### PR TITLE
Fix accidental type inference in array coercion

### LINKED ISSUE #136420: Rust fails to coerce to a fn pointer when passing an array as an argument to a generic function.
I tried this code:

```rust
fn foo() {}
fn bar() {}

fn main() {
    let _a = vec![foo, bar];
    let _b = [foo, bar];
    c(vec![foo, bar]);
    d([foo, bar]);
}

fn c<T>(_: Vec<T>) {}
fn d<T>(_: [T; 2]) {}
```

I expected the four lines to either all compile or all error. Instead, only the `d([foo, bar])` line fails, with the following error:

```
error[E0308]: mismatched types
  --> src/main.rs:8:7
   |
8  |     d([foo, bar]);
   |     - ^^^^^^^^^^ expected `[fn() {foo}; 2]`, found `[fn(); 2]`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected array `[fn() {foo}; 2]`
              found array `[fn(); 2]`
note: function defined here
  --> src/main.rs:12:4
   |
12 | fn d<T>(_: [T; 2]) {}
   |    ^    ---------

For more information about this error, try `rustc --explain E0308`.
```

For some reason, it's failing to coerce the function items into function pointers, but only when an array is being passed to a generic function.

Discovered by @xero-lib

### Meta

Issue reproducible on the playground with stable rust 1.84.1, and nightly rust `1.86.0-nightly (2025-02-01 8239a37f9c0951a037cf)`

@rustbot labels +A-inference +A-coercions

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes rust-lang/rust#136420.

If the expectation of array element is a type variable, we should avoid resolving it to the first element's type and wait until LUB coercion is completed.
We create a free type variable instead which is only used in this `CoerceMany`.

[`check_expr_match`](https://github.com/rust-lang/rust/blob/847e3ee6b0e614937eee4e6d8f61094411eadcc0/compiler/rustc_hir_typeck/src/_match.rs#L72) and [`check_expr_if`](https://github.com/rust-lang/rust/blob/847e3ee6b0e614937eee4e6d8f61094411eadcc0/compiler/rustc_hir_typeck/src/expr.rs#L1329) where `CoerceMany` is also used do the [same](https://github.com/rust-lang/rust/blob/847e3ee6b0e614937eee4e6d8f61094411eadcc0/compiler/rustc_hir_typeck/src/expectation.rs#L50). 

### Remaining inconsistency with `if` and `match`(rust-lang/rust#145048):
The typeck of array always uses the element coercion target type as the expectation of element exprs while `if` and `match` use `NoExpectation` if the expected type is an infer var.
This causes that array doesn't support nested coercion. 
```rust
fn foo() {}
fn bar() {}
fn main() {
    let _ =  [foo, if false { bar } else { foo }]; // type mismatch when trying to coerce `bar` into `foo` in if-then branch coercion.
}
```
But we can't simply change this behavior to be the same as `if` and `match` since [many code](https://github.com/rust-lang/rust/pull/140283#issuecomment-3190564399) depends on using the first element's type as expectation.

### CODE REVIEW

**Review by jieyouxu — CHANGES_REQUESTED** [review]
Please add a test to demonstrate the effect of this change. Especially since with this change, we would be accepting more code than on `master` (this is the snippet in the original issue):

```rs
fn foo() {}
fn bar() {}

fn main() {
    let _a = if true { foo } else { bar };
    let _b = vec![foo, bar];
    let _c = [foo, bar];
    d(if true { foo } else { bar });
    e(vec![foo, bar]);
    f([foo, bar]);  // <- this PR now accepts this
}

fn d<T>(_: T) {}
fn e<T>(_: Vec<T>) {}
fn f<T>(_: [T; 2]) {}
```

whereas on `master` this snippet does not compile w/

```
error[E0308]: mismatched types
  --> src/main.rs:10:7
   |
10 |     f([foo, bar]);
   |     - ^^^^^^^^^^ expected `[fn() {foo}; 2]`, found `[fn(); 2]`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected array `[fn() {foo}; 2]`
              found array `[fn(); 2]`
note: function defined here
  --> src/main.rs:15:4
   |
15 | fn f<T>(_: [T; 2]) {}
   |    ^    ---------

For more information about this error, try `rustc --explain E0308`.
```

I'm surprised there are no ui test diffs.

**Comment by adwinwhite** [comment]
There're some similar errors, but I'm unsure whether it's okay to allow these code. [The Rust Reference](https://doc.rust-lang.org/stable/reference/type-coercions.html?#least-upper-bound-coercions).

```rust
fn foo() {}
fn bar() {}

fn main() {
    let block_var = 'a: { // Easy to fix, but not specified by the Rust Reference.
        if false {
            break 'a foo;
        }
        break 'a bar;
    };

    let loop_var = loop {  // Easy to fix, but not specified by the Rust Reference.
        if false {
            break foo;
        }
        break bar;
    };

    let closure_var = || { // More complicated. But this should work according to the Rust Reference.
        if false {
            return foo;
        }
        return bar;
    };
}
```

File: compiler/rustc_hir_typeck/src/expectation.rs [hunk 1]
```diff
@@ -113,7 +113,12 @@ impl<'a, 'tcx> Expectation<'tcx> {
 
     /// Like `only_has_type`, but instead of returning `None` if no
     /// hard constraint exists, creates a fresh type variable.
+    /// Also avoid using the original type variable as the target, as it may resolve prematurely
+    /// during the first coercion in `CoerceMany`, rather than deferring to the final coerced type.
     pub(super) fn coercion_target_type(self, fcx: &FnCtxt<'a, 'tcx>, span: Span) -> Ty<'tcx> {
```
Comment (adwinwhite) [inline compiler/rustc_hir_typeck/src/expectation.rs:118]: This method is only used with `CoerceMany` in *loop*, *block* and *if* coercions.

**Comment by adwinwhite** [comment]
Turns out the ‘easy’ cases aren’t so easy after all. I can't fix the inference regressions for now, but I might revisit them later once I understand type inference better.

**Comment by oli-obk** [comment]
I am not going to get to this in the next 10 days. I'll need to review the general state of inference here and write a T-types FCP text

**Comment by oli-obk** [comment]
Array expressions normally lub their element expressions' types to ensure that things like `[5, 5_u8]` work and don't result in type mismatches. When invoking a generic function `fn foo<T>(_: [T; N])` with an array expression, we end up with an infer var for the element type of the array in the signature. So when typecking the first array element we compare its type with the infer var and thus subsequently require all other elements to be the same type.

This PR changes that to instead fall back to "not knowing" that the argument type is array of infer var, but just having an infer var for the entire argument. Thus we typeck the array expression normally, lubbing the element expressions, and then in the end comparing the array expression's type with the array of infer var type.

Things like

```rust
fn foo() {}
fn bar() {} 
fn f<T>(_: [T; 2]) {}

f([foo, bar]);
```

and


```rust
struct Foo;
struct Bar;
trait Trait {}
impl Trait for Foo {}
impl Trait for Bar {} 
fn f<T>(_: [T; 2]) {}

f([&Foo, &Bar as &dyn Trait]);
```

@rfcbot merge

**Review by lcnr — COMMENTED** [review]
this breaks
```rust
fn foo<F: FnOnce(&str) -> usize, const N: usize>(x: [F; N]) {}

fn main() {
    foo([|s| s.len()])
}
```
This doesn't rly matter though, as `[|s| s.len(), |s| s.trim().len()]` errors with a coercion failure :3

This PR got me to look more deeply at `CoerceMany`. We already have this hack for `match` and `if` https://github.com/rust-lang/rust/blob/c68032fd4c442d275f4daa571ba19c076106b490/compiler/rustc_hir_typeck/src/expectation.rs#L38-L54

Even so, this is insufficient:
```rust
fn foo() {}
fn bar() {}

fn mk<T>() -> T { todo!() }

fn main() {
    let mut x = (mk(),);
    x = match false {
        true => (foo,),
        false => (bar,),
    }
}
```
Here we use the expected type `(?x,)` which then gets equated to the type of the first branch.

As a more general fix and something which should fix pretty much all cases where these sorts of coercions go wrong, could we instead hcange `CoerceMany::make` to fold the expected type and replace all infer vars with fresh new ones? Now, this also breaks some code, notably this weakens `deduce_closure_signature`. However, given that closures in such matches aren't supported anyways once they are in more than one branch, this feels like a more general and more desirable fix

**Comment by compiler-errors** [comment]
should we crater this too?

@bors2 try

**Comment by adwinwhite** [comment]
> As a more general fix and something which should fix pretty much all cases where these sorts of coercions go wrong, could we instead hcange `CoerceMany::make` to fold the expected type and replace all infer vars with fresh new ones? Now, this also breaks some code, notably this weakens `deduce_closure_signature`. However, given that closures in such matches aren't supported anyways once they are in more than one branch, this feels like a more general and more desirable fix

I tried this at first, but it resulted in too many errors. I think one reason is that constraints on the old inference variables are missing when we create fresh ones.

**Comment by lcnr** [comment]
> I tried this at first, but it resulted in too many errors. 

Can you share an example snippet which failed? I would assume that we still constrain the original variable when we actually equate the returned type in the parent.

**Comment by adwinwhite** [comment]
[This](https://github.com/adwinwhite/rust/commit/9e6142963b380392c7abd2b4826d420aced5371a) is how I fold the type vars in `CoerceMany`. 
<details>
  <summary>Failed ui tests (Some diagnostics changes are excluded)</summary>

- tests/ui/drop/lint-tail-expr-drop-order-borrowck.rs
- tests/ui/coroutine/type-mismatch-error.rs
- tests/ui/closures/issue-78720.rs
- tests/ui/coroutine/type-mismatch-signature-deduction.rs
- tests/ui/coercion/coerce-unify.rs
- tests/ui/expr/if/if-else-type-mismatch.rs
- tests/ui/impl-trait/ice-unexpected-param-type-whensubstituting-in-region-112823.rs#next
- tests/ui/lazy-type-alias-impl-trait/branches3.rs
- tests/ui/never_type/fallback-closure-ret.rs#fallback
- tests/ui/impl-trait/point-to-type-err-cause-on-impl-trait-return.rs
- tests/ui/type-alias-impl-trait/closures_in_branches.rs
- tests/ui/suggestions/if-then-neeing-semi.rs
- tests/ui/suggestions/return-bindings.rs
- tests/ui/type-alias-impl-trait/issue-84660-unsoundness.rs#next
- tests/ui/weird-exprs.rs

</details>

Pick one example, `coerce-unify.rs`.
```rust
pub fn main() {
    let s = String::from("bar");
    let _ = [("a", Default::default()), (Default::default(), "b"), (&s, &s)];
}
```
Its compilation error:
```log
error[E0308]: mismatched types
 --> coerce-unify.rs:3:68
  |
3 |     let _ = [("a", Default::default()), (Default::default(), "b"), (&s, &s)];
  |                                                                    ^^^^^^^^ expected `(&str, &str)`, found `(&String, &String)`
  |
  = note: expected tuple `(&str, &str)`
             found tuple `(&String, &String)`
```
Let's call the expectation type var in `check_expr_array` arguments `?external`.

Before the change, `?external` obtains additional constraints as it's used in the first two tuples' coercions so that when typecking the third tuple, `?external` is known to be `(&str, &str)` and the `&String -> &str` coercion is done in `check_expr_tuple`. Then the `(&str, &str) -> (&str, &str)` in `CoerceMany` is easy.

After the change, `?external` is not affected by the coercions and remains unknown. So the `&String -> &str` coercion doesn't happen during typecking the third tuple and now we have `(&String, &String) -> (&str, &str)` in `CoerceMany` which it doens't handle.

**Comment by lcnr** [comment]
this is surprising to me :thinking: while the expected type in `check_expr_array` starts out as an infer var, shouldn't we replace it with a new one at the start of coercion which then also gets constrained to `(&str, &str)` before we get to the last branch.

Is the issue here that in the `pushed == 0` case u map the `expected_ty` but don't actually replace `self.expected_ty`, so accessing that field again uses the old infer vars again?

Ah no, the issue is that you're updating the `expected_ty` too late, you need the same "fudged" type as the expected type of the coercion and as the `coerce_to` here https://github.com/rust-lang/rust/blob/40daf23eeb711dadf140b2536e67e3ff4c999196/compiler/rustc_hir_typeck/src/expr.rs#L1794-L1797

**Comment by adwinwhite** [comment]
Ah, you're right. I should do the replacement right before `CoerceMany` construction to avoid unnecessary intermediate type vars and use the new `expected_ty` as expectation to guide type inference. 
This change make some failed tests compile again. Let me look into the rest.

**Comment by adwinwhite** [comment]
By now, I think using type variable to guide elements' type inference is an accident. 
Although the following works, it's quite brittle.
```rust
pub fn main() {
    let s = String::from("bar");
    let _ = [("a", Default::default()), (Default::default(), "b"), (&s, &s)]; // compiles.
}
```
Since the type variable is always unified with the first expr's type, it can be a wrong expectation for the remaining expressions.
```rust
fn foo() {}
fn bar() {}
fn main() {
    let _ =  [foo, if false { bar } else { foo }]; // type mismatch when trying to coerce `bar` into `foo`.
}
```
On the contrary, `if` doesn't guide inference but gets typecking right.
```rust
pub fn main() {
    let s = String::from("bar");
    let _ = if false { // `if` uses `NoExpectation` for typecking when the expected_ty is a type variable.
        ("a", Default::default())
    } else if false {
        (Default::default(), "b")
    } else {
        (&s, &s) // incompatible types: expected `(_, &str)`, found `(&String, &String)`
    };
}
```
```rust
fn foo() {}
fn bar() {}
fn main() {
    let _ = if false { // compiles.
        foo
    } else {
        if false {
            bar
        } else {
            foo
        }
    };
}
```


As for mentioned tuple coercion support, 
```rust
fn foo() {}
fn bar() {}

fn mk<T>() -> T { todo!() }

fn main() {
    let mut x = (mk(),);
    x = match false {
        true => (foo,),
        false => (bar,),
    }
}
```
it's a non-trivial task. Tuples can be nested arbitrarily. As we try to refine the LUB type at each new coercion site, we need to apply adjustments to each field of previous expressions recursively. This seems to complicate coercion a lot.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 2]
```diff
@@ -1760,7 +1760,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             let coerce_to = expected
                 .to_option(self)
                 .and_then(|uty| match *self.try_structurally_resolve_type(expr.span, uty).kind() {
-                    ty::Array(ty, _) | ty::Slice(ty) => Some(ty),
+                    // Avoid using a type variable as the coerce_to type, as it may resolve
+                    // during the first coercion instead of being based on the common type.
+                    ty::Array(ty, _) | ty::Slice(ty) if !ty.is_ty_var() => Some(ty),
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs]: u need to structurally resolve the `ty` again before this check :thinking: `try_structurally_resolve_type` only structurally resolves the outermost type constructor

**Comment by lcnr** [comment]
hmm, I don't feel like I've got a good grasp of the way this works rn (and it's definitely not in cache for me rn)

I do think treating array expressions teh same as `if` and `match` is better than the status quo however and I think I agree with you after thinking about it for a while, I am not yet totally confident that there does not exist a nice and more powerful alternative here.

@rfcbot fcp reviewed

**Comment by adwinwhite** [comment]
Filed a separate issue #145048 to track the nested coercion bug.

**Comment by lcnr** [comment]
ah wait, can you actually try to perfectly match the if/match behavior :thinking: it feels weird to weaken inference without going all the way here.

We can crater and look at the actual regressions in the wild

**Comment by lcnr** [comment]
@rfcbot concern try going all the way, no expectation

**Comment by adwinwhite** [comment]
The first error:
```log
error[E0308]: mismatched types
     --> compiler/rustc_metadata/src/locator.rs:435:17
      |
  435 |                 (dylib_prefix, dylib_suffix, CrateFlavor::Dylib),
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `(&str, &str, CrateFlavor)`, found `(&String, &Cow<'_, str>, CrateFlavor)`
      |
      = note: expected tuple `(&str, &str, CrateFlavor)`
                 found tuple `(&std::string::String, &Cow<'_, str>, CrateFlavor)`
```
Source:
https://github.com/rust-lang/rust/blob/3507a749b365aae4eefa96ab700a9315d3280ee7/compiler/rustc_metadata/src/locator.rs#L432-L435

Trying to build stage2 compiler locally:
```log
error[E0308]: mismatched types
   --> /home/adwin/.cargo/registry/src/crates.io-xxxxxxxx/tracing-log-0.2.0/src/lib.rs:187:17
    |
187 |                 (&keys.target, Some(&record.target())),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `(&Field, Option<&dyn Value>)`, found `(&Field, Option<&&str>)`
    |
```
Source: https://docs.rs/crate/tracing-log/latest/source/src/lib.rs#185-187

I guess there's a large amount of code depending on the first tuple's type as typeck expectation.

**Comment by lcnr** [comment]
that's tragic :/ alright.

@rustbot resolve concern try going all the way, no expectation

I edited the PR description to contain the FCP proposal + additional context

**Comment by jackh726** [comment]
Would it be possible/desired to add a FCW for the "all the way" case?

File: tests/ui/coercion/coerce-many-with-ty-var.rs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    let _ = match false {
+        true => foo,
+        false => bar,
+    };
+    infer(match false {
+        true => foo,
+        false => bar,
+    });
+
+
```
Comment (lcnr) [inline tests/ui/coercion/coerce-many-with-ty-var.rs]:
```suggestion
```

**Comment by lcnr** [comment]
please add the following as a test
```rust
fn foo<F: FnOnce(&str) -> usize, const N: usize>(x: [F; N]) {}

fn main() {
    foo([|s| s.len()])
}
```

**Comment by BoxyUwU** [comment]
@craterbot check

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 4]
```diff
@@ -1817,11 +1817,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 .unwrap_or_else(|| self.next_ty_var(expr.span));
             let mut coerce = CoerceMany::with_coercion_sites(coerce_to, args);
             assert_eq!(self.diverges.get(), Diverges::Maybe);
             for e in args {
+                // FIXME: the element expectation should use
+                // `try_structurally_resolve_and_adjust_for_branches` just like in `if` and `match`.
+                // While that fixes nested coercion, it will break [some
+                // code like this](https://github.com/rust-lang/rust/pull/140283#issuecomment-2958776528).
+                // If we find a way to support recursive tuple coercion, this break can be avoided.
                 let e_ty = self.check_expr_with_hint(e, coerce_to);
```
Comment (BoxyUwU) [inline compiler/rustc_hir_typeck/src/expr.rs:1689]: This feels somewhat weird :thinking: I would expect we use `coerce.merged_ty()` here to typeck each element with an expectation of the currently known coerce-LUB'd type of the array element, rather than whatever the first element happend to have the type of.

Not sure of a test where this would actually matter.

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 5]
```diff
@@ -1817,11 +1817,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        .builtin_index()
+                        // Avoid using the original type variable as the coerce_to type, as it may resolve
+                        // during the first coercion instead of being the LUB type.
+                        .filter(|t| !self.try_structurally_resolve_type(expr.span, *t).is_ty_var())
+                })
                 .unwrap_or_else(|| self.next_ty_var(expr.span));
             let mut coerce = CoerceMany::with_coercion_sites(coerce_to, args);
             assert_eq!(self.diverges.get(), Diverges::Maybe);
             for e in args {
+                // FIXME: the element expectation should use
```
Comment (BoxyUwU) [inline compiler/rustc_hir_typeck/src/expr.rs:1684]: I don't understand this FIXME :thinking: If we have an expected type of some infer var and we turn that into NoExpectation that ought to only affect closure signature inference, or if we were to be able to make inference progress and resolve it to more than just an infer var :thinking: 

Both of those cases ought to already be broken under this PR in a lot of cases though. It also seems like the examples that broke didn't actually care about either of those things.

Reading further it sounds like the original impl was wrong? Would like to see this comment updated with more of an explanation of what went wrong here.

Comment (adwinwhite) [reply compiler/rustc_hir_typeck/src/expr.rs:1684]: This FIXME is about [this issue](https://github.com/rust-lang/rust/issues/145048). 
To make array coercion consistent with `if` and `match`, we ought not to use ty var as expectation here.
But a lot of code already depends on the behavior that ty var expectation gets resolved in `CoerceMany` thus it can guide array element's typeck. E.g. the example in my linked comment and [others](https://github.com/rust-lang/rust/pull/140283#issuecomment-3190564399).
This comment isn't out of sync with the code. Perhaps I should word it better or omit it to avoid confusion.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 4 above)
Comment (adwinwhite) [reply compiler/rustc_hir_typeck/src/expr.rs:1689]: Yeah, `coerce.merged_ty()` is better than the first element's type. 
But it's still best effort. We can only know the **true** LUB type after all typeck is done, not before.

It may introduce the problem that adjusted types of array elements are not the same since `merged_ty()` can change gradually.

Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/expr.rs:1689]: Yeah :+1: My thoughts here is that we've already given up on having the expected type stay the same across branches. If we wanted this we'd do what match/if do and use the original expectation adjusted for branches for each expr we check.

Instead here we're accepting that we *need* the expectation to change across element expressions as too much code relies on that happening in order to have nested coercions work properly. From this POV using the (in progress) LUB type seems more principled than the type of the first element's expression.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 5 above)
Comment (BoxyUwU) [reply compiler/rustc_hir_typeck/src/expr.rs:1684]: Hmm, what i don't understand is why using the `try_structurally_resolve_and_adjust_for_branches` function would break anything. That should only affect the case where we have an unconstrained infer var, but the case we care about supporting is one where that variable has been inferred to some type like `fn(...)` in which case we wouldn't replace the expectation with `NoExpectation`.

I agree that as the `CoerceMany` "makes progress" we need to propagate that information into the expectation of the element expressions as otherwise nested coercions will fail.

Did you try to implement this previously and found it broke stuff, do you still have that impl around for me to look at?

Comment (adwinwhite) [reply compiler/rustc_hir_typeck/src/expr.rs:1684]: It can break code like this,
```rust
pub fn main() {
    let s = String::from("bar");
    let _ = [("a", Default::default()), (Default::default(), "b"), (&s, &s)];
}
```
Currently we're using an infer var as expectation for array element. With coercions of the first two elements, the infer var is known to be `(&str, &str)` so it can guide the typeck of the third element, specifically the tuple coercion `(&String, &String) -> (&str, &str)`.

If we use `try_structurally_resolve_and_adjust_for_branches`, the third element would have `NoExpectation` as expectation and its typeck result would be `(&String, &String)` which can't be coerced into or from `(&str, &str)` in `CoerceMany`.

The key point is that field-wise tuple coercion is supported in typeck but not in `CoerceMany`.

[This branch](https://github.com/rust-lang/rust/compare/master...adwinwhite:rust:consistent-coerce-many-for-array) breaks the code above, but fixes #145048.

File: compiler/rustc_hir_typeck/src/expr.rs (hunk 4 above)
Comment (adwinwhite) [reply compiler/rustc_hir_typeck/src/expr.rs:1689]: Just replaced `coerce_to` with `merged_ty()` and it doesn't break any ui test.
The adjusted types are not a concern since all exprs are always adjusted according to the latest `merged_ty()` so they'll have the same type.
This change should enhance something. I just can't come up with an example.

**Comment by adwinwhite** [comment]
Yeah, this is an inherent problem of `CoerceMany`. loop/block/ret all have this kind of bug.
See [my comment](https://github.com/rust-lang/rust/pull/140283#issuecomment-2831799753) above for examples.
However they can't be fixed by the same trivial solution. There're some inference regressions.

**Comment by RalfJung** [comment]
This kind of logic already seems to apply for arrays in some situations, but it's fragile and changing the code a bit breaks it... so it seems like this mostly makes the array treatment more consistent?
That's why we ran into it in https://github.com/rust-lang/rust/pull/148190, where currently it's not just possible to refactor the `vec!` macro to be less special because changing it in any way whatsoever breaks type inference.

**Comment by jackh726** [comment]
> I think that was previously tried upthread somewhere and it broke a lot of stuff

I don't think the specific variant I am suggesting (checking if `coerce_to` contains any inference variable) has been checked, only with the `try_structurally_resolve_and_adjust_for_branches` call, which removes *any* expectation if `coerce_to` is an infer var. This is both stronger (because of `NoExpectation` but also weaker `because of `is_ty_var()`).

**Comment by adwinwhite** [comment]
```rust
    let _: Vec<Box<dyn Fn(isize) -> _>> = vec![
        Box::new(|x| (x as u8)),
        Box::new(|x| (x as i16 as u8)),
    ];
```
This fails with log:
```log
error[E0308]: mismatched types
  --> /home/adwin/Code/rust/rust/base/tests/ui/coercion/coerce-expect-unsized.rs:39:43
   |
LL |       let _: Vec<Box<dyn Fn(isize) -> _>> = vec![
   |  ___________________________________________^
LL | |         Box::new(|x| (x as u8)),
   | |                  --- the found closure
LL | |         Box::new(|x| (x as i16 as u8)),
LL | |     ];
   | |     ^
   | |     |
   | |_____expected `Box<[Box<dyn Fn(isize) -> _>]>`, found `Box<[Box<{closure@...}>; 2]>`
   |       arguments to this function are incorrect
```

**Comment by jackh726** [comment]
Alright, so, I'm good to land the PR as-is, and it's been FCPed. Can you rebase?
