### PR TITLE
macros: fix partially consumed tokens in macro matchers

### LINKED ISSUE #37175: <$t:ty> falls victim to C++ >> ambiguity
Consider this macro:

```rust
macro_rules! m { (<$t:ty>) => { stringify!($t) } }
```

Unfortunately it can't deal with a type that ends in `>`:

```rust
m!(<Vec<i32>>)
```

```
error: no rules expected the token `>>`
 --> .cargo/.cargo/script-cache/expr-edcce559d98013ba/expr.rs:5:64
  |
5 | {macro_rules! m { (<$t:ty>) => { stringify!($t) } } m!(<Vec<i32>>)}
  |                                                                ^^

error: Could not compile `expr`.
```

Is it possible to fix this? It seems to me the macro parser should know it's parsing `$t:ty` and therefore `>>` can't be valid, so it should be split into two tokens.

cc @jseyfried

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #37175.

This PR also avoids re-transcribing the tokens consumed by a matcher (and cloning the `TtReader` once per matcher), which improves expansion performance of the test case from #34630 by ~8%.

r? @nrc

### CODE REVIEW

File: src/libsyntax/ext/tt/macro_parser.rs [hunk 1]
```diff
@@ -476,24 +476,21 @@ pub fn parse(sess: &ParseSess,
...
+                    let mut rust_parser = Parser::new(sess, cfg.clone(), Box::new(&mut rdr));
+                    let mut ei = bb_eis.pop().unwrap();
+                    if let TokenTree::Token(span, MatchNt(_, ident)) = ei.top_elts.get_tt(ei.idx) {
                         let match_cur = ei.match_cur;
                         (&mut ei.matches[match_cur]).push(Rc::new(MatchedNonterminal(
                             parse_nt(&mut rust_parser, span, &ident.name.as_str()))));
                         ei.idx += 1;
                         ei.match_cur += 1;
+                    } else {
+                        panic!()
```
Comment (nrc) [inline src/libsyntax/ext/tt/macro_parser.rs]: nit: this panic should be unreachable (it might be better though to encapsulate this on the token tree somewhere, rather than doing it here.

**Comment by nrc** [comment]
r+ with the nit addressed

File: src/libsyntax/ext/tt/macro_parser.rs (hunk 1 above)
Comment (jseyfried) [inline src/libsyntax/ext/tt/macro_parser.rs]: Changed to `unreachable!()`.
