### PR TITLE
Issue 81508 fix

### LINKED ISSUE #81508: Confusing diagnostic when improperly using constant as type.
The following code...
```rust
#[allow(non_upper_case_globals)]
pub const Foo: &str = "";

mod submod {
    use super::Foo;
    fn function() {
        println!("{}", Foo::Bar);
    }
}
```

...yields the following error and warning:

```
error[E0433]: failed to resolve: use of undeclared type `Foo`
 --> src/lib.rs:7:24
  |
7 |         println!("{}", Foo::Bar);
  |                        ^^^ use of undeclared type `Foo`

warning: unused import: `super::Foo`
 --> src/lib.rs:5:9
  |
5 |     use super::Foo;
  |         ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

The warning says that `Foo` is not used but it clearly is, just not properly. This error is normally easier to spot when using the proper casing for constants, but that might not always be the case. Perhaps in this instance, we should look for other items with the exact same name and point out that the user is trying to use a constant as a type.

### PR DESCRIPTION
**Pull request by kwj2104**
Fix #81508

**Problem**: When variable name is used incorrectly as path, error and warning point to undeclared/unused name, when in fact the name is used, just incorrectly (should be used as a variable, not part of a path). 

**Summary for fix**: When path resolution errs, diagnostics checks for variables in ```ValueNS``` that have the same name (e.g., variable rather than path named Foo), and adds additional suggestion that user may actually intend to use the variable name rather than a path. 

The fix does not suppress or otherwise change the *warning* that results. I did not find a straightforward way in the code to modify this, but would love to make changes here as well with any guidance.

### CODE REVIEW

File: compiler/rustc_resolve/src/lib.rs [hunk 1]
```diff
@@ -2386,7 +2388,29 @@ impl<'a> Resolver<'a> {
...
+                                        parent_scope,
+                                        None,
+                                        path_span,
+                                        &ribs.unwrap()[ValueNS],
+                                    )
+                                    .is_some()
+                            {
+                                suggestion = Some((
+                                    vec![(path_span, format!("{}", ident))],
+                                    String::from("try using variable instead of path"),
```
Comment (JohnTitor) [inline compiler/rustc_resolve/src/lib.rs:2408]: IMO:

```suggestion
                                    String::from("try using the similarly named variable instead"),
```

**Review by JohnTitor — COMMENTED** [review]
Also, could you rebase instead of merging as per https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy?

**Comment by JohnTitor** [comment]
Okay, thanks for rebasing, the last thing I'd like to ask is to squash commits into one, could you?

File: src/test/ui/resolve/issue-81508.stderr [hunk 2]
```diff
@@ -0,0 +1,12 @@
+error[E0433]: failed to resolve: use of undeclared type `Foo`
+  --> $DIR/issue-81508.rs:15:24
+   |
+LL |         println!("{}", Foo::Bar);
+   |                        ^^^-----
+   |                        |
+   |                        use of undeclared type `Foo`
+   |                        help: try using the similarly named variable instead: `Foo`
```
Comment (varkor) [inline src/test/ui/resolve/issue-81508.stderr:8]: I think this message is confusing, because it seems to suggest using `Foo`, which the user is already doing. I think we should instead point to the declaration of `Foo` and say something like:
```
`Foo` is defined here, but is not a type
```

Comment (varkor) [reply src/test/ui/resolve/issue-81508.stderr:8]: @kwj2104: yes, that looks like the sort of thing I had in mind!

Comment (kwj2104) [reply src/test/ui/resolve/issue-81508.stderr]: New format for errors now points to declaration line: 

```
error[E0433]: failed to resolve: use of undeclared type `Baz`
  --> $DIR/issue-81508.rs:11:20
   |
LL |     let Baz: &str = "";
   |         --- help: Baz is defined here, but is not a type
LL | 
LL |     println!("{}", Baz::Bar);
   |                    ^^^ use of undeclared type `Baz`
```

File: compiler/rustc_resolve/src/lib.rs [hunk 3]
```diff
@@ -1909,17 +1912,19 @@ impl<'a> Resolver<'a> {
                 return Some(LexicalScopeBinding::Item(binding));
             }
         }
+        let returned_item = self
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:1915]: This change seems unnecessary.

File: compiler/rustc_resolve/src/lib.rs [hunk 4]
```diff
@@ -884,6 +884,10 @@ pub struct Resolver<'a> {
     /// "self-confirming" import resolutions during import validation.
     unusable_binding: Option<&'a NameBinding<'a>>,
 
+    // Spans for local variables found during resolution
+    // Used for suggestions during error reporting
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:888]:
```suggestion
    // Spans for local variables found during resolution.
    // Used for suggestions during error reporting.
```

File: compiler/rustc_resolve/src/late.rs [hunk 5]
```diff
@@ -1597,6 +1596,7 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
                         .try_resolve_as_non_binding(pat_src, pat, bmode, ident, has_sub)
                         .unwrap_or_else(|| self.fresh_binding(ident, pat.id, pat_src, bindings));
                     self.r.record_partial_res(pat.id, PartialRes::new(res));
+                    self.r.record_local_span(pat.id, pat.span);
```
Comment (varkor) [inline compiler/rustc_resolve/src/late.rs:1599]: Instead of `local_span`, I think `pat_span` would be more descriptive.

File: compiler/rustc_resolve/src/lib.rs [hunk 6]
```diff
@@ -1879,7 +1884,6 @@ impl<'a> Resolver<'a> {
                     ribs,
                 )));
             }
-
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:1882]: I don't think these needed to change.

File: compiler/rustc_resolve/src/lib.rs [hunk 7]
```diff
@@ -2386,7 +2391,40 @@ impl<'a> Resolver<'a> {
...
+                                        }
+                                        LexicalScopeBinding::Item(name_binding) => {
+                                            match_span = Some(name_binding.span);
+                                        }
+                                        _ => (),
+                                    };
+                                    if let Some(span) = match_span {
+                                        suggestion = Some((
+                                            vec![(span, String::from(""))],
+                                            format!("{} is defined here, but is not a type", ident),
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:2420]:
```suggestion
                                            format!("`{}` is defined here, but is not a type", ident),
```

File: compiler/rustc_resolve/src/lib.rs [hunk 8]
```diff
@@ -2386,7 +2391,40 @@ impl<'a> Resolver<'a> {
                             .next()
                             .map_or(false, |c| c.is_ascii_uppercase())
                         {
-                            (format!("use of undeclared type `{}`", ident), None)
+                            // Add check case for similarly named item in alternative namespace
+                            let mut suggestion = None;
+
+                            if ribs.is_some() {
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:2397]:
```suggestion
                            let suggestion = if ribs.is_some() {
```
(and then return `Some(...)` or `None` inside the `match`)

File: compiler/rustc_resolve/src/lib.rs [hunk 9]
```diff
@@ -2386,7 +2391,40 @@ impl<'a> Resolver<'a> {
...
+                                    ident,
+                                    ValueNS,
+                                    parent_scope,
+                                    None,
+                                    path_span,
+                                    &ribs.unwrap()[ValueNS],
+                                ) {
+                                    let mut match_span: Option<Span> = None;
+                                    match res {
+                                        LexicalScopeBinding::Res(Res::Local(id)) => {
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:2408]: To help future readers, could you give an example above each arm (i.e. `Res::Local` or `LexicalScopeBinding::Item`) describing what kind of case each one deals with?

File: compiler/rustc_resolve/src/lib.rs [hunk 10]
```diff
@@ -2386,7 +2391,40 @@ impl<'a> Resolver<'a> {
...
+                                if let Some(res) = self.resolve_ident_in_lexical_scope(
+                                    ident,
+                                    ValueNS,
+                                    parent_scope,
+                                    None,
+                                    path_span,
+                                    &ribs.unwrap()[ValueNS],
+                                ) {
+                                    let mut match_span: Option<Span> = None;
+                                    match res {
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:2407]:
```suggestion
                                    let match_span = match res {
```
(same here)

File: compiler/rustc_resolve/src/lib.rs [hunk 11]
```diff
@@ -2386,7 +2391,40 @@ impl<'a> Resolver<'a> {
                             .next()
                             .map_or(false, |c| c.is_ascii_uppercase())
                         {
-                            (format!("use of undeclared type `{}`", ident), None)
+                            // Add check case for similarly named item in alternative namespace
```
Comment (varkor) [inline compiler/rustc_resolve/src/lib.rs:2394]:
```suggestion
                            // Check whether the name refers to an item in the value namespace.
```

**Review by varkor — COMMENTED** [review]
This is looking pretty good now! Most of my comments are very minor.

**Comment by varkor** [comment]
Thanks @kwj2104: this looks great!

@bors r+
