### PR TITLE
Make target-cpu=native detect individual features

### LINKED ISSUE #38218: SIGILL in the binary compiled with `-C target-cpu=native` on the latest nightly
I'm trying to build ripgrep with its SIMD optimizations on, and on Archlinux this means that ripgrep is compiled as follows:
```
% RUSTFLAGS="-C target-cpu=native" cargo build --release --features simd-accel
```
However, the build fails with the following error:
```
% RUSTFLAGS="-C target-cpu=native" cargo build --release --features simd-accel
   Compiling winapi-build v0.1.1
   Compiling fnv v1.0.5
   Compiling crossbeam v0.2.10
   Compiling ansi_term v0.9.0
   Compiling utf8-ranges v0.1.3
   Compiling winapi v0.2.8
   Compiling vec_map v0.6.0
   Compiling log v0.3.6
   Compiling void v1.0.2
   Compiling libc v0.2.18
   Compiling unreachable v0.1.1
   Compiling bitflags v0.7.0
   Compiling unicode-segmentation v0.1.3
   Compiling strsim v0.5.2
   Compiling unicode-width v0.1.3
   Compiling walkdir v1.0.3
   Compiling term_size v0.2.1
   Compiling thread-id v3.0.0
   Compiling regex-syntax v0.3.9
   Compiling thread_local v0.3.0
   Compiling termcolor v0.1.1 (file:///tmp/yaourt-tmp-netvl/aur-ripgrep-git/src/ripgrep-git/termcolor)
   Compiling clap v2.18.0
   Compiling memmap v0.5.0
   Compiling simd v0.1.1
   Compiling kernel32-sys v0.2.2
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `kernel32-sys v0.2.2`
process didn't exit successfully: `/tmp/yaourt-tmp-netvl/aur-ripgrep-git/src/ripgrep-git/target/release/build/kernel32-sys-f1c920c4b0efc1c4/build-script-build` (signal: 4, SIGILL: illegal instruction)
```

I tried checking out the appropriate commit in the winapi-rs repo where kernel32-sys 0.2.2 is available, and was able to reproduce this problem directly with the kernel32-sys crate:
```
% git clone https://github.com/retep998/winapi-rs
% cd winapi-rs
% git checkout 00ba888
% cd lib/kernel32
% RUSTFLAGS="-C target-cpu=native" cargo build --release
   Compiling winapi v0.2.8 (file:///tmp/winapi-rs)
   Compiling winapi-build v0.1.1 (file:///tmp/winapi-rs/build)
   Compiling kernel32-sys v0.2.2 (file:///tmp/winapi-rs/lib/kernel32)
error: failed to run custom build command for `kernel32-sys v0.2.2 (file:///tmp/winapi-rs/lib/kernel32)`
process didn't exit successfully: `/tmp/winapi-rs/lib/kernel32/target/release/build/kernel32-sys-70200ca6b7279963/build-script-build` (signal: 4, SIGILL: illegal instruction)
```

If I omit the RUSTFLAGS variable, everything compiles fine:
```
% cargo build --release                   
   Compiling winapi v0.2.8 (file:///tmp/winapi-rs)
   Compiling winapi-build v0.1.1 (file:///tmp/winapi-rs/build)
   Compiling kernel32-sys v0.2.2 (file:///tmp/winapi-rs/lib/kernel32)
    Finished release [optimized] target(s) in 0.91 secs
```

Compiler version:
```
% rustc -V
rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)
% cargo -V
cargo 0.16.0-nightly (built 2016-12-06)
```

Also, I'm running a Skylake i7 CPU, here is my /proc/cpuinfo, if it is relevant:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 78
model name	: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
stepping	: 3
microcode	: 0x9e
cpu MHz		: 3288.598
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		:
bogomips	: 5615.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 78
model name	: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
stepping	: 3
microcode	: 0x9e
cpu MHz		: 3320.043
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		:
bogomips	: 5621.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 78
model name	: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
stepping	: 3
microcode	: 0x9e
cpu MHz		: 3282.275
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		:
bogomips	: 5623.92
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 78
model name	: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
stepping	: 3
microcode	: 0x9e
cpu MHz		: 3326.367
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		:
bogomips	: 5622.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

### LINKED ISSUE #48464: Possible miscompilation of alacritty with -C target-cpu=native
Hello

I admit it is a bit hard to say where exactly the problem lies, but I think something in rustc *might* be to blame here. I first reported it to alacritty directly, but the more info I gather I think it might be here: https://github.com/jwilm/alacritty/issues/1122.

In short, on one of my computers, alacritty crashes with this panic on start:

```
thread 'main' panicked at 'capacity overflow', libcore/option.rs:917:5
stack backtrace:
   0:     0x55912e09fd73 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h5be622d6bae271e4
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55912e09e76d - std::panicking::default_hook::{{closure}}::h3dad42fd5277700a
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:380
   2:     0x55912e09d176 - std::panicking::rust_panic_with_hook::h17668d919cb963a0
                               at libstd/panicking.rs:396
                               at libstd/panicking.rs:576
   3:     0x55912e09cc02 - std::panicking::begin_panic::hc486239aa11674a1
                               at libstd/panicking.rs:537
   4:     0x55912e09cb79 - std::panicking::begin_panic_fmt::h2d2bb54c3df78ea1
                               at libstd/panicking.rs:521
   5:     0x55912e0b998a - core::panicking::panic_fmt::hee07a740495be6a3
                               at libstd/panicking.rs:497
   6:     0x55912e0c02a8 - core::option::expect_failed::h8c28a7270985f5ac
                               at libcore/option.rs:917
   7:     0x55912dec0e24 - <std::collections::hash::table::RawTable<K, V>>::new::h9be5b206095a0292
                               at /checkout/src/libcore/option.rs:302
                               at /checkout/src/libstd/collections/hash/table.rs:776
                               at /checkout/src/libstd/collections/hash/table.rs:816
   8:     0x55912deb825a - <std::collections::hash::map::HashMap<K, V, S>>::resize::hfcf2613f008e9ae5
                               at /checkout/src/libstd/collections/hash/map.rs:777
   9:     0x55912deb7fec - <std::collections::hash::map::HashMap<K, V, S>>::entry::h5422f5e504c51b41
                               at /checkout/src/libcore/cmp.rs:0
  10:     0x55912dea653b - alacritty::renderer::QuadRenderer::with_loader::hf63d8fc8d3d62172
                               at src/renderer/mod.rs:282
                               at src/renderer/mod.rs:214
                               at src/renderer/mod.rs:200
                               at src/display.rs:227
                               at src/renderer/mod.rs:686
  11:     0x55912ded5f4b - alacritty::display::Display::new::h18ace9deaccdd433
                               at src/display.rs:226
                               at src/display.rs:153
  12:     0x55912de09755 - alacritty::main::h023b5d1d018376be
                               at src/main.rs:104
                               at src/main.rs:62
  13:     0x55912e0f49f5 - std::rt::lang_start::{{closure}}::h924495c33c565557
                               at /checkout/src/libstd/rt.rs:74
  14:     0x55912de14f82 - main
  15:     0x7f30e925e010 - __libc_start_main
  16:     0x55912ddfaa39 - _start
  17:                0x0 - <unknown>
```

Further information:

* Works fine with stable.
* The last working nightly is nightly-2018-02-10, as provided by rustup.
* It is broken only on one of my computers and only when I compile it with `-C target-cpu=native`.

If I had to guess, I'd say it has something to do with switch to llvm 6.

Current nightly version info (still broken):

```
$ rustc --version --verbose
rustc 1.25.0-nightly (27a046e93 2018-02-18)
binary: rustc
commit-hash: 27a046e9338fb0455c33b13e8fe28da78212dedc
commit-date: 2018-02-18
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 6.0
```

I believe my `/proc/cpuinfo` is also relevant (it's some low-power celeron).

```
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 55
model name	: Intel(R) Celeron(R) CPU  N2940  @ 1.83GHz
stepping	: 8
microcode	: 0x829
cpu MHz		: 499.609
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 3666.91
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

Is there any other way I could narrow it down further, or anything more I could try?

### LINKED ISSUE #54688: target-cpu=native should also check all the target-features
Because LLVM doesn't know what `target-cpu=native` is, we currently [convert this to an actual CPU family name](https://github.com/rust-lang/rust/commit/1fd45a13dee17701fc0aeaa847c1919d485d09fd), relying on the [`llvm::sys::getHostCPUName`](http://llvm.org/doxygen/namespacellvm_1_1sys.html#a2e8cdc0e591685c9156af3d0d4fdae06) function. So if the current CPU's family is Haswell, we convert `target-cpu=native` to `target-cpu=haswell`.

As @EFanZh noticed [here](https://github.com/rust-lang/rust/issues/38218#issuecomment-424210340) and [here](https://github.com/rust-lang/rust/issues/48464), some Intel Pentiums belong to the Haswell microarch, but they lack AVX.

<hr/>

Here are the flags Clang generates for `-march=native`:

```sh
$ clang -E - -march=native -###
-target-cpu skylake -target-feature +sse2 -target-feature +cx16 -target-feature +sahf
...
-target-feature -avx512ifma -target-feature -avx512dq
```

Not only does it set the right `target-cpu` for optimization purposes, it actually manually enables / disables all the features available / not available on the host. This ensures no matter what the microarch is, only available features will be used.

<hr/>

We should probably use the [`llvm::sys::getHostCPUFeatures`](http://llvm.org/doxygen/namespacellvm_1_1sys.html#a4cdccbe62562aeff32fb137a042d5432) to manually get a list of supported target features. This is [what Clang does](https://github.com/llvm-mirror/clang/blob/024b9a4311cfd57ecb7f29d1138dc975fede4752/lib/Driver/ToolChains/Arch/X86.cpp#L116).

I think this issue will supersede both rust-lang/rust#38218 and rust-lang/rust#48464. If we can fix this, we will never generate code with unavailable target features.

Reproducing these errors is pretty hard, unless you have a machine with a Haswell Intel Pentium. 
I think it might be possible to reproduce this in QEMU with `-cpu Haswell,-avx`

### PR DESCRIPTION
**Pull request by as-com**
This PR makes target-cpu=native check for and enable/disable individual features instead of detecting and targeting a CPU by name. This brings the flag's behavior more in line with clang and gcc and ensures that the host actually supports each feature that we are compiling for. 

This should resolve issues with miscompilations on e.g. "Haswell" Pentiums and Celerons that lack support for AVX, and also enable support for `aes` on Broadwell processors that support it. It should also resolve issues with failing to detect feature support in newer CPUs that aren't yet known by LLVM (see: #80633).

Fixes #54688 
Fixes #48464
Fixes #38218

### CODE REVIEW

**Comment by nagisa** [comment]
r? @nagisa

This seems broadly LGTM, however I do have a concern with use of `std::detect` – in particular it only supports a few specific architectures (`x86`, `x86_64`, `arm`, `aarch64`, `powerpc`, `powerpc64`, `mips` and `mips64`). Furthermore it only iterates features that stdsimd knows about. This overall may lead to pessimizing the generated code.

With that in mind using LLVM's getHostCPUFeatures is probably better? It is also guaranteed that its output is suitable for passing to LLVM, avoiding the need to maintain a denylist of features like what you did with `tsc` here.

**Comment by as-com** [comment]
@nagisa Using getHostCPUFeatures would require an update to the C++ shim layer that translates the StringMap data structure. I'll take a look later to see if it's possible to do that without too much of a mess.

**Comment by nagisa** [comment]
There's a C API of this as well `LLVMGetHostCPUFeatures`, that could let you avoid doing this, but all in all its no huge deal if you find it better to adjust rustc_llvm's RustWrapper to expose an API that is more convenient to consume from the Rust side (e.g. by returning string-length pairs rather than null-terminated strings).

**Comment by as-com** [comment]
Alright, I added `LLVMGetHostCPUFeatures` and `LLVMDisposeMessage` to ffi.rs, and updated the implementation accordingly.

File: compiler/rustc_codegen_llvm/src/llvm_util.rs [hunk 1]
```diff
@@ -221,6 +221,26 @@ pub fn target_cpu(sess: &Session) -> &str {
...
 
+pub fn handle_native_features(sess: &Session) -> Vec<String> {
+    match sess.opts.cg.target_cpu {
+        Some(ref s) => {
+            if s != "native" {
+                return vec![];
+            }
+
+            let ptr = unsafe { llvm::LLVMGetHostCPUFeatures() };
+            let str = unsafe { CStr::from_ptr(ptr).to_string_lossy() };
```
Comment (nagisa) [inline compiler/rustc_codegen_llvm/src/llvm_util.rs:232]: style nit: override of the `str` seems somewhat iffy.

I also think this should just `bug!` out if the string doesn't convert to utf8 rather than replacing characters with replacement characters.

This should also check for `ptr` being null before dereferencing it.

Finally, another style nit, although I could go either way on it: all of these unsafe expressions should share the same unsafe block. As thus I would write this sippet as follows:

```rust
let features_string = unsafe {
    let ptr = llvm::LLVMGetHostCPUFeatures();
    let features_string = if !ptr.is_null() {
        String::from(CStr::from_ptr(ptr).to_str().unwrap_or_else(|| {
            bug!("LLVM returned a non-utf8 features string");
        }))
    } else {
        bug!("could not allocate host CPU features, LLVM returned a `null` string")
    };
    LLVMDisposeMessage(ptr);
    features_string
};
// split here...
```

One thing this achieves is making it more clear that there are non-trivial invariants shared between the various unsafe calls in this function.

**Comment by nagisa** [comment]
@bors r+ rollup=iffy

Thanks!

**Comment by nagisa** [comment]
@bors retry

Looks like a timeout

**Comment by JohnTitor** [comment]
bors stuck?

@bors retry
