### PR TITLE
Change opt-level from 2 back to 3

### LINKED ISSUE #52378: Setting opt-level = 3 will cause stage1-rustc to segfault on Linux
Stack trace:

```
#0  0x00007f9fc5fe6a11 in llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::DFSVisitOne(llvm::CallGraphNode*) ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#0  0x00007f9fc5fe6a11 in llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::DFSVisitOne(llvm::CallGraphNode*) ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#1  0x00007f9fc6f295b1 in (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#2  0x00007f9fc7289f0c in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#3  0x00007f9fc720c829 in LLVMRunPassManager ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#4  0x00007f9fc5681fe7 in rustc_codegen_llvm::back::write::execute_work_item::hfd3cb98239864c6b ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#5  0x00007f9fc56343a3 in std::sys_common::backtrace::__rust_begin_short_backtrace::h8c37409cc6efa4b9 ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#6  0x00007f9fc5658096 in std::panicking::try::do_call::h3fbe882ce88a0178 ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#7  0x00007f9fcfc0942a in __rust_maybe_catch_panic ()
    at libpanic_unwind/lib.rs:106
#8  0x00007f9fc5641ad1 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hcd99e38bedf3313c ()
   from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#9  0x00007f9fcfbc13bb in call_once<(),()> ()
    at /checkout/src/liballoc/boxed.rs:650
#10 std::sys_common::thread::start_thread::hf91e8d5f6a6b3cf0 ()
    at libstd/sys_common/thread.rs:24
#11 0x00007f9fcfbc6bf6 in std::sys::unix::thread::Thread::new::thread_start::h3a956f4a27a51528 () at libstd/sys/unix/thread.rs:90
#12 0x00007f9fc9d196ba in ?? ()
#13 0x0000000000000000 in ?? ()
```

Examples:

* https://github.com/rust-lang/rust/pull/52326#issuecomment-405024232
* https://github.com/rust-lang/rust/pull/51829#issuecomment-405028289

### PR DESCRIPTION
**Pull request by Others**
In Cargo.toml, the opt-level for `release` and `bench` was overridden to be 2. This was to work around a problem with LLVM 7. However, rust no longer uses LLVM 7, so this is hopefully no longer needed?

I tried a little bit to replicate the original problem, and could not. I think running this through CI is the best way to smoke test this :) Even if things break dramatically, the comment should be updated to reflect that things are still broken with LLVM 9. 

I'm just getting started playing with the compiler, so apologies if I've missed an obvious problem here.

fixes #52378

(possibly relevant is the [current update to LLVM 10](https://github.com/rust-lang/rust/pull/67759))

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I suspect things are still broken; that comment has been around since I can remember. However, we might as well let this inch its way through the queue. @bors rollup=never r+

It's also I believe true that we've not really seen appreciable performance gains when doing this, so it may just generally not be worth it. (I am unsure of the *costs* in compile time of rustc itself, but would not be surprised if they're non-marginal). I suspect this will fail anyway.

r? @Mark-Simulacrum

**Comment by mati865** [comment]
Previously identical chenge has passed CI but made subsequent PRs fail spuriously. That makes this PR quite high risk.

**Comment by Mark-Simulacrum** [comment]
I think enough time had passed that it may be worth trying again. However, one thing I did want to do but forgot - @bors r- try @rust-timer queue

Let's gather perf stats before landing.

**Comment by bjorn3** [comment]
`const_eval_raw` is about 16% slower.

**Comment by Others** [comment]
@bjorn3 I haven't used `rust-timer` before. Where are you pulling that number from?
I do see that the `ctfe` tests have some unfortunate high variance

**Comment by bjorn3** [comment]
First click on the benchmark group (ctfe-stress-4-check), then click on the percentage corresponding to a specific benchmark (10.7% for clean) You will then go to a page which shows info for every query.

**Comment by Others** [comment]
@bjorn3 ah, thanks!

Digging into the results, it seems that this change improves incremental speed by a few percent on quite a few of the test cases. This seems like a good initial sign! `const_eval_raw` is the only query I can find that significantly regressed.

I think this PR probably is worth landing, assuming the `const_eval_raw` regression can be mitigated. (And we try and ensure it's not going to cause spurious failures in the future.)

@Mark-Simulacrum How do you recommend I proceed here?

**Comment by Aaron1011** [comment]
I ran `perf` on `rustc 1.42.0-nightly (119307a83 2019-12-31)` and the try build for this PR (`c8c22433c5b3e436a1837ce84de8eacc5586de6d`) against `ctfe-stress-4`.

The slowdown appears to be coming from the body of `const_eval_raw_provider`. Here's the relevant snippets of annotated assembly:

Nightly:

```
  7.37 │      → callq  rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step                                                                                                                              ▒
 11.35 │        movzbl 0x20(%rsp),%edx                                                                                                                                                                                                       ▒
  6.80 │        movzbl 0x21(%rsp),%ecx                                                                                                                                                                                                       ▒
  1.14 │        movzbl 0x28(%rsp),%eax                                                                                                                                                                                                       ▒
  1.70 │        movups (%rbx),%xmm0                                                                                                                                                                                                          ▒
 11.94 │        movups 0x10(%rbx),%xmm1                                                                                                                                                                                                      ▒
  6.81 │        movups 0x20(%rbx),%xmm2                                                                                                                                                                                                      ▒
  6.85 │        movups 0x30(%rbx),%xmm3                                                                                                                                                                                                      ▒
       │        movaps %xmm0,0xa0(%rsp)                                                                                                                                                                                                      ▒
  9.11 │        movaps %xmm1,0xb0(%rsp)                                                                                                                                                                                                      ▒
  7.34 │        movaps %xmm2,0xc0(%rsp)                                                                                                                                                                                                      ▒
  5.11 │        movaps %xmm3,0xd0(%rsp)                                                                                                                                                                                                      ▒
       │        mov    0x3f(%rbx),%rsi                                                                                                                                                                                                       ▒
  9.66 │        mov    %rsi,0xdf(%rsp)                                                                                                                                                                                                       ▒
  5.15 │        cmp    $0x1,%dl                                                                                                                                                                                                              ▒
```

This PR:

```
  2.55 │      → callq  rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step                                                                                                                              ▒
  2.35 │        movups 0x130(%rsp),%xmm0                                                                                                                                                                                                     ▒
  0.10 │        movaps %xmm0,0x60(%rsp)                                                                                                                                                                                                      ▒
 67.80 │        movups 0xf0(%rsp),%xmm0                                                                                                                                                                                                      ▒
       │        movups 0x100(%rsp),%xmm1                                                                                                                                                                                                     ▒
  0.10 │        movups 0x110(%rsp),%xmm2                                                                                                                                                                                                     ▒
       │        movups 0x120(%rsp),%xmm3                                                                                                                                                                                                     ▒
  3.53 │        movaps %xmm3,0x50(%rsp)                                                                                                                                                                                                      ▒
       │        movaps %xmm2,0x40(%rsp)                                                                                                                                                                                                      ▒
       │        movaps %xmm1,0x30(%rsp)                                                                                                                                                                                                      ▒
  3.22 │        movaps %xmm0,0x20(%rsp)                                                                                                                                                                                                      ▒
 12.67 │        cmpb   $0x1,0x20(%rsp)   
```

With this branch, LLVM appears to be generating more SIMD instructions. However, the total percentage for the the various `mov` instructions seems to be about the same. The real difference seems to be the `cmp` instruction - on Nightly, it's comparing against a register. On this branch, it's performing a load from memory.

I think this corresponds to checking the discriminant of the `Result` returned by `InterpCx::step`. 

I'm not 100% sure that this analysis is correct. However, it appears that part of this regression may be due to LLVM codegenning `InterpCx::step` such that the discriminant of the result is stored on the stack, rather than in a register.

**Comment by Others** [comment]
@Aaron1011 

Very interesting! I'm assuming that the expensive call chain is:
```
const_eval_raw_provider => eval_body_using_ecx => InterpCx::run => InterpCx::step
```

My reading of the assembly is that on nightly LLVM is loading some part of the return value at the start (from `0x20(%rsp)`), then doing stuff, then branching on that part of the return value:
```
  7.37 │      → callq  rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step                                                                                                                              ▒
 11.35 │        movzbl 0x20(%rsp),%edx  # ret value loaded from 0x20(%rsp)                                                                                                                                                                                             ▒
[SNIP: instructions don't touch %edx]
  5.15 │        cmp    $0x1,%dl         # ret value used for comparison                                                                                                                                                                                                           ▒
```
(Note: 77.81 on movs, 5.15 on cmps)

After this patch, LLVM doesn't bother loading that part of the ret value till the end:
```
  2.55 │      → callq  rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step                                                                                                                              ▒
  2.35 │        movups 0x130(%rsp),%xmm0                                                                                                                                                                                                     ▒
[SNIP: instructions don't touch 0x20(%rsp)]
  3.22 │        movaps %xmm0,0x20(%rsp)   # ret value loaded from 0x20(%rsp)                                                                                                                                                                                                   ▒
 12.67 │        cmpb   $0x1,0x20(%rsp)    # ret value loaded _AGAIN_ from 0x20(%rsp)
```
(Note: 77.1 on movs, 12.67 on cmps)

I wonder if this double load is hurting pipelining or instruction parallelism in some subtle way. This just seems like unlucky codegen from LLVM. 

Perhaps one idea is to mark `InterpCx::step` as `inline` or `inline(always)`.  `step` is only ever called from the tiny function `run`, but the direct call seems to indicate that it's not being inlined (perhaps because of the length of the implementation of `step`). That might churn the IR enough to give us better performing assembly. This would be an easy thing to try, and  isn't even particularly hacky -- it seems `step` might want to be `inline` anyway. What do you think of that idea?

**Comment by Aaron1011** [comment]
> After this patch, LLVM doesn't bother loading that part of the ret value till the end:

I'm not sure that that's correct. I think LLVM is loading the return value first on both nightly and this branch. However, due to `opt-level=3`, it ended up using additional SIMD instructions on this branch. Note how the mov instruction totals are almost identical.

Marking `step` as `inline` seems like it could be worth a shot. However, I think it would be a good idea to try to determine why LLVM is no longer storing (what I think is) the discriminant in a register. t might just be a deliberate (but unfortunate) decision by LLVM, but it seems surprising to me that a higher optimization level should cause LLVM to avoid using a register.

**Comment by nagisa** [comment]
I’m pretty confident there’s no real point in attempting to operate on a register here. The memory location in question ought to be in the L1 cache – it has been just written to the memory address in question after all.

**Comment by Others** [comment]
Here’s my hypothesis:

Register is still faster than cache. The original code does the load from 0x20(%rsp) to %edx first. There isn’t a store to that address, so that can be totally pipelined with the vectorized movs. In the new code, the load from 0x20(%rsp) is only at the end — it cannot be pipelined properly.

**Comment by Others** [comment]
Okay, I added an `#[inline(always)]`. Comparing naively versus nightly on my local machine, this seems to have fixed the regression. (Fingers crossed.)

@Mark-Simulacrum (or someone else with bors privileges), can we get another try + rust-timer run?

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

(I will try to relook at this PR myself to see what my thoughts are, haven't had a chance yet though. I think most of the discussion has echoed my opinions, though).

File: src/librustc_mir/interpret/step.rs [hunk 1]
```diff
@@ -38,6 +38,7 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
     /// Returns `true` as long as there are more things to do.
     ///
     /// This is used by [priroda](https://github.com/oli-obk/priroda)
+    #[inline(always)]
```
Comment (bjorn3) [inline src/librustc_mir/interpret/step.rs]: Please add a comment that this is necessary to make LLVM perform a certain optimization that drastically improves performance when opt-level=3.

Comment (RalfJung) [reply src/librustc_mir/interpret/step.rs]: Wow, inlining such a big function actually *helps*? So weird...

Comment (bjorn3) [reply src/librustc_mir/interpret/step.rs]: https://github.com/rust-lang/rust/pull/67878#issuecomment-570953839

> That might churn the IR enough to give us better performing assembly.

Comment (RalfJung) [reply src/librustc_mir/interpret/step.rs]: Yeah I saw that, but still... weird.

Comment (Others) [reply src/librustc_mir/interpret/step.rs]: It's notable that `step` is only ever used in the tiny function `run` above it in this file, so it isn't going to lead to any huge functions after inlining

**Comment by Others** [comment]
The results are a little disappointing. It does improve the regression slightly, but not super significantly. I don't see value in me trying to optimize this further, since #67890 will change a lot of the code down the slow path. 

I do think that this is worth landing. It improves several of the compile time benchmarks by up to 5%, while removing a hack from the codebase. I see several options for trying to get this merged:

- Merge as-is, including the `inline(always)` tag on `step` (and I'll add a comment about it)
- Merge without the tag on `step`
- Wait for #67890 to land, and then revaluate the performance regression 
- Try to figure out some other performance hack for `const_eval_raw`

**Comment by Mark-Simulacrum** [comment]
I am going to nominate for the compiler team meeting re: the options above (and more generally how we feel about landing this).

I believe that a good summary of this change is that it does, in fact, bring fairly sizeable optimizations (2-5% wins). However, we may end up needing to revert it, as historically O3 has caused spurious and sporadic problems on CI (usually only picked up *after* it passes through full CI once, of course). 

In particular, I would be interested in @oli-obk and @wesleywiser's thoughts on the const eval performance hit here (there may be better people to ping, I'm not sure). Do we think it's significant enough to block this PR? I personally lean towards no.

**Comment by oli-obk** [comment]
Seems fine to me. We can figure out how to improve the stress tests later. We mostly need them as canaries for detecting accidental regressions not as a hard blocker for merging stuff.

**Comment by wesleywiser** [comment]
Re: const eval performance, I agree with @oli-obk. The rest of the improvements look great and I believe we can recover the regressed const eval performance with more MIR optimizations in the future. 

Is there anyway we could try to determine if O3 is still buggy? Perhaps a crater run would tell us if the compiler is more prone to crashes?

**Comment by Mark-Simulacrum** [comment]
Crater is an interesting idea. I wish we could do a random sampling run, but a full run won't be too long I imagine either.

@craterbot run mode=build-only 

We'll skip tests though as I think any problems should hopefully be exposed by just the regular build (though check would perhaps be insufficient, as it skips LLVM).

**Comment by RalfJung** [comment]
@Mark-Simulacrum according to https://github.com/rust-lang/crater/blob/master/docs/bot-usage.md#available-crate-selections, a random sampling run is possible, with something like `random-5000` to pick 5000 crates.

**Comment by Mark-Simulacrum** [comment]
Huh, cool! In any case this seems fine as queue was empty it seems, but if someone wants to kill it in the next few days (i.e., we get something higher priority) that's fine by me.

**Comment by gnzlbg** [comment]
Would it be possible to minimize the perf regression, and open a tracking issue or fill an LLVM bug ?

**Comment by Others** [comment]
@gnzlbg #67890 will completely change the performance characteristics of the regressed method. So this regression may not matter much. See also the comments above regarding MIR/const-eval.

A LLVM bug might be a good idea, but I’m unsure how to best to proceed on that front. I’ll look into creating a minimal example (which I think we’d need), but that doesn’t need to be a blocker for this PR

**Comment by Others** [comment]
The regressions look spurious to me — out of memory or out of disk space. I’m pretty sure the fixed ones are spurious too—just changed memory/disk usage probably.

I’m doing this on mobile, so apologies for the formatting. Here is a comprehensive overview of the regressions:

femnad.gel.78a1ae35ea52d0b50c42ce679cd5bc2ea6b41c5f
“ [INFO] [stderr] LLVM ERROR: IO failure on output stream: Cannot allocate memory”
This is just a fancy OOM as far as I can tell

hiroshiyui.libwonderarray.dd9b18d88105863b58027a94951ebfedf9af5133
“[INFO] [stderr]   = note: /opt/rustwide/target/debug/deps/libwonderarray.so: file not recognized: File truncated”
I think this is an out of disk problem—but I’m not 100% on that. Probably the weirdest error.

doryen-rs-1.1.0
“ [INFO] [stderr]   = note: /usr/bin/ld: final link failed: Cannot allocate memory”
Straightforward OOM

igdb-rs-0.2.0
“ [INFO] [stderr]   = note: /usr/bin/ld: final link failed: No space left on device”
Straightforward lack of disk

xmc4500-0.3.1
“ [INFO] [stderr] error: failed to write /tmp/rustcDQrHYK/lib.rmeta: Cannot allocate memory (os error 12)”
Lack of disk or OOM

I don’t see any evidence for random segfaults in the data, and this is a lot of built crates. Perhaps previous issues only arose while building the compiler? Either way, merging this seems unlikely to cause user problems.

@Mark-Simulacrum Is there any way to run CI on this a couple times? That would be a way to gain confidence this won’t cause spurious CI failures. (Although perhaps a bit wasteful of CI resources...)

**Comment by Mark-Simulacrum** [comment]
Given the tiny amount of regressions (none of which appear legitimate, too), I'm going to say that we *probably* do not have a bug in the compiler produced here, so I think we can proceed with merging. Of course, it's possible that the compiler itself will expose a bug that Crater has not caught, but I think we've done due diligence and checked as well as we can; we can revert if this causes spurious failures. cc @Centril @rust-lang/wg-triage re:spurious failures

@bors r+ -- let's not block on the comment since https://github.com/rust-lang/rust/pull/67890 is planning on changing things here anyway which will naturally drop the inline hopefully (and any regressions can be dealt with, if necessary, there)

**Comment by Others** [comment]
I think this is spurious? I'm kinda confused why there seems to be a test failure with no diagnostic output -- scary.

**Comment by Aaron1011** [comment]
> I'm kinda confused why there seems to be a test failure with no diagnostic output -- scary.

I think this is just the result of a command in the `Makefile` exiting with a nonzero status:

```
2020-01-13T01:30:53.0880282Z [ "`wc -c < /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/wasm-stringify-ints-small/wasm-stringify-ints-small/foo.wasm`" -lt "20500" ]
2020-01-13T01:30:53.0880635Z Makefile:5: recipe for target 'all' failed
```

However, it seems extremely alarming that switching to `opt-level=3` caused the size of a *program built by the stage2 compiler* to become larger. It looks like the behavior of the stage2 compiler was changed by the optimization level increase, which definitely shouldn't happen.

**Comment by nikic** [comment]
Does the opt-level here only affect the compiler itself or also libcore/libstd builds? If the latter, then that could result in a program size increase.

**Comment by Aaron1011** [comment]
Thats a good point - I think it affects every crate. That's much less concerning - hopefully the size impact isn't too high.

**Comment by Mark-Simulacrum** [comment]
This is an increase of 2,299 bytes which feels pretty significant to me, but I don't have a lot of context here. Certainly @jamesmunns has indicated to me I believe that this is pretty significant for embedded.

Could you try to investigate where the size increase is coming from? That is, is it spread out across all of libcore/std or a few functions getting significantly larger?

**Comment by pnkfelix** [comment]
> This is an increase of 2,299 bytes which feels pretty significant to me, but I don't have a lot of context here. Certainly @jamesmunns has indicated to me I believe that this is pretty significant for embedded.
> 
> Could you try to investigate where the size increase is coming from? That is, is it spread out across all of libcore/std or a few functions getting significantly larger?

(also, we might want to consider the possiblilty that the failures due to lack of disk and OOMs in the earlier crater run are somehow connected to the code size increase, no?)

**Comment by Mark-Simulacrum** [comment]
I suspect no -- historically we've seen sporadic oom and disk full errors sporadically on entirely clean runs too.

**Comment by Mark-Simulacrum** [comment]
I would like to see us track down the size diff in that particular test before moving forward. `twiggy` or a similar tool run on the output from master and this branch should be helpful.

**Comment by JohnCSimon** [comment]
Ping from triage: @Others this PR has sat idle for a week, can you please post your status?

**Comment by Others** [comment]
Sorry, have had a couple deadlines outside of this work. Will get back to this ASAP

**Comment by Others** [comment]
After investigating, I believe the difference is almost entirely in the size of the `dlmalloc::dlmalloc::Dlmalloc::malloc` function. I'm not sure why, but I can confirm that this is the only thing that's getting massively blown up.

Twiggy output pre this PR:
```
 Shallow Bytes │ Shallow % │ Item                                                                                                                                                                           
───────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────                                                                                                 
          3518 ┊    17.26% ┊ foo                                                                                                                                                                            
          3436 ┊    16.86% ┊ dlmalloc::dlmalloc::Dlmalloc::malloc::h5191837f74aa063b                                                                                                                        
          2786 ┊    13.67% ┊ "function names" subsection                                                                                                                                                    
          1171 ┊     5.75% ┊ core::fmt::write::h0ce3b15765a50a38                                                                                                                                            
          1091 ┊     5.35% ┊ <&T as core::fmt::Display>::fmt::h8a37c3d9d7b52c10                                                                                                                             
          1017 ┊     4.99% ┊ dlmalloc::dlmalloc::Dlmalloc::free::he974a440dac0e703                                                                                                                          
           835 ┊     4.10% ┊ data[0]                                                                                                                                                                        
           791 ┊     3.88% ┊ core::fmt::Formatter::pad_integral::hda797e1e16145143                                                                                                                          
           785 ┊     3.85% ┊ __rdl_realloc                                                                                                                                                                  
           706 ┊     3.46% ┊ dlmalloc::dlmalloc::Dlmalloc::dispose_chunk::h2ab4f6a050146e3d                                                                                                                 
           481 ┊     2.36% ┊ data[1]                                                                                                                                                                        
           396 ┊     1.94% ┊ __rdl_alloc                                                                                                                                                                    
           365 ┊     1.79% ┊ <&mut W as core::fmt::Write>::write_char::he9f72744d97cef6e                                                                                                                    
           364 ┊     1.79% ┊ core::fmt::num::imp::fmt_u64::h6b8bd0148369b5f2                                                                                                                                
           332 ┊     1.63% ┊ dlmalloc::dlmalloc::Dlmalloc::insert_large_chunk::h9c2c0eddd01a2805                                                                                                            
           322 ┊     1.58% ┊ dlmalloc::dlmalloc::Dlmalloc::unlink_large_chunk::h971e5e4ddf7fb69e                                                                                                            
           205 ┊     1.01% ┊ alloc::raw_vec::RawVec<T,A>::reserve::h8b68b4c50816a33e                                                                                                                        
           162 ┊     0.79% ┊ core::result::unwrap_failed::hf27cc13e099ddfcf                                                                                                                                 
           132 ┊     0.65% ┊ core::panicking::panic_bounds_check::h281ad44a05ec4aee                                                                                                                         
           123 ┊     0.60% ┊ std::panicking::rust_panic_with_hook::h0cb0cfbfcae4d325                                                                                                                        
           118 ┊     0.58% ┊ <&mut W as core::fmt::Write>::write_fmt::h9257c36ec995818d                                                                                                                     
<SNIP>
```
After applying this PR:
```
ubuntu@ip-172-31-23-149:~/rust$ twiggy top /home/ubuntu/rust/build/x86_64-unknown-linux-gnu/test/run-make/wasm-stringify-ints-small/wasm-stringify-ints-small/foo.wasm                                      
 Shallow Bytes │ Shallow % │ Item                                                                                                                                                                           
───────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────
          6256 ┊    25.41% ┊ dlmalloc::dlmalloc::Dlmalloc::malloc::h41b2f4cb262befbb
          3518 ┊    14.29% ┊ foo
          2642 ┊    10.73% ┊ "function names" subsection
          1974 ┊     8.02% ┊ dlmalloc::dlmalloc::Dlmalloc::free::h74082b2fc321a532
          1660 ┊     6.74% ┊ dlmalloc::dlmalloc::Dlmalloc::dispose_chunk::h194d309ddaa42708
          1158 ┊     4.70% ┊ core::fmt::write::h7a56f8be98585755
          1105 ┊     4.49% ┊ <&T as core::fmt::Display>::fmt::ha36b0b1ae11f94a9
          1094 ┊     4.44% ┊ __rdl_realloc
           831 ┊     3.37% ┊ data[0]
           791 ┊     3.21% ┊ core::fmt::Formatter::pad_integral::h2884a891601c317e
           481 ┊     1.95% ┊ data[1]
           402 ┊     1.63% ┊ __rdl_alloc
           365 ┊     1.48% ┊ <&mut W as core::fmt::Write>::write_char::h7c7a8ec042aeecbd
           364 ┊     1.48% ┊ core::fmt::num::imp::fmt_u64::h20314ec5886669d6
           205 ┊     0.83% ┊ alloc::raw_vec::RawVec<T,A>::reserve::h6b68995b555c2ec7
           162 ┊     0.66% ┊ core::result::unwrap_failed::haa7e7a77a7937368
           132 ┊     0.54% ┊ core::panicking::panic_bounds_check::ha6acab54c4f53c2d
           123 ┊     0.50% ┊ std::panicking::rust_panic_with_hook::h9c90ba24f7d72c9c
           118 ┊     0.48% ┊ <&mut W as core::fmt::Write>::write_fmt::h3f4eaeca77ac8b69
<SNIP>
```
Twiggy diff output:
```
 Delta Bytes │ Item
─────────────┼────────────────────────────────────────────────────────────────────
       +6256 ┊ dlmalloc::dlmalloc::Dlmalloc::malloc::h41b2f4cb262befbb
       -3436 ┊ dlmalloc::dlmalloc::Dlmalloc::malloc::h5191837f74aa063b
       +1974 ┊ dlmalloc::dlmalloc::Dlmalloc::free::h74082b2fc321a532
       +1660 ┊ dlmalloc::dlmalloc::Dlmalloc::dispose_chunk::h194d309ddaa42708
       -1171 ┊ core::fmt::write::h0ce3b15765a50a38
       +1158 ┊ core::fmt::write::h7a56f8be98585755
       +1105 ┊ <&T as core::fmt::Display>::fmt::ha36b0b1ae11f94a9
       -1091 ┊ <&T as core::fmt::Display>::fmt::h8a37c3d9d7b52c10
       -1017 ┊ dlmalloc::dlmalloc::Dlmalloc::free::he974a440dac0e703
        +791 ┊ core::fmt::Formatter::pad_integral::h2884a891601c317e
        -791 ┊ core::fmt::Formatter::pad_integral::hda797e1e16145143
        -706 ┊ dlmalloc::dlmalloc::Dlmalloc::dispose_chunk::h2ab4f6a050146e3d
        +365 ┊ <&mut W as core::fmt::Write>::write_char::h7c7a8ec042aeecbd
        -365 ┊ <&mut W as core::fmt::Write>::write_char::he9f72744d97cef6e
        +364 ┊ core::fmt::num::imp::fmt_u64::h20314ec5886669d6
        -364 ┊ core::fmt::num::imp::fmt_u64::h6b8bd0148369b5f2
        -332 ┊ dlmalloc::dlmalloc::Dlmalloc::insert_large_chunk::h9c2c0eddd01a2805
        -322 ┊ dlmalloc::dlmalloc::Dlmalloc::unlink_large_chunk::h971e5e4ddf7fb69e
        +309 ┊ __rdl_realloc
        +205 ┊ alloc::raw_vec::RawVec<T,A>::reserve::h6b68995b555c2ec7
        -347 ┊ ... and 61 more.
       +4245 ┊ Σ [81 Total Rows]
```

I kinda doubt this should be a blocker for the PR? Would love some more review feedback.

**Comment by Mark-Simulacrum** [comment]
Interesting! Looks like the dlmalloc functions are somewhat big. Given that it's just the default allocator, and not actually mandatory (i.e. most wasm executables that care about size will likely switch to some alternative), I imagine that we can land this.

Looks like there's still a comment left to be added about the `#[inline(always)]` we've added and once that's in I believe we can merge.

**Comment by Others** [comment]
@Mark-Simulacrum  I've added the comment :)
