### PR TITLE
Prepend temp files with per-invocation random string to avoid temp filename conflicts

### LINKED ISSUE #139407: Instructions missing from naked_asm blocks.
Instructions are getting omitted from naked_asm blocks after fixing a compilation error and then rebuilding with `cargo run`.  A `cargo clean` and `cargo run` is then required to get a correct executable.

As a minimal demonstration of this problem this code contains a deliberate error and fails to build:
```
#![feature(naked_functions)]
#![no_main]

use core::arch::naked_asm;

#[unsafe(no_mangle)]
#[naked]
extern "C" fn add_u64(x: u64, y: u64) -> u64 {
    unsafe { naked_asm!("add x0, x0, w1", "ret") }
}

#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: isize, _argv: *const *const u8) -> isize {
    println!("{}", add_u64(3u64, 7u64));
    0
}
```
```
cargo run
   Compiling rust_asm v0.1.0 (/Users/me/rust_asm)
error: too few operands for instruction
  |
note: instantiated into assembly here
 --> <inline asm>:5:1
  |
5 | add x0, x0, w1
  | ^^^^^^^^^^^^^^
```

We fix the source by changing `w1` into `x1`. Which now builds without error but produces the wrong result:
```
#![feature(naked_functions)]
#![no_main]

use core::arch::naked_asm;

#[unsafe(no_mangle)]
#[naked]
extern "C" fn add_u64(x: u64, y: u64) -> u64 {
    unsafe { naked_asm!("add x0, x0, x1", "ret") }
}

#[unsafe(no_mangle)]
pub extern "C" fn main(_argc: isize, _argv: *const *const u8) -> isize {
    println!("{}", add_u64(3u64, 7u64));
    0
}
```
```
cargo run
   Compiling rust_asm v0.1.0 (/Users/me/rust_asm)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/rust_asm`
3
```
Looking at the disassembled executable with `objdump -d target/debug/rust_asm | less` we find the `add` instruction is missing from the `add_u64()` function:
```
00000001000018d0 <_add_u64>:
1000018d0: d65f03c0     ret
```
Rebuilding with `cargo clean` and `cargo run` then produces the correct result:
```
cargo clean
     Removed 41 files, 1.0MiB total
cargo run
   Compiling rust_asm v0.1.0 (/Users/me/rust_asm)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/rust_asm`
10
```
And of course the `add` instruction is now in the executable where we expect it to be:
```
00000001000018cc <_add_u64>:
1000018cc: 8b010000     add     x0, x0, x1
1000018d0: d65f03c0     ret
```

### Meta
```
rustc --version --verbose
rustc 1.87.0-nightly (249cb8431 2025-03-12)
binary: rustc
commit-hash: 249cb84316401daf040832cdbb8a45e0f5ab6af8
commit-date: 2025-03-12
host: aarch64-apple-darwin
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### PR DESCRIPTION
**Pull request by compiler-errors**
https://github.com/rust-lang/rust/issues/139407 uncovered a very subtle unsoundness with incremental codegen, failing compilation sessions (due to assembler errors), and the "prefer hard linking over copying files" strategy we use in the compiler for file management.

Specifically, imagine we're building a single file 3 times, all with `-Csave-temps -Cincremental=...`. Let's call the object file we're building for the codegen unit for `main` "`XXX.o`" just for clarity since it's probably some gigantic hash name:

```
#[inline(never)]
#[cfg(any(rpass1, rpass3))]
fn a() -> i32 {
    0
}

#[cfg(any(cfail2))]
fn a() -> i32 {
    1
}

fn main() {
    evil::evil();
    assert_eq!(a(), 0);
}

mod evil {
    #[cfg(any(rpass1, rpass3))]
    pub fn evil() {
        unsafe {
            std::arch::asm!("/*  */");
        }
    }

    #[cfg(any(cfail2))]
    pub fn evil() {
        unsafe {
            std::arch::asm!("missing");
        }
    }
}
```

Session 1 (`rpass1`):
* Type-check, borrow-check, etc.
* Serialize the dep graph to the incremental working directory `.../s-...-working/`.
* Codegen object file to a temp file `XXX.rcgu.o` which is spit out in the cwd.
* Hard-link[^1] `XXX.rcgu.o` to the incremental working directory `.../s-...-working/XXX.o`.
* Save-temps option means we don't delete `XXX.rgcu.o`.
* Link the binary and stuff.
* Finalize[^2] the working incremental session by renaming `.../s-...-working` to ` s-...-asjkdhsjakd` (some other finalized incr comp session dir name).

Session 2 (`cfail2`):
* Load artifacts from the previous *finalized* incremental session, namely the dep graph.
* Type-check, borrow-check, etc. since the file has changed, so most dep graph nodes are red.
* Serialize the dep graph to the incremental working directory `.../s-...-working/`.
* Codegen object file to a temp file `XXX.rcgu.o`. **HERE IS THE PROBLEM**: The hard-link is still set up to point to the inode from `XXX.o` from the first session, so this also modifies the `XXX.o` in the previous finalized session directory.
* Codegen emits an error b/c `missing` is not an instruction, so we abort before finalizing the incremental session. Specifically, this means that the *previous* session is the last finalized session.

Session 3 (`rpass3`):
* Load artifacts from the previous *finalized* incremental session, namely the dep graph. NOTE that this is from session 1.
* All the dep graph nodes are green since we are basically replaying session 1.
* codegen object file `XXX.o`, which is detected as *reused* from session 1 since dep nodes were green. That means we **reuse** `XXX.o` which had been dirtied from session 2.
* Link the binary and stuff.

This results in a binary which reuses some of the build artifacts from session 2, but thinks it's from session 1.

At this point, I hope it's clear to see that the incremental results from session 1 were dirtied from session 2, but we reuse them as if session 1 was the previous (finalized) incremental session we ran. This is at best really buggy, and at worst **unsound**.

This isn't limited to `-C save-temps`, since there are other combinations of flags that may keep around temporary files (hard linked) in the working directory (like `-C debuginfo=1 -C split-debuginfo=unpacked` on darwin, for example).

---

This PR implements a fix which is to prepend temp filenames with a random string that is generated per invocation of rustc. This string is not *deterministic*, but temporary files are transient anyways, so I don't believe this is a problem.

That means that temp files are now something like... `{crate-name}.{cgu}.{invocation_temp}.rcgu.o`, where `{invocation_temp}` is the new temporary string we generate per invocation of rustc.

Fixes https://github.com/rust-lang/rust/issues/139407

[^1]: https://github.com/rust-lang/rust/blob/175dcc7773d65c1b1542c351392080f48c05799f/compiler/rustc_fs_util/src/lib.rs#L60
[^2]: https://github.com/rust-lang/rust/blob/175dcc7773d65c1b1542c351392080f48c05799f/compiler/rustc_incremental/src/persist/fs.rs#L1-L40

### CODE REVIEW

File: tests/run-make/dirty-incr-due-to-hard-link/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+use run_make_support::{run, rustc};
```
Comment (compiler-errors) [inline tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:1]: I could *not* make this into a `tests/incremental` test b/c it simply wouldn't reproduce, but `tests/run-make` works fine. Probably has to do with how `-Csave-temps` interacts w/ incremental tests, given that it generates temp files into the cwd.

Is there a way to limit this just to `x86_64-unknown-linux-gnu`? I think we just need one platform with asm support for this test.

**Comment by bjorn3** [comment]
cg_clif will also need changes. In any case would it make sense to codegen to a file with a randomly generated name using eg the tempfile crate rather using a fixed filename? The existing fixed filename can still be used within the incr comp cache and as name for the archive members. This would also prevent issues when two rustc instances with the same crate name and `-Cmetadata` are running inside the same directory if they use a different output filename (and if they use the same output filename, one of them would win rather than non-deterministically mixing object files from the two).

**Comment by compiler-errors** [comment]
> cg_clif will also need changes

Yeah, the cc was not really me asking *whether* `cg_clif` needed changes but asking *where* we should be making those changes, since I don't know how temp files get generated in clif 😆

We already have a fixed name for the file in the incr comp cache, so yeah, I think(?) we can just modify the way we generate temporary file names[^1] to append the per-session temporary name? Like `XXX.session-hash.rcgu.o`? 🤔

[^1]: https://github.com/rust-lang/rust/blob/fd4dc18e684ffb8c000b053e4d34f412ee1d586a/compiler/rustc_session/src/config.rs#L1097

Though I'm not sure if anyone relies on the filename of these temporaries today; that seems like a more dramatic change given that people are probably doing... funny things with the outputs of `-Csave-temps` 😓

**Comment by bjorn3** [comment]
> Yeah, the cc was not really me asking whether cg_clif needed changes but asking where we should be making those changes, since I don't know how temp files get generated in clif 

All this code is in src/driver/aot.rs.

> Though I'm not sure if anyone relies on the filename of these temporaries today

People may depend on the rough format of the filename, but can't depend on the exact filename as it is rustc version dependent.

**Comment by the8472** [comment]
> This seems a bit scattered. I think our usage of hard-links in the compiler is really sketchy and feels like it's somewhat brittle; not using hard links would also fix the problem.

Ideally all our cachable outputs would be created read-only to prevent this kind of accidental modification since they're semantically write-once anyway. Similar to #137025

File: tests/run-make/dirty-incr-due-to-hard-link/rmake.rs (hunk 1 above)
Comment (jieyouxu) [reply tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:1]: Yes, you can do `//@ only-x86_64-unknown-linux-gnu` I believe.

Comment (compiler-errors) [reply tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:1]: Oh ok, I didn't know rmake files could take directives.

**Comment by compiler-errors** [comment]
Anyways, I haven't updated this to a new strategy for encoding temporary files. I'll probably evaluate that in a bit and if it's too hard/annoying then I'd prefer we just land this approach to patch the unsoundness.

File: tests/run-make/dirty-incr-due-to-hard-link/rmake.rs (hunk 1 above)
Comment (jieyouxu) [reply tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:3]: `rmake.rs` files take a subset of directives. For instance, revisions are not supported, but the usual `{ignore,only}-*` ones do work. I want to eventually make which directives can be used in which test suites way easier to figure out, but yeah.

Comment (compiler-errors) [reply tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:3]: gamer

**Comment by compiler-errors** [comment]
OK, I updated the description to implement a new strategy of just augmenting these temp filenames with a per-invocation temporary string. 

I think it's a lot more straightforward than unlinking. I opted to just use `rand` to generate the string, since that's what we use for generating the session directory names too.

**Comment by compiler-errors** [comment]
CGU reuse 💀

File: compiler/rustc_session/src/config.rs [hunk 2]
```diff
@@ -1094,40 +1094,39 @@ impl OutputFilenames {
...
-                extension.push('.');
-                extension.push_str(RUST_CGU_EXT);
-                extension.push('.');
-            }
-
+            extension.push('.');
+            extension.push_str(RUST_CGU_EXT);
+            extension.push('.');
             extension.push_str(ext);
         }
```
Comment (jieyouxu) [inline compiler/rustc_session/src/config.rs:1142]: Remark: okay so this bit also seemed a bit sus to me, git archaeology points way back to

- https://github.com/rust-lang/rust/commit/65e8a13441cb4169ce4fb43be7f1369d5c9d71e0 as part of https://github.com/rust-lang/rust/pull/33890

and I can't seem to find any specific reason to skip appending `.rcgu` when the ext is empty, except for the diagnostic long-type-hash file.

```diff
-           self.output_filenames(()).temp_path_ext(&format!("long-type-{hash}.txt"), None)
+           self.output_filenames(()).temp_path_for_diagnostic(&format!("long-type-{hash}.txt"))
```

All other call sites AFAICT explicitly constructs a CGU name and passes `Some(..)`, so I believe it was *correct* but just hard to follow.

The cleanup here is indeed very nice because we no longer rely on that `Option<CguName>` to splice what `temp_path_ext` does.

File: tests/run-make/dirty-incr-due-to-hard-link/rmake.rs
Comment (jieyouxu) [inline tests/run-make/dirty-incr-due-to-hard-link/rmake.rs:1]: Suggestion: could you add a backlink to the issue, and maybe add a smol test comment, because it's probably very non-obvious what this test is trying to check at first glance?

**Review by jieyouxu — APPROVED** [review]
Thanks for the fix! The approach and changes look good to me, only left a few remarks.

File: compiler/rustc_session/src/config.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_session/src/config.rs:1142]: > The cleanup here is indeed very nice because we no longer rely on that Option<CguName> to splice what temp_path_ext does.

Yeah, that's why I did all that splitting first, since there seemed to be totally distinct responsibilities for `temp_path` -- for cgu files and for "other" files.

**Comment by jieyouxu** [comment]
Also, damn, that's nasty
