### PR TITLE
Suggest appropriate path when calling associated item on bare types

### LINKED ISSUE #26760: f32 seen as ambiguous associated type
see http://stackoverflow.com/questions/31208465/pi-constant-is-ambiguous

``` rust
   fn main() {
        let _ = f32::consts::PI;
    }
```

fails to compile with:

``` bash
$ rustc -
<anon>:2:13: 2:28 error: ambiguous associated type; specify the type using the syntax `<f32 as Trait>::consts` [E0223]
<anon>:2     let i = f32::consts::PI;
                     ^~~~~~~~~~~~~~~
error: aborting due to previous error
```

on rust 1.0 stable and 1.1 stable

using the full path `std::f32::consts::PI;` works. The compilation error looks wrong (why is f32 an associated type)?

### LINKED ISSUE #46660: str primitive usage should automatically recommend str module functions
Using `str` without the `std::str` prefix to specify the module generates unhelpful error messages (especially since the distinction between the `std::str` module and the `str` primitive is not very nicely thought out due to technical restrictions I wish we could revisit).

Example code:

```rust
fn main() {
    let bytes = "hello world".as_bytes();
    let string = unsafe {
        str::from_utf8(bytes)
    };

    println!("{}", string);
}
```

This causes the compiler to emit the following error:

```rust
error[E0599]: no function or associated item named `from_utf8` found for type `str` in the current scope
 --> ./test.rs:4:9
  |
4 |         str::from_utf8(bytes)
  |         ^^^^^^^^^^^^^^

error: aborting due to previous error

```

A recommendation to specify `std::` to access the module function with the same name would be most helpful. In fact, anything the compiler could do to blur the distinction between the type and the primitive would be most appreciated.

### PR DESCRIPTION
**Pull request by estebank**
When looking at the documentation for `std::f32` or `std::str`, for
example, it is easy to get confused and assume `std::f32` and `f32`
are the same thing. Because of this, it is not uncommon to attempt
writing `f32::consts::PI` instead of the correct
`std::f32::consts::PI`. When encountering the former, which results
in an access error due to it being an inexistent path, try to access
the same path under `std`. If this succeeds, this information is
stored for later tweaking of the final E0599 to provide an
appropriate suggestion.

Fix #26760, fix #46660.

### CODE REVIEW

File: src/librustc/session/mod.rs [hunk 1]
```diff
@@ -165,6 +165,10 @@ pub struct Session {
 
     /// `Span`s of trait methods that weren't found to avoid emitting object safety errors
     pub trait_methods_not_found: Lock<FxHashSet<Span>>,
+
+    /// Mapping from indent span to path span for paths that don't exist as written, but that
```
Comment (petrochenkov) [inline src/librustc/session/mod.rs]:
```suggestion
    /// Mapping from ident span to path span for paths that don't exist as written, but that
```

File: src/librustc_resolve/lib.rs [hunk 2]
```diff
@@ -3273,6 +3274,38 @@ impl<'a> Resolver<'a> {
                     let traits = self.get_traits_containing_item(item_name, ns);
                     self.trait_map.insert(id, traits);
                 }
+
+                // check if we wrote `str::from_utf8` instead of `std::str::from_utf8`
+                let item_span = path.iter().last().map(|segment| segment.ident.span)
+                    .unwrap_or(span);
+                let mut std_path = vec![Segment::from_ident(Ident::from_str("std"))];
+                std_path.extend(path);
+                match self.resolve_qpath_anywhere(
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: You don't need neither `resolve_qpath_anywhere`, nor `resolve_qpath` for speculative search of names in modules.
`resolve_path_without_parent_scope` is used for that (you can see some other diagnostics code using it already).

File: src/librustc_resolve/lib.rs [hunk 3]
```diff
@@ -3273,6 +3274,38 @@ impl<'a> Resolver<'a> {
                     let traits = self.get_traits_containing_item(item_name, ns);
                     self.trait_map.insert(id, traits);
                 }
+
+                // check if we wrote `str::from_utf8` instead of `std::str::from_utf8`
+                let item_span = path.iter().last().map(|segment| segment.ident.span)
+                    .unwrap_or(span);
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: Nit: could you move this closer to the use point (which will also avoid evaluating the span unless necessary).

File: src/librustc_resolve/lib.rs (hunk 2 above)
Comment (petrochenkov) [reply src/librustc_resolve/lib.rs]: I'm also not too happy about doing this extra work on happy path.
Perhaps we should do it only if it really looks like a built-in type (`primitive_type_table` contains it).

File: src/librustc_resolve/lib.rs [hunk 4]
```diff
@@ -3273,6 +3274,38 @@ impl<'a> Resolver<'a> {
...
+                    crate_lint,
+                    true,
+                ) {
+                    Some(resolution) if resolution.unresolved_segments() == 0 => {
+                        debug!("accessed item from `std` submodule as a bare type {:?}", std_path);
+                        let mut hm = self.session.confused_type_with_std_module.borrow_mut();
+                        hm.insert(
+                            item_span,
+                            span,
+                        );
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: Nit: I don't think even rustfmt would format this on multiple lines (and rustfmt is known to be vertical space hungry).

File: src/librustc_resolve/lib.rs [hunk 5]
```diff
@@ -3273,6 +3273,33 @@ impl<'a> Resolver<'a> {
...
+                std_path.extend(path);
+                if self.primitive_type_table.primitive_types.contains_key(&path[0].ident.name) {
+                    match self.resolve_path_without_parent_scope(
+                        &std_path,
+                        Some(ns),
+                        false,
+                        span,
+                        CrateLint::No,
+                    ) {
+                        PathResult::Module(_) | PathResult::NonModule(_) => {
```
Comment (petrochenkov) [inline src/librustc_resolve/lib.rs]: `if let` can be used here

**Comment by petrochenkov** [comment]
Could you revert the changes to `resolve_qpath(_anywhere)` and squash the commits to avoid the changing/reverting back and forth?

r=me after that

**Comment by estebank** [comment]
@petrochenkov is it ok if I leave the reformatting of signatures to the current style?

**Comment by petrochenkov** [comment]
Rustfmt is going to do that anyway, but yeah, it's probably ok to leave them.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/60100#issuecomment-484740120, @bors r-
