### PR TITLE
mir: add `used_generic_parameters_needs_subst`

### LINKED ISSUE #74636: bug with polymorphisation + closures that inherit unused parameters
#74614 discovered a regression in polymorphisation, fixed by disabling polymorphisation in #74633. This issue will track the fix for the regression, based on the [discussion in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/216091-t-compiler.2Fwg-polymorphization/topic/tokio.20regression.20%28.2374614%29/near/204640191) (with thanks to @lcnr, @oli-obk and @eddyb).

#74614 can be reduced to the following MCVE (`src/test/ui/issues/issue-74614.rs` after #74633):

```rust
fn test<T>() { std::mem::size_of::<T>(); }

pub fn foo<T>(_: T) -> &'static fn() {
    &(test::<T> as fn())
}

fn outer<T>() {
    foo(|| ());
}


fn main() {
    outer::<u8>();
}
```

`outer` is polymorphized because `T` is not used in `outer` or `outer::{{closure}}#0`. `outer::{{closure}}#0` therefore inherits `T` from `outer` and that ends up being `T` in `foo<T>`. 

Without a transitive analysis (which isn't possible without hitting cycle errors), `outer` cannot consider `T` used based on how `outer::{{closure}}#0` is used in other functions.

There are two issues that this can cause - when that closure is used in a cast or when that closure is used in reflection.

When used in a cast (as in the example above), the following lines will be hit:

https://github.com/rust-lang/rust/blob/e22b61bff0bdd08be7665607cb7be3748c8a35d2/src/librustc_mir/interpret/cast.rs#L49-L52

https://github.com/rust-lang/rust/blob/e22b61bff0bdd08be7665607cb7be3748c8a35d2/src/librustc_mir/interpret/cast.rs#L91-L94

Using `still_further_specializable` instead of `needs_subst` here fixes the issue, as that flag isn't set for the parent substitutions of closures.

When used in reflection (see the example below), then this will ICE once #74538 lands, but doesn't right now.

```rust
use std::any::TypeId;

pub fn foo<T: 'static>(_: T) -> TypeId {
    TypeId::of::<T>()
}

fn outer<T: 'static>() {
    foo(|| ());
}

fn main() {
    outer::<u8>();
}
```

Reflection is more complicated because it makes the result of polymorphisation observable.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #74636.

This PR adds a `used_generic_parameters_needs_subst` helper function which checks whether a type needs substitution, but only for parameters that the `unused_generic_params` query considers used. This is used in the MIR interpreter to make the check for some pointer casts and for reflection intrinsics more precise.

I've opened this as a draft PR because this might not be the approach we want to fix this issue and we have to decide what to do about the reflection case.

r? @eddyb 
cc @lcnr @wesleywiser

### CODE REVIEW

**Comment by oli-obk** [comment]
r? @oli-obk 

I got a crash course in polymorphization magic in https://rust-lang.zulipchat.com/#narrow/stream/216091-t-compiler.2Fwg-polymorphization/topic/tokio.20regression.20%28.2374614%29/near/205594913

**Comment by oli-obk** [comment]
cc @rust-lang/wg-const-eval 

@bors r+

File: src/librustc_mir/interpret/util.rs [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                        // are used and require substitution.
+                        if is_used && subst.needs_subst() {
+                            // Just in case there are closures or generators within this subst,
+                            // recurse.
+                            if subst.super_visit_with(self) {
+                                // Only return when we find a parameter so the remaining substs
+                                // are not skipped.
+                                return true;
+                            }
+                        }
```
Comment (lcnr) [inline src/librustc_mir/interpret/util.rs:58]:
```suggestion
                        } else if cfg!(debug_assert)
                             match subst.unpack() {
                                 ty::GenericArgKind::Lifetime(_) => ??? // not sure how lt are used
                                 ty::GenericArgKind::Ty(ty) => assert!(matches!(ty.kind, ty::Param(_))),
                                 ty::GenericArgKind::Const(ct) => assert!(matches!(ct, ty::ConstKind::Param(_))),
                             }
                        }
```
Or something like this would make me more comfortable about `type_id`

Comment (davidtwco) [reply src/librustc_mir/interpret/util.rs:58]: It isn't true that a `subst` here will be a `ty::Param(_)` and not a type which contains a `ty::Param(_)`, right?

Comment (lcnr) [reply src/librustc_mir/interpret/util.rs:58]: If a param is unused it, polymorphization should it with `ty::Param(_)`, shouldn't it?

So if this assert failed, we may have called `type_id` with an unpolymorphized type which can result in `type_id::<Ty>() != ty_id::<Ty>()` if we then call `type_id` of the polymorphized type

Comment (davidtwco) [reply src/librustc_mir/interpret/util.rs:58]: I don't think this could just be an `else` on that conditional, given that if it is used, but doesn't need substitution, then it won't be `ty::Param`, but that assert will be hit regardless. I wasn't sure initially given that `subst` might not be a `ty::Param` but something containing one -  though I think I've convinced myself something like this would probably work.

Comment (davidtwco) [reply src/librustc_mir/interpret/util.rs:58]: Implemented this in #75155.
