### PR TITLE
Emit error when using path-segment keyword as cfg pred

### LINKED ISSUE #146968: `cfg!($crate)`, `cfg!(crate)`, `cfg!(self)`, `cfg!(Self)`, and `cfg!(super)` should not be accepted
I tried this code:

```rust
macro_rules! foo {
    () => {
        cfg!($crate)
    };
}

fn main() {
    let b = foo!();
    println!("{b}");
}
```

I expected a compile error. Instead, I got the following warning, but the code compiles fine and prints `false`.

```
warning: unexpected `cfg` condition name: `$crate`
 --> src/main.rs:3:14
  |
3 |         cfg!($crate)
  |              ^^^^^^
...
8 |     let b = foo!();
  |             ------ in this macro invocation
  |
  = help: expected names are: `docsrs`, `feature`, and `test` and 31 more
  = help: consider using a Cargo feature instead
  = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
           [lints.rust]
           unexpected_cfgs = { level = "warn", check-cfg = ['cfg($crate)'] }
  = help: or consider adding `println!("cargo::rustc-check-cfg=cfg($crate)");` to the top of the `build.rs`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the macro `foo` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Since it's impossible to set the value of this `cfg`, I think this should cause a compile error.

See also #146967 for more nonsense with `$crate`.

### Meta

Reproducible on the playground with version `1.92.0-nightly (2025-09-23 975e6c8fec280816d24f)`

### PR DESCRIPTION
**Pull request by mu001999**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/146978)*

Fixes rust-lang/rust#146968

Emit error `CfgPredicateIdentifier` if the word is path-segment keyword.

Detailed change description - https://github.com/rust-lang/rust/pull/146978#issuecomment-3437353950.

r? petrochenkov

### CODE REVIEW

File: tests/ui/cfg/path-kw-as-cfg-pred-cli-cfg.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+//@ edition: 2024
+//@ check-fail
```
Comment (petrochenkov) [inline tests/ui/cfg/path-kw-as-cfg-pred-cli-cfg.rs]: This should be unnecessary, UI tests are check-fail by default.
(Same in one more test below.)

File: tests/ui/cfg/path-kw-as-cfg-pred-cli-cfg.rs [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+//@ [cfg_crate]compile-flags: --cfg crate
+//@ [cfg_super]compile-flags: --cfg super
+//@ [cfg_self_lower]compile-flags: --cfg self
+//@ [cfg_self_upper]compile-flags: --cfg Self
+
+//@ [cfg_struct]compile-flags: --cfg struct
+//@ [cfg_enum]compile-flags: --cfg enum
+//@ [cfg_async]compile-flags: --cfg async
+//@ [cfg_impl]compile-flags: --cfg impl
+//@ [cfg_trait]compile-flags: --cfg trait
```
Comment (petrochenkov) [inline tests/ui/cfg/path-kw-as-cfg-pred-cli-cfg.rs]: Let's use `struct`, `priv` and `_` as the keyword list for testing instead of these 5 keywords, that would be a more interesting list because it would cover some non-`is_used_keyword_*` cases.
(This applies to all tests.)

File: tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs [hunk 3]
```diff
@@ -1,5 +1,9 @@
-//@ revisions: become return
-//@ [become] run-pass
+//@ revisions: become_ return_
+//@ [become_] run-pass
+//@ [become_] compile-flags: --cfg r#become
+//@ [return_] compile-flags: --cfg r#return
```
Comment (petrochenkov) [inline tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs]: Why are these two lines necessary?

File: compiler/rustc_parse/src/parser/mod.rs [hunk 4]
```diff
@@ -181,6 +181,7 @@ pub struct Parser<'a> {
     /// The previous token.
     pub prev_token: Token,
     pub capture_cfg: bool,
+    pub parse_cfg_pred: bool,
```
Comment (petrochenkov) [inline compiler/rustc_parse/src/parser/mod.rs]: I don't think this is a good approach, it turns a local problem (`interface::parse_cfg` swallowing legitimate errors by using fatal-only emitter) into a concern for the whole parsing infrastructure.

What prevents `parse_cfg` from using a regular non-fatal-only emitter?
Or at least setting `Recovery::Forbidden` in the `Parser`?

Comment (mu001999) [reply compiler/rustc_parse/src/parser/mod.rs]: This is ~~not only for `interface::parse_cfg` but also~~ for parsing `#[cfg(...)]`

Comment (petrochenkov) [reply compiler/rustc_parse/src/parser/mod.rs]: Hm, looks like `with_fatal_emitter` is only used when parsing `--cfg` and `--check-cfg`.
So at least we are not swallowing errors in any other cases.
I'm looking through the git history to understand why it was used there in the first place.

Comment (mu001999) [reply compiler/rustc_parse/src/parser/mod.rs]: sorry, I make a mistake. This flag is used for parsing `#[cfg(...)]`

Comment (mu001999) [reply compiler/rustc_parse/src/parser/mod.rs]: `interface::parse_cfg` won't use it in fact, becasue it will ignore errors during parsing, and the new `interface::parse_cfg`  still just check the final recovered result and then emit proper errors.

And this flag works when we parsing `#[cfg(...)]` and then call `parse_meta_attr`, `parse_cfg_pred` will make the first is parsed by `parse_ident` instead of `parse_path`.

Comment (petrochenkov) [reply compiler/rustc_parse/src/parser/mod.rs]: > Hm, looks like `with_fatal_emitter` is only used when parsing `--cfg` and `--check-cfg`. So at least we are not swallowing errors in any other cases. I'm looking through the git history to understand why it was used there in the first place.

So https://github.com/rust-lang/rust/pull/64467 originally improved some diagnostics, but introduced bugs (swallowing errors).
Then https://github.com/rust-lang/rust/pull/89468 fixed the bug, but incompletely.

I'd rather make the diagnostics worse again than preserve the bugs.

Comment (petrochenkov) [reply compiler/rustc_parse/src/parser/mod.rs]: >And this flag works when we parsing `#[cfg(...)]` and then call `parse_meta_attr`, `parse_cfg_pred` will make the first is parsed by `parse_ident` instead of `parse_path`.

Introducing a global parser state is sort of a last resort.
Introducing a new parsing function, or a new argument to an existing parsing function is preferable.
In case of `cfg` predicates the desired syntax is a subset of paths, so using a post-processing check after parsing is fine, I think it's better to keep doing that.

Comment (mu001999) [reply compiler/rustc_parse/src/parser/mod.rs]: > I'd rather make the diagnostics worse again than preserve the bugs.

I will try to use a regular emitter and check if there will be any problems.

Comment (mu001999) [reply compiler/rustc_parse/src/parser/mod.rs]: > so using a post-processing check after parsing is fine, I think it's better to keep doing that.

Current impl is because I tried to support raw path-segement kw. And the post-precessing check cannot know whether the source is raw or now, so it will deny all usage although raw.

Then I use current way to deny non-raw them when parsing. But I find raw path-segement kw will destroy many things.

So, I agree and will recover the old impl.

File: tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs (hunk 3 above)
Comment (mu001999) [reply tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs]: The old regex cannot capture `//[r#return]~ ERROR`, has updated the regex.

https://github.com/rust-lang/rust/blob/f8ee9f018c53c7555c07a035ff2efaad9723adc9/src/tools/compiletest/src/errors.rs#L143-L147

File: compiler/rustc_interface/src/interface.rs
Comment (mu001999) [inline compiler/rustc_interface/src/interface.rs]: @petrochenkov `interface::parse_cfg` and `interface::parse_check_cfg` call `parse_meta_item` directly, so I think current approach is good enough. It is appropriate to process the meta item result below.

Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: `parse_meta_item` won't emit error when parsing `#[cfg(crate)]` because it is a valid path.

File: tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs (hunk 3 above)
Comment (petrochenkov) [reply tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs]: No, I mean if the revision is `return_`, then `--cfg return_` will be passed, and `#[cfg(return_)]` will be usable in code.
It's better to keep the revision syntax and compiletest regexes as is.

File: compiler/rustc_interface/src/interface.rs [hunk 5]
```diff
@@ -63,8 +63,8 @@ pub(crate) fn parse_cfg(dcx: DiagCtxtHandle<'_>, cfgs: Vec<String>) -> Cfg {
                     #[allow(rustc::untranslatable_diagnostic)]
                     #[allow(rustc::diagnostic_outside_of_impl)]
                     dcx.fatal(format!(
-                        concat!("invalid `--cfg` argument: `{}` (", $reason, ")"),
-                        s
+                        concat!("invalid `--cfg` argument: `{}` ({})"),
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]: It looks like `concat` is not needed here anymore.

File: tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs (hunk 3 above)
Comment (mu001999) [reply tests/ui/explicit-tail-calls/ctfe-id-unlimited.rs]: Updated ;)

File: compiler/rustc_interface/src/interface.rs [hunk 6]
```diff
@@ -83,6 +83,19 @@ pub(crate) fn parse_cfg(dcx: DiagCtxtHandle<'_>, cfgs: Vec<String>) -> Cfg {
                             }
                             MetaItemKind::NameValue(..) | MetaItemKind::Word => {
                                 let ident = meta_item.ident().expect("multi-segment cfg key");
+
+                                if ident.is_reserved() {
+                                    if !ident.name.can_be_raw() {
+                                        if s.trim().starts_with(&format!("r#{}", ident.as_str())) {
+                                            error!(format!("argument key must be an identifier, but `{}` cannot be a raw identifier", ident.name));
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]: So now we have to manually detect all recoverable parsing errors here, not just keywords instead of identifiers.
The set of recoverable errors is open, parser does much more recovery now than at the times of https://github.com/rust-lang/rust/pull/64467, you can't catch them all manually.

If we don't want to remove the use of fatal-only emitter, then we need to set `Recovery::Forbidden` in the parser, then `parse_meta_item` will return `Err` on any syntactically invalid stuff instead of recovering.
Then the only remaining thing to check will be `is_path_segment_keyword`, like in `rustc_attr_parsing`.

File: tests/ui/cfg/raw-true-false.rs
Comment (Urgau) [inline tests/ui/cfg/raw-true-false.rs:1]: Note that this test and the change in behavior of `--check-cfg` was specifically added at the request of T-lang in the stabilization of `#[cfg(true)]`/`#[cfg(false)]` https://github.com/rust-lang/rust/pull/138632#issuecomment-2737254098

Comment (petrochenkov) [reply tests/ui/cfg/raw-true-false.rs:1]: This PR will need to go through lang team too after a crater run.
(Similarly to other cases in this PR, this test case was accepted because `--cfg` parsing swallowed non-fatal parsing errors.)

**Comment by mu001999** [comment]
> It looks like you removed some `.32bit.stderr` files from `src/tools/clippy/tests/ui/` instead of renaming them.

Good catch! Recovered. Seems the 32bit revision is not tested on both myself device and CI 🤔

File: compiler/rustc_interface/src/interface.rs [hunk 7]
```diff
@@ -63,35 +64,47 @@ pub(crate) fn parse_cfg(dcx: DiagCtxtHandle<'_>, cfgs: Vec<String>) -> Cfg {
...
+                                        error!(format!("argument key must be an identifier, but `{}` cannot be a raw identifier", ident.name));
+                                    }
+
+                                    return (ident.name, meta_item.value_str());
+                                }
                             }
                         }
+                        Ok(..) => {}
+                        Err(err) => {
+                            err.emit();
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]: Canceling these errors and reporting the generic `error!` below was the point of https://github.com/rust-lang/rust/pull/64467.
I think we can still do it, if the input is not a meta-item.
(Same applies to `check-cfg`.)

File: compiler/rustc_interface/src/interface.rs [hunk 8]
```diff
@@ -52,7 +53,7 @@ pub struct Compiler {
 pub(crate) fn parse_cfg(dcx: DiagCtxtHandle<'_>, cfgs: Vec<String>) -> Cfg {
     cfgs.into_iter()
         .map(|s| {
-            let psess = ParseSess::with_fatal_emitter(
+            let psess = ParseSess::with_error_emitter(
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]: Why are the emitter changes necessary if we set `Recovery::Forbidden`?
Without recovery parsing should not emit errors anyway, it will return `Err` instead.
(Same applies to `check-cfg`.)

File: compiler/rustc_interface/src/interface.rs [hunk 9]
```diff
@@ -63,35 +64,47 @@ pub(crate) fn parse_cfg(dcx: DiagCtxtHandle<'_>, cfgs: Vec<String>) -> Cfg {
...
-                                return (ident.name, meta_item.value_str());
+                            match &meta_item.kind {
+                                MetaItemKind::List(..) => {}
+                                MetaItemKind::NameValue(lit) if !lit.kind.is_str() => {
+                                    error!("argument value must be a string");
+                                }
+                                MetaItemKind::NameValue(..) | MetaItemKind::Word => {
+                                    let ident = meta_item.ident().expect("multi-segment cfg key");
+
+                                    if !ident.name.can_be_raw() {
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                                    if ident.is_path_segment_keyword() {
```
I don't think it makes a difference here, but just for symmetry with the attribute parsing logic.
(Same applies to `check-cfg`.)

File: compiler/rustc_interface/src/interface.rs [hunk 10]
```diff
@@ -173,16 +186,19 @@ pub(crate) fn parse_check_cfg(dcx: DiagCtxtHandle<'_>, specs: Vec<String>) -> Ch
             {
                 Ok(parser) => parser,
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                Ok(parser) => parser.recovery(Recovery::Forbidden),
```

File: compiler/rustc_interface/src/interface.rs (hunk 8 above)
Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: some errors will be emitted directly instead of returing: https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/lexer/mod.rs#L230-L239

Comment (petrochenkov) [reply compiler/rustc_interface/src/interface.rs]: Technically they should also return `Err` if recovery is forbidden, but it may be harder to change than `parse_ident`.
Then I think we can just use the "regular" emitter here.
(`FatalOnlyEmitter` and some other stuff will become dead code and could be removed.)

File: compiler/rustc_interface/src/interface.rs (hunk 9 above)
Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: Using `can_be_raw` here because the ident may be `_`, so that `--cfg _` will exit with 0 instead of failure.

And the attribute parsing logic uses `is_path_segment_keyword` is OK because the error during lexing will lead to exit with failure.

Comment (petrochenkov) [reply compiler/rustc_interface/src/interface.rs]: I'd expect `--cfg _` to be a parsing error and return `Err` from `parse_meta_item`.
Why doesn't it happen? It shouldn't be different from e.g. `--cfg struct`.

File: compiler/rustc_interface/src/interface.rs (hunk 8 above)
Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: `ErrorOnlyEmitter` adds note indicates the error occurs while parsing `--cfg ...` and deny warnings.

Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: I'd like to keep the note.

Comment (petrochenkov) [reply compiler/rustc_interface/src/interface.rs]: >adds note indicates the error occurs while parsing `--cfg ...`

Ok, this part may be hard to reproduce without a separate emitter.
Let's keep it for now, and maybe refactor later.

>deny warnings.

This part is no longer relevant, hardcoded warnings are exceedingly rare, and it's not a problem if they are emitted.
The `diag.is_error()` part can be removed, and the emitter can be renamed to something indicating that it adds a note to every diagnostic.

File: compiler/rustc_interface/src/interface.rs (hunk 9 above)
Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: sorry, that should be `--cfg="r#_"`.

Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: Also due to https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/lexer/mod.rs#L230-L239

The error is emitted but the ident ('\_') is returned. So we will get the ident ('\_') here.

Comment (petrochenkov) [reply compiler/rustc_interface/src/interface.rs]: So we get a double error on `r#_` here.
Can we just mirror both the condition and wording from the attribute parsing infra? I don't think saying the "cannot be a raw identifier" part is too important.

Comment (mu001999) [reply compiler/rustc_interface/src/interface.rs]: > Can we just mirror both the condition and wording from the attribute parsing infra

Do you mean `malformed `cfg` attribute input, expected a valid identifier`?

Comment (petrochenkov) [reply compiler/rustc_interface/src/interface.rs]: Yes, just without the "attribute" parts.

**Comment by mu001999** [comment]
@petrochenkov Cool! Thanks!

**Comment by tmandry** [comment]
@rfcbot reviewed

File: compiler/rustc_interface/src/interface.rs [hunk 11]
```diff
@@ -52,46 +53,57 @@ pub struct Compiler {
...
 
             macro_rules! error {
                 ($reason: expr) => {
                     #[allow(rustc::untranslatable_diagnostic)]
                     #[allow(rustc::diagnostic_outside_of_impl)]
-                    dcx.fatal(format!(
-                        concat!("invalid `--cfg` argument: `{}` (", $reason, ")"),
-                        s
-                    ));
+                    dcx.fatal(format!("invalid `--cfg` argument: `{}` ({})", s, $reason,));
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                    dcx.fatal(format!("invalid `--cfg` argument: `{s}` ({})", $reason));
```

File: compiler/rustc_interface/src/interface.rs [hunk 12]
```diff
@@ -52,46 +53,57 @@ pub struct Compiler {
...
-                                return (ident.name, meta_item.value_str());
+                            match &meta_item.kind {
+                                MetaItemKind::List(..) => {}
+                                MetaItemKind::NameValue(lit) if !lit.kind.is_str() => {
+                                    error!("argument value must be a string");
+                                }
+                                MetaItemKind::NameValue(..) | MetaItemKind::Word => {
+                                    let ident = meta_item.ident().expect("multi-segment cfg key");
+
+                                    if !ident.name.can_be_raw() {
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                                    if ident.is_path_segment_keyword()
```
Again, `_` should be already reported as a parsing error.

File: compiler/rustc_interface/src/interface.rs [hunk 13]
```diff
@@ -52,46 +53,57 @@ pub struct Compiler {
...
+                                        );
+                                    }
+
+                                    return (ident.name, meta_item.value_str());
+                                }
                             }
                         }
+                        Ok(..) => {}
+                        Err(err) => {
+                            err.cancel();
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                            err.cancel()
```
Unnecessary formatting changes due to semicolon here and in two places below.

File: compiler/rustc_interface/src/interface.rs [hunk 14]
```diff
@@ -209,11 +223,17 @@ pub(crate) fn parse_check_cfg(dcx: DiagCtxtHandle<'_>, specs: Vec<String>) -> Ch
                 if values_specified {
                     error!("`cfg()` names cannot be after values");
                 }
+
+                if !ident.name.can_be_raw() {
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]:
```suggestion
                if ident.is_path_segment_keyword() {
```

File: compiler/rustc_interface/src/interface.rs [hunk 15]
```diff
@@ -209,11 +223,17 @@ pub(crate) fn parse_check_cfg(dcx: DiagCtxtHandle<'_>, specs: Vec<String>) -> Ch
...
+                    error!("malformed `cfg` input, expected a valid identifier");
+                }
+
                 names.push(ident);
             } else if let Some(boolean) = arg.boolean_literal() {
                 if values_specified {
                     error!("`cfg()` names cannot be after values");
                 }
+
```
Comment (petrochenkov) [inline compiler/rustc_interface/src/interface.rs]: Nit: unnecessary whitespace change.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Comment by ehuss** [comment]
Filed https://github.com/rust-lang/rust/issues/148910

**Comment by Zalathar** [comment]
Possibly failed in rollup: https://github.com/rust-lang/rust/pull/148927#issuecomment-3530436860

@bors r-

**Comment by mu001999** [comment]
I will request retry after cargo updated
