### PR TITLE
Prevent bumping the parser past the EOF.

### LINKED ISSUE #32446: Regression on beta: three dots in a trait leads to an infinite loop(?)
```rust
trait T { ... }
```
(Yes, just a single line.)

```
$ ulimit -t 3
$ multirust run stable rustc ~tmp/lone-incl-range-in-trait.rs
/tmp/nodakai//lone-incl-range-in-trait.rs:1:11: 1:14 error: expected one of `const`, `extern`, `fn`, `type`, or `unsafe`, found `...`
/tmp/nodakai//lone-incl-range-in-trait.rs:1 trait T { ... }
                                                      ^~~
error: aborting due to previous error
$ multirust run stable rustc --version
rustc 1.7.0 (a5d1e7a59 2016-02-29)
$ multirust run beta rustc ~tmp/lone-incl-range-in-trait.rs
zsh: cpu limit exceeded  multirust run beta rustc ~tmp/lone-incl-range-in-trait.rs
$ multirust run beta rustc --version
rustc 1.8.0-beta.1 (facbfdd71 2016-03-02)
$ multirust run nightly rustc ~tmp/lone-incl-range-in-trait.rs
zsh: cpu limit exceeded  multirust run nightly rustc ~tmp/lone-incl-range-in-trait.rs
$ multirust run nightly rustc --version
rustc 1.9.0-nightly (21922e1f4 2016-03-21)
```

Possibly related to #32245 ?

Like #32445 , it was found during `make check-docs`. One doctest contained three dots probably just to mean some codes had been omitted.
- https://doc.rust-lang.org/error-index.html#E0273

### PR DESCRIPTION
**Pull request by eddyb**
Makes `Parser::bump` after EOF into an ICE, forcing callers to avoid repeated EOF bumps.
This ICE is intended to break infinite loops where EOF wasn't stopping the loop.

For example, the handling of EOF in `parse_trait_items`' recovery loop fixes #32446.
But even without this specific fix, the ICE is triggered, which helps diagnosis and UX.

This is a `[breaking-change]` for plugins authors who eagerly eat multiple EOFs.
See https://github.com/docopt/docopt.rs/pull/171 for such an example and the necessary fix.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
starting a crater run

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -1282,12 +1290,19 @@ impl<'a> Parser<'a> {
                     Err(e) => {
                         loop {
                             p.bump();
-                            if p.token == token::Semi {
+
+                            // Don't bump past the EOF.
+                            if p.token == token::Eof {
```
Comment (nagisa) [inline src/libsyntax/parse/parser.rs]: To me it feels like at this point converting this chain to a `match` would be better here.

File: src/libsyntax/parse/parser.rs [hunk 2]
```diff
@@ -2777,9 +2792,13 @@ impl<'a> Parser<'a> {
 
                 // Parse the close delimiter.
                 let close_span = self.span;
-                self.bump();
                 self.open_braces.pop().unwrap();
 
+                // Don't bump past the EOF.
+                if self.token != token::Eof {
+                    self.bump();
```
Comment (nagisa) [inline src/libsyntax/parse/parser.rs]: Perhaps a utility function like `self.bump_even_through_eof()` would be suitable?

Comment (eddyb) [inline src/libsyntax/parse/parser.rs]: That's just asking to be called in a loop instead of manually analyzing each use site.

File: src/libsyntax/parse/parser.rs (hunk 1 above)
Comment (eddyb) [inline src/libsyntax/parse/parser.rs]: I wish `loop`-`match` was a bit more first-class, but I agree.

**Comment by nikomatsakis** [comment]
Crater report: https://gist.github.com/nikomatsakis/416a719bf29fb0fa8028


    4431 crates tested: 2819 working / 1508 broken / 7 regressed / 1 fixed / 96 unknown.

haven't investigated yet.

**Comment by eddyb** [comment]
Looks like this breaks syntax extensions (`regex`, `peg` and `docopt`, at least).

**Comment by nikomatsakis** [comment]
cc @BurntSushi @kevinmehall -- curious to get your take here. In response to various bugs where the parser was looping infinitely, @eddyb implemented a change that caused the `bump` method to panic if you attempt to bump *past* EOF. This breaks some of your syntax extension crates. We're debating whether to land it and under what conditions. (One option might be to modify your crates.)

@eddyb, I know you were attempting to modify the PR to only abort if we bumped past EOF multiple times, what was the outcome of those experiments?

**Comment by eddyb** [comment]
@nikomatsakis Actually, that's the current state, but `parse_unspanned_seq` is giving me trouble because it's unconditionally bumping a token, even if it's not the `ket` and the travis failure was because that changes how errors are reported (presumably due to the "expected tokens" list which `check`, used by `eat`, pushes onto).

I realize right now that I can just handle the error case by not bumping, and I just pushed that change.

**Comment by BurntSushi** [comment]
@nikomatsakis I'm totally fine with breakage of plugins if there's a path to fixing them.

With that said, what part of the parsing code would break? Regex's interaction with the parser is quite small: https://github.com/rust-lang-nursery/regex/blob/master/regex_macros/src/lib.rs#L567

I guess it's clearer where it breaks in docopt: https://github.com/docopt/docopt.rs/blob/master/docopt_macros/src/macro.rs#L234

**Comment by eddyb** [comment]
@BurntSushi The original changes would make `parser.eat(&token::Eof)` always ICE - but that seemed impractical so I'm trying something which will only trigger on the second EOF bump, not the first one.

**Comment by kevinmehall** [comment]
`peg` [uses](https://github.com/kevinmehall/rust-peg/blob/fadcb5d7406f13dcc791e2570674a454359e6b5d/src/peg_syntax_ext.rs#L97) `parser.eat` to obtain the string literal from a `peg!("grammar goes here")` invocation and check that no additional arguments are passed. If there's a better way to do that, I'm happy to change it. Unstable interfaces are unstable, after all.

**Comment by eddyb** [comment]
@kevinmehall Changing that shouldn't be necessary with my latest attempt - just waiting for travis to confirm everything's good with the tests before starting another crater run.

**Comment by eddyb** [comment]
@nrc See my changes to `compile-fail` test.
I believe that if we switch away from parsing *everything* as TTs first we can handle `;` closing `(`, for example:

```rust
{ option.map(|some| 42; }
```

It currently parses as the following TTs:
```rust
{ option.map(|some| 42;) }
```

It *accidentally* gave relatively sane errors because `parse_unspanned_seq` was bumping the `;` as if it was `)` for the method call, resulting in the same effect as this:
```rust
{ option.map(|some| 42)) }
```

I fixed that so it behaves as it should, *given what TTs we end up with*, but if we didn't parse it to TTs, we could recover a statement based on `;` and parse as:
```rust
{ option.map(|some| 42); }
```

Which is arguably what the intention was, and save for a single parse error, the compilation could continue unhindered.

**Comment by nikomatsakis** [comment]
Sounds good

**Comment by nrc** [comment]
lgtm
