### PR TITLE
Download rustfmt regardless of rustc being set in config.toml

### LINKED ISSUE #81155: `./x.py fmt` uses incorrect rustfmt with download-ci-llvm=true and custom rustc (not stage0/beta)
On master branch with commit c4df63f47f37cfb8fff80919be560e4d51ae9a44, replace `RUSTUP_HOME` 
with actual value and apply this diff:

```diff
% diff config.toml.example config.toml
--- config.toml.example 2021-01-18 02:40:45.127363851 +0000
+++ config.toml 2021-01-18 05:34:16.052659202 +0000
@@ -45,7 +45,7 @@
 #
 # Note that many of the LLVM options are not currently supported for
 # downloading. Currently only the "assertions" option can be toggled.
-#download-ci-llvm = false
+download-ci-llvm = true
 
 # Indicates whether LLVM rebuild should be skipped when running bootstrap. If
 # this is `false` then the compiler's LLVM will be rebuilt whenever the built
@@ -193,11 +193,11 @@
 
 # Instead of downloading the src/stage0.txt version of Cargo specified, use
 # this Cargo binary instead to build all Rust code
-#cargo = "/path/to/bin/cargo"
+cargo = "$RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo"
 
 # Instead of downloading the src/stage0.txt version of the compiler
 # specified, use this rustc binary instead as the stage0 snapshot compiler.
-#rustc = "/path/to/bin/rustc"
+rustc = "$RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc"
 
 # Instead of download the src/stage0.txt version of rustfmt specified,
 # use this rustfmt binary instead as the stage0 snapshot rustfmt.
```
</details>

Run `./x.py fmt` after that. Then run `git status` to check status of the repo.

I expected to see this happen: Nothing should change.

Instead, this happened: Many files changed dues to using wrong rustfmt.

cc @Mark-Simulacrum as in https://github.com/rust-lang/rust/pull/81152#issuecomment-761965481

@rustbot label T-infra

### Meta

```
% rustc -Vv
rustc 1.51.0-nightly (4253153db 2021-01-17)
binary: rustc
commit-hash: 4253153db205251f72ea4493687a31e04a2a8ca0
commit-date: 2021-01-17
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### PR DESCRIPTION
**Pull request by KittyBorgX**
Fixes #81155 

cc : https://github.com/rust-lang/rust/issues/108210 for exact error details

### CODE REVIEW

File: src/bootstrap/config.rs [hunk 1]
```diff
@@ -1562,7 +1562,16 @@ impl Config {
...
+            RustfmtState::SystemToolchain(_) => {
+                let path = self.maybe_download_rustfmt();
+                if let Some(p) = &path {
+                    RustfmtState::Downloaded(p.clone())
+                } else {
+                    RustfmtState::Unavailable
+                };
+                path
+            }
+            RustfmtState::Downloaded(p) => Some(p.clone()),
```
Comment (jyn514) [inline src/bootstrap/config.rs:1574]: This not the right fix. We allow explicitly configuring a rustfmt in https://github.com/rust-lang/rust/blob/956ad918b9f6b923b897ffc9589c7200ceef7a9a/config.toml.example#L222-L224 and in that case we should continue to respect that option instead of downloading rustfmt.

Try looking around https://github.com/rust-lang/rust/blob/956ad918b9f6b923b897ffc9589c7200ceef7a9a/src/bootstrap/config.rs#L1128-L1134 instead.

**Review by jyn514 — CHANGES_REQUESTED** [review]

**Comment by jyn514** [comment]
r? jyn514

@bors r+ rollup
