### PR TITLE
don't suggest non-deriveable traits for unions

### LINKED ISSUE #137587: consider annotating `Union` with `#[derive(Debug)]` is misleading
### Code

```Rust
union Union {
    member: usize,
}

impl PartialEq<u8> for Union {
    fn eq(&self, rhs: &u8) -> bool {
        unsafe { self.member == (*rhs).into() }
    }
}

fn main() {
    assert_eq!(Union { member: 0, }, 0);
}
```

### Current output

```Shell
error[E0277]: `Union` doesn't implement `Debug`
  --> src/main.rs:13:5
   |
13 |     assert_eq!(Union { member: 0, }, 0);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Union` cannot be formatted using `{:?}`
   |
   = help: the trait `Debug` is not implemented for `Union`
   = note: add `#[derive(Debug)]` to `Union` or manually `impl Debug for Union`
   = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `Union` with `#[derive(Debug)]`
   |
2  + #[derive(Debug)]
3  | union Union {
   |

For more information about this error, try `rustc --explain E0277`.
```

### Desired output

```Shell
error[E0277]: `Union` doesn't implement `Debug`
  --> src/main.rs:13:5
   |
13 |     assert_eq!(Union { member: 0, }, 0);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Union` cannot be formatted using `{:?}`
   |
   = help: the trait `Debug` is not implemented for `Union`
   = note: add `#[derive(Debug)]` to `Union` or manually `impl Debug for Union`
   = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
```

### Rationale and extra context

The help in the error should be removed when the type is a union, because if you follow that instruction, you will just run into the "this trait cannot be derived for unions" error.

### Other cases

```Rust

```

### Rust Version

```Shell
I tested it with stable in playground.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=baa42bb5a36216b734f9eb665173a70b
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by malezjaa**
Fixes rust-lang/rust#137587 

Before, the compiler suggested adding `#[derive(Debug)]` (other traits too) for unions,
which is misleading because some traits can't be automatically derived.

Only traits that are still suggested are Copy and Clone.

I noticed the error label changed after removing the suggestion. I hope this isn't a big deal, but let me know if that's an issue.

original example:
```rs
union Union {
    member: usize,
}

impl PartialEq<u8> for Union {
    fn eq(&self, rhs: &u8) -> bool {
        unsafe { self.member == (*rhs).into() }
    }
}

fn main() {
    assert_eq!(Union { member: 0 }, 0);
}
```

before:
```
error[E0277]: `Union` doesn't implement `Debug`                                                                       
  --> src\main.rs:13:5
   |
13 |     assert_eq!(Union { member: 0 }, 0);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Debug` is not implemented for `Union`
   |
   = note: add `#[derive(Debug)]` to `Union` or manually `impl Debug for Union`
   = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `Union` with `#[derive(Debug)]`
   |
 2 + #[derive(Debug)]
 3 | union Union {
   |
```

after (the message doesn't suggest adding #[derive(Debug)] to unions) 
```
error[E0277]: `Union` doesn't implement `Debug`                                                                       
  --> src\main.rs:13:5
   |
13 |     assert_eq!(Union { member: 0 }, 0);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound
   |
help: the trait `Debug` is not implemented for `Union`
  --> src\main.rs:2:1
   |
 2 | union Union {
   | ^^^^^^^^^^^
   = note: manually `impl Debug for Union`
```

### CODE REVIEW

File: library/core/src/fmt/mod.rs [hunk 1]
```diff
@@ -1037,9 +1037,10 @@ impl Display for Arguments<'_> {
 #[stable(feature = "rust1", since = "1.0.0")]
 #[rustc_on_unimplemented(
     on(
-        crate_local,
+        all(crate_local, not(Self = "{union}")),
```
Comment (JonathanBrouwer) [inline library/core/src/fmt/mod.rs:1040]: The original issue mentions more places where this is useful, could you also fix those and add tests for those?
https://github.com/rust-lang/rust/issues/137587#issuecomment-2681199700

File: compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs [hunk 2]
```diff
@@ -460,9 +460,10 @@ fn parse_filter(input: Symbol) -> FilterFormatString {
                 // if the integer type has been resolved, to allow targeting all integers.
                 // `"{integer}"` and `"{float}"` come from numerics that haven't been inferred yet,
                 // from the `Display` impl of `InferTy` to be precise.
+                // `"{union}"` is used as a special selector for union self types.
                 //
                 // Don't try to format these later!
-                Position::ArgumentNamed(arg @ ("integer" | "integral" | "float")) => {
+                Position::ArgumentNamed(arg @ ("integer" | "integral" | "float" | "union")) => {
```
Comment (JonathanBrouwer) [inline compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs]: It feels a bit weird to add `{union}` but not `{struct}` and `{enum}`, can we also add those?

File: compiler/rustc_trait_selection/src/error_reporting/traits/on_unimplemented.rs [hunk 3]
```diff
@@ -133,6 +133,10 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
                 self_types.push("{integral}".to_owned());
             }
 
+            if self_ty.ty_adt_def().is_some_and(|def| def.is_union()) {
```
Comment (JonathanBrouwer) [inline compiler/rustc_trait_selection/src/error_reporting/traits/on_unimplemented.rs]: I noticed that these options are not documented in the reference
https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-diagnostic-tool-attribute-namespace
Would be nice if we can add them

File: compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs (hunk 2 above)
Comment (JonathanBrouwer) [inline compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs]: We should also still really figure out whether this change needs T-lang approval or not, I think T-lang has never explicitly said that we can freely make changes to diagnostic attrs

**Review by JonathanBrouwer — CHANGES_REQUESTED** [review]

File: library/core/src/fmt/mod.rs (hunk 1 above)
Comment (malezjaa) [reply library/core/src/fmt/mod.rs:1040]: I checked the other traits mentioned in the issue. They don’t provide custom on_unimplemented messages suggesting #[derive(...)] (like Debug does), so they fall back to the default suggestion, which is now disabled for unions. There’s no misleading suggestion to fix there. If you had something else in mind, let me know.

Comment (JonathanBrouwer) [reply library/core/src/fmt/mod.rs:1040]: Ah that makes sense
Could you add a test for those then :)

**Comment by JonathanBrouwer** [comment]
cc @mejrs 
if you feel like it, could you also take a look?

File: compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs (hunk 2 above)
Comment (mejrs) [reply compiler/rustc_attr_parsing/src/attributes/diagnostic/mod.rs]: This is only reachable from rustc_on_unimplemented, thus perma unstable, so any changes here should be fine.

File: compiler/rustc_trait_selection/src/error_reporting/traits/on_unimplemented.rs (hunk 3 above)
Comment (mejrs) [reply compiler/rustc_trait_selection/src/error_reporting/traits/on_unimplemented.rs]: They are documented at https://rustc-dev-guide.rust-lang.org/diagnostics.html#rustc_on_unimplemented @malezjaa Can you please update this? Up to you if that's in this PR or a separate PR to https://github.com/rust-lang/rustc-dev-guide

Comment (malezjaa) [reply compiler/rustc_trait_selection/src/error_reporting/traits/on_unimplemented.rs]: I'll open a new pr in rustc dev guide repo.

File: tests/ui/union/union-no-derive-suggestion.rs [hunk 4]
```diff
@@ -0,0 +1,34 @@
+//@ dont-require-annotations: NOTE
```
Comment (mejrs) [inline tests/ui/union/union-no-derive-suggestion.rs:3]:
```suggestion
//! Check that we do not suggest using `#[derive(...)]` for unions,
//! as some traits cannot be autoderived for them.

//@ dont-require-annotations: NOTE
```

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 5]
```diff
@@ -4037,14 +4037,17 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
             sym::Default => !adt.is_enum(),
             sym::PartialEq | sym::PartialOrd => {
                 let rhs_ty = trait_pred.skip_binder().trait_ref.args.type_at(1);
                 trait_pred.skip_binder().self_ty() == rhs_ty
             }
-            sym::Eq | sym::Ord | sym::Clone | sym::Copy | sym::Hash | sym::Debug => true,
+            sym::Eq | sym::Ord | sym::Hash | sym::Debug => true,
             _ => false,
         };
+
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: Stray line

```suggestion
```

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 6]
```diff
@@ -4037,14 +4037,17 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
             _ => return false,
         };
         let is_derivable_trait = match diagnostic_name {
+            sym::Copy | sym::Clone => true,
+            _ if adt.is_union() => false,
             sym::Default => !adt.is_enum(),
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs]: I know you didn't write this, but you can autoderive default for enums now. I suspect this code was written before that update.

edit: you can actually just merge this with the sym::Eq arm

```suggestion
            sym::Default => true,
```

**Review by mejrs — APPROVED** [review]
The changes to on_unimplemented look good. I have some suggestions.

Please also update this test https://github.com/rust-lang/rust/blob/bfc05d6b072585dfd0c792ec1b8728c08a3511fe/tests/ui/diagnostic_namespace/on_unimplemented/do_not_accept_options_of_the_internal_rustc_attribute.rs#L28-L43

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154118/bfc05d6b072585dfd0c792ec1b8728c08a3511fe..dd844f361ca8933b57eefa1ae8f2c695d11a6d92)*

**Comment by malezjaa** [comment]
I forgot to rebless the test. Will do that in a sec

File: library/core/src/fmt/mod.rs [hunk 7]
```diff
@@ -1037,9 +1037,10 @@ impl Display for Arguments<'_> {
...
         note = "add `#[derive(Debug)]` to `{Self}` or manually `impl {This} for {Self}`"
     ),
+    on(Self = "{union}", note = "manually `impl {This} for {Self}`"),
```
Comment (mejrs) [inline library/core/src/fmt/mod.rs]:
```suggestion
    on(all(crate_local, Self = "{union}"), note = "manually `impl {This} for {Self}`"),
```

**Review by JonathanBrouwer — APPROVED** [review]
