### PR TITLE
rustdoc: be more strict about "Methods from Deref"

### LINKED ISSUE #24686: rustdoc: `Methods from Deref<Target = T<U>>` is imprecise (contains false positives)
``` rust
use std::ops::Deref;

pub struct Foo<T>(T);
impl Foo<i32> {
    pub fn get_i32(&self) -> i32 { self.0 }
}
impl Foo<u32> {
    pub fn get_u32(&self) -> u32 { self.0 }
}
pub struct Bar(Foo<i32>);
impl Deref for Bar {
    type Target = Foo<i32>;
    fn deref(&self) -> &Foo<i32> {
        &self.0
    }
}
```

The `Methods from Deref` for `Bar` will contain both `get_i32` and `get_u32`, but should only contain `get_i32`.

[Image](http://i.imgur.com/bUEO5pb.png)

### LINKED ISSUE #137083: rustdoc bug: page "ByteStr" is outright wrong: it shows methods for [MaybeUninit<...>]
rustdoc bug: page `ByteStr` is outright wrong: it shows methods for `[MaybeUninit<...>]`

Information on page https://doc.rust-lang.org/nightly/std/bstr/struct.ByteStr.html is currently totally wrong.

After inherent methods we see "Methods from `Deref<Target = [u8]>`". But then instead of methods of `[u8]`, we actually see methods of `[MaybeUninit<T>]`!!! Immediately after header "Methods from `Deref<Target = [u8]>`" we see method `write_copy_of_slice`, which is actually `[MaybeUninit<T>]` method!

@rustbot label: +T-rustdoc

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes #137083
fixes #24686

Currently done:
* [x] fix `render_assoc_items_inner
* [x] fix sidebar logic
* [x] port test from https://github.com/rust-lang/rust/pull/137564
* [x] add test for sidebar items

Note that this does not yet fix the sidebar logic.

### CODE REVIEW

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -1533,6 +1533,14 @@ impl Type {
         matches!(self, Type::BorrowedRef { .. })
     }
 
+    fn is_type_alias(&self) -> bool {
+        if let Type::Path { path: Path { res: Res::Def(DefKind::TyAlias, _), .. } } = &self {
+            true
+        } else {
+            false
+        }
+    }
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/types.rs:1542]:
```suggestion
        matches!(self, Type::Path { path: Path { res: Res::Def(DefKind::TyAlias, _), .. } })
```

File: tests/rustdoc/deref/deref-methods-24686-target.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+pub struct Foo<T>(T);
+impl Foo<i32> {
+    pub fn get_i32(&self) -> i32 { self.0 }
+}
+impl Foo<u32> {
+    pub fn get_u32(&self) -> u32 { self.0 }
+}
+
+// Note that the same href is used both on the method itself,
```
Comment (GuillaumeGomez) [inline tests/rustdoc/deref/deref-methods-24686-target.rs:14]: Isn't it an issue?

Comment (lolbinarycat) [reply tests/rustdoc/deref/deref-methods-24686-target.rs:14]: no, since we're testing that it appears twice, and in any case, we care about the negative case much more, which will trigger if the bad method shows up in the sidebar or on the main page.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for the fix! Squash your commits then r=me.

**Comment by lolbinarycat** [comment]
r=@GuillaumeGomez

(still don't have bors perms so I doubt the r= is going to do anything)
