### PR TITLE
Fix rustdoc::private_doc_tests lint for public re-exported items

### LINKED ISSUE #72081: `warn(private_doc_tests)` warns about republished items
I have doctests on a type in a private module, that's then republished into the crate's top-level module. I think this is a pretty common pattern in Rust?

Here's a simplified example:

```rust
// lib.rs
#[warn(private_doc_tests)]
mod inner {
    /// This is my struct.
    ///
    /// You can make a struct:
    ///
    /// ```
    /// A{}
    /// ```
    pub struct A {}
}

pub use inner::A;
```

If you run rustdoc on this, you'll see

1. The example is visible under the top-level `A` struct.
2. You get a warning about "documentation test in private item"

```
 Documenting rustdoc-warning-example v0.1.0 (/Users/mbp/src/rustdoc-warning-example)
warning: documentation test in private item
 --> src/lib.rs:3:5
  |
3 | /     /// This is my struct.
4 | |     ///
5 | |     /// You can construct it:
6 | |     ///
7 | |     /// ```
8 | |     /// A{}
9 | |     /// ```
  | |___________^
  |
note: the lint level is defined here
 --> src/lib.rs:1:8
  |
1 | #[warn(private_doc_tests)]
  |        ^^^^^^^^^^^^^^^^^

warning: documentation test in private item
 --> src/lib.rs:3:5
  |
3 | /     /// This is my struct.
4 | |     ///
5 | |     /// You can construct it:
6 | |     ///
7 | |     /// ```
8 | |     /// A{}
9 | |     /// ```
  | |___________^

warning: 2 warnings emitted
```

If you run rustdoc, it does build and run the test. 

I expected there would not be a warning, because the doctest is both visible to users, and run. In other words the warning ought to match whether the item is actually visible. 

Also, it seems like a glitch that the warning is reported twice.

Follows on from #55333, #55367, cc @GuillaumeGomez.  

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-beta.2 (b1162ed50 2020-04-25)
binary: rustc
commit-hash: b1162ed5067784cff2bb06afa8910510bf43e2bf
commit-date: 2020-04-25
host: x86_64-apple-darwin
release: 1.44.0-beta.2
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by avitex**
Closes #72081

This involves changing the lint to check the access level is exported, rather than public.
The [exported access level](https://github.com/rust-lang/rust/blob/e91ad5fc62bdee4a29c18baa5fad2ca42fc91bf4/compiler/rustc_middle/src/middle/privacy.rs#L24) accounts for public items and items accessible to other crates with the help of `pub use` re-exports. 
The pattern of re-exporting public items from a private module is usage seen in a number of popular crates.

### CODE REVIEW

File: src/test/rustdoc-ui/public-reexported-item-doc-test.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+mod foo {
+    /// re-exported doc test
+    ///
+    /// ```
+    /// assert!(true);
+    /// ```
+    pub fn bar() {}
+}
+
+pub use foo::bar;
```
Comment (GuillaumeGomez) [inline src/test/rustdoc-ui/public-reexported-item-doc-test.rs:14]: Can you add:

```rust
pub fn foo() {}

pub mod whatever {
    pub fn bar() {}
}
```

to be sure it doesn't warn on public items too please?

Comment (avitex) [reply src/test/rustdoc-ui/public-reexported-item-doc-test.rs:14]: Sure can :)

**Comment by avitex** [comment]
Will this be able to make it to beta? I can rebase onto beta if needed

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I can nominate it to beta, but considering how old the issue is, I'm not sure it'll be accepted.

In any case, I'll approve it once CI pass.

**Comment by GuillaumeGomez** [comment]
Nothing on your side, it's done when the release is being done. They cherry-pick the commits from the nominated PRs and that's it.

**Comment by avitex** [comment]
Awesome, thanks for letting me know

**Comment by GuillaumeGomez** [comment]
I added the tag to the PR and the compiler-team will discuss it at their next meeting once this PR is merged.

**Comment by apiraino** [comment]
Beta backport discussed and declined during compiler team meeting [on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202021-12-30.20.2354818.html#266436127), we can let this patch land in the next beta without backporting.

@rustbot label -beta-nominated

**Comment by camelid** [comment]
> In any case, I'll approve it once CI pass.

@GuillaumeGomez any updates?

**Comment by GuillaumeGomez** [comment]
@camelid I completely forgot to approve it... Don't hesitate to review it as well. ;)

@bors: r+
