### PR TITLE
Suggest making private tuple struct field public

### LINKED ISSUE #52144: Non-public tuple fields causes confusing error message when crossing module boundaries
```
mod first {
    #[derive(Debug)]
    pub struct SomeId(u32);    
}

mod second {
    use ::first::SomeId;

    #[derive(Debug)]    
    pub enum MyEnum {
        Variant1 {
            id: SomeId
        }
    }
}

fn main() {
    use first::SomeId;
    use second::MyEnum;

    let test = MyEnum::Variant1 {
        id: SomeId(32),
    };
    
    println!("{:?}", test);
}
```

This gave me the following error message:

```
error[E0423]: expected function, found struct `SomeId`
  --> src/main.rs:22:13
   |
22 |         id: SomeId(32),
   |             ^^^^^^
   |             |
   |             did you mean `Some`?
   |             constructor is not visible here due to private fields
help: possible better candidate is found in another module, you can import it into scope
   |
1  | use first::SomeId;
   |
```

It turns out the fix for this was to change my struct definition to `pub struct SomeId(pub u32);`.  This was not obvious to me for several reasons:

1. The `expected function, found struct SomeId` is odd because that's what I'm trying to perform, so it appears like it's erroring because it's doing what I want.
1. The suggestion for the use statement is completely incorrect, as that use statement already exists and won't fix the problem
1. The `constructor is not visible here due to private fields` didn't make sense to me as the rust book never gives an example of the `Struct(pub fieldType)` syntax, so I assumed tuple fields had the same visibility as the struct itself.

It probably needs a recommendation for tuple structs to show that all fields should be marked as `pub`

### PR DESCRIPTION
**Pull request by estebank**
Fix #52144.

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1451,6 +1451,26 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+                                &format!(
+                                    "consider making the field{} publicly accessible",
+                                    pluralize!(visibility_spans.len())
+                                ),
+                                visibility_spans
+                                    .iter()
+                                    .map(|span| {
+                                        (
+                                            *span,
+                                            if span.lo() == span.hi() { "pub " } else { "pub" }
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1465]:
```suggestion
                                            if span.is_empty() { "pub " } else { "pub" }
```

File: compiler/rustc_resolve/src/lib.rs [hunk 2]
```diff
@@ -881,6 +881,10 @@ pub struct Resolver<'a> {
     /// Used for hints during error reporting.
     field_names: FxHashMap<DefId, Vec<Spanned<Symbol>>>,
 
+    /// Span of the privacy modifier in fields of an item `DefId` accessible with dot syntax.
+    /// Used for hints during error reporting.
+    field_visibility_spans: FxHashMap<DefId, Vec<Span>>,
+
```
Comment (Nilstrieb) [inline compiler/rustc_resolve/src/lib.rs:887]: Would it make sense to extend and reuse the `field_names` field for this?

Comment (estebank) [reply compiler/rustc_resolve/src/lib.rs:887]: `field_names` only had the `Symbol` and I wasn't sure if there was any place that relied on it being always a `Vec`, causing perf impact if needing to map/collect it every time. But yes, we could do that :)

Comment (estebank) [reply compiler/rustc_resolve/src/lib.rs:887]: The only difference I see is that this approach will only store the privacy span vec for tuple structs and nothing else.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1451,6 +1451,26 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+                                &format!(
+                                    "consider making the field{} publicly accessible",
+                                    pluralize!(visibility_spans.len())
+                                ),
+                                visibility_spans
+                                    .iter()
+                                    .map(|span| {
+                                        (
+                                            *span,
+                                            if span.is_empty() { "pub " } else { "pub" }
```
Comment (Nilstrieb) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1465]: This could lead to an invalid suggestion if the user wrote something like this
```rust
mod a {
    pub struct A(pub(self)String);
}

fn main() {
    a::A("a".into());
}
```
I'm not sure how likely this is to come up (since it's non-standard formatting) so I'll leave it up to you whether you want to fix it.

Comment (Nilstrieb) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1465]: Hm, my example actually doesn't trigger the error at all..
```rust
error[E0603]: tuple struct constructor `A` is private
 --> aa.rs:6:8
  |
2 |     pub struct A(pub(self)String);
  |                  --------------- a constructor is private if any of the fields is private
...
6 |     a::A("a".into());
  |        ^ private tuple struct constructor
  |
note: the tuple struct constructor `A` is defined here
 --> aa.rs:2:5
  |
2 |     pub struct A(pub(self)String);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But this version does produce an invalid suggestion:
```rust
mod a {
    pub struct A(pub(self)String);
}

mod b {
    use crate::a::A;
    fn x() {
        A("".into());
    }
}

fn main() {}
```

```rust
help: consider making the field publicly accessible
  |
2 |     pub struct A(pubString);
  |                  ~~~
```

Comment (estebank) [reply compiler/rustc_resolve/src/late/diagnostics.rs:1465]: Fixed
