### PR TITLE
Fix using `include_bytes` in pattern position

### LINKED ISSUE #104414: non-pattern macro in pattern position: include_bytes
### Code

I tried this code:

```rust
fn main() {
    match b"a\n" {
        include_bytes!("file.inc") => (),
        _ => panic!("no match"),
    }
}
```

I expected to see this happen: code compiles and execute

Instead, this happened: compilation fails with 
```
error: non-pattern macro in pattern position: include_bytes
 --> src/main.rs:3:9
  |
4 |         include_bytes!("file.inc") => (),
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `regression` due to previous error
```

### Version it worked on

It most recently worked on: `rustc 1.65.0 (897e37553 2022-11-02)` and `rustc 1.67.0-nightly (1286ee23e 2022-11-05)`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (e631891f7 2022-11-13)
binary: rustc
commit-hash: e631891f7ad40eac3ef58ec3c2b57ecd81e40615
commit-date: 2022-11-13
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Notes
used by [x509-signature](https://crates.io/crates/x509-signature). I suspect #103812 (but did not confirm) might be the cause of the breakage as it is a recent change on that area.

### PR DESCRIPTION
**Pull request by clubby789**
Fix #104414

### CODE REVIEW

File: src/test/ui/proc-macro/expand-expr.rs [hunk 1]
```diff
@@ -123,4 +123,10 @@ expand_expr_fail!(echo_pm!(arbitrary_expression() + "etc"));
 
 const _: u32 = recursive_expand!(); //~ ERROR: recursion limit reached while expanding `recursive_expand!`
 
-fn main() {}
+fn main() {
+    // https://github.com/rust-lang/rust/issues/104414
+    match b"a" {
+        include_bytes!("auxiliary/included-file.txt") => (),
+        _ => ()
```
Comment (danielhenrymantilla) [inline src/test/ui/proc-macro/expand-expr.rs:130]:
```suggestion
    match b"Included file contents\n" {
        include_bytes!("auxiliary/included-file.txt") => (),
        _ => panic!("include_bytes! in pattern"),
```
