### PR TITLE
Don't build drop shim for polymorphic types

### LINKED ISSUE #110682: ICE: Failed to normalize, maybe try to call `try_normalize_erasing_regions` instead
### Code

I found this ICE while compiling `bitvec 0.19.6` in release mode.

https://github.com/ferrilab/bitvec/tree/v0/19/6

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (fec9adcdb 2023-04-21)
binary: rustc
commit-hash: fec9adcdbc21469ef105162cc8cabf81c72d06be
commit-date: 2023-04-21
host: aarch64-apple-darwin
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:195:90: Failed to normalize alloc::raw_vec::RawVec<<T as store::BitStore>::Mem>, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/fec9adcdbc21469ef105162cc8cabf81c72d06be/compiler/rustc_errors/src/lib.rs:1643:9

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (fec9adcdb 2023-04-21) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C target-cpu=apple-m1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_shims] generating MIR shim for `core::ptr::drop_in_place`
#1 [optimized_mir] optimizing MIR for `vec::ops::<impl at src/vec/ops.rs:141:1: 141:33>::drop::{closure#0}`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x104a90738 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9e6c436959f1b8e
   1:        0x104ae075c - core::fmt::write::h03620c265cda50c9
   2:        0x104a86658 - std::io::Write::write_fmt::h4582733544e760df
   3:        0x104a90598 - std::sys_common::backtrace::print::h52cbdd72190599ef
   4:        0x104a92f38 - std::panicking::default_hook::{{closure}}::hbd7990be14834316
   5:        0x104a92d3c - std::panicking::default_hook::hefa394ac64f6527f
   6:        0x10cfb5b58 - rustc_driver_impl[9431cfa2328e8da]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x104a9352c - std::panicking::rust_panic_with_hook::h7504e9066f7b4f07
   8:        0x110d6c2e8 - std[614eb408c5fa570d]::panicking::begin_panic::<rustc_errors[c2a69e08fcd2e8bf]::ExplicitBug>::{closure#0}
   9:        0x110d69db0 - std[614eb408c5fa570d]::sys_common::backtrace::__rust_end_short_backtrace::<std[614eb408c5fa570d]::panicking::begin_panic<rustc_errors[c2a69e08fcd2e8bf]::ExplicitBug>::{closure#0}, !>
  10:        0x1113a1b44 - std[614eb408c5fa570d]::panicking::begin_panic::<rustc_errors[c2a69e08fcd2e8bf]::ExplicitBug>
  11:        0x110e2b5ac - <rustc_errors[c2a69e08fcd2e8bf]::HandlerInner>::bug::<&alloc[8ca104b1f3df9592]::string::String>
  12:        0x110e2b270 - <rustc_errors[c2a69e08fcd2e8bf]::Handler>::bug::<&alloc[8ca104b1f3df9592]::string::String>
  13:        0x110dd1124 - rustc_middle[662f54c0a25f7c56]::util::bug::opt_span_bug_fmt::<rustc_span[7733720cb78d73dd]::span_encoding::Span>::{closure#0}
  14:        0x110dd0b34 - rustc_middle[662f54c0a25f7c56]::ty::context::tls::with_opt::<rustc_middle[662f54c0a25f7c56]::util::bug::opt_span_bug_fmt<rustc_span[7733720cb78d73dd]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:        0x110dd0b00 - rustc_middle[662f54c0a25f7c56]::ty::context::tls::with_context_opt::<rustc_middle[662f54c0a25f7c56]::ty::context::tls::with_opt<rustc_middle[662f54c0a25f7c56]::util::bug::opt_span_bug_fmt<rustc_span[7733720cb78d73dd]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:        0x1113a18ac - rustc_middle[662f54c0a25f7c56]::util::bug::bug_fmt
  17:        0x110dcdea8 - <rustc_middle[662f54c0a25f7c56]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::normalize_generic_arg_after_erasing_regions
  18:        0x110dcdee4 - <rustc_middle[662f54c0a25f7c56]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_type_ir[50bb8a969b2c53c]::fold::TypeFolder<rustc_middle[662f54c0a25f7c56]::ty::context::TyCtxt>>::fold_ty
  19:        0x10f6d33cc - <core[dc40836e4f3e0da7]::iter::adapters::map::Map<core[dc40836e4f3e0da7]::iter::adapters::enumerate::Enumerate<core[dc40836e4f3e0da7]::slice::iter::Iter<rustc_middle[662f54c0a25f7c56]::ty::FieldDef>>, <rustc_mir_dataflow[2ace872dcdcb608a]::elaborate_drops::DropCtxt<rustc_mir_transform[c661f0a31a836e75]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}> as core[dc40836e4f3e0da7]::iter::traits::iterator::Iterator>::fold::<(), core[dc40836e4f3e0da7]::iter::traits::iterator::Iterator::for_each::call<(rustc_middle[662f54c0a25f7c56]::mir::syntax::Place, core[dc40836e4f3e0da7]::option::Option<()>), <alloc[8ca104b1f3df9592]::vec::Vec<(rustc_middle[662f54c0a25f7c56]::mir::syntax::Place, core[dc40836e4f3e0da7]::option::Option<()>)>>::extend_trusted<core[dc40836e4f3e0da7]::iter::adapters::map::Map<core[dc40836e4f3e0da7]::iter::adapters::enumerate::Enumerate<core[dc40836e4f3e0da7]::slice::iter::Iter<rustc_middle[662f54c0a25f7c56]::ty::FieldDef>>, <rustc_mir_dataflow[2ace872dcdcb608a]::elaborate_drops::DropCtxt<rustc_mir_transform[c661f0a31a836e75]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>::{closure#0}>::{closure#0}>
  20:        0x10f7e0f04 - <alloc[8ca104b1f3df9592]::vec::Vec<(rustc_middle[662f54c0a25f7c56]::mir::syntax::Place, core[dc40836e4f3e0da7]::option::Option<()>)> as alloc[8ca104b1f3df9592]::vec::spec_from_iter::SpecFromIter<(rustc_middle[662f54c0a25f7c56]::mir::syntax::Place, core[dc40836e4f3e0da7]::option::Option<()>), core[dc40836e4f3e0da7]::iter::adapters::map::Map<core[dc40836e4f3e0da7]::iter::adapters::enumerate::Enumerate<core[dc40836e4f3e0da7]::slice::iter::Iter<rustc_middle[662f54c0a25f7c56]::ty::FieldDef>>, <rustc_mir_dataflow[2ace872dcdcb608a]::elaborate_drops::DropCtxt<rustc_mir_transform[c661f0a31a836e75]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>>::from_iter
  21:        0x10f6de998 - <rustc_mir_dataflow[2ace872dcdcb608a]::elaborate_drops::DropCtxt<rustc_mir_transform[c661f0a31a836e75]::shim::DropShimElaborator>>::open_drop_for_adt
  22:        0x10f6de2e8 - <rustc_mir_dataflow[2ace872dcdcb608a]::elaborate_drops::DropCtxt<rustc_mir_transform[c661f0a31a836e75]::shim::DropShimElaborator>>::elaborate_drop
  23:        0x10f800090 - rustc_mir_transform[c661f0a31a836e75]::shim::make_shim
  24:        0x11027591c - <std[614eb408c5fa570d]::thread::local::LocalKey<core[dc40836e4f3e0da7]::cell::Cell<*const ()>>>::with::<rustc_middle[662f54c0a25f7c56]::ty::context::tls::enter_context<rustc_query_system[2ed44d2bc999b7a]::query::plumbing::execute_job_non_incr<rustc_query_impl[eba986b151bf483e]::queries::mir_shims, rustc_query_impl[eba986b151bf483e]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[662f54c0a25f7c56]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[662f54c0a25f7c56]::query::erase::Erased<[u8; 8usize]>>
  25:        0x11014ccd0 - rustc_query_system[2ed44d2bc999b7a]::query::plumbing::try_execute_query::<rustc_query_impl[eba986b151bf483e]::queries::mir_shims, rustc_query_impl[eba986b151bf483e]::plumbing::QueryCtxt>
  26:        0x110347614 - <rustc_query_impl[eba986b151bf483e]::Queries as rustc_middle[662f54c0a25f7c56]::ty::query::QueryEngine>::mir_shims
  27:        0x110eba434 - <rustc_middle[662f54c0a25f7c56]::ty::context::TyCtxt>::instance_mir
  28:        0x10f7cb2c4 - <rustc_mir_transform[c661f0a31a836e75]::inline::Inliner>::try_inlining
  29:        0x10f7cac2c - <rustc_mir_transform[c661f0a31a836e75]::inline::Inliner>::process_blocks
  30:        0x10f7cad14 - <rustc_mir_transform[c661f0a31a836e75]::inline::Inliner>::process_blocks
  31:        0x10f7ca6f0 - <rustc_mir_transform[c661f0a31a836e75]::inline::Inline as rustc_middle[662f54c0a25f7c56]::mir::MirPass>::run_pass
  32:        0x10f7c3dd0 - rustc_mir_transform[c661f0a31a836e75]::pass_manager::run_passes_inner
  33:        0x10f6f15a8 - rustc_mir_transform[c661f0a31a836e75]::optimized_mir
  34:        0x1100dd060 - rustc_query_system[2ed44d2bc999b7a]::query::plumbing::try_execute_query::<rustc_query_impl[eba986b151bf483e]::queries::optimized_mir, rustc_query_impl[eba986b151bf483e]::plumbing::QueryCtxt>
  35:        0x11033e7b8 - <rustc_query_impl[eba986b151bf483e]::Queries as rustc_middle[662f54c0a25f7c56]::ty::query::QueryEngine>::optimized_mir
  36:        0x1106e1654 - <rustc_metadata[f2a84a8141f6c436]::rmeta::encoder::EncodeContext>::encode_crate_root
  37:        0x1106eeb08 - rustc_metadata[f2a84a8141f6c436]::rmeta::encoder::encode_metadata_impl
  38:        0x110695d88 - rustc_data_structures[240cd432e77d6b7b]::sync::join::<rustc_metadata[f2a84a8141f6c436]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[f2a84a8141f6c436]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  39:        0x1106ee348 - rustc_metadata[f2a84a8141f6c436]::rmeta::encoder::encode_metadata
  40:        0x11068928c - rustc_metadata[f2a84a8141f6c436]::fs::encode_and_write_metadata
  41:        0x10d066d9c - rustc_interface[5a3a908aa1aef180]::passes::start_codegen
  42:        0x10d052850 - <rustc_middle[662f54c0a25f7c56]::ty::context::GlobalCtxt>::enter::<<rustc_interface[5a3a908aa1aef180]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[dc40836e4f3e0da7]::result::Result<alloc[8ca104b1f3df9592]::boxed::Box<dyn core[dc40836e4f3e0da7]::any::Any>, rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>
  43:        0x10d01ea18 - <rustc_interface[5a3a908aa1aef180]::queries::Queries>::ongoing_codegen
  44:        0x10cf8ec74 - <rustc_interface[5a3a908aa1aef180]::interface::Compiler>::enter::<rustc_driver_impl[9431cfa2328e8da]::run_compiler::{closure#1}::{closure#2}, core[dc40836e4f3e0da7]::result::Result<core[dc40836e4f3e0da7]::option::Option<rustc_interface[5a3a908aa1aef180]::queries::Linker>, rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>
  45:        0x10cf52ca4 - rustc_span[7733720cb78d73dd]::set_source_map::<core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>, rustc_interface[5a3a908aa1aef180]::interface::run_compiler<core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>, rustc_driver_impl[9431cfa2328e8da]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  46:        0x10cf58250 - <scoped_tls[4e67b4d1df739e32]::ScopedKey<rustc_span[7733720cb78d73dd]::SessionGlobals>>::set::<rustc_interface[5a3a908aa1aef180]::interface::run_compiler<core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>, rustc_driver_impl[9431cfa2328e8da]::run_compiler::{closure#1}>::{closure#0}, core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>
  47:        0x10cf49a1c - std[614eb408c5fa570d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[5a3a908aa1aef180]::util::run_in_thread_pool_with_globals<rustc_interface[5a3a908aa1aef180]::interface::run_compiler<core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>, rustc_driver_impl[9431cfa2328e8da]::run_compiler::{closure#1}>::{closure#0}, core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>
  48:        0x10cf5d42c - <<std[614eb408c5fa570d]::thread::Builder>::spawn_unchecked_<rustc_interface[5a3a908aa1aef180]::util::run_in_thread_pool_with_globals<rustc_interface[5a3a908aa1aef180]::interface::run_compiler<core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>, rustc_driver_impl[9431cfa2328e8da]::run_compiler::{closure#1}>::{closure#0}, core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[dc40836e4f3e0da7]::result::Result<(), rustc_span[7733720cb78d73dd]::ErrorGuaranteed>>::{closure#1} as core[dc40836e4f3e0da7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:        0x104a9bcd0 - std::sys::unix::thread::Thread::new::thread_start::h02c2263b1a3b4fc6
  50:        0x19840bfa8 - __pthread_joiner_wake
```

</p>
</details>

bisect command: 

```
cargo bisect-rustc --start 2023-04-17 --end 2023-04-18 --without-cargo -- build --release
```

bisect result: https://github.com/rust-lang/rust/pull/109247

********************************************************************************
Regression in 5546cb64f6fbba70529582bbe58a40ba4a8ed9fc
********************************************************************************

### PR DESCRIPTION
**Pull request by b-naber**
Fixes https://github.com/rust-lang/rust/issues/110682

This was exposed through the changes in https://github.com/rust-lang/rust/pull/109247, which causes more things to be inlined. Inlining can happen before monomorphization, so we can't expect normalization to succeed. In the elaborate_drops analysis we currently have [this call](https://github.com/rust-lang/rust/blob/033aa092ab23ba14cdad27073c5e37ba0eddb428/compiler/rustc_mir_dataflow/src/elaborate_drops.rs#L278) to `normalize_erasing_regions`, which ICEs when normalization fails. The types are used to infer [whether the type needs a drop](https://github.com/rust-lang/rust/blob/033aa092ab23ba14cdad27073c5e37ba0eddb428/compiler/rustc_mir_dataflow/src/elaborate_drops.rs#L374), where `needs_drop` itself [uses `try_normalize_erasing_regions`](https://github.com/rust-lang/rust/blob/033aa092ab23ba14cdad27073c5e37ba0eddb428/compiler/rustc_middle/src/ty/util.rs#L1121). 

~[`instance_mir`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.instance_mir) isn't explicit about whether it expects the instances corresponding to the `InstanceDef`s to be monomorphized (though I think in all other contexts the function is used post-monomorphization), so the use of `instance_mir` in inlining doesn't necessarily seem wrong to me.~

### CODE REVIEW

**Comment by b-naber** [comment]
Actually I think this might not be the proper fix for this. Inlining actually is only done post-monomorphization afaict (its only called through `instance_mir` (the earliest call of that function should be [this one](https://github.com/rust-lang/rust/blob/033aa092ab23ba14cdad27073c5e37ba0eddb428/compiler/rustc_monomorphize/src/collector.rs#L1450)), so we have fully non-generic substs at each call site of `instance_mir`. We discard those substs for the call though and then only use non substituted `param_env`s throughout inlining (and all other optimizations too I think), which seems wrong to me. I'm not really that familiar with the code in `rustc_mir_transform`. Can anybody more familiar with this share some light on whether this might be wrong? cc @oli-obk @JakobDegen

**Comment by JakobDegen** [comment]
The reported issue is a dupe of #106444 , which has a draft PR up to fix it.

We definitely do try to inline pre-mono Mir, and normally that works fine. The problem is just that drop shim generation specifically is not set up to deal with that at all, which is what causes the problems. I don't know what the right fix is either, you'll probably have to coordinate that with Camille.

**Comment by cjgillot** [comment]
https://github.com/rust-lang/rust/pull/106905 stumbled on this ICE https://github.com/rust-lang/rust/pull/106905#issuecomment-1423598452. This PR may have a similar one.

**Comment by b-naber** [comment]
> #106905 stumbled on this ICE [#106905 (comment)](https://github.com/rust-lang/rust/pull/106905#issuecomment-1423598452). This PR may have a similar one.

I think this change wouldn't be affected by that, as we keep normalizing as we previously do, so this should not introduce any other normalization related ICEs, though it might lead to other problems.

I've tried to familiarize myself more with the inlining and drop elaboration code and I believe the current behaviour of not being able to normalize during inlining introduces some inconsistencies. When we `process_blocks` during inlining we [rely on `Instance::resolve`](https://github.com/rust-lang/rust/blob/b7d8c88b64843d05761576aa093a34a8bc176817/compiler/rustc_mir_transform/src/inline.rs#L324) to [determine callsites](https://github.com/rust-lang/rust/blob/b7d8c88b64843d05761576aa093a34a8bc176817/compiler/rustc_mir_transform/src/inline.rs#L133). If we're working with generic projections, then we can't resolve those callsites, which will result in the compiler not inlining calls it could (should?) inline. E.g.:

```
use std::mem::ManuallyDrop;
use std::ops::Drop;

#[inline(always)]
fn called_when_dropped() {
    let _s = "this is inlined";
}

struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        called_when_dropped()
    }
}

fn func(arg: Foo) {
    let mut md = unsafe { ManuallyDrop::new(arg) };
    unsafe { ManuallyDrop::drop(&mut md) };
}

fn main() {
    let v = Foo {};
    func(v);
}
```

results in the following mir after inlining for `func`:

```
// MIR for `func` after Inline

fn func(_1: Foo) -> () {
    debug arg => _1;                     // in scope 0 at inline-no-generics-no-vec.rs:17:9: 17:12
    let mut _0: ();                      // return place in scope 0 at inline-no-generics-no-vec.rs:17:19: 17:19
    let mut _2: std::mem::ManuallyDrop<Foo>; // in scope 0 at inline-no-generics-no-vec.rs:18:9: 18:15
    let mut _3: Foo;                     // in scope 0 at inline-no-generics-no-vec.rs:18:45: 18:48
    let _4: ();                          // in scope 0 at inline-no-generics-no-vec.rs:19:14: 19:41
    let mut _5: &mut std::mem::ManuallyDrop<Foo>; // in scope 0 at inline-no-generics-no-vec.rs:19:33: 19:40
    let mut _6: &mut std::mem::ManuallyDrop<Foo>; // in scope 0 at inline-no-generics-no-vec.rs:19:33: 19:40
    scope 1 {
        debug md => _2;                  // in scope 1 at inline-no-generics-no-vec.rs:18:9: 18:15
        scope 3 {
            scope 5 (inlined ManuallyDrop::<Foo>::drop) { // at inline-no-generics-no-vec.rs:19:14: 19:41
                debug slot => _5;        // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:140:24: 140:28
                let mut _7: *mut Foo;    // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
                let mut _8: &mut Foo;    // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
                scope 6 {
                    scope 7 (inlined std::ptr::drop_in_place::<Foo> - shim(Some(Foo))) { // at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
                        let mut _9: &mut Foo; // in scope 7 at /home/gh-b-naber/rust/library/core/src/ptr/mod.rs:490:1: 490:56
                        let mut _10: (); // in scope 7 at /home/gh-b-naber/rust/library/core/src/ptr/mod.rs:490:1: 490:56
                    }
                }
            }
        }
    }
    scope 2 {
        scope 4 (inlined ManuallyDrop::<Foo>::new) { // at inline-no-generics-no-vec.rs:18:27: 18:49
            debug value => _3;           // in scope 4 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:70:22: 70:27
        }
    }

    bb0: {
        StorageLive(_2);                 // scope 0 at inline-no-generics-no-vec.rs:18:9: 18:15
        StorageLive(_3);                 // scope 2 at inline-no-generics-no-vec.rs:18:45: 18:48
        _3 = move _1;                    // scope 2 at inline-no-generics-no-vec.rs:18:45: 18:48
        _2 = ManuallyDrop::<Foo> { value: move _3 }; // scope 4 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:71:9: 71:31
        StorageDead(_3);                 // scope 2 at inline-no-generics-no-vec.rs:18:48: 18:49
        StorageLive(_4);                 // scope 1 at inline-no-generics-no-vec.rs:19:5: 19:43
        StorageLive(_5);                 // scope 3 at inline-no-generics-no-vec.rs:19:33: 19:40
        StorageLive(_6);                 // scope 3 at inline-no-generics-no-vec.rs:19:33: 19:40
        _6 = &mut _2;                    // scope 3 at inline-no-generics-no-vec.rs:19:33: 19:40
        _5 = &mut (*_6);                 // scope 3 at inline-no-generics-no-vec.rs:19:33: 19:40
        StorageLive(_7);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        StorageLive(_8);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        _8 = &mut ((*_5).0: Foo);        // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        _7 = &raw mut (*_8);             // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        StorageLive(_9);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
        StorageLive(_10);                // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
        _9 = &mut (*_7);                 // scope 7 at /home/gh-b-naber/rust/library/core/src/ptr/mod.rs:490:1: 490:56
        _10 = <Foo as Drop>::drop(move _9) -> [return: bb2, unwind: bb1]; // scope 7 at /home/gh-b-naber/rust/library/core/src/ptr/mod.rs:490:1: 490:56
                                         // mir::Constant
                                         // + span: /home/gh-b-naber/rust/library/core/src/ptr/mod.rs:490:1: 490:56
                                         // + literal: Const { ty: for<'a> fn(&'a mut Foo) {<Foo as Drop>::drop}, val: Value(<ZST>) }
    }

    bb1 (cleanup): {
        resume;                          // scope 0 at inline-no-generics-no-vec.rs:17:1: 20:2
    }

    bb2: {
        StorageDead(_10);                // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
        StorageDead(_9);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
        StorageDead(_7);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:52: 144:53
        StorageDead(_8);                 // scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:145:5: 145:6
        StorageDead(_5);                 // scope 3 at inline-no-generics-no-vec.rs:19:40: 19:41
        StorageDead(_6);                 // scope 1 at inline-no-generics-no-vec.rs:19:43: 19:44
        StorageDead(_4);                 // scope 1 at inline-no-generics-no-vec.rs:19:43: 19:44
        _0 = const ();                   // scope 0 at inline-no-generics-no-vec.rs:17:19: 20:2
        StorageDead(_2);                 // scope 0 at inline-no-generics-no-vec.rs:20:1: 20:2
        return;                          // scope 0 at inline-no-generics-no-vec.rs:20:2: 20:2
    }
}
```

So here we do inline the call to `drop_in_place` for `Foo`.

Whereas for the following example we do not, but we could if we would properly normalize this:

```
use std::mem::ManuallyDrop;
use std::ops::Drop;

#[inline(always)]
fn must_be_inlined() {
    let _s = "this should be inlined";
}

struct Foo;

struct Bar {
    a: u32,
}

impl Drop for Bar {
    fn drop(&mut self) {
        must_be_inlined()
    }
}

impl A for Foo {
    type MyType = Bar;
}

trait A {
    type MyType;
}

fn func<T: A>(foo: T, arg: <T as A>::MyType) {
    let mut to_drop = unsafe { ManuallyDrop::new(arg) };
    unsafe { ManuallyDrop::drop(&mut to_drop) }
}

fn main() {
    let bar = Bar { a: 1 };
    let foo = Foo {};
    func(foo, bar);
}
```

which results in the following post-inline mir:

```
// MIR for `func` after Inline

fn func(_1: T, _2: <T as A>::MyType) -> () {
    debug foo => _1;                     // in scope 0 at manual-drop-associated-type.rs:29:15: 29:18
    debug arg => _2;                     // in scope 0 at manual-drop-associated-type.rs:29:23: 29:26
    let mut _0: ();                      // return place in scope 0 at manual-drop-associated-type.rs:29:46: 29:46
    let mut _3: std::mem::ManuallyDrop<<T as A>::MyType>; // in scope 0 at manual-drop-associated-type.rs:30:9: 30:20
    let mut _4: <T as A>::MyType;        // in scope 0 at manual-drop-associated-type.rs:30:50: 30:53
    let mut _5: &mut std::mem::ManuallyDrop<<T as A>::MyType>; // in scope 0 at manual-drop-associated-type.rs:31:33: 31:45
    let mut _6: &mut std::mem::ManuallyDrop<<T as A>::MyType>; // in scope 0 at manual-drop-associated-type.rs:31:33: 31:45
    scope 1 {
        debug to_drop => _3;             // in scope 1 at manual-drop-associated-type.rs:30:9: 30:20
        scope 3 {
            scope 5 (inlined ManuallyDrop::<<T as A>::MyType>::drop) { // at manual-drop-associated-type.rs:31:14: 31:46
                debug slot => _5;        // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:140:24: 140:28
                let mut _7: *mut <T as A>::MyType; // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
                let mut _8: &mut <T as A>::MyType; // in scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
                scope 6 {
                }
            }
        }
    }
    scope 2 {
        scope 4 (inlined ManuallyDrop::<<T as A>::MyType>::new) { // at manual-drop-associated-type.rs:30:32: 30:54
            debug value => _4;           // in scope 4 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:70:22: 70:27
        }
    }

    bb0: {
        StorageLive(_3);                 // scope 0 at manual-drop-associated-type.rs:30:9: 30:20
        StorageLive(_4);                 // scope 2 at manual-drop-associated-type.rs:30:50: 30:53
        _4 = move _2;                    // scope 2 at manual-drop-associated-type.rs:30:50: 30:53
        _3 = ManuallyDrop::<<T as A>::MyType> { value: move _4 }; // scope 4 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:71:9: 71:31
        StorageDead(_4);                 // scope 2 at manual-drop-associated-type.rs:30:53: 30:54
        StorageLive(_5);                 // scope 3 at manual-drop-associated-type.rs:31:33: 31:45
        StorageLive(_6);                 // scope 3 at manual-drop-associated-type.rs:31:33: 31:45
        _6 = &mut _3;                    // scope 3 at manual-drop-associated-type.rs:31:33: 31:45
        _5 = &mut (*_6);                 // scope 3 at manual-drop-associated-type.rs:31:33: 31:45
        StorageLive(_7);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        StorageLive(_8);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        _8 = &mut ((*_5).0: <T as A>::MyType); // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        _7 = &raw mut (*_8);             // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:37: 144:52
        _0 = std::ptr::drop_in_place::<<T as A>::MyType>(move _7) -> [return: bb4, unwind: bb2]; // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53
                                         // mir::Constant
                                         // + span: /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:36
                                         // + literal: Const { ty: unsafe fn(*mut <T as A>::MyType) {std::ptr::drop_in_place::<<T as A>::MyType>}, val: Value(<ZST>) }
    }

    bb1: {
        return;                          // scope 0 at manual-drop-associated-type.rs:32:2: 32:2
    }

    bb2 (cleanup): {
        drop(_1) -> [return: bb3, unwind terminate]; // scope 0 at manual-drop-associated-type.rs:32:1: 32:2
    }

    bb3 (cleanup): {
        resume;                          // scope 0 at manual-drop-associated-type.rs:29:1: 32:2
    }

    bb4: {
        StorageDead(_7);                 // scope 6 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:52: 144:53
        StorageDead(_8);                 // scope 5 at /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:145:5: 145:6
        StorageDead(_5);                 // scope 3 at manual-drop-associated-type.rs:31:45: 31:46
        StorageDead(_3);                 // scope 0 at manual-drop-associated-type.rs:32:1: 32:2
        StorageDead(_6);                 // scope 0 at manual-drop-associated-type.rs:32:1: 32:2
        drop(_1) -> [return: bb1, unwind: bb3]; // scope 0 at manual-drop-associated-type.rs:32:1: 32:2
    }
}
```

This is because after having inlined `ManuallyDrop::<<T as A>::MyType>::drop` to:

```
│ │ │ │ │ │ │ │ │ │ │ │             BasicBlockData {
│ │ │ │ │ │ │ │ │ │ │ │                 statements: [
│ │ │ │ │ │ │ │ │ │ │ │                     StorageLive(_7),
│ │ │ │ │ │ │ │ │ │ │ │                     StorageLive(_8),
│ │ │ │ │ │ │ │ │ │ │ │                     _8 = &mut ((*_5).0: <T as A>::MyType),
│ │ │ │ │ │ │ │ │ │ │ │                     _7 = &raw mut (*_8),
│ │ │ │ │ │ │ │ │ │ │ │                 ],
│ │ │ │ │ │ │ │ │ │ │ │                 terminator: Some(
│ │ │ │ │ │ │ │ │ │ │ │                     Terminator {
│ │ │ │ │ │ │ │ │ │ │ │                         source_info: SourceInfo {
│ │ │ │ │ │ │ │ │ │ │ │                             span: /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:144:18: 144:53 (#30),
│ │ │ │ │ │ │ │ │ │ │ │                             scope: scope[6],
│ │ │ │ │ │ │ │ │ │ │ │                         },
│ │ │ │ │ │ │ │ │ │ │ │                         kind: _0 = std::ptr::drop_in_place::<<T as A>::MyType>(move _7) -> [return: bb8, unwind: bb4],
│ │ │ │ │ │ │ │ │ │ │ │                     },
│ │ │ │ │ │ │ │ │ │ │ │                 ),
│ │ │ │ │ │ │ │ │ │ │ │                 is_cleanup: false,
│ │ │ │ │ │ │ │ │ │ │ │             },
│ │ │ │ │ │ │ │ │ │ │ │             BasicBlockData {
│ │ │ │ │ │ │ │ │ │ │ │                 statements: [
│ │ │ │ │ │ │ │ │ │ │ │                     StorageDead(_7),
│ │ │ │ │ │ │ │ │ │ │ │                     StorageDead(_8),
│ │ │ │ │ │ │ │ │ │ │ │                 ],
│ │ │ │ │ │ │ │ │ │ │ │                 terminator: Some(
│ │ │ │ │ │ │ │ │ │ │ │                     Terminator {
│ │ │ │ │ │ │ │ │ │ │ │                         source_info: SourceInfo {
│ │ │ │ │ │ │ │ │ │ │ │                             span: /home/gh-b-naber/rust/library/core/src/mem/manually_drop.rs:145:6: 145:6 (#0),
│ │ │ │ │ │ │ │ │ │ │ │                             scope: scope[0],
│ │ │ │ │ │ │ │ │ │ │ │                         },
│ │ │ │ │ │ │ │ │ │ │ │                         kind: goto -> bb2,
│ │ │ │ │ │ │ │ │ │ │ │                     },
│ │ │ │ │ │ │ │ │ │ │ │                 ),
│ │ │ │ │ │ │ │ │ │ │ │                 is_cleanup: false,
│ │ │ │ │ │ │ │ │ │ │ │             },
```

we cannot resolve the callsite for `DefId(2:2136 ~ core[f82a]::ptr::drop_in_place), param_env=ParamEnv { caller_bounds: [Binder(TraitPredicate(<T as A>, polarity:Positive), []), Binder(TraitPredicate(<T as std::marker::Sized>, polarity:Positive), [])], reveal: All, constness: NotConst }, substs=[<T as A>::MyType]`, so we never create the drop shim here for the `callee_body` and stop inlining here.

Is this inconsistent?

When do we actually start to inline at the earliest? AFAICT the earliest call that would result in inlining is [this one](https://github.com/rust-lang/rust/blob/b7d8c88b64843d05761576aa093a34a8bc176817/compiler/rustc_monomorphize/src/collector.rs#L1450) in `collect_neighbors`. So we should always have concrete substs available when calling `instance_mir`. Is that correct? 

If it is, then I think the proper fix is to have a version of `instance_mir` that takes substs and then enforces normalization to succeed everywhere.

**Comment by cjgillot** [comment]
> I think this change wouldn't be affected by that, as we keep normalizing as we previously do, so this should not introduce any other normalization related ICEs, though it might lead to other problems.

Falling back to the unnormalized type may cause the other ICE: if for some reason, we cannot normalize and drop elaboration expects and ADT, boom.

> ...
> Is this inconsistent?

I don't think this is inconsistent. The whole point of working on MIR that we optimize MIR *in its polymorphic form*. The `<T as A>::MyType` in your example stays because we want inlining to be accurate for any generic type T, and we have no way of knowing that it will just be used for `Foo`.

If polymorphism prevents some inlining, then we leave to LLVM to perform the monomorphic inlining.

However, specifically for drop shims, if trying to manufacture polymorphic drop shims is an issue, we may need to check that the instance is monomorphic enough and skip trying to inline it if it isn't.

File: compiler/rustc_mir_dataflow/src/elaborate_drops.rs [hunk 1]
```diff
@@ -272,10 +272,16 @@ where
...
                 let subpath = self.elaborator.field_subpath(variant_path, field);
                 let tcx = self.tcx();
-
                 assert_eq!(self.elaborator.param_env().reveal(), Reveal::All);
-                let field_ty =
-                    tcx.normalize_erasing_regions(self.elaborator.param_env(), f.ty(tcx, substs));
+
+                let fty = f.ty(tcx, substs);
+                let field_ty = match tcx
+                    .try_normalize_erasing_regions(self.elaborator.param_env(), f.ty(tcx, substs))
```
Comment (cjgillot) [inline compiler/rustc_mir_dataflow/src/elaborate_drops.rs:279]: Nit
```suggestion
                let field_ty = match tcx
                    .try_normalize_erasing_regions(self.elaborator.param_env(), fty)
```

File: compiler/rustc_mir_transform/src/inline.rs [hunk 2]
```diff
@@ -1124,3 +1125,27 @@ impl<'tcx> MutVisitor<'tcx> for Integrator<'_, 'tcx> {
...
 }
+
+#[instrument(skip(tcx), level = "debug")]
+fn try_instance_mir<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    instance: InstanceDef<'tcx>,
+) -> Result<&'tcx Body<'tcx>, &'static str> {
+    match instance {
+        ty::InstanceDef::DropGlue(_, Some(ty)) => match ty.kind() {
+            ty::Adt(def, substs) => {
```
Comment (b-naber) [inline compiler/rustc_mir_transform/src/inline.rs:1136]: Not sure if we want to do this in a more generalized way. I believe the normalization in `move_paths_for_fields` is the only place where building drop shims can go wrong, so rejecting those types here should be sufficient (though this change feels a little hacky). 

Rejecting these here seemed preferable to me compared to making changes in the shim/drop elaboration code.
