### PR TITLE
rustdoc: add a couple of regression tests

### LINKED ISSUE #107715: rustdoc: ICE: synthetic auto trait impls: `unexpected result when selecting […]` involving const in super trait bounds & item bounds
### Problem

Minimal example
```Rust
pub const N: usize = 1;

pub struct MapType<K: Supertrait<V>, V> {
    _array: K::Array,
}

pub trait Subtrait: Supertrait<[u8; N]> {}

pub trait Supertrait<V> {
    type Array: AnotherTrait<V>;
}

pub trait AnotherTrait<V> {
    const LENGTH: usize;
}

pub struct Container<S: Subtrait> {
    _x: MapType<S, [u8; N]>,
}
```

What I expected: `cargo doc` works.
What happens:
```
thread 'rustc' panicked at 'Unexpected result when selecting Container<S> Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: [S, [u8; 1]], item_def_id: DefId(0:12 ~ panic[490c]::Supertrait::Array) }, Term::Ty(_)), []), depth=2)', compiler/rustc_trait_selection/src/traits/auto_trait.rs:750:33
stack backtrace:
   0:     0x7f1849b6c9a0 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1849b6c9a0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1849b6c9a0 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1849b6c9a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1849bc898e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f1849b5cb15 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x7f1849b6c765 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1849b6c765 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1849b6f56f - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x7f1849b6f2aa - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x7f1849b6fd78 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x7f1849b6fb17 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:     0x7f1849b6ce4c - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f1849b6f832 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x7f1849bc5373 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x7f184d8733ea - <rustc_trait_selection[5aec47e3fc81d5cc]::traits::auto_trait::AutoTraitFinder>::evaluate_predicates
  16:     0x5652762e9602 - <rustc_trait_selection[5aec47e3fc81d5cc]::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc[85586d594f3d7f89]::clean::types::Generics, <rustdoc[85586d594f3d7f89]::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
  17:     0x5652761e01d3 - <rustdoc[85586d594f3d7f89]::clean::auto_trait::AutoTraitFinder>::generate_for_trait
  18:     0x565276195391 - <alloc[d987cf4402e5b40a]::vec::Vec<rustdoc[85586d594f3d7f89]::clean::types::Item> as alloc[d987cf4402e5b40a]::vec::spec_from_iter::SpecFromIter<rustdoc[85586d594f3d7f89]::clean::types::Item, core[b97a30f8df81432d]::iter::adapters::filter_map::FilterMap<alloc[d987cf4402e5b40a]::vec::into_iter::IntoIter<rustc_span[14998722174c1bca]::def_id::DefId>, <rustdoc[85586d594f3d7f89]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
  19:     0x5652761e0f0f - <rustdoc[85586d594f3d7f89]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls
  20:     0x56527613a501 - rustdoc[85586d594f3d7f89]::clean::utils::get_auto_trait_and_blanket_impls
  21:     0x56527626b0d8 - <rustdoc[85586d594f3d7f89]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[85586d594f3d7f89]::visit::DocVisitor>::visit_item
  22:     0x56527626b21a - <rustdoc[85586d594f3d7f89]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[85586d594f3d7f89]::visit::DocVisitor>::visit_item
  23:     0x5652762683d5 - rustdoc[85586d594f3d7f89]::passes::collect_trait_impls::collect_trait_impls
  24:     0x5652762351fd - <rustc_session[87e5e219eb43521c]::session::Session>::time::<rustdoc[85586d594f3d7f89]::clean::types::Crate, rustdoc[85586d594f3d7f89]::core::run_global_ctxt::{closure#7}>
  25:     0x56527604c78c - rustdoc[85586d594f3d7f89]::core::run_global_ctxt
  26:     0x565276236e0b - <rustc_interface[ee1a3f92e887e004]::passes::QueryContext>::enter::<rustdoc[85586d594f3d7f89]::main_args::{closure#1}::{closure#0}::{closure#1}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>
  27:     0x5652761a6fa4 - <rustc_interface[ee1a3f92e887e004]::interface::Compiler>::enter::<rustdoc[85586d594f3d7f89]::main_args::{closure#1}::{closure#0}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>
  28:     0x56527602aa33 - std[bbad73ae434e23e5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ee1a3f92e887e004]::util::run_in_thread_pool_with_globals<rustc_interface[ee1a3f92e887e004]::interface::run_compiler<core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>, rustdoc[85586d594f3d7f89]::main_args::{closure#1}>::{closure#0}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>
  29:     0x5652763065ea - <<std[bbad73ae434e23e5]::thread::Builder>::spawn_unchecked_<rustc_interface[ee1a3f92e887e004]::util::run_in_thread_pool_with_globals<rustc_interface[ee1a3f92e887e004]::interface::run_compiler<core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>, rustdoc[85586d594f3d7f89]::main_args::{closure#1}>::{closure#0}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b97a30f8df81432d]::result::Result<(), rustc_errors[21897ed46328f955]::ErrorGuaranteed>>::{closure#1} as core[b97a30f8df81432d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f1849b79843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  31:     0x7f1849b79843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  32:     0x7f1849b79843 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f1849894b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  34:     0x7f1849926a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  35:                0x0 - <unknown>
```

### Steps

`cargo doc` (check & build work)

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-unknown-linux-gnu
release: 1.66.0
LLVM version: 15.0.2
```

### LINKED ISSUE #112242: rustdoc: ICE: synthetic auto trait impls: `index out of bounds, snapshot vec` using `-Znormalize-docs`
### Code
`rustdoc -Znormalize-docs --edition=2021 file.rs`
```Rust
mod foo {
    pub trait MyTrait<'a> {
        type MyItem: ?Sized;
    }

    pub struct Inner<'a, Q, R: ?Sized> {
        field: Q,
        field3: &'a u8,
        my_foo: Foo<Q>,
        field2: R,
    }

    pub struct Outer<'a, T, K: ?Sized> {
        my_inner: Inner<'a, T, K>,
    }

    pub struct Foo<T> {
        myfield: T,
    }
}

// @has complex/struct.NotOuter.html
// @has - '//*[@id="synthetic-implementations-list"]//*[@class="impl"]//h3[@class="code-header"]' \
// @has complex/struct.NotOuter.html
// -> &'b i8, T: MyTrait<'a>, <T as MyTrait<'a>>::MyItem: Copy, 'a: 'static"

pub use foo::{Foo, Inner as NotInner, MyTrait as NotMyTrait, Outer as NotOuter};

unsafe impl<T> Send for Foo<T>
where
    T: NotMyTrait<'static>,
{
}

unsafe impl<'a, Q, R: ?Sized> Send for NotInner<'static, Q, R>
where
    Q: NotMyTrait<'a>,
    <Q as NotMyTrait<'a>>::MyItem: Copy,
    R: for<'b> Fn((&'b bool, &'a u8)) -> &'b i8,
    Foo<Q>: Send,
{
}
```

### Meta

`rustc --version --verbose`:
```
rustdoc 1.72.0-nightly (dd5d7c729 2023-06-02)
binary: rustdoc
commit-hash: dd5d7c729d4e8a59708df64002e09dbcbc4005ba
commit-date: 2023-06-02
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 1', /cargo/registry/src/index.crates.io-6f17d22bba15001f/ena-0.14.2/src/snapshot_vec.rs:199:10
stack backtrace:
   0:     0x7f3621169bb1 - std::backtrace_rs::backtrace::libunwind::trace::hf9423e7319e7b273
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3621169bb1 - std::backtrace_rs::backtrace::trace_unsynchronized::h66acda1b30f743d6
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3621169bb1 - std::sys_common::backtrace::_print_fmt::hd68a2e46e11b4b1a
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f3621169bb1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9597144efc95fd0d
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f36211ca18f - core::fmt::rt::Argument::fmt::h78292bc3d727b7ea
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/core/src/fmt/rt.rs:138:9
   5:     0x7f36211ca18f - core::fmt::write::h3c0df26dbae30f71
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f362115ce61 - std::io::Write::write_fmt::h9885b87fb4cdbd4b
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/io/mod.rs:1713:15
   7:     0x7f36211699c5 - std::sys_common::backtrace::_print::h8dd7723bf85d46b9
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f36211699c5 - std::sys_common::backtrace::print::h4d1dcd147b97d0e0
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f362116c687 - std::panicking::default_hook::{{closure}}::h77fbf8c391b9b7dc
  10:     0x7f362116c474 - std::panicking::default_hook::h8cf79dcd3fda8d66
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/panicking.rs:288:9
  11:     0x7f362436c01b - <rustc_driver_impl[1c1e48d71b0475de]::install_ice_hook::{closure#0} as core[4909aebc30286168]::ops::function::FnOnce<(&core[4909aebc30286168]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f362116cdcd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hab8947fe39a54f02
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/alloc/src/boxed.rs:1999:9
  13:     0x7f362116cdcd - std::panicking::rust_panic_with_hook::h499030a402682852
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/panicking.rs:709:13
  14:     0x7f362116cb67 - std::panicking::begin_panic_handler::{{closure}}::h6ee14f69855f4395
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/panicking.rs:597:13
  15:     0x7f3621169fe6 - std::sys_common::backtrace::__rust_end_short_backtrace::he15120d3b7461309
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7f362116c8b2 - rust_begin_unwind
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/panicking.rs:593:5
  17:     0x7f36211c6413 - core::panicking::panic_fmt::hc8e9b6dda341d3de
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/core/src/panicking.rs:67:14
  18:     0x7f36211c6572 - core::panicking::panic_bounds_check::h05862dd3eb969670
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/core/src/panicking.rs:162:5
  19:     0x7f36223a7876 - <ena[4426b5e329104381]::unify::UnificationTable<ena[4426b5e329104381]::unify::backing_vec::InPlace<rustc_middle[810cd5c852e8362a]::infer::unify_key::RegionVidKey, &mut alloc[c31f8ca689b1ba4a]::vec::Vec<ena[4426b5e329104381]::unify::VarValue<rustc_middle[810cd5c852e8362a]::infer::unify_key::RegionVidKey>>, &mut rustc_infer[631e14d7b7f44c7d]::infer::undo_log::InferCtxtUndoLogs>>>::uninlined_get_root_key
  20:     0x7f362245ba5d - <rustc_infer[631e14d7b7f44c7d]::infer::canonical::canonicalizer::Canonicalizer as rustc_type_ir[924a60b187e3d5f3]::fold::TypeFolder<rustc_middle[810cd5c852e8362a]::ty::context::TyCtxt>>::fold_region
  21:     0x7f3622d0610d - <&rustc_middle[810cd5c852e8362a]::ty::list::List<rustc_middle[810cd5c852e8362a]::ty::subst::GenericArg> as rustc_type_ir[924a60b187e3d5f3]::fold::TypeFoldable<rustc_middle[810cd5c852e8362a]::ty::context::TyCtxt>>::try_fold_with::<rustc_infer[631e14d7b7f44c7d]::infer::canonical::canonicalizer::Canonicalizer>
  22:     0x7f3622d408a0 - <rustc_trait_selection[b17b0dc4b37af673]::traits::query::normalize::QueryNormalizer as rustc_type_ir[924a60b187e3d5f3]::fold::FallibleTypeFolder<rustc_middle[810cd5c852e8362a]::ty::context::TyCtxt>>::try_fold_ty
  23:     0x556ae975b959 - <rustc_infer[631e14d7b7f44c7d]::infer::at::At as rustc_trait_selection[b17b0dc4b37af673]::traits::query::normalize::QueryNormalizeExt>::query_normalize::<rustc_middle[810cd5c852e8362a]::ty::sty::Binder<rustc_middle[810cd5c852e8362a]::ty::Ty>>
  24:     0x556ae99a53e8 - rustdoc[88e8a3041a7fc0e6]::clean::normalize
  25:     0x556ae99d148f - rustdoc[88e8a3041a7fc0e6]::clean::clean_middle_ty
  26:     0x556ae999ce5a - rustdoc[88e8a3041a7fc0e6]::clean::clean_predicate
  27:     0x556ae98270e0 - <rustdoc[88e8a3041a7fc0e6]::clean::auto_trait::AutoTraitFinder>::param_env_to_generics
  28:     0x556ae994a326 - <rustc_trait_selection[b17b0dc4b37af673]::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc[88e8a3041a7fc0e6]::clean::types::Generics, <rustdoc[88e8a3041a7fc0e6]::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
  29:     0x556ae982383f - <rustdoc[88e8a3041a7fc0e6]::clean::auto_trait::AutoTraitFinder>::generate_for_trait
  30:     0x556ae98b5bb0 - <alloc[c31f8ca689b1ba4a]::vec::Vec<rustdoc[88e8a3041a7fc0e6]::clean::types::Item> as alloc[c31f8ca689b1ba4a]::vec::spec_from_iter::SpecFromIter<rustdoc[88e8a3041a7fc0e6]::clean::types::Item, core[4909aebc30286168]::iter::adapters::filter_map::FilterMap<alloc[c31f8ca689b1ba4a]::vec::into_iter::IntoIter<rustc_span[f21e7ea1847889b8]::def_id::DefId>, <rustdoc[88e8a3041a7fc0e6]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
  31:     0x556ae9824061 - <rustdoc[88e8a3041a7fc0e6]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls
  32:     0x556ae9867df3 - rustdoc[88e8a3041a7fc0e6]::clean::utils::get_auto_trait_and_blanket_impls
  33:     0x556ae997b083 - <rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[88e8a3041a7fc0e6]::visit::DocVisitor>::visit_item
  34:     0x556ae997b18a - <rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[88e8a3041a7fc0e6]::visit::DocVisitor>::visit_item
  35:     0x556ae997b18a - <rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[88e8a3041a7fc0e6]::visit::DocVisitor>::visit_item
  36:     0x556ae997cc06 - <rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[88e8a3041a7fc0e6]::visit::DocVisitor>::visit_crate
  37:     0x556ae97f83a7 - <rustc_session[92d4b519115028ad]::session::Session>::time::<alloc[c31f8ca689b1ba4a]::vec::Vec<rustdoc[88e8a3041a7fc0e6]::clean::types::Item>, rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::collect_trait_impls::{closure#0}>
  38:     0x556ae9978ce3 - rustdoc[88e8a3041a7fc0e6]::passes::collect_trait_impls::collect_trait_impls
  39:     0x556ae97f85b2 - <rustc_session[92d4b519115028ad]::session::Session>::time::<rustdoc[88e8a3041a7fc0e6]::clean::types::Crate, rustdoc[88e8a3041a7fc0e6]::core::run_global_ctxt::{closure#7}>
  40:     0x556ae9973435 - rustdoc[88e8a3041a7fc0e6]::core::run_global_ctxt
  41:     0x556ae97f8831 - <rustc_session[92d4b519115028ad]::session::Session>::time::<(rustdoc[88e8a3041a7fc0e6]::clean::types::Crate, rustdoc[88e8a3041a7fc0e6]::config::RenderOptions, rustdoc[88e8a3041a7fc0e6]::formats::cache::Cache), rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  42:     0x556ae9742a03 - <rustc_middle[810cd5c852e8362a]::ty::context::GlobalCtxt>::enter::<rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}::{closure#0}::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>
  43:     0x556ae97f9bf3 - <rustc_interface[6876b9425c9db921]::interface::Compiler>::enter::<rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>
  44:     0x556ae9944502 - rustc_span[f21e7ea1847889b8]::set_source_map::<core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>, rustc_interface[6876b9425c9db921]::interface::run_compiler<core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>, rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  45:     0x556ae9a0a6ca - <scoped_tls[3d28ca529fb5aad6]::ScopedKey<rustc_span[f21e7ea1847889b8]::SessionGlobals>>::set::<rustc_interface[6876b9425c9db921]::interface::run_compiler<core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>, rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}>::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>
  46:     0x556ae96f7409 - std[cde9a7b237b1159]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6876b9425c9db921]::util::run_in_thread_pool_with_globals<rustc_interface[6876b9425c9db921]::interface::run_compiler<core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>, rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}>::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>
  47:     0x556ae9914301 - <<std[cde9a7b237b1159]::thread::Builder>::spawn_unchecked_<rustc_interface[6876b9425c9db921]::util::run_in_thread_pool_with_globals<rustc_interface[6876b9425c9db921]::interface::run_compiler<core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>, rustdoc[88e8a3041a7fc0e6]::main_args::{closure#1}>::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4909aebc30286168]::result::Result<(), rustc_span[f21e7ea1847889b8]::ErrorGuaranteed>>::{closure#1} as core[4909aebc30286168]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f36211772c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h13a60418c9a4d1aa
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/alloc/src/boxed.rs:1985:9
  49:     0x7f36211772c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4eb541375b2c3d8
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/alloc/src/boxed.rs:1985:9
  50:     0x7f36211772c5 - std::sys::unix::thread::Thread::new::thread_start::hbdba04d5a7b01509
                               at /rustc/dd5d7c729d4e8a59708df64002e09dbcbc4005ba/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f3620df1bb5 - <unknown>
  52:     0x7f3620e73d90 - <unknown>
  53:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.72.0-nightly (dd5d7c729 2023-06-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z normalize-docs

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #112828: rustdoc: ICE: synthetic auto trait impls: `unable to fulfill trait […] for […]` due to ambiguity involving to unconstrained param in impl
### Code

`rustdoc code.rs`

```Rust
// code.rs
trait MyTrait {}
struct Inner;
struct Outer(Inner);

unsafe impl<Q> Send for Inner
where
  Q: MyTrait 
{}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (fe7454bf4 2023-06-19)
binary: rustc
commit-hash: fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2
commit-date: 2023-06-19
host: aarch64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Unable to fulfill trait DefId(2:2683 ~ core[0f69]::marker::Send) for 'Outer': [FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<_ as std::marker::Sized>, polarity:Positive), []), depth=2),Ambiguity), FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<_ as MyTrait>, polarity:Positive), []), depth=2),Ambiguity)]', /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_trait_selection/src/traits/auto_trait.rs:186:13
stack backtrace:
   0:        0x1015c40f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98bf6f1b8a3176b4
   1:        0x10161475c - core::fmt::write::h32b4394822667739
   2:        0x1015b999c - std::io::Write::write_fmt::h19e6965a4f1b2789
   3:        0x1015c3f4c - std::sys_common::backtrace::print::h75a318905bc68cf1
   4:        0x1015c6ac8 - std::panicking::default_hook::{{closure}}::hd804ed281d7e08a7
   5:        0x1015c6858 - std::panicking::default_hook::hf1f7a911542630ee
   6:        0x109b456cc - rustc_driver_impl[d5bfd45cb53215fb]::install_ice_hook::{closure#0}
   7:        0x1015c7248 - std::panicking::rust_panic_with_hook::h74c8b87d4371442c
   8:        0x1015c701c - std::panicking::begin_panic_handler::{{closure}}::hd7ff9b18e4ab7574
   9:        0x1015c44d4 - std::sys_common::backtrace::__rust_end_short_backtrace::hdc7391160fc74630
  10:        0x1015c6d88 - _rust_begin_unwind
  11:        0x10163f924 - core::panicking::panic_fmt::hb1c27fe21c4f1f37
  12:        0x100300f28 - <rustc_trait_selection[3bfe20a7ab0ad0d3]::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc[e386f36fe3828e32]::clean::types::Generics, <rustdoc[e386f36fe3828e32]::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
  13:        0x1004030b0 - <rustdoc[e386f36fe3828e32]::clean::auto_trait::AutoTraitFinder>::generate_for_trait
  14:        0x100445ad4 - <alloc[480d25cc58e20263]::vec::Vec<rustdoc[e386f36fe3828e32]::clean::types::Item> as alloc[480d25cc58e20263]::vec::spec_from_iter::SpecFromIter<rustdoc[e386f36fe3828e32]::clean::types::Item, core[f69943f7197f08d]::iter::adapters::filter_map::FilterMap<alloc[480d25cc58e20263]::vec::into_iter::IntoIter<rustc_span[131a45c9b4032fd]::def_id::DefId>, <rustdoc[e386f36fe3828e32]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
  15:        0x100403698 - <rustdoc[e386f36fe3828e32]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls
  16:        0x100395f54 - rustdoc[e386f36fe3828e32]::clean::utils::get_auto_trait_and_blanket_impls
  17:        0x10052afa0 - <rustdoc[e386f36fe3828e32]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[e386f36fe3828e32]::visit::DocVisitor>::visit_item
  18:        0x10052b070 - <rustdoc[e386f36fe3828e32]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[e386f36fe3828e32]::visit::DocVisitor>::visit_item
  19:        0x10052c36c - <rustdoc[e386f36fe3828e32]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[e386f36fe3828e32]::visit::DocVisitor>::visit_crate
  20:        0x10039e61c - <rustc_session[b33ec7bea72ab9c0]::session::Session>::time::<alloc[480d25cc58e20263]::vec::Vec<rustdoc[e386f36fe3828e32]::clean::types::Item>, rustdoc[e386f36fe3828e32]::passes::collect_trait_impls::collect_trait_impls::{closure#0}>
  21:        0x100528cfc - rustdoc[e386f36fe3828e32]::passes::collect_trait_impls::collect_trait_impls
  22:        0x10039e914 - <rustc_session[b33ec7bea72ab9c0]::session::Session>::time::<rustdoc[e386f36fe3828e32]::clean::types::Crate, rustdoc[e386f36fe3828e32]::core::run_global_ctxt::{closure#7}>
  23:        0x100526c94 - rustdoc[e386f36fe3828e32]::core::run_global_ctxt
  24:        0x10039ec58 - <rustc_session[b33ec7bea72ab9c0]::session::Session>::time::<(rustdoc[e386f36fe3828e32]::clean::types::Crate, rustdoc[e386f36fe3828e32]::config::RenderOptions, rustdoc[e386f36fe3828e32]::formats::cache::Cache), rustdoc[e386f36fe3828e32]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  25:        0x10037c4ac - <rustc_middle[69929678d7438a39]::ty::context::GlobalCtxt>::enter::<rustdoc[e386f36fe3828e32]::main_args::{closure#1}::{closure#0}::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>
  26:        0x1003cfb54 - <rustc_interface[f4474a023a28a1e1]::interface::Compiler>::enter::<rustdoc[e386f36fe3828e32]::main_args::{closure#1}::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>
  27:        0x10047b0b4 - rustc_span[131a45c9b4032fd]::set_source_map::<core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>, rustc_interface[f4474a023a28a1e1]::interface::run_compiler<core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>, rustdoc[e386f36fe3828e32]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  28:        0x100533b38 - <scoped_tls[14441d0542f530d4]::ScopedKey<rustc_span[131a45c9b4032fd]::SessionGlobals>>::set::<rustc_interface[f4474a023a28a1e1]::interface::run_compiler<core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>, rustdoc[e386f36fe3828e32]::main_args::{closure#1}>::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>
  29:        0x1003ad540 - std[305047cfbd8f31b0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f4474a023a28a1e1]::util::run_in_thread_pool_with_globals<rustc_interface[f4474a023a28a1e1]::interface::run_compiler<core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>, rustdoc[e386f36fe3828e32]::main_args::{closure#1}>::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>
  30:        0x100495fb0 - <<std[305047cfbd8f31b0]::thread::Builder>::spawn_unchecked_<rustc_interface[f4474a023a28a1e1]::util::run_in_thread_pool_with_globals<rustc_interface[f4474a023a28a1e1]::interface::run_compiler<core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>, rustdoc[e386f36fe3828e32]::main_args::{closure#1}>::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f69943f7197f08d]::result::Result<(), rustc_span[131a45c9b4032fd]::ErrorGuaranteed>>::{closure#1} as core[f69943f7197f08d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:        0x1015cfa6c - std::sys::unix::thread::Thread::new::thread_start::hdf5e17a1fe30b937
  32:        0x191d6bfa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.72.0-nightly (fe7454bf4 2023-06-19) running on aarch64-apple-darwin

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #114657: rustdoc: ICE: synthetic auto trait impls: `unexpected result when selecting […]` involving unsatisfied bounds, projections and super trait bounds
### Code
This is the least I've managed to reduce the code: 
```Rust
pub trait Foo {
    type FooType;
}

pub trait Bar<const A: usize>: Foo<FooType = <Self as Bar<A>>::BarType> {
    type BarType;
}

pub(crate) const B: usize = 5;

pub trait Tec: Bar<B> {}

pub struct Structure<C: Tec> {
    _field: C::BarType,
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: aarch64-apple-darwin
release: 1.71.1
LLVM version: 16.0.5
```

With nightly version
```rust
rustc 1.73.0-nightly (f88a8b71c 2023-08-08)
binary: rustc
commit-hash: f88a8b71cebb730cbd5058c45ebcae1d4d9be377
commit-date: 2023-08-08
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 17.0.0
```

the compiler asks me to change the `Structure` as follows: 
```rust
pub struct Structure<C: Tec + Bar<5>> {
    _field: <C as Bar<B>>::BarType,
}
```
and now the error no longer occurs. 
### Error output
After running the `cargo doc`  command, I get the following:
```
thread 'rustc' panicked at 'Unexpected result when selecting Structure<C> Obligation(predicate=Binder(ProjectionPredicate(AliasTy { substs: [C, Const { ty: usize, kind: Leaf(0x0000000000000005) }], def_id: DefId(0:7 ~ rust_sodium[23d3]::Bar::BarType) }, Term::Ty(_)), []), depth=2)', compiler/rustc_trait_selection/src/traits/auto_trait.rs:756:33
stack backtrace:
   0:        0x10627acc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb75be2413dd8ceb3
   1:        0x1062c9a64 - core::fmt::write::h95d50546e769656f
   2:        0x106270e2c - std::io::Write::write_fmt::hce019ca594763835
   3:        0x10627ab14 - std::sys_common::backtrace::print::hae7307dcada41b2a
   4:        0x10627d578 - std::panicking::default_hook::{{closure}}::h30c41986d637ef23
   5:        0x10627d380 - std::panicking::default_hook::h81d03189ef2e7e78
   6:        0x10e72ff98 - rustc_driver_impl[21827c9a287a9f15]::install_ice_hook::{closure#0}
   7:        0x10627dc2c - std::panicking::rust_panic_with_hook::he8360f4d28da55fc
   8:        0x10627da0c - std::panicking::begin_panic_handler::{{closure}}::he9e07d605072520f
   9:        0x10627b0a0 - std::sys_common::backtrace::__rust_end_short_backtrace::he03bf52f9c1eb73a
  10:        0x10627d780 - _rust_begin_unwind
  11:        0x1062f49e0 - core::panicking::panic_fmt::ha5f5ca2311fff2ad
  12:        0x1122eba90 - <rustc_trait_selection[96b496d6d05954f1]::traits::auto_trait::AutoTraitFinder>::evaluate_predicates
  13:        0x1051c41f4 - <rustc_trait_selection[96b496d6d05954f1]::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc[426ea5acc7761888]::clean::types::Generics, <rustdoc[426ea5acc7761888]::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
  14:        0x1050cc2a8 - <rustdoc[426ea5acc7761888]::clean::auto_trait::AutoTraitFinder>::generate_for_trait
  15:        0x105122808 - <alloc[e0f95eb21a34f6a8]::vec::Vec<rustdoc[426ea5acc7761888]::clean::types::Item> as alloc[e0f95eb21a34f6a8]::vec::spec_from_iter::SpecFromIter<rustdoc[426ea5acc7761888]::clean::types::Item, core[6a5f4426c52daa32]::iter::adapters::filter_map::FilterMap<alloc[e0f95eb21a34f6a8]::vec::into_iter::IntoIter<rustc_span[2eda851f0959417e]::def_id::DefId>, <rustdoc[426ea5acc7761888]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
  16:        0x1050cc86c - <rustdoc[426ea5acc7761888]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls
  17:        0x10507d76c - rustdoc[426ea5acc7761888]::clean::utils::get_auto_trait_and_blanket_impls
  18:        0x1051fb170 - <rustdoc[426ea5acc7761888]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[426ea5acc7761888]::visit::DocVisitor>::visit_item
  19:        0x1051fb240 - <rustdoc[426ea5acc7761888]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[426ea5acc7761888]::visit::DocVisitor>::visit_item
  20:        0x1051fbd34 - <rustdoc[426ea5acc7761888]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[426ea5acc7761888]::visit::DocVisitor>::visit_crate
  21:        0x105091a30 - <rustc_session[1039b6c2e3771dcd]::session::Session>::time::<alloc[e0f95eb21a34f6a8]::vec::Vec<rustdoc[426ea5acc7761888]::clean::types::Item>, rustdoc[426ea5acc7761888]::passes::collect_trait_impls::collect_trait_impls::{closure#0}>
  22:        0x1051f94cc - rustdoc[426ea5acc7761888]::passes::collect_trait_impls::collect_trait_impls
  23:        0x105091d28 - <rustc_session[1039b6c2e3771dcd]::session::Session>::time::<rustdoc[426ea5acc7761888]::clean::types::Crate, rustdoc[426ea5acc7761888]::core::run_global_ctxt::{closure#7}>
  24:        0x1051a808c - rustdoc[426ea5acc7761888]::core::run_global_ctxt
  25:        0x105092064 - <rustc_session[1039b6c2e3771dcd]::session::Session>::time::<(rustdoc[426ea5acc7761888]::clean::types::Crate, rustdoc[426ea5acc7761888]::config::RenderOptions, rustdoc[426ea5acc7761888]::formats::cache::Cache), rustdoc[426ea5acc7761888]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  26:        0x10523c070 - <rustc_middle[a39402582bfd677]::ty::context::GlobalCtxt>::enter::<rustdoc[426ea5acc7761888]::main_args::{closure#1}::{closure#0}::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>
  27:        0x10504f878 - <rustc_interface[df80c09a2aa6fb7f]::interface::Compiler>::enter::<rustdoc[426ea5acc7761888]::main_args::{closure#1}::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>
  28:        0x105201938 - rustc_span[2eda851f0959417e]::set_source_map::<core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>, rustc_interface[df80c09a2aa6fb7f]::interface::run_compiler<core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>, rustdoc[426ea5acc7761888]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  29:        0x104fd0214 - <scoped_tls[80ce123946cbe7a6]::ScopedKey<rustc_span[2eda851f0959417e]::SessionGlobals>>::set::<rustc_interface[df80c09a2aa6fb7f]::interface::run_compiler<core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>, rustdoc[426ea5acc7761888]::main_args::{closure#1}>::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>
  30:        0x1050b901c - std[12e62f360352ccd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[df80c09a2aa6fb7f]::util::run_in_thread_pool_with_globals<rustc_interface[df80c09a2aa6fb7f]::interface::run_compiler<core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>, rustdoc[426ea5acc7761888]::main_args::{closure#1}>::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>
  31:        0x1051904c0 - <<std[12e62f360352ccd]::thread::Builder>::spawn_unchecked_<rustc_interface[df80c09a2aa6fb7f]::util::run_in_thread_pool_with_globals<rustc_interface[df80c09a2aa6fb7f]::interface::run_compiler<core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>, rustdoc[426ea5acc7761888]::main_args::{closure#1}>::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6a5f4426c52daa32]::result::Result<(), rustc_span[2eda851f0959417e]::ErrorGuaranteed>>::{closure#1} as core[6a5f4426c52daa32]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:        0x106286640 - std::sys::unix::thread::Thread::new::thread_start::h06dea01d0985d944
  33:        0x196397fa8 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.71.1 (eb26296b5 2023-08-03) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `rust-sodium`

Caused by:
  process didn't exit successfully: `/Users/queremendi/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustdoc --edition=2018 --crate-type lib --crate-name rust_sodium src/lib.rs -o /Users/queremendi/iohk/CryptoLibs/rust-testing/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=244 -C metadata=cfbf9925d0133061 -L dependency=/Users/queremendi/iohk/CryptoLibs/rust-testing/target/debug/deps --crate-version 0.1.0` (exit status: 101)

```

<details><summary><strong>Backtrace</strong></summary>
<p>
Output seems the same

```
thread 'rustc' panicked at 'Unexpected result when selecting Structure<C> Obligation(predicate=Binder(ProjectionPredicate(AliasTy { substs: [C, Const { ty: usize, kind: Leaf(0x0000000000000005) }], def_id: DefId(0:7 ~ rust_sodium[23d3]::Bar::BarType) }, Term::Ty(_)), []), depth=2)', compiler/rustc_trait_selection/src/traits/auto_trait.rs:756:33
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_trait_selection::traits::auto_trait::AutoTraitFinder>::evaluate_predicates
   3: <rustc_trait_selection::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc::clean::types::Generics, <rustdoc::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
   4: <rustdoc::clean::auto_trait::AutoTraitFinder>::generate_for_trait
   5: <alloc::vec::Vec<rustdoc::clean::types::Item> as alloc::vec::spec_from_iter::SpecFromIter<rustdoc::clean::types::Item, core::iter::adapters::filter_map::FilterMap<alloc::vec::into_iter::IntoIter<rustc_span::def_id::DefId>, <rustdoc::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
   6: <rustdoc::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls
   7: rustdoc::clean::utils::get_auto_trait_and_blanket_impls
   8: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::visit::DocVisitor>::visit_item
   9: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::visit::DocVisitor>::visit_item
  10: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::visit::DocVisitor>::visit_crate
  11: <rustc_session::session::Session>::time::<alloc::vec::Vec<rustdoc::clean::types::Item>, rustdoc::passes::collect_trait_impls::collect_trait_impls::{closure#0}>
  12: rustdoc::passes::collect_trait_impls::collect_trait_impls
  13: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#7}>
  14: rustdoc::core::run_global_ctxt
  15: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  16: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  17: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_args::{closure#1}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  18: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}::{closure#0}>
  19: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: rustc 1.71.1 (eb26296b5 2023-08-03) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `rust-sodium`

Caused by:
  process didn't exit successfully: `/Users/queremendi/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustdoc --edition=2018 --crate-type lib --crate-name rust_sodium src/lib.rs -o /Users/queremendi/iohk/CryptoLibs/rust-testing/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=244 -C metadata=cfbf9925d0133061 -L dependency=/Users/queremendi/iohk/CryptoLibs/rust-testing/target/debug/deps --crate-version 0.1.0` (exit status: 101)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fmease**
Fixes #114657.
Fixes #112828.
Fixes #107715.

r? rustdoc

### CODE REVIEW

File: tests/rustdoc-ui/synthetic-auto-trait-impls/const-in-super-trait-and-item-bound.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// We you used to ICE here while trying to synthesize auto trait impls.
```
Comment (GuillaumeGomez) [inline tests/rustdoc-ui/synthetic-auto-trait-impls/const-in-super-trait-and-item-bound.rs:1]: "We you used"? :wink:

File: tests/rustdoc-ui/synthetic-auto-trait-impls/lifetime-generic-user-impl-normalize.rs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// We you used to ICE here while trying to synthesize auto trait impls.
```
Comment (GuillaumeGomez) [inline tests/rustdoc-ui/synthetic-auto-trait-impls/lifetime-generic-user-impl-normalize.rs:1]: Same.

File: tests/rustdoc-ui/synthetic-auto-trait-impls/projections-in-super-trait-bound-unsatisfied.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+// We you used to ICE here while trying to synthesize auto trait impls.
```
Comment (GuillaumeGomez) [inline tests/rustdoc-ui/synthetic-auto-trait-impls/projections-in-super-trait-bound-unsatisfied.rs:1]: Same.

**Review by GuillaumeGomez — APPROVED** [review]
Thanks! r=me once typos are fixed.

**Comment by fmease** [comment]
o.O

**Comment by GuillaumeGomez** [comment]
Maybe it's because of changes in your other PR?

**Comment by fmease** [comment]
Right, I intentionally changed a `vid_map.get(vid).unwrap_or(r)` to a `vid_map[vid]` making rustdoc panic if `rustc::AutoTraitFinder` returns a region inference variable that cannot be resolved because that is really fishy. I can change it back with a `FIXME: investigate` which would also fix #123370 or remove the failing test from this PR and readd it once I understand `rustc::AutoTraitFinder` and fix the underlying issue if there's one.

`rustc::AutoTraitFinder` can also return placeholder regions `RePlaceholder` which doesn't seem right either and which makes rustdoc ICE, too (we have a GitHub issue for that already).

**Comment by fmease** [comment]
Should I implement the hot fix to fix the regressions from my simplification PR or should I postpone?

**Comment by GuillaumeGomez** [comment]
Remove the failing test from here and do the hotfix in another PR?

**Comment by fmease** [comment]
I've removed the failing test. Hot fix coming up in a sec.
@bors r=GuillaumeGomez
