### PR TITLE
set subsections_via_symbols for ld64 helper sections

### LINKED ISSUE #139744: functions marked with `#[no_mangle]` cannot be GC-ed on MacOS
### Code

I tried this code:

```rust
// src/main.rs

unsafe extern "C" {
    unsafe static UNDEFINED: usize;
}

#[unsafe(no_mangle)]
pub fn used() {
    println!("UNDEFINED = {}", unsafe { UNDEFINED });
}

pub fn marker() -> usize {
    0
}

fn main() {
    assert_eq!(marker(), 0_usize);
}
```

```
cargo build --target aarch64-apple-darwin
```

I expected to see this happen: *it builds*

Instead, this happened: *it emits linker errors*

### Version it worked on

1.86.0

### Version with regression

nightly-2025-02-26; bisects to https://github.com/rust-lang/rust/pull/133832

### PR DESCRIPTION
**Pull request by usamoi**
closes https://github.com/rust-lang/rust/issues/139744
cc @madsmtm

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 1]
```diff
@@ -221,6 +221,9 @@ pub(crate) fn create_object_file(sess: &Session) -> Option<write::Object<'static
 
         file.set_macho_build_version(macho_object_build_version_for_target(sess))
     }
+    if binary_format == BinaryFormat::MachO {
+        file.set_subsections_via_symbols();
+    }
```
Comment (madsmtm) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:226]: It's not clear to me that this needs to be in `create_object_file`? Maybe it would be better to only use it in `add_linked_symbol_object`?

Also, `MH_SUBSECTIONS_VIA_SYMBOLS` is vastly under-documented, I'd really like to see a comment here explaining why it's safe for us to use.

File: tests/run-make/executable-no-mangle-strip/main.rs [hunk 2]
```diff
@@ -0,0 +1,16 @@
+unsafe extern "C" {
```
Comment (madsmtm) [inline tests/run-make/executable-no-mangle-strip/main.rs:1]: Nit: This can be a UI test, use something like `//@ build-pass` or `//@ run-pass`

**Review by madsmtm — CHANGES_REQUESTED** [review]
Thanks for the ping!

@rustbot label O-apple O-linkage

File: tests/run-make/executable-no-mangle-strip/main.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+    unsafe static UNDEFINED: usize;
+}
+
+#[unsafe(no_mangle)]
+pub fn used() {
+    println!("UNDEFINED = {}", unsafe { UNDEFINED });
+}
```
Comment (madsmtm) [inline tests/run-make/executable-no-mangle-strip/main.rs:8]: Honestly, I'm kind of surprised that this worked in the past. Could you describe the use-case?

I'd also be interested, does this pattern work on other platforms?

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 1 above)
Comment (usamoi) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:226]: [Object::set_subsections_via_symbols](https://docs.rs/object/latest/object/write/struct.Object.html#method.set_subsections_via_symbols) says it should be called before `add_section` or `add_subsection`, so I feel it better to put it here (not error-prone).

I don't know whether it's safe or not, either. I searched on the Internet and found that this is the only way for Mach-O to implement GC.

File: tests/run-make/executable-no-mangle-strip/main.rs (hunk 3 above)
Comment (usamoi) [reply tests/run-make/executable-no-mangle-strip/main.rs:8]: It's used by https://github.com/pgcentralfoundation/pgrx. It's a framework for developing PostgreSQL extensions. This trick is used for writing hybrid (dylib and host tools) code. Code about host tools could be compiled to an executable, since dylib-related code are GC-ed.

This should be a reasonable usage. Please see https://github.com/rust-lang/rust/pull/95604 and https://github.com/rust-lang/rust/pull/95363#issuecomment-1079932354.

Yes. It works for Linux and Windows too.

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 1 above)
Comment (madsmtm) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:226]: My problem with having it in `create_object_file` is that it may negatively affect the other object files we create (which again is hard to tell for sure, since the docs around it are so limited).

File: tests/run-make/executable-no-mangle-strip/main.rs (hunk 3 above)
Comment (madsmtm) [reply tests/run-make/executable-no-mangle-strip/main.rs:8]: Thanks for the answer. Might make sense to leave a comment in the file about this, and perhaps link to https://github.com/rust-lang/rust/issues/139744, stating that it is a regression test for that?

Comment (usamoi) [reply tests/run-make/executable-no-mangle-strip/main.rs:8]: The symbol is present in fhe dynamic library. It's GC-ed iff the final artifact is the executable.

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 1 above)
Comment (usamoi) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs:226]: Ah! I didn't notice that this function has multiple callers.

I will add a parameter to control this behavior.

**Comment by jieyouxu** [comment]
cc @bjorn3 @petrochenkov in case this is problematic

File: tests/ui/linking/executable-no-mangle-strip.rs [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+// are not indirectly referenced by main.
+
+unsafe extern "C" {
+    unsafe static THIS_SYMBOL_SHOULD_BE_UNDEFINED: usize;
+}
+
+#[unsafe(no_mangle)]
+pub unsafe fn used() {
+    println!("THIS_SYMBOL_SHOULD_BE_UNDEFINED = {}", unsafe { THIS_SYMBOL_SHOULD_BE_UNDEFINED });
+}
```
Comment (madsmtm) [inline tests/ui/linking/executable-no-mangle-strip.rs:14]: Nit: I know that `#[no_mangle]` implies it, but could we also add an explicit test for `#[used]`?

File: tests/run-make/executable-no-mangle-strip/main.rs (hunk 3 above)
Comment (madsmtm) [reply tests/run-make/executable-no-mangle-strip/main.rs]: An idea then would perhaps be to add another test (or use UI-test revisions) with `#![crate_type = "dylib"]` and `//@ dont-check-compiler-stderr` that expectedly fails?

File: tests/ui/linking/executable-no-mangle-strip.rs (hunk 4 above)
Comment (usamoi) [reply tests/ui/linking/executable-no-mangle-strip.rs:14]: Using `#[used]` emits errors, while `#[no_mangle]` does not, on MacOS.

Don't know why.

Comment (usamoi) [reply tests/ui/linking/executable-no-mangle-strip.rs:14]: I know why now.

On MacOS, `#[used]` emits `llvm.compiler.used`. So `#[used(compiler)]` is needed here. Is it expected behavior?

Comment (bjorn3) [reply tests/ui/linking/executable-no-mangle-strip.rs:14]: TIL that `#[used]` is an alias for `#[used(linker)]` on some platforms: https://github.com/rust-lang/rust/blob/f836ae4e663b6e8938096b8559e094d18361be55/compiler/rustc_codegen_ssa/src/codegen_attrs.rs#L195-L223 Eventually `#[used]` should be changed to `#[used(linker)]` unconditionally anyway.

File: tests/run-make/executable-no-mangle-strip/main.rs (hunk 3 above)
Comment (usamoi) [reply tests/run-make/executable-no-mangle-strip/main.rs]: I think it's alreay tested in https://github.com/rust-lang/rust/tree/master/tests/run-make/c-link-to-rust-dylib.

Comment (madsmtm) [reply tests/run-make/executable-no-mangle-strip/main.rs]: No, I meant having test that _fails_ when trying to link undefined symbols in a dylib

Comment (usamoi) [reply tests/run-make/executable-no-mangle-strip/main.rs]: It is added.

**Comment by Nadrieril** [comment]
r? codegen

**Comment by usamoi** [comment]
I hope this gets a beta backport to prevent [pgrx](https://github.com/pgcentralfoundation/pgrx) from being broken on macOS.

@rustbot label +beta-nominated

File: compiler/rustc_codegen_ssa/src/back/metadata.rs (hunk 1 above)
Comment (madsmtm) [reply compiler/rustc_codegen_ssa/src/back/metadata.rs]: Eh, I'd still have preferred to just change `add_linked_symbol_object`, it'd be unexpected if `create_object_file` added any sections or subsections, it's literally prefixed "create" as in "only create, do not fill".

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 5]
```diff
@@ -221,6 +224,11 @@ pub(crate) fn create_object_file(sess: &Session) -> Option<write::Object<'static
 
         file.set_macho_build_version(macho_object_build_version_for_target(sess))
     }
+    if binary_format == BinaryFormat::MachO {
+        if set_subsections_via_symbols {
+            file.set_subsections_via_symbols();
```
Comment (madsmtm) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:229]: Still needs a documentation comment IMO explaining _why_ we do this.

File: tests/run-make/executable-no-mangle-strip/main.rs (hunk 3 above)
Comment (madsmtm) [reply tests/run-make/executable-no-mangle-strip/main.rs]: Thanks!

**Review by madsmtm — APPROVED** [review]

**Comment by saethlin** [comment]
Looks good! Thanks @madsmtm for also reviewing ❤️ 

@bors r=saethlin,madsmtm

**Comment by Zalathar** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/140231#issuecomment-2826437922

@bors r-

**Comment by usamoi** [comment]
On Windows, the linker seems to prioritize symbol resolution over code elimination. So on Windows, this test uses `raw-dylib` and `pass-mode` is changed to `run-pass`.

@rustbot ready

**Comment by jieyouxu** [comment]
This was [discussed in today's compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-04-24/near/514139925). The compiler team will revisit this beta backport decision next week after this PR merges.

**Comment by usamoi** [comment]
On windows-gnu, the linker removes statics marked with `#[used]`, but does not functions marked with `#[used]` or referenced by statics marked with `#[used]`. Not interested in this target, so I mark the test as `ignore-windows-gnu` for now.

@rustbot ready

**Comment by saethlin** [comment]
Can you add the reason windows-gnu is special for this test to the magic comment?

**Comment by rylev** [comment]
I don't really understand how this change could have the performance impact seen here. Some of the regressions do seem like pure noise (with the next run returning back to the previous baseline), but not all of them.

@usamoi @saethlin would you agree that the regressions here are unlikely to be actually caused by this change?

**Comment by madsmtm** [comment]
This should only affect macOS/Apple platforms, and I don't think the benchmarks are run on those?

**Comment by rylev** [comment]
That is correct. I'll mark this as triaged

@rustbot label: +perf-regression-triaged

**Comment by jieyouxu** [comment]
This was discussed in [today's compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-05-01/near/515511171). Beta backport was approved, thanks!

@rustbot label: +beta-accepted
