### PR TITLE
Issue 56128 segment id ice nightly

### LINKED ISSUE #55475: Panic rustc 1.31.0-nightly (96064eb61 2018-10-28) running on x86_64-pc-windows-msvc: in hir_id_validator.rs:31
Trying to build: https://github.com/rust-analyzer/rust-analyzer latest nightly rustc 1.31.0-nightly (96064eb61 2018-10-28) running on x86_64-pc-windows-msvc panics.

>  RUST_BACKTRACE=1 cargo +nightly check
    Checking idna v0.1.5
    Checking ra_syntax v0.1.0 (C:\projects\test\rust-analyzer\crates\ra_syntax)
thread 'main' panicked at 'librustc\hir\map\hir_id_validator.rs:31:
ItemLocalIds not assigned densely in ::grammar[0]::expressions[0]::{{?}}[1]. Max ItemLocalId = 4, missing IDs = ["[local_id: 1, node:unknown node (id=13965)]", "[local_id: 2, node:path segment super (id=13964)]"]; seens IDs = ["(NodeId(13963) use grammar::expressions::{{?}} (id=13963))", "(NodeId(13967) path segment atom (id=13967))", "(NodeId(13966) path segment self (id=13966))"]
HirIdValidator: The recorded owner of path segment super (id=13964) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[2]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[2]/2 assigned for nodes path segment super (id=13964) and path segment atom (id=60792)
HirIdValidator: The recorded owner of path segment super (id=13964) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[3]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[3]/2 assigned for nodes path segment super (id=13964) and path segment atom (id=60795)', librustc\util\bug.rs:47:26
stack backtrace:
   0: <std::future::SetOnDrop as core::ops::drop::Drop>::drop
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
   4: std::panicking::rust_panic_with_hook
   5: rustc::ty::query::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::read_u32
   6: rustc::ty::context::tls::track_diagnostic
   7: rustc::ty::context::tls::track_diagnostic
   8: rustc::ty::context::tls::track_diagnostic
   9: rustc::ty::context::tls::track_diagnostic
  10: rustc::util::bug::bug_fmt
  11: rustc::util::bug::bug_fmt
  12: <rustc::hir::def_id::LocalDefId as core::fmt::Debug>::fmt
  13: rustc::hir::map::map_crate
  14: rustc_driver::driver::build_output_filenames
  15: rustc_driver::driver::compile_input
  16: rustc_driver::run_compiler
  17: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  18: rustc_driver::run_compiler
  19: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  20: <rustc_driver::pretty::IdentifiedAnnotation<'hir> as rustc_driver::pretty::PrinterSupport>::sess
  21: _rust_maybe_catch_panic
  22: rustc_driver::target_features::add_configuration
  23: rustc_driver::main
  24: <unknown>
  25: std::panicking::update_panic_count
  26: _rust_maybe_catch_panic
  27: std::rt::lang_start_internal
  28: <unknown>
  29: <unknown>
  30: BaseThreadInitThunk
  31: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (96064eb61 2018-10-28) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `ra_syntax`.
warning: build failed, waiting for other jobs to finish...
error: build failed

### LINKED ISSUE #56128: Beta ICE: ItemLocalIds not assigned densely
Hi! I am seeing an ICE in rust-analyzer, when updating rustc from `rustc 1.31.0-beta.14` to `rustc 1.31.0-beta.15` (so, seems pretty bad?).

Error message:

<details>

```
   Compiling ra_syntax v0.1.0 (/home/matklad/projects/rust-analyzer/crates/ra_syntax)               
thread 'main' panicked at 'librustc/hir/map/hir_id_validator.rs:31:                                 
ItemLocalIds not assigned densely in ::grammar[0]::expressions[0]::{{?}}[1]. Max ItemLocalId = 4, missing IDs = ["[local_id: 1, node:unknown node (id=28193)]", "[local_id: 2, node:path segment super (id=28192)]"]; seens IDs = ["(NodeId(28191) use grammar::expressions::{{?}} (id=28191))", "(NodeId(28195) path segment atom (id=28195))", "(NodeId(28194) path segment self (id=28194))"]
HirIdValidator: The recorded owner of path segment super (id=28192) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[2]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[2]/2 assigned for nodes path segment super (id=28192) and path segment atom (id=92512)
HirIdValidator: The recorded owner of path segment super (id=28192) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[3]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[3]/2 assigned for nodes path segment super (id=28192) and path segment atom (id=92515)', librustc/util/bug.rs:47:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                  
                                                                                                    
error: internal compiler error: unexpected panic                                                    
                                                                                                    
note: the compiler unexpectedly panicked. this is a bug.                                            
                                                                                                    
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                    
note: rustc 1.31.0-beta.15 (4b3a1d911 2018-11-20) running on x86_64-unknown-linux-gnu               
                                                                                                    
note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib                                
                                                                                                    
note: some of the compiler flags provided by cargo are hidden                                       
                                                                                                    
error: Could not compile `ra_syntax`.                                                               
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'librustc/hir/map/hir_id_validator.rs:31:                                 
ItemLocalIds not assigned densely in ::grammar[0]::expressions[0]::{{?}}[1]. Max ItemLocalId = 4, missing IDs = ["[local_id: 1, node:unknown node (id=28200)]", "[local_id: 2, node:path segment super (id=28199)]"]; seens IDs = ["(NodeId(28198) use grammar::expressions::{{?}} (id=28198))", "(NodeId(28202) path segment atom (id=28202))", "(NodeId(28201) path segment self (id=28201))"]
HirIdValidator: The recorded owner of path segment super (id=28199) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[2]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[2]/2 assigned for nodes path segment super (id=28199) and path segment atom (id=104341)
HirIdValidator: The recorded owner of path segment super (id=28199) is ::grammar[0]::expressions[0]::{{?}}[1] instead of ::grammar[0]::expressions[0]::{{?}}[3]
HirIdValidator: Same HirId ::grammar[0]::expressions[0]::{{?}}[3]/2 assigned for nodes path segment super (id=28199) and path segment atom (id=104344)', librustc/util/bug.rs:47:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                  
                                                                                                    
error: internal compiler error: unexpected panic                                                    
                                                                                                    
note: the compiler unexpectedly panicked. this is a bug.                                            
                                                                                                    
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                    
note: rustc 1.31.0-beta.15 (4b3a1d911 2018-11-20) running on x86_64-unknown-linux-gnu               
                                                                                                    
note: compiler flags: -C debuginfo=2 -C incremental                                                 
                                                                                                    
note: some of the compiler flags provided by cargo are hidden  
 ```

</details>

Steps to reproduce:

```
$ git clone git@github.com:rust-analyzer/rust-analyzer.git
$ cd rust-analyzer
$ git reset --hard 049f8df93cca05af395ce873738dc85d5a25f3fc
$ cargo test
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Tentative fix for #56128 

From what I can tell, the problem is that if you have `pub(super) use foo::{a, b}`, then when we explode the `a` and `b`, the segment ids from the `super` path were not getting cloned. However, once I fixed *that*, then I ran into a problem that the "visibility" node-ids were not present in the final HIR -- this is because the visibility of the "stem" that is returned in this case was getting reset to inherited. I don't *think* it is a problem to undo that, so that the visibility is returned unmodified.

Fixes #55475
Fixes #56128 

cc @nrc @petrochenkov

### CODE REVIEW

**Review by nrc — COMMENTED** [review]
Did you mean to update the submodules?

LGTM otherwise

**Comment by nikomatsakis** [comment]
Er, no, no I did not.

**Comment by nikomatsakis** [comment]
I guess though that this is fallout from the visibility change:

```
[00:48:29] ---- [ui] ui/lint/unreachable_pub-pub_crate.rs stdout ----
[00:48:29] diff of stderr:
[00:48:29] 
[00:48:29] 14    = help: or consider exporting it for use by other crates
[00:48:29] 15 
[00:48:29] 16 warning: unreachable `pub` item
[00:48:29] +   --> $DIR/unreachable_pub-pub_crate.rs:26:5
[00:48:29] +    |
[00:48:29] + LL |     pub use std::env::{Args}; // braced-use has different item spans than unbraced
[00:48:29] +    |     ---^^^^^^^^^^^^^^^
[00:48:29] +    |     |
[00:48:29] +    |     help: consider restricting its visibility: `pub(crate)`
[00:48:29] +    |
[00:48:29] +    = help: or consider exporting it for use by other crates
[00:48:29] + 
[00:48:29] + warning: unreachable `pub` item
[00:48:29] 18    |
[00:48:29] 18    |
[00:48:29] 19 LL |     pub use std::env::{Args}; // braced-use has different item spans than unbraced
```

**Comment by nikomatsakis** [comment]
I can make that code ignore `ListStem` but..ugh.

**Comment by nikomatsakis** [comment]
I tried an alternate fix (use the vis for the last item) but it ice'd because the owner was wrong; [more notes from discord here](https://discordapp.com/channels/442252698964721669/446773231018442763/514904968394965002). 

I don't have a better idea than what's in this PR -- I leave it to @nrc and @petrochenkov to decide best course of action =)

**Comment by alexcrichton** [comment]
@bors: p=1

we're gonna want to backport this

File: src/librustc/hir/lowering.rs [hunk 1]
```diff
@@ -3143,17 +3139,27 @@ impl<'a> LoweringContext<'a> {
                     });
                 }
 
-                // Privatize the degenerate import base, used only to check
-                // the stability of `use a::{};`, to avoid it showing up as
-                // a re-export by accident when `pub`, e.g. in documentation.
                 let def = self.expect_full_def_from_use(id).next().unwrap_or(Def::Err);
                 let path = P(self.lower_path_extra(def, &prefix, ParamMode::Explicit, None));
-                *vis = respan(prefix.span.shrink_to_lo(), hir::VisibilityKind::Inherited);
```
Comment (petrochenkov) [inline src/librustc/hir/lowering.rs]: IIRC, you still need to reset at least `pub` (`hir::VisibilityKind::Public`) into something more private, otherwise you'll get *a lot* of noise from rustdoc (the stem is emitted for all braced imports).

This way the hack for `UnreachablePub` can be avoided as well.

This should be ok since `hir::VisibilityKind::Public` doesn't have a path with node IDs inside it.

Comment (petrochenkov) [reply src/librustc/hir/lowering.rs]: Everything except for `VisibilityKind::Restricted` can be reset to `VisibilityKind::Inherited` basically.

**Comment by petrochenkov** [comment]
Beside https://github.com/rust-lang/rust/pull/56143#discussion_r235570778 everything looks reasonable.

(I never fully understood what are relations between node ids, def ids, their owners, parents, etc, and why @QuietMisdreavus had to do all those horrible things with them in https://github.com/rust-lang/rust/pull/51425.)
