### PR TITLE
Don't warn an empty pattern unreachable if we're not sure the data is valid

### LINKED ISSUE #117119: Incorrect "unreachable match arm" warning
The following code generates a warning:
```rust
fn main() {
    #[derive(Copy, Clone)]
    enum Void {}
    union Uninit<T: Copy> {
        value: T,
        uninit: (),
    }
    unsafe {
        let x: Uninit<Void> = Uninit { uninit: () };
        match x.value {
            _ => println!("hi from the void!"),
        }
    }
}
```
```
warning: unreachable pattern
  --> src/main.rs:12:13
   |
12 |             _ => println!("hi from the void!"),
   |             ^
   |
   = note: `#[warn(unreachable_patterns)]` on by default
```
This warning is wrong: running the code in Miri shows that this arm is reachable and there is no UB.

### PR DESCRIPTION
**Pull request by Nadrieril**
Exhaustiveness checking used to be naive about the possibility of a place containing invalid data. This could cause it to emit an "unreachable pattern" lint on an arm that was in fact reachable, as in https://github.com/rust-lang/rust/issues/117119.

This PR fixes that. We now track whether a place that is matched on may hold invalid data. This also forced me to be extra precise about how exhaustiveness manages empty types.

Note that this now errs in the opposite direction: the following arm is truly unreachable (because the binding causes a read of the value) but not linted as such. I'd rather not recommend writing a `match ... {}` that has the implicit side-effect of loading the value. [Never patterns](https://github.com/rust-lang/rust/issues/118155) will solve this cleanly.
```rust
match union.value {
    _x => unreachable!(),
}
```

I recommend reviewing commit by commit. I went all-in on the test suite because this went through a lot of iterations and I kept everything. The bit I'm least confident in is `is_known_valid_scrutinee` in `check_match.rs`.

Fixes https://github.com/rust-lang/rust/issues/117119.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Perf looked neutral on my machine but just in case

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
r? compiler-errors

Do you have justification for the perf regression? Is there any way around it? I assume if no, then we can land this since it's obviously a correctness fix, but I do want to be certain that it's necessary before accepting this (admittedly somewhat minor) perf hit.

**Comment by Nadrieril** [comment]
Yeah I expected a perf regression because of the validity tracking. It adds an extra step for every constructor we try, and match-stress has an enum with 8000 of these. I don't think there's a way around it, I need to know the validity of every inspected place.

My guess is that it's particularly impactful because it allocates; that's not easily avoided, I'm planning to try arena allocation of the `Matrix` in the future

**Comment by compiler-errors** [comment]
OK I shall review this PR tomorrow then with that in mind.

File: compiler/rustc_middle/src/ty/inhabitedness/inhabited_predicate.rs [hunk 1]
```diff
@@ -71,11 +77,25 @@ impl<'tcx> InhabitedPredicate<'tcx> {
                 match normalized_pred {
                     // We don't have more information than we started with, so consider inhabited.
                     Self::GenericType(_) => Ok(true),
-                    pred => pred.apply_inner(tcx, param_env, in_module),
+                    pred => {
+                        // A type which is cyclic when monomorphized can happen here since the
+                        // layout error would only trigger later. See e.g. `tests/ui/sized/recursive-type-2.rs`.
+                        if eval_stack.contains(&t) {
+                            return Ok(true); // Recover; this will error later.
+                        }
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/ty/inhabitedness/inhabited_predicate.rs:85]: What used to happen here? A stack overflow? IS there a test that exercises this and would repro it on nightly with `exhaustive_patterns `?

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 2]
```diff
@@ -287,35 +288,114 @@ impl<'thir, 'p, 'tcx> MatchVisitor<'thir, 'p, 'tcx> {
...
+            | LogicalOp { .. }
+            | Loop { .. }
+            | Match { .. }
+            | NamedConst { .. }
+            | NonHirLiteral { .. }
+            | OffsetOf { .. }
+            | Repeat { .. }
+            | StaticRef { .. }
+            | ThreadLocalRef { .. }
+            | Tuple { .. }
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs:354]: We don't need to recurse into aggregates?

File: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs [hunk 3]
```diff
@@ -974,15 +971,17 @@ pub(super) enum ConstructorSet {
 /// constructors that exist in the type but are not present in the column.
 ///
 /// More formally, if we discard wildcards from the column, this respects the following constraints:
-/// 1. the union of `present` and `missing` covers the whole type
+/// 1. the union of `present`, `missing` an `missing_empty` covers all the constructors of the type
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:974]: typo: and

File: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs [hunk 4]
```diff
@@ -970,82 +1047,74 @@ impl ConstructorSet {
...
+            | ty::FnPtr(_)
+            | ty::Dynamic(_, _, _)
+            | ty::Closure(_, _)
+            | ty::Coroutine(_, _, _)
+            | ty::CoroutineWitness(_, _)
+            | ty::Alias(_, _)
+            | ty::Param(_)
+            | ty::Bound(_, _)
+            | ty::Placeholder(_)
+            | ty::Infer(_)
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1116]: infer should be a bug

File: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs [hunk 5]
```diff
@@ -970,82 +1047,74 @@ impl ConstructorSet {
...
+            ty::Float(_)
+            | ty::Str
+            | ty::Foreign(_)
+            | ty::RawPtr(_)
+            | ty::FnDef(_, _)
+            | ty::FnPtr(_)
+            | ty::Dynamic(_, _, _)
+            | ty::Closure(_, _)
+            | ty::Coroutine(_, _, _)
+            | ty::CoroutineWitness(_, _)
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1111]: witness should be a bug too

File: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs [hunk 6]
```diff
@@ -1186,17 +1245,16 @@ impl ConstructorSet {
...
+                if !pcx.is_top_level {
+                    missing_empty.push(NonExhaustive);
+                }
             }
-            ConstructorSet::Uninhabited => {}
         }
 
+        if !pcx.cx.tcx.features().exhaustive_patterns {
+            missing.extend(missing_empty);
+        }
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs]: So this is why we don't need to check exhaustive_patterns in `is_uninhabited`? 
Because we now *always* characterize the ctor as missing-but-empty, and just treat them as missing here at the end?

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs]: Yep exactly. Before this PR we kinda lied by pretending constructors were nonempty when `exhaustive_patterns` is off. Now we properly track which constructor is or isn't empty in `ConstructorSet`, and decide whether to count them as missing here

File: compiler/rustc_middle/src/ty/inhabitedness/inhabited_predicate.rs (hunk 1 above)
Comment (Nadrieril) [reply compiler/rustc_middle/src/ty/inhabitedness/inhabited_predicate.rs:85]: Yep, [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=003924cba3ab88ea27d345e709e3bb79). It's in `tests/ui/sized/recursive-type-2.rs`

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs (hunk 2 above)
Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:354]: No, unless I misunderstand what these constructs do, this means we have `match (x, y, z) { ... }`. A `(x, y, z)` expression evaluates to a value, not a place, and thus cannot hold invalid data without UB. The conservative direction would in fact be `false`.

File: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs (hunk 4 above)
Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1116]: :+1: Are all the other ones possible? `Placeholder` and `Bound` feel like they shouldn't.

Comment (compiler-errors) [reply compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs]: Yes, those could also be bug.

**Review by compiler-errors — APPROVED** [review]

File: compiler/rustc_mir_build/src/thir/pattern/check_match.rs [hunk 7]
```diff
@@ -287,35 +288,114 @@ impl<'thir, 'p, 'tcx> MatchVisitor<'thir, 'p, 'tcx> {
         }
     }
 
+    /// Inspects the match scrutinee expression to determine whether the place it evaluates to may
+    /// hold invalid data.
+    fn is_known_valid_scrutinee(&self, scrutinee: &Expr<'tcx>) -> bool {
+        use ExprKind::*;
+        match &scrutinee.kind {
+            // Both pointers and references can validly point to a place with invalid data.
```
Comment (RalfJung) [inline compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: For references I'd say this is an open question, but we want to be conservative here.

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: Ah indeed, I'll update the comment to say that. Does the rest of this function seem right to you?

Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: I don't quite understand how it is used, but it treats unions and raw ptr deref specially so that seems right. For reference deref I guess we have to see how we want to treat them in the end, but it seems good to be conservative -- and I assume "not known to be valid" is the conservative answer here.

Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: What I am missing is test coverage, is there any test for the case of a union with an uninhabited field, or raw pointers?

Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: > I assume "not known to be valid" is the conservative answer here

Yep

Here's the test cases: https://github.com/Nadrieril/rust/blob/c3df51a976dfa69f0f1869997fdf79516ba6afab/tests/ui/pattern/usefulness/empty-types.rs#L191-L271

Comment (RalfJung) [reply compiler/rustc_mir_build/src/thir/pattern/check_match.rs:296]: Ah, nice! The tests for references should also have the comment about this being undecided so the lint being conservative.

Feel free to r? me on the PR that adds the comments.
