### PR TITLE
Don't suggest `impl Trait` in path position

### LINKED ISSUE #113264: Compiler suggestion ping-pongs between E0283 and E0562
I tried to [call the gtk-rs insert_before function](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.insert_before), with this signature:

```rust
    fn insert_before(&self, parent: &impl IsA<Widget>, next_sibling: Option<&impl IsA<Widget>>);
```

I got this error:

```
error[E0283]: type annotations needed
   --> src/ui/task_list.rs:115:46
    |
115 |         scroller.insert_before(&*self.obj(), None);
    |                  -------------               ^^^^ cannot infer type of the type parameter `T` declared on the enum `Option`
    |                  |
    |                  required by a bound introduced by this call
```

Along with this suggestion:

```
    |
410 |     fn insert_before(&self, parent: &impl IsA<Widget>, next_sibling: Option<&impl IsA<Widget>>);
    |                                                                                   ^^^^^^^^^^^ required by this bound in `WidgetExt::insert_before`
help: consider specifying the generic argument
    |
115 |         scroller.insert_before(&*self.obj(), None::<&impl IsA<Widget>>);
    |                                                  +++++++++++++++++++++
```

That suggestion ran me into a different error:

```
error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in paths
   --> src/ui/task_list.rs:115:54
    |
115 |         scroller.insert_before(&*self.obj(), None::<&impl IsA<Widget>>);
    |                                                      ^^^^^^^^^^^^^^^^
```

I would expect the first error to understand that using `impl Trait` within the path would lead me into E0562 and thus not make that suggestion.

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

### PR DESCRIPTION
**Pull request by jieyouxu**
Fixes #113264.

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 1]
```diff
@@ -482,7 +482,32 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                                    let ty_vars = infcx_inner.type_variables();
+                                    let var_origin = ty_vars.var_origin(ty_vid);
+                                    if let TypeVariableOriginKind::TypeParameterDefinition(name, _) = var_origin.kind
+                                        && name.as_str().starts_with("impl ")
+                                    {
+                                        true
+                                    } else {
+                                        false
+                                    }
+                                };
```
Comment (jieyouxu) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: Is there a less hacky way to do this check?

Comment (jieyouxu) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: Is there a less hacky way to do this check?

Comment (lcnr) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: I think it's better to change `fn fmt_printer` to not use the name of`TypeVariableOriginKind::TypeParameterDefinition` if the `DefId` is from an argument position impl trait instead.

Comment (tgross35) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: I think reaching 11 indentation levels might be justification to refactor some of this to a function anyway 🙂

Comment (jieyouxu) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: > I think it's better to change `fn fmt_printer` to not use the name of`TypeVariableOriginKind::TypeParameterDefinition` if the `DefId` is from an argument position impl trait instead.

How do you check if a `DefId` is from an arg position `impl Trait`?

Comment (lcnr) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:496]: `tcx.generics_of(tcx.parent(def_id))`, look at the https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/generics/struct.GenericParamDef.html for whether the type param is synthetic.

I am not 10% sure whether the `parent` is necessary 🤷 try it without, if it ices, add `tcx.parent`

Comment (jieyouxu) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs]: Thanks, I think that works, but I'm not sure if it's 100% correct.

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 2]
```diff
@@ -162,10 +162,17 @@ fn fmt_printer<'a, 'tcx>(infcx: &'a InferCtxt<'tcx>, ns: Namespace) -> FmtPrinte
...
         let ty_vars = infcx_inner.type_variables();
         let var_origin = ty_vars.var_origin(ty_vid);
-        if let TypeVariableOriginKind::TypeParameterDefinition(name, _) = var_origin.kind
+        if let TypeVariableOriginKind::TypeParameterDefinition(name, def_id) = var_origin.kind
             && !var_origin.span.from_expansion()
         {
-            Some(name)
+            let ty::Generics { params, .. } = infcx.tcx.generics_of(infcx.tcx.parent(def_id));
+            if let Some(generic_param_def) = params.iter().find(|&generic_param_def| generic_param_def.name == name)
+                && let ty::GenericParamDefKind::Type { synthetic: true, .. } = generic_param_def.kind
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:170]: please don't look up by name, instead check that the `DefId` is equal. Instead use `param_def_id_to_index` and then `param_at` of the `generics`.

**Review by lcnr — COMMENTED** [review]
one nit, after that r=me

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 3]
```diff
@@ -162,10 +162,18 @@ fn fmt_printer<'a, 'tcx>(infcx: &'a InferCtxt<'tcx>, ns: Namespace) -> FmtPrinte
...
         let ty_vars = infcx_inner.type_variables();
         let var_origin = ty_vars.var_origin(ty_vid);
-        if let TypeVariableOriginKind::TypeParameterDefinition(name, _) = var_origin.kind
+        if let TypeVariableOriginKind::TypeParameterDefinition(name, def_id) = var_origin.kind
             && !var_origin.span.from_expansion()
         {
-            Some(name)
+            let generics = infcx.tcx.generics_of(infcx.tcx.parent(def_id));
+            if let Some(idx) = generics.param_def_id_to_index(infcx.tcx, def_id)
+                && let generic_param_def = generics.param_at(idx as usize, infcx.tcx)
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:170]:
```suggestion
            if let Some(idx) = generics.param_def_id_to_index(infcx.tcx, def_id)
                && let generic_param_def = generics.param_at(idx as usize, infcx.tcx)
```
please `unwrap` instead of using `if let`. Not getting `Some` here indicates a bug

Comment (workingjubilee) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs]: very astute! https://github.com/rust-lang/rust/issues/113610
