### PR TITLE
Take supertraits into account when calculating associated types

### LINKED ISSUE #24010: Error extending Fn trait then using it as a trait object: the value of the associated type `Output must be specified
``` rust
trait Foo: Fn(i32) + Send { }
impl<T:?Sized + Fn(i32) + Send> Foo for T { }

fn wants_foo(t: Box<Foo>) {
}

fn main() {
  let f = Box::new(|x| println!("{}", x));
  wants_foo(f);
}
```

Output:

```
<anon>:9:13: 9:14 error: the value of the associated type `Output` (from the trait `core::ops::FnOnce`) must be specified [E0191]
<anon>:9   wants_foo(f);
                     ^
```

cc @nikomatsakis

### PR DESCRIPTION
**Pull request by alexreg**
Fixes #24010 and #23856. Applies to trait aliases too.

As a by-product, this PR also makes repeated bindings of the same associated item in the same definition a hard error. This was previously a warning with a note about it becoming a hard error in the future. See #50589 for more info.

I talked about this with @nikomatsakis recently, but only very superficially, so this shouldn't stop anyone from assigning it to themself to review and r+.

N.B. The "WIP" commits represent imperfect attempts to solve the problem just for trait objects, but I've left them in for reference for the sake of whomever is reviewing this.

CC @carllerche @theemathas @durka @mbrubeck

### CODE REVIEW

**Comment by pietroalbini** [comment]
@craterbot run start=6cfc6033955dd2685dfa7baeec6f6bc3bfdfe2f1 end=6cfc6033955dd2685dfa7baeec6f6bc3bfdfe2f1+rustflags=-Dduplicate_associated_type_bindings mode=check-only

File: src/test/run-pass/traits/trait-alias-objects.rs [hunk 1]
```diff
@@ -21,7 +21,6 @@ pub fn main() {
     let b = Box::new(456) as Box<dyn Foo>;
     assert!(*b == 456);
 
-    // FIXME(alexreg): associated type should be gotten from trait alias definition
-    // let c: &dyn I32Iterator = &vec![123].into_iter();
-    // assert_eq!(c.next(), Some(123));
+    let c: &mut dyn I32Iterator<Item = u32> = &mut vec![123].into_iter();
```
Comment (oli-obk) [inline src/test/run-pass/traits/trait-alias-objects.rs]: Should the commented out code also be legal?

File: src/librustc_typeck/astconv.rs [hunk 2]
```diff
@@ -1021,16 +1012,26 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
...
-        // Use a BTreeSet to keep output in a more consistent order.
+        // Use a `BTreeSet` to keep output in a more consistent order.
         let mut associated_types = BTreeSet::default();
 
         for tr in traits::supertraits(tcx, principal) {
             associated_types.extend(tcx.associated_items(tr.def_id())
                 .filter(|item| item.kind == ty::AssociatedKind::Type)
                 .map(|item| item.def_id));
+
+            projection_bounds.extend(tcx.predicates_of(tr.def_id())
```
Comment (oli-obk) [inline src/librustc_typeck/astconv.rs]: The argument to `extend` warrants its own function (the same code also appears elsewhere)

File: src/librustc_typeck/astconv.rs [hunk 3]
```diff
@@ -947,14 +961,6 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
         )
     }
 
-    /// Transform a `PolyTraitRef` into a `PolyExistentialTraitRef` by
-    /// removing the dummy `Self` type (`TRAIT_OBJECT_DUMMY_SELF`).
-    fn trait_ref_to_existential(&self, trait_ref: ty::TraitRef<'tcx>)
```
Comment (oli-obk) [inline src/librustc_typeck/astconv.rs]: Instead of removing this function, you could extend it to include the entire erasure procedure

**Review by oli-obk — COMMENTED** [review]
First pass, will review in detail when back on a pc

**Comment by pietroalbini** [comment]
Uh, woops.

@craterbot abort

**Comment by pietroalbini** [comment]
Wrong commit hash...

@craterbot run start=24e66c28980442a48d9458f1a4f9b76cc722dc8a end=24e66c28980442a48d9458f1a4f9b76cc722dc8a+rustflags=-Dduplicate_associated_type_bindings mode=check-only

**Comment by pietroalbini** [comment]
@craterbot abort

**Comment by pietroalbini** [comment]
...forgot this is not my local branch...

@craterbot run start=master#24e66c28980442a48d9458f1a4f9b76cc722dc8a end=master#24e66c28980442a48d9458f1a4f9b76cc722dc8a+rustflags=-Dduplicate_associated_type_bindings mode=check-only

File: src/librustc_typeck/astconv.rs (hunk 2 above)
Comment (alexreg) [reply src/librustc_typeck/astconv.rs]: Actually I just forgot to remove it in one place I think heh.

File: src/test/run-pass/traits/trait-alias-objects.rs (hunk 1 above)
Comment (alexreg) [reply src/test/run-pass/traits/trait-alias-objects.rs]: Actually *only* the commented-out code should be legal. I was messing around and forgot to revert. Thanks for the catch.

File: src/librustc_typeck/astconv.rs [hunk 4]
```diff
@@ -711,14 +711,16 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
...
-    /// The given `trait_ref` must actually be trait.
+    /// The given trait ref must actually be a trait.
     pub(super) fn instantiate_poly_trait_ref_inner(&self,
         trait_ref: &hir::TraitRef,
         self_ty: Ty<'tcx>,
         poly_projections: &mut Vec<(ty::PolyProjectionPredicate<'tcx>, Span)>,
         speculative: bool)
         -> ty::PolyTraitRef<'tcx>
     {
+        let tcx = self.tcx();
```
Comment (scalexm) [inline src/librustc_typeck/astconv.rs]: (unused after you move the code below)

File: src/librustc_typeck/astconv.rs [hunk 5]
```diff
@@ -738,10 +740,22 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
             let predicate: Result<_, ErrorReported> =
                 self.ast_type_binding_to_poly_projection_predicate(
                     trait_ref.ref_id, poly_trait_ref, binding, speculative, &mut dup_bindings);
-            // ok to ignore Err because ErrorReported (see above)
+            // okay to ignore Err because of ErrorReported (see above)
             Some((predicate.ok()?, binding.span))
         }));
 
+        // Include all projections from associated type bindings of supertraits.
```
Comment (scalexm) [inline src/librustc_typeck/astconv.rs]: So we need to move the below code in `conv_object_ty_poly_trait_ref`

File: src/librustc_typeck/astconv.rs [hunk 6]
```diff
@@ -908,16 +922,25 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
...
+                    // let mut err = self.tcx().struct_span_lint_node(
+                    //     ::rustc::lint::builtin::DUPLICATE_ASSOCIATED_TYPE_BINDINGS,
+                    //     ref_id,
+                    //     binding.span,
+                    //     &format!("associated type binding `{}` specified more than once",
+                    //              binding.item_name)
+                    // );
+                    // err.span_label(binding.span, "used more than once");
+                    // err.span_label(*prev_span, format!("first use of `{}`", binding.item_name));
+                    // err.emit();
```
Comment (scalexm) [inline src/librustc_typeck/astconv.rs]: (careful to remove the commented out code)

File: src/librustc_typeck/astconv.rs [hunk 7]
```diff
@@ -934,6 +957,14 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
...
     }
 
+    /// Transform a `PolyTraitRef` into a `PolyExistentialTraitRef` by
+    /// removing the dummy `Self` type (`TRAIT_OBJECT_DUMMY_SELF`).
+    fn trait_ref_to_existential(&self, trait_ref: ty::TraitRef<'tcx>)
+                                -> ty::ExistentialTraitRef<'tcx> {
+        assert_eq!(trait_ref.self_ty().sty, TRAIT_OBJECT_DUMMY_SELF);
+        ty::ExistentialTraitRef::erase_self_ty(self.tcx(), trait_ref)
+    }
+
```
Comment (scalexm) [inline src/librustc_typeck/astconv.rs]: could you maybe keep the former function and use it again in `conv_object_ty_poly_trait_ref`, so that we have a cleaner diff?

File: src/librustc_typeck/astconv.rs [hunk 8]
```diff
@@ -1021,7 +1029,7 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx>+'o {
             return tcx.types.err;
         }
 
-        // Use a BTreeSet to keep output in a more consistent order.
+        // Use a `BTreeSet` to keep output in a more consistent order.
         let mut associated_types = BTreeSet::default();
 
         for tr in traits::supertraits(tcx, principal) {
```
Comment (scalexm) [inline src/librustc_typeck/astconv.rs]: Ok so I would advise merging the code which extends `projection_bounds` with this loop, something like:
```rust
for predicate in traits::elaborate_trait_ref(tcx, principal).into_iter() {
    match predicate {
        ty::TraitPredicate(tr) => {
            associated_types.extend(tcx.associated_items(tr.def_id())
                .filter(|item| item.kind == ty::AssociatedKind::Type)
                .map(|item| item.def_id));
        }
        ty::ProjectionPredicate(projection) => projection_bounds.push((projection, DUMMY_SP)),
        _ => continue,
    }
}
```
also, turns out we don't need any span information in the end, so `DUMMY_SP` is fine and we don't need to tweak `elaborate_trait_ref`.

File: src/test/ui/error-codes/E0719-trait-alias-object.rs [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![feature(trait_alias)]
+
+trait I32Iterator = Iterator<Item = i32>;
+
+fn main() {
+    let _: &I32Iterator<Item = u32>; //~ ERROR E0719
```
Comment (scalexm) [inline src/test/ui/error-codes/E0719-trait-alias-object.rs]: This test should indeed trigger an error, but rather just the one about type inference as we discussed.

File: src/test/ui/error-codes/E0719-trait-alias.rs [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+#![feature(trait_alias)]
+
+trait I32Iterator = Iterator<Item = i32>;
+trait I32Iterator2 = I32Iterator<Item = i32>; //~ ERROR E0719
```
Comment (scalexm) [inline src/test/ui/error-codes/E0719-trait-alias.rs]: This one and the one below shouldn't be treated as errors (at least for now) as we discussed.

**Review by scalexm — CHANGES_REQUESTED** [review]
A summary of what we discussed on Zulip. Two additional items:
* we'd need a test which shows off the "transitive" elaboration, e.g.:
```rust
trait Foo: Iterator<Item = i32> { }
trait Bar: Foo { }

fn main {
    let x: &dyn Bar;
}
```
* maybe clean the commit history

**Comment by nikomatsakis** [comment]
Seems like @scalexm is on this? =)

**Review by scalexm — APPROVED** [review]
