### PR TITLE
Fix unreachable coverage generation for inlined functions

### LINKED ISSUE #98833: Recent nightly started ICEing with "No counters provided the source_hash for used function"
This can be seen here: https://github.com/pyca/cryptography/runs/7165695219?check_suite_focus=true

```
Running `rustc --crate-name cryptography_rust --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C lto=thin --crate-type cdylib -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="extension-module"' -C metadata=34bb19b331b20af2 --out-dir /home/runner/work/cryptography/cryptography/src/rust/target/release/deps -L dependency=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps --extern asn1=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libasn1-5b30914c3eca7b28.rlib --extern chrono=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libchrono-ffc9d6801354fd45.rlib --extern once_cell=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libonce_cell-0e0945728073c72b.rlib --extern ouroboros=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libouroboros-5e1a3c513f27c586.rlib --extern pem=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libpem-6f7633cd9970b696.rlib --extern pyo3=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libpyo3-56560276294129fc.rlib -Cinstrument-coverage`
  thread 'rustc' panicked at 'No counters provided the source_hash for used function: Instance { def: Item(WithOptConstParam { did: DefId(42:58 ~ once_cell[2993]::imp::{impl#4}::is_initialized), const_param_did: None }), substs: [asn1::Tlv] }', compiler/rustc_codegen_ssa/src/coverageinfo/map.rs:156:9
  stack backtrace:
     0:     0x7f3d426e3b20 - std::backtrace_rs::backtrace::libunwind::trace::h419808c895a1be3b
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     1:     0x7f3d426e3b20 - std::backtrace_rs::backtrace::trace_unsynchronized::h4cd640051eb1546f
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x7f3d426e3b20 - std::sys_common::backtrace::_print_fmt::h6a643b487717d871
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x7f3d426e3b20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h84bab1c2a632e967
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x7f3d4273c85c - core::fmt::write::h41252a77742ac576
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/fmt/mod.rs:1198:17
     5:     0x7f3d426d53c5 - std::io::Write::write_fmt::h68f35cff36a534dd
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/io/mod.rs:1672:15
     6:     0x7f3d426e6711 - std::sys_common::backtrace::_print::h82f0b1ac2501b6af
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x7f3d426e6711 - std::sys_common::backtrace::print::h3dc7f0e84685b9ba
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x7f3d426e6711 - std::panicking::default_hook::{{closure}}::h6ace3fe16ec6f7aa
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:295:22
     9:     0x7f3d426e63e3 - std::panicking::default_hook::h77c1c7afb621e87c
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:314:9
    10:     0x7f3d42f02824 - rustc_driver[e83335c4a38137f8]::DEFAULT_HOOK::{closure#0}::{closure#0}
    11:     0x7f3d426e6ee6 - std::panicking::rust_panic_with_hook::h4cc32db16e14054a
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:702:17
    12:     0x7f3d426e6d37 - std::panicking::begin_panic_handler::{{closure}}::h402861fe76edfc4d
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:588:13
    13:     0x7f3d426e3ff4 - std::sys_common::backtrace::__rust_end_short_backtrace::he555a3759268da10
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:138:18
    14:     0x7f3d426e6a62 - rust_begin_unwind
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:584:5
    15:     0x7f3d426ab8e3 - core::panicking::panic_fmt::hd3841d7ec8a5a967
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:142:14
    16:     0x7f3d43a09ced - <rustc_codegen_ssa[8f83f5a95e7fa903]::coverageinfo::map::FunctionCoverage>::get_expressions_and_counter_regions
    17:     0x7f3d43029b5e - rustc_codegen_llvm[ddaab1b683620c95]::coverageinfo::mapgen::finalize
    18:     0x7f3d44291216 - rustc_codegen_llvm[ddaab1b683620c95]::base::compile_codegen_unit::module_codegen
    19:     0x7f3d450cc586 - <rustc_query_system[c868fe53e983a2f2]::dep_graph::graph::DepGraph<rustc_middle[a37307bbdd285edd]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a37307bbdd285edd]::ty::context::TyCtxt, rustc_span[550c183cd1c0caaa]::symbol::Symbol, rustc_codegen_ssa[8f83f5a95e7fa903]::ModuleCodegen<rustc_codegen_llvm[ddaab1b683620c95]::ModuleLlvm>>
    20:     0x7f3d450fdcf9 - rustc_codegen_llvm[ddaab1b683620c95]::base::compile_codegen_unit
    21:     0x7f3d450cf719 - rustc_codegen_ssa[8f83f5a95e7fa903]::base::codegen_crate::<rustc_codegen_llvm[ddaab1b683620c95]::LlvmCodegenBackend>
    22:     0x7f3d4512a3ea - <rustc_codegen_llvm[ddaab1b683620c95]::LlvmCodegenBackend as rustc_codegen_ssa[8f83f5a95e7fa903]::traits::backend::CodegenBackend>::codegen_crate
    23:     0x7f3d45098727 - <rustc_session[16e8265f3bee680e]::session::Session>::time::<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_interface[edbb2596f0660065]::passes::start_codegen::{closure#0}>
    24:     0x7f3d45085d40 - <rustc_interface[edbb2596f0660065]::passes::QueryContext>::enter::<<rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[303bee78761e0753]::result::Result<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_errors[cf96977[925](https://github.com/pyca/cryptography/runs/7165695219?check_suite_focus=true#step:9:926)b9f0c]::ErrorGuaranteed>>
    25:     0x7f3d4508fa23 - <rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen
    26:     0x7f3d450518e1 - <rustc_interface[edbb2596f0660065]::interface::Compiler>::enter::<rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}::{closure#2}, core[303bee78761e0753]::result::Result<core[303bee78761e0753]::option::Option<rustc_interface[edbb2596f0660065]::queries::Linker>, rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
    27:     0x7f3d4504dab0 - rustc_span[550c183cd1c0caaa]::with_source_map::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#1}>
    28:     0x7f3d450680f2 - rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>
    29:     0x7f3d4504d2b2 - <scoped_tls[c1a1588d7c68db11]::ScopedKey<rustc_span[550c183cd1c0caaa]::SessionGlobals>>::set::<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
    30:     0x7f3d4504ffcf - std[a38b499b13c80ab0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
    31:     0x7f3d45068539 - <<std[a38b499b13c80ab0]::thread::Builder>::spawn_unchecked_<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#1} as core[303bee78761e0753]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
    32:     0x7f3d426f0843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6cafef397152c3f0
                                 at /rustc/f2d93[935](https://github.com/pyca/cryptography/runs/7165695219?check_suite_focus=true#step:9:936)ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1951:9
    33:     0x7f3d426f0843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0308246411b63a3b
                                 at /rustc/f2d[939](https://github.com/pyca/cryptography/runs/7165695219?check_suite_focus=true#step:9:940)35ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1[951](https://github.com/pyca/cryptography/runs/7165695219?check_suite_focus=true#step:9:952):9
    34:     0x7f3d426f0843 - std::sys::unix::thread::Thread::new::thread_start::hd2e6d604897dcfa7
                                 at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys/unix/thread.rs:108:17
    35:     0x7f3d42608609 - start_thread
    36:     0x7f3d4252b133 - clone
    37:                0x0 - <unknown>
  error: internal compiler error: unexpected panic
  note: the compiler unexpectedly panicked. this is a bug.
  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
  note: rustc 1.64.0-nightly (f2d93935f 2022-07-02) running on x86_64-unknown-linux-gnu
  note: compiler flags: --crate-type cdylib -C opt-level=3 -C lto=thin --crate-type cdylib -C overflow-checks=on -C instrument-coverage
  note: some of the compiler flags provided by cargo are hidden
```

To reproduce:

```
$ git clone https://github.com/pyca/cryptography
$ cd cryptography
# Apply the change from https://github.com/pyca/cryptography/pull/7387
$ vim tox.ini
$ RUSTUP_TOOLCHAIN=nightly RUSTFLAGS="-Cinstrument-coverage" tox -e rust -vvv
```

### PR DESCRIPTION
**Pull request by tmiasko**
To generate a function coverage we need at least one coverage counter,
so a coverage from unreachable blocks is retained only when some live
counters remain.

The previous implementation incorrectly retained unreachable coverage,
because it didn't account for the fact that those live counters can
belong to another function due to inlining.

Fixes #98833.

### CODE REVIEW

**Comment by alex** [comment]
Thank you for diving into this -- sorry my test case wasn't especially reduced!

File: compiler/rustc_middle/src/mir/mod.rs [hunk 1]
```diff
@@ -375,6 +375,20 @@ impl<'tcx> Body<'tcx> {
         (&mut self.basic_blocks, &mut self.local_decls)
     }
 
+    #[inline]
+    pub fn basic_blocks_and_source_scopes_mut(
```
Comment (tmiasko) [inline compiler/rustc_middle/src/mir/mod.rs:379]: I wasn't particularly happy to introduce yet another variant of `basic_blocks_and_...`, so I opened #98930 that would remove a need for it.

**Comment by gshep** [comment]
Hi! Any update on this?

**Comment by alex** [comment]
It's awaiting a review.

File: compiler/rustc_mir_transform/src/simplify.rs [hunk 2]
```diff
@@ -28,6 +28,7 @@
 //! return.
 
 use crate::MirPass;
+use rustc_data_structures::stable_set::FxHashSet;
```
Comment (wesleywiser) [inline compiler/rustc_mir_transform/src/simplify.rs:31]:
```suggestion
use rustc_data_structures::fx::FxHashSet;
```

Changed in #99058

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @tmiasko! 

@bors r+
