### PR TITLE
Do not reuse post LTO products when exports change

### LINKED ISSUE #69798: cdylib link error after TLS unused -> used transition
From nightly-2020-02-28 (nightly-2020-02-27 was fine), I get link errors if I compile a cdylib with a thread local that isn't used, then compile again after referencing the thread local.

To reproduce, create a.rs:

```rust
pub struct Foo {}
impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping Foo");
    }
}
#[no_mangle]
pub extern "C" fn run() {
    thread_local! { pub static FOO : Foo = Foo { } ; }
    //FOO.with(|_f| ())
}
```

Then run:

```sh
rustc a.rs --crate-type cdylib --emit=dep-info,link -C opt-level=2 --out-dir target -C incremental=target/incremental
```

Uncomment the commented line and rerun the above command.

This produces the following link error:

```
1k5ednsjh2ku99ix:(.text._ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h998faaa5ce3b2835E.llvm.11804660923702021477+0x3a): undefined reference to `anon.043848776374366c7b657cba74aa2e83.1.llvm.9876575881142733961'
/usr/bin/ld: target/lib.1k5ednsjh2ku99ix.rcgu.o: relocation R_X86_64_PC32 against undefined hidden symbol `anon.043848776374366c7b657cba74aa2e83.1.llvm.9876575881142733961' can not be used when making a shared object
```

It's possible however that the underlying bug is actually older though, since at opt-level=1, I get link errors from 1.32.0 onwards (1.31.0 was fine). In that case, the Drop implementation isn't needed.

```rust
pub struct Foo {}
#[no_mangle]
pub extern "C" fn run() {
    thread_local! { pub static FOO : Foo = Foo { } ; }
    //FOO.with(|_f| ())
}
```

```sh
rustc a.rs --crate-type cdylib --emit=dep-info,link -C opt-level=1 --out-dir target -C incremental=target/incremental
```

Linking fails with: `undefined reference to 'core::ptr::drop_in_place'`

The exact symbol that's reported varies.

Versions:
rustc 1.43.0-nightly (2890b37b8 2020-03-06)
cc (Debian 9.2.1-16) 9.2.1 20191030
GNU ld (GNU Binutils for Debian) 2.33.1

### PR DESCRIPTION
**Pull request by pnkfelix**
Do not reuse post lto products when exports change

Generalizes code from PR #67020, which handled case when imports change.

Fix #69798

### CODE REVIEW

**Comment by pnkfelix** [comment]
@bors rollup=never

This may affect performance, especially of incremental compilations.

**Comment by pnkfelix** [comment]
nominating for beta backport; this bug is old, but it was *exposed* by a recent change (PR #67332), which has not made it to stable yet.

**Comment by pnkfelix** [comment]
I think [both](https://internals.rust-lang.org/t/stepping-away-from-the-rust-project/11971/9) @michaelwoerister [and](https://internals.rust-lang.org/t/scaling-back-my-involvement-in-rust/11754) @alexcrichton have scalred back their involvement with the project.

I'll try r? @nagisa or @eddyb for now...

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
The symmetry here makes sense, r=me.

File: src/librustc_codegen_llvm/back/lto.rs [hunk 1]
```diff
@@ -885,13 +894,19 @@ pub unsafe fn optimize_thin_module(
 pub struct ThinLTOImports {
```
Comment (nagisa) [inline src/librustc_codegen_llvm/back/lto.rs:894]: This name is not ideal anymore, since it also contains exports.

Same applies to the `{curr,prev}_import_map` variable name in these lines above:

```rust
//...
                let curr_imports = curr_import_map.modules_imported_by(module_name);
                let prev_exports = prev_import_map.modules_exported_by(module_name); 
//...
```

I had to stare for good couple mins at them to notice that these are not just duplicated lines and are _ex_ not _im_.

**Review by nagisa — APPROVED** [review]
r=me on implementation sans the struct/variable names.

File: src/librustc_codegen_llvm/back/lto.rs [hunk 2]
```diff
@@ -517,11 +517,20 @@ fn thin_lto(
 
                 let prev_imports = prev_import_map.modules_imported_by(module_name);
                 let curr_imports = curr_import_map.modules_imported_by(module_name);
+                let prev_exports = prev_import_map.modules_exported_by(module_name);
+                let curr_exports = curr_import_map.modules_exported_by(module_name);
                 let imports_all_green = curr_imports
                     .iter()
                     .all(|imported_module| green_modules.contains_key(imported_module));
+                let exports_all_green = curr_exports
```
Comment (Aaron1011) [inline src/librustc_codegen_llvm/back/lto.rs:525]: Could you add a comment here linking to https://github.com/rust-lang/rust/issues/69798? When I was investigating the issue, it wasn't obvious to me that the *exports* of a module could affect its codegen.

File: src/librustc_codegen_llvm/back/lto.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs:894]: fair enough, let me see what I can do to address that.

File: src/librustc_codegen_llvm/back/lto.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_codegen_llvm/back/lto.rs:525]: will do!

**Comment by pnkfelix** [comment]
> Queued [c8085c9](https://github.com/rust-lang/rust/commit/c8085c9fa29609558b4745fc37c7a14c335e0ec3) with parent [edc0258](https://github.com/rust-lang/rust/commit/edc02580e4e80476ac1ded2cc1008eaf8b8400e6), future [comparison URL](https://perf.rust-lang.org/compare.html?start=edc02580e4e80476ac1ded2cc1008eaf8b8400e6&end=c8085c9fa29609558b4745fc37c7a14c335e0ec3).

Wow, [these results](https://perf.rust-lang.org/compare.html?start=edc02580e4e80476ac1ded2cc1008eaf8b8400e6&end=c8085c9fa29609558b4745fc37c7a14c335e0ec3) seem so bad that I'm having a hard time believing them to be true...

image

**Comment by eddyb** [comment]
Is that because `println!` introduces a `static`? Or is that no longer the case, I can't remember.

**Comment by eddyb** [comment]
Post rust-lang/rustc-perf#645 retry:
@bors try @rust-timer queue

**Comment by pnkfelix** [comment]
Discussed in todays T-compiler [weekly meeting](https://zulip-archive.rust-lang.org/131828tcompiler/71793weeklymeeting2020041654818.html#194309307). There was general consensus that we *should* look into the performance issue here, but that we were also willing to accept the performance hit in exchange for fixing the nasty link time bug.

Marking as accepted for beta-backport.

**Comment by pnkfelix** [comment]
> Is that because `println!` introduces a `static`? Or is that no longer the case, I can't remember.

Well one of the cases, namely this:


patched incremental: is valid cap letter | 1,966,458,429.00 | 8,424,369,206.00 | 328.4%
-- | -- | -- | --


 is just [this patch](https://github.com/rust-lang/rustc-perf/blob/master/collector/benchmarks/regex/1-is-valid-cap-letter.patch):

```diff
diff --git a/src/expand.rs b/src/expand.rs
index 9bea703..3b6ae94 100644
--- a/src/expand.rs
+++ b/src/expand.rs
@@ -84,6 +84,7 @@ fn find_cap_ref(mut replacement: &[u8]) -> Option<CaptureRef> {
 }

 fn is_valid_cap_letter(b: &u8) -> bool {
+    { }
     match *b {
         b'0' ... b'9' | b'a' ... b'z' | b'A' ... b'Z' | b'_' => true,
         _ => false,
```

**Comment by pnkfelix** [comment]
I'm going to land this as is for now, and look into the performance regression as a follow-up work item.

**Comment by pnkfelix** [comment]
@bors p=2

(this gets slightly elevated priority because we want to backport it in time for next week's release, and I *really* dislike backporting things that have not landed in nightly. It remains rollup=never due to potential for performance impact.)

**Comment by Dylan-DPC** [comment]
@bors retry 

(yielding this for a rollup, will run this pr after that, when i'm asleep so that there is no need to monitor the queue :P )

**Comment by eddyb** [comment]
@rust-timer build 4909ccc0a8d5affc76bd6e900e76f9a46d0e3e9e
