### PR TITLE
Suggest async {} for async || {}

### LINKED ISSUE #76011: Suggest `async {}` for `async || {}`
This code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=988c3dd515555a1e28500cb19ca7d303)):
```rust
fn main() {
    let my_future = async || {
        1
    };
}
```
prints out
```
error[E0658]: async closures are unstable
 --> src/main.rs:2:21
  |
2 |     let my_future = async || {
  |                     ^^^^^
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information

error: aborting due to previous error
```
This is pretty unhelpful for beginners - normally this happens when they try to use `await` in a closure, which tells them they need async:
```
error[E0728]: `await` is only allowed inside `async` functions and blocks
 --> src/main.rs:3:9
  |
2 |     let my_future = || {
  |                     -- this is not `async`
3 |         1.await
  |         ^^^^^^^ only allowed inside `async` functions and blocks
```
But when they do they get an error about async being unstable, which they have no idea how to solve. The fix is to remove the pipe symbols:
```
async { }
```
However, this requires knowledge that async blocks desugar internally into closures, which is not at all clear from the syntax. It would be better for the compiler to suggest it:
```
error[E0658]: async closures are unstable
 --> src/main.rs:2:21
  |
2 |     let my_future = async || {
  |                     ^^^^^^^^^^ help: to use an async block, remove the `||`: `async {`
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information
```

### PR DESCRIPTION
**Pull request by rokob**
Fixes #76011

This adds support for adding help diagnostics to the feature gating checks and
then uses it for the async_closure gate to add the extra bit of help
information as described in the issue.

### CODE REVIEW

**Comment by estebank** [comment]
Can we add a test?

File: compiler/rustc_ast_passes/src/feature_gate.rs [hunk 1]
```diff
@@ -14,6 +14,17 @@ use rustc_span::Span;
...
 
 macro_rules! gate_feature_fn {
+    ($visitor: expr, $has_feature: expr, $span: expr, $name: expr, $explain: expr, $help: expr) => {{
+        let (visitor, has_feature, span, name, explain, help) =
+            (&*$visitor, $has_feature, $span, $name, $explain, $help);
+        let has_feature: bool = has_feature(visitor.features);
+        debug!("gate_feature(feature = {:?}, span = {:?}); has? {}", name, span, has_feature);
+        if !has_feature && !span.allows_unstable($name) {
+            feature_err_issue(&visitor.sess.parse_sess, name, span, GateIssue::Language, explain)
+                .span_help(span, help)
```
Comment (estebank) [inline compiler/rustc_ast_passes/src/feature_gate.rs:24]: Because we have a single span, I think this should be a bare `help` call (without a span) so the output isn't too verbose/redundant. I would _not_ close #76011, as that is asking for a structured suggestion, which we might be able to provide in the future (but this current change is a great mitigation).

**Comment by rokob** [comment]
I updated the  src/test/ui/async-await/feature-async-closure UI test. I also made a change to  compiler/rustc_parse/src/parser/expr.rs because otherwise this help would show up in this test src/test/ui/parser/block-no-opening-brace.

I can backout that change if you want and instead have this help show up in that case as well. But looking at that example, it didn't seem right to me that this code:

```
fn f5() {
    async
        let x = 0;
}
```

would produce an error about async closures being unstable. You don't know that this is trying to be a closure, it could very well have been an async block which is not unstable. The help message I am adding makes this part even more confusing because it suggests removing the || and replacing it with a { but there is no ||. I think moving the feature gate until after the parsing of the rest of the closure has no semantic impact but makes more sense as you shouldn't assume you have a closure if you don't have |, or ||, or {.

**Comment by jyn514** [comment]
ping @estebank

**Comment by jyn514** [comment]
ping @estebank - is there a better reviewer for this?

**Comment by camelid** [comment]
I think estebank is catching up on reviews now.

**Comment by estebank** [comment]
@bors r+

Noticed the following output

```
error: expected one of `move`, `|`, or `||`, found keyword `let`
  --> $DIR/block-no-opening-brace.rs:30:9
   |
LL |     async
   |          - expected one of `move`, `|`, or `||`
LL |         let x = 0;
   |         ^^^ unexpected token
```

should also include `{` as an expected token, but that's independent of this.
