### PR TITLE
Always inline functions signatures containing `f16` or `f128`

### LINKED ISSUE #133035: LLVM ERROR about f128 on AIX and SPARC32 when building core without optimization
### Code

I tried this code:

```rust
#![no_std]
// empty
```

With `cargo build -Z build-std=core --target powerpc64-ibm-aix`:

```
rustc-LLVM ERROR: f128 is unimplemented on AIX.
error: could not compile `core` (lib)
```

With `cargo build -Z build-std=core --target sparc-unknown-none-elf`:

```
rustc-LLVM ERROR: SPARCv8 does not handle f128 in calls; pass indirectly
error: could not compile `core` (lib)
```

I expected to see this happen: no error

I suspect the same problem exists with the other targets listed here: https://github.com/rust-lang/compiler-builtins/blob/a09218f1c4d23ffbd97d68f0fefb5feed2469dc5/configure.rs#L82-L91

Workaround: Passing `--release` flag resolves error.

### Version it worked on

It most recently worked on: nightly-2024-11-13

### Version with regression

nightly-2024-11-14

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (8adb4b30f 2024-11-13)
binary: rustc
commit-hash: 8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c
commit-date: 2024-11-13
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.3
```

@rustbot label +regression-from-stable-to-nightly -regression-untriaged

### PR DESCRIPTION
**Pull request by tgross35**
There are a handful of tier 2 and tier 3 targets that cause a LLVM crash or linker error when generating code that contains `f16` or `f128`. The cranelift backend also does not support these types. To work around this, every function in `std` or `core` that contains these types must be marked `#[inline]` in order to avoid sending any code to the backend unless specifically requested.

However, this is inconvenient and easy to forget. Introduce a check for these types in the frontend that automatically inlines any function signatures that take or return `f16` or `f128`.

Note that this is not a perfect fix because it does not account for the types being passed by reference or as members of aggregate types, but this is sufficient for what is currently needed in the standard library.

Fixes: https://github.com/rust-lang/rust/issues/133035
Closes: https://github.com/rust-lang/rust/pull/133037

### CODE REVIEW

**Comment by tgross35** [comment]
I'm not sure what I am missing here - testing by setting `#[inline(always)]` the codegen tests seem to emit code (maybe a compiletest option). Aside from that, I don't think generics or traits are handled at this point.

r? @saethlin, I could use a bit of help here

**Comment by saethlin** [comment]
You're getting code emitted because the functions are `#[no_mangle]`, which is the first thing that `cross_crate_inlinable` checks for. `contains_extern_indicator` is perhaps poorly named.

You might also run into https://github.com/rust-lang/rust/blob/c82e0dff84f922274c3060f09b5ae78d5dbf5c49/compiler/rustc_middle/src/mir/mono.rs#L107-L113 after fixing that.

File: compiler/rustc_mir_transform/src/cross_crate_inline.rs [hunk 1]
```diff
@@ -50,6 +50,16 @@ fn cross_crate_inlinable(tcx: TyCtxt<'_>, def_id: LocalDefId) -> bool {
         _ => {}
     }
 
+    let sig = tcx.fn_sig(def_id).instantiate_identity();
+    for ty in sig.inputs().skip_binder().iter().chain(std::iter::once(&sig.output().skip_binder()))
+    {
+        // FIXME(f16_f128): in order to avoid crashes building `core`, always inline to skip
+        // codegen if the function is not used.
```
Comment (RalfJung) [inline compiler/rustc_mir_transform/src/cross_crate_inline.rs:57]: if you move this down after `let mir`, you can just iterate over `mir.args_iter()` instead of having to call `fn_sig`

File: tests/codegen/float/f16-f128-inline.rs [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+#![crate_type = "lib"]
+#![feature(f128)]
+#![feature(f16)]
+
+/* Check for direct arguments and return types */
+
+pub fn f16_arg(_a: f16) {
+    // CHECK-NOT: f16_arg
+    todo!()
```
Comment (RalfJung) [inline tests/codegen/float/f16-f128-inline.rs:11]: Are you sure the automatic inlining heuristics wouldn't anyway already mark these functions as inlineable? Might be worth setting cross_crate_inline_threshold to 0 to be sure that doesn't mask the test.

File: compiler/rustc_mir_transform/src/cross_crate_inline.rs (hunk 1 above)
Comment (tgross35) [reply compiler/rustc_mir_transform/src/cross_crate_inline.rs:57]: I think this would require moving `let mir` above the checks against `opts.incremental`, `OptLevel::No`, and `threashold` to avoid hitting a `return false` before we check for the types. Would this wind up with a perf impact since we don't generate mir here in these cases?

Comment (RalfJung) [reply compiler/rustc_mir_transform/src/cross_crate_inline.rs:57]: Hm, I thought having this check so far down would be fine. But maybe not.

File: tests/codegen/float/f16-f128-inline.rs (hunk 2 above)
Comment (tgross35) [reply tests/codegen/float/f16-f128-inline.rs:13]: I added a revision with `-Zcross-crate-inline-threshold=never -Zmir-opt-level=0 -Cno-prepopulate-passes`, is that reasonable?

**Comment by tgross35** [comment]
I need to unjunkify my commit history but as-is, this resolves the problem at https://github.com/rust-lang/rust/issues/133035.

File: tests/codegen/float/f16-f128-inline.rs (hunk 2 above)
Comment (saethlin) [reply tests/codegen/float/f16-f128-inline.rs:13]: No, you also need `-Copt-level=0`.

Comment (tgross35) [reply tests/codegen/float/f16-f128-inline.rs:13]: Oh yeah of course. Done, tests still pass.

Comment (saethlin) [reply tests/codegen/float/f16-f128-inline.rs:13]: `-Cno-prepopulate-passes` just disables LLVM optimizations, rustc changes its behavior in a few places based on the value of `opt-level`.

File: compiler/rustc_mir_transform/src/cross_crate_inline.rs (hunk 1 above)
Comment (saethlin) [reply compiler/rustc_mir_transform/src/cross_crate_inline.rs:57]: Since this is a (temporary, right?) hack, I'd rather the diff be small and localized than pretty. What you've written here is good.

Comment (tgross35) [reply compiler/rustc_mir_transform/src/cross_crate_inline.rs:57]: > (temporary, right?)

Yes please, I don't think we will be able to stabilize these types until LLVM at least doesn't crash on everything T2+.

**Comment by saethlin** [comment]
> Should this function be updated to emit a `LocalCopy` if `generate_cgu_internal_copies || /* contains f16/f128 */`? I think this relates to Ralf's comment.

After thinking about this I think I've convinced myself that no such change is required, because that code is only run after MirUsedCollector has determined that the Instance must be codegenned. The choice of `LocalCopy` or `GloballyShared` there only changes how we're going to codegen the instance, not whether we are going to.

**Comment by saethlin** [comment]
I've manually verified that
```
cargo +stage1 build -Zbuild-std=core --target=powerpc64-ibm-aix
cargo +stage1 build -Zbuild-std=core --target=arm64ec-pc-windows-msvc
```
Work on this PR, and not on nightly.

@bors r+

**Comment by uweigand** [comment]
After this PR, building on s390x is completely broken:

```
Building stage0 library artifacts (s390x-unknown-linux-gnu)
   Compiling core v0.0.0 (/home/uweigand/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/uweigand/rust/library/rustc-std-workspace-core)
   Compiling compiler_builtins v0.1.138
   Compiling libc v0.2.161
   Compiling alloc v0.0.0 (/home/uweigand/rust/library/alloc)
   Compiling cfg-if v1.0.0
   Compiling adler v1.0.2
rustc-LLVM ERROR: Cannot select: 0x3ff58190770: ch = store<(store (s16) into %ir.6), trunc to f16> 0x3ff580a4768, 0x3ff58190850, FrameIndex:i64<2>, undef:i64
  0x3ff58190850: f32,ch = CopyFromReg 0x3ff580a4768, Register:f32 %1
    0x3ff580bdff0: f32 = Register %1
  0x3ff581905b0: i64 = FrameIndex<2>
  0x3ff58190fc0: i64 = undef
In function: _ZN4core3f1621_$LT$impl$u20$f16$GT$5clamp8do_panic7runtime17ha09a9a0f7fcbf036E
```

It looks like the first of the two commits (pass by value) introduces the breakage.

**Comment by saethlin** [comment]
@uweigand Can you open a new issue for this? I'm quite surprised that s390x is broken because it is a tier 2 with host tools target.
