### PR TITLE
rustbuild: Fix MSBuild location of `llvm-config.exe`

### LINKED ISSUE #48749: Rustc no longer builds for msvc 17
It appears to be since this commit yesterday: https://github.com/rust-lang/rust/commit/d69b24805b5071e5ec9e62d2777a761723644144#diff-9a46b13a265be2ded97369dddf5037f5

@alexcrichton can you have a look at it?, discussing in IRC, it seems that changing the line 88 back from "build/bin" to only "bin" does the work.

### PR DESCRIPTION
**Pull request by alexcrichton**
For LLD integration the path to `llvm-config` needed to change to inside the
build directory itself (for whatever reason) but the build directory is
different on MSBuild than it is on `ninja` for MSVC builds, so the path to
`llvm-config.exe` was actually wrong and not working!

This commit removes the `Build::llvm_config` function in favor of the source of
truth, the `Llvm` build step itself. The build step was then updated to find the
right build directory for MSBuild as well as `ninja` for where `llvm-config.exe`
is located.

Closes #48749

### CODE REVIEW

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -162,7 +162,11 @@ pub fn std_cargo(build: &Build,
         // missing
         // We also only build the runtimes when --enable-sanitizers (or its
         // config.toml equivalent) is used
-        cargo.env("LLVM_CONFIG", build.llvm_config(target));
+        let llvm_config = build.ensure(native::Llvm {
+            target: build.config.build,
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs]: Shouldn't this be the target we're passing to std_cargo? Or is this some other llvm-config? Either way, it'd be good to comment on the build.config.build with why we're passing it, and not `target`.

It also looks like it's maybe worth making this `build.ensure(...)` call the body of the old `llvm_config` function and then just calling it so we avoid duplicating it. But that's probably a minor detail, up to you.

**Review by Mark-Simulacrum — CHANGES_REQUESTED** [review]
I think with the comment I'll consider this good to go.

File: src/bootstrap/compile.rs (hunk 1 above)
Comment (alexcrichton) [reply src/bootstrap/compile.rs]: Ah good point! I was hoping to keep the `ensure` here though to canonicalize the definition of where `llvm-config` comes from in one place (previously it was calculated in two places)

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Zoxc** [comment]
@bors p=1

Giving this a little boost so I can actually build rustc locally

**Comment by kennytm** [comment]
[`dist x86_64-apple-darwin`](https://api.travis-ci.org/v3/job/351299713/log.txt) failed, seems legit.

```
[01:08:50] Building stage2 std artifacts (x86_64-apple-darwin -> aarch64-apple-ios)
[01:08:50] Building LLVM for aarch64-apple-ios
[01:08:50] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "target `aarch64-apple-ios` is not configured as a host, only as a target"', libcore/result.rs:945:5
```

**Comment by pietroalbini** [comment]
macOS crashed with a sigsegv while building stage2 cargo.

@bors retry #48866
