### PR TITLE
rustc: Search all derives for inert attributes

### LINKED ISSUE #52219: #![feature(proc_macro)] breaks some custom derive attributes
Originally reported as https://github.com/rust-lang-nursery/rustfix/issues/126 this is reduced to:

```rust
// foo.rs
#![crate_type = "proc-macro"]

extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro_derive(Foo)]
pub fn foo(a: TokenStream) -> TokenStream {
    "".parse().unwrap()
}

#[proc_macro_derive(Bar, attributes(custom))]
pub fn bar(a: TokenStream) -> TokenStream {
    "".parse().unwrap()
}
```

```rust
// bar.rs
#![cfg_attr(broken, feature(proc_macro))]
#![crate_type = "lib"]

#[macro_use]
extern crate foo;

#[derive(Foo, Bar, Debug)]
#[custom = "test"]
pub enum A{
    B,
    C,
}
```

compiles with:

```
$ rustc +nightly foo.rs
$ rustc +nightly bar.rs -L .
$ rustc +nightly bar.rs -L . --cfg broken
error: cannot find attribute macro `custom` in this scope
 --> bar.rs:8:3
  |
8 | #[custom = "test"]
  |   ^^^^^^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes an apparent mistake in librustc_resolve where when the
`proc_macro` feature is enabled (or `rust_2018_preview`) the resolution of
custom attributes for custom derive was tweaked. Previously when an attribute
failed to resolve it was attempted to locate if there is a custom derive also in
scope which declares the attribute, but only the first custom derive directive
was search.

Instead this commit fixes the loop to search all custom derive invocations
looking for any which register the attribute in question.

Closes #52219

### CODE REVIEW

File: src/librustc_resolve/macros.rs [hunk 1]
```diff
@@ -412,7 +428,7 @@ impl<'a> Resolver<'a> {
                             attrs
                         });
                     }
-                    return Err(Determinacy::Undetermined);
```
Comment (petrochenkov) [inline src/librustc_resolve/macros.rs]: Hmm, I think the return was actually correct, but misplaced - we *can* return once we've found an inert attribute and processed it, we don't need to go through remaining traits and possibly repeat the process, so the return should go inside `if inert_attrs.contains(&attr_name) { ... }`

Comment (alexcrichton) [reply src/librustc_resolve/macros.rs]: Oh right yes indeed!

Comment (alexcrichton) [reply src/librustc_resolve/macros.rs]: should be updated now!
