### PR TITLE
Fix `Instance::resolve()` incorrectly returning specialized instances

### LINKED ISSUE #66901: Specialization does not work correctly during constant evaluation.
A crate using specialization I've been working on seems to have broken sometime between `nightly-2019-11-19` and `nightly-2019-11-20`. After a bit of debugging, it seems the issue is that specialization doesn't always work correctly in const contexts.

[This code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a22248608ba3b6ee06212a9496ed1644), for example, returns the following:

```
const_bool::<TypeA>: in default impl
const_bool::<TypeB>: in default impl
const_str::<TypeA>: in specialized impl
const_str::<TypeB>: in default impl
run_method::<TypeA>: in specialized impl
run_method::<TypeB>: in default impl
```

On earlier versions, this would have returned the following:

```
const_bool::<TypeA>: in specialized impl
const_bool::<TypeB>: in default impl
const_str::<TypeA>: in specialized impl
const_str::<TypeB>: in default impl
run_method::<TypeA>: in specialized impl
run_method::<TypeB>: in default impl
```

This bug does not happen when the `-Z mir-opt-level=0` flag is set, and it behaves the same as prior versions.

### PR DESCRIPTION
**Pull request by wesleywiser**
We only want to return specializations when `Reveal::All` is passed, not
when `Reveal::UserFacing` is. Resolving this fixes several issues with
the `ConstProp`, `SimplifyBranches`, and `Inline` MIR optimization
passes.

Fixes #66901

Rebased on top of #67631 

r? @oli-obk

### CODE REVIEW

File: src/test/ui/consts/trait_specialization.rs [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+#![feature(specialization)]
+
+trait Marker {}
+
+trait SpecializedTrait {
+    const CONST_BOOL: bool;
+    const CONST_STR: &'static str;
+    fn method() -> &'static str;
+}
+impl <T> SpecializedTrait for T {
```
Comment (oli-obk) [inline src/test/ui/consts/trait_specialization.rs]: Doesn't rustfmt trigger on this?

```suggestion
impl<T> SpecializedTrait for T {
```

File: src/test/ui/consts/trait_specialization.rs [hunk 2]
```diff
@@ -0,0 +1,64 @@
+// ignore-wasm32-bare which doesn't support `std::process:exit()`
+// run-pass
+
+// Tests that specialization does not cause optimizations running on polymorphic MIR to resolve
```
Comment (oli-obk) [inline src/test/ui/consts/trait_specialization.rs]: Don't you also need `// compile-flags: -Zmir-opt-level=3`?

File: src/test/ui/consts/trait_specialization.rs (hunk 1 above)
Comment (wesleywiser) [reply src/test/ui/consts/trait_specialization.rs]: Just ran the formatter

File: src/test/ui/consts/trait_specialization.rs (hunk 2 above)
Comment (wesleywiser) [reply src/test/ui/consts/trait_specialization.rs]: To trigger the inliner? No, it runs on `mir-opt-level=2`

File: src/test/mir-opt/inline/inline-specialization.rs [hunk 3]
```diff
@@ -0,0 +1,48 @@
+#![feature(specialization)]
+
+fn main() {
+    let x = <Vec::<()> as Foo>::bar();
```
Comment (oli-obk) [inline src/test/mir-opt/inline/inline-specialization.rs]: what exactly is this PR testing? Shouldn't this get inlined? If so, we're probably gonna need the same param env reveal_all change for inlining

File: src/test/ui/consts/trait_specialization.rs (hunk 2 above)
Comment (oli-obk) [reply src/test/ui/consts/trait_specialization.rs]: Ok, then `=2` :D, since ui tests don't run optimizations afaik

Comment (wesleywiser) [reply src/test/ui/consts/trait_specialization.rs]: Oh duh. I wrote this originally as a `mir-opt` test but it was going to be like 800 lines of output and I didn't think it was worth it.

File: src/test/mir-opt/inline/inline-specialization.rs (hunk 3 above)
Comment (wesleywiser) [reply src/test/mir-opt/inline/inline-specialization.rs]: I think I just wanted to show that the incorrect inlining wasn't happening. However, you're right it ideally would be getting inlined.

**Comment by anp** [comment]
@oli-obk I assume that closing https://github.com/rust-lang/rust/pull/67631 implies this should also fix the test failure I have in https://github.com/rust-lang/rust/pull/67137, but rebasing onto @wesleywiser's branch still yields a failure for me :(.

**Comment by wesleywiser** [comment]
Force pushed

**Comment by wesleywiser** [comment]
Hi @anp do you have the error details so I can look at them?

**Comment by anp** [comment]
It's the same error that [highfive reports](https://github.com/rust-lang/rust/pull/67137#issuecomment-569146210):

```
------------------------------------------
stderr:
------------------------------------------
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

warning: struct is never constructed: `PrintName`
  --> /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:10:8
   |
10 | struct PrintName<T>(T);
   |        ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated const is never used: `VOID`
  --> /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:13:5
   |
13 |     const VOID: ! = panic!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `no_codegen`
  --> /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:16:4
   |
16 | fn no_codegen<T>() {
   |    ^^^^^^^^^^

error: any use of this value will cause an error
  --> /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:13:21
   |
13 |     const VOID: ! = panic!();
   |     ----------------^^^^^^^^-
   |                     |
   |                     the evaluated program panicked at 'explicit panic', /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:13:21
   |
   = note: `#[deny(const_err)]` on by default
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0080]: erroneous constant used
  --> /usr/local/google/home/adamperry/c/rust/src/test/mir-opt/retain-never-const.rs:17:13
   |
17 |     let _ = PrintName::<T>::VOID;
   |             ^^^^^^^^^^^^^^^^^^^^ referenced constant has errors

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0080`.

------------------------------------------

failures:
    [mir-opt] mir-opt/retain-never-const.rs

test result: FAILED. 73 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by oli-obk** [comment]
I guess we still need my PR for backwards compatibility of @anp's PR. I'll reopen

**Comment by wesleywiser** [comment]
I have no idea why your PR would change that test's behavior but I wonder if we shouldn't have `#[warn(const_err)]` on that test.

**Comment by anp** [comment]
I think oli said at one point that it would be a breaking change to allow const prop to surface this error?

**Comment by oli-obk** [comment]
> error[E0080]: erroneous constant used

this is the problem, the use of the broken constant inside a never used function should not cause a hard error.

File: src/test/mir-opt/inline/inline-specialization.rs (hunk 3 above)
Comment (wesleywiser) [reply src/test/mir-opt/inline/inline-specialization.rs]: I've updated the inliner to do the same param env reveal_all change.

File: src/librustc/ty/instance.rs [hunk 4]
```diff
@@ -346,6 +346,25 @@ fn resolve_associated_item<'tcx>(
...
+            let resolved_item = tcx.associated_item(def_id);
+
+            // Since this is a trait item, we need to see if the item is either a trait default item
+            // or a specialization because we can't resolve those unless we can `Reveal::All`.
+            // NOTE: This should be kept in sync with the similar code in
+            // `rustc::traits::project::assemble_candidates_from_impls()`.
+            let eligible = if !resolved_item.defaultness.is_default() {
+                true
+            } else if param_env.reveal == traits::Reveal::All {
+                !trait_ref.needs_subst()
```
Comment (eddyb) [inline src/librustc/ty/instance.rs]: You might want an assert that `!trait_ref.needs_infer()`.

File: src/librustc_mir/transform/const_prop.rs [hunk 5]
```diff
@@ -293,13 +294,20 @@ impl<'mir, 'tcx> ConstPropagator<'mir, 'tcx> {
...
-        let param_env = tcx.param_env(def_id);
+        let substs = &InternalSubsts::identity_for_item(tcx, def_id);
+        let mut param_env = tcx.param_env(def_id);
+
+        // If we're evaluating inside a monomorphic function, then use `Reveal::All` because
+        // we want to see the same instances that codegen will see. This allows us to `resolve()`
+        // specializations.
+        if !substs.needs_subst() {
+            param_env = param_env.with_reveal_all();
+        }
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: I don't understand why this cares about monomorphic functions. `Reveal::All` is orthogonal to being monomorphic, and any assumption tying them together is a bug.

`Reveal::All` is "*literally* anything outside type-checking", and I'm not even sure `Reveal::UserFacing` should even exist, when it was first added we didn't have the polymorphic+specialization-aware `Reveal::All` (based on `needs_substs`) capability.

File: src/librustc_mir/transform/inline.rs [hunk 6]
```diff
@@ -66,7 +66,14 @@ impl Inliner<'tcx> {
...
 
-        let param_env = self.tcx.param_env(self.source.def_id());
+        let mut param_env = self.tcx.param_env(self.source.def_id());
+
+        let substs = &InternalSubsts::identity_for_item(self.tcx, self.source.def_id());
+
+        // For monomorphic functions, we can use `Reveal::All` to resolve specialized instances.
+        if !substs.needs_subst() {
+            param_env = param_env.with_reveal_all();
+        }
```
Comment (eddyb) [inline src/librustc_mir/transform/inline.rs]: Same here.
