### PR TITLE
Replace the global fulfillment cache with the evaluation cache

### LINKED ISSUE #39970: rustc panic
rustc asked me to file a bug report:

> error: internal compiler error: /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/infer/mod.rs:626: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { trait_ref: <std::vec::Vec<f32> as array::Array<'a, usize>>, item_name: Element(610) }, _)),depth=1),MismatchedProjectionTypes(RegionsInsufficientlyPolymorphic(BrNamed(CrateNum(0):DefIndex(1030), 'a(180), WontChange), '_#0r)))]` resolving bounds after type-checking
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> 
> thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc_errors/lib.rs:382
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Here's [a fragment of code](https://play.rust-lang.org/?gist=bd9babc03dbc57d51159eb35cc8e57c2&version=stable&backtrace=0) sufficient to trigger the bug. It's not minimal yet, sorry. The code might not be correct; I was kinda relying on the compiler to tell me. ;-)

> $ rustc --version --verbose
> rustc 1.15.1 (021bd294c 2017-02-08)
> binary: rustc
> commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
> commit-date: 2017-02-08
> host: x86_64-unknown-linux-gnu
> release: 1.15.1
> LLVM version: 3.9

I hope you can make something of this.

### LINKED ISSUE #42796: trait cache can be poisoned through an associated type
I was trying to root out the root cause of #39970 and I found this:

## Meta

```
rustc 1.20.0-nightly (445077963 2017-06-20)
```

## STR

```Rust
pub trait Mirror<Smoke> {
    type Image;
}

impl<T, Smoke> Mirror<Smoke> for T {
    type Image = T;
}

pub fn poison<S>(victim: String) where <String as Mirror<S>>::Image: Copy {
    loop { drop(victim); }
}

fn main() {
    let s = "Hello!".to_owned();
    let mut s_copy = s;
    s_copy.push_str("World!");
    "0wned!".to_owned();
    println!("{}", s);
}
```

## Expected result

Code does not compile, because it attempts to copy a string..

## Actual result

Code compiles, is UB, generally prints `0wned!`

## Explanation

The global fulfilled predicates cache (`GlobalFulfilledPredicates`) tries to cache "environment-independent" predicates. The idea is that if a predicate contains neither parameters nor inference variables, then whether it holds is unaffected by the parameter environment.

This property almost holds - because in the absence of inference variables, trait impl search is "predicative", its results are independent of the universe of types, and therefore can be transferred from a "maximal universe" where the type parameters can be assigned variables.

However, that argument isn't 100% correct. If predicates are *inconsistent*, then there can be no such "maximal universe", and so `String: Copy` might be implied by `<String as Mirror<T>>::Image: Copy`.

We can say that this would be "fixed by Chalk" (as of course, in the absence of "intelligent" caching, this is not a problem), but that assumes the implementation of Chalk would not make the same mistake. I *think* a good way to fix this would be to check global predicates in the empty environment directly - if the current environment is consistent that will return the correct result, and if it is inconsistent we already don't always care about any kind of stability (e.g. we occasionally "know" that `[T]` is never `Sized`, even if some predicate tries to claim so).

cc @nikomatsakis @aturon @RalfJung (are you interested in trait systems?)

### PR DESCRIPTION
**Pull request by arielb1**
This uses the new "Chalk" ParamEnv refactoring to check "global" predicates in an empty environment, which should be correct because global predicates aren't affected by a consistent environment.

Fixes #39970.
Fixes #42796.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/select.rs [hunk 1]
```diff
@@ -703,14 +702,25 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
...
+            let cycle = stack.iter().skip(1).take(rec_index+1);
+            let cycle = cycle.map(|stack| ty::Predicate::Trait(stack.obligation.predicate));
+            if self.coinductive_match(cycle) {
+                debug!("evaluate_stack({:?}) --> recursive, coinductive",
+                       stack.fresh_trait_ref);
+                return EvaluatedToOk;
+            } else {
+                debug!("evaluate_stack({:?}) --> recursive, inductive",
+                       stack.fresh_trait_ref);
+                return EvaluatedToErr;
```
Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: So we've been working through this logic in the context of chalk -- it turns out that error isn't really the *right* answer here. In particular, it can lead you to "overconfidence". The correct answer probably requires iteration (at least, that's what we're doing in chalk). Maybe might be tolerable for now, but may break stuff, I'm not sure. 

PR https://github.com/nikomatsakis/chalk/pull/47 by @scalexm outlines the chalk strategy, which is based on a technique called tabling. In short, you start out by saying error, but then -- if you find solutions -- you iterate again, and this time, on the cycle, you return the solution that you found. This may allow you to find a second solution, in which case you can report ambiguity (no unique solution).

This [example test](https://github.com/nikomatsakis/chalk/blob/master/src/solve/test.rs#L250-L270) is relevant -- on the first iteration, we encounter a cycle testing whether `exists<T> { T: Foo }` (that is, `S<T>: Foo` inquires whether `S<T>: Foo`), but we also encounter a solution -- `T = i32`. This then enables (on the second round) us to uncover that `S<i32>: Foo` is another solution. (Indeed, there are infinitely many, iirc.)

Comment (arielb1) [inline src/librustc/traits/select.rs]: The current logic [reports an overflow error in this case](https://github.com/rust-lang/rust/blob/master/src/librustc/traits/fulfill.rs#L321), which aborts compilation. Maybe it's better to do that here too?

Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: It seems like we return "OK" for the "evaluation" result, but abort in the fulfillment cx..? If we aborted in both, it might cause trouble? Maybe worth a try though.

Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: The other option is `EvaluatedToAmbiguity`.

**Comment by nikomatsakis** [comment]
@arielb1 sorry for delay, I promise a review soon. =)

**Comment by nikomatsakis** [comment]
r=me after rebase

**Comment by nikomatsakis** [comment]
@arielb1 I did the rebase locally because I wanted to check some experiments; just pushed it, hope you don't mind. =)
