### PR TITLE
fix the check for which expressions read never type

### LINKED ISSUE #149431: type ascription: stack overflow
### Code

```Rust
const ARRAY_REF: [!; 1] = todo!();
fn main() {
    type_ascribe!(ARRAY_REF[0], i32)
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.93.0-nightly (c86564c41 2025-11-27)
binary: rustc
commit-hash: c86564c412a5949088a53b665d8b9a47ec610a39
commit-date: 2025-11-27
host: x86_64-unknown-linux-gnu
release: 1.93.0-nightly
LLVM version: 21.1.5
```

### Error output

```
error[E0658]: use of unstable library feature `type_ascription`: placeholder syntax for type ascription
 --> code.rs:3:5
  |
3 |     type_ascribe!(ARRAY_REF[0], i32)
  |     ^^^^^^^^^^^^
  |
  = note: see issue #23416 <https://github.com/rust-lang/rust/issues/23416> for more information
  = help: add `#![feature(type_ascription)]` to the crate attributes to enable
  = note: this compiler was built on 2025-11-27; consider upgrading it if it is out of date

error[E0658]: the `!` type is experimental
 --> code.rs:1:19
  |
1 | const ARRAY_REF: [!; 1] = todo!();
  |                   ^
  |
  = note: see issue #35121 <https://github.com/rust-lang/rust/issues/35121> for more information
  = help: add `#![feature(never_type)]` to the crate attributes to enable
  = note: this compiler was built on 2025-11-27; consider upgrading it if it is out of date

error[E0080]: evaluation panicked: not yet implemented
 --> code.rs:1:27
  |
1 | const ARRAY_REF: [!; 1] = todo!();
  |                           ^^^^^^^ evaluation of `ARRAY_REF` failed here
  |
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: rustc interrupted by SIGSEGV, printing backtrace

/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x3ad574c) [0x7f7a54ad574c]
/usr/lib/libc.so.6(+0x3e540) [0x7f7a50c3e540]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(_RNvMs1_NtNtCshPD3nR7tEK4_12rustc_middle3hir3mapNtNtNtB9_2ty7context6TyCtxt15parent_hir_node+0x2b) [0x7f7a5629e7fd]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56030eb) [0x7f7a566030eb]

### cycle encountered after 4 frames with period 5
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
### recursed 50 times

/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]
/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x56032ee) [0x7f7a566032ee]

note: rustc unexpectedly overflowed its stack! this is a bug
note: maximum backtrace depth reached, frames may have been lost
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
[1]    4073700 segmentation fault  rustc code.rs
```

</p>
</details>

### LINKED ISSUE #149542: rustc crashes when trying to check if nested `type_ascription` constitutes a read of never
I tried this code:

```rust
#![feature(never_type)]
#![feature(type_ascription)]
use std::ptr;

fn main() { unsafe {
   let _ = type_ascribe!(type_ascribe!(*ptr::null(), !), _);
} }
```

I expected to see this happen: code compiles.

Instead, this happened: rustc stack overflows

### Meta

`rustc` version:
```
1.93.0-nightly (2025-12-01 1d60f9e070c1039b263e)
```

<details><summary>Backtrace</summary>
<p>

```
error: rustc interrupted by SIGSEGV, printing backtrace

/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x3acca3c)[0x7ed77a2cca3c]
/lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7ed776633330]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(_RNvMs1_NtNtCs4obKHf8g18q_12rustc_middle3hir3mapNtNtNtB9_2ty7context6TyCtxt15parent_hir_node+0x9)[0x7ed77be6601b]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edd1d)[0x7ed77bdedd1d]

### cycle encountered after 4 frames with period 5
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
### recursed 50 times

/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]
/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-d012d9d43742cddd.so(+0x55edf20)[0x7ed77bdedf20]

note: rustc unexpectedly overflowed its stack! this is a bug
note: maximum backtrace depth reached, frames may have been lost
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
error: could not compile `playground` (bin "playground")

Caused by:
  process didn't exit successfully: `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name playground --edition=2024 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=bdfad08d67a33166 -C extra-filename=-658c0fadac72774f --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern addr2line=/playground/target/debug/deps/libaddr2line-e50d38b3d86c7662.rlib --extern adler2=/playground/target/debug/deps/libadler2-1ec5103b4bfc71a8.rlib --extern ahash=/playground/target/debug/deps/libahash-631dbff5f40ff4f0.rlib --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-dca9c358048472ff.rlib --extern aligned=/playground/target/debug/deps/libaligned-be48101eb7dc7ce4.rlib --extern aligned_vec=/playground/target/debug/deps/libaligned_vec-d7a60db93c57fc85.rlib --extern alloc_no_stdlib=/playground/target/debug/deps/liballoc_no_stdlib-3d278c327d595575.rlib --extern alloc_stdlib=/playground/target/debug/deps/liballoc_stdlib-e8e19c8289978d83.rlib --extern allocator_api2=/playground/target/debug/deps/liballocator_api2-06602b85c92a05eb.rlib --extern ansi_term=/playground/target/debug/deps/libansi_term-8b066d1d8b60870b.rlib --extern anstream=/playground/target/debug/deps/libanstream-ee54e2f1b5459385.rlib --extern anstyle=/playground/target/debug/deps/libanstyle-b9b4bb1574cd33fb.rlib --extern anstyle_parse=/playground/target/debug/deps/libanstyle_parse-4391c3545e9d8226.rlib --extern anstyle_query=/playground/target/debug/deps/libanstyle_query-b77e1b335a923318.rlib --extern anyhow=/playground/target/debug/deps/libanyhow-6a5b67a42a323065.rlib --extern approx=/playground/target/debug/deps/libapprox-c07270e7cbd0eacc.rlib --extern arc_swap=/playground/target/debug/deps/libarc_swap-15171b01af3937ad.rlib --extern arg_enum_proc_macro=/playground/target/debug/deps/libarg_enum_proc_macro-af189ff29785f138.so --extern arrayvec=/playground/target/debug/deps/libarrayvec-0a83ca20b888b616.rlib --extern as_slice=/playground/target/debug/deps/libas_slice-3f57f0da9fcd0859.rlib --extern async_compression=/playground/target/debug/deps/libasync_compression-eeecc195d2e6f81f.rlib --extern async_trait=/playground/target/debug/deps/libasync_trait-918d744d3e19e592.so --extern atomic=/playground/target/debug/deps/libatomic-5dc53df5be76ec2b.rlib --extern atomic_waker=/playground/target/debug/deps/libatomic_waker-0cdb97624137bcfb.rlib --extern autocfg=/playground/target/debug/deps/libautocfg-c2458794153dfcca.rlib --extern av_scenechange=/playground/target/debug/deps/libav_scenechange-7f3edd35c866e63f.rlib --extern av1_grain=/playground/target/debug/deps/libav1_grain-3cc491f1ceb350b3.rlib --extern avif_serialize=/playground/target/debug/deps/libavif_serialize-e9f4cb6a3d28aa50.rlib --extern aws_lc_rs=/playground/target/debug/deps/libaws_lc_rs-22db64ba7acda19f.rlib --extern aws_lc_sys=/playground/target/debug/deps/libaws_lc_sys-617916c19d870037.rlib --extern backtrace=/playground/target/debug/deps/libbacktrace-4c354dc0a689d6ed.rlib --extern base64=/playground/target/debug/deps/libbase64-31a61120b61ae6dc.rlib --extern bit_set=/playground/target/debug/deps/libbit_set-ff02b9c967451bad.rlib --extern bit_vec=/playground/target/debug/deps/libbit_vec-6347e14da918bcf5.rlib --extern bit_field=/playground/target/debug/deps/libbit_field-4aaf625559c5b1f8.rlib --extern bitflags=/playground/target/debug/deps/libbitflags-99f1706d57d1528b.rlib --extern bitstream_io=/playground/target/debug/deps/libbitstream_io-bde31cf0ef48ce87.rlib --extern block_buffer_0_10_4=/playground/target/debug/deps/libblock_buffer-8d6ba7f8d32b3838.rlib --extern block_buffer=/playground/target/debug/deps/libblock_buffer-56271f662153606e.rlib --extern borsh=/playground/target/debug/deps/libborsh-6139d1fc1cf42585.rlib --extern brotli=/playground/target/debug/deps/libbrotli-861d29375a0cff19.rlib --extern brotli_decompressor=/playground/target/debug/deps/libbrotli_decompressor-0f23dd56d9a56a83.rlib --extern built=/playground/target/debug/deps/libbuilt-67f43f3bcad08ece.rlib --extern bumpalo=/playground/target/debug/deps/libbumpalo-3bb453c7d301d63a.rlib --extern bytemuck=/playground/target/debug/deps/libbytemuck-272e2966a853bdc9.rlib --extern bytemuck_derive=/playground/target/debug/deps/libbytemuck_derive-6cda4886b74222d7.so --extern byteorder=/playground/target/debug/deps/libbyteorder-f89bcde6f1e2352a.rlib --extern byteorder_lite=/playground/target/debug/deps/libbyteorder_lite-13db135683c331a4.rlib --extern bytes_0_4_12=/playground/target/debug/deps/libbytes-ec060d14a785ba1c.rlib --extern bytes=/playground/target/debug/deps/libbytes-da904f078bb4e94f.rlib --extern cc=/playground/target/debug/deps/libcc-8b8ae7da88dceffa.rlib --extern cfg_if=/playground/target/debug/deps/libcfg_if-69ea8bafce1e7420.rlib --extern cfg_aliases=/playground/target/debug/deps/libcfg_aliases-3f829bf49deda5a7.rlib --extern chrono=/playground/target/debug/deps/libchrono-bfce005f6f307ab7.rlib --extern clap=/playground/target/debug/deps/libclap-be7104f8ca188d72.rlib --extern clap_builder=/playground/target/debug/deps/libclap_builder-e11c387c314de5c3.rlib --extern clap_derive=/playground/target/debug/deps/libclap_derive-1391d94fb11aa0ef.so --extern clap_lex=/playground/target/debug/deps/libclap_lex-122ce265b28cb7a8.rlib --extern cmake=/playground/target/debug/deps/libcmake-ab350de02a29ddb0.rlib --extern color_quant=/playground/target/debug/deps/libcolor_quant-b37e32f0613756c3.rlib --extern colorchoice=/playground/target/debug/deps/libcolorchoice-c6677832c56adf16.rlib --extern compression_codecs=/playground/target/debug/deps/libcompression_codecs-4f4a1bb7634e1c03.rlib --extern compression_core=/playground/target/debug/deps/libcompression_core-c44621c00fc3246f.rlib --extern const_default=/playground/target/debug/deps/libconst_default-9070b74538de1c4e.rlib --extern convert_case=/playground/target/debug/deps/libconvert_case-7065ebfd0c612e09.rlib --extern cookie=/playground/target/debug/deps/libcookie-124898cfdb624815.rlib --extern cookie_store=/playground/target/debug/deps/libcookie_store-56aa228cf098d4ba.rlib --extern core2=/playground/target/debug/deps/libcore2-b26f36ba4318a4e2.rlib --extern cpufeatures=/playground/target/debug/deps/libcpufeatures-6ebe4431a91b597a.rlib --extern crc32fast=/playground/target/debug/deps/libcrc32fast-acd98063b405a068.rlib --extern crossbeam=/playground/target/debug/deps/libcrossbeam-d0bc10f0f9ededcb.rlib --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-7f53a8119a7051a8.rlib --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-2f91775a21d2b5c3.rlib --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-e109f0a88152a061.rlib --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-80457f32cb99cefc.rlib --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-9ee094194fa600b5.rlib --extern crypto_common=/playground/target/debug/deps/libcrypto_common-c8db1a2d5d99bf2a.rlib --extern cssparser=/playground/target/debug/deps/libcssparser-c0b1258b604a9883.rlib --extern cssparser_macros=/playground/target/debug/deps/libcssparser_macros-581d6bbfca8efe85.so --extern csv=/playground/target/debug/deps/libcsv-2c666a9433442cf8.rlib --extern csv_core=/playground/target/debug/deps/libcsv_core-9404c03b5ae9da93.rlib --extern data_encoding=/playground/target/debug/deps/libdata_encoding-8e09ad290032e325.rlib --extern deranged=/playground/target/debug/deps/libderanged-e4d9a19551c8557d.rlib --extern derive_more_0_99_20=/playground/target/debug/deps/libderive_more-fd9a8cc963fb0c77.so --extern derive_more=/playground/target/debug/deps/libderive_more-56628a1f5160fc4a.rlib --extern derive_more_impl=/playground/target/debug/deps/libderive_more_impl-19321798165bb5c2.so --extern destructure_traitobject=/playground/target/debug/deps/libdestructure_traitobject-829f77be92d9b6be.rlib --extern digest=/playground/target/debug/deps/libdigest-5dcfbfd6a764b935.rlib --extern displaydoc=/playground/target/debug/deps/libdisplaydoc-cb0971d1f186e78c.so --extern document_features=/playground/target/debug/deps/libdocument_features-d8527ad9d89f7d82.so --extern dtoa=/playground/target/debug/deps/libdtoa-545f21489abed9e0.rlib --extern dtoa_short=/playground/target/debug/deps/libdtoa_short-d5cd918d962d2f00.rlib --extern dunce=/playground/target/debug/deps/libdunce-b10e6a36dfbf7930.rlib --extern ego_tree=/playground/target/debug/deps/libego_tree-73f40f45b6a4e570.rlib --extern either=/playground/target/debug/deps/libeither-59c3c25dd109a1f4.rlib --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-e35afa9cf6257f04.rlib --extern env_filter=/playground/target/debug/deps/libenv_filter-38f2c1982e64a918.rlib --extern env_logger=/playground/target/debug/deps/libenv_logger-f136554a301fd741.rlib --extern equator=/playground/target/debug/deps/libequator-b0462227062435eb.rlib --extern equator_macro=/playground/target/debug/deps/libequator_macro-6c7be3e9c83d3661.so --extern equivalent=/playground/target/debug/deps/libequivalent-0aa8633503843b1d.rlib --extern exr=/playground/target/debug/deps/libexr-4fd09c2514f9023e.rlib --extern fallible_iterator_0_2_0=/playground/target/debug/deps/libfallible_iterator-78181c302fe2a95d.rlib --extern fallible_iterator=/playground/target/debug/deps/libfallible_iterator-e0d7ba2356bc3941.rlib --extern fallible_streaming_iterator=/playground/target/debug/deps/libfallible_streaming_iterator-4d43113dcd7e624e.rlib --extern faster_hex=/playground/target/debug/deps/libfaster_hex-d44bb73bc6d5e633.rlib --extern fastrand=/playground/target/debug/deps/libfastrand-7facbaa3cdec1804.rlib --extern fax=/playground/target/debug/deps/libfax-ae1325feaf86144c.rlib --extern fax_derive=/playground/target/debug/deps/libfax_derive-28a4e89201acbd40.so --extern fdeflate=/playground/target/debug/deps/libfdeflate-079253eb0d115276.rlib --extern filetime=/playground/target/debug/deps/libfiletime-2e453113e9b639f1.rlib --extern find_msvc_tools=/playground/target/debug/deps/libfind_msvc_tools-22eb48903f0723b2.rlib --extern fixedbitset_0_4_2=/playground/target/debug/deps/libfixedbitset-e884c2cdbc2b28f7.rlib --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-c0ce8b456c751122.rlib --extern flate2=/playground/target/debug/deps/libflate2-1a16381eab815eea.rlib --extern fnv=/playground/target/debug/deps/libfnv-c83dd288116d22a3.rlib --extern foldhash_0_1_5=/playground/target/debug/deps/libfoldhash-6d4b61ae779a4b80.rlib --extern foldhash=/playground/target/debug/deps/libfoldhash-6e894e24277d1204.rlib --extern foreign_types=/playground/target/debug/deps/libforeign_types-21cfd0509e60997a.rlib --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-54300d37a1dc9e86.rlib --extern form_urlencoded=/playground/target/debug/deps/libform_urlencoded-13cfccaad0d0ae67.rlib --extern fs_extra=/playground/target/debug/deps/libfs_extra-2b0e42d21600b1d9.rlib --extern futf=/playground/target/debug/deps/libfutf-daad7ce55e2e3a40.rlib --extern futures_0_1_31=/playground/target/debug/deps/libfutures-d15221489a7c75be.rlib --extern futures=/playground/target/debug/deps/libfutures-c514fc8608531d08.rlib --extern futures_channel=/playground/target/debug/deps/libfutures_channel-8b2b65985a27d04b.rlib --extern futures_core=/playground/target/debug/deps/libfutures_core-36b4650629fb76bb.rlib --extern futures_executor=/playground/target/debug/deps/libfutures_executor-16d6610a4d35a2a5.rlib --extern futures_io=/playground/target/debug/deps/libfutures_io-dff1125e2cfb2bd8.rlib --extern futures_macro=/playground/target/debug/deps/libfutures_macro-434996b1a8c7878f.so --extern futures_sink=/playground/target/debug/deps/libfutures_sink-c9de3ece2487f0ce.rlib --extern futures_task=/playground/target/debug/deps/libfutures_task-e47d7289a7587cc8.rlib --extern futures_util=/playground/target/debug/deps/libfutures_util-572a6c99d4f0467c.rlib --extern fxhash=/playground/target/debug/deps/libfxhash-6d362db88fc991f3.rlib --extern generic_array_0_14_7=/playground/target/debug/deps/libgeneric_array-387e1792208e92bf.rlib --extern generic_array=/playground/target/debug/deps/libgeneric_array-c2a810cacc5775b2.rlib --extern getopts=/playground/target/debug/deps/libgetopts-834a6a8ce4f319f8.rlib --extern getrandom_0_2_16=/playground/target/debug/deps/libgetrandom-31c0d0138bd3df2e.rlib --extern getrandom=/playground/target/debug/deps/libgetrandom-5e09843ed1380517.rlib --extern gif=/playground/target/debug/deps/libgif-2d47bb5c8fd9ff60.rlib --extern gimli=/playground/target/debug/deps/libgimli-51b7b5efee4e6347.rlib --extern glob=/playground/target/debug/deps/libglob-034b2c46835bf95c.rlib --extern h2=/playground/target/debug/deps/libh2-dc27f9136ec7cc0e.rlib --extern half=/playground/target/debug/deps/libhalf-20de12f0ff23aa3e.rlib --extern hash32=/playground/target/debug/deps/libhash32-b0c5224ce9f3d1c8.rlib --extern hashbrown_0_15_5=/playground/target/debug/deps/libhashbrown-0ed4f8e1a9d46e35.rlib --extern hashbrown=/playground/target/debug/deps/libhashbrown-b415483c3a2fec15.rlib --extern hashlink=/playground/target/debug/deps/libhashlink-737595dcde0b0894.rlib --extern hdrhistogram=/playground/target/debug/deps/libhdrhistogram-f5efad88b8fd64d6.rlib --extern heapless=/playground/target/debug/deps/libheapless-26c16fa0fe305b4d.rlib --extern heck=/playground/target/debug/deps/libheck-634e4b5da59437af.rlib --extern hmac=/playground/target/debug/deps/libhmac-16e3f95d5f256614.rlib --extern html5ever_0_26_0=/playground/target/debug/deps/libhtml5ever-714521d23d523e43.rlib --extern html5ever=/playground/target/debug/deps/libhtml5ever-7f4a8909990dd073.rlib --extern http=/playground/target/debug/deps/libhttp-6b01efe326110dae.rlib --extern http_body=/playground/target/debug/deps/libhttp_body-47b6503ded501aad.rlib --extern http_body_util=/playground/target/debug/deps/libhttp_body_util-1205534358739f46.rlib --extern http_range_header=/playground/target/debug/deps/libhttp_range_header-99a4a1b4ed571481.rlib --extern httparse=/playground/target/debug/deps/libhttparse-c7461cdb9a3aca43.rlib --extern httpdate=/playground/target/debug/deps/libhttpdate-01e485a0cc7a20c3.rlib --extern humantime=/playground/target/debug/deps/libhumantime-9dcc8540632d1a07.rlib --extern hybrid_array=/playground/target/debug/deps/libhybrid_array-b59d426d2bea5a31.rlib --extern hyper=/playground/target/debug/deps/libhyper-039573c2493f05a3.rlib --extern hyper_rustls=/playground/target/debug/deps/libhyper_rustls-5a0ef407e747fe56.rlib --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-dbb0d44d2a20b218.rlib --extern hyper_util=/playground/target/debug/deps/libhyper_util-ef33e6eadfacb7f1.rlib --extern iana_time_zone=/playground/target/debug/deps/libiana_time_zone-946b5162d892ed15.rlib --extern icu_collections=/playground/target/debug/deps/libicu_collections-e7757ab0246d5fc7.rlib --extern icu_locale_core=/playground/target/debug/deps/libicu_locale_core-192bf9809b00efb4.rlib --extern icu_normalizer=/playground/target/debug/deps/libicu_normalizer-71802b9903732256.rlib --extern icu_normalizer_data=/playground/target/debug/deps/libicu_normalizer_data-783bbfbc3a430362.rlib --extern icu_properties=/playground/target/debug/deps/libicu_properties-b5b5234517564fb9.rlib --extern icu_properties_data=/playground/target/debug/deps/libicu_properties_data-77e6b8413aa3279a.rlib --extern icu_provider=/playground/target/debug/deps/libicu_provider-7b88fb03f48c17c7.rlib --extern idna=/playground/target/debug/deps/libidna-634d2346a90beb90.rlib --extern idna_adapter=/playground/target/debug/deps/libidna_adapter-0af25daadd4554bc.rlib --extern image=/playground/target/debug/deps/libimage-a3c5545a92458c1b.rlib --extern image_webp=/playground/target/debug/deps/libimage_webp-a1163574a6e1aca8.rlib --extern imgref=/playground/target/debug/deps/libimgref-7ef82907a7dbd40d.rlib --extern indexmap=/playground/target/debug/deps/libindexmap-187003081d43d94e.rlib --extern iovec=/playground/target/debug/deps/libiovec-a80e1d24c86f1b6c.rlib --extern ipnet=/playground/target/debug/deps/libipnet-ba350b5bc091e431.rlib --extern iri_string=/playground/target/debug/deps/libiri_string-7f3cae729d7951e2.rlib --extern is_terminal_polyfill=/playground/target/debug/deps/libis_terminal_polyfill-cbb22e29e528ce96.rlib --extern itertools_0_13_0=/playground/target/debug/deps/libitertools-b640541c317370b8.rlib --extern itertools=/playground/target/debug/deps/libitertools-ab678ae2863bf74a.rlib --extern itoa=/playground/target/debug/deps/libitoa-76364ae43bdd8853.rlib --extern jiff=/playground/target/debug/deps/libjiff-1a4176fb9394a77a.rlib --extern jobserver=/playground/target/debug/deps/libjobserver-3e201df1c4d8cf4d.rlib --extern lazy_static=/playground/target/debug/deps/liblazy_static-9a7119a03c0f9c42.rlib --extern lebe=/playground/target/debug/deps/liblebe-0ce7df9d9639ac55.rlib --extern libc=/playground/target/debug/deps/liblibc-3f6ceeb72911f791.rlib --extern libm=/playground/target/debug/deps/liblibm-fe819babc78e3a42.rlib --extern libsqlite3_sys=/playground/target/debug/deps/liblibsqlite3_sys-6cb9c0fab526e4d3.rlib --extern linux_raw_sys_0_11_0=/playground/target/debug/deps/liblinux_raw_sys-816f90303109c7af.rlib --extern linux_raw_sys=/playground/target/debug/deps/liblinux_raw_sys-209a5768bc4d6d82.rlib --extern litemap=/playground/target/debug/deps/liblitemap-e7d02124dd5c847c.rlib --extern litrs=/playground/target/debug/deps/liblitrs-e2b5a79a774f1cb3.rlib --extern lock_api=/playground/target/debug/deps/liblock_api-9aeca48b42f43ea4.rlib --extern log=/playground/target/debug/deps/liblog-37b36b1138bccda9.rlib --extern log_mdc=/playground/target/debug/deps/liblog_mdc-b137fedca9e6dd88.rlib --extern log4rs=/playground/target/debug/deps/liblog4rs-e351c27a0ef8d141.rlib --extern loop9=/playground/target/debug/deps/libloop9-1815024eef2387c2.rlib --extern mac=/playground/target/debug/deps/libmac-28a60312f0b25a6e.rlib --extern markup5ever_0_11_0=/playground/target/debug/deps/libmarkup5ever-498908714b67418b.rlib --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-b90af035d33efe2f.rlib --extern markup5ever_rcdom=/playground/target/debug/deps/libmarkup5ever_rcdom-74d19f8d203ab808.rlib --extern matrixmultiply=/playground/target/debug/deps/libmatrixmultiply-3bb8259ebbe99feb.rlib --extern maybe_rayon=/playground/target/debug/deps/libmaybe_rayon-e7640ecf38338da2.rlib --extern md5=/playground/target/debug/deps/libmd5-1f9fbd966c9db691.rlib --extern memchr=/playground/target/debug/deps/libmemchr-b2125737a2b86a60.rlib --extern memmap=/playground/target/debug/deps/libmemmap-85c33584c8cf0a3b.rlib --extern memoffset=/playground/target/debug/deps/libmemoffset-8c14d5e2db6a8740.rlib --extern mime=/playground/target/debug/deps/libmime-47c1f0fe5b106f57.rlib --extern mime_guess=/playground/target/debug/deps/libmime_guess-6a298b297ea958c3.rlib --extern minimal_lexical=/playground/target/debug/deps/libminimal_lexical-b368051a83dbe595.rlib --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-9c18c75586ff1adb.rlib --extern mio=/playground/target/debug/deps/libmio-70882fa051fe04bd.rlib --extern mock_instant=/playground/target/debug/deps/libmock_instant-7485d66a915f646d.rlib --extern moxcms=/playground/target/debug/deps/libmoxcms-c3df75aff0777336.rlib --extern nalgebra=/playground/target/debug/deps/libnalgebra-0ef71933b08154f8.rlib --extern nalgebra_macros=/playground/target/debug/deps/libnalgebra_macros-95ee991b43f06c22.so --extern native_tls=/playground/target/debug/deps/libnative_tls-b50c486a148a993f.rlib --extern ndarray=/playground/target/debug/deps/libndarray-d00a3abffc7ba070.rlib --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-67101fabcd8f048d.rlib --extern nom_7_1_3=/playground/target/debug/deps/libnom-a6da7c2d7f600bcd.rlib --extern nom=/playground/target/debug/deps/libnom-eb946fd273171a1a.rlib --extern noop_proc_macro=/playground/target/debug/deps/libnoop_proc_macro-3b682bfd5c2986cf.so --extern num=/playground/target/debug/deps/libnum-03338f5305b38875.rlib --extern num_bigint=/playground/target/debug/deps/libnum_bigint-2e95591d407aa630.rlib --extern num_complex=/playground/target/debug/deps/libnum_complex-bb58717acaa2a3b7.rlib --extern num_conv=/playground/target/debug/deps/libnum_conv-ad475ce6bb892599.rlib --extern num_derive=/playground/target/debug/deps/libnum_derive-a015e5f2e30c5f69.so --extern num_integer=/playground/target/debug/deps/libnum_integer-4064378951e7ea90.rlib --extern num_iter=/playground/target/debug/deps/libnum_iter-2908a8d2a73c7d74.rlib --extern num_rational=/playground/target/debug/deps/libnum_rational-2593c94a482600ac.rlib --extern num_traits=/playground/target/debug/deps/libnum_traits-8324a54efeda9d2c.rlib --extern num_cpus=/playground/target/debug/deps/libnum_cpus-7064e46ed1a3be56.rlib --extern object=/playground/target/debug/deps/libobject-0d05c0a46d07b6d4.rlib --extern once_cell=/playground/target/debug/deps/libonce_cell-adcb4d457d57ece7.rlib --extern openssl=/playground/target/debug/deps/libopenssl-8b2d456ef97b3279.rlib --extern openssl_macros=/playground/target/debug/deps/libopenssl_macros-61a313aba9d48ef5.so --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-fa4ea0707081b1ab.rlib --extern openssl_sys=/playground/target/debug/deps/libopenssl_sys-26924c4b69b6408f.rlib --extern ordered_float=/playground/target/debug/deps/libordered_float-02f3fc0c50b93b70.rlib --extern parking_lot=/playground/target/debug/deps/libparking_lot-888f812346647b75.rlib --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-7b2acee41a858a66.rlib --extern paste=/playground/target/debug/deps/libpaste-bb8d46bfd02cdebd.so --extern pastey=/playground/target/debug/deps/libpastey-32f764cb72562bd4.so --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-cf4d414bcea3099f.rlib --extern petgraph_0_6_5=/playground/target/debug/deps/libpetgraph-74437714bac67568.rlib --extern petgraph=/playground/target/debug/deps/libpetgraph-676ab826e85cc59a.rlib --extern phf_0_10_1=/playground/target/debug/deps/libphf-aae50f175cb1559a.rlib --extern phf_0_11_3=/playground/target/debug/deps/libphf-36376dde7b6fb8f9.rlib --extern phf=/playground/target/debug/deps/libphf-1ab8460a15d9a082.rlib --extern phf_codegen_0_10_0=/playground/target/debug/deps/libphf_codegen-5338e278c99090a4.rlib --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-7946c84c6703c85c.rlib --extern phf_generator_0_10_0=/playground/target/debug/deps/libphf_generator-64dc8d4e5cd05cf0.rlib --extern phf_generator_0_11_3=/playground/target/debug/deps/libphf_generator-79815dbb3a5a6707.rlib --extern phf_generator=/playground/target/debug/deps/libphf_generator-04071ed8f9dcdfc4.rlib --extern phf_macros_0_11_3=/playground/target/debug/deps/libphf_macros-3c895d8274a57410.so --extern phf_macros=/playground/target/debug/deps/libphf_macros-4773cf30ea8386bb.so --extern phf_shared_0_10_0=/playground/target/debug/deps/libphf_shared-b5438fced6496711.rlib --extern phf_shared_0_11_3=/playground/target/debug/deps/libphf_shared-9ed5559afa5857b2.rlib --extern phf_shared=/playground/target/debug/deps/libphf_shared-6a455f85804eb931.rlib --extern pin_project_lite=/playground/target/debug/deps/libpin_project_lite-e592cb65c274c83b.rlib --extern pin_utils=/playground/target/debug/deps/libpin_utils-c5428260280d5cb2.rlib --extern pkg_config=/playground/target/debug/deps/libpkg_config-e04c5071b23480ce.rlib --extern png=/playground/target/debug/deps/libpng-6fb4383266c5a17e.rlib --extern postgres=/playground/target/debug/deps/libpostgres-27d530dee4cbb9ff.rlib --extern postgres_protocol=/playground/target/debug/deps/libpostgres_protocol-3b995f68b30f93f2.rlib --extern postgres_types=/playground/target/debug/deps/libpostgres_types-ad4b68184982dd13.rlib --extern potential_utf=/playground/target/debug/deps/libpotential_utf-6a79eef181cf120d.rlib --extern powerfmt=/playground/target/debug/deps/libpowerfmt-73f7befc01795dfb.rlib --extern ppv_lite86=/playground/target/debug/deps/libppv_lite86-9d1906e673965f8e.rlib --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-79eaef263cdc8ef4.rlib --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-84690cc6866fe66c.rlib --extern profiling=/playground/target/debug/deps/libprofiling-bbef24f6514906ee.rlib --extern profiling_procmacros=/playground/target/debug/deps/libprofiling_procmacros-e5b9e8e0042053c8.so --extern psl_types=/playground/target/debug/deps/libpsl_types-221477247deb62ee.rlib --extern publicsuffix=/playground/target/debug/deps/libpublicsuffix-587d33859c40723e.rlib --extern pxfm=/playground/target/debug/deps/libpxfm-ce1c89107ab5bd02.rlib --extern qoi=/playground/target/debug/deps/libqoi-255d98420d18e372.rlib --extern quick_error=/playground/target/debug/deps/libquick_error-3db4f8b19b38b0d6.rlib --extern quote=/playground/target/debug/deps/libquote-b2c4ea2cb164c1ff.rlib --extern rand_0_8_5=/playground/target/debug/deps/librand-f7cbe1f5f092e081.rlib --extern rand=/playground/target/debug/deps/librand-a5c56fb71748809a.rlib --extern rand_chacha_0_3_1=/playground/target/debug/deps/librand_chacha-a27f91ffc9ffc959.rlib --extern rand_chacha=/playground/target/debug/deps/librand_chacha-0be717a02ac318db.rlib --extern rand_core_0_6_4=/playground/target/debug/deps/librand_core-29a3244ea4c16e70.rlib --extern rand_core=/playground/target/debug/deps/librand_core-443c6335690eb90e.rlib --extern rand_distr=/playground/target/debug/deps/librand_distr-3e2a2b71867e9bf6.rlib --extern rav1e=/playground/target/debug/deps/librav1e-9214d8c2e29c9e4b.rlib --extern ravif=/playground/target/debug/deps/libravif-f07881603cafcbba.rlib --extern rawpointer=/playground/target/debug/deps/librawpointer-19589c4be5c36778.rlib --extern rayon=/playground/target/debug/deps/librayon-9c01b114ad2fef65.rlib --extern rayon_core=/playground/target/debug/deps/librayon_core-5f254debb6f6c56c.rlib --extern regex=/playground/target/debug/deps/libregex-b6a43ca6b00c2dee.rlib --extern regex_automata=/playground/target/debug/deps/libregex_automata-750eee3554623b6e.rlib --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-1a11c44f6c335024.rlib --extern reqwest=/playground/target/debug/deps/libreqwest-90c32aaaca1bda48.rlib --extern rgb=/playground/target/debug/deps/librgb-d3fc2ba1604a6456.rlib --extern ring=/playground/target/debug/deps/libring-c15faae9ca25024c.rlib --extern rusqlite=/playground/target/debug/deps/librusqlite-713fd08d928351d4.rlib --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-524c7281ac647672.rlib --extern rustix=/playground/target/debug/deps/librustix-6007515bd21639b0.rlib --extern rustls=/playground/target/debug/deps/librustls-994623faa897bca6.rlib --extern rustls_pki_types=/playground/target/debug/deps/librustls_pki_types-a204638816023a95.rlib --extern webpki=/playground/target/debug/deps/libwebpki-cff244d5ec83f5c0.rlib --extern rustversion=/playground/target/debug/deps/librustversion-d7a1cab06ba76036.so --extern ryu=/playground/target/debug/deps/libryu-4a4fd40082b5de27.rlib --extern safe_arch=/playground/target/debug/deps/libsafe_arch-d2a9c67686cb3cba.rlib --extern same_file=/playground/target/debug/deps/libsame_file-0cea9fd0e1629f3d.rlib --extern scopeguard=/playground/target/debug/deps/libscopeguard-9215752600491415.rlib --extern scraper=/playground/target/debug/deps/libscraper-08ebe0f1ce20a3b4.rlib --extern select=/playground/target/debug/deps/libselect-90446d180a93a777.rlib --extern selectors=/playground/target/debug/deps/libselectors-ca140732fd423bbb.rlib --extern semver=/playground/target/debug/deps/libsemver-374a1009d913b5b3.rlib --extern serde=/playground/target/debug/deps/libserde-a1fb27d9465818fe.rlib --extern serde_value=/playground/target/debug/deps/libserde_value-445b99c5ea0cffcc.rlib --extern serde_core=/playground/target/debug/deps/libserde_core-66d84d69ee96afdf.rlib --extern serde_derive=/playground/target/debug/deps/libserde_derive-00ecc562a8395e12.so --extern serde_json=/playground/target/debug/deps/libserde_json-9e99de4b669f3ef6.rlib --extern serde_spanned=/playground/target/debug/deps/libserde_spanned-0e9bf7b6c95ec7d6.rlib --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-60c8cbcf506614de.rlib --extern serde_yaml=/playground/target/debug/deps/libserde_yaml-a92b870e478916d8.rlib --extern servo_arc=/playground/target/debug/deps/libservo_arc-2476e2bba4e195a1.rlib --extern sha1_smol=/playground/target/debug/deps/libsha1_smol-d9bf14ed0aaa0905.rlib --extern sha2=/playground/target/debug/deps/libsha2-796c703f6fcdb191.rlib --extern shlex=/playground/target/debug/deps/libshlex-6599caf05ae1039c.rlib --extern signal_hook_registry=/playground/target/debug/deps/libsignal_hook_registry-066d3fcd3b7ed2a0.rlib --extern simba=/playground/target/debug/deps/libsimba-f81e34fd673f79ab.rlib --extern simd_adler32=/playground/target/debug/deps/libsimd_adler32-3f65fc997753015c.rlib --extern simd_helpers=/playground/target/debug/deps/libsimd_helpers-2def51dafb8b02f5.so --extern siphasher_0_3_11=/playground/target/debug/deps/libsiphasher-472c2df808d8e46e.rlib --extern siphasher=/playground/target/debug/deps/libsiphasher-93567ba0af5c9471.rlib --extern slab=/playground/target/debug/deps/libslab-984425709f06e1e0.rlib --extern smallvec=/playground/target/debug/deps/libsmallvec-60346dfd28560fea.rlib --extern socket2=/playground/target/debug/deps/libsocket2-d5a0c6864b35a0f5.rlib --extern sptr=/playground/target/debug/deps/libsptr-d9e0cac27b0bea56.rlib --extern stable_deref_trait=/playground/target/debug/deps/libstable_deref_trait-d160f9bd0a693307.rlib --extern string_cache=/playground/target/debug/deps/libstring_cache-8e776c277bc80e3b.rlib --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-15c433f4d576662e.rlib --extern stringprep=/playground/target/debug/deps/libstringprep-55c6e3ec2da49096.rlib --extern strsim=/playground/target/debug/deps/libstrsim-f9b0a05515226f87.rlib --extern subtle=/playground/target/debug/deps/libsubtle-7da494fecbd869c7.rlib --extern syn_1_0_109=/playground/target/debug/deps/libsyn-45e4b666e8bb983d.rlib --extern syn=/playground/target/debug/deps/libsyn-a81bbbcdfeb0a44a.rlib --extern sync_wrapper=/playground/target/debug/deps/libsync_wrapper-d91853e2098ed83a.rlib --extern synstructure=/playground/target/debug/deps/libsynstructure-64adaa5e4d58b826.rlib --extern tar=/playground/target/debug/deps/libtar-01509659935f1ab2.rlib --extern tempfile=/playground/target/debug/deps/libtempfile-b124cc2ef4b78beb.rlib --extern tendril=/playground/target/debug/deps/libtendril-f3e2cb5dd958cf07.rlib --extern terminal_size=/playground/target/debug/deps/libterminal_size-4b42e7040b83867e.rlib --extern thiserror=/playground/target/debug/deps/libthiserror-3eb2b187306644d6.rlib --extern thiserror_impl=/playground/target/debug/deps/libthiserror_impl-7d5c1d52453099e2.so --extern thread_id=/playground/target/debug/deps/libthread_id-70a11ef01bd33111.rlib --extern threadpool=/playground/target/debug/deps/libthreadpool-d9f3be63753b74b3.rlib --extern tiff=/playground/target/debug/deps/libtiff-4f3b04ee9ca8ce9d.rlib --extern time=/playground/target/debug/deps/libtime-51bd81e1e494c384.rlib --extern time_core=/playground/target/debug/deps/libtime_core-db9726ff305ca3d7.rlib --extern time_macros=/playground/target/debug/deps/libtime_macros-87618e8bf3b04b77.so --extern tinystr=/playground/target/debug/deps/libtinystr-70580bd3a1a66b74.rlib --extern tinyvec=/playground/target/debug/deps/libtinyvec-22073b91d2829988.rlib --extern tinyvec_macros=/playground/target/debug/deps/libtinyvec_macros-c493a7607347b438.rlib --extern tokio=/playground/target/debug/deps/libtokio-70a0f52d407adac1.rlib --extern tokio_io=/playground/target/debug/deps/libtokio_io-d722ac530f6ca358.rlib --extern tokio_macros=/playground/target/debug/deps/libtokio_macros-e628a76d1be2d93d.so --extern tokio_native_tls=/playground/target/debug/deps/libtokio_native_tls-2924337302f9031b.rlib --extern tokio_postgres=/playground/target/debug/deps/libtokio_postgres-c259686429ee34d9.rlib --extern tokio_rustls=/playground/target/debug/deps/libtokio_rustls-d52a1313ff161e05.rlib --extern tokio_stream=/playground/target/debug/deps/libtokio_stream-cf8841b4f7761271.rlib --extern tokio_util=/playground/target/debug/deps/libtokio_util-a95c6f7596049da5.rlib --extern toml=/playground/target/debug/deps/libtoml-4b4e0c16c67b5777.rlib --extern toml_datetime=/playground/target/debug/deps/libtoml_datetime-491cbd3550cd896c.rlib --extern toml_parser=/playground/target/debug/deps/libtoml_parser-307e87a65a79bc96.rlib --extern toml_writer=/playground/target/debug/deps/libtoml_writer-e266b2ba8f383a82.rlib --extern tower=/playground/target/debug/deps/libtower-354b7168a163648b.rlib --extern tower_http=/playground/target/debug/deps/libtower_http-7960991b50fb7658.rlib --extern tower_layer=/playground/target/debug/deps/libtower_layer-de18ea94c6a041d6.rlib --extern tower_service=/playground/target/debug/deps/libtower_service-8a3ebed63e1e495e.rlib --extern tracing=/playground/target/debug/deps/libtracing-919c6d577ef82181.rlib --extern tracing_attributes=/playground/target/debug/deps/libtracing_attributes-75c368e14a194102.so --extern tracing_core=/playground/target/debug/deps/libtracing_core-a4bdf6e7801ea249.rlib --extern trpl=/playground/target/debug/deps/libtrpl-9e0d13d0e0c0b20d.rlib --extern try_lock=/playground/target/debug/deps/libtry_lock-e98c118bd2ea891e.rlib --extern typemap_ors=/playground/target/debug/deps/libtypemap_ors-e01b04bb13b92f74.rlib --extern typenum=/playground/target/debug/deps/libtypenum-b17ce8499582f44a.rlib --extern unicase=/playground/target/debug/deps/libunicase-2d9e6a0db4b2d3fe.rlib --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-fb88fa06210965de.rlib --extern unicode_ident=/playground/target/debug/deps/libunicode_ident-11444c7a525cf9e8.rlib --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-231906d8779f7e13.rlib --extern unicode_properties=/playground/target/debug/deps/libunicode_properties-db09111f7436a30d.rlib --extern unicode_segmentation=/playground/target/debug/deps/libunicode_segmentation-83fa2183b1f760fb.rlib --extern unicode_width=/playground/target/debug/deps/libunicode_width-7c389150024cb5ec.rlib --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-ad1679f653d44fdb.rlib --extern unsafe_any_ors=/playground/target/debug/deps/libunsafe_any_ors-15506b7b5a161017.rlib --extern unsafe_libyaml=/playground/target/debug/deps/libunsafe_libyaml-f6122d38af7695f0.rlib --extern untrusted=/playground/target/debug/deps/libuntrusted-a0e2fe1720fa3cd1.rlib --extern url=/playground/target/debug/deps/liburl-bec30833283694d1.rlib --extern utf8=/playground/target/debug/deps/libutf8-b3eafb012370ed64.rlib --extern utf8_iter=/playground/target/debug/deps/libutf8_iter-e1c5c172df6f0786.rlib --extern utf8parse=/playground/target/debug/deps/libutf8parse-149a297d12eed339.rlib --extern uuid=/playground/target/debug/deps/libuuid-85847186201a9665.rlib --extern v_frame=/playground/target/debug/deps/libv_frame-10ba2050d8d01621.rlib --extern vcpkg=/playground/target/debug/deps/libvcpkg-95ea934bb1f2c6d6.rlib --extern version_check=/playground/target/debug/deps/libversion_check-0baa7a5dd740a136.rlib --extern walkdir=/playground/target/debug/deps/libwalkdir-bf3faf8af3d7ca2b.rlib --extern want=/playground/target/debug/deps/libwant-ed934ad7866c919d.rlib --extern wasm_bindgen=/playground/target/debug/deps/libwasm_bindgen-3278e697672d3876.rlib --extern wasm_bindgen_macro=/playground/target/debug/deps/libwasm_bindgen_macro-cfdce54bb4534221.so --extern wasm_bindgen_macro_support=/playground/target/debug/deps/libwasm_bindgen_macro_support-9d7d757671d95192.rlib --extern wasm_bindgen_shared=/playground/target/debug/deps/libwasm_bindgen_shared-ade8a75011a84e83.rlib --extern webpki_roots=/playground/target/debug/deps/libwebpki_roots-abfaf6ebd2dec8af.rlib --extern weezl=/playground/target/debug/deps/libweezl-54a383db1e12dff1.rlib --extern whoami=/playground/target/debug/deps/libwhoami-a47b27cbf773cc1b.rlib --extern wide=/playground/target/debug/deps/libwide-f5ea6164e647ff17.rlib --extern windows_link=/playground/target/debug/deps/libwindows_link-1b19eda4e6440b32.rlib --extern windows_sys_0_52_0=/playground/target/debug/deps/libwindows_sys-32478fc56cdf5bcb.rlib --extern windows_sys_0_59_0=/playground/target/debug/deps/libwindows_sys-37e8e87f7d4a99fa.rlib --extern windows_sys_0_60_2=/playground/target/debug/deps/libwindows_sys-fe43a8fcec78fab0.rlib --extern windows_sys=/playground/target/debug/deps/libwindows_sys-d3ec6f8acd47587a.rlib --extern windows_targets_0_52_6=/playground/target/debug/deps/libwindows_targets-7bcb98533c5a5c60.rlib --extern windows_targets=/playground/target/debug/deps/libwindows_targets-47c01f80574419ab.rlib --extern windows_aarch64_gnullvm_0_52_6=/playground/target/debug/deps/libwindows_aarch64_gnullvm-343804a929b9bc2e.rlib --extern windows_aarch64_gnullvm=/playground/target/debug/deps/libwindows_aarch64_gnullvm-85c80aa48d5e6b15.rlib --extern windows_aarch64_msvc_0_52_6=/playground/target/debug/deps/libwindows_aarch64_msvc-a5b499fc4fca325c.rlib --extern windows_aarch64_msvc=/playground/target/debug/deps/libwindows_aarch64_msvc-4e29c447ad31bf2c.rlib --extern windows_i686_gnu_0_52_6=/playground/target/debug/deps/libwindows_i686_gnu-aabba30c6f85e8db.rlib --extern windows_i686_gnu=/playground/target/debug/deps/libwindows_i686_gnu-73cfa58bd9286234.rlib --extern windows_i686_msvc_0_52_6=/playground/target/debug/deps/libwindows_i686_msvc-59a560b4b265508b.rlib --extern windows_i686_msvc=/playground/target/debug/deps/libwindows_i686_msvc-2da284f64cb4392a.rlib --extern windows_x86_64_gnu_0_52_6=/playground/target/debug/deps/libwindows_x86_64_gnu-6b434238f72010e6.rlib --extern windows_x86_64_gnu=/playground/target/debug/deps/libwindows_x86_64_gnu-cda40c5b2f832954.rlib --extern windows_x86_64_gnullvm_0_52_6=/playground/target/debug/deps/libwindows_x86_64_gnullvm-6d1a94ac49072bc7.rlib --extern windows_x86_64_gnullvm=/playground/target/debug/deps/libwindows_x86_64_gnullvm-b5a2465915eda753.rlib --extern windows_x86_64_msvc_0_52_6=/playground/target/debug/deps/libwindows_x86_64_msvc-9b036e52df5b31e0.rlib --extern windows_x86_64_msvc=/playground/target/debug/deps/libwindows_x86_64_msvc-d84155fc3590a014.rlib --extern winnow=/playground/target/debug/deps/libwinnow-861eaba11f479a14.rlib --extern writeable=/playground/target/debug/deps/libwriteable-bf98deb64b2a628c.rlib --extern xattr=/playground/target/debug/deps/libxattr-e0a794789a45a040.rlib --extern xml5ever=/playground/target/debug/deps/libxml5ever-10697d11f199ad0a.rlib --extern y4m=/playground/target/debug/deps/liby4m-17a13d7c16722b61.rlib --extern yoke=/playground/target/debug/deps/libyoke-f6e16931b43714cc.rlib --extern yoke_derive=/playground/target/debug/deps/libyoke_derive-520224de7a304a31.so --extern zerocopy=/playground/target/debug/deps/libzerocopy-67fe94a97c89f202.rlib --extern zerocopy_derive=/playground/target/debug/deps/libzerocopy_derive-b1359c419270f51b.so --extern zerofrom=/playground/target/debug/deps/libzerofrom-40fecb6f5f610791.rlib --extern zerofrom_derive=/playground/target/debug/deps/libzerofrom_derive-64061db98df167a8.so --extern zeroize=/playground/target/debug/deps/libzeroize-55e631fdff860424.rlib --extern zerotrie=/playground/target/debug/deps/libzerotrie-75082852da5e89ec.rlib --extern zerovec=/playground/target/debug/deps/libzerovec-89a864351752671b.rlib --extern zerovec_derive=/playground/target/debug/deps/libzerovec_derive-1389b9d41c84fa0f.so --extern zstd=/playground/target/debug/deps/libzstd-56b77a5c7e21db16.rlib --extern zstd_safe=/playground/target/debug/deps/libzstd_safe-5603f1a13cf76e86.rlib --extern zstd_sys=/playground/target/debug/deps/libzstd_sys-0a19ee58f646656f.rlib --extern zune_core_0_4_12=/playground/target/debug/deps/libzune_core-40bc3b5e42e66a94.rlib --extern zune_core=/playground/target/debug/deps/libzune_core-900ee7a870dc3167.rlib --extern zune_inflate=/playground/target/debug/deps/libzune_inflate-96d8e24854fb8db9.rlib --extern zune_jpeg_0_4_21=/playground/target/debug/deps/libzune_jpeg-9016490097e3423c.rlib --extern zune_jpeg=/playground/target/debug/deps/libzune_jpeg-c2a0c2bc03c9acef.rlib -L native=/playground/target/debug/build/zstd-sys-ae70b494ee05ba22/out -L native=/playground/target/debug/build/aws-lc-sys-8714e8ec0019dd5e/out -L native=/playground/target/debug/build/ring-5e23c2456e550993/out -L native=/playground/target/debug/build/libsqlite3-sys-8ef8ee658c097489/out -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnu-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_aarch64_gnullvm-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_aarch64_gnullvm-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_aarch64_msvc-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_aarch64_msvc-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_gnu-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_gnu-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_msvc-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_i686_msvc-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnullvm-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_gnullvm-0.53.1/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_msvc-0.52.6/lib -L native=/playground/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/windows_x86_64_msvc-0.53.1/lib` (signal: 11, SIGSEGV: invalid memory reference)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Fixes rust-lang/rust#149542
Fixes rust-lang/rust#149431

First commit is a drive-by needed for the refactor of the unreachable code lint, see https://github.com/rust-lang/rust/issues/148303

### CODE REVIEW

File: compiler/rustc_hir/src/hir.rs [hunk 1]
```diff
@@ -1793,6 +1793,54 @@ impl<'hir> Pat<'hir> {
...
+    /// what happens when this returns true.
+    ///
+    /// [m]: ../../rustc_middle/ty/struct.TyCtxt.html#method.expr_guaranteed_to_constitute_read_for_never
+    pub fn is_guaranteed_to_constitute_read_for_never(&self) -> bool {
+        match self.kind {
+            // Does not constitute a read.
+            PatKind::Wild => false,
+
+            // Might not constitute a read, since the condition might be false.
+            PatKind::Guard(_, _) => true,
```
Comment (jackh726) [inline compiler/rustc_hir/src/hir.rs]: A drive-by thought: this comment doesn't seem to match the function? From the comment, the expectation is `false`, given the function is `guaranteed` but this comment just it's *not* guaranteed.

File: tests/ui/reachable/type_ascribe_never_field.rs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// Regression test for <https://github.com/rust-lang/rust/issues/149431>
```
Comment (jackh726) [inline tests/ui/reachable/type_ascribe_never_field.rs:1]: In the previous commit, you moved tests from `unreachable-code` to `reachable`, but this test is in `unreachable-code`?

File: compiler/rustc_hir/src/hir.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_hir/src/hir.rs]: Ok soo.... this is weird. *Both the comment and the code are wrong*.

The guard in a guard pattern can only be executed after the inner pattern matched, so it can't affect whatever we make a read or not, at most it will affect whatever following patterns can execute or not (which we do not check anyway).

i.e. the following should be well defined imo:
```rust
#![feature(guard_patterns, never_type)]
#![expect(incomplete_features, unused_parens)]
#![deny(unreachable_code)]

fn main() {
    unsafe {
        let x = std::ptr::null::<!>();

        let (_ if true): ! = *x;
        ();
    }
}
```

(right now it emits unreachable code lint and causes UB)

File: tests/ui/reachable/type_ascribe_never_field.rs (hunk 2 above)
Comment (WaffleLapkin) [reply tests/ui/reachable/type_ascribe_never_field.rs:1]: Oops. Fixed that.

File: compiler/rustc_hir/src/hir.rs (hunk 1 above)
Comment (jackh726) [reply compiler/rustc_hir/src/hir.rs]: cool
