### PR TITLE
mir: adjust conditional in recursion limit check

### LINKED ISSUE #67552: [ICE] with recursive impl trait and Iterator.by_ref()
The compiler panics when compiling the following code.

I tried this code:

main.rs:
```
fn main() {
    rec(std::iter::empty::<()>(), 0);
}

fn rec(mut it: impl Iterator, n: u32) -> usize {
    if n == 0 {
        it.count()
    } else {
        rec(it.by_ref(), n - 1)
    }
}
```

I ran:

$ rustc main.rs

Rustc panics:

```
thread 'rustc' panicked at 'assertion failed: !substs.needs_infer()', src/librustc/traits/specialize/mod.rs:122:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu
```

## Meta

$ rustc --version --verbose
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-unknown-linux-gnu
release: 1.39.0
LLVM version: 9.0

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #67552.

This PR adjusts the condition used in the recursion limit check of
the monomorphization collector, from `>` to `>=`.

In #67552, the test case had infinite indirect recursion, repeating a
handful of functions (from the perspective of the monomorphization
collector): `rec` -> `identity` -> `Iterator::count` -> `Iterator::fold`
-> `Iterator::next` -> `rec`.

During this process, `resolve_associated_item` was invoked for
`Iterator::fold` (during the construction of an `Instance`), and
ICE'd due to substitutions needing inference. However, previous
iterations of this recursion would have called this function for
`Iterator::fold` - and did! - and succeeded in doing so (trivially
checkable from debug logging, `()` is present where `_` is in the substs
of the failing execution).

The expected outcome of this test case would be a recursion limit error
(which is present when the `identity` fn indirection is removed), and
the recursion depth of `rec` is increasing (other functions finish
collecting their neighbours and thus have their recursion depths reset).

When the ICE occurs, the recursion depth of `rec` is 256 (which matches
the recursion limit), which suggests perhaps that a different part of
the compiler is using a `>=` comparison and returning a different result
on this recursion rather than what it returned in every previous
recursion, thus stopping the monomorphization collector from reporting
an error on the next recursion, where `recursion_depth_of_rec > 256`
would have been true.

With grep and some educated guesses, we can determine that
the recursion limit check at line 818 in
`src/librustc_trait_selection/traits/project.rs` is the other check that
is using a different comparison. Modifying either comparison to be `>` or
`>=` respectively will fix the error, but changing the monomorphization
collector produces the nicer error.

### CODE REVIEW

**Comment by varkor** [comment]
It seems this inconsistency is found in more places throughout the compiler, e.g. in these two locations
https://github.com/rust-lang/rust/blob/a59264b01247836c70e24217e0d346b868387525/src/librustc_ty/needs_drop.rs#L70-L72
https://github.com/rust-lang/rust/blob/a59264b01247836c70e24217e0d346b868387525/src/librustc_mir/interpret/eval_context.rs#L635-L637
These should probably be fixed at the same time. Also, this behaviour should be documented, e.g. in https://doc.rust-lang.org/reference/attributes/limits.html (though for now, we could just open an issue). It would be good to make sure the other limit attributes behave similarly.

Do you think you could audit these limits and add a comment somewhere appropriate mentioning this?

**Comment by Mark-Simulacrum** [comment]
It seems reasonable to add a struct somewhere with check and increment methods that would store recursion limits and be used throughout the compiler, to hopefully prevent this from happening again.

**Comment by davidtwco** [comment]
I've added a commit with a `Limit` type, based on @Mark-Simulacrum's suggestion. I chose to make the comparison `value <= limit`, as while this did result in a larger diff, it behaved more like I would expect - in the macro expansion recursion limit tests, a limit of four would show four "in expansion of" lines - which matched my expectations. I'll submit a PR to the reference shortly.

File: src/librustc_session/session.rs [hunk 1]
```diff
@@ -55,6 +57,52 @@ pub enum CtfeBacktrace {
...
+
+impl Limit {
+    /// Create a new limit from a `usize`.
+    pub fn new(value: usize) -> Self {
+        Limit(value)
+    }
+
+    /// Check that `value` is within the limit. Ensures that the same comparisons are used
+    /// throughout the compiler, as mismatches can cause ICEs, see #72540.
+    pub fn within_limit(&self, value: usize) -> bool {
```
Comment (varkor) [inline src/librustc_session/session.rs:73]: Maybe `value_within_limit` would be a less ambiguous name, because currently it reads like the argument is the limit, rather than the other way around.

File: src/librustc_session/session.rs [hunk 2]
```diff
@@ -55,6 +57,52 @@ pub enum CtfeBacktrace {
     Immediate,
 }
 
+/// New-type wrapper around `usize` for representing limits. Ensures that comparisons against
+/// limits are consistent throughout the compiler.
+#[derive(Clone, Copy, Debug)]
+pub struct Limit(usize);
```
Comment (varkor) [inline src/librustc_session/session.rs:63]: Is there a reason not to just make the `usize` a public field?

**Review by varkor — COMMENTED** [review]
This looks good to me. r=me with the name change, or similar.

File: src/librustc_session/session.rs (hunk 1 above)
Comment (Havvy) [reply src/librustc_session/session.rs:73]: Bikeshedding: `is_reached_by` so the code reads `recursion_limit.is_reached_by(some_depth)`

Comment (davidtwco) [reply src/librustc_session/session.rs:73]: I've changed the name to this.

File: src/librustc_session/session.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc_session/session.rs:63]: Fixed!
