### PR TITLE
Fix #53525  - Unify E0243, E0244, E0087, E0088, E0089, and E0090 into E0107

### LINKED ISSUE #53525: Unify E0243, E0244 and E0107
[E0243](https://doc.rust-lang.org/error-index.html#E0243) and [E0244](https://doc.rust-lang.org/error-index.html#E0244) are both errors about providing the wrong number of generic arguments. Having both is unnecessary: it'd be better if they were unified with [E0107](https://doc.rust-lang.org/error-index.html#E0107) — the analogous error for lifetimes.

`GenericArgMismatchErrorCode` can go once this is done.

### PR DESCRIPTION
**Pull request by matthew-russo**
Fix #53525

This pr merges all errors related to too many or too few generic arguments in types and functions. E0243, E0244, E0087, E0088, E0089, E0090 errors will no longer be emitted and E0107 will be used instead.

### CODE REVIEW

**Comment by mcr431** [comment]
referencing #53525, consolidating error codes E0087, E0088, E0089, E0090, E0243, and E0244 into E0107. Let me know if there are any changes I should make

File: src/librustc_typeck/diagnostics.rs [hunk 1]
```diff
@@ -1041,6 +1041,7 @@ enum NightsWatch {}
 "##,
 
 E0087: r##"
+#### Note: this error code is no longer emitted by the compiler.
```
Comment (varkor) [inline src/librustc_typeck/diagnostics.rs]: Could you leave a blank line after the note (and the ones in the other error messages), just for readability?

File: src/librustc_typeck/diagnostics.rs [hunk 2]
```diff
@@ -1258,18 +1262,53 @@ extern "rust-intrinsic" {
 "##,
 
 E0107: r##"
-This error means that an incorrect number of lifetime parameters were provided
-for a type (like a struct or enum) or trait:
+This error means that an incorrect number of type or lifetime parameters
```
Comment (varkor) [inline src/librustc_typeck/diagnostics.rs]: Since we're going to be getting const parameters fairly soon, it's easier just to call them "generic arguments" rather than "type or lifetime parameters".

File: src/librustc_typeck/diagnostics.rs [hunk 3]
```diff
@@ -1258,18 +1262,53 @@ extern "rust-intrinsic" {
...
+                  //        expected 0, found 1
+}
+```
+
+```compile_fail,E0107
+struct Foo<T> { x: T }
+
+struct Bar { x: Foo }             // error: wrong number of type arguments:
+                                  //        expected 1, found 0
+struct Baz<S, T> { x: Foo<S, T> } // error: wrong number of type arugemtns:
```
Comment (varkor) [inline src/librustc_typeck/diagnostics.rs]: *arguments

File: src/librustc_typeck/diagnostics.rs [hunk 4]
```diff
@@ -1258,18 +1262,53 @@ extern "rust-intrinsic" {
...
+fn main() {
+    let x: bool = true;
+    foo::<f64>(x);           // error: wrong number of type arguments:
+                             //        expected 2, found 1
+    foo::<f64, f64, i32>(x); // error: wrong number of type arguments:
+                             //        expected 2, found 3
 }
 ```
+
+```compile_fail,E0088
```
Comment (varkor) [inline src/librustc_typeck/diagnostics.rs]: Should be `E0107`.

File: src/librustc_typeck/diagnostics.rs [hunk 5]
```diff
@@ -1258,18 +1262,53 @@ extern "rust-intrinsic" {
...
-    foo: Foo<'a>, // error: expected 2, found 1
-    bar: Bar<'a>, // error: expected 0, found 1
+    foo: Foo<'a>, // error: wrong number of lifetime arguments:
+                  //        expected 2, found 1
+    bar: Bar<'a>, // error: wrong number of lifetime arguments:
+                  //        expected 0, found 1
+}
+```
+
+```compile_fail,E0107
```
Comment (varkor) [inline src/librustc_typeck/diagnostics.rs]: These examples can be in the same code block. You don't need an example of less than/greater than the expected number for every single position — maybe one example for each position (type, function call, method call).

**Review by varkor — CHANGES_REQUESTED** [review]
This is looking good so far! It looks like there are still some tests failing, which you'll need to update. Also, it's not linking the committer for each commit with your GitHub profile, which you might want to fix with a rebase.

**Comment by varkor** [comment]
If you put the pull request description in the first comment (and title), it helps people to tell what the pull request is doing, at a glance, too. I think you'll need to put "Fix #53525" in the first comment for GitHub to automatically close the issue when this is merged.

**Comment by mcr431** [comment]
Noted. Will probably not get a chance to update this before this evening

**Comment by mcr431** [comment]
@varkor I rebased and changed order of code. Honestly not positive if I got it right since was my first time reordering git commits. Also still haven't fixed all failing errors so will do that tomorrow and will need to rebase again. Will update when its ready to review

**Comment by mcr431** [comment]
Yeah I had set up a dummy account to test stuff and forgot to switch it back. When rebasing with fixed test cases I'll make sure it has proper author

**Comment by varkor** [comment]
Ah, the snippets in the diagnostics are also run by the test-suite, so you'll need to update the `compile_fail` error code so that it matches the new code `E0107`.

**Comment by mcr431** [comment]
finally!

**Comment by varkor** [comment]
@mcr431: that's looking great! If you could just fix the [typo here](https://github.com/rust-lang/rust/pull/53584/files/8540117cc408805a8f2ccdaff465010c18eb63dc#diff-0827bbd2c0dfd5eaf2059ca7f0c35a56), it'll be good to go! (You can do the other two comments as well, but they'll have to be modified when const generics are merged anyway, so it's fine to leave them like that for now).

**Comment by varkor** [comment]
Thanks @mcr431, that all looks great to me: nice work!

@bors r+
