### PR TITLE
Always set the deployment target when building std

### LINKED ISSUE #650: "was built for iOS 16.4" warning
Seeing the following type of errors after upgrading from rust 1.79 to 1.80:

```
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[441](ee9320b67fe2b8d4-lse_ldadd8_acq.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[442](ee9320b67fe2b8d4-lse_ldadd8_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[443](ee9320b67fe2b8d4-lse_ldadd8_acq_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[444](ee9320b67fe2b8d4-lse_ldclr1_relax.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[445](ee9320b67fe2b8d4-lse_ldclr1_acq.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[446](ee9320b67fe2b8d4-lse_ldclr1_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
```

<details>

<summary>The full list of problematic `.o` files</summary>

```
lse_cas1_relax.o
lse_cas1_acq.o
lse_cas1_rel.o
lse_cas1_acq_rel.o
lse_cas2_relax.o
lse_cas2_acq.o
lse_cas2_rel.o
lse_cas2_acq_rel.o
lse_cas4_relax.o
lse_cas4_acq.o
lse_cas4_rel.o
lse_cas4_acq_rel.o
lse_cas8_relax.o
lse_cas8_acq.o
lse_cas8_rel.o
lse_cas8_acq_rel.o
lse_cas16_relax.o
lse_cas16_acq.o
lse_cas16_rel.o
lse_cas16_acq_rel.o
lse_swp1_relax.o
lse_swp1_acq.o
lse_swp1_rel.o
lse_swp1_acq_rel.o
lse_swp2_relax.o
lse_swp2_acq.o
lse_swp2_rel.o
lse_swp2_acq_rel.o
lse_swp4_relax.o
lse_swp4_acq.o
lse_swp4_rel.o
lse_swp4_acq_rel.o
lse_swp8_relax.o
lse_swp8_acq.o
lse_swp8_rel.o
lse_swp8_acq_rel.o
lse_ldadd1_relax.o
lse_ldadd1_acq.o
lse_ldadd1_rel.o
lse_ldadd1_acq_rel.o
lse_ldadd2_relax.o
lse_ldadd2_acq.o
lse_ldadd2_rel.o
lse_ldadd2_acq_rel.o
lse_ldadd4_relax.o
lse_ldadd4_acq.o
lse_ldadd4_rel.o
lse_ldadd4_acq_rel.o
lse_ldadd8_relax.o
lse_ldadd8_acq.o
lse_ldadd8_rel.o
lse_ldadd8_acq_rel.o
lse_ldclr1_relax.o
lse_ldclr1_acq.o
lse_ldclr1_rel.o
lse_ldclr1_acq_rel.o
lse_ldclr2_relax.o
lse_ldclr2_acq.o
lse_ldclr2_rel.o
lse_ldclr2_acq_rel.o
lse_ldclr4_relax.o
lse_ldclr4_acq.o
lse_ldclr4_rel.o
lse_ldclr4_acq_rel.o
lse_ldclr8_relax.o
lse_ldclr8_acq.o
lse_ldclr8_rel.o
lse_ldclr8_acq_rel.o
lse_ldeor1_relax.o
lse_ldeor1_acq.o
lse_ldeor1_rel.o
lse_ldeor1_acq_rel.o
lse_ldeor2_relax.o
lse_ldeor2_acq.o
lse_ldeor2_rel.o
lse_ldeor2_acq_rel.o
lse_ldeor4_relax.o
lse_ldeor4_acq.o
lse_ldeor4_rel.o
lse_ldeor4_acq_rel.o
lse_ldeor8_relax.o
lse_ldeor8_acq.o
lse_ldeor8_rel.o
lse_ldeor8_acq_rel.o
lse_ldset1_relax.o
lse_ldset1_acq.o
lse_ldset1_rel.o
lse_ldset1_acq_rel.o
lse_ldset2_relax.o
lse_ldset2_acq.o
lse_ldset2_rel.o
lse_ldset2_acq_rel.o
lse_ldset4_relax.o
lse_ldset4_acq.o
lse_ldset4_rel.o
lse_ldset4_acq_rel.o
lse_ldset8_relax.o
lse_ldset8_acq.o
lse_ldset8_rel.o
lse_ldset8_acq_rel.o
aarch64.o
absvdi2.o
absvsi2.o
addtf3.o
addvdi3.o
addvsi3.o
clzdi2.o
clzsi2.o
cmpdi2.o
comparetf2.o
ctzdi2.o
ctzsi2.o
divdc3.o
divsc3.o
divtf3.o
extenddftf2.o
extendhfsf2.o
extendsftf2.o
fp_mode.o
fixtfdi.o
fixtfsi.o
fixtfti.o
fixunstfdi.o
fixunstfsi.o
fixunstfti.o
floatditf.o
floatsitf.o
floatunditf.o
floatunsitf.o
int_util.o
muldc3.o
mulsc3.o
multc3.o
multf3.o
mulvdi3.o
mulvsi3.o
negdf2.o
negdi2.o
negsf2.o
negvdi2.o
negvsi2.o
paritydi2.o
paritysi2.o
popcountdi2.o
popcountsi2.o
powitf2.o
subtf3.o
subvdi3.o
subvsi3.o
truncdfhf2.o
truncsfhf2.o
trunctfdf2.o
trunctfsf2.o
ucmpdi2.o
atomic_flag_clear.o
atomic_flag_clear_explicit.o
atomic_flag_test_and_set.o
atomic_flag_test_and_set_explicit.o
atomic_signal_fence.o
atomic_thread_fence.o
```

</details>

### LINKED ISSUE #128419: "was built for iOS 16.4" warning after updating from 1.79 to 1.80
Seeing the following type of warning after upgrading from rust 1.79 to 1.80:

```
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[441](ee9320b67fe2b8d4-lse_ldadd8_acq.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[442](ee9320b67fe2b8d4-lse_ldadd8_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[443](ee9320b67fe2b8d4-lse_ldadd8_acq_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[444](ee9320b67fe2b8d4-lse_ldclr1_relax.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[445](ee9320b67fe2b8d4-lse_ldclr1_acq.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
ld: warning: object file (external/Capture/Capture.xcframework/ios-arm64/Capture.framework/Capture[446](ee9320b67fe2b8d4-lse_ldclr1_rel.o)) was built for newer 'iOS' version (16.4) than being linked (15.0)
```

<details>

<summary>THE FULL LIST OF PROBLEMATIC `.o` FILES</summary>

```
lse_cas1_relax.o
lse_cas1_acq.o
lse_cas1_rel.o
lse_cas1_acq_rel.o
lse_cas2_relax.o
lse_cas2_acq.o
lse_cas2_rel.o
lse_cas2_acq_rel.o
lse_cas4_relax.o
lse_cas4_acq.o
lse_cas4_rel.o
lse_cas4_acq_rel.o
lse_cas8_relax.o
lse_cas8_acq.o
lse_cas8_rel.o
lse_cas8_acq_rel.o
lse_cas16_relax.o
lse_cas16_acq.o
lse_cas16_rel.o
lse_cas16_acq_rel.o
lse_swp1_relax.o
lse_swp1_acq.o
lse_swp1_rel.o
lse_swp1_acq_rel.o
lse_swp2_relax.o
lse_swp2_acq.o
lse_swp2_rel.o
lse_swp2_acq_rel.o
lse_swp4_relax.o
lse_swp4_acq.o
lse_swp4_rel.o
lse_swp4_acq_rel.o
lse_swp8_relax.o
lse_swp8_acq.o
lse_swp8_rel.o
lse_swp8_acq_rel.o
lse_ldadd1_relax.o
lse_ldadd1_acq.o
lse_ldadd1_rel.o
lse_ldadd1_acq_rel.o
lse_ldadd2_relax.o
lse_ldadd2_acq.o
lse_ldadd2_rel.o
lse_ldadd2_acq_rel.o
lse_ldadd4_relax.o
lse_ldadd4_acq.o
lse_ldadd4_rel.o
lse_ldadd4_acq_rel.o
lse_ldadd8_relax.o
lse_ldadd8_acq.o
lse_ldadd8_rel.o
lse_ldadd8_acq_rel.o
lse_ldclr1_relax.o
lse_ldclr1_acq.o
lse_ldclr1_rel.o
lse_ldclr1_acq_rel.o
lse_ldclr2_relax.o
lse_ldclr2_acq.o
lse_ldclr2_rel.o
lse_ldclr2_acq_rel.o
lse_ldclr4_relax.o
lse_ldclr4_acq.o
lse_ldclr4_rel.o
lse_ldclr4_acq_rel.o
lse_ldclr8_relax.o
lse_ldclr8_acq.o
lse_ldclr8_rel.o
lse_ldclr8_acq_rel.o
lse_ldeor1_relax.o
lse_ldeor1_acq.o
lse_ldeor1_rel.o
lse_ldeor1_acq_rel.o
lse_ldeor2_relax.o
lse_ldeor2_acq.o
lse_ldeor2_rel.o
lse_ldeor2_acq_rel.o
lse_ldeor4_relax.o
lse_ldeor4_acq.o
lse_ldeor4_rel.o
lse_ldeor4_acq_rel.o
lse_ldeor8_relax.o
lse_ldeor8_acq.o
lse_ldeor8_rel.o
lse_ldeor8_acq_rel.o
lse_ldset1_relax.o
lse_ldset1_acq.o
lse_ldset1_rel.o
lse_ldset1_acq_rel.o
lse_ldset2_relax.o
lse_ldset2_acq.o
lse_ldset2_rel.o
lse_ldset2_acq_rel.o
lse_ldset4_relax.o
lse_ldset4_acq.o
lse_ldset4_rel.o
lse_ldset4_acq_rel.o
lse_ldset8_relax.o
lse_ldset8_acq.o
lse_ldset8_rel.o
lse_ldset8_acq_rel.o
aarch64.o
absvdi2.o
absvsi2.o
addtf3.o
addvdi3.o
addvsi3.o
clzdi2.o
clzsi2.o
cmpdi2.o
comparetf2.o
ctzdi2.o
ctzsi2.o
divdc3.o
divsc3.o
divtf3.o
extenddftf2.o
extendhfsf2.o
extendsftf2.o
fp_mode.o
fixtfdi.o
fixtfsi.o
fixtfti.o
fixunstfdi.o
fixunstfsi.o
fixunstfti.o
floatditf.o
floatsitf.o
floatunditf.o
floatunsitf.o
int_util.o
muldc3.o
mulsc3.o
multc3.o
multf3.o
mulvdi3.o
mulvsi3.o
negdf2.o
negdi2.o
negsf2.o
negvdi2.o
negvsi2.o
paritydi2.o
paritysi2.o
popcountdi2.o
popcountsi2.o
powitf2.o
subtf3.o
subvdi3.o
subvsi3.o
truncdfhf2.o
truncsfhf2.o
trunctfdf2.o
trunctfsf2.o
ucmpdi2.o
atomic_flag_clear.o
atomic_flag_clear_explicit.o
atomic_flag_test_and_set.o
atomic_flag_test_and_set_explicit.o
atomic_signal_fence.o
atomic_thread_fence.o
```

</details>

### Code

I expected not to see an issue with files being built for iOS 16.4 and up only.

Instead, this happened: The compiler complains about the app being built for iOS 15.0 while parts of the binary appear to have been built for iOS 16.4 and up only.

### Version it worked on

It most recently worked on: 1.79

### Version with regression

1.80

### PR DESCRIPTION
**Pull request by madsmtm**
`cc` has [a bug/feature](https://github.com/rust-lang/cc-rs/issues/1171) (I guess depending on how you look at it) where the default deployment target is taken from the SDK instead of from `rustc`. This causes `compiler-builtins` to build `compiler-rt` with the wrong deployment target on iOS.

I've been meaning to change how `cc` works in this regard, but that's a lengthy process, so let's fix it in bootstrap for now.

The behaviour can be seen locally with `./x build library --set build.optimized-compiler-builtins=true` for various target triples, and then inspecting with `otool -l build/host/stage1/lib/rustlib/*/lib/libcompiler_builtins-*.rlib | rg 'minos|version'`. I have added a rmake test that ensures that we now have the same version everywhere.

Fixes https://github.com/rust-lang/rust/issues/128419
Fixes https://github.com/rust-lang/compiler-builtins/issues/650
Fixes https://github.com/rust-lang/rust/issues/136523
See also https://github.com/rust-lang/cargo/issues/13115, https://github.com/rust-lang/cc-rs/issues/1171, https://github.com/rust-lang/rust/issues/136113
See https://github.com/rust-lang/rust/pull/133092#issuecomment-2626206772 for a description of how the change works.

try-job: i686-gnu-1
try-job: i686-gnu-2
try-job: x86_64-apple-1
try-job: aarch64-apple
try-job: dist-apple-various
try-job: dist-aarch64-apple
try-job: dist-various-2
try-job: x86_64-fuchsia

### CODE REVIEW

**Comment by madsmtm** [comment]
> This PR changes how LLVM is built. Consider updating src/bootstrap/download-ci-llvm-stamp.

Not sure if I should? It changes in theory (we pass different flags), but in practice it shouldn't (because those flags were already set by `cmake-rs`, so they were just duplicated)?

**Comment by Mark-Simulacrum** [comment]
r=me modulo comment

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 1]
```diff
@@ -462,8 +462,55 @@ fn compiler_rt_for_profiler(builder: &Builder<'_>) -> PathBuf {
...
+            "XROS_DEPLOYMENT_TARGET"
+        } else {
+            panic!("unknown target OS for apple target");
+        };
+
+        // Unconditionally set the env var (if it was set in the environment
+        // already, rustc should've picked that up).
+        cargo.env(env_var, value);
+
+        // Allow CI to override the deployment target for `std`.
```
[the remark this answers is not in the document]
Comment (madsmtm) [reply src/bootstrap/src/core/build_steps/compile.rs:510]: So, you can always override it by just using the environment variable itself. I.e. doing `IPHONEOS_DEPLOYMENT_TARGET=14.0 ./x build --target aarch64-apple-ios` would raise the deployment target for the standard library to 14.0.

The reason why `MACOSX_STD_DEPLOYMENT_TARGET` exists is because we might want to build `std` with one version, and the host tooling LLVM, `rustc`, Cargo etc. with another (this option isn't needed for the other platforms, since only macOS has support for host tooling).

[the remark this answers is not in the document]
Comment (Mark-Simulacrum) [reply src/bootstrap/src/core/build_steps/compile.rs:510]: Can you expand the comment to include "this option isn't needed for the other platforms, since only macOS has support for host tooling"? That reasoning makes sense but I think we should persist it into the comments too.

[the remark this answers is not in the document]
Comment (madsmtm) [reply src/bootstrap/src/core/build_steps/compile.rs]: Done!

**Comment by Zalathar** [comment]
Could this have caused the failure at https://github.com/rust-lang/rust/pull/133609#issuecomment-2507121542?

**Comment by alex-semenyuk** [comment]
@madsmtm
Thanks for your contribution
From wg-triage. Could you please take a look comments above

**Comment by madsmtm** [comment]
Yeah, I'm aware that it failed, just haven't gotten around to looking into it yet

**Comment by madsmtm** [comment]
Okay, so I believe I've fixed that error, the issue was that bootstrap was setting `CMAKE_C_FLAGS`, which prevented `cmake-rs` from setting the define itself based on `cc-rs`' defaults.
@rustbot ready

Since it is unlikely that I caught everything:
@rustbot rollup=iffy

**Comment by madsmtm** [comment]
Actually, I decided to downscope this, as I realized there were more implications that I originally thought.

Functionally, I've now split `Build::cflags` into `Build::default_cflags` and `Build::extra_cflags`. Most places call both, with the exception of Cargo, which only calls `extra_cflags` (to allow the default ones to be selected by `cc-rs`). In the future, I'd like to do the same for our use of `cmake-rs`, and probably other places too, but that requires more work.

With that change done, passing the `*_DEPLOYMENT_TARGET` variables in bootstrap when building with Cargo allows `compiler-builtins`' build script to pick a higher deployment target.

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 2]
```diff
@@ -1541,7 +1541,8 @@ pub fn compiler_file(
         return PathBuf::new();
     }
     let mut cmd = command(compiler);
-    cmd.args(builder.cflags(target, GitRepo::Rustc, c));
+    cmd.args(builder.default_cflags(target, c));
+    cmd.args(builder.extra_cflags(target, GitRepo::Rustc, c));
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/compile.rs:1586]: Discussion: based on the method comments, should we just be explicit and call them `cc_handled_clags` vs `cc_unhandled_cflags`?

Comment (madsmtm) [reply src/bootstrap/src/core/build_steps/compile.rs]: That's fine by me!

**Comment by madsmtm** [comment]
> Some changes occurred in src/tools/cargo

Sorry for the ping, I accidentally updated the submodule in a commit.

**Review by jieyouxu — APPROVED** [review]
Thanks, this LGTM as well, waiting for Mark to do a final review. I'll mark this as rollup=iffy and run a couple of try jobs in the meantime.

**Comment by matthiaskrgr** [comment]
looks like its stuck
@bors force

**Comment by tgross35** [comment]
@bors r- retry

https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/bors.20stuck.3F.20.282025-02-09.29

**Comment by workingjubilee** [comment]
I am skeptical about the idea that error was spurious.
@bors r- rollup=never

@bors try

**Comment by workingjubilee** [comment]
er whoops.

@bors try

**Comment by workingjubilee** [comment]
Yeaaah, I don't think that's spurious.

**Comment by madsmtm** [comment]
I'll try to take a look myself first

**Comment by madsmtm** [comment]
Pretty sure I've fixed this now, the issue was that CI scripts were (correctly) setting `CFLAGS_*`, and bootstrap was then overriding these preferences. It worked implicitly before by invoking `cc-rs` in bootstrap to get the default flags (which meant that `cc-rs` parsed the `CFLAGS_*`), now we do it manually.

**Comment by jieyouxu** [comment]
(Tidy moment)

**Review by jieyouxu — APPROVED** [review]
LGTM with tidy pleased

**Comment by jieyouxu** [comment]
The bootstrap diff LGTM.
@bors r=Mark-Simulacrum,jieyouxu

File: src/bootstrap/src/core/builder/cargo.rs [hunk 3]
```diff
@@ -329,10 +336,17 @@ impl Cargo {
...
-                let cxxflags = builder.cflags(target, GitRepo::Rustc, CLang::Cxx).join(" ");
-                self.command
-                    .env(format!("CXX_{triple_underscored}"), &cxx)
-                    .env(format!("CXXFLAGS_{triple_underscored}"), cxxflags);
+                self.command.env(format!("CXX_{triple_underscored}"), &cxx);
+
+                // Extend `CXXFLAGS_$TARGET` with our extra flags.
+                let env = format!("CXXFLAGS_{triple_underscored}");
+                let mut cxxflags =
+                    builder.cc_unhandled_cflags(target, GitRepo::Rustc, CLang::Cxx).join(" ");
```
Comment (aeubanks) [inline src/bootstrap/src/core/builder/cargo.rs:344]: @madsmtm this change here broke our rust build (http://crbug.com/395891130) and extending this with `cc_handled_cflags()` fixes the issue. was it intentional to leave out the cc handled flags here (and above)?

(also nit: typo in `cc_handled_clags`)

Comment (aeubanks) [reply src/bootstrap/src/core/builder/cargo.rs:344]: ah I see it was intentional based on the comments, but it's dropping flags we're passing via `CFLAGS`/`CXXFLAGS`/`LDFLAGS` like `--sysroot=` in the stage1 build. am I holding it wrong? should I be using some other method to pass flags?

```
  = note: ld.lld: error: undefined reference: __libc_single_threaded
          >>> referenced by /usr/home/aeubanks/repos/chromium/src/third_party/rust-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-d74657ee7dc4cb63.so (disallowed by --no-allow-shlib-undefined)
          
          ld.lld: error: undefined reference: std::__throw_bad_array_new_length()
          >>> referenced by /usr/home/aeubanks/repos/chromium/src/third_party/rust-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-d74657ee7dc4cb63.so (disallowed by --no-allow-shlib-undefined)
          
          ld.lld: error: undefined reference: std::ios_base_library_init()
          >>> referenced by /usr/home/aeubanks/repos/chromium/src/third_party/rust-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-d74657ee7dc4cb63.so (disallowed by --no-allow-shlib-undefined)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `rustc-main` (bin "rustc-main") due to 1 previous error
```

Comment (aeubanks) [reply src/bootstrap/src/core/builder/cargo.rs:344]: @madsmtm having stared at this change a bit more, it seems like there's no longer a way to pass flags to stage1 links, which seems like a big regression?
