### PR TITLE
Recover invalid assoc type bounds using `==`

### LINKED ISSUE #87493: Misleading error message on associated type bounds
I tried this code:

```rust
trait MyTrait {
    type Assoc;
}

#[allow(dead_code)]
fn foo<S, T>(_s: S, _t: T)
where
    S: MyTrait, T: MyTrait<Assoc == S::Assoc>
{}
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=adddc330eab816444616202cc576f88e

I expected to see this happen: The error message should indicate that the `==` should be a single `=`.

Instead, this happened: The error message gives no hint of the correct syntax.  It gives two errors, neither of which are helpful:

```
error: expected one of `,` or `>`, found `==`
 --> src/lib.rs:8:34
  |
8 |     S: MyTrait, T: MyTrait<Assoc == S::Assoc>
  |                                  ^^ expected one of `,` or `>`
  |
help: expressions must be enclosed in braces to be used as const generic arguments
  |
8 |     S: MyTrait, T: MyTrait<{ Assoc == S::Assoc }>
  |                            ^                   ^
```

This error is unhelpful because it says "expected one of `,` or `>`", but `=` is also allowed.  Also, the suggestion to use curly braces is a red herring.

```
error[E0107]: this trait takes 0 const arguments but 1 const argument was supplied
 --> src/lib.rs:8:20
  |
8 |     S: MyTrait, T: MyTrait<Assoc == S::Assoc>
  |                    ^^^^^^^------------------- help: remove these generics
  |                    |
  |                    expected 0 const arguments
  |
note: trait defined here, with 0 const parameters
 --> src/lib.rs:1:7
  |
1 | trait MyTrait {
  |       ^^^^^^^
```

This error is unhelpful because I am not specifying const arguments; I'm specifying associated types.

### Meta

Rust version according to play.rust-lang.org: 1.53.0

### PR DESCRIPTION
**Pull request by JohnTitor**
Fix #87493
r? @estebank

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -1933,7 +1933,19 @@ impl<'a> Parser<'a> {
         }
         match self.parse_expr_res(Restrictions::CONST_EXPR, None) {
             Ok(expr) => {
-                if token::Comma == self.token.kind || self.token.kind.should_end_const_arg() {
+                // Find a mistake like `MyTrait<Assoc == S::Assoc>`.
+                if token::EqEq == snapshot.token.kind {
```
Comment (jackh726) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1937]: I feel like this is the wrong place for this. Haven't dug into this, but I would have expected this to be in the same place as the associated type parsing code? There, we just "accept" with an error `==` when we really want `=`.

I guess this is potentially "ambiguous" if `Assoc == S::Assoc` gets treated as a const arg, which I guess is what currently happens.

Is there anything we can to be smarter here? Would we theoretically be allowed to have a variable named `Assoc`? I'm trying to think of if we had complete knowledge of all traits, types, variables, etc. in scope, are there any cases where we can know if this should be a bracketed const expr arg or an associated type binding?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -1933,7 +1933,19 @@ impl<'a> Parser<'a> {
...
+                    err.span_suggestion(
+                        snapshot.token.span,
+                        "replace `==` with `=`",
+                        "=".to_string(),
+                        Applicability::MaybeIncorrect,
+                    );
```
Comment (jackh726) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1943]: If this does stay here, it might be worth mentioning something like "if you meant to use an associated type binding"

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1937]: I got somewhat confused as to why we didn't have a `==` binop here, but looking at the surrounding code I can now see that we discard whatever op this was and what is being parsed here is the RHS, namely a single path. So I'm getting around to thinking that this is not a bad place to make this check.

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 3]
```diff
@@ -1933,7 +1933,19 @@ impl<'a> Parser<'a> {
...
+                    let value = self.mk_expr_err(expr.span);
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1944]: Shouldn't this be `self.mk_expr_err(start.to(expr.span))`? We'd want this to cover the whole `Foo == Bar` instead of just `Bar`.

**Review by estebank — APPROVED** [review]
Please apply @jackh726's wording change and this can be merged.

**Comment by estebank** [comment]
Just realized that we should probably also check that the rhs is a path (because `foo == 42` is more likely to be meant as a const expression), but we can iterate on that later.
