### PR TITLE
Account for `!` arm in tail `match` expr

### LINKED ISSUE #24157: Incorrect "match arms have incompatible types" error message
I have code that `match`es on a `Result<usize>`, with cases for `Ok(usize_var)` and `Err(why)`. I get a "match arms have incompatible types" error upon compilation which I believe is incorrect.

I'm not incredibly experienced with this, but discussion in irc (https://botbot.me/mozilla/rust/2015-04-06/?msg=35985521&page=37) supports that this may be a bug.

I tried this code (available at http://is.gd/Y00aRi):

``` rust
fn main() {
    let mut input: String = String::new();
    match std::io::stdin().read_line(&mut input) {
        Ok(bytes_read) => bytes_read,
        Err(why) => panic!("{}", why)
    }
    println!("{}", input);
}
```

I expected it to compile, however there is a "match arms have incompatible types" error even though I believe the match arms should both be of type usize.

I should note that adding a semicolon after the match causes clean compilation.

### PR DESCRIPTION
**Pull request by estebank**
On functions with a default return type that influences the coerced type of `match` arms, check if the failing arm is actually of type `!`. If so, suggest changing the return type so the coercion against the prior arms is successful.

```
error[E0308]: `match` arms have incompatible types
  --> $DIR/match-tail-expr-never-type-error.rs:9:13
   |
LL |   fn bar(a: bool) {
   |                  - help: try adding a return type: `-> i32`
LL | /     match a {
LL | |         true => 1,
   | |                 - this is found to be of type `{integer}`
LL | |         false => {
LL | |             never()
   | |             ^^^^^^^
   | |             |
   | |             expected integer, found `()`
   | |             this expression is of type `!`, but it get's coerced to `()` due to its surrounding expression
LL | |         }
LL | |     }
   | |_____- `match` arms have incompatible types
```

Fix #24157.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 1]
```diff
@@ -139,7 +139,30 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    if let hir::ExprKind::Block(block, _) = arm.body.kind
+                        && let Some(expr) = block.expr
+                        && let arm_tail_ty = self.node_ty(expr.hir_id)
+                        && arm_tail_ty.is_never()
+                        && !arm_ty.is_never()
+                    {
+                        err.span_label(
+                            expr.span,
+                            format!(
+                                "this expression is of type `!`, but it get's coerced to \
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/_match.rs:152]: "get's" -> "gets", but i think "is" is equivalent here

```suggestion
                                "this expression is of type `!`, but it is coerced to \
```

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 2]
```diff
@@ -139,7 +139,30 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 &cause,
                 Some(&arm.body),
                 arm_ty,
-                |err| self.suggest_removing_semicolon_for_coerce(err, expr, arm_ty, prior_arm),
+                |err| {
+                    if let hir::ExprKind::Block(block, _) = arm.body.kind
```
Comment (b-naber) [inline compiler/rustc_hir_typeck/src/_match.rs:143]: Please hide this closure body behind a function!

Comment (estebank) [reply compiler/rustc_hir_typeck/src/_match.rs]: Done
