### PR TITLE
Correctly check `never_type` feature gating

### LINKED ISSUE #120542: No feature gate error for `-> !` used in a trait bound
I tried this code:

```rust
pub fn look_ma_no_feature_gate<F: FnOnce() -> !>() {}
```

I expected to see this happen: “error[E0658]: the `!` type is experimental”

Instead, this happened: Successful compilation, as long as I'm using a nightly compiler, but the error when on stable 1.75. 

This is incorrect because nightly features should always require `#![feature]` attributes on nightly (until they're stabilized, which hasn't happened yet for `!`).

### Meta

`rustc --version --verbose`:
```
rustc 1.77.0-nightly (11f32b73e 2024-01-31)
binary: rustc
commit-hash: 11f32b73e0dc9287e305b5b9980d24aecdc8c17f
commit-date: 2024-01-31
host: x86_64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```

@rustbot label +F-never_type +requires-nightly

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #120542.

The feature wasn't tested on return type of a generic function type, so it got under the radar in https://github.com/rust-lang/rust/pull/120316.

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
Can you check if this also works for RPIT? Or `dyn Fn() -> !`?

**Comment by compiler-errors** [comment]
Also, instead of keeping this as "in generics", please just modify this line to check for `!` manually, and leave a comment saying "in generic args, we don't allow -> !" or something:

https://github.com/rust-lang/rust/pull/120316/files#diff-90854f27d73f89fc2997be31fa36f58cb9af532d1387ac39751134afdd2ff8e2R505

**Comment by compiler-errors** [comment]
This will also likely require a beta backport depending on the timing of when this lands. I'll nominate it pre-emptively so we don't forget.

**Comment by GuillaumeGomez** [comment]
> Also, instead of keeping this "in generics" state as part of the visitor, please just modify this line to check for `!` manually, and leave a comment saying "in generic args, we don't allow -> !" or something:
> 
> https://github.com/rust-lang/rust/pull/120316/files#diff-90854f27d73f89fc2997be31fa36f58cb9af532d1387ac39751134afdd2ff8e2R505

Except this is the "default" implementation. It should call the `visitor` method and not the `walk_` one. That's what my PR fixed originally. The problem here lies in the implementation of `PostExpansionVisitor`.

**Comment by compiler-errors** [comment]
Actually, that's not the right line anyways. Just modify the `visit_generic_args` impl to check for `Parenthesized` generics, and manually look for `RetTy::Return` with a `Never` type. If you don't want to do this, I can put up a PR myself.

The manual tracking of a boolean in a walker imo is an anti-pattern, because it's very easy to get wrong with nested items and other AST nodes.

**Comment by GuillaumeGomez** [comment]
No I'm fine with doing it. Just didn't understand what you meant.

**Comment by GuillaumeGomez** [comment]
Applied your suggestions. Added more ui tests and also the case which should work.

File: compiler/rustc_ast_passes/src/feature_gate.rs [hunk 1]
```diff
@@ -362,6 +362,16 @@ impl<'a> Visitor<'a> for PostExpansionVisitor<'a> {
         }
     }
 
+    fn visit_generic_args(&mut self, args: &'a ast::GenericArgs) {
+        if let ast::GenericArgs::Parenthesized(generic_args) = args
```
Comment (compiler-errors) [inline compiler/rustc_ast_passes/src/feature_gate.rs:366]: pls leave a comment explaining why this is being checked here

File: tests/ui/never_type/const-context.rs [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// build-pass
+
+trait X<const N: i32> {}
+
+fn hello<T: X<{ fn hello() -> ! { loop {} } 1 }>>() {}
```
Comment (compiler-errors) [inline tests/ui/never_type/const-context.rs:5]: could you rename this? it's not really that it's in a "const context", it's more about it being in a nested item.

Maybe `never-type-in-nested-fn-decl`

**Review by compiler-errors — APPROVED** [review]
r=me after applying changes

File: tests/ui/never_type/const-context.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply tests/ui/never_type/const-context.rs]: :+1:

File: compiler/rustc_ast_passes/src/feature_gate.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast_passes/src/feature_gate.rs:369]: Good point!

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-02-08/near/420478168)

@rustbot label +beta-accepted
