### PR TITLE
Disable browser history API on file:/// URLs

### LINKED ISSUE #25953: Documentation search no longer works in Chrome Canary when accessing local documentation
The console reports this error:

```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///Users/me/Projects/rust/doc/std/index.html?search=hello' cannot be created in a document with origin 'null'.search @ main.js:578
```

This is [the line of JS](https://github.com/rust-lang/rust/blob/613e57b448c88591b6076a8cea9799f1f3876687/src/librustdoc/html/static/main.js#L578) in question.

I recognize that I'm using a beta browser version, and that the team may not wish to support these browsers. However, it's easy for me to report it, just in case it becomes a problem with the next released version!

### Meta

* Chrome Version 45.0.2454.85 (64-bit)
* OS X
* `rustc 1.2.0`

### PR DESCRIPTION
**Pull request by badboy**
history.pushState is defined, but not working whenever document.origin is "null"
(literally that string, not just the null object).
This is due to some security considerations and is unlikely to be ever working.

For now just disable the usage of the history API when the documentation
is accessed through a file:/// URL.

See https://code.google.com/p/chromium/issues/detail?id=301210 for a
Chrome-specific issue on the history API on file:/// URLs

Closes #25953

### CODE REVIEW

**Comment by christopherdumas** [comment]
@badboy you should probably squash your commits. That's what is normally wanted if your pull request is left sitting for a long time.

**Comment by badboy** [comment]
It's just a few hours yet. I happily squash them though.

File: src/librustdoc/html/static/main.js [hunk 1]
```diff
@@ -54,7 +54,8 @@
     }
 
     function browserSupportsHistoryApi() {
-        return window.history && typeof window.history.pushState === "function";
+        return document.origin != "null" &&
```
Comment (Gankro) [inline src/librustdoc/html/static/main.js]: document.origin doesn't seem to be well-supported: https://developer.mozilla.org/en-US/docs/Web/API/Document/origin

Comment (Gankro) [inline src/librustdoc/html/static/main.js]: Looks like `document.defaultView.location.origin` might be the compatible way?

Comment (badboy) [inline src/librustdoc/html/static/main.js]: Interesting, and I thought this was the standard. I will update & test in Firefox as well.

**Comment by badboy** [comment]
force-pushed, now using `document.location.protocol`, which should be portable enough.
