### PR TITLE
Suggest std::ptr::null if literal 0 is given to a raw pointer function argument

### LINKED ISSUE #107517: Add help when trying to use literal 0 as raw pointer
### Code

```Rust
extern "C" {
    // hypothetical C function which takes a nullable pointer
    fn foo(ptr: *const u8);
}

fn main() {
    unsafe { foo(0); }
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:6:18
  |
6 |     unsafe { foo(0); }
  |              --- ^ expected `*const u8`, found `usize`
  |              |
  |              arguments to this function are incorrect
  |
  = note: expected raw pointer `*const u8`
                    found type `usize`
note: function defined here
 --> src/main.rs:2:8
  |
2 |     fn foo(ptr: *const u8);
  |        ^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:6:18
  |
6 |     unsafe { foo(0); }
  |              --- ^ expected `*const u8`, found `usize`
  |              |
  |              arguments to this function are incorrect
  |
  = note: expected raw pointer `*const u8`
                    found type `usize`
  = help: if you're trying to create a null pointer, use
    std::ptr::null()
note: function defined here
 --> src/main.rs:2:8
  |
2 |     fn foo(ptr: *const u8);
  |        ^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### Rationale and extra context

(Note the added help line.)

C programers could reasonably expect `0` in a raw-pointer position to mean null. Seems like this could be a fairly simple check to save them a google.

(For reference: I'm a fairly experienced Rust programmer, and a novice C programmer, but I haven't done much FFI. I couldn't remember what `std::ptr::null` was called, so I tried 0; I was pretty sure it wasn't going to work, but I hoped I might at least get a helpful error.)

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by edward-shen**
Implementation feels a little sus (we're parsing the span for a `0`) but it seems to fall in line the string-expected-found-char condition right above this check, so I think it's fine.

Feedback appreciated on help text? I think it's consistent but it does sound a little awkward maybe?

Fixes #107517

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 1]
```diff
@@ -1999,6 +1999,19 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
                         (ty::Bool, ty::Tuple(list)) => if list.len() == 0 {
                             self.suggest_let_for_letchains(&mut err, &trace.cause, span);
                         }
+                        // Suggest providing a `std::ptr::null()` if they pass in a 0 to an *const uint
+                        (ty::RawPtr(ptr), ty::Uint(_)) if ptr.mutbl == rustc_hir::Mutability::Not => {
```
Comment (Nilstrieb) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2003]: You can also suggest `std::ptr::null_mut()` for `*mut T`.

Comment (Nilstrieb) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2003]:
```suggestion
                        (ty::RawPtr(ptr), ty::Uint(_)) if ptr.mutbl == hir::Mutability::Not => {
```

File: tests/ui/suggest-null-ptr.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
+// Suggest providing a std::ptr::null if provided with
```
Comment (Nilstrieb) [inline tests/ui/suggest-null-ptr.rs:1]:
```suggestion
// run-rustfix

// Suggest providing a std::ptr::null if provided with
```
To make sure that the suggestion works as expected.

**Comment by edward-shen** [comment]
Changes:
 - Added `run-runfix` directive and a `.fixed` file 
 - `s/rustc_hir/hir/`
 - Added suggestion for `_mut() variant.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 3]
```diff
@@ -1999,6 +1999,31 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
...
+                        // Suggest providing a std::ptr::null{,_mut}() if they pass in a 0 to an *{const,mut} uint
+                        (ty::RawPtr(ptr), ty::Uint(_))  => {
+                            if let Ok(code) = self.tcx.sess().source_map().span_to_snippet(span) {
+                                if let Ok(0) = code.parse::<u8>() {
+                                    match ptr.mutbl {
+                                        hir::Mutability::Not => {
+                                            err.span_suggestion(
+                                                span,
+                                                "if you meant to create a null pointer, use `std::ptr::null()`",
+                                                "std::ptr::null()",
```
Comment (WaffleLapkin) [inline compiler/rustc_infer/src/infer/error_reporting/mod.rs:2011]: Hard-coding `std` may be annoying for `#![no_std]` crates, please get the path to the diagnostic item instead.

The only way I've found so far that does that is the following:
```rust
let null_sym = match ptr.mutbl {
    hir::Mutability::Not => sym::ptr_null,
    hir::Mutability::Mut => sym::ptr_null_mut,
};

if let Some(null_did) = self.tcx.get_diagnostic_item(null_sym) {
    if let Ok((printer, true)) = FmtPrinter::new(self.tcx, Namespace::ValueNS).try_print_visible_def_path(null_did) {
        let path = printer.into_buffer();
        err.span_suggestion(
            span,
            format!("if you meant to create a null pointer, use `{path}`"),
            path + "()",
            Applicability::MachineApplicable,
        );
    }
}
```

File: tests/ui/suggest-null-ptr.rs [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+    fn foo_mut(ptr: *mut u8);
+
+    fn usize(ptr: *const usize);
+
+    fn usize_mut(ptr: *mut usize);
+}
+
+fn main() {
+    unsafe {
```
Comment (eggyal) [inline tests/ui/suggest-null-ptr.rs:17]: Nit: not required

**Comment by workingjubilee** [comment]
`c_char` is understood to mean `i8` in some cases, it is surprising this suggestion would be limited to `u8`, etc.

**Comment by Nilstrieb** [comment]
The diagnostic fires for raw pointers no matter the type behind it.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs [hunk 5]
```diff
@@ -1999,6 +1999,31 @@ impl<'tcx> TypeErrCtxt<'_, 'tcx> {
                         (ty::Bool, ty::Tuple(list)) => if list.len() == 0 {
                             self.suggest_let_for_letchains(&mut err, &trace.cause, span);
                         }
+                        // Suggest providing a std::ptr::null{,_mut}() if they pass in a 0 to an *{const,mut} uint
+                        (ty::RawPtr(ptr), ty::Uint(_))  => {
+                            if let Ok(code) = self.tcx.sess().source_map().span_to_snippet(span) {
+                                if let Ok(0) = code.parse::<u8>() {
```
[the remark this answers is not in the document]
Comment (edward-shen) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2005]: Is additional string parsing a good idea here?

We can discard all `_`, followed by then taking the subset of the str that excludes anything after an `i` or `u`, if one was present. That should handle all cases I can think of (`000_000`, `0_0usize` `0_0_iu32`, and parse already supports something like `"0000000000000"` parsing as a valid `u8`). Maybe this work has already been done somewhere?

Alternatively we can just leave that as potential future work -- after all I don't think it will be common that folks will pass in a prefixed numeric literal to an raw pointer argument.

**Comment by edward-shen** [comment]
Yeah, I think the commit name is better, let me update the PR name to better reflect the changes. Sorry for the confusion.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2011]: all that `FmtPrinter` stuff might be avoided with a call to `with_no_trimmed_paths!(tcx.def_path_str(null_def_id))`

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2011]: Also, this logic may better live in `FnCtxt::emit_type_mismatch_suggestions` (well, a method called from it). At that point, we should have access to the HIR expression that causes this mismatch. Then we can just check if it's a literal. 

Otherwise, I would personally not want to land this if we're doing that span_to_snippet + parsing. It seems pretty fragile.

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2011]: Alternatively, we could probably make `report_and_explain_type_error` to take an optional `Option<&'tcx hir::Expr<'tcx>>`, and use that here, bubbling it down from hir typeck. That's a much more intrusive change, though.

File: compiler/rustc_infer/src/infer/error_reporting/mod.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (WaffleLapkin) [reply compiler/rustc_infer/src/infer/error_reporting/mod.rs:2005]: it's more that I don't think that parsing `span_to_snippet` is a good idea at all, see @compiler-errors' comments: https://github.com/rust-lang/rust/pull/107553#discussion_r1093963499

**Comment by workingjubilee** [comment]
ferris clueless
Ope, my bad.

**Comment by edward-shen** [comment]
Changes:
 - Moved logic into a new function that is called by `FnCtxt::emit_type_mismatch_suggestions`
 - Cleaned up logic now that we have information about the HIR
 - Used `with_no_trimmed_paths` to print the diagnostic item instead.

**Review by WaffleLapkin — APPROVED** [review]
Thanks!
