### PR TITLE
Collapse multiple dead code warnings into a single diagnostic

### LINKED ISSUE #97643: Emit only one note per struct when multiple fields would trigger the same compiler note
Given the following code: 

```rust
#[derive(Debug)]
pub struct Whatever {
  pub field0: (),
  field1: (),
  field2: (),
  field3: (),
  field4: (),
}
```

The current output is:

```
warning: field is never read: `field1`
  --> src\cmake\preset.rs:23:3
   |
23 |   field1: (),
   |   ^^^^^^^^^^
   |
note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  --> src\cmake\preset.rs:20:10
   |
20 | #[derive(Debug)]
   |          ^^^^^
   = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: field is never read: `field2`
  --> src\cmake\preset.rs:24:3
   |
24 |   field2: (),
   |   ^^^^^^^^^^
   |
note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  --> src\cmake\preset.rs:20:10
   |
20 | #[derive(Debug)]
   |          ^^^^^
   = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: field is never read: `field3`
  --> src\cmake\preset.rs:25:3
   |
25 |   field3: (),
   |   ^^^^^^^^^^
   |
note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  --> src\cmake\preset.rs:20:10
   |
20 | #[derive(Debug)]
   |          ^^^^^
   = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: field is never read: `field4`
  --> src\cmake\preset.rs:26:3
   |
26 |   field4: (),
   |   ^^^^^^^^^^
   |
note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  --> src\cmake\preset.rs:20:10
   |
20 | #[derive(Debug)]
   |          ^^^^^
   = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

```

Ideally the output should look like:

```
warning: field is never read: `field1`
  --> src\cmake\preset.rs:23:3
   |
23 |   field1: (),
   |   ^^^^^^^^^^
   |

warning: field is never read: `field2`
  --> src\cmake\preset.rs:24:3
   |
24 |   field2: (),
   |   ^^^^^^^^^^
   |

warning: field is never read: `field3`
  --> src\cmake\preset.rs:25:3
   |
25 |   field3: (),
   |   ^^^^^^^^^^
   |

warning: field is never read: `field4`
  --> src\cmake\preset.rs:26:3
   |
26 |   field4: (),
   |   ^^^^^^^^^^
   |
note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
  --> src\cmake\preset.rs:20:10
   |
20 | #[derive(Debug)]
   |          ^^^^^
   = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

```

Or something even more compact if possible. Without this, compiler output is almost double, and mostly unnecessary.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #97643

### CODE REVIEW

File: compiler/rustc_passes/src/dead.rs [hunk 1]
```diff
@@ -787,22 +790,41 @@ impl<'tcx> Visitor<'tcx> for DeadVisitor<'tcx> {
...
     }
 
     fn visit_field_def(&mut self, field: &'tcx hir::FieldDef<'tcx>) {
         if self.should_warn_about_field(&field) {
-            self.warn_dead_code(field.hir_id, field.span, field.ident.name, "read");
+            debug!(?self.ignored_struct_def);
+            let struct_did = if let Some(parent_hir_id) = self.tcx.hir().find_parent_node(field.hir_id)
+                && let Some(parent_node) = self.tcx.hir().find(parent_hir_id)
+                && let Node::Item(hir::Item{kind: hir::ItemKind::Struct(..), ..}) = parent_node
+                && let Some(did) = self.tcx.hir().opt_local_def_id(parent_hir_id)
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:812]: I think you could move this logic to line 705, using the `id` parameter that already exists in that function. With that, you can get the hir parent (or maybe just get the hir owner), check if it's a struct, then do `ignored_struct_def.insert(did)`. That would avoid having to pass a `with_note: bool` parameter. Does that make sense?

Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:812]: I didn't take that approach because I thought `warn_dead_code` should not decide if a note should be emitted or not inside it but just emit warnings. Should I fixed it?

Comment (compiler-errors) [reply compiler/rustc_passes/src/dead.rs:812]: I think `warn_dead_code` already decides whether a note should be emitted or not, so modifying that condition further shouldn't be an issue. `warn_dead_code` also already takes `&mut self` too. :)

Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:812]: Understood. I will fix it.

File: compiler/rustc_passes/src/dead.rs [hunk 2]
```diff
@@ -722,6 +731,9 @@ impl<'tcx> DeadVisitor<'tcx> {
                         traits_str,
                         is_are
                     );
+                    if let Some(struct_def_id) = struct_def_id {
+                        self.ignored_struct_def.insert(struct_def_id);
+                    }
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:736]: after applying the change above, then:

```suggestion
```

File: compiler/rustc_passes/src/dead.rs [hunk 3]
```diff
@@ -802,6 +814,7 @@ impl<'tcx> Visitor<'tcx> for DeadVisitor<'tcx> {
 
     fn visit_field_def(&mut self, field: &'tcx hir::FieldDef<'tcx>) {
         if self.should_warn_about_field(&field) {
+            debug!(?self.ignored_struct_def);
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:817]: can you remove this?

File: compiler/rustc_passes/src/dead.rs [hunk 4]
```diff
@@ -274,10 +272,9 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
             Node::ImplItem(hir::ImplItem { def_id, .. }) => Some(def_id.to_def_id()),
             _ => None,
-        } {
-            if self.should_ignore_item(item_def_id) {
-                return;
-            }
+        } && self.should_ignore_item(item_def_id)
+        {
+            return;
         }
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:278]: this change is arguably harder to read/understand...

Comment (compiler-errors) [reply compiler/rustc_passes/src/dead.rs:278]: if you are going to change this, then please refactor it further, like:

```
match node {
  Node::ImplItem(..) if should_ignore() => return,
}
```

Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs]: I fixed it.

**Comment by compiler-errors** [comment]
Thanks for applying the changes I asked for, the code is much simpler now :tada:. But I'm not sure if I like how this renders -- I would prefer either continuing to be as verbose as we are now, or grouping all 4 of these diagnostics into one, i.e. "these fields are unused".

But I will defer to the reviewer to a call on whether this change is worth merging.

**Comment by TaKO8Ki** [comment]
@compiler-errors Thank you :) 

> grouping all 4 of these diagnostics into one, i.e. "these fields are unused".

That is a good idea. I will open an issue about that.

**Comment by davidtwco** [comment]
> @davidtwco I understand. I will fix warnings to collapse them into a single diagnostic. Should I implement it in this PR or a new one?

You can do either, feel free to update this or close it and open a new PR - whichever is easiest for you.

File: compiler/rustc_passes/src/dead.rs [hunk 5]
```diff
@@ -677,30 +677,91 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                ) => Some((*def_id, false)),
+                (
+                    Node::Variant(hir::Variant { data: hir::VariantData::Struct(..), id, .. }, ..),
+                    Node::Field(..),
+                ) => self
+                    .tcx
+                    .hir()
+                    .find_parent_node(*id)
+                    .and_then(|id| self.tcx.hir().opt_local_def_id(id).map(|id| (id, true))),
+                _ => None,
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:720]: Comment here would be nice. My understanding is that first case is struct/union fields, second case is enum variants, and third case is enum variant fields?

File: compiler/rustc_passes/src/dead.rs [hunk 6]
```diff
@@ -677,30 +677,91 @@ impl<'tcx> DeadVisitor<'tcx> {
...
     ) {
-        if !name.as_str().starts_with('_') {
-            self.tcx.struct_span_lint_hir(lint::builtin::DEAD_CODE, id, span, |lint| {
-                let def_id = self.tcx.hir().local_def_id(id);
-                let descr = self.tcx.def_kind(def_id).descr(def_id.to_def_id());
-                let mut err = lint.build(&format!("{} is never {}: `{}`", descr, participle, name));
-                let hir = self.tcx.hir();
-                if let Some(encl_scope) = hir.get_enclosing_scope(id)
+        if let Some((id, _, name)) = dead_codes.first()
+            && !name.as_str().starts_with('_')
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:743]: Why is this just checking `.first`?

File: compiler/rustc_passes/src/dead.rs [hunk 7]
```diff
@@ -677,30 +677,91 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+            }
+        };
+        if let Some(parent_hir_id) = self.tcx.hir().find_parent_node(id)
+            && let Some(parent_node) = self.tcx.hir().find(parent_hir_id)
+            && let Some(node) = self.tcx.hir().find(id)
+            && let Some((did, is_field)) = field_or_variant_local_def_id(parent_node, node)
+            && !name.as_str().starts_with('_')
+        {
+            if is_field {
+                self.dead_fields.entry(did).or_default().push((id, span, name));
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:730]: These are accumulated in a member that is (I think?) shared for all of the items in a module, but what happens when we have two structs both with dead fields? Does that mess with the diagnostics?

```rust
struct A {
  a: i32,
}

struct B {
  b: i32,
}

File: compiler/rustc_passes/src/dead.rs [hunk 8]
```diff
@@ -164,10 +164,9 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
                     if let (Res::Local(id_l), Res::Local(id_r)) = (
                         typeck_results.qpath_res(qpath_l, lhs.hir_id),
                         typeck_results.qpath_res(qpath_r, rhs.hir_id),
-                    ) {
-                        if id_l == id_r {
-                            return true;
-                        }
+                    ) && id_l == id_r
```
Comment (compiler-errors) [inline compiler/rustc_passes/src/dead.rs:167]: Side-note: difficult to tell what is meaningful code change with all of these tiny codemods everywhere in this file :/

File: compiler/rustc_passes/src/dead.rs (hunk 7 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:730]: In this case, warning looks like the following.

```
error: field is never read: `a`
 --> src/main.rs:5:5
  |
5 |     a: i32,
  |     ^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:11
  |
1 | #![forbid(dead_code)]
  |           ^^^^^^^^^
  = note: `A` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

error: field is never read: `b`
  --> src/main.rs:10:5
   |
10 |     b: i32,
   |     ^^^^^^
   |
   = note: `B` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

error: could not compile `debug_playground` due to 2 previous errors
```

Comment (compiler-errors) [reply compiler/rustc_passes/src/dead.rs:730]: oh, didn't notice it was a `Map<DefId, Vec<HirId>>`

File: compiler/rustc_passes/src/dead.rs (hunk 8 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:167]: I forgot reverting this change.

File: compiler/rustc_passes/src/dead.rs (hunk 6 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:743]: The first dead_code's `hir_id` is used as an argument of `struct_span_lint_hir` and `name` is used in an error message when `dead_codes` has a single element. Do you think this should check if all dead codes have the same `DefKind`?

File: compiler/rustc_passes/src/dead.rs (hunk 5 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:724]: I added comments.

File: compiler/rustc_passes/src/dead.rs [hunk 9]
```diff
@@ -677,30 +678,94 @@ impl<'tcx> DeadVisitor<'tcx> {
...
         span: rustc_span::Span,
         name: Symbol,
+    ) {
+        let field_or_variant_local_def_id = |parent_node, node| -> Option<(LocalDefId, bool)> {
+            match (parent_node, node) {
+                // struct/union fields
+                (
+                    Node::Item(hir::Item {
+                        kind:
+                            hir::ItemKind::Struct(hir::VariantData::Struct(..), ..)
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:703]: Why not `Tuple` fields too?

File: compiler/rustc_passes/src/dead.rs [hunk 10]
```diff
@@ -630,6 +629,8 @@ struct DeadVisitor<'tcx> {
     tcx: TyCtxt<'tcx>,
     live_symbols: &'tcx FxHashSet<LocalDefId>,
     ignored_derived_traits: &'tcx FxHashMap<LocalDefId, Vec<(DefId, DefId)>>,
+    dead_fields: FxHashMap<LocalDefId, Vec<(hir::HirId, Span, Symbol)>>,
+    dead_variants: FxHashMap<LocalDefId, Vec<(hir::HirId, Span, Symbol)>>,
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:633]: Why store fields and variants separately?

File: compiler/rustc_passes/src/dead.rs [hunk 11]
```diff
@@ -677,30 +678,94 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                // enum variants
+                (
+                    Node::Item(hir::Item { kind: hir::ItemKind::Enum(..), def_id, .. }),
+                    Node::Variant(..),
+                ) => Some((*def_id, false)),
+                // variant fields
+                (
+                    Node::Variant(hir::Variant { data: hir::VariantData::Struct(..), id, .. }, ..),
+                    Node::Field(..),
+                ) => self
```
Comment (cjgillot) [inline compiler/rustc_passes/src/dead.rs:719]: `Some((id.owner, true))` should do the trick.

File: compiler/rustc_passes/src/dead.rs (hunk 6 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:747]: > What happens if one of the variants allows the lint?

Given the following code:
```rust
#[derive(Debug)]
pub struct Whatever {
    pub field0: (),
    field1: (), //~ERROR these fields are never read
    field2: (),
    #[allow(dead_code)]
    field3: (),
    field4: (),
}
```
The current output is:
```
warning: these fields are never read
 --> src/main.rs:4:5
  |
4 |     field1: (), //~ERROR these fields are never read
  |     ^^^^^^^^^^
5 |     field2: (),
  |     ^^^^^^^^^^
...
8 |     field4: (),
  |     ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
  = note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
```

Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:747]: > What happens if the first variant allows the lint?

Given the following code:
```
#[derive(Debug)]
pub struct Whatever {
    #[allow(dead_code)]
    field1: (), //~ERROR these fields are never read
    field2: (),
    field3: (),
    field4: (),
}
```

The current output is:
```rust
warning: these fields are never read
 --> src/main.rs:5:5
  |
5 |     field2: (),
  |     ^^^^^^^^^^
6 |     field3: (),
  |     ^^^^^^^^^^
7 |     field4: (),
  |     ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
  = note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
```

Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:747]: > What happens if the second variant forbids the lint?

However, the last case has the following problem, which I will correct later.

Given the following code:

```rust
#[derive(Debug)]
pub struct Whatever {
    field1: (), //~ERROR these fields are never read
    #[forbid(dead_code)]
    field2: (),
    field3: (),
    field4: (),
}
```

The current output is:

```
warning: these fields are never read
 --> src/main.rs:3:5
  |
3 |     field1: (), //~ERROR these fields are never read
  |     ^^^^^^^^^^
4 |     #[forbid(dead_code)]
5 |     field2: (),
  |     ^^^^^^^^^^
6 |     field3: (),
  |     ^^^^^^^^^^
7 |     field4: (),
  |     ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
  = note: `Whatever` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
```

File: compiler/rustc_passes/src/dead.rs (hunk 11 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs]: I fixed it.

File: compiler/rustc_passes/src/dead.rs (hunk 6 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:748]: I fixed this problem in https://github.com/rust-lang/rust/pull/97853/commits/194df3ec8cce584903238f104a02d82ee076f91f.

File: compiler/rustc_passes/src/dead.rs (hunk 9 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:712]: That is because rustc does not warn about tuple fields (positional fields) like the following if I am not wrong.

https://github.com/rust-lang/rust/blob/20ad8209288896259cd1829d2b057bc017315fce/compiler/rustc_passes/src/dead.rs#L653

**Comment by cjgillot** [comment]
I really have a lot of doubts about this change.  This brings a lot of additional complexity, manually re-implements some of the lint handling infrastructure, and makes testing more brittle since we can't annotate the whole list of unused fields any more.

I'd see such complexity much more keenly if they were making the lint more precise.

As we already stopped pointing to the ignored trait derives, half of the output in https://github.com/rust-lang/rust/issues/97643 is gone.  I'm a bit tempted to close the issue and this PR.

Other possibility: could such merging of lints be done at the level of the diagnostic infrastructure itself?  (It's a naive question, I don't know that code at all.)  This would allow to keep a low complexity in the analysis itself, and have the support code handle it, and maybe be much easier to extend to other verbose lints.

**Comment by TaKO8Ki** [comment]
@cjgillot Thank you for your review! I would like to know what others think about. @rust-lang/wg-diagnostics

**Comment by compiler-errors** [comment]
> As we already stopped pointing to the ignored trait derives, half of the output in https://github.com/rust-lang/rust/issues/97643 is gone.

I actually was unaware that the more verbose output had already been mostly suppressed for a much shorter note somewhere between stable and nightly. 

In that case, I actually probably agree with @cjgillot that this is a lot of overhead for suppressing just a few lines of diagnostics.

**Comment by davidtwco** [comment]
> @cjgillot Thank you for your review! I would like to know what the others think about.

Thanks for your work on this @TaKO8Ki, I appreciate it has been a lot of changes and rework. I prefer the error after these changes. It is a lot more code and complexity though, so I understand the concerns there.

> Other possibility: could such merging of lints be done at the level of the diagnostic infrastructure itself? (It's a naive question, I don't know that code at all.) This would allow to keep a low complexity in the analysis itself, and have the support code handle it, and maybe be much easier to extend to other verbose lints.

I don't think this would be particularly practical to do.

**Comment by TaKO8Ki** [comment]
@davidtwco
Thank you! If this patch is not worth being merged, please feel free to close it and the issue. 👍

File: compiler/rustc_passes/src/dead.rs [hunk 12]
```diff
@@ -724,10 +790,58 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                        | hir::ItemKind::Enum(..),
+                    ..
+                })
+            )
+            && let Some(did) = self.tcx.hir().opt_local_def_id(hir_id)
+            && let Some(dead_codes) = self.dead_variants.get(&did)
+        {
+            let mut dead_codes = dead_codes
+                .iter()
+                .filter(|v| v.is_field == is_field)
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:815]: Should the `_` prefix checking be done here? Then that check can be removed from `warn_multiple_dead_codes`

File: compiler/rustc_passes/Cargo.toml [hunk 13]
```diff
@@ -5,6 +5,7 @@ edition = "2021"
 
 [dependencies]
 tracing = "0.1"
+itertools = "0.10.1"
```
Comment (estebank) [inline compiler/rustc_passes/Cargo.toml:8]: I'm failing to see where itertools is being used now, is still necessary after the previous rounds of reviews?

File: src/test/ui/lint/dead-code/multiple-dead-codes-in-the-same-struct.rs [hunk 14]
```diff
@@ -0,0 +1,18 @@
...
+    #[allow(dead_code)]
+    a: usize,
+    #[forbid(dead_code)]
+    b: usize, //~ ERROR field is never read: `b`
+    #[deny(dead_code)]
+    c: usize, //~ ERROR these fields are never read
+    d: usize, //~ WARN these fields are never read
+    #[deny(dead_code)]
+    e: usize,
+    f: usize,
```
Comment (estebank) [inline src/test/ui/lint/dead-code/multiple-dead-codes-in-the-same-struct.rs:13]: Can we add a `_g` field here?

File: compiler/rustc_passes/src/dead.rs [hunk 15]
```diff
@@ -677,30 +686,87 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                    let def_id = self.tcx.hir().local_def_id(*id);
+                    let descr = self.tcx.def_kind(def_id).descr(def_id.to_def_id());
+                    let span_len = dead_codes.len();
+                    let mut err = lint.build(&format!(
+                        "{these}{descr}{s} {are} never {participle}{name}",
+                        these = if span_len > 1 { "these " } else { "" },
+                        s = pluralize!(span_len),
+                        are = pluralize!("is", span_len),
+                        name = if span_len > 1 { String::new() } else { format!(": `{name}`") },
+                    ));
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:766]:
```suggestion
                    let mut err = lint.build(&format!(
                        "{these}{descr}{s} {names}{are} never {participle}",
                        these = if span_len > 6 { "multiple " } else { "" },
                        s = pluralize!(span_len),
                        names = match dead_codes.iter().map(|(_, _, n)| format!("{n}")).collect::<Vec<_>>() {
                            _ if span_len > 6 => String::new(),
                            [name] => format!("{name} "),
                            [] => unreachable!(),
                            [names.., last] => format!("{} and {last} ", names.join(", "),
                        },
                        are = pluralize!("is", span_len),
                    ));
```

You can simplify by removing the len check for over 6 cases.

Comment (estebank) [reply compiler/rustc_passes/src/dead.rs:766]: If we include the ident for the type, we could also add that context to the message:

```
warning: fields `a` and `b` in struct `Foo` are never read
  --> $DIR/issue-85255.rs:7:5
   |
LL | struct Foo {
   |        --- fields in this struct
LL |     a: i32,
   |     ^^^^^^
LL |     pub b: i32,
   |     ^^^^^^^^^^
   |
note: the lint level is defined here
  --> $DIR/issue-85255.rs:4:9
   |
LL | #![warn(dead_code)]
   |         ^^^^^^^^^
```

**Comment by estebank** [comment]
Left some nitpicks, but love the direction

**Comment by estebank** [comment]
> Other possibility: could such merging of lints be done at the level of the diagnostic infrastructure itself? (It's a naive question, I don't know that code at all.) This would allow to keep a low complexity in the analysis itself, and have the support code handle it, and maybe be much easier to extend to other verbose lints.

That should be theoretically possible, but the linting machinery is somewhat obtuse at the moment and less flexible than dealing with the `DiagnosticBuilder` directly.

> this is a lot of overhead for suppressing just a few lines of diagnostics.

Not to be contrarian, but that's what we always end up doing: adding a lot of code for somewhat marginal improvements. We should absolutely clean up our code, reduce duplication (I think I write code to make lists of ` wrapped names more often than I get out of the house) and increase maintainability over time, but I am against using "this adds some cost" as a baton to hit people over the head with. Code is written and rewritten a lot, there's maintenance cost, but *not* doing something because it has a cost to us is doing a disservice to our users. At the very least we should land the changes that make us now use let chains (which improves maintainability!).

I'm rereading the patch, and honestly I don't see *that* much extra code over what we had (when only looking at the semantic changes), beyond tracking more context and ferrying it around in a new field/Vec.

File: compiler/rustc_passes/src/dead.rs [hunk 16]
```diff
@@ -724,10 +790,58 @@ impl<'tcx> DeadVisitor<'tcx> {
...
-                err.emit();
-            });
+                    err.emit();
+                },
+            );
+        }
+    }
+
+    fn warn_dead_fields_and_variants(&self, hir_id: hir::HirId, participle: &str, is_field: bool) {
+        if let Some(parent_node) = self.tcx.hir().find(hir_id)
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:800]: Instead of looking at the parent, why don't we pass it in? It seems like that you already have the item's info in the visitor.

File: compiler/rustc_passes/src/dead.rs [hunk 17]
```diff
@@ -724,10 +790,58 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+            let mut dead_codes = dead_codes
+                .iter()
+                .filter(|v| v.is_field == is_field)
+                .map(|v| v)
+                .collect::<Vec<&DeadVariant>>();
+            if dead_codes.is_empty() {
+                return
+            }
+            dead_codes.sort_by_key(|v| v.level);
+            for (_, group) in &dead_codes.into_iter().group_by(|v| v.level) {
```
Comment (TaKO8Ki) [inline compiler/rustc_passes/src/dead.rs:822]: This line uses `group_by` in `itertools`.

File: compiler/rustc_passes/Cargo.toml (hunk 13 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/Cargo.toml:8]: `group_by` in `itertools` is used for grouping dead_codes by their log levels.

ref: https://github.com/rust-lang/rust/pull/97853/files#r898454245

File: Cargo.lock [hunk 18]
```diff
@@ -4643,9 +4644,9 @@ dependencies = [
 
 [[package]]
 name = "rustfix"
-version = "0.6.1"
+version = "0.6.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "ecd2853d9e26988467753bd9912c3a126f642d05d229a4b53f5752ee36c56481"
+checksum = "6f0be05fc0675ef4f47119dc39cfc46636bb77d4fc4ef1bd851b9c3f7697f32a"
```
Comment (klensy) [inline Cargo.lock:4649]: This and sysinfo looks unrelated.

File: src/test/ui/lint/dead-code/multiple-dead-codes-in-the-same-struct.rs (hunk 14 above)
Comment (TaKO8Ki) [reply src/test/ui/lint/dead-code/multiple-dead-codes-in-the-same-struct.rs:13]: I added it!

File: compiler/rustc_passes/src/dead.rs (hunk 15 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs]: I added the label to the ident.span!

File: compiler/rustc_passes/src/dead.rs (hunk 12 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs]: Previously, `store_dead_field_or_variant` does it, but I moved the checking to `warn_dead_fields_and_variants`.

File: Cargo.lock (hunk 18 above)
Comment (estebank) [reply Cargo.lock:4649]: @TaKO8Ki if this change and the one below are removed, does rustc still compile? If so, lets avoid not completely necessary changes :)

File: compiler/rustc_passes/src/dead.rs [hunk 19]
```diff
@@ -251,33 +251,33 @@ impl<'tcx> MarkSymbolVisitor<'tcx> {
...
-        } {
-            if self.should_ignore_item(item_def_id) {
+        match node {
+            Node::ImplItem(hir::ImplItem { def_id, .. })
+                if self.should_ignore_item(def_id.to_def_id()) =>
+            {
                 return;
             }
+            _ => (),
         }
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:281]: This can be an if let chain, right?

```suggestion
        if let Node::ImplItem(hir::ImplItem { def_id, .. }) = node
                && self.should_ignore_item(def_id.to_def_id()) =>
        {
            return;
        }
```

File: compiler/rustc_passes/src/dead.rs [hunk 20]
```diff
@@ -677,57 +686,178 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                    Node::Variant(hir::Variant { data: hir::VariantData::Struct(..), id, .. }, ..),
+                    Node::Field(..),
+                ) => Some((id.owner, true)),
+                _ => None,
+            }
+        };
+        if let Some(parent_hir_id) = self.tcx.hir().find_parent_node(id)
+            && let Some(parent_node) = self.tcx.hir().find(parent_hir_id)
+            && let Some(node) = self.tcx.hir().find(id)
+            && let Some((did, is_field)) = field_or_variant_local_def_id(parent_node, node)
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:732]: Instead of doing this, why don't we modify the visitor to *not* call this function from the variant and field visits, but rather from the type visitor so that we *don't* need to look for the parent item, we pass it in.

File: compiler/rustc_passes/src/dead.rs [hunk 21]
```diff
@@ -780,14 +910,30 @@ impl<'tcx> Visitor<'tcx> for DeadVisitor<'tcx> {
...
-            self.warn_dead_code(variant.id, variant.span, variant.ident.name, "constructed");
+            self.store_dead_field_or_variant(
+                variant.id,
+                variant.span,
+                variant.ident.name,
+                self.tcx.lint_level_at_node(lint::builtin::DEAD_CODE, id).0,
+            );
         } else {
             intravisit::walk_variant(self, variant, g, id);
         }
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:936]: It would mean modifying `visit_variant` here so it doesn't call `store_dead_field_or_variant`, and modify `visit_enum_def` to look at the enum's variants itself and call `store_dead_field_or_variant` there while passing in the enum def. Same thing for `visit_field_def` (which would likely require more changes, as more things have fields).

Maybe instead modify the visitor itself to hold "current item being visited", instead of passing it as an arg in `store_dead_field_or_variant`?

**Comment by estebank** [comment]
@davidtwco @cjgillot do you have thoughts on what I've said up-thread? I'm personally leaning towards landing this (after the nitpick about avoiding querying for the parent node), but I'm not the reviewer original and would love you to push back if you think I'm wrong in my position.

**Comment by compiler-errors** [comment]
I'm also okay with landing this, though I would really like for the commits to get squashed so we don't have three "fix a ui test" commits in the commit history forever :stuck_out_tongue_closed_eyes:

File: compiler/rustc_passes/src/dead.rs (hunk 21 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs:936]: Is it like this?

```rust
fn visit_enum_def(
        &mut self,
        enum_definition: &'tcx hir::EnumDef<'tcx>,
        generics: &'tcx hir::Generics<'tcx>,
        item_id: hir::HirId,
        _: Span,
) {
    intravisit::walk_enum_def(self, enum_definition, generics, item_id);
    let dead_variants = enum_definition.variants
        .iter().filter(|variant| self.should_warn_about_variant(&variant)
        .map(|variant| DeadVariant {
            hir_id: variant.id,
            span: variant.span,
            name: variant.ident.name,
            level: self.tcx.lint_level_at_node(lint::builtin::DEAD_CODE, id).0,
            is_field: false,
        });
    self.warn_dead_fields_and_variants(item_id, "constructed", dead_variants)
}
```

**Comment by TaKO8Ki** [comment]
After the review, I will squash my commits.

File: compiler/rustc_passes/src/dead.rs (hunk 21 above)
Comment (TaKO8Ki) [reply compiler/rustc_passes/src/dead.rs]: I refactored.

**Comment by davidtwco** [comment]
> @davidtwco @cjgillot do you have thoughts on what I've said up-thread? I'm personally leaning towards landing this (after the nitpick about avoiding querying for the parent node), but I'm not the reviewer original and would love you to push back if you think I'm wrong in my position.

I'm okay with landing this. I agree with your comment, I think diagnostic improvements are worth landing despite some increases in code complexity. 

I'm just cautious that there's a trade-off here, every bit of complexity we add for improved diagnostics makes refactorings and improvements in the compiler more difficult for the team members who are working on those areas, and I think it's important that we do something to address that so that - as much as is possible - everyone is in favour of improving our diagnostics.

**Comment by cjgillot** [comment]
> @davidtwco @cjgillot do you have thoughts on what I've said up-thread? I'm personally leaning towards landing this (after the nitpick about avoiding querying for the parent node), but I'm not the reviewer original and would love you to push back if you think I'm wrong in my position.

I also agree that improving diagnostics is worth increasing the complexity.  That's what made diagnostics one of the best features for rustc :smile:.  I had doubts with the tradeoff in this case, but since several people agree that this PR is worth it, let's go.
After re-reading the code, it seems simple enough, so I retract my objection.

Once this PR is merged, I will probably look again to the pass.  I think there are refactor opportunities, for instance to avoid traversing the crate twice (once to mark symbols live, and once to diagnose them dead).

File: compiler/rustc_passes/src/dead.rs [hunk 22]
```diff
@@ -677,56 +681,127 @@ impl<'tcx> DeadVisitor<'tcx> {
...
+                ),
+                |lint| {
+                    let def_id = self.tcx.hir().local_def_id(*id);
+                    let descr = self.tcx.def_kind(def_id).descr(def_id.to_def_id());
+                    let span_len = dead_codes.len();
+                    let names = match &dead_codes.iter().map(|(_, _, n)| n.to_string()).collect::<Vec<_>>()[..]
+                    {
+                        _ if span_len > 6 => String::new(),
+                        [name] => format!("`{name}` "),
+                        [names @ .., last] => format!("`{}` and `{last}` ", names.join(", ")),
```
Comment (estebank) [inline compiler/rustc_passes/src/dead.rs:717]: Tiny bug here: this would look like

    `a, b, c` and `d`

which is not what we want. You can probably instead surround the names with backticks in the map on line 713.

**Comment by estebank** [comment]
I'm ok with the current changes, modulo the squashing and the small fix to the output of messages with lists of more than 2 elements.

**Comment by TaKO8Ki** [comment]
@estebank 
I fixed the bug and squashed my commits!

**Comment by TaKO8Ki** [comment]
I opened two PRs to fix this errors in CI.

- https://github.com/rust-lang/rls/pull/1780
- https://github.com/rust-lang/cargo/pull/10768

**Comment by TaKO8Ki** [comment]
@estebank 
Could you review again? ref: https://github.com/rust-lang/rust/pull/97853#issuecomment-1159675128

**Comment by TaKO8Ki** [comment]
@ehuss Ok. I understand. I appreciate your help.

**Comment by estebank** [comment]
@ehuss apologies for the breakdown of process.

**Comment by RalfJung** [comment]
This also changed the rls submodule to a commit not in the rls repo (https://github.com/rust-lang/rls/tree/27f4044df03d15c7c38a483c3e4635cf4f51807d), which means currently I cannot build rustc locally since it fails to fetch that commit.

**Comment by RalfJung** [comment]
Can this PR be reverted to get the repo into a state again where its submodules point to existing commits?

**Comment by TaKO8Ki** [comment]
@RalfJung Wouldn't merging this pull request solve this provlem? https://github.com/rust-lang/rls/pull/1780

**Comment by RalfJung** [comment]
Maybe, but when a PR has unintended side-effects the right reaction is to back it out and try again -- not to hurry and land some fix in a haste.

**Comment by RalfJung** [comment]
Don't worry, we *do* want to have your PR. :)  We just want to make sure that it doesn't break anything else, and (due to no fault of yours -- the process should have caught this) this PR caused more trouble than it should. I know seeing one's PR reverted can be frustrating, but this is really just a temporary thing, and then we have all the time we need to figure out how to land this properly without causing trouble.

**Comment by Mark-Simulacrum** [comment]
OK, I've now posted branches to both rust-lang/cargo and rust-lang/rls to preserve the wrongly-introduced commits for the future; that will likely already fix the submodule updates (but I have no confirmation as of this commit from users reporting breakage).

We've already bumped Cargo since this PR in #98395, which moved us back onto Cargo master.

I've also posted https://github.com/rust-lang/rust/pull/98488 to move us back onto RLS master, and nominated for beta backport (to the beta branching next week; i.e., 1.63).

I believe that should resolve the problem here and avoid a revert which would've been annoying to backport to 1.63 and such.

**Comment by TaKO8Ki** [comment]
@RalfJung Thanks. Is there anything I can help?
