### PR TITLE
rustc_typeck: unify expected return types with formal return types to propagate coercions through calls of generic functions.

### LINKED ISSUE #20178: Fn item/fn pointer distinction breaks fn pointer generics
This is broken now:
```rust
fn accepts_optional_fn_ptr(_test: Option<fn(int) -> int>) {}
 
fn test_int(_: int) -> int { 0i }
 
fn main() {
    accepts_optional_fn_ptr(Some(test_int));
}
```
because it expects `Option<fn(int) -> int>` and gets `Option<fn(int) -> int {test_int}>`

This is an issue for FFI specifically because `Option<fn(...) -> ...>` is the idiomatic way (mentioned in the FFI guide) to represent C function pointers as it takes advantage of nullable pointer optimization.

I'll add that for anyone encountering this issue, an explicit cast fixes it:
```rust
accepts_optional_fn_ptr(Some(test_int as fn(int) -> int));
```

### PR DESCRIPTION
**Pull request by eddyb**
This allows passing `Some(free_fn)` to something expecting `Option<fn()>`, dealing with most of the fallout from #19891.
Fixes #20178.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
assigning myself as reviewer

**Comment by nikomatsakis** [comment]
This looks really nice but not quite there. Look at what I wrote and let me know if you have questions.

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3005,6 +3045,38 @@ enum TupleArgumentsFlag {
...
+                                        formal_ret: ty::FnOutput<'tcx>,
+                                        formal_args: &[Ty<'tcx>])
+                                        -> Vec<Ty<'tcx>> {
+    // Unify the return type with the expected type early, for more coercions.
+    let expected_args = expected_ret.only_has_type(fcx).and_then(|ret_ty| {
+        if let ty::FnConverging(formal_ret_ty) = formal_ret {
+            fcx.infcx().probe(|_| {
+                use rustc::middle::infer::combine::Combine;
+                let trace = infer::TypeTrace::dummy(fcx.tcx());
+                match fcx.infcx().equate(false, trace).tys(ret_ty, formal_ret_ty) {
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: One last comment: I'd rather not see the `Combine` trait used outside of `infer`. You can just invoke `infer::mk_eqty()` instead, it's equivalent and shorter.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: (Better yet, move it to a method :)

Comment (eddyb) [inline src/librustc_typeck/check/mod.rs]: It's not equivalent, what I have here could be `with_eqty` or `resolve_with_eqty`.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: in what way is it not equivalent? it looks equivalent to me.

Comment (eddyb) [inline src/librustc_typeck/check/mod.rs]: I execute code in the `Ok` case, before rolling back the snapshot, while `mk_eqty` would commit it. Unless you mean it's okay to have nested snapshots like this, in which case I have to wonder what the cost is.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: It is fine to have nested snapshots and the cost is nothing.

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: Commit within a nested snapshot in particular is basically a no-op.

**Comment by eddyb** [comment]
I've switched back to subtyping and used a modified version of `commit_if_ok` that commits region vars (which can be created during subtyping) but discards the type bindings (which could be incorrect and are only usable for expectations).

File: src/librustc/middle/infer/mod.rs [hunk 2]
```diff
@@ -613,6 +613,36 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
         self.commit_unconditionally(move || self.try(move |_| f()))
     }
 
+    /// Execute `f` and commit the region bindings if successful
```
Comment (nikomatsakis) [inline src/librustc/middle/infer/mod.rs]: We probably want a more detailed comment here. "...commit only the region bindings if successful. The function `f` must be very careful not to leak any non-region variables that get created."

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -2990,6 +3031,35 @@ enum TupleArgumentsFlag {
...
+                                        expected_ret: Expectation<'tcx>,
+                                        formal_ret: ty::FnOutput<'tcx>,
+                                        formal_args: &[Ty<'tcx>])
+                                        -> Vec<Ty<'tcx>> {
+    // Unify the return type with the expected type early, for more coercions.
+    let expected_args = expected_ret.only_has_type(fcx).and_then(|ret_ty| {
+        if let ty::FnConverging(formal_ret_ty) = formal_ret {
+            fcx.infcx().commit_regions_if_ok(|| {
+                let origin = infer::Misc(call_span);
+                fcx.infcx().sub_types(false, origin, formal_ret_ty, ret_ty).map(|_| {
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: can we do `let () = try!(fcx.infcx().sub_types(false, origin, formal_ret_ty, ret_ty));`

Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: (it's a total nit; I just find the deep nesting hard to read)

**Comment by nikomatsakis** [comment]
@eddyb ok I have to admit, I have my reservations but this looks pretty nice.

r+ modulo nits (and maybe a cleaned up commit history?)

File: src/librustc_typeck/check/mod.rs [hunk 4]
```diff
@@ -2750,7 +2773,25 @@ fn check_argument_types<'a, 'tcx>(fcx: &FnCtxt<'a, 'tcx>,
                     AutorefArgs::No => {}
                 }
 
-                check_expr_coercable_to_type(fcx, &***arg, formal_ty);
+                // The special-cased logic below has three functions:
+                // 1. Provide as good of an expectated type as possible.
```
Comment (Ms2ger) [inline src/librustc_typeck/check/mod.rs]: "expected type"
