### PR TITLE
Handle `impl Trait` where `Trait` has an assoc type with missing bounds

### LINKED ISSUE #69638: Suggestions for refining `impl Trait` argument are invalid Rust code
```rust
fn check(constraints: impl Iterator) {
    for constraint in constraints {
        println!("{:?}", constraint);
    }
}

fn main() {}
```
This yields the error message:
```
error[E0277]: `<impl Iterator as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
 --> src/main.rs:3:26
  |
1 | fn check(constraints: impl Iterator) {
  |                                     - help: consider further restricting the associated type: `where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug`
2 |     for constraint in constraints {
3 |         println!("{:?}", constraint);
  |                          ^^^^^^^^^^ `<impl Iterator as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator as std::iter::Iterator>::Item`
  = note: required by `std::fmt::Debug::fmt`

error: aborting due to previous error
```
If I add `where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug` to the function declaration, I receive:
```
error[E0667]: `impl Trait` is not allowed in path parameters
 --> src/main.rs:2:8
  |
2 | where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug
  |        ^^^^^^^^^^^^^

error[E0562]: `impl Trait` not allowed outside of function and inherent method return types
 --> src/main.rs:2:8
  |
2 | where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug
  |        ^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by estebank**
When encountering a type parameter that needs more bounds the trivial case is `T` `where T: Bound`, but it can also be an `impl Trait` param that needs to be decomposed to a type param for cleaner code. For example, given

```rust
fn foo(constraints: impl Iterator) {
    for constraint in constraints {
        println!("{:?}", constraint);
    }
}
```

the previous output was

```
error[E0277]: `<impl Iterator as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
 --> src/main.rs:3:26
  |
1 | fn foo(constraints: impl Iterator) {
  |                                    - help: consider further restricting the associated type: `where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug`
2 |     for constraint in constraints {
3 |         println!("{:?}", constraint);
  |                          ^^^^^^^^^^ `<impl Iterator as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator as std::iter::Iterator>::Item`
  = note: required by `std::fmt::Debug::fmt`
```

which is incorrect as `where <impl Iterator as std::iter::Iterator>::Item: std::fmt::Debug` is not valid syntax nor would it restrict the positional `impl Iterator` parameter if it were.

The output being introduced is

```
error[E0277]: `<impl Iterator as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
 --> src/main.rs:3:26
  |
3 |         println!("{:?}", constraint);
  |                          ^^^^^^^^^^ `<impl Iterator as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator as std::iter::Iterator>::Item`
  = note: required by `std::fmt::Debug::fmt`
help: introduce a type parameter with a trait bound instead of using `impl Trait`
   |
LL | fn foo<T: Iterator>(constraints: T) where <T as std::iter::Iterator>::Item: std::fmt::Debug  {
   |       ^^^^^^^^^^^^^              ^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This suggestion is correct and lead the user in the right direction: because you have an associated type restriction you can no longer use `impl Trait`, the only reasonable alternative is to introduce a named type parameter, bound by `Trait` and with a `where` binding on the associated type for the new type parameter `as Trait` for the missing bound.

*Ideally*, we would want to suggest something like the following, but that is not valid syntax today

```
error[E0277]: `<impl Iterator as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
 --> src/main.rs:3:26
  |
3 |         println!("{:?}", constraint);
  |                          ^^^^^^^^^^ `<impl Iterator as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator as std::iter::Iterator>::Item`
  = note: required by `std::fmt::Debug::fmt`
help: introduce a type parameter with a trait bound instead of using `impl Trait`
   |
LL | fn foo(constraints: impl Iterator<Item: std::fmt::Debug>) {
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Fix #69638.

### CODE REVIEW

**Comment by estebank** [comment]
This will require discussion/approval of the lang team.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
         };
 
         let suggest_restriction =
-            |generics: &hir::Generics<'_>, msg, err: &mut DiagnosticBuilder<'_>| {
+            |generics: &hir::Generics<'_>,
+             msg,
+             err: &mut DiagnosticBuilder<'_>,
+             fn_sig: Option<&hir::FnSig<'_>>| {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:166]: Let's make this a method now since it's large enough.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
             };
 
         // FIXME: Add check for trait bound that is already present, particularly `?Sized` so we
         //        don't suggest `T: Sized + ?Sized`.
         let mut hir_id = body_id;
         while let Some(node) = self.tcx.hir().find(hir_id) {
+            debug!(
+                "suggest_restricting_param_bound {:?} {:?} {:?} {:?}",
+                trait_ref, self_ty.kind, projection, node
+            );
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:290]: I don't think leaving in `debug!(...)`s is valuable in general beyond this PR. Let's clean it up before landing.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 3]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
-                                ","
-                            } else {
-                                " where"
+                    // Given `fn foo(t: impl Trait)` where `Trait` requires assoc type `A`...
+                    if let Some((name, fn_sig)) = fn_sig.and_then(|sig| {
+                        projection.and_then(|p| {
+                            // Shenanigans to get the `Trait` from the `impl Trait`.
+                            match p.self_ty().kind {
+                                ty::Param(param) if param.name.as_str().starts_with("impl ") => {
+                                    let n = param.name.as_str();
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:178]:
```suggestion
                                    let trait_str = param.name.as_str().strip_prefix("impl").trim_start();
```

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 4]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                                    .span_for_predicates_or_empty_place()
+                                    .shrink_to_hi(),
+                                format!(
+                                    "{} {} ",
+                                    if !generics.where_clause.predicates.is_empty() {
+                                        ","
+                                    } else {
+                                        " where"
+                                    },
+                                    pred,
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:248]: This is duplicated below, dedup with a closure (taking `pred` as a parameter).

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 5]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                    kind: hir::ImplItemKind::Fn(fn_sig, ..),
                     ..
                 })
-                | hir::Node::Item(
-                    hir::Item { kind: hir::ItemKind::Fn(_, generics, _), .. }
-                    | hir::Item { kind: hir::ItemKind::Trait(_, _, generics, _, _), .. }
+                | hir::Node::Item(hir::Item {
+                    kind: hir::ItemKind::Fn(fn_sig, generics, _), ..
+                }) if projection.is_some() => {
+                    // Missing associated type bound.
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:315]: What do you mean by this comment? This isn't related to `#![feature(associated_type_bounds)]` is it? (also, I should work towards getting this to stable so fewer hacks are necessary here)

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (Centril) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:178]: Also, there has to be a cleaner, less stringy way to extract this info... :( cc @eddyb

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 6]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                                        .map(|n| (n.to_string(), sig))
+                                }
+                                _ => None,
+                            }
+                        })
+                    }) {
+                        // FIXME: Cleanup.
+                        let mut ty_spans = vec![];
+                        let impl_name = format!("impl {}", name);
+                        for i in fn_sig.decl.inputs {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:193]:
```suggestion
                        for input in fn_sig.decl.inputs {
```

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 7]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                                        .skip(1)
+                                        .next()
+                                        .map(|n| (n.to_string(), sig))
+                                }
+                                _ => None,
+                            }
+                        })
+                    }) {
+                        // FIXME: Cleanup.
+                        let mut ty_spans = vec![];
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:191]: Let's add a comment on this variable re. what it collects.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 8]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                        let impl_name = format!("impl {}", name);
+                        for i in fn_sig.decl.inputs {
+                            if let hir::TyKind::Path(hir::QPath::Resolved(None, path)) = i.kind {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:194]:
```suggestion
                            if let hir::TyKind::Path(hir::QPath::Resolved(None, hir::Path { segments: [segment], .. })) = i.kind {
```

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 9]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                                match path.segments {
+                                    [segment] if segment.ident.to_string() == impl_name => {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:196]: Is `.to_string()` really needed here before comparison?

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 10]
```diff
@@ -160,58 +160,168 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+                            }
+                        }
+
+                        let type_param = format!("{}: {}", "T", name);
+                        // FIXME: modify the `trait_ref` instead of string shenanigans.
+                        // Turn `<impl Trait as Foo>::Bar: Qux` into `<T as Foo>::Bar: Qux`.
+                        let pred = trait_ref.without_const().to_predicate().to_string();
+                        let pred = pred.replace(&impl_name, "T");
+                        let mut sugg = vec![
+                            match generics
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:215]: Generally, I'd appreciate sprinkling more comments on the new code as its not clear what picture the parts are painting.

**Review by Centril — COMMENTED** [review]
Some initial comments -- I can't say I followed everything on a first pass, but addressing these comments might help me.

**Comment by Centril** [comment]
Also, please add a more elaborate PR description to help me understand the core issue being solved here.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:178]: Would it be possible to use the `Span` of the parameter? At the very least that would replace the `param.name.as_str()`. But you might need to get it from some contextual information, since `ty::Param` itself doesn't have it.

Or maybe even better, search in `self.param_env` for bounds on `p.self_ty()`, and find the min/max point along their spans... oh, but `ParamEnv` doesn't have `Span`s, ugh.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 9 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:196]: I _would_ prefer a non-stringly way of figuring this out.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 5 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:315]: This refers to a situation where we have a type param that has a trait bound that doesn't satisfy an associated type's trait bound. An example would be

```rust
fn foo(constraints: impl Iterator) {
    for constraint in constraints {
        println!("{:?}", constraint);
    }
}
```

where `constraint` needs to satisfy `<_ as Iterator>::Item: Debug`, but doesn't.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 9 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:196]: It seems like it wasn't necessary, but still, I would prefer not to do this kind of stringly wobbly stuff.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 10 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:215]: The explanation for what's going on here are in the `match` arms, namely figuring out whether there are type params already to add to them or suggest introducing type params. I think we might already have code for this elsewhere though.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Applied the suggest. Agree that there should be a better way to do this, but I couldn't find one. It seemed to me that we need to turn `impl Trait` into a more first-class member of `rustc` in order to avoid these kind of things.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 5 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Changed to `// Missing restriction on associated type of type parameter (unmet projection).`

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 7 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: Added a comment for the entire block instead of just the span. Let me know if it is clear enough.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 11]
```diff
@@ -147,6 +147,126 @@ crate trait InferCtxtExt<'tcx> {
...
+    msg: &str,
+    err: &mut DiagnosticBuilder<'_>,
+    fn_sig: Option<&hir::FnSig<'_>>,
+    projection: Option<&ty::ProjectionTy<'_>>,
+    trait_ref: &ty::PolyTraitRef<'_>,
+) {
+    let span = generics.where_clause.span_for_predicates_or_empty_place();
+    if !span.from_expansion() && span.desugaring_kind().is_none() {
+        // Given `fn foo(t: impl Trait)` where `Trait` requires assoc type `A`...
+        if let Some((name, fn_sig)) = fn_sig.and_then(|sig| {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:175]:
```suggestion
        if let Some((name, fn_sig)) = fn_sig.zip(projection).and_then(|(p, sig)| {
```

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 12]
```diff
@@ -147,6 +147,126 @@ crate trait InferCtxtExt<'tcx> {
...
+fn suggest_restriction(
+    generics: &hir::Generics<'_>,
+    msg: &str,
+    err: &mut DiagnosticBuilder<'_>,
+    fn_sig: Option<&hir::FnSig<'_>>,
+    projection: Option<&ty::ProjectionTy<'_>>,
+    trait_ref: &ty::PolyTraitRef<'_>,
+) {
+    let span = generics.where_clause.span_for_predicates_or_empty_place();
+    if !span.from_expansion() && span.desugaring_kind().is_none() {
```
Comment (Centril) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:173]: Could early return here to reduce the rightward drift.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 3 above)
Comment (eddyb) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: > It seemed to me that we need to turn `impl Trait` into a more first-class member of `rustc` in order to avoid these kind of things.

That's not exactly true, the problem here is that parameters don't know their *identity*, only an index, and the Chalk integration seems to strongly want to move even further towards indexes only. So what you're missing is contextual information to let you dig deeper into what *defined* this `ty::Param`.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 13]
```diff
@@ -147,6 +147,126 @@ crate trait InferCtxtExt<'tcx> {
...
+                match p.self_ty().kind {
+                    ty::Param(param) => {
+                        // `fn foo(t: impl Trait)`
+                        //                 ^^^^^ get this string
+                        param
+                            .name
+                            .as_str()
+                            .strip_prefix("impl")
+                            .map(|s| (s.trim_start().to_string(), sig))
+                    }
```
Comment (eddyb) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:187]: Actually, looked at the whole diff, you have the `hir::Generics`, and you could either use that (tricky) or you could pass in the `predicates_of` for the item. Which, I think if you `instantiate_identity`, you get a flat list of all of the predicates in scope, and they should still have `Span`s.

You can presumably search for `trait_ref` in the list of predicate and get the corresponding `Span`.
Which should be *exactly* the `Foo` in `impl Foo + Bar`, that corresponds to the trait that's missing an associated type.

Comment (eddyb) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:187]: Bonus: you can probably use the `Span`s in `predicates_of` for other suggestions elsewhere - their initial purpose was automatically applicable suggestions for `type` aliases not being WF, back in late 2018, before that stuff fell through the f loor.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 14]
```diff
@@ -147,6 +147,126 @@ crate trait InferCtxtExt<'tcx> {
...
+/// Type parameter needs more bounds. The trivial case is `T` `where T: Bound`, but
+/// it can also be an `impl Trait` param that needs to be decomposed to a type
+/// param for cleaner code.
+fn suggest_restriction(
+    generics: &hir::Generics<'_>,
+    msg: &str,
+    err: &mut DiagnosticBuilder<'_>,
+    fn_sig: Option<&hir::FnSig<'_>>,
+    projection: Option<&ty::ProjectionTy<'_>>,
+    trait_ref: &ty::PolyTraitRef<'_>,
```
Comment (eddyb) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:170]: Typesystem things are usually small and `Copy`, you can remove both of the `&` here.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 13 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs:187]: So I added span labels for each `TraitPredicate`, and this is what I got:

```
error[E0277]: `<impl Iterator as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
  --> src/test/ui/suggestions/impl-trait-with-missing-bounds.rs:6:13
   |
4  | fn foo(constraints: impl  Iterator) {
   |                     --------------
   |                     |     |
   |                     |     Binder(TraitPredicate(<impl Iterator as std::iter::Iterator>)) NotConst
   |                     Binder(TraitPredicate(<impl Iterator as std::marker::Sized>)) NotConst
5  |     for constraint in constraints {
6  |         qux(constraint);
   |             ^^^^^^^^^^ `<impl Iterator as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
...
27 | fn qux(_: impl std::fmt::Debug) {}
   |    ---         --------------- required by this bound in `qux`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator as std::iter::Iterator>::Item`
help: introduce a type parameter with a trait bound instead of using `impl Trait`
   |
4  | fn foo<T: Iterator>(constraints: T) where <T as std::iter::Iterator>::Item: std::fmt::Debug  {
   |       ^^^^^^^^^^^^^              ^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I can see how it could be useful for some things, but the problem I see is that because this is an assoc type bound instead of setting it a type we cannot use the sytnax `impl Iterator<Item = Something>`. These spans would be great for that, but in this case we need to sadly rely only on extending the `where` clause to `<X as Iterator>::Item: Trait`.

Comment (eddyb) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: You have two options: switching to `impl Iterator<Item = T>` where `T` is a new type parameter and adding a `T: Trait` bound, or `impl Iterator<Item: Trait>`, although I'm not sure the latter works yet or when it will work and it's probably still unstable anyway.

Anyway I was commenting only on the approach of getting the trait bound from the `ty::Param` "name": my point is that you can get its *definition* and work with that, which lets you get the *real snippet* where `impl Foo+Bar` was written (and each `Foo` and `Bar` *in that* if you look in the `predicates_of`).

File: src/librustc_hir/hir.rs [hunk 15]
```diff
@@ -437,6 +437,29 @@ impl GenericParam<'hir> {
...
 }
 
+pub trait NextTypeParamName {
+    fn next_type_param_name(&self) -> &'static str;
+}
+
+impl NextTypeParamName for &[GenericParam<'_>] {
+    fn next_type_param_name(&self) -> &'static str {
+        // This is the whitelist of possible parameter names that we might suggest.
+        let possible_names = ["T", "K", "L", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];
```
Comment (eddyb) [inline src/librustc_hir/hir.rs:447]: `K` and `L` are surprising, I would've expected `T`, `U`, `V` at the least, maybe some `X`, `Y`, `Z`.

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs (hunk 13 above)
Comment (estebank) [reply src/librustc_trait_selection/traits/error_reporting/suggestions.rs]: > `impl Iterator<Item: Trait>`

Yeah, that's not valid today.

> Anyway I was commenting only on the approach

I understand.

> which lets you get the _real snippet_ where `impl Foo+Bar` was written

The current output for a `impl Foo + Bar` case is the following:

```
error[E0277]: `<impl Iterator + std::fmt::Debug as std::iter::Iterator>::Item` doesn't implement `std::fmt::Debug`
  --> src/test/ui/suggestions/impl-trait-with-missing-bounds.rs:37:13
   |
37 |         qux(constraint);
   |             ^^^^^^^^^^ `<impl Iterator + std::fmt::Debug as std::iter::Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
...
42 | fn qux(_: impl std::fmt::Debug) {}
   |    ---         --------------- required by this bound in `qux`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `<impl Iterator + std::fmt::Debug as std::iter::Iterator>::Item`
help: introduce a type parameter with a trait bound instead of using `impl Trait`
   |
35 | fn bak<T: Iterator + std::fmt::Debug>(constraints: T) where <T as std::iter::Iterator>::Item: std::fmt::Debug  {
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              ^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

We need the whole `Foo + Bar` for the type param `T: Foo + Bar`. The only place where having the span to `Foo` for its snippet could be useful as things stand now is for the suggestion message where we now use `<impl Foo + Bar as Foo>::AssocType` where we could say `<_ as Foo>::AssocType` instead, but I feel that leaving it as it is is reasonable.

I think suggesting `fn foo<T: Debug>(constraints: impl Iterator<Item = T>) {}` is reasonable, but at that point the only thing left is the tension between ease of implementation of the suggestion and stylistic preference. The later seems to be more stylistically preferable, but don't know what the code to suggest it will look like yet.

File: src/librustc_hir/hir.rs (hunk 15 above)
Comment (estebank) [reply src/librustc_hir/hir.rs:447]: Does `["T", "U", "V", "X", "Y", "Z", "A", "B", "C", "D", "E", "F", "G"];` seem reasonable to you?

Comment (Centril) [reply src/librustc_hir/hir.rs]: Please address this in a different PR. This seems unrelated to this one.

File: src/librustc_hir/hir.rs [hunk 16]
```diff
@@ -437,6 +437,29 @@ impl GenericParam<'hir> {
...
+                _ => None,
+            })
+            .collect::<Vec<_>>();
+
+        possible_names
+            .iter()
+            .find(|n| !used_names.contains(&Symbol::intern(n)))
+            .unwrap_or(&"ParamName")
+    }
+}
```
Comment (Centril) [inline src/librustc_hir/hir.rs:461]: Also I don't think this belongs in `rustc_hir` as it is diagnostics code, and not about AST data structures. You can move it to `rustc_trait_selection` instead.

Comment (estebank) [reply src/librustc_hir/hir.rs]: It is also used in `typeck` (where I extracted it from in the first place).

File: src/librustc_hir/hir.rs (hunk 15 above)
Comment (estebank) [reply src/librustc_hir/hir.rs]: We already had that code in the codebase, I only moved it to a common place so that it could be used here too, otherwise we can suggest `fn foo<T, T>() {}` by accident.

File: src/librustc_hir/hir.rs (hunk 16 above)
Comment (Centril) [reply src/librustc_hir/hir.rs]: `rustc_typeck` has a dependency on `rustc_trait_selection`. I personally don't think this as common as `descr` to warrant adding it here.

Comment (estebank) [reply src/librustc_hir/hir.rs]: Moved to `rustc_trait_selection` :)

**Comment by estebank** [comment]
Ping :)

**Review by Centril — COMMENTED** [review]
This is complicated enough that I didn't follow everything; but r=me with these small adjustments nevertheless.

**Comment by Centril** [comment]
Seems to have failed tests in https://github.com/rust-lang/rust/pull/71012, @bors r-
