### PR TITLE
Permit ty::Bool in const generics for v0 mangling

### LINKED ISSUE #76365: ICE on bootstrap with new symbol mangling
Command was `./x.py build --stage 1 -i` with the following config.toml:

```toml
[llvm]
skip-rebuild = true # but it was my first build anyways

# Indicates whether the LLVM assertions are enabled or not
assertions = true

# Indicates whether ccache is used when building LLVM
ccache = "/usr/bin/ccache"

[build]
docs = false

# Build the profiler runtime (required when compiling with options that depend
# on this runtime, such as `-C profile-generate` or `-Z instrument-coverage`).
profiler = true

print-step-timings = true

[rust]
debug = true

codegen-units = 0

codegen-units-std = 0

# Debuginfo level for the test suites run with compiletest.
# FIXME(#61117): Some tests fail when this option is enabled.
debuginfo-level-tests = 0

incremental = true
parallel-compiler = true
backtrace-on-ice = true
jemalloc = false

# Enable symbol-mangling-version v0. This can be helpful when profiling rustc,
# as generics will be preserved in symbols (rather than erased into opaque T).
new-symbol-mangling = true
```

### Error output

```

error: internal compiler error: src/librustc_symbol_mangling/v0.rs:511:17: symbol_names: unsupported constant of type `bool` (Const { ty: bool, val: Value(Scalar(0x01)) })
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_symbol_mangling/v0.rs:511:17: symbol_names: unsupported constant of type `bool` (Const { ty: bool, val: Value(Scalar(0x01)) })

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
stack backtrace:
   0:     0x7f373a6e5590 - std::backtrace_rs::backtrace::libunwind::trace::h9e3e6d9b3369e699
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7f373a6e5590 - std::backtrace_rs::backtrace::trace_unsynchronized::he58aba3ac08ed12a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7f373a6e5590 - std::sys_common::backtrace::_print_fmt::hbbbd4c92d537cef4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:79
   3:     0x7f373a6e5590 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80c2ae080004cc83
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:58
   4:     0x7f373a753f9c - core::fmt::write::h0c11e16fd03fe660
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/core/src/fmt/mod.rs:1082
   5:     0x7f373a6d78b7 - std::io::Write::write_fmt::h2e2072ff86131fcd
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/io/mod.rs:1514
   6:     0x7f373a6ea250 - std::sys_common::backtrace::_print::h165e6476adb4cb58
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:61
   7:     0x7f373a6ea250 - std::sys_common::backtrace::print::hbbfa32a92cd1fc34
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:48
   8:     0x7f373a6ea250 - std::panicking::default_hook::{{closure}}::h3a02067ca7f64068
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:200
   9:     0x7f373a6e9f9c - std::panicking::default_hook::ha3137d6f4e961fe2
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:219
[RUSTC-TIMING] rustc_incremental test:false 2.023
  10:     0x7f373af61f29 - rustc_driver::report_ice::ha928cb19cffa046d
  11:     0x7f373a6ea9f8 - std::panicking::rust_panic_with_hook::he6505c3b9d82db8b
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:573
  12:     0x7f373deb47ad - std::panicking::begin_panic::{{closure}}::hdb5318733587c285
  13:     0x7f373deb43e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf869fec5c3427872
  14:     0x7f373deb467f - std::panicking::begin_panic::h46b4a1cb043b0510
  15:     0x7f373de78ea0 - rustc_errors::HandlerInner::bug::hff9597832d4fa5b3
  16:     0x7f373de77800 - rustc_errors::Handler::bug::h5da178dbed903cad
  17:     0x7f373da6101d - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h2907aad52cf3f889
  18:     0x7f373da50d2b - rustc_middle::ty::context::tls::with_opt::{{closure}}::h246f7425f0808a59
  19:     0x7f373da50cd2 - rustc_middle::ty::context::tls::with_opt::h558aa4d135d104ea
  20:     0x7f373da60f49 - rustc_middle::util::bug::opt_span_bug_fmt::h09b57d246bdf8c54
  21:     0x7f373da60ebe - rustc_middle::util::bug::bug_fmt::had21e5443b742c91
  22:     0x7f373ca4f10b - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_const::hafbb63b3b6848d37
  23:     0x7f373ca4a9ab - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  24:     0x7f373ca4c7a3 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_type::hd58012656fcaad94
  25:     0x7f373ca4ba14 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_impl_path::h16b4e1e1d0561bf8
  26:     0x7f373ca4a68f - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  27:     0x7f373ca4ae83 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  28:     0x7f373ca49350 - rustc_symbol_mangling::v0::mangle::h877426cb0ed451fb
  29:     0x7f373ca12c5d - rustc_symbol_mangling::symbol_name_provider::hdceaf7358b6f63e7
  30:     0x7f373dd6fabd - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::symbol_name>::compute::ha07d82a957adb98f
  31:     0x7f373dd440df - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h344f5077b77cff50
  32:     0x7f373d8aa80f - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h7404c6d587dc7d43
  33:     0x7f373d9d9c2c - rustc_data_structures::stack::ensure_sufficient_stack::h7c6a21731db1a308
  34:     0x7f373d752a00 - rustc_query_system::query::plumbing::get_query_impl::h9fe2e41092355180
  35:     0x7f373dd5465f - rustc_middle::mir::mono::MonoItem::symbol_name::h80ad1a8b806d4d42
  36:     0x7f373c8206f1 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h289f14a9c9df6419
  37:     0x7f373c323848 - rustc_mir::monomorphize::partitioning::assert_symbols_are_distinct::h5eb8a0de426726e3
  38:     0x7f373c71e03f - rustc_data_structures::sync::join::hf6d46c40d8a552e1
  39:     0x7f373c323f2f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h42ef428227c6cac5
  40:     0x7f373b4f53b2 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h38717b5d7bc20b73
  41:     0x7f373b3f3669 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h0f075104b32e285c
  42:     0x7f373b439223 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::heae1a81ad9031678
  43:     0x7f373b4c3c1c - rustc_data_structures::stack::ensure_sufficient_stack::hb806e005d2730a66
  44:     0x7f373b3d6e6f - rustc_query_system::query::plumbing::get_query_impl::hdcae9702cbc1ab03
  45:     0x7f373b4f9b4b - rustc_codegen_ssa::base::codegen_crate::h5bde621f620a0717
  46:     0x7f373b4f3065 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h60a8c0c146b76e3a
  47:     0x7f373b28e4c8 - rustc_interface::passes::QueryContext::enter::h30985390d20106a1
  48:     0x7f373b2d6013 - rustc_interface::queries::Queries::ongoing_codegen::h8c333d30bf607b41
  49:     0x7f373af86047 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h02ce8096a5f06d01
  50:     0x7f373af19da7 - rustc_span::with_source_map::h2b775fec60d279ee
  51:     0x7f373af87513 - rustc_interface::interface::create_compiler_and_run::h9fad8d2ec65cfb15
  52:     0x7f373af65dda - scoped_tls::ScopedKey<T>::set::hb36a1010cb307a36
  53:     0x7f373af7a157 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0613e9c7478aaba2
  54:     0x7f373af0434e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hab35b7186d8c364d
  55:     0x7f373a6f9faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h08a7f59d1f132678
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  56:     0x7f373a6f9faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcc8dca4ed5ef7ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  57:     0x7f373a6f9faa - std::sys::unix::thread::Thread::new::thread_start::h8bde10ff272e5ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys/unix/thread.rs:87
  58:     0x7f373a61c669 - start_thread
  59:     0x7f373a5312b3 - __clone
  60:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=v0 -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [symbol_name] computing the symbol for `rustc_data_structures::tagged_ptr::CopyTaggedPtr::<&rustc_middle::ty::List<rustc_middle::ty::Predicate>, rustc_middle::traits::Reveal, true>::tag`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

[RUSTC-TIMING] rustc_symbol_mangling test:false 2.053
error: could not compile `rustc_symbol_mangling`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
[RUSTC-TIMING] rustc_metadata test:false 4.249
error: internal compiler error: src/librustc_symbol_mangling/v0.rs:511:17: symbol_names: unsupported constant of type `bool` (Const { ty: bool, val: Value(Scalar(0x01)) })

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
stack backtrace:
   0:     0x7fe72486d590 - std::backtrace_rs::backtrace::libunwind::trace::h9e3e6d9b3369e699
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7fe72486d590 - std::backtrace_rs::backtrace::trace_unsynchronized::he58aba3ac08ed12a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7fe72486d590 - std::sys_common::backtrace::_print_fmt::hbbbd4c92d537cef4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:79
   3:     0x7fe72486d590 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80c2ae080004cc83
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:58
   4:     0x7fe7248dbf9c - core::fmt::write::h0c11e16fd03fe660
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/core/src/fmt/mod.rs:1082
   5:     0x7fe72485f8b7 - std::io::Write::write_fmt::h2e2072ff86131fcd
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/io/mod.rs:1514
   6:     0x7fe724872250 - std::sys_common::backtrace::_print::h165e6476adb4cb58
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:61
   7:     0x7fe724872250 - std::sys_common::backtrace::print::hbbfa32a92cd1fc34
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:48
   8:     0x7fe724872250 - std::panicking::default_hook::{{closure}}::h3a02067ca7f64068
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:200
   9:     0x7fe724871f9c - std::panicking::default_hook::ha3137d6f4e961fe2
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:219
  10:     0x7fe7250e9f29 - rustc_driver::report_ice::ha928cb19cffa046d
  11:     0x7fe718d1a2cc - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::habbf7ea7a8ddfd8a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1056
  12:     0x7fe718d62cf2 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h59a5f872ede9449a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/proc_macro/src/bridge/client.rs:319
  13:     0x7fe7248729f8 - std::panicking::rust_panic_with_hook::he6505c3b9d82db8b
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:573
  14:     0x7fe72803c7ad - std::panicking::begin_panic::{{closure}}::hdb5318733587c285
  15:     0x7fe72803c3e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf869fec5c3427872
  16:     0x7fe72803c67f - std::panicking::begin_panic::h46b4a1cb043b0510
  17:     0x7fe728000ea0 - rustc_errors::HandlerInner::bug::hff9597832d4fa5b3
  18:     0x7fe727fff800 - rustc_errors::Handler::bug::h5da178dbed903cad
  19:     0x7fe727be901d - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h2907aad52cf3f889
  20:     0x7fe727bd8d2b - rustc_middle::ty::context::tls::with_opt::{{closure}}::h246f7425f0808a59
  21:     0x7fe727bd8cd2 - rustc_middle::ty::context::tls::with_opt::h558aa4d135d104ea
  22:     0x7fe727be8f49 - rustc_middle::util::bug::opt_span_bug_fmt::h09b57d246bdf8c54
  23:     0x7fe727be8ebe - rustc_middle::util::bug::bug_fmt::had21e5443b742c91
  24:     0x7fe726bd710b - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_const::hafbb63b3b6848d37
  25:     0x7fe726bd29ab - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  26:     0x7fe726bd47a3 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_type::hd58012656fcaad94
  27:     0x7fe726bd3a14 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_impl_path::h16b4e1e1d0561bf8
  28:     0x7fe726bd268f - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  29:     0x7fe726bd2e83 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  30:     0x7fe726bd1350 - rustc_symbol_mangling::v0::mangle::h877426cb0ed451fb
  31:     0x7fe726b9ac5d - rustc_symbol_mangling::symbol_name_provider::hdceaf7358b6f63e7
  32:     0x7fe727ef7abd - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::symbol_name>::compute::ha07d82a957adb98f
  33:     0x7fe727ecc0df - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h344f5077b77cff50
  34:     0x7fe727a3280f - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h7404c6d587dc7d43
  35:     0x7fe727b61c2c - rustc_data_structures::stack::ensure_sufficient_stack::h7c6a21731db1a308
  36:     0x7fe7278daa00 - rustc_query_system::query::plumbing::get_query_impl::h9fe2e41092355180
  37:     0x7fe727edc65f - rustc_middle::mir::mono::MonoItem::symbol_name::h80ad1a8b806d4d42
  38:     0x7fe7269a86f1 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h289f14a9c9df6419
  39:     0x7fe7264ab848 - rustc_mir::monomorphize::partitioning::assert_symbols_are_distinct::h5eb8a0de426726e3
  40:     0x7fe7268a603f - rustc_data_structures::sync::join::hf6d46c40d8a552e1
  41:     0x7fe7264abf2f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h42ef428227c6cac5
  42:     0x7fe72567d3b2 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h38717b5d7bc20b73
  43:     0x7fe72557b669 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h0f075104b32e285c
  44:     0x7fe7255c1223 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::heae1a81ad9031678
  45:     0x7fe72564bc1c - rustc_data_structures::stack::ensure_sufficient_stack::hb806e005d2730a66
  46:     0x7fe72555ee6f - rustc_query_system::query::plumbing::get_query_impl::hdcae9702cbc1ab03
  47:     0x7fe725681b4b - rustc_codegen_ssa::base::codegen_crate::h5bde621f620a0717
  48:     0x7fe72567b065 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h60a8c0c146b76e3a
  49:     0x7fe7254164c8 - rustc_interface::passes::QueryContext::enter::h30985390d20106a1
  50:     0x7fe72545e013 - rustc_interface::queries::Queries::ongoing_codegen::h8c333d30bf607b41
  51:     0x7fe72510e047 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h02ce8096a5f06d01
  52:     0x7fe7250a1da7 - rustc_span::with_source_map::h2b775fec60d279ee
  53:     0x7fe72510f513 - rustc_interface::interface::create_compiler_and_run::h9fad8d2ec65cfb15
  54:     0x7fe7250eddda - scoped_tls::ScopedKey<T>::set::hb36a1010cb307a36
  55:     0x7fe725102157 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0613e9c7478aaba2
  56:     0x7fe72508c34e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hab35b7186d8c364d
  57:     0x7fe724881faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h08a7f59d1f132678
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  58:     0x7fe724881faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcc8dca4ed5ef7ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  59:     0x7fe724881faa - std::sys::unix::thread::Thread::new::thread_start::h8bde10ff272e5ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys/unix/thread.rs:87
  60:     0x7fe7247a4669 - start_thread
  61:     0x7fe7246b92b3 - __clone
  62:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=v0 -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [symbol_name] computing the symbol for `rustc_data_structures::tagged_ptr::CopyTaggedPtr::<&rustc_middle::ty::List<rustc_middle::ty::Predicate>, rustc_middle::traits::Reveal, true>::pointer_raw`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

[RUSTC-TIMING] rustc_codegen_ssa test:false 5.878
error: internal compiler error: src/librustc_symbol_mangling/v0.rs:511:17: symbol_names: unsupported constant of type `bool` (Const { ty: bool, val: Value(Scalar(0x01)) })

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
stack backtrace:
   0:     0x7fe693730590 - std::backtrace_rs::backtrace::libunwind::trace::h9e3e6d9b3369e699
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7fe693730590 - std::backtrace_rs::backtrace::trace_unsynchronized::he58aba3ac08ed12a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7fe693730590 - std::sys_common::backtrace::_print_fmt::hbbbd4c92d537cef4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:79
   3:     0x7fe693730590 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80c2ae080004cc83
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:58
   4:     0x7fe69379ef9c - core::fmt::write::h0c11e16fd03fe660
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/core/src/fmt/mod.rs:1082
   5:     0x7fe6937228b7 - std::io::Write::write_fmt::h2e2072ff86131fcd
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/io/mod.rs:1514
   6:     0x7fe693735250 - std::sys_common::backtrace::_print::h165e6476adb4cb58
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:61
   7:     0x7fe693735250 - std::sys_common::backtrace::print::hbbfa32a92cd1fc34
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:48
   8:     0x7fe693735250 - std::panicking::default_hook::{{closure}}::h3a02067ca7f64068
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:200
   9:     0x7fe693734f9c - std::panicking::default_hook::ha3137d6f4e961fe2
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:219
  10:     0x7fe693facf29 - rustc_driver::report_ice::ha928cb19cffa046d
  11:     0x7fe68791a2cc - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::habbf7ea7a8ddfd8a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1056
  12:     0x7fe687962cf2 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h59a5f872ede9449a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/proc_macro/src/bridge/client.rs:319
  13:     0x7fe6937359f8 - std::panicking::rust_panic_with_hook::he6505c3b9d82db8b
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:573
  14:     0x7fe696eff7ad - std::panicking::begin_panic::{{closure}}::hdb5318733587c285
  15:     0x7fe696eff3e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf869fec5c3427872
  16:     0x7fe696eff67f - std::panicking::begin_panic::h46b4a1cb043b0510
  17:     0x7fe696ec3ea0 - rustc_errors::HandlerInner::bug::hff9597832d4fa5b3
  18:     0x7fe696ec2800 - rustc_errors::Handler::bug::h5da178dbed903cad
  19:     0x7fe696aac01d - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h2907aad52cf3f889
  20:     0x7fe696a9bd2b - rustc_middle::ty::context::tls::with_opt::{{closure}}::h246f7425f0808a59
  21:     0x7fe696a9bcd2 - rustc_middle::ty::context::tls::with_opt::h558aa4d135d104ea
  22:     0x7fe696aabf49 - rustc_middle::util::bug::opt_span_bug_fmt::h09b57d246bdf8c54
  23:     0x7fe696aabebe - rustc_middle::util::bug::bug_fmt::had21e5443b742c91
  24:     0x7fe695a9a10b - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_const::hafbb63b3b6848d37
  25:     0x7fe695a959ab - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  26:     0x7fe695a977a3 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_type::hd58012656fcaad94
  27:     0x7fe695a96a14 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_impl_path::h16b4e1e1d0561bf8
  28:     0x7fe695a9568f - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  29:     0x7fe695a95e83 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  30:     0x7fe695a94350 - rustc_symbol_mangling::v0::mangle::h877426cb0ed451fb
  31:     0x7fe695a5dc5d - rustc_symbol_mangling::symbol_name_provider::hdceaf7358b6f63e7
  32:     0x7fe696dbaabd - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::symbol_name>::compute::ha07d82a957adb98f
  33:     0x7fe696d8f0df - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h344f5077b77cff50
  34:     0x7fe6968f580f - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h7404c6d587dc7d43
  35:     0x7fe696a24c2c - rustc_data_structures::stack::ensure_sufficient_stack::h7c6a21731db1a308
  36:     0x7fe69679da00 - rustc_query_system::query::plumbing::get_query_impl::h9fe2e41092355180
  37:     0x7fe696d9f65f - rustc_middle::mir::mono::MonoItem::symbol_name::h80ad1a8b806d4d42
  38:     0x7fe69586b6f1 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h289f14a9c9df6419
  39:     0x7fe69536e848 - rustc_mir::monomorphize::partitioning::assert_symbols_are_distinct::h5eb8a0de426726e3
  40:     0x7fe69576903f - rustc_data_structures::sync::join::hf6d46c40d8a552e1
  41:     0x7fe69536ef2f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h42ef428227c6cac5
  42:     0x7fe6945403b2 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h38717b5d7bc20b73
  43:     0x7fe69443e669 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h0f075104b32e285c
  44:     0x7fe694484223 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::heae1a81ad9031678
  45:     0x7fe69450ec1c - rustc_data_structures::stack::ensure_sufficient_stack::hb806e005d2730a66
  46:     0x7fe694421e6f - rustc_query_system::query::plumbing::get_query_impl::hdcae9702cbc1ab03
  47:     0x7fe694544b4b - rustc_codegen_ssa::base::codegen_crate::h5bde621f620a0717
  48:     0x7fe69453e065 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h60a8c0c146b76e3a
  49:     0x7fe6942d94c8 - rustc_interface::passes::QueryContext::enter::h30985390d20106a1
  50:     0x7fe694321013 - rustc_interface::queries::Queries::ongoing_codegen::h8c333d30bf607b41
  51:     0x7fe693fd1047 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h02ce8096a5f06d01
  52:     0x7fe693f64da7 - rustc_span::with_source_map::h2b775fec60d279ee
  53:     0x7fe693fd2513 - rustc_interface::interface::create_compiler_and_run::h9fad8d2ec65cfb15
  54:     0x7fe693fb0dda - scoped_tls::ScopedKey<T>::set::hb36a1010cb307a36
  55:     0x7fe693fc5157 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0613e9c7478aaba2
  56:     0x7fe693f4f34e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hab35b7186d8c364d
  57:     0x7fe693744faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h08a7f59d1f132678
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  58:     0x7fe693744faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcc8dca4ed5ef7ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  59:     0x7fe693744faa - std::sys::unix::thread::Thread::new::thread_start::h8bde10ff272e5ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys/unix/thread.rs:87
  60:     0x7fe693667669 - start_thread
  61:     0x7fe69357c2b3 - __clone
  62:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=v0 -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [symbol_name] computing the symbol for `<rustc_data_structures::tagged_ptr::CopyTaggedPtr<&rustc_middle::ty::List<rustc_middle::ty::Predicate>, rustc_middle::traits::Reveal, true> as std::cmp::PartialEq>::eq`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

[RUSTC-TIMING] rustc_infer test:false 7.400
error: internal compiler error: src/librustc_symbol_mangling/v0.rs:511:17: symbol_names: unsupported constant of type `bool` (Const { ty: bool, val: Value(Scalar(0x01)) })

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
stack backtrace:
   0:     0x7f9bc5fe3590 - std::backtrace_rs::backtrace::libunwind::trace::h9e3e6d9b3369e699
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7f9bc5fe3590 - std::backtrace_rs::backtrace::trace_unsynchronized::he58aba3ac08ed12a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7f9bc5fe3590 - std::sys_common::backtrace::_print_fmt::hbbbd4c92d537cef4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:79
   3:     0x7f9bc5fe3590 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80c2ae080004cc83
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:58
   4:     0x7f9bc6051f9c - core::fmt::write::h0c11e16fd03fe660
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/core/src/fmt/mod.rs:1082
   5:     0x7f9bc5fd58b7 - std::io::Write::write_fmt::h2e2072ff86131fcd
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/io/mod.rs:1514
   6:     0x7f9bc5fe8250 - std::sys_common::backtrace::_print::h165e6476adb4cb58
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:61
   7:     0x7f9bc5fe8250 - std::sys_common::backtrace::print::hbbfa32a92cd1fc34
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys_common/backtrace.rs:48
   8:     0x7f9bc5fe8250 - std::panicking::default_hook::{{closure}}::h3a02067ca7f64068
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:200
   9:     0x7f9bc5fe7f9c - std::panicking::default_hook::ha3137d6f4e961fe2
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:219
  10:     0x7f9bc685ff29 - rustc_driver::report_ice::ha928cb19cffa046d
  11:     0x7f9bb891a2cc - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::habbf7ea7a8ddfd8a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1056
  12:     0x7f9bb8962cf2 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h59a5f872ede9449a
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/proc_macro/src/bridge/client.rs:319
  13:     0x7f9bc5fe89f8 - std::panicking::rust_panic_with_hook::he6505c3b9d82db8b
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/panicking.rs:573
  14:     0x7f9bc97b27ad - std::panicking::begin_panic::{{closure}}::hdb5318733587c285
  15:     0x7f9bc97b23e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf869fec5c3427872
  16:     0x7f9bc97b267f - std::panicking::begin_panic::h46b4a1cb043b0510
  17:     0x7f9bc9776ea0 - rustc_errors::HandlerInner::bug::hff9597832d4fa5b3
  18:     0x7f9bc9775800 - rustc_errors::Handler::bug::h5da178dbed903cad
  19:     0x7f9bc935f01d - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h2907aad52cf3f889
  20:     0x7f9bc934ed2b - rustc_middle::ty::context::tls::with_opt::{{closure}}::h246f7425f0808a59
  21:     0x7f9bc934ecd2 - rustc_middle::ty::context::tls::with_opt::h558aa4d135d104ea
  22:     0x7f9bc935ef49 - rustc_middle::util::bug::opt_span_bug_fmt::h09b57d246bdf8c54
  23:     0x7f9bc935eebe - rustc_middle::util::bug::bug_fmt::had21e5443b742c91
  24:     0x7f9bc834d10b - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_const::hafbb63b3b6848d37
  25:     0x7f9bc83489ab - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  26:     0x7f9bc834a7a3 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_type::hd58012656fcaad94
  27:     0x7f9bc8349a14 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_impl_path::h16b4e1e1d0561bf8
  28:     0x7f9bc834868f - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  29:     0x7f9bc8348e83 - <rustc_symbol_mangling::v0::SymbolMangler as rustc_middle::ty::print::Printer>::print_def_path::h0ca4eac8d30a8de4
  30:     0x7f9bc8347350 - rustc_symbol_mangling::v0::mangle::h877426cb0ed451fb
  31:     0x7f9bc8310c5d - rustc_symbol_mangling::symbol_name_provider::hdceaf7358b6f63e7
  32:     0x7f9bc966dabd - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::symbol_name>::compute::ha07d82a957adb98f
  33:     0x7f9bc96420df - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h344f5077b77cff50
  34:     0x7f9bc91a880f - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h7404c6d587dc7d43
  35:     0x7f9bc92d7c2c - rustc_data_structures::stack::ensure_sufficient_stack::h7c6a21731db1a308
  36:     0x7f9bc9050a00 - rustc_query_system::query::plumbing::get_query_impl::h9fe2e41092355180
  37:     0x7f9bc965265f - rustc_middle::mir::mono::MonoItem::symbol_name::h80ad1a8b806d4d42
  38:     0x7f9bc811e6f1 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h289f14a9c9df6419
  39:     0x7f9bc7c21848 - rustc_mir::monomorphize::partitioning::assert_symbols_are_distinct::h5eb8a0de426726e3
  40:     0x7f9bc801c03f - rustc_data_structures::sync::join::hf6d46c40d8a552e1
  41:     0x7f9bc7c21f2f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h42ef428227c6cac5
  42:     0x7f9bc6df33b2 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h38717b5d7bc20b73
  43:     0x7f9bc6cf1669 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h0f075104b32e285c
  44:     0x7f9bc6d37223 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::heae1a81ad9031678
  45:     0x7f9bc6dc1c1c - rustc_data_structures::stack::ensure_sufficient_stack::hb806e005d2730a66
  46:     0x7f9bc6cd4e6f - rustc_query_system::query::plumbing::get_query_impl::hdcae9702cbc1ab03
  47:     0x7f9bc6df7b4b - rustc_codegen_ssa::base::codegen_crate::h5bde621f620a0717
  48:     0x7f9bc6df1065 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h60a8c0c146b76e3a
  49:     0x7f9bc6b8c4c8 - rustc_interface::passes::QueryContext::enter::h30985390d20106a1
  50:     0x7f9bc6bd4013 - rustc_interface::queries::Queries::ongoing_codegen::h8c333d30bf607b41
  51:     0x7f9bc6884047 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h02ce8096a5f06d01
  52:     0x7f9bc6817da7 - rustc_span::with_source_map::h2b775fec60d279ee
  53:     0x7f9bc6885513 - rustc_interface::interface::create_compiler_and_run::h9fad8d2ec65cfb15
  54:     0x7f9bc6863dda - scoped_tls::ScopedKey<T>::set::hb36a1010cb307a36
  55:     0x7f9bc6878157 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0613e9c7478aaba2
  56:     0x7f9bc680234e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hab35b7186d8c364d
  57:     0x7f9bc5ff7faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h08a7f59d1f132678
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  58:     0x7f9bc5ff7faa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcc8dca4ed5ef7ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/alloc/src/boxed.rs:1042
  59:     0x7f9bc5ff7faa - std::sys::unix::thread::Thread::new::thread_start::h8bde10ff272e5ca4
                               at /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe/library/std/src/sys/unix/thread.rs:87
  60:     0x7f9bc5f1a669 - start_thread
  61:     0x7f9bc5e2f2b3 - __clone
  62:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=v0 -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [symbol_name] computing the symbol for `<rustc_data_structures::tagged_ptr::CopyTaggedPtr<&ty::list::List<ty::Predicate>, traits::Reveal, true> as std::cmp::PartialEq>::eq`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

[RUSTC-TIMING] rustc_middle test:false 40.194
[RUSTC-TIMING] rustc_resolve test:false 26.721
error: build failed
command did not execute successfully: "/tmp/rustc/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--features" " llvm" "--manifest-path" "/tmp/rustc/compiler/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /tmp/rustc/build/bootstrap/debug/bootstrap build -i --stage 1
Build completed unsuccessfully in 0:00:47
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This should unbreak using new-symbol-mangling = true in config.toml (once it lands in beta anyway).

Fixes #76365 (well, it will, but seems fine to close as soon as we have support)

r? @eddyb (for mangling) but I'm okay with some other reviewer too :)

### CODE REVIEW

File: compiler/rustc_symbol_mangling/src/v0.rs [hunk 1]
```diff
@@ -504,6 +504,7 @@ impl Printer<'tcx> for SymbolMangler<'tcx> {
 
         match ct.ty.kind() {
             ty::Uint(_) => {}
+            ty::Bool => {}
```
Comment (varkor) [inline compiler/rustc_symbol_mangling/src/v0.rs:507]: If this is all that's required, can we also add `ty::Char` and `ty::Int`, or do these need special attention?

Comment (Mark-Simulacrum) [reply compiler/rustc_symbol_mangling/src/v0.rs:507]: ty::Int seems reasonable, though we might want to change mangling to express signed-ness (so you get `foo<-1>` in perf top or whatever, not `foo<255>`). I think we do not want to encode char with the bits so I would like to hold off on it for now.

Comment (Mark-Simulacrum) [reply compiler/rustc_symbol_mangling/src/v0.rs:507]: So both seem harder than just bool, which encoding with 0/1 seems quite reasonable.

**Review by eddyb — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
No, but I will work on that.

**Comment by varkor** [comment]
Don't worry about the rustc-demangle support: I'm going to add it along with `char` and signed integer support.
