### PR TITLE
Fix the conflict problem between the diagnostics fixes of lint `unnecessary_qualification`  and  `unused_imports`

### LINKED ISSUE #121331: unused_qualifications clashes with unused_import
### Code

```Rust
#![warn(unused_qualifications)]
#![feature(coroutines, coroutine_trait)]

use std::ops::{
    Coroutine,
    CoroutineState::{self, *},
};
use std::pin::Pin;

fn finish<T>(mut amt: usize, mut t: T) -> T::Return
    where T: Coroutine<(), Yield = ()> + Unpin,
{
    loop {
        match Pin::new(&mut t).resume(()) {
            CoroutineState::Yielded(()) => amt = amt.checked_sub(1).unwrap(),
            CoroutineState::Complete(ret) => {
                assert_eq!(amt, 0);
                return ret
            }
        }
    }

}

pub fn main() {}
```

### Current output

```Shell

warning: unused import: `*`
 --> src/main.rs:6:28
  |
6 |     CoroutineState::{self, *},
  |                            ^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unnecessary qualification
  --> src/main.rs:15:13
   |
15 |             CoroutineState::Yielded(()) => amt = amt.checked_sub(1).unwrap(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![warn(unused_qualifications)]
   |         ^^^^^^^^^^^^^^^^^^^^^
help: remove the unnecessary path segments
   |
15 -             CoroutineState::Yielded(()) => amt = amt.checked_sub(1).unwrap(),
15 +             Yielded(()) => amt = amt.checked_sub(1).unwrap(),
   |

warning: unnecessary qualification
  --> src/main.rs:16:13
   |
16 |             CoroutineState::Complete(ret) => {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: remove the unnecessary path segments
   |
16 -             CoroutineState::Complete(ret) => {
16 +             Complete(ret) => {
   |

```

### Desired output

_No response_

### Rationale and extra context

The suggestion fails to apply with cargo fix

````
The following errors were reported:
error[E0531]: cannot find tuple struct or tuple variant `Yielded` in this scope
  --> src/main.rs:15:13
   |
15 |             Yielded(()) => amt = amt.checked_sub(1).unwrap(),
   |             ^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
4  + use core::ops::CoroutineState::Yielded;
   |
4  + use crate::CoroutineState::Yielded;
   |
4  + use std::ops::CoroutineState::Yielded;
   |

error[E0531]: cannot find tuple struct or tuple variant `Complete` in this scope
  --> src/main.rs:16:13
   |
16 |             Complete(ret) => {
   |             ^^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
4  + use core::ops::CoroutineState::Complete;
   |
4  + use crate::CoroutineState::Complete;
   |
4  + use std::ops::CoroutineState::Complete;
   |

warning: unused import: `self`
```

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.78.0-nightly (3246e7951 2024-02-19)
binary: rustc
commit-hash: 3246e79513cb89ddbfc0f21cb5a877e5b321dcc5
commit-date: 2024-02-19
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```


### Anything else?

_No response_

<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_DATA_START$${"user":"surechen"}$$TRIAGEBOT_ASSIGN_DATA_END -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->

### PR DESCRIPTION
**Pull request by surechen**
fixes #121331

For an `item` that triggers lint unnecessary_qualification, if the `use item` which imports this item is also trigger unused import, fixing the two lints at the same time may lead to the problem that the `item` cannot be found.
This PR will avoid reporting lint unnecessary_qualification when conflict occurs.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -1534,3 +1539,16 @@ impl<'a, 'b, 'tcx> Visitor<'b> for BuildReducedGraphVisitor<'a, 'b, 'tcx> {
         }
     }
 }
+
+fn check_allow_unused_imports_attr(attrs: &AttrVec) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1543]: This is really unreliable, the `allow` attribute may be e.g. on a parent module instead of the `use` item itself, and I wouldn't want to include the lint level tree logic into resolve.

In general, the `unused_qualifications` lint is not very reliable and rarely used, that's why it's allow-by-default.
So, I think we can prioritize the unused import lints and just do some minimal repair to the `unused_qualifications` lint so it doesn't produce breaking suggestions.

So, if we don't consider `allow` we would still suppress `unused_qualifications` even if it refers to an allowed unused imports, and that seems fine to me.

File: compiler/rustc_resolve/src/lib.rs [hunk 2]
```diff
@@ -1105,6 +1105,8 @@ pub struct Resolver<'a, 'tcx> {
 
     potentially_unused_imports: Vec<Import<'a>>,
 
+    potentially_unnecessary_qualification: Vec<UnnecessaryQualification<'a>>,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1108]:
```suggestion
    potentially_unnecessary_qualifications: Vec<UnnecessaryQualification<'a>>,
```

File: compiler/rustc_resolve/src/late.rs [hunk 3]
```diff
@@ -4653,20 +4661,15 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
             let ns = if i + 1 == path.len() { ns } else { TypeNS };
             let res = self.r.partial_res_map.get(&seg.id?)?.full_res()?;
             let binding = self.resolve_ident_in_lexical_scope(seg.ident, ns, None, None)?;
-
-            (res == binding.res()).then_some(seg)
+            (res == binding.clone().res()).then_some((seg, binding))
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:4664]:
```suggestion
            (res == binding.res()).then_some((seg, binding))
```
`LexicalScopeBinding` can be easily made `Copy`, not just `Clone`.

File: compiler/rustc_resolve/src/late.rs [hunk 4]
```diff
@@ -4653,20 +4661,15 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
         });
 
         if let Some(unqualified) = unqualified {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:4667]:
```suggestion
        if let Some((seg, binding)) = unqualified {
```

File: compiler/rustc_resolve/src/late.rs [hunk 5]
```diff
@@ -580,6 +580,14 @@ impl MaybeExported<'_> {
     }
 }
 
+/// Used for recording UnnecessaryQualification.
+#[derive(Debug)]
+pub(crate) struct UnnecessaryQualification<'a> {
+    pub binding: LexicalScopeBinding<'a>,
+    pub finalize: Finalize,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:587]: Only `node_id` and `path_span` are used, can keep just them instead of full `Finalize`.

File: compiler/rustc_resolve/src/late.rs [hunk 6]
```diff
@@ -580,6 +580,14 @@ impl MaybeExported<'_> {
...
+    pub span: Span,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:588]:
```suggestion
    pub removal_span: Span,
```

File: compiler/rustc_resolve/src/check_unused.rs [hunk 7]
```diff
@@ -494,6 +496,30 @@ impl Resolver<'_, '_> {
...
+
+        // The lint fixes for unused_import and unnecessary_qualification may conflict.
+        // Deleting both unused imports and unnecessary segments of an item may result
+        // in the item not being found.
+        for v in &self.potentially_unnecessary_qualification {
+            if let LexicalScopeBinding::Item(name_binding) = v.binding
+                && let NameBindingKind::Import { import, .. } = name_binding.kind
+                && let Some(unused_import) = unused_imports.get(&import.root_id)
+                && let Some(id) = import.id()
+                && unused_import.unused.contains(&id)
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/check_unused.rs:508]: Shouldn't redundant imports be excluded here as well?

File: compiler/rustc_resolve/src/check_unused.rs [hunk 8]
```diff
@@ -27,14 +27,16 @@ use crate::imports::ImportKind;
...
 use rustc_ast as ast;
 use rustc_ast::visit::{self, Visitor};
 use rustc_data_structures::fx::{FxHashMap, FxIndexMap, FxIndexSet};
 use rustc_data_structures::unord::UnordSet;
 use rustc_errors::{pluralize, MultiSpan};
 use rustc_hir::def::{DefKind, Res};
-use rustc_session::lint::builtin::{MACRO_USE_EXTERN_CRATE, UNUSED_EXTERN_CRATES, UNUSED_IMPORTS};
+use rustc_session::lint::builtin::{
+    MACRO_USE_EXTERN_CRATE, UNUSED_EXTERN_CRATES, UNUSED_IMPORTS, UNUSED_QUALIFICATIONS,
+};
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/check_unused.rs:39]: Style nit: could you keep the single line import style?

**Comment by petrochenkov** [comment]
This PR also needs some more human-readable title.
@rustbot author

File: compiler/rustc_resolve/src/check_unused.rs (hunk 8 above)
Comment (surechen) [reply compiler/rustc_resolve/src/check_unused.rs:39]: Thank you. I tried removing the comma at the end and putting on one line, but `x.py fmt`  format it like this.

Comment (surechen) [reply compiler/rustc_resolve/src/check_unused.rs:39]: > Style nit: could you keep the single line import style?

Thank you. I tried removing the comma at the end and putting on one line, but x.py fmt format it like this.

File: compiler/rustc_resolve/src/check_unused.rs (hunk 7 above)
Comment (surechen) [reply compiler/rustc_resolve/src/check_unused.rs]: > Shouldn't redundant imports be excluded here as well?

Thank you. yes, I add it now, because there is no fix for redundant import, so I didn’t add it at first.

File: compiler/rustc_resolve/src/check_unused.rs (hunk 8 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/check_unused.rs:39]: I meant splitting imports into multiple lines if they are too long for one line.
But that's not too important.

File: compiler/rustc_resolve/src/late.rs [hunk 9]
```diff
@@ -4653,20 +4662,16 @@ impl<'a: 'ast, 'b, 'ast, 'tcx> LateResolutionVisitor<'a, 'b, 'ast, 'tcx> {
...
-                finalize.node_id,
-                finalize.path_span,
-                "unnecessary qualification",
-                lint::BuiltinLintDiag::UnusedQualifications {
-                    removal_span: path[0].ident.span.until(unqualified.ident.span),
-                },
-            );
+        if let Some((seg, binding)) = unqualified {
+            self.r.potentially_unnecessary_qualifications.push(UnnecessaryQualification {
+                binding: binding,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:4670]:
```suggestion
                binding,
```

File: compiler/rustc_resolve/src/check_unused.rs [hunk 10]
```diff
@@ -514,8 +516,59 @@ impl Resolver<'_, '_> {
             }
         }
 
+        let mut redundant_imports = FxIndexSet::default();
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/check_unused.rs:519]:
```suggestion
        let mut redundant_imports = UnordSet::default();
```
This set doesn't need ordering.

File: compiler/rustc_resolve/src/check_unused.rs [hunk 11]
```diff
@@ -514,8 +516,59 @@ impl Resolver<'_, '_> {
...
+            self.lint_buffer.buffer_lint_with_diagnostic(
+                UNUSED_QUALIFICATIONS,
+                unn_qua.node_id,
+                unn_qua.path_span,
+                "unnecessary qualification",
+                BuiltinLintDiag::UnusedQualifications { removal_span: unn_qua.removal_span },
+            );
+        }
+
+        fn check_if_redundant_import(
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/check_unused.rs:549]:
```suggestion
        fn is_redundant_import(
```

File: compiler/rustc_resolve/src/check_unused.rs [hunk 12]
```diff
@@ -514,8 +516,59 @@ impl Resolver<'_, '_> {
...
+        ) -> bool {
+            if let Some(id) = import.id()
+                && redundant_imports.contains(&id)
+            {
+                return true;
+            }
+            false
+        }
+
+        fn check_if_unused_import(
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/check_unused.rs:561]:
```suggestion
        fn is_unused_import(
```

**Comment by surechen** [comment]
> Both `potentially_unnecessary_qualifications` and `redundant_imports` collections are typically empty or very small, so this probably doesn't need a separate perf run. r=me after addressing remaining comments. @rustbot author

Done. Thank you.
