### PR TITLE
fix rustdoc search says “Consider searching for "null" instead.” #149324

### LINKED ISSUE #149324: rustdoc search says “Consider searching for "null" instead.”
# Reproduction Steps
1. Visit <https://doc.rust-lang.org/nightly/std/>
2. Enter “`-> Result<Foo, E>`” in the search box.

# Output
> Type "Foo" not found and used as generic parameter. Consider searching for "null" instead.

The “null” part makes no sense. Probably that sentence should be removed when there is no suggestion.

# Version
rustdoc 1.93.0-nightly (c871d09d1 2025-11-24)
Browser: Chrome 142.0.7444.176

### PR DESCRIPTION
**Pull request by asukaminato0721**
fix rust-lang/rust#149324

Now builds the “generic parameter” correction banner from discrete sentence fragments and appends the “Consider searching …” clause only when query.proposeCorrectionTo is non-null, so the UI no longer renders null as the suggested type.

Adds a PARSED section with two queries: one typo (Result<SomeTraiz>) that still produces a concrete suggestion and one fully unknown type (Result<NoSuchTrait>) that leaves proposeCorrectionTo null.

### CODE REVIEW

File: src/librustdoc/html/static/js/search.js [hunk 1]
```diff
@@ -5050,9 +5050,11 @@ ${obj.displayPath}<span class="${type}">${name}</span>\
     if (query.proposeCorrectionFrom !== null && isTypeSearch) {
         const orig = query.proposeCorrectionFrom;
         const targ = query.proposeCorrectionTo;
-        correctionOutput = "<h3 class=\"search-corrections\">" +
-            `Type "${orig}" not found and used as generic parameter. ` +
-            `Consider searching for "${targ}" instead.</h3>`;
+        const parts = [`Type "${orig}" not found and used as generic parameter.`];
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/search.js]: Instead of making an array, wouldn't a string be simpler since you push everything directly into it?

**Review by GuillaumeGomez — APPROVED** [review]
