### PR TITLE
librustc_metadata: Pass a default value when unwrapping a span

### LINKED ISSUE #57323: Specifying `static-nobundle` on command line causes an internal compiler error
Reproduction:
```rust
rustc -l static-nobundle=nonexistent main.rs

---

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic
```

This happens because code in https://github.com/rust-lang/rust/blob/c0bbc3927e28c22edefe6a1353b5ecc95ea9a104/src/librustc_metadata/native_libs.rs#L166 assumes that the span always exists, which is not true for things passed from command line.

### PR DESCRIPTION
**Pull request by AB1908**
Fixes #57323.

When compiling with `static-nobundle` a-la 

`rustc -l static-nobundle=nonexistent main.rs`

we now get a neat output in the form of:

```
error[E0658]: kind="static-nobundle" is feature gated (see issue #37403)
  |
  = help: add #![feature(static_nobundle)] to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```
The build and tests completed successfully on my machine. Should I be adding a new test?

### CODE REVIEW

**Comment by AB1908** [comment]
Even though I've fixed the issue (at least to my knowledge), I have no clue what static-nobundle is or does. Could someone point me to some info? I also tried compiling a Hello World! program after adding `#![feature(static_nobundle)]` but I got an error `linking with cc failed`.

**Comment by petrochenkov** [comment]
@AB1908 
>Even though I've fixed the issue (at least to my knowledge), I have no clue what static-nobundle is or does. 

`rustc -l static-nobundle=foo main.rs` will link our `main` program with a static library `foo` (file `libfoo.a` on Linux) found somewhere in library search directories.
This is usually used for linking to code written in C or Assembler.

"linking with cc failed" is reported because no library named `nonexistent` is found, so it's a linking error.

>Should I be adding a new test?

Yes, this needs a test.
A proper place for the test is probably `src/test/ui/feature-gates/feature-gate-static-nobundle-2.rs` and the test will look something like this
```
// compile-flags: -l static-nobundle=nonexistent

fn main() {}
```
\+ `ERROR` annotation + `.stderr` file with test output.

**Comment by AB1908** [comment]
> + `ERROR` annotation + `.stderr` file with test output.

I think I've added the necessary tests properly but I have another issue to raise. I couldn't figure out from the docs where to place the `ERROR` annotation as it should fail because of a flag in this case rather than from some source code. However, the testing framework pointed out that it was looking for an `ERROR` in line 1 rather than say 7 and I was able to fix that up. Should we add some relevant snippet about this in the testing docs to save the hassle for a new contributor or did I not look hard enough?

**Comment by petrochenkov** [comment]
@bors r+ rollup
Thanks!

>Should we add some relevant snippet about this in the testing docs to save the hassle for a new contributor

Sure, if you think it would be useful.
As you said, the testing framework already kind of helps here pointing to the line 1.

File: src/librustc_metadata/native_libs.rs [hunk 1]
```diff
@@ -163,7 +163,7 @@ impl<'a, 'tcx> Collector<'a, 'tcx> {
            !self.tcx.features().static_nobundle {
             feature_gate::emit_feature_err(&self.tcx.sess.parse_sess,
                                            "static_nobundle",
-                                           span.unwrap(),
+                                           span.unwrap_or_else(|| syntax_pos::DUMMY_SP),
```
Comment (eddyb) [inline src/librustc_metadata/native_libs.rs]: This should be `span.unwrap_or(syntax_pos::DUMMY_SP)`, as it's just a constant.

Comment (petrochenkov) [reply src/librustc_metadata/native_libs.rs]: Oh. I didn't even notice.
