### PR TITLE
only replace the intended comma in pattern suggestions

### LINKED ISSUE #143330: `...or a vertical bar to match` bugs
### Code

```Rust
fn main() {
    struct Foo { x: i32, ch: char }
    let pos = Foo { x: 2, ch: 'x' };
    match pos {
        Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' } => (),
        _ => todo!(),
    }
}
```

### Current output

```Shell
Compiling test_ v0.1.0 (/home/lrne/Project/Rust/test_)
error: unexpected `,` in pattern
 --> src/main.rs:5:30
  |
5 |         Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' } => (),
  |                              ^
  |
help: try adding parentheses to match on a tuple...
  |
5 |         (Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' }) => (),
  |         +                                            +
help: ...or a vertical bar to match on multiple alternatives
  |
5 -         Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' } => (),
5 +         Foo { x: 2 | ch: ' |' } | Foo { x: 3 | ch: '@' } => (),
  |

error: could not compile `test_` (bin "test_") due to 1 previous error
```

### Desired output

```Shell
Compiling test_ v0.1.0 (/home/lrne/Project/Rust/test_)
error: unexpected `,` in pattern
 --> src/main.rs:5:30
  |
5 |         Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' } => (),
  |                              ^
  |
help: try adding parentheses to match on a tuple...
  |
5 |         (Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' }) => (),
  |         +                                            +
help: ...or a vertical bar to match on multiple alternatives
  |
5 -         Foo { x: 2, ch: ',' }, Foo { x: 3, ch: '@' } => (),
5 +         Foo { x: 2, ch: ',' } | Foo { x: 3, ch: '@' } => (),
  |

error: could not compile `test_` (bin "test_") due to 1 previous error
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.88.0-nightly (a15cce269 2025-04-17)
binary: rustc
commit-hash: a15cce2690e8fab72422515c9dc02c6fbc506733
commit-date: 2025-04-17
host: aarch64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by karolzwolak**
Only suggest to replace the intended comma, not all bars in the pattern.
Fixes rust-lang/rust#143330.
This continues rust-lang/rust#143331, the credit for making the fix goes to @A4-Tacks. I just blessed tests and added a regression test.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -2947,26 +2947,24 @@ impl<'a> Parser<'a> {
...
+            vec![
+                (seq_span.shrink_to_lo(), "(".to_string()),
+                (seq_span.shrink_to_hi(), ")".to_string()),
+            ],
+            Applicability::MachineApplicable,
+        );
+        if let CommaRecoveryMode::EitherTupleOrPipe = rt {
+            err.span_suggestion(
+                comma_span,
+                "...or a vertical bar to match on alternative",
```
Comment (lcnr) [inline compiler/rustc_parse/src/parser/diagnostics.rs]: that reads weirdly, I think it should still be "alternatives"?

File: tests/ui/suggestions/only-replace-intended-bar-not-all-in-pattern.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
+//@ run-rustfix
+
+// Regression test for issue #143330.
+// Ensure we suggest to replace only the intended bar with a comma, not all bars in the pattern.
```
Comment (lcnr) [inline tests/ui/suggestions/only-replace-intended-bar-not-all-in-pattern.rs]: we're replacing commas with a bar, not the other way around

Comment (karolzwolak) [reply tests/ui/suggestions/only-replace-intended-bar-not-all-in-pattern.rs]: Yeah, idk what happened here hah

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (karolzwolak) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Plural 'alternatives' does sound a bit better

**Comment by karolzwolak** [comment]
I addressed the comments. Appreciate the quick review.
