### PR TITLE
revert #75443, update mir validator

### LINKED ISSUE #75313: Panic when compiling gluon on 1.46
<!--
Thank you for finding an Internal Compiler Error! 🧊  If possible, try to provide
a minimal verifiable example. You can read "Rust Bug Minimization Patterns" for
how to create smaller examples.

http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/

-->

I created an empty hello world project with Cargo, added the "gluon" library to it, then tried to compile.
I understand this is something more than just an incompatibility between the nightly compiler and the library.
Does not occur on stable.

### Code
There's no code, I added `gluon = "0.16.1"` to Cargo.toml of an empty project.


### Meta
`rustc --version --verbose`:
```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

### Error output

```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:814 ~ gluon[bf1c]::std_lib[0]::regex[0]::load[0]), const_param_did: None }) (end of phase Optimized) at bb26[20]:            
encountered `Assign` statement with incompatible types:                                                                                                                                                          
left-hand side has type: fn(&std_lib::regex::Regex, &str) -> std::option::Option<vm::api::Collect<impl std::iter::Iterator>>                                                                                     
right-hand side has type: for<'r, 's> fn(&'r std_lib::regex::Regex, &'s str) -> std::option::Option<vm::api::Collect<impl std::iter::Iterator>>                                                                  
  --> /home/jcd/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.16.1/src/std_lib/regex.rs:90:39                                                                                                          
   |                                                                                                                                                                                                             
90 |             captures => primitive!(2, std::regex::prim::captures),                                                                                                                                          
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            
   |                                                                                                                                                                                                             
   = note: delayed at src/librustc_mir/transform/validate.rs:140:36                                                                                                                                              
                                                                                                                                                                                                                 
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:2715 ~ gluon[bf1c]::std_lib[0]::regex[0]::load[0]::wrapper[3]), const_param_did: None }) (end of phase Optimized) at bb0[0]: 
encountered `Assign` statement with incompatible types:                                                                                                                                                          
left-hand side has type: fn(&std_lib::regex::Regex, &str) -> std::option::Option<vm::api::Collect<impl std::iter::Iterator>>                                                                                     
right-hand side has type: for<'r, 's> fn(&'r std_lib::regex::Regex, &'s str) -> std::option::Option<vm::api::Collect<impl std::iter::Iterator>>                                                                  
  --> /home/jcd/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon-0.16.1/src/std_lib/regex.rs:90:39                                                                                                          
   |                                                                                                                                                                                                             
90 |             captures => primitive!(2, std::regex::prim::captures),                                                                                                                                          
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                                
   = note: delayed at src/librustc_mir/transform/validate.rs:140:36

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (6c8927b0c 2020-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `gluon`.

```
</details>

### LINKED ISSUE #75992: Increasingly slow compilation as more levels of `async` are added in Rust 1.46
I upgraded from 1.45 to 1.46 today and a crate I'm working on seems to hang forever while compiling. I've attempted to create a somewhat minimal test case. For convenience here's a repo that includes the code below: https://github.com/nicholasbishop/rust146hang

Cargo.toml:
```toml
[package]
name = "rust146hang"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "2.0"
bb8 = "0.4"
bb8-postgres = "0.4"
tokio-postgres = "0.5"
```

src/lib.rs:
```rust
use actix_web::{web, HttpResponse, Responder};
use bb8_postgres::PostgresConnectionManager;
use tokio_postgres::NoTls;

type Pool = bb8::Pool<PostgresConnectionManager<NoTls>>;

async fn handle_req_1(pool: &Pool) {
    let conn = pool.get().await.unwrap();
    conn.query_one("", &[]).await.unwrap();
}

async fn handle_req_2(pool: &Pool) {
    handle_req_1(pool).await;
}

async fn handle_req_3(pool: &Pool) {
    handle_req_2(pool).await;
}

async fn handle_req_4(pool: &Pool) {
    handle_req_3(pool).await;
}

async fn handle_req_5(pool: &Pool) {
    handle_req_4(pool).await;
}

async fn handle_req_final(pool: web::Data<Pool>) -> impl Responder {
    handle_req_5(pool.get_ref()).await;
    HttpResponse::Ok().finish()
}

pub fn app_config(config: &mut web::ServiceConfig) {
    config.service(
        web::scope("").route("/api", web::post().to(handle_req_final)),
    );
}
```

I've found that the slowness seems tied to the depth of the async call chain. In the example code I have a long call chain: `handle_req_1` is called by `handle_req_2` is called by `handle_req_3`, etc. Here's the compilation timing I've observed when changing `handle_req_final` to directly call one of the `handle_req_N` functions:

```
handle_req_1 -> 0m12s
handle_req_2 -> 0m28s
handle_req_3 -> 1m06s
handle_req_4 -> 2m18s
handle_req_5 -> 5m01s
```

These times only include building the rust146hang lib, not the dependencies.

(Caveat: unscientific timings, these are not averaged over multiple
runs or anything.)

```
$ cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)
$ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
```

### PR DESCRIPTION
**Pull request by lcnr**
This PR reverts rust-lang#75443 to fix rust-lang#75992 and instead uses rust-lang#75419 to fix rust-lang#75313.

Adapts rust-lang#75419 to correctly deal with unevaluated constants as otherwise some `feature(const_evaluatable_checked)` tests would ICE.

Note that rust-lang#72793 was also fixed by rust-lang#75443, but as that issue only concerns `feature(type_alias_impl_trait)` I deleted that test case for now and would reopen that issue.

rust-lang#75443 may have also allowed some other code to now successfully compile which would make this revert a breaking change after 2 stable versions, but I hope that this is a purely theoretical concern.

See https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/generator.20upvars/near/214617274 for more reasoning about this.

r? @nikomatsakis @eddyb @RalfJung

### CODE REVIEW

**Comment by yotamofek** [comment]
@lcnr the binary that has been taking ~30mins for me to build is now taking 2:20 minutes to build from scratch, using rustc with your branch!!!!!!

thank you so much for ALL your work on this! I read on zulip you mentioned that it's the first time you felt unpleasant opening a PR... well, if it means anything, this PR is very much pleasant to me. I've been waiting for this for a while now! I'm so far from understanding the compiler internals to know what the underlying issue was, but just wanted to express my gratitude as an end-user of the amazing Rust language. And also let you know that it certainly fixed the issue I was experiencing :P

**Comment by Mark-Simulacrum** [comment]
> #75443 may have also allowed some other code to now successfully compile which would make this revert a breaking change after 2 stable versions, but I hope that this is a purely theoretical concern.

Can you say more about this? Maybe a code example if possible? I think if we are to land a breaking change I'd prefer to have pre-prepared a note to include in the release notes, at least.

File: compiler/rustc_mir/src/transform/validate.rs [hunk 1]
```diff
@@ -68,79 +69,24 @@ pub fn equal_up_to_regions(
...
+                // lifetimes in invariant positions could matter (e.g. through associated types).
+                // We rely on the fact that layout was confirmed to be equal above.
+                lt_op: |_| tcx.lifetimes.re_erased,
+                // Leave consts and types unchanged.
+                ct_op: |ct| ct,
+                ty_op: |ty| ty,
+            }),
+        )
+    };
+    tcx.infer_ctxt().enter(|infcx| infcx.can_eq(param_env, normalize(src), normalize(dest)).is_ok())
```
Comment (RalfJung) [inline compiler/rustc_mir/src/transform/validate.rs:89]: This seems reasonable -- it is pretty close to what I had before we went for `TypeRelation`, except for this `infcx.can_eq` thing which I never saw before so I cannot comment on it.^^

Comment (lcnr) [reply compiler/rustc_mir/src/transform/validate.rs:89]: Using `normalize(src) == normalize(dest)` would fail to unify 2 generic consts, so the following would fail mir validation
```rust
#[feature(const_generics, lazy_normalization_consts)]
fn test<const N: usize>() -> [u8; N + 1] {
    [0; N + 1]
}
```

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:89]: So generic consts are not interned the same way as others? Or what does the difference stem from?

Comment (lcnr) [reply compiler/rustc_mir/src/transform/validate.rs:89]: the 2 `N + 1` are two distinct mir bodies so we have `ConstKind::Unevaluated(DefId1, substs: [N])` and `ConstKind::Unevaluated(DefId2, substs: [N])` which should still be considered equal. This doesn't really exist for types afaik as we can partially normalize them.

We may want to change this in the future but I don't yet know how we would do that

**Comment by lcnr** [comment]
> Can you say more about this? Maybe a code example if possible?

I tried to find something which worked because of #75443 on stable but wasn't able to.
My concern is something like #76956
```rust
use std::ops::Deref;

fn use_data(v: &'static i32, user: &dyn for<'a> Fn(<Box<&'a i32> as Deref>::Target)) {
    //~^ ERROR expected function, found `&dyn for<'a> Fn(<Box<&'a i32> as Deref>::Target)`
    user(v)
}

fn use_data(v: &'static i32, user: &dyn for<'a> Fn(&'a i32)) {
    // OK
    user(v)
}
```
where we somehow use an opaque type instead of `<Box<&'a i32> as Deref>::Target`. But it looks like that isn't possible on stable yet so we might be safe.

**Comment by pnkfelix** [comment]
beta-nominating to discuss whether we would consider back porting this based on the degree of the stable-to-stable compilation-time regression

**Comment by oli-obk** [comment]
cc @rust-lang/wg-mir-opt

File: compiler/rustc_mir/src/transform/validate.rs [hunk 2]
```diff
@@ -68,79 +69,24 @@ pub fn equal_up_to_regions(
...
-    let mut relator: LifetimeIgnoreRelation<'tcx> = LifetimeIgnoreRelation { tcx: tcx, param_env };
-    relator.relate(src, dest).is_ok()
+    // Normalize lifetimes away on both sides, then compare.
+    let param_env = param_env.with_reveal_all_normalized(tcx);
+    let normalize = |ty: Ty<'tcx>| {
+        tcx.normalize_erasing_regions(
+            param_env,
+            ty.fold_with(&mut BottomUpFolder {
+                tcx,
+                // We just erase all late-bound lifetimes, but this is not fully correct (FIXME):
```
Comment (nikomatsakis) [inline compiler/rustc_mir/src/transform/validate.rs:79]: I don't fully understand this comment. I'm not sure how much it matters, but it'd be nice to have a more detailed explanation of how lifetimes could matter. I guess it depends on a bit of context that I seem to be missing, about the broader role of this function.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:89]: "which would still be considered *un*equal", you mean?

**Review by nikomatsakis — APPROVED** [review]
Generally looks reasonable, though I think I'm also missing some context to fully understand what's going on.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_mir/src/transform/validate.rs:89]: `ConstKind::Unevaluated(DefId1, substs: [N])` and `ConstKind::Unevaluated(DefId2, substs: [N])` are considered unequal when using `Ty == Ty` atm but are - and should be - considered equal with `feature(const_evaluatable_checked)`.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:88]: This is the concern that @eddyb keeps raising; [another instance of that is here](https://github.com/rust-lang/rust/pull/77196#issuecomment-719919173). It's something about using lifetimes in invariant positions to force two different trait implementations to be used which could have different associated types which could make this check unsound. I don't have more than a fuzzy understanding of this, and I forgot if we ever were able to come up with a concrete example.

Comment (eddyb) [reply compiler/rustc_mir/src/transform/validate.rs:88]: Apologies for not providing an example initially, given how trivial it is to construct "transmute in safe code" gadgets from associated type unsoundness (the hard part is you have to intentionally make `rustc` unsound enough to truly confirm something else doesn't defeat the example).
I've just posted https://github.com/rust-lang/rust/pull/77196#issuecomment-721036102, hope that helps.

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:88]: @eddyb also pointed out that we should probably clarify the comment to explicitly mention projections -- specifically, if I understood correctly, the concern is about erasing a lifetime in `T` when the type is `T::Assoc`.

Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:88]: I see, so the concern here is that we are not preserving the binding levels? Let me re-read this code then.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:98]: I see. Yes, that makes sense. The point here is that `normalize` doesn't do any kind of evaluation of unevaluated constants, so simple equality is not especially meaningful.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 2 above)
Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:88]: OK well I definitely agree this requires a FIXME. I don't know that it has to block this PR from *landing*, but I'm not sure I have a good handle on the full repercussions here. I guess the question is why we are not using an existing function to erase or normalize regions and instead rolling our own here.

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:88]: > I see, so the concern here is that we are not preserving the binding levels? Let me re-read this code then.

Binding levels? I have no idea what you are talking about.^^

>  I guess the question is why we are not using an existing function to erase or normalize regions and instead rolling our own here.

I tried all the existing ones (that I could find) and none of them worked.^^ (As in, none of them accepted all the code out there.) Then I asked @eddyb what to do and we ended up with this.

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:88]: > I don't know that it has to block this PR from landing

No, it certainly is not a blocker. This is an old FIXME that was removed when we switched to `TypeRelation` and now re-appears since we are switching back to `BottomUpFolder`.

File: compiler/rustc_mir/src/transform/validate.rs [hunk 3]
```diff
@@ -77,79 +78,24 @@ pub fn equal_up_to_regions(
...
+                // lifetimes in invariant positions could matter (e.g. through associated types).
```
Comment (RalfJung) [inline compiler/rustc_mir/src/transform/validate.rs:89]:
```suggestion
                // lifetimes in projections could matter (e.g. `T<'a>::Assoc`).
```
We should clarify this comment, but I am not sure how to best do that.^^

Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:89]: Maybe we should add a link to https://github.com/rust-lang/rust/pull/77196#issuecomment-721036102.

File: compiler/rustc_mir/src/transform/validate.rs (hunk 2 above)
Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:88]: What I meant by "binding level" is that `for<'a> fn(fn(&'a u32))` and `fn(for<'a> fn(&'a u32))` are considered distinct types (and `fn(&'a u32)`, where `'a` appears free, is also distinct) by various parts of Rust. We've been slowly changing the model here but I think we'll not be able to change this completely. In particular, the coherence code accepts distinct impls (as eddyb demonstrated) for some such cases.

Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:88]: see also https://github.com/rust-lang/rust/issues/56105 and https://github.com/rust-lang/rust/pull/72493

File: compiler/rustc_mir/src/transform/validate.rs (hunk 3 above)
Comment (nikomatsakis) [reply compiler/rustc_mir/src/transform/validate.rs:89]: I'd probably inline the comment, but I agree we can improve the wording here. Something like:

> FIXME: We erase all late-bound lifetimes, but this is not fully correct. If you have a type like
`<for<'a> fn(&'a u32) as SomeTrait>::Assoc`, this is not necessarily equivalent to `<fn(&'static u32) as SomeTrait>::Assoc`, since one may have an `impl SomeTrait for fn(&32)` and `impl SomeTrait for fn(&'static u32)` at the same time which specify distinct values for `Assoc`. (See also https://github.com/rust-lang/rust/issues/56105)

**Comment by nikomatsakis** [comment]
r=me with improved comment wording (Cc @lcnr)

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/61797weeklymeeting2020110554818.html#215724464) in T-compiler meeting.

@rustbot modify labels: beta-accepted

File: compiler/rustc_mir/src/transform/validate.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/transform/validate.rs:88]: > What I meant by "binding level" is that for<'a> fn(fn(&'a u32)) and fn(for<'a> fn(&'a u32)) are considered distinct types

Sure, it would be really strange if those would be the same type. The outer function in the latter may pick different lifetimes for different calls of the inner function; that is not the case for the former.

**Comment by lcnr** [comment]
used the fixme recommended by @nikomatsakis in https://github.com/rust-lang/rust/pull/78410#discussion_r518273815,

@bors r=nikomatsakis rollup=never

**Comment by Mark-Simulacrum** [comment]
@lcnr should we pull the new commit into the beta backport as well?

**Comment by lcnr** [comment]
It only changes a comment, so while it wouldn't hurt to do so I don't really think it matters

**Comment by Dylan-DPC** [comment]
@bors p=4 
(giving this a bit of a priority bump)
