### PR TITLE
Delegation: fix ICE on wrong `Self` instantiation

### LINKED ISSUE #119919: ICE: delegation: out of range when substituting
snippet:
````rust
trait Trait {
    fn static_method(&self, x: i32) -> i32 { x }
}

struct F;

struct S(F);
impl Trait for S {
    reuse Trait::bar { &self.0 }
    reuse <F as Trait>
    reuse Trait::baz { &self.0 }
}

impl S {
    reuse Trait::baz { &self.0 }
}


fn main() {
    reuse <S as Trait>::static_method;
    reuse <S as Trait>::static_method2 { (self) }
    #[inline]
    
    assert_eq!(42, static_method(42));
}


````

Version information
````
rustc 1.77.0-nightly (89110dafe 2024-01-13)
binary: rustc
commit-hash: 89110dafe79621fa07d6cd7c8493dd1d0a83cfaf
commit-date: 2024-01-13
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected `::`, found `reuse`
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:11:5
   |
8  | impl Trait for S {
   |                  - while parsing this item list starting here
9  |     reuse Trait::bar { &self.0 }
10 |     reuse <F as Trait>
   |                       - expected `::`
11 |     reuse Trait::baz { &self.0 }
   |     ^^^^^ unexpected token
12 | }
   | - the item list ends here

error[E0407]: method `bar` is not a member of trait `Trait`
 --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:9:5
  |
9 |     reuse Trait::bar { &self.0 }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Trait`

error[E0425]: cannot find function `bar` in trait `Trait`
 --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:9:18
  |
9 |     reuse Trait::bar { &self.0 }
  |                  ^^^ not found in `Trait`

error[E0425]: cannot find function `baz` in trait `Trait`
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:15:18
   |
15 |     reuse Trait::baz { &self.0 }
   |                  ^^^ not found in `Trait`

error[E0576]: cannot find method or associated constant `static_method2` in trait `Trait`
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:21:25
   |
2  |     fn static_method(&self, x: i32) -> i32 { x }
   |     -------------------------------------- similarly named associated function `static_method` defined here
...
21 |     reuse <S as Trait>::static_method2 { (self) }
   |                         ^^^^^^^^^^^^^^ help: an associated function with a similar name exists: `static_method`

error[E0658]: functions delegation is not yet fully implemented
 --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:9:5
  |
9 |     reuse Trait::bar { &self.0 }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
  = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:15:5
   |
15 |     reuse Trait::baz { &self.0 }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:20:5
   |
20 |     reuse <S as Trait>::static_method;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:21:5
   |
21 |     reuse <S as Trait>::static_method2 { (self) }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

warning: unused attribute `inline`
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:22:5
   |
22 |     #[inline]
   |     ^^^^^^^^^
   |
note: the built-in attribute `inline` will be ignored, since it's applied to the macro invocation `assert_eq`
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:24:5
   |
24 |     assert_eq!(42, static_method(42));
   |     ^^^^^^^^^
   = note: `#[warn(unused_attributes)]` on by default

warning: unnecessary parentheses around block return value
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:21:42
   |
21 |     reuse <S as Trait>::static_method2 { (self) }
   |                                          ^    ^
   |
   = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
   |
21 -     reuse <S as Trait>::static_method2 { (self) }
21 +     reuse <S as Trait>::static_method2 { self }
   |

error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:898:9: type parameter `Self/#0` (Self/#0/0) out of range when substituting, args=[]

thread 'rustc' panicked at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/compiler/rustc_errors/src/lib.rs:939:30:
Box<dyn Any>
stack backtrace:
   0:     0x7fe11298c7e6 - std::backtrace_rs::backtrace::libunwind::trace::h4f92a9ab1e969130
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fe11298c7e6 - std::backtrace_rs::backtrace::trace_unsynchronized::hff5adbaff3a8cfb8
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe11298c7e6 - std::sys_common::backtrace::_print_fmt::h9d3e0e63f6f89eaf
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fe11298c7e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2d31e6c8aa8ef934
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe1129deec0 - core::fmt::rt::Argument::fmt::hd4eaf83b012a42ab
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/fmt/rt.rs:142:9
   5:     0x7fe1129deec0 - core::fmt::write::hb507e806b3ae16c4
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fe11298014f - std::io::Write::write_fmt::h203bf95b6a67c7a0
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/io/mod.rs:1810:15
   7:     0x7fe11298c5c4 - std::sys_common::backtrace::_print::h2f732cf10966ea1c
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fe11298c5c4 - std::sys_common::backtrace::print::hef45416e244164df
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fe11298f357 - std::panicking::default_hook::{{closure}}::h1a73802a0a993acf
  10:     0x7fe11298f0b9 - std::panicking::default_hook::h34548737700c4b4d
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:292:9
  11:     0x7fe11574e80c - std[d6f21989bfff4f42]::panicking::update_hook::<alloc[21b544e6cc75226b]::boxed::Box<rustc_driver_impl[bce72efeea91a1de]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fe11298faa6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb0b823449909a650
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2030:9
  13:     0x7fe11298faa6 - std::panicking::rust_panic_with_hook::h60e4310ab2a16e4e
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:785:13
  14:     0x7fe1157808c4 - std[d6f21989bfff4f42]::panicking::begin_panic::<rustc_errors[eaf17d4bd6ee3375]::ExplicitBug>::{closure#0}
  15:     0x7fe11577d1c6 - std[d6f21989bfff4f42]::sys_common::backtrace::__rust_end_short_backtrace::<std[d6f21989bfff4f42]::panicking::begin_panic<rustc_errors[eaf17d4bd6ee3375]::ExplicitBug>::{closure#0}, !>
  16:     0x7fe11577ce36 - std[d6f21989bfff4f42]::panicking::begin_panic::<rustc_errors[eaf17d4bd6ee3375]::ExplicitBug>
  17:     0x7fe11578b9d1 - <rustc_errors[eaf17d4bd6ee3375]::diagnostic_builder::BugAbort as rustc_errors[eaf17d4bd6ee3375]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fe115b50e8b - <rustc_errors[eaf17d4bd6ee3375]::DiagCtxt>::bug::<alloc[21b544e6cc75226b]::string::String>
  19:     0x7fe115be8c6b - rustc_middle[63813a132a817cd4]::util::bug::opt_span_bug_fmt::<rustc_span[6e44e330265df079]::span_encoding::Span>::{closure#0}
  20:     0x7fe115bd10da - rustc_middle[63813a132a817cd4]::ty::context::tls::with_opt::<rustc_middle[63813a132a817cd4]::util::bug::opt_span_bug_fmt<rustc_span[6e44e330265df079]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fe115bd0f58 - rustc_middle[63813a132a817cd4]::ty::context::tls::with_context_opt::<rustc_middle[63813a132a817cd4]::ty::context::tls::with_opt<rustc_middle[63813a132a817cd4]::util::bug::opt_span_bug_fmt<rustc_span[6e44e330265df079]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fe113b85a10 - rustc_middle[63813a132a817cd4]::util::bug::bug_fmt
  23:     0x7fe115bdecf6 - <rustc_middle[63813a132a817cd4]::ty::generic_args::ArgFolder>::type_param_out_of_range
  24:     0x7fe116a07563 - <rustc_middle[63813a132a817cd4]::ty::generic_args::ArgFolder as rustc_type_ir[a282ecd95494b706]::fold::TypeFolder<rustc_middle[63813a132a817cd4]::ty::context::TyCtxt>>::fold_ty
  25:     0x7fe116a02493 - <rustc_middle[63813a132a817cd4]::ty::generic_args::ArgFolder as rustc_type_ir[a282ecd95494b706]::fold::TypeFolder<rustc_middle[63813a132a817cd4]::ty::context::TyCtxt>>::fold_ty
  26:     0x7fe116af35aa - <rustc_middle[63813a132a817cd4]::ty::Ty>::fn_sig
  27:     0x7fe116ebbb1d - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_path
  28:     0x7fe11740ef25 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_call
  29:     0x7fe1174dbc39 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7fe1174dc73f - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7fe1174df710 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7fe1173f57df - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_match
  33:     0x7fe1174dcb09 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7fe1173f0fa3 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_block_with_expected
  35:     0x7fe1174dc049 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  36:     0x7fe117055848 - rustc_hir_typeck[995280b49f849d23]::check::check_fn
  37:     0x7fe116cd3f02 - rustc_hir_typeck[995280b49f849d23]::typeck
  38:     0x7fe116cd3289 - rustc_query_impl[f8b584d7216df600]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f8b584d7216df600]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 8usize]>>
  39:     0x7fe116abfdf9 - rustc_query_system[13649e0efc92577a]::query::plumbing::try_execute_query::<rustc_query_impl[f8b584d7216df600]::DynamicConfig<rustc_query_system[13649e0efc92577a]::query::caches::VecCache<rustc_span[6e44e330265df079]::def_id::LocalDefId, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f8b584d7216df600]::plumbing::QueryCtxt, false>
  40:     0x7fe116abfa90 - rustc_query_impl[f8b584d7216df600]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7fe116fe99cc - <rustc_middle[63813a132a817cd4]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[f88d56455d931b67]::check_crate::{closure#6}>::{closure#0}
  42:     0x7fe116fe82c4 - rustc_hir_analysis[f88d56455d931b67]::check_crate
  43:     0x7fe117494419 - rustc_interface[37b6cebe1bce16]::passes::analysis
  44:     0x7fe11749405f - rustc_query_impl[f8b584d7216df600]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f8b584d7216df600]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7fe1179cd040 - rustc_query_system[13649e0efc92577a]::query::plumbing::try_execute_query::<rustc_query_impl[f8b584d7216df600]::DynamicConfig<rustc_query_system[13649e0efc92577a]::query::caches::SingleCache<rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f8b584d7216df600]::plumbing::QueryCtxt, false>
  46:     0x7fe1179cce47 - rustc_query_impl[f8b584d7216df600]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7fe1177343ed - rustc_interface[37b6cebe1bce16]::interface::run_compiler::<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}
  48:     0x7fe1179f3546 - std[d6f21989bfff4f42]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[37b6cebe1bce16]::util::run_in_thread_with_globals<rustc_interface[37b6cebe1bce16]::util::run_in_thread_pool_with_globals<rustc_interface[37b6cebe1bce16]::interface::run_compiler<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>
  49:     0x7fe1179f3373 - <<std[d6f21989bfff4f42]::thread::Builder>::spawn_unchecked_<rustc_interface[37b6cebe1bce16]::util::run_in_thread_with_globals<rustc_interface[37b6cebe1bce16]::util::run_in_thread_pool_with_globals<rustc_interface[37b6cebe1bce16]::interface::run_compiler<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#1} as core[a757d3bbb7cc29b8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  50:     0x7fe1129999d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc62465ce3696edbb
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2016:9
  51:     0x7fe1129999d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2898b364df1453ed
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2016:9
  52:     0x7fe1129999d5 - std::sys::unix::thread::Thread::new::thread_start::hefe0ce868779f0f1
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys/unix/thread.rs:108:17
  53:     0x7fe1127859eb - <unknown>
  54:     0x7fe1128097cc - <unknown>
  55:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (89110dafe 2024-01-13) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error[E0308]: mismatched types
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:20:25
   |
20 |     reuse <S as Trait>::static_method;
   |           --------------^^^^^^^^^^^^^
   |           |             |
   |           |             expected `&S`, found `&Self`
   |           arguments to this function are incorrect
   |
   = note: expected reference `&S`
              found reference `&Self`
note: method defined here
  --> /tmp/icemaker_global_tempdir.bHkheWGOf7Q4/rustc_testrunner_tmpdir_reporting.hSy8JnLxBMYR/mvce.rs:2:8
   |
2  |     fn static_method(&self, x: i32) -> i32 { x }
   |        ^^^^^^^^^^^^^ -----

error: aborting due to 11 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0308, E0407, E0425, E0576, E0658.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

### LINKED ISSUE #119921: ICE. delegation: `index out of bounds` with syntax error
snippet:
````rust

trait Trait {
    fn static_method2(, ) -> i32 { x + y }
    fn baz<'a>(&self, x: &'a i32) -> &'a i32 { x }
}

struct F;

struct S(F);
impl Trait for S {
    reuse <S as Trait>::static_method2 { (self); // oopsie
    reuse Trait::baz { &self.0 }
}
}


````

Version information
````
rustc 1.77.0-nightly (89110dafe 2024-01-13)
binary: rustc
commit-hash: 89110dafe79621fa07d6cd7c8493dd1d0a83cfaf
commit-date: 2024-01-13
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected argument name, found `,`
 --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:3:23
  |
3 |     fn static_method2(, ) -> i32 { x + y }
  |                       ^ expected argument name

error[E0425]: cannot find value `x` in this scope
 --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:3:36
  |
3 |     fn static_method2(, ) -> i32 { x + y }
  |                                    ^ help: a unit struct with a similar name exists: `F`
...
7 | struct F;
  | --------- similarly named unit struct `F` defined here

error[E0425]: cannot find value `y` in this scope
 --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:3:40
  |
3 |     fn static_method2(, ) -> i32 { x + y }
  |                                        ^ help: a unit struct with a similar name exists: `F`
...
7 | struct F;
  | --------- similarly named unit struct `F` defined here

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:12:5
   |
12 |     reuse Trait::baz { &self.0 }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

error[E0658]: functions delegation is not yet fully implemented
  --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:11:5
   |
11 | /     reuse <S as Trait>::static_method2 { (self); // oppsie
12 | |     reuse Trait::baz { &self.0 }
13 | | }
   | |_^
   |
   = note: see issue #118212 <https://github.com/rust-lang/rust/issues/118212> for more information
   = help: add `#![feature(fn_delegation)]` to the crate attributes to enable

warning: anonymous parameters are deprecated and will be removed in the next edition
 --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:3:22
  |
3 |     fn static_method2(, ) -> i32 { x + y }
  |                      ^ help: try naming the parameter or explicitly ignoring it: `_: (`
  |
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2018!
  = note: for more information, see issue #41686 <https://github.com/rust-lang/rust/issues/41686>
  = note: `#[warn(anonymous_parameters)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:14:2
   |
14 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs`

thread 'rustc' panicked at compiler/rustc_middle/src/ty/generics.rs:233:25:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x7f2c60f9b7e6 - std::backtrace_rs::backtrace::libunwind::trace::h4f92a9ab1e969130
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f2c60f9b7e6 - std::backtrace_rs::backtrace::trace_unsynchronized::hff5adbaff3a8cfb8
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2c60f9b7e6 - std::sys_common::backtrace::_print_fmt::h9d3e0e63f6f89eaf
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2c60f9b7e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2d31e6c8aa8ef934
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2c60fedec0 - core::fmt::rt::Argument::fmt::hd4eaf83b012a42ab
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2c60fedec0 - core::fmt::write::hb507e806b3ae16c4
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f2c60f8f14f - std::io::Write::write_fmt::h203bf95b6a67c7a0
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/io/mod.rs:1810:15
   7:     0x7f2c60f9b5c4 - std::sys_common::backtrace::_print::h2f732cf10966ea1c
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2c60f9b5c4 - std::sys_common::backtrace::print::hef45416e244164df
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2c60f9e357 - std::panicking::default_hook::{{closure}}::h1a73802a0a993acf
  10:     0x7f2c60f9e0b9 - std::panicking::default_hook::h34548737700c4b4d
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:292:9
  11:     0x7f2c5dd4e80c - std[d6f21989bfff4f42]::panicking::update_hook::<alloc[21b544e6cc75226b]::boxed::Box<rustc_driver_impl[bce72efeea91a1de]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f2c60f9eaa6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb0b823449909a650
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2030:9
  13:     0x7f2c60f9eaa6 - std::panicking::rust_panic_with_hook::h60e4310ab2a16e4e
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:785:13
  14:     0x7f2c60f9e7f2 - std::panicking::begin_panic_handler::{{closure}}::h61737518028fa2b2
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:659:13
  15:     0x7f2c60f9bce6 - std::sys_common::backtrace::__rust_end_short_backtrace::h7870f48bedce1dac
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f2c60f9e550 - rust_begin_unwind
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/panicking.rs:647:5
  17:     0x7f2c60fea5c5 - core::panicking::panic_fmt::h01c3f6a1955aca70
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/panicking.rs:72:14
  18:     0x7f2c60fea802 - core::panicking::panic_bounds_check::h25b685aaca1db28e
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/core/src/panicking.rs:208:5
  19:     0x7f2c6033b750 - <rustc_middle[63813a132a817cd4]::ty::generics::Generics>::type_param.cold.0
  20:     0x7f2c5f263655 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_field
  21:     0x7f2c5fadc938 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:     0x7f2c5fadc73f - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:     0x7f2c5f9f1065 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_block_with_expected
  24:     0x7f2c5fadc049 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25:     0x7f2c5fb69770 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_argument_types
  26:     0x7f2c5fa0ff0a - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_call
  27:     0x7f2c5fadbc39 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f2c5f9f1065 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7f2c5fadc049 - <rustc_hir_typeck[995280b49f849d23]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f2c5f655848 - rustc_hir_typeck[995280b49f849d23]::check::check_fn
  31:     0x7f2c5f2d3f02 - rustc_hir_typeck[995280b49f849d23]::typeck
  32:     0x7f2c5f2d3289 - rustc_query_impl[f8b584d7216df600]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f8b584d7216df600]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f2c5f0bfdf9 - rustc_query_system[13649e0efc92577a]::query::plumbing::try_execute_query::<rustc_query_impl[f8b584d7216df600]::DynamicConfig<rustc_query_system[13649e0efc92577a]::query::caches::VecCache<rustc_span[6e44e330265df079]::def_id::LocalDefId, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f8b584d7216df600]::plumbing::QueryCtxt, false>
  34:     0x7f2c5f0bfa90 - rustc_query_impl[f8b584d7216df600]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f2c5f5e99cc - <rustc_middle[63813a132a817cd4]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[f88d56455d931b67]::check_crate::{closure#6}>::{closure#0}
  36:     0x7f2c5f5e82c4 - rustc_hir_analysis[f88d56455d931b67]::check_crate
  37:     0x7f2c5fa94419 - rustc_interface[37b6cebe1bce16]::passes::analysis
  38:     0x7f2c5fa9405f - rustc_query_impl[f8b584d7216df600]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f8b584d7216df600]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7f2c5ffcd040 - rustc_query_system[13649e0efc92577a]::query::plumbing::try_execute_query::<rustc_query_impl[f8b584d7216df600]::DynamicConfig<rustc_query_system[13649e0efc92577a]::query::caches::SingleCache<rustc_middle[63813a132a817cd4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[f8b584d7216df600]::plumbing::QueryCtxt, false>
  40:     0x7f2c5ffcce47 - rustc_query_impl[f8b584d7216df600]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7f2c5fd343ed - rustc_interface[37b6cebe1bce16]::interface::run_compiler::<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}
  42:     0x7f2c5fff3546 - std[d6f21989bfff4f42]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[37b6cebe1bce16]::util::run_in_thread_with_globals<rustc_interface[37b6cebe1bce16]::util::run_in_thread_pool_with_globals<rustc_interface[37b6cebe1bce16]::interface::run_compiler<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>
  43:     0x7f2c5fff3373 - <<std[d6f21989bfff4f42]::thread::Builder>::spawn_unchecked_<rustc_interface[37b6cebe1bce16]::util::run_in_thread_with_globals<rustc_interface[37b6cebe1bce16]::util::run_in_thread_pool_with_globals<rustc_interface[37b6cebe1bce16]::interface::run_compiler<core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>, rustc_driver_impl[bce72efeea91a1de]::run_compiler::{closure#0}>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a757d3bbb7cc29b8]::result::Result<(), rustc_span[6e44e330265df079]::ErrorGuaranteed>>::{closure#1} as core[a757d3bbb7cc29b8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f2c60fa89d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc62465ce3696edbb
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2016:9
  45:     0x7f2c60fa89d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2898b364df1453ed
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/alloc/src/boxed.rs:2016:9
  46:     0x7f2c60fa89d5 - std::sys::unix::thread::Thread::new::thread_start::hefe0ce868779f0f1
                               at /rustc/89110dafe79621fa07d6cd7c8493dd1d0a83cfaf/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7f2c5ae6f9eb - <unknown>
  48:     0x7f2c5aef37cc - <unknown>
  49:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (89110dafe 2024-01-13) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at /tmp/icemaker_global_tempdir.9KzAYMOKvvyy/rustc_testrunner_tmpdir_reporting.iFAbOoiLuUqy/mvce.rs:10:1: 10:17>::static_method2::baz`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors; 1 warning emitted

Some errors have detailed explanations: E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by Bryanskiy**
fixes https://github.com/rust-lang/rust/issues/119921
fixes https://github.com/rust-lang/rust/issues/119919

There is no way to instantiate `Self` param for caller in delegation item if

1. callee is a trait method && callee contains `Self` param
2. delegation item isn't an associative item

In general, we can consider `Self` param as independent type param in these cases:

```rust

trait Trait {
    fn foo(_: Option<&Self>) {...}
}

reuse Trait::foo;
// will be desugared to:
fn foo<T: Trait>(x: Option<&T>) { Trait::foo(x) }
```

But this requires early bound parameters support. For now, I suggest banning such cases to avoid ICE's.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2193,46 +2195,76 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                fn visit_ty(&mut self, ty: Ty<'tcx>) -> Self::Result {
+                    // All early bound generics except `Self` are previously banned.
+                    // It is enough to check only the `ty::Param`.
+                    if matches!(ty.kind(), ty::Param(..)) {
+                        return ControlFlow::Break(());
+                    }
+
+                    ty.super_visit_with(self)
+                }
+            }
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2240]: this is just `ty.has_param()` (which utilizes `TypeFlags` under the hood)

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 2]
```diff
@@ -2193,46 +2195,76 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        // 1. callee is a trait method && callee contains `Self` param
+        // 2. parent item isn't a trait or impl
+        if let DefKind::AssocFn = self.tcx().def_kind(sig_id)
+            && !matches!(parent_def_kind, DefKind::Impl { .. } | DefKind::Trait)
+            && self.tcx().associated_item(sig_id).container
+                == ty::AssocItemContainer::TraitContainer
+        {
+            struct HasSelfParamVisitor;
+
+            impl<'tcx> ty::TypeVisitor<TyCtxt<'tcx>> for HasSelfParamVisitor {
```
Comment (petrochenkov) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2228]: Do you plan to eventually produce a different signature for `reuse Trait::foo` depending on the use of `Self` in signature?

That doesn't seem right.
The number of generic parameters should probably be the same regardless of specific input/output types.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 3]
```diff
@@ -2193,46 +2195,76 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+                    if matches!(ty.kind(), ty::Param(..)) {
+                        return ControlFlow::Break(());
+                    }
+
+                    ty.super_visit_with(self)
+                }
+            }
+
+            if sig.visit_with(&mut HasSelfParamVisitor).is_break() {
+                try_emit("Couldn't instantiate `Self` callee type");
```
Comment (petrochenkov) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2243]: This message is oriented towards compiler writers instead of users.
(Also, diagnostic messages conventionally start with a lowercase letter.)

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2228]: `Self` parameter from `Trait::foo` will turn either into 1 or into 0 parameters, depending on the details of
https://github.com/rust-lang/rfcs/blob/923b8e65639de80a93ef2b9770ba1c976c24cf5d/text/0000-fn-delegation.md#self-mapping

Comment (Bryanskiy) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: > Do you plan to eventually produce a different signature for `reuse Trait::foo` depending on the use of `Self` in signature?
> 
> That doesn't seem right. The number of generic parameters should probably be the same regardless of specific input/output types.

At the moment, I have banned all cases where a free function delegates to a trait method. If we plan to support this case in the future, then I expect for delegation without `qself` to map `Self` to `T: Trait` like an example from description. For callee signature without `Self` new parameter will be unused.
```rust
trait Trait {
    fn bar(x: i32) {...}
}

reuse Trait::foo;
// will be desugared to:
fn bar<T: Trait>(x: i32) { Trait::foo(x) }
```

That is why this case is working on master and this check has been added.
