### PR TITLE
Fix bug in integer range matching

### LINKED ISSUE #57894: Regression in match patterns in beta
Hello, the pattern matching in match arms seems to have different behavior in stable than in beta/nightly.

I tried this code:

```rust
use std::i8;

fn main() {
    let a = Some(-50_i8);
    match a {
        Some(c @ i8::MIN...-101) | Some(c @ 101...i8::MAX) => println!("out of bounds, {}", c),
        _ => println!("OK"),
    }
}
```

I expected to see this happen: In all chains, it should print "OK".

Instead, this happened: It prints "OK" in stable, but it prints "out of bounds, -50" in beta/nightly.

[Example in the playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=0874084dd8b91a733ffaf7c7fa32d5c8)

I understand that this code is not very idiomatic, but still, I think that the behavior should be consistent between Rust versions.

### PR DESCRIPTION
**Pull request by varkor**
Fixes #57894.

### CODE REVIEW

File: src/librustc_mir/build/matches/simplify.rs [hunk 1]
```diff
@@ -106,27 +106,28 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
             }
 
             PatternKind::Range(PatternRange { lo, hi, ty, end }) => {
```
Comment (Centril) [inline src/librustc_mir/build/matches/simplify.rs]: Since this code apparently wasn't obvious to even yourself, a few comments would be nice ;)

File: src/librustc_mir/build/matches/simplify.rs [hunk 2]
```diff
@@ -106,27 +106,28 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
                         let max = !0u128 >> (128 - size.bits());
-                        Some((0, max, size))
+                        (Some((0, max, size)), 0)
                     }
-                    _ => None,
+                    _ => (None, 0),
                 };
                 if let Some((min, max, sz)) = range {
                     if let (Some(lo), Some(hi)) = (lo.val.try_to_bits(sz), hi.val.try_to_bits(sz)) {
+                        let (lo, hi) = (lo ^ bias, hi ^ bias);
```
Comment (oli-obk) [inline src/librustc_mir/build/matches/simplify.rs]: So this basically makes sure that unsigned comparison of signed numbers still works out?

Comment (varkor) [reply src/librustc_mir/build/matches/simplify.rs]: Yeah. I'll add a comment.

File: src/librustc_mir/build/matches/simplify.rs [hunk 3]
```diff
@@ -106,27 +106,34 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
                         let max = !0u128 >> (128 - size.bits());
-                        Some((0, max, size))
+                        (Some((0, max, size)), 0)
                     }
-                    _ => None,
+                    _ => (None, 0),
                 };
                 if let Some((min, max, sz)) = range {
                     if let (Some(lo), Some(hi)) = (lo.val.try_to_bits(sz), hi.val.try_to_bits(sz)) {
+                        // We want to compare ranges numerically, but the order of signed floating-
```
Comment (matthewjasper) [inline src/librustc_mir/build/matches/simplify.rs]: Signed integers

**Comment by oli-obk** [comment]
@bors r-

r=me with the comment nit addressed

**Comment by pnkfelix** [comment]
@varkor your update to the comment continues to refer to floating-point numbers rather than signed integers (which is what I had interpreted the comment nit as referring to).

So now I am inferring that you did in fact **mean** to reference floating-point numbers in your comment.

I haven't attempted to validate the reasoning in the comment/code when applied to floating-point numbers.

But, both your own code here and the referenced code in [pattern/_match.rs](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/hair/pattern/_match.rs#L840), is only going to look at ranges constructed from one of the types {`char`, `iN`, `uN`} ... nothing with floating-point type.

... so ... is there some way that floating point values can arise in these code paths? Even the underlying representation in the MIR interpreter, as far as I can tell, avoids using floating-point values...

**Comment by varkor** [comment]
Sorry, I must have been distracted when editing the comment; it should not refer to floating-point numbers at all. I think I was conflating it with another problem I've been thinking about recently. Floating-point range patterns are not permitted in this location and do not need to be handled. I shall update the comment (and squash all of the edits) once I get back to my computer. Sorry for the confusion.
