### PR TITLE
Do not mix normalized and unnormalized caller bounds when constructing param-env for `receiver_is_dispatchable`

### LINKED ISSUE #138937: A "cannot infer type" compilation error appeared from 1.87.0-nightly (249cb84 2025-03-12)
A "cannot infer type" compilation error appeared in nightly-2025-03-13, 1.87.0-nightly (249cb8431 2025-03-12) and subsequent versions
### Code

I tried this code:

```rust
pub trait TraitA {}
pub trait TraitB<T> {
    fn f_b(a: T) -> Self;
}
pub trait TraitC: TraitB<Self::Value> {
    type Value: TraitA;
}
pub trait TraitD: TraitC<Value = Self::Scalar> {
    type Scalar: TraitA;
}

pub trait TraitE {
    //This fails compiling in 1.87.0-nightly (249cb8431 2025-03-12)
    fn apply<A: TraitA, PF: TraitD<Scalar = A>>(&self);
}

pub struct StructA;
impl StructA {
    //This compiles correctly
    pub fn apply<A: TraitA, PF: TraitD<Scalar = A>>(&self) {}
}

```

I expected to see this happen: compiling successfully

Instead, this happened: 
```
error[E0284]: type annotations needed
  --> src/lib.rs:14:5
   |
14 |     fn apply<A: TraitA, PF: TraitD<Scalar = A>>(&self);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `<PF as TraitC>::Value == _`
```

### Version it worked on

It most recently worked on: nightly-2025-03-12 1.87.0-nightly (665025243 2025-03-11)

### Version with regression

`rustc +nightly-2025-03-13 --version --verbose`:
```
rustc 1.87.0-nightly (249cb8431 2025-03-12)
binary: rustc
commit-hash: 249cb84316401daf040832cdbb8a45e0f5ab6af8
commit-date: 2025-03-12
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0
```

### PR DESCRIPTION
**Pull request by compiler-errors**
See comments in code and in test I added.

r? @BoxyUwU since you reviewed the last PR, or reassign

Fixes #138937

### CODE REVIEW

**Comment by compiler-errors** [comment]
probably :)

File: tests/ui/self/dyn-dispatch-do-not-mix-normalized-and-unnormalized.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+//@ check-pass
+
+// Regression test for <https://github.com/rust-lang/rust/issues/138937>.
+
+// Previously, we'd take the normalized param env's clauses which included
+// `<PF as TraitC>::Value = i32`, which comes from the supertraits of `TraitD`
+// after normalizing `<PF as TraitC>::Value = <PF as TraitD>::Scalar`. Since
+// `normalize_param_env_or_error` ends up re-elaborating `PF: TraitD`, we'd
+// end up with both versions of this predicate (normalized and unnormalized).
+// Since these projections preds are not equal, we'd fail with ambiguity.
```
Comment (BoxyUwU) [inline tests/ui/self/dyn-dispatch-do-not-mix-normalized-and-unnormalized.rs:10]: its *during* `normalize_param_env_or_error` that we error due to there being two candidates?

Comment (compiler-errors) [reply tests/ui/self/dyn-dispatch-do-not-mix-normalized-and-unnormalized.rs:10]: We error during `normalize_param_env_or_error` b/c we have two candidates for normalizing <PF as TraitC>::Value`, which shows up in the supertrait `TraitB<Self::Value>`. The first candidate comes from normalizing the param-env one time, and the second comes from the second time we normalize it.

File: compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs [hunk 2]
```diff
@@ -583,27 +583,29 @@ fn receiver_is_dispatchable<'tcx>(
     // create a modified param env, with `Self: Unsize<U>` and `U: Trait` (and all of
     // its supertraits) added to caller bounds. `U: ?Sized` is already implied here.
     let param_env = {
-        let param_env = tcx.param_env(method.def_id);
+        // N.B. We generally want to emulate the construction of the `unnormalized_param_env`
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs:586]: So this currently misses out on the constness bounds which I guess is fine because associated type normalization doesn't care about constness? And also because `DispatchFromDyn` isnt a `const_trait` so it can only have non-const impls so again we don't really care about constness of stuff in the env.

We also miss out on the RPITIT projection preds? That's probable fine because it's not like we can define opaque types in this analysis anyway. I am assuming that the "assoc type" effectively has the item bounds of the opaque too so it won't result in being unable to prove stuff :woman_shrugging: 

Is that roughly correct? Can u add a small comment noting why we don't need to emulate those parts of param env construction

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/traits/dyn_compatibility.rs:586]: Precisely correct. 

I could add the code to emulate those too but at that point I'd rather abstract this out into code shared by both the paramenv query and this, which is overkill imo (since it's still duplicated but slightly different for compare-impl-item).

I'll add a comment.

**Comment by compiler-errors** [comment]
k i added a comment

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/rust/issues/140019

@rustbot label: +beta-nominated

**Comment by jieyouxu** [comment]
This was [discussed in today's compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-04-24/near/514137889) and beta backport was approved. Thanks!

@rustbot label: +beta-approved
