### PR TITLE
Additional span info for E0053

### LINKED ISSUE #35212: E0053 needs tighter spans
From: src/test/compile-fail/E0053.rs

Some bonus tasks on this one:

* Add the original trait requirement, so that you can see both the error and what the original trait expects
* If possible, tighten the spans

Error E0053 currently is updated to the new error format, but the spans are very large.  Ideally, instead of this:

```
error[E0053]: method `foo` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:19:5
   |
19 |     fn foo(x: i16) { } //~ ERROR E0053
   |     ^^^^^^^^^^^^^^^^^^ expected u16, found i16

error[E0053]: method `bar` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:20:5
   |
20 |     fn bar(&mut self) { } //~ ERROR E0053
   |     ^^^^^^^^^^^^^^^^^^^^^ values differ in mutability
   |
   = note: expected type `fn(&Bar)`
   = note:    found type `fn(&mut Bar)`
```

We could have smaller spans (with updated labels):

```
error[E0053]: method `foo` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:19:5
   |
19 |     fn foo(x: i16) { } //~ ERROR E0053
   |               ^^^ expected u16

error[E0053]: method `bar` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:20:5
   |
20 |     fn bar(&mut self) { } //~ ERROR E0053
   |            ^^^^ values differ in mutability
   |
   = note: expected type `fn(&Bar)`
   = note:    found type `fn(&mut Bar)`
```

It would also be great to show what the other definition was:

```
error[E0053]: method `foo` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:19:5
   |
12 |     fn foo(x: u16);
   |               --- original trait requirement
...
19 |     fn foo(x: i16) { } //~ ERROR E0053
   |               ^^^ expected u16

error[E0053]: method `bar` has an incompatible type for trait
  --> src/test/compile-fail/E0053.rs:20:5
   |
13 |     fn bar(&self);
   |            - original trait requirement
...
20 |     fn bar(&mut self) { } //~ ERROR E0053
   |            ^^^^ values differ in mutability
   |
   = note: expected type `fn(&Bar)`
   = note:    found type `fn(&mut Bar)`
```

### PR DESCRIPTION
**Pull request by KiChjang**
Part of #35233.
Fixes #35212.

r? @jonathandturner

### CODE REVIEW

File: src/librustc/ty/error.rs [hunk 1]
```diff
@@ -144,8 +144,7 @@ impl<'tcx> fmt::Display for TypeError<'tcx> {
                            found bound lifetime parameter {}", br)
             }
             Sorts(values) => ty::tls::with(|tcx| {
-                report_maybe_different(f, values.expected.sort_string(tcx),
-                                       values.found.sort_string(tcx))
+                write!(f, "expected {}", values.expected.sort_string(tcx))
```
Comment (KiChjang) [inline src/librustc/ty/error.rs]: The reason why there are so many test expectation changes is due to this line here. I realize that changing this here means that all affected error messages will have to be shown in the new format, and I haven't really touched the other ones aside from E0053.

File: src/librustc_typeck/check/compare_method.rs [hunk 2]
```diff
@@ -331,16 +332,82 @@ pub fn compare_impl_method<'a, 'tcx>(ccx: &CrateCtxt<'a, 'tcx>,
...
+                        let arg_idx = impl_iter.zip(trait_iter)
+                                               .position(|(impl_arg_ty, trait_arg_ty)| {
+                                                *impl_arg_ty == found && *trait_arg_ty == expected
+                                               }).unwrap();
+                        impl_m_iter.zip(trait_m_iter)
+                                   .nth(arg_idx)
+                                   .map(|(impl_arg, trait_arg)|
+                                        (impl_arg.ty.span, Some(trait_arg.ty.span)))
+                                   .unwrap_or(
+                                    (origin.span(), tcx.map.span_if_local(trait_m.def_id)))
```
Comment (KiChjang) [inline src/librustc_typeck/check/compare_method.rs]: I ended up not using `ccx.ast_ty_to_ty_cache` since it can apparently store types that are exactly the same as either of `expected` or `found` on a completely different AST node. Iterating over the arguments is a safer bet since we have all the contextual information we need.

File: src/librustc/ty/error.rs (hunk 1 above)
Comment (jonathandturner) [inline src/librustc/ty/error.rs]: I know you just did all the work to change this, but this part of the change makes me nervous.  If there are other errors that will also need "expected __, found ___" changes for the label, maybe it makes sense to do all of those at once.

What does this change look like without changing this line?

File: src/test/compile-fail/fn-item-type.rs [hunk 3]
```diff
@@ -24,20 +24,20 @@ fn main() {
     //~^ ERROR mismatched types
     //~|  expected type `fn(isize) -> isize {foo::<u8>}`
     //~|  found type `fn(isize) -> isize {bar::<u8>}`
-    //~|  expected fn item, found a different fn item
+    //~|  expected fn item
```
Comment (jonathandturner) [inline src/test/compile-fail/fn-item-type.rs]: Yeah, changes like this in particular are what I was worried about.  If we remove the `found` part the underline becomes very confusing.

File: src/librustc/ty/error.rs (hunk 1 above)
Comment (jonathandturner) [inline src/librustc/ty/error.rs]: Looking through the unit tests that changed, I think I definitely underestimated the impact changing the label would have.

For the time being it looks like we'll need to keep it as-is, until we can come up with another solution.  If we removed the "expected" part, some of the labels just won't make sense or will become much more difficult to understand.

Comment (KiChjang) [inline src/librustc/ty/error.rs]: That's totally fine (in fact, that's the whole reason why I have a separate commit removing all the "found ___" part). It does make me feel like it makes more sense to change all of them at once. Not sure if this interim state is desirable though, i.e. having the span label state "expected ___, found ____" instead of simply "expected _____".

**Comment by KiChjang** [comment]
Okay, I've removed the test expectation changes and the code is now using the older format of "expected \_\_\_, found \_\_\_".

**Comment by jonathandturner** [comment]
Great!  Thanks for doing that.

@bors r+

**Comment by KiChjang** [comment]
I needed to re-update my UI test. re-r? @jonathandturner

File: src/librustc_typeck/check/compare_method.rs [hunk 4]
```diff
@@ -331,16 +332,82 @@ pub fn compare_impl_method<'a, 'tcx>(ccx: &CrateCtxt<'a, 'tcx>,
...
+                            TraitItem_::MethodTraitItem(ref trait_m_sig, _) =>
+                                trait_m_sig.decl.inputs.iter(),
+                            _ => bug!("{:?} is not a MethodTraitItem", trait_m)
+                        };
+                        let impl_iter = impl_args.iter();
+                        let trait_iter = trait_args.iter();
+                        let arg_idx = impl_iter.zip(trait_iter)
+                                               .position(|(impl_arg_ty, trait_arg_ty)| {
+                                                *impl_arg_ty == found && *trait_arg_ty == expected
+                                               }).unwrap();
```
Comment (TimNN) [inline src/librustc_typeck/check/compare_method.rs]: This `unwrap` is probably the cause of the ICE / regression #35869.
