### PR TITLE
Type inference for inline consts

### LINKED ISSUE #78132: Inline const blocks default integers to i32
Inline const blocks default to the `i32` type on integer literals, see the following:

```Rust
#![feature(inline_const)]

fn main() {
    let _: usize = const { 0 };
}
```

fails compilation with: 
```
error[E0308]: mismatched types
 --> src/main.rs:4:20
  |
4 |     let _: usize = const { 0 };
  |            -----   ^^^^^ expected `usize`, found `i32`
  |            |
  |            expected due to this
  |
help: you can convert an `i32` to `usize` and panic if the converted value wouldn't fit
  |
4 |     let _: usize = const.try_into().unwrap() { 0 };
```

Regular integer literals, and in unsafe blocks just get the type right: `let _: usize = 0` and  `let _: usize = unsafe { 0 };`

Another minor thing is the error message, `const.try_into().unwrap() { 0 };` is an invalid suggestion ^^.

### LINKED ISSUE #78174: ICE: "cannot convert `ReErased` to a region vid" for `let const { "foo" } = "foo"`
### Code

About as minimal of an example as it gets :)

```rust
#![allow(incomplete_features)]
#![feature(inline_const)]
fn main() {
    let const { "foo" } = "foo";
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aad978f0eba5b537939f73acca35ecf4)

### Version

On the playground, so I don't think I can access the rest, but:

`rustc 1.49.0-nightly (b1496c6e6 2020-10-18) running on x86_64-unknown-linux-gnu`

This is a nightly-only feature, so I can't test on stable or beta :)

### Error output

```
error: internal compiler error: compiler/rustc_mir/src/borrow_check/universal_regions.rs:768:36: cannot convert `ReErased` to a region vid

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid::{{closure}}
   9: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid
  10: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::fold_to_region_vids::{{closure}}
  11: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  12: rustc_mir::borrow_check::universal_regions::UniversalRegions::new
  13: rustc_mir::borrow_check::nll::replace_regions_in_mir
  14: rustc_mir::borrow_check::do_mir_borrowck
  15: rustc_infer::infer::InferCtxtBuilder::enter
  16: rustc_mir::borrow_check::mir_borrowck
  17: core::ops::function::FnOnce::call_once
  18: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  19: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  20: rustc_data_structures::stack::ensure_sufficient_stack
  21: rustc_query_system::query::plumbing::get_query_impl
  22: rustc_query_system::query::plumbing::ensure_query_impl
  23: rustc_mir::transform::mir_drops_elaborated_and_const_checked
  24: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_drops_elaborated_and_const_checked>::compute
  25: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  26: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_mir::transform::optimized_mir
  29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  30: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  31: rustc_data_structures::stack::ensure_sufficient_stack
  32: rustc_query_system::query::plumbing::get_query_impl
  33: rustc_mir::interpret::eval_context::InterpCx<M>::load_mir
  34: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_allocation_raw>::compute
  36: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  37: rustc_data_structures::stack::ensure_sufficient_stack
  38: rustc_query_system::query::plumbing::get_query_impl
  39: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  40: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_const_value_raw>::compute
  41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  42: rustc_data_structures::stack::ensure_sufficient_stack
  43: rustc_query_system::query::plumbing::get_query_impl
  44: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  45: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  46: rustc_infer::infer::InferCtxt::const_eval_resolve
  47: rustc_trait_selection::traits::const_evaluatable::is_const_evaluatable
  48: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  49: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  50: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  51: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::select_obligations_where_possible
  52: rustc_infer::infer::InferCtxtBuilder::enter
  53: rustc_typeck::check::typeck
  54: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  55: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  56: rustc_data_structures::stack::ensure_sufficient_stack
  57: rustc_query_system::query::plumbing::get_query_impl
  58: rustc_query_system::query::plumbing::ensure_query_impl
  59: rustc_typeck::check::typeck_item_bodies
  60: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  61: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  62: rustc_data_structures::stack::ensure_sufficient_stack
  63: rustc_query_system::query::plumbing::get_query_impl
  64: rustc_typeck::check_crate
  65: rustc_interface::passes::analysis
  66: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  67: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  68: rustc_data_structures::stack::ensure_sufficient_stack
  69: rustc_query_system::query::plumbing::get_query_impl
  70: rustc_interface::passes::QueryContext::enter
  71: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  72: rustc_span::with_source_map
  73: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (b1496c6e6 2020-10-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `main::{constant#0}`
#1 [mir_drops_elaborated_and_const_checked] elaborating drops for `main::{constant#0}`
#2 [optimized_mir] optimizing MIR for `main::{constant#0}`
#3 [eval_to_allocation_raw] const-evaluating + checking `main::{constant#0}`
#4 [eval_to_const_value_raw] simplifying constant for the type system `main::{constant#0}`
#5 [typeck] type-checking `main`
#6 [typeck_item_bodies] type-checking all item bodies
#7 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `playground`
```

</p>
</details>

### LINKED ISSUE #81857: ICE:  cannot convert `ReErased` to a region vid
It seems like a duplicate of [#78174](https://github.com/rust-lang/rust/issues/78174). But it is, on the other hand, an invalid statements instead of a nightly-only feature (inline_const). So I open this issue. 

I will try to understand whether it is indeed a duplicate. But it would be very appreciated if someone can figure it out, so that we do not bother so much. Thanks!

### Code

```Rust
#[c=""]

fn e()->i {{""]const{""
```

md5: fef99e2b36eeaaa4fe32447f7ff03c9c 

### Meta

It is on nightly, beta, and stable versions.

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (a73c2e555 2021-02-06)
binary: rustc
commit-hash: a73c2e555c26ef0c8b98c91c97a7d24b7017267f
commit-date: 2021-02-06
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1

rustc 1.50.0-beta.8 (1cd030396 2021-01-20)
binary: rustc
commit-hash: 1cd0303963629f317a08e7e52162ccca7232ae7f
commit-date: 2021-01-20
host: x86_64-unknown-linux-gnu
release: 1.50.0-beta.8

rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

### Error output

The output is from nightly.

```
➜  playground rustc poc.rs
error: this file contains an unclosed delimiter
 --> poc.rs:3:25
  |
3 | fn e()->i {{""]const{""
  |           -         -   ^
  |           |         |
  |           |         unclosed delimiter
  |           unclosed delimiter

error: mismatched closing delimiter: `]`
 --> poc.rs:3:15
  |
3 | fn e()->i {{""]const{""
  |            -  ^ mismatched closing delimiter
  |            |
  |            unclosed delimiter

error: cannot find attribute `c` in this scope
 --> poc.rs:1:3
  |
1 | #[c=""]
  |   ^

error[E0412]: cannot find type `i` in this scope
 --> poc.rs:3:9
  |
3 | fn e()->i {{""]const{""
  |         ^ help: a builtin type with a similar name exists: `i8`

error[E0658]: inline-const is experimental
 --> poc.rs:3:16
  |
3 | fn e()->i {{""]const{""
  |                ^^^^^
  |
  = note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information
  = help: add `#![feature(inline_const)]` to the crate attributes to enable

warning: unnecessary braces around block return value
 --> poc.rs:3:12
  |
3 | fn e()->i {{""]const{""
  |            ^^^^ help: remove these braces
  |
  = note: `#[warn(unused_braces)]` on by default

error[E0308]: mismatched types
 --> poc.rs:3:13
  |
3 | fn e()->i {{""]const{""
  |             ^^ expected `()`, found `&str`

error: internal compiler error: compiler/rustc_mir/src/borrow_check/universal_regions.rs:768:36: cannot convert `ReErased` to a region vid

thread 'rustc' panicked at 'Box<Any>', /rustc/a73c2e555c26ef0c8b98c91c97a7d24b7017267f/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (a73c2e555 2021-02-06) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `e::{constant#0}`
#1 [mir_drops_elaborated_and_const_checked] elaborating drops for `e::{constant#0}`
end of query stack
error: aborting due to 7 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0412, E0658.
For more information about an error, try `rustc --explain E0308`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', /rustc/a73c2e555c26ef0c8b98c91c97a7d24b7017267f/library/std/src/panic.rs:59:5
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid
   8: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::fold_to_region_vids::{{closure}}
   9: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  10: rustc_mir::borrow_check::universal_regions::UniversalRegions::new
  11: rustc_mir::borrow_check::nll::replace_regions_in_mir
  12: rustc_mir::borrow_check::do_mir_borrowck
  13: rustc_infer::infer::InferCtxtBuilder::enter
  14: rustc_mir::borrow_check::mir_borrowck
  15: core::ops::function::FnOnce::call_once
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: rustc_query_system::query::plumbing::ensure_query_impl
  22: rustc_mir::transform::mir_drops_elaborated_and_const_checked
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_drops_elaborated_and_const_checked>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::force_query_with_job
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_mir::transform::inner_mir_for_ctfe
  29: rustc_mir::transform::mir_for_ctfe
  30: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_for_ctfe>::compute
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::force_query_with_job
  34: rustc_query_system::query::plumbing::get_query_impl
  35: <rustc_mir::const_eval::machine::CompileTimeInterpreter as rustc_mir::interpret::machine::Machine>::load_mir
  36: rustc_mir::interpret::eval_context::InterpCx<M>::load_mir
  37: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
  38: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_allocation_raw>::compute
  39: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  40: rustc_data_structures::stack::ensure_sufficient_stack
  41: rustc_query_system::query::plumbing::force_query_with_job
  42: rustc_query_system::query::plumbing::get_query_impl
  43: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  44: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_const_value_raw>::compute
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  46: rustc_data_structures::stack::ensure_sufficient_stack
  47: rustc_query_system::query::plumbing::force_query_with_job
  48: rustc_query_system::query::plumbing::get_query_impl
  49: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  50: rustc_infer::infer::InferCtxt::const_eval_resolve
  51: rustc_trait_selection::traits::const_evaluatable::is_const_evaluatable
  52: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  53: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  54: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::select_obligations_where_possible
  55: rustc_infer::infer::InferCtxtBuilder::enter
  56: rustc_typeck::check::typeck
  57: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  58: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  59: rustc_data_structures::stack::ensure_sufficient_stack
  60: rustc_query_system::query::plumbing::force_query_with_job
  61: rustc_query_system::query::plumbing::get_query_impl
  62: rustc_query_system::query::plumbing::ensure_query_impl
  63: rustc_typeck::check::typeck_item_bodies
  64: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  65: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  66: rustc_data_structures::stack::ensure_sufficient_stack
  67: rustc_query_system::query::plumbing::force_query_with_job
  68: rustc_query_system::query::plumbing::get_query_impl
  69: rustc_typeck::check_crate
  70: rustc_interface::passes::analysis
  71: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  72: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  73: rustc_data_structures::stack::ensure_sufficient_stack
  74: rustc_query_system::query::plumbing::force_query_with_job
  75: rustc_query_system::query::plumbing::get_query_impl
  76: rustc_interface::passes::QueryContext::enter
  77: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  78: rustc_span::with_source_map
  79: rustc_interface::interface::create_compiler_and_run
  80: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

### LINKED ISSUE #89964: `inline_const` blocks type inference
I tried this code: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b628c24337168091d1c20e62ff6e31e8>
```rust
#![feature(inline_const)]
use std::collections::HashMap;
fn main() {
    let mut h = <HashMap<usize, Vec<i32>>>::new();
    h.entry(123).or_insert(const { Vec::new() });
    dbg!(h);
}
```

I expected to see this happen: It compiles, the same as the following (without the `const{}`) does <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2da5b1d9926024223ba6dff77a647f17>
```rust
#![feature(inline_const)]
use std::collections::HashMap;
fn main() {
    let mut h = <HashMap<usize, Vec<i32>>>::new();
    h.entry(123).or_insert(Vec::new());
    dbg!(h);
}
```

Instead, this happened: type inference fails
```text
error[E0282]: type annotations needed
 --> src/main.rs:5:36
  |
5 |     h.entry(123).or_insert(const { Vec::new() });
  |                                    ^^^^^^^^ cannot infer type for type parameter `T`
```

<small>(Spotted after looking at https://internals.rust-lang.org/t/should-clippy-warn-about-function-calls-outside-closures-if-those-are-const-answered/15452/4?u=scottmcm)</small>

### PR DESCRIPTION
**Pull request by nbdd0121**
Fixes #78132
Fixes #78174
Fixes #81857
Fixes #89964

Perform type checking/inference of inline consts in the same context as the outer def, similar to what is currently done to closure.

Doing so would require `closure_base_def_id` of the inline const to return the outer def, and since `closure_base_def_id` can be called on non-local crate (and thus have no HIR available), a new `DefKind` is created for inline consts.

The type of the generated anon const can capture lifetime of outer def, so we couldn't just use the typeck result as the type of the inline const's def. Closure has a similar issue, and it uses extra type params `CK, CS, U` to capture closure kind, input/output signature and upvars. I use a similar approach for inline consts, letting it have an extra type param `R`, and then `typeof(InlineConst<[paremt generics], R>)` would just be `R`. In borrowck region requirements are also propagated to the outer MIR body just like it's currently done for closure.

With this PR, inline consts in expression position are quitely usable now; however the usage in pattern position is still incomplete -- since those does not remain in the MIR borrowck couldn't verify the lifetime there. I have left an ignored test as a FIXME.

Some disucssions can be found on [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/inline.20consts.20typeck).
cc @spastorino @lcnr
r? @nikomatsakis

@rustbot label A-inference F-inline_const T-compiler

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -1938,7 +1938,8 @@ fn resolution_failure(
                             | Use
                             | LifetimeParam
                             | Ctor(_, _)
-                            | AnonConst => {
+                            | AnonConst
+                            | InlineConst => {
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1942]: These should probably just be `unreachable!` ... but this change is fine, it should never be hit in practice.

File: compiler/rustc_middle/src/ty/util.rs [hunk 2]
```diff
@@ -440,16 +448,19 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    /// has its own type-checking context or "inference enviornment".
+    ///
+    /// For example, a closure has its own `DefId`, but it is type-checked
+    /// with the containing item. Similarly, an inline const block has its
+    /// own `DefId` but it is type-checked together with the containing item.
+    ///
+    /// Therefore, when we fetch the
     /// `typeck` the closure, for example, we really wind up
     /// fetching the `typeck` the enclosing fn item.
     pub fn closure_base_def_id(self, def_id: DefId) -> DefId {
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/util.rs:461]: maybe something like `typeck_root_def_id` or something, this name is a bit misleading rn

File: compiler/rustc_typeck/src/check/regionck.rs [hunk 3]
```diff
@@ -299,6 +299,29 @@ impl<'a, 'tcx> RegionCtxt<'a, 'tcx> {
         self.constrain_opaque_types(self.outlives_environment.free_region_map());
     }
 
+    fn visit_inline_const(&mut self, id: hir::HirId, body: &'tcx hir::Body<'tcx>) {
+        debug!("visit_inline_const(id={:?})", id);
+
+        // Save state of current function. We will restore afterwards.
+        let old_body_id = self.body_id;
+        let old_body_owner = self.body_owner;
+        let env_snapshot = self.outlives_environment.push_snapshot_pre_closure();
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/regionck.rs:308]: same here, `push_snapshot_pre_closure` is somewhat badly named now

**Review by lcnr — COMMENTED** [review]
skimmed over this and it looks really nice, good job :+1: :heart:

File: compiler/rustc_middle/src/ty/util.rs (hunk 2 above)
Comment (nbdd0121) [reply compiler/rustc_middle/src/ty/util.rs:461]: Well, I have considered to rename it, but I kinda persuaded myself that inline const is sort of "const closure" :)

**Review by spastorino — COMMENTED** [review]
This seems great to me. Anyway, leaving this up to @nikomatsakis.

File: compiler/rustc_middle/src/ty/consts.rs [hunk 4]
```diff
@@ -95,16 +115,53 @@ impl<'tcx> Const<'tcx> {
...
+        let ty = tcx.typeck(def_id).node_type(hir_id);
+
+        let ret = match Self::try_eval_body_expr(tcx, ty, expr) {
+            Some(v) => v,
+            None => {
+                let outer_def_id = tcx.closure_base_def_id(def_id.to_def_id());
+                let parent_substs =
+                    tcx.erase_regions(InternalSubsts::identity_for_item(tcx, outer_def_id));
+                let substs =
+                    InlineConstSubsts::new(tcx, InlineConstSubstsParts { parent_substs, ty })
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/ty/consts.rs:151]: seems weird to erase regions above, given that `ty` is not erased here -- it'd be better to erase everything or nothing.

File: compiler/rustc_middle/src/ty/consts.rs [hunk 5]
```diff
@@ -54,6 +56,24 @@ impl<'tcx> Const<'tcx> {
...
+                    def: def.to_global(),
+                    substs_: None,
+                    promoted: None,
+                }),
+                ty,
+            }),
+        }
+    }
+
+    fn try_eval_body_expr(
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/ty/consts.rs:72]: Rename to `literal_or_parameter` or something like that.

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 6]
```diff
@@ -569,7 +569,8 @@ impl<'tcx> RegionInferenceContext<'tcx> {
         // to store those. Otherwise, we'll pass in `None` to the
         // functions below, which will trigger them to report errors
         // eagerly.
-        let mut outlives_requirements = infcx.tcx.is_closure(mir_def_id).then(Vec::new);
+        let mut outlives_requirements =
+            infcx.tcx.is_closure_or_inline_const(mir_def_id).then(Vec::new);
```
Comment (nikomatsakis) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:573]: It'd be good to find a better name for this---

* `is_typeck_child` ?

File: compiler/rustc_borrowck/src/universal_regions.rs [hunk 7]
```diff
@@ -540,11 +551,21 @@ impl<'cx, 'tcx> UniversalRegionsBuilder<'cx, 'tcx> {
             }
 
             BodyOwnerKind::Const | BodyOwnerKind::Static(..) => {
-                assert_eq!(self.mir_def.did.to_def_id(), closure_base_def_id);
                 let identity_substs = InternalSubsts::identity_for_item(tcx, closure_base_def_id);
-                let substs =
-                    self.infcx.replace_free_regions_with_nll_infer_vars(FR, identity_substs);
-                DefiningTy::Const(self.mir_def.did.to_def_id(), substs)
+                if self.mir_def.did.to_def_id() == closure_base_def_id {
```
Comment (nikomatsakis) [inline compiler/rustc_borrowck/src/universal_regions.rs:555]: rename `closure_base_def_id` (here and elsewhere) to `typeck_root_def_id`

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 8]
```diff
@@ -1346,7 +1346,12 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                     Some(RETURN_PLACE) => {
                         if let BorrowCheckContext {
                             universal_regions:
-                                UniversalRegions { defining_ty: DefiningTy::Const(def_id, _), .. },
+                                UniversalRegions {
+                                    defining_ty:
+                                        DefiningTy::Const(def_id, _)
```
Comment (nikomatsakis) [inline compiler/rustc_borrowck/src/type_check/mod.rs:1352]: can we extract this into a method, so that we write

`defining_ty.is_any_const()`

?

**Review by nikomatsakis — COMMENTED** [review]
r=me modulo nits

File: compiler/rustc_borrowck/src/type_check/mod.rs (hunk 8 above)
Comment (nbdd0121) [reply compiler/rustc_borrowck/src/type_check/mod.rs:1352]: There is `is_const` that does this, but this one needs to match def_id. I'll split it into a `is_const` call followed by a `def_id` call.

File: compiler/rustc_middle/src/ty/consts.rs (hunk 4 above)
Comment (nbdd0121) [reply compiler/rustc_middle/src/ty/consts.rs:151]: ty is from `typeck().node_type()` and is already erased.

File: compiler/rustc_middle/src/ty/util.rs (hunk 2 above)
Comment (nbdd0121) [reply compiler/rustc_middle/src/ty/util.rs]: Renamed to `typeck_root_def_id`.

File: compiler/rustc_typeck/src/check/regionck.rs (hunk 3 above)
Comment (nbdd0121) [reply compiler/rustc_typeck/src/check/regionck.rs]: Renamed to `push_snapshot_pre_typeck_child`. Feel free to suggest a better name :)
