### PR TITLE
Fix v0 symbol mangling bug

### LINKED ISSUE #83611: v0 mangled symbol doesn't match specification nor can it be demangled with rustfilt or c++filt
For program below, mangled symbol doesn't match specification nor can it be demangled with rustfilt or c++filt (with rust v0 support):

```rust
pub fn f<T>() {}

pub fn g() {
    f::<&dyn FnMut(&u8)>();
}
```

```shell
$  rustc --crate-type=lib -Zsymbol-mangling-version=v0 a.rs && nm ./liba.rlib | c++filt 
a.a.3a1fbbbh-cgu.0.rcgu.o:
0000000000000000 T _RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hEEG_p6OutputuEL_EB2_
0000000000000000 T a[cdfa367c26312547]::g
```
<details>
<summary>Partial derivation</summary>

```
"" <symbol-name>
"_R" [<decimal-number>] <path> [<instantiating-crate>]
"_R" <path> [<instantiating-crate>]
"_RI" <path> {<generic-arg>} "E" [<instantiating-crate>]
"_RIN" <namespace> <path> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINv" <path> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvC" <identifier> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvC" [<disambiguator>] <undisambiguated-identifier> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCs" <base-62-number> <undisambiguated-identifier> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_" <undisambiguated-identifier> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_" <decimal-number> ["_"] <bytes> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1" ["_"] <bytes> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1" <bytes> <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a" <identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a" [<disambiguator>] <undisambiguated-identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a" <undisambiguated-identifier> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a" <decimal-number> ["_"] <bytes> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1" ["_"] <bytes> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1" <bytes> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1f" {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1f" <type> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fR" [<lifetime>] <type> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fR" <type> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRD" <dyn-bounds> <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRD" <binder> {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG" <base-62-number> {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_" {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_" <path> {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_I" <path> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_IN" <namespace> <path> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INt" <path> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtN" <namespace> <path> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNt" <path> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtN" <namespace> <path> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNt" <path> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtC" <identifier> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtC" [<disambiguator>] <undisambiguated-identifier> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs" <base-62-number> <undisambiguated-identifier> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_" <undisambiguated-identifier> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_" <decimal-number> ["_"] <bytes> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4" ["_"] <bytes> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4" <bytes> <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core" <identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core" [<disambiguator>] <undisambiguated-identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core" <undisambiguated-identifier> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core" <decimal-number> ["_"] <bytes> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3" ["_"] <bytes> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3" <bytes> <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops" <identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops" [<disambiguator>] <undisambiguated-identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops" <undisambiguated-identifier> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops" <decimal-number> ["_"] <bytes> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8" ["_"] <bytes> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8" <bytes> <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function" <identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function" [<disambiguator>] <undisambiguated-identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function" <undisambiguated-identifier> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function" <decimal-number> ["_"] <bytes> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5" ["_"] <bytes> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5" <bytes> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMut" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMut" <type> {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutT" {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTR" [<lifetime>] <type> {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTR" <base-62-number> <type> {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_" <type> {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_" <basic-type> {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_h" {<type>} "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_h" "E" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hE" {<generic-arg>} "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hE" "E" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hEE" {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hEE" {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hEE" <path> {<dyn-trait-assoc-binding>} {<dyn-trait>} "E" <lifetime> {<generic-arg>} "E" [<instantiating-crate>]
"_RINvCshGpAVYOtgW1_1a1fRDG_INtNtNtCs4RZURTQcbNt_4core3ops8function5FnMutTRL0_hEEG_p6OutputuEL_EB2_" ?
```

</details>

### PR DESCRIPTION
**Pull request by camelid**
Fixes #83611.

r? @jackh726

### CODE REVIEW

**Comment by camelid** [comment]
It seems @eddyb was suggesting a slightly different approach: https://github.com/rust-lang/rust/issues/83611#issuecomment-811580990

**Comment by camelid** [comment]
By the way, why do so many `SymbolMangler` functions return `Result<T, !>` instead of just `T`?

**Comment by camelid** [comment]
How do I add a test for this? I wasn't able to find any existing name mangling tests.

**Comment by tmiasko** [comment]
`--emit llvm-ir` output contains both mangled function name and demangled one (obtained from mangled one), so a codegen test should do just fine.

File: compiler/rustc_symbol_mangling/src/v0.rs [hunk 1]
```diff
@@ -486,26 +486,26 @@ impl Printer<'tcx> for SymbolMangler<'tcx> {
         predicates: &'tcx ty::List<ty::Binder<'tcx, ty::ExistentialPredicate<'tcx>>>,
     ) -> Result<Self::DynExistential, Self::Error> {
         for predicate in predicates {
-            self = self.in_binder(&predicate, |mut cx, predicate| {
-                match predicate {
-                    ty::ExistentialPredicate::Trait(trait_ref) => {
+            match predicate.as_ref().skip_binder() {
```
Comment (jackh726) [inline compiler/rustc_symbol_mangling/src/v0.rs:489]: Can you add a comment about why we jump though these hoops?

**Review by jackh726 — CHANGES_REQUESTED** [review]
This looks exactly like what I was expecting. Just needs a test (and comment).

File: compiler/rustc_symbol_mangling/src/v0.rs [hunk 2]
```diff
@@ -486,26 +486,26 @@ impl Printer<'tcx> for SymbolMangler<'tcx> {
...
-                    }
-                    ty::ExistentialPredicate::AutoTrait(def_id) => {
-                        cx = cx.print_def_path(*def_id, &[])?;
-                    }
+                        Ok(cx)
+                    })?;
                 }
-                Ok(cx)
-            })?;
+                ty::ExistentialPredicate::Projection(projection) => {
```
Comment (jackh726) [inline compiler/rustc_symbol_mangling/src/v0.rs:499]: Also, based on @eddyb's [comment](https://github.com/rust-lang/rust/issues/83611#issuecomment-811580990), we should just do a simple validation here.

When we encounter an `ExistentialPredicate::Trait`, we should store that in a local variable `last_trait_ref: Binder<'tcx, TraitRef>` then when we see an `ExistentialPredicate::Projection`, we want to check that 1) the binders match and 2) the projection's trait is the same as the last trait

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 1 above)
Comment (camelid) [reply compiler/rustc_symbol_mangling/src/v0.rs:489]: How's this? da404b52d91b5644f2a6490ee0f22021e985bb22

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 2 above)
Comment (camelid) [reply compiler/rustc_symbol_mangling/src/v0.rs:503]: I added some assertions, are they what you expected? 65c04123f81

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 1 above)
Comment (jackh726) [reply compiler/rustc_symbol_mangling/src/v0.rs:491]: I think I'd prefer a little bit better explanation. Something along the lines of "Symbol mangling does not output binder information for projection predicates. Instead, it assumes that the binders are the same as on the trait ref. See issue #83611."

**Comment by camelid** [comment]
The assertions panic on the test case :/

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `std::ops::FnMut<(&u8,)>`,
 right: `std::ops::FnOnce<(&u8,)>`', compiler/rustc_symbol_mangling/src/v0.rs:507:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-dev running on x86_64-apple-darwin

note: compiler flags: -Z symbol-mangling-version=v0

query stack during panic:
#0 [symbol_name] computing the symbol for `f::<&dyn for<'r> std::ops::FnMut(&'r u8)>`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

I think the issue is that the projection for the `FnMut` arguments is actually projecting out of `FnOnce`, since `FnOnce` is a supertrait of `FnMut`. What should I do?

**Comment by jackh726** [comment]
So, you should be able to get the trait that defines the associated type by
```
traits::supertraits(tcx, trait_ref).filter(|r| {
  tcx
    .associated_items(r.def_id())
    .find_by_name_and_kind(tcx, assoc_name, ty::AssocKind::Type, r.def_id())
    .is_some()
}).next()
```

**Comment by camelid** [comment]
> So, you should be able to get the trait that defines the associated type by
> 
> ```
> traits::supertraits(tcx, trait_ref).filter(|r| {
>   tcx
>     .associated_items(r.def_id())
>     .find_by_name_and_kind(tcx, assoc_name, ty::AssocKind::Type, r.def_id())
>     .is_some()
> }).next()
> ```

It looks like in order to do that I would need to add a dependency on `rustc_infer`. Is that okay to do?

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 1 above)
Comment (camelid) [reply compiler/rustc_symbol_mangling/src/v0.rs:491]: Sure, that seems good. My comment doesn't have much information because I'm new to trait solving/binders/etc. :)

**Comment by eddyb** [comment]
> It seems @eddyb was suggesting a slightly different approach: [#83611 (comment)](https://github.com/rust-lang/rust/issues/83611#issuecomment-811580990)

Please add my example as a test - I don't see how `in_binder` can correctly work without being around everything it applies to.

r? @nikomatsakis

**Comment by camelid** [comment]
> Please add my example as a test - I don't see how `in_binder` can correctly work without being around everything it applies to.

Sure, I'm happy to add your test case, but I have never written a codegen test before and am new to the symbol mangling code, so I would appreciate extra help :)

**Comment by tmiasko** [comment]
Codegen tests are located in `src/test/codegen`. They use LLVM FileCheck https://www.llvm.org/docs/CommandGuide/FileCheck.html to verify output. In this case I would check that LLVM IR contains correctly demangled names in the comments:

```rust
// compile-flags: -Zsymbol-mangling-version=v0 -Cno-prepopulate-passes 

pub fn test<T>() {}

fn main() {
    // CHECK: ; call a::test::<&dyn for<'a> core::ops::function::FnMut<(&'a u8,), Output = ()>>
    test::<&dyn FnMut(&u8)>();
    // CHECK: ; call a::test::<for<'a> fn(&'a dyn for<'b> core::ops::function::FnOnce<(&'b u8,), Output = &'b u8> + 'a) -> &'a u8>
    test::<for<'a> fn(&'a dyn for<'b> FnOnce(&'b u8) -> &'b u8) -> &'a u8>();
}
```

You can cross verify output with a toolchain before refactoring, e.g., `d23e08448332425a84ae23124bea4dbd685536ce`.

**Comment by camelid** [comment]
> So, you should be able to get the trait that defines the associated type by
> 
> ```
> traits::supertraits(tcx, trait_ref).filter(|r| {
>   tcx
>     .associated_items(r.def_id())
>     .find_by_name_and_kind(tcx, assoc_name, ty::AssocKind::Type, r.def_id())
>     .is_some()
> }).next()
> ```

That's giving errors:

```
error[E0308]: mismatched types
   --> compiler/rustc_symbol_mangling/src/v0.rs:511:55
    |
511 |                         traits::supertraits(self.tcx, projection.trait_ref(self.tcx)).find(|r| {
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Binder`, found struct `ExistentialTraitRef`
    |
    = note: expected struct `Binder<'_, rustc_middle::ty::TraitRef<'_>>`
               found struct `ExistentialTraitRef<'_>`

error[E0308]: mismatched types
   --> /Users/user/rust4/library/core/src/macros/mod.rs:39:35
    |
35  | / macro_rules! assert_eq {
36  | |     ($left:expr, $right:expr $(,)?) => ({
37  | |         match (&$left, &$right) {
38  | |             (left_val, right_val) => {
39  | |                 if !(*left_val == *right_val) {
    | |                                   ^^^^^^^^^^ expected struct `ExistentialTraitRef`, found enum `Option`
...   |
61  | |     });
62  | | }
    | |_- in this expansion of `assert_eq!`
    | 
   ::: compiler/rustc_symbol_mangling/src/v0.rs:522:21
    |
522 |                       assert_eq!(last_trait_ref.skip_binder(), assoc_item_parent_trait);
    |                       ------------------------------------------------------------------ in this macro invocation
    |
    = note: expected struct `ExistentialTraitRef<'_>`
                 found enum `Option<Binder<'_, rustc_middle::ty::TraitRef<'_>>>`

error: aborting due to 2 previous errors
```

**Comment by jackh726** [comment]
You'll have to convert the `ExistentialTraitRef` to a normal one via `with_self_ty`.

**Comment by eddyb** [comment]
@camelid @tmiasko We don't use codegen tests for testing symbol names.
Check out `src/test/ui/symbol-names` instead, e.g: https://github.com/rust-lang/rust/blob/5b0ab79116ba3231f447bc7a67c16ce93ecca0a3/src/test/ui/symbol-names/impl1.rs#L61-L73

These tests include demangling output, which is important to confirm correct roundtrip.

**Comment by michaelwoerister** [comment]
What's the state of this PR? Is a test case the only thing that remains to do?

**Comment by jackh726** [comment]
I think tests and a review from @nikomatsakis

**Comment by nikomatsakis** [comment]
@jackh726 I don't really understand what I'm meant to review, I think. =) Maybe we can touch on this tomorrow morning?

**Comment by jackh726** [comment]
@nikomatsakis yeah we can do that

**Comment by camelid** [comment]
Hmm, I can't quite get the code working. Here's my current version:

```rust
                ty::ExistentialPredicate::Projection(projection) => {
                    let assoc_item = self.tcx.associated_item(projection.item_def_id);

                    let last_trait_ref = last_trait_ref
                        .expect("trait predicate must come before projection predicate");
                    assert_eq!(last_trait_ref.bound_vars(), predicate.bound_vars());
                    // Use a type that can't appear in defaults of type parameters.
                    let dummy_self = self.tcx.mk_ty_infer(ty::FreshTy(0));
                    let assoc_item_parent_trait =
                        traits::supertraits(self.tcx, projection.trait_ref(self.tcx).with_self_ty(self.tcx, dummy_self)).find(|r| {
                            self.tcx
                                .associated_items(r.def_id())
                                .find_by_name_and_kind(
                                    self.tcx,
                                    assoc_item.ident,
                                    assoc_item.kind,
                                    r.def_id(),
                                )
                                .is_some()
                        }).unwrap();
                    assert_eq!(last_trait_ref.skip_binder(), ty::ExistentialTraitRef::erase_self_ty(self.tcx, assoc_item_parent_trait.skip_binder()));

                    let name = assoc_item.ident;
                    self.push("p");
                    self.push_ident(&name.as_str());
                    self = projection.ty.print(self)?;
                }
```

This code fails to compile:

```
error[E0308]: mismatched types
   --> compiler/rustc_symbol_mangling/src/v0.rs:513:55
    |
513 |                         traits::supertraits(self.tcx, projection.trait_ref(self.tcx).with_self_ty(self.tcx, dummy_self)).find(|r| {
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Binder`, found struct `rustc_middle::ty::TraitRef`
    |
    = note: expected struct `Binder<'_, rustc_middle::ty::TraitRef<'_>, >`
               found struct `rustc_middle::ty::TraitRef<'_>`
```

Then I tried using `Binder::dummy`, but that causes the `!has_escaping_bound_vars` assertions to fail. So then I tried using `Binder::bind`, but that fails with

```
error: internal compiler error: compiler/rustc_middle/src/ty/fold.rs:824:17: Trying to collect bound vars with a bound region: DebruijnIndex(0) BoundRegion { var: 0, kind: BrAnon(0) }

thread 'rustc' panicked at 'Box<Any>', /Users/user/rust4/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-dev running on x86_64-apple-darwin

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z emit-future-incompat-report -Z unstable-options -Z symbol-mangling-version=v0 -C prefer-dynamic -C rpath -C debuginfo=0

query stack during panic:
#0 [symbol_name] computing the symbol for `test::<&dyn for<'r> std::ops::FnMut(&'r u8)>`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error
```

What should I do?

**Comment by jackh726** [comment]
Should be `Binder::bind_with_vars(trait_ref, last_trait_ref.bound_vars())`

File: compiler/rustc_symbol_mangling/src/v0.rs [hunk 3]
```diff
@@ -485,27 +485,36 @@ impl Printer<'tcx> for SymbolMangler<'tcx> {
...
+                    let last_trait_ref = last_trait_ref
+                        .expect("trait predicate must come before projection predicate");
+                    assert_eq!(last_trait_ref.bound_vars(), predicate.bound_vars());
+                    assert_eq!(last_trait_ref.skip_binder(), projection.trait_ref(self.tcx));
+
+                    let name = self.tcx.associated_item(projection.item_def_id).ident;
+                    self.push("p");
+                    self.push_ident(&name.as_str());
+                    self = projection.ty.print(self)?;
```
Comment (jackh726) [inline compiler/rustc_symbol_mangling/src/v0.rs:512]: So, I think one of @eddyb's concerns here is that this should maybe be *inside* the `in_binder` call. But I'm not sure that's necessary because that only writes `G<num>` and doesn't add anything "after".

However, a perhaps straightforward way to write this is not `for predicate in predicates`, but instead do something like
```
let predicate_iter = predicates.iter().peekable();
while let Some(predicate) = predicate_iter.next() {
  match predicate.as_ref().skip_binder() {
    ty::ExistentialPredicate::Trait(trait_ref) => {
      self = self.in_binder(&predicate, |mut cx, _predicate| {
        <print trait ref>
        while let Some(projection) = predicate_iter.next_if(|p| matches!(p, ty::ExistentialPredicate::Projection(_))) {
          <match to projection predicate and print>
        }
      }
    }
    <match projection, this is bug>
    <match auto trait>
  }
}
```

File: compiler/rustc_symbol_mangling/src/v0.rs [hunk 4]
```diff
@@ -485,27 +485,36 @@ impl Printer<'tcx> for SymbolMangler<'tcx> {
...
-                    }
+                        Ok(cx)
+                    })?;
                 }
-                Ok(cx)
-            })?;
+                ty::ExistentialPredicate::Projection(projection) => {
+                    let last_trait_ref = last_trait_ref
+                        .expect("trait predicate must come before projection predicate");
+                    assert_eq!(last_trait_ref.bound_vars(), predicate.bound_vars());
```
Comment (jackh726) [inline compiler/rustc_symbol_mangling/src/v0.rs:506]: This assertion probably won't actually hold when there are supertrait HRTBs.
Ex.
```
trait Foo<'c> { type Output; }
trait Bar<'a, 'b>: for<'c> Foo<'c> { }

dyn for<'a, 'b> Bar<Output = u32>
````

**Review by jackh726 — CHANGES_REQUESTED** [review]
Might have a cleaner way to approach this. @nikomatsakis and I discussed, and would also definitely like to see the example in my comment as a test case too.

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_symbol_mangling/src/v0.rs:490]: Still waiting on this comment :)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Hi @camelid! I'm more-or-less ready to r+ this, but I would still like to see a comment. Do you need help to write it?

**Comment by jackh726** [comment]
This needs a couple tests. Unless @camelid is around today, I'll get those done.

File: compiler/rustc_symbol_mangling/src/v0.rs (hunk 1 above)
Comment (jackh726) [reply compiler/rustc_symbol_mangling/src/v0.rs]: Added :)

**Comment by jackh726** [comment]
@nikomatsakis this is ready :)

**Comment by jackh726** [comment]
Ugh don't remember how to make this reproducible locally

File: src/test/ui/symbol-names/trait-objects.legacy.stderr [hunk 5]
```diff
@@ -1,53 +1,53 @@
...
+error: demangling(<&dyn core::ops::function::FnMut<(&u8,)>+Output = () as trait_objects::Bar>::metSYMBOL_HASH::SYMBOL_HASH)
+  --> $DIR/trait-objects.rs:17:5
    |
 LL |     #[rustc_symbol_name]
    |     ^^^^^^^^^^^^^^^^^^^^
 
-error: demangling-alt(<&dyn core::ops::function::FnMut<(&u8,)>+Output = () as trait_objects::Bar>::method)
-  --> $DIR/trait-objects.rs:15:5
+error: demangling-alt(<&dyn core::ops::function::FnMut<(&u8,)>+Output = () as trait_objects::Bar>::metSYMBOL_HASH)
+  --> $DIR/trait-objects.rs:17:5
```
Comment (camelid) [inline src/test/ui/symbol-names/trait-objects.legacy.stderr]: Is it expected that this changed from `::method` to `::metSYMBOL_HASH`?

Comment (jackh726) [reply src/test/ui/symbol-names/trait-objects.legacy.stderr]: Oh this file shouldn't be here currently...(mostly because I didn't think hard enough about what regex to use here to make it reproducible and we don't care about legacy here anyways)

**Review by nikomatsakis — APPROVED** [review]
