### PR TITLE
Fix revision support for UI tests.

### LINKED ISSUE #48878: add support for "test revisions" into `ui` tester
`ui` tests do not current support revisions. This blocks our goals to [migrate entirely over to unit tests](https://github.com/rust-lang/rust/issues/44844). We should fix it!

I imagine it working like this:

- For each test T with revisions R1..Rn, we would expect N stderr files:
  - `T.Ri.stderr`, where `Ri` is the current revision
- Comments on lines work as normal (`//[Ri]~ ERROR`)

However, it might be useful to permit tests to have a "fallback" `T.stderr` file, in which case the output is supposed to be the same for all revisions.  I am of mixed minds about this though: I don't know how often it would be useful, and I fear "dead stderr files" that are not used. Probably best not to have it.

### PR DESCRIPTION
**Pull request by ehuss**
Fixes #48878

### CODE REVIEW

**Comment by ehuss** [comment]
cc @nikomatsakis 

I tried to make the code a little more explicit and cleaner to avoid confusion, though I'm not sure I succeeded. :)  Everything should work the same as before, except UI tests can now output `TESTNAME.REVISION.stderr/stdout` files.

In order to generate the output for a test with multiple revisions, you have to run compiletest separately for each revision because it stops immediately when a revision fails.  There doesn't seem to be the equivalent of `--no-fail-fast` for compiletest.  Thoughts?

**Comment by nikomatsakis** [comment]
@ehuss 

> In order to generate the output for a test with multiple revisions, you have to run compiletest separately for each revision because it stops immediately when a revision fails. There doesn't seem to be the equivalent of `--no-fail-fast` for compiletest. Thoughts?

Hmm, one idea would be to fix https://github.com/rust-lang/rust/issues/47604 -- @spastorino got *most* of the way there in https://github.com/rust-lang/rust/pull/48023, but got entangled in some of the mess that you're sorting out in this PR. A side-effect of this change would be that each revision is its own test, so they would all run independently of a failure.

File: src/tools/tidy/src/ui_tests.rs [hunk 1]
```diff
@@ -17,9 +17,19 @@ pub fn check(path: &Path, bad: &mut bool) {
...
+                // Some files have the pattern TESTNAME.stderr, some have
+                // TESTNAME.REVISION.stderr.  Grab the TESTNAME from
+                // everything up to the first dot.
+                let testname = file_path.file_name().unwrap()
+                                        .to_str().unwrap()
+                                        .splitn(2, '.').next().unwrap();
+                if !file_path.with_file_name(testname)
+                             .with_extension("rs")
+                             .exists() {
+                    println!("Stray file with UI testing output: {:?}", file_path);
```
Comment (nikomatsakis) [inline src/tools/tidy/src/ui_tests.rs]: cc @pnkfelix

**Review by nikomatsakis — APPROVED** [review]

File: src/tools/compiletest/src/runtest.rs [hunk 2]
```diff
@@ -1834,25 +1848,26 @@ impl<'test> TestCx<'test> {
...
+    /// `/path/to/build/<triple>/test/compile-fail/foo/bar`.
     fn output_base_name(&self) -> PathBuf {
         let dir = self.config.build_base.join(&self.testpaths.relative_dir);
 
         // Note: The directory `dir` is created during `collect_tests_from_dir`
         dir.join(&self.output_testname(&self.testpaths.file))
-            .with_extension(&self.config.stage_id)
+    }
+
+    fn output_base_name_stage(&self) -> PathBuf {
```
Comment (nikomatsakis) [inline src/tools/compiletest/src/runtest.rs]: Maybe a comment?

Comment (nikomatsakis) [reply src/tools/compiletest/src/runtest.rs]: I believe this returns `foo/bar.stage1`, right?

File: src/tools/compiletest/src/runtest.rs [hunk 3]
```diff
@@ -2864,7 +2879,9 @@ impl<'test> TestCx<'test> {
             }
         }
 
-        let output_file = self.output_base_name().with_extension(kind);
+        let output_file = self.output_base_name()
```
Comment (nikomatsakis) [inline src/tools/compiletest/src/runtest.rs]: Why do we *not* want the stage here?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
On second read, I'm perhaps confused.

File: src/tools/compiletest/src/runtest.rs (hunk 3 above)
Comment (ehuss) [reply src/tools/compiletest/src/runtest.rs]: Good question.  What are the arguments in favor of including the stage?  Is it to guard against using the wrong cached results if you run `x.py test --stage 1` and `x.py test --stage 2` separately?

One issue is that `update-references.sh` won't know which stage to use.  We could add that as another argument, and print the correct stage in the usage instructions.

Some of the other tests that don't include the stage may need to be updated as well.  I was reluctant to do so because I don't fully understand the need and consequences.

File: src/tools/compiletest/src/runtest.rs (hunk 2 above)
Comment (ehuss) [reply src/tools/compiletest/src/runtest.rs]: Stage also includes the platform triple (like `foo/bar.stage1-x86_64-apple-darwin`).  That is...a little confusing. :)

Comment (nikomatsakis) [reply src/tools/compiletest/src/runtest.rs]: ok -- in any case I'd like to see a comment =)

File: src/tools/compiletest/src/runtest.rs (hunk 3 above)
Comment (nikomatsakis) [reply src/tools/compiletest/src/runtest.rs]: > What are the arguments in favor of including the stage?

The way I always imagined it, we use the stage/target data to effectively "isolate" stage1 and stage2 tests from one another completely. To be honest, I think we should be using separate directories altogether (i.e, `src/test/stage1`). I'm not sure why we don't, I think for no particularly good reason.

But you're right that I don't know what can go wrong in *particular*.

Comment (nikomatsakis) [reply src/tools/compiletest/src/runtest.rs]: > One issue is that update-references.sh won't know which stage to use. We could add that as another argument, and print the correct stage in the usage instructions.

Seems fair. We can leave as is for now.

Comment (nikomatsakis) [reply src/tools/compiletest/src/runtest.rs]: If we moved to `./x.py bless`, then you could do `./x.py bless --stage 1` and so forth to specify the test suite that you ran. (Maybe it should be `./x.py test --bless`? Anyway.)

**Comment by ehuss** [comment]
@nikomatsakis I just wanted to confirm, what you'd like me to do in regards to the new NLL compare-mode changes.  For this PR, I at least need to redo the tidy checks (cc @pnkfelix).

Long term do you want the output files to be `$test.$rev.$mode.stderr` (where rev and mode are optional)?  The new tidy check might be a little aggressive since it can't handle `$test.$rev.stderr`.  

AFAIK, compiletest currently doesn't handle generating output files with the $mode part (and update-references doesn't handle it either).  I'm guessing updates to support that should be in another PR?

**Comment by nikomatsakis** [comment]
@ehuss that does need to be decided =) 

I think though it might be most practical if compare-mode=nll used an nll revision *if available* but otherwise used a kind of "default" revision.

**Comment by nikomatsakis** [comment]
That is to say, I feel like 'compare-mode' might perhaps be better considered a kind of "automatic revision" that applies to every test which does not already have one. (And -- indeed -- perhaps revisions also want the same "failover" behavior for their stderr files? I guess that's the question.)

File: src/tools/tidy/src/ui_tests.rs (hunk 1 above)
Comment (pnkfelix) [reply src/tools/tidy/src/ui_tests.rs]: Grabbing everything up to first dot to derive the source file name sounds like a reasonable start to me.

**Comment by ehuss** [comment]
I think this is now working well with the latest NLL updates.  With a sample test from compile-fail, it was able to successfully create `mir`, `ast`, and `ast.nll` variants, and everything seems happy.

**Comment by nikomatsakis** [comment]
> I think this is now working well with the latest NLL updates. With a sample test from compile-fail, it was able to successfully create mir, ast, and ast.nll variants, and everything seems happy.

@ehuss can you say a bit more? What was the test you tried? I don't quite understand what "everything seems happy" means. =)

**Review by nikomatsakis — APPROVED** [review]

**Comment by ehuss** [comment]
> What was the test you tried?

I tried copying over some tests from `compile-fail` (without the stderr files).  Example of going through this dance:

1. Run `x.py test`.  Test fails.
2. Run `update-references.sh` to copy over `xxx.ast.stderr`.
3. Run `x.py test`.  Test fails.
4. Run `update-references.sh` to copy over `xxx.mir.stderr`.
5. Run `x.py test`.  Test fails.
6. Run `update-references.sh` to copy over `xxx.ast.nll.stderr`.
7. Run `x.py test`.  Test succeeds!  (The mir NLL is the same without NLL in this example, so no file is generated.)

And verified that the `stderr` files look reasonable.
