### PR TITLE
Ignore all debuginfo tests for LLDB that we do not run in CI

### LINKED ISSUE #151966: LLDB testing should be disabled
Per @khyperia in https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp/topic/debuginfo.20tests.20broken.20locally/with/571307617 these tests don't run in CI. On a contributor's machine they can easily fail to pass, for reasons I am not going to get into in this issue description because clearly I *should not* care about the specifics of why if we are not running these tests in CI. We should disable these sooner rather than later, long before trying to do any Big Cleanup projects for debuginfo testing.

### PR DESCRIPTION
**Pull request by workingjubilee**
We only run LLDB 1500 in CI. Any test with a min-lldb-version above that is currently ignored. It's not clear any of these tests actually work with that LLDB version, and they definitely don't work on LLDB ~2100. So, ignore them until we fix debuginfo testing.

Fixes rust-lang/rust#151966

### CODE REVIEW

File: tests/debuginfo/opt/dead_refs.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-//@ min-lldb-version: 1800
+//@ ignore-lldb
```
Comment (workingjubilee) [inline tests/debuginfo/opt/dead_refs.rs:2]: Now using `ignore-lldb` for all cases, and found this case also.

**Comment by Noratrieb** [comment]
@bors r+ rollup
sounds good. alternatively we may want to just never use lldb on non-apple by default.
