### PR TITLE
`-Znext-solver` use the trait object's own bounds instead of goal when considering builtin object bounds

### LINKED ISSUE #151329: [ICE]: `could not replace AliasTerm` (unsatisifed bounds)
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Znext-solver=globally
trait Foo {
    type V;
}

trait Callback<T: Foo>: Fn(&T, &T::V) {}

struct Bar<T: Foo> {
    callback: Box<dyn Callback<T>>,
}

impl<T: Foo> Bar<dyn Callback<T>> {
    fn event(&self) {
        (self.callback)(any(), any());
    }
}

struct A;
struct B;

````

original:
````rust
fn any<T>() -> T { loop {} }

trait Foo { type V; }

trait Callback<T: Foo>: Fn(&T, &T::V) {}
impl<T: Foo, F: Fn(&T, &T::V)> Callback<T> for F {}

struct Bar<T: Foo> {
    callback: Box<dyn Callback<T>>,
}

impl<T: Foo> Bar<dyn Callback<T>> {
    fn event(&self) {
        (self.callback)(any(), any());
    }
}

struct A;
struct B;
impl Foo for A { type V = B; }

fn main() {
    let elem = 1i32;
    foo.event();
}

````

Version information
````
rustc 1.95.0-nightly (621d76794 2026-01-18)
binary: rustc
commit-hash: 621d76794c76fc21c0a6151fbc090120e0230a91
commit-date: 2026-01-18
host: x86_64-unknown-linux-gnu
release: 1.95.0-nightly
LLVM version: 21.1.8

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/621d76794c76fc21c0a6151fbc090120e0230a91/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs#L960-L972

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Znext-solver=globally`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:18:10
   |
18 | struct B;
   |          ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs`

error[E0277]: the size for values of type `(dyn Callback<T> + 'static)` cannot be known at compilation time
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:11:14
   |
11 | impl<T: Foo> Bar<dyn Callback<T>> {
   |              ^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `(dyn Callback<T> + 'static)`
note: required by an implicit `Sized` bound in `Bar`
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:7:12
   |
 7 | struct Bar<T: Foo> {
   |            ^ required by the implicit `Sized` requirement on this type parameter in `Bar`
help: consider relaxing the implicit `Sized` restriction
   |
 7 | struct Bar<T: Foo + ?Sized> {
   |                   ++++++++

error[E0277]: the size for values of type `(dyn Callback<T> + 'static)` cannot be known at compilation time
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:12:14
   |
12 |     fn event(&self) {
   |              ^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `(dyn Callback<T> + 'static)`
note: required by an implicit `Sized` bound in `Bar`
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:7:12
   |
 7 | struct Bar<T: Foo> {
   |            ^ required by the implicit `Sized` requirement on this type parameter in `Bar`
help: consider relaxing the implicit `Sized` restriction
   |
 7 | struct Bar<T: Foo + ?Sized> {
   |                   ++++++++


thread 'rustc' (1999399) panicked at /rustc-dev/621d76794c76fc21c0a6151fbc090120e0230a91/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:966:13:
could not replace AliasTerm { args: [dyn [Binder { value: Trait(Callback<dyn Callback<!0>>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) dyn [Binder { value: Trait(Callback<!0>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) !0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [!0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [dyn [Binder { value: Trait(Callback<!0>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) !0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [!0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0, (?0t, ?1t)], def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), .. } with term from from dyn [Binder { value: Trait(Callback<dyn Callback<!0>>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) dyn [Binder { value: Trait(Callback<!0>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) !0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [!0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [dyn [Binder { value: Trait(Callback<!0>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(2:4226 ~ core[7477]::ops::function::FnOnce::Output), args: [(&'^0.Named(DefId(0:17 ~ mvce[a621]::Callback::'_)) !0, &'^1.Named(DefId(0:18 ~ mvce[a621]::Callback::'_#1)) Alias(Projection, AliasTy { args: [!0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0], def_id: DefId(0:4 ~ mvce[a621]::Foo::V), .. }))], term: Term::Ty(()), use_existential_projection_new_instead: () }), bound_vars: [Region(BrNamed(DefId(0:17 ~ mvce[a621]::Callback::'_))), Region(BrNamed(DefId(0:18 ~ mvce[a621]::Callback::'_#1)))] }] + '?0
stack backtrace:
   0:     0x7f3560233fd3 - <<std[287527946f71f0bc]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[7477a31a1a34cc49]::fmt::Display>::fmt
   1:     0x7f356080e2c8 - core[7477a31a1a34cc49]::fmt::write
   2:     0x7f356024a9c6 - <std[287527946f71f0bc]::sys::stdio::unix::Stderr as std[287527946f71f0bc]::io::Write>::write_fmt
   3:     0x7f356020a048 - std[287527946f71f0bc]::panicking::default_hook::{closure#0}
   4:     0x7f3560227703 - std[287527946f71f0bc]::panicking::default_hook
   5:     0x7f355f1fbb8a - std[287527946f71f0bc]::panicking::update_hook::<alloc[979041e9952e771b]::boxed::Box<rustc_driver_impl[517260a07841a630]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f35602279e2 - std[287527946f71f0bc]::panicking::panic_with_hook
   7:     0x7f356020a108 - std[287527946f71f0bc]::panicking::panic_handler::{closure#0}
   8:     0x7f3560200dc9 - std[287527946f71f0bc]::sys::backtrace::__rust_end_short_backtrace::<std[287527946f71f0bc]::panicking::panic_handler::{closure#0}, !>
   9:     0x7f356020bbdd - __rustc[5ec7081ce87b032f]::rust_begin_unwind
  10:     0x7f355cd0cfbc - core[7477a31a1a34cc49]::panicking::panic_fmt
  11:     0x7f3561235810 - <rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::structural_traits::ReplaceProjectionWith<rustc_middle[725063e074f29df]::ty::context::TyCtxt, rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate> as rustc_type_ir[b93cf349b3a4f34d]::fold::FallibleTypeFolder<rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::try_fold_ty
  12:     0x7f3561234ac8 - <&rustc_middle[725063e074f29df]::ty::list::RawList<(), rustc_middle[725063e074f29df]::ty::generic_args::GenericArg> as rustc_type_ir[b93cf349b3a4f34d]::fold::TypeFoldable<rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::try_fold_with::<rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::structural_traits::ReplaceProjectionWith<rustc_middle[725063e074f29df]::ty::context::TyCtxt, rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate>>
  13:     0x7f35619c9e80 - rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::structural_traits::predicates_for_object_candidate::<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>
  14:     0x7f356172ee31 - <rustc_type_ir[b93cf349b3a4f34d]::predicate::TraitPredicate<rustc_middle[725063e074f29df]::ty::context::TyCtxt> as rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::GoalKind<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::match_assumption::<<rustc_type_ir[b93cf349b3a4f34d]::predicate::TraitPredicate<rustc_middle[725063e074f29df]::ty::context::TyCtxt> as rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::GoalKind<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::probe_and_consider_object_bound_candidate::{closure#0}>
  15:     0x7f356172e9b3 - <rustc_type_ir[b93cf349b3a4f34d]::predicate::TraitPredicate<rustc_middle[725063e074f29df]::ty::context::TyCtxt> as rustc_next_trait_solver[2bc6883c9be4be93]::solve::assembly::GoalKind<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::probe_and_consider_object_bound_candidate
  16:     0x7f3561729bbc - <rustc_next_trait_solver[2bc6883c9be4be93]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::compute_trait_goal
  17:     0x7f356141b74f - <rustc_next_trait_solver[2bc6883c9be4be93]::solve::search_graph::SearchGraphDelegate<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate> as rustc_type_ir[b93cf349b3a4f34d]::search_graph::Delegate>::compute_goal::{closure#0}
  18:     0x7f35614323a3 - <rustc_next_trait_solver[2bc6883c9be4be93]::solve::eval_ctxt::EvalCtxt<rustc_trait_selection[9fee51d8a10a777c]::solve::delegate::SolverDelegate, rustc_middle[725063e074f29df]::ty::context::TyCtxt>>::evaluate_goal_raw
  19:     0x7f35614310dd - <rustc_infer[5a785d1c27494969]::infer::InferCtxt as rustc_trait_selection[9fee51d8a10a777c]::traits::query::evaluate_obligation::InferCtxtExt>::goal_may_hold_opaque_types_jank
  20:     0x7f3560fbff94 - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::lookup_method_for_operator
  21:     0x7f3560c6327c - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::try_overloaded_call_traits
  22:     0x7f3560c40dbc - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::check_expr_call
  23:     0x7f3560c199b0 - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:     0x7f3560c14ac2 - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::check_expr_block
  25:     0x7f3560c1998b - <rustc_hir_typeck[ed5453188701a25b]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f3560bfa1a6 - rustc_hir_typeck[ed5453188701a25b]::check::check_fn
  27:     0x7f35615b3d33 - rustc_hir_typeck[ed5453188701a25b]::typeck_with_inspect::{closure#0}
  28:     0x7f35615b26b4 - rustc_query_impl[f20b8284200e680a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f20b8284200e680a]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[725063e074f29df]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f356095522a - rustc_query_system[b7e73caa2c2ad9a]::query::plumbing::try_execute_query::<rustc_query_impl[f20b8284200e680a]::DynamicConfig<rustc_data_structures[e0d8483206daafa2]::vec_cache::VecCache<rustc_span[851f35e07e3c2dd4]::def_id::LocalDefId, rustc_middle[725063e074f29df]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[b7e73caa2c2ad9a]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[f20b8284200e680a]::plumbing::QueryCtxt, false>
  30:     0x7f3560954b09 - rustc_query_impl[f20b8284200e680a]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f356133fdb5 - <rustc_middle[725063e074f29df]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[1a80394817eddfdd]::check_crate::{closure#2}>::{closure#0}
  32:     0x7f356133f7c4 - rustc_hir_analysis[1a80394817eddfdd]::check_crate
  33:     0x7f35609493db - rustc_interface[5c48368f5debe80d]::passes::analysis
  34:     0x7f3560949035 - rustc_query_impl[f20b8284200e680a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f20b8284200e680a]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[725063e074f29df]::query::erase::Erased<[u8; 0usize]>>
  35:     0x7f35619a4be3 - rustc_query_system[b7e73caa2c2ad9a]::query::plumbing::try_execute_query::<rustc_query_impl[f20b8284200e680a]::DynamicConfig<rustc_query_system[b7e73caa2c2ad9a]::query::caches::SingleCache<rustc_middle[725063e074f29df]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[f20b8284200e680a]::plumbing::QueryCtxt, false>
  36:     0x7f35619a49ce - rustc_query_impl[f20b8284200e680a]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7f3561b82c11 - <rustc_interface[5c48368f5debe80d]::passes::create_and_enter_global_ctxt<core[7477a31a1a34cc49]::option::Option<rustc_interface[5c48368f5debe80d]::queries::Linker>, rustc_driver_impl[517260a07841a630]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[7477a31a1a34cc49]::ops::function::FnOnce<(&rustc_session[eb79e6d3104f29ae]::session::Session, rustc_middle[725063e074f29df]::ty::context::CurrentGcx, alloc[979041e9952e771b]::sync::Arc<rustc_data_structures[e0d8483206daafa2]::jobserver::Proxy>, &std[287527946f71f0bc]::sync::once_lock::OnceLock<rustc_middle[725063e074f29df]::ty::context::GlobalCtxt>, &rustc_data_structures[e0d8483206daafa2]::sync::worker_local::WorkerLocal<rustc_middle[725063e074f29df]::arena::Arena>, &rustc_data_structures[e0d8483206daafa2]::sync::worker_local::WorkerLocal<rustc_hir[7eac7792dedc1861]::Arena>, rustc_driver_impl[517260a07841a630]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  38:     0x7f35619f5d34 - rustc_interface[5c48368f5debe80d]::interface::run_compiler::<(), rustc_driver_impl[517260a07841a630]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7f356195aa3a - std[287527946f71f0bc]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5c48368f5debe80d]::util::run_in_thread_with_globals<rustc_interface[5c48368f5debe80d]::util::run_in_thread_pool_with_globals<rustc_interface[5c48368f5debe80d]::interface::run_compiler<(), rustc_driver_impl[517260a07841a630]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  40:     0x7f356195a7fe - <std[287527946f71f0bc]::thread::lifecycle::spawn_unchecked<rustc_interface[5c48368f5debe80d]::util::run_in_thread_with_globals<rustc_interface[5c48368f5debe80d]::util::run_in_thread_pool_with_globals<rustc_interface[5c48368f5debe80d]::interface::run_compiler<(), rustc_driver_impl[517260a07841a630]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[7477a31a1a34cc49]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f356195c5c4 - <std[287527946f71f0bc]::sys::thread::unix::Thread>::new::thread_start
  42:     0x7f355b29698b - <unknown>
  43:     0x7f355b31a9cc - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.95.0-nightly (621d76794 2026-01-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z next-solver=globally -Z dump-mir-dir=dir

query stack during panic:
#0 [typeck] type-checking `<impl at /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:11:1: 11:34>::event`
#1 [analysis] running analysis passes on crate `mvce`
end of query stack
error[E0425]: cannot find function `any` in this scope
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:13:25
   |
13 |         (self.callback)(any(), any());
   |                         ^^^ not found in this scope

error[E0425]: cannot find function `any` in this scope
  --> /tmp/icemaker_global_tempdir.P7n4BPAPG2qy/rustc_testrunner_tmpdir_reporting.Ihw4lR5RFRrV/mvce.rs:13:32
   |
13 |         (self.callback)(any(), any());
   |                                ^^^ not found in this scope

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0277, E0425, E0601.
For more information about an error, try `rustc --explain E0277`.

```

</p>
</details>

@rustbot label +WG-trait-system-refactor

### LINKED ISSUE #152789: `-Znext-solver`: trait object candidate ICE "could not replace AliasTerm"
### Code

```Rust
pub trait Trait<T> {
    type Assoc;
}

pub trait Foo {
    type FooAssoc;
}

pub struct Wrap<U: Foo>(<dyn Trait<i32, Assoc = i64> as Trait<U::FooAssoc>>::Assoc)
where
    dyn Trait<i32, Assoc = i64>: Trait<U::FooAssoc>;

fn main() {}
```

This code compiles with the old trait solver, but ICEs with `-Znext-solver`.

This was discovered while investigating #152783

Has a similar error message to #151329

cc @lcnr

### Meta

`rustc --version --verbose`:
```
rustc 1.95.0-nightly (838709580 2026-02-17)
binary: rustc
commit-hash: 8387095803f21a256a9a772ac1f9b41ed4d5aa0a
commit-date: 2026-02-17
host: aarch64-apple-darwin
release: 1.95.0-nightly
LLVM version: 22.1.0
```

### Error output

```
thread 'rustc' (296541) panicked at /rustc-dev/8387095803f21a256a9a772ac1f9b41ed4d5aa0a/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs:966:13:
could not replace AliasTerm { args: [dyn [Binder { value: Trait(Trait<i32>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(0:5 ~ foo[b507]::Trait::Assoc), args: [i32], term: Term::Ty(i64), use_existential_projection_new_instead: () }), bound_vars: [] }] + '?0, Alias(Projection, AliasTy { args: [!0], def_id: DefId(0:7 ~ foo[b507]::Foo::FooAssoc), .. })], def_id: DefId(0:5 ~ foo[b507]::Trait::Assoc), .. } with term from from dyn [Binder { value: Trait(Trait<i32>), bound_vars: [] }, Binder { value: Projection(ExistentialProjection { def_id: DefId(0:5 ~ foo[b507]::Trait::Assoc), args: [i32], term: Term::Ty(i64), use_existential_projection_new_instead: () }), bound_vars: [] }] + '?0
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_next_trait_solver::solve::assembly::structural_traits::ReplaceProjectionWith<rustc_middle::ty::context::TyCtxt, rustc_trait_selection::solve::delegate::SolverDelegate>>::try_eagerly_replace_alias
   3: <rustc_middle::ty::generic_args::GenericArg as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_next_trait_solver::solve::assembly::structural_traits::ReplaceProjectionWith<rustc_middle::ty::context::TyCtxt, rustc_trait_selection::solve::delegate::SolverDelegate>>
   4: <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::try_fold_with::<rustc_next_trait_solver::solve::assembly::structural_traits::ReplaceProjectionWith<rustc_middle::ty::context::TyCtxt, rustc_trait_selection::solve::delegate::SolverDelegate>>
   5: rustc_next_trait_solver::solve::assembly::structural_traits::predicates_for_object_candidate::<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>
   6: <rustc_type_ir::predicate::TraitPredicate<rustc_middle::ty::context::TyCtxt> as rustc_next_trait_solver::solve::assembly::GoalKind<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::match_assumption::<<rustc_type_ir::predicate::TraitPredicate<rustc_middle::ty::context::TyCtxt> as rustc_next_trait_solver::solve::assembly::GoalKind<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::probe_and_consider_object_bound_candidate::{closure#0}>
   7: <rustc_type_ir::predicate::TraitPredicate<rustc_middle::ty::context::TyCtxt> as rustc_next_trait_solver::solve::assembly::GoalKind<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::probe_and_match_goal_against_assumption::<<rustc_type_ir::predicate::TraitPredicate<rustc_middle::ty::context::TyCtxt> as rustc_next_trait_solver::solve::assembly::GoalKind<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::probe_and_consider_object_bound_candidate::{closure#0}>
   8: <rustc_next_trait_solver::solve::eval_ctxt::EvalCtxt<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::compute_trait_goal
   9: <rustc_next_trait_solver::solve::search_graph::SearchGraphDelegate<rustc_trait_selection::solve::delegate::SolverDelegate> as rustc_type_ir::search_graph::Delegate>::compute_goal::{closure#0}
  10: <rustc_type_ir::search_graph::SearchGraph<rustc_next_trait_solver::solve::search_graph::SearchGraphDelegate<rustc_trait_selection::solve::delegate::SolverDelegate>, rustc_middle::ty::context::TyCtxt>>::evaluate_goal_in_task
  11: <rustc_next_trait_solver::solve::eval_ctxt::EvalCtxt<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::evaluate_goal_raw
  12: <rustc_next_trait_solver::solve::eval_ctxt::EvalCtxt<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::evaluate_added_goals_step
  13: <rustc_next_trait_solver::solve::search_graph::SearchGraphDelegate<rustc_trait_selection::solve::delegate::SolverDelegate> as rustc_type_ir::search_graph::Delegate>::compute_goal::{closure#0}
  14: <rustc_type_ir::search_graph::SearchGraph<rustc_next_trait_solver::solve::search_graph::SearchGraphDelegate<rustc_trait_selection::solve::delegate::SolverDelegate>, rustc_middle::ty::context::TyCtxt>>::evaluate_goal_in_task
  15: <rustc_next_trait_solver::solve::eval_ctxt::EvalCtxt<rustc_trait_selection::solve::delegate::SolverDelegate, rustc_middle::ty::context::TyCtxt>>::evaluate_goal_raw
  16: <rustc_trait_selection::solve::delegate::SolverDelegate as rustc_next_trait_solver::solve::eval_ctxt::SolverDelegateEvalExt>::evaluate_root_goal
  17: <rustc_trait_selection::solve::fulfill::FulfillmentCtxt<rustc_trait_selection::traits::FulfillmentError> as rustc_infer::traits::engine::TraitEngine<rustc_trait_selection::traits::FulfillmentError>>::try_evaluate_obligations
  18: <rustc_trait_selection::solve::normalize::NormalizationFolder<rustc_trait_selection::traits::FulfillmentError>>::normalize_alias_term
  19: <rustc_trait_selection::solve::normalize::NormalizationFolder<rustc_trait_selection::traits::FulfillmentError> as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty::{closure#0}
  20: <rustc_hir_analysis::check::wfcheck::WfCheckingCtxt>::deeply_normalize::<rustc_middle::ty::Ty>
  21: rustc_hir_analysis::check::wfcheck::check_type_defn
  22: rustc_hir_analysis::check::check::check_item_type
  23: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  24: rustc_hir_analysis::check::wfcheck::check_type_wf
      [... omitted 1 frame ...]
  25: rustc_hir_analysis::check_crate
  26: rustc_interface::passes::analysis
  27: rustc_query_impl::execution::try_execute_query::<rustc_middle::query::caches::SingleCache<rustc_middle::query::erase::ErasedData<[u8; 0]>>, {rustc_query_impl::QueryFlags { is_anon: false, is_depth_limit: false, is_feedable: false }}, true>
  28: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>
  29: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. This is a bug

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/timch/foo/rustc-ice-2026-02-18T08_49_10-24860.txt` to your bug report

note: rustc 1.95.0-nightly (838709580 2026-02-17) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED] -Z next-solver

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_well_formed] checking that `Wrap` is well-formed
#1 [check_type_wf] checking that types are well-formed
#2 [analysis] running analysis passes on crate `foo`
end of query stack
error: could not compile `foo` (bin "foo")
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/152859)*

Fixes https://github.com/rust-lang/rust/issues/152789 and fixes https://github.com/rust-lang/rust/issues/151329

r? lcnr

### CODE REVIEW

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 1]
```diff
@@ -83,14 +83,21 @@ where
         assumption: I::Clause,
     ) -> Result<Candidate<I>, NoSolution> {
         Self::probe_and_match_goal_against_assumption(ecx, source, goal, assumption, |ecx| {
+            ecx.try_evaluate_added_goals()?;
```
Comment (ShoyuVanilla) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: https://github.com/rust-lang/rust/blob/1eb36c651676c1101f3049a122a4aa38bb5c45a4/compiler/rustc_next_trait_solver/src/solve/trait_goals.rs#L192-L194

We equate the goal with the assumption before entering this closure in the above lines.
However, that eq relationship does not actually hold in the problematic cases from the linked issues.

Because this additional goal is introduced through that equality, the ICE still occurs even if we use the trait ref from the trait object (instead of the goal's trait ref) when calling `predicates_for_object_candidate`.
Those predicates are evaluated here, in `projection_may_match`:
https://github.com/rust-lang/rust/blob/1eb36c651676c1101f3049a122a4aa38bb5c45a4/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs#L937

I think short-circuiting candidates for which the equality cannot hold, before entering the remaining probing, would be harmless and prevent the ICE.

In fact, adding just that early check is enough to fix the ICE in the linked issues.
But I think using trait object's own bounds instead of goal's is correct, so changed the follwing lines as well.

File: compiler/rustc_next_trait_solver/src/coherence.rs [hunk 2]
```diff
@@ -425,7 +425,7 @@ where
                 }
             }
             ty::Dynamic(tt, ..) => {
-                let principal = tt.principal().map(|p| p.def_id());
+                let principal = tt.principal_def_id();
```
Comment (ShoyuVanilla) [inline compiler/rustc_next_trait_solver/src/coherence.rs:428]: This change is irrelevant of the issue but seems trivial 😅

**Comment by ShoyuVanilla** [comment]
Hmm, the CI failure looks sus. Am I doing somewhat very incorrect thingy?

**Comment by ShoyuVanilla** [comment]
> How? do you still have the code which ICEd when using the trait object arguments lying around?

The very same code from the beginning

```rust
pub trait Trait<T> {
    type Assoc;
}

pub trait Foo {
    type FooAssoc;
}

pub struct Wrap<U: Foo>(<dyn Trait<i32, Assoc = i64> as Trait<U::FooAssoc>>::Assoc)
where
    dyn Trait<i32, Assoc = i64>: Trait<U::FooAssoc>;

fn main() {}
```

but maybe I've done what you said in a very wrong way, as the CI failed with very suspicious segfault: https://github.com/rust-lang/rust/actions/runs/22516543500/job/65235925254

**Comment by ShoyuVanilla** [comment]
> Given the way this is setup, all projections should structurally match and we shouldn't have to do any interesting type system stuff there at all. Could you replace the code to check whether the arguments are structurally equal instead of doing proper type system equality?

Oh, that sounds like a correct way. Would it be sth like the following?

```diff
    fn projection_may_match(
        &mut self,
        source_projection: ty::Binder<I, ty::ProjectionPredicate<I>>,
        target_projection: ty::AliasTerm<I>,
    ) -> bool {
        source_projection.item_def_id() == target_projection.def_id
            && self
                .ecx
                .probe(|_| ProbeKind::ProjectionCompatibility)
                .enter(|ecx| -> Result<_, NoSolution> {
                    let source_projection = ecx.instantiate_binder_with_infer(source_projection);
-                   ecx.eq(self.param_env, source_projection.projection_term, target_projection)?;
-                   ecx.try_evaluate_added_goals()
+                   ecx.eq_structurally_relating_aliases(self.param_env, source_projection.projection_term, target_projection)
                })
                .is_ok()
    }
```

**Comment by ShoyuVanilla** [comment]
Uh-oh, I encountered the very same problem expressed in this test:
https://github.com/rust-lang/rust/pull/139774/changes#diff-30c364a67db542a51da9d3cc9120515d449317be5a564efe64fe6ec01e9913d4
The test ICEs with exactly the same reason the test says and looks like structural equality isn't enough 🤔

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 3]
```diff
@@ -88,10 +87,17 @@ where
             let ty::Dynamic(bounds, _) = goal.predicate.self_ty().kind() else {
                 panic!("expected object type in `probe_and_consider_object_bound_candidate`");
             };
+            let Some(principal) = bounds.principal() else {
+                panic!("expected principal for object type");
+            };
+            let principal = principal.with_self_ty(cx, goal.predicate.self_ty());
+            let trait_ref = elaborate::supertraits(cx, principal)
+                .find(|trait_ref| trait_ref.def_id() == goal.predicate.trait_def_id(cx))
+                .unwrap_or(principal);
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: does `supertraits` not also contain the trait itself? can you change this to instead be a `find().unwrap()` by making sure the iterator also contains the `principal` traitref it with the `principal`? 

also, can you move the `instantiate_binder_with_infer` into `predicates_for_object_candidate`?

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: > does `supertraits` not also contain the trait itself? can you change this to instead be a `find().unwrap()` by making sure the iterator also contains the `principal` traitref it with the `principal`?

The above lines are for finding supertrait of the object bound matching the goal's trait def. So..

```rust
trait Foo {}
trait Bar {}

fn implements_foo(_: &impl Foo) {}

fn bar(bar: &dyn Bar) {
    implements_foo(&bar);
}
```

I guess in the cases as the above, the `goal`'s trait is `Foo` but the supertraits wouldn't contain it

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: > also, can you move the `instantiate_binder_with_infer` into `predicates_for_object_candidate`?

🙆

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: > > does `supertraits` not also contain the trait itself? can you change this to instead be a `find().unwrap()` by making sure the iterator also contains the `principal` traitref it with the `principal`?
> 
> The above lines are for finding supertrait of the object bound matching the goal's trait def. So..
> 
> ```rust
> trait Foo {}
> trait Bar {}
> 
> fn implements_foo(_: &impl Foo) {}
> 
> fn bar(bar: &dyn Bar) {
>     implements_foo(&bar);
> }
> ```
> 
> I guess in the cases as the above, the `goal`'s trait is `Foo` but the supertraits wouldn't contain it

but that should always fail the "match assumption" check, should it, does unwrapping here ICE?

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: Oh, you're right. Yeah, they should be rejected by the match assumption due to different def ids for their trait refs 😅 I'll just unwrap instead of this

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: Oops, actually ICEing 😅 I'll look into this after my vacation.

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: The ICEs were from the cases that the goal is an auto trait goal, e.g. `<dyn Trait + Send as Send>` as we are calling this with the auto trait bounds assumptions as well:

https://github.com/rust-lang/rust/blob/cde9cf08d7a79042758db8d5d824d0341da97f7a/compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs#L849-L859

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs [hunk 4]
```diff
@@ -88,10 +88,24 @@ where
...
+                ty::Binder::dummy(goal.predicate.trait_ref(cx))
+            } else {
+                let Some(principal) = bounds.principal() else {
+                    panic!("expected principal for object type");
+                };
+                let principal = principal.with_self_ty(cx, goal.predicate.self_ty());
+                elaborate::supertraits(cx, principal)
+                    .find(|trait_ref| trait_ref.def_id() == goal.predicate.trait_def_id(cx))
+                    .unwrap()
+            };
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: instead of recomputing the `trait_ref`, we should be able to use the `assumption` here, should we?

File: compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs [hunk 5]
```diff
@@ -41,10 +41,27 @@ where
...
+        self,
+        f: impl FnOnce(&mut EvalCtxt<'_, D>) -> T,
+        ignore_parent_goals: bool,
+    ) -> T {
         let ProbeCtxt { ecx: outer, probe_kind, _result } = self;
 
         let delegate = outer.delegate;
         let max_input_universe = outer.max_input_universe;
+        let nested_goals =
+            if ignore_parent_goals { Default::default() } else { outer.nested_goals.clone() };
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs]: slight impl change:

instead of `ignore_parent_goals: bool` which is somewhat confusing, could you pass `propagated_nested_goals` and then either pass in `outer.nested.clone()` or the empty thing

File: compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs (hunk 4 above)
Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: I'm not totally sure but as we already elaborate and iterate through them as assumptions here so I guess that might not only prevent recomputing the `trait_ref` but might save us from probing candidates many times with the same goal and trait ref as well, perhaps. I'll try that 👍 

https://github.com/rust-lang/rust/blob/e6b64a2f4c696b840f8a384ec28690eed6a5d267/compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs#L872-L882

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/assembly/mod.rs]: i would expect that the assumption is the trait_ref we want to generate the impl for :+1:

File: compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs (hunk 5 above)
Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs]: still necessary, after that r=me

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs]: I've changed it [here](https://github.com/rust-lang/rust/compare/81cba7cdc840c338307c94f253a6911fdc0c3828..2a3b2b47ca1a7b937569e4e8bf23ee55a56a3ec5#diff-118b829019e774a2415817d9f495c1cd11203a26ea3596b999abde37bbac7619). Would there be sth I'm still missing, like making it as an binary enum rather than boolean?

Comment (lcnr) [reply compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs]: oh, I meant `propagated_nested_goals: Vec<(GoalSource, Goal<I, I::Predicate>, Option<GoalStalledOn<I>>)>`, so not "should we propagate nested goals", but "these are the nested goals we should propagate"

Comment (ShoyuVanilla) [reply compiler/rustc_next_trait_solver/src/solve/eval_ctxt/probe.rs]: ~~@lcnr Sorry for the ping 😅 Would this be okay as is or require another change?~~
Ah, we wrote the comments simultaneously 😅. I see. Thanks!

**Comment by panstromek** [comment]
perf triage:

another attempt

@rust-timer build c69ae78d2c950102bec958ce9e2a042279eecc89
