### PR TITLE
Make Rcs and Arcs use pointer comparison for unsized types

### LINKED ISSUE #154998: `MarkerEq` doesn't specialize on unsized types
If you write the following code, the `a == b` will not specialize to pointer comparisons purely because `str` is unsized. If a `String` were used, the address would be compared.

```rs
let a: Rc<str> = "example".into();
let b = Rc::clone(a);
a == b;
```

You can see an example on Godbolt here: https://godbolt.org/z/qeKMYvPo1.

The bug itself narrows down to, as far as I can see, the following code using `T: Eq` instead of `T: ?Sized + Eq`. Notably the code just below uses `?Sized + MarkerEq`, which will never occur unless a std type were to manually implement `MarkerEq` for some reason, leading me to believe that this is likely an unintended for this bound to fail on unsized types.

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0 (4a4ef493e 2026-03-02)
binary: rustc
commit-hash: 4a4ef493e3a1488c6e321570238084b38948f6db
commit-date: 2026-03-02
host: x86_64-pc-windows-msvc
release: 1.94.0
LLVM version: 21.1.8
```

### PR DESCRIPTION
**Pull request by Gaming32**
`Rc` and `Arc`s have an `Eq` implementation that first attempt to compare the pointers as an optimization. This, however, was not extended to DSTs, which is what this PR fixes.

Fixes rust-lang/rust#154998.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you provide some context on how this addresses the concerns from @theemathas and @Jules-Bertholet in the issue? Those seem at least plausible to me (i.e., this is a change in behavior).

**Comment by Gaming32** [comment]
This implements the idea from https://github.com/rust-lang/rust/issues/154998#issuecomment-4208790066. I included the example from @Jules-Bertholet in a test as well, and confirmed that it is still sound under the changes.

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

OK, I think this makes sense. Thanks for clarifying!

File: library/alloc/src/rc.rs [hunk 1]
```diff
@@ -2628,12 +2628,12 @@ impl<T: Eq> MarkerEq for T {}
 impl<T: ?Sized + MarkerEq, A: Allocator> RcEqIdent<T, A> for Rc<T, A> {
     #[inline]
     fn eq(&self, other: &Rc<T, A>) -> bool {
-        Rc::ptr_eq(self, other) || **self == **other
+        ptr::eq(self.ptr.as_ptr(), other.ptr.as_ptr()) || **self == **other
```
Comment (inkreasing) [inline library/alloc/src/rc.rs:2631]: Is this correct? The docs for `ptr::eq` state that vtable comparisons are unreliable.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155579/4fbae3e30923ca23262b696d54ddbd176c2c38b4..6f28cd5073b4738b3a630c7903fc0dd1d4f1e1f5)*

Comment (Gaming32) [reply library/alloc/src/rc.rs:2631]: If the vtables are equal, and the pointer is the same, then it will be the same value, as dereferencing either value will get identical results. If the vtables aren't equal, then we get the slow path, but this is the slow path that always happened anyway before this PR.
