### PR TITLE
macros: fix bug in collecting trait and impl items with derives.

### LINKED ISSUE #43023: Unexpected panic with derive debug on non-item
```
Compiling mount v0.3.0 (file:///var/www/sites/current/mount)
error: `derive` can be only be applied to items
  --> /var/www/sites/current/mount/src/mount.rs:63:14
   |
63 |     #[derive(Debug)]
   |              ^^^^^

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'adding a def'n for node-id NodeId(4294967295) and data TypeParam("H") but a previous def'n exists: DefKey { parent: Some(DefIndex(29)), disambiguated_data: DisambiguatedDefPathData { data: ValueNs("mount"), disambiguator: 0 } }', /checkout/src/librustc/hir/map/definitions.rs:479
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `mount`.
```

---

Code:

```
impl Mount {
    /// Creates a new instance of `Mount`.
    pub fn new() -> Mount {
        Mount {
            inner: SequenceTrie::new()
        }
    }

    /// Mounts a given `Handler` onto a route.
    ///
    /// This method may be called multiple times with different routes.
    /// For a given request, the *most specific* handler will be selected.
    ///
    /// Existing handlers on the same route will be overwritten.
    #[derive(Debug)]
    pub fn mount<H: Handler>(&mut self, route: &str, handler: H) -> &mut Mount {
        // Parse the route into a list of strings. The unwrap is safe because strs are UTF-8.
        let key: Vec<&str> = Path::new(route).components().flat_map(|c|
            match c {
                Component::RootDir => None,
                c => Some(c.as_os_str().to_str().unwrap())
            }
        ).collect();

        // Insert a match struct into the trie.
        let match_length = key.len();
        self.inner.insert(key, Match {
            handler: Box::new(handler) as Box<Handler>,
            length: match_length,
        });
        self
    }
}
```

I assume this is because of where I put the derive debug line.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #43023.
r? @nrc

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Nominating for backport because fixes a stable-to-beta regression (https://github.com/rust-lang/rust/issues/43023).

**Comment by arielb1** [comment]
```
[00:03:56] tidy error: /checkout/src/libsyntax/ext/expand.rs:755: line longer than 100 chars
```

@bors r-

File: src/test/compile-fail/issue-43023.rs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+struct S;
+
+impl S {
+    #[derive(Debug)] //~ ERROR `derive` can be only be applied to items
```
Comment (kennytm) [inline src/test/compile-fail/issue-43023.rs]: Please update the error messages.

```
[00:55:08] ---- [compile-fail] compile-fail/issue-43023.rs stdout ----
[00:55:08] 	
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:14: unexpected "error": '14:5: 14:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:21: unexpected "error": '21:5: 21:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:26: unexpected "error": '26:5: 26:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: 3 unexpected errors found, 0 expected errors not found
```

**Review by kennytm — CHANGES_REQUESTED** [review]

**Comment by alexcrichton** [comment]
@bors: p=1

fixing a regression and beta-accepted

**Comment by nikomatsakis** [comment]
Backporting to beta.
