### PR TITLE
Suggest an appropriate token when encountering `pub Ident<'a>`

### LINKED ISSUE #55403: Confusing error message: "can't qualify macro invocation with `pub`" when `struct` keyword missing
The program:
```
pub LexicalEnv<'a>
```
elicits the confusing error message:
```
error: can't qualify macro invocation with `pub`
 --> src/lib.rs:1:1
  |
1 | pub LexicalEnv<'a>
  | ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `<`
 --> src/lib.rs:1:15
  |
1 | pub LexicalEnv<'a>
  |               ^ expected one of `!` or `::` here
```
Similar issues have been filed before (#40006 and #38911, at least), and were not closed with an indication that the problem wasn't expected to be fixed, so I'm going ahead and filing this. This specific case was mentioned in [a comment](https://github.com/rust-lang/rust/issues/38911#issuecomment-342589773) by @fschutt.

### PR DESCRIPTION
**Pull request by estebank**
Fix #55403. Follow up to #45997.

### CODE REVIEW

File: src/test/ui/pub/pub-ident-fn-with-lifetime.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+pub   foo<'a>(_s: &'a usize) -> bool { true }
+//~^ ERROR missing `fn` for method definition
```
Comment (Centril) [inline src/test/ui/pub/pub-ident-fn-with-lifetime.rs]: Outside an `impl` it cannot possibly be a method so you should imo either 1) say "function definition", 2) check if there's a receiver `(&mut?)? self` and then say "method definition" or otherwise say "function definition.

**Comment by Centril** [comment]
I primarily had a look at the test files; but I'd like someone else to look at the implementation bits so I'll give r? back to you. :)

r? @michaelwoerister

File: src/test/ui/pub/pub-ident-fn-with-lifetime.rs (hunk 1 above)
Comment (estebank) [reply src/test/ui/pub/pub-ident-fn-with-lifetime.rs]: Done

**Comment by estebank** [comment]
ping @michaelwoerister

**Comment by michaelwoerister** [comment]
Hm, I don't know the parser very well. r? @petrochenkov maybe? Do we have a parser expert among the reviewers?
