### PR TITLE
Tweak trait not `use`d suggestion

### LINKED ISSUE #84272: Diagnostic when a trait is not in scope no longer tells you to add a use, instead tells you to box the receiver.
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=057c1715bd0bea7866420e59e5a070f1

```rust
// Not including std::hash::Hasher, which is why the build fails
use std::hash::BuildHasher;

fn next_u64() -> u64 {
    let bh = std::collections::hash_map::RandomState::new();
    let h = bh.build_hasher();
    h.finish()
}

fn main() {}
```

The current (`nightly`) output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `finish` found for struct `DefaultHasher` in the current scope
   --> src/main.rs:7:7
    |
7   |     h.finish()
    |       ^^^^^^ method not found in `DefaultHasher`
    |
help: consider wrapping the receiver expression with the appropriate type
    |
7   |     Box::new(h).finish()
    |     ^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |     Box::new(&mut h).finish()
    |     ^^^^^^^^^^^^^  ^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

On stable, there was a line telling you which trait you need to import in order to call the function.

```
   Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `finish` found for struct `DefaultHasher` in the current scope
   --> src/main.rs:7:7
    |
7   |     h.finish()
    |       ^^^^^^ method not found in `DefaultHasher`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
2   | use std::hash::Hasher;
    |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Also, boxing the object here isn't helpful, so it shouldn't be suggested.

Bisected this, and I'm *assuming* that the relevant issue is https://github.com/rust-lang/rust/pull/83667, but I'm not sure how I would verify that.

---

searched nightlies: from nightly-2021-03-30 to nightly-2021-03-31
regressed nightly: nightly-2021-03-31
searched commits: from https://github.com/rust-lang/rust/commit/48691ea6e639640f110b43e33d4aba1f07e7415c to https://github.com/rust-lang/rust/commit/74874a690bc95443292496ff5df5cc5c8cb56e0b
regressed commit: https://github.com/rust-lang/rust/commit/16156fb2787f745e57504197bd7fe38b69c6cbea

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --test-dir=. --start=2021-03-30 --end=2021-03-31 --preserve --script=./test.sh 
```

(where test.sh is
```sh
#!/bin/bash

cargo check 2>&1 | grep "std::hash::Hasher"
```
)
</details>

### PR DESCRIPTION
**Pull request by estebank**
Fix #84272. Follow up to #83667.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -996,6 +1002,27 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    // We point at the method, but we just skip the rest of the check for arbitrary
+                    // self types and rely on the suggestion to `use` the trait from
+                    // `suggest_valid_traits`.
+                    let did = Some(pick.item.container.id());
+                    let skip = skippable.contains(&did);
+                    if pick.autoderefs == 0 && !skip {
+                        err.span_label(
+                            pick.item.ident.span,
+                            &format!("the method is available for `{}` here", rcvr_ty),
+                        );
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1022]: I'm really not sure how useful this is...imo the *module*/`use` statement is enough.

**Review by jackh726 — COMMENTED** [review]
This looks reasonable except for the additional diagnostic. r=me with that removed or if you *really* think that extra label is helpful :)

File: compiler/rustc_typeck/src/check/method/suggest.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/method/suggest.rs:1022]: I *think* it helps a little bit when in concert with the suggestion, because the suggestion text doesn't explain why importing that trait would be enough.

**Comment by estebank** [comment]
I'll land the PR with the change and we can remove or reword later.

@bors r=jackh726
