### PR TITLE
Do not intern filemap to entry w/ mismatched length.

### LINKED ISSUE #37274: assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes
Hit on running `./mach test-unit` on https://github.com/Ms2ger/servo/tree/rustc-bug-codemap on travis.

```
12.18s$ ./mach test-unit

   Compiling util_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/util)

   Compiling profile_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/profile)

   Compiling net_traits_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/net_traits)

   Compiling net_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/net)

   Compiling gfx_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/gfx)

   Compiling script_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/script)

   Compiling layout_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/layout)

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', ../src/libsyntax/codemap.rs:707

stack backtrace:

   1:     0x7f623f0f79df - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2

   2:     0x7f623f106f0d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd

   3:     0x7f623f104386 - std::panicking::default_hook::h852b4223c1c00c59

   4:     0x7f623f104a68 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc

   5:     0x7f623b79a92f - std::panicking::begin_panic::hc03e2830c2c89a5f

   6:     0x7f623b7ff9c0 - syntax::codemap::CodeMap::bytepos_to_file_charpos::h3e1ecefe8c872433

   7:     0x7f623b7fc85f - syntax::codemap::CodeMap::lookup_char_pos::hfba960093e9845af

   8:     0x7f623dd0e8d7 - rustc_trans::mir::MirContext::scope_metadata_for_loc::hf4ec7e4a54af690a

   9:     0x7f623dd0e71c - rustc_trans::mir::MirContext::debug_loc::h081d6b2d00268062

  10:     0x7f623dd12a44 - rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'bcx, 'tcx>>::trans_block::he67d3259f79e4177

  11:     0x7f623dd10b58 - rustc_trans::mir::trans_mir::h2fb44ecb31cfdffa

  12:     0x7f623dcb2cdc - rustc_trans::base::trans_closure::h941de14309416d66

  13:     0x7f623dd30a34 - rustc_trans::trans_item::TransItem::define::ha4a18b94a3d46bf3

  14:     0x7f623dcb6254 - rustc_trans::base::trans_crate::h9b06de31ed8799d1

  15:     0x7f623f48cd4d - rustc_driver::driver::phase_4_translate_to_llvm::hc3883ea2c4750179

  16:     0x7f623f4c7cf7 - rustc_driver::driver::compile_input::{{closure}}::h9162a2fa292aeb3f

  17:     0x7f623f4beef3 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h1928c4704cfe9c61

  18:     0x7f623f48a6ed - rustc_driver::driver::phase_3_run_analysis_passes::he578df6b8805151c

  19:     0x7f623f476f69 - rustc_driver::driver::compile_input::h5b63ccd49eeeb98b

  20:     0x7f623f4a02ba - rustc_driver::run_compiler::h98c7274e7cb1d11d

  21:     0x7f623f3d9f0b - std::panicking::try::do_call::h99ed0da044e497c3

  22:     0x7f623f10ee06 - __rust_maybe_catch_panic

  23:     0x7f623f3f8461 - <F as alloc::boxed::FnBox<A>>::call_box::hbdd5a14cd8e33b97

  24:     0x7f623f102de0 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2

  25:     0x7f62373da183 - start_thread

  26:     0x7f623edbe37c - clone

  27:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...

error: Could not compile `net_tests`.

To learn more, run the command again with --verbose.

The command "./mach test-unit" exited with 101.
```

### PR DESCRIPTION
**Pull request by pnkfelix**
Do not intern filemap to entry w/ mismatched length.

Fix #37274 (I think).

Beta-nominated; note that only the second commit needs to be cherry picked to beta branch. (The first just adds some debug instrumentation that I wish had been present.)

### CODE REVIEW

File: src/librustc_metadata/decoder.rs [hunk 1]
```diff
@@ -1193,6 +1207,10 @@ impl<'a, 'tcx> CrateMetadata {
 }
 
 fn are_equal_modulo_startpos(fm1: &syntax_pos::FileMap, fm2: &syntax_pos::FileMap) -> bool {
```
Comment (pnkfelix) [inline src/librustc_metadata/decoder.rs]: (maybe we should move this to a method on `FileMap`, the idea being that future modifications to `FileMap`, such as adding new fields,  would know to update the method accordingly. But that can wait for a future PR; I prefer to keep this one minimal.)

**Comment by SimonSapin** [comment]
Confirming: I’ve managed to build https://github.com/servo/servo/pull/13813 (which is blocked on this ICE) with a rustc from this PR.

**Comment by SimonSapin** [comment]
```
failures:

---- [codegen-units] codegen-units/partitioning/local-inlining.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/test/codegen-units/partitioning/local-inlining.rs -L x86_64-unknown-linux-gnu/test/codegen-units/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-inlining.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-inlining.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/local-inlining
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: Could not create incremental compilation crate directory `tmp/partitioning-tests/local-inlining/local_inlining-4pp8dn3374zr`: No such file or directory (os error 2)

error: aborting due to previous error


------------------------------------------

thread '[codegen-units] codegen-units/partitioning/local-inlining.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/tools/compiletest/src/runtest.rs:2377
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [codegen-units] codegen-units/partitioning/local-inlining.rs

test result: FAILED. 31 passed; 1 failed; 3 ignored; 0 measured

thread 'main' panicked at 'Some tests failed', /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/tools/compiletest/src/main.rs:298
/buildslave/rust-buildbot/slave/auto-linux-64-opt/build/mk/tests.mk:771: recipe for target 'tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-codegen-units.ok' failed
make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-codegen-units.ok] Error 101

**Comment by SimonSapin** [comment]
`make tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-codegen-units.ok` succeeds for me locally, but this might be an intermittent failure.

**Comment by brson** [comment]
Seems like a low-risk backport.

**Comment by nikomatsakis** [comment]
Approving for beta backport: appears to be super low risk.

cc @rust-lang/compiler
