### PR TITLE
fix lexing of comments with many \r

### LINKED ISSUE #62863: compiler nontermination after "error: bare CR not allowed in doc-comment"
```
$ rustc -vV
rustc 1.38.0-nightly (273f42b59 2019-07-21)
binary: rustc
commit-hash: 273f42b5964c29dda2c5a349dd4655529767b07f
commit-date: 2019-07-21
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0


$ echo cyAgaS8vL2cNLyBydW4tcA0vLyBhIHNi | base64 --decode > main.rs

$ rustc main.rs
error: bare CR not allowed in doc-comment
 --> main.rs:1:9
  |
// a sbi///g
  |         ^

error: bare CR not allowed in doc-comment
 --> main.rs:1:12
  |
// a sbi///g
  |           ^
```
... and `rustc` keeps running until I kill it.

This bad behavior did not exist on the previous nightly. I hypothesize that it has to do with #59706 (cc @matklad).

This issue was found with the help of [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc).

This issue has been assigned to @matklad via [this comment](https://github.com/rust-lang/rust/issues/62863#issuecomment-513668719).

### PR DESCRIPTION
**Pull request by matklad**
closes #62863

### CODE REVIEW

File: src/test/ui/parser/several-carriage-returns-in-doc-comment.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// Issue #62863
+// ignore-tidy-cr
+
+/// This doc comment contains three isolated `\r` symbols
```
Comment (eddyb) [inline src/test/ui/parser/several-carriage-returns-in-doc-comment.rs]: Maybe mention in a comment that this might be rendered as `^M`? It looks kinda funny on GitHub.

Comment (matklad) [reply src/test/ui/parser/several-carriage-returns-in-doc-comment.rs]: good call, fixed!
