### PR TITLE
Fix ICE for broken or-pattern in async fn

### LINKED ISSUE #71297: internal compiler error: no entry found for key
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
async fn a(x | s: String) {}
fn main() {}
```

```
$ rustc --edition=2018 main.rs 
error: an or-pattern parameter must be wrapped in parenthesis
 --> main.rs:1:12
  |
1 | async fn a(x | s: String) {}
  |            ^^^^^ help: wrap the pattern in parenthesis: `(x | s)`

error[E0408]: variable `x` is not bound in all patterns
 --> main.rs:1:16
  |
1 | async fn a(x | s: String) {}
  |            -   ^ pattern doesn't bind `x`
  |            |
  |            variable not in all patterns

error[E0408]: variable `s` is not bound in all patterns
 --> main.rs:1:12
  |
1 | async fn a(x | s: String) {}
  |            ^   - variable not in all patterns
  |            |
  |            pattern doesn't bind `s`

thread 'rustc' panicked at 'no entry found for key', src/librustc_mir_build/build/mod.rs:343:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (ce93331e2 2020-04-17) running on x86_64-unknown-linux-gnu

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0408`.
```

### PR DESCRIPTION
**Pull request by matthewjasper**
closes #71297

### CODE REVIEW

File: src/librustc_mir_build/build/matches/mod.rs [hunk 1]
```diff
@@ -578,12 +581,26 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                var,
+                ty,
+                ref subpattern,
+                is_primary,
+                ..
+            } => {
+                if is_primary {
+                    f(self, mutability, name, mode, var, pattern.span, ty, pattern_user_ty.clone());
+                }
                 if let Some(subpattern) = subpattern.as_ref() {
```
Comment (oli-obk) [inline src/librustc_mir_build/build/matches/mod.rs:602]: aren't subpatterns only relevant for the primary, too, as each variable must occur in all variants?

File: src/librustc_mir_build/build/matches/mod.rs [hunk 2]
```diff
@@ -578,12 +581,26 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                mutability,
+                name,
+                mode,
+                var,
+                ty,
+                ref subpattern,
+                is_primary,
+                ..
+            } => {
+                if is_primary {
```
Comment (oli-obk) [inline src/librustc_mir_build/build/matches/mod.rs:599]: instead of adding a `is_primary` field, wouldn't it suffice to check `pattern.id == var` here?

Comment (oli-obk) [reply src/librustc_mir_build/build/matches/mod.rs:599]: oh... :facepalm: this isn't `hir::PatKind`

File: src/librustc_mir_build/build/matches/mod.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir_build/build/matches/mod.rs:602]: The whole point of this PR is that we can't assume that patterns are well formed because the error isn't fatal.
