### PR TITLE
Export `#[inline]` fns with extern indicators

### LINKED ISSUE #72463: `#[inline]` prevents symbol from appearing in `staticlib` output
I currently use Rust to generate a static library for FFI consumption. In some public interfaces, I call other FFI public interfaces as primarily a wrapper with a few tweaks. I'd like to mark these "inner" functions as inline, however, this seems to cause them to not show up in the final staticlib.

Given this drastically simplified example:

```rust
/// lib.rs
#![no_std]

#[no_mangle]
pub extern "C" fn square_plus_one(input: usize) -> usize {
    square(input) + 1
}

#[no_mangle]
#[inline]
pub extern "C" fn square(input: usize) -> usize {
    input * input
}

use core::panic::PanicInfo;

/// This function is called on panic.
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {
        // Prevent loop mis-optimization
        continue;
    }
}
```

```toml
# Cargo.toml
[package]
name = "inline-ffi"
version = "0.2.0"
edition = "2018"
description = ""
license = ""
documentation = ""
homepage = ""
repository = ""

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```

The `square_plus_one` function makes it to the static library, but the `square` function does not:

```text
nm -nSC ./target/release/libinline_ffi.a | rg square
0000000000000000 0000000000000009 T square_plus_one
```

If I remove the `#[inline]` attribute, we see both functions in the static lib:

```text
nm -nSC ./target/release/libinline_ffi.a | rg square
0000000000000000 0000000000000008 T square
0000000000000000 0000000000000009 T square_plus_one
```

The [relevant docs](https://doc.rust-lang.org/reference/attributes/codegen.html#the-inline-attribute) don't seem to hint that `#[inline]` can prevent `#[no_mangle]`/`pub extern "C"` items from surviving all the way to the final library, or that they shouldn't be used together.

I would expect any function marked `pub extern "C"` and/or `#[no_mangle]` should be present in the final artifact, regardless of `#[inline]` attributes.

I see this behavior on `1.43.1` stable, as well as a recent nightly. I don't know if this is a regression, as this is the first time I've run into this.

Thanks!

Edit: Simplified `Cargo.toml` profile settings, they are not needed to reproduce.

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/72463#issuecomment-639441633).

### LINKED ISSUE #72944: Warn if a function is marked as both #[inline] and #[no_mangle]
Code:

```rust
// src/lib.rs
#[inline] #[no_mangle] pub extern "C" fn foo() { }
```
```toml
# Cargo.toml
[package]
name = "foo"
version = "0.0.1"
edition = "2018"

[lib]
name = "foo"
crate-type = ["cdylib"]
```
```sh
cargo build --release
```
If the function is marked as `#[inline]`, it doesn't get compiled into the dll file:
```sh
strings target/release/libfoo.so | grep foo
```

The reason a function may be marked as both `#[inline]` and `#[no_mangle]` is so that it gets inlined when compiling the crate as a rust library, but *not inlined* when compiling the crate as a cdylib.

There should be a warning to use something like `#[cfg_attr(not(crate_type="cdylib"), inline]` instead.

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/72944#issuecomment-639442457).

### PR DESCRIPTION
**Pull request by cofibrant**
In ancient history (#36280) we stopped `#[inline]` fns being codegened if they weren't used. However,

- #72944
- #72463

observe that when writing something like

```rust
#![crate_type = "cdylib"]

#[no_mangle]
#[inline]
pub extern "C" fn foo() {
    // ...
}
```

we really _do_ want `foo` to be codegened. This change makes this the case.

Resolves #72944, resolves #72463 (and maybe some more)

### CODE REVIEW

File: src/librustc_typeck/collect.rs [hunk 1]
```diff
@@ -2634,6 +2636,16 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
     codegen_fn_attrs
 }
 
+fn inline_exportable(tcx: TyCtxt<'_>, def_id: DefId) -> bool {
+    // Functions marked with #[inline] are only ever codegened
+    // with "internal" linkage and are never exported unless we're
+    // building a `staticlib` or `cdylib` and they are marked
+    // `#[no_mangle]`.
+    tcx.codegen_fn_attrs(def_id).flags.contains(CodegenFnAttrFlags::NO_MANGLE)
```
Comment (ollie27) [inline src/librustc_typeck/collect.rs:2644]: There is also `#[export_name = "..."]` and `#[linkage = "..."]` to consider so this should really be calling [`contains_extern_indicator`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/middle/codegen_fn_attrs/struct.CodegenFnAttrs.html#method.contains_extern_indicator).

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -2634,6 +2636,16 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
...
+        && (tcx.sess.crate_types().contains(&CrateType::Cdylib)
+            || tcx.sess.crate_types().contains(&CrateType::Staticlib))
```
Comment (ollie27) [inline src/librustc_typeck/collect.rs:2646]: Do we need to check the crate type here? Even when building `rlib`s we'll still need to codegen and export `#[no_mangle] #[inline]` items in case they're linked into a `staticlib` or `cdylib`.

File: src/librustc_typeck/collect.rs (hunk 1 above)
Comment (doctorn) [reply src/librustc_typeck/collect.rs:2644]: I wasn't aware of `contains_extern_indicator`, thank you so much for the suggestion!

File: src/librustc_typeck/collect.rs (hunk 2 above)
Comment (doctorn) [reply src/librustc_typeck/collect.rs:2646]: Just to check I understand between these two you're saying that `#[inline]` should always be superseded by an extern indicator and crate-type/specifics of indicator are irrelevant?

Comment (Amanieu) [reply src/librustc_typeck/collect.rs:2646]: Yes, this should be done regardless of the output crate type.

File: src/librustc_middle/mir/mono.rs [hunk 3]
```diff
@@ -102,8 +103,12 @@ impl<'tcx> MonoItem<'tcx> {
...
-                // be creating a local copy per CGU
-                if generate_cgu_internal_copies {
+                // be creating a local copy per CGU. We need to watch out here
+                // for an extern indicator as we don't want to optimise away
+                // inlined functions that should be exported.
+                if generate_cgu_internal_copies
+                    && !tcx.codegen_fn_attrs(instance.def_id()).contains_extern_indicator()
+                {
                     return InstantiationMode::LocalCopy;
                 }
```
[the remark this answers is not in the document]
Comment (doctorn) [reply src/librustc_middle/mir/mono.rs:113]: Ah! That's a good catch - I'll update and add some tests to cover. Thanks a lot!

[the remark this answers is not in the document]
Comment (doctorn) [reply src/librustc_middle/mir/mono.rs:108]: Should be sorted!

**Comment by Aaron1011** [comment]
@bors r-

Failed in https://github.com/rust-lang/rust/pull/73240#issuecomment-642798437: The function `random_inline` in test `codegen/sanitizer-no-sanitize-inlining.rs` no longer gets the `fastcc` calling convention assigned by LLVM, since it is now visible outside of the module.

**Comment by Dylan-DPC** [comment]
failed in [rollup log](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31719&view=results)

@bors r-

**Comment by doctorn** [comment]
> @bors r-
> 
> Failed in [#73240 (comment)](https://github.com/rust-lang/rust/pull/73240#issuecomment-642798437): The function `random_inline` in test `codegen/sanitizer-no-sanitize-inlining.rs` no longer gets the `fastcc` calling convention assigned by LLVM, since it is now visible outside of the module.

I can't reproduce this locally, is this an architecture specific failure?

**Comment by mati865** [comment]
@doctorn do you have sanitizers enabled? https://github.com/rust-lang/rust/blob/ce6d3a73b514e9649e57cee812ad129bb2112016/config.toml.example#L210

**Comment by doctorn** [comment]
@matl865 that'll do it :sweat_smile:

**Comment by doctorn** [comment]
So looking into this, `random_inline` only needs to be `no_mangle` so that it can be mentioned in the test, can we have a private `#[no_export]` attribute to deal with this kind of case?

**Comment by doctorn** [comment]
I've update the sanitizer test so that it doesn't depend on the `#[inline]` symbol meaning that it's ok to mangle it

File: src/test/codegen/sanitizer-no-sanitize-inlining.rs [hunk 4]
```diff
@@ -13,7 +13,7 @@
 #![feature(no_sanitize)]
 
 // ASAN-LABEL: define void @test
-// ASAN:         tail call fastcc void @random_inline
+// ASAN:         tail call fastcc
```
Comment (tmiasko) [inline src/test/codegen/sanitizer-no-sanitize-inlining.rs:16]: The name is relevant insofar it prevents unintentionally matching on a
different call, especially that `-Zsanitizer=address` does insert calls to
`@__asan_init` and `@__asan_version_mismatch_check_v8`.

As mentioned earlier, the issue is that check unnecessarily looks for fastcc
which is no longer there. I would relax the pattern and retain the no_mangle:

```
// ASAN:         call {{.*}} @random_inline
```

Comment (doctorn) [reply src/test/codegen/sanitizer-no-sanitize-inlining.rs:16]: Good point - thanks a lot
