### PR TITLE
Fix overflow when converting ZST Vec to VecDeque

### LINKED ISSUE #78532: VecDeque from Vec fails with ZST
This code panics under Miri, and also when I compile to WASM, though not when running normally.

```rust
use std::collections::VecDeque;

fn main() {
    let _: VecDeque<()> = vec![()].into();
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d709dae58894f45e7c866df3f98bac60)

```text
thread 'main' panicked at 'attempt to add with overflow', /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/collections/vec_deque.rs:3236:36
```

The overflow is here: https://github.com/rust-lang/rust/blob/a53fb30e3bf2655b0563da6d561c23cda5f3ec11/library/alloc/src/collections/vec_deque.rs#L3236

### PR DESCRIPTION
**Pull request by Stupremee**
```rust
let v = vec![(); 100];
let queue = VecDeque::from(v);
println!("{:?}", queue);
```
This code will currently panic with a capacity overflow.
This PR resolves this issue and makes the code run fine.

Resolves #78532

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 1]
```diff
@@ -2793,8 +2793,12 @@ impl<T> From<Vec<T>> for VecDeque<T> {
             let len = other.len();
 
             // We need to extend the buf if it's not a power of two, too small
-            // or doesn't have at least one free space
-            if !buf.capacity().is_power_of_two()
+            // or doesn't have at least one free space.
+            // We check if `T` is a ZST in the first condition,
+            // because `usize::MAX` (the capacity returned by `capacity()` for ZST)
+            // is not a power of zero and thus it'll always try
```
Comment (the8472) [inline library/alloc/src/collections/vec_deque/mod.rs:2799]: power of zero? 🤔

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by Stupremee** [comment]
I don't know why the build failed but I think it has nothing to do with my PR?

**Comment by dtolnay** [comment]
The i686-msvc-1 job failed with:

```console
error: linking with `link.exe` failed: exit code: 1201
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.0.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.1.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.2.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.3.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.4.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.5.rcgu.o" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.main.7rcbfp3g-cgu.6.rcgu.o" "/OUT:D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.exe" "D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags\\main.4s37gsrti678ik8u.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:D:/a/rust/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/override-aliased-flags/override-aliased-flags" "/LIBPATH:D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-2deb73d3b5fa87cf.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-15c6a7fdf91ef35a.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-e074a35b22c4b5d2.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-6c3c9ebd17ae006e.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-13e844b011774ae1.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-a91a7398553297ff.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-35a0f6d337703982.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-fe3cebfa1c67a4da.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-db1c1d00bd877cb8.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-99335de001fe3f12.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-c8fa98e615898128.rlib" "D:\\a\\rust\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-38e39f9411889523.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1201: error writing to program database 'D:\a\rust\rust\build\i686-pc-windows-msvc\test\run-make-fulldeps\override-aliased-flags\override-aliased-flags\main.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
```

@bors retry

File: library/alloc/src/collections/vec_deque/mod.rs [hunk 2]
```diff
@@ -2793,8 +2793,12 @@ impl<T> From<Vec<T>> for VecDeque<T> {
...
 
             // We need to extend the buf if it's not a power of two, too small
-            // or doesn't have at least one free space
-            if !buf.capacity().is_power_of_two()
+            // or doesn't have at least one free space.
+            // We check if `T` is a ZST in the first condition,
+            // because `usize::MAX` (the capacity returned by `capacity()` for ZST)
+            // is not a power of two and thus it'll always try
+            // to reserve more memory which will panic for ZST (rust-lang/rust#78532)
+            if (!buf.capacity().is_power_of_two() && mem::size_of::<T>() != 0)
```
Comment (tmiasko) [inline library/alloc/src/collections/vec_deque/mod.rs:2801]: Maximum len of ZST Vec is larger than maximum len of ZST VecDeque (MAXIMUM_ZST_CAPACITY - 1), which would be another thing to check before constructing VecDeque.

Comment (Stupremee) [reply library/alloc/src/collections/vec_deque/mod.rs:2801]: I'm not sure if this should be changed in this PR, but it's definitely a check that should be added I think.

Comment (tmiasko) [reply library/alloc/src/collections/vec_deque/mod.rs:2801]: Fair. I mentioned it here, because it wasn't an issue so far, but will be as a result of changes in this PR.

Comment (Stupremee) [reply library/alloc/src/collections/vec_deque/mod.rs:2801]: You can just open a new issue👍

Comment (lcnr) [reply library/alloc/src/collections/vec_deque/mod.rs:2801]: We now create a `VecDeque` with a capacity which is not a power of two here, breaking one of its invariants.

This is either unsound or that invariant isn't actually required anywhere and we should remove it.
