### PR TITLE
Report the `unsafe_attr_outside_unsafe` lint at the closest node

### LINKED ISSUE #140602: Can't allow `unsafe_attr_outside_unsafe` in Rust 2015-2021
I tried this code in Rust 2021 ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2edb7707d806afe22cbc68a52c4fc258)):

```rust
#![deny(unsafe_attr_outside_unsafe)]

#[allow(unsafe_attr_outside_unsafe)]
mod generated {
    #[no_mangle]
    fn _generated_foo() {}
}
```

I expected to see this happen: compiles successfully

Instead, this happened:
```
error: unsafe attribute used without unsafe
 --> src/lib.rs:5:7
  |
5 |     #[no_mangle]
  |       ^^^^^^^^^ usage of unsafe attribute
  |
  = warning: this is accepted in the current edition (Rust 2021) but is a hard error in Rust 2024!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/unsafe-attributes.html>
note: the lint level is defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(unsafe_attr_outside_unsafe)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: wrap the attribute in `unsafe(...)`
  |
5 |     #[unsafe(no_mangle)]
  |       +++++++         +
```

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: x86_64-unknown-linux-gnu
release: 1.85.0
LLVM version: 19.1.7

```

Reproduces in `1.88.0-nightly (2025-05-01 3350c1eb3fd8fe1bee1e)` on the Playground.

### PR DESCRIPTION
**Pull request by Urgau**
This PR have `AstValidation` track a linting node id and then uses it when reporting the `unsafe_attr_outside_unsafe` lint, so that instead of being bound at the crate-root, `#[allow]` of the lint works at any node.

Fixes rust-lang/rust#140602
r? @jieyouxu

### CODE REVIEW

File: tests/ui/rust-2024/unsafe-attributes/unsafe-attributes-allow.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+//@ check-pass
+//
+// https://github.com/rust-lang/rust/issues/140602
```
Comment (jieyouxu) [inline tests/ui/rust-2024/unsafe-attributes/unsafe-attributes-allow.rs:3]: Suggestion: can you explicitly write an edition e.g. `//@ edition: 2015`, and slightly elaborate here that this test is a regression test for

> Can't allow `unsafe_attr_outside_unsafe` in pre-2024 edition

**Review by jieyouxu — APPROVED** [review]
Thanks! One nit, but r=me otherwise

**Comment by jieyouxu** [comment]
Don't know if we want to backport this to beta, it's in stable ever since this lint was implemented I think

File: tests/ui/rust-2024/unsafe-attributes/unsafe-attributes-allow.rs (hunk 1 above)
Comment (Urgau) [reply tests/ui/rust-2024/unsafe-attributes/unsafe-attributes-allow.rs]: Went with the 2021 edition, and added a small explanation for the anti-regression test.

**Comment by jieyouxu** [comment]
I'll nominate this for beta-backport discussion at least.

---

This PR fixes a bug reported in #140602, where it wasn't possible to `#[allow(unsafe_attr_outside_unsafe)]` in scopes *within* crate root, e.g. the following will error and not compile

```rs
#![deny(unsafe_attr_outside_unsafe)]

#[allow(unsafe_attr_outside_unsafe)]
mod generated {
    #[no_mangle]
    fn _generated_foo() {}
}
```

This was broken since the `unsafe_attr_outside_unsafe` lint was introduced (also present on stable).

@rustbot label: +beta-nominated

**Comment by jieyouxu** [comment]
This was discussed in today's [compiler triage meeting]. We considered the **beta backport** nomination but decided to **decline** this beta backport.

The beta backport was considered but rejected because:

- It's very late into the release cycle.
- It has been broken ever since the lint was stabilized, but we only received one bug report.

[compiler triage meeting]: https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-05-08/near/516905943

@rustbot label: -beta-nominated
