### PR TITLE
rustbuild: print out env vars on verbose rustc invocations

### LINKED ISSUE #38686: rustbuild `--verbose` switch is missing env var info
When I run `time python /Users/fklock/Dev/Mozilla/rust.git/x.py build --stage 1`, in an error condition like `` error: Could not compile `core` ``, I see the subsequent suggestion: `To learn more, run the command again with --verbose.`

When I run with `--verbose`, I do see helpful output with the build commands it executes. In particular, I see `rustc` invocations that I would like to run myself, with `RUST_BACKTRACE=1` turned on.

Unfortunately:

```
 /Users/fklock/Dev/Mozilla/rust.git/objdir-dbgopt/build/bootstrap/debug/rustc /Users/fklock/Dev/Mozilla/rust.git/src/libcore/lib.rs --crate-name core --crate-type lib -C opt-level=2 -C metadata=7824b4c14b4ca3e8 -C extra-filename=-7824b4c14b4ca3e8 --out-dir /Users/fklock/Dev/Mozilla/rust.git/objdir-dbgopt/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps --emit=dep-info,link --target x86_64-apple-darwin -L dependency=/Users/fklock/Dev/Mozilla/rust.git/objdir-dbgopt/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps
thread 'main' panicked at 'RUSTC_STAGE was not set: NotPresent', ../src/libcore/result.rs:837
```

i.e., the environment variable `RUSTC_STAGE` needs to be set. After I set that, I get:

```
thread 'main' panicked at 'RUSTC_SYSROOT was not set', ../src/libcore/option.rs:705
```

and I start to wonder: "How many of these environment variables are there? Am I going to have to deduce the values for all of them? Why doesn't the `--verbose` flag either include them in the command invocation output (to make it trivial to cut-and-paste the desired command), or at least include them somewhere in the output so that I can grep for them?"

### PR DESCRIPTION
**Pull request by pnkfelix**
Print out environment variables related to Rust on sufficiently verbose rustc invocations.

Output is filtered via heuristic of only printing environment variables whose keys start with "RUST" or "CARGO." This filtering is mostly motivated by my not caring to see e.g. "PATH" in my own output, though it is also motivated as a way to try to avoid printing out personal secrets like github keys that people might have stored in their environments for better or for worse, especially since build output is often pasted into bug reports or gists.

Fix #38686.

<details>

<summary>Click here to see sample output</summary>

Sample output looks like:

```
...
      Fresh core v0.0.0 (/home/pnkfelix/Dev/Rust/rust.git/library/core)
rustc env[0]: "CARGO"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/bin/cargo"
rustc env[1]: "CARGO_CRATE_NAME"="core"
rustc env[2]: "CARGO_INCREMENTAL"="0"
rustc env[3]: "CARGO_MAKEFLAGS"="--jobserver-fds=5,6 -j --jobserver-auth=5,6 -j"
rustc env[4]: "CARGO_MANIFEST_DIR"="/home/pnkfelix/Dev/Rust/rust.git/library/core"
rustc env[5]: "CARGO_PKG_AUTHORS"="The Rust Project Developers"
rustc env[6]: "CARGO_PKG_DESCRIPTION"=""
rustc env[7]: "CARGO_PKG_HOMEPAGE"=""
rustc env[8]: "CARGO_PKG_LICENSE"=""
rustc env[9]: "CARGO_PKG_LICENSE_FILE"=""
rustc env[10]: "CARGO_PKG_NAME"="core"
rustc env[11]: "CARGO_PKG_REPOSITORY"=""
rustc env[12]: "CARGO_PKG_VERSION"="0.0.0"
rustc env[13]: "CARGO_PKG_VERSION_MAJOR"="0"
rustc env[14]: "CARGO_PKG_VERSION_MINOR"="0"
rustc env[15]: "CARGO_PKG_VERSION_PATCH"="0"
rustc env[16]: "CARGO_PKG_VERSION_PRE"=""
rustc env[17]: "CARGO_PROFILE_RELEASE_CODEGEN_UNITS"="256"
rustc env[18]: "CARGO_PROFILE_RELEASE_DEBUG"="0"
rustc env[19]: "CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS"="false"
rustc env[20]: "CARGO_TARGET_DIR"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0-std"
rustc env[21]: "RUSTBUILD_NATIVE_DIR"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/native"
rustc env[22]: "RUSTC"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/bootstrap/debug/rustc"
rustc env[23]: "RUSTC_BOOTSTRAP"="1"
rustc env[24]: "RUSTC_BREAK_ON_ICE"="1"
rustc env[25]: "RUSTC_ERROR_METADATA_DST"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/tmp/extended-error-metadata"
rustc env[26]: "RUSTC_FORCE_UNSTABLE"="1"
rustc env[27]: "RUSTC_INSTALL_BINDIR"="bin"
rustc env[28]: "RUSTC_LIBDIR"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/lib"
rustc env[29]: "RUSTC_LINT_FLAGS"="-Wrust_2018_idioms -Wunused_lifetimes -Dwarnings"
rustc env[30]: "RUSTC_PRINT_STEP_TIMINGS"="1"
rustc env[31]: "RUSTC_REAL"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/bin/rustc"
rustc env[32]: "RUSTC_SNAPSHOT"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/bin/rustc"
rustc env[33]: "RUSTC_SNAPSHOT_LIBDIR"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/lib"
rustc env[34]: "RUSTC_STAGE"="0"
rustc env[35]: "RUSTC_SYSROOT"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0-sysroot"
rustc env[36]: "RUSTC_VERBOSE"="2"
rustc env[37]: "RUSTDOC"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/bootstrap/debug/rustdoc"
rustc env[38]: "RUSTDOCFLAGS"="--cfg=bootstrap -Dwarnings -Winvalid_codeblock_attributes --crate-version 1.52.0-dev"
rustc env[39]: "RUSTDOC_REAL"="/path/to/nowhere/rustdoc/not/required"
rustc env[40]: "RUSTFLAGS"="--cfg=bootstrap -Zmacro-backtrace -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Cprefer-dynamic"
rustc env[41]: "RUST_COMPILER_RT_ROOT"="/home/pnkfelix/Dev/Rust/rust.git/src/llvm-project/compiler-rt"
rustc env[42]: "RUST_TEST_THREADS"="128"
rustc working directory: /home/pnkfelix/Dev/Rust/rust.git
rustc command: "LD_LIBRARY_PATH"="/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/lib:/home/pnkfelix/Dev/Rust/rust.git/objdi\
r-default/build/x86_64-unknown-linux-gnu/stage0-std/release/deps:/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/lib" "/home\
/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" "--crate-name" "core" "--edition=2018" "library/core/src/lib.rs" "--er\
ror-format=json" "--json=diagnostic-rendered-ansi,artifacts" "--crate-type" "lib" "--emit=dep-info,metadata,link" "-C" "opt-level=3" "-C" "embed-bitcode=no" "-C" \
"codegen-units=256" "-C" "debuginfo=0" "-C" "metadata=6748933694d8be19" "-C" "extra-filename=-6748933694d8be19" "--out-dir" "/home/pnkfelix/Dev/Rust/rust.git/objd\
ir-default/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps" "--target" "x86_64-unknown-linux-gnu" "-L" "dependency=/home/pnkfelix/\
Dev/Rust/rust.git/objdir-default/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/home/pnkfelix/Dev/Rust/rust.gi\
t/objdir-default/build/x86_64-unknown-linux-gnu/stage0-std/release/deps" "--cfg=bootstrap" "-Zmacro-backtrace" "-Clink-args=-Wl,-rpath,$ORIGIN/../lib" "-Cprefer-d\
ynamic" "-Z" "binary-dep-depinfo" "-Wrust_2018_idioms" "-Wunused_lifetimes" "-Dwarnings" "--sysroot" "/home/pnkfelix/Dev/Rust/rust.git/objdir-default/build/x86_64\
-unknown-linux-gnu/stage0-sysroot" "-Z" "force-unstable-if-unmarked"
...
```

### CODE REVIEW

**Comment by jyn514** [comment]
Can you double check that this allows running the rustc command x.py prints without getting "variable not set" errors?

**Comment by pnkfelix** [comment]
@jyn514 it won't work out of the box, the output isn't parsable by a shell script in the manner it is currently printed.

Do you just mean "double-check that this is a sufficiently large set of environment variables for a typical case" ? I can do that, I'm actually in the midst of doing it now, in fact. :)

**Comment by pnkfelix** [comment]
(also, if people *want* the output to be parsable by a shell script, I can do that too. I was following existing precedent for how the "DYLD_LIBRARY_PATH" key is printed currently (namely, with double-quotes around it), but I would be happy to revise that printing as part of this work so that the key is printed without surrounding double-quotes.)

File: src/bootstrap/bin/rustc.rs [hunk 1]
```diff
@@ -139,6 +139,12 @@ fn main() {
     }
 
     if verbose > 1 {
+        let rust_env_vars =
+            env::vars().filter(|(k, _)| k.starts_with("RUST") || k.starts_with("CARGO"));
```
Comment (Mark-Simulacrum) [inline src/bootstrap/bin/rustc.rs:143]: FWIW there's no guarantee that we set them prefixed with RUST or CARGO, though we probably should - it may be worth doing some grep through bootstrap and fixing things up in a separate PR (or commit in this one).

Comment (pnkfelix) [reply src/bootstrap/bin/rustc.rs:143]: hmm.

Are you asking for a future PR that tries to correct any cases we can find of a non-prefixed environment variable?

Or are you asking for something that *enforces* a rule that we do not use environment variables without a `RUST` or `CARGO` prefix ? (Apart from cases like `PATH` ... or perhaps `SHELL` ...)

Comment (jyn514) [reply src/bootstrap/bin/rustc.rs:143]: There's quite a bit being set without RUST or CARGO prefixes, mostly starting with CFG_.

<details>

```
$ rg '\.env\("' | grep -v RUST | grep -v CARGO
util.rs:            cmd.env("TERM", "xterm").args(&["--color", "always"]);
dist.rs:    cmd.env("CFG_RELEASE_INFO", builder.rust_version())
dist.rs:        .env("CFG_RELEASE_NUM", &builder.version)
dist.rs:        .env("CFG_RELEASE", builder.rust_release())
dist.rs:        .env("CFG_VER_MAJOR", parts.next().unwrap())
dist.rs:        .env("CFG_VER_MINOR", parts.next().unwrap())
dist.rs:        .env("CFG_VER_PATCH", parts.next().unwrap())
dist.rs:        .env("CFG_VER_BUILD", "0") // just needed to build
dist.rs:        .env("CFG_PACKAGE_VERS", builder.rust_package_vers())
dist.rs:        .env("CFG_PACKAGE_NAME", pkgname(builder, "rust"))
dist.rs:        .env("CFG_BUILD", target.triple)
dist.rs:        .env("CFG_CHANNEL", &builder.config.channel);
dist.rs:        cmd.env("CFG_MINGW", "1").env("CFG_ABI", "GNU");
dist.rs:        cmd.env("CFG_MINGW", "0").env("CFG_ABI", "MSVC");
dist.rs:        cmd.env("CFG_PLATFORM", "x64");
dist.rs:        cmd.env("CFG_PLATFORM", "x86");
builder.rs:            .env("CFG_RELEASE_CHANNEL", &self.config.channel)
builder.rs:        cargo.env("REAL_LIBRARY_PATH_VAR", &util::dylib_path_var());
builder.rs:            cargo.env("REAL_LIBRARY_PATH", e);
builder.rs:            cargo.env("UPDATE_EXPECT", "1");
builder.rs:                cargo.env("CC", cl).env("CXX", cl);
builder.rs:        cargo.env("CFG_COMPILER_HOST_TRIPLE", target.triple);
builder.rs:        cargo.env("CFG_RELEASE_CHANNEL", &self.config.channel);
builder.rs:            cargo.env("WINAPI_NO_BUNDLED_LIBRARIES", "1");
test.rs:        cargo.env("CFG_DISABLE_CROSS_TESTS", "1");
test.rs:        cargo.env("PATH", &path_for_cargo(builder, compiler));
test.rs:            cargo.env("MIRI", &miri);
test.rs:            cargo.env("XARGO_CHECK", builder.out.join("bin").join("xargo-check"));
test.rs:            cargo.env("MIRI_SYSROOT", miri_sysroot);
test.rs:            cargo.env("MIRI", miri);
test.rs:        cargo.env("SYSROOT", builder.sysroot(compiler));
test.rs:        cargo.env("HOST_LIBS", host_libs);
test.rs:        cargo.env("TARGET_LIBS", target_libs);
test.rs:        cargo.env("CLIPPY_DRIVER_PATH", clippy);
test.rs:            .env("CFG_RELEASE_CHANNEL", &builder.config.channel)
test.rs:                    cmd.env("PATH", new_path);
test.rs:        rustbook_cmd.env("PATH", new_path).arg("test").arg(path);
test.rs:            .env("BOOTSTRAP_OUTPUT_DIRECTORY", &builder.config.out)
tool.rs:            cargo.env("LIBZ_SYS_STATIC", "1");
tool.rs:    cargo.env("LZMA_API_STATIC", "1");
tool.rs:    cargo.env("CFG_RELEASE", builder.rust_release());
tool.rs:    cargo.env("CFG_RELEASE_CHANNEL", &builder.config.channel);
tool.rs:    cargo.env("CFG_VERSION", builder.rust_version());
tool.rs:    cargo.env("CFG_RELEASE_NUM", &builder.version);
tool.rs:        cargo.env("CFG_COMMIT_HASH", sha);
tool.rs:        cargo.env("CFG_SHORT_COMMIT_HASH", sha_short);
tool.rs:        cargo.env("CFG_COMMIT_DATE", date);
native.rs:    cfg.env("DESTDIR", "");
native.rs:        cfg.env("SCCACHE_PATH", builder.config.ccache.as_ref().unwrap())
native.rs:            .env("SCCACHE_TARGET", target.triple)
native.rs:            .env("SCCACHE_CC", &cc)
native.rs:            .env("SCCACHE_CXX", &cxx);
native.rs:            cfg.env("SCCACHE_EXTRA_ARGS", "-m32");
native.rs:            .env("LLVM_CONFIG_REAL", &llvm_config)
native.rs:            cfg.env("LLVM_CONFIG_SHIM_REPLACE", &builder.config.build.triple)
native.rs:                .env("LLVM_CONFIG_SHIM_REPLACE_WITH", &target.triple)
compile.rs:        cargo.env("MACOSX_DEPLOYMENT_TARGET", target);
compile.rs:        .env("CFG_RELEASE", builder.rust_release())
compile.rs:        .env("CFG_RELEASE_CHANNEL", &builder.config.channel)
compile.rs:        .env("CFG_VERSION", builder.rust_version())
compile.rs:        .env("CFG_PREFIX", builder.config.prefix.clone().unwrap_or_default());
compile.rs:    cargo.env("CFG_LIBDIR_RELATIVE", libdir_relative);
compile.rs:        cargo.env("CFG_VER_DATE", ver_date);
compile.rs:        cargo.env("CFG_VER_HASH", ver_hash);
compile.rs:        cargo.env("CFG_DISABLE_UNSTABLE_FEATURES", "1");
compile.rs:        cargo.env("CFG_DEFAULT_LINKER", s);
compile.rs:        cargo.env("LLVM_CONFIG", &llvm_config);
compile.rs:            cargo.env("CFG_LLVM_ROOT", s);
compile.rs:            cargo.env("LLVM_LINKER_FLAGS", s);
compile.rs:            cargo.env("LLVM_STATIC_STDCPP", file);
compile.rs:            cargo.env("LLVM_LINK_SHARED", "1");
compile.rs:            cargo.env("LLVM_USE_LIBCXX", "1");
compile.rs:            cargo.env("LLVM_NDEBUG", "1");
```

</details>

**Comment by jyn514** [comment]
> Do you just mean "double-check that this is a sufficiently large set of environment variables for a typical case" ? I can do that, I'm actually in the midst of doing it now, in fact. :)

Yes, that's what I meant :)

File: src/bootstrap/bin/rustc.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/bin/rustc.rs:143]: I think enforcing isn't necessary (and would be painful) but checking rustbuild for it, and perhaps adding a tidy lint that e.g. `env("` in src/bootstrap is always followed by a RUST or CARGO prefix might make sense (we'd opt out when we need to set platform specific variables like ld library path, or maybe allow them explicitly in tidy).

**Comment by pnkfelix** [comment]
> > Do you just mean "double-check that this is a sufficiently large set of environment variables for a typical case" ? I can do that, I'm actually in the midst of doing it now, in fact. :)
> 
> Yes, that's what I meant :)

Okay. It seemed to work for me, and I didn't include any of the `CFG` nor `CARGO` variables in my invocation.

**Comment by camelid** [comment]
@pnkfelix I updated the PR description from

> Fix issue #38686

to

> Fix #38686

so GitHub will close the issue on PR merge. Letting you know in case you intended to leave the issue open.

**Comment by Mark-Simulacrum** [comment]
Since this worked for you locally, I'm going to go ahead and r+, since it seems like a strict improvement to me. We can continue to iterate (e.g., moving more variables over to a RUST_ prefix) over time if necessary.

Thanks!

@bors r+ rollup
