### PR TITLE
parser: not insert dummy field in struct

### LINKED ISSUE #114636: ICE: `None` when deriving `Debug` of struct containing `unreachable!()`
### Code

```Rust
#[derive(Debug)]
pub struct Lazy {
    unreachable!()
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (03a119b0b 2023-08-07)
binary: rustc
commit-hash: 03a119b0b0e310d22d94399b24ed030056050f13
commit-date: 2023-08-07
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error: unexpected token: `!`
 --> treereduce.out:3:16
  |
3 |     unreachable!()
  |                ^ unexpected token after this
  |
  = note: macros cannot expand to struct fields
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_builtin_macros/src/deriving/debug.rs:114:63:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f2adf96441c - std::backtrace_rs::backtrace::libunwind::trace::hae002a1235f5943b
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2adf96441c - std::backtrace_rs::backtrace::trace_unsynchronized::h5c6bd4f7426dfc23
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2adf96441c - std::sys_common::backtrace::_print_fmt::h5d3e21cf396f0686
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f2adf96441c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4df6398b8c79682d
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2adf9c991c - core::fmt::rt::Argument::fmt::he622d38b82b28b38
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/core/src/fmt/rt.rs:138:9
   5:     0x7f2adf9c991c - core::fmt::write::h766f202e494d1c46
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f2adf956dee - std::io::Write::write_fmt::h4acbb73e5adc92cf
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/io/mod.rs:1714:15
   7:     0x7f2adf964204 - std::sys_common::backtrace::_print::hb0b7b4c1fd1959e0
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2adf964204 - std::sys_common::backtrace::print::hb16047524a0efcb6
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2adf9672fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::hbfc807576ec72365
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/panicking.rs:278:22
  10:     0x7f2adf966fe7 - std::panicking::panic_hook_with_disk_dump::h90afe991ab863313
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/panicking.rs:312:9
  11:     0x7f2ae2b45369 - <rustc_driver_impl[da10067d57af8d1d]::install_ice_hook::{closure#0} as core[708e8bb138b9c609]::ops::function::FnOnce<(&core[708e8bb138b9c609]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f2adf967ba0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h33b0dab6d17bb58f
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/alloc/src/boxed.rs:2021:9
  13:     0x7f2adf967ba0 - std::panicking::rust_panic_with_hook::hb42f613f3941ffdf
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/panicking.rs:733:13
  14:     0x7f2adf9678e1 - std::panicking::begin_panic_handler::{{closure}}::hd271dbc42f32a15e
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/panicking.rs:619:13
  15:     0x7f2adf964946 - std::sys_common::backtrace::__rust_end_short_backtrace::h89f31826ebe8fc58
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f2adf967672 - rust_begin_unwind
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/panicking.rs:617:5
  17:     0x7f2adf9c5d23 - core::panicking::panic_fmt::h78ec2879fa0b4e5b
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/core/src/panicking.rs:67:14
  18:     0x7f2adf9c5db3 - core::panicking::panic::h3c0f5f829255f8a2
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/core/src/panicking.rs:117:5
  19:     0x7f2ae1f6fa50 - rustc_builtin_macros[e6a957b1f71a82b9]::deriving::debug::expand_deriving_debug::{closure#0}
  20:     0x7f2ae1f5e1cb - <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::MethodDef>::expand_struct_method_body
  21:     0x7f2ae1f5de43 - <core[708e8bb138b9c609]::iter::adapters::map::Map<core[708e8bb138b9c609]::slice::iter::Iter<rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::MethodDef>, <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::TraitDef>::expand_struct_def::{closure#1}> as core[708e8bb138b9c609]::iter::traits::iterator::Iterator>::fold::<(), core[708e8bb138b9c609]::iter::traits::iterator::Iterator::for_each::call<rustc_ast[8d85310b5d27e92d]::ptr::P<rustc_ast[8d85310b5d27e92d]::ast::Item<rustc_ast[8d85310b5d27e92d]::ast::AssocItemKind>>, <alloc[f6d94832d5e777bc]::vec::Vec<rustc_ast[8d85310b5d27e92d]::ptr::P<rustc_ast[8d85310b5d27e92d]::ast::Item<rustc_ast[8d85310b5d27e92d]::ast::AssocItemKind>>>>::extend_trusted<core[708e8bb138b9c609]::iter::adapters::map::Map<core[708e8bb138b9c609]::slice::iter::Iter<rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::MethodDef>, <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::TraitDef>::expand_struct_def::{closure#1}>>::{closure#0}>::{closure#0}>
  22:     0x7f2ae1f5d678 - <alloc[f6d94832d5e777bc]::vec::Vec<rustc_ast[8d85310b5d27e92d]::ptr::P<rustc_ast[8d85310b5d27e92d]::ast::Item<rustc_ast[8d85310b5d27e92d]::ast::AssocItemKind>>> as alloc[f6d94832d5e777bc]::vec::spec_from_iter::SpecFromIter<rustc_ast[8d85310b5d27e92d]::ptr::P<rustc_ast[8d85310b5d27e92d]::ast::Item<rustc_ast[8d85310b5d27e92d]::ast::AssocItemKind>>, core[708e8bb138b9c609]::iter::adapters::map::Map<core[708e8bb138b9c609]::slice::iter::Iter<rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::MethodDef>, <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::TraitDef>::expand_struct_def::{closure#1}>>>::from_iter
  23:     0x7f2ae1f5d4d7 - <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::TraitDef>::expand_struct_def
  24:     0x7f2ae1f58f60 - <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::generic::TraitDef>::expand_ext
  25:     0x7f2ae23a6f3c - rustc_builtin_macros[e6a957b1f71a82b9]::deriving::debug::expand_deriving_debug
  26:     0x7f2ae23a7dc7 - <rustc_builtin_macros[e6a957b1f71a82b9]::deriving::BuiltinDerive as rustc_expand[2ff8e59ac252b7df]::base::MultiItemModifier>::expand
  27:     0x7f2ae1cb0310 - <rustc_expand[2ff8e59ac252b7df]::expand::MacroExpander>::fully_expand_fragment
  28:     0x7f2ae1c67567 - <rustc_expand[2ff8e59ac252b7df]::expand::MacroExpander>::expand_crate
  29:     0x7f2ae1c6683a - <rustc_session[a82e8cd710bc7107]::session::Session>::time::<rustc_ast[8d85310b5d27e92d]::ast::Crate, rustc_interface[a1e77c0e0a807641]::passes::configure_and_expand::{closure#1}>
  30:     0x7f2ae1c62003 - rustc_interface[a1e77c0e0a807641]::passes::resolver_for_lowering
  31:     0x7f2ae206000a - rustc_query_impl[d1ef721d40105293]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d1ef721d40105293]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4f696632061e1cd0]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7f2ae205fff9 - <rustc_query_impl[d1ef721d40105293]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[708e8bb138b9c609]::ops::function::FnOnce<(rustc_middle[4f696632061e1cd0]::ty::context::TyCtxt, ())>>::call_once
  33:     0x7f2ae1fce2bc - rustc_query_system[f2faba017c73cca]::query::plumbing::try_execute_query::<rustc_query_impl[d1ef721d40105293]::DynamicConfig<rustc_query_system[f2faba017c73cca]::query::caches::SingleCache<rustc_middle[4f696632061e1cd0]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d1ef721d40105293]::plumbing::QueryCtxt, false>
  34:     0x7f2ae24c4775 - rustc_query_impl[d1ef721d40105293]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f2ae21c84a5 - <rustc_middle[4f696632061e1cd0]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[da10067d57af8d1d]::run_compiler::{closure#1}::{closure#2}::{closure#4}, &rustc_data_structures[7ee79dbb60cc3bb8]::steal::Steal<(rustc_middle[4f696632061e1cd0]::ty::ResolverAstLowering, alloc[f6d94832d5e777bc]::rc::Rc<rustc_ast[8d85310b5d27e92d]::ast::Crate>)>>
  36:     0x7f2ae1e16723 - rustc_span[1a026db0fbf8373b]::set_source_map::<core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>, rustc_interface[a1e77c0e0a807641]::interface::run_compiler<core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>, rustc_driver_impl[da10067d57af8d1d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  37:     0x7f2ae1e10cc0 - std[b9a874157477860e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a1e77c0e0a807641]::util::run_in_thread_pool_with_globals<rustc_interface[a1e77c0e0a807641]::interface::run_compiler<core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>, rustc_driver_impl[da10067d57af8d1d]::run_compiler::{closure#1}>::{closure#0}, core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>>
  38:     0x7f2ae23be565 - <<std[b9a874157477860e]::thread::Builder>::spawn_unchecked_<rustc_interface[a1e77c0e0a807641]::util::run_in_thread_pool_with_globals<rustc_interface[a1e77c0e0a807641]::interface::run_compiler<core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>, rustc_driver_impl[da10067d57af8d1d]::run_compiler::{closure#1}>::{closure#0}, core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[708e8bb138b9c609]::result::Result<(), rustc_span[1a026db0fbf8373b]::ErrorGuaranteed>>::{closure#1} as core[708e8bb138b9c609]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f2adf972225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1e7c61bdab097da8
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/alloc/src/boxed.rs:2007:9
  40:     0x7f2adf972225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfdf756610eac66a4
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/alloc/src/boxed.rs:2007:9
  41:     0x7f2adf972225 - std::sys::unix::thread::Thread::new::thread_start::h65a83d8fc5842941
                               at /rustc/f525bb4e2afac6d2491a86c178aa98e3f3931130/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7f2adf6cb44b - <unknown>
  43:     0x7f2adf74ee40 - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/tmp/im/rustc-ice-2023-08-08T19:12:40.973402629Z-3356979.txt` to your bug report

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #114636 

This PR eliminates the dummy field, initially introduced in #113999, thereby enabling unrestricted use of ﻿`ident.unwrap()`. A side effect of this action is that we can only report the error of the first macro invocation field within the struct node.

An alternative solution might be giving a virtual name to the macro, but it appears more complex.(https://github.com/rust-lang/rust/issues/114636#issuecomment-1670228715). Furthermore, if you think https://github.com/rust-lang/rust/issues/114636#issuecomment-1670228715 is a better solution, feel free to close this PR.

### CODE REVIEW

**Comment by bvanjoi** [comment]
cc @Centri3

**Comment by compiler-errors** [comment]
This is a somewhat sad regression but it's fine imo

**Comment by compiler-errors** [comment]
r=me
@bors delegate+ rollup

**Comment by Centri3** [comment]
> An alternative solution might be giving a virtual name to the macro, but it appears more complex.

It really isn't. You can easily give it its name by using the already parsed `name` variable, though I think having multiple fields with the same name is *probably* breaking an invariant of named structs. Maybe not? I'm not sure but I think this is something disallowed really early on, as afaik macro expansion doesn't even happen if there are multiple fields with the same name.

Instead, I think, if you want to go through the trouble, make `parse_name_and_ty` return an `Option<FieldDef>` and push it onto the field list only if it's `Some`. Otherwise, just continue and act as though it never existed.

This shouldn't even be that big of a performance regression since all it is is *usually* a pointer under the hood, and a single `null` check after the call.

**Comment by bvanjoi** [comment]
> make parse_name_and_ty return an Option<FieldDef> and push it onto the field list only if it's Some

This represents an improved solution.

@rustbot ready

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1849,23 +1852,15 @@ impl<'a> Parser<'a> {
         lo: Span,
         vis: Visibility,
         attrs: AttrVec,
-    ) -> PResult<'a, FieldDef> {
+    ) -> PResult<'a, Option<FieldDef>> {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1855]: Can you make `Option<FieldDef>` into `Result<FieldDef, ErrorGuaranteed>`?

We should only ever return `Err` when a diagnostic is emitted.

Comment (bvanjoi) [reply compiler/rustc_parse/src/parser/item.rs:1855]: I think if we return `﻿Err` directly, the commit https://github.com/rust-lang/rust/commit/f25f9fe7d239dc866dbc0e522eb6011e6acb9806  is sufficient. Would it be advisable to revert it?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs:1855]: No, we're not returning a `DiagnosticBuilder` here, we're just returning the `ErrorGuaranteed` token from emitting that error.

Comment (bvanjoi) [reply compiler/rustc_parse/src/parser/item.rs]: The side effect of changing `﻿Option` to `﻿Result` involves the implementation of `﻿HasTokens` and `﻿HasAttrs` for `﻿Result`. While it may appear a bit unconventional, it seems remains acceptable.

Another aspect possibly requiring modification might be the return type of [parse_enum_variant](https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/parser/item.rs#L1461).

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -1610,12 +1612,13 @@ impl<'a> Parser<'a> {
                     e
                 });
                 match field {
-                    Ok(field) => fields.push(field),
+                    Ok(Ok(field)) => fields.push(field),
```
Comment (Centri3) [inline compiler/rustc_parse/src/parser/item.rs:1615]: `Result<Result<T>>` is, a bit weird imo. I think if possible, we should edit this to represent something similar to `Result<T, Either<DiagnosticBuilder, ErrorGuaranteed>>, and report the error if it's `DiagnosticBuilder`.

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (Centri3) [reply compiler/rustc_parse/src/parser/item.rs]: I believe it was already like this. We should probably modify `PResult` to optionally have a `DiagnosticBuilder`, somehow.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs]: Please do not modify PResult 😅

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs]: Also returning Err for the PResult variant would cause us to fail parsing -- I thought the whole point of this modification was to recover?

Comment (Centri3) [reply compiler/rustc_parse/src/parser/item.rs]: > Also returning the Err variant for the PResult would cause us to fail parsing -- I thought the whole point of this modification was to recover?

That's what I was worried about, it would require much more changes. We could implement `Try` on a different `PResult`, but is that worth the effort? Probably not

I don't like having a nested `Result` though, we have two error conditions but one which we should essentially ignore; `Result<Result<T>>` doesn't convey this properly.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs]: Having two results represent two levels of state here -- the first Result is parsing failure, and the second is to carry an ErrorGuaranteed to make sure we don't ever accidentally drop fields. I think it's totally fine, if only a bit awkward.

File: compiler/rustc_parse/src/parser/item.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs:1615]: Let's not do this. I don't even think the eager recovery of fields here is necessarily worth it, given the amount of code that this results in.

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -1849,23 +1854,15 @@ impl<'a> Parser<'a> {
...
-                return Ok(FieldDef {
-                    span: DUMMY_SP,
-                    ident: None,
-                    vis,
-                    id: DUMMY_NODE_ID,
-                    ty: self.mk_ty(DUMMY_SP, TyKind::Err),
-                    attrs,
-                    is_placeholder: false,
-                });
+                return Ok(Err(res));
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:1865]: Let's just change this to:

```
err.subdiagnostic(MacroExpandsToAdtField { adt_ty });
return Err(err);
```

**Review by compiler-errors — COMMENTED** [review]
Sorry for the back and forth @bvanjoi, but I thought about this some more and I'm not convinced that all of the changes are worth it. Let's just go with the simple approach and bail eagerly.

**Comment by bvanjoi** [comment]
> Sorry for the back and forth

Not to worry. As a beginner, every piece of advice is invaluable.

@rustbot ready
