### PR TITLE
Set `signext` or `zeroext` for integer arguments on RISC-V and LoongArch64

### LINKED ISSUE #114508: RISC-V Codegen Problem with type information
Codegen for `riscv64gc-unknown-linux-gnu` sends wrong type information to LLVM.

When I compile on godbolt.org with the following flags.

[GodBolt Link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:19,endLineNumber:2,positionColumn:19,positionLineNumber:2,selectionStartColumn:19,selectionStartLineNumber:2,startColumn:19,startLineNumber:2),source:'pub+fn+max(a:+u32+,+b:+u32)+-%3E+u32+%7B%0A++++u32::max(a,+b)%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:49.165541155755804,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1710,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'--target%3Driscv64gc-unknown-linux-gnu+-C+target-feature%3D%2Bzbb+-C+opt-level%3D3',overrides:!(),selection:(endColumn:12,endLineNumber:5,positionColumn:1,positionLineNumber:1,selectionStartColumn:12,selectionStartLineNumber:5,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+1.71.0+(Editor+%231)',t:'0')),k:50.834458844244224,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```
--target=riscv64gc-unknown-linux-gnu -C target-feature=+zbb -C opt-level=3
```

I tried this code:

```rust
fn max(a: u32, b: u32) -> u32 {
    u32::max(a, b)
}
```

It outputs:

```asm
example::max:
        sext.w  a1, a1
        sext.w  a0, a0
        maxu    a0, a0, a1
        ret
```

It definitely does not need to sign extend `a0` or `a1` and in fact, when we inspect the LLVM IR, it seems to assume that the numbers are `i32`s instead of `u32`s. Is this a problem with Rust's codegen output?

LLVM IR:
```
; example::max
define noundef i32 @example::max(i32 noundef %a, i32 noundef %b) unnamed_addr personality ptr @rust_eh_personality {
start:
  %.0.sroa.speculated.i = tail call i32 @llvm.umax.i32(i32 %a, i32 %b)
  ret i32 %.0.sroa.speculated.i
}

declare noundef signext i32 @rust_eh_personality(i32 noundef signext, i32 noundef signext, i64 noundef, ptr noundef, ptr noundef) unnamed_addr #1

declare i32 @llvm.umax.i32(i32, i32) #2
```

Properly optimized code would be:

```asm
example::max:
        maxu    a0, a0, a1
        ret
```

### PR DESCRIPTION
**Pull request by SpriteOvO**
This PR contains 3 commits:

- the first one introduces a new function `adjust_for_rust_abi` in `rustc_target`, and moves the x86 specific adjustment code into it;
- the second one adds RISC-V specific adjustment code into it, which sets `signext` or `zeroext` attribute for integer arguments.
- **UPDATE**: added the 3rd commit to apply the same adjustment for LoongArch64.

Fixes #114508.

r? @workingjubilee 
CC @coastalwhite @Urgau @topperc @michaelmaitland

### CODE REVIEW

**Comment by workingjubilee** [comment]
Oh _thank you_ for rust-lang/rust@9ba8053ff8b60cf59b917875c44600a8c63e3905

File: tests/assembly/riscv64gc-zbb.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
+//@ assembly-output: emit-asm
+//@ compile-flags: --target riscv64gc-unknown-linux-gnu
+//@ compile-flags: -C target-feature=+zbb
+//@ compile-flags: -C opt-level=3
```
Comment (workingjubilee) [inline tests/assembly/riscv64gc-zbb.rs:4]: This won't be good enough, it needs to have compiled the parts of libcore we use here and that isn't guaranteed on a given test host.

File: tests/codegen/checked_math.rs [hunk 2]
```diff
@@ -1,4 +1,10 @@
 //@ compile-flags: -O -Z merge-functions=disabled
+//@ revisions: others riscv64
+
+//@[others] ignore-riscv64
+//@[riscv64] only-riscv64
+//@[riscv64] compile-flags: --target riscv64gc-unknown-linux-gnu
+//@[riscv64] needs-llvm-components: riscv
```
Comment (workingjubilee) [inline tests/codegen/checked_math.rs:7]: you may wish to reuse this pattern for tests/assembly/riscv64gc-zbb.rs

File: tests/assembly/riscv64gc-zbb.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    u32::max(a, b)
+}
+
+#[no_mangle]
+// CHECK-LABEL: issue_114508_i32:
+pub fn issue_114508_i32(a: i32, b: i32) -> i32 {
+    // CHECK:      max a0, a0, a1
+    // CHECK-NEXT: ret
+    i32::max(a, b)
+}
```
Comment (workingjubilee) [inline tests/assembly/riscv64gc-zbb.rs:23]: as mentioned in the issue, this problem affects both loongarch and riscv, and it affects riscv both with and without zbb, having consulted Godbolt: https://godbolt.org/z/hnWhx5bz9

so I'd like to see two more tests. at least one should be another revision in this test, specifically for riscv-without-zbb (well, this revision should become riscv-zbb, actually). you can make the loongarch test its own file or yet another revision.

File: tests/assembly/riscv64gc-zbb.rs (hunk 1 above)
Comment (SpriteOvO) [reply tests/assembly/riscv64gc-zbb.rs]: I have added `only-riscv64` header for it, it should be fine now.

File: tests/assembly/riscv64gc-zbb.rs (hunk 3 above)
Comment (SpriteOvO) [reply tests/assembly/riscv64gc-zbb.rs]: I have added non-zbb ext checks in it and improved conditions (with all `-NEXT` tag).

Since RISC-V and LoongArch are different archs (though highly similar), checking the expected LoongArch ASM output requires we do the similar adjustment to Rust ABI. I have added it in the third commit.

**Comment by SpriteOvO** [comment]
CC @xen0n since the PR contains changes about LoongArch.

File: tests/codegen/checked_ilog.rs [hunk 4]
```diff
@@ -1,11 +1,23 @@
...
 
 #![crate_type = "lib"]
 
 // Ensure that when val < base, we do not divide or multiply.
 
 // CHECK-LABEL: @checked_ilog
-// CHECK-SAME: (i16 noundef %val, i16 noundef %base)
+// others-SAME:      (i16 noundef %val, i16 noundef %base)
+// riscv64-SAME:     (i16 noundef zeroext %val, i16 noundef zeroext %base)
+// loongarch64-SAME: (i16 noundef zeroext %val, i16 noundef zeroext %base)
```
Comment (nikic) [inline tests/codegen/checked_ilog.rs:20]: For tests where checking the zeroext/signext attributes is not the point of the test, I'd prefer to just use a `{{.*}}` wildcard, rather than splitting this by architecture.

Comment (workingjubilee) [reply tests/codegen/checked_ilog.rs:20]: like so?
```suggestion
// CHECK-SAME: (i16 noundef {{.*}} %val, i16 noundef {{.*}} %base)
```

Comment (workingjubilee) [inline tests/codegen/checked_ilog.rs:20]: like so?
```suggestion
// CHECK-SAME: (i16 noundef {{.*}} %val, i16 noundef {{.*}} %base)
```

or without the noundef? it's not clear to me if checking for that attr is useful for this test or not, honestly.
```suggestion
// CHECK-SAME: (i16 {{.*}} %val, i16 {{.*}} %base)
```

Comment (nikic) [reply tests/codegen/checked_ilog.rs:20]: It's fine to add the noundef into the wildcard as well, it's not relevant to the purpose of the test.

Comment (SpriteOvO) [reply tests/codegen/checked_ilog.rs]: Done. Since space matters in Regex matching, I had to use `ty{{( .+)?}} %var` instead of `ty {{.*}} %var`.

Comment (SpriteOvO) [reply tests/codegen/checked_ilog.rs]: Also added a separated test file `tests/codegen/rust-abi-arch-specific-adjustment.rs` specifically for the changes in this PR.

File: tests/assembly/rust-abi-arg-attr.rs [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+//@ [riscv64] only-riscv64
+//@ [riscv64] compile-flags: --target riscv64gc-unknown-linux-gnu
+//@ [riscv64] needs-llvm-components: riscv
+//@ [riscv64-zbb] only-riscv64
+//@ [riscv64-zbb] compile-flags: --target riscv64gc-unknown-linux-gnu
+//@ [riscv64-zbb] compile-flags: -C target-feature=+zbb
+//@ [riscv64-zbb] needs-llvm-components: riscv
+//@ [loongarch64] only-loongarch64
+//@ [loongarch64] compile-flags: --target loongarch64-unknown-linux-gnu
+//@ [loongarch64] needs-llvm-components: loongarch
```
Comment (nikic) [inline tests/assembly/rust-abi-arg-attr.rs:13]: This should be a no_core test.

File: tests/codegen/checked_ilog.rs [hunk 6]
```diff
@@ -5,7 +5,7 @@
 // Ensure that when val < base, we do not divide or multiply.
 
 // CHECK-LABEL: @checked_ilog
-// CHECK-SAME: (i16 noundef %val, i16 noundef %base)
+// CHECK-SAME: (i16{{( .+)?}} %val, i16{{( .+)?}} %base)
```
Comment (nikic) [inline tests/codegen/checked_ilog.rs:8]:
```suggestion
// CHECK-SAME: (i16{{.*}} %val, i16{{.*}} %base)
```
Should be enough, there's no need to explicitly match the space, we're not really afraid of accidentally generating i165 here...

File: tests/assembly/rust-abi-arg-attr.rs (hunk 5 above)
Comment (SpriteOvO) [reply tests/assembly/rust-abi-arg-attr.rs:13]: The test file uses `{i32,u32}::max`, if marking it with `#![no_core]`, how do I use the `max` methods?

Comment (SpriteOvO) [reply tests/assembly/rust-abi-arg-attr.rs:13]: `::gt` is also requires core.

```
error[E0369]: binary operation `>` cannot be applied to type `u32`
  --> /rust/tests/assembly/rust-abi-arg-attr.rs:39:10
   |
39 |     if a > b { a } else { b }
   |        - ^ - u32
   |        |
   |        u32

error[E0369]: binary operation `>` cannot be applied to type `i32`
  --> /rust/tests/assembly/rust-abi-arg-attr.rs:59:10
   |
59 |     if a > b { a } else { b }
   |        - ^ - i32
   |        |
   |        i32
```

File: tests/codegen/checked_ilog.rs (hunk 6 above)
Comment (SpriteOvO) [reply tests/codegen/checked_ilog.rs]: Makes sense, this is more clear indeed. Done.

File: tests/assembly/rust-abi-arg-attr.rs (hunk 5 above)
Comment (workingjubilee) [reply tests/assembly/rust-abi-arg-attr.rs:13]: The impl of Ord for these types looks like this:

```rust
    macro_rules! ord_impl {
        ($($t:ty)*) => ($(
            #[stable(feature = "rust1", since = "1.0.0")]
            impl PartialOrd for $t {
                #[inline]
                fn partial_cmp(&self, other: &$t) -> Option<Ordering> {
                    Some(crate::intrinsics::three_way_compare(*self, *other))
                }
                #[inline(always)]
                fn lt(&self, other: &$t) -> bool { (*self) < (*other) }
                #[inline(always)]
                fn le(&self, other: &$t) -> bool { (*self) <= (*other) }
                #[inline(always)]
                fn ge(&self, other: &$t) -> bool { (*self) >= (*other) }
                #[inline(always)]
                fn gt(&self, other: &$t) -> bool { (*self) > (*other) }
            }

            #[stable(feature = "rust1", since = "1.0.0")]
            impl Ord for $t {
                #[inline]
                fn cmp(&self, other: &$t) -> Ordering {
                    crate::intrinsics::three_way_compare(*self, *other)
                }
            }
        )*)
    }
```

Comment (workingjubilee) [reply tests/assembly/rust-abi-arg-attr.rs:13]: Personally, assuming no objections, I am happy with this not being a no-core test until https://github.com/rust-lang/rust/pull/130693 lands.

Please leave a FIXME though.

Comment (SpriteOvO) [reply tests/assembly/rust-abi-arg-attr.rs:13]: Oh, so if I understand correctly, if I choose to mark `no_core` in this PR, I have to copy `three_way_compare`'s declaration (including `enum Ordering`) to here, right? I'll try it after I wake up.

It looks like #130693 didn't add `Ord` for `minicore` either, should we remind them?

Comment (workingjubilee) [reply tests/assembly/rust-abi-arg-attr.rs:13]: Yes, exactly.

And sure, cc @jieyouxu you will want to absorb this PR, I think.

It's probably omitted because nobody's bothered so far.

Comment (jieyouxu) [reply tests/assembly/rust-abi-arg-attr.rs:13]: https://github.com/rust-lang/rust/pull/130693 didn't add the full core stubs because I was trying to figure out the infra first, it's intended that people can add grow the core stubs as needed (I didn't want to figure out all the core stubs). I'll absorb the ord stuff into what I had previously, but it doesn't need to block this PR (unless you want to wait for `minicore` to land first).

File: compiler/rustc_ty_utils/src/abi.rs [hunk 7]
```diff
@@ -834,11 +710,6 @@ fn fn_abi_adjust_for_abi<'tcx>(
                     }
                 }
```
Comment (bjorn3) [inline compiler/rustc_ty_utils/src/abi.rs:711]: Maybe move this code into adjust_for_rust_abi too?

File: tests/assembly/rust-abi-arg-attr.rs (hunk 5 above)
Comment (SpriteOvO) [reply tests/assembly/rust-abi-arg-attr.rs:13]: Done! Added a minimal reimplementation of `{u,i}32::max`, so we can go no_core now~

File: compiler/rustc_ty_utils/src/abi.rs (hunk 7 above)
Comment (SpriteOvO) [reply compiler/rustc_ty_utils/src/abi.rs:711]: This was my first attempt locally. The function `fn_abi_adjust_for_abi` uses items from the `rustc_middle` and `rustc_session` crates, but `rustc_target` crate doesn't seem to depend on them. I guess this is to keep `rustc_target` crate as minimal as possible. So I gave up on moving it all over.

**Comment by SpriteOvO** [comment]
Rebased to the latest master since #131871 is merged just now.

File: tests/assembly/rust-abi-arg-attr.rs [hunk 8]
```diff
@@ -0,0 +1,111 @@
+//@ assembly-output: emit-asm
+//@ revisions: riscv64 riscv64-zbb loongarch64
+//@ compile-flags: -C opt-level=3
+//@ [riscv64] only-riscv64
```
Comment (workingjubilee) [inline tests/assembly/rust-abi-arg-attr.rs:4]: With the cross-compilation flags set up properly, and now this being `no_core`, this no longer needs the "only" tags:
```suggestion
```

File: tests/assembly/rust-abi-arg-attr.rs [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+//@ [riscv64] compile-flags: --target riscv64gc-unknown-linux-gnu
+//@ [riscv64] needs-llvm-components: riscv
+//@ [riscv64-zbb] only-riscv64
```
Comment (workingjubilee) [inline tests/assembly/rust-abi-arg-attr.rs:7]:
```suggestion
```

File: tests/assembly/rust-abi-arg-attr.rs [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+//@ [riscv64-zbb] compile-flags: --target riscv64gc-unknown-linux-gnu
+//@ [riscv64-zbb] compile-flags: -C target-feature=+zbb
+//@ [riscv64-zbb] needs-llvm-components: riscv
+//@ [loongarch64] only-loongarch64
```
Comment (workingjubilee) [inline tests/assembly/rust-abi-arg-attr.rs:11]:
```suggestion
```

File: tests/assembly/rust-abi-arg-attr.rs (hunk 8 above)
Comment (SpriteOvO) [reply tests/assembly/rust-abi-arg-attr.rs]: Get it! Commits updated.

**Comment by workingjubilee** [comment]
- This was the recommended implementation by @michaelmaitland here: https://github.com/rust-lang/rust/issues/114508#issuecomment-2397243236
- It was recommended for the arches specified here: https://github.com/rust-lang/rust/issues/114508#issuecomment-2397618125
- And the LoongArch maintainers think it's cool.

So, looks like we're good.

@bors r+
