### PR TITLE
Taint the type of ill-formed (unsized) statics

### LINKED ISSUE #121176: ICE `immediate Scalar(alloc1) does not fit to layout TyAndLayout`
snippet:
````rust
use std::fmt::Debug;

static STATIC_1: dyn Debug + Sync = *();

fn main() {
    println!("{:?}", &STATIC_1);
}


````

Version information
````
rustc 1.78.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.78.0-dev
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/local-debug-assertions/bin/rustc `

### LINKED ISSUE #129109: ICE: `write_immediate_to_mplace: invalid Scalar layout: TyAndLayout`
auto-reduced (treereduce-rust):
````rust
extern "C" {
    pub static mut symbol: [i8];

}

fn main() {
    println!("C", unsafe { &symbol });
}


````

original:
````rust
extern "C" {
    pub static mut symbol: [i8];
    //~^ WARN creating a shared reference to mutable static is discouraged [static_mut_refs]
}

fn main() {
    println!("C", unsafe { &symbol });
    //~^ WARN creating a shared reference to mutable static is discouraged [static_mut_refs]
}

````

Version information
````
rustc 1.82.0-nightly (fbce03b19 2024-08-14)
binary: rustc
commit-hash: fbce03b195c02e425fbb12276b8f02349048a75f
commit-date: 2024-08-14
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: argument never used
 --> /tmp/icemaker_global_tempdir.gKK7s1KquQAJ/rustc_testrunner_tmpdir_reporting.JRe5Vq1I3rjY/mvce.rs:7:19
  |
7 |     println!("C", unsafe { &symbol });
  |              ---  ^^^^^^^^^^^^^^^^^^ argument never used
  |              |
  |              formatting specifier missing

error[E0277]: the size for values of type `[i8]` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.gKK7s1KquQAJ/rustc_testrunner_tmpdir_reporting.JRe5Vq1I3rjY/mvce.rs:2:28
  |
2 |     pub static mut symbol: [i8];
  |                            ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[i8]`

warning: creating a shared reference to mutable static is discouraged
 --> /tmp/icemaker_global_tempdir.gKK7s1KquQAJ/rustc_testrunner_tmpdir_reporting.JRe5Vq1I3rjY/mvce.rs:7:28
  |
7 |     println!("C", unsafe { &symbol });
  |                            ^^^^^^^ shared reference to mutable static
  |
  = note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
  = note: this will be a hard error in the 2024 edition
  = note: this shared reference has lifetime `'static`, but if the static ever gets mutated, or a mutable reference is created, then any further use of this shared reference is Undefined Behavior
  = note: `#[warn(static_mut_refs)]` on by default
help: use `addr_of!` instead to create a raw pointer
  |
7 |     println!("C", unsafe { addr_of!(symbol) });
  |                            ~~~~~~~~~      +

error: internal compiler error: /rustc/fbce03b195c02e425fbb12276b8f02349048a75f/compiler/rustc_const_eval/src/interpret/place.rs:693:21: write_immediate_to_mplace: invalid Scalar layout: TyAndLayout {
                                    ty: &[i8],
                                    layout: Layout {
                                        size: Size(16 bytes),
                                        align: AbiAndPrefAlign {
                                            abi: Align(8 bytes),
                                            pref: Align(8 bytes),
                                        },
                                        abi: ScalarPair(
                                            Initialized {
                                                value: Pointer(
                                                    AddressSpace(
                                                        0,
                                                    ),
                                                ),
                                                valid_range: 1..=18446744073709551615,
                                            },
                                            Initialized {
                                                value: Int(
                                                    I64,
                                                    false,
                                                ),
                                                valid_range: 0..=18446744073709551615,
                                            },
                                        ),
                                        fields: Arbitrary {
                                            offsets: [
                                                Size(0 bytes),
                                                Size(8 bytes),
                                            ],
                                            memory_index: [
                                                0,
                                                1,
                                            ],
                                        },
                                        largest_niche: Some(
                                            Niche {
                                                offset: Size(0 bytes),
                                                value: Pointer(
                                                    AddressSpace(
                                                        0,
                                                    ),
                                                ),
                                                valid_range: 1..=18446744073709551615,
                                            },
                                        ),
                                        variants: Single {
                                            index: 0,
                                        },
                                        max_repr_align: None,
                                        unadjusted_abi_align: Align(8 bytes),
                                    },
                                }

thread 'rustc' panicked at /rustc/fbce03b195c02e425fbb12276b8f02349048a75f/compiler/rustc_const_eval/src/interpret/place.rs:693:21:
Box<dyn Any>
stack backtrace:
   0:     0x7dabe2fb666d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h560b4d28c137b093
   1:     0x7dabe3804f2f - core::fmt::write::h99766545c4efef9d
   2:     0x7dabe47b0ed1 - std::io::Write::write_fmt::h8e3cbf6208612263
   3:     0x7dabe2fb8d4b - std::panicking::default_hook::{{closure}}::h6bf6ccd32e88a7b7
   4:     0x7dabe2fb89be - std::panicking::default_hook::ha56d0025017107a4
   5:     0x7dabe2146299 - std[265a0665abe5e043]::panicking::update_hook::<alloc[f7eab8ff756c9dca]::boxed::Box<rustc_driver_impl[18c1de8e11281817]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x7dabe2fb9667 - std::panicking::rust_panic_with_hook::h53b891e816ad5807
   7:     0x7dabe2180b41 - std[265a0665abe5e043]::panicking::begin_panic::<rustc_errors[99e98b0bbb24b16c]::ExplicitBug>::{closure#0}
   8:     0x7dabe2173d26 - std[265a0665abe5e043]::sys::backtrace::__rust_end_short_backtrace::<std[265a0665abe5e043]::panicking::begin_panic<rustc_errors[99e98b0bbb24b16c]::ExplicitBug>::{closure#0}, !>
   9:     0x7dabe2173aa6 - std[265a0665abe5e043]::panicking::begin_panic::<rustc_errors[99e98b0bbb24b16c]::ExplicitBug>
  10:     0x7dabe2189cc1 - <rustc_errors[99e98b0bbb24b16c]::diagnostic::BugAbort as rustc_errors[99e98b0bbb24b16c]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7dabe283efcd - <rustc_errors[99e98b0bbb24b16c]::DiagCtxtHandle>::span_bug::<rustc_span[e524fe640245e945]::span_encoding::Span, alloc[f7eab8ff756c9dca]::string::String>
  12:     0x7dabe28719f8 - rustc_middle[d7f4792719c666e4]::util::bug::opt_span_bug_fmt::<rustc_span[e524fe640245e945]::span_encoding::Span>::{closure#0}
  13:     0x7dabe2871a2a - rustc_middle[d7f4792719c666e4]::ty::context::tls::with_opt::<rustc_middle[d7f4792719c666e4]::util::bug::opt_span_bug_fmt<rustc_span[e524fe640245e945]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7dabe285dd0b - rustc_middle[d7f4792719c666e4]::ty::context::tls::with_context_opt::<rustc_middle[d7f4792719c666e4]::ty::context::tls::with_opt<rustc_middle[d7f4792719c666e4]::util::bug::opt_span_bug_fmt<rustc_span[e524fe640245e945]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7dabe285cb27 - rustc_middle[d7f4792719c666e4]::util::bug::span_bug_fmt::<rustc_span[e524fe640245e945]::span_encoding::Span>
  16:     0x7dabe42a8335 - <rustc_const_eval[4703571d7d15c956]::interpret::eval_context::InterpCx<rustc_const_eval[4703571d7d15c956]::const_eval::dummy_machine::DummyMachine>>::write_immediate_to_mplace_no_validate
  17:     0x7dabe1324a74 - <rustc_mir_transform[4b24bac2940eeb7a]::gvn::GVN as rustc_middle[d7f4792719c666e4]::mir::MirPass>::run_pass
  18:     0x7dabe3802151 - rustc_mir_transform[4b24bac2940eeb7a]::pass_manager::run_passes_inner
  19:     0x7dabe432ccb3 - rustc_mir_transform[4b24bac2940eeb7a]::optimized_mir
  20:     0x7dabe435039b - rustc_query_impl[c2f5f95cecf69337]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c2f5f95cecf69337]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7f4792719c666e4]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7dabe382af27 - rustc_query_system[f8c10878fe801c76]::query::plumbing::try_execute_query::<rustc_query_impl[c2f5f95cecf69337]::DynamicConfig<rustc_query_system[f8c10878fe801c76]::query::caches::DefIdCache<rustc_middle[d7f4792719c666e4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c2f5f95cecf69337]::plumbing::QueryCtxt, false>
  22:     0x7dabe382a4df - rustc_query_impl[c2f5f95cecf69337]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7dabe0184814 - <rustc_middle[d7f4792719c666e4]::ty::context::TyCtxt>::instance_mir
  24:     0x7dabe3bb63f9 - rustc_interface[8b2190a255f69c87]::passes::run_required_analyses
  25:     0x7dabe43663de - rustc_interface[8b2190a255f69c87]::passes::analysis
  26:     0x7dabe43663b1 - rustc_query_impl[c2f5f95cecf69337]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c2f5f95cecf69337]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d7f4792719c666e4]::query::erase::Erased<[u8; 1usize]>>
  27:     0x7dabe47706ee - rustc_query_system[f8c10878fe801c76]::query::plumbing::try_execute_query::<rustc_query_impl[c2f5f95cecf69337]::DynamicConfig<rustc_query_system[f8c10878fe801c76]::query::caches::SingleCache<rustc_middle[d7f4792719c666e4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c2f5f95cecf69337]::plumbing::QueryCtxt, false>
  28:     0x7dabe477044f - rustc_query_impl[c2f5f95cecf69337]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7dabe45dd169 - rustc_interface[8b2190a255f69c87]::interface::run_compiler::<core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>, rustc_driver_impl[18c1de8e11281817]::run_compiler::{closure#0}>::{closure#1}
  30:     0x7dabe45025d0 - std[265a0665abe5e043]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8b2190a255f69c87]::util::run_in_thread_with_globals<rustc_interface[8b2190a255f69c87]::util::run_in_thread_pool_with_globals<rustc_interface[8b2190a255f69c87]::interface::run_compiler<core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>, rustc_driver_impl[18c1de8e11281817]::run_compiler::{closure#0}>::{closure#1}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>::{closure#0}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>
  31:     0x7dabe4502c3a - <<std[265a0665abe5e043]::thread::Builder>::spawn_unchecked_<rustc_interface[8b2190a255f69c87]::util::run_in_thread_with_globals<rustc_interface[8b2190a255f69c87]::util::run_in_thread_pool_with_globals<rustc_interface[8b2190a255f69c87]::interface::run_compiler<core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>, rustc_driver_impl[18c1de8e11281817]::run_compiler::{closure#0}>::{closure#1}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>::{closure#0}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[12164080e42249fc]::result::Result<(), rustc_span[e524fe640245e945]::ErrorGuaranteed>>::{closure#1} as core[12164080e42249fc]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7dabe4502fab - std::sys::pal::unix::thread::Thread::new::thread_start::hbf34cdaead1142d4
  33:     0x7dabe5dab39d - <unknown>
  34:     0x7dabe5e3049c - <unknown>
  35:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (fbce03b19 2024-08-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.

```

</p>
</details>

### LINKED ISSUE #130970: ICE: `expected wide pointer extra data`
auto-reduced (treereduce-rust):
````rust
fn main() {
    extern "C" {
        static symbol: [usize];
    }
    println!("{}", symbol[0]);
}


````

original:
````rust
//~ ERROR rustc_outlives

const _: bool = false && false;
const _: bool = true && false;
const _: bool = {
    let mut x = true && false;
    x
};
const _TOO_LOW: () = { u64::from_str_radix("12345ABCD" 1); };

fn main() {
    extern "C" {
        static symbol: [usize]; //~ ERROR: the size for values of type
    }
    println!("{}", symbol[0]);
    //~^ ERROR: extern static is unsafe
}

````

Version information
````
rustc 1.83.0-nightly (851f69868 2024-09-28)
binary: rustc
commit-hash: 851f698682aa2e4c226e1a2c1af30adbcb63aae2
commit-date: 2024-09-28
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0277]: the size for values of type `[usize]` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.UzS9t28kBj7Z/rustc_testrunner_tmpdir_reporting.ClR4SdutAcRi/mvce.rs:3:24
  |
3 |         static symbol: [usize];
  |                        ^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[usize]`

error[E0133]: use of extern static is unsafe and requires unsafe function or block
 --> /tmp/icemaker_global_tempdir.UzS9t28kBj7Z/rustc_testrunner_tmpdir_reporting.ClR4SdutAcRi/mvce.rs:5:20
  |
5 |     println!("{}", symbol[0]);
  |                    ^^^^^^ use of extern static
  |
  = note: extern statics are not controlled by the Rust type system: invalid data, aliasing violations or data races will cause undefined behavior

error: internal compiler error: /rustc/851f698682aa2e4c226e1a2c1af30adbcb63aae2/compiler/rustc_const_eval/src/interpret/place.rs:36:17: expected wide pointer extra data (e.g. slice length or trait object vtable)

thread 'rustc' panicked at /rustc/851f698682aa2e4c226e1a2c1af30adbcb63aae2/compiler/rustc_const_eval/src/interpret/place.rs:36:17:
Box<dyn Any>
stack backtrace:
   0:     0x7407a38ceaba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h7900a3ecde60f42e
   1:     0x7407a40037e6 - core::fmt::write::h550ce993e33b1b64
   2:     0x7407a51ae991 - std::io::Write::write_fmt::h934b266016a01ab9
   3:     0x7407a38ce912 - std::sys::backtrace::BacktraceLock::print::hfed7190cfb479085
   4:     0x7407a38d0e31 - std::panicking::default_hook::{{closure}}::hf3239a9153976196
   5:     0x7407a38d0c64 - std::panicking::default_hook::ha9ae936b7eae362b
   6:     0x7407a299a03f - std[7abf0287877b87c3]::panicking::update_hook::<alloc[dcdda265b4d77909]::boxed::Box<rustc_driver_impl[2b0d10d4d558aac7]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7407a38d1548 - std::panicking::rust_panic_with_hook::h62359f8c356e73f3
   8:     0x7407a29d41e1 - std[7abf0287877b87c3]::panicking::begin_panic::<rustc_errors[47f0f04182922d6e]::ExplicitBug>::{closure#0}
   9:     0x7407a29c7286 - std[7abf0287877b87c3]::sys::backtrace::__rust_end_short_backtrace::<std[7abf0287877b87c3]::panicking::begin_panic<rustc_errors[47f0f04182922d6e]::ExplicitBug>::{closure#0}, !>
  10:     0x7407a29c2769 - std[7abf0287877b87c3]::panicking::begin_panic::<rustc_errors[47f0f04182922d6e]::ExplicitBug>
  11:     0x7407a29dda71 - <rustc_errors[47f0f04182922d6e]::diagnostic::BugAbort as rustc_errors[47f0f04182922d6e]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7407a30020a4 - rustc_middle[8066596e1db03fa9]::util::bug::opt_span_bug_fmt::<rustc_span[19f86c6d4b17e07c]::span_encoding::Span>::{closure#0}
  13:     0x7407a2fe7dea - rustc_middle[8066596e1db03fa9]::ty::context::tls::with_opt::<rustc_middle[8066596e1db03fa9]::util::bug::opt_span_bug_fmt<rustc_span[19f86c6d4b17e07c]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7407a2fe7c7b - rustc_middle[8066596e1db03fa9]::ty::context::tls::with_context_opt::<rustc_middle[8066596e1db03fa9]::ty::context::tls::with_opt<rustc_middle[8066596e1db03fa9]::util::bug::opt_span_bug_fmt<rustc_span[19f86c6d4b17e07c]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7407a05cd630 - rustc_middle[8066596e1db03fa9]::util::bug::bug_fmt
  16:     0x7407a312dcf3 - <rustc_const_eval[45b572bde6308908]::interpret::place::MPlaceTy as rustc_const_eval[45b572bde6308908]::interpret::projection::Projectable<rustc_middle[8066596e1db03fa9]::mir::interpret::pointer::CtfeProvenance>>::len::<rustc_const_eval[45b572bde6308908]::const_eval::dummy_machine::DummyMachine>
  17:     0x7407a4a53010 - <rustc_mir_transform[7719501850dfb079]::gvn::VnState>::insert
  18:     0x7407a4a4519c - <rustc_mir_transform[7719501850dfb079]::gvn::VnState>::simplify_rvalue
  19:     0x7407a16394e4 - <rustc_mir_transform[7719501850dfb079]::gvn::GVN as rustc_mir_transform[7719501850dfb079]::pass_manager::MirPass>::run_pass
  20:     0x7407a400bd8d - rustc_mir_transform[7719501850dfb079]::pass_manager::run_passes_inner
  21:     0x7407a4a075e2 - rustc_mir_transform[7719501850dfb079]::optimized_mir
  22:     0x7407a4a05e9d - rustc_query_impl[6f1e8f04bf490f6a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f1e8f04bf490f6a]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8066596e1db03fa9]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7407a402fa38 - rustc_query_system[808f2ed519714d18]::query::plumbing::try_execute_query::<rustc_query_impl[6f1e8f04bf490f6a]::DynamicConfig<rustc_query_system[808f2ed519714d18]::query::caches::DefIdCache<rustc_middle[8066596e1db03fa9]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6f1e8f04bf490f6a]::plumbing::QueryCtxt, false>
  24:     0x7407a402eff3 - rustc_query_impl[6f1e8f04bf490f6a]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7407a1480699 - <rustc_middle[8066596e1db03fa9]::ty::context::TyCtxt>::instance_mir
  26:     0x7407a43a47dc - rustc_interface[a8f766607a628292]::passes::run_required_analyses
  27:     0x7407a4b068de - rustc_interface[a8f766607a628292]::passes::analysis
  28:     0x7407a4b068b1 - rustc_query_impl[6f1e8f04bf490f6a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f1e8f04bf490f6a]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8066596e1db03fa9]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7407a4e7892e - rustc_query_system[808f2ed519714d18]::query::plumbing::try_execute_query::<rustc_query_impl[6f1e8f04bf490f6a]::DynamicConfig<rustc_query_system[808f2ed519714d18]::query::caches::SingleCache<rustc_middle[8066596e1db03fa9]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[6f1e8f04bf490f6a]::plumbing::QueryCtxt, false>
  30:     0x7407a4e7860f - rustc_query_impl[6f1e8f04bf490f6a]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7407a4d1825e - rustc_interface[a8f766607a628292]::interface::run_compiler::<core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>, rustc_driver_impl[2b0d10d4d558aac7]::run_compiler::{closure#0}>::{closure#1}
  32:     0x7407a4de3290 - std[7abf0287877b87c3]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a8f766607a628292]::util::run_in_thread_with_globals<rustc_interface[a8f766607a628292]::util::run_in_thread_pool_with_globals<rustc_interface[a8f766607a628292]::interface::run_compiler<core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>, rustc_driver_impl[2b0d10d4d558aac7]::run_compiler::{closure#0}>::{closure#1}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>::{closure#0}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>
  33:     0x7407a4de38fa - <<std[7abf0287877b87c3]::thread::Builder>::spawn_unchecked_<rustc_interface[a8f766607a628292]::util::run_in_thread_with_globals<rustc_interface[a8f766607a628292]::util::run_in_thread_pool_with_globals<rustc_interface[a8f766607a628292]::interface::run_compiler<core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>, rustc_driver_impl[2b0d10d4d558aac7]::run_compiler::{closure#0}>::{closure#1}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>::{closure#0}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9c5d060eac7beb80]::result::Result<(), rustc_span[19f86c6d4b17e07c]::ErrorGuaranteed>>::{closure#1} as core[9c5d060eac7beb80]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7407a4de3ceb - std::sys::pal::unix::thread::Thread::new::thread_start::ha5204e3fc18d4472
  35:     0x7407a656039d - <unknown>
  36:     0x7407a65e549c - <unknown>
  37:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (851f69868 2024-09-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0133, E0277.
For more information about an error, try `rustc --explain E0133`.

```

</p>
</details>

### LINKED ISSUE #131347: ICE: `primitive read not possible for type`
auto-reduced (treereduce-rust):
````rust
struct S;

static STUFF: [i8] = [0; S::N];

fn main() {
    assert_eq!(STUFF, [0; 63]);
}


````

original:
````rust
//@ run-pass

struct S;

impl S {
    const N: usize = 3;
}

static STUFF: [i8] = [0; S::N];

fn main() {
    assert_eq!(STUFF, [0; 63]);
}

````

Version information
````
rustc 1.83.0-nightly (7d53688b2 2024-10-06)
binary: rustc
commit-hash: 7d53688b25d52d822c7094ee80db42b2b2f2a8d3
commit-date: 2024-10-06
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.1

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0277]: the size for values of type `[i8]` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.DNQmEJ3ruUkV/rustc_testrunner_tmpdir_reporting.YpnplTJyJ0BS/mvce.rs:3:15
  |
3 | static STUFF: [i8] = [0; S::N];
  |               ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[i8]`

error[E0599]: no associated item named `N` found for struct `S` in the current scope
 --> /tmp/icemaker_global_tempdir.DNQmEJ3ruUkV/rustc_testrunner_tmpdir_reporting.YpnplTJyJ0BS/mvce.rs:3:29
  |
1 | struct S;
  | -------- associated item `N` not found for this struct
2 |
3 | static STUFF: [i8] = [0; S::N];
  |                             ^ associated item not found in `S`

error[E0277]: the size for values of type `[i8]` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.DNQmEJ3ruUkV/rustc_testrunner_tmpdir_reporting.YpnplTJyJ0BS/mvce.rs:3:22
  |
3 | static STUFF: [i8] = [0; S::N];
  |                      ^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[i8]`
  = note: constant expressions must have a statically known size

error: internal compiler error: /rustc/7d53688b25d52d822c7094ee80db42b2b2f2a8d3/compiler/rustc_const_eval/src/interpret/operand.rs:637:13: primitive read not possible for type: ()

thread 'rustc' panicked at /rustc/7d53688b25d52d822c7094ee80db42b2b2f2a8d3/compiler/rustc_const_eval/src/interpret/operand.rs:637:13:
Box<dyn Any>
stack backtrace:
   0:     0x7e646991d14a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6ace371e0627a94e
   1:     0x7e646a003466 - core::fmt::write::h0da4415e760642fe
   2:     0x7e646b2d4651 - std::io::Write::write_fmt::h14d763d63a110c4d
   3:     0x7e646991cfa2 - std::sys::backtrace::BacktraceLock::print::h7d6a7a510b18a0ef
   4:     0x7e646991f476 - std::panicking::default_hook::{{closure}}::h754c7d0464a75c1a
   5:     0x7e646991f2c0 - std::panicking::default_hook::ha44cb32a98416a5c
   6:     0x7e64689d4ebf - std[f5329afc3aca534d]::panicking::update_hook::<alloc[75367514fbcf0ba1]::boxed::Box<rustc_driver_impl[2db31ecf159f2c88]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7e646991fb88 - std::panicking::rust_panic_with_hook::hba17070c6731b05a
   8:     0x7e6468a0ea11 - std[f5329afc3aca534d]::panicking::begin_panic::<rustc_errors[497b4da1b5346fe1]::ExplicitBug>::{closure#0}
   9:     0x7e6468a01ab6 - std[f5329afc3aca534d]::sys::backtrace::__rust_end_short_backtrace::<std[f5329afc3aca534d]::panicking::begin_panic<rustc_errors[497b4da1b5346fe1]::ExplicitBug>::{closure#0}, !>
  10:     0x7e6468a01a73 - std[f5329afc3aca534d]::panicking::begin_panic::<rustc_errors[497b4da1b5346fe1]::ExplicitBug>
  11:     0x7e6468a182a1 - <rustc_errors[497b4da1b5346fe1]::diagnostic::BugAbort as rustc_errors[497b4da1b5346fe1]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7e646913e1ad - <rustc_errors[497b4da1b5346fe1]::DiagCtxtHandle>::span_bug::<rustc_span[4e6ff54001148787]::span_encoding::Span, alloc[75367514fbcf0ba1]::string::String>
  13:     0x7e646916f9d8 - rustc_middle[371b8b9dd6010c8]::util::bug::opt_span_bug_fmt::<rustc_span[4e6ff54001148787]::span_encoding::Span>::{closure#0}
  14:     0x7e646916fa0a - rustc_middle[371b8b9dd6010c8]::ty::context::tls::with_opt::<rustc_middle[371b8b9dd6010c8]::util::bug::opt_span_bug_fmt<rustc_span[4e6ff54001148787]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7e646915947b - rustc_middle[371b8b9dd6010c8]::ty::context::tls::with_context_opt::<rustc_middle[371b8b9dd6010c8]::ty::context::tls::with_opt<rustc_middle[371b8b9dd6010c8]::util::bug::opt_span_bug_fmt<rustc_span[4e6ff54001148787]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7e64691582a7 - rustc_middle[371b8b9dd6010c8]::util::bug::span_bug_fmt::<rustc_span[4e6ff54001148787]::span_encoding::Span>
  17:     0x7e646aabce42 - <rustc_mir_transform[da304eeb1db9ec1]::gvn::VnState>::insert
  18:     0x7e646aab24e0 - <rustc_mir_transform[da304eeb1db9ec1]::gvn::VnState>::simplify_rvalue
  19:     0x7e64675d42a4 - <rustc_mir_transform[da304eeb1db9ec1]::gvn::GVN as rustc_mir_transform[da304eeb1db9ec1]::pass_manager::MirPass>::run_pass
  20:     0x7e646a00b6cd - rustc_mir_transform[da304eeb1db9ec1]::pass_manager::run_passes_inner
  21:     0x7e646a2b5822 - rustc_mir_transform[da304eeb1db9ec1]::optimized_mir
  22:     0x7e646a2b40e1 - rustc_query_impl[8639a1bd341d7b6f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8639a1bd341d7b6f]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[371b8b9dd6010c8]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7e646a292038 - rustc_query_system[51edba716c9866b7]::query::plumbing::try_execute_query::<rustc_query_impl[8639a1bd341d7b6f]::DynamicConfig<rustc_query_system[51edba716c9866b7]::query::caches::DefIdCache<rustc_middle[371b8b9dd6010c8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[8639a1bd341d7b6f]::plumbing::QueryCtxt, false>
  24:     0x7e646a2915f3 - rustc_query_impl[8639a1bd341d7b6f]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7e646742b6ff - <rustc_middle[371b8b9dd6010c8]::ty::context::TyCtxt>::instance_mir
  26:     0x7e646a46d14a - rustc_interface[e2e0aaaa9098ac0f]::passes::run_required_analyses
  27:     0x7e646ad219de - rustc_interface[e2e0aaaa9098ac0f]::passes::analysis
  28:     0x7e646ad219b1 - rustc_query_impl[8639a1bd341d7b6f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8639a1bd341d7b6f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[371b8b9dd6010c8]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7e646aed80ee - rustc_query_system[51edba716c9866b7]::query::plumbing::try_execute_query::<rustc_query_impl[8639a1bd341d7b6f]::DynamicConfig<rustc_query_system[51edba716c9866b7]::query::caches::SingleCache<rustc_middle[371b8b9dd6010c8]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[8639a1bd341d7b6f]::plumbing::QueryCtxt, false>
  30:     0x7e646aed7dcf - rustc_query_impl[8639a1bd341d7b6f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7e646ad191de - rustc_interface[e2e0aaaa9098ac0f]::interface::run_compiler::<core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>, rustc_driver_impl[2db31ecf159f2c88]::run_compiler::{closure#0}>::{closure#1}
  32:     0x7e646adf6690 - std[f5329afc3aca534d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[e2e0aaaa9098ac0f]::util::run_in_thread_with_globals<rustc_interface[e2e0aaaa9098ac0f]::util::run_in_thread_pool_with_globals<rustc_interface[e2e0aaaa9098ac0f]::interface::run_compiler<core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>, rustc_driver_impl[2db31ecf159f2c88]::run_compiler::{closure#0}>::{closure#1}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>::{closure#0}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>
  33:     0x7e646adf6d57 - <<std[f5329afc3aca534d]::thread::Builder>::spawn_unchecked_<rustc_interface[e2e0aaaa9098ac0f]::util::run_in_thread_with_globals<rustc_interface[e2e0aaaa9098ac0f]::util::run_in_thread_pool_with_globals<rustc_interface[e2e0aaaa9098ac0f]::interface::run_compiler<core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>, rustc_driver_impl[2db31ecf159f2c88]::run_compiler::{closure#0}>::{closure#1}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>::{closure#0}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c850f409d6837007]::result::Result<(), rustc_span[4e6ff54001148787]::ErrorGuaranteed>>::{closure#1} as core[c850f409d6837007]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7e646adf7c41 - std::sys::pal::unix::thread::Thread::new::thread_start::ha1af13d74af699f6
  35:     0x7e646c59639d - <unknown>
  36:     0x7e646c61b49c - <unknown>
  37:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (7d53688b2 2024-10-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.

```

</p>
</details>

### LINKED ISSUE #139872: ICE: `layout.is_sized()`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Zmir-opt-level=5 -Zvalidate-mir



enum E { V16(u16), V32(u32) }
static C: (E, u16, str) = (, 0x600D, 0xBAD);

pub fn main() {
    let (_, n, _) = C;
    
    
}

````

original:
````rust
//@ run-pass
#![allow(dead_code)]

enum E { V16(u16), V32(u32) }
static C: (E, u16, str) = (E::V16(0xDEAD), 0x600D, 0xBAD);

pub fn main() {
    let (_, n, _) = C;
    assert!(n != 0xBAD);
    assert_eq!(n, 0x600D);
}

````

Version information
````
rustc 1.88.0-nightly (40dacd50b 2025-04-15)
binary: rustc
commit-hash: 40dacd50b7074783db748d73925ac5c3693a7ec1
commit-date: 2025-04-15
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/40dacd50b7074783db748d73925ac5c3693a7ec1/compiler/rustc_middle/src/mir/interpret/mod.rs#L366-L378

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir`

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected expression, found `,`
 --> /tmp/icemaker_global_tempdir.3AprGNyTl55i/rustc_testrunner_tmpdir_reporting.bRtgIyNkaXla/mvce.rs:5:28
  |
5 | static C: (E, u16, str) = (, 0x600D, 0xBAD);
  |                            ^ expected expression

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> /tmp/icemaker_global_tempdir.3AprGNyTl55i/rustc_testrunner_tmpdir_reporting.bRtgIyNkaXla/mvce.rs:5:11
  |
5 | static C: (E, u16, str) = (, 0x600D, 0xBAD);
  |           ^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: within `(E, u16, str)`, the trait `Sized` is not implemented for `str`
  = note: required because it appears within the type `(E, u16, str)`
  = note: statics and constants must have a statically known size

warning: unused variable: `n`
 --> /tmp/icemaker_global_tempdir.3AprGNyTl55i/rustc_testrunner_tmpdir_reporting.bRtgIyNkaXla/mvce.rs:8:13
  |
8 |     let (_, n, _) = C;
  |             ^ help: if this is intentional, prefix it with an underscore: `_n`
  |
  = note: `#[warn(unused_variables)]` on by default


thread 'rustc' panicked at compiler/rustc_middle/src/mir/interpret/mod.rs:372:21:
assertion failed: layout.is_sized()
stack backtrace:
   0:     0x7f16c90e36f3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hac1fd18538367f85
   1:     0x7f16c9806087 - core::fmt::write::h355b50e2dd48b7cb
   2:     0x7f16cacaab91 - std::io::Write::write_fmt::h3c208cfcae87fbc5
   3:     0x7f16c90e3552 - std::sys::backtrace::BacktraceLock::print::h52bf60fe66a866b6
   4:     0x7f16c90e703a - std::panicking::default_hook::{{closure}}::ha54cd4f331000bf4
   5:     0x7f16c90e6bbf - std::panicking::default_hook::h65502b75eb6b3c4d
   6:     0x7f16c815b843 - std[6f1f62f9e1890267]::panicking::update_hook::<alloc[9c10c445f94edf6f]::boxed::Box<rustc_driver_impl[261694032873b461]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7f16c90e78b3 - std::panicking::rust_panic_with_hook::h9f8305ffe577d3e1
   8:     0x7f16c90e7576 - std::panicking::begin_panic_handler::{{closure}}::h1196da9ca3c9caa6
   9:     0x7f16c90e3bb9 - std::sys::backtrace::__rust_end_short_backtrace::h209d7d99dc310f1c
  10:     0x7f16c90e726d - __rustc[de9843575c99dce8]::rust_begin_unwind
  11:     0x7f16c5a8a680 - core::panicking::panic_fmt::h42dd318a0e6082fa
  12:     0x7f16c5a8f62c - core::panicking::panic::hb0960e31c93bed80
  13:     0x7f16cae0181e - <rustc_middle[2dc3a1ceabbabe6a]::mir::interpret::GlobalAlloc>::size_and_align.cold
  14:     0x7f16ca324c6a - <rustc_const_eval[ae92fa6a8d266fb6]::interpret::eval_context::InterpCx<rustc_const_eval[ae92fa6a8d266fb6]::const_eval::dummy_machine::DummyMachine>>::get_alloc_info
  15:     0x7f16ca334d58 - <rustc_const_eval[ae92fa6a8d266fb6]::interpret::eval_context::InterpCx<rustc_const_eval[ae92fa6a8d266fb6]::const_eval::dummy_machine::DummyMachine>>::ptr_offset_inbounds
  16:     0x7f16ca334ab9 - <rustc_const_eval[ae92fa6a8d266fb6]::interpret::operand::OpTy as rustc_const_eval[ae92fa6a8d266fb6]::interpret::projection::Projectable<rustc_middle[2dc3a1ceabbabe6a]::mir::interpret::pointer::CtfeProvenance>>::offset_with_meta::<rustc_const_eval[ae92fa6a8d266fb6]::const_eval::dummy_machine::DummyMachine>
  17:     0x7f16ca334998 - <rustc_const_eval[ae92fa6a8d266fb6]::interpret::eval_context::InterpCx<rustc_const_eval[ae92fa6a8d266fb6]::const_eval::dummy_machine::DummyMachine>>::project_field::<rustc_const_eval[ae92fa6a8d266fb6]::interpret::operand::OpTy>
  18:     0x7f16ca334447 - <rustc_const_eval[ae92fa6a8d266fb6]::interpret::eval_context::InterpCx<rustc_const_eval[ae92fa6a8d266fb6]::const_eval::dummy_machine::DummyMachine>>::project::<rustc_const_eval[ae92fa6a8d266fb6]::interpret::operand::OpTy>
  19:     0x7f16ca32d176 - <rustc_mir_transform[27e09089e56c5a07]::gvn::VnState>::insert
  20:     0x7f16ca32863b - <rustc_mir_transform[27e09089e56c5a07]::gvn::VnState>::simplify_place_value
  21:     0x7f16ca327deb - <rustc_mir_transform[27e09089e56c5a07]::gvn::VnState>::simplify_operand
  22:     0x7f16c70e2b1e - <rustc_mir_transform[27e09089e56c5a07]::gvn::VnState as rustc_middle[2dc3a1ceabbabe6a]::mir::visit::MutVisitor>::visit_statement
  23:     0x7f16c70e0e97 - <rustc_mir_transform[27e09089e56c5a07]::gvn::GVN as rustc_mir_transform[27e09089e56c5a07]::pass_manager::MirPass>::run_pass
  24:     0x7f16c9803fbb - rustc_mir_transform[27e09089e56c5a07]::pass_manager::run_passes_inner
  25:     0x7f16ca376a9f - rustc_mir_transform[27e09089e56c5a07]::optimized_mir
  26:     0x7f16ca37608d - rustc_query_impl[ad69a23e50a8fbd1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad69a23e50a8fbd1]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2dc3a1ceabbabe6a]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7f16c9af412f - rustc_query_system[8ca381065095edd4]::query::plumbing::try_execute_query::<rustc_query_impl[ad69a23e50a8fbd1]::DynamicConfig<rustc_query_system[8ca381065095edd4]::query::caches::DefIdCache<rustc_middle[2dc3a1ceabbabe6a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ad69a23e50a8fbd1]::plumbing::QueryCtxt, false>
  28:     0x7f16c9af355d - rustc_query_impl[ad69a23e50a8fbd1]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f16c9db3d46 - <rustc_middle[2dc3a1ceabbabe6a]::ty::context::TyCtxt>::instance_mir
  30:     0x7f16c9c0e0b4 - rustc_interface[f2198cb0de4afffb]::passes::run_required_analyses
  31:     0x7f16ca355f9e - rustc_interface[f2198cb0de4afffb]::passes::analysis
  32:     0x7f16ca355f73 - rustc_query_impl[ad69a23e50a8fbd1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ad69a23e50a8fbd1]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2dc3a1ceabbabe6a]::query::erase::Erased<[u8; 0usize]>>
  33:     0x7f16ca7fb73d - rustc_query_system[8ca381065095edd4]::query::plumbing::try_execute_query::<rustc_query_impl[ad69a23e50a8fbd1]::DynamicConfig<rustc_query_system[8ca381065095edd4]::query::caches::SingleCache<rustc_middle[2dc3a1ceabbabe6a]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ad69a23e50a8fbd1]::plumbing::QueryCtxt, false>
  34:     0x7f16ca7fb438 - rustc_query_impl[ad69a23e50a8fbd1]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f16cab1b47e - rustc_interface[f2198cb0de4afffb]::passes::create_and_enter_global_ctxt::<core[e6c01ae462af1362]::option::Option<rustc_interface[f2198cb0de4afffb]::queries::Linker>, rustc_driver_impl[261694032873b461]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  36:     0x7f16ca90d904 - rustc_interface[f2198cb0de4afffb]::interface::run_compiler::<(), rustc_driver_impl[261694032873b461]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7f16ca6ee028 - std[6f1f62f9e1890267]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f2198cb0de4afffb]::util::run_in_thread_with_globals<rustc_interface[f2198cb0de4afffb]::util::run_in_thread_pool_with_globals<rustc_interface[f2198cb0de4afffb]::interface::run_compiler<(), rustc_driver_impl[261694032873b461]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  38:     0x7f16ca6ee92b - <<std[6f1f62f9e1890267]::thread::Builder>::spawn_unchecked_<rustc_interface[f2198cb0de4afffb]::util::run_in_thread_with_globals<rustc_interface[f2198cb0de4afffb]::util::run_in_thread_pool_with_globals<rustc_interface[f2198cb0de4afffb]::interface::run_compiler<(), rustc_driver_impl[261694032873b461]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[e6c01ae462af1362]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f16ca6efd37 - std::sys::pal::unix::thread::Thread::new::thread_start::he9943a285b1830ff
  40:     0x7f16c46a370a - <unknown>
  41:     0x7f16c4727aac - <unknown>
  42:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (40dacd50b 2025-04-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.

```

</p>
</details>

### LINKED ISSUE #140332: ICE: `invalid immediate for given destination place`
Possible related issue:
- [#140100](https://github.com/rust-lang/rust/issues/140100) Which has a different query stack, and require some data in the var
- [#131347](https://github.com/rust-lang/rust/issues/131347) Remove the `mut` in it would be extremely like that.

*The test case is generated by a fuzzer and reduced manually*

### Code

```Rust
static mut S: [i8] = ["Some thing"; 1];
fn main() {
    assert_eq!(S, [0; 1]);
}
```

The command to reproduce should be: `rustc -C opt-level=3 --edition 2024 -Zvalidate-mir `

### Meta

`rustc --version --verbose`:
```
rustc 1.88.0-nightly (b4c8b0c3f 2025-04-25)
binary: rustc
commit-hash: b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3
commit-date: 2025-04-25
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

```

### Error output

```
error: internal compiler error: /rustc/b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3/compiler/rustc_const_eval/src/interpret/operand.rs:157:17: invalid immediate for given destination place: value Scalar(alloc1) does not match ABI ScalarPair(Initialized { value: Pointer(AddressSpace(0)), valid_range: 1..=18446744073709551615 }, Initialized { value: Int(I64, false), valid_range: 0..=18446744073709551615 }))


thread 'rustc' panicked at /rustc/b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3/compiler/rustc_const_eval/src/interpret/operand.rs:157:17:
Box<dyn Any>
...
query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0277]: the size for values of type `[i8]` cannot be known at compilation time
 --> tmp/out3/gen_30479.rs:1:15
  |
1 | static mut S: [i8] = ["Some thing"; 1];
  |               ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[i8]`
  = note: statics and constants must have a statically known size

error[E0308]: mismatched types
 --> tmp/out3/gen_30479.rs:1:23
  |
1 | static mut S: [i8] = ["Some thing"; 1];
  |                       ^^^^^^^^^^^^ expected `i8`, found `&str`

error[E0308]: mismatched types
 --> tmp/out3/gen_30479.rs:1:22
  |
1 | static mut S: [i8] = ["Some thing"; 1];
  |                      ^^^^^^^^^^^^^^^^^ expected `[i8]`, found `[i8; 1]`

error[E0133]: use of mutable static is unsafe and requires unsafe block
 --> tmp/out3/gen_30479.rs:3:16
  |
3 |     assert_eq!(S, [0; 1]);
  |                ^ use of mutable static
  |
  = note: mutable statics can be mutated by multiple threads: aliasing violations or data races will cause undefined behavior

error: internal compiler error: /rustc/b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3/compiler/rustc_const_eval/src/interpret/operand.rs:157:17: invalid immediate for given destination place: value Scalar(alloc1) does not match ABI ScalarPair(Initialized { value: Pointer(AddressSpace(0)), valid_range: 1..=18446744073709551615 }, Initialized { value: Int(I64, false), valid_range: 0..=18446744073709551615 }))


thread 'rustc' panicked at /rustc/b4c8b0c3f0533bb342a4873ff59bdad3883ab8e3/compiler/rustc_const_eval/src/interpret/operand.rs:157:17:
Box<dyn Any>
stack backtrace:
   0:     0x7512466ef453 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h3810760a61645fc6
   1:     0x751246e05ac7 - core::fmt::write::h0088928f76d30077
   2:     0x7512481f3311 - std::io::Write::write_fmt::h78de47c93a2470e9
   3:     0x7512466ef2b2 - std::sys::backtrace::BacktraceLock::print::hd536e5d51513ad76
   4:     0x7512466f30fa - std::panicking::default_hook::{{closure}}::h6492940019273362
   5:     0x7512466f2c7f - std::panicking::default_hook::h96833e74e5b18821
   6:     0x7512457756b3 - std[30e4b062834ac322]::panicking::update_hook::<alloc[8846d236b4ac61d9]::boxed::Box<rustc_driver_impl[6daf40cdc4897975]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7512466f3973 - std::panicking::rust_panic_with_hook::h33332f412fb2ffa9
   8:     0x7512457b1681 - std[30e4b062834ac322]::panicking::begin_panic::<rustc_errors[757a7ab50bea937f]::ExplicitBug>::{closure#0}
   9:     0x7512457a56b6 - std[30e4b062834ac322]::sys::backtrace::__rust_end_short_backtrace::<std[30e4b062834ac322]::panicking::begin_panic<rustc_errors[757a7ab50bea937f]::ExplicitBug>::{closure#0}, !>
  10:     0x7512457a1d99 - std[30e4b062834ac322]::panicking::begin_panic::<rustc_errors[757a7ab50bea937f]::ExplicitBug>
  11:     0x7512457bba51 - <rustc_errors[757a7ab50bea937f]::diagnostic::BugAbort as rustc_errors[757a7ab50bea937f]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x751245df70ea - rustc_middle[14964323be5c6d14]::util::bug::opt_span_bug_fmt::<rustc_span[9b2946c57ebb402d]::span_encoding::Span>::{closure#0}
  13:     0x751245dd221a - rustc_middle[14964323be5c6d14]::ty::context::tls::with_opt::<rustc_middle[14964323be5c6d14]::util::bug::opt_span_bug_fmt<rustc_span[9b2946c57ebb402d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x751245dd208b - rustc_middle[14964323be5c6d14]::ty::context::tls::with_context_opt::<rustc_middle[14964323be5c6d14]::ty::context::tls::with_opt<rustc_middle[14964323be5c6d14]::util::bug::opt_span_bug_fmt<rustc_span[9b2946c57ebb402d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x75124308aee0 - rustc_middle[14964323be5c6d14]::util::bug::bug_fmt
  16:     0x751247a28e44 - <rustc_const_eval[5548788696870cc5]::interpret::eval_context::InterpCx<rustc_const_eval[5548788696870cc5]::const_eval::dummy_machine::DummyMachine>>::write_immediate_to_mplace_no_validate
  17:     0x75124464c59b - <rustc_mir_transform[a95ce98e4e91b81e]::gvn::VnState as rustc_middle[14964323be5c6d14]::mir::visit::MutVisitor>::visit_statement
  18:     0x7512446450ab - <rustc_mir_transform[a95ce98e4e91b81e]::gvn::GVN as rustc_mir_transform[a95ce98e4e91b81e]::pass_manager::MirPass>::run_pass
  19:     0x751246e039fb - rustc_mir_transform[a95ce98e4e91b81e]::pass_manager::run_passes_inner
  20:     0x7512477efd1f - rustc_mir_transform[a95ce98e4e91b81e]::optimized_mir
  21:     0x7512477ef30d - rustc_query_impl[fe0de826094a3706]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fe0de826094a3706]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[14964323be5c6d14]::query::erase::Erased<[u8; 8usize]>>
  22:     0x75124714c56f - rustc_query_system[c83524e34b3ee13b]::query::plumbing::try_execute_query::<rustc_query_impl[fe0de826094a3706]::DynamicConfig<rustc_query_system[c83524e34b3ee13b]::query::caches::DefIdCache<rustc_middle[14964323be5c6d14]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[fe0de826094a3706]::plumbing::QueryCtxt, false>
  23:     0x75124714b99d - rustc_query_impl[fe0de826094a3706]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7512475ac7ef - <rustc_middle[14964323be5c6d14]::ty::context::TyCtxt>::instance_mir
  25:     0x75124790df8c - rustc_interface[76005b124f6a7e54]::passes::run_required_analyses
  26:     0x751247cf7a1e - rustc_interface[76005b124f6a7e54]::passes::analysis
  27:     0x751247cf79ed - rustc_query_impl[fe0de826094a3706]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fe0de826094a3706]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[14964323be5c6d14]::query::erase::Erased<[u8; 0usize]>>
  28:     0x751247cfd4fd - rustc_query_system[c83524e34b3ee13b]::query::plumbing::try_execute_query::<rustc_query_impl[fe0de826094a3706]::DynamicConfig<rustc_query_system[c83524e34b3ee13b]::query::caches::SingleCache<rustc_middle[14964323be5c6d14]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[fe0de826094a3706]::plumbing::QueryCtxt, false>
  29:     0x751247cfd1f8 - rustc_query_impl[fe0de826094a3706]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  30:     0x751247fab580 - rustc_interface[76005b124f6a7e54]::passes::create_and_enter_global_ctxt::<core[52168106b816615d]::option::Option<rustc_interface[76005b124f6a7e54]::queries::Linker>, rustc_driver_impl[6daf40cdc4897975]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  31:     0x751247ec2504 - rustc_interface[76005b124f6a7e54]::interface::run_compiler::<(), rustc_driver_impl[6daf40cdc4897975]::run_compiler::{closure#0}>::{closure#1}
  32:     0x751247ea2d74 - std[30e4b062834ac322]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[76005b124f6a7e54]::util::run_in_thread_with_globals<rustc_interface[76005b124f6a7e54]::util::run_in_thread_pool_with_globals<rustc_interface[76005b124f6a7e54]::interface::run_compiler<(), rustc_driver_impl[6daf40cdc4897975]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  33:     0x751247ea31b4 - <<std[30e4b062834ac322]::thread::Builder>::spawn_unchecked_<rustc_interface[76005b124f6a7e54]::util::run_in_thread_with_globals<rustc_interface[76005b124f6a7e54]::util::run_in_thread_pool_with_globals<rustc_interface[76005b124f6a7e54]::interface::run_compiler<(), rustc_driver_impl[6daf40cdc4897975]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[52168106b816615d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x751247ea45ab - std::sys::pal::unix::thread::Thread::new::thread_start::h32ef7da320b5e71e
  35:     0x751241ca3708 - <unknown>
  36:     0x751241d27aac - <unknown>
  37:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.88.0-nightly (b4c8b0c3f 2025-04-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -Z validate-mir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0133, E0277, E0308.
For more information about an error, try `rustc --explain E0133`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes rust-lang/rust#121176
Fixes rust-lang/rust#129109
Fixes rust-lang/rust#130970
Fixes rust-lang/rust#131347 
Fixes rust-lang/rust#139872
Fixes rust-lang/rust#140332

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/operand.rs [hunk 1]
```diff
@@ -243,6 +243,17 @@ impl<'tcx, Prov: Provenance> std::ops::Deref for ImmTy<'tcx, Prov> {
 }
 
 impl<'tcx, Prov: Provenance> ImmTy<'tcx, Prov> {
+    #[inline(always)]
+    pub fn try_from_immediate(imm: Immediate<Prov>, layout: TyAndLayout<'tcx>) -> Option<Self> {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/operand.rs]: I'm not a fan of these functions. The point of the assertions is that they are a last line of defense to detect defective callers. They are *not* exhaustive checks. If the caller can't ensure that the value has the right type, that can only be fixed in the caller.

IOW, `matches_abi` here really is more of a `maybe_matches_abi`. It is necessary, but not sufficient. And trying to make it sufficient is the wrong approach; the right approach is figuring out why someone is feeding bogus data into these functions.

File: tests/ui/mir/static-by-value-dyn.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+//! Regression test for #121176
+//! KnownPanicsLint used to assert ABI compatibility in the interpreter,
+//! which ICEs with unsized statics.
+//@ needs-rustc-debug-assertions
+
+use std::fmt::Debug;
+
+static STATIC_1: dyn Debug + Sync = *();
```
Comment (RalfJung) [inline tests/ui/mir/static-by-value-dyn.rs:8]: For instance, this is a clearly ill-formed static. Nothing should ever look at its MIR. Trying to make the MIR interpreter APIs resistant against bogus MIR is a pointless game of whack-a-mole.

**Review by RalfJung — CHANGES_REQUESTED** [review]
These all seem to be standard cases of "ill-formed MIR gets too far into the pipeline". We should never run any MIR passes on ill-formed MIR; it is a waste of effort to try and fix this inside every individual pass.

**Comment by cjgillot** [comment]
> These all seem to be standard cases of "ill-formed MIR gets too far into the pipeline". We should never run any MIR passes on ill-formed MIR; it is a waste of effort to try and fix this inside every individual pass.

I agree, but fixing this is general is hard too. We have an `ImpossiblePredicates` pass to skip this kind of nonsense, but it is quite limited to avoid query cycles. And it cannot handle nonsense that spans multiple items.

A "cleaner" way would be to ensure we never produce a constant with mismatching ABI, be it as a `ConstValue` or as an `OpTy`. But that also clashes with the notion that miri should run on sensible code.

**Comment by RalfJung** [comment]
These are statics failing the "it must be sized" check. It's not some impossible where bound. I don't see what is so hard about marking them as tainted so nothing else ever touches them again. It's the exact same thing as a static whose initializer body is plainly ill-typed.

**Comment by cjgillot** [comment]
@RalfJung this latest version prevents creating the erroneous constants altogether. Do you agree with this version?

**Comment by RalfJung** [comment]
Yeah, that looks much better, thanks.

I'm not familiar with MIR building so I can't approve this on my own, however.

**Comment by cjgillot** [comment]
It's not ready yet. Just checking sizedness is not enough, as some non-sized types are OK too, like extern types. And using layout causes cycles.

**Comment by RalfJung** [comment]
Extern types can only work with extern statics, right?

And even then, that seems kind of cursed. Did we intentionally allow that or just forget to disallow it?

**Comment by cjgillot** [comment]
> Extern types can only work with extern statics, right?

Or inside pointers. And pointers to extern types are scalars.

> And even then, that seems kind of cursed. Did we intentionally allow that or just forget to disallow it?

It's intentional. We have a run-make test to verify this works.

**Comment by RalfJung** [comment]
Pointers to extern types are sized so there is no problem with them, those should just work.

**Comment by cjgillot** [comment]
The failing test is this one:
https://github.com/rust-lang/rust/blob/a7a1618e6c835f1f00940ad72203d05808209a0d/tests/run-make/static-extern-type/use-foo.rs#L3-L7

As a foreign type `Foo` is not sized, but `&Foo` and `*mut Foo` are still scalar. This is a special case in layout computation.

Checking whether `&T` is scalar in full generality requires either to call `layout_of`, or to open-code it. Internally, it normalizes `<T as Pointee>::Metadata` and compute that type's layout. The normalization process may try to normalize opaque types. This breaks https://github.com/rust-lang/rust/blob/master/tests/ui/coroutine/layout-error.rs

**Comment by RalfJung** [comment]
> The failing test is this one:

Yeah, that is a very odd test, I didn't think we'd allow extern statics with unknown size. Interestingly, we reject `static FOO2: [i32];` (as we have to).

What is not entirely clear to me is why we'd care about whether `&Foo` has metadata or not. Is that for constructing the pointer that represents the extern static access in MIR? As far as I can see, those pointers are *always* scalar, since statics with unsized types that require metadata are forbidden (and that makes sense; where would the metadata come from anyway).

**Comment by RalfJung** [comment]
All the issues referenced here seem to be about statics that are unsized-with-metadata. You can check for this without knowing the layout; just call `ptr_metadata_ty` on the type of the static. Statics can't be generic so this should always give you a definite answer.

This still has to normalize some things though, so that coroutine case could become interesting. But it's okay for that code to error, it just can't ICE.

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs [hunk 3]
```diff
@@ -88,8 +83,19 @@ pub(crate) fn as_constant_inner<'tcx>(
...
+            let const_ = if pointee.is_sized(tcx, typing_env) {
+                let const_val = ConstValue::Scalar(Scalar::from_pointer(alloc_id.into(), &tcx));
+                Const::Val(const_val, ty)
+            } else {
+                // Ill-formed code may produce instances where `pointee` is not `Sized`.
+                // This should be reported by wfcheck on the static itself.
+                // Still, producing a single scalar constant would be inconsistent, as pointers to
+                // non-`Sized` types are scalar pairs. Avoid an ICE by producing an error constant.
+                let guar =
+                    tcx.dcx().span_delayed_bug(span, format!("static's type `{ty}` is not Sized"));
```
Comment (RalfJung) [inline compiler/rustc_mir_build/src/builder/expr/as_constant.rs]:
```suggestion
                    tcx.dcx().span_delayed_bug(span, format!("static's type `{pointee}` is not Sized"));
```

**Comment by RalfJung** [comment]
Wouldn't an alternative be to change the type of the static itself to `TyKind::Error` after we determined that it's not a valid type for a static? Then we don't need patches like this all over the rest of the compiler.

Cc @oli-obk

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs [hunk 4]
```diff
@@ -88,8 +83,21 @@ pub(crate) fn as_constant_inner<'tcx>(
...
+            {
+                let const_val = ConstValue::Scalar(Scalar::from_pointer(alloc_id.into(), &tcx));
+                Const::Val(const_val, ty)
+            } else {
+                // Ill-formed code may produce instances where `pointee` is not `Sized`.
+                // This should be reported by wfcheck on the static itself.
+                // Still, producing a single scalar constant would be inconsistent, as pointers to
+                // non-`Sized` types are scalar pairs. Avoid an ICE by producing an error constant.
+                let guar =
+                    tcx.dcx().span_delayed_bug(span, format!("static's type `{ty}` is not scalar"));
```
Comment (RalfJung) [inline compiler/rustc_mir_build/src/builder/expr/as_constant.rs]: `ty` is not the type of the static, it's the type of a pointer to the static.

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs [hunk 5]
```diff
@@ -88,8 +83,21 @@ pub(crate) fn as_constant_inner<'tcx>(
             ConstOperand { user_ty: None, span, const_ }
         }
         ExprKind::StaticRef { alloc_id, ty, .. } => {
-            let const_val = ConstValue::Scalar(Scalar::from_pointer(alloc_id.into(), &tcx));
-            let const_ = Const::Val(const_val, ty);
+            let layout = tcx.layout_of(typing_env.as_query_input(ty));
+            let const_ = if let Ok(layout) = layout
+                && let BackendRepr::Scalar(..) = layout.backend_repr
```
Comment (RalfJung) [inline compiler/rustc_mir_build/src/builder/expr/as_constant.rs]: As noted before, I think the better approach would be to give the static an `Error` type -- otherwise, there might well be other consumers all over rustc that assume things about a `static`s type, that all need to get a fix like this.

File: tests/ui/coroutine/layout-error.rs
Comment (RalfJung) [inline tests/ui/coroutine/layout-error.rs:1]: @oli-obk is it okay for this to cycle-error? Having the *type* of a static depend on its value does seem quite cursed.^^

**Comment by oli-obk** [comment]
> Wouldn't an alternative be to change the type of the static itself to `TyKind::Error` after we determined that it's not a valid type for a static? Then we don't need patches like this all over the rest of the compiler.

that would mean moving these checks to `type_of`, which should be fine for static items, but are very cycle prone for other things

File: tests/ui/mir/static-by-value-dyn.rs (hunk 2 above)
Comment (oli-obk) [reply tests/ui/mir/static-by-value-dyn.rs:8]: yea those cases are straight forward to prevent within `type_of`, we don't even need to compute the layout, just doing a sizedness check.

Comment (RalfJung) [reply tests/ui/mir/static-by-value-dyn.rs:8]: That doesn't quite work since we allow extern statics that have extern types, which are unsized.

File: tests/ui/coroutine/layout-error.rs
Comment (oli-obk) [reply tests/ui/coroutine/layout-error.rs:1]: Is a static's type meaningfully different from a function's return type? Because it's not about its evaluated value, but just how opaque types work.

I don't think this use case is particularly unusual and expect people will want to be using TAITs like this.

File: compiler/rustc_mir_build/src/builder/expr/as_constant.rs (hunk 5 above)
Comment (cjgillot) [reply compiler/rustc_mir_build/src/builder/expr/as_constant.rs]: I tried that, and for some reason that was not enough to fix the ices. I did try to find why error tainting failed.

File: tests/ui/coroutine/layout-error.rs
Comment (RalfJung) [reply tests/ui/coroutine/layout-error.rs:1]: > Is a static's type meaningfully different from a function's return type?

Hm... not really, the problem is just that the constraint on the type cannot be so easily expressed as a trait query. For return types it's `T: Sized`, but for static types it's... `T: Pointee<Metadata = ()>` or so?

File: tests/ui/mir/static-by-value-dyn.rs (hunk 2 above)
Comment (oli-obk) [reply tests/ui/mir/static-by-value-dyn.rs:8]: Well, we can check the tail manually for slices and dyn trait

Comment (RalfJung) [reply tests/ui/mir/static-by-value-dyn.rs:8]: But that requires unfolding the type which will trigger the same cycle error, won't it?

**Comment by cjgillot** [comment]
> > Wouldn't an alternative be to change the type of the static itself to `TyKind::Error` after we determined that it's not a valid type for a static? Then we don't need patches like this all over the rest of the compiler.
> 
> that would mean moving these checks to `type_of`, which should be fine for static items, but are very cycle prone for other things

The latest commit tries that. I think it's worse because it breaks passing tests.

File: tests/ui/type-alias-impl-trait/type-alias-impl-trait-const.rs
Comment (RalfJung) [inline tests/ui/type-alias-impl-trait/type-alias-impl-trait-const.rs:1]: Hm... I don't think I understand why this fails, but I guess that's how type_alias_impl_trait works...?

File: tests/ui/coroutine/layout-error.rs [hunk 6]
```diff
@@ -17,6 +17,7 @@ impl<F: Future> Task<F> {
 }
 
 pub type F = impl Future;
```
Comment (oli-obk) [inline tests/ui/coroutine/layout-error.rs:19]:
```suggestion
pub type F = impl Future + Sync;
```

Needing an extra annotation for an opaque type in a static item seems fine to me

File: tests/ui/coroutine/metadata-sufficient-for-layout.rs [hunk 7]
```diff
@@ -23,5 +22,6 @@ mod helper {
 
 // Static queries the layout of the coroutine.
 static A: Option<helper::F> = None;
+//~^ ERROR cycle detected when computing type of `A`
```
Comment (oli-obk) [inline tests/ui/coroutine/metadata-sufficient-for-layout.rs]: Similarly here. Open an issue that this cycle diagnostic should propose adding the bound to the opaque. We'll fix that for TAITs but that shouldn't stop your PR

File: tests/ui/type-alias-impl-trait/type-alias-impl-trait-const.rs
Comment (oli-obk) [reply tests/ui/type-alias-impl-trait/type-alias-impl-trait-const.rs:1]: Yea, if we do use the "reveal opaque type to check the auto trait" logic, then this must cycle if we do it as a part of type_of. But if you are using a TAIT as the type of a static then it's not unreasonable to mark it as Sync, too.

Of course we could keep the Sync check out of the type_of code path and check it only in wfcheck like we did before this PR, but that'll be up to the lang team I guess?

Comment (RalfJung) [reply tests/ui/type-alias-impl-trait/type-alias-impl-trait-const.rs:1]: Ah I see. Yeah `Sync` can't influence layout so it's much less likely to ICE later parts of the compiler... but I'm fine either way.

**Review by oli-obk — APPROVED** [review]

File: compiler/rustc_hir_analysis/src/collect/type_of.rs [hunk 8]
```diff
@@ -217,7 +218,13 @@ pub(super) fn type_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> ty::EarlyBinder<'_
                         "static variable",
                     )
                 } else {
-                    icx.lower_ty(ty)
+                    let ty = icx.lower_ty(ty);
+                    // MIR relies on references to statics being scalars.
+                    // Verify that here to avoid ill-formed MIR.
+                    match check_static_item(tcx, def_id, ty, false) {
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/collect/type_of.rs:224]:
```suggestion
                    // Verify that here to avoid ill-formed MIR.
                    // We skip the `Sync` check to avoid cycles for type-alias-impl-trait,
                    // relying on the fact that non-Sync statics don't ICE the rest of the compiler.
                    match check_static_item(tcx, def_id, ty, /* should_check_for_sync */ false) {
```

File: compiler/rustc_hir_analysis/src/collect/type_of.rs [hunk 9]
```diff
@@ -275,7 +282,15 @@ pub(super) fn type_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> ty::EarlyBinder<'_
                 let args = ty::GenericArgs::identity_for_item(tcx, def_id);
                 Ty::new_fn_def(tcx, def_id.to_def_id(), args)
             }
-            ForeignItemKind::Static(t, _, _) => icx.lower_ty(t),
+            ForeignItemKind::Static(ty, _, _) => {
+                let ty = icx.lower_ty(ty);
+                // MIR relies on references to statics being scalars.
+                // Verify that here to avoid ill-formed MIR.
+                match check_static_item(tcx, def_id, ty, false) {
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/collect/type_of.rs:289]:
```suggestion
                // Verify that here to avoid ill-formed MIR.
                // We skip the `Sync` check to avoid cycles for type-alias-impl-trait,
                // relying on the fact that non-Sync statics don't ICE the rest of the compiler.
                match check_static_item(tcx, def_id, ty, /* should_check_for_sync */ false) {
```

File: compiler/rustc_hir_analysis/src/check/check.rs [hunk 10]
```diff
@@ -767,7 +767,8 @@ pub(crate) fn check_item_type(tcx: TyCtxt<'_>, def_id: LocalDefId) -> Result<(),
                 DefKind::Static { .. } => {
                     check_static_inhabited(tcx, def_id);
                     check_static_linkage(tcx, def_id);
-                    res = res.and(wfcheck::check_static_item(tcx, def_id));
+                    let ty = tcx.type_of(def_id).instantiate_identity();
+                    res = res.and(wfcheck::check_static_item(tcx, def_id, ty, true));
```
Comment (RalfJung) [inline compiler/rustc_hir_analysis/src/check/check.rs:771]:
```suggestion
                    res = res.and(wfcheck::check_static_item(tcx, def_id, ty, /* should_check_for_sync */ true));
```

**Review by RalfJung — COMMENTED** [review]
Just some minor comment nits, I can imagine this being quite confusing for someone who doesn't have the context we do right now.

@bors r-
(But we already got rolled up so this may have to be resolved in a follow-up PR.)

**Comment by RalfJung** [comment]
I'll submit a PR with the comments.
