### PR TITLE
libsyntax: be more accepting of whitespace in lexer

### LINKED ISSUE #29590: Lexer chokes on certain kinds of whitespace
The presence in a Rust source file of unusual but useful kinds of whitespace, such as ASCII 0x0C (form feed), leads to the following error:

    src/main.rs:1:1: 1:2 error: unknown start of token: \u{c}
    src/main.rs:1 
                  ^

I have a specific use case for form-feeds in source files. But I think in general it is nice to ignore the same whitespace that every other programming language and file format ignores; it lessens confusion for people coming from other languages and backgrounds.

My specific use case is the long-standing, but somewhat uncommon use of the form-feed character (which semantically is a separator between pages of text) as a way to group together especially closely related functions or blocks in a file of source code. Text editors or IDEs such as vim, Emacs or XCode provide convenience features to display these form-feeds in aesthetically pleasing way, move between form-feed-delimited pages, and restrict editing to one form-feed-delimited page at a time. It's just a simple convenience feature, but it would really be nice to support it.

### PR DESCRIPTION
**Pull request by Ryman**
Fixes #29590.

Perhaps this may need more thorough testing? 

r? @Aatch

### CODE REVIEW

File: src/libsyntax/util/parser_testing.rs [hunk 1]
```diff
@@ -83,69 +83,65 @@ pub fn strs_to_idents(ids: Vec<&str> ) -> Vec<ast::Ident> {
 
 /// Does the given string match the pattern? whitespace in the first string
 /// may be deleted or replaced with other whitespace to match the pattern.
-/// this function is Unicode-ignorant; fortunately, the careful design of
-/// UTF-8 mitigates this ignorance.  In particular, this function only collapses
-/// sequences of \n, \r, ' ', and \t, but it should otherwise tolerate Unicode
-/// chars. Unsurprisingly, it doesn't do NKF-normalization(?).
```
Comment (Aatch) [inline src/libsyntax/util/parser_testing.rs]: Probably should leave the rest of this comment in. The function is more unicode-aware now, but presumably still doesn't do any normalisation.

File: src/libsyntax/util/parser_testing.rs [hunk 2]
```diff
@@ -83,69 +83,65 @@ pub fn strs_to_idents(ids: Vec<&str> ) -> Vec<ast::Ident> {
...
-            idx_a = scan_for_non_ws_or_end(a,idx_a);
-        }
-        // *don't* silently eat ws in expected only.
-        else if char_at(a, idx_a) == char_at(b, idx_b) {
-            idx_a += 1;
-            idx_b += 1;
-        }
-        else {
-            return false;
+            (Some(a), Some(b)) => (a.clone(), b.clone())
```
Comment (Aatch) [inline src/libsyntax/util/parser_testing.rs]: This would probably be more clear with `(Some(&a), Some(&b)) => (a, b)` rather than the calls to `clone`, since `char` is `Copy`.

File: src/libsyntax/util/parser_testing.rs (hunk 1 above)
Comment (Ryman) [inline src/libsyntax/util/parser_testing.rs]:
```
/// This function is relatively Unicode-ignorant; fortunately, the careful design
/// of UTF-8 mitigates this ignorance. It doesn't do NKF-normalization(?).
``` 
Would be ok for you? Or just the normalization sentence?

**Comment by Aatch** [comment]
Test looks fine to me. r=me with the nits addressed.

File: src/libsyntax/util/parser_testing.rs (hunk 1 above)
Comment (Aatch) [inline src/libsyntax/util/parser_testing.rs]: That looks fine to me.

**Comment by eefriedman** [comment]
This is technically a new feature... probably doesn't need a full RFC, but shouldn't it at least be discussed a bit?

**Comment by Ryman** [comment]
Should we `r-` bors if there are concerns? 

cc @nikomatsakis  (who suggested accepting all whitespace in #29590)

**Comment by eefriedman** [comment]
I guess I don't really have any specific concerns; it's not like we could interpret a character of class whitespace as anything other than whitespace or an error.  We could end up with a sort of confusing parse with ZWNJs and other characters like that, but I don't see any reason not to allow users to inflict that on themselves.

**Comment by eefriedman** [comment]
Err, actually, correction, I do have a specific objection: UAX #31 specifically recommends not doing this.  We should be using the Pattern_White_Space property, not White_Space.

**Comment by Aatch** [comment]
Sorry, I guess I got a little too zealous there.

**Comment by nikomatsakis** [comment]
My bad. I should have known better than to think anything about unicode was a black-and-white decision!

**Comment by Ryman** [comment]
I've updated the branch to accept only `PATTERN_WHITE_SPACE`, I've assumed exposing more from librustc_unicode is fine due to it being unstable. 

The github diff doesn't seem to display the testfile too well, it shows as the below in my local git which shows the test more clearly:

```diff
-    assert_eq!(4 + 　7 * 2
-
+assert_eq!(4^L+

-/ 3 * 2 , 4 + 7 * 2 / 3 * 2);
+7   * 2<U+0085>/<U+200E>3<U+200F>*<U+2028>2<U+2029>, 4 + 7 * 2 / 3 * 2);
 }```

**Comment by steveklabnik** [comment]
What's the status of this PR?

**Comment by Ryman** [comment]
@steveklabnik Needs some feedback on if the changes are now ok, perhaps this change still needs more discussion though? Can rebase after that!

File: src/libsyntax/util/parser_testing.rs [hunk 3]
```diff
@@ -83,69 +83,67 @@ pub fn strs_to_idents(ids: Vec<&str> ) -> Vec<ast::Ident> {
...
+        } else if a == b {
+            a_iter.next();
+            b_iter.next();
+        } else {
+            return false
         }
     }
+
+    // check if a has *only* trailing whitespace
+    a_iter.all(|c| is_pattern_whitespace(c))
```
Comment (ranma42) [inline src/libsyntax/util/parser_testing.rs]: Is the closure needed? Wouldn't `a_iter.all(is_pattern_whitespace)` work just fine?

File: src/libsyntax/parse/lexer/mod.rs [hunk 4]
```diff
@@ -1366,11 +1367,10 @@ impl<'a> StringReader<'a> {
...
 
-pub fn is_whitespace(c: Option<char>) -> bool {
-    match c.unwrap_or('\x00') { // None can be null for now... it's not whitespace
-        ' ' | '\n' | '\t' | '\r' => true,
-        _ => false
-    }
+// This tests the character for the unicode property 'PATTERN_WHITE_SPACE' which
+// is guaranteed to be forward compatible. http://unicode.org/reports/tr31/#R3
+pub fn is_pattern_whitespace(c: Option<char>) -> bool {
+    c.map(Pattern_White_Space).unwrap_or(false)
```
Comment (ranma42) [inline src/libsyntax/parse/lexer/mod.rs]: How about `c.map_or(false, Pattern_White_Space)` ?

File: src/libsyntax/util/parser_testing.rs [hunk 5]
```diff
@@ -83,69 +83,67 @@ pub fn strs_to_idents(ids: Vec<&str> ) -> Vec<ast::Ident> {
...
-fn scan_for_non_ws_or_end(a : &str, idx: usize) -> usize {
-    let mut i = idx;
-    let len = a.len();
-    while (i < len) && (is_whitespace(char_at(a, i))) {
-        i += 1;
+/// Advances the given peekable `Iterator` until it reaches a non-whitespace character
+fn scan_for_non_ws_or_end<I: Iterator<Item= char>>(iter: &mut Peekable<I>) {
+    loop {
+        match iter.peek() {
+            Some(&c) if is_pattern_whitespace(c) => {} // fall through; borrowck
```
Comment (ranma42) [inline src/libsyntax/util/parser_testing.rs]: I would find something like
```Rust
    while lexer::is_pattern_whitespace(iter.peek().cloned()) {
        iter.next();
    }
```
more straightforward

File: src/librustc_unicode/tables.rs [hunk 6]
```diff
@@ -16,14 +16,19 @@
...
+fn bsearch_range_table(c: char, r: &'static [(char, char)]) -> bool {
     use core::cmp::Ordering::{Equal, Less, Greater};
     use core::slice::SliceExt;
-    r.binary_search_by(|&(lo,hi)| {
-        if lo <= c && c <= hi { Equal }
-        else if hi < c { Less }
-        else { Greater }
-    }).is_ok()
+    r.binary_search_by(|&(lo, hi)| {
+         if lo <= c && c <= hi {
```
Comment (ranma42) [inline src/librustc_unicode/tables.rs]: Would it make sense to restructure this function to
```Rust
    if c < lo {
        Greater
    } else if hi < c {
        Less
    } else {
        Equal
    }
```
?

The LLVM IR and the assembly from this version are much simpler and unfortunately we cannot rely on the compiler to optimise this much, as it would need to know that `lo <= high`.

Besides from simpler code, there might also be a performance reason why this would be good, although I believe this should not appear on any benchmark, as we are doing a binary search (which should involve few comparisons).
We are performing a search, so the `Equal` branch will be taken exactly once.
If the comparison function returns `Less` L times and `Greater` G times, the old code performs 2+3*L+3*G comparisons. The branch structure I proposed, instead, should perform L+2*G+2 comparisons.

Comment (Ryman) [inline src/librustc_unicode/tables.rs]: You might want to raise this in another PR/issue, this is generated code from `unicode.py` and the only differences here (for this function) are formatting which apparently didn't get pulled in from a formatting change in the past?

File: src/libsyntax/util/parser_testing.rs (hunk 5 above)
Comment (Ryman) [inline src/libsyntax/util/parser_testing.rs]: I agree, good catch!

I'll see if it passes borrowck whenever I rebase this branch (still need to know if we want the change _at all_ and if this is the approach to take or not)

**Comment by nikomatsakis** [comment]
@Ryman so it now conforms with UAX #31 (as cited by @eefriedman)?

**Comment by Ryman** [comment]
@nikomatsakis I think it partially does:

>Pattern_White_Space and Pattern_Syntax Characters: To meet this requirement, an implementation shall use Pattern_White_Space characters as all and only those characters interpreted as whitespace in parsing, and shall use Pattern_Syntax characters as all and only those characters with syntactic use. ...
>
>    Note: When meeting this requirement, all characters except those that have the Pattern_White_Space or Pattern_Syntax properties are available for use as identifiers or literals.

This PR doesn't change anything about the acceptance of Pattern_Syntax, so I don't think the final note is true, but it does bring us into alignment with the whitespace requirements of the guideline. (unless I've mis-implemented!)

**Comment by nikomatsakis** [comment]
@Ryman great!

**Comment by Ryman** [comment]
Rebased, I think I got all of your suggestions accounted for @ranma42 :)

**Comment by ranma42** [comment]
Yes, thank you! :)

**Comment by steveklabnik** [comment]
Triage: it seems this PR has been updated with review and is still siting here almost a month later, anyone willing to r+?

**Comment by alexcrichton** [comment]
r? @nikomatsakis 

was this intended to be r+'d? just confirming...

**Comment by Aatch** [comment]
Woops, looks like this managed to slip by.
