### PR TITLE
Normalize the type Self resolves to in an impl

### LINKED ISSUE #57796: ICE when using Self as uninitialized return type in trait method
```
trait FromUnchecked {
    unsafe fn from_unchecked(s: &str) -> Self;
}

impl FromUnchecked for [u8; 30] {
    unsafe fn from_unchecked(s: &str) -> Self {
        let mut array: Self = std::mem::uninitialized();
        let ptr = &mut array as *mut [u8] as *mut u8;
        std::ptr::copy_nonoverlapping(s.as_bytes().as_ptr(), ptr, s.len());
        std::ptr::write_bytes(ptr.add(s.len()), 0, 30 - s.len());
        array
    }
}

fn main() {
    let _: [u8; 30] = unsafe { FromUnchecked::from_unchecked("asdasd") };
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=53e2da580843961ccab6e0686c897bdb)

To make it compile you can simply replace `Self` for `[u8; 30]` in the `uninitialized` call ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=56c6b124419971f6fe2548d45e85f1bc))

```
 Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc/ty/sty.rs:2107: expected constant usize, got Const {
    ty: usize,
    val: Unevaluated(
        DefId(0/1:9 ~ playground[ec94]::{{impl}}[0]::{{constant}}[0]),
        []
    )
}

thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:495
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc::ty::sty::Const::unwrap_usize::{{closure}}
  15: <rustc_mir::transform::qualify_consts::Qualifier<'a, 'tcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_rvalue
  16: <rustc_mir::transform::qualify_consts::Qualifier<'a, 'tcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_assign
  17: <rustc_mir::transform::qualify_consts::QualifyAndPromoteConstants as rustc_mir::transform::MirPass>::run_pass
  18: rustc_mir::transform::run_passes::{{closure}}
  19: rustc_mir::transform::run_passes
  20: rustc_mir::transform::mir_validated
  21: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_validated<'tcx>>::compute
  22: rustc::dep_graph::graph::DepGraph::with_task_impl
  23: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  26: rustc_mir::borrow_check::mir_borrowck
  27: rustc::ty::query::__query_compute::mir_borrowck
  28: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute
  29: rustc::dep_graph::graph::DepGraph::with_task_impl
  30: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  32: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  33: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  34: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  35: rustc::util::common::time
  36: rustc::ty::context::tls::enter_context
  37: <std::thread::local::LocalKey<T>>::with
  38: rustc::ty::context::TyCtxt::create_and_enter
  39: rustc_driver::driver::compile_input
  40: rustc_driver::run_compiler_with_pool
  41: <scoped_tls::ScopedKey<T>>::set
  42: rustc_driver::run_compiler
  43: rustc_driver::monitor::{{closure}}
  44: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  45: rustc_driver::run
  46: rustc_driver::main
  47: std::rt::lang_start::{{closure}}
  48: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  49: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  50: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  51: main
  52: __libc_start_main
  53: <unknown>
query stack during panic:
#0 [mir_validated] processing `<[u8; _] as FromUnchecked>::from_unchecked`
#1 [mir_borrowck] processing `<[u8; _] as FromUnchecked>::from_unchecked`
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0 (9fda7c223 2019-01-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### LINKED ISSUE #58212: ICE on generic trait impl for aliased array type
Following snippet is sufficient to trigger an ICE on both stable 1.32 and nightly 1.34
```
use std::io::Read;
use std::default::Default;

trait MyRead: Sized {
    fn read<R: Read>(r: &mut R) -> Self;
}

type Foobar = [u8;10];

impl MyRead for Foobar {
    fn read<R: Read>(r: &mut R) -> Self {
        let mut result: Self = Default::default();
        r.read(&mut result[..]).unwrap();
        result
    }
}

fn main() {
}
```
## Meta
rustc 1.32.0 (9fda7c223 2019-01-16) running on x86_64-pc-windows-msvc

Backtrace:
```
    Checking rs_repro1 v0.1.0 (D:\Work\src\test\rs_repro1)
     Running `rustc --edition=2018 --crate-name rs_repro1 src\main.rs --color always --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=1fc4b6d5a86da623 -C extra-filename=-1fc4b6d5a86da623 --out-dir D:\Work\src\test\rs_repro1\target\debug\deps -C incremental=D:\Work\src\test\rs_repro1\target\debug\incremental -L dependency=D:\Work\src\test\rs_repro1\target\debug\deps`
error: internal compiler error: src\librustc\ty\sty.rs:2107: expected constant usize, got Const {
    ty: usize,
    val: Unevaluated(
        DefId(0/1:10 ~ rs_repro1[b69e]::Foobar[0]::{{constant}}[0]),
        []
    )
}

thread 'main' panicked at 'Box<Any>', src\librustc_errors\lib.rs:600:9
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
   4: std::panicking::rust_panic_with_hook
   5: <rustc_errors::diagnostic::SubDiagnostic as core::fmt::Debug>::fmt
   6: rustc_errors::Handler::bug
   7: rustc::util::ppaux::get_highlight_region_for_bound_region
   8: rustc::util::ppaux::verbose
   9: rustc::ty::context::tls::track_diagnostic
  10: rustc::util::ppaux::verbose
  11: rustc::util::bug::bug_fmt
  12: rustc::util::bug::bug_fmt
  13: <rustc_mir::util::liveness::IdentityMap<'a, 'tcx> as core::fmt::Debug>::fmt
  14: <rustc_mir::transform::qualify_consts::Qualifier<'a, 'tcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_rvalue
  15: <rustc_mir::transform::qualify_consts::Qualifier<'a, 'tcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_assign
  16: <rustc_mir::transform::qualify_consts::QualifyAndPromoteConstants as rustc_mir::transform::MirPass>::run_pass
  17: rustc_mir::transform::run_passes
  18: rustc_mir::transform::run_passes
  19: rustc_mir::transform::run_passes
  20: <rustc::traits::query::NoSolution as core::fmt::Debug>::fmt
  21: rustc::ty::context::tls::track_diagnostic
  22: rustc::dep_graph::graph::DepGraph::assert_ignored
  23: <rustc::traits::query::type_op::subtype::Subtype<'tcx> as rustc::traits::query::type_op::QueryTypeOp<'gcx, 'tcx>>::perform_query
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_print_query_stack
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_print_query_stack
  26: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_validated
  27: <rustc::mir::Location as rustc_mir::borrow_check::nll::type_check::NormalizeLocation>::to_locations
  28: <rustc::traits::query::NoSolution as core::fmt::Debug>::fmt
  29: <rustc::traits::query::NoSolution as core::fmt::Debug>::fmt
  30: rustc::ty::context::tls::track_diagnostic
  31: rustc::dep_graph::graph::DepGraph::assert_ignored
  32: <rustc::traits::query::type_op::subtype::Subtype<'tcx> as rustc::traits::query::type_op::QueryTypeOp<'gcx, 'tcx>>::perform_query
  33: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_print_query_stack
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_print_query_stack
  35: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  36: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  37: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  38: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  39: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  40: rustc_driver::driver::compile_input
  41: rustc_driver::run_compiler
  42: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  43: rustc_driver::run_compiler
  44: <humantime::duration::Error as std::error::Error>::cause
  45: _rust_maybe_catch_panic
  46: rustc_driver::profile::dump
  47: rustc_driver::main
  48: <unknown>
  49: std::panicking::update_panic_count
  50: _rust_maybe_catch_panic
  51: std::rt::lang_start_internal
  52: <unknown>
  53: <unknown>
  54: BaseThreadInitThunk
  55: RtlUserThreadStart
query stack during panic:
#0 [mir_validated] processing `<[u8; _] as MyRead>::read`
#1 [mir_borrowck] processing `<[u8; _] as MyRead>::read`
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0 (9fda7c223 2019-01-16) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `rs_repro1`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name rs_repro1 src\main.rs --color always --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=1fc4b6d5a86da623 -C extra-filename=-1fc4b6d5a86da623 --out-dir D:\Work\src\test\rs_repro1\target\debug\deps -C incremental=D:\Work\src\test\rs_repro1\target\debug\incremental -L dependency=D:\Work\src\test\rs_repro1\target\debug\deps` (exit code: 101)```

### PR DESCRIPTION
**Pull request by aoikonomopoulos**
This is required at the very least in order to evaluate associated
constants for arrays.

Fixes #57796 
Fixes #58212.

r? @oli-obk 
cc @hellow554

### CODE REVIEW

File: src/librustc_typeck/astconv.rs [hunk 1]
```diff
@@ -1700,7 +1700,7 @@ impl<'o, 'gcx: 'tcx, 'tcx> dyn AstConv<'gcx, 'tcx> + 'o {
                 // `Self` in impl (we know the concrete type).
                 assert_eq!(opt_self_ty, None);
                 self.prohibit_generics(&path.segments);
-                tcx.at(span).type_of(def_id)
+                self.normalize_ty(span, tcx.at(span).type_of(def_id))
```
Comment (oli-obk) [inline src/librustc_typeck/astconv.rs]: Add a comment so that we know we do this to normalize e.g. any unevaluated constants into their evaluated counterpart if possible.

Comment (aoikonomopoulos) [reply src/librustc_typeck/astconv.rs]: Would '// Try to evaluate any associated constants' be an accurate way of phrasing it?

**Comment by eddyb** [comment]
`normalize_ty` only does something in the `rustc_check::check::FnCtxt` implementation, so this is a reasonable bugfix (even if it should become irrelevant in the future).

@bors r+

File: src/librustc_typeck/astconv.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_typeck/astconv.rs]: It's not really associated constants. Maybe

```
// Try to evaluate array length constants
```

?

Comment (aoikonomopoulos) [reply src/librustc_typeck/astconv.rs]: Thanks.
