### PR TITLE
Unify const-checking structured errors for `&mut` and `&raw mut`

### LINKED ISSUE #77414: Feature `const_mut_refs` incorrectly suggested for the use of `raw_mut!` in `static`
I tried this code:

```rust
#![feature(const_raw_ptr_to_usize_cast)]
#![feature(const_mut_refs)]
#![feature(raw_ref_macros)]
#![no_std]

static mut X: u32 = 0;

static P: usize = unsafe { core::ptr::raw_mut!(X) as usize };
```

I expected to see this happen: The code either compiles successfully or fails to compile with a reasonable error message

Instead, this happened:

```
error[E0658]: `&raw mut` is not allowed in statics
 --> src/lib.rs:8:28
  |
8 | static P: usize = unsafe { core::ptr::raw_mut!(X) as usize };
  |                            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
  = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

But the code already includes `#![feature(const_mut_refs)]`.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (381b445ff 2020-09-29)
```

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #77414 as well as a FIXME.

### CODE REVIEW

File: src/test/ui/consts/const-address-of-mut.rs [hunk 1]
```diff
@@ -1,14 +1,14 @@
 #![feature(raw_ref_op)]
 
-const A: () = { let mut x = 2; &raw mut x; };           //~ ERROR `&raw mut` is not allowed
+const A: () = { let mut x = 2; &raw mut x; };           //~ mutable reference
```
Comment (davidtwco) [inline src/test/ui/consts/const-address-of-mut.rs:3]: Should this test's annotations still have `ERROR` in them?

```suggestion
const A: () = { let mut x = 2; &raw mut x; };           //~ ERROR mutable reference
```

**Review by davidtwco — APPROVED** [review]
LGTM, r=me after resolving previous comment

File: src/test/ui/consts/const-address-of-mut.rs (hunk 1 above)
Comment (ecstatic-morse) [reply src/test/ui/consts/const-address-of-mut.rs:3]: Why?

Comment (davidtwco) [reply src/test/ui/consts/const-address-of-mut.rs:3]: I was under the impression that it was required for the annotation.

Comment (Dylan-DPC) [reply src/test/ui/consts/const-address-of-mut.rs:3]: it's good to have but not a necessity iirc.
