### PR TITLE
Don't check for alias bounds in liveness when aliases have escaping bound vars

### LINKED ISSUE #117455: ICE: assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
### Code

Check out ICU4X (tested on commit https://github.com/unicode-org/icu4x/commit/582e46cd5bac851d25eea6188e5641ad99ce8a78), and build `components/locid_transform`

### Meta

`rustc --version --verbose`:
```
$ rustc +nightly --version --verbose
rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)
binary: rustc
commit-hash: 31bc7e2c47e82798a392c770611975a6883132c8
commit-date: 2023-10-30
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3

```

However this started happening in our nightly CI since `rustc 1.75.0-nightly (608e9682f 2023-10-29)` (one nightly before this one). The PR must have landed in the recent past.

### Error output

```
[09:51:33] मanishearth@manishearth-glaptop2 ~/dev/icu4x/components/locid_transform O_o 
$ cargo +nightly c
   Compiling syn v2.0.37
   Compiling synstructure v0.13.0
   Compiling zerofrom-derive v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom/derive)
   Compiling yoke-derive v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke/derive)
   Compiling zerovec-derive v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec/derive)
   Compiling displaydoc v0.2.4
   Compiling icu_provider_macros v1.3.2 (/home/manishearth/dev/icu4x/provider/macros)
    Checking zerofrom v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom)
    Checking yoke v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke)
    Checking zerovec v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec)
    Checking tinystr v0.7.4 (/home/manishearth/dev/icu4x/utils/tinystr)
    Checking icu_locid v1.3.2 (/home/manishearth/dev/icu4x/components/locid)
    Checking icu_provider v1.3.2 (/home/manishearth/dev/icu4x/provider/core)
    Checking icu_locid_transform v1.3.2 (/home/manishearth/dev/icu4x/components/locid_transform)
thread 'rustc' panicked at compiler/rustc_infer/src/infer/outlives/test_type_match.rs:46:5:
assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
stack backtrace:
   0:     0x7f8c3c812cfc - std::backtrace_rs::backtrace::libunwind::trace::h974857262e179b17
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f8c3c812cfc - std::backtrace_rs::backtrace::trace_unsynchronized::h6adce2053c056ac9
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8c3c812cfc - std::sys_common::backtrace::_print_fmt::hcf2018a5ad956761
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8c3c812cfc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3d39e48ce4d7e36f
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8c3c874f50 - core::fmt::rt::Argument::fmt::hef0ae15422a7f61d
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/fmt/rt.rs:142:9
   5:     0x7f8c3c874f50 - core::fmt::write::hf465a4ba34489409
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f8c3c806c1f - std::io::Write::write_fmt::hf34ad5986fa99e89
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/io/mod.rs:1763:15
   7:     0x7f8c3c812ae4 - std::sys_common::backtrace::_print::h5aa7f1d99916c125
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f8c3c812ae4 - std::sys_common::backtrace::print::h036d85b5c81889eb
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8c3c815777 - std::panicking::default_hook::{{closure}}::h9b311bcc8d2b2a40
  10:     0x7f8c3c8154df - std::panicking::default_hook::hd7a03fd029ce4ee2
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:292:9
  11:     0x7f8c398e06a0 - std[d7fc13cc5242579e]::panicking::update_hook::<alloc[46fb3a2f92666e24]::boxed::Box<rustc_driver_impl[88c66c37425cba72]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8c3c815eb8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h079168172b9ee18d
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2021:9
  13:     0x7f8c3c815eb8 - std::panicking::rust_panic_with_hook::h9ec5267af19ebd61
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:783:13
  14:     0x7f8c3c815bd9 - std::panicking::begin_panic_handler::{{closure}}::hded4ae2a191a7bae
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:649:13
  15:     0x7f8c3c8131c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h3b03f6ccd27da73f
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f8c3c815972 - rust_begin_unwind
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:645:5
  17:     0x7f8c3c871675 - core::panicking::panic_fmt::h290f6f1be63b094c
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/panicking.rs:72:14
  18:     0x7f8c3c871713 - core::panicking::panic::hac1e457063a02956
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/panicking.rs:127:5
  19:     0x7f8c3b9e68c5 - rustc_infer[fa218757abe60590]::infer::outlives::test_type_match::extract_verify_if_eq
  20:     0x7f8c3bbf112e - <core[53bdee0566a68c19]::iter::adapters::filter_map::FilterMap<core[53bdee0566a68c19]::iter::adapters::chain::Chain<rustc_middle[604fc891fd74f2d8]::ty::generic_args::IterInstantiated<&rustc_middle[604fc891fd74f2d8]::ty::list::List<rustc_middle[604fc891fd74f2d8]::ty::Clause>>, core[53bdee0566a68c19]::iter::adapters::copied::Copied<core[53bdee0566a68c19]::slice::iter::Iter<rustc_middle[604fc891fd74f2d8]::ty::Clause>>>, <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::generic_args::GenericArg>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty::{closure#0}> as core[53bdee0566a68c19]::iter::traits::iterator::Iterator>::next.cold.0
  21:     0x7f8c3ad5ba75 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  22:     0x7f8c3ad5ad00 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  23:     0x7f8c3ad5b438 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  24:     0x7f8c3b6fcb44 - rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::trace
  25:     0x7f8c3b37afbf - rustc_borrowck[1b2fc09ff996dd54]::type_check::type_check
  26:     0x7f8c3820b833 - rustc_borrowck[1b2fc09ff996dd54]::nll::compute_regions
  27:     0x7f8c3b7c384d - rustc_borrowck[1b2fc09ff996dd54]::do_mir_borrowck
  28:     0x7f8c3b7b3997 - rustc_borrowck[1b2fc09ff996dd54]::mir_borrowck
  29:     0x7f8c3b7b3557 - rustc_query_impl[688c8a72794c2a04]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[688c8a72794c2a04]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f8c3b212bd8 - rustc_query_system[92afb14951a5a4cf]::query::plumbing::try_execute_query::<rustc_query_impl[688c8a72794c2a04]::DynamicConfig<rustc_query_system[92afb14951a5a4cf]::query::caches::VecCache<rustc_span[88faddf4715d2d43]::def_id::LocalDefId, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[688c8a72794c2a04]::plumbing::QueryCtxt, true>
  31:     0x7f8c3b209ef3 - rustc_query_impl[688c8a72794c2a04]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  32:     0x7f8c3b20a648 - rustc_interface[90d65b0f51490bf6]::passes::analysis
  33:     0x7f8c3b209f35 - rustc_query_impl[688c8a72794c2a04]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[688c8a72794c2a04]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7f8c3b4f2844 - rustc_query_system[92afb14951a5a4cf]::query::plumbing::try_execute_query::<rustc_query_impl[688c8a72794c2a04]::DynamicConfig<rustc_query_system[92afb14951a5a4cf]::query::caches::SingleCache<rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[688c8a72794c2a04]::plumbing::QueryCtxt, true>
  35:     0x7f8c3b4f2520 - rustc_query_impl[688c8a72794c2a04]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  36:     0x7f8c3b743643 - std[d7fc13cc5242579e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[90d65b0f51490bf6]::util::run_in_thread_with_globals<rustc_interface[90d65b0f51490bf6]::interface::run_compiler<core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>, rustc_driver_impl[88c66c37425cba72]::run_compiler::{closure#1}>::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>
  37:     0x7f8c3b742909 - <<std[d7fc13cc5242579e]::thread::Builder>::spawn_unchecked_<rustc_interface[90d65b0f51490bf6]::util::run_in_thread_with_globals<rustc_interface[90d65b0f51490bf6]::interface::run_compiler<core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>, rustc_driver_impl[88c66c37425cba72]::run_compiler::{closure#1}>::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#1} as core[53bdee0566a68c19]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f8c3c820c85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he310d06a8f297797
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  39:     0x7f8c3c820c85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h69350f715ad37c20
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  40:     0x7f8c3c820c85 - std::sys::unix::thread::Thread::new::thread_start::h7310dea1d780d6a0
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f8c36ca63ec - start_thread
                               at ./nptl/pthread_create.c:444:8
  42:     0x7f8c36d26a4c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/manishearth/dev/icu4x/rustc-ice-2023-10-31T16_51_40-491262.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `expander::<impl at components/locid_transform/src/expander.rs:184:1: 184:20>::try_new_compat`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `icu_locid_transform` (lib)

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
[09:51:33] मanishearth@manishearth-glaptop2 ~/dev/icu4x/components/locid_transform O_o 
$ cargo +nightly c
   Compiling syn v2.0.37
   Compiling synstructure v0.13.0
   Compiling zerofrom-derive v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom/derive)
   Compiling yoke-derive v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke/derive)
   Compiling zerovec-derive v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec/derive)
   Compiling displaydoc v0.2.4
   Compiling icu_provider_macros v1.3.2 (/home/manishearth/dev/icu4x/provider/macros)
    Checking zerofrom v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom)
    Checking yoke v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke)
    Checking zerovec v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec)
    Checking tinystr v0.7.4 (/home/manishearth/dev/icu4x/utils/tinystr)
    Checking icu_locid v1.3.2 (/home/manishearth/dev/icu4x/components/locid)
    Checking icu_provider v1.3.2 (/home/manishearth/dev/icu4x/provider/core)
    Checking icu_locid_transform v1.3.2 (/home/manishearth/dev/icu4x/components/locid_transform)
thread 'rustc' panicked at compiler/rustc_infer/src/infer/outlives/test_type_match.rs:46:5:
assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
stack backtrace:

<snip>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/manishearth/dev/icu4x/rustc-ice-2023-10-31T16_51_40-491262.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `expander::<impl at components/locid_transform/src/expander.rs:184:1: 184:20>::try_new_compat`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `icu_locid_transform` (lib)

```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
I actually have no idea how we *should* be treating aliases with escaping bound vars here... but the simplest behavior is just doing what we used to do before.

r? aliemjay

Fixes #117455

### CODE REVIEW

**Comment by tmandry** [comment]
Friendly ping, this is breaking our build and I'd rather see a fix forward land soon.

If it helps: I haven't seen the code where this visitor is used, but the diff looks reasonable and the strategy of "do what we did before" sounds safe. If you're confident it's not horribly broken you can r=me.

**Comment by aliemjay** [comment]
I have thought about "smarter" solutions but they all turned to be incorrect (unsound?) because of the way we handle well-formedness around higher ranked types. Now I'm fairly convinced that the approach of this PR is the only way handle escaping bound vars.

Accordingly I'd prefer removing the FIXME comment and adding the following test to make sure we are not trying to do anthing smarter in this inference but you can r=me without these changes.

```rust
trait Trait {
    type Gat<'a: 'b, 'b: 'c, 'c>: 'c;
}

fn get_func<'a, T: Trait>(_: &'a str) -> fn(T::Gat<'a, '_, 'static>) {
    loop {}
}

fn test<T: Trait>() {
    let func = get_func::<T>(&String::new()); //~ ERROR temporary value dropped
    drop(func);
}
```

File: tests/ui/type-alias-impl-trait/alias-bounds-when-bounds-escape.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+struct MentionsLifetimeAndType<'a, T>(&'a (), T);
+
+fn foo<'a, 'b, T: Foo>(_: <T as Foo>::Assoc<'a, 'b>) {}
+
+fn test<'b, T: Foo>() {
+    let y: MentionsLifetimeAndType<'_, for<'a> fn(<T as Foo>::Assoc<'a, 'b>)> =
+        MentionsLifetimeAndType(&(), foo);
+}
+
+fn main() {}
```
Comment (lcnr) [inline tests/ui/type-alias-impl-trait/alias-bounds-when-bounds-escape.rs:16]: this test doesn't contain an opaque. Please add a comment referencing #117455 and one or two sentences explaining what this is testing

**Comment by compiler-errors** [comment]
Added aliemjay's test, added a comment and moved the original test cause it didn't have a TAIT anyways.

@bors r=aliemjay
