### PR TITLE
nontemporal_store: make sure that the intrinsic is truly just a hint

### LINKED ISSUE #114582: Non-temporal stores (and _mm_stream operations in stdarch) break our memory model
I recently discovered [this funny little intrinsic](https://doc.rust-lang.org/nightly/std/intrinsics/fn.nontemporal_store.html) with the great comment

> Emits a !nontemporal store according to LLVM (see their docs). Probably will never become stable.

Unfortunately, the comment is wrong: this *has* become stable, through vendor intrinsics like `_mm_stream_ps`.

Why is that a problem? Well, turns out non-temporal stores completely break our memory model. The following assertion can fail under the current compilation scheme used by LLVM:
```rust
static mut DATA: usize = 0;
static INIT: AtomicBool = AtomicBool::new(false);

thread::spawn(|| {
  while INIT.load(Acquire) == false {}
  assert_eq!(DATA, 42); // can this ever fail? that would be bad
});

nontemporal_store(&mut DATA, 42);
INIT.store(true, Release);
```
The assertion can fail because the CPU may order MOVNT after later MOV (for different locations), so the nontemporal_store might occur after the release store. Sources for this claim:
- [Peter Cordes answer here](https://stackoverflow.com/questions/44864033/make-previous-nt-stores-visible-to-subsequent-memory-loads-in-other-threads/44866652#44866652): "A mutex unlock on x86 is sometimes a lock add, in which case that's a full fence for NT stores already. But if you can't rule out a mutex implementation using a simple mov store then you need at least sfence at some point after NT stores, before unlock."
- glibc fixing their memcpy (which uses nontemporal stores) to have a [trailing sfence](https://github.com/lattera/glibc/commit/f6ed654cabb55cc809bde696ad8357498af39757).

This is a big problem -- we have a memory model that says you can use release/acquire operations to synchronize any (including non-atomic) memory accesses, and we have memory accesses which are not properly synchronized by release/acquire operations.

So what could be done?
- Remove nontemporal_store and implement the `_mm_stream` intrinsics without it and mark them as deprecated to signal that they don't match the expected semantics of the underlying hardware operation. People should use inline assembly instead and then it is their responsibility to have an sfence at the end of their asm block to restore expected synchronization behavior.
- Change the way release stores are compiled such that an sfence is emitted. This is mostly a theoretical option though: this is an ABI-breaking change, at least my understanding of the x86 ABI is that a regular mov is considered to be sufficient synchronization. To make this work reliably all compilers for all languages that have something like release writes need to emit the sfence, or else Rust code cannot be soundly linked with code produced by those other compilers.
- There's a third hypothetical option of adjusting our concurrency memory model to be able to support these operations. But that's (a) a huge design space -- which fences are supposed to interact how with this? We might even have to add a new kind of fence! And (b) modifying the C++ concurrency memory model should be done with utmost care and thorough formal analysis; the current model is the result of a decade worth of research that shouldn't be thrown away lightly.
- Just ignore the problem and hope it doesn't explode? I am not happy with this.

Thanks a lot to @workingjubilee and @the8472 for their help in figuring out the details of nontemporal stores.

Cc @rust-lang/lang @Amanieu 

Also see the [nomination comment here](https://github.com/rust-lang/rust/issues/114582#issuecomment-1670907861).

### PR DESCRIPTION
**Pull request by RalfJung**
The `!nontemporal` flag for stores in LLVM *sounds* like it is just a hint, but actually, it is not -- at least on x86, non-temporal stores need very special treatment by the programmer or else the Rust memory model breaks down. LLVM still treats these stores as-if they were normal stores for optimizations, which is [highly dubious](https://github.com/llvm/llvm-project/issues/64521). Let's avoid all that dubiousness by making our own non-temporal stores be truly just a hint, which is possible on some targets (e.g. ARM). On all other targets, non-temporal stores become regular stores.

~~Blocked on https://github.com/rust-lang/stdarch/pull/1541 propagating to the rustc repo, to make sure the `_mm_stream` intrinsics are unaffected by this change.~~

Fixes https://github.com/rust-lang/rust/issues/114582
Cc @Amanieu @workingjubilee

### CODE REVIEW

File: compiler/rustc_codegen_gcc/src/builder.rs [hunk 1]
```diff
@@ -1128,6 +1128,8 @@ impl<'a, 'gcc, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'gcc, 'tcx> {
         self.llbb().add_assignment(self.location, aligned_destination, val);
         // TODO(antoyo): handle align and flags.
         // NOTE: dummy value here since it's never used. FIXME(antoyo): API should not return a value here?
+        // When adding support for NONTEMPORAL, see see the LLVM backend for which
```
Comment (workingjubilee) [inline compiler/rustc_codegen_gcc/src/builder.rs:1131]:
```suggestion
        // When adding support for NONTEMPORAL, see the LLVM backend for which
```

File: compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs [hunk 2]
```diff
@@ -725,7 +725,8 @@ fn codegen_regular_intrinsic_call<'tcx>(
 
             // Cranelift treats stores as volatile by default
             // FIXME correctly handle unaligned_volatile_store
-            // FIXME actually do nontemporal stores if requested
+            // FIXME actually do nontemporal stores if requested (but see the LLVM backend for which
+            // architectures even allow this in a sane way)
```
Comment (workingjubilee) [inline compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs:729]: The cranelift or gcc backends could lawfully implement the stores by introducing implicit sfences that were then propagated forward by their InstCombine pass or similar, as I mentioned in the LLVM issue, like
```
[store !nt, sfence, store !nt, sfence, ..] => [store !nt, store !nt, sfence, ..]
```
I don't consider this insane. Perhaps complex? But this would both reap the benefits of these stores in actual programs and also solve the problem regarding the Rust memory model. So I would prefer we mention somewhere that there are *complex* but plausible options here even on x86, and what is important is that they *simply cannot* lower this *directly* to the nontemporal store instructions on some architectures.

Comment (RalfJung) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs:729]: The LLVM backend could do that too, no?

Comment (workingjubilee) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs:729]: Correct, there's nothing stopping LLVM from implementing that.

**Comment by Kobzol** [comment]
It's a bit sad if this becomes an actual no-op on x86, nontemporal stores can be (very rarely) very useful. Is this usable through anything else than [mm_stream_*](https://doc.rust-lang.org/beta/core/arch/x86_64/fn._mm_stream_si64.html) and friends? These functions already contain a safety note that a fence has to be used after them.

**Comment by workingjubilee** [comment]
> It's a bit sad if this becomes an actual no-op on x86, nontemporal stores can be (very rarely) very useful. Is this usable through anything else than [mm_stream_*](https://doc.rust-lang.org/beta/core/arch/x86_64/fn._mm_stream_si64.html) and friends? These functions already contain a safety note that a fence has to be used after them.

Those intrinsic functions are, in the latest commits to `std::arch`, internally assembly. They should behave identically to how they did before, please file a bug if they emit notably worse codegen. The distinction is that, in general, LLVM does not try to perform store deduplication into assembly code.

**Comment by Kobzol** [comment]
So mm_stream will still emit nontemporal instructions on x86? Thanks for clarifying!

File: compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs]: Okay so I added the comment there and made everything else reference that.

**Comment by Kobzol** [comment]
Ok, great, then I misunderstood this change, sorry!

**Comment by workingjubilee** [comment]
Thank you, @RalfJung.

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 3]
```diff
@@ -725,13 +725,29 @@ impl<'a, 'll, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
...
+                // stores, i.e., non-temporal stores that are equivalent to regular stores except
+                // for performance. LLVM doesn't seem to care about this, and will happily treat
+                // `!nontemporal` stores as-if they were normal stores (for reordering optimizations
+                // etc) even on x86, despite later lowering them to MOVNT which do *not* behave like
+                // regular stores but require special fences.
+                // So we keep a list of architectures where `!nontemporal` is known to be truly just
+                // a hint, and use regular stores everywhere else.
+                // (In the future, we could alternatively ensure that an sfence gets emitted after a sequence of movnt
+                // before any kind of synchronizing operation. But it's not clear how to do that with LLVM.)
+                const WELL_BEHAVED_NONTEMPORAL_ARCHS: &[&str] = &["aarch64", "arm"];
```
Comment (Amanieu) [inline compiler/rustc_codegen_llvm/src/builder.rs:738]: You can add riscv32 and riscv64 to this list.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/stdarch/pull/1541 has propagated, so this should be good to go. We haven't heard from @fmease though so let's re-roll the reviewer dice.

r? compiler

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 4]
```diff
@@ -727,13 +727,30 @@ impl<'a, 'll, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
...
+                // for performance. LLVM doesn't seem to care about this, and will happily treat
+                // `!nontemporal` stores as-if they were normal stores (for reordering optimizations
+                // etc) even on x86, despite later lowering them to MOVNT which do *not* behave like
+                // regular stores but require special fences.
+                // So we keep a list of architectures where `!nontemporal` is known to be truly just
+                // a hint, and use regular stores everywhere else.
+                // (In the future, we could alternatively ensure that an sfence gets emitted after a sequence of movnt
+                // before any kind of synchronizing operation. But it's not clear how to do that with LLVM.)
+                const WELL_BEHAVED_NONTEMPORAL_ARCHS: &[&str] =
+                    &["aarch64", "arm", "riscv32", "riscv64"];
```
Comment (jieyouxu) [inline compiler/rustc_codegen_llvm/src/builder.rs:741]: Question [REV1 (2/2)]: If I understand it correctly, the codegen test is modified such that it only codegens for `aarch64-unknown-linux-gnu` target, but here we have 4 "well-behaved" architectures that we do emit `!nontemporal` for.

File: tests/codegen/intrinsics/nontemporal.rs [hunk 5]
```diff
@@ -1,13 +1,28 @@
 //@ compile-flags: -O
+//@ compile-flags: --target aarch64-unknown-linux-gnu
+//@ needs-llvm-components: aarch64
```
Comment (jieyouxu) [inline tests/codegen/intrinsics/nontemporal.rs:3]: Question [REV1 (1/2)]: do we want to have revisions for:

- Each of the known "well-behaved" architectures (subject to availability of llvm components) where `!nontemporal` is emitted (i.e. `CHECK`)
- Examples of "naughty" architectures like x86_64 where `!nontemporal` is explicitly not emitted (i.e. `CHECK-NOT`)

So that we have both positive test cases where we emit `!nontemporal` and negative test cases where we resort to regular stores?

**Review by jieyouxu — APPROVED** [review]
Thanks! The changes themselves look good based on the prior discussions. Just a question about the codegen test with regards to target coverage.

**Comment by jieyouxu** [comment]
r? jieyouxu

File: tests/codegen/intrinsics/nontemporal.rs
Comment (jieyouxu) [inline tests/codegen/intrinsics/nontemporal.rs:1]: Suggestion: in this codegen test, we should probably also link to https://github.com/llvm/llvm-project/issues/64521 and #114582 for context.

File: tests/codegen/intrinsics/nontemporal.rs (hunk 5 above)
Comment (RalfJung) [reply tests/codegen/intrinsics/nontemporal.rs:3]: I don't think it makes sense to repeat the list of well-behaved architectures here.

But yeah I can add a variant for x86 to ensure we do not emit the flag there, that's a good point.

Comment (jieyouxu) [reply tests/codegen/intrinsics/nontemporal.rs]: Yeah, that seems fine to me!

File: tests/codegen/intrinsics/nontemporal.rs [hunk 6]
```diff
@@ -1,13 +1,37 @@
 //@ compile-flags: -O
+//@revisions: with_nontemporal without_nontemporal
+//@[with_nontemporal] compile-flags: --target aarch64-unknown-linux-gnu
+//@[with_nontemporal] needs-llvm-components: aarch64
+//@[without_nontemporal] compile-flags: --target x86_64-unknown-linux-gnu
+//@[without_nontemporal] needs-llvm-components: x86
 
-#![feature(core_intrinsics)]
+// Ensure that we *do* eomit the `!nonteporal` flag on architectures where it
```
Comment (jieyouxu) [inline tests/codegen/intrinsics/nontemporal.rs:8]: Nit: sorry this was bugging me 😄 
```suggestion
// Ensure that we *do* omit the `!nontemporal` flag on architectures where it
```

**Review by jieyouxu — APPROVED** [review]
Thanks, feel free to r=me,Amanieu,Jubilee after maybe fixing the nit :3

File: tests/codegen/intrinsics/nontemporal.rs [hunk 7]
```diff
@@ -1,13 +1,37 @@
 //@ compile-flags: -O
+//@revisions: with_nontemporal without_nontemporal
+//@[with_nontemporal] compile-flags: --target aarch64-unknown-linux-gnu
+//@[with_nontemporal] needs-llvm-components: aarch64
+//@[without_nontemporal] compile-flags: --target x86_64-unknown-linux-gnu
+//@[without_nontemporal] needs-llvm-components: x86
 
-#![feature(core_intrinsics)]
+// Ensure that we *do* omit the `!nontemporal` flag on architectures where it
+// is well-behaved, but do *not* emit it on architectures where it is ill-behaved.
```
Comment (jieyouxu) [inline tests/codegen/intrinsics/nontemporal.rs:9]: ... wait I'm so sorry, this is supposed to be "emit" right?

Comment (RalfJung) [reply tests/codegen/intrinsics/nontemporal.rs]: Ah yes, I should have checked the suggestion instead of just copying it.^^
