### PR TITLE
tip for define macro name after `macro_rules!`

### LINKED ISSUE #118295: Unhelpful error when macro_rules macro name is missing
### Code

```rust
macro_rules! {
    () => {};
}
```

### Current output

```console
error: cannot find macro `macro_rules` in this scope
 --> src/main.rs:1:1
  |
1 | macro_rules! {
  | ^^^^^^^^^^^
```

### Desired output

```console
error: `macro_rules` needs to be given a name for the macro you are defining
 --> src/main.rs:1:14
  |
1 | macro_rules! {
  |             ^ put a macro name here
```

### Rationale and extra context

The syntax for how an ident is given to `macro_rules!` is unlike any other macro invocation. New Rust users would typically have more experience calling macros (`println!`) before defining their own macros. There may be a period in which the bespoke `macro_rules` syntax is tricky to build muscle memory for.

### Other cases

When name of a function is omitted, this is still a better error than "cannot find 'fn' in this scope".

```rust
fn() {
}
```

```console
error: expected identifier, found `(`
 --> src/lib.rs:1:3
  |
1 | fn() {
  |   ^ expected identifier
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #118295

~Note that there are some bad case such as `﻿macro_rules![]` or `﻿macro_rules!()`. However, I think these are acceptable as they are likely to be seldom used (feel free to close this if you think its shortcomings outweigh its benefits)~

Edit: this problem was resolved by utilizing the `﻿source_map.span_to_next_source`.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1421,14 +1419,42 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                    while idx < chars.len() && chars[idx].is_ascii_whitespace() {
+                        idx += 1;
+                    }
+                    (idx < chars.len() && chars[idx] == '{').then_some(idx)
+                }
+            }
+        {
+            let bang_pos = ident.span.hi().0;
+            let lo = bang_pos + 1; // the pos after `!`
+            let hi = bang_pos + brace_offset as u32; // the pos of '{'
```
Comment (bvanjoi) [inline compiler/rustc_resolve/src/diagnostics.rs:1442]: It's safe because we have ensured the inclusion of `﻿!` and `{`

Comment (petrochenkov) [reply compiler/rustc_resolve/src/diagnostics.rs:1442]: This is not obvious, and the logic is now overcomplicated too much.
One single call to `span_extend_while` (or a similar method) to find where `!` ends is the maximum amount of logic that I'd want to see here from the cost/benefit point of view.

Comment (bvanjoi) [reply compiler/rustc_resolve/src/diagnostics.rs]: I think the current method simplifies the process while still preserving the tip

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 2]
```diff
@@ -1421,14 +1419,29 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             "",
         );
 
+        if macro_kind == MacroKind::Bang
+            && ident.name == sym::macro_rules
+            && let source_map = self.tcx.sess.source_map()
+            && let Ok(next_source) = source_map.span_to_next_source(ident.span)
+            && next_source.starts_with("!")
+            && let next = ident.span.with_hi(ident.span.hi() + BytePos(1))
+            && let Ok(span) = source_map.span_extend_while(next, |c| c.is_whitespace() || c == '{')
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1428]: I still don't understand why you are trying to search for `{`.

The difference between
```
LL | macro_rules! {
   | ^^^^^^^^^^^
```
and
```
LL | macro_rules! {
   | ^^^^^^^^^^^^
```
is not even visible unless you are looking *really* carefully.
In this case it's better to just always use `ident.span`.

And if you want a span for a `name` insertion suggestion, then a zero-length span immediately after `!` would be enough.

Comment (bvanjoi) [reply compiler/rustc_resolve/src/diagnostics.rs:1428]: > I still don't understand why you are trying to search for {

It's to prevent tips from being displayed under:

```rs
macro_rules![];
macro_rules!();
```

Comment (petrochenkov) [reply compiler/rustc_resolve/src/diagnostics.rs:1428]: But why, `macro_rules! foo (() => ());` is a legal way to define a macro.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/diagnostics.rs:1428]: `﻿macro_rules!` that is supposed to be an unresolved macro call and *not* a `macro_rules` item is also extremely rare, so it's not important what we do in that case, so we can optimize for the least amount of logic in the compiler.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 3]
```diff
@@ -1421,14 +1419,26 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             "",
         );
 
+        if macro_kind == MacroKind::Bang
+            && ident.name == sym::macro_rules
+            && let source_map = self.tcx.sess.source_map()
+            && let Ok(next_source) = source_map.span_to_next_source(ident.span)
+            && next_source.starts_with("!")
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:1426]: This condition is actually also redundant.
`macro_kind == MacroKind::Bang` means that the next token is `!` by definition (maybe after some whitespace, but that's fine).

Comment (bvanjoi) [reply compiler/rustc_resolve/src/diagnostics.rs:1426]: > maybe after some whitespace, but that's fine

```rs
// amazing it to work normally :)
macro_rules         !  something { () => {}}
```

**Comment by bvanjoi** [comment]
The fix is now quite straightforward. 

@rustbot ready

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
