### PR TITLE
Stabilise `c_unwind`

### LINKED ISSUE #74990: Tracking Issue for "C-unwind ABI", RFC 2945
This is a tracking issue for the RFC "C-unwind ABI" (rust-lang/rfcs#2945).

The feature gate for the issue is `#![feature(c_unwind)]`.

This RFC was created as part of the ffi-unwind project group tracked at https://github.com/rust-lang/lang-team/issues/19.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation notes

Major provisions in the RFC:

* [x] Add a `C-unwind` ABI and `system-unwind` (I think), we may need more variants.
* [ ] For external functions with the C ABI, we already (I believe) add the "nounwind" LLVM attributes when we build them. We want to continue doing this.
* [ ] For external functions with the C-unwind ABI, we do *not* want any such attributes.
* [ ] For Rust functions defined with the C ABI, e.g., `extern "C" fn foo() { ... }`, we want to force them to abort if there is a panic. The MIR helper function [`should_abort_on_panic`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir_build/build/fn.should_abort_on_panic.html) already exists and I think will modify the generated code to insert the required shims in such a case. They should also be marked as "nounwind" in LLVM, if they're not already. 
* [ ] Rust functions with the "C-unwind" ABI should **not** abort on panic.
* [ ] Use ABI to guide the "nounwind" attribute on callsites as well.
* [ ] Write suitable codegen tests to check generated LLVM IR.

### Unresolved Questions

None. The unresolved questions in the RFC were meant to be solved by future RFCs building on this one.

### Implementation history
* Initial implementation: https://github.com/rust-lang/rust/pull/76570
* Additional work (removing `#[unwind]`, adjusting panic handling): https://github.com/rust-lang/rust/pull/86155

### LINKED ISSUE #115285: `c_unwind` full stabilization request: change in `extern "C"` behavior
Tracking issue: #74990

This is a separate issue to enable using the FCP bot a second time. The request-for-stabilization comment is duplicated below, without modification.

RFC "C-unwind ABI": https://github.com/rust-lang/rfcs/pull/2945

Feature gate to be stabilized: `#![feature(c_unwind)]`

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #74990
Fix #115285 (that's also where FCP is happening)

Marking as draft PR for now due to `compiler_builtins` issues

r? @Amanieu

### CODE REVIEW

**Comment by kornelski** [comment]
I've updated the `mozjpeg` crate to use the `"C-unwind"` ABI, so the stabilization of aborting in "C" ABI is fine by me.

**Comment by Amanieu** [comment]
`compiler_builtins` is not being compiled with panic=abort, and `__umodti4` calls `specialized_div_rem` which is `extern "Rust"` and defined in a separate codegen unit.

I think https://github.com/rust-lang/rust/pull/113923 should resolve this, but I'm not 100% sure.

Alternatively we should ensure that `-Cpanic=abort -Coverflow-checks=off` is always passed when building compiler-builtins since this isn't currently the case.

**Comment by DianQK** [comment]
> I think #113923 should resolve this, but I'm not 100% sure.

From the error log, yes.

**Comment by nbdd0121** [comment]
Panic strategy and overflow checks are currently defined on Session, and if we want to force them for compiler builtins then we'll need to make them queries. Maybe instead of ad-hoc special cases we should just wait for #113923 to land first.

**Comment by bjorn3** [comment]
> Panic strategy and overflow checks are currently defined on Session, and if we want to force them for compiler builtins then we'll need to make them queries.

We also need to force an unlimited amount of codegen units for compiler-builtins to be compiled correctly. `-Zbuild-std` doesn't set all these things correctly for compiler-builtins, so it would be nice to have rustc handle this. Would also allow the panic_abort crate to always be built with panic=abort even without a rustc wrapper matching on the crate name.

**Comment by Dylan-DPC** [comment]
@nbdd0121 any updates on this?

**Comment by nbdd0121** [comment]
> @nbdd0121 any updates on this?

Still blocked by #113923

**Comment by nbdd0121** [comment]
I spent way too much time debugging the error today...

I couldn't reproduce the issue when compiling directly (with downloaded LLVM), but the issue is reproducible with both x86_64-gnu-llvm-16 and x86_64-gnu-llvm-17 containers.

This error looks identical to #116976 (https://github.com/llvm/llvm-project/issues/70578), and fix of which is to upgrade LLVM to 17.0.4. But the CI is using LLVM versions without the fix (I checked that the CI containers uses Ubuntu shipped LLVM 16.0.0 and 17.0.2, both of which I believe does not have the fix).

What should be done to get the CI to work? Perhaps we should disable noalias when LLVM version < 17.0.4?

cc @DianQK

**Comment by RalfJung** [comment]
Cc @nikic 
what are we usually doing when unpatched LLVM leads to segfaults due to miscompilation?

**Comment by nbdd0121** [comment]
> Could you try to revert this commit locally to verify that it is indeed the same issue?

Yes, I can confirm that reverting `[MemCpyOpt] Combine alias metadatas when replacing byval arguments (#70580)` will cause the sigsegv to trigger with locally built LLVM.

---

> Hm, this is a tricky case. Disabling noalias on older versions is a possibility, but it comes with it's own risks -- it's a big change in optimization behavior, which may surface other latent issues. We've seen this e.g. with the attempt to drop inbounds on getelementptr. I'd rather not rock the boat if we can avoid it, especially for old versions that receive little testing.

I think noalias probably is one of the safer attribute to disable, consider that we already disable it for `&!Freeze` and `&mut !Unpin` and clang rarely generates them.

> Something we should consider, especially to account for future cases where there might not be any workaround like "disable noalias", is to explicitly document additional patches that Rust requires if a certain system LLVM version is used. In that case we should change our llvm-N CI to build LLVM with the necessary patches ourselves.

This would be great, would it then require cooperation from distributions to ensure miscompilation bugs that affect us are backported to LLVM releases that they support?

---

I found a workaround which is to change `extern "C"` in library/proc_macro/src/bridge/buffer.rs to `extern "C-unwind"`, which inhibits some optimisation opportunity for LLVM that happens to mask the bug. However it feels very hacky to tweak source code so that LLVM happens to not miscompile, and I don't have the confidence that code in the wild wouldn't be misoptimised.

**Comment by cuviper** [comment]
> At least for Fedora's use case (cc @cuviper) I think we wouldn't mind if additional patches are required, as long as they're clearly documented.

In theory, that's fine, although I hope we can do it without ever requiring Rust-specific patches. Ideally it would always be limited to fixes from LLVM main that we know can be backported without affecting libLLVM ABI.

For this particular case, I think LLVM 16 would need a backport of https://github.com/llvm/llvm-project/pull/67539 and https://github.com/llvm/llvm-project/pull/70580, and I don't know if there's any further dependency.

> (I checked that the CI containers uses Ubuntu shipped LLVM 16.0.0 and 17.0.2, both of which I believe does not have the fix).
> 
> What should be done to get the CI to work?

It's disappointing that Ubuntu is apparently not even keeping up with LLVM point releases, but we could try asking them to update. And it will require backports on 16 too, but that shouldn't be a problem.

We could consider switching CI to Debian instead, since trixie is newer with 17.0.5 and 16.0.6, but again they would need more patches on 16. Or we can really change flavors and switch these to Fedora, especially since @nikic and I can do those updates as needed. :)

**Comment by DianQK** [comment]
> For this particular case, I think LLVM 16 would need a backport of [llvm/llvm-project#67539](https://github.com/llvm/llvm-project/pull/67539) and [llvm/llvm-project#70580](https://github.com/llvm/llvm-project/pull/70580), and I don't know if there's any further dependency.

If we can backport to LLVM 16, that's find for me. We only need the backport of https://github.com/llvm/llvm-project/pull/70580. Another optimization is only in LLVM 17 with https://github.com/llvm/llvm-project/commit/361464c027239a70d66fb7790032b23696d5b303.

**Comment by cuviper** [comment]
Well, the latter patch at least needs the definition of `combineAAMetadata` from the former.

**Comment by DianQK** [comment]
I found another alternative. We can introduce `optnone`.
When we find the function that was miscompiled, add the `optnone` attribute.

One example:

```rust
#[optnone(llvm_16)]
extern "C" fn reserve(b: Buffer, additional: usize) -> Buffer {
    let mut v = to_vec(b);
    v.reserve(additional);
    Buffer::from(v)
}
```

> The `optnone` is a function attribute of LLVM IR. It indicates that most optimization passes will skip this function, with the exception of interprocedural optimization passes.

**Comment by tgross35** [comment]
It seems like most of the failures are disk full or OOM, but there are a few interesting ones. Random selections:

- from https://crater-reports.s3.amazonaws.com/pr-116088/try%232b9b2b6df45a66f7b3c37b587bb1100d9ea1f02e/gh/19h.gx/log.txt
  ``error: the crate `proc_macro` requires panic strategy `unwind` which is incompatible with this crate's strategy of `abort` ``
- https://crater-reports.s3.amazonaws.com/pr-116088/try%232b9b2b6df45a66f7b3c37b587bb1100d9ea1f02e/reg/hornet-0.1.0/log.txt has a SIGBUS?
- https://crater-reports.s3.amazonaws.com/pr-116088/try%232b9b2b6df45a66f7b3c37b587bb1100d9ea1f02e/gh/BTCPrivateClassic.BTCPrivate-Classic/log.txt I think this is just an OK statement of fact
  `` [INFO] [stderr] panic in a function that cannot unwind ``

The proc macro strategy failure is the most interesting

**Comment by RalfJung** [comment]
> It seems like most of the failures are disk full or OOM,

Let's sieve those out...
@craterbot run mode=build-and-test crates=https://crater-reports.s3.amazonaws.com/pr-116088/retry-regressed-list.txt

**Comment by RalfJung** [comment]
@craterbot p=1

**Comment by nbdd0121** [comment]
> * from [crater-reports.s3.amazonaws.com/pr-116088/try%232b9b2b6df45a66f7b3c37b587bb1100d9ea1f02e/gh/19h.gx/log.txt](https://crater-reports.s3.amazonaws.com/pr-116088/try%232b9b2b6df45a66f7b3c37b587bb1100d9ea1f02e/gh/19h.gx/log.txt)
>   `` error: the crate `proc_macro` requires panic strategy `unwind` which is incompatible with this crate's strategy of `abort`  ``
>
> The proc macro strategy failure is the most interesting

Ah, this is caused by the hack cff15e8454f0eaea1909efafee7c238470220bee to get `proc_macro` crate to not miscompile in LLVM 16/17.

Since all standard libraries are only compiled once, using `C-unwind` API in them would prevent them from being linked with `-Cpanic=abort`. I guess I need either to seek another workaround, or we need to get the LLVM patch requirement sorted out...

**Comment by nbdd0121** [comment]
I switched to a different hack to workaround issue with LLVM < 17.0.4, which should prevent the panic strategy issue.

File: tests/codegen/debuginfo-inline-callsite-location.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@
 #![crate_type = "lib"]
 
 #[no_mangle]
-extern "C" fn add_numbers(x: &Option<i32>, y: &Option<i32>) -> i32 {
+extern "C-unwind" fn add_numbers(x: &Option<i32>, y: &Option<i32>) -> i32 {
```
Comment (Amanieu) [inline tests/codegen/debuginfo-inline-callsite-location.rs:23]: This seems like a bit of an arbitrary change. Is it needed for this test to pass?

Comment (nbdd0121) [reply tests/codegen/debuginfo-inline-callsite-location.rs:23]: Without this change there'll be terminate guards generated, so the `CHECK: tail call` above wouldn't match.

**Comment by Amanieu** [comment]
Changes LGTM, r=me once crater passes.

**Comment by RalfJung** [comment]
@craterbot run mode=build-and-test crates=https://crater-reports.s3.amazonaws.com/pr-116088/retry-regressed-list.txt p=1

**Comment by nbdd0121** [comment]
I looked into all failures:

For Git repos tested, most of the failure can be attributed to near_sdk and zcash, both of which panics in an `extern "C" function.

Other failures are:
* ns6251.spin-cookie-token-sample.c0e2276248d78c67fffda9e888d7462bb857de21
* FlixCoder.EvoResNN.b5d3825ca2213850060ed3d722795e99d96d6e0f
* GeneralSet.Set.612e3e22b509352b8ceac8453ed092e4c0daa89f
* InputUsername.rescrobbled.d9837ad4ddbe4f77a06c4f8a697d7d6df858e414
* U16A0-U16B9.tgrep.70b0e61fee3859c8d268a8d79e922760812211c7
* WiZLite.wisp.2f114b734e70e56708a67340b70d60e57a420c81
* adrien-zinger.dyn-timeout.10b63c9cc4f09a182f200628a439309fcc4628e7

For crates.io crates tested, the following are panicking in `extern "C"` function:
* ad9361-rs-0.1.0
* cashweb-secp256k1-0.19.1
* consistenttime-0.2.0
* http_desync_guardian-0.1.3
* lv2-worker-0.1.1
* mujs-0.0.3
* quest_bind-0.3.7
* sawp-ffi-0.12.1

The test in `command-fds` is flaky and is disabled: https://github.com/google/command-fds/commit/5608cdbb650feceb35f05338cbc01a7f94e67ead

Other failures are:
* casaubon-0.3.2
* extendr-api
* iota_stronghold-2.0.0
* latin_squares-0.1.2
* ringu-0.1.1
* timemoji-0.2.0

**Comment by nbdd0121** [comment]
I have triaged all crater failure and determined they are either flaky test, or broken crate, or are expected failure due to the change to enforce `extern "C"` to be nounwind.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/113923 is being [reverted](https://github.com/rust-lang/rust/pull/119885). Does that mean this PR is blocked again?

**Comment by DianQK** [comment]
> #113923 is being [reverted](https://github.com/rust-lang/rust/pull/119885). Does that mean this PR is blocked again?

We should be also able to fix it with specific optimizations.

File: compiler/rustc_middle/src/ty/layout.rs [hunk 2]
```diff
@@ -1180,6 +1180,21 @@ pub fn fn_can_unwind(tcx: TyCtxt<'_>, fn_def_id: Option<DefId>, abi: SpecAbi) ->
...
+        // functions, rustc will inject unwind guards to prevent unwind leaking out. This is
+        // normally okay, but for `compiler-builtins` crate it has the additional requirement to
+        // not call into libcore, so we *must not* generate such guards. One way to do it is to
+        // ensure those exported functions never call into unwindable functions, so we make
+        // every single function defined in compiler builtins nounwind.
+        //
+        // See rust-lang/compiler-builtins#578 for context.
+        if tcx.is_compiler_builtins(did.krate) && !tcx.is_foreign_item(did) {
+            return false;
+        }
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/layout.rs:1197]: FWIW, if this works I think it should be landed as a separate change, just in case it causes problems. The stabilization PR should only do stabilization and nothing else, ideally.

Comment (nbdd0121) [reply compiler/rustc_middle/src/ty/layout.rs:1197]: The issue is that since compiler_builtins crate currently don't have `c_unwind` feature enabled, landing this change separately is not really meaningful. Without stabilisation PR, we'll need to manual enable `c_unwind` feature in `compiler_builtins` for this to be effective, but doing so is arguably a bad idea since it breaks the crate for all older compiler versions.

Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1197]: > it breaks the crate for all older compiler versions.

I don't think that matters, the crate is very tied to latest nightly rustc.

Ideally the crate can opt-in to the new feature before it is stabilized, so that we can check if it actually works before landing the final PR.

**Comment by BatmanAoD** [comment]
Is this currently blocked? CI seems to be passing (🎉) but it looks like that doesn't include any checks with the MSVC toolchain.

**Comment by RalfJung** [comment]
@saethlin has recently improved how we deal with compiler-builtin's special linking needs. I wonder if that helps here? It should at least help in detecting problems. So it may be worth a rebase to run CI with the latest checks.

Maybe the entire "make everything rustc_nounwind" is not even needed any more.

File: compiler/rustc_middle/src/ty/layout.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1197]: > The issue is that since compiler_builtins crate currently don't have c_unwind feature enabled

Given that compiler_builtins is a critical crate when it comes to unwinding, and given that just enabling the feature gate has a side-effect (which is somewhat unconventional), I think that there absolutely should be a PR to compiler_builtins enabled this feature before we do a stabilization PR. That way we can explore what "stabilize this only for compiler_builtins" looks like. Everything else seems way too risky.

**Comment by saethlin** [comment]
It should not be _required_ but the attribute may provide some nice optimizations because MIR opts can know callers don't need landing pads.

File: compiler/rustc_middle/src/ty/layout.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1197]: Submitted https://github.com/rust-lang/compiler-builtins/pull/583 to do that.

**Comment by RalfJung** [comment]
The patch is definitely not needed, https://github.com/rust-lang/compiler-builtins/pull/583 passes CI.

> It should not be required but the attribute may provide some nice optimizations because MIR opts can know callers don't need landing pads.

Sure. But there's no reason to couple it to stabilizing the c_unwind feature, this can just be done independently.

**Comment by nbdd0121** [comment]
Great, thanks for testing out @RalfJung. I'll rebase the PR when I got time to do it, and see how the CI performs without the commit.

**Comment by RalfJung** [comment]
It might be worth perf-checking the update of compiler builtins with the feature in isolation, once my PR there lands.

**Comment by RalfJung** [comment]
compiler-builtins as used by rustc has the `c_unwind` feature now (since https://github.com/rust-lang/rust/pull/123719).

So I think this PR here can be rebased and all compiler-builtins-related changes removed, and then we are good to go?

**Comment by RalfJung** [comment]
Though before landing we may want to resolve https://github.com/rust-lang/rust/issues/123231.

**Comment by BatmanAoD** [comment]
Unless I'm misunderstanding, #123231 is a request for specification work, introducing a new guarantee that was not part of RFC 2945. I do not think it should block stabilizing the behavior that has already been specified, not least because it doesn't seem like there's a consensus in that thread about what the behavior should be and whether the implementation cost is worth it.

From my perspective, the value of the guarantee that unwinding through `extern "C"` causes an abort _far_ outweighs any potential confusion caused by inconsistency among platforms regarding cleanup code being run prior to the abort.

**Comment by RalfJung** [comment]
Yeah, that's fair. We currently don't document what exactly gets dropped or not when an unwind hits a frame that forces an abort, and that's still a lot better than the status quo.

Hoping this can be stabilized soon, then :)

**Comment by BatmanAoD** [comment]
@nbdd0121 Sorry for the ping, but do you know when you'll have a chance to look at the conflicts here?

**Comment by nbdd0121** [comment]
I'll rebase later this week

File: tests/codegen/debuginfo-inline-callsite-location.rs (hunk 1 above)
Comment (RalfJung) [reply tests/codegen/debuginfo-inline-callsite-location.rs:23]: A lot of other tests seem to have similar problems and you added `-C panic=abort` there. Why use a different approach here? Or is it a similar problem?

**Comment by RalfJung** [comment]
Based on [this comment](https://github.com/rust-lang/rust/pull/116088#issuecomment-1869650414) we can land this, though I have one last question. r=Amanieu,RalfJung once that is resolved.

**Comment by nbdd0121** [comment]
Sorry what do you want me to resolve?

**Comment by RalfJung** [comment]
<https://github.com/rust-lang/rust/pull/116088#discussion_r1623414388>

Thanks to GH for hiding that...

File: tests/codegen/debuginfo-inline-callsite-location.rs (hunk 1 above)
Comment (nbdd0121) [reply tests/codegen/debuginfo-inline-callsite-location.rs]: There's no particular reason. The other tests have a lot more extern functions so I used `-C panic=abort` instead of changing all of them to `C-unwind`. I have now fixed this test to also use `-C panic=abort`.

**Comment by RalfJung** [comment]
Awesome, let's finally land this. :)

@bors r=Amanieu,RalfJung

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/126126#issuecomment-2155285273

**Comment by BatmanAoD** [comment]
💔

**Comment by RalfJung** [comment]
The failing test has

https://github.com/rust-lang/rust/blob/ec2cc761bc7067712ecc7734502f703fe3b024c8/tests/ui/asm/aarch64/may_unwind.rs#L19-L21

so yeah that's just blatant UB.

**Comment by scovich** [comment]
> The failing test has
> 
> https://github.com/rust-lang/rust/blob/ec2cc761bc7067712ecc7734502f703fe3b024c8/tests/ui/asm/aarch64/may_unwind.rs#L19-L21
> 
> so yeah that's just blatant UB.

Am I understanding correctly, that this test can (only) be made correct if it specifies `extern "C-unwind"` ABI for that function?

**Comment by RalfJung** [comment]
Yeah, it should always have used C-unwind -- probably the test pre-dates that ABI.

**Comment by RalfJung** [comment]
Looks like another test needs adjusting?

File: tests/assembly/wasm_exceptions.rs [hunk 3]
```diff
@@ -8,10 +8,11 @@
 #![feature(core_intrinsics)]
 #![feature(rustc_attrs)]
```
Comment (RalfJung) [inline tests/assembly/wasm_exceptions.rs:9]: Looks like this feature can also be removed here?

**Comment by RalfJung** [comment]
r=Amanieu,RalfJung when CI is green.
Also, this has been waiting long enough, let's give it some priority.
@bors p=10 delegate+

**Comment by tgross35** [comment]
About time :) thanks for all the work on this @nbdd0121!!
