### PR TITLE
Do not suggest `.try_into()` on `i32::from(x)`

### LINKED ISSUE #63697: Compiler suggests unnecessary try into
I updated a dependency and the type of a struct field changed from an `i32` to a `u16`.

I am assigning a `u16` value to this struct field. Before, I was calling `i32::from` to convert the `u16` to an `i32`. With the upgrade this is unnecessary since the field  and the value are both `u16`.

The rust compiler suggests this fix:

```
error[E0308]: mismatched types
  --> artichoke-frontend/src/parser.rs:90:37
   |
90 |             (*self.parser).lineno = i32::from((*self.context).lineno);
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u16, found i32
help: you can convert an `i32` to `u16` and panic if the converted value wouldn't fit
   |
90 |             (*self.parser).lineno = i32::from((*self.context).lineno).try_into().unwrap();
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `artichoke-frontend`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

But it should really suggest removing the `i32::from` and using the `u16` directly.

### PR DESCRIPTION
**Pull request by estebank**
Fix #63697.

### CODE REVIEW

File: src/librustc_typeck/check/demand.rs [hunk 1]
```diff
@@ -587,6 +587,30 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 return false;
             }
         }
+        if let hir::ExprKind::Call(path, args) = &expr.node {
+            if let (
+                hir::ExprKind::Path(hir::QPath::TypeRelative(base_ty, path_segment)),
+                1,
+            ) = (&path.node, args.len()) {
+                // `expr` is a conersion like `u32::from(val)`, do not suggest anything (#63697).
```
Comment (jonas-schievink) [inline src/librustc_typeck/check/demand.rs]:
```suggestion
                // `expr` is a conversion like `u32::from(val)`, do not suggest anything (#63697).
```

File: src/test/ui/suggestions/mismatched-types-nunmeric-from.stderr [hunk 2]
```diff
@@ -0,0 +1,9 @@
+error[E0308]: mismatched types
+  --> $DIR/mismatched-types-nunmeric-from.rs:2:18
```
Comment (u32i64) [inline src/test/ui/suggestions/mismatched-types-nunmeric-from.stderr]: Filename typo: should be `mismatched-types-numeric-from.rs`.
