### PR TITLE
Prevent aborting guard from aborting the process in a forced unwind

### LINKED ISSUE #101469: pthread_exit no longer works in panic=abort
I tried this code:
https://rust.godbolt.org/z/M5Pz1rjnd

```rust
#![feature(c_unwind)]
#![no_main]
use std::ffi::{c_void, c_int, c_char};
use std::ptr::null_mut;

extern "C-unwind" {
    fn pthread_exit(v: *mut c_void) -> !;
}

#[no_mangle]
pub unsafe extern "C-unwind" fn main(_argc: c_int, _argv: *mut *mut c_char) {
    unsafe {pthread_exit(null_mut())}
}
```

I expected to see this happen: exits with exit code 0 as documented for `pthread_exit`

Instead, this happened: aborts with double panic

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (8c6ce6b91 2022-09-02)
binary: rustc
commit-hash: 8c6ce6b91b172f77c795a74bfeaf74b865146b3f
commit-date: 2022-09-02
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

sorry, i can't figure out how to get a backtrace from godbolt.org, it doesn't seem to allow setting environment variables.

This bug serms to be caused by #96959

@rust-lang/wg-ffi-unwind

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #101469

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/traits/builder.rs [hunk 1]
```diff
@@ -272,6 +272,7 @@ pub trait BuilderMethods<'a, 'tcx>:
 
     // These are used by everyone except msvc
     fn cleanup_landing_pad(&mut self, pers_fn: Self::Value) -> (Self::Value, Self::Value);
+    fn filter_landing_pad(&mut self, pers_fn: Self::Value) -> (Self::Value, Self::Value);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/traits/builder.rs:275]: What is the difference between cleanup and filter? How should a backend implement it?

Comment (nbdd0121) [reply compiler/rustc_codegen_ssa/src/traits/builder.rs:275]: It's purely metadata in LSDA. https://itanium-cxx-abi.github.io/cxx-abi/exceptions.pdf

A negative value in action record means filter, a positive value means catch, and zero (or absence of action record) means cleanup.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/traits/builder.rs:275]: This corresponds to section 7.5 "Exception Specification" of that document?

Comment (nbdd0121) [reply compiler/rustc_codegen_ssa/src/traits/builder.rs:275]: Yeah. I call it `filter` because that's how LLVM calls it.

The code here doesn't actually specify any exceptions (corresponds to C++ `throw()`), so it's essentially catch-all. But it provides a way for the personality function to distinguish terminate vs cleanup.

File: compiler/rustc_codegen_gcc/src/builder.rs [hunk 2]
```diff
@@ -1226,6 +1226,10 @@ impl<'a, 'gcc, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'gcc, 'tcx> {
         (value1, value2)
     }
 
+    fn filter_landing_pad(&mut self, pers_fn: RValue<'gcc>) -> (RValue<'gcc>, RValue<'gcc>) {
+        self.cleanup_landing_pad(pers_fn)
```
Comment (Amanieu) [inline compiler/rustc_codegen_gcc/src/builder.rs:1230]: This seems incorrect?

File: compiler/rustc_codegen_llvm/src/builder.rs [hunk 3]
```diff
@@ -988,6 +988,13 @@ impl<'a, 'll, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'll, 'tcx> {
         (self.extract_value(landing_pad, 0), self.extract_value(landing_pad, 1))
     }
 
+    fn filter_landing_pad(&mut self, pers_fn: &'ll Value) -> (&'ll Value, &'ll Value) {
+        let ty = self.type_struct(&[self.type_i8p(), self.type_i32()], false);
+        let landing_pad = self.landing_pad(ty, pers_fn, 1 /* FIXME should this be 0? */);
```
Comment (Amanieu) [inline compiler/rustc_codegen_llvm/src/builder.rs:993]: Regarding the FIXME here: the number is a hint with the number of clauses to reserve space for (like `Vec::with_capacity`). 1 is the correct value to use here since we are only adding 1 clause.

Comment (nbdd0121) [reply compiler/rustc_codegen_llvm/src/builder.rs:993]: So the value for cleanup above should be 0?

File: compiler/rustc_codegen_gcc/src/builder.rs (hunk 2 above)
Comment (nbdd0121) [reply compiler/rustc_codegen_gcc/src/builder.rs:1230]: The proper way to encode this in GCC would be `<<<eh_filter (NULL)>>>` (or even better, `<<<eh_must_not_throw (terminate)>>>`, which is something we hoped for for LLVM!). But I don't think there is support in libgccjit yet, @antoyo to confirm?

**Comment by Amanieu** [comment]
r=me after double-checking the GCC changes with @antoyo.

File: compiler/rustc_codegen_gcc/src/builder.rs (hunk 2 above)
Comment (antoyo) [reply compiler/rustc_codegen_gcc/src/builder.rs:1230]: Yeah, I'll take care of this. I'm not done with supporting unwinding yet.

But, please add a `// TODO(antoyo): generate the correct landing pad`.

For my personal information, what are `<<<eh_filter (NULL)>>>` and `<<<eh_must_not_throw (terminate)>>>`? I've never seen this syntax. Are they C attributes?

I don't remember exactly what `filter` is doing, but the proper implementation of this method might be very similar as `cleanup_landing_pad`, but without adding to `self.cleanup_blocks`.

Comment (nbdd0121) [reply compiler/rustc_codegen_gcc/src/builder.rs:1230]: These are part of generic/gimple: https://godbolt.org/z/5adjbahnd

**Comment by nbdd0121** [comment]
The failed test is touched in #109394. cc @krasimirgg, @nikic

This PR changes codegen for terminating/aborting guard to move away from `cleanup`, which prevents LLVM from outsmarting us in regard to double panic. Should I just revert the affected test?

I think this test should also fix the double panic case in #109672, but doesn't resolve the more general issue of non-resuming cleanups.

**Comment by nikic** [comment]
@nbdd0121 The test changes are only for LLVM 17, so shouldn't be relevant here. I think the problem might just be that the cleanup label got renamed to terminate?

**Comment by nbdd0121** [comment]
Oh, I see. It's not the label. The test is checking for `cleanup attribute`, but that's now `filter [0 x ptr] zeroinitializer`.

**Comment by Amanieu** [comment]
A thought occurs: if we can detect in phase 1 that we're going to hit a filter, could we skip unwinding entirely and just return an error in phase1? This would be handled in `std` to abort immediately.

This would allow the landing pad itself to just be `unreachable` (maybe with a `llvm.sideffect`), which would reduce code size.

**Comment by nbdd0121** [comment]
> A thought occurs: if we can detect in phase 1 that we're going to hit a filter, could we skip unwinding entirely and just return an error in phase1? This would be handled in `std` to abort immediately.
> 
> This would allow the landing pad itself to just be `unreachable` (maybe with a `llvm.sideffect`), which would reduce code size.


Yes, I already code locally that going to do it. But that's a logically different change (and change the behaviour), so it warrants a separate PR and perhaps a FCP. This one is a bug fix.

**Comment by nbdd0121** [comment]
My actual plan is that: in phase 1 unwind, if we detect this is this `UnwindAction::Terminate`, then if the exception is a Rust exception, then set a flag inside to indicate that there's a nounwind frame and then return an error. The exception raising code would then inspect that flag upon unwind error, and report diagnostics accordingly.

**Comment by bjorn3** [comment]
If the exception doesn't come from Rust it would have to be handled in a different way, right?

**Comment by Amanieu** [comment]
I think we can just return `_URC_END_OF_STACK` in phase1. This will cause C++ to call `std::terminate` and for Rust we can abort with a nicer message.

**Comment by nbdd0121** [comment]
@Amanieu is there anything blocking the approval of this PR? I'll submit the behaviour change in a separate PR after this one lands (because that'll depend on the new `EHAction::Filter`).

**Comment by Amanieu** [comment]
Oops, I'd forgotten that this was assigned to me.

@bors r+

File: tests/run-make/forced-unwind-terminate-pof/foo.rs [hunk 4]
```diff
@@ -0,0 +1,17 @@
+// Tests that forced unwind through POF Rust frames wouldn't trigger our terminating guards.
```
Comment (Amanieu) [inline tests/run-make/forced-unwind-terminate-pof/foo.rs:1]: It would be nice to have a Windows version of this test that uses `longjmp`. On Windows `longjmp` is implemented using SEH exceptions and effectively acts like a forced unwind.

Comment (nbdd0121) [reply tests/run-make/forced-unwind-terminate-pof/foo.rs:1]: We already have a test longjmp-across-rust added by #48572 to fix #48251

**Comment by nbdd0121** [comment]
Somehow a commit from my other (already merged) PR was mixed in. Fixed
