### PR TITLE
require type defaults to be after const generic parameters

### LINKED ISSUE #70471: const_generics with default arguments
Should the following code be accepted?
```rust
// compiles rn
#![feature(const_generics)]

struct A<T = u32, const N: usize> {
    arg: T,
}

type C = A<u32, 7>;
```
if so, we probably also want to accept the following:
```rust
// this currently fails
type B = A<7>;
//~^ ERROR constant provided when a type was expected
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a80b3b2c8ebe0860a4ea9d1faae1d581)

cc @varkor @eddyb

### PR DESCRIPTION
**Pull request by lcnr**
From current discussions it seems like the goal here is for type and const parameters to be unordered and allow things like `struct Foo<const N: usize, T = u32>(T)` and `struct Foo<T, const N: usize = 7>` this way.

Note: This means that using `min_const_generics` it will not be possible for an adt to have both type defaults and const parameters.

closes #70471

r? @varkor @eddyb

### CODE REVIEW

File: src/librustc_ast_passes/ast_validation.rs [hunk 1]
```diff
@@ -1118,13 +1118,26 @@ impl<'a> Visitor<'a> for AstValidator<'a> {
...
+                GenericParamKind::Type { .. } | GenericParamKind::Const { .. } => {
+                    if let Some(span) = prev_ty_default {
+                        let mut err = self.err_handler().struct_span_err(
+                            span,
+                            "type parameters with a default must be trailing",
+                        );
+                        if matches!(param.kind, GenericParamKind::Const { .. }) {
+                            err.note(
+                                "using type defaults and const parameters \
+                                 in the same parameter listing is currently not possible",
```
Comment (varkor) [inline src/librustc_ast_passes/ast_validation.rs:1135]:
```suggestion
                                 in the same parameter list is currently not permitted",
```

**Comment by varkor** [comment]
r=me after wording tweak for consistency.
