### PR TITLE
build_helper: fix yarn locking, add check, and bump lockfile

### LINKED ISSUE #154446: Yarn install isn't actually frozen
### Summary

In #148763, we switched to using yarn1 to install JS deps for the rustdoc-gui suite. This was motivated by wanting to ensure packages would be locked. Unfortunatly that's not the case.

### Command used

```sh
./x test ./tests/rustdoc-gui/go-to-collapsed-elem.goml
```

### Expected behaviour

`yarn.lock` and `./build/host/test/rustdoc-gui/yarn.lock` have the same contents.

### Actual behaviour

They don't. 

```
$ md5sum yarn.lock  ./build/host/test/rustdoc-gui/yarn.lock
74649b371fd0dcb143ea171d11075918  yarn.lock
2b895cd885819933c18bea54155476c2  ./build/host/test/rustdoc-gui/yarn.lock
```

We use `yarn install --frozen`

https://github.com/rust-lang/rust/blob/23903d01c237d7c7d4fb62b82ca846bc45de4e0c/src/build_helper/src/npm.rs#L19-L22

But that's not the right flag, it should be [`--frozen-lockfile`](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile).

For some reason, by default, yarn doesn't do a frozen install. And it doesn't error on unknown flags, so it'll silently ignore the lockfile:

```
gh-aDotInTheVoid@dev-desktop-eu-2:~/rust0$ git checkout yarn.lock && rm -rf ./node_modules && ~/.local/bin/yarn install --this-definly-isnt-a-valid-flag
Updated 0 paths from the index
yarn install v1.22.22
warning package.json: License should be a valid SPDX license expression
warning License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
warning bare-fs@4.5.0: The engine "bare" appears to be invalid.
warning bare-os@3.6.2: The engine "bare" appears to be invalid.
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
success Saved lockfile.
Done in 1.94s.
gh-aDotInTheVoid@dev-desktop-eu-2:~/rust0$ git status
On branch main
Your branch is ahead of 'origin/main' by 1955 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
gh-aDotInTheVoid@dev-desktop-eu-2:~/rust0$ md5sum yarn.lock  ./build/host/test/rustdoc-gui/yarn.lock
2b895cd885819933c18bea54155476c2  yarn.lock
2b895cd885819933c18bea54155476c2  ./build/host/test/rustdoc-gui/yarn.lock
```

If use the right flag here, yarn errors that the lockfile needs updating (for unclear reasons):

```
gh-aDotInTheVoid@dev-desktop-eu-2:~/rust0$ git checkout yarn.lock && rm -rf ./node_modules && ~/.local/bin/yarn install --frozen-lockfile
Updated 1 path from the index
yarn install v1.22.22
warning package.json: License should be a valid SPDX license expression
warning License should be a valid SPDX license expression
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Bootstrap configuration (bootstrap.toml)
```toml
profile = "compiler"  # Includes one of the default files in src/bootstrap/defaults
# Not using download-rustc until https://github.com/rust-lang/rust/pull/154394 merges

change-id = 153143

[build]
yarn = "/home/gh-aDotInTheVoid/.local/bin/yarn"
```

### Operating system

Ubuntu 24.04.3 LTS

### HEAD

212ef7770dfad656782207fda799bdae28fc5b7b

### Additional context

```
$ ~/.local/bin/yarn --version
1.22.22
```

CC @lolbinarycat @yotamofek . The right solution is probably to update the lockfile to something installable, then to use the `--frozen-lockfile` flag (and maybe add a sanity check that the lockfile hasn't changed)

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes rust-lang/rust#154446

cc @aDotInTheVoid, @GuillaumeGomez 

not sure if this needs review from t-rustdoc, t-bootstrap, or both.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

File: src/build_helper/src/npm.rs [hunk 1]
```diff
@@ -38,5 +38,13 @@ pub fn install(src_root_path: &Path, out_dir: &Path, yarn: &Path) -> Result<Path
             "yarn install returned exit code {exit_status}"
         ))));
     }
+    if env::var("BOOTSTRAP_SKIP_YARN_LOCK_CHECK").is_err()
```
Comment (jieyouxu) [inline src/build_helper/src/npm.rs:41]: Q: is this env var documented anywhere?

Comment (lolbinarycat) [reply src/build_helper/src/npm.rs:41]: Not outside the error message in the same file, no.

Comment (lolbinarycat) [reply src/build_helper/src/npm.rs:41]: I wasn't sure if it needed documenting given that hopefully noone will ever encounter a situation where it is needed.

Comment (lolbinarycat) [reply src/build_helper/src/npm.rs:41]: There's also a lot of much less niche env variables used by bootstrap that are not documented, even by the program's output, such as `DUMP_BOOTSTRAP_SHIMS`.  Now, maybe those *should* be documented, and this envar too, but that was my reasoning.

Comment (jieyouxu) [reply src/build_helper/src/npm.rs:41]: Oh sorry, I was missing that the error message mentions the env var itself, that's fine then.

**Review by jieyouxu — APPROVED** [review]
`build_helper` changes LGTM, thanks
@bors r=GuillaumeGomez,jieyouxu rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154641/e4fdb554ad2c0270473181438e338c42b5b30b0c..f0c7cd28b8d8eb7f9a1bb48df1a0f9c049af5677)*
