### PR TITLE
Normalize opaques w/ bound vars

### LINKED ISSUE #2433: ICE: Failed to normalize <[closure] as std::ops::FnOnce<(&S,)>>::Output
code from rustc `./src/test/ui/type-alias-impl-trait/issue-72793.rs`

````rust
// check-pass
// compile-flags: -Zmir-opt-level=3

#![feature(type_alias_impl_trait)]

trait T { type Item; }

type Alias<'a> = impl T<Item = &'a ()>;

struct S;
impl<'a> T for &'a S {
    type Item = &'a ();
}

fn filter_positive<'a>() -> Alias<'a> {
    &S
}

fn with_positive(fun: impl Fn(Alias<'_>)) {
    fun(filter_positive());
}

fn main() {
    with_positive(|_| ());
}
````

````
WARNING: Ignoring `RUSTC_WRAPPER` environment variable, Miri does not support wrapping.
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/m`
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:199:90: Failed to normalize <[closure@src/main.rs:24:19: 24:22] as std::ops::FnOnce<(&S,)>>::Output, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/compiler/rustc_errors/src/lib.rs:1392:9
stack backtrace:
   0:     0x7f7fc64a37a0 - std::backtrace_rs::backtrace::libunwind::trace::h763ecd2b1c94eb47
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f7fc64a37a0 - std::backtrace_rs::backtrace::trace_unsynchronized::h7346e33da5e91dc9
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7fc64a37a0 - std::sys_common::backtrace::_print_fmt::h8ca9befc16375e7f
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7fc64a37a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h35a76e8acc949815
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f7fc64fda2c - core::fmt::write::h1966177bbb3b1b76
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f7fc6494f85 - std::io::Write::write_fmt::he17142a652adbfaa
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/io/mod.rs:1672:15
   6:     0x7f7fc64a6471 - std::sys_common::backtrace::_print::h58fd682547bc6ff7
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f7fc64a6471 - std::sys_common::backtrace::print::hb71ddfedfd79ba3f
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f7fc64a6471 - std::panicking::default_hook::{{closure}}::h866ffdcbb9391663
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:295:22
   9:     0x7f7fc64a6143 - std::panicking::default_hook::hc53d610bee87e7b5
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:314:9
  10:     0x7f7fc6d53731 - rustc_driver[ee492072531d29b9]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f7fc64a6c46 - std::panicking::rust_panic_with_hook::h1f2457f8494b1ce0
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:702:17
  12:     0x7f7fc7dbfb31 - std[af12de6c3337c1b7]::panicking::begin_panic::<rustc_errors[30e8870fe27fb8ba]::ExplicitBug>::{closure#0}
  13:     0x7f7fc7dbee66 - std[af12de6c3337c1b7]::sys_common::backtrace::__rust_end_short_backtrace::<std[af12de6c3337c1b7]::panicking::begin_panic<rustc_errors[30e8870fe27fb8ba]::ExplicitBug>::{closure#0}, !>
  14:     0x7f7fc7d9cdd6 - std[af12de6c3337c1b7]::panicking::begin_panic::<rustc_errors[30e8870fe27fb8ba]::ExplicitBug>
  15:     0x7f7fc7d59ea6 - std[af12de6c3337c1b7]::panic::panic_any::<rustc_errors[30e8870fe27fb8ba]::ExplicitBug>
  16:     0x7f7fc7d55755 - <rustc_errors[30e8870fe27fb8ba]::HandlerInner>::bug::<&alloc[327c298d5f7f3986]::string::String>
  17:     0x7f7fc7d554b0 - <rustc_errors[30e8870fe27fb8ba]::Handler>::bug::<&alloc[327c298d5f7f3986]::string::String>
  18:     0x7f7fc7e142ad - rustc_middle[ba567b0c63397382]::ty::context::tls::with_context_opt::<rustc_middle[ba567b0c63397382]::ty::context::tls::with_opt<rustc_middle[ba567b0c63397382]::util::bug::opt_span_bug_fmt<rustc_span[e8a062c38fd06fcf]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7f7fc7e1a2b6 - rustc_middle[ba567b0c63397382]::util::bug::opt_span_bug_fmt::<rustc_span[e8a062c38fd06fcf]::span_encoding::Span>
  20:     0x7f7fc7e1a233 - rustc_middle[ba567b0c63397382]::util::bug::bug_fmt
  21:     0x7f7fc8d7daa7 - <rustc_middle[ba567b0c63397382]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle[ba567b0c63397382]::ty::fold::TypeFolder>::fold_ty
  22:     0x5623e49ee3c1 - rustc_middle[ba567b0c63397382]::ty::util::fold_list::<rustc_middle[ba567b0c63397382]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder, rustc_middle[ba567b0c63397382]::ty::Ty, <&rustc_middle[ba567b0c63397382]::ty::list::List<rustc_middle[ba567b0c63397382]::ty::Ty> as rustc_middle[ba567b0c63397382]::ty::fold::TypeFoldable>::try_fold_with<rustc_middle[ba567b0c63397382]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::{closure#0}>
  23:     0x5623e48f7af0 - <rustc_middle[ba567b0c63397382]::ty::context::TyCtxt>::normalize_erasing_late_bound_regions::<rustc_middle[ba567b0c63397382]::ty::sty::FnSig>
  24:     0x5623e495d99f - <rustc_const_eval[fabfa6a4d198841f]::interpret::eval_context::InterpCx<miri[ab945d3d15ab0ad0]::machine::Evaluator>>::terminator
  25:     0x5623e4933c3d - <core[7b47b893e00d8dca]::panic::unwind_safe::AssertUnwindSafe<miri[ab945d3d15ab0ad0]::eval::eval_entry::{closure#0}> as core[7b47b893e00d8dca]::ops::function::FnOnce<()>>::call_once
  26:     0x5623e4912e6c - miri[ab945d3d15ab0ad0]::eval::eval_entry
  27:     0x5623e4867c89 - <rustc_interface[c2045ebdcb88575c]::passes::QueryContext>::enter::<<miri[a2bdd18a035b3443]::MiriCompilerCalls as rustc_driver[ee492072531d29b9]::Callbacks>::after_analysis::{closure#0}, ()>
  28:     0x5623e486c653 - <miri[a2bdd18a035b3443]::MiriCompilerCalls as rustc_driver[ee492072531d29b9]::Callbacks>::after_analysis
  29:     0x7f7fc8f06c8b - <rustc_interface[c2045ebdcb88575c]::interface::Compiler>::enter::<rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}::{closure#2}, core[7b47b893e00d8dca]::result::Result<core[7b47b893e00d8dca]::option::Option<rustc_interface[c2045ebdcb88575c]::queries::Linker>, rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>
  30:     0x7f7fc8f02f3a - rustc_span[e8a062c38fd06fcf]::with_source_map::<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_interface[c2045ebdcb88575c]::interface::create_compiler_and_run<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}>::{closure#1}>
  31:     0x7f7fc8f1f360 - rustc_interface[c2045ebdcb88575c]::interface::create_compiler_and_run::<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}>
  32:     0x7f7fc8f33362 - <scoped_tls[7afe57960397b723]::ScopedKey<rustc_span[e8a062c38fd06fcf]::SessionGlobals>>::set::<rustc_interface[c2045ebdcb88575c]::interface::run_compiler<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}>::{closure#0}, core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>
  33:     0x7f7fc8f0532f - std[af12de6c3337c1b7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c2045ebdcb88575c]::util::run_in_thread_pool_with_globals<rustc_interface[c2045ebdcb88575c]::interface::run_compiler<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}>::{closure#0}, core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>::{closure#0}, core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>
  34:     0x7f7fc8f1f7b9 - <<std[af12de6c3337c1b7]::thread::Builder>::spawn_unchecked_<rustc_interface[c2045ebdcb88575c]::util::run_in_thread_pool_with_globals<rustc_interface[c2045ebdcb88575c]::interface::run_compiler<core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>, rustc_driver[ee492072531d29b9]::run_compiler::{closure#1}>::{closure#0}, core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>::{closure#0}, core[7b47b893e00d8dca]::result::Result<(), rustc_errors[30e8870fe27fb8ba]::ErrorGuaranteed>>::{closure#1} as core[7b47b893e00d8dca]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7f7fc64b0693 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2535c4f17d1ae00a
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/alloc/src/boxed.rs:1935:9
  36:     0x7f7fc64b0693 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9555fa64d2fdcc1f
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/alloc/src/boxed.rs:1935:9
  37:     0x7f7fc64b0693 - std::sys::unix::thread::Thread::new::thread_start::hcd4b7b87c76163e2
                               at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7f7fc619954d - <unknown>
  39:     0x7f7fc621e874 - clone
  40:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (93ffde6f0 2022-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

Miri caused an ICE during evaluation. Here's the interpreter backtrace at the time of the panic:
note: the place in the program where the ICE was triggered
  --> src/main.rs:20:5
   |
20 |     fun(filter_positive());
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: inside `with_positive::<[closure@src/main.rs:24:19: 24:22]>` at src/main.rs:20:5
note: inside `main` at src/main.rs:24:5
  --> src/main.rs:24:5
   |
24 |     with_positive(|_| ());
   |     ^^^^^^^^^^^^^^^^^^^^^
   = note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
   = note: inside `std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
   = note: inside closure at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:145:18
   = note: inside `std::ops::function::impls::<impl std::ops::FnOnce<()> for &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>::call_once` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:280:13
   = note: inside `std::panicking::r#try::do_call::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
   = note: inside `std::panicking::r#try::<i32, &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
   = note: inside `std::panic::catch_unwind::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
   = note: inside closure at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:48
   = note: inside `std::panicking::r#try::do_call::<[closure@std::rt::lang_start_internal::{closure#2}], isize>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
   = note: inside `std::panicking::r#try::<isize, [closure@std::rt::lang_start_internal::{closure#2}]>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
   = note: inside `std::panic::catch_unwind::<[closure@std::rt::lang_start_internal::{closure#2}], isize>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
   = note: inside `std::rt::lang_start_internal` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:20
   = note: inside `std::rt::lang_start::<()>` at /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:144:17

error: aborting due to previous error
````

This has been fixed on the rustc side, why does this crash with miri now? :thinking:

### PR DESCRIPTION
**Pull request by compiler-errors**
First, we reenable normalization of opaque types with escaping late bound regions to fix rust-lang/miri#2433. This essentially reverts #89285.

Second, we mitigate the perf regression found in #88862 by simplifying the way that we relate (sub and eq) GeneratorWitness types. 

This relies on the fact that we construct these GeneratorWitness types somewhat particularly (with all free regions found in the witness types replaced with late bound regions) -- but those bound regions really should be treated as existential regions, not universal ones. Those two facts leads me to believe that we do not need to use the full `higher_ranked_sub` machinery to relate two generator witnesses. I'm pretty confident that this is correct, but I'm glad to discuss this further.

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors try @rust-timer queue

r? types

cc @rust-lang/types I could use some help gauging the correctness of the last commit.

**Comment by compiler-errors** [comment]
I think a 4% perf regression on [issue-88862](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/issue-88862) is worth the correctness fix that we have here.

**Comment by jackh726** [comment]
Agreed @bors r+

File: compiler/rustc_infer/src/infer/sub.rs [hunk 1]
```diff
@@ -153,6 +153,32 @@ impl<'tcx> TypeRelation<'tcx> for Sub<'_, '_, 'tcx> {
...
+                // universes to be instantiated.
+                assert_eq!(a_types.skip_binder().len(), b_types.skip_binder().len());
+                let universe = infcx.create_next_universe();
+                let a_types =
+                    infcx.replace_bound_vars_with_placeholders_in_universe(a_types, universe);
+                let b_types =
+                    infcx.replace_bound_vars_with_placeholders_in_universe(b_types, universe);
+                for (a, b) in std::iter::zip(a_types, b_types) {
+                    self.relate(a, b)?;
+                }
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/sub.rs:179]: that seems really dangerous in cause one of the generators has anonymized bound vars while the other one does not. Anonymization can reorder bound vars which would cause this to fail even though it shouldn't.

I believe we need something like the impl in #97427. I personally would prefer for us to not add the method `replace_bound_vars_with_placeholders_in_universe` as I can't think of any use which does not feel worrying to me.

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/sub.rs:179]: Makes sense. Shouldn't be too hard.

**Comment by compiler-errors** [comment]
I think this was what you were looking for @lcnr? At least, I adapted the same approach, but just for the GeneratorWitness case, since I'm just trying to keep this as directed as possible.

@bors try @rust-timer queue
r? @lcnr

File: compiler/rustc_infer/src/infer/equate.rs [hunk 2]
```diff
@@ -110,6 +110,24 @@ impl<'tcx> TypeRelation<'tcx> for Equate<'_, '_, 'tcx> {
...
+                    );
+                    for (a, b) in std::iter::zip(a_types, b_types) {
+                        self.relate(a, b)?;
+                    }
+                } else {
+                    self.fields.infcx.super_combine_tys(
+                        self,
+                        infcx.tcx.mk_generator_witness(a_types),
+                        infcx.tcx.mk_generator_witness(b_types),
+                    )?;
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/equate.rs:128]: i would expect this to error instead 🤔

**Comment by lcnr** [comment]
yes, only doing this in the `GeneratorWitness` case for this PR seems good to me 👍

is there a reason we can't do this in `super_combine_tys` (or even `super_relate_tys`) instead of individually doing it for each combiner separately

File: compiler/rustc_infer/src/infer/equate.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/equate.rs:128]: Yeah fair, I was going for a defensive approach of "fall back to old behavior", lol

**Comment by compiler-errors** [comment]
> is there a reason we can't do this in super_combine_tys (or even super_relate_tys) instead of individually doing it for each combiner separately?

No particular reason, other than I was somewhat uncertain of my approach so I wanted to keep it as limited as possible. But yeah, shouldn't hurt to do it there.

**Comment by compiler-errors** [comment]
Actually, @lcnr, now that I think of it, `Sub` and `Equate` are the only `TypeRelation`s that call `higher_ranked_sub`. Is it correct to be doing this in `super_combine_tys` instead? Like idk what this would do for NLL's type relation.

**Comment by lcnr** [comment]
hm, yeah... I guess that might be a problem right now. Keeping it in `Equate` and `Sub` seems fine then.

nll takes a different approach to bound variables, only replacing them lazily, so doing it in `super_combine_tys` would break stuff. I think we should change nll to also eagerly replace bound vars but that's not relevant for this PR :3

File: compiler/rustc_infer/src/infer/equate.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/equate.rs]: Ugh, so this causes things to fail in the case we have unevaluated consts, which after evaluating/normalization now have fewer regions than they had before (because the Unevaluated form may capture parent substs which mention things with regions). 

I think a fallback is needed, or else we need to do something like `normalize_erasing_regions` when constructing the generator interior.

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/equate.rs]: Could use advice @lcnr.

Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/equate.rs]: Actually, just plain normalizing the generator interior types worked, no need to `normalize_erasing_regions`.

File: compiler/rustc_infer/src/infer/equate.rs [hunk 3]
```diff
@@ -110,6 +110,25 @@ impl<'tcx> TypeRelation<'tcx> for Equate<'_, '_, 'tcx> {
...
+            (&ty::GeneratorWitness(a_types), &ty::GeneratorWitness(b_types)) => {
+                let a_types = infcx.tcx.anonymize_bound_vars(a_types);
+                let b_types = infcx.tcx.anonymize_bound_vars(b_types);
+                if a_types.bound_vars() == b_types.bound_vars() {
+                    let (a_types, b_types) = infcx.replace_bound_vars_with_placeholders(
+                        a_types.map_bound(|a_types| (a_types, b_types.skip_binder())),
+                    );
+                    for (a, b) in std::iter::zip(a_types, b_types) {
+                        self.relate(a, b)?;
+                    }
```
Comment (lcnr) [inline compiler/rustc_infer/src/infer/equate.rs:125]: does `self.relate(a_types, b_types)?` not work?

**Comment by lcnr** [comment]
one nit, then r=me

we may want to only land this after the next beta cutoff, as we may still get another perf regression because of this '^^

File: compiler/rustc_infer/src/infer/equate.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/equate.rs:125]: nope can't relate substs lists directly, need to do them one by one i think

Comment (lcnr) [reply compiler/rustc_infer/src/infer/equate.rs:125]: we should impl `Relate` for substs lists :grin:

**Comment by compiler-errors** [comment]
I can wait until September 16 when the next branch happens.

**Comment by compiler-errors** [comment]
Beta has branched, I think this is ready @lcnr :smile_cat: 

@rustbot ready

**Comment by lcnr** [comment]
forgot about this and thought it was already merged :grin:

@bors r+ rollup=never

happy to finally see this landing

**Comment by compiler-errors** [comment]
@aliemjay I don't think so? We handle binders differently there, so I suspect the same pathological case where we create way too many region variables just doesn't happen.
