### PR TITLE
handle outlives predicates in trait evaluation

### LINKED ISSUE #54302: Trait with HRTB blanket impl is implemented when it shouldn't be
```rust
trait Deserialize<'de> {}

trait DeserializeOwned: for<'de> Deserialize<'de> {}
impl<T> DeserializeOwned for T where T: for<'de> Deserialize<'de> {}

// Based on this impl, `&'static str` only implements Deserialize<'static>.
// It does not implement for<'de> Deserialize<'de>.
impl<'de: 'a, 'a> Deserialize<'de> for &'a str {}

fn main() {
    // Then why does it implement DeserializeOwned? This compiles.
    fn assert_deserialize_owned<T: DeserializeOwned>() {}
    assert_deserialize_owned::<&'static str>();

    // It correctly does not implement for<'de> Deserialize<'de>.
    //fn assert_hrtb<T: for<'de> Deserialize<'de>>() {}
    //assert_hrtb::<&'static str>();
}
```

This is a regression between rustc 1.20.0 and 1.21.0.

1.20 correctly rejects this code with the following error.

```console
error[E0279]: the requirement `for<'de> 'de : ` is not satisfied (`expected bound lifetime parameter 'de, found concrete lifetime`)
  --> src/main.rs:13:5
   |
13 |     assert_deserialize_owned::<&'static str>();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: required because of the requirements on the impl of `for<'de> Deserialize<'de>` for `&'static str`
   = note: required because of the requirements on the impl of `DeserializeOwned` for `&'static str`
   = note: required by `main::assert_deserialize_owned`
```

### PR DESCRIPTION
**Pull request by arielb1**
This handles higher-ranked outlives predicates in trait evaluation the same way they are handled in projection.

Fixes #54302. I think this is a more correct fix than #54401 because it fixes the root case in evaluation instead of making evaluation used in less cases. However, we might want to go to a direction closer to @nikomatsakis's solution with Chalk.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/traits/select.rs [hunk 1]
```diff
@@ -690,10 +690,76 @@ impl<'cx, 'gcx, 'tcx> SelectionContext<'cx, 'gcx, 'tcx> {
...
+                }
+            }
+
+            ty::Predicate::RegionOutlives(ref binder) => {
+                let ty::OutlivesPredicate(r_a, r_b) = binder.skip_binder();
+
+                if r_a == r_b {
+                    // for<'a> 'a: 'a. OK
+                    Ok(EvaluatedToOk)
+                } else if r_a.is_late_bound() || r_b.is_late_bound() {
```
Comment (nikomatsakis) [inline src/librustc/traits/select.rs]: Annoyingly, the current region solver has one extra case to consider: the case where `r_a` is `'static`. In that case, know it outlives any `r_b`. But we support this case inconsistently owing to the leak-check. Not sure how relevant that is here.

Comment (nikomatsakis) [reply src/librustc/traits/select.rs]: In particular, even within the leak check, we don't generate a constraint like `'a <= 'static`, and hence the leak-check doesn't fail:

https://github.com/rust-lang/rust/blob/80e6e3e582a9eb9115900d51ae6edecf46d81f6e/src/librustc/infer/region_constraints/mod.rs#L731-L733

Comment (nikomatsakis) [reply src/librustc/traits/select.rs]: The caching code that is going wrong — however — only cares about `predicate_must_hold`, so it's ok to falsely fail from time to time. Still, we might want this to be `is_late_bound() && is_late_bound()`? 

You mentioned coherence, though...

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
I agree this is good. I'm happy to land this in place of my PR. Left a few nits/thoughts, though. 

Also, do you still think we need to keep that `!data.has_late_bound_regions()` check, though? If so, why?

File: src/librustc/traits/select.rs (hunk 1 above)
Comment (arielb1) [reply src/librustc/traits/select.rs]: Actually, I think the only way something like this might happen if someone writes a literal `'static: 'a` bound in their trait. In this case, evaluation would return an error, but fulfillment would be ok. 

Maybe I should add a special case for this (`r_a == 'static`)?

**Comment by nnethercote** [comment]
This hurt perf by ~1% for several benchmarks:
https://perf.rust-lang.org/compare.html?start=d0787284da6e25a018f2f94fcd3779d33d6150fc&end=c67ea54d4466f1c082f72b194c100bb4954449e6&stat=instructions:u

@arielb1: any thoughts?
