### PR TITLE
improper ctypes: normalize return types and transparent structs

### LINKED ISSUE #66202: Types equal to/wrapping () result in "not FFI-safe" warning
```rust
// OK
pub extern "system" fn raw() -> () {}

// warning: `extern` fn uses type `()`, which is not FFI-safe
pub extern "system" fn assoc() -> <() as ToOwned>::Owned {}
//                                ^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe

#[repr(transparent)]
pub struct W<T>(T);

// warning: `extern` fn uses type `()`, which is not FFI-safe
pub extern "system" fn wrap() -> W<()> { W(()) }
//                              ^^^^^^ not FFI-safe
// note: composed only of `PhantomData`
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=62da3bf343e1358e16a6692a72ca7f33

All of these cases work in Beta. At least the associated type warning is recent regression in Nightly. I suspect https://github.com/rust-lang/rust/pull/65134

CC @davidtwco

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #66202.

See each commit individually (except the first which adds a test) for more detailed explanations on the changes made.

In summary, this PR ensures that return types are normalized before being checked for FFI-safety, and that transparent newtype wrappers are FFI-safe if the type being wrapped is FFI-safe (often true previously, but not if, after substitution, all types in a transparent newtype were zero sized).

### CODE REVIEW

File: src/librustc_lint/types.rs [hunk 1]
```diff
@@ -957,14 +963,20 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
-        // and then recursively check the types inside.
+
+        // C doesn't really support passing arrays by value - the only way to pass an array by value
+        // is through a struct. So, first test that the top level isn't an array, and then
+        // recursively check the types inside.
         if !is_static && self.check_for_array_ty(sp, ty) {
             return;
         }
 
+        // Don't report FFI errors for unit return types - not checking in `check_foreign_fn` so
```
Comment (varkor) [inline src/librustc_lint/types.rs:980]: I can't quite parse this sentence. Is it "we are now checking in"?

Comment (davidtwco) [reply src/librustc_lint/types.rs:980]: Apparently this made sense to me when I wrote it - I understand past-me to have meant "we aren't checking in `check_foreign_fn` (where this check might have been expected) because we want to check after normalization".

**Comment by varkor** [comment]
The changes look good to me. Just want to get clarification on that comment. Also cc @hanna-kruppe, who may have comments.

File: src/librustc_lint/types.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_lint/types.rs]: Pushed a hopefully clearer comment.

**Comment by varkor** [comment]
Thanks!

@bors r+ rollup
