### PR TITLE
collections: Make BinaryHeap panic safe in sift_up / sift_down

### LINKED ISSUE #25842: BinaryHeap is not exception safe
BinaryHeap is using `zeroed()` and may not be exception safe. I.e. it is in an inconsistent state after being recovered after panic. See issue #25662 and others.

Relevant code is [BinaryHeap::sift_up, sift_down_range](https://github.com/rust-lang/rust/blob/47f9e528f13403f48dc0521f360055430da6d538/src/libcollections/binary_heap.rs#L485-L527)

cc @cmr

### PR DESCRIPTION
**Pull request by bluss**
collections: Make BinaryHeap panic safe in sift_up / sift_down

Use a struct called Hole that keeps track of an invalid location
in the vector and fills the hole on drop.

I include a run-pass test that the current BinaryHeap fails, and the new
one passes.

NOTE: The BinaryHeap will still be inconsistent after a comparison fails. It will
not have the heap property. What we fix is just that elements will be valid
values.

This is actually a performance win -- the new code does not bother to write in `zeroed()`
values in the holes, it just leaves them as they were.

Net result is something like a 5% decrease in runtime for `BinaryHeap::from_vec`. This
can be further improved by using unchecked indexing (I confirmed it makes a difference,
not a surprise with the non-sequential access going on), but let's leave that for another PR.
Safety first :wink: 

Fixes #25842

### CODE REVIEW

**Comment by bluss** [comment]
I prototyped this using a [general scope guard](https://crates.io/crates/scopeguard), but this Hole representation turned out to be nice.

This is actually a performance win -- the new code does not bother to write in `zeroed()` values in the holes, it just leaves them as they were.

LLVM needs to be on our side here and see that the removed element's `Option<T>` is always Some, etc. If you wonder why I use `hole.pos()` in one location and `hole.pos` in another, it's because those choices benched the best, both locations. Optimizing compilers, they are chaotic.

Net result is something like a 5% decrease in runtime for `BinaryHeap::from_vec`. This can be further improved by using unchecked indexing (I confirmed it makes a difference, not a surprise with the non-sequential access going on), but let's leave that for another PR.

cc @alexcrichton @Gankro

**Comment by bluss** [comment]
Using only unchecked indexing in `Hole` removes the bench result dependence on `hole.pos` vs `hole.pos()` -- just shows how panicking can be an impediment to optimization.

File: src/libcollections/binary_heap.rs [hunk 1]
```diff
@@ -554,6 +553,70 @@ impl<T: Ord> BinaryHeap<T> {
...
+/// position with the value that was originally removed.
+struct Hole<'a, T: 'a> {
+    data: &'a mut [T],
+    elt: Option<T>,
+    pos: usize,
+}
+
+impl<'a, T> Hole<'a, T> {
+    /// Create a new Hole at index `pos`.
+    pub fn new(data: &'a mut [T], pos: usize) -> Self {
```
Comment (alexcrichton) [inline src/libcollections/binary_heap.rs]: Could the `pub` be dropped from these functions? (`Hole` isn't exposed so they shouldn't need to be exposed either)

**Comment by alexcrichton** [comment]
Looks good to me, thanks @bluss! Perhaps the test could also be modified to ensure that the destructor for each element in the heap isn't run more than once?

Other than that though r=me, we can always tweak the performance at a later date.

cc @Gankro

**Comment by bluss** [comment]
Thanks. I'll add a test that makes sure no destructors were called right after catching the panic, before I inspect the data further. That should cover it (and fails on old version of BinaryHeap).

File: src/libcollections/binary_heap.rs [hunk 2]
```diff
@@ -484,44 +484,43 @@ impl<T: Ord> BinaryHeap<T> {
...
-            while pos > start {
-                let parent = (pos - 1) >> 1;
-
-                if new <= self.data[parent] { break; }
-
-                let x = replace(&mut self.data[parent], zeroed());
-                ptr::write(&mut self.data[pos], x);
-                pos = parent;
+            while hole.pos() > start {
+                let parent = (hole.pos() - 1) >> 1;
```
Comment (Gankro) [inline src/libcollections/binary_heap.rs]: Surely LLVM can convert the much more semantically clear `/2` to this?

File: src/libcollections/binary_heap.rs (hunk 1 above)
Comment (Gankro) [inline src/libcollections/binary_heap.rs]: It makes the code more portable, though. e.g. we can happily move this to a module without worrying.

File: src/libcollections/binary_heap.rs [hunk 3]
```diff
@@ -554,6 +553,70 @@ impl<T: Ord> BinaryHeap<T> {
     pub fn clear(&mut self) { self.drain(); }
 }
 
+/// Hole represents a hole in a slice i.e. an index without valid value
+/// (because it was moved from or duplicated).
+/// In drop, `Hole` will restore the slice by filling the hole
+/// position with the value that was originally removed.
+struct Hole<'a, T: 'a> {
+    data: &'a mut [T],
+    elt: Option<T>,
```
Comment (Gankro) [inline src/libcollections/binary_heap.rs]: Perhaps worth noting that this value is `Some` until this value is Dropped

File: src/libcollections/binary_heap.rs [hunk 4]
```diff
@@ -554,6 +553,70 @@ impl<T: Ord> BinaryHeap<T> {
...
+        &self.data[index]
+    }
+
+    /// Move hole to new location
+    #[inline(always)]
+    pub unsafe fn move_to(&mut self, index: usize) {
+        debug_assert!(index != self.pos);
+        let old_pos = self.pos;
+        let x = ptr::read(&mut self.data[index]);
+        ptr::write(&mut self.data[old_pos], x);
```
Comment (Gankro) [inline src/libcollections/binary_heap.rs]: Should this not just be a `copy_nonoverlapping`?

Comment (bluss) [inline src/libcollections/binary_heap.rs]: That's a good idea for here. Haven't really looked at changing anything besides what's needed.

File: src/libcollections/binary_heap.rs (hunk 2 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: I'll fix it. Haven't really looked at changing anything besides what's needed, though.

File: src/libcollections/binary_heap.rs (hunk 3 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: Good idea.

File: src/libcollections/binary_heap.rs (hunk 1 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: It came out with pub, I think `pub` is natural as soon as the methods are intended to be called from outside the struct itself. I know our privacy doesn't work that way, but it does once the code grows and yes you move it out to a module. I'm fine either way but I prefer pub.

File: src/libcollections/binary_heap.rs (hunk 4 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: Can we leave it for now? It requires switching to unchecked indexing.

File: src/libcollections/binary_heap.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libcollections/binary_heap.rs]: Idiomatically code in the rest of the standard library does not do this, so let's stick to existing conventions. We can add `pub` if necessary at a later date, but code should be as conservative as possible in exports today.

File: src/libcollections/binary_heap.rs (hunk 4 above)
Comment (Gankro) [inline src/libcollections/binary_heap.rs]: You don't need unchecked indexing, you just need to cache &self.data[index] in a `*const` for a line. Right?

(also at very least, you shouldn't be `read`ing from an &mut :) )

File: src/libcollections/binary_heap.rs (hunk 1 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: ok that's fine

**Comment by Gankro** [comment]
This looks great!

File: src/libcollections/binary_heap.rs (hunk 4 above)
Comment (bluss) [inline src/libcollections/binary_heap.rs]: I had a feeling something was off. I promise, a feeling.

**Comment by bluss** [comment]
PR updated. Everything is addressed, removed pub. The test checks for number of drop calls now (old binary heap used to drop 1 on panic), but it could still have tracked drops in even more detail.

**Comment by bluss** [comment]
wait

**Comment by Gankro** [comment]
@bors r+

Sweet!

**Comment by huonw** [comment]
Nice work @bluss!

**Comment by alexcrichton** [comment]
triage: beta-accepted
