### PR TITLE
filter suggestions from extern prelude

### LINKED ISSUE #59027: rustc emits a misguided "a crate with a similar name exists" help note
```
   Compiling script v0.0.1 (/Users/nox/src/servo/components/script)
error[E0412]: cannot find type `Inert` in this scope
   --> components/script/dom/bindings/root.rs:642:26
    |
642 |     type Output = Option<Inert<Dom<T>>>;
    |                          ^^^^^
help: a crate with a similar name exists
    |
642 |     type Output = Option<inert<Dom<T>>>;
    |                          ^^^^^
help: possible candidate is found in another module, you can import it into scope
    |
27  | use inert::Inert;
    |
```

A crate cannot be a type, so suggesting `inert<Dom<T>>` is wrong.

### PR DESCRIPTION
**Pull request by euclio**
Fixes #59027.

Modifies the candidate gathering code to call `filter_fn` on extern crates, which causes them to be filtered out when looking for a type.

### CODE REVIEW

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -4046,13 +4046,27 @@ impl<'a> Resolver<'a> {
...
-                                TypoSuggestion {
-                                    candidate: ident.name,
-                                    article: "a",
-                                    kind: "crate",
-                                }
+                            names.extend(self.extern_prelude.clone().iter().flat_map(|(ident, _)| {
+                                self.crate_loader
+                                    .maybe_process_path_extern(ident.name, ident.span)
+                                    .and_then(|crate_id| {
+                                        let crate_root = self.get_module(DefId {
```
Comment (oli-obk) [inline src/librustc_resolve/lib.rs]: Calling `self.get_module(some_def_id).def().unwrap()` for `CRATE_DEF_INDEX` is equivalent to `Def::Mod(some_def_id)`. I think it would be clearer to just use that as an argument to `filter_fn`

Comment (euclio) [reply src/librustc_resolve/lib.rs]: Fixed.
