### PR TITLE
Display valid crate types in error message for --crate-type flag

### LINKED ISSUE #70183: rustc --crate-type flag should display valid values
Hello,

When we provide wrong value for the `--emit` flag, we will get a list of valid values. This is not the case for `--crate-type` flag, which should also display valid values.

The `--emit` example:
```
$ cargo rustc -- --emit=asd
   Compiling tokio v0.2.13 (/host/tokio/tokio)
error: unknown emission type: `asd` - expected one of: `llvm-bc`, `asm`, `llvm-ir`, `mir`, `obj`, `metadata`, `link`, `dep-info`
```

The `--crate-type` example:
```
$ cargo rustc -- --crate-type=dynlib
   Compiling tokio v0.2.13 (/host/tokio/tokio)
error: unknown crate type: `dynlib`

error: could not compile `tokio`.

To learn more, run the command again with --verbose.
```

Versions:
```
$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
r$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
```

I have also tested this on rustc 1.42.0 and it is the same.

### PR DESCRIPTION
**Pull request by malezjaa**
This PR improves the error message for the --crate-type flag. When an invalid crate type is provided, the compiler will now show a list of valid options.

### Before
image

### After
image

I based the implementation on `OutputType::shorthands_display`

Closes #70183

### CODE REVIEW

**Comment by jieyouxu** [comment]
I seem to recall not all the targets support all the crate types. For example, does some of the wasm targets support `proc-macro` crate type?

Example: https://github.com/rust-lang/rust/pull/130599/files#diff-ec897fdc27fe33a590c42303d7adda80b03a9af4860440e41a235d7081aa2165

**Comment by malezjaa** [comment]
You're right 🙂 This error is just to show the valid values for --crate-type. Target-specific issues will appear later.

**Review by jieyouxu — COMMENTED** [review]
Can you add an ui test for this diagnostics?

**Comment by malezjaa** [comment]
Hi, I added the tests. I'm not sure if I did it the right way, though.

File: src/etc/pre-push.sh
Comment (clubby789) [inline src/etc/pre-push.sh:1]: Should revert these changes

**Comment by clubby789** [comment]
The UI test looks good. You'll should squash all your changes into one commit

**Comment by malezjaa** [comment]
Done 👍

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -2678,7 +2701,12 @@ pub fn parse_crate_types_from_list(list_list: Vec<String>) -> Result<Vec<CrateTy
                 "cdylib" => CrateType::Cdylib,
                 "bin" => CrateType::Executable,
                 "proc-macro" => CrateType::ProcMacro,
-                _ => return Err(format!("unknown crate type: `{part}`")),
+                _ => {
+                    return Err(format!(
+                        "unknown crate type: `{part}` - expected one of: {display}",
```
Comment (jieyouxu) [inline compiler/rustc_session/src/config.rs:2706]: Tiny nit:

```suggestion
                        "unknown crate type `{part}`, expected one of: {display}",
```

File: compiler/rustc_session/src/config.rs [hunk 2]
```diff
@@ -1296,6 +1296,29 @@ impl CrateType {
...
+
+    fn shorthands_display() -> String {
+        format!(
+            "`{}`, `{}`, `{}`, `{}`, `{}`, `{}`",
+            CrateType::Executable.shorthand(),
+            CrateType::Dylib.shorthand(),
+            CrateType::Rlib.shorthand(),
+            CrateType::Staticlib.shorthand(),
+            CrateType::Cdylib.shorthand(),
+            CrateType::ProcMacro.shorthand(),
```
Comment (jieyouxu) [inline compiler/rustc_session/src/config.rs:1319]: Suggestion: can you sort these alphabetically (for display) to make it easier for the user to follow? (I know the enum definition isn't sorted alphabetically).

**Review by jieyouxu — APPROVED** [review]
Thanks, this looks like a nice improvement, only some tiny stylistic nits, then LGTM.

**Comment by jieyouxu** [comment]
Thanks, I'll r+ after PR CI is green.

**Comment by jieyouxu** [comment]
(You might need to rebless the test)

**Comment by jieyouxu** [comment]
Also, can you squash the commits into one? Thanks.

**Comment by jieyouxu** [comment]
Cool.
@bors r+ rollup

**Comment by clubby789** [comment]
Looks like Cargo tests (possibly other tools too) will need some blessing/manual updatimg

**Comment by malezjaa** [comment]
Should I just create a PR in Cargo to update this test?

https://github.com/rust-lang/cargo/blob/master/tests/testsuite/bad_config.rs#L424-L430

**Comment by clubby789** [comment]
No, it must be made in this repo. Changes are periodically synced between the repos - if you were to update it in Cargo then both repos would be failing until that's done 😄

File: compiler/rustc_session/src/config.rs [hunk 3]
```diff
@@ -1296,6 +1296,29 @@ impl CrateType {
             CrateType::Executable | CrateType::Cdylib | CrateType::Staticlib => false,
         }
     }
+
+    pub fn shorthand(&self) -> &'static str {
+        match *self {
+            CrateType::Executable => "bin",
+            CrateType::Dylib => "dylib",
+            CrateType::Rlib => "rlib",
+            CrateType::Staticlib => "lib",
```
Comment (ollie27) [inline compiler/rustc_session/src/config.rs:1305]:
```suggestion
            CrateType::Staticlib => "staticlib",
```

Although `lib` also needs to be in the list.

**Comment by malezjaa** [comment]
> No, it must be made in this repo. Changes are periodically synced between the repos - if you were to update it in Cargo then both repos would be failing until that's done 😄

So sorry for responding so late 😅. Could you give me more information about where is the cargo test in this repo that I should update?

**Comment by clubby789** [comment]
If you check the CI logs (the `(web)` link above), you can see the test `src/tools/cargo/tests/testsuite/bad_config.rs` failed. That test uses
```rs
    p.cargo("build -v")
        .with_status(101)
        .with_stderr_data(str![[r#"
[ERROR] failed to run `rustc` to learn about crate-type bad_type information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bad_type` ([EXIT_STATUS]: 1)
  --- stderr
  [ERROR] unknown crate type: `bad_type`


"#]])
        .run();
```
It should pass if you update the error message with the new one (you should be able to copy from the diff shown under the test in the logs)

**Comment by jieyouxu** [comment]
Actually wait, this is a problem -- cargo is a submodule, it's not like miri or rust-analyzer that can be updated then sync'd back, we'd have to rebless the cargo test over at cargo but that requires having the changes in this PR at r-l/r!

File: compiler/rustc_session/src/config.rs (hunk 3 above)
Comment (jieyouxu) [reply compiler/rustc_session/src/config.rs:1305]: Good point...

File: compiler/rustc_session/src/config.rs [hunk 4]
```diff
@@ -2678,7 +2701,12 @@ pub fn parse_crate_types_from_list(list_list: Vec<String>) -> Result<Vec<CrateTy
                 "cdylib" => CrateType::Cdylib,
                 "bin" => CrateType::Executable,
                 "proc-macro" => CrateType::ProcMacro,
-                _ => return Err(format!("unknown crate type: `{part}`")),
+                _ => {
+                    return Err(format!(
+                        "unknown crate type `{part}`, expected one of: {display}",
+                        display = CrateType::shorthands_display()
+                    ));
+                }
```
Comment (jieyouxu) [inline compiler/rustc_session/src/config.rs:2709]: Suggestion: as @ollie27 mentioned above, we forgot about the "lib" being a valid accepted value which is not part of the `CrateType` enum ("lib" currently defaults to `default_lib_output()`).

Instead of adding the `shorthand` and `shorthands_display` methods to `CrateType`, could you instead slightly refactor this `match part` logic, to something like

```rs
const SUPPORTED_CRATE_TYPES: &str = ["lib", /* .. accepted values from the match arms */];

if SUPPORTED_CRATE_TYPES.contains(&part) {
    // blah
} else {
    return Err(format!("unknown crate type: `{}`, expected one of: ..."));
}
```

And could you add the colon back after "unknown crate type" (sorry)?

File: src/tools/cargo
Comment (jieyouxu) [inline src/tools/cargo:1]: Suggestion: sorry, I forgot that cargo is a *submodule* in this repo and not sync'd as `josh` subtrees like miri or rust-analyzer. This means that we cannot rebless the cargo test in rust-lang/rust and we'll have to do it over at rust-lang/cargo. I'll send a PR to cargo to relax that test to only match on "unknown crate type" and not the full error message.

Can you drop the `src/tools/cargo` submodule change?

**Review by jieyouxu — CHANGES_REQUESTED** [review]

**Comment by malezjaa** [comment]
Yeah 😅 I was hesitant at first about updating the Cargo tests in this repo, but I figured it was the only way to do it. I am going to revert the changes in the submodule.

**Comment by malezjaa** [comment]
Just give me a second and I will resolve requested changes.

File: src/tools/cargo
Comment (jieyouxu) [reply src/tools/cargo:1]: rust-lang/cargo side PR: https://github.com/rust-lang/cargo/pull/14990

**Comment by jieyouxu** [comment]
I opened https://github.com/rust-lang/cargo/pull/14990 on the cargo side to relax the cargo bad crate type ui test. So... this PR is going to have to wait until the next cargo submodule bump to *this* repo, lol.

File: compiler/rustc_session/src/config.rs (hunk 4 above)
Comment (malezjaa) [reply compiler/rustc_session/src/config.rs:2709]: I think we can keep the error in the `_` match arm, because we still need to match the input to enum variant.
So maybe something like this?
```rs
pub fn parse_crate_types_from_list(list_list: Vec<String>) -> Result<Vec<CrateType>, String> {
    const SUPPORTED_CRATE_TYPES: &[&str] = &[
        "lib",
        "rlib",
        "staticlib",
        "dylib", 
        "cdylib",
        "bin",
        "proc-macro",
    ];

    let mut crate_types: Vec<CrateType> = Vec::new();
    for unparsed_crate_type in &list_list {
        for part in unparsed_crate_type.split(',') {
            let new_part = match part {
                "lib" => default_lib_output(),
                "rlib" => CrateType::Rlib,
                "staticlib" => CrateType::Staticlib,
                "dylib" => CrateType::Dylib,
                "cdylib" => CrateType::Cdylib,
                "bin" => CrateType::Executable,
                "proc-macro" => CrateType::ProcMacro,
                _ => return Err(format!(
                    "unknown crate type: `{part}`, expected one of: {display}",
                    display = SUPPORTED_CRATE_TYPES.join(", ")
                )),
            };

            if !crate_types.contains(&new_part) {
                crate_types.push(new_part)
            }
        }
    }

    Ok(crate_types)
}
```

Possibly the `SUPPORTED_CRATE_TYPES` could be inlined into `format!`

```diff
                _ => return Err(format!(
                    "unknown crate type: `{part}`, expected one of: {display}",
-                     display = SUPPORTED_CRATE_TYPES.join(", ")
+                    display = ["lib", "rlib", "staticlib", "dylib", "cdylib", "bin", "proc-macro"].join(", ")
                )),
```

Comment (jieyouxu) [reply compiler/rustc_session/src/config.rs:2709]: Ok yeah, let's just do the simplest thing here, since the crate types we accept isn't going to change very often.

Inlining will do, don't bother with the helper methods or the const array.

```rs
pub fn parse_crate_types_from_list(list_list: Vec<String>) -> Result<Vec<CrateType>, String> {
    // NOTE: the param is called `list_list` as we support invocations like:
    //
    // ```
    // --crate-type=rlib,staticlib --crate-type=dylib`
    // ```

    let mut crate_types: Vec<CrateType> = Vec::new();
    for unparsed_crate_type in &list_list {
        for part in unparsed_crate_type.split(',') {
            let new_part = match part {
                "lib" => default_lib_output(),
                "rlib" => CrateType::Rlib,
                "staticlib" => CrateType::Staticlib,
                "dylib" => CrateType::Dylib,
                "cdylib" => CrateType::Cdylib,
                "bin" => CrateType::Executable,
                "proc-macro" => CrateType::ProcMacro,
                _ => {
                    return Err(format!(
                        "unknown crate type: `{part}`, expected one of: {display}",
                        display =
                            ["lib", "rlib", "staticlib", "dylib", "cdylib", "bin", "proc-macro"]
                                .join(", ")
                    ));
                }
            };
            if !crate_types.contains(&new_part) {
                crate_types.push(new_part)
            }
        }
    }

    Ok(crate_types)
}

```

**Comment by malezjaa** [comment]
Okay done. Sorry that it took so long. Had to rebuild it 2 times and test.

**Comment by jieyouxu** [comment]
There's no rush at all, we can't merge this before the cargo submodule bump which contains my cargo-side PR to merge back into this repo anyway lol.

File: compiler/rustc_session/src/config.rs [hunk 5]
```diff
@@ -2678,7 +2678,12 @@ pub fn parse_crate_types_from_list(list_list: Vec<String>) -> Result<Vec<CrateTy
                 "cdylib" => CrateType::Cdylib,
                 "bin" => CrateType::Executable,
                 "proc-macro" => CrateType::ProcMacro,
-                _ => return Err(format!("unknown crate type: `{part}`")),
+                _ => {
+                    return Err(format!(
+                        "unknown crate type: `{part}`, expected one of: {display}",
+                        display = ["lib", "rlib", "staticlib", "dylib", "cdylib", "bin", "proc-macro"].join(", ")
```
Comment (jieyouxu) [inline compiler/rustc_session/src/config.rs:2684]: I suspect you may have to run `./x fmt` locally to format this line, but maybe not?

**Review by jieyouxu — APPROVED** [review]
Thanks, this LGTM now, we just have to wait for the cargo submodule bump before the cargo test in this repo can pass.

**Comment by malezjaa** [comment]
Oh yeah. I ran x.py test tidy. Not x.py fmt. Didn't know that. Sorry!

**Comment by malezjaa** [comment]
Hey @jieyouxu sorry for pinging, but I think this pr can be merged.

**Comment by jieyouxu** [comment]
Thanks for the reminder, I missed the cargo bump.

@bors r+ rollup

**Comment by jhpratt** [comment]
@bors r-

presumptive (partial) cause of https://github.com/rust-lang/rust/pull/135181#issuecomment-2574298798

**Comment by jieyouxu** [comment]
Ah right, I added a new test, may have to rebless it

**Comment by jieyouxu** [comment]
I reblessed the test, no significant changes.
@bors r+ rollup
