### PR TITLE
rustdoc: improve crate-local inlining

### LINKED ISSUE #28537: Rustdoc handling of public re-export is broken
Looking at nightly docs of `core::num`, the presentation of `ParseFloatError` is confusing. It looks like this: 

rustdoc

It should be rendered like `ParseIntError`, for example. The fact that it's defined in a private submodule is irrelevant and should not leak to unsuspecting users. The type *does* have a page, which can be found with the search, and links from other pages (functions, traits) do work. It's just the landing page for `core::num` that sucks.

FWIW, in `std::num` it *is* rendered normally (the source link is broken, but whatever).

### PR DESCRIPTION
**Pull request by mitaa**
fixes #28537

r? @alexcrichton

### CODE REVIEW

File: src/librustdoc/visit_ast.rs [hunk 1]
```diff
@@ -213,8 +215,36 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
                   glob: bool, om: &mut Module, please_inline: bool) -> bool {
+
+        fn is_doc_hidden(cx: &core::DocContext, mut node: ast::NodeId) -> bool {
+            let mut seen = HashSet::new();
+            seen.insert(node);
+
+            while let Some(id) = cx.map.get_enclosing_scope(node) {
+                node = id;
+                if !seen.insert(id) {
+                    break;
```
Comment (mitaa) [inline src/librustdoc/visit_ast.rs]: I'm not quite sure why this is necessary. (`rustdoc/viewpath-self.rs` is caught in an infinite loop otherwise)

File: src/librustdoc/visit_ast.rs [hunk 2]
```diff
@@ -213,8 +215,36 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
 
     }
 
-    fn resolve_id(&mut self, id: ast::NodeId, renamed: Option<ast::Name>,
+    /// Tries to resolve the target of a `pub use` statement and inlines the
```
Comment (mitaa) [inline src/librustdoc/visit_ast.rs]: It may also make sense to inline private imports if we're not stripping private items and the target inherits `doc(hidden)`

Comment (mitaa) [inline src/librustdoc/visit_ast.rs]: Oh... then the privacy of the inlined items would also need to be overridden to private.

**Comment by alexcrichton** [comment]
Thanks @mitaa! I wonder if we might be able to get away from dealing with the passes for now? Is there a use case where rustdoc is actually being called with various passes and this isn't working? 

I tend to view the passes in rustdoc as kinda a half-baked feature which wasn't ever really ready for prime time :(

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (alexcrichton) [inline src/librustdoc/visit_ast.rs]: ah yeah private imports probably never want to be inlining as it's just bringing a name into scope

**Comment by mitaa** [comment]
I've backed that commit out for now. The only thing rustdoc would be doing "wrong" is overzealous inlining when it isn't required.

It is definitely unfortunate that some passes have to currently to leak out like that such that various points in rustdoc need to have knowledge about them hardcoded in.
That may be better solved (another time..) by extending the pass system somehow with various hooks into the required stages in rustdoc? IOW by rounding out the pass feature out.
