### PR TITLE
Use more principled check for generics in const ops

### LINKED ISSUE #140891: ICE:called `Option::unwrap()` on a `None` value
The code is generated by a fuzzer and reduced manually
Possible repetition with #129209

### Code

```Rust
struct A<const N: usize> {}
impl<const N: usize> Iterator for A<N> {
    fn next() -> [(); std::mem::size_of::<Option<Self::Item>>] {}
}
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.89.0-nightly (dcecb9917 2025-05-09)
binary: rustc
commit-hash: dcecb99176edf2eec51613730937d21cdd5c8f6e
commit-date: 2025-05-09
host: x86_64-pc-windows-msvc
release: 1.89.0-nightly
LLVM version: 20.1.4
```

### Error output

```
error[E0186]: method `next` has a `&mut self` declaration in the trait, but not in the impl
    |
197 |     fn next() -> [(); std::mem::size_of::<Option<Self::Item>>] {}
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut self` in impl
    |
    = note: `next` from trait: `fn(&mut Self) -> Option<<Self as Iterator>::Item>`

error[E0046]: not all trait items implemented, missing: `Item`
    |
196 | impl<const N: usize> Iterator for A<N> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Item` in implementation
    |
    = help: implement the missing item: `type Item = /* Type */;`

error: generic `Self` types are currently not permitted in anonymous constants
    |
197 |     fn next() -> [(); std::mem::size_of::<Option<Self::Item>>] {}
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_middle\src\ty\sty.rs:364:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff96d220282 - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ff96d220282 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff96d220282 - std::sys::backtrace::_print_fmt
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\sys\backtrace.rs:66
   3:     0x7ff96d220282 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\sys\backtrace.rs:39
   4:     0x7ff96d252aab - core::fmt::rt::Argument::fmt
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\core\src\fmt\rt.rs:181
   5:     0x7ff96d252aab - core::fmt::write
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\core\src\fmt\mod.rs:1446
   6:     0x7ff96d2160a7 - std::io::default_write_fmt
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\io\mod.rs:639
   7:     0x7ff96d2160a7 - std::io::Write::write_fmt<std::sys::stdio::windows::Stderr>
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\io\mod.rs:1914
   8:     0x7ff96d2200c5 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\sys\backtrace.rs:42
   9:     0x7ff96d225d4a - std::panicking::default_hook::closure$0
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\panicking.rs:300
  10:     0x7ff96d225ae0 - std::panicking::default_hook
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\panicking.rs:327
  11:     0x7ff96e9410bf - core[9d60ee0329d566fc]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[748db264f8602b7b]::Level, &str), usize), <((rustc_lint_defs[748db264f8602b7b]::Level, &str), usize) as core[9d60ee0329d566fc]::cmp::PartialOrd>::lt>
  12:     0x7ff96d2269de - std::panicking::rust_panic_with_hook
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\panicking.rs:841
  13:     0x7ff96d226702 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\panicking.rs:699
  14:     0x7ff96d22104f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\sys\backtrace.rs:168
  15:     0x7ff96d22633e - std::panicking::begin_panic_handler
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\panicking.rs:697
  16:     0x7ff9703d3351 - core::panicking::panic_fmt
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\core\src\panicking.rs:75
  17:     0x7ff9703d340d - core::panicking::panic
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\core\src\panicking.rs:145
  18:     0x7ff9703d32ce - core::option::unwrap_failed
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\core\src\option.rs:2040
  19:     0x7ff96d0aa4c6 - <rustc_middle[8660d27183fc6825]::ty::sty::ParamConst>::find_ty_from_env
  20:     0x7ff96e281f71 - <rustc_trait_selection[58084ddd0cf58050]::traits::fulfill::FulfillProcessor as rustc_data_structures[9935af3ebed2be53]::obligation_forest::ObligationProcessor>::process_obligation
  21:     0x7ff96e1c843b - <rustc_data_structures[9935af3ebed2be53]::obligation_forest::ObligationForest<rustc_trait_selection[58084ddd0cf58050]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[58084ddd0cf58050]::traits::fulfill::FulfillProcessor>
  22:     0x7ff96d4d87bc - <rustc_hir_typeck[bfa3800aa3d4f1a2]::upvar::InferBorrowKind as rustc_hir_typeck[bfa3800aa3d4f1a2]::expr_use_visitor::Delegate>::borrow
  23:     0x7ff96d48e2bf - rustc_hir_typeck[bfa3800aa3d4f1a2]::typeck
  24:     0x7ff96e17427b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  25:     0x7ff96e0acd04 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  26:     0x7ff96e17c7b2 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  27:     0x7ff96d8813c3 - rustc_mir_build[d6bf2d72d7ee99f6]::thir::pattern::check_match::check_match
  28:     0x7ff96e171e1b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  29:     0x7ff96e0a7a4e - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  30:     0x7ff96e17d160 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  31:     0x7ff96d8167b5 - rustc_mir_build[d6bf2d72d7ee99f6]::builder::build_mir
  32:     0x7ff96d6bb3f8 - rustc_mir_transform[581157cbd5ddc9bf]::mir_built
  33:     0x7ff96e17447b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  34:     0x7ff96e0acd04 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  35:     0x7ff96e178552 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  36:     0x7ff96d6ba7a8 - rustc_mir_transform[581157cbd5ddc9bf]::mir_const_qualif
  37:     0x7ff96e172ce0 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  38:     0x7ff96e03bb7b - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches10DefIdCacheINtNtNtCsbxi6Ha6uNij_12rustc_middle5query5erase6ErasedAhj4_EEKb0_KB3q_KB3q_ENtNtB1e_8plumbing9QueryCtxtK
  39:     0x7ff96e178471 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  40:     0x7ff96d6bdcf1 - rustc_mir_transform[581157cbd5ddc9bf]::mir_promoted
  41:     0x7ff96e1722f9 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  42:     0x7ff96e0a4041 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  43:     0x7ff96e178b02 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  44:     0x7ff96d96d0c8 - rustc_borrowck[d16af58a5736816b]::mir_borrowck
  45:     0x7ff96e17227b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  46:     0x7ff96e0acd04 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  47:     0x7ff96e17cd12 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  48:     0x7ff96d6ce6f8 - rustc_mir_transform[581157cbd5ddc9bf]::mir_drops_elaborated_and_const_checked
  49:     0x7ff96e173f1b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  50:     0x7ff96e0acd04 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  51:     0x7ff96e178912 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  52:     0x7ff96d6cb2cf - rustc_mir_transform[581157cbd5ddc9bf]::mir_for_ctfe
  53:     0x7ff96e1722b0 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  54:     0x7ff96e03d935 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches10DefIdCacheINtNtNtCsbxi6Ha6uNij_12rustc_middle5query5erase6ErasedAhj8_EEKb0_KB3q_KB3q_ENtNtB1e_8plumbing9QueryCtxtK
  55:     0x7ff96e178a14 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  56:     0x7ff96dae4f89 - rustc_const_eval[5e4b847289603190]::interpret::eval_context::mir_assign_valid_types
  57:     0x7ff96dca060c - rustc_const_eval[5e4b847289603190]::const_eval::eval_queries::eval_to_allocation_raw_provider
  58:     0x7ff96e1734c8 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  59:     0x7ff96e06a393 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheINtNtCsbxi6Ha6uNij_12rustc_middle2ty20PseudoCanonicalInputNtNtNtB2x_3mir9interpret8GlobalIdEINtNtNtB2x
  60:     0x7ff96e17cf03 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  61:     0x7ff96cb6f0c5 - rustc_const_eval[5e4b847289603190]::const_eval::valtrees::eval_to_valtree
  62:     0x7ff969b79b77 - <alloc[1be1f531b41370bc]::sync::Arc<jiff[27f6babda31ce97f]::tz::db::Kind>>::drop_slow
  63:     0x7ff96cd9abe8 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id8CrateNumINtNtNtCsbxi6Ha6uNij_12r
  64:     0x7ff96cd7089b - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id8CrateNumINtNtNtCsbxi6Ha6uNij_12r
  65:     0x7ff96e06a4ec - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheINtNtCsbxi6Ha6uNij_12rustc_middle2ty20PseudoCanonicalInputNtNtNtB2x_3mir9interpret8GlobalIdEINtNtNtB2x
  66:     0x7ff96cdb2653 - rustc_query_impl[993ab63a0c6afe36]::query_system
  67:     0x7ff96d0a65cb - <rustc_middle[8660d27183fc6825]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  68:     0x7ff96d0a5786 - <rustc_middle[8660d27183fc6825]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  69:     0x7ff96cebc54f - rustc_trait_selection[58084ddd0cf58050]::traits::try_evaluate_const
  70:     0x7ff96ceb57ec - <rustc_trait_selection[58084ddd0cf58050]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[829588816c884077]::fold::TypeFolder<rustc_middle[8660d27183fc6825]::ty::context::TyCtxt>>::fold_const
  71:     0x7ff96e21bc18 - <rustc_trait_selection[58084ddd0cf58050]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[829588816c884077]::fold::TypeFolder<rustc_middle[8660d27183fc6825]::ty::context::TyCtxt>>::fold_ty
  72:     0x7ff96d54f778 - rustc_hir_analysis[284df9e8bdc6f5c4]::check::region::region_scope_tree
  73:     0x7ff96d5c0fcf - <rustc_hir_analysis[284df9e8bdc6f5c4]::check::wfcheck::check_where_clauses::{closure#2}::CountParams as rustc_type_ir[829588816c884077]::visit::TypeVisitor<rustc_middle[8660d27183fc6825]::ty::context::TyCtxt>>::visit_ty
  74:     0x7ff96d551294 - rustc_hir_analysis[284df9e8bdc6f5c4]::check::region::region_scope_tree
  75:     0x7ff96d554efe - rustc_hir_analysis[284df9e8bdc6f5c4]::check::wfcheck::check_well_formed
  76:     0x7ff96e172d7b - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  77:     0x7ff96e0a7cee - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id10LocalDefIdINtNtNtCsbxi6Ha6uNij_
  78:     0x7ff96e183785 - rustc_query_impl[993ab63a0c6afe36]::plumbing::query_key_hash_verify_all
  79:     0x7ff96d566dea - rustc_hir_analysis[284df9e8bdc6f5c4]::check::wfcheck::check_mod_type_wf
  80:     0x7ff96cd9ba3b - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id8CrateNumINtNtNtCsbxi6Ha6uNij_12r
  81:     0x7ff96cce5976 - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id13LocalModDefIdINtNtNtCsbxi6Ha6uNij_12rustc_middle5query5erase6Er
  82:     0x7ff96cdb0160 - rustc_query_impl[993ab63a0c6afe36]::query_system
  83:     0x7ff96d5b2d6e - rustc_hir_analysis[284df9e8bdc6f5c4]::check_crate
  84:     0x7ff96d28a1f6 - <rustc_interface[642e9f6cacad30a4]::passes::LintStoreExpandImpl as rustc_expand[6c773f9594c871da]::base::LintStoreExpand>::pre_expansion_lint
  85:     0x7ff969b8dbf7 - rustc_interface[642e9f6cacad30a4]::passes::analysis
  86:     0x7ff96cd9e7ca - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtCsd9wXIVlvcyJ_21rustc_data_structures9vec_cache8VecCacheNtNtCs4F9Gp71IGkq_10rustc_span6def_id8CrateNumINtNtNtCsbxi6Ha6uNij_12r
  87:     0x7ff96cca730a - RINvNtNtCsi9HO7w7UkL_18rustc_query_system5query8plumbing17try_execute_queryINtCsd9DrxHbgjXe_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsbxi6Ha6uNij_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3r_KB3r_ENtNtB1e_8plumbing9QueryCtxt
  88:     0x7ff96cda4df3 - rustc_query_impl[993ab63a0c6afe36]::query_system
  89:     0x7ff969b4ecf8 - std[547ad0aa56f99cda]::sys::backtrace::__rust_begin_short_backtrace::<<std[547ad0aa56f99cda]::thread::Builder>::spawn_unchecked_<ctrlc[8beb5292918c80fb]::set_handler_inner<rustc_driver_impl[ee03924009af6117]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  90:     0x7ff969b48f36 - std[547ad0aa56f99cda]::sys::backtrace::__rust_begin_short_backtrace::<<std[547ad0aa56f99cda]::thread::Builder>::spawn_unchecked_<ctrlc[8beb5292918c80fb]::set_handler_inner<rustc_driver_impl[ee03924009af6117]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  91:     0x7ff969b4413f - RINvNtNtCs7fGoaO6NkXC_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCs8BgyDmMp6lY_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCskqWrDiLSCdn_17rustc_driver_i
  92:     0x7ff969b53050 - std[547ad0aa56f99cda]::sys::backtrace::__rust_begin_short_backtrace::<<std[547ad0aa56f99cda]::thread::Builder>::spawn_unchecked_<ctrlc[8beb5292918c80fb]::set_handler_inner<rustc_driver_impl[ee03924009af6117]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  93:     0x7ff96d22ad6d - alloc::boxed::impl$28::call_once
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\alloc\src\boxed.rs:1966
  94:     0x7ff96d22ad6d - alloc::boxed::impl$28::call_once
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\alloc\src\boxed.rs:1966
  95:     0x7ff96d22ad6d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/dcecb99176edf2eec51613730937d21cdd5c8f6e/library\std\src\sys\pal\windows\thread.rs:56
  96:     0x7ffa0f247374 - BaseThreadInitThunk
  97:     0x7ffa1063cc91 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `D:\rust_test\test1\src\rustc-ice-2025-05-10T11_55_56-33528.txt` to your bug report

query stack during panic:
#0 [typeck] type-checking `<impl at .\test.rs:2:1: 2:39>::next::{constant#0}`
#1 [check_match] match-checking `<impl at .\test.rs:2:1: 2:39>::next::{constant#0}`
... and 11 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
error: aborting due to 3 previous errors
```

</p>
</details>

### LINKED ISSUE #144547: Panic when using constant from associated type trait impl
### Code [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=e33362c7b4731f262abf2d47e1e2a460)

```Rust
trait UnderlyingImpl<const MAX_SIZE: usize> {
    type InfoType: LevelInfo;
    type SupportedArray<T>;
}

trait LevelInfo {
    const SUPPORTED_SLOTS: usize;
}

struct Info;

impl LevelInfo for Info {
    const SUPPORTED_SLOTS: usize = 1;
}

struct SomeImpl;

impl<const MAX_SIZE: usize> UnderlyingImpl<MAX_SIZE> for SomeImpl {
    type InfoType = Info;
    // This line makes compiler panic
    type SupportedArray<T> = [T; <Self::InfoType as LevelInfo>::SUPPORTED_SLOTS];
    // But this works
    //type SupportedArray<T> = [T; <Info as LevelInfo>::SUPPORTED_SLOTS];
}
```

### Meta (local)

`rustc --version --verbose`: 
Same behavior on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=e33362c7b4731f262abf2d47e1e2a460) (both stable and nightly)
```
rustc 1.90.0-nightly (8f08b3a32 2025-07-18)
binary: rustc
commit-hash: 8f08b3a32478b8d0507732800ecb548a76e0fd0c
commit-date: 2025-07-18
host: x86_64-pc-windows-msvc
release: 1.90.0-nightly
LLVM version: 20.1.8
```

<details><summary><strong>Error output</strong></summary>
<p>

```
Compiling playground v0.0.1 (/playground)

thread 'rustc' panicked at compiler/rustc_middle/src/ty/sty.rs:364:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7924dcd46543 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h46a716bba2450163
   1:     0x7924dd405947 - core::fmt::write::h275e5980d7008551
   2:     0x7924de4c16d1 - std::io::Write::write_fmt::h561a66a0340b6995
   3:     0x7924dcd463a2 - std::sys::backtrace::BacktraceLock::print::hafb9d5969adc39a0
   4:     0x7924dcd49f9a - std::panicking::default_hook::{{closure}}::hae2e97a5c4b2b777
   5:     0x7924dcd49b1f - std::panicking::default_hook::h3db1b505cfc4eb79
   6:     0x7924dbd75b93 - std[61bb86a81f0491]::panicking::update_hook::<alloc[7c55b5a5cf9e3c5f]::boxed::Box<rustc_driver_impl[b7d73271a09ede7d]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7924dcd4a813 - std::panicking::rust_panic_with_hook::h409da73ddef13937
   8:     0x7924dcd4a4d6 - std::panicking::begin_panic_handler::{{closure}}::h159b61b27f96a9c2
   9:     0x7924dcd46a09 - std::sys::backtrace::__rust_end_short_backtrace::h5b56844d75e766fc
  10:     0x7924dcd4a1cd - __rustc[4794b31dd7191200]::rust_begin_unwind
  11:     0x7924d9685620 - core::panicking::panic_fmt::hc8737e8cca20a7c8
  12:     0x7924d9689ddc - core::panicking::panic::h4a11c031239f36a8
  13:     0x7924d9685f99 - core::option::unwrap_failed::h62317944fa5dc382
  14:     0x7924df135866 - <rustc_middle[1134768a56a896b4]::ty::sty::ParamConst>::find_ty_from_env.cold
  15:     0x7924dddc9031 - <rustc_trait_selection[cbbc305c14e6b9fb]::traits::fulfill::FulfillProcessor as rustc_data_structures[e24569e090b577b3]::obligation_forest::ObligationProcessor>::process_obligation
  16:     0x7924dd407566 - <rustc_data_structures[e24569e090b577b3]::obligation_forest::ObligationForest<rustc_trait_selection[cbbc305c14e6b9fb]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[cbbc305c14e6b9fb]::traits::fulfill::FulfillProcessor>
  17:     0x7924dd7d8f23 - rustc_hir_typeck[69b4494f2e6af28b]::typeck_with_inspect::{closure#0}
  18:     0x7924dd7d7ab6 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  19:     0x7924dd7c9366 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  20:     0x7924dd7c8dd2 - rustc_query_impl[6f0ca6887c150a69]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7924ddbeebc1 - rustc_mir_build[66235fdd4417f78a]::thir::pattern::check_match::check_match
  22:     0x7924ddbee459 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>>
  23:     0x7924ddc16665 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  24:     0x7924ddc162a1 - rustc_query_impl[6f0ca6887c150a69]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7924dd81a788 - rustc_mir_build[66235fdd4417f78a]::builder::build_mir
  26:     0x7924dd409aab - rustc_mir_transform[bc4f92cb7c061fd1]::mir_built
  27:     0x7924dd409a65 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7924dd7c9366 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  29:     0x7924dd7c8e92 - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7924de1a6695 - rustc_mir_transform[bc4f92cb7c061fd1]::mir_const_qualif
  31:     0x7924de1a65a5 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_const_qualif::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 4usize]>>
  32:     0x7924de1a59fe - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::DefIdCache<rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  33:     0x7924de1a574f - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_const_qualif::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7924dac614b2 - rustc_mir_transform[bc4f92cb7c061fd1]::mir_promoted
  35:     0x7924dd8bd792 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 16usize]>>
  36:     0x7924dd8bda24 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  37:     0x7924dd8bd692 - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7924dd7ca66b - rustc_borrowck[177ef636edd0ce33]::mir_borrowck
  39:     0x7924dd7ca59f - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  40:     0x7924dd7c9366 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  41:     0x7924dd7c8d12 - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7924dd6b5e45 - rustc_mir_transform[bc4f92cb7c061fd1]::mir_drops_elaborated_and_const_checked
  43:     0x7924dd6b5535 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  44:     0x7924dd7c9366 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  45:     0x7924dd7c8c5c - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7924dd892118 - rustc_mir_transform[bc4f92cb7c061fd1]::mir_for_ctfe
  47:     0x7924dd891f4d - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_for_ctfe::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  48:     0x7924dd8800bf - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::DefIdCache<rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  49:     0x7924ddd677a2 - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_for_ctfe::get_query_non_incr::__rust_end_short_backtrace
  50:     0x7924ddd678d0 - <rustc_const_eval[1f8ce8110e3e9be6]::interpret::eval_context::InterpCx<rustc_const_eval[1f8ce8110e3e9be6]::const_eval::machine::CompileTimeMachine>>::load_mir
  51:     0x7924ddd6876b - rustc_const_eval[1f8ce8110e3e9be6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  52:     0x7924ddd68010 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 24usize]>>
  53:     0x7924ddd55e98 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::DefaultCache<rustc_middle[1134768a56a896b4]::ty::PseudoCanonicalInput<rustc_middle[1134768a56a896b4]::mir::interpret::GlobalId>, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  54:     0x7924ddd55a4b - rustc_query_impl[6f0ca6887c150a69]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  55:     0x7924ddd33650 - rustc_const_eval[1f8ce8110e3e9be6]::const_eval::valtrees::eval_to_valtree
  56:     0x7924ddd333d4 - <rustc_const_eval[1f8ce8110e3e9be6]::provide::{closure#0} as core[105cb658ab12d76f]::ops::function::FnOnce<(rustc_middle[1134768a56a896b4]::ty::context::TyCtxt, rustc_middle[1134768a56a896b4]::ty::PseudoCanonicalInput<rustc_middle[1134768a56a896b4]::mir::interpret::GlobalId>)>>::call_once
  57:     0x7924ddd3337e - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 24usize]>>
  58:     0x7924ddd33337 - <rustc_query_impl[6f0ca6887c150a69]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[105cb658ab12d76f]::ops::function::FnOnce<(rustc_middle[1134768a56a896b4]::ty::context::TyCtxt, rustc_middle[1134768a56a896b4]::ty::PseudoCanonicalInput<rustc_middle[1134768a56a896b4]::mir::interpret::GlobalId>)>>::call_once
  59:     0x7924ddd55f7b - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::DefaultCache<rustc_middle[1134768a56a896b4]::ty::PseudoCanonicalInput<rustc_middle[1134768a56a896b4]::mir::interpret::GlobalId>, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  60:     0x7924ddd55955 - rustc_query_impl[6f0ca6887c150a69]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  61:     0x7924dde83600 - <rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  62:     0x7924dde83142 - <rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  63:     0x7924dd8db408 - rustc_trait_selection[cbbc305c14e6b9fb]::traits::try_evaluate_const
  64:     0x7924dd8dabb4 - <rustc_trait_selection[cbbc305c14e6b9fb]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[59256336525b79e2]::fold::TypeFolder<rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>>::fold_const
  65:     0x7924dd5cb191 - <rustc_middle[1134768a56a896b4]::ty::Ty as rustc_type_ir[59256336525b79e2]::fold::TypeSuperFoldable<rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>>::super_fold_with::<rustc_trait_selection[cbbc305c14e6b9fb]::traits::normalize::AssocTypeNormalizer>
  66:     0x7924dd5d0790 - rustc_trait_selection[cbbc305c14e6b9fb]::traits::project::normalize_projection_term
  67:     0x7924dd5c9e34 - <rustc_trait_selection[cbbc305c14e6b9fb]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[59256336525b79e2]::fold::TypeFolder<rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>>::fold_ty
  68:     0x7924ddb7960a - <&rustc_middle[1134768a56a896b4]::ty::list::RawList<(), rustc_middle[1134768a56a896b4]::ty::generic_args::GenericArg> as rustc_type_ir[59256336525b79e2]::fold::TypeFoldable<rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>>::fold_with::<rustc_trait_selection[cbbc305c14e6b9fb]::traits::normalize::AssocTypeNormalizer>
  69:     0x7924ddb79464 - <rustc_trait_selection[cbbc305c14e6b9fb]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[59256336525b79e2]::fold::TypeFolder<rustc_middle[1134768a56a896b4]::ty::context::TyCtxt>>::fold_predicate
  70:     0x7924ddb73953 - rustc_hir_analysis[5a87eb6962d34b42]::check::compare_impl_item::check_type_bounds
  71:     0x7924ddb7fb64 - rustc_hir_analysis[5a87eb6962d34b42]::check::compare_impl_item::compare_impl_item
  72:     0x7924ddb7d2cb - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::compare_impl_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>>
  73:     0x7924ddc16665 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  74:     0x7924ddc16161 - rustc_query_impl[6f0ca6887c150a69]::query_impl::compare_impl_item::get_query_non_incr::__rust_end_short_backtrace
  75:     0x7924dd9cc62c - rustc_hir_analysis[5a87eb6962d34b42]::check::check::check_item_type
  76:     0x7924ddc1886e - rustc_hir_analysis[5a87eb6962d34b42]::check::wfcheck::check_well_formed
  77:     0x7924ddc1704b - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>>
  78:     0x7924ddc168f1 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  79:     0x7924ddc163e6 - rustc_query_impl[6f0ca6887c150a69]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  80:     0x7924ddc13965 - rustc_hir_analysis[5a87eb6962d34b42]::check::wfcheck::check_mod_type_wf
  81:     0x7924ddc1375f - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>>
  82:     0x7924de3eda84 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::DefaultCache<rustc_span[1f7aec696a0836ce]::def_id::LocalModDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  83:     0x7924de3ed811 - rustc_query_impl[6f0ca6887c150a69]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  84:     0x7924dd7c6f72 - rustc_hir_analysis[5a87eb6962d34b42]::check_crate
  85:     0x7924ddde0237 - rustc_interface[a43b584b4c4124b4]::passes::run_required_analyses
  86:     0x7924de2edb5e - rustc_interface[a43b584b4c4124b4]::passes::analysis
  87:     0x7924de2edb35 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 0usize]>>
  88:     0x7924de2efc3a - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::SingleCache<rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, false>
  89:     0x7924de2ef90f - rustc_query_impl[6f0ca6887c150a69]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  90:     0x7924de5aa0c7 - rustc_interface[a43b584b4c4124b4]::passes::create_and_enter_global_ctxt::<core[105cb658ab12d76f]::option::Option<rustc_interface[a43b584b4c4124b4]::queries::Linker>, rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  91:     0x7924de4fe966 - rustc_interface[a43b584b4c4124b4]::interface::run_compiler::<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}
  92:     0x7924de4b523e - std[61bb86a81f0491]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_with_globals<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_pool_with_globals<rustc_interface[a43b584b4c4124b4]::interface::run_compiler<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  93:     0x7924de4b56b4 - <<std[61bb86a81f0491]::thread::Builder>::spawn_unchecked_<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_with_globals<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_pool_with_globals<rustc_interface[a43b584b4c4124b4]::interface::run_compiler<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[105cb658ab12d76f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  94:     0x7924de4b6aab - std::sys::pal::unix::thread::Thread::new::thread_start::h1822d22fde68314f
  95:     0x7924d828aaa4 - <unknown>
  96:     0x7924d8317a34 - clone
  97:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.88.0 (6b00bc388 2025-06-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#1 [check_match] match-checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
... and 12 other queries... use `env RUST_BACKTRACE=1` to see the full query stack
error: could not compile `playground` (lib)

Caused by:
  process didn't exit successfully: `/playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name playground --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=88d75c911cfddd04 -C extra-filename=-013ef0dffb93ce85 --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps [...] (deleted bcs 65536 character limit)` (exit status: 101)
```
</p>
</details>

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_middle/src/ty/sty.rs:364:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: <rustc_middle::ty::sty::ParamConst>::find_ty_from_env.cold
   5: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
   6: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
   7: rustc_hir_typeck::typeck_with_inspect::{closure#0}
      [... omitted 1 frame ...]
   8: rustc_mir_build::thir::pattern::check_match::check_match
      [... omitted 1 frame ...]
   9: rustc_mir_build::builder::build_mir
  10: rustc_mir_transform::mir_built
      [... omitted 1 frame ...]
  11: rustc_mir_transform::mir_const_qualif
      [... omitted 1 frame ...]
  12: rustc_mir_transform::mir_promoted
      [... omitted 1 frame ...]
  13: rustc_borrowck::mir_borrowck
      [... omitted 1 frame ...]
  14: rustc_mir_transform::mir_drops_elaborated_and_const_checked
      [... omitted 1 frame ...]
  15: rustc_mir_transform::mir_for_ctfe
      [... omitted 1 frame ...]
  16: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeMachine>>::load_mir
  17: rustc_const_eval::const_eval::eval_queries::eval_to_allocation_raw_provider
      [... omitted 1 frame ...]
  18: rustc_const_eval::const_eval::valtrees::eval_to_valtree
  19: <rustc_const_eval::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::PseudoCanonicalInput<rustc_middle::mir::interpret::GlobalId>)>>::call_once
      [... omitted 2 frames ...]
  20: <rustc_middle::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  21: <rustc_middle::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  22: rustc_trait_selection::traits::try_evaluate_const
  23: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const
  24: <rustc_middle::ty::Ty as rustc_type_ir::fold::TypeSuperFoldable<rustc_middle::ty::context::TyCtxt>>::super_fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
  25: rustc_trait_selection::traits::project::normalize_projection_term
  26: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_ty
  27: <&rustc_middle::ty::list::RawList<(), rustc_middle::ty::generic_args::GenericArg> as rustc_type_ir::fold::TypeFoldable<rustc_middle::ty::context::TyCtxt>>::fold_with::<rustc_trait_selection::traits::normalize::AssocTypeNormalizer>
  28: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_predicate
  29: rustc_hir_analysis::check::compare_impl_item::check_type_bounds
  30: rustc_hir_analysis::check::compare_impl_item::compare_impl_item
      [... omitted 1 frame ...]
  31: rustc_hir_analysis::check::check::check_item_type
  32: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  33: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
      [... omitted 1 frame ...]
  34: rustc_hir_analysis::check_crate
  35: rustc_interface::passes::run_required_analyses
  36: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  37: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  38: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.88.0 (6b00bc388 2025-06-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#1 [check_match] match-checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#2 [mir_built] building MIR for `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#3 [mir_const_qualif] const checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#4 [mir_promoted] promoting constants in MIR for `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#5 [mir_borrowck] borrow-checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#6 [mir_drops_elaborated_and_const_checked] elaborating drops for `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#7 [mir_for_ctfe] caching mir of `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}` for CTFE
#8 [eval_to_allocation_raw] const-evaluating + checking `<impl at src/lib.rs:18:1: 18:66>::SupportedArray::{constant#0}`
#9 [eval_to_valtree] evaluating type-level constant
#10 [compare_impl_item] checking assoc item `<impl at src/lib.rs:18:1: 18:66>::SupportedArray` is compatible with trait definition
#11 [check_well_formed] checking that `<impl at src/lib.rs:18:1: 18:66>` is well-formed
#12 [check_mod_type_wf] checking that types are well-formed in top-level module
#13 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `playground` (lib)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by camelid**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/150519)*

Fixes rust-lang/rust#144547.
Fixes rust-lang/rust#140891.

In the future, we likely want to make the check less likely to be missed by reducing the number of external entry points to HIR type lowering.

Note: If this causes pass->error regressions (not truly regressions because those cases were mistakenly accepted), they can easily be avoided for the time being by only running the check if `is_self_alias` is true or mgca is enabled.

- **Fix parsing of mgca const blocks in array repeat exprs**
- **Use more principled check for generics in const ops**

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 1]
```diff
@@ -2184,6 +2204,30 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
+        &self,
+        param_use_hir_id: HirId,
+    ) -> Option<ErrorGuaranteed> {
+        let tcx = self.tcx();
+
+        let parent_def_id = self.item_def_id();
+        if tcx.features().min_generic_const_args()
+            && tcx.def_kind(parent_def_id) == DefKind::AnonConst
+            && let ty::AnonConstKind::MCG = tcx.anon_const_kind(parent_def_id)
+            && tcx.generics_of(parent_def_id).is_empty()
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]:
```suggestion
```
i think this should definitionally be true of all `AnonConstKind::MCG`

File: tests/ui/const-generics/min_const_generics/self-ty-in-const-2.stderr [hunk 2]
```diff
@@ -1,14 +1,8 @@
-error: generic `Self` types are currently not permitted in anonymous constants
+error: generic parameters may not be used in const operations
```
Comment (BoxyUwU) [inline tests/ui/const-generics/min_const_generics/self-ty-in-const-2.stderr]: this feels like an unfortuante diagnostic regression. want to pass in something to `check_param_use_if_mcg` to say whether the term is from a Self alias or not

File: tests/ui/const-generics/mgca/explicit_anon_consts-7.rs [hunk 3]
```diff
@@ -0,0 +1,10 @@
+#![feature(min_generic_const_args)]
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/explicit_anon_consts-7.rs]: all the `explicit_anon_consts-1..6` tests should be able to be moved back into `explicit_anon_const.rs` now. ie delete them all and uncomment all the commented out tests in `explicit_anon_consts.rs`.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 4]
```diff
@@ -2184,6 +2230,28 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
         }
     }
 
+    pub fn check_param_use_if_in_anon_const(
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: consolidate this with `check_param_use_if_mcg` instead of having both

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 5]
```diff
@@ -394,7 +394,65 @@ pub trait GenericArgsLowerer<'a, 'tcx> {
...
+        if matches!(r.kind(), ty::RegionKind::ReEarlyParam(..) | ty::RegionKind::ReLateParam(..)) {
+            return ty::Region::new_error(self.tcx, self.error());
+        }
+        r
+    }
+}
+
 impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
+    #[must_use = "need to use transformed output"]
+    fn check_param_uses_if_mcg<T>(&self, term: T, span: Span) -> T
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: can u add a flag for whether to only actually perform the check here if `mgca` is enabled? I think we should only use this codepath on stable for the `Self` ty alias handling, and otherwise the other codepaths should only fold under `mgca`.

I realised that if we want to land this "everywhere" it'll actually need a crater run and an FCP which will likely take over a month given how slow crater is nowadays. If we go through all that work we may as well spend that time doing a proper impl that is less likely to miss cases and then crater/FCP *that*.

So in the meanwhile I'd like to make MGCA work nicer and leave enabling this "everywhere" to a separate PR that can proceed in parallel

I realise I kinda asked you to un-feature-gate this earlier so my bad :<

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 6]
```diff
@@ -394,7 +394,130 @@ pub trait GenericArgsLowerer<'a, 'tcx> {
...
+    /// See [`Self::check_param_uses_if_mcg`].
+    /// 
+    /// FIXME(mgca): this is pub only for instantiate_value_path and would be nice to avoid altogether
+    pub fn check_param_res_if_mcg_for_instantiate_value_path(
+        &self,
+        res: Res,
+        span: Span,
+    ) -> Result<(), ErrorGuaranteed> {
+        let tcx = self.tcx();
+        // FIXME(mgca): this should always be performed but needs FCP
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs]: I think this actually doesn't need an FCP as nothing should hit this codepath on stable :thinking:

**Comment by BoxyUwU** [comment]
Perf regression is unfortunate. I'm not sure what we can do about it :thinking: Doing more work here feels somewhat unavoidable and also necessary to fix the ICEs and generally correctly handle forbidding uses of generic parameters introduced after name resolution :frowning_face:

**Comment by Kobzol** [comment]
It's a tiny regression on diesel, I think that we can eat this one.

@rustbot label: +perf-regression-triaged
