### PR TITLE
Fixes #53119.

### LINKED ISSUE #53119: [nll] `gluon_base` does not compile with NLL
I reduced a crater run failure of `gluon_base` v0.8.0 to [this standalone snippet](https://play.rust-lang.org/?gist=4cfa7a80bffea0a12f1f73e7981378b1&version=nightly&mode=debug&edition=2015):

```rust
#![feature(nll)]

use std::ops::Deref;

pub struct TypeFieldIterator<'a, T: 'a> {
    typ: &'a T,
    current: usize,
}

pub enum Type<Id, T> {
    Unit,

    Record(T),
    
    ExtendRow {
        types: Vec<(Id, T)>,
        rest: T,
    },
}

impl<'a, Id: 'a, T> Iterator for TypeFieldIterator<'a, T>
where
    T: Deref<Target = Type<Id, T>>,
{
    type Item = &'a (Id, T);
    
    fn next(&mut self) -> Option<&'a (Id, T)> {
        match **self.typ {
            Type::Unit => None,

            Type::Record(ref row) => {
                self.typ = row;
                self.next()
            }
            
            Type::ExtendRow { ref types, ref rest } => {
                let current = self.current;
                self.current += 1;
                types.get(current).or_else(|| {
                    self.current = 0;
                    self.typ = rest;
                    self.next()
                })
            }            
        }
    }
}

fn main() { }
```

this compiles without NLL; with NLL it fails with:

```
error[E0310]: the parameter type `Id` may not live long enough
  --> src/main.rs:39:44
   |
39 |                   types.get(current).or_else(|| {
   |  ____________________________________________^
40 | |                     self.current = 0;
41 | |                     self.typ = rest;
42 | |                     self.next()
43 | |                 })
   | |_________________^
   |
   = help: consider adding an explicit lifetime bound `Id: 'static`...
```

I think this is some kind of failure from the "closure checking" code.

### PR DESCRIPTION
**Pull request by mikhail-m1**
Fixes #53119.

I minimized sample little bit more, but I checked the sample from issue too.
r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs [hunk 1]
```diff
@@ -661,28 +661,33 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
-        let lower_bound_plus = self.non_local_universal_upper_bound(*lower_bound);
-        assert!(self.universal_regions.is_universal_region(lower_bound_plus));
-        assert!(
-            !self
+        // For each region outlived by lower_bound find a non-local,
+        // universal region (it may be the same region) and add it to
+        // `ClosureOutlivesRequirement`.
+        let r_scc = self.constraint_sccs.scc(*lower_bound);
+        for ur in self.scc_values.universal_regions_outlived_by(r_scc) {
+            let non_local_ub = self.universal_region_relations.non_local_upper_bound(ur);
```
Comment (mikhail-m1) [inline src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: I cannot use `non_local_universal_upper_bound` because it returns `'static` for `'_#5r` from your comment in the issue

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: seems fine

File: src/librustc_mir/borrow_check/nll/region_infer/mod.rs [hunk 2]
```diff
@@ -661,28 +661,33 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
-        // Find some bounding subject-region R+ that is a super-region
-        // of the existing subject-region R. This should be a non-local, universal
-        // region, which ensures it can be encoded in a `ClosureOutlivesRequirement`.
-        let lower_bound_plus = self.non_local_universal_upper_bound(*lower_bound);
-        assert!(self.universal_regions.is_universal_region(lower_bound_plus));
-        assert!(
-            !self
+        // For each region outlived by lower_bound find a non-local,
+        // universal region (it may be the same region) and add it to
+        // `ClosureOutlivesRequirement`.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/region_infer/mod.rs]: OK, this looks good except that I'd like to expand this comment I think. Actually, maybe we should just put the comment on the fn itself? Something like this:

---

Invoked when we have some type-test (e.g., `T: 'X`) that we cannot prove to be satisfied. If this is a closure, we will attempt to "promote" this type-test into our `ClosureRegionRequirements` and hence pass it up the creator. To do this, we have to phrase the type-test in terms of external free regions, as local free regions are not nameable by the closure's creator. 

Promotion works as follows: we first check that the type T contains only regions that the creator knows about. If this is true, then -- as a consequence -- we know that all regions in the type T are free regions that outlive the closure body. If false, then promotion fails.

Once we've promoted `T`, we have to "promote" 'X to some region that is "external" to the closure. Generally speaking, a region may be the union of some points in the closure body as well as various free lifetimes. We can ignore the points in the closure body: if the type T can be expressed in terms of external regions, we know it outlives the points in the closure body. That just leaves the free regions.

The idea then is to lower the `T: 'X` constraint into multiple bounds -- e.g., if `'X` is the union of two free lifetimes, `'1` and `'2`, then we would create `T: '1` and `T: '2`.

**Review by nikomatsakis — APPROVED** [review]
Nice! Left a nit requesting a new comment.

**Comment by nikomatsakis** [comment]
@bors r+ p=1

This is a RC blocker for NLL.
