### PR TITLE
Show the used type variable when issuing a "can't use type parameters from outer function" error message

### LINKED ISSUE #14844: suggest binding site when issuing "try using a local type parameter instead" err msg
UPDATE: [Mentoring instructions below.](https://github.com/rust-lang/rust/issues/14844#issuecomment-331316573)

--

Here is some code:

``` rust
pub trait Bar { fn m(&self); }

pub fn foo<T>() {
    struct S<T>;
    impl Bar for S<T> {
        fn m(&self) { println!("Hello World"); }
    }
    let s = S::<T>;
    s.m();
}

pub fn main() {
    foo::<int>();
}
```

Here is a transcript of a compilation attempt:

```
% rustc /tmp/bar.rs
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
/tmp/bar.rs:9:7: 9:10 error: type `foo::S<T>` does not implement any method in scope named `m`
/tmp/bar.rs:9     s.m();
                    ^~~
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `fn(&foo::S<T>)`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `fn(&foo::S<T>)`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: aborting due to 11 previous errors
% 
```

First off, maybe we should be aborting the compilation a little sooner rather than emitting so many seemingly redundant error messages.

Second, I was scratching my head for a little while because I was saying to myself "`T` _is_ a local type parameter".  Of course, it is not local _enough_; one needs to change the `impl Bar for S<T>` to `impl<T> Bar for S<T>`.

So, I think it would be good if the error message suggested this; e.g.:

> error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try adding a local type parameter to the `impl`

or

> error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter like `impl<T> Bar for ...`

### PR DESCRIPTION
**Pull request by zilbuz**
Fix #14844 

r? @estebank

### CODE REVIEW

**Comment by zilbuz** [comment]
@estebank I've got a compile error with my current edits that I don't understand: 
```
error[E0119]: conflicting implementations of trait `iter_private::TrustedRandomAccess` for type `iter::Cloned<_>`:
   --> libcore\iter\mod.rs:593:1
    |
581 | / default unsafe impl<'a, I, T: 'a> TrustedRandomAccess for Cloned<I>
582 | |     where I: TrustedRandomAccess<Item=&'a T>, T: Clone
583 | | {
584 | |     unsafe fn get_unchecked(&mut self, i: usize) -> Self::Item {
...   |
589 | |     fn may_have_side_effect() -> bool { true }
590 | | }
    | |_- first implementation here
...
593 | / unsafe impl<'a, I, T: 'a> TrustedRandomAccess for Cloned<I>
594 | |     where I: TrustedRandomAccess<Item=&'a T>, T: Copy
595 | | {
596 | |     unsafe fn get_unchecked(&mut self, i: usize) -> Self::Item {
...   |
601 | |     fn may_have_side_effect() -> bool { false }
602 | | }
    | |_^ conflicting implementation for `iter::Cloned<_>`

error: aborting due to previous error

error: Could not compile `core`.
```

Do you have an idea of where that could come from? How could I gather more informations to debug this kind of error, because the error seems very far from the edits that I did?

**Comment by zilbuz** [comment]
Alright some more details: the compilation seems to fail when I copy the span argument of the `ParamTy::new()` function to the structure. 

With: 
```rust
#[derive(Clone, Copy, PartialEq, Eq, Hash, RustcEncodable, RustcDecodable)]
pub struct ParamTy {
    pub idx: u32,
    pub name: Name,
    pub span: Span,
}
```

This works:
```rust
    pub fn new(index: u32, name: Name, _span: Span) -> ParamTy {
        ParamTy { idx: index, name: name, span: DUMMY_SP }
    }
```

This doesn't (compilation error: https://github.com/rust-lang/rust/pull/47574#issuecomment-358961722):
```rust
    pub fn new(index: u32, name: Name, span: Span) -> ParamTy {
        ParamTy { idx: index, name: name, span: span }
    }
```

**Comment by estebank** [comment]
You're indeed right that it doesn't seem to be _caused_ by your code, but somehow triggered by the change. It is indeed quite weird.

The code you've written looks correct to me. Can you provide the full compiler output? I'm intrigued as to what stage this is happening in.

**Comment by zilbuz** [comment]
It's failing when compiling stage 1 std artifacts.

Build log:
<details>

```
Updating submodules
    Finished dev [unoptimized] target(s) in 0.0 secs
Building stage0 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 std from stage0 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Building stage0 test artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 test from stage0 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Building stage0 compiler artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling rustc v0.0.0 (file:///C:/rust/src/librustc)
   Compiling rustc_incremental v0.0.0 (file:///C:/rust/src/librustc_incremental)
   Compiling rustc_typeck v0.0.0 (file:///C:/rust/src/librustc_typeck)
   Compiling rustc_metadata v0.0.0 (file:///C:/rust/src/librustc_metadata)
   Compiling rustc_allocator v0.0.0 (file:///C:/rust/src/librustc_allocator)
   Compiling rustc_trans_utils v0.0.0 (file:///C:/rust/src/librustc_trans_utils)
   Compiling rustc_resolve v0.0.0 (file:///C:/rust/src/librustc_resolve)
   Compiling rustc_const_eval v0.0.0 (file:///C:/rust/src/librustc_const_eval)
   Compiling rustc_plugin v0.0.0 (file:///C:/rust/src/librustc_plugin)
   Compiling rustc_passes v0.0.0 (file:///C:/rust/src/librustc_passes)
   Compiling rustc_lint v0.0.0 (file:///C:/rust/src/librustc_lint)
   Compiling rustc_mir v0.0.0 (file:///C:/rust/src/librustc_mir)
   Compiling rustc_privacy v0.0.0 (file:///C:/rust/src/librustc_privacy)
   Compiling rustc_save_analysis v0.0.0 (file:///C:/rust/src/librustc_save_analysis)
   Compiling rustc_trans v0.0.0 (file:///C:/rust/src/librustc_trans)
   Compiling rustc_borrowck v0.0.0 (file:///C:/rust/src/librustc_borrowck)
   Compiling rustc_driver v0.0.0 (file:///C:/rust/src/librustc_driver)
   Compiling rustc-main v0.0.0 (file:///C:/rust/src/rustc)
    Finished release [optimized] target(s) in 207.72 secs
Copying stage0 rustc from stage0 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Assembling stage1 compiler (x86_64-pc-windows-msvc)
Building stage1 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling cc v1.0.4
   Compiling core v0.0.0 (file:///C:/rust/src/libcore)
   Compiling unwind v0.0.0 (file:///C:/rust/src/libunwind)
   Compiling cfg-if v0.1.2
   Compiling filetime v0.1.15
   Compiling build_helper v0.1.0 (file:///C:/rust/src/build_helper)
   Compiling std v0.0.0 (file:///C:/rust/src/libstd)
   Compiling compiler_builtins v0.0.0 (file:///C:/rust/src/rustc/compiler_builtins_shim)
error[E0119]: conflicting implementations of trait `iter_private::TrustedRandomAccess` for type `iter::Cloned<_>`:
   --> libcore\iter\mod.rs:593:1
    |
581 | / default unsafe impl<'a, I, T: 'a> TrustedRandomAccess for Cloned<I>
582 | |     where I: TrustedRandomAccess<Item=&'a T>, T: Clone
583 | | {
584 | |     unsafe fn get_unchecked(&mut self, i: usize) -> Self::Item {
...   |
589 | |     fn may_have_side_effect() -> bool { true }
590 | | }
    | |_- first implementation here
...
593 | / unsafe impl<'a, I, T: 'a> TrustedRandomAccess for Cloned<I>
594 | |     where I: TrustedRandomAccess<Item=&'a T>, T: Copy
595 | | {
596 | |     unsafe fn get_unchecked(&mut self, i: usize) -> Self::Item {
...   |
601 | |     fn may_have_side_effect() -> bool { false }
602 | | }
    | |_^ conflicting implementation for `iter::Cloned<_>`

error: aborting due to previous error

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `C:\rust\build\bootstrap/debug/rustc --crate-name core libcore\lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=10ce4b4b7843f587 -C extra-filename=-10ce4b4b7843f587 --out-dir C:\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps --target x86_64-pc-windows-msvc -L dependency=C:\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps -L dependency=C:\rust\build\x86_64-pc-windows-msvc\stage1-std\release\deps` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "C:\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "--target" "x86_64-pc-windows-msvc" "-j" "4" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "C:\\rust\\src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', bootstrap\compile.rs:881:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\rust\build\bootstrap\debug\bootstrap build src/libstd --stage 1 --incremental
Build completed unsuccessfully in 0:05:00
```
</details>

**Comment by estebank** [comment]
Thinking about this a bit more, it makes sense that this was introduced by your change. I have to dig a bit deeper to check where, but I'm guessing there's some equality check or similar code somewhere in `librustc/traits/specialize` that fails (or incorrectly succeeds) due to the span field.

**Comment by kennytm** [comment]
Review ping for you @estebank! Have you checked why the Span field caused the conflicting impl error?

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -3195,8 +3195,9 @@ impl<'a> Resolver<'a> {
                             // This was an attempt to use a type parameter outside
                             // its scope.
                             if record_used {
+                                debug!("rib: {:?}", rib);
                                 resolve_error(self, span,
-                                              ResolutionError::TypeParametersFromOuterFunction);
+                                              ResolutionError::TypeParametersFromOuterFunction(&span));
```
Comment (kennytm) [inline src/librustc_resolve/lib.rs]: BTW, this line is >100 chars, failing the CI.

```
[00:06:14] tidy error: /checkout/src/librustc_resolve/lib.rs:3200: line longer than 100 chars
[00:06:16] some tidy checks failed
```

Comment (zilbuz) [reply src/librustc_resolve/lib.rs]: Thanks! I'll update that before finalizing the PR :) (and run tidy again to check for other errors)

File: src/librustc/ty/sty.rs [hunk 2]
```diff
@@ -862,23 +863,24 @@ impl<'tcx> PolyFnSig<'tcx> {
 pub struct ParamTy {
     pub idx: u32,
     pub name: Name,
+    pub span: Span,
 }
```
Comment (estebank) [inline src/librustc/ty/sty.rs]: Try modifying the `derive` to not include `PartialEq` and implement it yourself as such:

```rust
impl PartialEq for ParamTy {
    fn eq(&self, other: &Self) -> bool {
        (self.idx, self.name) == (other.idx, other.name)
    }
}
```

The compilation went past `compiler_builtins` with that change.

**Comment by estebank** [comment]
I'm stumped, I haven't figured out why this is happening, although the only working theory I have at the moment is around `derive(Hash)` and the query system, but it's just a guess.

@rust-lang/compiler, apologies for the wide shout out but can someone help @zilbuz with this issue? This is also blocking @gaurikholkar on a PR that also requires adding spans to `TyParam`s.

**Comment by nikomatsakis** [comment]
r? @nikomatsakis

I'll try to take a look. Assigning review to myself so I remember. Does seem likely to be an unrelated bug, but I've not reviewed the diffs yet.

**Comment by nikomatsakis** [comment]
Hmm, I wonder if it has to do w/ incremental compilation somehow.

File: src/librustc/ty/sty.rs [hunk 3]
```diff
@@ -862,23 +863,24 @@ impl<'tcx> PolyFnSig<'tcx> {
 pub struct ParamTy {
     pub idx: u32,
     pub name: Name,
+    pub span: Span,
```
[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc/ty/sty.rs]: We should just add a `DefId` if we want to get back the definition, `Span` is a *very* bad idea within anything reachable from `Ty`.

[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/librustc/ty/sty.rs]: Yes, definitely not a span. I have been resisting the idea of going back to `DefId`, because I'd *rather* we move towards just an index, but that would require having more context about the currently "in scope" parameters somewhere to give good error messages. Maybe a `DefId` is the right step for now.

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc/ty/sty.rs]: I think we use `DefId` in `Region`, don't we?

**Comment by zilbuz** [comment]
For information @nikomatsakis, I tried to compile without incremental compilation, but I have the same compilation error.

I'll try to make a summary of the situation.

# Objective

The goal of this PR is to clarify the error message for E0401. I have two examples that trigger this error.

## First example
```rust
pub trait Bar { fn m(&self); }

pub fn foo<T>() {
    struct S<T>;
    impl Bar for S<T> {
        fn m(&self) { println!("Hello World"); }
    }
    let s = S::<T>;
    s.m();
}

pub fn main() {
}
```

Current error message:
```
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:5:20
  |
5 |     impl Bar for S<T> {
  |                    ^ use of type variable from outer function
```

Ideal error message:
```
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:5:20
3 | pub fn foo<T>() {
  |            - type variable from outer function
...
5 |     impl Bar for S<T> {
  |                    ^ use of type variable from outer function
note: try using a local type parameter instead
  |
5 |     impl<T> Bar for S<T> {
  |         ^^^
```

## Second example
```rust
struct A<T> {
    inner: T,
}

impl<T> Iterator for A<T> {
    type Item = u8;
    fn next(&mut self) -> Option<u8> {
        fn helper(sel: &Self) -> u8 {
            unimplemented!();
        }
        Some(helper(self))
    }
}

fn main() {
}
```

Current error message:
```
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:8:25
  |
8 |         fn helper(sel: &Self) -> u8 {
  |                         ^^^^ use of type variable from outer function
```

I don't really know what the ideal error message is here. The `Self` type parameter doesn't appear explicitly so we can't show its span. I suppose the note can be added, but we need to either use `T` arbitrarily every time or choose an unused letter as type parameter when generating the error message. I don't know if that's possible.

# Implementation

## Step one: adjust `enum ResolutionError` to add the necessary spans

The function [`resolve_error()`](https://github.com/rust-lang/rust/blob/679f30e1aac510082b0fd3a2b5465321753aa7d1/src/librustc_resolve/lib.rs#L164-L166) is used to print the error message. The function takes the main span and a `ResolutionError` value as parameters. For "E0401", the enum has the value `TypeParametersFromOuterFunction`. This value needs to carry two more spans to be able to generate the ideal error message.

Open questions:
 * Are the spans OK for this use case or should we have `DefId` or indexes? 
   Other enum values seems to use spans for this purpose;
 * Should we copy the spans inside the enum value or use a reference? The other 
   enum values seem to use one or the other indiscriminately;
 * Should we use a fixed type name in the suggestion of the error message or 
   generate one when constructing the error? If we generate one, should we do it 
   before calling `resolve_error()` and pass it to the enum value or should we 
   generate it inside `resolve_error()`?

## Step two: retrieve the extra spans when triggering the error

The E0401 error is triggered in [`adjust_local_ref()`](https://github.com/rust-lang/rust/blob/679f30e1aac510082b0fd3a2b5465321753aa7d1/src/librustc_resolve/lib.rs#L3266-L3285). Here we have access to:
 * A span given to the function that corresponds to the type 
   parameter incorrectly used. This span is currently used for the error message;
 * The `DefId`s of the `Def::TyParam(..)` and `Def::SelfTy(..)` that triggered 
   the error. I think that these ids correspond to the same span as above, but I 
   may be a bit confused about that;
 * A `Rib` of kind `ItemRibKind`. Unfortunately in both examples above, the 
   `bindings` struct member was empty so I don't know what informations are 
   available in this struct.
   
I feel that I'm missing something here, because I don't see how I can retrieve the necessary spans here, and I don't really know why I was trying to add a span to `ParamTy` since I don't see a value of this type here :/

Open questions:
 * How should we retrieve the necessary spans here?
 * Do we really need new informations on `struct ParamTy` here? And if so, should we add a `DefId` or an index?
 * I also wanted to ask how to retrieve the span of a `DefId`?

Sorry to be a bother, I feel like I'm asking a lot but I'm a bit lost :/. Feel free to contact me on Gitter if some of you want to discuss this more directly.

**Comment by pietroalbini** [comment]
@nikomatsakis, ping from triage (also pinged on IRC)!

**Comment by nikomatsakis** [comment]
@zilbuz sorry for not responding earlier. I keep diving into your list and then getting a bit lost myself. =)

**Comment by nikomatsakis** [comment]
The last time, I got into a discussion with @eddyb about how we really want to be handling the `Param` type. My preference ultimately woudl be to just have an index, and to get the contextual information (e.g., its name, spans, etc) out of the TLS somehow (basically, when doing display, we'd set up the "environment that we are in")

**Comment by pietroalbini** [comment]
@nikomatsakis what's the status on this?

**Comment by nikomatsakis** [comment]
@zilbuz 

Sorry for the delay. So, I've finally taken some time to catch up on what the original goal was here. The good news is that I think there is really no *need* to be changing the `Ty<'tcx>` and doing the other controversial things. The error that we are trying to fix is limited to the `librustc_resolve` section of the code, and the types in question don't even exist yet!

I'll try to leave some comments in the code itself, but also, a quick note on your second example:

```
struct A<T> {
    inner: T,
}

impl<T> Iterator for A<T> {
    type Item = u8;
    fn next(&mut self) -> Option<u8> {
        fn helper(sel: &Self) -> u8 {
            unimplemented!();
        }
        Some(helper(self))
    }
}

fn main() {
}
```

for this, may I suggest the following error?

```
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:8:25
5 | impl<T> Iterator for A<T> {
  | ^^^^ `Self` type implicitly declared here, on the `impl`
...
  |
8 |         fn helper(sel: &Self) -> u8 {
  |                         ^^^^ use of type variable from outer function
```

The truth is that it is not a type *parameter* in this context, not really, more like a type *alias*, but that may not be worth clarifying.

File: src/librustc_resolve/lib.rs [hunk 4]
```diff
@@ -3275,8 +3278,10 @@ impl<'a> Resolver<'a> {
                             // This was an attempt to use a type parameter outside
                             // its scope.
                             if record_used {
+                                debug!("rib: {:?}", rib);
                                 resolve_error(self, span,
-                                              ResolutionError::TypeParametersFromOuterFunction);
+                                    ResolutionError::TypeParametersFromOuterFunction(None));
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: OK, so, here `def.def_id()` gives you the `DefId` of the thing we want -- annoyingly, I'm not sure how to get the span from that. Normally I'd say to use the hir-map, but it's not available in resolve. Perhaps @eddyb or @petrochenkov can answer that -- what is the best way to get the span where `def` was declared here?

File: src/librustc_resolve/lib.rs [hunk 5]
```diff
@@ -3275,8 +3278,10 @@ impl<'a> Resolver<'a> {
                             // This was an attempt to use a type parameter outside
                             // its scope.
                             if record_used {
+                                debug!("rib: {:?}", rib);
                                 resolve_error(self, span,
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: I think we can kill all the diffs that are not part of this file.

File: src/librustc_resolve/lib.rs [hunk 6]
```diff
@@ -122,7 +122,7 @@ impl Ord for BindingError {
 
 enum ResolutionError<'a> {
     /// error E0401: can't use type parameters from outer function
-    TypeParametersFromOuterFunction,
+    TypeParametersFromOuterFunction(Option<&'a Span>),
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: May I suggest, instead of passing the span, that you pass the `Def`? (See other comments)

File: src/librustc_resolve/lib.rs [hunk 7]
```diff
@@ -172,13 +172,16 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver,
                                    resolution_error: ResolutionError<'a>)
                                    -> DiagnosticBuilder<'sess> {
     match resolution_error {
-        ResolutionError::TypeParametersFromOuterFunction => {
+        ResolutionError::TypeParametersFromOuterFunction(outer_span) => {
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: if we have the full `Def` here, we can match on it and see whether it is `Def::SelfType` or some other kind of def. If it is a self-type, we can customize the error message to highlight the trait/impl. The tricky bit is still getting the *span* from a `Def`.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
OK, I left some comments, hopefully that helps!

**Comment by estebank** [comment]
> The truth is that it is not a type parameter in the context of an impl, not really, more like a type alias, but that may not be worth clarifying.

@nikomatsakis although I somewhat agree in this case, there are other error messages that would benefit from pointing at the type argument directly.

**Comment by nikomatsakis** [comment]
@estebank 

> although I somewhat agree in this case, there are other error messages that would benefit from pointing at the type argument directly.

Seems reasonable. I don't think however that adding spans to the type argument is the way to go. Rather, I think that -- as @eddyb and I [were saying earlier](https://github.com/rust-lang/rust/pull/47574#issuecomment-364218602) -- the way to do this is to give more information about the current scope when formatting errors.

This is probably best done as part of a larger refactoring to the `ppaux` code, which is kind of a mess, despite the heroic efforts of a recent refactoring (which made it much, much nicer than it was). 

Basically the idea would be that -- when you format a type for display -- you should always know some information about the 'scope' in which that type appears. This should readily give access to e.g. the `Generics` from the HIR and so forth, which could be used to get the spans of the type parameters. 

I'm trying to remember what @eddyb and I were saying now. I *think* that the hope was that we could modify the `struct_span_err!` macros to perhaps figure out this information based on the *span* of the error -- @eddyb, was that right?

In any case, I think it's better to figure out that design outside of the context of this PR, probably?

**Comment by zilbuz** [comment]
@nikomatsakis @estebank Thanks for the feedback!

I changed `ResolutionError::TypeParametersFromOuterFunction` to take a `Def` and adapted the error message according to its value (`TyParam` or `SelfTy`). The new messages are commented out because I still need to retrieve the span from a `DefId`, but once we have that it should be straightforward to finish them.

I saw that the `Resolver` struct has a `session` member, would it be a correct place to track the spans of `DefId`?

**Comment by nikomatsakis** [comment]
@zilbuz so I was chatting with @eddyb on IRC. It seems like -- at the time that name resolution runs -- there is no existing map that goes from a DefId to a span. Annoying.

One easy option would be for the resolver to build up such a map as it brings things into scope. Another option, which @eddyb suggested, is to extend the [definitions struct](https://github.com/rust-lang/rust/blob/master/src/librustc/hir/map/definitions.rs#L147-L158) so that it tracks the span of each def-id that is added to it. That would probably involve adding a new map into the struct, and then extending this function to take a Span parameter, so we can update the table:

https://github.com/rust-lang/rust/blob/1670a532dd769763f1d6ad9e5d624ec31361a098/src/librustc/hir/map/definitions.rs#L523-L530

We'd obviously have to visit the callers, as well.

I'm of two minds on this point. On the one hand, it feels better to provide these spans more universally. On the other, that sort of duplicates the existing HIR map. But then again the HIR map isn't always available (e.g., in this case).

@eddyb -- is this indeed what you had in mind?

**Comment by zilbuz** [comment]
@nikomatsakis I added a map to track the `Span`s of `DefId`s in the definitions struct. However I have some problems:

* I don't know which span to use [here](https://github.com/rust-lang/rust/pull/47574/files#diff-045bbea69ac58b5b2007d081eff9026fR160). `struct_def` doesn't have one available, and I don't know if the one in `i.span` is specific enough for this case?
* [When the `def` is `SelfTy`](https://github.com/rust-lang/rust/pull/47574/files#diff-aeb0880081a991f34aef2ab889e1fb7aR185), the span linked to impl `DefId` enclosed all the impl and not just the keyword. I tried iterating over the tracked `DefId` with the impl as parent to try to find the `impl` keyword, but all the children's span were also on the entire impl block. Is [the message as-is](https://github.com/rust-lang/rust/pull/47574/files#diff-b67dcd2a6867a856176b7fcda257d123R14) sufficient? And if not how should I retrieve the span of just the impl keyword?
* [For the suggestion](https://github.com/rust-lang/rust/pull/47574/files#diff-aeb0880081a991f34aef2ab889e1fb7aR204), I need to retrieve the span of the enclosing item (impl or fn depending on the example) and modify the printed source to add the suggestion. How should I do this? Is there an error code that already do this so that I could check how this is done?

**Comment by estebank** [comment]
> I don't know which span to use here.

I _think_ that `i.span` is correct there.

> When the def is SelfTy, the span linked to impl DefId enclosed all the impl and not just the keyword.

```
// impl_span: `impl<T> Iterator for A<T> { ... }`
// impl_span: `impl Iterator for A { ... }`
// impl_span: `impl      Iterator for A { ... }`
let cm = self.session.codemap();
let sp = cm.span_until_char(impl_span, '<'); // `impl`, `impl Iterator for A { ... }`, `impl    Iterator for A { ... }`
let sp = cm.span_until_char(sp, ' '); // `impl`, `impl`, `impl    Iterator for A { ... }`
let sp = cm.span_until_char(sp, '\t'); // `impl`, `impl`,`impl`
```

You could add a method `span_until_whitespace` to complement the existing `span_until_non_whitespace` that already exists in `libsyntax/codemap.rs`.

> How should I do this? Is there an error code that already do this so that I could check how this is done?

For the suggestion: you use `err.span_suggestion(span_to_be_replaced, "text message or label", "new code".to_string());`. In this case, you'll have to get a span for the method's type arguments (if there are any already), or the method's name. We don't keep that span around anywhere, but you could synthesize one getting the span for the method and skipping the keywords (`fn`, `unsafe`, `pub`, etc.). This is frowned upon, as we're duplicating logic from the parser, but adding the span for the method name would be a bit more involved than necessary for this feature and I feel the tradeoff here it's reasonable (you can look at `tcx.sess.codemap.def_span(span)` for a method doing something similar to this).

**Comment by zilbuz** [comment]
@estebank I've done the requested modifications.

To retrieve the span and source of the function, I added two functions to `codemap.rs`: `span_extend_to_prev_char()` and `span_extend_to_prev_str()`. I feel like these functions could be one instead since the code inside them is identical, but I wasn't able to use a type parameter here. If you think that I should indeed have a single function, I could copy-paste the code that I tried.

Otherwise I think it's good to go, I'll remove the WIP status on the PR :)

**Comment by nikomatsakis** [comment]
@zilbuz great!

File: src/libsyntax/codemap.rs [hunk 8]
```diff
@@ -593,6 +609,32 @@ impl CodeMap {
...
+                return sp.with_lo(BytePos(sp.lo().0 - prev_source.len() as u32));
+            }
+        }
+
+        sp
+    }
+
+    /// Extend the given `Span` to just after the previous occurrence of `pat`. Return the same span
+    /// if no character could be found or if an error occurred while retrieving the code snippet.
+    pub fn span_extend_to_prev_str(&self, sp: Span, pat: &str) -> Span {
```
Comment (estebank) [inline src/libsyntax/codemap.rs]: I think you could unify both of these methods writing it like this:

```rust
 pub fn span_extend_to_prev<P>(&self, sp: Span, pat: P) -> Span {
```

**Review by estebank — APPROVED** [review]
LOVE IT!

Left one nitpick about unifying methods that you already mentioned, but after cleaning that up, enthusiastically r=me.

File: src/libsyntax/codemap.rs (hunk 8 above)
Comment (zilbuz) [reply src/libsyntax/codemap.rs]: I actually tried this version because I also thought that it would be sufficient to unify those methods, but I've got a compile error:
```rust
// Code
    pub fn span_extend_to_prev<P>(&self, sp: Span, pat: P) -> Span {
        if let Ok(prev_source) = self.span_to_prev_source(sp) {
            let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
            if !prev_source.is_empty() {
                return sp.with_lo(BytePos(sp.lo().0 - prev_source.len() as u32));
            }
        }

        sp
    }

// Error
error[E0277]: the trait bound `P: std::ops::FnMut<(char,)>` is not satisfied
   --> libsyntax\codemap.rs:615:43
    |
615 |             let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
    |                                           ^^^^^^ the trait `std::ops::FnMut<(char,)>` is not implemented for `P`
    |
    = help: consider adding a `where P: std::ops::FnMut<(char,)>` bound
    = note: required because of the requirements on the impl of `std::str::pattern::Pattern<'_>` for `P`

error[E0599]: no method named `nth` found for type `std::str::RSplit<'_, P>` in the current scope
   --> libsyntax\codemap.rs:615:55
    |
615 |             let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
    |                                                       ^^^
    |
    = note: the method `nth` exists but the following trait bounds were not satisfied:
            `std::str::RSplit<'_, P> : std::iter::Iterator`

error: aborting due to 2 previous errors
```

I also tried being explicit on the type parameter by copying the bounds of `rsplit()`, but then I've got a lifetime error:
```rust
// Code
    pub fn span_extend_to_prev2<'a, P: Pattern<'a>>(&self, sp: Span, pat: P) -> Span 
        where <P as Pattern<'a>>::Searcher: ReverseSearcher<'a>
    {
        if let Ok(prev_source) = self.span_to_prev_source(sp) {
            let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
            if !prev_source.is_empty() {
                return sp.with_lo(BytePos(sp.lo().0 - prev_source.len() as u32));
            }
        }

        sp
    }

// Error
error[E0597]: `prev_source` does not live long enough
   --> libsyntax\codemap.rs:628:31
    |
628 |             let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
    |                               ^^^^^^^^^^^ borrowed value does not live long enough
...
632 |         }
    |         - borrowed value only lives until here
    |
note: borrowed value must be valid for the lifetime 'a as defined on the method body at 624:5...
   --> libsyntax\codemap.rs:624:5
    |
624 | /     pub fn span_extend_to_prev2<'a, P: Pattern<'a>>(&self, sp: Span, pat: P) -> Span
625 | |         where <P as Pattern<'a>>::Searcher: ReverseSearcher<'a>
626 | |     {
627 | |         if let Ok(prev_source) = self.span_to_prev_source(sp) {
...   |
634 | |         sp
635 | |     }
    | |_____^
```

Here are some links to the playground illustrating the errors: [first try][1], [second try][2].

Do you have an idea of how I could fix this?

[1]: https://play.rust-lang.org/?gist=f6797f5271da80c33d9498492f3c5c30&version=nightly
[2]: https://play.rust-lang.org/?gist=829569512050301a0df4057e10831039&version=nightly

Comment (estebank) [reply src/libsyntax/codemap.rs]: The first one is missing a trait bound, as written it would allow _any_ type to be passed as a pattern.

For the second, the string needs to outlive the method, which you can assure by [borrowing it instead](https://play.rust-lang.org/?gist=eb61a70a48ce013d254e24ce11aae74c&version=nightly).

File: src/librustc_resolve/lib.rs [hunk 9]
```diff
@@ -172,13 +172,90 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver,
...
+            match outer_def {
+                Def::SelfTy(_, maybe_impl_defid) => {
+                    if let Some(impl_span) = maybe_impl_defid.map_or(None,
+                            |def_id| resolver.definitions.opt_span(def_id)) {
+                        // Adjust the span so that just the `impl` keyword is taken by removing
+                        // everything after `<` (`"impl<T> Iterator for A<T> {}" -> "impl"`) and
+                        // everything after the first whitespace (`"impl Iterator for A" -> "impl"`)
+                        let cm = resolver.session.codemap();
+                        let impl_span = cm.span_until_char(impl_span, '<');
+                        let impl_span = cm.span_until_whitespace(impl_span);
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: whoosh, this kind of manipulation feels very fragile (I strongly suspect we are overlooking cases here). Probably ok for this PR, but we should think about saving these spans during the parsing stage or something.

File: src/librustc_resolve/lib.rs [hunk 10]
```diff
@@ -172,13 +172,90 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver,
...
+                Def::AssociatedConst(..) | Def::Local(..) | Def::Upvar(..) | Def::Label(..) |
+                Def::Macro(..) | Def::GlobalAsm(..) | Def::Err =>
+                    bug!("TypeParametersFromOuterFunction should only be used with Def::SelfTy or \
+                         Def::TyParam")
+            }
+
+            // Try to extend the span to the previous "fn" keyword to retrieve the function
+            // signature
+            let cm = resolver.session.codemap();
+            let sugg_span = cm.span_extend_to_prev_str(span, "fn");
```
Comment (nikomatsakis) [inline src/librustc_resolve/lib.rs]: Same here.

File: src/librustc_resolve/lib.rs (hunk 9 above)
Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: At minimum, can we move these adjustments into some sort of helpers, so that we can tweak them over time and share them between error reporting code?

File: src/test/ui/error-codes/E0401.stderr [hunk 11]
```diff
@@ -1,8 +1,23 @@
...
+  --> $DIR/E0401.rs:14:38
    |
-12 |     fn bar(y: T) { //~ ERROR E0401
-   |               ^ use of type variable from outer function
+13 | fn foo<T>(x: T) {
+   |        - type variable from outer function
+14 |     fn bar<U, V: Baz<U>, W: Fn()>(y: T) { //~ ERROR E0401
+   |        --------------------------    ^ use of type variable from outer function
+   |        |
+   |        help: try using a local type parameter instead: `bar<U, V: Baz<U>, W: Fn(), T>`
```
Comment (nikomatsakis) [inline src/test/ui/error-codes/E0401.stderr]: still, the end result is slick

File: src/libsyntax/codemap.rs [hunk 12]
```diff
@@ -578,6 +583,17 @@ impl CodeMap {
         }
     }
 
+    /// Return the source snippet as `String` corresponding to the given `Span`
+    pub fn span_to_snippet(&self, sp: Span) -> Result<String, SpanSnippetError> {
+        self.span_to_source(sp, |src, start_index, end_index| src[start_index..end_index]
+                                                                .to_string())
+    }
+
+    /// Return the source snippet as `String` before the given `Span`
```
Comment (nikomatsakis) [inline src/libsyntax/codemap.rs]: Can you expand this comment a bit -- where does the resulting string start? From the beginning of the containing file?

**Review by nikomatsakis — COMMENTED** [review]
This looks great! I'll leave it to you + estebank to decide how much to refactor the "suggestion creation" code, but r=me on the overall approach. Nice job.

File: src/libsyntax/codemap.rs (hunk 8 above)
Comment (zilbuz) [reply src/libsyntax/codemap.rs]: For the first one, I think I still have a C++ mental model where the template parameter is automatically bound by its use inside the function, so I thought this should work :).

Anyway for the second one, when I use the `Pattern<'a>` bound I'm not sure how to use a borrowed string instead of a `String` since I use the result of `span_to_prev_source()` which return `Result<String, SpanSnippetError>` (That's why I used `Option<String>` in the playground, to try to mirror this case). 

I could create a function like this:
```rust
fn span_and_source_extend_to_prev<'a, P: Pattern<'a>>(&self, sp: Span, prev_source: &'a str, pat: P) -> Span
    where <P as Pattern<'a>>::Searcher: ReverseSearcher<'a>
{
    let prev_source = prev_source.rsplit(pat).nth(0).unwrap_or("").trim_left();
    if !prev_source.is_empty() {
        sp.with_lo(BytePos(sp.lo().0 - prev_source.len() as u32))
    } else {
        sp
    }
}
```

But then I still need two more functions for `char` and `&str`, otherwise I run into the same problem: 
```rust
pub fn span_extend_to_prev_char(&self, sp: Span, c: char) -> Span {
    if let Ok(prev_source) = self.span_to_prev_source(sp) {
        self.span_and_source_extend_to_prev(sp, &prev_source, c)
    } else {
        sp
    }
}

pub fn span_extend_to_prev_str(&self, sp: Span, pat: &str) -> Span {
    if let Ok(prev_source) = self.span_to_prev_source(sp) {
        self.span_and_source_extend_to_prev(sp, &prev_source, pat)
    } else {
        sp
    }
}
```
So it seems to defeat the point.

What do you think?

File: src/librustc_resolve/lib.rs (hunk 9 above)
Comment (zilbuz) [reply src/librustc_resolve/lib.rs]: I can put some helper functions in `codemap.rs` for these manipulations, but as you say they are fragile and putting them here may encourage to use them. I think that if we make them easily acccessible, then we should transition them to more robust versions as soon as possible. I don't know how to save the spans that we want, but maybe the functions in codemap could work on parsed tokens instead of string? (I'm thinking of the `quote` crate used for the procedural macros, but maybe there's another way of doing that since we're inside the `syntax` crate)

File: src/libsyntax/codemap.rs (hunk 12 above)
Comment (zilbuz) [reply src/libsyntax/codemap.rs]: I'm not actually sure. It comes from either the `src` or the `external_src` field of the `FileMap` associated with the span. I think that this is the containing file, but comments like "[...] source that doesn't originate from files [...]" in the `FileMap` struct make me doubt myself.

Should I stay vague and put something like: "The snippet will begin at the start of the codemap's source associated with the span.", or should I specifically say "The snippet will begin at the start of the file associated with the span."?

Comment (nikomatsakis) [reply src/libsyntax/codemap.rs]: maybe just leave a comment saying you are not sure :)

File: src/librustc_resolve/lib.rs (hunk 9 above)
Comment (nikomatsakis) [reply src/librustc_resolve/lib.rs]: I'm not sure ... let's land it like this for now I guess ...

**Comment by pietroalbini** [comment]
Ping from the release team @zilbuz!

We haven't heard from you on this in a while, and both @estebank and @nikomatsakis left a few comments you should address so we can finally merge this PR!

Also, https://github.com/rust-lang/rust/pull/48449 was recently merged, changing the way UI tests are run. You should rebase on the latest master branch and re-generate the stderr of `error-codes/E0401`.

**Comment by nikomatsakis** [comment]
It seems like none of my suggestions were that imp't. @zilbuz please do rebase though!

**Comment by zilbuz** [comment]
Sorry! I was away and my laptop wasn't powerful enough to compile rustc so I wasn't able to rebase. I'll finish this up today. @nikomatsakis After thinking a bit more about it, I think I'll extract the code to expand the spans in `resolve_error()` in private functions in the same file, then I will be able to add some comments to explain that this is not the best way and should anyone need to use this, they should see if some more robust way can be found. What do you think?

**Comment by nikomatsakis** [comment]
@zilbuz sounds great!

File: src/test/ui/error-codes/E0401.rs [hunk 13]
```diff
@@ -8,11 +8,28 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+trait Baz<T> {}
+
 fn foo<T>(x: T) {
-    fn bar(y: T) { //~ ERROR E0401
+    fn bar<U, V: Baz<U>, W: Fn()>(y: T) { //~ ERROR E0401
```
Comment (estebank) [inline src/test/ui/error-codes/E0401.rs]: When you get back to this, add another test case like this one where the type arguments are all on their own line. I wan't to make sure the suggestion presentation will work will in the case or multiline spans. If the output looks wonky through no fault of your code, let's just file a ticket for it, as it would very likely already affect other diagnostics, and I don't want to block this PR.

Comment (zilbuz) [reply src/test/ui/error-codes/E0401.rs]: It doesn't work really well:
```rust
// Source
    fn baz<U,
           V: Baz<U>,
           W: Fn()>
           (y: T) {
    }

// Message
error[E0401]: can't use type parameters from outer function
  --> main.rs:19:16
   |
13 | fn foo<T>(x: T) {
   |        - type variable from outer function
...
19 |            (y: T) {
   |                ^ use of type variable from outer function
help: try using a local type parameter instead
   |
16 |     fn baz<U,
17 |            V: Baz<U>,
18 |            W: Fn()>
19 |            <T>(y: T) {
   |
```

When I implemented `span_extend_to_prev_char()` from `span_until_char()`, I removed the condition `!prev_source.contains('\n')`. I suspected that it could pose some problems but I didn't test it (I forgot I think...). Anyway if I update `span_extend_to_prev_char()` to not extend the span if a newline is present in the extension, I can have a message without the suggested snippet and just the text:
```
error[E0401]: can't use type parameters from outer function
  --> main.rs:19:16
   |
13 | fn foo<T>(x: T) {
   |        - type variable from outer function
...
19 |            (y: T) { //~ ERROR E0401
   |                ^ use of type variable from outer function
   |
   = help: try using a local type parameter instead
```

I think this is better since it doesn't change the message for the other cases and makes this one clearer. What do you think, should I push this patch?

Comment (estebank) [reply src/test/ui/error-codes/E0401.rs]: Push the latter change to avoid giving an incorrect suggestion, but could you also file ticket once the PR is merged to account for this? As rare as the case might be, it'd be nice to eventually support it too. Add the change to the test so that we can verify that the suggestion is not being displayed for this case.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

@estebank -- I think you were ready to r+, but feel free to r- if not

**Comment by Mark-Simulacrum** [comment]
@bors retry 

cc @alexcrichton 

```
[01:16:18] Cannot create directory /Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/openssl/install: File exists
```

**Comment by kennytm** [comment]
`check x86_64-apple-darwin` failed, but looks spurious.

@bors retry 

```
[02:10:35] test net::tcp::tests::multiple_connect_interleaved_greedy_schedule ... FAILED

[02:10:35] 

[02:10:35] failures:

[02:10:35] 

[02:10:35] ---- net::tcp::tests::multiple_connect_interleaved_greedy_schedule stdout ----

[02:10:35] 	thread 'net::tcp::tests::multiple_connect_interleaved_greedy_schedule' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21

[02:10:35] 

[02:10:35] 

[02:10:35] failures:

[02:10:35]     net::tcp::tests::multiple_connect_interleaved_greedy_schedule
```
