### PR TITLE
Make sure casts from other types to fat pointers are illegal

### LINKED ISSUE #21397: impossible case reached: bad combination of types for cast
Running Arch Linux: 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux

rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000)
binary: rustc
commit-hash: f4f10dba2975b51c2d2c92157018db3ac13d4d4a
commit-date: 2015-01-17 20:31:08 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

Here's the line that caused the error:
`pub static mut SOCKS_HOST: *const str = 0 as *const str;`

backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:126

stack backtrace:
   1:     0x7f81445c3c90 - sys::backtrace::write::hda88ebe91818f572tXt
   2:     0x7f81445e5b90 - failure::on_fail::h9fbfe25f5b38e775qeA
   3:     0x7f8144554300 - rt::unwind::begin_unwind_inner::h1bd92865247a942cjTz
   4:     0x7f813efd7770 - rt::unwind::begin_unwind::h15336451338054780329
   5:     0x7f813efd7700 - diagnostic::SpanHandler::span_bug::h110bf60630d186b1VoF
   6:     0x7f814293e690 - session::Session::impossible_case::h7839f1024fe36b1etFp
   7:     0x7f8143d5eb50 - trans::consts::const_expr_unadjusted::he1dcbfb2818dd7e8Gfo
   8:     0x7f8143d5cdb0 - trans::consts::const_expr::h734b9de8ebda8b92N4n
   9:     0x7f8143c977b0 - trans::base::get_item_val::h8df99413e1d50374a3u
  10:     0x7f8143d64450 - trans::consts::trans_static::hfe38a6a23470d6e4UJo
  11:     0x7f8143c952c0 - trans::base::trans_item::h25a1b35201e5520bCyu
  12:     0x7f8143d7d320 - trans::base::trans_mod::h63dc8a5716cd3e9eeEu
  13:     0x7f8143c952c0 - trans::base::trans_item::h25a1b35201e5520bCyu
  14:     0x7f8143d804d0 - trans::base::trans_crate::hcee70ebbe1e36918juv
  15:     0x7f8144b26a70 - driver::phase_4_translate_to_llvm::h1d3249612b78766ewOa
  16:     0x7f8144b06960 - driver::compile_input::h9092b12341e3a857Cba
  17:     0x7f8144bc8340 - run_compiler::h62323e6edb706ae8nac
  18:     0x7f8144bc6ab0 - thunk::F.Invoke<A, R>::invoke::h12018745279237426453
  19:     0x7f8144bc5a10 - rt::unwind::try::try_fn::h1504517046915204584
  20:     0x7f814464cc00 - rust_try_inner
  21:     0x7f814464cbf0 - rust_try
  22:     0x7f8144bc5cc0 - thunk::F.Invoke<A, R>::invoke::h3360625291245025634
  23:     0x7f81445d37f0 - sys::thread::thread_start::h4faa993964f784ad5Nw
  24:     0x7f813e7f3250 - start_thread
  25:     0x7f8144205219 - clone
  26:                0x0 - <unknown>
```

### LINKED ISSUE #22955: Compiler crash when casting from *mut c_void to *mut [u8]
```
extern crate libc;

fn main() {
    unsafe {
        let data = libc::malloc(100);
        let data_vec = data as *mut [u8];
    }
}
```

```
$ rustc --version
rustc 1.0.0-nightly (890293655 2015-02-28) (built 2015-03-01)
```

```
$ RUST_BACKTRACE=1 rustc 1.rs 
1.rs:1:1: 1:19 warning: use of unstable library feature 'libc'
1.rs:1 extern crate libc;
       ^~~~~~~~~~~~~~~~~~
1.rs:1:1: 1:19 help: add #![feature(libc)] to the crate attributes to silence this warning
1.rs:1 extern crate libc;
       ^~~~~~~~~~~~~~~~~~
1.rs:5:20: 5:32 warning: use of unstable library feature 'libc'
1.rs:5         let data = libc::malloc(100);
                          ^~~~~~~~~~~~
1.rs:5:20: 5:32 help: add #![feature(libc)] to the crate attributes to silence this warning
1.rs:5         let data = libc::malloc(100);
                          ^~~~~~~~~~~~
1.rs:6:13: 6:21 warning: unused variable: `data_vec`, #[warn(unused_variables)] on by default
1.rs:6         let data_vec = data as *mut [u8];
                   ^~~~~~~~
error: internal compiler error: translating unsupported cast: *mut libc::types::common::c95::c_void (cast_pointer) -> *mut [u8] (cast_other)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:189

stack backtrace:
   1:         0x61ef7c4f - sys::backtrace::write::hb08af03691eab78a5kA
   2:         0x61f20782 - panicking::on_panic::h37164609ca1c02afBnJ
   3:         0x61e6063a - rt::unwind::begin_unwind_inner::h24d5e7492198457b43I
   4:         0x5f189a8d - rt::unwind::begin_unwind::h9113908695753286194
   5:         0x5f18a2c5 - diagnostic::Handler::bug::h35ee8d5e5a4a01aeCHD
   6:         0x5fcaa9fb - session::Session::bug::hf545afa75e911993uwp
   7:         0x615e1650 - trans::expr::trans_imm_cast::h267a0afdb72de17aLPj
   8:         0x615cc199 - trans::expr::trans_unadjusted::h195794326d4a3453m4h
   9:         0x615835bf - trans::expr::trans_into::h4bccf2ad56ca2eb8mnh
  10:         0x6168307e - trans::_match::mk_binding_alloca::h11720668362277363266
  11:         0x6158281d - trans::base::init_local::h445e388f28d5f2ddMps
  12:         0x61583fe2 - trans::controlflow::trans_block::hac110643148141f4T4d
  13:         0x615cd7ae - trans::expr::trans_rvalue_dps_unadjusted::h98f8f68155d4ea21Rzi
  14:         0x6158359e - trans::expr::trans_into::h4bccf2ad56ca2eb8mnh
  15:         0x61584307 - trans::controlflow::trans_block::hac110643148141f4T4d
  16:         0x6164f7ef - trans::base::trans_closure::hf74692cb2d4d8ab8wct
  17:         0x61570538 - trans::base::trans_fn::hd3b302f8da4ef8d2pnt
  18:         0x6156c107 - trans::base::trans_item::h43df28c38e89c2c1hLt
  19:         0x616562fc - trans::base::trans_crate::h6e541e412696da41RGu
  20:         0x62581fd2 - driver::phase_4_translate_to_llvm::h39966ab909496f1crNa
  21:         0x6255d5c8 - driver::compile_input::hee81c045ab46c74fIba
  22:         0x62627e6e - run_compiler::h875c1e123fe4ae2cF5b
  23:         0x62625a1c - thunk::F.Invoke<A, R>::invoke::h12424714292252424185
  24:         0x62624770 - rt::unwind::try::try_fn::h4021821266450575721
  25:         0x61f8bfe8 - rust_try_inner
  26:         0x61f8bfd5 - rust_try
  27:         0x62624e5c - thunk::F.Invoke<A, R>::invoke::h8199562432922027576
  28:         0x61f0c2d5 - sys::thread::thread_start::h1b1bb1e7ac08d3a6yRE
  29:         0x5bc420a3 - start_thread
  30:         0x61adfccc - __clone
  31:         0xffffffff - <unknown>
```

### LINKED ISSUE #23237: ICE: translating unsupported cast: *mut [u32] (cast_other) -> *mut c_void (cast_pointer)
```
error: internal compiler error: translating unsupported cast: *mut [u32] (cast_other) -> *mut libc::types::common::c95::c_void (cast_pointer)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:189

stack backtrace:
   1:     0x7f58387ff2f2 - sys::backtrace::write::hd861c9cad5664affQBA
   2:     0x7f5838825342 - panicking::on_panic::h2d36a117ae395cb9jHJ
   3:     0x7f583876ba89 - rt::unwind::begin_unwind_inner::h020c424433824dc2mnJ
   4:     0x7f5835d790ed - rt::unwind::begin_unwind::h10233696008248825440
   5:     0x7f5835d79925 - diagnostic::Handler::bug::h5b4a3d5d737e3662KdE
   6:     0x7f5836782d2b - session::Session::bug::hc4ea5c682d373bb1tYp
   7:     0x7f5837ef9cde - trans::expr::trans_imm_cast::hcd3ecb042c0927e9bTj
   8:     0x7f5837ee637c - trans::expr::trans_unadjusted::h98b3a24d34abc9f436h
   9:     0x7f5837ea80e0 - trans::expr::trans::h66ceb310b9edf1f9bwh
  10:     0x7f5837ed986b - trans::callee::trans_args::hf2cfa069a4970bdbG3g
  11:     0x7f5837edee74 - trans::callee::trans_call_inner::h17056753389190948462
  12:     0x7f5837ee8077 - trans::expr::trans_rvalue_dps_unadjusted::hbd2cd1fd54de27cayCi
  13:     0x7f5837ea6bd6 - trans::expr::trans_into::hf1ef6b0748ac8f9eTph
  14:     0x7f5837ea5f5e - trans::controlflow::trans_stmt_semi::h91aecc9fc3a8807dI6d
  15:     0x7f5837ea762d - trans::controlflow::trans_block::h47e6e8902755cf9cv7d
  16:     0x7f5837ee768a - trans::expr::trans_rvalue_dps_unadjusted::hbd2cd1fd54de27cayCi
  17:     0x7f5837ea6bd6 - trans::expr::trans_into::hf1ef6b0748ac8f9eTph
  18:     0x7f5837ea7987 - trans::controlflow::trans_block::h47e6e8902755cf9cv7d
  19:     0x7f5837f62ed0 - trans::base::trans_closure::h70b835bf44b08f62ent
  20:     0x7f5837e96f4b - trans::base::trans_fn::h88672d255f7695867xt
  21:     0x7f5837e9809d - trans::monomorphize::monomorphic_fn::h5456f629cfa11f62Oud
  22:     0x7f5837eb86e7 - trans::glue::trans_struct_drop::hca0bf2ab407ff704XKe
  23:     0x7f5837eb60c8 - trans::glue::trans_struct_drop_flag::hd2fdfa898dbd0abe5Ie
  24:     0x7f5837eaf229 - trans::glue::get_drop_glue::h995ee19a14e101b31De
  25:     0x7f5837eae72d - trans::glue::drop_ty::h5b7f57924de7b3bdvAe
  26:     0x7f5837fd1819 - trans::cleanup::DropValue<'tcx>.Cleanup<'tcx>::trans::h050e22dd6399d306nXK
  27:     0x7f5837ebfe1e - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_custom_cleanup_scope::h4f8733d43bdc3f3cR0J
  28:     0x7f5837f7daa5 - trans::_match::trans_match_inner::hafede36b631dfe103Kw
  29:     0x7f5837ee7659 - trans::expr::trans_rvalue_dps_unadjusted::hbd2cd1fd54de27cayCi
  30:     0x7f5837ea6bd6 - trans::expr::trans_into::hf1ef6b0748ac8f9eTph
  31:     0x7f5837f92b2e - trans::_match::mk_binding_alloca::h6781106208550372573
  32:     0x7f5837ea60ad - trans::base::init_local::h6b5a17c439dc15bfGBs
  33:     0x7f5837ea7662 - trans::controlflow::trans_block::h47e6e8902755cf9cv7d
  34:     0x7f5837f62ed0 - trans::base::trans_closure::h70b835bf44b08f62ent
  35:     0x7f5837e96f4b - trans::base::trans_fn::h88672d255f7695867xt
  36:     0x7f5837e93819 - trans::base::trans_item::h1cf2dcffa3cf86bfZVt
  37:     0x7f5837f6967c - trans::base::trans_crate::h88960ef764a955bcaSu
  38:     0x7f5838e23f92 - driver::phase_4_translate_to_llvm::h5d3ca9bd44c7f33agOa
  39:     0x7f5838dff8ea - driver::compile_input::h124aae68147ae8b8Nba
  40:     0x7f5838ec415d - run_compiler::hffd5283ae5d6d3abG6b
  41:     0x7f5838ec1ecc - thunk::F.Invoke<A, R>::invoke::h16438916220137010031
  42:     0x7f5838ec0b20 - rt::unwind::try::try_fn::h17325604874211535233
  43:     0x7f5838891118 - rust_try_inner
  44:     0x7f5838891105 - rust_try
  45:     0x7f5838ec12ab - thunk::F.Invoke<A, R>::invoke::h5807416775295653773
  46:     0x7f5838812b45 - sys::thread::thread_start::h2188587ec04914c6t8E
  47:     0x7f583285d181 - start_thread
  48:     0x7f58383e447c - __clone
  49:                0x0 - <unknown>

Could not compile `handmade_libsdl`.

To learn more, run the command again with --verbose.
```

This is done when compiling [this][repo] repository. Use `cargo build` on either the entire handmade_hero crate, or handmade_libsdl. Warning: Ugly, `no_std` code ahead!

Cleaned up repo: [newrepo]

It does need to be across crate lines, and needs to be returned in a result, afaict.

`rustc 1.0.0-nightly (91bdf23f5 2015-03-09) (built 2015-03-09)`

[repo]: https://github.com/GBGamer/handmade_hero_nostd
[newrepo]: https://github.com/GBGamer/compiler_error

### LINKED ISSUE #24100: ICE: translating unsupported cast
Example code:

    let mem: &[u8] = &[48, 49];
    let ptr = mem.as_ptr() as *const str;
    let s = unsafe { &*ptr };

Error message:
```
error: internal compiler error: translating unsupported cast: *const u8 (cast_pointer) -> *const str (cast_other)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/swizard/distr/rust/src/libsyntax/diagnostic.rs:190
stack backtrace:
   1:        0x105f01957 - sys::backtrace::write::h49bc1af3bff4a6e3DJC
   2:        0x105f2f873 - panicking::on_panic::h22918d2e20ddf008PxI
   3:        0x105e53cbe - rt::unwind::begin_unwind_inner::hb0f5c720a6629d10qfI
   4:        0x10563b19e - rt::unwind::begin_unwind::h13792904101880946349
   5:        0x10563b9e9 - diagnostic::Handler::bug::h8d018cb8efa3e647EsB
   6:        0x102f32627 - session::Session::bug::he24b74119a1174bbFPq
   7:        0x1029c1358 - trans::expr::trans_imm_cast::h0dc669e5f6c002d8nKj
   8:        0x1029a82e6 - trans::expr::trans_unadjusted::h86976c6745580e14TXh
   9:        0x10295a53c - trans::expr::trans_into::hefe6c24c6801eb34gfh
  10:        0x102a7ad1a - trans::_match::mk_binding_alloca::h16979327121447448331
  11:        0x10295977f - trans::base::init_local::h45ac8135c05a5146NMs
  12:        0x10295b342 - trans::controlflow::trans_block::h8c650fbe27085d2cH6d
  13:        0x102a3b4f5 - trans::base::trans_closure::h46864fd94aa01bc0Qtt
  14:        0x102942c83 - trans::base::trans_fn::h2ca708b7c163d918zEt
  15:        0x10294463e - trans::monomorphize::monomorphic_fn::h95fbd095b702f0baYtd
  16:        0x102989b81 - trans::callee::trans_fn_ref_with_substs::h1994bdb61afbe636Zbg
  17:        0x102988a2e - trans::meth::trans_static_method_callee::hf8b89488d2117b8dNAy
  18:        0x1029859ca - trans::callee::trans::hbb34a5eec289d1c9jPf
  19:        0x10299c33b - trans::callee::trans_call_inner::h8192340426532286712
  20:        0x1029aa770 - trans::expr::trans_rvalue_dps_unadjusted::h27b9d0cd52a394f1mti
  21:        0x10295a51c - trans::expr::trans_into::hefe6c24c6801eb34gfh
  22:        0x102a7ad1a - trans::_match::mk_binding_alloca::h16979327121447448331
  23:        0x10295977f - trans::base::init_local::h45ac8135c05a5146NMs
  24:        0x10295b342 - trans::controlflow::trans_block::h8c650fbe27085d2cH6d
  25:        0x102a3b4f5 - trans::base::trans_closure::h46864fd94aa01bc0Qtt
  26:        0x102942c83 - trans::base::trans_fn::h2ca708b7c163d918zEt
  27:        0x102944592 - trans::monomorphize::monomorphic_fn::h95fbd095b702f0baYtd
  28:        0x102989b81 - trans::callee::trans_fn_ref_with_substs::h1994bdb61afbe636Zbg
  29:        0x102987f57 - trans::callee::trans_fn_ref::h63f04e40db0908572Zf
  30:        0x102985bd0 - trans::callee::trans::hbb34a5eec289d1c9jPf
  31:        0x10299c33b - trans::callee::trans_call_inner::h8192340426532286712
  32:        0x1029aa770 - trans::expr::trans_rvalue_dps_unadjusted::h27b9d0cd52a394f1mti
  33:        0x10295a51c - trans::expr::trans_into::hefe6c24c6801eb34gfh
  34:        0x102959492 - trans::controlflow::trans_stmt_semi::he0a71a03e8e22f97L5d
  35:        0x10295b317 - trans::controlflow::trans_block::h8c650fbe27085d2cH6d
  36:        0x1029a9bad - trans::expr::trans_rvalue_dps_unadjusted::h27b9d0cd52a394f1mti
  37:        0x10295a51c - trans::expr::trans_into::hefe6c24c6801eb34gfh
  38:        0x10295b6a0 - trans::controlflow::trans_block::h8c650fbe27085d2cH6d
  39:        0x102a3b4f5 - trans::base::trans_closure::h46864fd94aa01bc0Qtt
  40:        0x102942c83 - trans::base::trans_fn::h2ca708b7c163d918zEt
  41:        0x10293d4bd - trans::base::trans_item::h46b9d96ec061ef10P2t
  42:        0x102a43fc7 - trans::base::trans_crate::h2a7f765e28da6987lZu
  43:        0x10236a82c - driver::phase_4_translate_to_llvm::hb12845c52d9d2a39aOa
  44:        0x10234217e - driver::compile_input::hf700a572a1239378Qba
  45:        0x1023ffd35 - run_compiler::h2254195776d5d4d5S4b
  46:        0x1023fd502 - boxed::F.FnBox<A>::call_box::h6405845031818806926
  47:        0x1023fc9f7 - rt::unwind::try::try_fn::h692286709647191617
  48:        0x105fbc4b8 - rust_try_inner
  49:        0x105fbc4a5 - rust_try
  50:        0x1023fccea - boxed::F.FnBox<A>::call_box::h15513867904557068020
  51:        0x105f18d5d - sys::thread::create::thread_start::h320d70da47133ff2weH
  52:     0x7fff8f86f267 - _pthread_body
  53:     0x7fff8f86f1e4 - _pthread_start
```

Rust:

    rustc 1.0.0-dev (b3c5507f3 2015-04-05) (built 2015-04-05)

OS:

    Darwin pair 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by bluss**
typeck: Make sure casts from other types to fat pointers are illegal

Fixes ICEs where non-fat pointers and scalars are cast to fat pointers,

Fixes #21397
Fixes #22955
Fixes #23237
Fixes #24100

### CODE REVIEW

**Comment by bluss** [comment]
I've run the targeted tests, running more tests. This change catches more invalid casts than I intended..

File: src/test/compile-fail/issue-22034.rs [hunk 1]
```diff
@@ -14,6 +14,6 @@ fn main() {
     let foo: *mut libc::c_void;
     let cb: &mut Fn() = unsafe {
         &mut *(foo as *mut Fn())
-        //~^ ERROR use of possibly uninitialized variable: `foo`
+        //~^ ERROR illegal cast
```
Comment (kballard) [inline src/test/compile-fail/issue-22034.rs]: Looks like this test case was actually testing the wrong thing. The associated issue is actually just another instance of casting thin <-> fat pointers, and this test case should not have closed that issue. Note that the error is complaining about something completely unrelated to why the code is actually invalid.

It would be great if you could actually fix up this test case to avoid the other reasons why this case is invalid. A corrected test case looks like

```rust
fn main() {
    let ptr: *mut () = 0 as *mut _;
    let _: &mut Fn() = unsafe {
        &mut *(ptr as *mut Fn())
    };
}
```

Comment (bluss) [inline src/test/compile-fail/issue-22034.rs]: absolutely. Finding this test case was a bit confusing.

**Comment by bluss** [comment]
Updated the list of issues this should fix

File: src/test/compile-fail/issue-22034.rs (hunk 1 above)
Comment (bluss) [inline src/test/compile-fail/issue-22034.rs]: Fixed.

**Comment by bluss** [comment]
Nice. Thank you!

**Comment by luqmana** [comment]
Probably addressed in #24333 or should be if it isn't.
