### PR TITLE
Fix rustdoc

### LINKED ISSUE #43625: rustdoc panic on nul in docstring
In certain circumstances, a nul in a docstring causes rustdoc to panic with a NulError.

I tried this code:
```rust
#[macro_use]
extern crate error_chain;

error_chain! {
    foreign_links {
        StringContainsNul(::std::ffi::NulError)
            #[doc = "Attempted to pass a string containing `\0`"];
    }
}
```
(See https://gist.github.com/kw217/4687d8c42b890f8f7c75533f64cb00c8)

Notice the probably-wrong literal nul char in the docstring - the author intended to use a double-backslash.

When I ran cargo doc, I expected this to either work (emitting HTML output containing the literal nul or somehow eliding it) or give me an appropriate error message (e.g., "Docstring contains NUL at lib.rs:7").

Instead, I got the following panic:
```
$ RUST_BACKTRACE=1 cargo doc
 Documenting repro v0.1.0 (file:///data/ksw/repro)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(6, [60, 99, 111, 100, 101, 62, 0, 60, 47, 99, 111, 100, 101, 62])', /checkout/src/libcore/result.rs:860
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rustdoc::html::markdown::render::codespan
  11: char_codespan
  12: parse_inline
  13: parse_block.part.19
  14: hoedown_document_render
  15: rustdoc::html::markdown::render
  16: core::fmt::write
             at /checkout/src/libcore/fmt/mod.rs:954
  17: core::fmt::Formatter::write_fmt
             at /checkout/src/libcore/fmt/mod.rs:1262
  18: rustdoc::html::render::document_full
  19: <rustdoc::html::render::Item<'a> as core::fmt::Display>::fmt
  20: core::fmt::write
             at /checkout/src/libcore/fmt/mod.rs:994
             at /checkout/src/libcore/fmt/mod.rs:962
  21: std::io::Write::write_fmt
  22: rustdoc::html::render::Context::render_item
  23: rustdoc::html::render::run

error: Could not document `repro`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name repro src/lib.rs -o /data/ksw/repro/target/doc -L dependency=/data/ksw/repro/target/debug/deps --extern error_chain=/data/ksw/repro/target/debug/deps/liberror_chain-4a7bcc9cb68d5e79.rlib` (exit code: 101)
```

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0 (0ade33941 2017-07-17)
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-unknown-linux-gnu
release: 1.19.0
LLVM version: 4.0
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #43625.

r? @rust-lang/dev-tools 

cc @rust-lang/docs

### CODE REVIEW

File: src/librustdoc/html/markdown.rs [hunk 1]
```diff
@@ -695,8 +695,23 @@ pub fn render(w: &mut fmt::Formatter,
...
+                for slice in bytes.split(|&x| x == 0) {
+                    if !full.is_empty() {
+                        full.extend_from_slice(&[b'\\', b'0']);
+                        added = true;
+                    }
+                    full.extend_from_slice(slice);
+                }
+                if !added {
+                    full.extend_from_slice(&[b'\\', b'0']);
+                }
```
Comment (QuietMisdreavus) [inline src/librustdoc/html/markdown.rs]: This loop feels suspect. After a long enough read it *seems* okay, but maybe replacing it with a loop over indices and something like `full.splice(idx..(idx+1), b"\\0".iter().cloned())` would make it easier to read its intent.

**Comment by ollie27** [comment]
This isn't how I would fix this. I don't think there is any need to escape null bytes as they are valid UTF-8. The issue is with the `unwrap` on `CString::new` but we don't need to use `CString`s at all here if we use `hoedown_buffer_put` instead of `hoedown_buffer_puts`.

Specifically replacing all 3 instances of:

```rust
let element = CString::new(content).unwrap();
unsafe { hoedown_buffer_puts(ob, element.as_ptr()); }
```

with:

```rust
unsafe { hoedown_buffer_put(ob, content.as_ptr(), content.len()); }
```

File: src/librustdoc/html/markdown.rs (hunk 1 above)
Comment (ollie27) [inline src/librustdoc/html/markdown.rs]: For what it's worth `s.replace("\0", "\\0")` would be even easier to read.

**Comment by estebank** [comment]
@GuillaumeGomez the only reason I wouldn't fix this issue this way is because there's an unexpected side effect: now writing `\0` and `\\0` will result in the same output, and it's only on this escape sequence that this happens. Although the only conceptual problem I can see this causing is making people think that they can't use escape sequences _at all_, which would be a rather small problem admitedly, and I appreciate the effort to be helpful and do what the user meant instead of what wrote, I feel that a lint pointing at the error would be preferable as it is a _teachable moment_ opportunity to make the user's mental model more accurate. Of course, even with a lint or warning this fix could still apply, if nothing else to allow the compiler to continue.

**Comment by GuillaumeGomez** [comment]
The problem only exists because of `hoedown`. This is just a quick fix until we get rid of `hoedown` definitely (some day...).

**Comment by GuillaumeGomez** [comment]
Updated, and keep in mind that this "fix" only concerns hoedown and won't be an issue with pulldown.

File: src/librustdoc/html/markdown.rs [hunk 2]
```diff
@@ -531,6 +530,7 @@ extern {
     fn hoedown_buffer_new(unit: libc::size_t) -> *mut hoedown_buffer;
     fn hoedown_buffer_puts(b: *mut hoedown_buffer, c: *const libc::c_char);
     fn hoedown_buffer_free(b: *mut hoedown_buffer);
+    fn hoedown_buffer_put(b: *mut hoedown_buffer, c: *const libc::c_char, len: libc::size_t);
```
Comment (ollie27) [inline src/librustdoc/html/markdown.rs]: The second parameter is [`const uint8_t *data`](https://github.com/rust-lang/hoedown/blob/da282f1bb7277b4d30fa1599ee29ad8eb4dd2a92/src/buffer.h#L75) so here it should be `*const u8`. That also means ` as *const libc::c_char` can be removed from below.

File: src/librustdoc/html/markdown.rs [hunk 3]
```diff
@@ -699,9 +697,10 @@ pub fn render(w: &mut fmt::Formatter,
             collapse_whitespace(s)
         };
 
-        let content = format!("<code>{}</code>", Escape(&content));
-        let element = CString::new(content).unwrap();
-        unsafe { hoedown_buffer_puts(ob, element.as_ptr()); }
+        let content = format!("<code>{}</code>", Escape(&content)).replace("\0", "\\0");
```
Comment (ollie27) [inline src/librustdoc/html/markdown.rs]: This change seems unnecessary. As hoedown just passes null bytes through unmodified everywhere else there is no reason to escape it in this one case.

Comment (GuillaumeGomez) [inline src/librustdoc/html/markdown.rs]: If we don't do it, it doesn't appear in the generated HTML.

Comment (ollie27) [inline src/librustdoc/html/markdown.rs]: It will, but browsers may not show anything but that's expected and what already happens if null bytes appear in normal paragraphs.

Comment (GuillaumeGomez) [inline src/librustdoc/html/markdown.rs]: So be it.

**Comment by GuillaumeGomez** [comment]
Updated. No more `\0` displayed.

File: src/librustdoc/html/markdown.rs [hunk 4]
```diff
@@ -531,6 +530,7 @@ extern {
     fn hoedown_buffer_new(unit: libc::size_t) -> *mut hoedown_buffer;
     fn hoedown_buffer_puts(b: *mut hoedown_buffer, c: *const libc::c_char);
     fn hoedown_buffer_free(b: *mut hoedown_buffer);
+    fn hoedown_buffer_put(b: *mut hoedown_buffer, c: *const u8, len: libc::size_t);
```
Comment (steveklabnik) [inline src/librustdoc/html/markdown.rs]: is `hoedown_buffer_puts` used elsewhere? This PR seems mostly to be replacing puts with put. If puts isn't, then we should also remove it

**Review by steveklabnik — COMMENTED** [review]
This PR seems fine, but I'm still not super mega confident with rustdoc's codebase

File: src/librustdoc/html/markdown.rs (hunk 4 above)
Comment (GuillaumeGomez) [inline src/librustdoc/html/markdown.rs]: No, it's still used.

**Comment by steveklabnik** [comment]
r=me if @QuietMisdreavus likes it too

**Comment by QuietMisdreavus** [comment]
r=me pending travis on this last push
