### PR TITLE
Better diagnostic for `use Self::..`

### LINKED ISSUE #111627: Confusing diagnostic when `use Self::Variant` inside an impl
I tried this ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021)):

```rust
pub enum Uwu {
    Hi
}

impl Uwu {
    fn a() -> Uwu {
        use Self::Hi;
        Hi
    }
}
```

Heres the current output:
```
   Compiling playground v0.0.1 (/playground)
error[E0432]: unresolved import `Self`
 --> src/lib.rs:8:13
  |
8 |         use Self::Hi;
  |             ^^^^ `Self` is only available in impls, traits, and type definitions

For more information about this error, try `rustc --explain E0432`.
error: could not compile `playground` due to previous error
```

The label that says "`Self` is only available in impls" is misleading since it is already in an impl.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #111627

cc @petrochenkov, you might have thoughts on a better way to handle this (https://github.com/rust-lang/rust/issues/63720#issuecomment-591597466)

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1832,7 +1832,14 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             }
             (msg, None)
         } else if ident.name == kw::SelfUpper {
-            ("`Self` is only available in impls, traits, and type definitions".to_string(), None)
+            if opt_ns.is_none() {
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/diagnostics.rs:1835]: This is kinda strange on first impression, but it literally says above that "// `None` indicates a module path in import"... so :shrug:

Comment (compiler-errors) [reply compiler/rustc_resolve/src/diagnostics.rs:1835]: couldn't hurt
