### PR TITLE
bootstrap: open `llvm-config` as r+w

### LINKED ISSUE #127849: Bootstrap using `set_times` on a read-only file
@jieyouxu noticed that bootstrap is now failing on a clean Windows build:

```
thread 'main' panicked at src\core\download.rs:711:13:
llvm_config_file.set_times(file_times) failed with Access is denied. (os error 5)
```

This fails due to the file being opened as read-only:

https://github.com/rust-lang/rust/blob/cb12b52f160c633551bd6e5be8d4c6e2e8660950/src/bootstrap/src/core/download.rs#L709-L711

This could be fixed using windows specific permissions but it'd be simpler to just use `OpenOptions` with `write(true)`.

### PR DESCRIPTION
**Pull request by jieyouxu**
This previously failed on Windows and prevented building on Windows for compiler stuff because the `llvm-config` file was open as read-only.

Tested locally on a Windows machine.

Fixes #127849.

### CODE REVIEW

File: src/bootstrap/src/core/download.rs [hunk 1]
```diff
@@ -706,7 +706,7 @@ download-rustc = false
             let file_times = fs::FileTimes::new().set_accessed(now).set_modified(now);
 
             let llvm_config = llvm_root.join("bin").join(exe("llvm-config", self.build));
-            let llvm_config_file = t!(File::open(llvm_config));
+            let llvm_config_file = t!(OpenOptions::new().read(true).write(true).open(llvm_config));
```
Comment (ChrisDenton) [inline src/bootstrap/src/core/download.rs:709]: You could save yourself an import using `File::options()`.

Also I don't think you need `read`?

**Review by onur-ozkan — APPROVED** [review]
LGTM, feel free to r=me

File: src/bootstrap/src/core/download.rs (hunk 1 above)
Comment (jieyouxu) [reply src/bootstrap/src/core/download.rs]: Switched to `File::options` and removed `read()`. Thanks!

**Comment by jieyouxu** [comment]
Made suggested changes, and tested it to make sure it builds past llvm step locally on Windows.
@bors r=@onur-ozkan rollup
