### PR TITLE
Fix spurious trait privacy error

### LINKED ISSUE #18241: Trait re-exports fail due to privacy of containing module
This was working previously before `rustc 0.13.0-nightly (3d2cf6063 2014-10-22 00:22:04 +0000)`.

If this is an intended change, we should probably give the error where the re-export is defined and not on use of the trait.

````
use foo::Bar;

mod foo {
    pub use self::bar::Bar;
    
    mod bar {
        pub trait Bar {
            fn call(&self) -> bool;
        }
    }
}

impl foo::Bar for uint {
    fn call(&self) -> bool {
        true
    }
}

fn main() {
    println!("{}", 0u.call())
    //^~ ERROR source trait is inaccessible
}
````

### PR DESCRIPTION
**Pull request by jseyfried**
This PR allows using methods from traits that are visible but are defined in an inaccessible module (fixes #18241). For example,

``` rust
mod foo {
    pub use foo::bar::Tr;
    mod bar { // This module is inaccessible from `g`
        pub trait Tr { fn f(&self) {} }
    }
}
fn g<T: foo::Tr>(t: T) {
    t.f(); // Currently, this is a privacy error even though `foo::Tr` is visible
}
```

After this PR, it will continue to be a privacy error to use a method from a trait that is not visible. This can happen when a public trait inherits from a private trait (in violation of the `public_in_private` lint) -- see @petrochenkov's example in #28504.
r? @nikomatsakis

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @alexcrichton

File: src/librustc_privacy/lib.rs [hunk 1]
```diff
@@ -609,73 +609,50 @@ impl<'a, 'tcx> PrivacyVisitor<'a, 'tcx> {
...
+            }
+            Some(ast_map::NodeTraitItem(_)) => hir::Public,
 
-                // This is not a method call, extract the visibility as one
-                // would normally look at it
-                Some(ast_map::NodeItem(it)) => it.vis,
-                Some(ast_map::NodeForeignItem(_)) => {
-                    self.tcx.map.get_foreign_vis(closest_private_id)
-                }
-                Some(ast_map::NodeVariant(..)) => {
```
Comment (jseyfried) [inline src/librustc_privacy/lib.rs]: This arm was unreachable

**Comment by petrochenkov** [comment]
LGTM

**Comment by alexcrichton** [comment]
Weird, I thought that loop was at the core of one of the required parts of the privacy check... But hey if the tests pass looks like a great cleanup to me!

**Comment by jseyfried** [comment]
I added another commit that fixes #21670, a separate bug that also happens to cause incorrect `source trait is private` errors.

**Comment by nikomatsakis** [comment]
r=me

**Comment by jseyfried** [comment]
@nikomatsakis According to my measurements, loading the public external modules eagerly slows down the `stage1-cfail` tests by ~14% and slows down a minimal example with crates `rustc`, `syntax`, and `typeck` by ~7%.

I decided to fix #21670 without slowing anything down in another PR.

**Comment by jseyfried** [comment]
Failing because of implicit merge conflicts (unused function)
