### PR TITLE
Give a better diagnostic for missing parens in Fn* bounds

### LINKED ISSUE #108109: Diagnostic when Fn*-family trait bounds is missing parens could be improved
### Code

```Rust
fn handle<F>() where F: FnOnce -> () {}
```

### Current output

```Shell
error: expected one of `(`, `+`, `,`, `::`, `<`, or `{`, found `->`
 --> src/main.rs:1:32
  |
1 | fn handle<F>() where F: FnOnce -> () {}
  |                                ^^ expected one of `(`, `+`, `,`, `::`, `<`, or `{`
```

### Desired output

```Shell
error: expected `(`, found `->`
 --> src/main.rs:1:32
  |
1 | fn handle<F>() where F: FnOnce -> () {}
  |                               ^ `Fn*`-family trait bounds must be followed by parentheses
help: try using parenthesis here:
  |
1 | fn handle<F>() where F: FnOnce() -> () {}
  |                               ^^
```

### Rationale and extra context

It feels like rustc should be able to determine that a trait followed by a `->` is a `Fn*`-family trait bound and be able to suggest this behavior. If that is too general it could just check for `Fn`, `FnOnce`, `FnMut`.

### Other cases

~~Not that i know of...~~

Very similar is if parenthesis are missing from regular `fn` declarations:
```Shell
error: expected one of `(` or `<`, found `->`
 --> src/lib.rs:3:9
  |
3 | fn main -> () {}
  |         ^^ expected one of `(` or `<`
```

### Anything else?

Also happens on nightly according to Rust Playground.

I'd like to try my hand at implementing this diagnostic, but I'll likely need a little bit of locational guidance. A naive code search show that the message is emitted by this code is the parser diagnostics, but I'm not sure if the adjustment would need to be made within that or from where it is invoked in this case.
https://github.com/rust-lang/rust/blob/c5283576ec18937d98889679a54aa8f2dee2b875/compiler/rustc_parse/src/parser/diagnostics.rs#L384-L388

----

_Edit: Updated to use the wording "`Fn*`-family trait bounds" rather than "HRTBs"._

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #108109

It would be nice to try and recover here, but I'm not sure it's worth the effort, especially as the bounds on the recovered function would be incorrect.

### CODE REVIEW

**Comment by clubby789** [comment]
Follow-up PR #117298 to address the other case mentioned in the issue of  `fn main -> () {}`

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -2278,6 +2278,18 @@ impl<'a> Parser<'a> {
                     err.span_label(ident.span, "while parsing this `fn`");
                     err.emit();
                 } else {
+                    // check for typo'd Fn* trait bounds such as
+                    // fn foo<F>() where F: FnOnce -> () {}
+                    if self.token.kind == token::RArrow
+                        && let Some(t) = [sym::FnOnce, sym::FnMut, sym::Fn]
+                            .into_iter()
+                            .find(|s| self.prev_token.is_ident_named(*s))
+                    {
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/item.rs:2287]:
```suggestion
                    if self.token.kind == token::RArrow {
```

You could theoretically generalize this by not special-casing `Fn{,Mut,Once}` similar to #104531 (#108185). This would allow us to suggest adding `()` in cases like

```rs
fn f(_: impl Function -> ()) {}
use FnOnce as Function;
```

Comment (clubby789) [reply compiler/rustc_parse/src/parser/item.rs:2287]: What would be a good message in that case? Maybe something like
diagnostic: "expected a function body, found `->`"
note: "you may be trying to write a `Fn*` family trait bound, which require arguments in parentheses"
suggestion: (maybe-incorrect) "try adding parentheses"

Comment (fmease) [reply compiler/rustc_parse/src/parser/item.rs:2287]: Hmm, I'd just say “`Fn` bounds require arguments in parentheses” or “expected list of arguments before `->`”, not sure. #104531 just says “`Fn` traits […]” showing complete disregard for the concrete trait (`FnOnce`, `FnMut`, …).

Comment (fmease) [reply compiler/rustc_parse/src/parser/item.rs:2287]: Personally I'd prefer “`Fn`-family (trait) bound” but I'm not sure if we already use this terminology already in diagnostics. “expected a function *body* [my emphasis], found ->” wouldn't be correct, since it's about the argument list, not a body.

And yeah it's maybe-incorrect, I guess. You could make it conditional on the name. So if it isn't `Fn{,Mut,Once}` the suggestion is maybe-incorrect, otherwise, machine-applicable.

**Comment by jsenkpiel-godaddy** [comment]
Nice looks like the fix to my issue was pretty simple, maybe I'll be able to follow that next time
