### PR TITLE
Do not allocate or unwind after fork

### LINKED ISSUE #79740: panic! in `Command` child forked from non-main thread results in exit status 0
If a panic occurs in a child process forked off by `Command` on a thread other than the main thread, the whole child process exits 0, so it looks like things have worked when in fact they've gone catastrophically wrong.  This seems like a serious error handling bug.

@rustbot modify labels +T-libs +libs-impl

### Steps to reproduce

```rust
use std::io;
use std::process::Command;
use std::os::unix::process::CommandExt;
use std::thread;

fn main() -> Result<(),io::Error> {
    let thr = thread::spawn(||{
        let mut c = Command::new("echo");
        c.arg("hi");
        unsafe {
            c.pre_exec(|| panic!("crash now!"));
        }
        let st = c.status().expect("get status");
        println!("{:?}", st);
    });
    thr.join().expect("joined");
    Ok(())
}
```

### Actual behaviour

```
thread '<unnamed>' panicked at 'crash now!', t.rs:11:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ExitStatus(ExitStatus(0))
```

### Expected behaviour

 * The spawned thread builds the Command.
 * `Command.status` tries to run the command, so
 * `Command.status` forks, and then runs the `pre_exec` closure
 * The `pre_exec` closure panics
 * Consequently, the child process exits with `SIGABRT` or in any case nonzero
 * `st` is not a success

Specifically, the last line should be something like `ExitStatus(ExitStatus(25856))` (which is what you get without the `thread::spawn`)

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (3ff10e74a 2020-12-04)
binary: rustc
commit-hash: 3ff10e74a74ed093fcabac1de27fe1cd65bbbb4a
commit-date: 2020-12-04
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

<details><summary>Backtrace (not particularly enlightening)</summary>
<p>
```
thread '<unnamed>' panicked at 'crash now!', t.rs:11:27
stack backtrace:
   0: std::panicking::begin_panic
   1: t::main::{{closure}}::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/library/alloc/src/boxed.rs:1314:9
   3: std::sys::unix::process::process_inner::<impl std::sys::unix::process::process_common::Command>::do_exec
             at /rustc/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/library/std/src/sys/unix/process/process_unix.rs:228:13
   4: std::sys::unix::process::process_inner::<impl std::sys::unix::process::process_common::Command>::spawn
             at /rustc/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/library/std/src/sys/unix/process/process_unix.rs:58:36
   5: std::process::Command::status
             at /rustc/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/library/std/src/process.rs:904:9
   6: t::main::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
ExitStatus(ExitStatus(0))

```

</p>
</details>

### PR DESCRIPTION
**Pull request by ijackson**
### Objective scenarios

 * Make (simple) panics safe in `Command::pre_exec_hook`, including most `panic!` calls, `Option::unwrap`, and array bounds check failures.
 * Make it possible to `libc::fork` and then safely panic in the child (needed for the above, but this requirement means exposing the new raw hook API which the `Command` implementation needs).
 * In singlethreaded programs, where panic in `pre_exec_hook` is already memory-safe, prevent the double-unwinding malfunction #79740.

I think we want to make panic after fork safe even though the post-fork child environment is only experienced by users of `unsafe`, beause the subset of Rust in which any panic is UB is really far too hazardous and unnatural.

#### Approach

 * Provide a way for a program to, at runtime, switch to having panics abort.  This makes it possible to panic without making *any* heap allocations, which is needed because on some platforms malloc is UB in a child forked from a multithreaded program (see https://github.com/rust-lang/rust/pull/80263#issuecomment-774272370, and maybe also the SuS [spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fork.html)).
 * Make that change in the child spawned by `Command`.
 * Document the rules comprehensively enough that a programmer has a fighting chance of writing correct code.
 * Test that this all works as expected (and in particular, that there aren't any heap allocations we missed)

Fixes #79740

#### Rejected (or previously attempted) approaches

 * Change the panic machinery to be able to unwind without allocating, at least when the payload and message are both `'static`.  This seems like it would be even more subtle.  Also that is a potentially-hot path which I don't want to mess with.
 * Change the existing panic hook mechanism to not convert the message to a `String` before calling the hook.  This would be a surprising change for existing code and would not be detected by the type system.
 * Provide a `raw_panic_hook` function to intercept panics in a way that doesn't allocate.  (That was an earlier version of this MR.)

### History

This MR could be considered a v2 of #80263.  Thanks to everyone who commented there.  In particular, thanks to @m-ou-se, @Mark-Simulacrum and @hyd-dev.  (Tagging you since I think you might be interested in this new MR.)  Compared to #80263, this MR has very substantial changes and additions.

Additionally, I have recently (2021-04-20) completely revised this series following very helpful comments from @m-ou-se.

r? @m-ou-se

### CODE REVIEW

File: library/std/src/sys/unix/ext/process.rs [hunk 1]
```diff
@@ -74,6 +76,12 @@ pub trait CommandExt {
     /// sure that the closure does not violate library invariants by making
     /// invalid use of these duplicates.
     ///
+    /// Panicking in the hook is safe only if all the format arguemnts for the panic message can be
```
Comment (the8472) [inline library/std/src/sys/unix/ext/process.rs:79]:
```suggestion
    /// Panicking in the hook is safe only if all the format arguments for the panic message can be
```

File: library/std/src/panicking.rs [hunk 2]
```diff
@@ -160,6 +270,23 @@ pub fn set_hook(hook: Box<dyn Fn(&PanicInfo<'_>) + 'static + Sync + Send>) {
 /// ```
 #[stable(feature = "panic_hooks", since = "1.10.0")]
 pub fn take_hook() -> Box<dyn Fn(&PanicInfo<'_>) + 'static + Sync + Send> {
+    take_hook_raw().0
+}
+
+/// Unregisters the current panic hook, returning it, saying whether it was a raw hook.
```
Comment (the8472) [inline library/std/src/panicking.rs:276]:
```suggestion
/// Unregisters the current panic hook, returns it along with a flag indicating whether it was a raw hook.
```

File: library/std/src/sys/unix/ext/process.rs [hunk 3]
```diff
@@ -314,3 +322,102 @@ impl IntoRawFd for process::ChildStderr {
...
 }
+
+/// Panic hook which prints to stderr and aborts.
+///
+/// Prints the panic information to stderr using raw system calls on fd 2, and then aborts.
+///
+/// When called (typically, during a panic), this hook will not heap allocate unless `panic!` was
+/// passed format arguments whose formatting involves heap allocation.
+///
+/// Typically installed usingt [`std::panic::set_raw_hook`](crate::panic::set_raw_hook) or
```
Comment (the8472) [inline library/std/src/sys/unix/ext/process.rs:333]:
```suggestion
/// Typically installed using [`std::panic::set_raw_hook`](crate::panic::set_raw_hook) or
```

**Review by the8472 — COMMENTED** [review]
Would this also work for vfork?

**Comment by ijackson** [comment]
> Would this also work for vfork?

vfork is more tricky, because anything you mutate in the child stays mutated (or may do - some people provide a vfork which is just fork...)

I think allocation is still potentially unsafe because you may deadlock with your suspended parent, and the thread ids or TLS etc. may make no sense to your allocator.  So you still want to be able to avoid allocation and this MR achieves that.

There's the additional complication that with vfork, setting the panic hook affects the parent too.  You'd have to Do Something about that.  Maybe check the pid in your hook.

So I think this MR makes it easier to DTRT for vfork, but I haven't thought about it thoroughly.  In particular I'm not sure if even after this MR, it is possible to arrange for it to be safe to panic after vfork.

**Comment by ijackson** [comment]
Rebased onto master and fixed the trivial merge conflict.

**Comment by ijackson** [comment]
Rebased onto master and fixed the trivial merge conflict.

**Review by m-ou-se — COMMENTED** [review]
This adds quite a large API surface area for a very niche issue. It'd be great to make panicking after fork safer, but I'm not sure if it's worth it to add so many new things for it. Maybe there's a simpler way that would be good enough?

A big part of the api (the raw_hook) is only there to avoid the allocation of a `String` after a `panic!()` with formatting arguments, right? The alternative would be to only have this work for `panic!("literal without arguments")`, which does not allocate before the hook is executed. That won't work on `Result::unwrap()` though. (But it would for `Option::unwrap()`.)

Not sure how/if we could do this, but maybe we could instead make a way to fully disable the global allocator. Replace it with one that won't (de)allocate anything anymore. That would prevent a lot more misusages in pre_exec, and we could have the panic handler skip allocating the String before calling the hook, if allocation fails.

File: library/std/src/sys/unix/ext/process.rs [hunk 4]
```diff
@@ -328,3 +336,102 @@ impl IntoRawFd for process::ChildStderr {
...
+/// # } // #[cfg(unix)]
+/// ```
+#[cold]
+#[unstable(feature = "raw_panic_hooks", issue = "none")]
+pub fn panic_emergency(info: &PanicInfo<'_>) {
+    use crate::io::{self, Write};
+    use core::fmt;
+
+    struct StderrWriter;
+    impl io::Write for StderrWriter {
```
Comment (m-ou-se) [inline library/std/src/sys/unix/ext/process.rs:411]: By the way, we already `std::sys_common::util::dump_print` for this.

**Comment by m-ou-se** [comment]
Another idea would be to be able to set some kind of flag (or set `panic_count` to a special value) that would cause `rust_panic_with_hook` to simply `util::dump_print + abort`, just like it already does for `panic_count > 2`. Then you don't need to do anything with the hook at all.

**Comment by ijackson** [comment]
@m-ou-se Thanks for the review.  You make many good observations and suggestions which I don't have time to look at right now in detail.  I will come back to this.  Thanks!

@rustbot modify labels -S-waitng-on-review +S-waiting-on-author

**Comment by crlf0710** [comment]
@ijackson Ping from triage! Any updates on this? Also, there's merge conflict now.

**Comment by ijackson** [comment]
> @ijackson Ping from triage! Any updates on this? Also, there's merge conflict now.

Hi.  Thanks for the ping.  I may be able to look at this today...

**Comment by ijackson** [comment]
> Not sure how/if we could do this, but maybe we could instead make a way to fully disable the global allocator. Replace it with one that won't (de)allocate anything anymore. That would prevent a lot more misusages in pre_exec, and we could have the panic handler skip allocating the String before calling the hook, if allocation fails.

I think this would be ideal.  However it is really tough.  The existing compile-time indirections boil each call to the allocator down to a call to `malloc`, without any runtime indirection or status checks or anything like that.  Adding some kind of additional check to that path is, I think, out of the question.  Ideally the libc would provide us with a way to cause `malloc` to abort; for any reasonable implementation there will be a slow path whose use could be forced and which could do the additional check.  But that's not where we are.  I will pursue your other ideas.

**Comment by ijackson** [comment]
> Another idea would be to be able to set some kind of flag (or set `panic_count` to a special value) that would cause `rust_panic_with_hook` to simply `util::dump_print + abort`, just like it already does for `panic_count > 2`. Then you don't need to do anything with the hook at all.

I tried this approach and it worked very well with very little code.

I chose to steal a bit out of the top of the thread-local `panic_count`.  In principle the thing is now a struct containing this one bit, plus a (n-1)-bit counter, but that would be bigger than one word, so I chose to pick a flag bit.  The flag can only be set, never cleared, and always forces panics to go via the slow path.

**Comment by ijackson** [comment]
@rustbot modify labels -S-waiting-on-author +S-waiting-on-review

@m-ou-se Thanks for your very helpful comments a few weeks ago.  I went with one of your suggestions and I think it has turned out a lot better than my original approach.

File: library/std/src/panic.rs [hunk 5]
```diff
@@ -461,5 +461,41 @@ pub fn resume_unwind(payload: Box<dyn Any + Send>) -> ! {
     panicking::rust_panic_without_hook(payload)
 }
 
+/// Make all future panics abort rather than unwinding.
```
Comment (m-ou-se) [inline library/std/src/panic.rs:464]: This might make it sound like this only has effect in `panic = "unwind"` situations. But even in `panic = "abort"` this still prevents the panic hook from running.

Maybe something like this:
```suggestion
/// Make all future panics abort directly without running the panic hook or unwinding.
```

File: library/std/src/panic.rs [hunk 6]
```diff
@@ -461,5 +461,41 @@ pub fn resume_unwind(payload: Box<dyn Any + Send>) -> ! {
...
+/// execs (or the equivalent).
+///
+/// # Use after fork
+///
+/// This function is particularly useful for calling after `libc::fork`.  After `fork`, in a
+/// multithreaded program it is (on many platforms) not safe to call the allocator.  It is also
+/// generally highly undesirable for an unwind to unwind past the `fork`, because that results in
+/// the unwind propagating to code that was only ever expecting to run in the parent.
+///
+/// `panicc::always_abort()` helps avoid both of these.  It directly avoids any further unwinding,
```
Comment (m-ou-se) [inline library/std/src/panic.rs:476]:
```suggestion
/// `panic::always_abort()` helps avoid both of these.  It directly avoids any further unwinding,
```

Comment (m-ou-se) [reply library/std/src/panic.rs:476]: It'd be good to also mention here the panic hook will not be executed.

File: library/std/src/sys/unix/ext/process.rs [hunk 7]
```diff
@@ -75,6 +75,12 @@ pub trait CommandExt: Sealed {
     /// sure that the closure does not violate library invariants by making
     /// invalid use of these duplicates.
     ///
+    /// Panicking in the hook is safe only if all the format arguemnts for the
```
Comment (m-ou-se) [inline library/std/src/sys/unix/ext/process.rs:78]:
```suggestion
    /// Panicking in the closure is safe only if all the format arguments for the
```

File: library/std/src/panicking.rs [hunk 8]
```diff
@@ -261,6 +263,14 @@ pub mod panic_count {
         })
     }
 
+    pub fn set_always_abort() {
+        GLOBAL_PANIC_COUNT.fetch_add(1, Ordering::Relaxed); // it will always be nonzero, now
+        LOCAL_PANIC_COUNT.with(|c| {
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:268]: Why only set this on the current thread instead of for the entire process?

File: library/std/src/panic.rs [hunk 9]
```diff
@@ -461,5 +461,41 @@ pub fn resume_unwind(payload: Box<dyn Any + Send>) -> ! {
...
+/// panic::always_abort();
+///
+/// let _ = panic::catch_unwind(|| {
+///     panic!("inside the catch");
+/// });
+///
+/// // We will have aborted already, due to the panic.
+/// unreachable!();
+/// ```
+#[unstable(feature = "panic_always_abort", issue = "none")]
```
Comment (m-ou-se) [inline library/std/src/panic.rs:495]: Can you [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX)?

File: library/std/src/panicking.rs [hunk 10]
```diff
@@ -571,7 +581,16 @@ fn rust_panic_with_hook(
...
     if panics > 2 {
-        util::dumb_print(format_args!("thread panicked while processing panic. aborting.\n"));
+        if (panics & !panic_count::ALWAYS_ABORT_FLAG) > 2 {
+            // Don't try to print the message in this case
+            // - perhaps that is causing the recursive panics.
+            util::dumb_print(format_args!("thread panicked while processing panic. aborting.\n"));
+        } else {
+            if let Some(message) = message {
+                util::dumb_print(*message);
+            }
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:591]: It'd be good to display the message and location in the same way as the regular panics.

If you construct a `PanicInfo` with `PanicInfo::internal_constructor(message, location)`, you can format that `PanicInfo` instead of just the message. It has a `Display` implementation that shows `panicked at '{message}', {location}` or `panicked at {location}` depending on whether a message is available.

(Then you could also combine both dump_print calls here into one, since `PanicInfo` will take care of handling the `message = None` case.)

File: library/std/src/sys/unix/process/process_unix/tests.rs [hunk 11]
```diff
@@ -28,3 +35,22 @@ fn exitstatus_display_tests() {
...
+            c.pre_exec(|| panic!("{}", "crash now!"));
+        }
+        let st = c.status().expect("failed to get command status");
+        dbg!(st);
+        st
+    });
+    dbg!(&got);
+    let status = got.expect("panic unexpectedly propagated");
+    dbg!(status);
+    let signal = status.signal().expect("expected child to die of signal");
```
Comment (m-ou-se) [inline library/std/src/sys/unix/process/process_unix/tests.rs:54]: Let's make this sound a bit less grim ^^'
```suggestion
    let signal = status.signal().expect("expected child process to die of signal");
```

File: src/test/ui/process/process-panic-after-fork.rs [hunk 12]
```diff
@@ -0,0 +1,150 @@
...
+
+    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
+        self.check();
+        self.parent.realloc(ptr, layout, new_size)
+    }
+}
+
+fn expect_aborted(status: ExitStatus) {
+    dbg!(status);
+    let signal = status.signal().expect("expected child to die of signal");
```
Comment (m-ou-se) [inline src/test/ui/process/process-panic-after-fork.rs:80]:
```suggestion
    let signal = status.signal().expect("expected child process to die of signal");
```

File: src/test/ui/process/process-panic-after-fork.rs [hunk 13]
```diff
@@ -0,0 +1,150 @@
...
+    assert!(signal == libc::SIGABRT || signal == libc::SIGILL);
+}
+
+fn main() {
```
Comment (m-ou-se) [inline src/test/ui/process/process-panic-after-fork.rs:84]: This is a great test. :)

**Review by m-ou-se — COMMENTED** [review]
Looks great! Thanks for working on this!

I have a bunch of comments, but they're all small:

File: library/std/src/panicking.rs (hunk 8 above)
Comment (ijackson) [reply library/std/src/panicking.rs:268]: > Why only set this on the current thread instead of for the entire process?

This is a thinko on my part.  I was thinking about the post-`fork` case where of course there is only one thread.  But `panic::always_panic` may be used in other situations and should be entirely global.  That means that the magic bit needs to be in GLOBAL_PANIC_COUNT, not in LOCAL_PANIC_COUNT.  I will rework this.

And also add a test :-).

Comment (ijackson) [reply library/std/src/panicking.rs:268]: > Why only set this on the current thread instead of for the entire process?

Fixing this involved strengthening the `Ordering` of the reads of the global panic count, to `Acquire`.  The writes are still `Relaxed`.  I hope this is OK.  I think this is a necessary consequence of having `panic::always_abort` be global.  Having it be local would be an alternative possibility (though I would have to check what happens if a thread with a local panic count ends...)

File: library/std/src/panicking.rs [hunk 14]
```diff
@@ -571,7 +594,18 @@ fn rust_panic_with_hook(
     // process real quickly as we don't want to try calling it again as it'll
     // probably just panic again.
     if panics > 2 {
-        util::dumb_print(format_args!("thread panicked while processing panic. aborting.\n"));
+        if (panics & !panic_count::ALWAYS_ABORT_FLAG) > 2 {
+            // Don't try to print the message in this case
+            // - perhaps that is causing the recursive panics.
+            util::dumb_print(format_args!("thread panicked while processing panic. aborting.\n"));
+        } else {
+            let location = Location::caller();
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:602]: The location of the panic is already given as an argument to this function.
```suggestion
```

File: library/std/src/panicking.rs [hunk 15]
```diff
@@ -241,33 +243,54 @@ pub mod panic_count {
...
+    }
+
+    pub fn set_always_abort() {
+        GLOBAL_PANIC_COUNT.fetch_or(ALWAYS_ABORT_FLAG, Ordering::Release);
     }
 
     pub fn get() -> usize {
-        LOCAL_PANIC_COUNT.with(|c| c.get())
+        GLOBAL_PANIC_COUNT.load(Ordering::Acquire) & ALWAYS_ABORT_FLAG
+            | LOCAL_PANIC_COUNT.with(|c| c.get())
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:288]: Why does `get()` need to include the flag? I think this counter is only used by the default hook, which isn't invoked when the flag is enabled.

File: library/std/src/panicking.rs [hunk 16]
```diff
@@ -241,33 +243,54 @@ pub mod panic_count {
...
+    // Even a newtype around usize would be clumsy because we need atomics.
+    //
+    // Stealing a bit is fine because it just amounts to assuming that each
+    // panicking thread consumes at least 2 bytes of address space.
     static GLOBAL_PANIC_COUNT: AtomicUsize = AtomicUsize::new(0);
 
+    pub fn is_always_panic(value: usize) -> bool {
+        value & ALWAYS_ABORT_FLAG != 0
+    }
+
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:263]: Is this used anywhere?

File: library/std/src/panicking.rs [hunk 17]
```diff
@@ -288,7 +311,7 @@ pub mod panic_count {
     #[inline(never)]
     #[cold]
     fn is_zero_slow_path() -> bool {
-        LOCAL_PANIC_COUNT.with(|c| c.get() == 0)
+        get() == 0
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:314]: This would result in `std::thread::panicking()` always returning true when 'always abort' mode has been set.

File: library/std/src/panicking.rs [hunk 18]
```diff
@@ -241,33 +243,54 @@ pub mod panic_count {
...
+    //
+    // Stealing a bit is fine because it just amounts to assuming that each
+    // panicking thread consumes at least 2 bytes of address space.
     static GLOBAL_PANIC_COUNT: AtomicUsize = AtomicUsize::new(0);
 
+    pub fn is_always_panic(value: usize) -> bool {
+        value & ALWAYS_ABORT_FLAG != 0
+    }
+
     pub fn increase() -> usize {
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:264]: Maybe it makes things a bit easier to read if this returns `(usize, bool)`. Then the code below can do
```rust
let (panics, must_abort) = panic_count::increase();
```

**Review by m-ou-se — COMMENTED** [review]
I'm a bit confused about the memory ordering. This is basically just a global `ALWAYS_ABORT: AtomicBool` flag independent of the counter(s), right? (Just integrated into the global counter so they can be read at once.) Why does that need a memory ordering other than Relaxed?

File: library/std/src/panicking.rs (hunk 10 above)
Comment (ijackson) [reply library/std/src/panicking.rs]: > It'd be good to display the message and location in the same way as the regular panics.
> 
> If you construct a `PanicInfo` with `PanicInfo::internal_constructor(message, location)`
...
> (Then you could also combine both dump_print calls here into one, since `PanicInfo` will take care of handling the `message = None` case.)

Thanks for the suggestion, which I have incorporated.  Ideally we would print a backtrace but AFAICT we cannot do that without allocating, with the existing `Backtrace` api.

**Comment by ijackson** [comment]
> I'm a bit confused about the memory ordering. This is basically just a global `ALWAYS_ABORT: AtomicBool` flag independent of the counter(s), right? (Just integrated into the global counter so they can be read at once.)

Precisely.

Thanks for looking closely at this part.  I was going to ask you specifically to do that, since this is concurrent code with explicitly synchronisation and while I think it is correct, humans are in fact terrible at this kind of thing...

> Why does that need a memory ordering other than Relaxed?

Because if thread A calls `always_abort` and "then" thread B calls `panic`, we need B to see the update.  ("then" here is the notional program ordering implied by other atomics etc. in the rest of the program, ie as implied by other synchronisations)  With `Relaxed` I think B could continue to see an old value of `GLOBAL_PANIC_COUNT` - in principle, forever.  So `B` might unwind.

File: library/std/src/panicking.rs (hunk 18 above)
Comment (ijackson) [reply library/std/src/panicking.rs:264]: > Maybe it makes things a bit easier to read if this returns `(usize, bool)`. Then the code below can do
> 
> ```rust
> let (panics, must_abort) = panic_count::increase();
> ```

Mmm.  I tried that.  It is rather more typesafe.  I had a reason for changing it but now that I try to explain the reason it seems to make no sense.

I think changing this will fix a couple of your other comments too...

File: library/std/src/panicking.rs (hunk 17 above)
Comment (ijackson) [reply library/std/src/panicking.rs:314]: > This would result in `std::thread::panicking()` always returning true when 'always abort' mode has been set.

You are right.  I should have done the more typesafe thing with having `increase` return a tuple as you suggested.  That would have caught this.  The branch has become too much of a mess with this flail and I will force push it when I've fixed things and have a comprehensible story.

**Comment by the8472** [comment]
If this is only meant to be set after a fork then there are no other threads. Are there other situations where this should be usable?

**Comment by ijackson** [comment]
> If this is only meant to be set after a fork then there are no other threads. Are there other situations where this should be usable?

That is a reasonable question.  It would be possible to declare that this function only affects the current thread.  However, that is quite a strange API.  (We need to expose this API because everyone who calls `libc::fork` needs it.)

**Comment by ijackson** [comment]
@m-ou-se Thanks for your review and sorry for the flail.  I think it's better now.

**Comment by ijackson** [comment]
> other threads

In particular, there is only one ordering strengthening now, the one on panic entry.  I think that's OK from a perf pov.

File: library/std/src/panicking.rs [hunk 19]
```diff
@@ -241,33 +243,53 @@ pub mod panic_count {
...
-    pub fn increase() -> usize {
-        GLOBAL_PANIC_COUNT.fetch_add(1, Ordering::Relaxed);
-        LOCAL_PANIC_COUNT.with(|c| {
-            let next = c.get() + 1;
-            c.set(next);
-            next
-        })
+    pub fn increase() -> (bool, usize) {
+        (
+            GLOBAL_PANIC_COUNT.fetch_add(1, Ordering::Acquire) & ALWAYS_ABORT_FLAG != 0,
```
Comment (m-ou-se) [inline library/std/src/panicking.rs:262]: `Ordering::Relaxed` should suffice here (and below in `set_always_abort`). We're not using this flag to synchronize any other data. Any 'happens-before' relationship that might be necessary should already be provided by whatever caused that need. E.g. thread spawning, changing some global allocator property, etc:

If a thread does something like `always_abort(); some_global = 1` and another thread runs code that would somehow be unsound if `some_global == 1` is observed while it doesn't yet see the always-abort flag, that's a problem with the memory ordering on the store+load of `some_global`, and is not solved by an acquire+release ordering on the always-abort flag.

(Specifically, in `always_abort(); thread::spawn(|| ..);`, the always-abort flag is definitely directly visible inside that thread, because spawning a thread synchronizes and guarantees that everything that happened before also already happened from the perspective the new thread as well.)

The other way around, it should never be a problem if `some_global = 1; always_abort();` is executed by one thread and another thread observes the always-abort flag already set while still seeing `some_global != 1`. It might mean that it aborts instead of unrolls when it wasn't strictly necessary yet.

**Review by m-ou-se — COMMENTED** [review]
Sorry for the delay! Looks good to me now, just a small typo and a comment on the memory ordering:

**Comment by m-ou-se** [comment]
> Because if thread A calls `always_abort` and "then" thread B calls `panic`, we need B to see the update. ("then" here is the notional program ordering implied by other atomics etc. in the rest of the program, ie as implied by other synchronisations) With `Relaxed` I think B could continue to see an old value of `GLOBAL_PANIC_COUNT` - in principle, forever. So `B` might unwind.

Acquire+release is no guarantee that changes are observed 'immediately'*. Just like a relaxed store+load, a release store might also not be observed by a acquire load until 'forever' (in theory**). It only means that if/once the change is observed, you can be sure that everything that happened before the release store is also visible.

(*Not that 'immediately' has a good definition in a world where things happen in different orders depending on where you're looking from.)
(**In practice, all these orderings are only about reordering instructions, so within the timescale of clockcycles.)

**Comment by ijackson** [comment]
> `Ordering::Relaxed` should suffice here

I spent a while with the memory ordering docs and have convinced myself that you are correct.  Thanks.

File: src/test/ui/process/process-panic-after-fork.rs [hunk 20]
```diff
@@ -0,0 +1,151 @@
...
+// ignore-windows
+// ignore-sgx no libc
+// ignore-emscripten no processes
+// ignore-sgx no processes
+
+#![feature(bench_black_box)]
+#![feature(rustc_private)]
+#![feature(never_type)]
+#![feature(panic_always_abort)]
+#![feature(test)]
```
Comment (hyd-dev) [inline src/test/ui/process/process-panic-after-fork.rs:13]: I think this was for `black_box` so it's not required now (since it's gated under `bench_black_box` instead).

Comment (ijackson) [reply src/test/ui/process/process-panic-after-fork.rs]: Let's try it and see.,.

Comment (ijackson) [reply src/test/ui/process/process-panic-after-fork.rs]: Hooray.  Thank you.

**Comment by ijackson** [comment]
@m-ou-se Thanks for the review.  Please let me know if you would like me to squash down some or all of the fixes.  (Personally I'd be inclned to keep the top commit, with `Relaxed`, separate in any case.)

@rustbot modify labels -S-waiting-on-author +S-waiting-on-review

**Comment by m-ou-se** [comment]
@ijackson Yes, squashing some of the commits would be good. Feel free to keep things in separate commits where you think that makes sense. :)

Once you're done, you can tell bors: `r=m-ou-se`, to approve the PR on my behalf.

Thanks again for implementing this!

@bors delegate+

**Comment by ijackson** [comment]
@bors r=m-ou-se

Thanks!

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/85032#issuecomment-834402121) 

@bors r-

File: library/std/src/sys/unix/process/process_unix/tests.rs [hunk 21]
```diff
@@ -28,3 +35,24 @@ fn exitstatus_display_tests() {
         t(0x000ff, "unrecognised wait status: 255 0xff");
     }
 }
+
+#[test]
+fn test_command_fork_no_unwind() {
+    if cfg!(target_os = "emscripten") { return }
```
Comment (m-ou-se) [inline library/std/src/sys/unix/process/process_unix/tests.rs:41]:
```suggestion
#[test]
#[cfg_attr(target_os = "emscripten", ignore)]
fn test_command_fork_no_unwind() {
```

**Comment by ijackson** [comment]
Bear with me, flailing with git slightly

**Comment by ijackson** [comment]
OK, I have pushed a commit to disable this test under emscripten.  It would have been better to instead have it simply call it a pass if `Command::status` returns `ErrorKind::Unsupported`, but emscripten returns the wrong errno value and we do not want to tolerate `EAGAIN` here.

@Dylan-DPC would it be best to do a separate CI run for this to see if there are other issues, or should we just try it again?

@m-ou-se I guess since you reviewed it and I adopted your suggestion, I should tell bors to approve it on your behalf, again?

**Comment by m-ou-se** [comment]
Thanks!

@bors r+ rollup=iffy

> would it be best to do a separate CI run for this to see if there are other issues, or should we just try it again?

(`rollup=iffy` marks this PR as something we should probably not test together with other PRs)

**Comment by ijackson** [comment]
```
engaging allocator trap, parent pid=10817
[/checkout/src/test/ui/process/process-panic-after-fork.rs:79] status = ExitStatus(
    ExitStatus(
        5,
    ),
)
thread 'main' panicked at 'assertion failed: signal == libc::SIGABRT || signal == libc::SIGILL', /checkout/src/test/ui/process/process-panic-after-fork.rs:81:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`ExitStatus` (really, wait status) 5 is `WIFSIGNALED` with `SIGTRAP`.

This is perplexing.  It must mean that something allocated in the child.  This is in the very first test.  The only things the child does is `panic::always_abort()` (which definitely does not allocate) and `panic!()` (without arguments).  The `abort-on-panic` test passed which means that there, `panic!()` after `panic::always_abort()` did not allocate.

Theories that seem to be excluded by the pass of `abort-on-panic`:
 * Something os-specific on this platform allocates somewhere in panic entry
 * Something os-specific on this platform allocates in `util::dumb_print`.

Theories that might explain it would seem to include:
  * On this platform, `libc::fork` allocates in the child before returning to the caller.  This seems implausible since why would `libc` do anything with Rust's global allocator.
 * The test is flaky somehow, so the pass of `abort-on-panic` was luck.  But `abort-on-panic` does not have any concurrency.  No threads, and the only child processes are spawned and then immediately waited for.
 * The `abort-on-panic` test was fooled somehow;  maybe on this platform aborting produces `WIFEXITED` `WEXITSTATUS==1` or something?  This really seems quite unlikely.
 * I am confused and some of my reasoning above is wrong.

Can we get some expert on `arm-linux-androideabi` to look at this?  It looks like quite a pain to debug from a standing start.  AFAICT this is a tier 2 platform, so it would be acceptable to simply disable this test there, but I would rather at least give someone  chance to fix it.  Alternatively, I guess I could disable it now and file an issue asking for it to be looked at.

**Comment by hyd-dev** [comment]
> * On this platform, aborting always produces `SIGTRAP`.  That would be very odd.  (The `abort-on-panic` test does not check the precise signal so wouldn't notice.)

I think that's possible, according to https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20121015/153706.html:
> `__builtin_trap()` behave differently on different systems. e.g. it raises `SIGTRAP` on ARM, and `SIGILL` on X86.

(AFAIK `intrinsics::abort()` == `llvm.trap` == `__builtin_trap()`)

**Comment by ijackson** [comment]
> > * On this platform, aborting always produces `SIGTRAP`.  That would be very odd.  (The `abort-on-panic` test does not check the precise signal so wouldn't notice.)
> 
> I think that's possible, according to https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20121015/153706.html:
> 
> > `__builtin_trap()` behave differently on different systems. e.g. it raises `SIGTRAP` on ARM, and `SIGILL` on X86.
> 
> (AFAIK `intrinsics::abort()` == `llvm.trap` == `__builtin_trap()`)

Uhhh.  How strange.  `SIGTRAP` is for debug traps, which are different from aborts.  `SIGABRT` is what you would expect abort to generate.  Which is why I chose it for my test case.  In SuS, C's, `abort()` is guaranteed to generate `SIGABRT`.

**Comment by ijackson** [comment]
OK.  Well.  Thanks for this information!  Very helpful!

After consulting a llvm expert local to me, I think this may be a bug in Rust stdlib.  It seems to me that on Unix Rust's panic abort should always generate `SIGABRT`.  But I don't want to entangle this MR in that yak!

I will change the test case to use `SIGUSR1` instead of `SIGTRAP` and take up the strange behaviour of `abort()` separately, possibly in #85261 or elsewhere.

**Comment by ijackson** [comment]
I'm pretty sure these further changes are uncontroversial so I intend to try to use the "bors r delegate" from earlier to self-approve this when the initial CI run completes.

**Comment by hyd-dev** [comment]
```
engaging allocator trap, parent pid=10725
[/checkout/src/test/ui/process/process-panic-after-fork.rs:79] status = ExitStatus(
    ExitStatus(
        10,
    ),
)
thread 'main' panicked at 'assertion failed: signal == libc::SIGABRT || signal == libc::SIGILL || signal == libc::SIGTRAP', /checkout/src/test/ui/process/process-panic-after-fork.rs:81:5
```
Sorry for the useless `SIGTRAP` information... :facepalm:

**Comment by ijackson** [comment]
> Sorry for the useless `SIGTRAP` information... facepalm

I think in fact having looked at the implementation of `intrinsics::abort`, your information was right but there is *also* an actual alloc-after-fork bug.  I'm going suppress the test on Android.  It seems there's a convention for how to refer to the issue in the test suppression directive, yay.

@rustbot modify labels -O-android

**Comment by ijackson** [comment]
@bors r+ rollup=iffy

(Should I be using `rollup=never` by now?  There is a definite air here of "this time for sure"...)

**Comment by ijackson** [comment]
Hooray!  Thanks everyone.

**Comment by m-ou-se** [comment]
This is now available on nightly: https://doc.rust-lang.org/nightly/std/panic/fn.always_abort.html

Thanks for working on this, @ijackson!
