### PR TITLE
 Rust 2015: No longer downgrade NLL errors

### LINKED ISSUE #27868: Inconsistent evaluation order for assignment operations
UPDATE: This is fixed by the MIR-based borrow checker and just needs a test. [See the mentoring instructions below.](https://github.com/rust-lang/rust/issues/27868#issuecomment-378392425)

---

Currently, the borrow checker thinks that the RHS of `+=` is evaluated before the LHS.  trans thinks that the LHS is evaluated before the RHS.  The disagreement leads to bad results.

``` rust
fn main() {
    let x = Box::new(0);
    let mut y = 0;
    *{ drop(x); &mut y } += *x;
    assert_eq!(y, 0);
}
```

### LINKED ISSUE #31567: `Drop` and leaking `&mut` references
There's a way to leak a `&mut` member borrowed from a struct, and then manipulate that member from the `Drop` handler -- even while it is immutably borrowed!

``` rust
struct VecWrapper<'a>(&'a mut Vec<u8>);

impl<'a> IntoIterator for VecWrapper<'a> {
    type Item = &'a u8;
    type IntoIter = std::slice::Iter<'a, u8>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

impl<'a> Drop for VecWrapper<'a> {
    fn drop(&mut self) {
        // aggressively free memory
        self.0.clear();
        self.0.shrink_to_fit();
    }
}

fn main() {
    let mut v = vec![1, 2, 3];
    for i in VecWrapper(&mut v) {
        let s = "foo".to_owned(); // reused allocation
        println!("{}!  {} {:#x} '{}'", s, i, i, *i as char);
    }
}
```

[playground](http://is.gd/v4Qi95) output:

```
foo!  102 0x66 'f'
foo!  111 0x6f 'o'
foo!  111 0x6f 'o'
```

So this drop frees the vec's buffer, then an unrelated string allocation reuses the same memory, and those new values come out of the `vec::Iter`.

I think if the member was immutable `&`, then this "leak" from `into_iter()` would be fine since they can both share that reference, and `Drop` can't mutate it.  But `&mut` must be exclusive, of course...

### LINKED ISSUE #38899: borrowed referent of a `&T` sometimes incorrectly allowed
@jorendorf asks on [the users forum](https://users.rust-lang.org/t/why-are-reads-sometimes-tolerated-during-mut-borrows-and-sometimes-not/8774) about a curious discrepancy around fields. It seems that implicit borrows sometimes seem to get overlooked in the borrow checker.  This seems like a kind of bad bug, though it's exact scope is unclear until we investigate a bit more. 

Here is a variant of @jorendorf's example which is pretty clearly wrong. Here, the `block` variable is mutably borrowed into `x`, so it should not be accessible via `let p`:

```rust
#![allow(dead_code)]
pub struct Block<'a> {
    current: &'a u8,
    unrelated: &'a u8,
}

fn bump<'a>(mut block: &mut Block<'a>) {
    let x = &mut block;
    let p: &'a u8 = &*block.current;
	// (use `x` and `p` so enabling NLL doesn't assign overly short lifetimes)
	drop(x);
	drop(p);
}

fn main() {}
```

I'm guessing that the problem has to do with the logic around borrowing the referent of an `&T` (in this case, we are borrowing `*block.current`). In particular, we deem that to be "safe" for the scope of `'a` because the data is independently guaranteed to be valid that long (this is reasonable). But we still need to validate that `block.current` can be (instantaneously) read. It seems we are not doing that. But this is all a hypothesis: I've not dug into the code to validate it.

### LINKED ISSUE #45157: Borrow checker unsoundness with unions
```rust
#![allow(unused)]

#[derive(Clone, Copy, Default)]
struct S {
    a: u8,
    b: u8,
}
#[derive(Clone, Copy, Default)]
struct Z {
    c: u8,
    d: u8,
}

union U {
    s: S,
    z: Z,
}

fn main() { unsafe {
    let mut u = U { s: Default::default() };
    
    let mref = &mut u.s.a;
    let err = &u.z.c; // This line compiles, but it certainly shouldn't ...
    drop(mref); // ... (at least if `mref` is used after `err`)
}}
```

"Cousins" of borrowed union sub-fields (and their further children) are not marked as borrowed.
~~The same bug should happen with move checking as well, but I haven't made an example yet.~~

### LINKED ISSUE #47366: tracking issue for bugs fixed by the MIR borrow checker or NLL
Part of: https://github.com/rust-lang/rust/issues/43234

The MIR-based borrow checker used by NLL fixes a number of bugs in the existing AST-based borrow checker. Our plan for these bugs is to fix them by transitioning to the MIR-based borrow checker. In the meantime, we wish to add tests that show that the bugs are fixed with NLL, and then close the bugs (so they don't clutter up the issue tracker).  This issue tracks the set of such bugs and gives instructions for how to proceed.

## Bugs fixed by MIR

All these bugs are **confirmed as fixed**; the checkmark indicates that a PR with a test is enqueued or landed.

- [x] https://github.com/rust-lang/rust/issues/46557
- [x] https://github.com/rust-lang/rust/issues/38899
- [x] #45045 (using example from [this comment](https://github.com/rust-lang/rust/issues/45045#issuecomment-356953507))
- [x] https://github.com/rust-lang/rust/issues/46314
- [x] #47053  (PR https://github.com/rust-lang/rust/pull/47425)
- [x] https://github.com/rust-lang/rust/issues/47366 (examples from [this comment])
- [x] https://github.com/rust-lang/rust/issues/29149 (fix in https://github.com/rust-lang/rust/pull/47877)
- [x] #16223 
- [x] #48238 (and specifically [this reduction](https://github.com/rust-lang/rust/issues/48238#issuecomment-366048269))
- [x] https://github.com/rust-lang/rust/issues/45157
- [x] https://github.com/rust-lang/rust/issues/46314 (hygiene interaction)
- [x] https://github.com/rust-lang/rust/issues/27868 -- evaluation order and operators
- [x] https://github.com/rust-lang/rust/issues/16223 -- incorrect partially moved value error check

## Procedure

- First, if you wish, add yourself to the [list of participants for the WG-compiler-nll working group](https://docs.google.com/spreadsheets/d/1vymoSTIzepS6PVidHJWsMOVl12aSXixMev0LBLKLykY/edit?usp=sharing).
    - This will help us to find people who might like to help later!
- Create a regression test in `src/test/ui/nll/`
    - The name can be `issue-XXX.rs`, though giving a more descriptive name is also good
    - The file should include a comment saying `// Regression test for #XXX` however to ease searching later
- This test should include the error from the bug along with the following header material:
    - Rust license
    - `#![feature(nll)]` at the top
    - comments like `//~ ERROR` for the errors, or whatever is needed for test harness to pass
- Run `./x.py test --stage 1 src/test/ui --test-args nll`, this will test all the nll tests (including yours)
- Presuming that passes, open a PR! Otherwise, stop in at the [WG-compiler-nll gitter channel](https://gitter.im/rust-impl-period/WG-compiler-nll)
    - Put `r? @nikomatsakis` in the PR summary

### LINKED ISSUE #53432: Bug: nested closure outlives borrowed value.
```rust
extern crate futures;
extern crate tokio_core;

use futures::{future, Future};
use tokio_core::reactor::Core;

pub trait Action {
    type Output: Future<Item = (), Error = ()>;

    fn run(self) -> Self::Output;
}

impl<T: Future<Item=(), Error=()>, F: FnOnce() -> T> Action for F {
    type Output = T;

    fn run(self) -> Self::Output {
        self()
    }
}

fn retry<A: Action>(action: A) -> impl Future<Item = (), Error = ()> {
    action.run()
}

/*

The `lazy` closure avoids the check of its lifetime here, if:
- the `lazy` closure is nested into the `action` closure, and
- the `action` closure is passed into the `retry` function, and
- the `retry` function take a generic by the `Action` trait argument, and
- the `Action` trait is implemented for an `Fn*` trait.

As a result, we get arbitrary values in variables and at best SIGSEGV.

*/

fn main() {
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    for i in &[1, 2, 3, 4, 5] {
        println!("outer: {}", i);

        let f = move || {
            println!("inner: {}", i);
            future::ok::<(), ()>(())
        };

        let action = move || {
            future::lazy(|| { // The `lazy` closure
                f()
            })
        };
        handle.spawn(retry(action))
    }

    core.run(future::empty::<(), ()>()).expect("Core::run");
}

```

([Playground](http://play.rust-lang.org/?gist=4a9eee50ba36ad6af4c4528d4fd552a9&version=stable&mode=debug&edition=2015))

Output:

```
outer: 1
outer: 2
outer: 3
outer: 4
outer: 5
inner: 1027752016
inner: 1027752016
inner: 1027752016
inner: 1027752016
inner: 1027752016

```

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
    Finished dev [unoptimized + debuginfo] target(s) in 2.29s
     Running `target/debug/playground`
/root/entrypoint.sh: line 8:     8 Killed                  timeout --signal=KILL ${timeout} "$@"

```

This emits a warning in the 2018 edition mode, but silently accepts code leading to UB in the 2015 edition.

### PR DESCRIPTION
**Pull request by Centril**
As per decision on a language team meeting as described in https://github.com/rust-lang/rust/pull/63565#issuecomment-528563744, in Rust 2015, we refuse to downgrade NLL errors, that AST borrowck accepts, into warnings and keep them as hard errors.

The remaining work to throw out AST borrowck and adjust some tests still remains after this PR.

Fixes https://github.com/rust-lang/rust/issues/38899
Fixes https://github.com/rust-lang/rust/issues/53432
Fixes https://github.com/rust-lang/rust/issues/45157
Fixes https://github.com/rust-lang/rust/issues/31567
Fixes https://github.com/rust-lang/rust/issues/27868
Fixes https://github.com/rust-lang/rust/issues/47366

r? @matthewjasper

### CODE REVIEW

**Comment by Centril** [comment]
Marking as *blocked* on changing nightly to 1.40.

File: src/test/ui/consts/min_const_fn/min_const_fn.rs [hunk 1]
```diff
@@ -136,9 +136,7 @@ const fn no_rpit() -> impl std::fmt::Debug {} //~ ERROR `impl Trait` in const fn
 const fn no_dyn_trait(_x: &dyn std::fmt::Debug) {} //~ ERROR trait bounds other than `Sized`
 const fn no_dyn_trait_ret() -> &'static dyn std::fmt::Debug { &() }
 //~^ ERROR trait bounds other than `Sized`
-//~| WARNING cannot return reference to temporary value
-//~| WARNING this error has been downgraded to a warning
-//~| WARNING this warning will become a hard error in the future
+//~| ERROR cannot return reference to temporary value
```
Comment (matthewjasper) [inline src/test/ui/consts/min_const_fn/min_const_fn.rs]: Note to self: min const fn qualification failing causing temporary promotion to fail really should be fixed.

File: src/test/ui/feature-gates/feature-gate-nll.rs [hunk 2]
```diff
@@ -1,20 +1,18 @@
 // There isn't a great way to test feature(nll), since it just disables migrate
-// mode and changes some error messages. We just test for migrate mode.
+// mode and changes some error messages.
+
+// FIXME(Centril): This test is probably obsolete now and `nll` should become
+// `accepted`.
```
Comment (matthewjasper) [inline src/test/ui/feature-gates/feature-gate-nll.rs]: Probably, the `-Z` flags are probably sufficient for the remaining borrowck configuration. This can be a future PR.

File: src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.rs [hunk 3]
```diff
@@ -2,27 +2,16 @@
 // mutable borrows that would be scribbled over by destructors before
 // the return occurs.
 //
-// We will explicitly test NLL, and migration modes;
-// thus we will also skip the automated compare-mode=nll.
+// We will explicitly test NLL; thus we will also skip the automated compare-mode=nll.
```
Comment (matthewjasper) [inline src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.rs]: This no longer appears to be the case.

File: src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.migrate.stderr [hunk 4]
```diff
@@ -1,4 +1,4 @@
-warning[E0713]: borrow may still be in use when destructor runs
+error[E0713]: borrow may still be in use when destructor runs
```
Comment (matthewjasper) [inline src/test/ui/issues/issue-45696-scribble-on-boxed-borrow.migrate.stderr]: File should be deleted

**Review by matthewjasper — APPROVED** [review]
r=me with the couple of nits addressed

cc @rust-lang/lang

File: src/test/ui/consts/min_const_fn/min_const_fn.rs (hunk 1 above)
Comment (Centril) [reply src/test/ui/consts/min_const_fn/min_const_fn.rs]: Might be worth filing an issue; cc @oli-obk

**Comment by Centril** [comment]
Fixed the two currently actionable nits (+ rebased -- don't want to rebuild LLVM :P).

@bors r=matthewjasper

🚀

**Comment by Centril** [comment]
Had to bump webrender and iron in cargotest due to failure in https://github.com/rust-lang/rust/pull/64800#issuecomment-535329207.

File: src/test/ui/consts/min_const_fn/min_const_fn.rs (hunk 1 above)
Comment (eddyb) [reply src/test/ui/consts/min_const_fn/min_const_fn.rs]: Should probably go away once we decouple promotion and const-checking.

**Comment by Centril** [comment]
@bors r=matthewjasper

Carried over @pnkfelix's note in https://github.com/rust-lang/rust/pull/64790#discussion_r328502898 to this PR.
