### PR TITLE
std: Stabilize APIs for the 1.9 release

### LINKED ISSUE #27719: Tracking issue for `recover` stabilization
The `recover` function is able, on a single thread, to recover from a panic. There are numerous controversies around this API, including the bounds it applies to its closure, its safety, and its location within `std`. An [open RFC](https://github.com/rust-lang/rfcs/pull/1236) seeks to settle these issues and open the door to stabilization.

cc @alexcrichton

### LINKED ISSUE #27754: Tracking issue for `str_char` stabilization
The `str` type offers a number of `char`-oriented methods, many of which can be replaced by uses of `char_indices`.

It's not clear how widely used these methods are, or whether there are significant downsides over using `char_indices`. This API area needs a comprehensive re-evaluation.

cc @SimonSapin

### LINKED ISSUE #27780: Tracking issue for <*mut T, *const T>::{as_ref, as_mut_ref}
This is a tracking issue for the unstable `ptr_as_ref` feature of the standard library. These functions allow unsafely converting raw pointers to optional safe references, returning `None` if they're null.

I would personally vote for removing these, but there's certainly some usage throughout the standard distribution.

cc @Gankro

### LINKED ISSUE #27809: Tracking issue for make_ascii_{upper,lower}case
This is a tracking issue for the unstable `ascii` feature in the standard library. These functions have the somewhat odd naming scheme of `make_*` (not found elsewhere in the standard library). The utility with `&mut str` is also somewhat questionable as there's not a lot of support for that in the standard library.

Overall this probably just largely needs a decision.

### LINKED ISSUE #27811: Tracking issue for CommandExt::session_leader
This is a tracking issue for the unstable `process_session_leader` feature in the standard library. Added in #26470 some open questions are:

* Is there a Windows "equivalent" that should mean this is exposed on `Command` directly?
* Is this the best name for the function? Should it just be called `setsid`?
* Is this best done through some different means? (e.g. a closure-after-fork approach)

cc @l0kod

### LINKED ISSUE #27830: Tracking issue for UTF-16 decoding iterators
#27808 proposes exposing in `std::char` two iterator adaptors `Utf16Decoder` and `Utf16LossyDecoder`. This functionality was previously only available with an API that require allocation (`String::from_utf16{,_lossy}`) or using the unstable `rustc_unicode` crate directly.

They are exposed unstable with a new `utf16_decoder` feature name. I’d like to stabilize them when we’re confident with the naming and API.

### LINKED ISSUE #28050: Set recovery methods
Tracking issue for https://github.com/rust-lang/rfcs/pull/1194

cc https://github.com/rust-lang/rust/pull/28043

### LINKED ISSUE #29453: Add Capacity/length methods for OsString
Tracking issue for https://github.com/rust-lang/rfcs/pull/1307

### LINKED ISSUE #29791: Tracking issue for getting pthread_t from JoinHandle
This is a tracking issue for the `thread_extensions` feature in the standard library which allows acquiring a `pthread_t` from a `JoinHandle` on Unix. Some questions on this are:

* Should this trait also be implemented for `Thread`? (e.g. should we store the id there)
* Does it deserve its own trait or is a one-off `JoinHandleExt` ok?
* If you can get a `pthread_t` from a `Thread` can you also get a `HANDLE` from one on Windows?

### LINKED ISSUE #29935: Tracking issue for `#[deprecated]`
Tracking issue for https://github.com/rust-lang/rfcs/pull/1270

### LINKED ISSUE #30014: Tracking issue for OpenOptions expansion
Tracking issue for https://github.com/rust-lang/rfcs/pull/1252

Unstable APIs:

* [x] `OpenOptions::create_new`
* [ ] `os::unix::fs::OpenOptionsExt::custom_flags`
* [ ] `os::windows::fs::OpenOptionsExt::custom_flags`

### LINKED ISSUE #30752: Tracking issue for panic::propagate
`panic::propagate` triggers a panic without invoking the panic handler or wrapping the payload in a `Box<Any>`, allowing for panics to be recovered from at an FFI boundary, transported back into Rust and restarted.

### LINKED ISSUE #31262: `HashMap` and `HashSet` should provide a getter for their hashers
```rust
impl<K: Eq + Hash, V, S: BuildHasher> HashMap<K, V, S> {
    pub fn hasher(&self) -> &S { &self.hash_builder }
}

impl<T: Eq + Hash, S: BuildHasher> HashSet<T, S> {
    pub fn hasher(&self) -> &S { self.map.hasher() }
}
```

This would let us close contain-rs/linked-hash-map#3, and likely has other (niche) uses for code that needs to reproduce hashes.

### LINKED ISSUE #31405: Tracking issue for file_try_clone

### LINKED ISSUE #31572: Tracking issue for SocketAddr setters
#31083 adds `set_ip` and `set_port` methods to `SocketAddr`, `SocketAddrV4`, and `SocketAddrV6`; as well as `set_flowinfo` and `set_scope_id` on `SocketAddrV6`. They are all fairly straightforward and correspond to existing getter methods.

As all new additions, they will be `#[unstable]` for now.

### LINKED ISSUE #31755: Tracking issue for <[T]>::copy_from_slice
Tracking issue for https://github.com/rust-lang/rfcs/pull/1419

### LINKED ISSUE #31756: Tracking issue for ptr::{read,write}_volatile
Tracking issue for https://github.com/rust-lang/rfcs/pull/1467

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit applies all stabilizations, renamings, and deprecations that the
library team has decided on for the upcoming 1.9 release. All tracking issues
have gone through a cycle-long "final comment period" and the specific APIs
stabilized/deprecated are:

Stable
- `std::panic`
- `std::panic::catch_unwind` (renamed from `recover`)
- `std::panic::resume_unwind` (renamed from `propagate`)
- `std::panic::AssertUnwindSafe` (renamed from `AssertRecoverSafe`)
- `std::panic::UnwindSafe` (renamed from `RecoverSafe`)
- `str::is_char_boundary`
- `<*const T>::as_ref`
- `<*mut T>::as_ref`
- `<*mut T>::as_mut`
- `AsciiExt::make_ascii_uppercase`
- `AsciiExt::make_ascii_lowercase`
- `char::decode_utf16`
- `char::DecodeUtf16`
- `char::DecodeUtf16Error`
- `char::DecodeUtf16Error::unpaired_surrogate`
- `BTreeSet::take`
- `BTreeSet::replace`
- `BTreeSet::get`
- `HashSet::take`
- `HashSet::replace`
- `HashSet::get`
- `OsString::with_capacity`
- `OsString::clear`
- `OsString::capacity`
- `OsString::reserve`
- `OsString::reserve_exact`
- `OsStr::is_empty`
- `OsStr::len`
- `std::os::unix::thread`
- `RawPthread`
- `JoinHandleExt`
- `JoinHandleExt::as_pthread_t`
- `JoinHandleExt::into_pthread_t`
- `HashSet::hasher`
- `HashMap::hasher`
- `CommandExt::exec`
- `File::try_clone`
- `SocketAddr::set_ip`
- `SocketAddr::set_port`
- `SocketAddrV4::set_ip`
- `SocketAddrV4::set_port`
- `SocketAddrV6::set_ip`
- `SocketAddrV6::set_port`
- `SocketAddrV6::set_flowinfo`
- `SocketAddrV6::set_scope_id`
- `<[T]>::copy_from_slice`
- `ptr::read_volatile`
- `ptr::write_volatile`
- The `#[deprecated]` attribute
- `OpenOptions::create_new`

Deprecated
- `std::raw::Slice` - use raw parts of `slice` module instead
- `std::raw::Repr` - use raw parts of `slice` module instead
- `str::char_range_at` - use slicing plus `chars()` plus `len_utf8`
- `str::char_range_at_reverse` - use slicing plus `chars().rev()` plus `len_utf8`
- `str::char_at` - use slicing plus `chars()`
- `str::char_at_reverse` - use slicing plus `chars().rev()`
- `str::slice_shift_char` - use `chars()` plus `Chars::as_str`
- `CommandExt::session_leader` - use `before_exec` instead.

Closes #27719
cc #27751 (deprecating the `Slice` bits)
Closes #27754
Closes #27780
Closes #27809
Closes #27811
Closes #27830
Closes #28050
Closes #29453
Closes #29791
Closes #29935
Closes #30014
Closes #30752
Closes #31262
cc #31398 (still need to deal with `before_exec`)
Closes #31405
Closes #31572
Closes #31755
Closes #31756

### CODE REVIEW

File: src/libcore/ptr.rs [hunk 1]
```diff
@@ -166,9 +166,16 @@ pub unsafe fn write<T>(dst: *mut T, src: T) {
...
-/// operations. See the LLVM documentation on [[volatile]].
+/// operations.
 ///
-/// [volatile]: http://llvm.org/docs/LangRef.html#volatile-memory-accesses
+/// # Notes
+///
+/// Rust does not currently have a rigorously and formally defined memory model,
+/// so the precise semantics of what "volatile" means here is subject to change
+/// over time. That being said, the semantics will almost always end up pretty
+/// close to what [C11's definition of volatile is][c11].
```
Comment (brson) [inline src/libcore/ptr.rs]: -> "close to C11's definition of volatile". Extra "what" and "is".

Comment (brson) [inline src/libcore/ptr.rs]: or "end up similar to C11's..."

File: src/libstd/ffi/os_str.rs [hunk 2]
```diff
@@ -86,54 +86,51 @@ impl OsString {
         self.inner.push_slice(&s.as_ref().inner)
     }
 
-    /// Creates a new `OsString` with the given capacity. The string will be
-    /// able to hold exactly `capacity` bytes without reallocating. If
-    /// `capacity` is 0, the string will not allocate.
+    /// Creates a new `OsString` with the given capacity.
+    ///
+    /// The string will be able to hold exactly `capacity` lenth units of other
+    /// OS stringswithout reallocating. If `capacity` is 0, the string will not
```
Comment (brson) [inline src/libstd/ffi/os_str.rs]: "stringswithout"

File: src/libstd/panic.rs [hunk 3]
```diff
@@ -104,18 +104,24 @@ pub fn take_handler() -> Box<Fn(&PanicInfo) + 'static + Sync + Send> {
...
 /// (more on this below).
-#[unstable(feature = "recover", reason = "awaiting feedback", issue = "27719")]
+#[stable(feature = "catch_unwind", since = "1.9.0")]
 #[rustc_on_unimplemented = "the type {Self} may not be safely transferred \
                             across a recover boundary"]
+pub trait UnwindSafe {}
+
+/// Deprecated, renamed to UnwindSafe
+#[unstable(feature = "recover", reason = "awaiting feedback", issue = "27719")]
 pub trait RecoverSafe {}
```
Comment (brson) [inline src/libstd/panic.rs]: Add rustc_deprecated?

File: src/libsyntax/feature_gate.rs [hunk 4]
```diff
@@ -237,7 +237,7 @@ const KNOWN_FEATURES: &'static [(&'static str, &'static str, Option<u32>, Status
     ("stmt_expr_attributes", "1.6.0", Some(15701), Active),
 
     // Allows `#[deprecated]` attribute
-    ("deprecated", "1.6.0", Some(29935), Active),
+    ("deprecated", "1.6.0", Some(29935), Accepted),
```
Comment (brson) [inline src/libsyntax/feature_gate.rs]: This should be bumped to 1.9.0. "The version numbers here correspond to the version in which the current status
// was set".

**Comment by brson** [comment]
r=me w/ feedback

File: src/compiletest/compiletest.rs [hunk 5]
```diff
@@ -411,16 +410,26 @@ fn extract_gdb_version(full_version_line: Option<String>) -> Option<String> {
...
-                if full_version_line.char_at(pos + 1) != '.' { continue }
-                if !full_version_line.char_at(pos + 2).is_digit(10) { continue }
-                if pos > 0 && full_version_line.char_at_reverse(pos).is_digit(10) {
+                if !c.is_digit(10) {
+                    continue
+                }
+                if pos + 2 >= full_version_line.len() {
+                    continue
+                }
+                if full_version_line[pos + 1..].chars().next().unwrap() != '.' {
```
Comment (tamird) [inline src/compiletest/compiletest.rs]: not sure it matters, but you could probably use just one iterator here rather than 3.

ditto on L464

File: src/librustc/session/mod.rs [hunk 6]
```diff
@@ -351,11 +351,11 @@ fn split_msg_into_multilines(msg: &str) -> Option<String> {
             return None
     }
     let first = msg.match_indices("expected").filter(|s| {
-        s.0 > 0 && (msg.char_at_reverse(s.0) == ' ' ||
-                    msg.char_at_reverse(s.0) == '(')
+        s.0 > 0 && (msg[..s.0].chars().rev().next() == Some(' ') ||
```
Comment (tamird) [inline src/librustc/session/mod.rs]: seems easy to extract a local binding

**Comment by Manishearth** [comment]
```
src/libstd/panic.rs:125:21: 125:32 error: use of deprecated item: renamed to `UnwindSafe`

src/libstd/panic.rs:125 impl<T: UnwindSafe> RecoverSafe for T {}
                                            ^~~~~~~~~~~
src/libstd/lib.rs:283:31: 283:39 note: lint level defined here
src/libstd/lib.rs:283 #![cfg_attr(not(stage0), deny(warnings))]
```

File: src/compiletest/compiletest.rs (hunk 5 above)
Comment (alexcrichton) [inline src/compiletest/compiletest.rs]: Perhaps yeah, but this is pretty brittle and has no tests, so I'd rather not tamper with it too much.

**Comment by bluss** [comment]
```rust
rustc: x86_64-pc-windows-msvc/stage0/lib/rustlib/x86_64-pc-windows-msvc/lib/libstd
../src/libstd\sys/windows\ext\thread.rs:19:1: 23:2 error: This node does not have a stability attribute
../src/libstd\sys/windows\ext\thread.rs:19 impl<T> AsRawHandle for thread::JoinHandle<T> {
../src/libstd\sys/windows\ext\thread.rs:20     fn as_raw_handle(&self) -> RawHandle {
../src/libstd\sys/windows\ext\thread.rs:21         self.as_inner().handle().raw() as *mut _
../src/libstd\sys/windows\ext\thread.rs:22     }
../src/libstd\sys/windows\ext\thread.rs:23 }
../src/libstd\sys/windows\ext\thread.rs:25:1: 29:2 error: This node does not have a stability attribute
../src/libstd\sys/windows\ext\thread.rs:25 impl<T> IntoRawHandle for thread::JoinHandle<T>  {
../src/libstd\sys/windows\ext\thread.rs:26     fn into_raw_handle(self) -> RawHandle {
../src/libstd\sys/windows\ext\thread.rs:27         self.into_inner().into_handle().into_raw() as *mut _
../src/libstd\sys/windows\ext\thread.rs:28     }
../src/libstd\sys/windows\ext\thread.rs:29 }
error: aborting due to 2 previous errors
```

**Comment by brson** [comment]
These will need to be backported.
