### PR TITLE
Warn on pointless #[derive] in more places

### LINKED ISSUE #49934: Regression in 1.26 with misplaced attributes
All the regressed crates have a misplaced `#[derive]` in the codebase (such as a `#[derive(Debug)]` above a variable declaration). In Rust 1.25 the compiler accepts the code, but in Rust 1.26 it throws an error _and then_ crashes.

* [bitlab](https://crates.io/crates/bitlab) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/bitlab-0.8.1/log.txt)) cc @kkayal
* [promise-rs](https://crates.io/crates/promise-rs) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/promise-rs-0.3.0/log.txt)) cc @stan-kondrat
* [serde_bencode](https://crates.io/crates/serde_bencode) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/serde_bencode-0.2.0/log.txt)) cc @toby
* [paulkramme/rustybrainfuck](https://github.com/paulkramme/rustybrainfuck) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/gh/paulkramme.rustybrainfuck.072942e1220da27ccc56b3bc04c7165bdf5cef0d/log.txt)) cc @paulkramme

Even if we keep the error (which could be turned into a warn-by-default lint) the ICE should be fixed.

### PR DESCRIPTION
**Pull request by abonander**
This fixes the regression in #49934 and ensures that unused `#[derive]` invocations on statements, expressions and generic type parameters survive to trip the `unused_attributes` lint. There is a separate warning hardcoded for `#[derive]` on macro invocations since linting (even the early-lint pass) occurs after expansion. This also adds regression tests for some nodes that were already warning properly.

closes #49934

### CODE REVIEW

**Comment by abonander** [comment]
The regression test won't be effective until #49826 is merged, however. compile-fail is eating ICEs because they're not reported as such (#49888).

**Comment by pietroalbini** [comment]
Maybe you can use an ui test instead of a compile-fail test? Also yeah, if the extra derive on statements doesn't cause any trouble but it's just for correctness, I would prefer a warn-by-default lint.

File: src/test/compile-fail/issue-49934.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+#![feature(stmt_expr_attributes)]
+
+fn main() {
+    #[derive(Debug)] //~ ERROR `derive`
```
Comment (petrochenkov) [inline src/test/compile-fail/issue-49934.rs]: >//~ ERROR `derive`

That's very informative.
Also + to @pietroalbini's suggestion about UI tests.

**Comment by petrochenkov** [comment]
@abonander 
There were few regressions, some of them have reverse dependencies, so it would indeed make sense to make this a deprecation lint instead of a hard error, if that's not too much hassle.

**Comment by abonander** [comment]
@petrochenkov I made it a hard warning instead of a deprecation lint (since there's nothing being deprecated here)

File: src/test/ui/issue-49934.stderr [hunk 2]
```diff
@@ -0,0 +1,24 @@
+warning: `#[derive]` on non-item statements is ignored
```
Comment (abonander) [inline src/test/ui/issue-49934.stderr]: Bikeshedding:

Better term than "non-item statement"? (That items are a subtype of statements is an idiosyncrasy of the current AST)

And:

"is ignored", "does nothing", or "is meaningless"?

Comment (pietroalbini) [reply src/test/ui/issue-49934.stderr]: Maybe "`#[derive]` can only be applied to items"?

Comment (abonander) [reply src/test/ui/issue-49934.stderr]: That doesn't explain why it's a warning and not an error, though.

**Comment by abonander** [comment]
@pietroalbini can you mark this `Waiting on Review` please

**Comment by pietroalbini** [comment]
Sure. Also, @petrochenkov, ping! This fixes a beta regression.

**Comment by abonander** [comment]
@petrochenkov I was also thinking we could just leave the `#[derive]` unexpanded and cover it in the unused-attributes lint. Would that be preferable?

**Comment by petrochenkov** [comment]
@abonander 
That depends on whether we want to make it an error in the future or not.
It's also somewhat a policy question.
So many attributes are not checked and allowed in nonsense positions right now. Will we be able to make them errors in the future without breaking unreasonable amount of code? Maybe not, then there's a chance that all misplaced attributes will end up as reported as unused in the future.
I'd personally be in favor of a separate deprecation lint probably, but unused lint would probably be as effective in practice.

**Comment by petrochenkov** [comment]
@abonander 
By the way, what happens if `derive` attribute is applied to some other place where no expansion currently happen, like a match arm or a type parameter?

**Comment by abonander** [comment]
@petrochenkov I assume it gets picked up by the unused-attributes lint unless something earlier forbids all attributes in that position. It was probably already triggering for `#[derive]` on statements before my expansion PR broke it. I can look through the code if you need a more solid answer.

**Comment by abonander** [comment]
The unused-attributes lint seems to be the most semantically appropriate lint, especially because I'm almost sure it was already triggering on `#[derive]` on statements before the breaking change.

**Comment by pietroalbini** [comment]
@petrochenkov @abonander do you want to change how this PR is implemented? It's not needed to merge this *right now*, but it would be nice to have this backported in the next week.

**Comment by abonander** [comment]
@pietroalbini yeah if you want to r- I'll pivot this to fall-through to the unused-attributes lint, that's definitely better than hardcoding a warning.

**Comment by pietroalbini** [comment]
I don't have review permissions, let's see if this stops the build though.

@bors force

**Comment by abonander** [comment]
@petrochenkov It's hilariously inconsistent (it's set to stable branch): https://play.rust-lang.org/?gist=43643beeb19d33a3da505b2432ec9e48&version=stable&mode=debug

**Comment by abonander** [comment]
I've got it mostly in-place now, however the attribute on `let` bindings still doesn't warn for some reason, and I also need to update the stderr for the UI test. I'll work on this more later today.

**Comment by abonander** [comment]
@petrochenkov the one problem with making this a lint is that crates that use `#[deny(unused_attributes)]` would see this as a breaking change. Is there any policy yet on expanding the scope of a given lint?

**Comment by xfix** [comment]
@abonander It's fine, see https://github.com/arcnmx/rust-rfcs/blob/master/text/1105-api-evolution.md#lints.

**Comment by abonander** [comment]
This is really funny. Somewhere the `#[derive]` attribute on the `let` statement is being completely forgotten but I can't figure out why. It's somewhere in the lowering from AST to HIR.

**Comment by abonander** [comment]
Maybe because [HIR visit doesn't visit attributes when walking `let` bindings](https://github.com/rust-lang/rust/blob/master/src/librustc/hir/intravisit.rs#L407).

**Comment by abonander** [comment]
@petrochenkov @pietroalbini I've got every case covered except `#[derive]` on macro invocations since those are eliminated before the `unused_attributes` lint fires. We do check attributes on macro invocs but it's mostly for feature-gating; should I just hardcode a warning for this specific case or do we not really care?

**Comment by abonander** [comment]
The UI test also seems to be passing `-A unused` and silencing the warnings.

**Comment by abonander** [comment]
Figured it out. Need an answer to https://github.com/rust-lang/rust/pull/50092#issuecomment-385218411. The commits are a mess, I know, I'll squash when we're ready.

**Comment by abonander** [comment]
We may want a more detailed warning for `#[derive]` on macro invocations because I can see a user trying to use it to add a derived trait to a macro-generated type (especially if the macro is from an external crate):

```rust
macro_rules! make_struct {
    ($name:ident) => (
        pub struct $name;
}

#[derive(Debug)]
make_struct!(Foo);
```

The user might expect this to expand to 

```rust
#[derive(Debug)]
pub struct Foo;
```

But it of course doesn't work that way. A novice user might find this confusing, though I guess marking the `#[derive]` unused and `Foo` not implementing `Debug` when used might be enough of a hint.

**Comment by abonander** [comment]
I hardcoded a warning for `#[derive]` on macros. Squashing.

File: src/libsyntax/ast.rs [hunk 3]
```diff
@@ -821,7 +821,7 @@ impl Stmt {
 
     pub fn is_item(&self) -> bool {
         match self.node {
-            StmtKind::Local(_) => true,
+            StmtKind::Item(_) => true,
```
Comment (petrochenkov) [inline src/libsyntax/ast.rs]: :laughing:

File: src/test/ui/issue-49934.rs [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+    // fold_expr
+    let _ = #[derive(Debug)] "Hello, world!";
+    //~^ WARN unused attribute
+
+    let _ = [
+        // fold_opt_expr
+        #[derive(Debug)] //~ WARN unused attribute
+        "Hello, world!"
+    ];
```
Comment (petrochenkov) [inline src/test/ui/issue-49934.rs]: Could you add test cases for https://github.com/rust-lang/rust/pull/50092#issuecomment-385158914 as well?
I.e. something like
```rust
fn f<#[derive(Debug)] T>() {
    match 0 {
        #[derive(Debug)]
        _ => {}
    }
}
```

File: src/libsyntax/ast.rs (hunk 3 above)
Comment (abonander) [reply src/libsyntax/ast.rs]: Hey, you missed it too. I don't wanna hear it 😛

File: src/test/ui/issue-49934.rs (hunk 4 above)
Comment (abonander) [reply src/test/ui/issue-49934.rs]: @petrochenkov `intravisit` is already walking attributes on match arms, but it is not walking attributes on type parameters. Do you want me to implement that as well? It's a one-line change.

Comment (petrochenkov) [reply src/test/ui/issue-49934.rs]: Sure, the more bugs are fixed the better, especially with one-line changes.

**Comment by abonander** [comment]
@petrochenkov updated.

File: src/test/ui/issue-49934.rs (hunk 4 above)
Comment (abonander) [reply src/test/ui/issue-49934.rs]: Updated.

File: src/libsyntax/ext/derive.rs [hunk 5]
```diff
@@ -19,6 +19,20 @@ use syntax_pos::Span;
...
+pub fn remove_derive_spans<A: HasAttrs>(item: A) -> (A, Vec<Span>) {
+    let mut derive_spans = Vec::new();
+
+    let item = item.map_attrs(|mut attrs| {
+        derive_spans.extend(attrs.drain_filter(|a| a.path == "derive").map(|a| a.span));
+        attrs
+    });
+
+    (item, derive_spans)
+}
```
Comment (abonander) [inline src/libsyntax/ext/derive.rs]: this method is unused but isn't being warned about because it's public

File: src/librustc/hir/intravisit.rs [hunk 6]
```diff
@@ -404,7 +404,7 @@ pub fn walk_local<'v, V: Visitor<'v>>(visitor: &mut V, local: &'v Local) {
     // Intentionally visiting the expr first - the initialization expr
     // dominates the local's definition.
     walk_list!(visitor, visit_expr, &local.init);
-
+    walk_list!(visitor, visit_attribute, local.attrs.iter());
```
Comment (abonander) [inline src/librustc/hir/intravisit.rs]: I would almost recommend an audit of the entire `intravisit` module to ensure that anywhere attributes can appear they're being visited. This missing line took me three hours to debug because I assumed it was something wrong with _my_ code.

File: src/libsyntax/ext/expand.rs [hunk 7]
```diff
@@ -1001,7 +1040,14 @@ impl<'a, 'b> Folder for InvocationCollector<'a, 'b> {
 
         // we'll expand attributes on expressions separately
         if !stmt.is_expr() {
-            let (attr, derives, stmt_) = self.classify_item(stmt);
+            let (attr, derives, stmt_) = if stmt.is_item() {
```
Comment (abonander) [inline src/libsyntax/ext/expand.rs]: I think I could flatten these two conditionals plus the `if let StmtKind::Mac(_)` to a single `match` if it's preferred.

File: src/librustc/hir/intravisit.rs (hunk 6 above)
Comment (abonander) [reply src/librustc/hir/intravisit.rs]: It looks like every type in `hir` that has an `attrs` field is now being walked by `intravisit`. I think I've fixed the last of the discrepancies.

Comment (abonander) [reply src/librustc/hir/intravisit.rs]: On a different note, this field and a couple others use `ThinVec` while the `attrs` fields on all the other types use `HirVec`. I'm not sure of the difference but I think it's just an alias anyway. However, I got an error when passing `&local.attrs` here when it works fine for invocations with `HirVec`.

**Comment by petrochenkov** [comment]
Excellent.
@bors r+
