### PR TITLE
Test `rustc-dev` in `distcheck`

### LINKED ISSUE #138646: test `rustc-dev` dist component on CI
Recently, the `rustc-dev` component was broken several times in a row (https://github.com/rust-lang/rust/issues/138304, https://github.com/rust-lang/rust/issues/138647).

It would be nice if we had some CI check that would at least run `cargo metadata` on the extracted `rustc-src` component.

CC @RalfJung - Would running `cargo metadata` be enough as a smoke test?

### PR DESCRIPTION
**Pull request by Kobzol**
Adds a new `distcheck` test component.

Fixes: https://github.com/rust-lang/rust/issues/138646

r? @jieyouxu

try-job: x86_64-gnu-distcheck

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/test.rs [hunk 1]
```diff
@@ -3229,71 +3229,97 @@ impl Step for Distcheck {
...
+        .arg("-xf")
+        .arg(tarball.tarball())
+        .arg("--strip-components=1")
+        .current_dir(dir)
+        .run(builder);
+
+    command(&builder.initial_cargo)
+        .arg("metadata")
+        .arg("--manifest-path")
+        .arg("rustc-dev/lib/rustlib/rustc-src/rust/compiler/rustc_ast/Cargo.toml")
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/test.rs]: Using `rustc/Cargo.toml` would load a crate that depends on ~all the other crates, which might give better test coverage.

**Comment by jieyouxu** [comment]
Hm, Ralf's suggestion with using `rustc`-the-crate makes sense to me.
@rustbot author

**Comment by Kobzol** [comment]
Switched to the `rustc` crate.

@rustbot ready

File: src/bootstrap/src/core/build_steps/test.rs [hunk 2]
```diff
@@ -3189,61 +3189,66 @@ impl Step for Distcheck {
...
-            // Will read the libstd Cargo.toml
-            // which uses the unstable `public-dependency` feature.
-            .env("RUSTC_BOOTSTRAP", "1")
-            .arg("generate-lockfile")
-            .arg("--manifest-path")
-            .arg(&toml)
-            .current_dir(&src_dir)
-            .run(builder);
-    }
+        distcheck_plain_source_tarball(builder, &root_dir.join("distcheck-plain-src"));
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/test.rs]: Suggestion: could you add a comment that this is `rustc-src` while the one below is `rust-src`? And even maybe change the dir name here to `distcheck-rustc-src`? I know this is historical, but `rustc-src` and `rust-src` are two incredible names that are totally not confusing.

Or maybe just change their dir names to match the actual dist component name, because I find that diverging here introduces even _more_ `*-src`s, and it really confused me. As in, `distcheck-plain-src` checks `rustc-src`, and `distcheck-src` checks `rust-src`...

**Review by jieyouxu — APPROVED** [review]
Thanks, the changes themselves look good to me, just a tiny drive-by nit on pre-existing distcheck dir names because they made it even more confusing...

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146124/51ff895062ba60a7cba53f57af928c3fb7b0f2f4..0f4c806ef87cb53bb0591a6c6e3768381cf317cb)*
