### PR TITLE
Do not consider using a semicolon inside of a different-crate macro

### LINKED ISSUE #81943: "consider using a semicolon here" when ; is present with dbg!() inside inspect()
````rust
fn main() {
let sum: i32 = [1,2,3].iter().inspect(|n| dbg!(n) ).sum();
}
````
This will suggest adding a `;`

````
error[E0308]: mismatched types
 --> src/main.rs:3:43
  |
3 | let sum: i32 = [1,2,3].iter().inspect(|n| dbg!(n) ).sum();
  |                                           ^^^^^^^
  |                                           |
  |                                           expected `()`, found `&&{integer}`
  |                                           expected this to be `()`
  |                                           help: consider using a semicolon here
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 ````
 
 But doing so will "break" the code even more and not fix the error:
 
 ````
 error: expected one of `)`, `,`, `.`, `?`, or an operator, found `;`
 --> src/main.rs:2:50
  |
2 | let sum: i32 = [1,2,3].iter().inspect(|n| dbg!(n); ).sum();
  |                                                  ^ expected one of `)`, `,`, `.`, `?`, or an operator

error[E0308]: mismatched types
 --> src/main.rs:2:43
  |
2 | let sum: i32 = [1,2,3].iter().inspect(|n| dbg!(n); ).sum();
  |                                           ^^^^^^^
  |                                           |
  |                                           expected `()`, found `&&{integer}`
  |                                           expected this to be `()`
  |                                           help: consider using a semicolon here
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

````
Could rust suggest adding `{    }` around the macro?

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #81943

### CODE REVIEW

File: compiler/rustc_typeck/src/check/coercion.rs [hunk 1]
```diff
@@ -1448,7 +1448,15 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
...
-                if cond_expr.span.desugaring_kind().is_none() {
+                // If the block is from a macro, then do not suggest
+                // adding a semicolon, because there's nowhere to put it.
+                // See issue #81943.
+                let hir = fcx.tcx.hir();
+                let body_owner =
+                    hir.body_owner(hir.body_owned_by(hir.enclosing_body_owner(fcx.body_id)));
+                let from_same_crate = cond_expr.span.ctxt().dollar_crate_name()
+                    == hir.span(body_owner).ctxt().dollar_crate_name();
+                if cond_expr.span.desugaring_kind().is_none() && from_same_crate {
```
Comment (petrochenkov) [inline compiler/rustc_typeck/src/check/coercion.rs:1459]: I'm not sure what you are trying to do here.
The previously used `cond_expr.span.desugaring_kind().is_none()` works in the right direction, but uses an incorrect function (`desugaring_kind` only reports expansions from compiler desugarings, but not from macros).

The logic here should looks like
```rust
if is_macro_expanded(cond_expr.span) {
    // emit suggestions
}
```
, but I'm not sure how the most popular `is_macro_expanded` function is called now, @estebank probably knows.
There may be multiple because people adding new ones are often not aware of the previous ones.

There's `fn in_external_macro`, but it seems to only by lints right now.

Comment (notriddle) [reply compiler/rustc_typeck/src/check/coercion.rs:1459]: `in_external_macro` is exactly what I want. I didn’t just want to check if it’s a macro. I also want to make sure it’s in a separate crate, because that’s the case where we need to suppress this diagnostic.

Comment (notriddle) [reply compiler/rustc_typeck/src/check/coercion.rs]: It's converted to `in_external_macro` now.

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/82426#issuecomment-783788984)

**Comment by notriddle** [comment]
Okay, I've rebased onto master, and also made the test slightly more robust (it uses its own macro, instead of using `dbg!`, which might change).

@rustbot -S-waiting-on-author +S-waiting-on-review

**Comment by notriddle** [comment]
LL |   f(|x| match x { tmp => { g(tmp) } };);
       |                                      ^

I know that's technically a different bug, but that's totally bogus. Apply that suggestion, and you get a syntax error

**Comment by estebank** [comment]
```
tidy error: /checkout/src/test/ui/typeck/auxiliary/issue-81943-lib.rs: too many trailing newlines (2)
some tidy checks failed
```

**Comment by notriddle** [comment]
Okay, I've set up a commit hook for tidy. That should be the last of these sorts of errors.
