### PR TITLE
Suggest replacing an inexisting field for an unmentioned field

### LINKED ISSUE #87938: Suggest a missing field when the rest of the field is found
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2c9af7b21295b19d151a109261981cd2

```rust
enum Foo {
    Bar { alpha: u8, bravo: u8, charlie: u8 },
}

fn foo(foo: Foo) {
    match foo {
        Foo::Bar {
            alpha,
            beta, // `bravo` miswritten as `beta` here.
            charlie,
        } => todo!(),
    }
}
```

The current output is:

```
error[E0026]: variant `Foo::Bar` does not have a field named `beta`
 --> src/lib.rs:9:13
  |
9 |             beta, // `bravo` miswritten as `beta` here.
  |             ^^^^ variant `Foo::Bar` does not have this field

error[E0027]: pattern does not mention field `bravo`
  --> src/lib.rs:7:9
   |
7  | /         Foo::Bar {
8  | |             alpha,
9  | |             beta, // `bravo` miswritten as `beta` here.
10 | |             charlie,
11 | |         } => todo!(),
   | |_________^ missing field `bravo`
   |
help: include the missing field in the pattern
   |
10 |             charlie, bravo } => todo!(),
   |                    ^^^^^^^^^
help: if you don't care about this missing field, you can explicitly ignore it
   |
10 |             charlie, .. } => todo!(),
   |                    ^^^^^^

error: aborting due to 2 previous errors
```

Ideally the output should look like:

```
error[E0026]: variant `Foo::Bar` does not have a field named `beta`
 --> src/lib.rs:9:13
  |
9 |             beta, // `bravo` miswritten as `beta` here.
  |             ^^^^ help: maybe replacing this for a missing field: `bravo`
```

We already provide a suggestion for similar names, for example, `brav0` is suggested to replace it for `bravo`.
Analogous to that, when the rest of the field (`alpha` & `charlie`) is mentioned, suggesting to replace the miswritten field (`beta`) for the missing field (`bravo`) can be helpful for users.

### PR DESCRIPTION
**Pull request by hkmatsumoto**
Fix #87938

This PR adds a suggestion to replace an inexisting field for an
unmentioned field. Given the following code:
```rust
enum Foo {
    Bar { alpha: u8, bravo: u8, charlie: u8 },
}

fn foo(foo: Foo) {
    match foo {
        Foo::Bar {
            alpha,
            beta, // `bravo` miswritten as `beta` here.
            charlie,
        } => todo!(),
    }
}
```
the compiler now emits the error messages below.
```text
error[E0026]: variant `Foo::Bar` does not have a field named `beta`
 --> src/lib.rs:9:13
  |
9 |             beta, // `bravo` miswritten as `beta` here.
  |             ^^^^
  |             |
  |             variant `Foo::Bar` does not have this field
  |             help: `Foo::Bar` has a field named `bravo`: `bravo`
```

Note that this suggestion is available iff the number of inexisting
fields and unmentioned fields are both 1.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/pat.rs [hunk 1]
```diff
@@ -1421,7 +1421,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                let unmentioned_field = unmentioned_fields[0].1.name;
+                err.span_suggestion(
+                    ident.span,
+                    &format!(
+                        "`{}` has a field named `{}`, try replacing `{}` for it.",
+                        tcx.def_path_str(variant.def_id),
+                        unmentioned_field,
+                        inexistent_fields[0]
+                    ),
+                    format!("{}", unmentioned_field),
```
Comment (LeSeulArtichaut) [inline compiler/rustc_typeck/src/check/pat.rs:1435]: This can be simplified to
```suggestion
                    unmentioned_field.to_string(),
```

File: compiler/rustc_typeck/src/check/pat.rs [hunk 2]
```diff
@@ -1421,7 +1421,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            if inexistent_fields.len() == 1 && unmentioned_fields.len() == 1 {
+                let unmentioned_field = unmentioned_fields[0].1.name;
+                err.span_suggestion(
+                    ident.span,
+                    &format!(
+                        "`{}` has a field named `{}`, try replacing `{}` for it.",
+                        tcx.def_path_str(variant.def_id),
+                        unmentioned_field,
+                        inexistent_fields[0]
+                    ),
```
Comment (LeSeulArtichaut) [inline compiler/rustc_typeck/src/check/pat.rs:1434]: What about keeping only the start of the sentence? The error message will already have the name of the inexistant field in it.
```suggestion
                    &format!(
                        "`{}` has a field named `{}`",
                        tcx.def_path_str(variant.def_id),
                        unmentioned_field,
                    ),
```
This will read as "struct XXX does not have a field named YYY. help: XXX has a field named ZZZ", which sounds good to me (I'm definitely not an expert in diagnostics though).

Also, other nit: messages in diagnostics usually don't end with a `.`

File: src/test/ui/issues/issue-52717.stderr [hunk 3]
```diff
@@ -2,10 +2,16 @@ error[E0026]: variant `A::A` does not have a field named `fob`
...
+   |            ^^^ variant `A::A` does not have this field
+   |
+help: `A::A` has a field named `foo`, try replacing `fob` for it.
+   |
+LL |     A::A { foo } => { println!("{}", fob); }
+   |            ~~~
+help: a field with a similar name exists
+   |
+LL |     A::A { foo } => { println!("{}", fob); }
+   |            ~~~
```
Comment (LeSeulArtichaut) [inline src/test/ui/issues/issue-52717.stderr:14]: I'm not sure we need both of these suggestions to appear in the error message. I think the second one is maybe the most accurate (?) but I could see a case for either of them to be kept.

**Review by LeSeulArtichaut — COMMENTED** [review]
Thanks for the PR, and sorry for the delay on my part. I have a few minor comments.

File: src/test/ui/issues/issue-51102.stderr [hunk 4]
```diff
@@ -3,6 +3,11 @@ error[E0026]: struct `SimpleStruct` does not have a field named `state`
    |
 LL |                 state: 0,
    |                 ^^^^^ struct `SimpleStruct` does not have this field
+   |
+help: `SimpleStruct` has a field named `no_state_here`, try replacing `state` for it.
+   |
+LL |                 no_state_here: 0,
+   |                 ~~~~~~~~~~~~~
```
[the remark this answers is not in the document]
Comment (hkmatsumoto) [reply src/test/ui/issues/issue-51102.stderr]: Do you mean to avoid emitting diagnostic when the code was something like`state: "foo"` in this case by type checking?

[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/issues/issue-51102.stderr]: Correct. But we don't need to do that as part of this PR.

File: compiler/rustc_typeck/src/check/pat.rs [hunk 5]
```diff
@@ -1468,6 +1469,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                         // We don't want to throw `E0027` in case we have thrown `E0026` for them.
                         unmentioned_fields.retain(|&(_, x)| x.name != suggested_name);
                     }
+                } else if inexistent_fields.len() == 1 {
+                    let unmentioned_field = unmentioned_fields[0].1.name;
+                    err.span_suggestion(
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/pat.rs:1474]: One small change so that w e don't mention the field name twice in a row:
```suggestion
                    err.span_suggestion_short(
```

After that, r=me.

**Review by estebank — APPROVED** [review]

File: src/test/ui/issues/issue-51102.stderr (hunk 4 above)
[the remark this answers is not in the document]
Comment (hkmatsumoto) [reply src/test/ui/issues/issue-51102.stderr]: Got it, I'll make a follow-up PR later.

File: compiler/rustc_typeck/src/check/pat.rs (hunk 5 above)
Comment (hkmatsumoto) [reply compiler/rustc_typeck/src/check/pat.rs]: Applied :+1: I don't have the bors permission so please do it instead of me.

**Comment by estebank** [comment]
Please squash your commits. Then we can merge this :)

File: src/test/ui/issues/issue-51102.stderr (hunk 4 above)
[the remark this answers is not in the document]
Comment (hkmatsumoto) [reply src/test/ui/issues/issue-51102.stderr]: Opened.
