### PR TITLE
rustdoc: Improve playground run buttons

### LINKED ISSUE #36621: rustdoc: Renders Run button even if playpen is not enabled
rustdoc renders the **Run** button even if playpen is not enabled now. Clicking the button has no useful effect.

Was this caused by #36334 ?

### LINKED ISSUE #36910: 'Run' button on the nightly error index doesn't open playground
In the [compiler error index](https://doc.rust-lang.org/nightly/error-index.html), like in other parts of the documentation, it is possible to click a 'Run' button to open a playground containing the code from a `<code>` block. Unlike in other parts of the documentation, this does not work, and opens the same page in a new tab instead.

The issue in the page's HTML is that the `href` attribute of the `a` element that shows the button is blank:

`<a class="test-arrow" target="_blank" href="">Run</a>`.

In other parts of the documentation (e.g. [the rust reference](https://doc.rust-lang.org/nightly/reference.html)), this is not the case:

`<a class="test-arrow" target="_blank" href="https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20let%20a%20%3D%20%22foobar%22%3B%0Alet%20b%20%3D%20%22foo%5C%0A%20%20%20%20%20%20%20%20%20bar%22%3B%0A%0Aassert_eq!(a%2Cb)%3B%0A%7D">Run</a>`.

This is likely an issue in the HTML generation, but I have not pinned down where exactly the generation goes wrong.

### PR DESCRIPTION
**Pull request by ollie27**
The main change is to stop using javascript to generate the URLs and use
rustdoc instead.

This also adds run buttons to the error index examples.

You can test the changes at https://ollie27.github.io/rust_doc_test/.

Fixes #36621
Fixes #36910

### CODE REVIEW

File: src/librustdoc/html/markdown.rs [hunk 1]
```diff
@@ -248,24 +250,53 @@ pub fn render(w: &mut fmt::Formatter, s: &str, print_toc: bool) -> fmt::Result {
...
                     let test = test::maketest(&test, krate, false,
                                               &Default::default());
-                    s.push_str(&format!("<span class='rusttest'>{}</span>", Escape(&test)));
+                    let channel = if test.contains("#![feature(") {
+                        "&amp;version=nightly"
+                    } else {
+                        ""
+                    };
+                    // These characters don't need to be escaped in a URI.
+                    // FIXME: use a library function for percent encoding.
```
Comment (steveklabnik) [inline src/librustdoc/html/markdown.rs]: hmmmmmm yeah

**Comment by steveklabnik** [comment]
Neat! I think this is a noble goal overall.

@alexcrichton @GuillaumeGomez what do you think?

/cc @rust-lang/tools as well.

**Comment by alexcrichton** [comment]
👍

**Comment by GuillaumeGomez** [comment]
I have shared feelings: on one side, it removes javascript and watchers, which is super nice. On the other side, we add more data into our docs. So I'm mostly in favor for this change.

**Comment by GuillaumeGomez** [comment]
After consensus, let's merge it!

Thanks a lot for this!

@bors: r+

**Comment by ollie27** [comment]
Rebased.
