### PR TITLE
typeck: suggest use of match_default_bindings feature

### LINKED ISSUE #45383: suggest use of the `match_default_bindings` feature gate
Right now, if the `match_default_bindings` is not enabled, then [type check does not even **attempt** to auto-deref on pattern match](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/_match.rs#L71). This makes it rather undiscoverable. If I try to run this program, for example:

```rust
fn foo(x: &Option<i32>) {
  if let Some(y) = x {
    println!("{}", y);
  }
}

fn main() {
  foo(&Some(22));
}
```

I get:

```
Standard Error

   Compiling playground v0.0.1 (file:///playground)
error[E0308]: mismatched types
 --> src/main.rs:2:10
  |
2 |   if let Some(y) = x {
  |          ^^^^^^^ expected reference, found enum `std::option::Option`
  |
  = note: expected type `&std::option::Option<i32>`
             found type `std::option::Option<_>`
```

Of course, [if I add the feature gate, it works](https://play.rust-lang.org/?gist=60cc8d1a9e23d0a3f4c705153a288c82&version=nightly).

What I would like is for some kind of **hint** that the feature gate is available, at least on nightly builds. As an example, if I [use slice patterns (also unstable) on nightly](https://play.rust-lang.org/?gist=66fee3f2744bdc380180a8995565d9de&version=nightly), I get:

```
error: slice pattern syntax is experimental (see issue #23121)
 --> src/main.rs:2:7
  |
2 |   let [x, y] = [1, 2];
  |       ^^^^^^
  = help: add #![feature(slice_patterns)] to the crate attributes to enable
```

(On stable, the help is not present.) This error results from [this code here](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L1501-L1503) which invokes the [`gate_features_post!` macro](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L1165-L1178). I'm not 100% sure what error message we should use here, but I think we should do something similar.

Roughly speaking, the idea would be this: 

- Remove the feature check for `tcx.sess.features.borrow().match_default_bindings` from [this line](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/_match.rs#L71) and instead enter the `if` the same either way.
- Instead, we can do the feature check only [once we actually decide to insert match default bindings](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/_match.rs#L117-L119) -- this code only runs for patterns that would result in an error without the feature-gate enabled anyhow.
- In that branch, if the feature-gate is disabled, we can invoke [the `feature_err` function](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L1074-L1077) to create an error to emit. 
    - Perhaps we should a help or suggestion like, "to make this code work without the feature gate, consider using an `&`-pattern here".

The final error would thus look something like:

```
error: matching a value of reference type with a non-reference pattern is unstable
 --> src/main.rs:2:10
  |
2 |   if let Some(y) = x {
  |          ^^^^^^^ `&`-pattern required: `&Some(y)`
  |
  = help: add `#![feature(match_default_bindings)]` to the crate attributes to enable
```

This error is...a bit funky. We might want to play with the wording. Maybe it wants to be something like:

```
error[Ε0123]: non-reference pattern used to match a reference
 --> src/main.rs:2:10
  |
2 |   if let Some(y) = x {
  |          ^^^^^^^ `&`-pattern required: `&Some(y)`
  |
  = help: you can add `#![feature(match_default_bindings)]` to the crate attributes to enable
```

We could then make an extended error message for E0123 that explains the RFC a bit too.

cc @tschottdorf @estebank

### PR DESCRIPTION
**Pull request by tamird**
Fixes #45383.
Updates #42640.

r? @nikomatsakis
cc @tschottdorf 

This needs a UI test, but thought I'd get some early feedback.

### CODE REVIEW

**Comment by tamird** [comment]
OK, this should be in a reasonable state now - I had to do some additional juggling to prevent halfway-massaging in the case of the feature not being enabled.

File: src/librustc_typeck/check/_match.rs [hunk 1]
```diff
@@ -109,20 +113,41 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                        "match_default_bindings",
+                        pat.span,
+                        feature_gate::GateIssue::Language,
+                        "non-reference pattern used to match a reference",
+                    );
+                    if let Ok(snippet) = tcx.sess.codemap().span_to_snippet(pat.span) {
+                        err.span_suggestion(pat.span, "consider using", format!("&{}", &snippet));
+                    }
+                    err.emit();
+                    None
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/_match.rs]: Hmm, it seems like it may be better to just update `expected` and `def_bm` either way -- i.e., if the feature gate is not enabled, we type-check *as if it were*, but issue an error. It'd certainly be less complicated, but it would also suppress the "duplicate-ish" errors we see below (e.g., mismatched types).

File: src/test/compile-fail/keyword-false-as-identifier.rs [hunk 2]
```diff
@@ -9,5 +9,7 @@
 // except according to those terms.
 
 fn main() {
-    let false = "foo"; //~ error: mismatched types
+    let false = "foo";
```
Comment (nikomatsakis) [inline src/test/compile-fail/keyword-false-as-identifier.rs]: let's change this test from `"foo"` to `22` -- I feel like the message about non-reference patterns isn't central to the test.

File: src/test/compile-fail/keyword-self-as-identifier.rs [hunk 3]
```diff
@@ -9,5 +9,7 @@
 // except according to those terms.
 
 fn main() {
-    let Self = "foo"; //~ ERROR cannot find unit struct/variant or constant `Self` in this scope
+    let Self = "foo";
```
Comment (nikomatsakis) [inline src/test/compile-fail/keyword-self-as-identifier.rs]: let's change this test from `"foo"` to `22` -- I feel like the message about non-reference patterns isn't central to the test.

File: src/test/compile-fail/keyword-super-as-identifier.rs [hunk 4]
```diff
@@ -9,5 +9,7 @@
 // except according to those terms.
 
 fn main() {
-    let super = "foo"; //~ ERROR failed to resolve. There are too many initial `super`s
+    let super = "foo";
```
Comment (nikomatsakis) [inline src/test/compile-fail/keyword-super-as-identifier.rs]: let's change this test from `"foo"` to `22` -- I feel like the message about non-reference patterns isn't central to the test.

File: src/test/compile-fail/keyword-true-as-identifier.rs [hunk 5]
```diff
@@ -9,5 +9,7 @@
 // except according to those terms.
 
 fn main() {
-    let true = "foo"; //~ error: mismatched types
+    let true = "foo";
```
Comment (nikomatsakis) [inline src/test/compile-fail/keyword-true-as-identifier.rs]: let's change this test from `"foo"` to `22` -- I feel like the message about non-reference patterns isn't central to the test.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Looks great. I left one suggestion -- let me know what you think.

**Comment by tamird** [comment]
@kennytm should be waiting-on-review again.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@tamird sorry for the delay; I was at the Rust Belt Rust conference. Looks good, thanks!

**Comment by tamird** [comment]
No worries! Can you let me squash it before it merges? I'll be back at my
computer this evening.

**Comment by kennytm** [comment]
@bors r-

(Waiting on author to cleanup.)

**Comment by tamird** [comment]
OK, should be good to go, unless y'all have tweaks for the message.

**Comment by kennytm** [comment]
@bors retry #45230 LLDB segfault at `check x86_64-apple-darwin`

<details>

```
[01:34:24] ---- [debuginfo-lldb] debuginfo/associated-types.rs stdout ----
[01:34:24] 	NOTE: compiletest thinks it is using LLDB version 370
[01:34:24] 
[01:34:24] error: Error while running LLDB
[01:34:24] status: signal: 11
[01:34:24] command: "/usr/bin/python" "/Users/travis/build/rust-lang/rust/src/etc/lldb_batchmode.py" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/associated-types.stage2-x86_64-apple-darwin" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/associated-types.debugger.script"
[01:34:24] stdout:
[01:34:24] ------------------------------------------
[01:34:24] LLDB batch-mode script
[01:34:24] ----------------------
[01:34:24] Debugger commands script is '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/associated-types.debugger.script'.
[01:34:24] Target executable is '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/associated-types.stage2-x86_64-apple-darwin'.
[01:34:24] Current working directory is '/Users/travis/build/rust-lang/rust'
[01:34:24] Creating a target for '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/associated-types.stage2-x86_64-apple-darwin'
[01:34:24] settings set auto-confirm true
[01:34:24] 
[01:34:24] version
[01:34:24] lldb-370.0.42 Swift-3.1 
[01:34:24] command script import /Users/travis/build/rust-lang/rust/./src/etc/lldb_rust_formatters.py
[01:34:24] type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
[01:34:24] type category enable Rust
[01:34:24] 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 110
[01:34:24] Breakpoint 1: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_struct<i32> + 4 at associated-types.rs:110, address = 0x0000000100000764 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 117
[01:34:24] Breakpoint 2: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_local<i32> + 74 at associated-types.rs:117, address = 0x00000001000007fa 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 121
[01:34:24] Breakpoint 3: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_arg<i32> + 12 at associated-types.rs:121, address = 0x000000010000084c 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 129
[01:34:24] Breakpoint 4: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_tuple<i32> + 4 at associated-types.rs:129, address = 0x00000001000008d4 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 136
[01:34:24] Breakpoint 5: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_enum<i32> + 102 at associated-types.rs:136, address = 0x0000000100000976 
[01:34:24] breakpoint set --file 'associated-types.rs' --line 139
[01:34:24] Breakpoint 6: where = associated-types.stage2-x86_64-apple-darwin`associated_types::assoc_enum<i32> + 143 at associated-types.rs:139, address = 0x000000010000099f 
[01:34:24] quit
[01:34:24] 
[01:34:24] 
[01:34:24] ------------------------------------------
[01:34:24] stderr:
[01:34:24] ------------------------------------------
[01:34:24] 
[01:34:24] ------------------------------------------
[01:34:24] 
[01:34:24] thread '[debuginfo-lldb] debuginfo/associated-types.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:2485:8
[01:34:24] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:34:24] 
[01:34:24] 
[01:34:24] failures:
[01:34:24]     [debuginfo-lldb] debuginfo/associated-types.rs
[01:34:24] 
[01:34:24] test result: [31mFAILED(B[m. 97 passed; 1 failed; 10 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by alexcrichton** [comment]
```
test [run-pass] run-pass\rustc-rust-log.rs has been running for over 60 seconds
fatal runtime error: allocator memory exhausted
```

Looks like [this test](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/rustc-rust-log.rs) generated so much log output that it caused `compiletest`, which was collecting output, to OOM.

Unsure if it's caused by this PR (in that maybe it increased the amount of logging?) but it also seems like we may just need to remove the test...

**Comment by alexcrichton** [comment]
@kennytm we may want to watch this test though, I suspect this won't be the first time we see this error. Also the test ran for at least a minute which is a bit much

**Comment by kennytm** [comment]
@alexcrichton Sorry did not see your reply when commenting. @bors r-

This test case has failed before, e.g. https://github.com/rust-lang/rust/pull/44142#issuecomment-325573211 which was legit. Probably this diff caused a lot more logs to appear and failing the test case?

```diff
diff --git a/src/librustc_typeck/check/_match.rs b/src/librustc_typeck/check/_match.rs
index ab8994bcae25..e25f7d796689 100644
--- a/src/librustc_typeck/check/_match.rs
+++ b/src/librustc_typeck/check/_match.rs
@@ -68,7 +69,7 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
             PatKind::Binding(..) |
             PatKind::Ref(..) => false,
         };
-        if is_non_ref_pat && tcx.sess.features.borrow().match_default_bindings {
+        if is_non_ref_pat {
             debug!("pattern is non reference pattern");
             let mut exp_ty = self.resolve_type_vars_with_obligations(&expected);
```

**Comment by nikomatsakis** [comment]
@kennytm I cannot imagine how this change would affect that **particular** test -- it compiles an empty file, so I don't think that this code will trigger at all.

I do think the test is useful, but I wonder if we should consider e.g. directing the log output into `/dev/null` or something so as not to overwhelm compile-test. This could be a compiletest flag, or perhaps we can modify the test to invoke rustc as a subprocess or something.

Regardless, I'm going to r+ again because I don't *think* the problem is related to this patch per se.

**Comment by nikomatsakis** [comment]
Before:

```
lunch-box. RUST_LOG=debug /usr/bin/time -o killme.master rustc rustc-rust-log.rs 2>&1 | wc -c
606664960
lunch-box. cat killme.master
17.36user 8.18system 0:25.55elapsed 99%CPU (0avgtext+0avgdata 107360maxresident)k
32inputs+8488outputs (4major+20279minor)pagefaults 0swaps
```

With this branch:

```
lunch-box. RUST_LOG=debug /usr/bin/time -o killme rustc rustc-rust-log.rs 2>&1 | wc -c
606664960
lunch-box. cat killme
22.50user 8.48system 0:31.05elapsed 99%CPU (0avgtext+0avgdata 108668maxresident)k
0inputs+8488outputs (0major+20557minor)pagefaults 0swaps
```

No real difference. This branch for some reason took an extra few seconds, but it's probably because I was compiling other working directories at the same time or something.

**Comment by kennytm** [comment]
AppVeyor passed 😕 I'm going to record that as a spurious error.
