### PR TITLE
`--explain` disambiguates no long description and invalid error codes

### LINKED ISSUE #44710: `--explain` should disambiguate nonexistent from underdocumented error codes
The `--explain EXXX` functionality (does anyone still uses this now that it's [no longer advertised so hard](https://github.com/rust-lang/rust/commit/fad4f32c3#diff-4d5b8cff35812b800ff77376382671a7L781)?) gives the same "no extended information" message for real error codes that don't have a "long" explanation written, and nonexistent codes. These messages should be disambiguated (as "no extended information for E0XXX" _vs_. "E0XXX does not exist" or similar).

```
$ rustc --explain E0489 # "type/lifetime parameter not in scope here"
error: no extended information for E0489

$ rustc --explain E9999nonexisting
error: no extended information for E9999nonexisting
```

-----

I _thought_ this would be straightforward to implement: we [_do_ keep track of codes without explanations](https://github.com/rust-lang/rust/blob/f60bc3ac/src/libsyntax/diagnostics/plugin.rs#L100) (which get successfully [plumbed through to the error index](https://github.com/rust-lang/rust/blob/f60bc3ac0c20f7b3/src/tools/error_index_generator/main.rs#L104), although the [CSS hides them](https://github.com/rust-lang/rust/blob/f60bc3ac0c20f7b3/src/tools/error_index_generator/main.rs#L68-L69)), only to [throw that information away](https://github.com/rust-lang/rust/blob/f60bc3ac/src/libsyntax/diagnostics/plugin.rs#L198-L199) when macroexpanding the arrays [that ultimately stock the `--explain` functionality](https://github.com/rust-lang/rust/blob/f60bc3ac0c20/src/librustc_driver/lib.rs#L1329-L1342). So this _should_, you would _think_, just be a matter of editing [`expand_build_diagnostic_array`](https://github.com/rust-lang/rust/blob/f60bc3ac/src/libsyntax/diagnostics/plugin.rs#L159) to give us a `[(&str, Option<&str>)]` of code–maybe-explanation pairs instead of a `[(&str, &str)]` of code–explanation pairs, editing [`errors::Registry`](https://github.com/rust-lang/rust/blob/f60bc3ac0c20f7b3ab85df1e5e2e3217a7a95630/src/librustc_errors/registry.rs) reflect that, and making the [driver](https://github.com/rust-lang/rust/blob/f60bc3ac0c20f7b3ab85df1e5e2e3217a7a95630/src/librustc_driver/lib.rs#L489) care.

But when I actually do this (zackmdavis/rust@048dde26e) ... my changes to `expand_build_diagnostic_array` seem to have absolutely no effect (!?!); we still get a `[(&str, &str)]` even though I _thought_ my code pretty clearly said otherwise, on more than one day that I've looked at this. I hereby give up in despair, bafflement, and tears.

This issue has been assigned to @jakevossen5 via [this comment](https://github.com/rust-lang/rust/issues/44710#issuecomment-588446206).

### PR DESCRIPTION
**Pull request by jakevossen5**
Closes #44710

First code contribution here, so feedback is very much appreciated!

cc @zackmdavis 
cc @Mark-Simulacrum

### CODE REVIEW

File: src/librustc_driver/lib.rs [hunk 1]
```diff
@@ -549,9 +549,12 @@ fn handle_explain(registry: Registry, code: &str, output: ErrorOutputType) {
                 print!("{}", text);
             }
         }
-        None => {
+        NoLongDescription => {
             early_error(output, &format!("no extended information for {}", code));
         }
+        InvalidErrorCode => {
+            early_error(output, &format!("{} is not a valid error code ", code));
```
Comment (jakevossen5) [inline src/librustc_driver/lib.rs]: Is this an okay error code?

File: src/librustc_errors/json.rs [hunk 2]
```diff
@@ -417,8 +418,14 @@ impl DiagnosticCode {
...
             };
-            let explanation =
-                je.registry.as_ref().and_then(|registry| registry.find_description(&s));
+            let reg_result =
+                je.registry.as_ref().and_then(|registry| Some(registry.find_description(&s)));
+            let reg_result = reg_result.unwrap();
+
+            let explanation = match reg_result {
+                HasLongDescription(s) => Some(s),
+                _ => None,
```
Comment (jakevossen5) [inline src/librustc_errors/json.rs]: Do we need to rework this struct to also distinguish between non-existent long descriptions and invalid error codes? Currently it is pretty much treating it just as it was before, where a error code will be `Some(s)` and a code not existing / no long description will be `None`

File: src/librustc_errors/lib.rs [hunk 3]
```diff
@@ -786,7 +786,7 @@ impl HandlerInner {
                 .emitted_diagnostic_codes
                 .iter()
                 .filter_map(|x| match &x {
-                    DiagnosticId::Error(s) if registry.find_description(s).is_some() => {
+                    DiagnosticId::Error(s) if registry.find_description(s).has_value() => {
```
Comment (jakevossen5) [inline src/librustc_errors/lib.rs]: Is there a better way to do this here? I tried doing a match but couldn't quite get it to work. Is this okay?

File: src/librustc_errors/registry.rs [hunk 4]
```diff
@@ -1,16 +1,39 @@
+use crate::registry::RegistryResult::HasLongDescription;
 use rustc_data_structures::fx::FxHashMap;
 
+pub enum RegistryResult {
```
Comment (jakevossen5) [inline src/librustc_errors/registry.rs]: Does this `enum` belong here?

File: src/librustc_errors/registry.rs [hunk 5]
```diff
@@ -1,16 +1,39 @@
...
+        Registry { long_descriptions: long_descriptions.iter().cloned().collect() }
     }
 
-    pub fn find_description(&self, code: &str) -> Option<&'static str> {
-        self.descriptions.get(code).cloned()
+    pub fn find_description(&self, code: &str) -> RegistryResult {
+        if !self.long_descriptions.contains_key(code) {
+            return RegistryResult::InvalidErrorCode;
+        }
+        let entry = self.long_descriptions.get(code).unwrap(); // use unwrap here because we checked the key exists already
```
Comment (Centril) [inline src/librustc_errors/registry.rs]: Nit: let's move the comment to it's own line above the statement; getting a bit too long to the right.

File: src/librustc_driver/lib.rs [hunk 6]
```diff
@@ -549,9 +550,12 @@ fn handle_explain(registry: Registry, code: &str, output: ErrorOutputType) {
...
```
Comment (Mark-Simulacrum) [inline src/librustc_driver/lib.rs]:
```suggestion
            early_error(output, &format!("{} is not a valid error code", code));
```

File: src/librustc_error_codes/lib.rs [hunk 7]
```diff
@@ -3,7 +3,7 @@
 
 macro_rules! register_diagnostics {
     ($($ecode:ident: $message:expr,)* ; $($code:ident,)*) => (
-        pub static DIAGNOSTICS: &[(&str, &str)] = &[
+        pub static DIAGNOSTICS: &[(&str, Option<&str>)] = &[
             $( (stringify!($ecode), $message), )*
```
Comment (Mark-Simulacrum) [inline src/librustc_error_codes/lib.rs]: It looks like at some point this macro was updated and we forgot about the $code argument. We should be able to avoid changing every line in error_codes.rs and instead have this be something like the following, I think.

```rust
$( (stringify!($ecode), Some($message)), )*
$( (stringify!($code), None), )*
```

File: src/librustc_driver/lib.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/librustc_driver/lib.rs]: Yes, this is fine.

File: src/librustc_errors/json.rs [hunk 8]
```diff
@@ -417,8 +418,14 @@ impl DiagnosticCode {
                 DiagnosticId::Error(s) => s,
                 DiagnosticId::Lint(s) => s,
             };
-            let explanation =
-                je.registry.as_ref().and_then(|registry| registry.find_description(&s));
+            let reg_result =
+                je.registry.as_ref().and_then(|registry| Some(registry.find_description(&s)));
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/json.rs]: I think this code'll be easier to read if we have an `if let Some(registry) = je.registry { ... }` and avoid the combinators on Option here.

File: src/librustc_errors/json.rs (hunk 2 above)
Comment (Mark-Simulacrum) [reply src/librustc_errors/json.rs]: Ah, we should actually be able to panic or so if there's an invalid error code getting passed in here, that should never happen (if it does in practice we can fix it in this PR).

File: src/librustc_errors/registry.rs [hunk 9]
```diff
@@ -1,16 +1,40 @@
...
 impl Registry {
-    pub fn new(descriptions: &[(&'static str, &'static str)]) -> Registry {
-        Registry { descriptions: descriptions.iter().cloned().collect() }
+    pub fn new(long_descriptions: &[(&'static str, Option<&'static str>)]) -> Registry {
+        Registry { long_descriptions: long_descriptions.iter().cloned().collect() }
     }
 
-    pub fn find_description(&self, code: &str) -> Option<&'static str> {
-        self.descriptions.get(code).cloned()
+    pub fn find_description(&self, code: &str) -> RegistryResult {
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/registry.rs]: Looking at the use sites, it looks like most of the time (well, 2 out of 3?) expect to be passing in a valid code, and we should panic if they don't.

I think we'll want the following API:

```rust

#[derive(Debug)]
struct InvalidErrorCode;

/// This will panic if an invalid error code is passed in
pub fn find_description(&self, code: &str) -> Option<&'static str> {
    self.try_find_description(code).unwrap()
}

pub fn try_find_description(&self, code: &str) -> Result<Option<&'static str>, InvalidErrorCode> {
    // ...
}
```

**Review by Mark-Simulacrum — COMMENTED** [review]
This is looking great!

I've added some comments -- I didn't have time to go back through a second time to make sure they're all consistent, but the latter comments are the "more correct" ones as I gained a better understanding of the code myself.

File: src/librustc_errors/json.rs (hunk 2 above)
Comment (jakevossen5) [reply src/librustc_errors/json.rs]: I don't have a great idea of what this file is doing, what would be a good panic message?

Comment (Mark-Simulacrum) [reply src/librustc_errors/json.rs]: Doesn't matter too much. Just `panic!("unexpected invalid error code {}", code);` would be fine.

**Review by GuillaumeGomez — APPROVED** [review]
Good idea, thanks for doing it!

File: src/librustc_driver/lib.rs [hunk 10]
```diff
@@ -522,35 +522,40 @@ fn stdout_isatty() -> bool {
...
-                if dedented_line.starts_with("```") {
-                    is_in_code_block = !is_in_code_block;
-                    text.push_str(&line[..(indent_level + 3)]);
-                } else if is_in_code_block && dedented_line.starts_with("# ") {
-                    continue;
-                } else {
-                    text.push_str(line);
+    match registry.try_find_description(&normalised) {
+        Ok(registry_result) => {
+            match registry_result {
```
Comment (Mark-Simulacrum) [inline src/librustc_driver/lib.rs]: You can avoid the inner match here by using patterns like `Ok(Some(description))` at the top level, it'll reduce the rightward drift a bit.

File: src/librustc_driver/lib.rs [hunk 11]
```diff
@@ -522,35 +522,40 @@ fn stdout_isatty() -> bool {
...
-
-            if stdout_isatty() {
-                show_content_with_pager(&text);
-            } else {
-                print!("{}", text);
             }
         }
-        None => {
-            early_error(output, &format!("no extended information for {}", code));
+        Err(_) => {
```
Comment (Mark-Simulacrum) [inline src/librustc_driver/lib.rs]: Please use `Err(InvalidErrorCode)` to make it clear we're not losing the error here.

File: src/librustc_errors/json.rs [hunk 12]
```diff
@@ -417,10 +417,16 @@ impl DiagnosticCode {
                 DiagnosticId::Error(s) => s,
                 DiagnosticId::Lint(s) => s,
             };
-            let explanation =
-                je.registry.as_ref().and_then(|registry| registry.find_description(&s));
+            let je_result = je
+                .registry
+                .as_ref()
+                .and_then(|registry| Some(registry.try_find_description(&s)))
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/json.rs]: I believe this is equivalent to a `map` without the inner Some?

File: src/librustc_errors/json.rs [hunk 13]
```diff
@@ -417,10 +417,16 @@ impl DiagnosticCode {
...
+                .unwrap();
+            if je_result.is_ok() {
+                return DiagnosticCode { code: s, explanation: je_result.unwrap() };
+            }
 
-            DiagnosticCode { code: s, explanation }
+            DiagnosticCode { code: s, explanation: None }
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/json.rs]: It looks like we can do `DiagnosticCode { code: s, explanation: je_result.ok() }` here actually.

File: src/librustc_errors/lib.rs [hunk 14]
```diff
@@ -786,7 +786,10 @@ impl HandlerInner {
                 .emitted_diagnostic_codes
                 .iter()
                 .filter_map(|x| match &x {
-                    DiagnosticId::Error(s) if registry.find_description(s).is_some() => {
+                    DiagnosticId::Error(s)
+                        if registry.try_find_description(s).is_ok()
+                            && registry.try_find_description(s).unwrap().is_some() =>
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/lib.rs]: I think we can refactor this to move the try_find_description calls into the right hand side of the match arm, something like this:

```rust
DiagnosticId::Error(s) => {
    if let Ok(Some(explanation)) = registry.try_find_description(s) {
        Some(s.clone())
    } else {
        None
    }
}
```

File: src/librustc_errors/registry.rs [hunk 15]
```diff
@@ -1,16 +1,30 @@
...
+        Registry { long_descriptions: long_descriptions.iter().cloned().collect() }
     }
 
+    /// This will panic if an invalid error code is passed in
     pub fn find_description(&self, code: &str) -> Option<&'static str> {
-        self.descriptions.get(code).cloned()
+        self.try_find_description(code).unwrap()
+    }
+
+    pub fn try_find_description(
```
Comment (Mark-Simulacrum) [inline src/librustc_errors/registry.rs]: Please add some documentation for what the return type here means.

File: src/librustc_driver/lib.rs (hunk 11 above)
Comment (jakevossen5) [reply src/librustc_driver/lib.rs]: When I do this it gets upset that I have an unused variable. I can do something like `Err(_invalid_error_code)`, or should I do something different?

File: src/librustc_driver/lib.rs [hunk 16]
```diff
@@ -542,16 +541,18 @@ fn handle_explain(registry: Registry, code: &str, output: ErrorOutputType) {
...
                 show_content_with_pager(&text);
             } else {
                 print!("{}", text);
             }
         }
-        None => {
+        Ok(None) => {
             early_error(output, &format!("no extended information for {}", code));
         }
+        Err(_invalid_error_code) => {
```
Comment (Mark-Simulacrum) [inline src/librustc_driver/lib.rs]: Sorry, I literally meant the InvalidErrorCode struct from the other file (you may need to import it).

**Comment by Mark-Simulacrum** [comment]
Please also squash all the commits down into one in your next push, and I think this'll be ready to go!

File: src/librustc_driver/lib.rs (hunk 11 above)
Comment (estebank) [reply src/librustc_driver/lib.rs]: You need to import the type from `rustc_errors::registry::InvalidErrorCode`, otherwise this is introducing a binding `InvalidErrorCode` instead of pattern matching against `struct InvalidErrorCode`, which is what @Mark-Simulacrum suggested.

Comment (jakevossen5) [reply src/librustc_driver/lib.rs]: Thank you!

**Comment by estebank** [comment]
@jakevossen5 you will need to rebase on top of a recent master.

**Comment by jakevossen5** [comment]
@estebank  should be fixed now.

**Comment by jakevossen5** [comment]
@estebank should be good now!

**Comment by Mark-Simulacrum** [comment]
Commits need to be squashed into one here it looks like but otherwise this is good to go.

**Comment by jakevossen5** [comment]
@Mark-Simulacrum should be good now, thank you!

**Comment by Mark-Simulacrum** [comment]
@bors r+

Thanks!
