### PR TITLE
Account for `ref` and `mut` in the wrong place for pattern ident renaming

### LINKED ISSUE #72298: Unhelpful message for syntax error in pattern bindings
When changing a pattern binding from something like

```rust
match some_value {
    SomeEnum::SomeVariant { ref some_field } => { /* do something with some_field */ },
    _ => {}
}
```

to something like

```rust
match some_value {
    SomeEnum::SomeVariant { some_field: ref alias } => { /* do something with alias */ },
    _ => {}
}
```

it's easy to end up with

```rust
match some_value {
    SomeEnum::SomeVariant { ref some_field: alias } => { /* do something with alias */ },
    _ => {}
}
```

which yields an unhelpful syntax error message ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=09095874891f43440d7921d06f3cff2b)). I don't believe it's obvious why `ref some_field` and `some_field: alias` are valid, but `ref some_field: alias` is not. The same holds for `ref mut` bindings, of course.

It would be nice if rustc's parser accepted the invalid syntax and provided one of its helpful "did you mean to write `some_field: ref alias`?" error messages.

### PR DESCRIPTION
**Pull request by estebank**
If the user writes `S { ref field: name }` instead of `S { field: ref name }`, we suggest the correct code.

Fix #72298.

### CODE REVIEW

File: compiler/rustc_parse/src/parser/pat.rs [hunk 1]
```diff
@@ -1109,6 +1110,43 @@ impl<'a> Parser<'a> {
...
+    fn recover_misplaced_pattern_modifiers(
+        &self,
+        fields: &ThinVec<PatField>,
+        err: &mut DiagnosticBuilder<'a, ErrorGuaranteed>,
+    ) {
+        if let Some(last) = fields.iter().last()
+            && last.is_shorthand
+            && let PatKind::Ident(binding, ident, None) = last.pat.kind
+            && binding != BindingAnnotation::NONE
+            && self.token == token::Colon
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/pat.rs:1124]:
```suggestion
            && self.token == token::Colon
            // We found `ref mut? ident:`, try to parse a `name,` or `name }`.
```

File: compiler/rustc_parse/src/parser/pat.rs [hunk 2]
```diff
@@ -1109,6 +1110,43 @@ impl<'a> Parser<'a> {
...
+            && self.look_ahead(1, |t| t.is_ident())
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/pat.rs:1125]:
```suggestion
            && let Some(name_span) = self.look_ahead(1, |t| t.is_ident().then(t.span))
```

File: compiler/rustc_parse/src/parser/pat.rs [hunk 3]
```diff
@@ -1109,6 +1110,43 @@ impl<'a> Parser<'a> {
...
+            err.multipart_suggestion(
+                "the pattern modifiers belong after the `:`",
+                vec![
+                    (span, String::new()),
+                    (
+                        self.token
+                            .span
+                            .shrink_to_hi()
+                            .with_hi(self.look_ahead(1, |t| t.span.lo())),
+                        format!(" {snippet}"),
```
Comment (cjgillot) [inline compiler/rustc_parse/src/parser/pat.rs:1142]:
```suggestion
                        name_span.shrink_to_lo(),
                        binding.prefix_str(),
```

File: tests/ui/pattern/incorrect-placement-of-pattern-modifiers.rs [hunk 4]
```diff
@@ -0,0 +1,11 @@
+// run-rustfix
+struct S {
+    field_name: (),
+}
+
+fn main() {
+    match (S {field_name: ()}) {
+        S {ref field_name: _foo} => {} //~ ERROR expected `,`
```
Comment (cjgillot) [inline tests/ui/pattern/incorrect-placement-of-pattern-modifiers.rs:8]: Could you add cases with `ref mut` and `mut`?

File: tests/ui/pattern/incorrect-placement-of-pattern-modifiers.rs [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+    }
+    let _: usize = 3u8; //~ ERROR mismatched types
```
Comment (cjgillot) [inline tests/ui/pattern/incorrect-placement-of-pattern-modifiers.rs:10]:
```suggestion
    // Verify that we recover enough to run typeck.
    let _: usize = 3u8; //~ ERROR mismatched types
```
