### PR TITLE
MGCA: fix type error handling for const array and tuple lowering logic

### LINKED ISSUE #153254: mGCA: Syntactic type mismatch diagnostic can leak `{type error}` for forbidden inferred types `_` in the type of type-level const items
With *syntactic* type mismatch I'm referring to mismatches detected by the pre-normalization check in HIR ty lowering for tuples & non-repeat arrays (as contrasted with the semantic `ConstArgHasType` check used for other expr kinds).

Reproducers:

```rs
#![feature(min_generic_const_args)]
#![expect(incomplete_features)]

type const T0: _ = ();
```

```
error[E0121]: the placeholder `_` is not allowed within types on item signatures for constants
 --> file.rs:4:16
  |
4 | type const T0: _ = ();
  |                ^ not allowed in type signatures

error: expected `{type error}`, found const tuple
 --> file.rs:4:20
  |
4 | type const T0: _ = ();
  |                    ^^
```

```rs
#![feature(min_generic_const_args)]
#![expect(incomplete_features)]

type const T1 = [0];
```

```
error: missing type for `const` item
 --> file.rs:4:14
  |
4 | type const T1 = [0];
  |              ^
  |
help: provide a type for the item
  |
4 | type const T1: <type> = [0];
  |              ++++++++

error: expected `{type error}`, found const array
 --> file.rs:4:17
  |
4 | type const T1 = [0];
  |                 ^^^
```

### PR DESCRIPTION
**Pull request by Human9000-bit**
It's a simple fix; just needed to handle Ty::Error in `lower_const_arg_array` and `lower_const_arg_tup`

Fixes rust-lang/rust#153254

r? @fmease

### CODE REVIEW

File: tests/ui/const-generics/mgca/syntactic-type-mismatch.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+#![feature(min_generic_const_args)]
+#![expect(incomplete_features)]
+
+type const T0: _ = ();
+//~^ ERROR: the placeholder `_` is not allowed within types on item signatures for constants [E0121]
+
+type const T1 = [0];
+//~^ ERROR: missing type for `const` item
+
+fn main() {}
```
Comment (Human9000-bit) [inline tests/ui/const-generics/mgca/syntactic-type-mismatch.rs:13]: are we okay with putting both cases in a single test file?

Comment (fmease) [reply tests/ui/const-generics/mgca/syntactic-type-mismatch.rs:13]: Yes, that's totally fine.

**Review by fmease — APPROVED** [review]
Thanks! @bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/153345/1b7d722f429f09c87b08b757d89c689c6cf7f6e7..ee1d0cfbe6b17fe77e1da569be33ac0ee7916be7)*
