### PR TITLE
Report an error if a lang item has the wrong number of generic arguments

### LINKED ISSUE #83893: ICE: panicked at 'index out of bounds: the len is 1 but the index is 1', compiler/rustc_typeck/src/check/method/mod.rs:318:32
### Code

```Rust
#[lang = "add"]
trait Add<'a, T> {}
fn ice() {
    r + a
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (c755ee4ce 2021-04-04)
binary: rustc
commit-hash: c755ee4ce8cae6ea977d65a0288480940db721d9
commit-date: 2021-04-04
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
error[E0425]: cannot find value `r` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:4:5
  |
4 |     r + a
  |     ^ not found in this scope

error[E0425]: cannot find value `a` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:4:9
  |
4 |     r + a
  |         ^ not found in this scope

error[E0658]: language items are subject to change
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | #[lang = "add"]
  | ^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(lang_items)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / #[lang = "add"]
2 | | trait Add<'a, T> {}
3 | | fn ice() {
4 | |     r + a
5 | | }
  | |_^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

error[E0152]: found duplicate lang item `add`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:2:1
  |
2 | trait Add<'a, T> {}
  | ^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `core` (which `std` depends on)
  = note: first definition in `core` loaded from /home/cnsun/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-166dae07beec0398.rlib
  = note: second definition in the local crate (`perses_node_priority_with_dfs_delta_reduced_mutant`)

thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', compiler/rustc_typeck/src/check/method/mod.rs:318:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (c755ee4ce 2021-04-04) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `ice`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0152, E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0152`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0425]: cannot find value `r` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:4:5
  |
4 |     r + a
  |     ^ not found in this scope

error[E0425]: cannot find value `a` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:4:9
  |
4 |     r + a
  |         ^ not found in this scope

error[E0658]: language items are subject to change
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | #[lang = "add"]
  | ^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(lang_items)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / #[lang = "add"]
2 | | trait Add<'a, T> {}
3 | | fn ice() {
4 | |     r + a
5 | | }
  | |_^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

error[E0152]: found duplicate lang item `add`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:2:1
  |
2 | trait Add<'a, T> {}
  | ^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `core` (which `std` depends on)
  = note: first definition in `core` loaded from /home/cnsun/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-166dae07beec0398.rlib
  = note: second definition in the local crate (`perses_node_priority_with_dfs_delta_reduced_mutant`)

thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', compiler/rustc_typeck/src/check/method/mod.rs:318:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/panicking.rs:69:5
   3: rustc_middle::ty::subst::<impl rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>>::fill_item
   4: rustc_middle::ty::subst::<impl rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>>::for_item
   5: rustc_typeck::check::method::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::lookup_method_in_trait
   6: rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::lookup_op_method
   7: rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_overloaded_binop
   8: rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_binop
   9: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  10: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  11: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  12: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  13: rustc_typeck::check::check::check_fn
  14: rustc_infer::infer::InferCtxtBuilder::enter
  15: rustc_typeck::check::typeck
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::force_query_with_job
  19: rustc_query_system::query::plumbing::get_query_impl
  20: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  21: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  22: rustc_typeck::check::typeck_item_bodies
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  24: rustc_data_structures::stack::ensure_sufficient_stack
  25: rustc_query_system::query::plumbing::force_query_with_job
  26: rustc_query_system::query::plumbing::get_query_impl
  27: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  28: rustc_session::utils::<impl rustc_session::session::Session>::time
  29: rustc_typeck::check_crate
  30: rustc_interface::passes::analysis
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::force_query_with_job
  34: rustc_query_system::query::plumbing::get_query_impl
  35: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  36: rustc_interface::passes::QueryContext::enter
  37: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  38: rustc_span::with_source_map
  39: rustc_interface::interface::create_compiler_and_run
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (c755ee4ce 2021-04-04) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `ice`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0152, E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0152`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
This pull request fixes #83893. The issue is that the lang item code currently checks whether the lang item has the correct item kind (e.g. a `#[lang="add"]` has to be a trait), but not whether the item has the correct number of generic arguments.

This can lead to an "index out of bounds" ICE when the compiler tries to create more substitutions than there are suitable types available (if the lang item was declared with too many generic arguments).

For instance, here is a reduced ("reduced" in the sense that it does not trigger additional errors) version of the example given in #83893:
```rust
#![feature(lang_items,no_core)]
#![no_core]
#![crate_type="lib"]

#[lang = "sized"]
trait MySized {}

#[lang = "add"]
trait MyAdd<'a, T> {}

fn ice() {
    let r = 5;
    let a = 6;
    r + a
}
```
On current nightly, this immediately causes an ICE without any warnings or errors emitted. With the changes in this PR, however, I get no ICE and two errors:
```
error[E0718]: `add` language item must be applied to a trait with 1 generic argument
 --> pr-ex.rs:8:1
  |
8 | #[lang = "add"]
  | ^^^^^^^^^^^^^^^
9 | trait MyAdd<'a, T> {}
  |            ------- this trait has 2 generic arguments, not 1

error[E0369]: cannot add `{integer}` to `{integer}`
  --> pr-ex.rs:14:7
   |
14 |     r + a
   |     - ^ - {integer}
   |     |
   |     {integer}

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0369, E0718.
For more information about an error, try `rustc --explain E0369`.
```

### CODE REVIEW

File: compiler/rustc_typeck/src/check/place_op.rs [hunk 1]
```diff
@@ -153,6 +153,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        // run into an ICE (#83893). The error is reported where the lang item is
+        // declared.
+        if let Some(trait_did) = imm_tr {
+            let generics = self.tcx.generics_of(trait_did);
+            let expected_num = match op {
+                PlaceOp::Deref => 0,
+                PlaceOp::Index => 1,
+            } + if generics.has_self { 1 } else { 0 };
+            let num_generics = generics.count();
+            if num_generics != expected_num {
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/place_op.rs:167]:
```suggestion
            if generics.count() != expected_num {
```
Same here. Perhaps since this pattern is already found in three places, it would make sense to split this out into a macro?

File: compiler/rustc_passes/src/lang_items.rs [hunk 2]
```diff
@@ -180,6 +181,83 @@ impl LanguageItemCollector<'tcx> {
...
+            | LangItem::BitAndAssign
+            | LangItem::BitOrAssign
+            | LangItem::ShlAssign
+            | LangItem::ShrAssign
+            | LangItem::Index
+            | LangItem::IndexMut => Some(1),
+
+            LangItem::Neg | LangItem::Not | LangItem::Deref | LangItem::DerefMut => Some(0),
+
+            // FIXME: add more cases?
```
Comment (varkor) [inline compiler/rustc_passes/src/lang_items.rs:222]: How difficult would it be to go through all the lang items and check all of them have been accounted for?

**Review by varkor — COMMENTED** [review]
Thanks – this is looking pretty good. Just have a couple of comments.

File: compiler/rustc_passes/src/lang_items.rs [hunk 3]
```diff
@@ -100,11 +100,12 @@ impl LanguageItemCollector<'tcx> {
     }
 
     fn collect_item(&mut self, item_index: usize, item_def_id: DefId) {
+        let lang_item = LangItem::from_u32(item_index as u32).unwrap();
```
[the remark this answers is not in the document]
Comment (FabianWolff) [reply compiler/rustc_passes/src/lang_items.rs:103]: I started adding code to the bottom of this function before moving it to `collect_item_extended()`, and this is a leftover of that. I did not think it would hurt to have these two statements outside of the `if`, and so I left them there.

File: compiler/rustc_typeck/src/check/place_op.rs (hunk 1 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/place_op.rs]: Yes, I moved it to a separate function.

File: compiler/rustc_passes/src/lang_items.rs (hunk 2 above)
Comment (FabianWolff) [reply compiler/rustc_passes/src/lang_items.rs]: I've added all the other lang items that are traits now. The code below assumes that it is looking at a trait, so adding the non-trait lang items would be more work, and also less important, because e.g. the `bool` lang item is an `impl`, and writing `impl<T> bool<T> { ... }` already gives you an error from elsewhere in the compiler.

File: compiler/rustc_passes/src/lang_items.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (varkor) [reply compiler/rustc_passes/src/lang_items.rs:103]: Generally, it's better to declare variables only where they're needed. This helps for readability and reduces unnecessary computation.

File: compiler/rustc_typeck/src/check/mod.rs [hunk 4]
```diff
@@ -1190,3 +1190,17 @@ fn fatally_break_rust(sess: &Session) {
...
+    tcx: TyCtxt<'tcx>,
+    trait_did: Option<DefId>,
+    mut expected: usize,
+) -> bool {
+    trait_did.map_or(true, |trait_did| {
+        let generics = tcx.generics_of(trait_did);
+        if generics.has_self {
+            expected += 1;
+        }
+        generics.count() == expected
```
Comment (varkor) [inline compiler/rustc_typeck/src/check/mod.rs:1204]:
```suggestion
        generics.count() == expected + if generics.has_self { 1 } else { 0 }
```
I think this is slightly clearer than using a mutable variable.

**Review by varkor — COMMENTED** [review]
If you could revert the change in `collect_item` and address the comment in `has_expected_num_generic_args`, I think this is good to go.

**Comment by FabianWolff** [comment]
> If you could revert the change in `collect_item` and address the comment in `has_expected_num_generic_args`, I think this is good to go.

Done. Thanks for your suggestions and for taking the time to review this PR!

**Comment by varkor** [comment]
Thanks for fixing this, @FabianWolff!

@bors r+
