### PR TITLE
Point at cause of expectation of `break` value when possible

### LINKED ISSUE #115905: Unhelpful message when not using value from a loop break
### Code

```Rust
loop {
    break Some(1);
}
```

### Current output

```Shell
error[E0308]: mismatched types
  --> src\main.rs:24:15
   |
24 |         break Some(1);
   |               ^^^^^^^ expected `()`, found `Option<{integer}>`
   |
   = note: expected unit type `()`
                   found enum `Option<{integer}>`

error: aborting due to previous error
```

### Desired output

```Shell
loop value is never used so
break expected unit type `()`
              found enum `Option<{integer}>`
```

### Rationale and extra context

It might not be too hard to figure what the issue is in such a simple example as the above, but when you have multiple levels of nesting with complex layered types, this can quickly become a source of frustration as it sends you on a wild chase of misdirection.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When encountering a type error within the value of a `break` statement, climb the HIR tree to identify if the expectation comes from an assignment or a return type (if the loop is the tail expression of a `fn`).

Fix #115905.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 1]
```diff
@@ -527,6 +528,67 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         false
     }
 
+    // When encuontering a E0308 on the value of a `break`, try to point at the reason for the
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:531]:
```suggestion
    // When encountering a type error on the value of a `break`, try to point at the reason for the
```

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
pls fix typo, r=me

**Comment by estebank** [comment]
r? @compiler-errors 

I added another mechanism to check for when the typeck inference comes from other `break` statements.

**Comment by estebank** [comment]
Actually, I'll just open another PR.

@bors r=compiler-errors
