### PR TITLE
Don't require rigid alias's trait to hold

### LINKED ISSUE #177: rocket regression
https://crater-reports.s3.amazonaws.com/pr-133502-1/try%23fa8e241660363f48d64b66b05eea58c93ab828fb/reg/rocket-0.5.1/log.txt

Minimized:

```
use std::future::Future;

pub trait FromData<'r>: Sized {
    fn from_data() -> impl Future<Output = ()> + Send;
}

impl<'r, T: FromData<'r>> FromData<'r> for Option<T> {
    async fn from_data() {
        T::from_data().await;
    }
}
```

### PR DESCRIPTION
**Pull request by compiler-errors**
See test for write-up. TL;DR is that we don't need the trait bound to hold, since we enforce it during WF.

I think this is preferable to introducing (if we even could do so) a more specific hack around coroutine interiors, higher ranked types, etc, since this is just a manifestation of more pervasive issues w/ lifetime erasure in coroutines. This just doesn't manifest in the old solver b/c it doesn't try to prove `T: Trait` holds when rigidly projecting `<T as Trait>::Assoc`.

It's pretty clear that this affects quite a few traits (https://github.com/rust-lang/rust/pull/139763), so I think this needs fixing.

r? lcnr

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/177

### CODE REVIEW

File: tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs [hunk 1]
```diff
@@ -0,0 +1,33 @@
+//@ compile-flags: -Znext-solver
+//@ edition: 2024
+//@ check-pass
+
+// Regression test for <https://github.com/rust-lang/trait-system-refactor-initiative/issues/177>.
+// Coroutines erase all free lifetimes from their interior types. In the future in `from_request`,
+// that means the `'r` lifetime in the type `<T as FromRequest<'r>>::Assoc`, which is in the
+// `dyn Future` type it's awaiting. Normalizing this associated type, with its free lifetimes
+// replaced, means proving `T: FromRequest<'!0>`, which definitely doesn't hold.
```
Comment (compiler-errors) [inline tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs:9]: by "definitely", i mean today. in the future (in order, for example, to fix the 12893892 other issues with async) we ideally will imply that `T: FromRequest<'!0>` holds for the specific erased lifetime we took from the coroutine. Or at least we would imply that `'!0 = 'r`, so the param-env bound applies.

File: tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs [hunk 2]
```diff
@@ -0,0 +1,33 @@
+//@ compile-flags: -Znext-solver
+//@ edition: 2024
+//@ check-pass
+
+// Regression test for <https://github.com/rust-lang/trait-system-refactor-initiative/issues/177>.
+// Coroutines erase all free lifetimes from their interior types. In the future in `from_request`,
+// that means the `'r` lifetime in the type `<T as FromRequest<'r>>::Assoc`, which is in the
+// `dyn Future` type it's awaiting. Normalizing this associated type, with its free lifetimes
```
Comment (lcnr) [inline tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs:8]: wordiong "that means the `'r` lifetime..." what is the `'r` lifetime doing. "Is getting replaced by a higher ranked variable?"

File: tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+// replaced, means proving `T: FromRequest<'!0>`, which definitely doesn't hold.
+
+// proving `T: Trait` holds when `<T as Trait>::Assoc` is rigid is not necessary for soundness,
+// at least not *yet*, and it's not even necessary for diagnostics since we have other special
+// casing for, e.g., AliasRelate goals failing in the BestObligation folder.
+
+// The old solver deals this by not checking that `T: Trait` holds when `<T as Trait>::Assoc` is
```
Comment (lcnr) [inline tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs:15]:
```suggestion
// The old solver avoids this by not checking that `T: Trait` holds when `<T as Trait>::Assoc` is
```
"deals with" makes it seem like we intentionally decided to not check this which seems not quite true to me.

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs [hunk 4]
```diff
@@ -45,7 +45,6 @@ where
                             goal,
                             goal.predicate.alias,
                         );
-                        this.add_goal(GoalSource::AliasWellFormed, goal.with(cx, trait_ref));
```
Comment (lcnr) [inline compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:48]: so what's going on is, `proven_via` is `ParamEnv`, but the actual candidate has unsatisfiable region constraints. We then don't add these region constraints when keeping the alias rigid.

File: tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs [hunk 5]
```diff
@@ -0,0 +1,33 @@
+//@ compile-flags: -Znext-solver
+//@ edition: 2024
+//@ check-pass
```
Comment (lcnr) [inline tests/ui/traits/next-solver/coroutine-higher-ranked-rigid.rs:3]: to my knowledge there was no existing ui test for this.

Please move this test to ui/generators or what not and also enable it for the old solver.

File: compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs (hunk 4 above)
Comment (compiler-errors) [reply compiler/rustc_next_trait_solver/src/solve/normalizes_to/mod.rs:48]: Correct
