### PR TITLE
Enhance UI test output handling for runtime errors

### LINKED ISSUE #141531: UI tests that execute don't include the stdout/err of the executed program in the error message if they fail
If the test executes, we get a new `ProcRes` from executing the test and we call `get_output` on that to get the output to pass into `check_all_error_patterns`.

https://github.com/rust-lang/rust/blob/3d86494a0d0131c32eb15e3a4b685707b9ff000d/src/tools/compiletest/src/runtest/ui.rs#L130

We continue to pass in the old `ProcRes` though, so if the test fails, we don't actually print the output we failed to match against. This makes these rather annoying to debug.

### PR DESCRIPTION
**Pull request by AMS21**
When a UI test runs a compiled binary and an error/forbid pattern check fails, the failure message previously only showed compiler output, hiding the executed programs stdout/stderr. This makes it harder to see near-miss or unexpected runtime lines.

Fixed rust-lang/rust#141531
Supersedes rust-lang/rust#141977

### CODE REVIEW

**Comment by Kobzol** [comment]
Makes sense to me. It would be nicer to return a tuple `(String, ProcRes)` from the if condition, but that would require cloning a `ProcRes` for all non-executed UI tests, which could add up a bit.

I'll let @jieyouxu leave comments, since you reviewed the previous variant of this PR.

**Comment by AMS21** [comment]
> Makes sense to me. It would be nicer to return a tuple `(String, ProcRes)` from the if condition, but that would require cloning a `ProcRes` for all non-executed UI tests, which could add up a bit.

Yes, avoiding the clone was the exact reason I implemented it this way.

File: src/tools/compiletest/src/runtest/ui.rs [hunk 1]
```diff
@@ -127,6 +128,9 @@ impl TestCx<'_> {
             );
         }
 
+        // If the test is executed, capture its ProcRes separately so that
+        // pattern/forbid checks can report the *runtime* stdout/stderr when they fail.
+        let mut run_proc_res_opt: Option<ProcRes> = None;
```
Comment (jieyouxu) [inline src/tools/compiletest/src/runtest/ui.rs]: Nit: can you just call this `run_proc_res`

**Review by jieyouxu — APPROVED** [review]
Seems fine, thanks. Just a tiny naming nit
