### PR TITLE
Skip linking if it is not required

### LINKED ISSUE #81117: Cannot emit `metadata,obj` without `link`
Requesting both `metadata` and `obj` without `link` fails:

    $ echo | rustc --crate-type rlib --emit=metadata,obj -

The output files are created, but the compiler thinks it still has to build the archive:

    error: failed to build archive: No such file or directory

The same behavior happens for other metadata + non-link combinations.

### Meta

Both latest stable (1.49.0) and nightly exhibit the problem.

### PR DESCRIPTION
**Pull request by ojeda**
This allows to use `--emit=metadata,obj` and other metadata + non-link combinations.

Fixes #81117.

### CODE REVIEW

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -403,6 +403,14 @@ impl OutputTypes {
             OutputType::Metadata | OutputType::DepInfo => false,
         })
     }
+
+    // Returns `true` if any of the output types require linking.
+    pub fn should_link(&self) -> bool {
+        self.0.keys().any(|k| match *k {
+            OutputType::Exe => true,
+            _ => false,
```
Comment (nagisa) [inline compiler/rustc_session/src/config.rs:411]: Please match exhaustively to ensure this function gets looked at if `OutputType` enum is expanded in the future.

**Comment by ojeda** [comment]
The added `should_link()` looked like the right local fix, but someone with more knowledge around other `should_codegen()` callers should probably take a look.

File: compiler/rustc_session/src/config.rs (hunk 1 above)
Comment (ojeda) [reply compiler/rustc_session/src/config.rs]: Done.

**Comment by nagisa** [comment]
This seems reasonable enough. Thank you!

@bors r+

**Comment by ojeda** [comment]
Thanks to you! That was a quick review. :)

Fixed the formatting.
