### PR TITLE
Disallow Self in type param defaults of ADTs

### LINKED ISSUE #61631: Self as default type isnt typechecked
The following code compiles:
```Rust
struct B<P: Sized = [Self]>(P);
```
but shouldn't, because `[Self]` is NOT Sized.

If we change `[Self]` with a `[u8]`, like this:
```Rust
struct B<P: Sized = [u8]>(P);
```
it fails to compile, because `[u8]` isnt sized.

Also note that if we would write `impl B {}` in the case of P being of default type `[Self]`, we get an ICE:

Related to https://github.com/rust-lang/rust/issues/59956#issuecomment-482946649

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #61631 

(also includes a drive-by fix to a typo in some related diagnostic output.)

### CODE REVIEW

**Comment by pnkfelix** [comment]
cc @alexreg

File: src/librustc_resolve/diagnostics.rs [hunk 1]
```diff
@@ -354,6 +354,13 @@ impl<'a> Resolver<'a> {
                     span, "defaulted type parameters cannot be forward declared".to_string());
                 err
             }
+            ResolutionError::SelfInTyParamDefault => {
+                let mut err = struct_span_err!(self.session, span, E0734,
```
Comment (Centril) [inline src/librustc_resolve/diagnostics.rs]: Formatting should be as in the arm below.

File: src/librustc_resolve/error_codes.rs [hunk 2]
```diff
@@ -1660,6 +1660,20 @@ fn const_id<T, const N: T>() -> T { // error: const parameter
 }
 ```
 "##,
+
+E0734: r##"
+Type parameter defaults cannot use `Self` on structs, enums, or unions.
+Erroneous code example:
+
+```compile_fail,E0734
+struct Foo<X=Box<Self>> {
```
Comment (Centril) [inline src/librustc_resolve/error_codes.rs]:
```suggestion
struct Foo<X = Box<Self>> {
```

File: src/librustc_resolve/error_codes.rs [hunk 3]
```diff
@@ -1660,6 +1660,20 @@ fn const_id<T, const N: T>() -> T { // error: const parameter
...
+    field1: Option<X>,
+    field2: Option<X>,
+}
+// error: type parameters cannot use Self in their defaults.
```
Comment (Centril) [inline src/librustc_resolve/error_codes.rs]:
```suggestion
// error: type parameters cannot use `Self` in their defaults.
```

File: src/librustc_resolve/late.rs [hunk 4]
```diff
@@ -468,6 +468,18 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
             }));
 
+        // rust-lang/rust#61631: The type `Self` is essentially
+        // another type parameter. For ADT's, we consider it
+        // well-defined only after all of the ADT type parameters have
+        // been provided. Therefore, we do not allow use of `Self`
+        // anywhere in type parameter defaults of ADT's.
+        //
+        // (We however cannot ban `Self` for defaults on *any* generic
+        // list; e.g. trait generics can usefully refer to `Self`)
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: An example would be good here.

File: src/librustc_resolve/late.rs [hunk 5]
```diff
@@ -468,6 +468,18 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+        if self.current_self_item.is_some() { // (this is Some if only if within ADT's generics.
```
Comment (Centril) [inline src/librustc_resolve/late.rs]:
```suggestion
        if self.current_self_item.is_some() { // (this is `Some` if only if within ADT's generics.
```

File: src/librustc_resolve/lib.rs [hunk 6]
```diff
@@ -214,6 +214,8 @@ enum ResolutionError<'a> {
     BindingShadowsSomethingUnacceptable(&'a str, Name, &'a NameBinding<'a>),
     /// Error E0128: type parameters with a default cannot use forward-declared identifiers.
     ForwardDeclaredTyParam, // FIXME(const_generics:defaults)
+    /// Error E0734: type parameters with a default cannot use Self
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
    /// Error E0734: type parameters with a default cannot use `Self`
```

File: src/librustc_resolve/lib.rs [hunk 7]
```diff
@@ -2128,7 +2131,11 @@ impl<'a> Resolver<'a> {
         // An invalid forward use of a type parameter from a previous default.
         if let ForwardTyParamBanRibKind = all_ribs[rib_index].kind {
             if record_used {
-                self.report_error(span, ResolutionError::ForwardDeclaredTyParam);
+                if rib_ident.name == kw::SelfUpper {
```
Comment (Centril) [inline src/librustc_resolve/lib.rs]:
```suggestion
                let res_error = match rib_ident.name {
```
(I'd move out the call to `self.report_error`)

File: src/librustc_resolve/diagnostics.rs (hunk 1 above)
Comment (pnkfelix) [reply src/librustc_resolve/diagnostics.rs]: The formatting does match that of the arm *above*, which is the closest analogy in terms of the intent here (since the use of a `Self` param is semantically like a use of a forward-declaration.)

Nonetheless, I will reindent the new arm.

File: src/librustc_resolve/error_codes.rs (hunk 2 above)
Comment (pnkfelix) [reply src/librustc_resolve/error_codes.rs]: Okay, I'll change the other diagnostic in the file that uses type parameter defaults to use this formatting too, for consistency.

Comment (Centril) [reply src/librustc_resolve/error_codes.rs]: Excellent, thanks. =)

File: src/librustc_resolve/late.rs (hunk 4 above)
Comment (pnkfelix) [reply src/librustc_resolve/late.rs]: Yes you're right; I put an example in the relevant unit test (issue-61631-default-type-param-can-reference-self-in-trat.rs), but it would be useful here as well.

File: src/librustc_resolve/error_codes.rs [hunk 8]
```diff
@@ -10,7 +10,7 @@ Erroneous code example:
 ```compile_fail,E0128
 struct Foo<T=U, U=()> {
     field1: T,
-    filed2: U,
+    field2: U,
```
Comment (GuillaumeGomez) [inline src/librustc_resolve/error_codes.rs]: :+1:

File: src/librustc_resolve/error_codes.rs [hunk 9]
```diff
@@ -1660,6 +1660,20 @@ fn const_id<T, const N: T>() -> T { // error: const parameter
 }
 ```
 "##,
+
+E0734: r##"
```
Comment (GuillaumeGomez) [inline src/librustc_resolve/error_codes.rs]: You'll have to make it E0735, I created E0734 just a few days ago.

File: src/librustc_resolve/error_codes.rs [hunk 10]
```diff
@@ -1660,6 +1660,20 @@ fn const_id<T, const N: T>() -> T { // error: const parameter
...
+Type parameter defaults cannot use `Self` on structs, enums, or unions.
+Erroneous code example:
```
Comment (GuillaumeGomez) [inline src/librustc_resolve/error_codes.rs]: Please add an empty line before this one.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]
Thanks a lot for writing the long error explanation when creating a new error code! Just a few minor changes and it should be good to go for me.

File: src/librustc_resolve/error_codes.rs (hunk 9 above)
Comment (pnkfelix) [reply src/librustc_resolve/error_codes.rs]: thanks for the heads up

File: src/librustc_resolve/error_codes.rs (hunk 10 above)
Comment (pnkfelix) [reply src/librustc_resolve/error_codes.rs]: done, thanks!

**Comment by pnkfelix** [comment]
> Thanks a lot for writing the long error explanation when creating a new error code! 

/me squints at [their code](https://github.com/rust-lang/rust/pull/64842/files#diff-973c6c11f20e70e3770d90417accd499R1665)

I cannot tell if you're being sarcastic with your use of the word "long". . .but I'll take your thanks as genuine! No problem, happy to get my feet wet with diagnostics again!

**Comment by GuillaumeGomez** [comment]
No no, it's how we call them: long error explanations. No sarcasm here: I'm really happy about this PR!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
About the long error explanation: generally we appreciate to have an example on how to fix it, but I'm not sure it can be applied here so I approved the PR. :)

**Comment by Centril** [comment]
cc also @petrochenkov

File: src/librustc_resolve/late.rs [hunk 11]
```diff
@@ -468,6 +468,19 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
                 }
             }));
 
+        // rust-lang/rust#61631: The type `Self` is essentially
+        // another type parameter. For ADT's, we consider it
```
Comment (varkor) [inline src/librustc_resolve/late.rs]:
```suggestion
        // another type parameter. For ADTs, we consider it
```

File: src/librustc_resolve/late.rs [hunk 12]
```diff
@@ -468,6 +468,19 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+        // well-defined only after all of the ADT type parameters have
+        // been provided. Therefore, we do not allow use of `Self`
+        // anywhere in type parameter defaults of ADT's.
```
Comment (varkor) [inline src/librustc_resolve/late.rs]:
```suggestion
        // anywhere in ADT type parameter defaults.
```

File: src/librustc_resolve/late.rs [hunk 13]
```diff
@@ -468,6 +468,19 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+        //
+        // (We however cannot ban `Self` for defaults on *all* generic
+        // lists; e.g. trait generics can usefully refer to `Self`,
+        // such as in the case of `trait Add<Rhs = Self>`)
```
Comment (varkor) [inline src/librustc_resolve/late.rs]:
```suggestion
        // such as in the case of `trait Add<Rhs = Self>`.)
```

File: src/librustc_resolve/late.rs [hunk 14]
```diff
@@ -468,6 +468,19 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+        if self.current_self_item.is_some() { // (is `Some` if and only if within ADT's generics.
```
Comment (varkor) [inline src/librustc_resolve/late.rs]:
```suggestion
        if self.current_self_item.is_some() { // (`Some` if and only if we are within an ADT's generics.)
```

File: src/librustc_resolve/diagnostics.rs [hunk 15]
```diff
@@ -354,6 +354,17 @@ impl<'a> Resolver<'a> {
                     span, "defaulted type parameters cannot be forward declared".to_string());
                 err
             }
+            ResolutionError::SelfInTyParamDefault => {
+                let mut err = struct_span_err!(
+                    self.session,
+                    span,
+                    E0735,
+                    "type parameters with a default cannot use `Self`"
```
Comment (varkor) [inline src/librustc_resolve/diagnostics.rs]: I prefer the wording in the documentation.
```suggestion
                    "type parameters cannot use `Self` in their defaults"
```

File: src/librustc_resolve/diagnostics.rs [hunk 16]
```diff
@@ -354,6 +354,17 @@ impl<'a> Resolver<'a> {
...
+                );
+                err.span_label(
+                    span, "defaulted type parameters cannot use `Self`".to_string());
```
Comment (varkor) [inline src/librustc_resolve/diagnostics.rs]:
```suggestion
                    span, "`Self` in type parameter default".to_string());
```
I think this is clearer.

**Review by varkor — CHANGES_REQUESTED** [review]
Implementation looks good; I just have some wording suggestions.

**Comment by alexreg** [comment]
Looks good to me, thanks for tackling this!

I agree with @varkor's stylistic/wording "nits" too, for that matter. Modulo that, LGTM?

File: src/librustc_resolve/late.rs (hunk 14 above)
Comment (pnkfelix) [reply src/librustc_resolve/late.rs]: (this might break tidy. we will see.)

File: src/librustc_resolve/late.rs [hunk 17]
```diff
@@ -468,6 +468,19 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
                 }
             }));
 
+        // rust-lang/rust#61631: The type `Self` is essentially
+        // another type parameter. For ADTs, we consider it
+        // well-defined only after all of the ADT type parameters have
+        // been provided. Therefore, we do not allow use of `Self`
```
Comment (eddyb) [inline src/librustc_resolve/late.rs]: I disagree with the phrasing (although the conclusion is similar) - see https://github.com/rust-lang/rust/issues/61631#issuecomment-538346412

In short, `Self` expands to/aliases `Adt<A, B, C, ...>`, referring to *all* the ADTs' parameters, and we shouldn't allow writing `Self` where we wouldn't allow `Adt<A, B, C, ...>`.
