### PR TITLE
[7/n] rustc: desugar UFCS in HIR and don't use DefMap for associated resolutions.

### LINKED ISSUE #35870: Using impl trait across crates results in linker error
I have a small test case that doesn't work in its current state (split into two crates), producing a linker error; but works when everything is moved into one crate: https://github.com/jplatte/rust-impl-trait-across-crates

Error:

```
   Compiling bin v0.1.0 (file:///home/jplatte/Projekte/rust-impl-trait-across-crates/bin)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/jplatte/Projekte/rust-impl-trait-across-crates/bin/target/debug/bin.0.o" "-o" "/home/jplatte/Projekte/rust-impl-trait-across-crates/bin/target/debug/bin" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/jplatte/Projekte/rust-impl-trait-across-crates/bin/target/debug/deps" "-L" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/jplatte/Projekte/rust-impl-trait-across-crates/bin/target/debug/deps/liblib.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-411f48d3.rlib" "/home/jplatte/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-411f48d3.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
  = note: /home/jplatte/Projekte/rust-impl-trait-across-crates/bin/target/debug/bin.0.o: In function `{{inlined-root}}::next<core::slice::Iter<u32>,closure>':
/buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/mod.rs:953: undefined reference to `lib::Thing::even_elems::_$u7b$$u7b$closure$u7d$$u7d$::h337a400b104ae277'
collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `bin`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by eddyb**
_This is part of a series ([prev](https://github.com/rust-lang/rust/pull/37412) | [next](https://github.com/rust-lang/rust/pull/37688)) of patches designed to rework rustc into an out-of-order on-demand pipeline model for both better feature support (e.g. [MIR-based](https://github.com/solson/miri) early constant evaluation) and incremental execution of compiler passes (e.g. type-checking), with beneficial consequences to IDE support as well.
If any motivation is unclear, please ask for additional PR description clarifications or code comments._

<hr>

Previously, a path like `T::Assoc::method`, while equivalent to `<<T>::Assoc>::method`, wasn't desugared in any way at the HIR level and everything inspecting it had to either deal with knowing only `T` (before typeck) or knowing only the definition of `method` (after typeck).
Such a path also had only one `NodeId` and associated resolution during typeck modified `DefMap`, in a way that would be hard for incremental recompilation to track, and inconvenient for partial type conversions from HIR to `Ty`, which are required to break faux-cycles in on-demand type collection.

The desugarings performed by this PR are as follows:
* `use a::{b,c};` is flattened to `use a as _; use a::b; use a::c;`
  * as resolution is complete, `use a as _;` doesn't do anything, except get checked for stability
* `Vec::new` (an expression) becomes `Vec<..>::new<..>`, to distinguish it from `<Vec>::new<..>`
  * the "infer all parameters" `<..>` form is internal and not even pretty-printed
  * used when there are no type parameters at all, in an expression or pattern path segment
* `T::A::B` becomes `<<T>::A>::B` in a type, and `<<T<..>>::A<..>>::B<..>` in an expression/pattern
  * one additional `hir::Ty` node is created for each prefix, starting with the fully-resolved type (`T`) and extending it with each segment (e.g. `<T>::A`)
* fully-resolved paths contain their `Def` in HIR, getting rid of the `DefMap` and absolving incremental recompilation of needing to manually look up nodes to handle that side information

Not keeping the `DefMap` around meant that associated resolutions had to be stored somewhere else:
* expressions and patterns use a new `NodeId -> Def` map in `ty::Tables`
  * compatible with the future per-body (constant / `fn` / closure) `Tables`
* types are accessible via `Ty` and the usual per-item generics / predicates / type
  * `rustdoc` and `save-analysis` are the only situations which insist on mapping syntactical types to semantical ones, or at least understand the resolution of associated types, therefore the type conversion cache, i.e. a `NodeId -> Ty` map, is exposed by typeck for this purpose
  * stability had to be split into a pass that runs on HIR and checks the results of name resolution, and impromptu checks triggered by `typeck` for associated paths, methods, fields, etc.
  * privacy using semantic types results in accurate reachability for `impl Trait`, which fixes #35870, and thorough introspection of associated types, which may allow relaxing private-in-public checking on bounds, while keeping the intended ban on projections with private type parameters

cc @petrochenkov

### CODE REVIEW

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/2c11a89cd0223fa0dce035a18f004908) shows no user-facing regressions.

**Comment by petrochenkov** [comment]
(I'll read this on Friday or Saturday.)

File: src/librustc/hir/mod.rs [hunk 1]
```diff
@@ -961,22 +956,24 @@ pub enum Expr_ {
...
-///
-///     <HirVec<T>>::AssociatedItem
-///      ^~~~~    ^
-///      ty       position = 0
+/// Optionally `Self`-qualified value/type path or associated extension.
 #[derive(Clone, PartialEq, Eq, RustcEncodable, RustcDecodable, Hash, Debug)]
-pub struct QSelf {
-    pub ty: P<Ty>,
-    pub position: usize,
+pub enum QPath {
```
Comment (petrochenkov) [inline src/librustc/hir/mod.rs]: Nice, this is exactly what I wanted in https://github.com/eddyb/rust/commit/0a5d332730f4c1abc122026d3a0fe47556001747#commitcomment-19533413

File: src/librustc/hir/pat_util.rs [hunk 2]
```diff
@@ -171,7 +176,7 @@ pub fn necessary_variants(dm: &DefMap, pat: &hir::Pat) -> Vec<DefId> {
     pat.walk(|p| {
         match p.node {
             PatKind::TupleStruct(..) |
-            PatKind::Path(..) |
+            PatKind::Path(hir::QPath::Regular(..)) |
```
Comment (petrochenkov) [inline src/librustc/hir/pat_util.rs]: Unnecessary condition now + incompatible with "associated variants" (https://github.com/rust-lang/rust/issues/26264#issuecomment-250603946).

File: src/librustc/middle/effect.rs [hunk 3]
```diff
@@ -186,7 +186,7 @@ impl<'a, 'tcx, 'v> Visitor<'v> for EffectCheckVisitor<'a, 'tcx> {
             hir::ExprInlineAsm(..) => {
                 self.require_unsafe(expr.span, "use of inline assembly");
             }
-            hir::ExprPath(..) => {
+            hir::ExprPath(hir::QPath::Regular(..)) => {
```
Comment (petrochenkov) [inline src/librustc/middle/effect.rs]: Nit: `hir::QPath::Regular(..)` is unnecessary, this commit contains several places where path kind is unnecessarily restricted, then `Def` is queried, they probably remained from previous version of this commit.

Nit 2: Unnecessary `..` -> `_` changes here and there.

Comment (eddyb) [inline src/librustc/middle/effect.rs]: Oh, btw, the `Def` being queried is avoided where possible, because of the latter commit where the embedded/queried distinction exists. That's why some places are weird, because that way they stay simple.

Comment (petrochenkov) [inline src/librustc/middle/effect.rs]: I see. I read each commit separately, so some comments may be immediately outdated.

File: src/librustc/hir/map/mod.rs [hunk 4]
```diff
@@ -250,16 +250,8 @@ impl<'ast> Map<'ast> {
...
-                        let def_id = self.local_def_id(item.id);
-                        // NB                          ^~~~~~~
-                        //
-                        // You would expect that `item.id == id`, but this
-                        // is not always the case. In particular, for a
-                        // ViewPath item like `use self::{mem, foo}`, we
-                        // map the ids for `mem` and `foo` to the
-                        // enclosing view path item. This seems mega super
-                        // ultra wrong, but then who am I to judge?
-                        // -nmatsakis
```
Comment (petrochenkov) [inline src/librustc/hir/map/mod.rs]: Lol

File: src/librustc/hir/mod.rs [hunk 5]
```diff
@@ -1497,8 +1468,16 @@ pub enum Item_ {
...
+
+    /// `use foo::bar::baz as quux;`
+    ///
+    /// or just
+    ///
+    /// `use foo::bar::baz;` (with `as baz` implicitly on the right)
+    ItemUse(P<Path>),
+
+    /// `use foo::bar::*;`
+    ItemUseGlob(P<Path>),
```
Comment (petrochenkov) [inline src/librustc/hir/mod.rs]: It'd be simpler to use `ItemUse(P<Path>, bool /* is glob*/)`/`ItemUse(P<Path>, UseKind)`, this distinction is very rarely relevant in HIR and I'd prefer not to see it in every exhaustive match.

**Comment by petrochenkov** [comment]
>since name resolution is complete, use a; doesn't do anything, except get checked for stability

It would be ideal to just remove `use` items from HIR and do stability checking for paths in resolve, this would fix https://github.com/rust-lang/rust/issues/15702 as well.
The only problem is that `use` items are used by rustdoc...

**Comment by eddyb** [comment]
@petrochenkov We could at least remove the degenerate `use a::{};` aka `use a as _;` that way.
Although, if you look at my changes to stability, that doesn't really seem that feasible.
At least I pushed it back further, and maybe we just don't need the same-crate stability index?

**Comment by eddyb** [comment]
@petrochenkov Hang on, couldn't rustdoc use the export map? After all, isn't that what name resolution in dependent crate uses? IMO it's silly to present anything other than what the crate user can observe.

**Comment by petrochenkov** [comment]
@eddyb 
>Hang on, couldn't rustdoc use the export map?

If it's ok to lose globs in documentation, then I'm pretty sure export maps can be used.

File: src/librustc/hir/lowering.rs [hunk 6]
```diff
@@ -298,44 +294,103 @@ impl<'a> LoweringContext<'a> {
...
-                    name: identifier.name,
-                    parameters: self.lower_path_parameters(parameters, param_mode),
-                }
+                self.lower_path_segment(segment, param_mode)
+            }).collect(),
+            span: p.span,
+        });
+
+        // Simple case, either no projections, or only fully-qualified.
+        if resolution.depth == 0 {
```
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: I completely forgot about it, the way things are set up it's not necessary. That is, `Trait::method` is really `Trait<..>::method::<..>` now and you could imagine `<..>` includes `Self.

**Comment by eddyb** [comment]
cc @rust-lang/tools on the `rustdoc` vs `use` items above (not that more is likely to happen here).

File: src/librustc/middle/stability.rs [hunk 7]
```diff
@@ -349,337 +415,171 @@ impl<'a, 'tcx> Index<'tcx> {
...
-            Some(&Stability { ref level, ref feature, .. }) => {
-                self.used_features.insert(feature.clone(), level.clone());
-
+            Some(_) => {
                 // Stable APIs are always ok to call and deprecated APIs are
-                // handled by a lint.
+                // handled by the lint emitting logic above.
             }
             None => {
                 // This is an 'unmarked' API, which should not exist
```
Comment (petrochenkov) [inline src/librustc/middle/stability.rs]: Everything mentioning `unmarked_api` can be removed now and this arm should simply ICE.

**Comment by petrochenkov** [comment]
Marking items hidden under `impl Trait` as `AccessLevel::Reachable` has some implications beyond linkage, for example such items will require stability annotations, and will be reported by missing `Copy` and missing `Debug` lints. It may become annoying if `impl Trait` becomes popular, but it's probably okay for now.

File: src/librustc_privacy/lib.rs [hunk 8]
```diff
@@ -898,190 +898,174 @@ impl<'a, 'tcx, 'v> Visitor<'v> for ObsoleteVisiblePrivateTypesVisitor<'a, 'tcx>
...
+            ty::TyProjection(ref proj) => {
+                if self.required_visibility == ty::Visibility::PrivateExternal {
                     // Conservatively approximate the whole type alias as public without
                     // recursing into its components when determining impl publicity.
                     // For example, `impl <Type as Trait>::Alias {...}` may be a public impl
                     // even if both `Type` and `Trait` are private.
                     // Ideally, associated types should be substituted in the same way as
                     // free type aliases, but this isn't done yet.
-                    return
+                    return false;
```
Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Yeah but we don't do normalization there atm, so there's no concrete type to speak of.
cc @nikomatsakis

File: src/librustc_privacy/lib.rs [hunk 9]
```diff
@@ -898,190 +898,174 @@ impl<'a, 'tcx, 'v> Visitor<'v> for ObsoleteVisiblePrivateTypesVisitor<'a, 'tcx>
...
                 }
-                _ => {}
             }
         }
 
-        intravisit::walk_ty(self, ty);
+        if let ty::TyProjection(ref proj) = ty.sty {
+            // Avoid calling `visit_trait_ref` below on the trait,
+            // as we have already checked the trait itself above.
+            proj.trait_ref.super_visit_with(self)
```
Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Correct, you'd just get double errors without this special-casing.

File: src/librustc_privacy/lib.rs (hunk 8 above)
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: I don't understand the terminology.
Doesn't `ty::TyProjection` automatically mean in all contexts that the type can't be "normalized"/"reduced" to a concrete type before monomorphization?

Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Not at all, the type *always* exists in that form before being normalized. Within a function's body, where inference takes place, normalization is performed on all expression/pattern path types and other types that "come from elsewhere", so they're not observed as often.

Type collection, which handles all the signatures, runs *too early* for this to be possible atm.
That is, if you tried to perform normalization, you'd just run into impls with missing types half the time, and in fact, that's one of the things this patch series will eventually deal with.

File: src/librustc_privacy/lib.rs (hunk 9 above)
Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Yes on also the second point, `proj.super_visit_with(self)` would call `proj.trait_ref.visit_with(self)` which calls `self.visit_trait_ref(proj.trait_ref)` (which is not what we want).

File: src/librustc_privacy/lib.rs [hunk 10]
```diff
@@ -1092,58 +1076,103 @@ impl<'a, 'tcx, 'v> Visitor<'v> for PrivateItemsInPublicInterfacesVisitor<'a, 'tc
...
-                check.visit_item(item);
+            hir::ItemTy(..) => {
+                self.check(item.id, item_visibility).generics().predicates().item_type();
+
+                // Take `impl Trait` into account.
+                self.inner_visibility = item_visibility;
+                intravisit::walk_item(self, item);
+            }
+            hir::ItemTrait(.., ref trait_items) => {
+                self.check(item.id, item_visibility).generics().predicates();
```
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: Are supertraits included in `predicates`?

Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Yes, `super_predicates` (i.e. bounds on `Self`) is a subset of `predicates`.

**Comment by petrochenkov** [comment]
I wanted to finish reviewing today, but it's already morning here and I need to wrap up.

The two remaining questions I didn't figure out yet:
1. How `impl Trait` is treated? As far as I can see if `impl Trait` returns a private type it's caught by the checker. This seems to be too strict, I expected only `Trait` to be checked, but not the anonymized type.
2. How exactly `has_old_errors` works. As far as I can see if the new checker wants to report an error in node `id`, but the old checker doesn't report an error in `id` or any of its children, then we can't report a hard error and return a warning. What is the reasoning behind this?

Besides these two questions everything is reviewed.

**Comment by eddyb** [comment]
@petrochenkov Thank you so much! I'll try to address everything tomorrow (today?).
1. The concrete type of `impl Trait` isn't checked, just the *signature*.
That is, the syntactical `Trait` in `impl Trait` is not part of the type but rather the predicates of `impl Trait`.

2. Previously the rule was based on having an error with a matching `NodeId` in the old checker for the `hir::Ty` node that triggers the error in the new checker. What I have should not produce less errors, as long as the old checker only errored within an item due to access *from* that item.
OTOH, it's possible that in some cases it will trigger more errors (with nested items), but that is fine because there's *already* an error somewhere, so it can't actually harm compiling code, just the accuracy of the old/new distinction *in cases with at least old errors*.

File: src/librustc_privacy/lib.rs [hunk 11]
```diff
@@ -1092,58 +1076,103 @@ impl<'a, 'tcx, 'v> Visitor<'v> for PrivateItemsInPublicInterfacesVisitor<'a, 'tc
             hir::ItemUse(..) | hir::ItemUseGlob(..) => {}
             // Subitems of these items have inherited publicity
             hir::ItemConst(..) | hir::ItemStatic(..) | hir::ItemFn(..) |
-            hir::ItemEnum(..) | hir::ItemTrait(..) | hir::ItemTy(..) => {
-                check.required_visibility = item_visibility;
-                check.visit_item(item);
+            hir::ItemTy(..) => {
+                self.check(item.id, item_visibility).generics().predicates().item_type();
+
+                // Take `impl Trait` into account.
```
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: I asked question 2 in https://github.com/rust-lang/rust/pull/37676#issuecomment-260162743 because this comment was confusing.
I could never guess that `impl Trait` has its own item predicates.

Comment (eddyb) [inline src/librustc_privacy/lib.rs]: Oh right, I was supposed to refer to its public API, i.e. the "trait signature" itself.

File: src/librustc/hir/mod.rs [hunk 12]
```diff
@@ -961,22 +956,24 @@ pub enum Expr_ {
...
+pub enum QPath {
+    /// Path to a definition, optionally "fully-qualified" with a `Self` type
+    /// if it points to an associated item, e.g. `<Vec<T> as Trait>::method`.
+    Regular(Option<P<Ty>>, P<Path>),
+
+    /// Associated path extension, e.g. `<T>::default` or `<T>::Output`.
+    /// UFCS source paths can desugar into this, with `Vec::new` turning into
+    /// `<Vec>::new`, and `T::X::Y::method` into `<<<T>::X>::Y>::method`,
+    /// the inner nodes being each one `TyPath(QPath::Extend(..))`.
+    Extend(P<Ty>, P<PathSegment>)
```
Comment (nikomatsakis) [inline src/librustc/hir/mod.rs]: So, I think the key distinction between "Regular" and "Extend" is that `Extend` requires type-based resolution? I guess that's not quite true, since the same holds for `<X as Y>::Bar` -- but it is true that we have to do a method-style lookup to figure out the trait, right? In any case, I think it'd be helpful for this comment to explain what the difference is.

File: src/librustc/hir/mod.rs (hunk 1 above)
Comment (nikomatsakis) [inline src/librustc/hir/mod.rs]: I'll have to see how this structure works out -- it doesn't seem like what I would naively expect, which is probably something more like:

```rust
pub enum Path {
    Base(P<PathBase>),
    Project(P<Path>, P<PathProjection>),
}

pub enum PathBase {
    Module(P<Path>), // i.e., `::a` (or `a`, in a `use` statement)
    FullyQualified(P<Ty>, P<Path>), // i.e., `<Ty as Path>`
    Type(P<Ty>),
}

...
```

But I can see that the first two cases are kind of the same as `QPath` (also, the structure that I gave is less precise, in that it would permit associated modules etc). But anyway the point is some kind of recursive tree.

That said, I am also happy with this `QPath` structure -- I think mostly I just want some better documentation. Specifically, some examples showing different paths and how they wind up being represented to make it clearer.

File: src/librustc/hir/mod.rs (hunk 12 above)
Comment (nikomatsakis) [inline src/librustc/hir/mod.rs]: (Also, maybe we can pick more descriptive names?)

File: src/librustc/hir/lowering.rs [hunk 13]
```diff
@@ -298,44 +294,103 @@ impl<'a> LoweringContext<'a> {
...
+            return hir::QPath::Regular(qself, path);
+        }
+
+        // Don't keep the inner resolution for the outer node.
+        self.resolver.clear_resolution(id);
```
Comment (nikomatsakis) [inline src/librustc/hir/lowering.rs]: Huh. This is some pretty complex code. Some more comments in general would be helpful, but in particular here: why are setting/clearing resolutions? Ideal would be to find one or two example paths and trace them through the resolution process.

File: src/librustc/hir/lowering.rs [hunk 14]
```diff
@@ -578,7 +604,7 @@ impl<'a> LoweringContext<'a> {
 
     fn lower_trait_ref(&mut self, p: &TraitRef) -> hir::TraitRef {
         hir::TraitRef {
-            path: self.lower_path(&p.path, ParamMode::Explicit),
+            path: self.lower_path(p.ref_id, &p.path, ParamMode::Explicit),
```
Comment (nikomatsakis) [inline src/librustc/hir/lowering.rs]: Side comment: (can we please just give paths an id already?!)

File: src/librustc_const_eval/pattern.rs [hunk 15]
```diff
@@ -163,8 +163,14 @@ impl<'a, 'gcx, 'tcx> PatternContext<'a, 'gcx, 'tcx> {
...
 
-            PatKind::Path(..) => {
-                match self.tcx.expect_def(pat.id) {
+            PatKind::Path(ref qpath) => {
+                let def = match *qpath {
+                    hir::QPath::Regular(_, ref path) => path.def,
+                    hir::QPath::Extend(..) => {
+                        self.tcx.tables().extend_defs[&pat.id]
+                    }
+                };
```
Comment (nikomatsakis) [inline src/librustc_const_eval/pattern.rs]: +1 to a helper on tables

File: src/librustc/hir/lowering.rs [hunk 16]
```diff
@@ -173,6 +182,19 @@ impl<'a> LoweringContext<'a> {
...
     }
 
+    fn lower_label(&mut self, id: NodeId, label: Option<Spanned<Ident>>) -> Option<hir::Label> {
+        label.map(|sp_ident| {
+            hir::Label {
+                span: sp_ident.span,
+                name: sp_ident.node.name,
+                loop_id: match self.expect_full_def(id) {
+                    Def::Label(loop_id) => loop_id,
+                    _ => DUMMY_NODE_ID
```
Comment (nikomatsakis) [inline src/librustc/hir/lowering.rs]: Maybe `Option<>` would be better?

File: src/test/compile-fail/lint-stability.rs [hunk 17]
```diff
@@ -13,7 +13,7 @@
 // aux-build:stability_cfg1.rs
 // aux-build:stability_cfg2.rs
 
-#![deny(deprecated)]
+#![allow(deprecated)]
```
Comment (nikomatsakis) [inline src/test/compile-fail/lint-stability.rs]: sorry, what is going on with this test? was it just bogus before?

File: src/test/compile-fail/lint-stability.rs [hunk 18]
```diff
@@ -430,34 +371,33 @@ mod this_crate {
...
-        <Foo as Trait>::trait_deprecated_text(&foo); //~ ERROR use of deprecated item: text
+        foo.trait_deprecated();
+        Trait::trait_deprecated(&foo);
+        <Foo>::trait_deprecated(&foo);
+        <Foo as Trait>::trait_deprecated(&foo);
+        foo.trait_deprecated_text();
+        Trait::trait_deprecated_text(&foo);
+        <Foo>::trait_deprecated_text(&foo);
+        <Foo as Trait>::trait_deprecated_text(&foo);
         foo.trait_unstable();
```
Comment (nikomatsakis) [inline src/test/compile-fail/lint-stability.rs]: sorry, we do not expect lint errors here?

File: src/librustc/ty/structural_impls.rs [hunk 19]
```diff
@@ -765,6 +769,36 @@ impl<'tcx> TypeFoldable<'tcx> for ty::RegionParameterDef<'tcx> {
     }
 }
 
+impl<'tcx> TypeFoldable<'tcx> for ty::Generics<'tcx> {
+    fn super_fold_with<'gcx: 'tcx, F: TypeFolder<'gcx, 'tcx>>(&self, folder: &mut F) -> Self {
+        ty::Generics {
+            parent: self.parent,
+            parent_regions: self.parent_regions,
```
Comment (nikomatsakis) [inline src/librustc/ty/structural_impls.rs]: Unrelated to this PR: we should really implement folder on all types, so that this is just `fold_with()` no matter what.

File: src/librustc_privacy/lib.rs (hunk 8 above)
Comment (nikomatsakis) [inline src/librustc_privacy/lib.rs]: I'm a bit confused here-- @eddyb we could plausibly normalize before we do this visiting, no?

**Review by nikomatsakis — APPROVED** [review]
I left various comments, but everything here makes sense to me. r=me, assuming @petrochenkov is happy.

File: src/librustc/hir/mod.rs (hunk 12 above)
Comment (eddyb) [inline src/librustc/hir/mod.rs]: `<X as Y>::Bar` is already resolved and typeck needs to do nothing (only trans would look up the exact implementation - which might not even have a `DefId` etc.
As for names I'll gladly take suggestions. These ones are the best I came up with in a day.

File: src/librustc/hir/lowering.rs (hunk 13 above)
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: Nothing is using the `DefMap` now, but if they were, they'd see something not that useful.
I can probably not update it. Also agree on more comments.

File: src/librustc_typeck/astconv.rs [hunk 20]
```diff
@@ -1412,54 +1412,51 @@ impl<'o, 'gcx: 'tcx, 'tcx> AstConv<'gcx, 'tcx>+'o {
...
-                      base_path_ref_id: ast::NodeId,
-                      base_segments: &[hir::PathSegment],
-                      permit_variants: bool)
-                      -> Ty<'tcx> {
+    // Check a type Def and convert it to a Ty.
+    pub fn def_to_ty(&self,
+                     rscope: &RegionScope,
+                     span: Span,
+                     def: Def,
+                     opt_self_ty: Option<Ty<'tcx>>,
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: Yeah resolve expects a `Def::Trait` when that is `Some` - will add the assert.

File: src/librustc/hir/lowering.rs (hunk 16 above)
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: I believe there's already an `Option` around this whole structure.

File: src/test/compile-fail/lint-stability.rs (hunk 17 above)
Comment (eddyb) [inline src/test/compile-fail/lint-stability.rs]: I had to split it in two. It's that thing where if we kept going we'd have to fix so many warnings from lints that were never taken into account. Here the non-lint stability case was moved before typeck.

File: src/test/compile-fail/lint-stability.rs (hunk 18 above)
Comment (eddyb) [inline src/test/compile-fail/lint-stability.rs]: See mumy previous comment, some tests were split.

File: src/librustc/hir/mod.rs (hunk 12 above)
Comment (petrochenkov) [inline src/librustc/hir/mod.rs]: `Resolved`/`Unresolved`, `Early`/`Late`, `Defined`/`Undefined`, `Fixed`/`Overloaded`, `NameBased`/`TypeBased`, `Explicit`/`Inferred`.

Comment (eddyb) [inline src/librustc/hir/mod.rs]: Sadly none of those suggest "associated item" (other than `TypeBased`, I suppose) - I used to have `Project` instead of `Extend` although I changed it because @nikomatsakis mentioned it ("projection" requires a trait everywhere else we use that term).

That said, I like `Resolved` instead of `Regular`. How about `Resolved` / `TypeBased`?
Or `TypeLookup` or even `TypeAssociated` although that's maybe a bit to long.

Comment (nikomatsakis) [inline src/librustc/hir/mod.rs]: +1 to `Resolved` instead of `Regular`

`TypeRelative` seems ok for the other.

File: src/librustc_privacy/lib.rs (hunk 8 above)
Comment (eddyb) [inline src/librustc_privacy/lib.rs]: @nikomatsakis Even if we do normalize we'd still have it in the cases that are more generic.

File: src/librustc/middle/stability.rs (hunk 7 above)
Comment (eddyb) [inline src/librustc/middle/stability.rs]: This can be done later, I don't want to remove the feature in this PR, opened #37981 instead.

**Comment by eddyb** [comment]
Bloody windows. @bors r=nikomatsakis

File: src/librustc_lint/bad_style.rs [hunk 21]
```diff
@@ -288,11 +288,8 @@ impl LateLintPass for NonSnakeCase {
     }
 
     fn check_pat(&mut self, cx: &LateContext, p: &hir::Pat) {
-        if let &PatKind::Binding(_, ref path1, _) = &p.node {
-            // Exclude parameter names from foreign functions (they have no `Def`)
```
Comment (petrochenkov) [inline src/librustc_lint/bad_style.rs]: @eddyb 
>Bloody windows.

These comment and check were here for a reason - to avoid checking parameter names in foreign functions.
WinAPI, for example, uses totally different idiomatic style than Rust and now large part of imports from WinAPI are going show up as errors in buildbot logs.

Comment (eddyb) [inline src/librustc_lint/bad_style.rs]: But they were going about it the wrong way... I suppose I can make this *actually* look for foreign `fn` items so the intent is preserved.

**Comment by arielb1** [comment]
```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64\\link.exe" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\8.1\\lib\\winv6.3\\um\\x64" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps\\rustc_metadata-9869b2000f840c07.0.o" "/OUT:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps\\rustc_metadata-9869b2000f840c07.dll" "/DEF:C:\\Users\\RUSTBU~1\\AppData\\Local\\Temp\\rustc.lktMYCafbdJI\\lib.def" "C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps\\rustc_metadata-9869b2000f840c07.metadata.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\build\\flate-c2681c4afa35212a\\out" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\build\\rustc_llvm-938c943309e964af\\out" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\llvm\\lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "syntax_ext-3a0c73ccaa3da911.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc-18aee6ec33e9eb60.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "graphviz-26ae206855efb7e3.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc_const_math-917fa3468652216c.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "flate-8d768bd83b913ccc.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "proc_macro-c8118cd735a41dff.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "getopts-7163f9091fc23f77.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc_back-59e8426e45dac207.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "syntax-1f9d67ea6af568ee.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc_errors-c81b402346fa89f1.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "syntax_pos-4ad8644d13b8b4e0.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "term-005703da88df29ba.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc_data_structures-0bb70a5eaeaabd25.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "serialize-334034fc22e850fe.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "log-a1f1766e0002cf48.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "fmt_macros-353c95079c400b97.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "arena-d54ed70224a65ce1.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps" "rustc_llvm-2b9b0146bfc11c15.dll.lib" "/LIBPATH:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-4bdc56ec9b040411.dll.lib" "C:\\Users\\RUSTBU~1\\AppData\\Local\\Temp\\rustc.lktMYCafbdJI\\libcompiler_builtins-7ebbe1bca0561620.rlib" "psapi.lib" "kernel32.lib" "ole32.lib" "psapi.lib" "shell32.lib" "ole32.lib" "uuid.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\bot\\slave\\auto-win-msvc-64-opt-rustbuild\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage1-rustc\\x86_64-pc-windows-msvc\\release\\deps\\rustc_metadata-9869b2000f840c07.dll.lib"
  = note: lib.def : error LNK2001: unresolved external symbol _ZN14rustc_metadata5index85_$LT$impl$u20$rustc_metadata..schema..LazySeq$LT$rustc_metadata..index..Index$GT$$GT$15iter_enumerated28_$u7b$$u7b$closure$u7d$$u7d$17h55602b2a39cad770E
```

This looks *random*

@bors retry

**Comment by eddyb** [comment]
@arielb1 it's not, it's an `impl Iterator` exported closure. This works on other platforms but I must've missed some ingredient to making it work on windows too.

@bors r-

**Comment by eddyb** [comment]
@arielb1 Turns out your changes to the handling of closures means `impl Fn` just works now, heh.
