### PR TITLE
Downgrade `linker-warnings` to allow-by-default

### LINKED ISSUE #136086: linker failure on macOS when building Miri: "linker stderr: ld: ignoring duplicate libraries"
Miri is [failing to build](https://github.com/rust-lang/miri/actions/runs/12971694990/job/36179217813?pr=4151) on macOS:
```
 error: linker stderr: ld: ignoring duplicate libraries: '-liconv', '-lm'
         ld: search path '/Users/runner/work/miri/miri/target/release/build/libffi-sys-2c3f829423e2e4d5/out/libffi-root/lib64' not found
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[4](jemalloc.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[5](arena.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[6](background_thread.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[7](base.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[8](bin.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[9](bin_info.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[10](bitmap.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[11](buf_writer.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[12](cache_bin.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[13](ckh.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[14](counter.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[15](ctl.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[16](decay.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[17](div.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[18](ecache.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[19](edata.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[20](edata_cache.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[21](ehooks.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[22](emap.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[23](eset.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[24](exp_grow.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[25](extent.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[26](extent_dss.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[27](extent_mmap.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[28](fxp.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[29](san.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[30](san_bump.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[31](hook.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[32](hpa.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[33](hpa_hooks.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[34](hpdata.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[35](inspect.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[36](large.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[37](log.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[38](malloc_io.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[39](mutex.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[40](nstime.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[41](pa.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[42](pa_extra.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[43](pai.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[44](pac.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[45](pages.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[47](prof.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[48](prof_data.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[50](prof_recent.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[53](psset.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[54](rtree.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[55](safety_check.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[56](sc.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[57](sec.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[58](stats.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[59](sz.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[60](tcache.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[61](test_hooks.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[62](thread_event.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[63](ticker.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[64](tsd.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[65](witness.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/libtikv_jemalloc_sys-80d1ddce8807bb5c.rlib[66](zone.pic.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/liblibffi_sys-713e5fa4137b14c5.rlib[4](prep_cif.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/liblibffi_sys-713e5fa4137b14c5.rlib[5](types.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/liblibffi_sys-713e5fa4137b14c5.rlib[8](closures.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/liblibffi_sys-713e5fa4137b14c5.rlib[10](ffi.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
         ld: object file (/Users/runner/work/miri/miri/target/release/deps/liblibffi_sys-713e5fa4137b14c5.rlib[11](sysv.o)) was built for newer 'macOS' version (14.5) than being linked (11.0)
    |
    = note: `-D linker-messages` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(linker_messages)]`
  error: could not compile `miri` (bin "miri") due to 1 previous error
  error: failed to compile `miri v0.1.0 (/Users/runner/work/miri/miri)`, intermediate artifacts can be found at `/Users/runner/work/miri/miri/target`.
  To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
  Error: command exited with non-zero code `cargo +miri install --locked -Zroot-dir=/Users/runner/work/miri/miri --path /Users/runner/work/miri/miri --force --root /Users/runner/.rustup/toolchains/miri`: 101
```

Regression range: https://github.com/rust-lang/rust/compare/814ebca2931bd25384ade5018e1cbc403b13ec11...2f0ad2a71e4a4528bb80bcb24bf8fa4e50cb87c2

### PR DESCRIPTION
**Pull request by jyn514**
This needs more time to bake before we turn it on. Turning it on early risks people silencing the warning indefinitely, before we have the chance to make it less noisy.

cc https://github.com/rust-lang/rust/issues/136096
fixes https://github.com/rust-lang/rust/issues/136086#issuecomment-2614476308

r? @saethlin cc @Noratrieb @bjorn3 

@rustbot label A-linkage L-linker_messages

### CODE REVIEW

**Comment by Noratrieb** [comment]
@bors r-
I look really silly now

File: tests/run-make/rust-lld-by-default-beta-stable/rmake.rs [hunk 1]
```diff
@@ -12,7 +12,7 @@ use run_make_support::rustc;
 fn main() {
     // A regular compilation should not use rust-lld by default. We'll check that by asking the
     // linker to display its version number with a link-arg.
-    let output = rustc().link_arg("-Wl,-v").input("main.rs").run();
+    let output = rustc().arg("-Wlinker-messages").link_arg("-Wl,-v").input("main.rs").run();
```
Comment (jyn514) [inline tests/run-make/rust-lld-by-default-beta-stable/rmake.rs:15]: cc @rust-lang/release it continues to make me very uncomfortable to be editing tests that i have no way of running. if this fails in 6 weeks i do not know if i will have time to fix it.

Comment (cuviper) [reply tests/run-make/rust-lld-by-default-beta-stable/rmake.rs:15]: Locally, you can config `[rust] channel = "beta"` (or stable). For CI, you could temporarily change `src/ci/channel` for a `@bors try` attempt.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 2]
```diff
@@ -4104,17 +4105,20 @@ declare_lint! {
...
+    /// 1 | #![warn(linker_messages)]
+    ///   |         ^^^^^^^^^^^^^^^
     /// warning: 1 warning emitted
     /// ```
     ///
     /// ### Explanation
     ///
     /// Linkers emit platform-specific and program-specific warnings that cannot be predicted in advance by the rust compiler.
-    /// They are forwarded by default, but can be disabled by adding `#![allow(linker_messages)]` at the crate root.
+    /// They are forwarded by default, but can be disabled by adding `#![allow(linker_messages)]` at the root of a crate that requires linking.
```
Comment (retep998) [inline compiler/rustc_lint_defs/src/builtin.rs:4119]: Shouldn't this be updated to say they are *not* forwarded by default?

File: tests/run-make/rust-lld-by-default-beta-stable/rmake.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply tests/run-make/rust-lld-by-default-beta-stable/rmake.rs:15]: This test runs in (full) CI on the x86_64-gnu-stable job:

https://github.com/rust-lang-ci/rust/actions/runs/12975734650/job/36187153380

2025-01-26T16:46:32.1849227Z test [run-make] tests/run-make/rust-lld-by-default-beta-stable ... ok

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 2 above)
Comment (saethlin) [reply compiler/rustc_lint_defs/src/builtin.rs]: Good callout. I took the time to also update this paragraph to elaborate on the current state of the lint.

**Comment by saethlin** [comment]
Well don't I look silly now.

**Comment by pietroalbini** [comment]
@bors p=10

Now go to sleep >:(
