### PR TITLE
incr.comp.: Fix HashStable for ty::RegionKind and trans item order

### LINKED ISSUE #45161: ICE: /checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, "BrEnv")
Received the ICE in the title when compilng [rsjni](https://github.com/rustyhorde/rsjni)

[output.txt](https://github.com/rust-lang/rust/files/1370453/output.txt)

This only occurred on the `x86_64-unknown-linux-gnu` nightly build.   I was able to successfully build and test with `i686-unknown-linux-gnu` and `x86_64-pc-windows-msvc` nightlies.

## Meta
`rustc --version --verbose`

rustc 1.22.0-nightly (692b94ae2 2017-10-09)
binary: rustc
commit-hash: 692b94ae25e0ae7d74cf15a5800e10a16239dab1
commit-date: 2017-10-09
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::bug_fmt
  10: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::RegionKind>::hash_stable
  11: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable
  12: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::Binder<T>>::hash_stable
  13: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable
  14: <T as rustc::dep_graph::dep_node::DepNodeParams<'a, 'gcx, 'tcx>>::to_fingerprint
  15: rustc::dep_graph::dep_node::DepNode::new
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::is_sized_raw<'tcx>>::try_get
  17: rustc::ty::maps::TyCtxtAt::is_sized_raw
  18: rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::is_sized
  19: rustc_trans::callee::get_fn
  20: rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_terminator
  21: rustc_trans::mir::trans_mir
  22: rustc_trans::base::trans_instance
  23: rustc_trans::base::compile_codegen_unit
  24: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get
  26: rustc::ty::maps::TyCtxtAt::compile_codegen_unit
  27: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit
  28: rustc_trans::base::trans_crate
  29: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  30: rustc_driver::driver::compile_input::{{closure}}
  31: rustc::ty::context::TyCtxt::create_and_enter
  32: rustc_driver::driver::compile_input
  33: rustc_driver::run_compiler

error: Could not compile `rsjni`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rsjni src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="nine" -C metadata=6f62d2c5bbcca5bb -C extra-filename=-6f62d2c5bbcca5bb --out-dir /data/projects/rust-lang/rsjni/target/debug/deps -L dependency=/data/projects/rust-lang/rsjni/target/debug/deps --extern error_chain=/data/projects/rust-lang/rsjni/target/debug/deps/liberror_chain-07f6a9232ac6c576.rlib --extern getset=/data/projects/rust-lang/rsjni/target/debug/deps/libgetset-16d8a528ec0c58f1.so -Zincremental=/data/projects/rust-lang/rsjni/target/debug/incremental -L /opt/java/lib/server -l jvm -L native=/data/projects/rust-lang/rsjni/target/debug/build/backtrace-sys-09fe0c7e20aa4b64/out/.libs` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by michaelwoerister**
Fixes #45161 and the failing rust-icci tests.

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_trans/partitioning.rs [hunk 1]
```diff
@@ -163,10 +163,27 @@ pub trait CodegenUnitExt<'tcx> {
...
-                TransItem::Fn(instance) => {
-                    tcx.hir.as_local_node_id(instance.def_id())
+                TransItem::Fn(ref instance) => {
+                    match instance.def {
+                        // We only want to take NodeIds of user-defined
+                        // instances into account. The others don't matter for
+                        // the codegen tests and can even make item order
+                        // unstable.
+                        InstanceDef::Item(def_id) => {
+                            tcx.hir.as_local_node_id(def_id)
```
Comment (nikomatsakis) [inline src/librustc_trans/partitioning.rs]: should we sort instead by `def_id`?

**Review by nikomatsakis — APPROVED** [review]
Seems fine. I left a question, but I'll r+ in the meantime.

File: src/librustc_trans/partitioning.rs (hunk 1 above)
Comment (michaelwoerister) [reply src/librustc_trans/partitioning.rs]: I'm not sure that `DefIds` also reflect definition order. They probably do. This whole thing is a bit of a hack anyway. We could sort by `Span`...

Comment (nikomatsakis) [reply src/librustc_trans/partitioning.rs]: DefIds do not reflect definition order, except in anonymous cases like impls. Otherwise, they would sort by name. Why do we care if these are  reflect "definition order" per se?

Comment (michaelwoerister) [reply src/librustc_trans/partitioning.rs]: I makes writing the codegen tests a lot more pleasant if you know in which order things will appear in LLVM IR. You could of course also run the compiler once to find out what the order is but that's another hurdle to writing such tests. Also the tests might break if we changed the details of our symbol mangling (which we've done quite a few times). What we have now is "OK" in comparison, I think.

**Comment by michaelwoerister** [comment]
@bors p=1

Taking the liberty of bumping the priority of this since it will (hopefully) unbreak perf.rlo.

**Comment by alexcrichton** [comment]
@michaelwoerister @nikomatsakis the [bootstrap compiler update](https://github.com/rust-lang/rust/pull/45285) has bounced I believe due to https://github.com/rust-lang/rust/issues/45161 and I think this PR is not currently in beta. Any objections to backporting this?

**Comment by michaelwoerister** [comment]
No objections.
