### PR TITLE
Emit errors/warns on some wrong uses of rustdoc attributes

### LINKED ISSUE #80275: Rustdoc should give an error if you set both `doc(inline)` and `doc(no_inline)`
Given the following code:
```rust
#![crate_type = "lib"]

pub mod inner {
    pub struct S;
}

#[doc(inline)]
#[doc(no_inline)]
pub use inner::S;
```

Rustdoc will generate image
This is bogus: rustdoc is ignoring one of the attributes. Instead, it should give an error that you can't apply both attributes to the same item.

Thought of while reviewing https://github.com/rust-lang/rust/pull/80267.

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
This PR adds a few diagnostics:
- error if conflicting `#[doc(inline)]`/`#[doc(no_inline)]` are found
- introduce the `invalid_doc_attributes` lint (warn-by-default) which triggers:
  - if a crate-level attribute is used on a non-`crate` item
  - if `#[doc(inline)]`/`#[doc(no_inline)]` is used on a non-`use` item

The code could probably be improved but I wanted to get feedback first. Also, some of those changes could be considered breaking changes, so I don't know what the procedure would be? ~~And finally, for the warnings, they are currently hard warnings, maybe it would be better to introduce a lint?~~ (EDIT: introduced the `invalid_doc_attributes` lint)

Closes #80275.
r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
I think this should probably go through FCP - I'll take a look at the code first so the review isn't intermingled with the policy change.

File: src/librustdoc/visit_ast.rs [hunk 1]
```diff
@@ -337,4 +352,58 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
             om.foreigns.push((item, renamed));
         }
     }
+
+    /// Run a few checks on the `#[doc]` attributes for an item:
+    /// - warn if a crate-level attribute is used on a non-`crate` item
+    /// - warn if `#[doc(inline)]`/`#[doc(no_inline)]` is used on a non-`use` item
+    /// - error if conflicting `#[doc(inline)]`/`#[doc(no_inline)]` are found
+    fn check_item_attrs(&mut self, attrs: &'tcx [ast::Attribute], is_crate: bool, is_use: bool) {
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:360]: nit: this allows impossible states (`is_crate` and `is_use` set simultaneously). I'd prefer to have an explicit type instead:

```rust
enum AttrKind {
    Crate,
    Use,
    Other,
}
```
but at that point it might be simpler to just pass in the `ItemKind` directly.

File: src/librustdoc/visit_ast.rs [hunk 2]
```diff
@@ -337,4 +352,58 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+        for attr in attrs.lists(sym::doc) {
+            // Check for crate-level attributes used on non-crate item
+            if !is_crate
+                && attr
+                    .meta_item()
+                    .map_or(false, |meta| CRATE_LEVEL_ATTRS.iter().any(|attr| meta.path == *attr))
+            {
+                self.cx
+                    .sess()
+                    .struct_span_warn(attr.meta_item().unwrap().span, "this attribute can only be applied at the crate level")
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:372]: Maybe add a new error code for this?

File: src/librustdoc/visit_ast.rs [hunk 3]
```diff
@@ -337,4 +352,58 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                            let attr_span = attr.meta_item().unwrap().span;
+                            let mut spans = MultiSpan::from_spans(vec![prev_span, attr_span]);
+                            spans.push_span_label(prev_span, String::from("this attribute..."));
+                            spans.push_span_label(
+                                attr_span,
+                                String::from("...conflicts with this attribute"),
+                            );
+                            self.cx
+                                .sess()
+                                .struct_span_err(spans, "conflicting doc inlining attributes")
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:392]: What's the difference between using `MultiSpan` and `diag.span_label("this attribute")`?

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:392]: Also, I'm think this isn't supposed to depend on the order of the attributes in case the diagnostic library switches it.

File: src/test/rustdoc-ui/check-doc-attrs.rs [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+pub mod bar {
+    pub struct Bar;
+}
+
+#[doc(no_inline)]
+//~^ WARNING can only be applied to a `use` item
+#[doc(html_no_source)]
+//~^ WARNING can only be applied at the crate level
+fn main() {}
```
Comment (jyn514) [inline src/test/rustdoc-ui/check-doc-attrs.rs:18]: nit: missing a newline at EOF, this will break `cat`.

**Review by jyn514 — COMMENTED** [review]
Left a few comments, and I think it would be helpful for @estebank to take a look if you have time.

File: src/test/rustdoc-ui/check-doc-attrs.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
+#![doc(inline)]
+//~^ WARNING can only be applied to a `use` item
+
+#[doc(inline)]
+#[doc(no_inline)]
+//~^^ ERROR conflicting doc inlining attributes
+//~|  ERROR conflicting doc inlining attributes
```
Comment (pickfire) [inline src/test/rustdoc-ui/check-doc-attrs.rs:7]: Why is this duplicated?

Comment (jyn514) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: It warns one per attribute: the first one warns about `doc(inline)`, the second about `doc(no_inline)`.

File: src/librustdoc/visit_ast.rs (hunk 1 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:360]: There is no `ItemKind::Crate`, so I'll go with an `AttrKind` enum

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 5 above)
Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: It's supposed to error only once though. I think it's just how the `MultiSpan` is handled.

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 4 above)
Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.rs:18]: And CI 😕

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:372]: I was thinking about adding a lint as I said in the original post. Which would be prefered?

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 5 above)
Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: I added a `#[doc(no_inline)]` and I'm getting (with `-Zdeduplicate-diagnostics=no`):

```
error: conflicting doc inlining attributes
 --> src/test/rustdoc-ui/check-doc-attrs.rs:4:7
  |
4 | #[doc(inline)]
  |       ^^^^^^ this attribute...
5 | #[doc(no_inline)]
  |       ^^^^^^^^^ ...conflicts with this attribute
  |
  = help: remove one of the conflicting attributes

error: conflicting doc inlining attributes
 --> src/test/rustdoc-ui/check-doc-attrs.rs:4:7
  |
4 | #[doc(inline)]
  |       ^^^^^^ this attribute...
5 | #[doc(no_inline)]
6 | #[doc(no_inline)]
  |       ^^^^^^^^^ ...conflicts with this attribute
  |
  = help: remove one of the conflicting attributes

error: conflicting doc inlining attributes
 --> src/test/rustdoc-ui/check-doc-attrs.rs:4:7
  |
4 | #[doc(inline)]
  |       ^^^^^^ this attribute...
5 | #[doc(no_inline)]
  |       ^^^^^^^^^ ...conflicts with this attribute
  |
  = help: remove one of the conflicting attributes

error: conflicting doc inlining attributes
 --> src/test/rustdoc-ui/check-doc-attrs.rs:4:7
  |
4 | #[doc(inline)]
  |       ^^^^^^ this attribute...
5 | #[doc(no_inline)]
6 | #[doc(no_inline)]
  |       ^^^^^^^^^ ...conflicts with this attribute
  |
  = help: remove one of the conflicting attributes
```

File: src/librustdoc/visit_ast.rs [hunk 6]
```diff
@@ -337,4 +358,65 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                        .note("read https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#docno_inlinedocinline for more information")
+                        .emit();
+                }
+            }
+        }
+    }
+}
+
+#[derive(Debug, Copy, Clone, PartialEq)]
+enum AttrRecieverKind {
```
Comment (GuillaumeGomez) [inline src/librustdoc/visit_ast.rs:418]:
```suggestion
enum AttrReceiverKind {
```

Little typo. :)

**Comment by GuillaumeGomez** [comment]
Also, it could be interesting to add a macro like https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/macro.struct_span_err.html for warnings (but without error code).

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 5 above)
Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: Looks like two different `Use` items exist:
```
DEBUG rustdoc::visit_ast visiting item Item { ident: Bar#0, hir_id: HirId { owner: DefId(0:3 ~ check_doc_attrs[8787]::{misc#1}), local_id: 0 }, attrs: [Attribute { kind: Normal(AttrItem { path: Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:4:3: 4:6 (#0), segments: [PathSegment { ident: doc#0, id: NodeId(12), args: None }], tokens: None }, args: Delimited(DelimSpan { open: src/test/rustdoc-ui/check-doc-attrs.rs:4:6: 4:7 (#0), close: src/test/rustdoc-ui/check-doc-attrs.rs:4:13: 4:14 (#0) }, Parenthesis, TokenStream([(Token(Token { kind: Ident("inline", false), span: src/test/rustdoc-ui/check-doc-attrs.rs:4:7: 4:13 (#0) }), Alone)])), tokens: None }, None), id: AttrId(1), style: Outer, span: src/test/rustdoc-ui/check-doc-attrs.rs:4:1: 4:15 (#0) }, Attribute { kind: Normal(AttrItem { path: Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:5:3: 5:6 (#0), segments: [PathSegment { ident: doc#0, id: NodeId(13), args: None }], tokens: None }, args: Delimited(DelimSpan { open: src/test/rustdoc-ui/check-doc-attrs.rs:5:6: 5:7 (#0), close: src/test/rustdoc-ui/check-doc-attrs.rs:5:16: 5:17 (#0) }, Parenthesis, TokenStream([(Token(Token { kind: Ident("no_inline", false), span: src/test/rustdoc-ui/check-doc-attrs.rs:5:7: 5:16 (#0) }), Alone)])), tokens: None }, None), id: AttrId(2), style: Outer, span: src/test/rustdoc-ui/check-doc-attrs.rs:5:1: 5:18 (#0) }], kind: Use(Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:8:9: 8:17 (#0), res: Def(Struct, DefId(0:5 ~ check_doc_attrs[8787]::bar::Bar)), segments: [PathSegment { ident: bar#0, hir_id: Some(HirId { owner: DefId(0:3 ~ check_doc_attrs[8787]::{misc#1}), local_id: 1 }), res: Some(Def(Mod, DefId(0:4 ~ check_doc_attrs[8787]::bar))), args: None, infer_args: false }, PathSegment { ident: Bar#0, hir_id: Some(HirId { owner: DefId(0:3 ~ check_doc_attrs[8787]::{misc#1}), local_id: 2 }), res: Some(Err), args: None, infer_args: false }] }, Single), vis: Spanned { node: Public, span: src/test/rustdoc-ui/check-doc-attrs.rs:8:1: 8:4 (#0) }, span: src/test/rustdoc-ui/check-doc-attrs.rs:8:1: 8:18 (#0) }
```
```
DEBUG rustdoc::visit_ast visiting item Item { ident: Bar#0, hir_id: HirId { owner: DefId(0:8 ~ check_doc_attrs[8787]::{misc#1}::{misc#0}), local_id: 0 }, attrs: [Attribute { kind: Normal(AttrItem { path: Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:4:3: 4:6 (#0), segments: [PathSegment { ident: doc#0, id: NodeId(12), args: None }], tokens: None }, args: Delimited(DelimSpan { open: src/test/rustdoc-ui/check-doc-attrs.rs:4:6: 4:7 (#0), close: src/test/rustdoc-ui/check-doc-attrs.rs:4:13: 4:14 (#0) }, Parenthesis, TokenStream([(Token(Token { kind: Ident("inline", false), span: src/test/rustdoc-ui/check-doc-attrs.rs:4:7: 4:13 (#0) }), Alone)])), tokens: None }, None), id: AttrId(1), style: Outer, span: src/test/rustdoc-ui/check-doc-attrs.rs:4:1: 4:15 (#0) }, Attribute { kind: Normal(AttrItem { path: Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:5:3: 5:6 (#0), segments: [PathSegment { ident: doc#0, id: NodeId(13), args: None }], tokens: None }, args: Delimited(DelimSpan { open: src/test/rustdoc-ui/check-doc-attrs.rs:5:6: 5:7 (#0), close: src/test/rustdoc-ui/check-doc-attrs.rs:5:16: 5:17 (#0) }, Parenthesis, TokenStream([(Token(Token { kind: Ident("no_inline", false), span: src/test/rustdoc-ui/check-doc-attrs.rs:5:7: 5:16 (#0) }), Alone)])), tokens: None }, None), id: AttrId(2), style: Outer, span: src/test/rustdoc-ui/check-doc-attrs.rs:5:1: 5:18 (#0) }], kind: Use(Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:8:9: 8:17 (#0), res: Def(Ctor(Struct, Const), DefId(0:6 ~ check_doc_attrs[8787]::bar::Bar::{constructor#0})), segments: [PathSegment { ident: bar#0, hir_id: Some(HirId { owner: DefId(0:8 ~ check_doc_attrs[8787]::{misc#1}::{misc#0}), local_id: 1 }), res: Some(Err), args: None, infer_args: false }, PathSegment { ident: Bar#0, hir_id: Some(HirId { owner: DefId(0:8 ~ check_doc_attrs[8787]::{misc#1}::{misc#0}), local_id: 2 }), res: Some(Err), args: None, infer_args: false }] }, Single), vis: Spanned { node: Public, span: src/test/rustdoc-ui/check-doc-attrs.rs:8:1: 8:4 (#0) }, span: src/test/rustdoc-ui/check-doc-attrs.rs:8:9: 8:17 (#0) }
```

Both point to line 8 (`pub use bar::Bar`). Seems very confusing to me.

I think this could be cleaned up later, considering that the error get deduplicated by rustc anyway.

Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: I think that if `check_item_attrs` gets called twice, we should fix it first before merging this one. The problem is that you call the check on the `krate` and then it gets called again. Instead of doing that, just check if you are at the crate level. I did the same in another part of the compiler, posting the link when I have it...

Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: Hum but in your case, just removing the function call should be enough to remove this issue. :3

Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: Sorry, I still don't understand... Which call would you remove? And from my debugging it appears to me that there are two distinct `Item`s pointing to the same `use` statement, is this wrong?

Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: I really think the common item is `krate.item`.

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/visit_ast.rs:378]: lints sound fine to me as long as there's something clear rustdoc can do. Any case that's ambiguous should be a hard error I think - so e.g. `#[doc(inline)] struct S;` should be a warning but
```rust
#[doc(inline)]
#[doc(no_inline)]
pub use crate::S;
```
should be a hard error.

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 5 above)
Comment (jyn514) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: The issue is that `struct S;` desugars to something like
```rust
struct S {}
fn S() -> S { ... }
```
except with compiler magic so you don't need the parentheses. If you look at the debugging @LeSeulArtichaut found, it contains
```
kind: Use(Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:8:9: 8:17 (#0), res: Def(Struct, DefId(0:5 ~ check_doc_attrs[8787]::bar::Bar))
kind: Use(Path { span: src/test/rustdoc-ui/check-doc-attrs.rs:8:9: 8:17 (#0), res: Def(Ctor(Struct, Const), DefId(0:6 ~ check_doc_attrs[8787]::bar::Bar::{constructor#0}))
```
So I think the fix is to ignore attributes on Ctor items, because they can never occur without also occurring on the struct itself.

**Comment by jyn514** [comment]
> Also, it could be interesting to add a macro like https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/macro.struct_span_err.html for warnings (but without error code).

I think that's https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.struct_span_lint_hir.

File: src/test/rustdoc-ui/check-doc-attrs.rs (hunk 5 above)
Comment (jyn514) [reply src/test/rustdoc-ui/check-doc-attrs.rs:7]: For the same reason, re-exporting an item have different behavior than using the original if it has private fields: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=764be855d78364df0b1b8eb0dbd7ce8e

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:378]: So you agree with the categorization in warns/errs that I have implemented? The attributes that `rustdoc` can ignore only get a warn, but `#[doc(inline)] #[doc(no_inline)] struct S;` is a hard error.

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:378]: Yes, that sounds good to me :)

File: src/librustdoc/visit_ast.rs [hunk 7]
```diff
@@ -243,13 +243,15 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
         debug!("visiting item {:?}", item);
 
-        let receiver_kind = if let hir::ItemKind::Use(..) = item.kind {
-            AttrReceiverKind::Use
+        if let hir::ItemKind::Use(path, _) = item.kind {
+            if let hir::def::Res::Def(hir::def::DefKind::Ctor(..), _) = path.res {
+                // ignore auto-generated constructors to avoid duplicated errors
+            } else {
+                self.check_item_attrs(&item.attrs, AttrReceiverKind::Use)
+            }
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:251]:
```suggestion
            // ignore auto-generated constructors to avoid duplicated errors
            if !matches(path.res, hir::def::Res::Def(hir::def::DefKind::Ctor(..), _)) {
                self.check_item_attrs(&item.attrs, AttrReceiverKind::Use)
            }
```

File: src/test/rustdoc-ui/check-doc-attrs.stderr [hunk 8]
```diff
@@ -0,0 +1,52 @@
+warning: this attribute can only be applied to a `use` item
+  --> $DIR/check-doc-attrs.rs:1:8
+   |
+LL | #![doc(inline)]
+   |        ^^^^^^
+   |
+   = note: read https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#docno_inlinedocinline for more information
```
Comment (jyn514) [inline src/test/rustdoc-ui/check-doc-attrs.stderr:7]: It would be nice to point to the item here:
```
warning: this attribute can only be applied to a `use` item
  --> $DIR/check-doc-attrs.rs:1:8
   |
LL | #![doc(inline)]
   |        ^^^^^^
   | struct Foo;
   | ^^^^^^^^^^^ not a `use` item
   = note: read https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#docno_inlinedocinline for more information

File: src/test/rustdoc-ui/check-doc-attrs.stderr [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+   |
+LL | #[doc(no_inline)]
+   |       ^^^^^^^^^
+   |
+   = note: read https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#docno_inlinedocinline for more information
+
+warning: this attribute can only be applied at the crate level
+  --> $DIR/check-doc-attrs.rs:21:7
+   |
+LL | #[doc(html_no_source)]
```
Comment (jyn514) [inline src/test/rustdoc-ui/check-doc-attrs.stderr:46]: Maybe suggest `#![doc(html_no_source)]` instead? https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion

Comment (LeSeulArtichaut) [reply src/test/rustdoc-ui/check-doc-attrs.stderr:46]: Good idea! But only if the enclosing scope is the crate, I guess

File: src/librustdoc/visit_ast.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/visit_ast.rs:380]: Here's an example of adding a lint: https://github.com/rust-lang/rust/pull/77856/files

File: src/librustdoc/visit_ast.rs (hunk 7 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:251]: Oh, right, this is so much cleaner :)

File: src/test/rustdoc-ui/check-doc-attrs.stderr (hunk 9 above)
Comment (jyn514) [reply src/test/rustdoc-ui/check-doc-attrs.stderr:46]: This should only happen for items in the current crate, right? Or at least, if not that's a bug - we shouldn't be linting other crates.

Comment (jyn514) [reply src/test/rustdoc-ui/check-doc-attrs.stderr:46]: >  But only if the enclosing scope is the crate

Oh I misread this - yes, ideally this would only warn if this is an outer attribute on an item with the crate root as the parent. You can find that out with `tcx.parent(item).index == CRATE_DEF_INDEX`.

**Comment by LeSeulArtichaut** [comment]
Note to self:
- just use `span_label`
- take the span of the whole attribute for the suggestion

File: src/librustdoc/visit_ast.rs (hunk 3 above)
Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:417]: IIUC, `span_label` adds a "non-primary" span which getd shown in blue. Here boths spans get shown in red.
Unsure what's best though.

Comment (jyn514) [reply src/librustdoc/visit_ast.rs:417]: Ahh, that makes sense - you have two primary labels instead of one primary and one secondary. No need to change this, then.

File: src/librustdoc/visit_ast.rs [hunk 10]
```diff
@@ -333,4 +363,102 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+            // Check for crate-level attributes used on non-crate item
+            if item != AttrReceiverKind::Crate
+                && attr
+                    .meta_item()
+                    .map_or(false, |meta| CRATE_LEVEL_ATTRS.iter().any(|attr| meta.path == *attr))
+            {
+                let mut err = self.cx.sess().struct_span_warn(
+                    attr.meta_item().unwrap().span,
+                    "this attribute can only be applied at the crate level",
+                );
```
Comment (jyn514) [inline src/librustdoc/visit_ast.rs:398]: Were you going to make this a lint so it can be `allow`ed or denied?

Comment (LeSeulArtichaut) [reply src/librustdoc/visit_ast.rs:398]: Yes, still working on this ;)

**Comment by LeSeulArtichaut** [comment]
@jyn514 @GuillaumeGomez this is ready for review again

File: src/doc/rustdoc/src/lints.md [hunk 11]
```diff
@@ -251,6 +251,33 @@ warning: unknown attribute `should-panic`. Did you mean `should_panic`?
 In the example above, the correct form is `should_panic`. This helps detect
 typo mistakes for some common attributes.
 
+## invalid_doc_attributes
+
+This lint is **warn by default**. It detects misuses of the `#[doc]` attribute,
+like trying to apply `#[doc(inline)]` on a non-`use` item. For example:
```
Comment (jyn514) [inline src/doc/rustdoc/src/lints.md:257]:
```suggestion
like trying to apply `#[doc(inline)]` on something other than a re-export. For example:
```

File: src/doc/rustdoc/src/lints.md [hunk 12]
```diff
@@ -283,7 +310,6 @@ warning: unclosed HTML tag `h1`
 2 | | /// </script>
   | |_____________^
 
-warning: 2 warnings emitted
```
Comment (jyn514) [inline src/doc/rustdoc/src/lints.md:286]: Did you mean to change this?

**Comment by jyn514** [comment]
@rfcbot fcp merge

This gives warnings or errors for several possible mistakes with the `#[doc]` attribute:

- warn (as an `invalid_doc_attributes` lint) if a crate-level attribute is used on a non-`crate` item
- warn (as an `invalid_doc_attributes` lint) if `#[doc(inline)]`/`#[doc(no_inline)]` is used on a non-`use` item
- hard error if conflicting `#[doc(inline)]`/`#[doc(no_inline)]` are found

These have no semantic meaning and are currently ignored, except that having both `inline` and `no_inline` currently gives precedence to `no_inline`.

File: src/doc/rustdoc/src/lints.md (hunk 12 above)
Comment (LeSeulArtichaut) [reply src/doc/rustdoc/src/lints.md:286]: Oops

**Comment by jyn514** [comment]
@rfcbot concern wait for renaming

Petrochenkov mentioned in https://github.com/rust-lang/rust/pull/80456#issuecomment-751882904 that rustdoc should really be using `rustdoc::x` for lints instead of making them built-in lints directly (which normally go through T-lang). I think we should wait for the lints to be renamed so we don't have even more lints to deprecate. I hope to do that sometime in the next couple weeks (depending how long it takes me to figure it out: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/What.20is.20the.20policy.20for.20new.20lints.3F).

**Comment by LeSeulArtichaut** [comment]
@jyn514 I could split out the error from the warnings if you want

**Comment by jyn514** [comment]
@LeSeulArtichaut that would be great! Then we could error on that immediately and wait to merge the warnings until I finish renaming the lints.

**Comment by LeSeulArtichaut** [comment]
Should I close this PR and open a new one?

**Review by syncing0x — APPROVED** [review]

**Comment by jyn514** [comment]
@LeSeulArtichaut let's wait for the FCP to finish, then you can split the error into a separate PR and have the warnings in this one stay blocked on https://github.com/rust-lang/rust/pull/80527.

File: src/librustdoc/visit_ast.rs [hunk 13]
```diff
@@ -333,4 +364,111 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+                    } else {
+                        specified_inline = Some((inline, attr.meta_item().unwrap().span));
+                    }
+                } else {
+                    self.cx.tcx.struct_span_lint_hir(
+                        INVALID_DOC_ATTRIBUTES,
+                        hir_id,
+                        attr.meta_item().unwrap().span,
+                        |lint| {
+                            let mut err = lint.build("this attribute can only be applied to a `use` item");
```
Comment (estebank) [inline src/librustdoc/visit_ast.rs:455]:
```suggestion
                            let mut err = lint.build("this attribute can only be applied to a `use` item");
                            err.span_label(attr.meta_item().unwrap().span, "only applicable on `use` items");
```

**Review by estebank — COMMENTED** [review]
I have only one nitpick, but otherwise the changes look great!

**Comment by LeSeulArtichaut** [comment]
@jyn514 This will be able to enter FCP with your concern resolved.

**Comment by jyn514** [comment]
> @jyn514 This will be able to enter FCP with your concern resolved.

Just to clarify, the FCP is for adding the lint in general, not adding it as a built-in lint? I still thing we should wait to add the lint until rustdoc uses a `rustdoc::` prefix: https://github.com/rust-lang/rust/pull/80527.

File: src/test/rustdoc-ui/check-doc-attrs.stderr [hunk 14]
```diff
@@ -0,0 +1,71 @@
+error: this attribute can only be applied to a `use` item
+  --> $DIR/check-doc-attrs.rs:3:8
+   |
+LL | #![doc(inline)]
+   |        ^^^^^^
+   |
```
Comment (estebank) [inline src/test/rustdoc-ui/check-doc-attrs.stderr:6]: Unnecessary nitpick: The only inconsistency I see here is that we don't point at the `mod`, which is reasonable, but maybe we would want to add a `note` saying "`#[doc(inline)]` cannot be applied to a `mod`, or something similar (but we'd probably want another iteration to make sure we remove redundant wording... maybe add it to the message?: "this attribute can only be applied to a `use` item, not a `mod`").

**Comment by LeSeulArtichaut** [comment]
> > @jyn514 This will be able to enter FCP with your concern resolved.
> 
> Just to clarify, the FCP is for adding the lint in general, not adding it as a built-in lint? I still thing we should wait to add the lint until rustdoc uses a `rustdoc::` prefix: #80527.

Ah, I thought you wanted to have the FCP now so that we could merge the error part. Don't mind me then

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/80527 was merged, so this is no longer blocked :)

@rustbot label: -S-blocked +S-waiting-on-author

**Comment by LeSeulArtichaut** [comment]
Rebased on #80527 and made `invalid_doc_attributes` a rustdoc tool lint. I haven't tested it though, but CI should catch any mistakes 🤞

@jyn514 should the FCP be unblocked now?

**Comment by jyn514** [comment]
@rfcbot resolved wait for renaming

**Comment by LeSeulArtichaut** [comment]
CI error is spurious (networking error), re-running the tests

**Comment by Manishearth** [comment]
Wait hold on, we're adding `invalid_doc_attributes` to https://github.com/rust-lang/rust/pull/82708. This seems to be adding `rustdoc::invalid_doc_attributes` for a different purpose. Let's make sure we have different names for these lints or if they can be merged (note that `invalid_doc_attributes` is a future incompat lint)

**Comment by jyn514** [comment]
@Manishearth hmm, do you see this as a different kind of error than https://github.com/rust-lang/rust/pull/82708 ? They're both warning on attributes that are invalid and currently do nothing. Why would we make this one only a lint but the other a future-incompat warning?

**Comment by jyn514** [comment]
But yeah these PRs conflict and we should probably wait for https://github.com/rust-lang/rust/pull/82708.

**Comment by Manishearth** [comment]
> @Manishearth hmm, do you see this as a different kind of error than #82708 ? They're both warning on attributes that are invalid and currently do nothing. Why would we make this one only a lint but the other a future-incompat warning?

Not necessarily! I want to allow for this to be something we don't consider future incompat. But if we consider all of this to be future incompat, go for it! I don't have a strong opinion either way.

**Comment by LeSeulArtichaut** [comment]
#82708 has been merged now. Should I merge my `invalid_doc_attributes` with the existing one in #82708, so all the warns in this PR become future-incompat lints? Would you prefer another solution?

**Comment by jyn514** [comment]
> #82708 has been merged now. Should I merge my invalid_doc_attributes with the existing one in #82708, so all the warns in this PR become future-incompat lints? Would you prefer another solution?

I think that's the best approach, yes.

**Comment by jyn514** [comment]
@LeSeulArtichaut I think this is just waiting on a rebase to merge your new lint with the future-incompat one :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me. Just need the future-incompat rebase like @jyn514 suggested and we should be good to go!

**Comment by LeSeulArtichaut** [comment]
Diving into this only now, sorry for the wait.

So #82708 (which IIUC is a subset of this PR) runs its checks in `rustc` while this runs in `rustdoc`, which is preferred? I guess running everything in `rustc` would allow for people to see the lint when not running `rustdoc`. Should I move my logic to `rustc`?

**Comment by GuillaumeGomez** [comment]
I'd personally say yes. When it's not lint about code improvements but warnings/errors, I think it should be in rustc directly. Opinion @rust-lang/rustdoc ?

**Comment by Manishearth** [comment]
Yeah, I think we should just put the lints directly in rustc

**Comment by jyn514** [comment]
I don't feel super strongly, as long as it's a lint and not a hard error putting it in rustc sounds fine.

**Comment by camelid** [comment]
Putting it in rustc seems good to me too, especially since the other doc attribute lints are in rustc.

**Comment by GuillaumeGomez** [comment]
@camelid Not all of them. When it's lint specific to rustdoc (for example, a codeblock has invalid tag), we lint in rustdoc. When it's based on rust syntax or in rustdoc attribute usage, we put them in rustc so that people can see the issue before running rustdoc so it doesn't appear out of nowhere.

**Comment by camelid** [comment]
> @camelid Not all of them. When it's lint specific to rustdoc (for example, a codeblock has invalid tag), we lint in rustdoc. When it's based on rust syntax or in rustdoc attribute usage, we put them in rustc so that people can see the issue before running rustdoc so it doesn't appear out of nowhere.

Yeah, that's what I meant by "doc attribute lints".

**Comment by jyn514** [comment]
Hi @LeSeulArtichaut, do you know when you'll get a chance to look at this?

**Comment by LeSeulArtichaut** [comment]
Sorry, I currently have no working computer, so I can't do anything at the moment. I'll make sure to come back to this as soon as I can

**Comment by jyn514** [comment]
I don't have time to look at this.

r? @Manishearth

**Review by Manishearth — APPROVED** [review]
Overall looks great, would love to have more doc comments

**Comment by LeSeulArtichaut** [comment]
@Manishearth Added a few doc comments in a separate commit

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
@bors r+

thanks!

**Comment by LeSeulArtichaut** [comment]
This is the only case of invalid `#[doc(inline)]` I found in `std::{os,sys}` so we should be good now
