### PR TITLE
Fix copy code example with line numbers

### LINKED ISSUE #150339: Do not include line numbers when copying code examples
## Unexpected behavior

1. Enable the "Show line numbers on code examples" option:

    Image

2. Copy the code by clicking "copy code to clipboard" in the upper right corner of a code example:
    
    Image

3. Paste the code somewhere, and you'll see **redundant** line numbers in the code:

    Image

## Expected behavior

Regardless of whether the "Show line numbers on code examples" option is enabled, *do not include line numbers* when copying code examples!

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#150339.

Since the line numbers are now included in the actual highlighted code, we need to filter them out when we "copy" the code.

r? @yotamofek

### CODE REVIEW

File: src/librustdoc/html/static/js/main.js [hunk 1]
```diff
@@ -2163,7 +2163,15 @@ function preLoadCss(cssUrl) {
             // Should never happen, but the world is a dark and dangerous place.
             return;
         }
-        copyContentToClipboard(codeElem.textContent);
+        let content = '';
+        for (const node of codeElem.childNodes) {
+            // We exclude line numbers.
+            if (node.hasAttribute && node.hasAttribute("data-nosnippet")) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/main.js]: If it's a text node (different than an element node), there is no `hasAttribute` method, so I need to check for its existence first before calling it. And if there is no such method, then we know it's ok to copy it.

File: src/librustdoc/html/static/js/main.js [hunk 2]
```diff
@@ -2163,7 +2163,15 @@ function preLoadCss(cssUrl) {
             // Should never happen, but the world is a dark and dangerous place.
             return;
         }
-        copyContentToClipboard(codeElem.textContent);
+        let content = '';
+        for (const node of codeElem.childNodes) {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/static/js/main.js:2167]: Since the line numbers can only be at the top-level of the DOM for code examples, we only need to check if it's a line number directly at the top.

File: src/librustdoc/html/static/js/main.js (hunk 1 above)
Comment (yotamofek) [reply src/librustdoc/html/static/js/main.js]: (asking due to ignorance..)

do you know why this code path doesn't go through the filtration of `[data-nosnippet]`s in the handler for the `copy` event? https://github.com/GuillaumeGomez/rust/blob/f556d51c1c83c559c4d89288aec1b39ddc033347/src/librustdoc/html/static/js/main.js#L2296-L2300

Seems to me like `copyContentToClipboard` is supposed to trigger that handler, and it sucks to have to impl the same logic twice.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: It's because the code you linked is triggered by doing `ctrl+c` (the `copy` event) whereas in this case the user clicks on a button we have to retrieve the text ourselves so it can be copied into user's clipboard. Kinda similar but different. :')

Comment (yotamofek) [reply src/librustdoc/html/static/js/main.js]: I assumed that `execCommand("copy")` would trigger that event, since it's supposed to mimic the user doing `ctrl+c`, but now I realize that even if that's true - `copyContentToClipboard` takes a string, so the event would also be getting a single text node.

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: Ah indeed, missed that. Yes, it's already broken before that point in this context. :wink:

**Comment by GuillaumeGomez** [comment]
Performance is very much secondary in here considering you don't click on "copy code" multiple times per second (I hope XD).

File: src/librustdoc/html/static/js/main.js (hunk 1 above)
Comment (spanishpear) [reply src/librustdoc/html/static/js/main.js]: Apologies in advance for the drive-by, was interested in the original issue. Just leaving this comment if it's helpful, please feel free to ignore if already considered!

> If it's a text node (different than an element node), there is no `hasAttribute` method, so I need to check for its existence first before calling it. And if there is no such method, then we know it's ok to copy it.

You _may_ be able to remove the ts-expect-error by filtering on `node.nodeType`  https://developer.mozilla.org/en/docs/Web/API/Node/nodeType

I.e. something like (optional probably not needed)
```ts
// If a text node, or has data-nosnippet then skip
if (node.nodeType !== nodeType.TEXT_NODE || node.hasAttribute?.("data-nosnippet")) { 
    continue; 
}
```
Though, typescripts type narrowing can be finicky, so if that isn't happy it may need a separate if statement 🥲 - I can maybe poke at it in a follow-up!

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: Oh, let me give it a try!

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: It fixed the issue, thanks for the tip!

**Comment by GuillaumeGomez** [comment]
Wut. Just tested locally and no error. I guess I use a different version...

File: src/librustdoc/html/static/js/main.js (hunk 1 above)
Comment (yotamofek) [reply src/librustdoc/html/static/js/main.js]: @spanishpear nice!

**Comment by GuillaumeGomez** [comment]
I tested using: `./x.py test tidy --extra-checks=js --stage 1`.

**Comment by yotamofek** [comment]
> Performance is very much secondary in here considering you don't click on "copy code" multiple times per second (I hope XD).

LOL
but I was thinking more of a hypothetical situation where copying 1MB of example code causes the browser to allocate 1GB of RAM for the piecemeal string concatenation.
(hypothetical, but still...)

**Comment by yotamofek** [comment]
> I tested using: `./x.py test tidy --extra-checks=js --stage 1`.

That's depressing 😅
Let me see if I can reproduce it locally

File: src/librustdoc/html/static/js/main.js (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: So it didn't in fact, my `ts` setup simply was wrong, @yotamofek told me how to fix it. So yeah, still the same. Gonna revert my changes then. :'(

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/main.js]: @yotamofek suggested instead:

```js
            if (node instanceof HTMLElement && node.hasAttribute("data-nosnippet")) {
```

Made ts and tests happy so let's go with it. =D
