### PR TITLE
rustdoc: Optimize and refactor doc link resolution

### LINKED ISSUE #96079: Compiler error on nightly `cargo doc` invocation on `fltk-rs` repository
### Code

```Rust
$ git clone https://github.com/fltk-rs/fltk-rs.git
$ git checkout a0402da3d160f55a5d41b1a8daec3d7a41f58fbc
$ cargo doc
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (e7575f967 2022-04-14)
binary: rustc
commit-hash: e7575f9670f3c837def3d186ae09366c75c7632e
commit-date: 2022-04-14
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Error output

(The whole backtrace is printed anyway, so I'm posting only the `cargo doc` output:

```
 Documenting fltk v1.3.5 (/tmp/fltk-rs/fltk)
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:976:16
stack backtrace:
   0:     0x7fcd713e496d - std::backtrace_rs::backtrace::libunwind::trace::h391ee3eb96720bb8
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fcd713e496d - std::backtrace_rs::backtrace::trace_unsynchronized::h8ac766d4ecc4f21c
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fcd713e496d - std::sys_common::backtrace::_print_fmt::h67120ae1638604b6
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fcd713e496d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h43d9264c5edad28c
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fcd7143efec - core::fmt::write::hb38509135e81eb46
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/core/src/fmt/mod.rs:1194:17
   5:     0x7fcd713d60c1 - std::io::Write::write_fmt::h68856f209e22f0a1
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/io/mod.rs:1655:15
   6:     0x7fcd713e7685 - std::sys_common::backtrace::_print::h2f4ffd98d72d3d6b
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fcd713e7685 - std::sys_common::backtrace::print::hca608482b4ab8751
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fcd713e7685 - std::panicking::default_hook::{{closure}}::h9ed02f27942ac2ac
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/panicking.rs:295:22
   9:     0x7fcd713e72f9 - std::panicking::default_hook::h632f45ebccdd2f92
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/panicking.rs:314:9
  10:     0x7fcd71b88051 - rustc_driver[8d2c61ed892e27c5]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fcd61147333 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha3e42d46fe255c46
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/alloc/src/boxed.rs:1880:9
  12:     0x7fcd611596dd - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h5530a261fac5a395
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/proc_macro/src/bridge/client.rs:335:21
  13:     0x7fcd713e7e56 - std::panicking::rust_panic_with_hook::h4565951773f90b0d
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/panicking.rs:702:17
  14:     0x7fcd713e7c57 - std::panicking::begin_panic_handler::{{closure}}::hc43ea5bc6ea479a7
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/panicking.rs:588:13
  15:     0x7fcd713e4e24 - std::sys_common::backtrace::__rust_end_short_backtrace::hce88d380b9b7207e
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7fcd713e7989 - rust_begin_unwind
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/panicking.rs:584:5
  17:     0x7fcd713ab933 - core::panicking::panic_fmt::h5088ed6a76740fc5
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/core/src/panicking.rs:142:14
  18:     0x7fcd7143be01 - core::panicking::panic_display::h1943abbc831ba687
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/core/src/panicking.rs:72:5
  19:     0x7fcd7143bdab - core::panicking::panic_str::h515e7e9b1ccc828a
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/core/src/panicking.rs:56:5
  20:     0x7fcd713ab7a6 - core::option::expect_failed::h940cf1bbf7d964ff
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/core/src/option.rs:1855:5
  21:     0x55a30525b349 - rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::resolve_associated_trait_item
  22:     0x55a305259aee - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  23:     0x55a305256cd5 - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector>::resolve
  24:     0x55a30525cc59 - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_item
  25:     0x55a30526ddaa - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_inner_recur
  26:     0x55a3052603d8 - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_item
  27:     0x55a30526dd2a - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_inner_recur
  28:     0x55a3052603bd - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_item
  29:     0x55a30526dd2a - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_inner_recur
  30:     0x55a3052603bd - <rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::LinkCollector as rustdoc[1fc6f13c0da15d8c]::visit::DocVisitor>::visit_item
  31:     0x55a30525528c - rustdoc[1fc6f13c0da15d8c]::passes::collect_intra_doc_links::collect_intra_doc_links
  32:     0x55a305303e27 - rustdoc[1fc6f13c0da15d8c]::main_options::{closure#0}::{closure#0}::{closure#1}
  33:     0x55a3052a3649 - <rustc_interface[ad68b8c89b0ab142]::passes::QueryContext>::enter::<rustdoc[1fc6f13c0da15d8c]::main_options::{closure#0}::{closure#0}::{closure#1}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>
  34:     0x55a3051f2979 - <rustc_interface[ad68b8c89b0ab142]::interface::Compiler>::enter::<rustdoc[1fc6f13c0da15d8c]::main_options::{closure#0}::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>
  35:     0x55a3053882da - rustc_span[58998adc3a002fd7]::with_source_map::<core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>, rustc_interface[ad68b8c89b0ab142]::interface::create_compiler_and_run<core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>, rustdoc[1fc6f13c0da15d8c]::main_options::{closure#0}>::{closure#1}>
  36:     0x55a3051f5334 - rustc_interface[ad68b8c89b0ab142]::interface::create_compiler_and_run::<core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>, rustdoc[1fc6f13c0da15d8c]::main_options::{closure#0}>
  37:     0x55a3050f238a - rustdoc[1fc6f13c0da15d8c]::main_options
  38:     0x55a305389d1b - <scoped_tls[5587684970d3e6f5]::ScopedKey<rustc_span[58998adc3a002fd7]::SessionGlobals>>::set::<rustdoc[1fc6f13c0da15d8c]::main_args::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>
  39:     0x55a30521d31f - std[965189dd79571a90]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ad68b8c89b0ab142]::util::run_in_thread_pool_with_globals<rustdoc[1fc6f13c0da15d8c]::main_args::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>
  40:     0x55a3052c5aa9 - <<std[965189dd79571a90]::thread::Builder>::spawn_unchecked_<rustc_interface[ad68b8c89b0ab142]::util::run_in_thread_pool_with_globals<rustdoc[1fc6f13c0da15d8c]::main_args::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>::{closure#0}, core[c15249dfec5bc62b]::result::Result<(), rustc_errors[b80d242712464baa]::ErrorGuaranteed>>::{closure#1} as core[c15249dfec5bc62b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fcd713f2033 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h051b06cc552f7ca2
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/alloc/src/boxed.rs:1866:9
  42:     0x7fcd713f2033 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0ed7e89ffdc39ab5
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/alloc/src/boxed.rs:1866:9
  43:     0x7fcd713f2033 - std::sys::unix::thread::Thread::new::thread_start::hf01169ad6dd2310f
                               at /rustc/e7575f9670f3c837def3d186ae09366c75c7632e/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7fcd7130a609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  45:     0x7fcd710b3163 - clone
  46:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (e7575f967 2022-04-14) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `fltk`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name fltk fltk/src/lib.rs -o /tmp/fltk-rs/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=554e9c97422d16fb -L dependency=/tmp/fltk-rs/target/debug/deps --extern bitflags=/tmp/fltk-rs/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern crossbeam_channel=/tmp/fltk-rs/target/debug/deps/libcrossbeam_channel-953c0c9c26457b2e.rmeta --extern fltk_sys=/tmp/fltk-rs/target/debug/deps/libfltk_sys-29c8541252091319.rmeta --extern paste=/tmp/fltk-rs/target/debug/deps/libpaste-85067c7f435fa569.so --extern ttf_parser=/tmp/fltk-rs/target/debug/deps/libttf_parser-d364752abb3e84e9.rmeta --crate-version 1.3.5` (exit status: 101)
```

### PR DESCRIPTION
**Pull request by petrochenkov**
One more subset of https://github.com/rust-lang/rust/pull/94857 that should bring perf improvements rather than regressions + a couple more optimizations on top of it.
It's better to read individual commits and their descriptions to understand the changes.
The `may_have_doc_links` optimization is not *very* useful here, but it's much more important for https://github.com/rust-lang/rust/pull/94857.

Closes https://github.com/rust-lang/rust/issues/96079

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems ike you're almost done in here! :D

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
This PR should be ready.

[tt-muncher](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/tt-muncher) seems to fluctuate a lot for reasons unrelated to this PR.
[stm32f4](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/stm32f4-0.14.0) has a huge number of items with doc attributes, so the ~0.4% regression from encoding metadata is an expected tradeoff for faster documentation generation.

File: compiler/rustc_ast/src/util/comments.rs [hunk 1]
```diff
@@ -24,6 +24,14 @@ pub struct Comment {
     pub pos: BytePos,
 }
 
+/// A fast conservative estimate on whether the string can contain documentation links.
+/// Doc links are markdown links (<https://spec.commonmark.org/0.30/#links>) so either
+/// a `[]` pair or `<>` pair must exist in the string.
+#[inline]
+pub fn may_have_doc_links(s: &str) -> bool {
+    s.contains(&['[', '<']) && s.contains(&[']', '>'])
```
Comment (GuillaumeGomez) [inline compiler/rustc_ast/src/util/comments.rs:32]: `<>` links aren't being used for intra doc links but only "as is".

**Comment by GuillaumeGomez** [comment]
Considering the amount of changes in intra-doc links, I'd feel better to have @jyn514 or @camelid taking a look too if possible.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_ast/src/util/comments.rs:32]: Apparently they still go through path resolution?
Because if they are filtered away then tests like `src/test/rustdoc-ui/intra-doc/email-address-localhost.rs` fail.
See https://github.com/rust-lang/rust/pull/83865#issuecomment-1100424663.

If we can change the behavior in cases like `email-address-localhost.rs` and skip comments with `<>`s but without `[]`s entirely that would be really great, because `<>`s are almost always false positives.

Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: What the hell... Do you want me to send a PR to remove `<>` check in intra-doc links? It wouldn't change much in here but it'd be still that less to worry about...

Comment (petrochenkov) [reply compiler/rustc_ast/src/util/comments.rs:32]: Yes, it would be ideal if links without `[]` never showed up in the output from `fn preprocess_link` or even `fn markdown_links`.

Comment (jyn514) [reply compiler/rustc_ast/src/util/comments.rs:32]: What? No, it's wrong and inconsistent to treat `[]` different from `<>`. Please don't break stable behavior.

Comment (petrochenkov) [reply compiler/rustc_ast/src/util/comments.rs:32]: On stable `<>` links don't show in the visible output tho.
It means they are removed from the output by some other pass.

Comment (jyn514) [reply compiler/rustc_ast/src/util/comments.rs:32]: Ok, I think I see what's going on. Pulldown-cmark only passes autolinks to rustdoc if it thinks they're already links, our `broken_link_callback` doesn't seem to be called. There's lots of existing buggy behavior around this, e.g.
```rust
/// <fn@localhost>
pub fn localhost() {}
```
generates a link to `mailto:fn.localhost.html` which is definitely wrong. We should investigate and fix those bugs before changing the behavior further.

File: library/proc_macro/Cargo.toml [hunk 2]
```diff
@@ -5,3 +5,7 @@ edition = "2021"
 
 [dependencies]
 std = { path = "../std" }
+# Workaround: when documenting this crate rustdoc will try to load crate named
+# `core` when resolving doc links. Without this line a different `core` will be
+# loaded from sysroot causing duplicate lang items and other similar errors.
+core = { path = "../core" }
```
Comment (jyn514) [inline library/proc_macro/Cargo.toml:11]: I wish I'd thought of this a year ago :( this is much simpler than https://github.com/rust-lang/rust/pull/86876 or https://github.com/rust-lang/rust/pull/75176. Good idea!

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -1041,16 +1050,29 @@ impl<'a, 'tcx> DocVisitor for LinkCollector<'a, 'tcx> {
         // Rather than merging all documentation into one, resolve it one attribute at a time
         // so we know which module it came from.
         for (parent_module, doc) in item.attrs.collapsed_doc_value_by_module_level() {
+            if !may_have_doc_links(&doc) {
+                continue;
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1055]: What is the goal of the short-circuiting here? Rustdoc has already loaded the attributes from disk. All this avoids is a call to `markdown_links`, but that function is both not very expensive and much more reliable than this check.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: It's worth a discussion apparently. :)

> On stable `<>` links don't show up in the visible output tho.
> It means they are removed from the output by some other pass.

Just to confirm @petrochenkov's words:

```
//! This is a super <https://crate.com> <Foo>.

pub struct Foo;
```

Gives:

Screenshot from 2022-04-18 16-07-21

@jyn514: Also, unlinke `[]`, `<>` can only be HTML links and we don't mention anywhere that they can be used for intra-doc links (based on https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html).

But you're right on fixing the other bugs first before deciding about this. What do you think should be done next?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -1041,16 +1050,29 @@ impl<'a, 'tcx> DocVisitor for LinkCollector<'a, 'tcx> {
...
+            }
             debug!("combined_docs={}", doc);
             // NOTE: if there are links that start in one crate and end in another, this will not resolve them.
             // This is a degenerate case and it's not supported by rustdoc.
             let parent_node = parent_module.or(parent_node);
-            for md_link in markdown_links(&doc) {
+            let mut tmp_links = self
+                .cx
+                .resolver_caches
+                .markdown_links
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1064]: Why are these cached? I wouldn't expect markdown parsing to be expensive compared to all the other things rustdoc does. If you look at https://perf.rust-lang.org/compare.html?start=1ec2c136b35bd4660cba778346f8df7daf2ab173&end=cd5dce912ebe17db000b68c530333a49ad85d462&stat=max-rss this also comes with a max-rss hit.

File: src/librustdoc/clean/types.rs [hunk 5]
```diff
@@ -1153,23 +1146,17 @@ impl Attributes {
...
-        for (i, new_frag) in self.doc_strings.iter().enumerate() {
-            let out = ret.entry(new_frag.parent_module).or_default();
-            add_doc_fragment(out, new_frag);
-            if i == last_index {
-                out.pop();
-            }
+    ///
+    /// The last newline is not trimmed so the produced strings are reusable between
+    /// early and late doc link resolution regardless of their position.
+    crate fn prepare_to_doc_link_resolution(&self) -> FxHashMap<Option<DefId>, String> {
```
Comment (jyn514) [inline src/librustdoc/clean/types.rs:1153]: at this point it may as well be in `collect_intra_doc_links.rs`; it's not reusable.

**Review by jyn514 — COMMENTED** [review]
I am confused that the caching was a performance improvement. Did you benchmark each of these changes locally?

anyway, didn't read the changes in detail, but overall they seem fine.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (jyn514) [reply compiler/rustc_ast/src/util/comments.rs:32]: I don't want to be responsible for this decision.

Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: It's not about being responsible but having your opinion on this topic. You are a very important rustdoc contributor and your opinion is highly respected. Hence why I'm asking you. You said "don't break stable behaviour" but it's already not supported for `<>` to be intra-doc links. So at this point, I think it'd be only logical to make it official, which would allow us some potential perf improvements. But maybe I missed something and it's why I want to hear your opinion. Then I can bring it up to the rest of the rustdoc team with all elements in hand.

File: library/proc_macro/Cargo.toml (hunk 2 above)
Comment (petrochenkov) [reply library/proc_macro/Cargo.toml:11]: Both https://github.com/rust-lang/rust/pull/86876 and https://github.com/rust-lang/rust/pull/75176 were helpful for other reasons though, like closing #56935 and improving performance.

**Comment by petrochenkov** [comment]
@jyn514 
>I am confused that the caching was a performance improvement. Did you benchmark each of these changes locally?

Yes, I benchmarked the changes on https://github.com/rust-lang/rust/pull/94857.
`markdown_links` is very expensive and is responsible for majority of runtime regression in https://github.com/rust-lang/rust/pull/94857, `preprocess_link` is also somewhat expensive.
So if there's an opportunity to not run them twice then it's better to use it.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 3 above)
Comment (petrochenkov) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1055]: It is expensive, https://github.com/rust-lang/rust/pull/96135#issuecomment-1101475868.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: I opened this [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Only.20support.20intra-doc.20links.20for.20.60.5B.5D.60) to talk about it.

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 4 above)
Comment (petrochenkov) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1064]: See https://github.com/rust-lang/rust/pull/96135#issuecomment-1101475868.

Many things in this area use `String`s while they could benefit from using `Symbol`s instead, maybe that can help with max-rss.

File: src/librustdoc/clean/types.rs (hunk 5 above)
Comment (petrochenkov) [reply src/librustdoc/clean/types.rs:1153]: It uses `add_doc_fragment` which is private, but I can make it more public if that's preferable.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (notriddle) [reply compiler/rustc_ast/src/util/comments.rs:32]: We should officially not support intra-doc links in `<>`. It’s not documented, it’s buggy, and the `<>` symbols are already painfully overloaded. What's supposed to happen when someone tries to use a `<b>` HTML tag, but they have a function named `b()` in scope?

Just to get across how confusing it is, *you both got it wrong.* `<Foo>` is not being parsed as an intra-doc link. It's an HTML tag. It's not getting stripped. It's right there in the generated HTML:

```html
<p>This is a super <a href="https://crate.com">https://crate.com</a> <Foo>.</p>
```

Comment (notriddle) [reply compiler/rustc_ast/src/util/comments.rs:32]: More importantly, the RFC says that auto-links shouldn't work: https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html#no-autolinks-style

**Comment by jyn514** [comment]
> markdown_links is very expensive and is responsible for majority of runtime regression in #94857

Got it. This is surprising to me, we should probably consider optimizing pulldown-cmark if possible. But no need to block your fixes on that.

File: compiler/rustc_ast/src/util/comments.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: If the RFC says it, then I'll send a PR to clean things up a bit.

Comment (petrochenkov) [reply compiler/rustc_ast/src/util/comments.rs]: Changed the condition to only consider square brackets.

File: src/librustdoc/clean/types.rs (hunk 5 above)
Comment (petrochenkov) [reply src/librustdoc/clean/types.rs:1153]: Left as is for now, because all other impls on `Attributes` are here, and because of `add_doc_fragment`.
Maybe later I'll eliminate it entirely by changing how `Attributes` are represented.

File: compiler/rustc_ast/src/util/comments.rs [hunk 6]
```diff
@@ -24,6 +24,14 @@ pub struct Comment {
     pub pos: BytePos,
 }
 
+/// A fast conservative estimate on whether the string can contain documentation links.
+/// A pair of square brackets `[]` must exist in the string, but we only search for the
+/// opening bracket because brackets always go in pairs in practice.
+#[inline]
+pub fn may_have_doc_links(s: &str) -> bool {
+    s.contains('[')
```
Comment (GuillaumeGomez) [inline compiler/rustc_ast/src/util/comments.rs:32]: Originally you checked for both `[` and `]`. Is there a reason why it's not the case anymore? (this is pure curiosity)

**Review by GuillaumeGomez — APPROVED** [review]

File: compiler/rustc_ast/src/util/comments.rs (hunk 6 above)
Comment (petrochenkov) [reply compiler/rustc_ast/src/util/comments.rs:32]: I left a comment about this above.
I collected some statistics from the standard library and the `[]` pair appeared exactly the same number of times as a single opening bracket `[` (about 4000 times, IIRC).
So if we are doing a conservative estimate we don't even need to check for the closing bracket, it's pretty much guaranteed to be there.

Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:32]: Sorry, I didn't see the change in the doc comments. Thanks for your answer. :)

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
Updated with the test from https://github.com/rust-lang/rust/pull/96216.

**Comment by Kobzol** [comment]
> markdown_links is very expensive and is responsible for majority of runtime regression in https://github.com/rust-lang/rust/pull/94857, preprocess_link is also somewhat expensive.

Are there any specific crates in the benchmark suite that use these doc links a lot? I can try to profile them and look for potential bottlenecks.

**Comment by GuillaumeGomez** [comment]
Thanks @petrochenkov ! Let's go then. :)

@bors: r+

**Comment by petrochenkov** [comment]
@Kobzol 
Standard library.
If you build rustdoc with https://github.com/rust-lang/rust/pull/94857 and run it on hello-world, you'll see `markdown_links` at the top of the profile inside `early_resolve_intra_doc_links`.
(It happens because with https://github.com/rust-lang/rust/pull/94857 rustdoc pulls impl items with their docs from dependency crates too eagerly.)

File: library/proc_macro/Cargo.toml (hunk 2 above)
Comment (camelid) [reply library/proc_macro/Cargo.toml:11]: Ooh, this might help with removing `BadImplStripper`...

**Comment by rylev** [comment]
@petrochenkov said:

> [stm32f4](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/stm32f4-0.14.0) has a huge number of items with doc attributes, so the ~0.4% regression from encoding metadata is an expected tradeoff for faster documentation generation.

Given that besides that benchmark, this is a win (and sometimes a big one), I'll mark this as triaged.

@rustbot label: +perf-regression-triaged
