### PR TITLE
handle spurious returns of `wait_timeout` in test

### LINKED ISSUE #147885: spurious test failures `condvar::nonpoison_timeout_nanoseconds`
happening since https://github.com/rust-lang/rust/pull/146503 it seems x86_64-mingw-1 , x86_64-msvc-1
cc @joboet 

https://github.com/rust-lang/rust/pull/147508#issuecomment-3412654785
https://github.com/rust-lang/rust/pull/147874#issuecomment-3419605042

```
2025-10-16T14:03:24.5908828Z failures:
2025-10-16T14:03:24.5909052Z 
2025-10-16T14:03:24.5909735Z ---- condvar::nonpoison_timeout_nanoseconds stdout ----
2025-10-16T14:03:24.5910121Z 
2025-10-16T14:03:24.5910856Z thread 'condvar::nonpoison_timeout_nanoseconds' (3328) panicked at library\std\tests\sync\condvar.rs:298:13:
2025-10-16T14:03:24.5912086Z assertion failed: *guard
2025-10-16T14:03:24.5912443Z stack backtrace:
2025-10-16T14:03:24.5912756Z    0: __rustc::rust_begin_unwind
2025-10-16T14:03:24.5913140Z    1: core::panicking::panic_fmt
2025-10-16T14:03:24.5913533Z    2: core::panicking::panic
2025-10-16T14:03:24.5913941Z    3: core::ops::function::FnOnce::call_once
2025-10-16T14:03:24.5914587Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2025-10-16T14:03:24.5915323Z ---- condvar::nonpoison_timeout_nanoseconds stdout end ----
2025-10-16T14:03:24.5915726Z 
2025-10-16T14:03:24.5915831Z failures:
2025-10-16T14:03:24.5916130Z     condvar::nonpoison_timeout_nanoseconds
2025-10-16T14:03:24.5916431Z 
2025-10-16T14:03:24.5916831Z test result: FAILED. 316 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out;
``

### PR DESCRIPTION
**Pull request by joboet**
Fixes https://github.com/rust-lang/rust/issues/147885
Closes https://github.com/rust-lang/rust/pull/147871

`wait_timeout` is allowed to spuriously return, hence the `timeout_nanoseconds` must not assume that the wakeup resulted from a `notify_all()`.

### CODE REVIEW

File: library/std/tests/sync/condvar.rs [hunk 1]
```diff
@@ -290,12 +290,18 @@ nonpoison_and_poison_unwrap_test!(
...
             });
 
-            let guard = maybe_unwrap(sent.lock());
-            // If there is internal overflow, this call will return almost
-            // immediately, before the other thread has reached the `notify_all`
-            let (guard, res) = maybe_unwrap(cond.wait_timeout(guard, Duration::from_secs(u64::MAX.div_ceil(1_000_000_000))));
-            assert!(!res.timed_out());
-            assert!(*guard);
+            let mut guard = maybe_unwrap(sent.lock());
+            loop {
```
Comment (ChrisDenton) [inline library/std/tests/sync/condvar.rs:301]: Could you add a comment about why the loop?

Comment (joboet) [reply library/std/tests/sync/condvar.rs:301]: Done.
