### PR TITLE
`rc""` more clear error message

### LINKED ISSUE #140170: `rc""` instead of `cr""` should get a clear diagnostic
### Code

```Rust
fn main() {
    rc"\n";
}
```

### Current output

```Shell
error: prefix `rc` is unknown
 --> src/lib.rs:2:5
  |
2 |     rc"\n";
  |     ^^ unknown prefix
  |
  = note: prefixed identifiers and literals are reserved since Rust 2021
help: consider inserting whitespace here
  |
2 |     rc "\n";
  |       +

error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `"\n"`
 --> src/lib.rs:2:7
  |
2 |     rc"\n";
  |       ^^^^ expected one of 8 possible tokens
```

### Desired output

```Shell
error: prefix `rc` is unknown
help: consider using `cr` instead:
```

### Rationale and extra context

not sure whether the combination of c-string and raw string is common, but this seems like a plausible mistake if it is

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.88.0-nightly (d6c1e454a 2025-04-21)
binary: rustc
commit-hash: d6c1e454aa8af5e7e59fbf5c4e7d3128d2f99582
commit-date: 2025-04-21
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kivooeo**
here is small fix that provides better error message when user is trying to use `rc""` the same way it was made for `rb""`

example of it's work

```rust
  |
2 |     rc"\n";
  |     ^^ unknown prefix
  |
  = note: prefixed identifiers and literals are reserved since Rust 2021
help: use `cr` for a raw C-string
  |
2 -     rc"\n";
2 +     cr"\n";
  |
```

**related issue**
fixes #140170

cc @cyrgani (issue author)

### CODE REVIEW

File: compiler/rustc_parse/src/lexer/mod.rs [hunk 1]
```diff
@@ -256,7 +256,6 @@ impl<'psess, 'src> Lexer<'psess, 'src> {
                     let lit_start = start + BytePos(prefix_len);
                     self.pos = lit_start;
                     self.cursor = Cursor::new(&str_before[prefix_len as usize..]);
-
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/lexer/mod.rs:259]: please don't remove unrelated lines

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+ rollup
