### PR TITLE
Enhance error message when misspelled label to value in break expression

### LINKED ISSUE #79424: [ER] Better error message for wrongly written break label
This is an enhancement request. This code is wrong because it lacks a ':

```rust
fn main() {
    'LOOP: for _ in 0 .. 9 {
        break LOOP;
    }
}
```

It gives the error messages (rustc 1.50.0-nightly 1c389ffef 2020-11-24):

```rust
error[E0425]: cannot find value `LOOP` in this scope
 --> ...test.rs:3:15
  |
3 |         break LOOP;
  |               ^^^^ not found in this scope

warning: unused label
 --> ...test.rs:2:5
  |
2 |     'LOOP: for _ in 0 .. 9 {
  |     ^^^^^
  |
  = note: `#[warn(unused_labels)]` on by default

error[E0571]: `break` with value from a `for` loop
 --> ...test.rs:3:9
  |
3 |         break LOOP;
  |         ^^^^^^^^^^ can only break with a value inside `loop` or breakable block
  |
help: instead, use `break` on its own without a value inside this `for` loop
  |
3 |         break;
  |         ^^^^^

error: aborting due to 2 previous errors; 1 warning emitted
```

But in such case I think it's better for the compiler to recognize in the error messages that the problem is probably just a lack of ' instead.

### PR DESCRIPTION
**Pull request by sasurau4**
Fix #79424

### CODE REVIEW

File: src/test/ui/loops/loop-break-value.rs [hunk 1]
```diff
@@ -90,4 +90,10 @@ fn main() {
         break; //~ ERROR mismatched types
         break 4;
     };
+
+    'LOOP: for _ in 0 .. 9 {
+        break LOOP;
```
Comment (pickfire) [inline src/test/ui/loops/loop-break-value.rs:95]:
```suggestion
        break LOOP;
```

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -542,6 +542,22 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
                 err.span_label(base_span, fallback_label);
             }
         }
+        if let Some(err_code) = &err.code {
+            if err_code == &rustc_errors::error_code!(E0425) {
+                for label_rib in &self.label_ribs {
+                    for (label_ident, _) in &label_rib.bindings {
+                        if format!("'{}", ident) == label_ident.to_string() {
+                            let msg = format!(
+                                "a label with a similar name exists: `{}`",
```
Comment (pickfire) [inline compiler/rustc_resolve/src/late/diagnostics.rs:551]: I think it would be better to suggest `missing ' to be used for label` rather than a label with similar ident. Maybe

> missing ' required for label: \`'{}'`

The message still doesn't seemed that good for me.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -542,6 +542,22 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
                 err.span_label(base_span, fallback_label);
             }
         }
+        if let Some(err_code) = &err.code {
+            if err_code == &rustc_errors::error_code!(E0425) {
```
Comment (pickfire) [inline compiler/rustc_resolve/src/late/diagnostics.rs:546]: Is it possible to do this?
```rust
        if let Some(&rustc_errors::error_code!(E0425)) = &err.code {
```

Comment (lcnr) [reply compiler/rustc_resolve/src/late/diagnostics.rs:546]: sadly not.
```rust
#[macro_export]
macro_rules! error_code {
    ($code:ident) => {{ $crate::DiagnosticId::Error(stringify!($code).to_owned()) }};
}
```

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_resolve/src/late/diagnostics.rs:551]: i think the error message is fine as is. I would prefer a `span_suggestion` here, as that should make this even clearer.

**Review by lcnr — COMMENTED** [review]
:heart: 

How does this interact with something like
```rust
fn main() {
    'qq: loop {
        qq;
    }
}
```
if we also emit this help there it probably makes sense to check the `source` to check if we are inside of a break expression.

File: compiler/rustc_resolve/src/late/diagnostics.rs (hunk 2 above)
Comment (sasurau4) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: I use `span_suggestion` instead :+1:

**Comment by sasurau4** [comment]
> if we also emit this help there it probably makes sense to `check` the source to check if we are inside of a break expression.
How to check that? When I look into `source`, it's `PathSource::Expr(None)`. Can I check if we are inside of a break expr with another way?

**Review by lcnr — APPROVED** [review]

**Comment by lcnr** [comment]
not actually sure, we probably should try harder to get a relevant `PathSource` here but that is not really trivial.

Considering that the suggestion can easily be incorrect I feel that a simple help message instead `span_suggestion` might actually be slightly preferable here :laughing: @sasurau4 how do you feel about this?

Am happy with whatever you end up prefering.

**Comment by sasurau4** [comment]
@lcnr OK, I'll try to get relevent `PathSource`.

For `span_suggestion`, it would be preferable for me rather than using `span_help`. When using `span_help`, I had to insert ident_label.name to message by format macro but it doesn't need when using `span_suggetion`. It seems better.

**Comment by sasurau4** [comment]
I look into `PathSource` and `parent_scope`, `PathSource`  have `Expr(None)` and seems not able to access parent `PathSource`. On the other hand, parent_scope has only module related method and field.
I have no idea to achieve it. I think it's enough even though without checking. How about it?

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 4]
```diff
@@ -542,6 +542,24 @@ impl<'a: 'ast, 'ast> LateResolutionVisitor<'a, '_, 'ast> {
...
+                for label_rib in &self.label_ribs {
+                    for (label_ident, _) in &label_rib.bindings {
+                        if format!("'{}", ident) == label_ident.to_string() {
+                            let msg = "a label with a similar name exists";
+                            err.span_suggestion(
```
Comment (lcnr) [inline compiler/rustc_resolve/src/late/diagnostics.rs:551]:
```suggestion
                            // FIXME: consider only emitting this suggestion if a label would be valid here
                            // which is pretty much only the case for `break` expressions.
                            err.span_suggestion(
```

**Comment by lcnr** [comment]
r=me afterwards

File: src/test/ui/label/label_misspelled.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
+fn main() {
+    'LOOP: loop {
+        LOOP;
+        //~^ ERROR cannot find value `LOOP` in this scope
+    };
+    'while_loop: while true { //~ WARN denote infinite loops with
```
Comment (pickfire) [inline src/test/ui/label/label_misspelled.rs:6]: Just wondering, is the recommended label capitalization `SCREAMING_SNAKE_CASE` or `snake_case`?

Comment (lcnr) [reply src/test/ui/label/label_misspelled.rs:6]: the recommended label is `snake_case` from what I know
