### PR TITLE
diagnostics: account for self type when looking for source of unsolved type variable

### LINKED ISSUE #109905: cannot infer type of the type parameter `'a` declared on the trait `Baz`
### Code

```Rust
use std::{borrow::Borrow, marker::PhantomData};

pub struct Foo<Borrowed, B> {
    borrowed: PhantomData<Borrowed>,
    y: B,
}

pub struct Bar<A, Borrowed, B, C> {
    x: PhantomData<A>,
    borrowed: PhantomData<Borrowed>,
    y: PhantomData<B>,
    z: C,
}

pub trait Baz<'a, D, B> {
    fn baz(&'a self) -> &'a B;
}

impl<'a, A, Borrowed, B, C> Baz<'a, Bar<A, Borrowed, B, C>, Borrowed> for C
where
    B: Borrow<Borrowed> + 'a,
    C: Borrow<Foo<Borrowed, B>>,
{
    fn baz(&'a self) -> &'a Borrowed {
        self.borrow().y.borrow()
    }
}

// fn foobar<Borrowed, B>(foo: &Foo<Borrowed, B>)
// where
//     B: Borrow<Borrowed>,
// {
//     foo.baz();
// }

fn foobar<'a, Borrowed, B>(foo: &'a Foo<Borrowed, B>)
where
    B: Borrow<Borrowed>,
{
    <Foo<Borrowed, B> as Baz<'a, _, _>>::baz(foo);
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
release: 1.66.1
LLVM version: 15.0.2
```

This was also tried on with `1.70.0-nightly (2023-04-02 3a8a131e9509c478ece1)` on Rust Playground, with the same error.

### Error output

```
error[E0282]: type annotations needed
  --> src/lib.rs:40:5
   |
40 |     <Foo<Borrowed, B> as Baz<'a, _, _>>::baz(foo);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `'a` declared on the trait `Baz`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0282]: type annotations needed
  --> src/lib.rs:40:5
   |
40 |     <Foo<Borrowed, B> as Baz<'a, _, _>>::baz(foo);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `'a` declared on the trait `Baz`
```

</p>
</details>

### Note

Without the fully qualified path, see commented code, the error is `error[E0282]: type annotations needed`.

### PR DESCRIPTION
**Pull request by fmease**
Fixes #109905.

When searching for the source of an unsolved infer var inside of a list of generic args, we look through the `tcx.generics_of(…).own_substs(…)` which *skips* the self type if present. However, the computed `argument_index` is later[^1] used to index into `tcx.generics_of(…).params` which may still contain the self type. In such case, we are off by one when indexing into the parameters.

From now on, we account for this immediately after calling `own_substs` which keeps things local.

This also fixes the wrong output in the preexisting UI test `inference/need_type_info/concrete-impl.rs` which was overlooked. It used to claim that the *type of type parameter `Self`* couldn't be inferred in `<Struct as Ambiguous<_>>::method()` which of course isn't true: `Self` equals `Struct` here, `A` couldn't be inferred.

@rustbot label A-diagnostics

[^1]: https://github.com/rust-lang/rust/blob/f98a2718141593fbb8dbad10acc537786d748156/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L471

### CODE REVIEW

File: tests/ui/inference/need_type_info/concrete-impl.rs [hunk 1]
```diff
@@ -12,5 +12,7 @@ impl Ambiguous<Two> for Struct {}
 fn main() {
     <Struct as Ambiguous<_>>::method();
     //~^ ERROR type annotations needed
+    //~| cannot infer type of the type parameter `A`
     //~| ERROR type annotations needed
+    //~| cannot infer type of the type parameter `A`
```
Comment (fmease) [inline tests/ui/inference/need_type_info/concrete-impl.rs:17]: I've added the label as an error annotation to safeguard against future accidental overwrites via `--bless`. Let me know if you deem this unnecessary.

File: tests/ui/inference/need_type_info/issue-109905.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+    fn m(self) {}
+}
+
+fn main() {
+    #[cfg(qualified)]
+    <() as Trait<'static, _>>::m(());
+    //[qualified]~^ ERROR type annotations needed
+    //[qualified]~| cannot infer type of the type parameter `T`
+
+    #[cfg(unqualified)]
```
Comment (petrochenkov) [inline tests/ui/inference/need_type_info/issue-109905.rs:20]: Why does this test need revisions and cfgs?
I think it can report both errors at the same time, without cfgs.

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs [hunk 3]
```diff
@@ -1191,11 +1191,14 @@ impl<'a, 'tcx> Visitor<'tcx> for FindInferSourceVisitor<'a, 'tcx> {
                 have_turbofish,
             } = args;
             let generics = tcx.generics_of(generics_def_id);
-            if let Some(argument_index) = generics
+            if let Some(mut argument_index) = generics
                 .own_substs(substs)
                 .iter()
                 .position(|&arg| self.generic_arg_contains_target(arg))
             {
+                if generics.parent.is_none() && generics.has_self {
```
Comment (petrochenkov) [inline compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:1199]: Is the situation `generics.parent.is_some() && generics.has_self` possible?
What happens in that case?

File: tests/ui/inference/need_type_info/concrete-impl.rs (hunk 1 above)
Comment (petrochenkov) [reply tests/ui/inference/need_type_info/concrete-impl.rs:17]: Seems fine.

Comment (petrochenkov) [inline tests/ui/inference/need_type_info/concrete-impl.rs:17]:
```suggestion
    //~| NOTE cannot infer type of the type parameter `A`
```

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:1199]: It shouldn't ever happen. I'd be fine with adding an assertion here, or just remove the check for `generics.parent.is_none()` altogether.

File: tests/ui/inference/need_type_info/issue-109905.rs (hunk 2 above)
Comment (fmease) [reply tests/ui/inference/need_type_info/issue-109905.rs:20]: Only one of two errors is shown when I remove the `cfg`s. See for yourself: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9ffa0073cb6a0b0cd3dac37867b8ae76).  They seem to be resolved in different passes.

`cfg` is probably overkill for this test, I'm gonna put the two paths into two different functions which also fixes the problem.

File: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs (hunk 3 above)
Comment (fmease) [reply compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:1199]: I couldn't conjure up such a case either. `own_substs` also checks for `parent` and so do a lot of other places that query `has_self`. I just followed suit.

I can remove the check.

**Comment by fmease** [comment]
> Is the situation generics.parent.is_some() && generics.has_self possible?

The CI test failures explain it lol. Going back to checking the `parent` …

**Comment by fmease** [comment]
> Is the situation generics.parent.is_some() && generics.has_self possible?

I've looked at the implementation of `tcx.generics_of` and `has_self` can also be true if the *parent* `has_self` in which case the *own arguments* (as returned by `generics.own_substs(…)`) do not contain the self type in the first position and thus in that case we shouldn't offset the index.

Looking at `(vec![1,2,3]).into_iter().sum()` in test `tests/ui/span/type-annotations-needed-expr.rs` for example where we cannot infer param `S` on method `sum`, `generics.parent` is `Some(Iterator_def_id)` but the `generics.params` only contains param `S` and notably not the self type. The parent – the trait `Iterator` – has the self type and thus `generics.has_self` is true.

<details>
<summary>relevant definitions</summary>

* `generics.parent`: `DefId(2:7268 ~ core[280a]::iter::traits::iterator::Iterator)`
* `generics.has_self`: `true`
* `generics.params`: `["S"]` (w/o self type)
* `substs`: `[std::vec::IntoIter<i32>, _#20t]`
* `generics.own_substs_no_defaults(substs)`: `[_#20t]`

</details>
