### PR TITLE
Fix the issue of unused assignment from MIR liveness checking

### LINKED ISSUE #148418: Regression (?) in unused_assignments lint when Drop is implemented
I've only tried two versions available on rust playground.

I'm not quite sure what behaviour is better or worse, but a change between stable and beta is at least worth mentioning in changelogs. I have not found any relevant issues about `unused_assignments` lint change, so I believe this may be in fact unintended.

I've noticed that when my `cargo check` have failed in CI (running stable), but succeeded locally (running nightly).

### Code

I tried this code:

```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {}
}

fn main() {
    let mut foo = Foo;
    foo = Foo;
}
```

I expected to see this happen:
```
warning: variable `foo` is assigned to, but never used
 --> src/main.rs:8:13
  |
8 |     let mut foo = Foo;
  |             ^^^
  |
  = note: consider using `_foo` instead
  = note: `#[warn(unused_variables)]` (part of `#[warn(unused)]`) on by default
help: you might have meant to pattern match on the similarly named struct `Foo` (notice the capitalization)
  |
8 -     let mut foo = Foo;
8 +     let mut Foo = Foo;
  |

warning: value assigned to `foo` is never read
 --> src/main.rs:9:5
  |
9 |     foo = Foo;
  |     ^^^
  |
  = help: maybe it is overwritten before being read?
  = note: `#[warn(unused_assignments)]` (part of `#[warn(unused)]`) on by default
```

Instead, this happened: (no warnings)
```
   Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/playground`
```

### Version it worked on

It most recently worked on: `1.91.0`

### Version with regression

```
1.92.0-beta.2 (2025-10-31 0a411606e9cc00588c83)
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### LINKED ISSUE #148960: unused_assignments not shown for vec overwrite - Rust 1.92.0-beta.3
### Summary

Clippy shipped with Rust 1.92.0-beta.3 doesn't report unused_assignments when a vector is initialized and then replaced with another value unconditionally.

### Lint Name

unused_assignments

### Reproducer

I tried this code:

```rust
fn main() {
    let mut value = b"0".to_vec();
    value = b"1".to_vec();
    println!("{:?}", value);
}
```

I expected to see this happen:

```
$ cargo +stable clippy
warning: value assigned to `value` is never read
 --> src/main.rs:2:13
  |
2 |     let mut value = b"0".to_vec();
  |             ^^^^^
  |
  = help: maybe it is overwritten before being read?
  = note: `#[warn(unused_assignments)]` (part of `#[warn(unused)]`) on by default
```

Instead, this happened:

```
$ cargo +beta clippy
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
```

Nightly is affected too.

### Version

```text
rustc 1.92.0-beta.3 (f3f12444a 2025-11-09)
binary: rustc
commit-hash: f3f12444a017add0468f683f3a10656d29438a05
commit-date: 2025-11-09
host: x86_64-unknown-linux-gnu
release: 1.92.0-beta.3
LLVM version: 21.1.3
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#148960
Fixes rust-lang/rust#148418

r? @davidtwco 

cc @cjgillot 

My first try on MIR related code, so it may not be the best fix.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/liveness.rs [hunk 1]
```diff
@@ -1048,26 +1052,41 @@ impl<'a, 'tcx> AssignmentResult<'a, 'tcx> {
...
-            for (source_info, Access { live, kind }) in statements.into_iter().rev() {
+            for (source_info, Access { live, kind, is_direct }) in statements.into_iter().rev() {
                 if live {
                     continue;
                 }
 
+                // If this place was dropped and has non-trivial drop,
+                // skip reporting field assignments.
+                if !is_direct && is_maybe_drop_guard {
+                    continue;
```
Comment (chenyukang) [inline compiler/rustc_mir_transform/src/liveness.rs:1077]: this is for avoiding report `unused_assign` for this line of code:
https://github.com/rust-lang/rust/blob/main/library/std/src/io/mod.rs#L393

File: compiler/rustc_mir_transform/src/liveness.rs
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/liveness.rs:665]: Should we update `direct` too?

File: compiler/rustc_mir_transform/src/liveness.rs [hunk 2]
```diff
@@ -1048,26 +1052,41 @@ impl<'a, 'tcx> AssignmentResult<'a, 'tcx> {
...
+            let is_pure_drop_guard = is_maybe_drop_guard && {
+                // Check if ALL direct assignments are not live
+                // which meaning the place is never read
+                statements
+                    .values()
+                    .filter(|access| access.kind == AccessKind::Assign && access.is_direct)
+                    .all(|access| !access.live)
+            };
+
+            if is_pure_drop_guard {
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/liveness.rs]: I'm not sure which kind of snippet this is targetting. Do you mind adding an example in a comment?

**Review by cjgillot — COMMENTED** [review]
I wonder about a more principled fix. Instead of trying guess is this is a drop guard when emitting the diagnostic, should we change the dataflow analysis to make the `Drop` terminator mark live on *interesting* types? Maybe as a follow-up...

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149072/3d461af2a23456a2676aadb13b4253c87bdfe28d..57c1dcf945cb885a28b560fd14aa6fb7e964cc34)*

File: compiler/rustc_mir_transform/src/liveness.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs]: this is redundant check, I removed it now.

File: compiler/rustc_mir_transform/src/liveness.rs
Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs:665]: yeah, I fixed it and added a test case.

File: compiler/rustc_mir_transform/src/liveness.rs (hunk 1 above)
Comment (bjorn3) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: Why would there be an `unused_assign` for that line irrespective of whether there is a `Drop` impl?

Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: If there's no subsequent code that explicitly reads `g.len`, this assignment appears "unused".

I think the liveness checking in MIR only knows that the entire `g` will be dropped, but doesn't know the drop process will read `g.len`. The `is_direct` here is used to distinguish this case and avoid false positives for field assignments that Drop may use.

Comment (bjorn3) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: In the past fields weren't checked, only whole variables, right? Why was that changed?

Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: The indirect statement is added here:

https://github.com/chenyukang/rust/blob/4930d3e6129b17538e687f97c3b3f3e0dcaea76f/compiler/rustc_mir_transform/src/liveness.rs#L656-L661

it seems to be trying to record the access for a variable with a field:

```rust
let mut waiter_queue = .... ; 
...

waiter_queue.set_state_on_drop_to = ..
```

@cjgillot correct me if I'm wrong.

Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: another issue which related to Drop, but this PR does not fix it:

https://github.com/rust-lang/rust/issues/148418

maybe we need a more general fix.

Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs:1077]: I added a new commit for this PR to fix #148418

https://github.com/rust-lang/rust/pull/149072/commits/00f3155794f40030249a36b4abb09906b6e8fa5d

I double checked the changes for testcase `tests/ui/drop/or-pattern-drop-order.stderr`, it's now the same with stable branch.

**Review by davidtwco — APPROVED** [review]
