### PR TITLE
can_begin_literal_maybe_minus: `true` on `"-"? lit` NTs.

### LINKED ISSUE #70050: Negative numbers are not correctly identified as literals inside macros
Negative numbers are no longer parsed as literals when used as a parameter to a macro inside a macro. This appears to be a regression from stable to nightly.

According to cargo-bisect-rustc, https://github.com/rust-lang/rust/pull/69023 is responsible (thanks to @jebrosen for helping with this on the Rust discord)
Specifically, the changes to [this function](https://github.com/rust-lang/rust/pull/69023/files#diff-cd934bf3d344974edb4b4bbad00a60c2R407) look suspicious.

The below fails to compile:
```rust
macro_rules! foo {
    ($a:literal) => {
        bar!($a)
    }
}

macro_rules! bar {
    ($b:literal) => {}
}

fn main() {
    // fails on nightly, but not stable
    foo!(-2);
    // doesn't fail
    bar!(-2);
}
```

with the following error on nightly-2020-02-14,

```
~ >cargo b
error: no rules expected the token `-2`
  --> src\main.rs:3:14
   |
3  |         bar!($a)
   |              ^^ no rules expected this token in macro call
...
7  | macro_rules! bar {
   | ---------------- when calling this macro
...
12 |     foo!(-2);
   |     --------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by Centril**
Make `can_begin_literal_or_bool` (renamed to `can_begin_literal_maybe_minus`) accept `NtLiteral(e) | NtExpr(e)` where `e` is either a literal or a negated literal.

Fixes https://github.com/rust-lang/rust/issues/70050.

r? @petrochenkov

### CODE REVIEW

File: src/librustc_ast/token.rs [hunk 1]
```diff
@@ -448,13 +448,22 @@ impl Token {
     /// Returns `true` if the token is any literal, a minus (which can prefix a literal,
     /// for example a '-42', or one of the boolean idents).
     ///
-    /// Keep this in sync with `Lit::from_token`.
+    /// In other words, would this token be a valid start of `parse_literal_maybe_minus`?
+    ///
+    /// Keep this in sync with and `Lit::from_token`, excluding unary negation.
     pub fn can_begin_literal_or_bool(&self) -> bool {
```
Comment (petrochenkov) [inline src/librustc_ast/token.rs]:
```suggestion
    pub fn can_begin_literal_maybe_minus(&self) -> bool {
```
This should probably be renamed to avoid surprises.

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/23763weeklymeeting2020031954818.html#191118334) at T-compiler meeting. beta-accepted.

File: src/librustc_ast/token.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_ast/token.rs]: Done.
