### PR TITLE
Pretty printing give proper error message without panic

### LINKED ISSUE #100770: rustc panics if output is set to directory while pretty printing
`rustc 1.65.0-nightly (0b79f758c 2022-08-18)`

If you `rustc ./a.rs -o/tmp/`, you get a normal error like
````
error: the generated executable for the input file "./a.rs" conflicts with the existing directory "/tmp/"

error: aborting due to previous error
````
but if you try to `-Zunpretty` at the same time: `rustc ./a.rs -o/tmp/ -Zunpretty=ast-tree`
rust will panic which is a bit weird. Mayne that panic should be demoted to a regular error?

````
thread 'rustc' panicked at 'print-print failed to write /tmp/ due to Is a directory (os error 21)', compiler/rustc_driver/src/pretty.rs:365:17
stack backtrace:
   0:     0x7f338bdd86d0 - std::backtrace_rs::backtrace::libunwind::trace::hdc27bfa6aa97f84d
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f338bdd86d0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd260a87da0307fa5
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f338bdd86d0 - std::sys_common::backtrace::_print_fmt::h789cb96c4a337f2c
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f338bdd86d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h36bc3de3612a60f5
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f338be3376e - core::fmt::write::h2db4bfe92ef037b0
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f338bdc94d5 - std::io::Write::write_fmt::hcd345fc714a96537
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/io/mod.rs:1672:15
   6:     0x7f338bddb393 - std::sys_common::backtrace::_print::hcf53c28899e66110
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f338bddb393 - std::sys_common::backtrace::print::hd8ec3e1ae139ef7a
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f338bddb393 - std::panicking::default_hook::{{closure}}::he70b99e2f9e5bd44
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/panicking.rs:295:22
   9:     0x7f338bddb07f - std::panicking::default_hook::h8d91a23b91011754
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/panicking.rs:314:9
  10:     0x7f338e61a644 - <rustc_driver[d9adb13473fd7853]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[97bb3a13db18d0cb]::ops::function::FnOnce<(&core[97bb3a13db18d0cb]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f338bddbbcd - std::panicking::rust_panic_with_hook::h5af783bc1124b2c1
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/panicking.rs:702:17
  12:     0x7f338bddba27 - std::panicking::begin_panic_handler::{{closure}}::h234d8ef84a25d2ee
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/panicking.rs:588:13
  13:     0x7f338bdd8bdc - std::sys_common::backtrace::__rust_end_short_backtrace::he0cdebe1a4227e87
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f338bddb742 - rust_begin_unwind
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/panicking.rs:584:5
  15:     0x7f338be30283 - core::panicking::panic_fmt::hfb889492842f4bec
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/core/src/panicking.rs:142:14
  16:     0x7f338e6117cc - rustc_driver[d9adb13473fd7853]::pretty::write_or_print
  17:     0x7f338e611911 - rustc_driver[d9adb13473fd7853]::pretty::print_after_parsing
  18:     0x7f338ddf1b52 - <rustc_interface[67a969eeca26ae2c]::interface::Compiler>::enter::<rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}::{closure#2}, core[97bb3a13db18d0cb]::result::Result<core[97bb3a13db18d0cb]::option::Option<rustc_interface[67a969eeca26ae2c]::queries::Linker>, rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>
  19:     0x7f338dded1bc - rustc_span[8d4f92e92ba5c24b]::with_source_map::<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_interface[67a969eeca26ae2c]::interface::create_compiler_and_run<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}>::{closure#1}>
  20:     0x7f338ddecba2 - rustc_interface[67a969eeca26ae2c]::interface::create_compiler_and_run::<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}>
  21:     0x7f338ddeb741 - <scoped_tls[e4311800d1c0ff57]::ScopedKey<rustc_span[8d4f92e92ba5c24b]::SessionGlobals>>::set::<rustc_interface[67a969eeca26ae2c]::interface::run_compiler<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}>::{closure#0}, core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>
  22:     0x7f338ddeb42f - std[e5af5fec29962f4a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[67a969eeca26ae2c]::util::run_in_thread_pool_with_globals<rustc_interface[67a969eeca26ae2c]::interface::run_compiler<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}>::{closure#0}, core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>::{closure#0}, core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>
  23:     0x7f338e441e79 - <<std[e5af5fec29962f4a]::thread::Builder>::spawn_unchecked_<rustc_interface[67a969eeca26ae2c]::util::run_in_thread_pool_with_globals<rustc_interface[67a969eeca26ae2c]::interface::run_compiler<core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>, rustc_driver[d9adb13473fd7853]::run_compiler::{closure#1}>::{closure#0}, core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>::{closure#0}, core[97bb3a13db18d0cb]::result::Result<(), rustc_errors[713e2db940a8ff0d]::ErrorGuaranteed>>::{closure#1} as core[97bb3a13db18d0cb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f338bde59c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h374ee76b025338a5
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/alloc/src/boxed.rs:1935:9
  25:     0x7f338bde59c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2bee731a5ba86295
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/alloc/src/boxed.rs:1935:9
  26:     0x7f338bde59c3 - std::sys::unix::thread::Thread::new::thread_start::h44c172ae3f11ec1f
                               at /rustc/0b79f758c9aa6646606662a6d623a0752286cd17/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f338bb4278d - <unknown>
  28:     0x7f338bbc38e4 - clone
  29:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (0b79f758c 2022-08-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=ast-tree

query stack during panic:
end of query stack
````

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #100770

### CODE REVIEW

File: compiler/rustc_driver/src/pretty.rs [hunk 1]
```diff
@@ -362,7 +362,8 @@ fn write_or_print(out: &str, ofile: Option<&Path>) {
         None => print!("{}", out),
         Some(p) => {
             if let Err(e) = std::fs::write(p, out) {
-                panic!("print-print failed to write {} due to {}", p.display(), e);
+                eprintln!("print-print failed to write {} due to `{}`", p.display(), e);
+                std::process::exit(1);
```
Comment (estebank) [inline compiler/rustc_driver/src/pretty.rs:366]: Instead of this, what you'd want to do is to pass in `sess: Session` into `write_or_print` and use the diagnostic machinery (`sess.struct_fatal(&format!("pretty-print failed to write {} due to `{e}`", p.display())`).

**Comment by petrochenkov** [comment]
Could you add a test for this (to `src/test/ui/unpretty`)?
@rustbot  author

**Comment by chenyukang** [comment]
> Could you add a test for this (to `src/test/ui/unpretty`)? @rustbot author

Done!

**Comment by chenyukang** [comment]
oops, need to resolve rebase issue.

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/101137#issuecomment-1229700581

**Comment by chenyukang** [comment]
> @bors r- failed in a rollup [#101137 (comment)](https://github.com/rust-lang/rust/pull/101137#issuecomment-1229700581)

The error message in Windows is a little bit different with Linux.

**Comment by chenyukang** [comment]
I added a `#only-linux` in the new testcase.

**Comment by petrochenkov** [comment]
@bors r-

Although it's better to remove this message from the test output entirely, using `// normalize-stderr-test`.
It's still brittle and may fail depending on locale and may be some other factors.

**Comment by chenyukang** [comment]
> @bors r-
> 
> Although it's better to remove this message from the test output entirely, using `// normalize-stderr-test`. It's still brittle and may fail depending on locale and may be some other factors.

Agree, just know we have `normalize-stderr-test`, I will update it.

**Comment by khyperia** [comment]
Hmm, the `avoid-crash.rs` test appears to be failing for me (as in, compilation incorrectly succeeds) - I'm on windows, and have checked out rust on my `D:` drive.

<details>
  <summary>Click to expand output of me running `./x.py test src/test/ui --test-args avoid-crash`</summary>
  
```
D:\src\rust> ./x.py test src/test/ui --test-args avoid-crash
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.12s
Building stage0 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.43s
Copying stage0 std from stage0 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Building stage0 compiler artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.76s
Copying stage0 rustc from stage0 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Assembling stage1 compiler (x86_64-pc-windows-msvc)
Building stage1 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.43s
Copying stage1 std from stage1 (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc / x86_64-pc-windows-msvc)
Building stage0 tool compiletest (x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.44s
Check compiletest suite=ui mode=ui (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)

running 1 test
F
failures:

---- [ui] src/test\ui\unpretty\avoid-crash.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: PATH="D:\src\rust\build\x86_64-pc-windows-msvc\stage1\bin;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64;D:\src\rust\build\x86_64-pc-windows-msvc\stage0-bootstrap-tools\x86_64-pc-windows-msvc\release\deps;D:\src\rust\build\x86_64-pc-windows-msvc\stage0\bin;C:\Program Files\PowerShell\7;C:\Python310\Scripts\;C:\Python310\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\OpenJDK\jdk-18.0.2\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;C:\Program Files\Perforce\;C:\Users\khype\.cargo\bin;C:\Users\khype\AppData\Local\Microsoft\WindowsApps;C:\Users\khype\Documents\unison\bin;C:\tools\neovim\Neovim\bin;C:\Users\khype\.dotnet\tools;C:\tools\neovim\nvim-win64\bin;;C:\Users\khype\AppData\Local\Programs\Microsoft VS Code\bin" "D:\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\bin\\rustc.exe" "D:\\src\\rust\\src/test\\ui\\unpretty\\avoid-crash.rs" "-Zthreads=1" "--target=x86_64-pc-windows-msvc" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "D:\\src\\rust\\build\\x86_64-pc-windows-msvc\\test\\ui\\unpretty\\avoid-crash" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=D:\\src\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "-Clink-arg=-Wl,/threads:1" "-Clinker=D:\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\lib\\rustlib\\x86_64-pc-windows-msvc\\bin\\rust-lld" "-o/tmp/" "-Zunpretty=ast-tree" "-L" "D:\\src\\rust\\build\\x86_64-pc-windows-msvc\\test\\ui\\unpretty\\avoid-crash\\auxiliary"
stdout: none
stderr: none



failures:
    [ui] src/test\ui\unpretty\avoid-crash.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 13561 filtered out; finished in 0.05s

Some tests failed in compiletest suite=ui mode=ui host=x86_64-pc-windows-msvc target=x86_64-pc-windows-msvc
Build completed unsuccessfully in 0:00:19
```

</details>

I noticed that this created a file called `D:\tmp` (the test has `compile-flags: -o/tmp/ -Zunpretty=ast-tree`):

```
D:\> cat tmp
Crate {
    attrs: [],
    items: [
        Item {
            attrs: [],
            id: NodeId(4294967040),
            span: D:\src\rust\src/test\ui\unpretty\avoid-crash.rs:4:1: 4:13 (#0),
[... I truncated the file ...]
```

My theory is that this passed the Windows CI build because there's perhaps a `C:\tmp\` directory that already exists (which makes compilation fail, i.e. the test passes), or that it has a checkout on the `C:` drive instead of some `D:` drive and has a permission error when creating the `C:\tmp` file.

Let me know if you'd like any more information, or if you'd like me to run more tests to figure out what's going on! :heart:

**Comment by chenyukang** [comment]
@khyperia Thanks for pointing this out.
Yes, if the directory has already existed(like `/tmp/` in Linux), the test case will pass, since created it will fail.

I thought `/tmp/` will always be a invalid for Windows... so it will also fail when creating it.
I don't have a PC right now, could you please make a fix on it? Thanks!

**Comment by khyperia** [comment]
> I don't have a PC right now, could you please make a fix on it? Thanks!

Unfortunately I'm not sure what the right fix is!
