### PR TITLE
Fix an extra newline in rendered std doc

### LINKED ISSUE #132564: Weird formatting on documentation of "Summary" button
location: https://doc.rust-lang.org/nightly/std/#how-to-read-this-documentation

I believe this issue comes from using an `svg` element inside a `code` element.

Image

### PR DESCRIPTION
**Pull request by uellenberg**
Fixes #132564

(taken from the issue above)

The problem with the formatting is due to that newline between `<code>` and `<svg>`. Any newlines outside of the code (i.e., within elements inside of it) are fine.

### CODE REVIEW

File: library/std/src/lib.rs [hunk 1]
```diff
@@ -32,9 +32,8 @@
 //!
 //! Once you are familiar with the contents of the standard library you may
 //! begin to find the verbosity of the prose distracting. At this stage in your
-//! development you may want to press the <code>
-//! <svg style="width:0.75rem;height:0.75rem" viewBox="0 0 12 12"
-//! stroke="currentColor" fill="none">
+//! development you may want to press the <code><svg style="width:0.75rem;height:0.75rem"
+//! viewBox="0 0 12 12" stroke="currentColor" fill="none">
 //! <path d="M2,2l4,4l4,-4M2,6l4,4l4,-4"/></svg> Summary</code> button near the
```
Comment (workingjubilee) [inline library/std/src/lib.rs:37]: does it format correctly if we just move all the HTML elements to the same line and then resume text on the next?

Comment (uellenberg) [reply library/std/src/lib.rs]: Yes, although the line ends up quite long. I've pushed a commit showing it, and can revert it line length is an issue.

Comment (workingjubilee) [reply library/std/src/lib.rs]: Tidy seems to be okay with it.

...which is mildly surprising since it IS over 100 characters long...

**Comment by cuviper** [comment]
Why is it using `<code>` at all? The actual UI element looks like a regular sans font to me. I'd expect this to be in regular quotation marks, and maybe `&nbsp;` to connect the svg arrow.

Same for the `<code>source</code>` in the next paragraph -- I'd expect "Source" to quote and match the UI.

**Comment by uellenberg** [comment]
It's from #129545. I suppose using the code blocks makes them stand out more. Here's a before and after:
image
image

Let me know what you think, and I can swap it over.

**Comment by cuviper** [comment]
Hmm, it used to be bold **\[-\]** and **\[src\]**, but it looks like that was raising link warnings in https://github.com/rust-lang/rust/pull/49542#pullrequestreview-108530442, and code backticks were an easy escape.

I think the double-quotes look good, although please do capitalize "Source" as well. We could try bold again too.

**Comment by uellenberg** [comment]
There we go.

**Comment by cuviper** [comment]
Thanks!

@bors r+ rollup
