### PR TITLE
Run `eval_config_entry` on all branches so we always emit lints

### LINKED ISSUE #149090: `cfg_select` should check for `unexpected_cfgs` on other arms
Code:

```rust
#![feature(cfg_select)]

fn main() {
    let demo1 = cfg_select! {
        true => "valid",
        invalid_cfg1 => "invalid",
        _ => "fallback"
    };
    let demo2 = cfg_select! {
        invalid_cfg2 => "invalid",
        true => "valid",
        _ => "fallback"
    };
    dbg!(demo1, demo2);
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=170a24120aafa2dcf4d941fd1b189a56

Output:

```text
   Compiling playground v0.0.1 (/playground)
warning: unexpected `cfg` condition name: `invalid_cfg2`
  --> src/main.rs:10:9
   |
10 |         invalid_cfg2 => "invalid",
   |         ^^^^^^^^^^^^
   |
   = help: expected names are: `docsrs`, `feature`, and `test` and 31 more
   = help: consider using a Cargo feature instead
   = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
            [lints.rust]
            unexpected_cfgs = { level = "warn", check-cfg = ['cfg(invalid_cfg2)'] }
   = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(invalid_cfg2)");` to the top of the `build.rs`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `#[warn(unexpected_cfgs)]` on by default

warning: `playground` (bin "playground") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.60s
     Running `target/debug/playground`
[src/main.rs:14:5] demo1 = "valid"
[src/main.rs:14:5] demo2 = "valid"
```

Here we get a warning on `invalid_cfg2` since the invalid arm for `demo2` comes before the matched arm (`true`). Ideally we should get the same warning for `invalid_cfg1` because it also isn't a valid configuration: however, since `true` is hit first in the `demo2` case, the rest of the arms don't currently get checked.

Version: 1.93.0-nightly (2025-11-18 3d461af2a23456a2676a)

### PR DESCRIPTION
**Pull request by JonathanBrouwer**
Fixes https://github.com/rust-lang/rust/issues/149090

Ideally I'd have liked to fix this issue using https://github.com/rust-lang/rust/pull/149215, and this is still the long term plan, but this is slightly more annoying to implement than I'd have liked to, and this is also a nice and easy solution to the problem.

r? @tgross35

### CODE REVIEW

**Review by Urgau — COMMENTED** [review]
Looks good to me. r=me after addressing the comment

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149380/7b9905edb4df3aeaabd0d6cd0d4c09b183d7d965..a582d93a03c9f24c8138239ad3a83ebf6b3b516f)*

File: tests/ui/macros/cfg_select.rs [hunk 1]
```diff
@@ -95,3 +95,17 @@ cfg_select! {
...
+    //~^ WARN unexpected `cfg` condition name
+    _ => {}
+}
+
+cfg_select! {
+    invalid_cfg2 => {}
+    //~^ WARN unexpected `cfg` condition name
+    true => {}
+    _ => {}
+}
```
Comment (Urgau) [inline tests/ui/macros/cfg_select.rs]: Could you move those two tests inside the check-cfg test suite: `tests/ui/check-cfg/`.

Comment (JonathanBrouwer) [reply tests/ui/macros/cfg_select.rs]: Sure! That makes sense, thanks!
