### PR TITLE
Fix exhaustiveness in case a byte string literal is used at slice type

### LINKED ISSUE #79048: Incorrect "unreachable pattern" warning on nightly
I tried this code:

```rust
pub fn parse_data(data: &[u8]) -> u32 {
    match data {
        b"" => 1,
        _ => 2,
    }
}

fn main() {
    println!("{}", parse_data(b"asd"))
}
```

It produces the following, incorrect, warning:

```
warning: unreachable pattern
 --> src/main.rs:4:9
  |
4 |         _ => 2,
  |         ^
  |
  = note: `#[warn(unreachable_patterns)]` on by default
```

however, the output is `2` so it's clearly incorrect

### Meta

`rustc --version`:
```
1.50.0-nightly (2020-11-13 74f7e32f43b5fb0f8389)
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #79048

### CODE REVIEW

File: compiler/rustc_middle/src/ty/context.rs [hunk 1]
```diff
@@ -418,6 +418,12 @@ pub struct TypeckResults<'tcx> {
     /// Stores the type, expression, span and optional scope span of all types
     /// that are live across the yield of this generator (if a generator).
     pub generator_interior_types: Vec<GeneratorInteriorTypeCause<'tcx>>,
+
+    /// We treat byte string literals as polymorphic over their type. This means
+    /// they are simultaneously `&[u8]` and `&[u8; N]`, depending on the pattern
+    /// in which they are used. This hashset records all instances where we behave
+    /// like this to allow other code to reliably process this.
+    pub polymorphic_byte_string_literals: ItemLocalSet,
```
Comment (Nadrieril) [inline compiler/rustc_middle/src/ty/context.rs:426]: So this tells us which consts have a polymorphic type. How do we know which of the two types is the correct one? Also from what's below I understand that the array type is still the one assigned by default, could you mention this here?

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs [hunk 2]
```diff
@@ -413,7 +441,7 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
                                 suffix: vec![],
                             }),
                             span,
-                            ty: pointee_ty,
+                            ty: tcx.mk_slice(elem_ty),
```
Comment (Nadrieril) [inline compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:444]: If I understand correctly, here you're making `b"foo"` literals always have type `&[u8]`? Wouldn't that break in a case where they really are supposed to be `&[u8;N]`? Though knowing how exhaustiveness handles slices it might work by accident.

File: compiler/rustc_middle/src/ty/context.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/ty/context.rs:426]: actually, this field should just be `treat_byte_string_as_slice`, that's the only situation where the types differ (when we get a byte string literal, which is always of `&[u8; N]` type, and we need a slice)

File: src/test/ui/match/type_polymorphic_byte_str_literals.rs [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+        b"" => 1,
+        _ => 2,
+    }
+}
+
+fn parse_data2(data: &[u8]) -> u32 {
+    match data { //~ ERROR non-exhaustive patterns: `&[_, ..]` not covered
+        b"" => 1,
+    }
+}
```
Comment (Nadrieril) [inline src/test/ui/match/type_polymorphic_byte_str_literals.rs:14]: Could you add the following tests?
```rust
fn parse_data(data: &[u8; 0]) -> u8 {
    match data {
        b"" => 1,
    }
}

fn parse_data(data: &[u8]) -> u8 {
    match data { //~ ERROR non-exhaustive patterns
        b"aaa" => 0,
        [_, _, _] => 1,
    }
}

fn parse_data(data: &[u8; 3]) -> u8 {
    match data {
        b"aaa" => 0,
        [_, _, _] => 1,
    }
}
```

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:444]: There's a match arm for `ty::Array` above, which handles all situations where we expect an array. I had to invert the condition, because I can't put conditions on or patterns, so I can't do `ty::Array(..) if something | ty::Slice(_)`

File: compiler/rustc_middle/src/ty/context.rs (hunk 1 above)
Comment (Nadrieril) [reply compiler/rustc_middle/src/ty/context.rs]: Oh I see. Your latest change makes it clearer.

File: compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs (hunk 2 above)
Comment (Nadrieril) [reply compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:444]: Ah, got it

File: src/test/ui/match/type_polymorphic_byte_str_literals.rs (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/match/type_polymorphic_byte_str_literals.rs:14]: done

File: compiler/rustc_middle/src/ty/context.rs [hunk 4]
```diff
@@ -418,6 +418,12 @@ pub struct TypeckResults<'tcx> {
     /// Stores the type, expression, span and optional scope span of all types
     /// that are live across the yield of this generator (if a generator).
     pub generator_interior_types: Vec<GeneratorInteriorTypeCause<'tcx>>,
+
+    /// We sometimes treat byte string literals (which are of type`&[u8; N]`)
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/context.rs:422]:
```suggestion
    /// We sometimes treat byte string literals (which are of type `&[u8; N]`)
```

File: compiler/rustc_middle/src/ty/context.rs [hunk 5]
```diff
@@ -418,6 +418,12 @@ pub struct TypeckResults<'tcx> {
...
+    /// as `&[u8]`, depending on the pattern  in which they are used.
+    /// This hashset records all instances where we behave
+    /// like this to allow other code to reliably process this.
```
Comment (estebank) [inline compiler/rustc_middle/src/ty/context.rs:425]: "other code", could we explicitly mention `const_to_pat`?

**Review by estebank — APPROVED** [review]
r=me with nitpicks addressed or not

File: compiler/rustc_middle/src/ty/context.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/ty/context.rs:425]: :laughing: I had this before, but worried that this documentation would then just regress, but I guess I also don't see what other could could possibly care for this information, so yea, I'll add it again

**Comment by spastorino** [comment]
Adding `T-compiler` label so this can be picked up by our automated prioritization tool and added to the following `T-compiler` weekly meeting agenda.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/51074weeklymeeting2020121054818.html#219485251) in T-compiler meeting.

@rustbot modify labels: beta-accepted
