### PR TITLE
Emit ForbiddenBound fatally if meeting complex bound

### LINKED ISSUE #149695: ICE `No HirId for DefId`
auto-reduced (treereduce-rust):
````rust


trait Trait<T: ?Sized> {
    
}

fn produce() -> impl for<A: A< {
    
    

    
    #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
    enum A { A, A{ C  C: } }

    

    struct A<A> {
        A: A,
    }

    
    

    
    
} >> Trait<(), > {
    16
}

````

original:
````rust
#![feature(non_lifetime_binders)]

trait Trait<T: ?Sized> {
    type Assoc;
}

fn produce() -> impl for<A: A< {
    #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
    enum A { A(A), }

    #[repr(i16)]
    #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
    enum A { A, A{ C  C: } }

    #[ignore  = "msg"]
#[should_panic]
    struct A<A> {
        A: A,
    }

    #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
    struct A<A: A>(B)
    where
        A: A< continue >;

    #[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
    enum A<A> {
        A(
),
        A { A: A },
    }
} >> Trait<(), Assoc = impl Trait<T>> {
    16
}

````

Version information
````
rustc 1.93.0-nightly (66428d92b 2025-12-05)
binary: rustc
commit-hash: 66428d92bec337ed4785d695d0127276a482278c
commit-date: 2025-12-05
host: x86_64-unknown-linux-gnu
release: 1.93.0-nightly
LLVM version: 21.1.5

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected `:`, found `C`
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:13:23
   |
13 |     enum A { A, A{ C  C: } }
   |                 -     ^ expected `:`
   |                 |
   |                 while parsing this struct

error[E0428]: the name `A` is defined multiple times
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:17:5
   |
13 |     enum A { A, A{ C  C: } }
   |     ------ previous definition of the type `A` here
...
17 |     struct A<A> {
   |     ^^^^^^^^^^^ `A` redefined here
   |
   = note: `A` must be defined only once in the type namespace of this block

error[E0428]: the name `A` is defined multiple times
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:13:17
   |
13 |     enum A { A, A{ C  C: } }
   |              -  ^ `A` redefined here
   |              |
   |              previous definition of the type `A` here
   |
   = note: `A` must be defined only once in the type namespace of this enum

error[E0658]: only lifetime parameters can be used in this context
 --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:7:26
  |
7 | fn produce() -> impl for<A: A< {
  |                          ^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = help: add `#![feature(non_lifetime_binders)]` to the crate attributes to enable
  = note: this compiler was built on 2025-12-05; consider upgrading it if it is out of date

error: bounds cannot be used in this context
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:7:29
   |
 7 |   fn produce() -> impl for<A: A< {
   |  _____________________________^
...  |
26 | | } >> Trait<(), > {
   | |___^

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:28:2
   |
28 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs`

error[E0277]: the trait bound `{integer}: Trait<()>` is not satisfied
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:7:17
   |
 7 |   fn produce() -> impl for<A: A< {
   |  _________________^
...  |
26 | | } >> Trait<(), > {
   | |________________^ the trait `Trait<()>` is not implemented for `{integer}`
27 |       16
   |       -- return type was inferred to be `{integer}` here
   |
help: this trait has no implementations, consider adding one
  --> /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:3:1
   |
 3 | trait Trait<T: ?Sized> {
   | ^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: /rustc-dev/66428d92bec337ed4785d695d0127276a482278c/compiler/rustc_middle/src/hir/mod.rs:377:32: No HirId for DefId(0:8 ~ mvce[f267]::produce::{opaque#0}::{constant#0})


thread 'rustc' (2704135) panicked at /rustc-dev/66428d92bec337ed4785d695d0127276a482278c/compiler/rustc_middle/src/hir/mod.rs:377:32:
Box<dyn Any>
stack backtrace:
   0:     0x7f0873e6f6b3 - <<std[d1cf8494b7637499]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[7a5baad27c58ac9b]::fmt::Display>::fmt
   1:     0x7f0874411848 - core[7a5baad27c58ac9b]::fmt::write
   2:     0x7f0873e85ed6 - <std[d1cf8494b7637499]::sys::stdio::unix::Stderr as std[d1cf8494b7637499]::io::Write>::write_fmt
   3:     0x7f0873e45e78 - std[d1cf8494b7637499]::panicking::default_hook::{closure#0}
   4:     0x7f0873e63583 - std[d1cf8494b7637499]::panicking::default_hook
   5:     0x7f0872ecfec7 - std[d1cf8494b7637499]::panicking::update_hook::<alloc[fc8570482610e41]::boxed::Box<rustc_driver_impl[9b4b378bd639d3bd]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f0873e63862 - std[d1cf8494b7637499]::panicking::panic_with_hook
   7:     0x7f0872f0bf41 - std[d1cf8494b7637499]::panicking::begin_panic::<rustc_errors[888950e5e47c8ba6]::ExplicitBug>::{closure#0}
   8:     0x7f0872efc596 - std[d1cf8494b7637499]::sys::backtrace::__rust_end_short_backtrace::<std[d1cf8494b7637499]::panicking::begin_panic<rustc_errors[888950e5e47c8ba6]::ExplicitBug>::{closure#0}, !>
   9:     0x7f0872efc1cf - std[d1cf8494b7637499]::panicking::begin_panic::<rustc_errors[888950e5e47c8ba6]::ExplicitBug>
  10:     0x7f0872f29641 - <rustc_errors[888950e5e47c8ba6]::diagnostic::BugAbort as rustc_errors[888950e5e47c8ba6]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7f087348b959 - rustc_middle[35056dba64335523]::util::bug::opt_span_bug_fmt::<rustc_span[a0d314e698c4c838]::span_encoding::Span>::{closure#0}
  12:     0x7f087348bae2 - rustc_middle[35056dba64335523]::ty::context::tls::with_opt::<rustc_middle[35056dba64335523]::util::bug::opt_span_bug_fmt<rustc_span[a0d314e698c4c838]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7f087347cdbb - rustc_middle[35056dba64335523]::ty::context::tls::with_context_opt::<rustc_middle[35056dba64335523]::ty::context::tls::with_opt<rustc_middle[35056dba64335523]::util::bug::opt_span_bug_fmt<rustc_span[a0d314e698c4c838]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7f08718db7c4 - rustc_middle[35056dba64335523]::util::bug::bug_fmt
  15:     0x7f087469e207 - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::local_def_id_to_hir_id::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7f087469d5f7 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_data_structures[adb2697dbf3e0adc]::vec_cache::VecCache<rustc_span[a0d314e698c4c838]::def_id::LocalDefId, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[59d0c891baa5ac40]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  17:     0x7f087469d34b - rustc_query_impl[ac86e4dc6825f939]::query_impl::local_def_id_to_hir_id::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7f0874a4397f - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::hir_owner_parent::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>
  19:     0x7f0874a429b7 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_data_structures[adb2697dbf3e0adc]::vec_cache::VecCache<rustc_hir_id[3f20a8067ac1f93b]::OwnerId, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[59d0c891baa5ac40]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  20:     0x7f0874a4258b - rustc_query_impl[ac86e4dc6825f939]::query_impl::hir_owner_parent::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7f0874bd40e5 - <rustc_middle[35056dba64335523]::hir::map::ParentHirIterator as core[7a5baad27c58ac9b]::iter::traits::iterator::Iterator>::next
  22:     0x7f087305b8cd - <rustc_hir_analysis[c90d90e42cbb1186]::errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::get_type_or_const_args_suggestions_from_param_names
  23:     0x7f0872fccadf - <rustc_hir_analysis[c90d90e42cbb1186]::errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::suggest_adding_args::<rustc_span[a0d314e698c4c838]::ErrorGuaranteed>
  24:     0x7f08730d2820 - <rustc_hir_analysis[c90d90e42cbb1186]::errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_errors[888950e5e47c8ba6]::diagnostic::Diagnostic>::into_diag
  25:     0x7f0874bb1e9a - <dyn rustc_hir_analysis[c90d90e42cbb1186]::hir_ty_lowering::HirTyLowerer>::lower_resolved_ty_path
  26:     0x7f0874ba7d9b - <dyn rustc_hir_analysis[c90d90e42cbb1186]::hir_ty_lowering::HirTyLowerer>::lower_ty::{closure#0}
  27:     0x7f0874bcb065 - rustc_hir_analysis[c90d90e42cbb1186]::collect::type_of::type_of
  28:     0x7f087441b6e8 - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f087441a3c6 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_query_system[59d0c891baa5ac40]::query::caches::DefIdCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  30:     0x7f0874419f6f - rustc_query_impl[ac86e4dc6825f939]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f08745431e8 - rustc_middle[35056dba64335523]::ty::trait_def::trait_impls_of_provider
  32:     0x7f0874542563 - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::trait_impls_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f087441a3c6 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_query_system[59d0c891baa5ac40]::query::caches::DefIdCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  34:     0x7f08744638a5 - rustc_query_impl[ac86e4dc6825f939]::query_impl::trait_impls_of::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f087446376e - <rustc_middle[35056dba64335523]::ty::context::TyCtxt>::all_impls
  36:     0x7f087446393d - rustc_trait_selection[bfbaae654e06ec63]::traits::specialize::specialization_graph_provider
  37:     0x7f08744638cd - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7f087441a3c6 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_query_system[59d0c891baa5ac40]::query::caches::DefIdCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  39:     0x7f087454f75b - rustc_query_impl[ac86e4dc6825f939]::query_impl::specialization_graph_of::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f0874552977 - rustc_hir_analysis[c90d90e42cbb1186]::coherence::coherent_trait
  41:     0x7f0874552695 - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 1usize]>>
  42:     0x7f0874977be3 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_query_system[59d0c891baa5ac40]::query::caches::DefIdCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  43:     0x7f0874976ca4 - rustc_query_impl[ac86e4dc6825f939]::query_impl::coherent_trait::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f0874d4279c - rustc_middle[35056dba64335523]::query::inner::query_ensure_error_guaranteed::<rustc_query_system[59d0c891baa5ac40]::query::caches::DefIdCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 1usize]>>, ()>
  45:     0x7f0874feb548 - rustc_hir_analysis[c90d90e42cbb1186]::check_crate
  46:     0x7f0874696e95 - rustc_interface[a570f551ea6bf79f]::passes::analysis
  47:     0x7f0874696b5b - rustc_query_impl[ac86e4dc6825f939]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ac86e4dc6825f939]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 0usize]>>
  48:     0x7f0875564388 - rustc_query_system[59d0c891baa5ac40]::query::plumbing::try_execute_query::<rustc_query_impl[ac86e4dc6825f939]::DynamicConfig<rustc_query_system[59d0c891baa5ac40]::query::caches::SingleCache<rustc_middle[35056dba64335523]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ac86e4dc6825f939]::plumbing::QueryCtxt, false>
  49:     0x7f0875563fbe - rustc_query_impl[ac86e4dc6825f939]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  50:     0x7f08756f6410 - <rustc_interface[a570f551ea6bf79f]::passes::create_and_enter_global_ctxt<core[7a5baad27c58ac9b]::option::Option<rustc_interface[a570f551ea6bf79f]::queries::Linker>, rustc_driver_impl[9b4b378bd639d3bd]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[7a5baad27c58ac9b]::ops::function::FnOnce<(&rustc_session[61d9c53fe18acc9a]::session::Session, rustc_middle[35056dba64335523]::ty::context::CurrentGcx, alloc[fc8570482610e41]::sync::Arc<rustc_data_structures[adb2697dbf3e0adc]::jobserver::Proxy>, &std[d1cf8494b7637499]::sync::once_lock::OnceLock<rustc_middle[35056dba64335523]::ty::context::GlobalCtxt>, &rustc_data_structures[adb2697dbf3e0adc]::sync::worker_local::WorkerLocal<rustc_middle[35056dba64335523]::arena::Arena>, &rustc_data_structures[adb2697dbf3e0adc]::sync::worker_local::WorkerLocal<rustc_hir[670b2116001876c4]::Arena>, rustc_driver_impl[9b4b378bd639d3bd]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  51:     0x7f08755b8c85 - rustc_interface[a570f551ea6bf79f]::interface::run_compiler::<(), rustc_driver_impl[9b4b378bd639d3bd]::run_compiler::{closure#0}>::{closure#1}
  52:     0x7f087550e1d6 - std[d1cf8494b7637499]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a570f551ea6bf79f]::util::run_in_thread_with_globals<rustc_interface[a570f551ea6bf79f]::util::run_in_thread_pool_with_globals<rustc_interface[a570f551ea6bf79f]::interface::run_compiler<(), rustc_driver_impl[9b4b378bd639d3bd]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  53:     0x7f087550dfa9 - <std[d1cf8494b7637499]::thread::lifecycle::spawn_unchecked<rustc_interface[a570f551ea6bf79f]::util::run_in_thread_with_globals<rustc_interface[a570f551ea6bf79f]::util::run_in_thread_pool_with_globals<rustc_interface[a570f551ea6bf79f]::interface::run_compiler<(), rustc_driver_impl[9b4b378bd639d3bd]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[7a5baad27c58ac9b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:     0x7f087550c3f8 - <std[d1cf8494b7637499]::sys::thread::unix::Thread>::new::thread_start
  55:     0x7f086f0969cb - <unknown>
  56:     0x7f086f11aa0c - <unknown>
  57:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.93.0-nightly (66428d92b 2025-12-05) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [local_def_id_to_hir_id] getting HIR ID of `produce::{opaque#0}::{constant#0}`
#1 [hir_owner_parent] getting HIR parent of `produce::{opaque#0}::{constant#0}::<impl at /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:12:14: 12:18>`
#2 [type_of] computing type of `produce::{opaque#0}::{constant#0}::<impl at /tmp/icemaker_global_tempdir.nyMyaiftF75w/rustc_testrunner_tmpdir_reporting.re9MAsDkvErY/mvce.rs:12:14: 12:18>`
#3 [trait_impls_of] finding trait impls of `core::marker::Copy`
#4 [specialization_graph_of] building specialization graph of trait `core::marker::Copy`
#5 [coherent_trait] coherence checking all impls of trait `core::marker::Copy`
#6 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 8 previous errors

Some errors have detailed explanations: E0277, E0428, E0601, E0658.
For more information about an error, try `rustc --explain E0277`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by mu001999**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/149728)*

Fixes https://github.com/rust-lang/rust/issues/149695

---

Bounds in binders are denied, hir items won't contain and index them. But nested items in the bounds will still be lowered to hir. And their parents, i.e., the block in bounds is not in hir. So that ICE happens when error handling requires visiting hir parents.

~~This PR collects hirless def ids and skips them when iterating parents.~~

~~This PR checks such bounds used in higher ranked binders and emit error `ForbiddenBound` when parsing. And make sure no such bounds appear in hir.~~

This PR emits this error fatally if meeting complex bound.

### CODE REVIEW

File: compiler/rustc_ast_passes/src/feature_gate.rs [hunk 1]
```diff
@@ -152,7 +152,14 @@ impl<'a> PostExpansionVisitor<'a> {
         for param in params {
             if !param.bounds.is_empty() {
                 let spans: Vec<_> = param.bounds.iter().map(|b| b.span()).collect();
-                self.sess.dcx().emit_err(errors::ForbiddenBound { spans });
+                if param.bounds.iter().any(|bound| matches!(bound, GenericBound::Trait(_))) {
+                    // Issue #149695
+                    // Abort immediately otherwise items defined in complex bounds will be lowered into HIR,
+                    // which will cause ICEs when errors of the items visit unlowered parents.
+                    self.sess.dcx().emit_fatal(errors::ForbiddenBound { spans });
```
Comment (jdonszelmann) [inline compiler/rustc_ast_passes/src/feature_gate.rs:156]: fatal errors are a little unfortunate since they prevent other errors from happening. Is there no way to actually filter them out of the nested items? Maybe by setting a flag on the visitor?

Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: Sorry, I'm not sure what you mean. Did you mean skipping unlowered parents when visiting?

Comment (jdonszelmann) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: well, if I understand it correctly, there are bounds in nested items, that if they remain there into the HIR will mess up type checking when finding those. So your solution is to error fatally early, so we never get to type checking. But that means you also don't get to see any other errors in the compilation process. Can we not filter out these bounds so they just won't go into HIR anymore? Or am I misunderstanding the situation and is that not easily possible?

Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: This ICE is because the error in the nested item needs visiting its parent which is complex bound contains nested items. Not due to bounds in nested items.

For the case in the issue:
```rust
#![feature(non_lifetime_binders)]
fn produce() -> for<A: A< {
#[derive(Hash)]
 enum A {}
 struct A<A>;
}
>> Trait{
}

fn main() {}
```

Nested items in the complex bound `for <A: A<{ ... }>>` cause error and needs visiting its parent when reporting errors, and the parent points to the block in the trait ref. But we now won't lower the complex bound to hir, so that the block is not in hir also. And it's still the parent of the inner nested items, then ICE happens.

Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: So did you mean that don't lower nested items to hir if they are in a complex bound?

Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: IIUC, it may cause perf problem, because this needs checking whether an item is in a complex bound or not when lowering them, and lowering them is a separate procedure.

Comment (jdonszelmann) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: could you try how bad that perf problem is? I'll start you a perf run. Cause I don't like the fatal errors much :/

Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: Ok, I will try to do that later

Comment (jdonszelmann) [reply compiler/rustc_ast_passes/src/feature_gate.rs:156]: thanks! If it does end up being terrible, we can go this route

**Comment by jdonszelmann** [comment]
@rusbot author

**Comment by mu001999** [comment]
Hi @jdonszelmann, in the lastest rough change, I tried to filter nested items in the bound, and not lower them to hir.

`dbg!` shows it works:
```
[compiler/rustc_ast_lowering/src/lib.rs:527:17] "skipping lowering of {:?}" = "skipping lowering of {:?}"
[compiler/rustc_ast_lowering/src/lib.rs:527:17] def_id = DefId(0:6 ~ bad_bounds[bee6]::produce::{constant#0}::A)
[compiler/rustc_ast_lowering/src/lib.rs:527:17] "skipping lowering of {:?}" = "skipping lowering of {:?}"
[compiler/rustc_ast_lowering/src/lib.rs:527:17] def_id = DefId(0:7 ~ bad_bounds[bee6]::produce::{constant#0}::A::{constructor#0})
[compiler/rustc_ast_lowering/src/lib.rs:527:17] "skipping lowering of {:?}" = "skipping lowering of {:?}"
[compiler/rustc_ast_lowering/src/lib.rs:527:17] def_id = DefId(0:8 ~ bad_bounds[bee6]::produce::{constant#0}::A::A)
[compiler/rustc_ast_lowering/src/lib.rs:527:17] "skipping lowering of {:?}" = "skipping lowering of {:?}"
[compiler/rustc_ast_lowering/src/lib.rs:527:17] def_id = DefId(0:10 ~ bad_bounds[bee6]::produce::{constant#0}::A#1)
[compiler/rustc_ast_lowering/src/lib.rs:527:17] "skipping lowering of {:?}" = "skipping lowering of {:?}"
[compiler/rustc_ast_lowering/src/lib.rs:527:17] def_id = DefId(0:11 ~ bad_bounds[bee6]::produce::{constant#0}::{impl#0})
```

But there still be errors, because they still have `LocalDefId`, so that they can be result of many other queries. For example, after the change, a new ICE appears because `type_of(bad_bounds[bee6]::produce::{constant#0}::{impl#0})`.

Concrete content of the new ICE is:
```
error: internal compiler error: compiler/rustc_middle/src/hir/mod.rs:385:32: No HirId for DefId(0:11 ~ bad_bounds[bee6]::produce::{constant#0}::{impl#0})


thread 'rustc' (6902108) panicked at compiler/rustc_middle/src/hir/mod.rs:385:32:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
             at /rustc/1b6e21e163baa0b20f119e17e3871910978a60b6/library/std/src/panicking.rs:761:5
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
             at /rustc/1b6e21e163baa0b20f119e17e3871910978a60b6/library/std/src/panic.rs:260:5
   2: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             at ./compiler/rustc_errors/src/diagnostic.rs:63:9
   3: <rustc_errors::diagnostic::Diag<rustc_errors::diagnostic::BugAbort>>::emit
             at ./compiler/rustc_errors/src/diagnostic.rs:1405:9
   4: <rustc_errors::DiagCtxtHandle>::bug::<alloc::string::String>
             at ./compiler/rustc_errors/src/lib.rs:1231:30
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
             at ./compiler/rustc_middle/src/util/bug.rs:39:48
   6: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
             at ./compiler/rustc_middle/src/ty/context/tls.rs:136:23
   7: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:79:18
   8: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>
             at ./compiler/rustc_middle/src/ty/context/tls.rs:134:5
   9: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
             at ./compiler/rustc_middle/src/util/bug.rs:33:5
  10: rustc_middle::util::bug::bug_fmt
             at ./compiler/rustc_middle/src/util/bug.rs:16:5
  11: rustc_middle::hir::provide::{closure#0}
             at ./compiler/rustc_middle/src/macros.rs:18:9
  12: <rustc_middle::hir::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
             at /rustc/1b6e21e163baa0b20f119e17e3871910978a60b6/library/core/src/ops/function.rs:250:5
  13: rustc_query_impl::query_impl::local_def_id_to_hir_id::dynamic_query::{closure#2}::{closure#0}
             at ./compiler/rustc_query_impl/src/plumbing.rs:298:9
      [... omitted 22 frames ...]
  14: rustc_middle::query::inner::query_get_at::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex>>
             at ./compiler/rustc_middle/src/query/inner.rs:33:17
  15: <rustc_middle::query::plumbing::TyCtxtAt>::local_def_id_to_hir_id::<rustc_span::def_id::LocalDefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:415:31
  16: <rustc_middle::ty::context::TyCtxt>::local_def_id_to_hir_id::<rustc_span::def_id::LocalDefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:406:35
  17: rustc_hir_analysis::collect::type_of::type_of::{closure#0}
             at ./compiler/rustc_hir_analysis/src/collect/type_of.rs:56:22
  18: rustc_hir_analysis::collect::type_of::type_of
             at ./compiler/rustc_hir_analysis/src/collect/type_of.rs:21:1
  19: rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}
             at ./compiler/rustc_query_impl/src/plumbing.rs:302:13
      [... omitted 22 frames ...]
  20: rustc_middle::query::inner::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
             at ./compiler/rustc_middle/src/query/inner.rs:33:17
  21: <rustc_middle::query::plumbing::TyCtxtAt>::type_of::<rustc_span::def_id::DefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:415:31
  22: <rustc_middle::ty::context::TyCtxt>::type_of::<rustc_span::def_id::DefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:406:35
  23: rustc_middle::ty::trait_def::trait_impls_of_provider
             at ./compiler/rustc_middle/src/ty/trait_def.rs:227:32
  24: rustc_query_impl::query_impl::trait_impls_of::dynamic_query::{closure#2}::{closure#0}
             at ./compiler/rustc_query_impl/src/plumbing.rs:298:9
      [... omitted 22 frames ...]
  25: rustc_middle::query::inner::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>>
             at ./compiler/rustc_middle/src/query/inner.rs:33:17
  26: <rustc_middle::query::plumbing::TyCtxtAt>::trait_impls_of::<rustc_span::def_id::DefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:415:31
  27: <rustc_middle::ty::context::TyCtxt>::trait_impls_of::<rustc_span::def_id::DefId>
             at ./compiler/rustc_middle/src/query/plumbing.rs:406:35
  28: <rustc_middle::ty::context::TyCtxt>::all_impls
             at ./compiler/rustc_middle/src/ty/trait_def.rs:194:68

**Comment by mu001999** [comment]
I think at least it's more difficult than I expected. Do you have any suggestions?

**Comment by jdonszelmann** [comment]
Maybe that's not great for perf, mostly in visiting all those extra nodes I'm afraid

**Comment by mu001999** [comment]
Yep, I think this adds excessive overhead to the hot path.

**Comment by mu001999** [comment]
> to already error on them when creating the AST

Make sense, I think I could move the check in `check_late_bound_lifetime_defs` into `parse_higher_ranked_binder`, and report it as a parse error and then return empty bounds.

**Comment by jdonszelmann** [comment]
@mu001999 is this ready for review? I think doing it like this is quite reasonable, and we don't error fatally which is nice.

File: compiler/rustc_ast_passes/src/feature_gate.rs [hunk 2]
```diff
@@ -145,7 +145,8 @@ impl<'a> PostExpansionVisitor<'a> {
         }
 
         for param in params {
-            if !param.bounds.is_empty() {
+            if !matches!(param.kind, ast::GenericParamKind::Type { .. }) && !param.bounds.is_empty()
```
Comment (jdonszelmann) [inline compiler/rustc_ast_passes/src/feature_gate.rs]: This check is the same as one below

File: compiler/rustc_parse/src/parser/ty.rs [hunk 3]
```diff
@@ -1433,6 +1433,24 @@ impl<'a> Parser<'a> {
...
             let params = self.parse_generic_params()?;
             self.expect_gt()?;
+
+            // Issue 149695
+            // Deny and remove bounds for type parameters in higher-ranked binders,
+            // otherwise nested items may have parents not in hir.
+            let params = params
+                .into_iter()
+                .map(|mut param| {
+                    if matches!(param.kind, ast::GenericParamKind::Type { .. })
```
Comment (jdonszelmann) [inline compiler/rustc_parse/src/parser/ty.rs]: This one. Might be nice to split out?

Comment (jdonszelmann) [reply compiler/rustc_parse/src/parser/ty.rs]: Into a .is_forbidden_bound or whatever

**Comment by jdonszelmann** [comment]
r=me after that

File: compiler/rustc_ast_passes/src/feature_gate.rs (hunk 2 above)
Comment (mu001999) [reply compiler/rustc_ast_passes/src/feature_gate.rs]: No, they are different. This is `!matches!(param.kind, ast::GenericParamKind::Type { .. })`, the below is `matches!(param.kind, ast::GenericParamKind::Type { .. })`

File: compiler/rustc_parse/src/parser/ty.rs (hunk 3 above)
Comment (mu001999) [reply compiler/rustc_parse/src/parser/ty.rs]: As the above, `.is_forbidden_bound` will only check `!param.bounds.is_empty()` in fact

**Review by fmease — CHANGES_REQUESTED** [review]
This is a breaking change to stable Rust's grammar. This is not acceptable without T-lang involvement and a crater run.

Moreover this renders the grammar quite inconsistent by syntactically rejecting bounds on higher-ranked type parameters but syntactically permitting them on higher-ranked lifetime parameters.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149728/7bee525095c0872e87c038c412c781b9bbb3f5dc..ca6cc5d49b6d0f9499b1056248842482923eb38c)*
