### PR TITLE
Do not encode gensymed imports in metadata

### LINKED ISSUE #59243: the name `std` is defined multiple times
The error happens on latest stable and nightly.
Steps to reproduce: `cargo new --lib lib1`;
`src/lib.rs`:
```rust
pub mod std {
}
```
`tests/test1.rs`:
```rust
use lib1;
fn main() {
}
```
`cargo test` returns error:
```
error[E0260]: the name `std` is defined multiple times
  |
  = note: `std` must be defined only once in the type namespace of this module
```
The error only happens if the module is named `std` (for instance, `core` and `alloc` work without error). The error is not produced if `test1.rs` doesn't use `lib1` in any way. If `test1.rs` doesn't contain imports but uses the library directly (e.g. `::lib1::x()`), the error is produced. `cargo build` always succeeds. 

I don't know if this is supposed to be forbidden but the error message seems to be misleading.

### PR DESCRIPTION
**Pull request by petrochenkov**
(Unless they are underscore `_` imports which are re-gensymed on crate loading, see https://github.com/rust-lang/rust/pull/56392.)

We cannot encode gensymed imports properly in metadata and if we encode them improperly, we can get erroneous name conflicts downstream.
Gensymed imports are produced by the compiler, so we control their set, and can be sure that none of them needs being encoded for use from other crates.

A workaround that fixes https://github.com/rust-lang/rust/issues/59243.

### CODE REVIEW

File: src/librustc_resolve/build_reduced_graph.rs [hunk 1]
```diff
@@ -312,7 +312,7 @@ impl<'a> Resolver<'a> {
                             Ident::new(keywords::SelfLower.name(), new_span)
                         ),
                         kind: ast::UseTreeKind::Simple(
-                            Some(Ident::new(keywords::Underscore.name().gensymed(), new_span)),
+                            Some(Ident::new(Name::gensym("__dummy"), new_span)),
```
Comment (estebank) [inline src/librustc_resolve/build_reduced_graph.rs]: Doesn't this shift the problem to the possible existence of `__dummy` somewhere in the namespace?

Comment (petrochenkov) [reply src/librustc_resolve/build_reduced_graph.rs]: No, it's still a gensym, so it doesn't conflict with anything locally + it's not written into metadata since it's no longer an underscore.
(Previously it wasn't written due to the `binding.vis != ty::Visibility::Invisible` condition, but I removed it to simplify things a bit.)
