### PR TITLE
Force all native libraries to be statically linked when linking a static binary

### LINKED ISSUE #102993: ELF binary built linked against fake loader
hi, I'm compiling a Rust program on my ARM AArch64 machine which is running linux with a musl libc. Rust wants to compile the binary with the interpreter set as `/lib/ld-linux-aarch64.so.1` which does not exist on my system. I do have `/lib/ld-musl-aarch64.so.1` however. 

As a result when I try to execute the binary built by rust in this case I just get ENOENT. In fact when I `strace ./binary` there is only a single syscall printed, the execve on the binary itself, which returns ENOENT. This makes me sad...

Manually loading the binary (ie running `exec /lib/ld-musl-aarch64.so.1 $PWD/binary`) gets me a lot farther in the execution of my program which then crashes for other reasons, presumably my fault :) But that's out of scope for this issue.

If it helps I installed Rust via rustup.

### LINKED ISSUE #108878: Builds on *-unknown-linux-musl that link to C libaries produce broken binaries
### Problem

I'm trying to build the following minimal example:

```rs
fn main() {
    _ = xkbcommon::xkb::Context::new(0);
    println!("Hello, world!");
}
```

I'm buildling on `aarch64-unknown-linux-musl`, and my target is `aarch64-unknown-linux-musl` (e.g.: there's no cross-compiling going on here).

The above builds fine, but the resulting binary fails to run:

```
> cargo run  
   Compiling libc v0.2.137
   Compiling memmap2 v0.5.7
   Compiling xkbcommon v0.5.0
   Compiling hello v0.1.0 (/home/user/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 6.67s
     Running `target/debug/hello`
error: could not execute process `target/debug/hello` (never executed)

Caused by:
  No such file or directory (os error 2)
```

The resulting binary is clearly linked against glibc, which is not present here:

```rs
> ldd target/debug/hello
	/lib/ld-linux-aarch64.so.1 (0xffffacf0b000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0xffffacebc000)
	libc.musl-aarch64.so.1 => /lib/ld-linux-aarch64.so.1 (0xffffacf0b000)
> readelf -l target/debug/hello

Elf file type is EXEC (Executable file)
Entry point 0x405328
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000400238 0x0000000000400238
                 0x000000000000001b 0x000000000000001b  R      0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x00000000000581dc 0x00000000000581dc  R E    0x10000
  LOAD           0x0000000000058e28 0x0000000000468e28 0x0000000000468e28
                 0x0000000000007338 0x0000000000008e40  RW     0x10000
  DYNAMIC        0x000000000005fcb0 0x000000000046fcb0 0x000000000046fcb0
                 0x00000000000001f0 0x00000000000001f0  RW     0x8
  TLS            0x000000000005d758 0x000000000046d758 0x000000000046d758
                 0x0000000000000028 0x0000000000000050  R      0x8
  GNU_EH_FRAME   0x0000000000056124 0x0000000000456124 0x0000000000456124
                 0x000000000000132c 0x000000000000132c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000058e28 0x0000000000468e28 0x0000000000468e28
                 0x00000000000071d8 0x00000000000071d8  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .debug_gdb_scripts .eh_frame_hdr .gcc_except_table 
   03     .eh_frame .tdata .init_array .fini_array .data.rel.ro .dynamic .got .data .bss 
   04     .dynamic 
   05     .tdata .tbss 
   06     .eh_frame_hdr 
   07     
   08     .eh_frame .tdata .init_array .fini_array .data.rel.ro .dynamic .got 
```

### Steps

```sh
rustup default nightly
mkdir lalala
cd lalala
cargo init
cargo add xkbcommon
cat > src/main.rs <<EOF
fn main() {
    _ = xkbcommon::xkb::Context::new(0);
    println!("Hello, world!");
}
EOF
cargo run
```

### Possible Solution(s)

Not sure, I think there's something wrong with the binaries that rustup ships.

### Notes

Using cargo/rust/etc from Alpine repositories works fine. It's the binaries pulled by rustup that are faulty somehow.

Originally reported at the library I was trying to use (https://github.com/rust-x-bindings/xkbcommon-rs/issues/37), but eventually realised it seems to be an issue with the binaries that `rustup` pulls.

### Rustup version

```console
rustup 1.25.1 :: v20220715+1493 (394daf022 2022-08-03) dirty 2 modifications
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.65.0 (897e37553 2022-11-02)`
```

### Installed toolchains

```console
Default host: aarch64-unknown-linux-musl
rustup home:  /home/user/.rustup

stable-aarch64-unknown-linux-musl (default)
rustc 1.65.0 (897e37553 2022-11-02)
```

### PR DESCRIPTION
**Pull request by Amanieu**
Previously, `#[link]` without an explicit `kind = "static"` would confuse the linker and end up producing a dynamically linked library because of the `-Bdynamic` flag. However this binary would not work correctly anyways since it was linked with startup code for a static binary.

This PR solves this by forcing all native libraries to be statically linked when the output is a static binary that cannot link to dynamic libraries anyways.

Fixes #108878
Fixes #102993

### CODE REVIEW

File: compiler/rustc_target/src/spec/mod.rs [hunk 1]
```diff
@@ -596,6 +596,18 @@ impl LinkOutputKind {
...
+    pub fn can_link_dylib(self) -> bool {
+        match self {
+            LinkOutputKind::StaticNoPicExe
+            | LinkOutputKind::StaticPicExe
+            | LinkOutputKind::StaticDylib
+            | LinkOutputKind::WasiReactorExe => false,
+            LinkOutputKind::DynamicNoPicExe
+            | LinkOutputKind::DynamicPicExe
+            | LinkOutputKind::DynamicDylib => true,
+        }
```
Comment (fbstj) [inline compiler/rustc_target/src/spec/mod.rs:609]:
```suggestion
        matches!(self, LinkOutputKind::DynamicNoPicExe
            | LinkOutputKind::DynamicPicExe
            | LinkOutputKind::DynamicDylib)
```

Comment (Amanieu) [reply compiler/rustc_target/src/spec/mod.rs:609]: I prefer explicitly writing out each case, that way this doesn't get missed when a new `LinkOutputKind` variant is added.

**Comment by WhyNotHugo** [comment]
I'm not entirely sure how to test this.

Given the original issue at hand here, I don't expect that I'll be able to use the nightly compiler to compile this branch.

I tried anyway, but:

```console
> ./x.py setup --verbose
downloading https://static.rust-lang.org/dist/2023-04-20/rust-std-beta-x86_64-unknown-linux-musl.tar.xz
############################################################################################################################## 100.0%
downloading https://static.rust-lang.org/dist/2023-04-20/rustc-beta-x86_64-unknown-linux-musl.tar.xz
############################################################################################################################## 100.0%
downloading https://static.rust-lang.org/dist/2023-04-20/cargo-beta-x86_64-unknown-linux-musl.tar.xz
############################################################################################################################## 100.0%
extracting /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-20/rust-std-beta-x86_64-unknown-linux-musl.tar.xz
extracting /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-20/rustc-beta-x86_64-unknown-linux-musl.tar.xz
extracting /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-20/cargo-beta-x86_64-unknown-linux-musl.tar.xz
Building bootstrap
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.56
   Compiling memchr v2.5.0
   Compiling unicode-ident v1.0.0
   Compiling quote v1.0.26
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling bitflags v1.3.2
   Compiling io-lifetimes v1.0.9
   Compiling cc v1.0.73
   Compiling regex-automata v0.1.10
   Compiling serde v1.0.137
   Compiling pkg-config v0.3.25
   Compiling log v0.4.17
   Compiling lazy_static v1.4.0
   Compiling rustix v0.37.6
   Compiling once_cell v1.12.0
   Compiling clap_lex v0.4.1
   Compiling syn v1.0.102
   Compiling anstyle v1.0.0
   Compiling linux-raw-sys v0.3.2
   Compiling heck v0.4.1
   Compiling crossbeam-utils v0.8.14
   Compiling regex-syntax v0.6.26
   Compiling serde_json v1.0.81
   Compiling same-file v1.0.6
   Compiling serde_derive v1.0.137
   Compiling fnv v1.0.7
   Compiling clap_builder v4.2.4
   Compiling semver v1.0.17
   Compiling thread_local v1.1.4
   Compiling walkdir v2.3.2
   Compiling ryu v1.0.10
   Compiling cpufeatures v0.2.5
   Compiling bootstrap v0.0.0 (/home/hugo/src/github.com/rust-lang/rust/src/bootstrap)
   Compiling itoa v1.0.2
   Compiling build_helper v0.1.0 (/home/hugo/src/github.com/rust-lang/rust/src/tools/build_helper)
   Compiling termcolor v1.2.0
   Compiling generic-array v0.14.5
   Compiling hex v0.4.3
   Compiling cmake v0.1.48
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.17
   Compiling object v0.29.0
   Compiling lzma-sys v0.1.17
   Compiling syn v2.0.15
   Compiling opener v0.5.0
   Compiling block-buffer v0.10.2
   Compiling crypto-common v0.1.3
   Compiling digest v0.10.3
   Compiling regex v1.5.6
   Compiling sha2 v0.10.2
   Compiling filetime v0.2.16
   Compiling xattr v0.2.3
   Compiling xz2 v0.1.6
   Compiling tar v0.4.38
   Compiling globset v0.4.8
   Compiling ignore v0.4.18
   Compiling toml v0.5.9
   Compiling is-terminal v0.4.6
   Compiling fd-lock v3.0.11
   Compiling clap_derive v4.2.0
   Compiling clap v4.2.4
   Compiling clap_complete v4.2.2
    Finished dev [unoptimized] target(s) in 0.03s
running: /home/hugo/src/github.com/rust-lang/rust/build/bootstrap/debug/bootstrap setup --verbose
finding compilers
CC_x86_64-unknown-linux-musl = "cc"
CFLAGS_x86_64-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-static"]
CXX_x86_64-unknown-linux-musl = "c++"
CXXFLAGS_x86_64-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-static"]
AR_x86_64-unknown-linux-musl = "ar"
verifying /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-21/rustfmt-nightly-x86_64-unknown-linux-musl.tar.xz
extracting /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-21/rustfmt-nightly-x86_64-unknown-linux-musl.tar.xz to /home/hugo/src/github.com/rust-lang/rust/build/x86_64-unknown-linux-musl/rustfmt
Traceback (most recent call last):
  File "/home/hugo/src/github.com/rust-lang/rust/./x.py", line 32, in <module>
    bootstrap.main()
  File "/home/hugo/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 1084, in main
    bootstrap(args)
  File "/home/hugo/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 1059, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/home/hugo/src/github.com/rust-lang/rust/src/bootstrap/bootstrap.py", line 184, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /home/hugo/src/github.com/rust-lang/rust/build/bootstrap/debug/bootstrap setup --verbose
```

Indeed, it looks like the root cause of this build failure is the same issue that this patch is trying to fix:

```console
> /home/hugo/src/github.com/rust-lang/rust/build/bootstrap/debug/bootstrap setup --verbose
finding compilers
CC_x86_64-unknown-linux-musl = "cc"
CFLAGS_x86_64-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-static"]
CXX_x86_64-unknown-linux-musl = "c++"
CXXFLAGS_x86_64-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-static"]
AR_x86_64-unknown-linux-musl = "ar"
verifying /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-21/rustfmt-nightly-x86_64-unknown-linux-musl.tar.xz
extracting /home/hugo/src/github.com/rust-lang/rust/build/cache/2023-04-21/rustfmt-nightly-x86_64-unknown-linux-musl.tar.xz to /home/hugo/src/github.com/rust-lang/rust/build/x86_64-unknown-linux-musl/rustfmt
zsh: segmentation fault  /home/hugo/src/github.com/rust-lang/rust/build/bootstrap/debug/bootstrap setup
```

This makes me wonder: how are official binaries produced if the upstream binaries aren't linking libraries properly? Is some non-default flag used when building these?

I guess I need to explicitly tell the nightly compiler to dynamically link to libc, right? Or statically link all external libraries?

**Comment by nekopsykose** [comment]
@WhyNotHugo that looks unrelated, i would assume you get that issue building the compiler without these changes. you'll have to figure out how to do that first

@Amanieu 

before:  
```
$ RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --release 
   Compiling libc v0.2.144
   Compiling memmap2 v0.5.10
   Compiling xkbcommon v0.5.0
   Compiling x v0.1.0 (/tmp/mytemp.iKnNJK/x)
    Finished release [optimized] target(s) in 3.53s
$ file target/release/x                                                           
target/release/x: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=221da58c22e8613b8972fe45c140e1c66396699c, with debug_info, not stripped
$ ./target/release/x       
zsh: segmentation fault (core dumped)  ./target/release/x
```

after:  

first, building without a `.a` available fails (good):  

```

  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/13.1.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lxkbcommon: No such file or directory
          collect2: error: ld returned 1 exit status
```

adding the .a:  

```
$ RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --release
   Compiling x v0.1.0 (/tmp/mytemp.iKnNJK/x)
    Finished release [optimized] target(s) in 2.96s
$ file target/release/x
target/release/x: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[sha1]=f1dc0a1ca6ee75bb3b96ab24bdeacf82379f1305, with debug_info, not stripped
$ ./target/release/x       
Hello, world!
```


looks good!

File: compiler/rustc_target/src/spec/mod.rs (hunk 1 above)
Comment (nekopsykose) [reply compiler/rustc_target/src/spec/mod.rs:609]: yes, this is one of those cases where you would want a build failure for new Kind's that have to be handled, so being explicit is better.

**Comment by petrochenkov** [comment]
r? @petrochenkov 
I need to look at what this PR does in detail, probably next week.
There's some history behind these issues https://github.com/rust-lang/rust/issues/71647, https://github.com/rust-lang/rust/issues/39998, maybe https://github.com/rust-lang/rust/issues/71651.

**Comment by Amanieu** [comment]
A static binary literally cannot link to dynamic libraries. The only sane behavior here is to force all external libraries to also be statically linked or to emit an error.

**Comment by petrochenkov** [comment]
>A static binary ...

First, `-C target-feature=+crt-static` is more like "link libc statically" which is very similar to "make a static binary" on Unix-like targets, but e.g. on Windows you can link libc statically and still link to other DLLs because dynamic linker is an OS component and not libc component in that case.

>... literally cannot link to dynamic libraries

Second, this is true for ELFs loaded by standard dynamic linker, but not necessarily true for ELF plugins loaded by something else.

For example, unix style linkers not being opinionated in this regard make it very convenient to make statically linked [DynamoRIO](https://github.com/dynamorio/dynamorio) plugins (with which you are probably familiar due to your work on MAMBO) that still link to libdynamorio.so dynamically at static link time and are loaded by that same libdynamorio.so instead of a standard ld.

**Comment by petrochenkov** [comment]
Sorry, no conclusion so far, I still didn't have time to devote to this PR properly.
But I wrote a [very pedantic overview](https://github.com/rust-lang/rust/issues/71651#issuecomment-985229406) of linking libc and dynamic libraries on various targets a couple of years ago, which I need to re-read myself and which had some conclusions, possibly slightly over-engineered.

**Comment by petrochenkov** [comment]
I think we can try flipping the default for `NativeLibKind::Unspecified` libs only, while still respecting explicit `dylib` kinds to cover rare cases.

And land this on nightly only to see what breaks on targets that are more similar to Windows than to Linux.

**Comment by petrochenkov** [comment]
@craterbot run mode=build-only

**Comment by Amanieu** [comment]
I've updated the core to only apply this when building an executable (`crate_type = "bin"`) and changed it to only affect unspecified link types.

**Comment by petrochenkov** [comment]
@Amanieu 
Did you check the regressions? Is there anything non-spurious there?

File: compiler/rustc_codegen_ssa/src/back/link.rs [hunk 2]
```diff
@@ -2476,8 +2496,14 @@ fn add_native_libs_from_crate(
                 }
             }
             NativeLibKind::Unspecified => {
-                if link_dynamic {
-                    cmd.link_dylib(name, verbatim, true);
+                if prefer_link_static {
```
Comment (petrochenkov) [inline compiler/rustc_codegen_ssa/src/back/link.rs:2499]:
```suggestion
                if !link_output_kind.can_link_dylib() {
```
Nit: it's only used once now.

**Comment by petrochenkov** [comment]
@bors rollup=never
r=me after answering https://github.com/rust-lang/rust/pull/111698#issuecomment-1572105083.

**Comment by Amanieu** [comment]
The regression are all related to running out of disk space. I also don't expect any regressions from crater since crater only tests x86_64-unknown-linux-gnu which uses dynamic linking.

**Comment by petrochenkov** [comment]
>Too bad there's no Windows-based infra for crater.

>The job dist-i686-msvc failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/5145338695/jobs/9262862890) [(plain)](https://github.com/rust-lang-ci/rust/commit/68608e68d00d71d80937e81ac5d7a70a5ff69b78/checks/13927989211/logs)

Well, looks like we didn't even need crater.
@rustbot author

**Comment by Amanieu** [comment]
I changed the condition to exclude targets that specify `crt_static_allows_dylibs`.

File: src/doc/rustc/src/command-line-arguments.md [hunk 3]
```diff
@@ -58,8 +58,8 @@ Example: `-l static:+whole-archive=mylib`.
 
 The kind of library and the modifiers can also be specified in a [`#[link]`
 attribute][link-attribute]. If the kind is not specified in the `link`
-attribute or on the command-line, it will link a dynamic library if available,
-otherwise it will use a static library. If the kind is specified on the
+attribute or on the command-line, it will link a dynamic library by default,
+except when building a static executable. If the kind is specified on the
```
Comment (petrochenkov) [inline src/doc/rustc/src/command-line-arguments.md:62]: The previous wording was right in the sense that `-Bdynamic` with ld-like linkers is only a *preference* for a dynamic library, not a requirement, so a static library can be linked even despite `kind=dylib` if there's no dynamic version of it.

That's what I called "too platform specific" above.
That's why I also suggested to document things in terms of the inferred `kind` and not in terms of actually linked libraries.

Comment (Amanieu) [reply src/doc/rustc/src/command-line-arguments.md:62]: Based on my experiments, this isn't actually a preference: the linker will not search for static libraries if -Bdynamic is specified.
