### PR TITLE
diagnostics: suggest changing `s@self::{macro}@::macro` for exported

### LINKED ISSUE #99695: import #[macro_export] from crate root help broken by use trees
Given the following code: [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=48dddf636bdd62b020eaea0bd0e04393)

```rust
mod m {
    #[macro_export]
    macro_rules! nu {
        {} => {};
    }

    #[allow(nonstandard_style)]
    pub struct other_item;

    pub use self::{nu, other_item as _};
}
```

The current output is:

```
error[[E0432]](https://doc.rust-lang.org/nightly/error-index.html#E0432): unresolved import `self::nu`
  --> src/lib.rs:10:20
   |
10 |     pub use self::{nu, other_item as _};
   |                    ^^ no `nu` in `m`
   |
   = note: this could be because a macro annotated with `#[macro_export]` will be exported at the root of the crate instead of the module where it is defined
help: a macro with this name exists at the root of the crate
   |
10 -     pub use self::{nu, other_item as _};
10 +     pub use self::{nu, other_item as _};
   |
```

<details><summary>If the starting order is reversed, the suggestion puts the macro first in the tree</summary>

```
error[[E0432]](https://doc.rust-lang.org/nightly/error-index.html#E0432): unresolved import `self::nu`
  --> src/lib.rs:10:37
   |
10 |     pub use self::{other_item as _, nu};
   |                                     ^^ no `nu` in `m`
   |
   = note: this could be because a macro annotated with `#[macro_export]` will be exported at the root of the crate instead of the module where it is defined
help: a macro with this name exists at the root of the crate
   |
10 -     pub use self::{other_item as _, nu};
10 +     pub use self::{nu, other_item as _};
   |
```
</details>

This is suggesting to change the code to itself 🙃 It needs to move the import into a `use crate::` tree; the easy way is to make a new `use` statement (and let rustfmt clean that up); the medium way is to find an existing `use crate::` context; the hard way is when a `use crate::` tree root doesn't already exist (or isn't immediately a tree at that point) determine what [import granularity](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity) the code is using and match that.

Related: #99694

@rustbot label +D-confusing +D-incorrect

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #99695

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -2285,9 +2285,31 @@ impl<'a, 'b> ImportResolver<'a, 'b> {
 
                 let source_map = self.r.session.source_map();
 
+                // Make sure this is actually crate-relative.
+                let use_and_crate = import.use_span.with_hi(after_crate_name.lo());
+                let is_definitely_crate =
+                    source_map.span_to_snippet(use_and_crate).map_or(false, |s| {
```
Comment (TaKO8Ki) [inline compiler/rustc_resolve/src/diagnostics.rs:2291]: Could you use `ImportKind` to check if the import is crate relative or not? I think this can also remove the use of `span_to_snippet`sanipulating strings.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 2]
```diff
@@ -2299,11 +2321,17 @@ impl<'a, 'b> ImportResolver<'a, 'b> {
...
-                if !has_nested {
-                    corrections.push((source_map.end_point(after_crate_name), "};".to_string()));
+                    // Add a `};` to the end if nested, matching the `{` added at the start.
+                    if !has_nested {
+                        corrections.push((source_map.end_point(after_crate_name), "};".to_string()));
+                    }
+                } else {
+                    // If the root import is module-relative, add the import separately
+                    corrections.push((
+                        source_map.start_point(import.use_span).shrink_to_lo(),
```
Comment (TaKO8Ki) [inline compiler/rustc_resolve/src/diagnostics.rs:2332]: Is there any reason why you use `start_point`? If not, could you change like the following:

```suggestion
                        import.use_span.shrink_to_lo(),
```

**Review by TaKO8Ki — COMMENTED** [review]
Sorry for the late replay. I left some comments.

**Comment by apiraino** [comment]
Friendly ping for a review @TaKO8Ki . Thanks!
