### PR TITLE
avoid overlapping privacy suggestion for single nested imports

### LINKED ISSUE #114884: Import trait help message is incorrect
### Code

```Rust
extern crate rustc_index;

use rustc_index::{vec::Idx};

fn main() { }
```

### Current output

```Shell
# rustc --version
rustc 1.73.0-nightly (0bdb00d55 2023-08-15)

# rustc main.rs
error[E0603]: module `vec` is private
 --> main.rs:3:19
  |
3 | use rustc_index::{vec::Idx};
  |                   ^^^ private module
  |
note: the module `vec` is defined here
 --> /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_index/src/lib.rs:24:1
help: consider importing this trait instead
  |
3 | use rustc_index::{rustc_index::Idx};
  |                   ~~~~~~~~~~~~~~~~

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
 --> main.rs:1:1
  |
1 | extern crate rustc_index;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #27812 <https://github.com/rust-lang/rust/issues/27812> for more information
  = help: add `#![feature(rustc_private)]` to the crate attributes to enable

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0603, E0658.
For more information about an error, try `rustc --explain E0603`.
```

(The rustc_private error is irrelevant)

### Desired output

The suggestion to import `rustc_index::{rustc_index::Idx};` is obviously wrong. It should be `rustc_index::{Idx};` (or even `rustc_index::Idx`).

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #114884

This PR aims to avoid confusion inside braces for import suggestions.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/ident.rs [hunk 1]
```diff
@@ -870,6 +870,7 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                         dedup_span: path_span,
                         outermost_res: None,
                         parent_scope: *parent_scope,
+                        imported,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/ident.rs:873]:
```suggestion
                        single_nested: path_span != root_span,
```
Looks like `Finalize` doesn't need to carry additional data (especially with a lifetime), the property we need can be inferred from already existing fields.
Also `PrivacyError` doesn't need to keep whole `Option<Import<'a>>`, it only needs a single boolean flag.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 2]
```diff
@@ -2659,7 +2663,10 @@ pub(crate) enum DiagnosticMode {
     /// The binding is part of a pattern
     Pattern,
     /// The binding is part of a use statement
-    Import,
+    Import {
+        /// Is the format `use a::{b,c}`
+        single_nested: bool,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/diagnostics.rs:2668]:
```suggestion
        append: bool,
```
To emphasize how we change the diagnostic (from replacing to appending), instead of the initial reason for that.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
