### PR TITLE
interpret: adjust vtable validity check for higher-ranked types

### LINKED ISSUE #135230: Inconsistent/wrong choice of trait impls under `miri` with transmuted vtables
Here is a test case
```rust
#![allow(coherence_leak_check)]

fn main() {
    let x: &dyn Trait<Marker1> = &();
    let y: &dyn Trait<Marker2> = unsafe { std::mem::transmute(x) };
    y.report();
}

type Marker1 = fn(&()) -> (&(), &'static ());
type Marker2 = fn(&()) -> (&'static (), &());

trait Trait<M: 'static> {
    fn report(&self);
}
impl<M: 'static> Trait<M> for () {
    fn report(&self) {
        who_am_i::<M>();
    }
}

fn who_am_i<M: 'static>() {
    let marker1 = std::any::TypeId::of::<Marker1>();
    let marker2 = std::any::TypeId::of::<Marker2>();
    let m = std::any::TypeId::of::<M>();
    let m_is = if m == marker1 {
        "Marker1"
    } else if m == marker2 {
        "Marker2"
    } else {
        unreachable!()
    };
    println!("M == {m_is}");
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f3ea7b28ea1c770d5f84068c2f699e09))

When run normally, this prints
```rust
M == Marker1
```

When run with miri, this prints
```rust
M == Marker2
```

### Expected behavior: Miri either reports UB, or behaves the same way like the actual codegen does.

---

It gets even more interesting if we add a trait bound to the `impl`:
```rust
impl<M: 'static> Trait<M> for ()
where
    M: Bound,
{
    fn report(&self) {
        who_am_i::<M>();
        println!("---");
        M::who_am_i();
    }
}

trait Bound: 'static + Sized {
    fn who_am_i() {
        who_am_i::<Self>();
    }
}
impl Bound for Marker1 {}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=032bb768232c99aa7316d3cf5c742495))

When run normally, this prints
```rust
M == Marker1
---
M == Marker1
```

When run with miri, this prints
```rust
M == Marker2
---
M == Marker1
```

*Oh wonderful, the type apparently just changes in the middle of it!*

---

If we add a second implementation, Miri reconsiders its choices
```rust
impl Bound for Marker1 {}
impl Bound for Marker2 {}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=8f46f10cff12456009d7287c428c54f7))

*(Behavior when run normally: unchanged.)*

When run with miri, this prints
```rust
M == Marker2
---
M == Marker2
```

*(still wrong though / [actual execution without `miri` is reporting `Marker1`, `Marker1`])*

---

This behavior must come from some sort of rough heuristic that wasn't supposed to ever matter… because… if the second `impl` *exists* but comes with an impossible trait bound, then miri still seems to try to make use of this `Marker2`-impl nonetheless:
```rust
impl Bound for Marker1 {}
impl Bound for Marker2 where Self: Unimplemented {}

trait Unimplemented {}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=75708feacbe51b65b17ffa08e0cc4415))

When run normally, this still prints
```rust
M == Marker1
---
M == Marker1
```

When run with miri, you get ICE:
```plain
error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:585:21: failed to resolve instance for <() as Trait<for<'a> fn(&'a ()) -> (&(), &'a ())>>::report
  --> src/main.rs:13:5
   |
13 |     fn report(&self);
   |     ^^^^^^^^^^^^^^^^^


thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:585:21:
Box<dyn Any>
stack backtrace:
   0:     0x7d96ae6d260a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hcfde92856b8e7b4d
   1:     0x7d96aee135e6 - core::fmt::write::h8aa28d7c2e766574
   2:     0x7d96afcc0491 - std::io::Write::write_fmt::h0473f60143e76874
   3:     0x7d96ae6d2462 - std::sys::backtrace::BacktraceLock::print::he0a43b48023f5fb3
   4:     0x7d96ae6d4a07 - std::panicking::default_hook::{{closure}}::h16c37508eb1e165d
   5:     0x7d96ae6d47f0 - std::panicking::default_hook::h188c5d4452b2e2a8
   6:     0x7d96ad8518a8 - std[fac44eaeb111bcc8]::panicking::update_hook::<alloc[66489a0f9c76ca63]::boxed::Box<rustc_driver_impl[1ee6f045412d773c]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7d96ae6d5253 - std::panicking::rust_panic_with_hook::h1cf1663d92a293a0
   8:     0x7d96ad889dd1 - std[fac44eaeb111bcc8]::panicking::begin_panic::<rustc_errors[8e1a8b7a3353af80]::ExplicitBug>::{closure#0}
   9:     0x7d96ad87efb6 - std[fac44eaeb111bcc8]::sys::backtrace::__rust_end_short_backtrace::<std[fac44eaeb111bcc8]::panicking::begin_panic<rustc_errors[8e1a8b7a3353af80]::ExplicitBug>::{closure#0}, !>
  10:     0x7d96ad87ef9d - std[fac44eaeb111bcc8]::panicking::begin_panic::<rustc_errors[8e1a8b7a3353af80]::ExplicitBug>
  11:     0x7d96ad893d31 - <rustc_errors[8e1a8b7a3353af80]::diagnostic::BugAbort as rustc_errors[8e1a8b7a3353af80]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7d96adde29ac - <rustc_errors[8e1a8b7a3353af80]::DiagCtxtHandle>::span_bug::<rustc_span[7d28ac27f72ec6b1]::span_encoding::Span, alloc[66489a0f9c76ca63]::string::String>
  13:     0x7d96ade67927 - rustc_middle[5606c862b127c2dc]::util::bug::opt_span_bug_fmt::<rustc_span[7d28ac27f72ec6b1]::span_encoding::Span>::{closure#0}
  14:     0x7d96ade4c9ca - rustc_middle[5606c862b127c2dc]::ty::context::tls::with_opt::<rustc_middle[5606c862b127c2dc]::util::bug::opt_span_bug_fmt<rustc_span[7d28ac27f72ec6b1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7d96ade4c85b - rustc_middle[5606c862b127c2dc]::ty::context::tls::with_context_opt::<rustc_middle[5606c862b127c2dc]::ty::context::tls::with_opt<rustc_middle[5606c862b127c2dc]::util::bug::opt_span_bug_fmt<rustc_span[7d28ac27f72ec6b1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7d96ac8b3e97 - rustc_middle[5606c862b127c2dc]::util::bug::span_bug_fmt::<rustc_span[7d28ac27f72ec6b1]::span_encoding::Span>
  17:     0x7d96af4ae73c - <rustc_middle[5606c862b127c2dc]::ty::instance::Instance>::expect_resolve
  18:     0x7d96af9d0695 - <rustc_middle[5606c862b127c2dc]::ty::instance::Instance>::expect_resolve_for_vtable
  19:     0x7d96af6b28f7 - rustc_trait_selection[d64518d2976bfae4]::traits::vtable::vtable_entries::{closure#0}
  20:     0x7d96af41d9f0 - rustc_trait_selection[d64518d2976bfae4]::traits::vtable::vtable_entries
  21:     0x7d96af41d72a - rustc_query_impl[25a774c2c57585ee]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[25a774c2c57585ee]::query_impl::vtable_entries::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5606c862b127c2dc]::query::erase::Erased<[u8; 16usize]>>
  22:     0x7d96af41d6f9 - <rustc_query_impl[25a774c2c57585ee]::query_impl::vtable_entries::dynamic_query::{closure#2} as core[249175d58a5edd5c]::ops::function::FnOnce<(rustc_middle[5606c862b127c2dc]::ty::context::TyCtxt, rustc_type_ir[e0f584499d9d9d64]::binder::Binder<rustc_middle[5606c862b127c2dc]::ty::context::TyCtxt, rustc_type_ir[e0f584499d9d9d64]::predicate::TraitRef<rustc_middle[5606c862b127c2dc]::ty::context::TyCtxt>>)>>::call_once
  23:     0x7d96afb91f59 - rustc_query_system[880048adabd2048e]::query::plumbing::try_execute_query::<rustc_query_impl[25a774c2c57585ee]::DynamicConfig<rustc_query_system[880048adabd2048e]::query::caches::DefaultCache<rustc_type_ir[e0f584499d9d9d64]::binder::Binder<rustc_middle[5606c862b127c2dc]::ty::context::TyCtxt, rustc_type_ir[e0f584499d9d9d64]::predicate::TraitRef<rustc_middle[5606c862b127c2dc]::ty::context::TyCtxt>>, rustc_middle[5606c862b127c2dc]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[25a774c2c57585ee]::plumbing::QueryCtxt, false>
  24:     0x7d96afb91cb8 - rustc_query_impl[25a774c2c57585ee]::query_impl::vtable_entries::get_query_non_incr::__rust_end_short_backtrace
  25:     0x574a5c488044 - <rustc_const_eval[e2da1d737b1da01f]::interpret::eval_context::InterpCx<miri[7fefe668a30715d]::machine::MiriMachine>>::vtable_entries
  26:     0x574a5c4ab00b - <rustc_const_eval[e2da1d737b1da01f]::interpret::eval_context::InterpCx<miri[7fefe668a30715d]::machine::MiriMachine>>::init_fn_call
  27:     0x574a5c5245fa - miri[7fefe668a30715d]::eval::eval_entry::{closure#0}
  28:     0x574a5c52072b - miri[7fefe668a30715d]::eval::eval_entry
  29:     0x574a5c3d4216 - <miri[38dcf146ac8aeb09]::MiriCompilerCalls as rustc_driver_impl[1ee6f045412d773c]::Callbacks>::after_analysis
  30:     0x7d96afdf13ab - rustc_interface[a5b8f6a3ca67129a]::passes::create_and_enter_global_ctxt::<core[249175d58a5edd5c]::option::Option<rustc_interface[a5b8f6a3ca67129a]::queries::Linker>, rustc_driver_impl[1ee6f045412d773c]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  31:     0x7d96afd116d6 - rustc_interface[a5b8f6a3ca67129a]::interface::run_compiler::<(), rustc_driver_impl[1ee6f045412d773c]::run_compiler::{closure#0}>::{closure#1}
  32:     0x7d96afc14c07 - std[fac44eaeb111bcc8]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a5b8f6a3ca67129a]::util::run_in_thread_with_globals<rustc_interface[a5b8f6a3ca67129a]::util::run_in_thread_pool_with_globals<rustc_interface[a5b8f6a3ca67129a]::interface::run_compiler<(), rustc_driver_impl[1ee6f045412d773c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  33:     0x7d96afc150a4 - <<std[fac44eaeb111bcc8]::thread::Builder>::spawn_unchecked_<rustc_interface[a5b8f6a3ca67129a]::util::run_in_thread_with_globals<rustc_interface[a5b8f6a3ca67129a]::util::run_in_thread_pool_with_globals<rustc_interface[a5b8f6a3ca67129a]::interface::run_compiler<(), rustc_driver_impl[1ee6f045412d773c]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[249175d58a5edd5c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7d96afc16681 - std::sys::pal::unix::thread::Thread::new::thread_start::h1f4f8d3a2ffc672f
  35:     0x7d96aa08aa94 - <unknown>
  36:     0x7d96aa117a34 - clone
  37:                0x0 - <unknown>
```

To run into this ICE, calling a method of `Bound` isn't actually necessary. Once the `y.report()` call it reached, it already goes ICE:

```rust
#![allow(coherence_leak_check)]

fn main() {
    let x: &dyn Trait<Marker1> = &();
    let y: &dyn Trait<Marker2> = unsafe { std::mem::transmute(x) };
    y.report();
}

type Marker1 = fn(&()) -> (&(), &'static ());
type Marker2 = fn(&()) -> (&'static (), &());

trait Trait<M> {
    fn report(&self) {}
}
impl<M: Bound> Trait<M> for () {}

trait Bound {}
impl Bound for Marker1 {}
impl Bound for Marker2 where Self: Unimplemented {}

trait Unimplemented {}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f1f89308af6ac9062053658d8945c8e8))

@rustbot label A-miri, A-trait-objects, I-ICE, T-compiler

### PR DESCRIPTION
**Pull request by lukas-code**
## What

Transmuting between trait objects where a generic argument or associated type only differs in bound regions (not bound at or above the trait object's binder) is now UB. For example

* transmuting between `&dyn Trait<for<'a> fn(&'a u8)>` and `&dyn Trait<fn(&'static u8)>` is UB.
* transmuting between `&dyn Trait<Assoc = for<'a> fn(&'a u8)>` and `&dyn Trait<Assoc = fn(&'static u8)>` is UB.
* transmuting between `&dyn Trait<for<'a> fn(&'a u8) -> (&'a u8, &'static u8)>` and `&dyn Trait<for<'a> fn(&'a u8) -> (&'static u8, &'a u8)>` is UB.

Transmuting between subtypes (in either direction) is still allowed, which means that bound regions that are bound at or above the trait object's binder can still be changed:

* transmuting between `&dyn for<'a> Trait<fn(&'a u8)>` and `&dyn for Trait<fn(&'static u8)>` is fine.
* transmuting between `&dyn for<'a> Trait<dyn Trait<fn(&'a u8)>>` and `&dyn for Trait<dyn Trait<fn(&'static u8)>>` is fine.

## Why

Very similar to https://github.com/rust-lang/rust/issues/120217 and https://github.com/rust-lang/rust/issues/120222, changing a trait object's generic argument to a type that only differs in bound regions can still affect the vtable layout and lead to segfaults at runtime (for an example see `src/tools/miri/tests/fail/validity/dyn-transmute-inner-binder.rs`).

Since we already already require that the trait object predicates must be equal modulo bound regions, it is only natural to extend this check to also require type equality considering bound regions.

However, it also makes sense to allow transmutes between a type and a subtype thereof. For example `&dyn for<'a> Trait<&'a u8>` is a subtype of `&dyn Trait<&'static ()>` and they are guaranteed to have the same vtable, so it makes sense to allow this transmute. So that's why bound lifetimes that are bound to the trait object itself are treated as free lifetime for the purpose of this check.  

Note that codegen already relies on the property that subtyping cannot change the the vtable and this is asserted here (note the leak check): https://github.com/rust-lang/rust/blob/251206c27b619ccf3a08e2ac4c525dc343f08492/compiler/rustc_codegen_ssa/src/base.rs#L106-L153

Furthermore, we allow some pointer-to-pointer casts like `*const dyn for<'a> Trait<&'a u8>` to `*const Wrapper<dyn Trait<&'static u8>>` that instantiate the trait object binder and are currently lowered to a single pointer-to-pointer cast in MIR (`CastKind::PtrToPtr`) and *not* an unsizing coercion (`CastKind::PointerCoercion(Unsize)`), so the current MIR lowering of these would be UB if we didn't allow subtyping transmutes.

---

fixes https://github.com/rust-lang/rust/issues/135230
cc @rust-lang/opsem
r? @compiler-errors for the implementation

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/eval_context.rs [hunk 1]
```diff
@@ -323,12 +324,25 @@ impl<'tcx, M: Machine<'tcx>> InterpCx<'tcx, M> {
...
+    /// This is called on [`ty::PolyExistentialTraitRef`] or [`ty::PolyExistentialProjection`]
+    /// and checks whether there is a subtyping relation between them in either direction.
+    ///
+    /// # Examples
+    ///
+    /// - returns `true` for `dyn for<'a> Trait<fn(&'a u8)>` and `dyn Trait<fn(&'static u8)>`
+    /// - returns `false` for `dyn Trait<for<'a> fn(&'a u8)>` and either of the above
     #[instrument(level = "trace", skip(self), ret)]
-    pub(super) fn eq_in_param_env<T>(&self, a: T, b: T) -> bool
+    pub(super) fn relate_dyn_predicates_bivariantly<T>(
```
Comment (lcnr) [inline compiler/rustc_const_eval/src/interpret/eval_context.rs:338]: bivariance is different from being bidirectional subtypes

https://github.com/lcnr/random-rust-snippets/issues/3

change it to `eq_modulo_regions`? :thinking: 

:+1: on manually adding the leak-check here. The alternative would be to instantiate all regions with existentials and do a proper region check at the end, not totally sure whether a leak-check will always be sufficient given that it doesn't have to be catch all errors

Comment (lukas-code) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:338]: > bivariance is different from being bidirectional subtypes

Hm, this comment here made me believe that they are supposed to be the same:

https://github.com/rust-lang/rust/blob/336209eef13882bd1e211b24779584cb7ef911eb/compiler/rustc_infer/src/infer/at.rs#L241-L246

I see now that bivariance as implemented does indeed just do nothing, so :+1: on renaming this to avoid confusion.

---

Also, after thinking about this more, I think we can also just structurally compare the predicates (after instantiating the binder + normalizing), no leak check required, because the soundness of `TypeId` requires structural equality anyway (https://github.com/rust-lang/rust/issues/97156).

Is there any reason why this would be a bad idea?

Comment (lcnr) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs:338]: > Hm, this comment here made me believe that they are supposed to be the same:

This comment is wrong then :grin: 

> Also, after thinking about this more, I think we can also just structurally compare the predicates (after instantiating the binder + normalizing), no leak check required, because the soundness of TypeId requires structural equality anyway (https://github.com/rust-lang/rust/issues/97156).
>
> Is there any reason why this would be a bad idea?

don't think so, would have some false negatives in generic code, but :shrug:

File: src/tools/miri/tests/fail/validity/dyn-trait-leak-check.rs [hunk 2]
```diff
@@ -0,0 +1,41 @@
+// Test that transmuting from `&dyn Dyn<fn(&'static ())>` to `&dyn Dyn<for<'a> fn(&'a ())>` is UB.
+//
+// The vtable of `() as Dyn<fn(&'static ())>` and `() as Dyn<for<'a> fn(&'a ())>` can have
+// different entries and, because in the former the entry for `foo` is vacant, this test will
+// segfault at runtime.
+
+trait Dyn<U> {
```
Comment (RalfJung) [inline src/tools/miri/tests/fail/validity/dyn-trait-leak-check.rs:7]: That's a confusing trait name.^^ Even `Trait` would be better...

File: src/tools/miri/tests/pass/validity/dyn-trait-bivariant-transmutes.rs
Comment (RalfJung) [inline src/tools/miri/tests/pass/validity/dyn-trait-bivariant-transmutes.rs:1]: This creates a new folder, I don't think we should do that.

Adding it as a new test inside `tests/pass/dyn-upcast.rs` seems better.

File: src/tools/miri/tests/pass/validity/dyn-trait-bivariant-transmutes.rs [hunk 3]
```diff
@@ -0,0 +1,26 @@
+// Test that transmuting between subtypes of dyn traits is fine, even in the
+// "wrong direction", i.e. going from a lower-ranked to a higher-ranked dyn trait.
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/validity/dyn-trait-bivariant-transmutes.rs:2]:
```suggestion
// "wrong direction", i.e. going from a lower-ranked to a higher-ranked dyn trait.
// Note that compared to the `dyn-trait-leak-check` test, the `for` is on the *outside* here!
```

**Comment by lukas-code** [comment]
(this now includes https://github.com/rust-lang/rust/pull/135318 to avoid conflicts, sorry for the pings)

File: compiler/rustc_const_eval/src/interpret/eval_context.rs (hunk 1 above)
Comment (lukas-code) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs]: Alright, replaced this with just `==` now.

[the remark this answers is not in the document]
Comment (lukas-code) [reply compiler/rustc_const_eval/src/interpret/eval_context.rs]: This function is gone now, because turns out that this entire complicated operation is (almost) just equivalent to `==` ^^

File: src/tools/miri/tests/fail/validity/dyn-trait-leak-check.rs (hunk 2 above)
Comment (lukas-code) [reply src/tools/miri/tests/fail/validity/dyn-trait-leak-check.rs:7]: renamed to `Trait`

**Comment by compiler-errors** [comment]
Let's wait for #135318 to land. Sorry for blocking your PR 😓 

@rustbot blocked

**Review by compiler-errors — APPROVED** [review]
LGTM. Sorry for taking a bit to review this.

I don't believe this needs an FCP, because it simply fixes a shortcoming in vtable validation code -- this is *morally* equivalent[^1] to changing the `eq_in_param_env` function to instantiate the binder of the principal trait ref (à la #135318) and then performing a [leak check](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/region_constraints/struct.RegionConstraintCollector.html#method.leak_check) at the end of processing obligations. 

The fact that we weren't previously leak-checking (or equivalent) allows certain kinds of transmutes to pass miri today that clearly allow changing the principal trait ref in a way that constitutes different types (e.g. `fn(&'static ())` and `for<'a> fn(&'a ())`).

[^1]: Though simpler b/c we don't need to actually go through the whole dance of using an infcx if we expect the types to be fully normalized and region erased.

**Comment by compiler-errors** [comment]
cc @rust-lang/opsem and @rust-lang/types once again, if someone *does* think this needs an FCP then please explain why. Otherwise I'll approve this in a couple of days.

**Comment by RalfJung** [comment]
Making some more dyn trait type transmutes UB in a very gray area seems entirely reasonable to me. Our reference says that:

> `dyn Trait` metadata must be a pointer to a compiler-generated vtable for `Trait`. (For raw pointers, this requirement remains a subject of some debate.)

`Trait<fn(&'static ())>` and `Trait<for<'a> fn(&'a ())>` are not the same trait. So it is basically a bug that we accepted this so far. I don't think this needs an FCP, we haven't officially decided anything in this area yet.
