### PR TITLE
diagnostics: be more careful when suggesting struct fields

### LINKED ISSUE #116334: decl_macro. no field `0` on type. a field with a similar name exists: `0`
I tried this code:

https://github.com/planetoryd/rust_bug_missing_field

```rust
#![feature(decl_macro)]

make_struct!(Uh);

macro make_struct ($id:ident) {
    pub struct $id(pub i32);
}

fn main() {
    let k = Uh(2);
    println!("{}", k.0);
}
```

The equivalent code without macro works.

```rust
hash@hash-pc /s/e/missing_field (master)> cargo b
   Compiling missing_field v0.1.0 (/space/experim/missing_field)
error[E0609]: no field `0` on type `Uh`
  --> src/main.rs:11:22
   |
11 |     println!("{}", k.0);
   |                      ^ help: a field with a similar name exists: `0`

For more information about this error, try `rustc --explain E0609`.
error: could not compile `missing_field` (bin "missing_field") due to previous error
warning: build failed, waiting for other jobs to finish...
```

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (e0d7ed1f4 2023-10-01)
binary: rustc
commit-hash: e0d7ed1f453fb54578cc96dfea859b0e7be15016
commit-date: 2023-10-01
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: **17.0.2**
```

### PR DESCRIPTION
**Pull request by fmease**
Consolidate the various places which filter out struct fields that shouldn't be suggested into a single function.

Previously, each of those code paths had slightly different and incomplete metrics for no good reason. Now, there's only a single 'complete' metric (namely `is_field_suggestable`) which also filters out hygienic fields that come from different syntax contexts.

Fixes #116334.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -1687,4 +1687,18 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        field.vis.is_accessible_from(self.tcx.parent_module(hir_id), self.tcx)
+            // The field must not be unstable.
+            && !matches!(
+                self.tcx.eval_stability(field.did, None, rustc_span::DUMMY_SP, None),
+                rustc_middle::middle::stability::EvalResult::Deny { .. }
+            )
+            // If the field is from an external crate it must not be `doc(hidden)`.
+            && (field.did.is_local() || !self.tcx.is_doc_hidden(field.did))
+            // If the field is hygienic it must not originate from a macro expansion.
+            && !self.tcx.def_ident_span(field.did).unwrap().normalize_to_macros_2_0().from_expansion()
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1702]: should we check that the span ctxts are the same? Does this affect our ability to suggest hygenic fields from *within* a macro?

Comment (fmease) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1702]: Have to check, good points.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1702]: Maybe test something like:

```
#![feature(decl_macro)]

pub macro foo() {
    fn test() {
        struct Hello { world: () }
        let x: Hello = Hello { worl: () };
    }
}

foo!();
```

Comment (fmease) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1702]: Yep, you're right. It's obvious in hindsight.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1702]: No worries. We have lots of diagnostics that are subtly wrong due to being overly defensive, resulting them just totally not applying within macros even when they should. Thx for investigating.

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -1687,4 +1687,23 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
     }
+
+    pub(crate) fn is_field_suggestable(
+        &self,
+        field: &ty::FieldDef,
+        hir_id: HirId,
+        span: Span,
+    ) -> bool {
+        // The field must be visible in the containing module.
+        field.vis.is_accessible_from(self.tcx.parent_module(hir_id), self.tcx)
```
Comment (fmease) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1698]: I've taken `is_accessible_from(parent_module())` from one of the places I've removed but another one tries to obtain the `DefScope` instead of the parent module (via `adjust_ident_and_get_scope`). Which one is more correct / general?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1698]: I think the latter, but I doubt it matters. If something is reachable from an item then it's reachable from its parent module, no?

**Review by compiler-errors — APPROVED** [review]
r=me

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 2 above)
Comment (fmease) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1698]: I wonder if there are some edge cases like `structs`s defined inside of a `fn` instead of a module. Not sure.
