### PR TITLE
Re-implement async fn drop order lowering 

### LINKED ISSUE #61187: Internal compiler error in nightly when reversing a vector inside a async fn
Got an internal compiler error when reversing a vector inside a async fn

I tried this code:

```rust
#![feature(async_await)]

fn main() {
}

async fn response(data: Vec<u8>) {
    data.reverse();
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4e90f405e1d73fdbc7b009a3de23bcae))

This happened:

```
$ RUST_BACKTRACE=1 cargo check
    Checking rust-error-testing-unfold-option-unwrap v0.1.0 (/home/sindre/src/rust/rust-error-testing-unfold-option-unwrap)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic
             at src/libcore/panicking.rs:49
  10: rustc_mir::borrow_check::mutability_errors::<impl rustc_mir::borrow_check::MirBorrowckCtxt>::report_mutability_error
  11: rustc_mir::borrow_check::MirBorrowckCtxt::access_place
  12: <rustc_mir::borrow_check::MirBorrowckCtxt as rustc_mir::dataflow::DataflowResultsConsumer>::visit_statement_entry
  13: rustc_mir::borrow_check::do_mir_borrowck
  14: rustc::ty::context::GlobalCtxt::enter_local
  15: rustc_mir::borrow_check::mir_borrowck
  16: rustc::ty::query::__query_compute::mir_borrowck
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  18: rustc::dep_graph::graph::DepGraph::with_task_impl
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  20: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  21: rustc::util::common::time
  22: rustc_interface::passes::analysis
  23: rustc::ty::query::__query_compute::analysis
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  27: rustc::ty::context::tls::enter_global
  28: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  29: rustc_interface::passes::create_global_ctxt::{{closure}}
  30: rustc_interface::interface::run_compiler_in_existing_thread_pool
  31: std::thread::local::LocalKey<T>::with
  32: scoped_tls::ScopedKey<T>::set
  33: syntax::with_globals
query stack during panic:
#0 [mir_borrowck] processing `response::{{closure}}#0`
#1 [analysis] running analysis passes on this crate
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (dec4c5201 2019-05-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `rust-error-testing-unfold-option-unwrap`.

To learn more, run the command again with --verbose.
```

## Meta

```
$ rustc --version --verbose
rustc 1.36.0-nightly (dec4c5201 2019-05-24)
binary: rustc
commit-hash: dec4c5201f88efbc3020b04ba96a5ee2c3b6cfcd
commit-date: 2019-05-24
host: x86_64-unknown-linux-gnu
release: 1.36.0-nightly
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by davidtwco**
This PR re-implements the async fn drop order lowering changes so
that it all takes place in HIR lowering, building atop the work done by
@eddyb to refactor `Res::Upvar`.

Previously, this types involved in the lowering were constructed in
libsyntax as they had to be used during name resolution and HIR
lowering. This was awful because none of that logic should have existed
in libsyntax.

This commit also changes `ArgSource` to keep a `HirId` to the original
argument pattern rather than a cloned copy of the pattern.

Only b7aa4ed and 71fb8fa should be reviewed, any other commits
are from #61276 (though 447e336 might end up staying in this PR).

As a nice side effect, it also fixes #61187 (cc #61192).

r? @eddyb 
cc @cramertj

### CODE REVIEW

File: src/librustc/hir/lowering.rs [hunk 1]
```diff
@@ -2995,56 +3006,177 @@ impl<'a> LoweringContext<'a> {
...
+
+                // Check if this is a binding pattern, if so, we can optimize and avoid adding a
+                // `let <pat> = __argN;` statement. In this case, we do not rename the argument.
+                let (ident, is_simple_argument) = match argument.pat.node {
+                    hir::PatKind::Binding(hir::BindingAnnotation::Unannotated, _, ident, _) =>
+                        (ident, true),
+                    _ => {
+                        // Replace the ident for bindings that aren't simple.
+                        let name = format!("__arg{}", index);
+                        let ident = Ident::from_str(&name).gensym();
```
Comment (matthewjasper) [inline src/librustc/hir/lowering.rs]: `gensym` isn't needed in HIR

Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: Fixed, thanks!

Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: Fixed, thanks!

**Comment by davidtwco** [comment]
I'll hold off on rebasing this until #61276 lands or makes significant changes.

File: src/librustc/infer/error_reporting/nice_region_error/different_lifetimes.rs [hunk 2]
```diff
@@ -86,12 +86,14 @@ impl<'a, 'gcx, 'tcx> NiceRegionError<'a, 'gcx, 'tcx> {
...
-        let span_label_var1 = match anon_arg_sup.original_pat().simple_ident() {
+        let arg_sup_pat = self.tcx().hir().original_pat_of_argument(anon_arg_sup);
+        let span_label_var1 = match arg_sup_pat.simple_ident() {
             Some(simple_ident) => format!(" from `{}`", simple_ident),
             None => String::new(),
         };
 
-        let span_label_var2 = match anon_arg_sub.original_pat().simple_ident() {
+        let arg_sub_pat = self.tcx().hir().original_pat_of_argument(anon_arg_sub);
+        let span_label_var2 = match arg_sub_pat.simple_ident() {
```
Comment (eddyb) [inline src/librustc/infer/error_reporting/nice_region_error/different_lifetimes.rs]: Couldn't you just use the original name if it's a `simple_ident()`, to keep `simple_ident()` working?
Local names in HIR are merely informative, since the identity of a local is determined by its `HirId`.

File: src/librustc/infer/error_reporting/nice_region_error/named_anon_conflict.rs [hunk 3]
```diff
@@ -95,7 +95,8 @@ impl<'a, 'gcx, 'tcx> NiceRegionError<'a, 'gcx, 'tcx> {
             }
         }
 
-        let (error_var, span_label_var) = match arg.original_pat().simple_ident() {
+        let arg_pat = self.tcx().hir().original_pat_of_argument(arg);
+        let (error_var, span_label_var) = match arg_pat.simple_ident() {
```
Comment (eddyb) [inline src/librustc/infer/error_reporting/nice_region_error/named_anon_conflict.rs]: Same here.

File: src/librustc/middle/resolve_lifetime.rs [hunk 4]
```diff
@@ -2421,7 +2421,8 @@ impl<'a, 'tcx> LifetimeContext<'a, 'tcx> {
 
             let help_name = if let Some(body) = parent {
                 let arg = &self.tcx.hir().body(body).arguments[index];
-                format!("`{}`", self.tcx.hir().hir_to_pretty_string(arg.original_pat().hir_id))
+                let original_pat = self.tcx.hir().original_pat_of_argument(arg);
+                format!("`{}`", self.tcx.hir().hir_to_pretty_string(original_pat.hir_id))
```
Comment (eddyb) [inline src/librustc/middle/resolve_lifetime.rs]: Shouldn't this be using `simple_ident()` to avoid printing a potentially confusing/ambiguous pattern?

File: src/librustc_mir/build/mod.rs [hunk 5]
```diff
@@ -878,26 +901,23 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
-            let mut name = None;
-            if let Some(pat) = pattern {
+            let (name, span) = if let Some(pat) = user_pattern {
                 match pat.node {
                     hir::PatKind::Binding(hir::BindingAnnotation::Unannotated, _, ident, _)
-                    | hir::PatKind::Binding(hir::BindingAnnotation::Mutable, _, ident, _) => {
-                        name = Some(ident.name);
-                    }
-                    _ => (),
+                    | hir::PatKind::Binding(hir::BindingAnnotation::Mutable, _, ident, _) =>
```
Comment (eddyb) [inline src/librustc_mir/build/mod.rs]: Same here, you wouldn't need the original pattern if you reused the name.

File: src/librustdoc/clean/mod.rs [hunk 6]
```diff
@@ -2018,8 +2018,9 @@ impl<'a> Clean<Arguments> for (&'a [hir::Ty], hir::BodyId) {
 
         Arguments {
             values: self.0.iter().enumerate().map(|(i, ty)| {
+                let original_pat = cx.tcx.hir().original_pat_of_argument(&body.arguments[i]);
                 Argument {
-                    name: name_from_pat(&body.arguments[i].original_pat()),
+                    name: name_from_pat(original_pat),
```
Comment (eddyb) [inline src/librustdoc/clean/mod.rs]: And same here, so that's all the uses of `ArgSource`!

File: src/librustc/hir/lowering.rs [hunk 7]
```diff
@@ -2968,11 +2972,18 @@ impl<'a> LoweringContext<'a> {
         bounds.iter().map(|bound| self.lower_param_bound(bound, itctx.reborrow())).collect()
     }
 
-    fn lower_block(&mut self, b: &Block, targeted_by_break: bool) -> P<hir::Block> {
+    fn lower_block_and_prepend_statements(
+        &mut self,
+        b: &Block,
+        targeted_by_break: bool,
+        f: impl FnOnce(&mut Vec<hir::Stmt>),
```
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: I think it would be cleaner to just make this a `Vec<hir::Stmt>` instead of a callback. Then you can construct it normally, without `.insert(0)`.

File: src/librustc/hir/lowering.rs [hunk 8]
```diff
@@ -1148,18 +1142,32 @@ impl<'a> LoweringContext<'a> {
...
+        body: impl FnOnce(&mut LoweringContext<'_>) -> hir::Expr,
+    ) -> hir::BodyId {
+        self.lower_body(|this| (
+            decl.inputs.iter().map(|x| this.lower_arg(x)).collect(),
+            body(this),
+        ))
+    }
+
+    fn lower_const_body(&mut self, expr: &Expr) -> hir::BodyId {
+        self.lower_body(|this| (hir_vec![], this.lower_expr(expr)))
```
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: I wonder if maybe we should've done this in a separate PR? Or commit? It doesn't matter much though.

File: src/librustc/infer/error_reporting/nice_region_error/different_lifetimes.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc/infer/error_reporting/nice_region_error/different_lifetimes.rs]: Fixed.

File: src/librustc/infer/error_reporting/nice_region_error/named_anon_conflict.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc/infer/error_reporting/nice_region_error/named_anon_conflict.rs]: Fixed.

File: src/librustc/middle/resolve_lifetime.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc/middle/resolve_lifetime.rs]: Fixed.

File: src/librustc_mir/build/mod.rs (hunk 5 above)
Comment (davidtwco) [reply src/librustc_mir/build/mod.rs]: Fixed.

File: src/librustdoc/clean/mod.rs (hunk 6 above)
Comment (davidtwco) [reply src/librustdoc/clean/mod.rs]: Fixed.

File: src/librustc/hir/lowering.rs (hunk 7 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: Fixed.

File: src/librustc/hir/lowering.rs (hunk 8 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: Fixed.

File: src/librustc_mir/build/mod.rs [hunk 9]
```diff
@@ -883,21 +881,13 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
-                    }
-                    _ => (),
-                }
-            }
-
-            let source_info = SourceInfo {
-                scope: OUTERMOST_SOURCE_SCOPE,
-                span: pattern.map_or(self.fn_span, |pat| pat.span)
+            let (name, span) = if let Some(pat) = pattern {
+                (pat.simple_ident().map(|ident| ident.name), pat.span)
```
Comment (eddyb) [inline src/librustc_mir/build/mod.rs]: @pnkfelix @nikomatsakis @matthewjasper Is this correct, as far as you know?
(if nobody replies I expect we can just merge without this change, this only affects debuginfo, and not in a significant way.

File: src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr [hunk 10]
```diff
@@ -30,7 +30,7 @@ error[E0106]: missing lifetime specifier
 LL | fn foo2(_: &'_ u8, y: &'_ u8) -> &'_ u8 { y }
    |                                   ^^ expected lifetime parameter
    |
-   = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `_` or `y`
+   = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from argument 1 or `y`
```
Comment (eddyb) [inline src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr]: @estebank Just to check with you, this is an improvement, right?

**Review by eddyb — APPROVED** [review]
r=me with MIR building changes backed out, or after someone else checks off on them

File: src/librustc/hir/lowering.rs [hunk 11]
```diff
@@ -3025,56 +3014,143 @@ impl<'a> LoweringContext<'a> {
...
+                |this| {
+                    let mut stmts = vec![];
+                    for (move_stmt, pattern_stmt) in statements.drain(..) {
+                        // Insert the `let __argN = __argN` statement first.
+                        stmts.push(move_stmt);
+                        // Then insert the `let <pat> = __argN` statement, if there is one.
+                        if let Some(pattern_stmt) = pattern_stmt {
+                            stmts.push(pattern_stmt);
+                        }
+                    }
```
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: Wait, I just noticed this, can't you just create this `Vec` like this from the start?

File: src/librustc/hir/lowering.rs [hunk 12]
```diff
@@ -5187,6 +5217,10 @@ impl<'a> LoweringContext<'a> {
         }
     }
 
+    fn arg(&mut self, hir_id: hir::HirId, pat: P<hir::Pat>, source: hir::ArgSource) -> hir::Arg {
+        hir::Arg { hir_id, pat, source }
```
Comment (eddyb) [inline src/librustc/hir/lowering.rs]: `hir_id: self.next_id()` would probably be more ergonomic.

File: src/librustc_mir/build/mod.rs (hunk 9 above)
Comment (matthewjasper) [reply src/librustc_mir/build/mod.rs]: I think that the corresponding change needs to be made on line 925 below. Or this should be combined with that check.

File: src/librustc/hir/lowering.rs (hunk 12 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: This function is given the `HirId` of the original argument rather than a newly generated one.

File: src/librustc/hir/lowering.rs (hunk 11 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: I’m not sure what you mean by this comment?

File: src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr (hunk 10 above)
Comment (estebank) [reply src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr]: @eddyb It'd might be even better if we added spans to it, like below, but this is an improvement in my eyes

```
error[E0106]: missing lifetime specifier
  --> $DIR/underscore-lifetime-binders.rs:16:35
   |
LL | fn foo2(_: &'_ u8, y: &'_ u8) -> &'_ u8 { y }
   |                                   ^^ expected lifetime parameter
   |
help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from argument 1 or `y`
   |
LL | fn foo2(_: &'_ u8, y: &'_ u8) -> &'_ u8 { y }
   |         ^          ^

```

File: src/librustc/hir/lowering.rs (hunk 12 above)
Comment (eddyb) [reply src/librustc/hir/lowering.rs]: Ah, then maybe don't add this method?

File: src/librustc/hir/lowering.rs (hunk 11 above)
Comment (eddyb) [reply src/librustc/hir/lowering.rs]: Instead of creating a `Vec<(Stmt, Option<Stmt>)>` and then flattening it into `Vec<Stmt>`, you can create the latter from the start.

File: src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr (hunk 10 above)
Comment (eddyb) [reply src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr]: It would be even better if it pointed at the lifetimes in the signature (which is information we could collect).

Comment (davidtwco) [reply src/test/ui/underscore-lifetime/underscore-lifetime-binders.stderr]: I think it might be best if we left this as a follow-up (it's a bit out of scope for this PR). I'd be happy to do it after this though.

File: src/librustc/hir/lowering.rs (hunk 12 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: I've removed it.

File: src/librustc/hir/lowering.rs (hunk 11 above)
Comment (davidtwco) [reply src/librustc/hir/lowering.rs]: Oh, I hadn't spotted that, fixed.

File: src/librustc_mir/build/mod.rs (hunk 9 above)
Comment (davidtwco) [reply src/librustc_mir/build/mod.rs]: @matthewjasper could you clarify on what corresponding change needs to be made? 

I'm probably misunderstanding what you're referring to, but as far as I can tell the `BindingMode::ByValue` checked on line 925 is equivalent to `BindingAnnotation::Unannotated` and `BindingAnnotation::Mutable` that `simple_ident` checks (and that the code this PR changes checked for)?

Comment (matthewjasper) [reply src/librustc_mir/build/mod.rs]: You also need to check that there's no subpattern.

Comment (davidtwco) [reply src/librustc_mir/build/mod.rs]: Ah, hadn't spotted that, fixed, thanks!

**Review by eddyb — APPROVED** [review]
