### PR TITLE
Fix diagnostics for `@ ..` binding pattern in tuples and tuple structs

### LINKED ISSUE #72574: Diagnostics for `@ ..` idiom use in tuple and tuple struct patterns is incorrect
@estebank and I are working on diagnostics for the `@ ..` rest idiom in slice patterns (#72534) and came across this issue when an attempt is made to use it in tuples and tuple structs.

IIUC, this is allowed:

#### tuple ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fd26ccb092664465d57a0da45e4b51a3))

```rust
fn main() {
    let x = (1, 2, 3);
    match x {
        (_a, ..) => {}
        _ => {}
    }
}
```

#### tuple struct ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=36bbaac9c00e19fab6f5e9493087523e))

```rust
struct Binder(i32, i32, i32);

fn main() {
    let x = Binder(1, 2, 3);
    match x {
        Binder(_a, ..) => {}
        _ => {}
    }
}
```

and this is not allowed (note the addition of `[id] @`):

#### tuple ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cc75c579abac2802713c7baed0a85dba))

```rust
fn main() {
    let x = (1, 2, 3);
    match x {
        (_a, _x @ ..) => {}
        _ => {}
    }
}
```

#### tuple struct ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=037263f68c19cdf58aaaec6587212b66))

```rust
struct Binder(i32, i32, i32);

fn main() {
    let x = Binder(1, 2, 3);
    match x {
        Binder(_a, _x @ ..) => {}
        _ => {}
    }
}
```

The error messages for the tuple and tuple struct cases include the following incorrect information:

> error: `..` patterns are not allowed here

This should state that the `@ ..` id binding to rest is not allowed.  `..` patterns **are** allowed.

> note: only allowed in tuple, tuple struct, and slice patterns

`@ ..` is only allowed in slice patterns, not in tuple or tuple struct patterns.  This should state that the idiom is only allowed in slice patterns.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #72574 
Associated https://github.com/rust-lang/rust/pull/72534 https://github.com/rust-lang/rust/issues/72373

Includes a new suggestion with `Applicability::MaybeIncorrect` confidence level.

#### tuple

```
error: `..` patterns are not allowed here
 --> src/main.rs:4:19
  |
4 |         (_a, _x @ ..) => {}
  |                   ^^
  |
  = note: only allowed in tuple, tuple struct, and slice patterns

error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
3 |     match x {
  |           - this expression has type `({integer}, {integer}, {integer})`
4 |         (_a, _x @ ..) => {}
  |         ^^^^^^^^^^^^^ expected a tuple with 3 elements, found one with 2 elements
  |
  = note: expected tuple `({integer}, {integer}, {integer})`
             found tuple `(_, _)`

error: aborting due to 2 previous errors
```

#### tuple struct

```
error: `..` patterns are not allowed here
 --> src/main.rs:6:25
  |
6 |         Binder(_a, _x @ ..) => {}
  |                         ^^
  |
  = note: only allowed in tuple, tuple struct, and slice patterns

error[E0023]: this pattern has 2 fields, but the corresponding tuple struct has 3 fields
 --> src/main.rs:6:9
  |
1 | struct Binder(i32, i32, i32);
  | ----------------------------- tuple struct defined here
...
6 |         Binder(_a, _x @ ..) => {}
  |         ^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 2

error: aborting due to 2 previous errors
```

### After

*Note: final output edited during source review discussion, see thread for details*

#### tuple

```
error: `_x @` is not allowed in a tuple
 --> src/main.rs:4:14
  |
4 |         (_a, _x @ ..) => {}
  |              ^^^^^^^ is only allowed in a slice
  |
help: replace with `..` or use a different valid pattern
  |
4 |         (_a, ..) => {}
  |              ^^

error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
3 |     match x {
  |           - this expression has type `({integer}, {integer}, {integer})`
4 |         (_a, _x @ ..) => {}
  |         ^^^^^^^^^^^^^ expected a tuple with 3 elements, found one with 1 element
  |
  = note: expected tuple `({integer}, {integer}, {integer})`
             found tuple `(_,)`

error: aborting due to 2 previous errors
```

#### tuple struct

```
error: `_x @` is not allowed in a tuple struct
 --> src/main.rs:6:20
  |
6 |         Binder(_a, _x @ ..) => {}
  |                    ^^^^^^^ is only allowed in a slice
  |
help: replace with `..` or use a different valid pattern
  |
6 |         Binder(_a, ..) => {}
  |                    ^^

error[E0023]: this pattern has 1 field, but the corresponding tuple struct has 3 fields
 --> src/main.rs:6:9
  |
1 | struct Binder(i32, i32, i32);
  | ----------------------------- tuple struct defined here
...
6 |         Binder(_a, _x @ ..) => {}
  |         ^^^^^^^^^^^^^^^^^^^ expected 3 fields, found 1

error: aborting due to 2 previous errors
```

r? @estebank

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Modified the suggestion slightly to better address attempts to use a BindingMode in the binding.

e.g., 

```
error: `_x @` is not allowed in a tuple
 --> src/main.rs:4:14
  |
4 |         (_a, ref mut _x @ ..) => {}
  |              ^^^^^^^^^^^^^^^ is only allowed in a slice
  |
help: replace with `..` or use a different valid pattern
  |
4 |         (_a, ..) => {}
  |              ^^

error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
3 |     match x {
  |           - this expression has type `({integer}, {integer}, {integer})`
4 |         (_a, ref mut _x @ ..) => {}
  |         ^^^^^^^^^^^^^^^^^^^^^ expected a tuple with 3 elements, found one with 1 element
  |
  = note: expected tuple `({integer}, {integer}, {integer})`
             found tuple `(_,)`

error: aborting due to 2 previous errors
```

File: src/librustc_ast_lowering/pat.rs [hunk 1]
```diff
@@ -102,10 +103,34 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                    let sp = pat.span;
+                    self.diagnostic()
+                        .struct_span_err(
+                            sp,
+                            &format!("`{} @` is not allowed in a {}", ident.name, ctx),
+                        )
+                        .span_label(sp, "is only allowed in a slice")
+                        .span_suggestion_verbose(
+                            sp,
+                            "replace with `..` or use a different valid pattern",
```
Comment (estebank) [inline src/librustc_ast_lowering/pat.rs:124]:
```suggestion
                            &format!("If you don't need to use the contents of {}, discard the tuple's remaining fields", ident),
```

File: src/test/ui/issues/issue-72574-1.stderr [hunk 2]
```diff
@@ -0,0 +1,25 @@
+error: `_x @` is not allowed in a tuple
+  --> $DIR/issue-72574-1.rs:4:14
+   |
+LL |         (_a, _x @ ..) => {}
+   |              ^^^^^^^ is only allowed in a slice
+   |
+help: replace with `..` or use a different valid pattern
+   |
+LL |         (_a, ..) => {}
+   |              ^^
```
Comment (estebank) [inline src/test/ui/issues/issue-72574-1.stderr:10]: It'd be nice if we also gave a suggestion to be able to use the fields:

```
help: alternatively, bind each tuple field independently
   |
LL |         (_a, field1, field2) => {}
   |              ^^^^^^^^^^^^^^
```

Edit: right, at parse time you don't _know_ the size of the tuple. To give this suggestion accurately you'd need to delay the error to after resolve. Let's instead either use placeholders for now or a stand alone `help`. Note that `help` will come before the suggestion (always) so consider changing the wording appropriately.

File: src/librustc_ast_lowering/pat.rs [hunk 3]
```diff
@@ -102,10 +103,34 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                // Found a sub-tuple pattern `$binding_mode $ident @ ..`.
+                // This is not allowed as a sub-tuple pattern
+                PatKind::Ident(ref _bm, ident, Some(ref sub)) if sub.is_rest() => {
+                    let sp = pat.span;
+                    self.diagnostic()
+                        .struct_span_err(
+                            sp,
+                            &format!("`{} @` is not allowed in a {}", ident.name, ctx),
+                        )
+                        .span_label(sp, "is only allowed in a slice")
```
Comment (estebank) [inline src/librustc_ast_lowering/pat.rs:121]:
```suggestion
                        .span_label(sp, "this is only allowed in slice patterns")
```

File: src/librustc_ast_lowering/pat.rs [hunk 4]
```diff
@@ -102,10 +103,34 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
             // Note that unlike for slice patterns,
             // where `xs @ ..` is a legal sub-slice pattern,
             // it is not a legal sub-tuple pattern.
-            if pat.is_rest() {
-                rest = Some((idx, pat.span));
-                break;
+            match pat.kind {
+                // Found a sub-tuple rest pattern
+                PatKind::Rest => {
+                    rest = Some((idx, pat.span));
```
Comment (estebank) [inline src/librustc_ast_lowering/pat.rs:109]: Shouldn't we also have this line in the other arm? That way we _won't_ emit the mismatched pattern size error, which would be solved if the pattern is changed. We would _still_ emit errors if `ident` is being used inside the arm, but that should be ok.

File: src/test/ui/issues/issue-72574-1.rs [hunk 5]
```diff
@@ -0,0 +1,9 @@
+fn main() {
+    let x = (1, 2, 3);
+    match x {
+        (_a, _x @ ..) => {}
+        _ => {}
+    }
+}
+//~^^^^ ERROR `_x @` is not allowed in a tuple
+//~^^^^^ ERROR mismatched types [E0308]
```
Comment (estebank) [inline src/test/ui/issues/issue-72574-1.rs:9]: `|` continues checking on the same line as the check above.
```suggestion
//~| ERROR mismatched types [E0308]
```

-----

That being said, if you change lowering so as it won't emit the mismatched types error, you'll have to remove this.

File: src/test/ui/issues/issue-72574-2.rs [hunk 6]
```diff
@@ -0,0 +1,11 @@
...
+
+fn main() {
+    let x = Binder(1, 2, 3);
+    match x {
+        Binder(_a, _x @ ..) => {}
+        _ => {}
+    }
+}
+//~^^^^ ERROR `_x @` is not allowed in a tuple struct
+//~^^^^^ ERROR this pattern has 1 field, but the corresponding tuple struct has 3 fields [E0023]
```
Comment (estebank) [inline src/test/ui/issues/issue-72574-2.rs:11]: Same here.

**Review by estebank — CHANGES_REQUESTED** [review]
A few nitpicks, let me know what you think.

File: src/librustc_ast_lowering/pat.rs (hunk 4 above)
Comment (chrissimpkins) [reply src/librustc_ast_lowering/pat.rs:109]: Looking into this.

File: src/test/ui/issues/issue-72574-1.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.rs:9]: Will address these error annotations locally once I have a look at the errors emitted with the changes that you recommended.

File: src/test/ui/issues/issue-72574-1.stderr (hunk 2 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.stderr:10]: > Let's instead either use placeholders for now or a stand alone help

Can you expand on this?  I'm not sure that I completely follow the ask here.

File: src/test/ui/issues/issue-72574-2.rs (hunk 6 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-2.rs:11]: Will change this once I have a look at the errors following your recommended source changes.

File: src/librustc_ast_lowering/pat.rs (hunk 4 above)
Comment (chrissimpkins) [reply src/librustc_ast_lowering/pat.rs:109]: This is correct Esteban.  I will push a new commit with this change.

File: src/test/ui/issues/issue-72574-1.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.rs:9]: You are correct.  When I make the edit that you suggested in https://github.com/rust-lang/rust/pull/72677#discussion_r431964600, this goes away

File: src/test/ui/issues/issue-72574-2.rs (hunk 6 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-2.rs:11]: This goes away with the changes that you recommended in https://github.com/rust-lang/rust/pull/72677#discussion_r431964600 too. 👍

File: src/test/ui/issues/issue-72574-1.stderr (hunk 2 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.stderr]: I ended up going with this in https://github.com/rust-lang/rust/pull/72677/commits/e73ac086c54084dced1916d062267be4058b257c.  I think that this addresses your request here?

```
error: `_x @` is not allowed in a tuple
 --> src/main.rs:4:14
  |
4 |         (_a, ref mut _x @ ..) => {}
  |              ^^^^^^^^^^^^^^^ this is only allowed in slice patterns
  |
help: either remove this and bind each tuple field independently
 --> src/main.rs:4:14
  |
4 |         (_a, ref mut _x @ ..) => {}
  |              ^^^^^^^^^^^^^^^
help: or if you don't need to use the contents of _x, discard the tuple's remaining fields
  |
4 |         (_a, ..) => {}
  |              ^^

error: aborting due to previous error
```

File: src/librustc_ast_lowering/pat.rs (hunk 4 above)
Comment (chrissimpkins) [reply src/librustc_ast_lowering/pat.rs:109]: https://github.com/rust-lang/rust/pull/72677/commits/e73ac086c54084dced1916d062267be4058b257c

File: src/test/ui/issues/issue-72574-1.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.rs]: https://github.com/rust-lang/rust/pull/72677/commits/e73ac086c54084dced1916d062267be4058b257c

File: src/test/ui/issues/issue-72574-2.rs (hunk 6 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-2.rs]: https://github.com/rust-lang/rust/pull/72677/commits/e73ac086c54084dced1916d062267be4058b257c

File: src/test/ui/issues/issue-72574-1.stderr (hunk 2 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.stderr]: I changed the local test code that I am working with to include the `ref mut` binding mode.  The tests did not change. The example above is slightly different than what you will see in the test files

File: src/test/ui/issues/issue-72574-1.rs (hunk 5 above)
Comment (chrissimpkins) [reply src/test/ui/issues/issue-72574-1.rs]: Examples of these error annotations are now available in the rustc-dev-guide: https://rustc-dev-guide.rust-lang.org/tests/adding.html#error-annotation-examples

File: src/librustc_ast_lowering/pat.rs [hunk 7]
```diff
@@ -102,10 +103,36 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                PatKind::Ident(ref _bm, ident, Some(ref sub)) if sub.is_rest() => {
+                    rest = Some((idx, pat.span));
+                    let sp = pat.span;
+                    self.diagnostic()
+                        .struct_span_err(
+                            sp,
+                            &format!("`{} @` is not allowed in a {}", ident.name, ctx),
+                        )
+                        .span_label(sp, "this is only allowed in slice patterns")
+                        .span_help(sp, "either remove this and bind each tuple field independently")
```
Comment (estebank) [inline src/librustc_ast_lowering/pat.rs:123]:
```suggestion
                        .help("either remove this and bind each tuple field independently")
```

The `help` subwindow is redundant as it shows the same as the previous one.

File: src/librustc_ast_lowering/pat.rs [hunk 8]
```diff
@@ -102,10 +103,36 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+                        .span_suggestion_verbose(
+                            sp,
+                            &format!("or if you don't need to use the contents of {}, discard the tuple's remaining fields", ident),
```
Comment (estebank) [inline src/librustc_ast_lowering/pat.rs:126]:
```suggestion
                            &format!("if you don't need to use the contents of {}, discard the tuple's remaining fields", ident),
```

**Comment by chrissimpkins** [comment]
Thanks Esteban!  I accepted the two new suggestions and will push updated test files.

**Comment by chrissimpkins** [comment]
Tests updated with the latest round of changes in https://github.com/rust-lang/rust/pull/72677/commits/dbb2d6bc1cbfa7e0ee3a491696e506b67e15001d

**Comment by chrissimpkins** [comment]
@estebank I'll wait for this to pass the CI tests and then will squash. Let me know if you feel that any other changes are needed.  This looks good 👍 

```
error: `_x @` is not allowed in a tuple
 --> src/main.rs:4:14
  |
4 |         (_a, ref mut _x @ ..) => {}
  |              ^^^^^^^^^^^^^^^ this is only allowed in slice patterns
  |
  = help: remove this and bind each tuple field independently
help: if you don't need to use the contents of _x, discard the tuple's remaining fields
  |
4 |         (_a, ..) => {}
  |              ^^

error: aborting due to previous error
```

**Comment by chrissimpkins** [comment]
Squashed to https://github.com/rust-lang/rust/pull/72677/commits/27ed143ba9bb96e907f56c9f294c904a2cb26123

All set on my end.  Please let me know if there is anything else that I need to address.  Thanks again Esteban.
