### PR TITLE
fix homogeneous_aggregate not ignoring some ZST

### LINKED ISSUE #115664: `extern "C" fn` ABI on aarch64 violates repr(transparent)
On aarch64-unknown-linux-gnu (a tier 1 target), consider this testcase:
```rust
#![feature(rustc_attrs)]

type T = (f32, f32, f32);

#[repr(transparent)]
struct Wrapper2<T>((), T);

#[rustc_abi(debug)]
extern "C" fn test1(_x: T) {}

#[rustc_abi(debug)]
extern "C" fn test2(_x: Wrapper2<T>) {}

fn main() {}
```
`test1` passes its argument as
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Float,
                                   size: Size(4 bytes),
                               },
                               total: Size(12 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```
`test2` uses
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Integer,
                                   size: Size(8 bytes),
                               },
                               total: Size(12 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```

IOW, `test1` uses float registers and `test2` uses int registers.  This violates our promise that `repr(transparent)` types are ABI-compatible.

I think this might indicate a bug in the `homogeneous_aggregate` function? At least I don't see anything in the aarch64 adjustment that would be obviously wrong.

### PR DESCRIPTION
**Pull request by RalfJung**
This is an ABI-breaking change, because it fixes bugs in our ABI code. I'm not sure what that means for this PR, we don't really have a process for such changes, do we? I can only hope nobody relied on the old buggy behavior.

Fixes https://github.com/rust-lang/rust/issues/115664

### CODE REVIEW

**Comment by RalfJung** [comment]
Given that this seems to be related to being sensitive to field ordering, it is possible that in fact the bug was introduced in https://github.com/rust-lang/rust/pull/115277 -- in which case this PR would restore the ABI to what it was before that PR.

File: compiler/rustc_target/src/abi/call/mod.rs [hunk 1]
```diff
@@ -441,12 +441,17 @@ impl<'a, Ty> TyAndLayout<'a, Ty> {
                         let mut total = start;
 
                         for i in 0..layout.fields.count() {
+                            let field = layout.field(cx, i);
+                            if field.is_zst() {
```
Comment (RalfJung) [inline compiler/rustc_target/src/abi/call/mod.rs:445]: I'm not sure if this should ignore all ZST or only all 1-ZST. That depends on whether alignment of a struct affects whether it is considered to be a homogeneous aggregate.

Comment (RalfJung) [reply compiler/rustc_target/src/abi/call/mod.rs:445]: @bjorn3 do you know what would be more appropriate here?

Comment (bjorn3) [reply compiler/rustc_target/src/abi/call/mod.rs:445]: I think only ignoring 1-ZSTs here is safer. I don't know if there are any abi's where it will matter though.

Comment (RalfJung) [reply compiler/rustc_target/src/abi/call/mod.rs:445]: Let's do the safe thing then.

Comment (RalfJung) [reply compiler/rustc_target/src/abi/call/mod.rs]: FWIW for `Abi::Scalar/ScalarPair`, we ignore all ZST, but not entirely -- there is a 2nd pass checking their alignment and falling back to Aggregate ABI if the alignment is too high. That way `(i32, [u16; 0])`  can get Scalar ABI (compatible with `i32`) but `(i16, [u32; 0])` is an Aggregate (the highly-aligned ZST prevents making this `i16`-compatible).

**Review by davidtwco — APPROVED** [review]
