### PR TITLE
Remove erroneous normalization step in `tests/run-make/linker-warning`

### LINKED ISSUE #146977: Run-make test `tests/run-make/linker-warning/` fails for me locally
Running `./x test --stage 1 tests/run-make/linker-warning` locally with an unmodified stage1 build of `rustc` leads to a test failure because an actual linker error doesn't match the expected one.

Here's the diff output by compiletest:

```diff
--- short-error.txt
+++ (linker error)
@@ -1,6 +1,6 @@
 error: linking with `./fake-linker` failed: exit status: 1
   |
-  = note:  "./fake-linker" "-m64" "/symbols.o" "<2 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/build-root/test/run-make/linker-warning/rmake_out/{libfoo,libbar}.rlib" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/raw-dylibs" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/build-root/test/run-make/linker-warning/rmake_out" "-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "main" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "run_make_error"
+  = note:  "./fake-linker" "-m64" "/symbols.o" "<2 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/home/fmease/programming/rust/rustc/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out/{libfoo,libbar}.rlib" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/raw-dylibs" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/fmease/programming/rust/rustc/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out" "-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "main" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "run_make_error"
   = note: some arguments are omitted. use `--verbose` to show all linker arguments
   = note: error: baz
```

Note that the following normalization step didn't kick in in two places:

```rs
            .normalize(
                regex::escape(
                    run_make_support::build_root().canonicalize().unwrap().to_str().unwrap(),
                ),
                "/build-root",
            )
```

That's because allegedly the actual paths passed to the (fake) linker are `/home/fmease/programming/rust/rustc/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out/{libfoo,libbar}.rlib` and `/home/fmease/programming/rust/rustc/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out` while they are were expected to be `/home/fmease/programming/rust/rustc3/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out/{libfoo,libbar}.rlib` and `/home/fmease/programming/rust/rustc3/build/x86_64-unknown-linux-gnu/test/run-make/linker-warning/rmake_out`, respectively.

To make this clearer, allegedly my stage1 rustc passes the path prefix `/home/fmease/programming/rust/rustc/` (**which is a path that doesn't exist on my machine!**) to the linker but the run-make test expects `/home/fmease/programming/rust/rustc3/` (which *is* a path that exists on my machine, it's my CWD / the place I've executed `./x test` in (it's one of my four local r-l/r.git checkouts)).

---

That stage1 build is of commit a015919e54c60b1b2bec7a98dec478cfc4a48f4e from Sep 13 2025 (base: 1.91.0). Host: x86_64-unknown-linux-gnu.

### PR DESCRIPTION
**Pull request by fmease**
Fixes rust-lang/rust#146977.

r? bjorn3 or reassign

### CODE REVIEW

File: tests/run-make/linker-warning/rmake.rs [hunk 1]
```diff
@@ -61,7 +61,7 @@ fn main() {
         diff()
             .expected_file("short-error.txt")
             .actual_text("(linker error)", out.stderr())
-            .normalize(r#"/rustc[^/_-]*/"#, "/rustc/")
+            .normalize(r#"^/rustc[^/_-]*/"#, "/rustc/")
```
Comment (fmease) [inline tests/run-make/linker-warning/rmake.rs]: For me locally, the test as a whole passes just fine if I remove this normalization step altogether but I guess there are some environments where there's a `rustcXXX` (tempdir?) in the (fake?) rootdir?

Or is the current change of prepending `^` as suggested in https://github.com/rust-lang/rust/issues/146977#issuecomment-3328525229 actually wrong as it makes this normalization step effectively unreachable?

**Comment by fmease** [comment]
@bors try cancel

That's probably the wrong job actually.

File: tests/run-make/linker-warning/rmake.rs (hunk 1 above)
Comment (bjorn3) [reply tests/run-make/linker-warning/rmake.rs]: Right, that was what this was supposed to normalize. I was thinking about the `/rustc/<commit>/` for source files, but those wouldn't have matched anyway. So yeah, my suggestion will probably break something.

**Comment by fmease** [comment]
Okay I hope that this one is a suitable try job (host `x86_64-unknown-linux-gnu` to trigger the branch in the run-make test + executing tests).

@bors try jobs=x86_64-gnu

File: tests/run-make/linker-warning/rmake.rs (hunk 1 above)
Comment (fmease) [reply tests/run-make/linker-warning/rmake.rs]: Okay, so I've now completely removed that normalization step because `short-error.txt` doesn't contain any occurrence of `/rustc/` so I'm led to believe that it never fired anyway (except on my machine) since the subsequent normalizations didn't depend on the ↦`/rustc/` normalization I think (so the lack of `/rustc/` in the golden file should really mean "never fired").

Does that make sense to you or am I misunderstanding something? In which environments or circumstances would it be possible for rustc to pass a `/rustc/<commit>/` path to the linker (but even if it did that the test would fail I believe)? Anything I could test via a try job?

Comment (bjorn3) [reply tests/run-make/linker-warning/rmake.rs]: I think the `.normalize(r#""[^"]*\/symbols.o""#, "\"/symbols.o\"").normalize(r#""[^"]*\/raw-dylibs""#, "\"/raw-dylibs\"")` below made the tempdir normalization obsolete.
