### PR TITLE
Do not accept unicode escape characters in byte strings or as byte

### LINKED ISSUE #23620: ICE on Unicode escape in byte string literal
```rust
fn main() {
    b"\u{a66e}";
}
```

```
thread 'rustc' panicked at 'lexer accepted invalid byte literal \u{a66e} step 3', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/parse/mod.rs:592
```

### PR DESCRIPTION
**Pull request by fhahn**
closes #23620

This PR patches the issue mentioned in #23620, but there is also an ICE for invalid escape sequences in byte literals. This is due to the fact that the `scan_byte` function returns `token::intern("??")` for invalid bytes, resulting in an ICE later on. Is there a reason for this behavior? Shouldn't `scan_byte` fail when it encounters an invalid byte?

And I noticed a small inconsistency in the documentation. According to the formal byte literal definition in http://doc.rust-lang.org/reference.html#byte-and-byte-string-literals , a byte string literal contains `string_body *`, but according to the text (and the behavior of the lexer) it should not accept unicode escape sequences. Hence it should be replaced by `byte_body *`. If this is valid, I can add this fix to this PR.

### CODE REVIEW

File: src/libsyntax/parse/lexer/mod.rs [hunk 1]
```diff
@@ -799,7 +799,15 @@ impl<'a> StringReader<'a> {
                             'n' | 'r' | 't' | '\\' | '\'' | '"' | '0' => true,
                             'x' => self.scan_byte_escape(delim, !ascii_only),
                             'u' if self.curr_is('{') => {
-                                self.scan_unicode_escape(delim)
+                                if self.scan_unicode_escape(delim) && ascii_only {
```
Comment (alexcrichton) [inline src/libsyntax/parse/lexer/mod.rs]: If `scan_unicode_escape` returns `false`, doesn't this whole branch return `true`? I think that only happens when the unicode escape is not a valid character (e.g. `\u{ffffff}`). Could you make sure that still emits an error?

**Comment by alexcrichton** [comment]
> If this is valid, I can add this fix to this PR.

I think it's even supposed to be `byte_string_body`, and sure, feel free to include it!

**Comment by fhahn** [comment]
I have updated the pull request and found other escape sequences that lead to ICEs. The problem seems to be that the parser expect the lexer to reject invalid byte literals, but the lexer just returns `??` tokens (e.g. https://github.com/rust-lang/rust/pull/23625/files#diff-d06ad31c547d2d94c8b8770006977767L1333), which lead to the ICEs.

In this PR, I just abort as soon as an invalid literal is encountered. Note that using `fatal_span_` would be also possible, but the current version displays error messages for the complete literal before it aborts. Does this sound like a reasonable approach?

Unfortunately, this affects the following tests:

    [parse-fail] parse-fail/ascii-only-character-escape.rs
    [parse-fail] parse-fail/bad-char-literals.rs
    [parse-fail] parse-fail/byte-literals.rs
    [parse-fail] parse-fail/byte-string-literals.rs
    [parse-fail] parse-fail/lex-bad-char-literals.rs
    [parse-fail] parse-fail/lex-bare-cr-string-literal-doc-comment.rs


The fail, because they contain invalid string literals, which cause `rustc` to abort sooner as without the changes in the PR.

**Comment by alexcrichton** [comment]
Hm would it be possible to intern a valid token instead of `??`? If an error has already been emitted then we're guaranteed that it already won't finish compiling, so it could help paper over the later ICEs perhaps?

**Comment by fhahn** [comment]
@alexcrichton Yes, `scan_byte` now returns `token::intern("?")` instead of `token::intern("??")` which is an invalid byte. I also changed some `fatal_span_` to `err_span_` in `scan_hex_digits` so the parsing can continue.
Now it only uses `fatal_span_` when the escape sequence is not terminated (https://github.com/rust-lang/rust/pull/23625/files#diff-d06ad31c547d2d94c8b8770006977767R749), but maybe we should read until the literal is terminated in order to continue parsing in this case?

File: src/libsyntax/parse/lexer/mod.rs [hunk 2]
```diff
@@ -799,7 +804,18 @@ impl<'a> StringReader<'a> {
...
                             'x' => self.scan_byte_escape(delim, !ascii_only),
                             'u' if self.curr_is('{') => {
-                                self.scan_unicode_escape(delim)
+                            let valid = self.scan_unicode_escape(delim);
+                            if valid && ascii_only {
+                                self.err_span_(
+                                    escaped_pos,
+                                    self.last_pos,
+                                    "Unicode escape sequences cannot be used as byte or in \
+                                    byte string."
```
Comment (alexcrichton) [inline src/libsyntax/parse/lexer/mod.rs]: Error messages in Rust conventionally do not start with an uppercase letter and also don't end with a period

Comment (alexcrichton) [inline src/libsyntax/parse/lexer/mod.rs]: Also, perhaps "as a byte" instead of "as byte"?

**Comment by alexcrichton** [comment]
Looks great to me, thanks @fhahn! Just a small nit about the error message and a tidy failure on travis and I think this is otherwise good to go.

**Comment by fhahn** [comment]
Thanks for the feedback, I've updated the PR.

**Comment by alexcrichton** [comment]
Perhaps the push was forgotten? (looks the same)

**Comment by fhahn** [comment]
Damn, I pushed it to the wrong branch. It should be updated now
