### PR TITLE
rustbuild: Remove one LLD workaround

### LINKED ISSUE #68647: Linking libtest with lld-link results in undefined symbols
Not sure if this is a LLD or rustc bug.

Error output:
```
error: linking with `F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0\lib\rustlib\x86_64-pc-windows-msvc\bin\rust-lld` failed: exit code: 1
  |
  = note: "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\lib\\rustlib\\x86_64-pc-windows-msvc\\bin\\rust-lld" "-flavor" "link" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.0.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.1.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.11.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.12.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.13.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.14.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.15.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.16.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.18.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.20.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.23.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.24.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.26.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.27.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.28.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.29.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.3.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.30.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.4.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.6.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.8.rcgu.o" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.test.cdf7p9m0-cgu.9.rcgu.o" "/OUT:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.dll" "/DEF:C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\lib.def" "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.5yai0brzr211np4.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\release\\deps" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\build\\compiler_builtins-44214af0d2365ef5\\out" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\libterm-6cfbd4c1589fa116.rlib" "C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\libgetopts-b1f28f4def7ae8a6.rlib" "C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\libunicode_width-e7889bd28dfba242.rlib" "C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\librustc_std_workspace_std-c2dd7b0881cfef4e.rlib" "/LIBPATH:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps" "std-c2f4da12d5907bd6.dll.lib" "C:\\Users\\John\\AppData\\Local\\Temp\\rustccCOdq4\\libcompiler_builtins-c95709d8d9af9cff.rlib" "kernel32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "libcmt.lib" "/DLL" "/IMPLIB:F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\deps\\test-08b31b6e3b792056.dll.lib"
  = note: rust-lld: error: undefined symbol: _ZN57_$LT$std..io..stdio..Stdout$u20$as$u20$std..io..Write$GT$5write17hbd65a0f1fbe667c0E
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1354
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN3std2io5Write9write_all17hc57fcfc82d35e7bfE)
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1292
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN3std2io5Write14write_vectored17had78528bfd4cfb96E)
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1354
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN3std2io5Write9write_all17hb2fe52f879a86becE)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\mod.rs:240
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN76_$LT$term..terminfo..TerminfoTerminal$LT$T$GT$$u20$as$u20$std..io..Write$GT$5write17h054e87e6072a8a23E)
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1292
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.7.rcgu.o):(_ZN3std2io5Write14write_vectored17he432d4dae6f33724E)
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1354
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.7.rcgu.o):(_ZN3std2io5Write9write_all17h24b9f983f507eb04E)
          >>> referenced by F:\Rust\rust\src\libterm\win.rs:148
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.7.rcgu.o):(_ZN65_$LT$term..win..WinConsole$LT$T$GT$$u20$as$u20$std..io..Write$GT$5write17hb36400ba3410fed5E)
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:424
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.6.rcgu.o):(_ZN3std2io22default_write_vectored17hea04ec47e1df1efbE)

          rust-lld: error: undefined symbol: _ZN75_$LT$std..sys..windows..handle..Handle$u20$as$u20$core..ops..drop..Drop$GT$4drop17h9d4cbc594f7ddd03E
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4core3ptr13drop_in_place17h10c86f64ec3fbe82E)
          >>> referenced by F:\Rust\rust\src\libstd\thread\mod.rs:386
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o:(_ZN3std6thread7Builder5spawn17h1dfac31957576ee6E)
          >>> referenced by F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o:(_ZN4core3ptr13drop_in_place17hd44aed8a67551d1bE)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ptr13drop_in_place17h9a6a8680eb1c3cbdE)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ptr13drop_in_place17h9a6a8680eb1c3cbdE)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ptr13drop_in_place17h9a6a8680eb1c3cbdE)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ptr13drop_in_place17h9d0e65faf2221092E)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ptr13drop_in_place17hc5ca69be49ef12bcE)
          >>> referenced by F:\Rust\rust\src\libcore\ptr\mod.rs:174
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN4core3ptr13drop_in_place17h4fcacb682c942e1cE)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\mod.rs:99
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN4term8terminfo8TermInfo10_from_path17h4356dd4e91d92a31E)
          >>> referenced 1 more times

          rust-lld: error: undefined symbol: _ZN42_$LT$str$u20$as$u20$core..fmt..Display$GT$3fmt17h88e4b43699a75114E
          >>> referenced by F:\Rust\rust\src\liballoc\string.rs:1914
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN60_$LT$alloc..string..String$u20$as$u20$core..fmt..Display$GT$3fmt17h5bcd62f1b4993ca7E)
          >>> referenced by F:\Rust\rust\src\liballoc\string.rs:1914
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN60_$LT$alloc..string..String$u20$as$u20$core..fmt..Display$GT$3fmt17h5bcd62f1b4993ca7E)
          >>> referenced by F:\Rust\rust\src\liballoc\string.rs:1914
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o:(_ZN60_$LT$alloc..string..String$u20$as$u20$core..fmt..Display$GT$3fmt17h5bcd62f1b4993ca7E)
          >>> referenced by F:\Rust\rust\src\liballoc\string.rs:1914
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o:(_ZN60_$LT$alloc..string..String$u20$as$u20$core..fmt..Display$GT$3fmt17h5bcd62f1b4993ca7E.llvm.815056061026961744)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o:(_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17he1974b7d847ff08bE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o:(_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17he1974b7d847ff08bE)
          >>> referenced by F:\Rust\rust\src\libtest\types.rs:73
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o:(_ZN60_$LT$test..types..TestName$u20$as$u20$core..fmt..Display$GT$3fmt17h7e47fd605c7cb8caE)
          >>> referenced by F:\Rust\rust\src\libtest\types.rs:73
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o:(_ZN60_$LT$test..types..TestName$u20$as$u20$core..fmt..Display$GT$3fmt17h7e47fd605c7cb8caE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17h7c65517032b4dca1E)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17h8e0ecf5328ef8bf9E)
          >>> referenced 10 more times

          rust-lld: error: undefined symbol: _ZN57_$LT$std..io..stdio..Stdout$u20$as$u20$std..io..Write$GT$5flush17hf0feb76a6d2e94a5E
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:40
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN73_$LT$test..console..OutputLocation$LT$T$GT$$u20$as$u20$std..io..Write$GT$5flush17h48246d88c4661c06E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:75
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN4test10formatters5terse23TerseFormatter$LT$T$GT$18write_short_result17he25bfd3d3e0dc0b8E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:96
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN4test10formatters5terse23TerseFormatter$LT$T$GT$12write_pretty17h78043e5d54e58cf0E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:161
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN4test10formatters5terse23TerseFormatter$LT$T$GT$15write_test_name17hba7c0f113354e930E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:171
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$15write_run_start17h0029d6bb43e29174E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:206
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$12write_result17h3e2ab4131cf54c4bE)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:212
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$13write_timeout17ha9ff0ccec19ad78aE)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:221
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$16write_run_finish17h8da3733db12e7cb3E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:221
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$16write_run_finish17h8da3733db12e7cb3E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:221
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN102_$LT$test..formatters..terse..TerseFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$16write_run_finish17h8da3733db12e7cb3E)
          >>> referenced 26 more times

          rust-lld: error: undefined symbol: _ZN79_$LT$std..path..Path$u20$as$u20$core..convert..AsRef$LT$std..path..Path$GT$$GT$6as_ref17h59c9d46a758a5f64E
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:64
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console16ConsoleTestState3new17h3d759a1c195c1dc7E)
          >>> referenced by F:\Rust\rust\src\libstd\fs.rs:399
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o:(_ZN3std2fs4File6create17h8f4dc7c919d646b5E)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\mod.rs:83
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN4term8terminfo8TermInfo9from_name17h0911df633b1b8d1bE)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\mod.rs:96
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN4term8terminfo8TermInfo10_from_path17h4356dd4e91d92a31E)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\mod.rs:96
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.3.rcgu.o):(_ZN4term8terminfo8TermInfo10_from_path17h4356dd4e91d92a31E)

          rust-lld: error: undefined symbol: _ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$i32$GT$3fmt17h349d87bebbbc3d0aE
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:177
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console18list_tests_console17h6532b99e448f68eaE)
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:177
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console18list_tests_console17h6532b99e448f68eaE)
          >>> referenced by F:\Rust\rust\src\libtest\test_result.rs:99
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN4test11test_result25get_result_from_exit_code17h2897dec9f27c18ffE)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\parm.rs:500
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.1.rcgu.o):(_ZN4term8terminfo4parm6format17h881ca09f38c08643E)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\parm.rs:505
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.1.rcgu.o):(_ZN4term8terminfo4parm6format17h881ca09f38c08643E)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\parm.rs:503
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.1.rcgu.o):(_ZN4term8terminfo4parm6format17h881ca09f38c08643E)
          >>> referenced by F:\Rust\rust\src\libterm\terminfo\parm.rs:507
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.1.rcgu.o):(_ZN4term8terminfo4parm6format17h881ca09f38c08643E)

          rust-lld: error: undefined symbol: _ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$u32$GT$3fmt17h6ab8423d5480caf0E
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:177
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console18list_tests_console17h6532b99e448f68eaE)
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:177
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console18list_tests_console17h6532b99e448f68eaE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.16.rcgu.o):(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hc2e52cb3d92982e7E)

          rust-lld: error: undefined symbol: _ZN60_$LT$alloc..string..String$u20$as$u20$core..clone..Clone$GT$5clone17hcff66481f9e15336E
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:226
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console13on_test_event17he33006036fa6d8edE)
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:226
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console13on_test_event17he33006036fa6d8edE)
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:226
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console13on_test_event17he33006036fa6d8edE)
          >>> referenced by F:\Rust\rust\src\libtest\console.rs:226
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.10.rcgu.o:(_ZN4test7console13on_test_event17he33006036fa6d8edE)
          >>> referenced by F:\Rust\rust\src\libtest\types.rs:64
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.22.rcgu.o:(_ZN4test5types8TestName12with_padding17ha7b9c60d78c181cdE)
          >>> referenced by F:\Rust\rust\src\libcore\option.rs:959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.29.rcgu.o:(_ZN4core6option19Option$LT$$RF$T$GT$6cloned17he58b2e34c64df414E)
          >>> referenced by F:\Rust\rust\src\libcore\iter\adapters\mod.rs:331
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o:(_ZN96_$LT$core..iter..adapters..Cloned$LT$I$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4fold17h7e008dc87d88f18fE)
          >>> referenced by F:\Rust\rust\src\libcore\iter\adapters\mod.rs:812
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o:(_ZN97_$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4fold17h1bd3f87ed184ab99E)
          >>> referenced by F:\Rust\rust\src\libtest\cli.rs:206
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.4.rcgu.o:(_ZN4test3cli10parse_opts17h32a8683d3313fe8dE)
          >>> referenced by F:\Rust\rust\src\libcore\ops\function.rs:274
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4core3ops8function5impls79_$LT$impl$u20$core..ops..function..FnMut$LT$A$GT$$u20$for$u20$$RF$mut$u20$F$GT$8call_mut17h02de41c3d932d472E)
          >>> referenced 27 more times

          rust-lld: error: undefined symbol: _ZN107_$LT$std..sync..mpsc..RecvTimeoutError$u20$as$u20$core..convert..From$LT$std..sync..mpsc..RecvError$GT$$GT$4from17hb69f0c3bf67d41a6E
          >>> referenced by F:\Rust\rust\src\libstd\sync\mpsc\mod.rs:1288
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.12.rcgu.o:(_ZN3std4sync4mpsc17Receiver$LT$T$GT$12recv_timeout17h57b40ffff32c22c5E)

          rust-lld: error: undefined symbol: _ZN40_$LT$str$u20$as$u20$core..fmt..Debug$GT$3fmt17h3099fb3f88f892ebE
          >>> referenced by F:\Rust\rust\src\libstd\sync\mpsc\mod.rs:1540
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.12.rcgu.o:(_ZN72_$LT$std..sync..mpsc..SendError$LT$T$GT$$u20$as$u20$core..fmt..Debug$GT$3fmt17hd40867e3e8108901E)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h1f218226c179698eE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hb44421a8e1e924cbE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hc74aa123b38842c2E)
          >>> referenced by F:\Rust\rust\src\libstd\sys_common\poison.rs:138
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.26.rcgu.o:(_ZN82_$LT$std..sys_common..poison..PoisonError$LT$T$GT$$u20$as$u20$core..fmt..Debug$GT$3fmt17h8f4d69f8ea34858dE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.31.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17h1b2e483bb3c1d72cE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               libgetopts-b1f28f4def7ae8a6.rlib(getopts-b1f28f4def7ae8a6.getopts.5palysce-cgu.0.rcgu.o):(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17he450f958f24cf18bE)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.22.rcgu.o):(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hb5b2e1d3d12e8c73E)

          rust-lld: error: undefined symbol: _ZN4core3fmt3num3imp54_$LT$impl$u20$core..fmt..Display$u20$for$u20$usize$GT$3fmt17h92876b3d8c7fe544E
          >>> referenced by F:\Rust\rust\src\libstd\macros.rs:23
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.13.rcgu.o:(_ZN3std4sync4mpsc6shared15Packet$LT$T$GT$9drop_chan17h70710ca56a3cfd7fE)
          >>> referenced by F:\Rust\rust\src\libtest\bench.rs:72
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o:(_ZN4test5bench17fmt_bench_samples17h042c770e1d2f0929E)
          >>> referenced by F:\Rust\rust\src\libtest\bench.rs:86
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o:(_ZN4test5bench17fmt_thousands_sep17h80883fe1ecfdb1b4E)
          >>> referenced by F:\Rust\rust\src\libtest\bench.rs:88
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o:(_ZN4test5bench17fmt_thousands_sep17h80883fe1ecfdb1b4E)
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.25.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17ha9de42ef17e78163E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\json.rs:61
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.6.rcgu.o:(_ZN100_$LT$test..formatters..json..JsonFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$15write_run_start17h2196ba29f028d64dE)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\json.rs:135
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.6.rcgu.o:(_ZN100_$LT$test..formatters..json..JsonFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$12write_result17h9be8b1bae120fc65E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\json.rs:138
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.6.rcgu.o:(_ZN100_$LT$test..formatters..json..JsonFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$12write_result17h9be8b1bae120fc65E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\json.rs:159
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.6.rcgu.o:(_ZN100_$LT$test..formatters..json..JsonFormatter$LT$T$GT$$u20$as$u20$test..formatters..OutputFormatter$GT$16write_run_finish17h6bf7c757d17b74d2E)
          >>> referenced by F:\Rust\rust\src\libtest\formatters\terse.rs:74
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(_ZN4test10formatters5terse23TerseFormatter$LT$T$GT$18write_short_result17he25bfd3d3e0dc0b8E)
          >>> referenced 8 more times

          rust-lld: error: undefined symbol: _ZN4core3fmt5float52_$LT$impl$u20$core..fmt..Display$u20$for$u20$f64$GT$3fmt17h189b136135402b9eE
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17h6d99a020930638eaE)
          >>> referenced by F:\Rust\rust\src\libtest\time.rs:69
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN63_$LT$test..time..TestExecTime$u20$as$u20$core..fmt..Display$GT$3fmt17h37687ecc4b6966cbE)
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2007
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h9aaff847c7a08091E)
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2019
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h9aaff847c7a08091E)
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2019
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h9aaff847c7a08091E)
          >>> referenced by F:\Rust\rust\src\libcore\ops\function.rs:285
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o:(_ZN4core3ops8function5impls80_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$mut$u20$F$GT$9call_once17hcd3bddeec5fd4180E)

          rust-lld: error: undefined symbol: _ZN4core3num52_$LT$impl$u20$core..str..FromStr$u20$for$u20$u64$GT$8from_str17hcf1d7caa913b041cE
          >>> referenced by F:\Rust\rust\src\libcore\iter\adapters\mod.rs:791
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN97_$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hefeeb8cdeb76c86aE)

          rust-lld: error: undefined symbol: _ZN54_$LT$core..any..TypeId$u20$as$u20$core..fmt..Debug$GT$3fmt17h4acf93e863d041d5E
          >>> referenced by F:\Rust\rust\src\libtest\test_result.rs:57
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN4test11test_result11calc_result17h578d2295b2aff976E)

          rust-lld: error: undefined symbol: _ZN88_$LT$std..time..Instant$u20$as$u20$core..ops..arith..Add$LT$core..time..Duration$GT$$GT$3add17h547da9327098516eE
          >>> referenced by F:\Rust\rust\src\libtest\time.rs:60
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.17.rcgu.o:(_ZN4test4time24get_default_test_timeout17h0e82631fa0b0c141E)
          >>> referenced by F:\Rust\rust\src\libtest\lib.rs:296
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.5.rcgu.o:(_ZN4test9run_tests17had54d3605a3f920dE)

          rust-lld: error: undefined symbol: _ZN53_$LT$core..fmt..Error$u20$as$u20$core..fmt..Debug$GT$3fmt17h44e19c88cc9c88a5E
          >>> referenced by F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.19.rcgu.o:(anon.e4d4364cd92e2c9867e8e6e4bcbcea34.3)
          >>> referenced by F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.4.rcgu.o:(anon.a8992f771d7cebb48de2f01bdce6ac0d.5)
          >>> referenced by F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.7.rcgu.o:(anon.46c5e78587de7248bbd21783e47c14b4.5)
          >>> referenced by F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.8.rcgu.o:(anon.810636724a72e72083165abd11ec6984.5)
          >>> referenced by libgetopts-b1f28f4def7ae8a6.rlib(getopts-b1f28f4def7ae8a6.getopts.5palysce-cgu.14.rcgu.o):(anon.1cf900d2eafb2dcd1312552eb099fe06.5)
          >>> referenced by libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.5.rcgu.o):(anon.9a1b1af1903ff770925bb87d0fca2c64.6)
          >>> referenced by libterm-6cfbd4c1589fa116.rlib(term-6cfbd4c1589fa116.term.cvtlv8xb-cgu.11.rcgu.o):(anon.b2b52a5a62deeaf091d02115f0e921d7.5)

          rust-lld: error: undefined symbol: _ZN73_$LT$std..env..Args$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h76d2e0121a5a7450E
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2007
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h91faedf2173edcf3E)
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2019
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h91faedf2173edcf3E)

          rust-lld: error: undefined symbol: _ZN73_$LT$std..env..Args$u20$as$u20$core..iter..traits..iterator..Iterator$GT$9size_hint17h8a29deca6154f599E
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2010
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h91faedf2173edcf3E)
          >>> referenced by F:\Rust\rust\src\liballoc\vec.rs:2019
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.2.rcgu.o:(_ZN80_$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$9from_iter17h91faedf2173edcf3E)

          rust-lld: error: undefined symbol: _ZN48_$LT$std..fs..File$u20$as$u20$std..io..Write$GT$5write17h88eedd89f1c8a942E
          >>> referenced by F:\Rust\rust\src\libstd\io\mod.rs:1354
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o:(_ZN3std2io5Write9write_all17h180604707e4abef7E)

          rust-lld: error: undefined symbol: _ZN55_$LT$std..path..PathBuf$u20$as$u20$core..fmt..Debug$GT$3fmt17h01a79564a1f3d451E
          >>> referenced by F:\Rust\rust\src\libcore\fmt\mod.rs:1959
          >>>               F:\Rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\test-08b31b6e3b792056.test.cdf7p9m0-cgu.21.rcgu.o:(_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hd2d63f726e4f4e25E)

          rust-lld: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)


error: aborting due to previous error

error: could not compile `test`.

To learn more, run the command again with --verbose.
command did not execute successfully: "F:\\Rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe" "build" "-Zconfig-profile" "--target" "x86_64-pc-windows-msvc" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "F:\\Rust\\rust\\src/libtest/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
```

### PR DESCRIPTION
**Pull request by petrochenkov**
The version of LLD shipped with Rust no longer have this issue.

Closes https://github.com/rust-lang/rust/issues/68647

### CODE REVIEW

**Comment by petrochenkov** [comment]
Full `./x.py test --stage 2` still doesn't pass with LLD on MSVC, compiletest crashes on some accesses to thread-local storage when running UI tests.
```sh
./x.py test src/test/ui
```
```
Unhandled exception at 0x00007FF692F336F3 in compiletest.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred
```
```
[Inline Frame] compiletest.exe!core::intrinsics::copy_nonoverlapping() Line 1858
	at C:\msys64\home\we\rust\library\core\src\intrinsics.rs(1858)
[Inline Frame] compiletest.exe!core::ptr::swap_nonoverlapping_bytes() Line 503
	at C:\msys64\home\we\rust\library\core\src\ptr\mod.rs(503)
[Inline Frame] compiletest.exe!core::ptr::swap_nonoverlapping() Line 445
	at C:\msys64\home\we\rust\library\core\src\ptr\mod.rs(445)
[Inline Frame] compiletest.exe!core::ptr::swap_nonoverlapping_one() Line 462
	at C:\msys64\home\we\rust\library\core\src\ptr\mod.rs(462)
[Inline Frame] compiletest.exe!core::mem::swap() Line 698
	at C:\msys64\home\we\rust\library\core\src\mem\mod.rs(698)
[Inline Frame] compiletest.exe!core::mem::replace() Line 833
	at C:\msys64\home\we\rust\library\core\src\mem\mod.rs(833)
[Inline Frame] compiletest.exe!std::thread::local::lazy::LazyKeyInner::initialize() Line 306
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(306)
[Inline Frame] compiletest.exe!std::thread::local::fast::Key::try_initialize() Line 427
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(427)
[Inline Frame] compiletest.exe!std::thread::local::fast::Key::get() Line 412
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(412)
compiletest.exe!std::io::stdio::LOCAL_STDERR::__getit() Line 177
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(177)
[Inline Frame] compiletest.exe!std::thread::local::LocalKey::try_with() Line 264
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(264)
compiletest.exe!std::thread::local::LocalKey::with<core::cell::RefCell<core::option::Option<alloc::boxed::Box<Write>>>,closure-0,core::option::Option<alloc::boxed::Box<Write>>>() Line 241
	at C:\msys64\home\we\rust\library\std\src\thread\local.rs(241)
compiletest.exe!std::io::stdio::set_panic() Line 832
	at C:\msys64\home\we\rust\library\std\src\io\stdio.rs(832)
compiletest.exe!test::run_test_in_process() Line 535
	at C:\msys64\home\we\rust\library\test\src\lib.rs(535)
[Inline Frame] compiletest.exe!test::run_test::run_test_inner::{{closure}}() Line 450
	at C:\msys64\home\we\rust\library\test\src\lib.rs(450)
compiletest.exe!std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,tuple<>>() Line 140
	at C:\msys64\home\we\rust\library\std\src\sys_common\backtrace.rs(140)
[Inline Frame] compiletest.exe!std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}() Line 458
	at C:\msys64\home\we\rust\library\std\src\thread\mod.rs(458)
[Inline Frame] compiletest.exe!std::panic::{{impl}}::call_once() Line 308
	at C:\msys64\home\we\rust\library\std\src\panic.rs(308)
[Inline Frame] compiletest.exe!std::panicking::try::do_call() Line 381
	at C:\msys64\home\we\rust\library\std\src\panicking.rs(381)
[Inline Frame] compiletest.exe!std::panicking::try() Line 345
	at C:\msys64\home\we\rust\library\std\src\panicking.rs(345)
[Inline Frame] compiletest.exe!std::panic::catch_unwind() Line 382
	at C:\msys64\home\we\rust\library\std\src\panic.rs(382)
[Inline Frame] compiletest.exe!std::thread::{{impl}}::spawn_unchecked::{{closure}}() Line 457
	at C:\msys64\home\we\rust\library\std\src\thread\mod.rs(457)
compiletest.exe!core::ops::function::FnOnce::call_once<closure-0,tuple<>>() Line 227
	at C:\msys64\home\we\rust\library\core\src\ops\function.rs(227)
[Inline Frame] compiletest.exe!alloc::boxed::{{impl}}::call_once() Line 1042
	at C:\msys64\home\we\rust\library\alloc\src\boxed.rs(1042)
[Inline Frame] compiletest.exe!alloc::boxed::{{impl}}::call_once() Line 1042
	at C:\msys64\home\we\rust\library\alloc\src\boxed.rs(1042)
compiletest.exe!std::sys::windows::thread::{{impl}}::new::thread_start() Line 56
	at C:\msys64\home\we\rust\library\std\src\sys\windows\thread.rs(56)
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```

**Comment by petrochenkov** [comment]
With `x86_64-pc-windows-gnu` things are worse, with LLD enabled build hangs when trying to build `src/tools/tidy`.
cc @mati865

**Comment by mati865** [comment]
@petrochenkov can you obtain stack trace from hanged LLD on windows-gnu? I suppose it will look like LLD -> libstdc++ -> winpthreads -> Windows DLLs.

File: src/bootstrap/builder.rs [hunk 1]
```diff
@@ -1041,15 +1041,11 @@ impl<'a> Builder<'a> {
             }
         }
 
-        // FIXME: Don't use LLD with MSVC if we're compiling libtest, since it fails to link it.
-        // See https://github.com/rust-lang/rust/issues/68647.
-        let can_use_lld = mode != Mode::Std;
-
-        if let Some(host_linker) = self.linker(compiler.host, can_use_lld) {
+        if let Some(host_linker) = self.linker(compiler.host, true) {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/builder.rs:1044]: I think we always pass true now, could we drop that arg as well?

**Review by Mark-Simulacrum — APPROVED** [review]
r=me with nit resolved (whether I'm right about it or not)

File: src/bootstrap/builder.rs (hunk 1 above)
Comment (petrochenkov) [reply src/bootstrap/builder.rs:1044]: Test suite is still run without explicit linker because there are tests that check linker search etc.
Perhaps we could switch to LLD there as well, but it may require adjusting some tests.
I'll try to do it in a separate PR.

**Comment by petrochenkov** [comment]
@mati865 
I'll try to provide the backtrace a bit later.

@bors r=Mark-Simulacrum rollup

**Comment by mati865** [comment]
@petrochenkov I won't mind process dump or steps to reproduce it either, whatever is easiest for you.

**Comment by petrochenkov** [comment]
@mati865 
The step to reproduce is to run `x.py test tidy` basically.
(With
```toml
[rust]
use-lld = true
```
in `config.toml`)

**Comment by mati865** [comment]
I cannot reproduce the hang:
```
$ pacman -Qs 64-lld
local/mingw-w64-x86_64-lld 10.0.1-1
    Linker tools for LLVM (mingw-w64)
```
If you encounter it again stack trace or a dump would be useful.

**Comment by mati865** [comment]
@petrochenkov I can reproduce the hang with `rust-lld` shipped by Rust:
```
    frame #0: 0x00007ffba90ebe44 ntdll.dll`NtWaitForSingleObject + 20
    frame #1: 0x00007ffba6b826ee KernelBase.dll`WaitForSingleObjectEx + 142
    frame #2: 0x000000006494209c libwinpthread-1.dll`pthread_cond_init + 556
    frame #3: 0x00000000649421de libwinpthread-1.dll`pthread_cond_init + 878
    frame #4: 0x000000006494246f libwinpthread-1.dll`pthread_cond_signal + 207
    frame #5: 0x00000000029a5119 rust-lld.exe`std::condition_variable::notify_one() + 9
    frame #6: 0x000000000218854c rust-lld.exe`llvm::parallel::detail::TaskGroup::spawn(std::function<void ()>) + 412
    frame #7: 0x0000000000ffd62b rust-lld.exe`(anonymous namespace)::Writer::run() + 5499
    frame #8: 0x000000000119e465 rust-lld.exe`lld::coff::writeResult() + 837
    frame #9: 0x00000000011aa4b4 rust-lld.exe`lld::coff::LinkerDriver::link(llvm::ArrayRef<char const*>) + 30628
    frame #10: 0x00000000011c99b3 rust-lld.exe`lld::coff::link(llvm::ArrayRef<char const*>, bool, llvm::raw_ostream&, ll
vm::raw_ostream&) + 243
    frame #11: 0x000000000122ba1e rust-lld.exe`lld::mingw::link(llvm::ArrayRef<char const*>, bool, llvm::raw_ostream&, l
lvm::raw_ostream&) + 12894
    frame #12: 0x0000000002c4143b rust-lld.exe`main + 1243
    frame #13: 0x00000000004013f8 rust-lld.exe`__tmainCRTStartup + 584
    frame #14: 0x000000000040151b rust-lld.exe
    frame #15: 0x00007ffba82f6fd4 kernel32.dll`BaseThreadInitThunk + 20
    frame #16: 0x00007ffba909cec1 ntdll.dll`RtlUserThreadStart + 33
```
Short explanation: ancient winpthreads library used by CI is quite buggy, this hang is caused by one of them (libstdc++ uses winpthreads for C++ multithreading). I'll try to raise topic about upgrading mingw-w64 once again...

**Comment by petrochenkov** [comment]
@mati865 
Thanks for getting to this sooner than me.
Yes, `x.py` with `use-lld = true` uses `rust-lld` shipped with Rust, I didn't try the one from `pacman`.

**Comment by mati865** [comment]
> Yes, x.py with use-lld = true uses rust-lld shipped with Rust, I didn't try the one from pacman.

Maybe for msvc (I haven't really investigated it) but for other targets this passes `-fuse-ld=lld` to the linker: https://github.com/rust-lang/rust/pull/75111

**Comment by petrochenkov** [comment]
Ok, I'll test again and look why `rust-lld` was used in my case.
