### PR TITLE
deny using default function in impl const Trait

### LINKED ISSUE #79450: `impl const` wrongly accepts impl with non-const provided methods
This prints no error, but `prov` is not `const`-safe, so the `impl const Tr` should not be accepted:

```rust
#![feature(const_trait_impl)]

trait Tr {
    fn req(&self);
    
    fn prov(&self) {
        println!("lul");
        self.req();
    }
}

struct S;

impl const Tr for S {
    fn req(&self) {}
}
```

### PR DESCRIPTION
**Pull request by fee1-dead**
Fixes #79450.

I don't know if my implementation is correct:

 - The check is in `rustc_passes::check_const`, should I put it somewhere else instead?
 - Is my approach (to checking the impl) optimal? It works for the current tests, but it might have some issues or there might be a better way of doing this.

### CODE REVIEW

File: compiler/rustc_passes/src/check_const.rs [hunk 1]
```diff
@@ -59,12 +60,70 @@ impl NonConstExpr {
 fn check_mod_const_bodies(tcx: TyCtxt<'_>, module_def_id: LocalDefId) {
     let mut vis = CheckConstVisitor::new(tcx);
     tcx.hir().visit_item_likes_in_module(module_def_id, &mut vis.as_deep_visitor());
+    if tcx.features().enabled(sym::const_trait_impl) {
```
Comment (jonas-schievink) [inline compiler/rustc_passes/src/check_const.rs:63]: I think you can skip this check. We can emit these errors even when the feature gate is turned off.

File: src/test/ui/consts/const-float-classify.rs [hunk 2]
```diff
@@ -53,6 +53,9 @@ impl const PartialEq<NonDet> for bool {
     fn eq(&self, _: &NonDet) -> bool {
         true
     }
+    fn ne(&self, _: &NonDet) -> bool {
```
Comment (jackh726) [inline src/test/ui/consts/const-float-classify.rs:56]: Why add these?

**Review by jackh726 — CHANGES_REQUESTED** [review]
I'm wondering if this would catch super trait functions. Can you add a test for that?

File: src/test/ui/consts/const-float-classify.rs (hunk 2 above)
Comment (fee1-dead) [reply src/test/ui/consts/const-float-classify.rs:56]: because we deny using the default functions, for now.

in the future, it might verify if the default function is `const`. but for now, it denies if a default function is used

Comment (jackh726) [reply src/test/ui/consts/const-float-classify.rs:56]: Oh I see. Whoops.

File: compiler/rustc_passes/src/check_const.rs [hunk 3]
```diff
@@ -59,12 +60,68 @@ impl NonConstExpr {
...
+                        })
+                        .count();
+
+                    let impl_fn_cnt = imp
+                        .items
+                        .iter()
+                        .filter(|it| matches!(it.kind, hir::AssocItemKind::Fn { .. }))
+                        .count();
+
+                    if trait_fn_cnt != impl_fn_cnt {
```
Comment (jackh726) [inline compiler/rustc_passes/src/check_const.rs:104]: Also, this is kind of a hacky way to check if there are any non-implemented default functions. But it might just be the best.

**Comment by fee1-dead** [comment]
> if this would catch super trait functions

I don't understand, because with `B: A` you must implement A to implement B. But this raises a question, with super traits, does `impl const B` require `impl const A`? This is currently not enforced, but it also works because when it is not const, the functions of `A` would not be recognized as `const` (I guess).

Is there anything about super traits (and default implementations of functions of those) that it should catch? There is no way for a sub-trait to specify default impls for a super-trait, right?

**Comment by fee1-dead** [comment]
cc @oli-obk

**Comment by jackh726** [comment]
> > if this would catch super trait functions
> 
> I don't understand, because with `B: A` you must implement A to implement B. But this raises a question, with super traits, does `impl const B` require `impl const A`? This is currently not enforced, but it also works because when it is not const, the functions of `A` would not be recognized as `const` (I guess).
> 
> Is there anything about super traits (and default implementations of functions of those) that it should catch? There is no way for a sub-trait to specify default impls for a super-trait, right?

Ah, you're right. Not sure about if `impl const B` should require `impl const A`; seems orthogonal. For this, I think this is fine except I'd like a comment basically explaining what this code does and why it's required.
