### PR TITLE
Require `type_map::stub` callers to supply file information

### LINKED ISSUE #98678: Missing debug information about type definitions in PDB
It seems like rustc does not generate enough information about types in PDB debug information. Particularly, the PDB IPI Stream contains invalid `LF_UDT_MOD_SRC_LINE` entries without source file information. Due to this issue, from the debugger's perspective, it is impossible to check whether a certain type corresponds to Rust source code or not. This affects both user-defined and stdlib types.

### Steps to reproduce

1. Create a simple Rust program with a structure definition `rusttest::MyType` located in `main.rs`
2. Dump PDB data using `llvm-pdbutil.exe dump -all main.pdb > main.pdb.txt` command
3. Look at  `rusttest::MyType` information in the TPI Stream and IPI Stream sections

It may look as follows:
```
                     Types (TPI Stream)                     
============================================================
  0x107A | LF_STRUCTURE [size = 76, hash = 0x2C45E] `rusttest::MyType`
           unique name: `36f9e7b2e2f4a0c8d5bebaa1feba526d`
           vtable: <no type>, base list: <no type>, field list: 0x1079
           options: has unique name, sizeof 8

                     Types (IPI Stream)                     
============================================================
   0x1051 | LF_UDT_MOD_SRC_LINE [size = 20, hash = 0x1C61]
            udt = 0x107A, mod = 4, file = 1, line = 0

                        String Table                        
============================================================
     ID | String
      1 | '\<unknown>'

```
Note, in the corresponding entry of IPI Stream (`udt = 0x107A`) we have `file = 1`, which refers to an unknown file.

In comparison, this is an example of correct information generated by `cl.exe` when compiling a similar C++ program:
```
                     Types (TPI Stream)                     
============================================================
   0x5760 | LF_STRUCTURE [size = 44, hash = 0x1D1EA] `MyType`
            unique name: `.?AUMyType@@`
            vtable: <no type>, base list: <no type>, field list: 0x575F
            options: has unique name, sizeof 4

                     Types (IPI Stream)                     
============================================================
   0x287E | LF_UDT_MOD_SRC_LINE [size = 18, hash = 0x5B53]
            udt = 0x5760, mod = 1, file = 19765, line = 3

                        String Table                        
============================================================
   19765 | 'C:\path\to\main.cpp'
```

### PR DESCRIPTION
**Pull request by mweber15**
This change attaches file information (`DIFile` reference and line number) to struct debug info nodes.

Before:

```
; foo.ll
...
!5 = !DIFile(filename: "<unknown>", directory: "")
...
!16 = !DICompositeType(tag: DW_TAG_structure_type, name: "MyType", scope: !2, file: !5, size: 32, align: 32, elements: !17, templateParams: !19, identifier: "4cb373851db92e732c4cb5651b886dd0")
...
```

After:

```
; foo.ll
...
!3 = !DIFile(filename: "foo.rs", directory: "/home/matt/src/rust98678", checksumkind: CSK_SHA1, checksum: "bcb9f08512c8f3b8181ef4726012bc6807bc9be4")
...
!16 = !DICompositeType(tag: DW_TAG_structure_type, name: "MyType", scope: !2, file: !3, line: 3, size: 32, align: 32, elements: !17, templateParams: !19, identifier: "9e5968c7af39c148acb253912b7f409f")
...
```

Fixes #98678

r? @wesleywiser

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs [hunk 1]
```diff
@@ -1169,6 +1188,8 @@ fn build_closure_env_di_node<'ll, 'tcx>(
             Stub::Struct,
             unique_type_id,
             &type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:1192]: I think closures could have reasonable file info that would point to the line that contains the closure. Could you try `TyCtxt::def_span` here as well and see if that provides the correct info? (If it does, it's probably worth extracting a function that can be called from both locations)

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs [hunk 2]
```diff
@@ -1200,6 +1221,8 @@ fn build_union_type_di_node<'ll, 'tcx>(
             Stub::Union,
             unique_type_id,
             &type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs:1225]: `union`s should also have line numbers (you can call the extracted function I mentioned above here)

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs [hunk 3]
```diff
@@ -213,6 +213,8 @@ pub(super) fn build_enum_type_di_node<'ll, 'tcx>(
             type_map::Stub::Union,
             unique_type_id,
             &enum_type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:217]: I think this should use the line number of the enum declaration.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs [hunk 4]
```diff
@@ -288,6 +290,8 @@ pub(super) fn build_generator_di_node<'ll, 'tcx>(
             type_map::Stub::Union,
             unique_type_id,
             &generator_type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:294]: Generators should also have useful line numbers I think.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs [hunk 5]
```diff
@@ -490,6 +494,8 @@ fn build_variant_struct_wrapper_type_di_node<'ll, 'tcx>(
                 variant_index,
             ),
             &variant_struct_wrapper_type_name(variant_index),
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:498]: It would be cool if we could also get the line numbers for the enum variants but that's a little more complex. If you want to take a stab at that, you need to get the `AdtDef` for the enum (like we do for structs) and then call the `variant` method, providing the `variant_index`. From there, you the `def_id` should work with `tcx.def_span`.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/mod.rs [hunk 6]
```diff
@@ -265,6 +265,8 @@ fn build_enum_variant_struct_type_di_node<'ll, 'tcx>(
                 variant_index,
             ),
             variant_def.name.as_str(),
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/mod.rs:269]: If we can manage it, it would be nice to use the enum variant declaration line as mentioned above.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/mod.rs [hunk 7]
```diff
@@ -347,6 +349,8 @@ pub fn build_generator_variant_struct_type_di_node<'ll, 'tcx>(
             Stub::Struct,
             unique_type_id,
             &variant_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/mod.rs:353]: Same with generators here (they are basically just enums anyway).

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/native.rs [hunk 8]
```diff
@@ -73,6 +73,8 @@ pub(super) fn build_enum_type_di_node<'ll, 'tcx>(
             Stub::Struct,
             unique_type_id,
             &enum_type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/native.rs:77]: We should look up the line number for the enum here.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/native.rs [hunk 9]
```diff
@@ -151,6 +153,8 @@ pub(super) fn build_generator_di_node<'ll, 'tcx>(
             Stub::Struct,
             unique_type_id,
             &generator_type_name,
+            unknown_file_metadata(cx),
+            UNKNOWN_LINE_NUMBER,
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/native.rs:157]: and for the generator here.

File: src/test/debuginfo/issue-98678.rs [hunk 10]
```diff
@@ -0,0 +1,28 @@
+// This test verifies that debug info for structs contains accurate filename and line locations
```
Comment (wesleywiser) [inline src/test/debuginfo/issue-98678.rs:1]: This is great! Thanks for adding a test case 💯 

I think might also make sense to add a codegen test as then we can verify that the LLVM IR generated contains the file and line number annotations. What do you think?

**Review by wesleywiser — COMMENTED** [review]
This is on the right track, thanks for working on this!

File: src/test/debuginfo/issue-98678.rs (hunk 10 above)
Comment (mweber15) [reply src/test/debuginfo/issue-98678.rs:1]: That sounds like a good idea to me. Thank you for the detailed feedback and pointers. I'll work on implementing the types you highlighted and expanding the tests.

Comment (wesleywiser) [reply src/test/debuginfo/issue-98678.rs:1]: You're welcome! If you have questions, feel free to ping me on Zulip or just leave them here 🙂

Comment (mweber15) [reply src/test/debuginfo/issue-98678.rs:1]: I think the codegen test is a much better driver for this than this original test. I didn't expand this original test yet because I think it would be better to remove it instead. I don't think we need to test that the conversion from IR to debuginfo works here.

I think I hit all of the places that you called out in your review. I'm not super confident that the `DW_TAG_variant_part` is pointing to the right place (it's currently referring to the `enum` definition itself), but I think the field identification is correct. There are also still gaps that could be filled in, and I'll try to come up with some more examples in the codegen test to exercise those if you think I'm still on the right overall track here. I wanted to push what I have first to make sure I haven't gone off the rails.

I'm sure there are better ways to express a lot of this than what I am doing here currently. The `file_metadata_from_def_id` function in particular feels clunkier than it probably should be.

It feels like the places where I'm using `Option<T>` to accept defs and `DefId`s would instead not be optional if this were complete.

Looking forward to your comments on this iteration of the changes.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs [hunk 11]
```diff
@@ -784,8 +786,13 @@ fn build_union_fields_for_direct_tag_enum_or_generator<'ll, 'tcx>(
         let field_name = variant_union_field_name(variant_member_info.variant_index);
         let (size, align) = size_and_align_of(enum_type_and_layout);
 
+        let ty::Adt(enum_adt_def, _) = enum_type_and_layout.ty.kind() else {
+            unreachable!();
+        };
```
Comment (wesleywiser) [inline compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:791]: I don't think this will work because this function is shared between enums and generators so `ty.kind()` can return `ty::Generator`. Generators kind of throw a wrench into this approach as their variants don't have `DefIds`. If you want to support that in this PR, we probably need to refactor some of the DI builder functions to take either a `DefId` or just a `(file, line_number)` pair, perhaps as a new `enum DefinitionLocation` type . We can also just leave that for future work 🙂

**Comment by wesleywiser** [comment]
> I didn't expand this original test yet because I think it would be better to remove it instead

That seems fine to me! I think the important part we want to test is that we're generating the right LLVM IR. What it does with that depends on the target and some debuggers probably don't provide this data to the user anyway. 

> I'm not super confident that the DW_TAG_variant_part is pointing to the right place (it's currently referring to the enum definition itself)

I believe that is correct. In DWARF, you define a struct/class and a part of that which is the variant. For Rust enums, we model this as essentially a struct whose only member is a DW_TAG_variant_part so both the outer struct and the DW_TAG_variant_part should refer to the (Rust) enum definition. 

>  The file_metadata_from_def_id function in particular feels clunkier than it probably should be.

You might be able to clean that up using the unstable [`let-chains` feature](https://rust-lang.github.io/rfcs/2497-if-let-chains.html). The other option would be to use some of the `Option` combinator methods to avoid the duplication of the unknown file/line items.

> It feels like the places where I'm using Option<T> to accept defs and DefIds would instead not be optional if this were complete.

While I think there are some places this is true, there will be a few kinds of types that cannot have locations emitted. For things like tuples or trait objects, there is no real definition location that can be meaningfully assigned. We'll always need to omit location data for those types. 

Overall this looks good; nice work!

**Comment by wesleywiser** [comment]
Oh, just as an FYI, the Windows and Linux targets differ in how they name and generate some kinds of debuginfo so we'll either need to adapt the codegen test to match both or have one codegen test for Linux and one for Windows (I think we do want to have both under test). If you don't have access to a Windows machine, I can pull that together when the PR is ready to merge.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs [hunk 12]
```diff
@@ -460,13 +460,15 @@ fn build_variant_names_type_di_node<'ll, 'tcx>(
     cx: &CodegenCx<'ll, 'tcx>,
     containing_scope: &'ll DIType,
     variants: impl Iterator<Item = (VariantIdx, Cow<'tcx, str>)>,
+    def_id: rustc_span::def_id::DefId,
```
[the remark this answers is not in the document]
Comment (mweber15) [reply compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:468]: Agreed. I'll rename the parameter to `enum_def_id`.

File: compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs (hunk 11 above)
Comment (mweber15) [reply compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs:791]: The codegen test isn't covering this properly right now. Interestingly, it panics on Windows, but not on Linux. It seems like I might be able to use `variant_member_info.source_info` (which is of type `Option<(&'ll DIFile, c_uint)>`), since we're iterating members here. The test still passes on Linux when I make the changes necessary to use that, but as you pointed out elsewhere I need to update the codegen test to work properly on Windows. It seems like this function is potentially only properly exercised on Windows for a reason I don't currently understand.

Comment (wesleywiser) [reply compiler/rustc_codegen_llvm/src/debuginfo/metadata/enums/cpp_like.rs]: The way we encode enums is very different between Windows and Linux (and other *nix likes). Linux uses DWARF which has native support for variant types, which we just call enums in Rust. Windows' debuginfo format PDB is very C++ centric and doesn't have an equivalent concept. As such, we represent Rust enums as unions consisting of one field per variant plus the discriminator field. We then bundle some visualization scripts into the debuginfo that can display the correct value to the user in a debugger. 

This split is evidenced in the file names "cpp_like" is second encoding (the Windows one) and "native" is for platforms that have native support for variant types that LLVM can lower to. As such, any bugs in one of these files will only show up on the corresponding platform.

File: src/test/codegen/issue-98678-native-enum.rs [hunk 13]
```diff
@@ -4,12 +4,16 @@
...
-// CHECK: ![[#FILE:]] = !DIFile({{.*}}filename:{{.*}}src/test/codegen/issue-98678-native-enum.rs{{".*}})
+// NONMSVC: ![[#FILE:]] = !DIFile({{.*}}filename:{{.*}}src/test/codegen/issue-98678-native-enum.rs{{".*}})
+// MSVC: ![[#FILE:]] = !DIFile({{.*}}filename:{{.*}}src/test\\codegen\\issue-98678-native-enum.rs{{".*}})
 
-// CHECK: !DICompositeType({{.*"}}MyNativeEnum{{".*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 2]],
-// CHECK: !DICompositeType({{.*}}DW_TAG_variant_part{{.*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 1]],
+// NONMSVC: !DICompositeType({{.*"}}MyNativeEnum{{".*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 4]],
+// MSVC: !DICompositeType({{.*::}}MyNativeEnum>{{.*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 3]],
+// NONMSVC: !DICompositeType({{.*}}DW_TAG_variant_part{{.*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 2]],
+// COM: MSVC: currently no DW_TAG_variant_part from MSVC
```
Comment (wesleywiser) [inline src/test/codegen/issue-98678-native-enum.rs:15]: I think this might be because of https://github.com/rust-lang/rust/pull/104342/files#diff-a1ba92bf09005c702fd2e516c36d5660acea04dd3a8f871ff32bdbe478e6a034R363

Which reminds me, we should probably have test coverage for all of 

```rust
pub enum SingleCase {
    One,
}

pub enum MultipleDataCases {
    Case1(u32),
    Case2(i64),
}

pub enum NicheLayout {
    Something(&'static u32),
    Nothing,
}
```

Since all of these have different codepaths in debuginfo generation (at least, for `cpp_like` they do).

**Comment by wesleywiser** [comment]
Overall this is looking really good! I think we're close to merging but it would be good to have a few more tests. In particular, I think async blocks and async functions should already be getting the correct line numbers because of the generator case but it would be good to have that under test. It looks like there is support for setting line numbers for fields in enum variants but that doesn't have a test case. 

Can you also rebase over master? The test folder was recently moved to the top level so all new tests should be under `test/` instead of the old `src/test` path.

**Comment by mweber15** [comment]
I haven't looked at Windows yet, but on Linux async functions use the CGU as the associated `DIFile`, while async blocks use the `DIFile` for the original source. Naively, it seems like this wouldn't be helpful from the debugger's perspective. Is this something I should look into further, or is this to be expected?

```rust
// issue-98678-async.rs
 13 // NONMSVC: !DISubprogram(name: "foo",{{.*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 1]],
 14 pub async fn foo() -> u8 { 5 }
 15  
 16 pub fn bar() -> impl std::future::Future<Output = u8> {
 17     // NONMSVC: !DICompositeType({{.*"}}{async_block_env#0}{{".*}}file: ![[#FILE]]{{.*}}line: [[# @LINE + 2]],
 18     //
 19     async {
 20         let x: u8 = foo().await;
 21         x + 5
 22     }
```
```llvm
; ModuleID = 'issue_98678_async.93abf016-cgu.0'
source_filename = "issue_98678_async.93abf016-cgu.0"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
...
!5 = !DIFile(filename: "/home/matt/src/rust/tests/codegen/issue-98678-async.rs/@/issue_98678_async.93abf016-cgu.0", directory: "/home/matt/src/rust")
!6 = distinct !DISubprogram(name: "foo", linkageName: "_ZN17issue_98678_async3foo17h01ba907115d7bc3cE", scope: !8, file: !7, line: 14, type: !9, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !4, templateParams: !19, retainedNodes: !19)
!7 = !DIFile(filename: "tests/codegen/issue-98678-async.rs", directory: "/home/matt/src/rust", checksumkind: CSK_MD5, checksum: "8646bf0aeb47a8db7f05394862674bbe")
...
!30 = !DICompositeType(tag: DW_TAG_structure_type, name: "{async_block_env#0}", scope: !31, file: !7, line: 19, size: 16, align: 8, elements: !32, templateParams: !19, identifier: "4b1579c68b9f70aaa924f3bce20bc1e1")
```

**Comment by mweber15** [comment]
I recombined the two enum tests into one and used the examples you suggested. If I understand correctly, and please feel free to correct me, the difference between "native" and "cpp-like" enums is an implementation detail and not the direct result of how enums are expressed in Rust. That being the case I see no reason for having the two separate test cases that I did.

**Review by wesleywiser — APPROVED** [review]
This is really great work! Thanks for all your effort on this!

**Comment by wesleywiser** [comment]
Let's do a perf run real quick just to see if there is any impact to LLVM throughput. 

@bors try @rust-timer queue

**Comment by wesleywiser** [comment]
The perf results are very strange. It looks like performing code generation for more modules than before but it's unclear to me why that is.

**Comment by WaffleLapkin** [comment]
What is the status here?

**Comment by apiraino** [comment]
Also. the results of the perf. run indicate something's weird, so switching review flag to investigate the results. Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

**Comment by mweber15** [comment]
I'm mostly using macOS now, and I don't think benchmarking supported on macOS, but I did have some luck collecting profiles. `webrender-2022` seems like the best benchmark to use, but it produces large amounts of profiling data so that was hard to work with. Instead I have mostly looked at `clap-3.1.6`.

Original (Debug IncrPatched):
flamegraph-Original-clap-3 1 6-Debug-IncrPatched0

Modified (Debug IncrPatched):
flamegraph-Modified-clap-3 1 6-Debug-IncrPatched0

I noticed a couple of places that seem like the main problem spots.

First is the absence of most of the time spent in `codegen_copy_artifacts_from_incr_cache` in the profile of the PR code (31.43% before, 2.78% after). At face value, that seems to suggest that something I've done here is inhibiting incremental artifact caching. My guess is that is also why `codegen_module_optimize` is a much larger chunk of the time in the changed version. Since the big regressions with this change are in incremental builds, this is probably the primary problem.

Second is that `codegen_module` accounts for significantly more time with this change than before (8.89% vs 0.7%). That is probably the main issue in the regressions for scenarios that aren't using incremental artifacts.

I don't yet have a sense for which part(s) of the change are at fault, but I think I can dig into these specific areas a bit and hopefully learn some more.

**Comment by mweber15** [comment]
Finally making some time to dig into this again -- my apologies for letting this linger.

The primary regression (possibly the only important issue, but I'm not sure), is [this](https://github.com/rust-lang/rust/pull/104342/files#diff-7270869bb27765bdcfd002efbec7b31f57697382330a6c90855f8e6be13d5e0dR1155) part of the change, including the additional metadata for `build_closure_env_di_node<'ll, 'tcx>`.

With this change, we get 34.6% of samples when profiling clap-3.1.6 Debug IncrPatched in `codegen_module_optimize` and 6.53% of samples in `codegen_copy_artifacts_from_incr_cache`. Changing that line to `None` changes the profile to 31.27% in `codegen_copy_artifacts_from_incr_cache` with only 1.74% in `codegen_module_optimize`. This is inline with the numbers I see without the rest of this change (31.06% `codegen_copy_artifacts_from_incr_cache`, 1.76% `codegen_module_optimize`).

I can only guess as to why this has the effect it does at the moment. I'll continue to investigate that, but one path forward for this PR might be to remove this part of the change and do another perf run.

**Comment by wesleywiser** [comment]
> Finally making some time to dig into this again -- my apologies for letting this linger.

No worries! I've also been struggling to find time to come back and dig in more. Sorry about that! 🙂 

Happy to try a run without line number information for closures and see what the perf impact is! Feel free to DM me on Zulip and I can kick that off. My suspicion is that there probably is not going to be a way to avoid regressing incremental significantly in some cases because we don't have a way to only change debuginfo without regenerating an entire CGU in which it appears. That looks to me like the primary cause of the most significant incremental regressions. 

What might make sense is to land this under a unstable (`-Z`) option for now in a disabled by default state. If we can identify parts that don't significantly affect compiler performance (for instance, maybe just location info for structs and enums?) then we can move those to be enabled by default.

**Comment by mweber15** [comment]
@wesleywiser thank you for re-running the perf. Looks like I at least managed to get the `clap` benchmark to look better, but as you suspected there are still issues. What would you expect a `-Z` option for this to look like? Is there a good example I could base this off of?

**Comment by mweber15** [comment]
All of the new stuff should now be behind `-Z more-source-locations-in-debuginfo`. Happy to rename/reorganize that if desired.

**Comment by wesleywiser** [comment]
I'm so sorry I failed to respond to your ping! Let me go ahead and explain how to add that unstable option and then we should be able to get this merged. 

Overall, it's pretty simple, there's just a few places you need to update. One is here

https://github.com/rust-lang/rust/blob/139fb2214675fed8143a12f6287a3a1e6e2e866d/compiler/rustc_session/src/options.rs#L1567-L1568

which declares the option itself. You'll need to provide a name (perhaps `debuginfo_type_line_numbers` or something similar?), the type (boolean is fine), default value (we'll want it disabled by default), whether this option is tracked in the incremental compilation system (`[TRACKED]`), and a brief help string that `-Zhelp` prints out. 

You'll also need to add a line to the test which verifies tracking occurs correctly:

https://github.com/rust-lang/rust/blob/master/compiler/rustc_interface/src/tests.rs#L748

(specify the *opposite* of the default value here so we see the value change).

Finally, add a page describing the flag to the unstable book (for example, something like [this page](https://github.com/rust-lang/rust/blob/139fb2214675fed8143a12f6287a3a1e6e2e866d/src/doc/unstable-book/src/compiler-flags/dylib-lto.md)). 

With that done, you can then access the value of the option by reading the `sess.opts.unstable_opts.debuginfo_type_line_numbers` field. 

Please feel free to ping me directly on Zulip if you have any questions and sorry again for the extreme delay!

**Comment by Dylan-DPC** [comment]
@mweber15 any updates on this?

**Comment by mweber15** [comment]
I have rebased this and have most of the tests working again for LLVM on AArch64. Unfortunately, I no longer have a readily available Windows system or VM with which to test these changes on that platform.

The intervening changes related to coroutines seem to have made the related debug info more complex. My test for the older generator debug info doesn't pass, and it looks like the object (`!20`) that gets linked to the expected line is not very useful without connecting some additional dots (`!13 elements` -> `!17` -> `!18 elements` -> `!19` -> `!20`):

```
!13 = !DICompositeType(tag: DW_TAG_structure_type, name: "{coroutine_env#1}", scope: !15, file: !14, size: 8, align: 8, elements: !17, templateParams: !23, identifier: "787f7d6164d1b98ef8e9251a1c66b317")
!14 = !DIFile(filename: "<unknown>", directory: "")
!15 = !DINamespace(name: "foo", scope: !16)
!16 = !DINamespace(name: "issue_98678_closure_coroutine", scope: null)
!17 = !{!18}
!18 = !DICompositeType(tag: DW_TAG_variant_part, scope: !13, file: !14, size: 8, align: 8, elements: !19, templateParams: !23, identifier: "cebd2411ebd90950cc37a2fde4475484", discriminator: !30)
!19 = !{!20, !24, !26, !28}
!20 = !DIDerivedType(tag: DW_TAG_member, name: "0", scope: !18, file: !21, line: 20, baseType: !22, size: 8, align: 8, extraData: i128 0)
!21 = !DIFile(filename: "src/rust/tests/codegen/issues/issue-98678-closure-coroutine.rs", directory: "/Users/matt", checksumkind: CSK_MD5, checksum: "d30f8374643284442e3419b1222ce1fb")
!22 = !DICompositeType(tag: DW_TAG_structure_type, name: "Unresumed", scope: !13, file: !14, size: 8, align: 8, elements: !23, identifier: "fe0d90a7f8d2ff7e261c6ecf66e6883")
```

I'll go ahead and push the changes that I have, including the failing test. I'm not sure right now what to with the above.

**Comment by wesleywiser** [comment]
Thanks @mweber15! I built & ran the tests on msvc, everything passed except the closure-coroutine one. I fixed that up and this should be good to go.

> it looks like the object (!20) that gets linked to the expected line is not very useful without connecting some additional dots

I think given that everything else works, we should land this now especially since it's behind the experimental codegen flag. Improving the line numbers for that doesn't need to block the rest of the work.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @mweber15 for all your work on this! 🏅 

@bors r+

**Comment by RalfJung** [comment]
@bors r-
(bors sync fixup)

**Comment by JohnCSimon** [comment]
@mweber15 
ping from triage - can you post your status on this PR? This PR has not received an update in a few months.

**Comment by mweber15** [comment]
Hi @JohnCSimon. This was ready to go, but I wasn't able to resolve some problems with Windows builds. @wesleywiser was helping with resolving those to finally wrap this up. It seems this is currently blocked on an i686-mingw failure, but I'm not sure how to replicate that CI run locally, or if I even can with a cross compiler.

**Comment by oskgo** [comment]
Maybe you could try asking for help on Zulip?

**Comment by Dylan-DPC** [comment]
@mweber15 any updates on this?

**Comment by mweber15** [comment]
I expect to have the time and the necessary resources to return to this very soon, hopefully within the next few days.

**Comment by SparrowLii** [comment]
@mweber15 Haved you solved the CI failure?

I think we can do a perf run again since the last one is one year ago. Some changes may improve the result of regressions.
@bors try @rust-timer queue

**Comment by nnethercote** [comment]
@Kobzol Sparrow and I both tried and failed to trigger a perf run here. Any idea what's wrong?

**Comment by Kobzol** [comment]
The problem is not with perf, but bors, as the try build hasn't been started.

**Comment by SparrowLii** [comment]
Looks like `i686-mingw` still failed, do you have some clues now? @mweber15

**Comment by mweber15** [comment]
This particular failure seems to be due to the path separator, as I wrote the `NONMSVC-DAG` checks assuming they applied to Unix-like systems exclusively. I'm not sure what other issues might be lurking behind this one, though it might be the only problem. I don't personally use any MinGW toolchains so I don't have it readily available for testing.

Why wasn't this CI triggered automatically after I pushed? Finding out this is still a problem weeks after last touching this is incredibly frustrating. Was there something else I should have done to trigger this to run?

**Comment by SparrowLii** [comment]
@Kobzol Do you konw if there is a command for the **bot** to test a certain target?

**Comment by mweber15** [comment]
I reproduced and fixed the problem using `x86_64-pc-windows-msvc`. I ran into a linker error trying to test `i686-pc-windows-msvc`, so I was not able to confirm that there aren't any other issues lurking with that toolchain. I will circle back to that if that CI still fails after this change, but hopefully it was only the separator issue.

**Comment by Kobzol** [comment]
> @Kobzol Do you konw if there is a command for the **bot** to test a certain target?

What do you mean by target here?

**Comment by SparrowLii** [comment]
> > @Kobzol Do you konw if there is a command for the **bot** to test a certain target?
> 
> What do you mean by target here?

run CI for `i686-mingw` separately， for example

**Comment by Kobzol** [comment]
Yeah, you can do that with arbitrary try builds (https://rustc-dev-guide.rust-lang.org/tests/ci.html#try-builds - see the part with `try-job`).
