### PR TITLE
Remove in band lifetimes

### LINKED ISSUE #44524: Tracking issue for RFC 2115: In-band lifetime bindings
Update for 2022: With the [FCP close](https://github.com/rust-lang/rust/issues/44524#issuecomment-988260463) finished, this is no longer on a stabilization path, and will likely be removed from nightly.  The issue will remain open so long as it's referenced by an implemented `feature` in the compiler, however.

---

This is a tracking issue for the RFC "In-band lifetime bindings" (rust-lang/rfcs#2115).

**Steps:**

- [x] Stabilize `'_` (this has its own tracking issue, #48469)
- [x] ~~#15872: Enable elision in impl headers ([mentoring instructions here](https://github.com/rust-lang/rust/issues/15872#issuecomment-283987512))~~
  - Now tracked by `impl_header_lifetime_elision` in https://github.com/rust-lang/rust/issues/15872
- [ ] https://github.com/rust-lang/rust/issues/45667: Support `'_` in where-clauses on functions. -- blocked on #15872 
- [x] https://github.com/rust-lang/rust/issues/46042: Enable implicit binders.
- [ ] Lint against single-letter lifetimes not confined to functions (?)
- [ ] Lint against single-use lifetimes: #44752
   * note: @pnkfelix added this as a "prereq", but its possible we do not have consensus that it is required (though @pnkfelix believes it was part of the RFC...)
- [ ] Apply to rustc, experimenting with naming conventions (e.g., working through the affect on rustc).
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- What conventions should we use for lifetime names, and should they be enforced via lint?
  - Considerations:
    - To help avoiding accidental shadowing, [make it easy to know where a lifetime name is bound](https://github.com/rust-lang/rfcs/pull/2115#issuecomment-327629159) (and in particular if it is bound in some enclosing, possibly out-of-sight, scope).
    - [Permitting "well-known" names like `'tcx` and `'gcx` to be used consistently](https://github.com/rust-lang/rfcs/pull/2115#issuecomment-328211495)
  - Some prior proposals:
    - Names bound in impls are upper-case (but: fails to permit well-known names)
    - Single-letter names cannot be bound across scopes (but: can't easily tell if longer names are bound across scopes or not)
- ~~Can we find an unequivocally-better syntax than `'_` for elided lifetimes?~~
  - These are now stable, so we didn't

Known bugs (possibly incomplete list):
 - [ ] https://github.com/rust-lang/rust/issues/52532

### PR DESCRIPTION
**Pull request by compiler-errors**
As discussed in t-lang backlog bonanza, the `in_band_lifetimes` FCP closed in favor for the feature not being stabilized. This PR removes `#![feature(in_band_lifetimes)]` in its entirety.

Let me know if this PR is too hasty, and if we should instead do something intermediate for deprecate the feature first.

r? @scottmcm (or feel free to reassign, just saw your last comment on #44524)
Closes #44524

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -684,7 +680,7 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
         // that collisions are ok here and this shouldn't
         // really show up for end-user.
         let (str_name, kind) = match hir_name {
-            ParamName::Plain(ident) => (ident.name, hir::LifetimeParamKind::InBand),
+            ParamName::Plain(ident) => (ident.name, hir::LifetimeParamKind::Explicit),
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/lib.rs:683]: This is the only suspicious change.

**Comment by compiler-errors** [comment]
Thank you CI -- I'll add those error codes back then! 

@rustbot author

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/lib.rs:683]: Async fns declare named elided lifetimes. We should give them a category here -- not sure if it's `LifetimeParamKind::Explicit` though. Maybe I can add `LifetimeParamKind::Explicit` back. 

It all funnels into `hir::LifetimeDefOrigin::ExplicitOrElided` though, so I don't think the distinction matters?

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 2]
```diff
@@ -141,13 +141,9 @@ struct LoweringContext<'a, 'hir: 'a> {
     /// indicate whether or not we're in a place where new lifetimes will result
     /// in in-band lifetime definitions, such a function or an impl header,
     /// including implicit lifetimes from `impl_header_lifetime_elision`.
-    is_collecting_in_band_lifetimes: bool,
+    is_collecting_anonymous_lifetimes: bool,
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/lib.rs:144]: I renamed this to `anonymous`, since this handles both elided and in-band lifetimes, but we now only have the former. Open to calling this something like `is_collecting_elided_lifetimes` tho!

**Comment by compiler-errors** [comment]
I think this is ready for.. at least an initial review

@rustbot ready

**Comment by scottmcm** [comment]
I'm not a compiler reviewer, so since you mention there are few nuanced bits here, it's probably better than someone who knows it better takes a look.

r? rust-lang/compiler

I could probably review some pieces, if you felt like splitting it up.  (It seems like there are some easy bits, like updating tests that aren't about in-band to stop using it.  Or maybe removing the special "do you want to try in-band?" hint would be a pure removal.)  But since this is almost entirely red, it's not clear to me that it would be worth the effort of splitting.  Hopefully the compiler reviewer will just be able to skim it and go "yup, seems fine".

File: compiler/rustc_feature/src/active.rs [hunk 3]
```diff
@@ -397,8 +397,6 @@ declare_features! (
     (active, if_let_guard, "1.47.0", Some(51114), None),
     /// Allows using imported `main` function
     (active, imported_main, "1.53.0", Some(28937), None),
-    /// Allows in-band quantification of lifetime bindings (e.g., `fn foo(x: &'a u8) -> &'a u8`).
-    (active, in_band_lifetimes, "1.23.0", Some(44524), None),
```
Comment (petrochenkov) [inline compiler/rustc_feature/src/active.rs:401]: Features are usually moved from the `active` list to the `removed` list instead of being removed entirely.

File: compiler/rustc_error_codes/src/error_codes.rs [hunk 4]
```diff
@@ -397,8 +397,6 @@ E0668: include_str!("./error_codes/E0668.md"),
 E0669: include_str!("./error_codes/E0669.md"),
 E0670: include_str!("./error_codes/E0670.md"),
 E0671: include_str!("./error_codes/E0671.md"),
-E0687: include_str!("./error_codes/E0687.md"),
```
Comment (GuillaumeGomez) [inline compiler/rustc_error_codes/src/error_codes.rs:400]: Please don't remove them from the listing.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]

File: compiler/rustc_error_codes/src/error_codes.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply compiler/rustc_error_codes/src/error_codes.rs:400]: (I'll add a tidy check for that one too :smile: )

Comment (compiler-errors) [reply compiler/rustc_error_codes/src/error_codes.rs:400]: oops!

Comment (GuillaumeGomez) [reply compiler/rustc_error_codes/src/error_codes.rs]: Just so you know: https://github.com/rust-lang/rust/pull/93898 :)

**Comment by cjgillot** [comment]
Can `hir::LifetimeParamKind::InBand` be removed?
You may also need to remove the check for mixed explicit and in-band lifetime definitions during lifetime resolution.

**Comment by compiler-errors** [comment]
@cjgillot, I actually removed that enum variant [here](https://github.com/rust-lang/rust/pull/93845/files#diff-67c494d6d292cbe0a96d420fa02cf4589c7fad5a8d9abbdfa317d49a8bdce6daL473). Is there anything I missed?

**Comment by cjgillot** [comment]
Sorry @compiler-errors, read too fast.

Now that https://github.com/rust-lang/rust/pull/93845 is merged, you should be able to remove `in_scope_lifetime` and code that updates it.

**Comment by compiler-errors** [comment]
@cjgillot, did you mean to mention another PR? #93845 is this one :)

I tried to remove `in_scope_lifetimes`, but that (+ `LoweringContext::with_in_scope_lifetime_defs`) is apparently used somewhere in async fn lowering that I don't exactly understand. Removing it leads to this code (`ui/async-await/issue-61949-self-return-type.rs`):
```rust
// edition:2018

// This test checks that `Self` is prohibited as a return type. See #61949 for context.

pub struct Foo<'a> {
    pub bar: &'a i32,
}

impl<'a> Foo<'a> {
    pub async fn new(_bar: &'a i32) -> Self {
    //~^ ERROR `async fn` return type cannot contain a projection or `Self` that references lifetimes from a parent scope
        Foo {
            bar: &22
        }
    }
}

async fn foo() {
    let x = {
        let bar = 22;
        Foo::new(&bar).await
    };
    drop(x);
}

fn main() { }
```

Yielding new errors like:
```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> $DIR/issue-61949-self-return-type.rs:10:40
   |
LL | impl<'a> Foo<'a> {
   |      -- hidden type `impl Future<Output = [async output]>` captures the lifetime `'a` as defined here
LL |     pub async fn new(_bar: &'a i32) -> Self {
   |                                        ^^^^
```

**Comment by cjgillot** [comment]
I meant https://github.com/rust-lang/rust/pull/91403. I will take another look.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_ast_lowering/src/lib.rs:683]: This case should only happen when synthetizing lifetimes for an async fn return `impl Future` type. There should not be a difference, but we got bit before.

File: compiler/rustc_middle/src/middle/resolve_lifetime.rs [hunk 5]
```diff
@@ -15,8 +15,6 @@ use rustc_macros::HashStable;
 pub enum LifetimeDefOrigin {
```
Comment (cjgillot) [inline compiler/rustc_middle/src/middle/resolve_lifetime.rs:15]: This enum was just used to forbid in-band lifetimes in some places. It can be fully removed now.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_ast_lowering/src/lib.rs:683]: Once `LifetimeDefOrigin` is removed, `LifetimeParamKind` is only used in lifetime resolution diagnostics and rustdoc to filter elided lifetimes. Therefore `LifetimeParamKind::Explicit` is fine.

**Comment by cjgillot** [comment]
r=me with LifetimeDefOrigin removed and commits squashed.

**Comment by Dylan-DPC** [comment]
failed in #94326

@bors r-

**Comment by compiler-errors** [comment]
@Dylan-DPC wrong PR referenced?

**Comment by Dylan-DPC** [comment]
ye fixed now :P

**Comment by compiler-errors** [comment]
I'll re-bless when I get back to my computer.

**Comment by compiler-errors** [comment]
Had to bless tests with `--compare-mode=nll`. That did the trick.

when you have the free time, @cjgillot can you r+ again? thank you!
