### PR TITLE
only set non-ADT derive error once per attribute, not per trait

### LINKED ISSUE #43927: `derive` may only be applied to structs, enums and unions error should only show once per derive
The error ``` `derive` may only be applied to structs, enums and unions``` currently fires for each derived trait in the attribute pointing at the trait it is implementing. It should instead fire once per attribute, pointing at the `derive`.

## Minimal Code

```
#![allow(dead_code)]

#![derive(Debug, PartialEq, Eq)]
struct DerivedOn;

fn main() {}
```

## Output

```
   Compiling playground v0.0.1 (file:///playground)
error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:3:29
  |
3 | #![derive(Debug, PartialEq, Eq)]
  |                             ^^

error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:3:18
  |
3 | #![derive(Debug, PartialEq, Eq)]
  |                  ^^^^^^^^^

error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:3:11
  |
3 | #![derive(Debug, PartialEq, Eq)]
  |           ^^^^^

error: aborting due to 3 previous errors

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

## Expected Output

```
   Compiling playground v0.0.1 (file:///playground)
error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:3:29
  |
3 | #![derive(Debug, PartialEq, Eq)]
  |    ^^^^^^

error: aborting due to 1 previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by zackmdavis**
I found the expansion code very hard to follow, leaving me unsure as to whether this might somehow be done better, but this patch does give us the behavior requested in #43927 (up to exact choice of span; here, it's the entire attribute, not just the `derive` token).

(Note to GitHub robots: _resolves #43927_.)

r? @jseyfried

### CODE REVIEW

File: src/libsyntax_ext/deriving/generic/mod.rs [hunk 1]
```diff
@@ -428,8 +428,8 @@ impl<'a> TraitDef<'a> {
                         }
                     }
                     _ => {
-                        cx.span_err(mitem.span,
-                                    "`derive` may only be applied to structs, enums and unions");
+                        // This not-an-ADT case is an error, but it should have
```
Comment (oli-obk) [inline src/libsyntax_ext/deriving/generic/mod.rs]: so this branch should be `bug!("non-ADT derive should have been caught during expansion")`

**Comment by oli-obk** [comment]
You also need to update some compile-fail tests to your changes.
<details>
  <summary>
Click to expand

[00:47:25]     [compile-fail] compile-fail/deriving-non-type.rs
[00:47:25]     [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs
[00:47:25]     [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive.rs
[00:47:25]     [compile-fail] compile-fail/issue-36617.rs

</summary>

```
[00:47:25] failures:
[00:47:25] 
[00:47:25] ---- [compile-fail] compile-fail/deriving-non-type.rs stdout ----
[00:47:25] 	
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:15: unexpected "error": '15:1: 15:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:18: unexpected "error": '18:1: 18:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:21: unexpected "error": '21:1: 21:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:24: unexpected "error": '24:1: 24:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:27: unexpected "error": '27:1: 27:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:30: unexpected "error": '30:1: 30:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:33: unexpected "error": '33:1: 33:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:36: unexpected "error": '36:1: 36:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:39: unexpected "error": '39:1: 39:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:15: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:18: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:21: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:24: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:27: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:30: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:33: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:36: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/deriving-non-type.rs:39: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: 9 unexpected errors found, 9 expected errors not found
[00:47:25] status: exit code: 101
[00:47:25] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/deriving-non-type.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/deriving-non-type.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -A unused -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/deriving-non-type.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers
[00:47:25] unexpected errors (from JSON output): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "15:1: 15:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "18:1: 18:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "21:1: 21:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "24:1: 24:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 27,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "27:1: 27:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 30,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "30:1: 30:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 33,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "33:1: 33:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 36,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "36:1: 36:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 39,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "39:1: 39:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] not found errors (from test file): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 27,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 30,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 33,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 36,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 39,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] thread '[compile-fail] compile-fail/deriving-non-type.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:1133:12
[00:47:25] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:47:25] 
[00:47:25] ---- [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs stdout ----
[00:47:25] 	
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:15: unexpected "error": '15:1: 15:18: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:18: unexpected "error": '18:1: 18:17: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:21: unexpected "error": '21:17: 21:34: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:24: unexpected "error": '24:5: 24:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:40: unexpected "error": '40:5: 40:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:44: unexpected "error": '44:5: 44:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:15: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:18: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:21: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:24: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:28: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:32: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:36: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:40: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs:44: expected error not found: cannot find derive macro `x3300` in this scope
[00:47:25] 
[00:47:25] error: 6 unexpected errors found, 9 expected errors not found
[00:47:25] status: exit code: 101
[00:47:25] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -A unused -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers
[00:47:25] unexpected errors (from JSON output): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "15:1: 15:18: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "18:1: 18:17: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "21:17: 21:34: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "24:5: 24:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 40,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "40:5: 40:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 44,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "44:5: 44:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] not found errors (from test file): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 28,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 32,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 36,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 40,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 44,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "cannot find derive macro `x3300` in this scope"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] thread '[compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:1133:12
[00:47:25] 
[00:47:25] ---- [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive.rs stdout ----
[00:47:25] 	
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:15: unexpected "error": '15:1: 15:18: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:18: unexpected "error": '18:1: 18:17: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:21: unexpected "error": '21:17: 21:34: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:24: unexpected "error": '24:5: 24:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:37: unexpected "error": '37:5: 37:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:41: unexpected "error": '41:5: 41:21: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:15: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:18: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:21: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:24: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:37: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs:41: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: 6 unexpected errors found, 6 expected errors not found
[00:47:25] status: exit code: 101
[00:47:25] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/feature-gate/issue-43106-gating-of-derive.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate/issue-43106-gating-of-derive.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -A unused -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate/issue-43106-gating-of-derive.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers
[00:47:25] unexpected errors (from JSON output): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "15:1: 15:18: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "18:1: 18:17: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "21:17: 21:34: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "24:5: 24:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 37,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "37:5: 37:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 41,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "41:5: 41:21: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     }
[00:47:25] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:323:21
[00:47:25] ]
[00:47:25] 
[00:47:25] not found errors (from test file): [
[00:47:25]     Error {
[00:47:25]         line_num: 15,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 18,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 21,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 24,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 37,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     },
[00:47:25]     Error {
[00:47:25]         line_num: 41,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] thread '[compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:1133:12
[00:47:25] 
[00:47:25] ---- [compile-fail] compile-fail/issue-36617.rs stdout ----
[00:47:25] 	
[00:47:25] error: /checkout/src/test/compile-fail/issue-36617.rs:11: unexpected "error": '11:1: 11:17: `derive` may only be applied to structs, enums, and unions'
[00:47:25] 
[00:47:25] error: /checkout/src/test/compile-fail/issue-36617.rs:11: expected error not found: `derive` may only be applied to structs, enums and unions
[00:47:25] 
[00:47:25] error: 1 unexpected errors found, 1 expected errors not found
[00:47:25] status: exit code: 101
[00:47:25] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/issue-36617.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36617.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -A unused -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36617.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers
[00:47:25] unexpected errors (from JSON output): [
[00:47:25]     Error {
[00:47:25]         line_num: 11,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "11:1: 11:17: `derive` may only be applied to structs, enums, and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] not found errors (from test file): [
[00:47:25]     Error {
[00:47:25]         line_num: 11,
[00:47:25]         kind: Some(
[00:47:25]             Error
[00:47:25]         ),
[00:47:25]         msg: "`derive` may only be applied to structs, enums and unions"
[00:47:25]     }
[00:47:25] ]
[00:47:25] 
[00:47:25] thread '[compile-fail] compile-fail/issue-36617.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:1133:12
[00:47:25] 
[00:47:25] 
[00:47:25] failures:
[00:47:25]     [compile-fail] compile-fail/deriving-non-type.rs
[00:47:25]     [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs
[00:47:25]     [compile-fail] compile-fail/feature-gate/issue-43106-gating-of-derive.rs
[00:47:25]     [compile-fail] compile-fail/issue-36617.rs
[00:47:25] 
[00:47:25] test result: [31mFAILED(B[m. 2715 passed; 4 failed; 13 ignored; 0 measured; 0 filtered out
```
</details>

File: src/libsyntax/ext/expand.rs [hunk 2]
```diff
@@ -282,6 +282,22 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
                     let expansion = self.expand_invoc(invoc, ext);
                     self.collect_invocations(expansion, &[])
                 } else if let InvocationKind::Attr { attr: None, traits, item } = invoc.kind {
+                    if let Annotatable::Item(ref item) = item {
```
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Could we also error on `Annotatable::TraitItem` and `Annotatable::ImplItem` here and then also get rid of the other corresponding error in `src/libsyntax_ext/deriving/generic/mod.rs`? e.g.
```rust
let derive_allowed = match item {
    Annotatable::Item(ref item) => match item.node {
        ast::ItemKind::Struct(..) | ast::ItemKind::Enum(..) | ast::ItemKind::Union(..) => true,
        _ => false,
    _ => false,
};
if !derive_allowed {
    // error
}
```

**Comment by jseyfried** [comment]
Looks good! r=me with @oli-obk's comment addressed.

File: src/libsyntax_ext/deriving/generic/mod.rs (hunk 1 above)
Comment (zackmdavis) [reply src/libsyntax_ext/deriving/generic/mod.rs]: Unfortunately, this will ICE: setting the `span_err` during expansion doesn't stop compilation from reaching this point. (But maybe it should??)

**Comment by zackmdavis** [comment]
Updated. Travis error appears spurious (just one macOS subjob failed, and [its terminal log](https://travis-ci.org/rust-lang/rust/jobs/268773025) says that `git fetch` failed).

There are two potential concerns, though:

* The code in `libsyntax_ext/deriving/generic/mod.rs ` still runs, so we can't put an assertion there unless we somehow stop compilation earlier.
* As revealed by the compile-fail tests, if the non-ADT-derive error occurs, then we don't get to see any derive-macro-not-found errors (which will surface the next time the user attempts to compile after fixing the erroneous non-ADT derives). This isn't _necessarily_ a blocker (it's pretty ordinary for errors in one pass to overshadow others), but it wasn't intended and I don't understand why it's happening.

**Comment by eddyb** [comment]
@zackmdavis Restarted the dummy macOS build, should be green in a few minutes.

**Comment by arielb1** [comment]
@zackmdavis do you think we should land this as is, or are you interested in perfecting it? If that, are you still interested in working on this? Just a friendly ping too make sure it isn't getting lost.

**Comment by zackmdavis** [comment]
@arielb1 My disposition is to merge as-is (the reservations bulleted in my previous comment being minor IMO), but if someone were to argue that it's important to preserve the exact error behavior specified in the original compile-fail/issue-43106-gating-of-derive-2.rs, I would respect that judgment, too.

**Comment by carols10cents** [comment]
@jseyfried sounds like this is in your court for review. what do you think?

**Comment by carols10cents** [comment]
ping @jseyfried @rust-lang/compiler for review please!

File: src/libsyntax/ext/expand.rs [hunk 3]
```diff
@@ -282,6 +282,24 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
...
+                            _ => false,
+                        },
+                        _ => false,
+                    };
+                    if !derive_allowed {
+                        let span = item.attrs().iter()
+                            .find(|attr| attr.check_name("derive"))
+                            .expect("`derive` attribute should exist").span;
+                        self.cx.span_err(span,
+                                         "`derive` may only be applied to structs, enums, \
```
Comment (estebank) [inline src/libsyntax/ext/expand.rs]: Can you keep the existing output and avoid the oxford comma? Not because I'm against it but I'd prefer to keep this change small (so it doesn't affect `compile-fail/deriving-non-type.rs` at all).

During the impl period I'm going to audit all the existing diagnostic output in order to identify current conventions to write them down. Doing this I fully expect to find inconsistent wording and will try to reach consensus for them.

File: src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs [hunk 4]
```diff
@@ -8,23 +8,9 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
-// `#![derive]` is interpreted (and raises errors) when it occurs at
-// contexts other than ADT definitions. This test checks cases where
-// the derive-macro does not exist.
+// This test checks cases where the derive-macro does not exist.
 
-#![derive(x3300)]
```
Comment (estebank) [inline src/test/compile-fail/feature-gate/issue-43106-gating-of-derive-2.rs]: What's the reason to remove these?

File: src/test/ui/span/issue-43927-non-ADT-derive.stderr [hunk 5]
```diff
@@ -0,0 +1,8 @@
+error: `derive` may only be applied to structs, enums, and unions
+  --> $DIR/issue-43927-non-ADT-derive.rs:13:1
+   |
+13 | #![derive(Debug, PartialEq, Eq)] // should be an outer attribute!
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Comment (estebank) [inline src/test/ui/span/issue-43927-non-ADT-derive.stderr]: This is a great example of a case where a `note` pointing out that this derive is being applied to the outer context instead of the `struct` immediately after would be beneficial. If you don't want to add that on this PR, could you please file a ticket for it?

It could be something along the lines of

```
error: `derive` may only be applied to structs, enums, and unions
  --> $DIR/issue-43927-non-ADT-derive.rs:13:1
   |
13 | #![derive(Debug, PartialEq, Eq)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ derive cannot be applied to outer mod
note: as it is written, the derive is applied to the outer scope, did you mean to apply it to the next element?
   |
13 | #[derive(Debug, PartialEq, Eq)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

File: src/libsyntax_ext/deriving/generic/mod.rs (hunk 1 above)
Comment (estebank) [reply src/libsyntax_ext/deriving/generic/mod.rs]: Can you add a `debug!` statement here then? Also add a comment pointing at `libsyntax/ext/expand.rs:MacroExpand::expand()` for the handling of this case.

**Review by estebank — COMMENTED** [review]
Other than a few nitpicks I'm r+ too.

File: src/libsyntax_ext/deriving/generic/mod.rs (hunk 1 above)
Comment (zackmdavis) [reply src/libsyntax_ext/deriving/generic/mod.rs]: > Can you add a debug! statement here then?

_Surprisingly_, no: the `libsyntax_ext` crate doesn't have `debug!` in scope, and when I tried adding `#[macro use] extern crate log;` to lib.rs, we get "can't find crate for `log`". I don't understand what's going on there. (Added the expand filename comment pointer, though.)

File: src/libsyntax/ext/expand.rs (hunk 3 above)
Comment (zackmdavis) [reply src/libsyntax/ext/expand.rs]: I trust that the community will affirm the correctness of the serial comma at that time.

File: src/test/ui/span/issue-43927-non-ADT-derive.stderr (hunk 5 above)
Comment (zackmdavis) [reply src/test/ui/span/issue-43927-non-ADT-derive.stderr]: 083f053

**Comment by zackmdavis** [comment]
(force-pushed) 

* We no longer add a serial comma to the message, leaving that to a future error-message auditing pass.
* "error set earlier" comments in libsyntax_ext note file/function where
    * unfortunately, the `debug!` macro isn't available in `libsyntax_ext` (and trying to add the `log` crate didn't work), so the suggestion to use that was not taken in this revision
* another commit adds a suggestion to use an outer attribute (`#`, not `#!`) in the case where the offending attribute was an inner

**Comment by Havvy** [comment]
:heart_decoration:
