### PR TITLE
Identify unreachable subpatterns more reliably

### LINKED ISSUE #80501: Spurious unreachable_patterns with macro
### Code

I tried this code:

```rust
pub enum TypeCtor {
    Bool,
    Slice,
    Array,
}

pub struct ApplicationTy {
    pub ctor: TypeCtor,
    pub parameters: (),
}

pub enum Ty {
    Apply(ApplicationTy),
}

macro_rules! ty_app {
    ($ctor:pat, $param:pat) => {
        crate::Ty::Apply(crate::ApplicationTy {
            ctor: $ctor,
            parameters: $param,
        })
    };
    ($ctor:pat) => {
        ty_app!($ctor, _)
    };
}

fn _foo(ty: Ty) {
    match ty {
        ty_app!(TypeCtor::Array, _st) | ty_app!(TypeCtor::Slice, _st) => {}
        _ => {}
    }

    // same as above, with the macro expanded
    match ty {
        Ty::Apply(crate::ApplicationTy {
            ctor: TypeCtor::Array,
            parameters: _st,
        })
        | Ty::Apply(crate::ApplicationTy {
            ctor: TypeCtor::Slice,
            parameters: _st,
        }) => {}
        _ => {}
    }
}

fn main() {}
```

I expected to see this happen: code should build fine

Instead, this happened: `unreachable pattern` in the first, but not on the second match

```
warning: unreachable pattern
  --> src/main.rs:18:9
   |
18 | /         crate::Ty::Apply(crate::ApplicationTy {
19 | |             ctor: $ctor,
20 | |             parameters: $param,
21 | |         })
   | |__________^
...
30 |           ty_app!(TypeCtor::Array, _st) | ty_app!(TypeCtor::Slice, _st) => {}
   |                                           ----------------------------- in this macro invocation
   |
   = note: `#[warn(unreachable_patterns)]` on by default
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 1 warning emitted
```

### Version it worked on

It most recently worked on:

```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

### Version with regression

```
rustc 1.50.0-beta.1 (05b602367 2020-12-29)
binary: rustc
commit-hash: 05b6023675d77979637b04a350c85903fbf59257
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.50.0-beta.1
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by Nadrieril**
In https://github.com/rust-lang/rust/pull/80104 I used `Span`s to identify unreachable sub-patterns in the presence of or-patterns during exhaustiveness checking. In https://github.com/rust-lang/rust/issues/80501 it was revealed that `Span`s are complicated and that this was not a good idea.
Instead, this PR identifies subpatterns logically: as a path in the tree of subpatterns of a given pattern. I made a struct that captures a set of such subpatterns. This is a bit complex, but thankfully self-contained; the rest of the code does not need to know anything about it.
Fixes https://github.com/rust-lang/rust/issues/80501. I think I managed to keep the perf neutral.

r? @varkor

### CODE REVIEW

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 1]
```diff
@@ -600,191 +619,306 @@ impl<'p, 'tcx> FromIterator<PatStack<'p, 'tcx>> for Matrix<'p, 'tcx> {
...
+/// ```
+/// match (true, true) {
+///     (true, true) => {}
+///     (true | false, true | false) => {}
+/// }
+/// ```
+/// When we try the alternatives of the first or-pattern, the last `true` is unreachable in the
+/// first alternative but no the other. So we don't want to report it as unreachable. Therefore we
+/// intersect sets of unreachable patterns coming from different alternatives in order to figure
+/// out which subpatterns are overall unreachable.
```
Comment (varkor) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:638]: This paragraph is slightly unclear. "the alternatives of the first or-pattern" indicates to me the two `true | false` patterns, but I'm not sure what "the last `true` is unreachable in the first alternative" means: there's only one `true` in the first alternative `true | false`.
"but no the other" should be "but not the other"

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 2]
```diff
@@ -600,191 +619,306 @@ impl<'p, 'tcx> FromIterator<PatStack<'p, 'tcx>> for Matrix<'p, 'tcx> {
...
+#[derive(Debug, Clone)]
+enum SubPatSet<'p, 'tcx> {
+    /// The set containing the full pattern.
```
Comment (varkor) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:641]: Maybe expand this, e.g. `The set containing the full pattern, meaning the entire pattern is unreachable.`.

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 3]
```diff
@@ -600,191 +619,306 @@ impl<'p, 'tcx> FromIterator<PatStack<'p, 'tcx>> for Matrix<'p, 'tcx> {
...
-    /// only in the presence of or-patterns, otherwise it stays empty.
-    Useful(SpanSet),
-    /// Carries a list of witnesses of non-exhaustiveness.
-    UsefulWithWitness(Vec<Witness<'tcx>>),
-    NotUseful,
+enum Usefulness<'p, 'tcx> {
+    /// Carries a set of subpatterns that have been found to be unreachable. If full, this
+    /// indicates the whole pattern is unreachable. If not, this indicates that the pattern is
+    /// reachable but has some unreachable sub-patterns (due to or-patterns). In the absence of
+    /// or-patterns, this is either `Empty` or `Full`.
```
Comment (varkor) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:852]:
```suggestion
    /// or-patterns, this is either `Empty` (meaning the pattern is reachable) or `Full` (meaning
    /// the pattern is unreachable).
```
My heuristic for writing comments is that the reader may be coming from a different area of the compiler and not be entirely familiar with the terminology, so it helps to repeat oneself frequently.

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 4]
```diff
@@ -600,191 +619,306 @@ impl<'p, 'tcx> FromIterator<PatStack<'p, 'tcx>> for Matrix<'p, 'tcx> {
...
 
 #[derive(Clone, Debug)]
-crate enum Usefulness<'tcx> {
-    /// Pontentially carries a set of sub-branches that have been found to be unreachable. Used
-    /// only in the presence of or-patterns, otherwise it stays empty.
-    Useful(SpanSet),
-    /// Carries a list of witnesses of non-exhaustiveness.
-    UsefulWithWitness(Vec<Witness<'tcx>>),
-    NotUseful,
+enum Usefulness<'p, 'tcx> {
```
Comment (varkor) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:848]: I've just noticed we don't have a comment for `Usefulness`. I know it's described in the algorithm description at the top of the file, but could you write a brief comment describing what `Usefulness` means and the distinction between the two variants? It doesn't need to be detailed; just a quick overview for a reader skimming the code.

File: compiler/rustc_mir_build/src/thir/pattern/usefulness.rs [hunk 5]
```diff
@@ -1017,10 +1155,18 @@ crate struct MatchArm<'p, 'tcx> {
     crate has_guard: bool,
 }
 
+#[derive(Clone, Debug)]
+crate enum Reachability {
+    /// Potentially carries a set of sub-branches that have been found to be unreachable. Used only
+    /// in the presence of or-patterns, otherwise it stays empty.
+    Reachable(Vec<Span>),
```
Comment (varkor) [inline compiler/rustc_mir_build/src/thir/pattern/usefulness.rs:1162]: This comment is slightly confusing, because it says "that have found to be unreachable", but the variant is called `Reachable`.

**Review by varkor — COMMENTED** [review]
I've just left a few comments about the comments. Apologies if I made any mistakes about the meaning; it's a little late. I've only skimmed the code so far, so I'll take a better look soon. My appreciation for the complexity of handling or-patterns correctly continues to grow.

**Comment by Nadrieril** [comment]
I realized it's much clearer if we keep a set of reachable subpatterns instead of a set of unreachable ones. There were negations everywhere it was hurting my head. And I incorporated your review.

**Comment by varkor** [comment]
Thanks, these changes definitely make the code clearer! Looks good to me.

@bors r+

**Comment by Nadrieril** [comment]
Thanks for expressing your confusion ^^

**Comment by lnicola** [comment]
Will this be backported to the beta branch?

**Comment by Nadrieril** [comment]
No idea

**Comment by rylev** [comment]
@Nadrieril @varkor This seems to have caused a [performance regression](https://perf.rust-lang.org/compare.html?start=5a5f3a980c0d2afd55f2162300339471378e341f&end=36ecbc94eb6be90bc38b2d0fdd4bfac3f34d9923&stat=instructions:u) after merging. 

The regression is in a benchmark specifically for pattern match which is impacted by this change. The [`check match`](https://perf.rust-lang.org/detailed-query.html?commit=36ecbc94eb6be90bc38b2d0fdd4bfac3f34d9923&base_commit=5a5f3a980c0d2afd55f2162300339471378e341f&benchmark=match-stress-enum-check&run_name=full) query was responsible for the regression.

**Comment by Nadrieril** [comment]
Hm, the perf run we did was neutral... Given that the last commit is purely about naming, the cause must be the rebase I did after the perf run. The `match-stress-enum` bench is very sensitive, I expect that I undid a lucky gain from a concurrent PR due to inlining or something like that.

**Comment by rylev** [comment]
@Nadrieril the question now is is whether this is an acceptable performance regression. 1% on a stress benchmark is not a cause for great concern, but perhaps trying to gain that performance back might be helpful.

**Comment by Nadrieril** [comment]
Hm, well I can't reproduce the perf loss locally with `incremental=true`, and if I set `incremental=false` then I get a ~1% perf _gain_ instead... I'm guessing something else must have changed on `master` in the mean time, but that sounds hard to diagnose. I think I'll pass on this one sorry.

**Comment by apiraino** [comment]
I'll label this with @rustbot label T-compiler

(not 100% sure though)

**Comment by apiraino** [comment]
Backports declined ([compiler meeting notes](https://zulip-archive.rust-lang.org/238009tcompilermeetings/76458weeklymeeting2021021854818.html#226824687))

@rustbot label -beta-nominated -stable-nominated
