### PR TITLE
Overhaul filename handling for cross-compiler consistency

### LINKED ISSUE #148328: `std::panic::Location::caller().file()` uses absolute path when monomorphized in a different crate.
I want to create a `const &str` based on the current location, but compilation fails with an out of bounds exception.

The following is a minimal reproduction for the core problem: The `&str` returned by `std::panic::Location::caller().file()` sometimes is the full path for const evaluation with async.

```rust
pub async fn async_example() {
    const LOCATION: &std::panic::Location = std::panic::Location::caller();
    const FILE: &str = LOCATION.file();

    // (expected) evaluation panicked: dependency/src/lib.rs 
    // const VALUE: () = panic!("{}", FILE);

    // (unexpected) evaluation panicked: /Users/anton.wetzel/projects/locate_what/dependency/src/lib.rs 
    const LENGTH: usize = FILE.len();
    const VALUE: &str = in_sync::<LENGTH>(FILE);

    println!("{:?}", VALUE);
}

pub const fn in_sync<const N: usize>(file: &str) -> &str {
    if N != file.len() {
        panic!("{}", file);
    }
    // create a [u8; N] and fill it with the chars or something similar...
    file
}

```

I expected no panic, because `N` is the length of `FILE`.
Instead, the function is evaluated with the length of the relative file name as `N` and the complete file name as `file`.

Without the `panic!` `Value` is the relative name in the compiled binary.

If the function is not async, the problem does not occur.
If the function is not a dependency, the problem does not occur.

The complete reproduction: <https://github.com/antonWetzel/locate_what>

### Meta

`rustc --version --verbose`:
```
rustc 1.91.0 (f8297e351 2025-10-28)
binary: rustc
commit-hash: f8297e351a40c1439a467bbbb6879088047f50b3
commit-date: 2025-10-28
host: aarch64-apple-darwin
release: 1.91.0
LLVM version: 21.1.2
```

`rustc +nightly --version --verbose`:
```
rustc 1.93.0-nightly (d5419f1e9 2025-10-30)
binary: rustc
commit-hash: d5419f1e97b90741d51841f800d3c697c662567d
commit-date: 2025-10-30
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.3
```

### PR DESCRIPTION
**Pull request by Urgau**
This PR overhauls the way we handle filenames in the compiler and `rmeta` in order to achieve achieve cross-compiler consistency (ie. having the same path no matter if the filename was created in the current compiler session or is coming from `rmeta`).

This is required as some parts of the compiler rely on consistent paths for the soundness of generated code (see rust-lang/rust#148328).

In order to achieved consistency multiple steps are being taken by this PR:
 - by making `RealFileName` immutable
 - by only having `SourceMap::to_real_filename` create `RealFileName`
   - currently `RealFileName` can be created from any `Path` and are remapped afterwards, which creates consistency issue
 - by also making `RealFileName` holds it's working directory, embeddable name and the remapped scopes
   - this removes the need for a `Session`, to know the current(!) scopes and cwd, which is invalid as they may not be equal to the scopes used when creating the filename

In order for `SourceMap::to_real_filename` to know which scopes to apply `FilePathMapping` now takes the current remapping scopes to apply, which makes `FileNameDisplayPreference` and company useless and are removed.

This PR is split-up in multiple commits (unfortunately not atomic), but should help review the changes.

Unblocks https://github.com/rust-lang/rust/pull/147611
Fixes https://github.com/rust-lang/rust/issues/148328

cc @RalfJung @oli-obk 
r? @davidtwco

### CODE REVIEW

File: compiler/rustc_session/src/options.rs [hunk 1]
```diff
@@ -491,8 +491,6 @@ top_level_options!(
 
         pretty: Option<PpMode> [UNTRACKED],
 
-        /// The (potentially remapped) working directory
-        working_dir: RealFileName [TRACKED],
```
Comment (bjorn3) [inline compiler/rustc_session/src/options.rs:495]: Doesn't this mean the current working directory is no longer tracked by incr comp? Generated dwarf debuginfo still depends on the current working directory.

Comment (Urgau) [reply compiler/rustc_session/src/options.rs:495]: Good point. We still want to track the current working directory in incr comp.

I've added it back.

One thing I'm wondering is if we need to track the remapped working directory in addition to the local working directory? Creating the remapped working directory is quite awkward and I'm not sure that's even useful.

Comment (bjorn3) [reply compiler/rustc_session/src/options.rs:495]: The inputs to the remapping are already tracked, right? Together with the tracked local working directory, that should make tracking the remapped working directory unnecessary.

Comment (Urgau) [reply compiler/rustc_session/src/options.rs:495]: Yes, they are already tracked in `Config::remap_path_prefix` and `UnstableOptions::remap_path_scopes`.

I will therefor remove the unnecessary remapping.

Comment (Urgau) [reply compiler/rustc_session/src/options.rs:495]: Turns out it's not unnecessary. [`reproducable-build`](https://github.com/rust-lang/rust/blob/ba86c0460b0233319e01fd789a42a7276eade805/tests/run-make/reproducible-build/rmake.rs#L230-L236) asserts that two rlib that remap their cwd to the same prefix and invoked from different working directory produce the same rlib.

Reverted to the previous state of tracking the maybe-remapped working directory.

File: src/tools/rustfmt/src/config/file_lines.rs [hunk 2]
```diff
@@ -28,7 +28,13 @@ pub enum FileName {
 impl From<rustc_span::FileName> for FileName {
     fn from(name: rustc_span::FileName) -> FileName {
         match name {
-            rustc_span::FileName::Real(rustc_span::RealFileName::LocalPath(p)) => FileName::Real(p),
+            rustc_span::FileName::Real(real) => {
+                if let Some(p) = real.into_local_path() {
+                    FileName::Real(p)
+                } else {
+                    unreachable!()
```
Comment (ytmimi) [inline src/tools/rustfmt/src/config/file_lines.rs:37]: Could you leave a comment here explaining why this is `unreachable!()`.

Comment (Urgau) [reply src/tools/rustfmt/src/config/file_lines.rs:37]: Sure, done.

**Review by davidtwco — APPROVED** [review]
LGTM

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149709/a371038013f4f3e3f1d4fdcacfaa02c3252a518b..06ff58da2cae5bda2e82f6e4d927f34b5096ff77)*

**Review by Shopgra702e — APPROVED** [review]
