### PR TITLE
Fix erroneous error note when using field after move

### LINKED ISSUE #51512: Erroneous error note for using field after move with NLL enabled
Hi, I noticed that the error for the following code:
```rust
#![feature(nll)]
fn main() {
    let range = 0 .. 1;
    let r = range;
    let x = range.start;
}
```
is this:
```
error[E0382]: use of moved value: `range.start`
 --> src/main.rs:5:13
  |
4 |     let r = range;
  |             ----- value moved here
5 |     let x = range.start;
  |             ^^^^^^^^^^^ value used here after move
  |
  = note: move occurs because `range.start` has type `i32`, which does not implement the `Copy` 
```
Notice the weird error note.

Without NLL enabled, the error becomes the more expected:
```
error[E0382]: use of moved value: `range.start`
 --> src/main.rs:4:9
  |
3 |     let r = range;
  |         - value moved here
4 |     let x = range.start;
  |         ^ value used here after move
  |
  = note: move occurs because `range` has type `std::ops::Range<i32>`, which does not implement the `Copy` trait
```
I'm running the latest nightly (as of this writing), which I got from rustup.
```
rustc 1.28.0-nightly (a805a2a5e 2018-06-10)
binary: rustc
commit-hash: a805a2a5ebba2802f432d79874e59c24e398f82a
commit-date: 2018-06-10
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```
Thanks for your time.

### PR DESCRIPTION
**Pull request by spastorino**
Closes #51512

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/util/borrowck_errors.rs [hunk 1]
```diff
@@ -356,12 +356,14 @@ pub trait BorrowckErrors<'cx>: Sized + Copy {
                                  use_span: Span,
                                  verb: &str,
                                  optional_adverb_for_moved: &str,
-                                 moved_path: &str,
+                                 moved_path: Option<String>,
                                  o: Origin)
                                  -> DiagnosticBuilder<'cx>
     {
+        let moved_path = moved_path.map(|mp| format!(": `{}`", mp)).unwrap_or("".to_owned());
```
Comment (nikomatsakis) [inline src/librustc_mir/util/borrowck_errors.rs]: do we have a test that shows the effect of this change? I don't see one... or is it that other tests regressed as a result?

Comment (spastorino) [reply src/librustc_mir/util/borrowck_errors.rs]: the stderr files changed like in https://github.com/rust-lang/rust/pull/51688/files#diff-4d3cc9be8c38f963314cf51e57d3fcbcL23

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 2]
```diff
@@ -52,15 +52,15 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+            let item_msg = match self.describe_place(place, true) {
                 Some(name) => format!("`{}`", name),
                 None => "value".to_owned(),
             };
             self.tcx
                 .cannot_act_on_uninitialized_variable(
                     span,
                     desired_action.as_noun(),
-                    &self.describe_place(place).unwrap_or("_".to_owned()),
+                    &self.describe_place(place, true).unwrap_or("_".to_owned()),
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir/borrow_check/error_reporting.rs]: Done!

File: src/librustc_mir/borrow_check/error_reporting.rs [hunk 3]
```diff
@@ -654,12 +668,26 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
     }
 }
 
+pub(super) struct IncludingDowncast(bool);
```
Comment (estebank) [inline src/librustc_mir/borrow_check/error_reporting.rs]: It's usually a bit more idiomatic to use an enum with the possible states, but this is still an improvement in readibility over a naked Boolean.

File: src/test/ui/borrowck/issue-41962.stderr [hunk 4]
```diff
@@ -49,15 +49,15 @@ LL |         if let Some(thing) = maybe {
...
 
-error[E0382]: use of moved value: `maybe.0` (Mir)
+error[E0382]: use of moved value (Mir)
   --> $DIR/issue-41962.rs:17:21
    |
 LL |         if let Some(thing) = maybe {
    |                     ^^^^^ value moved here in previous iteration of loop
    |
-   = note: move occurs because `maybe.0` has type `std::vec::Vec<bool>`, which does not implement the `Copy` trait
+   = note: move occurs because value has type `std::vec::Vec<bool>`, which does not implement the `Copy` trait
```
Comment (estebank) [inline src/test/ui/borrowck/issue-41962.stderr]: I wonder wether a small wording tweak would be warranted here:

Move occurs because the value has type

Move occurs because it has type

File: src/librustc_mir/borrow_check/error_reporting.rs (hunk 3 above)
Comment (spastorino) [reply src/librustc_mir/borrow_check/error_reporting.rs]: Yeah, I think I prefer an enum, was just following @nikomatsakis suggestion. But I'm fine with either.
