### PR TITLE
When LLVM's location discriminator value limit is exceeded, emit locations with dummy spans instead of dropping them entirely

### LINKED ISSUE #135332: Broken LLVM module: inlinable function call in a function with debug info must have a !dbg location
### Code

I tried this code foundry-rs/foundry@0cc535504a909dcee74694fa86f7faafa4cbf4bc:

```bash
git clone https://github.com/foundry-rs/foundry.git
git checkout 0cc535504a909dcee74694fa86f7faafa4cbf4bc
cargo +stable build --bin forge --profile maxperf # takes a while (>5 min)
```

I expected to see this happen: compiles like with dev or release profile

Instead, this happened (see https://github.com/foundry-rs/foundry/actions/runs/12700786553/job/35404155023#step:7:3652):
```
inlinable function call in a function with debug info must have a !dbg location
  tail call fastcc void @_ZN5alloc5alloc18handle_alloc_error17ha0547c441587f574E(i64 noundef 8, i64 noundef 128) #324
... # the last line repeated thousands of times with different arguments
rustc-LLVM ERROR: Broken module found, compilation aborted!
```

This is caused by the following config combination, as changing any of these values makes it compile again:
```toml
debug = "line-tables-only" # any value that's not "none"
lto = "fat"
```

I've also verified that the `strip` value does not affect the outcome either.

We fixed this by setting `debug = "none"`.

~~Maybe related to https://github.com/rust-lang/rust/pull/129063, which modified the function mentioned in the error?~~

---

~~I could reproduce this locally only on 1.84, not on beta or nightly, so feel free to close this if it has already been fixed.~~ Reproducible with `RUSTFLAGS="-Zverify-llvm-ir"`, see https://github.com/rust-lang/rust/issues/135332#issuecomment-2583700719.

~~Unfortunately I wasn't able to minimize this.~~
Simpler repro in https://github.com/rust-lang/rust/issues/135332#issuecomment-2584516583.

### Version it worked on

It most recently worked on: 1.83.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.84.0 (9fc6b4312 2025-01-07)
binary: rustc
commit-hash: 9fc6b43126469e3858e2fe86cafb4f0fd5068869
commit-date: 2025-01-07
host: x86_64-unknown-linux-gnu
release: 1.84.0
LLVM version: 19.1.5
```

```
rustc 1.86.0-nightly (824759493 2025-01-09)
binary: rustc
commit-hash: 824759493246ee383beb9cd5ceffa0e15deb9fa4
commit-date: 2025-01-09
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.6
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by khuey**
Dropping them fails `-Zverify-llvm-ir`.

Fixes #135332.

r? @jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks. One thing -- is it possible to conjure *a* regression test for this? I imagine that it's not going to be very feasible because the test case would have to exceed "LLVM's location discriminator value limit", but I wanted to ask in case you actually have a magical way. Based on the synthetic reproducer linked in #135332, we might be able to synthetic generate such a test case in a run-make test. What do you think?

EDIT: no that might be fragile, because it would be testing against an LLVM-internal limit which I'm not sure is guaranteed to remain the same between different LLVM versions.

**Comment by khuey** [comment]
I attempted to turn the reporter-provided testcase into a compile test but could not get it to fail. We have existing tests that exceed LLVM's limits (it's currently only 4096, so not hard to exceed). But the provided testcase also requires fat pgo and some other ingredient not present in compiletest that I failed to isolate ...

**Comment by jieyouxu** [comment]
I'll see if I can cook up a test that fails locally. If not, the change is mostly "obvious" enough.

**Comment by jieyouxu** [comment]
I was able to conjure a regerssion test based on the reproducer. It's not pretty, but notably it fails without the changes in this PR with the broken LLVM module error, and passes with the changes in this PR.

**Comment by jieyouxu** [comment]
Ok, it fails as expected on both linux and msvc.

@khuey could you cherry-pick https://github.com/jieyouxu/rust/commit/1439412ef00077562cf56e214ddc71f57f08db03, and check that if we have three commits:

1. The cherry-picked regression test commit mentioned above
2. (Current PR commit 1) The revert commit
3. (Current PR commit 2) The refix commit

That the regression test fails at (1.) against master, but passes after (3.) for you locally as well?

**Comment by khuey** [comment]
Thanks. This test does fail after commits 1 and 2 but passes after 3.

I trimmed the compiler flags a bit. Assuming you're fine with the 30 second runtime (fat lto + verify-llvm-ir = ouch) it looks good to me.

**Comment by jieyouxu** [comment]
> Thanks. This test does fail after commits 1 and 2 but passes after 3. I trimmed the compiler flags a bit.
> 
> Assuming you're fine with the 30 second runtime (fat lto + verify-llvm-ir = ouch) it looks good to me.

Yeah I noticed the test being slow which is not *great*. If we ever think this is too long, then I wouldn't mind deleting this test.

File: tests/run-make/llvm-location-discriminator-limit-dummy-span/rmake.rs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+//! We can't simply drop debuginfo location spans when LLVM's location discriminator value limit is
+//! reached. Otherwise, with `-Z verify-llvm-ir` and fat LTO, LLVM will report a broken module for
+//!
+//! ```text
+//! inlinable function call in a function with debug info must have a !dbg location
+//! ```
+
+//@ ignore-cross-compile
+//@ needs-dynamic-linking
+//@ only-nightly: requires unstable rustc flag
```
Comment (jieyouxu) [inline tests/run-make/llvm-location-discriminator-limit-dummy-span/rmake.rs:12]: Nit: I know I wrote this test, can you convert this into

```suggestion
//@ only-nightly (requires unstable rustc flag)
```

(I'd like to migrate off using colon form for comments on directives eventually, I accidentally wrote this.)

File: tests/run-make/llvm-location-discriminator-limit-dummy-span/rmake.rs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+
+#![deny(warnings)]
+
+use run_make_support::{dynamic_lib_name, rfs, rust_lib_name, rustc};
+
+// Generate a program that has a *lot*
```
Comment (jieyouxu) [inline tests/run-make/llvm-location-discriminator-limit-dummy-span/rmake.rs:18]: Suggestion:

```suggestion
// Synthesize program that requires a lot of location discriminators.
```

or some wording to that effect, or just remove this.

**Review by jieyouxu — APPROVED** [review]
Thanks, two minor nits on the test, otherwise LGTM

**Comment by khuey** [comment]
Let me know what you think of those comment changes. If that's satisfactory I'll either squash those into the test commit or squash all the commits together, your choice.

**Review by jieyouxu — APPROVED** [review]
Thanks, looks good to me. Let's just squash the commits.

**Comment by jieyouxu** [comment]
r=me after PR CI is green

@bors delegate+ rollup=never

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-01-23.5D/near/495523019). A backport PR will be authored by the release team at the end of the current development cycle. Backport labels handled by them.

Stable backport approved as well. Leaning to motivate for a dot release.

@rustbot label +beta-accepted +stable-accepted
