### PR TITLE
Fix emission of niche-filling discriminant values

### LINKED ISSUE #55606: Debuginfo changes causing ICE
A recent change to debug info (possibly https://github.com/rust-lang/rust/commit/0db7abe5b6f3cdfca736f9238689cbea8ef61c7e) seems to be causing ICEs with code like the following:

```Rust
#![feature(never_type)]
#![feature(nll)]

#[derive(Copy, Clone)]
pub struct Entity {
    private: std::num::NonZeroU32,
}

#[derive(Copy, Clone, PartialEq, Eq)]
pub struct Declaration;

impl TypeFamily for Declaration {
    type Base = Base;
    type Placeholder = !;

    fn intern_base_data(_: BaseKind<Self>) {}
}

#[derive(Copy, Clone)]
pub struct Base;

pub trait TypeFamily: Copy + 'static {
    type Base: Copy;
    type Placeholder: Copy;

    fn intern_base_data(_: BaseKind<Self>);
}

#[derive(Copy, Clone)]
pub enum BaseKind<F: TypeFamily> {
    Named(Entity),
    Placeholder(F::Placeholder),
    Error,
}
```
Compiled with: 

```
rustc src/lib.rs -C debuginfo=2  --crate-type lib 
```

*Edit*: Platform info:

```
jonathan@pop-os:~/Source/lark/components/lark-ty$ rustc --version
rustc 1.31.0-nightly (de9666f12 2018-10-31)
```

### PR DESCRIPTION
**Pull request by tromey**
Bug #55606 points out a regression introduced by #54004; namely that
an assertion can erroneously fire when a niche-filling discriminant
value is emitted.

This fixes the bug by removing the assertion, and furthermore by
arranging for the discriminant value to be masked according to the
size of the niche.  This makes handling the discriminant a bit simpler
for debuggers.

The test case is from Jonathan Turner.

Closes #55606

### CODE REVIEW

File: src/test/codegen/enum-debug-niche-2.rs [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+// min-system-llvm-version 7.0
+
+// compile-flags: -g -C no-prepopulate-passes
+
+// CHECK: {{.*}}DICompositeType{{.*}}tag: DW_TAG_variant_part,{{.*}}size: 32,{{.*}}
+// CHECK: {{.*}}DIDerivedType{{.*}}tag: DW_TAG_member,{{.*}}name: "Placeholder",{{.*}}extraData: i64 4294967295{{[,)].*}}
+// CHECK: {{.*}}DIDerivedType{{.*}}tag: DW_TAG_member,{{.*}}name: "Error",{{.*}}extraData: i64 0{{[,)].*}}
+
+#![feature(never_type)]
+#![feature(nll)]
```
Comment (matthewjasper) [inline src/test/codegen/enum-debug-niche-2.rs]: This appears to be unnecessary

File: src/librustc_codegen_llvm/debuginfo/metadata.rs [hunk 2]
```diff
@@ -1361,11 +1361,11 @@ impl EnumMemberDescriptionFactory<'ll, 'tcx> {
                         let niche_value = if i == dataful_variant {
                             None
                         } else {
-                            let niche = (i as u128)
+                            let value = (i as u128)
                                 .wrapping_sub(*niche_variants.start() as u128)
                                 .wrapping_add(niche_start);
-                            assert_eq!(niche as u64 as u128, niche);
-                            Some(niche as u64)
+                            let value = value & ((1u128 << niche.value.size(cx).bits()) - 1);
```
Comment (eddyb) [inline src/librustc_codegen_llvm/debuginfo/metadata.rs]: Removing the assert is wrong, because you're throwing away bits just below!

WIth the new change, `assert_eq!(niche as u64 as u128, niche);` should be between the truncation (`let value = value & ...;`) and the lossy cast (`value as u64`).
