### PR TITLE
Fix bad suggestion when wrong parentheses around a dyn trait

### LINKED ISSUE #114797: Diagnostics: bad suggestion when I have wrong parentheses around a dyn trait pointer type
This code
```rust
trait Trait {}

fn assert_send(ptr: *mut dyn Trait) -> *mut dyn (Trait + Send) {
    ptr as _
}
```
produces the following error
```
error: incorrect braces around trait bounds
 --> src/lib.rs:3:49
  |
3 | fn assert_send(ptr: *mut dyn Trait) -> *mut dyn (Trait + Send) {
  |                                                 ^            ^
  |
help: remove the parentheses
  |
3 - fn assert_send(ptr: *mut dyn Trait) -> *mut dyn (Trait + Send) {
3 + fn assert_send(ptr: *mut dyn Trait) -> *mut dyn  Trait + Send {
  |

error: could not compile `playground` (lib) due to previous error
```
First of all, "braces" is the wrong word here I think, AFAIK "braces" means `{...}`, but here we have parentheses.

More importantly though, if I apply the suggestion, the code still does not build! Instead it now shows a different error:
```
error: ambiguous `+` in a type
 --> src/lib.rs:3:45
  |
3 | fn assert_send(ptr: *mut dyn Trait) -> *mut dyn Trait + Send {
  |                                             ^^^^^^^^^^^^^^^^ help: use parentheses to disambiguate: `(dyn Trait + Send)`

```

The correct syntax is to write `*mut (dyn Trait + Send)`.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #114797

### CODE REVIEW

File: compiler/rustc_parse/src/errors.rs [hunk 1]
```diff
@@ -2636,21 +2636,13 @@ pub(crate) struct MissingPlusBounds {
...
-    pub sugg: IncorrectBracesTraitBoundsSugg,
-}
-
-#[derive(Subdiagnostic)]
-#[multipart_suggestion(parse_suggestion, applicability = "machine-applicable")]
-pub(crate) struct IncorrectBracesTraitBoundsSugg {
-    #[suggestion_part(code = " ")]
-    pub l: Span,
-    #[suggestion_part(code = "")]
-    pub r: Span,
```
Comment (estebank) [inline compiler/rustc_parse/src/errors.rs:2653]: Could we keep the multipart suggestion approach? Even if we suggest moving the brace to the left of the `dyn`, the "patch-style" suggestion format tends to be easier to understand for people.

**Review by estebank — APPROVED** [review]

File: compiler/rustc_parse/src/errors.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_parse/src/errors.rs]: yes, fixed it.
