### PR TITLE
Fixed ICE when using function pointer as const generic parameter

### LINKED ISSUE #137084: mgca: index out of bounds
snippet:
````rust
#![feature(min_generic_const_args)]
fn a<const b: i32>() {}
fn d(e: &String) {
    a::<d>
}

````

Version information
````
rustc 1.86.0-nightly (69fd5e405 2025-02-15)
binary: rustc
commit-hash: 69fd5e4059f8840f09f60269bcda23dcdcb77151
commit-date: 2025-02-15
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/69fd5e4059f8840f09f60269bcda23dcdcb77151/compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs#L637-L649

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.YW1oVwrZuaFw/rustc_testrunner_tmpdir_reporting.ZWaERXhXQkjK/mvce.rs:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.YW1oVwrZuaFw/rustc_testrunner_tmpdir_reporting.ZWaERXhXQkjK/mvce.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.YW1oVwrZuaFw/rustc_testrunner_tmpdir_reporting.ZWaERXhXQkjK/mvce.rs`


thread 'rustc' panicked at compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:643:20:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x76d7191db980 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb724eabc0ad78635
   1:     0x76d719a28a3c - core::fmt::write::h2ba87c04d7395c9c
   2:     0x76d71acf4ed1 - std::io::Write::write_fmt::hfa6a9da60d569ca6
   3:     0x76d7191db7e2 - std::sys::backtrace::BacktraceLock::print::h4ab0db3d989d552e
   4:     0x76d7191ddc62 - std::panicking::default_hook::{{closure}}::h3f0eed1f3665de82
   5:     0x76d7191ddaea - std::panicking::default_hook::h179f8301c7da8cf4
   6:     0x76d71833d989 - std[b8741c4e06d6af8f]::panicking::update_hook::<alloc[5bb95d137f7b141e]::boxed::Box<rustc_driver_impl[bc34f49570369c15]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x76d7191de7e3 - std::panicking::rust_panic_with_hook::h86cd07aec2e613c5
   8:     0x76d7191de4da - std::panicking::begin_panic_handler::{{closure}}::he2e747a6c54051c6
   9:     0x76d7191dbe59 - std::sys::backtrace::__rust_end_short_backtrace::h0141671d10fc3772
  10:     0x76d7191de19d - rust_begin_unwind
  11:     0x76d715e3d8e0 - core::panicking::panic_fmt::h5eb235fb4ae88e73
  12:     0x76d717a04eb9 - core::panicking::panic_bounds_check::h63f9f738529401d8
  13:     0x76d71852c16d - rustc_hir_analysis[59042490e38607df]::hir_ty_lowering::generics::check_generic_arg_count
  14:     0x76d7185179c6 - <dyn rustc_hir_analysis[59042490e38607df]::hir_ty_lowering::HirTyLowerer>::lower_generic_args_of_path_segment
  15:     0x76d71b31a591 - <dyn rustc_hir_analysis[59042490e38607df]::hir_ty_lowering::HirTyLowerer>::lower_const_arg.cold
  16:     0x76d71a3623a1 - <<rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::instantiate_value_path::CtorGenericArgsCtxt as rustc_hir_analysis[59042490e38607df]::hir_ty_lowering::GenericArgsLowerer>::provided_kind
  17:     0x76d719f707b3 - <rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::instantiate_value_path
  18:     0x76d719f679ad - <rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::check_expr_path
  19:     0x76d71a6526a6 - <rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  20:     0x76d71a64d557 - <rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::check_expr_block
  21:     0x76d71a6550e7 - <rustc_hir_typeck[65fba9be917441b7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:     0x76d719f34a9d - rustc_hir_typeck[65fba9be917441b7]::check::check_fn
  23:     0x76d719f3d27d - rustc_hir_typeck[65fba9be917441b7]::typeck_with_inspect::{closure#0}
  24:     0x76d719f3b28c - rustc_query_impl[e5659b33053300]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e5659b33053300]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0d5fddc3318c322]::query::erase::Erased<[u8; 8usize]>>
  25:     0x76d719e2d057 - rustc_query_system[d0cce9770b6d6e67]::query::plumbing::try_execute_query::<rustc_query_impl[e5659b33053300]::DynamicConfig<rustc_data_structures[e5f998b15358e4fa]::vec_cache::VecCache<rustc_span[bb9bdc9d21462a2e]::def_id::LocalDefId, rustc_middle[f0d5fddc3318c322]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[d0cce9770b6d6e67]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[e5659b33053300]::plumbing::QueryCtxt, false>
  26:     0x76d719e2c09f - rustc_query_impl[e5659b33053300]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  27:     0x76d719e2bd59 - <rustc_middle[f0d5fddc3318c322]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[59042490e38607df]::check_crate::{closure#3}>::{closure#0}
  28:     0x76d719e2b3c9 - rustc_hir_analysis[59042490e38607df]::check_crate
  29:     0x76d719e25f2b - rustc_interface[1e9e5fafa3130242]::passes::run_required_analyses
  30:     0x76d71a4abf5e - rustc_interface[1e9e5fafa3130242]::passes::analysis
  31:     0x76d71a4abf2f - rustc_query_impl[e5659b33053300]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e5659b33053300]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f0d5fddc3318c322]::query::erase::Erased<[u8; 0usize]>>
  32:     0x76d71a9796d5 - rustc_query_system[d0cce9770b6d6e67]::query::plumbing::try_execute_query::<rustc_query_impl[e5659b33053300]::DynamicConfig<rustc_query_system[d0cce9770b6d6e67]::query::caches::SingleCache<rustc_middle[f0d5fddc3318c322]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[e5659b33053300]::plumbing::QueryCtxt, false>
  33:     0x76d71a97940e - rustc_query_impl[e5659b33053300]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x76d71a8c26a9 - rustc_interface[1e9e5fafa3130242]::passes::create_and_enter_global_ctxt::<core[aa6201c117299edb]::option::Option<rustc_interface[1e9e5fafa3130242]::queries::Linker>, rustc_driver_impl[bc34f49570369c15]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  35:     0x76d71a939266 - rustc_interface[1e9e5fafa3130242]::interface::run_compiler::<(), rustc_driver_impl[bc34f49570369c15]::run_compiler::{closure#0}>::{closure#1}
  36:     0x76d71a879744 - std[b8741c4e06d6af8f]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1e9e5fafa3130242]::util::run_in_thread_with_globals<rustc_interface[1e9e5fafa3130242]::util::run_in_thread_pool_with_globals<rustc_interface[1e9e5fafa3130242]::interface::run_compiler<(), rustc_driver_impl[bc34f49570369c15]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  37:     0x76d71a879419 - <<std[b8741c4e06d6af8f]::thread::Builder>::spawn_unchecked_<rustc_interface[1e9e5fafa3130242]::util::run_in_thread_with_globals<rustc_interface[1e9e5fafa3130242]::util::run_in_thread_pool_with_globals<rustc_interface[1e9e5fafa3130242]::interface::run_compiler<(), rustc_driver_impl[bc34f49570369c15]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[aa6201c117299edb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x76d71a878bab - std::sys::pal::unix::thread::Thread::new::thread_start::h8fb7ff7d63dbc0f6
  39:     0x76d714aa339d - <unknown>
  40:     0x76d714b2849c - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (69fd5e405 2025-02-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `d`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-min_generic_const_args

### LINKED ISSUE #151186: ICE：index out of bounds: the len is 0 but the index is 0
I searched using the "F-min_generic_const_args" label and the keyword "index out of bounds", but I haven't found any similar issues so far.

### Code

```Rust
#![feature(min_generic_const_args)]
#![allow(incomplete_features)]

trait Maybe<T> {}

trait MyTrait<const F: fn() -> ()> {}

fn foo<'a>(x: &'a ()) -> &'a () { x }

impl<T> Maybe<T> for T where T: MyTrait<{ foo }> {}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.94.0-nightly (86a49fd71 2026-01-14)
binary: rustc
commit-hash: 86a49fd71fecd25b0fd20247db0ba95eeceaba28
commit-date: 2026-01-14
host: x86_64-unknown-linux-gnu
release: 1.94.0-nightly
LLVM version: 21.1.8
```

<details><summary><strong>Program Output</strong></summary>
<p>

```
thread 'rustc' (3) panicked at /rustc-dev/86a49fd71fecd25b0fd20247db0ba95eeceaba28/compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:622:20:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x7f7f78844783 - <<std[99a77fcd2881e1e7]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[270d1373c8f6a07d]::fmt::Display>::fmt
   1:     0x7f7f78e0e35c - core[270d1373c8f6a07d]::fmt::write
   2:     0x7f7f7885b186 - <std[99a77fcd2881e1e7]::sys::stdio::unix::Stderr as std[99a77fcd2881e1e7]::io::Write>::write_fmt
   3:     0x7f7f7881a688 - std[99a77fcd2881e1e7]::panicking::default_hook::{closure#0}
   4:     0x7f7f78837d83 - std[99a77fcd2881e1e7]::panicking::default_hook
   5:     0x7f7f7781b63a - std[99a77fcd2881e1e7]::panicking::update_hook::<alloc[206d51544a00c3e8]::boxed::Box<rustc_driver_impl[20c567ab0eec109e]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f7f78838062 - std[99a77fcd2881e1e7]::panicking::panic_with_hook
   7:     0x7f7f7881a748 - std[99a77fcd2881e1e7]::panicking::panic_handler::{closure#0}
   8:     0x7f7f7880ec59 - std[99a77fcd2881e1e7]::sys::backtrace::__rust_end_short_backtrace::<std[99a77fcd2881e1e7]::panicking::panic_handler::{closure#0}, !>
   9:     0x7f7f7881c21d - __rustc[e1bf4ce096729b3a]::rust_begin_unwind
  10:     0x7f7f75cc8c5c - core[270d1373c8f6a07d]::panicking::panic_fmt
  11:     0x7f7f7588bce3 - core[270d1373c8f6a07d]::panicking::panic_bounds_check
  12:     0x7f7f7965fb7d - <dyn rustc_hir_analysis[ce7edadf7d88a9df]::hir_ty_lowering::HirTyLowerer>::lower_generic_args_of_path::{closure#0}
  13:     0x7f7f779c6230 - <dyn rustc_hir_analysis[ce7edadf7d88a9df]::hir_ty_lowering::HirTyLowerer>::lower_generic_args_of_path_segment
  14:     0x7f7f7aa5e1dc - <dyn rustc_hir_analysis[ce7edadf7d88a9df]::hir_ty_lowering::HirTyLowerer>::lower_resolved_const_path.cold
  15:     0x7f7f7965e484 - <dyn rustc_hir_analysis[ce7edadf7d88a9df]::hir_ty_lowering::HirTyLowerer>::lower_generic_args_of_path::{closure#0}
  16:     0x7f7f79663da7 - <dyn rustc_hir_analysis[ce7edadf7d88a9df]::hir_ty_lowering::HirTyLowerer>::lower_poly_trait_ref
  17:     0x7f7f79709cbd - rustc_hir_analysis[ce7edadf7d88a9df]::collect::predicates_of::gather_explicit_predicates_of::{closure#0}
  18:     0x7f7f79707f00 - rustc_query_impl[5d03519af14689dc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5d03519af14689dc]::query_impl::explicit_predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 24usize]>>
  19:     0x7f7f78f6b11a - rustc_query_system[eed45c866303c690]::query::plumbing::try_execute_query::<rustc_query_impl[5d03519af14689dc]::DynamicConfig<rustc_query_system[eed45c866303c690]::query::caches::DefIdCache<rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[5d03519af14689dc]::plumbing::QueryCtxt, false>
  20:     0x7f7f78f6aa22 - rustc_query_impl[5d03519af14689dc]::query_impl::explicit_predicates_of::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7f7f78f69651 - rustc_query_impl[5d03519af14689dc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5d03519af14689dc]::query_impl::predicates_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 24usize]>>
  22:     0x7f7f78f6b139 - rustc_query_system[eed45c866303c690]::query::plumbing::try_execute_query::<rustc_query_impl[5d03519af14689dc]::DynamicConfig<rustc_query_system[eed45c866303c690]::query::caches::DefIdCache<rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[5d03519af14689dc]::plumbing::QueryCtxt, false>
  23:     0x7f7f78f6a922 - rustc_query_impl[5d03519af14689dc]::query_impl::predicates_of::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7f7f79db3985 - <rustc_trait_selection[b005c1927c673c5a]::traits::select::SelectionContext>::assemble_candidates_from_impls
  25:     0x7f7f78e872ec - <rustc_trait_selection[b005c1927c673c5a]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}
  26:     0x7f7f7a05d98f - <rustc_trait_selection[b005c1927c673c5a]::traits::select::SelectionContext>::poly_select::{closure#0}
  27:     0x7f7f79584f38 - <rustc_trait_selection[b005c1927c673c5a]::traits::fulfill::FulfillProcessor as rustc_data_structures[d4baafc84bef5099]::obligation_forest::ObligationProcessor>::process_obligation
  28:     0x7f7f78e04724 - <rustc_data_structures[d4baafc84bef5099]::obligation_forest::ObligationForest<rustc_trait_selection[b005c1927c673c5a]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[b005c1927c673c5a]::traits::fulfill::FulfillProcessor>
  29:     0x7f7f798224be - <rustc_trait_selection[b005c1927c673c5a]::traits::fulfill::FulfillmentContext<rustc_trait_selection[b005c1927c673c5a]::traits::FulfillmentError> as rustc_infer[7c27d8c17c7f8d6a]::traits::engine::TraitEngine<rustc_trait_selection[b005c1927c673c5a]::traits::FulfillmentError>>::evaluate_obligations_error_on_ambiguity
  30:     0x7f7f797ea9f8 - rustc_hir_analysis[ce7edadf7d88a9df]::check::wfcheck::check_trait
  31:     0x7f7f794d960d - rustc_hir_analysis[ce7edadf7d88a9df]::check::check::check_item_type
  32:     0x7f7f794d1d76 - rustc_hir_analysis[ce7edadf7d88a9df]::check::wfcheck::check_well_formed
  33:     0x7f7f794d1d57 - rustc_query_impl[5d03519af14689dc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5d03519af14689dc]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7f7f794d15cd - rustc_query_system[eed45c866303c690]::query::plumbing::try_execute_query::<rustc_query_impl[5d03519af14689dc]::DynamicConfig<rustc_data_structures[d4baafc84bef5099]::vec_cache::VecCache<rustc_span[75f1283d4e19c02c]::def_id::LocalDefId, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[eed45c866303c690]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[5d03519af14689dc]::plumbing::QueryCtxt, false>
  35:     0x7f7f794d10d6 - rustc_query_impl[5d03519af14689dc]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f7f794ce870 - rustc_hir_analysis[ce7edadf7d88a9df]::check::wfcheck::check_type_wf
  37:     0x7f7f794ce75d - rustc_query_impl[5d03519af14689dc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5d03519af14689dc]::query_impl::check_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7f7f79fcd588 - rustc_query_system[eed45c866303c690]::query::plumbing::try_execute_query::<rustc_query_impl[5d03519af14689dc]::DynamicConfig<rustc_query_system[eed45c866303c690]::query::caches::SingleCache<rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[5d03519af14689dc]::plumbing::QueryCtxt, false>
  39:     0x7f7f79fcd34e - rustc_query_impl[5d03519af14689dc]::query_impl::check_type_wf::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f7f79884456 - rustc_hir_analysis[ce7edadf7d88a9df]::check_crate
  41:     0x7f7f790f4c1b - rustc_interface[4190908c685cc231]::passes::analysis
  42:     0x7f7f790f4871 - rustc_query_impl[5d03519af14689dc]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5d03519af14689dc]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 0usize]>>
  43:     0x7f7f79fced66 - rustc_query_system[eed45c866303c690]::query::plumbing::try_execute_query::<rustc_query_impl[5d03519af14689dc]::DynamicConfig<rustc_query_system[eed45c866303c690]::query::caches::SingleCache<rustc_middle[2e386638a360c90c]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[5d03519af14689dc]::plumbing::QueryCtxt, false>
  44:     0x7f7f79fceac8 - rustc_query_impl[5d03519af14689dc]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7f7f7a1c0c91 - <rustc_interface[4190908c685cc231]::passes::create_and_enter_global_ctxt<core[270d1373c8f6a07d]::option::Option<rustc_interface[4190908c685cc231]::queries::Linker>, rustc_driver_impl[20c567ab0eec109e]::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core[270d1373c8f6a07d]::ops::function::FnOnce<(&rustc_session[b1a887d3ceadb98b]::session::Session, rustc_middle[2e386638a360c90c]::ty::context::CurrentGcx, alloc[206d51544a00c3e8]::sync::Arc<rustc_data_structures[d4baafc84bef5099]::jobserver::Proxy>, &std[99a77fcd2881e1e7]::sync::once_lock::OnceLock<rustc_middle[2e386638a360c90c]::ty::context::GlobalCtxt>, &rustc_data_structures[d4baafc84bef5099]::sync::worker_local::WorkerLocal<rustc_middle[2e386638a360c90c]::arena::Arena>, &rustc_data_structures[d4baafc84bef5099]::sync::worker_local::WorkerLocal<rustc_hir[a0f10157905e5583]::Arena>, rustc_driver_impl[20c567ab0eec109e]::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  46:     0x7f7f7a041715 - rustc_interface[4190908c685cc231]::interface::run_compiler::<(), rustc_driver_impl[20c567ab0eec109e]::run_compiler::{closure#0}>::{closure#1}
  47:     0x7f7f79f8d18e - std[99a77fcd2881e1e7]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4190908c685cc231]::util::run_in_thread_with_globals<rustc_interface[4190908c685cc231]::util::run_in_thread_pool_with_globals<rustc_interface[4190908c685cc231]::interface::run_compiler<(), rustc_driver_impl[20c567ab0eec109e]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  48:     0x7f7f79f8cf60 - <std[99a77fcd2881e1e7]::thread::lifecycle::spawn_unchecked<rustc_interface[4190908c685cc231]::util::run_in_thread_with_globals<rustc_interface[4190908c685cc231]::util::run_in_thread_pool_with_globals<rustc_interface[4190908c685cc231]::interface::run_compiler<(), rustc_driver_impl[20c567ab0eec109e]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[270d1373c8f6a07d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7f7f79f8ed04 - <std[99a77fcd2881e1e7]::sys::thread::unix::Thread>::new::thread_start
  50:     0x7f7f73894ac3 - <unknown>
  51:     0x7f7f739268c0 - <unknown>
  52:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/app/rustc-ice-2026-01-16T01_31_44-1.txt` to your bug report

note: rustc 1.94.0-nightly (86a49fd71 2026-01-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type bin -C linker=/opt/compiler-explorer/gcc-15.2.0/bin/gcc

query stack during panic:
#0 [explicit_predicates_of] computing explicit predicates of `<impl at <source>:11:1: 11:49>`
#1 [predicates_of] computing predicates of `<impl at <source>:11:1: 11:49>`
#2 [check_well_formed] checking that `Maybe` is well-formed
#3 [check_type_wf] checking that types are well-formed
#4 [analysis] running analysis passes on crate `example`
end of query stack
error: using function pointers as const generic parameters is forbidden
 --> <source>:7:24
  |
7 | trait MyTrait<const F: fn() -> ()> {}
  |                        ^^^^^^^^^^
  |
  = note: the only supported types are integers, `bool`, and `char`

error: aborting due to 1 previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by enthropy7**
added bounds check in prohibit_explicit_late_bound_lifetimes to prevent index out of bounds panic when args.args is empty. also regression test here to ensure function pointers in const generics produce proper error messages instead of ICE.

Fixes rust-lang/rust#151186
Fixes rust-lang/rust#137084

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs [hunk 1]
```diff
@@ -634,6 +616,10 @@ pub(crate) fn prohibit_explicit_late_bound_lifetimes(
     }
 
     if let Some(span_late) = def.has_late_bound_regions {
```
Comment (Kivooeo) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs]:
```suggestion
    if let Some(span_late) = def.has_late_bound_regions && !args.args.is_empty() {
```

seems like it could be simplified a little (just style nit, feel free to ignore)

**Comment by enthropy7** [comment]
also fixes #137084

File: tests/ui/const-generics/fn-item-as-const-arg-137084.rs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+//@ check-fail
```
Comment (fmease) [inline tests/ui/const-generics/fn-item-as-const-arg-137084.rs]:
```suggestion
```

It's the default

File: tests/ui/const-generics/ice-151186-fn-ptr-in-where-clause.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+//@ check-fail
+//
```
Comment (fmease) [inline tests/ui/const-generics/ice-151186-fn-ptr-in-where-clause.rs]:
```suggestion
```

**Comment by fmease** [comment]
> also fixes #137084

Please mention all issues in the PR description via e.g., `Fixes #NNN`, so they can be auto-closed on merge & are properly linked (useful for e.g., search queries). Read more about keywords here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

Moreover, please remove the `#NNN` from the title, it's not descriptive & nobody can click on it either.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs (hunk 1 above)
Comment (enthropy7) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs]: thanks for your suggestion! implemented it

**Comment by BoxyUwU** [comment]
r? BoxyUwU

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs [hunk 4]
```diff
@@ -615,7 +615,9 @@ pub(crate) fn prohibit_explicit_late_bound_lifetimes(
         return ExplicitLateBound::No;
     }
 
-    if let Some(span_late) = def.has_late_bound_regions {
+    if let Some(span_late) = def.has_late_bound_regions
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:613]: this function is somewhat confusing to me :thinking: 

Can you try doing two things for me:
1. remove the `infer_lifetimes` case above, it seems unnecessary if we only emit an error/fcw if there's explicit arguments given
2. use `args.has_lifetime_params()` instead of `!args.args.is_empty()`, I think this is closer to the logic we want, especially for cases like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=68e940981358cc99ffb8515cf293ad0a) where there *are* arguments but they're not lifetimes

I think both of these together would make it a lot easier to read this fn :sweat_smile:

Comment (enthropy7) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs:613]: hi again! thanks for the review! implemented all of your suggestions, now waiting for CI check, tests passed, fn now looking better and more consistent :3

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs [hunk 5]
```diff
@@ -609,17 +609,19 @@ pub(crate) fn prohibit_explicit_late_bound_lifetimes(
...
         let msg = "cannot specify lifetime arguments explicitly \
                        if late bound lifetime parameters are present";
         let note = "the late bound lifetime parameter is introduced here";
-        let span = args.args[0].span();
+        let Some(first_lifetime_arg) =
+            args.args.iter().find(|arg| matches!(arg, GenericArg::Lifetime(_)))
+        else {
+            return ExplicitLateBound::No;
+        };
+        let span = first_lifetime_arg.span();
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs]: why change this? if args isnt empty then `args.args[0]` should work fine

Comment (enthropy7) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/generics.rs]: sorry, overcomplicated it, was a little bit confused

**Review by BoxyUwU — APPROVED** [review]
Thanks, looks good to me. Can you squash all your commits into one? I'll r+ it afterwards

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151219/158ae9ee50d82b415fc9479575bc33f8985f4f1a..ce65294743adc40c4c52f5e408da19ae7526cc0f)*
