### PR TITLE
fix type of const params in associated types.

### LINKED ISSUE #66906: ICE with const generics: broken MIR
```rust
#![feature(const_generics)]

pub struct Tuple;

pub trait ConstInput<const I: usize> {
    type Input;
}

impl Tuple {
    fn const_index<const I: usize>(_: <Self as ConstInput<I>>::Input)
    where
        Self: ConstInput<I>
    {}
}
```
results in an ICE ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cfdf4e69d4c60473945655d6c7203a2f)):

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:347:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1024
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:190
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:207
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::real_drop_in_place
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  16: core::ptr::real_drop_in_place
  17: rustc_interface::interface::run_compiler_in_existing_thread_pool
  18: std::thread::local::LocalKey<T>::with
  19: scoped_tls::ScopedKey<T>::set
  20: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (25d8a9494 2019-11-29) running on x86_64-unknown-linux-gnu
```

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/66906#issuecomment-601774195).

### LINKED ISSUE #70167: ICE with Const Generics cast of self in supertrait list
I was writing some generic code over vectors using the under-construction feature of const generics, and had a circular chain of super-traits that required me to cast the Self type to the trait as can be seen in the `Div` supertrait requirement. I believe that is causing the MIR error.
I think this may be related to #66906 but it is subtly different so I'm putting the issue up regardless.

### Code

```
#![feature(const_generics)]
use std::ops::Div;
use num::Float;

/// Abstract vector over some finite field
pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  type Field: Float;
  fn cons(vs: [Self::Field; N]) -> Self { todo!() }
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3856486297085a463f98c2fc9f9a99c6

### Meta

`rustc --version --verbose`:
I updated my rust version on nightly right before I ran this so hopefully it is up to date:
```
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-apple-darwin
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
... Warnings Elided for convenience...

warning: Error finalizing incremental compilation session directory `/Users/julianknodt/Desktop/programming/projects/rustjects/gfx/target/debug/incremental/ray_weekend-1jydezk8mz1tf/s-flpmnsfnok-1ritjvd-working`: No such file or directory (os error 2)

error: internal compiler error: mir_const_qualif: MIR had errors
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: PromoteTemps: MIR had errors
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: broken MIR in DefId(0:2682 ~ ray_weekend[6635]::vec[0]::Vector[0]::{{constant}}[0]) ("return type"): bad type [type error]
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: broken MIR in DefId(0:2682 ~ ray_weekend[6635]::vec[0]::Vector[0]::{{constant}}[0]) (LocalDecl { mutability: Mut, local_info: Other, internal: false, is_block_tail: None, ty: [type error], user_ty: UserTypeProjections { contents: [] }, source_info: SourceInfo { span: src/vec.rs:8:55: 8:56, scope: scope[0] } }): bad type [type error]
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:360:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `ray_weekend`.

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
...Warnings elided for clarity...

warning: Error finalizing incremental compilation session directory `/Users/julianknodt/Desktop/programming/projects/rustjects/gfx/target/debug/incremental/ray_weekend-1jydezk8mz1tf/s-flpmrtevdl-1q49gen-working`: No such file or directory (os error 2)

error: internal compiler error: mir_const_qualif: MIR had errors
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: PromoteTemps: MIR had errors
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: broken MIR in DefId(0:2682 ~ ray_weekend[6635]::vec[0]::Vector[0]::{{constant}}[0]) ("return type"): bad type [type error]
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

error: internal compiler error: broken MIR in DefId(0:2682 ~ ray_weekend[6635]::vec[0]::Vector[0]::{{constant}}[0]) (LocalDecl { mutability: Mut, local_info: Other, internal: false, is_block_tail: None, ty: [type error], user_ty: UserTypeProjections { contents: [] }, source_info: SourceInfo { span: src/vec.rs:8:55: 8:56, scope: scope[0] } }): bad type [type error]
 --> src/vec.rs:8:55
  |
8 | pub trait Vector<const N: usize>: Div<<Self as Vector<N>>::Field, Output = Self> + Copy {
  |                                                       ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:360:17
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `ray_weekend`.

To learn more, run the command again with --verbose.
```

</p>
</details>

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70167#issuecomment-601753044).

### PR DESCRIPTION
**Pull request by lcnr**
fixes #66906
fixes #70167 

r? @eddyb

### CODE REVIEW

File: src/librustc_typeck/collect/type_of.rs [hunk 1]
```diff
@@ -256,15 +256,18 @@ pub(super) fn type_of(tcx: TyCtxt<'_>, def_id: DefId) -> Ty<'_> {
                         // figure out which generic parameter it corresponds to and return
                         // the relevant type.
                         let generics = match path.res {
-                            Res::Def(DefKind::Ctor(..), def_id) => {
+                            Res::Def(DefKind::Ctor(..), def_id)
```
Comment (Centril) [inline src/librustc_typeck/collect/type_of.rs]: (We can use nested or-patterns now, for future reference.)
