### PR TITLE
Fix unindent in doc comments

### LINKED ISSUE #70732: doc attribute removes whitespace
I tried this code:

```rust
/// You are supposed to call it like this
///
/// # Example
///
/// ```
/// let example = Example::new()
///     .first("hello")
#[cfg_attr(not(feature = "one"), doc = "     .second(\"hello\")\n")]
///     .third("hello")
///     .build();
/// ```
pub struct Example {}

fn main() {}
```

with `cargo doc --open`

I expected to see this:

Screenshot_20200403_123723

Instead, this happened:

Screenshot_20200403_123648

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (564758c4c 2020-03-08)
binary: rustc
commit-hash: 564758c4c329e89722454dd2fbb35f1ac0b8b47c
commit-date: 2020-03-08
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

running `cargo expand` over the code gives me

```rust
#![feature(prelude_import)]
#[prelude_import]                                                                                                                                                                             
use std::prelude::v1::*;                                                                                                                                                                      
#[macro_use]                                                                                                                                                                                  
extern crate std;                                                                                                                                                                             
/// You are supposed to call it like this
///                                                                                                                                                                                           
/// # Example                                                                                                                                                                                 
///                                                                                                                                                                                           
/// ```                                                                                                                                                                                       
/// let example = Example::new()                                                                                                                                                              
///     .first("hello")
///     .second("hello")
///     .third("hello")
///     .build();
/// ```
pub struct Example {}
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #70732

r? @jyn514

### CODE REVIEW

**Comment by Nemo157** [comment]
How come this doesn't break <https://github.com/QuietMisdreavus/rust/blob/master/src/test/rustdoc/issue-42760.rs>, which was explicitly testing for the old behaviour?

File: src/librustdoc/passes/unindent_comments.rs [hunk 1]
```diff
@@ -35,65 +34,72 @@ impl clean::Attributes {
...
+                });
+                cmp::min(min_indent, whitespace)
+            }
+        })
+    }).collect::<Vec<_>>();
+    if min_indents.is_empty() {
+        return;
+    }
+    min_indents.sort_unstable();
+    let min_indent = min_indents[0];
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs]: Why did all this have to change? From what I see you don't use `min_indents` after this.

File: src/librustdoc/passes/unindent_comments.rs [hunk 2]
```diff
@@ -35,65 +34,72 @@ impl clean::Attributes {
...
+
+    for (index, fragment) in docs.iter_mut().enumerate() {
+        let lines = fragment.doc.lines().collect::<Vec<&str>>();
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:84]:
```suggestion
        let lines: Vec<_> = fragment.doc.lines().collect();
```

File: src/test/rustdoc-ui/intra-links-warning.stderr [hunk 3]
```diff
@@ -96,8 +96,8 @@ LL | | /// [error]
    |
    = note: the link appears in this line:
            
-           [error]
-            ^^^^^
+            [error]
+             ^^^^^
```
Comment (jyn514) [inline src/test/rustdoc-ui/intra-links-warning.stderr:100]: Is this change intentional? It looks like this is no longer stripping leading whitespace, which doesn't seem right.

File: src/librustdoc/passes/unindent_comments.rs [hunk 4]
```diff
@@ -35,65 +34,72 @@ impl clean::Attributes {
...
-    } else {
-        s.to_string()
+    for (index, fragment) in docs.iter_mut().enumerate() {
+        let lines = fragment.doc.lines().collect::<Vec<&str>>();
+
+        if !lines.is_empty() {
+            let mut unindented =
+                if index == 0 { vec![lines[0].trim_start().to_string()] } else { vec![] };
+            unindented.extend_from_slice(
+                &lines[if index == 0 { 1 } else { 0 }..]
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:90]: I don't understand what this is doing, can you add a comment?

**Comment by GuillaumeGomez** [comment]
This test only check that there is a title, not that the indent isn't broken as far as I can tell?

File: src/librustdoc/passes/unindent_comments.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs]: I needed to get the `min_indent` based on all the doc fragments, not just on one.

File: src/test/rustdoc-ui/intra-links-warning.stderr (hunk 3 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/intra-links-warning.stderr:100]: Hum... It should definitely take into account the kind of the doc fragment. Good point!

File: src/librustdoc/passes/unindent_comments.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs:90]: Actually, I think that most of this code can be simplified now.

**Comment by GuillaumeGomez** [comment]
@Nemo157 Well, for me it seems like it should work because sugared doc comments should be handled a bit differently than the others (they need to have one extra whitespace after all).

@jyn514 Thanks to your remarks, I greatly improved the code. :)

File: src/librustdoc/passes/unindent_comments.rs [hunk 5]
```diff
@@ -35,52 +34,64 @@ impl clean::Attributes {
...
                 }
-            });
-            cmp::min(min_indent, whitespace)
-        }
-    });
+            }) + if fragment.kind == DocFragmentKind::SugaredDoc { 0 } else { 1 }
+        })
+        .collect::<Vec<_>>();
+    min_indents.sort_unstable();
+    let min_indent = min_indents[0];
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:81]: I was suggesting something like this:
```suggestion
        })
        .min();
```

File: src/librustdoc/passes/unindent_comments.rs [hunk 6]
```diff
@@ -35,52 +34,64 @@ impl clean::Attributes {
...
+        let lines = fragment.doc.lines().collect::<Vec<&str>>();
+
+        if !lines.is_empty() {
+            let min_indent = if fragment.kind == DocFragmentKind::SugaredDoc {
+                min_indent
+            } else if min_indent > 0 {
+                min_indent - 1
+            } else {
+                min_indent
+            };
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:93]:
```suggestion
            let min_indent = if fragment.kind != DocFragmentKind::SugaredDoc && min_indent > 0 {
                min_indent - 1
            } else {
                min_indent
            };
```

File: src/librustdoc/passes/unindent_comments.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs:81]: :o That's awesome!

**Comment by Nemo157** [comment]
> @Nemo157 Well, for me it seems like it should work because sugared doc comments should be handled a bit differently than the others (they need to have one extra whitespace after all).

But they don't, you can have 
```rust
///# Documentation
///
///Without leading whitespace
```
just fine, it's just convention to have a space between the doc-comment marker and the docs.

**Comment by GuillaumeGomez** [comment]
Well, glad I treated that correctly then. Thanks for the extra information! :)

**Comment by GuillaumeGomez** [comment]
Hum, actually I might need to make a small update in the code. :3

File: src/librustdoc/passes/unindent_comments.rs [hunk 7]
```diff
@@ -35,65 +34,69 @@ impl clean::Attributes {
...
+                    line.chars().all(|char| {
+                        // Compare against either space or tab, ignoring whether they
+                        // are mixed or not
+                        if char == ' ' || char == '\t' {
+                            whitespace += 1;
+                            true
+                        } else {
+                            false
+                        }
+                    });
```
Comment (pickfire) [inline src/librustdoc/passes/unindent_comments.rs:71]: We could probably simplify this a bit.
```suggestion
                    // Compare against either space or tab, ignoring whether they are
                    // mixed or not
                    let whitespace = line.chars().take_while(|c| c == ' ' || c == '\t').count();
```

Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs:71]: :+1:

File: src/librustdoc/passes/unindent_comments/tests.rs [hunk 8]
```diff
@@ -1,26 +1,40 @@
...
+        line: 0,
+        span: DUMMY_SP,
+        parent_module: None,
+        doc: s.to_string(),
+        kind: DocFragmentKind::SugaredDoc,
+    }]
+}
+
+// We use a macro to keep the line in case of a test failure.
+macro_rules! run_test {
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments/tests.rs:15]: Can you make this a function with `track_caller` instead?

File: src/test/rustdoc/unindent.rs [hunk 9]
```diff
@@ -0,0 +1,27 @@
+#![feature(no_core)]
+
+#![crate_name = "foo"]
+#![no_std]
+#![no_core]
```
Comment (jyn514) [inline src/test/rustdoc/unindent.rs:5]: Any reason to make this no_std and no_core?

Comment (GuillaumeGomez) [reply src/test/rustdoc/unindent.rs:5]: Woups, it was just to have less logs when running my tests. I removed them.

File: src/librustdoc/passes/unindent_comments.rs [hunk 10]
```diff
@@ -35,65 +34,85 @@ impl clean::Attributes {
...
+
+        if !lines.is_empty() {
+            let min_indent = if fragment.kind != DocFragmentKind::SugaredDoc && min_indent > 0 {
+                min_indent - add
+            } else {
+                min_indent
+            };
+
+            let mut iter = lines.iter();
+            let mut result = if !first_ignored {
```
Comment (pickfire) [inline src/librustdoc/passes/unindent_comments.rs:97]: What is `result`?

File: src/librustdoc/passes/unindent_comments.rs [hunk 11]
```diff
@@ -35,65 +34,85 @@ impl clean::Attributes {
...
+                &iter
+                    .map(|&line| {
+                        if line.chars().all(|c| c.is_whitespace()) {
+                            line.to_string()
+                        } else {
+                            assert!(line.len() >= min_indent);
+                            line[min_indent..].to_string()
+                        }
+                    })
+                    .collect::<Vec<_>>(),
```
Comment (pickfire) [inline src/librustdoc/passes/unindent_comments.rs:113]: I believe this could be separated into it's own line already, at least to make it easier to understand what was being extended.

File: src/librustdoc/passes/unindent_comments.rs [hunk 12]
```diff
@@ -35,65 +34,85 @@ impl clean::Attributes {
...
-                    true
+    let add = if !docs.windows(2).all(|arr| arr[0].kind == arr[1].kind)
+        && docs.iter().any(|d| d.kind == DocFragmentKind::SugaredDoc)
+    {
+        // In case we have a mix of sugared doc comments and "raw" ones, we want the sugared one to
+        // "decide" how much the minimum indent will be.
+        1
+    } else {
+        0
+    };
```
Comment (pickfire) [inline src/librustdoc/passes/unindent_comments.rs:48]:
```suggestion
    let sugared_doc = if !docs.windows(2).all(|arr| arr[0].kind == arr[1].kind)
        && docs.iter().any(|d| d.kind == DocFragmentKind::SugaredDoc);
    // In case we have a mix of sugared doc comments and "raw" ones, we want the sugared one to
    // "decide" how much the minimum indent will be.
    let add = if sugared_doc { 1 } else { 0 };
```

**Comment by jyn514** [comment]
We're discussing this [on discord](https://discord.com/channels/442252698964721669/459149231702278154/771053580656312320), but either way the following test cases we came up with should be added:

```rust
///no whitespace
#[doc = " lol"]
```
```
///    4 whitespaces!
#[doc = "something"]
```

Additionally, note that the fixed version of https://github.com/rust-lang/rust/issues/70732 in the test case uses *4* spaces instead of 5, which differs from the original bug report. IMO this seems reasonable to match https://github.com/rust-lang/rust/issues/42760.

There should also be test cases for `doc(include = ...)`.

**Comment by GuillaumeGomez** [comment]
So I changed a bit how the unindent is handled. For example:

```rust
#[doc = "hello
         second"]
```

Before, we didn't take into account the first line that in this case, we could align the doc based on the next lines indent. It was very misleading and not that great as I discovered while updating this PR. I always assumed it was supposed to be:

```rust
#[doc = "hello
second"]
```

I definitely think it's better this way.

Apart from that change, I also added comments and extended tests to add doc includes.

**Comment by jyn514** [comment]
```
#[doc = "hello
second"]
```
This does not look right. If that's really what the user meant, they can use
```
"hello \
    second"
```
which the lexer will handle without rustdoc having to get involved. I think rustdoc is already trying to be too magic here and we shouldn't special-case things any more than they already are.

File: src/librustdoc/passes/unindent_comments.rs [hunk 13]
```diff
@@ -35,52 +34,69 @@ impl clean::Attributes {
...
+    // we need to take into account the fact that the minimum indent minus one (to take this
+    // whitespace into account).
+    //
+    // For example:
+    //
+    // /// hello!
+    // #[doc = "another"]
+    //
+    // In this case, you want "hello! another" and not "hello!  another".
+    let add = if !docs.windows(2).all(|arr| arr[0].kind == arr[1].kind)
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:49]: nit: I think this is easier to read if you expand the boolean logic. Plus it allows short-circuiting.
```suggestion
    let add = if docs.windows(2).any(|arr| arr[0].kind != arr[1].kind)
```

File: src/librustdoc/passes/unindent_comments.rs [hunk 14]
```diff
@@ -35,52 +34,69 @@ impl clean::Attributes {
...
+    // `add` is used in case the most common sugared doc syntax is used ("/// "). The other
+    // fragments kind's lines are never starting with a whitespace unless they are using some
+    // markdown formatting requiring it. Therefore, if the doc block have a mix between the two,
+    // we need to take into account the fact that the minimum indent minus one (to take this
+    // whitespace into account).
+    //
+    // For example:
+    //
+    // /// hello!
+    // #[doc = "another"]
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:46]: This is a really great comment :) do you have the same example in a test?

File: src/librustdoc/passes/unindent_comments.rs [hunk 15]
```diff
@@ -35,52 +34,69 @@ impl clean::Attributes {
...
+            })
+        })
+        .min()
+    {
+        Some(x) => x,
+        None => return,
+    };
+
+    for fragment in docs {
+        let lines: Vec<_> = fragment.doc.lines().collect();
```
Comment (jyn514) [inline src/librustdoc/passes/unindent_comments.rs:90]: nit: this seems a little inefficient, I think you only need the collect for the `is_empty()` call? Instead you could check `fragment.doc.trim().is_empty()` and use `fragment.doc.lines()` for the loop.

File: src/test/rustdoc/unindent.rs [hunk 16]
```diff
@@ -21,3 +23,42 @@ pub struct Example;
...
+
+// @has foo/struct.J.html
+// @matches - '//div[@class="docblock"]/p' '(?m)a\nno whitespace\nJust some text.\Z'
+///a
+///no whitespace
+#[doc(include = "unindent.md")]
+pub struct J;
+
+// @has foo/struct.K.html
+// @matches - '//pre[@class="rust rust-example-rendered"]' '(?m)4 whitespaces!\Z'
```
Comment (jyn514) [inline src/test/rustdoc/unindent.rs:58]: What does `?m` do? Where are the other lines from the doc-comment?

**Review by jyn514 — COMMENTED** [review]
I like the current behavior and code :) just a few comments on the tests.

**Comment by jyn514** [comment]
> This does not look right.

It turns out I was confused - Guillaume was describing the _old_ behavior, not what rustdoc does after this PR.

File: src/test/rustdoc/unindent.rs (hunk 16 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/unindent.rs:58]: `(?m)` checks that it's the beginning of the line. Also, in here I test the content of a codeblock, which is why you don't see the rest. It's easier to check the whitespace handling. :)

File: src/librustdoc/passes/unindent_comments.rs (hunk 15 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs:90]: We want to keep the empty lines, they're important in the markdown. :)

File: src/librustdoc/passes/unindent_comments.rs (hunk 14 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/unindent_comments.rs:46]: Yep! It's actually the first one I added (even though it doesn't look exactly the same). For example: https://github.com/rust-lang/rust/pull/78400/files#diff-b8ef7a3193cdebf8d2bf582e37fa1689711ed17ef19f6324e25d640f5a796dc0R11

File: src/test/rustdoc/unindent.rs [hunk 17]
```diff
@@ -0,0 +1,64 @@
...
+///a
+///
+///    4 whitespaces!
```
Comment (pickfire) [inline src/test/rustdoc/unindent.rs:61]: Just wondering for the other html sanitization patch, can we do something like a diagram?
```
///    a --> b
```
I feel lazy to go back and check which patch is it.

Comment (GuillaumeGomez) [reply src/test/rustdoc/unindent.rs:61]: You can have HTML in your markdown already, this PR doesn't change anything about the rendering part. :)

File: src/librustdoc/passes/unindent_comments.rs (hunk 15 above)
Comment (jyn514) [reply src/librustdoc/passes/unindent_comments.rs:90]: Right, I'm saying you can keep the empty lines without having to collect into a vec, like this:
```suggestion
if fragment.doc.lines().count() != 0 {
    fragment.doc = fragment.doc.lines().map(...);
```

**Comment by jyn514** [comment]
r=me with CI passing. Thanks for adding all the tests and comments, this looks a lot better :)

**Comment by GuillaumeGomez** [comment]
Fetch error, let's retry!

@bors: retry

**Comment by jyn514** [comment]
If this fails because of another zlib error, let's avoid retrying, `@ehuss` is working on a fix for the underlying issue in https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/pinging.20for.20zlib.20error.

**Comment by GuillaumeGomez** [comment]
Seeing that other PRs seem to pass, let's give it another try.

@bors: retry
