### PR TITLE
Structured `use` suggestion on privacy error

### LINKED ISSUE #42909: trying to import a `use` statement should not talk of privacy
```rust
fn main() {
    use foo::mem;
}

pub mod foo {
    use std::mem;
}
```

gives the error:

```
error: module `mem` is private
 --> <anon>:2:9
  |
2 |     use foo::mem;
  |         ^^^^^^^^

error: aborting due to previous error
```

However, really, we don't consider `use std::mem` to be introducing a module, so it's confusing when we say that it's private. This gives off the impression that we typed the correct path, but the library author neglected to make it public. 

We should instead give an error that the module/type/etc does not exist, but perhaps note that there is a `use` statement that could be made `pub use` if the error is from the same crate.

### PR DESCRIPTION
**Pull request by estebank**
When encoutering a privacy error on an item through a re-export that is accessible in an alternative path, provide a structured suggestion with that path.

```
error[E0603]: module import `mem` is private
  --> $DIR/private-std-reexport-suggest-public.rs:4:14
   |
LL |     use foo::mem;
   |              ^^^ private module import
   |
note: the module import `mem` is defined here...
  --> $DIR/private-std-reexport-suggest-public.rs:8:9
   |
LL |     use std::mem;
   |         ^^^^^^^^
note: ...and refers to the module `mem` which is defined here
  --> $SRC_DIR/std/src/lib.rs:LL:COL
   |
   = note: you could import this
help: import `mem` through the re-export
   |
LL |     use std::mem;
   |         ~~~~~~~~
```

Fix #42909.

### CODE REVIEW

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 1]
```diff
@@ -1749,10 +1751,51 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             }
         }
 
+        let mut sugg_paths = vec![];
```
Comment (b-naber) [inline compiler/rustc_resolve/src/diagnostics.rs:1754]: `report_privacy_error` is more than 200 lines long after this change ^^ and i find it really difficult to read because all the path collection logic is all over the place. I think it would be better if we would re-structure some of the logic into functions. But it's not too important to me since this is only diagnostics code, so up to you whether you want to change this or not.

**Review by b-naber — APPROVED** [review]
r=me with or without addressing the nit.

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_resolve/src/diagnostics.rs:1754]: Let's split this method in a follow up PR.
