### PR TITLE
layout: handle rigid aliases without params

### LINKED ISSUE #151791: Regression in 1.93.0 `the type <XYZ as Archive>::Archived has an unknown layout`
### Code

I tried the following in a new cargo project. This is minimized from a real codebase.

```toml
[package]
name = "broken-nightly"
version = "0.1.0"
edition = "2024"

[dependencies]
cynic-codegen = { version = "3.12.0", features = [ "rkyv" ] }

[profile.dev.package.cynic-codegen]
opt-level = 1 # only 0 doesn't cause the issue
```

I expected to see this happen: compilation to succeed.

Instead, this happened: multiple errors that are basically impossible to track down the cause of.

```
error[E0080]: the type `<With<Cow<'_, str>, AsOwned> as Archive>::Archived` has an unknown layout
 --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/mem/mod.rs:1251:26
  |
  = note: evaluation of `<schema::names::ArchivedFieldName<'_> as std::mem::SizedTypeProperties>::ALIGN` failed here

error[E0080]: the type `<std::collections::HashMap<std::string::String, schema::types::Type<'_>> as Archive>::Archived` has an unknown layout
 --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/mem/mod.rs:1251:26
  |
  = note: evaluation of `<schema::type_index::optimised::ArchivedOptimisedTypes<'_> as std::mem::SizedTypeProperties>::ALIGN` failed here

error[E0080]: the type `<schema::types::ObjectType<'_> as Archive>::Archived` has an unknown layout
 --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/mem/mod.rs:1251:26
  |
  = note: evaluation of `<schema::types::ArchivedSchemaRoots<'_> as std::mem::SizedTypeProperties>::ALIGN` failed here

error[E0080]: the type `<schema::types::ScalarType<'_> as Archive>::Archived` has an unknown layout
 --> /rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library/core/src/mem/mod.rs:1251:26
  |
  = note: evaluation of `<schema::types::ArchivedType<'_> as std::mem::SizedTypeProperties>::ALIGN` failed here

...
```

For anyone that is encountering this in the wild, updating cynic to be the latest main that uses rkyv 0.8 resolves the issue.

It would seem specifically rkyv 0.7 is causing the issue when applied to the cynic-codegen types.

### Version it worked on

It most recently worked on: 1.92.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.93.0 (254b59607 2026-01-19)
```

Running a bisection I get the nightly that introduced the bug to be nightly-2025-10-24. I am unable to get the exact commit at the moment because of GitHub rate limiting.

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by lcnr**
fixes rust-lang/rust#151791

r? types

### CODE REVIEW

File: compiler/rustc_ty_utils/src/layout.rs [hunk 1]
```diff
@@ -764,9 +764,17 @@ fn layout_of_uncached<'tcx>(
...
+            // if we've got a `T: Trait` where-bound, `T::Assoc` cannot be normalized
+            // in the current context.
+            //
+            // For some builtin traits, generic aliases can be rigid even in an empty environment,
+            // e.g. `<T as Pointee>::Metadata`.
+            //
+            // Due to trivial bounds, this can even be the case if the alias does not reference
+            // any generic parameters, e.g. a `for<'a> u32: Trait<'a>` where-bound means that
+            // `<u32 as Trait<'static>>::Assoc` is rigid.
+            let err = if ty.has_param() || !cx.typing_env.param_env.caller_bounds().is_empty() {
```
Comment (jackh726) [inline compiler/rustc_ty_utils/src/layout.rs:777]: This seems like a weird fix? Like, just because there were where clauses, doesn't mean they they were even relevant to the alias, right? Like, this would mean that `<u32 as Trait<'static>>::Assoc` would be "too generic", if there is a where clause like `where u8: Foo`, but "unknown" if there *isn't* that bound, even though that where clause seemingly makes no difference?

I'm not sure I have a better easy solution in mind. As a heuristic, we could see if there is a bound like `X: Y<...>` if the alias is `<X as Y<...>>::Z` - this is not *quite* enough, because that doesn't guarantee that it *could* be normalized even if not too-generic, but is better than a blank check.

**Review by jackh726 — CHANGES_REQUESTED** [review]

File: compiler/rustc_ty_utils/src/layout.rs
Comment (workingjubilee) [inline compiler/rustc_ty_utils/src/layout.rs:1]: Before https://github.com/rust-lang/rust/pull/147793/changes/5dfbf67f94a91cd689275ff9d6cb7753eef84990 (the commit that revealed the bug this fixes) we had this in the middle of borrowck:
```rust
            &Rvalue::NullaryOp(NullOp::SizeOf | NullOp::AlignOf, ty) => {
                let trait_ref =
                    ty::TraitRef::new(tcx, tcx.require_lang_item(LangItem::Sized, span), [ty]);

                self.prove_trait_ref(
                    trait_ref,
                    location.to_locations(),
                    ConstraintCategory::SizedBound,
                );
            }
```

Was that `.prove_trait_ref(..., ..., ConstraintCategory::SizedBound)` what was "rescuing" this code from having to think about this?

File: compiler/rustc_ty_utils/src/layout.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_ty_utils/src/layout.rs:777]: I agree, I don't care as the `else` branch is actually unreachable as normalization should have failed for non-wf aliases, so the only way you can get an alias in layout_of is if it is still rigid.

File: compiler/rustc_ty_utils/src/layout.rs
Comment (lcnr) [reply compiler/rustc_ty_utils/src/layout.rs:1]: I don't think so, the code broken by his compiled previously and this check could have at most resulted in errors.

The reason this regressed is that we've added new associated constants to the standard library causing us to evaluate things and to check their layout in more places
