### PR TITLE
exclude unexported macro bindings from extern crate

### LINKED ISSUE #119301: issue-80074 test should not compile
The test in https://github.com/rust-lang/rust/blob/master/tests/ui/extern/issue-80074.rs shouldn't actually compile -- it's using a non-exported macro from a foreign crate. Instead, we should get an error indicating that the name is private and/or that the name doesn't exist at all.

Likely a regression introduced by https://github.com/rust-lang/rust/pull/88019.

See discussion in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/cross-crate.20macro.20usage.20allowed.20with.20no.20macro_export.3F

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #119301 

Macros that aren't exported from an external crate should not be defined.

r? @petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -1071,7 +1071,8 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
             let import = macro_use_import(self, span);
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1071]: Could you also make sure that named macro uses (`#[macro_use(foo)]`) on extern crates do not allow using private macros?
(That's the `else` part of this `if`.)

Comment (bvanjoi) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1071]: I have updated this patch.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1071]: Ah, great, it is already working correctly.

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
Many "No space left on device" errors, need to run for the second time as usual.
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-119369/retry-regressed-list.txt

**Comment by bvanjoi** [comment]
The majority of issues are caused by the usage of the ﻿`quote` which exported from other crates. For instance, such instances occur in `﻿leptos_macro`:

```rs
#[macro_use]
extern crate proc_macro_error;

use proc_macro::TokenStream;

#[proc_macro]
pub fn view(_a: TokenStream) -> TokenStream {
  quote!{};
  TokenStream::new()
}
```


and the reduced was:
```rs
// extern-1
#[macro_export]
macro_rules! quote {
    () => {}
}

// extern-2
use extern_1::quote;

// code.rs
#[macro_use]
extern crate sera_2;

fn main() {
  quote! {};
}
```

**Comment by bvanjoi** [comment]
Should we consider adding a lint for this issue?

**Comment by petrochenkov** [comment]
Yeah, this clearly needs to go through a deprecation lint.
@rustbot author

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 2]
```diff
@@ -4614,3 +4614,49 @@ declare_lint! {
...
+    /// This is a [future-incompatible] lint to transition this to a
+    /// hard error in the future.
+    ///
+    /// [future-incompatible]: ../index.md#future-incompatible-lints
+    pub UNEXPECTED_REEXPORT_MACRO,
+    Warn,
+    "detects certain macro bindings that should not be re-exported",
+    @future_incompatible = FutureIncompatibleInfo {
+        reason: FutureIncompatibilityReason::FutureReleaseErrorDontReportInDeps,
+        reference: "issue #X <https://github.com/rust-lang/rust/issues/X>",
```
Comment (bvanjoi) [inline compiler/rustc_lint_defs/src/builtin.rs:4660]: I'll create an issue after the regression test passes.

File: tests/ui/extern/issue-80074.rs [hunk 3]
```diff
@@ -1,10 +1,20 @@
...
+#[macro_use(m)]
+extern crate issue_80074_2;
+//~^^ ERROR: imported macro not found
+
 fn main() {
     foo!();
+    //~^ WARN: foo is not reexported
+    //~| WARN: it will become a hard error in a future release!
+    bar!();
+    //~^ ERROR: cannot find macro `bar` in this scope
```
Comment (bvanjoi) [inline tests/ui/extern/issue-80074.rs:17]: `bar` has thrown an error as it did previously.

**Comment by bvanjoi** [comment]
Minor reduction for the above failure:

```rs
#[macro_use]
extern crate smallvec;

#[derive(Hash)]
struct A {}

fn main() {}
```

**Comment by bvanjoi** [comment]
ci is green @rustbot ready

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 4]
```diff
@@ -1072,7 +1074,24 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
             self.r.potentially_unused_imports.push(import);
             module.for_each_child(self, |this, ident, ns, binding| {
                 if ns == MacroNS {
-                    let imported_binding = this.r.import(binding, import);
+                    let imported_binding =
+                        if this.r.is_accessible_from(binding.vis, this.parent_scope.module) {
+                            this.r.import(binding, import)
+                        } else if !this.r.is_builtin_macro(binding.res())
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1080]: This is not fully correct, but should be good enough for a lint, second crater run will show.

File: compiler/rustc_resolve/src/lib.rs [hunk 5]
```diff
@@ -1808,6 +1809,12 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
                     }
                 }
             }
+            if let ImportKind::MacroUse { warn_not_exported } = import.kind
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1812]:
```suggestion
            if let ImportKind::MacroUse { warn_not_exported: true } = import.kind
```

Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1812]: Could you put this block above the `if is_lexical_scope { ... }` logic, so it's not skipped if return happens?
I'm not sure if it makes any difference, but just in case.

File: compiler/rustc_resolve/src/imports.rs [hunk 6]
```diff
@@ -80,7 +80,11 @@ pub(crate) enum ImportKind<'a> {
         target: Ident,
         id: NodeId,
     },
-    MacroUse,
+    MacroUse {
+        /// A field has been added indicating whether it should be reported as a lint,
+        /// addressing issue#119301.
+        warn_not_exported: bool,
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/imports.rs:86]:
```suggestion
        warn_private: bool,
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 7]
```diff
@@ -1029,9 +1029,9 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
             }
         }
 
-        let macro_use_import = |this: &Self, span| {
+        let macro_use_import = |this: &Self, span: Span, warn_not_exported: bool| {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1032]:
```suggestion
        let macro_use_import = |this: &Self, span, warn_not_exported| {
```
The type annotations look redundant here.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 8]
```diff
@@ -1048,11 +1048,28 @@ impl<'a, 'b, 'tcx> BuildReducedGraphVisitor<'a, 'b, 'tcx> {
...
+                    } else if !this.r.is_builtin_macro(binding.res())
+                        && !this.r.macro_use_prelude.contains_key(&ident.name)
+                    {
+                        // - `!r.is_builtin_macro(res)` excluding the built-in macros such as `Debug` or `Hash`.
+                        // - `!r.macro_use_prelude.contains_key(name)` excluding macros defined in other extern
+                        //    crates such as `std`.
+                        // FIXME: This branch should eventually be removed.
+                        let import = macro_use_import(this, span, true);
+                        let binding = this.r.import(binding, import);
+                        self.r.arenas.alloc_name_binding(NameBindingData { ..(*binding).clone() })
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1069]: This is not needed now? `binding` could be returned directly instead?

**Comment by petrochenkov** [comment]
The issue still need to be created - https://github.com/rust-lang/rust/pull/119369#discussion_r1439665726.
@rustbot author

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 9]
```diff
@@ -4604,3 +4604,49 @@ declare_lint! {
...
+    /// This is a [future-incompatible] lint to transition this to a
+    /// hard error in the future.
+    ///
+    /// [future-incompatible]: ../index.md#future-incompatible-lints
+    pub PRIVATE_MACRO_USE,
+    Warn,
+    "detects certain macro bindings that should not be re-exported",
+    @future_incompatible = FutureIncompatibleInfo {
+        reason: FutureIncompatibilityReason::FutureReleaseErrorDontReportInDeps,
+        reference: "issue #X <https://github.com/rust-lang/rust/issues/120192>",
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/builtin.rs:4650]:
```suggestion
        reference: "issue #120192 <https://github.com/rust-lang/rust/issues/120192>",
```

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 10]
```diff
@@ -4604,3 +4604,49 @@ declare_lint! {
         reference: "issue #X <https://github.com/rust-lang/rust/issues/X>",
     };
 }
+
+declare_lint! {
+    /// The `private_macro_use` lint detects macros that are imported
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/builtin.rs:4609]:
```suggestion
    /// The `private_macro_use` lint detects private macros that are imported
```

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 11]
```diff
@@ -4604,3 +4604,49 @@ declare_lint! {
...
+    /// with `#[macro_use]`.
+    ///
+    /// ### Example
+    ///
+    /// ```rust,ignore (needs extern crate)
+    /// // extern_macro.rs
+    /// macro_rules! foo { () => {}; }
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/builtin.rs:4616]:
```suggestion
    /// use proc_macro_foo::foo;
```
Usual `macro_rules!` are not affected by this issue, only `macro`s 2.0, and reexports of procedural macros or `#[macro_export] macro_rules!` from some third crate.

For a macro to be fetched by `#[macro_use] extern crate bar;` its name should be placed into the `bar`'s root module, but `macro_rules!` names are not placed into modules.

**Comment by petrochenkov** [comment]
r=me with the remaining nits addressed.

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 11 above)
Comment (bvanjoi) [reply compiler/rustc_lint_defs/src/builtin.rs:4616]: I will modify as follows:

```rs
// extern_macro.rs
macro_rules! foo_ { () => {}; }
use foo_ as foo;
```

Comment (petrochenkov) [reply compiler/rustc_lint_defs/src/builtin.rs]: Ah, yes, that should work too.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+
