### PR TITLE
Lower extra lifetimes before normal generic params.

### LINKED ISSUE #143413: ICE: `no entry for node id: NodeId(27)`
### Code

```Rust
static a: for<const b: [c([&impl 'd; _]); _]> e;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (da58c0513 2025-07-03)
binary: rustc
commit-hash: da58c051315268a197ce280f6ba07bbd03c66535
commit-date: 2025-07-03
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_ast_lowering/src/lib.rs:561:55:
no entry for node id: `NodeId(27)`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_ast_lowering/src/lib.rs:561:55:
no entry for node id: `NodeId(27)`
stack backtrace:
   0:     0x7f8a9051ab95 - std::backtrace::Backtrace::create::ha23dbb93c61c8dfd
   1:     0x7f8a9051aae5 - std::backtrace::Backtrace::force_capture::hcf7d29f280c9a155
   2:     0x7f8a8f5ff57c - std[4c753eefc38e611f]::panicking::update_hook::<alloc[52d37518c7e65bd5]::boxed::Box<rustc_driver_impl[4ceb8fef541c3c89]::install_ice_hook::{closure#1}>>::{closure#0}
   3:     0x7f8a90534cdb - std::panicking::rust_panic_with_hook::hb7e8da047aff3a07
   4:     0x7f8a905349da - std::panicking::begin_panic_handler::{{closure}}::h8172934590c86311
   5:     0x7f8a90530ff9 - std::sys::backtrace::__rust_end_short_backtrace::h7f7916d1eada9ebc
   6:     0x7f8a905346bd - __rustc[689ec07a40e2eaf3]::rust_begin_unwind
   7:     0x7f8a8cca61f0 - core::panicking::panic_fmt::hbea0fe892fb47fcf
   8:     0x7f8a91043c92 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::new_named_lifetime
   9:     0x7f8a91044a72 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct
  10:     0x7f8a91046390 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct
  11:     0x7f8a91038fbc - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_qpath
  12:     0x7f8a91044f55 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct
  13:     0x7f8a91046390 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct
  14:     0x7f8a91086ca7 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_generic_param
  15:     0x7f8a910434f1 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_lifetime_binder
  16:     0x7f8a91074d6e - <core[95da0b4bbfd84352]::iter::adapters::GenericShunt<core[95da0b4bbfd84352]::iter::adapters::map::Map<core[95da0b4bbfd84352]::iter::adapters::filter_map::FilterMap<core[95da0b4bbfd84352]::slice::iter::Iter<rustc_ast[4ee61d1cc044460]::ast::GenericBound>, <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct::{closure#1}::{closure#0}>, core[95da0b4bbfd84352]::result::Result<rustc_hir[32919f855a89c7c2]::hir::PolyTraitRef, !>::Ok>, core[95da0b4bbfd84352]::result::Result<core[95da0b4bbfd84352]::convert::Infallible, !>> as core[95da0b4bbfd84352]::iter::traits::iterator::Iterator>::next
  17:     0x7f8a91074919 - rustc_arena[b5658d2c80d473eb]::outline::<<rustc_arena[b5658d2c80d473eb]::DroplessArena>::alloc_from_iter<rustc_hir[32919f855a89c7c2]::hir::PolyTraitRef, core[95da0b4bbfd84352]::iter::adapters::filter_map::FilterMap<core[95da0b4bbfd84352]::slice::iter::Iter<rustc_ast[4ee61d1cc044460]::ast::GenericBound>, <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct::{closure#1}::{closure#0}>>::{closure#0}, &mut [rustc_hir[32919f855a89c7c2]::hir::PolyTraitRef]>
  18:     0x7f8a910465d3 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_ty_direct
  19:     0x7f8a91eb5795 - <rustc_ast_lowering[cb6aa0bf883173e2]::LoweringContext>::lower_item_kind
  20:     0x7f8a90f6446e - <rustc_ast_lowering[cb6aa0bf883173e2]::item::ItemLowerer>::lower_node
  21:     0x7f8a90f62c63 - rustc_ast_lowering[cb6aa0bf883173e2]::lower_to_hir
  22:     0x7f8a91ea79e2 - rustc_query_impl[f1e02cc070b3fce1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f1e02cc070b3fce1]::query_impl::hir_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7f8a91cb8041 - rustc_query_system[b1c6291b83d15898]::query::plumbing::try_execute_query::<rustc_query_impl[f1e02cc070b3fce1]::DynamicConfig<rustc_query_system[b1c6291b83d15898]::query::caches::SingleCache<rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f1e02cc070b3fce1]::plumbing::QueryCtxt, false>
  24:     0x7f8a91cb77de - rustc_query_impl[f1e02cc070b3fce1]::query_impl::hir_crate::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7f8a92318116 - rustc_query_impl[f1e02cc070b3fce1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f1e02cc070b3fce1]::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2}::{closure#0}, rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>>.warm
  26:     0x7f8a90da416e - rustc_query_system[b1c6291b83d15898]::query::plumbing::try_execute_query::<rustc_query_impl[f1e02cc070b3fce1]::DynamicConfig<rustc_data_structures[1f7fc31d10663dcb]::vec_cache::VecCache<rustc_span[cd697bb88190d092]::def_id::LocalDefId, rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[b1c6291b83d15898]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[f1e02cc070b3fce1]::plumbing::QueryCtxt, false>
  27:     0x7f8a90da3e0b - rustc_query_impl[f1e02cc070b3fce1]::query_impl::opt_hir_owner_nodes::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f8a916a2c26 - <rustc_middle[70415016df95c802]::ty::context::TyCtxt>::expect_hir_owner_nodes
  29:     0x7f8a90d9810a - rustc_middle[70415016df95c802]::hir::map::hir_crate_items
  30:     0x7f8a91ea60d9 - rustc_query_impl[f1e02cc070b3fce1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f1e02cc070b3fce1]::query_impl::hir_crate_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f8a91cb8041 - rustc_query_system[b1c6291b83d15898]::query::plumbing::try_execute_query::<rustc_query_impl[f1e02cc070b3fce1]::DynamicConfig<rustc_query_system[b1c6291b83d15898]::query::caches::SingleCache<rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[f1e02cc070b3fce1]::plumbing::QueryCtxt, false>
  32:     0x7f8a916987d2 - rustc_query_impl[f1e02cc070b3fce1]::query_impl::hir_crate_items::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f8a91698ba4 - rustc_interface[b4fd03ac85b435ff]::passes::analysis
  34:     0x7f8a91698b2b - rustc_query_impl[f1e02cc070b3fce1]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[f1e02cc070b3fce1]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 0usize]>>
  35:     0x7f8a91cb6176 - rustc_query_system[b1c6291b83d15898]::query::plumbing::try_execute_query::<rustc_query_impl[f1e02cc070b3fce1]::DynamicConfig<rustc_query_system[b1c6291b83d15898]::query::caches::SingleCache<rustc_middle[70415016df95c802]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[f1e02cc070b3fce1]::plumbing::QueryCtxt, false>
  36:     0x7f8a91cb5d40 - rustc_query_impl[f1e02cc070b3fce1]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7f8a91ea9fd6 - rustc_interface[b4fd03ac85b435ff]::passes::create_and_enter_global_ctxt::<core[95da0b4bbfd84352]::option::Option<rustc_interface[b4fd03ac85b435ff]::queries::Linker>, rustc_driver_impl[4ceb8fef541c3c89]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  38:     0x7f8a91e70cc3 - rustc_interface[b4fd03ac85b435ff]::interface::run_compiler::<(), rustc_driver_impl[4ceb8fef541c3c89]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7f8a91e170f8 - std[4c753eefc38e611f]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[b4fd03ac85b435ff]::util::run_in_thread_with_globals<rustc_interface[b4fd03ac85b435ff]::util::run_in_thread_pool_with_globals<rustc_interface[b4fd03ac85b435ff]::interface::run_compiler<(), rustc_driver_impl[4ceb8fef541c3c89]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  40:     0x7f8a91e16dd6 - <<std[4c753eefc38e611f]::thread::Builder>::spawn_unchecked_<rustc_interface[b4fd03ac85b435ff]::util::run_in_thread_with_globals<rustc_interface[b4fd03ac85b435ff]::util::run_in_thread_pool_with_globals<rustc_interface[b4fd03ac85b435ff]::interface::run_compiler<(), rustc_driver_impl[4ceb8fef541c3c89]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[95da0b4bbfd84352]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f8a91e153bd - std::sys::pal::unix::thread::Thread::new::thread_start::hc3b694f3a738a566
  42:     0x7f8a8b86bac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  43:     0x7f8a8b8fd850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
  44:                0x0 - <unknown>


rustc version: 1.90.0-nightly (da58c0513 2025-07-03)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [opt_hir_owner_nodes] getting HIR owner items in ``
#2 [hir_crate_items] getting HIR crate items
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### Bisection
Regression in nightly-2022-06-23

- commit[0] 2022-06-21: Auto merge of #98098 - bjorn3:archive_refactor, r=michaelwoerister
- commit[1] 2022-06-22: Auto merge of #98359 - JohnTitor:rollup-v30vyzr, r=JohnTitor
- commit[2] 2022-06-22: Auto merge of #97853 - TaKO8Ki:emit-only-one-note-per-unused-struct-field, r=estebank
- commit[3] 2022-06-22: Auto merge of #98375 - JohnTitor:rollup-e5c6rgo, r=JohnTitor
- commit[4] 2022-06-22: Auto merge of #98279 - cjgillot:all-fresh-nofn, r=petrochenkov

### Related issue
#118697

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/143413

### CODE REVIEW

File: tests/ui/lifetimes/elided-lifetime-in-const-param-type.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/143413>
+//! The anonymous lifetime in `c(&())` is desugared by the resolver as an extra lifetime parameter
+//! at the end of the `for` binder. Verify that lowering creates the definition for that extra
+//! lifetime parameter before lowering `c(&())`.
+
+type A = for<const B: c(&())> D;
```
Comment (oli-obk) [inline tests/ui/lifetimes/elided-lifetime-in-const-param-type.rs]: Unrelated error minimization:

```rust
#![feature(non_lifetime_binders)]
#![expect(incomplete_features)]

trait D {}

type A = dyn for<const B: c(&())> D;
```

**Comment by matthiaskrgr** [comment]
meh, I was hoping this would fix https://github.com/rust-lang/rust/issues/122903 as well :see_no_evil:

File: tests/ui/lifetimes/elided-lifetime-in-const-param-type.rs (hunk 1 above)
Comment (cjgillot) [reply tests/ui/lifetimes/elided-lifetime-in-const-param-type.rs]: The attributes introduce even more errors, as they trigger some validation.
