### PR TITLE
Fix a parser ICE on invalid `fn` body

### LINKED ISSUE #87635: ICE on nightly 1.56.0 (2021-07-29) when missing semicolon or function body in impl block
Playground with repro [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0240939444c902f277a55c9d7d9ba3a7). Not present in latest stable or beta.

### Code

```Rust
struct Foo {}

impl Foo {
    pub fn bar()
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (492723897 2021-07-29)
binary: rustc
commit-hash: 492723897e9b4db6701b3a75b72618d08a7d5319
commit-date: 2021-07-29
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
   Compiling ice v0.1.0 ([redacted])
error: expected `;`, found `}`
 --> src/main.rs:4:17
  |
4 |     pub fn bar()
  |                 ^ help: add `;` here
5 | }
  | - unexpected token

thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_parse/src/parser/item.rs:1723:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (492723897 2021-07-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `ice` due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/library/std/src/panicking.rs:516:5
   1: core::panicking::panic_fmt
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/library/core/src/panicking.rs:93:14
   2: core::panicking::panic
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319/library/core/src/panicking.rs:50:5
   3: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_fn
   4: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_kind
   5: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_common
   6: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_assoc_item
   7: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_impl
   8: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_kind
   9: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_common
  10: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_mod
  11: rustc_parse::parse_crate_from_file
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_interface::passes::parse
  14: rustc_interface::queries::Queries::parse
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: rustc_interface::interface::create_compiler_and_run
  18: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #87635
A better fix would add a check for `fn` body on `expected_one_of_not_found` but I haven't come up with a graceful way. Any idea?
r? @oli-obk @estebank

### CODE REVIEW

**Comment by estebank** [comment]
FWIW, I'm ok with the code change as it is.

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -1715,13 +1715,11 @@ impl<'a> Parser<'a> {
                     // the AST for typechecking.
                     err.span_label(ident.span, "while parsing this `fn`");
                     err.emit();
-                    (Vec::new(), None)
                 } else {
                     return Err(err);
                 }
-            } else {
-                unreachable!()
```
Comment (oli-obk) [inline compiler/rustc_parse/src/parser/item.rs:1723]: maybe add a `delay_span_bug` to protect against this ever passing compilation.

**Comment by oli-obk** [comment]
Seems ok, even if the first parser error is unfortunately not great. The second error clears up things, so that is good.

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_parse/src/parser/item.rs:1723]: esteban and I had a short chat. This is ok, even if not idea. There should be an issue mentioning the wrong first error suggestion (as seen in the newly added test) and that we should find a way to avoid that message and just show the second one.

r=me with that issue opened.

**Comment by JohnTitor** [comment]
The issue is already open: #87647
@bors r=oli-obk
