### PR TITLE
Properly handle primitive disambiguators in rustdoc

### LINKED ISSUE #80559: Rustdoc treats primitive disambiguators incorrectly
I tried this code:

```rust
//! [str::trim()]
```

I expected to see this happen: Rustdoc links to https://doc.rust-lang.org/nightly/std/primitive.str.html#method.trim.

Instead, this happened: Rustdoc gets confused that `()` means a function and thinks that the link is a primitive.

```
error: incompatible link kind for `str::trim`
   |
   |
57 | /// Using the [`str::trim()`] method ensures that no whitespace remains before parsing.
   |                ^^^^^^^^^^^^^ help: to link to the builtin type, prefix with `prim@`: ``prim@str::trim``
   |
   = note: `-D broken-intra-doc-links` implied by `-D warnings`
   = note: this link resolved to a builtin type, which is not a function
```

### Meta

`rustdoc --version`:
```
rustdoc 1.50.0-beta.1 (05b602367 2020-12-29)
```

Relevant code: https://github.com/rust-lang/rust/blob/a6bd5246da7806786b5c1f61d05a957c9ae68903/src/librustdoc/passes/collect_intra_doc_links.rs#L1181

I think the fix is just to add `if self.kind_side_channel.is_none()` as a match guard.

### PR DESCRIPTION
**Pull request by max-heller**
Fixes #80559 

r? @jyn514 

Is there a way to test that the generated intra-doc link is what I expect?

### CODE REVIEW

**Comment by jyn514** [comment]
> Is there a way to test that the generated intra-doc link is what I expect?

Yes, see https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts for instructions and `src/test/rustdoc/intra-doc` for examples. Please also move the test case to the `intra-doc` subdirectory and name it after the fix instead of the issue.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -1143,6 +1147,7 @@ impl LinkCollector<'_, '_> {
                     None
                 }
             },
+            Res::Primitive(_) => Some(ItemLink { link: ori_link, link_text, did: None, fragment }),
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1150]: This won't check that the disambiguator is correct, it unconditionally resolves the link. I would refactor the body of the `Res::Def` arm into a closure (or function) and call that to check this is correct. You can get the `kind` and `id` from the `kind_side_channel` you just updated.

Please also add a test case:
```rust
//! [struct@str::trim] //~ ERROR incompatible link
```

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: That makes sense, I made the refactor. Now I'm getting this error for the mismatched disambiguator:
```
error: unresolved link to `str::trim`
  --> /home/max/documents/projects/rust/src/test/rustdoc/intra-doc/incompatible-primitive-disambiguator.rs:3:6
   |
 3 | //! [struct@str::trim]
   |      ^^^^^^^^^^^^^^^^
   |      |
   |      this link resolves to the associated function `trim`, which is not in the type namespace
   |      help: to link to the associated function, add parentheses: `str::trim()`
```
which isn't the one we want. It seems like it's coming from a `ResolutionFailure::WrongNamespace` and that the disambiguator is never making it to the part of the code I'm touching.

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: I'm not sure without getting a debug build. `WrongNamespace` is very wrong but I'm also baffled how you could end up with one - the parsing code is relatively simple and I would expect it to panic before returning the wrong thing: https://github.com/rust-lang/rust/blob/06b0900a2dc53ed4b5fa98c859fec5c224929eb8/src/librustdoc/passes/collect_intra_doc_links.rs#L1473
Can you try to find how you end up with a `Disambiguator::Namespace`?

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: We don't end up with a namespace disambiguator, the type namespace is implied by the `struct@` disambiguator. Then, in `resolve_with_disambiguator`, we get here:

https://github.com/rust-lang/rust/blob/06b0900a2dc53ed4b5fa98c859fec5c224929eb8/src/librustdoc/passes/collect_intra_doc_links.rs#L1285-L1292

which finds the associated method in the value namespace and yields the namespace error.

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Hmm, that seems like an existing bug. If you use `struct@Vec::new`, does it have a similar misleading error? If so I think it's ok not to fix it here and mention it in https://github.com/rust-lang/rust/issues/77150; you could just use a different test that works approximately right instead.

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Yep:
```
warning: unresolved link to `Vec::new`
 --> src/lib.rs:1:6
  |
1 | //! [struct@Vec::new]
  |      ^^^^^^^^^^^^^^^
  |      |
  |      this link resolves to the associated function `new`, which
 is not in the type namespace
  |      help: to link to the associated function, add parentheses:
 `Vec::new()`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default

warning: 1 warning emitted
```

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Commented on the issue and pushed an updated test.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -1142,55 +1146,67 @@ impl LinkCollector<'_, '_> {
...
+                } else {
+                    match disambiguator {
+                        Some(Disambiguator::Primitive | Disambiguator::Namespace(_)) | None => {}
+                        Some(other) => {
+                            report_mismatch(other, Disambiguator::Primitive);
+                            return None;
+                        }
                     }
                 }
+                Some(ItemLink { link: ori_link.link, link_text, did: None, fragment })
```
Comment (jyn514) [inline src/librustdoc/passes/collect_intra_doc_links.rs:1206]: This doesn't look right for the verify case: I think `register_res` is still needed, and `did` should be the ID you just found. (I think register_res only matters for cross-crate re-exports, which is why it didn't show up in the tests.)

Maybe it would be simpler rather than duplicating the control flow of `Res::Def` to do `let (kind, id) = match res { ... }`, like you had in https://github.com/rust-lang/rust/pull/80660/commits/fc3a4058cefc09bebe98039c7fb8d74d1be9c6e6 ? That looked right to me, I'm not sure why you changed it.

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1206]: Including the `let id = register_res(cx, rustc_hir::def::Res::Def(kind, id));` causes this error:
```
error: internal compiler error: compiler/rustc_metadata/src/rmeta/decoder.rs:807:18: def-index does not refer to trait or trait alias

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
```
I changed the control flow to avoid it. Should I be passing `register_res` something else?

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1206]: Well that's strange. Can you find where that goes wrong? I wouldn't expect a fake id to make it this far.

If this ends up being tricky I'm ok with getting the fix in, but it sounds like something suspicious is going on.

It would also be nice to add a test for cross crate exports:

```rust
//! [trim]
pub use str::trim;
```

Comment (max-heller) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1206]: `use`ing primitive associated items doesn't appear to work in the first place ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1208a24fa33894a880b22505ad7a21ec))

Comment (jyn514) [reply src/librustdoc/passes/collect_intra_doc_links.rs:1206]: Hmm, ok. This is probably ok to land as-is then - I'm confused why `register_res` ICEs but otherwise the current code seems fine.

Can you leave a comment summarizing what's going on?

**Comment by jyn514** [comment]
@bors r+

Thanks for sticking with this!

**Comment by jyn514** [comment]
@bors squash

This messes with github unfortunately - if bors says this was merged you can trust it and close the PR.

**Comment by max-heller** [comment]
@jyn514 thanks for the help!

**Comment by jyn514** [comment]
Looks like it couldn't find a runner for aarch64-gnu? There's no build log.

@bors retry

**Comment by jyn514** [comment]
@bors retry

https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/CI.20failure.3A.20maintainer.20not.20assignable
