### PR TITLE
std: Audit std::thread implementations

### LINKED ISSUE #24442: compiles on linux but not windows
```rust
use std::thread;
use std::thread::JoinGuard;
use std::collections::HashMap;
use std::sync::{Mutex,Arc};

fn main() {
	let join_guards:Arc<Mutex<HashMap<u64, JoinGuard<'static,()>>>> = Arc::new(Mutex::new(HashMap::new()));
	let join_guard = thread::scoped(move||{
		while join_guards.lock().unwrap().len() != 0{
			//...
		}
	});
}
```

The above code compiles fine using the latest nightly build on Ubuntu (`rustc 1.0.0-nightly (e6a812402 2015-04-14) (built 2015-04-14)`)
but gets the following error on Windows 8 (same rustc version)
```
src\main.rs:11:19: 11:33 error: the trait `core::marker::Send` is not implemented for the type `*mut libc::types::common
::c95::c_void` [E0277]
src\main.rs:11  let join_guard = thread::scoped(move||{
                                 ^~~~~~~~~~~~~~
src\main.rs:11:19: 11:33 note: `*mut libc::types::common::c95::c_void` cannot be sent between threads safely
src\main.rs:11  let join_guard = thread::scoped(move||{
                                 ^~~~~~~~~~~~~~
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Much of this code hasn't been updated in quite some time and this commit does a
small audit of the functionality:
- Implementation functions now centralize all functionality on a locally defined
  `Thread` type.
- The `detach` method has been removed in favor of a `Drop` implementation. This
  notably fixes leaking thread handles on Windows.
- The `Thread` structure is now appropriately annotated with `Send` and `Sync`
  automatically on Windows and in a custom fashion on Unix.
- The unsafety of creating a thread has been pushed out to the right boundaries
  now.

Closes #24442

### CODE REVIEW

File: src/libstd/thread/mod.rs [hunk 1]
```diff
@@ -610,27 +594,19 @@ impl thread_info::NewThread for Thread {
 #[stable(feature = "rust1", since = "1.0.0")]
 pub type Result<T> = ::result::Result<T, Box<Any + Send + 'static>>;
 
-struct Packet<T>(Arc<UnsafeCell<Option<Result<T>>>>);
-
-unsafe impl<T:Send> Send for Packet<T> {}
-unsafe impl<T> Sync for Packet<T> {}
+type Packet<T> = Arc<Mutex<Option<Result<T>>>>;
```
Comment (aturon) [inline src/libstd/thread/mod.rs]: Why introduce a mutex? The use of join should already guarantee sufficient synchronization.

**Comment by aturon** [comment]
This looks good to me, though I am curious about the introduction of a `Mutex` in the `Packet` type.

File: src/libstd/thread/mod.rs (hunk 1 above)
Comment (alexcrichton) [inline src/libstd/thread/mod.rs]: This helped avoid a number of `unsafe impl` blocks as well as removing a bit of `unsafe` code. I definitely agree that it was properly synchronized before, I was just hoping to cut down on the amount of `unsafe` here. I'll see if I can't finesse a nicer solution to this though.

Comment (aturon) [inline src/libstd/thread/mod.rs]: OK. Not a huge deal, the extra call into system APIs would probably never show up on a profile.
