### PR TITLE
stabilize `ci_rustc_if_unchanged_logic` test for local environments

### LINKED ISSUE #138239: Bootstrap test ci_rustc_if_unchanged_logic fails locally
### Summary

The test `ci_rustc_if_unchanged_logic` fails if you are working on a branch that has any changes to library or compiler with:

```
---- core::builder::tests::ci_rustc_if_unchanged_logic stdout ----
Creating a sysroot for stage2 compiler (use `rustup toolchain link 'name' build/host/stage2`)
Building stage2 library artifacts (x86_64-unknown-linux-gnu)

thread 'core::builder::tests::ci_rustc_if_unchanged_logic' panicked at src/bootstrap/src/core/builder/tests.rs:267:9:
CI-rustc can't be used with 'if-unchanged' while there are changes in compiler and/or library.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    core::builder::tests::ci_rustc_if_unchanged_logic
```

This makes it difficult to run tests locally. For example, running the `x86_64-gnu` docker image fails with this message.

I'm not entirely clear how this test works in CI, but it would be helpful if it didn't fail for local testing.

### Command used

```sh
./x test bootstrap
```

or

```sh
 cargo run --manifest-path src/ci/citool/Cargo.toml run-local x86_64-gnu
```

### Expected behaviour

Command should pass.

### Actual behaviour

Test fails.

### Bootstrap configuration (config.toml)

No config (use all defaults), or use the config in the x86_64-gnu image.

```toml
```

### Operating system

Any

### HEAD

39d5d9284fbfbc12d6d2ce8805b1c3f2654cd9f5

### PR DESCRIPTION
**Pull request by onur-ozkan**
Fixes #138239

### CODE REVIEW

File: src/bootstrap/src/core/builder/tests.rs [hunk 1]
```diff
@@ -261,8 +261,14 @@ fn ci_rustc_if_unchanged_logic() {
     // Make sure "if-unchanged" logic doesn't try to use CI rustc while there are changes
     // in compiler and/or library.
     if config.download_rustc_commit.is_some() {
-        let has_changes =
-            config.last_modified_commit(&["compiler", "library"], "download-rustc", true).is_none();
+        let mut paths = vec!["compiler"];
+
+        // Handle library tree the same way as in `Config::download_ci_rustc_commit`.
```
Comment (jieyouxu) [inline src/bootstrap/src/core/builder/tests.rs:266]: Suggestion: I think we should either:

- Have a single source of truth for the paths calculation fed to `last_modified_commit` for this purpose,
- Or also add a comment at the source site where we also do this paths adjustment.

wdyt?

**Review by jieyouxu — APPROVED** [review]
Thanks, the test fix LGTM. I have one suggestion re. how to make this test less likely to diverge in the future.

File: src/bootstrap/src/core/builder/tests.rs (hunk 1 above)
Comment (onur-ozkan) [reply src/bootstrap/src/core/builder/tests.rs:266]: > Have a single source of truth for the paths calculation fed to last_modified_commit for this purpose,

We can't do that as one side excludes those paths and the other includes them. Also, using that approach would cause this coverage to miss the expected behaviour (imagine that function somehow have bugs in its logic).

> Or at least add a comment at the source site where we also do this paths adjustment to remind also updating this test.

Sure, let me know exactly where and what you want me to write.

Comment (jieyouxu) [reply src/bootstrap/src/core/builder/tests.rs:266]: Maybe just cc this test next to https://github.com/rust-lang/rust/blob/master/src%2Fbootstrap%2Fsrc%2Fcore%2Fconfig%2Fconfig.rs#L2984-L2990?

**Comment by jieyouxu** [comment]
Thanks!
@bors r+ rollup
