### PR TITLE
Don't rerun MIR passes when inlining

### LINKED ISSUE #50411: [ICE] with mir-opt-level=3
```
fn main() {
    let _ = (0 .. 1).filter(|_| [1].iter().all(|_| true)).count();
}
```

Compiling with:

`rustc -Z mir-opt-level=3 test.rs`

Gives:

```
error: internal compiler error: librustc_mir\dataflow\move_paths\builder.rs:296: SetDiscriminant should not exist during borrowck

thread 'main' panicked at 'Box<Any>', librustc_errors\lib.rs:499:9
stack backtrace:
   0: mingw_set_invalid_parameter_handler
   1: mingw_set_invalid_parameter_handler
   2: mingw_set_invalid_parameter_handler
   3: mingw_set_invalid_parameter_handler
   4: mingw_set_invalid_parameter_handler
   5: mingw_set_invalid_parameter_handler
   6: mingw_set_invalid_parameter_handler
   7: mingw_set_invalid_parameter_handler
   8: mingw_set_invalid_parameter_handler
   9: mingw_set_invalid_parameter_handler
  10: mingw_set_invalid_parameter_handler
  11: mingw_set_invalid_parameter_handler
  12: mingw_set_invalid_parameter_handler
  13: mingw_set_invalid_parameter_handler
  14: mingw_set_invalid_parameter_handler
  15: mingw_set_invalid_parameter_handler
  16: mingw_set_invalid_parameter_handler
  17: mingw_set_invalid_parameter_handler
  18: mingw_set_invalid_parameter_handler
  19: mingw_set_invalid_parameter_handler
  20: mingw_set_invalid_parameter_handler
  21: mingw_set_invalid_parameter_handler
  22: mingw_set_invalid_parameter_handler
  23: mingw_set_invalid_parameter_handler
  24: mingw_set_invalid_parameter_handler
  25: mingw_set_invalid_parameter_handler
  26: mingw_set_invalid_parameter_handler
  27: mingw_set_invalid_parameter_handler
  28: mingw_set_invalid_parameter_handler
  29: mingw_set_invalid_parameter_handler
  30: mingw_set_invalid_parameter_handler
  31: mingw_set_invalid_parameter_handler
  32: mingw_set_invalid_parameter_handler
  33: mingw_set_invalid_parameter_handler
  34: mingw_set_invalid_parameter_handler
  35: mingw_set_invalid_parameter_handler
  36: mingw_set_invalid_parameter_handler
  37: mingw_set_invalid_parameter_handler
  38: mingw_set_invalid_parameter_handler
  39: mingw_set_invalid_parameter_handler
  40: mingw_set_invalid_parameter_handler
  41: mingw_set_invalid_parameter_handler
  42: mingw_set_invalid_parameter_handler
  43: mingw_set_invalid_parameter_handler
  44: mingw_set_invalid_parameter_handler
  45: mingw_set_invalid_parameter_handler
  46: mingw_set_invalid_parameter_handler
  47: mingw_set_invalid_parameter_handler
  48: mingw_set_invalid_parameter_handler
  49: std::rt::lang_start::{{closure}}
  50: mingw_set_invalid_parameter_handler
  51: mingw_set_invalid_parameter_handler
  52: mingw_set_invalid_parameter_handler
  53: main
  54: _tmainCRTStartup
  55: mainCRTStartup
  56: mingw_set_invalid_parameter_handler
  57: mingw_set_invalid_parameter_handler
query stack during panic:
#0 [optimized_mir] processing `main::{{closure}}`
#1 [collect_and_partition_translation_items] collect_and_partition_translation_items
end of query stack
error: aborting due to previous error

note: rustc 1.27.0-nightly (8a37c75a3 2018-05-02) running on x86_64-pc-windows-gnu

note: compiler flags: -Z mir-opt-level=3
```

```
rustc 1.27.0-nightly (8a37c75a3 2018-05-02)
binary: rustc
commit-hash: 8a37c75a3a661385cc607d934c70e86a9eaf5fd7
commit-date: 2018-05-02
host: x86_64-pc-windows-gnu
release: 1.27.0-nightly
LLVM version: 6.0
```

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #50411 

r? @nikomatsakis 

I updated your commit message with additional details. Let me know if any of that is incorrect. I also added the appropriate `compile-flags` directive to the test. 

Thanks for you help on this!

cc @RalfJung related to your PR #55086

### CODE REVIEW

File: src/librustc_mir/transform/mod.rs [hunk 1]
```diff
@@ -155,17 +155,30 @@ pub trait MirPass {
                           mir: &mut Mir<'tcx>);
 }
 
-pub macro run_passes($tcx:ident, $mir:ident, $def_id:ident, $suite_index:expr; $($pass:expr,)*) {{
-    let suite_index: usize = $suite_index;
+pub macro run_passes(
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/mod.rs]: Unrelated: it'd be nice to move this out of a macro and into some kind of generic function. I don't really see any inherent difficulty in that. The functon could take a `vec![&dyn MirPass]` or else we could do some hancy h-list sort of thing (hint: seems unnecessary =)

**Review by nikomatsakis — APPROVED** [review]

File: src/librustc/mir/mod.rs [hunk 2]
```diff
@@ -69,13 +69,38 @@ impl<'tcx> HasLocalDecls<'tcx> for Mir<'tcx> {
...
+}
+
 /// Lowered representation of a single function.
 #[derive(Clone, RustcEncodable, RustcDecodable, Debug)]
 pub struct Mir<'tcx> {
     /// List of basic blocks. References to basic block use a newtyped index type `BasicBlock`
     /// that indexes into this vector.
     basic_blocks: IndexVec<BasicBlock, BasicBlockData<'tcx>>,
 
+    pub phase: MirPhase,
```
Comment (nikomatsakis) [inline src/librustc/mir/mod.rs]: It's probably a good idea to add a doc comment here. Something like:

---

Records how far through the "desugaring and optimization" process this particular MIR has traversed.

This is particularly useful when inlining, since in that context we instantiate the promoted constants and add them to our promoted vector -- but those promoted items have already been optimized, whereas ours have not. This field allows us to see the difference and forego optimization on the inlined promoted items.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Comment by wesleywiser** [comment]
Good ideas! I've implemented the feedback.

File: src/librustc_mir/transform/mod.rs [hunk 3]
```diff
@@ -155,53 +155,68 @@ pub trait MirPass {
...
 
-pub macro run_passes($tcx:ident, $mir:ident, $def_id:ident, $suite_index:expr; $($pass:expr,)*) {{
-    let suite_index: usize = $suite_index;
-    let run_passes = |mir: &mut _, promoted| {
+pub fn run_passes(
+    tcx: TyCtxt<'a, 'tcx, 'tcx>,
+    mir: &mut Mir<'tcx>,
+    def_id: DefId,
+    mir_phase: MirPhase,
+    passes: &[&dyn MirPass]) {
```
Comment (nikomatsakis) [inline src/librustc_mir/transform/mod.rs]: Nit: rustfmt would put the `) {` on the next line (with a trailing comma here)

**Review by nikomatsakis — APPROVED** [review]
r=me

File: src/librustc_mir/transform/mod.rs (hunk 3 above)
Comment (wesleywiser) [reply src/librustc_mir/transform/mod.rs]: Ah I was unsure of the convention here.

**Comment by wesleywiser** [comment]
Is it worth getting a perf run on these changes? I'm unsure of what the impact might be. It's probably small though...

**Comment by wesleywiser** [comment]
@bors try

For perf run, if we want that

**Comment by nikomatsakis** [comment]
@wesleywiser it is not

File: src/librustc/mir/mod.rs [hunk 4]
```diff
@@ -69,13 +69,43 @@ impl<'tcx> HasLocalDecls<'tcx> for Mir<'tcx> {
...
+    Const,
+    Validated,
+    Optimized,
+}
+
+impl MirPhase {
+    /// Gets the index of the current MirPhase within the set of all MirPhases.
+    pub fn phase_index(&self) -> usize {
+        match self {
+            MirPhase::Build => 0,
```
Comment (bjorn3) [inline src/librustc/mir/mod.rs]: Could you use `self as usize` instead of matching?

Comment (RalfJung) [reply src/librustc/mir/mod.rs]: But then please assign the discriminants explicitly.

Comment (wesleywiser) [reply src/librustc/mir/mod.rs]: Sure, I can change that.
