### PR TITLE
Always make tuple elements a coercion site

### LINKED ISSUE #112856: tuple elements are not considered a coercion site
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0f8eb4d18cb66ef70cdc3c373b7bdb7d)

### I tried this code:

```rust
fn main() {
    let a = if true {
        ((), todo!())
    } else {
        ((), ())
    };
}
```

### I expected to see this happen:
Code compiles, runs, and panics.
`a` has type `((), ())`.

### Instead, this happened:
```
   Compiling example v0.1.0 (/tmp/exmaple)
warning: unreachable expression
 --> src/main.rs:3:9
  |
3 |         ((), todo!())
  |         ^^^^^-------^
  |         |    |
  |         |    any code following this expression is unreachable
  |         unreachable expression
  |
  = note: `#[warn(unreachable_code)]` on by default

error[E0308]: `if` and `else` have incompatible types
 --> src/main.rs:5:9
  |
2 |       let a = if true {
  |  _____________-
3 | |         ((), todo!())
  | |         ------------- expected because of this
4 | |     } else {
5 | |         ((), ())
  | |         ^^^^^^^^ expected `((), !)`, found `((), ())`
6 | |     };
  | |_____- `if` and `else` have incompatible types
  |
  = note: expected tuple `((), !)`
             found tuple `((), ())`

For more information about this error, try `rustc --explain E0308`.
warning: `example` (bin "example") generated 1 warning
error: could not compile `example` (bin "example") due to previous error; 1 warning emitted
```
### The following changes have no effect:
* Removing `let a = `.
* Changing `true` to some runtime-only condition.
* Swapping the two branches.
* Replacing `if`-`else` with `match`.
* Swapping `todo!()` and `()` inside of the tuple.
* Replacing `todo!()` with `loop{}` or `std::process::exit(0)`.
* Replacing `todo!()` with a call to a function returning `std::convert::Infallible` (though this makes the warning about the unreachable code go away).
* Using `u8` or any other "normal" type instead of `()`.

### The following changes make the error go away.
* ```rust
  let x = todo!();
  ((), x)
  ```
* ```rust
  fn foo() -> () { todo!() }
  ((), foo())
  ```
* ```rust
  let foo = || todo!();
  ((), foo())
  ```
* ```rust
  ((), (||todo!())())
  ```

### Meta
`rustc --version --verbose`:
```rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```
Same on nightly and beta.

Must be related to #35121.

### PR DESCRIPTION
**Pull request by WaffleLapkin**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/147834)*

Previously we only used `check_expr_coercible_to_type` if we had an expectation (using `check_expr_with_expectation(NoExpectation)` otherwise). Normally that'd be fine, because without an expectation we can't insert a coercion anyway. However, for the case of never-to-any coercion specifically, we _do_ insert it eagerly, so this prevents some code from compiling, for example:

```rust
((),) = (loop {},);
```

With this PR we are always using `check_expr_coercible_to_type` (using an infer var if there is no expectation), which allows slightly more code to compile.

Fixes rust-lang/rust#112856

r? BoxyUwU

### CODE REVIEW

File: compiler/rustc_middle/src/ty/sty.rs [hunk 1]
```diff
@@ -1570,6 +1571,15 @@ impl<'tcx> Ty<'tcx> {
         }
     }
 
+    /// Returns a list of tuple type arguments, or `None` if `self` isn't a tuple.
+    #[inline]
+    pub fn tuple(self) -> Option<&'tcx List<Ty<'tcx>>> {
```
Comment (BoxyUwU) [inline compiler/rustc_middle/src/ty/sty.rs]:
```suggestion
    pub fn opt_tuple_fields(self) -> Option<&'tcx List<Ty<'tcx>>> {
```
seems like it does the same thing as `tuple_fields` it just doesnt panic

File: tests/ui/tuple/coercion.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+    let _: ((),) = x;
+
+    let _: (&[u8],) = (&[],);
+
+    // This one can't work without a redesign on the coercion system.
+    // We currently only eagerly add never-to-any coercions, not any others.
+    // Thus, because we don't have an expectation when typechecking `&[]`,
+    // we don't add a coercion => this doesn't work.
+    let y = (&[],);
+    let _: (&[u8],) = y; //~ error: mismatched types
```
Comment (BoxyUwU) [inline tests/ui/tuple/coercion.rs]: can you split the failing cases out to a different test so that the working stuff can be marked `// @check-pass` . It's also nice because this change probably needs an FCP because we start allowing more code to compile so having a simple "this is the test that now passes" is nice

**Comment by BoxyUwU** [comment]
@craterbot check

File: compiler/rustc_middle/src/ty/sty.rs (hunk 1 above)
Comment (WaffleLapkin) [reply compiler/rustc_middle/src/ty/sty.rs]: That is indeed the case, is there a problem with that? In the code I wrote I found this a lot more convenient than checking the type first.

File: tests/ui/tuple/coercion.rs (hunk 2 above)
Comment (WaffleLapkin) [reply tests/ui/tuple/coercion.rs]: I've split the tests

File: compiler/rustc_middle/src/ty/sty.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_middle/src/ty/sty.rs]: no it's fine I just found the differences in the names doesn't really reflect the differences in behaviour

Comment (WaffleLapkin) [reply compiler/rustc_middle/src/ty/sty.rs]: If you have a better idea for the names I can rename them

Comment (BoxyUwU) [reply compiler/rustc_middle/src/ty/sty.rs]: i suggested a different name already :P

Comment (WaffleLapkin) [reply compiler/rustc_middle/src/ty/sty.rs]: 🤦🏻 

I swear I sleep at night sometimes

**Comment by WaffleLapkin** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-147834/retry-regressed-list.txt

**Comment by BoxyUwU** [comment]
@rfcbot concern investigate and migrate broken crate

**Comment by WaffleLapkin** [comment]
@bors r=BoxyUwU

The FCP was blocked for a while, everyone had enough time to raise concerns. Agreed with boxy that this doesn't have to wait any longer.
