### PR TITLE
Fix "new trace_macros doesn't work if there's an error during expansion"

### LINKED ISSUE #43493: new trace_macros doesn't work if there's an error during expansion
The new trace_macros has much better output, but it has regressed in functionality! The old trace_macros could be used to debug macro expansion. Example using rustc 1.6.0:

```
$ cargo +1.6.0 script -u trace_macros -e 'trace_macros!(true); macro_rules! m { (x $($t:tt)*) => { m!() } } m!(foo);'
   Compiling expr v0.1.0 (file:///Users/alex/.cargo/.cargo/script-cache/expr-634e13f197b6cae5)
m! { foo }
.cargo/.cargo/script-cache/expr-634e13f197b6cae5/expr.rs:11:81: 11:84 error: no rules expected the token `foo`
.cargo/.cargo/script-cache/expr-634e13f197b6cae5/expr.rs:11     match {trace_macros!(true); macro_rules! m { (x $($t:tt)*) => { m!() } } m!(foo);} {
                                                                                                                                            ^~~
Could not compile `expr`.
```

OK, you can see `m!(foo)` was invoked, and then it didn't match so there's an error.

Now with current rustc (all channels):

```
$ cargo script -u trace_macros -e 'trace_macros!(true); macro_rules! m { (x $($t:tt)*) => { m!() } } m!(foo);'
   Compiling expr v0.1.0 (file:///Users/alex/.cargo/.cargo/script-cache/expr-634e13f197b6cae5)
error: no rules expected the token `foo`
  --> .cargo/.cargo/script-cache/expr-634e13f197b6cae5/expr.rs:11:81
   |
11 |     match {trace_macros!(true); macro_rules! m { (x $($t:tt)*) => { m!() } } m!(foo);} {
   |                                                                                 ^^^

error: Could not compile `expr`.
```

You no longer get to see the chain of expansions leading up to the error. This typically occurs much deeper in a string of recursive macros, making debugging much harder.

cc #41520 @estebank @nikomatsakis

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #43493

### CODE REVIEW

**Comment by durka** [comment]
Let's work up a test?

**Comment by bjorn3** [comment]
Will do it tommorrow when I have more time to build rust

File: src/libsyntax/ext/expand.rs [hunk 1]
```diff
@@ -439,11 +440,13 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
             }
             ProcMacroDerive(..) | BuiltinDerive(..) => {
                 self.cx.span_err(attr.span, &format!("`{}` is a derive mode", attr.path));
+                self.cx.trace_macros_diag();
                 kind.dummy(attr.span)
```
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: I don't think we need `self.cx.trace_macros_diag();` when we're not panicking immediately after.

**Comment by shepmaster** [comment]
@bjorn3 A gentle reminder - it's been 7 days since your last message!

**Comment by bjorn3** [comment]
@shepmaster Working on it.

**Comment by bjorn3** [comment]
@jseyfried: Should be working.

Travis job #58449.5 failed: `The command "eval git fetch origin +refs/pull/44088/merge: " failed 3 times.`

File: src/libsyntax/ext/base.rs [hunk 2]
```diff
@@ -792,14 +792,16 @@ impl<'a> ExtCtxt<'a> {
...
+    pub fn trace_macros_diag(&mut self) {
         for (sp, notes) in self.expansions.iter() {
             let mut db = self.parse_sess.span_diagnostic.span_note_diag(*sp, "trace_macro");
             for note in notes {
                 db.note(note);
             }
             db.emit();
         }
+        // Fixme: does this result in errors?
+        self.expansions.clear();
```
Comment (jseyfried) [inline src/libsyntax/ext/base.rs]: Why is this necessary?

File: src/libsyntax/ext/expand.rs [hunk 3]
```diff
@@ -439,11 +440,13 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
...
             }
             _ => {
                 let msg = &format!("macro `{}` may not be used in attributes", attr.path);
                 self.cx.span_err(attr.span, msg);
+                self.cx.trace_macros_diag();
```
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Why do we need this here? This error shouldn't abort expansion.

File: src/libsyntax/ext/expand.rs [hunk 4]
```diff
@@ -482,6 +485,7 @@ impl<'a, 'b> MacroExpander<'a, 'b> {
                 if let Err(msg) = validate_and_set_expn_info(def_span.map(|(_, s)| s),
                                                              false, false) {
                     self.cx.span_err(path.span, &msg);
+                    self.cx.trace_macros_diag();
```
Comment (jseyfried) [inline src/libsyntax/ext/expand.rs]: Also this, and the most of the others in this file.
We use dummy expansions (`kind.dummy(span)`) so that we don't have to abort.

File: src/libsyntax/ext/tt/macro_rules.rs [hunk 5]
```diff
@@ -172,7 +172,9 @@ fn generic_extension<'cx>(cx: &'cx mut ExtCtxt,
     }
 
     let best_fail_msg = parse_failure_msg(best_fail_tok.expect("ran no matchers"));
-    cx.span_fatal(best_fail_spot.substitute_dummy(sp), &best_fail_msg);
+    cx.span_err(best_fail_spot.substitute_dummy(sp), &best_fail_msg);
+    cx.trace_macros_diag();
+    DummyResult::any(sp)
```
Comment (jseyfried) [inline src/libsyntax/ext/tt/macro_rules.rs]: With `DummyResult` we shouldn't need `cx.trace_macros_diag();` here.

**Review by jseyfried — COMMENTED** [review]
LGTM other than what appears to be excessive `self.cx.trace_macros_diag();`.

File: src/libsyntax/ext/base.rs (hunk 2 above)
Comment (bjorn3) [reply src/libsyntax/ext/base.rs]: As this prevent reporting an expansion trace twice or more

File: src/libsyntax/ext/expand.rs (hunk 3 above)
Comment (bjorn3) [reply src/libsyntax/ext/expand.rs]: The order of the trace notes is unstable otherwise.

File: src/libsyntax/ext/expand.rs (hunk 4 above)
Comment (bjorn3) [reply src/libsyntax/ext/expand.rs]: Same here

File: src/libsyntax/ext/tt/macro_rules.rs (hunk 5 above)
Comment (bjorn3) [reply src/libsyntax/ext/tt/macro_rules.rs]: Same here

**Comment by bjorn3** [comment]
ping @jseyfried

**Comment by jseyfried** [comment]
@bjorn3 Ok, makes sense.
@bors r+

**Comment by kennytm** [comment]
@bors p=-1 retry 

Why are you still appearing in the queue
