### PR TITLE
Resolve enum field visibility correctly

### LINKED ISSUE #79593: Diagnostic regression (1.47 -> 1.48): public enum fields incorrectly described as "inaccessible fields".
Test example ([try on playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0d6db204597d38ebd9bdfd3e104e669)):
```rust
mod foo {
    pub struct Pub { private: () }

    pub enum Enum {
        Variant { x: (), y: () },
        Other
    }
    
    fn correct() {
        Pub {};
        Enum::Variant { x: () };
    }
}

fn correct() {
    foo::Pub {};
}

fn wrong() {
    foo::Enum::Variant { x: () };
}
```

Only `foo::Pub {}` in the top level `correct` should say "cannot construct ... due to inaccessible fields", the other 3 errors should be "missing field ... in initializer", but it seems like it's treating the `enum` field as private (even though it inherits `pub` from the `enum`).

The "cannot construct ... due to inaccessible fields" error seems to be new in 1.48, as part of #76524, and unmodified since.

It's using `field.vis.is_accessible_from(...)` which seems correct, but it's possible `enum` fields are incapable of giving the right result, if they don't track the `enum`'s own privacy (and they only know they inherit it, whatever *it* is).

cc @davidtwco @estebank

### PR DESCRIPTION
**Pull request by camelid**
Fixes #79593. :tada:

Previously, this code treated enum fields' visibility as if they were
struct fields. However, that's not correct because the visibility of a
struct field with `ast::VisibilityKind::Inherited` is private to the
module it's defined in, whereas the visibility of an *enum* field with
`ast::VisibilityKind::Inherited` is the visibility of the enum it
belongs to.

### CODE REVIEW

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -258,7 +258,18 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
+                    // Anything in an enum has the visibility of the enum.
+                    Ok(*self
+                        .r
+                        .visibilities
+                        .get(&self.parent_scope.module.normal_ancestor_id.expect_local())
+                        .unwrap())
+                } else {
+                    // If it's not in an enum, its visibility is restricted to the trait or module
+                    // that it's defined in.
+                    Ok(ty::Visibility::Restricted(self.parent_scope.module.normal_ancestor_id))
```
Comment (camelid) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:271]: Should this be:

```suggestion
                    Ok(ty::Visibility::Restricted(self.parent_scope.module.nearest_item_scope().normal_ancestor_id))
```

instead? It seems doing that will restrict trait items' visibility to the module the trait is defined in, whereas not calling it will restrict their visibility to the trait.

File: src/test/ui/issues/issue-79593.stderr [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+LL |         Enum::Variant { x: () };
+   |         ^^^^^^^^^^^^^ missing `y`
+
+error: cannot construct `Pub` with struct literal syntax due to inaccessible fields
+  --> $DIR/issue-79593.rs:18:5
+   |
+LL |     foo::Pub {};
+   |     ^^^^^^^^
+
+error[E0063]: missing field `y` in initializer of `Enum`
```
Comment (camelid) [inline src/test/ui/issues/issue-79593.stderr:19]: This should probably print

```
error[E0063]: missing field `y` in initializer of `Enum::Variant`
```

but that's unrelated to this change.

(I'm leaving this as a todo for myself.)

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 3]
```diff
@@ -258,7 +258,18 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
             }
             ast::VisibilityKind::Inherited => {
-                Ok(ty::Visibility::Restricted(parent_scope.module.normal_ancestor_id))
+                if self.parent_scope.module.kind.is_enum() {
+                    // Anything in an enum has the visibility of the enum.
+                    Ok(*self
+                        .r
+                        .visibilities
+                        .get(&self.parent_scope.module.normal_ancestor_id.expect_local())
+                        .unwrap())
```
Comment (jyn514) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:267]: nit: rustfmt really mangles this
```suggestion
                    // Anything in an enum has the visibility of the enum.
                    let parent_enum = self.parent_scope.module.normal_ancestor_id.expect_local();
                    Ok(*self.r.visibilities.get(&parent_enum).unwrap())
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 4]
```diff
@@ -1462,6 +1473,14 @@ impl<'a, 'b> Visitor<'b> for BuildReducedGraphVisitor<'a, 'b> {
...
         } else {
             let vis = self.resolve_visibility(&sf.vis);
+            debug!(
+                "BuildReducedGraphVisitor::visit_struct_field: self.parent_scope={:?}",
+                self.parent_scope
+            );
+            debug!(
+                "BuildReducedGraphVisitor::visit_struct_field: sf={:?}, sf.vis={:?}, vis={:?}",
+                &sf, &sf.vis, &vis
+            );
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:1483]: Could you remove this temporary debugging code?

File: compiler/rustc_resolve/src/lib.rs [hunk 5]
```diff
@@ -435,6 +436,11 @@ impl ModuleKind {
             ModuleKind::Def(.., name) => Some(*name),
         }
     }
+
+    /// Check if the module is an enum.
+    pub fn is_enum(&self) -> bool {
+        matches!(self, ModuleKind::Def(DefKind::Enum, _, _))
+    }
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:443]: Could you avoid this trivial method that is used once?

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 6]
```diff
@@ -258,7 +258,18 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
                 Ok(ty::Visibility::Restricted(DefId::local(CRATE_DEF_INDEX)))
             }
             ast::VisibilityKind::Inherited => {
-                Ok(ty::Visibility::Restricted(parent_scope.module.normal_ancestor_id))
+                if self.parent_scope.module.kind.is_enum() {
+                    // Anything in an enum has the visibility of the enum.
+                    Ok(*self
+                        .r
+                        .visibilities
+                        .get(&self.parent_scope.module.normal_ancestor_id.expect_local())
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:266]:
```suggestion
                        visibilities[&self.parent_scope.module.def_id().unwrap().expect_local()]
```
By using `normal_ancestor_id` you don't use visibility of enum, but rather visibility of its parent `mod` item.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 7]
```diff
@@ -258,7 +258,18 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
                 Ok(ty::Visibility::Restricted(DefId::local(CRATE_DEF_INDEX)))
             }
             ast::VisibilityKind::Inherited => {
-                Ok(ty::Visibility::Restricted(parent_scope.module.normal_ancestor_id))
+                if self.parent_scope.module.kind.is_enum() {
+                    // Anything in an enum has the visibility of the enum.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:262]:
```suggestion
                    // Any inherited visibility resolved directly inside an enum (e.g. variants or fields) inherits from the visibility of the enum.
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 8]
```diff
@@ -258,7 +258,18 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
+                    Ok(*self
+                        .r
+                        .visibilities
+                        .get(&self.parent_scope.module.normal_ancestor_id.expect_local())
+                        .unwrap())
+                } else {
+                    // If it's not in an enum, its visibility is restricted to the trait or module
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:269]:
```suggestion
                    // If it's not in an enum, the visibility is restricted to the current `mod` item.
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 4 above)
Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1483]: I had more debugging code that I did remove; i thought this might be helpful for debugging in the future.

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (camelid) [reply compiler/rustc_resolve/src/lib.rs:443]: I would rather keep it as it makes the code easier to understand and it will make it easier in the future if `ModuleKind` or `DefKind` are changed.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 6 above)
Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:266]: Ah, okay! I wasn't sure what it did.

Related to this, what does `nearest_item_scope()` do? (See my comment at https://github.com/rust-lang/rust/pull/79956#discussion_r541495180.)

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 8 above)
Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:269]: I think the way it is now is clearer.

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (camelid) [reply compiler/rustc_resolve/src/lib.rs:443]: Also, it's used once *here*, but it's something that will very possibly be useful later.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 4 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1483]: >I thought this might be helpful for debugging in the future.

It really won't be. (And in the unlikely case if it will, it could be added and removed again.)

Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1483]: Okay, I'll remove it then.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 8 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:269]: Now it's incorrect, `normal_ancestor_id` does not refer to traits and "module" is ambiguous in resolve context (it can be e.g. an unnamed block), while `normal_ancestor_id` refers to `mod` items specifically.

Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:269]: Oh, I see what you mean.

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 9]
```diff
@@ -258,7 +258,15 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
                 Ok(ty::Visibility::Restricted(DefId::local(CRATE_DEF_INDEX)))
             }
             ast::VisibilityKind::Inherited => {
-                Ok(ty::Visibility::Restricted(parent_scope.module.normal_ancestor_id))
+                if self.parent_scope.module.kind.is_enum() {
```
Comment (camelid) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:261]: How should this behave for `union`s (and other items)? I think they should behave like `struct`s, so this should be correct, but I'm not sure.

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:443]: This is pretty much the same situation as https://github.com/rust-lang/rust/pull/79956#discussion_r541699385.
"Later" does not exist right now, if it ever materializes the function could be added.

I'll just remove it when I touch this code next time (which is soon, because visibilities in resolve have some other issues), so I'd prefer it to not be introduced in the first place.

Comment (camelid) [reply compiler/rustc_resolve/src/lib.rs:443]: I will remove it if you feel strongly about it, but there are already seem to be similar methods on `ModuleData`:

```rust
    // `self` resolves to the first module ancestor that `is_normal`.
    fn is_normal(&self) -> bool {
        matches!(self.kind, ModuleKind::Def(DefKind::Mod, _, _))
    }

    fn is_trait(&self) -> bool {
        matches!(self.kind, ModuleKind::Def(DefKind::Trait, _, _))
    }
```

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 9 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:261]: Yes for fields in unions and structs the current behavior should be correct (and we don't have other fields besides them and fields in variants).

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 3 above)
Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs]: Fixed in 26886f8.

**Comment by petrochenkov** [comment]
Could you also squashing commits after addressing the comments?

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 10]
```diff
@@ -258,7 +258,15 @@ impl<'a, 'b> BuildReducedGraphVisitor<'a, 'b> {
...
+                    // Any inherited visibility resolved directly inside an enum (e.g. variants or fields) inherits from the visibility of the enum.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:262]: (Tidy cannot work on rustfmt-controlled code, unfortunately, but keeping 100-character line limit is still reasonable.)

File: compiler/rustc_resolve/src/lib.rs (hunk 5 above)
Comment (camelid) [reply compiler/rustc_resolve/src/lib.rs:443]: So do you still feel I should remove it?

Comment (petrochenkov) [reply compiler/rustc_resolve/src/lib.rs:443]: Yes, I thing removing is better.

File: compiler/rustc_resolve/src/build_reduced_graph.rs (hunk 4 above)
Comment (camelid) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:1481]: (I'm going to remove it after my build finishes.)

**Comment by camelid** [comment]
I believe I have addressed all of your comments now.

**Comment by petrochenkov** [comment]
Thanks!
r=me after squashing commits.

**Comment by camelid** [comment]
Nominating for beta-backport since this error comes up fairly frequently and the unfixed version is very confusing and annoying, and it's likely that it's even more so for newcomers. (The issue this fixed was P-high because of the reasons I listed.)

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/21097weeklymeeting2020121754818.html#220256344) in T-compiler meeting, declined to backport.

@rustbot modify labels: -beta-nominated
