### PR TITLE
rustc: Fix regression where jemalloc isn't used

### LINKED ISSUE #57115: Up to 7% regression in recent rollup
Noticed [here](https://github.com/rust-lang/rust/pull/57094#issuecomment-449778938) it looks like something in that rollup has caused a blanket regression in compile time instruction counts while also simultaneously improving memory. The [current hypothesis](https://github.com/rust-lang/rust/pull/57094#issuecomment-449779215) is that https://github.com/rust-lang/rust/pull/56986 is incorrect and disabled jemalloc entirely.

Another hypothesis is that https://github.com/rust-lang/rust/pull/56944 had a really weird effect on the build. 

In any case, we should investigate!

### PR DESCRIPTION
**Pull request by alexcrichton**
In #56986 the linkage of jemalloc to the compiler was switched from the
driver library to the rustc binary to ensure that only rustc itself uses
jemalloc. In doing so, however, it turns out jemalloc wasn't actually
linked in at all! None of the symbols were referenced so the static
library wasn't used. This means that jemalloc wasn't pulled in at all.

This commit performs a bit of a dance to reference jemalloc symbols,
attempting to pull it in despite LLVM's optimizations.

Closes #57115

### CODE REVIEW

File: src/rustc/rustc.rs [hunk 1]
```diff
@@ -11,17 +10,32 @@
...
+    // pull it in we need to actually reference its symbols for it to get
+    // linked. The two crates we link to here, std and rustc_driver, are both
+    // dynamic libraries. That means to pull in jemalloc we need to actually
+    // reference allocation symbols one way or another (as this file is the only
+    // object code in the rustc executable).
+    //
+    // As such, here's an interprative dance to slip under LLVM's radar yet
+    // please the linker.
+    #[cfg(feature = "jemalloc-sys")] {
+        if std::env::var("__RUSTC_NEVER_PRESENT_ENV_VAR").is_ok() {
```
Comment (nikomatsakis) [inline src/rustc/rustc.rs]: what is the point of this environment variable? oh, I guess it's to make dead code that will always appear live?

File: src/rustc/rustc.rs [hunk 2]
```diff
@@ -11,17 +10,32 @@
...
+            unsafe {
+                jemalloc_sys::calloc(1, 4);
+                jemalloc_sys::posix_memalign(&mut std::ptr::null_mut(), 1, 10);
+                jemalloc_sys::aligned_alloc(1, 10);
```
Comment (nikomatsakis) [inline src/rustc/rustc.rs]: I confess this goes over my head. I guess that my keeping these calls live, we keep things linked in, and then calls to `calloc` and so forth wind up invoking jemalloc and not the system allocator?

File: src/rustc/rustc.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/rustc/rustc.rs]: I feel like that merits a comment =)

**Comment by alexcrichton** [comment]
@rust-timer build 3550c27b5e8a9ea9e692e701861714886a4c22ca

File: src/rustc/rustc.rs (hunk 1 above)
Comment (alexcrichton) [reply src/rustc/rustc.rs]: Sure thing, I'll add a comment once I confirm this fixes the issue

File: src/rustc/rustc.rs (hunk 2 above)
Comment (alexcrichton) [reply src/rustc/rustc.rs]: Right yeah, we need to give the linker a reason to actually statically link jemalloc, which means we need to reference allocation symbols which will get satisfied by jemalloc's library.

Comment (petrochenkov) [reply src/rustc/rustc.rs]: @alexcrichton 
Hmm, this reminded me of one question I wanted to ask.
Static libraries linked through command line `-l static=mylib` are wrapped into `--whole-archive` (which would obviate the need to add these dummy uses for otherwise unused symbols).
Static libraries linked from source with `#[link(name = "test", kind = "static")]`, on the other hand, are not wrapped into `--whole-archive`.
What's the history behind this?

Comment (petrochenkov) [reply src/rustc/rustc.rs]: Hm, actually `jemalloc-sys` links jemalloc though command line, then why are the symbols lost?
Do I understand correctly that static `jemalloc` is linked into `jemalloc-sys.rlib` (?) (it uses `static`, rather than `static-nobundle`) and the symbols are not lost at *that* moment.
The symbols are lost later than static `jemalloc-sys` is linked into rustc executable, and `--whole-archive` is not used at this time?

**Comment by nikomatsakis** [comment]
So my take on this:

- The code itself seems "obviously" "fine" (as in, not going go to break things)
- But oh god what a hack

It seems surprising to me that there is no more elegant way to do this. 

I'm willing therefore to r+ though I might prefer if somebody else who was closer to the whole linking story did so, since maybe they will have another idea. (e.g., @petrochenkov is asking good questions [here](https://github.com/rust-lang/rust/pull/57287#discussion_r245052663)).

**Comment by nikomatsakis** [comment]
Also, the try build is ready, not sure what use you had in mind, @alexcrichton ?

**Comment by alexcrichton** [comment]
The most elegant way to do this without looking like a hack is probably to use linker flags directly, but actually doing that in Rust would look like more of a hack unfortunately. We don't have that level of control over how things are built to know what's where on the command line, so I've found symbol references to be much more flexible.

Also sorry should have mentioned, but I'd like to do a perf run to confirm that this actually fixes the regression this claims to fix.

File: src/rustc/rustc.rs (hunk 2 above)
Comment (alexcrichton) [reply src/rustc/rustc.rs]: I think the `--whole-archive` with `-l` vs `#[link]` is probably a bug actually? I wasn't aware of that behavior. Unfortunately though it wouldn't help in this case because jemalloc is included in `libjemalloc_sys.rlib` which isn't linked with `--whole-archive`

(we don't link rlibs with `--whole-archive`)

>  Do I understand correctly that static jemalloc is merged into jemalloc-sys.rlib (it uses static, rather than static-nobundle) and the symbols are not lost at that moment.

correct

>  The symbols are lost later when static jemalloc-sys is linked into rustc executable, and --whole-archive is not used at this time?

correct!

**Comment by alexcrichton** [comment]
(I'd also like to add more comments in the code about the hacks here code-wise, was just waiting on perf)

**Comment by alexcrichton** [comment]
Yay regression is indeed fixed!

I've added some comments, and perhaps in addition to @petrochenkov @michaelwoerister may want to take a look?

File: src/rustc/rustc.rs (hunk 1 above)
Comment (nagisa) [reply src/rustc/rustc.rs]: Wouldn't something like

```
#[used]
static FOO: fn(...) = jemalloc_sys::calloc;
// etc
```

be better/cleaner/less hacky?

Comment (alexcrichton) [reply src/rustc/rustc.rs]: @nagisa an excellent idea!

**Comment by petrochenkov** [comment]
Other crates that want to use static jemalloc will have to do something like this as well?

**Comment by alexcrichton** [comment]
In theory, yes, but in practice it isn't much of a problem. Almost all Rust code that isn't rustc is built with all Rust code statically linked, so the references to the jemalloc symbols will come through things like libstd or just bland `Vec::new`

**Comment by petrochenkov** [comment]
@alexcrichton 
>I think the --whole-archive with -l vs #[link] is probably a bug actually?

Some update: apparently I misremembered the details, command line and attribute behave identically (that's good).

The difference was that `static` uses `whole-archive`, but `static-nobundle` doesn't.
That's also not entirely correct since bundling and `whole-archive`-ness are somewhat independent.
For example, for linking jemalloc in this case we'd want exactly nobundle + whole-archive.

**Comment by alexcrichton** [comment]
From my experience at least creating a composable system where libraires can specify linkage and whatnot is insanely hard to say the least and likely downright impossible. We do our best when we can and otherwise just try to fix things when a bug comes up. We're definitely not consistent though :(

**Comment by nikomatsakis** [comment]
@bors r+

Since it seems like @petrochenkov doesn't have any blocking objections, I'm going to r+ here for  now. Feel free to r- or r? someone else though.
