### PR TITLE
Deduplicate ParamCandidates with the same value except for bound vars

### LINKED ISSUE #84398: Type annotations needed error on definition site
Hello

After upgrading nightly rustc, I'm getting a lot of type inference errors on code that was compiling fine previously. Moreover, these are not at the call site, but at the definition site, so there doesn't seem to be any place to put any type annotations, like this:

```
    --> src/spirit.rs:996:1
     |
996  | / impl<O, C> SpiritBuilder for Builder<O, C>
997  | | where
998  | |     Self::Config: DeserializeOwned + Send + Sync + 'static,
999  | |     Self::Opts: StructOpt + Sync + Send + 'static,
...    |
1108 | |     }
1109 | | }
     | |_^ cannot infer type for type parameter `C`
```

It spills more kinds of errors that make little sense, but I have the impression these will have a common cause:

```
error[E0277]: `C` cannot be shared between threads safely
   --> src/spirit.rs:998:45
    |
998 |     Self::Config: DeserializeOwned + Send + Sync + 'static,
    |                                             ^^^^ `C` cannot be shared between threads safely
```

The problematic code is both released on crates.io (crate spirit, version 0.4.16, but I expect that to be happening through most of the history of the crate), and in master (https://github.com/vorner/spirit/commit/1495c1cdef17663e8f847f037abeceb37f310fad).

I think this is a regression, as it was compiling previously.

It compiles fine with older nightly (and stable is fine way back, this particular code is looking mostly the same for some 2 years or more):

```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
```

Breaks with

```
rustc 1.53.0-nightly (6df26f897 2021-04-20)
binary: rustc
commit-hash: 6df26f897cffb2d86880544bb451c6b5f8509b2d
commit-date: 2021-04-20
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

(Unfortunately, I haven't been keeping fully up to date recently, so I don't have a smaller range).

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #84398

This is kind of a hack. I wonder if we can get other types of candidates that are the same except for bound vars. This won't be a problem with Chalk, since we don't really need to know that there are two different "candidates" if they both give the same final substitution.

r? @nikomatsakis

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 1]
```diff
@@ -1361,7 +1361,17 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-                if other.value == victim.value && victim.constness == Constness::NotConst {
+                let value_same_except_bound_vars = other.value.skip_binder()
+                    == victim.value.skip_binder()
+                    && !other.value.skip_binder().has_escaping_bound_vars();
+                if value_same_except_bound_vars {
+                    // See issue #84398. In short, we can generate multiple ParamCandidates which are
+                    // the same except for unused bound vars. Just pick the current one (the should
+                    // both evaluate to the same answer). This is probably best characterized as a
+                    // "hack", since we might prefer to just do our best to *not* create essentially
+                    // duplicate candidates in the first place.
```
Comment (nikomatsakis) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs:1372]: maybe we want to pick the one with fewer bound vars? it'd be nice to be more deterministic here

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Comment by pietroalbini** [comment]
This fixes a regression that slipped into beta 1.53, nominating for backport.

**Comment by jackh726** [comment]
Status on this: discussed with @nikomatsakis a change he'd like to see here. Just have to get some time to implement it.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/87937weekly2021050654818.html#237663853). Meanwhile a crater run could help assessing if this PR has any breakage.

@rustbot label +beta-accepted
