### PR TITLE
Fix suggestion to slice if scrutinee is a `Result` or `Option`

### LINKED ISSUE #91328: Incorrect slicing suggestion for pattern matching against a `Vec` inside a `Result` or `Option`
When trying to pattern match against a `Vec` inside a `Result` or `Option`, an incorrect suggestion is given, that says to append `[..]` to the variable to slice it, which won't work since the variable is of type `Result` / `Option` rather than being a `Vec` itself.

Instead one option is to use `.as_deref()` on the `Result`:
https://doc.rust-lang.org/std/result/enum.Result.html#method.as_deref

Given the following code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1e834c61673228c36f08e8c294efc68d

```rust
fn main() {
    let s = "1:2";
    let result: Result<Vec<u64>, _> = s.split(':').map(str::parse).collect();

    match result {
        Ok([first, second]) => {
            println!("first: {}, second: {}", first, second);
        }
        _ => {}
    }
}
```

The current output is:

```
error[E0529]: expected an array or slice, found `Vec<u64>`
 --> src/main.rs:6:12
  |
5 |     match result {
  |           ------ help: consider slicing here: `result[..]`
6 |         Ok([first, second]) => {
  |            ^^^^^^^^^^^^^^^ pattern cannot match with input type `Vec<u64>`
```

Ideally the output should look like:

```
error[E0529]: expected an array or slice, found `Vec<u64>`
 --> src/main.rs:6:12
  |
5 |     match result {
  |           ------ help: consider converting the contents of the Result to a slice using: `result.as_deref()`
6 |         Ok([first, second]) => {
  |            ^^^^^^^^^^^^^^^ pattern cannot match with input type `Vec<u64>`
```

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #91328.

### CODE REVIEW

File: compiler/rustc_typeck/src/check/pat.rs [hunk 1]
```diff
@@ -2032,12 +2032,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            err.span_suggestion(
+                                span,
+                                "consider using `as_deref` here",
+                                format!("{}.as_deref()", snippet),
+                                Applicability::MaybeIncorrect,
+                            );
+                            None
+                        }
+                        ty::Adt(adt_def, _)
+                            if self.tcx.is_diagnostic_item(sym::Vec, adt_def.did) =>
```
Comment (jackh726) [inline compiler/rustc_typeck/src/check/pat.rs:2050]: So...I think I'm learning something today about how Rust's `SliceIndex` works (at least, unless I've missed something). So...I guess when we do `a_vec[..]`, what's *actually* happening is there is an implicit deref: `(a_vec.deref())[..])` - because `SliceIndex` is only implemented for `slice`, then the implicit deref is basically "forced". (At least, I think this is the case...please someone correct me if I'm wrong.)

I bring this up because rather than checking for `Vec` exactly, we could check if the type impls `Deref<Target=X>`?

Of course, this could be done as followup. This looks good otherwise.

Comment (jackh726) [reply compiler/rustc_typeck/src/check/pat.rs:2050]: I guess we could in general be smarter above too for `Result<T>` to only suggest if `T: Deref<Target=X>`

File: src/test/ui/typeck/issue-91328.fixed [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// Regression test for issue #91328.
```
Comment (jackh726) [inline src/test/ui/typeck/issue-91328.fixed:1]: Might be nice to see examples where the type being matched is *not* a `Result<Vec<_>>` or  `Option<Vec<_>>`. I'm thinking straight `Vec<_>` or some other type that doesn't deref to slice. (Though, not wrapping in a `Result`/`Option` might be covered elsewhere)

**Review by jackh726 — APPROVED** [review]

File: src/test/ui/typeck/issue-91328.fixed (hunk 2 above)
Comment (jackh726) [reply src/test/ui/typeck/issue-91328.fixed:1]: Clarification: this is the only thing I'd like to see before this PR is merged, but doesn't *need* to block this PR.

Comment (FabianWolff) [reply src/test/ui/typeck/issue-91328.fixed:1]: I've added a test case with a match on a plain `Vec<_>` now (sorry for taking so long to get around to this...).

File: compiler/rustc_typeck/src/check/pat.rs (hunk 1 above)
Comment (FabianWolff) [reply compiler/rustc_typeck/src/check/pat.rs:2051]: Yes, that would be nicer, but I don't know how to check for such a trait bound here. Let's leave it to a follow-up (or do you know an easy way to implement this?).

Comment (jackh726) [reply compiler/rustc_typeck/src/check/pat.rs:2051]: Yes, let's leave this as a followup. Can you add a FIXME comment though?

**Comment by jackh726** [comment]
@bors delegate+ rollup

r=me with FIXME

**Comment by FabianWolff** [comment]
Done, thanks for reviewing this!

@bors r=jackh726

**Comment by ChayimFriedman2** [comment]
This still does not work with references:
```rust
pub fn foo(v: &Option<Vec<i32>>) {
    match v {
        Some([]) => {}
        _ => {}
    }
}
```
```
error[E0529]
 --> src/lib.rs:3:14
  |
2 |     match v {
  |           - help: consider slicing here: `v[..]`
3 |         Some([]) => {}
  |              ^^ pattern cannot match with input type `Vec<i32>`
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=765f516f1fe085014c256125a8e8a1ac).
