### PR TITLE
Don't emit `rustdoc::broken_intra_doc_links` for GitHub-flavored Markdown admonitions like `[!NOTE]`

### LINKED ISSUE #141866: Rustdoc reports `broken-intra-doc-links` for Github-flavored Markdown admonitions like `[!IMPORTANT]`
I tried this code:

```rust
#![doc = include_str!("../README.md")]
```

```markdown
> [!IMPORTANT]
> This is an important message
```

I expected to see this happen: Rustdoc at least generating documentation (perhaps not with specialized support for the `[!FOO]` syntax, but at least not error)

Instead, this happened: With `env RUSTFLAGS="-D warnings"`, rustdoc errored with `unresolved link to '!NOTICE'`

### Meta

`rustc --version --verbose`:
```
rustc 1.89.0-nightly (6f6971078 2025-05-28)
binary: rustc
commit-hash: 6f69710780d579b180ab38da4c1384d630f7bd31
commit-date: 2025-05-28
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.5
```

`rustdoc --version --verbose`:
```
rustdoc 1.89.0-nightly (6f6971078 2025-05-28)
binary: rustdoc
commit-hash: 6f69710780d579b180ab38da4c1384d630f7bd31
commit-date: 2025-05-28
host: x86_64-unknown-linux-gnu
release: 1.89.0-nightly
LLVM version: 20.1.5
```

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes rust-lang/rust#141866

### CODE REVIEW

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 1]
```diff
@@ -1013,11 +1014,18 @@ fn preprocess_link(
...
     // | no backtick  | ignore if url-like |    never ignore   |
     // |-------------------------------------------------------|
-    let ignore_urllike =
-        can_be_url || (ori_link.kind == LinkType::ShortcutUnknown && !ori_link.link.contains('`'));
+    let ignore_urllike = can_be_url || (is_shortcut_style && !ori_link.link.contains('`'));
     if ignore_urllike && should_ignore_link(path_str) {
         return None;
     }
+    // ignore github flavored markdown special blockquotes,
+    // such as [!NOTE] and [!IMPORTANT]
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: Could you elaborate the comment slightly noting that it's ~common for people to include_str the README.md of their GitHub repo?

I think we want to highlight that cuz rustdoc doesn't use GitHub-flavored Markdown and doesn't support GitHub-style admonitions.

Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: yeah, good point, will elaborate.

Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: alright, I expanded the documentation and also made sure that `[!]` is still parsed as a link to the never type.

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 2]
```diff
@@ -1013,11 +1014,25 @@ fn preprocess_link(
...
+    //
+    // rustdoc does not support github-flavored markdown,
+    // however it is a common pattern to add #[doc = include_str!("../README.md")] to the root of a crate,
+    // so we want to at least accept github-flavored markdown, even if it doesn't render perfectly.
+    //
+    // we do allow [!] as a link to the never type.
+    if is_shortcut_style
+        && ori_link.link.starts_with('!')
+        && ori_link.link.len() > 1
+        && ori_link.link[1..].chars().all(|c| c.is_ascii_alphabetic())
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]:
```suggestion
        && let Some(suffix) = ori_link.strip_prefix('!')
        && suffix.chars().all(|c| c.is_ascii_alphabetic())
```

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 3]
```diff
@@ -1013,11 +1014,25 @@ fn preprocess_link(
...
     // | no backtick  | ignore if url-like |    never ignore   |
     // |-------------------------------------------------------|
-    let ignore_urllike =
-        can_be_url || (ori_link.kind == LinkType::ShortcutUnknown && !ori_link.link.contains('`'));
+    let ignore_urllike = can_be_url || (is_shortcut_style && !ori_link.link.contains('`'));
     if ignore_urllike && should_ignore_link(path_str) {
         return None;
     }
+    // ignore github flavored markdown special blockquotes,
+    // such as [!NOTE] and [!IMPORTANT]
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]:
```suggestion
    // Ignore GitHub-flavored Markdown admonitions, such as `[!NOTE]` and `[!IMPORTANT]`.
```

They're called *admonitions*. The name originates from AsciiDoc (https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/) and to my knowledge GitHub actually doesn't document them anywhere (IINM, the only reference we have is here: https://github.com/orgs/community/discussions/16925) which is kinda odd but maybe they're mentioned in some official changelog somewhere?

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 4]
```diff
@@ -1013,11 +1014,25 @@ fn preprocess_link(
...
+    //
+    // rustdoc does not support github-flavored markdown,
```
Comment (fmease) [inline src/librustdoc/passes/collect_intra_doc_links.rs]: I'm sorry this is super nitpicky but could you capitalize all proper nouns according to their official stylization? So *github* to *GitHub* and *markdown* to *Markdown* (*rustdoc* remains as is because that's its stylization). Moreover could you surround the code snippets with backticks (`[!]` and the `include_str` one)?

That's just my strong personal preference >.< Much appreciation in advance.

File: tests/rustdoc-ui/intra-doc/github-flavored-blockquote.rs
Comment (fmease) [inline tests/rustdoc-ui/intra-doc/github-flavored-blockquote.rs:1]: `tests/rustdoc-ui/intra-doc/github-flavored-blockquote.rs` → `tests/rustdoc-ui/intra-doc/github-flavored-admonitions.rs`

**Review by fmease — APPROVED** [review]
Some final nits.

**Comment by fmease** [comment]
The problem is that there's no workaround for the user as far as I can tell. There's nothing they could do to their repo `README.md` that would fix this warning. (Well, they could `#[allow(rustdoc::broken_intra_doc_links)]` at the … crate root? That's not desirable)

**Comment by GuillaumeGomez** [comment]
Oh I see. Hum... Should we make a specific lint for it? Like `github_flavored_markdown`? Or am I just too picky here and just going through with this PR is good enough?

**Comment by fmease** [comment]
> Or am I just too picky here and just going through with this PR is good enough?

No, definitely not too picky. Your position is absolutely fair because it could open the floodgate to a never-ending stream of compatibility hacks for GitHub-flavored markdown (esp. since it keeps getting extended). I wonder if we already have hacks like these in rustdoc?

> Should we make a specific lint for it? Like `github_flavored_markdown`?

That sounds like a good solution/compromise! I'm all for a new lint. We probably don't want to have `github` in its name since I don't think we want to tie ourselves to that platform like that (it might not exist in 10 years time / another platform might become the new 'default' platform with their own flavor of Markdown). Maybe `other_flavored_markdown` or `differently_flavored_markdown` (bikesheddable names)?

**Comment by GuillaumeGomez** [comment]
`non_commonmark_flavored_markdown`? =D

**Comment by fmease** [comment]
Or simply `rustdoc::nonstandard_markdown` (borrowing the adjective from `nonstandard_style`, https://doc.rust-lang.org/rustc/lints/groups.html#lint-groups), maybe that's too vague tho.

Ok, enough of bikeshedding. Let's wait for binarycat :)

File: src/librustdoc/passes/collect_intra_doc_links.rs (hunk 2 above)
Comment (lolbinarycat) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: this is incorrect, it needs to be *greater* than 1, (i.e. two or more), in order to allow links to the never type (`[!]`).

Comment (fmease) [reply src/librustdoc/passes/collect_intra_doc_links.rs]: Oh, true :+1:. My bad. Still, `strip_prefix` over `starts_with` + manual slicing

```suggestion
        && let Some(suffix) = ori_link.strip_prefix('!')
        && !suffix.is_empty()
        && suffix.chars().all(|c| c.is_ascii_alphabetic())
```

**Comment by lolbinarycat** [comment]
My reasoning for adding this logic is it is adding a simple heuristic to a lint that already uses a bunch of heuristics.

I have a number of problems with a `nonstandard_markdown`:
1. the name is simply incorrect.  rustdoc uses it's own flavor of markdown, from obvious domain-specific things like intra-doc lints, to benign things like footnotes that are not actually in the commonmark spec.
2. this would be way more likely to lead to more logic for unsupported markdown being added, as people report "false negatives" for the lint.
3. commonmark, similar to html5, is defined in such a way that every document has an interpretation, so it is not always clear what is intended as using non-standard features. `* [x] y` could either be a task list, or a reference link to `x`.

I think if any lint should be added, it should be `rustdoc::broken_link_references`, as that seems like something that would be desirable to deny in CI in order to make sure no typos slip through, and a decent number of issues get filed complaining about broken references not being denied.   This would need to be an allow-by-default lint, at least initially, in order to not cause massive ecosystem churn.

**Comment by lolbinarycat** [comment]
addressed feedback from code review

@rustbot review

cc @fmease @GuillaumeGomez

**Comment by lolbinarycat** [comment]
Just added a code comment that should hopefully clear up confusion.

The main point is that regardless of what github flavored markdown does, we probably shouldn't be considering these as intra-doc link candidates for the same reason we don't consider links containing spaces to be intra-doc link candidates: item paths will never contain a space or start with a `!` (with the exception of the special never type syntax).

File: src/librustdoc/passes/collect_intra_doc_links.rs [hunk 5]
```diff
@@ -1013,11 +1014,27 @@ fn preprocess_link(
...
+    // Ignore GitHub-flavored Markdown (GFM) admonitions, such as [!NOTE] and [!IMPORTANT]
+    //
+    // rustdoc does not support GFM,
+    // however it is a common pattern to add `#[doc = include_str!("../README.md")]` to the root of a crate,
+    // so we want to at least accept GFM, even if it doesn't render perfectly.
+    //
+    // We make sure to allow `[!]` as a link to the never type by checking length.
+    //
+    // This will never cause us to ignore something that is a valid intra-doc link,
+    // as (with the exception of `[!]`), intra-doc links can never start with `!`.
```
Comment (GuillaumeGomez) [inline src/librustdoc/passes/collect_intra_doc_links.rs]:
```suggestion
    // If we have an intra-doc link starting with `!` (which isn't `[!]` because this is the never type), we ignore it
    // as it is never valid.
    //
    // The case is common enough because of cases like `#[doc = include_str!("../README.md")]` which often
    // uses GitHub-flavored Markdown (GFM) admonitions, such as `[!NOTE]`.
```

**Review by fmease — APPROVED** [review]
r=fmease,GuillaumeGomez if GuillaumeGomez also approves of this unfortunate compatibility hack (round two).

Ofc we could also poll this but I'm not sure how long it would take to reach all members (also, I dislike rfcbot poll bc it doesn't discern between "disapprove" and "haven't seen yet").

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks everyone!

@bors r=fmease,GuillaumeGomez rollup
