### PR TITLE
incr.comp.: Make sure dependencies are recorded when feeding queries during eval-always queries.

### LINKED ISSUE #108481: ICE: 'index out of bounds' in on_disk_cache.rs, then double panic 'Illegal read of:'
This is one of those ICEs that are terribly hard to minimize because they happen ~~randomly and~~ cache-dependently, ~~but hopefully the backtraces will be useful~~ [update: see below for repro instructions]. If nothing else, notice that there is a panic _while trying to print the query stack;_ it might be desirable to look into making that not happen so as to be able to get more information.

### Meta

Occurred while running `cargo check` or `cargo clippy`.

`rustc --version --verbose`:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: x86_64-apple-darwin
release: 1.67.1
LLVM version: 15.0.6
```

### Error output

```
$ /Users/kpreid/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo clippy
    Checking all-is-cubes v0.5.0 (/Users/kpreid/Projects/all-is-cubes/all-is-cubes)
warning: glob import doesn't reexport anything because no candidate is public enough
  --> /Users/kpreid/Projects/all-is-cubes/all-is-cubes/src/mesh/chunked_mesh.rs:20:9
   |
20 | pub use blocks::*;
   |         ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'index out of bounds: the len is 536 but the index is 667', compiler/rustc_query_impl/src/on_disk_cache.rs:717:40
stack backtrace:
[[[backtrace trimmed; see backtrace section below]]]

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.1 (d5a82bbd2 2023-02-07) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 58907', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/compiler/rustc_query_system/src/dep_graph/graph.rs:450:25
stack backtrace:
[[[backtrace trimmed; see backtrace section below]]]

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.1 (d5a82bbd2 2023-02-07) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
warning: `all-is-cubes` (lib) generated 1 warning
error: could not compile `all-is-cubes`; 1 warning emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ /Users/kpreid/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo clippy
    Checking all-is-cubes v0.5.0 (/Users/kpreid/Projects/all-is-cubes/all-is-cubes)
warning: glob import doesn't reexport anything because no candidate is public enough
  --> /Users/kpreid/Projects/all-is-cubes/all-is-cubes/src/mesh/chunked_mesh.rs:20:9
   |
20 | pub use blocks::*;
   |         ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'index out of bounds: the len is 536 but the index is 667', compiler/rustc_query_impl/src/on_disk_cache.rs:717:40
stack backtrace:
   0:        0x10aaeb796 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb2b3f9f8dc23cb9d
   1:        0x10ab4a1ea - core::fmt::write::h603bc3f9f076a504
   2:        0x10aaddbbc - std::io::Write::write_fmt::haffd946fd0c71703
   3:        0x10aaeb57a - std::sys_common::backtrace::print::hf660b768f462926e
   4:        0x10aaee8e3 - std::panicking::default_hook::{{closure}}::hb5b3e9f2c6b6790b
   5:        0x10aaee638 - std::panicking::default_hook::ha10903320e35543e
   6:        0x11a3746dd - rustc_driver[8e093e25fe36b41b]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10aaef0c7 - std::panicking::rust_panic_with_hook::h52ed83dd7c5d1444
   8:        0x10aaeee74 - std::panicking::begin_panic_handler::{{closure}}::h5f4e10879935eaea
   9:        0x10aaebc38 - std::sys_common::backtrace::__rust_end_short_backtrace::hadc7b677a554f9f9
  10:        0x10aaeeb3d - _rust_begin_unwind
  11:        0x10ab76993 - core::panicking::panic_fmt::hc10ef4c7e7c3da2e
  12:        0x10ab76ad6 - core::panicking::panic_bounds_check::hf660537e54ee196e
  13:        0x11de45ce7 - <rustc_span[2625accf23a29991]::SourceFile>::lines::<<rustc_span[2625accf23a29991]::span_encoding::Span as rustc_serialize[a208a1dcefcb3cbf]::serialize::Decodable<rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::CacheDecoder>>::decode::{closure#0}, rustc_span[2625accf23a29991]::BytePos>
  14:        0x11dde2841 - <rustc_span[2625accf23a29991]::span_encoding::Span as rustc_serialize[a208a1dcefcb3cbf]::serialize::Decodable<rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::CacheDecoder>>::decode
  15:        0x11de29509 - <rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_span[2625accf23a29991]::span_encoding::Span>
  16:        0x11df80871 - rustc_query_impl[cfd1e86cd19618c3]::plumbing::try_load_from_disk::<rustc_span[2625accf23a29991]::span_encoding::Span>
  17:        0x11dff0946 - <rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind as rustc_query_system[b885f6fe60382e2e]::dep_graph::DepKind>::with_deps::<rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_span[2625accf23a29991]::def_id::DefId, core[36719e2ca9cc5cdf]::option::Option<rustc_middle[fc7ebf79883dfa5a]::ty::Destructor>>::{closure#0}, core[36719e2ca9cc5cdf]::option::Option<core[36719e2ca9cc5cdf]::option::Option<rustc_middle[fc7ebf79883dfa5a]::ty::Destructor>>>
  18:        0x11dd0c588 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_span[2625accf23a29991]::def_id::DefId, rustc_span[2625accf23a29991]::span_encoding::Span>
  19:        0x11dc1a07c - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<rustc_span[2625accf23a29991]::def_id::DefId, rustc_span[2625accf23a29991]::span_encoding::Span>>
  20:        0x11dd4a84f - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::def_span, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  21:        0x11ddd3ba5 - <rustc_query_impl[cfd1e86cd19618c3]::Queries as rustc_middle[fc7ebf79883dfa5a]::ty::query::QueryEngine>::def_span
  22:        0x11cb2cc7d - rustc_ty_utils[2e8d38d334874b81]::ty::param_env
  23:        0x11df2c78e - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, rustc_span[2625accf23a29991]::def_id::DefId, rustc_middle[fc7ebf79883dfa5a]::ty::ParamEnv>
  24:        0x11dc247cc - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<rustc_span[2625accf23a29991]::def_id::DefId, rustc_middle[fc7ebf79883dfa5a]::ty::ParamEnv>>
  25:        0x11dd4bab5 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::param_env, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  26:        0x11cc5f854 - <rustc_hir_typeck[6a8d7b4346cd089d]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_with_fallback<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_const_arg::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  27:        0x11cc85c41 - rustc_hir_typeck[6a8d7b4346cd089d]::typeck_const_arg
  28:        0x11dfed5ba - <rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind as rustc_query_system[b885f6fe60382e2e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>::{closure#0}, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  29:        0x11df50d42 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  30:        0x11dc650a1 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>>
  31:        0x11dd3ac7d - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck_const_arg, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  32:        0x11ddd33e7 - <rustc_query_impl[cfd1e86cd19618c3]::Queries as rustc_middle[fc7ebf79883dfa5a]::ty::query::QueryEngine>::typeck_const_arg
  33:        0x11cc867ba - rustc_hir_typeck[6a8d7b4346cd089d]::typeck
  34:        0x11df1fa2f - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, rustc_span[2625accf23a29991]::def_id::LocalDefId, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  35:        0x11dcb8f0e - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::VecCache<rustc_span[2625accf23a29991]::def_id::LocalDefId, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>>
  36:        0x11dd4a314 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  37:        0x11ccfa49a - std[3161060b00c850ea]::panicking::try::<(), core[36719e2ca9cc5cdf]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[5322186b9ea74ad0]::sync::par_for_each_in<&[rustc_span[2625accf23a29991]::def_id::LocalDefId], <rustc_middle[fc7ebf79883dfa5a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  38:        0x11ccfa695 - rustc_data_structures[5322186b9ea74ad0]::sync::par_for_each_in::<&[rustc_span[2625accf23a29991]::def_id::LocalDefId], <rustc_middle[fc7ebf79883dfa5a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies::{closure#0}>::{closure#0}>
  39:        0x11cc859cd - rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies
  40:        0x11df63cf6 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (), ()>
  41:        0x11dc91839 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(), ()>>
  42:        0x11dd3d191 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck_item_bodies, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  43:        0x11cdeadfe - <rustc_session[6d4ac4b3b9abdb4d]::session::Session>::time::<(), rustc_hir_analysis[bf6ee3453ce961c4]::check_crate::{closure#7}>
  44:        0x11ce31435 - rustc_hir_analysis[bf6ee3453ce961c4]::check_crate
  45:        0x11a45348a - rustc_interface[22d5e9ac326097ba]::passes::analysis
  46:        0x11df56b36 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (), core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  47:        0x11dc802a7 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(), core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>>
  48:        0x11dd4a6f1 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::analysis, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  49:        0x11a303ab3 - <rustc_interface[22d5e9ac326097ba]::passes::QueryContext>::enter::<rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  50:        0x11a34ae32 - rustc_span[2625accf23a29991]::with_source_map::<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  51:        0x11a33ce6d - <scoped_tls[b2500c2140549217]::ScopedKey<rustc_span[2625accf23a29991]::SessionGlobals>>::set::<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  52:        0x11a30c9aa - std[3161060b00c850ea]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[22d5e9ac326097ba]::util::run_in_thread_pool_with_globals<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  53:        0x11a2eeaf5 - <<std[3161060b00c850ea]::thread::Builder>::spawn_unchecked_<rustc_interface[22d5e9ac326097ba]::util::run_in_thread_pool_with_globals<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#1} as core[36719e2ca9cc5cdf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:        0x10aaf8437 - std::sys::unix::thread::Thread::new::thread_start::he272a3f7edb058e0
  55:     0x7ff80544d4e1 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.1 (d5a82bbd2 2023-02-07) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 58907', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/compiler/rustc_query_system/src/dep_graph/graph.rs:450:25
stack backtrace:
   0:        0x10aaeb796 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb2b3f9f8dc23cb9d
   1:        0x10ab4a1ea - core::fmt::write::h603bc3f9f076a504
   2:        0x10aaddbbc - std::io::Write::write_fmt::haffd946fd0c71703
   3:        0x10aaeb57a - std::sys_common::backtrace::print::hf660b768f462926e
   4:        0x10aaee8e3 - std::panicking::default_hook::{{closure}}::hb5b3e9f2c6b6790b
   5:        0x10aaee638 - std::panicking::default_hook::ha10903320e35543e
   6:        0x11a3746dd - rustc_driver[8e093e25fe36b41b]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10aaef0c7 - std::panicking::rust_panic_with_hook::h52ed83dd7c5d1444
   8:        0x10aaeee74 - std::panicking::begin_panic_handler::{{closure}}::h5f4e10879935eaea
   9:        0x10aaebc38 - std::sys_common::backtrace::__rust_end_short_backtrace::hadc7b677a554f9f9
  10:        0x10aaeeb3d - _rust_begin_unwind
  11:        0x10ab76993 - core::panicking::panic_fmt::hc10ef4c7e7c3da2e
  12:        0x11ebfa7c4 - <rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind as rustc_query_system[b885f6fe60382e2e]::dep_graph::DepKind>::read_deps::<<rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::read_index::{closure#0}>
  13:        0x11ed22617 - <rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt>::type_length_limit
  14:        0x11ec54a52 - rustc_middle[fc7ebf79883dfa5a]::query::descs::typeck
  15:        0x11df79313 - rustc_query_impl[cfd1e86cd19618c3]::plumbing::create_query_frame::<rustc_span[2625accf23a29991]::def_id::LocalDefId>
  16:        0x11dec3165 - <rustc_query_impl[cfd1e86cd19618c3]::query_structs::typeck::{closure#0} as core[36719e2ca9cc5cdf]::ops::function::FnOnce<(rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, &mut std[3161060b00c850ea]::collections::hash::map::HashMap<rustc_query_system[b885f6fe60382e2e]::query::job::QueryJobId, rustc_query_system[b885f6fe60382e2e]::query::job::QueryJobInfo, core[36719e2ca9cc5cdf]::hash::BuildHasherDefault<rustc_hash[7147e8159724e841]::FxHasher>>)>>::call_once
  17:        0x11de56f5d - rustc_query_system[b885f6fe60382e2e]::query::job::print_query_stack::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  18:        0x11a3fb583 - rustc_interface[22d5e9ac326097ba]::interface::try_print_query_stack
  19:        0x11a375491 - rustc_driver[8e093e25fe36b41b]::report_ice
  20:        0x10aaef0c7 - std::panicking::rust_panic_with_hook::h52ed83dd7c5d1444
  21:        0x10aaeee74 - std::panicking::begin_panic_handler::{{closure}}::h5f4e10879935eaea
  22:        0x10aaebc38 - std::sys_common::backtrace::__rust_end_short_backtrace::hadc7b677a554f9f9
  23:        0x10aaeeb3d - _rust_begin_unwind
  24:        0x10ab76993 - core::panicking::panic_fmt::hc10ef4c7e7c3da2e
  25:        0x10ab76ad6 - core::panicking::panic_bounds_check::hf660537e54ee196e
  26:        0x11de45ce7 - <rustc_span[2625accf23a29991]::SourceFile>::lines::<<rustc_span[2625accf23a29991]::span_encoding::Span as rustc_serialize[a208a1dcefcb3cbf]::serialize::Decodable<rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::CacheDecoder>>::decode::{closure#0}, rustc_span[2625accf23a29991]::BytePos>
  27:        0x11dde2841 - <rustc_span[2625accf23a29991]::span_encoding::Span as rustc_serialize[a208a1dcefcb3cbf]::serialize::Decodable<rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::CacheDecoder>>::decode
  28:        0x11de29509 - <rustc_query_impl[cfd1e86cd19618c3]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_span[2625accf23a29991]::span_encoding::Span>
  29:        0x11df80871 - rustc_query_impl[cfd1e86cd19618c3]::plumbing::try_load_from_disk::<rustc_span[2625accf23a29991]::span_encoding::Span>
  30:        0x11dff0946 - <rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind as rustc_query_system[b885f6fe60382e2e]::dep_graph::DepKind>::with_deps::<rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_span[2625accf23a29991]::def_id::DefId, core[36719e2ca9cc5cdf]::option::Option<rustc_middle[fc7ebf79883dfa5a]::ty::Destructor>>::{closure#0}, core[36719e2ca9cc5cdf]::option::Option<core[36719e2ca9cc5cdf]::option::Option<rustc_middle[fc7ebf79883dfa5a]::ty::Destructor>>>
  31:        0x11dd0c588 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_span[2625accf23a29991]::def_id::DefId, rustc_span[2625accf23a29991]::span_encoding::Span>
  32:        0x11dc1a07c - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<rustc_span[2625accf23a29991]::def_id::DefId, rustc_span[2625accf23a29991]::span_encoding::Span>>
  33:        0x11dd4a84f - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::def_span, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  34:        0x11ddd3ba5 - <rustc_query_impl[cfd1e86cd19618c3]::Queries as rustc_middle[fc7ebf79883dfa5a]::ty::query::QueryEngine>::def_span
  35:        0x11cb2cc7d - rustc_ty_utils[2e8d38d334874b81]::ty::param_env
  36:        0x11df2c78e - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, rustc_span[2625accf23a29991]::def_id::DefId, rustc_middle[fc7ebf79883dfa5a]::ty::ParamEnv>
  37:        0x11dc247cc - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<rustc_span[2625accf23a29991]::def_id::DefId, rustc_middle[fc7ebf79883dfa5a]::ty::ParamEnv>>
  38:        0x11dd4bab5 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::param_env, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  39:        0x11cc5f854 - <rustc_hir_typeck[6a8d7b4346cd089d]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_with_fallback<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_const_arg::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  40:        0x11cc85c41 - rustc_hir_typeck[6a8d7b4346cd089d]::typeck_const_arg
  41:        0x11dfed5ba - <rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind as rustc_query_system[b885f6fe60382e2e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>::{closure#0}, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  42:        0x11df50d42 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  43:        0x11dc650a1 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(rustc_span[2625accf23a29991]::def_id::LocalDefId, rustc_span[2625accf23a29991]::def_id::DefId), &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>>
  44:        0x11dd3ac7d - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck_const_arg, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  45:        0x11ddd33e7 - <rustc_query_impl[cfd1e86cd19618c3]::Queries as rustc_middle[fc7ebf79883dfa5a]::ty::query::QueryEngine>::typeck_const_arg
  46:        0x11cc867ba - rustc_hir_typeck[6a8d7b4346cd089d]::typeck
  47:        0x11df1fa2f - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, rustc_span[2625accf23a29991]::def_id::LocalDefId, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>
  48:        0x11dcb8f0e - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::VecCache<rustc_span[2625accf23a29991]::def_id::LocalDefId, &rustc_middle[fc7ebf79883dfa5a]::ty::context::TypeckResults>>
  49:        0x11dd4a314 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  50:        0x11ccfa49a - std[3161060b00c850ea]::panicking::try::<(), core[36719e2ca9cc5cdf]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[5322186b9ea74ad0]::sync::par_for_each_in<&[rustc_span[2625accf23a29991]::def_id::LocalDefId], <rustc_middle[fc7ebf79883dfa5a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  51:        0x11ccfa695 - rustc_data_structures[5322186b9ea74ad0]::sync::par_for_each_in::<&[rustc_span[2625accf23a29991]::def_id::LocalDefId], <rustc_middle[fc7ebf79883dfa5a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies::{closure#0}>::{closure#0}>
  52:        0x11cc859cd - rustc_hir_typeck[6a8d7b4346cd089d]::typeck_item_bodies
  53:        0x11df63cf6 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (), ()>
  54:        0x11dc91839 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(), ()>>
  55:        0x11dd3d191 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::typeck_item_bodies, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  56:        0x11cdeadfe - <rustc_session[6d4ac4b3b9abdb4d]::session::Session>::time::<(), rustc_hir_analysis[bf6ee3453ce961c4]::check_crate::{closure#7}>
  57:        0x11ce31435 - rustc_hir_analysis[bf6ee3453ce961c4]::check_crate
  58:        0x11a45348a - rustc_interface[22d5e9ac326097ba]::passes::analysis
  59:        0x11df56b36 - <rustc_query_system[b885f6fe60382e2e]::dep_graph::graph::DepGraph<rustc_middle[fc7ebf79883dfa5a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[fc7ebf79883dfa5a]::ty::context::TyCtxt, (), core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  60:        0x11dc802a7 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::try_execute_query::<rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt, rustc_query_system[b885f6fe60382e2e]::query::caches::DefaultCache<(), core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>>
  61:        0x11dd4a6f1 - rustc_query_system[b885f6fe60382e2e]::query::plumbing::get_query::<rustc_query_impl[cfd1e86cd19618c3]::queries::analysis, rustc_query_impl[cfd1e86cd19618c3]::plumbing::QueryCtxt>
  62:        0x11a303ab3 - <rustc_interface[22d5e9ac326097ba]::passes::QueryContext>::enter::<rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  63:        0x11a34ae32 - rustc_span[2625accf23a29991]::with_source_map::<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  64:        0x11a33ce6d - <scoped_tls[b2500c2140549217]::ScopedKey<rustc_span[2625accf23a29991]::SessionGlobals>>::set::<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  65:        0x11a30c9aa - std[3161060b00c850ea]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[22d5e9ac326097ba]::util::run_in_thread_pool_with_globals<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>
  66:        0x11a2eeaf5 - <<std[3161060b00c850ea]::thread::Builder>::spawn_unchecked_<rustc_interface[22d5e9ac326097ba]::util::run_in_thread_pool_with_globals<rustc_interface[22d5e9ac326097ba]::interface::run_compiler<core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>, rustc_driver[8e093e25fe36b41b]::run_compiler::{closure#1}>::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[36719e2ca9cc5cdf]::result::Result<(), rustc_errors[8823badf17c9d4b2]::ErrorGuaranteed>>::{closure#1} as core[36719e2ca9cc5cdf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  67:        0x10aaf8437 - std::sys::unix::thread::Thread::new::thread_start::he272a3f7edb058e0
  68:     0x7ff80544d4e1 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.1 (d5a82bbd2 2023-02-07) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
warning: `all-is-cubes` (lib) generated 1 warning
error: could not compile `all-is-cubes`; 1 warning emitted
```

</p>
</details>

@rustbot label +A-incr-comp

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes sure we don't drop dependency edges when feeding queries during an eval-always query. 

Background: During eval-always queries, no dependencies are recorded because the system knows to unconditionally re-evaluate them regardless of any actual dependencies. This works fine for these queries themselves but leads to a problem when feeding other queries: When queries are fed, we set up their dependency edges by copying the current set of dependencies of the feeding query. But because this set is empty for eval-always queries, we record no edges at all -- which has the effect that the fed query instances always look "green" to the system, although they should always be "red".

The fix is to explicitly add a dependency on the artificial "always red" dep-node when feeding during eval-always queries.

Fixes https://github.com/rust-lang/rust/issues/108481
Maybe also fixes issue https://github.com/rust-lang/rust/issues/88488.

cc @jyn514 

r? @cjgillot or @oli-obk

### CODE REVIEW

File: compiler/rustc_passes/src/hir_id_validator.rs [hunk 1]
```diff
@@ -8,34 +8,34 @@ use rustc_middle::hir::nested_filter;
 use rustc_middle::ty::TyCtxt;
 
 pub fn check_crate(tcx: TyCtxt<'_>) {
-    tcx.dep_graph.assert_ignored();
```
Comment (cjgillot) [inline compiler/rustc_passes/src/hir_id_validator.rs:11]: Why this change?

Comment (michaelwoerister) [reply compiler/rustc_passes/src/hir_id_validator.rs:11]: This is actually running inside of an eval-always query, not in `with_ignore()`. The two kinds both used `TaskDepsRef::Ignore` before this PR. Now that there is a `TaskDepsRef::EvalAlways`, the assertion fails.

Looking at the code again, I think we might actually want to just run it normally. I think the original `with_ignore()` scope was just a performance optimization when this check was run for release builds too.

File: compiler/rustc_query_system/src/dep_graph/graph.rs [hunk 2]
```diff
@@ -556,7 +572,10 @@ impl<K: DepKind> DepGraph<K> {
             let mut edges = SmallVec::new();
             K::read_deps(|task_deps| match task_deps {
                 TaskDepsRef::Allow(deps) => edges.extend(deps.lock().reads.iter().copied()),
-                TaskDepsRef::Ignore => {} // During HIR lowering, we have no dependencies.
+                TaskDepsRef::EvalAlways => {
+                    edges.push(DepNodeIndex::FOREVER_RED_NODE);
+                }
+                TaskDepsRef::Ignore => {}
```
[the remark this answers is not in the document]
Comment (michaelwoerister) [reply compiler/rustc_query_system/src/dep_graph/graph.rs:578]: Yeah, I've been wondering about that too. I think adding a dependency would be surprising. We are inside a `with_ignore()` after all. But ICEing might be useful?

One factor that might influence a decision here is that we seem to wrap everything inside of `TaskDepsRef::Ignore` by default:

https://github.com/rust-lang/rust/blob/a412564f8ca794e227305309da9da16c417ea9ce/compiler/rustc_middle/src/ty/context/tls.rs#L40-L49

If we changed that to `TaskDepsRef::Forbid` there would be less chance of things being silently ignored and as a result less harm in treating `TaskDepsRef::Ignore` as "yes, really turn off dependency tracking". We use `DepGraph::with_ignore()` in a few places where we really don't want any dep-tracking to happen, e.g. [when re-computing the value of a green node](https://github.com/rust-lang/rust/blob/a412564f8ca794e227305309da9da16c417ea9ce/compiler/rustc_query_system/src/query/plumbing.rs#L610).

But I haven't tried what the fallout of switching to `TaskDepsRef::Forbid` would be. It might need some cleanup.

Overall, I think `DepGraph::with_ignore()` should really reliable turn off dep-tracking -- but we should use it in as few places as possible. This PR would be an example of replacing it with something more targeted.
