### PR TITLE
mir opt + codegen: handle subtyping

### LINKED ISSUE #107205: codegen generates vtables for a variable's supertype when unsizing sometimes
I was putting `&`'s here and there to make my program compile as beginners supposed to do and finally ended with:

```
  = note: Undefined symbols for architecture arm64:
            "core::ptr::drop_in_place$LT$fn$LP$$RF$$u5b$i64$u5d$$RP$$u20$.$GT$$u20$i64$GT$::h8f1379e9ceec7fb5", referenced from:
                l___unnamed_1 in wyas-3cfa3c0d2101b65b.6xaszv4ay9i42ky.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
To assure myself that this is unrelated to native/rosetta mess I've ran this in docker and in [rust playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ea5473b749dd86ba767cc9acbd2f8be5) with the same outcome.
```
  = note: /usr/bin/ld: /playground/target/release/deps/playground-7e94a1292993c003.playground.0627c30c-cgu.0.rcgu.o:(.data.rel.ro..L__unnamed_3+0x0): undefined reference to `core::ptr::drop_in_place<fn(&[i64]) -> i64>'
          /usr/bin/ld: /playground/target/release/deps/playground-7e94a1292993c003: hidden symbol `_ZN4core3ptr66drop_in_place$LT$fn$LP$$RF$$u5b$i64$u5d$$RP$$u20$.$GT$$u20$i64$GT$17h8581d5a4605118bdE' isn't defined
          /usr/bin/ld: final link failed: bad value
```

This particular code breaks the linker
```rust
struct Wrapper(fn(val: &[i64]) -> i64);

impl Debug for Wrapper {
    fn fmt<'a>(&'a self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&self.0 as &fn(&'a [i64]) -> i64).finish()
    }
}

fn main() {
    println!("{:?}", Wrapper(useful));
}
```
I've come up with that since deriving `Debug` or implementing it manually like that 
```rust
impl Debug for Wrapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&self.0).finish()
    }
}
```
leads to following type/borrow check error:
> implementation of `Debug` is not general enough

Expected behavior: program prints
> Wrapper(address)

Actual behavior: *see above*

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: aarch64-apple-darwin
release: 1.66.1
LLVM version: 15.0.2
```

I've tried both beta `1.67.0-beta.9` and nightly `1.68.0-nighlty` at rust playground and both are failing during linking.

----------------
***Edit***

I've bruteforced working program 😂  :
```rust
impl Debug for Wrapper {
    fn fmt<'a>(&'a self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&(self.0 as fn(&'a [i64]) -> i64)).finish()
    }
}
```

### PR DESCRIPTION
**Pull request by lcnr**
fixes #107205

the same issue was caused in multiple places:
- mir opts: both copy and destination propagation
- codegen: assigning operands to locals (which also propagates values)

I changed codegen to always update the type in the operands used for locals which should guard against any new occurrences of this bug going forward. I don't know how to make mir optimizations more resilient here. Hopefully the added tests will be enough to detect any trivially wrong optimizations going forward.

### CODE REVIEW

File: compiler/rustc_mir_transform/src/dest_prop.rs [hunk 1]
```diff
@@ -37,6 +37,10 @@
 //!   if they do not consistently refer to the same place in memory. This is satisfied if they do
 //!   not contain any indirection through a pointer or any indexing projections.
 //!
+//! * `p` and `q` must have the **same type**. If we replace a local with a subtype or supertype,
+//!   computing this may result in a different vtable for that local. See the `subtyping-impacts-selection`
```
Comment (lcnr) [inline compiler/rustc_mir_transform/src/dest_prop.rs:41]: reminder: have to fix that comment

File: compiler/rustc_codegen_ssa/src/mir/operand.rs [hunk 2]
```diff
@@ -518,6 +518,10 @@ impl<'a, 'tcx, Bx: BuilderMethods<'a, 'tcx>> FunctionCx<'a, 'tcx, Bx> {
         match self.locals[place_ref.local] {
             LocalRef::Operand(mut o) => {
                 // Moves out of scalar and scalar pair fields are trivial.
+                o.layout.ty = self.monomorphized_place_ty(mir::PlaceRef {
+                    local: place_ref.local,
+                    projection: &[],
+                });
```
Comment (lcnr) [inline compiler/rustc_codegen_ssa/src/mir/operand.rs:524]: unsure whether this one is necessary, should maybe move this to an assert when setting a `LocalRef` :thinking:

**Comment by cjgillot** [comment]
I'm not sure this is the best course of action. Subtyping assignments will continue to be a footgun. Should we instead require exact equality, checked by MIR validation, and make subtyping assignment require a `Rvalue::Cast`?

**Comment by lcnr** [comment]
yeah, agree with that :+1: we should add a mir pass post analysis which makes subtyping explicit, opened #112651 for that. I don't have the capacity to actually implement this though, so I would like for someone else to take that over.

I would still like to merge this PR (putting a `FIXME(#112651)` at every place which should be changed once subtyping is explicit) given that it still fixes the unsoundness. I also think that extracting `Locals` into a private module is a positive change regardless. Checking the type of `LocalRef::Operand` detected another 'bug' (using wrong types in shims) and we can change `overwrite_local` to assert that the types are equal instead afterwards.

does this seem sensible to you @cjgillot?

**Comment by cjgillot** [comment]
I agree to do it that way.

**Comment by lcnr** [comment]
add a bunch of `FIXME(#112651)` to everything that should be changed/reverted after #112651.

@rustbot ready

**Review by compiler-errors — APPROVED** [review]
Everything looks good.

File: compiler/rustc_codegen_ssa/src/mir/locals.rs [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+                let local_ty = self.monomorphize(self.mir.local_decls[local].ty);
+                if local_ty != op.layout.ty {
+                    // FIXME(#112651): This can be changed to an ICE afterwards.
+                    debug!("updating type of operand due to subtyping");
+                    with_no_trimmed_paths!(debug!(?op.layout.ty));
+                    with_no_trimmed_paths!(debug!(?local_ty));
+                    op.layout.ty = local_ty;
+                }
+            }
+        };
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/locals.rs:71]: FWIW in the MIR interpreter we avoid the risk of this by not having the type of the local in our `locals` map to begin with: we store a `IndexVec<mir::Local, LocalState<'tcx, Prov>>`, where `LocalState` is basically just [`interpret::Operand`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_const_eval/interpret/operand/enum.Operand.html). When we need the type we always go through `body.local_decls`.

So that might also be something codegen can do; storing the type in `self.locals` is redundant.
