### PR TITLE
fix(compiler/rustc_codegen_llvm): apply `target-cpu` attribute

### LINKED ISSUE #140174: Many new wasm features are enabled if compile `wasm32v1-none` with `-C linker-plugin-lto` flag on LLVM 20+
### Code

@alexcrichton

Code is minimized as much as possible and here is demo repository: https://github.com/StackOverflowExcept1on/wasm-builder-regression/
- `wasm-checker` - simple CLI tool that passes wasm to parity-wasm parser (it does not support new wasm features like reference-types, bulk-memory)
- `wasm-program` - this is smart contract that just allocates vector
- `wasm-project` - some intermediate directory that is generated by our utility
- [check.sh source code](https://github.com/StackOverflowExcept1on/wasm-builder-regression/blob/wasm32v1-none-bulk-memory/wasm-project/check.sh)

```bash
git clone https://github.com/StackOverflowExcept1on/wasm-builder-regression.git
cd wasm-builder-regression/wasm-project
cargo clean
./check.sh
```
```
   Compiling wasm-program v0.1.0 (/mnt/tmpfs/wasm-builder-regression/wasm-program)
   Compiling wasm-project v0.1.0 (/mnt/tmpfs/wasm-builder-regression/wasm-project)
    Finished `release` profile [optimized] target(s) in 0.27s
   Compiling gear-wasm v0.45.1
   Compiling wasm-checker v0.1.0 (/mnt/tmpfs/wasm-builder-regression/wasm-checker)
    Finished `release` profile [optimized] target(s) in 1.67s
     Running `/mnt/tmpfs/wasm-builder-regression/wasm-checker/target/release/wasm-checker ./target/wasm32v1-none/release/wasm_program.wasm`
Error: UnknownOpcode(252)
```

opcode 252 is `memory.fill` (bulk memory operations)

```bash
wasm-dis ./target/wasm32v1-none/release/wasm_program.wasm
```
```
(module $wasm_program.wasm
 ...
 ;; custom section "producers", size 75
 ;; features section: mutable-globals, nontrapping-float-to-int, bulk-memory, sign-ext, reference-types, multivalue
)
```

target was `wasm32v1-none`, however here we see bunch of wasm features that shouldn't be here.

I've also added LLVM IR output so we can report this bug to LLVM as soon as possible:
```
ls ./target/wasm32v1-none/release/deps/*.ll
```

If I remove flag `-C linker-plugin-lto`, it works as expected

I expected to see this happen: *I can use `-C linker-plugin-lto` to optimize my .wasm programs and it results in generating the correct code for the `wasm32v1-none` target*

Instead, this happened: *there is some kind of conflict between compiler flags?*

### Version it worked on

Problems started after #135763. I don't have time to bisect exact version right now.

### Version with regression

`rustc +nightly-2025-04-22 --version --verbose`:
```
rustc 1.88.0-nightly (d6c1e454a 2025-04-21)
binary: rustc
commit-hash: d6c1e454aa8af5e7e59fbf5c4e7d3128d2f99582
commit-date: 2025-04-21
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
Resolves rust-lang/rust#140174

r? @alexcrichton

try-job: `test-various*`

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/allocator.rs [hunk 1]
```diff
@@ -147,6 +149,20 @@ fn create_wrapper_function(
         llvm::Visibility::from_generic(tcx.sess.default_visibility()),
         ty,
     );
+
+    let mut attrs = SmallVec::<[_; 2]>::new();
+
+    let target_cpu = llvm_util::target_cpu(tcx.sess);
+    let target_cpu_attr = llvm::CreateAttrStringValue(cx.llcx, "target-cpu", target_cpu);
```
Comment (StackOverflowExcept1on) [inline compiler/rustc_codegen_llvm/src/allocator.rs:155]: https://doc.rust-lang.org/beta/nightly-rustc/rustc_codegen_llvm/context/struct.GenericCx.html#method.apply_target_cpu_attr
I would like to use this, but my `cx` is `SimpleCx`

**Comment by alexcrichton** [comment]
Would it be possible to add a test for this? Either a codegen test or something in `tests/run-make/wasm-*` might suffice. It'd be nice to have a full application validated with `wasmparser`, for example, where all features were disabled except for a minimal set.

File: compiler/rustc_codegen_llvm/src/allocator.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_codegen_llvm/src/allocator.rs:155]: You can move the method onto SimpleCx, it doesn't appear to use anything FullCx related

Comment (StackOverflowExcept1on) [reply compiler/rustc_codegen_llvm/src/allocator.rs:155]: I'm not very familiar with the code base. What is the recommended way to do this? There is `MiscCodegenMethods`, but it probably has more methods.

**Comment by StackOverflowExcept1on** [comment]
@alexcrichton done

File: src/tools/run-make-support/Cargo.toml [hunk 2]
```diff
@@ -17,7 +17,7 @@ object = "0.37"
 regex = "1.11"
 serde_json = "1.0"
 similar = "2.7"
-wasmparser = { version = "0.219", default-features = false, features = ["std"] }
+wasmparser = { version = "0.219", default-features = false, features = ["std", "features", "validate"] }
```
Comment (bjorn3) [inline src/tools/run-make-support/Cargo.toml]: The latest wasmparser version doesn't pull in ahash or another version of hashbrown.

File: tests/run-make/wasm-unexpected-features/rmake.rs [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+        .opt_level("z")
+        .run();
+    verify_features(Path::new("foo.wasm"));
+}
+
+fn verify_features(path: &Path) {
+    eprintln!("verify {path:?}");
+    let file = rfs::read(&path);
+
+    let mut validator = wasmparser::Validator::new_with_features(wasmparser::WasmFeatures::WASM1);
```
Comment (bjorn3) [inline tests/run-make/wasm-unexpected-features/rmake.rs:24]: `wasm32v1-none` produces `LIME1` compatible files, not `WASM1` compatible ones. lime1 is a slight superset of wasm1.

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs:24]: you're wrong: https://doc.rust-lang.org/rustc/platform-support/wasm32v1-none.html#enabled-webassembly-features

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs:24]: it's `target-cpu = mvp` and `+mutable-globals`

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs:24]: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/targets/wasm32v1_none.rs

File: tests/run-make/wasm-unexpected-features/rmake.rs [hunk 4]
```diff
@@ -0,0 +1,25 @@
+//@ only-wasm32v1-none
```
Comment (alexcrichton) [inline tests/run-make/wasm-unexpected-features/rmake.rs]: Oh I'm realizing now, does this actually run anywhere in CI? I don't believe tests are run for this target)

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Well, I ran the tests and looked at the output via `wasm-dis | less`

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Since `wasm32v1-none` is a Tier2 target, it should probably be tested before publishing binaries: https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-without-host-tools.

Comment (alexcrichton) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Would it be possible to rephrase this test in terms of `minicore` in the test suite? I'm not sure if that's integrated into the run-make test suite though. In any case the main value from a test like this will be preventing regressions, but if it's not run on CI then it won't prevent regressions. If it's not run on CI I don't think it's worth adding a test.

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Hmm, what if we do the same test, but for `wasm32-unknown-unknown` target? This test will use `-Z build-std` and `-C target-feature`, and it will also need the `rust-src` component.

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: @alexcrichton done

File: tests/run-make/wasm-unexpected-features/rmake.rs [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+    cargo()
+        .args([
+            "rustc",
+            "--manifest-path",
+            "wasm32_test/Cargo.toml",
+            "--profile",
+            "release",
+            "--target",
+            "wasm32-unknown-unknown",
+            "-Zbuild-std=std,core,panic_abort",
```
Comment (bjorn3) [inline tests/run-make/wasm-unexpected-features/rmake.rs]: This doesn't need std, right?

File: tests/run-make/wasm-unexpected-features/rmake.rs [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+    cargo()
+        .args([
+            "rustc",
+            "--manifest-path",
+            "wasm32_test/Cargo.toml",
+            "--profile",
+            "release",
+            "--target",
+            "wasm32-unknown-unknown",
```
Comment (bjorn3) [inline tests/run-make/wasm-unexpected-features/rmake.rs]: With build-std this can use wasm32v1-none just fine, right?

File: tests/run-make/wasm-unexpected-features/rmake.rs (hunk 5 above)
Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: yes, it should be `core`, `alloc` and `panic_abort`

File: tests/run-make/wasm-unexpected-features/rmake.rs (hunk 6 above)
Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: I think we should do this for `wasm32-wasip1` (I consulted with `jieyouxu`).
https://github.com/rust-lang/rust/blob/350d0ef0ec0493e6d21cfb265cb8211a0e74d766/src/ci/docker/host-x86_64/test-various/Dockerfile#L62

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: `wasm32-wasip1` has the same features as `wasm32-unknown-unknown`, but tests are run for it in the Docker image above.
https://doc.rust-lang.org/rustc/platform-support/wasm32-wasip1.html#enabled-webassembly-features

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: However, with `-C target-cpu=mvp` and `-Z build-std`, we can achieve a build that is similar to `wasm32v1-none`

Comment (bjorn3) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Given that you use `-Zbuild-std`, you don't need the target of rustc to be wasm32v1-none, just that the wasm llvm component is compiled in.

File: tests/run-make/wasm-unexpected-features/rmake.rs (hunk 4 above)
Comment (alexcrichton) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Unfortunately AFAIK `-Zbuild-std` is a known pain point in tests right now as it can take an excessively long amount of time to build and requires a lot of dependencies. I've seen comments in the past about how `-Zbuild-std` should be avoided in tests.

I don't see existing integration with `minicore` in run-make tests right now unfortunately. There is [one test referencing it](https://github.com/rust-lang/rust/blob/350d0ef0ec0493e6d21cfb265cb8211a0e74d766/tests/run-make/avr-rjmp-offset/avr-rjmp-offsets.rs#L25) but the test's FIXME has not yet been updated.

Instead of using `-Zbuild-std` could this build `tests/auxiliary/minicore.rs` directly perhaps? I'll also cc @jieyouxu as you might know better how best to integrate minicore bits here than I

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: Ok, I basically understand what you want. You want to use `minicore` instead of compiling `core` with the required features. But what should I do with `alloc`?

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: I will also need to somehow link any symbol marked as `#[rustc_std_internal_symbol]` with `#![no_core]`...

Comment (StackOverflowExcept1on) [reply tests/run-make/wasm-unexpected-features/rmake.rs]: @alexcrichton https://github.com/rust-lang/rust/issues/140174#issuecomment-3187526593

**Comment by StackOverflowExcept1on** [comment]
https://github.com/rust-lang/rust/actions/runs/16962093107/job/48077217291
https://github.com/rust-lang/rust/commit/1cd152f07820ea259d1dbeb28855e8e059dc02e3/checks/48077217291/logs
```
2025-08-14T10:50:53.8323270Z test [run-make] tests/run-make/wasm-unexpected-features ... ok
```
