### PR TITLE
error parsing lifetime following by Sized and message + between them

### LINKED ISSUE #102598: `impl 'a Trait` in argument position emits multible wrong diagnostics
I tried this almost-correct code: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4b790ecfcbff9ad627076dcc3ca0e584)

```rust
fn foo<'a>(_: impl 'a Sized) {}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `:`, `@`, or `|`, found `)`
 --> src/lib.rs:1:28
  |
1 | fn foo<'a>(_: impl 'a Sized) {}
  |                            ^ expected one of `:`, `@`, or `|`
  |
  = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a parameter name, give it a type
  |
1 | fn foo<'a>(_: impl 'a Sized: TypeName) {}
  |                            ++++++++++
help: if this is a type, explicitly ignore the parameter name
  |
1 | fn foo<'a>(_: impl 'a _: Sized) {}
  |                       ++

error: expected one of `)`, `+`, or `,`, found `Sized`
 --> src/lib.rs:1:23
  |
1 | fn foo<'a>(_: impl 'a Sized) {}
  |                      -^^^^^ expected one of `)`, `+`, or `,`
  |                      |
  |                      help: missing `,`

error: at least one trait must be specified
 --> src/lib.rs:1:15
  |
1 | fn foo<'a>(_: impl 'a Sized) {}
  |               ^^^^^^^

error: could not compile `playground` due to 3 previous errors
```

Ideally the output should look like:

```
   Compiling playground v0.0.1 (/playground)
error: expected `+` between lifetime and trait
 --> src/lib.rs:1:22
  |
1 | fn foo<'a>(_: impl 'a + Sized) {}
  |                       ^
  |                       |
  |                       help: missing `+`
  |
error: could not compile `playground` due to 1 previous errors
```

### PR DESCRIPTION
**Pull request by lyming2007**
Fixes #102598

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -2385,7 +2385,22 @@ impl<'a> Parser<'a> {
             };
             let (pat, ty) = if is_name_required || this.is_named_param() {
                 debug!("parse_param_general parse_pat (is_name_required:{})", is_name_required);
-
+                if let token::Ident(symname, _) = this.token.kind
+                    && symname.as_str().eq("Sized")
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2389]: I think this is too specific of a suggestion. I would likely not merge this unless it can be generalized for all trait names, since it's very unique for people to be writing `impl 'lifetime Sized`.

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -2385,7 +2385,22 @@ impl<'a> Parser<'a> {
...
+                    && this.prev_token.is_lifetime()
+                {
+                    // parse pattern with "'a Sized" we're supposed to give suggestion like
+                    // "'a + Sized"
+                    let mut err = this.struct_span_err(this.prev_token.span, "expected `+` between lifetime and trait");
+                    err.multipart_suggestion(
+                    "missing `+`",
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2396]: This should be an instruction for the user: "add `+`"

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -2385,7 +2385,22 @@ impl<'a> Parser<'a> {
...
+                     vec![(this.prev_token.span.shrink_to_hi(), " +".to_string()),
+                       (this.token.span.shrink_to_lo(), "".to_string())],
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2398]: This doesn't add anything? It's replacing "" with "".

File: compiler/rustc_parse/src/parser/item.rs [hunk 4]
```diff
@@ -2385,7 +2385,22 @@ impl<'a> Parser<'a> {
...
+                     Applicability::MaybeIncorrect,
+                    );
+                    err.emit();
+                    return Err(err);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2402]: You don't need to emit the error if it's being returned right after.

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: yes. you're right. It was a hack.
Now the code handles more specific cases for not only `'lifetime Size` as I removed `&& symname.as_str().eq("Sized")`

File: compiler/rustc_parse/src/parser/item.rs (hunk 2 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: fixed

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: If I don't add the second suggestion-part. The emit would look like:
error: expected `+` between lifetime and Sized
```
 --> main.rs:1:20
  |
1 | fn foo<'a>(_: impl 'a Sized) {}
  |                    ^^- help: add `+`: `+`
```
If now is like:
```
error: expected `+` between lifetime and Sized
 --> main.rs:1:20
  |
1 | fn foo<'a>(_: impl 'a Sized) {}
  |                    ^^
  |
help: add `+`
  |
1 | fn foo<'a>(_: impl 'a + Sized) {}
  |                       +
```
Which one do you prefer? I think the current suggestion looks better

File: compiler/rustc_parse/src/parser/item.rs (hunk 4 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs:2401]: I have to return `the err` early. Because at this point, we've parsed 'lifetime + trait which is already incorrect. If we don't return it. The parser would parse more in the following line:
```
2403                 let (pat, colon) = this.parse_fn_param_pat_colon()?;
2404                 if !colon {
```
And it would emit something like:
```
help: if this is a parameter name, give it a type
  |
1 | fn foo<'a>(_: impl 'a Sized: TypeName) {}
  |                            ++++++++++
help: if this is a type, explicitly ignore the parameter name

```
which I think it's not necessary

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs:2401]: Don't call `emit()` is what I meant, I agree you need to return the `Err` here.

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/item.rs]: You should be getting the span between the previous token and the current token, and replacing that with "` + `", so this doesn't matter.

**Review by compiler-errors — COMMENTED** [review]
I still don't know if this code should live in `parse_param_general` -- it seems like a very specific place to put this fix, so similar typos still don't have a suggestion, both in different positions (e.g. return position) and similar in nature (e.g. `impl Sized 'a`)

File: compiler/rustc_parse/src/parser/item.rs (hunk 4 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: this was fixed

**Comment by lyming2007** [comment]
> I still don't know if this code should live in `parse_param_general` -- it seems like a very specific place to put this fix, so similar typos still don't have a suggestion, both in different positions (e.g. return position) and similar in nature (e.g. `impl Sized 'a`)

at least `parse_param_general` is safe for this code, because that `'lifetime + trait` appears as parameters for function, though the code is rare as you mentioned before.

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: fixed by using `span_suggestion_verbose`. Thank you for the suggestion

**Comment by wesleywiser** [comment]
r? @compiler-errors

since you're already looking at it 🙂

File: compiler/rustc_parse/src/parser/item.rs [hunk 5]
```diff
@@ -2385,7 +2385,20 @@ impl<'a> Parser<'a> {
             };
             let (pat, ty) = if is_name_required || this.is_named_param() {
                 debug!("parse_param_general parse_pat (is_name_required:{})", is_name_required);
-
+                if let token::Ident(symname, _) = this.token.kind
+                    && this.prev_token.is_lifetime()
+                {
+                    // parse pattern with "'a Sized" we're supposed to give suggestion like
+                    // "'a + Sized"
+                    let mut err = this.struct_span_err(this.prev_token.span, &format!("expected `+` between lifetime and {}", symname.as_str()));
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2393]: This really shouldn't be creating a new error, but adding to an existing error.

File: compiler/rustc_parse/src/parser/item.rs [hunk 6]
```diff
@@ -2385,7 +2385,20 @@ impl<'a> Parser<'a> {
             };
             let (pat, ty) = if is_name_required || this.is_named_param() {
                 debug!("parse_param_general parse_pat (is_name_required:{})", is_name_required);
-
+                if let token::Ident(symname, _) = this.token.kind
+                    && this.prev_token.is_lifetime()
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/item.rs:2389]: It's not *critical*, but we should be checking `self.may_recover()`, just in case.

**Review by compiler-errors — COMMENTED** [review]
Sorry I have neglected reviewing this.

I'm still not convinced this is worth the extra code, since it's not as general as I would like it to be -- but that's just my opinion, and I'd rather not continue accidentally blocking this PR since I've been distracted.

**Comment by lyming2007** [comment]
> Let's get someone else's opinion on this. Sorry again about letting this PR sit around for so long, totally my fault.
> 
> r? compiler

Thanks Michael. Your suggestions are really helpful. I'll investigate more.

File: compiler/rustc_parse/src/parser/item.rs (hunk 6 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs:2389]: Sorry. I didn't find this function `self.may_recover()`. Does that mean we should check if we can recover from the parsing error? I don't think so, because `'a Sized` is not a legal syntax. The parser only check if the code missing `'` between some words

**Comment by lyming2007** [comment]
> I still don't know if this code should live in `parse_param_general` -- it seems like a very specific place to put this fix, so similar typos still don't have a suggestion, both in different positions (e.g. return position) and similar in nature (e.g. `impl Sized 'a`)

I think you're right, the code shouldn't be in `parse_param_general` after carefully thinking about it. Now I moved it to `parse_impl_ty` which seems to be more general.

File: compiler/rustc_parse/src/parser/item.rs (hunk 5 above)
Comment (lyming2007) [reply compiler/rustc_parse/src/parser/item.rs]: I moved the code to `parse_impl_ty ` which need to create a new error, because at that moment. There was no existing error to add.
