### PR TITLE
Check paths for privacy as they are resolved and refactor away `LastPrivate`

### LINKED ISSUE #12334: Give better error messages for visibility errors where there are defintions in both namespaces
(See #4110 and the fix in #12245).

If there are two definitions with the same name and different privacy modifiers in different namespaces, and there is an error on one of them, the error message might use the wrong kind of item name in its description.

E.g., if there is both a trait and function called `foo` and the latter is referred to and used, then the error message will still talk about "the trait `foo`" even though it is a function. 

See the FIXME in privacy.rs.

We might want to do something even better than just fixing this bug - it would be nice if we could make the error messages a bit clearer as to where exactly the error is (which namespace, but not using that terminology). See discussion in #12245.

### LINKED ISSUE #31779: A private module can be used outside its containing module
Consider the following code:
```rust
mod foo {
    mod bar { // `bar` should only be visible inside `foo`
        pub struct S;
    }
    pub use self::bar::S;
}

impl foo::S {
    fn f() {}
    pub fn g() {}
}

fn main() {
    foo::bar::S::f(); //< yet this line compiles
    // foo::bar::S::g(); //< this line would give the correct privacy error
}
```

### PR DESCRIPTION
**Pull request by jseyfried**
This PR privacy checks paths as they are resolved instead of in `librustc_privacy` (fixes #12334 and fixes #31779). This removes the need for the `LastPrivate` system introduced in PR #9735, the limitations of which cause #31779.

This PR also reports privacy violations in paths to intra- and inter-crate items the same way -- it always reports the first inaccessible segment of the path.

Since it fixes #31779, this is a [breaking-change]. For example, the following code would break:

``` rust
mod foo {
    pub use foo::bar::S;
    mod bar { // `bar` should be private to `foo`
        pub struct S;
    }
}

impl foo::S {
    fn f() {}
}

fn main() {
    foo::bar::S::f(); // This is now a privacy error
}
```

r? @alexcrichton

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nrc @petrochenkov @nikomatsakis

**Comment by petrochenkov** [comment]
Reviewed.

**Comment by alexcrichton** [comment]
Thanks for the PR @jseyfried! I may unfortunately not be the best reviewer for this as so much of resolve and privacy have changed since this was originally implemented, but I can at least add my 2cents!

Historically privacy and resolve were entangled, but this ended up leading to tons of really weird resolution problems. The major motivation for moving all of privacy to its own separate pass was to improve all these errors. At that point, the only privacy-related parts of resolve were that glob imports didn't bring private names into a module. 

Since then, though, maybe resolve has changed to be much more robust? I've definitely seen some awesome work of yours fly by in the interim :).

I suspect that the buggy program you've linked here can possibly be fixed by not jettisoning `LastPrivate` but patching up support for it. It looks like this approach may be cleaner, though? It at least has a negative diffstat!

**Comment by alexcrichton** [comment]
Looking over the tests, it looks like the error messages related to privacy get *even better* than where they are today. Specifically the messages seem much more precise in terms of what's actually private along the chain of a path.

With that in mind, if you're confident that this fits nicely into resolve as-is today and it won't regress resolution error messages, then it seems like a fine shift to me! I forget now what the `rustc_privacy` pass would actually do if this is removed, but it seems large enough that it surely does *something*.

**Comment by jseyfried** [comment]
@alexcrichton Thanks for the history and feedback! Resolve is indeed more robust now :)

I'm confident that this PR won't regress resolution error messages since it doesn't change the observable behavior of the import resolver or crate resolver; instead, it silently collects privacy errors during resolution and reports them after resolution is complete.

`rustc_privacy` still does a couple of passes that are unaffected by this PR, including checking for public types in private interfaces. The pass that used to privacy check paths, `PrivacyChecker`, still privacy checks struct fields (including the sometimes implicit fields in struct constructors) and non-UFCS methods. Field checking can be moved into `resolve` and non-UFCS method checking can be moved into `typeck`, but that is for another PR.

**Comment by jseyfried** [comment]
> I may unfortunately not be the best reviewer for this

r? @nikomatsakis

**Comment by jseyfried** [comment]
I added a commit addressing @petrochenkov's comments.
I tested the commit locally -- travis is isn't working right now.

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -3614,6 +3606,12 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
             }
         }
     }
+
+    fn report_privacy_errors(&self) {
+        for (span, string) in self.privacy_errors.iter() {
```
Comment (gereeter) [inline src/librustc_resolve/lib.rs]: Since `privacy_errors` is a `HashMap`, this will result in nondeterministic error ordering. Maybe the map should be changed to an `FnvHashMap` or a `BTreeMap`?

**Comment by petrochenkov** [comment]
I've added a couple more comments since you are going to rebase this anyway.

File: src/librustc_resolve/lib.rs (hunk 1 above)
Comment (jseyfried) [inline src/librustc_resolve/lib.rs]: Good point, I'll change it to a `BTreeMap`.

**Comment by nikomatsakis** [comment]
This seems like a big improvement. r=me.

**Comment by nikomatsakis** [comment]
To be clear: r=me after rebase + nits that others have already listed are addressed.

**Comment by jseyfried** [comment]
@nikomatsakis I rebased, addressed the comments, and cleaned up the history. Given the breakage in `rustc_metadata`, do you think this needs a crater run?

**Comment by nikomatsakis** [comment]
@jseyfried unclear, but I kicked off one just in case

**Comment by nikomatsakis** [comment]
The crater run somehow failed. I'm inclined to just land this, since the next beta has branched.
