### PR TITLE
Open a BCrypt algorithm handle

### LINKED ISSUE #101474: hashbrown tests crash on wine
When running `cargo test --target x86_64-pc-windows-gnu` on a Linux system with Wine installed, the tests crash with:
```
wine: Unhandled page fault on read access to 0000000000000081 at address 00000002D4D43703 (thread 010c), starting debugger...
```

Bisecting points to https://github.com/rust-lang/rust/commit/92086258e30ae59610a1b1097d97227377db0ada, I suspect the root cause might be https://github.com/rust-lang/rust/pull/101325.

cc @ChrisDenton

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #101474, supplants #101456.

Replaces use of a pseduo handle with manually opening a algorithm handle.

Most interesting thing here is the atomics.

r? @thomcc

### CODE REVIEW

File: library/std/src/sys/windows/rand.rs [hunk 1]
```diff
@@ -34,35 +33,77 @@ use crate::sys::c;
...
+
+struct Rng(c::BCRYPT_ALG_HANDLE);
+impl Rng {
+    // Open a handle to the RNG algorithm.
+    fn open() -> Result<Self, c::NTSTATUS> {
+        use crate::sync::atomic::AtomicIsize;
+        use crate::sync::atomic::Ordering::{Acquire, Release};
+
+        // An atomic is used so we don't need to reopen the handle every time.
+        static HANDLE: AtomicIsize = AtomicIsize::new(0);
```
Comment (thomcc) [inline library/std/src/sys/windows/rand.rs:47]: Hmm... the fact that on WINE it crashes with a page fault at the address makes me think the HANDLEs for this really should be pointers, not `isize`.

File: library/std/src/sys/windows/rand.rs [hunk 2]
```diff
@@ -34,35 +33,77 @@ use crate::sys::c;
...
+                // If another thread opens a handle first then use that handle instead.
+                let result = HANDLE.compare_exchange(0, handle, Release, Acquire);
+                if let Err(previous_handle) = result {
+                    // Close our handle and return the previous one.
+                    unsafe { c::BCryptCloseAlgorithmProvider(handle, 0) };
+                    handle = previous_handle;
+                }
+                Ok(Self(handle))
+            } else {
+                Err(status)
```
Comment (thomcc) [inline library/std/src/sys/windows/rand.rs:69]: If this fails, we don't remember that fact, so we'll keep retrying `BCryptOpenAlgorithmProvider` every time.

Perhaps we should store `INVALID_HANDLE` (or some other sentinel) in the atomic in this case to indicate "opening failed, don't bother trying repeatedly", and return an Err if we see it.

File: library/std/src/sys/windows/rand.rs [hunk 3]
```diff
@@ -34,35 +33,77 @@ use crate::sys::c;
...
+    }
 }
 
 /// We can't use RtlGenRandom with UWP, so there is no fallback
 #[cfg(target_vendor = "uwp")]
 #[inline(never)]
-fn fallback_rng() -> (u64, u64) {
-    panic!("fallback RNG broken: RtlGenRandom() not supported on UWP");
+fn fallback_rng(rng_status: c::NTSTATUS) -> (u64, u64) {
+    panic!("RMG broken: {rng_status:#x} fallback RNG broken: RtlGenRandom() not supported on UWP");
```
Comment (BlackHoleFox) [inline library/std/src/sys/windows/rand.rs:108]: Typo nit:

```suggestion
    panic!("RNG broken: {rng_status:#x} fallback RNG broken: RtlGenRandom() not supported on UWP");
```

File: library/std/src/sys/windows/rand.rs (hunk 1 above)
Comment (ChrisDenton) [reply library/std/src/sys/windows/rand.rs:47]: I don't feel particularly strongly about this either way so fair enough. I don't think we should be treating these as pointers on our side though.

File: library/std/src/sys/windows/rand.rs (hunk 2 above)
Comment (ChrisDenton) [reply library/std/src/sys/windows/rand.rs:69]: I'm hopeful that case will now never be reached but I guess it does make sense to avoid having to try again if it is. I wouldn't use the `INVALID_HANDLE` constant though as that only has a meaning in the context of certain filesystem APIs. I mean, even if we use the same actual value I'd want to give it a different name to avoid conflating the two things.

File: library/std/src/sys/windows/rand.rs (hunk 3 above)
Comment (ChrisDenton) [reply library/std/src/sys/windows/rand.rs:108]: Thanks! That's embarrassing. 🙂

File: library/std/src/sys/windows/rand.rs (hunk 2 above)
Comment (ChrisDenton) [reply library/std/src/sys/windows/rand.rs:74]: I used a local constant instead, which I'm happier about. Also I wasn't sure what to return as the error so I picked something that seems reasonable enough to me.

**Comment by thomcc** [comment]
Thanks, looks great!

@bors r+

**Comment by ChrisDenton** [comment]
fixed formatting

@bors r=thomcc

File: library/std/src/sys/windows/rand.rs [hunk 4]
```diff
@@ -34,35 +33,94 @@ use crate::sys::c;
...
+    fn open() -> Result<Self, c::NTSTATUS> {
+        const BCRYPT_RNG_ALG_HANDLE: c::BCRYPT_ALG_HANDLE = ptr::invalid_mut(0x81);
+        let _ = (
+            c::BCryptOpenAlgorithmProvider,
+            c::BCryptCloseAlgorithmProvider,
+            c::BCRYPT_RNG_ALGORITHM,
+            c::STATUS_NOT_SUPPORTED,
+        );
+        Ok(Self(BCRYPT_RNG_ALG_HANDLE))
+    }
```
Comment (RalfJung) [inline library/std/src/sys/windows/rand.rs:51]: I am surprised to see a Miri special path here; usually we try to execute the real thing where feasible (and `BCryptOpenAlgorithmProvider` looks easy enough to fake). Also please Cc @rust-lang/miri when adding such a codepath.

Comment (thomcc) [reply library/std/src/sys/windows/rand.rs:51]: Yeah, for this I'd say it's better to just add the shims to miri.

Comment (ChrisDenton) [reply library/std/src/sys/windows/rand.rs:51]: Sorry! My intent was for this to be temporary until I was confident that the crash issue was addressed. Then we can go back to using `BCRYPT_USE_SYSTEM_PREFERRED_RNG` as the default and `BCryptOpenAlgorithmProvider` would be the fallback. I can submit a PR to undo tho.

Comment (RalfJung) [reply library/std/src/sys/windows/rand.rs:51]: Ah, if this is just temporary then implementing the shims in Miri would indeed not be worth it.
