### PR TITLE
Fix unused_assignments false positives from macros

### LINKED ISSUE #147648: nightly `unused_assignments` false positives for `miette::Diagnostic` fields
Starting with rustc 1.92.0-nightly (2300c2aef, 2025-10-12), the compiler’s `unused_assignments` lint now emits warnings in the following snippet which uses `miette` and `thiserror`

### Code

I tried this code:

```rust
#![warn(unused)]

use miette::{Diagnostic, NamedSource, SourceSpan};

#[derive(Debug, thiserror::Error, Diagnostic)]
enum MyError {
    #[error("malformed input")]
    Example {
        #[source_code]
        source_code: NamedSource<String>, // WARNING: value assigned to `source_code` is never read
        #[label]
        span: SourceSpan, // WARNING: value assigned to `span` is never read
    },
}

fn main() {
    let _error = MyError::Example {
        source_code: NamedSource::new("example", "fn main() {}".to_owned()),
        span: SourceSpan::from((0, 5)),
    };
}
```

I expected to see this happen: The code compiles without any error 

Instead, this happened: 

```
warning: value assigned to `source_code` is never read
  --> src/main.rs:10:9
   |
10 |         source_code: NamedSource<String>, // WARNING: value assigned to `source_code` is never read
   |         ^^^^^^^^^^^
   |
   = help: maybe it is overwritten before being read?
note: the lint level is defined here
  --> src/main.rs:1:9
   |
 1 | #![warn(unused)]
   |         ^^^^^^
   = note: `#[warn(unused_assignments)]` implied by `#[warn(unused)]`

warning: value assigned to `span` is never read
  --> src/main.rs:12:9
   |
12 |         span: SourceSpan, // WARNING: value assigned to `span` is never read
   |         ^^^^
   |
   = help: maybe it is overwritten before being read?

warning: `clippy-error` (bin "clippy-error") generated 2 warnings
```

### Version it worked on

It most recently worked on: 
```
rustc 1.92.0-nightly (be0ade2b6 2025-10-11)
binary: rustc
commit-hash: be0ade2b602bdfe37a3cc259fcc79e8624dcba94
commit-date: 2025-10-11
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.2
```

### Version with regression

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (2300c2aef 2025-10-12)
binary: rustc
commit-hash: 2300c2aef7dbc2a7bbbeaa9894d07d459abd9bc6
commit-date: 2025-10-12
host: aarch64-apple-darwin
release: 1.92.0-nightly
LLVM version: 21.1.2
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#147648

### CODE REVIEW

File: compiler/rustc_mir_transform/src/liveness.rs [hunk 1]
```diff
@@ -72,6 +72,14 @@ pub(crate) fn check_liveness<'tcx>(tcx: TyCtxt<'tcx>, def_id: LocalDefId) -> Den
         return DenseBitSet::new_empty(0);
     }
 
+    // Don't run unused pass for items generated by foreign macros
+    if tcx.def_span(parent).from_expansion()
+        && let Some(macro_def_id) = tcx.def_span(parent).ctxt().outer_expn_data().macro_def_id
+        && !macro_def_id.is_local()
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/liveness.rs]: Why `parent` and not `def_id`?
Should this use `tcx.def_span(parent).in_external_macro(tcx.sess.source_map())`?

Comment (chenyukang) [reply compiler/rustc_mir_transform/src/liveness.rs]: use `def_id` will remove the warning for this testcase:
https://github.com/chenyukang/rust/blob/f943606503b142b24edb2b20f77f1eb737fb9ed2/tests/ui/proc-macro/attributes-included.rs#L17
yeah, `tcx.def_span(parent).in_external_macro(tcx.sess.source_map())` is simpler.

**Comment by Kobzol** [comment]
@rust-timer build 4da4cc50d15322746cc27267d8ceab7810c033d1

**Comment by Kobzol** [comment]
Posted a revert in https://github.com/rust-lang/rust/pull/149657.
