### PR TITLE
Better underline for E0057,E0060,E0061

### LINKED ISSUE #35214: E0057 needs to be updated to new format
From: src/test/compile-fail/E0057.rs

Error E0057 needs a span_label, updating it from:

```
error[E0057]: this function takes 1 parameter but 2 parameters were supplied
  --> src/test/compile-fail/E0057.rs:15:13
   |
15 |     let c = f(2, 3); //~ ERROR E0057
   |             ^^^^^^^
   |
   = note: the following parameter type was expected: (_,)
```

To:

```
error[E0057]: this function takes 1 parameter but 2 parameters were supplied
  --> src/test/compile-fail/E0057.rs:15:13
   |
15 |     let c = f(2, 3); //~ ERROR E0057
   |             ^^^^^^^ expected 1 parameter
   |
   = note: the following parameter type was expected: (_,)
```

Bonus 1: The note seems excessive.  Check other E0057 errors.  If it is not needed, remove the note.

Bonus 2: The span for the error could likely focus on the parameters rather than the whole call.

### PR DESCRIPTION
**Pull request by acrrd**
Fix #35214
Part of #35233

r? @jonathandturner

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -2449,6 +2449,12 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
         let mut expected_arg_tys = expected_arg_tys;
         let expected_arg_count = fn_inputs.len();
 
+        let sp_args = if args.len() > 0 {
+            Span { lo: args[0].span.lo, ..args[args.len()-1].span}
```
Comment (jonathandturner) [inline src/librustc_typeck/check/mod.rs]: Sadly, we can't safely mix spans like this because some arguments may come from incompatible locations (like from macros).

**Comment by jonathandturner** [comment]
I added a comment here about not being able to mix spans directly.

Instead, we'll need to use the span information that's already been calculated, or add it when it's safe to add.  If the latter is required, you should chat with some people in #rust-internals and see if they have ideas of how best to add it.

**Comment by acrrd** [comment]
I could not not fint any usable span, I'm asking on irc

**Comment by acrrd** [comment]
This is what I can achieve with a MultiSpan constructed from the args span
selection_002

**Comment by jonathandturner** [comment]
@nrc - is it okay to merge spans *if* those spans are on the same line?  See the above screenshot.  It seems like there are cases we could safely merge.

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -2424,9 +2424,20 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
         let expected_arg_count = fn_inputs.len();
 
-        fn parameter_count_error<'tcx>(sess: &Session, sp: Span, fn_inputs: &[Ty<'tcx>],
+        let sp_args = if args.len() > 0 {
+            args.iter().map(|arg| arg.span).collect::<Vec<Span>>()
+        } else {
+            vec!(sp)
+        };
+
+        fn parameter_count_error<'tcx>(sess: &Session, spans: Vec<Span>, fn_inputs: &[Ty<'tcx>],
```
Comment (KiChjang) [inline src/librustc_typeck/check/mod.rs]: Can we use an array for spans instead of a Vec here?

Comment (acrrd) [inline src/librustc_typeck/check/mod.rs]: The field of MultiSpan is a Vec<Span> so we have to constrct a Vec somewhere.

**Comment by jonathandturner** [comment]
I'm chatting with @nrc about what to do here, and we have some ideas.  RustConf is currently going on, so it may take us a few more days to get back to this.

**Comment by acrrd** [comment]
ok!

**Comment by jonathandturner** [comment]
@acrrd - wow, sorry for the looong delay.  I just landed a new method on CodeMap you can use to merge spans called `merge_spans`.  This should be able to safely let you merge the parameter spans.

**Comment by acrrd** [comment]
I merge spans until possible, this allow to underline at least some arguments also if the call is on multiple lines.

**Comment by jonathandturner** [comment]
@acrrd - sounds good

You may want to also run tidy on your code:

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

And fix the errors it has.  Looks like there are some in the current PR.

**Comment by acrrd** [comment]
Fixed

**Comment by jonathandturner** [comment]
Great!

The one last thing is to create a test for this in src/test/ui.  You can see some of the tests there and how to do them (specifically in src/test/ui/spans).

After you add a test I think we're good to go.

**Comment by acrrd** [comment]
Test added

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup
