### PR TITLE
Suppress unhelpful diagnostics for unresolved top level attributes

### LINKED ISSUE #67107: Incorrect outer `#![derive(Debug)]` emits too many errors
The following incorrect code:

```rust
#![derive(Debug)]
struct Coordinate(i32, i32);

fn main() {
    println!("{:?}", Coordinate(4, 2));
}
```
[generates the following output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef81d3cc909f2125bdf11680bd134f42):
```
error: `derive` may only be applied to structs, enums and unions
 --> src/main.rs:1:1
  |
1 | #![derive(Debug)]
  | ^^^^^^^^^^^^^^^^^ help: try an outer attribute: `#[derive(Debug)]`

error: cannot determine resolution for the derive macro `Debug`
 --> src/main.rs:1:11
  |
1 | #![derive(Debug)]
  |           ^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error[E0277]: `Coordinate` doesn't implement `std::fmt::Debug`
 --> src/main.rs:5:22
  |
5 |     println!("{:?}", Coordinate(4, 2));
  |                      ^^^^^^^^^^^^^^^^ `Coordinate` cannot be formatted using `{:?}`
  |
  = help: the trait `std::fmt::Debug` is not implemented for `Coordinate`
  = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
  = note: required by `std::fmt::Debug::fmt`
```

We should not emit the second value, given it could detect that the following element is an ADT it could internally treat it as `#[derive(Debug)]` so that no knock-down errors will happen.

### LINKED ISSUE #89566: Diagnostics: improve error message for incorrect inner attribute
I was assisting someone new to Rust and they were confused by an error message. This is the complete file of code they had written:

```rust
#![derive(Debug)]
struct Test {
    s: String,
}

fn main() {
}
```

Using rustc 1.55.0 (c8dfcfe04 2021-09-06) and rustc 1.57.0-nightly (f03eb6bef 2021-10-02), the compiler outputs the following error ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=148060b0318329961ad9ec4d1e7af0b4)):

```
error: cannot determine resolution for the attribute macro `derive`
 --> src/main.rs:1:4
  |
1 | #![derive(Debug)]
  |    ^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports
```

The fix is to use `#[derive]`, an outer attribute, rather than `#![derive]`, an inner attribute, but the compiler's error does not make that clear. And its suggestion to simplify macro imports doesn't help, as from the user's perspective, nothing is being imported in this source file!

I think a more specific error message that checks whether the inner attribute's name would fit as an outer attribute would be helpful here. A suggestion to remove the `!` would be even better. Annoyingly, having `#!` at the start of the file looked correct as it resembles a shebang.

Note that there _is_ a good error for using `#![]` instead of `#[]` in the general case. It even mentions the difference between inner and outer attributes in its message. It was just bad luck that this particular struct happened to be at the very start of the source file, so that error was not displayed.

I also spotted that in issue #67107, which has a _very_ similar piece of example code, the compiler used to provide a suggestion to "try an outer attribute". But, running that example on the latest stable and nightly, it looks like that suggestion is not being produced anymore.

### LINKED ISSUE #118455: A nonexistent inner attribute in `lib.rs` or `main.rs` breaks every procedural macro used within the entire crate
### Code

```Rust
#![some_nonexistent_attribute]

#[derive(Debug)]
pub struct SomeUserCode;
```

### Current output

```Shell
error: cannot find attribute `unsafe_code` in this scope
 --> src/lib.rs:1:4
  |
1 | #![some_nonexistent_attribute]
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot determine resolution for the attribute macro `derive`
 --> src/lib.rs:3:3
  |
3 | #[derive(Debug)]
  |   ^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: could not compile `bug-replica` (lib) due to 2 previous errors
```

### Desired output

```Shell
error: cannot find attribute `unsafe_code` in this scope
 --> src/lib.rs:1:4
  |
1 | #![some_nonexistent_attribute]
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `bug-replica` (lib) due to previous error
```

### Rationale and extra context

Having an inner nonexistent attribute in `lib.rs` or `main.rs` shouldn't break every procedural macro in the entire crate.

Usually, one would detect this error just after writing, but when contained within `#[cfg_attr(not(feature = "some-feature", invalid_attribute))]` it can remain undetected for a while due to rust-analyzer not reporting errors for every feature combination, and causing the developer to have to deal with potentially several hundred errors without any clear lead on what caused it.

When this bug is triggered while having and using, for example, a struct deriving `#[derive(Clone, Eq, PartialEq)]` or any other trait, it'll make the compiler emit an error for every attempt to use them. For moderately large projects this means suddenly having hundreds to thousands of errors not related to the actual change from one commit to the next one.

### Other cases

_No response_

### Anything else?

The bug exists at least in versions `1.72.1` (stable) and `1.76.0-nightly (a1a37735c 2023-11-23)`.
Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=45f3021f3d7420b1d8e76d3295d5e283

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #118455, unresolved top level attribute error didn't imported prelude and already have emitted an error, report builtin macro and attributes error by the way, so `check_invalid_crate_level_attr` in can ignore them.

Also fixes #89566, fixes #67107.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
(I should get to this on new year holidays.)

**Comment by petrochenkov** [comment]
Both this PR and https://github.com/rust-lang/rust/pull/118511 are hacks, but this one is better.

File: compiler/rustc_passes/src/check_attr.rs [hunk 1]
```diff
@@ -2517,11 +2513,6 @@ fn check_invalid_crate_level_attr(tcx: TyCtxt<'_>, attrs: &[Attribute]) {
         sym::start,
         sym::rustc_main,
         sym::unix_sigpipe,
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/check_attr.rs:2515]: What is this remaining list?
Most built-in attributes are invalid in crate root position, but only a few are listed here.

File: compiler/rustc_passes/src/check_attr.rs [hunk 2]
```diff
@@ -2503,12 +2503,8 @@ fn is_c_like_enum(item: &Item<'_>) -> bool {
     }
 }
 
-// FIXME: Fix "Cannot determine resolution" error and remove built-in macros
-// from this check.
+// builtin macros will be checked in resolve
```
Comment (petrochenkov) [inline compiler/rustc_passes/src/check_attr.rs:2506]:
```suggestion
// Built-in macros will be checked in resolve.
```

File: compiler/rustc_resolve/src/lib.rs [hunk 3]
```diff
@@ -1581,6 +1581,13 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         self.get_macro(res).is_some_and(|macro_data| macro_data.ext.builtin_name.is_some())
     }
 
+    fn is_builtin(&mut self, res: Res) -> bool {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs:1584]: This function is used once and doesn't make much sense outside of that context, better inline and remove.

File: compiler/rustc_resolve/src/macros.rs [hunk 4]
```diff
@@ -1,6 +1,8 @@
 //! A bunch of methods and structures more or less related to resolving macros and
 //! interface provided by `Resolver` to macro expander.
 
+use crate::ast::AttrStyle;
+use crate::ast::Attribute;
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:5]: Editor's import auto-insert (merge into the proper import list below).

File: compiler/rustc_resolve/src/macros.rs [hunk 5]
```diff
@@ -35,6 +37,7 @@ use rustc_span::edition::Edition;
 use rustc_span::hygiene::{self, ExpnData, ExpnKind, LocalExpnId};
 use rustc_span::hygiene::{AstPass, MacroKind};
 use rustc_span::symbol::{kw, sym, Ident, Symbol};
+use rustc_span::BytePos;
 use rustc_span::{Span, DUMMY_SP};
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:41]:
```suggestion
use rustc_span::{BytePos, Span, DUMMY_SP};
```
Another import auto-insert.

File: compiler/rustc_resolve/src/macros.rs [hunk 6]
```diff
@@ -695,6 +698,35 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         res.map(|res| (self.get_macro(res).map(|macro_data| macro_data.ext.clone()), res))
     }
 
+    fn report_invalid_crate_level_attr(&mut self, attrs: &[Attribute], name: Symbol) -> bool {
+        for attr in attrs.iter().filter(|attr| attr.style == AttrStyle::Inner) {
+            if attr.has_name(name) {
+                let tcx = self.tcx;
+                tcx.dcx().emit_err(errors::InvalidAttrAtCrateLevel {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:705]: Can the common logic here and in `compiler/rustc_passes/src/check_attr.rs` be shared?

File: compiler/rustc_resolve/src/macros.rs [hunk 7]
```diff
@@ -714,15 +746,28 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
-                // However, non-speculative `resolve_path` can successfully return private items
+                // Special cases:
+                // 1. non-speculative `resolve_path` can successfully return private items
                 // even if speculative `resolve_path` returned nothing previously, so we skip this
                 // less informative error if the privacy error is reported elsewhere.
+                // 2. issue #118455, unresolved top level attribute error didn't imported prelude and
+                // already have emitted an error, report builtin macro and attributes error by the way,
+                // so `check_invalid_crate_level_attr` in can ignore them.
+
+                let is_builtin = res.opt_def_id().map_or(false, |_| this.is_builtin(res));
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:757]: This can be moved into the `if` condition below.

File: compiler/rustc_resolve/src/macros.rs [hunk 8]
```diff
@@ -714,15 +746,28 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
                 if this.privacy_errors.is_empty() {
-                    this.dcx().emit_err(CannotDetermineMacroResolution {
-                        span,
-                        kind: kind.descr(),
-                        path: Segment::names_to_string(path),
-                    });
+                    let mut fallback = !is_builtin;
+                    if is_builtin && krate.id == ast::CRATE_NODE_ID {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:760]: `krate.id` is always `ast::CRATE_NODE_ID` (at least after expansion, and we are after expansion here).

Also, it seems like `fallback` can be simplified to a single `&&`.

File: compiler/rustc_passes/src/check_attr.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_passes/src/check_attr.rs:2515]: Any good idea for this?
I have found we have 
https://github.com/rust-lang/rust/blob/04521fd10e6eefb113ca1cefd02862599fd08640/compiler/rustc_feature/src/builtin_attrs.rs#L271

I tried to add a new helper for query:

```rust
pub fn is_normal_builtin_attr(name: Symbol) -> bool {
    BUILTIN_ATTRIBUTE_MAP.get(&name).is_some_and(|attr| match attr.type_ {
        AttributeType::CrateLevel => false,
        AttributeType::Normal => true,
    })
}
```

It turns out `Normal` in `BUILTIN_ATTRIBUTES` means the attribute may used at `CrateLevel` or other item level, for example `warn`, `allow`, etc.

`CrateLevel` is right(means it can only be used at crate level).

We need a list of builtin attributes which can not be used at crate level...

File: compiler/rustc_resolve/src/macros.rs (hunk 6 above)
Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: seems not easy to share the common logic, but I moved InvalidAttrAtCrateLevel into `rustc_attr` crate, so we only have the duplicated diagnostic resources in different components.

File: compiler/rustc_passes/src/check_attr.rs (hunk 1 above)
Comment (petrochenkov) [reply compiler/rustc_passes/src/check_attr.rs:2515]: Ok, let's keep this list as is for now.

File: compiler/rustc_resolve/src/macros.rs [hunk 9]
```diff
@@ -689,6 +691,32 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
         res.map(|res| (self.get_macro(res).map(|macro_data| macro_data.ext.clone()), res))
     }
 
+    fn report_invalid_crate_level_attr(&mut self, attrs: &[Attribute], name: Symbol) -> bool {
+        for attr in attrs.iter().filter(|attr| attr.style == AttrStyle::Inner) {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:695]:
```suggestion
        for attr in attrs {
```
Redundant condition, crate attributes are inner by definition.

File: compiler/rustc_resolve/src/macros.rs [hunk 10]
```diff
@@ -708,15 +736,29 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                // so `check_invalid_crate_level_attr` in can ignore them.
+
                 if this.privacy_errors.is_empty() {
-                    this.dcx().emit_err(CannotDetermineMacroResolution {
-                        span,
-                        kind: kind.descr(),
-                        path: Segment::names_to_string(path),
-                    });
+                    if this.is_builtin_macro(res)
+                        || this.builtin_attrs_bindings.values().any(|b| b.res() == res)
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:749]: What these two conditions try to achieve?
Why is `CannotDetermineMacroResolution` reporting put under them?
`CannotDetermineMacroResolution` should be reported for anything, not just built-in macros and attributes.

Also, I don't think we ever going to report `CannotDetermineMacroResolution` for built-in *attributes*, they are always reported successfully.

File: compiler/rustc_resolve/src/macros.rs [hunk 11]
```diff
@@ -708,15 +736,29 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                    {
+                        if this.report_invalid_crate_level_attr(&krate.attrs, path[0].ident.name) {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:751]: What if the path has more than one segment?

File: compiler/rustc_resolve/src/macros.rs [hunk 12]
```diff
@@ -708,15 +736,29 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
+                            return;
+                        }
+                        if this.tcx.dcx().has_errors().is_none() {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:754]: This change is orthogonal to the rest of the PR, it has nothing to do with crate-level attributes.

I think we can skip following `CannotDetermineMacroResolution` errors if one `CannotDetermineMacroResolution` was reported.
But it's better done in a separate PR.

**Comment by petrochenkov** [comment]
Could we actually land the `CannotDetermineMacroResolution` deduplication change (https://github.com/rust-lang/rust/pull/118533#discussion_r1468437191) *before* this PR?
It seems like an unambiguous improvement, but the crate-level attribute logic here is more questionable.
@rustbot author

File: compiler/rustc_resolve/src/macros.rs (hunk 12 above)
Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs]: On a second look, it's fine to skip `CannotDetermineMacroResolution` if *any* other error was reported.
They are useless by themselves, and only need to be reported if the compilation otherwise succeeds.

Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs]: It is even possible that this error can be turned into `span_delayed_bug`, could you check?

Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: yes, this is a simple fix for #118455, I can land it separately.

my crate-level logic here is also trying to resolve this issue (#89566, #67107)

```rust
#![derive(Debug)]
struct Test {
    s: String,
}

fn main() {
}

```

the output is:
```
error: cannot determine resolution for the attribute macro `derive`
 --> ./t/derive.rs:1:4
  |
1 | #![derive(Debug)]
  |    ^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: `derive` attribute cannot be used at crate level
 --> ./t/derive.rs:1:1
  |
1 | #![derive(Debug)]
  | ^^^^^^^^^^^^^^^^^
2 | struct Test {
  |        ---- the inner attribute doesn't annotate this struct
  |
help: perhaps you meant to use an outer attribute
  |
1 - #![derive(Debug)]
1 + #[derive(Debug)]
  |
```

the crate-level logic is trying to report only:

```console
error: `derive` attribute cannot be used at crate level
 --> ./t/derive.rs:1:1
  |
1 | #![derive(Debug)]
  | ^^^^^^^^^^^^^^^^^
  |
help: perhaps you meant to use an outer attribute
  |
1 - #![derive(Debug)]
1 + #[derive(Debug)]
  |
```

Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: > It is even possible that this error can be turned into `span_delayed_bug`, could you check?

ah, seems a good idea, maybe we can solve these two kinds of issue!
let me check.

Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: only this case can not be handled:

```rust
use std as derive;

#[derive(Default)] //~ ERROR cannot determine resolution for the attribute macro `derive`
struct S;

fn main() {}

```

Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: let's stash this error!
it will reported if no other errors reported, seems work like a charm.

File: compiler/rustc_resolve/src/macros.rs [hunk 13]
```diff
@@ -10,7 +10,9 @@ use crate::{BuiltinMacroState, Determinacy, MacroData};
 use crate::{DeriveData, Finalize, ParentScope, ResolutionError, Resolver, ScopeSet};
 use crate::{ModuleKind, ModuleOrUniformRoot, NameBinding, PathResult, Segment, ToNameBinding};
 use rustc_ast::expand::StrippedCfgItem;
-use rustc_ast::{self as ast, attr, Crate, Inline, ItemKind, ModKind, NodeId};
+use rustc_ast::{
+    self as ast, attr, AttrStyle, Attribute, Crate, Inline, ItemKind, ModKind, NodeId,
+};
```
[the remark this answers is not in the document]
Comment (chenyukang) [reply compiler/rustc_resolve/src/macros.rs]: I can not keep single-lien style, since this is the result comes from `x fmt .`.

**Comment by chenyukang** [comment]
@rustbot ready

How about this version, seems a small change and suppresses a lot of unnecessary messages.

File: compiler/rustc_resolve/src/macros.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply compiler/rustc_resolve/src/macros.rs]: Long imports can be split into multiple imports, like it's done in all crates following this style.

File: compiler/rustc_errors/src/lib.rs [hunk 14]
```diff
@@ -509,6 +509,7 @@ pub enum StashKey {
     MaybeForgetReturn,
     /// Query cycle detected, stashing in favor of a better error.
     Cycle,
+    MacroResolutionError,
```
Comment (petrochenkov) [inline compiler/rustc_errors/src/lib.rs:512]:
```suggestion
    UndeterminedMacroResolution,
```
More specific.

File: compiler/rustc_resolve/src/macros.rs [hunk 15]
```diff
@@ -703,21 +704,21 @@ impl<'a, 'tcx> Resolver<'a, 'tcx> {
...
-                    });
-                }
+                // less informative error if no other error is reported elsewhere.
+
+                let err = this.dcx().create_err(CannotDetermineMacroResolution {
+                    span,
+                    kind: kind.descr(),
+                    path: Segment::names_to_string(path),
+                });
+                err.stash(span, MacroResolutionError);
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/macros.rs:721]:
```suggestion
                err.stash(span, StashKey::MacroResolutionError);
```

**Comment by petrochenkov** [comment]
r=me after addressing https://github.com/rust-lang/rust/pull/118533#discussion_r1468433841 and remaining cleanup (preferably including auto-inserted imports).
@rustbot author
