### PR TITLE
fix std::thread docs are unclear regarding stack sizes

### LINKED ISSUE #102671: std::thread docs are unclear regarding stack sizes
### Location

https://doc.rust-lang.org/std/thread/#stack-size

### Summary

This says

> The default stack size for spawned threads is 2 MiB, though this particular stack size is subject to change in the future.

This is not correct, because it implies this is true for all platforms, but each platform sets their own default stack size. Even amongst unices, 2mib isn't always the case. https://github.com/rust-lang/rust/blob/02cd79afb8080fce8c8ce35533c54d8ecf8f390e/library/std/src/sys/unix/thread.rs#L14-L21

### PR DESCRIPTION
**Pull request by HintringerFabian**
Improves the documentation about the default stack size of a spawned thread
Fixes #102671

### CODE REVIEW

File: library/std/src/thread/mod.rs [hunk 1]
```diff
@@ -124,9 +124,9 @@
 //!
 //! ## Stack size
 //!
-//! The default stack size for spawned threads is 2 MiB, though this particular stack size is
-//! subject to change in the future. There are two ways to manually specify the stack size for
-//! spawned threads:
+//! The default stack size for spawned threads is 2 MiB on most platforms. Though this
```
Comment (the8472) [inline library/std/src/thread/mod.rs:127]: I don't think "most" is particularly useful. Maybe something like this

> The default stack size is platform-dependent and subject to change. Currently it is 2MB on all Tier-1 platforms.
