### PR TITLE
Use `def_path_str` for def id arg in `UnsupportedOpInfo`

### LINKED ISSUE #138730: Constant value evaluation failure prints debug representation
### Code

```Rust
extern "C" {
    static FOO: i32;
}

const BAR: i32 = FOO;
```

### Current output

```Shell
error[E0080]: evaluation of constant value failed
 --> src/lib.rs:5:18
  |
5 | const BAR: i32 = FOO;
  |                  ^^^ cannot access extern static (DefId(0:4 ~ playground[6412]::{extern#0}::FOO))

error[E0133]: use of extern static is unsafe and requires unsafe function or block
 --> src/lib.rs:5:18
  |
5 | const BAR: i32 = FOO;
  |                  ^^^ use of extern static
  |
  = note: extern statics are not controlled by the Rust type system: invalid data, aliasing violations or data races will cause undefined behavior

Some errors have detailed explanations: E0080, E0133.
For more information about an error, try `rustc --explain E0080`.
```

### Desired output

```Shell
error[E0080]: evaluation of constant value failed
 --> src/lib.rs:5:18
  |
5 | const BAR: i32 = FOO;
  |                  ^^^ cannot access extern static

error[E0133]: use of extern static is unsafe and requires unsafe function or block
 --> src/lib.rs:5:18
  |
5 | const BAR: i32 = FOO;
  |                  ^^^ use of extern static
  |
  = note: extern statics are not controlled by the Rust type system: invalid data, aliasing violations or data races will cause undefined behavior

Some errors have detailed explanations: E0080, E0133.
For more information about an error, try `rustc --explain E0080`.
```

### Rationale and extra context

_No response_

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: x86_64-unknown-linux-gnu
release: 1.85.1
LLVM version: 19.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compiler-errors**
We could alternatively just omit the def path from the label, but I think it's fine to keep around

Fixes #138730

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
I think it's nice to keep around, thanks!

File: compiler/rustc_const_eval/src/errors.rs [hunk 1]
```diff
@@ -917,9 +918,9 @@ impl ReportErrorExt for UnsupportedOpInfo {
             OverwritePartialPointer(ptr) | ReadPartialPointer(ptr) => {
                 diag.arg("ptr", ptr);
             }
-            ThreadLocalStatic(did) | ExternStatic(did) => {
-                diag.arg("did", format!("{did:?}"));
-            }
+            ThreadLocalStatic(did) | ExternStatic(did) => rustc_middle::ty::tls::with(|tcx| {
+                diag.arg("did", tcx.def_path_str(did));
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/errors.rs:922]: Does `DefId` not implement `IntoDiagArg` so that we can pass it here directly?
