### PR TITLE
Mention Result<!, E> in never docs.

### LINKED ISSUE #48096: Mention Result<!, E> in addition to Result<T, !> on never docs
While the latter is mentioned as a way of saying "this computation will never fail if it returns," the former is a way of saying "this computation will never return unless it fails."

For example, it makes a lot of sense to make `Command::exec` return `Result<!, Error>`, even though it currently just returns `Error` (which can't be changed without breaking stability guarantees). Demonstrating both cases seems like a good idea.

### PR DESCRIPTION
**Pull request by clarfonthey**
Fixes #48096.

### CODE REVIEW

File: src/libstd/primitive_docs.rs [hunk 1]
```diff
@@ -112,6 +112,8 @@ mod prim_bool { }
 ///
 /// # `!` and generics
 ///
+/// ## Infalliable errors
```
Comment (bluetech) [inline src/libstd/primitive_docs.rs]: Typo: Infalliable -> Infallible

File: src/libstd/primitive_docs.rs [hunk 2]
```diff
@@ -140,9 +142,59 @@ mod prim_bool { }
 /// [`Ok`] variant. This illustrates another behaviour of `!` - it can be used to "delete" certain
 /// enum variants from generic types like `Result`.
 ///
+/// ## Infinite loops
+///
+/// While [`Result<T, !>`] is very useful for removing errors, `!` can also be used to removed
```
Comment (bluetech) [inline src/libstd/primitive_docs.rs]: Typo: removed -> remove

File: src/libstd/primitive_docs.rs [hunk 3]
```diff
@@ -140,9 +142,59 @@ mod prim_bool { }
...
+///     }
+/// }
+/// ```
+///
+/// Now, when the server disconnects, we exit the loop with an error instead of panicking. While it
+/// might be intuitive to simply return the error, we might want to wrap it in a [`Result<!, E>`] 
+/// instead:
+///
+/// ```ignore (hypothetical-example)
+/// fn server_loop() -> Result<!, ConnectionError> {
```
Comment (scottmcm) [inline src/libstd/primitive_docs.rs]: I really like this example :+1:  A thought: with https://github.com/rust-lang/rust/pull/49162, it could even be 
```rust
fn main() -> Result<!, ConnectionError>
```

Also, I think the `Ok(` isn't needed because loop returns `!`, which will coerce to the `Result`: https://play.rust-lang.org/?gist=1cc0b7e8032bec565768ab95f42c454d&version=nightly

Comment (clarcharr) [reply src/libstd/primitive_docs.rs]: My main reasoning for not making this `main` is that the idea is that you might in principle want a larger loop that handles the error. Also, while I agree that the loop can be coerced to `Ok`, I think that wrapping in an `Ok` is best to draw parallels to a non-infinite loop. If it seems more clear the other way though, I'll definitely change it.

**Comment by pietroalbini** [comment]
Ping from triage @steveklabnik! This PR needs your review!

File: src/libstd/primitive_docs.rs (hunk 2 above)
Comment (steveklabnik) [reply src/libstd/primitive_docs.rs]: same

File: src/libstd/primitive_docs.rs [hunk 4]
```diff
@@ -140,9 +142,59 @@ mod prim_bool { }
...
+/// ## Infinite loops
+///
+/// While [`Result<T, !>`] is very useful for removing errors, `!` can also be used to removed
+/// successes as well. If we think of [`Result<T, !>`] as "if this function returns, it has not
+/// errored," we get a very intuitive idea of [`Result<!, E>`] as well: if the function returns, it
+/// *has* errored.
+///
+/// For example, consider the case of a simple web server, which can be simplified to:
+///
+/// ```ignore (hypothetical-example)
```
Comment (steveklabnik) [inline src/libstd/primitive_docs.rs]: I've never seen this notation, does this work?

File: src/libstd/primitive_docs.rs (hunk 3 above)
Comment (steveklabnik) [reply src/libstd/primitive_docs.rs]: I'd prefer to leave off the Ok, but I can agree that this being not main makes a lot of sense

**Review by steveklabnik — CHANGES_REQUESTED** [review]
Some typos, but other than that, looks good! Thank you!

File: src/libstd/primitive_docs.rs (hunk 4 above)
Comment (clarcharr) [reply src/libstd/primitive_docs.rs]: I actually copied it from an example earlier in the file, so, I assume so?

File: src/libstd/primitive_docs.rs (hunk 3 above)
Comment (clarcharr) [reply src/libstd/primitive_docs.rs]: I'll leave off the `Ok` and explain the coercion.

**Comment by clarcharr** [comment]
I'll try and make the desired changes later today.

**Comment by clarcharr** [comment]
Actually made the changes; sorry it took so long.

**Comment by TimNN** [comment]
Ping from triage @steveklabnik ! This PR is awaiting your review.

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks!

File: src/libstd/primitive_docs.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/libstd/primitive_docs.rs]: It doesn't do anything. It's recognized as non-rust code. That's pretty much all.
