### PR TITLE
Fix a byte/char confusion issue in the error emitter

### LINKED ISSUE #44023: nightly ICE: panicked in /checkout/src/libcore/str/mod.rs:2188:4
```bash
$ rustc-nightly --version
rustc 1.21.0-nightly (8c303ed87 2017-08-20)
$ 
$ RUST_BACKTRACE=full rustc-nightly tmp.rs
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (8c303ed87 2017-08-20) running on i686-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'byte index 41 is not a char boundary; it is inside 'ი' (bytes 40..43) of `fn საჭმელად_გემრიელი_სადილი ( ) -> isize {`', /checkout/src/libcore/str/mod.rs:2188:4
stack backtrace:
   0: 0xf7514e9a - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h80d78ba3b40687b5
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: 0xf750fc22 - std::sys_common::backtrace::_print::h47b9b32fe06dd6eb
                       at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: 0xf7520c7e - std::panicking::default_hook::{{closure}}::h006dcf643a2d1ee4
                       at /checkout/src/libstd/sys_common/backtrace.rs:60
                       at /checkout/src/libstd/panicking.rs:381
   3: 0xf75209ad - std::panicking::default_hook::h1e56c296d63316e2
                       at /checkout/src/libstd/panicking.rs:391
   4: 0xf752119b - std::panicking::rust_panic_with_hook::h218401524ff20a29
                       at /checkout/src/libstd/panicking.rs:611
   5: 0xf7521003 - std::panicking::begin_panic::h1668556d5aa9a913
                       at /checkout/src/libstd/panicking.rs:572
   6: 0xf7520f86 - std::panicking::begin_panic_fmt::h1ac0ef5f67ba5408
                       at /checkout/src/libstd/panicking.rs:522
   7: 0xf7520eed - rust_begin_unwind
                       at /checkout/src/libstd/panicking.rs:498
   8: 0xf7570736 - core::panicking::panic_fmt::h121b79d1b9922ab6
                       at /checkout/src/libcore/panicking.rs:71
   9: 0xf7571813 - core::str::slice_error_fail::h0212fbcc0a2225c6
                       at /checkout/src/libcore/str/mod.rs:0
  10: 0xf5ca5f89 - rustc_errors::emitter::EmitterWriter::emit_message_default::h9754044246ad7a16
  11: 0xf5c98f46 - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit::h60cb475a7f977bf4
  12: 0xf5c9803f - rustc_errors::diagnostic_builder::DiagnosticBuilder::emit::hc6a62a688f6076fb
  13: 0xf6dc2a5a - <rustc_typeck::check::coercion::CoerceMany<'gcx, 'tcx, 'exprs, E>>::coerce_inner::heb5f23cce9e8fc20
  14: 0xf6e310f9 - rustc_typeck::check::FnCtxt::check_block_with_expected::{{closure}}::h4f39835360e65072
  15: 0xf6e307d2 - rustc_typeck::check::FnCtxt::check_block_with_expected::hc9d159585b24dec2
  16: 0xf6e231d8 - rustc_typeck::check::FnCtxt::check_expr_kind::h67e77ffa77c67699
  17: 0xf6e21aa7 - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::ha1b30e1074fc5f8c
  18: 0xf6e1d8df - rustc_typeck::check::FnCtxt::check_return_expr::hc64bf1c86107a0e0
  19: 0xf6e0eb42 - rustc_typeck::check::check_fn::hcbeacbf8e9fed71b
  20: 0xf6e08418 - rustc_typeck::check::typeck_tables_of::{{closure}}::h57b0292d6f023ad7
  21: 0xf6e07e24 - rustc_typeck::check::typeck_tables_of::h43378384ce7decaa
  22: 0xf62b06e5 - rustc::dep_graph::graph::DepGraph::with_task::hae4e83d803c099b9
  23: 0xf64ed822 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get::h2453eccfce7ac8a7
  24: 0xf6528423 - rustc::ty::maps::TyCtxtAt::typeck_tables_of::h76cd939430aaebde
  25: 0xf65240fc - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of::h8a9d1c980f6af18f
  26: 0xf6e070da - rustc_typeck::check::typeck_item_bodies::h12aa5076199503b1
  27: 0xf62b04bd - rustc::dep_graph::graph::DepGraph::with_task::hab0342f2a47ea8cc
  28: 0xf64ec3e8 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get::hc9ed0514ce4d8544
  29: 0xf65282c5 - rustc::ty::maps::TyCtxtAt::typeck_item_bodies::h9777cbdadfc94eaa
  30: 0xf6524099 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies::hbb96b015c8ed480a
  31: 0xf6e6389e - rustc_typeck::check_crate::he7e69726bde9082c
  32: 0xf763c706 - rustc::ty::context::TyCtxt::create_and_enter::h54fe8ddc7b2f2638
  33: 0xf76a2e43 - rustc_driver::driver::compile_input::h36c200773836acf5
  34: 0xf76bc575 - rustc_driver::run_compiler::hdf3c0b5b5e4bbadc
  35: 0xf75fbcaf - std::sys_common::backtrace::__rust_begin_short_backtrace::h9143dfc110593bba
  36: 0xf755df82 - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:98
  37: 0xf762dae1 - <F as alloc::boxed::FnBox<A>>::call_box::h7d6c81c9ff90eab5
  38: 0xf751fcbb - std::sys::imp::thread::Thread::new::thread_start::h505201887c39140f
                       at /checkout/src/liballoc/boxed.rs:692
                       at /checkout/src/libstd/sys_common/thread.rs:21
                       at /checkout/src/libstd/sys/unix/thread.rs:84
  39: 0xf5c0f294 - start_thread
  40: 0xf73a405d - __clone
  41:        0x0 - <unknown>

$ 
$ cat tmp.rs
#![feature(non_ascii_idents)] 

pub fn main () {} 

fn საჭმელად_გემრიელი_სადილი ( ) -> isize {
} 
$ 
```

### LINKED ISSUE #44078: Compiler panic when string literal contains emoji followed by a quote
When I try to compile the following incorrect code:

```
fn main() {
    println!("💞"");
}
```

This happen:
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'byte index 16 is not a char boundary; it is inside '💞' (bytes 14..18) of `    println!("💞"");`', src/libcore/str/mod.rs:2161
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

Version information:

> rustc --version --verbose
> rustc 1.19.0 (0ade33941 2017-07-17)
> binary: rustc
> commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
> commit-date: 2017-07-17
> host: x86_64-apple-darwin
> release: 1.19.0
> LLVM version: 4.0

Backtrace:
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::str::slice_error_fail
   9: rustc_errors::emitter::EmitterWriter::emit_message_default
  10: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
  11: rustc_errors::Handler::emit
  12: rustc_errors::Handler::span_fatal
  13: syntax::parse::lexer::StringReader::fatal_span_
  14: syntax::parse::lexer::StringReader::next_token_inner
  15: syntax::parse::lexer::StringReader::advance_token
  16: syntax::parse::lexer::StringReader::try_next_token
  17: syntax::parse::lexer::StringReader::real_token
  18: syntax::parse::lexer::tokentrees::<impl syntax::parse::lexer::StringReader<'a>>::parse_token_tree
  19: syntax::parse::lexer::tokentrees::<impl syntax::parse::lexer::StringReader<'a>>::parse_token_tree
  20: syntax::parse::lexer::tokentrees::<impl syntax::parse::lexer::StringReader<'a>>::parse_all_token_trees
  21: syntax::parse::filemap_to_stream
  22: syntax::parse::filemap_to_parser
  23: syntax::parse::parse_crate_from_file
  24: rustc_driver::driver::phase_1_parse_input::{{closure}}
  25: rustc_driver::driver::phase_1_parse_input
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler
```

### PR DESCRIPTION
**Pull request by est31**
Fixes #44078. Fixes #44023.

The start_col member is given in chars, while the code previously assumed it was given in bytes.

The more basic issue #44080 doesn't get fixed.

### CODE REVIEW

File: src/librustc_errors/emitter.rs [hunk 1]
```diff
@@ -311,7 +311,13 @@ impl EmitterWriter {
         if line.annotations.len() == 1 {
             if let Some(ref ann) = line.annotations.get(0) {
                 if let AnnotationType::MultilineStart(depth) = ann.annotation_type {
-                    if source_string[0..ann.start_col].trim() == "" {
+                    if source_string.chars()
+                                    .enumerate()
+                                    .filter(|&(i, _)| i < ann.start_col)
+                                    .map(|(_, v)|v)
```
Comment (rkruppe) [inline src/librustc_errors/emitter.rs]: `.chars().take(ann.start_col)`?

Comment (est31) [reply src/librustc_errors/emitter.rs]: Oh right, that's better. Not very familiar with iterator APIs.

**Comment by eddyb** [comment]
I don't think @rkruppe can r+? Let me know when this is done.

File: src/librustc_errors/emitter.rs [hunk 2]
```diff
@@ -311,7 +311,11 @@ impl EmitterWriter {
         if line.annotations.len() == 1 {
             if let Some(ref ann) = line.annotations.get(0) {
                 if let AnnotationType::MultilineStart(depth) = ann.annotation_type {
-                    if source_string[0..ann.start_col].trim() == "" {
+                    if source_string.chars()
+                                    .take(ann.start_col)
+                                    .collect::<String>()
```
Comment (eddyb) [inline src/librustc_errors/emitter.rs]: Wait, why is this collecting to a string?

File: src/librustc_errors/emitter.rs [hunk 3]
```diff
@@ -311,7 +311,11 @@ impl EmitterWriter {
         if line.annotations.len() == 1 {
             if let Some(ref ann) = line.annotations.get(0) {
                 if let AnnotationType::MultilineStart(depth) = ann.annotation_type {
-                    if source_string[0..ann.start_col].trim() == "" {
```
Comment (eddyb) [inline src/librustc_errors/emitter.rs]: Why is the byte offset unavailable here? Converting to column should be delayed until the last moment IMO (and should take into account unicode grapheme width).

File: src/librustc_errors/emitter.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_errors/emitter.rs]: You can do the same btw with `.all(|c| c.is_whitespace())`.

**Comment by rkruppe** [comment]
@eddyb You're right, I can't r+, and I'm not particularly qualified to review this either. I told @est31 as much on IRC, should have mentioned it here as well. Someone else should review.

File: src/librustc_errors/emitter.rs (hunk 3 above)
Comment (est31) [reply src/librustc_errors/emitter.rs]: @eddyb I'm not sure what you mean but the start_col is given as columns, as per this comment: https://github.com/rust-lang/rust/blob/32b50e280faf56f21cbd82d1cf82cb4795535143/src/librustc_errors/snippet.rs#L123-L124

**Comment by est31** [comment]
@eddyb sorry I didn't know that @rkruppe didn't have r+ privileges. I just r?'d because he seemed to show interest and I didn't want to burden you...
