### PR TITLE
Record visibility of reexports for all items, not just type items

### LINKED ISSUE #73363: Cross-crate intra-doc links broken for functions when there's a doc(hidden) full-crate reexport involved
Discovered in https://github.com/rust-lang/futures-rs/pull/2177#discussion_r439041648

```rust
// crate main:
pub use dependency::future::{ready, Ready};

// crate dependency:

#[doc(hidden)]
pub mod __reexport {
    pub use crate::*;
}

pub mod future {
    mod ready {

        /// Link to [`ready`](function@ready)
        pub struct Ready;
        pub fn ready() {}

    }
    pub use self::ready::{ready, Ready};

}
```

The link to `ready` does not work.

### PR DESCRIPTION
**Pull request by Manishearth**
This fixes https://github.com/rust-lang/rust/issues/73363

Unfortunately I can't add a test for this since this bug is obscured by the cross-crate bug, being fixed in https://github.com/rust-lang/rust/issues/73363 . Tests will be added later.

cc @jyn514

r? @GuillaumeGomez

### CODE REVIEW

**Comment by Manishearth** [comment]
The test would basically be a test version of the code in https://github.com/rust-lang/rust/issues/73363 . We could also land this PR after #73363 , and I can just add tests in the PR itself. Either way, would be nice to get code review while we wait for this PR stack to move forward.

**Comment by jyn514** [comment]
> The test would basically be a test version of the code in #73363 . We could also land this PR after #73363 , and I can just add tests in the PR itself.

I think that would be easier to do, with you rebasing off of/cherry-picking the commits from #73101.

**Comment by Manishearth** [comment]
Yep, that's what I'm doing locally, but I realized that the fix itself was independent of your stuff, it's just that it's impossible to _test_ without your stuff.

**Comment by Manishearth** [comment]
Another fix for this might be to not _visit_ hidden modules in the embargo visitor. This might break things.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Should we wait for @jyn514's work to be merged first? Otherwise r=me. Thanks @Manishearth !

**Comment by Manishearth** [comment]
Yes, that's what I was saying earlier. We have to wait since the test won't pass otherwise

**Comment by jyn514** [comment]
@rustbot modify labels: -S-blocked +S-waiting-on-author

https://github.com/rust-lang/rust/pull/73101 just landed so I think this should be good to go after a rebase :)

File: src/test/rustdoc/intra-doc-crate/auxiliary/hidden.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+#![crate_name = "hidden_dep"]
+#![deny(intra_doc_resolution_failure)]
```
Comment (jyn514) [inline src/test/rustdoc/intra-doc-crate/auxiliary/hidden.rs:2]: I made the same mistake in my PR. We should probably have `deny(unknown_lints)` on by default in UI-tests.

```suggestion
#![deny(intra_doc_link_resolution_failure)]
```

File: src/test/rustdoc/intra-doc-crate/hidden.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// aux-build:hidden.rs
+// build-aux-docs
+#![deny(intra_doc_resolution_failure)]
```
Comment (jyn514) [inline src/test/rustdoc/intra-doc-crate/hidden.rs:3]:
```suggestion
#![deny(intra_doc_link_resolution_failure)]
```

**Comment by Manishearth** [comment]
@bors r=GuillaumeGomez

no need to rebase, bors will handle it

**Comment by jyn514** [comment]
> We could also land this PR after #73363 , and I can just add tests in the PR itself.

Did you ever add that test?
