### PR TITLE
Fix UB in `std::sys::os::getenv()`

### LINKED ISSUE #114949: Possible data race & use-after-free in std::env::var for unix implementation
Investigating library sources for [std::os::env::var/set_var](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/os.rs#L594), I have found that the copying of the env variable value is performed not under the lock:

```rust
pub fn getenv(k: &OsStr) -> Option<OsString> {
    // environment variables with a nul byte can't be set, so their value is
    // always None as well
    let s = run_with_cstr(k.as_bytes(), |k| {
        let _guard = env_read_lock();
        Ok(unsafe { libc::getenv(k.as_ptr()) } as *const libc::c_char)
       // lock is dropped here
    })
    .ok()?;
    if s.is_null() {
        None
    } else {
        // but access is here
        Some(OsStringExt::from_vec(unsafe { CStr::from_ptr(s) }.to_bytes().to_vec()))
    }
}
```
So there is a potential data race with setenv.

I tried this code with miri

```rust
fn main() {
    let t1 = std::thread::spawn(|| {
        let mut cnt = 0;
        for _ in 0..100000 {
            let var = std::env::var_os("HELLO");
            cnt += var.map(|v| v.len()).unwrap_or_default();
        }
        cnt
    });
    let t2 = std::thread::spawn(|| {
        for i in 0..100000 {
            let value = format!("helloooooooooooooo{i}");
            std::env::set_var("HELLO", &value);
        }
    });

    let cnt = t1.join().expect("ok");
    println!("{cnt}");
    t2.join();
}
```

And got

```
error: Undefined Behavior: Data race detected between (1) Read on thread `<unnamed>` and (2) Deallocate on thread `<unnamed>` at alloc3346+0x6. (2) just happened here
   --> /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:613:26
    |
613 |             cvt(unsafe { libc::setenv(k.as_ptr(), v.as_ptr(), 1) }).map(drop)
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Data race detected between (1) Read on thread `<unnamed>` and (2) Deallocate on thread `<unnamed>` at alloc3346+0x6. (2) just happened here
    |
help: and (1) occurred earlier here
   --> src/main.rs:30:23
    |
30  |             let var = std::env::var_os("HELLO");
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE (of the first span):
    = note: inside closure at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:613:26: 613:65
    = note: inside `std::sys::common::small_c_string::run_with_cstr::<(), [closure@std::sys::unix::os::setenv::{closure#0}::{closure#0}]>` at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/common/small_c_string.rs:43:18: 43:22
    = note: inside closure at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:611:9: 614:11
    = note: inside `std::sys::common::small_c_string::run_with_cstr::<(), [closure@std::sys::unix::os::setenv::{closure#0}]>` at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/common/small_c_string.rs:43:18: 43:22
    = note: inside `std::sys::unix::os::setenv` at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:610:5: 615:7
    = note: inside `std::env::_set_var` at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/env.rs:347:5: 347:31
    = note: inside `std::env::set_var::<&str, &std::string::String>` at /home/dmis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/env.rs:343:5: 343:43
note: inside closure
   --> src/main.rs:38:13
```

Have tried to move `Some(OsStringExt::from_vec(unsafe { CStr::from_ptr(s) }.to_bytes().to_vec()))` under the lock, but still got error with miri.

I was not able to trigger the real crash with it yet.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.71.1
LLVM version: 16.0.5
```

Bug was introduced by this commit: https://github.com/rust-lang/rust/commit/86974b83af48ee9e196da42730ec96ad646009c4   (PR: https://github.com/rust-lang/rust/pull/93668)
Before that changes, read was under the lock.

### PR DESCRIPTION
**Pull request by ShE3py**
Fixes #114949.

Reduced the loops to 1k iterations (100k was taking way too long), Miri no longer shows any UB.

@rustbot label +A-process +C-bug +I-unsound +O-unix

### CODE REVIEW

**Comment by Nekrolm** [comment]
Same changes seems also needed for https://github.com/rust-lang/rust/blob/master/library/std/src/sys/solid/os.rs#L173
and https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasi/os.rs#L230

there are same patterns

**Comment by ShE3py** [comment]
> Same changes seems also needed for https://github.com/rust-lang/rust/blob/master/library/std/src/sys/solid/os.rs#L173 and https://github.com/rust-lang/rust/blob/master/library/std/src/sys/wasi/os.rs#L230
> 
> there are same patterns

Thanks for pointing out, I also copied `env_read_lock()` to Solid as I guess it too should ignore poisoning (furthermore the result was ignored, resulting in UB as `_guard` was a `Result<Guard, NotAGuard>`).

**Comment by thomcc** [comment]
Wasn't the Err case of the guard something that held a nested guard?

File: library/std/src/sys/solid/os.rs [hunk 1]
```diff
@@ -81,6 +81,10 @@ pub fn current_exe() -> io::Result<PathBuf> {
 
 static ENV_LOCK: RwLock<()> = RwLock::new(());
 
+pub fn env_read_lock() -> impl Drop {
+    ENV_LOCK.read().unwrap_or_else(PoisonError::into_inner)
```
Comment (thomcc) [inline library/std/src/sys/solid/os.rs:85]: This is fine, but isn't actually needed.

**Comment by ShE3py** [comment]
> Wasn't the Err case of the guard something that held a nested guard?

```rs
pub type LockResult<Guard> = Result<Guard, PoisonError<Guard>>;

pub struct PoisonError<T> {
    guard: T,
}
```
You're right, the lock is acquired regardless of the variant, so the result can be used as-is.

**Comment by klensy** [comment]
Topic mentioned some loop iterations, but test didn't added here?

**Comment by ShE3py** [comment]
I couldn't find any text or code (to copy from) to make a Miri test, but if you have one, I can add a test.

**Comment by ChrisDenton** [comment]
Hm, this PR shouldn't be affecting windows targets, not even mingw? Also weird that it's a rustdoc failure. My guess would be it's spurious.
