### PR TITLE
Deny `FnDef` in patterns

### LINKED ISSUE #114658: inline_const_pat ICE: broken MIR unexpected comparison types fn() {uwu} and fn() {uwu}
### Code

```Rust
#![allow(incomplete_features, dead_code)]
#![feature(inline_const_pat)]

fn uwu() {}

fn owo() {
    let x = [];
    // note: this `if false` is necessary, otherwise the ICE is different
    if false {
        // uncomment this for the code to compile
        // (and it even lets you use some unsafe tricks to get the function item)
        // x[99] = loop {};
        match x[123] {
            const { uwu } => {},
            _ => {}
        }
    }
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6275ce809bed70b2636367c361346295)

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (03a119b0b 2023-08-07)
binary: rustc
commit-hash: 03a119b0b0e310d22d94399b24ed030056050f13
commit-date: 2023-08-07
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output
```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:4 ~ playground[b5a3]::owo) (Eq(<ZST>: fn() {uwu}, _1[_3])): unexpected comparison types fn() {uwu} and fn() {uwu}
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:4 ~ playground[b5a3]::owo) (Eq(<ZST>: fn() {uwu}, _1[_3])): unexpected comparison types fn() {uwu} and fn() {uwu}
  --> src/lib.rs:14:13
   |
14 |             const { uwu } => {},
   |             ^^^^^^^^^^^^^
   |
note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:2318:26
         0: <rustc_errors::HandlerInner>::emit_diagnostic
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         2: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
         3: rustc_borrowck::type_check::type_check
         4: rustc_borrowck::nll::compute_regions
         5: rustc_borrowck::do_mir_borrowck
         6: rustc_borrowck::mir_borrowck
         7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
         8: <rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
         9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        10: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
        11: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
        12: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#1}>
        13: rustc_interface::passes::analysis
        14: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        15: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        17: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        18: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#6}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        19: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
        20: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        21: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/alloc/src/boxed.rs:2007:9
        23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/alloc/src/boxed.rs:2007:9
        24: std::sys::unix::thread::Thread::new::thread_start
                   at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys/unix/thread.rs:108:17
        25: start_thread
        26: clone
  --> src/lib.rs:14:13
   |
14 |             const { uwu } => {},
   |             ^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/playground/rustc-ice-2023-08-09T15:58:06.807784224Z-18.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```
</p>
</details>

@rustbot label +requires-nightly +F-inline_const_pat +requires-incomplete-features

### LINKED ISSUE #114659: inline_const_pat ICE: primitive read not possible for type: fn() {uwu}
(note: this is very similar to #114658 but it does appear to be a different ICE)

### Code

```Rust
#![allow(incomplete_features, dead_code)]
#![feature(inline_const_pat)]

fn uwu() {}

#[allow(unconditional_panic)]
fn owo() {
    let x = [];
    // uncomment this for the code to compile
    // (and it even lets you use some unsafe tricks to get the function item)
    // x[99] = loop {};
    match x[123] {
        const { uwu } => {}
        _ => {}
    }
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=19e44591266c2b80ec5b33af25c76fac)

### Meta
`rustc --version --verbose`:
```
rustc 1.73.0-nightly (03a119b0b 2023-08-07)
binary: rustc
commit-hash: 03a119b0b0e310d22d94399b24ed030056050f13
commit-date: 2023-08-07
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output
```
error: internal compiler error: /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/compiler/rustc_const_eval/src/interpret/operand.rs:499:13: primitive read not possible for type: fn() {uwu}
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/compiler/rustc_const_eval/src/interpret/operand.rs:499:13: primitive read not possible for type: fn() {uwu}
  --> src/lib.rs:13:9
   |
13 |         const { uwu } => {}
   |         ^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/compiler/rustc_errors/src/lib.rs:979:33:
Box<dyn Any>
stack backtrace:
   0:     0x7f5644eac41c - std::backtrace_rs::backtrace::libunwind::trace::hca136959d52e6933
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5644eac41c - std::backtrace_rs::backtrace::trace_unsynchronized::h1c6a8e094542be1c
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5644eac41c - std::sys_common::backtrace::_print_fmt::h0da2398478023750
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f5644eac41c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6a573864c0f846
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5644f1191c - core::fmt::rt::Argument::fmt::he6fd7e0d0105a739
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/fmt/rt.rs:138:9
   5:     0x7f5644f1191c - core::fmt::write::h94f577461195b051
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f5644e9efce - std::io::Write::write_fmt::hd1a9413609baf17e
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/io/mod.rs:1714:15
   7:     0x7f5644eac204 - std::sys_common::backtrace::_print::h6209835ea4995823
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5644eac204 - std::sys_common::backtrace::print::he714f50554d615bf
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f5644eaf2fa - std::panicking::panic_hook_with_disk_dump::{{closure}}::h3bcbb7ff457b5172
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/panicking.rs:278:22
  10:     0x7f5644eaefe7 - std::panicking::panic_hook_with_disk_dump::he69919c08bd7c189
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/panicking.rs:312:9
  11:     0x7f5648089c99 - <rustc_driver_impl[a3b376697c1f9d40]::install_ice_hook::{closure#0} as core[5c8cf3808a1d57ad]::ops::function::FnOnce<(&core[5c8cf3808a1d57ad]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f5644eafba0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha904a5fedd1a6164
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/alloc/src/boxed.rs:2021:9
  13:     0x7f5644eafba0 - std::panicking::rust_panic_with_hook::h2a611f1a2fc1b8fc
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/panicking.rs:733:13
  14:     0x7f56487c3271 - std[daf38f5e158042c3]::panicking::begin_panic::<rustc_errors[7d56c13f6856642f]::ExplicitBug>::{closure#0}
  15:     0x7f56487c1d36 - std[daf38f5e158042c3]::sys_common::backtrace::__rust_end_short_backtrace::<std[daf38f5e158042c3]::panicking::begin_panic<rustc_errors[7d56c13f6856642f]::ExplicitBug>::{closure#0}, !>
  16:     0x7f5648854fb6 - std[daf38f5e158042c3]::panicking::begin_panic::<rustc_errors[7d56c13f6856642f]::ExplicitBug>
  17:     0x7f56487e1e1e - <rustc_errors[7d56c13f6856642f]::HandlerInner>::span_bug::<rustc_span[fbb5fda749e896f2]::span_encoding::Span, alloc[221a7a11f5e0e716]::string::String>
  18:     0x7f56487e1a8f - <rustc_errors[7d56c13f6856642f]::Handler>::span_bug::<rustc_span[fbb5fda749e896f2]::span_encoding::Span, alloc[221a7a11f5e0e716]::string::String>
  19:     0x7f56487e391b - rustc_middle[4e39534ad143988e]::util::bug::opt_span_bug_fmt::<rustc_span[fbb5fda749e896f2]::span_encoding::Span>::{closure#0}
  20:     0x7f56487e394a - rustc_middle[4e39534ad143988e]::ty::context::tls::with_opt::<rustc_middle[4e39534ad143988e]::util::bug::opt_span_bug_fmt<rustc_span[fbb5fda749e896f2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f56487e2f48 - rustc_middle[4e39534ad143988e]::ty::context::tls::with_context_opt::<rustc_middle[4e39534ad143988e]::ty::context::tls::with_opt<rustc_middle[4e39534ad143988e]::util::bug::opt_span_bug_fmt<rustc_span[fbb5fda749e896f2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f56470dd4b4 - rustc_middle[4e39534ad143988e]::util::bug::span_bug_fmt::<rustc_span[fbb5fda749e896f2]::span_encoding::Span>
  23:     0x7f56470de579 - <rustc_mir_transform[1767db2ea534335]::const_prop_lint::ConstPropagator>::check_binary_op
  24:     0x7f56470ac7c4 - <rustc_mir_transform[1767db2ea534335]::const_prop_lint::ConstPropagator as rustc_middle[4e39534ad143988e]::mir::visit::Visitor>::visit_body
  25:     0x7f564709e9bd - <rustc_mir_transform[1767db2ea534335]::const_prop_lint::ConstProp as rustc_mir_transform[1767db2ea534335]::pass_manager::MirLint>::run_lint
  26:     0x7f56475597ad - rustc_mir_transform[1767db2ea534335]::pass_manager::run_passes_inner
  27:     0x7f56471472ce - rustc_mir_transform[1767db2ea534335]::mir_drops_elaborated_and_const_checked
  28:     0x7f5646196a4e - rustc_query_impl[e5a2310130a23b66]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e5a2310130a23b66]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4e39534ad143988e]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f5646196a1e - <rustc_query_impl[e5a2310130a23b66]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core[5c8cf3808a1d57ad]::ops::function::FnOnce<(rustc_middle[4e39534ad143988e]::ty::context::TyCtxt, rustc_span[fbb5fda749e896f2]::def_id::LocalDefId)>>::call_once
  30:     0x7f564624276d - rustc_query_system[f19bd4f68b2513a8]::query::plumbing::try_execute_query::<rustc_query_impl[e5a2310130a23b66]::DynamicConfig<rustc_query_system[f19bd4f68b2513a8]::query::caches::VecCache<rustc_span[fbb5fda749e896f2]::def_id::LocalDefId, rustc_middle[4e39534ad143988e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e5a2310130a23b66]::plumbing::QueryCtxt, false>
  31:     0x7f56479f1bbf - rustc_query_impl[e5a2310130a23b66]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f5647564a9b - <rustc_session[5b68303f1d45cafc]::session::Session>::time::<(), rustc_interface[bbd54b40b3118f42]::passes::analysis::{closure#2}>
  33:     0x7f5647562b95 - rustc_interface[bbd54b40b3118f42]::passes::analysis
  34:     0x7f564759682a - rustc_query_impl[e5a2310130a23b66]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e5a2310130a23b66]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4e39534ad143988e]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7f5647596819 - <rustc_query_impl[e5a2310130a23b66]::query_impl::analysis::dynamic_query::{closure#2} as core[5c8cf3808a1d57ad]::ops::function::FnOnce<(rustc_middle[4e39534ad143988e]::ty::context::TyCtxt, ())>>::call_once
  36:     0x7f5647727968 - rustc_query_system[f19bd4f68b2513a8]::query::plumbing::try_execute_query::<rustc_query_impl[e5a2310130a23b66]::DynamicConfig<rustc_query_system[f19bd4f68b2513a8]::query::caches::SingleCache<rustc_middle[4e39534ad143988e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e5a2310130a23b66]::plumbing::QueryCtxt, false>
  37:     0x7f56477276f7 - rustc_query_impl[e5a2310130a23b66]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7f56476f8806 - <rustc_middle[4e39534ad143988e]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[a3b376697c1f9d40]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>>
  39:     0x7f564733dee1 - rustc_span[fbb5fda749e896f2]::set_source_map::<core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>, rustc_interface[bbd54b40b3118f42]::interface::run_compiler<core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>, rustc_driver_impl[a3b376697c1f9d40]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  40:     0x7f56473383b0 - std[daf38f5e158042c3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bbd54b40b3118f42]::util::run_in_thread_pool_with_globals<rustc_interface[bbd54b40b3118f42]::interface::run_compiler<core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>, rustc_driver_impl[a3b376697c1f9d40]::run_compiler::{closure#1}>::{closure#0}, core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>>
  41:     0x7f56478ff6f5 - <<std[daf38f5e158042c3]::thread::Builder>::spawn_unchecked_<rustc_interface[bbd54b40b3118f42]::util::run_in_thread_pool_with_globals<rustc_interface[bbd54b40b3118f42]::interface::run_compiler<core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>, rustc_driver_impl[a3b376697c1f9d40]::run_compiler::{closure#1}>::{closure#0}, core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c8cf3808a1d57ad]::result::Result<(), rustc_span[fbb5fda749e896f2]::ErrorGuaranteed>>::{closure#1} as core[5c8cf3808a1d57ad]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7f5644eba225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he74562cf0068d98a
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/alloc/src/boxed.rs:2007:9
  43:     0x7f5644eba225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h499befea8267854a
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/alloc/src/boxed.rs:2007:9
  44:     0x7f5644eba225 - std::sys::unix::thread::Thread::new::thread_start::h94d7dff6e38d6249
                               at /rustc/f88a8b71cebb730cbd5058c45ebcae1d4d9be377/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7f5644d80609 - start_thread
  46:     0x7f5644ca3133 - clone
  47:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/playground/rustc-ice-2023-08-09T16:04:06.91411877Z-27.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `owo`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
We can only see these via `const { .. }` patterns, which are unstable.

cc #76001 (tracking issue for inline const pats)

Fixes #114658
Fixes #114659

### CODE REVIEW

File: compiler/rustc_mir_build/src/build/matches/test.rs [hunk 1]
```diff
@@ -282,13 +282,20 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
-                    let expect = self.literal_operand(test.span, value);
-                    let val = Operand::Copy(place);
-                    self.compare(block, success, fail, source_info, BinOp::Eq, expect, val);
                 } else {
-                    bug!("`TestKind::Eq` should have two target blocks");
+                    let [success, fail] = *make_target_blocks(self) else {
+                        bug!("`TestKind::Eq` should have two target blocks");
+                    };
+                    assert_eq!(value.ty(), ty);
+                    if matches!(ty.kind(), ty::FnDef(..)) {
```
Comment (cjgillot) [inline compiler/rustc_mir_build/src/build/matches/test.rs:290]: `rustc_borrowck::type_check` only allows comparisons for a few types. Should we use the same list of allowed types here, instead of special-casing `FnDef`?

Comment (compiler-errors) [reply compiler/rustc_mir_build/src/build/matches/test.rs:290]: That list seems to just be `Ty::is_scalar` except for `FnDef`?

I actually don't really even know why `FnDef` is counted as scalar in `Ty::is_scalar`. Seems a bit misleading at best.

Comment (compiler-errors) [reply compiler/rustc_mir_build/src/build/matches/test.rs:290]: Though I don't totally understand what you mean here -- are you suggesting this should be an error instead?

**Comment by petrochenkov** [comment]
LGTM, assuming this shouldn't be an error.

AFAIR, "exotic" types in patterns produced errors some time ago, but maybe they do not now?
@rustbot author

**Comment by compiler-errors** [comment]
This isn't waiting on author -- I'm waiting for advice on how to proceed w/ this PR :smile_cat: 

@rustbot ready

**Comment by compiler-errors** [comment]
That is to say, I'm happy to either:
1. Land this PR as-is,
2. Make `FnDef`s in consts a hard error, guaranteed others also agree this is the right behavior (since this can happen only with unstable features, not sure if it necessarily even needs T-lang).

**Comment by petrochenkov** [comment]
In don't see the place which @cjgillot is talking about in https://github.com/rust-lang/rust/pull/114668#discussion_r1289177698, but let's make it an error for now.
@rustbot author
