### PR TITLE
Properly deal with weak alias types as self types of impls

### LINKED ISSUE #114216: lazy_type_alias:  causes error `no nominal type found for inherent implementation`
I tried this code:
`tests/rustdoc/deref/deref-typedef.rs`
```rust
#![crate_name = "foo"]

// @has 'foo/struct.Bar.html'
// @has '-' '//*[@id="deref-methods-FooJ"]' 'Methods from Deref<Target = FooJ>'
// @has '-' '//*[@class="impl-items"]//*[@id="method.foo_a"]' 'pub fn foo_a(&self)'
// @has '-' '//*[@class="impl-items"]//*[@id="method.foo_b"]' 'pub fn foo_b(&self)'
// @has '-' '//*[@class="impl-items"]//*[@id="method.foo_c"]' 'pub fn foo_c(&self)'
// @has '-' '//*[@class="impl-items"]//*[@id="method.foo_j"]' 'pub fn foo_j(&self)'
// @has '-' '//div[@class="sidebar-elems"]//h3/a[@href="#deref-methods-FooJ"]' 'Methods from Deref<Target=FooJ>'
// @has '-' '//*[@class="sidebar-elems"]//section//a[@href="#method.foo_a"]' 'foo_a'
// @has '-' '//*[@class="sidebar-elems"]//section//a[@href="#method.foo_b"]' 'foo_b'
// @has '-' '//*[@class="sidebar-elems"]//section//a[@href="#method.foo_c"]' 'foo_c'
// @has '-' '//*[@class="sidebar-elems"]//section//a[@href="#method.foo_j"]' 'foo_j'

pub struct FooA;
pub type FooB = FooA;
pub type FooC = FooB;
pub type FooD = FooC;
pub type FooE = FooD;
pub type FooF = FooE;
pub type FooG = FooF;
pub type FooH = FooG;
pub type FooI = FooH;
pub type FooJ = FooI;

impl FooA {
    pub fn foo_a(&self) {}
}

impl FooB {
    pub fn foo_b(&self) {}
}

impl FooC {
    pub fn foo_c(&self) {}
}

impl FooJ {
    pub fn foo_j(&self) {}
}

pub struct Bar;
impl std::ops::Deref for Bar {
    type Target = FooJ;
    fn deref(&self) -> &Self::Target { unimplemented!() }
}
```

without  `-Zcrate-attr=feature(lazy_type_alias)´: no warnings

with `-Zcrate-attr=feature(lazy_type_alias)`:

```
error[E0118]: no nominal type found for inherent implementation
  --> tests/rustdoc/deref/deref-typedef.rs:30:1
   |
30 | impl FooB {
   | ^^^^^^^^^ impl requires a nominal type
   |
   = note: either implement a trait on it or create a newtype to wrap it instead

error[E0118]: no nominal type found for inherent implementation
  --> tests/rustdoc/deref/deref-typedef.rs:34:1
   |
34 | impl FooC {
   | ^^^^^^^^^ impl requires a nominal type
   |
   = note: either implement a trait on it or create a newtype to wrap it instead

error[E0118]: no nominal type found for inherent implementation
  --> tests/rustdoc/deref/deref-typedef.rs:38:1
   |
38 | impl FooJ {
   | ^^^^^^^^^ impl requires a nominal type
   |
   = note: either implement a trait on it or create a newtype to wrap it instead

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0118`.
```

````
rustc 1.73.0-nightly (04abc370b 2023-07-28)
binary: rustc
commit-hash: 04abc370b9f3855b28172b65a7f7d5a433f41412
commit-date: 2023-07-28
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
````

### LINKED ISSUE #116100: lazy type alias: type parameters are not considered constrained in impls
Uplifted from https://github.com/rust-lang/rust/issues/112792#issuecomment-1713933644.

```rs
#![feature(lazy_type_alias)]
#![allow(incomplete_features)]

type Faa<A> = Foo<A>;
struct Foo<A>(A);

impl<A> Faa<A> {}
```

```
error[E0207]: the type parameter `A` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:11:6
  |
7 | impl<A> Faa<A> {}
  |      ^ unconstrained type parameter
```

### PR DESCRIPTION
**Pull request by fmease**
Fixes #114216.
Fixes #116100.

Not super happy about the two ad hoc “normalization” implementations for weak alias types:

1. In `inherent_impls`: The “peeling”, normalization to [“WHNF”][whnf]: Semantically that's exactly what we want (neither proper normalization nor shallow normalization would be correct here). Basically a weak alias type is “nominal” (well...^^) if the WHNF is nominal. [#97974](https://github.com/rust-lang/rust/pull/97974) followed the same approach.
2. In `constrained_generic_params`: Generic parameters are constrained by a weak alias type if the corresp. “normalized” type constrains them (where we only normalize *weak* alias types not arbitrary ones). Weak alias types are injective if the corresp. “normalized” type is injective.

Both have ad hoc overflow detection mechanisms.

**Coherence** is handled in #117164.

r? @oli-obk or types

[whnf]: https://en.wikipedia.org/wiki/Lambda_calculus_definition#Weak_head_normal_form

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/constrained_generic_params.rs [hunk 1]
```diff
@@ -43,26 +44,45 @@ pub fn parameters_for_impl<'tcx>(
...
+            ty::Alias(ty::Weak, alias) if !self.include_nonconstraining => {
+                if !self.tcx.recursion_limit().value_within_limit(self.depth) {
+                    return ControlFlow::Break(());
+                }
+                self.depth += 1;
+                return self
+                    .tcx
+                    .type_of(alias.def_id)
+                    .instantiate(self.tcx, alias.args)
+                    .visit_with(self);
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/constrained_generic_params.rs:84]: `ensure_sufficient_stack` might make sense here.

File: compiler/rustc_hir_analysis/src/constrained_generic_params.rs [hunk 2]
```diff
@@ -43,26 +44,45 @@ pub fn parameters_for_impl<'tcx>(
...
-                // projections are not injective
+            ty::Alias(ty::Projection | ty::Inherent | ty::Opaque, _)
+                if !self.include_nonconstraining =>
+            {
+                // Projections are not injective in general.
                 return ControlFlow::Continue(());
             }
+            ty::Alias(ty::Weak, alias) if !self.include_nonconstraining => {
+                if !self.tcx.recursion_limit().value_within_limit(self.depth) {
+                    return ControlFlow::Break(());
```
Comment (fmease) [inline compiler/rustc_hir_analysis/src/constrained_generic_params.rs:77]: We might want to `Continue` instead of `Break`, not sure.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/constrained_generic_params.rs:77]: What's the difference?

Comment (fmease) [reply compiler/rustc_hir_analysis/src/constrained_generic_params.rs:77]: Only affects the diagnostics (“found unconstrained param” vs. “overflow”) and that only in certain cases. E.g., given:

```rs
#![feature(lazy_type_alias)]
#![allow(incomplete_features)]

trait Trait {}
impl<T> Trait for (Loop<T>, T) {}
type Loop<T> = Loop<T>;

fn main() {}
```

* With `Break`: ``the type parameter `T` is not constrained``
* With `Continue`: 2× `` overflow evaluating the requirement `Loop<T>` ``

Comment (fmease) [reply compiler/rustc_hir_analysis/src/constrained_generic_params.rs:77]: What's happening here (pretty sure): With `Break` we immediately give up, therefore don't see the bare `T`, consider `T` unconstrained due to the overflow and report a fatal “unconstrained” error. With `Continue` we – well – continue and see that `T` is indeed constrained. Hence we reach normalization & the overflow. So nothing major basically.

Comment (fmease) [reply compiler/rustc_hir_analysis/src/constrained_generic_params.rs:77]: I guess I like `Continue` better, lemme change it.

**Comment by fmease** [comment]
Reminder to myself: Check if the following code leads to a cycle error:

```rs
#![feature(lazy_type_alias)]

pub struct I8<const F: i8>;

type Identity<T: ?Sized> = T;

impl Identity<I8<{i8::MIN}>> {
    pub fn foo(&self) {}
}
```

Guillaume just sent me a document of them about issues encountered with the previous pre-`ty::Weak` approaches. Namely, the code above (`ty::Weak` → `ty::Projection`/`#[lang = "identity"]`) resulted in a cycle: https://hackmd.io/EI_RO0oKQ9OhssvpMrEDQA#Impl-block-on-a-projection

**Comment by fmease** [comment]
Update: No, it doesn't lead to cycles and everything works flawlessly and `let _ = I8::<-128>.foo();` is `// check-pass`.

File: compiler/rustc_hir_analysis/src/constrained_generic_params.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_hir_analysis/src/constrained_generic_params.rs:85]: Yea please add it, otherwise this is just waiting for someone to generate an example that stack overflows the compiler.

**Comment by oli-obk** [comment]
> Check if the following code leads to a cycle error:

yea, the previous approach used full normalization, which causes issues. Just peeling away the weak aliases works around all of that.

Sad that we need these custom normalization routines, but that's kinda the conclusion we always came to when we discussed these cases...

**Comment by fmease** [comment]
Added an `ensure_sufficient_stack`.

> Sad that we need these custom normalization routines, but that's kinda the conclusion we always came to when we discussed these cases...

Yea :/ and I'm pretty sure we need to add more of them if we want to emulate some of the existing behavior of eager type aliases. E.g. for #114220 I bet we don't want to properly normalize either.

File: tests/ui/lazy-type-alias/inherent-impls.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+// check-pass
```
Comment (oli-obk) [inline tests/ui/lazy-type-alias/inherent-impls.rs:1]: These comments now need an `@`

**Comment by oli-obk** [comment]
@bors r-

ui tests now use `//@` headers

**Comment by fmease** [comment]
:facepalm: :+1:

**Comment by fmease** [comment]
Let's wait till green to make sure I didn't mess up the new `ui_test` syntax and Imma bors approve on behalf of you later.

**Comment by fmease** [comment]
I think the retry didn't register
@bors retry
