### PR TITLE
fix for `Self` not respecting tuple Ctor privacy

### LINKED ISSUE #111220: Tuple struct's private field can be accessed outside the defining module
I tried this code:

```rust
mod my {
    pub struct Foo(&'static str);
}

impl AsRef<str> for my::Foo {
    fn as_ref(&self) -> &str {
        let Self(s) = self;
        s
    }
}
```

I expected to see this happen: compilation should fail because the trait impl is defined outside of the module for the type but refers to its private field.

Instead, this happened: this compiled successfully

### Meta
This reproduces on the playground for stable Rust, version 1.69.0: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=20f12a0f682d8dd6530d75f1b5e7a8dd

### PR DESCRIPTION
**Pull request by fee1-dead**
This PR fixes #111220 by checking the privacy of tuple constructors using `Self`, so the following code now errors
```rust
mod my {
    pub struct Foo(&'static str);
}

impl AsRef<str> for my::Foo {
    fn as_ref(&self) -> &str {
        let Self(s) = self; // previously compiled, now errors correctly
        s
    }
}
```

### CODE REVIEW

File: compiler/rustc_privacy/src/lib.rs [hunk 1]
```diff
@@ -1309,6 +1309,23 @@ impl<'tcx> Visitor<'tcx> for TypePrivacyVisitor<'tcx> {
...
+                    // we're only interested in `Adt`s since only those have privacy
+                    let ty::Adt(adt_def, _) = self_ty.kind() else { return };
+                    let ctor = adt_def.non_enum_variant().ctor_def_id().unwrap();
+                    if !self.item_is_accessible(ctor) {
+                        self.tcx.sess.emit_err(CtorIsPrivate {
+                            span,
+                            def: self.tcx.def_path_str(adt_def.did()),
+                        });
+                    }
+                    debug!("hello");
```
Comment (m-ou-se) [inline compiler/rustc_privacy/src/lib.rs:1326]: hi 👋

**Comment by Nilstrieb** [comment]
Do we want a crater run here? I think it wouldn't hurt to see what happens, not that we won't ship a fix but maybe we want a grace period and an FCW (which, given that this was broke forever, could afford). Gonna start a try build for that.
@bors try

**Comment by fee1-dead** [comment]
@craterbot check

File: compiler/rustc_privacy/src/lib.rs (hunk 1 above)
Comment (BoxyUwU) [reply compiler/rustc_privacy/src/lib.rs]: *waves*

File: compiler/rustc_privacy/src/lib.rs [hunk 2]
```diff
@@ -1309,6 +1309,23 @@ impl<'tcx> Visitor<'tcx> for TypePrivacyVisitor<'tcx> {
         let def = match qpath {
             hir::QPath::Resolved(_, path) => match path.res {
                 Res::Def(kind, def_id) => Some((kind, def_id)),
+                // HACK: prevent using the `Self` ctor when the concrete type is private.
+                Res::SelfCtor(impl_) => {
```
Comment (lcnr) [inline compiler/rustc_privacy/src/lib.rs:1313]: it's very annoying, but we normalize before looking up the constructor iirc, so the following should still be an issue:
```rust
mod b {
    #[derive(Default)]
    pub struct A(u32);
}

pub trait B {
    fn f(&self);
}

pub trait Id {
    type Assoc;
}
impl<T> Id for T {
    type Assoc = Self;
}

impl B for <b::A as Id>::Assoc {
    fn f(&self) {
        let Self(a) = self;
        //~^ ERROR: tuple struct constructor `A` is private
        println!("{}", a);
    }
}

fn main() {
    let a = b::A::default();
    a.f();
}
```
while ugly, it might be safer to do the check in astconv or sth :thinking: I am not familiar with this code

Comment (fee1-dead) [reply compiler/rustc_privacy/src/lib.rs:1313]: It doesn't allow projections:

```
error: the `Self` constructor can only be used with tuple or unit structs
  --> /home/gh-fee1-dead/rust/tests/ui/privacy/issue-111220-tuple-struct-fields.rs:28:13
   |
LL |         let Self(a) = self;
   |             ^^^^^^^

error[E0164]: expected tuple struct or tuple variant, found self constructor `Self`
  --> /home/gh-fee1-dead/rust/tests/ui/privacy/issue-111220-tuple-struct-fields.rs:28:13
   |
LL |         let Self(a) = self;
   |             ^^^^^^^ not a tuple struct or tuple variant
```

Comment (lcnr) [reply compiler/rustc_privacy/src/lib.rs:1313]: what? :sweat_smile: this compiles on nightly: https://rust.godbolt.org/z/nM6vzrc5Y

how does your code change this '^^

Comment (fee1-dead) [reply compiler/rustc_privacy/src/lib.rs:1313]: Ahh, I turned `b::A::Assoc` into `(b::A,)` which isn't a tuple struct lol. This is indeed an issue, I will look into this when I get time.

Comment (fee1-dead) [reply compiler/rustc_privacy/src/lib.rs:1349]: I used `try_normalize_erasing_regions` which should fix this for `impl Trait for Foo::AssocTy`. Let me know if this should totally be at some other crate and not `rustc_privacy`. I mainly put this stuff here so I can use `item_is_accessible`.

Comment (lcnr) [reply compiler/rustc_privacy/src/lib.rs:1349]: I think normalizing it with the impl where bounds is still not enough as you can avoid it as follows (please add this as a test)
```rust
mod b {
    pub struct A(u32);
}

trait Id {
    type Assoc;
}
impl Id for b::A {
    type Assoc = b::A;
}
impl Id for u32 {
    type Assoc = u32;
}


trait Trait<T> {
    fn method(&self)
    where
        T: Id<Assoc = b::A>;
}

impl<T: Id> Trait<T> for <T as Id>::Assoc {
    fn method(&self)
    where
        T: Id<Assoc = b::A>,
    {
        let Self(a) = self;
        println!("{a}");
    }
}
```
You would have to normalize in the `param_env` of `self.current_item` I think but even then it feels somewhat dangerous.

Can you add a check to `instantiate_value_path` that the used ctor for is actually accessible :thinking: either completely move this check to there or at least `delay_span_bug` if we expect it to error.

Comment (compiler-errors) [reply compiler/rustc_privacy/src/lib.rs:1349]: Yeah, I think this could be moved to typeck.

**Comment by fee1-dead** [comment]
Moved to typeck.

@rustbot ready

**Comment by lcnr** [comment]
r=me after updating the PR description. I am also not sure whether I would consider this fix to be "temporary" :thinking: 

I guess we can mention this in the relnotes, even if it feels very unlikely that someone will depend on this. Crater did not show any regressions.

This PR fixes #111220 by checking the privacy of tuple constructors using `Self`, so the following code now errors
```rust
mod my {
    pub struct Foo(&'static str);
}

impl AsRef<str> for my::Foo {
    fn as_ref(&self) -> &str {
        let Self(s) = self; // previously compiled, now errors correctly
        s
    }
}
```
