### PR TITLE
Fix soundness issue for `replace_range` and `range`

### LINKED ISSUE #81138: String::replace_range is unsound
It's possible to use `String::replace_range` to create invalid strings containing broken Unicode. This happens because `replace_range` checks range bounds twice - first time to check parameter validity and second time for actually doing the splice.

```rust
use std::cell::Cell;
use std::ops::{Bound, RangeBounds};
use std::str;

struct EvilRange(Cell<bool>);

impl RangeBounds<usize> for EvilRange {
    fn start_bound(&self) -> Bound<&usize> {
        Bound::Included(if self.0.get() {
            &1
        } else {
            self.0.set(true);
            &0
        })
    }
    fn end_bound(&self) -> Bound<&usize> {
        Bound::Unbounded
    }
}

fn main() {
    let mut s = String::from("🦀");
    s.replace_range(EvilRange(Cell::new(false)), "");
    println!("{:?}", str::from_utf8(s.as_bytes()));
}
```

This will print `Utf8Error` showing that a string is not valid UTF-8.

### PR DESCRIPTION
**Pull request by dylni**
Fixes #81138 by only calling `start_bound` and `end_bound` once.

I also fixed the same issue for [`BTreeMap::range`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.range) and [`BTreeSet::range`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.range).

### CODE REVIEW

File: library/alloc/src/string.rs [hunk 1]
```diff
@@ -1553,18 +1553,21 @@ impl String {
         // Replace_range does not have the memory safety issues of a vector Splice.
         // of the vector version. The data is just plain bytes.
 
-        match range.start_bound() {
+        let start = range.start_bound();
```
Comment (bugadani) [inline library/alloc/src/string.rs:1556]: I think comments explaining this change might be beneficial here as well. With or without a big `// WARNING: do not inline this variable` :)

File: library/alloc/src/string.rs [hunk 2]
```diff
@@ -1553,18 +1553,21 @@ impl String {
...
-        match range.end_bound() {
+        let end = range.end_bound();
+        match end {
             Included(&n) => assert!(self.is_char_boundary(n + 1)),
             Excluded(&n) => assert!(self.is_char_boundary(n)),
             Unbounded => {}
         };
 
-        unsafe { self.as_mut_vec() }.splice(range, replace_with.bytes());
+        // Using `range` again would be unsound (#81138)
```
Comment (bugadani) [inline library/alloc/src/string.rs:1569]: Ah, here it is. Hmm.

Comment (dylni) [reply library/alloc/src/string.rs:1569]: @bugadani Do you think another comment would be helpful? I added one where I thought it would make the most sense, since adding one above `let start` but not `let end` is a little weird.

Comment (KodrAus) [reply library/alloc/src/string.rs:1569]: I think more comments wouldn't hurt 🙂

**Comment by KodrAus** [comment]
@dylni Would you like to include the example from #81138 as a test case to make sure we are still maintaining the UTF8 invariant?

File: library/alloc/src/collections/btree/navigate.rs [hunk 3]
```diff
@@ -25,7 +25,10 @@ where
     K: Borrow<Q>,
     R: RangeBounds<Q>,
 {
-    match (range.start_bound(), range.end_bound()) {
+    // Using `range` again would be unsound (#81138)
```
Comment (KodrAus) [inline library/alloc/src/collections/btree/navigate.rs:28]:
```suggestion
    // Using `range` again would be unsound (#81138)
    // We assume the bounds reported by `range` remain the same, but
    // an adversarial implementation could change between calls
```

File: library/alloc/src/string.rs (hunk 2 above)
Comment (KodrAus) [inline library/alloc/src/string.rs:1569]:
```suggestion
        // Using `range` again would be unsound (#81138)
        // We assume the bounds reported by `range` remain the same, but
        // an adversarial implementation could change between calls
```

**Comment by KodrAus** [comment]
I've just left a few comments. It would be good to include the `EvilRange` as a test case, but r=me at any time.

File: library/alloc/src/string.rs (hunk 2 above)
Comment (dylni) [reply library/alloc/src/string.rs:1571]: That's true :stuck_out_tongue:

**Comment by dylni** [comment]
> Would you like to include the example from #81138 as a test case to make sure we are still maintaining the UTF8 invariant?

Yes, good idea.

**Comment by KodrAus** [comment]
@dylni This looks good to me! Would you like to squash these down then we should be good to go.

**Comment by dylni** [comment]
Thanks @KodrAus! Is this what you had in mind? Squashing is a little awkward with merge commits.

**Comment by KodrAus** [comment]
That's it, thanks! I rebase and squash is what I'd meant. We try to avoid merge commits in PRs and leave that to bors to handle.

Thanks for fixing this up 🙇

**Comment by dylni** [comment]
Oh, thanks, that makes sense.

**Comment by ssomers** [comment]
> I also fixed the same issue for [`BTreeMap::range`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.range) and [`BTreeSet::range`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.range).

Useful and inspirational, but I feel the need to point out that you didn't entirely plug that hole, and probably nobody can. Unlike `String::replace_range` whose range is tied to `usize`, the caller of `BTreeMap::range` gets to choose a type and its `Ord` implementation. I got a little lost trying to brew a really evil example with a panic, but I still believe it can be done. [Here on playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9956fe6313ad6bda1cd6e47ec19da9fa) is proof that there are 12 integers from 5 to 7, with the help of an evil `borrow`.

**Comment by dylni** [comment]
@ssomers I think that's ok. If an impl used by `BTreeMap` misbehaves, `BTreeMap` is allowed to misbehave too. The only thing it can't do is something unsound. Although the playground example doesn't give the right result for the number values, it gives the right result based on the `Borrow` impl.

**Comment by ssomers** [comment]
@dylni I agree, but that means there was no unsoundness in BTreeMap's use of start_bound/end_bound, is what I realized this week. How many times these functions are called or what they return doesn't matter for unsoundness. It's what the various invocations of the lookup type's `Ord` say that might make BTreeMap trip up.

This PR is of course still a welcome fix to avoid BTreeMap from appearing to misbehave when the range misbehaves. If there was a possibility of unsoundness, that possibility is still there. And I can't find it.

**Comment by dylni** [comment]
@ssomers You're right. I was looking at the unsafe code [here](https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/library/alloc/src/collections/btree/node.rs#L701), but it's inside a safe function, so it makes sense that this can't be exploited.

**Comment by ssomers** [comment]
Not sure how you arrived in `left_edge`. But yes, disappointingly, I don't think there's anything to exploit. Essentially, BTreeMap is already prepared to withstand a malicious implementation of `Ord` for the key type, so the fact that `range` smuggles in another `Ord` for its search can't make things worse. When BTreeMap validates the range and panics, it doesn't do that to protect itself from unsoundness, but just to advise the caller that they messed up the range (with a message assuming they have an honest `Ord` implementation). Not sure if the original authors of the code realized that, but it's written in the contract that it should panic on an invalid range, so I'd better leave that to be.

**Comment by dylni** [comment]
@ssomers `left_edge` is [called here](https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/library/alloc/src/collections/btree/navigate.rs#L54).

> When BTreeMap validates the range and panics, it doesn't do that to protect itself from unsoundness, but just to advise the caller that they messed up the range (with a message assuming they have an honest `Ord` implementation).

I agree, but this was surprising. I think I'll change the comments a little there to make it clearer for people reading it in the future.
