### PR TITLE
Fix incorrect eq_unspanned in TokenStream

### LINKED ISSUE #141522: `eq_unspanned` is incorrect
The following function is incorrect:

https://github.com/rust-lang/rust/blob/038d599eda4fe3e3d78103fba51ee663df86dadf/compiler/rustc_ast/src/tokenstream.rs#L698-L707

Zipped iterators with uneven lengths will still consume an item from both sides of the zip on their final iteration (where one will return `None` and one will return `Some`). This allows for both iterators to be exhausted even though their lengths are unequal.

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#141522

r? @workingjubilee 

should we remove this function?
since it's used in several places, i'd prefer to keep it.

### CODE REVIEW

**Comment by workingjubilee** [comment]
is it actually important to those places?

**Comment by chenyukang** [comment]
> is it actually important to those places?

it's also trivial, removed it in new commit https://github.com/rust-lang/rust/pull/141570/commits/78b4fe371fb831cba60799c04261cea96027bb07.

**Comment by mejrs** [comment]
You can use https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.eq_by instead

File: compiler/rustc_ast/src/tokenstream.rs [hunk 1]
```diff
@@ -57,7 +57,9 @@ impl TokenTree {
         match (self, other) {
             (TokenTree::Token(token, _), TokenTree::Token(token2, _)) => token.kind == token2.kind,
             (TokenTree::Delimited(.., delim, tts), TokenTree::Delimited(.., delim2, tts2)) => {
-                delim == delim2 && tts.eq_unspanned(tts2)
+                delim == delim2
+                    && tts.len() == tts2.len()
+                    && tts.iter().zip(tts2.iter()).all(|(a, b)| a.eq_unspanned(b))
```
Comment (petrochenkov) [inline compiler/rustc_ast/src/tokenstream.rs:62]:
```suggestion
                    && tts.iter().zip(tts2).all(|(a, b)| a.eq_unspanned(b))
```
Methods like `zip` usually take `IntoIter` and not `Iter`.

Comment (chenyukang) [reply compiler/rustc_ast/src/tokenstream.rs:62]: yeah, I tried it with a compiling error:

```console
error[E0277]: `&tokenstream::TokenStream` is not an iterator
  --> compiler/rustc_ast/src/tokenstream.rs:62:35
   |
62 |                     && tts.iter().zip(tts2).all(|(a, b)| a.eq_unspanned(b))
   |                                   ^^^ `&tokenstream::TokenStream` is not an iterator
   |
   = help: the trait `Iterator` is not implemented for `&tokenstream::TokenStream`
   = note: required for `&tokenstream::TokenStream` to implement `IntoIterator`

error[E0599]: the method `all` exists for struct `Zip<TokenStreamIter<'_>, &TokenStream>`, but its trait bounds were not satisfied
  --> compiler/rustc_ast/src/tokenstream.rs:62:45
   |
62 |                     && tts.iter().zip(tts2).all(|(a, b)| a.eq_unspanned(b))
   |                                             ^^^ method cannot be called on `Zip<TokenStreamIter<'_>, &TokenStream>` due to unsatisfied trait bounds
   |
  ::: /Users/yukang/rust/library/core/src/iter/adapters/zip.rs:15:1
   |
15 | pub struct Zip<A, B> {
   | -------------------- doesn't satisfy `_: Iterator`
   |
   = note: the following trait bounds were not satisfied:
           `&tokenstream::TokenStream: Iterator`
           which is required by `Zip<TokenStreamIter<'_>, &tokenstream::TokenStream>: Iterator`
```

**Comment by chenyukang** [comment]
> You can use https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.eq_by instead

feature `iter_order_by` is still unstable, prefer to use stable methods?

**Comment by workingjubilee** [comment]
Thanks!

If we want to use the nightly stdlib feature that seeems fine, but this also seems better, so!

@bors r+ rollup

**Comment by workingjubilee** [comment]
@bors r-
@bors2 try

**Comment by workingjubilee** [comment]
Checking to see if we somehow caused https://github.com/rust-lang/rust/pull/141995#issuecomment-2938439163

**Comment by workingjubilee** [comment]
I guess it's okay!

@bors r+
