### PR TITLE
Fix inference issues with unconstrained base expr in `type_changing_struct_update`

### LINKED ISSUE #96878: type_changing_struct_update: regression in type inference
I tried this code:

```rust
#![feature(type_changing_struct_update)]

#[derive(Default)]
struct NonGeneric {
    field1: usize,
}

#[derive(Default)]
struct Generic<T, U> {
    field1: T,
    field2: U,
}

fn main() {
    let default = NonGeneric {
        ..Default::default()
    };
    let default: Generic<i32, f32> = Generic {
        ..Default::default()
    };
}
```

I expected to see this happen: Compilation succeeds, the two variables are assigned their default values.

Instead, this happened:

```
error[E0308]: mismatched types
  --> src/main.rs:16:11
   |
16 |         ..Default::default()
   |           ^^^^^^^^^^^^^^^^^^ expected struct `NonGeneric`, found inferred type
   |
   = note: expected struct `NonGeneric`
                found type `_`

error[E0308]: mismatched types
  --> src/main.rs:19:11
   |
19 |         ..Default::default()
   |           ^^^^^^^^^^^^^^^^^^ expected struct `Generic`, found inferred type
   |
   = note: expected struct `Generic<i32, f32>`
                found type `_`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (cb1219871 2022-05-08)
binary: rustc
commit-hash: cb121987158d69bb894ba1bcc21dc45d1e0a488f
commit-date: 2022-05-08
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

This was originally reported in https://github.com/rust-lang/rust/issues/86618#issuecomment-1022100845.
cc #86555

### PR DESCRIPTION
**Pull request by compiler-errors**
Use fresh infer vars to guide inference along in `type_changing_struct_update`.

Fixes #96878

### CODE REVIEW

**Comment by estebank** [comment]
r? @lcnr 

I'm r=me, but adding someone on the types team.

File: compiler/rustc_typeck/src/check/expr.rs [hunk 1]
```diff
@@ -1558,9 +1558,27 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        // of the `remaining_fields` below, per the RFC.
+                        let fresh_substs = self.fresh_substs_for_item(base_expr.span, adt.did());
+                        let base_ty = self.check_expr_has_type_or_error(
+                            base_expr,
+                            self.tcx.mk_adt(*adt, fresh_substs),
+                            |_| {},
+                        );
+                        let base_ty = self.shallow_resolve(base_ty);
                         match base_ty.kind() {
                             ty::Adt(base_adt, base_subs) if adt == base_adt => {
```
Comment (lcnr) [inline compiler/rustc_typeck/src/check/expr.rs:1583]: can you now `bug!` if that isn#t the case? or at least `delay_span_bug` if it's `ty::Error`? would safe us 8 columns of indentation ^^

**Review by lcnr — COMMENTED** [review]
lgtm r=me 

there's one optional improvement i found, if you're interested in implementing that

**Review by lcnr — COMMENTED** [review]
also, while you're in that file, can you change https://github.com/rust-lang/rust/blob/ac33d2b3e1359930a02653f0c61a124947912ed8/compiler/rustc_typeck/src/check/expr.rs#L1538 to not do a string comparison :laughing:

File: compiler/rustc_typeck/src/check/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/expr.rs:1583]: ironically, I don't think `check_expr_has_type_or_error` actually returns `ty::Error` when the expected type != the checked type of the input expr, hence us needing to call `report_mismatched_types` on line before:1605/after:1624. I can easily check, though.

I will see if I can simplify this, though. It can at least be changed to a let-chain :)

**Comment by compiler-errors** [comment]
I was able to turn the redundant `report_mismatched_types` into a `span_bug!` and I removed the string comparison with `"union"`.

@bors r=lcnr

**Comment by compiler-errors** [comment]
wake up bors

@bors r=lcnr
