### PR TITLE
Prevent very long compilation runtimes in LateBoundRegionNameCollector

### LINKED ISSUE #83150: compiler hangs trying to print an overflow error
I tried this code:

```rust
fn main(){
  let mut iter=0u8..1;
  println!("begin");
  func(&mut iter)
}
fn func<T:Iterator<Item=u8>>(iter:&mut T){
    if let Some(x)=iter.next(){
        println!("{}",x);
        func(&mut iter.map(|x|x+1))
    }
}
```

I expected to see this happen:

program either compiled successful or compiler generate an error

Instead, this happened: 
rustc eats 100% CPU for several minutes, but nothing generated.
I compile this code using both
`rustc testxx.rs -C opt-level=3 -C target-cpu=native -C codegen-units=1 -C lto -o testxx `and`rustc testxx.rs -C opt-level=0 -o testxx` before I began to write this issue, but compiler do not compile even after this issue is submitted.
### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (152f66092 2021-02-17)
binary: rustc
commit-hash: 152f6609246558be5e2582e67376194815e6ba0d
commit-date: 2021-02-17
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

<details><summary>Backtrace</summary>
<p>

```
(cannot compile)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by b-naber**
Fixes https://github.com/rust-lang/rust/issues/83150

On recursive types such as in the example given in https://github.com/rust-lang/rust/issues/83150, the current implementation of `LateBoundRegionNameCollector` has very long compilation runtimes. To prevent those we store the types visited in the `middle::ty::Visitor` implementation of `LateBoundRegionNameCollector` in a `SsoHashSet`.

### CODE REVIEW

File: src/test/ui/recursion/issue-83150.rs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+fn main() {
```
Comment (b-naber) [inline src/test/ui/recursion/issue-83150.rs:1]: This test passes for an unexplainable reason. When I compile this file I get the expected error:

```
error[E0275]: overflow evaluating the requirement `Map<&mut Map<&mut Map<&mut Map<&mut Map<.....
```

But the test suite cannot find an error.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 2]
```diff
@@ -1861,18 +1863,47 @@ impl<F: fmt::Write> FmtPrinter<'_, 'tcx, F> {
...
             fn visit_region(&mut self, r: ty::Region<'tcx>) -> ControlFlow<Self::BreakTy> {
+                debug!("LateBoundRegionNameCollector::visit_region(r: {:?}, address: {:p})", r, &r);
                 if let ty::ReLateBound(_, ty::BoundRegion { kind: ty::BrNamed(_, name) }) = *r {
-                    self.0.insert(name);
+                    self.used_region_names.insert(name);
                 }
                 r.super_visit_with(self)
             }
+
+            // In order to prohibit infinite recursion on infinitely recursed types we count the
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1885]: > infinitely recursed types

tnit: there are no infinite types. Types are finite trees, so infinite types are impossible.
We can get very large types though, which causes the hang here.

**Review by lcnr — COMMENTED** [review]
I don't think that using type length limit is the best approach here.

The issue here is that the type `T` is `&mut Map<T_prev, closure [T_prev]>` so the type size scales by `2^depth` instead of just `depth`.

Using https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/sso/struct.SsoHashSet.html in `visit_ty` seems like a potentially better solution to me

**Comment by b-naber** [comment]
@lcnr Thanks for the review. 

I don't understand how you would want to use `SsoHashSet`. The sub-`Ty`s we encounter when we traverse these very large types are not the same, so breaking control flow once we have encountered a `Ty` some given number of times is not an option. I don't see any other reason why we would want to collect those types.

**Comment by lcnr** [comment]
I don't want to break control at all here. This is not a hang, this is a finite, but incredibly large perf regression.

I want to use a `SsoHashSet` to not look multiple times into identical parts of our type

**Comment by b-naber** [comment]
@lcnr Thanks, that clarifies things. You're right, this isn't a hang. 

I updated the PR to use the `SsoHashSet`. There's still problem with the test though. When I changed this to `build-pass` the test fails, but it also fails when I add an expected error to the test with the reason that the test compiled successfully?!

**Comment by b-naber** [comment]
There's also a problem with another test, seems as if `LateBoundRegionNameCollector' has different functionality if we skip types we've seen before.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 3]
```diff
@@ -1861,18 +1863,38 @@ impl<F: fmt::Write> FmtPrinter<'_, 'tcx, F> {
...
                 }
                 r.super_visit_with(self)
             }
+
+            // We collect types in order to prevent really large types from compiling for
+            // a really long time. See issue #83150 for why this is necessary.
+            fn visit_ty(&mut self, ty: Ty<'tcx>) -> ControlFlow<Self::BreakTy> {
+                debug!("LateBoundRegionNameCollector::visit_ty(ty: {:?}", ty);
+                let not_previously_inserted = self.type_collector.insert(ty);
+                if not_previously_inserted { ty.super_visit_with(self) } else { ControlFlow::BREAK }
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1889]:
```suggestion
                if not_previously_inserted { ty.super_visit_with(self) } else { ControlFlow::CONTINUE }
```
you must not break here, otherwise you don't see `T2` in `Type<T1, T1, T2>`

**Comment by b-naber** [comment]
@lcnr Can you take another look? What do we do about the tests?

**Comment by lcnr** [comment]
i think the correct attribute here is `// build-fail`. By default we only try to check (like `cargo check`) ui tests afaik.

**Comment by b-naber** [comment]
@lcnr Yes, that's the correct attribute. Thanks for the review and the help.

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 4]
```diff
@@ -1861,18 +1863,42 @@ impl<F: fmt::Write> FmtPrinter<'_, 'tcx, F> {
...
+                    ControlFlow::CONTINUE
+                }
+            }
         }
 
         self.used_region_names.clear();
-        let mut collector = LateBoundRegionNameCollector(&mut self.used_region_names);
+        let mut collector = LateBoundRegionNameCollector {
+            used_region_names: &mut self.used_region_names,
+            type_collector: SsoHashSet::with_capacity(1000),
```
Comment (lcnr) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1900]:
```suggestion
            type_collector: SsoHashSet::new(),
```
we don't want to allocate here by default.

File: src/test/ui/recursion/issue-83150.rs [hunk 5]
```diff
@@ -0,0 +1,11 @@
+// build-fail
+  //~^ overflow evaluating
```
Comment (lcnr) [inline src/test/ui/recursion/issue-83150.rs:2]:
```suggestion
//~^ overflow evaluating
```

**Comment by lcnr** [comment]
update the PR name and description, then this should be ready after a perf run.

**Comment by b-naber** [comment]
@lcnr This is ready for the perf run.

**Comment by estebank** [comment]
Should this be backported to 1.52? @rust-lang/compiler
