### PR TITLE
Evaluate repeat expression lengths as late as possible

### LINKED ISSUE #68567: `Rvalue::Repeat` should hold a `ty::Const`
```rust
fn test<const N: usize>() {
    let array = [0; N];
}
```
currently fails with `error: array lengths can't depend on generic parameters`, because we can't tell what concrete value `N` should take here. This is an artificial limitation: when producing a `Rvalue::Repeat`, we currently need to provide the length of the array, which is impossible at this stage.
cc https://github.com/rust-lang/rust/issues/43408#issuecomment-578526551

### PR DESCRIPTION
**Pull request by oli-obk**
Fixes #68567

r? @varkor

### CODE REVIEW

File: src/librustc_mir/borrow_check/type_check/mod.rs [hunk 1]
```diff
@@ -1983,7 +1983,7 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
             }
 
             Rvalue::Repeat(operand, len) => {
-                if *len > 1 {
+                if len.try_eval_usize(tcx, self.param_env).map_or(false, |len| len > 1) {
```
Comment (oli-obk) [inline src/librustc_mir/borrow_check/type_check/mod.rs]: This one I'm not sure about. In case we can't evaluate the constant, should we be going into the if body, because it may not be length zero?

**Comment by Centril** [comment]
cc also @eddyb

**Comment by oli-obk** [comment]
heh, do we need a wg-const-generics?

**Comment by Centril** [comment]
probably :)

File: src/librustc_mir/borrow_check/type_check/mod.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir/borrow_check/type_check/mod.rs]: Yes, we should check that the element type is `Copy` unless we know that the length is 0 or 1.

File: src/librustc_const/lib.rs [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    match &expr.kind {
+        ExprKind::Path(hir::QPath::Resolved(_, path)) => match path.res {
+            Res::Def(DefKind::ConstParam, did) => Some(did),
+            _ => None,
+        },
+        _ => None,
+    }
+}
+
+pub fn ast_const_to_const<'tcx>(
```
Comment (eddyb) [inline src/librustc_const/lib.rs]: Wait, why is this its own crate?
This looks like it should be a query (taking a `DefId`, which a `hir::AnonConst` should always have) in `rustc_typeck`.

File: src/librustc_mir/borrow_check/type_check/mod.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc_mir/borrow_check/type_check/mod.rs]: So `false` should be replaced with `true`, or maybe you can do something like this instead:
```rust
let at_most_one_element =
    len.try_eval_usize(tcx, self.param_env).map_or(false, |len| len <= 1);
if !at_most_one_element {
```

File: src/librustc_const/lib.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_const/lib.rs]: feels a bit overkill to make it a query, all it does is intern a trivially created ty::Const

**Comment by varkor** [comment]
Sorry, I've had a half-finished branch to do this for a couple of months, but haven't managed to get back to it. Thanks for taking it on. I'll have a look soon.

File: src/librustc_const/lib.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc_const/lib.rs]: I'd still be more comfortable with it if it were, idk. But also why is any of this necessary for repeat lengths, they can remain `Unevaluated` for as long as possible (you can use normalization to make it happen sooner without bothering to create anything other than `Unevaluated`).

Comment (oli-obk) [reply src/librustc_const/lib.rs]: that's what I tried first. but that causes problems with parameters, because the parameters point to the surrounding function, causing cycles during mir building

Comment (eddyb) [reply src/librustc_const/lib.rs]: But they're not in the signature of the function, so there shouldn't be a cycle is my point.

Do you have one of those cycle errors? I'm intrigued now.

Comment (oli-obk) [reply src/librustc_const/lib.rs]: Ah it's indeed not a cycle. It's an ICE.

```
error: internal compiler error: broken MIR in DefId(0:3 ~ issue_61336_1[317d]::f[0]) (_0 = [move _2; Const { ty: usize, val: Unevaluated(DefId(0:7 ~ issue_61336_1[317d]::f[0]::{{constant}}[1]), [T, Const { ty: usize, val: Param(N/#1) }], None) }]): bad assignment ([T; _] = [T; _]): NoSolution
  --> /home/oli/rustc/rust4/src/test/ui/const-generics/issues/issue-61336-1.rs:7:5
   |
LL |     [x; N]
   |   
```

at

https://github.com/rust-lang/rust/blob/42ce9b4e9054d63c8f352f994e2d5dae7d04130f/src/librustc_mir/borrow_check/type_check/mod.rs#L1437-L1440

Normalization doesn't convert unevaluated consts to `ConstKind::Param` where possible, and const comparisons of unevaluated constants compare the `DefId`, not the mir body.

Comment (eddyb) [reply src/librustc_const/lib.rs]: > Normalization doesn't convert unevaluated consts to `ConstKind::Param` where possible

Right, because we have nothing resembling symbolic miri. So we still need this hack.

If you don't want this to be a query... how about a constructor on `ty::Const`? That by default constructs a `ConstKind::Unevaluated`, but for local `DefId`s that point to `hir::AnonConst`s it does the hack.

Comment (oli-obk) [reply src/librustc_const/lib.rs]: sgtm, the only reason I put it into a separate crate was that I didn't want to add stuff to the rustc crate

Comment (oli-obk) [reply src/librustc_const/lib.rs]: done

File: src/librustc/mir/tcx.rs [hunk 3]
```diff
@@ -149,7 +149,9 @@ impl<'tcx> Rvalue<'tcx> {
     {
         match *self {
             Rvalue::Use(ref operand) => operand.ty(local_decls, tcx),
-            Rvalue::Repeat(ref operand, count) => tcx.mk_array(operand.ty(local_decls, tcx), count),
+            Rvalue::Repeat(ref operand, count) => {
+                tcx.mk_ty(ty::Array(operand.ty(local_decls, tcx), count))
```
Comment (eddyb) [inline src/librustc/mir/tcx.rs]: I wonder when we can have `mk_array` take a `ty::Const`.

File: src/test/ui/const-generics/issues/issue-61336.rs [hunk 4]
```diff
@@ -3,12 +3,11 @@
 
 fn f<T: Copy, const N: usize>(x: T) -> [T; N] {
     [x; N]
-    //~^ ERROR array lengths can't depend on generic parameters
 }
 
 fn g<T, const N: usize>(x: T) -> [T; N] {
     [x; N]
-    //~^ ERROR array lengths can't depend on generic parameters
+    //~^ ERROR the trait bound `T: std::marker::Copy` is not satisfied
```
Comment (eddyb) [inline src/test/ui/const-generics/issues/issue-61336.rs]: Presumably in cases like these we should add a `Copy` bound and show that it works.

File: src/test/ui/const-generics/issues/issue-61336-1.rs [hunk 5]
```diff
@@ -1,9 +1,10 @@
 #![feature(const_generics)]
 //~^ WARN the feature `const_generics` is incomplete and may cause the compiler to crash
 
+// build-pass
+
 fn f<T: Copy, const N: usize>(x: T) -> [T; N] {
     [x; N]
-    //~^ ERROR array lengths can't depend on generic parameters
 }
```
Comment (eddyb) [inline src/test/ui/const-generics/issues/issue-61336-1.rs]: Nevermind, this looks like a test with the `Copy` bound.

File: src/librustc/ty/sty.rs [hunk 6]
```diff
@@ -2407,18 +2407,91 @@ pub struct Const<'tcx> {
 #[cfg(target_arch = "x86_64")]
 static_assert_size!(Const<'_>, 48);
 
+/// Returns the `DefId` of the constant parameter that the provided expression is a path to.
+fn const_param_def_id(expr: &hir::Expr<'_>) -> Option<DefId> {
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: This is called only once now, can it just be inlined?

File: src/librustc/ty/sty.rs [hunk 7]
```diff
@@ -2407,18 +2407,91 @@ pub struct Const<'tcx> {
...
+}
+
 impl<'tcx> Const<'tcx> {
+    /// Literals and const generic parameters are eagerly converted to a constant, everything else
+    /// becomes `Unevaluated`.
+    pub fn from_hir_anon_const(
+        tcx: TyCtxt<'tcx>,
+        ast_const: &hir::AnonConst,
+        ty: Ty<'tcx>,
+    ) -> &'tcx Self {
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: IMO this should take `DefId` and `Substs` and create `Unevaluated` by default.

The `hir::AnonConst` special-casing is just a hack to make a few things work better.

File: src/test/ui/const-generics/issues/issue-61336.rs (hunk 4 above)
Comment (oli-obk) [reply src/test/ui/const-generics/issues/issue-61336.rs]: scroll up ;)

File: src/librustc/ty/sty.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc/ty/sty.rs]: that makes the function less useful than it is now. It abstracts away the HirId -> DefId conversion and substs creation, which would need to get replicated at all call sites. I can split it into two functions if you prefer, but I'd like to keep the current API

File: src/librustc/mir/tcx.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc/mir/tcx.rs]: Likely never, we have 14 uses in the code base, and half of them are `ProjectionKind::SubSlice` related.

File: src/librustc/ty/sty.rs (hunk 7 above)
Comment (eddyb) [reply src/librustc/ty/sty.rs]: > It abstracts away the HirId -> DefId conversion and substs creation, which would need to get replicated at all call sites

`DefId` is the correct type here, it's just unfortunate that the HIR contains a `HirId` instead. And substs are easy to get.

And if you have more than 2-3 calls to this function something went wrong.

File: src/test/ui/const-generics/issues/issue-62504.stderr [hunk 8]
```diff
@@ -1,8 +1,12 @@
-error: array lengths can't depend on generic parameters
-  --> $DIR/issue-62504.rs:18:25
+error[E0308]: mismatched types
+  --> $DIR/issue-62504.rs:18:21
    |
 LL |         ArrayHolder([0; Self::SIZE])
-   |                         ^^^^^^^^^^
+   |                     ^^^^^^^^^^^^^^^ expected `X`, found `Self::SIZE`
```
Comment (oli-obk) [inline src/test/ui/const-generics/issues/issue-62504.stderr]: This span could use some improvement

File: src/test/ui/const-generics/issues/issue-67739.rs [hunk 9]
```diff
@@ -10,7 +10,7 @@ pub trait Trait {
 
     fn associated_size(&self) -> usize {
         [0u8; mem::size_of::<Self::Associated>()];
```
Comment (oli-obk) [inline src/test/ui/const-generics/issues/issue-67739.rs]: This ICEs the compiler, because CTFE tries to `subst_and_normalize_erasing_regions`, and this can't be normalized. I'm not sure how to resolve this. @eddyb a while back we worked on this and I had some hacky stuff that first substituted and returned `TooGeneric` if the result still had substs. Back then you had the insight that allowed the hack to be removed. I'm hoping this is just another case of that...

The entry point is https://github.com/rust-lang/rust/blob/8e6de3244cd62cbde367c206bc9972daded5281d/src/librustc_mir/interpret/operand.rs#L493-L496 which invokes https://github.com/rust-lang/rust/blob/7cdbc87a49b0b705a41a004a6d486b0952521ae7/src/librustc_mir/interpret/eval_context.rs#L338-L347 which ICEs in https://github.com/rust-lang/rust/blob/8e6de3244cd62cbde367c206bc9972daded5281d/src/librustc_traits/normalize_erasing_regions.rs#L13-L39

Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-67739.rs]: Is codegen calling `self.monomorphize` correctly for the length?

Comment (oli-obk) [reply src/test/ui/const-generics/issues/issue-67739.rs]: Codegen dosn't have this problem I think, as it would have substituted `Self` with the concrete type already.

Comment (eddyb) [reply src/test/ui/const-generics/issues/issue-67739.rs]: Judging by [the query stack](https://gist.github.com/oli-obk/6bf4cd07b030d536830f1b94cc8e84c9#file-gistfile1-txt-L636-L641) something is dropping a `ParamEnv` on the floor (`caller_bounds` should have a `Self: Trait` in it).

Comment (oli-obk) [reply src/test/ui/const-generics/issues/issue-67739.rs]: that was it, thanks. It works now

File: src/test/ui/const-generics/issues/issue-67739.rs [hunk 10]
```diff
@@ -10,7 +12,6 @@ pub trait Trait {
...
```
Comment (oli-obk) [inline src/test/ui/const-generics/issues/issue-67739.rs]: This file compiles now successfully!

**Comment by oli-obk** [comment]
This PR is ready for review again

File: src/librustc/mir/mod.rs [hunk 11]
```diff
@@ -2066,7 +2066,7 @@ pub enum Rvalue<'tcx> {
     Use(Operand<'tcx>),
 
     /// [x; 32]
-    Repeat(Operand<'tcx>, u64),
+    Repeat(Operand<'tcx>, &'tcx ty::Const<'tcx>),
```
Comment (eddyb) [inline src/librustc/mir/mod.rs]: Wondering now if this should be `Constant` or if that's somewhat pointless.

File: src/librustc/ty/sty.rs [hunk 12]
```diff
@@ -2402,17 +2402,84 @@ pub struct Const<'tcx> {
 static_assert_size!(Const<'_>, 48);
 
 impl<'tcx> Const<'tcx> {
+    /// Literals and const generic parameters are eagerly converted to a constant, everything else
+    /// becomes `Unevaluated`.
+    pub fn from_hir_anon_const(tcx: TyCtxt<'tcx>, def_id: DefId, ty: Ty<'tcx>) -> &'tcx Self {
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Hmm, what if you remove the `ty` argument and get it from `tcx.type_of(def_id)`?

Also `from_anon_const` could be an okay name. I still would prefer if this handled all `Unevaluated` and only for  *local* `hir::Node::AnonConst` specifically it would bother to look at the body but I suppose that's inconsistent.

Oh, I know, you can change `DefId` to `LocalDefId`, then finally everything should be good.

File: src/librustc/ty/sty.rs [hunk 13]
```diff
@@ -2402,17 +2402,84 @@ pub struct Const<'tcx> {
...
+        debug!("Const::from_hir_anon_const(id={:?})", def_id);
+
+        let hir_id = tcx.hir().as_local_hir_id(def_id).unwrap();
+
+        let body_id = tcx.hir().body_owned_by(hir_id);
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: If you want to limit this to `AnonConst`s, use `get` and support only ``hir::Node::AnonConst`, instead of relying on `body_owned_by`.

File: src/librustc/ty/sty.rs (hunk 12 above)
Comment (eddyb) [reply src/librustc/ty/sty.rs]: Not passing `Substs` is fine in retrospect, it makes this constructor like `tcx.type_of` but "value of", instead, I suppose (well, "unevaluated value of").

File: src/librustc_mir_build/hair/cx/expr.rs [hunk 14]
```diff
@@ -406,34 +406,8 @@ fn make_mirror_unadjusted<'a, 'tcx>(
...
-                    }
-                }
-                Err(ErrorHandled::Reported) => 0,
-                Err(ErrorHandled::TooGeneric) => {
-                    let span = cx.tcx.def_span(def_id);
-                    cx.tcx.sess.span_err(span, "array lengths can't depend on generic parameters");
-                    0
-                }
-            };
+            let count = cx.tcx.hir().local_def_id(count.hir_id);
```
Comment (eddyb) [inline src/librustc_mir_build/hair/cx/expr.rs]: Might be good to call variables like these `count_def_id`.

File: src/librustc_typeck/astconv.rs [hunk 15]
```diff
@@ -2766,7 +2765,8 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
                     .unwrap_or(tcx.types.err)
             }
             hir::TyKind::Array(ref ty, ref length) => {
-                let length = self.ast_const_to_const(length, tcx.types.usize);
+                let length = tcx.hir().local_def_id(length.hir_id);
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: `length_def_id`

File: src/librustc_typeck/astconv.rs [hunk 16]
```diff
@@ -782,7 +780,8 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
                     }
                 }
                 (GenericParamDefKind::Const, GenericArg::Const(ct)) => {
-                    self.ast_const_to_const(&ct.value, tcx.type_of(param.def_id)).into()
+                    let ct = tcx.hir().local_def_id(ct.value.hir_id);
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: `ct_def_id`

File: src/librustc_typeck/astconv.rs [hunk 17]
```diff
@@ -782,7 +780,8 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
+                    ty::Const::from_hir_anon_const(tcx, ct, tcx.type_of(param.def_id)).into()
```
Comment (eddyb) [inline src/librustc_typeck/astconv.rs]: `tcx.type_of(param.def_id)` here may seem good but ultimately `tcx.type_of(ct_def_id)` has to work, otherwise the `AnonConst` can't be type-checked anyway.

File: src/librustc_typeck/check/expr.rs [hunk 18]
```diff
@@ -1009,12 +1008,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     ) -> Ty<'tcx> {
         let tcx = self.tcx;
         let count_def_id = tcx.hir().local_def_id(count.hir_id);
-        let count = if self.const_param_def_id(count).is_some() {
-            Ok(self.to_const(count, tcx.type_of(count_def_id)))
-        } else {
-            tcx.const_eval_poly(count_def_id)
-                .map(|val| ty::Const::from_value(tcx, val, tcx.type_of(count_def_id)))
-        };
+        let count = self.to_const(count, tcx.type_of(count_def_id));
```
Comment (eddyb) [inline src/librustc_typeck/check/expr.rs]: `to_const` should register an `WellFormedConst` obligation (cc @lcnr).
(Not for this PR, `WellFormedConst` isn't possible yet)

File: src/librustc/mir/mod.rs (hunk 11 above)
Comment (oli-obk) [reply src/librustc/mir/mod.rs]: It's guaranteed to be a `usize`, it could be `ConstKind` :laughing:

Comment (eddyb) [reply src/librustc/mir/mod.rs]: > It's guaranteed to be a `usize`, it could be `ConstKind`

Interning is *good*.

File: src/librustc/ty/sty.rs [hunk 19]
```diff
@@ -2402,17 +2402,89 @@ pub struct Const<'tcx> {
...
+    /// Literals and const generic parameters are eagerly converted to a constant, everything else
+    /// becomes `Unevaluated`.
+    pub fn from_anon_const(tcx: TyCtxt<'tcx>, def_id: LocalDefId) -> &'tcx Self {
+        debug!("Const::from_anon_const(id={:?})", def_id);
+
+        let hir_id = tcx.hir().local_def_id_to_hir_id(def_id);
+
+        let body_id = match tcx.hir().get(hir_id) {
+            hir::Node::AnonConst(ac) => ac.body,
+            _ => span_bug!(tcx.def_span(def_id.to_def_id()), "from_anon_const can only process anonymous constants"),
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: My kingdom for a custom coercion `LocalDefId` -> `DefId`.
(`impl Into<DefId>` is bad for your `fn` bodies, sadly, if we could even use it for queries)

File: src/librustc/ty/sty.rs [hunk 20]
```diff
@@ -2402,17 +2402,89 @@ pub struct Const<'tcx> {
...
+            _ => None,
+        };
+
+        if let Some(lit_input) = lit_input {
+            // If an error occurred, ignore that it's a literal and leave reporting the error up to
+            // mir.
+            if let Ok(c) = tcx.at(expr.span).lit_to_const(lit_input) {
+                return c;
+            } else {
+                tcx.sess.delay_span_bug(expr.span, "ast_const_to_const: couldn't lit_to_const");
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Old name `ast_const_to_const`.

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
r=me after fixing https://github.com/rust-lang/rust/pull/69981#discussion_r396705644, everything else looks great!

**Comment by eddyb** [comment]
```
error: /checkout/src/librustc/mir/mod.rs: too many lines (3007) (add `// ignore-tidy-filelength` to the file to suppress this error)
```

*Sigh*, it's that silly error again. (although I suppose a bunch of the `impl`s could be moved to their own modules under `rustc::mir`)

**Comment by Centril** [comment]
You need to `./x.py fmt`, @bors r-
