### PR TITLE
skip rpit constraint checker if borrowck return type error

### LINKED ISSUE #117794: ice: `bug!()` in mir building
auto-reduced (treereduce-rust):
````rust
trait Foo {}

trait ThreeCellFragment {
    fn ext_cells<'a>(&'a self) -> impl Foo + 'a {
        self.ext_adjacent_cells(|()| 3)
    }
}


````

original:
````rust
// check-pass


trait Foo {}

impl Foo for () {}

trait ThreeCellFragment {
    fn ext_cells<'a>(&'a self) -> impl Foo + 'a {
        self.ext_adjacent_cells(|()| 3)
    }

    fn ext_adjacent_cells<'a>(&'a self) -> impl Foo + 'a;
}

fn main() {}

````

Version information
````
rustc 1.75.0-nightly (17d0a45f5 2023-11-10)
binary: rustc
commit-hash: 17d0a45f5df31f218b84c3275bb05c3227348b5b
commit-date: 2023-11-10
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.sMhjD6Mc1Nu9/rustc_testrunner_tmpdir_reporting.f0KwVpsVTJF1/mvce.rs:7:2
  |
7 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.sMhjD6Mc1Nu9/rustc_testrunner_tmpdir_reporting.f0KwVpsVTJF1/mvce.rs`

error[E0599]: no method named `ext_adjacent_cells` found for reference `&'a Self` in the current scope
 --> /tmp/icemaker_global_tempdir.sMhjD6Mc1Nu9/rustc_testrunner_tmpdir_reporting.f0KwVpsVTJF1/mvce.rs:5:14
  |
5 |         self.ext_adjacent_cells(|()| 3)
  |              ^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `ext_cells`

error: internal compiler error: compiler/rustc_mir_build/src/build/mod.rs:643:65: impossible case reached

thread 'rustc' panicked at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/compiler/rustc_errors/src/lib.rs:1661:9:
Box<dyn Any>
stack backtrace:
   0:     0x7fc8a9b8b62c - std::backtrace_rs::backtrace::libunwind::trace::h46374b84341786bc
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fc8a9b8b62c - std::backtrace_rs::backtrace::trace_unsynchronized::he7815f30c698ee16
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc8a9b8b62c - std::sys_common::backtrace::_print_fmt::hf3ac027a6e20df81
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fc8a9b8b62c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6350b6493143b1fc
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc8a9bde630 - core::fmt::rt::Argument::fmt::haac38874886df8e7
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/core/src/fmt/rt.rs:142:9
   5:     0x7fc8a9bde630 - core::fmt::write::hf0e822b6d8ad56b2
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fc8a9b7f54f - std::io::Write::write_fmt::h1a44df357aa13b6e
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/io/mod.rs:1762:15
   7:     0x7fc8a9b8b414 - std::sys_common::backtrace::_print::h95329df2b370286a
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fc8a9b8b414 - std::sys_common::backtrace::print::hd1549e5974c3fa44
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fc8a9b8e0a7 - std::panicking::default_hook::{{closure}}::hfc23d70499246b08
  10:     0x7fc8a9b8de0f - std::panicking::default_hook::h0d66df0a095a3bd0
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/panicking.rs:292:9
  11:     0x7fc8ac8ee150 - std[4df474cf7c0204ae]::panicking::update_hook::<alloc[ca626be192fcf572]::boxed::Box<rustc_driver_impl[ec4025a53c2103e9]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fc8a9b8e7e8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h44f7f870300bcc1d
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/alloc/src/boxed.rs:2021:9
  13:     0x7fc8a9b8e7e8 - std::panicking::rust_panic_with_hook::h652875067b2fe609
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/panicking.rs:783:13
  14:     0x7fc8acd39a74 - std[4df474cf7c0204ae]::panicking::begin_panic::<rustc_errors[1bc87cf102603fe6]::ExplicitBug>::{closure#0}
  15:     0x7fc8acd2e0e6 - std[4df474cf7c0204ae]::sys_common::backtrace::__rust_end_short_backtrace::<std[4df474cf7c0204ae]::panicking::begin_panic<rustc_errors[1bc87cf102603fe6]::ExplicitBug>::{closure#0}, !>
  16:     0x7fc8acd1c5d6 - std[4df474cf7c0204ae]::panicking::begin_panic::<rustc_errors[1bc87cf102603fe6]::ExplicitBug>
  17:     0x7fc8acd13714 - <rustc_errors[1bc87cf102603fe6]::HandlerInner>::bug::<alloc[ca626be192fcf572]::string::String>
  18:     0x7fc8acd1341a - <rustc_errors[1bc87cf102603fe6]::Handler>::bug::<alloc[ca626be192fcf572]::string::String>
  19:     0x7fc8acdb514d - rustc_middle[dadee63cb0feb6d5]::util::bug::opt_span_bug_fmt::<rustc_span[9afbaaf51cc05e3]::span_encoding::Span>::{closure#0}
  20:     0x7fc8acd9c0aa - rustc_middle[dadee63cb0feb6d5]::ty::context::tls::with_opt::<rustc_middle[dadee63cb0feb6d5]::util::bug::opt_span_bug_fmt<rustc_span[9afbaaf51cc05e3]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fc8acd9bf28 - rustc_middle[dadee63cb0feb6d5]::ty::context::tls::with_context_opt::<rustc_middle[dadee63cb0feb6d5]::ty::context::tls::with_opt<rustc_middle[dadee63cb0feb6d5]::util::bug::opt_span_bug_fmt<rustc_span[9afbaaf51cc05e3]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fc8aad158c0 - rustc_middle[dadee63cb0feb6d5]::util::bug::bug_fmt
  23:     0x7fc8ace10c52 - rustc_mir_build[a72c6cb2b0bc5327]::build::construct_error
  24:     0x7fc8ae15c1e7 - rustc_mir_build[a72c6cb2b0bc5327]::build::mir_built
  25:     0x7fc8ae15aa07 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7fc8adce2083 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::VecCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  27:     0x7fc8adce1a10 - rustc_query_impl[d9d242dab8718f47]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7fc8ab07bc1e - rustc_mir_transform[68e77d7196a8ecec]::check_unsafety::unsafety_check_result
  29:     0x7fc8adce1e07 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7fc8adce2083 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::VecCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  31:     0x7fc8adce1b90 - rustc_query_impl[d9d242dab8718f47]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fc8adce3076 - rustc_mir_transform[68e77d7196a8ecec]::mir_const
  33:     0x7fc8adce2fa1 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7fc8adce2083 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::VecCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  35:     0x7fc8adce1ad0 - rustc_query_impl[d9d242dab8718f47]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7fc8abe6c490 - rustc_mir_transform[68e77d7196a8ecec]::mir_promoted
  37:     0x7fc8ae0e3092 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 16usize]>>
  38:     0x7fc8ae0e3345 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::VecCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  39:     0x7fc8ae0e2f93 - rustc_query_impl[d9d242dab8718f47]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7fc8aea1ffcb - rustc_borrowck[44740cb65e3b9e2a]::mir_borrowck
  41:     0x7fc8aea1ff17 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7fc8adce2083 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::VecCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  43:     0x7fc8adce1c50 - rustc_query_impl[d9d242dab8718f47]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7fc8aec19ff1 - <rustc_hir_analysis[3fdc3bc95e806e7]::collect::type_of::opaque::RpitConstraintChecker>::check
  45:     0x7fc8ac181bf5 - <rustc_hir_analysis[3fdc3bc95e806e7]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[8da2da2e6769dc1f]::intravisit::Visitor>::visit_expr
  46:     0x7fc8ac181bdb - <rustc_hir_analysis[3fdc3bc95e806e7]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[8da2da2e6769dc1f]::intravisit::Visitor>::visit_expr
  47:     0x7fc8ae96aa70 - rustc_hir_analysis[3fdc3bc95e806e7]::collect::type_of::type_of_opaque
  48:     0x7fc8ae96a19b - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  49:     0x7fc8adc531d4 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::DefaultCache<rustc_span[9afbaaf51cc05e3]::def_id::DefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  50:     0x7fc8aec4ff9e - rustc_query_impl[d9d242dab8718f47]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  51:     0x7fc8adcc1f38 - rustc_middle[dadee63cb0feb6d5]::query::plumbing::query_get_at::<rustc_query_system[6b6f1c30493de844]::query::caches::DefaultCache<rustc_span[9afbaaf51cc05e3]::def_id::DefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>>
  52:     0x7fc8abdd3c1f - rustc_hir_analysis[3fdc3bc95e806e7]::collect::type_of::type_of
  53:     0x7fc8adc54336 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>
  54:     0x7fc8adc531d4 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::DefaultCache<rustc_span[9afbaaf51cc05e3]::def_id::DefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  55:     0x7fc8adc52d9b - rustc_query_impl[d9d242dab8718f47]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  56:     0x7fc8adcc1f38 - rustc_middle[dadee63cb0feb6d5]::query::plumbing::query_get_at::<rustc_query_system[6b6f1c30493de844]::query::caches::DefaultCache<rustc_span[9afbaaf51cc05e3]::def_id::DefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 8usize]>>>
  57:     0x7fc8ae32088c - rustc_hir_analysis[3fdc3bc95e806e7]::check::check::check_mod_item_types
  58:     0x7fc8ae31f293 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 0usize]>>
  59:     0x7fc8ae60757b - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::DefaultCache<rustc_span[9afbaaf51cc05e3]::def_id::LocalModDefId, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  60:     0x7fc8ae606f57 - rustc_query_impl[d9d242dab8718f47]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  61:     0x7fc8ae1ce7d5 - rustc_hir_analysis[3fdc3bc95e806e7]::check_crate
  62:     0x7fc8adfaa8d7 - rustc_interface[b3bf249fff60da9a]::passes::analysis
  63:     0x7fc8adfaa537 - rustc_query_impl[d9d242dab8718f47]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d9d242dab8718f47]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 1usize]>>
  64:     0x7fc8aeb98824 - rustc_query_system[6b6f1c30493de844]::query::plumbing::try_execute_query::<rustc_query_impl[d9d242dab8718f47]::DynamicConfig<rustc_query_system[6b6f1c30493de844]::query::caches::SingleCache<rustc_middle[dadee63cb0feb6d5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[d9d242dab8718f47]::plumbing::QueryCtxt, false>
  65:     0x7fc8aeb98615 - rustc_query_impl[d9d242dab8718f47]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  66:     0x7fc8aeba123f - rustc_interface[b3bf249fff60da9a]::interface::run_compiler::<core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>, rustc_driver_impl[ec4025a53c2103e9]::run_compiler::{closure#1}>::{closure#0}
  67:     0x7fc8aeba855a - std[4df474cf7c0204ae]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b3bf249fff60da9a]::util::run_in_thread_with_globals<rustc_interface[b3bf249fff60da9a]::util::run_in_thread_pool_with_globals<rustc_interface[b3bf249fff60da9a]::interface::run_compiler<core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>, rustc_driver_impl[ec4025a53c2103e9]::run_compiler::{closure#1}>::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>
  68:     0x7fc8aeba8383 - <<std[4df474cf7c0204ae]::thread::Builder>::spawn_unchecked_<rustc_interface[b3bf249fff60da9a]::util::run_in_thread_with_globals<rustc_interface[b3bf249fff60da9a]::util::run_in_thread_pool_with_globals<rustc_interface[b3bf249fff60da9a]::interface::run_compiler<core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>, rustc_driver_impl[ec4025a53c2103e9]::run_compiler::{closure#1}>::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f248d18e5721e18e]::result::Result<(), rustc_span[9afbaaf51cc05e3]::ErrorGuaranteed>>::{closure#1} as core[f248d18e5721e18e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:     0x7fc8a9b986a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h473dfddbf197f5bf
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/alloc/src/boxed.rs:2007:9
  70:     0x7fc8a9b986a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8959fbdf8cbf8098
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/alloc/src/boxed.rs:2007:9
  71:     0x7fc8a9b986a5 - std::sys::unix::thread::Thread::new::thread_start::hab410919d7ef6e45
                               at /rustc/17d0a45f5df31f218b84c3275bb05c3227348b5b/library/std/src/sys/unix/thread.rs:108:17
  72:     0x7fc8a99899eb - <unknown>
  73:     0x7fc8a9a0d7cc - <unknown>
  74:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.75.0-nightly (17d0a45f5 2023-11-10) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `ThreeCellFragment::ext_cells::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `ThreeCellFragment::ext_cells::{closure#0}`
#2 [mir_const] preparing `ThreeCellFragment::ext_cells::{closure#0}` for borrow checking
#3 [mir_promoted] promoting constants in MIR for `ThreeCellFragment::ext_cells::{closure#0}`
#4 [mir_borrowck] borrow-checking `ThreeCellFragment::ext_cells::{closure#0}`
#5 [type_of_opaque] computing type of opaque `ThreeCellFragment::ext_cells::{opaque#0}`
#6 [type_of] computing type of `ThreeCellFragment::ext_cells::{opaque#0}`
#7 [check_mod_item_types] checking item types in top-level module
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0599, E0601.
For more information about an error, try `rustc --explain E0599`.

```

</p>
</details>

### LINKED ISSUE #117886: ICE: closures: `no entry found for key`
auto-reduced (treereduce-rust):
````rust
trait Foo {
    fn test() -> impl Fn(u32) -> u32 {
        || x.count_ones()
    }
}


````

original:
````rust
// compile-flags: -Ztrait-solver=next
// check-pass

trait Foo {
    fn test() -> impl Fn(u32) -> u32 {
        || x.count_ones()
    }
}

fn test() -> impl Fn(u32) -> u32 {
        |x| x.count_ones()
    }

````

Version information
````
rustc 1.76.0-nightly (1ab2bcda4 2023-11-13)
binary: rustc
commit-hash: 1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `x` in this scope
 --> /tmp/icemaker_global_tempdir.fsYCHepUila8/rustc_testrunner_tmpdir_reporting.iEesmi5L3ZBB/mvce.rs:3:12
  |
3 |         || x.count_ones()
  |            ^ not found in this scope

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.fsYCHepUila8/rustc_testrunner_tmpdir_reporting.iEesmi5L3ZBB/mvce.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.fsYCHepUila8/rustc_testrunner_tmpdir_reporting.iEesmi5L3ZBB/mvce.rs`

error[E0593]: closure is expected to take 1 argument, but it takes 0 arguments
 --> /tmp/icemaker_global_tempdir.fsYCHepUila8/rustc_testrunner_tmpdir_reporting.iEesmi5L3ZBB/mvce.rs:2:18
  |
2 |     fn test() -> impl Fn(u32) -> u32 {
  |                  ^^^^^^^^^^^^^^^^^^^ expected closure that takes 1 argument
3 |         || x.count_ones()
  |         -- takes 0 arguments
  |
help: consider changing the closure to take and ignore the expected argument
  |
3 |         |_| x.count_ones()
  |         ~~~

thread 'rustc' panicked at compiler/rustc_middle/src/ty/closure.rs:262:62:
no entry found for key
stack backtrace:
   0:     0x7f6cbebc461c - std::backtrace_rs::backtrace::libunwind::trace::h02700d0b9106f6ee
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f6cbebc461c - std::backtrace_rs::backtrace::trace_unsynchronized::h47697d498917cc3a
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6cbebc461c - std::sys_common::backtrace::_print_fmt::h61e153e4a9281095
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f6cbebc461c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h19e4154d0ad4df85
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6cbec17620 - core::fmt::rt::Argument::fmt::hff5f47072cf5d938
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/fmt/rt.rs:142:9
   5:     0x7f6cbec17620 - core::fmt::write::he88bb017eb7320eb
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f6cbebb84af - std::io::Write::write_fmt::he5d70b9e85592aa1
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/io/mod.rs:1762:15
   7:     0x7f6cbebc4404 - std::sys_common::backtrace::_print::h0f9eda7450aa4845
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f6cbebc4404 - std::sys_common::backtrace::print::h2824fde3c1bc9cf4
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f6cbebc7097 - std::panicking::default_hook::{{closure}}::h1805dbb298de9c25
  10:     0x7f6cbebc6dff - std::panicking::default_hook::ha21d0b6721dee8b1
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/panicking.rs:292:9
  11:     0x7f6cbb8ef240 - std[ebdb09ff591878d7]::panicking::update_hook::<alloc[22a98c5663efe855]::boxed::Box<rustc_driver_impl[5634551524408def]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f6cbebc77d8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha9c965637066c11f
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/alloc/src/boxed.rs:2021:9
  13:     0x7f6cbebc77d8 - std::panicking::rust_panic_with_hook::hc95115aac9b43978
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/panicking.rs:783:13
  14:     0x7f6cbebc752e - std::panicking::begin_panic_handler::{{closure}}::hadf007604e83e37e
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/panicking.rs:657:13
  15:     0x7f6cbebc4ae6 - std::sys_common::backtrace::__rust_end_short_backtrace::h4243b36539a052a4
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f6cbebc7292 - rust_begin_unwind
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/panicking.rs:645:5
  17:     0x7f6cbec13d05 - core::panicking::panic_fmt::h0396d052df2d310c
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/panicking.rs:72:14
  18:     0x7f6cbec13ab3 - core::panicking::panic_display::h5c3aa0fffe5c1bb1
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/panicking.rs:178:5
  19:     0x7f6cbec13ab3 - core::panicking::panic_str::h9aa8a76502539bda
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/panicking.rs:152:5
  20:     0x7f6cbec13ab3 - core::option::expect_failed::h3b7f6a03d7af5d21
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/core/src/option.rs:1985:5
  21:     0x7f6cbe135afe - rustc_middle[29cace5c4948c514]::ty::closure::closure_typeinfo.cold.0
  22:     0x7f6cbd5ec118 - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::closure_typeinfo::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 64usize]>>
  23:     0x7f6cbd5ec0f3 - <rustc_query_impl[94d6f6b2e1186b94]::query_impl::closure_typeinfo::dynamic_query::{closure#2} as core[578f67fda67372d9]::ops::function::FnOnce<(rustc_middle[29cace5c4948c514]::ty::context::TyCtxt, rustc_span[dd40b738055021c1]::def_id::LocalDefId)>>::call_once
  24:     0x7f6cbd5eb6aa - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::VecCache<rustc_span[dd40b738055021c1]::def_id::LocalDefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 64usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  25:     0x7f6cbd5eb3f1 - rustc_query_impl[94d6f6b2e1186b94]::query_impl::closure_typeinfo::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7f6cbd5eabbe - <rustc_middle[29cace5c4948c514]::ty::context::TyCtxt>::closure_captures
  27:     0x7f6cbda01438 - rustc_borrowck[45e3ca37d614772c]::do_mir_borrowck
  28:     0x7f6cbda002ca - rustc_borrowck[45e3ca37d614772c]::mir_borrowck
  29:     0x7f6cbd9ffd6f - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f6cbcceb483 - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::VecCache<rustc_span[dd40b738055021c1]::def_id::LocalDefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  31:     0x7f6cbcceb050 - rustc_query_impl[94d6f6b2e1186b94]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f6cbdc154f1 - <rustc_hir_analysis[9e914fc505a4e762]::collect::type_of::opaque::RpitConstraintChecker>::check
  33:     0x7f6cbb1780d5 - <rustc_hir_analysis[9e914fc505a4e762]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[5a61b80be043b6a0]::intravisit::Visitor>::visit_expr
  34:     0x7f6cbd96c770 - rustc_hir_analysis[9e914fc505a4e762]::collect::type_of::type_of_opaque
  35:     0x7f6cbd96be9b - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>
  36:     0x7f6cbcc53354 - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::DefaultCache<rustc_span[dd40b738055021c1]::def_id::DefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  37:     0x7f6cbdc587de - rustc_query_impl[94d6f6b2e1186b94]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7f6cbccc0a38 - rustc_middle[29cace5c4948c514]::query::plumbing::query_get_at::<rustc_query_system[303543fe729c1791]::query::caches::DefaultCache<rustc_span[dd40b738055021c1]::def_id::DefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>>
  39:     0x7f6cbadd293f - rustc_hir_analysis[9e914fc505a4e762]::collect::type_of::type_of
  40:     0x7f6cbcc544b6 - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>
  41:     0x7f6cbcc53354 - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::DefaultCache<rustc_span[dd40b738055021c1]::def_id::DefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  42:     0x7f6cbcc52f1b - rustc_query_impl[94d6f6b2e1186b94]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7f6cbccc0a38 - rustc_middle[29cace5c4948c514]::query::plumbing::query_get_at::<rustc_query_system[303543fe729c1791]::query::caches::DefaultCache<rustc_span[dd40b738055021c1]::def_id::DefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 8usize]>>>
  44:     0x7f6cbd33164c - rustc_hir_analysis[9e914fc505a4e762]::check::check::check_mod_item_types
  45:     0x7f6cbd330053 - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 0usize]>>
  46:     0x7f6cbd5d4bbb - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::DefaultCache<rustc_span[dd40b738055021c1]::def_id::LocalModDefId, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  47:     0x7f6cbd5d4597 - rustc_query_impl[94d6f6b2e1186b94]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7f6cbd1b00d5 - rustc_hir_analysis[9e914fc505a4e762]::check_crate
  49:     0x7f6cbcf79957 - rustc_interface[91b7e6a880170ab5]::passes::analysis
  50:     0x7f6cbcf795b7 - rustc_query_impl[94d6f6b2e1186b94]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[94d6f6b2e1186b94]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 1usize]>>
  51:     0x7f6cbdb96be4 - rustc_query_system[303543fe729c1791]::query::plumbing::try_execute_query::<rustc_query_impl[94d6f6b2e1186b94]::DynamicConfig<rustc_query_system[303543fe729c1791]::query::caches::SingleCache<rustc_middle[29cace5c4948c514]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[94d6f6b2e1186b94]::plumbing::QueryCtxt, false>
  52:     0x7f6cbdb969d5 - rustc_query_impl[94d6f6b2e1186b94]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  53:     0x7f6cbdb9f5ff - rustc_interface[91b7e6a880170ab5]::interface::run_compiler::<core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>, rustc_driver_impl[5634551524408def]::run_compiler::{closure#1}>::{closure#0}
  54:     0x7f6cbdba691a - std[ebdb09ff591878d7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[91b7e6a880170ab5]::util::run_in_thread_with_globals<rustc_interface[91b7e6a880170ab5]::util::run_in_thread_pool_with_globals<rustc_interface[91b7e6a880170ab5]::interface::run_compiler<core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>, rustc_driver_impl[5634551524408def]::run_compiler::{closure#1}>::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>
  55:     0x7f6cbdba6743 - <<std[ebdb09ff591878d7]::thread::Builder>::spawn_unchecked_<rustc_interface[91b7e6a880170ab5]::util::run_in_thread_with_globals<rustc_interface[91b7e6a880170ab5]::util::run_in_thread_pool_with_globals<rustc_interface[91b7e6a880170ab5]::interface::run_compiler<core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>, rustc_driver_impl[5634551524408def]::run_compiler::{closure#1}>::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[578f67fda67372d9]::result::Result<(), rustc_span[dd40b738055021c1]::ErrorGuaranteed>>::{closure#1} as core[578f67fda67372d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:     0x7f6cbebd1695 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h37189f8e9fbe515c
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/alloc/src/boxed.rs:2007:9
  57:     0x7f6cbebd1695 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hef966e35865ebb05
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/alloc/src/boxed.rs:2007:9
  58:     0x7f6cbebd1695 - std::sys::unix::thread::Thread::new::thread_start::h7d0959f9b7c2f0a7
                               at /rustc/1ab2bcda4303b81b1124b88ddff6f5e9a68d7bc2/library/std/src/sys/unix/thread.rs:108:17
  59:     0x7f6cb8aaa9eb - <unknown>
  60:     0x7f6cb8b2e7cc - <unknown>
  61:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (1ab2bcda4 2023-11-13) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [closure_typeinfo] finding symbols for captures of closure `Foo::test::{closure#0}`
#1 [mir_borrowck] borrow-checking `Foo::test::{closure#0}`
#2 [type_of_opaque] computing type of opaque `Foo::test::{opaque#0}`
#3 [type_of] computing type of `Foo::test::{opaque#0}`
#4 [check_mod_item_types] checking item types in top-level module
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0425, E0593, E0601.
For more information about an error, try `rustc --explain E0425`.

```

</p>
</details>

### LINKED ISSUE #119025: ice: `expected type of closure to be a closure`
auto-reduced (treereduce-rust):
````rust
pub trait Foo {
    async fn baz() -> i32 {
        || if true { 1 } else { 2 } * 3;
    }
}


````

original:
````rust
// edition:2021

#![allow(incomplete_features)]

pub trait Foo {
    // @has async_trait_sig/trait.Foo.html '//h4[@class="code-header"]' "async fn bar() -> i32"
    async fn bar() -> i32;

    // @has async_trait_sig/trait.Foo.html '//h4[@class="code-header"]' "async fn baz() -> i32"
    async fn baz() -> i32 {
    // Test that lambdas behave as unary expressions with block-like expressions
    -if true { 1 } else { 2 } * 3;
    || if true { 1 } else { 2 } * 3;

    //~ ERROR use of undeclared lifetime name `'foo`
    // if true { 1 } else { 2 } * 3
}
}

````

Version information
````
rustc 1.76.0-nightly (e223c4102 2023-12-16)
binary: rustc
commit-hash: e223c41028def5123ffd2a4a51a9109b1aae2c2e
commit-date: 2023-12-16
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0670]: `async fn` is not permitted in Rust 2015
 --> /tmp/icemaker_global_tempdir.Jm5p9C7j0cjw/rustc_testrunner_tmpdir_reporting.L3z3qI7ds0DB/mvce.rs:2:5
  |
2 |     async fn baz() -> i32 {
  |     ^^^^^ to use `async fn`, switch to Rust 2018 or later
  |
  = help: pass `--edition 2021` to `rustc`
  = note: for more on editions, read https://doc.rust-lang.org/edition-guide

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.Jm5p9C7j0cjw/rustc_testrunner_tmpdir_reporting.L3z3qI7ds0DB/mvce.rs:5:2
  |
5 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.Jm5p9C7j0cjw/rustc_testrunner_tmpdir_reporting.L3z3qI7ds0DB/mvce.rs`

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.Jm5p9C7j0cjw/rustc_testrunner_tmpdir_reporting.L3z3qI7ds0DB/mvce.rs:2:27
  |
2 |       async fn baz() -> i32 {
  |  ___________________________^
3 | |         || if true { 1 } else { 2 } * 3;
4 | |     }
  | |_____^ expected `i32`, found `()`

error: internal compiler error: compiler/rustc_mir_build/src/build/mod.rs:654:17: expected type of closure to be a closure

thread 'rustc' panicked at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/compiler/rustc_errors/src/lib.rs:1119:75:
Box<dyn Any>
stack backtrace:
   0:     0x7f2c26b8b10c - std::backtrace_rs::backtrace::libunwind::trace::h40c4f9403e9106ce
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f2c26b8b10c - std::backtrace_rs::backtrace::trace_unsynchronized::h034afacd87380e54
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2c26b8b10c - std::sys_common::backtrace::_print_fmt::h964653ebee1cb7e4
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2c26b8b10c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h74a6e824a409ebfb
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2c26bde6c0 - core::fmt::rt::Argument::fmt::hfbfcbe20f1de6b4b
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2c26bde6c0 - core::fmt::write::h563ec15019c84174
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f2c26b7efff - std::io::Write::write_fmt::ha8bf6bb3a1d25673
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/io/mod.rs:1810:15
   7:     0x7f2c26b8aef4 - std::sys_common::backtrace::_print::h590ad40e00b03203
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2c26b8aef4 - std::sys_common::backtrace::print::hbde661fab8b9de44
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2c26b8dbf7 - std::panicking::default_hook::{{closure}}::h276d0740e1e4dd9a
  10:     0x7f2c26b8d95f - std::panicking::default_hook::h773a22917e51f7ee
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/panicking.rs:292:9
  11:     0x7f2c2995e5a0 - std[2bf2c5e6f42c1d81]::panicking::update_hook::<alloc[3e1464f82126f796]::boxed::Box<rustc_driver_impl[d5b6de9f3c2a441e]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f2c26b8e338 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h55116213a5c0c206
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/alloc/src/boxed.rs:2029:9
  13:     0x7f2c26b8e338 - std::panicking::rust_panic_with_hook::h67d1cc71ec8072bf
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/panicking.rs:783:13
  14:     0x7f2c29996a84 - std[2bf2c5e6f42c1d81]::panicking::begin_panic::<rustc_errors[5f2b31ed444b107e]::ExplicitBug>::{closure#0}
  15:     0x7f2c29992f16 - std[2bf2c5e6f42c1d81]::sys_common::backtrace::__rust_end_short_backtrace::<std[2bf2c5e6f42c1d81]::panicking::begin_panic<rustc_errors[5f2b31ed444b107e]::ExplicitBug>::{closure#0}, !>
  16:     0x7f2c2998e2a6 - std[2bf2c5e6f42c1d81]::panicking::begin_panic::<rustc_errors[5f2b31ed444b107e]::ExplicitBug>
  17:     0x7f2c299a1d58 - <rustc_errors[5f2b31ed444b107e]::diagnostic_builder::Bug as rustc_errors[5f2b31ed444b107e]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  18:     0x7f2c29d86185 - <rustc_errors[5f2b31ed444b107e]::Handler>::bug::<alloc[3e1464f82126f796]::string::String>
  19:     0x7f2c29e205fd - rustc_middle[2c55df33fbcd02e8]::util::bug::opt_span_bug_fmt::<rustc_span[d66e1cc682400b55]::span_encoding::Span>::{closure#0}
  20:     0x7f2c29e09bea - rustc_middle[2c55df33fbcd02e8]::ty::context::tls::with_opt::<rustc_middle[2c55df33fbcd02e8]::util::bug::opt_span_bug_fmt<rustc_span[d66e1cc682400b55]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f2c29e09a88 - rustc_middle[2c55df33fbcd02e8]::ty::context::tls::with_context_opt::<rustc_middle[2c55df33fbcd02e8]::ty::context::tls::with_opt<rustc_middle[2c55df33fbcd02e8]::util::bug::opt_span_bug_fmt<rustc_span[d66e1cc682400b55]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f2c27d638a0 - rustc_middle[2c55df33fbcd02e8]::util::bug::bug_fmt
  23:     0x7f2c29e7857e - rustc_mir_build[f2854bfd4333bdb3]::build::construct_error
  24:     0x7f2c2aeff52a - rustc_mir_build[f2854bfd4333bdb3]::build::mir_built
  25:     0x7f2c2aefde2d - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7f2c2ae7d503 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::VecCache<rustc_span[d66e1cc682400b55]::def_id::LocalDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  27:     0x7f2c2ae7ce90 - rustc_query_impl[982ae447665c173c]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f2c280f704e - rustc_mir_transform[216b0e542727acb1]::check_unsafety::unsafety_check_result
  29:     0x7f2c2ae7d287 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f2c2ae7d503 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::VecCache<rustc_span[d66e1cc682400b55]::def_id::LocalDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  31:     0x7f2c2ae7d010 - rustc_query_impl[982ae447665c173c]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f2c2ae7e4f6 - rustc_mir_transform[216b0e542727acb1]::mir_const
  33:     0x7f2c2ae7e421 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7f2c2ae7d503 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::VecCache<rustc_span[d66e1cc682400b55]::def_id::LocalDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  35:     0x7f2c2ae7cf50 - rustc_query_impl[982ae447665c173c]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f2c28ecd4df - rustc_mir_transform[216b0e542727acb1]::mir_promoted
  37:     0x7f2c2b11e8d2 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 16usize]>>
  38:     0x7f2c2b11eb9c - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::VecCache<rustc_span[d66e1cc682400b55]::def_id::LocalDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  39:     0x7f2c2b11e7d3 - rustc_query_impl[982ae447665c173c]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f2c2ba95a8d - rustc_borrowck[9b01be6d2fbb8954]::mir_borrowck
  41:     0x7f2c2ba959d7 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7f2c2ae7d503 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::VecCache<rustc_span[d66e1cc682400b55]::def_id::LocalDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  43:     0x7f2c2ae7d0d0 - rustc_query_impl[982ae447665c173c]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f2c2bbe8c71 - <rustc_hir_analysis[70e50c671a2d212]::collect::type_of::opaque::RpitConstraintChecker>::check
  45:     0x7f2c291da565 - <rustc_hir_analysis[70e50c671a2d212]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[390f8e9e93ef8f24]::intravisit::Visitor>::visit_expr
  46:     0x7f2c2b6bdbe2 - <rustc_hir_analysis[70e50c671a2d212]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[390f8e9e93ef8f24]::intravisit::Visitor>::visit_block
  47:     0x7f2c2b6bd398 - rustc_hir_analysis[70e50c671a2d212]::collect::type_of::type_of_opaque
  48:     0x7f2c2b6bc973 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  49:     0x7f2c2ac89d14 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::DefaultCache<rustc_span[d66e1cc682400b55]::def_id::DefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  50:     0x7f2c2bc3735e - rustc_query_impl[982ae447665c173c]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  51:     0x7f2c2addaf04 - rustc_middle[2c55df33fbcd02e8]::query::plumbing::query_get_at::<rustc_query_system[6cc3be0e52029f3e]::query::caches::DefaultCache<rustc_span[d66e1cc682400b55]::def_id::DefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>>
  52:     0x7f2c29009b81 - rustc_hir_analysis[70e50c671a2d212]::collect::type_of::type_of
  53:     0x7f2c2ac8aea6 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>
  54:     0x7f2c2ac89d14 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::DefaultCache<rustc_span[d66e1cc682400b55]::def_id::DefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  55:     0x7f2c2ac898db - rustc_query_impl[982ae447665c173c]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  56:     0x7f2c2addaf04 - rustc_middle[2c55df33fbcd02e8]::query::plumbing::query_get_at::<rustc_query_system[6cc3be0e52029f3e]::query::caches::DefaultCache<rustc_span[d66e1cc682400b55]::def_id::DefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 8usize]>>>
  57:     0x7f2c2b8c09c6 - rustc_hir_analysis[70e50c671a2d212]::check::check::check_mod_item_types
  58:     0x7f2c2b8becf3 - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 0usize]>>
  59:     0x7f2c2b7d667b - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::DefaultCache<rustc_span[d66e1cc682400b55]::def_id::LocalModDefId, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  60:     0x7f2c2b7d6057 - rustc_query_impl[982ae447665c173c]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  61:     0x7f2c2b661763 - rustc_hir_analysis[70e50c671a2d212]::check_crate
  62:     0x7f2c2b66a697 - rustc_interface[956eab51901a62c2]::passes::analysis
  63:     0x7f2c2b66a2dd - rustc_query_impl[982ae447665c173c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[982ae447665c173c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 1usize]>>
  64:     0x7f2c2bb79eb2 - rustc_query_system[6cc3be0e52029f3e]::query::plumbing::try_execute_query::<rustc_query_impl[982ae447665c173c]::DynamicConfig<rustc_query_system[6cc3be0e52029f3e]::query::caches::SingleCache<rustc_middle[2c55df33fbcd02e8]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[982ae447665c173c]::plumbing::QueryCtxt, false>
  65:     0x7f2c2bb79cb9 - rustc_query_impl[982ae447665c173c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  66:     0x7f2c2bc2f563 - rustc_interface[956eab51901a62c2]::interface::run_compiler::<core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>, rustc_driver_impl[d5b6de9f3c2a441e]::run_compiler::{closure#0}>::{closure#0}
  67:     0x7f2c2bbac20a - std[2bf2c5e6f42c1d81]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[956eab51901a62c2]::util::run_in_thread_with_globals<rustc_interface[956eab51901a62c2]::util::run_in_thread_pool_with_globals<rustc_interface[956eab51901a62c2]::interface::run_compiler<core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>, rustc_driver_impl[d5b6de9f3c2a441e]::run_compiler::{closure#0}>::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>
  68:     0x7f2c2bbac033 - <<std[2bf2c5e6f42c1d81]::thread::Builder>::spawn_unchecked_<rustc_interface[956eab51901a62c2]::util::run_in_thread_with_globals<rustc_interface[956eab51901a62c2]::util::run_in_thread_pool_with_globals<rustc_interface[956eab51901a62c2]::interface::run_compiler<core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>, rustc_driver_impl[d5b6de9f3c2a441e]::run_compiler::{closure#0}>::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[411d08b4a4626c2f]::result::Result<(), rustc_span[d66e1cc682400b55]::ErrorGuaranteed>>::{closure#1} as core[411d08b4a4626c2f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:     0x7f2c26b981c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdee8ccc00ea3745f
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/alloc/src/boxed.rs:2015:9
  70:     0x7f2c26b981c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h66e7bd21c6afa306
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/alloc/src/boxed.rs:2015:9
  71:     0x7f2c26b981c5 - std::sys::unix::thread::Thread::new::thread_start::he285325b4cca362f
                               at /rustc/e223c41028def5123ffd2a4a51a9109b1aae2c2e/library/std/src/sys/unix/thread.rs:108:17
  72:     0x7f2c269849eb - <unknown>
  73:     0x7f2c26a087cc - <unknown>
  74:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (e223c4102 2023-12-16) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `Foo::baz::{closure#0}::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `Foo::baz::{closure#0}::{closure#0}`
#2 [mir_const] preparing `Foo::baz::{closure#0}::{closure#0}` for borrow checking
#3 [mir_promoted] promoting constants in MIR for `Foo::baz::{closure#0}::{closure#0}`
#4 [mir_borrowck] borrow-checking `Foo::baz::{closure#0}::{closure#0}`
#5 [type_of_opaque] computing type of opaque `Foo::baz::{opaque#0}`
#6 [type_of] computing type of `Foo::baz::{opaque#0}`
#7 [check_mod_item_types] checking item types in top-level module
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0601, E0670.
For more information about an error, try `rustc --explain E0308`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #117794
Fixes #117886
Fixes #119025

Prior to change #117418, the value of ﻿`concrete_opaque_types` for ﻿`mir_borrock(T::a::opaque)` was ﻿`None`. However, due to modifications in `﻿body.local_decls`, the return value had been changed.

The changed of `﻿body.local_decls` has let to the addition of `﻿ty:Error` to ﻿`infcx.opaque_type_storage.opaque_types` during ﻿`TypeChecker::equate_inputs_and_outputs`. This is due to it utilizing the output of a function signature that was appended during ﻿`construct_error`(which previously only appended a `ty::Error`) and then execute `TypeChecker::Related_types`.

Therefore, in this PR, I've implemented a condition to bypass the ﻿rpit check when an error is encountered.

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm still not sure why the ICE in #117794 happens, and this seems like a strange way to be avoiding an ICE in mir-building...

**Comment by bvanjoi** [comment]
I think the root cause of the issue can be traced back to the modifications made in ﻿`body.local_decls`:

1. Prior to change #117418, it only contained ﻿`ty::Error`, but now it includes the output of the function signature.
2. This has led to changes in [mir_opaque_ty](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs#L279), which previously held ﻿`None`, but now contains `﻿ty: ty::Error`. Specifically, this amendment took place in [checker.equate_inputs_and_outputs](https://github.com/rust-lang/rust/blob/master/compiler/rustc_borrowck/src/type_check/mod.rs#L197).
3. This means that we have executed additional [RpitConstraintChecker](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs#L288), and #117794 is to encounter a panic during the visit.

Therefore, in this PR, I've implemented a condition to bypass the checker when `﻿mir_opaque_ty` includes a `﻿ty::Error`.

Another potential solution to this issue could involve altering the handling for `﻿ty:: Closure` as introduced in #117418.

**Comment by bvanjoi** [comment]
I have made a minor modification: if a type error is found, then the borrow check is skipped during the ﻿`RpitConstraintChecker` visit. This should maintain the same effect as before.

**Comment by compiler-errors** [comment]
I'm still not certain this is the right way to fix this bug. I would be much more satisfied if we understood what is wrong with mir building that leads to this issue -- this seems to be fixing a symptom of the problem, rather than the actual problem itself, in my opinion.

File: compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs [hunk 1]
```diff
@@ -324,6 +324,9 @@ struct RpitConstraintChecker<'tcx> {
 impl RpitConstraintChecker<'_> {
     #[instrument(skip(self), level = "debug")]
     fn check(&self, def_id: LocalDefId) {
+        if self.found.references_error() {
+            return;
+        }
         // Use borrowck to get the type with unerased regions.
         let concrete_opaque_types = &self.tcx.mir_borrowck(def_id).concrete_opaque_types;
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs:331]: I still don't think this is the right fix, because we should be able to call `mir_borrowck` on any def id at this point without causing issues..?

Either that, or we should check if `self.tcx.typeck(def_id).tainted_by_errors.is_some()` rather than `self.found.references_error()`...

**Comment by bvanjoi** [comment]
> if we understood what is wrong with mir building that leads to this issue

Thanks for this tip, and I'll delve deeper

**Comment by compiler-errors** [comment]
This also should fix #119025.
