### PR TITLE
Fix bad error message with `::<` in types

### LINKED ISSUE #36116: Using `Foo::<Bar>` in some contexts where a type is expected gives wrong error message
The following example gives a wrong error message:

```rust
fn main() {
    let f = foo.map(|a| a as Foo::<Bar>);
}
```

```rust
error: expected identifier, found `<`
 --> b.rs:2:35
  |
2 |     let f = foo.map(|a| a as Foo::<Bar>);
  |                                   ^

error: chained comparison operators require parentheses
 --> b.rs:2:35
  |
2 |     let f = foo.map(|a| a as Foo::<Bar>);
  |                                   ^^^^^^
  |
  = help: use `::<...>` instead of `<...>` if you meant to specify type arguments

error: expected expression, found `)`
 --> b.rs:2:40
  |
2 |     let f = foo.map(|a| a as Foo::<Bar>);
  |                                        ^

error: aborting due to 4 previous errors
```
The ``help: use `::<...>` instead of `<...>` `` bit is wrong and suggests the opposite of the fix.

---

Note that none of the following give that error message:

```rust
fn main() {
    let g = a as Foo::<Bar>;
}
```
gives
```rust
error: expected identifier, found `<`
 --> b.rs:2:23
  |
2 |     let g = a as Foo::<Bar>;
  |                       ^

error: aborting due to previous error
```
and
```rust
fn main() {
    let g: Foo::<Bar>;
}
```
gives
```rust
error: expected identifier, found `<`
 --> b.rs:2:17
  |
2 |     let g: Foo::<Bar>;
  |                 ^

error: aborting due to previous error
```

which are correct but could be more explicit about the problem.

### PR DESCRIPTION
**Pull request by mcarton**
Fix #36116.

Before:

``` rust
error: expected identifier, found `<`
  --> src/test/compile-fail/issue-36116.rs:16:52
   |
16 |     let f = Some(Foo { _a: 42 }).map(|a| a as Foo::<i32>);
   |                                                    ^

error: chained comparison operators require parentheses
  --> src/test/compile-fail/issue-36116.rs:16:52
   |
16 |     let f = Some(Foo { _a: 42 }).map(|a| a as Foo::<i32>);
   |                                                    ^^^^^^
   |
   = help: use `::<...>` instead of `<...>` if you meant to specify type arguments

error: expected expression, found `)`
  --> src/test/compile-fail/issue-36116.rs:16:57
   |
16 |     let f = Some(Foo { _a: 42 }).map(|a| a as Foo::<i32>);
   |                                                         ^

error: expected identifier, found `<`
  --> src/test/compile-fail/issue-36116.rs:20:17
   |
20 |     let g: Foo::<i32> = Foo { _a: 42 };
   |                 ^

error: aborting due to 5 previous errors
```

After:

``` rust
error: unexpected token: `::`
  --> src/test/compile-fail/issue-36116.rs:16:50
   |
16 |     let f = Some(Foo { _a: 42 }).map(|a| a as Foo::<i32>);
   |                                                  ^^
   |
   = help: use `<...>` instead of `::<...>` if you meant to specify type arguments

error: unexpected token: `::`
  --> src/test/compile-fail/issue-36116.rs:20:15
   |
20 |     let g: Foo::<i32> = Foo { _a: 42 };
   |               ^^
   |
   = help: use `<...>` instead of `::<...>` if you meant to specify type arguments

error: aborting due to 2 previous errors
```

### CODE REVIEW

**Comment by pnkfelix** [comment]
(travis failure seemed spurious; i'm giving it another shot and also starting a review.)

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -1802,6 +1802,20 @@ impl<'a> Parser<'a> {
             // First, parse an identifier.
             let identifier = self.parse_path_segment_ident()?;
 
+            if
+                self.check(&token::ModSep) &&
```
Comment (pnkfelix) [inline src/libsyntax/parse/parser.rs]: stylistically I don't think we put line breaks between the `if` and the condition expression in cases like this.

File: src/test/compile-fail/issue-36116.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+struct Foo<T> {
+    _a: T,
+}
+
+fn main() {
+    let f = Some(Foo { _a: 42 }).map(|a| a as Foo::<i32>);
+    //~^ERROR unexpected token: `::`
```
Comment (pnkfelix) [inline src/test/compile-fail/issue-36116.rs]: stylistically I think we tend to separate the arrow (the `^` and the `|`) and the `ERROR`/`WARN` by putting a space between them.

**Comment by pnkfelix** [comment]
These changes seem fine to me. I had stylistic nits that would be nice to address.

**Comment by pnkfelix** [comment]
In other words, r=me once nits are addressed.

**Comment by mcarton** [comment]
Addressed nits.

**Comment by cramertj** [comment]
@pnkfelix Any reason this hasn't been merged yet?

**Comment by GuillaumeGomez** [comment]
It seems your code fails:

```
error: attempted access of field `last_span` on type `&mut parse::parser::Parser<'a>`, but no field with that name was found
    --> ../src/libsyntax/parse/parser.rs:1762:33
     |
1762 |                 let last_span = self.last_span;
     |                                 ^^^^^^^^^^^^^^

error: aborting due to previous error
```

Please update your code and I'll re-r+ it.

@bors: r-

**Comment by mcarton** [comment]
@GuillaumeGomez done. Thanks for pointing that out, that field was renamed in #36470.

**Comment by pnkfelix** [comment]
It has been pointed out that this commit series needs revision. It should be rebased (to remove the merge commit) and squashed into a smaller series of commits, e.g. One commit maybe

**Comment by mcarton** [comment]
No problem, done.

**Comment by pnkfelix** [comment]
Great, thanks for your patience and perseverance @mcarton
