### PR TITLE
Fix ICE when pointing at multi bytes character

### LINKED ISSUE #80134: "é" in the code  caused "bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32"
Was reported here : https://github.com/rust-lang/rust/issues/68730
but still occurring.

### Code

```Rust
fn main() {
    let matches = App::new()
        .arg(
            Arg::with_name(OPT_MODE)é
        );
    
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (b32e6e6ac 2020-12-16)
binary: rustc
commit-hash: b32e6e6ac8921035177256ab6806e6ab0d4b9b94
commit-date: 2020-12-16
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
  Compiling bug v0.1.0 (/tmp/bug)
     Running `rustc --crate-name bug --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=51917d1ea2d63dad -C extra-filename=-51917d1ea2d63dad --out-dir /tmp/bug/target/debug/deps -C incremental=/tmp/bug/target/debug/incremental -L dependency=/tmp/bug/target/debug/deps`
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1489:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (b32e6e6ac 2020-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `bug`

Caused by:
  process didn't exit successfully: `rustc --crate-name bug --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=51917d1ea2d63dad -C extra-filename=-51917d1ea2d63dad --out-dir /tmp/bug/target/debug/deps -C incremental=/tmp/bug/target/debug/incremental -L dependency=/tmp/bug/target/debug/deps` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1489:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b32e6e6ac8921035177256ab6806e6ab0d4b9b94/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/b32e6e6ac8921035177256ab6806e6ab0d4b9b94/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/b32e6e6ac8921035177256ab6806e6ab0d4b9b94/library/core/src/panicking.rs:50:5
   3: rustc_span::SourceFile::lookup_file_pos
   4: rustc_span::SourceFile::lookup_file_pos_with_col_display
   5: rustc_span::source_map::SourceMap::is_multiline
   6: rustc_parse::parser::Parser::parse_seq_to_before_tokens
   7: rustc_parse::parser::Parser::parse_delim_comma_seq
   8: rustc_parse::parser::expr::<impl rustc_parse::parser::Parser>::parse_dot_or_call_expr_with_
   9: rustc_parse::parser::expr::<impl rustc_parse::parser::Parser>::parse_dot_or_call_expr_with
  10: rustc_parse::parser::expr::<impl rustc_parse::parser::Parser>::parse_prefix_expr::{{closure}}
  11: rustc_parse::parser::expr::<impl rustc_parse::parser::Parser>::parse_prefix_expr
  12: rustc_parse::parser::expr::<impl rustc_parse::parser::Parser>::parse_assoc_expr_with
  13: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_local
  14: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_stmt_without_recovery::{{closure}}
  15: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_stmt_without_recovery
  16: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_full_stmt
  17: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_block_tail
  18: rustc_parse::parser::stmt::<impl rustc_parse::parser::Parser>::parse_block_common
  19: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_kind
  20: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_common_
  21: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_common
  22: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item
  23: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_mod
  24: rustc_parse::parse_crate_from_file
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
  26: rustc_interface::passes::parse
  27: rustc_interface::queries::Queries::parse
  28: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  29: rustc_span::with_source_map
  30: rustc_interface::interface::create_compiler_and_run
  31: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (b32e6e6ac 2020-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

```

</p>
</details>

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #80134

Seems this ICE was introduced by #73953, checking width of span to avoid ICE.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Oh, `find_width_of_character_at_span` doesn't work well on the original case, one sec...

**Comment by JohnTitor** [comment]
So, in `next_point`, `width` will be 1 since it's shrinked and `next_point` doesn't return the span on multibyte character correctly here.

https://github.com/rust-lang/rust/blob/8bb302d34dde36cc78a288cb5beb4af7fe30ba41/compiler/rustc_span/src/source_map.rs#L777-L790

I think using `sp` for now is the easist way, though it regresses some suggestion (but I think it's fine as `MaybeIncorrect`).

File: src/test/ui/parser/issue-80134.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+fn main() {
```
Comment (davidtwco) [inline src/test/ui/parser/issue-80134.rs:1]: Could you rename this test file to be more descriptive?

**Review by davidtwco — CHANGES_REQUESTED** [review]
I'd prefer that we work out how to fix `next_point` (or `find_width_of_character_at_span`) so that it returns a correct span here. Assuming that `sp` is valid (and if it isn't, we should fix that), I'd expect that calling `next_point` should always do the correct thing.

File: src/test/ui/parser/issue-80134.rs (hunk 1 above)
Comment (JohnTitor) [reply src/test/ui/parser/issue-80134.rs:1]: What the name do you prefer?

**Comment by JohnTitor** [comment]
> I'd prefer that we work out how to fix next_point (or find_width_of_character_at_span) so that it returns a correct span here. 

The `next_point` behavior was changed by https://github.com/rust-lang/rust/commit/3250057da983fa4d5bfd0799adaa41cb038f0e25 (cc @estebank), I'm not sure how we could deal with that while preventing known ICEs...

File: src/test/ui/parser/issue-80134.rs (hunk 1 above)
Comment (davidtwco) [reply src/test/ui/parser/issue-80134.rs:1]: `multibyte-char-use-seperator-issue-80134.rs`? It's long but I'm trying to avoid landing more tests that are named `issue-XXXXX.rs`.

**Comment by davidtwco** [comment]
> 
> 
> > I'd prefer that we work out how to fix next_point (or find_width_of_character_at_span) so that it returns a correct span here.
> 
> The `next_point` behavior was changed by [3250057](https://github.com/rust-lang/rust/commit/3250057da983fa4d5bfd0799adaa41cb038f0e25) (cc @estebank), I'm not sure how we could deal with that while preventing known ICEs...

If you don't think there's a more general fix here then I'm happy to land this - I'll approve and r=me after the last comment is resolved :)

**Comment by JohnTitor** [comment]
Rebased and applied filename suggestion on review.

> If you don't think there's a more general fix here then I'm happy to land this - I'll approve and r=me after the last comment is resolved :)

I don't have any idea how we could fix it right now, I'm going to r=you for now as the regression would affect rustfix only. Created a Zulip stream for further discussion: https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/.60SourceMap.3A.3Anext_point.60.20cannot.20point.20multibyte.20character

@bors r=davidtwco
