### PR TITLE
Detect and provide suggestion for `&raw EXPR`

### LINKED ISSUE #133231: Terse parse error on `&raw expr`
I tried this code:

```rust
mod foo {
    pub static A: i32 = 0;
    pub static B: i32 = 0;
    pub static C: i32 = 0;
}


fn main() {
    let _arr = [ &raw foo::A, &raw foo::B, &raw foo::C ];
}
```

I expected to see this happen: Code compiles normally

Instead, this happened: A parser error.

```
error: expected one of `!`, `,`, `.`, `::`, `;`, `?`, `]`, `{`, or an operator, found `foo`
 --> src/main.rs:9:23
  |
9 |     let _arr = [ &raw foo::A, &raw foo::B, &raw foo::C ];
  |                       ^^^ expected one of 9 possible tokens
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```

### PR DESCRIPTION
**Pull request by compiler-errors**
When emitting an error in the parser, and we detect that the previous token was `raw` and we *could* have consumed `const`/`mut`, suggest that this may have been a mistyped raw ref expr. To do this, we add `const`/`mut` to the expected token set when parsing `&raw` as an expression (which does not affect the "good path" of parsing, for the record).

This is kind of a rudimentary error improvement, since it doesn't actually attempt to recover anything, leading to some other knock-on errors b/c we still treat `&raw` as the expression that was parsed... but at least we add the suggestion! I don't think the parser grammar means we can faithfully recover `&raw EXPR` early, i.e. during `parse_expr_borrow`.

Fixes #133231

### CODE REVIEW

File: compiler/rustc_parse/src/parser/expr.rs [hunk 1]
```diff
@@ -829,6 +829,18 @@ impl<'a> Parser<'a> {
         if let Some(lt) = lifetime {
             self.error_remove_borrow_lifetime(span, lt.ident.span.until(expr.span));
         }
+
+        // Add expected tokens if we parsed `&raw` as an expression.
+        // This will make sure we see "expected `const`, `mut`", and
+        // guides recovery in case we write `&raw expr`.
+        if borrow_kind == ast::BorrowKind::Ref
+            && mutbl == ast::Mutability::Not
+            && matches!(&expr.kind, ExprKind::Path(None, p) if p.is_ident(kw::Raw))
```
Comment (fmease) [inline compiler/rustc_parse/src/parser/expr.rs:838]: (minor) `is_ident` or this `matches!` needs to account for raw identifiers, so we can exclude `r#raw` (*raw raw*) here

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:838]: This is a parsed ident, not an ident token, so we don't have a way to distinguish `r#raw` here, since ident is just a span and a symbol.

**Comment by compiler-errors** [comment]
r? oli-obk

File: compiler/rustc_parse/src/parser/expr.rs (hunk 1 above)
Comment (oli-obk) [reply compiler/rustc_parse/src/parser/expr.rs:838]: Hmm 🤔 why is this being checked on the parsed expr and not as a lookahead after parsing the borrow modifiers? I guess kinda related to the recovery comment above, but would trivially allow checking for non-raw ident

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/expr.rs:838]: Well we do want to avoid putting the expectation down for something like `&raw.field`
