### PR TITLE
core: Fix size_hint for signed integer Range<T> iterators

### LINKED ISSUE #24851: Overflow in Range<A> size_hint()
`size_hint` is not implemented correctly for the ranges, it overflows:

```
playbot: (-1i8..127).size_hint()
-playbot:#rust-internals- (18446744073709551488, Some(18446744073709551488))
```

Expected result: 128

With other compilation settings, the result is:

    'Error: arithmetic operation overflowed'

### PR DESCRIPTION
**Pull request by bluss**
core: Fix size_hint for signed integer `Range<T>` iterators

There was an overflow bug in .size_hint() for signed iterators, which
produced an hilariously incorrect size or an overflow panic.

Incorrect size is a serious bug since the iterators are marked
ExactSizeIterator. (And leads to abort() on (-1i8..127).collect() when
the collection tries to preallocate too much).

> (-1i8..127).size_hint()
> (18446744073709551488, Some(18446744073709551488))

Bug found using quickcheck.

Fixes #24851

### CODE REVIEW

**Comment by bluss** [comment]
I think this bug fix should be merged to the beta branch.

File: src/libcore/iter.rs [hunk 1]
```diff
@@ -2407,6 +2407,8 @@ pub trait Step: PartialOrd {
     /// `start` should always be less than `end`, so the result should never
     /// be negative.
     ///
+    /// `by` must be > 0.
+    ///
     /// Returns `None` if it is not possible to calculate steps_between
```
Comment (bluss) [inline src/libcore/iter.rs]: Explanation: "Result should never be negative" above implies this.

File: src/libcore/iter.rs [hunk 2]
```diff
@@ -2423,7 +2425,11 @@ macro_rules! step_impl {
             #[allow(trivial_numeric_casts)]
             fn steps_between(start: &$t, end: &$t, by: &$t) -> Option<usize> {
                 if *start <= *end {
-                    Some(((*end - *start) / *by) as usize)
+                    // Note: We assume $t <= usize/isize here
+                    Some(
+                        ((*end as isize).wrapping_sub(*start as isize) as usize
```
Comment (alexcrichton) [inline src/libcore/iter.rs]: Is this `wrapping_sub` needed here because `start` is verified to be less than `end`?

Comment (bluss) [inline src/libcore/iter.rs]: Since you ask, I should probably insert a comment there.

It's needed because the length of a Range<i8> or Range<i64> etc may be larger than the maximum of the signed type. We compute a wrapping sub and cast to unsigned and get the correct value.

Comment (alexcrichton) [inline src/libcore/iter.rs]: Oh so this is handling the case where you're calculating the `steps_between` something like `usize::max_value() - 10` and 0? In that case I can see where the subtraction might legitimately overflow (but it's ok)!

Comment (alexcrichton) [inline src/libcore/iter.rs]: (I do agree though that a comment would be nice)

Comment (bluss) [inline src/libcore/iter.rs]: See the test cases. It shouldn't be able to be larger than usize::MAX. (We guarantee ExactSizeIterator here and would have to revoke that).

Comment (bluss) [inline src/libcore/iter.rs]: Ugh, my patch is totally broken because I've been thinking *only* about the signed case. Need to account for the unsigned case too, I understand if it's puzzling to read.

Comment (alexcrichton) [inline src/libcore/iter.rs]: You may want to add a few test cases that use integer types larger than `i8` and `i16` as well because they'll always fit into an `isize` right now.

Comment (bluss) [inline src/libcore/iter.rs]: I'm adding a test case for isize now. `(-2..isize::MAX).size_hint();` was correct in optimized code already, but overflows in debug mode. Sad times.

**Comment by bluss** [comment]
Updated. I chose to split unsigned and signed.

**Comment by alexcrichton** [comment]
@bors: r+ 95be21df477655131627def1943de73922b1f6a4

Thanks!

**Comment by bluss** [comment]
This is just some weird bors failure

**Comment by bluss** [comment]
I'd like to nominate this for beta inclusion. (Can I do that?)

**Comment by pnkfelix** [comment]
triage: beta-nominated

(just want to ensure discussion; not directly advocating.)

**Comment by pnkfelix** [comment]
not accepted for beta backport.
