### PR TITLE
`unwrap_usize` should at least try to evaluate the underlying constant

### LINKED ISSUE #59016: Compiler panic when using a slice pattern
I got ``thread 'rustc' panicked at 'expected `LazyConst` to contain a usize', src/libcore/option.rs:1038:5`` when using a slice pattern.

Example code:
```rust
trait Gen<T> {
    fn gen(&self) -> T;
}

impl<T, F: Fn() -> T> Gen<T> for F {
    fn gen(&self) -> T {
        self()
    }
}

fn byte_gen() -> impl Gen<u8> {
    || 42
}

fn array_3_gen<T>(elem_gen: impl Gen<T>) -> impl Gen<[T; 3]> {
    move || [elem_gen.gen(), elem_gen.gen(), elem_gen.gen()]
}

fn main() {
    // let bytes = array_3_gen(byte_gen()).gen(); // no panic
    let [a, b, c] = array_3_gen(byte_gen()).gen(); // panic!
}
```
Compiler output:
```text
$ cargo build
   Compiling foo v0.1.0 (/home/rustlover/code/rust/foo)
thread 'rustc' panicked at 'expected `LazyConst` to contain a usize', src/libcore/option.rs:1038:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `foo`.

To learn more, run the command again with --verbose.
```
Compiler version:
```
$ rustc --version --verbose
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-unknown-linux-gnu
release: 1.33.0
LLVM version: 8.0
```
Backtrace:
```text
stack backtrace:
   0:     0x7f2ec5eff793 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf8722b0178fb1b63
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7f2ec5ef7c48 - std::sys_common::backtrace::_print::hc40139e5f1d656ee
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x7f2ec5efb922 - std::panicking::default_hook::{{closure}}::h993d43465919c16a
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x7f2ec5efb694 - std::panicking::default_hook::h73d2c2ec3d9ba5a4
                               at src/libstd/panicking.rs:215
   4:     0x7f2ec19ae31f - rustc::util::common::panic_hook::he83c1d31ee2662ae
   5:     0x7f2ec5efc109 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                               at src/libstd/panicking.rs:482
   6:     0x7f2ec5efbbb1 - std::panicking::continue_panic_fmt::h3557b3c3fa21b47b
                               at src/libstd/panicking.rs:385
   7:     0x7f2ec5efba95 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   8:     0x7f2ec5f25cac - core::panicking::panic_fmt::h74ee8034b317ceed
                               at src/libcore/panicking.rs:85
   9:     0x7f2ec5f25dc2 - core::option::expect_failed::hbc312d76c0b547f0
                               at src/libcore/option.rs:1038
  10:     0x7f2ec3e6b549 - rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::check_pat_walk::h71a84aaf4490c100
  11:     0x7f2ec3eaba89 - rustc_typeck::check::FnCtxt::check_decl_local::h6cd4344ce4d41c65
  12:     0x7f2ec3eabb97 - rustc_typeck::check::FnCtxt::check_stmt::h75310cceec23d2e4
  13:     0x7f2ec3eac00a - rustc_typeck::check::FnCtxt::check_block_with_expected::h3bfd8e88110fd9f1
  14:     0x7f2ec3ea11ff - rustc_typeck::check::FnCtxt::check_expr_kind::h375a1326cead31d6
  15:     0x7f2ec3ea0f90 - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs::h2ae4f0da43669b47
  16:     0x7f2ec3ea0139 - rustc_typeck::check::FnCtxt::check_return_expr::hd9c52b2ec7e22022
  17:     0x7f2ec3e9054c - rustc_typeck::check::check_fn::h3d19cb057f16bf14
  18:     0x7f2ec3fbd982 - rustc::ty::context::GlobalCtxt::enter_local::hc07cc749cef8eb1a
  19:     0x7f2ec3e8f1ef - rustc_typeck::check::typeck_tables_of::hb454bb4b066528cf
  20:     0x7f2ec190510c - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_tables_of<'tcx>>::compute::hc5eac1e163f72b87
  21:     0x7f2ec1580276 - rustc::dep_graph::graph::DepGraph::with_task_impl::h0b7551d53ac8e004
  22:     0x7f2ec1776a8c - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h7b6cd2762bee21db
  23:     0x7f2ec184a83e - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query::h001f5d6204e1c3a1
  24:     0x7f2ec3f0f30c - rustc::session::Session::track_errors::h6e57172230d7fa6d
  25:     0x7f2ec3e8ecde - rustc_typeck::check::typeck_item_bodies::hfbbc2617bda77f6d
  26:     0x7f2ec3dcb446 - rustc::ty::query::__query_compute::typeck_item_bodies::hc29cdeb125e5955e
  27:     0x7f2ec3f40bf8 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_item_bodies<'tcx>>::compute::h93523efffb25e349
  28:     0x7f2ec3f19ca5 - rustc::dep_graph::graph::DepGraph::with_task_impl::h203bcc11c6603b1b
  29:     0x7f2ec3f9b2b7 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::hdf3aec97cbb89d46
  30:     0x7f2ec3d556a4 - rustc::util::common::time::h3c5cedd106c5f0e8
  31:     0x7f2ec3f37ded - rustc_typeck::check_crate::hba6d5def7fb55eec
  32:     0x7f2ec62a2b85 - <std::thread::local::LocalKey<T>>::with::hcaf51866d9f51790
  33:     0x7f2ec621dc2e - rustc::ty::context::TyCtxt::create_and_enter::hf8fff029ce04ca77
  34:     0x7f2ec62d5414 - rustc_driver::driver::compile_input::h65aaa3180b3e84e4
  35:     0x7f2ec6230dd0 - rustc_driver::run_compiler_with_pool::h7731b79ae97e4d21
  36:     0x7f2ec623cc05 - <scoped_tls::ScopedKey<T>>::set::h10a9d6691c6667b2
  37:     0x7f2ec622fc1a - rustc_driver::run_compiler::hccae18cc847caa81
  38:     0x7f2ec623cdba - <scoped_tls::ScopedKey<T>>::set::h71212949a1d6fa63
  39:     0x7f2ec62ae802 - std::sys_common::backtrace::__rust_begin_short_backtrace::h76607ec057ea37b9
  40:     0x7f2ec5f0d529 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:92
  41:     0x7f2ec62c5fa0 - <F as alloc::boxed::FnBox<A>>::call_box::h33b88f71d009a576
  42:     0x7f2ec5f0c2ed - std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  43:     0x7f2ec5c7f6da - start_thread
  44:     0x7f2ec559c88e - __clone
  45:                0x0 - <unknown>
query stack during panic:
#0 [typeck_tables_of] processing `main`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
```

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb 

fixes #59016

I know that I'm still using `ParamEnv` wrongly, but that's a preexisting issue not amplified by this PR.

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @nikomatsakis 	this is related to lazy normalization. I could probably run the regular opportunistic normalization on the types (and thus the array lengths inside the array types) obtained in https://github.com/rust-lang/rust/blob/ad8a3eb039ca3dc1ff5a3d5757afc5e5330c1bce/src/librustc_typeck/check/_match.rs#L396 but I'm not sure if we'd ever catch all the cases (the linked issue shows other similar ICEs)

File: src/librustc/ty/sty.rs [hunk 1]
```diff
@@ -2151,64 +2151,60 @@ impl<'tcx> Const<'tcx> {
...
-        ty: ParamEnvAnd<'tcx, Ty<'tcx>>,
+        ty: Ty<'_>,
     ) -> Option<u128> {
-        assert_eq!(self.ty, ty.value);
+        assert_eq!(self.ty, ty);
+        let tcx = tcx.global_tcx();
         let ty = tcx.lift_to_global(&ty).unwrap();
-        let size = tcx.layout_of(ty).ok()?.size;
-        self.val.try_to_bits(size)
+        // FIXME(eddyb, oli-obk) get the right param_env.
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Can you keep the hacks at callsites? Most calls should not need to use `ParamEnv::empty()`.

File: src/librustc/ty/sty.rs [hunk 2]
```diff
@@ -2151,64 +2151,60 @@ impl<'tcx> Const<'tcx> {
...
+                let instance = ty::Instance::resolve(tcx, ParamEnv::empty(), did, substs)?;
+                let gid = GlobalId {
+                    instance,
+                    promoted: None,
+                };
+                let evaluated = tcx.const_eval(ParamEnv::empty().and(gid)).ok()?;
+                evaluated.val.try_to_bits(size)
+            },
+            // FIXME(const_generics): try to evaluate generic consts with a given param env?
+            // E.g. when you have an associated constant whose value depends on a generic const
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: Not sure what this refers to.

Comment (oli-obk) [reply src/librustc/ty/sty.rs]: Well, there are other "unevaluated" const values (Infer and Param) that could be attempted to be evaluated here.

File: src/librustc/ty/sty.rs (hunk 1 above)
Comment (eddyb) [reply src/librustc/ty/sty.rs]: Looking at this, at least everything `InferCtxt` does has a `ParamEnv`:
https://github.com/rust-lang/rust/blob/3f36ac4e835dfa0af77d5261a444a674ec9da3a5/src/librustc/infer/combine.rs#L44-L48
Here's an example of where `TypeRelation` could have a method to get it:
https://github.com/rust-lang/rust/blob/3f36ac4e835dfa0af77d5261a444a674ec9da3a5/src/librustc/infer/equate.rs#L25-L30

cc @nikomatsakis @varkor Can we let `TypeRelation` know the `ParamEnv`?

File: src/librustc/ty/sty.rs (hunk 2 above)
Comment (eddyb) [reply src/librustc/ty/sty.rs]: `Infer`, maybe, but doubtful (only makes sense within an inference context, but, really, shouldn't happen w/o lazy normalization support in `ty::relate`).

`Param` is not "unevaluated", it means the `ty::Const` is still generic - there's nothing to replace it with.

File: src/librustc/ty/sty.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc/ty/sty.rs]: I made `TypeRelation` have a method that returns the `ParamEnv` (although I left a few cases as `ParamEnv::empty()` and added a FIXME.

Now I'm stuck with trying to lift the following `ParamEnv` to the global tcx:

```
error: internal compiler error: src/librustc/ty/sty.rs:2163: cannot lift ParamEnvAnd {                                                                                                                       
    param_env: ParamEnv {
        caller_bounds: [
            Binder(
                OutlivesPredicate(
                    '_#0r,
                    '_#1r
                )
            )
        ],
        reveal: UserFacing,
        def_id: None
    },
    value: usize
} for Const {
    ty: usize,
    val: Scalar(
        Bits {
            size: 8,
            bits: 2
        }
    )
}
```

In this case the `ParamEnv` is pretty useless considering that all we're doing is to try to compute the layout of `usize`. We can't lift it because it only exists in the local interner as it was created on the fly for

```
#0 [evaluate_obligation] evaluating trait selection obligation `&[&str; 2]: marker::Copy`
```

Comment (eddyb) [reply src/librustc/ty/sty.rs]: You need to use canonicalization in the `const_eval` query to do this then - which is the correct approach. It means inference variables are replaced with a kind of "type parameter".
Since `const_eval` doesn't actually do any inference itself, you could treat `ty::Placeholder` (I think?) as `ty::Param`, but I'm not sure, @nikomatsakis should comment on this.

You could search for `canonicalize_query` around to find some examples, like this:
https://github.com/rust-lang/rust/blob/54479c624cc24bb852291d83e11cc19389dcb21b/src/librustc/traits/query/outlives_bounds.rs#L99-L130

Comment (eddyb) [reply src/librustc/ty/sty.rs]: As for your failure... you could work around it for now by having a non-ICE error path for failing to lift the `param_env, just like for failing to lift the `substs`, e.g.:
https://github.com/rust-lang/rust/blob/54479c624cc24bb852291d83e11cc19389dcb21b/src/librustc/traits/select.rs#L781

and (but this tries them separately for a reason not applicable in your case):

https://github.com/rust-lang/rust/blob/54479c624cc24bb852291d83e11cc19389dcb21b/src/librustc/traits/fulfill.rs#L462-L467

Comment (oli-obk) [reply src/librustc/ty/sty.rs]: I considered that, but I don't think it's going to go well. We have perfectly evaluable constants, that are actually evaluated today (due to `ParamEnv::empty()`, and suddenly they would stop being evaluable even though they are "obviously" fine. If we suddenly can't check for zero length arrays, a bunch of type system things will change (e.g. `[String; 0]` would stop being promotable).

I can try it out, but I can't really judge the consequences of doing so.

Comment (eddyb) [reply src/librustc/ty/sty.rs]: Ahhh, you should be doing something like this then:
https://github.com/rust-lang/rust/blob/54479c624cc24bb852291d83e11cc19389dcb21b/src/librustc/traits/project.rs#L404-L406

That is, falling back to trying to evaluate the constant with identity substitutions. You can also get `tcx.param_env(def_id)` for the "identity `ParamEnv`" (which is the most general, too; both the substs and the param env should be empty today, anyway, for things like array lengths).

(I'm not sure why I wasn't more general in the linked code, heh)

**Comment by oli-obk** [comment]
@eddyb is 1650513 what you had in mind?

**Comment by eddyb** [comment]
~~I was thinking of `tcx.lift_to_global(&substs).unwrap()`, but it makes sense if the type also contains inference variables...
The code is confusing, maybe split the `ParamEnvAnd` before doing anything to it?~~

~~But really, you're calling `.unwrap_or_else(|| bug!(...))` - my point was to *not* panic in those cases, but rather... I don't even know what's happening anymore :(~~

Your error says this is what can't be lifted:
```rust
ParamEnvAnd {                                                                                                                       
    param_env: ParamEnv {
        caller_bounds: [
            Binder(
                OutlivesPredicate(
                    '_#0r,
                    '_#1r
                )
            )
        ],
        reveal: UserFacing,
        def_id: None
    },
    value: usize
}
```
But this can't really exist? Ohhh, you need to convert it to a `RevealAll` `ParamEnv` and *then* call `.and(ty)` on it, to pass it to `layout_of`. That will clear all the irrelevant bounds!

File: src/librustc/ty/sty.rs [hunk 3]
```diff
@@ -2154,30 +2154,26 @@ impl<'tcx> Const<'tcx> {
...
-            tcx
-                .lift_to_global(&ty)
-                .unwrap_or_else(|| bug!("cannot lift {:#?} for {:#?}", ty, self))
-        } else {
-            let ty = tcx
-                .lift_to_global(&ty.value)
-                .unwrap_or_else(|| bug!("cannot lift {:#?} for {:#?}", ty, self));
-            ParamEnv::empty().and(ty)
-        };
+        // if `ty` has no unresolved components, use an empty param_env
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: I don't think this comment is accurate.
But I'd defer to @nikomatsakis. What I think ParamEnv::add does today is throw away the bounds if the value doesn't refer to any of the generic parameters in scope.
So less unresolved and more "generic".

File: src/librustc/ty/sty.rs [hunk 4]
```diff
@@ -2154,30 +2154,26 @@ impl<'tcx> Const<'tcx> {
...
+        let ty = tcx.lift_to_global(&param_env.with_reveal_all().and(ty)).unwrap();
         let size = tcx.layout_of(ty).ok()?.size;
         match self.val {
             ConstValue::Unevaluated(did, substs) => {
-                let substs = tcx.lift_to_global(&substs).unwrap();
-                let instance = ty::Instance::resolve(tcx, ty.param_env, did, substs)?;
+                // if `substs` has no unresolved components, use and empty param_env
+                let pem_and_substs = param_env.with_reveal_all().and(substs);
+                let (param_env, substs) = tcx.lift_to_global(&pem_and_substs).unwrap().into_parts();
```
Comment (eddyb) [inline src/librustc/ty/sty.rs]: IMO you should still fail gracefully instead of unwrapping.

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb waiting for your review on this

**Comment by oli-obk** [comment]
Nope, I still have things to address, sorry about that

**Comment by eddyb** [comment]
This is also waiting on @nikomatsakis for a few questions.

**Comment by pnkfelix** [comment]
cc #60471 since this is "related to lazy normalization"

File: src/librustc/ty/sty.rs (hunk 3 above)
Comment (oli-obk) [reply src/librustc/ty/sty.rs]: Yes that looks like what the source does and makes much more sense. I'll adjust the comment accordingly

File: src/test/ui/consts/self_normalization.rs [hunk 5]
```diff
@@ -0,0 +1,16 @@
+// compile-pass
+
+fn testfn(_arr: &mut [();0]) {}
```
Comment (Centril) [inline src/test/ui/consts/self_normalization.rs]:
```suggestion
fn testfn(_arr: &mut [(); 0]) {}
```

File: src/librustc/ty/sty.rs (hunk 4 above)
Comment (oli-obk) [reply src/librustc/ty/sty.rs]: Won't that just shift the problem to the user of `try_eval_bits` and make it much harder to debug what's wrong?

**Comment by oli-obk** [comment]
@nikomatsakis this is ready for review again.

The big question related to lazy normalization is whether it's ok that this moves evaluation of constants to the point where someone is trying to act upon the actual value of the constant, instead of trying to do this proactively in https://github.com/rust-lang/rust/blob/999c1fc2819e34539706b193711735d997633ef1/src/librustc/traits/project.rs#L401 and https://github.com/rust-lang/rust/blob/5cd28066214a4a255bac6655c20bf05cb95730fd/src/librustc/traits/query/normalize.rs#L191

**Comment by eddyb** [comment]
@oli-obk I would expect that for now eager normalization would still resolve *at least* everything which evaluates successfully, right?
I mean, that is the case for associated type projections, I don't see why consts would be different.

**Comment by Dylan-DPC** [comment]
ping from triage @oli-obk @eddyb what's the update on this?

**Comment by nikomatsakis** [comment]
r=me but @eddyb had some nits

r? @eddyb

**Comment by ProgrammaticNajel** [comment]
Ping from triage, @eddyb @Centril any updates on this? Thanks

File: src/librustc/ty/sty.rs (hunk 4 above)
Comment (oli-obk) [reply src/librustc/ty/sty.rs]: Resolved by getting rid of the lift entirely
