### PR TITLE
Fix `bump-stage0` build failure, and check-build `bump-stage0` in CI

### LINKED ISSUE #146252: Check `src/tools/bump-stage0` at least check-builds
cf. [#t-release > Bump stage0 rustfmt separately ("one-off") @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/Bump.20stage0.20rustfmt.20separately.20.28.22one-off.22.29/near/537916615)

### PR DESCRIPTION
**Pull request by jieyouxu**
This PR bumps the `toml` dependency of the `bump-stage0` tool to `0.8.23`, which AFAICT is the highest `toml` version that's present in the r-l/r workspace's `Cargo.lock` already (so we don't introduce _another_ `toml 0.x.*` series). I added some byte-buffer-to-string intermediary to workaround `toml 0.8.*` not having the `toml 0.9.*` `toml::from_slice` API.

To catch obvious build failures of the `src/tools/bump-stage0` tool early, before we find out it can't even build when we really need it to work.

Contexts:

- https://github.com/rust-lang/rust/pull/146250#issue-3388327410
- [#t-release > Bump stage0 rustfmt separately ("one-off") @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/Bump.20stage0.20rustfmt.20separately.20.28.22one-off.22.29/near/537916615)

Fixes rust-lang/rust#146252.

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/check.rs [hunk 1]
```diff
@@ -839,3 +839,9 @@ tool_check_step!(Linkchecker {
     mode: |_builder| Mode::ToolBootstrap,
     default: false
 });
+
+tool_check_step!(BumpStage0 {
+    path: "src/tools/bump-stage0",
+    mode: |_builder| Mode::ToolBootstrap,
+    default: false
```
Comment (Kobzol) [inline src/bootstrap/src/core/build_steps/check.rs:846]: It would be nice to have the option to check these tools by default on CI, so that we don't have to enumerate them manually in CI scripts.

**Review by Kobzol — COMMENTED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/146263/397f93362974d298b79e0e0cd43677014aa7b722..7b9980236cc8c32fa1ae5ce6886163a9d7f9ee16)*

**Comment by Kobzol** [comment]
Ah lol, I thought it was fixed already :D Sorry.

**Comment by Kobzol** [comment]
Looks fine. You can r=me once CI is green.
