### PR TITLE
Don't suggest adding the unexpected cfgs to the build-script it-self

### LINKED ISSUE #125368: New nightly feature "rustc-check-cfg" doesn't work as advertised by warning hint (cannot dismiss warning)
EDIT: Prefixing this bug with a better explanation now that I understand better: You can register a custom cfg with `rustc-check-cfg` in two ways, with a printf in build.rs or a `[lint]` in cargo.toml. However if your custom cfg is referenced *in build.rs itself*, the printf method does not work (you will get the warning anyway). Worse, the warning triggered by your cfg in build.rs will recommend suppressing itself by adding the printf, even though (currently?) that printf will be ineffective.

---

There is a very new (last 2 weeks) Nightly feature which protects against typos in cfg()s by warning if an unexpected cfg is found, comparing against a list of known Rust cfgs. That's useful, but what if your project legitimately uses a cfg that the Rust project did not forsee? According to a new compiler hint added along with this feature, you can register a custom cfg in build.rs with, for example:

```
    println!("cargo::rustc-check-cfg=cfg(exe)");
```

In my configuration, this "registration" println does not do anything.

### Repro

Clone this project (branch `z_bug_exe_warning`), then run `git submodule update --recursive --init`:

https://github.com/mcclure/pocket-riscv-rs-bug/tree/z_bug_exe_warning

Build with `make` or `cargo +nightly build  --release` (the former invokes the latter). You will see four instances of this warning:

```
warning: unexpected `cfg` condition name: `exe`
 --> src/rkyv_types.rs:4:11
  |
4 | #[cfg(not(exe))]
  |           ^^^
  |
  = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, `windows`
  = help: consider using a Cargo feature instead or adding `println!("cargo::rustc-check-cfg=cfg(exe)");` to the top of the `build.rs`
  = note: see <https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
```

(Aside: In my tests, build warnings in this project are always printed three times, once with ANSI coloring and twice without, so you'll actually see 12 of this warning, but that's outside the scope of this bug and I think it's my fault).

Context: This project builds a video game for an unusual (and low-horsepower) embedded system (hence the submodule). I don't want large support libraries like PNG decoders on the device, so I preprocess large assets such as images in build.rs and serialize them using [rkyv](https://github.com/rkyv/rkyv). This means I have a file, `rkyv_types.rs`, which contains the serialized types, and this file is included in both build.rs and the final program. So that this file can work properly in both environments, I put this in my `build.rs`:

```
    // Set this in the app build; if it's not present, we can assume we're in the build.
    println!("cargo:rustc-cfg=exe");
```

So this means I can use `cfg(exe)` to verify I'm in the built program and `cfg(not(exe))` to verify I'm in build.rs. This `exe` is the cfg `rustc-check-cfg` warns about. Fair enough, let's notify `rustc-check-cfg` of this custom cfg so we don't get the warning. At the top of build.rs main() is this line; uncomment it:

```
    println!("cargo:rustc-check-cfg=cfg(exe)");
```

(This is of course the action recommended by the hint in the warning.) Now re-run the build with `make`. You will see… the exact same four errors.

The rustc-check-cfg printout does nothing.

### Analysis

* I have not experimented with disabling the warning with `#[warn(unexpected_cfgs)]`. The warning seems good because it catches typos. I just don't want to be warned about `exe` because it's not a typo.
* In the repro I use the single colon version of `rustc-check-cfg`, because that feature only works when Rust MSRV is above 1.77, and requiring Rust 1.80 in order to banish a warning that didn't exist before Rust 1.80 seems silly. However, I did test with double colon and it didn't behave any different.
* It seems to me that since the file is included in both build.rs and the built program, even if `rustc-check-cfg` suppressed the warnings about the surplus `exe` config in the program I might still wind up facing warnings about `exe` *in the build.rs*, since the println has not run at the time the build.rs is built. However I don't think this is the problem above, because in that case I would have expected the number of warnings to *halve* on adding the suppression line, not stay the same.
* In case you were wondering, yes I see the warning both on `exe` and `not(exe)`.

### Meta

```
$ cargo +nightly --version
cargo 1.80.0-nightly (0de7f2ec6 2024-05-17)
$ uname -a
Linux Anthy 6.5.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

### PR DESCRIPTION
**Pull request by Urgau**
This PR adds a check to avoid suggesting to add the unexpected cfgs inside the build-script when building the build-script it-self, as it won't have any effect, since build-scripts applies to their descended target.

Fixes #125368

### CODE REVIEW

File: compiler/rustc_lint/src/context/diagnostics/check_cfg.rs [hunk 1]
```diff
@@ -42,6 +42,25 @@ fn to_check_cfg_arg(name: Symbol, value: Option<Symbol>, quotes: EscapeQuotes) -
     }
 }
 
+fn cargo_help_sub(inst: &impl Fn(EscapeQuotes) -> String) -> lints::UnexpectedCfgCargoHelp {
+    // We don't want to suggest the `build.rs` way to expected cfgs if we are already in a
+    // `build.rs`. We therefor do a best effort check to try to figure out if we are building a
+    // Cargo build script.
+    //
+    // Ideally we would check the crate name via `TyCtxt::crate_name`, but this isn't available
```
Comment (bjorn3) [inline compiler/rustc_lint/src/context/diagnostics/check_cfg.rs:50]: With access to the session you can check for the `--crate-name` argument, right? `tcx.crate_name()` additionally looks for `#![crate_name]`, but as cargo unconditionally passes `--crate-name`, any `#![crate_name]` has to match `--crate-name`, so ignoring `#![crate_name]` here is fine.

Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics/check_cfg.rs:50]: I didn't think of that, this could indeed use `sess.options.crate_name` and since this code is already behind [`was_invoked_from_cargo`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/utils/fn.was_invoked_from_cargo.html) we don't need to use the env verify if are actually coming from Cargo or not since it's already done.

Comment (Urgau) [reply compiler/rustc_lint/src/context/diagnostics/check_cfg.rs]: Done, thanks.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @Urgau!

@bors r+ rollup
