### PR TITLE
Test that opaque types can't have themselves as a hidden type with incompatible lifetimes

### LINKED ISSUE #122876: TAITs with different args incorrectly assumed to be equal
The following should not compile. Adapted from #115017.
```rust
#![feature(type_alias_impl_trait)]

type Opaque<'a> = impl Sized;

fn get_one<'a>(a: *mut &'a str) -> Opaque<'a> {
    a
}

fn get_iter<'a>() -> impl IntoIterator<Item = Opaque<'a>> {
    None::<Opaque<'static>>
}
```

This is a quick issue, I did not have the chance to look into it deeper but I guess it affects ATPIT as well.
cc @compiler-errors @oli-obk

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #122876

This PR used to add extra logic to prevent those cases, but after https://github.com/rust-lang/rust/pull/113169 this is implicitly rejected, because such usages are not defining.

### CODE REVIEW

File: tests/ui/type-alias-impl-trait/different_args_considered_equal3.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+//! Test that we don't allow coercing an opaque type with a static
+//! lifetime to a free version of itself. While this kind of
+//! conversion is fine for rigid types, the hidden type behind an opaque
+//! type may
```
Comment (compiler-errors) [inline tests/ui/type-alias-impl-trait/different_args_considered_equal3.rs:4]: this comment is incomplete? :thinking:

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
pls fix test comment then r=me

**Comment by compiler-errors** [comment]
@rustbot author

(so it is out of my review queue hehe)
