### PR TITLE
Fix index-page generation

### LINKED ISSUE #60096: rustdoc `--enable-index-page` broken
The index page that is printed out when using the `--enable-index-page` looks broken. This is using the development version of 1.34.

There is just a bunch of junk, and links to crates are missing:
Screenshot from 2019-04-18 14-47-59

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #60096.

The minifier was minifying crates name in `searchIndex` key position, which was a bit problematic for multiple reasons.

r? @rust-lang/rustdoc

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
This one is quite a huge issue so it'd be nice to have it reviewed as soon as possible. :-/

r? @Manishearth

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -1340,10 +1340,15 @@ fn write_minify_replacer<W: Write>(
...
                     tokens.apply(|f| {
                         // We add a backline after the newly created variables.
-                        minifier::js::aggregate_strings_into_array_with_separation(
+                        minifier::js::aggregate_strings_into_array_with_separation_filter(
                             f,
                             "R",
                             Token::Char(ReservedChar::Backline),
+                            |tokens, pos| {
+                                pos < 2 ||
+                                !tokens[pos - 1].is_char(ReservedChar::OpenBracket) ||
```
Comment (Manishearth) [inline src/librustdoc/html/render.rs]: please leave a comment here explaining why this is necessary

**Comment by ollie27** [comment]
At the very least this needs a test.

**Comment by GuillaumeGomez** [comment]
@ollie27 To test it, we need two things:

1. A test to check output JS (which must work, whatever the minification used)
2. To compile multiple crates at once since this bug only occurs at this time.

I can do it, but considering the amount of code necessary, this promise to be complicated to maintain...

**Comment by ollie27** [comment]
Changing `src/test/rustdoc/index-page.rs` to:

```rust
// aux-build:all-item-types.rs
// build-aux-docs
// compile-flags: -Z unstable-options --enable-index-page

#![crate_name = "foo"]

// @has foo/../index.html
// @has - '//span[@class="in-band"]' 'List of all crates'
// @has - '//ul[@class="mod"]//a[@href="foo/index.html"]' 'foo'
// @has - '//ul[@class="mod"]//a[@href="all_item_types/index.html"]' 'all_item_types'
pub struct Foo;
```

is enough to test for #60096.

Also now that crate names are no longer minified this code should be removed: https://github.com/rust-lang/rust/blob/bfb443eb1de484fde141fa9090a9f4291cbe60a5/src/librustdoc/html/render.rs#L967-L987

**Comment by GuillaumeGomez** [comment]
@ollie27: Good catch! Completely forgot about this part...

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/html/render.rs [hunk 2]
```diff
@@ -1340,10 +1315,17 @@ fn write_minify_replacer<W: Write>(
                         .into();
                     tokens.apply(|f| {
                         // We add a backline after the newly created variables.
-                        minifier::js::aggregate_strings_into_array_with_separation(
+                        minifier::js::aggregate_strings_into_array_with_separation_filter(
                             f,
                             "R",
                             Token::Char(ReservedChar::Backline),
+                            // This closure prevents crates' name to be aggregated. It allows to not
```
Comment (Manishearth) [inline src/librustdoc/html/render.rs]: "This closure prevents crates' names from being aggregated."

I'm not sure what the second sentence means. And this doesn't explain how the OpenBracket or searchIndex check work.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs]: > I'm not sure what the second sentence means. And this doesn't explain how the OpenBracket or searchIndex check work.

Ah? I'll reword it then...

**Comment by GuillaumeGomez** [comment]
@Manishearth Are the explanations more clear this way or is there something else I need to clarify?

**Comment by Manishearth** [comment]
@bors r+

thanks!
