### PR TITLE
Don't recommend const fns on a stable build without a note about nightlies

### LINKED ISSUE #28490: E0015 "function calls in statics" recommends using constant functions in stable even though constant functions are not stable
Using rustc 1.3.0 (9a92aaf19 2015-09-15)

```rust
struct Foo { a: u8 }
fn bar() -> Foo {
    Foo { a: 5 }
}

static foo: Foo = bar();

fn main() {}
```
```
> rustc test.rs
test.rs:6:19: 6:24 error: function calls in statics are limited to constant functions, struct and enum constructors [E0015]
test.rs:6 static foo: Foo = bar();
                            ^~~~~
test.rs:6:19: 6:24 help: run `rustc --explain E0015` to see a detailed explanation
```
```
> rustc --explain E0015
The only functions that can be called in static or constant expressions are
`const` functions. Rust currently does not support more general compile-time
function execution.

See [RFC 911] for more details on the design of `const fn`s.

[RFC 911]: https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md
```
Apply suggestion and make `bar` a `const fn`:
```rust
struct Foo { a: u8 }
const fn bar() -> Foo {
    Foo { a: 5 }
}

static foo: Foo = bar();

fn main() {}
```
yields
```
> rustc test.rs
test.rs:2:1: 4:2 error: const fn is unstable
test.rs:2 const fn bar() -> Foo {
test.rs:3     Foo { a: 5 }
test.rs:4 }
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #28490

cc #24111

### CODE REVIEW

File: src/librustc/middle/check_const.rs [hunk 1]
```diff
@@ -709,10 +710,21 @@ fn check_expr<'a, 'tcx>(v: &mut CheckCrateVisitor<'a, 'tcx>,
...
-                              "function calls in {}s are limited to \
-                               constant functions, \
-                               struct and enum constructors", v.msg());
+                    // FIXME(#24111) Remove this check when const fn stabilizes
+                    if v.tcx.sess.opts.unstable_features == UnstableFeatures::Allow {
+                        span_err!(v.tcx.sess, e.span, E0015,
+                                  "function calls in {}s are limited to \
+                                   struct and enum constructors", v.msg());
+                        v.tcx.sess.span_note(e.span,
+                                             "A limited form of compile-time function \
```
Comment (alexcrichton) [inline src/librustc/middle/check_const.rs]: I believe our error messages and such conventionally start with a lowercase letter

**Comment by alexcrichton** [comment]
Looks like there's a travis failure as well

**Comment by Manishearth** [comment]
Ah, I'd forgotten to push after fixing build errors. Addressed.

File: src/librustc/middle/check_const.rs [hunk 2]
```diff
@@ -709,10 +710,21 @@ fn check_expr<'a, 'tcx>(v: &mut CheckCrateVisitor<'a, 'tcx>,
...
+                                  "function calls in {}s are limited to \
+                                   struct and enum constructors", v.msg());
+                        v.tcx.sess.span_note(e.span,
+                                             "a limited form of compile-time function \
+                                              evaluation is available on a nightly \
+                                              compiler via `const fn`");
+                    } else {
+                        span_err!(v.tcx.sess, e.span, E0015,
+                                  "function calls in {}s are limited to \
+                                   constant functions, \
```
Comment (eefriedman) [inline src/librustc/middle/check_const.rs]: Did you intend to mention "constant functions" on stable Rust?

Comment (Manishearth) [inline src/librustc/middle/check_const.rs]: Yes, I did. That's why I mention that "it is available on nightlies".

I'm okay with suggesting unstable features on a stable compiler, as long as it is mentioned that they are only available on nightlies (so that the user can evaluate switching to a nightly if constfn was indeed what they wanted). I want to avoid the bad UX of "compiler suggests thing, try thing, thing doesn't work because stable".

Comment (Manishearth) [inline src/librustc/middle/check_const.rs]: Oh, I see what you mean. Fixed.
