### PR TITLE
rustdoc: fix href of extern crates in search results

### LINKED ISSUE #148300: Renamed extern crates generated wrong href in search results
The following code:

```rust
pub extern crate std as st2;
```

Will generate this `href` in the search result: `../st2/index.html`. Which is wrong, it should be `std`.

### PR DESCRIPTION
**Pull request by lolbinarycat**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/154697)*

To avoid modifying the search index, I instead overloaded an existing field that is always unused for extern crate items.

fixes rust-lang/rust#148300

r? @GuillaumeGomez

### CODE REVIEW

File: src/librustdoc/html/render/search_index.rs [hunk 1]
```diff
@@ -1537,6 +1542,15 @@ pub(crate) fn build_index(
                         > 1
                 {
                     Some(render::get_id_for_impl(tcx, ItemId::DefId(impl_id)))
+                } else if item.ty == ItemType::ExternCrate
+                    && let Some(def_id) = item.defid
+                    && let Some(local_def_id) = def_id.as_local()
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/search_index.rs]:
```suggestion
                    && let Some(local_def_id) = item.defid.and_then(|def_id| def_id.as_local())
```

One less binding. :)

File: src/librustdoc/html/render/search_index.rs [hunk 2]
```diff
@@ -1537,6 +1542,15 @@ pub(crate) fn build_index(
...
+                    && let cnum = tcx.extern_mod_stmt_cnum(local_def_id).unwrap_or(LOCAL_CRATE)
+                    && let Some(ExternalLocation::Remote { url, is_absolute }) =
+                        cache.extern_locations.get(&cnum)
+                    && *is_absolute
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/search_index.rs:1550]: You should move this check first since it's a simpler boolean check, much faster than all the other checks.

File: tests/rustdoc-js/import-filter.js [hunk 3]
```diff
@@ -6,15 +6,21 @@ const EXPECTED = [
         'query': 'import:st',
         'others': [
             { 'path': 'foo', 'name': 'st', 'href': '../foo/index.html#reexport.st' },
-            // FIXME: `href` is wrong: <https://github.com/rust-lang/rust/issues/148300>
-            { 'path': 'foo', 'name': 'st2', 'href': '../st2/index.html' },
+            {
+                'path': 'foo',
+                'name': 'st2',
+                'href': 'https://doc.rust-lang.org/nightly/std/index.html'
```
Comment (GuillaumeGomez) [inline tests/rustdoc-js/import-filter.js]: We need to replace `nightly` with `toolchain` otherwise it'll fail on beta and stable.

File: tests/rustdoc-js/import-filter.js [hunk 4]
```diff
@@ -6,15 +6,21 @@ const EXPECTED = [
         'query': 'import:st',
         'others': [
             { 'path': 'foo', 'name': 'st', 'href': '../foo/index.html#reexport.st' },
-            // FIXME: `href` is wrong: <https://github.com/rust-lang/rust/issues/148300>
-            { 'path': 'foo', 'name': 'st2', 'href': '../st2/index.html' },
+            {
```
Comment (GuillaumeGomez) [inline tests/rustdoc-js/import-filter.js:9]: Please add a code comment here to mention what we're testing. Which made me realize that we should maybe have a proper test file for this test.

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]

File: src/librustdoc/html/render/search_index.rs (hunk 2 above)
Comment (lolbinarycat) [reply src/librustdoc/html/render/search_index.rs:1550]: I think you might want to look at the code a bit closer, `is_absolute` is just bound, so we can't move it back any.

File: tests/rustdoc-js/import-filter.js (hunk 3 above)
Comment (lolbinarycat) [reply tests/rustdoc-js/import-filter.js]: Right... I don't know how to do that.

Comment (GuillaumeGomez) [reply tests/rustdoc-js/import-filter.js]: I can do that once you're done with your changes, so if a similar change is needed in the future, you know where to look. Does it sounds good to you?

File: tests/rustdoc-js/import-filter.js (hunk 4 above)
Comment (lolbinarycat) [reply tests/rustdoc-js/import-filter.js:9]: I actually initially wrote a standalone test for this, but ended up removing it once I found this test.

File: src/librustdoc/html/render/search_index.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/search_index.rs:1550]: Oh you're right, missed that binding. My bad!

File: tests/rustdoc-js/import-filter.js (hunk 4 above)
Comment (GuillaumeGomez) [reply tests/rustdoc-js/import-filter.js:9]: As you prefer. But if we keep it as is, we might want to rename the file and its top code comment.

File: tests/rustdoc-js/import-filter.js (hunk 3 above)
Comment (lolbinarycat) [reply tests/rustdoc-js/import-filter.js]: Sure? I'm a bit confused by the fact that there is no mention of the string "toolchain" in [the docs for the `rustdoc-js` test suite](https://rustc-dev-guide.rust-lang.org/rustdoc-internals/search.html#testing-the-search-engine), nor in *any  of the rustdoc tests*.

Comment (GuillaumeGomez) [reply tests/rustdoc-js/import-filter.js]: My bad, it's "channel".

**Comment by GuillaumeGomez** [comment]
That was what I planned to do. :)

**Review by GuillaumeGomez — APPROVED** [review]
