### PR TITLE
Document breaking out of a named code block

### LINKED ISSUE #110758: Incorrect / incomplete information about where you can break with a value
### Location

https://doc.rust-lang.org/std/keyword.break.html

### Summary

The documentation states that "When associated with loop, a break expression may be used to return a value from that loop. This is only valid with loop and not with any other type of loop. If no value is specified, break; returns (). Every break within a loop must return the same type."

"This is only valid with loop" is not true, as one can break with a value from within a non-loop block expression.

## Example:
```rust

let final_value = 'outer: {
    let value: Option<Value> = get_value();
    'inner: {
        if let Some(value) = value { break 'outer value; }
    }
    // do stuff here maybe
};

```
Whilst I admit the example I provide seems a little contrived, I use this practice myself.

For context, the technical reason why you can't break from say a while or for loop is because those loops are expected to yield the `()` type.

I believe that this part of the documentation should be amended/elaborated on as I find this pattern useful and practical for writing readable code.

### PR DESCRIPTION
**Pull request by ktnlvr**
Closes #110758.

### CODE REVIEW

File: library/std/src/keyword_docs.rs [hunk 1]
```diff
@@ -109,6 +109,33 @@ mod as_keyword {}
 /// println!("{result}");
 /// ```
 ///
+/// It is also possible to exit from any *labelled* block returning the value early.
+/// If no value specified `break;` returns `()`.
```
Comment (workingjubilee) [inline library/std/src/keyword_docs.rs:113]: Odd stutter here. I think it should be "If no value *is specified for*" or "*is given to*", then "it returns `()`".

**Review by workingjubilee — CHANGES_REQUESTED** [review]
Seems mostly fine, one detail.

File: library/std/src/keyword_docs.rs (hunk 1 above)
Comment (ktnlvr) [reply library/std/src/keyword_docs.rs:113]: This is a verbatim restatement of a sentence from the previous paragraph:
> This is only valid with `loop` and not with any other type of loop.
> If no value is specified, `break;` returns `()`. 

> It is also possible to exit from any *labelled* block returning the value early.
>  If no value specified `break;` returns `()`.

Does a comma suffice or should the text above be rephrased too?

Comment (workingjubilee) [reply library/std/src/keyword_docs.rs:113]: The comma is the minimum for it to be valid, as far as I can tell. I do not think it is sufficient for it to be very comprehensible. So if you wish to revise both cases to be consistent, that is fine with me.

**Comment by workingjubilee** [comment]
Thanks!

@bors r+ rollup
