### PR TITLE
run alloc benchmarks in Miri and fix UB

### LINKED ISSUE #104096: VecDeque benchmarks have UB
This benchmark function has UB:

https://github.com/rust-lang/rust/blob/bc3fae4dc1891de19368622d7b77ba3006b8f4ea/library/alloc/src/collections/vec_deque/tests.rs#L29-L40

It directly accesses private fields of `VecDeque` to set the head and tail pointers, but doesn't initialize the element in the middle so `pop_back` reads uninitialized memory.

### PR DESCRIPTION
**Pull request by RalfJung**
Miri since recently has a "fake monotonic clock" that works even with isolation. Its measurements are not very meaningful but it means we can run these benches and check them for UB.

And that's a good thing since there was UB here: fixes https://github.com/rust-lang/rust/issues/104096.

r? @thomcc

### CODE REVIEW

File: library/alloc/src/collections/vec_deque/tests.rs [hunk 1]
```diff
@@ -65,23 +66,26 @@ fn bench_retain_odd_10000(b: &mut test::Bencher) {
...
 
 #[bench]
-#[cfg_attr(miri, ignore)] // isolated Miri does not support benchmarks
 fn bench_pop_front_100(b: &mut test::Bencher) {
-    let mut deq = VecDeque::<i32>::with_capacity(101);
+    let size = 100;
+    let mut deq = VecDeque::<i32>::with_capacity(size + 1);
+    // We'll mess with private state to pretend like `deq` is filled.
+    // Make sure the buffer is initialized so that we don't read uninit memory.
+    unsafe { deq.ptr().write_bytes(0u8, size + 1) };
```
Comment (thomcc) [inline library/alloc/src/collections/vec_deque/tests.rs:85]: 🙀

**Review by thomcc — APPROVED** [review]
Mildly cursed but it's inside unit-~~tests~~benches so, fine.

File: library/alloc/src/collections/vec_deque/tests.rs (hunk 1 above)
Comment (RalfJung) [reply library/alloc/src/collections/vec_deque/tests.rs:85]: Not more cursed than just setting the `head` and `tail` fields without doing this...

I considered creating a filled `VecDeque` from an array, but that seems to me like it'd make even more assumptions about internal implementation details...
