### PR TITLE
Fix uplifting in `Assemble` step

### LINKED ISSUE #145534: nightly cross build started failing 2025-08-16
### Summary

I have a GitHub Actions workflow that cross-builds a nightly rust toolchain from x86_64-pc-windows-gnu to x86_64-pc-cygwin.  On 2025-08-16, this started failing.

### Command used

```sh
  PKG_CONFIG_SYSROOT_DIR="$(cygpath -w /)" \
  PKG_CONFIG="$(cygpath -w /usr/bin/pkgconf.exe)" \
  LIBGIT2_NO_VENDOR=1 \
  OPENSSL_DIR="$(cygpath -w /usr)" \
  OPENSSL_LIB_DIR="$(cygpath -w /usr/lib)" \
  OPENSSL_STATIC=0 \
  DESTDIR="$(cygpath -w "$PWD/build-Cygwin/dest-rust")" \
  python x.py install --stage 2
```

### Expected behaviour

successful build, as on 2025-08-15 and before

### Actual behaviour

```
Uplifting rustc (stage2 -> stage3)
ERROR: Unable to find the stamp file D:\cygwin\home\runneradmin\rustc-nightly-src\build-Cygwin\x86_64-pc-cygwin\stage3-rustc\x86_64-pc-cygwin\release\.librustc-stamp, did you try to keep a nonexistent build stage?
Build completed unsuccessfully in 1:21:24
```

### Bootstrap configuration (bootstrap.toml)
```toml
# see src/bootstrap/defaults/
profile = "dist"

# see src/bootstrap/src/utils/change_tracker.rs
change-id = 138986

[build]
submodules = false
build = "x86_64-pc-windows-gnu"
host = ["x86_64-pc-cygwin"]
target = [
  "x86_64-pc-cygwin",
]
build-dir = "build-Cygwin"
python = "$MSYS2_ROOT/mingw64/bin/python.exe"
locked-deps = true
vendor = true
tools = [
"clippy", "rustdoc", "rustfmt", "rust-analyzer-proc-macro-srv", "analysis",
  "cargo",
]
profiler = true
docs = false

[install]
prefix = "/usr"
sysconfdir = "/etc"

[llvm]
link-shared = true

[rust]
codegen-units-std = 1
channel = "stable"
rpath = false
frame-pointers = true
llvm-bitcode-linker = false
lld = false
llvm-tools = false
codegen-tests = false
deny-warnings = false
backtrace-on-ice = true
control-flow-guard = true
lto = "thin"

[dist]
compression-formats = ["gz"]
compression-profile = "fast"
include-mingw-linker = false

[target.x86_64-pc-windows-gnu]
cc = "$MSYS2_ROOT/mingw64/bin/clang.exe"
cxx = "$MSYS2_ROOT/mingw64/bin/clang++.exe"
ar = "$MSYS2_ROOT/mingw64/bin/llvm-ar.exe"
ranlib = "$MSYS2_ROOT/mingw64/bin/llvm-ranlib.exe"
linker = "$MSYS2_ROOT/mingw64/bin/clang.exe"
llvm-config = "$MSYS2_ROOT/mingw64/bin/llvm-config.exe"
crt-static = true

[target.x86_64-pc-cygwin]
cc = "$WORKSPACE/gcc.exe"
cxx = "$WORKSPACE/g++.exe"
ar = "$WORKSPACE/ar.exe"
ranlib = "$WORKSPACE/ranlib.exe"
linker = "$WORKSPACE/x86_64-pc-cygwin-gcc.exe"
llvm-config = "$WORKSPACE/llvm-config.exe"
profiler = false
```

### Operating system

windows-latest

### HEAD

https://static.rust-lang.org/dist/2025-08-16/rustc-nightly-src.tar.xz

### Additional context

https://github.com/jeremyd2019/cygwin-rust-bootstrap/actions/runs/17007568309/job/48225722817 - all the scripts and configs are in that repository.

<details><summary>Build Log</summary>
<p>

too long to paste, see https://github.com/jeremyd2019/cygwin-rust-bootstrap/actions/runs/17007568309/job/48225722817

</p>
</details>

### PR DESCRIPTION
**Pull request by Kobzol**
In https://github.com/rust-lang/rust/pull/145310, I removed [this line](https://github.com/rust-lang/rust/pull/145310/files#diff-5a1e05f2688d271039171a547d407d0c8a96715ee64d35562fc76b4c9a874303L2109), which adjusted the stage of the build compiler if an uplift has happened. This broke stage3+ uplifted rustc builds (https://github.com/rust-lang/rust/issues/145534). I could swear I tested this in the PR, but somehow I missed it.

Instead of keeping the original returned stage, I made it more explicit by returning the actually used `build_compiler` from the `Rustc` step, and then use that in the `Assemble` step.

The changes to `RustcLink` were needed to fix `ui-fulldeps`, which apparently build a stage3 rustc, because I haven't fixed the test steps yet :sweat_smile:

Hopefully we might be able to remove `RustcLink` if the approach from https://github.com/rust-lang/rust/pull/144252 will work.

Should fix https://github.com/rust-lang/rust/issues/145534.

r? @jieyouxu

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 1]
```diff
@@ -1441,31 +1462,51 @@ fn rustc_llvm_env(builder: &Builder<'_>, cargo: &mut Cargo, target: TargetSelect
     }
 }
 
-/// `RustcLink` copies all of the rlibs from the rustc build into the previous stage's sysroot.
+/// `RustcLink` copies compiler rlibs from a rustc build into a compiler sysroot.
+/// It works with (potentially up to) three compilers:
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/compile.rs:1466]: Remark: 😰

File: src/bootstrap/src/core/build_steps/compile.rs [hunk 2]
```diff
@@ -1441,31 +1462,51 @@ fn rustc_llvm_env(builder: &Builder<'_>, cargo: &mut Cargo, target: TargetSelect
...
 struct RustcLink {
-    /// The compiler whose rlibs we are copying around.
-    pub compiler: Compiler,
-    /// This is the compiler into whose sysroot we want to copy the rlibs into.
-    pub previous_stage_compiler: Compiler,
-    pub target: TargetSelection,
+    /// This compiler **built** some rustc, whose rlibs we will copy into a sysroot.
+    build_compiler: Compiler,
+    /// This is the compiler into whose sysroot we want to copy the built rlibs into.
+    /// In most cases, it will correspond to `build_compiler`.
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/compile.rs]: Nit:

```suggestion
    /// This is the compiler whose sysroot we want to copy the built rlibs into.
    /// In most cases, it will correspond to `build_compiler`.
```

**Review by jieyouxu — APPROVED** [review]
This was not obvious 😭 Thanks, r=me after comment fix.
