### PR TITLE
bootstrap: build bootstrap docs with in-tree rustdoc

### LINKED ISSUE #147142: Searching nightly-rustc docs is broken: "Unhandled Promise Rejection: Error: not a roaring bitmap: 101"
- https://doc.rust-lang.org/nightly/nightly-rustc/?search=TyCtxt

Searching nightly-rustc docs currently produces no results, and spins forever.

In my browser's dev console, I see this error:

- Unhandled Promise Rejection: Error: not a roaring bitmap: 101

### PR DESCRIPTION
**Pull request by notriddle**
All of the docs need to be built with the same rustdoc. Otherwise, any change to the search index breaks everything, because the two rustdocs don't agree on the format.

Fixes https://github.com/rust-lang/rust/issues/147142

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/doc.rs [hunk 1]
```diff
@@ -1024,10 +1024,6 @@ macro_rules! tool_doc {
                         run.builder.ensure(Rustc::from_build_compiler(run.builder, compilers.build_compiler(), target));
                         compilers.build_compiler()
                     }
-                    Mode::ToolBootstrap => {
-                        // bootstrap/host tools should be documented with the stage 0 compiler
```
Comment (RalfJung) [inline src/bootstrap/src/core/build_steps/doc.rs:1028]: Maybe have a comment somewhere emphasizing that everything needs to be documented with the same rustdoc?

Comment (Kobzol) [reply src/bootstrap/src/core/build_steps/doc.rs:1028]: That's not 100% true. For local usage, you can document them with whatever you want, you only need the same rustdoc when you dist everything together and ship it as a single docs directory.

**Comment by Mark-Simulacrum** [comment]
Is there some way for bootstrap or rustdoc to notice (perhaps in the dist artifacts?) that we used two different versions and bail out? Maybe when we produce the rustc and std doc components we could run such a check?
