### PR TITLE
check array type of repeat exprs is wf

### LINKED ISSUE #111091: array repeat exprs do not check the array type is well formed
I tried this code:

```rust
trait Foo {
    const ASSOC: [u8];
}

fn bar<T: Foo>() {
    let a = [T::ASSOC; 2];
}

fn main() {}
```

I expected to see this happen: It should not compile as the local variable `a` has type `[[u8]; 2]` which is not well formed

Instead, this happened: it compiled :grimacing: 

### Meta
`playground version`:
```
Nightly channel

Build using the Nightly version: 1.71.0-nightly

(2023-04-30 9ecda8de85ce893cc3fc)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by BoxyUwU**
Fixes #111091

Also makes sure that we actually renumber regions in the length of repeat exprs which we previously weren't doing and would cause ICEs in `adt_const_params` + `generic_const_exprs` from attempting to prove the wf goals when the length was an unevaluated constant with `'erased` in the `ty` field of `Const` 

The duplicate errors are caused by the fact that `const_arg_to_const`/`array_len_to_const` in `FnCtxt` adds a `WellFormed` goal for the created `Const` which is also checked by the added `WellFormed(array_ty)`. I don't want to change this to just emit a `T: Sized` goal for the element type since that would ignore `ConstArgHasType` wf requirements and generally uncomfortable with the idea of trying to sync up `wf::obligations` for arrays and the code in hir typeck for repeat exprs.

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

File: compiler/rustc_middle/src/mir/visit.rs [hunk 1]
```diff
@@ -192,6 +192,15 @@ macro_rules! make_mir_visitor {
                 self.super_constant(constant, location);
             }
 
+            #[allow(rustc::pass_by_value)]
```
Comment (lcnr) [inline compiler/rustc_middle/src/mir/visit.rs:195]: please don't use this, use `$(& $mutability)?` instead.

**Comment by lcnr** [comment]
@bors r-

in case the rollup goes through, please open a followup pr
