### PR TITLE
Point at individual type args on arg count mismatch

### LINKED ISSUE #55991: Invalid span of a struct's generics in presence of a where clause but no parameter
This is an issue that was reported initially to `rustfmt` in https://github.com/rust-lang-nursery/rustfmt/issues/3194.
The problematic code was based on the `Generics.span` field, which gave a wrong `BytePos` in case of a `struct` with a `where` clause but no parameter.

# Problem

Below is an explanation of the problem, and there is a runnable example below to test it out.

## Observed

With the code `mod m { struct S where A: B; }`, the field `generics.span` of the `struct` item is equal to  `Span { lo: BytePos(0), hi: BytePos(0), .. }`; this points to the _start_ of the input.

## Expected

The `span` value should point to the position just after the struct ident, i.e.,  `Span { lo: BytePos(16), hi: BytePos(16), .. }`.

# Versions

```
$ rustc --version --verbose
rustc 1.32.0-nightly (6f93e93af 2018-11-14)
binary: rustc
commit-hash: 6f93e93af6f823948cc13d2938957757c6486d88
commit-date: 2018-11-14
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0
```

# Example code

- tested with `rustc-ap-syntax = "297.0.0"`

```rust
extern crate syntax;

use syntax::ast::*;
use syntax::ext::quote::rt::FileName;
use syntax::parse;
use syntax::parse::ParseSess;
use syntax::source_map::FilePathMapping;

fn main() {
    // With source = "mod m { struct S<A> where A: B; }":
    // - the generics span is equal to `Span { lo: BytePos(16), hi: BytePos(19), .. }`
    //
    // With source = "mod m { struct S where A: B; }":
    // - the generics span is equal to `Span { lo: BytePos(0), hi: BytePos(0), .. }`
    // - it would be better if the span pointed to the portion just after the ident with the difference between `hi` and `lo` equal to 0, i.e., `Span { lo: BytePos(16), hi: BytePos(16), .. }`

    //let source = "mod m { struct S<A> where A: B; }";
    let source = "mod m { struct S where A: B; }";

    let session = ParseSess::new(FilePathMapping::empty());
    let file_name = FileName::Custom("source".to_string());

    syntax::with_globals(|| {
        let mut parser = parse::new_parser_from_source_str(&session, file_name, source.to_string());
        let result = parser.parse_crate_mod().unwrap();
        let item = &result.module.items[0];
        if let ItemKind::Mod(module) = &item.node {
            let item = &module.items[0];
            if let ItemKind::Struct(_data, generics) = &item.node {
                println!("generics.span = [{:?}]", generics.span);
                println!("generics.params = [{:?}]", generics.params.len());
            }
        }
    });
}
```

### PR DESCRIPTION
**Pull request by estebank**
- Point at individual type arguments on arg count mismatch
- Make generics always have a valid span, even when there are no args
- Explain that `impl Trait` introduces an implicit type argument

Fix #55991.

### CODE REVIEW

File: src/librustc_typeck/check/compare_method.rs [hunk 1]
```diff
@@ -600,17 +600,42 @@ fn compare_number_of_generics<'a, 'tcx>(
...
+            ) = if let Some(trait_hir_id) = tcx.hir().as_local_hir_id(trait_.def_id) {
+                let trait_item = tcx.hir().expect_trait_item(trait_hir_id);
+                if trait_item.generics.params.is_empty() {
+                    (Some(vec![trait_item.generics.span]), vec![])
+                } else {
+                    let arg_spans: Vec<Span> = trait_item.generics.params.iter()
+                        .map(|p| p.span)
+                        .collect();
+                    let impl_trait_spans: Vec<Span> = trait_item.generics.params.iter()
+                        .filter_map(|p| if !trait_item.generics.span.overlaps(p.span) {
```
Comment (varkor) [inline src/librustc_typeck/check/compare_method.rs]: Since this is specifically about `impl Trait`, I think it would be more meaningful to check for `GenericParamKind::Type { synthetic: SyntheticTyParamKind::ImplTrait }` here.

File: src/librustc_typeck/check/compare_method.rs [hunk 2]
```diff
@@ -600,17 +600,42 @@ fn compare_number_of_generics<'a, 'tcx>(
...
+                }
             } else {
-                impl_item.generics.span
+                (trait_span.map(|s| vec![s]), vec![])
             };
 
+            let impl_hir_id = tcx.hir().as_local_hir_id(impl_.def_id).unwrap();
+            let impl_item = tcx.hir().expect_impl_item(impl_hir_id);
+            let impl_item_impl_trait_spans: Vec<Span> = impl_item.generics.params.iter()
+                .filter_map(|p| if !impl_item.generics.span.overlaps(p.span) {
```
Comment (varkor) [inline src/librustc_typeck/check/compare_method.rs]: And here.

**Comment by varkor** [comment]
r=me with the nits fixed.
