### PR TITLE
tyencode: Make sure that projection bounds are handled in stable order.

### LINKED ISSUE #34796: undefined reference link error regression
This looks to be a regression from stable to beta unfortunately, compiling https://github.com/alexcrichton/futures-rs/commit/6ae0345ee0b2abc558b0d916fc17dbd46caa7969 succeeds on stable but fails on beta:

```
$ rustup run stable cargo build --manifest-path http/Cargo.toml
...
$ rustup run beta cargo build --manifest-path http/Cargo.toml
...
   Compiling http v0.1.0 (file:///home/alex/code/futures/http)
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/alex/code/futures/http/target/debug/http.0.o" "-o" "/home/alex/code/futures/http/target/debug/http" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/alex/code/futures/http/target/debug" "-L" "/home/alex/code/futures/http/target/debug/deps" "-L" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/alex/code/futures/http/target/debug/libhttp.rlib" "/home/alex/code/futures/http/target/debug/deps/libhttparse-36b96d90ffbce562.rlib" "/home/alex/code/futures/http/target/debug/deps/libfuturemio-986c91cdeb491b00.rlib" "/home/alex/code/futures/http/target/debug/deps/libslab-45f4a226259c4869.rlib" "/home/alex/code/futures/http/target/debug/deps/libfutures-1a55edc1e7c129de.rlib" "/home/alex/code/futures/http/target/debug/deps/libmio-a89f84904d772c54.rlib" "/home/alex/code/futures/http/target/debug/deps/libnet2-b2390925f9bbf4a2.rlib" "/home/alex/code/futures/http/target/debug/deps/libcfg_if-72c1f992b13d5087.rlib" "/home/alex/code/futures/http/target/debug/deps/libmiow-b827bf6129dcd844.rlib" "/home/alex/code/futures/http/target/debug/deps/libwinapi-0889532d327ff4e2.rlib" "/home/alex/code/futures/http/target/debug/deps/libnix-f8d033ce6354dacb.rlib" "/home/alex/code/futures/http/target/debug/deps/libbytes-f9fbfc75eb2416e0.rlib" "/home/alex/code/futures/http/target/debug/deps/libscoped_tls-53036341d2dbbe26.rlib" "/home/alex/code/futures/http/target/debug/deps/libtime-750bfdd52feafcb7.rlib" "/home/alex/code/futures/http/target/debug/deps/liblibc-1f3392fe1afd1313.rlib" "/home/alex/code/futures/http/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/home/alex/code/futures/http/target/debug/deps/libbitflags-e61ad67c3301e77d.rlib" "/home/alex/code/futures/http/target/debug/deps/libslab-4f8b9e9b6e35857c.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-411fd48b.rlib" "/home/alex/.multirust/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-411fd48b.rlib" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
note: /home/alex/code/futures/http/target/debug/http.0.o: In function `http::serve<http::request::Request,http::response::Response,closure>':
/home/alex/code/futures/http/src/lib.rs:55: undefined reference to `futuremio::tcp::_$LT$impl$u20$futuremio..event_loop..LoopHandle$GT$::tcp_listen::h9a7258751896fb30'
/home/alex/code/futures/http/target/debug/http.0.o: In function `http::serve::_$u7b$$u7b$closure$u7d$$u7d$::hed42a806f41e1837':
http.0.rs:(.text._ZN4http5serve28_$u7b$$u7b$closure$u7d$$u7d$17hed42a806f41e1837E+0xa2): undefined reference to `futuremio::tcp::TcpListener::incoming::h7aae24690b0d3a8d'
/home/alex/code/futures/http/target/debug/http.0.o: In function `futures::forget::forget<futures::then::Then<Box<Future>, core::result::Result<(), std::sync::mpsc::SendError<core::result::Result<(), std::io::error::Error>>>, closure>>':
/home/alex/code/futures/src/forget.rs:23: undefined reference to `futures::forget::_forget::h4301ad1ba69f01dc'
collect2: error: ld returned 1 exit status


error: aborting due to previous error
error: Could not compile `http`.
```

cc @michaelwoerister, does this look familiar?

I'll try to reduce down as well, but wanted to file an issue nonetheless.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Fixes #34796.

r? @alexcrichton

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc @eddyb

**Comment by alexcrichton** [comment]
triage: beta-nominated

File: src/librustc_metadata/tyencode.rs [hunk 1]
```diff
@@ -407,7 +407,14 @@ pub fn enc_existential_bounds<'a,'tcx>(w: &mut Cursor<Vec<u8>>,
 
     enc_region(w, cx, bs.region_bound);
 
-    for tp in &bs.projection_bounds {
+    // Encode projection_bounds in a stable order
+    let mut projection_bounds: Vec<_> = bs.projection_bounds
+                                          .iter()
+                                          .map(|b| (b.item_name().as_str(), b))
+                                          .collect();
+    projection_bounds.sort_by_key(|&(ref name, _)| name.clone());
```
Comment (aravind-pg) [inline src/librustc_metadata/tyencode.rs]: Newbie question (and total nit): why couldn't this basically be the following (or something close to it)?
```rust
let mut projection_bounds = bs.projection_bounds
                              .clone()
                              .sort_by_key(|&b| b.item_name().as_str());
```

Because then it seems we'd be able to keep the next line just `for tp in &projection_bounds { ... }`, avoiding the extra call to `map`.

And even if we didn't do this the next line still seems like it could stay `for tp in &projection_bounds` with `s/tp.0/tp.1.0` in the loop body.

Comment (michaelwoerister) [inline src/librustc_metadata/tyencode.rs]: Since sort_by_key() returns nothing, projection_bounds with be the unit value `()`. It would have to look at least like:
```rust
let mut projection_bounds = bs.projection_bounds.clone();
projection_bounds.sort_by_key(|&b| b.item_name().as_str());
```

And why didn't I do it like the above? In order to avoid that `b.item_name().as_str()` gets called more than once per item. Although, I somehow mistakenly assumed that `b.item_name().as_str()` would need to hash the string each time when looking it up in the interner, which it doesn't, so this "optimization" is even more premature than I thought `:)`

So, your version, when fixed as indicated, would actually be nicer than mine.

Comment (aravind-pg) [inline src/librustc_metadata/tyencode.rs]: Ahh, because `sort_by_key` would make basically O(n log n) calls to its closure, i.e. to `b.item_name().as_str()`? Makes much more sense now (notwithstanding the question of whether it's a premature optimization :). And yeah I overlooked the fact that `sort_by_key` returns unit, so your fix makes sense. Thanks for the explanation! Up to you what changes you want to make, if any.

**Comment by alexcrichton** [comment]
@bors: p=1

(fixing a regression0
