### PR TITLE
Remove blanket silencing of "type annotation needed" errors

### LINKED ISSUE #64084: cargo test gives up compiling after one error
I'm making a big refactor. When attempting to clean up my tests, `cargo test` appears to go file by file, alphabetically when compiling the tests. As soon as one `#[test]` has a compile error, the build is aborted.

- `#[test]`s following the failure do not get compiled.
- Subsequent compile errors in the `#[test]` that fails to build are not reported.

This makes finding errors very tedious.

---

Editing to provide concrete case:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c040edc58966f3fcc662002e84ec57aa gives up after the first test but should continue to report errors

### PR DESCRIPTION
**Pull request by estebank**
Remove blanket check for existence of other errors before emitting "type annotation needed" errors, and add some eager checks to avoid adding obligations when they refer to types that reference `[type error]` in order to reduce unneeded errors.

Fix #64084.

### CODE REVIEW

File: src/librustc/infer/opaque_types/mod.rs [hunk 1]
```diff
@@ -1155,6 +1157,15 @@ impl<'a, 'tcx> Instantiator<'a, 'tcx> {
         );
         debug!("instantiate_opaque_types: ty_var={:?}", ty_var);
 
+        for predicate in &bounds.predicates {
```
Comment (Centril) [inline src/librustc/infer/opaque_types/mod.rs]: We could make a method returning `-> bool` here and use `if stuff.obligation_references_error() { return ty_var; }` here.

Comment (estebank) [reply src/librustc/infer/opaque_types/mod.rs]: I didn't want to hide the `O(n)` behavior of the added code so that I could maybe nerd-snipe someone to point me a place where we could do the same with no added time ^_^

Comment (Centril) [reply src/librustc/infer/opaque_types/mod.rs]: Can't you just leave a doc comment about the `O(n)` complexity? This is in diagnostics code anyways so what does `O(n)` matter?

Comment (estebank) [reply src/librustc/infer/opaque_types/mod.rs]: Because it it needs to go over the predicates vec twice instead of once for _every_ case. This is to add the obligations, which may or may not be met.
