### PR TITLE
const fn stability checking: also check declared language features

### LINKED ISSUE #129656: A const-unstable function cannot call other const-unstable functions gated under a language feature gate
I expected this code to compile, but it does not:
```rust
#![feature(staged_api, f128)]
#![stable(feature = "rust_test", since = "1.0.0")]

#[unstable(feature = "f128", issue = "42")]
#[rustc_const_unstable(feature = "f128", issue = "42")]
const fn my_fun() {}

#[unstable(feature = "f128", issue = "42")]
#[rustc_const_unstable(feature = "f128", issue = "42")]
const fn my_fun2() {
    my_fun()
}
```
Renaming `f128` to `f128_const` makes it compile, so somehow the issue must be related to the fact that `f128` is a language feature gate. For regular library stability, we support also using a language feature as a library feature gate, but for const-stability that somehow does not work.

When this gets fixed, the f128_const and f16_const features (added in https://github.com/rust-lang/rust/pull/129555) can be merged into the f128 and f16 features, respectively.

Cc @oli-obk

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/129656

@oli-obk I assume it is just an oversight that this didn't use `features().declared()`? Or is there a deep reason that this must only check `declared_lib_features`?

### CODE REVIEW

**Comment by fee1-dead** [comment]
The only reason I could think of is that we might allow `rustc_const_unstable` under a lang feature, but the lang feature is already accepted. So when someone tries to call that const function in const contexts, it would suggest them to enable the feature, but when they enable the feature they'd see a warning that it is already stable?

oli is on leave, so maybe we can get more eyes on this from someone more familiar with stability checking

**Comment by RalfJung** [comment]
> The only reason I could think of is that we might allow rustc_const_unstable under a lang feature, but the lang feature is already accepted. So when someone tries to call that const function in const contexts, it would suggest them to enable the feature, but when they enable the feature they'd see a warning that it is already stable?

That would equally apply to regular stability, not just const stability, right?
We might want to reject `unstable`/`rustc_const_unstable` with an already-stable (or removed) language feature. But that's a separate question.

**Comment by RalfJung** [comment]
The status quo is that the example in https://github.com/rust-lang/rust/issues/129656 suggests to enable the `f128` feature gate which is already enabled. So that's clearly worse than what you describe. ;)

File: tests/ui/consts/min_const_fn/const-fn-lang-feature.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//! Ensure that we can use a language feature with a `const fn` and things behave as expected.
```
Comment (oli-obk) [inline tests/ui/consts/min_const_fn/const-fn-lang-feature.rs:1]: Explain what "expected" means in detail.

**Review by oli-obk — COMMENTED** [review]
I can't make any statements about the current or expected behavior around (const) stability without putting more thought and time into it than I am currently able to

File: tests/ui/consts/min_const_fn/const-fn-lang-feature.rs (hunk 1 above)
Comment (RalfJung) [reply tests/ui/consts/min_const_fn/const-fn-lang-feature.rs:1]: Well, it should work like all feature gates work -- if you enable the feature gate it is actually considered enabled...

**Comment by RalfJung** [comment]
To me this looks like a fairly simple oversight -- the code does `tcx.features().declared_lib_features.iter().any(...)` to check whether a feature gate is enabled, but everywhere else in the compiler we use `tcx.features().declared(...)` to do that check.

**Comment by fee1-dead** [comment]
> We might want to reject `unstable`/`rustc_const_unstable` with an already-stable (or removed) language feature. But that's a separate question.

Let's add that as a test. If this isn't rejected, we should open an issue to track fixing it for both `unstable` and `rustc_const_unstable`. If the case for `unstable` is already fixed but not `rustc_const_unstable`, I'd want this PR to have that fixed also.

> The status quo is that the example in #129656 suggests to enable the `f128` feature gate which is already enabled. So that's clearly worse than what you describe. ;)

Well, that requires someone who enables the `staged_api` feature to specify a lang feature with `rustc_const_unstable`. It's bad, but I think there's not a lot urgency for making it possible.. Even if the PR using `f128_const` lands first, we can also just rename the feature afterwards.

**Comment by RalfJung** [comment]
> I think there's not a lot urgency

I didn't say that this fix is more urgent than a regular PR. It's just a normal bugfix. :)

> Let's add that as a test. If this isn't rejected, we should open an issue to track fixing it for both unstable and rustc_const_unstable. If the case for unstable is already fixed but not rustc_const_unstable, I'd want this PR to have that fixed also.

This is completely orthogonal to the issue this PR is concerned with. Please don't ask the PR to be extended in scope to fix unrelated issues.

I created an issue to track this: https://github.com/rust-lang/rust/issues/129814.

**Comment by fee1-dead** [comment]
> > Let's add that as a test. If this isn't rejected, we should open an issue to track fixing it for both unstable and rustc_const_unstable. If the case for unstable is already fixed but not rustc_const_unstable, I'd want this PR to have that fixed also.
> 
> This is completely orthogonal to the issue this PR is concerned with. Please don't ask the PR to be extended in scope to fix unrelated issues.

Maybe I should be the person opening that issue.. I shouldn't be asking for more work when it isn't necessary. Sorry if that nudge was annoying!

On another look, I think there is no deep reason - probably an oversight as you said, so let's merge it.

@bors r+ rollup

**Comment by fee1-dead** [comment]
The actually reason that this used `declared_lib_features` instead of `.declared` is probably that we just didn't consider the potential use for specifying a lang feature in `rustc_const_unstable`. I guess I was trying too hard to find any deep reasons for this.
