### PR TITLE
[breaking change] Disallow statics initializing themselves

### LINKED ISSUE #71078: `static FOO:Foo=FOO;` doesn't cause cycle error for zero-sized-type with no public constructor.
I tried this code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b8f15edf4886c9c8bb753636feb70ec2
```rust
pub mod foo {
    #[derive(Debug, Copy, Clone)]
    pub struct Foo {
        x: (),
    }
}

pub static FOO: foo::Foo = FOO;

fn main() {
    dbg!(FOO);
}
```

I expected the code to fail to compile with a cycle error.

Instead, it compiled and ran,printing the value of `FOO` .

### Meta

I was able to verify that this bug happens for the 1.42.0 stable, 1.43-beta.5, and 1.44.0-nightly(2020-04-11 e82734e56b2a50d38e09) versions.

Trying this code in rust.godbolt.org it errors up to 1.36.0,and doesn't error anymore from 1.37.0 onwards.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #71078

Self-initialization is unsound because it breaks privacy assumptions that unsafe code can make. In

```rust
pub mod foo {
    #[derive(Debug, Copy, Clone)]
    pub struct Foo {
        x: (),
    }
}

pub static FOO: foo::Foo = FOO;
```

unsafe could could expect that ony functions inside the `foo` module were able to create a value of type `Foo`.

### CODE REVIEW

**Comment by oli-obk** [comment]
@craterbot check-only

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
@craterbot check

**Comment by Centril** [comment]
@craterbot check

**Comment by mati865** [comment]
All regressions and fixes are spurious.

**Comment by oli-obk** [comment]
@rust-lang/lang I would like to perform a soundness fixing breaking change. Namely I want to forbid ZST statics from initializing themselves by value. This allows one to create a ZST that has private fields and can usually only be initialized via functions from the same module as the ZST. Since the user can reasonably expect these private parts to be private, self-initialization violates that expectation, breaking assumptions in unsafe code.

There were no crater regressions, and I find it highly unlikely that anyone is using this for purposes other than breaking our privacy rules in private code.

**Comment by Mark-Simulacrum** [comment]
This has been broken since 1.37 according to the issue. I agree with @oli-obk though that it seems pretty unlikely that there are real use cases for this.

It also feels a static ZST isn't really useful, right?

With my release team hat on, I'd say we can go ahead here. Given the crater run I'm even comfortable with doing so without a warning period, though it'd be good to land it ASAP so that we get the full 12 weeks in nightly before it hits stable.

**Comment by nikomatsakis** [comment]
I feel comfortable making this change as a soundness fix. I am quite surprised that it works as is, and I definitely think this was not really intended. Given that a crater run was done with no regressions, I think "just land it" (which is permitted per the [compiler team policy](https://rustc-dev-guide.rust-lang.org/bug-fix-procedure.html) on these kinds of changes).

File: src/librustc_mir/interpret/operand.rs [hunk 1]
```diff
@@ -234,6 +234,12 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         {
             Some(ptr) => ptr,
             None => {
+                if let Scalar::Ptr(ptr) = mplace.ptr {
+                    // If the ZST pointer has provenance, we may be reading from a static.
+                    // In order to ensure that `static FOO: Type = FOO;` causes a cycle, we need to
+                    // trigger a read here.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/operand.rs:240]: Why do this here and not centrally in `Memory::check_ptr_access`?

File: src/librustc_mir/interpret/operand.rs [hunk 2]
```diff
@@ -242,13 +248,11 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
             }
         };
 
+        let alloc = self.memory.get_raw(ptr.alloc_id)?;
```
Comment (RalfJung) [inline src/librustc_mir/interpret/operand.rs:251]: This is just a no-behavioral-change optimization, right?

File: src/test/ui/consts/recursive-zst-static.rs [hunk 3]
```diff
@@ -1,6 +1,4 @@
-// build-pass
-
-static FOO: () = FOO;
+static FOO: () = FOO; //~ cycle detected when const-evaluating `FOO`
```
Comment (RalfJung) [inline src/test/ui/consts/recursive-zst-static.rs:1]: Please add a comment explaining why this failure is important, linking to the issue this fixes.

File: src/librustc_mir/interpret/operand.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs:251]: Ah yes, initially I thought I could merge it with the above `get_raw` call, I'll pull it out into a separate commit

Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs:251]: Oh :laughing: it is already a separate commit

File: src/librustc_mir/interpret/operand.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs:240]: Because that function doesn't actually do any reads so far in order to prevent other kind of cycles. I'm not sure whether any of the call sites need this.

File: src/test/ui/consts/recursive-zst-static.rs (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/consts/recursive-zst-static.rs:7]: done

File: src/librustc_mir/interpret/operand.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: Moving the check worked.

File: src/librustc_mir/interpret/memory.rs [hunk 4]
```diff
@@ -400,7 +400,14 @@ impl<'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'mir, 'tcx, M> {
 
                 // We can still be zero-sized in this branch, in which case we have to
                 // return `None`.
-                if size.bytes() == 0 { None } else { Some(ptr) }
+                if size.bytes() == 0 {
+                    // We may be reading from a static.
+                    // In order to ensure that `static FOO: Type = FOO;` causes a cycle error
+                    // instead of magically pulling *any* ZST value from the ether, we need to
+                    // trigger a read here.
```
Comment (RalfJung) [inline src/librustc_mir/interpret/memory.rs:407]:
```suggestion
                    // actually access the referenced allocation. The caller is likely to
                    // short-circuit on `None`, so we trigger the access here to make
                    // sure it happens.
```

**Comment by RalfJung** [comment]
r=me with comment nit fixed

**Comment by oli-obk** [comment]
ran rustfmt

@bors r=RalfJung

**Comment by oli-obk** [comment]
ran rustfmt

@bors r=RalfJung

File: src/librustc_mir/interpret/operand.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operand.rs]: So, moving this has started to cause problems, because validation goes through the `check_ptr_access` without actually doing a read (https://github.com/rust-lang/rust/issues/71612#issuecomment-622390064) and because const prop now creates references to foreign statics that later code ICEs on https://github.com/rust-lang/rust/issues/71709#issuecomment-622121249
