### PR TITLE
Fix bad span for explicit lifetime suggestions

### LINKED ISSUE #121267: The output help is incorrect, lifetime appears in an unexpected position
### Code

```Rust
fn main() {}

fn foo(src: &crate::Foo) -> Option<i32> {
    todo!()
}
fn bar(src: &crate::Foo) -> impl Iterator<Item = i32> {
    [0].into_iter()
        .filter_map(|_| foo(src))
}

struct Foo<'a>(&'a str);
```

### Current output

```Shell
Checking test1 v0.1.0 (/home/lrne/Project/Rust/test1)
error[E0700]: hidden type for `impl Iterator<Item = i32>` captures lifetime that does not appear in bounds
 --> src/main.rs:7:5
  |
6 |   fn bar(src: &crate::Foo) -> impl Iterator<Item = i32> {
  |                ----------     ------------------------- opaque type defined here
  |                |
  |                hidden type `FilterMap<std::array::IntoIter<i32, 1>, {closure@src/main.rs:8:21: 8:24}>` captures the anonymous lifetime defined here
7 | /     [0].into_iter()
8 | |         .filter_map(|_| foo(src))
  | |_________________________________^
  |
help: to declare that `impl Iterator<Item = i32>` captures `'_`, you can introduce a named lifetime parameter `'a`
  |
6 | fn bar<'a>(src: &'a crate::'a) -> impl Iterator<Item = i32> + 'a  {
  |       ++++       ++        ~~                               ++++

For more information about this error, try `rustc --explain E0700`.
error: could not compile `test1` (bin "test1") due to 1 previous error
```

### Desired output

```Shell
Checking test1 v0.1.0 (/home/lrne/Project/Rust/test1)
error[E0700]: hidden type for `impl Iterator<Item = i32>` captures lifetime that does not appear in bounds
 --> src/main.rs:7:5
  |
6 |   fn bar(src: &crate::Foo) -> impl Iterator<Item = i32> {
  |                ----------     ------------------------- opaque type defined here
  |                |
  |                hidden type `FilterMap<std::array::IntoIter<i32, 1>, {closure@src/main.rs:8:21: 8:24}>` captures the anonymous lifetime defined here
7 | /     [0].into_iter()
8 | |         .filter_map(|_| foo(src))
  | |_________________________________^
  |
help: to declare that `impl Iterator<Item = i32>` captures `'_`, you can introduce a named lifetime parameter `'a`
  |
6 | fn bar<'a>(src: &'a crate::Foo<'a>) -> impl Iterator<Item = i32> + 'a  {
  |       ++++       ++        ~~                               ++++

For more information about this error, try `rustc --explain E0700`.
error: could not compile `test1` (bin "test1") due to 1 previous error
```

### Rationale and extra context

_No response_

### Other cases

```Rust
fn main() {}

fn foo(src: &crate::Foo) -> Option<i32> {
    todo!()
}
fn bar(src: &crate::Foo<'_>) -> impl Iterator<Item = i32> {
    [0].into_iter()
        .filter_map(|_| foo(src))
}

struct Foo<'a>(&'a str);
```

### Rust Version

```Shell
rustc 1.77.0-nightly (bf8716f1c 2023-12-24)
binary: rustc
commit-hash: bf8716f1cd6416266807706bcae0ecb2e51c9d4a
commit-date: 2023-12-24
host: aarch64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #121267

Current explicit lifetime suggestions are not showing correct spans for some lifetimes - e.g. elided lifetime generic parameters;

This should be done correctly regarding elided lifetime kind like the following code

https://github.com/rust-lang/rust/blob/43fdd4916d19f4004e23d422b5547637ad67ab21/compiler/rustc_resolve/src/late/diagnostics.rs#L3015-L3044

### CODE REVIEW

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/static_impl_trait.rs [hunk 1]
```diff
@@ -356,20 +356,87 @@ pub fn suggest_new_region_bound(
...
+                                }
+                            }
+                            finish_bracket(
+                                &mut spans_suggs,
+                                name,
+                                &mut bracket_span,
+                                &mut brackets,
+                            );
+                            spans_suggs
+                        }
```
Comment (TaKO8Ki) [inline compiler/rustc_infer/src/infer/error_reporting/nice_region_error/static_impl_trait.rs:439]: I think it's better to define a new function for these lines since new implementation has many lines. Could you address this?

**Review by TaKO8Ki — COMMENTED** [review]
Sorry for the late review. I left one suggestion.

File: compiler/rustc_infer/src/infer/error_reporting/nice_region_error/static_impl_trait.rs (hunk 1 above)
Comment (ShoyuVanilla) [reply compiler/rustc_infer/src/infer/error_reporting/nice_region_error/static_impl_trait.rs]: Yes, it looked so ugly to me 😅

**Review by estebank — APPROVED** [review]
Please squash your three commits into one.

**Comment by ShoyuVanilla** [comment]
> Please squash your three commits into one.

Thanks! I've squash rebased onto the recent revision 😄
