### PR TITLE
Make associated type bounds in supertrait position implied

### LINKED ISSUE #112568: Bounds on return types in supertraits are not implied
**This is an issue with the unstable `return_type_notation` feature.**

I'm trying to write some code that provides `Send`-able versions of traits that may contain async functions:

```rust
#![feature(
    async_fn_in_trait,
    return_position_impl_trait_in_trait,
    return_type_notation
)]

use tokio::task::{JoinHandle, spawn};

trait Foo {
    async fn bar(&self) -> i32;
}

trait SendFoo: Foo<bar(): Send> + Send {}

fn foobar(foo: impl SendFoo) -> JoinHandle<i32> {
    spawn(async move {
        let future = foo.bar();
        future.await
    })
}
<code>
```

Gives the error:

```
error[E0277]: `impl Future<Output = i32>` cannot be sent between threads safely
  --> src/lib.rs:15:21
   |
15 | fn foobar(foo: impl SendFoo) -> JoinHandle<i32> {
   |                     ^^^^^^^ `impl Future<Output = i32>` cannot be sent between threads safely
   |
   = help: the trait `for<'a> Send` is not implemented for `impl Future<Output = i32>`
note: required by a bound in `SendFoo`
  --> src/lib.rs:13:27
   |
13 | trait SendFoo: Foo<bar(): Send> + Send {}
   |                           ^^^^ required by this bound in `SendFoo`

For more information about this error, try `rustc --explain E0277`.
```

I expected the `SendFoo: Foo<bar(): Send>` bound to mean "anything that implements `SendFoo` also has a `bar()` which implements `Send`" (I think this is implied bounds?). Instead, it appears to function like a where clause on a trait (non-implied). It's acting like I wrote:

```rust
trait SendFoo: Foo + Send
where
    <Self as Foo>::bar(): Send,
{}
```

(note that this syntax is not currently accepted by the compiler, but it gets the point across)

Are these bounds supposed to not be implied? As an aside, the error message here tripped me up for a while too.

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (37998ab50 2023-06-11)
binary: rustc
commit-hash: 37998ab508d5d9fa0d465d7b535dc673087dda8f
commit-date: 2023-06-11
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### LINKED ISSUE #112573: Should associated type bounds on supertraits be implied?
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=937d5a302838df7e7e1fdcf4ddee579a):

```rust
#![feature(associated_type_bounds)]

trait Trait: Super<Assoc: Bound> {}

trait Super {
    type Assoc;
}

trait Bound {}

fn foo<T>(x: T) where T: Trait {}
```

And this happened:

```
error[E0277]: the trait bound `<T as Super>::Assoc: Bound` is not satisfied
  --> src/lib.rs:13:8
   |
13 |     T: Trait,
   |        ^^^^^ the trait `Bound` is not implemented for `<T as Super>::Assoc`
   |
note: required by a bound in `Trait`
  --> src/lib.rs:3:27
   |
3  | trait Trait: Super<Assoc: Bound> {}
   |                           ^^^^^ required by this bound in `Trait`
help: consider further restricting the associated type
   |
13 |     T: Trait, <T as Super>::Assoc: Bound
   |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0277`.
```

I'm not exactly sure whether this should be implied or not! Nominating this for T-lang for discussion, I'd like to know whether this is expected behavior or not.

### Argument for the code failing

For non trait aliases, we don't imply currently any where clauses for non-supertrait bounds. In this case, supertrait bounds are precisely trait and associated type bounds which have `Self` as their self type. Since we can interpret `Self: Super<Assoc: Bound>` as two bounds -- `Self: Super` and `<Self as Super>::Assoc: Bound` -- it's consistent why the latter is not implied.

Fixing this complicates the code even more.

### Argument for the code compiling

The concept of "supertraits" from a language perspective (and not a types perspective) is not very well specified -- one may argue again that it could mean anything that comes after the colon in `trait Trait: ...` or `Self: ...`, for example. Whether or not that's more intuitive, 🤷 

It's also just annoying that this doesn't compile, and who knows if associated type bounds (which I'm personally motivated to compile) becomes more frustrating and/or less useful without these bounds being implied.

---

Related to #112568, which is essentially the same question but for return type notation.

### PR DESCRIPTION
**Pull request by compiler-errors**
`trait A: B<Assoc: C> {}` should be able to imply both `Self: B` and `<Self as B>::Assoc: C`. Adjust the way that we collect implied predicates to do so.

Fixes #112573
Fixes #112568

### CODE REVIEW

**Comment by jackh726** [comment]
I took a look at this briefly at one point. Trying to remember why `trait Trait: Super<Assoc = Bound> {}` is fine but `trait Trait: Super<Assoc: Bound> {}` isn't.

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 1]
```diff
@@ -618,45 +627,28 @@ pub(super) fn implied_predicates_with_filter(
...
+            icx.astconv().compute_bounds(self_param_ty, bounds, OnlySelfBounds(false))
+        }
+        // Should only imply "real" supertraits, i.e. predicates with the self type `Self`.
+        PredicateFilter::SelfOnly => {
+            icx.astconv().compute_bounds(self_param_ty, bounds, OnlySelfBounds(true))
+        }
+        PredicateFilter::SelfThatDefines(assoc_name) => {
+            icx.astconv().compute_bounds_that_match_assoc_item(self_param_ty, bounds, assoc_name)
+        }
     };
```
Comment (jackh726) [inline compiler/rustc_hir_analysis/src/collect/predicates_of.rs:643]: This is getting complex enough that I wonder if we should simplify. Some thoughts:
- Any way we can merge `compute_bounds` and `compute_bounds_that_match_assoc_items`?
- Should `compute_bounds` take a `PredicateFilter`?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs:643]: I think so, passing the whole predicate filter to compute_bounds allows us to merge the two fns. I'll give it a shot.

**Comment by compiler-errors** [comment]
(had to move some code around in the last commit, since astconv was hitting the size limit for a single file)

**Comment by spastorino** [comment]
Looks good to me but given that @jackh726 reviewed it and left comments already, I'd give it up to him.

r? @jackh726
