### PR TITLE
syntax: Use `let _` in #[derive(Debug)]

### LINKED ISSUE #29710: #[derive(Debug)] is triggering the unused_results lint
The following code fails to build on nightly

```rust
#![deny(unused_results)]

#[derive(Debug)]
enum Foo {
    Bar(u32),
}
```
It generates this error:
```
<anon>:3:10: 3:15 error: unused result
<anon>:3 #[derive(Debug)]
                  ^~~~~
<anon>:3:10: 3:15 note: in this expansion of #[derive_Debug] (defined in <anon>)
<anon>:1:9: 1:23 note: lint level defined here
<anon>:1 #![deny(unused_results)]
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This should help avoid triggering the unused_results lint which can frequently
be turned on.

Closes #29710

### CODE REVIEW

File: src/libsyntax/ext/deriving/debug.rs [hunk 1]
```diff
@@ -135,3 +138,19 @@ fn show_substructure(cx: &mut ExtCtxt, span: Span,
     let block = cx.block(span, stmts, Some(expr));
     cx.expr_block(block)
 }
+
+fn stmt_let_undescore(sp: Span, expr: P<ast::Expr>) -> P<ast::Stmt> {
+    let local = P(ast::Local {
```
Comment (sfackler) [inline src/libsyntax/ext/deriving/debug.rs]: Is there not anything on the AstBuilder extension trait that can do this with less manual work?

Comment (alexcrichton) [inline src/libsyntax/ext/deriving/debug.rs]: Ah turns out `pat_wild` exists, but unfortunately it looks like nothing exists for `local` + `decl` + `StmtDecl`
