### PR TITLE
[borrowck] Fix help on mutating &self in async fns

### LINKED ISSUE #93093: Incorrect suggestion when trying to write to an immutable field in an async function
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=df6e36b97b73bd3e3ea0fdfe9325b1c9

```rust
struct S { foo: usize }
impl S {
    async fn bar(&self) {
        self.foo += 1;
    }
}
```

The current output is:

```
error[E0594]: cannot assign to `self.foo`, which is behind a `&` reference
 --> src/lib.rs:4:9
  |
3 |     async fn bar(&self) {
  |                  ----- help: consider changing this to be a mutable reference: `&mut S`
4 |         self.foo += 1;
  |         ^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be written
```

Ideally the output should look like:

```
error[E0594]: cannot assign to `self.foo`, which is behind a `&` reference
 --> src/lib.rs:4:9
  |
3 |     async fn bar(&self) {
  |                  ----- help: consider changing this to be a mutable reference: `&mut self`
4 |         self.foo += 1;
  |         ^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be written
```

`&mut S` is not a valid argument; it needs to be either `&mut self` or `some_name: &mut S`. For some reason this problem only happens when the function is async.

### PR DESCRIPTION
**Pull request by alyssaverkade**
Previously, when rustc was provided an async function that tried to
mutate through a shared reference to an implicit self (as shown in the
ui test), rustc would suggest modifying the parameter signature
to `&mut` + the fully qualified name of the ty (in the case of the repro
`S`). If a user modified their code to match the suggestion, the
compiler would not accept it.

This commit modifies the suggestion so that when rustc is provided the
ui test that is also attached in this commit, it suggests (correctly)
`&mut self`. We try to be careful about distinguishing between implicit
and explicit self annotations, since the latter seem to be handled
correctly already.

This is my first PR here so I'm pretty sure I probably missed something/could use better terminology. I also didn't try to make the match exhaustive since implicit self is the only real special case that I need to handle (that I'm aware of), and I'm pretty sure there's a cleaner way to do this so any advice would be greatly appreciated! (I'm also not terribly confident about how I wrote the ui tests)

here is your cc as requested @compiler-errors

This is an attempt to fix #93093

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs [hunk 1]
```diff
@@ -488,12 +488,32 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
                                     // don't create labels for compiler-generated spans
                                     Some(_) => None,
                                     None => {
-                                        let (span, suggestion) = suggest_ampmut(
-                                            self.infcx.tcx,
-                                            local_decl,
-                                            opt_assignment_rhs_span,
-                                            *opt_ty_info,
-                                        );
+                                        let (span, suggestion) = if name != Symbol::intern("self") {
```
Comment (alyssaverkade) [inline compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:491]: Going to change this to
```suggestion
                                        let (span, suggestion) = if name != kw::SelfLower  {
```

**Comment by alyssaverkade** [comment]
r? rust-lang/compiler

**Comment by jackh726** [comment]
@alyssaverkade in the future, please be patient. Requesting a new reviewer after only a few days generally makes things harder.

**Comment by alyssaverkade** [comment]
Sorry! I had no idea what the norm was and I didn't want to overload you with more things to do

**Review by wesleywiser — APPROVED** [review]
Looks great, thanks for fixing this!
