### PR TITLE
Remove false label when `self` resolve failure does not relate to macro

### LINKED ISSUE #143134: `let self` in method with receiver incorrectly complains about macro hygiene
### Code

```Rust
trait T {
  fn f(self);
}
impl T for () {
  fn f(self) {
      let self = ();
  }
}
```

### Current output

```Shell
error[E0424]: expected unit struct, unit variant or constant, found local variable `self`
 --> src/lib.rs:6:11
  |
5 | /   fn f(self) {
6 | |       let self = ();
  | |           ^^^^ `self` value is a keyword and may not be bound to variables or shadowed
7 | |   }
  | |___- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
```

### Desired output

```Shell
error[E0424]: expected unit struct, unit variant or constant, found local variable `self`
 --> src/lib.rs:6:11
  |
5 |   fn f(self) {
6 |       let self = ();
  |           ^^^^ `self` value is a keyword and may not be bound to variables or shadowed
7 |   }
  |
  |
  help: remove this `let` keyword if you meant to assign to `self`
7 |       let self = ();
  |       ^^^
```

### Rationale and extra context

This code uses absolutely no macros, yet the diagnostic complains about macro hygiene! This seems to have been introduced while fixing #39057

I'm not really sure what's the best diagnostic here. Suggesting to remove the `let` keyword like i did here is probably not the best choice? But at least in the very simple case of `let self =`, it is probably what the user intended. (nevermind that `self` is not `mut`, because if the suggestion is applied, another diagnostic will suggest to add `mut` to the receiver)

Maybe a better diagnostic would briefly explain what is expected on the left-hand-side of an assignment expression where the `self` value is allowed, why it's *not* quite the same as a pattern, and that *this is in fact a pattern* where the `self` value is never allowed, or link to a documentation page explaining the difference.

If the method has no receiver ("Other cases", `T::f()`), then `let self = ();` will instead suggest adding a receiver. This is also wrong, because adding a receiver is *not* a valid fix to the issue (i.e. `self` value is never valid in a pattern).

Maybe the diagnostic in both cases should be identical, and only explain that `self` is not valid in this position, and that it has nothing to do with whether or not the method has a receiver or not?

The diagnostic for `let self = ();` in a toplevel function ("Other cases", `g()`) is already good, and simply states that the function cannot have a `self` receiver.

### Other cases

```Rust
trait T {
    fn f();
}
impl T for () {
    fn f() {
        let self = ();
    }
}

fn g() {
    let self = ();
}
```

### Rust Version

```Shell
rustc 1.90.0-nightly (bdaba05a9 2025-06-27)
binary: rustc
commit-hash: bdaba05a953eb5abeba0011cdda2560d157aed2e
commit-date: 2025-06-27
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes rust-lang/rust#143134 

In the first commit, I did some code-clean, moving `suggest*` to `suggestions/` dir.
In the second, commit, I added ui test.
In the third, I change the code, and present the test result.

r? compiler

### CODE REVIEW

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1186,12 +1186,18 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
...
-            // are resolving came from a different hygiene context.
+            // are resolving came from a different hygiene context or a variable binding.
             if fn_kind.decl().inputs.get(0).is_some_and(|p| p.is_self()) {
-                err.span_label(*span, format!("this function has {self_from_macro}"));
+                if span.from_expansion() {
+                    err.span_label(*fn_span, format!("this function has {self_from_macro}"));
+                } else {
+                    // If the `self` is neither from a macro nor from a function self parameter,
+                    // It is a local variable, we should suggest to rename `self` to `self_`
+                    err.span_help(span, format!("rename `self` to `self_`"));
```
Comment (lcnr) [inline compiler/rustc_resolve/src/late/diagnostics.rs]: this feels like the wrong place to put it :thinking: given the comment

```rust

                    // If the `self` is neither from a macro nor from a function self parameter,
                    // It is a local variable, we should suggest to rename `self` to `self_`
```
I feel like it would be better to put this into the `match source { ... }` above. using `let self` is wrong even if we're not in an associated method or if we're in a macro expansion. I would always emit this diagnostics in the `PathSource::Pat` case and then avoid the rest of this function.

I personally don't think suggestion a rename is too useful, but if you do, please provide it as a `suggestion` instead of a `help`

Comment (xizheyin) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Do you have any suggestions? Renaming can make it compile, but it doesn't necessarily meet the user's intention. There are two possibilities for the user to write like this. One is that he wants to change the value of the self parameter. The other is not knowing that self is a reserved identifier.

If you don't think it's helpful, we can just fix the bug without adding suggestions.🤔

Comment (lcnr) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: yeah, i could imagine either wanting `mut self` or `let self_;` :thinking: I would personally prefer fixing the bug without adding a suggestion

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 2]
```diff
@@ -1183,15 +1183,23 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
...
+        // So, we should return early if we're in a pattern, see issue #143134.
+        if matches!(source, PathSource::Pat) {
+            return true;
+        }
+
         let is_assoc_fn = self.self_type_is_available();
         let self_from_macro = "a `self` parameter, but a macro invocation can only \
                                access identifiers it receives from parameters";
-        if let Some((fn_kind, span)) = &self.diag_metadata.current_function {
+        if let Some((fn_kind, fn_span)) = &self.diag_metadata.current_function {
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1196]: I keep the `fn_span` change because `span` shadow make it confused.

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 3]
```diff
@@ -1183,15 +1183,23 @@ impl<'ast, 'ra, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
                 _ => "`self` value is a keyword only available in methods with a `self` parameter",
             },
         );
+
+        // using `let self` is wrong even if we're not in an associated method or if we're in a macro expansion.
+        // So, we should return early if we're in a pattern, see issue #143134.
+        if matches!(source, PathSource::Pat) {
+            return true;
+        }
+
```
Comment (xizheyin) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1192]: I return early when the source is `Pat`.

File: tests/ui/error-codes/E0424.stderr [hunk 4]
```diff
@@ -40,8 +40,6 @@ LL |     fn qux(&self) {
 error[E0424]: expected unit struct, unit variant or constant, found module `self`
   --> $DIR/E0424.rs:20:9
    |
-LL | fn main () {
-   |    ---- this function can't have a `self` parameter
```
Comment (xizheyin) [inline tests/ui/error-codes/E0424.stderr:44]: It indeed bring some benefits. :)

**Review by xizheyin — COMMENTED** [review]
@rustbot ready

**Comment by lcnr** [comment]
thx

@bors r+ rollup
