### PR TITLE
Fix various ICEs relating to trans'ing fields with associated types 

### LINKED ISSUE #20368: Associated types: ICE "type_of with ty_projection"
After #20307 was merged, I tried using associated types again to improve an API, but ran into an ICE demonstrated by the following example.

    #![feature(associated_types)]

    trait Foo {
      fn foo(&self) -> ();
    }

    trait Bar {
      type F: Foo;
    }

    struct Wat<B: Bar> {
      fs: Vec<B::F>,
    }

    impl<B: Bar> Wat<B> {
      fn new() -> Self {
        Wat { fs: Vec::new() }
      }

      fn wat(&mut self) -> () {
        Foo::foo(&self.fs.pop().unwrap());
      }
    }

    struct FooImpl;

    impl Foo for FooImpl {
      fn foo(&self) -> () {}
    }

    struct BarImpl;

    impl Bar for BarImpl {
      type F = FooImpl;
    }

    fn main() {
      // error is caused by this line.
      let wat: Wat<BarImpl> = Wat::new();
    }

Error:

    error: internal compiler error: type_of with ty_projection
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'Box<Any>', /Users/samuel/Documents/rust/src/libsyntax/diagnostic.rs:182

    stack backtrace:
       1:        0x10b98aa25 - sys::backtrace::write::h79fcf57f48f2accbUpt
       2:        0x10b9af473 - failure::on_fail::he313666202ab06e0wwz
       3:        0x10b9156aa - rt::unwind::begin_unwind_inner::h3818eca49d000e060dz
       4:        0x10988fe47 - rt::unwind::begin_unwind::h2232683046508229913
       5:        0x1098907b8 - diagnostic::Handler::bug::hd878cdd91e904135bVF
       6:        0x108edc1e8 - session::Session::bug::he3e7f8e3682f0beezyp
       7:        0x1084d0001 - trans::type_of::type_of::h9197635c60619429njp
       8:        0x1084d020f - trans::type_of::type_of::h9197635c60619429njp
       9:        0x1085f5c15 - vec::Vec<T>.FromIterator<T>::from_iter::h6585550067129994724
      10:        0x1084d04c3 - trans::type_of::type_of::h9197635c60619429njp
      11:        0x1084cf3ac - trans::type_of::type_of::h9197635c60619429njp
      12:        0x1085f5c15 - vec::Vec<T>.FromIterator<T>::from_iter::h6585550067129994724
      13:        0x1084d04c3 - trans::type_of::type_of::h9197635c60619429njp
      14:        0x1084cf3ac - trans::type_of::type_of::h9197635c60619429njp
      15:        0x1085f5c15 - vec::Vec<T>.FromIterator<T>::from_iter::h6585550067129994724
      16:        0x1084d04c3 - trans::type_of::type_of::h9197635c60619429njp
      17:        0x1084cf3ac - trans::type_of::type_of::h9197635c60619429njp
      18:        0x1084d8eed - trans::base::alloc_ty::h0ff116b4545bfc9eFFt
      19:        0x1085be404 - trans::_match::mk_binding_alloca::h1489438822966140848
      20:        0x1084c99e3 - trans::base::init_local::h78d0086b1f8238539qt
      21:        0x1084cae95 - trans::controlflow::trans_block::h2f26f7b25eb8f55a2ae
      22:        0x1085883a4 - trans::base::trans_closure::hd27e32dcce03144cKju
      23:        0x1084bac1b - trans::base::trans_fn::hb6a8bb6b558798cazuu
      24:        0x1084b6276 - trans::base::trans_item::h823c6709f851fa543Ru
      25:        0x10858f1f8 - trans::base::trans_crate::he3d01922f8b5bab14Ov
      26:        0x1082ebd0e - driver::phase_4_translate_to_llvm::hc27e2b2792fb5383eFa
      27:        0x1082ce0b1 - driver::compile_input::hf6a1e42e515c971bwba
      28:        0x1083ff393 - thunk::F.Invoke<A, R>::invoke::h1106905942537841072
      29:        0x1083fc4f0 - rt::unwind::try::try_fn::h16870325584336102008
      30:        0x10ba19649 - rust_try_inner
      31:        0x10ba19636 - rust_try
      32:        0x1083fcc36 - thunk::F.Invoke<A, R>::invoke::h8218093585600920335
      33:        0x10b99bd84 - sys::thread::thread_start::hccba841055eeb8d6Dfw
      34:     0x7fff8d7932fc - _pthread_body
      35:     0x7fff8d793279 - _pthread_body

### LINKED ISSUE #20470: ICE: Associated types in struct definitions ICE in trans
Somebody is failing to normalize an associated type in trans somewhere.

Test case:

```rust
// Copyright 2014 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#![feature(associated_types)]

trait Test {
    type V;

    fn test(&self, value: &Self::V) -> bool;
}

///////////////////////////////////////////////////////////////////////////

struct TesterPair<T:Test> {
    tester: T,
    value: T::V,
}

impl<T:Test> TesterPair<T> {
    fn new(tester: T, value: T::V) -> TesterPair<T> {
        TesterPair { tester: tester, value: value }
    }

    fn test(&self) -> bool {
        self.tester.test(&self.value)
    }
}

///////////////////////////////////////////////////////////////////////////

struct EqU32(u32);
impl Test for EqU32 {
    type V = u32;

    fn test(&self, value: &u32) -> bool {
        self.0 == *value
    }
}

struct EqI32(i32);
impl Test for EqI32 {
    type V = i32;

    fn test(&self, value: &i32) -> bool {
        self.0 == *value
    }
}

fn main() {
    let tester = TesterPair::new(EqU32(22), 23);
    tester.test();
}
```

Yields:

```
error: internal compiler error: type_of with ty_projection
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/nmatsakis/versioned/rust-2/src/libsyntax/diagnostic.rs:182
```

### LINKED ISSUE #20535: Associated type as struct field causes type-checking error
The following causes an error (indicated in the comment):

```rust
#![feature(associated_types)]

pub trait Foo {
    type Bar;
}

impl Foo for int {
    type Bar = int;
}

struct Thing<F: Foo> {
    a: F,
    b: F::Bar,
}

fn main() {
    let _ = Thing{a: 1i, b: 2i};
    //                      ^~
    // error: mismatched types: expected `<int as Foo>::Bar`,
    // found `int` (expected associated type, found int)
}
```

And this closely related case causes an ICE:

```rust
#![feature(associated_types)]

pub trait Foo {
    type Bar;
}

impl Foo for int {
    type Bar = int;
}

struct Thing<F: Foo> {
    a: F,
    b: Option<F::Bar>,
}

fn main() {
    let _ = Thing{a: 1i, b: None};
}
```

Backtrace:

```
error: internal compiler error: trying to take the sizing type of <int as Foo>::Bar, an unsized type
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:182

stack backtrace:
   1:     0x7f22c6fb32d0 - sys::backtrace::write::h8532e701ef86014f4it
   2:     0x7f22c6fd8b00 - failure::on_fail::h7532e1f79d134d5dzvz
   3:     0x7f22c6f3e1c0 - rt::unwind::begin_unwind_inner::h97b151606151d62deaz
   4:     0x7f22c1defc60 - rt::unwind::begin_unwind::h15809447133099964284
   5:     0x7f22c1df0510 - diagnostic::Handler::bug::h8818b567cf47e6a0DLF
   6:     0x7f22c512acf0 - session::Session::bug::h251da16737c526c0lrq
   7:     0x7f22c5dfd020 - trans::type_of::sizing_type_of::he06887b02c649aebXRo
   8:     0x7f22c5f1cb10 - trans::adt::represent_type_uncached::h6b884b95692379c1oxH
   9:     0x7f22c5df7b30 - trans::adt::represent_type::ha0c2ea2716678100YtH
  10:     0x7f22c5de2fb0 - trans::type_of::type_of::h7caa699265884e0bFYo
  11:     0x7f22c5de2fb0 - trans::type_of::type_of::h7caa699265884e0bFYo
  12:     0x7f22c5f22b20 - vec::Vec<T>.FromIterator<T>::from_iter::h11585473372288691594
  13:     0x7f22c5de2fb0 - trans::type_of::type_of::h7caa699265884e0bFYo
  14:     0x7f22c5de2fb0 - trans::type_of::type_of::h7caa699265884e0bFYo
  15:     0x7f22c5decf50 - trans::base::alloc_ty::h29690970a9e20515oft
  16:     0x7f22c5ee6800 - trans::_match::mk_binding_alloca::h2686137581982254550
  17:     0x7f22c5ddcb70 - trans::base::init_local::h9a5509ab5cb7df8eB1s
  18:     0x7f22c5dddd10 - trans::controlflow::trans_block::hfd89f3a5d0ddcbbdQ1d
  19:     0x7f22c5ea8f60 - trans::base::trans_closure::hbecde8c2bc5f7b2fsSt
  20:     0x7f22c5dc9120 - trans::base::trans_fn::hba312ea6d66cf757Z2t
  21:     0x7f22c5dc4300 - trans::base::trans_item::ha0e598b4af14d13fQpu
  22:     0x7f22c5eb1a60 - trans::base::trans_crate::hf12b6e99a3af9ab9blv
  23:     0x7f22c7513250 - driver::phase_4_translate_to_llvm::h40ce54ee4a878885vFa
  24:     0x7f22c74f2ae0 - driver::compile_input::h68b8602933aad8d7wba
  25:     0x7f22c75bdeb0 - thunk::F.Invoke<A, R>::invoke::h18029802347644288836
  26:     0x7f22c75bcc60 - rt::unwind::try::try_fn::h6518866316425934196
  27:     0x7f22c703f400 - rust_try_inner
  28:     0x7f22c703f3f0 - rust_try
  29:     0x7f22c75bcfb0 - thunk::F.Invoke<A, R>::invoke::h15513809553472565307
  30:     0x7f22c6fc4e40 - sys::thread::thread_start::h5ea7ba97235331d5a9v
  31:     0x7f22c16130c0 - start_thread
  32:     0x7f22c6be4ec9 - __clone
  33:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
There were various parts of trans that were failing to normalize associated types of fields. In addition, the use of `TypeContents` to compute whether something is sized was not able to handle projection types.

Fixes #20470.
Fixes #20368.
Fixes #20535.

r? @nick29581

### CODE REVIEW

**Comment by sfackler** [comment]
Does this close #20368 as well?

**Comment by nikomatsakis** [comment]
@sfackler yes, I just tried it. Test seems too similar to merit being added as a regression test though.

**Comment by nikomatsakis** [comment]
Just pushed one additional commit. This also fixes #20535 now.

File: src/librustc_trans/trans/common.rs [hunk 1]
```diff
@@ -114,23 +114,24 @@ pub fn normalize_ty<'tcx>(cx: &ty::ctxt<'tcx>, ty: Ty<'tcx>) -> Ty<'tcx> {
 }
 
 // Is the type's representation size known at compile time?
-pub fn type_is_sized<'tcx>(cx: &ty::ctxt<'tcx>, ty: Ty<'tcx>) -> bool {
-ty::type_contents(cx, ty).is_sized(cx)
+pub fn type_is_sized<'a,'tcx>(ccx: &CrateContext<'a,'tcx>, ty: Ty<'tcx>) -> bool {
```
Comment (nick29581) [inline src/librustc_trans/trans/common.rs]: Changing this fn and lltype_is_sized to take a CrateCtxt rather than a ty::ctxt seems unnecessary and makes things more complicated.

File: src/librustc_trans/trans/common.rs [hunk 2]
```diff
@@ -235,10 +236,10 @@ let simple = ty::type_is_scalar(ty) ||
     ty::type_is_unique(ty) || ty::type_is_region_ptr(ty) ||
     type_is_newtype_immediate(ccx, ty) ||
     ty::type_is_simd(tcx, ty);
-if simple && !type_is_fat_ptr(tcx, ty) {
+if simple && !type_is_fat_ptr(ccx, ty) {
     return true;
 }
-if !type_is_sized(tcx, ty) {
+if !type_is_sized(ccx, ty) {
```
Comment (nick29581) [inline src/librustc_trans/trans/common.rs]: in fact all the tcx->ccx changes here

**Comment by nick29581** [comment]
r = me with the tcx -> ccx changes reverted
