### PR TITLE
Use object crate for .rustc metadata generation

### LINKED ISSUE #90326: Work around custom section flag regression in LLVM
LLVM 13 has removed support for setting custom section flags in https://reviews.llvm.org/D100944. LLVM 13 carries a revert of the problematic change (https://reviews.llvm.org/D107216). However, LLVM 14 will no longer carry it, and we need to use alternative ways to set custom section flags.

There are currently two places affected by this. The `.llvmbc` bitcode section created in https://github.com/rust-lang/rust/blob/ffba4309241a7a21df4ec7b16f1357cbcd327d6e/compiler/rustc_codegen_llvm/src/back/write.rs#L926 and the `.rustc` metadata section created in https://github.com/rust-lang/rust/blob/612356aa9a0193cb5aee2b668b3893ddf67da2b5/compiler/rustc_codegen_llvm/src/base.rs#L41. In both cases, section flags are used to ensure that the section is not linked into the final binary or loaded into memory.

There are two ways to address this. The first one is to define the section entirely in module-level assembly. Rather than only emitting `.section`, we should also emit `.ascii "ENCODED_SECTION_CONTENTS"`, as well as the symbol name and any other necessary directives (e.g. for visibility). I'm not sure exactly what is needed on different platforms here.

The second one is to use the object crate to create the object file containing the section. The cranelift backend already implements this for the `.rustc` section in https://github.com/rust-lang/rust/blob/ffba4309241a7a21df4ec7b16f1357cbcd327d6e/compiler/rustc_codegen_cranelift/src/metadata.rs#L10. A nice side benefit of this is that the handling would be codegen-backend agnostic and could be shared between the llvm/cranelift/gcc backends.

The suggested course of action is to use the object crate for `.rustc` and inline assembly for `.llvmbc`. The reason for the latter is that the section is part of a larger object file emitted by LLVM, and the `object` crate doesn't seem great for modifying existing object files (as opposed to creating one from scratch). Though if we can use the object crate for everything, that would of course be great.

### PR DESCRIPTION
**Pull request by nikic**
We already use the object crate for generating uncompressed .rmeta
metadata object files. This switches the generation of compressed
.rustc object files to use the object crate as well. These have
slightly different requirements in that .rmeta should be completely
excluded from any final compilation artifacts, while .rustc should
be part of shared objects, but not loaded into memory.

The primary motivation for this change is #90326: In LLVM 14, the
current way of setting section flags (and in particular, preventing
the setting of SHF_ALLOC) will no longer work. There are other ways
we could work around this, but switching to the object crate seems
like the most elegant, as we already use it for .rmeta, and as it
makes this independent of the codegen backend. In particular, we
don't need separate handling in codegen_llvm and codegen_gcc.
codegen_cranelift should be able to reuse the implementation as
well, though I have omitted that here, as it is not based on
codegen_ssa.

This change mostly extracts the existing code for .rmeta handling
to allow using it for .rustc as well, and adjusts the codegen
infrastructure to handle the metadata object file separately: We
no longer create a backend-specific module for it, and directly
produce the compiled module instead.

This does not `fix` #90326 by itself yet, as .llvmbc will need to be
handled separately.

r? @nagisa

### CODE REVIEW

**Comment by nikic** [comment]
I don't get this regression on deep-vector. Compressed metadata is only relevant for dylibs, while this is an executable. The time diff is reported in monomorphization_collector_graph_walk, which doesn't really look related. I'm confused.

**Comment by Mark-Simulacrum** [comment]
It's almost certainly due to https://github.com/rust-lang/rustc-perf/issues/1105, I wouldn't worry about the incr-unchanged regression for deep-vector.

File: compiler/rustc_codegen_ssa/src/back/metadata.rs [hunk 1]
```diff
@@ -83,3 +94,187 @@ fn search_for_metadata<'a>(
...
+    };
+    let binary_format = if sess.target.is_like_osx {
+        BinaryFormat::MachO
+    } else if sess.target.is_like_windows {
+        BinaryFormat::Coff
+    } else {
+        BinaryFormat::Elf
+    };
+
+    let mut file = write::Object::new(binary_format, architecture, endianness);
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/metadata.rs:133]: This should probably get a `file.add_file_symbol(...)` call. In cg_clif I used the cgu name as argument.

**Comment by bjorn3** [comment]
Updated cg_clif in https://github.com/bjorn3/rustc_codegen_cranelift/commit/47962076a1ca95d2527400a6dd57b6c2fc81fafb.
