### PR TITLE
Fix drop-tracking ICE when a struct containing a field with a significant drop is used across an await

### LINKED ISSUE #98476: drop-tracking: ICE when using default struct update syntax
cc https://github.com/rust-lang/rust/issues/97331, @eholk. Minimized from https://crater-reports.s3.amazonaws.com/pr-97334/try%23615edd3ad1cf6871c977dc900317cb6c2070fd6b/gh/AsuMagic.markov-irc/log.txt in the crater run for https://github.com/rust-lang/rust/pull/97334.

### Code

```Rust
fn main() {
    let _ = foo();
}

async fn from_config(_: Config) {}

async fn foo() {
    from_config(Config {
        nickname: None,
        ..Default::default()
    })
    .await;
}

#[derive(Default)]
struct Config {
    nickname: Option<Box<u8>>,
}
```

### Meta

`rustc --version`: 615edd3ad1cf6871c977dc900317cb6c2070fd6b

### Error output

```
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:753:13: Broken MIR: generator contains type Config in MIR, but typeck only knows about {ResumeTy, impl Future<Output = ()>, ()} and []
  --> src/main.rs:7:16
   |
7  |   async fn foo() {
   |  ________________^
8  | |     from_config(Config {
9  | |         nickname: None,
10 | |         ..Default::default()
11 | |     })
12 | |     .await;
13 | | }
   | |_^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/compiler/rustc_errors/src/lib.rs:1274:9
stack backtrace:
   0:     0x7fd66bab8f4d - std::backtrace_rs::backtrace::libunwind::trace::h48663e6e02482f77
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fd66bab8f4d - std::backtrace_rs::backtrace::trace_unsynchronized::hd59d5365552a1436
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd66bab8f4d - std::sys_common::backtrace::_print_fmt::ha78e5f373355cd4a
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fd66bab8f4d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b6548c67a95d5a1
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fd66bb14aac - core::fmt::write::hca7ee89651358f58
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fd66baaa6e1 - std::io::Write::write_fmt::h4bbc99e2a7952e78
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/io/mod.rs:1654:15
   6:     0x7fd66babbc35 - std::sys_common::backtrace::_print::h26a0e5520b381b04
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fd66babbc35 - std::sys_common::backtrace::print::h743a45291d5f39cc
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fd66babbc35 - std::panicking::default_hook::{{closure}}::hf1e2b39dfd75cbc2
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/panicking.rs:295:22
   9:     0x7fd66babb956 - std::panicking::default_hook::h347898a158e52020
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/panicking.rs:314:9
  10:     0x7fd66c282d11 - rustc_driver[2c8e23c1704d1846]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fd66babc30a - std::panicking::rust_panic_with_hook::h3cc7233c1fa5669e
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/panicking.rs:702:17
  12:     0x7fd66c44acf1 - std[23f59d9749713536]::panicking::begin_panic::<rustc_errors[4317dacdbe7ee454]::ExplicitBug>::{closure#0}
  13:     0x7fd66c447296 - std[23f59d9749713536]::sys_common::backtrace::__rust_end_short_backtrace::<std[23f59d9749713536]::panicking::begin_panic<rustc_errors[4317dacdbe7ee454]::ExplicitBug>::{closure#0}, !>
  14:     0x7fd66c45d946 - std[23f59d9749713536]::panicking::begin_panic::<rustc_errors[4317dacdbe7ee454]::ExplicitBug>
  15:     0x7fd66c446546 - std[23f59d9749713536]::panic::panic_any::<rustc_errors[4317dacdbe7ee454]::ExplicitBug>
  16:     0x7fd66c4445a1 - <rustc_errors[4317dacdbe7ee454]::HandlerInner>::span_bug::<rustc_span[e0494e7a78d29b23]::span_encoding::Span, &alloc[444af299f81eecf5]::string::String>
  17:     0x7fd66c4439b0 - <rustc_errors[4317dacdbe7ee454]::Handler>::span_bug::<rustc_span[e0494e7a78d29b23]::span_encoding::Span, &alloc[444af299f81eecf5]::string::String>
  18:     0x7fd66c493fb8 - rustc_middle[8b88f8a0f89f93bb]::ty::context::tls::with_opt::<rustc_middle[8b88f8a0f89f93bb]::util::bug::opt_span_bug_fmt<rustc_span[e0494e7a78d29b23]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7fd66c493b86 - rustc_middle[8b88f8a0f89f93bb]::util::bug::opt_span_bug_fmt::<rustc_span[e0494e7a78d29b23]::span_encoding::Span>
  20:     0x7fd66c493b44 - rustc_middle[8b88f8a0f89f93bb]::util::bug::span_bug_fmt::<rustc_span[e0494e7a78d29b23]::span_encoding::Span>
  21:     0x7fd66d6982aa - <rustc_mir_transform[63cdf027e05c8c75]::generator::StateTransform as rustc_middle[8b88f8a0f89f93bb]::mir::MirPass>::run_pass
  22:     0x7fd66d6894d0 - rustc_mir_transform[63cdf027e05c8c75]::pass_manager::run_passes
  23:     0x7fd66d6ddeed - rustc_mir_transform[63cdf027e05c8c75]::optimized_mir
  24:     0x7fd66e7e44a7 - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt, rustc_span[e0494e7a78d29b23]::def_id::DefId, &rustc_middle[8b88f8a0f89f93bb]::mir::Body>
  25:     0x7fd66dd93b9d - rustc_query_system[8f6ed9285397c37a]::query::plumbing::try_execute_query::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt, rustc_query_system[8f6ed9285397c37a]::query::caches::DefaultCache<rustc_span[e0494e7a78d29b23]::def_id::DefId, &rustc_middle[8b88f8a0f89f93bb]::mir::Body>>
  26:     0x7fd66cc3c837 - rustc_query_system[8f6ed9285397c37a]::query::plumbing::force_query::<rustc_query_impl[362fa764a08dc22]::queries::optimized_mir, rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  27:     0x7fd66ccec7b4 - rustc_query_impl[362fa764a08dc22]::query_callbacks::optimized_mir::force_from_dep_node
  28:     0x7fd66e1c4dc1 - <rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt as rustc_query_system[8f6ed9285397c37a]::dep_graph::DepContext>::try_force_from_dep_node
  29:     0x7fd66dd0725e - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  30:     0x7fd66dd0722c - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  31:     0x7fd66dd0722c - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  32:     0x7fd66ddd1318 - rustc_query_system[8f6ed9285397c37a]::query::plumbing::get_query::<rustc_query_impl[362fa764a08dc22]::queries::layout_of, rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  33:     0x7fd66dd60fd0 - <rustc_query_impl[362fa764a08dc22]::Queries as rustc_middle[8b88f8a0f89f93bb]::ty::query::QueryEngine>::layout_of
  34:     0x7fd66d6cac58 - <rustc_mir_transform[63cdf027e05c8c75]::const_prop_lint::ConstProp as rustc_mir_transform[63cdf027e05c8c75]::pass_manager::MirLint>::run_lint
  35:     0x7fd66d6894d0 - rustc_mir_transform[63cdf027e05c8c75]::pass_manager::run_passes
  36:     0x7fd66d6dcaf8 - rustc_mir_transform[63cdf027e05c8c75]::mir_drops_elaborated_and_const_checked
  37:     0x7fd66e7cc85c - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt, rustc_middle[8b88f8a0f89f93bb]::ty::WithOptConstParam<rustc_span[e0494e7a78d29b23]::def_id::LocalDefId>, &rustc_data_structures[10bde15a730ca175]::steal::Steal<rustc_middle[8b88f8a0f89f93bb]::mir::Body>>
  38:     0x7fd66dd70688 - rustc_query_system[8f6ed9285397c37a]::query::plumbing::try_execute_query::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt, rustc_query_system[8f6ed9285397c37a]::query::caches::DefaultCache<rustc_middle[8b88f8a0f89f93bb]::ty::WithOptConstParam<rustc_span[e0494e7a78d29b23]::def_id::LocalDefId>, &rustc_data_structures[10bde15a730ca175]::steal::Steal<rustc_middle[8b88f8a0f89f93bb]::mir::Body>>>
  39:     0x7fd66dd5e8b8 - <rustc_query_impl[362fa764a08dc22]::Queries as rustc_middle[8b88f8a0f89f93bb]::ty::query::QueryEngine>::mir_drops_elaborated_and_const_checked
  40:     0x7fd66d6ddd5c - rustc_mir_transform[63cdf027e05c8c75]::optimized_mir
  41:     0x7fd66e7e44a7 - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt, rustc_span[e0494e7a78d29b23]::def_id::DefId, &rustc_middle[8b88f8a0f89f93bb]::mir::Body>
  42:     0x7fd66dd93b9d - rustc_query_system[8f6ed9285397c37a]::query::plumbing::try_execute_query::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt, rustc_query_system[8f6ed9285397c37a]::query::caches::DefaultCache<rustc_span[e0494e7a78d29b23]::def_id::DefId, &rustc_middle[8b88f8a0f89f93bb]::mir::Body>>
  43:     0x7fd66dd5eb5e - <rustc_query_impl[362fa764a08dc22]::Queries as rustc_middle[8b88f8a0f89f93bb]::ty::query::QueryEngine>::optimized_mir
  44:     0x7fd66e1f0d85 - <rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt>::instance_mir
  45:     0x7fd66d659e05 - rustc_monomorphize[7d37f3bf7209d2f1]::collector::collect_neighbours
  46:     0x7fd66d656762 - rustc_monomorphize[7d37f3bf7209d2f1]::collector::collect_items_rec
  47:     0x7fd66e4a9fbb - <rustc_session[cbae6b27f1b96b52]::session::Session>::time::<(), rustc_monomorphize[7d37f3bf7209d2f1]::collector::collect_crate_mono_items::{closure#1}>
  48:     0x7fd66e49efeb - rustc_monomorphize[7d37f3bf7209d2f1]::collector::collect_crate_mono_items
  49:     0x7fd66e4a5c36 - rustc_monomorphize[7d37f3bf7209d2f1]::partitioning::collect_and_partition_mono_items
  50:     0x7fd66cb525d8 - <rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind as rustc_query_system[8f6ed9285397c37a]::dep_graph::DepKind>::with_deps::<<rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt, (), (&std[23f59d9749713536]::collections::hash::set::HashSet<rustc_span[e0494e7a78d29b23]::def_id::DefId, core[d4370e29f295d5d]::hash::BuildHasherDefault<rustc_hash[e6f0752b427bcd09]::FxHasher>>, &[rustc_middle[8b88f8a0f89f93bb]::mir::mono::CodegenUnit])>::{closure#0}, (&std[23f59d9749713536]::collections::hash::set::HashSet<rustc_span[e0494e7a78d29b23]::def_id::DefId, core[d4370e29f295d5d]::hash::BuildHasherDefault<rustc_hash[e6f0752b427bcd09]::FxHasher>>, &[rustc_middle[8b88f8a0f89f93bb]::mir::mono::CodegenUnit])>
  51:     0x7fd66cbcfa81 - <rustc_query_system[8f6ed9285397c37a]::dep_graph::graph::DepGraph<rustc_middle[8b88f8a0f89f93bb]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8b88f8a0f89f93bb]::ty::context::TyCtxt, (), (&std[23f59d9749713536]::collections::hash::set::HashSet<rustc_span[e0494e7a78d29b23]::def_id::DefId, core[d4370e29f295d5d]::hash::BuildHasherDefault<rustc_hash[e6f0752b427bcd09]::FxHasher>>, &[rustc_middle[8b88f8a0f89f93bb]::mir::mono::CodegenUnit])>
  52:     0x7fd66e8b6a47 - rustc_query_system[8f6ed9285397c37a]::query::plumbing::try_execute_query::<rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt, rustc_query_system[8f6ed9285397c37a]::query::caches::DefaultCache<(), (&std[23f59d9749713536]::collections::hash::set::HashSet<rustc_span[e0494e7a78d29b23]::def_id::DefId, core[d4370e29f295d5d]::hash::BuildHasherDefault<rustc_hash[e6f0752b427bcd09]::FxHasher>>, &[rustc_middle[8b88f8a0f89f93bb]::mir::mono::CodegenUnit])>>
  53:     0x7fd66e8ef4b0 - rustc_query_system[8f6ed9285397c37a]::query::plumbing::get_query::<rustc_query_impl[362fa764a08dc22]::queries::collect_and_partition_mono_items, rustc_query_impl[362fa764a08dc22]::plumbing::QueryCtxt>
  54:     0x7fd66e84f042 - <rustc_query_impl[362fa764a08dc22]::Queries as rustc_middle[8b88f8a0f89f93bb]::ty::query::QueryEngine>::collect_and_partition_mono_items
  55:     0x7fd66e37a1f5 - <rustc_codegen_llvm[614e335b7ddb2b7c]::LlvmCodegenBackend as rustc_codegen_ssa[87ec517d1ac920df]::traits::backend::CodegenBackend>::codegen_crate
  56:     0x7fd66e340f77 - <rustc_session[cbae6b27f1b96b52]::session::Session>::time::<alloc[444af299f81eecf5]::boxed::Box<dyn core[d4370e29f295d5d]::any::Any>, rustc_interface[b04e2cdf424baf9e]::passes::start_codegen::{closure#0}>
  57:     0x7fd66e33d38c - <rustc_interface[b04e2cdf424baf9e]::passes::QueryContext>::enter::<<rustc_interface[b04e2cdf424baf9e]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[d4370e29f295d5d]::result::Result<alloc[444af299f81eecf5]::boxed::Box<dyn core[d4370e29f295d5d]::any::Any>, rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>
  58:     0x7fd66e36146f - <rustc_interface[b04e2cdf424baf9e]::queries::Queries>::ongoing_codegen
  59:     0x7fd66e309deb - <rustc_interface[b04e2cdf424baf9e]::interface::Compiler>::enter::<rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}::{closure#2}, core[d4370e29f295d5d]::result::Result<core[d4370e29f295d5d]::option::Option<rustc_interface[b04e2cdf424baf9e]::queries::Linker>, rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>
  60:     0x7fd66e3325af - rustc_span[e0494e7a78d29b23]::with_source_map::<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_interface[b04e2cdf424baf9e]::interface::create_compiler_and_run<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}>::{closure#1}>
  61:     0x7fd66e31dd94 - rustc_interface[b04e2cdf424baf9e]::interface::create_compiler_and_run::<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}>
  62:     0x7fd66e3082b2 - <scoped_tls[941ee80d8231eb23]::ScopedKey<rustc_span[e0494e7a78d29b23]::SessionGlobals>>::set::<rustc_interface[b04e2cdf424baf9e]::interface::run_compiler<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}>::{closure#0}, core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>
  63:     0x7fd66e31f37f - std[23f59d9749713536]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b04e2cdf424baf9e]::util::run_in_thread_pool_with_globals<rustc_interface[b04e2cdf424baf9e]::interface::run_compiler<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}>::{closure#0}, core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>::{closure#0}, core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>
  64:     0x7fd66e31f4b9 - <<std[23f59d9749713536]::thread::Builder>::spawn_unchecked_<rustc_interface[b04e2cdf424baf9e]::util::run_in_thread_pool_with_globals<rustc_interface[b04e2cdf424baf9e]::interface::run_compiler<core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>, rustc_driver[2c8e23c1704d1846]::run_compiler::{closure#1}>::{closure#0}, core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>::{closure#0}, core[d4370e29f295d5d]::result::Result<(), rustc_errors[4317dacdbe7ee454]::ErrorGuaranteed>>::{closure#1} as core[d4370e29f295d5d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  65:     0x7fd66bac6223 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hae8ffeec5cb662e2
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/alloc/src/boxed.rs:1872:9
  66:     0x7fd66bac6223 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1b179c7aca9d8b98
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/alloc/src/boxed.rs:1872:9
  67:     0x7fd66bac6223 - std::sys::unix::thread::Thread::new::thread_start::h3faf721b71afff7d
                               at /rustc/615edd3ad1cf6871c977dc900317cb6c2070fd6b/library/std/src/sys/unix/thread.rs:108:17
  68:     0x7fd66b9e1609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  69:     0x7fd66b8fa133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  70:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (615edd3ad 2022-05-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `foo::{closure#0}`
#1 [layout_of] computing layout of `impl core::future::future::Future<Output = ()>`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `main`
#3 [optimized_mir] optimizing MIR for `main`
#4 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

### LINKED ISSUE #98477: drop-tracking: type parameters are incorrectly required to be Send to make futures Send
cc https://github.com/rust-lang/rust/issues/97331, @eholk. Minimized from https://crater-reports.s3.amazonaws.com/pr-97334/try%23615edd3ad1cf6871c977dc900317cb6c2070fd6b/gh/AtsushiMiyazaki.rust-cmd/log.txt in the crater run for https://github.com/rust-lang/rust/pull/97334.

I tried this code:

```rust
fn assert_send<F: Send>(_: F) {}

async fn __post<T>() -> T {
    if false {
        todo!()
    } else {
        async {}.await;
        todo!()
    }
}

fn foo<T>() {
    assert_send(__post::<T>());
}
```

I expected to see this happen: The code compiles fine, like it does without -Zdrop-tracking. The code doesn't actually use `T` anywhere so it shouldn't require it to be Send.

Instead, this happened:

```
error: future cannot be sent between threads safely
  --> rust-iost/rpc/src/lib.rs:13:17
   |
13 |     assert_send(__post::<T>());
   |                 ^^^^^^^^^^^^^ future returned by `__post` is not `Send`
   |
note: future is not `Send` as this value is used across an await
  --> rust-iost/rpc/src/lib.rs:7:17
   |
4  |       if false {
   |  ______________-
5  | |         todo!()
6  | |     } else {
   | |_____- has type `T` which is not `Send`
7  |           async {}.await;
   |                   ^^^^^^ await occurs here, with the value maybe used later
8  |           todo!()
9  |       }
   |       - the value is later dropped here
note: required by a bound in `assert_send`
  --> rust-iost/rpc/src/lib.rs:1:19
   |
1  | fn assert_send<F: Send>(_: F) {}
   |                   ^^^^ required by this bound in `assert_send`
help: consider restricting type parameter `T`
   |
12 | fn foo<T: std::marker::Send>() {
   |         +++++++++++++++++++
```

### Meta

`rustc --version --verbose`: 615edd3ad1cf6871c977dc900317cb6c2070fd6b

### PR DESCRIPTION
**Pull request by jyn514**
Previously, drop-tracking would incorrectly assume the struct would be dropped immediately, which was not true.

Fixes #98476. Also fixes https://github.com/rust-lang/rust/issues/98477, I think because the parent HIR node for type variables is the whole function instead of the expression where the variable is used.

r? @eholk

### CODE REVIEW

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 1]
```diff
@@ -384,7 +386,9 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
         // However, in the case of temporary values, we are going to store the value into a
         // temporary on the stack that is live for the current temporary scope and then return a
         // reference to it. That value may be live across the entire temporary scope.
-        let scope = if self.drop_ranges.is_borrowed_temporary(expr) {
+        let scope = if self.drop_ranges.is_borrowed_temporary(expr)
+            || ty.map_or(true, |ty| ty.has_significant_drop(self.fcx.tcx, self.fcx.param_env))
```
Comment (jyn514) [inline compiler/rustc_typeck/src/check/generator_interior.rs:390]: hmm. this is probably more coarse than necessary - it will also trigger for things like `let x = String::new(); drop(x)`. I don't know a better way to do this - I guess this is what you were talking about in DMs?

> eholk: But I think maybe the conservative thing to do is to count the field access (.nickname) as a borrow of the Config temporary, so we should add it to maybe_borrowed_temporaries. Then I think that should make the whole Config live for the whole temporary scope (until the semicolon). It's more conservative than it needs to be, since .nickname has been dropped but this would still consider it live since it's part of the type of Config, but it should be sound.

Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: oh, it's still going to use the temporary scope though - I guess the proper use case is something like
```rust
f(String::new()).await
```
where the future doesn't actually use the string

Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: oh lol while debugging this I found that there's another existing bug where we're too coarse: for non-Sync types with trivial drop, we still consider them held across the generator:
```
async fn trivial_drop() {
    // uncomment to make this program compile
    // {
    let x: *const usize = &0;
    // }
    async {}.await;
}

fn assert_send<T: Send>(_: T) {}

fn main() {
    assert_send(trivial_drop());
}
```

Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: tried to fix this but got an ICE :( I think I will put this off until later
```diff
diff --git a/compiler/rustc_typeck/src/check/generator_interior.rs b/compiler/rustc_typeck/src/check/generator_interior.rs
index 946bfa52d37..5caa1b2ded7 100644
--- a/compiler/rustc_typeck/src/check/generator_interior.rs
+++ b/compiler/rustc_typeck/src/check/generator_interior.rs
@@ -387,7 +387,10 @@ fn visit_expr(&mut self, expr: &'tcx Expr<'tcx>) {
         // temporary on the stack that is live for the current temporary scope and then return a
         // reference to it. That value may be live across the entire temporary scope.
         let scope = if self.drop_ranges.is_borrowed_temporary(expr)
-            || ty.map_or(true, |ty| ty.has_significant_drop(self.fcx.tcx, self.fcx.param_env))
+            || ty.map_or(true, |ty| {
+                !ty.needs_drop(self.fcx.tcx, self.fcx.param_env)
+                || ty.has_significant_drop(self.fcx.tcx, self.fcx.param_env)
+            })
         {
             self.rvalue_scopes.temporary_scope(self.region_scope_tree, expr.hir_id.local_id)
         } else {
```
```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 13', /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
  21:     0x7f12f71e004b - ena::unify::UnificationTable<S>::value::h616d0c0c6ae4057b
                               at /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/
src/unify/mod.rs:347:10
  22:     0x7f12f71e004b - ena::unify::UnificationTable<S>::inlined_get_root_key::hea2bf8b4576b5472
                               at /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/
src/unify/mod.rs:362:19
  23:     0x7f12f71e004b - ena::unify::UnificationTable<S>::inlined_probe_value::hc1dc88e31da4bcc9
                               at /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/
src/unify/mod.rs:566:18
  24:     0x7f12f71e004b - rustc_infer::infer::type_variable::TypeVariableTable::inlined_probe::h29b4e108ffacbc08
                               at /home/jnelson/rust-lang/rust/compiler/rustc_infer/src/infer/type_variable.rs:312:9
  25:     0x7f12f71e004b - rustc_infer::infer::type_variable::TypeVariableTable::probe::h91a8d70bb6dc3e56
                               at /home/jnelson/rust-lang/rust/compiler/rustc_infer/src/infer/type_variable.rs:306:9
  26:     0x7f12f717fe34 - rustc_infer::infer::InferCtxt::probe_ty_var::hefc9501f755a1a65
                               at /home/jnelson/rust-lang/rust/compiler/rustc_infer/src/infer/mod.rs:1388:15
  27:     0x7f12f71d7089 - <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::Ty
peFolder>::fold_ty::h0ebb9c6ed6bc4918
                               at /home/jnelson/rust-lang/rust/compiler/rustc_infer/src/infer/canonical/canonicalizer
.rs:394:23
...

query stack during panic:
#0 [is_copy_raw] computing whether `[static generator@src/test/ui/async-await/non-trivial-drop-unused.rs:11:11: 11:13
]` is `Copy`
#1 [needs_drop_raw] computing whether `[static generator@src/test/ui/async-await/non-trivial-drop-unused.rs:11:11: 11
:13]` needs drop
#2 [typeck] type-checking `trivial_drop`
#3 [mir_built] building MIR for `trivial_drop`
#4 [unsafety_check_result] unsafety-checking `trivial_drop`
#5 [mir_const] processing MIR for `trivial_drop`
#6 [mir_promoted] processing `trivial_drop`
#7 [mir_borrowck] borrow-checking `trivial_drop`
#8 [type_of] computing type of `trivial_drop::{opaque#0}`
#9 [check_mod_item_types] checking item types in top-level module
#10 [analysis] running analysis passes on this crate
end of query stack
```

Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: > I guess the proper test case is something like

looks like this already errors today:
```
$  cat src/test/ui/async-await/non-trivial-drop-unused.rs
use std::rc::Rc;

async fn ignore_param(x: Rc<i32>) {
    drop(x);
    async {}.await;
}

fn assert_send<T: Send>(_: T) {}

fn main() {
    assert_send(ignore_param(Rc::new(0)));
}
$ rustc +nightly src/test/ui/async-await/non-trivial-drop-unused.rs --edition 2018 -Zdrop-tracking 
error: future cannot be sent between threads safely
  --> src/test/ui/async-await/non-trivial-drop-unused.rs:19:17
   |
19 |     assert_send(ignore_param(Rc::new(0)));
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^ future returned by `ignore_param` is not `Send`
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<i32>`
note: captured value is not `Send`
  --> src/test/ui/async-await/non-trivial-drop-unused.rs:6:23
   |
6  | async fn ignore_param(x: Rc<i32>) {
   |                       ^ has type `Rc<i32>` which is not `Send`
note: required by a bound in `assert_send`
  --> src/test/ui/async-await/non-trivial-drop-unused.rs:16:19
   |
16 | fn assert_send<T: Send>(_: T) {}
   |                   ^^^^ required by this bound in `assert_send`
```
that *also* seems wrong, for some reason it considers the param held for the whole async function even if you drop it earlier

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: just fyi that neither of those (nor most of the query-like functions on Ty) account for type variables, so that's why it's panicking i think

Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: wait what? why do they take a ParamEnv if they don't account for type variables?

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: that's because we still need to normalize projections -- also, reminder that i said type variables, not type parameters. type variables don't have anything to do with param envs. 

note a similar difference between Infcx::type_is_copy_modulo_regions and Ty::is_copy_modulo_regions.

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: Type (inference) variables are associated to a given InferCtxt, so unless the function is associated with one of those, it's not typically safe to pass a Ty to it unless you know that we're past the type-checking phase or we're outside of a function body.

**Comment by jyn514** [comment]
... apparently this fixes https://github.com/rust-lang/rust/issues/98477 too ?? I'll add a test.

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 1 above)
Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: thanks, using `!self.fcx.inh.infcx.resolve_vars_if_possible(ty).needs_drop(self.fcx.tcx, self.fcx.param_env)` fixed the ICE (but didn't allow the code to compile for reasons I don't understand - going to stop harping on it in this PR since it's not related to the current fix)

Comment (compiler-errors) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: nit: fcx derefs to infcx so you should just be able to do fcx.resolve_vars_if_possible

also that'll still ice if you have any region variables, so you might need to pass it through erase_regions for types that have lifetimes and also significant drops

**Review by eholk — APPROVED** [review]

**Comment by eholk** [comment]
This is awesome! I love it when it's just a small thing that was overlooked that fixes a bunch of different bugs.

(I don't know if this will work, but I'm going to try anyway...)
@bors r+

**Comment by eholk** [comment]
> @eholk: 🔑 Insufficient privileges: Not in reviewers

Ah, guess not. Oh well!

**Comment by compiler-errors** [comment]
hm, I'm not confident that this is the right solution...? Though I am only barely familiar with it.

> eholk: But I think maybe the conservative thing to do is to count the field access (.nickname) as a borrow of the Config temporary, so we should add it to maybe_borrowed_temporaries. Then I think that should make the whole Config live for the whole temporary scope (until the semicolon). It's more conservative than it needs to be, since .nickname has been dropped but this would still consider it live since it's part of the type of Config, but it should be sound.

@jyn514, what happened to this convo that you mentioned above?

**Comment by compiler-errors** [comment]
but anyways if eholk is ok w/ the change then that's fine

@bors delegate=eholk

**Comment by eholk** [comment]
That was a conversation we had as a DM on Zulip (I guess in retrospect we probably should have discussed it in #wg-async).

This change seems reasonable to me. This is related to #94309, where we changed the scope we considered values live for to be smaller in some circumstances. Basically there the change was to use the parent expression as the scope, rather the temporary scope, unless the value was borrowed at some point (since the MIR counterpart to generator_interior is really conservative around borrows). It turns out that was a little too aggressive because if the value has a non-trivial drop, we need to consider it live until the destructor runs at the end of the temporary scope.

**Comment by compiler-errors** [comment]
I _think_ I understand. I guess the one part I am somewhat suspicious of is the usage of `has_significant_drop` over `needs_drop` -- the former seems RFC 2229 specific:

```
/// Note that this method is used to check for change in drop order for
/// 2229 drop reorder migration analysis.
```

**Comment by eholk** [comment]
Ah, good question. Let me read up a little more on that and figure out which one is more appropriate. (@jyn514 - I noticed at one point you used both? Do you know what the difference is?)

**Comment by compiler-errors** [comment]
I _think_ we should be using `needs_drop`, but that one was ICEing due to some inference variable issues. I would rather us fix those inference variable issues properly.

If either of y'all need me to investigate how to get `needs_drop` to work without ICEing, lmk/ping me.

**Comment by jyn514** [comment]
I am not convinced we should be using `needs_drop`. Here is the documentation for both functions:
[`needs_drop()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Ty.html#method.needs_drop):
> If ty.needs_drop(...) returns true, then ty is definitely non-copy and might have a destructor attached; if it returns false, then ty definitely has no destructor (i.e., no drop glue).

[`has_significant_drop()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Ty.html#method.has_significant_drop):
> If ty.needs_drop(...) returns true, then ty is definitely non-copy and might have a destructor attached; if it returns false, then ty definitely has no destructor (i.e., no drop glue).

"non-copy" is not the right criteria here; we want this code (from https://github.com/rust-lang/rust/pull/94309) to compile, even if `Config` contains types which aren't Copy:
```rust
fn status(_client_status: &Client) -> i16 {
    200
}

fn main() {
    let client = Client;
    let g = move || match status(&client) {
        _status => yield,
    };
    assert_send(g);
}
```

In general, I am very unsure why the change in https://github.com/rust-lang/rust/pull/94309 is valid: it seems to me that *any* time `Client` has a drop impl, it's an observable change whether it's dropped before or after the yield.

**Comment by jyn514** [comment]
oh, but this test continues to pass even after my PR :/ not sure why this is allowed, will debug.
```
// check-pass
// compile-flags: -Zdrop-tracking
#![feature(generators, negative_impls)]

struct Client;

impl !Sync for Client {}
impl Drop for Client {
    fn drop(&mut self) {}
}

fn status(_client_status: &Client) -> i16 {
    200
}

fn assert_send<T: Send>(_thing: T) {}

// This is the same bug as issue 57017, but using yield instead of await
fn main() {
    let client = Client;
    let g = move || match status(&client) {
        _status => yield,
    };
    assert_send(g);
}
```

**Comment by jyn514** [comment]
Turns out that's because the type that's we're considering is `&Client`, not `Client`, so it's Copy.

If we change it so that the type in question is Client, then we have an ICE both before and after my PR when drop-tracking is enabled:

```rust
    let g = move || match status(Client { ..Client::default() }) {
```
```
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:760:13: Broken MIR: generator contains type Client in MIR, but typeck only knows about {i16, ()} and []
```

**Comment by jyn514** [comment]
> If we change it so that the type in question is Client, then we have an ICE both before and after my PR when drop-tracking is enabled and Client has a manual Drop impl:

Using `needs_drop` instead of `has_significant_drop` doesn't help, it still ICEs.

**Comment by jyn514** [comment]
Ok, I pushed a test which shows why we need to use `has_significant_drop` instead of needs_drop. In particular, this variant of the test fails when using needs_drop: https://github.com/rust-lang/rust/blob/eaf6db8638a4a73c38fb7692876e406f3ba20014/src/test/ui/generator/drop-tracking-parent-expression.rs#L41-L42

**Comment by jyn514** [comment]
Hmm, but now this ICEs on types with `rustc_insignificant_dtor`:
```rust
#[derive(Default)]
#[rustc_insignificant_dtor]
pub struct Client2;
impl Drop for Client2 {
    fn drop(&mut self) {}
}

fn main() {
    let f = move || match drop(Client2 { ..Client2::default() }) {
        _status => yield,
    };
    assert_send(f);
}
```
```
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:760:13: Broken MIR: generator contains type Client2 in MIR, but typeck only knows about {()} and []
  --> /home/jnelson/rust-lang/rust2/src/test/ui/generator/derived-drop-parent-expr.rs:25:13
   |
LL |     let f = move || match drop(Client2 { ..Client2::default() }) {
   |             ^^^^^^^
```
I think that might be ok? The only time when this comes up is when using struct update syntax, or when passing individual fields of a struct into a function. Neither of those are possible when the struct fields are private, which is true for all the types annotated with this attr in the standard library:
```
$ rg rustc_insignificant library -A1
library/alloc/src/collections/linked_list.rs
49:#[rustc_insignificant_dtor]
50-pub struct LinkedList<T> {

library/alloc/src/collections/vec_deque/mod.rs
97:#[rustc_insignificant_dtor]
98-pub struct VecDeque<

library/alloc/src/rc.rs
308:#[rustc_insignificant_dtor]
309-pub struct Rc<T: ?Sized> {

library/alloc/src/collections/btree/map.rs
171:#[rustc_insignificant_dtor]
172-pub struct BTreeMap<
--
381:#[rustc_insignificant_dtor]
382-pub struct IntoIter<

library/std/src/collections/hash/map.rs
212:#[rustc_insignificant_dtor]
213-pub struct HashMap<K, V, S = RandomState> {

library/alloc/src/vec/mod.rs
399:#[rustc_insignificant_dtor]
400-pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {

library/alloc/src/vec/into_iter.rs
29:#[rustc_insignificant_dtor]
30-pub struct IntoIter<

library/core/src/array/iter.rs
13:#[rustc_insignificant_dtor]
14-pub struct IntoIter<T, const N: usize> {
```

File: compiler/rustc_typeck/src/check/generator_interior.rs (hunk 1 above)
Comment (jyn514) [reply compiler/rustc_typeck/src/check/generator_interior.rs:390]: Ok, figured this out: https://github.com/rust-lang/rust/pull/99105

**Comment by compiler-errors** [comment]
> If it becomes a problem in the future, we can modify has_significant_drop to take a parameter specifying whether to take this attribute into account or not. (Or I can just do that now if you think this is a blocker.)

Yeah, maybe splitting this into a separate method, maybe called `has_destructor` or sth. Or maybe just adding a parameter like `ignore_insignificant`. The types annotated with these attributes are pretty common, so I'd be worried about keeping this behavior. But maybe @eholk's thoughts would be welcome too?

**Comment by jyn514** [comment]
Ok, after looking at the code some more it turns out that `has_significant_drop` is actually exactly the same as `needs_drop` if you ignore `rustc_insignificant_dtor`, glad you brought it up. I've changed this to instead see if the ADT has its own `Drop` impl (as opposed to being non-copy) instead, which I think keeps the semantics we want.

oh lol after doing this I found that drop-tracking is *more* precise than MIR borrowck and so we ICE :facepalm:
```
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:760:13: Broken MIR: generator contains type Config in MIR, but typeck only knows about {NonCopy, ()} and []
  --> src/test/ui/async-await/non-trivial-drop.rs:12:5
   |
LL |     || {
   |     ^^
```
https://github.com/rust-lang/rust/blob/121e7b63d722648e9ce71d2fc0934ac0d22450a4/src/test/ui/async-await/non-trivial-drop.rs#L11-L18

I think I'm just going to do this for all non-copy types for now and worry about being more granular later. As a result the test case  in https://github.com/rust-lang/rust/pull/98754#issuecomment-1179645390 will be broken until I get around to fixing this.

**Comment by jyn514** [comment]
> I think I'm just going to do this for all non-copy types for now and worry about being more granular later. As a result the test case in https://github.com/rust-lang/rust/pull/98754#issuecomment-1179645390 will be broken until I get around to fixing this.

Ok, done. This also means the diagnostics for https://github.com/rust-lang/rust/issues/97332 haven't been improved unfortunately.

@rustbot ready

File: compiler/rustc_typeck/src/check/generator_interior.rs [hunk 2]
```diff
@@ -376,6 +376,17 @@ impl<'a, 'tcx> Visitor<'tcx> for InteriorVisitor<'a, 'tcx> {
...
 
+        let ty = self.fcx.typeck_results.borrow().expr_ty_adjusted_opt(expr);
+        let may_need_drop = |ty: Ty<'tcx>| {
+            let ty = self.fcx.resolve_vars_if_possible(ty);
+            // Use this instead of `needs_infer` to avoid penalizing types with lifetimes.
+            // This is just a workaround to avoid ICEs anyway.
+            if ty.has_infer_types_or_consts() {
+                return true;
+            }
+            ty.needs_drop(self.fcx.tcx, self.fcx.param_env)
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/generator_interior.rs:387]: Will ICE if there are any region variables, I think. try this :smile_cat: 

```suggestion
            self.fcx.tcx.erase_regions(ty).needs_drop(self.fcx.tcx, self.fcx.param_env)
```

**Review by compiler-errors — APPROVED** [review]
r=me with tiny nit applied and if @eholk is happy with these changes too

**Comment by eholk** [comment]
Looks good to me!

Trying to be precise but not more precise than MIR has been a struggle with this feature :)

@bors r=compiler-errors

**Comment by Dylan-DPC** [comment]
likely failed in [rollup](https://github.com/rust-lang/rust/pull/99172#issuecomment-1181617820)

@bors r-

**Comment by jyn514** [comment]
I don't see how `src/test/run-pass-valgrind/cast-enum-with-dtor.rs` can be related. It uses no async code or generators and the error was because it got SIGKILL. I think it's much more likely that the MacOS runner just kills processes sometimes.

@bors r=compiler-errors
