### PR TITLE
Rustdoc: memoize `pub use`-reexported macros so they don't appear twice in docs

### LINKED ISSUE #39436: #[doc(hidden)] does not work for externally used macros
If a macro is imported using `use` (via the `use_extern_macros` feature), its documentation cannot be hidden. For instance, if the code is:

```rust
extern crate serde_json;

#[doc(hidden)]
pub use serde_json::json;
```

The documentation for the `json` macro will appear in the rustdocs. Of course, the expected result is that the documentation _does not_ appear.

cc @jseyfried @nrc @dtolnay

### PR DESCRIPTION
**Pull request by abonander**
Closes #39436 

Preserves existing behavior for `#[macro_reexport]`. `pub use`'d macros are shown as reexports unless inlined, and also correctly obey `#[doc(hidden)]`.

r? @jseyfried 

cc @SergioBenitez

### CODE REVIEW

**Comment by abonander** [comment]
I don't have a test for this because I don't have a clue where to start writing one. run-make + grep again?

**Comment by jseyfried** [comment]
This looks correct but seems like a step in the wrong direction w.r.t. complexity.

Could we get instead get rid of [this block](https://github.com/rust-lang/rust/pull/40814/files#diff-405166496365fa89a1db51bac554c2b2R201) entirely so that macro re-exports are not inlined by default and then push to `om.macros` [here](https://github.com/rust-lang/rust/pull/40814/files#diff-405166496365fa89a1db51bac554c2b2R283) when we *do* inline instead of removing from `export_map` when we *don't* inline?

I believe that would be equivalent, except that `#[macro_reexported]` macros would no longer get documented. To address this, we could
 - deprecate `#![feature(macro_reexport)]` in favor of `#![feature(use_extern_macro)]` (I've been meaning to do this for awhile), and/or
 - keep a `Vec` of `#[macro_reexported]`ed macro in the `Resolver` and push to these to `om.macros` directly in `rustdoc`.

**Comment by abonander** [comment]
The second option sounds like it'll require more complexity and touch more code, and I was hesitant to break documentation for `#[macro_reexport]`, whether we want to deprecate it or not.

Perhaps we can fix the issue first, then deprecate `#[macro_reexport]` and have a patch for the first option ready to merge alongside the attribute's removal? Going from this fix to the first option basically just involves moving some code around and reverting the need for `RefCell` on `export_map`.

**Comment by abonander** [comment]
"the first option" being your suggested changes; I just don't like the idea of breaking documentation for `#[macro_reexport]` even if it becomes deprecated--it's not really fair to the user, IMO.

**Comment by jseyfried** [comment]
Ok, makes sense. I still prefer the second option, but this is fine for now, especially since we can switch to the first option when removing `#[macro_reexport]` as you suggested.

I think you can write a `src/test/rustdoc` test. Looking at existing tests, it appears `// @has` checks that a file or string is in the docs, and `// @!has` checks that a file or string is not in the docs.

r=me with a test

**Comment by abonander** [comment]
The second option isn't horrible I guess, I just don't like touching Resolver for a short-term fix. It feels like it's leaking the scope of the fix.

**Comment by abonander** [comment]
@jseyfried New solution + test. I think you'll like it better than before.

**Comment by abonander** [comment]
I've also added some blank lines in places because it makes those bits easier to read.

File: src/librustdoc/visit_ast.rs [hunk 1]
```diff
@@ -274,6 +281,20 @@ impl<'a, 'tcx> RustdocVisitor<'a, 'tcx> {
...
+        // declaration in `visit_mod_contents()`
+        if !def_did.is_local() {
+            if let Def::Macro(did, _) = def {
+                if please_inline { return true }
+
+                debug!("memoizing non-inlined macro export: {:?}", def);
+
+                self.reexported_macros.insert(did);
+
+                return false;
```
Comment (abonander) [inline src/librustdoc/visit_ast.rs]: I could probably condense this block though, it looks weird in review.

Comment (jseyfried) [inline src/librustdoc/visit_ast.rs]: I'd probably condense, but up to you.

**Comment by jseyfried** [comment]
@abonander I do like this solution more :)
@bors r+
@bors delegate=abonander
