### PR TITLE
Don't suggest `.into_iter()` on iterators

### LINKED ISSUE #127511: "is not an iterator" diagnostic through blanket implementation, when the type is actually an iterator but is missing a marker
### Code

(inspired by [rayon's `ParallelBridge`](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelBridge.html))

```Rust
pub trait ParallelBridge: Sized {
    // Required method
    fn par_bridge(self) -> ();
}

impl<T: Iterator + Send> ParallelBridge for T
where
    T::Item: Send,
{
    fn par_bridge(self) -> () {
        unimplemented!("par_bridge");
    }
}


fn f(it: impl Iterator<Item=u64>) {
    it.map(|i| i+1).par_bridge()
}

fn main() -> std::io::Result<()> {
    let (_tx, rx) = std::sync::mpsc::sync_channel(1000);
    f(rx.iter());

    Ok(())
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=290bd6102ce2b63a30bb6c78e5a74e8b)

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `par_bridge` found for struct `Map<impl Iterator<Item = u64>, {closure@src/main.rs:17:12: 17:15}>` in the current scope
  --> src/main.rs:17:21
   |
17 |     it.map(|i| i+1).par_bridge()
   |                     ^^^^^^^^^^ `Map<impl Iterator<Item = u64>, {closure@src/main.rs:17:12: 17:15}>` is not an iterator
   |
help: call `.into_iter()` first
   |
17 |     it.map(|i| i+1).into_iter().par_bridge()
   |                     ++++++++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Desired output

The same error there is when removing the `.map()`

```
   Compiling playground v0.0.1 (/playground)
error[E0599]: no method named `par_bridge` found for type parameter `impl Iterator<Item = u64>` in the current scope
  --> src/main.rs:17:8
   |
16 | fn f(it: impl Iterator<Item=u64>) {
   |          ----------------------- method `par_bridge` not found for this type parameter
17 |     it.map(|i| i+1).par_bridge()
   |        ^^^^^^^^^^ method cannot be called on `impl Iterator<Item = u64>` due to unsatisfied trait bounds
   |
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `par_bridge`, perhaps you need to restrict type parameter `impl Iterator<Item = u64>` with it:
   |
16 | fn f(it: impl Iterator<Item=u64> + ParallelBridge) {
   |                                  ++++++++++++++++

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Rationale and extra context

The error indicated the type does not implement `Iterator`, even though it does and `Send` is the one that is missing.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.79.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dianne**
This makes the the suggestion to call `.into_iter()` only consider unsatisfied `Iterator` bounds for the receiver type itself. That way, it ignores predicates generated by trying to auto-ref the receiver (the result of which usually won't implement `Iterator`).

Fixes #127511

Unfortunately, the error in that case is still confusing: it labels `Iterator` as an unsatisfied bound because `&impl Iterator: Iterator` can't be satisfied, despite that not being required or helpful. I'd like to handle that in a separate PR. ~~I'm hoping fixing #124802 will fix it too.~~ It doesn't look connected to that issue. Still, I think it'd be clearest to visually distinguish unsatisfied predicates from different attempts at `pick_method`; I'll make a PR for that soon.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -152,6 +152,15 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             return false;
         }
 
+        // Does the `ty` not already implement `Iterator`? (#127511)
+        if let Some(iterator_trait) = self.tcx.get_diagnostic_item(sym::Iterator)
+            && self
+                .type_implements_trait(iterator_trait, [ty], self.param_env)
+                .must_apply_modulo_regions()
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:159]: this should not be necessary :thinking: why is the `impl Iterator: Iterator` in the `unsatisfied_predicates`. I feel like there's something bigger going on which likely also affects other diagnostics.

Comment (lcnr) [reply compiler/rustc_hir_typeck/src/method/suggest.rs:159]: ah, the reason is that `unsatisfied_predicates` also contains all the unsatisfied predicates from auto-ref and the deref-steps, e.g.
```rust
trait Trait {
    fn method(self)
}

trait Bound {}
impl<T: Bound> Trait for T {
    fn method(self) {}
}

fn main() {
    0u32.method()
}
```
results in 
```rust
error[E0599]: the method `method` exists for type `u32`, but its trait bounds were not satisfied
  --> src/main.rs:11:10
   |
11 |     0u32.method()
   |          ^^^^^^ method cannot be called on `u32` due to unsatisfied trait bounds
   |
note: the following trait bounds were not satisfied:
      `&mut u32: Bound`
      `&u32: Bound`
      `u32: Bound
```
as you can see in the new error message for this issue, it's talking about the following unsatisfied obligations:
```
      `&impl Iterator: Iterator`
      `&impl Iterator: Missing`
      `&mut impl Iterator: Missing`
      `impl Iterator: Missing`
```
so instead of checking whether `ty` implements iterator, modify `is_iterator_predicate` to only trigger if the self-type of the iterator predicate is `ty` itself

Comment (dianne) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: nice catch! I was thinking along those lines for making that error less confusing, but I totally missed that it could be applied to `is_iterator_predicate` too. it's much nicer now; thank you
