### PR TITLE
Avoid follow-up errors and ICEs after missing lifetime errors on data structures

### LINKED ISSUE #124083: ICE: `trying to compare incompatible constructors Ref and Str(Ty("foo"))`
auto-reduced (treereduce-rust):
````rust
enum En1<T> {
    Outest(&'a T),
}

fn wrap_en1_1<T>(x: T) -> En1<T> {}

fn main() {
    if let En1::Outest("foo") = wrap_en1_1::<_>("foo") {}
}


````

original:
````rust
trait Tr1 {}

enum En1<T> {
    Outest(&'a T),
}

fn wrap_en1_1<T>(x: T) -> En1<T> {}

fn main() {
    if let En1::Outest("foo") = wrap_en1_1::<_>("foo") {}
}

````

Version information
````
rustc 1.79.0-nightly (803e33a44 2024-04-17)
binary: rustc
commit-hash: 803e33a4460c82581bd01d4008d0f44aef1ddfe8
commit-date: 2024-04-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0261]: use of undeclared lifetime name `'a`
 --> /tmp/icemaker_global_tempdir.GLAdtPI8j8km/rustc_testrunner_tmpdir_reporting.XLmLiOlBrrIu/mvce.rs:2:13
  |
1 | enum En1<T> {
  |          - help: consider introducing lifetime `'a` here: `'a,`
2 |     Outest(&'a T),
  |             ^^ undeclared lifetime

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.GLAdtPI8j8km/rustc_testrunner_tmpdir_reporting.XLmLiOlBrrIu/mvce.rs:5:27
  |
5 | fn wrap_en1_1<T>(x: T) -> En1<T> {}
  |    ----------             ^^^^^^ expected `En1<T>`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
  |
  = note:   expected enum `En1<T>`
          found unit type `()`

error: internal compiler error: compiler/rustc_pattern_analysis/src/rustc.rs:897:9: trying to compare incompatible constructors Ref and Str(Ty("foo"))
 --> /tmp/icemaker_global_tempdir.GLAdtPI8j8km/rustc_testrunner_tmpdir_reporting.XLmLiOlBrrIu/mvce.rs:8:12
  |
8 |     if let En1::Outest("foo") = wrap_en1_1::<_>("foo") {}
  |            ^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_pattern_analysis/src/rustc.rs:897:9:
Box<dyn Any>
stack backtrace:
   0:     0x7a8d45dd8cd5 - std::backtrace_rs::backtrace::libunwind::trace::hd9cb198098d2c61d
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7a8d45dd8cd5 - std::backtrace_rs::backtrace::trace_unsynchronized::hddf1040e7fdba935
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7a8d45dd8cd5 - std::sys_common::backtrace::_print_fmt::h804fa0989ad810bd
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7a8d45dd8cd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h22cafdf1748a9616
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7a8d45e27f9b - core::fmt::rt::Argument::fmt::h6949bd6acf715f08
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/core/src/fmt/rt.rs:165:63
   5:     0x7a8d45e27f9b - core::fmt::write::h477d5c38da630f26
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/core/src/fmt/mod.rs:1157:21
   6:     0x7a8d45dcd85f - std::io::Write::write_fmt::h702d781f9312caab
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/io/mod.rs:1832:15
   7:     0x7a8d45dd8aae - std::sys_common::backtrace::_print::ha98bb3f47b7f108d
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7a8d45dd8aae - std::sys_common::backtrace::print::h0fda5e4e3b41e77c
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7a8d45ddb429 - std::panicking::default_hook::{{closure}}::h2f2bd0e1ae5292c4
  10:     0x7a8d45ddb16d - std::panicking::default_hook::hae01f2639bb30551
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/panicking.rs:291:9
  11:     0x7a8d4266c82b - std[579020d2760f34a5]::panicking::update_hook::<alloc[dd6d785e9c2bdfe3]::boxed::Box<rustc_driver_impl[f3f4779df6407916]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7a8d45ddbb2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8cd1b2746579a7c1
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/alloc/src/boxed.rs:2036:9
  13:     0x7a8d45ddbb2c - std::panicking::rust_panic_with_hook::hbf6eda42ac6530ee
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/panicking.rs:792:13
  14:     0x7a8d4269cc24 - std[579020d2760f34a5]::panicking::begin_panic::<rustc_errors[38e7372a7ffc3815]::ExplicitBug>::{closure#0}
  15:     0x7a8d426995d6 - std[579020d2760f34a5]::sys_common::backtrace::__rust_end_short_backtrace::<std[579020d2760f34a5]::panicking::begin_panic<rustc_errors[38e7372a7ffc3815]::ExplicitBug>::{closure#0}, !>
  16:     0x7a8d42694b66 - std[579020d2760f34a5]::panicking::begin_panic::<rustc_errors[38e7372a7ffc3815]::ExplicitBug>
  17:     0x7a8d426a5c51 - <rustc_errors[38e7372a7ffc3815]::diagnostic::BugAbort as rustc_errors[38e7372a7ffc3815]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7a8d42db1658 - <rustc_errors[38e7372a7ffc3815]::DiagCtxt>::span_bug::<rustc_span[6007e8e04ffa0b28]::span_encoding::Span, alloc[dd6d785e9c2bdfe3]::string::String>
  19:     0x7a8d42db97ed - rustc_middle[e034bcf58dc9044a]::util::bug::opt_span_bug_fmt::<rustc_span[6007e8e04ffa0b28]::span_encoding::Span>::{closure#0}
  20:     0x7a8d42db981a - rustc_middle[e034bcf58dc9044a]::ty::context::tls::with_opt::<rustc_middle[e034bcf58dc9044a]::util::bug::opt_span_bug_fmt<rustc_span[6007e8e04ffa0b28]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7a8d42db503b - rustc_middle[e034bcf58dc9044a]::ty::context::tls::with_context_opt::<rustc_middle[e034bcf58dc9044a]::ty::context::tls::with_opt<rustc_middle[e034bcf58dc9044a]::util::bug::opt_span_bug_fmt<rustc_span[6007e8e04ffa0b28]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7a8d42db4d47 - rustc_middle[e034bcf58dc9044a]::util::bug::span_bug_fmt::<rustc_span[6007e8e04ffa0b28]::span_encoding::Span>
  23:     0x7a8d447bd498 - rustc_pattern_analysis[b816e39839f8fe6e]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[b816e39839f8fe6e]::rustc::RustcPatCtxt>::{closure#0}
  24:     0x7a8d447b9606 - rustc_pattern_analysis[b816e39839f8fe6e]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[b816e39839f8fe6e]::rustc::RustcPatCtxt>::{closure#0}
  25:     0x7a8d447b9606 - rustc_pattern_analysis[b816e39839f8fe6e]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[b816e39839f8fe6e]::rustc::RustcPatCtxt>::{closure#0}
  26:     0x7a8d4417a480 - rustc_pattern_analysis[b816e39839f8fe6e]::analyze_match
  27:     0x7a8d40fc8b35 - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor>::is_let_irrefutable
  28:     0x7a8d40fc3350 - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  29:     0x7a8d40fc296d - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  30:     0x7a8d40fc2eaf - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  31:     0x7a8d40fc296d - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  32:     0x7a8d40fc3827 - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  33:     0x7a8d40fc296d - <rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::MatchVisitor as rustc_middle[e034bcf58dc9044a]::thir::visit::Visitor>::visit_expr
  34:     0x7a8d43d1b2ad - rustc_mir_build[639bcfbd6b56c353]::thir::pattern::check_match::check_match
  35:     0x7a8d43d1ae9f - rustc_query_impl[49829c95e283b62a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[49829c95e283b62a]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7a8d43d11b87 - rustc_query_system[43632b3ed5a17eb7]::query::plumbing::try_execute_query::<rustc_query_impl[49829c95e283b62a]::DynamicConfig<rustc_query_system[43632b3ed5a17eb7]::query::caches::VecCache<rustc_span[6007e8e04ffa0b28]::def_id::LocalDefId, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[49829c95e283b62a]::plumbing::QueryCtxt, false>
  37:     0x7a8d43d11815 - rustc_query_impl[49829c95e283b62a]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7a8d43d24093 - rustc_mir_build[639bcfbd6b56c353]::build::mir_build
  39:     0x7a8d43d23751 - rustc_query_impl[49829c95e283b62a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[49829c95e283b62a]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 8usize]>>
  40:     0x7a8d43c38d31 - rustc_query_system[43632b3ed5a17eb7]::query::plumbing::try_execute_query::<rustc_query_impl[49829c95e283b62a]::DynamicConfig<rustc_query_system[43632b3ed5a17eb7]::query::caches::VecCache<rustc_span[6007e8e04ffa0b28]::def_id::LocalDefId, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[49829c95e283b62a]::plumbing::QueryCtxt, false>
  41:     0x7a8d43c3884c - rustc_query_impl[49829c95e283b62a]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7a8d44225b9a - rustc_mir_build[639bcfbd6b56c353]::check_unsafety::check_unsafety
  43:     0x7a8d44225937 - rustc_query_impl[49829c95e283b62a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[49829c95e283b62a]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 0usize]>>
  44:     0x7a8d44230067 - rustc_query_system[43632b3ed5a17eb7]::query::plumbing::try_execute_query::<rustc_query_impl[49829c95e283b62a]::DynamicConfig<rustc_query_system[43632b3ed5a17eb7]::query::caches::VecCache<rustc_span[6007e8e04ffa0b28]::def_id::LocalDefId, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[49829c95e283b62a]::plumbing::QueryCtxt, false>
  45:     0x7a8d4422fc93 - rustc_query_impl[49829c95e283b62a]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  46:     0x7a8d4422c085 - rustc_interface[83f8b168dbc5b1b5]::passes::analysis
  47:     0x7a8d4422b195 - rustc_query_impl[49829c95e283b62a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[49829c95e283b62a]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 1usize]>>
  48:     0x7a8d447a5f25 - rustc_query_system[43632b3ed5a17eb7]::query::plumbing::try_execute_query::<rustc_query_impl[49829c95e283b62a]::DynamicConfig<rustc_query_system[43632b3ed5a17eb7]::query::caches::SingleCache<rustc_middle[e034bcf58dc9044a]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[49829c95e283b62a]::plumbing::QueryCtxt, false>
  49:     0x7a8d447a5c89 - rustc_query_impl[49829c95e283b62a]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  50:     0x7a8d4467b919 - rustc_interface[83f8b168dbc5b1b5]::interface::run_compiler::<core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>, rustc_driver_impl[f3f4779df6407916]::run_compiler::{closure#0}>::{closure#1}
  51:     0x7a8d4463e067 - std[579020d2760f34a5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[83f8b168dbc5b1b5]::util::run_in_thread_with_globals<rustc_interface[83f8b168dbc5b1b5]::util::run_in_thread_pool_with_globals<rustc_interface[83f8b168dbc5b1b5]::interface::run_compiler<core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>, rustc_driver_impl[f3f4779df6407916]::run_compiler::{closure#0}>::{closure#1}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>::{closure#0}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>
  52:     0x7a8d4463de2a - <<std[579020d2760f34a5]::thread::Builder>::spawn_unchecked_<rustc_interface[83f8b168dbc5b1b5]::util::run_in_thread_with_globals<rustc_interface[83f8b168dbc5b1b5]::util::run_in_thread_pool_with_globals<rustc_interface[83f8b168dbc5b1b5]::interface::run_compiler<core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>, rustc_driver_impl[f3f4779df6407916]::run_compiler::{closure#0}>::{closure#1}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>::{closure#0}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[83e4cb43580d14f1]::result::Result<(), rustc_span[6007e8e04ffa0b28]::ErrorGuaranteed>>::{closure#2} as core[83e4cb43580d14f1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7a8d45de5a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e4c94566de61594
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/alloc/src/boxed.rs:2022:9
  54:     0x7a8d45de5a1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3a5b2acb8225662e
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/alloc/src/boxed.rs:2022:9
  55:     0x7a8d45de5a1b - std::sys::pal::unix::thread::Thread::new::thread_start::h1b84f76802dc5e80
                               at /rustc/803e33a4460c82581bd01d4008d0f44aef1ddfe8/library/std/src/sys/pal/unix/thread.rs:108:17
  56:     0x7a8d45b8355a - <unknown>
  57:     0x7a8d45c00a3c - <unknown>
  58:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (803e33a44 2024-04-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_match] match-checking `main`
#1 [mir_built] building MIR for `main`
#2 [check_unsafety] unsafety-checking `main`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0261, E0308.
For more information about an error, try `rustc --explain E0261`.

```

</p>
</details>

### LINKED ISSUE #124262: ICE: `expected wide pointer extra data (e.g. slice length or trait object vtable)`
snippet:
````rust
struct Foo(<&[fn()] as ::core::ops::Deref>::Target);
const _: *const Foo = 0 as _;


````

Version information
````
rustc 1.79.0-nightly (290d79241 2024-04-22)
binary: rustc
commit-hash: 290d792411566c94273e5d1a980a1ab91f1d950b
commit-date: 2024-04-22
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2021`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0106]: missing lifetime specifier
 --> /tmp/icemaker_global_tempdir.1nBNEtZmd8hU/rustc_testrunner_tmpdir_reporting.YScR49rloxcZ/mvce.rs:1:13
  |
1 | struct Foo(<&[fn()] as ::core::ops::Deref>::Target);
  |             ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 | struct Foo<'a>(<&'a [fn()] as ::core::ops::Deref>::Target);
  |           ++++   ++

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.1nBNEtZmd8hU/rustc_testrunner_tmpdir_reporting.YScR49rloxcZ/mvce.rs:2:30
  |
2 | const _: *const Foo = 0 as _;
  |                              ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.1nBNEtZmd8hU/rustc_testrunner_tmpdir_reporting.YScR49rloxcZ/mvce.rs`

error: internal compiler error: compiler/rustc_const_eval/src/interpret/place.rs:37:17: expected wide pointer extra data (e.g. slice length or trait object vtable)

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/place.rs:37:17:
Box<dyn Any>
stack backtrace:
   0:     0x7d2e63191935 - std::backtrace_rs::backtrace::libunwind::trace::h26e1fa40e8cb8736
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7d2e63191935 - std::backtrace_rs::backtrace::trace_unsynchronized::h859af531c2f619a1
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7d2e63191935 - std::sys_common::backtrace::_print_fmt::h770ada6f33df9a23
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7d2e63191935 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1202620471ff2013
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7d2e631e0a6b - core::fmt::rt::Argument::fmt::h1d7f69a8f0bb037c
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/core/src/fmt/rt.rs:165:63
   5:     0x7d2e631e0a6b - core::fmt::write::h2cfd50c1c61a678b
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/core/src/fmt/mod.rs:1157:21
   6:     0x7d2e631864bf - std::io::Write::write_fmt::h68244818dfe9446a
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/io/mod.rs:1832:15
   7:     0x7d2e6319170e - std::sys_common::backtrace::_print::hb0df927864ffa3c4
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7d2e6319170e - std::sys_common::backtrace::print::hb29ea7496634044b
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7d2e63194079 - std::panicking::default_hook::{{closure}}::hcfcc8ff96a30a9c7
  10:     0x7d2e63193dbd - std::panicking::default_hook::h8bb790ee0d607409
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/panicking.rs:298:9
  11:     0x7d2e5fa3227c - std[37c8ccdab8a3c0d8]::panicking::update_hook::<alloc[34ed19a5ff888b12]::boxed::Box<rustc_driver_impl[480b09937bfb0708]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7d2e63194776 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h11842aeeeb09579f
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/alloc/src/boxed.rs:2036:9
  13:     0x7d2e63194776 - std::panicking::rust_panic_with_hook::h2039ccc53629d416
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/panicking.rs:799:13
  14:     0x7d2e5fa62584 - std[37c8ccdab8a3c0d8]::panicking::begin_panic::<rustc_errors[6444c462ca5918aa]::ExplicitBug>::{closure#0}
  15:     0x7d2e5fa5ef36 - std[37c8ccdab8a3c0d8]::sys_common::backtrace::__rust_end_short_backtrace::<std[37c8ccdab8a3c0d8]::panicking::begin_panic<rustc_errors[6444c462ca5918aa]::ExplicitBug>::{closure#0}, !>
  16:     0x7d2e5fa5a506 - std[37c8ccdab8a3c0d8]::panicking::begin_panic::<rustc_errors[6444c462ca5918aa]::ExplicitBug>
  17:     0x7d2e5fa6b801 - <rustc_errors[6444c462ca5918aa]::diagnostic::BugAbort as rustc_errors[6444c462ca5918aa]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7d2e5ff1155c - rustc_middle[d30f97e255128713]::util::bug::opt_span_bug_fmt::<rustc_span[128fa906eb8a1c67]::span_encoding::Span>::{closure#0}
  19:     0x7d2e5fef982a - rustc_middle[d30f97e255128713]::ty::context::tls::with_opt::<rustc_middle[d30f97e255128713]::util::bug::opt_span_bug_fmt<rustc_span[128fa906eb8a1c67]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7d2e5fef96cb - rustc_middle[d30f97e255128713]::ty::context::tls::with_context_opt::<rustc_middle[d30f97e255128713]::ty::context::tls::with_opt<rustc_middle[d30f97e255128713]::util::bug::opt_span_bug_fmt<rustc_span[128fa906eb8a1c67]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7d2e5e28fe70 - rustc_middle[d30f97e255128713]::util::bug::bug_fmt
  22:     0x7d2e5f9ef2ec - <rustc_const_eval[6d96b92d4bade795]::interpret::validity::ValidityVisitor<rustc_const_eval[6d96b92d4bade795]::const_eval::machine::CompileTimeInterpreter>>::check_wide_ptr_meta
  23:     0x7d2e60e6ecdd - <rustc_const_eval[6d96b92d4bade795]::interpret::validity::ValidityVisitor<rustc_const_eval[6d96b92d4bade795]::const_eval::machine::CompileTimeInterpreter> as rustc_const_eval[6d96b92d4bade795]::interpret::visitor::ValueVisitor<rustc_const_eval[6d96b92d4bade795]::const_eval::machine::CompileTimeInterpreter>>::visit_value
  24:     0x7d2e5ef85621 - rustc_const_eval[6d96b92d4bade795]::const_eval::eval_queries::eval_to_allocation_raw_provider
  25:     0x7d2e616b56b6 - rustc_query_impl[4316bc259f8ef16e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4316bc259f8ef16e]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 24usize]>>
  26:     0x7d2e616b4ed6 - rustc_query_system[8cff448a052401bd]::query::plumbing::try_execute_query::<rustc_query_impl[4316bc259f8ef16e]::DynamicConfig<rustc_query_system[8cff448a052401bd]::query::caches::DefaultCache<rustc_middle[d30f97e255128713]::ty::ParamEnvAnd<rustc_middle[d30f97e255128713]::mir::interpret::GlobalId>, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[4316bc259f8ef16e]::plumbing::QueryCtxt, false>
  27:     0x7d2e616b4aac - rustc_query_impl[4316bc259f8ef16e]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7d2e616b460c - rustc_middle[d30f97e255128713]::query::plumbing::query_get_at::<rustc_query_system[8cff448a052401bd]::query::caches::DefaultCache<rustc_middle[d30f97e255128713]::ty::ParamEnvAnd<rustc_middle[d30f97e255128713]::mir::interpret::GlobalId>, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 24usize]>>>
  29:     0x7d2e616b2afc - rustc_const_eval[6d96b92d4bade795]::const_eval::eval_queries::eval_to_const_value_raw_provider
  30:     0x7d2e616b2a76 - rustc_query_impl[4316bc259f8ef16e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4316bc259f8ef16e]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 24usize]>>
  31:     0x7d2e616b4e99 - rustc_query_system[8cff448a052401bd]::query::plumbing::try_execute_query::<rustc_query_impl[4316bc259f8ef16e]::DynamicConfig<rustc_query_system[8cff448a052401bd]::query::caches::DefaultCache<rustc_middle[d30f97e255128713]::ty::ParamEnvAnd<rustc_middle[d30f97e255128713]::mir::interpret::GlobalId>, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[4316bc259f8ef16e]::plumbing::QueryCtxt, false>
  32:     0x7d2e616b49ac - rustc_query_impl[4316bc259f8ef16e]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7d2e61043e10 - <rustc_middle[d30f97e255128713]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[6f20a5ebf44cea1c]::check_crate::{closure#3}>::{closure#0}
  34:     0x7d2e6104243c - rustc_hir_analysis[6f20a5ebf44cea1c]::check_crate
  35:     0x7d2e613163ba - rustc_interface[ffee9ea60ef965c3]::passes::analysis
  36:     0x7d2e61315f15 - rustc_query_impl[4316bc259f8ef16e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4316bc259f8ef16e]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7d2e61b8dca5 - rustc_query_system[8cff448a052401bd]::query::plumbing::try_execute_query::<rustc_query_impl[4316bc259f8ef16e]::DynamicConfig<rustc_query_system[8cff448a052401bd]::query::caches::SingleCache<rustc_middle[d30f97e255128713]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4316bc259f8ef16e]::plumbing::QueryCtxt, false>
  38:     0x7d2e61b8da09 - rustc_query_impl[4316bc259f8ef16e]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7d2e619ea753 - rustc_interface[ffee9ea60ef965c3]::interface::run_compiler::<core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>, rustc_driver_impl[480b09937bfb0708]::run_compiler::{closure#0}>::{closure#1}
  40:     0x7d2e619d8627 - std[37c8ccdab8a3c0d8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ffee9ea60ef965c3]::util::run_in_thread_with_globals<rustc_interface[ffee9ea60ef965c3]::util::run_in_thread_pool_with_globals<rustc_interface[ffee9ea60ef965c3]::interface::run_compiler<core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>, rustc_driver_impl[480b09937bfb0708]::run_compiler::{closure#0}>::{closure#1}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>::{closure#0}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>
  41:     0x7d2e619d83ea - <<std[37c8ccdab8a3c0d8]::thread::Builder>::spawn_unchecked_<rustc_interface[ffee9ea60ef965c3]::util::run_in_thread_with_globals<rustc_interface[ffee9ea60ef965c3]::util::run_in_thread_pool_with_globals<rustc_interface[ffee9ea60ef965c3]::interface::run_compiler<core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>, rustc_driver_impl[480b09937bfb0708]::run_compiler::{closure#0}>::{closure#1}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>::{closure#0}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d851a872a27282f9]::result::Result<(), rustc_span[128fa906eb8a1c67]::ErrorGuaranteed>>::{closure#2} as core[d851a872a27282f9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7d2e6319e60b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8fcfbedcc7bc1020
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/alloc/src/boxed.rs:2022:9
  43:     0x7d2e6319e60b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb725f441e1474916
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/alloc/src/boxed.rs:2022:9
  44:     0x7d2e6319e60b - std::sys::pal::unix::thread::Thread::new::thread_start::h34c8a550ac2bc24c
                               at /rustc/290d792411566c94273e5d1a980a1ab91f1d950b/library/std/src/sys/pal/unix/thread.rs:108:17
  45:     0x7d2e62f3c55a - <unknown>
  46:     0x7d2e62fb9a3c - <unknown>
  47:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (290d79241 2024-04-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dump-mir-dir=dir

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `_`
#1 [eval_to_const_value_raw] simplifying constant for the type system `_`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0106, E0601.
For more information about an error, try `rustc --explain E0106`.

```

</p>
</details>

### LINKED ISSUE #125155: ICE: `elem.index() < self.domain_size`
auto-reduced (treereduce-rust):
````rust
enum NestedEnum {
    First,
    Second,
    Third
}
enum Enum {
    Variant2(Option<*mut &'a &'b ()>)
}


fn foo(x: Enum) -> isize {
    match x {
      Enum::Variant2(NestedEnum::Third) => 4,  
    }
}

````

original:
````rust
#![allow(dead_code)]

enum NestedEnum {
    First,
    Second,
    Third
}
enum Enum {
    Variant1(bool),
    Variant2(Option<*mut &'a &'b ()>)
}

#[inline(never)]
fn foo(x: Enum) -> isize {
    match x {
        Enum::Variant1(true) => 1,
        Enum::Variant1(false) => 2,
        Enum::Variant2(NestedEnum::Second) => 3,
        Enum::Variant2(NestedEnum::Third) => 4,
        Enum::Variant2(NestedEnum::First) => 5
    }
}

fn main() {
    assert_eq!(foo(Enum::Variant2(NestedEnum::Third)), 4);
}

````

Version information
````
rustc 1.80.0-nightly (9e7aff794 2024-05-15)
binary: rustc
commit-hash: 9e7aff794539aa040362f4424eb29207449ffce0
commit-date: 2024-05-15
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: expected identifier, found `,`
 --> /tmp/icemaker_global_tempdir.atr7tKB0tvNE/rustc_testrunner_tmpdir_reporting.a4Uxzxxnly6f/mvce.rs:9:5
  |
9 |     ,
  |     ^
  |     |
  |     expected identifier
  |     help: remove this comma

error[E0261]: use of undeclared lifetime name `'a`
  --> /tmp/icemaker_global_tempdir.atr7tKB0tvNE/rustc_testrunner_tmpdir_reporting.a4Uxzxxnly6f/mvce.rs:10:27
   |
8  | enum Enum {
   |          - help: consider introducing lifetime `'a` here: `<'a>`
9  |     ,
10 |     Variant2(Option<*mut &'a &'b ()>)
   |                           ^^ undeclared lifetime

error[E0261]: use of undeclared lifetime name `'b`
  --> /tmp/icemaker_global_tempdir.atr7tKB0tvNE/rustc_testrunner_tmpdir_reporting.a4Uxzxxnly6f/mvce.rs:10:31
   |
8  | enum Enum {
   |          - help: consider introducing lifetime `'b` here: `<'b>`
9  |     ,
10 |     Variant2(Option<*mut &'a &'b ()>)
   |                               ^^ undeclared lifetime

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.atr7tKB0tvNE/rustc_testrunner_tmpdir_reporting.a4Uxzxxnly6f/mvce.rs:22:2
   |
22 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.atr7tKB0tvNE/rustc_testrunner_tmpdir_reporting.a4Uxzxxnly6f/mvce.rs`

thread 'rustc' panicked at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/compiler/rustc_index/src/bit_set.rs:188:9:
assertion failed: elem.index() < self.domain_size
stack backtrace:
   0:     0x7507130fee55 - std::backtrace_rs::backtrace::libunwind::trace::hc82148572bca43ce
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7507130fee55 - std::backtrace_rs::backtrace::trace_unsynchronized::h9b6c0021060334e8
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7507130fee55 - std::sys_common::backtrace::_print_fmt::hdf50e160c2606d9a
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7507130fee55 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd89105eb919743fa
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x75071314e16b - core::fmt::rt::Argument::fmt::h299039627f9699b8
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/core/src/fmt/rt.rs:165:63
   5:     0x75071314e16b - core::fmt::write::h90d4bcf0308a6921
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/core/src/fmt/mod.rs:1169:21
   6:     0x7507130f3b3f - std::io::Write::write_fmt::h971d4bf5135c0400
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/io/mod.rs:1835:15
   7:     0x7507130fec2e - std::sys_common::backtrace::_print::h0249ba9e007e0890
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7507130fec2e - std::sys_common::backtrace::print::h512af02446eaf912
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x750713101649 - std::panicking::default_hook::{{closure}}::hd7eed3dbeb3b0e1b
  10:     0x75071310138d - std::panicking::default_hook::hc22637f42e887b27
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/panicking.rs:298:9
  11:     0x75070faf4d5f - std[e1f444a3457101b2]::panicking::update_hook::<alloc[dde3ecb08ca6e715]::boxed::Box<rustc_driver_impl[5e1c2d2058911521]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x750713101d7b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h53851f315593fb6e
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/alloc/src/boxed.rs:2036:9
  13:     0x750713101d7b - std::panicking::rust_panic_with_hook::h5e0b74345c48df96
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/panicking.rs:799:13
  14:     0x750713101abb - std::panicking::begin_panic_handler::{{closure}}::h35a2f90e39b3450a
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/panicking.rs:656:13
  15:     0x7507130ff319 - std::sys_common::backtrace::__rust_end_short_backtrace::hc74b426b89ea2072
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x750713101827 - rust_begin_unwind
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/panicking.rs:652:5
  17:     0x75071314a733 - core::panicking::panic_fmt::h64193357920b31af
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/core/src/panicking.rs:72:14
  18:     0x75071314a7dc - core::panicking::panic::hd8eed21f3f9250e7
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/core/src/panicking.rs:146:5
  19:     0x750711533c1b - rustc_pattern_analysis[51b46f04f23eb7fd]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[51b46f04f23eb7fd]::rustc::RustcPatCtxt>::{closure#0}
  20:     0x75071152f314 - rustc_pattern_analysis[51b46f04f23eb7fd]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[51b46f04f23eb7fd]::rustc::RustcPatCtxt>::{closure#0}
  21:     0x75071153da54 - rustc_pattern_analysis[51b46f04f23eb7fd]::analyze_match
  22:     0x75070e3d5869 - <rustc_mir_build[36a8aa01da2a74cf]::thir::pattern::check_match::MatchVisitor as rustc_middle[2ad1b0c79c7e2a2b]::thir::visit::Visitor>::visit_expr
  23:     0x75070e3d4d8d - <rustc_mir_build[36a8aa01da2a74cf]::thir::pattern::check_match::MatchVisitor as rustc_middle[2ad1b0c79c7e2a2b]::thir::visit::Visitor>::visit_expr
  24:     0x75070e3d5c64 - <rustc_mir_build[36a8aa01da2a74cf]::thir::pattern::check_match::MatchVisitor as rustc_middle[2ad1b0c79c7e2a2b]::thir::visit::Visitor>::visit_expr
  25:     0x75070e3d4d8d - <rustc_mir_build[36a8aa01da2a74cf]::thir::pattern::check_match::MatchVisitor as rustc_middle[2ad1b0c79c7e2a2b]::thir::visit::Visitor>::visit_expr
  26:     0x75071114470c - rustc_mir_build[36a8aa01da2a74cf]::thir::pattern::check_match::check_match
  27:     0x7507111442df - rustc_query_impl[e4f4655505b9e0b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e4f4655505b9e0b]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 1usize]>>
  28:     0x750711142387 - rustc_query_system[3dc3927fb89859b0]::query::plumbing::try_execute_query::<rustc_query_impl[e4f4655505b9e0b]::DynamicConfig<rustc_query_system[3dc3927fb89859b0]::query::caches::VecCache<rustc_span[22bf4ef945b61209]::def_id::LocalDefId, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e4f4655505b9e0b]::plumbing::QueryCtxt, false>
  29:     0x750711142015 - rustc_query_impl[e4f4655505b9e0b]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  30:     0x75071114d5cb - rustc_mir_build[36a8aa01da2a74cf]::build::mir_build
  31:     0x75071114cc8e - rustc_query_impl[e4f4655505b9e0b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e4f4655505b9e0b]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7507115511f1 - rustc_query_system[3dc3927fb89859b0]::query::plumbing::try_execute_query::<rustc_query_impl[e4f4655505b9e0b]::DynamicConfig<rustc_query_system[3dc3927fb89859b0]::query::caches::VecCache<rustc_span[22bf4ef945b61209]::def_id::LocalDefId, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e4f4655505b9e0b]::plumbing::QueryCtxt, false>
  33:     0x750711550d0c - rustc_query_impl[e4f4655505b9e0b]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  34:     0x75071113e5dc - rustc_mir_build[36a8aa01da2a74cf]::check_unsafety::check_unsafety
  35:     0x75071113e36f - rustc_query_impl[e4f4655505b9e0b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e4f4655505b9e0b]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 0usize]>>
  36:     0x75071113d3dd - rustc_query_system[3dc3927fb89859b0]::query::plumbing::try_execute_query::<rustc_query_impl[e4f4655505b9e0b]::DynamicConfig<rustc_query_system[3dc3927fb89859b0]::query::caches::VecCache<rustc_span[22bf4ef945b61209]::def_id::LocalDefId, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[e4f4655505b9e0b]::plumbing::QueryCtxt, false>
  37:     0x75071113d097 - rustc_query_impl[e4f4655505b9e0b]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  38:     0x75071199a31b - rustc_interface[bf6b16ed275f9a93]::passes::analysis
  39:     0x75071199941b - rustc_query_impl[e4f4655505b9e0b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e4f4655505b9e0b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 1usize]>>
  40:     0x750711baef65 - rustc_query_system[3dc3927fb89859b0]::query::plumbing::try_execute_query::<rustc_query_impl[e4f4655505b9e0b]::DynamicConfig<rustc_query_system[3dc3927fb89859b0]::query::caches::SingleCache<rustc_middle[2ad1b0c79c7e2a2b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e4f4655505b9e0b]::plumbing::QueryCtxt, false>
  41:     0x750711baecc9 - rustc_query_impl[e4f4655505b9e0b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  42:     0x750711a33e8e - rustc_interface[bf6b16ed275f9a93]::interface::run_compiler::<core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>, rustc_driver_impl[5e1c2d2058911521]::run_compiler::{closure#0}>::{closure#1}
  43:     0x750711a1f4c9 - std[e1f444a3457101b2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bf6b16ed275f9a93]::util::run_in_thread_with_globals<rustc_interface[bf6b16ed275f9a93]::util::run_in_thread_pool_with_globals<rustc_interface[bf6b16ed275f9a93]::interface::run_compiler<core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>, rustc_driver_impl[5e1c2d2058911521]::run_compiler::{closure#0}>::{closure#1}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>::{closure#0}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>
  44:     0x750711a1f276 - <<std[e1f444a3457101b2]::thread::Builder>::spawn_unchecked_<rustc_interface[bf6b16ed275f9a93]::util::run_in_thread_with_globals<rustc_interface[bf6b16ed275f9a93]::util::run_in_thread_pool_with_globals<rustc_interface[bf6b16ed275f9a93]::interface::run_compiler<core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>, rustc_driver_impl[5e1c2d2058911521]::run_compiler::{closure#0}>::{closure#1}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>::{closure#0}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[621fd6879f29e550]::result::Result<(), rustc_span[22bf4ef945b61209]::ErrorGuaranteed>>::{closure#2} as core[621fd6879f29e550]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x75071310bc1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f48e858c823da76
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/alloc/src/boxed.rs:2022:9
  46:     0x75071310bc1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he41c381165ad67aa
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/alloc/src/boxed.rs:2022:9
  47:     0x75071310bc1b - std::sys::pal::unix::thread::Thread::new::thread_start::hed17c0eaf3bcb9d0
                               at /rustc/9e7aff794539aa040362f4424eb29207449ffce0/library/std/src/sys/pal/unix/thread.rs:108:17
  48:     0x75070c8a955a - <unknown>
  49:     0x75070c926a3c - <unknown>
  50:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (9e7aff794 2024-05-15) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_match] match-checking `foo`
#1 [mir_built] building MIR for `foo`
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0261, E0601.
For more information about an error, try `rustc --explain E0261`.

```

</p>
</details>

### LINKED ISSUE #125888: ICE: Unexpected type for constructor `Variant(1)`
I try to reduce the code of #125155 and find the ice changed. 
Maybe duplicated with #120601 and #124004, but I think the code here is cleaner.

### Code

```Rust
enum NestedEnum {
    First,
    Second,
}

enum Enum {
    Variant(*const &'a ()),
}

fn foo(x: Enum) {
    match x {
        Enum::Variant(NestedEnum::Second) => {}
    }
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (6f3df08aa 2024-05-30)
binary: rustc
commit-hash: 6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4
commit-date: 2024-05-30
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

<details><summary><strong>Error output</strong></summary>
<p>

```
error[E0261]: use of undeclared lifetime name `'a`
 --> src/main.rs:7:21
  |
6 | enum Enum {
  |          - help: consider introducing lifetime `'a` here: `<'a>`
7 |     Variant(*const &'a ()),
  |                     ^^ undeclared lifetime

error: internal compiler error: compiler/rustc_pattern_analysis/src/rustc.rs:236:22: Unexpected type for constructor `Variant(1)`: *const &'{erased} ()

thread 'rustc' panicked at compiler/rustc_pattern_analysis/src/rustc.rs:236:22:
Box<dyn Any>
stack backtrace:
   0:     0x7b7b729f9dfb - std::backtrace_rs::backtrace::libunwind::trace::h7d54eacc88008817
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7b7b729f9dfb - std::backtrace_rs::backtrace::trace_unsynchronized::h1b384a49badbbbf0
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7b7b729f9dfb - std::backtrace::Backtrace::create::ha4add90f9a9ffcbb
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/backtrace.rs:331:13
   3:     0x7b7b729f9d45 - std::backtrace::Backtrace::force_capture::he209e47860813be1
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/backtrace.rs:312:9
   4:     0x7b7b6f13432a - std[362b16250628d2ae]::panicking::update_hook::<alloc[36c56ba0e371072d]::boxed::Box<rustc_driver_impl[33236637d18b51d0]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7b7b72a14c2b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1df67ed3fceec998
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/alloc/src/boxed.rs:2077:9
   6:     0x7b7b72a14c2b - std::panicking::rust_panic_with_hook::h7947d7d7856ccdd3
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/panicking.rs:799:13
   7:     0x7b7b6f164644 - std[362b16250628d2ae]::panicking::begin_panic::<rustc_errors[59a72888fd61d3ce]::ExplicitBug>::{closure#0}
   8:     0x7b7b6f160f76 - std[362b16250628d2ae]::sys_common::backtrace::__rust_end_short_backtrace::<std[362b16250628d2ae]::panicking::begin_panic<rustc_errors[59a72888fd61d3ce]::ExplicitBug>::{closure#0}, !>
   9:     0x7b7b6f15c2c6 - std[362b16250628d2ae]::panicking::begin_panic::<rustc_errors[59a72888fd61d3ce]::ExplicitBug>
  10:     0x7b7b6f16dae1 - <rustc_errors[59a72888fd61d3ce]::diagnostic::BugAbort as rustc_errors[59a72888fd61d3ce]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7b7b6f64d31c - rustc_middle[d10142e9169e5087]::util::bug::opt_span_bug_fmt::<rustc_span[6ca5b1b463c06ed1]::span_encoding::Span>::{closure#0}
  12:     0x7b7b6f63055a - rustc_middle[d10142e9169e5087]::ty::context::tls::with_opt::<rustc_middle[d10142e9169e5087]::util::bug::opt_span_bug_fmt<rustc_span[6ca5b1b463c06ed1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7b7b6f6303fb - rustc_middle[d10142e9169e5087]::ty::context::tls::with_context_opt::<rustc_middle[d10142e9169e5087]::ty::context::tls::with_opt<rustc_middle[d10142e9169e5087]::util::bug::opt_span_bug_fmt<rustc_span[6ca5b1b463c06ed1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7b7b6d9eb1a0 - rustc_middle[d10142e9169e5087]::util::bug::bug_fmt
  15:     0x7b7b70e1d8cb - rustc_pattern_analysis[8a3e0b8a86761bb1]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[8a3e0b8a86761bb1]::rustc::RustcPatCtxt>::{closure#0}
  16:     0x7b7b70e178f3 - rustc_pattern_analysis[8a3e0b8a86761bb1]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[8a3e0b8a86761bb1]::rustc::RustcPatCtxt>::{closure#0}
  17:     0x7b7b70e0e704 - rustc_pattern_analysis[8a3e0b8a86761bb1]::analyze_match
  18:     0x7b7b6daa9d42 - <rustc_mir_build[bacafdeaff7b19ff]::thir::pattern::check_match::MatchVisitor as rustc_middle[d10142e9169e5087]::thir::visit::Visitor>::visit_expr
  19:     0x7b7b6daa92bd - <rustc_mir_build[bacafdeaff7b19ff]::thir::pattern::check_match::MatchVisitor as rustc_middle[d10142e9169e5087]::thir::visit::Visitor>::visit_expr
  20:     0x7b7b6daaa134 - <rustc_mir_build[bacafdeaff7b19ff]::thir::pattern::check_match::MatchVisitor as rustc_middle[d10142e9169e5087]::thir::visit::Visitor>::visit_expr
  21:     0x7b7b6daa92bd - <rustc_mir_build[bacafdeaff7b19ff]::thir::pattern::check_match::MatchVisitor as rustc_middle[d10142e9169e5087]::thir::visit::Visitor>::visit_expr
  22:     0x7b7b70873686 - rustc_mir_build[bacafdeaff7b19ff]::thir::pattern::check_match::check_match
  23:     0x7b7b7087326d - rustc_query_impl[a4ad450ce75c81f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a4ad450ce75c81f3]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 1usize]>>
  24:     0x7b7b70ad1b0e - rustc_query_system[466e502815dde757]::query::plumbing::try_execute_query::<rustc_query_impl[a4ad450ce75c81f3]::DynamicConfig<rustc_query_system[466e502815dde757]::query::caches::VecCache<rustc_span[6ca5b1b463c06ed1]::def_id::LocalDefId, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a4ad450ce75c81f3]::plumbing::QueryCtxt, true>
  25:     0x7b7b706e5aad - rustc_query_impl[a4ad450ce75c81f3]::query_impl::check_match::get_query_incr::__rust_end_short_backtrace
  26:     0x7b7b7087afc9 - rustc_mir_build[bacafdeaff7b19ff]::build::mir_build
  27:     0x7b7b7087a68e - rustc_query_impl[a4ad450ce75c81f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a4ad450ce75c81f3]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7b7b70c69776 - rustc_query_system[466e502815dde757]::query::plumbing::try_execute_query::<rustc_query_impl[a4ad450ce75c81f3]::DynamicConfig<rustc_query_system[466e502815dde757]::query::caches::VecCache<rustc_span[6ca5b1b463c06ed1]::def_id::LocalDefId, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a4ad450ce75c81f3]::plumbing::QueryCtxt, true>
  29:     0x7b7b70ad985c - rustc_query_impl[a4ad450ce75c81f3]::query_impl::mir_built::get_query_incr::__rust_end_short_backtrace
  30:     0x7b7b70c76aa6 - rustc_mir_build[bacafdeaff7b19ff]::check_unsafety::check_unsafety
  31:     0x7b7b70c76847 - rustc_query_impl[a4ad450ce75c81f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a4ad450ce75c81f3]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 0usize]>>
  32:     0x7b7b70ad7c61 - rustc_query_system[466e502815dde757]::query::plumbing::try_execute_query::<rustc_query_impl[a4ad450ce75c81f3]::DynamicConfig<rustc_query_system[466e502815dde757]::query::caches::VecCache<rustc_span[6ca5b1b463c06ed1]::def_id::LocalDefId, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[a4ad450ce75c81f3]::plumbing::QueryCtxt, true>
  33:     0x7b7b70ad777f - rustc_query_impl[a4ad450ce75c81f3]::query_impl::check_unsafety::get_query_incr::__rust_end_short_backtrace
  34:     0x7b7b70c7d05b - rustc_interface[749128fb2397a9e]::passes::analysis
  35:     0x7b7b70c7c15b - rustc_query_impl[a4ad450ce75c81f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a4ad450ce75c81f3]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7b7b7156640a - rustc_query_system[466e502815dde757]::query::plumbing::try_execute_query::<rustc_query_impl[a4ad450ce75c81f3]::DynamicConfig<rustc_query_system[466e502815dde757]::query::caches::SingleCache<rustc_middle[d10142e9169e5087]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a4ad450ce75c81f3]::plumbing::QueryCtxt, true>
  37:     0x7b7b7156603a - rustc_query_impl[a4ad450ce75c81f3]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  38:     0x7b7b711ee71c - rustc_interface[749128fb2397a9e]::interface::run_compiler::<core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>, rustc_driver_impl[33236637d18b51d0]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7b7b711d97e7 - std[362b16250628d2ae]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[749128fb2397a9e]::util::run_in_thread_with_globals<rustc_interface[749128fb2397a9e]::util::run_in_thread_pool_with_globals<rustc_interface[749128fb2397a9e]::interface::run_compiler<core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>, rustc_driver_impl[33236637d18b51d0]::run_compiler::{closure#0}>::{closure#1}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>::{closure#0}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>
  40:     0x7b7b711d95aa - <<std[362b16250628d2ae]::thread::Builder>::spawn_unchecked_<rustc_interface[749128fb2397a9e]::util::run_in_thread_with_globals<rustc_interface[749128fb2397a9e]::util::run_in_thread_pool_with_globals<rustc_interface[749128fb2397a9e]::interface::run_compiler<core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>, rustc_driver_impl[33236637d18b51d0]::run_compiler::{closure#0}>::{closure#1}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>::{closure#0}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5f8c442e32640be5]::result::Result<(), rustc_span[6ca5b1b463c06ed1]::ErrorGuaranteed>>::{closure#2} as core[5f8c442e32640be5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7b7b72a1ebfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc666fad739fe414e
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/alloc/src/boxed.rs:2063:9
  42:     0x7b7b72a1ebfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcd8201f663299c4b
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/alloc/src/boxed.rs:2063:9
  43:     0x7b7b72a1ebfb - std::sys::pal::unix::thread::Thread::new::thread_start::h4f248c4f539e2e55
                               at /rustc/6f3df08aadf71e8d4bf7e49f5dc10dfa6f254cb4/library/std/src/sys/pal/unix/thread.rs:108:17
  44:     0x7b7b727caded - <unknown>
  45:     0x7b7b7284e0dc - <unknown>
  46:                0x0 - <unknown>


rustc version: 1.80.0-nightly (6f3df08aa 2024-05-30)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_match] match-checking `foo`
#1 [mir_built] building MIR for `foo`
#2 [check_unsafety] unsafety-checking `foo`
#3 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

### LINKED ISSUE #125992: ICE: `polonius loan scopes differ from NLL borrow scopes`
auto-reduced (treereduce-rust):
````rust
#![feature(inherent_associated_types)]

type Function = for<'a> fn(&'a i32) -> S<'a>::P;

struct S<'a>(&'a ());

impl<'a> S {
    type P = &'a i32;
}

fn ret_ref_local<'e>() -> &'e i32 {
    let f: Function = |x| x;

    let local = 0;
    f(&local)
}


````

original:
````rust
#![feature(inherent_associated_types)]

type Function = for<'a> fn(&'a i32) -> S<'a>::P;

struct S<'a>(&'a ());

impl<'a> S<{ fn bar(&self) {} }> {
    type P = &'a i32;
}

fn ret_ref_local<'e>() -> &'e i32 {
    let f: Function = |x| x;

    let local = 0;
    f(&local)
}

fn main() {}

````

Version information
````
rustc 1.80.0-nightly (44701e070 2024-06-04)
binary: rustc
commit-hash: 44701e070c8453df10df1984944258018ac21610
commit-date: 2024-06-04
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zpolonius=next`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0726]: implicit elided lifetime not allowed here
 --> /tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs:7:10
  |
7 | impl<'a> S {
  |          ^ expected lifetime parameter
  |
help: indicate the anonymous lifetime
  |
7 | impl<'a> S<'_> {
  |           ++++

warning: the feature `inherent_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs:1:12
  |
1 | #![feature(inherent_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs:16:2
   |
16 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs`

error: lifetime may not live long enough
  --> /tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs:12:27
   |
12 |     let f: Function = |x| x;
   |                        -- ^ returning this value requires that `'1` must outlive `'2`
   |                        ||
   |                        |return type of closure is &'2 i32
   |                        has type `&'1 i32`

thread 'rustc' panicked at compiler/rustc_borrowck/src/dataflow.rs:418:13:
assertion `left == right` failed: polonius loan scopes differ from NLL borrow scopes, for body /tmp/icemaker_global_tempdir.j09zTpiMeB10/rustc_testrunner_tmpdir_reporting.6BA5IqLroDn9/mvce.rs:11:1: 16:2 (#0)
  left: {bb0[16]: [bw0]}
 right: {bb2[0]: [bw0], bb1[0]: [bw0]}
stack backtrace:
   0:     0x78e818c02d45 - std::backtrace_rs::backtrace::libunwind::trace::he27724ab9ba077ae
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x78e818c02d45 - std::backtrace_rs::backtrace::trace_unsynchronized::h8e764d5b7d96c928
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x78e818c02d45 - std::sys_common::backtrace::_print_fmt::h3b015d1dd0132d35
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x78e818c02d45 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5d1014338738062e
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x78e818c534eb - core::fmt::rt::Argument::fmt::h60a123cf0371ab3c
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/core/src/fmt/rt.rs:165:63
   5:     0x78e818c534eb - core::fmt::write::h83e73de2f751b956
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/core/src/fmt/mod.rs:1168:21
   6:     0x78e818bf7acf - std::io::Write::write_fmt::hc31dd1d0eb90cbf9
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/io/mod.rs:1835:15
   7:     0x78e818c02b1e - std::sys_common::backtrace::_print::hc36ef09893adcde7
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x78e818c02b1e - std::sys_common::backtrace::print::hff629cd88cbfd188
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x78e818c05559 - std::panicking::default_hook::{{closure}}::h9d71a1d8151e4423
  10:     0x78e818c052fa - std::panicking::default_hook::h8b6ebfe091a035c5
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/panicking.rs:298:9
  11:     0x78e81537c3ff - std[b127da73d53c36b6]::panicking::update_hook::<alloc[38d31d85db1a046c]::boxed::Box<rustc_driver_impl[45af4acf2cc78f06]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x78e818c05c8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hae8bef6fc4aacccb
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/alloc/src/boxed.rs:2077:9
  13:     0x78e818c05c8b - std::panicking::rust_panic_with_hook::h1bc8a1911adf5d38
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/panicking.rs:799:13
  14:     0x78e818c05a04 - std::panicking::begin_panic_handler::{{closure}}::hd4b966e58e008e0c
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/panicking.rs:664:13
  15:     0x78e818c03209 - std::sys_common::backtrace::__rust_end_short_backtrace::hef31567bf2c1bb30
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x78e818c05737 - rust_begin_unwind
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/panicking.rs:652:5
  17:     0x78e818c4fa83 - core::panicking::panic_fmt::h00800dd6c6e334a4
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/core/src/panicking.rs:72:14
  18:     0x78e818c5007f - core::panicking::assert_failed_inner::h377882419abf48f3
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/core/src/panicking.rs:403:23
  19:     0x78e8150b5347 - core[680d2829b3045f23]::panicking::assert_failed::<indexmap[18e14f81f0668936]::map::IndexMap<rustc_middle[349545b1af2ab62b]::mir::Location, alloc[38d31d85db1a046c]::vec::Vec<rustc_borrowck[46ee65c78ca61b43]::dataflow::BorrowIndex>, core[680d2829b3045f23]::hash::BuildHasherDefault<rustc_hash[338ae66e5de4b634]::FxHasher>>, indexmap[18e14f81f0668936]::map::IndexMap<rustc_middle[349545b1af2ab62b]::mir::Location, alloc[38d31d85db1a046c]::vec::Vec<rustc_borrowck[46ee65c78ca61b43]::dataflow::BorrowIndex>, core[680d2829b3045f23]::hash::BuildHasherDefault<rustc_hash[338ae66e5de4b634]::FxHasher>>>
  20:     0x78e817759932 - rustc_borrowck[46ee65c78ca61b43]::do_mir_borrowck
  21:     0x78e81773dbbe - rustc_query_impl[b18d7974ec639165]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b18d7974ec639165]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[349545b1af2ab62b]::query::erase::Erased<[u8; 8usize]>>
  22:     0x78e816b867b1 - rustc_query_system[6a27861ca80f3c7f]::query::plumbing::try_execute_query::<rustc_query_impl[b18d7974ec639165]::DynamicConfig<rustc_query_system[6a27861ca80f3c7f]::query::caches::VecCache<rustc_span[97aaaa995e2f92fe]::def_id::LocalDefId, rustc_middle[349545b1af2ab62b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[b18d7974ec639165]::plumbing::QueryCtxt, false>
  23:     0x78e816b8620d - rustc_query_impl[b18d7974ec639165]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  24:     0x78e816b64904 - rustc_interface[411eb75ca6615201]::passes::analysis
  25:     0x78e816b63a95 - rustc_query_impl[b18d7974ec639165]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b18d7974ec639165]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[349545b1af2ab62b]::query::erase::Erased<[u8; 1usize]>>
  26:     0x78e8175da965 - rustc_query_system[6a27861ca80f3c7f]::query::plumbing::try_execute_query::<rustc_query_impl[b18d7974ec639165]::DynamicConfig<rustc_query_system[6a27861ca80f3c7f]::query::caches::SingleCache<rustc_middle[349545b1af2ab62b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b18d7974ec639165]::plumbing::QueryCtxt, false>
  27:     0x78e8175da6cf - rustc_query_impl[b18d7974ec639165]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  28:     0x78e8173db092 - rustc_interface[411eb75ca6615201]::interface::run_compiler::<core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>, rustc_driver_impl[45af4acf2cc78f06]::run_compiler::{closure#0}>::{closure#1}
  29:     0x78e8173c8589 - std[b127da73d53c36b6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[411eb75ca6615201]::util::run_in_thread_with_globals<rustc_interface[411eb75ca6615201]::util::run_in_thread_pool_with_globals<rustc_interface[411eb75ca6615201]::interface::run_compiler<core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>, rustc_driver_impl[45af4acf2cc78f06]::run_compiler::{closure#0}>::{closure#1}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>::{closure#0}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>
  30:     0x78e8173c8342 - <<std[b127da73d53c36b6]::thread::Builder>::spawn_unchecked_<rustc_interface[411eb75ca6615201]::util::run_in_thread_with_globals<rustc_interface[411eb75ca6615201]::util::run_in_thread_pool_with_globals<rustc_interface[411eb75ca6615201]::interface::run_compiler<core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>, rustc_driver_impl[45af4acf2cc78f06]::run_compiler::{closure#0}>::{closure#1}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>::{closure#0}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[680d2829b3045f23]::result::Result<(), rustc_span[97aaaa995e2f92fe]::ErrorGuaranteed>>::{closure#2} as core[680d2829b3045f23]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x78e818c0fc7b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4ef5945c2429999c
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/alloc/src/boxed.rs:2063:9
  32:     0x78e818c0fc7b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5dd441b71d9c7ff9
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/alloc/src/boxed.rs:2063:9
  33:     0x78e818c0fc7b - std::sys::pal::unix::thread::Thread::new::thread_start::hac40c46ba02b627e
                               at /rustc/44701e070c8453df10df1984944258018ac21610/library/std/src/sys/pal/unix/thread.rs:108:17
  34:     0x78e8120a6ded - <unknown>
  35:     0x78e81212a0dc - <unknown>
  36:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.80.0-nightly (44701e070 2024-06-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polonius=next -Z dump-mir-dir=dir

query stack during panic:
#0 [mir_borrowck] borrow-checking `ret_ref_local`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0601, E0726.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

@rustbot label +F-inherent_associated_types

### LINKED ISSUE #126648: ICE: `Unexpected type for 'Ref' constructor: *const &'{erased} ()`
snippet:
````rust
struct Outest(*const &'a ());

fn make() -> Outest {}

fn main() {
    if let Outest("foo") = make() {}
}


````

Version information
````
rustc 1.81.0-nightly (dd104ef16 2024-06-18)
binary: rustc
commit-hash: dd104ef16315e2387fe94e8c43eb5a66e3dbd660
commit-date: 2024-06-18
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0261]: use of undeclared lifetime name `'a`
 --> /tmp/icemaker_global_tempdir.TgpW6JrktGaA/rustc_testrunner_tmpdir_reporting.7eRm4vVFAtEm/mvce.rs:1:23
  |
1 | struct Outest(*const &'a ());
  |              -        ^^ undeclared lifetime
  |              |
  |              help: consider introducing lifetime `'a` here: `<'a>`

error[E0308]: mismatched types
 --> /tmp/icemaker_global_tempdir.TgpW6JrktGaA/rustc_testrunner_tmpdir_reporting.7eRm4vVFAtEm/mvce.rs:3:14
  |
3 | fn make() -> Outest {}
  |    ----      ^^^^^^ expected `Outest`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression

error: internal compiler error: compiler/rustc_pattern_analysis/src/rustc.rs:241:22: Unexpected type for `Ref` constructor: *const &'{erased} ()

thread 'rustc' panicked at compiler/rustc_pattern_analysis/src/rustc.rs:241:22:
Box<dyn Any>
stack backtrace:
   0:     0x731938db2935 - std::backtrace_rs::backtrace::libunwind::trace::h24001de405a19c29
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x731938db2935 - std::backtrace_rs::backtrace::trace_unsynchronized::h52cb31f58d87e795
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x731938db2935 - std::sys::backtrace::_print_fmt::ha0a4a385e6305dc9
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/sys/backtrace.rs:68:5
   3:     0x731938db2935 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2ac9d261fff2c5c
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/sys/backtrace.rs:44:22
   4:     0x731938e034db - core::fmt::rt::Argument::fmt::h5dd96858711c38a5
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/core/src/fmt/rt.rs:165:63
   5:     0x731938e034db - core::fmt::write::h9137aaeb0715e137
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/core/src/fmt/mod.rs:1168:21
   6:     0x731938da751f - std::io::Write::write_fmt::h3d543f59fe71748a
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/io/mod.rs:1835:15
   7:     0x731938db270e - std::sys::backtrace::_print::h4a7caef85c10fa0d
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/sys/backtrace.rs:47:5
   8:     0x731938db270e - std::sys::backtrace::print::hf1ff8c4b50b84478
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/sys/backtrace.rs:34:9
   9:     0x731938db5149 - std::panicking::default_hook::{{closure}}::h76d1d90acd3a4473
  10:     0x731938db4eec - std::panicking::default_hook::h2a49ac4243aa5140
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/panicking.rs:292:9
  11:     0x7319354acd2f - std[49f1045a74567fa7]::panicking::update_hook::<alloc[5df14249ca9505f2]::boxed::Box<rustc_driver_impl[db4e8f03b5696bb3]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x731938db5a6f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h25f6191eb839a16b
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/alloc/src/boxed.rs:2076:9
  13:     0x731938db5a6f - std::panicking::rust_panic_with_hook::hc9c5e69e405d5d6c
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/panicking.rs:804:13
  14:     0x7319354dd7e1 - std[49f1045a74567fa7]::panicking::begin_panic::<rustc_errors[f1c452f0768a3196]::ExplicitBug>::{closure#0}
  15:     0x7319354da596 - std[49f1045a74567fa7]::sys::backtrace::__rust_end_short_backtrace::<std[49f1045a74567fa7]::panicking::begin_panic<rustc_errors[f1c452f0768a3196]::ExplicitBug>::{closure#0}, !>
  16:     0x7319354da276 - std[49f1045a74567fa7]::panicking::begin_panic::<rustc_errors[f1c452f0768a3196]::ExplicitBug>
  17:     0x7319354e6d31 - <rustc_errors[f1c452f0768a3196]::diagnostic::BugAbort as rustc_errors[f1c452f0768a3196]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7319359bf58c - rustc_middle[1b5811ec6d2edbd2]::util::bug::opt_span_bug_fmt::<rustc_span[b2dab8d5db9c06d4]::span_encoding::Span>::{closure#0}
  19:     0x7319359a8ada - rustc_middle[1b5811ec6d2edbd2]::ty::context::tls::with_opt::<rustc_middle[1b5811ec6d2edbd2]::util::bug::opt_span_bug_fmt<rustc_span[b2dab8d5db9c06d4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7319359a895b - rustc_middle[1b5811ec6d2edbd2]::ty::context::tls::with_context_opt::<rustc_middle[1b5811ec6d2edbd2]::ty::context::tls::with_opt<rustc_middle[1b5811ec6d2edbd2]::util::bug::opt_span_bug_fmt<rustc_span[b2dab8d5db9c06d4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x73193346c250 - rustc_middle[1b5811ec6d2edbd2]::util::bug::bug_fmt
  22:     0x731937004d48 - rustc_pattern_analysis[9ec12d2f5d12a80]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[9ec12d2f5d12a80]::rustc::RustcPatCtxt>::{closure#0}
  23:     0x731936ffee69 - rustc_pattern_analysis[9ec12d2f5d12a80]::usefulness::compute_exhaustiveness_and_usefulness::<rustc_pattern_analysis[9ec12d2f5d12a80]::rustc::RustcPatCtxt>::{closure#0}
  24:     0x731936ff92bc - rustc_pattern_analysis[9ec12d2f5d12a80]::analyze_match
  25:     0x731933de2804 - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor>::is_let_irrefutable
  26:     0x731933ddd05d - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  27:     0x731933ddc69d - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  28:     0x731933ddcbc9 - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  29:     0x731933ddc69d - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  30:     0x731933ddd504 - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  31:     0x731933ddc69d - <rustc_mir_build[10942160e2184657]::thir::pattern::check_match::MatchVisitor as rustc_middle[1b5811ec6d2edbd2]::thir::visit::Visitor>::visit_expr
  32:     0x731936bf41be - rustc_mir_build[10942160e2184657]::thir::pattern::check_match::check_match
  33:     0x731936bf3dd5 - rustc_query_impl[ed5fbfae2043678b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ed5fbfae2043678b]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 1usize]>>
  34:     0x731936bf347f - rustc_query_system[f4d6069fb68f5c49]::query::plumbing::try_execute_query::<rustc_query_impl[ed5fbfae2043678b]::DynamicConfig<rustc_query_system[f4d6069fb68f5c49]::query::caches::VecCache<rustc_span[b2dab8d5db9c06d4]::def_id::LocalDefId, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ed5fbfae2043678b]::plumbing::QueryCtxt, false>
  35:     0x731936bf31dd - rustc_query_impl[ed5fbfae2043678b]::query_impl::check_match::get_query_non_incr::__rust_end_short_backtrace
  36:     0x731936c0bcc8 - rustc_mir_build[10942160e2184657]::build::mir_build
  37:     0x731936c0b38e - rustc_query_impl[ed5fbfae2043678b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ed5fbfae2043678b]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 8usize]>>
  38:     0x731936bbe0ae - rustc_query_system[f4d6069fb68f5c49]::query::plumbing::try_execute_query::<rustc_query_impl[ed5fbfae2043678b]::DynamicConfig<rustc_query_system[f4d6069fb68f5c49]::query::caches::VecCache<rustc_span[b2dab8d5db9c06d4]::def_id::LocalDefId, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ed5fbfae2043678b]::plumbing::QueryCtxt, false>
  39:     0x731936bbdbcd - rustc_query_impl[ed5fbfae2043678b]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  40:     0x731936bff048 - rustc_mir_build[10942160e2184657]::check_unsafety::check_unsafety
  41:     0x731936bfedf1 - rustc_query_impl[ed5fbfae2043678b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ed5fbfae2043678b]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 0usize]>>
  42:     0x731936bfdeea - rustc_query_system[f4d6069fb68f5c49]::query::plumbing::try_execute_query::<rustc_query_impl[ed5fbfae2043678b]::DynamicConfig<rustc_query_system[f4d6069fb68f5c49]::query::caches::VecCache<rustc_span[b2dab8d5db9c06d4]::def_id::LocalDefId, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ed5fbfae2043678b]::plumbing::QueryCtxt, false>
  43:     0x731936bfdb0b - rustc_query_impl[ed5fbfae2043678b]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  44:     0x731937203d2a - rustc_interface[c6ece38a3a908c28]::passes::analysis
  45:     0x731937202e07 - rustc_query_impl[ed5fbfae2043678b]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ed5fbfae2043678b]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 1usize]>>
  46:     0x7319376360a5 - rustc_query_system[f4d6069fb68f5c49]::query::plumbing::try_execute_query::<rustc_query_impl[ed5fbfae2043678b]::DynamicConfig<rustc_query_system[f4d6069fb68f5c49]::query::caches::SingleCache<rustc_middle[1b5811ec6d2edbd2]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ed5fbfae2043678b]::plumbing::QueryCtxt, false>
  47:     0x731937635e0f - rustc_query_impl[ed5fbfae2043678b]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  48:     0x7319374dd3d2 - rustc_interface[c6ece38a3a908c28]::interface::run_compiler::<core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>, rustc_driver_impl[db4e8f03b5696bb3]::run_compiler::{closure#0}>::{closure#1}
  49:     0x7319374b54c9 - std[49f1045a74567fa7]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[c6ece38a3a908c28]::util::run_in_thread_with_globals<rustc_interface[c6ece38a3a908c28]::util::run_in_thread_pool_with_globals<rustc_interface[c6ece38a3a908c28]::interface::run_compiler<core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>, rustc_driver_impl[db4e8f03b5696bb3]::run_compiler::{closure#0}>::{closure#1}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>::{closure#0}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>
  50:     0x7319374b527a - <<std[49f1045a74567fa7]::thread::Builder>::spawn_unchecked_<rustc_interface[c6ece38a3a908c28]::util::run_in_thread_with_globals<rustc_interface[c6ece38a3a908c28]::util::run_in_thread_pool_with_globals<rustc_interface[c6ece38a3a908c28]::interface::run_compiler<core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>, rustc_driver_impl[db4e8f03b5696bb3]::run_compiler::{closure#0}>::{closure#1}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>::{closure#0}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3c5d2e85893f84f8]::result::Result<(), rustc_span[b2dab8d5db9c06d4]::ErrorGuaranteed>>::{closure#2} as core[3c5d2e85893f84f8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:     0x731938dbf8eb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haf6c6ed15ef7c4b2
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/alloc/src/boxed.rs:2062:9
  52:     0x731938dbf8eb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3648257e1237816c
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/alloc/src/boxed.rs:2062:9
  53:     0x731938dbf8eb - std::sys::pal::unix::thread::Thread::new::thread_start::h379e689399d87cbf
                               at /rustc/dd104ef16315e2387fe94e8c43eb5a66e3dbd660/library/std/src/sys/pal/unix/thread.rs:108:17
  54:     0x731938b58ded - <unknown>
  55:     0x731938bdc0dc - <unknown>
  56:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (dd104ef16 2024-06-18) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_match] match-checking `main`
#1 [mir_built] building MIR for `main`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0261, E0308.
For more information about an error, try `rustc --explain E0261`.

```

</p>
</details>

### LINKED ISSUE #126666: ICE: `assertion left == right failed` in `rustc_const_eval/src/interpret/cast.rs`
### Code

(hand-reduced & simplified)

```Rust
#![feature(const_mut_refs)]
#![feature(const_refs_to_static)]
#![feature(object_safe_for_dispatch)]

struct Meh {
    x: &'static dyn UnsafeCell,
}

const MUH: Meh = Meh {
    x: &mut *(&READONLY as *const _ as *mut _),
};

static READONLY: i32 = 0;

trait UnsafeCell<'a> {}

pub fn main() {}
```

- crate attribute `object_safe_for_dispatch` added from original code.

<details><summary><strong>(original)</strong></summary>
<p>

```Rust
#![feature(const_mut_refs)]
#![feature(const_refs_to_static)]

use std::cell::UnsafeCell;

struct Meh {
    x: &'static UnsafeCell<i32>,
}

const MUH: Meh = Meh {
    x: &mut *(&READONLY as *const _ as *mut _),
};

static READONLY: i32 = 0;

pub fn main() {}


#![feature(type_alias_impl_trait)]

struct call_me;

type ReturnType<'a> = impl std::future::Future<Output = u32> + 'a;
type FnType = impl Fn(&u32) -> ReturnType;

impl std::ops::Deref for call_me {
    type Target = FnType;
    
    fn deref(&self) -> &Self::Target {
        fn inner(val: &u32) -> ReturnType {
            async move {
                *val * 2
            }
        }
    
        &inner
    }
}


trait UnsafeCell<'a, 'b, T> {
    async fn foo(&'a self) -> (Self::Target, &'BAR T);
}
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (8fcd4dd08 2024-06-18)
binary: rustc
commit-hash: 8fcd4dd08e2ba3e922d917d819ba0be066bdb005
commit-date: 2024-06-18
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Error output

Command: `rustc`

```
error[E0106]: missing lifetime specifier
 --> r_cast214_DE5E554.rs:6:21
  |
6 |     x: &'static dyn UnsafeCell,
  |                     ^^^^^^^^^^ expected named lifetime parameter
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
6 |     x: &'static dyn for<'a> UnsafeCell<'a>,
  |                     +++++++           ++++
help: consider introducing a named lifetime parameter
  |
5 ~ struct Meh<'a> {
6 ~     x: &'static dyn UnsafeCell<'a>,
  |
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/cast.rs:214:13:
assertion `left == right` failed
  left: Size(8 bytes)
 right: Size(16 bytes)
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<rustc_abi::Size, rustc_abi::Size>
   4: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeMachine>>::cast
   5: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeMachine>>::statement
   6: rustc_const_eval::const_eval::eval_queries::eval_to_allocation_raw_provider
      [... omitted 2 frames ...]
   7: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::mir::interpret::GlobalId>, rustc_middle::query::erase::Erased<[u8; 24]>>>
   8: rustc_const_eval::const_eval::eval_queries::eval_to_const_value_raw_provider
      [... omitted 2 frames ...]
   9: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_hir_analysis::check_crate::{closure#3}>::{closure#0}
  10: rustc_hir_analysis::check_crate
  11: rustc_interface::passes::run_required_analyses
  12: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  13: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  14: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Volumes/T7/workspace/240615_100chaos_tree_combine_typ/icefiles/rustc-ice-2024-06-19T06_25_41-29848.txt` to your bug report

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `MUH`
#1 [eval_to_const_value_raw] simplifying constant for the type system `MUH`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0106`.
```

</p>
</details>

### Note
- ICE location: `compiler/rustc_const_eval/src/interpret/cast.rs L214`
  https://github.com/rust-lang/rust/blob/8fcd4dd08e2ba3e922d917d819ba0be066bdb005/compiler/rustc_const_eval/src/interpret/cast.rs#L209-L218

@rustbot label +F-const_mut_refs +F-const_refs_to_static +F-object_safe_for_dispatch

### LINKED ISSUE #127266: ICE: `write_immediate_to_mplace: invalid Scalar layout:` with feature `const_mut_refs` and `const_refs_to_static`
### Code

```Rust
#![feature(const_mut_refs)]
#![feature(const_refs_to_static)]

struct Meh {
    x: &'static dyn UnsafeCell,
}

const MUH: Meh = Meh {
    x: &mut *(READONLY as *mut _),
};

static READONLY: i32 = 0;

trait UnsafeCell<'a> {}

pub fn main() {}
```

### Related Issue
#126666 The origin of seed file before mutation. Line `x: &mut *(&READONLY as *const _ as *mut _),` mutated to `x: &mut *(READONLY as *mut _),`
#126272 is also another ICE with similar ice message`write_immediate_to_mplace:`, but that requires incomplete features

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (6292b2af6 2024-07-02)
binary: rustc
commit-hash: 6292b2af620dbd771ebb687c3a93c69ba8f97268
commit-date: 2024-07-02
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Error output

```
error[E0106]: missing lifetime specifier
 --> ./126666-1.rs:5:21
  |
5 |     x: &'static dyn UnsafeCell,
  |                     ^^^^^^^^^^ expected named lifetime parameter
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
5 |     x: &'static dyn for<'a> UnsafeCell<'a>,
  |                     +++++++           ++++
help: consider introducing a named lifetime parameter
  |
4 ~ struct Meh<'a> {
5 ~     x: &'static dyn UnsafeCell<'a>,
  |
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_const_eval/src/interpret/place.rs:698:21: write_immediate_to_mplace: invalid Scalar layout: TyAndLayout {
                                    ty: &dyn UnsafeCell<'_>,
                                    layout: Layout {
                                        size: Size(16 bytes),
                                        align: AbiAndPrefAlign {
                                            abi: Align(8 bytes),
                                            pref: Align(8 bytes),
                                        },
                                        abi: ScalarPair(
                                            Initialized {
                                                value: Pointer(
                                                    AddressSpace(
                                                        0,
                                                    ),
                                                ),
                                                valid_range: 1..=18446744073709551615,
                                            },
                                            Initialized {
                                                value: Pointer(
                                                    AddressSpace(
                                                        0,
                                                    ),
                                                ),
                                                valid_range: 1..=18446744073709551615,
                                            },
                                        ),
                                        fields: Arbitrary {
                                            offsets: [
                                                Size(0 bytes),
                                                Size(8 bytes),
                                            ],
                                            memory_index: [
                                                0,
                                                1,
                                            ],
                                        },
                                        largest_niche: Some(
                                            Niche {
                                                offset: Size(0 bytes),
                                                value: Pointer(
                                                    AddressSpace(
                                                        0,
                                                    ),
                                                ),
                                                valid_range: 1..=18446744073709551615,
                                            },
                                        ),
                                        variants: Single {
                                            index: 0,
                                        },
                                        max_repr_align: None,
                                        unadjusted_abi_align: Align(8 bytes),
                                    },
                                }
  --> ./126666-1.rs:8:18
   |
8  |   const MUH: Meh = Meh {
   |  __________________^
9  | |     x: &mut *(READONLY as *mut _),
10 | | };
   | |_^

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/place.rs:698:21:
Box<dyn Any>
stack backtrace:
   0:        0x10c0f2d93 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9393e218f71d31cf
   1:        0x10c13e17b - core::fmt::write::h1271a75a7bae980c
   2:        0x10c0e8c3e - std::io::Write::write_fmt::h8270e961acbabe61
   3:        0x10c0f2b81 - std::sys::backtrace::print::h04e4916ebe343f6e
   4:        0x10c0f5959 - std::panicking::default_hook::{{closure}}::hc9df26d29e0f9e5a
   5:        0x10c0f56da - std::panicking::default_hook::h1026261fa8b9d0a8
   6:        0x1153dd0ac - std[26270defc80edaa9]::panicking::update_hook::<alloc[98df03226deedbda]::boxed::Box<rustc_driver_impl[708b2ec565622c48]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x10c0f6699 - std::panicking::rust_panic_with_hook::hf72d729757d375cc
   8:        0x115451347 - std[26270defc80edaa9]::panicking::begin_panic::<rustc_errors[d689bc684dcf46ea]::ExplicitBug>::{closure#0}
   9:        0x11543d189 - std[26270defc80edaa9]::sys::backtrace::__rust_end_short_backtrace::<std[26270defc80edaa9]::panicking::begin_panic<rustc_errors[d689bc684dcf46ea]::ExplicitBug>::{closure#0}, !>
  10:        0x119e6e199 - std[26270defc80edaa9]::panicking::begin_panic::<rustc_errors[d689bc684dcf46ea]::ExplicitBug>
  11:        0x115463486 - <rustc_errors[d689bc684dcf46ea]::diagnostic::BugAbort as rustc_errors[d689bc684dcf46ea]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:        0x1152774e1 - <rustc_errors[d689bc684dcf46ea]::DiagCtxtHandle>::span_bug::<rustc_span[2de937bbddea0bd8]::span_encoding::Span, alloc[98df03226deedbda]::string::String>
  13:        0x1152a62a8 - rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt::<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}
  14:        0x1152a72a7 - rustc_middle[8094f41c293b336b]::ty::context::tls::with_opt::<rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:        0x115294155 - rustc_middle[8094f41c293b336b]::ty::context::tls::with_context_opt::<rustc_middle[8094f41c293b336b]::ty::context::tls::with_opt<rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:        0x119e5c672 - rustc_middle[8094f41c293b336b]::util::bug::span_bug_fmt::<rustc_span[2de937bbddea0bd8]::span_encoding::Span>
  17:        0x115342805 - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::write_immediate_to_mplace_no_validate
  18:        0x1153420e6 - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::write_immediate_no_validate::<rustc_const_eval[396cbee6e07433a6]::interpret::place::PlaceTy>
  19:        0x1153719ce - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::copy_op_no_validate::<rustc_const_eval[396cbee6e07433a6]::interpret::operand::OpTy, rustc_const_eval[396cbee6e07433a6]::interpret::place::PlaceTy>
  20:        0x115347955 - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::statement
  21:        0x115362ed8 - rustc_const_eval[396cbee6e07433a6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  22:        0x116a9aaec - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>
  23:        0x116a4fbae - <rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>)>>::call_once
  24:        0x1168b3c0d - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  25:        0x116ac59dc - rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  26:        0x115293752 - rustc_middle[8094f41c293b336b]::query::plumbing::query_get_at::<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>>
  27:        0x11535f700 - rustc_const_eval[396cbee6e07433a6]::const_eval::eval_queries::eval_to_const_value_raw_provider
  28:        0x116a9b48c - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>
  29:        0x116a5501e - <rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>)>>::call_once
  30:        0x1168b3c0d - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  31:        0x116ac628c - rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  32:        0x115656e41 - <rustc_middle[8094f41c293b336b]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[af0a509199b1bc4b]::check_crate::{closure#3}>::{closure#0}
  33:        0x1157ac0ec - rustc_hir_analysis[af0a509199b1bc4b]::check_crate
  34:        0x115d53df7 - rustc_interface[eab3c32d3b591e25]::passes::run_required_analyses
  35:        0x115d563a0 - rustc_interface[eab3c32d3b591e25]::passes::analysis
  36:        0x116a9d4ec - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>
  37:        0x11687bfbe - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::SingleCache<rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  38:        0x116aa7a47 - rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:        0x115386857 - <rustc_interface[eab3c32d3b591e25]::queries::QueryResult<&rustc_middle[8094f41c293b336b]::ty::context::GlobalCtxt>>::enter::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  40:        0x1153e4465 - rustc_interface[eab3c32d3b591e25]::interface::run_compiler::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}
  41:        0x1153caee1 - std[26270defc80edaa9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>
  42:        0x1153eaff6 - <<std[26270defc80edaa9]::thread::Builder>::spawn_unchecked_<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:        0x10c0ff83b - std::sys::pal::unix::thread::Thread::new::thread_start::hfcd29f6cc9954faa
  44:     0x7ff801f5318b - __pthread_start

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/240701-nightly/rustc-ice-2024-07-03T09_46_03-68509.txt` to your bug report

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `MUH`
#1 [eval_to_const_value_raw] simplifying constant for the type system `MUH`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0106`.
```

</p>
</details>

@rustbot label +F-const_mut_refs +F-const_refs_to_static

### LINKED ISSUE #127268: ICE: `type mismatch when copying!`
### Code

```Rust
//@ check-pass

struct Slice(&'reborrow [&'static [u8]]);

static MAP: Slice = Slice(&[
    b"CloseEvent" as &'static [u8],
]);

fn main() {}
```

(original seed)
https://github.com/rust-lang/rust/blob/d68fe4eaa81305b53cdddc2339e8efdc2aa1e013/tests/ui/nll/issue-55288.rs#L1-L9

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (6292b2af6 2024-07-02)
binary: rustc
commit-hash: 6292b2af620dbd771ebb687c3a93c69ba8f97268
commit-date: 2024-07-02
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Error output

```
error[E0261]: use of undeclared lifetime name `'reborrow`
 --> ./64489B3C9F806D45C54D5CFF302A6E7678F61B90E9746D6EC53E396C5DBD906C.rs:3:15
  |
3 | struct Slice(&'reborrow [&'static [u8]]);
  |             - ^^^^^^^^^ undeclared lifetime
  |             |
  |             help: consider introducing lifetime `'reborrow` here: `<'reborrow>`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_const_eval/src/interpret/place.rs:852:13: type mismatch when copying!
                                src: &[&[u8]; 1],
                                dest: &[&[u8]]
 --> ./64489B3C9F806D45C54D5CFF302A6E7678F61B90E9746D6EC53E396C5DBD906C.rs:5:21
  |
5 |   static MAP: Slice = Slice(&[
  |  _____________________^
6 | |     b"CloseEvent" as &'static [u8],
7 | | ]);
  | |__^

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/place.rs:852:13:
Box<dyn Any>
stack backtrace:
   0:        0x1100f2d93 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9393e218f71d31cf
   1:        0x11013e17b - core::fmt::write::h1271a75a7bae980c
   2:        0x1100e8c3e - std::io::Write::write_fmt::h8270e961acbabe61
   3:        0x1100f2b81 - std::sys::backtrace::print::h04e4916ebe343f6e
   4:        0x1100f5959 - std::panicking::default_hook::{{closure}}::hc9df26d29e0f9e5a
   5:        0x1100f56da - std::panicking::default_hook::h1026261fa8b9d0a8
   6:        0x1193dd0ac - std[26270defc80edaa9]::panicking::update_hook::<alloc[98df03226deedbda]::boxed::Box<rustc_driver_impl[708b2ec565622c48]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x1100f6699 - std::panicking::rust_panic_with_hook::hf72d729757d375cc
   8:        0x119451347 - std[26270defc80edaa9]::panicking::begin_panic::<rustc_errors[d689bc684dcf46ea]::ExplicitBug>::{closure#0}
   9:        0x11943d189 - std[26270defc80edaa9]::sys::backtrace::__rust_end_short_backtrace::<std[26270defc80edaa9]::panicking::begin_panic<rustc_errors[d689bc684dcf46ea]::ExplicitBug>::{closure#0}, !>
  10:        0x11de6e199 - std[26270defc80edaa9]::panicking::begin_panic::<rustc_errors[d689bc684dcf46ea]::ExplicitBug>
  11:        0x119463486 - <rustc_errors[d689bc684dcf46ea]::diagnostic::BugAbort as rustc_errors[d689bc684dcf46ea]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:        0x1192774e1 - <rustc_errors[d689bc684dcf46ea]::DiagCtxtHandle>::span_bug::<rustc_span[2de937bbddea0bd8]::span_encoding::Span, alloc[98df03226deedbda]::string::String>
  13:        0x1192a62a8 - rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt::<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}
  14:        0x1192a72a7 - rustc_middle[8094f41c293b336b]::ty::context::tls::with_opt::<rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:        0x119294155 - rustc_middle[8094f41c293b336b]::ty::context::tls::with_context_opt::<rustc_middle[8094f41c293b336b]::ty::context::tls::with_opt<rustc_middle[8094f41c293b336b]::util::bug::opt_span_bug_fmt<rustc_span[2de937bbddea0bd8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:        0x11de5c672 - rustc_middle[8094f41c293b336b]::util::bug::span_bug_fmt::<rustc_span[2de937bbddea0bd8]::span_encoding::Span>
  17:        0x119371d72 - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::copy_op_no_validate::<rustc_const_eval[396cbee6e07433a6]::interpret::operand::OpTy, rustc_const_eval[396cbee6e07433a6]::interpret::place::PlaceTy>
  18:        0x119347955 - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::statement
  19:        0x11936189b - rustc_const_eval[396cbee6e07433a6]::const_eval::eval_queries::eval_static_initializer_provider
  20:        0x11aa9b412 - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_static_initializer::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 16usize]>>
  21:        0x11aa5459e - <rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_static_initializer::dynamic_query::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_span[2de937bbddea0bd8]::def_id::DefId)>>::call_once
  22:        0x11a858319 - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefIdCache<rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  23:        0x11aac5ded - rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_static_initializer::get_query_non_incr::__rust_end_short_backtrace
  24:        0x119656cbb - <rustc_middle[8094f41c293b336b]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[af0a509199b1bc4b]::check_crate::{closure#3}>::{closure#0}
  25:        0x1197ac0ec - rustc_hir_analysis[af0a509199b1bc4b]::check_crate
  26:        0x119d53df7 - rustc_interface[eab3c32d3b591e25]::passes::run_required_analyses
  27:        0x119d563a0 - rustc_interface[eab3c32d3b591e25]::passes::analysis
  28:        0x11aa9d4ec - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>
  29:        0x11a87bfbe - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::SingleCache<rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  30:        0x11aaa7a47 - rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:        0x119386857 - <rustc_interface[eab3c32d3b591e25]::queries::QueryResult<&rustc_middle[8094f41c293b336b]::ty::context::GlobalCtxt>>::enter::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  32:        0x1193e4465 - rustc_interface[eab3c32d3b591e25]::interface::run_compiler::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}
  33:        0x1193caee1 - std[26270defc80edaa9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>
  34:        0x1193eaff6 - <<std[26270defc80edaa9]::thread::Builder>::spawn_unchecked_<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:        0x1100ff83b - std::sys::pal::unix::thread::Thread::new::thread_start::hfcd29f6cc9954faa
  36:     0x7ff801f5318b - __pthread_start

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/240701-nightly/rustc-ice-2024-07-03T10_34_51-69548.txt` to your bug report

query stack during panic:
#0 [eval_static_initializer] evaluating initializer of static `MAP`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0261`.
```

</p>
</details>

### Note
<strong> Ice location: </strong>
https://github.com/rust-lang/rust/blob/6292b2af620dbd771ebb687c3a93c69ba8f97268/compiler/rustc_const_eval/src/interpret/place.rs#L849-L858

### LINKED ISSUE #127304: ICE: `range start index 1 out of range for slice of length 1` in `rustc_const_eval/src/interpret/terminator.rs`
### Code

```Rust
trait Trait<T> {}
impl Trait<u16> for () {}

#![feature(adt_const_params)]

struct MyStr(str);
impl std::marker::ConstParamTy for MyStr {}

fn function_with_my_str<const S: &'static MyStr>() -> &'static MyStr {
    S
}

impl MyStr {
    const fn new(s: &Trait str) -> &'static MyStr {}
}

pub fn main() {
    let f = function_with_my_str::<{ MyStr::new("hello") }>();
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (6292b2af6 2024-07-02)
binary: rustc
commit-hash: 6292b2af620dbd771ebb687c3a93c69ba8f97268
commit-date: 2024-07-02
host: x86_64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Error output

```
error: an inner attribute is not permitted in this context
 --> ./2F705.rs:4:1
  |
4 | #![feature(adt_const_params)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
7 | struct MyStr(str);
  | ------------------ the inner attribute doesn't annotate this struct
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files
help: to annotate the struct, change the attribute from inner to outer style
  |
4 - #![feature(adt_const_params)]
4 + #[feature(adt_const_params)]
  |

error: expected one of `:`, `@`, or `|`, found `)`
  --> ./2F705.rs:15:31
   |
15 |     const fn new(s: &Trait str) -> &'static MyStr {}
   |                               ^ expected one of `:`, `@`, or `|`
   |
   = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a parameter name, give it a type
   |
15 |     const fn new(s: &Trait str: TypeName) -> &'static MyStr {}
   |                               ++++++++++
help: if this is a type, explicitly ignore the parameter name
   |
15 |     const fn new(s: &Trait _: str) -> &'static MyStr {}
   |                            ++

error: expected one of `!`, `(`, `)`, `,`, `::`, or `<`, found `str`
  --> ./2F705.rs:15:28
   |
15 |     const fn new(s: &Trait str) -> &'static MyStr {}
   |                           -^^^ expected one of `!`, `(`, `)`, `,`, `::`, or `<`
   |                           |
   |                           help: missing `,`

error[E0658]: use of unstable library feature 'adt_const_params'
 --> ./2F705.rs:8:6
  |
8 | impl std::marker::ConstParamTy for MyStr {}
  |      ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #95174 <https://github.com/rust-lang/rust/issues/95174> for more information
  = help: add `#![feature(adt_const_params)]` to the crate attributes to enable
  = note: this compiler was built on 2024-07-02; consider upgrading it if it is out of date

error[E0277]: the trait bound `MyStr: Eq` is not satisfied
   --> ./2F705.rs:8:36
    |
8   | impl std::marker::ConstParamTy for MyStr {}
    |                                    ^^^^^ the trait `Eq` is not implemented for `MyStr`
    |
note: required by a bound in `ConstParamTy`
   --> /Users/sal/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/marker.rs:981:47
    |
981 | pub trait ConstParamTy: StructuralPartialEq + Eq {}
    |                                               ^^ required by this bound in `ConstParamTy`
help: consider annotating `MyStr` with `#[derive(Eq)]`
    |
7   + #[derive(Eq)]
8   | struct MyStr(str);
    |

error[E0277]: the type `MyStr` does not `#[derive(PartialEq)]`
   --> ./2F705.rs:8:36
    |
8   | impl std::marker::ConstParamTy for MyStr {}
    |                                    ^^^^^ the trait `StructuralPartialEq` is not implemented for `MyStr`
    |
note: required by a bound in `ConstParamTy`
   --> /Users/sal/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/marker.rs:981:25
    |
981 | pub trait ConstParamTy: StructuralPartialEq + Eq {}
    |                         ^^^^^^^^^^^^^^^^^^^ required by this bound in `ConstParamTy`

error: `&'static MyStr` is forbidden as the type of a const generic parameter
  --> ./2F705.rs:10:34
   |
10 | fn function_with_my_str<const S: &'static MyStr>() -> &'static MyStr {
   |                                  ^^^^^^^^^^^^^^
   |
   = note: the only supported types are integers, `bool` and `char`
help: add `#![feature(adt_const_params)]` to the crate attributes to enable more complex and user defined types
   |
1  + #![feature(adt_const_params)]
   |

warning: trait objects without an explicit `dyn` are deprecated
  --> ./2F705.rs:15:22
   |
15 |     const fn new(s: &Trait str) -> &'static MyStr {}
   |                      ^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
   = note: `#[warn(bare_trait_objects)]` on by default
help: if this is an object-safe trait, use `dyn`
   |
15 |     const fn new(s: &dyn Trait str) -> &'static MyStr {}
   |                      +++

error[E0107]: missing generics for trait `Trait`
  --> ./2F705.rs:15:22
   |
15 |     const fn new(s: &Trait str) -> &'static MyStr {}
   |                      ^^^^^ expected 1 generic argument
   |
note: trait defined here, with 1 generic parameter: `T`
  --> ./2F705.rs:1:7
   |
1  | trait Trait<T> {}
   |       ^^^^^ -
help: add missing generic argument
   |
15 |     const fn new(s: &Trait<T> str) -> &'static MyStr {}
   |                           +++

error[E0308]: mismatched types
  --> ./2F705.rs:15:36
   |
15 |     const fn new(s: &Trait str) -> &'static MyStr {}
   |              ---                   ^^^^^^^^^^^^^^ expected `&MyStr`, found `()`
   |              |
   |              implicitly returns `()` as its body has no tail or `return` expression

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/terminator.rs:133:39:
range start index 2 out of range for slice of length 1
stack backtrace:
   0:        0x1091f2d93 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9393e218f71d31cf
   1:        0x10923e17b - core::fmt::write::h1271a75a7bae980c
   2:        0x1091e8c3e - std::io::Write::write_fmt::h8270e961acbabe61
   3:        0x1091f2b81 - std::sys::backtrace::print::h04e4916ebe343f6e
   4:        0x1091f5959 - std::panicking::default_hook::{{closure}}::hc9df26d29e0f9e5a
   5:        0x1091f56da - std::panicking::default_hook::h1026261fa8b9d0a8
   6:        0x1124dd0ac - std[26270defc80edaa9]::panicking::update_hook::<alloc[98df03226deedbda]::boxed::Box<rustc_driver_impl[708b2ec565622c48]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x1091f6699 - std::panicking::rust_panic_with_hook::hf72d729757d375cc
   8:        0x1091f5ed5 - std::panicking::begin_panic_handler::{{closure}}::h5eb191147adf0e0d
   9:        0x1091f3269 - std::sys::backtrace::__rust_end_short_backtrace::he8eea0af09eba22f
  10:        0x1091f5aec - _rust_begin_unwind
  11:        0x1092594ca - core::panicking::panic_fmt::h403139b1d3f51ed8
  12:        0x109259b36 - core::slice::index::slice_start_index_len_fail::h58e498803150e5af
  13:        0x11244b12a - <rustc_const_eval[396cbee6e07433a6]::interpret::eval_context::InterpCx<rustc_const_eval[396cbee6e07433a6]::const_eval::machine::CompileTimeMachine>>::terminator
  14:        0x112462f56 - rustc_const_eval[396cbee6e07433a6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  15:        0x113b9aaec - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>
  16:        0x113b4fbae - <rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>)>>::call_once
  17:        0x1139b3c0d - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  18:        0x113bc59dc - rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  19:        0x112393752 - rustc_middle[8094f41c293b336b]::query::plumbing::query_get_at::<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>>
  20:        0x11240f281 - rustc_const_eval[396cbee6e07433a6]::const_eval::valtrees::eval_to_valtree
  21:        0x112e34fe3 - <rustc_const_eval[396cbee6e07433a6]::provide::{closure#0} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>)>>::call_once
  22:        0x113b97d6c - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>
  23:        0x113b329de - <rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<(rustc_middle[8094f41c293b336b]::ty::context::TyCtxt, rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>)>>::call_once
  24:        0x1139b3c0d - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  25:        0x113bc671c - rustc_query_impl[36fa5edae9172c7f]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  26:        0x11321df16 - rustc_middle[8094f41c293b336b]::query::plumbing::query_get_at::<rustc_query_system[16c7cab3586fd5d4]::query::caches::DefaultCache<rustc_middle[8094f41c293b336b]::ty::ParamEnvAnd<rustc_middle[8094f41c293b336b]::mir::interpret::GlobalId>, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 24usize]>>>
  27:        0x113222208 - <rustc_middle[8094f41c293b336b]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  28:        0x113221bc2 - <rustc_middle[8094f41c293b336b]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  29:        0x1140b4f71 - <rustc_middle[8094f41c293b336b]::ty::consts::Const>::eval
  30:        0x114174e82 - rustc_trait_selection[e5babfdcefab668e]::traits::util::with_replaced_escaping_bound_vars::<rustc_middle[8094f41c293b336b]::ty::consts::Const, rustc_middle[8094f41c293b336b]::ty::consts::Const, <rustc_trait_selection[e5babfdcefab668e]::traits::normalize::AssocTypeNormalizer as rustc_type_ir[52f1f4e14ae618a5]::fold::TypeFolder<rustc_middle[8094f41c293b336b]::ty::context::TyCtxt>>::fold_const::{closure#0}>
  31:        0x1129c8d78 - <&rustc_middle[8094f41c293b336b]::ty::list::RawList<(), rustc_middle[8094f41c293b336b]::ty::generic_args::GenericArg> as rustc_type_ir[52f1f4e14ae618a5]::fold::TypeFoldable<rustc_middle[8094f41c293b336b]::ty::context::TyCtxt>>::try_fold_with::<rustc_trait_selection[e5babfdcefab668e]::traits::normalize::AssocTypeNormalizer>
  32:        0x1129e8f72 - rustc_trait_selection[e5babfdcefab668e]::traits::normalize::normalize_with_depth_to::<&rustc_middle[8094f41c293b336b]::ty::list::RawList<(), rustc_middle[8094f41c293b336b]::ty::generic_args::GenericArg>>::{closure#0}
  33:        0x112abd06a - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::normalize::<&rustc_middle[8094f41c293b336b]::ty::list::RawList<(), rustc_middle[8094f41c293b336b]::ty::generic_args::GenericArg>>
  34:        0x112b82dfd - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::instantiate_value_path
  35:        0x112a97dc5 - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_expr_path
  36:        0x112a9718e - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:        0x112b67f45 - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_expr_kind
  38:        0x112a972aa - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  39:        0x112ad6930 - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_decl
  40:        0x112ad738c - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_block_with_expected
  41:        0x112a972aa - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  42:        0x112a993b4 - <rustc_hir_typeck[83a831c03ea981a4]::fn_ctxt::FnCtxt>::check_return_expr
  43:        0x112b56b3a - rustc_hir_typeck[83a831c03ea981a4]::check::check_fn
  44:        0x112b522e1 - rustc_hir_typeck[83a831c03ea981a4]::typeck
  45:        0x113b9d43c - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 8usize]>>
  46:        0x113a210fe - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::VecCache<rustc_span[2de937bbddea0bd8]::def_id::LocalDefId, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  47:        0x113bc0abb - rustc_query_impl[36fa5edae9172c7f]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  48:        0x112756fd6 - <rustc_middle[8094f41c293b336b]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[af0a509199b1bc4b]::check_crate::{closure#4}>::{closure#0}
  49:        0x1128ac55c - rustc_hir_analysis[af0a509199b1bc4b]::check_crate
  50:        0x112e53df7 - rustc_interface[eab3c32d3b591e25]::passes::run_required_analyses
  51:        0x112e563a0 - rustc_interface[eab3c32d3b591e25]::passes::analysis
  52:        0x113b9d4ec - rustc_query_impl[36fa5edae9172c7f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>
  53:        0x11397bfbe - rustc_query_system[16c7cab3586fd5d4]::query::plumbing::try_execute_query::<rustc_query_impl[36fa5edae9172c7f]::DynamicConfig<rustc_query_system[16c7cab3586fd5d4]::query::caches::SingleCache<rustc_middle[8094f41c293b336b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[36fa5edae9172c7f]::plumbing::QueryCtxt, false>
  54:        0x113ba7a47 - rustc_query_impl[36fa5edae9172c7f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  55:        0x112486857 - <rustc_interface[eab3c32d3b591e25]::queries::QueryResult<&rustc_middle[8094f41c293b336b]::ty::context::GlobalCtxt>>::enter::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  56:        0x1124e4465 - rustc_interface[eab3c32d3b591e25]::interface::run_compiler::<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}
  57:        0x1124caee1 - std[26270defc80edaa9]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>
  58:        0x1124eaff6 - <<std[26270defc80edaa9]::thread::Builder>::spawn_unchecked_<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_with_globals<rustc_interface[eab3c32d3b591e25]::util::run_in_thread_pool_with_globals<rustc_interface[eab3c32d3b591e25]::interface::run_compiler<core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>, rustc_driver_impl[708b2ec565622c48]::run_compiler::{closure#0}>::{closure#1}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c342ec502b95801]::result::Result<(), rustc_span[2de937bbddea0bd8]::ErrorGuaranteed>>::{closure#2} as core[c342ec502b95801]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:        0x1091ff83b - std::sys::pal::unix::thread::Thread::new::thread_start::hfcd29f6cc9954faa
  60:     0x7ff801f5318b - __pthread_start

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/240701-nightly/rustc-ice-2024-07-04T07_01_14-84256.txt` to your bug report

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `main::{constant#0}`
#1 [eval_to_valtree] evaluating type-level constant
end of query stack
error: aborting due to 9 previous errors; 1 warning emitted

Some errors have detailed explanations: E0107, E0277, E0308, E0658.
For more information about an error, try `rustc --explain E0107`.
```

</p>
</details>

### Note
<strong> Ice location: </strong>

https://github.com/rust-lang/rust/blob/6292b2af620dbd771ebb687c3a93c69ba8f97268/compiler/rustc_const_eval/src/interpret/terminator.rs#L130-L136

@rustbot label +F-adt_const_params

### PR DESCRIPTION
**Pull request by oli-obk**
Tuple struct constructors are functions, so when we call them typeck will use the signature tuple struct constructor function to provide type hints. Since typeck mostly ignores and erases lifetimes, we end up never seeing the error lifetime in writeback, thus not tainting the typeck result.

Now, we eagerly taint typeck results by tainting from `resolve_vars_if_possible`, which is called all over the place.

I did not carry over all the `crashes` test suite tests, as they are really all the same cause (missing or unknown lifetime names in tuple struct definitions or generic arg lists).

fixes #124262
fixes #124083
fixes #125155
fixes #125888
fixes #125992
fixes #126666
fixes #126648
fixes #127268
fixes #127266
fixes #127304

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
nice :D

File: compiler/rustc_infer/src/infer/mod.rs [hunk 1]
```diff
@@ -1273,6 +1273,9 @@ impl<'tcx> InferCtxt<'tcx> {
     where
         T: TypeFoldable<TyCtxt<'tcx>>,
     {
+        if let Err(guar) = value.error_reported() {
+            self.set_tainted_by_errors(guar);
+        }
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/mod.rs:1278]: While this could be done in a more targeted location to just fix this one specific kind of ICE, as long as there is no perf impact, this seems like a good place to check a lot of types for errors

**Comment by oli-obk** [comment]
While instruction counts go up, cycles do not (deeply nested multi is probably just noise in mono collection)

@rustbot ready

**Comment by compiler-errors** [comment]
sure why not

@bors r+

**Comment by oli-obk** [comment]
-.- more crashes tests were added in the mean time

**Comment by rylev** [comment]
> Instruction counts go up, cycles do not (deeply nested multi is probably just noise in mono collection)

Seems like the performance after merge largely mirrors the pre-merge perf run so I think @oli-obk's analysis stands. In any case, this is a correctness fix so it seems like a small perf hit would be acceptable in any case. 

@rustbot label: +perf-regression-triaged
