### PR TITLE
mGCA: Support directly represented negated literals

### LINKED ISSUE #152123: mGCA: Support directly represented negated literals
Follow up of #150618 and #150699. We currently support directly represented literals as a `hir::ConstArgKind::Literal` but we don't support negated literals as such a representation:
```rust
#![feature(adt_const_params, min_generic_const_args)]

use std::marker::ConstParamTy;

#[derive(Eq, PartialEq, ConstParamTy)]
struct Foo {
    field: isize
}

fn foo<const F: Foo>() {}

fn main() {
    // works
    foo::<{ Foo { field: 1} }>();
    // needs an anon const
    foo::<{ Foo { field: -1 } }>();
    // works
    foo::<{ Foo { field: const { -1 } } }>();
}
```
```
error: complex const arguments must be placed inside of a `const` block
  --> src/main.rs:16:26
   |
16 |     foo::<{ Foo { field: -1 } }>();
   |                          ^^
```

Not certain of the right way of implementing this, maybe extending `ConstArgKind::Literal` with a flag for whether it was negated or not 🤔 Then it should just be a matter of updating `lower_anon_const_to_const_arg_direct` with a case for `-1` as well as threading the bool into the input of `lit_to_const` in `lower_const_arg_literal`

Once this and #152001 have been done we should remove the special casing in parsing under mGCA for literals being parsed as anon consts instead of direct const args.

### PR DESCRIPTION
**Pull request by khyperia**
fixes rust-lang/rust#152123

PatExprKind already awkwardly tacks on a `negated: bool` for the same purpose:

https://github.com/rust-lang/rust/blob/8bccf1224deab49b54694c9090e577bfe90a94e6/compiler/rustc_hir/src/hir.rs#L1954-L1959

perhaps one day we should indeed do that FIXME...

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 1]
```diff
@@ -2570,7 +2572,19 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
...
+            ExprKind::Unary(UnOp::Neg, inner_expr)
+                if let ExprKind::Lit(literal) = &inner_expr.kind =>
+            {
+                let span = expr.span;
+                let literal = self.lower_lit(literal, span);
+
+                ConstArg {
+                    hir_id: self.lower_node_id(expr.id),
+                    kind: hir::ConstArgKind::Literal { lit: literal.node, negated: true },
                     span,
```
Comment (khyperia) [inline compiler/rustc_ast_lowering/src/lib.rs:2588]: note to reviewers: in addition to nuking the FIXME in my last force-push, I changed the span for this `ConstArg` to **include** the negative sign in the span (before the push, it was excluded, just the inner_expr's span). Realized it was excluded when trying to add errors for `-1_usize`.

(the diff in the force push is rather unclear what's happening so I figured I'd point it out)
