### PR TITLE
Fix parsing of ranges after unary operators

### LINKED ISSUE #134899: Unary operator applied to range fails to parse
```rust
struct S;
impl<T> std::ops::Add<T> for S {
    type Output = ();
    fn add(self, _: T) {}
}

fn main() {
    let _ = ..0;
    let _ = S + ..0;
    let _ = &..0;
    let _ = || ..0;
    let _ = *..0;
}
```

With the exception of `*..0`, all of the above expressions parse successfully, so `..` is definitely allowed to appear at the beginning of an expression &mdash; including an expression with higher precedence such as binary `+` and unary `&`. I think it is a bug that `*..0` does not parse. Same for `-..0` and `!..0`.

```console
error: expected expression, found `..`
  --> src/main.rs:12:14
   |
12 |     let _ = *..0;
   |              ^^ expected expression
```

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes https://github.com/rust-lang/rust/issues/134899.

This PR aligns the parsing for unary `!` and `-` and `*` with how unary `&` is already parsed [here](https://github.com/rust-lang/rust/blob/5c0a6e68cfdad859615c2888de76505f13e6f01b/compiler/rustc_parse/src/parser/expr.rs#L848-L854).

### CODE REVIEW

File: tests/ui/parser/ranges-precedence.rs [hunk 1]
```diff
@@ -1,7 +1,8 @@
 //@ run-pass
+//@ edition: 2021
```
Comment (jieyouxu) [inline tests/ui/parser/ranges-precedence.rs:2]: Question: should this receive revisions to test both 2015 and 2021?

Comment (dtolnay) [reply tests/ui/parser/ranges-precedence.rs:2]: I don't think so. Nothing tested here is sensitive to edition. I added this because otherwise I have to write `extern crate core;` (2015 is a silly default).

**Comment by jieyouxu** [comment]
r? parser (this is likely accepting new code or re-accepting code that regressed a *while* ago)

File: tests/ui/parser/ranges-precedence.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/parser/ranges-precedence.rs:2]: For the record, most UI tests just import from std for that reason.

**Review by compiler-errors — APPROVED** [review]
Implementation looks fine and this does align with the approach that the `&` operator takes. Funny enough that was implemented in https://github.com/rust-lang/rust/pull/105701, and it never went through an FCP even though it was *tagged* as such, and obviously changes the set of parsed expressions in a way that makes new guarantees to the grammar (at least effectively? not certain if the grammar in the reference suggests that should be parsed, and I don't really want to look).

I think this is both clearly a T-lang signoff but also trivial and desirable to make, so r=me after that is approved. They also should perhaps *retroactively* be aware that we began to allow `&..` too in 1.68.

**Comment by oli-obk** [comment]
Should we crater this for the macro fragment effects this may theoretically have? Even if just to tell folk that their code needs fixing before this hits stable.

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
No one actually relied on this! Great. as errs said, let's ship it once T-lang had a look

**Review by davidtwco — APPROVED** [review]
Implementation LGTM, r=me when t-lang are happy.

**Comment by traviscross** [comment]
cc @ehuss

**Comment by traviscross** [comment]
@rfcbot fcp merge

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

OK. For future reference I would appreciate a more thorough comment than the one on this PR, which required a lot of context. I read through the source and finally came to understand what is going. Let me write out what I believe is true..

* In the past, unary operators like `!` and `-` did not accept `..X` range expressions. In the *code*, this comes out from the fact that they invoke `parse_expr_prefix` which, for reasons I do not know but I presume has to do with precedence, does not accept ranges.  This PR changes them to basically accept both prefixes.  It should affect the following operators from my read of the code: `!`, `~`, `-`, `*`.

I don't think it affects `+`. 

When you look at the reference grammar, it just says that `!` and friends are followed by an `Expression`, which could be a range expression, so this feels like a bug fix from that perspective.

**Comment by nikomatsakis** [comment]
@rfcbot concern +-operator

Does this PR intentionally not permit `+..5` to parse as an expression? From my read of the code, it does not cover this case, but why?

**Comment by nikomatsakis** [comment]
@rfcbot resolve +-operator

Ah, I think I see why-ish, because we special case `+`-literal. I'm gonna resolve my concern for now.

**Comment by dtolnay** [comment]
@bors r=compiler-errors,davidtwco
compiler-errors: https://github.com/rust-lang/rust/pull/134900#pullrequestreview-2525783930
davidtwco: https://github.com/rust-lang/rust/pull/134900#pullrequestreview-2624542859
