### PR TITLE
More jemalloc fixes

### LINKED ISSUE #38596: ppc64le and s390x 1.13.0 binaries segfault when trying to build 1.14.0
s390x: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=s390x&ver=1.14.0%2Bdfsg1-1&stamp=1482615802

~~~~
CFG_LLVM_LINKAGE_FILE=/«BUILDDIR»/rustc-1.14.0+dfsg1/s390x-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/«BUILDDIR»/rustc-1.14.0+dfsg1/s390x-unknown-linux-gnu/stage2/lib:/usr/lib/llvm-3.9/lib:$LD_LIBRARY_PATH   s390x-unknown-linux-gnu/stage2/bin/rustc --cfg stage2 -C link-args=-Wl,-z,relro -O --cfg rtopt -Cdebuginfo=1 -C rpath  --target=s390x-unknown-linux-gnu  -C prefer-dynamic -L "s390x-unknown-linux-gnu/rt" -L native="/usr/lib/llvm-3.9/lib"     --out-dir s390x-unknown-linux-gnu/stage2/lib/rustlib/s390x-unknown-linux-gnu/lib -C extra-filename=-f5a209a9 -C metadata=f5a209a9 src/libcore/lib.rs
Segmentation fault
~~~~

ppc64el: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64el&ver=1.14.0%2Bdfsg1-1&stamp=1482614656

~~~~
checking for secure_getenv... Segmentation fault
~~~~

No time atm to investigate further, but will follow this up with more info in the new year.

### LINKED ISSUE #38612: 1.14.0 tests fail (1 run-pass, 1 compile-fail) on arm64
We are bootstrapping this from Debian's 1.13.0, see https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=arm64&ver=1.14.0%2Bdfsg1-1&stamp=1482639065&raw=1

`run-pass/allocator-default.rs`:
~~~~
error: compilation failed!
status: exit code: 101
command: aarch64-unknown-linux-gnu/stage2/bin/rustc /«BUILDDIR»/rustc-1.14.0+dfsg1/src/test/run-pass/allocator-default.rs -L aarch64-unknown-linux-gnu/test/run-pass/ --target=aarch64-unknown-linux-gnu --error-format json -L aarch64-unknown-linux-gnu/test/run-pass/allocator-default.stage2-aarch64-unknown-linux-gnu.run-pass.libaux -C prefer-dynamic -o aarch64-unknown-linux-gnu/test/run-pass/allocator-default.stage2-aarch64-unknown-linux-gnu -C link-args=-Wl,-z,relro --cfg rtopt -C rpath -O -L aarch64-unknown-linux-gnu/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
{"message":"cannot link together two allocators: alloc_system and alloc_jemalloc","code":null,"level":"error","spans":[],"children":[],"rendered":null}
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":null}

------------------------------------------
~~~~

`compile-fail/allocator-rust-dylib-is-jemalloc.rs`:
~~~~
error: compile-fail test compiled successfully!
status: exit code: 0
command: aarch64-unknown-linux-gnu/stage2/bin/rustc /«BUILDDIR»/rustc-1.14.0+dfsg1/src/test/compile-fail/allocator-rust-dylib-is-jemalloc.rs -L aarch64-unknown-linux-gnu/test/compile-fail/ --target=aarch64-unknown-linux-gnu -L aarch64-unknown-linux-gnu/test/compile-fail/allocator-rust-dylib-is-jemalloc.stage2-aarch64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o aarch64-unknown-linux-gnu/test/compile-fail/allocator-rust-dylib-is-jemalloc.stage2-aarch64-unknown-linux-gnu -C link-args=-Wl,-z,relro --cfg rtopt -C rpath -O -L aarch64-unknown-linux-gnu/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------
~~~~

The logs linked above also contain some extra stack traces.

### PR DESCRIPTION
**Pull request by infinity0**
- Disable jemalloc on s390x as well (closes #38596)
- Disable jemalloc tests on platforms where it is disabled (closes #38612)

### CODE REVIEW

File: src/test/run-pass/allocator-default.rs [hunk 1]
```diff
@@ -10,7 +10,7 @@
 
 #![feature(alloc_jemalloc)]
 
-#[cfg(any(target_os = "linux", target_os = "macos"))]
+#[cfg(any(all(target_os = "linux", not(any(target_arch = "aarch64", target_arch = "mips", target_arch = "mips64", target_arch = "powerpc", target_arch = "powerpc64", target_arch = "s390x"))), target_os = "macos"))]
```
Comment (alexcrichton) [inline src/test/run-pass/allocator-default.rs]: This seems like it's getting out of hand, perhaps you can just configure the test to only run on x86_64 linux and OSX?

File: src/test/compile-fail/allocator-rust-dylib-is-jemalloc.rs [hunk 2]
```diff
@@ -29,9 +29,9 @@ extern crate allocator_dylib2;
 // ensure we get the same error.
 //
 // So long as we CI linux/OSX we should be good.
-#[cfg(any(target_os = "linux", target_os = "macos"))]
+#[cfg(any(all(target_os = "linux", not(any(target_arch = "aarch64", target_arch = "mips", target_arch = "mips64", target_arch = "powerpc", target_arch = "powerpc64", target_arch = "s390x"))), target_os = "macos"))]
```
Comment (alexcrichton) [inline src/test/compile-fail/allocator-rust-dylib-is-jemalloc.rs]: This also seems like it's getting out of hand, can we configure this to basically only run the test on x86_64 linux and OSX as well?

**Comment by nikomatsakis** [comment]
This seems reasonable to me (modulo @alexcrichton's comment), though this code is not really my area of expertise.

**Comment by nikomatsakis** [comment]
r=me once @alexcrichton is satisfied, so:

r? @alexcrichton

**Comment by brson** [comment]
Thanks for keeping these platforms running @infinity0

File: src/test/run-pass/allocator-default.rs (hunk 1 above)
Comment (glaubitz) [inline src/test/run-pass/allocator-default.rs]: What is the point of a testsuite if you're not running it? If users of non-x86 platforms are supposed to disable the testsuite, they shouldn't be really trusting any of the generated binaries, to be honest.

**Comment by infinity0** [comment]
Updated to specifically enable on x86 and x86_64 only. (I did it the other way around originally to match what is done in `librustc_back` - which defaults to jemalloc and specifically disables it for all those other arches.) But anyway, this won't matter much once #36963 is done.

File: src/test/run-pass/allocator-default.rs (hunk 1 above)
Comment (infinity0) [inline src/test/run-pass/allocator-default.rs]: In this particular case, we're simply disabling jemalloc-related tests that are not applicable on those platforms, because rust doesn't use jemalloc there. But in general, I do hope rust starts running tests on [these other platforms](https://forge.rust-lang.org/platform-support.html) too.
