### PR TITLE
Replace all const evaluation with miri

### LINKED ISSUE #25574: Constants involving dereferencing in pattern matching
Constants that dereference string literals cannot be currently used for pattern matching as show [below](http://is.gd/F13Q7Q):

``` rust
const A: [u8; 4] = *b"fooo";

fn main() {
    match *b"xxxx" {
        A => {},
        _ => {}
    }
}
```

Such constants can be used in other contexts without any problem. It is inconsistent, and a very prominent use case is missing.

### LINKED ISSUE #27918: Broken MIR with const match
### empty_and_catchall

``` rust
fn empty_and_catchall(raw: &[u8]) {
    let mut iter = raw.split(|&b| b == b'/');
    let first = iter.next().unwrap();
    let second = iter.next();

    const EMPTY: &'static [u8] = b"";

    match (first, second) {
        (EMPTY, Some(EMPTY))  => (),
        _ => (),
    }
}

fn main() { empty_and_catchall(b"foo") }
```

``` _
Assertion failed!

Program: C:\Program Files\Rust nightly 1.4\bin\rustc.exe
File: C:/bot/slave/nightly-dist-rustc-win-gnu-64/build/src/llvm/include/llvm/Support/Casting.h, Line 237

Expression: isa<X>(Val) && "cast<Ty>() argument of incompatible type!"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
### empty

``` rust
fn empty(raw: &[u8]) {
    let mut iter = raw.split(|&b| b == b'/');
    let first = iter.next().unwrap();
    let second = iter.next();

    const EMPTY: &'static [u8] = b"";

    match (first, second) {
        (EMPTY, Some(EMPTY))  => (),
    }
}

fn main() { empty(b"foo") }
```

``` _
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `1`, right: `0`)', ../src/librustc\middle\check_match.rs:536

stack backtrace:
   1:         0x699bb42e - sys::backtrace::write::hb12aa40f2f209619ols
   2:         0x699c5115 - rt::unwind::register::h92f30f49d41046e7Qww
   3:         0x6998564f - rt::unwind::begin_unwind_inner::hbffbb4981b0d700aZtw
   4:         0x69985fdc - rt::unwind::begin_unwind_fmt::h393d9d0c019d9fa55sw
   5:         0x6925756e - middle::const_eval::const_expr_to_pat::h09de9c640f8e12dfYuj
   6:         0x692379ac - session::Session::span_note::he19d21226dfbf5ecNYv
   7:         0x6925c905 - middle::ty::TyS<'tcx>::builtin_deref::h8d5bf22a376109d3kcb
   8:         0x6925bbd4 - middle::ty::TyS<'tcx>::builtin_deref::h8d5bf22a376109d3kcb
   9:         0x6925b903 - middle::ty::TyS<'tcx>::builtin_deref::h8d5bf22a376109d3kcb
  10:         0x69237815 - session::Session::span_note::he19d21226dfbf5ecNYv
  11:         0x69230f81 - middle::check_match::MatchCheckCtxt<'a, 'tcx>.Visitor<'v>::visit_expr::h08c39dd719c14c968uh
  12:         0x692327bb - middle::check_match::MatchCheckCtxt<'a, 'tcx>.Visitor<'v>::visit_fn::ha264f9b30c751779Cvh
  13:         0x69232d11 - middle::check_match::check_crate::hf7369bd73cb3b474kwh
  14:         0x6923292b - middle::check_match::check_crate::hf7369bd73cb3b474kwh
  15:         0x67c0a4a3 - driver::assign_node_ids_and_map::habd9138624442090aEa
  16:         0x67be68c9 - driver::assign_node_ids_and_map::habd9138624442090aEa
  17:         0x67be1bb1 - driver::assign_node_ids_and_map::habd9138624442090aEa
  18:         0x67bc278c - driver::compile_input::hec03b27c99a60d9dTba
  19:         0x67d39bd8 - run_compiler::he293276e81cb97efObc
  20:         0x67d374f0 - run::hd965d7dec4214920ubc
  21:         0x67d36f69 - run::hd965d7dec4214920ubc
  22:         0x699ae9b4 - rt::unwind::try::inner_try::hfa861391a664fbdeSpw
  23:         0x67d37104 - run::hd965d7dec4214920ubc
  24:         0x699c2dee - rt::util::report_overflow::h4a1688dd50f7ee7eyaw
  25:     0x7ffdaf8413d2 - BaseThreadInitThunk
```
### neither

Fails to compile but rustc catches the non exhaustive pattern successfully.

``` rust
fn neither(raw: &[u8]) {
    let mut iter = raw.split(|&b| b == b'/');
    let first = iter.next().unwrap();
    let second = iter.next();

    match (first, second) {
        (b"", Some(b""))  => (),    
    }
}

fn main() { neither(b"foo") }
```

I have no idea how to include more info from LLVM.

``` _
$ rustc --version -v
rustc 1.4.0-nightly (e35fd7481 2015-08-17)
binary: rustc
commit-hash: e35fd748114c22df6d08991980c4f7e199414497
commit-date: 2015-08-17
host: x86_64-pc-windows-gnu
release: 1.4.0-nightly
```

### LINKED ISSUE #29947: tracking issue for `const_indexing` stabilization
The feature called `const_indexing` allows the indexing operation to be performed while calculating a true constant like an array length.

See the implementation at #25570

### LINKED ISSUE #31364: const fn can cause infinite recursion in rustc
``` rust
#![feature(const_fn)]
const fn a() -> usize { b() }
const fn b() -> usize { a() }
const ARR: [i32; a()] = [5; 6];

fn main(){}
```

> thread 'rustc' has overflowed its stack

The same problem happens in trans when using `static A: usize = a();` instead.

Since we do not have constant conditionals, there's currently no way recursion ever makes sense.

### LINKED ISSUE #34997: Chained constant expressions causes stack overflow
Rustc's constant expression evaluation overflows in stack while compiling this kind of code:

``` rust
pub const CST_1: u32 = 0;
pub const CST_2: u32 = CST_1+1;
pub const CST_3: u32 = CST_2+1;
pub const CST_4: u32 = CST_3+1;
pub const CST_5: u32 = CST_4+1;
pub const CST_6: u32 = CST_5+1;
pub const CST_7: u32 = CST_6+1;
pub const CST_8: u32 = CST_7+1;
pub const CST_9: u32 = CST_8+1;
//...
pub const CST_350: u32 = CST_349+1;
```

On my machine (linux 64): ~350 constants on the chain is enough with rustc 1.10.0 (cfcb716cf 2016-10-03). What is quite troubling to me is that rustc seems to do the work for each constant and does not rely on previously computed results. One could think that Rust just always draws the short straw, but I tried random names and random order for my constants and got the same problem.

Also, on 1.12.0-nightly (936bfea94 2016-07-20) and 1.11.0-beta.1 (8dc253bcf 2016-07-05), there is no  stack overflow message just a painful silent abort (return code -1).

### LINKED ISSUE #37448: Consteval cannot handle non-scalar identity casts
``` rust
struct A;
&A as A;
```

results in

```
warning: can't cast this type, #[warn(const_err)] on by default
 --> <anon>:3:5
  |
3 |     A as A;
  |     ^^^^^^

```

### LINKED ISSUE #41898: "unimplemented constant expression: tuple struct constructors" for NonZero const
I came across this when experimenting with using intermediate `const` items to work around `NonZero`’s field being private and be able to use it in patterns.

Reduced test case:

```rust
#![feature(nonzero, const_fn)]
extern crate core;
use core::nonzero::NonZero;

fn main() {
    const FOO: NonZero<u64> = unsafe { NonZero::new(2) };
    if let FOO = FOO {}
}
```

Output with rustc 1.19.0-nightly (d3abc80b3 2017-05-09)

```rust
error[E0080]: constant evaluation error
   |
note: for pattern here
  --> a.rs:7:12
   |
7  |     if let FOO = FOO {}
   |            ^^^

error: aborting due to previous error
```

This error message is incomplete because of #41893, but hacking the compiler yields `unimplemented constant expression: tuple struct constructors`. That error message is emitted in `src/librustc_const_eval/eval.rs`.

It looks like non-tuple-like struct literals are handled in that file as the `hir::ExprStruct(_, ref fields, _)` variant, but tuple-like struct literals syntactically look like function calls so they end up in `hir::ExprPath(ref qpath)` then `Def::StructCtor(_, CtorKind::Fn)` instead, which is the unimplemented case. Beyond this I don’t really understand what’s going on.

CC @eddyb

### LINKED ISSUE #43754: ICE: const_fn feature
```rust
#![feature(const_fn)]
const fn foo(x: usize) -> usize {
    return x;
}
fn main() {
    [0; foo(2)];
}
```
or

```rust
#![feature(const_fn)]
const unsafe fn foo(x: usize) -> usize {
    return x;
}
fn main() {
    [0; unsafe {foo(2)}];

}
```

Note:  rustc 1.21.0-nightly (cbbe17aa7 2017-08-07) running on x86_64-apple-darwin

Run： Cargo build

ICEs with:

```rust
Compiling hello v0.1.0 (file:///.../hello)
error: internal compiler error: src/librustc_mir/hair/cx/expr.rs:472: constant evaluation of repeat count yielded Tuple([])

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (cbbe17aa7 2017-08-07) running on x86_64-apple-darwin

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:486:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

### LINKED ISSUE #45044: ICE: type mismatch comparing repeat and repeat
## STR
```
$ rustc --version
rustc 1.22.0-nightly (185cc5f26 2017-10-02)
```

```Rust
const X: [u8; 1] = [0; 1];

fn main() {
    match &X {
        &X => println!("a"),
        _ => println!("b"),
    };
}
```

## Expected Result

code compiles and runs

## Actual Result
```
warning: unreachable pattern
 --> x.rs:6:9
  |
6 |         &X => println!("a"),
  |         ^^
  |
  = note: #[warn(unreachable_patterns)] on by default

error: internal compiler error: type mismatch comparing Aggregate(Repeat(Const { ty: u8, val: Integral(U8(0)) }, 1)) and Aggregate(Repeat(Const { ty: u8, val: Integral(U8(0)) }, 1))
 --> x.rs:6:10
  |
6 |         &X => println!("a"),
  |          ^

error: aborting due to previous error

```

### LINKED ISSUE #46114: ICE with `match` statement on a struct with `const fn` constructor
Consider a simple `struct` which can be created at compile time (used in `const`s):
```rust
#[derive(Eq, PartialEq)]
struct A { value: u32 }

const fn new(value: u32) -> A {
  A { value }
}
```

I then defined some named constants:
```rust
const A_1: A = new(1);
const A_2: A = new(2);
```

Later on, I tried to use `match` to convert a variable of type `A` to a string:
```rust
let a_str = match a {
   A_1 => "A 1",
   A_2 => "A 2",
   _ => "Unknown A",
};
```

This leads to the following compiler crash:
```
error: internal compiler error: /checkout/src/librustc_const_eval/_match.rs:261: bad constructor ConstantValue(Const { ty: A, val: Aggregate(Struct([(value(91), Const { ty: u32, val: Integral(U32(1)) })])) }) for adt A

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0-nightly (5041b3bb3 2017-11-19) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:471:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Also [uploaded](https://play.rust-lang.org/?gist=fe1b91ecb18358fe5a72300d7033ba30&version=nightly) the sample code to the Rust Playground.

As a side-note: it does not crash if I manually construct the structs, i.e.
```rust
const A_1: A = A { value: 1 };
const A_2: A = A { value: 2 };
```

Alternatively, it also works if I replace the `match` with if / else chains.

### LINKED ISSUE #47971: ICE with static and const_fn
when initalizing a static using a const_fn that returns a pointer to the interior of the static, rustc panics.

```rust
#![feature(const_fn)]

struct S(pub &'static u32, pub u32);

const fn g(ss: &S) -> &u32 { &ss.1 }

static s: S = S(g(&s), 0);

fn main () { }
```

instead of `s` being initialized with a reference to its interior, the compiler panics:

```
error: internal compiler error: librustc_trans/mir/constant.rs:232: loading from `static` (({ i32*, i32 }*:@_ZN3foo1s17h92f76ce7d8965747E = internal global { i32*, i32 })) in constant
 --> foo.rs:5:30
  |
5 | const fn g(ss: &S) -> &u32 { &ss.1 }
  |                              ^^^^^

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:482:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: rustc::session::span_bug_fmt
  10: rustc_trans::mir::constant::MirConstContext::const_place
  11: rustc_trans::mir::constant::MirConstContext::trans
  12: rustc_trans::mir::constant::MirConstContext::trans_def
  13: rustc_trans::mir::constant::MirConstContext::trans
  14: rustc_trans::mir::constant::MirConstContext::trans_def
  15: rustc_trans::consts::trans_static
  16: rustc_trans::trans_item::MonoItemExt::define
  17: rustc_trans::base::compile_codegen_unit
  18: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::compute_result
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc_errors::Handler::track_diagnostics
  21: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  22: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force
  23: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get
  24: rustc::ty::maps::TyCtxtAt::compile_codegen_unit
  25: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit
  26: rustc_trans::base::trans_crate
  27: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  28: rustc::util::common::time
  29: rustc_driver::driver::phase_4_translate_to_llvm
  30: rustc_driver::driver::compile_input::{{closure}}
  31: <std::thread::local::LocalKey<T>>::with
  32: <std::thread::local::LocalKey<T>>::with
  33: rustc::ty::context::TyCtxt::create_and_enter
  34: rustc_driver::driver::compile_input
  35: rustc_driver::run_compiler
```

`rustc --version --verbose`:

```
rustc 1.25.0-nightly (56733bc9f 2018-02-01)
binary: rustc
commit-hash: 56733bc9f8302409a2b6110f422512923c878154
commit-date: 2018-02-01
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

### LINKED ISSUE #48081: [rustc panic:ed] associated constant
## Summary
I tried the following snippet:

```rustc
                self.dest.map_or_else(
                    || {
                        debug!("Called write_block() with no data");
                        false
                    },
                    |dest| {
                        let index = self.write_index.get();
                        let more = index + AES128::BLOCK_SIZE <= self.stop_index.get();
                        if !more {
                            return false;
                        }
                        let regs: &mut AesRegisters = unsafe { mem::transmute(self.registers) };
                        for i in 0..4 {
                            let mut v = dest[index + (i * 4) + 0] as usize;
                            v |= (dest[index + (i * 4) + 1] as usize) << 8;
                            v |= (dest[index + (i * 4) + 2] as usize) << 16;
                            v |= (dest[index + (i * 4) + 3] as usize) << 24;
                            regs.idata.set(v as u32);
                        }
                        self.write_index.set(index + AES128::BLOCK_SIZE);

                        let more =
                            self.write_index.get() + AES128::BLOCK_SIZE <= self.stop_index.get();
                        more
                    },
                )
```
## Expected

Not a compiler crash

## Outcome

```
error[E0283]: type annotations required: cannot resolve `_: kernel::hil::symmetric_encryption::AES128<'_>`
   --> /home/niklasad1/tock/chips/sam4l/src/aes.rs:211:44
    |
211 |                         let more = index + AES128::BLOCK_SIZE <= self.stop_index.get();
    |                                            ^^^^^^^^^^^^^^^^^^
    |
    = note: required by `kernel::hil::symmetric_encryption::AES128::BLOCK_SIZE`

error: internal compiler error: /checkout/src/librustc/traits/trans/mod.rs:62: Encountered ambiguity selecting `Binder(<[type error] as kernel::hil::symmetric_encryption::AES128>)` during trans, presuming due to overflow

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (8e7a609e6 2018-01-04) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:504:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### Backtrace
```
stack backtrace:
   0:     0x7fa41ef5bbfb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h91d1666c6327d52b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fa41ef6a7be - std::sys_common::backtrace::print::h66e8f3310af6a54c
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7fa41ef47680 - std::panicking::default_hook::{{closure}}::h7a402dd600c5b3cc
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7fa41ef47143 - std::panicking::default_hook::hc7cfa94336f822ac
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7fa41ef47acb - std::panicking::rust_panic_with_hook::h7bb2af2582fdefca
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7fa4198f0d47 - std::panicking::begin_panic::h050149da9cc7f772
   6:     0x7fa41990b681 - rustc_errors::Handler::bug::hfa625afa9f723db3
   7:     0x7fa41acd9eff - <std::thread::local::LocalKey<T>>::with::h543ce26cfb6f50bf
   8:     0x7fa41b0c864e - rustc::ty::context::tls::with_opt::h6878b003f8522a9e
   9:     0x7fa41ac0abd7 - rustc::session::opt_span_bug_fmt::hc8994976b9fd9c44
  10:     0x7fa41ac0aae6 - rustc::session::bug_fmt::ha9ee1b22a61f2e60
  11:     0x7fa41ace3ff4 - <std::thread::local::LocalKey<T>>::with::hc56362f2e196171c
  12:     0x7fa41aacf9f8 - rustc::ty::context::GlobalCtxt::enter_local::ha46ec5fc488a532a
  13:     0x7fa41b0711d7 - rustc::traits::trans::trans_fulfill_obligation::h36d04a4b73b138da
  14:     0x7fa41af73551 - rustc::ty::maps::<impl rustc::ty::maps::queries::trans_fulfill_obligation<'tcx>>::compute_result::h3a5709afd05411f6
  15:     0x7fa41aeaa80b - rustc::dep_graph::graph::DepGraph::with_task_impl::h3594064c92f10ee3
  16:     0x7fa41ab94e1f - rustc_errors::Handler::track_diagnostics::h212e44cb9f6613a7
  17:     0x7fa41aab7a40 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::hdb86a4c730046d0c
  18:     0x7fa41af735f4 - rustc::ty::maps::<impl rustc::ty::maps::queries::trans_fulfill_obligation<'tcx>>::force::h280621a9d1094134
  19:     0x7fa41af74178 - rustc::ty::maps::<impl rustc::ty::maps::queries::trans_fulfill_obligation<'tcx>>::try_get::h36d73c6793bed8fd
  20:     0x7fa41ad78d88 - rustc::ty::maps::TyCtxtAt::trans_fulfill_obligation::h3b01c51eba8ba696
  21:     0x7fa41af1456f - rustc::ty::instance::Instance::resolve::ha42785737c9d07b1
  22:     0x7fa41b8a0bf5 - rustc_const_eval::eval::lookup_const_by_id::h235481ee0dad229a
  23:     0x7fa41be46fae - rustc_mir::interpret::const_eval::const_eval_provider::he61ff6eb78749b4c
  24:     0x7fa41af52911 - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::compute_result::hd372dc799ddc81ba
  25:     0x7fa41aebdedb - rustc::dep_graph::graph::DepGraph::with_task_impl::h7d18d69d2b29c6ea
  26:     0x7fa41abaf2cf - rustc_errors::Handler::track_diagnostics::ha705e0db47c7e786
  27:     0x7fa41aabe750 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::hf369de754f658497
  28:     0x7fa41af529ab - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::force::hfe662e34cd1da2c1
  29:     0x7fa41af534c5 - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::try_get::h6b701d0550a2baf8
  30:     0x7fa41ad77858 - rustc::ty::maps::TyCtxtAt::const_eval::h55d029a49f1964dd
  31:     0x7fa41b8a209b - rustc_const_eval::eval::eval_const_expr_partial::hba9bae625532d936
  32:     0x7fa41b8a0c9b - rustc_const_eval::eval::ConstContext::eval::h88555953a4be0435
  33:     0x7fa41be4725d - rustc_mir::interpret::const_eval::const_eval_provider::he61ff6eb78749b4c
  34:     0x7fa41af52911 - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::compute_result::hd372dc799ddc81ba
  35:     0x7fa41aebdedb - rustc::dep_graph::graph::DepGraph::with_task_impl::h7d18d69d2b29c6ea
  36:     0x7fa41abaf2cf - rustc_errors::Handler::track_diagnostics::ha705e0db47c7e786
  37:     0x7fa41aabe750 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::hf369de754f658497
  38:     0x7fa41af529ab - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::force::hfe662e34cd1da2c1
  39:     0x7fa41af534c5 - rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::try_get::h6b701d0550a2baf8
  40:     0x7fa41ad77858 - rustc::ty::maps::TyCtxtAt::const_eval::h55d029a49f1964dd
  41:     0x7fa41af016f2 - <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_const::h367c7dcc2822faf4
  42:     0x7fa41ac35469 - rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_fold_with::hbbcbd16bc6f9410d
  43:     0x7fa41af00d79 - <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty::he448e45aef860a24
  44:     0x7fa41d55af9f - rustc::traits::project::normalize::h1a189fdb64aef9cc
  45:     0x7fa41d468e2c - rustc::infer::InferCtxt::partially_normalize_associated_types_in::h66d802a5e340389e
  46:     0x7fa41d4b8f5a - <std::thread::local::LocalKey<T>>::with::h15b2117ec1c7d041
  47:     0x7fa41d45df74 - rustc::infer::InferCtxtBuilder::enter::hd970daac5fcaeb5c
  48:     0x7fa41d4d633c - rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_item_type::h7c821f3c0df87f83
  49:     0x7fa41d4d7fec - <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h9ec08c5b3cd06f28
  50:     0x7fa41d5aa6bc - rustc::hir::Crate::visit_all_item_likes::h2ee6e7a157d04a3b
  51:     0x7fa41d5327e7 - rustc::session::Session::track_errors::h1f6a33d2e50a3c3c
  52:     0x7fa41d5803b5 - rustc_typeck::check_crate::hb09122b4ee79ea95
  53:     0x7fa41f389717 - <std::thread::local::LocalKey<T>>::with::hc6fb6087df81e9d2
  54:     0x7fa41f3871d6 - <std::thread::local::LocalKey<T>>::with::h836036c2a71f0071
  55:     0x7fa41f3de607 - rustc::ty::context::TyCtxt::create_and_enter::hb73d12258cf88a3c
  56:     0x7fa41f33ef3a - rustc_driver::driver::compile_input::h9deb377f84422e28
  57:     0x7fa41f3b4500 - rustc_driver::run_compiler::h7957e266f41bd133
  58:     0x7fa41f2f9af1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hca871f110f764e5c
  59:     0x7fa41ef933ae - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  60:     0x7fa41f2d8972 - <F as alloc::boxed::FnBox<A>>::call_box::h21ccf4de9d93f71f
  61:     0x7fa41ef6d087 - std::sys_common::thread::start_thread::h95c8df0df264c758
                               at /checkout/src/liballoc/boxed.rs:827
                               at /checkout/src/libstd/sys_common/thread.rs:24
  62:     0x7fa41ef71498 - std::sys::unix::thread::Thread::new::thread_start::hc1ac9245a2c79957
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  63:     0x7fa418e357fb - start_thread
  64:     0x7fa41ec31b5e - clone
  65:                0x0 - <unknown>
```

Thanks

### LINKED ISSUE #48746: "nonexistent struct field" warning when type-punning in a const definition
```rust
#[repr(C)]
union Foo {
    a: u32,
    b: i32,
}

const FOO: i32 = unsafe { Foo { a: 15 }.b };

fn main() {
    println!("{}", FOO);
}
```

```
warning: constant evaluation error: nonexistent struct field
 --> src/main.rs:8:18
  |
8 | const FOO: i32 = unsafe { Foo { a: 15 }.b };
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(const_err)] on by default
```

### PR DESCRIPTION
**Pull request by oli-obk**
* error reporting in constants prints a stacktrace through all called const fns
* Trivial constant propagation and folding in MIR (always active, irrelevant of the optimization level)
* can now use floating constants in patterns (previously only floating point literals were allowed)
    * the future compat lint is still produced for both cases
* can index into constant arrays during const eval (previously feature gated)
* can create a constant union value with field `a` and read from field `b`
* can dereference references into constants
* can create references inside constants (`const X: &u32 = &22`)
* Tuple struct constructors can be used in constants
* regression in const eval errors spans (some of these need improvements in mir debug info)
* can cast floats to ints and vice versa (in constants, and even nan/inf constants)
* Mir dump prints false/true instead of 0u8/1u8
* `1i8 >> [8][0]` does not lint about exceeding bitshifts anymore.
    * Needs const propagation across projections
* `foo[I]` produces a const eval lint if `foo: [T; N]` and `N < I`
    * Essentially all builtin panics produce lints if they can be statically proven to trigger at runtime. This is on a best effort basis, so there might be some complex cases that don't trigger. (The runtime panic stays there, irrelevant of whether the lint is produced or not)
* can use `union`s to implement `transmute` for `Copy` types in constants without a feature gate. With all the greatness and nasal demons that come with this.
* can convert integers to `&'static T` in constants (useful for embedded)

fixes #34997 (stack overflow with many constants)
fixes #25574 (deref byte strings in patterns)
fixes #27918 (broken mir ICE)
fixes #46114 (ICE on struct constructors in patterns)
fixes #37448 (`SomeStruct { foo } as SomeStruct`)
fixes #43754 (`return` in const fn)
fixes #41898 (tuple struct constructors)
fixes #31364 (infinite recursion with const fn, fixed by miri's recursion limit)
closes #29947 (const indexing stabilization)
fixes #45044 (pattern matching repeat expressions)
fixes #47971 (ICE on const fn + references)
fixes #48081 (ICE on cyclic assoc const error)
fixes #48746 (nonhelpful error message with unions)

r? @eddyb 

even though 1k loc are added in tests, this PR reduces the loc in this repository by 700

### CODE REVIEW

File: src/librustc_mir/hair/cx/expr.rs [hunk 1]
```diff
@@ -596,8 +597,18 @@ fn method_callee<'a, 'gcx, 'tcx>(cx: &mut Cx<'a, 'gcx, 'tcx>,
         span: expr.span,
         kind: ExprKind::Literal {
             literal: Literal::Value {
-                value: cx.tcx.mk_const(ty::Const {
-                    val: ConstVal::Function(def_id, substs),
+                value: cx.tcx().mk_const(ty::Const {
+                    val: if cx.tcx().sess.opts.debugging_opts.miri {
+                        let inst = ty::Instance::new(def_id, substs);
+                        let ptr = cx.tcx()
```
Comment (oli-obk) [inline src/librustc_mir/hair/cx/expr.rs]: @eddyb help! I'm not sure where to start touching the hair in order to get these 'gcx and 'tcx lifetimes satisfied:

```
error[E0623]: lifetime mismatch
   --> src/librustc_mir/hair/cx/expr.rs:603:38
    |
584 | fn method_callee<'a, 'gcx, 'tcx>(cx: &mut Cx<'a, 'gcx, 'tcx>,
    |                                           ------------------ this parameter and the return type are declared with different lifetimes...
...
587 |                                  -> Expr<'tcx> {
    |                                     ----------
...
603 |                         let ptr = cx.tcx()
    |                                      ^^^ ...but data from `cx` is returned here

error: aborting due to previous error

error: Could not compile `rustc_mir`.
```

**Comment by alexreg** [comment]
Great work on this, @oli-obk! I was just playing around with it myself, and was wondering on the state of it. Specifically, I seem to still be getting errors indicating that if expressions and loops are still not supported. Is this the case?

**Comment by oli-obk** [comment]
This PR does not enable much new stuff. That's not the point of it. We can enable more things after this PR. All I'm trying to do is to make it work on all code that worked before, without adding anything that we want to talk about in RFCs. That said, a few things will work after this PR.

1. Const indexing
2. Float patterns that go through constants (emitting the future compat lint about floats in patterns)
3. Dereferencing and  referencing things in constants
4. Tuple struct construction in constants

Also I haven't pushed everything yet.

**Comment by alexreg** [comment]
@oli-obk Oh, I see. Thanks for the clarification.

**Comment by alexcrichton** [comment]
@oli-obk this is currently tagged as waiting-on-author, but did you want to start getting an early review?

**Comment by alexreg** [comment]
FWIW, @eddyb and I have been expanding on this significantly over the last few days. He's encouraging me to submit a PR, though I don't know if it's going to be against oli-obk's branch, or rust-lang:master.

File: src/librustc_trans/mir/constant.rs [hunk 2]
```diff
@@ -183,27 +220,25 @@ pub fn trans_static_initializer<'a, 'tcx>(
...
-        .get_alloc(ptr.alloc_id.0)
+        .get_alloc(alloc_id)
         .expect("miri alloc not found");
     Ok(global_initializer(ccx, alloc))
 }
 
 impl<'a, 'tcx> MirContext<'a, 'tcx> {
     // Old version of trans_constant now used just for SIMD shuffle
-    pub fn remove_me__shuffle_indices(&mut self,
+    pub fn remove_me_shuffle_indices(&mut self,
```
Comment (eddyb) [inline src/librustc_trans/mir/constant.rs]: LOL this wasn't a typo, I meant it to be an ugly name like that.

Comment (alexreg) [reply src/librustc_trans/mir/constant.rs]: My bad. I got an error for non-snake-case names, and fixed it by removing the `_` instead of adding a `deny` attribute. :-P

Comment (eddyb) [reply src/librustc_trans/mir/constant.rs]: Ah if it triggered the lint then no worries! I didn't know it cared.

Comment (alexreg) [reply src/librustc_trans/mir/constant.rs]: Yep, it's picky.

**Comment by oli-obk** [comment]
I am now getting

> thread 'rustc' panicked at 'Found unstable fingerprints for MirOptimized(main[317d]::main[0])', librustc/ty/maps/mod.rs:82:1

Which very likely results from the fact that `AllocId`s are generated on the fly when loading from the incremental cache, but we hash the `AllocId`'s integer value. I can solve this by hashing the actual allocation, which obviously should never change. But there's an issue with that: Allocations can refer to themselves either directly or transitively. So hashing an allocation might require hashing the very same allocation, ....

Any clues how to solve this?

cc @nikomatsakis

**Comment by oli-obk** [comment]
cc @michaelwoerister 

You removed the `TyCtxt` from `StableHashingContext` in https://github.com/rust-lang/rust/commit/d5b1fee6fd658bf464902d46f9a6c9c2f8ab87d7#diff-c990dbfd90d57ef3911c819878ba7213
Is there any reason for this besides minimality?

I'm going to need access to the miri allocation interner to be able to hash AllocIds in a stable manner

**Comment by michaelwoerister** [comment]
@oli-obk, yes, we are creating `StableHashingContext`s before the `TyCtxt` is created: https://github.com/rust-lang/rust/blob/8ff449d505728276e822ca9a80c1e7b2da8288a2/src/librustc_driver/driver.rs#L189

This could be solved by some refactoring, I think. @eddyb wanted to move HIR lowering to after the `tcx` is created a while ago.

There might also be another way of hashing `AllocId`s in a stable way? How are the integer ids generated? Are they in a "global address space" or per const?

**Comment by eddyb** [comment]
We could have an `AllocId -> (ParamEnvAnd<GlobalId>, usize)` mapping to record which evaluation an allocation came from, with an evaluation-local index.
Oh and you can use `TLS_TCX` to get around limitations with missing `tcx`.

**Comment by oli-obk** [comment]
During lowering we won't have any `AllocId`s. So I could simply add an `Option<TyCtxt>` to StableHashingContext.

Won't just hashing the ID be problematic if recompiling changes the value of a static?

**Comment by michaelwoerister** [comment]
> Won't just hashing the ID be problematic if recompiling changes the value of a static?

That depends. Can you access the contents of an allocation via an `AllocId` directly? The contents of an allocation have to hashed at some point.

Is there a write up somewhere what these `AllocIds` are exactly?

**Comment by oli-obk** [comment]
Nope no writeup. I'll add one though

AllocIds are used to identify interned Allocations. Serialization serializes the allocation instead of the allocid and deserialization generates a new allocid on the fly to keep them unique

**Comment by michaelwoerister** [comment]
Is there one graph of allocations per `ParamEnvAnd<GlobalId>` that does not overlap with the graph of any other `ParamEnvAnd<GlobalId>`?

**Comment by eddyb** [comment]
@michaelwoerister they're all created by the same evaluation (which makes the per-evaluation index stable even if the global order of evaluations isn't necessary stable), but the graphs might connect, i.e. a `const`/`static` can refer to another `const`/`static`.

**Comment by michaelwoerister** [comment]
I would prefer if `StableHashingContext` could keep having just one lifetime parameter. Could use the `tcx` available from thread-local storage instead?

**Comment by oli-obk** [comment]
> Could use the tcx available from thread-local storage instead?

I'll have a look

**Comment by oli-obk** [comment]
Doesn't work. The lifetimes won't match up. The issue is that there are some things with a `'gcx` lifetime in the StableHashingContext. That clashes with using the tls, which has HKL.

**Comment by eddyb** [comment]
@oli-obk That's what's `lift` is for.

**Comment by eddyb** [comment]
> I'll have a look tomorrow. I'd need to implement `Lift` for `StableHashingContext`

Not sure that makes sense, usually you lift a `Ty` or something containing them, for a specific operation, you should poke me on IRC with the code because it sounds like I'm misleading you so far.

**Comment by oli-obk** [comment]
Travis backlog killed the job

File: src/librustc_mir/build/matches/test.rs [hunk 3]
```diff
@@ -312,15 +312,11 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                     })
                 };
 
-                // Use PartialEq::eq for &str and &[u8] slices, instead of BinOp::Eq.
+                // Use PartialEq::eq for references, instead of BinOp::Eq.
```
Comment (eddyb) [inline src/librustc_mir/build/matches/test.rs]: I'm not sure any of this should be specific to references :/.

File: src/librustc_mir/build/matches/test.rs [hunk 4]
```diff
@@ -258,69 +256,77 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
+                    value
+                });
+                // Use PartialEq::eq instead of BinOp::Eq
+                // (the binop can only handle primitives)
                 let fail = self.cfg.start_new_block();
-                let str_or_bytestr = ty
-                    .builtin_deref(true, ty::NoPreference)
-                    .map(|tam| tam.ty);
-                if let Some(ty) = str_or_bytestr {
+                if !ty.is_scalar() {
```
Comment (oli-obk) [inline src/librustc_mir/build/matches/test.rs]: @eddyb is this what you had in mind with not treating references special? Any non-scalar will be copied into a local (so we can take a reference to it, since `Eq::eq` takes references) and then compared with its `Eq` impl.

**Comment by oli-obk** [comment]
rebased, no conflicts

**Comment by oli-obk** [comment]
@rust-lang/infra can I get a crater run?

**Comment by aidanhs** [comment]
Crater run started

**Comment by aidanhs** [comment]
Crater results: http://cargobomb-reports.s3.amazonaws.com/pr-46882/index.html. 'Blacklisted' crates (spurious failures etc) can be found
[here](https://github.com/rust-lang-nursery/crater/blob/master/blacklist.md).
If you see any spurious failures not on the list, please make a PR against that file.

**Comment by kennytm** [comment]
493 regressions, that's a lot even considering spurious failures 😰

**Comment by oli-obk** [comment]
* missing mir, need to expose MIR for all statics, fixed
* too long RefCell borrows, fixed
* brotli2: that's a resource limit of miri, so we don't consume arbitrary amounts of memory or cpu, not sure what action to take here. I can just increase the limit, but allocating a 120MB array in constants is bound to make const eval take a long time anyway (to initialize all that memory)
* const_val_field: reading a zst field tried to actually read something, fixed

**Comment by eddyb** [comment]
We should probably try to do a second crater run, but maybe we can wait for a review, which I'll try to get to this week, just to make sure there's nothing left to tweak.

**Comment by oli-obk** [comment]
Jup, I really want another crater run after that fallout.

There's one open question: What are we going to do with resource limits?

Should I add an inst-stable (crate wide?) attribute that increases the evaluation steps, maximum frame count or maximum miri-memory usage?

Note that the limits already apply *per* constant, not globally. So even though if there's 100MB limit per constant, you can have multiple 90MB constants.

File: src/librustdoc/clean/mod.rs [hunk 5]
```diff
@@ -2350,17 +2350,29 @@ impl Clean<Type> for hir::Ty {
...
+                    ConstVal::Value(val) => {
+                        let mut s = String::new();
+                        ::rustc::mir::print_miri_value(val, n.ty, &mut s).unwrap();
+                        // array lengths are obviously usize
+                        if s.ends_with("usize") {
+                            let n = s.len() - "usize".len();
+                            s.truncate(n);
+                        }
+                        s
+                    },
```
Comment (eddyb) [inline src/librustdoc/clean/mod.rs]: Maybe some of this code can be deduplicated in this file?

File: src/librustc_trans/mir/constant.rs [hunk 6]
```diff
@@ -1060,278 +135,240 @@ pub fn const_scalar_checked_binop<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
+                        C_struct(bx.cx, &[a_llval, b_llval], false)
+                    },
+                    MiriValue::ByRef(..) => {
+                        let field_ty = constant.ty.builtin_index().unwrap();
+                        let fields = match constant.ty.sty {
+                            ty::TyArray(_, n) => n.val.unwrap_u64(),
+                            ref other => bug!("invalid simd shuffle type: {}", other),
+                        };
+                        let values: Result<Vec<ValueRef>, _> = (0..fields).map(|field| {
+                            let field = const_val_field(
```
Comment (eddyb) [inline src/librustc_trans/mir/constant.rs]: Can't you use this regardless of what `MiriValue` variant `c` is?

File: src/librustc_trans/mir/constant.rs [hunk 7]
```diff
@@ -1060,278 +135,240 @@ pub fn const_scalar_checked_binop<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
-        (vals[i], layout.fields.offset(i))
-    });
-    for (val, target_offset) in parts {
-        let (field_size, field_align) = cx.size_and_align_of(val.ty);
-        packed |= layout.align.abi() < field_align.abi();
-        cfields.push(padding(cx, target_offset - offset));
-        cfields.push(val.llval);
-        offset = target_offset + field_size;
+    // Old version of trans_constant now used just for SIMD shuffle
+    pub fn remove_me_shuffle_indices(&mut self,
```
Comment (eddyb) [inline src/librustc_trans/mir/constant.rs]: Now that it works you can rename this to something reasonable (and adjust the comment).

File: src/librustc_trans/mir/analyze.rs [hunk 8]
```diff
@@ -109,23 +110,32 @@ impl<'mir, 'a, 'tcx> Visitor<'tcx> for LocalAnalyzer<'mir, 'a, 'tcx> {
...
                     literal: Literal::Value {
-                        value: &ty::Const { val: ConstVal::Function(def_id, _), .. }, ..
+                        value: &ty::Const { val, ty }, ..
                     }, ..
                 }),
                 ref args, ..
-            } if Some(def_id) == self.fx.cx.tcx.lang_items().box_free_fn() => {
+            } => match val {
+                ConstVal::Value(Value::ByVal(PrimVal::Undef)) => match ty.sty {
+                    ty::TyFnDef(did, _) => Some((did, args)),
```
Comment (eddyb) [inline src/librustc_trans/mir/analyze.rs]: Again, only need to check the type here.

File: src/librustc_passes/consts.rs [hunk 9]
```diff
@@ -25,12 +25,6 @@
 // by borrowck::gather_loans
```
Comment (eddyb) [inline src/librustc_passes/consts.rs]: Can rename this file to `rvalue_promotion`.

File: src/librustc_mir/transform/instcombine.rs [hunk 10]
```diff
@@ -11,44 +11,54 @@
 //! Performs various peephole optimizations.
```
Comment (eddyb) [inline src/librustc_mir/transform/instcombine.rs]: cc @nikomatsakis @scottmcm This file ended up with a constant folder, can you take a look?

File: src/librustc_mir/transform/instcombine.rs [hunk 11]
```diff
@@ -67,28 +77,485 @@ impl<'tcx> MutVisitor<'tcx> for InstCombineVisitor<'tcx> {
...
+}
+
+fn type_size_of<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
+                          param_env: ty::ParamEnv<'tcx>,
+                          ty: ty::Ty<'tcx>) -> Option<u64> {
+    use rustc::ty::layout::LayoutOf;
+    (tcx, param_env).layout_of(ty).ok().map(|layout| layout.size.bytes())
+}
+
+struct ConstPropVisitor {
```
Comment (eddyb) [inline src/librustc_mir/transform/instcombine.rs]: I'd recommend doing this all at once by having an `IndexVec<Local, LocalState>` where `enum LocalState { Uninitialized, Const(val), Other }`. Also, it should really be separate from `instcombine`, I don't see any reason to put them in the same file.

File: src/librustc_mir/transform/instcombine.rs [hunk 12]
```diff
@@ -67,28 +77,485 @@ impl<'tcx> MutVisitor<'tcx> for InstCombineVisitor<'tcx> {
...
+        if let Rvalue::Ref(_, _, ref place) = *rvalue {
+            if self.is_our_local(place) {
+                self.can_const_prop = false;
+            }
+        }
+    }
 }
 
 impl<'b, 'a, 'tcx> Visitor<'tcx> for OptimizationFinder<'b, 'a, 'tcx> {
+    // override to visit basic blocks in execution order
```
Comment (eddyb) [inline src/librustc_mir/transform/instcombine.rs]: Did you reinvent/reimplement RPO? *Needing* a specific order is usually a pretty bad sign, it means correctness is much harder to understand, or it's not correct in the first place.

**Review by eddyb — CHANGES_REQUESTED** [review]
LGTM overall, but there are a few parts I'm not sure we should merge in the current state, on which I've cc'd other @rust-lang/compiler members

File: src/librustc/middle/const_val.rs [hunk 13]
```diff
@@ -170,6 +169,8 @@ impl<'a, 'gcx, 'tcx> ConstEvalErr<'tcx> {
 
             TypeckError => simple!("type-checking failed"),
             CheckMatchError => simple!("match-checking failed"),
+            // FIXME: report a full backtrace
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/middle/const_val.rs]: yea the "miri" was just for distinguishing errors

`ErrKind` is still used in some places. I'll reduce it to the actually used variants though.

File: src/librustc/ty/context.rs [hunk 14]
```diff
@@ -1247,6 +1269,36 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
         self.get_lang_items(LOCAL_CRATE)
     }
 
+    pub fn is_binop_lang_item(&self, def_id: DefId) -> Option<(mir::BinOp, bool)> {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/ty/context.rs]: is it temporary? This function is used both by miri to skip evaluating the lang items and by the mir inliner code to figure out whether it should be doing anything

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc/ty/context.rs]: Those lang items are a hack for missing LLVM support.

File: src/librustc_mir/const_eval/_match.rs [hunk 15]
```diff
@@ -13,21 +13,20 @@ use self::Usefulness::*;
 use self::WitnessPreference::*;
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc_mir/const_eval/_match.rs]: Well it was in `rustc_const_eval` before that ;)

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc_mir/const_eval/_match.rs]: For a historical reason - most of the match stuff belongs in `hair` I think.

File: src/librustc_mir/transform/instcombine.rs (hunk 12 above)
Comment (oli-obk) [reply src/librustc_mir/transform/instcombine.rs]: The order is just important for anything to happen at all, not for correctness. You only get const prop for `_1 + _2` if `_1 = 42` and `_2 = 55` have already been visited.

Comment (eddyb) [reply src/librustc_mir/transform/instcombine.rs]: You can do it order-independent by detecting an unique initializer (as per https://github.com/rust-lang/rust/pull/46882#discussion_r163838334). That's how rvalue promotion works, for example.

File: src/librustc/ty/util.rs [hunk 16]
```diff
@@ -25,57 +25,95 @@ use util::common::ErrorReported;
...
-type Disr = ConstInt;
-
-pub trait IntTypeExt {
-    fn to_ty<'a, 'gcx, 'tcx>(&self, tcx: TyCtxt<'a, 'gcx, 'tcx>) -> Ty<'tcx>;
-    fn disr_incr<'a, 'tcx>(&self, tcx: TyCtxt<'a, 'tcx, 'tcx>, val: Option<Disr>)
-                           -> Option<Disr>;
-    fn assert_ty_matches(&self, val: Disr);
-    fn initial_discriminant<'a, 'tcx>(&self, tcx: TyCtxt<'a, 'tcx, 'tcx>) -> Disr;
+#[derive(Copy, Clone, Debug)]
+pub struct Disr<'tcx> {
```
Comment (eddyb) [inline src/librustc/ty/util.rs]: Can you call this `Discr` at least?

File: src/librustc/ty/util.rs [hunk 17]
```diff
@@ -25,57 +25,95 @@ use util::common::ErrorReported;
...
-                ast::UintTy::U64 => ConstInt::Usize(ConstUsize::Us64($lit)),
-                _ => bug!(),
-            },
+impl<'tcx> Disr<'tcx> {
+    /// Adds 1 to the value and wraps around if the maximum for the type is reached
+    pub fn wrap_incr<'a, 'gcx>(self, tcx: TyCtxt<'a, 'gcx, 'tcx>) -> Self {
+        self.checked_add(tcx, 1).0
+    }
+    pub fn checked_add<'a, 'gcx>(self, tcx: TyCtxt<'a, 'gcx, 'tcx>, n: u128) -> (Self, bool) {
+        let ty = match self.ty.sty {
```
Comment (eddyb) [inline src/librustc/ty/util.rs]: Can you use `layout::Int` here?

File: src/librustc_const_math/lib.rs [hunk 18]
```diff
@@ -29,13 +29,7 @@ extern crate syntax;
 extern crate serialize as rustc_serialize; // used by deriving
 
 mod float;
-mod int;
-mod usize;
-mod isize;
 mod err;
 
 pub use float::*;
```
Comment (eddyb) [inline src/librustc_const_math/lib.rs]: Do we need the `ConstFloat` wrapper anymore? I'd like miri to call into `rustc_apfloat` directly.

File: src/librustc_driver/driver.rs [hunk 19]
```diff
@@ -1066,6 +1065,13 @@ pub fn phase_3_run_analysis_passes<'tcx, F, R>(trans: &TransCrate,
             stability::check_unused_or_stable_features(tcx)
         });
 
+
+        time(time_passes,
+             "MIR linting",
+             || for def_id in tcx.body_owners() {
+                 mir::const_eval::check::check(tcx, def_id)
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/librustc_driver/driver.rs]: do better in which respect?

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc_driver/driver.rs]: Probably bundling it up with unsafety checking, maybe have a notion of "MIR checks/lints"?

**Comment by aidanhs** [comment]
I guess this could probably do with another crater run at some point?

File: src/librustc/ty/util.rs (hunk 16 above)
Comment (oli-obk) [reply src/librustc/ty/util.rs]: I just followed the type alias name ;)

Comment (eddyb) [reply src/librustc/ty/util.rs]: Right, it was bad before.

File: src/librustc_const_math/lib.rs (hunk 18 above)
Comment (oli-obk) [reply src/librustc_const_math/lib.rs]: That would require us to replicate everything happening here in miri. I just checked all occurrences of `ConstFloat`, and they always pass through a FloatTy + bits.

File: src/librustc/ty/util.rs (hunk 17 above)
Comment (oli-obk) [reply src/librustc/ty/util.rs]: yes, done

File: src/librustc/ty/util.rs (hunk 16 above)
Comment (oli-obk) [reply src/librustc/ty/util.rs]: done

File: src/librustc_const_math/lib.rs (hunk 18 above)
Comment (eddyb) [reply src/librustc_const_math/lib.rs]: I think it's pretty straight-forward to adapt the macros to miri, so you wouldn't have really verbose code or anything like that.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 20]
```diff
@@ -258,7 +259,22 @@ impl<'a, 'b, 'gcx, 'tcx> TypeVerifier<'a, 'b, 'gcx, 'tcx> {
...
+                let did = match value.val {
+                    ConstVal::Value(Value::ByVal(PrimVal::Ptr(p))) => {
+                        self.tcx()
+                            .interpret_interner
+                            .get_fn(p.alloc_id)
+                            .map(|instance| instance.def_id())
+                    },
+                    ConstVal::Value(Value::ByVal(PrimVal::Undef)) => {
+                        match value.ty.sty {
+                            ty::TyFnDef(ty_def_id, _) => Some(ty_def_id),
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Sigh. I probably do. But that will take some reading into it won't it =)

File: src/librustc/ty/error.rs [hunk 21]
```diff
@@ -193,10 +192,10 @@ impl<'a, 'gcx, 'lcx, 'tcx> ty::TyS<'tcx> {
             ty::TyAdt(def, _) => format!("{} `{}`", def.descr(), tcx.item_path_str(def.did)),
             ty::TyForeign(def_id) => format!("extern type `{}`", tcx.item_path_str(def_id)),
             ty::TyArray(_, n) => {
-                if let ConstVal::Integral(ConstInt::Usize(n)) = n.val {
-                    format!("array of {} elements", n)
-                } else {
-                    "array".to_string()
+                match n.val {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/ty/error.rs]: I think it could be entirely unevaluable. If it is evaluable, it'll produce the `Bytes` Primval, if not, we can't print anything anyway. Trying to print weird things like this being a pointer to a string literal also makes little sense imo.

[the remark this answers is not in the document]
Comment (eddyb) [reply src/librustc/ty/error.rs]: I just mean that since this is an array length, it could use a `-> Option<u64>` method or something like that, to avoid matching itself on `ConstVal`.

File: src/librustc/ich/impls_ty.rs [hunk 22]
```diff
@@ -385,10 +392,15 @@ impl<'a> HashStable<StableHashingContext<'a>> for mir::interpret::Allocation {
         }
         self.undef_mask.hash_stable(hcx, hasher);
         self.align.hash_stable(hcx, hasher);
-        self.mutable.hash_stable(hcx, hasher);
+        self.runtime_mutability.hash_stable(hcx, hasher);
     }
 }
 
+impl_stable_hash_for!(enum ::syntax::ast::Mutability {
```
Comment (eddyb) [inline src/librustc/ich/impls_ty.rs]: Isn't there a type like `mir::Mutability` or similar that implements stable hash already?

Comment (oli-obk) [reply src/librustc/ich/impls_ty.rs]: Probably. There are three of these enums. Any reason not to merge them all into one?

Comment (eddyb) [reply src/librustc/ich/impls_ty.rs]: Ask @nikomatsakis.

File: src/librustc/ich/impls_ty.rs [hunk 23]
```diff
@@ -375,6 +336,70 @@ impl_stable_hash_for!(struct ::middle::const_val::ByteArray<'tcx> {
...
+        hcx: &mut StableHashingContext<'a>,
+        hasher: &mut StableHasher<W>,
+    ) {
+        ty::tls::with_opt(|tcx| {
+            let tcx = tcx.expect("can't hash AllocIds during hir lowering");
+            let interner = tcx
+                .interpret_interner
+                .borrow();
+            if let Some(def_id) = interner.get_corresponding_static_def_id(*self) {
+                0.hash_stable(hcx, hasher);
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/ich/impls_ty.rs]: done

File: src/librustc/middle/const_val.rs [hunk 24]
```diff
@@ -47,33 +38,34 @@ pub struct ByteArray<'tcx> {
...
-    Tuple(&'tcx [&'tcx ty::Const<'tcx>]),
-    Array(&'tcx [&'tcx ty::Const<'tcx>]),
-    Repeat(&'tcx ty::Const<'tcx>, u64),
-}
-
-impl<'tcx> Encodable for ConstAggregate<'tcx> {
-    fn encode<S: Encoder>(&self, _: &mut S) -> Result<(), S::Error> {
-        bug!("should never encode ConstAggregate::{:?}", self)
+impl<'tcx> ConstVal<'tcx> {
+    pub fn to_u128(&self) -> Option<u128> {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/middle/const_val.rs]: done

File: src/librustc/middle/const_val.rs [hunk 25]
```diff
@@ -47,33 +38,34 @@ pub struct ByteArray<'tcx> {
...
+                val as u64
+            },
+            None => bug!("expected constant u64, got {:#?}", self),
+        }
     }
-}
-
-impl<'tcx> ConstVal<'tcx> {
-    pub fn to_const_int(&self) -> Option<ConstInt> {
+    pub fn unwrap_usize<'a, 'gcx>(&self, tcx: TyCtxt<'a, 'gcx, 'tcx>) -> ConstUsize {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/middle/const_val.rs]: done

File: src/librustc/middle/const_val.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/middle/const_val.rs]: done

File: src/librustc/mir/interpret/mod.rs [hunk 26]
```diff
@@ -166,6 +169,8 @@ pub struct Allocation {
     pub undef_mask: UndefMask,
     /// The alignment of the allocation to detect unaligned reads.
     pub align: Align,
+    /// Whether the allocation should be put into mutable memory when translating via llvm
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/mir/interpret/mod.rs]: fixed

File: src/librustc/ty/error.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/ty/error.rs]: done

File: src/librustc/ty/layout.rs [hunk 27]
```diff
@@ -946,7 +946,7 @@ impl<'a, 'tcx> LayoutDetails {
         enum StructKind {
             /// A tuple, closure, or univariant which cannot be coerced to unsized.
             AlwaysSized,
-            /// A univariant, the last field of which may be coerced to unsized.
+            /// A univariant, the last field of which fn compute_uncachedmay be coerced to unsized.
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc/ty/layout.rs]: fixed

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 28]
```diff
@@ -1007,13 +1023,29 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
...
+                ConstVal::Value(Value::ByVal(PrimVal::Ptr(p))) => {
+                    let inst = self.tcx().interpret_interner.get_fn(p.alloc_id);
+                    inst.map_or(false, |inst| {
+                        Some(inst.def_id()) == self.tcx().lang_items().box_free_fn()
+                    })
+                },
+                ConstVal::Value(Value::ByVal(PrimVal::Undef)) => {
+                    match ty.sty {
+                        ty::TyFnDef(ty_def_id, _) => {
+                            Some(ty_def_id) == self.tcx().lang_items().box_free_fn()
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: done

File: src/librustc_mir/build/misc.rs [hunk 29]
```diff
@@ -62,49 +61,16 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
             ty::TyChar => {
                 Literal::Value {
                     value: self.hir.tcx().mk_const(ty::Const {
-                        val: ConstVal::Char('\0'),
+                        val: ConstVal::Value(Value::ByVal(PrimVal::Bytes(0))),
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc_mir/build/misc.rs]: done

File: src/librustc_mir/const_eval/_match.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc_mir/const_eval/_match.rs]: moved

File: src/librustc_mir/const_eval/check.rs [hunk 30]
```diff
@@ -0,0 +1,197 @@
...
+        }
+    } else {
+        match tcx.describe_def(def_id) {
+            Some(Def::Const(_)) => true,
+            _ => false
+        }
+    }
+}
+
+pub fn check<'a, 'tcx: 'a>(tcx: TyCtxt<'a, 'tcx, 'tcx>, def_id: DefId) {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/librustc_mir/const_eval/check.rs]: moved to the hair, `const_eval` is no more

File: src/librustc_trans/mir/analyze.rs (hunk 8 above)
Comment (oli-obk) [reply src/librustc_trans/mir/analyze.rs]: done

File: src/librustc_trans/mir/constant.rs (hunk 7 above)
Comment (oli-obk) [reply src/librustc_trans/mir/constant.rs]: done

File: src/librustc/ty/error.rs [hunk 31]
```diff
@@ -192,9 +190,8 @@ impl<'a, 'gcx, 'lcx, 'tcx> ty::TyS<'tcx> {
             ty::TyAdt(def, _) => format!("{} `{}`", def.descr(), tcx.item_path_str(def.did)),
             ty::TyForeign(def_id) => format!("extern type `{}`", tcx.item_path_str(def_id)),
             ty::TyArray(_, n) => {
-                match n.val {
-                    ConstVal::Value(Value::ByVal(PrimVal::Bytes(n))) =>
-                        format!("array of {} elements", n),
+                match n.val.to_raw_bits() {
+                    Some(n) => format!("array of {} elements", n),
                     _ => "array".to_string(),
```
Comment (eddyb) [inline src/librustc/ty/error.rs]: You can write `None` here.

**Comment by alexreg** [comment]
Time for another crater run, @oli-obk? :-)

**Comment by eddyb** [comment]
@alexreg I still need to review some things.

File: src/librustc_mir/transform/const_prop.rs [hunk 32]
```diff
@@ -562,9 +446,5 @@ impl<'b, 'a, 'tcx> Visitor<'tcx> for OptimizationFinder<'b, 'a, 'tcx> {
 
 #[derive(Default)]
 struct OptimizationList<'tcx> {
-    const_prop: FxHashMap<Location, Const<'tcx>>,
-    /// Terminators that get their Operand(s) turned into constants.
-    terminators: FxHashMap<BasicBlock, Const<'tcx>>,
     places: FxHashMap<Local, Const<'tcx>>,
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: Can you inline this struct now that it's one-field only?

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: done

**Comment by oli-obk** [comment]
@eddyb can we start a crater run without a full review?

**Comment by eddyb** [comment]
I think I'll take a quick look then we can send it off to crater again!

File: src/librustc_mir/transform/const_prop.rs [hunk 33]
```diff
@@ -52,7 +52,7 @@ struct OptimizationFinder<'b, 'a, 'tcx:'a+'b> {
     mir: &'b Mir<'tcx>,
     tcx: TyCtxt<'a, 'tcx, 'tcx>,
     source: MirSource,
-    optimizations: OptimizationList<'tcx>,
+    places: FxHashMap<Local, Const<'tcx>>,
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: Please use `IndexVec<Local, Option<Const<'tcx>>>`.
Also, rename `OptimizationFinder` to `ConstPropagator` or `ConstFolder`.

File: src/librustc_driver/driver.rs [hunk 34]
```diff
@@ -1066,6 +1064,13 @@ pub fn phase_3_run_analysis_passes<'tcx, F, R>(trans: &TransCrate,
             stability::check_unused_or_stable_features(tcx)
         });
 
+
+        time(time_passes,
+             "MIR linting",
+             || for def_id in tcx.body_owners() {
+                 mir::check_const_err::check(tcx, def_id)
```
Comment (eddyb) [inline src/librustc_driver/driver.rs]: I think this should be triggered from one of the MIR queries, as per:
https://github.com/rust-lang/rust/blob/679f30e1aac510082b0fd3a2b5465321753aa7d1/src/librustc_mir/transform/mod.rs#L188-L189

File: src/librustc_trans/mir/block.rs [hunk 35]
```diff
@@ -412,10 +412,11 @@ impl<'a, 'tcx> FunctionCx<'a, 'tcx> {
...
                 if const_cond == Some(!expected) {
                     if let Some(err) = const_err {
-                        let err = ConstEvalErr{ span: span, kind: err };
                         let mut diag = bx.tcx().sess.struct_span_warn(
-                            span, "this expression will panic at run-time");
-                        err.note(bx.tcx(), span, "expression", &mut diag);
+                            span, &format!(
+                                "this expression will panic at run-time with {:?}",
+                                err,
+                            ));
```
Comment (eddyb) [inline src/librustc_trans/mir/block.rs]: Can we *move* this to const prop? Ideally `rustc_trans` wouldn't emit any warnings!

File: src/librustc_mir/transform/const_prop.rs (hunk 33 above)
Comment (eddyb) [reply src/librustc_mir/transform/const_prop.rs]: Remove comments about "optimization opportunities" and add this comment:
```rust
// FIXME(oli-obk, eddyb) Optimize locals (or even local paths) to hold
// constants, instead of just checking for const-folding succeeding.
// That would require an uniform one-def no-mutation analysis
// and RPO (or recursing when needing the value of a local).
```

File: src/librustc_mir/check_const_err.rs [hunk 36]
```diff
@@ -1,197 +0,0 @@
...
-}
-
-impl<'a, 'tcx> Visitor<'tcx> for ConstErrVisitor<'a, 'tcx> {
-    fn visit_terminator(&mut self,
-                        block: BasicBlock,
-                        terminator: &Terminator<'tcx>,
-                        location: Location) {
-        self.super_terminator(block, terminator, location);
-        match terminator.kind {
-            TerminatorKind::Assert { ref cond, expected, ref msg, .. } => {
```
Comment (eddyb) [inline src/librustc_mir/check_const_err.rs]: Do you handle this in const prop now? I didn't realize what this file was, makes more sense to put it in const prop.

Comment (oli-obk) [reply src/librustc_mir/check_const_err.rs]: yea I was doing that the whole time. Totally forgot about the const checker and trans version of that.

File: src/librustc_mir/transform/const_prop.rs [hunk 37]
```diff
@@ -271,33 +273,34 @@ fn type_size_of<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
         let mut cpv = CanConstProp {
-            local,
-            can_const_prop: true,
-            found_assignment: false,
+            can_const_prop: IndexVec::from_elem(true, &mir.local_decls),
+            found_assignment: IndexVec::from_elem(false, &mir.local_decls),
         };
+        for (local, val) in cpv.can_const_prop.iter_enumerated_mut() {
+            *val = mir.local_kind(local) == LocalKind::Temp;
+        }
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: `rustc_trans` didn't have this limitation, so you should be able to check more.

File: src/librustc_mir/transform/const_prop.rs [hunk 38]
```diff
@@ -312,21 +315,21 @@ impl<'tcx> Visitor<'tcx> for CanConstProp {
         match statement.kind {
             StatementKind::SetDiscriminant { ref place, .. } |
             StatementKind::Assign(ref place, _) => {
-                if self.is_our_local(place) {
-                    if self.found_assignment {
-                        self.can_const_prop = false;
+                if let Some(local) = place_to_local(place) {
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: This should be done with `visit_local` and `PlaceContext` - see  https://github.com/rust-lang/rust/blob/fe7e1a45f37f4265434cead827f587e75412f85c/src/librustc_mir/transform/promote_consts.rs#L79-L135

File: src/librustc_mir/transform/const_prop.rs (hunk 37 above)
Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: You told me to only accept temporaries ;)

Comment (eddyb) [reply src/librustc_mir/transform/const_prop.rs]: I forgot all the things I said but the only limitation we have is we can't *remove* `var = const` assignments, because debuginfo needs to see them - but you're not replacing anything.

File: src/librustc_mir/transform/const_prop.rs [hunk 39]
```diff
@@ -272,78 +277,71 @@ fn type_size_of<'a, 'tcx>(tcx: TyCtxt<'a, 'tcx, 'tcx>,
...
-                        }
-                        return;
-                    }
+            // Reading constants is allowed an arbitrary number of times
+            Copy | Move |
+            StorageDead | StorageLive |
+            Validate |
+            Inspect => {},
+            Borrow { kind: BorrowKind::Shared, .. } => {
+                // cannot const prop immutable borrows of types with interior mutability
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: Do we need this special-case?

Comment (oli-obk) [reply src/librustc_mir/transform/const_prop.rs]: we can just forbid all borrows?

Comment (eddyb) [reply src/librustc_mir/transform/const_prop.rs]: Yeah, only named variables can be both used directly and borrowed, so this should be fine, I think.

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
This seems ready!

@bors try

**Comment by kennytm** [comment]
@oli-obk Could you revert the change done to `checktools.sh` from #47881 in this PR? Thanks.

**Comment by oli-obk** [comment]
If not absolutely required, I'd like to do that in a follow-up PR, since I still haven't fully fixed the miri submodule

**Comment by kennytm** [comment]
@oli-obk OK, just to avoid this being forgotten ^_^

**Comment by eddyb** [comment]
@rust-lang/infra Time for another Crater run!

**Comment by nikomatsakis** [comment]
@oli-obk @eddyb 

OK, I skimmed the PR. The only part that I read relatively closely were the changes to patterns. For the most part, those seemed pretty nice! The code is quite readable, kudos to @oli-obk, though I wouldn't mind some more comments on various functions to help clarify what they do. Better yet -- write a chapter for the [rustc-guide](https://github.com/rust-lang-nursery/rustc-guide/), or mentor someone through one. =)

Anyway, let me mention a few random things:

**Floating point changes.** I think consolidating the handling of floating point so that literals + named constants behave the same is fine. I tend to think we should just allow this, but that's a separate question from this PR.

**Quality of error output might be questionable.** 

The spans and things in these diffs seemed like an overall regression:

```diff
modified   src/test/ui/const-eval/issue-43197.stderr
@@ -1,28 +1,38 @@
-warning: constant evaluation error: attempt to subtract with overflow
-  --> $DIR/issue-43197.rs:18:20
-   |
-18 |     const X: u32 = 0-1; //~ ERROR constant evaluation error
-   |                    ^^^
+error[E0080]: constant evaluation error
+  --> $DIR/issue-43197.rs:20:23
    |
-   = note: #[warn(const_err)] on by default
+20 |     println!("{} {}", X, Y);
+   |                       ^ referenced constant has errors

-warning: constant evaluation error: attempt to subtract with overflow
-  --> $DIR/issue-43197.rs:20:20
+error[E0080]: constant evaluation error
+  --> $DIR/issue-43197.rs:20:26
    |
-20 |     const Y: u32 = foo(0-1); //~ ERROR constant evaluation error
-   |                    ^^^^^^^^
+20 |     println!("{} {}", X, Y);
+   |                          ^ referenced constant has errors

 error[E0080]: constant evaluation error
-  --> $DIR/issue-43197.rs:18:20
+  --> $DIR/issue-43197.rs:19:5
    |
-18 |     const X: u32 = 0-1; //~ ERROR constant evaluation error
-   |                    ^^^ attempt to subtract with overflow
+19 |     const Y: u32 = foo(0-1); //~ ERROR constant evaluation error
+   |     ^^^^^^^^^^^^^^^^^^^^^^^^ attempt to subtract with overflow
+   |
+note: for constant propagated here
+  --> $DIR/issue-43197.rs:20:26
+   |
+20 |     println!("{} {}", X, Y);
+   |                          ^

 error[E0080]: constant evaluation error
-  --> $DIR/issue-43197.rs:20:24
+  --> $DIR/issue-43197.rs:18:5
+   |
+18 |     const X: u32 = 0-1; //~ ERROR constant evaluation error
+   |     ^^^^^^^^^^^^^^^^^^^ attempt to subtract with overflow
+   |
+note: for constant propagated here
+  --> $DIR/issue-43197.rs:20:23
    |
-20 |     const Y: u32 = foo(0-1); //~ ERROR constant evaluation error
-   |                        ^^^ attempt to subtract with overflow
+20 |     println!("{} {}", X, Y);
+   |                       ^

-error: aborting due to 2 previous errors
+error: aborting due to 4 previous errors
```

we went from 2 errors with pretty precise spans, to 4 with less precise spans, and semi-duplicates. Any thoughts?

(Also, what are all these lines like `//~ ERROR const_err`... eddyb thought maybe a lint?)

**Recursion message nit.**

This message:

```
+error[E0080]: constant evaluation error
+  --> $DIR/infinite-recursion-const-fn.rs:16:18
+   |
+14 | const fn a() -> usize { b() }
+   |                         --- inside call to b
+15 | const fn b() -> usize { a() }
+   |                         ---
+   |                         |
+   |                         inside call to a
```

should say:

```
inside call to `b`
```

i.e., escape the `b` and `a` names

**changes to `is_useful` and friends.** I wasn't clear on the motivation for these diffs:

```diff
renamed    src/librustc_const_eval/_match.rs -> src/librustc_mir/hair/pattern/_match.rs
@@ -866,12 +899,13 @@ fn constructor_sub_pattern_tys<'a, 'tcx: 'a>(cx: &MatchCheckCtxt<'a, 'tcx>,
                                              ctor: &Constructor,
                                              ty: Ty<'tcx>) -> Vec<Ty<'tcx>>
 {
-    debug!("constructor_sub_pattern_tys({:?}, {:?})", ctor, ty);
+    debug!("constructor_sub_pattern_tys({:#?}, {:?})", ctor, ty);
     match ty.sty {
         ty::TyTuple(ref fs, _) => fs.into_iter().map(|t| *t).collect(),
         ty::TySlice(ty) | ty::TyArray(ty, _) => match *ctor {
             Slice(length) => (0..length).map(|_| ty).collect(),
             ConstantValue(_) => vec![],
+            Single => vec![ty],
             _ => bug!("bad slice pattern {:?} {:?}", ctor, ty)
         },
         ty::TyRef(_, ref ty_and_mut) => vec![ty_and_mut.ty],
@@ -880,6 +914,9 @@ fn constructor_sub_pattern_tys<'a, 'tcx: 'a>(cx: &MatchCheckCtxt<'a, 'tcx>,
                 // Use T as the sub pattern type of Box<T>.
                 vec![substs[0].as_type().unwrap()]
             } else {
+                if let ConstantValue(_) = *ctor {
+                    return vec![];
+                }
                 adt.variants[ctor.variant_index_for_adt(adt)].fields.iter().map(|field| {
                     let is_visible = adt.is_enum()
                         || field.vis.is_accessible_from(cx.module, cx.tcx);
```

The change mostly makes sense, but it wasn't clear to me what had changed to cause us to go down this path when we did not before.

**Comment by oli-obk** [comment]
> The spans and things in these diffs seemed like an overall regression

Yes. This looks like it is the move from a HIR lint to waiting until the collector hits it.

This probably also means that unused constants with errors aren't showing up as either warning or error.
So I guess I'll reintroduce the lint to check all constants and report errors on them and not produce any errors if const promotion tries to promote a broken constant.

> what are all these lines like //~ ERROR const_err...

Yep, lints in files with `deny(warnings)`. Duplication probably has the same  reason as the above mentioned error regression

> The change mostly makes sense, but it wasn't clear to me what had changed to cause us to go down this path when we did not before.

I don't remember exactly. This occurred after using const eval to produce constvalue patterns for anything other than literals. Now that I'm destructuring constants back to patterns, this might be dead code. I'll debug and add some comments if it's still necessary.

**Comment by nikomatsakis** [comment]
> I don't remember exactly. This occurred after using const eval to produce constvalue patterns for anything other than literals. Now that I'm destructuring constants back to patterns, this might be dead code. I'll debug and add some comments if it's still necessary.

👍

**Comment by oli-obk** [comment]
> Quality of error output might be questionable.

-might be +was (https://github.com/rust-lang/rust/pull/46882/commits/9e0b0fd28ad96a359050f73abc26ea2850dfb96b)

> changes to is_useful and friends. I wasn't clear on the motivation for these diffs:

That was indeed dead code: 417ccc9 

> Better yet -- write a chapter for the rustc-guide, or mentor someone through one. =)

I already got a few small chapters ready, will post them soonish

**Comment by oli-obk** [comment]
failure is in a test that wasn't on master this morning... rebasing...

**Comment by oli-obk** [comment]
@bors try

tests are passing locally

**Comment by oli-obk** [comment]
@rust-lang/infra can you start another crater run?

**Comment by ishitatsuyuki** [comment]
Crosspost from #48009: this chokes on large constant slices, and regressed it into an hard error (instead of long compile).

```
error[E0080]: constant evaluation error
  --> unic/ucd/name/src/name.rs:44:18
   |
44 |             _ => data::NAMES.find(ch).map(|pieces| Name::NR3(pieces)),
   |                  ^^^^^^^^^^^ referenced constant has errors

error[E0080]: constant evaluation error
     --> unic/ucd/name/src/../tables/name_map.rsv:3:24
      |
3     |   CharDataTable::Direct(&[
      |  ________________________^
4     | |     ('\u{20}', &[SPACE]),
5     | |     ('\u{21}', &[EXCLAMATION, MARK]),
6     | |     ('\u{22}', &[QUOTATION, MARK]),
...     |
31526 | |     ('\u{e01ef}', &[VARIATION, SELECTOR_256]),
31527 | | ])
      | |_^ reached the configured maximum execution time

    time: 4.969; rss: 764MB     translation item collection
error: aborting due to 2 previous errors
```

**Comment by oli-obk** [comment]
Yea this is kind of expected. I could easily add a configuration attribute for making the limits configurable (as mentioned earlier when crater found a few cases of this happening).

Although arrays with 31k elements are somewhat suboptimal imo. With miri you could create a binary file that contains all your data in one binary blob. Then you load said blob with `include_bytes!` and access its data with pointer arithmetics (yes that pointer arithmetic and reading from it works at compile-time).

**Comment by oli-obk** [comment]
We can change the hard error into a future compat warning (or a warning in general). This means you might crash the compiler with a stack overflow if you do infinite recursion.

**Comment by pftbest** [comment]
Sorry for interrupting, but I just want to raise my concern. I think exceeding time limits should never lead to compiler error. If the code successfully compiles on a very fast CPU it should also compile without error on a very slow machine. This becomes very important in a virtualized environments like travis, where your processing power depends on how many instances are also running on the same host and can vary over time.
Or for another example, imagine your laptop  goes to sleep during the compile, and after you wake it up you'll get a compile error.

Much better metric would be something like number of executed instructions, the number of function calls, the amount of memory allocated, or other parameters that are stable across builds and do not depend on the model of your CPU.

**Comment by oli-obk** [comment]
> If the code successfully compiles on a very fast CPU it should also compile without error on a very slow machine. 

We are not measuring time. We are counting MIR-statements.

> Much better metric would be something like number of executed instructions, the number of function calls, the amount of memory allocated, or other parameters that are stable across builds and do not depend on the model of your CPU.

That's what we are doing. There are 3 limits:

1. number of instructions executed (changes with optimizations or MIR improvements)
2. number of virtual bytes allocated
3. number of stack frames allocated (recursion depth with const fn)

**Comment by pftbest** [comment]
@oli-obk  Oh, sorry, I misunderstood the error message. I thought it really meant real time or process time.

**Comment by mark-i-m** [comment]
I am curious why a 31k-element array would take so much time and stack. 31k is not that much by modern standards.

**Comment by kennytm** [comment]
Since the miri "maximum execution time" is unrelated to time, perhaps choose another term like "complexity" to reduce confusion? Like Swift's error message:

dvecle0vqae14xd

**Comment by oli-obk** [comment]
> I am curious why a 31k-element array would take so much time and stack. 31k is not that much by modern standards.

It's not a question of being able to compute it. Miri is turing complete. These limits exist to prevent infinite recusion, looping or leaking. There is no (resonable) way to prevent such things otherwise. Without such limits the compiler will either run into a stack overflow, oom or just hang. Choosing a reasonable limit is hard and increasing it will increase the time the compiler needs to notify you with a error message.

> Since the miri "maximum execution time" is unrelated to time, perhaps choose another term like "complexity" to reduce confusion?

Seems reasonable

**Comment by alexreg** [comment]
@oli-obk Is the limit configurable? Might be worth adding the option down the line, if not.

**Comment by mark-i-m** [comment]
@oli-obk My question is more about efficiency. My understanding from https://github.com/rust-lang/rust/pull/46882#issuecomment-364847868 is that we are evaluating a large constant with no recursion, looping, etc. We _know_ that this can be computed in finite time and memory; we are not running into the halting problem here. Moreover, if we were computing and filling the array at runtime, it would take at most several dozens of thousands of processor instructions and hundreds of kilobytes of memory. So why is miri running into instruction/memory limits? Is there just an abnormally large amount of MIR generated or something?

**Comment by eddyb** [comment]
An `N`-element array of integer/float literals takes about `N + 1` instructions. String literals might have a few more instructions if reborrowing ends up in MIR, and byte literals would also have unsizing.

**Comment by oli-obk** [comment]
> Is there just an abnormally large amount of MIR generated or something?

Well... the step limit is 1 million.

31k array elements allow for ~30 instructions per element. Replicating something from the error message results in the following MIR for every element

```
StorageLive(_9);                 // scope 0 at src/main.rs:3:5: 3:26
        StorageLive(_10);                // scope 0 at src/main.rs:3:16: 3:25
        StorageLive(_11);                // scope 0 at src/main.rs:3:16: 3:25
        StorageLive(_12);                // scope 0 at src/main.rs:3:16: 3:25
        StorageLive(_13);                // scope 0 at src/main.rs:3:17: 3:25
        _13 = [const 43u8, const 34u8];  // scope 0 at src/main.rs:3:17: 3:25
        _12 = &_13;                      // scope 0 at src/main.rs:3:16: 3:25
        _11 = _12;                       // scope 0 at src/main.rs:3:16: 3:25
        _10 = _11 as &[u8] (Unsize);     // scope 0 at src/main.rs:3:16: 3:25
        _9 = (const '#', _10);           // scope 0 at src/main.rs:3:5: 3:26
```

So around 10 statements if the second field contains 2 elements. Thus I'm not sure why it runs into the limit, but I haven't seen all the code, maybe there's some really complex elements? Also note that  repeat expressions consume repeat-count instructions.

**Comment by mark-i-m** [comment]
Hmm... It looks like the offending file is https://raw.githubusercontent.com/behnam/rust-unic/v0.6.0/unic/ucd/name/tables/name_map.rsv

There are some elements of that array that have more than 2 elements, so it makes sense that we might hit a 1M limit...

Would it be possible for multi-element/field data structures to enforce the limit per-field? i.e. for an array, we would enforce the 1M limit per-element, and for structs/enums it would be per-field? That would make the limit proportional to the size of the MIR to be evaluated without as much danger of overflow, etc. We could also reduce from 1M to something much smaller, I think.

**Comment by oli-obk** [comment]
> Would it be possible for multi-element/field data structures to enforce the limit per-field? i.e. for an array, we would enforce the 1M limit per-element, and for structs/enums it would be per-field? That would make the limit proportional to the size of the MIR to be evaluated without as much danger of overflow, etc. We could also reduce from 1M to something much smaller, I think.

That won't work. The slice has no length in the type, so we can't know that beforehand. All its elements are computed, then the array is created, then the array is unsized.

We could count terminators instead of statements. That'll still catch all infinite loops. Infinite recursion is caught by the recursion limit already, so we don't need to even count function calls.

**Comment by mark-i-m** [comment]
> We could count terminators instead of statements. That'll still catch all infinite loops. Infinite recursion is caught by the recursion limit already, so we don't need to even count function calls.

That sounds good 👍

**Comment by eddyb** [comment]
So instead of an "step limit", it'd be a "branch limit"?

**Comment by scottmcm** [comment]
Terminators sounds great!  1 million is so high that it's hard to get an intuition about, whereas with something more focused it could be really low (especially initially) while still being very useful, so it would be feasible for a human to even count how many it would need.  The things that really need restricting are just `Call`s and CFG back-edges taken, right?  (I wanted to say `Goto` doesn't matter, but of course that's only true in terminating programs, which aren't the problem.  But it does feel like it would be easier to understand if, say, basic block splitting and merging didn't change the cost.)

And looking at the MIR example makes me really worried that it'd easy for random changes in HIR->MIR lowering or mir-opt to break programs in a pure `Statement`-count model.

**Comment by BatmanAoD** [comment]
@oli-obk Sounds like you have work to be done, and you're not waiting on a crater run. Is that correct? If so, I'll change the PR labels.

**Comment by alexreg** [comment]
@BatmanAoD I don't want to speak too much for @oli-obk, but I'm pretty sure he's been waiting for a crater run for many days now. These are new things that have just come up, and can probably be addressed easily enough after the crate run. That's my view, at least.

**Comment by BatmanAoD** [comment]
@alexreg I understand, and I am definitely sympathetic to that situation! I based my comment on the last comment from bors, though, which indicates that a merge was not possible; AFAIK, crater cannot be run without a successful merge comment from bors, at least not without some kind of override.

If someone with more knowledge of crater can correct me in this, please do!

**Comment by alexreg** [comment]
@BatmanAoD Oh right. I was under the impression crater could run without a PR being in a mergeable state... I mean, I don't see why it's required. It's just likely running off an old version of nightly. :-) I could be wrong though.

We will need a rebase onto the latest master before bors r+ can be done though.

**Comment by mark-i-m** [comment]
I think the crater run has been queued but not started yet.

**Comment by BatmanAoD** [comment]
@alexreg It may well be possible, I just don't know how to do or even facilitate it. I don't actually have access to the crater servers, and the instructions for triage of crater-ready PRs just say to use the commit IDs from bors comments.

**Comment by alexreg** [comment]
@BatmanAoD Oh right. Well I'll have to cede to someone with better knowledge of this than I. @aidanhs seems to have taken the initiative anyway, which is great.

**Comment by aidanhs** [comment]
> I think the crater run has been queued but not started yet.

@mark-i-m it's started - 'queued' with crater means 'someone has asked for a run' and 'started' (usually) means 'in ~4 days you'll get results'.

> AFAIK, crater cannot be run without a successful merge comment from bors, at least not without some kind of override.

@BatmanAoD you're absolutely right, but if you expand the comments github has hidden, you'll see a successful 'try' merge from 7 days ago (https://github.com/rust-lang/rust/pull/46882#issuecomment-363516086), and a quick scan of comments didn't suggest many substantial changes since then.

**Comment by BatmanAoD** [comment]
@aidanhs Thanks for explaining. I saw the huge stack of commits after that and didn't closely examine to see if the changes were substantial. Looks like the crater run is now pending.

**Comment by aidanhs** [comment]
Crater results: http://cargobomb-reports.s3.amazonaws.com/pr-46882-2/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/blacklist.md). If you see any spurious failures not on the list, please make a PR against that file.

**Comment by oli-obk** [comment]
# Build failures

* expected, too many computation steps (unic*)
* expected (out123, fixed in newer version of crate)
* google-dfareporting (unknown, access error)
* mozjs (ice after future compat lint)
* crypot-currency (timeout)
* uinput (timeout)
* expected (clippy)

# runtime failures

* brotli (tried to allocate 125829120 more bytes, but only 104857600 bytes are free of the 104857600 byte memory)
* cat-reader-0.1.3 (expected, can't find librustc_const_eval)
* cldap (runtime test failure)
* collapse-crate-0.1.0 (librustc_const_eval)
* hashconsing-0.3.0 (flaky)
* ipc-channel-0.9.1 (timeout)
* lockless-0.2.0 (test threading randomness)
* milagro-crypto-0.1.14 (flaky)
* msql-srv (timeout)
* parse-hosts-0.3.0 (librustc_const_eval)
* pop-trait-0.2.1 (librustc_const_eval)
* proptest-0.3.4 (randomness)
* rand-pop-0.1.1 (librustc_const_eval)
* rrun-ssh-0.3.0 (librustc_const_eval)
* sacn-0.3.0 (flaky)
* simple-munin-plugin-0.1.0 (env vars)
* suppositions-0.1.4 (skipping tests)
* sysconf-0.3.1 (syscall too big)
* treeflection (flaky)
* version-sort-0.1.0 (librustc_const_eval)
* vidar (flaky)
* x86asm-0.1.0 (timeout)


So the only real failures are reached limits and that one ice after an inference future compat lint that I'll investigate

**Comment by oli-obk** [comment]
So about the const oom error. Finding a good default limit is hard. We could simply disable that limit. Either people will run into the real memory limit and rustc will oom, or it'll work.

**Comment by oli-obk** [comment]
so the mozjs error is valid. I'm not sure what causes it at the moment, but it's a const evaluation from within the const propagator, I'll investigate tomorrow. 

```
TRACE:<unknown>: const eval: ParamEnvAnd { param_env: ParamEnv { caller_bounds: Slice([Binder(TraitPredicate(<T as rust::CustomTrace>)), Binder(TraitPredicate(<T as std::marker::Sized>))]), reveal: UserFacing }, value: GlobalId { instance: Instance { def: Item(DefId(0/0:266 ~ mozjs[5305]::rust[0]::CustomAutoTraceable[0]::vftable[0])), substs: Slice([rust::CustomAutoRooter<T>]) }, promoted: None } }
DEBUG:<unknown>: eval_body: GlobalId { instance: Instance { def: Item(DefId(0/0:266 ~ mozjs[5305]::rust[0]::CustomAutoTraceable[0]::vftable[0])), substs: Slice([rust::CustomAutoRooter<T>]) }, promoted: None }, ParamEnv { caller_bounds: Slice([Binder(TraitPredicate(<T as rust::CustomTrace>)), Binder(TraitPredicate(<T as std::marker::Sized>))]), reveal: UserFacing }
TRACE:<unknown>: load mir Item(DefId(0/0:266 ~ mozjs[5305]::rust[0]::CustomAutoTraceable[0]::vftable[0]))
TRACE:<unknown>: const_eval: pushing stack frame for global: rust::CustomAutoTraceable::vftable
TRACE:<unknown>: StorageLive(_1)
TRACE:<unknown>: _1 is now live
TRACE:<unknown>: _1 = const rust::CustomAutoTraceable::trace as unsafe extern "C" fn(*mut std::os::raw::c_void, *mut jsapi::JSTracer) (ReifyFnPointer)
TRACE:<unknown>: _1: Undef
error: internal compiler error: librustc/infer/mod.rs:641: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<rust::CustomAutoRooter<T> as rust::CustomTrace>)),depth=1),Unimplemented)]` resolving bounds after type-checking
```

**Comment by alexreg** [comment]
Hey @aidanhs. Any update on the crater run? I remember you saying on IRC a couple of days ago it should be done by now. 😊

**Comment by mark-i-m** [comment]
@alexreg Yep, they already posted results, but it is hidden by GitHub: https://github.com/rust-lang/rust/pull/46882#issuecomment-366553368

Also see https://github.com/rust-lang/rust/pull/46882#issuecomment-366555054

**Comment by mark-i-m** [comment]
@oli-obk 

> So about the const oom error. Finding a good default limit is hard. We could simply disable that limit. Either people will run into the real memory limit and rustc will oom, or it'll work.

I'm guessing you mean only for memory, right? That send like a reasonable approach.

Also, for the instruction limit, do you have any opinions on implementing the "branch limit" discussed above?

**Comment by CAD97** [comment]
Hi, I'm the author of the 31k-element array slice in UNIC. If anyone wants more info on why that monster exists, feel free to ping me and I can explain.

Making that specific case more interesting is a lot of factors. It's split into a file of const declarations and the actual map sperately because if I put them in one expression, the time scale of compile blows up, even on stable. I'm honestly terrified to mess with that file because I have no idea why it compiles in a reasonable amount of time, and any attempt to experiment usually doesn't, even when they seem identical to me.

The branch solution of counting seems like it would work. I'd also be happy to hide the issue by coming up with another solution, but the huge slice really is a map from most char to a slice of string slices.

**Comment by oli-obk** [comment]
* brotli works now (no more memory limit)
* unic works now (step limit is the number of executed branches, not statements)
* mozjs works now (I applied a substitution to itself -.- fixed)

one last review before launch @eddby ?

**Comment by eddyb** [comment]
@bors r+ p=1098

Let's get this ~~landed~~ up there!

**Comment by BatmanAoD** [comment]
@oli-obk How does the compile time compare to stable for UNIC now that it works with this branch?

**Comment by CAD97** [comment]
@BatmanAoD I got ~20s on `(27a046e93 2018-02-18)`, I'll `-Z time-passes` on this branch this evening for a proper comparison. For UNIC specifically, [we've got some ideas to restructure that table now anyway](https://www.reddit.com/r/rust/comments/7ysnl5/31k_array_slice_what_are_my_other_options/).

**Comment by Aaron1011** [comment]
Travis CI error:

```
[01:12:03] 
[01:12:03] failures:
[01:12:03] 
[01:12:03] ---- [run-pass] run-pass/const-negation.rs stdout ----
[01:12:03] 	
[01:12:03] error: test run failed!
[01:12:03] status: exit code: 101
[01:12:03] command: "/checkout/obj/build/i686-unknown-linux-gnu/test/run-pass/const-negation.stage2-i686-unknown-linux-gnu"
[01:12:03] stdout:
[01:12:03] ------------------------------------------
[01:12:03] 
[01:12:03] ------------------------------------------
[01:12:03] stderr:
[01:12:03] ------------------------------------------
[01:12:03] thread 'main' panicked at 'assertion failed: `(left == right)`
[01:12:03]   left: `9223372036854775808`,
[01:12:03]  right: `0`', /checkout/src/test/run-pass/const-negation.rs:24:5
[01:12:03] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:12:03] 
[01:12:03] ------------------------------------------
[01:12:03] 
[01:12:03] thread '[run-pass] run-pass/const-negation.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2892:9
[01:12:03] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:12:03] 
[01:12:03] 
[01:12:03] failures:
[01:12:03]     [run-pass] run-pass/const-negation.rs
[01:12:03] 
[01:12:03] test result: [31mFAILED(B[m. 2925 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out
[01:12:03] 
[01:12:03] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22
[01:12:03] 
```

File: src/librustc/ty/mod.rs [hunk 40]
```diff
@@ -1800,10 +1800,34 @@ impl<'a, 'gcx, 'tcx> AdtDef {
...
+                                .unwrap_or_else(|| {
+                                bug!("MIR: discriminants({:?}, {:?}) got \
+                                    type with inference types/regions",
+                                    ty, param_env);
+                            });
+                            let size = tcx.global_tcx()
+                                .layout_of(param_env.and(ty))
+                                .expect("int layout")
+                                .size
+                                .bits();
```
Comment (eddyb) [inline src/librustc/ty/mod.rs]: Can you skip this by going from `repr_type` to `layout::Integer` directly?

File: src/librustc_mir/hair/cx/mod.rs [hunk 41]
```diff
@@ -149,13 +149,34 @@ impl<'a, 'gcx, 'tcx> Cx<'a, 'gcx, 'tcx> {
...
+        ty: Ty<'tcx>,
+    ) -> u64 {
+        let tcx = self.tcx.global_tcx();
+        let (ty, param_env) = self
+            .tcx
+            .lift_to_global(&(ty, self.param_env))
+            .unwrap_or_else(|| {
+            bug!("MIR: Cx::const_eval_literal({:?}, {:?}) got \
+                type with inference types/regions",
+                ty, self.param_env);
```
Comment (eddyb) [inline src/librustc_mir/hair/cx/mod.rs]: Again, this is perhaps avoidable?

File: src/librustc_mir/interpret/memory.rs [hunk 42]
```diff
@@ -666,7 +666,10 @@ impl<'a, 'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'a, 'mir, 'tcx, M> {
         }
         // Now we do the actual reading
         let bytes = if signed {
-            read_target_int(endianness, bytes).unwrap() as u128
+            let bytes = read_target_int(endianness, bytes).unwrap() as u128;
+            let amt = 128 - (size * 8);
+            // truncate (shift left to drop out leftover values, shift right to fill with zeroes)
+            (bytes << amt) >> amt
```
Comment (eddyb) [inline src/librustc_mir/interpret/memory.rs]: Just don't have signed reads at all. Remove any kind of signed integer usage wrt `byteorder`.

File: src/librustc_mir/interpret/operator.rs [hunk 43]
```diff
@@ -197,94 +137,129 @@ impl<'a, 'mir, 'tcx, M: Machine<'mir, 'tcx>> EvalContext<'a, 'mir, 'tcx, M> {
...
+                        }
+                    },
+                    _ => {},
+                }
+                trace!("{}, {}, {}", l, l128, r);
+                let (result, mut oflo) = op(l128, r);
+                trace!("{}, {}", result, oflo);
+                if !oflo && size != 128 {
+                    let max = 1 << (size - 1);
+                    oflo = result >= max || result < -max;
```
Comment (eddyb) [inline src/librustc_mir/interpret/operator.rs]: Can't you write this as `sign_extend(truncated, left_ty) != truncated`?

File: src/librustc_mir/interpret/operator.rs [hunk 44]
```diff
@@ -153,11 +85,19 @@ impl<'a, 'mir, 'tcx, M: Machine<'mir, 'tcx>> EvalContext<'a, 'mir, 'tcx, M> {
...
                 _ => bug!("it has already been checked that this is a shift op"),
             };
+            let l = if left_ty.is_signed() {
+                self.sign_extend(l, left_ty)?
+            } else {
+                l
+            };
+            let (result, oflo) = op(l, r as u32);
+            let truncated = self.truncate(result, left_ty)?;
+            return Ok((PrimVal::Bytes(truncated), oflo || truncated != result));
```
Comment (eddyb) [inline src/librustc_mir/interpret/operator.rs]: I don't think this works for signed shifts (since the truncated form doesn't have the sign-extend bits anymore) - also, doesn't "overflowing" refer to the shift count being larger the bitwidth, not the value going out of range? but I'm not sure.

File: src/librustc_mir/interpret/operator.rs [hunk 45]
```diff
@@ -197,94 +137,129 @@ impl<'a, 'mir, 'tcx, M: Machine<'mir, 'tcx>> EvalContext<'a, 'mir, 'tcx, M> {
...
+        if let ty::TyFloat(fty) = left_ty.sty {
+            return Ok((float_op(bin_op, l, r, fty), false));
+        }
 
-            (Add, k) if k.is_int() => return int_arithmetic!(k, overflowing_add, l, r),
-            (Sub, k) if k.is_int() => return int_arithmetic!(k, overflowing_sub, l, r),
-            (Mul, k) if k.is_int() => return int_arithmetic!(k, overflowing_mul, l, r),
-            (Div, k) if k.is_int() => return int_arithmetic!(k, overflowing_div, l, r),
-            (Rem, k) if k.is_int() => return int_arithmetic!(k, overflowing_rem, l, r),
+        // only ints left
```
Comment (eddyb) [inline src/librustc_mir/interpret/operator.rs]: Does this mean to say "unsigned integers"?

File: src/librustc/ty/mod.rs [hunk 46]
```diff
@@ -1778,64 +1778,77 @@ impl<'a, 'gcx, 'tcx> AdtDef {
...
+                        .unwrap_or_else(|| {
+                        bug!("MIR: discriminants({:?}, {:?}) got \
+                            type with inference types/regions",
+                            ty, param_env);
+                    });
+                    let size = tcx.global_tcx()
+                        .layout_of(param_env.and(ty))
+                        .expect("int layout")
+                        .size
+                        .bits();
```
Comment (eddyb) [inline src/librustc/ty/mod.rs]: Can you skip this by going from `repr_type` to `layout::Integer` directly?

File: src/librustc_mir/hair/cx/mod.rs [hunk 47]
```diff
@@ -151,22 +151,13 @@ impl<'a, 'gcx, 'tcx> Cx<'a, 'gcx, 'tcx> {
...
-            .layout_of(param_env.and(ty))
-            .expect("int layout")
-            .size
-            .bits()
+        match ty.sty {
+            TyInt(ity) => ity.bit_width(),
+            TyUint(uti) => uty.bit_width(),
+            _ => bug!("{} is not an integer"),
+        }.unwrap_or_else(|| self.tcx.data_layout.pointer_size.bits())
     }
```
Comment (eddyb) [inline src/librustc_mir/hair/cx/mod.rs]: Can you inline this or something?

File: src/librustc_mir/hair/cx/mod.rs [hunk 48]
```diff
@@ -151,22 +151,13 @@ impl<'a, 'gcx, 'tcx> Cx<'a, 'gcx, 'tcx> {
...
-                ty, self.param_env);
-        });
-        tcx
-            .layout_of(param_env.and(ty))
-            .expect("int layout")
-            .size
-            .bits()
+        match ty.sty {
+            TyInt(ity) => ity.bit_width(),
+            TyUint(uti) => uty.bit_width(),
```
Comment (eddyb) [inline src/librustc_mir/hair/cx/mod.rs]: I don't expect this to work without a `tcx`... `usize` is a thing.

File: src/librustc_mir/interpret/memory.rs [hunk 49]
```diff
@@ -690,7 +683,7 @@ impl<'a, 'mir, 'tcx, M: Machine<'mir, 'tcx>> Memory<'a, 'mir, 'tcx, M> {
     }
 
     pub fn read_ptr_sized_unsigned(&self, ptr: MemoryPointer, ptr_align: Align) -> EvalResult<'tcx, PrimVal> {
```
Comment (eddyb) [inline src/librustc_mir/interpret/memory.rs]: "unsigned" or "signed" in names of memory functions should not be needed.

**Comment by mark-i-m** [comment]
I think we will give @bors a heart attack in this PR :stuck_out_tongue:

File: src/librustc_mir/hair/cx/mod.rs (hunk 48 above)
Comment (oli-obk) [reply src/librustc_mir/hair/cx/mod.rs]: these result in `none` if it's `usize`/`isize`, that's what the `unwrap_or_else` handles

File: src/librustc_mir/hair/cx/mod.rs (hunk 47 above)
Comment (oli-obk) [reply src/librustc_mir/hair/cx/mod.rs]: It's used 3 times.

File: src/librustc_mir/interpret/operator.rs (hunk 45 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operator.rs]: no, all ops that don't differ between signed and unsigned are handled here, too

File: src/librustc_mir/interpret/operator.rs (hunk 44 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operator.rs]: yea I already fixed that ^^

File: src/librustc_mir/interpret/operator.rs (hunk 43 above)
Comment (oli-obk) [reply src/librustc_mir/interpret/operator.rs]: I think this is much clearer. Also we'd run into the difference of the zeroes and ones on the left side again

**Comment by kennytm** [comment]
The rustc at stage1 segfault'ed when compiling `semver-parser v0.7.0` and/or `bitflags v0.9.1`.

<details>

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Thread 1 Crashed:: rustc
0   librustc-fd54ffcf10c10ca4.dylib	0x000000010fac8aed rustc::ich::hcx::_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$a$GT$$GT$$u20$for$u20$syntax_pos..span_encoding..Span$GT$::hash_stable::h527fb5f7c5b52558 + 733
1   librustc-fd54ffcf10c10ca4.dylib	0x000000010fad33a9 rustc::ich::impls_syntax::_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$a$GT$$GT$$u20$for$u20$$u5b$syntax..ast..Attribute$u5d$$GT$::hash_stable::h18ca05a96f1f42d6 + 2681
2   librustc-fd54ffcf10c10ca4.dylib	0x000000010fa993b9 _$LT$rustc..hir..map..collector..HirItemLike$LT$T$GT$$u20$as$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$hir$GT$$GT$$GT$::hash_stable::h982ccf22a29e02eb + 201
3   librustc-fd54ffcf10c10ca4.dylib	0x000000010fa087f8 rustc::dep_graph::graph::DepGraph::with_task::h5b7859a5e0500e46 + 2888
4   librustc-fd54ffcf10c10ca4.dylib	0x000000010fa96ee2 _$LT$rustc..hir..map..collector..NodeCollector$LT$$u27$a$C$$u20$$u27$hir$GT$$u20$as$u20$rustc..hir..intravisit..Visitor$LT$$u27$hir$GT$$GT$::visit_item::h9ef1df518350926b + 338
5   librustc-fd54ffcf10c10ca4.dylib	0x000000010faa8198 rustc::hir::map::map_crate::h5bbb241ee119e406 + 4904
6   librustc_driver-983cbf538e38e553.dylib	0x000000010e5a6ed3 rustc_driver::driver::compile_input::hd5ace6d7d5a4ae26 + 9875
7   librustc_driver-983cbf538e38e553.dylib	0x000000010e5c465f rustc_driver::run_compiler::h437ae108b51dac3b + 4479
8   librustc_driver-983cbf538e38e553.dylib	0x000000010e4ee336 std::sys_common::backtrace::__rust_begin_short_backtrace::he49f79e66e5373d2 + 1046
9   libstd-baf4feb790fe1273.dylib 	0x00000001111fa74f __rust_maybe_catch_panic + 31 (lib.rs:110)
10  librustc_driver-983cbf538e38e553.dylib	0x000000010e52a106 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h88c8863e6b781c9f + 134
11  libstd-baf4feb790fe1273.dylib 	0x00000001111ef4cc std::sys::unix::thread::Thread::new::thread_start::h6f25bdfb8af0a62d + 140 (thread.rs:25)
12  libsystem_pthread.dylib       	0x00007fff91b6999d _pthread_body + 131
13  libsystem_pthread.dylib       	0x00007fff91b6991a _pthread_start + 168
14  libsystem_pthread.dylib       	0x00007fff91b67351 thread_start + 13

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000111e11c68  rbx: 0x0000000000000100  rcx: 0x0000000000000006  rdx: 0x0000000115800000
  rdi: 0x000000010ffca930  rsi: 0x000000000000000a  rbp: 0x0000700000ff98c0  rsp: 0x0000700000ff97d0
   r8: 0xffffffffffffff68   r9: 0x7ffffffffffff000  r10: 0x0000000111516701  r11: 0x00000001111e6510
  r12: 0x0000000111e6b640  r13: 0x0000000000000000  r14: 0x0000700000ff9ce0  r15: 0x0000000000000000
  rip: 0x000000010fac8aed  rfl: 0x0000000000010202  cr2: 0x00000001110b66c0
```

</details>

The stack trace indicates the segfault happens at the `hash_stable` implementation of `Span`.

**Comment by eddyb** [comment]
@varkor pointed out on IRC that they could build this PR on macOS without issues. Maybe transient?

@bors retry

**Comment by kennytm** [comment]
Have they tried building stage2-cargo? The segfault happens when building stage2-cargo.

**Comment by Manishearth** [comment]
@bors r=eddyb

(rollup prioritization)

**Comment by oli-obk** [comment]
Legit. Some tests don't seem to be producing the correct lints anymore. These are usually caused by changes to MIR causing the const propagator to fail

**Comment by shepmaster** [comment]
Ping from triage, @oli-obk! It's been a few weeks since we've heard from you, will you have time to address the merge conflicts?

**Comment by oli-obk** [comment]
And we are back in business.

@bors r=eddyb

**Comment by oli-obk** [comment]
It looks like some PR changed some MIR optimizations from running unconditionally to running only with anything other than `-O0` and said optimizations were needed for the analyses producing bitshift errors to be able to work.

**Comment by alexreg** [comment]
@oli-obk Do you know how to resolve it?

**Comment by oli-obk** [comment]
Yea, but it will necessitate running some Mir opts unconditionally, which is against what's planned elsewhere for improving compilation perf

File: src/librustc_mir/transform/const_prop.rs [hunk 50]
```diff
@@ -134,15 +169,43 @@ impl<'b, 'a, 'tcx:'b> ConstPropagator<'b, 'a, 'tcx> {
...
+                        Value::ByValPair(a, b) => {
+                            trace!("by val pair: {:?}, {:?}", a, b);
+                            let base_layout = self.tcx.layout_of(self.param_env.and(ty)).ok()?;
+                            trace!("layout computed");
+                            use rustc_data_structures::indexed_vec::Idx;
+                            let field_index = field.index();
+                            let val = if field_index == 0 {
+                                a
+                            } else {
+                                assert_eq!(field_index, 1);
```
Comment (eddyb) [inline src/librustc_mir/transform/const_prop.rs]: You can write this shorter as `[a, b][field_index]`

**Comment by alexcrichton** [comment]
@bors: retry

pushed to master to kicking bors

**Comment by alexcrichton** [comment]
@bors: retry

pushed to master, so kicking bors

**Comment by lqd** [comment]
Looks like a compile error in `librustc_lint/types.rs` ?
<details>

```
[00:15:40] error[E0425]: cannot find function `int_ty_bits` in this scope
[00:15:40]    --> librustc_lint/types.rs:368:32
[00:15:40]     |
[00:15:40] 368 |                     let bits = int_ty_bits(t, cx.sess().target.isize_ty);
[00:15:40]     |                                ^^^^^^^^^^^ not found in this scope
[00:15:40] 
[00:15:40] error[E0425]: cannot find function `uint_ty_bits` in this scope
[00:15:40]    --> librustc_lint/types.rs:373:32
[00:15:40]     |
[00:15:40] 373 |                     let bits = uint_ty_bits(t, cx.sess().target.usize_ty);
[00:15:40]     |                                ^^^^^^^^^^^^ not found in this scope
[00:15:40] 
[00:15:41] error: aborting due to 2 previous errors
[00:15:41] 
[00:15:41] error: Could not compile `rustc_lint`.
```

</details>

**Comment by oli-obk** [comment]
I wonder why this didn't cause a merge conflict.

**Comment by oli-obk** [comment]
@bors r-

the new overflow lint suggestion doesn't cope with miri at runtime :/

**Comment by oli-obk** [comment]
@bors r+

tests pass now on stage1 locally

**Comment by phil-opp** [comment]
@oli-obk I think you meant to write `@bors r=eddyb`?

**Comment by oli-obk** [comment]
@bors r=eddyb

my bad... and bors, why do you even allow me to r+ my own PRs?

**Comment by oli-obk** [comment]
Ok, so it seems the apple issue is legit.

```
[01:05:23] [m[m[32m[1m   Compiling[m fnv v1.0.6
[01:05:23] [m[m[32m[1m   Compiling[m unicode-xid v0.0.4
[01:05:23] [m[m[31m[1merror:[m Could not compile `fnv`.
[01:05:23] [m[m[33m[1mwarning:[m build failed, waiting for other jobs to finish...
[01:05:23] [m[m[31m[1merror:[m Could not compile `unicode-xid`.
[01:05:23] 
[01:05:23] To learn more, run the command again with --verbose.
[01:05:23] 
[01:05:23] 
[01:05:23] command did not execute successfully: "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "--release" "--locked" "--color" "always" "--manifest-path" "/Users/travis/build/rust-lang/rust/src/tools/cargo/Cargo.toml"
[01:05:23] expected success, got: exit code: 101
[01:05:23] 
[01:05:23] 
[01:05:23] failed to run: /Users/travis/build/rust-lang/rust/build/bootstrap/debug/bootstrap build
[01:05:23] Build completed unsuccessfully in 0:58:18
[01:05:23] make: *** [all] Error 1
```

again in hash_stable

any help from mac users is welcome.

**Comment by michaelwoerister** [comment]
The `hash_stable` implementation in question (in `hcx.rs`) does not contain unsafe code, afaict. The only kind of special thing about it is that it uses a thread-local. No idea, what's wrong here.

**Comment by oli-obk** [comment]
@varkor was not able to reproduce on x86_64 "Darwin Kernel Version 15.6.0"

@eddyb suggested it might be the packed field of `Span`, which was

```rust
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
#[repr(packed)]
pub struct Span(u32);
```

and which looks very suspicious.

I changed them to manual impls

@bors r=eddyb

**Comment by lqd** [comment]
This time it's the appveyor 3-hour limit :(

**Comment by oli-obk** [comment]
So does that mean it's this PR which slows down things or is it the slowdown due to the recent ui test regression?

**Comment by mati865** [comment]
@oli-obk Appveyor timeouts are quite common recently and probably unrelated to those changes https://github.com/rust-lang/rust/issues/46903

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout.

We see that in `check-aux` the timing taken for "stage1-rustc" becomes extremely long (37 minutes); however, the `check x86_64-pc-windows-msvc` job having a similar configuration finished this step in 26 minutes, meaning the slowdown is likely a CI issue, irrelevant to this PR.

<details><summary>Timing breakdown for check-aux in this PR (timed out)</summary>

```
make-prepare                	  65.15
stage0-tidy                 	  73.36
stage0-std                  	  17.30
stage0-rustc                	1424.26
llvm                        	 823.23
stage0-trans-llvm           	 182.20
stage1-std                  	 126.71
stage1-test                 	  27.57
stage1-rustc                	2239.32
stage1-trans-llvm           	 247.80
stage2-rustdoc              	 324.59
stage0-std                  	 104.52
stage0-rustbook             	 306.99
stage2-rustdoc              	 120.23
doc/compiler                	 101.96
stage2-error_index_generator	  14.68
stage0-std                  	1165.44
stage2-rustdoc              	 525.90
test/libtools               	   3.70
```

</details>
<details><summary>Timing breakdown for x86_64-pc-windows-msvc in this PR (successful)</summary>

```
make-prepare                	  54.41
stage0-tidy                 	  63.19
bootstrap                   	  14.34
stage0-rustc                	1064.20
llvm                        	 605.31
stage0-trans-llvm           	 158.20
stage1-std                  	  86.37
stage1-test                 	  20.22
stage1-rustc                	1542.76
stage1-trans-llvm           	 177.77
stage0-compiletest          	  95.39
test/ui                     	 166.80
test/run-pass               	1276.29
test/compile-fail           	 283.06
test/parse-fail             	   6.64
test/run-fail               	  27.72
test/run-pass-valgrind      	   4.29
test/mir-opt                	  29.86
test/codegen                	   5.08
test/codegen-units          	   4.53
test/incremental            	  27.52
test/ui-fulldeps            	  49.75
test/run-pass-fulldeps      	 365.32
test/run-fail-fulldeps      	   5.56
test/compile-fail-fulldeps  	 109.74
test/incremental-fulldeps   	   4.03
stage2-rustdoc              	 192.70
test/rustdoc                	 192.26
test/run-make               	  98.72
stage1-test-term            	   4.82
test/libtest                	   7.93
stage1-test-test            	  14.16
test/libtest                	  15.03
stage1-test-alloc           	  72.97
test/libstd                 	 188.13
stage1-test-alloc_system    	  80.47
test/libstd                 	 302.89
stage1-test-panic_abort     	 145.38
test/libstd                 	 318.69
stage1-test-std_unicode     	   1.57
test/libstd                 	  12.56
stage1-test-unwind          	   2.93
test/librustc               	   3.41
stage1-test-fmt_macros      	   1.78
test/librustc               	   2.23
stage1-test-graphviz        	   2.90
test/librustc               	   3.32
stage1-test-proc_macro      	   1.56
test/librustc               	   2.41
stage1-test-rustc           	 120.80
test/librustc               	 120.98
stage1-test-rustc_allocator 	  24.44
test/librustc               	  25.10
stage1-test-rustc_back      	  16.91
test/librustc               	  17.41
stage1-test-rustc_borrowck  	   1.10
test/librustc               	   1.53
stage1-test-rustc_data_structures	  21.69
test/librustc               	  22.15
stage1-test-rustc_driver    	  81.00
test/librustc               	  81.90
stage1-test-rustc_errors    	   2.12
test/librustc               	   2.56
stage1-test-rustc_incremental	   5.39
test/librustc               	   5.85
stage1-test-rustc_lint      	   5.15
test/librustc               	   5.64
stage1-test-rustc_mir       	  31.99
test/librustc               	  32.46
stage1-test-rustc_passes    	   1.86
test/librustc               	   2.34
stage1-test-rustc_platform_intrinsics	   3.63
test/librustc               	   4.05
stage1-test-rustc_plugin    	   1.26
test/librustc               	   1.73
stage1-test-rustc_privacy   	   1.75
test/librustc               	   2.23
stage1-test-rustc_resolve   	   3.18
test/librustc               	   3.67
stage1-test-rustc_trans_utils	  27.67
test/librustc               	  30.30
stage1-test-syntax          	  98.64
test/librustc               	  99.34
stage1-test-syntax_ext      	   5.86
test/librustc               	   6.32
stage1-test-syntax_pos      	   3.37
test/librustc               	   3.87
stage1-test-rustc-main      	   4.29
test/librustc               	   4.82
stage0-unstable-book-gen    	  64.39
stage0-rustbook             	 130.89
doc/std                     	  75.60
doc/compiler                	  68.46
stage2-error_index_generator	   8.13
stage0-linkchecker          	   3.96
test/linkchecker            	  51.65
stage2-test-error-index     	  45.04
test/docs                   	   1.49
test/docs                   	  12.80
stage0-rustdoc-themes       	   1.15
```

</details>
<details><summary>Timing breakdown for check-aux the <a href="https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6578">previous successful build</a></summary>

```
make-prepare                	  51.35
stage0-tidy                 	  57.40
stage0-std                  	  13.71
stage0-rustc                	1069.22
llvm                        	 614.37
stage0-trans-llvm           	 160.10
stage1-std                  	  86.24
stage1-test                 	  21.71
stage1-rustc                	1591.91
stage1-trans-llvm           	 170.95
stage2-rustdoc              	 185.61
stage0-std                  	  61.91
stage0-rustbook             	 188.73
stage2-rustdoc              	  80.42
doc/compiler                	  75.45
stage2-error_index_generator	  11.23
stage0-std                  	 705.76
stage2-rustdoc              	 333.91
test/libtools               	   3.80
test/docs/webrender         	1515.81
stage0-compiletest          	  38.58
test/pretty                 	   8.77
test/run-pass               	 742.96
test/run-fail               	  12.51
test/run-pass-valgrind      	   1.63
test/run-pass-fulldeps      	 233.18
```

</details>
<details><summary>Timing breakdown for x86_64-pc-windows-msvc of the <a href="https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6578">previous successful build</a></summary>

```
make-prepare                	  60.48
stage0-tidy                 	  66.40
bootstrap                   	  15.72
stage0-rustc                	1242.56
llvm                        	 800.12
stage0-trans-llvm           	 153.20
stage1-std                  	  85.51
stage1-test                 	  21.59
stage1-rustc                	1697.63
stage1-trans-llvm           	 183.22
stage0-compiletest          	 103.85
test/ui                     	 166.65
test/run-pass               	1255.94
test/compile-fail           	 285.24
test/parse-fail             	   6.97
test/run-fail               	  28.59
test/run-pass-valgrind      	   4.47
test/mir-opt                	  28.51
test/codegen                	   5.45
test/codegen-units          	   4.90
test/incremental            	  31.04
test/ui-fulldeps            	  54.51
test/run-pass-fulldeps      	 386.22
test/run-fail-fulldeps      	   4.99
test/compile-fail-fulldeps  	 115.49
test/incremental-fulldeps   	   4.00
stage2-rustdoc              	 200.88
test/rustdoc                	 203.10
test/run-make               	 100.83
stage1-test-term            	   4.84
test/libtest                	   6.70
stage1-test-test            	  15.39
test/libtest                	  16.33
stage1-test-alloc           	  76.62
test/libstd                 	 189.71
stage1-test-alloc_system    	  80.49
test/libstd                 	 304.58
stage1-test-panic_abort     	 148.80
test/libstd                 	 310.72
stage1-test-std_unicode     	   1.46
test/libstd                 	  11.54
stage1-test-unwind          	   3.30
test/librustc               	   3.51
stage1-test-fmt_macros      	   1.81
test/librustc               	   2.25
stage1-test-graphviz        	   3.30
test/librustc               	   3.48
stage1-test-proc_macro      	   1.55
test/librustc               	   2.14
stage1-test-rustc           	 129.51
test/librustc               	 130.28
stage1-test-rustc_allocator 	  26.61
test/librustc               	  27.31
stage1-test-rustc_back      	  17.84
test/librustc               	  18.36
stage1-test-rustc_borrowck  	   3.23
test/librustc               	   3.73
stage1-test-rustc_const_math	   1.62
test/librustc               	   2.09
stage1-test-rustc_data_structures	  22.81
test/librustc               	  23.31
stage1-test-rustc_driver    	  85.60
test/librustc               	  85.85
stage1-test-rustc_errors    	   2.50
test/librustc               	   2.50
stage1-test-rustc_incremental	   5.78
test/librustc               	   6.26
stage1-test-rustc_lint      	   5.15
test/librustc               	   5.65
stage1-test-rustc_mir       	  30.99
test/librustc               	  31.51
stage1-test-rustc_passes    	   1.96
test/librustc               	   2.46
stage1-test-rustc_platform_intrinsics	   3.23
test/librustc               	   3.66
stage1-test-rustc_plugin    	   1.26
test/librustc               	   1.76
stage1-test-rustc_privacy   	   1.76
test/librustc               	   2.24
stage1-test-rustc_resolve   	   2.90
test/librustc               	   3.40
stage1-test-rustc_trans_utils	  29.50
test/librustc               	  31.78
stage1-test-syntax          	 103.67
test/librustc               	 104.41
stage1-test-syntax_ext      	   6.00
test/librustc               	   6.47
stage1-test-syntax_pos      	   3.36
test/librustc               	   3.84
stage1-test-rustc-main      	   2.56
test/librustc               	   3.10
stage0-unstable-book-gen    	  67.97
stage0-rustbook             	 140.55
doc/std                     	  71.37
doc/compiler                	  70.99
stage2-error_index_generator	   6.53
stage0-linkchecker          	   3.50
test/linkchecker            	  51.51
stage2-test-error-index     	  47.34
test/docs                   	   1.60
test/docs                   	  13.44
stage0-rustdoc-themes       	   1.21
```

</details>
<details><summary>Timing breakdown for check-aux of the <a href="https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6569">most recently timed out build</a></summary>

```
make-prepare                	  77.66
stage0-tidy                 	  95.48
stage0-std                  	  19.65
stage0-rustc                	1323.70
llvm                        	 776.49
stage0-trans-llvm           	 208.99
stage1-std                  	 112.21
stage1-test                 	  25.96
stage1-rustc                	1975.00
stage1-trans-llvm           	 202.50
stage2-rustdoc              	 233.37
stage0-std                  	  71.16
stage0-rustbook             	 244.46
stage2-rustdoc              	 109.67
doc/compiler                	  99.90
stage2-error_index_generator	  12.77
stage0-std                  	 960.23
stage2-rustdoc              	 504.24
test/libtools               	   3.70
test/docs/webrender         	1857.61
stage0-compiletest          	  34.22
test/pretty                 	   7.46
```

</details>

**Comment by kennytm** [comment]
@bors p=69

Let #48809 go in first, to reduce the chance for further timeouts.

**Comment by BatmanAoD** [comment]
:fireworks: Wooooo! Congratulations, everyone!

**Comment by bdrewery** [comment]
Getting a weird build crash on FreeBSD after this merge #48888

**Comment by ur0** [comment]
I'm sorry if this isn't the right place, but are tuple struct constructors available in the latest stable build (2018-03-25)?

**Comment by oli-obk** [comment]
This is as good a place as any other ;)

No they're not in the current stable. they'll be in the next stable (so they are in the current beta)
