### PR TITLE
Collect function instance used in `global_asm!` sym operand

### LINKED ISSUE #96623: `global_asm!` sym operands emit functions without function body
### Summary

If a function is only referenced by a `sym` operand in `global_asm!`, the definition/body of that function will not be emitted by the compiler, and the linker will fail with `unresolved symbol` error.

### Reproduction

Save the following code as `example.rs`:  (https://rust.godbolt.org/z/4jbf3eWjb)
```rust
#![no_std]
#![no_main]
#![feature(asm_sym)]
use core::arch::global_asm;

fn foo() {
    loop {}
}

static MY_STATIC: i32 = 0;

global_asm!(".global _start", "_start:", "call {}", sym foo);                       // ^1
// global_asm!(".global _start", "_start:", "lea rax, [rip + {}]", sym MY_STATIC);  // ^2

// #[no_mangle]                                                                     // ^3
// unsafe extern "sysv64" fn _start() {
//     core::arch::asm!("call {}", sym foo)
// }

#[panic_handler]
fn handle_panic(_panic: &core::panic::PanicInfo<'_>) -> ! {
    //foo();                                                                        // ^4
    loop {}
}
```
<sup>(`.global _start` is there to stop the linker from pruning unreachable code.)</sup>

Run `rustc example.rs -Cpanic=abort -Clink-args="-nostdlib"` produces a linker error "undefined reference to `example::main`":
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "example.example.2372ba8c-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-16d69221f10b0282.rlib" "-Wl,-Bdynamic" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "example" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-nostdlib"
note: /usr/bin/ld: example.example.2372ba8c-cgu.0.rcgu.o: in function `_start':
          example.2372ba8c-cgu.0:(.text+0x1): undefined reference to `example::foo'
```

`objdump -td example.example.2372ba8c-cgu.0.rcgu.o` verifies that `example::foo` is indeed missing:
```
0000000000000000 g       .text  0000000000000000 _start
0000000000000000         *UND*  0000000000000000 _ZN7example3foo17h902e29a481949057E
```

The emitted llvm-ir looks something like this:
```llvm
module asm ".global _start"
module asm "_start:"
module asm "call _ZN7example3foo17h902e29a481949057E"

@llvm.compiler.used = appending global [1 x i8*] [i8* bitcast (void ()* @_ZN7example3foo17h902e29a481949057E to i8*)], section "llvm.metadata"

; example::foo
; Function Attrs: nounwind nonlazybind
declare void @_ZN7example3foo17h902e29a481949057E() unnamed_addr #1
```

### Some observations

* The problem only appears if the function in question isn't used anywhere else. If we uncomment line `^4`, the resulting IR will be correctly emitted:
    
    ```llvm
    ; omit identical part
    
    ; example::foo
    ; Function Attrs: nounwind nonlazybind
    define internal void @_ZN7example3foo17h902e29a481949057E() unnamed_addr #0 {
    start:
      br label %bb1
    bb1:                                              ; preds = %bb1, %start
      br label %bb1
    }
    ```

* Only functions can reproduce, static items work fine, as per line `^2`.

* Only `global_asm!` can reproduce, `asm!` works fine, as per line `^3` and co.

### Meta

```
rustc 1.62.0-nightly (7c4b47696 2022-04-30)
binary: rustc
commit-hash: 7c4b47696907d64eff5621a64eb3c6e795a9ec77
commit-date: 2022-04-30
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

cc @Amanieu #94468
@rustbot label +A-inline-assembly +requires-nightly

### PR DESCRIPTION
**Pull request by tmiasko**
The constants used in SymFn operands have FnDef type,
so the type of the constant identifies the function.

Fixes #96623.

### CODE REVIEW

File: src/test/assembly/asm/global_asm.rs [hunk 1]
```diff
@@ -24,3 +25,7 @@ global_asm!("movl ${}, %ecx", const 5, options(att_syntax));
 global_asm!("call {}", sym my_func);
 // CHECK: lea rax, [rip + MY_STATIC]
 global_asm!("lea rax, [rip + {}]", sym MY_STATIC);
+// CHECK: call _RNvCsiubXh4Yz005_10global_asm6foobar
+global_asm!("call {}", sym foobar);
+// CHECK: _RNvCsiubXh4Yz005_10global_asm6foobar:
+fn foobar() { loop {} }
```
Comment (tmiasko) [inline src/test/assembly/asm/global_asm.rs:31]: I started with an empty function here, and noticed an issue where `my_func` and `foobar` had been merged together by `mergefunc` pass, invalidating the reference from global asm. Probably `mergefunc` shouldn't touch symbols from `llvm.compiler.used`?

Comment (Amanieu) [reply src/test/assembly/asm/global_asm.rs:31]: No, mergefunc is perfectly valid here. In general Rust doesn't guarantee that two functions will have separate addresses.

File: compiler/rustc_monomorphize/src/collector.rs [hunk 2]
```diff
@@ -451,6 +451,9 @@ fn collect_items_rec<'tcx>(
                                     collect_const_value(tcx, val, &mut neighbors);
```
Comment (Amanieu) [inline compiler/rustc_monomorphize/src/collector.rs:451]: Since `collect_const_value` isn't doing its job here, you can just remove it entirely.

File: src/test/assembly/asm/global_asm.rs (hunk 1 above)
Comment (tmiasko) [reply src/test/assembly/asm/global_asm.rs:31]: I mean, one of the functions is removed completely, and reference from the global asm is left unresolved.

Comment (Amanieu) [reply src/test/assembly/asm/global_asm.rs:31]: Oh right, that does seem like a bug. If something is in `llvm.compiler.used` then it's likely that it is being referenced using its symbol name, in which case mergefuncs shouldn't rename it. I *think* we can work around this by removing `unnamed_addr` from any symbols referenced by `llvm.compiler.used` in a pass after all values are generated.

Comment (nbdd0121) [reply src/test/assembly/asm/global_asm.rs:31]: I think this is might be related to symbol export. 

Functions that are referenced from inline asm in text form should be listed in `exported_symbols`. We currently don't have any special treatment of asm_sym there.

Comment (tmiasko) [reply src/test/assembly/asm/global_asm.rs:31]: Could you give an example of what you have in mind?

As far as I know, for an inline assembly we do consider this aspect. For example, if a  function with an inline assembly block might be code generated in a different crate (because it is marked inline or generic) and it references a non-generic function, the referenced function will be exported as necessary, etc. In what situation would it be necessary in the case of global asm?

Comment (nbdd0121) [reply src/test/assembly/asm/global_asm.rs:31]: asm_sym is injected into the assembly as text, so when doing LTO/ThinLTO, LLVM would consider the symbol to be unused. This is different from `llvm.compiler.used`, which only marks the function to be used, not the symbol.

Comment (tmiasko) [reply src/test/assembly/asm/global_asm.rs:31]: > This is different from `llvm.compiler.used`, which only marks the function to be used, not the symbol.

I see, but I think this is incorrect. Both `llvm.used` and `llvm.compiler.used` are about symbols, not function per se. The LLVM reference seems quite clear about that. Those lists are also limited to named values for that reason.

Comment (nbdd0121) [reply src/test/assembly/asm/global_asm.rs:31]: I reread LLVM doc, you are correct about that. Some further digging shows that the issue is actually we generate an LLVM IR that marks the function as `internal`: https://godbolt.org/z/c4jPajT48 -- removing the internal linkage will make codegen correct. The symbol export actually doesn't affect the outcome directly -- but it is used indirectly from rustc_monomorphize to determine the linkage.
