### PR TITLE
SimplifyArmIdentity only for locals with the same type

### LINKED ISSUE #66851: Miscompilation with recent Nightlies
Since few Rustc nightly versions I see a miscompilation problem with the code below.
I am using:

```
rustc 1.41.0-nightly (e87a205c2 2019-11-27)
binary: rustc
commit-hash: e87a205c2e117d9fb57f6cdeac0a7f6e95c88316
commit-date: 2019-11-27
host: x86_64-pc-windows-gnu
release: 1.41.0-nightly
LLVM version: 9.0
```

If I compile with:

```
-C opt-level=1 -Z mir-opt-level=1   ==> OK
-C opt-level=0 -Z mir-opt-level=2   ==> OK
-C opt-level=1 -Z mir-opt-level=2   ==> Runtime error
```

The code:

```
#[cfg(debug_assertions)]
use std::convert::TryFrom;

#[cfg(not(debug_assertions))]
macro_rules! to { ($e:expr, $t:ident) => (($e) as $t) }

#[cfg(debug_assertions)]
macro_rules! to { ($e:expr, $t:ident) => ($t::try_from($e).unwrap()) }

fn e103() -> Option<u64> {
    const TARGET: i32 = 7;
    const MAX_COST: i32 = 1 << 12;
    const MAX_COST_U: usize = MAX_COST as _;

    type TSubsets = [i32; 1 << TARGET];
    type TOccupancy = [bool; MAX_COST_U];
    type TMaxMin = [[i32; 2]; 16];

    enum SpecialsRes { Res(u64), Val(i32), Err }

    fn specials(len: i32,
                max_min: &mut TMaxMin,
                mut cost_ceiling: i32,
                vmax: i32,
                ix: i32,
                occupancy: &mut TOccupancy,
                subsets: &mut TSubsets) -> SpecialsRes {
        if ix == len || ix < 0 {
            let mut result = String::new();
            for i in (0 .. ix).rev() {
                result += &subsets[1 << i].to_string();
            }
            return if let Ok(r) = result.parse() {
                SpecialsRes::Res(r)
            } else {
                SpecialsRes::Err
            };
        }

        let mut lo_val: i32 = 0;
        let mut hi_val = vmax;

        for i in 0 .. ix {
            lo_val = lo_val.max(max_min[to!{i, usize} + 1][1] -
                                max_min[to!{i, usize} + 1][0]);
            hi_val = hi_val.min(max_min[to!{i, usize} + 2][0] -
                                max_min[to!{i, usize}][1]);
        }

        let r = len - ix;
        hi_val = hi_val.min(cost_ceiling - lo_val * r - r * (r + 1) / 2);

        let mut v = lo_val + (len - ix);
        while v < hi_val {
            let mut res = true;
            let pl = 1 << ix;
            let mut marked: i32 = 0;

            for i in 0 .. pl {
                let s = subsets[i] + v;
                if occupancy[to!{s, usize}] {
                    res = false;
                    break;
                }
                subsets[pl + i] = s;
                occupancy[to!{s, usize}] = true;
                marked += 1;
            }

            if res {
                let mut new_max_min: TMaxMin = Default::default();
                new_max_min[to!{ix, usize} + 2][0] = std::i32::MAX;

                for i in 1 .. ix + 2 {
                    new_max_min[to!{i, usize}][0] = max_min[to!{i, usize}][0]
                                                    .min(v + max_min[to!{i, usize} - 1][0]);
                    new_max_min[to!{i, usize}][1] = max_min[to!{i, usize}][1]
                                                    .max(v + max_min[to!{i, usize} - 1][1]);
                }

                let res = specials(len,
                                   &mut new_max_min,
                                   cost_ceiling - v,
                                   v,
                                   ix + 1,
                                   occupancy,
                                   subsets);
                match res {
                    SpecialsRes::Res(_) | SpecialsRes::Err => return res,

                    SpecialsRes::Val(val) => {
                        let new_cost_ceiling = v + val;
                        if new_cost_ceiling < cost_ceiling {
                            cost_ceiling = new_cost_ceiling;
                            hi_val = hi_val.min(cost_ceiling - lo_val * r - r * (r + 1) / 2);
                        }
                    }
                }
            }

            for i in 0 .. marked {
                occupancy[to!{subsets[pl + to!{i, usize}], usize}] = false;
            }

            v += 1;
        }

        SpecialsRes::Val(cost_ceiling)
    }

    let mut occupancy: TOccupancy = [false; MAX_COST_U];
    occupancy[0] = true;

    let mut subsets: TSubsets = [0i32; 1 << TARGET as usize];

    let mut max_min: TMaxMin = Default::default();
    max_min[1][0] = std::i32::MAX;

    match specials(TARGET, &mut max_min, MAX_COST,
                   MAX_COST, 0, &mut occupancy, &mut subsets) {
        SpecialsRes::Res(s) => Some(s),
        SpecialsRes::Val(_) | SpecialsRes::Err => None,
    }
}

fn main() {
    assert_eq!(e103(), Some(20_313_839_404_245));
}
```

### LINKED ISSUE #66856: ICE with mir-opt-level=2: store_with_flags: invalid ScalarPair layout
PR #66282 introduced an ICE in the following code with `-Z mir-opt-level=2`:

```rust
enum Src {
    Foo(u8),
    Bar,
}

enum Dst {
    Foo(u8),
}

fn main() {
    let e: Src = Src::Foo(0);
    let _: Dst = match e {
        Src::Foo(x) => Dst::Foo(x),
        Src::Bar => Dst::Foo(0),
    };
}
```

### Compiler output
```
error: internal compiler error: src/librustc_codegen_ssa/mir/operand.rs:329: store_with_flags: invalid ScalarPair layout: TyLayout {
    ty: Dst,
    details: LayoutDetails {
        variants: Single {
            index: 0,
        },
        fields: Arbitrary {
            offsets: [
                Size {
                    raw: 0,
                },
            ],
            memory_index: [
                0,
            ],
        },
        abi: Scalar(
            Scalar {
                value: Int(
                    I8,
                    false,
                ),
                valid_range: 0..=255,
            },
        ),
        largest_niche: None,
        align: AbiAndPrefAlign {
            abi: Align {
                pow2: 0,
            },
            pref: Align {
                pow2: 3,
            },
        },
        size: Size {
            raw: 1,
        },
    },
}

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:892:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_errors::HandlerInner::bug
   9: rustc_errors::Handler::bug
  10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc::ty::context::tls::with_opt::{{closure}}
  12: rustc::ty::context::tls::with_opt
  13: rustc::util::bug::opt_span_bug_fmt
  14: rustc::util::bug::bug_fmt
  15: rustc_codegen_ssa::mir::operand::OperandValue<V>::store_with_flags
  16: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue
  17: rustc_codegen_ssa::mir::codegen_mir
  18: rustc_codegen_ssa::base::codegen_instance
  19: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  20: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  21: rustc::dep_graph::graph::DepGraph::with_task
  22: rustc_codegen_llvm::base::compile_codegen_unit
  23: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  24: rustc_interface::passes::start_codegen::{{closure}}
  25: rustc_interface::passes::start_codegen
  26: rustc::ty::context::tls::enter_global
  27: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  28: rustc_interface::passes::create_global_ctxt::{{closure}}
  29: rustc_interface::passes::BoxedGlobalCtxt::enter
  30: rustc_interface::queries::Query<T>::compute
  31: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  32: rustc_interface::interface::run_compiler_in_existing_thread_pool
  33: std::thread::local::LocalKey<T>::with
  34: scoped_tls::ScopedKey<T>::set
  35: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (e87a205c2 2019-11-27) running on x86_64-apple-darwin

note: compiler flags: -Z mir-opt-level=2

query stack during panic:
end of query stack
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #66856
Fixes #66851

### CODE REVIEW

File: src/librustc_mir/transform/simplify_try.rs [hunk 1]
```diff
@@ -52,6 +53,7 @@ impl<'tcx> MirPass<'tcx> for SimplifyArmIdentity {
             };
             if local_tmp_s0 != local_tmp_s1
                 || vf_s0 != vf_s1
```
Comment (Centril) [inline src/librustc_mir/transform/simplify_try.rs]:
```suggestion
                // The field-and-variant information match up.
                || vf_s0 != vf_s1
```

File: src/librustc_mir/transform/simplify_try.rs [hunk 2]
```diff
@@ -52,6 +53,7 @@ impl<'tcx> MirPass<'tcx> for SimplifyArmIdentity {
...
+                || local_decls[local_0].ty != local_decls[local_1].ty
```
Comment (Centril) [inline src/librustc_mir/transform/simplify_try.rs]:
```suggestion
                // Source and target locals have the same type.
                // FIXME(Centril | oli-obk): possibly relax to same layout?
                || local_decls[local_0].ty != local_decls[local_1].ty
```

File: src/librustc_mir/transform/simplify_try.rs [hunk 3]
```diff
@@ -52,6 +53,7 @@ impl<'tcx> MirPass<'tcx> for SimplifyArmIdentity {
...
                 || Some((local_0, vf_s0.var_idx)) != match_set_discr(s2)
```
Comment (Centril) [inline src/librustc_mir/transform/simplify_try.rs]:
```suggestion
                // We're setting the discriminant of `local_0` to this variant.
                || Some((local_0, vf_s0.var_idx)) != match_set_discr(s2)
```

File: src/test/ui/issues/issue-66851.rs [hunk 4]
```diff
@@ -0,0 +1,17 @@
+// run-pass
+// compile-flags: -Zmir-opt-level=2
+
```
Comment (Centril) [inline src/test/ui/issues/issue-66851.rs]:
```suggestion

// This used to mis-compile because the mir-opt `SimplifyArmIdentity`
// did not check that the types matched up in the `Ok(r)` branch.

```

File: src/test/ui/issues/issue-66856.rs [hunk 5]
```diff
@@ -0,0 +1,19 @@
+// build-pass
```
Comment (Centril) [inline src/test/ui/issues/issue-66856.rs]: Let's convert this to a mir-opt test instead of a build-pass test to avoid relying on what LLVM does and doesn't do.

Comment (Centril) [reply src/test/ui/issues/issue-66856.rs]: Here's what I had (in `src/test/mir-opt/simplify-arm-identity.rs`):
```rust
enum Src {
    Foo(u8),
    Bar,
}

enum Dst {
    Foo(u8),
}

fn main() {
    let e: Src = Src::Foo(0);
    let _: Dst = match e {
        Src::Foo(x) => Dst::Foo(x),
        Src::Bar => Dst::Foo(0),
    };
}

// END RUST SOURCE
// START rustc.main.SimplifyArmIdentity.before.mir
// fn main() -> () {
//     ...
//     bb0: {
//         StorageLive(_1);
//         ((_1 as Foo).0: u8) = const 0u8;
//         discriminant(_1) = 0;
//         StorageLive(_2);
//         _3 = discriminant(_1);
//         switchInt(move _3) -> [0isize: bb3, 1isize: bb1, otherwise: bb2];
//     }
//     bb1: {
//         ((_2 as Foo).0: u8) = const 0u8;
//         discriminant(_2) = 0;
//         goto -> bb4;
//     }
//     ...
//     bb3: {
//         _4 = ((_1 as Foo).0: u8);
//         ((_2 as Foo).0: u8) = move _4;
//         discriminant(_2) = 0;
//         goto -> bb4;
//     }
//     ...
// }
// END rustc.main.SimplifyArmIdentity.before.mir
// START rustc.main.SimplifyArmIdentity.after.mir
// fn main() -> () {
//     ...
//     bb0: {
//         StorageLive(_1);
//         ((_1 as Foo).0: u8) = const 0u8;
//         discriminant(_1) = 0;
//         StorageLive(_2);
//         _3 = discriminant(_1);
//         switchInt(move _3) -> [0isize: bb3, 1isize: bb1, otherwise: bb2];
//     }
//     bb1: {
//         ((_2 as Foo).0: u8) = const 0u8;
//         discriminant(_2) = 0;
//         goto -> bb4;
//     }
//     ...
//     bb3: {
//         _4 = ((_1 as Foo).0: u8);
//         ((_2 as Foo).0: u8) = move _4;
//         discriminant(_2) = 0;
//         goto -> bb4;
//     }
//     ...
// }
// END rustc.main.SimplifyArmIdentity.after.mir
```

**Review by Centril — COMMENTED** [review]
Looks like you beat me to it... ;)
I had some additional stuff that would be good to add.
