### PR TITLE
[rustdoc] Do not emit redundant_explicit_links lint if the doc comment comes from expansion

### LINKED ISSUE #141553: redundant_explicit_links rustdoc lint should have macro guard
On ICU4X main, with nightly, `cargo doc --all-features` in `provider/core`

```rust
error: redundant explicit link target
   --> provider/core/src/constructors.rs:106:47
    |
106 |               "provided by a [`BufferProvider`](icu_provider::buf::BufferProvider).\n\n",
    |                               ----------------  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ explicit target is redundant
    |                               |
    |                               because label contains path that resolves to same destination
    |
   ::: provider/core/src/hello_world.rs:302:5
    |
302 | /     icu_provider::gen_buffer_data_constructors!((prefs: HelloWorldFormatterPreferences) -> error: DataError,
303 | |         functions: [
304 | |             try_new: skip,
305 | |             try_new_with_buffer_provider,
306 | |             try_new_unstable,
307 | |             Self,
308 | |     ]);
    | |______- in this macro invocation
    |
    = note: when a link's destination is not specified,
            the label is used to resolve intra-doc links
    = note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(rustdoc::redundant_explicit_links)]`
    = note: this error originates in the macro `$crate::gen_buffer_data_constructors` which comes from the expansion of the macro `icu_provider::gen_buffer_data_constructors` (in Nightly builds, run with -Z macro-backtrace for more info)

```

These docs are macro-generated, which means even if that import is around in _some_ contexts, it isn't around in all of them, and we can't fix that in the macro.

https://github.com/unicode-org/icu4x/blob/f47044e3de1ba0c47a43b95968bd503902328188/provider/core/src/constructors.rs#L107

Given that they are macro generated _docs_, it is not possible to stick an `allow()` statement in the macro to silence the lint (without enabling attributes-on-expressions). So this code is permabroken.

This lint should probably get a macro guard, or even be reverted until this can be figured out: the lint is mostly a cleanup lint and should not cause such problems.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/141553.

The problem was that we change the context for the attributes in some cases to get better error output, preventing us to detect if the attribute comes from expansion. Most of the changes are about keeping track of the "does this span comes from expansion" information.

r? @Manishearth

### CODE REVIEW

**Review by lolbinarycat — COMMENTED** [review]
Mostly nits about comments, but a few concerns about the actual logic as well.

**Comment by Manishearth** [comment]
(I've been rather busy catching up with stuff after vacation; I probably won't be able to review this myself soon ,sorry!)

**Comment by GuillaumeGomez** [comment]
No worries, take your time. We can pick another reviewer in the meantime.

r? notriddle

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 1]
```diff
@@ -497,16 +501,21 @@ fn collect_link_data<'input, F: BrokenLinkCallback<'input>>(
...
-    let start = fragments[0].span;
-    if start == DUMMY_SP {
+pub fn span_of_fragments_with_expansion(fragments: &[DocFragment]) -> Option<(Span, bool)> {
+    let Some(first_fragment) = fragments.first() else { return None };
+    if first_fragment.span == DUMMY_SP {
         return None;
     }
-    let end = fragments.last().expect("no doc strings provided").span;
-    Some(start.to(end))
+    let last_fragment = fragments.last().expect("no doc strings provided");
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs]: Actually we can even improve the code further, going to do that.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 2]
```diff
@@ -497,16 +501,21 @@ fn collect_link_data<'input, F: BrokenLinkCallback<'input>>(
...
+    Some((
+        first_fragment.span.to(last_fragment.span),
+        first_fragment.from_expansion || last_fragment.from_expansion,
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs]: Good point.

File: tests/rustdoc-ui/lints/redundant_explicit_links-expansion.rs [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+        pub struct BufferProvider;
+    }
+}
+
+// Should not lint.
+#[doc = mac1!()]
+pub struct Foo;
+
+// Should not lint.
+mac2!{}
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply tests/rustdoc-ui/lints/redundant_explicit_links-expansion.rs:30]: Added one.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 4]
```diff
@@ -531,7 +540,7 @@ pub fn source_span_for_markdown_range(
     markdown: &str,
     md_range: &Range<usize>,
     fragments: &[DocFragment],
-) -> Option<Span> {
+) -> Option<(Span, bool)> {
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs:560]: Done.

**Comment by GuillaumeGomez** [comment]
Applied suggestions and added more tests.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 5]
```diff
@@ -208,17 +211,18 @@ pub fn attrs_to_doc_fragments<'a, A: AttributeExt + Clone + 'a>(
     for (attr, item_id) in attrs {
         if let Some((doc_str, comment_kind)) = attr.doc_str_and_comment_kind() {
             let doc = beautify_doc_string(doc_str, comment_kind);
-            let (span, kind) = if attr.is_doc_comment() {
-                (attr.span(), DocFragmentKind::SugaredDoc)
+            let (span, kind, from_expansion) = if attr.is_doc_comment() {
+                let span = attr.span();
+                (span, DocFragmentKind::SugaredDoc, span.from_expansion())
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs:216]: This is actually a bit odd to me, `doc_str_and_comment_kind` knows if a doc fragment is raw or a comment, but it then we throw that info away only to recalculate it immediately.  These functions *probably* get inlined and *probably* llvm de-duplicates the match, but it's still a bit messy, especially considering this is the only call site of `doc_str_and_comment_kind` besides 1 place in clippy that only checks if the return value is None.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 6]
```diff
@@ -500,17 +504,26 @@ fn collect_link_data<'input, F: BrokenLinkCallback<'input>>(
...
 
-/// Returns a span encompassing all the document fragments.
-pub fn span_of_fragments(fragments: &[DocFragment]) -> Option<Span> {
-    if fragments.is_empty() {
-        return None;
-    }
-    let start = fragments[0].span;
-    if start == DUMMY_SP {
+/// Returns a tuple containing a span encompassing all the document fragments and a boolean that is
+/// `true` if the fragments are from a macro expansion.
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]:
```suggestion
/// `true` if any of the fragments are from a macro expansion.
```

Nit: more precise language

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 7]
```diff
@@ -524,18 +537,22 @@ pub fn span_of_fragments(fragments: &[DocFragment]) -> Option<Span> {
...
-/// - The doc includes exactly one substring matching `markdown[md_range]` which is contained in a single doc fragment.
+/// - The doc includes exactly one substring matching `markdown[md_range]` which is contained in a
+///   single doc fragment.
+///
+/// This function is defined in the compiler so it can be used by both `rustdoc` and `clippy`.
 ///
-/// This function is defined in the compiler so it can be used by
-/// both `rustdoc` and `clippy`.
+/// It returns a tuple containing a span encompassing all the document fragments and a boolean that
+/// is `true` if the fragments are from a macro expansion.
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]:
```suggestion
/// is `true` if any of the *matched* fragments are from a macro expansion.
```

same nit, but also clarify that only matching fragments are counted here.  it's a bit fuzzy because the details depend on the heuristic used.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 8]
```diff
@@ -500,17 +504,26 @@ fn collect_link_data<'input, F: BrokenLinkCallback<'input>>(
...
+        [first] => (first, first),
+    };
+    if first_fragment.span == DUMMY_SP {
         return None;
     }
-    let end = fragments.last().expect("no doc strings provided").span;
-    Some(start.to(end))
+    Some((
+        first_fragment.span.to(last_fragment.span),
+        fragments.iter().any(|frag| frag.from_expansion),
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs:525]: This probably produces false negatives if all of the following are true:
1. there is a macro that produces sugared doc comments
2. there is a non-macro generated sugared doc comment containing a redundant explicit link
3. there are no raw doc fragments on the item

This may be an acceptable regression, but I thought it was worth noting.

This could perhaps be made even more unlikely by trying to use the unambiguous substring heuristic first, or it could be eliminated completely by first calculating the final source span, then only checking the `from_expansion` of fragments that overlap with that source span.

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 9]
```diff
@@ -659,8 +681,12 @@ pub fn source_span_for_markdown_range_inner(
...
-        md_range.start + start_bytes,
-        md_range.end + start_bytes + end_bytes,
-    )))
+    let (span, from_expansion) = span_of_fragments_with_expansion(fragments)?;
+    Some((
+        span.from_inner(InnerSpan::new(
+            md_range.start + start_bytes,
+            md_range.end + start_bytes + end_bytes,
+        )),
+        from_expansion,
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs]: If we wanted to avoid the false negative I pointed out before, something like this could work:
```suggestion
    let src_span = span.from_inner(InnerSpan::new(
        md_range.start + start_bytes,
        md_range.end + start_bytes + end_bytes,
    ));
    Some(( 
        src_span,
        fragments.iter().any(|frag| frag.span.overlaps(src_span) && frag.from_expansion),
```

File: src/librustdoc/passes/lint/redundant_explicit_links.rs [hunk 10]
```diff
@@ -161,20 +161,34 @@ fn check_inline_or_reference_unknown_redundancy(
...
-                .unwrap_or(item.attr_span(cx.tcx));
-        let explicit_span = source_span_for_markdown_range(
+            match source_span_for_markdown_range(cx.tcx, doc, &link_range, &item.attrs.doc_strings)
+            {
+                Some((sp, from_expansion)) => {
+                    if from_expansion {
+                        return None;
+                    }
+                    sp
+                }
```
Comment (lolbinarycat) [inline src/librustdoc/passes/lint/redundant_explicit_links.rs:171]: I think lifting the `if` into the match makes this a bit neater, at the cost of losing the variable name:

```suggestion
                Some((_, true)) => return None, // from macro expansion, ignore
                Some((sp, false)) => sp,
```

File: src/librustdoc/passes/lint/redundant_explicit_links.rs [hunk 11]
```diff
@@ -206,21 +220,35 @@ fn check_reference_redundancy(
...
+                None => item.attr_span(cx.tcx),
```
Comment (lolbinarycat) [inline src/librustdoc/passes/lint/redundant_explicit_links.rs:233]: Same thing as before, I think this is more readable but maybe that's just because I'm used to haskell code that uses a lot of pattern matching.

```suggestion
                Some((_, true)) => return None, // from macro expansion, ignore
                Some((sp, false)) => sp,
                None => item.attr_span(cx.tcx),
```

File: src/librustdoc/passes/lint/redundant_explicit_links.rs [hunk 12]
```diff
@@ -161,20 +161,34 @@ fn check_inline_or_reference_unknown_redundancy(
...
+        }
+        let (display_span, from_expansion) = source_span_for_markdown_range(
             cx.tcx,
             doc,
             resolvable_link_range,
             &item.attrs.doc_strings,
         )?;
+        if from_expansion {
+            return None;
+        }
```
Comment (lolbinarycat) [inline src/librustdoc/passes/lint/redundant_explicit_links.rs]: Comment: Technically this type of control flow could be expressed more tersely as `let (foo, false) ... else { return None };` but that might not be the most readable thing.

File: tests/rustdoc-ui/lints/redundant_explicit_links-expansion.rs [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+
+#[doc = "provided by a [`BufferProvider`](crate::BufferProvider)."]
+//~^ ERROR: redundant_explicit_links
+pub struct Bla;
+
+#[doc = mac3!()]
+/// a [`BufferProvider`](crate::BufferProvider).
+//~^ ERROR: redundant_explicit_links
+pub fn f() {}
```
Comment (lolbinarycat) [inline tests/rustdoc-ui/lints/redundant_explicit_links-expansion.rs:40]: I kinda would like to see some tests exercising the all-sugared doc fragment case, where half of the fragments are macro-generated and half aren't.  Ideally there would be two cases for this, one where the redundant link is in the macro generated fragment and thus the lint is suppressed, and one where the redundant link is in the non-macro generated fragment and thus the link is emitted.

**Review by lolbinarycat — COMMENTED** [review]
There's 1 edge case I think this doesn't handle 100% correctly, and other than that I just have a few nits about wording, 1 tiny inefficiency,  and some comments about how some control flow could be rewritten to use pattern matching (if we wanted that)

File: compiler/rustc_resolve/src/rustdoc.rs (hunk 8 above)
Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs:525]: I suggest opening an issue once this PR is merged and send a PR with a regression test case. :)

Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs:525]: Ah you propose a solution below, copying it then.

File: src/librustdoc/passes/lint/redundant_explicit_links.rs (hunk 10 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/lint/redundant_explicit_links.rs:171]: I'm a bit shared here: your code relies more on the type system, but is also less readable and needs a comment, and the comment needs to understand that the second element of the tuple is the one we're talking about (not big issue, but still a small cognitive indirection). Although your code is better, I'll keep the current one for readability reasons.

File: src/librustdoc/passes/lint/redundant_explicit_links.rs (hunk 11 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/lint/redundant_explicit_links.rs:233]: Same reasoning as before. :)

File: src/librustdoc/passes/lint/redundant_explicit_links.rs (hunk 12 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/lint/redundant_explicit_links.rs]: In this case I think the `let else` is acceptable since we already know what the first element of the tuple is. I'm gonna implement this one then!

**Comment by notriddle** [comment]
I understand that this bail-out is needed because, in the event of a false positive, disabling the lint in the macro is impossible. There's nowhere to attach the attribute.

In that case, would it be simpler and make more sense to disable *all of the markdown lints*, and not just this one?

File: compiler/rustc_resolve/src/rustdoc.rs [hunk 14]
```diff
@@ -659,8 +681,13 @@ pub fn source_span_for_markdown_range_inner(
         }
     }
 
-    Some(span_of_fragments(fragments)?.from_inner(InnerSpan::new(
+    let (span, _) = span_of_fragments_with_expansion(fragments)?;
```
Comment (lolbinarycat) [inline compiler/rustc_resolve/src/rustdoc.rs:689]: We can revert `span_of_fragments_with_expansion` to just be `span_of_fragments` again now, right?

any future potential users of it would probably be suspect to the same edge case as is present here, and having a useless iteration isn't ideal.

File: src/librustdoc/passes/lint/redundant_explicit_links.rs [hunk 15]
```diff
@@ -161,20 +161,35 @@ fn check_inline_or_reference_unknown_redundancy(
...
+            {
+                Some((sp, from_expansion)) => {
+                    if from_expansion {
+                        return None;
+                    }
+                    sp
+                }
+                None => item.attr_span(cx.tcx),
+            };
+        let (explicit_span, from_expansion) = source_span_for_markdown_range(
```
Comment (lolbinarycat) [inline src/librustdoc/passes/lint/redundant_explicit_links.rs]: this could also be let else

File: src/librustdoc/passes/lint/redundant_explicit_links.rs [hunk 16]
```diff
@@ -206,21 +221,35 @@ fn check_reference_redundancy(
...
             cx.tcx,
             doc,
             &offset_explicit_range(doc, link_range.clone(), b'[', b']'),
             &item.attrs.doc_strings,
         )?;
-        let display_span = source_span_for_markdown_range(
+        if from_expansion {
+            return None;
+        }
+        let (display_span, from_expansion) = source_span_for_markdown_range(
```
Comment (lolbinarycat) [inline src/librustdoc/passes/lint/redundant_explicit_links.rs]: this could also also be let else

**Review by lolbinarycat — COMMENTED** [review]
1. we can revert `span_for_fragments`
2. more places could use if/else

File: compiler/rustc_resolve/src/rustdoc.rs (hunk 14 above)
Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs:689]: It would make a lot of unrelated changes, like in `clippy`. A follow-up is likely better to prevent blocking this fix.

**Comment by GuillaumeGomez** [comment]
Applied suggestions.

File: compiler/rustc_resolve/src/rustdoc.rs (hunk 14 above)
Comment (lolbinarycat) [reply compiler/rustc_resolve/src/rustdoc.rs:689]: I mean, I would agree with that reasoning, although it does make me wonder somewhat what your criteria for when a working but not ideal solution should be merged, given your review on https://github.com/rust-lang/rust/pull/142653

Comment (GuillaumeGomez) [reply compiler/rustc_resolve/src/rustdoc.rs:689]: Current PR is a bugfix. #142653 is a behaviour change introducing potentially a performance regression.

**Review by lolbinarycat — APPROVED** [review]
Should probably get a followup PR to clean up some oddities, but is definitely an improvement over the status quo.

**Comment by GuillaumeGomez** [comment]
Thanks for the review! Let's approve so this bug can finally be removed. :)

@bors r=lolbinarycat rollup
