### PR TITLE
Issue 21033 struct var pattern fix

### LINKED ISSUE #21033: Inconsistent pattern matching on struct variants
```rust
enum StructVar {
    BoxedInt { boxed: Box<i32> },
    UnboxedInt { unboxed: i32 }
}

fn main() {

    let x = StructVar::BoxedInt { boxed: box 3 };

    match x {
        //StructVar::BoxedInt { box boxed } => { } // expected identifier, found keyword 'box'
        StructVar::BoxedInt { boxed: box boxed } => { } // ok
        StructVar::UnboxedInt { unboxed } => { } 
    }

    match x { 
        StructVar::BoxedInt { ref boxed } => { } // works with ref
        StructVar::UnboxedInt { ref unboxed } => { }
    }

}
```

I'm not sure if this is actually an issue or if it's known behavior but it seems inconsistent to be able to match against `ref` and not `box`, especially since the same works with regular enums.

### PR DESCRIPTION
**Pull request by thchittenden**
Closes #21033. The new strategy for parsing a field pattern is to look 1 token ahead and if it's a colon, parse as "fieldname: pat", otherwise parse the shorthand form "(box) (ref) (mut) fieldname)". The previous strategy was to parse "(ref) (mut) fieldname" then if we encounter a colon, throw an error if either "ref" or "mut" were encountered.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add a few more tests for mixing `box`, `ref`, and `mut` to make sure everything checks out ok? Also, could you squash the commits into one? Otherwise this looks great to me!

**Comment by thchittenden** [comment]
Ok, done. I'm not sure if you want the tests in separate files or not but if you do I can separate them.

**Comment by thchittenden** [comment]
`ref mut box` doesn't work for pattern matching in regular enums so I tried to keep it consistent. `box mut` does, though I'm not sure what the actual use case woul be.

File: src/test/run-pass/issue-21033.rs [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    }
+    match a {
+        E::StructVar { box ref mut boxed } => { }
+    }
+    match a {
+        E::StructVar { ref boxed } => { }
+    }
+    match a {
+        E::StructVar { mut boxed } => { }
+    }
```
Comment (alexcrichton) [inline src/test/run-pass/issue-21033.rs]: Does this test compile? Isn't `a` moved into one of the branches above?

**Comment by alexcrichton** [comment]
Ah and all one test is fine by me, just wondering about whether the test compiles today

**Comment by thchittenden** [comment]
Bah, not sure how I missed that. Should be fixed now.
