### PR TITLE
Fix ICE on using result of index on a constant to index into a constant

### LINKED ISSUE #29914: ICE on using result of index operation on a constant to index into a constant
```rust
const ARR: [usize; 5] = [5, 4, 3, 2, 1];

fn main() {
    println!("{}", ARR[ARR[3]]);
}
```

causes

```
<anon>:5:24: 5:30 error: internal compiler error: index is not an integer-constant expression
<anon>:5     println!("{}", ARR[ARR[3]]);
                                ^~~~~~
```

### PR DESCRIPTION
**Pull request by wesleywiser**
The issue was that the const evaluator was returning an error because
the feature flag const_indexing wasn't turned on. The error was then
reported as a bug.

Fixes #29914

### CODE REVIEW

**Comment by wesleywiser** [comment]
First time fixing an ICE so any feedback is greatly appreciated :)

**Comment by wesleywiser** [comment]
I'll squash those up later

**Comment by nagisa** [comment]
cc @oli-obk @eddyb

**Comment by oli-obk** [comment]
Good idea. It would probably be a good idea to report all other errors, too. It should only be a bug when it returns a non int ok value.

File: src/test/run-pass/issue-29914.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+const ARR: [usize; 5] = [5, 4, 3, 2, 1];
+
+fn main() {
+    assert_eq!(2, ARR[ARR[3]]);
```
Comment (oli-obk) [inline src/test/run-pass/issue-29914.rs]: Doesn't this require the feature gate to be turned on?

Comment (wesleywiser) [inline src/test/run-pass/issue-29914.rs]: Done

**Comment by wesleywiser** [comment]
@oli-obk Done

**Comment by wesleywiser** [comment]
```
failures:

---- [run-pass] run-pass/issue-29914.rs stdout ----
	
error: test run failed!
status: signal: 11
command: x86_64-apple-darwin/test/run-pass/issue-29914.stage2-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/issue-29914.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/compiletest/runtest.rs:1505


failures:
    [run-pass] run-pass/issue-29914.rs

test result: FAILED. 2335 passed; 1 failed; 3 ignored; 0 measured
```

**Comment by wesleywiser** [comment]
I just retested this on OS X 10.11 and the test passes. Not sure what's going on

**Comment by wesleywiser** [comment]
So I tried merging again and retesting and it works on my machine:

```
run rpass [x86_64-apple-darwin]: x86_64-apple-darwin/stage2/bin/compiletest

running 2 tests
test [run-pass] run-pass/issue-29914.rs ... ok
test [run-pass] run-pass/issue-29914-2.rs ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured
```

@arielb1 maybe @bors just needs to be retried?

**Comment by eddyb** [comment]
@wesleywiser Signal 11 is SIGSEGV AFAIK, which is worrisome.

**Comment by wesleywiser** [comment]
@eddyb Agreed I'm just not sure where to go from here. I can't even repro the issue on my computer.

**Comment by nagisa** [comment]
AFAIR I also has SIGSEGV on buildbots once (a few months ago; also on OSX IIRC), which turned out to be “temporary” and not “reproducible” even on buildbots when retesting again.

**Comment by alexcrichton** [comment]
@bors: retry

Looks like this was likely spurious

**Comment by oli-obk** [comment]
Not a sporadic failure. Somehow this causes UB.

**Comment by oli-obk** [comment]
Ah since the error is never reported, this actually compiles successfully. You'd need to report an error, not just return it. The reason it's this weird is that multiple errors should be reported, and not just the first one. I could probably refactor it to ensure that something like this doesn't happen.

The test without the feature gate should be a compile fail test

**Comment by wesleywiser** [comment]
@oli-obk I thought if const-eval failed, it just generated code and evaluated at runtime as normal. Is that incorrect?

**Comment by oli-obk** [comment]
But you returned a compile time error. Also thats only true if it's not in a constant.nso you need to check trueconst

**Comment by oli-obk** [comment]
The clean solution is probably to stop using `eval_const_expr_partial` and extract the value from the llvm constant.

```diff
-            let iv = match eval_const_expr_partial(cx.tcx(), &index, ExprTypeChecked, None) {
-                Ok(ConstVal::Int(i)) => i as u64,
-                Ok(ConstVal::Uint(u)) => u,
-                _ => cx.sess().span_bug(index.span,
-                                        "index is not an integer-constant expression")
+            let iv = try!(const_expr(cx, &**index, param_substs, fn_args, trueconst)).0;
+            let iv = if let Some(iv) = const_to_opt_uint(iv) {
+                iv
+            } else {
+                cx.sess().span_bug(index.span, "index is not an integer-constant expression");
```

**Comment by wesleywiser** [comment]
@oli-obk Hmmm... so if I try that, it works but doesn't respect the feature gate. What do you think of the latest commit I pushed?

**Comment by oli-obk** [comment]
Not sure what you mean with not respecting the feature gate.

**Comment by wesleywiser** [comment]
I added a `compile-fail` test [here](https://github.com/wesleywiser/rust/blob/38de158bd36c5162dd0b209816c7d92b8dcc8bb9/src/test/compile-fail/issue-29914.rs) which is the same as the `run-pass` one but it doesn't have the `const_indexing` feature. I tried making the change you suggested but that test fails because the compiler doesn't produce an error. With `38de158`, both tests pass. That's the correct behavior right?

**Comment by oli-obk** [comment]
Right. The test should be run-fail because the indexing happens at runtime

**Comment by wesleywiser** [comment]
Oh, does the compile time error only come into play when doing something like 
`const BLA: usize = ARR[ARR[3]];` without `const_indexing`?

**Comment by oli-obk** [comment]
Jup

**Comment by wesleywiser** [comment]
Got it. Thanks!

**Comment by ia0** [comment]
It seems this PR also fixes #23513 and a similar ICE with const fn I got today:
```
#![feature(const_fn)]

const fn get(x: &[u8], i: usize) -> u8 {
    x[i]
}

fn main() {
    let _ = get(&[0], 0);
}
```
The`error: internal compiler error: index is not an integer-constant expression` is changed into `error: non-constant path in constant expression`.

File: src/librustc_trans/trans/consts.rs [hunk 2]
```diff
@@ -664,12 +662,19 @@ fn const_expr_unadjusted<'a, 'tcx>(cx: &CrateContext<'a, 'tcx>,
             adt::const_get_field(cx, &*brepr, bv, vinfo.discr, idx.node)
         },
         hir::ExprIndex(ref base, ref index) => {
+            //honor the const_indexing feature if this is in a CONST expression
+            if !cx.sess().features.borrow().const_indexing && trueconst == TrueConst::Yes {
```
Comment (wesleywiser) [inline src/librustc_trans/trans/consts.rs]: I had to add this check in order to get the `compile-fail` test I added to pass. Maybe this is the wrong place to add the check though?

File: src/librustc_trans/trans/consts.rs [hunk 3]
```diff
@@ -1032,7 +1037,7 @@ pub fn trans_static(ccx: &CrateContext,
             expr,
             empty_substs,
             None,
-            TrueConst::Yes,
+            TrueConst::No,
```
Comment (wesleywiser) [inline src/librustc_trans/trans/consts.rs]: I had to change this because otherwise, statics like this were causing compiler errors:
```
const A: [i32; 1] = [0];
static B: i32 = A[0];
```

File: src/test/compile-fail/array_const_index-1.rs [hunk 4]
```diff
@@ -7,6 +7,7 @@
 // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
+#![feature(const_indexing)]
```
Comment (wesleywiser) [inline src/test/compile-fail/array_const_index-1.rs]: These two tests started failing because the `const_indexing` error was being reported instead of the index out of bounds error.

**Comment by wesleywiser** [comment]
@oli-obk When you get a minute, could you look at my changes? Thanks!

File: src/librustc_trans/trans/consts.rs (hunk 3 above)
Comment (oli-obk) [inline src/librustc_trans/trans/consts.rs]: This definitely needs to stay at `TrueConst::Yes`.

File: src/librustc_trans/trans/consts.rs (hunk 2 above)
Comment (oli-obk) [inline src/librustc_trans/trans/consts.rs]: Const indexing is allowed in statics, just not in true constants. So this check is wrong here.

**Comment by oli-obk** [comment]
With the change from `eval_const_expr_partial` to running purely in trans/consts, the compile-fail test is actually a run-pass test. This is not a breaking change, since previously failing code now works, and all previously working code will still work, because `trans/consts` can eval more things than `eval_const_expr_partial`, and there's nothing that `eval_const_expr_partial` can eval while `trans/consts` cannot.

File: src/librustc_trans/trans/consts.rs [hunk 5]
```diff
@@ -664,12 +662,19 @@ fn const_expr_unadjusted<'a, 'tcx>(cx: &CrateContext<'a, 'tcx>,
...
+                return Err(ConstEvalFailure::Compiletime(e));
+            }
+
             let (bv, bt) = try!(const_expr(cx, &**base, param_substs, fn_args, trueconst));
-            let iv = match eval_const_expr_partial(cx.tcx(), &index, ExprTypeChecked, None) {
-                Ok(ConstVal::Int(i)) => i as u64,
-                Ok(ConstVal::Uint(u)) => u,
-                _ => cx.sess().span_bug(index.span,
-                                        "index is not an integer-constant expression")
+            let iv = try!(const_expr(cx, &**index, param_substs, fn_args, trueconst)).0;
```
Comment (oli-obk) [inline src/librustc_trans/trans/consts.rs]: `trueconst` should probably be `TrueConst::Yes` (definitely change this just to be on the safe side).

**Comment by wesleywiser** [comment]
> the compile-fail test is actually a run-pass test

I think I'm missing something then. Isn't it supposed to fail because it's performing a constant index operation without using `#![feature(const_indexing)]`?

**Comment by oli-obk** [comment]
not quite: the `const_indexing` feature exists solely to prevent constant indexing in array length calculations. Indexing was allowed in statics since 1.0.

**Comment by wesleywiser** [comment]
Ah ok. That makes perfect sense now. Thanks! I'll fix this up tonight

**Comment by wesleywiser** [comment]
@oli-obk Fixed

File: src/librustc_trans/trans/consts.rs [hunk 6]
```diff
@@ -664,12 +662,12 @@ fn const_expr_unadjusted<'a, 'tcx>(cx: &CrateContext<'a, 'tcx>,
...
         },
         hir::ExprIndex(ref base, ref index) => {
-            let (bv, bt) = try!(const_expr(cx, &**base, param_substs, fn_args, trueconst));
-            let iv = match eval_const_expr_partial(cx.tcx(), &index, ExprTypeChecked, None) {
-                Ok(ConstVal::Int(i)) => i as u64,
-                Ok(ConstVal::Uint(u)) => u,
-                _ => cx.sess().span_bug(index.span,
-                                        "index is not an integer-constant expression")
+            let (bv, bt) = try!(const_expr(cx, &**base, param_substs, fn_args, TrueConst::Yes));
+            let iv = try!(const_expr(cx, &**index, param_substs, fn_args, trueconst)).0;
```
Comment (oli-obk) [inline src/librustc_trans/trans/consts.rs]: the `TrueConst::Yes` should be on the index, not the array

Comment (wesleywiser) [inline src/librustc_trans/trans/consts.rs]: Fixed, thanks

**Comment by oli-obk** [comment]
lgtm

**Comment by wesleywiser** [comment]
Rebased

**Comment by wesleywiser** [comment]
@arielb1 I think this is ready to go
