### PR TITLE
std::alloc: use posix_memalign instead of memalign on solarish

### LINKED ISSUE #124787: Solarish: standard allocator uses `memalign` incorrectly
The [docs](https://docs.oracle.com/cd/E88353_01/html/E37843/memalign-3c.html) for that function state

> The memalign() function allocates size bytes on a specified alignment boundary and returns a pointer to the allocated block. The value of the returned address is guaranteed to be an even multiple of alignment. The value of alignment must be a power of two and **must be greater than or equal to the size of a word**.

(emphasis mine)

However, the way this function gets called [here](https://github.com/rust-lang/rust/blob/99128b7e45f8b95d962da2e6ea584767f0c85455/library/std/src/sys/pal/unix/alloc.rs#L84) does not ensure that the alignment is at least the size of a word.

Cc @devnexen (discovered by failing CI in https://github.com/rust-lang/miri/pull/3575)

### PR DESCRIPTION
**Pull request by devnexen**
`memalign` on Solarish requires the alignment to be at least the size of a pointer, which we did not honor. `posix_memalign` also requires that, but that code path already takes care of this requirement.

close GH-124787

### CODE REVIEW

File: library/std/src/sys/pal/unix/alloc.rs [hunk 1]
```diff
@@ -87,7 +87,11 @@ cfg_if::cfg_if! {
             // [3]: https://bugs.chromium.org/p/chromium/issues/detail?id=138579
             // [4]: https://chromium.googlesource.com/chromium/src/base/+/master/
             //                                       /memory/aligned_memory.cc
-            libc::memalign(layout.align(), layout.size()) as *mut u8
+            //
+            // We purpose use the higher alignment so we have it at least
+            // a proper word size value guaranteed.
+            let align = layout.align().max(create::mem::size_of::<usize>());
```
Comment (klensy) [inline library/std/src/sys/pal/unix/alloc.rs:93]:
```suggestion
            let align = layout.align().max(crate::mem::size_of::<usize>());
```

**Comment by RalfJung** [comment]
Can't we just use `posix_memalign`? [Solaris](https://docs.oracle.com/cd/E88353_01/html/E37843/posix-memalign-3c.html) and [Illumos](https://illumos.org/man/3C/posix_memalign) seem to both have that. Then the diff would be just two lines, as we're already using posix_memalign by default when we don't have some other special case.

**Comment by devnexen** [comment]
If we do not care of solaris < 10 then it s possible indeed.

**Comment by RalfJung** [comment]
https://doc.rust-lang.org/rustc/platform-support.html explicitly says "Solaris 11" so I think indeed we do not care about Solaris 10.

**Comment by RalfJung** [comment]
LGTM, thanks!
@bors r+
