### PR TITLE
print-type-sizes: skip field printing for primitives

### LINKED ISSUE #86528: -Z print-type-sizes: internal error: entered unreachable code: FieldsShape::offset: `Primitive`s have no fields'
### Code

https://github.com/rust-lang/docs.rs/commit/69b1f3d5cdedf0e2feba2d87c64c16a670cdd57a

MCVE:
```rust
pub fn test() {
    Vec::<()>::new()
        .into_iter()
        .filter(|_| true)
        .collect::<Vec<_>>();
}
```

### Meta

`rustc --version`: `rustc 1.54.0-nightly (cc77ba46f 2021-06-03)`

### Error output

```
thread 'rustc' panicked at 'internal error: entered unreachable code: FieldsShape::offset: `Primitive`s have no fields', compiler\rustc_target\src\abi\mod.rs:768:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (cc77ba46f 2021-06-03) running on x86_64-pc-windows-msvc

note: compiler flags: -Z print-type-sizes -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #86528.

### CODE REVIEW

File: compiler/rustc_middle/src/ty/layout.rs [hunk 1]
```diff
@@ -1805,8 +1805,11 @@ impl<'tcx> LayoutCx<'tcx, TyCtxt<'tcx>> {
 
         match layout.variants {
             Variants::Single { index } => {
-                debug!("print-type-size `{:#?}` variant {}", layout, adt_def.variants[index].ident);
-                if !adt_def.variants.is_empty() {
+                if !adt_def.variants.is_empty() && layout.fields != FieldsShape::Primitive {
```
Comment (jyn514) [inline compiler/rustc_middle/src/ty/layout.rs:1808]: Why is variants non-empty here? Primitives aren't enums.

Comment (tmiasko) [reply compiler/rustc_middle/src/ty/layout.rs:1808]: FieldsShape describes how fields are located in memory, with Primitive used for things that have no fields, including the never type.

Variants that are uninhabited and have ZST fields only are consider to be absent. Layout computation omits absents variants entirely. If all variants of an enum are absent, the layout of a never type is used (Variants::Single, FieldsShape::Primitive).
