### PR TITLE
(re-)tighten sourceinfo span of adjustments in MIR

### LINKED ISSUE #111016: Incorrect help note for `E0507 cannot move out of ... which is behind a shared reference` with try operator
### Code
```Rust
#[derive(Clone)]
struct Cloneable;
fn f() -> Result<(), Cloneable> {
    let thing = &(Ok::<(), Cloneable>(()),);
    thing.0?;
    Ok(())
}
```
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021)

### Current output

```Shell
error[E0507]: cannot move out of `thing.0` which is behind a shared reference
 --> src/lib.rs:5:5
  |
5 |     thing.0?;
  |     ^^^^^^^-
  |     |
  |     `thing.0` moved due to this method call
  |     move occurs because `thing.0` has type `Result<(), Cloneable>`, which does not implement the `Copy` trait
  |
note: `branch` takes ownership of the receiver `self`, which moves `thing.0`
 --> /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/try_trait.rs:218:15
help: you can `clone` the value and consume it, but this might not be your desired behavior
  |
5 |     clone().thing.0?;
  |     ++++++++

For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground` due to previous error
```

### Desired output

```Shell
error[E0507]: cannot move out of `thing.0` which is behind a shared reference
 --> src/lib.rs:5:5
  |
5 |     thing.0?;
  |     ^^^^^^^-
  |     |
  |     `thing.0` moved due to this method call
  |     move occurs because `thing.0` has type `Result<(), Cloneable>`, which does not implement the `Copy` trait
  |
note: `branch` takes ownership of the receiver `self`, which moves `thing.0`
 --> /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/try_trait.rs:218:15
help: you can `clone` the value and consume it, but this might not be your desired behavior
  |
5 |     thing.0.clone()?;
  |            ++++++++

For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground` due to previous error
```

### Rationale and extra context

The `.clone()` call is being prepended to the expression instead of appended

### Other cases

_No response_

### Anything else?

_No response_

### LINKED ISSUE #113547: Invalid suggestion from E0507 with & and ?
### Code

```Rust
struct A {
    member: Option<String>,
}

fn main() {
    let a = A{ member: None};

    function(&a);
}

fn function(a: &A) -> Option<()> {
    let member = &a.member?;
    None
}
```

### Current output

```Shell
error[E0507]: cannot move out of `a.member` which is behind a shared reference
  --> src/main.rs:12:19
   |
12 |     let member = &a.member?;
   |                   ^^^^^^^^-
   |                   |
   |                   `a.member` moved due to this method call
   |                   move occurs because `a.member` has type `Option<String>`, which does not implement the `Copy` trait
   |
note: `branch` takes ownership of the receiver `self`, which moves `a.member`
  --> /rustc/1065d876cdbc34a872b9e17c78caaa59ea0c94d4/library/core/src/ops/try_trait.rs:217:15
help: you can `clone` the value and consume it, but this might not be your desired behavior
   |
12 |     let member = &clone().a.member?;
   |                   ++++++++

For more information about this error, try `rustc --explain E0507`.
```

### Desired output

```Shell
12 |     let member = &a.member.clone()?;

or

12 |     let member = a.member.as_ref()?;
```

### Rationale and extra context

The suggestion for cloning the member that cannot be moved puts the `clone()` in the wrong place, but only (in this example) when combined with the question mark operator. Without the question mark `&a.member` compiles with no errors.

Playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0a72b96edb6cf4f2fcab3e2cbf4c877e

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compiler-errors**
Diagnostics rely on the spans of MIR statements being (approximately) correct in order to give suggestions relative to that span (i.e. `shrink_to_hi` and `shrink_to_lo`).

I discovered that we're *intentionally* lowering THIR exprs with their parent expr's span if they come from adjustments that are due to a parent expression. While I understand why that may be desirable to demonstrate the relationship of an adjustment and the expression that requires it, it leads to

1. very verbose borrowck output
2. incorrect spans for suggestions

Some diagnostics get around that by giving suggestions relative to other spans we've collected during MIR lowering, such as the span of the method's identifier (e.g. `name` in `.name()`), but this doesn't work too well when things come from desugaring.

I assume it also has lead to numerous tweaks and complications to diagnostics code down the road, which this PR doesn't necessarily aim to fix but may open the gates to fixing later... The last three commits are simplifications due to the fact that we can assume that the move span actually points to what is being moved (and a test).

This regressed in #89110, which was debated somewhat in #90286. cc @Aaron1011 who originally made this change.

r? diagnostics

Fixes #113547
Fixes #111016

### CODE REVIEW

File: compiler/rustc_mir_build/src/thir/cx/expr.rs [hunk 1]
```diff
@@ -278,14 +267,11 @@ impl<'tcx> Cx<'tcx> {
                 // When we apply adjustments to the receiver, use the span of
                 // the overall method call for better diagnostics. args[0]
                 // is guaranteed to exist, since a method call always has a receiver.
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/thir/cx/expr.rs:269]: this comment is now outdated and can be removed

**Comment by oli-obk** [comment]
This may affect miri diagnostic spans, too.

r=me with CI clean (should run miri, right?) and the comment removed

File: compiler/rustc_mir_build/src/thir/cx/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_mir_build/src/thir/cx/expr.rs:269]: I don't think I've ever made a change without accidentally forgetting to delete the comment associated with such change.

**Comment by compiler-errors** [comment]
I'll keep this open for a few days in case someone wants to speak up.

**Comment by saethlin** [comment]
The Miri diagnostic changes seem rather troubling to me. The changes here are all diagnostics trying to point at the creation of the receiver as the problem. Now the span points only to the instance that the method is called on, where previously I think it was pretty clear that we were pointing at the method _call_.

**Comment by compiler-errors** [comment]
@saethlin: The receiver *is* the problem here, though, or more specifically whatever adjustments of the receiver are applied before the method call. I don't think the right span to highlight on "receiver is auto-ref'd before a call happens" is the whole call span.

**Comment by compiler-errors** [comment]
It's arguable whether or not the method call is the important part in explaining that an adjustment happens, and I'm kinda skeptical that borrowck errors (or other errors derived from MIR spans, like miri diagnostics) should point there instead. That's presumably what #89110 was trying to restore from the pre-NLL borrowck, though.

Ideally, we'd pass down richer information than just a single source span per MIR statement for reasons like this :/

**Comment by RalfJung** [comment]
Given that the issue occurs before the actual call, I to agree the old spans were not great - we definitely shouldn't be pointing at the whole call expression including arguments ("rec.method(arg)").

A point could be made that we should point at "rec.method" and not just at "rec". I don't have a strong preference either way.
