### PR TITLE
(rustdoc) [src] link for types defined by macros shows invocation, not defintion

### LINKED ISSUE #39726: Clicking 'src' in rustdoc for a type defined by a macro should show invocation, not macro definition
Repro steps:

1. Go to a type defined by a macro. [Here's](https://hyper.rs/hyper/master/hyper/header/struct.AcceptCharset.html) an example from Hyper.
1. Click "[src]" in the upper right

**Expected:** Open source viewer at the macro invocation which defines this type.
**Observed:** Open source viewer at the macro definition.

### PR DESCRIPTION
**Pull request by liketechnik**
Previously the [src] link on types defined by a macro pointed to the macro definition.

This pr makes the Clean-Implementation for Spans aware of macro defined types, so that the link points to the invocation instead.

I'm not totally sure if it's okay to add the 'macro awareness' in the Clean-Implementation, because it erases that knowledge for all following code. Maybe it would be more sensible to add the check only for the link generation at https://github.com/rust-lang/rust/blob/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/src/librustdoc/html/render/mod.rs#L1619

Closes #39726.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
> I'm not totally sure if it's okay to add the 'macro awareness' in the Clean-Implementation, because it erases that knowledge for all following code.

I don't see why not? :)

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -1967,18 +1967,22 @@ impl Clean<Span> for rustc_span::Span {
             return Span::empty();
         }
 
+        // Check if the span is the result of a macro expansion,
+        // so we can point to the invocation instead of the definition. (See rust-lang/rust#39726)
+        let span = if self.from_expansion() { self.source_callsite() } else { *self };
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs:1972]: The `from_expansion` check isn't necessary I think - if it's not from an expansion, `source_callsite` will return the original span: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_span/lib.rs.html#444-447
```suggestion
        let span = self.source_callsite();
```

**Review by jyn514 — COMMENTED** [review]
Could you also add some tests for the new behavior? They'd go in `src/test/rustdoc`; there's examples there and instructions in https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts.

**Comment by jyn514** [comment]
Actually, it looks like just updating the existing tests should be enough:

```
------------------------------------------
12: @has check failed
	`XPATH PATTERN` did not match
	// @has - '//a[@href="https://example.com/src/external_macro_src/external-macro-src.rs.html#8"]' '[src]'
13: @has check failed
	`XPATH PATTERN` did not match
	// @has - '//a[@href="https://example.com/src/external_macro_src/external-macro-src.rs.html#9-13"]' '[src]'
14: @has check failed
	`XPATH PATTERN` did not match
	// @has - '//a[@href="https://example.com/src/external_macro_src/external-macro-src.rs.html#10-12"]' '[src]'

Encountered 3 errors

------------------------------------------


---- [rustdoc] rustdoc/issue-26606.rs stdout ----

error: htmldocck failed!
status: exit code: 1
command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-26606" "/checkout/src/test/rustdoc/issue-26606.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
10: @has check failed
	`XPATH PATTERN` did not match
	// @has - '//a/@href' '../src/issue_26606_macro/issue-26606-macro.rs.html#3'

Encountered 1 errors

------------------------------------------


---- [rustdoc] rustdoc/thread-local-src.rs stdout ----

error: htmldocck failed!
status: exit code: 1
command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/thread-local-src" "/checkout/src/test/rustdoc/thread-local-src.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
5: @has check failed
	`XPATH PATTERN` did not match
	// @has foo/constant.FOO.html '//a/@href' 'https://doc.rust-lang.org/nightly/src/std/'

Encountered 1 errors

------------------------------------------



failures:
    [rustdoc] rustdoc/external-macro-src.rs
    [rustdoc] rustdoc/issue-26606.rs
    [rustdoc] rustdoc/thread-local-src.rs
```

**Comment by jyn514** [comment]
@bors r+

Thanks for working on this! I actually wanted this just tonight while looking at documentation :)
