### PR TITLE
syntax: add parser recovery for intersection- / and-patterns `p1 @ p2`

### LINKED ISSUE #65400: Error for incorrect identifier patterns could be improved
The compiler could suggest that `e` identifier must precede the pattern in the following code:

playpen link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ca2dc7094a56b0478edefe0faefefe0e

```rust
fn main() {
    let x = 2;

    match x {
        1 ..= 5 @ e => {}
        _ => {}
    }
}
```

Current error message:
```rust
error: expected one of `=>`, `if`, or `|`, found `@`
 --> src/main.rs:5:17
  |
5 |         1 ..= 5 @ e => {}
  |                 ^ expected one of `=>`, `if`, or `|` here

error: aborting due to previous error
```

It could be improved as:
```rust
error: expected one of `=>`, `if`, or `|`, found `@`
 --> src/main.rs:5:17
  |
5 |         1 ..= 5 @ e => {}
  |                 ^ expected one of `=>`, `if`, or `|` here
                    | help: try `e @ 1 ..= 5`


error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/65400.

The recovery comes in two flavors:

1. We know that `p2` is a binding so we can invert as `p2 @ p1`:

```rust
error: pattern on wrong side of `@`
  --> $DIR/intersection-patterns.rs:13:9
   |
LL |         Some(x) @ y => {}
   |         -------^^^-
   |         |         |
   |         |         binding on the right, should be to the left
   |         pattern on the left, should be to the right
   |         help: switch the order: `y @ Some(x)`
```

2. Otherwise we emit a generic diagnostic for the lack of support for intersection patterns:

```rust
error: left-hand side of `@` must be a binding
  --> $DIR/intersection-patterns.rs:23:9
   |
LL |         Some(x) @ Some(y) => {}
   |         -------^^^-------
   |         |         |
   |         |         also a pattern
   |         interpreted as a pattern, not a binding
   |
   = note: bindings are `x`, `mut x`, `ref x`, and `ref mut x`
```

For more on and-patterns, see e.g. https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#and-pattern.

r? @davidtwco 
cc @varkor @lzutao

### CODE REVIEW

File: src/libsyntax/parse/parser/pat.rs [hunk 1]
```diff
@@ -375,6 +376,65 @@ impl<'a> Parser<'a> {
...
+            rhs.span = sp;
+            return Ok(rhs);
+        }
+
+        // The special case above doesn't apply so we may have e.g. `A(x) @ B(y)`.
+        let mut err = self.struct_span_err(sp, "left-hand side of `@` must be a binding pattern");
+        err.span_label(lhs.span, "interpreted as a pattern, not a binding")
+            .span_label(rhs.span, "also a pattern")
+            .note("bindings are `x`, `mut x`, `ref x`, and `ref mut x`");
+        // FIXME(Centril): Introduce `PatKind::Err` and use that instead.
```
Comment (petrochenkov) [inline src/libsyntax/parse/parser/pat.rs]: We don't have `PatKind::Err` because we have `PatKind::Wild` which already works without producing extra errors in all contexts.

Comment (Centril) [reply src/libsyntax/parse/parser/pat.rs]: Ah; will switch to that.

**Review by davidtwco — APPROVED** [review]
LGTM, r=me w/ @petrochenkov's comment and passing CI.

File: src/libsyntax/parse/parser/pat.rs [hunk 2]
```diff
@@ -375,6 +376,65 @@ impl<'a> Parser<'a> {
...
+                _ => true,
+            });
+
+            let lhs_span = lhs.span;
+            // Move the LHS into the RHS as a subpattern.
+            // The RHS is now the full pattern.
+            *sub = Some(lhs);
+
+            self.struct_span_err(sp, "pattern on wrong side of `@`")
+                .span_label(lhs_span, "pattern on the left, should be to the right")
```
Comment (varkor) [inline src/libsyntax/parse/parser/pat.rs]:
```suggestion
                .span_label(lhs_span, "pattern on the left, should be on the right")
```

Comment (varkor) [reply src/libsyntax/parse/parser/pat.rs]: (And below.)

File: src/test/ui/parser/intersection-patterns.stderr [hunk 3]
```diff
@@ -0,0 +1,33 @@
+error: pattern on wrong side of `@`
+  --> $DIR/intersection-patterns.rs:13:9
+   |
+LL |         Some(x) @ y => {}
+   |         -------^^^-
+   |         |         |
+   |         |         binding on the right, should be to the left
+   |         pattern on the left, should be to the right
+   |         help: switch the order: `y@Some(x)`
```
Comment (varkor) [inline src/test/ui/parser/intersection-patterns.stderr]: We surely want spaces here:
```rust
y @ Some(x)
```
I.e. we should change `pprust:: pat_to_string`.

File: src/libsyntax/parse/parser/pat.rs [hunk 4]
```diff
@@ -375,6 +376,65 @@ impl<'a> Parser<'a> {
...
+                .span_label(rhs.span, "binding on the right, should be to the left")
+                .span_suggestion(sp, "switch the order", pprust::pat_to_string(&rhs), applicability)
+                .emit();
+        } else {
+            // The special case above doesn't apply so we may have e.g. `A(x) @ B(y)`.
+            rhs.kind = PatKind::Wild;
+            self.struct_span_err(sp, "left-hand side of `@` must be a binding pattern")
+                .span_label(lhs.span, "interpreted as a pattern, not a binding")
+                .span_label(rhs.span, "also a pattern")
+                .note("bindings are `x`, `mut x`, `ref x`, and `ref mut x`")
```
Comment (varkor) [inline src/libsyntax/parse/parser/pat.rs]:
```suggestion
                .note("binding patterns are `x`, `mut x`, `ref x`, and `ref mut x`")
```

Comment (Centril) [reply src/libsyntax/parse/parser/pat.rs]: @varkor Ah I would prefer to change the `struct_span_err` message instead here to remove "pattern" because the `ref x` in `ref x @ sub` is not a pattern on its own, but it is a binding.

File: src/test/ui/parser/intersection-patterns.stderr (hunk 3 above)
Comment (Centril) [reply src/test/ui/parser/intersection-patterns.stderr]: Make an issue? :)

File: src/test/ui/parser/intersection-patterns.stderr [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+error: pattern on wrong side of `@`
+  --> $DIR/intersection-patterns.rs:32:9
+   |
+LL |         1 ..= 5 @ e => {}
+   |         -------^^^-
+   |         |         |
+   |         |         binding on the right, should be to the left
+   |         pattern on the left, should be to the right
+   |         help: switch the order: `e@1 ..=5`
```
Comment (lzutao) [inline src/test/ui/parser/intersection-patterns.stderr]: Can we make it space-separated?
```suggestion
   |         help: switch the order: `e @ 1 ..=5`
```

Comment (lzutao) [reply src/test/ui/parser/intersection-patterns.stderr]: Oh varkor has commented about this?

Comment (Centril) [reply src/test/ui/parser/intersection-patterns.stderr]: We should, but see @varkor's comment in https://github.com/rust-lang/rust/pull/65410#discussion_r334546244. The bug is in pretty printing.

File: src/test/ui/parser/intersection-patterns.stderr (hunk 3 above)
Comment (Centril) [reply src/test/ui/parser/intersection-patterns.stderr]: ...or I can fix it here. =P

**Comment by Centril** [comment]
@davidtwco Threw in two additional commits to address @varkor's review. Please take a look. :)

**Review by davidtwco — APPROVED** [review]

File: src/libsyntax/parse/parser/pat.rs [hunk 6]
```diff
@@ -375,6 +376,65 @@ impl<'a> Parser<'a> {
...
+        // At this point we attempt to parse `@ $pat_rhs` and emit an error.
+        self.bump(); // `@`
+        let mut rhs = self.parse_pat(None)?;
+        let sp = lhs.span.to(rhs.span);
+
+        if let PatKind::Ident(_, _, ref mut sub @ None) = rhs.kind {
+            // The user inverted the order, so help them fix that.
+            let mut applicability = Applicability::MachineApplicable;
+            lhs.walk(&mut |p| match p.kind {
+                // `check_match` is unhappy if the subpattern has a binding anywhere.
```
Comment (Centril) [inline src/libsyntax/parse/parser/pat.rs]: @pnkfelix This code should be removed when https://github.com/rust-lang/rust/issues/65490 is implemented / stabilized.
