### PR TITLE
CFI: Fix encode_region: unexpected ReEarlyBound(0, 'a)

### LINKED ISSUE #111515: ice: cfi: `encode_region: unexpected ReEarlyBound(0, 'a)`
### Code
`rustc   -Clto  -Zsanitizer=cfi`
```Rust
pub trait MyTrait<'a> {
    type Output: 'a;
    fn gimme_value(&self) -> Self::Output;
}

pub struct MyStruct;

impl<'a> MyTrait<'a> for MyStruct {
    type Output = &'a usize;
    fn gimme_value(&self) -> Self::Output {
        unimplemented!()
    }
}

fn meow<T, F>(t: T, f: F)
where
    T: for<'any> MyTrait<'any>,
    F: for<'any2> Fn(<T as MyTrait<'any2>>::Output),
{
    let v = t.gimme_value();
    f(v);
}

fn main() {
    let struc = MyStruct;
    meow(struc, |foo| {})
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (077fc26f0 2023-05-12)
binary: rustc
commit-hash: 077fc26f0acfa54e9c580534616c17ffc279a9d4
commit-date: 2023-05-12
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:285:13: encode_region: unexpected `ReEarlyBound(0, 'a)`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f746ff6a051 - std::backtrace_rs::backtrace::libunwind::trace::h3078c38bcf244cb0
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f746ff6a051 - std::backtrace_rs::backtrace::trace_unsynchronized::hae8fc14cdc8e4133
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f746ff6a051 - std::sys_common::backtrace::_print_fmt::hd18feb1e248cc700
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f746ff6a051 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0778d4788d776d0c
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f746ffca4af - core::fmt::rt::Argument::fmt::hfc4761188bd54631
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/core/src/fmt/rt.rs:138:9
   5:     0x7f746ffca4af - core::fmt::write::h79a7fdd9d194cc0d
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f746ff5d351 - std::io::Write::write_fmt::hf2bf8061d31c573e
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/io/mod.rs:1712:15
   7:     0x7f746ff69e65 - std::sys_common::backtrace::_print::hc8cc601132b2e52e
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f746ff69e65 - std::sys_common::backtrace::print::hd81a33670e423952
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f746ff6cae7 - std::panicking::default_hook::{{closure}}::h87364cf24ac04124
  10:     0x7f746ff6c8d4 - std::panicking::default_hook::h5b78b38c2a54b17a
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/panicking.rs:288:9
  11:     0x7f74731e8d1b - <rustc_driver_impl[13bf0d04f0b67ce9]::install_ice_hook::{closure#0} as core[9035cf7f5955cd74]::ops::function::FnOnce<(&core[9035cf7f5955cd74]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f746ff6d207 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hdc5f2153a7f41863
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/alloc/src/boxed.rs:1999:9
  13:     0x7f746ff6d207 - std::panicking::rust_panic_with_hook::h045d197919c3e8ba
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/panicking.rs:695:13
  14:     0x7f74736d8181 - std[b0554e33ca57edeb]::panicking::begin_panic::<rustc_errors[26f4fb3d98328957]::ExplicitBug>::{closure#0}
  15:     0x7f74736d5d06 - std[b0554e33ca57edeb]::sys_common::backtrace::__rust_end_short_backtrace::<std[b0554e33ca57edeb]::panicking::begin_panic<rustc_errors[26f4fb3d98328957]::ExplicitBug>::{closure#0}, !>
  16:     0x7f74736d59a6 - std[b0554e33ca57edeb]::panicking::begin_panic::<rustc_errors[26f4fb3d98328957]::ExplicitBug>
  17:     0x7f74736d0954 - <rustc_errors[26f4fb3d98328957]::HandlerInner>::bug::<alloc[b30310a06b34fd3]::string::String>
  18:     0x7f74736d0686 - <rustc_errors[26f4fb3d98328957]::Handler>::bug::<alloc[b30310a06b34fd3]::string::String>
  19:     0x7f747375a48c - rustc_middle[c66c2d2ac5a96442]::util::bug::opt_span_bug_fmt::<rustc_span[8db14cdbe7f466b8]::span_encoding::Span>::{closure#0}
  20:     0x7f747375a2ca - rustc_middle[c66c2d2ac5a96442]::ty::context::tls::with_opt::<rustc_middle[c66c2d2ac5a96442]::util::bug::opt_span_bug_fmt<rustc_span[8db14cdbe7f466b8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f747375a29a - rustc_middle[c66c2d2ac5a96442]::ty::context::tls::with_context_opt::<rustc_middle[c66c2d2ac5a96442]::ty::context::tls::with_opt<rustc_middle[c66c2d2ac5a96442]::util::bug::opt_span_bug_fmt<rustc_span[8db14cdbe7f466b8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f747142973d - rustc_middle[c66c2d2ac5a96442]::util::bug::bug_fmt
  23:     0x7f7473c519d9 - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::encode_region
  24:     0x7f7473c51ad8 - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::encode_substs
  25:     0x7f7473c51543 - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::encode_predicates
  26:     0x7f7473c52bfb - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::encode_ty
  27:     0x7f7473c52f8e - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::encode_ty
  28:     0x7f7473c556c4 - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::typeid_for_fnabi
  29:     0x7f7473c54f8a - rustc_symbol_mangling[f4730ed954a99ba6]::typeid::typeid_itanium_cxx_abi::typeid_for_instance
  30:     0x7f74715a733a - <rustc_codegen_llvm[c5a88784cad09a28]::context::CodegenCx as rustc_codegen_ssa[1d9595b98f3b7f2]::traits::declare::PreDefineMethods>::predefine_fn
  31:     0x7f7472656d91 - rustc_codegen_llvm[c5a88784cad09a28]::base::compile_codegen_unit::module_codegen
  32:     0x7f7472655d28 - rustc_codegen_llvm[c5a88784cad09a28]::base::compile_codegen_unit
  33:     0x7f74728adf3f - rustc_codegen_ssa[1d9595b98f3b7f2]::base::codegen_crate::<rustc_codegen_llvm[c5a88784cad09a28]::LlvmCodegenBackend>
  34:     0x7f74728ad7d0 - <rustc_codegen_llvm[c5a88784cad09a28]::LlvmCodegenBackend as rustc_codegen_ssa[1d9595b98f3b7f2]::traits::backend::CodegenBackend>::codegen_crate
  35:     0x7f74723ea750 - rustc_interface[813041c30d6fe35a]::passes::start_codegen
  36:     0x7f74723e6297 - <rustc_middle[c66c2d2ac5a96442]::ty::context::GlobalCtxt>::enter::<<rustc_interface[813041c30d6fe35a]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[9035cf7f5955cd74]::result::Result<alloc[b30310a06b34fd3]::boxed::Box<dyn core[9035cf7f5955cd74]::any::Any>, rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>
  37:     0x7f74723e5a0d - <rustc_interface[813041c30d6fe35a]::queries::Queries>::ongoing_codegen
  38:     0x7f74723e4ea3 - <rustc_interface[813041c30d6fe35a]::interface::Compiler>::enter::<rustc_driver_impl[13bf0d04f0b67ce9]::run_compiler::{closure#1}::{closure#2}, core[9035cf7f5955cd74]::result::Result<core[9035cf7f5955cd74]::option::Option<rustc_interface[813041c30d6fe35a]::queries::Linker>, rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>
  39:     0x7f74723e250b - std[b0554e33ca57edeb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[813041c30d6fe35a]::util::run_in_thread_pool_with_globals<rustc_interface[813041c30d6fe35a]::interface::run_compiler<core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>, rustc_driver_impl[13bf0d04f0b67ce9]::run_compiler::{closure#1}>::{closure#0}, core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>
  40:     0x7f74723e1c75 - <<std[b0554e33ca57edeb]::thread::Builder>::spawn_unchecked_<rustc_interface[813041c30d6fe35a]::util::run_in_thread_pool_with_globals<rustc_interface[813041c30d6fe35a]::interface::run_compiler<core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>, rustc_driver_impl[13bf0d04f0b67ce9]::run_compiler::{closure#1}>::{closure#0}, core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9035cf7f5955cd74]::result::Result<(), rustc_span[8db14cdbe7f466b8]::ErrorGuaranteed>>::{closure#1} as core[9035cf7f5955cd74]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f746ff776b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45f6a2020dca9236
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/alloc/src/boxed.rs:1985:9
  42:     0x7f746ff776b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha8428b00e1b18042
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/alloc/src/boxed.rs:1985:9
  43:     0x7f746ff776b5 - std::sys::unix::thread::Thread::new::thread_start::h99203a4e418970a3
                               at /rustc/077fc26f0acfa54e9c580534616c17ffc279a9d4/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f746fd15bb5 - <unknown>
  45:     0x7f746fd97d90 - <unknown>
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (077fc26f0 2023-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C lto -Z sanitizer=cfi

query stack during panic:
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by rcvalle**
Fixes #111515 and complements #106547 by adding support for encoding early bound regions and also excluding projections when transforming trait objects' traits into their identities before emitting type checks.

### CODE REVIEW

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 1]
```diff
@@ -272,12 +272,11 @@ fn encode_region<'tcx>(
             s.push('E');
             compress(dict, DictKey::Region(region), &mut s);
         }
-        RegionKind::ReErased => {
+        RegionKind::ReEarlyBound(..) | RegionKind::ReErased => {
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:275]: Why are we not just erasing regions? I don't think we should be handing early-bound vars here.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs [hunk 2]
```diff
@@ -704,14 +703,15 @@ fn transform_predicates<'tcx>(
 ) -> &'tcx List<ty::PolyExistentialPredicate<'tcx>> {
     let predicates: Vec<ty::PolyExistentialPredicate<'tcx>> = predicates
         .iter()
-        .map(|predicate| match predicate.skip_binder() {
+        .filter_map(|predicate| match predicate.skip_binder() {
```
Comment (compiler-errors) [inline compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: Unrelated, but why are we erasing projection predicates here? Those distinguish object types in a meaningful way?

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: The reason for this is when transforming the concrete self into a reference to a trait object before emitting type metadata identifiers for trait methods (in typeid_for_instance, called in predefine_fn), the trait resolved from the method is the identity trait (i.e., early bound), and this is also necessary for trait objects with generic type parameters (see Trait3 in tests).

Unless there is a way to bind the traits at that time, we'll need to work with identity traits (i.e., early bound, and that is the reason why predicates are excluded from the encoding) and add support for encoding early bound types both when emitting type metadata identifiers for trait methods and when emitting type checks.

It's okay to work with early bound types for CFI since we're not encoding/mangling names for linking. (Surely it'd be better if we could bind those traits when doing the method to trait resolution in typeid_for_instance so we'd get better granularity, but I haven't found a way to do that.)

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 1 above)
Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:275]: See below.

File: compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: I'm sorry, I'm not really sure if I follow.

What I mean is that you should be passing this trait ref through `tcx.erase_regions` here:

https://github.com/rust-lang/rust/blob/52dd1cde59ee86e5d61469ee1befe09c132c777d/compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs#L1067

Comment (BoxyUwU) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: what is an "identity trait" I have never heard this terminology before.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: Would you mind providing more information? I think that for CFI we want to know and encode that there was an (erased) region there so trait methods are properly grouped together.

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: > what is an "identity trait" I have never heard this terminology before.

The trait (reference) returned by https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.TraitRef.html#method.identity (which is early bound). (I'm not sure if identity trait is the actual correct name/terminology, but I've been using that to refer to it.)

Comment (compiler-errors) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: Why are you using the trait ref without substituting it?

https://github.com/rust-lang/rust/blob/52dd1cde59ee86e5d61469ee1befe09c132c777d/compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs#L1075

This seems like it's accidentally throwing away the substs that are carried by the instance:

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Instance.html#structfield.substs

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: It's intentional--but probably due to my lack of understanding--for grouping trait methods together for CFI. It's currently grouping methods per trait identity (i.e., early bound), but it surely would be better to group them per trait implementation and specialization (i.e., bound).

However, the instance has a concrete self (i.e., it was monomorphized already), and I'm transforming the concrete self into a reference to a trait object (for grouping trait methods together for CFI) by doing the method to trait resolution in typeid_for_instance. Are the subts from the instance there, the substs expected by the trait identity resolved from the method to trait resolution also there?

Comment (rcvalle) [reply compiler/rustc_symbol_mangling/src/typeid/typeid_itanium_cxx_abi.rs:706]: Even though this was merged, lets continue the discussion because I'm interested in finding out a way to group trait methods more granularly, and if the substs from the monomorphized instance can be used in the trait ref returned from the method to trait resolution that would be great--and I can follow up with a PR to increase the granularity for trait objects using that.
