### PR TITLE
Make `span_extend_to_prev_str()` more robust

### LINKED ISSUE #91560: "error[E0435]: attempt to use a non-constant value in a constant" shows wrong fix with mut variables
I tried this code:

```rust
fn main() {
    let mut length: usize = 2;
    let arr = [0; length];
}
```

I expected to see this happen: Get an error about using non constant values in a constant, with a help pointer showing where to change "let" to "const", like in this example without the mut keyword: 
```
2 |     let length: usize = 2;
  |     ---------- help: consider using `const` instead of `let`: `const length`
```

Instead, this happened: I get the correct error, but it points to a wrong place to fix, off by one character: 
```
2 |     let mut length: usize = 2;
  |      ------------- help: consider using `const` instead of `let`: `const length`
```
This means auto correcting it using the rust-analyzer vscode plugin produces invalid code: 
```rust
lconst length: usize = 2;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (efec54529 2021-12-04)
binary: rustc
commit-hash: efec545293b9263be9edfb283a7aa66350b3acbf
commit-date: 2021-12-04
host: x86_64-pc-windows-msvc
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #91560. The logic in `span_extend_to_prev_str()` is currently quite brittle and fails if there is extra whitespace or something else in between, and it also should return an `Option` but doesn't currently.

### CODE REVIEW

File: compiler/rustc_span/src/source_map.rs [hunk 1]
```diff
@@ -631,24 +631,40 @@ impl SourceMap {
     /// Extends the given `Span` to just after the previous occurrence of `pat` when surrounded by
     /// whitespace. Returns the same span if no character could be found or if an error occurred
     /// while retrieving the code snippet.
```
Comment (Badel2) [inline compiler/rustc_span/src/source_map.rs:633]: This comment needs to be updated, to mention when does this return None.

File: compiler/rustc_resolve/src/diagnostics.rs [hunk 2]
```diff
@@ -456,26 +456,32 @@ impl<'a> Resolver<'a> {
...
-                let sp =
-                    self.session.source_map().span_extend_to_prev_str(ident.span, current, true);
+                let sp = self
+                    .session
+                    .source_map()
+                    .span_extend_to_prev_str(ident.span, current, true, false);
 
-                let pos_for_suggestion = sp.lo().0.saturating_sub(current.len() as u32);
+                let pos_for_suggestion =
+                    sp.map(|sp| sp.lo().0.saturating_sub(current.len() as u32));
```
Comment (Badel2) [inline compiler/rustc_resolve/src/diagnostics.rs:465]: This saturating_sub and the check for `pos_for_suggestion == 0` were needed to avoid an overflow when the pattern was not found. Now that should be impossible because in that case `span_extend_to_prev_str` returns None. So you could just remove this variable and inline it later:

```rust
let sp = sp.with_lo(BytePos(sp.lo().0 - (current.len() as u32)));
```

Also there's another outdated comment above this line, 

`also make sure that the pos for the suggestion is not 0`

that case is now `None` so the check is implicit, you could mention "only calculate suggestion if the span is found" but that's redundant, so just remove that line.

File: compiler/rustc_span/src/source_map.rs [hunk 3]
```diff
@@ -629,26 +629,42 @@ impl SourceMap {
...
         //     ---------- correct span
-        for ws in &[" ", "\t", "\n"] {
-            let pat = pat.to_owned() + ws;
-            if let Ok(prev_source) = self.span_to_prev_source(sp) {
-                let prev_source = prev_source.rsplit(&pat).next().unwrap_or("").trim_start();
-                if prev_source.is_empty() && sp.lo().0 != 0 {
-                    return sp.with_lo(BytePos(sp.lo().0 - 1));
-                } else if accept_newlines || !prev_source.contains('\n') {
-                    return sp.with_lo(BytePos(sp.lo().0 - prev_source.len() as u32));
+        if let Ok(prev_source) = self.span_to_prev_source(sp) {
```
Comment (jackh726) [inline compiler/rustc_span/src/source_map.rs:645]: Could be changed to a `let prev_source = self.span_to_prev_source(sp).ok()?;` to avoid a level of nesting

File: compiler/rustc_resolve/src/diagnostics.rs (hunk 2 above)
Comment (jackh726) [reply compiler/rustc_resolve/src/diagnostics.rs:465]: See the above comment

**Review by jackh726 — CHANGES_REQUESTED** [review]

**Review by Badel2 — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
Failed in a rollup: https://github.com/rust-lang/rust/pull/93491#issuecomment-1025265750
Looks like test output needs to be updated.
@bors r-

**Comment by FabianWolff** [comment]
Fixed. The problem was that an `only-aarch64` test failed, which doesn't run in the CI or when I run the tests locally. This also means that I couldn't run the (hopefully) fixed version of the test, so please double-check with the output in https://github.com/rust-lang/rust/pull/93491#issuecomment-1025265750 (the relevant changes are in the latest commit). Thanks!

@rustbot ready
