### PR TITLE
Change two std process tests to not output to std{out,err}, and fix test suite stat reset in bootstrap CI test rendering

### LINKED ISSUE #136607: Panic (`attempt to subtract with overflow`) when calculating the number of `passed_tests` in `utils\render_tests.rs`
I apologize for not following the bug template + for not having a consistent repro.  I hope that opening this issue will still help (writing down and sharing what we know, looping in the author of the line that panics, etc.).

It seems that when running `rust` tests on Windows, the test binary sometimes (flakily, inconsistently) panics saying (based on two cases when it happened recently - see [here](https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8724459090124258257/+/u/package_rust/stdout) and [here](https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8723799973176581745/+/u/package_rust/stdout):

```
 [1m[32m     Running[0m tests\builtin-clone.rs (build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\builtin_clone-92ab8a9329f9b62b.exe)
 
 running 1 tests
 
 thread 'main' panicked at src\bootstrap\src\utils\render_tests.rs:230:36:
 attempt to subtract with overflow
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So far this has only happened on Windows (and not on Linux).  And it seems to only be happening when running tests from [`library/std/tests/builtin-clone.rs`](https://github.com/rust-lang/rust/blob/a9730c3b5f84a001c052c60c97ed0765e9ceac04/library/std/tests/builtin-clone.rs#L21) (which contain only a single testcase).

It seems that the line that panics has been introduced relatively recently (around a month ago) in https://github.com/rust-lang/rust/commit/dc11857ee77cf022ce23c39e303cf1dfd6a40834#diff-218273cbe7a566fb9d2f12187307eb7fd0e4664abd7c375f0f4cd30183ea78c9R230:

    ```
    let passed_tests = self.executed_tests - (self.failures.len() + self.ignored_tests);
    ```

I guess the panic indicates that `self.executed_tests` is smaller than the sum of `self.failures.len()` and `self.ignored_tests`.  This seems rather unexpected.

FWIW This issue is tracked in Chromium's issue tracker as https://crbug.com/392978169.

### PR DESCRIPTION
**Pull request by jieyouxu**
I don't really know how to test if this unbreaks CI (since #136607 reported that this breaks the CI test rendering *sometimes*).

Fixes #136607.

r? @ChrisDenton (two Windows process tests, but feel free to reroll)

### CODE REVIEW

File: src/bootstrap/src/utils/render_tests.rs [hunk 1]
```diff
@@ -310,6 +310,9 @@ impl<'a> Renderer<'a> {
         match message {
             Message::Suite(SuiteMessage::Started { test_count }) => {
                 println!("\nrunning {test_count} tests");
+                self.benches = vec![];
+                self.failures = vec![];
+                self.ignored_tests = 0;
```
Comment (ranger-ross) [inline src/bootstrap/src/utils/render_tests.rs:315]: Thanks, I over looked this in #135355 :sweat_smile:
