### PR TITLE
Print a message on OOM

### LINKED ISSUE #14674: OOM is silent beyond aborting
Right now when we hit OOM we simply invoke `abort()`, an LLVM intrinsic for an undefined instruction to kill the program. This led me to having to run an unoptimized rustc in GDB for 4+ hours just to figure out the backtrace pointed at `alloc::heap::reallocate`.

We should make OOM easier to debug by at least printing a message. Note, however, that the current OOM strategy was done to allow LLVM to optimize allocations, so we need to balance our priorities with that.

### PR DESCRIPTION
**Pull request by Amanieu**
This adds the ability to override the default OOM behavior by setting a handler function. This is used by libstd to print a message when running out of memory instead of crashing with an obscure "illegal hardware instruction" error (at least on Linux).

Fixes #14674

### CODE REVIEW

**Comment by rkruppe** [comment]
Does this actually work? That is, does `rtabort!` guarantee that it doesn't allocate memory? How is this ensured?

**Comment by Amanieu** [comment]
I checked that the implementation of `rtabort!` doesn't allocate memory on both windows and unix. I also ran a quick test and the message was correctly printed when the allocator failed to allocate memory.

**Comment by Amanieu** [comment]
Actually, I'll take that back, it seems that `rtabort!` does allocate memory on windows for UTF-16 conversion.

**Comment by Amanieu** [comment]
Since this is mainly going to be useful on unix platforms (windows will display a message box from the abort), I could simply make it unix-only where `rtabort!` is known to never allocate memory.

**Comment by Amanieu** [comment]
I instead made the OOM handler reset itself once it is invoked so that any recursive failure to allocate memory will simply fall back to the old behavior of aborting without a message.

**Comment by retep998** [comment]
Even on Windows it would be nice to have a message because often times when running a program in the console, the message box doesn't pop up, and even when it does it doesn't tell you anything useful other than the program crashed. Since most of the time people will hit oom from accidentally passing a silly huge number number to `Vec`, I think we should at least try to print a message. The handler resetting itself seems like a reasonable solution.

**Comment by mmcco** [comment]
Couldn't the error string just be stored as a static?

**Comment by retep998** [comment]
@mmcco Sure, you could have a const array of u16 and write that directly. If that is unreasonable since the message is ascii you could also just cast the u8 codeunits to u16 and store it in a buffer on the stack and write that.

**Comment by alexcrichton** [comment]
@Amanieu yes as you've found this will allocate memory on Windows, I think for two reasons:

1. If we fail to get a handle to the stderr stream, then creating the error to be returned will allocate memory.
2. When printing we'll allocate memory in the utf16 conversion

@retep998 do you know of a guaranteed way to print to the console which is infallible? If so, we could use that vector for printing information.

Otherwise I do agree that resetting the handler to the default "abort and die" seems reasonable right before we attempt to print. Note that this has implications on the multithreaded scenario, however, where if one thread is attempting to print and another hits OOM it'll take down the process without printing anything anyway. I believe that may be fixable by having a global mutex around the OOM handler, but that itself will be tricky to do.

I'm a little hesitant about this as it's very tough to ensure there are 0 allocations along the way in the oom handler unless it's basically written from scratch. I would almost prefer that the handler in libstd is written in such a way that all the code is self-contained to be easily inspected for "this doesn't allocate". It'll be a little uglier, but much easier to audit and future-proof from accidental modifications

**Comment by Amanieu** [comment]
One possibility would be to call `libc::write` directly on file descriptor 2. This would work on all platforms and avoid allocating memory, but it goes against the goal of having `libstd` not depend on `libc` for Windows.

**Comment by retep998** [comment]
@alexcrichton Remove the layers of abstraction? Just get `GetStdHandle(STD_ERROR_HANDLE)`, and call `WriteFile` on it with a simple ascii string. You don't even need to bother checking whether `GetStdHandle` returned a valid handle nor do you need to check the return value of `WriteFile` since `WriteFile` is memory safe with regard to invalid handles and you're going to terminate anyway.

**Comment by Amanieu** [comment]
I implemented a new version which uses separate platform-specific OOM handlers for windows & unix. I only tested the unix version, so there may be issues with the windows code.

Here's a small test program which triggers an OOM: http://ix.io/nkx You may have to adjust the numbers if you are running on a 32-bit system.

**Comment by retep998** [comment]
The windows code looks okay to me, as long as it compiles.

**Comment by alexcrichton** [comment]
@Amanieu yeah that's what I had in mind, I'll take a look.

@retep998 yes I'm aware the layers can be removed, I was wondering if there was an *infallible* method because `GetStdHandle` can fail.

File: src/liballoc/oom.rs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+/// Common out-of-memory routine
+#[cold]
+#[inline(never)]
+#[unstable(feature = "oom", reason = "not a scrutinized interface",
+           issue = "27700")]
+pub fn oom() -> ! {
+    // Reset the OOM handler to avoid infinite loops if the OOM handler tries
+    // to allocate memory and fails.
+    let value = OOM_HANDLER.swap(default_oom_handler as *mut (), Ordering::SeqCst);
```
Comment (alexcrichton) [inline src/liballoc/oom.rs]: I think that with the changes below it should be fine to have this just be `load` instead of `swap`. I'm worried about the usefulness of the `swap` here because if a bunch of threads hit OOM at the same time the process is likely to terminate without printing anything (the second thread will abort the process likely before the first prints).

The implementations below are pretty safe to audit for not having any allocations in them as well, I believe.

File: src/libstd/sys/unix/mod.rs [hunk 2]
```diff
@@ -58,6 +59,20 @@ pub fn init() {
     unsafe {
         assert!(signal(libc::SIGPIPE, libc::SIG_IGN) != !0);
     }
+
+    // A nicer handler for out-of-memory situations than the default one. This
+    // one prints a message to stderr before aborting.
+    fn oom_handler() -> ! {
+        static MSG: &'static [u8] = b"fatal runtime error: Out of memory\n";
+        unsafe {
+            use intrinsics;
```
Comment (alexcrichton) [inline src/libstd/sys/unix/mod.rs]: Could this `use` go up near the `use alloc::oom`?

**Comment by Amanieu** [comment]
If `GetStdHandle` fails then there is nothing attached to stderr, so printing a message is pointless anyways.

File: src/libstd/sys/unix/mod.rs [hunk 3]
```diff
@@ -58,6 +59,20 @@ pub fn init() {
     unsafe {
         assert!(signal(libc::SIGPIPE, libc::SIG_IGN) != !0);
     }
+
+    // A nicer handler for out-of-memory situations than the default one. This
+    // one prints a message to stderr before aborting.
```
Comment (alexcrichton) [inline src/libstd/sys/unix/mod.rs]: Could you expand this to explain:

* It's critical that this function doesn't have any allocations, so it shouldn't be using many abstractions.
* Errors are ignored here because there's not really anything else that can be done.

File: src/libstd/sys/windows/mod.rs [hunk 4]
```diff
@@ -42,7 +42,27 @@ pub mod thread_local;
 pub mod time;
 pub mod stdio;
 
-pub fn init() {}
+pub fn init() {
+    use alloc::oom;
+    // A nicer handler for out-of-memory situations than the default one. This
+    // one prints a message to stderr before aborting.
```
Comment (alexcrichton) [inline src/libstd/sys/windows/mod.rs]: In the spirit of deduplicating information, it should be fine to leave a comment here which just points to the unix impl explaining what's going on.

File: src/libstd/sys/unix/mod.rs [hunk 5]
```diff
@@ -58,6 +59,20 @@ pub fn init() {
...
+    fn oom_handler() -> ! {
+        static MSG: &'static [u8] = b"fatal runtime error: Out of memory\n";
```
Comment (alexcrichton) [inline src/libstd/sys/unix/mod.rs]: stylistically our error messages and such tend to elide capital letters

**Comment by alexcrichton** [comment]
Looking good to me, thanks @Amanieu!

**Comment by Amanieu** [comment]
Updated according to feedback.

**Comment by retep998** [comment]
If `GetStdHandle` does fail then you're pretty much out of luck. It is __the__ way to get stderr and everything else including libc uses it, and would only "fail" in the rare case that an invalid handle was assigned to stderr in which case it is the parent process's fault or some library's fault for setting it to an invalid handle. What else can you do? You could grab a handle to `"$CONOUT"` but that would be annoying as it would override any piping a parent process is trying to do and write directly to the console, and would only work in the windows console. Using `MessageBox` would be even more obnoxious and impractical.

File: src/libstd/sys/unix/mod.rs [hunk 6]
```diff
@@ -45,6 +46,22 @@ pub mod thread_local;
...
+// A nicer handler for out-of-memory situations than the default one. This one
+// prints a message to stderr before aborting. It is critical that this code
+// does not allocate any memory since we are in an OOM situation. Any errors are
+// ignored while printing since there's nothing we can do about them and we are
+// about to exit anyways.
+fn oom_handler() -> ! {
+    use intrinsics;
+    let msg = "fatal runtime error: out of memory\n";
+    unsafe {
+        libc::write(libc::STDERR_FILENO,
```
Comment (nagisa) [inline src/libstd/sys/unix/mod.rs]: `rtabort!`?

Comment (Amanieu) [inline src/libstd/sys/unix/mod.rs]: See @alexcrichton's comment:
> I'm a little hesitant about this as it's very tough to ensure there are 0 allocations along the way in the oom handler unless it's basically written from scratch. I would almost prefer that the handler in libstd is written in such a way that all the code is self-contained to be easily inspected for "this doesn't allocate". It'll be a little uglier, but much easier to audit and future-proof from accidental modifications

Comment (nagisa) [inline src/libstd/sys/unix/mod.rs]: Cool.

**Comment by Amanieu** [comment]
Oops, fixed.
