### PR TITLE
rustdoc: do not use plain summary for trait impls

### LINKED ISSUE #38386: links on first line of trait description are gone
See for example doc for the method scan: https://docs.rs/rawslice/0.1.0/rawslice/struct.SliceIter.html#method.scan

The link at `fold()` is removed because only the first line is shown in the trait impl documentation.

### LINKED ISSUE #48332: Trait method comments gets unescaped by pulldown rustdoc
It seems like documentation comments on trait methods get unescaped when they are shown as implemented traits. Something like `a\*b\*c\*` shows up as a\*b\*c\* in the trait documentation, but as a*b*c* when looking at a type that implements the trait. Adding double escapes makes it look bad on the trait page instead, and replacing `*` with `&#42;` doesn't help, since it gets reinterpreted as `*` anyway.

### LINKED ISSUE #49430: "Read more" shortening for trait impls chops off link references
Here's an example: https://doc.rust-lang.org/nightly/std/option/enum.Option.html#impl-Hash

If you notice here, because rustdoc naïvely chops off all lines of the doc but the first, link references get lost. While this particular instance will be solved by autolinking, this doesn't work if you link to something in general.

### LINKED ISSUE #62741: rustdoc doesn't render links in Trait Implementations sections
https://doc.rust-lang.org/nightly/std/iter/struct.Flatten.html#method.scan
image
https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.scan
image

As we can see, `fold` is not linked in the first image.

### LINKED ISSUE #73474: Rustdoc changes code blocks to inline code in trait implementations
If a doc comment of a trait item begins with a code block, it will be changed to inline code in implementations of that trait, which leads to weird formatting.

### Example

```rust
pub trait TraitExample {
    /// Some text.
    ///
    /// ```
    /// let a = 0;
    /// ```
    fn a() {}

    /// ```
    /// let b = 0;
    /// ```
    fn b() {}

    /// ```rust
    /// let c = 0;
    /// ```
    fn c() {}

    /// ```
    /// // Comment `example`.
    /// let d = 0;
    /// ```
    fn d() {}
}

pub struct StructExample;

impl TraitExample for StructExample {}

```

Here is what it looks like in the implementation for `StructExample`:

2020-06-18-154158_1542x547_scrot

- The docs for the method `a` work as expected.

- The code block of method `b` is changed to inline code.

- The code block of method `c` is also changed to inline code and the word `rust` is shown in the inline code instead of specifying the syntax. There is also a trailing whitespace which is not present in the original code block.

- In the docs of `d` the backticks of the word `example` end the main inline code.

While the inline code looks fine in simple examples (e.g. docs of method `b`), the format is confusing in most cases. The expected behaviour would probably be that the code block does **not** get converted to inline code.

### Example in `std`

Another example for this behaviour can be seen in the [`description`](https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.description) method of `std::error::Error`. The docs of the method  begin with a code block and then get changed to inline code in the implementations.

Documentation in `std::error::Error`:

2020-06-18-160734_1537x305_scrot

Documentation of the implementation in `std::io::Error`:

2020-06-18-160528_1517x191_scrot

More examples: `std::io::Error` ([stable](https://doc.rust-lang.org/stable/std/io/struct.Error.html#implementations), [nightly](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#implementations)), `std::num::ParseIntError` ([stable](https://doc.rust-lang.org/stable/std/num/struct.ParseIntError.html#implementations), [nightly](https://doc.rust-lang.org/nightly/std/num/struct.ParseIntError.html#implementations)).

### Meta

I ran `rustdoc`/`cargo doc` in both stable and nightly which all generated the same result.

`rustdoc --version --verbose`:
```
rustdoc 1.44.1 (c7087fe00 2020-06-17)
binary: rustdoc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

`rustdoc --version --verbose`:
```
rustdoc 1.46.0-nightly (2935d294f 2020-06-17)
binary: rustdoc
commit-hash: 2935d294ff862fdf96578d0cbbdc289e8e7ba81c
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

### PR DESCRIPTION
**Pull request by euclio**
Fixes #38386.
Fixes #48332.
Fixes #49430.
Fixes #62741.
Fixes #73474.

Unfortunately this is not quite ready to go because the newly-working links trigger a bunch of linkcheck failures. The failures are tough to fix because the links are resolved relative to the implementor, which could be anywhere in the module hierarchy.

(In the current docs, these links end up rendering as uninterpreted markdown syntax, so I don't think these failures are any worse than the status quo. It might be acceptable to just add them to the linkchecker whitelist.)

Ideally this could be fixed with intra-doc links ~~but it isn't working for me: I am currently investigating if it's possible to solve it this way.~~ Opened #73829.

EDIT: This is now ready!

### CODE REVIEW

File: src/librustdoc/html/markdown.rs [hunk 1]
```diff
@@ -955,44 +955,34 @@ impl MarkdownSummaryLine<'_> {
...
-                self.is_in += is_in;
-            }
-            if ret.is_some() {
-                self.is_first = false;
-                ret
-            } else {
-                Some(String::new())
+    let mut s = String::with_capacity(md.len() * 3 / 2);
+
+    // FIXME: This doesn't handle intra-doc links: "[`std::io::Error`]" will go through unchanged.
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:970]: You shouldn't need to handle them here, they're handled in a separate pass. See for example the links on https://docs.rs/rand/0.7.3/rand/#traits

File: src/librustdoc/html/markdown.rs [hunk 2]
```diff
@@ -955,44 +955,34 @@ impl MarkdownSummaryLine<'_> {
...
+            Event::Text(text) => s.push_str(text),
+            Event::Code(code) => {
+                s.push('`');
+                s.push_str(code);
+                s.push('`');
             }
+            Event::HardBreak | Event::SoftBreak => s.push(' '),
+            Event::Start(Tag::CodeBlock(..)) => break,
+            Event::End(Tag::Paragraph) => break,
+            _ => (),
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/markdown.rs:982]: Shouldn't you break here as well?

Comment (GuillaumeGomez) [reply src/librustdoc/html/markdown.rs:982]: Ah no, nevermind. In case we have a line written on two lines, it's still one line when rendered so no, it makes sense.

**Comment by GuillaumeGomez** [comment]
As far as I remember, the intra-links are currently not resolved in all shorten doc comments. As long as you don't change the current behavior, I think it's fine to fix it in another PR?

**Comment by euclio** [comment]
The problem is that linkcheck will break for basically anything that implements a trait with a link in the description, because there's no way to write a link that will work for all locations without intra-doc links.

**Comment by GuillaumeGomez** [comment]
Absolutely, that needs to be added and there is an issue open for this missing part. I started to take a look at it but some parts in intra-doc links were missing. Once @jyn514's big PR is merged, we'll be able to go back into it.

**Comment by jyn514** [comment]
> Once @jyn514's big PR is merged, we'll be able to go back into it.

See https://github.com/rust-lang/rust/issues/43466#issuecomment-656237436 for status on that, it's currently waiting on https://github.com/rust-lang/rust/pull/74195.

**Comment by crlf0710** [comment]
Ping from triage. What's the current status? Is this blocked on #74430?

**Comment by euclio** [comment]
Blocked on #74489.

**Comment by jyn514** [comment]
I'm not sure I follow. Why do intra-doc links need to be stabilized for this to work? The relevant bugs in intra-doc links have been fixed, except for https://github.com/rust-lang/rust/issues/73829.

**Comment by jyn514** [comment]
Oh oops I didn't realized you linked to two different PRs. I'll try and work on https://github.com/rust-lang/rust/pull/74489 sometime this weekend.

**Comment by euclio** [comment]
This is ready for another look. I put in a FIXME in linkcheck for the links that need #73829 to work.

File: src/tools/linkchecker/main.rs [hunk 3]
```diff
@@ -138,6 +138,11 @@ fn walk(cache: &mut Cache, root: &Path, dir: &Path, errors: &mut bool) {
 }
 
 fn is_exception(file: &Path, link: &str) -> bool {
+    // FIXME: These links are not resolved in trait impls due to #73829.
+    if link.ends_with("Clone::clone") || link.ends_with("Iterator::try_fold") {
+        return true;
+    }
```
Comment (jyn514) [inline src/tools/linkchecker/main.rs:144]: Can you put these in `LINKCHECK_EXCEPTIONS` instead so you don't accidentally allow more broken links than you meant to?

cc @Manishearth who wrote this originally

**Comment by jyn514** [comment]
A lot of the links you changed were also changed in https://github.com/rust-lang/rust/pull/75832, https://github.com/rust-lang/rust/pull/75852, and https://github.com/rust-lang/rust/pull/75853. So you may want to wait until some of those land.

File: src/tools/linkchecker/main.rs (hunk 3 above)
Comment (euclio) [reply src/tools/linkchecker/main.rs:144]: No, because there are hundreds of broken links.

**Comment by ollie27** [comment]
How about we filter out all links in short summaries when used for trait impls?

**Comment by jyn514** [comment]
FYI https://github.com/rust-lang/rust/pull/75176 is finally working and should be merged in the next few days :). So I'd prefer to wait for that to be fixed instead of adding blanket exceptions for hundreds of broken links.

Building with `--stage 0` shouldn't be an issue since the failures are silent - contributors building locally with `--stage 0` will have broken links on re-exports, but other than that it won't block this PR.

**Comment by euclio** [comment]
Now that #73829 has been fixed, I pushed a version without any linkcheck exceptions.

File: src/librustdoc/html/render/mod.rs [hunk 4]
```diff
@@ -1800,25 +1794,35 @@ fn render_markdown(
...
-                &plain_summary_line(Some(s)),
-                naive_assoc_href(item, link)
-            )
-        } else {
-            plain_summary_line(Some(s))
-        };
-        render_markdown(w, cx, &markdown, item.links(), prefix, is_hidden);
+        let mut summary_html = MarkdownSummaryLine(s, &item.links()).into_string();
+
+        if s.contains('\n') {
```
Comment (GuillaumeGomez) [inline src/librustdoc/html/render/mod.rs:1809]: Does it take into account when you only have an indented code block like:

```rust
///    hello
```

?

File: src/test/rustdoc/trait-impl.rs [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+    fn b();
+
+    /// ```
+    /// This code block should not be in the output, but a Read more link should be generated
+    /// ```
+    fn c();
+
+    /// Escaped formatting a\*b\*c\* works
+    fn d();
+}
```
Comment (GuillaumeGomez) [inline src/test/rustdoc/trait-impl.rs:19]: Please add a test with indented codeblock like this:

```rust
///    hello
```

**Comment by GuillaumeGomez** [comment]
Just one doubt about the indented codeblock but otherwise sounds good. Once the indented codeblock test has been added, it'll be good to go for me!

**Comment by euclio** [comment]
@GuillaumeGomez What's the expected behavior? `unindent-comments` trims the leading spaces so that

```
///    hello
```

is rendered as a paragraph, not a code block. There's nothing special about trait methods here.

**Comment by GuillaumeGomez** [comment]
@euclio It should be a codeblock. :o

**Comment by euclio** [comment]
My point is that

```
///    hello
pub struct Foo;
```

isn't rendered as a code block either.

**Comment by GuillaumeGomez** [comment]
Ah, I might have forgotten a whitespace. Codeblocks are 4 whitespaces, but with rustdoc we have to add a fifth one. Try again with 5. :)

Normally, it should render as a codeblock (it does with the commonmark spec), if not, we have a bug to report.

**Comment by euclio** [comment]
It's the same output with 4 and 5 spaces. I disagree that it's a bug, [seems like expected behavior from the `unindent-comments` pass](https://github.com/rust-lang/rust/blob/b543afca9b90ad6e4689b6d613ab51f9d3ba15e7/src/librustdoc/passes/unindent_comments.rs#L54-L57).

**Comment by GuillaumeGomez** [comment]
No, it's a bug for me: we can't transform a codeblock into text just like that.

**Comment by jyn514** [comment]
@guillaumegomez you haven't answered the question. This is done for all items - what's special about trait methods that they shouldn't be counted? Why is unindenting relevant to this PR? If you think rustdoc shouldn't be doing it in general, that seems like it should be a separate fix.

**Comment by GuillaumeGomez** [comment]
Unless I misunderstood, it's part of `plain_text_summary`, no?

**Comment by jyn514** [comment]
No, it's a separate pass.
https://github.com/rust-lang/rust/blob/b543afca9b90ad6e4689b6d613ab51f9d3ba15e7/src/librustdoc/passes/mod.rs#L98

**Comment by GuillaumeGomez** [comment]
Then I'm just confused. Apart from this, no issue for me.

File: src/librustdoc/html/markdown.rs [hunk 6]
```diff
@@ -955,44 +955,33 @@ impl MarkdownSummaryLine<'_> {
...
-                Some(String::new())
+    let mut s = String::with_capacity(md.len() * 3 / 2);
+
+    for event in Parser::new_ext(md, Options::ENABLE_STRIKETHROUGH) {
+        match &event {
+            Event::Text(text) => s.push_str(text),
+            Event::Code(code) => {
+                s.push('`');
+                s.push_str(code);
+                s.push('`');
```
Comment (jyn514) [inline src/librustdoc/html/markdown.rs:976]: Does this actually have the desired behavior? It seems like it will show literal backticks, not highlight it as code.

Comment (euclio) [reply src/librustdoc/html/markdown.rs:976]: Yep, this is intended. `plain_text_summary` is for non-HTML contexts, like the search index and tooltips. Part of the original bug here is that it was being used for trait impls, too.

I changed the name and added some docs to try and make that clearer.

Comment (jyn514) [reply src/librustdoc/html/markdown.rs:976]: Right, my question was more about whether having those backticks is _desired_ for places that can only show text and not markdown. But it looks like that's [an existing behavior](https://github.com/rust-lang/rust/pull/73819/files#diff-545d93b02fb448fc31d33a6b1e0e0c48L973) so that shouldn't block this PR.

**Review by jyn514 — APPROVED** [review]
LGTM
