### PR TITLE
Fix JS search scripts path

### LINKED ISSUE #145646: Search loads indefinitely in doc.rust-lang.org/nightly due to 404
When searching for anything on https://doc.rust-lang.org/nightly/std or https://doc.rust-lang.org/nightly/core the javascript console shows failure about loading additional javascript files and the search itself never succeeds, showing "Loading search results..." indefinitely.

I tried https://doc.rust-lang.org/nightly/std/?search=refcell

I expected to see the search results.

Instead, I'm seing "Loading search results..." indefinitely and I'm getting those errors in the javascript console:
```
GET https://doc.rust-lang.org/nightly//search.index/0c61ea98bd97.js net::ERR_ABORTED 404 (Not Found)
GET https://doc.rust-lang.org/nightly//search.index/7febe8a55d41.js net::ERR_ABORTED 404 (Not Found)
```

Version of https://doc.rust-lang.org/nightly: 1.91.0-nightly (05f5a58e8 2025-08-19)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
`rootPath` always end with a `/` so we should not add one. Interestingly enough, it only triggers the bug on a website (like https://doc.rust-lang.org/nightly/std/).

Follow-up of https://github.com/rust-lang/rust/pull/144476.
Fixes rust-lang/rust#145646.

cc @notriddle
r? @fmease

### CODE REVIEW

File: src/librustdoc/html/static/js/search.js [hunk 1]
```diff
@@ -5262,7 +5262,8 @@ if (typeof window !== "undefined") {
         },
         loadDataByNameAndHash: (name, hashHex) => {
             const script = document.createElement("script");
-            script.src = `${ROOT_PATH}/search.index/${name}/${hashHex}.js`;
+            const sep = ROOT_PATH.endsWith('/') ? '' : '/';
```
Comment (lqd) [inline src/librustdoc/html/static/js/search.js]:
```suggestion
```

Comment (GuillaumeGomez) [reply src/librustdoc/html/static/js/search.js]: Arf, forgot to remove it. ><

**Review by fmease — APPROVED** [review]
Thanks!

I've manually gone through all references of `ROOT_PATH` and "`DocSearch#rootPath`" (set to `ROOT_PATH` in the ctor) and all other sites seem to append path segments correctly (i.e., without an extra slash).

**Comment by lolbinarycat** [comment]
> That just means that rustdoc can't assume that consecutive slashes get normalized away by whomever ends up interpreting the path.

Is there a way we can modify the gui testing framework to error if there are ever duplicated slashes in the URL path? that seems desirable to stop this from happening again.

**Comment by fmease** [comment]
CC https://en.wikipedia.org/wiki/URI_normalization which classifies "slash collapsing" to be not necessary semantics-preserving.

**Comment by notriddle** [comment]
Yes. I'll have a PR open that tests this in a few minutes.

**Comment by BergmannAtmet** [comment]
A safer way to construct paths needs to be used in my humble opinion, so this [doesn't keep happening](https://blog.rust-lang.org/inside-rust/2023/07/21/crates-io-postmortem/).

That crates.io issue was Rust code which should have just used `Url::join()` or whatever. And I'm sure similar solutions exist for JS too.

**Comment by BergmannAtmet** [comment]
@GuillaumeGomez 

I don't do JS, so I assumed people familiar with it would know better.

Having said that, [this](https://github.com/jfromaniello/url-join) seems to work.

(I wrote a silly and technically wrong comment earlier which I promptly deleted.)
