### PR TITLE
MIR borrowck: implement union-and-array-compatible semantics

### LINKED ISSUE #44831: MIR-borrowck: Add support for `union` types
The MIR-borrowck prototype code left out support for `union`. Luckily we have test cases that illustrate the omission.
 * You can see list of such tests in the [discrepancy spreadsheet](https://docs.google.com/spreadsheets/d/11RfQxTBpdcQW8y7S2ASHv6Wkljj9j2kQ81eJNxTl3KE/edit?usp=sharing).
 * But for ease of reference, I am also transcribing that list into the first comment on this issue.

So the next step is to  incorporate support for `union` into `librustc_mir/borrow_check.rs`.

### LINKED ISSUE #44834: MIR-borrowck: (unsound) fails to see errors in borrowck-vec-pattern-move-tail.rs
Many MIR-borrowck bugs have been categorized as either extra errors or poor diagnostics, but this is a case where MIR borrowck is simply failing to flag *the* main error in the code in question.

We see below that AST-borrowck is flagging the error while MIR-borrowck says nothing. (This is *atop* the mir-borrowck4 branch from https://github.com/rust-lang/rust/pull/44736 )

```
 % ./objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/bin/rustc -Z emit-end-regions \
    -Z borrowck-mir ./src/test/compile-fail/borrowck/borrowck-vec-pattern-move-tail.rs
error[E0506]: cannot assign to `a[..]` because it is borrowed (Ast)
  --> ./src/test/compile-fail/borrowck/borrowck-vec-pattern-move-tail.rs:20:5
   |
16 |         [1, 2, ref tail..] => tail,
   |                -------- borrow of `a[..]` occurs here
...
20 |     a[2] = 0; //~ ERROR cannot assign to `a[..]` because it is borrowed
   |     ^^^^^^^^ assignment to borrowed `a[..]` occurs here

error: aborting due to previous error
```

### LINKED ISSUE #45537: MIR Borrowck does not handle borrows of array elements
This example only shows 1 error, from the AST borrow checker:

```rust
#![allow(warnings)]
#![feature(rustc_attrs)]

fn use_x(_: usize) -> bool { true }

#[rustc_mir_borrowck]
fn main() {
    let mut v = [1, 2, 3];
    let p = &v[0];
    if true {
        use_x(*p);
    } else {
        use_x(22);
    }
    v[0] += 1;
}
```

cc @arielb1

### LINKED ISSUE #45696: MIR-borrowck: behavior around Box<T> is different from AST borrowck
MIR borrowck treats `Box<T>` differently from AST borrowck (not that AST borrowck is terribly consistent there), for example, in the (simplified) test for #17263:

```Rust
struct Foo { a: isize, b: isize }

fn main() {
    let mut x: Box<_> = Box::new(Foo { a: 1, b: 2 });
    let (_a, _b) = (&mut x.a, &mut x.b);
    //~^ ERROR cannot borrow `x` (via `x.b`) as mutable more than once at a time
    //~| NOTE first mutable borrow occurs here (via `x.a`)
    //~| NOTE second mutable borrow occurs here (via `x.b`)

    let mut foo: Box<_> = Box::new(Foo { a: 1, b: 2 });
    let (_c, _d) = (&mut foo.a, &foo.b);
    //~^ ERROR cannot borrow `foo` (via `foo.b`) as immutable
    //~| NOTE mutable borrow occurs here (via `foo.a`)
    //~| NOTE immutable borrow occurs here (via `foo.b`)
}
//~^ NOTE first borrow ends here
//~^^ NOTE mutable borrow ends here
```

AST borrowck reports an error on both lines, but MIR borrowck lets the code pass:
```
error[E0499]: cannot borrow `x` (via `x.b`) as mutable more than once at a time (Ast)
  --> ../src/test/compile-fail/issue-17263.rs:15:36
   |
15 |     let (_a, _b) = (&mut x.a, &mut x.b);
   |                          ---       ^^^ second mutable borrow occurs here (via `x.b`)
   |                          |
   |                          first mutable borrow occurs here (via `x.a`)
...
25 | }
   | - first borrow ends here

error[E0502]: cannot borrow `foo` (via `foo.b`) as immutable because `foo` is also borrowed as mutable (via `foo.a`) (Ast)
  --> ../src/test/compile-fail/issue-17263.rs:21:34
   |
21 |     let (_c, _d) = (&mut foo.a, &foo.b);
   |                          -----   ^^^^^ immutable borrow occurs here (via `foo.b`)
   |                          |
   |                          mutable borrow occurs here (via `foo.a`)
...
25 | }
   | - mutable borrow ends here

error: aborting due to 2 previous errors
```

This should be investigated and solved

### PR DESCRIPTION
**Pull request by arielb1**
Fixes #44831.
Fixes #44834.
Fixes #45537.
Fixes #45696 (by implementing DerefPure semantics, which is what we want going forward).

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/borrow_check.rs [hunk 1]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+
+                    match (elem, &base_ty.sty, access) {
+                        (_, _, Shallow(Some(ArtificialField::Discriminant))) |
+                        (_, _, Shallow(Some(ArtificialField::ArrayLength))) => {
+                            // The discriminant and array length are like
+                            // additional fields on the type; they do not
+                            // overlap any existing data there. Furthermore,
+                            // they cannot actually be a prefix of any
+                            // borrowed lvalue (at least in MIR as it is
+                            // currently.)
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Good comment. Might be good to add an example:

---

So, for example, if we have borrowed `a.b.as<Some>.0`, and we access the discriminant of `a.b`, that is not considered to overlap.

File: src/librustc_mir/borrow_check.rs [hunk 2]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+                            debug!("borrow_conflicts_with_lvalue: implicit field");
+                            return false;
+                        }
+
+                        (ProjectionElem::Deref, _, Shallow(None)) => {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Comment:

---

Borrowed `*a.b` but accessed `a.b` or some prefix thereof. This is ok for shallow accesses, since they don't deref pointers.

File: src/librustc_mir/borrow_check.rs [hunk 3]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+                            // recursive case, let's see if we have a deref.
+                        }
+                    }
+                }
+                (Some(borrow_c), Some(lvalue_c)) => {
+                    match self.lvalue_element_conflict(borrow_c, lvalue_c) {
+                        Overlap::Arbitrary => {
+                            // the borrow partially overlaps. Give up - we
+                            // could try to be smarter here (e.g. counting
+                            // dereferences) but I think we should not.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Comment: This primarily occurs with unions. For example, a borrow of `some_union.x.y` and `some_union.a` would trigger this case (when accessing the `x` and `a` fields).

File: src/librustc_mir/borrow_check.rs [hunk 4]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+                            return false;
+                        }
+                        (ProjectionElem::Deref, ty::TyRef(_, ty::TypeAndMut {
+                            ty: _, mutbl: hir::MutImmutable
+                        }), _) => {
+                            // the borrow goes through a dereference of a shared reference.
+                            //
+                            // I'm not sure why we are tracking these borrows - shared
+                            // references can *always* be aliased, which means the
+                            // permission check already account for this borrow.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Yeah, we should probably not bother to track them.

**Review by nikomatsakis — APPROVED** [review]
r=me, I left some requests for comments, but this seems quite elegant. =)

File: src/librustc_mir/borrow_check.rs [hunk 5]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+    fn borrow_conflicts_with_lvalue(&mut self,
+                                    borrow: &BorrowData<'tcx>,
+                                    lvalue: &Lvalue<'tcx>,
+                                    access: ShallowOrDeep)
+                                    -> bool
+    {
+        debug!("borrow_conflicts_with_lvalue({:?},{:?},{:?})", borrow, lvalue, access);
+
+        // Return the elements pf
+        fn lvalue_elements<'a, 'tcx>(lvalue: &'a Lvalue<'tcx>) -> Vec<&'a Lvalue<'tcx>>
```
[the remark this answers is not in the document]
Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: Sure enough, I'll switch to use reversed prefixes instead.

File: src/librustc_mir/borrow_check.rs [hunk 6]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
...
+                        }
+                    }
+                    (ProjectionElem::Downcast(_, v1), ProjectionElem::Downcast(_, v2)) => {
+                        // different variants are treated as having disjoint fields,
+                        // even if they occupy the same "space", because it's
+                        // impossible for 2 variants of the same enum to exist
+                        // (and therefore, to be borrowed) at the same time.
+                        //
+                        // Note that this is different from unions, but both
+                        // behaviors are grandfathered.
```
[the remark this answers is not in the document]
Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: > In any case, we could alter unions to behave similarly to enums if we wanted, I imagine, but not the opposite, right? Or is there a reason we can't?

I think we could make unions behave similarly to enums, it would just be "super-unsafe".

File: src/librustc_mir/borrow_check.rs [hunk 7]
```diff
@@ -1115,13 +1116,238 @@ enum NoMovePathFound {
     ReachedStatic,
 }
 
+enum Overlap {
```
[the remark this answers is not in the document]
Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: Well for me it represented the "current" effect for a prefix of the lvalue (i.e. it's a monoid, and `lvalue_conflicts_with_borrow` is its product over all pairs of path elements).

[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: OK. These seem like similar ways of saying the same thing. In any case, the point is that this represents the "contribution" of a single part of a path.

File: src/librustc_mir/borrow_check.rs [hunk 8]
```diff
@@ -158,6 +166,9 @@ pub struct MirBorrowckCtxt<'cx, 'gcx: 'tcx, 'tcx: 'cx> {
     node_id: ast::NodeId,
     move_data: &'cx MoveData<'tcx>,
     param_env: ParamEnv<'gcx>,
+    /// This keeps track of whether local variables are free-ed when the function
+    /// exits even without a `StorageDead`.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Nit: It'd be nice to say something about why it might be true or false

File: src/librustc_mir/borrow_check.rs [hunk 9]
```diff
@@ -744,27 +751,29 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+    fn place_is_invalidated_at_exit(&mut self, place: &Place<'tcx>) -> bool {
         debug!("place_is_invalidated_at_exit({:?})", place);
         let root_place = self.prefixes(place, PrefixSet::All).last().unwrap();
 
         // FIXME(nll-rfc#40): do more precise destructor tracking here. For now
         // we just know that all locals are dropped at function exit (otherwise
         // we'll have a memory leak) and assume that all statics have a destructor.
-        let (might_be_alive, will_be_dropped) = match root_place {
+        //
+        // FIXME: allow thread-locals to borrow other thread locals?x
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Can you say a bit more about this? It seems like you have disabled these checks in statics/constants, right? Is that what you meant?

Comment (nikomatsakis) [reply src/librustc_mir/borrow_check.rs]: Oh, never mind, that flag was for whether *locals* are considered dropped, right...

File: src/librustc_mir/borrow_check.rs [hunk 10]
```diff
@@ -1248,13 +1273,356 @@ enum NoMovePathFound {
...
+    /// different fields of a union are borrowed. For example,
+    /// if `u` is a union, we have no way of telling how disjoint
+    /// `u.a.x` and `a.b.y` are.
+    Arbitrary,
+    /// The places are either completely disjoint or equal - this
+    /// is the "base case" on which we recur for extensions of
+    /// the place.
+    EqualOrDisjoint,
+    /// The places are disjoint, so we know all extensions of them
+    /// will also be disjoint.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: nice

File: src/librustc_mir/borrow_check.rs [hunk 11]
```diff
@@ -1248,13 +1273,356 @@ enum NoMovePathFound {
...
+    Disjoint,
+}
+
 impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
+    // Given that the bases of `elem1` and `elem2` are always either equal
+    // or disjoint (and have the same type!), return the overlap situation
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: does "equal or disjoint" mean "not known to be disjoint", basically? I guess it is referencing the `EqualOrDisjoint` variant? The phrasing as is sounds a bit like something that can't be false (i.e., sort of like "given that X is either true or false"), though I understand what you mean by it. Maybe just "given that the basis of `elem1` and `elem2` thus far overlap with `Overlap::EqualOrDisjoint`" or something.

File: src/librustc_mir/borrow_check.rs [hunk 12]
```diff
@@ -1248,13 +1273,356 @@ enum NoMovePathFound {
...
+                    (ProjectionElem::Index(..), ProjectionElem::Subslice { .. }) |
+                    (ProjectionElem::ConstantIndex { .. }, ProjectionElem::Index(..)) |
+                    (ProjectionElem::ConstantIndex { .. }, ProjectionElem::ConstantIndex { .. }) |
+                    (ProjectionElem::ConstantIndex { .. }, ProjectionElem::Subslice { .. }) |
+                    (ProjectionElem::Subslice { .. }, ProjectionElem::Index(..)) |
+                    (ProjectionElem::Subslice { .. }, ProjectionElem::ConstantIndex { .. }) |
+                    (ProjectionElem::Subslice { .. }, ProjectionElem::Subslice { .. }) => {
+                        // Array indexes (`a[0]` vs. `a[i]`). These can either be disjoint
+                        // (if the indexes differ) or equal (if they are the same), so this
+                        // is the recursive case that gives "equal *or* disjoint" its meaning.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Yep, nice comment here.

One question, but perhaps this is the FIXME. IIRC the intention with `ConstantIndex` and friends was to be able to handle things like:

```rust
let mut x = [1, 2];
match foo {
   [ref mut a, ref mut b] => { ... }
}
```

without an error. This current code doesn't handle that sort of thing yet, does it? (These will in MIR be sequentialized, after all.)

File: src/librustc_mir/borrow_check.rs [hunk 13]
```diff
@@ -1248,13 +1273,356 @@ enum NoMovePathFound {
...
+        {
+            let mut result = vec![];
+            let mut place = place;
+            loop {
+                result.push(place);
+                match place {
+                    Place::Projection(interior) => {
+                        place = &interior.base;
+                    }
+                    _ => {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: Nit: I'd personally be happier with `Place::Local(..) | Place::Static(..) => { ... }`. When there are so few cases, I prefer to see them written out, so that I don't have to try and remember what they are. That said, I think `Projection` is clearly the only case that would want to be handled here (that's the whole *point* of separating projections from base case...), so if you prefer to keep it as is, maybe use `if let` instead just to be more compact?

File: src/librustc_mir/borrow_check.rs [hunk 14]
```diff
@@ -1248,13 +1273,356 @@ enum NoMovePathFound {
...
+        // is a full deep access, then we *know* the borrow conflicts with it. However,
+        // if the access is shallow, then we can proceed:
+        //
+        //       x1[2].y    | (*x1[i].y)    -- a deref! the access can't get past this, so we
+        //                                     are disjoint
+        //
+        // Our invariant is, that at each step of the iteration:
+        //  - If we didn't run out of access to match, our borrow and access are comparable
+        //    and either equal or disjoint.
+        //  - If we did run out of accesss, the borrow can access a part of it.
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check.rs]: This is a wonderful comment.

**Review by nikomatsakis — APPROVED** [review]
r=me. I left some nits, but they are just nits.

**Comment by nikomatsakis** [comment]
Also:

@bors p=1

This is super critical to making MIR borrowck functional.

**Comment by nikomatsakis** [comment]
@arielb1 seems like it needs moar rebase. =(

**Comment by kennytm** [comment]
@nikomatsakis This should be good to go?
