### PR TITLE
fix: Do not ICE on normalization failure of an extern static item

### LINKED ISSUE #148161: ICE: Failed to normalize Alias(Projection, AliasTy...
I tried this code:

### Code

```Rust
trait Trait {
    type Assoc;
}

impl Trait for u8 {
    type Assoc = i8;
}

struct Struct<T: Trait> {
    member: T::Assoc,
}

unsafe extern "C" {
    static VAR: Struct<i8>;
}


fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (4068bafed 2025-10-20)
binary: rustc
commit-hash: 4068bafedd8ba724e332a5221c06a6fa531a30d2
commit-date: 2025-10-20
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.3
```

I expected to see error: the trait bound `i8: Trait` is not satisfied.

However, it triggered ICE.(It can also be triggered on the stable version.)

<details><summary><strong>Program Output</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:171:13: Failed to normalize Alias(Projection, AliasTy { args: [i8], def_id: DefId(0:4 ~ example[cbae]::Trait::Assoc), .. }) in typing_env=TypingEnv { typing_mode: Analysis { defining_opaque_types_and_generators: [] }, param_env: ParamEnv { caller_bounds: [] } }, maybe try to call `try_normalize_erasing_regions` instead


thread 'rustc' (3) panicked at compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:171:13:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::normalize_generic_arg_after_erasing_regions
   7: <rustc_middle::ty::context::TyCtxt>::struct_tail_for_codegen
   8: rustc_hir_analysis::check::wfcheck::check_static_item
   9: rustc_hir_analysis::collect::type_of::type_of
      [... omitted 1 frame ...]
  10: rustc_hir_analysis::check::check::check_item_type
  11: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  12: rustc_hir_analysis::check::wfcheck::check_type_wf
      [... omitted 1 frame ...]
  13: rustc_hir_analysis::check_crate
  14: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  15: <rustc_interface::passes::create_and_enter_global_ctxt<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core::ops::function::FnOnce<(&rustc_session::session::Session, rustc_middle::ty::context::CurrentGcx, alloc::sync::Arc<rustc_data_structures::jobserver::Proxy>, &std::sync::once_lock::OnceLock<rustc_middle::ty::context::GlobalCtxt>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_middle::arena::Arena>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_hir::Arena>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  16: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/app/rustc-ice-2025-10-27T03_51_24-1.txt` to your bug report

note: compiler flags: -C debuginfo=2 --crate-type bin -C linker=/opt/compiler-explorer/gcc-15.2.0/bin/gcc

query stack during panic:
#0 [type_of] computing type of `VAR`
#1 [check_well_formed] checking that `` is well-formed
#2 [check_type_wf] checking that types are well-formed
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes https://github.com/rust-lang/rust/issues/148161

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 1]
```diff
@@ -1191,7 +1191,24 @@ pub(crate) fn check_static_item<'tcx>(
         let is_foreign_item = tcx.is_foreign_item(item_id);
 
         let forbid_unsized = !is_foreign_item || {
```
Comment (jdonszelmann) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs]: Even though it was already done this way, I quite dislike the block on the right hand side of the or. Could you rewrite this condition to be a bit clearer?

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 2]
```diff
@@ -1191,7 +1191,24 @@ pub(crate) fn check_static_item<'tcx>(
...
-            let tail = tcx.struct_tail_for_codegen(item_ty, wfcx.infcx.typing_env(wfcx.param_env));
+            let tail = tcx.struct_tail_raw(
+                item_ty,
+                &ObligationCause::dummy(),
+                |ty| match tcx
+                    .try_normalize_erasing_regions(wfcx.infcx.typing_env(wfcx.param_env), ty)
```
Comment (jdonszelmann) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs]: This is an area of the compiler I'm still learning about, so I asked @BoxyUwU for her opinion to also learn from that (<3). To summarize our discussion:

Though this works the `erasing_regions` part is a bit awkward and probably unnecessary. It also skips some error reporting, hence we get a `Result` back. Though we think this probably almost never goes into the `Err()` case, it might be better to use  `wfcx.normalize` instead. If there are diagnostics, it would then also emit those.

Having said that, maybe it leads to duplicate diagnostics so let me know if that works out or not.

File: tests/ui/static/extern-static-normalization-failure-issue-148161.rs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+trait Trait {
```
Comment (jdonszelmann) [inline tests/ui/static/extern-static-normalization-failure-issue-148161.rs:2]: Could you leave a little comment that specifically for extern statics we forgot to normalize? Though the issue number is in the test name, I do like it if there's a tiny bit of context :)

**Review by jdonszelmann — CHANGES_REQUESTED** [review]
almost there I think! let me know how it goes and I'll give it another pass soon :)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149210/af17d59d71cd344fb34caab3e96c88b7c137f872..ec630b35e0a8f94656d2e2edbcad7feecf29b05a)*

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 4]
```diff
@@ -1186,14 +1186,21 @@ pub(crate) fn check_static_item<'tcx>(
 ) -> Result<(), ErrorGuaranteed> {
     enter_wf_checking_ctxt(tcx, item_id, |wfcx| {
         let span = tcx.ty_span(item_id);
-        let item_ty = wfcx.deeply_normalize(span, Some(WellFormedLoc::Ty(item_id)), ty);
+        let loc = Some(WellFormedLoc::Ty(item_id));
+        let item_ty = wfcx.deeply_normalize(span, loc, ty);
 
         let is_foreign_item = tcx.is_foreign_item(item_id);
+        let is_structurally_foreign_item = || {
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1193]: I took this name because it checks the foreign-ness of the nestedly last field of the type in question, which resembles check for structural sizedness of a type in
https://github.com/rust-lang/rust/blob/42ec52babac2cbf2bb2b9d794f980cbcb3ebe413/compiler/rustc_next_trait_solver/src/solve/assembly/structural_traits.rs#L160-L177

and
https://github.com/rust-lang/rust/blob/42ec52babac2cbf2bb2b9d794f980cbcb3ebe413/compiler/rustc_ty_utils/src/ty.rs#L115-L131

File: tests/ui/static/extern-static-normalization-failure-issue-148161.rs (hunk 3 above)
Comment (ShoyuVanilla) [reply tests/ui/static/extern-static-normalization-failure-issue-148161.rs:2]: I briefly added some comments and fixed a typo in the test filename (one of those `-` was `_` 😅)

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 5]
```diff
@@ -1186,14 +1186,21 @@ pub(crate) fn check_static_item<'tcx>(
...
+            let tail = tcx.struct_tail_raw(
+                item_ty,
+                &ObligationCause::dummy(),
+                |ty| wfcx.deeply_normalize(span, loc, ty),
```
Comment (ShoyuVanilla) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1197]: I tried `wfcx.normalize` as you suggested - actually `deeply_normalize`, which works exactly same as `wfcx.normalize` with the current solver, but necessary in next-solver - and everything is green.
The same `loc` with the `item_ty` is needed to add an extra note to the diagnostic that indicates where the failed bound comes from.

**Review by ShoyuVanilla — COMMENTED** [review]
@rustbot ready

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/149210/42ec52babac2cbf2bb2b9d794f980cbcb3ebe413..cf4668285f0800f9818e65dc5ad807ea1e268109)*
