### PR TITLE
hide internal types/traits from std docs via new #[doc(masked)] attribute

### LINKED ISSUE #43701: Stable Rustdoc contains broken links (to compiler internal crates)
The nightly rustdoc for `Deref` contains multiple links under Implementors which do not work.
https://doc.rust-lang.org/nightly/std/ops/trait.Deref.html
for example `InternedString, RcSlice<T>, ThinVec<T>, P<T>, ...`

rustdoc_nightly_deref

Those links seem to come from internal crates like 
rustc_data_structures, rustc_errors, syntax, syntax_pos

The problem does not appear for the stable documentation.
https://doc.rust-lang.org/stable/std/ops/trait.Deref.html

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Fixes #43701 (hopefully for good this time)

This PR introduces a new parameter to the `#[doc]` attribute that rustdoc looks for on `extern crate` statements. When it sees `#[doc(masked)]` on such a statement, it hides traits and types from that crate from appearing in either the "Trait Implementations" section of many type pages, or the "Implementors" section of trait pages. This is then applied to the `libc`/`rand`/`compiler_builtins` imports in libstd to prevent those crates from creating broken links in the std docs.

Like in #43348, this also introduces a feature gate, `doc_masked`, that controls the use of this parameter.

To view the std docs generated with this change, head to https://tonberry.quietmisdreavus.net/std-43701/std/index.html.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Tracking issue: #44027

File: src/test/rustdoc/doc-masked.rs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+// except according to those terms.
+
+#![feature(doc_masked)]
+
+#![doc(masked)]
+extern crate std as realstd;
+
+// @has doc_masked/struct.LocalStruct.html
+// @has - '//*[@class="impl"]//code' 'impl LocalTrait for LocalStruct'
+// @!has - '//*[@class="impl"]//code' 'impl Copy for LocalStruct'
```
Comment (kennytm) [inline src/test/rustdoc/doc-masked.rs]: Masking failed. I guess it's because `Copy` and `usize` are from libcore instead of libstd?

```
[00:50:50] ---- [rustdoc] rustdoc/doc-masked.rs stdout ----
[00:50:50] 	
[00:50:50] error: htmldocck failed!
[00:50:50] status: exit code: 1
[00:50:50] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/doc-masked.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/doc-masked.rs"
[00:50:50] stdout:
[00:50:50] ------------------------------------------
[00:50:50] 
[00:50:50] ------------------------------------------
[00:50:50] stderr:
[00:50:50] ------------------------------------------
[00:50:50] 18: @!has check failed
[00:50:50] 	`XPATH PATTERN` did not match
[00:50:50] 	// @!has - '//*[@class="impl"]//code' 'impl Copy for LocalStruct'
[00:50:50] 24: @!has check failed
[00:50:50] 	`XPATH PATTERN` did not match
[00:50:50] 	// @!has - '//*[@id="implementors-list"]//code' 'impl LocalTrait for usize'
[00:50:50] 
[00:50:50] Encountered 2 errors
[00:50:50] 
[00:50:50] ------------------------------------------
[00:50:50] 
[00:50:50] thread '[rustdoc] rustdoc/doc-masked.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2511:8
[00:50:50] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:50:50] 
[00:50:50] 
[00:50:50] failures:
[00:50:50]     [rustdoc] rustdoc/doc-masked.rs
[00:50:50] 
[00:50:50] test result: FAILED. 162 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

Comment (QuietMisdreavus) [inline src/test/rustdoc/doc-masked.rs]: Oh, that makes more sense. I saw the travis failure last night, but chalked it up to getting the htmldocck rules wrong. I'll poke at this more and see what can be done about it.

File: src/libstd/lib.rs [hunk 2]
```diff
@@ -352,18 +353,22 @@ use prelude::v1::*;
...
 #[macro_use]
 #[macro_reexport(vec, format)]
 extern crate alloc;
 extern crate alloc_system;
 extern crate std_unicode;
+#[doc(masked)]
 extern crate libc;
 
 // We always need an unwinder currently for backtraces
 extern crate unwind;
```
Comment (ollie27) [inline src/libstd/lib.rs]: `unwind` would also need to be `doc(masked)` to get rid of the impls for `_Unwind_Reason_Code` and `_Unwind_Action` on the [`Clone`](https://doc.rust-lang.org/nightly/std/clone/trait.Clone.html#implementors) page for example.

**Comment by kennytm** [comment]
4 failures now 😒 

<details>

```
[00:53:35] ---- [rustdoc] rustdoc/doc-masked.rs stdout ----
[00:53:35] 	
[00:53:35] error: htmldocck failed!
[00:53:35] status: exit code: 1
[00:53:35] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/doc-masked.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/doc-masked.rs"
[00:53:35] stdout:
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] stderr:
[00:53:35] ------------------------------------------
[00:53:35] 18: @!has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @!has - '//*[@class="impl"]//code' 'impl Copy for LocalStruct'
[00:53:35] 
[00:53:35] Encountered 1 errors
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] thread '[rustdoc] rustdoc/doc-masked.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2435:8
[00:53:35] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:53:35] 
[00:53:35] ---- [rustdoc] rustdoc/extern-impl.rs stdout ----
[00:53:35] 	
[00:53:35] error: htmldocck failed!
[00:53:35] status: exit code: 1
[00:53:35] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/extern-impl.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/extern-impl.rs"
[00:53:35] stdout:
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] stderr:
[00:53:35] ------------------------------------------
[00:53:35] 32: @has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @has - '//code' 'impl Bar for fn()'
[00:53:35] 34: @has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @has - '//code' 'impl Bar for extern "C" fn()'
[00:53:35] 36: @has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @has - '//code' 'impl Bar for extern "system" fn()'
[00:53:35] 
[00:53:35] Encountered 3 errors
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] thread '[rustdoc] rustdoc/extern-impl.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2435:8
[00:53:35] 
[00:53:35] ---- [rustdoc] rustdoc/inline_cross/issue-33113.rs stdout ----
[00:53:35] 	
[00:53:35] error: htmldocck failed!
[00:53:35] status: exit code: 1
[00:53:35] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/inline_cross/issue-33113.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/inline_cross/issue-33113.rs"
[00:53:35] stdout:
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] stderr:
[00:53:35] ------------------------------------------
[00:53:35] 18: @has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @has - '//code' "for &'a char"
[00:53:35] 
[00:53:35] Encountered 1 errors
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] thread '[rustdoc] rustdoc/inline_cross/issue-33113.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2435:8
[00:53:35] 
[00:53:35] ---- [rustdoc] rustdoc/issue-29503.rs stdout ----
[00:53:35] 	
[00:53:35] error: htmldocck failed!
[00:53:35] status: exit code: 1
[00:53:35] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-29503.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/issue-29503.rs"
[00:53:35] stdout:
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] ------------------------------------------
[00:53:35] stderr:
[00:53:35] ------------------------------------------
[00:53:35] 18: @has check failed
[00:53:35] 	`XPATH PATTERN` did not match
[00:53:35] 	// @has - "//ul[@id='implementors-list']/li" "impl<T> MyTrait for T where T: Debug"
[00:53:35] 
[00:53:35] Encountered 1 errors
[00:53:35] 
[00:53:35] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:322:21
[00:53:35] ------------------------------------------
[00:53:35] 
[00:53:35] thread '[rustdoc] rustdoc/issue-29503.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2435:8
[00:53:35] 
[00:53:35] 
[00:53:35] failures:
[00:53:35]     [rustdoc] rustdoc/doc-masked.rs
[00:53:35]     [rustdoc] rustdoc/extern-impl.rs
[00:53:35]     [rustdoc] rustdoc/inline_cross/issue-33113.rs
[00:53:35]     [rustdoc] rustdoc/issue-29503.rs
[00:53:35] 
[00:53:35] test result: FAILED. 159 passed; 4 failed; 1 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by QuietMisdreavus** [comment]
@kennytm Yeah, I'm needing to push to be able to test, since htmldocck.py doesn't work on python 3. `>_>`

It seems I was overzealous in my masking. Regardless, even with that change, Clone is still left out because its DefId still points to libcore instead of libstd.

**Comment by kennytm** [comment]
@QuietMisdreavus Seems only a problem of import (I haven't actually tried to run it after patching). These diffs should make it work for Python 3:

```diff
diff --git a/src/etc/htmldocck.py b/src/etc/htmldocck.py
index a5449b748d..c8246bf727 100644
--- a/src/etc/htmldocck.py
+++ b/src/etc/htmldocck.py
@@ -110,11 +110,17 @@ import os.path
 import re
 import shlex
 from collections import namedtuple
-from HTMLParser import HTMLParser
+try:
+    from html.parser import HTMLParser
+except ImportError:
+    from HTMLParser import HTMLParser
 from xml.etree import cElementTree as ET
 
 # &larrb;/&rarrb; are not in HTML 4 but are in HTML 5
-from htmlentitydefs import entitydefs
+try:
+    from html.entities import entitydefs
+except ImportError:
+    from htmlentitydefs import entitydefs
 entitydefs['larrb'] = u'\u21e4'
 entitydefs['rarrb'] = u'\u21e5'
 entitydefs['nbsp'] = ' '
```

**Comment by QuietMisdreavus** [comment]
@kennytm Want to make a new PR for that? I'm sure many people would love you for it. `:P`

**Comment by kennytm** [comment]
@QuietMisdreavus Let me verify if it actually works on Python 3 first 😄

**Comment by QuietMisdreavus** [comment]
Thinking about it more, it seems that to make this work how the tests expect it to basically amounts to fixing https://github.com/rust-lang/rust/issues/22083. Since the DefId for exported types points to the original crate, any reference to them later on, even if from the exported location, still points to that original crate. Add another thing to the pile of "reexport pains".

So... does that block this PR? It still works in the context of std, just not so well outside of it.

**Comment by QuietMisdreavus** [comment]
To help anyone who wants to see this effect when run on std and not just on my toy (broken) examples, i have [a rendering of libstd docs here](https://tonberry.quietmisdreavus.net/std-43701/std/index.html).

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/dev-tools because i just realized i never properly pinged the team.

This PR hides some internal types from appearing in the std docs by adding a new flag to the doc attribute, `#[doc(masked)]`. The problem is that the tests i wrote for this applied it to std itself, which doesn't completely work, since re-exported types aren't marked as coming from their exported crate.

The question i'm posing to the team (which may need to be relayed to other teams, come to think of it `>_>`) is whether we still want to land this, and how i should update the tests/docs if so. I think it's still useful in the context of the std docs, but until i/we can handle re-exports with this it's less useful outside of it.

**Comment by nrc** [comment]
We discussed this at today's dev-tools meetings. We should land this as is and iterate (since it is behind a feature flag). Better to fix the std links issue sooner and work towards something more generally useful.

**Comment by QuietMisdreavus** [comment]
I've fixed the merge conflict. The travis failure is due to a stalled macOS build.

**Comment by carols10cents** [comment]
I restarted the one osx builder. 

ping looks like this is ready for your review, @steveklabnik !

**Comment by carols10cents** [comment]
ping @steveklabnik @rust-lang/docs @rust-lang/dev-tools, this needs a review please!

**Comment by steveklabnik** [comment]
Looks good to me.
