### PR TITLE
Do not suggest a placeholder to const and static without a type

### LINKED ISSUE #101755: `placeholder _` is referred when there is a trait const with no type whatsoever.
Given the following code:

```rust
trait Qqq {
    const A;
}
```

(https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a84a11a114f0dcb9aa8f1ea1987db82f)

The current output is:

```
error[E0121]: the placeholder `_` is not allowed within types on item signatures for constants
 --> src/lib.rs:2:12
  |
2 |     const A;
  |            ^ not allowed in type signatures

error: missing type for `const` item
 --> src/lib.rs:2:12
  |
2 |     const A;
  |            ^ help: provide a type for the item: `: <type>`

...
```

Ideally the output should look like:

```
error: missing type for `const` item
 --> src/lib.rs:2:12
  |
2 |     const A;
  |            ^ help: provide a type for the item: `: <type>`

...
```

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #101755

### CODE REVIEW

File: compiler/rustc_typeck/src/collect.rs [hunk 1]
```diff
@@ -857,7 +857,21 @@ fn convert_trait_item(tcx: TyCtxt<'_>, trait_item_id: hir::TraitItemId) {
...
+                    // When the const does not have a type, this error should not be emitted.
+                    .filter(|span| {
+                        !tcx.sess.diagnostic().has_stashed_diagnostic(*span, StashKey::ItemNoType)
+                    })
+                    .collect::<Vec<_>>(),
+                false,
+                None,
+                "constant",
+            );
         }
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/collect.rs:875]: This is a bit more generalized than necessary -- `ItemNoType` will only be stashed if we have a `_` infer type as the type of the const -- it will never be nested. Try something like:

```rust
hir:TraitItemKind(hir_ty, ..) => {
  tcx.ensure().type_of(trait_item_id.def_id);
  // Account for `const C: _;`.
  let mut visitor = HirPlaceholderCollector::default();
  visitor.visit_trait_item(trait_item);
  if !tcx.sess.diagnostic().has_stashed_diagnostic(hir_ty.span, StashKey::ItemNoType) {
    placeholder_type_error(tcx, None, visitor.0, false, None, "constant");
  }
}
```

**Review by compiler-errors — COMMENTED** [review]
One nit
