### PR TITLE
Use less CString in the examples of CStr.

### LINKED ISSUE #83999: Docs for `CStr.as_ptr()` are describing `CString`
The documentation for [CStr.as_ptr()](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.as_ptr) is identical to docs for [CString.as_ptr()](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr) and does not work for `CStr`. For instance, the provided code samples don't even create a `CStr`.

### PR DESCRIPTION
**Pull request by hkBst**
Fixes #83999

### CODE REVIEW

File: library/core/src/ffi/c_str.rs [hunk 1]
```diff
@@ -449,38 +445,59 @@ impl CStr {
...
-    /// let ptr = CString::new("Hello").expect("CString::new failed").as_ptr();
-    /// unsafe {
-    ///     // `ptr` is dangling
-    ///     *ptr;
-    /// }
+    /// let ptr = std::ffi::CStr::from_bytes_with_nul(
+    ///     &"Hello world!"
+    ///         .to_uppercase()
+    ///         .chars()
+    ///         .map(|c| c.try_into().unwrap())
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:453]:
```suggestion
    ///         .bytes()
```

File: library/core/src/ffi/c_str.rs [hunk 2]
```diff
@@ -449,38 +445,59 @@ impl CStr {
     /// behavior when `ptr` is used inside the `unsafe` block:
     ///
     /// ```no_run
-    /// # #![allow(unused_must_use)]
-    /// # #![expect(dangling_pointers_from_temporaries)]
-    /// use std::ffi::CString;
-    ///
     /// // Do not do this:
-    /// let ptr = CString::new("Hello").expect("CString::new failed").as_ptr();
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:457]: Here, we called `as_ptr()` on CString, but it autoderefs to CStr when looking up where to call. The current example does in fact illustrate usage of `CStr::as_ptr`, and the issue was mistaken. The review from https://github.com/rust-lang/rust/pull/84000 seems to apply in full to this example.

File: library/core/src/ffi/c_str.rs [hunk 3]
```diff
@@ -384,13 +381,12 @@ impl CStr {
...
     ///
-    /// unsafe {
-    ///     let cstring = CString::new("hello").expect("CString::new failed");
-    ///     let cstr = CStr::from_bytes_with_nul_unchecked(cstring.to_bytes_with_nul());
-    ///     assert_eq!(cstr, &*cstring);
-    /// }
+    /// let bytes = b"Hello world!\0";
+    ///
+    /// let cstr = unsafe { CStr::from_bytes_with_nul_unchecked(bytes) };
+    /// assert_eq!(cstr.to_bytes_with_nul(), bytes);
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:389]: This is fine though.

File: library/core/src/ffi/c_str.rs [hunk 4]
```diff
@@ -55,18 +55,15 @@ use crate::{fmt, ops, slice, str};
...
-/// #   /* Extern functions are awkward in doc comments - fake it instead
-///     extern "C" { fn work_with(data: *const c_char); }
-/// #   */ unsafe extern "C" fn work_with(s: *const c_char) {}
-///
+///     unsafe extern "C" fn work_with(s: *const c_char) {}
 ///     unsafe { work_with(data.as_ptr()) }
 /// }
 ///
-/// let s = CString::new("data data data data").expect("CString::new failed");
+/// let s = c"Hello world!";
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:66]: as is this

File: library/core/src/ffi/c_str.rs [hunk 5]
```diff
@@ -449,38 +445,59 @@ impl CStr {
...
+    ///
+    /// assert_eq!(
+    ///     (0..)
+    ///         .map_while(|i| unsafe {
+    ///             let p = ptr.add(i);
+    ///             (*p != 0).then_some(*p as u8 as char)
+    ///         })
+    ///         .collect::<String>(),
+    ///     "Hello world!".to_uppercase()
+    /// );
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:499]: as #84000 said, the code pattern we want to warn against is specifically given and replacing the example with a more contrived one does not improve it. I don't think we want to accept this.

**Review by workingjubilee — CHANGES_REQUESTED** [review]
there are two minor changes that are fine but the gist of the issue was simply incorrect when it comes to most cases.

File: library/core/src/ffi/c_str.rs (hunk 5 above)
Comment (hkBst) [reply library/core/src/ffi/c_str.rs:499]: `CString::new("Hello").expect("CString::new failed")` is also contrived, since there is no point in doing that with a literal string when you can just use c"Hello", IIANM, but perhaps this tries too hard to avoid using CString...

File: library/core/src/ffi/c_str.rs (hunk 1 above)
Comment (hkBst) [reply library/core/src/ffi/c_str.rs:453]: I was worried this would break for non-ASCII chars...

File: library/core/src/ffi/c_str.rs (hunk 5 above)
Comment (hkBst) [reply library/core/src/ffi/c_str.rs:499]: How about something like this:
```rust
use std::ffi::{CStr, CString};

fn main() {
    // creates a dangling pointer to a CString temporary!
    let ptr = CString::new("Hi!".to_uppercase()).unwrap().as_ptr();

    // fails, showing ptr is now garbage
    assert_eq!(unsafe { CStr::from_ptr(ptr) }, c"HI!");
}
```

File: library/core/src/ffi/c_str.rs (hunk 4 above)
Comment (hkBst) [reply library/core/src/ffi/c_str.rs:66]: Since you're here, do you have any idea about "/* Extern functions are awkward in doc comments - fake it instead"?

File: library/core/src/ffi/c_str.rs (hunk 5 above)
Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: sometimes it won't actually show garbage depending on the optimization level

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: Yes, that's true. And since this is UB anything might happen really. Current proposal says this:
```rust
    /// let ptr = CString::new("Hi!".to_uppercase()).unwrap().as_ptr();
    /// // temporary CString is dropped here...
    ///
    /// // because of UB, anything might happen...,
    /// // but most likely this fails, showing ptr is now garbage,
    /// assert_eq!(unsafe { CStr::from_ptr(ptr) }, c"HI!");
```
but I can add a note about "mostly depending on optimizations" or some such...

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: Mmh. Most of our asserts are actually tested, so I'd prefer we avoid including any `assert!` usage at all for any case where the code is `no_run`. And yes, I'm aware this policy may not be enforced across all of our documentation.

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: The assert is there for if the reader wants to try this code, but I'm open to suggestions. I think there is some real value in being able to see the effects of UB for yourself in such a controlled manner. It goes a long way towards demystifying it and may help people to remember about it: "Oh wait, isn't this similar to that code that causes garbage...".

Another option would be to negate the assert and remove the no_run, but I don't think we really want to run code with UB. I've seen somewhere that it can produce garbage ;P.

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: Including negative examples at all is dicey, because humans are bad at negative reasoning. People will blindly copy code that has UB in it and use it anyways, without checking whether it is run and tested.

I am trying to explain to you that `assert!` is used elsewhere to **document guaranteed results**. Your idea of how it should be used here doesn't necessarily matter. It contradicts the intuition that most of the rest of our documentation is designed to build.

Here we are introducing a special case into an example that requires negative reasoning to understand, in a way that largely contradicts how our documentation works. It thus makes every other example harder to read, because now we have to check whether or not the assert was "really meant".

You can describe yourself as open to suggestions, but I have twice tried to explain why this change should not be done in milder terms, and now I am doing it a third time.

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: When I said "this policy may not be enforced across all our documentation", I meant that it **IS** enforced across the **majority** of the std API documentation, and that finding a counterexample is not a reason to introduce another counterexample.

File: library/core/src/ffi/c_str.rs (hunk 1 above)
Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: A CStr is a byte vector which does not contain `0x00` except for the terminator, it has no notion of "characters", despite whatever the C Standard might try to tell you.

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: I definitely should have used `bytes` here, but it seems I was distracted by worrying about non-ASCII chars. Definitely a mistake on my part. Thanks for your keen attention.

File: library/core/src/ffi/c_str.rs (hunk 5 above)
Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: > You can describe yourself as open to suggestions, but I have twice tried to explain why this change should not be done in milder terms, and now I am doing it a third time.

And I've changed the PR quite significantly based on your feedback. And I'm willing to change it further (although I'm not sure I should, since I seem to have annoyed you)...

Also, I am not trying to argue for an exception, nor have I pointed to a counterexample. I haven't mentioned any policy, and I'm not trying to use any rules or exceptions against you. All I've been doing is trying to argue my changes on their merits.

I'm happy to remove the assert all-together since you've now made it clear that it is unacceptable. You haven't quite convinced me, but I do think that you have good reasons, and you may well be right.

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: I've reviewed hundreds of PRs, and dozens where the primary way we documented a guarantee, new or old, is to add a set of asserts. The best way to "argue... on the merits", for me, would be to go look up the entirety of my review history. Doing that would be a rather lot of work.

But most of all I would rather things not feel like an argument where it doesn't feel like they need to, because I feel like things _do_ actually _need_ to become an argument way too often already. I'm certainly not a stranger to them, but an argument is still an enormously costly event for everyone involved. And most of all, you have to understand, that a reviewer will only feel obliged to participate in arguments as long as they feel they are useful, because the moment they don't, they have a simple way to resolve the argument:

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: Of course, clicking the "Close pull request" button is a fairly far step for many reviewers. A lot would rather simply leave you there, languishing in their queue forever. It's not because they enjoy you twisting in the wind, but it can take a lot of energy to give you the decency of a "No", especially if they feel they have to provide a reason for it and want to, say, try to avoid hurting anyone's feelings unnecessarily?

File: library/core/src/ffi/c_str.rs (hunk 4 above)
Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs:66]: It's just a comment about how linking functions gets weird in rustdoc tests.

File: library/core/src/ffi/c_str.rs (hunk 5 above)
Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: ...But as you might have guessed, I come from a different school of thought, as it were. I think letting people languish isn't great, but I recognize the energy it costs. Nonetheless, I try to actively pursue resolutions. I do often prefer finding them empathetically, but certainly not because I cannot get hard-headed and heedless.

Rather, I find framing things in terms of questions about what we want to often provide a more useful discussion. While simply presenting information is more efficient than a question-and-response format, argumentation is a lot _less_ efficient than a question-and-response format. A lot of energy wasted in presenting conflicting views, and inevitably engaging with misunderstandings, or trying to defend against possible misunderstandings by "heading them off at the pass", when we could simply ask questions.

But I'm still not sure of what question would be best to ask. Certain questions can wind up stirring conflict anyways. I think I was sort of hoping you'd ask at some point what changes would be desirable? It's awkward for me to just ask that question and answer it on my own, after all.

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: > I think I was sort of hoping you'd ask at some point what changes would be desirable? It's awkward for me to just ask that question and answer it on my own, after all.

I guess I was not asking exactly that, because I thought I had a pretty good idea of what was desirable here, although I did try to recognize flaws "perhaps this tries too hard to avoid using CString..." and ask for clarification both based on a suggestion "How about something like this: ..." and open-ended "I'm open to suggestions". While not exactly the same, I'm not quite sure why you did not feel that this provided you the same opening.

> But most of all I would rather things not feel like an argument where it doesn't feel like they need to, because I feel like things _do_ actually _need_ to become an argument way too often already. I'm certainly not a stranger to them, but an argument is still an enormously costly event for everyone involved.

I completely agree. I'd much rather have a discussion than an argument, which is what I thought we were having (a discussion), until it seemed like you thought you were in an argument. I'm really not sure what happened there, and I'd really like to know if you care to explain. But I'm also happy to wipe the slate; to forgive and forget. Anything to get back to a productive discussion, because the cost of an argument isn't worth it.

> Of course, clicking the "Close pull request" button is a fairly far step for many reviewers. A lot would rather simply leave you there, languishing in their queue forever. It's not because they enjoy you twisting in the wind, but it can take a lot of energy to give you the decency of a "No", especially if they feel they have to provide a reason for it and want to, say, try to avoid hurting anyone's feelings unnecessarily?

I'm certainly aware that it can be difficult to say "no" while avoiding hurt feelings, and that this can complicate the job of reviewing PRs (to say the least). I certainly have some other open PRs where it is difficult to find the path of progress, although in all cases so far, I've found that I've been able to make improvements and learn something, even if the "no" seemed wrong at first.

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: So my current thinking is that instead of an `assert` a `dbg` or `println` would have the same benefit, without the downside of being wrong. Please let me know what you think, even if I'm on the wrong track entirely.

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: Yes, that would be fine, actually.

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: Perplexing on both sides :D, but I'm happy we're making progress again.

I've pushed a new version without assert that would fail, instead now using dbg (since CStr doesn't impl Display anyway). I've also beefed up the explanation/warning of UB. I hope you like it, but if you still think the original is better, that's fine too.

File: library/core/src/ffi/c_str.rs [hunk 6]
```diff
@@ -449,38 +445,38 @@ impl CStr {
...
-    /// // Do not do this:
-    /// let ptr = CString::new("Hello").expect("CString::new failed").as_ptr();
-    /// unsafe {
-    ///     // `ptr` is dangling
-    ///     *ptr;
-    /// }
-    /// ```
+    /// // this program contains undefined behavior (UB);
+    /// // nothing about its behavior is guaranteed, although,
+    /// // it will likely resemble the code as written
```
Comment (workingjubilee) [inline library/core/src/ffi/c_str.rs:453]: This is the only part I still have issue with: the main problem with UB is that people misunderstand this detail. The compiler is given large latitude in terms of what it decides a program means when undefined behavior is involved, so it's more of a "even though"... especially "even if you get a certain described result in one example, you can't rely on this consistently operating a certain way when combined with any other code".

A somewhat infamous miscompilation result that can happen is that by reaching UB, LLVM may notice and delete code, including the parts that would initiate a transfer of control... so the result is fall-through to whatever machine code was ordered next in the binary!

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs:453]: So I suppose I should ask, what did you have in mind with this phrasing change?

Comment (hkBst) [reply library/core/src/ffi/c_str.rs:453]: Rereading my old version it did not seem to make it clear enough that the UB could affect the whole program, instead of just the line that tries to print the dangling CStr. That's why I moved the comment about UB making it do anything from the printing line to the top. Together with:
```rust
    /// // most likely the program behaved as expected so far
    /// // and this just shows `ptr` is now garbage
    /// dbg!(unsafe { CStr::from_ptr(ptr) });
```
it is now clearer that the whole program may be affected.

So it looks like we are on the same page again (namely people misunderstanding the possible impact of UB, and I was one of them when I wrote the previous text), but from your question I must conclude that the writing is not as clear as I had hoped. Any ideas for how to make it better?

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs:453]: Note that this is linted on right now:
```
warning: a dangling pointer will be produced because the temporary `CString` will be dropped
 --> src/main.rs:5:55
  |
5 | let ptr = CString::new("Hi!".to_uppercase()).unwrap().as_ptr();
  |           ------------------------------------------- ^^^^^^ this pointer will immediately be invalid
  |           |
  |           this `CString` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
  |
  = note: pointers do not have a lifetime; when calling `as_ptr` the `CString` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
  = help: you must make sure that the variable you bind the `CString` to lives at least as long as the pointer returned by the call to `as_ptr`
  = help: in particular, if this pointer is returned from the current function, binding the `CString` inside the function will not suffice
  = help: for more information, see <https://doc.rust-lang.org/reference/destructors.html>
  = note: `#[warn(dangling_pointers_from_temporaries)]` on by default
```

Maybe it is more helpful to reference the lint and explain it further?

I would say something like, "this entire program experiences UB, even if it behaved as expected up to this point. the following may show `"HI!"`, but usually it's junk instead".

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs:453]: in general and I would stress "even if" instead of "although"... it's always a "yes and" with UB. "yes it can actually perform correctly right now, at this point, and then infest your computer with malware later in the program's runtime, even though the UB is here".

Comment (hkBst) [reply library/core/src/ffi/c_str.rs]: Another attempt, with skull emojis... Apologies if this is too much...

Comment (workingjubilee) [reply library/core/src/ffi/c_str.rs]: Ah, I think just the text as-is good now, but I'm happy with the emojis if you like them. If someone finds them intolerable I'm sure we'll hear about it. :^)

**Review by workingjubilee — APPROVED** [review]
