### PR TITLE
Prevent String::retain from creating non-utf8 strings when abusing panic

### LINKED ISSUE #78498: String::retain allows safely creating invalid (non-utf8) strings when abusing panic
While `String::retain` executes it may temporarily leave the `String` in an inconsistent state, in particular it may contain invalid utf8. This is safe because it restores this invariant before returning, but the caller may skip this by panicing inside the closure and catching the unwind it outside. This allows to create `String`s that are not utf8, breaking the library invariant without using `unsafe`.

For example the following will panic at the final assertion, while I would expect it to never fail when `s` has type `String`:

```rust
let mut s = "0è0".to_string();
let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
    let mut count = 0;
    s.retain(|_| {
        count += 1;
        match count {
            1 => false,
            2 => true,
            _ => panic!(),
        }
    });
}));
assert!(std::str::from_utf8(s.as_bytes()).is_ok()); // This will fail
```

### PR DESCRIPTION
**Pull request by SkiFire13**
Fixes #78498

The idea is the same as `Vec::drain`, set the len to 0 so that nobody can observe the broken invariant if it escapes the function (in this case if `f` panics)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Won't this result in an empty string if you do `s.retain(|_| true)` now?

**Comment by m-ou-se** [comment]
Can you add a test that fails without this change, but passes with?

**Comment by jonas-schievink** [comment]
A test for `s.retain(|_| true)` would also be good, since I don't think the existing tests caught that bug

**Comment by SkiFire13** [comment]
> 
> 
> Can you add a test that fails without this change, but passes with?

Done. I added it in the same function of the other tests for `String::retain`. Is that ok or should I make it separate?

> 
> 
> A test for `s.retain(|_| true)` would also be good, since I don't think the existing tests caught that bug

There's already a test for that, which in fact initially failed in the CI. The reason I didn't catch it before opening the pull request is that I naively ran `./x.py test library/std` expecting it to also test `alloc`, but to be fair the rustc book is pretty misleading about that.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

File: library/alloc/src/string.rs [hunk 1]
```diff
@@ -1235,6 +1235,10 @@ impl String {
         let mut del_bytes = 0;
         let mut idx = 0;
 
+        unsafe {
+            self.vec.set_len(0);
+        }
+
         while idx < len {
             let ch = unsafe { self.get_unchecked(idx..len).chars().next().unwrap() };
```
Comment (eddyb) [inline library/alloc/src/string.rs:1243]: @RalfJung this was brought to my attention by @DJMcNab (the author of [`retain_more`](https://github.com/DJMcNab/retain_more)), as somewhat suspicious - it's calling `get_unchecked` on a `&str` obtained via auto-deref **which is zero-length now**. So we more or less expect this needs to go through a raw pointer directly or something similar.

Comment (SkiFire13) [reply library/alloc/src/string.rs:1243]: Good catch! I guess another alternative would be using a `DropGuard` for setting the length at the end of the loop. This way it's not necessary to set the length to 0 anymore because its `drop` implementation would called even in case of panic.

Comment (SkiFire13) [reply library/alloc/src/string.rs:1243]: I've opened #82554, let me know what you think about it
