### PR TITLE
Fix issue 30063 (reset codegen-units to 1 when necessary)

### LINKED ISSUE #30063: `make RUSTFLAGS="-Ccodegen-units=N"` always starts building at rsbegin.o
Needless to say, this is really inconvenient. This is happening because the make recipe calls rustc with `-o`, which is ignored when `codegen-units` is present. Make will then always recompile `rsbegin.o` and `rsend.o`, since they aren't actually created.

The build still works for me, since the files aren't actually needed on Linux, but would probably fail on `x86-windows-gnu` according to `rsbegin.rs` (I haven't actually checked).

`RUSTFLAGS` should probably be ignored for these targets. I have no idea how, since the makefiles look like something straight out of `/dev/random`.

### PR DESCRIPTION
**Pull request by pnkfelix**
When given `rustc -C codegen-units=4 --emit=obj`, reset units back to 1.

Fix #30063

Note: while this code is careful to handle the case of mutliple emit types (e.g. `--emit=asm,obj`) by reporting all the emit types that conflict with codegen units in its warnings, an invocation with multiple emit types _and_ `-o PATH` will continue to ignore the requested target path (with a warning), as it already does today, since the code that checks for that is further downstream.  (Multiple emit types without `-o PATH` will "work", though it will downgrade codegen-units to 1 just like all the other cases.)

r? @alexcrichton

### CODE REVIEW

File: src/librustc/session/config.rs [hunk 1]
```diff
@@ -933,7 +957,28 @@ pub fn build_session_options(matches: &getopts::Matches) -> Options {
         output_types.insert(OutputType::Exe, None);
     }
 
-    let cg = build_codegen_options(matches, color);
+    let mut cg = build_codegen_options(matches, color);
+
+    // Issue #30063: if user requests llvm-related output to one
+    // particular path, disable codegen-units.
+    if matches.opt_present("o") && cg.codegen_units != 1 {
```
Comment (alexcrichton) [inline src/librustc/session/config.rs]: I'd personally prefer to omit the check here for `-o` and always execute this logic if `codegen_units != 1`, that way we maintain equivalence between `rustc -o foo foo.rs` and `rustc foo.rs` (for all emit types)

File: src/test/run-make/issue-30063/Makefile [hunk 2]
```diff
@@ -0,0 +1,21 @@
+-include ../tools.mk
+
+all:
+	$(RUSTC) -C codegen-units=4 -o foo-output foo.rs
+	ls foo-output
```
Comment (alexcrichton) [inline src/test/run-make/issue-30063/Makefile]: I may not remember the current directory of run-make tests, but I think this puts files in the source tree? Adding `$(TMPDIR)` on front should fix it.

I also tend to use `rm` to ensure that the file was created so that way it also doesn't interfere with further tests, but this should work either way.

Comment (pnkfelix) [inline src/test/run-make/issue-30063/Makefile]: oh I think you're right, let me fix that

Comment (pnkfelix) [inline src/test/run-make/issue-30063/Makefile]: (make `tidy-binaries` would have caught it, too, I think)

File: src/librustc/session/config.rs (hunk 1 above)
Comment (pnkfelix) [inline src/librustc/session/config.rs]: Okay; I was trying to minimize the impact of the change over the current state of affairs, but I'm willing to concede that the principle of least surprise implies we should adopt the tack you suggest.

Comment (pnkfelix) [inline src/librustc/session/config.rs]: (okay commit 24bc2d2 should address this concern.)

File: src/test/run-make/issue-30063/Makefile [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+	$(RUSTC) -C codegen-units=4 --emit=llvm-bc --out-dir $(TMPDIR) foo.rs
+	rm $(TMPDIR)/foo.bc
+
+	rm -f $(TMPDIR)/foo.ll
+	$(RUSTC) -C codegen-units=4 --emit=llvm-ir --out-dir $(TMPDIR) foo.rs
+	rm $(TMPDIR)/foo.ll
+
+	rm -f $(TMPDIR)/foo
+	$(RUSTC) -C codegen-units=4 --emit=link --out-dir $(TMPDIR) foo.rs
+	rm $(TMPDIR)/foo
```
Comment (alexcrichton) [inline src/test/run-make/issue-30063/Makefile]: I think this may fail on Windows unfortunately due to the file being called `foo.exe` instead of `foo`. The `output-type-permutations` run-make test has some examples of how to deal with this I think.

**Comment by alexcrichton** [comment]
r=me, thanks @pnkfelix!

File: src/test/run-make/issue-30063/Makefile (hunk 3 above)
Comment (pnkfelix) [inline src/test/run-make/issue-30063/Makefile]: hmm, a similar problem may be embedded in my patch to that test in #30211

**Comment by pnkfelix** [comment]
Doh,I was running the Makefile by hand and forgot the driver will already add an `--out-dir`

**Comment by pnkfelix** [comment]
Hmm, it seems that  `test/run-make/sepcomp-cci-copies` is *requiring* that we support using `-C codegen-units=N` and `--emit=llvm-ir`.

**Comment by pnkfelix** [comment]
@alexcrichton given that at least one pre-existing test is relying on the ability to mix `-C codegen-units` and `--emit=llvm-thingie`, I'm tempted to go back to my previous more conservative approach of only erroring when one mixes `-o <file>` in the invocation as well.

What do you think?

**Comment by pnkfelix** [comment]
> Update: @alexcrichton gave me a quicker solution to the problem here: don't use --emit=llvm-ir for the test in question; use -C save-temps instead.

This didn't work, since `-C save-temps` does not emit disassembled LLVM .ll files (just  .bc  bitcode files)

----

I discussed the matter face-to-face with @alexcrichton and @huonw , and @alexcrichton agreed that my original approach (of only downshifting to code-units=1 if one also passed `-o`) is the better way to go here.
