### PR TITLE
Only include metadata for non-dynamic libraries in rustc-dev

### LINKED ISSUE #103538: rustc-dev component recently became a lot bigger
I need to download the rustc-dev component quite a lot for Miri development, and noticed that it recently became a lot bigger.

For b1ab3b738ac718da74cd4aa0bb7f362d0adbdf84, it was 125MB in size.
Now, at 85d089b41e2a0c0f07ab34f6c5a7c451389f25e6, it is 205MB in size.

Is that an expected regression? Is there a way to avoid this almost doubling of the size?

### PR DESCRIPTION
**Pull request by bjorn3**
The actual object code should be linked from librustc_driver.so, which is still included in rustc-dev. This saves on download time and disk usage.

Fixes https://github.com/rust-lang/rust/issues/103538

### CODE REVIEW

**Comment by bjorn3** [comment]
Works as intended. It cuts both download and disk size in half.

## Before

```
detecting the channel of the `37d7de337903a558dbeb1e82c844fe915ab8ff25` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/37d7de337903a558dbeb1e82c844fe915ab8ff25/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
67.75 MB / 67.75 MB [==================================================================================================================================================] 100.00 % 13.27 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/37d7de337903a558dbeb1e82c844fe915ab8ff25/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz>...
220.29 MB / 220.29 MB [================================================================================================================================================] 100.00 % 12.68 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/37d7de337903a558dbeb1e82c844fe915ab8ff25/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
29.74 MB / 29.74 MB [==================================================================================================================================================] 100.00 % 12.33 MB/s 
toolchain `37d7de337903a558dbeb1e82c844fe915ab8ff25` is successfully installed!
```

```
$ du -sh ~/.rustup/toolchains/37d7de337903a558dbeb1e82c844fe915ab8ff25/lib/rustlib/x86_64-unknown-linux-gnu/lib/
1.6G    /home/gh-bjorn3/.rustup/toolchains/37d7de337903a558dbeb1e82c844fe915ab8ff25/lib/rustlib/x86_64-unknown-linux-gnu/lib/
```

## After

```
detecting the channel of the `6d5b237d87d74959bd7608dfc370ef9feda36b2c` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/6d5b237d87d74959bd7608dfc370ef9feda36b2c/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
67.71 MB / 67.71 MB [==================================================================================================================================================] 100.00 % 11.51 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/6d5b237d87d74959bd7608dfc370ef9feda36b2c/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz>...
106.88 MB / 106.88 MB [=================================================================================================================================================] 100.00 % 6.31 MB/s 
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/6d5b237d87d74959bd7608dfc370ef9feda36b2c/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
29.73 MB / 29.73 MB [===================================================================================================================================================] 100.00 % 9.17 MB/s 
toolchain `6d5b237d87d74959bd7608dfc370ef9feda36b2c` is successfully installed!
```

```
$ du -sh ~/.rustup/toolchains/6d5b237d87d74959bd7608dfc370ef9feda36b2c/lib/rustlib/x86_64-unknown-linux-gnu/lib/
729M    /home/gh-bjorn3/.rustup/toolchains/6d5b237d87d74959bd7608dfc370ef9feda36b2c/lib/rustlib/x86_64-unknown-linux-gnu/lib/
```

File: compiler/rustc_metadata/src/dependency_format.rs [hunk 1]
```diff
@@ -224,7 +224,12 @@ fn calculate_type(tcx: TyCtxt<'_>, ty: CrateType) -> DependencyList {
                     Linkage::Static => "rlib",
                     _ => "dylib",
                 };
-                sess.emit_err(LibRequired { crate_name: tcx.crate_name(cnum), kind: kind });
+                let crate_name = tcx.crate_name(cnum);
+                if crate_name.as_str().starts_with("rustc_") {
```
Comment (jyn514) [inline compiler/rustc_metadata/src/dependency_format.rs:228]: Can we make this a more general check, `if crate_can_be_loaded_from_sysroot(crate_name)` or something like that? I understand that's pretty hard, fine to open a follow-up issue if you don't want to spend time on it.

File: compiler/rustc_metadata/src/errors.rs [hunk 2]
```diff
@@ -24,6 +24,14 @@ pub struct LibRequired<'a> {
     pub kind: &'a str,
 }
 
+#[derive(Diagnostic)]
+#[diag(metadata_rustc_lib_required)]
+#[help]
```
Comment (jyn514) [inline compiler/rustc_metadata/src/errors.rs:29]: @davidtwco why is this `#[help]` attribute required? Can we remove that requirement somehow? We already have `.help` in the .ftl file, I wouldn't expect both to be necessary.

File: src/bootstrap/compile.rs [hunk 3]
```diff
@@ -1411,6 +1413,7 @@ pub fn run_cargo(
     stamp: &Path,
     additional_target_deps: Vec<(PathBuf, DependencyType)>,
     is_check: bool,
+    rlib_only_metadata: bool,
```
Comment (jyn514) [inline src/bootstrap/compile.rs:1416]: This getting to be quite a lot of arguments. AFAICT `Cargo` is only used here and for `stream_cargo` - can we make `rlib_only_metadata` part of the `Cargo` builder instead of adding a new arg?

File: compiler/rustc_error_messages/locales/en-US/metadata.ftl [hunk 4]
```diff
@@ -4,6 +4,10 @@ metadata_rlib_required =
 metadata_lib_required =
     crate `{$crate_name}` required to be available in {$kind} format, but was not found in this form
 
+metadata_rustc_lib_required =
+    crate `{$crate_name}` required to be available in {$kind} format, but was not found in this form
```
Comment (jyn514) [inline compiler/rustc_error_messages/locales/en-US/metadata.ftl:8]: It was unclear to me at first why this suggested `rustc_driver` unconditionally - the error message seems like a better place for it than the comment in `src/test/run-make-fulldeps`.
```suggestion
    crate `{$crate_name}` required to be available in {$kind} format, but was not found in this form
    .note = only .rmeta files are distributed for `rustc_private` crates other than `rustc_driver`
```

File: src/bootstrap/compile.rs [hunk 5]
```diff
@@ -728,6 +729,7 @@ impl Step for Rustc {
             &librustc_stamp(builder, compiler, target),
             vec![],
             false,
+            true,
```
Comment (jyn514) [inline src/bootstrap/compile.rs:732]:
```suggestion
            true, // Only ship rustc_driver.so and .rmeta files, not all intermediate .rlib files.
```

File: src/bootstrap/compile.rs [hunk 6]
```diff
@@ -1444,12 +1447,13 @@ pub fn run_cargo(
...
             // Skip files like executables
-            if !(filename.ends_with(".rlib")
+            if !((!rlib_only_metadata && filename.ends_with(".rlib"))
                 || filename.ends_with(".lib")
                 || filename.ends_with(".a")
                 || is_debug_info(&filename)
                 || is_dylib(&filename)
-                || (is_check && filename.ends_with(".rmeta")))
+                || ((is_check || rlib_only_metadata) && filename.ends_with(".rmeta"))
+                || filename.contains("jemalloc_sys"))
```
Comment (jyn514) [inline src/bootstrap/compile.rs:1456]: Why is jemalloc special-cased?

File: src/bootstrap/compile.rs [hunk 7]
```diff
@@ -1444,12 +1447,13 @@ pub fn run_cargo(
         };
         for filename in filenames {
             // Skip files like executables
-            if !(filename.ends_with(".rlib")
+            if !((!rlib_only_metadata && filename.ends_with(".rlib"))
```
Comment (jyn514) [inline src/bootstrap/compile.rs:1450]: This is very hard for me to understand. Could you do something like `(rlib_only_metadata && filename.ends_with(".rlib")) || !( // ...` instead?

**Review by jyn514 — COMMENTED** [review]
Thanks :) LGTM with the comments addressed. Great idea!

File: src/bootstrap/compile.rs (hunk 6 above)
Comment (bjorn3) [reply src/bootstrap/compile.rs:1456]: It isn't linked into rustc_driver, but several tools still use it from the sysroot. By the way I think rustc_smir may also need to have an exception.

File: src/bootstrap/compile.rs (hunk 3 above)
Comment (bjorn3) [reply src/bootstrap/compile.rs:1416]: `Cargo` represents a specific cargo binary together with the global cargo and rust flags for the current stage. Maybe combining `is_check` and `rlib_only_metadata` into a `CargoBuildMode` enum would work?

File: src/bootstrap/compile.rs (hunk 7 above)
Comment (bjorn3) [reply src/bootstrap/compile.rs]: I split it into multiple if's and added comments. Is this less confusing?

Comment (jyn514) [reply src/bootstrap/compile.rs]: Looks a lot better, thank you!

File: compiler/rustc_metadata/src/dependency_format.rs (hunk 1 above)
Comment (jyn514) [reply compiler/rustc_metadata/src/dependency_format.rs:228]: I misunderstood, this error is specifically about having an .rmeta but not an .rlib, which isn't about *sysroot* crates, it's about specifically crates that are in `rustc_driver`. No need to change the error.

File: src/bootstrap/compile.rs (hunk 3 above)
Comment (jyn514) [reply src/bootstrap/compile.rs:1416]: hmm, ok. let's put this refactor off for later, it's not important for now.

**Comment by jyn514** [comment]
@bors r+

Thanks!

**Comment by bjorn3** [comment]
On Windows libc isn't used, causing a difference in the test output. Changed the test to ignore non-unix targets.

**Comment by bjorn3** [comment]
Rebased. Do you want me to squash?

**Comment by jyn514** [comment]
That would be great, thanks :)

**Comment by bjorn3** [comment]
Done. There is a CI failure that doesn't make any sense though.

**Comment by dtolnay** [comment]
For anyone landing here with an error like this:

```console
error: crate `rustc_ast_pretty` required to be available in rlib format, but was not found in this form
  |
  = help: try adding `extern crate rustc_driver;` at the top level of this crate
```

If you add `extern crate rustc_driver` and then get an error like this:

```console
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcJ6ZtcA/symbols.o" "target/debug/deps/foo-71b8be8abb28cf36.y793e40jtmbzz9q.rcgu.o" "-Wl,--as-needed" "-L" "target/debug/deps" "-L" ".rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-L" ".rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-lrustc_driver-eaaa85fc498d717c" "-L" ".rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-62c4894b82797b30" "-Wl,-Bstatic" ".rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-66b9c3ae5ff29c13.rlib" "-Wl,-Bdynamic" "-lLLVM-15-rust-1.68.0-nightly" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" ".rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lLLVM-15-rust-1.68.0-nightly: No such file or directory
          collect2: error: ld returned 1 exit status
```

then you need to do `rustup component add llvm-tools`.
