### PR TITLE
Unclosed html tag lint

### LINKED ISSUE #67799: Tracking issue for check_invalid_html_tags
This is a tracking issue for the rustdoc lint `check_invalid_html_tags`.
There is no feature gate for this lint, but it is currently nightly-only.

### `check_invalid_html_tags`

This lint warns about unclosed HTML tags and comments. See https://doc.rust-lang.org/nightly/rustdoc/lints.html#invalid_html_tags for more information.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implementation (https://github.com/rust-lang/rust/pull/77119)
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Implementation history

- [x] Initial implementation (https://github.com/rust-lang/rust/pull/77119)
- [x] Expanded to HTML comments (https://github.com/rust-lang/rust/pull/77753)
- [x] Stabilization PR (https://github.com/rust-lang/rust/pull/101720)

<details><summary>Original issue</summary>

Rustdoc currently allows HTML in markdown, which is fine. The problem is that it doesn't sanitize the HTML at all, which means you can do wacky stuff like:

```rust
/// This is basically a Vec<Script>
pub enum ScriptExtension { /* ... */ }


impl ScriptExtension {
   /// docs
   pub fn some_func() {}
}
```

in which the `Vec<Script>` parses as an opening script tag, and the rest of the docs just ... disappear

image

This isn't great, and it's kind of surprising. Perhaps we should sanitize these, or at least warn when it happens? This may not be easy or cheap, though.

cc @GuillaumeGomez @kinnison 

</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #67799.

I think @ollie27 will be interested (@Manishearth too since they opened the issue ;) ).

r? @jyn514

### CODE REVIEW

File: src/librustdoc/passes/html_tags.rs [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+
+fn extract_tag(cx: &DocContext<'_>, tags: &mut Vec<String>, text: &str, hir_id: HirId, sp: Span) {
+    let mut iter = text.chars().peekable();
+
+    while let Some(c) = iter.next() {
+        if c == '<' {
+            let mut tag_name = String::new();
+            let mut is_closing = false;
+            while let Some(&c) = iter.peek() {
+                if c == '/' && tag_name.is_empty() {
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:65]:
```suggestion
                // </script>
                if c == '/' && tag_name.is_empty() {
```

File: src/librustdoc/passes/html_tags.rs [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+                    is_closing = true;
+                } else if c.is_ascii_alphanumeric() && !c.is_ascii_uppercase() {
+                    tag_name.push(c);
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:68]:
```suggestion
                } else if c.is_ascii_alphanumeric() && !c.is_ascii_uppercase() {
                    // <script>
                    tag_name.push(c);
```

File: src/librustdoc/passes/html_tags.rs [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+    coll.fold_crate(krate)
+}
+
+const ALLOWED_UNCLOSED: &[&str] = &[
+    "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param",
+    "source", "track", "wbr",
+];
+
+fn drop_tag(cx: &DocContext<'_>, tags: &mut Vec<String>, tag_name: String, hir_id: HirId, sp: Span) {
+    // In case the tag wasn't in the queue, I guess it's not really an issue...
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:39]: Shouldn't we warn on closing tags that were never opened, too? That was the cause of some issues in https://github.com/tokio-rs/tracing/pull/881.

File: src/librustdoc/passes/html_tags.rs [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+    if let Some(pos) = tags.iter().position(|t| *t == tag_name) {
+        for _ in pos + 1..tags.len() {
+            if ALLOWED_UNCLOSED.iter().find(|&at| at == &tags[pos + 1]).is_some() {
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:42]: I don't understand what this is doing. `pos` is where the opening tag is , `pos+1..len()` is all following tags ... what is `pos+1`? I think this will give false negatives on
```html
<div>
  <hr>
```
Please add that as a test case.

File: src/librustdoc/passes/html_tags.rs [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+                continue;
+            }
+            cx.tcx.struct_span_lint_hir(
+                lint::builtin::UNCLOSED_HTML_TAGS,
+                hir_id,
+                sp,
+                |lint| lint.build(&format!("Unclosed HTML tag `{}`", tags[pos])).emit(),
+            );
+            tags.remove(pos + 1);
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:51]: Why is this looking at `pos+1` instead of `pos`?

File: src/librustdoc/passes/html_tags.rs [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+
+const ALLOWED_UNCLOSED: &[&str] = &[
+    "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param",
+    "source", "track", "wbr",
+];
+
+fn drop_tag(cx: &DocContext<'_>, tags: &mut Vec<String>, tag_name: String, hir_id: HirId, sp: Span) {
+    // In case the tag wasn't in the queue, I guess it's not really an issue...
+    if let Some(pos) = tags.iter().position(|t| *t == tag_name) {
+        for _ in pos + 1..tags.len() {
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:41]: Why does this go through every following tag if it only looks at `pos` and `pos + 1`? I think this will give duplicate warnings for
```html
<h1>
  <h2>
    <h3>
</h1>
```
Please add that as a test case.

File: src/librustdoc/passes/html_tags.rs [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+            if ALLOWED_UNCLOSED.iter().find(|&at| at == &tags[pos + 1]).is_some() {
+                continue;
+            }
+            cx.tcx.struct_span_lint_hir(
+                lint::builtin::UNCLOSED_HTML_TAGS,
+                hir_id,
+                sp,
+                |lint| lint.build(&format!("Unclosed HTML tag `{}`", tags[pos])).emit(),
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:49]:
```suggestion
                |lint| lint.build(&format!("unclosed HTML tag `{}`", tags[pos])).emit(),
```

**Review by jyn514 — CHANGES_REQUESTED** [review]
I might have gone overboard on the comments 😆

File: compiler/rustc_session/src/lint/builtin.rs [hunk 8]
```diff
@@ -1870,6 +1870,17 @@ declare_lint! {
     "detects code samples in docs of private items not documented by rustdoc"
 }
 
+declare_lint! {
+    /// The `private_doc_tests` lint detects code samples in docs of private
+    /// items not documented by `rustdoc`. This is a `rustdoc` only lint, see
+    /// the documentation in the [rustdoc book].
+    ///
+    /// [rustdoc book]: ../../../rustdoc/lints.html#private_doc_tests
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_session/src/lint/builtin.rs:1878]: Oh damn, I forgot all the doc part. :o

File: src/test/rustdoc-ui/unclosed-tags.rs [hunk 9]
```diff
@@ -0,0 +1,11 @@
+#![deny(unclosed_html_tags)]
+
+/// <script>
+//~^ ERROR Unclosed HTML tag `unknown`
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/unclosed-tags.rs:4]: No, currently it always points to the doc comment, not the location. It's not great in that regard...

File: src/test/rustdoc-ui/unclosed-tags.rs [hunk 10]
```diff
@@ -0,0 +1,11 @@
...
+//~^^ ERROR Unclosed HTML tag `script`
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/unclosed-tags.rs:5]: Like said above, it's currently only showing the doc comment location, not the faulty content location.

File: src/librustdoc/passes/html_tags.rs [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+
+    coll.fold_crate(krate)
+}
+
+const ALLOWED_UNCLOSED: &[&str] = &[
+    "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param",
+    "source", "track", "wbr",
+];
+
+fn drop_tag(cx: &DocContext<'_>, tags: &mut Vec<String>, tag_name: String, hir_id: HirId, sp: Span) {
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:38]: I always write the code this way: "includes"/"declarations" then I use them in the code at the bottom.

File: src/librustdoc/passes/html_tags.rs [hunk 12]
```diff
@@ -0,0 +1,122 @@
...
+                sp,
+                |lint| lint.build(&format!("Unclosed HTML tag `{}`", tags[pos])).emit(),
+            );
+            tags.remove(pos + 1);
+        }
+        tags.remove(pos);
+    }
+}
+
+fn extract_tag(cx: &DocContext<'_>, tags: &mut Vec<String>, text: &str, hir_id: HirId, sp: Span) {
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:57]: I guess it could. But then it would need to instead of having just `Html(&str)`, something more complicated like `HtmlOpenTag(&str)` and `HtmlCloseTag(&str)`. But that seems doable. I can add it there if that seems fine to you.

File: src/librustdoc/passes/html_tags.rs [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+                    is_closing = true;
+                } else if c.is_ascii_alphanumeric() && !c.is_ascii_uppercase() {
+                    tag_name.push(c);
+                } else {
+                    break;
+                }
+                iter.next();
+            }
+            if tag_name.is_empty() {
+                // Not an HTML tag presumably...
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:75]: Like I said to you, currently, if there is an HTML tag, it returns the whole line as being HTML, meaning you definitely can have `<` in the line even though it's not an HTML tag.

File: src/librustdoc/passes/html_tags.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:68]: No, it can also be `</script>`.

File: src/librustdoc/passes/html_tags.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:39]: Then we need to update the lint name to reflect it. What about `invalid_html_tag`?

File: src/librustdoc/passes/html_tags.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:42]: I use the vec as a queue, therefore, all items coming after `pos` are included into it. In this case, I go top to bottom to the included tags.

File: src/librustdoc/passes/html_tags.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:51]: Explanation in the comment above. ;)

I should maybe add a comment explaining what's going on if it's troublesome though!

File: src/librustdoc/passes/html_tags.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:41]: Absolutely, it's the goal! I'll add a test for them as well then.

File: src/librustdoc/passes/html_tags.rs (hunk 7 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:49]: :+1:

File: src/test/rustdoc-ui/unclosed-tags.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/test/rustdoc-ui/unclosed-tags.rs:4]: Right, I'm asking for it to point to the location instead. Not sure how hard that is ... is there some other part of the code that already does this?

File: src/librustdoc/passes/html_tags.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:38]: Well I can't say I agree with the style ;) but that's fine, no need to change it.

File: src/librustdoc/passes/html_tags.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:57]: That would be helpful, I think. They already have the information and it would be less code to go wrong.

File: src/librustdoc/passes/html_tags.rs (hunk 2 above)
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:68]: Oh I see this runs for _every_ character in the loop, so it runs for both `<script>` and `</script>`. Got it.

File: src/librustdoc/passes/html_tags.rs (hunk 3 above)
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:39]: `invalid_html_tag` sounds good to me!

File: src/librustdoc/passes/html_tags.rs (hunk 6 above)
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:41]: Oh I see, that's intentional. I don't think I like that behavior - it should only warn once per _incorrect_ tag, not once per tag along the way.

File: src/librustdoc/passes/html_tags.rs (hunk 4 above)
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:42]: Right, but why is `pos+1` special? You look at `ALLOWED_UNCLOSED` only for that tag.

File: src/librustdoc/passes/html_tags.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:41]: If the tags are after `pos`, it means they're unclosed and so we should warn.

File: src/librustdoc/passes/html_tags.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:47]: No, I look it at another place as well. ;)

File: src/librustdoc/passes/html_tags.rs [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+        }
+    }
+}
+
+impl<'a, 'tcx> DocFolder for UnclosedHtmlTagsLinter<'a, 'tcx> {
+    fn fold_item(&mut self, item: Item) -> Option<Item> {
+        let hir_id = match self.cx.as_local_hir_id(item.def_id) {
+            Some(hir_id) => hir_id,
+            None => {
+                // If non-local, no need to check anything.
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:99]: Then it's a local item no?

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by Manishearth** [comment]
We should absolutely not be doing our own HTML parsing here, HTML parsing is extremely complicated even in cases like this one where HTML is rare.

If we can get this info from pulldown that's fine, but a hand rolled bespoke HTML parser is all but guaranteed to have problems.

**Comment by Manishearth** [comment]
A different approach: perhaps we can look for _very specific_ strings, e.g. `<script>`, `<audio>`, `<video>`, i.e. cases where the tag will slurp up and hide all proceeding content, and make sure that the number of such instances is equally matched with the number of closing tags

**Comment by Manishearth** [comment]
Actually thinking about this more I guess it's fine if we parse a very limited subset of HTML. @jyn514 what is your take on this? I'd rather not do anything brittle here.

**Comment by jyn514** [comment]
> Actually thinking about this more I guess it's fine if we parse a very limited subset of HTML. @jyn514 what is your take on this? I'd rather not do anything brittle here.

I think we absolutely shouldn't stabilize the lint with a bespoke HTML parser. I think it's ok to land this as `allow` by default on nightly, though. 

Before merging we should definitely reach out to pulldown-cmark about how hard it would be to add this info in the API.

File: compiler/rustc_session/src/lint/builtin.rs [hunk 15]
```diff
@@ -1870,6 +1870,16 @@ declare_lint! {
     "detects code samples in docs of private items not documented by rustdoc"
 }
 
+declare_lint! {
+    /// The `invalid_html_tags` lint detects invalid HTML tags. This is a
+    /// `rustdoc` only lint, see the documentation in the [rustdoc book].
```
Comment (camelid) [inline compiler/rustc_session/src/lint/builtin.rs:1875]: I think there should be a hyphen here:

```suggestion
    /// `rustdoc`-only lint, see the documentation in the [rustdoc book].
```

Comment (camelid) [reply compiler/rustc_session/src/lint/builtin.rs:1875]: Also, maybe skip the inline code style since you don't use it for "... in the rustdoc book"?

**Review by camelid — COMMENTED** [review]
Just a nit regarding the lint docs :)

File: compiler/rustc_session/src/lint/builtin.rs (hunk 15 above)
Comment (GuillaumeGomez) [reply compiler/rustc_session/src/lint/builtin.rs:1875]: I used the same style as the other rustdoc lints, so I'll keep it.

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/passes/html_tags.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:107]: No, this is the reason that failed links on intra-doc re-exports don't warn: https://github.com/rust-lang/rust/issues/77200

We had a conversation about it this morning after you made the original comment: https://discordapp.com/channels/442252698964721669/459149231702278154/759114849640251433 and concluded that something is going wrong in clean for pub re-exports, it marks them as `ImplItem` instead of `UseItem` like it should.

File: src/doc/rustdoc/src/lints.md [hunk 16]
```diff
@@ -210,3 +210,38 @@ warning: unknown attribute `should-panic`. Did you mean `should_panic`?
 
 In the example above, the correct form is `should_panic`. This helps detect
 typo mistakes for some common attributes.
+
+## invalid_html_tags
+
+This lint is **allowed by default** and is **nigtly-only**. It detects unclosed
```
Comment (jyn514) [inline src/doc/rustdoc/src/lints.md:216]:
```suggestion
This lint is **allowed by default** and is **nightly-only**. It detects unclosed
```

File: src/librustdoc/passes/html_tags.rs [hunk 17]
```diff
@@ -0,0 +1,144 @@
...
+    "source", "track", "wbr",
+];
+
+fn drop_tag(
+    tags: &mut Vec<(String, Range<usize>)>,
+    tag_name: String,
+    range: Range<usize>,
+    f: &impl Fn(&str, &Range<usize>),
+) {
+    if let Some(pos) = tags.iter().position(|(t, _)| *t == tag_name) {
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:48]: I thought of another thing: what happens if you have nested tags? I think this will mistakenly warn on the following code:

```rust
/// <div>
///   <p> //~ WARNING <p> not closed
///      <div></div> //~ WARNING <div> not closed
///   </p> //~ WARNING <p> has no opening tag
/// </div>
```
Try using a reverse iterator instead so it uses the most recently opened tag:
```suggestion
    if let Some(pos) = tags.iter().rev().position(|(t, _)| *t == tag_name) {
```
Can you also add my code snippet as a test?

File: src/librustdoc/passes/html_tags.rs [hunk 18]
```diff
@@ -0,0 +1,144 @@
...
+        for _ in pos + 1..tags.len() {
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:49]: nit: I think this would be more clear as `while tags.len() >= pos {` and using `tags.pop()` instead of `tags.remove(pos + 1)`.

File: src/librustdoc/passes/html_tags.rs [hunk 19]
```diff
@@ -0,0 +1,144 @@
...
+            if ALLOWED_UNCLOSED.iter().find(|&at| at == &tags[pos + 1].0).is_some() {
+                continue;
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:51]: I think because of the way you have this set up it will skip any nested tags if it sees an unclosed tag before. Consider:
```html
<div>
   <br/> <p>
</div>
```
It will see `pos+1` is an unclosed tag, go to the next iteration, and then every following iteration hit this code again because the tag wasn't removed. Try removing it on the continue:
```suggestion
            if ALLOWED_UNCLOSED.iter().find(|&at| at == &tags[pos + 1].0).is_some() {
                tags.remove(pos+1);
                continue;
```
Can you add that as a test case?

File: src/test/rustdoc-ui/invalid-html-tags.stderr [hunk 20]
```diff
@@ -0,0 +1,38 @@
+error: unclosed HTML tag `unknown`
+  --> $DIR/invalid-html-tags.rs:7:5
+   |
+LL | /// <unknown>
+   |     ^^^^^^^^
```
Comment (jyn514) [inline src/test/rustdoc-ui/invalid-html-tags.stderr:5]: Hmm, do you know why this doesn't also point to the closing `>` of the tag? Like this:
```suggestion
LL | /// <unknown>
   |     ^^^^^^^^^
```

Comment (jyn514) [reply src/test/rustdoc-ui/invalid-html-tags.stderr:5]: I think pulldown might be passing you the wrong span.

File: src/librustdoc/passes/html_tags.rs (hunk 17 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:48]: Great catch! I completely forgot the `rev` part...

File: src/librustdoc/passes/html_tags.rs (hunk 18 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:49]: Indeed. :+1:

File: src/librustdoc/passes/html_tags.rs (hunk 19 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:51]: It's fixed by the `pop` you suggested just before. But I'll add a test for this!

File: src/test/rustdoc-ui/invalid-html-tags.stderr (hunk 20 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc-ui/invalid-html-tags.stderr:5]: It might be a whitespace or anything else in case you `<unknown style="1">`. So I preferred to only point to the start of the tag in case attributes were also present.

**Comment by GuillaumeGomez** [comment]
> No, this is the reason that failed links on intra-doc re-exports don't warn: #77200

@jyn514 The issue is that the reexport item itself should be here, which isn't the case currently for some reason. In my opinion, this check is valid.

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by jyn514 — COMMENTED** [review]
> The issue is that the reexport item itself should be here, which isn't the case currently for some reason. In my opinion, this check is valid.

Ok, I opened https://github.com/rust-lang/rust/issues/77230 for this. No need to block this PR on it.

File: src/librustdoc/passes/html_tags.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (jyn514) [reply src/librustdoc/passes/html_tags.rs:109]: Opened https://github.com/rust-lang/rust/issues/77230 for this.

File: compiler/rustc_session/src/lint/builtin.rs [hunk 21]
```diff
@@ -1870,6 +1870,16 @@ declare_lint! {
...
+    ///
+    /// [rustdoc book]: ../../../rustdoc/lints.html#invalid_html_tags
+    pub INVALID_HTML_TAGS,
+    Allow,
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_session/src/lint/builtin.rs:1879]: Sure!

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by jyn514** [comment]
The last thing is adding a test for tags inside `<script>`, which I think isn't handled currently: https://github.com/rust-lang/rust/pull/77119#discussion_r493853647

Other than that you just need to run `x.py fmt`.
```
 -                        let mut r = Range { start: range.start + start_pos, end: range.start + pos };
+                        let mut r =
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
+                            Range { start: range.start + start_pos, end: range.start + pos };
```

**Comment by GuillaumeGomez** [comment]
No more warning in case the tag is nested inside a `<script>`.

File: src/librustdoc/passes/html_tags.rs [hunk 22]
```diff
@@ -48,8 +48,10 @@ fn drop_tag(
     if let Some(pos) = tags.iter().rev().position(|(t, _)| *t == tag_name) {
         // Because this is from a `rev` iterator, the position is reversed as well!
         let pos = tags.len() - 1 - pos;
+        // If the tag is nested inside a "<script>", not warning should be emitted.
+        let should_not_warn = tags.iter().take(pos + 1).any(|(at, _)| at == "script");
```
Comment (jyn514) [inline src/librustdoc/passes/html_tags.rs:52]: Sorry - I was using "script" as a shorthand for "any tag that introduces a syntax that's not HTML". So that includes at least `style`. @Manishearth might have more suggestions.
```suggestion
        // If the tag is nested inside a "<script>", not warning should be emitted.
        let should_not_warn = tags.iter().take(pos + 1).any(|(at, _)| at == "script" || at == "style");
```

File: src/test/rustdoc-ui/invalid-html-tags.rs [hunk 23]
```diff
@@ -39,3 +39,14 @@ pub fn b() {}
 ///   <h3>
 //~^ ERROR unclosed HTML tag `h3`
 pub fn c() {}
+
+// Unclosed tags shouldn't warn if they are nested inside a script elem.
+/// <script>
+///   <h3><div>
+/// </script>
```
Comment (jyn514) [inline src/test/rustdoc-ui/invalid-html-tags.rs:46]:
```suggestion
/// <script>
///   <h3><div>
/// </script>
/// <style>
///   <h3><div>
/// </style>
```

**Comment by GuillaumeGomez** [comment]
I applied the same treatment to `<script>` then!

**Comment by jyn514** [comment]
r=me with CI passing, this is definitely good enough to be on nightly

**Comment by ollie27** [comment]
@bors r-

This ICEs on:

```rust
//! <p>💩<p>
```

```
thread 'rustc' panicked at 'byte index 4 is not a char boundary; it is inside '💩' (bytes 3..7) of `<p>💩<p>`', src\librustdoc\passes\mod.rs:352:25
```

<hr>

> Fixes #67799.

While this is work towards fixing #67799 it certainly can't close the issue. The lint doesn't even trigger for the example given in #67799 because the tag in `Vec<Script>` starts with a capital letter. HTML tags aren't case sensitive which is something this PR doesn't seem to take into account.

The lint is also not triggering for incomplete tags like:

```rust
//! <script
```

or

```rust
//! <!--
```

which causes the same kinds of problems as in #67799.

File: src/librustdoc/passes/html_tags.rs [hunk 24]
```diff
@@ -0,0 +1,155 @@
...
+fn drop_tag(
+    tags: &mut Vec<(String, Range<usize>)>,
+    tag_name: String,
+    range: Range<usize>,
+    f: &impl Fn(&str, &Range<usize>),
+) {
+    if let Some(pos) = tags.iter().rev().position(|(t, _)| *t == tag_name) {
+        // Because this is from a `rev` iterator, the position is reversed as well!
+        let pos = tags.len() - 1 - pos;
+        // If the tag is nested inside a "<script>", not warning should be emitted.
```
Comment (camelid) [inline src/librustdoc/passes/html_tags.rs:51]: nit: this comment is out-of-date

```suggestion
        // If the tag is nested inside a "<script>" or "<style>" tag, no warning should be emitted.
```

**Comment by GuillaumeGomez** [comment]
@ollie27 Handling HTML comments would be a bit tricky. Also, I'm not sure if `pulldown-cmark` handles them... I think it's best to discuss about it inside another PR. I fixed the two other issues.

**Comment by GuillaumeGomez** [comment]
ping @ollie27

File: src/librustdoc/passes/html_tags.rs [hunk 25]
```diff
@@ -0,0 +1,181 @@
...
+    }
+}
+
+fn extract_tag(
+    tags: &mut Vec<(String, Range<usize>)>,
+    text: &str,
+    range: Range<usize>,
+    f: &impl Fn(&str, &Range<usize>),
+) {
+    let mut iter = text.chars().enumerate().peekable();
```
Comment (ollie27) [inline src/librustdoc/passes/html_tags.rs:86]:
```suggestion
    let mut iter = text.char_indices().peekable();
```

This is what will actually fix the ICE with none ASCII characters. The two `for _ in 0..c.len_utf8() {` loops below aren't correct because they're confusing bytes and characters.

**Review by ollie27 — CHANGES_REQUESTED** [review]
> Handling HTML comments would be a bit tricky (actually, just requires a different loop to handle it). Also, I'm not sure if `pulldown-cmark` handles them...

Of course it does: https://github.com/raphlinus/pulldown-cmark/blob/d0119f59c139d810fb354a910b0d7ce4e47e8cbb/src/firstpass.rs#L1230. `pulldown-cmark` also handles other types of tags which will need to handled somehow.

> I think it's best to discuss about it inside another PR.

It's fine for this to be a partial implementation but "Fixes #67799." needs to be removed from then PR comment because #67799 cannot be closed until we cover all of the ways the issue can be triggered.

Another case not currently detected by this PR is:

```rust
//! <script></script
```

File: src/librustdoc/passes/html_tags.rs [hunk 26]
```diff
@@ -77,21 +85,29 @@ fn extract_tag(
...
+                };
+                prev_pos = pos;
                 // Checking if this is a closing tag (like `</a>` for `<a>`).
-                if *c == '/' && tag_name.is_empty() {
+                if c == '/' && tag_name.is_empty() {
                     is_closing = true;
-                } else if c.is_ascii_alphanumeric() && !c.is_ascii_uppercase() {
-                    tag_name.push(*c);
+                } else if c.is_ascii_alphanumeric() {
+                    tag_name.push(c);
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:105]: No because then, we lose the original name. This would problematic.

File: src/librustdoc/passes/html_tags.rs [hunk 27]
```diff
@@ -45,14 +45,22 @@ fn drop_tag(
     range: Range<usize>,
     f: &impl Fn(&str, &Range<usize>),
 ) {
-    if let Some(pos) = tags.iter().rev().position(|(t, _)| *t == tag_name) {
+    let tag_name_low = tag_name.to_lowercase();
+    if let Some(pos) = tags.iter().rev().position(|(t, _)| t.to_lowercase() == tag_name_low) {
         // Because this is from a `rev` iterator, the position is reversed as well!
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:50]: :+1:

File: src/librustdoc/passes/html_tags.rs (hunk 25 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:86]: Much simpler indeed, thanks!

**Comment by GuillaumeGomez** [comment]
@ollie27 Thanks a lot for the great suggestions! I also enforced the fact that a closing HTML tag needed to end with `>`. Once this PR is merged, I'll add support for HTML comments.

File: src/librustdoc/passes/html_tags.rs [hunk 28]
```diff
@@ -0,0 +1,190 @@
...
+                                }
+                                let mut found = false;
+                                for (new_pos, c) in text[pos..].char_indices() {
+                                    if !c.is_whitespace() {
+                                        if c == '>' {
+                                            r.end = range.start + new_pos + 1;
+                                            found = true;
+                                        }
+                                        break;
+                                    }
```
Comment (camelid) [inline src/librustdoc/passes/html_tags.rs:128]: I think this would be clearer as an if-else:

```suggestion
                                    if c == '>' {
                                        r.end = range.start + new_pos + 1;
                                        found = true;
                                        break;
                                    } else if !c.is_whitespace() {
                                        break;
                                    }
```

File: src/librustdoc/passes/html_tags.rs [hunk 29]
```diff
@@ -0,0 +1,190 @@
...
+                            // refer to it fully.
+                            r.end += 1;
+                        }
+                        if is_closing {
+                            // In case we have "</div >" or even "</div         >".
+                            if c != '>' {
+                                if !c.is_whitespace() {
+                                    // It seems like it's not a valid HTML tag.
+                                    break;
+                                }
```
Comment (camelid) [inline src/librustdoc/passes/html_tags.rs:119]: I think this would also be clearer as an if-else. It may introduce an extra comparison, but hopefully MIR would be able to figure that out. (Plus it would probably be like one or two instructions.)

**Comment by Manishearth** [comment]
> It's fine for this to be a partial implementation but "Fixes #67799." needs to be removed from then PR comment because #67799 cannot be closed until we cover all of the ways the issue can be triggered.

I kinda disagree, I actually do not think we should try to catch _every_ way the issue can be triggered, only cases that are likely to occur, like `Vec<Script>`, where the HTML was completely unintentional. . E.g. `<script></script`, while broken, is still _intended to be HTML_, at which point we don't relaly need to care. I'm strongly against adding really precise heuristics for catching broken HTML, we'd need a markdown-compatible HTML parser with recovery and that would be a mess for very  marginal gain.

**Comment by GuillaumeGomez** [comment]
So should I mark this PR as fix or not?

File: src/librustdoc/passes/html_tags.rs (hunk 28 above)
Comment (GuillaumeGomez) [reply src/librustdoc/passes/html_tags.rs:128]: I'm not sure to understand in which it is more readable. :-/

In my code, if it's not a whitespace, then you enter the block and you check along the way if the character is `>`. It's not about optimization, I just find it more logical this way.

**Comment by jyn514** [comment]
Let's remove it for now so we can get the initial implementation in, we can always close the issue later. r=me with that done.

**Comment by jyn514** [comment]
@bors r+

We can make fixes in follow up PRs if necessary.

File: src/librustdoc/passes/html_tags.rs (hunk 26 above)
[the remark this answers is not in the document]
Comment (ollie27) [reply src/librustdoc/passes/html_tags.rs:103]: I don't see what problems that could cause but if the original case needs to be preserved in `tags` then you should use [`eq_ignore_ascii_case`](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.eq_ignore_ascii_case) to compare strings. `.to_lowercase()` allocates a new `String` which is very inefficient.

**Comment by ollie27** [comment]
> I'm strongly against adding really precise heuristics for catching broken HTML, we'd need a markdown-compatible HTML parser with recovery and that would be a mess for very marginal gain.

Hmm, I agree that we don't want this code to get too complicated. So yeah, maybe just catching some common cases might be the best we should do. Ideally we could actually fix close the unclosed tags so the rendering of the rest of the page isn't completely broken but that might be getting way too complicated.

I do think #67799 should to be left open at least until this lint is stabilized and warn by default though. At the very least we need a tracking issue for doing that and reusing #67799 seems like the easiest choice.

**Comment by GuillaumeGomez** [comment]
> I do think #67799 should to be left open at least until this lint is stabilized and warn by default though. At the very least we need a tracking issue for doing that and reusing #67799 seems like the easiest choice.

Agreed. I'll let @Manishearth update the issue then.

**Comment by Manishearth** [comment]
> I do think #67799 should to be left open at least until this lint is stabilized and warn by default though. At the very least we need a tracking issue for doing that and reusing #67799 seems like the easiest choice.

Yeah that seems fine. When this lands someone should do that.

**Comment by GuillaumeGomez** [comment]
I can't see why it failed. Maybe it's a CI issue? cc @pietroalbini

**Comment by camelid** [comment]
Yeah, I always get confused when it fails at "mark the job as a failure". Where are the logs of the actual failure?

**Comment by pietroalbini** [comment]
The weirdness was probably https://www.githubstatus.com/incidents/t34640ccrmfs.

**Comment by GuillaumeGomez** [comment]
Oh okay. Well, let's try again then!

@bors: retry
