### PR TITLE
fix Drop items getting leaked in Filter::next_chunk

### LINKED ISSUE #126872: `<core::iter::Filter as Iterator>::next_chunk` virtually `core::mem::forget`s all elements that fail the predicate
The `Iterator::next_chunk` (see #98326) implementation for `core::iter::Filter` does not gracefully drop the elements failing the predicate in the original iterator; instead it forgets them.
As an example, you can try this code:

```rust
#![feature(iter_next_chunk)]
struct LoudlyDropped(usize);

impl Drop for LoudlyDropped {
    fn drop(&mut self) {
        println!("No. {} getting dropped here!!!", self.0);
    }
}

fn main() {
    let v = (0..10).map(LoudlyDropped).collect::<Vec<_>>();
    let _= v.into_iter().filter(|_| false).next_chunk::<1>();
}
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=55424189789c70f6a013ec341df3718b))

I expected this program to generate the same message as the program without the last line in `main`, that is:

```rust
#![feature(iter_next_chunk)]
struct LoudlyDropped(usize);

impl Drop for LoudlyDropped {
    fn drop(&mut self) {
        println!("No. {} getting dropped here!!!", self.0);
    }
}

fn main() {
    let _ = (0..10).map(LoudlyDropped).collect::<Vec<_>>();
}
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1ea9c0e0aaab7c5c1278cc60ff2519a2))

However, instead, the first program doesn't print anything.

The origin of this behavior is trivial to find: in the lines 90--98 of the file for`mod core::iter::adapters::filter` of the current master (aabbf84), we have the following code ([Github permalink](https://github.com/rust-lang/rust/blob/aabbf84b45a5e7b868c33e959d7e5cc985097d19/library/core/src/iter/adapters/filter.rs#L90-L98)), which is part of the implementation of `next_chunk`:

```rust
        let result = self.iter.try_for_each(|element| {
            let idx = guard.initialized;
            guard.initialized = idx + (self.predicate)(&element) as usize;


            // SAFETY: Loop conditions ensure the index is in bounds.
            unsafe { guard.array.get_unchecked_mut(idx) }.write(element);


            if guard.initialized < N { ControlFlow::Continue(()) } else { ControlFlow::Break(()) }
        });
```

This `core::ptr::write`s each element that doesn't comply the element into the place out of the range of `guard.initialized`.
The elements here, if not overwritten by this process, will be left undropped by the `Drop` implementation of `[T; N]::IntoIter`.

### Meta

Playground version:
```
Build using the Nightly version: 1.81.0-nightly
(2024-06-22 3cb521a4344f0b556b81)
```

### PR DESCRIPTION
**Pull request by the8472**
The optimization only makes sense for non-drop elements anyway. Use the default implementation for items that are Drop instead.

It also simplifies the implementation.

fixes #126872
tracking issue #98326

### CODE REVIEW

File: library/core/src/iter/adapters/filter.rs [hunk 1]
```diff
@@ -64,52 +99,15 @@ where
...
-                // SAFETY: The loop above is only explicitly broken when the array has been fully initialized
-                Ok(unsafe { MaybeUninit::array_assume_init(array) })
-            }
-            ControlFlow::Continue(()) => {
-                let initialized = guard.initialized;
-                // SAFETY: The range is in bounds since the loop breaks when reaching N elements.
-                Err(unsafe { array::IntoIter::new_unchecked(array, 0..initialized) })
-            }
-        }
+        fun(self)
```
Comment (danielhenrymantilla) [inline library/core/src/iter/adapters/filter.rs:110]: Do we know whether the codegen for:

```rs
if const { crate::mem::needs_drop::<I::Item>() } {
    array::iter_next_chunk::<I::Item, N>(fun)
} else {
    Self::next_chunk_dropless::<N>(fun)
}
```

is worse/better than that involving a `dyn`amic `fn` _pointer_?

Both approaches rely on some basic optimization pass optimizing out the `fn`-pointer (devirtualizing) or the branch, but it feels like the latter would put less strain on compilers, and in a way, on maintainers of this code (no need to have two exact `fn`s).

File: library/core/src/iter/adapters/filter.rs [hunk 2]
```diff
@@ -27,6 +27,41 @@ impl<I, P> Filter<I, P> {
...
+    ) -> Result<[I::Item; N], array::IntoIter<I::Item, N>> {
+        let mut array: [MaybeUninit<I::Item>; N] = MaybeUninit::uninit_array();
+        let mut initialized = 0;
+
+        let result = self.iter.try_for_each(|element| {
+            let idx = initialized;
+            initialized = idx + (self.predicate)(&element) as usize;
+
+            // SAFETY: Loop conditions ensure the index is in bounds.
+            unsafe { array.get_unchecked_mut(idx) }.write(element);
```
Comment (danielhenrymantilla) [inline library/core/src/iter/adapters/filter.rs:47]: I know this is unrelated to this PR, and is rather about the original code with the leak issue, but I think that when we have a non-leaking, non-unnecessarily-bit-copying-discarded-items, all in all simpler, alternative available:

```suggestion
            if (self.predicate)(&element) {
                unsafe { array.get_unchecked_mut(initialized) }.write(element);
                initialized += 1;
            }
```

then, if we still want to stick to these now needed leak-avoiding hoops and `idx/initialized` split (I assume the objective then is to produce branchless code since in practice it may pan out better?), at the very least it ought to warrant some kind of comment saying so (_e.g._, pointing at benchmarks or codegen comparisons).

  - cc @rossmacarthur, original author of this logic

File: library/core/src/iter/adapters/filter.rs (hunk 1 above)
Comment (the8472) [reply library/core/src/iter/adapters/filter.rs:110]: The const approach means the unused callee won't have to be codegen'd even in debug.

**Review by cuviper — APPROVED** [review]
The change looks good, but please add a regression test too.
