### PR TITLE
fix(bootstrap): rename exclude flag to skip 🐛

### LINKED ISSUE #111894: bootstrap: make `--exclude` consistent with `--skip` in libtest
Right now, there are two ways to ignore tests:
1. Pass `x test --exclude tests/ui/weird-exprs.rs` to bootstrap
2. Pass `x test --test-args --skip=tests/ui/weird-exprs.rs` to compiletest

It's weird that these use different arguments. `--skip` is public-facing, so we should rename `--exclude` to `--skip` in bootstrap.

I don't have a strong opinion on whether to keep `--exclude` around as an alias for `--skip`, but `--skip` should be the one we document.

Note that `--exclude` is *slightly* different from `--skip` because it can also applies to whole Steps, not just tests, and doesn't support substring matching. But I don't think it's different *enough* to be worth having a different name.

### PR DESCRIPTION
**Pull request by meysam81**
fixes #111894

### CODE REVIEW

**Comment by meysam81** [comment]
@clubby789 

Would you take a look at this PR when you get some time?

Regards.

**Comment by clubby789** [comment]
Apologies for not getting round to this yet. When you're rebasing to fix the merge conflicts, would you mind squashing your commits into one?

**Comment by meysam81** [comment]
I wonder @clubby789, why contributors would need to squash their commits in a pull request when GitHub already gives you the option to do that upon merging (as shown in the screenshot below).
image

**Comment by saethlin** [comment]
Merging using the GitHub interface means that if two PRs pass the tests individually but together break, you would be allowed to merge both and break the master branch instead of getting a test failure. There is an option to "require pull requests be up to date before merging" in GitHub but it is _brutal_ to use even on repos much less active than this one.

So Rust uses bors: https://graydon2.dreamwidth.org/1597.html

**Comment by clubby789** [comment]
I think it would be a good idea to alias `exclude` to `skip` to not break existing workflows, but otherwise lgtm

**Comment by clubby789** [comment]
I mean for downstream users, i.e. developers/distros

**Comment by joshtriplett** [comment]
AFAICT this got mislabeled as T-style (and other things) because it appeared to touch a bunch of files that it no longer touches.

**Comment by meysam81** [comment]
@clubby789 @joshtriplett @saethlin @jyn514 
Would you kindly review [and possibly approve] this PR?
It is touching many files and it keeps getting conflicts as other PRs get merged.

File: src/bootstrap/doc.rs [hunk 1]
```diff
@@ -570,7 +570,7 @@ fn doc_std(
     if builder.no_std(target) == Some(true) {
         panic!(
             "building std documentation for no_std target {target} is not supported\n\
-             Set `docs = false` in the config to disable documentation, or pass `--exclude doc::library`."
+             Set `docs = false` in the config to disable documentation, or pass `--skip library`."
```
Comment (klensy) [inline src/bootstrap/doc.rs:573]: This changed more that exclude/skip replace?

Comment (meysam81) [reply src/bootstrap/doc.rs:573]: @klensy 
Sorry, but I don't get it. Would you explain more, please?

File: src/bootstrap/config.rs [hunk 2]
```diff
@@ -1112,7 +1112,8 @@ impl Config {
 
         // Set flags.
         config.paths = std::mem::take(&mut flags.paths);
-        config.exclude = flags.exclude;
+        config.skip = flags.skip;
+        config.skip = flags.exclude;
```
Comment (klensy) [inline src/bootstrap/config.rs:1116]: This kinda suspicious: silently overwriting one flag with other one.

File: src/bootstrap/doc.rs (hunk 1 above)
Comment (klensy) [reply src/bootstrap/doc.rs:573]: before: `--exclude doc::library`,
after: `--skip library`

Comment (klensy) [reply src/bootstrap/doc.rs:573]: Probably. Is this suggestion still valid after change?

File: src/bootstrap/config.rs (hunk 2 above)
Comment (klensy) [reply src/bootstrap/config.rs:1116]: This is true if there some warn about this behavior, otherwise this is bug, IMHO.

Comment (lnicola) [reply src/bootstrap/config.rs:1116]: Wouldn't it make sense to merge (`extend`) the two instead of overwriting `flags.skip`?

Comment (meysam81) [reply src/bootstrap/config.rs:1116]: absolutely, extend is the right way to do it

Comment (lnicola) [reply src/bootstrap/config.rs:1116]: Do you mind if I stop bors, then?

Comment (klensy) [reply src/bootstrap/config.rs]: It's safer to r- r+, as approved commit differs from last one? bors kind glitchy around that things.

File: src/bootstrap/doc.rs (hunk 1 above)
Comment (meysam81) [reply src/bootstrap/doc.rs:573]: Running this on master:

```bash
x --stage=0 doc --exclude library
```

Output:
```
...truncated
Skipping Set({doc::library}) because it is excluded
...truncated
```


running it on my change:

```bash
x --stage=0 doc --exclude library
```


```
...truncated
Skipping Set({doc::library}) because it is excluded
...truncated
```

Comment (klensy) [reply src/bootstrap/doc.rs:573]: Hm, ok.

File: src/bootstrap/flags.rs [hunk 3]
```diff
@@ -68,7 +68,10 @@ pub struct Flags {
 
     #[arg(global(true), long, value_name = "PATH")]
     /// build paths to exclude
-    pub exclude: Vec<PathBuf>,
+    pub exclude: Vec<PathBuf>, // keeping for client backward compatibility
```
Comment (lnicola) [inline src/bootstrap/flags.rs:71]: Maybe change the comment to "build paths to skip, prefer `--skip` instead` because having both "build paths to exclude" and "build paths to skip" is a bit confusing.

Ideally, we'd hide it from the help message. I see https://docs.rs/clap/latest/clap/struct.Arg.html#method.hide, but I can't seem to make it work for `arg`.

File: src/etc/completions/x.py.fish [hunk 4]
```diff
@@ -4,6 +4,7 @@ complete -c x.py -n "__fish_use_subcommand" -l build -d 'build target of the sta
 complete -c x.py -n "__fish_use_subcommand" -l host -d 'host targets to build' -r -f
 complete -c x.py -n "__fish_use_subcommand" -l target -d 'target targets to build' -r -f
 complete -c x.py -n "__fish_use_subcommand" -l exclude -d 'build paths to exclude' -r -F
+complete -c x.py -n "__fish_use_subcommand" -l skip -d 'build paths to skip' -r -F
```
Comment (lnicola) [inline src/etc/completions/x.py.fish:7]: We could drop `exclude`, but it might annoy some people.

File: src/bootstrap/flags.rs (hunk 3 above)
Comment (lnicola) [reply src/bootstrap/flags.rs:71]: Oh, it's `#[arg(hide(true))]`.

**Review by lnicola — APPROVED** [review]

File: src/etc/completions/x.py.fish (hunk 4 above)
Comment (lnicola) [reply src/etc/completions/x.py.fish:7]: Okay, I guess the completions are generated automatically so they'll get updated anyway.

**Review by lnicola — APPROVED** [review]

**Review by klensy — APPROVED** [review]

**Comment by clubby789** [comment]
Thanks to everyone for taking a second look ❤️ 
@bors r+

**Comment by meysam81** [comment]
The failing test is passing locally, as seen in the snippet below. What should I do to reproduce/rerun this? @clubby789 

```bash
$ time x test tests/run-pass-valgrind/cleanup-auto-borrow-obj.rs

...truncated

Testing stage1 compiletest suite=run-pass-valgrind mode=run-pass-valgrind (x86_64-unknown-linux-gnu)                   
                                                                                                                       
running 1 tests                                                                                                        
.                                                                                                                      
                                                                                                                       
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 16 filtered out; finished in 69.17ms                       
                                                                                                                       
Build completed successfully in 0:01:52                                                                                
                                                                                                                       
real    1m52.257s                                                                                                      
user    7m37.223s                                                                                                      
sys     0m54.704s                                                                                                      
```

**Comment by klensy** [comment]
This is spurious error. no need to fix anything, `failed with Connection reset by peer (os error 104)', src/tools/remote-test-client/src/main.rs:310:9`

**Comment by meysam81** [comment]
Alright then, would someone pls approve this before another mishappen occurs pls :pray:

**Comment by lnicola** [comment]
@meysam81 I have bors rights, but I don't normally merge PRs here, so let's wait for **clubby789**.

**Comment by meysam81** [comment]
@clubby789 
any update on this?
