### PR TITLE
std: Stabilize the `env` module

### LINKED ISSUE #22122: std::env::VarError should capture name
I have been refactoring command-line program code to use the patterns implied by [Improved Error Handling in Rust](http://lucumr.pocoo.org/2014/11/6/error-handling-in-rust/).  Errors are *bubbled up* to `main()` using the `std::error::Error` and `std::error::FromError` traits.  This allows most user messaging to occur in a central location (especially panic-level failures), simplifying testing and internationalization.

One issue I have encountered has to do with missing environment variables.  `std::env::VarError` does not capture the the environment variable name (which std::env calls a *key*); therefore, the messages from `Error::description()` and `Display::fmt()` do not tell the user which environment variable is missing.  To work around this issue, I have wrapped `VarError` in another struct.  It would be much simpler if `VarError` captured the environment variable name and included it in the messages.

I realize this is likely to require heap allocation to save a copy of the name.  In most (sane) cases, environment variables are accessed once during program initialization and the value stored for future use.  Therefore, I believe the benefit of knowing which environment variable is missing outweighs the heap allocation cost.

### PR DESCRIPTION
**Pull request by alexcrichton**
Now that the `std::env` module has had some time to bake this commit marks most
of its APIs as `#[stable]`. Some notable APIs that are **not** stable (and still
use the same `env` feature gate) are:
- `{set,get}_exit_status` - there are still questions about whether this is the
  right interface for setting/getting the exit status of a process.
- `page_size` - this may change location in the future or perhaps name as well.

This also effectively closes #22122 as the variants of `VarError` are
`#[stable]` now. (this is done intentionally)

### CODE REVIEW

File: src/libstd/env.rs [hunk 1]
```diff
@@ -412,12 +439,14 @@ static EXIT_STATUS: AtomicIsize = ATOMIC_ISIZE_INIT;
...
 ///
 /// Note that this is not synchronized against modifications of other threads.
+#[unstable(feature = "env", reason = "managing the exit status may change")]
 pub fn set_exit_status(code: i32) {
     EXIT_STATUS.store(code as isize, Ordering::SeqCst)
 }
 
 /// Fetches the process's current exit code. This defaults to 0 and can change
 /// by calling `set_exit_status`.
+#[unstable(feature = "env", reason = "managing the exit status may change")]
```
Comment (aturon) [inline src/libstd/env.rs]: Hm, you can have both `stable` and `unstable` items for the same feature name?

Comment (alexcrichton) [inline src/libstd/env.rs]: Hm right that does sound like a bad idea, I will move these to a new feature name.

**Comment by aturon** [comment]
@bors: r+ 974011f

another one bites the dust

**Comment by aturon** [comment]
@alexcrichton Hm, want to push a trivial new commit to get a new SHA, since homu seems busted here?
