### PR TITLE
Suggest dereferencing on assignment to mutable borrow

### LINKED ISSUE #33570: Compiler should hint to user to deref when doing reference assignment
https://is.gd/wm0S9G

``` rust
fn change_opt(opt: &mut Option<String>){
    opt = None
}
```

```
<anon>:2:11: 2:15 error: mismatched types:
 expected `&mut core::option::Option<collections::string::String>`,
    found `core::option::Option<_>`
(expected &-ptr,
    found enum `core::option::Option`) [E0308]
<anon>:2     opt = None
                   ^~~~
<anon>:2:11: 2:15 help: see the detailed explanation for E0308
error: aborting due to previous error
```

It'd be great if this had a hint:

```
 Did you mean `*opt = None`
```

Someone on IRC just ran into this.

### PR DESCRIPTION
**Pull request by estebank**
Fix #33570

### CODE REVIEW

**Comment by estebank** [comment]
cc @Centril on wording

**Comment by mark-i-m** [comment]
Won't this suggestion trigger even if the type of the pointee and the assignee are different?

```rust
let mut x = 0;

(&mut x) = None; // suggestion to consider dereferencing does not work
```

**Comment by estebank** [comment]
I'll add a negative check to the test to avoid regressions, but by the time we hit this code we have already checked that the two types can be unified and that the left is a mutable borrow.

File: src/librustc_typeck/check/demand.rs [hunk 1]
```diff
@@ -397,6 +398,29 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                         } else {
                             String::new()
                         };
+                        if let Some(hir::Node::Expr(hir::Expr {
```
Comment (Centril) [inline src/librustc_typeck/check/demand.rs]: With this addition the function is ~200+ LOC -- can we avoid making it bigger? =P

**Review by Centril — CHANGES_REQUESTED** [review]
I'm a big, big fan of having a diagnostic for this as I make this mistake on a regular basis.

File: src/librustc_typeck/check/demand.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/demand.rs]: I'm focusing on slimming/splitting `Parser` now. I'll move to other parts of the compiler once in done with that.

Comment (Centril) [reply src/librustc_typeck/check/demand.rs]: Cool, just don't forget about it... =)

**Comment by estebank** [comment]
For the case in @mark-i-m's comment, the output is:

```
error[E0308]: mismatched types
 --> file2.rs:4:12
  |
4 | (&mut x) = None;
  |            ^^^^ expected mutable reference, found enum `std::option::Option`
  |
  = note: expected type `&mut {integer}`
             found type `std::option::Option<_>`

error[E0070]: invalid left-hand side expression
 --> file2.rs:4:1
  |
4 | (&mut x) = None;
  | ^^^^^^^^^^^^^^^ left-hand of expression not valid
```
