### PR TITLE
Make positional argument error in format! clearer

### LINKED ISSUE #44954: Off-by-one in println! diagnostic
This program:

```rust
fn main() {
    let name = "foo";
    
    println!("{} {}", name);
}
```

Gives this error:

```text
error: invalid reference to argument `1` (there is 1 argument)
```

Both things having 1 here is confusing, it'd be nicer if we didn't compare a zero-indexed and a one-indexed number.

Additionally, a note could make this easier to understand overall too.

### PR DESCRIPTION
**Pull request by tommyip**
r? @estebank 

Fixes #44954

### CODE REVIEW

File: src/test/compile-fail/ifmt-bad-arg.rs [hunk 1]
```diff
@@ -11,36 +11,39 @@
...
-    //~^ ERROR invalid reference to argument `2` (there are 2 arguments)
-
-    format!("{0} {1}");
-    //~^ ERROR invalid reference to argument `0` (no arguments given)
-    //~^^ ERROR invalid reference to argument `1` (no arguments given)
+    //~^ ERROR: 3 positional arguments in format string, but there are only 2 arguments
+
+    format!("{} {value} {} {}", 1, value=2);
+    //~^ ERROR: invalid reference to positional argument 2 (there are only 2 arguments)
+    format!("{name} {value} {} {} {} {} {} {}", 0, name=1, value=2);
```
Comment (estebank) [inline src/test/compile-fail/ifmt-bad-arg.rs]: Could you add a case with multiple named arguments that are not used, mixed with positional arguments? I'm curious about the new output.

File: src/libsyntax_ext/format.rs [hunk 2]
```diff
@@ -251,23 +253,49 @@ impl<'a, 'b> Context<'a, 'b> {
...
+    /// Handle invalid references to positional arguments. Output different
+    /// errors for the case where all arguments are positional and for when
+    /// there are named arguments in the format string.
+    fn report_invalid_references(&self) {
+        let mut refs: Vec<String> = self.invalid_refs
+                                        .iter()
+                                        .map(|r| r.to_string())
+                                        .collect();
+
+        let msg = if self.names.is_empty() {
```
Comment (estebank) [inline src/libsyntax_ext/format.rs]: Add another check for `self.args.iter().filter_map(|arg| /* Some(arg) if numbered positional argument */).count() == 0` here, so that if there are arguments like `{1}`, it goes to the else branch and it is explicit about the arguments that are wrong.

**Review by estebank — CHANGES_REQUESTED** [review]

File: src/libsyntax_ext/format.rs [hunk 3]
```diff
@@ -251,23 +253,49 @@ impl<'a, 'b> Context<'a, 'b> {
...
+                             tail=refs.pop().unwrap(),
+                             head=refs.join(", "))
+            };
+
+            format!("invalid reference to positional {} ({})",
+                    arg_list,
+                    self.describe_num_args())
+        };
+
+        self.ecx.span_err(self.fmtsp, &msg[..]);
```
Comment (estebank) [inline src/libsyntax_ext/format.rs]: We should probably add a `note` making it explicit that positional arguments are `0` indexed, probably only when it is needed (I think only for the `else` branch).

File: src/libsyntax_ext/format.rs (hunk 2 above)
Comment (tommyip) [reply src/libsyntax_ext/format.rs]: Seems like the position is already resolved in the parser, should we change it so we still have that information here?

Comment (estebank) [reply src/libsyntax_ext/format.rs]: If you prefer, that's also a reasonable change.

**Comment by tommyip** [comment]
@estebank this should work now.

> Could you add a case with multiple named arguments that are not used, mixed with positional arguments? I'm curious about the new output.

Yeah the output is incorrect, fixed that in the latest commit (test case: https://github.com/tommyip/rust/blob/1be9cc76daa1a5047fadb0bb0e826b47a63d8f1b/src/test/compile-fail/ifmt-bad-arg.rs#L37)
