### PR TITLE
make unaligned_references future-incompat lint warn-by-default

### LINKED ISSUE #46043: Tracking issue for `safe_packed_borrows` compatibility lint
## What is this warning about

Fields of structs with the `#[repr(packed)]` attribute might be unaligned. Even if a field has a valid offset (e.g. 0) within the struct, the struct itself might be unaligned.

On the other hand, safe references (`&T` and `&mut T`) must always have valid alignment (even when they are just created) - not only will *dereferencing* these references cause segfaults on architectures such as Sparc, but the compiler is allowed to optimize based on that assumption (e.g. in a future version of rustc, it might use the "free" alignment bits to represent enum discriminants), so even just *creating* an unaligned reference is Undefined Behavior and might cause the program to behave in unexpected ways.

Therefore, borrowing a field in the interior of a packed structure with alignment other than 1 is unsafe - if the reference is not *known* to be aligned, the borrow must be done to an unsafe pointer.

Note that borrowing a field with alignment 1 is always safe.

For example, consider the common `struct Unaligned`:
```Rust
#[repr(packed)]
pub struct Unaligned<T>(pub T);
```

That struct can be placed inside a bigger struct at an unaligned offset:
```Rust
pub struct Foo {
    start: u8,
    data: Unaligned<u32>,
}
```

In that case, a borrow of a field of the struct would be Undefined Behavior (UB), and therefore is made unsafe:
```Rust
let x = Foo { start: 0, data: Unaligned(1) };
let y = &x.data.0; // UB, also future-compatibility warning
println!("{}", x.data.0); // this borrows `x.data.0`, so UB + future-compat warning
use(y);
```

This used to be left unchecked by the compiler - issue #27060.

## How to fix this warning/error

The most common ways to fix this warnings are:
1. remove the `#[repr(packed)]` attribute if it is not actually needed. A few crates had unnecessary `#[repr(packed)]` annotations - for example, [tendril].
2. copy the fields to a local first. When accessing a field of a packed struct directly without using a borrow, the compiler will make sure the access is done correctly even when the field is unaligned. The then-aligned local can then be freely used. For example:
    ```Rust
    let x = Foo { start: 0, data: Unaligned(1) };
    let temp = x.data.0;
    println!("{}", temp); // works
    // or, to the same effect, using an `{x}` block:
    println!("{}", {x.data.0}); // works
    use(y);
    ````

In some cases, it might be necessary to borrow the fields as raw pointers and use `read_unaligned`/`write_unaligned` to access them, but I haven't encountered such a case.

### Derives

One annoying case where this problem can appear is if a packed struct has builtin derives, e.g.
```Rust
#[derive(PartialEq, ...)]
#[repr(packed)]
pub struct Unaligned<T>(pub T);
```

Which essentially expands to this:
```Rust
impl<T: PartialEq> PartialEq for Unaligned<T> {
    fn eq(&self, other: &Self) -> bool {
        PartialEq::eq(&self.0, &other.0) // this is UB and unsafe
    }
}
```

If your struct already derives `Copy` and has no generics, the compiler will generate code that copies the fields to locals and will therefore work. Otherwise, you'll have to write the `derive` implementations manually.

For example, you might want to add a `T: Copy` bound and copy things out:

```Rust
#[repr(packed)]
pub struct Unaligned<T: Copy>(pub T);

impl<T: Copy + PartialEq> PartialEq for Unaligned<T> {
    fn eq(&self, other: &Self) -> bool {
        ({self.0}) == ({other.0}) // this copies fields to temps, and works
    }
}
```

[tendril]: https://github.com/servo/tendril/issues/29

### PR DESCRIPTION
**Pull request by RalfJung**
and also remove the safe_packed_borrows lint that it replaces.

`std::ptr::addr_of!` has hit beta now and will hit stable in a month, so I propose we start fixing https://github.com/rust-lang/rust/issues/27060 for real: creating a reference to a field of a packed struct needs to eventually become a hard error; this PR makes it a warn-by-default future-incompat lint. (The lint already existed, this just raises its default level.) At the same time I removed the corresponding code from unsafety checking; really there's no reason an `unsafe` block should make any difference here.

For references to packed fields outside `unsafe` blocks, this means `unaligned_refereces` replaces the previous `safe_packed_borrows` warning with a link to https://github.com/rust-lang/rust/issues/82523 (and no more talk about unsafe blocks making any difference). So behavior barely changes, the warning is just worded differently. For references to packed fields inside `unsafe` blocks, this PR shows a new future-incompat warning.

Closes https://github.com/rust-lang/rust/issues/46043 because that lint no longer exists.

### CODE REVIEW

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 1]
```diff
@@ -1150,49 +1154,6 @@ declare_lint! {
     "detects attempts to mutate a `const` item",
 }
 
-declare_lint! {
```
Comment (nagisa) [inline compiler/rustc_lint_defs/src/builtin.rs:1153]: Is it okay to entirely remove the lints after they make their way to stable? I mildly recall us having a mechanism (much like for features) to "remove" a lint without actually removing it and/or making things like `#[deny(warnings, safe_packed_borrows)]` fail.

Comment (ehuss) [reply compiler/rustc_lint_defs/src/builtin.rs:1153]: [`register_renamed`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/context/struct.LintStore.html#method.register_renamed) and [`register_removed`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/context/struct.LintStore.html#method.register_removed)

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 2]
```diff
@@ -1078,8 +1078,12 @@ declare_lint! {
     /// [undefined behavior]: https://doc.rust-lang.org/reference/behavior-considered-undefined.html
     /// [issue #27060]: https://github.com/rust-lang/rust/issues/27060
     pub UNALIGNED_REFERENCES,
-    Allow,
+    Warn,
```
Comment (ehuss) [inline compiler/rustc_lint_defs/src/builtin.rs:1081]: Can you also update the documentation a few lines above to remove the paragraph about it being `allow`?  And maybe switch the link to the new tracking issue (#82523)?

**Comment by digama0** [comment]
Why is it okay to make it not unsafe anymore? Doesn't this cause a soundness issue, at least in versions that don't give the hard error (i.e. the current version)?

**Comment by RalfJung** [comment]
> Why is it okay to make it not unsafe anymore? Doesn't this cause a soundness issue, at least in versions that don't give the hard error (i.e. the current version)?

Instead of making it unsafe, we will forbid it entirely. This is always UB, which is not allowed even in unsafe blocks.

Previously, outside unsafe blocks, it just caused a warning -- that was silenced by adding an unsafe block. That makes little sense, given that it is *still UB*.

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_lint_defs/src/builtin.rs:1153]: Oh right, good point.

File: compiler/rustc_lint_defs/src/builtin.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_lint_defs/src/builtin.rs:1077]: Good point, done.

File: compiler/rustc_lint/src/lib.rs [hunk 3]
```diff
@@ -336,6 +336,7 @@ fn register_builtins(store: &mut LintStore, no_interleave_lints: bool) {
     store.register_renamed("redundant_semicolon", "redundant_semicolons");
     store.register_renamed("intra_doc_link_resolution_failure", "broken_intra_doc_links");
     store.register_renamed("overlapping_patterns", "overlapping_range_endpoints");
+    store.register_renamed("safe_packed_borrows", "unaligned_references");
```
Comment (RalfJung) [inline compiler/rustc_lint/src/lib.rs:339]: I called this a "rename" now because the lints are fairly similar... but maybe "remove" would be more appropriate?

**Comment by RalfJung** [comment]
FWIW, I don't know what our policy is wrt how long we wait before shipping such things -- `std::ptr::addr_of!` is available on beta and nightly, but not yet on stable.  So maybe we want to wait until it hits stable to ensure that people can properly fix this warning while remaining stable-compatible. But in case there need to be FCPs or so I wanted to already get the ball rolling here.

**Comment by DemiMarie** [comment]
In the future, I would like to see a type that wraps a (possibly unaligned) pointer that is guaranteed to be safe to dereference.

File: compiler/rustc_lint_defs/src/builtin.rs [hunk 4]
```diff
@@ -1066,20 +1066,20 @@ declare_lint! {
...
-    /// [undefined behavior] and should be disallowed.
-    ///
-    /// This lint is "allow" by default because there is no stable
-    /// alternative, and it is not yet certain how widespread existing code
-    /// will trigger this lint.
-    ///
-    /// See [issue #27060] for more discussion.
+    /// Creating a reference to an insufficiently aligned packed field is [undefined behavior] and
+    /// should be disallowed. Using an `unsafe` block does not change anything about this. Instead,
+    /// the code should use raw pointers and unaligned accesses, or do a copy of the data in the
```
Comment (petrochenkov) [inline compiler/rustc_lint_defs/src/builtin.rs:1071]:
```suggestion
    /// the code should do a copy of the data in the packed field or use raw pointers and unaligned accesses
```
From my experience the most common way to trigger this lint is passing a packed field to a formatting/printing macro that implicitly takes references, like `println!("{:?}", packed.field);`, so it's preferable to put the advice about copying the value first.

File: compiler/rustc_lint/src/lib.rs (hunk 3 above)
Comment (petrochenkov) [reply compiler/rustc_lint/src/lib.rs:339]: No opinion, seems fine as is.

**Comment by petrochenkov** [comment]
I think it's useful to land this even if `std::ptr::addr_of` is not yet stable, since the most common correct fix is to copy the field rather than to take a raw reference to it.
The old lint is not good, I've personally seen people wrongly silencing the warning by adding an `unsafe` block instead of copying the value.

**Comment by petrochenkov** [comment]
r=me with the doc tweaked (https://github.com/rust-lang/rust/pull/82525#discussion_r584317154).

**Comment by RalfJung** [comment]
> I think it's useful to land this even if std::ptr::addr_of is not yet stable, since the most common correct fix is to copy the field rather than to take a raw reference to it.

My concern here is that people will silence the lint if they cannot fix the error because `addr_of` is not yet stable.

Let's see what @rust-lang/lang says.

**Comment by DemiMarie** [comment]
> > I think it's useful to land this even if std::ptr::addr_of is not yet stable, since the most common correct fix is to copy the field rather than to take a raw reference to it.
> 
> My concern here is that people will silence the lint if they cannot fix the error because `addr_of` is not yet stable.

It is worth noting that a packed field can be aligned at runtime, even if it the compiler cannot prove this.  In this situation, breaking code that validly took the address of a packed field (after appropriate runtime checks) would be a regression.

**Comment by RalfJung** [comment]
This would have to be code that actually *guarantees* that the packed field is aligned at runtime. Code that *sometimes* happens to be correct when the stars align, still has UB (UB in any non-deterministic branch "infects" all branches).

Is there a known example of such code?

**Comment by DemiMarie** [comment]
> This would have to be code that actually _guarantees_ that the packed field is aligned at runtime. Code that _sometimes_ happens to be correct when the stars align, still has UB (UB in any non-deterministic branch "infects" all branches). On second reading, I guess that's what you meant by "after appropriate runtime checks".
> 
> Is there a known example of such code? There certainly are known examples of code that creates packed references in unsafe blocks and does so incorrectly (because the old lint wasn't great).

I don’t know of any in this particular case, but I do know of crates that check that a buffer (such as an `&[u8]`) is properly aligned before converting it to a more-aligned slice.  That said, I think a better solution is to stabilize `std::ptr::addr_of` ASAP.

**Comment by RalfJung** [comment]
> but I do know of crates that check that a buffer (such as an &[u8]) is properly aligned before converting it to a more-aligned slice.

Yeah, that's no uncommon. But for packed fields it seems less likely than the invalid alternatives -- in my, admittedly limited, experience.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/lang meeting and we would approve **merging** the PR. I'm happy to do any review necessary.

**Comment by petrochenkov** [comment]
r=me with commits squashed.
