### PR TITLE
Propagate `types.err` in locals further to avoid spurious knock-down errors

### LINKED ISSUE #33575: Unhelpful "Sized not implemented for str" (or slices) after method lookup error.
``` rust
fn main() {
    let x = ().foo();
    <i32 as std::str::FromStr>::from_str(&x);
}
```

```
<anon>:2:16: 2:19 error: no method named `foo` found for type `()` in the current scope
<anon>:2:9: 2:10 error: the trait `core::marker::Sized` is not implemented for the type `str` [E0277]
```

Because of the method error, `x` doesn't get a type (not even `TyError`, AFAICT), and then it gets inferred to `str` from another call in the function, which results in the unsized variable error.

### LINKED ISSUE #44504: Bogus extra error about unsized variable (the trait bound `str: std::marker::Sized` is not satisfied)
Given code like this (not complete):

```rust
extern crate serde_json;
let g1 = vec![0; 16];
let json1 = serde_json::to_pretty_string(&g1).unwrap();
let foo: Foo = serde_json::from_str(&json1).unwrap();
```

The first error is correct but the second is nonsense:

```rust
error[E0425]: cannot find function `to_pretty_string` in module `serde_json`
   --> serialization-tests/tests/serialization.rs:498:35
    |
498 |         let json1 = serde_json::to_pretty_string(&g1).unwrap();
    |                                 ^^^^^^^^^^^^^^^^ not found in `serde_json`

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> serialization-tests/tests/serialization.rs:498:13
    |
498 |         let json1 = serde_json::to_pretty_string(&g1).unwrap();
    |             ^^^^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: all local variables must have a statically known size
```

There's an extra error here. `json1` is used in a way (with the `from_str` function) that it should be a `str` or something that derefs to `str`. The second error message supposes it is a `str`, which is nonsense that the user doesn't intend at all. (If the user would only find the right name of the function, they would get a String in the json variable and the next line compiles fine.)

### PR DESCRIPTION
**Pull request by estebank**
Fix #33575, fix #44504.

### CODE REVIEW

**Comment by estebank** [comment]
cc @eddyb

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3752,14 +3752,35 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    decl_ty: t,
+                    revealed_ty: init_ty,
+                });
             }
         }
 
         self.check_pat_top(&local.pat, t, None);
         let pat_ty = self.node_ty(local.pat.hir_id);
+        debug!("check_decl_local pat_ty {:?}", pat_ty);
         if pat_ty.references_error() {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: De-duplicate this please with a new method (including the `if`) (also to reduce diagnostic logic in happy path).

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -3752,14 +3752,35 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            // Override the types everywhere with `types.err` to avoid knock down errors.
             self.write_ty(local.hir_id, pat_ty);
+            self.write_ty(local.pat.hir_id, pat_ty);
+            self.locals.borrow_mut().insert(local.hir_id, LocalTy {
+                decl_ty: t,
+                revealed_ty: pat_ty,
+            });
+            self.locals.borrow_mut().insert(local.pat.hir_id, LocalTy {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Also de-dup the `LocalTy`. :)

File: src/librustc_typeck/check/coercion.rs [hunk 3]
```diff
@@ -821,7 +821,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
 
         let (adjustments, _) = self.register_infer_ok_obligations(ok);
         self.apply_adjustments(expr, adjustments);
-        Ok(target)
+        if expr_ty.references_error() {
```
Comment (Centril) [inline src/librustc_typeck/check/coercion.rs]:
```suggestion
        Ok(if expr_ty.references_error() {
```

File: src/test/ui/issues/issue-33575.rs [hunk 4]
```diff
@@ -0,0 +1,4 @@
+fn main() {
+    let baz = ().foo(); //~ ERROR no method named `foo` found for type `()` in the current scope
+    <i32 as std::str::FromStr>::from_str(&baz); // No complains about `str` being unsized
```
Comment (Centril) [inline src/test/ui/issues/issue-33575.rs]:
```suggestion
    <i32 as std::str::FromStr>::from_str(&baz); // No complaints about `str` being unsized.
```

**Review by Centril — CHANGES_REQUESTED** [review]

**Comment by Centril** [comment]
r=me with comments addressed (if you want).
