### PR TITLE
Use min_specialization in libcore

### LINKED ISSUE #68536: `nth_back()` for `Zip` returns wrong values
Assertions are successful in this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ecd909fd9a7fb53290298f2045a07bfd)):

```rust
let mut a = Vec::new();
let mut b = Vec::new();
let value = [1, 2, 3, 4, 5, 6]
    .iter()
    .cloned()
    .map(|n| {
        a.push(n);
        n * 10
    })
    .zip([2, 3, 4, 5, 6, 7, 8].iter().cloned().map(|n| {
        b.push(n * 100);
        n * 1000
    }))
    .nth_back(3);
assert_eq!(value, Some((30, 4000)));
assert_eq!(a, vec![6, 6, 5, 5, 4, 4, 3]);
assert_eq!(b, vec![800, 700, 700, 600, 600, 500, 500, 400]);
```

But later assertions are actually wrong (the second and third ones shouldn't double-count).
@matthewjasper pointed out it's a bug that exists in the current `next_back` implementation.

### PR DESCRIPTION
**Pull request by matthewjasper**
Getting `TrustedRandomAccess` to work is the main interesting thing here.

- `get_unchecked` is now an unstable, hidden method on `Iterator`
- The contract for `TrustedRandomAccess` is made clearer in documentation
- Fixed a bug where `Debug` would create aliasing references when using the specialized zip impl
- Added tests for the side effects of `next_back` and `nth`.

closes #68536

### CODE REVIEW

File: src/libcore/str/mod.rs [hunk 1]
```diff
@@ -822,6 +823,13 @@ impl Iterator for Bytes<'_> {
     {
         self.0.rposition(predicate)
     }
+
+    #[inline]
+    unsafe fn get_unchecked(&mut self, idx: usize) -> u8 {
+        // SAFETY: we directly wrap `self.0`, so all safety requirements are
```
Comment (nagisa) [inline src/libcore/str/mod.rs:829]: (note: not something that needs to be fixed, just me rambling) I find this comment interesting. I understand the need to add such a comment around an `unsafe { }` block as that's where callers spend effort to satisfy the invariants of the unsafe callee, however in this case, as this comment alludes to, the responsibility for all the invariants is propagated to the caller of the wrapping function… so this comment doesn’t appear to be adding any value. If anything I’d expect a doc-comment on top of this wrapper function specifying that the caller should look at docs of `$ANOTHER_FUNCTION` for invariants they need to uphold.

File: src/libcore/iter/adapters/zip.rs [hunk 2]
```diff
@@ -295,19 +324,105 @@ where
...
+/// Further, given that these conditions are met, it must guarantee that:
+///
+/// * It does not change the value returned from `size_hint`
+/// * It must be safe to call the methods listed above on `self` after calling
+///   `get_unchecked`, assuming that the required traits are implemented.
+/// * It must also be safe to drop `self` after calling `get_unchecked`.
+#[doc(hidden)]
+#[unstable(feature = "trusted_random_access", issue = "none")]
+#[rustc_specialization_trait]
+pub unsafe trait TrustedRandomAccess: Sized {
```
Comment (nagisa) [inline src/libcore/iter/adapters/zip.rs:385]: Why does this need to become `pub`?

File: src/libcore/iter/adapters/zip.rs [hunk 3]
```diff
@@ -295,19 +324,105 @@ where
...
 ///
 /// # Safety
 ///
-/// The iterator's .len() and size_hint() must be exact.
-/// `.len()` must be cheap to call.
+/// The iterator's `size_hint` must be exact and cheap to call.
+///
+/// `size` may not be overridden.
+///
+/// `<Self as Iterator>::get_unchecked` must be overridden. It must be safe to
```
Comment (nagisa) [inline src/libcore/iter/adapters/zip.rs:360]: Given that the default implementation simply `panic!()`s, this is not an unsafety invariant, is it?

**Review by nagisa — COMMENTED** [review]
Only made a very basic initial pass, got distracted before I could go through the whole PR.

File: src/libcore/iter/adapters/zip.rs (hunk 2 above)
Comment (matthewjasper) [reply src/libcore/iter/adapters/zip.rs:385]: It's now used in the interface of `Iterator`

**Comment by JohnTitor** [comment]
Let's r? @nagisa as they left some review comments.

**Review by nagisa — APPROVED** [review]
@bors r+

**Comment by nagisa** [comment]
Oh well, this will need a rebase, but r=me once that's done.

**Comment by the8472** [comment]
@matthewjasper I'm currently thinking how to extend `TrustedRandomAccess` to drop types, one piece I am currently not understanding is why  `__iterator_get_unchecked` was moved from `TrustedRandomAccess` to `Iterator` but not its other methods.

**Comment by matthewjasper** [comment]
` __iterator_get_unchecked` was moved because it sometimes needs the bounds on the `Iterator` impl. The other methods were not because I wanted to minimize what was added to `Iterator`.
