### PR TITLE
fix(expand): prevent infinity loop in macro containing only "///"

### LINKED ISSUE #112342: A simple macro with "///" hangs
### Code:

```rust
#[macro_export]
macro_rules! memory_leak {
    (
        $(
            /// <-- causes the memory leak
        )*
    ) => {};
}

// must call at least once
memory_leak! {}

fn main() {}
```

Here are some playground links at which it also doesn't compile. (also does not work on `release`)
[Playground (2021; stable; debug)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=25331ec7971a87eaceafafb5ac8a662f)
[Playground (2021; nightly; debug)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e8c77ce3e0331db042eddfe996455475)

### Steps to reproduce

* Save the code as `memory_leak.rs`
* Run `rustc memory_leak.rs`

### Expected Behavior:

Raise an `repetition matches empty token tree` compiler error, like a normal comment would, as an example:
```rust
#[macro_export]
macro_rules! works {
    (
        $(
            // <-- notice the missing slash
        )*
    ) => {};
}

works! {}

fn main() {}
```

### What happened:

It entered an infinite loop and allocated infinite amount of memory. I have 16 GB of ram and 8 GB swap, at one point it got killed by the oom killer.

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (e6d4725c7 2023-06-05)
binary: rustc
commit-hash: e6d4725c76f3b526c74454bc51afdf6daf133506
commit-date: 2023-06-05
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4
```

`No backtrace available, as it gets killed by the oom killer`

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes https://github.com/rust-lang/rust/issues/112342

Issue #112342 was caused by an infinity loop in `parse_tt_inner`, and the state of it is as follows:

- `matcher`: `[Sequence, Token(Doc), SequenceKleeneOpNoSep(op: ZeroOrMore), Eof]`

-  loop:

| Iteration | Action | 
| - | - |
| 0   |  enter `Sequence`|
| 1    |  enter `Token(Doc)` and `mp.idx += 1` had been executed |
| 2   |  enter `SequenceKleeneOpNoSep` and reset `mp.idx` to `1` |
| 3   | enter `Token(Doc)` again|

To prevent the infinite loop, a check for whether it only contains `DocComment` in `check_lhs_no_empty_seq` had been added.

### CODE REVIEW

File: compiler/rustc_expand/src/mbe/macro_parser.rs [hunk 1]
```diff
@@ -463,7 +464,7 @@ impl TtParser {
         // Matcher positions that would be valid if the macro invocation was over now. Only
         // modified if `token == Eof`.
         let mut eof_mps = EofMatcherPositions::None;
-
+        let mut pre_doc_token_idx = None;
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_parser.rs:467]: Nit: I think prev would be a better name here, as `pre-` can also indicate something before something else.

File: compiler/rustc_expand/src/mbe/macro_parser.rs [hunk 2]
```diff
@@ -526,6 +528,12 @@ impl TtParser {
                     };
                     self.cur_mps.push(ending_mp);
 
+                    // A workaround to prevent a infinity loop between
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_parser.rs:531]: Nit

```suggestion
                    // A workaround to prevent an infinity loop between
```

**Review by est31 — APPROVED** [review]
~~r=me except two small nits, very good PR~~ edit: see [comment below](https://github.com/rust-lang/rust/pull/112345#issuecomment-1578900582)

File: tests/ui/macros/issue-112342-1.rs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+macro_rules! m1 {
+    (
+        $(
+            ///
+        )*
+    ) => {};
+}
+
+m1! {} //~ERROR unexpected end of macro invocation
```
[the remark this answers is not in the document]
Comment (Nilstrieb) [reply tests/ui/macros/issue-112342-1.rs:11]: even if it should fail, the error looks wrong
```
   | ^^^^^^ missing tokens in macro arguments
   |
   = note: while trying to match sequence start
```

[the remark this answers is not in the document]
Comment (Nilstrieb) [reply tests/ui/macros/issue-112342-1.rs:11]: I haven't looked at this in detail (I have some familiarity with the code but it's been a while) but I don't think this is the correct solution if it leads to this behavior.

[the remark this answers is not in the document]
Comment (bvanjoi) [reply tests/ui/macros/issue-112342-1.rs:11]: > I would expect this to pass

Maybe not, `macro_rules! m { ( $()* ) => {} }` will throw error.

> the error looks wrong

Yes, you are right, naked break is not good for this situation, I will change `break` to `continue`, it will emit error same as:

```rs
macro_rules! m {
    (
        $(
            ///
        )?
    ) => {};
}
```

As for the error throwing `missing tokens in macro arguments`, I think it would be better to fix it in a separate PR.

File: compiler/rustc_expand/src/mbe/macro_parser.rs (hunk 1 above)
Comment (bvanjoi) [reply compiler/rustc_expand/src/mbe/macro_parser.rs:467]: Forgive my poor English 😂

**Comment by est31** [comment]
Hmm yeah so what is happening here is that the compiler attempts to try another repetition, infinitely many times. This would also happen for code like:

```Rust
macro_rules! foo {
    ($()*) => {};
}
foo!();
```

Similarly:

```Rust
macro_rules! foo {
    ($($(foo:tt)?)*) => {};
}
```

But thankfully the compiler catches that before it gets into the matching code and errors with "repetition matches empty token tree".

I think it would be best to instead edit `check_lhs_no_empty_seqa` to check if there is a sequence that has nothing but a doc comment. Make sure that it also errors for multiple doc comments :)

cc also #5067, #42755, #57597

**Comment by bvanjoi** [comment]
> it would be best to instead edit check_lhs_no_empty_seqa to check if there is a sequence that has nothing but a doc comment.

nice solution!

**Review by est31 — APPROVED** [review]
r=me if you add a test for `///` together with another `///` doc comment, as well as one test with `///` and `$(foo:tt)?`.

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 4]
```diff
@@ -647,6 +647,7 @@ fn check_lhs_no_empty_seq(sess: &ParseSess, tts: &[mbe::TokenTree]) -> bool {
                 if seq.separator.is_none()
                     && seq.tts.iter().all(|seq_tt| match seq_tt {
                         TokenTree::MetaVarDecl(_, _, Some(NonterminalKind::Vis)) => true,
+                        TokenTree::Token(t) => matches!(t, Token { kind: DocComment(..), .. }),
```
Comment (Nilstrieb) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:650]: if you slightly restructure the code you should be able to track whether a doc comment was used. If it was, you should attach an extra note to the diagnostic saying `doc comments are ignored in matcher position`, because otherwise it's quite confusing. You may even be able to record the span of the last doc comment inside and emit a `span_note` pointing at it for maximal prettyness 😊

Comment (est31) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:650]: The same could be done for a `:vis` matcher as it's not 100% obvious there either that they can be empty.

Also there might be cases where you have multiple such matchers combined:

```Rust
macro_rules! foo {
($(
    ///
    $v:vis
)*) => {};
}
```

It is a nice thing for a separate PR as well, shrug.

Comment (Nilstrieb) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:650]: doing it together with vis would be a good follow up PR, agreed. r=me too if you want :D

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 5]
```diff
@@ -628,6 +628,44 @@ fn check_lhs_nt_follows(sess: &ParseSess, def: &ast::Item, lhs: &mbe::TokenTree)
     // after parsing/expansion. we can report every error in every macro this way.
 }
 
+fn is_empty_token_tree(sess: &ParseSess, seq: &mbe::SequenceRepetition) -> bool {
+    if seq.separator.is_some() {
+        return false;
+    }
+    use mbe::TokenTree;
+    let mut index = 0;
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:636]: Instead of an index you could use a (peekable) iterator instead, and `while let Some(tt) = it.next()`.

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 6]
```diff
@@ -628,6 +628,44 @@ fn check_lhs_nt_follows(sess: &ParseSess, def: &ast::Item, lhs: &mbe::TokenTree)
     // after parsing/expansion. we can report every error in every macro this way.
 }
 
+fn is_empty_token_tree(sess: &ParseSess, seq: &mbe::SequenceRepetition) -> bool {
+    if seq.separator.is_some() {
+        return false;
+    }
+    use mbe::TokenTree;
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:635]: Use statements should, with few exceptions (like wildcard enum variant imports), always be on the top of the file. This is not one of the exceptions.

**Review by est31 — CHANGES_REQUESTED** [review]

File: compiler/rustc_expand/src/mbe/macro_rules.rs (hunk 6 above)
Comment (bvanjoi) [reply compiler/rustc_expand/src/mbe/macro_rules.rs:635]: The reason for using `use mbe::TokenTree;` here should be to prevent confusion with (rustc_ast::tokenstream::TokenTree)[https://github.com/rust-lang/rust/blob/master/compiler/rustc_ expand/src/mbe/macro_rules.rs#L13], as you can see, there are many uses of `macro_rules.rs`.

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 7]
```diff
@@ -628,6 +628,40 @@ fn check_lhs_nt_follows(sess: &ParseSess, def: &ast::Item, lhs: &mbe::TokenTree)
...
+fn is_empty_token_tree(sess: &ParseSess, seq: &mbe::SequenceRepetition) -> bool {
+    if seq.separator.is_some() {
+        return false;
+    }
+    let mut is_empty = true;
+    let mut iter = seq.tts.iter().peekable();
+    while let Some(tt) = iter.next() {
+        match tt {
+            mbe::TokenTree::MetaVarDecl(_, _, Some(NonterminalKind::Vis)) => {}
+            mbe::TokenTree::Token(t) if matches!(t, Token { kind: DocComment(..), .. }) => {
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:640]: You can combine the match and the `matches!` here to one via `mbe::TokenTree::Token(t @ Token { etc })`.

File: compiler/rustc_expand/src/mbe/macro_rules.rs [hunk 8]
```diff
@@ -628,6 +628,40 @@ fn check_lhs_nt_follows(sess: &ParseSess, def: &ast::Item, lhs: &mbe::TokenTree)
...
+                let lo = t.span.lo();
+                let mut now = t;
+                while let Some(&next) = iter.peek() {
+                    if let mbe::TokenTree::Token(t) = next && matches!(t, Token { kind: DocComment(..), .. }) {
```
Comment (est31) [inline compiler/rustc_expand/src/mbe/macro_rules.rs:644]: Nit: same here. In fact, it could be integrated into the `while let` itself (doesn't have to).

**Review by est31 — APPROVED** [review]
Some final nits. I promised approval before, but given you are learning I thought this would be useful to know.

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
@bors r=nilstrieb,est31

as per https://github.com/rust-lang/rust/pull/112345#discussion_r1219894370
