### PR TITLE
[NLL] Fix various unused mut errors

### LINKED ISSUE #50897: [NLL] mutability difference
```
#![feature(generator_trait, generators)]
#![feature(nll)]

use std::ops::{Generator, GeneratorState};

fn generator_to_iterator<G>(g: G) -> impl Iterator<Item = G::Yield>
where G: Generator<Return = ()> {
    struct It<G>(G);

    impl<G: Generator<Return = ()>> Iterator for It<G> {
        type Item = G::Yield;

        fn next(&mut self) -> Option<Self::Item> {
            unsafe {
                match self.0.resume() {
                    GeneratorState::Yielded(y) => Some(y),
                    GeneratorState::Complete(()) => None,
                }
            }
        }
    }

    It(g)
}

fn foo(mut n: u32) -> impl Iterator<Item=u32> {
    generator_to_iterator(move || {
        while n != 0 {
            yield n;
            n -= 1;
        }
    })
}

fn main() {
    for d in foo(10) {
        println!("{}", d);
    }
}
```

Gives a warning:

```
warning: variable does not need to be mutable
  --> ...\test.rs:26:8
   |
26 | fn foo(mut n: u32) -> impl Iterator<Item=u32> {
   |        ----^
   |        |
   |        help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default
```

If I remove the "mut" that warning goes away and the program runs correctly.

But if I comment out the feature(nll) line (without the "mut" in foo signature) it gives:

```
error[E0594]: cannot assign to immutable captured outer variable in an `FnOnce` closure `n`
  --> ...\test.rs:30:13
   |
30 |             n -= 1;
   |             ^^^^^^
```

### LINKED ISSUE #51801: nll: incorrect unused_mut with move closure
With the [nll feature](rust-lang/rust#43234) enabled, a "variable does not need to be mutable" warning is emitted incorrectly when a variable is mutated from inside a move closure.

```
#![feature(nll)]

fn main() {
    let mut baz = 4; // "warning: variable does not need to be mutable"
    move || { baz = 6 };
}   
```

### LINKED ISSUE #51830: [NLL] variable does not need to be mutable
UPD:
[minimal repro](https://play.rust-lang.org/?gist=96e87e9946fca3db5273c6ac87008af9&version=nightly&mode=debug) from @lqd :
```
#![feature(nll)]
#![allow(unused_variables)]
fn main() {
    let _ = Some(0).as_ref().map(|ref a| true);
}
```

---------------

I got this warning:

```
warning: variable does not need to be mutable
   --> src/toxcore/dht/server/mod.rs:363:32
    |
363 |         ping_map.retain(|&_pk, ref client|
    |                                ----^^^^^^
    |                                |
    |                                help: remove this `mut`
```

While I don't see any `mut` in the given code. The given patch fixed the warning but still I don't know why:

```diff
-        ping_map.retain(|&_pk, ref client|
+        ping_map.retain(|_pk, client|
```

You may try on: https://github.com/tox-rs/tox/commit/3d0ddf86c32abb94c94eb44ff1388bab06f50bd2 (you will have to enable NLL on your own).

Also seems like you don't highlight the correct site of the error in macros:

```
warning: variable does not need to be mutable
   --> src/toxcore/state_format/old.rs:173:9
    |
173 | /         do_gen!(buf,
174 | |             gen_le_u16!(0x0002) >>
175 | |             gen_slice!(SECTION_MAGIC) >>
176 | |             gen_le_u32!(DHT_MAGICAL as u32) >>
...   |
180 | |             gen_many_ref!(&self.0, |buf, node| PackedNode::to_bytes(node, buf))
181 | |         )
    | |_________^ help: remove this `mut`
    |
    = note: #[warn(unused_mut)] on by default
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

warning: variable does not need to be mutable
 --> <gen_many_ref macros>:3:32
  |
3 | Ok ( ( $ i , $ idx ) ) , | r , ref v | {
  |                                ----^
  |                                |
  |                                help: remove this `mut`
```

I would like you to highlight [gen_many_ref!](https://docs.rs/cookie-factory/0.2.4/src/cookie_factory/gen.rs.html#813-825).

### LINKED ISSUE #51904: NLL: incorrect "unused mut" lint warning, with multiple closures
Found while trying to bootstrap Rust with NLL enabled, just in case we're not already tracking this incorrect warning (as we're already tracking other similar ones in #51801 and #51830 and more).

Reduced from `libsyntax::parser::parser::parse_dot_or_call_expr_with`. Probably not exactly minimal, but smaller than the whole parser :)

Repro here on the [playground](https://play.rust-lang.org/?gist=006f54543251c34541a879a2fb1a0365&version=nightly&mode=debug)

### PR DESCRIPTION
**Pull request by matthewjasper**
Closes #51801
Closes #50897
Closes #51830 
Closes #51904
cc #51918 - keeping this one open in case there are any more issues

This PR contains multiple changes. List of changes with examples of what they fix:

* Change mir generation so that the parameter variable doesn't get a name when a `ref` pattern is used as an argument
```rust
fn f(ref y: i32) {} // doesn't trigger lint
```
* Change mir generation so that by-move closure captures don't get first moved into a temporary.
```rust
let mut x = 0; // doesn't trigger lint
move || {
    x = 1;
};
```
* Treat generator upvars the same as closure upvars
```rust
let mut x = 0; // This mut is now necessary and is not linted against.
move || {
    x = 1;
    yield;
};
```

r? @nikomatsakis

### CODE REVIEW

File: src/librustc_mir/build/expr/as_rvalue.rs [hunk 1]
```diff
@@ -186,10 +186,27 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
...
+                    .map(|upvar| {
+                        let upvar = this.hir.mirror(upvar);
+                        match Category::of(&upvar.kind) {
+                            // Use as_place to avoid creating a temporary when
+                            // moving a variable into a closure, so that
+                            // borrowck knows which variables to mark as being
+                            // used as mut. This is OK here because the upvar
+                            // expressions have no side effects and act on
+                            // disjoint places.
+                            Some(Category::Place) => {
```
Comment (nikomatsakis) [inline src/librustc_mir/build/expr/as_rvalue.rs]: to make sure I am remembering correctly — this occurs on copy/move variables, whereas a by-ref binding would use `as_operand`?

Comment (nikomatsakis) [reply src/librustc_mir/build/expr/as_rvalue.rs]: this might be worth noting in a comment

File: src/librustc_mir/build/mod.rs [hunk 2]
```diff
@@ -675,8 +675,12 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
             // If this is a simple binding pattern, give the local a nice name for debuginfo.
             let mut name = None;
             if let Some(pat) = pattern {
-                if let hir::PatKind::Binding(_, _, ident, _) = pat.node {
-                    name = Some(ident.name);
+                if let hir::PatKind::Binding(binding_annotation, _, ident, _) = pat.node {
+                    if binding_annotation == hir::BindingAnnotation::Unannotated
+                        || binding_annotation == hir::BindingAnnotation::Mutable
```
Comment (nikomatsakis) [inline src/librustc_mir/build/mod.rs]: I don't quite understand this part — does this not affect debuginfo in negative ways or something?

Also, a nit: maybe we should use a match here?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Left a few nits and a question but basically 💯

File: src/librustc_mir/build/mod.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/librustc_mir/build/mod.rs]: I presume this corresponds to 

> Change mir generation so that the parameter variable doesn't get a name when a ref pattern is used as an argument

? 

In that case, I would want to see some comments to that effect...

**Review by nikomatsakis — APPROVED** [review]
