### PR TITLE
move const param structural match checks to wfcheck

### LINKED ISSUE #74950: Cycle detected when deriving PartialEq, Eq for type with non-primitive const param.
The following code used to compile on nightly:

```rust
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct Inner;

#[derive(PartialEq, Eq)]
struct Outer<const I: Inner>;
```

[but now results in](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5dc01707666caa7066b31aa686f1374c) 

```
error[E0391]: cycle detected when computing type of `Outer::I`
   --> src\lib.rs:7:20
    |
7   | struct Outer<const I: Inner>;
    |                    ^
    |
    = note: ...which requires computing whether `Inner` implements `PartialStructuralEq` and `StructuralEq`...
    = note: ...which requires evaluating trait selection obligation `Inner: std::marker::StructuralPartialEq`...
note: ...which requires trait impls of `std::marker::StructuralPartialEq`...
   --> .../src/rust\library\core\src\marker.rs:152:1
    |
152 | pub trait StructuralPartialEq {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing type of `<impl at src\lib.rs:6:10: 6:19>`...
   --> src\lib.rs:6:10
    |
6   | #[derive(PartialEq, Eq)]
    |          ^^^^^^^^^
    = note: ...which again requires computing type of `Outer::I`, completing the cycle
note: cycle used when computing type of `<impl at src\lib.rs:6:21: 6:23>`
   --> src\lib.rs:6:21
    |
6   | #[derive(PartialEq, Eq)]
    |                     ^^
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

The same is true for any non-primitive const param, i.e.:
```rust
#[derive(PartialEq, Eq)]
struct Outer<const I: Option<usize>>;
```

### LINKED ISSUE #75047: expressions in the type of const params can cause cycle errors
```rust
#![feature(const_generics)]
struct Bar<T>(T);

impl<T> Bar<T> {
    const fn value() -> usize {
        42
    }
}

struct Foo<const N: [u8; Bar::<u32>::value()]>;
```
This results in 
```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

error[E0391]: cycle detected when computing type of `Foo`
  --> src/lib.rs:10:1
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing type of `Foo::N`...
  --> src/lib.rs:10:18
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   |                  ^
note: ...which requires const-evaluating + checking `Foo::{{constant}}#0`...
  --> src/lib.rs:10:26
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   |                          ^^^^^^^^^^^^^^^^^^^
note: ...which requires const-evaluating + checking `Foo::{{constant}}#0`...
  --> src/lib.rs:10:26
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   |                          ^^^^^^^^^^^^^^^^^^^
note: ...which requires const-evaluating `Foo::{{constant}}#0`...
  --> src/lib.rs:10:26
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   |                          ^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `Foo::{{constant}}#0`...
  --> src/lib.rs:10:26
   |
10 | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   |                          ^^^^^^^^^^^^^^^^^^^
note: ...which requires computing the variances of `Bar`...
  --> src/lib.rs:2:1
   |
2  | struct Bar<T>(T);
   | ^^^^^^^^^^^^^^^^^
   = note: ...which requires computing the variances for items in this crate...
   = note: ...which again requires computing type of `Foo`, completing the cycle
note: cycle used when collecting item types in top-level module
  --> src/lib.rs:1:1
   |
1  | / #![feature(const_generics)]
2  | | struct Bar<T>(T);
3  | |
4  | | impl<T> Bar<T> {
...  |
9  | |
10 | | struct Foo<const N: [u8; Bar::<u32>::value()]>;
   | |_______________________________________________^

error: aborting due to previous error; 1 warning emitted

```

### PR DESCRIPTION
**Pull request by lcnr**
fixes #75047 fixes #74950

We currently check for structural match violations inside of `type_of`.
As we need to check the array length when checking if `[NonEq; arr_len]` is structural match, we potentially require the variance of an expression. Computing the variance requires `type_of` for all types though, resulting in a cycle error.

r? @varkor @eddyb

### CODE REVIEW

**Comment by lcnr** [comment]
This PR fixes this by moving structural match checks to wfcheck which is now potentially slower, so this requires a perf run.

@bors rollup=never

**Comment by lcnr** [comment]
Apparently this removes some additional overflow errors :thinking: not sure what's going on there,
probably have to look a bit more into why this happens before we can merge this

**Comment by lcnr** [comment]
I guess this is now ready for review.

@bors try @rust-timer queue

**Comment by Aaron1011** [comment]
> This also changes wfcheck to not run in parallel anymore, which means that we only emit at most 1 overflow error.

@lcnr Why can wfcheck no longer run in parallel?

**Comment by lcnr** [comment]
Because par visitor only visits items and the `Visitor` takes `&mut self`. Just realised how to fix this :laughing: let me quickly do so...

**Comment by lcnr** [comment]
Okay, wfcheck is once again running in parralel (or at least it pretends to do so :laughing: )

@bors try @rust-timer queue

**Comment by lcnr** [comment]
perf looks neutral to me

@bors rollup-

**Comment by varkor** [comment]
I'll try to review soon; sorry for the delay.

File: src/test/ui/const-generics/issues/issue-74950.rs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+// revisions: full min
+#![cfg_attr(full, feature(const_generics))]
+#![cfg_attr(full, allow(incomplete_features))]
+#![cfg_attr(min, feature(min_const_generics))]
+
+
+#[derive(PartialEq, Eq)]
+struct Inner;
+
+// Note: We emit the error 5 times if we don't deduplicate:
```
Comment (varkor) [inline src/test/ui/const-generics/issues/issue-74950.rs:11]: Can we deduplicate? This is very user-unfriendly at the moment.

File: src/test/ui/const-generics/nested-type.min.stderr [hunk 2]
```diff
@@ -4,172 +4,29 @@ error: using `[u8; _]` as const generic parameters is forbidden
...
 ...  |
-LL | |     Foo::<17>::value()
+LL | |
 LL | | }]>;
    | |__^
    |
    = note: the only supported types are integers, `bool` and `char`
    = note: more complex types are supported with `#[feature(const_generics)]`
 
-error[E0391]: cycle detected when computing type of `Foo`
```
Comment (varkor) [inline src/test/ui/const-generics/nested-type.min.stderr:17]: :)

File: src/librustc_typeck/check/wfcheck.rs [hunk 3]
```diff
@@ -275,6 +278,95 @@ pub fn check_impl_item(tcx: TyCtxt<'_>, def_id: LocalDefId) {
...
+            let ty = tcx.type_of(tcx.hir().local_def_id(param.hir_id));
+
+            let err_ty_str;
+            let err = if tcx.features().min_const_generics {
+                match ty.kind {
+                    ty::Bool | ty::Char | ty::Int(_) | ty::Uint(_) | ty::Error(_) => None,
+                    ty::FnPtr(_) => Some("function pointers"),
+                    ty::RawPtr(_) => Some("raw pointers"),
+                    _ => {
+                        err_ty_str = format!("`{}`", ty);
```
Comment (varkor) [inline src/librustc_typeck/check/wfcheck.rs:298]:
```suggestion
                        err_ty_str = format!("`{}`s", ty);
```
Maybe this reads a little better? (Or, alternatively, changing the text `"using {} as const generic parameters is forbidden"` to `"{} is forbidden as the type of a const generic parameter"` for the non-`FnPtr`/`RawPtr` case.)

**Review by varkor — COMMENTED** [review]
r=me with message tweak and deduplication.

File: src/test/ui/const-generics/issues/issue-74950.rs (hunk 1 above)
Comment (lcnr) [reply src/test/ui/const-generics/issues/issue-74950.rs:11]: We deduplicate automatically on stable, the problem is that UI tests don't deduplicate by default

File: src/librustc_typeck/check/wfcheck.rs (hunk 3 above)
Comment (lcnr) [reply src/librustc_typeck/check/wfcheck.rs:300]: Implemented the second suggestion, also moved "note: more complex types are supported with `#[feature(const_generics)]`" to non trigger for pointers.

**Comment by varkor** [comment]
Thanks!

@bors r+

**Comment by lcnr** [comment]
> 2020-08-19T09:12:24.5372520Z curl: (56) SSLRead() return error -9806
> 2020-08-19T09:12:24.5373420Z clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang-query: Lzma library error:  No progress is possible
> 2020-08-19T09:12:24.5473760Z tar: Error exit delayed from previous errors.

@rust-lang/infra is that a spurious error?

**Comment by kennytm** [comment]
yes, but that builder is "fallible", so we could wait for other builders to complete.

**Comment by lcnr** [comment]
> warning: error: Connection to server timed out

That also seems spurious...

@bors retry

**Comment by tmandry** [comment]
Rolled up
@bors retry
