### PR TITLE
Fix ICE when calling non-functions within closures

### LINKED ISSUE #46771: [ICE] Calling syntax on struct
```
fn main() {
    struct Foo;
    (1 .. 2).find(|_| Foo(0) == 0);
}
```

Gives:

```
error[E0618]: expected function, found `main::Foo`
 --> ...\test.rs:3:24
  |
3 |     (1 .. 2).find(|_| Foo(0) == 0);
  |                        ^^^^^^
  |
note: defined here
 --> ...\test.rs:2:5
  |
2 |     struct Foo;
  |     ^^^^^^^^^^^

error: internal compiler error: unexpected panic

note: rustc 1.24.0-nightly (77efd6800 2017-12-15) running on x86_64-pc-windows-gnu

thread 'rustc' panicked at 'LocalTableInContext: key not found', src\libcore\option.rs:891:4
```

Eventually we'll have to start fuzzying the Rustc compiler.

### PR DESCRIPTION
**Pull request by varkor**
The visitor for walking function bodies did not previously properly
handle error-cases for function calls. These are now ignored,
preventing the panic. This fixes #46771.

### CODE REVIEW

File: src/test/compile-fail/issue-46771.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+fn main() {
+    struct Foo;
+    (1 .. 2).find(|_| Foo(0) == 0); //~ ERROR expected function, found `main::Foo`
+}
```
Comment (bjorn3) [inline src/test/compile-fail/issue-46771.rs]: Missing trailing newline

**Review by bjorn3 — CHANGES_REQUESTED** [review]

File: src/test/compile-fail/issue-46771.rs (hunk 1 above)
Comment (varkor) [reply src/test/compile-fail/issue-46771.rs]: Whoops, that's what I get for late-night commits. Fixed.

**Comment by arielb1** [comment]
Your code does not compile libcore, and I suspect it allows such aberrant code as
```Rust
fn foo<F: FnMut()>(f: &F) {
    (*f)();
}
```

**Comment by varkor** [comment]
Not quite sure what happened, but that previous commit was entirely wrong. Sorry, it should be fixed now.

File: src/librustc/middle/expr_use_visitor.rs [hunk 2]
```diff
@@ -558,24 +558,27 @@ impl<'a, 'gcx, 'tcx> ExprUseVisitor<'a, 'gcx, 'tcx> {
...
-                                         ClosureInvocation);
-                    }
-                    FnOverloadedCall => {
-                        let call_scope_r = self.tcx().mk_region(ty::ReScope(call_scope));
-                        self.borrow_expr(callee,
-                                         call_scope_r,
-                                         ty::ImmBorrow,
-                                         ClosureInvocation);
+                let type_dependent_defs = self.mc.tables.type_dependent_defs();
+                if type_dependent_defs.contains_key(call.hir_id) {
```
Comment (arielb1) [inline src/librustc/middle/expr_use_visitor.rs]: Could you use this instead? It's more standard.
```Rust
if let Some(def_id) = type_dependent_defs.get(call.hir_id)
```

Comment (arielb1) [reply src/librustc/middle/expr_use_visitor.rs]: I would actually prefer

```Rust
let def_id = match type_dependent_defs.get(call.hir_id) {
    Some(def) => def.def_id(),
    None => tcx.sess.delay_span_bug(call.span, "no type-dependant def for overloaded call?)
};
```

as that would make sure we get an ICE if there's ever a mismatch.

**Comment by arielb1** [comment]
r=me with comment addressed

File: src/librustc/middle/expr_use_visitor.rs (hunk 2 above)
Comment (varkor) [reply src/librustc/middle/expr_use_visitor.rs]: Isn't an ICE exactly what we're trying to avoid in this situation? In the issue this fix addresses, this function is called for a struct (with no type-dependent call definition) — an error has already been logged, we just want to make sure we don't attempt anything else with it.

**Comment by arielb1** [comment]
> [00:03:23] tidy error: /checkout/src/librustc/middle/expr_use_visitor.rs:582: line longer than 100 chars

**Comment by arielb1** [comment]
I'll r+ when travis is green
