### PR TITLE
Prevent Error::type_id overrides

### LINKED ISSUE #60784: Manual implementations of `Error::type_id` are memory unsafe
Reported by @seanmonstar to the security mailing list recently, it was discovered that the recent stabilization of `Error::type_id` in Rust 1.34.0 is actually not memory safe. Described in a [recent security announcement](https://groups.google.com/forum/#!topic/rustlang-security-announcements/aZabeCMUv70) the stabilization of `Error::type_id` has been reverted for [stable](https://github.com/rust-lang/rust/pull/60785), [beta](https://github.com/rust-lang/rust/pull/60786), and [master](https://github.com/rust-lang/rust/pull/60787).

This leaves us, however, with the question of what to do about this API? `Error::type_id` has been present since the inception of the `Error` trait, all the way back to 1.0.0. It's unstable, however, and is pretty rare as well to have a manual implementation of the `type_id` function. Despite this we would ideally still like a path to stability which includes safety at some point.

This tracking issue is intended to serve as a location to discuss this issue and determine the best way forward to fully removing `Error::type_id` (so even nightly users are not affected by this memory safety issue) and having a stable mechanism for the functionality.

### PR DESCRIPTION
**Pull request by sfackler**
type_id now takes an argument that can't be named outside of the
std::error module, which prevents any implementations from overriding
it. It's a pretty grody solution, and there's no way we can stabilize
the method with this API, but it avoids the soudness issue!

Closes #60784

r? @alexcrichton

### CODE REVIEW

File: src/libstd/error.rs [hunk 1]
```diff
@@ -201,11 +201,19 @@ pub trait Error: Debug + Display {
...
                reason = "this is memory unsafe to override in user code",
                issue = "60784")]
-    fn type_id(&self) -> TypeId where Self: 'static {
+    fn type_id(&self, _: private::Internal) -> TypeId where Self: 'static {
         TypeId::of::<Self>()
     }
 }
 
+mod private {
+    // this is a hack to prevent type_id from being overridden by Error
```
Comment (Centril) [inline src/libstd/error.rs]:
```suggestion
    // This is a hack to prevent `type_id` from being overridden by `Error`
```

**Review by Centril — APPROVED** [review]
A small nit. Looks good to me otherwise.

**Comment by RalfJung** [comment]
I guess this is `pub` in a private module to silence some private-in-public lint? Ouch. :/

Also, right now, doesn't this also prevent calling the method from the outside? Or is that okay because people shouldn't call it anyways?

**Comment by pnkfelix** [comment]
do we not also need the bit from @seanmonstar 's [original suggestion](https://github.com/rust-lang/rust/issues/60784#issuecomment-493259293) with:

```rust
impl dyn Error + 'static {
    fn type_id(&self) -> TypeId {
        self.__type_id(Internal)
    }
}
```

**Comment by alexcrichton** [comment]
@bors: r+

This sounds like a good stopgap approach for mitigating the impact on nightly. In the meantime discussion can continue on the issue for how to stabilize long-term.

File: src/libstd/error.rs [hunk 2]
```diff
@@ -201,11 +201,19 @@ pub trait Error: Debug + Display {
...
         TypeId::of::<Self>()
     }
 }
 
+mod private {
+    // This is a hack to prevent `type_id` from being overridden by `Error`
+    // implementations, since that can enable unsound downcasting.
+    #[unstable(feature = "error_type_id", issue = "60784")]
+    #[derive(Debug)]
+    pub struct Internal;
```
Comment (nagisa) [inline src/libstd/error.rs]: Would `pub(crate)` be a better option?

Comment (sfackler) [reply src/libstd/error.rs]: No, that violates the private types in public interfaces check.

Comment (nagisa) [reply src/libstd/error.rs]: Hypothetically, what would happen if somebody fixed this technical loophole? Would the fix then be blocked on the grounds of this workaround-hack?

Comment (Centril) [reply src/libstd/error.rs]: cc @petrochenkov

Comment (seanmonstar) [reply src/libstd/error.rs]: Fixed which loophole? Allowing such a pseudo public type in an exported interface? Fixing that would likely require a new edition, as many libraries already take advantage.

Comment (sfackler) [reply src/libstd/error.rs]: This is not a loophole - it was the explicit design of the relevant RFC: https://github.com/rust-lang/rfcs/blob/26197104b7bb9a5a35db243d639aee6e46d35d75/text/0136-no-privates-in-public.md#when-is-an-item-public
