### PR TITLE
Match std `RUSTFLAGS` for host and target for `mir-opt` test suite to fix double std build/rebuilds

### LINKED ISSUE #131437: Running `./x test mir-opt` rebuilds std every time
Using `profile = compiler`, running `./x test mir-opt` causes bootstrap to rebuild all of std before running the tests, even when the build cache ought to be warm from a previous `./x test mir-opt`.

Needless to say, this is not very fun when actually trying to run one or more mir-opt tests.

### PR DESCRIPTION
**Pull request by jieyouxu**
Previously the bootstrap compiletest `Step::run` flow had:

```rs
// ensure that `libproc_macro` is available on the host.
builder.ensure(compile::Std::new(compiler, compiler.host));

// ...

if suite == "mir-opt" {
    builder.ensure(compile::Std::new_for_mir_opt_tests(compiler, target));
} else {
    builder.ensure(compile::Std::new(compiler, target));
}
```

This can cause unnecessary std rebuilds (even on the same invocation) because if host == target then `builder.ensure(compile::Std::new_for_mir_opt_tests(compiler, target))` will have different `RUSTFLAGS` than `builder.ensure(compile::Std::new(compiler, compiler.host))`.

This PR fixes that by matching up std `RUSTFLAGS` if the test suite is `mir-opt`:

```rs
if suite == "mir-opt" {
    builder.ensure(compile::Std::new_for_mir_opt_tests(compiler, compiler.host));
} else {
    builder.ensure(compile::Std::new(compiler, compiler.host));
}
```

This is a short-term fix, the better fix is to enforce how `RUSTFLAGS` are handled as described in https://github.com/rust-lang/rust/issues/131437#issuecomment-2401710727.

Fixes #131437.

### CODE REVIEW

File: src/bootstrap/src/core/build_steps/test.rs [hunk 1]
```diff
@@ -1697,7 +1697,11 @@ NOTE: if you're sure you want to do this, please open an issue as to why. In the
         builder.ensure(TestHelpers { target: compiler.host });
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/test.rs:1697]: Remark: the compiletest `Step::run` is some gigantic convoluted build step, lol. I might revisit that in the future and see if I can try to make it uhhh less insane.
