### PR TITLE
The #[panic_handler] attribute can be applied to non-functions

### LINKED ISSUE #54896: The #[panic_handler] attribute can be applied to non-functions
It's possible to apply the `panic_handler` attribute to an `extern crate` statement without errror:

```rust
#[panic_handler]
extern crate some_example_crate;
```

It only causes a linker error:

```
rust-lld: error: undefined symbol: rust_begin_unwind
```

(When the `panic_handler` attribute is not defined there is a much better "`#[panic_handler]` function required, but not found" error. There is also a nice error when the function signature is wrong. But it seems like the above case is not handled.)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #54896.

This commit extends the existing lang items functionality to assert
that the `#[lang_item]` attribute is only found on the appropriate item
for any given lang item. That is, language items representing traits
must only ever have their corresponding attribute placed on a trait, for
example.

r? @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
@bors r+

This looks good to me.

File: src/librustc/middle/lang_items.rs [hunk 1]
```diff
@@ -298,68 +322,68 @@ language_item_table! {
     // defined to use it, but a final product is required to define it
     // somewhere. Additionally, there are restrictions on crates that use a weak
     // lang item, but do not have it defined.
-    PanicFnLangItem,                 "panic",                   panic_fn;
-    PanicBoundsCheckFnLangItem,      "panic_bounds_check",      panic_bounds_check_fn;
-    PanicInfoLangItem,               "panic_info",              panic_info;
-    PanicImplLangItem,               "panic_impl",              panic_impl;
+    PanicFnLangItem,             "panic",              panic_fn,                Target::Fn;
+    PanicBoundsCheckFnLangItem,  "panic_bounds_check", panic_bounds_check_fn,   Target::Fn;
+    PanicInfoLangItem,           "panic_info",         panic_info,              Target::Struct;
```
Comment (nagisa) [inline src/librustc/middle/lang_items.rs]: In the future there might be a language item that could possibly be some sort of type definition, not specifically a `struct`.

This is especially notable here. `panic_info` in `no_core` could easily be defined to be an `enum` as well for example – in fact, the only reason this is a language item is to facilitate type-checking the `panic_impl` function.

Yet, I do not see a nice way out here, and since language items are not stable anyway it seems fine to keep it restrictive for now.

Comment (davidtwco) [reply src/librustc/middle/lang_items.rs]: I think this could be extended to have a `Target::Any` that allows the attribute to be applied to anything, as was the behaviour before this PR. 

Alternatively, the definition of `Target` could be changed to a `u32` and have each bit represent a variant (similar to `AdtFlags`) and then the language item definitions could `|` together these “variants” to indicate that the attribute could be applied to either construct. 

I agree that, for the moment, the simplest solution would be to keep this more restrictive approach and change if necessary.
