### PR TITLE
fix `-Zsanitizer=kcfi` on `#[naked]` functions

### LINKED ISSUE #143266: ICE: `#[naked] functions should always terminate with an asm! block`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Zsanitizer=kcfi -Cpanic=abort
//

#![feature(abi_custom)]

use std::arch::{asm, global_asm, naked_asm};

#[unsafe(naked)]
unsafe extern "custom" fn double() {
    naked_asm!("add rax, rax", "ret");
}

unsafe extern "custom" {}

struct Thing(u64);

trait BitwiseNot {
    #[unsafe(naked)]
    unsafe extern "custom" fn bitwise_not() {
        naked_asm!("\0\x00\u{0}\u{0}", "ret");
    }
}

impl BitwiseNot for Thing {}

#[unsafe(naked)]
unsafe extern "C" fn const_generic<const N: u64>() {
    naked_asm!(
        "mov rax, {}",
        "ret",
        const N,
    );
}

pub fn main() {

    let mut x: u64 = 42;
    unsafe { asm!("call {}", sym Thing::bitwise_not, inout("rax") x) };
}

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
// Test that `extern "custom"` functions can be called from assembly, and defined using a naked
// function, and `global_asm!` with an `extern "custom"` block.
//
//@ run-pass
//@ only-x86_64
#![feature(abi_custom)]

use std::arch::{asm, global_asm, naked_asm};

#[unsafe(naked)]
unsafe extern "custom" fn double() {
    naked_asm!("add rax, rax", "ret");
}

global_asm!(
    // work around macOS prefixing symbols with _
    "    .globl  {0}",
    "{0}:",
    "    add     rax, 1",
    "    ret",
    sym increment,
);

unsafe extern "custom" {
    fn increment();
}

#[repr(transparent)]
struct Thing(u64);

impl Thing {
    #[unsafe(naked)]
    unsafe extern "custom" fn is_even() {
        naked_asm!("test al, 1", "sete al", "ret");
    }
}

trait BitwiseNot {
    #[unsafe(naked)]
    unsafe extern "custom" fn bitwise_not() {
        naked_asm!("\0\x00\u{0}\u{0}", "ret");
    }
}

impl BitwiseNot for Thing {}

#[unsafe(naked)]
unsafe extern "C" fn const_generic<const N: u64>() {
    naked_asm!(
        "mov rax, {}",
        "ret",
        const N,
    );
}

pub fn main() {
    let mut x: u64 = 21;
    unsafe { asm!("call {}", sym double, inout("rax") x) };
    assert_eq!(x, 42);

    let mut x: u64 = 41;
    unsafe { asm!("call {}", sym increment, inout("rax") x) };
    assert_eq!(x, 42);

    let mut x: u8;
    unsafe { asm!("call {}", sym Thing::is_even, inout("al") 42u8 => x) };
    assert!(x != 0);

    let mut x: u64 = 42;
    unsafe { asm!("call {}", sym Thing::bitwise_not, inout("rax") x) };
    assert_eq!(x, !42);

    // Create and call in `asm!` an `extern "custom"` function pointer.
    fn caller(f: unsafe extern "custom" fn(), mut x: u64) -> u64 {
        unsafe { asm!("call {}", in(reg) f, inout("rax") x) };
        x
    }

    assert_eq!(caller(double, 2), 4);

    let x: u64;
    unsafe { asm!("call {}", sym const_generic::<42>, out("rax") x) };
    assert_eq!(x, 42);

    let x: u64;
    unsafe { asm!("call {}", sym const_generic::<84>, out("rax") x) };
    assert_eq!(x, 84);
}

````
</p>
</details>

Version information
````
rustc 1.90.0-nightly (f26e58023 2025-06-30)
binary: rustc
commit-hash: f26e58023071e71636a3c72ac3a2bf89b1f76706
commit-date: 2025-06-30
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zsanitizer=kcfi -Cpanic=abort`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused import: `global_asm`
 --> /tmp/icemaker_global_tempdir.L3dNdrnvcGlo/rustc_testrunner_tmpdir_reporting.8ehK9SvmHkij/mvce.rs:5:22
  |
5 | use std::arch::{asm, global_asm, naked_asm};
  |                      ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: value assigned to `x` is never read
  --> /tmp/icemaker_global_tempdir.L3dNdrnvcGlo/rustc_testrunner_tmpdir_reporting.8ehK9SvmHkij/mvce.rs:37:67
   |
37 |     unsafe { asm!("call {}", sym Thing::bitwise_not, inout("rax") x) };
   |                                                                   ^
   |
   = help: maybe it is overwritten before being read?
   = note: `#[warn(unused_assignments)]` on by default

warning: function `double` is never used
 --> /tmp/icemaker_global_tempdir.L3dNdrnvcGlo/rustc_testrunner_tmpdir_reporting.8ehK9SvmHkij/mvce.rs:8:27
  |
8 | unsafe extern "custom" fn double() {
  |                           ^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: field `0` is never read
  --> /tmp/icemaker_global_tempdir.L3dNdrnvcGlo/rustc_testrunner_tmpdir_reporting.8ehK9SvmHkij/mvce.rs:14:14
   |
14 | struct Thing(u64);
   |        ----- ^^^
   |        |
   |        field in this struct
   |
   = help: consider removing this field

warning: function `const_generic` is never used
  --> /tmp/icemaker_global_tempdir.L3dNdrnvcGlo/rustc_testrunner_tmpdir_reporting.8ehK9SvmHkij/mvce.rs:26:22
   |
26 | unsafe extern "C" fn const_generic<const N: u64>() {
   |                      ^^^^^^^^^^^^^

error: internal compiler error: /rustc-dev/f26e58023071e71636a3c72ac3a2bf89b1f76706/compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:40:9: #[naked] functions should always terminate with an asm! block


thread 'rustc' panicked at /rustc-dev/f26e58023071e71636a3c72ac3a2bf89b1f76706/compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:40:9:
Box<dyn Any>
stack backtrace:
   0:     0x773530f2e243 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5d4004938ff2c5de
   1:     0x77353160277f - core::fmt::write::he40d39caeedce22d
   2:     0x773530f23e83 - std::io::Write::write_fmt::h6b481595dd1fc53f
   3:     0x773530f2e0a2 - std::sys::backtrace::BacktraceLock::print::h6122e56851fd7e04
   4:     0x773530f31b9a - std::panicking::default_hook::{{closure}}::h5da9a6ee005a6c0c
   5:     0x773530f3171f - std::panicking::default_hook::he77158b4319b132a
   6:     0x7735300095d3 - std[abb3b870cf4d8027]::panicking::update_hook::<alloc[3b9c56f51ca07bea]::boxed::Box<rustc_driver_impl[7eb6cf164257341f]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x773530f323eb - std::panicking::rust_panic_with_hook::hbc48a4f07e431d11
   8:     0x773530043861 - std[abb3b870cf4d8027]::panicking::begin_panic::<rustc_errors[3b19c8b340e0e702]::ExplicitBug>::{closure#0}
   9:     0x773530037d86 - std[abb3b870cf4d8027]::sys::backtrace::__rust_end_short_backtrace::<std[abb3b870cf4d8027]::panicking::begin_panic<rustc_errors[3b19c8b340e0e702]::ExplicitBug>::{closure#0}, !>
  10:     0x773530037c17 - std[abb3b870cf4d8027]::panicking::begin_panic::<rustc_errors[3b19c8b340e0e702]::ExplicitBug>
  11:     0x77353004d341 - <rustc_errors[3b19c8b340e0e702]::diagnostic::BugAbort as rustc_errors[3b19c8b340e0e702]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x77353061900a - rustc_middle[6ca7f7d3ce556234]::util::bug::opt_span_bug_fmt::<rustc_span[376a63540bfd47fc]::span_encoding::Span>::{closure#0}
  13:     0x7735305f8bea - rustc_middle[6ca7f7d3ce556234]::ty::context::tls::with_opt::<rustc_middle[6ca7f7d3ce556234]::util::bug::opt_span_bug_fmt<rustc_span[376a63540bfd47fc]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7735305f8a5b - rustc_middle[6ca7f7d3ce556234]::ty::context::tls::with_context_opt::<rustc_middle[6ca7f7d3ce556234]::ty::context::tls::with_opt<rustc_middle[6ca7f7d3ce556234]::util::bug::opt_span_bug_fmt<rustc_span[376a63540bfd47fc]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x77352d6a7e90 - rustc_middle[6ca7f7d3ce556234]::util::bug::bug_fmt
  16:     0x7735327519a9 - rustc_codegen_llvm[5e38973cde8d21c0]::base::compile_codegen_unit::module_codegen
  17:     0x773532714c4d - <rustc_codegen_llvm[5e38973cde8d21c0]::LlvmCodegenBackend as rustc_codegen_ssa[87a67ccac236a82e]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  18:     0x7735327129b3 - rustc_codegen_ssa[87a67ccac236a82e]::base::codegen_crate::<rustc_codegen_llvm[5e38973cde8d21c0]::LlvmCodegenBackend>
  19:     0x773532837083 - <rustc_codegen_llvm[5e38973cde8d21c0]::LlvmCodegenBackend as rustc_codegen_ssa[87a67ccac236a82e]::traits::backend::CodegenBackend>::codegen_crate
  20:     0x773532836732 - <rustc_interface[f681bac94ac292a9]::queries::Linker>::codegen_and_build_linker
  21:     0x77353282ca87 - rustc_interface[f681bac94ac292a9]::passes::create_and_enter_global_ctxt::<core[7243450d3d38063e]::option::Option<rustc_interface[f681bac94ac292a9]::queries::Linker>, rustc_driver_impl[7eb6cf164257341f]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  22:     0x77353286756f - rustc_interface[f681bac94ac292a9]::interface::run_compiler::<(), rustc_driver_impl[7eb6cf164257341f]::run_compiler::{closure#0}>::{closure#1}
  23:     0x773532807e38 - std[abb3b870cf4d8027]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f681bac94ac292a9]::util::run_in_thread_with_globals<rustc_interface[f681bac94ac292a9]::util::run_in_thread_pool_with_globals<rustc_interface[f681bac94ac292a9]::interface::run_compiler<(), rustc_driver_impl[7eb6cf164257341f]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  24:     0x773532807b16 - <<std[abb3b870cf4d8027]::thread::Builder>::spawn_unchecked_<rustc_interface[f681bac94ac292a9]::util::run_in_thread_with_globals<rustc_interface[f681bac94ac292a9]::util::run_in_thread_pool_with_globals<rustc_interface[f681bac94ac292a9]::interface::run_compiler<(), rustc_driver_impl[7eb6cf164257341f]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[7243450d3d38063e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x77353280ddfd - std::sys::pal::unix::thread::Thread::new::thread_start::h277742a54d34f956
  26:     0x77352c2a57eb - <unknown>
  27:     0x77352c32918c - <unknown>
  28:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.90.0-nightly (f26e58023 2025-06-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=kcfi -C panic=abort -Z dump-mir-dir=dir

query stack during panic:
end of query stack
error: aborting due to 1 previous error; 5 warnings emitted


```

</p>
</details>

@rustbot label +F-abi_custom

### PR DESCRIPTION
**Pull request by folkertdev**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/143293)*

fixes https://github.com/rust-lang/rust/issues/143266

With `-Zsanitizer=kcfi`, indirect calls happen via generated intermediate shim that forwards the call. The generated shim preserves the attributes of the original, including `#[unsafe(naked)]`. The shim is not a naked function though, and violates its invariants (like having a body that consists of a single `naked_asm!` call).

My fix here is to match on the `InstanceKind`, and only use `codegen_naked_asm` when the instance is not a `ReifyShim`. That does beg the question whether there are other `InstanceKind`s that could come up. As far as I can tell the answer is no: calling via `dyn` seems to work find, and `#[track_caller]` is disallowed in combination with `#[naked]`.

r? codegen
@rustbot label +A-naked
cc @maurer @rcvalle

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/mono_item.rs [hunk 1]
```diff
@@ -41,12 +42,12 @@ impl<'a, 'tcx: 'a> MonoItemExt<'a, 'tcx> for MonoItem<'tcx> {
...
-                    .codegen_fn_attrs(instance.def_id())
-                    .flags
-                    .contains(CodegenFnAttrFlags::NAKED)
-                {
+                // A shim used by `-Zsanitizer=kcfi`. Its body is a call to the real function.
+                // The shim should be codegened like a normal function.
+                let is_reify_shim = matches!(instance.def, InstanceKind::ReifyShim(..));
+
+                let flags = cx.tcx().codegen_fn_attrs(instance.def_id()).flags;
+                if flags.contains(CodegenFnAttrFlags::NAKED) && !is_reify_shim {
```
Comment (compiler-errors) [inline compiler/rustc_codegen_ssa/src/mono_item.rs]: reify shims are not the only way to trigger this ICE. For example, vtable shims will trigger this too:

```
use std::arch::naked_asm;

trait MyTrait {
    #[unsafe(naked)]
    extern "C" fn foo(&self) {
        naked_asm!("ret")
    }
}

impl MyTrait for i32 {}

fn main() {
    let x: extern "C" fn(&_) = <dyn MyTrait as MyTrait>::foo;
    x(&1);
}
```

I think this check should be limited to `InstanceKind::Item`, like:

```
if let InstanceKind::Item(def_id) = instance.kind
    && cx.tcx().codegen_fn_attrs(instance.def_id()).flags.contains(NAKED)
{}
```

Rather than filtering out shims explicitly.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors

**Comment by compiler-errors** [comment]
Please also grep for other instances of `.contains(CodegenFnAttrFlags::NAKED)` in the codebase. They may need to be adjusted similarly.

**Comment by compiler-errors** [comment]
This also feels like it deserves a larger refactor, though I wouldn't block this fix on that: I think the `codegen_fn_attrs` query being keyed on `DefId` is a bit of a footgun. Although two `InstanceKind`s may correspond to the same def id, the shims that some of them generate sometimes don't have the same characteristics. Like in this case, both the vtable shim and reify shims should probably not be inheriting the naked attr.

**Comment by compiler-errors** [comment]
(edit: the code I shared above actually is just a non-CFI instance of a reify shim, not a vtable shim, but I think that the point still remains that we may add new shim `InstanceKind`s so codegen attrs being keyed on def id is still a footgun)

**Comment by maurer** [comment]
Came here to post that I think we should have a `codegen_instance_attrs` that takes an instance instead of a `DefId`, that way we could have a different "effective" set of attributes compared to the real ones. I think that's what @compiler-errors has already suggested though.

If we made a `codegen_instance_attrs`, we could then see if it's easy to migrate `codegen_fn_attrs` calls that get tested for `NAKED` to the new method. 

Other attributes that might make sense to have an effective flag strip for some instance kinds include `NO_MANGLE`, `USED_COMPILER`, `USED_LINKER`.

**Comment by compiler-errors** [comment]
> I think that's what @compiler-errors has already suggested though.

Yeah, I agree.

I think it's worth to just migrate all `codegen_fn_attrs` calls. All existing calls (that care about the item itself) would just use `InstanceKind::Item(def_id)`, or they'd migrate to using the instance itself if it has one at hand. 

And it should probably take `InstanceKind`, not `Instance`; there's probably no reason for it to need to have its args included.

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 2]
```diff
@@ -1466,6 +1466,7 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
             }
             if def_kind.has_codegen_attrs() {
                 record!(self.tables.codegen_fn_attrs[def_id] <- self.tcx.codegen_fn_attrs(def_id));
+                record!(self.tables.codegen_instance_attrs[def_id] <- self.tcx.codegen_fn_attrs(def_id));
```
Comment (folkertdev) [inline compiler/rustc_metadata/src/rmeta/encoder.rs]: This does work (for now), but is highly suspicious. I feel like this really should be using `self.tcx.codegen_instance_attrs`, but we don't have the `InstanceKind` available here.

File: compiler/rustc_metadata/src/rmeta/mod.rs [hunk 3]
```diff
@@ -432,6 +432,7 @@ define_tables! {
     variances_of: Table<DefIndex, LazyArray<ty::Variance>>,
     fn_sig: Table<DefIndex, LazyValue<ty::EarlyBinder<'static, ty::PolyFnSig<'static>>>>,
     codegen_fn_attrs: Table<DefIndex, LazyValue<CodegenFnAttrs>>,
+    codegen_instance_attrs: Table<DefIndex, LazyValue<CodegenFnAttrs>>,
```
Comment (folkertdev) [inline compiler/rustc_metadata/src/rmeta/mod.rs]: is keying by `DefIndex` actually correct here?

File: compiler/rustc_middle/src/query/mod.rs [hunk 4]
```diff
@@ -1511,6 +1511,14 @@ rustc_queries! {
         separate_provide_extern
     }
 
+    query codegen_instance_attrs(instance_kind: InstanceKind<'tcx>) -> &'tcx CodegenFnAttrs {
+        desc { |tcx| "computing instance attributes of `{}`", tcx.def_path_str(instance_kind.def_id()) }
+        arena_cache
+        cache_on_disk_if { instance_kind.def_id().is_local() }
+        separate_provide_extern
+        feedable
+    }
```
Comment (folkertdev) [inline compiler/rustc_middle/src/query/mod.rs]: these attributes were just copied from `codegen_fn_attrs`, I'm assuming that makes sense?

**Review by folkertdev — COMMENTED** [review]
I've made an attempt at implementing the `codegen_instance_attrs` query. It does work (locally), but I think it's not quite right yet.

I've also updated the locations where an instance is easily available. That is generally the case in the backend, but in earlier stages it won't be. On the other hand, having `codegen_fn_attrs` available means it's likely to be used by accident. So either it needs a scarier name, or we do translate all occurences to use `InstanceKind::Item`, but that'll be quite verbose.

Anyway, my thinking is that resolving that can be its own PR, and here we can focus just on naked functions and some of the low-hanging fruit.

**Comment by folkertdev** [comment]
> Please also grep for other instances of .contains(CodegenFnAttrFlags::NAKED) in the codebase. They may need to be adjusted similarly.

The only one that's still missing is here:

https://github.com/rust-lang/rust/blob/f51c9870bab634afb9e7a262b6ca7816bb9e940d/compiler/rustc_mir_transform/src/coverage/query.rs#L45-L48

Where I could make up a `InstanceKind::Item` but I suspect that is incorrect.

File: compiler/rustc_codegen_ssa/src/codegen_attrs.rs [hunk 5]
```diff
@@ -54,6 +54,12 @@ fn linkage_by_name(tcx: TyCtxt<'_>, def_id: LocalDefId, name: &str) -> Linkage {
 }
 
 fn codegen_fn_attrs(tcx: TyCtxt<'_>, did: LocalDefId) -> CodegenFnAttrs {
+    codegen_instance_attrs(tcx, InstanceKind::Item(did.to_def_id()))
+}
+
+fn codegen_instance_attrs(tcx: TyCtxt<'_>, instance_kind: InstanceKind<'_>) -> CodegenFnAttrs {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/codegen_attrs.rs]: Maybe `codegen_instance_attrs` could be a regular function that calls the `codegen_fn_attrs` query and drops the naked flag (and any other flags like no_mangle) as necessary depending on the instance kind?

Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs]: For this PR that is probably a nicer solution actually yeah.

Comment (folkertdev) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs]: A downside of that approach is that function has to clone the `CodegenFnAttrs` in order to modify it (the query method returns an immutable reference). I'm not sure how big of a deal that is though?

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/codegen_attrs.rs]: A `Cow<'tcx, CodegenFnAttrs>` could be returned I guess. So only when we actually need to modify the arguments is it necessary to clone it.

**Comment by folkertdev** [comment]
This is ready for review btw, the implementation now uses a `Cow` as suggested to minimize the cloning.

**Review by compiler-errors — APPROVED** [review]
Could you rename `codegen_fn_attrs` to `codegen_fn_attrs_raw`, and suggest in a query doc comment that it's beneficial to use `codegen_instance_attr` during codegen when trying to access the attrs of a called instance, since it may not be a "normal" item but also a shim?

r=me afterwards.

**Comment by compiler-errors** [comment]
@bors delegate+

r=me when green
