### PR TITLE
Suggest associated method on deref types when path syntax method fails

### LINKED ISSUE #100278: Using non-existent associated method doesn't hint about deref
In #100227, someone was a little confused by `<&[T]>::contains` not being accessible as`Vec::<T>::contains`.

Given the following code: [](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1d36dcb34966fbb76466c06ce945bc95)

```rust
fn test() {
    let vec = Vec::new();
    Vec::contains(&vec, &0);
}
```

The current output is:

```
error[E0599]: no function or associated item named `contains` found for struct `Vec<_, _>` in the current scope
 --> src/lib.rs:3:10
  |
3 |     Vec::contains(&vec, &0);
  |          ^^^^^^^^ function or associated item not found in `Vec<_, _>`

For more information about this error, try `rustc --explain E0599`.
```

Ideally, it would add a note about the method being found on a type that `Vec<_, _>` can deref to.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #100278

### CODE REVIEW

File: compiler/rustc_typeck/src/check/method/suggest.rs [hunk 1]
```diff
@@ -1631,6 +1633,62 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                ProbeScope::TraitsInScope,
+            ) {
+                if deref_ty.is_suggestable(self.tcx, true)
+                    // If this method receives `&self`, then the provided
+                    // argument _should_ coerce, so it's valid to suggest
+                    // just changing the path.
+                    && pick.item.fn_has_self_parameter
+                    && let Some(self_ty) =
+                        self.tcx.fn_sig(pick.item.def_id).inputs().skip_binder().get(0)
+                    && self_ty.is_ref()
```
Comment (compiler-errors) [inline compiler/rustc_typeck/src/check/method/suggest.rs:1661]: This is a bit of a strange heuristic, but it works pretty well. Part of the issue here is that we don't have information for the self type.

This is a `MaybeIncorrect` suggestion, so I think it's fine for it to be a bit incorrect, as long as it's not suggesting something wildly wrong.
