### PR TITLE
Refer to "`self` type" instead of "receiver type"

### LINKED ISSUE #42603: An error message should not contain a keyword x such that searching rust + x has 0 relevant results on the first page
Case in point: I get an error:

```
the trait `Foo` cannot be made into an object
....
method add has no receiver
```

I looked up `rust receiver` but couldn't find any relevant results. Upon investigating further, in this case, `method add does not have a self parameter` would be more appropriate.

### PR DESCRIPTION
**Pull request by estebank**
Fix https://github.com/rust-lang/rust/issues/42603.

### CODE REVIEW

File: src/librustc_typeck/error_codes.rs [hunk 1]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
 "##,
 
+E0307: r##"
+This error indicates that the `self` parameter in a method has an invalid
+"reciever type".
+
+Methods take a special first parameter, of which there are three variants:
+`self`, `&self`, and `&mut self`. The type `Self` acts as an alias to the
+type of the current trait implementor, or "receiver type". Besides the
+already mentioned `Self`, `&Self` and `&mut Self` valid receiver types, the
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: You didn't mention them; you mentioned `self`, `&self`, `&mut self`.

File: src/librustc_typeck/error_codes.rs [hunk 2]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
 ```
 "##,
 
+E0307: r##"
+This error indicates that the `self` parameter in a method has an invalid
+"reciever type".
+
+Methods take a special first parameter, of which there are three variants:
+`self`, `&self`, and `&mut self`. The type `Self` acts as an alias to the
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: I think these should be *explained as* sugar for `self: Self`, `self: &Self`, and `self: &mut Self` respectively.

File: src/librustc_typeck/error_codes.rs [hunk 3]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+type of the current trait implementor, or "receiver type". Besides the
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]:
```suggestion
type of the current trait implementer, or "receiver type". Besides the
```

File: src/librustc_typeck/error_codes.rs [hunk 4]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+already mentioned `Self`, `&Self` and `&mut Self` valid receiver types, the
+following are also valid, if less common: `self: Box<Self>`,
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]:
```suggestion
following are also valid: `self: Box<Self>`,
```
don't waste readers attention span on what is and isn't common; instead, indicate it implicitly by putting the less common ones last.

File: src/librustc_typeck/error_codes.rs [hunk 5]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+`self: Rc<Self>`, `self: Arc<Self>`, and `self: Pin<P>` (where P is one of
+the previous types except `Self`).
+
+```
+# struct Foo;
+trait Trait {
+    fn foo(&self);
+//         ^^^^^ this let's you refer to the type that implements this trait
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: No it doesn't; `self` lives only in the value namespace. Only `Self` is the type. (See above re. explaining `self` as sugar)

File: src/librustc_typeck/error_codes.rs [hunk 6]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+}
+impl Trait for Foo {
+//             ^^^ this is the "receiver type"
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: No it isn't; `&'0 Foo` is the receiver type.

File: src/librustc_typeck/error_codes.rs [hunk 7]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+
+The above is equivalent to:
+
+```
+# struct Foo;
+# trait Trait {
+#     fn foo(&self);
+# }
+impl Trait for Foo {
+    fn foo(&self: &Foo) {}
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: `&self: $type` is not valid syntax.

File: src/librustc_typeck/error_codes.rs [hunk 8]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+```compile_fail,E0307
+# struct Foo;
+# struct Bar;
+# trait Trait {
+#     fn foo(&self);
+# }
+impl Trait for Struct {
+    fn foo(&self: &Bar) {}
+}
+```
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: You have said *"When P,"* but I'm waiting for *"then Q"*.
Is it the pharagraph below? That's not clear from the text.

File: src/librustc_typeck/error_codes.rs [hunk 9]
```diff
@@ -2425,6 +2425,83 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+
+The nightly feature [Arbintrary self types][AST] extends the accepted
+receiver type to also include any type that can dereference to `Self`:
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]:
```suggestion
set of receiver types to also include any type that can dereference to `Self`:
```

File: src/librustc/traits/object_safety.rs [hunk 10]
```diff
@@ -47,13 +47,15 @@ impl ObjectSafetyViolation {
...
-                format!("method `{}` has no receiver", name).into(),
-            ObjectSafetyViolation::Method(name, MethodViolationCode::ReferencesSelf) =>
-                format!("method `{}` references the `Self` type \
-                         in its arguments or return type", name).into(),
-            ObjectSafetyViolation::Method(name,
-                                            MethodViolationCode::WhereClauseReferencesSelf(_)) =>
-                format!("method `{}` references the `Self` type in where clauses", name).into(),
+                format!("associated function `{}` has no `self` parameter", name).into(),
+            ObjectSafetyViolation::Method(name, MethodViolationCode::ReferencesSelf) => format!(
+                "method `{}` references the `Self` type in its arguments or return type",
```
Comment (Centril) [inline src/librustc/traits/object_safety.rs]: This change never occurs in the `--bless` and I suspect "arguments" should be "parameters".

File: src/librustc/traits/object_safety.rs [hunk 11]
```diff
@@ -47,13 +47,15 @@ impl ObjectSafetyViolation {
...
+                name,
+            ).into(),
+            ObjectSafetyViolation::Method(
+                name,
+                MethodViolationCode::WhereClauseReferencesSelf(_),
+            ) => format!("method `{}` references the `Self` type in where clauses", name).into(),
```
Comment (Centril) [inline src/librustc/traits/object_safety.rs]: This one doesn't seem to either.

File: src/librustc_typeck/error_codes.rs (hunk 8 above)
Comment (estebank) [reply src/librustc_typeck/error_codes.rs]: I forgot to finish the sentence because I didn't know how to end it ^_^

File: src/librustc_typeck/error_codes.rs (hunk 5 above)
Comment (estebank) [reply src/librustc_typeck/error_codes.rs]: What would be an appropriate one sentence explanation on what `&self` is in the trait?

File: src/librustc/traits/object_safety.rs [hunk 12]
```diff
@@ -46,22 +46,33 @@ impl ObjectSafetyViolation {
...
+            ObjectSafetyViolation::Method(
+                name,
+                MethodViolationCode::WhereClauseReferencesSelf,
+                _,
+            ) => format!("method `{}` references the `Self` type in where clauses", name).into(),
+            ObjectSafetyViolation::Method(name, MethodViolationCode::Generic, _) =>
                 format!("method `{}` has generic type parameters", name).into(),
-            ObjectSafetyViolation::Method(name, MethodViolationCode::UndispatchableReceiver) =>
+            ObjectSafetyViolation::Method(name, MethodViolationCode::UndispatchableReceiver, _) =>
                 format!("method `{}`'s receiver cannot be dispatched on", name).into(),
```
Comment (Centril) [inline src/librustc/traits/object_safety.rs]:
```suggestion
                format!("method `{}`'s `self` parameter cannot be dispatched on", name).into(),
```

File: src/librustc/traits/object_safety.rs (hunk 10 above)
Comment (estebank) [reply src/librustc/traits/object_safety.rs]: [It did](https://github.com/rust-lang/rust/pull/64110/files#diff-acc2dab55a045afa40b3c9e94c09b1a9)? (It should be `parameters,` making the change.)

File: src/librustc/traits/object_safety.rs (hunk 11 above)
Comment (estebank) [reply src/librustc/traits/object_safety.rs]: src/test/ui/issues/issue-50781.stderr should have been updated, running `--bless` again

File: src/librustc/traits/object_safety.rs (hunk 10 above)
Comment (Centril) [reply src/librustc/traits/object_safety.rs]: Not in the first commit (which is what I wrote the comment wrt.) =P

File: src/librustc_typeck/error_codes.rs [hunk 13]
```diff
@@ -2425,6 +2425,85 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+
+```
+# struct Foo;
+trait Trait {
+    fn foo(&self);
+}
+
+impl Trait for Foo {
+    fn foo(&self) {}
+//         ^^^^^ this the receiver type `&Foo`
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]:
```suggestion
//         ^^^^^ the receiver type is `&Foo`
```

File: src/librustc_typeck/error_codes.rs [hunk 14]
```diff
@@ -2425,6 +2425,85 @@ struct Bar<S, T> { x: Foo<S, T> }
...
+"reciever type".
+
+Methods take a special first parameter, of which there are three variants:
+`self`, `&self`, and `&mut self`. These are syntactic sugar for
+`self: Self`, `self: &Self`, and `self: &mut Self` respectively. The type
+`Self` acts as an alias to the type of the current trait implementer, or
+"receiver type". Besides the already mentioned `Self`, `&Self` and
+`&mut Self` valid receiver types, the following are also valid:
+`self: Box<Self>`, `self: Rc<Self>`, `self: Arc<Self>`, and `self: Pin<P>`
+(where P is one of the previous types except `Self`).
```
Comment (Centril) [inline src/librustc_typeck/error_codes.rs]: Hmm; is it sufficiently clear here that `self: Box<Self>` is not meant literally (e.g. `self: Box<Foo>` is fine as well)?

File: src/librustc_typeck/error_codes.rs (hunk 5 above)
Comment (Centril) [reply src/librustc_typeck/error_codes.rs]: "`self` here is a reference to the receiver object" maybe?

File: src/librustc/traits/object_safety.rs (hunk 10 above)
Comment (estebank) [reply src/librustc/traits/object_safety.rs]: :)

File: src/librustc/traits/object_safety.rs [hunk 15]
```diff
@@ -67,9 +67,9 @@ impl ObjectSafetyViolation {
     }
 
     pub fn span(&self) -> Option<Span> {
-        match self {
+        match *self {
             ObjectSafetyViolation::AssocConst(_, span) |
-            ObjectSafetyViolation::Method(_, _, span) => Some(*span),
+            ObjectSafetyViolation::Method(_, _, span) if span != DUMMY_SP => Some(span),
```
Comment (Centril) [inline src/librustc/traits/object_safety.rs]: Can you explain this change? Why does `DUMMY_SP` occur?

File: src/librustc_typeck/error_codes.rs (hunk 14 above)
Comment (estebank) [reply src/librustc_typeck/error_codes.rs]: This copy is taken from the current diagnostic, so if we should change it too. What about "a type that _can be_ Self". Then again, the extended explanation should probably go in the book and linked from the error code index.

File: src/librustc/traits/object_safety.rs (hunk 15 above)
Comment (estebank) [reply src/librustc/traits/object_safety.rs]: When the trait is from a different crate. One of the tests that got `bless`ed in the last commit recover a `note` that had gone away. Sadly `DUMMY_SP` are way too common still.

**Comment by estebank** [comment]
@Centril I'm torn on whether to call it "`self`-parameter type" or the current "`self` parameter type".

**Comment by Centril** [comment]
> @Centril I'm torn on whether to call it "`self`-parameter type" or the current "`self` parameter type".

I think @alexreg is best placed to evaluate this. =P

File: src/librustc_typeck/error_codes.rs (hunk 14 above)
Comment (Centril) [reply src/librustc_typeck/error_codes.rs]: Maybe we could instead add a sentence: "Note that `Self` is not meant literally here. Any type which resolves to the underlying implementing type is fine."?

File: src/librustc/traits/object_safety.rs (hunk 15 above)
Comment (Centril) [reply src/librustc/traits/object_safety.rs]: Ah; could you transcribe your note here to a comment in the code?

File: src/librustc_typeck/error_codes.rs (hunk 14 above)
Comment (estebank) [reply src/librustc_typeck/error_codes.rs]: "Note that `Self` can also be the underlying implementing type, like `Foo` in the following example."

Comment (Centril) [reply src/librustc_typeck/error_codes.rs]: 👍 -- better to connect to an example.

**Comment by Centril** [comment]
> I think @alexreg is best placed to evaluate this. =P

But I read https://www.grammarbook.com/punctuation/hyphens.asp and https://www.grammarly.com/blog/hyphen/ which suggest that "self-parameter type" is correct.
