### PR TITLE
codegen, miri: fix computing the offset of an unsized field in a packed struct

### LINKED ISSUE #3200: We are computing the wrong offsets for unsized packed structs
This assertion passes with rustc but not with Miri:
```rust
use std::mem;

#[repr(packed, C)]
struct PackedSized {
    f: u8,
    d: [u32; 4],
}

#[repr(packed, C)]
struct PackedUnsized {
    f: u8,
    d: [u32],
}

impl PackedSized {
    fn unsize(&self) -> &PackedUnsized {
        // We can't unsize via a generic type since then we get the error
        // that packed structs with unsized tail don't work if the tail
        // might need dropping.
        let len = 4usize;
        unsafe { mem::transmute((self, len)) }
    }
}

fn main() { unsafe {
    let p = PackedSized { f: 0, d: [1, 2, 3, 4] };
    let p = p.unsize() as *const PackedUnsized;
    let d = std::ptr::addr_of!((*p).d);
    assert_eq!(d.cast::<u32>().read_unaligned(), 1);
} }
```

### LINKED ISSUE #118537: We are computing the wrong offset for unsized packed structs
This code panics, but it should not:
```rust
use std::mem;

struct Slice([u32]);

#[repr(packed, C)]
struct PackedSized {
    f: u8,
    d: [u32; 4],
}

#[repr(packed, C)]
struct PackedUnsized {
    f: u8,
    d: Slice,
}

impl PackedSized {
    fn unsize(&self) -> &PackedUnsized {
        // We can't unsize via a generic type since then we get the error
        // that packed structs with unsized tail don't work if the tail
        // might need dropping.
        let len = 4usize;
        unsafe { mem::transmute((self, len)) }
    }
}

fn main() { unsafe {
    let p = PackedSized { f: 0, d: [1, 2, 3, 4] };
    let p = p.unsize() as *const PackedUnsized;
    let d = std::ptr::addr_of!((*p).d);
    assert_eq!(d.cast::<u32>().read_unaligned(), 1);
} }
```

The panic disappears when the `Newtype` is inlined (because then we hit a different code path in [this match](https://github.com/rust-lang/rust/blob/c089a162d80dbbcc0543649fa78ccabac569db81/compiler/rustc_codegen_ssa/src/mir/place.rs#L147-L166)).

What happens here is a bug in the logic that computes the offset of `d`: since it is an unsized field, the offset is computed dynamically, by taking the statically known offset and then rounding it up to the dynamic alignment of the field. However, since the struct is packed, we need to cap the dynamic alignment of the field to the packing of the surrounding struct -- which we currently do not do. This is just yet another case where the non-compositional nature of `repr(packed)` is causing issues...

### PR DESCRIPTION
**Pull request by RalfJung**
`#[repr(packed)]`  strikes again.

Fixes https://github.com/rust-lang/rust/issues/118537
Fixes https://github.com/rust-lang/miri/issues/3200

@bjorn3 I assume cranelift needs the same fix.

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/mir/place.rs [hunk 1]
```diff
@@ -154,14 +153,6 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
             }
             _ if field.is_sized() => return simple(),
             ty::Slice(..) | ty::Str | ty::Foreign(..) => return simple(),
-            ty::Adt(def, _) => {
-                if def.repr().packed() {
```
Comment (RalfJung) [inline compiler/rustc_codegen_ssa/src/mir/place.rs:158]: We could have tried to preserve this fast-path for some packed structs, but I don't think that's worth it.

**Comment by apiraino** [comment]
r? compiler

**Comment by RalfJung** [comment]
@WaffleLapkin should this one also be marked as "relnotes"?

**Comment by WaffleLapkin** [comment]
@RalfJung I think so

**Comment by RalfJung** [comment]
For the relnotes this should probably be grouped with https://github.com/rust-lang/rust/pull/118538. One fixes the logic for computing the offset of an unsized field in a packed struct, the other fixes the logic for computing the size and alignment of an unsized packed struct.
