### PR TITLE
wf: handle "livelock" checking before reaching `WfPredicates::compute`.

### LINKED ISSUE #70168: Potential WF unsoundness: predicate_obligations doesn't check compute's return type.
`WfPredicates::compute` returns `false` if it can't make progress on an inference variable, and the original obligation should be retried later.
*However*, `wf::predicate_obligations` doesn't check that return type and may (incorrectly) return no obligations.

On #70107 I suggested this:
> Maybe it would be better to have a `struct NoProgress;` and `compute` return `Result<(), NoProgress>` instead of `bool`.

I'm pretty sure now that it would've prevented this bug.

<hr/>

Looking at the users, only `wfcheck` uses this function, and only for the user-specified bounds, so it's possible inference variables are impossible to find (unless normalization introduces them, I guess?).
It might be fine to just create `WellFormed` obligation for the `ty::Infer` instead of bailing out (see below, this is the same as moving `return false` out of `WfPredicats::compute`)

<hr/>

~~Related, this looks wrong, or perhaps outdated?~~
https://github.com/rust-lang/rust/blob/f4c675c476c18b1a11041193f2f59d695b126bc8/src/librustc_trait_selection/traits/wf.rs#L591

It's true that `ty::Infer` can't be found *as the first type* in the recursive call, but `compute` is a `loop`, and it uses `Ty::walk`.
~~I'm amazed nobody has triggered this assert by e.g. causing an inference variable to be unified with `Vec<_>`, how is that possible?~~

~~Maybe `ty::Infer` should only cause `return false` (i.e. `return Err(NoProgress)`) for `ty0`), not any of its descendants?~~

(**EDIT**: Read the code more carefully and the check is `ty == ty0`, so while it's not an early like I would prefer, it does seem to only trigger on the root type)

However, a few other things call `WfPredicats::compute` and it would be fine for them to create an obligation rather than erroring out, so maybe `wf::obligations` itself should do that check?

cc @nikomatsakis @matthewjasper

### PR DESCRIPTION
**Pull request by eddyb**
For `wf::obligations`'s "livelock" handling, this PR shouldn't cause any behavioral changes, as the check moved to it should be equivalent to the old one in `WfPredicates::compute`.

However, it fixes #70168 by making *other* users of `WfPredicates::compute` (that is, `wf::predicate_obligations` and `compute`'s own upvar handling) correct for `ty::Infer`, in that they now get a `WellFormed(ty::Infer(_))` obligation instead of silently ignoring the type.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
(I forgot to push some comment tweaks, hopefully it doesn't kill the try build)

**Comment by eddyb** [comment]
@rust-timer build 05f512090ead730e044e52571dba2da5ff8f9dcf

**Comment by eddyb** [comment]
The worst regression, [`clap-rs-check` clean](https://perf.rust-lang.org/detailed-query.html?commit=05f512090ead730e044e52571dba2da5ff8f9dcf&base_commit=f4c675c476c18b1a11041193f2f59d695b126bc8&benchmark=clap-rs-check&run_name=clean) has 143 less `specializes` calls? What's up with *that*?
But `typeck_tables_of` getting slower makes sense, and [`clap-rs-debug` clean](https://perf.rust-lang.org/detailed-query.html?commit=05f512090ead730e044e52571dba2da5ff8f9dcf&base_commit=f4c675c476c18b1a11041193f2f59d695b126bc8&benchmark=clap-rs-debug&run_name=clean) also has that.

I guess I'll try to come up with a synthetic stress test that hits the worst case of this PR (`wf::obligations` with `ty::Infer` that resolves to a different `ty::Infer`), and see what I can do to alleviate it.

But still, 7.5% regression of `typeck_tables_of`, from this change? That means a lot of `clap-rs`' type-checking time is spent on solving WF obligations.

File: src/librustc_trait_selection/traits/wf.rs [hunk 1]
```diff
@@ -504,8 +519,9 @@ impl<'a, 'tcx> WfPredicates<'a, 'tcx> {
                     // are not directly inspecting closure types
                     // anyway, except via auto trait matching (which
                     // only inspects the upvar types).
-                    subtys.skip_current_subtree(); // subtree handled by compute_projection
+                    walker.skip_current_subtree(); // subtree handled below
                     for upvar_ty in substs.as_closure().upvar_tys() {
+                        // FIXME(eddyb) add the type to `walker` instead of recursing.
                         self.compute(upvar_ty);
```
Comment (eddyb) [inline src/librustc_trait_selection/traits/wf.rs:525]: Wait I forgot about this, this is technically a bugfix (before, if `compute` returned `false` here, those inference variables would be forgotten about).

So it might make sense that it's slower. Let me, uh, make a PR that only changes this, and check that for perf regressions.

Comment (eddyb) [reply src/librustc_trait_selection/traits/wf.rs:525]: This is it.

`typeck_tables_of` on `clap-rs` gets slightly faster (instead of being a significant regression), if I ignore upvar types that are `ty::Infer(ty::TyVar(_))` and don't resolve.

But that's a WF hole, right? Do we just accept the regression?

**Comment by eddyb** [comment]
I added some fast paths, let's see if they improve anything (but also see https://github.com/rust-lang/rust/pull/70170#discussion_r402910049):

@bors try @rust-timer queue

**Comment by eddyb** [comment]
Hehe, I think my second PR, `wf: {Int,Float}Var can only infer to always-WF ints/floats.`, made the old macro-expanded version of `inflate` that `perf.rust-lang.org` tests, significantly faster to compile, it seems, so I guess it was spending a lot of time on WF-ing `ty::IntVar`s?

I'm not surprised, there were *a lot* of macro-replicated integer literals in that code.

File: src/librustc_trait_selection/traits/wf.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_trait_selection/traits/wf.rs:525]: Sorry, I lost track of this PR. I agree that this is a bug-fix.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I'm inclined to merge this PR @eddyb -- r=me on the code itself -- the clap-rs-debug perf regression seems small and I agree it's a bug fix, and there are some significant (albeit somewhat surprising?) improvements, too. I guess your explanation makes sense, though.

**Comment by eddyb** [comment]
Let's get some new numbers, post-https://github.com/rust-lang/rustc-perf/pull/645:

@bors try @rust-timer queue
