### PR TITLE
deduplicate the rest of AST walker functions

### LINKED ISSUE #139825: ICE: failed to process buffered lint here (dummy = false)`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --check-cfg=cfg(docsrs,test)
type FnGood = for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> fn(yes); // OK
type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(FALSE);

type PolyGood = dyn for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> Copy; // OK
type PolyBad = dyn for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> Copy;

struct WhereGood
where
    for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> u8: Copy; // OK

// OK

// OK

// OK

// OK

// OK

````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ compile-flags:--cfg yes --check-cfg=cfg(yes,no)

fn f_lt<#[cfg(yes)] 'a: 'a, #[cfg(FALSE)] T>() {}
fn f_ty<#[cfg(FALSE)] 'a: 'a, #[cfg(yes)] T>() {}

type FnGood = for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> fn(); // OK
type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn();
//~^ ERROR only lifetime parameters can be used in this context

type PolyGood = dyn for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> Copy; // OK
type PolyBad = dyn for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> Copy;
//~^ ERROR only lifetime parameters can be used in this context

struct WhereGood where for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> u8: Copy; // OK
struct WhereBad where for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> u8: Copy;
//~^ ERROR only lifetime parameters can be used in this context

fn f_lt_no<#[cfg_attr(FALSE, unknown)] 'a>() {} // OK
fn f_lt_yes<#[cfg_attr(yes, unknown)] 'a>() {}
//~^ ERROR cannot find attribute `unknown` in this scope
fn f_ty_no<#[cfg_attr(FALSE, unknown)] T>() {} // OK
fn f_ty_yes<#[cfg_attr(yes, unknown)] T>() {}
//~^ ERROR cannot find attribute `unknown` in this scope

type FnNo = for<#[cfg_attr(FALSE, unknown)] 'a> fn(); // OK
type FnYes = for<#[cfg_attr(yes, unknown)] 'a> fn();
//~^ ERROR cannot find attribute `unknown` in this scope

type PolyNo = dyn for<#[cfg_attr(FALSE, unknown)] 'a> Copy; // OK
type PolyYes = dyn for<#[cfg_attr(yes, unknown)] 'a> Copy;
//~^ ERROR cannot find attribute `unknown` in this scope

struct WhereNo where for<#[cfg_attr(FALSE, unknown)] 'a> u8: Copy; // OK
struct WhereYes where for<#[cfg_attr(yes, unknown)] 'a> u8: Copy;
//~^ ERROR cannot find attribute `unknown` in this scope

fn main() {
    f_lt::<'static>();
    f_ty::<u8>();
}

````
</p>
</details>

Version information
````
rustc 1.88.0-nightly (07d3fd1d9 2025-04-14)
binary: rustc
commit-hash: 07d3fd1d9b9c1f07475b96a9d168564bf528db68
commit-date: 2025-04-14
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --check-cfg=cfg(docsrs,test)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `yes` in this scope
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:1:55
  |
1 | type FnGood = for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> fn(yes); // OK
  |                                                       ^^^ not found in this scope

error[E0412]: cannot find type `FALSE` in this scope
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:2:54
  |
2 | type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(FALSE);
  |                                                      ^^^^^ not found in this scope
  |
help: you may want to use a bool value instead
  |
2 - type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(FALSE);
2 + type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(false);
  |

warning: unexpected `cfg` condition name: `yes`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:1:25
  |
1 | type FnGood = for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> fn(yes); // OK
  |                         ^^^
  |
  = help: expected names are: `docsrs` and `test` and 31 more
  = help: to expect this configuration use `--check-cfg=cfg(yes)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default

warning: unexpected `cfg` condition name: `FALSE`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:1:41
  |
1 | type FnGood = for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> fn(yes); // OK
  |                                         ^^^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `FALSE`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:2:24
  |
2 | type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(FALSE);
  |                        ^^^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `yes`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:2:42
  |
2 | type FnBad = for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> fn(FALSE);
  |                                          ^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(yes)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `yes`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:4:31
  |
4 | type PolyGood = dyn for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> Copy; // OK
  |                               ^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(yes)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `FALSE`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:4:47
  |
4 | type PolyGood = dyn for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> Copy; // OK
  |                                               ^^^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `FALSE`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:5:30
  |
5 | type PolyBad = dyn for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> Copy;
  |                              ^^^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `yes`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:5:48
  |
5 | type PolyBad = dyn for<#[cfg(FALSE)] 'a, #[cfg(yes)] T> Copy;
  |                                                ^^^
  |
  = help: to expect this configuration use `--check-cfg=cfg(yes)`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs:9:51
  |
9 |     for<#[cfg(yes)] 'a, #[cfg(FALSE)] T> u8: Copy; // OK
  |                                                   ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.DgZc43XxscLa/rustc_testrunner_tmpdir_reporting.d8TE3zkji74S/mvce.rs`

error: aborting due to 3 previous errors; 8 warnings emitted

Some errors have detailed explanations: E0412, E0601.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by fee1-dead**
After this, we can tidy things up and deduplicate the visitor traits themselves too.

Fixes rust-lang/rust#139825, apparently
 
r? @oli-obk

### CODE REVIEW

**Comment by cjgillot** [comment]
Any idea which change fixes the crash?

File: compiler/rustc_ast/src/visit.rs [hunk 1]
```diff
@@ -1075,573 +1077,640 @@ macro_rules! common_visitor_and_walkers {
...
-        GenericArg::Const(ct) => visitor.visit_anon_const(ct),
-    }
-}
+        pub fn walk_generic_param<$($lt,)? V: $Visitor$(<$lt>)?>(
+            vis: &mut V,
+            param: &$($lt)? $($mut)? GenericParam,
+        ) -> V::Result {
+            let GenericParam { id, ident, attrs, bounds, is_placeholder: _, kind, colon_span } =
+                param;
+            try_visit!(visit_id(vis, id));
```
Comment (oli-obk) [inline compiler/rustc_ast/src/visit.rs:1169]: I think this fixes the bug (`visit_id` being called more reliably), but other cases may also be visiting the ids more correctly now. We can now change the `EarlyContextAndPass` lint pass to not implement all the `visit` methods anymore but just rely on `visit_id` instead.

**Review by oli-obk — APPROVED** [review]

File: compiler/rustc_ast/src/visit.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/visit.rs:1169]: Gonna take a look.

**Comment by fmease** [comment]
@fee1-dead This had a negative perf impact (found out in rollup https://github.com/rust-lang/rust/pull/142299).

Pasting https://github.com/rust-lang/rust/pull/142299#issuecomment-2964373988 below:

---

Finished benchmarking commit (294d66c266c83139d525116a1b1addba75f318a4): [comparison URL](https://perf.rust-lang.org/compare.html?start=c6a955468b025dbe3d1de3e8f3e30496d1fb7f40&end=294d66c266c83139d525116a1b1addba75f318a4&stat=instructions:u).

### Overall result: ❌ regressions - please read the text below




### [Instruction count](https://perf.rust-lang.org/compare.html?start=c6a955468b025dbe3d1de3e8f3e30496d1fb7f40&end=294d66c266c83139d525116a1b1addba75f318a4&stat=instructions:u)
Our most reliable metric. Used to determine the overall result above. However, even this metric can be noisy.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.5% | [0.1%, 0.7%] | 9     |
| Regressions ❌ <br /> (secondary)  | 0.4% | [0.2%, 1.1%] | 36    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.5% | [0.1%, 0.7%] | 9     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=c6a955468b025dbe3d1de3e8f3e30496d1fb7f40&end=294d66c266c83139d525116a1b1addba75f318a4&stat=max-rss)
<details>
<summary>Results (secondary 8.3%)</summary>

A less reliable metric. May be of interest, but not used to determine the overall result above.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 8.3% | [8.3%, 8.3%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=c6a955468b025dbe3d1de3e8f3e30496d1fb7f40&end=294d66c266c83139d525116a1b1addba75f318a4&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=c6a955468b025dbe3d1de3e8f3e30496d1fb7f40&end=294d66c266c83139d525116a1b1addba75f318a4&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 754.321s -> 755.502s (0.16%)
**Artifact size**: 372.15 MiB -> 372.15 MiB (-0.00%)

**Comment by fee1-dead** [comment]
perf note: The regression will be fixed in #142398
