### PR TITLE
Simplify polonius location-sensitive analysis

### LINKED ISSUE #135646: ICE: polonius:  `None` in region infer with unconditional panic
not sure why this only panics in edition 2024 🤔 

auto-reduced (treereduce-rust):
````rust
//@compile-flags: --edition=2024 -Zpolonius=next
fn main() {
    &{ [1, 2, 3][4] };
}

````

original:
````rust
//@ build-pass
//@ ignore-pass (test emits codegen-time warnings and verifies that they are not errors)

#![warn(unconditional_panic)]

fn main() {
    &{ [1, 2, 3][4] };
    //~^ WARN operation will panic
}

````

Version information
````
rustc 1.86.0-nightly (bcd0683e5 2025-01-17)
binary: rustc
commit-hash: bcd0683e5dce1945b5d940714742e7502883bb5c
commit-date: 2025-01-17
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/bcd0683e5dce1945b5d940714742e7502883bb5c/compiler/rustc_borrowck/src/region_infer/mod.rs#L1882-L1894

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2024 -Zpolonius=next`

<details><summary><strong>Program output</strong></summary>
<p>

```

thread 'rustc' panicked at compiler/rustc_borrowck/src/region_infer/mod.rs:1888:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7077524fb0ca - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h245d3d13c9e117ef
   1:     0x707752c12d26 - core::fmt::write::ha5c79450f6a60aba
   2:     0x707753b95891 - std::io::Write::write_fmt::hc0bb623be5e87022
   3:     0x7077524faf22 - std::sys::backtrace::BacktraceLock::print::h5f0375c539e6bbfe
   4:     0x7077524fd3a2 - std::panicking::default_hook::{{closure}}::hfaae0dc7005f1f46
   5:     0x7077524fd22a - std::panicking::default_hook::had3887552141764d
   6:     0x70775165e33b - std[970739192a5a8910]::panicking::update_hook::<alloc[c190f769f0908da9]::boxed::Box<rustc_driver_impl[98a1c83b91f31d14]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7077524fdee3 - std::panicking::rust_panic_with_hook::h0f6e30840497503a
   8:     0x7077524fdba6 - std::panicking::begin_panic_handler::{{closure}}::h00d1f33c4abe282b
   9:     0x7077524fb5a9 - std::sys::backtrace::__rust_end_short_backtrace::h7f80f131d37aefa4
  10:     0x7077524fd89d - rust_begin_unwind
  11:     0x70774f1a8530 - core::panicking::panic_fmt::h313dbd2ed26f8657
  12:     0x70774fcc082c - core::panicking::panic::h6bed83e7eae20130
  13:     0x70775067d5a9 - core::option::unwrap_failed::h5e1ae1d3b98bd9cb
  14:     0x70775143be47 - <rustc_borrowck[4bd42f5d1352065e]::region_infer::RegionInferenceContext>::find_sub_region_live_at
  15:     0x707750fd0fb4 - <rustc_borrowck[4bd42f5d1352065e]::MirBorrowckCtxt>::explain_why_borrow_contains_point
  16:     0x707750e18b6b - <rustc_borrowck[4bd42f5d1352065e]::MirBorrowckCtxt>::report_borrowed_value_does_not_live_long_enough
  17:     0x707753cf134f - rustc_borrowck[4bd42f5d1352065e]::do_mir_borrowck
  18:     0x707753cc352f - rustc_query_impl[a1940b4b03f25947]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a1940b4b03f25947]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a423a87a2792eea]::query::erase::Erased<[u8; 8usize]>>
  19:     0x707752f2260e - rustc_query_system[f87afe778d5ed02f]::query::plumbing::try_execute_query::<rustc_query_impl[a1940b4b03f25947]::DynamicConfig<rustc_data_structures[7c7a3305c98b4df4]::vec_cache::VecCache<rustc_span[e90766ed4fb19497]::def_id::LocalDefId, rustc_middle[1a423a87a2792eea]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f87afe778d5ed02f]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a1940b4b03f25947]::plumbing::QueryCtxt, false>
  20:     0x707752f22113 - rustc_query_impl[a1940b4b03f25947]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  21:     0x707752f16fb0 - rustc_interface[f2cc204a1e18dc42]::passes::run_required_analyses
  22:     0x707753b9109e - rustc_interface[f2cc204a1e18dc42]::passes::analysis
  23:     0x707753b9106f - rustc_query_impl[a1940b4b03f25947]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a1940b4b03f25947]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a423a87a2792eea]::query::erase::Erased<[u8; 0usize]>>
  24:     0x707753be8355 - rustc_query_system[f87afe778d5ed02f]::query::plumbing::try_execute_query::<rustc_query_impl[a1940b4b03f25947]::DynamicConfig<rustc_query_system[f87afe778d5ed02f]::query::caches::SingleCache<rustc_middle[1a423a87a2792eea]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[a1940b4b03f25947]::plumbing::QueryCtxt, false>
  25:     0x707753be808e - rustc_query_impl[a1940b4b03f25947]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  26:     0x707753c5c2e9 - rustc_interface[f2cc204a1e18dc42]::passes::create_and_enter_global_ctxt::<core[31d5326fba56f7df]::option::Option<rustc_interface[f2cc204a1e18dc42]::queries::Linker>, rustc_driver_impl[98a1c83b91f31d14]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  27:     0x707753c4f4d6 - rustc_interface[f2cc204a1e18dc42]::interface::run_compiler::<(), rustc_driver_impl[98a1c83b91f31d14]::run_compiler::{closure#0}>::{closure#1}
  28:     0x707753a92c07 - std[970739192a5a8910]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f2cc204a1e18dc42]::util::run_in_thread_with_globals<rustc_interface[f2cc204a1e18dc42]::util::run_in_thread_pool_with_globals<rustc_interface[f2cc204a1e18dc42]::interface::run_compiler<(), rustc_driver_impl[98a1c83b91f31d14]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  29:     0x707753a928d9 - <<std[970739192a5a8910]::thread::Builder>::spawn_unchecked_<rustc_interface[f2cc204a1e18dc42]::util::run_in_thread_with_globals<rustc_interface[f2cc204a1e18dc42]::util::run_in_thread_pool_with_globals<rustc_interface[f2cc204a1e18dc42]::interface::run_compiler<(), rustc_driver_impl[98a1c83b91f31d14]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[31d5326fba56f7df]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x707753a9206b - std::sys::pal::unix::thread::Thread::new::thread_start::h84cef28dceb72f89
  31:     0x70774dea339d - <unknown>
  32:     0x70774df2849c - <unknown>
  33:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.86.0-nightly (bcd0683e5 2025-01-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polonius=next -Z dump-mir-dir=dir

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by lqd**
This PR reworks the location-sensitive analysis into what we think is a worthwhile subset of the datalog analysis. A sort of polonius alpha analysis that handles NLL problem case 3 and more, but is still using the faster "reachability as an approximation of liveness", as well as the same loans-in-scope computation as NLLs -- and thus doesn't handle full flow-sensitivity like the datalog implementation.

In the last few months, we've identified this subset as being actionable:
- we believe we can make a stabilizable version of this analysis
- it is an improvement over the status quo
- it can also be modeled in a-mir-formality, or some other formalism, for assurances about soundness, and I believe @nikomatsakis is interested in looking into this during H2.
- and we've identified the areas of work we wish to explore later to gradually expand the supported cases: the differences between reachability and liveness, support of kills, and considerations of time-traveling, for example.

The approach in this PR is to try less to have the graph only represent live paths, by checking whether we reach a live region during traversal and recording the loan as live there, instead of equating traversal with liveness like today because it has subtleties with the typeck edges in statements (that could forward loans to the successor point without ensuring their liveness). We can then also simplify these typeck stmt edges. And we also can simplify traversal by removing looking at kills, because that's enough to handle a bunch of NLL problem 3 cases -- and we can gradually support them more and more in traversal in the future, to reduce the approximation of liveness.

There's still some in-progress pieces of work w/r/t opaque types that I'm expecting [lcnr's opaque types rework](https://github.com/rust-lang/rust/pull/139587), and [amanda's SCCs rework](https://github.com/rust-lang/rust/pull/130227) to handle. That didn't seem to show up in tests until I rebased today (and shows lack of test coverage once again) when https://github.com/rust-lang/rust/pull/142255 introduced a couple of test failures with the new captures rules from edition 2024. It's not unexpected since we know more work is needed with member constraints (and we're not even using SCCs in this prototype yet)

I'll look into these anyways, both for future work, and checking how these other 2 PRs would change things.

---

I'm not sure the following means a lot until we have some formalism in-place, but:
- I've changed the polonius compare-mode to use this analysis: the tests pass with it, except 2 cases with minor diagnostics differences, and the 2 edition 2024 opaque types one I mentioned above and need to investigate
- things that are expected to work still do work: it bootstraps, can run our rustc-perf benchmarks (and the results are not even that bad), and a crater run didn't find any regressions (forgetting that crater currently fails to test around a quarter of all crates 👼)
- I've added tests with improvements, like the NLL problem case 3 and others, as well as some that behave the same as NLLs today and are thus worse than the datalog implementation

r? @jackh726 

(no rush I know you're deep in phd work and "implmentating" the new trait solver for r-a :p <3)

This also fixes rust-lang/rust#135646, a diagnostics ICE from the previous implementation.

### CODE REVIEW

**Comment by jackh726** [comment]
Happy to review, but don't expect it for 2 weeks :)

File: tests/ui/nll/issue-46589.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 //@ ignore-compare-mode-polonius (explicit revisions)
 //@ revisions: nll polonius_next polonius
-//@ [polonius_next] check-pass
+//@ [polonius_next] check-fail
```
Comment (jackh726) [inline tests/ui/nll/issue-46589.rs]: *Should* this pass? If so, then we should utilize `known_bug`

File: tests/ui/nll/polonius/nll-problem-case-3.rs [hunk 2]
```diff
@@ -0,0 +1,244 @@
+// This is a collection of regression tests related to the NLL problem case 3 that was deferred from
+// the implementation of the NLL RFC, and left to be implemented by polonius. Most of them are from
+// open issues, e.g. tagged fixed-by-polonius, to ensure that the polonius alpha analysis does
+// handle them, as does the datalog implementation.
+
+//@ check-pass
```
Comment (jackh726) [inline tests/ui/nll/polonius/nll-problem-case-3.rs]: Similarly, can we add this as a known_bug test for NLL? This could even be done in a separate PR

**Review by jackh726 — CHANGES_REQUESTED** [review]
First thought: there are a bunch of really useful tests added here. I'd really like to see them added separately, covering nll, polonius-legacy, and polonius-next. You can use known-bug as appropriate.

File: tests/ui/nll/issue-46589.rs (hunk 1 above)
Comment (lqd) [reply tests/ui/nll/issue-46589.rs]: In some hypothetical longer-term future with full flow sensitivity and infinite development resources, yes :3. Otherwise, not in the current plans.

**Comment by lqd** [comment]
Could you expand on how useful having known-bug tests is for things that we don’t support yet and have open issues?

I guess you mean in another PR with "separately"?

File: tests/ui/nll/issue-46589.rs (hunk 1 above)
Comment (jackh726) [reply tests/ui/nll/issue-46589.rs]: I guess it's really a question of what's in scope for `known-bug` 😛 For things like polonius, where it's like "it works exactly like it's intended, but we want it to not work this way", it's on the edge. In my mind, if there's an issue for it, then it's `known-bug`.

File: tests/ui/nll/polonius/nll-problem-case-3.rs (hunk 2 above)
Comment (lqd) [reply tests/ui/nll/polonius/nll-problem-case-3.rs]: Done in #145053

File: tests/ui/nll/issue-46589.rs (hunk 1 above)
Comment (lqd) [reply tests/ui/nll/issue-46589.rs]: Done in this PR.

**Comment by lqd** [comment]
Rebased to remove and update the tests now that #145053 has landed.

**Comment by jackh726** [comment]
Seems good to me.

@bors r+
