### PR TITLE
Generate synthetic region from `impl` even in closure body within an associated fn

### LINKED ISSUE #102209: ICE during borrow check HRTB & Self type
### Code

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=03575f5ac3e8419c0bd8efb8bd1846f5

```rs
use std::marker::PhantomData;

pub struct NfaBuilder<'brand> {
    brand: PhantomData<&'brand mut &'brand mut ()>,
}

impl NfaBuilder<'_> {
    pub fn with<R, F: FnOnce(NfaBuilder<'_>) -> R>(f: F) -> R {
        Brand::with(|brand| {
            // This should be using NfaBuilder instead of Self becuase they have diffrent lifetime constraints
            f(Self {
                brand: brand.lt,
            })
        })
    }
}

#[derive(Clone, Copy)]
pub struct Brand<'brand> {
    lt: PhantomData<&'brand mut &'brand mut ()>,
}

impl Brand<'_> {
    pub fn with<R, F: FnOnce(Brand<'_>) -> R>(f: F) -> R {
        f(Self { lt: PhantomData })
    }
}
```

### Meta

`rustc --version --verbose`:
```
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_borrowck/src/diagnostics/region_errors.rs:691:70
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_borrowck/src/diagnostics/region_errors.rs:691:70
stack backtrace:
   0:        0x102baf978 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
   1:        0x102bfc828 - core::fmt::write::hda8e8eb84b49cbfc
   2:        0x102ba2c74 - std::io::Write::write_fmt::hb84c8996aec7120c
   3:        0x102bb25d0 - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
   4:        0x102bb2334 - std::panicking::default_hook::hd7ceb942fff7b170
   5:        0x10a1fcd9c - rustc_driver[8f8caae8abf9e6c7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x102bb2ba4 - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
   7:        0x102bb2a04 - std::panicking::begin_panic_handler::{{closure}}::hea9e6c546a23e8ff
   8:        0x102bafe54 - std::sys_common::backtrace::__rust_end_short_backtrace::hd64e012cf32134c6
   9:        0x102bb2794 - _rust_begin_unwind
  10:        0x102c27808 - core::panicking::panic_fmt::hbfde5533e1c0592e
  11:        0x102c27728 - core::panicking::panic::h89917039f65f3f80
  12:        0x10ccbc748 - <rustc_borrowck[af5d7d8467a98ff0]::MirBorrowckCtxt>::report_general_error
  13:        0x10ccba364 - <rustc_borrowck[af5d7d8467a98ff0]::MirBorrowckCtxt>::report_region_errors
  14:        0x10ccc5900 - rustc_borrowck[af5d7d8467a98ff0]::do_mir_borrowck
  15:        0x10cbfd914 - <rustc_infer[7b400c282ed9aa06]::infer::InferCtxtBuilder>::enter::<rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult, rustc_borrowck[af5d7d8467a98ff0]::mir_borrowck::{closure#0}>
  16:        0x10ccc00cc - rustc_borrowck[af5d7d8467a98ff0]::mir_borrowck
  17:        0x10cc9feb8 - <rustc_borrowck[af5d7d8467a98ff0]::provide::{closure#0} as core[470b050f2b764c47]::ops::function::FnOnce<(rustc_middle[dc659c3191ae8a04]::ty::context::TyCtxt, rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId)>>::call_once
  18:        0x10d27f7d8 - <rustc_query_system[6f834e4506ff6c03]::dep_graph::graph::DepGraph<rustc_middle[dc659c3191ae8a04]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[dc659c3191ae8a04]::ty::context::TyCtxt, rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId, &rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult>
  19:        0x10d03f034 - rustc_query_system[6f834e4506ff6c03]::query::plumbing::try_execute_query::<rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt, rustc_query_system[6f834e4506ff6c03]::query::caches::DefaultCache<rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId, &rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult>>
  20:        0x10d0ccf48 - rustc_query_system[6f834e4506ff6c03]::query::plumbing::get_query::<rustc_query_impl[8b8fa26cca04f19]::queries::mir_borrowck, rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt>
  21:        0x10cc4c864 - <rustc_borrowck[af5d7d8467a98ff0]::type_check::TypeChecker>::prove_closure_bounds
  22:        0x10cc50340 - <rustc_borrowck[af5d7d8467a98ff0]::type_check::TypeChecker>::check_rvalue
  23:        0x10cc53a68 - <rustc_borrowck[af5d7d8467a98ff0]::type_check::TypeChecker>::typeck_mir
  24:        0x10cc46e34 - rustc_borrowck[af5d7d8467a98ff0]::type_check::type_check
  25:        0x10cc3b198 - rustc_borrowck[af5d7d8467a98ff0]::nll::compute_regions
  26:        0x10ccc4b60 - rustc_borrowck[af5d7d8467a98ff0]::do_mir_borrowck
  27:        0x10cbfd914 - <rustc_infer[7b400c282ed9aa06]::infer::InferCtxtBuilder>::enter::<rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult, rustc_borrowck[af5d7d8467a98ff0]::mir_borrowck::{closure#0}>
  28:        0x10ccc00cc - rustc_borrowck[af5d7d8467a98ff0]::mir_borrowck
  29:        0x10cc9feb8 - <rustc_borrowck[af5d7d8467a98ff0]::provide::{closure#0} as core[470b050f2b764c47]::ops::function::FnOnce<(rustc_middle[dc659c3191ae8a04]::ty::context::TyCtxt, rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId)>>::call_once
  30:        0x10d27f7d8 - <rustc_query_system[6f834e4506ff6c03]::dep_graph::graph::DepGraph<rustc_middle[dc659c3191ae8a04]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[dc659c3191ae8a04]::ty::context::TyCtxt, rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId, &rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult>
  31:        0x10d03f034 - rustc_query_system[6f834e4506ff6c03]::query::plumbing::try_execute_query::<rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt, rustc_query_system[6f834e4506ff6c03]::query::caches::DefaultCache<rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId, &rustc_middle[dc659c3191ae8a04]::mir::query::BorrowCheckResult>>
  32:        0x10d0ccf48 - rustc_query_system[6f834e4506ff6c03]::query::plumbing::get_query::<rustc_query_impl[8b8fa26cca04f19]::queries::mir_borrowck, rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt>
  33:        0x10a29d464 - rustc_data_structures[30e623ab5ac4e192]::sync::par_for_each_in::<&[rustc_span[a44dd0315ec95fe3]::def_id::LocalDefId], <rustc_middle[dc659c3191ae8a04]::hir::map::Map>::par_body_owners<rustc_interface[efe2b5ffa23206d6]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  34:        0x10a2eed80 - <rustc_middle[dc659c3191ae8a04]::hir::map::Map>::par_body_owners::<rustc_interface[efe2b5ffa23206d6]::passes::analysis::{closure#2}::{closure#0}>
  35:        0x10a29097c - <rustc_session[6283a40eea3c7aa9]::session::Session>::time::<(), rustc_interface[efe2b5ffa23206d6]::passes::analysis::{closure#2}>
  36:        0x10a28cee8 - rustc_interface[efe2b5ffa23206d6]::passes::analysis
  37:        0x10d2a1a70 - <rustc_query_system[6f834e4506ff6c03]::dep_graph::graph::DepGraph<rustc_middle[dc659c3191ae8a04]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[dc659c3191ae8a04]::ty::context::TyCtxt, (), core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  38:        0x10d07044c - rustc_query_system[6f834e4506ff6c03]::query::plumbing::try_execute_query::<rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt, rustc_query_system[6f834e4506ff6c03]::query::caches::DefaultCache<(), core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>>
  39:        0x10d10f7a0 - rustc_query_system[6f834e4506ff6c03]::query::plumbing::get_query::<rustc_query_impl[8b8fa26cca04f19]::queries::analysis, rustc_query_impl[8b8fa26cca04f19]::plumbing::QueryCtxt>
  40:        0x10a1b79f4 - <rustc_interface[efe2b5ffa23206d6]::passes::QueryContext>::enter::<rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  41:        0x10a19a7e4 - <rustc_interface[efe2b5ffa23206d6]::interface::Compiler>::enter::<rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}::{closure#2}, core[470b050f2b764c47]::result::Result<core[470b050f2b764c47]::option::Option<rustc_interface[efe2b5ffa23206d6]::queries::Linker>, rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  42:        0x10a1e70a0 - rustc_span[a44dd0315ec95fe3]::with_source_map::<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_interface[efe2b5ffa23206d6]::interface::create_compiler_and_run<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#1}>
  43:        0x10a19afd0 - <scoped_tls[438d350ce76b615a]::ScopedKey<rustc_span[a44dd0315ec95fe3]::SessionGlobals>>::set::<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  44:        0x10a1ba43c - std[dfd41530add96b74]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[efe2b5ffa23206d6]::util::run_in_thread_pool_with_globals<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  45:        0x10a1baaf8 - <<std[dfd41530add96b74]::thread::Builder>::spawn_unchecked_<rustc_interface[efe2b5ffa23206d6]::util::run_in_thread_pool_with_globals<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#1} as core[470b050f2b764c47]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:        0x102bbb3dc - std::sys::unix::thread::Thread::new::thread_start::h403ab16d5f453cd4
  47:        0x1a64b026c - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `nfa::<impl at src/nfa.rs:32:1: 32:26>::with::{closure#0}`
#1 [mir_borrowck] borrow-checking `nfa::<impl at src/nfa.rs:32:1: 32:26>::with`
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: std::backtrace::Backtrace::create
             1: <rustc_errors::Handler>::delay_good_path_bug::<&str>
             2: rustc_middle::ty::print::pretty::trimmed_def_paths
             3: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>
             4: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::ArenaCache<(), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>>
             5: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
             6: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             7: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::default_print_def_path
             8: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             9: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::pretty::PrettyPrinter>::pretty_print_type
            10: <rustc_infer::infer::InferCtxt>::extract_inference_diagnostics_data
            11: <rustc_borrowck::MirBorrowckCtxt>::highlight_if_we_cannot_match_hir_ty
            12: <rustc_borrowck::MirBorrowckCtxt>::give_region_a_name
            13: <rustc_borrowck::MirBorrowckCtxt>::report_general_error
            14: <rustc_borrowck::MirBorrowckCtxt>::report_region_errors
            15: rustc_borrowck::do_mir_borrowck
            16: <rustc_infer::infer::InferCtxtBuilder>::enter::<rustc_middle::mir::query::BorrowCheckResult, rustc_borrowck::mir_borrowck::{closure#0}>
            17: rustc_borrowck::mir_borrowck
            18: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            19: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
            20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
            21: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
            22: <rustc_borrowck::type_check::TypeChecker>::prove_closure_bounds
            23: <rustc_borrowck::type_check::TypeChecker>::check_rvalue
            24: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
            25: rustc_borrowck::type_check::type_check
            26: rustc_borrowck::nll::compute_regions
            27: rustc_borrowck::do_mir_borrowck
            28: <rustc_infer::infer::InferCtxtBuilder>::enter::<rustc_middle::mir::query::BorrowCheckResult, rustc_borrowck::mir_borrowck::{closure#0}>
            29: rustc_borrowck::mir_borrowck
            30: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
            31: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
            32: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
            33: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
            34: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
            35: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_interface::passes::analysis::{closure#2}::{closure#0}>
            36: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#2}>
            37: rustc_interface::passes::analysis
            38: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            39: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
            40: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            41: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            42: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
            43: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
            44: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            45: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            46: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            47: std::sys::unix::thread::Thread::new::thread_start
            48: __pthread_deallocate
          

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1426:13
stack backtrace:
   0:        0x102baf978 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
   1:        0x102bfc828 - core::fmt::write::hda8e8eb84b49cbfc
   2:        0x102ba2c74 - std::io::Write::write_fmt::hb84c8996aec7120c
   3:        0x102bb25d0 - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
   4:        0x102bb2334 - std::panicking::default_hook::hd7ceb942fff7b170
   5:        0x10a1fcd9c - rustc_driver[8f8caae8abf9e6c7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x102bb2ba4 - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
   7:        0x10df5be64 - std[dfd41530add96b74]::panicking::begin_panic::<rustc_errors[b30f6c19c09b5d30]::ExplicitBug>::{closure#0}
   8:        0x10df5bc40 - std[dfd41530add96b74]::sys_common::backtrace::__rust_end_short_backtrace::<std[dfd41530add96b74]::panicking::begin_panic<rustc_errors[b30f6c19c09b5d30]::ExplicitBug>::{closure#0}, !>
   9:        0x10e26d64c - std[dfd41530add96b74]::panicking::begin_panic::<rustc_errors[b30f6c19c09b5d30]::ExplicitBug>
  10:        0x10df8c2c8 - std[dfd41530add96b74]::panic::panic_any::<rustc_errors[b30f6c19c09b5d30]::ExplicitBug>
  11:        0x10df8f588 - <rustc_errors[b30f6c19c09b5d30]::HandlerInner as core[470b050f2b764c47]::ops::drop::Drop>::drop
  12:        0x10a18d2dc - core[470b050f2b764c47]::ptr::drop_in_place::<rustc_session[6283a40eea3c7aa9]::parse::ParseSess>
  13:        0x10a193f68 - <alloc[e1afe643157cdf10]::rc::Rc<rustc_session[6283a40eea3c7aa9]::session::Session> as core[470b050f2b764c47]::ops::drop::Drop>::drop
  14:        0x10a1e98a8 - core[470b050f2b764c47]::ptr::drop_in_place::<rustc_interface[efe2b5ffa23206d6]::interface::Compiler>
  15:        0x10a1e767c - rustc_span[a44dd0315ec95fe3]::with_source_map::<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_interface[efe2b5ffa23206d6]::interface::create_compiler_and_run<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#1}>
  16:        0x10a19afd0 - <scoped_tls[438d350ce76b615a]::ScopedKey<rustc_span[a44dd0315ec95fe3]::SessionGlobals>>::set::<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  17:        0x10a1ba43c - std[dfd41530add96b74]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[efe2b5ffa23206d6]::util::run_in_thread_pool_with_globals<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>
  18:        0x10a1baaf8 - <<std[dfd41530add96b74]::thread::Builder>::spawn_unchecked_<rustc_interface[efe2b5ffa23206d6]::util::run_in_thread_pool_with_globals<rustc_interface[efe2b5ffa23206d6]::interface::run_compiler<core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>, rustc_driver[8f8caae8abf9e6c7]::run_compiler::{closure#1}>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#0}, core[470b050f2b764c47]::result::Result<(), rustc_errors[b30f6c19c09b5d30]::ErrorGuaranteed>>::{closure#1} as core[470b050f2b764c47]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  19:        0x102bbb3dc - std::sys::unix::thread::Thread::new::thread_start::h403ab16d5f453cd4
  20:        0x1a64b026c - __pthread_deallocate

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `dfa`

Caused by:
  process didn't exit successfully: `rustc --crate-name dfa --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=0aef2edf0abc743f -C extra-filename=-0aef2edf0abc743f --out-dir /Users/krishna-selectstar/playground/dfa/target/debug/deps -C incremental=/Users/krishna-selectstar/playground/dfa/target/debug/incremental -L dependency=/Users/krishna-selectstar/playground/dfa/target/debug/deps` (signal: 6, SIGABRT: process abort signal)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #102209

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/region_name.rs [hunk 1]
```diff
@@ -864,15 +864,13 @@ impl<'tcx> MirBorrowckCtxt<'_, 'tcx> {
         };
 
         let tcx = self.infcx.tcx;
-        let body_parent_did = tcx.opt_parent(self.mir_def_id().to_def_id())?;
-        if tcx.parent(region.def_id) != body_parent_did
-            || tcx.def_kind(body_parent_did) != DefKind::Impl
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/region_name.rs:869]: Basically this check was too strict -- we don't care if the direct parent of the body is an impl, we only care that the region originates from the impl.
