### PR TITLE
casting `&[u8]` to `* const u8` doesn't work in const_eval

### LINKED ISSUE #33452: const_err warns about casting bytestring to raw pointer
In particular, `b"TouchList\0" as *const u8`. We can't use `as_ptr()` because it's in a const context.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #33452

r? @eddyb 

cc @Ms2ger

### CODE REVIEW

File: src/librustc_const_eval/eval.rs [hunk 1]
```diff
@@ -1117,6 +1117,10 @@ fn cast_const<'tcx>(tcx: &TyCtxt<'tcx>, val: ConstVal, ty: ty::Ty) -> CastResult
         Float(f) => cast_const_float(tcx, f, ty),
         Char(c) => cast_const_int(tcx, Infer(c as u64), ty),
         Function(_) => Err(UnimplementedConstVal("casting fn pointers")),
+        ByteStr(_) => match ty.sty {
+            ty::TyRawPtr(_) => Err(ErrKind::UnimplementedConstVal("casting a bytestr to a raw ptr")),
```
Comment (eddyb) [inline src/librustc_const_eval/eval.rs]: How does this help? Wouldn't it still error?

Comment (oli-obk) [inline src/librustc_const_eval/eval.rs]: Yea, and the `const_err` lint ignores some kinds of errors, since there's no point in informing the user that const_eval can't evaluate it unless they try to use it in an array length or pattern.

**Comment by bluss** [comment]
`b""` is actually a `&[u8; 0]` (and so on with the correct length), not a slice (`&[u8]`).

**Comment by Ms2ger** [comment]
And travis complains:
```
/home/travis/build/rust-lang/rust/src/librustc_const_eval/eval.rs:1121: line longer than 100 chars
```

**Comment by oli-obk** [comment]
done
