### PR TITLE
Point at the return type on `.into()` failure caused by `?`

### LINKED ISSUE #35946: Improve `?` error messages per RFC 1859
RFC 1859 laid out [specific error messages](https://github.com/rust-lang/rfcs/blob/master/text/1859-try-trait.md#error-messages) for the `?` operator, but currently they are not implemented (and instead the compiler's internal desugaring is revealed).

UPDATE: Many parts of this are done, but not all. [Here is a post with examples that are not yet great.](https://github.com/rust-lang/rust/issues/35946#issuecomment-364183576)

UPDATE 2: to close this ticket we need [to improve the output of a single case left](https://play.rust-lang.org/?gist=110a357512f6b3287055963dcdbb951d&version=nightly) to [point at the return type to explain where `usize` is coming from](https://github.com/rust-lang/rust/issues/35946#issuecomment-617465813).

-----

**Original text:**

`try!` in main has long been an issue, to the point of trying to adjust the language to support it: https://github.com/rust-lang/rfcs/issues/1176

I was trying out `?` today, and hit this error:

``` rust
error[E0308]: mismatched types
 --> src/main.rs:5:13
  |
5 |     let f = File::open("hello.txt")?;
  |             ^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
  |
  = note: expected type `()`
  = note:    found type `std::result::Result<_, _>`
```

That's the only line, inside of a `main()` function. Even though I know about this pitfall, and have been using Rust for a long time, I asked a question about it on IRC.

Can we print a better diagnostic here that points out it's the _return type_ of the function that's looking for `()`?

### PR DESCRIPTION
**Pull request by estebank**
Fix #35946.

### CODE REVIEW

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 1]
```diff
@@ -760,6 +762,21 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
         }
     }
 
+    fn return_type_span(&self, obligation: &PredicateObligation<'tcx>) -> Option<Span> {
+        let hir = self.tcx.hir();
+        let parent_node = hir.get_parent_node(obligation.cause.body_id);
+        let node = hir.find(parent_node);
+        let sig =
+            if let Some(hir::Node::Item(hir::Item { kind: hir::ItemKind::Fn(sig, ..), .. })) = node
```
Comment (petrochenkov) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:770]: Nit: this would look better as a `match`.

**Comment by petrochenkov** [comment]
r=me with nits addressed.
