### PR TITLE
Fix `SourceScope` for `if let` bindings.

### LINKED ISSUE #97799: Identifiers introduced via `if let` binding can't be debugged
Identifiers introduced via an `if let` binding can't be inspected in the debugger. For instance:

```rust
pub fn do_it(o: Option<i32>) {
    if let Some(x) = o {
        zzz(x); // #break
    }
}

fn zzz(_: i32) { }
```

Stopping the debugger on line 3 shows no variables in scope other than the function argument `o`. I tested this in both gdb and WinDbg.

This appears to be because rustc generates incorrect scoping information for the call to `zzz`. Looking at the LLVM IR, I see

```llvm
...
  %x = load i32, i32* %7, align 4, !dbg !36
  store i32 %x, i32* %x.dbg.spill, align 4, !dbg !36
  call void @llvm.dbg.declare(metadata i32* %x.dbg.spill, metadata !31, metadata !DIExpression()), !dbg !37
  call void @_ZN7example3zzz17h59648a546f323dcaE(i32 %x), !dbg !38
...
!5 = distinct !DISubprogram(name: "do_it", linkageName: "_ZN7example5do_it17h549531f5caefefa2E", scope: !7, file: !6, line: 1, type: !8, scopeLine: 1, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, templateParams: !19, retainedNodes: !29)
!32 = distinct !DILexicalBlock(scope: !5, file: !6, line: 2, column: 12)
!37 = !DILocation(line: 2, column: 17, scope: !32)
!38 = !DILocation(line: 3, column: 9, scope: !5)
```

Which puts the call to the `zzz` in a different scope than the one `x` is in and thus it isn't visible.

This reproduces on all current versions of Rust:

```
$ rustc +stable --version
rustc 1.61.0 (fe5b13d68 2022-05-18)
$ rustc +beta --version
rustc 1.62.0-beta.3 (a5cf77ca6 2022-06-02)
$ rustc +nightly --version
rustc 1.63.0-nightly (fee3a459d 2022-06-05)
```

### PR DESCRIPTION
**Pull request by xldenis**
Fixes #97799.

I'm not sure how to test this properly, is there any way to observe the difference in behavior apart from `ui` tests? I'm worried that they would be overlooked in the case of a regression.

### CODE REVIEW

File: compiler/rustc_mir_build/src/build/matches/mod.rs [hunk 1]
```diff
@@ -1800,7 +1811,14 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
         let otherwise_post_guard_block = otherwise_candidate.pre_binding_block.unwrap();
         self.break_for_else(otherwise_post_guard_block, else_target, self.source_info(expr_span));
 
-        self.declare_bindings(None, pat.span.to(span), pat, ArmHasGuard(false), opt_expr_place);
+        self.declare_bindings(
```
Comment (xldenis) [inline compiler/rustc_mir_build/src/build/matches/mod.rs:1814]: Another option is to systematically set `self.source_scope` to the scope returned here, but I'm hesitant to do that as this would also affect the path that normal `let` bindings flow through.

File: compiler/rustc_mir_build/src/build/matches/mod.rs [hunk 2]
```diff
@@ -1811,13 +1800,12 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
-            pat,
-            ArmHasGuard(false),
-            opt_expr_place,
-        );
+        let scope =
+            self.declare_bindings(None, pat.span.to(span), pat, ArmHasGuard(false), opt_expr_place);
+
+        if let Some(scope) = scope {
+            self.source_scope = scope;
+        }
```
Comment (xldenis) [inline compiler/rustc_mir_build/src/build/matches/mod.rs:1808]: This is done in `lower_match` for `match` statements, so I do the same here.

Comment (xldenis) [reply compiler/rustc_mir_build/src/build/matches/mod.rs:1808]: actually, this seems insufficient to solve the underlying issue, though its close.

File: src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff [hunk 3]
```diff
@@ -7,33 +7,35 @@
 -     let mut _2: bool;                    // in scope 0 at $SRC_DIR/core/src/macros/mod.rs:LL:COL
 -     let mut _3: isize;                   // in scope 0 at $DIR/const_goto.rs:12:22: 12:28
 +     let mut _2: isize;                   // in scope 0 at $DIR/const_goto.rs:12:22: 12:28
+      scope 1 {
+      }
```
Comment (xldenis) [inline src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff:11]: I'm not super happy about this, but only creating a `scope` when we actually created bindings would require much more invasive changes since we need to bubble up the scope from `declare_bindings` in `lower_let_expr`

Comment (xldenis) [reply src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff:11]: The other option would be to create a scope only for `if let` statements _regardless_ of if they have bindings.

**Comment by xldenis** [comment]
There is one failing test (is ignored on my local machine?) but I would like some validation of the approach anyways if possible.

**Comment by nagisa** [comment]
> is there any way to observe the difference in behavior apart from ui tests

A test for this sort of issue would go into `src/test/debuginfo/`. `var-captured-in-sendable-closure.rs` might serve as a reasonable template the test necessary here.

File: src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff (hunk 3 above)
Comment (xldenis) [reply src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff]: @nagisa do you consider this to be an issue? I've reduced it to only introduce scopes for `if let` but it can still happen

Comment (nagisa) [reply src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff]: I haven't had an opportunity to give this PR a thorough look yet. I'll need to think about the implications of this approach too, so I can't promise I'll be able to get back to you this week.

Comment (xldenis) [reply src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff]: That's fine, this bug is a blocker for some of my work but I'll be at a conference next week anyways

**Comment by wesleywiser** [comment]
Thanks for working on this @xldenis! I took the liberty of pushing a debuginfo test into your PR branch.

File: src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff (hunk 3 above)
Comment (nagisa) [reply src/test/mir-opt/const_goto.issue_77355_opt.ConstGoto.diff]: I think it is perfectly fine to create scopes liberally if it serves some purpose (such as simplifying the code) – it seems like it would likely be much more straightfoward to clean this up as a MIR transformation pass after the fact if this ever came up as a sticking point.

**Comment by nagisa** [comment]
I feel there might be some nice way to make `lower_let_expr` simpler somehow, but I don’t think thinking about it needs to block the fix here.

@bors r+

**Comment by xldenis** [comment]
> I feel there might be some nice way to make lower_let_expr simpler somehow, but I don’t think thinking about it needs to block the fix here.

I also think this, but more broadly I think the whole logic including `then_else_break` could probably be simplified.
