### PR TITLE
don't make empty ident when printing `'` ident from `extern "'"`

### LINKED ISSUE #147365: ICE: `"'"` isn't `""`
probably another case of https://github.com/rust-lang/rust/issues/140884

auto-reduced (treereduce-rust):
````rust
extern "C" {
    extern "'" fn L() {}
}

````

original:
````rust
extern {
    extern "'" fn L() {
        async fn M() {}
    }
}

````

Version information
````
rustc 1.92.0-nightly (2cb4e7dce 2025-10-04)
binary: rustc
commit-hash: 2cb4e7dce84fdebc0279159f1082f92b99299d87
commit-date: 2025-10-04
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.2

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs#L2470-L2482

Command:
`/home/matthias/.rustup/toolchains/alt-master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: incorrect function inside `extern` block
 --> /tmp/icemaker_global_tempdir.n1ZLQ8e0s75E/rustc_testrunner_tmpdir_reporting.tyl0BcU5f56b/mvce.rs:2:19
  |
1 | extern "C" {
  | ---------- `extern` blocks define existing foreign functions and functions inside of them cannot have a body
2 |     extern "'" fn L() {}
  |                   ^   -- help: remove the invalid body: `;`
  |                   |
  |                   cannot have a body
  |
  = help: you might have meant to write a function accessible through FFI, which can be done by writing `extern fn` outside of the `extern` block
  = note: for more information, visit https://doc.rust-lang.org/std/keyword.extern.html

error: functions in `extern` blocks cannot have `extern` qualifier
 --> /tmp/icemaker_global_tempdir.n1ZLQ8e0s75E/rustc_testrunner_tmpdir_reporting.tyl0BcU5f56b/mvce.rs:2:5
  |
1 | extern "C" {
  | ---------- in this `extern` block
2 |     extern "'" fn L() {}
  |     ^^^^^^^^^^ help: remove the `extern` qualifier


thread 'rustc' (3564091) panicked at compiler/rustc_span/src/symbol.rs:2476:9:
assertion `left != right` failed
  left: ""
 right: ""
stack backtrace:
   0:     0x7f108e824973 - std::backtrace_rs::backtrace::libunwind::trace::hd83a37773dfd4434
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x7f108e824973 - std::backtrace_rs::backtrace::trace_unsynchronized::h509cab0e6461e251
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x7f108e824973 - std::sys::backtrace::_print_fmt::hb32fd28dac0ec9b4
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/backtrace.rs:66:9
   3:     0x7f108e824973 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb957197655182d29
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/backtrace.rs:39:26
   4:     0x7f1089be9e42 - core::fmt::rt::Argument::fmt::h51357c52ce984306
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/fmt/rt.rs:173:76
   5:     0x7f1089be9e42 - core::fmt::write::h454666a6f3677ca6
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/fmt/mod.rs:1468:25
   6:     0x7f108e7b0a39 - std::io::default_write_fmt::hc063ebda100f426f
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/io/mod.rs:639:11
   7:     0x7f108e7b0a39 - std::io::Write::write_fmt::haa291f166d9cbca2
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/io/mod.rs:1954:13
   8:     0x7f108e7d5a4b - std::sys::backtrace::BacktraceLock::print::he1f21aa3a083ed35
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/backtrace.rs:42:9
   9:     0x7f108e7d5a4b - std::panicking::default_hook::{{closure}}::h3b951f9d4e38c759
  10:     0x7f108e7d55e5 - std::panicking::default_hook::h9891268de37b6da3
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:328:9
  11:     0x7f108afe7b82 - <alloc[818a06d4bd488de9]::boxed::Box<dyn for<'a, 'b> core[bcc826e88542c6f8]::ops::function::Fn<(&'a std[85c9cd87381b0611]::panic::PanicHookInfo<'b>,), Output = ()> + core[bcc826e88542c6f8]::marker::Sync + core[bcc826e88542c6f8]::marker::Send> as core[bcc826e88542c6f8]::ops::function::Fn<(&std[85c9cd87381b0611]::panic::PanicHookInfo,)>>::call
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/boxed.rs:2018:9
  12:     0x7f108afe7b82 - rustc_driver_impl[b24c57aa69b7aaf8]::install_ice_hook::{closure#1}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_driver_impl/src/lib.rs:1431:17
  13:     0x7f108afe7b82 - <alloc[818a06d4bd488de9]::boxed::Box<rustc_driver_impl[b24c57aa69b7aaf8]::install_ice_hook::{closure#1}> as core[bcc826e88542c6f8]::ops::function::Fn<(&dyn for<'a, 'b> core[bcc826e88542c6f8]::ops::function::Fn<(&'a std[85c9cd87381b0611]::panic::PanicHookInfo<'b>,), Output = ()> + core[bcc826e88542c6f8]::marker::Sync + core[bcc826e88542c6f8]::marker::Send, &std[85c9cd87381b0611]::panic::PanicHookInfo)>>::call
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/boxed.rs:2018:9
  14:     0x7f108afe7b82 - std[85c9cd87381b0611]::panicking::update_hook::<alloc[818a06d4bd488de9]::boxed::Box<rustc_driver_impl[b24c57aa69b7aaf8]::install_ice_hook::{closure#1}>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:243:47
  15:     0x7f108e7d6064 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbfa19977fcd00847
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/boxed.rs:2018:9
  16:     0x7f108e7d6064 - std::panicking::panic_with_hook::hfe189f193e882d33
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:842:13
  17:     0x7f108e7d5d0c - std::panicking::panic_handler::{{closure}}::h0e3d2c5807ed6148
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:707:13
  18:     0x7f108e7cc849 - std::sys::backtrace::__rust_end_short_backtrace::hae920909d0226e4e
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/backtrace.rs:174:18
  19:     0x7f108e79f8dd - __rustc[f902241ae06a8ef2]::rust_begin_unwind
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:698:5
  20:     0x7f1089bfa660 - core::panicking::panic_fmt::h1e654ad5b19c30f3
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/panicking.rs:78:14
  21:     0x7f1089bfa413 - core::panicking::assert_failed_inner::h16cb7aa6ddc1155f
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/panicking.rs:442:17
  22:     0x7f108dcfc4ec - core[bcc826e88542c6f8]::panicking::assert_failed::<rustc_span[125fb94978f1d1d2]::symbol::Symbol, rustc_span[125fb94978f1d1d2]::symbol::Symbol>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/panicking.rs:397:5
  23:     0x7f108dd09f48 - <rustc_span[125fb94978f1d1d2]::symbol::Ident>::new
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:2476:9
  24:     0x7f108dd09f48 - <rustc_span[125fb94978f1d1d2]::symbol::Ident>::without_first_quote
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:2511:9
  25:     0x7f108dd3dced - <rustc_span[125fb94978f1d1d2]::symbol::Ident>::is_raw_lifetime_guess
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:3097:44
  26:     0x7f108dd3dced - <rustc_span[125fb94978f1d1d2]::symbol::Ident>::guess_print_mode
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:3104:17
  27:     0x7f108dd3dced - <rustc_span[125fb94978f1d1d2]::symbol::Ident as core[bcc826e88542c6f8]::fmt::Display>::fmt
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:2569:62
  28:     0x7f108a030e7b - <rustc_span[125fb94978f1d1d2]::symbol::Ident as alloc[818a06d4bd488de9]::string::SpecToString>::spec_to_string
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/string.rs:2807:9
  29:     0x7f108a030e7b - <rustc_span[125fb94978f1d1d2]::symbol::Ident as alloc[818a06d4bd488de9]::string::ToString>::to_string
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/string.rs:2786:9
  30:     0x7f108a030e7b - <rustc_span[125fb94978f1d1d2]::symbol::Symbol>::to_ident_string
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/symbol.rs:2778:85
  31:     0x7f108a030e7b - <rustc_span[125fb94978f1d1d2]::symbol::Symbol as rustc_error_messages[b2227f60f3b5e05d]::IntoDiagArg>::into_diag_arg
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_error_messages/src/diagnostic_impls.rs:111:14
  32:     0x7f108a030e7b - <rustc_errors[d36fc64ef399c425]::diagnostic::DiagInner>::arg::<&str, rustc_span[125fb94978f1d1d2]::symbol::Symbol>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_errors/src/diagnostic.rs:358:25
  33:     0x7f108a030e7b - <rustc_errors[d36fc64ef399c425]::diagnostic::Diag>::arg::<&str, rustc_span[125fb94978f1d1d2]::symbol::Symbol>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_errors/src/diagnostic.rs:1296:26
  34:     0x7f108a0df195 - <rustc_ast_lowering[c826c95c6e78e5f4]::errors::InvalidAbi as rustc_errors[d36fc64ef399c425]::diagnostic::Diagnostic>::into_diag
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/errors.rs:25:10
  35:     0x7f108a0df195 - <rustc_errors[d36fc64ef399c425]::DiagCtxtHandle>::create_err::<rustc_ast_lowering[c826c95c6e78e5f4]::errors::InvalidAbi>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_errors/src/lib.rs:1343:13
  36:     0x7f108a0df195 - <rustc_errors[d36fc64ef399c425]::DiagCtxtHandle>::emit_err::<rustc_ast_lowering[c826c95c6e78e5f4]::errors::InvalidAbi>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_errors/src/lib.rs:1348:14
  37:     0x7f108a0df195 - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::error_on_invalid_abi
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:1675:20
  38:     0x7f108a0df195 - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_abi::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:1632:18
  39:     0x7f108a0df195 - <core[bcc826e88542c6f8]::result::Result<rustc_abi[9ee87857b5dbfbc3]::extern_abi::ExternAbi, rustc_abi[9ee87857b5dbfbc3]::AbiFromStrErr>>::unwrap_or_else::<<rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_abi::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/result.rs:1615:23
  40:     0x7f108a0df195 - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_abi
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:1631:60
  41:     0x7f108a0bc668 - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_extern
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:1665:46
  42:     0x7f108a0bc668 - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_fn_header
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:1625:23
  43:     0x7f108a01a33e - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::lower_foreign_item
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:642:35
  44:     0x7f108a01a33e - <rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::lower_node::{closure#4}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:96:54
  45:     0x7f108a01a33e - <rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::with_lctx::<<rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::lower_node::{closure#4}>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:62:46
  46:     0x7f108a01a33e - <rustc_ast_lowering[c826c95c6e78e5f4]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::lower_node::{closure#4}>::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/lib.rs:633:20
  47:     0x7f108a01a33e - <rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::with_lctx::<<rustc_ast_lowering[c826c95c6e78e5f4]::item::ItemLowerer>::lower_node::{closure#4}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/item.rs:62:14
  48:     0x7f108a064311 - rustc_ast_lowering[c826c95c6e78e5f4]::lower_to_hir
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_ast_lowering/src/lib.rs:496:17
  49:     0x7f108d4c6e56 - rustc_query_impl[494ca645a3fc548]::query_impl::hir_crate::dynamic_query::{closure#2}::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:294:9
  50:     0x7f108d4c6e56 - rustc_query_impl[494ca645a3fc548]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[494ca645a3fc548]::query_impl::hir_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:578:18
  51:     0x7f108d93d017 - rustc_query_impl[494ca645a3fc548]::query_impl::hir_crate::dynamic_query::{closure#2}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:655:25
  52:     0x7f108d93d017 - <rustc_query_impl[494ca645a3fc548]::query_impl::hir_crate::dynamic_query::{closure#2} as core[bcc826e88542c6f8]::ops::function::FnOnce<(rustc_middle[5b61fab83e64ab4]::ty::context::TyCtxt, ())>>::call_once
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/ops/function.rs:250:5
  53:     0x7f108d5000ff - <rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false> as rustc_query_system[f2ec611453bf65]::query::config::QueryConfig<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>>::compute
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/lib.rs:122:9
  54:     0x7f108d5000ff - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:493:72
  55:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context::<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:60:9
  56:     0x7f108d5000ff - <std[85c9cd87381b0611]::thread::local::LocalKey<core[bcc826e88542c6f8]::cell::Cell<*const ()>>>::try_with::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/local.rs:508:12
  57:     0x7f108d5000ff - <std[85c9cd87381b0611]::thread::local::LocalKey<core[bcc826e88542c6f8]::cell::Cell<*const ()>>>::with::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/local.rs:472:20
  58:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context::<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:57:9
  59:     0x7f108d5000ff - <rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:161:13
  60:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context::<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:112:9
  61:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:90:36
  62:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context_opt::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:79:18
  63:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:90:5
  64:     0x7f108d5000ff - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context::<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:103:5
  65:     0x7f108d5000ff - <rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:147:9
  66:     0x7f108d5000ff - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:493:22
  67:     0x7f108d5000ff - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt, false>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:429:9
  68:     0x7f108d5000ff - rustc_query_system[f2ec611453bf65]::query::plumbing::try_execute_query::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt, false>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:372:13
  69:     0x7f108d755513 - rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:814:32
  70:     0x7f108d755513 - stacker[afa0e35183669fac]::maybe_grow::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  71:     0x7f108d755513 - rustc_data_structures[15a1d3c4e01dbff6]::stack::ensure_sufficient_stack::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_data_structures/src/stack.rs:21:5
  72:     0x7f108d755513 - rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:814:5
  73:     0x7f108d755513 - rustc_query_impl[494ca645a3fc548]::query_impl::hir_crate::get_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:631:26
  74:     0x7f108c0d754f - rustc_middle[5b61fab83e64ab4]::query::plumbing::query_get_at::<rustc_query_system[f2ec611453bf65]::query::caches::SingleCache<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/query/plumbing.rs:182:17
  75:     0x7f108c0d754f - <rustc_middle[5b61fab83e64ab4]::query::plumbing::TyCtxtAt>::hir_crate
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/query/plumbing.rs:475:31
  76:     0x7f108c0d754f - <rustc_middle[5b61fab83e64ab4]::ty::context::TyCtxt>::hir_crate
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/query/plumbing.rs:466:35
  77:     0x7f108c0d754f - rustc_middle[5b61fab83e64ab4]::hir::provide::{closure#1}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/hir/mod.rs:226:23
  78:     0x7f108c0d754f - <rustc_middle[5b61fab83e64ab4]::hir::provide::{closure#1} as core[bcc826e88542c6f8]::ops::function::FnOnce<(rustc_middle[5b61fab83e64ab4]::ty::context::TyCtxt, rustc_span[125fb94978f1d1d2]::def_id::LocalDefId)>>::call_once
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/ops/function.rs:250:5
  79:     0x7f108d4b2a4e - rustc_query_impl[494ca645a3fc548]::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2}::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:294:9
  80:     0x7f108d4b2a4e - rustc_query_impl[494ca645a3fc548]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[494ca645a3fc548]::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:578:18
  81:     0x7f108d8f5b3f - rustc_query_impl[494ca645a3fc548]::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:655:25
  82:     0x7f108d8f5b3f - <rustc_query_impl[494ca645a3fc548]::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2} as core[bcc826e88542c6f8]::ops::function::FnOnce<(rustc_middle[5b61fab83e64ab4]::ty::context::TyCtxt, rustc_span[125fb94978f1d1d2]::def_id::LocalDefId)>>::call_once
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/ops/function.rs:250:5
  83:     0x7f108d5a397e - <rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false> as rustc_query_system[f2ec611453bf65]::query::config::QueryConfig<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>>::compute
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/lib.rs:122:9
  84:     0x7f108d5a397e - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:493:72
  85:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context::<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:60:9
  86:     0x7f108d5a397e - <std[85c9cd87381b0611]::thread::local::LocalKey<core[bcc826e88542c6f8]::cell::Cell<*const ()>>>::try_with::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/local.rs:508:12
  87:     0x7f108d5a397e - <std[85c9cd87381b0611]::thread::local::LocalKey<core[bcc826e88542c6f8]::cell::Cell<*const ()>>>::with::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/local.rs:472:20
  88:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::enter_context::<rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:57:9
  89:     0x7f108d5a397e - <rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:161:13
  90:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context::<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:112:9
  91:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:90:36
  92:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context_opt::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:79:18
  93:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_context::<rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:90:5
  94:     0x7f108d5a397e - rustc_middle[5b61fab83e64ab4]::ty::context::tls::with_related_context::<<rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>::{closure#0}, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_middle/src/ty/context/tls.rs:103:5
  95:     0x7f108d5a397e - <rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt as rustc_query_system[f2ec611453bf65]::query::QueryContext>::start_query::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_impl/src/plumbing.rs:147:9
  96:     0x7f108d5a397e - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:493:22
  97:     0x7f108d5a397e - rustc_query_system[f2ec611453bf65]::query::plumbing::execute_job::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt, false>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:429:9
  98:     0x7f108d5a397e - rustc_query_system[f2ec611453bf65]::query::plumbing::try_execute_query::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_hir_id[a2985891b479ea06]::OwnerId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt, false>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:372:13
  99:     0x7f108d71455c - rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr::<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_span[125fb94978f1d1d2]::def_id::LocalDefId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_query_system/src/query/plumbing.rs:814:32
 100:     0x7f108d71455c - stacker[afa0e35183669fac]::maybe_grow::<rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::query::plumbing::get_query_non_incr<rustc_query_impl[494ca645a3fc548]::DynamicConfig<rustc_data_structures[15a1d3c4e01dbff6]::vec_cache::VecCache<rustc_span[125fb94978f1d1d2]::def_id::LocalDefId, rustc_middle[5b61fab83e64ab4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[f2ec611453bf65]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[494ca645a3fc548]::plumbing::QueryCtxt>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
 
 
 <snip>
 
 195:     0x7f108afd3df6 - rustc_span[125fb94978f1d1d2]::create_session_globals_then::<(), rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_span/src/lib.rs:146:21
 196:     0x7f108afd3df6 - rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals::<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/compiler/rustc_interface/src/util.rs:158:17
 197:     0x7f108afd3df6 - std[85c9cd87381b0611]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/backtrace.rs:158:18
 198:     0x7f108aff5020 - <std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_::<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/mod.rs:562:17
 199:     0x7f108aff5020 - <core[bcc826e88542c6f8]::panic::unwind_safe::AssertUnwindSafe<<std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}> as core[bcc826e88542c6f8]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/panic/unwind_safe.rs:274:9
 200:     0x7f108aff5020 - std[85c9cd87381b0611]::panicking::catch_unwind::do_call::<core[bcc826e88542c6f8]::panic::unwind_safe::AssertUnwindSafe<<std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:590:40
 201:     0x7f108aff5020 - std[85c9cd87381b0611]::panicking::catch_unwind::<(), core[bcc826e88542c6f8]::panic::unwind_safe::AssertUnwindSafe<<std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panicking.rs:553:19
 202:     0x7f108aff5020 - std[85c9cd87381b0611]::panic::catch_unwind::<core[bcc826e88542c6f8]::panic::unwind_safe::AssertUnwindSafe<<std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/panic.rs:359:14
 203:     0x7f108aff5020 - <std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_::<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/thread/mod.rs:560:30
 204:     0x7f108aff5020 - <<std[85c9cd87381b0611]::thread::Builder>::spawn_unchecked_<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_with_globals<rustc_interface[c3e66f9e3c57193f]::util::run_in_thread_pool_with_globals<rustc_interface[c3e66f9e3c57193f]::interface::run_compiler<(), rustc_driver_impl[b24c57aa69b7aaf8]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[bcc826e88542c6f8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc-dev/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/core/src/ops/function.rs:250:5
 205:     0x7f108e7c5cc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h292b9770a2bce0f2
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/alloc/src/boxed.rs:2004:9
 206:     0x7f108e7c5cc5 - std::sys::thread::unix::Thread::new::thread_start::h944ac51c2d0327c9
                               at /rustc/2cb4e7dce84fdebc0279159f1082f92b99299d87/library/std/src/sys/thread/unix.rs:126:17
 207:     0x7f10880969cb - <unknown>
 208:     0x7f108811aa0c - <unknown>
 209:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.92.0-nightly (2cb4e7dce 2025-10-04) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [opt_hir_owner_nodes] getting HIR owner items in ``
#2 [hir_crate_items] getting HIR crate items
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors


```

</p>
</details>

### PR DESCRIPTION
**Pull request by karolzwolak**
Fixes rust-lang/rust#147365.
r? @nnethercote

### CODE REVIEW

File: compiler/rustc_span/src/symbol.rs [hunk 1]
```diff
@@ -3095,10 +3098,15 @@ impl Ident {
...
-        let name_without_apostrophe = self.without_first_quote();
-        name_without_apostrophe.name != self.name
-            && name_without_apostrophe.name.can_be_raw()
-            && name_without_apostrophe.is_reserved_lifetime()
+        // Check that the name isn't just a single quote.
+        // `self.without_first_quote()` would return empty ident, which triggers debug assert.
+        if self.name.as_str() == "'" {
+            return false;
+        }
+        let ident_without_apostrophe = self.without_first_quote();
```
Comment (nnethercote) [inline compiler/rustc_span/src/symbol.rs:3106]: Thumbs up for the `name`/`ident` renaming here.

**Comment by nnethercote** [comment]
Thanks for fixing the bug!

@bors r+ rollup
