### PR TITLE
Resume one waiter at once in deadlock handler

### LINKED ISSUE #120757: ICE: deadlock due to query cycle
### Code

```Rust
#![feature(generic_const_exprs)]

trait TensorDimension {
    const DIM: usize;
    const ISSCALAR: bool = Self::DIM == 0;
    fn is_scalar(&self) -> bool {
        Self::ISSCALAR
    }
}

trait TensorSize: TensorDimension {
    fn size(&self) -> [usize; Self::DIM];
    fn inbounds(&self, index: [usize; Self::DIM]) -> bool {
        index.iter().zip(self.size().iter()).all(|(i, s)| i < s)
    }
}

trait Broadcastable: TensorSize + Sized {
    type Element;
    fn bget(&self, index: [usize; Self::DIM]) -> Option<Self::Element>;
    fn lazy_updim<const NEWDIM: usize>(
        &self,
        size: [usize; NEWDIM],
    ) -> LazyUpdim<Self, { Self::DIM }, NEWDIM> {
        assert!(
            NEWDIM >= Self::DIM,
            "Updimmed tensor cannot have fewer indices than the initial one."
        ); // const generic bounds on nightly. ( )
        LazyUpdim {
            size,
            reference: &self,
        }
    }
    fn bmap<T, F: Fn(Self::Element) -> T>(&self, foo: F) -> BMap<T, Self, F, { Self::DIM }> {
        BMap {
            reference: self,
            closure: foo,
        }
    }
}

struct LazyUpdim<'a, T: Broadcastable, const OLDDIM: usize, const DIM: usize> {
    size: [usize; DIM],
    reference: &'a T,
}

impl<'a, T: Broadcastable, const DIM: usize> TensorDimension for LazyUpdim<'a, T, { T::DIM }, DIM> {
    const DIM: usize = DIM;
}
impl<'a, T: Broadcastable, const DIM: usize> TensorSize for LazyUpdim<'a, T, { T::DIM }, DIM> {
    fn size(&self) -> [usize; DIM] {
        self.size
    }
}
impl<'a, T: Broadcastable, const DIM: usize> Broadcastable for LazyUpdim<'a, T, { T::DIM }, DIM> {
    type Element = T::Element;
    fn bget(&self, index: [usize; DIM]) -> Option<Self::Element> {
        assert!(DIM >= T::DIM);
        if !self.inbounds(index) {
            return None;
        }
        let size = self.size();
        let newindex: [usize; T::DIM] = Default::default(); //array_init::array_init(|i| if size[i] > 1 {index[i]} else {0});
        self.reference.bget(newindex)
    }
}

struct BMap<'a, R, T: Broadcastable, F: Fn(T::Element) -> R, const DIM: usize> {
    reference: &'a T,
    closure: F,
}

impl<'a, R, T: Broadcastable, F: Fn(T::Element) -> R, const DIM: usize> TensorDimension
    for BMap<'a, R, T, F, DIM>
{
    const DIM: usize = DIM;
}
impl<'a, R, T: Broadcastable, F: Fn(T::Element) -> R, const DIM: usize> TensorSize
    for BMap<'a, R, T, F, DIM>
{
    fn size(&self) -> [usize; DIM] {
        self.reference.size()
    }
}
impl<'a, R, T: Broadcastable, F: Fn(T::Element) -> R, const DIM: usize> Broadcastable
    for BMap<'a, R, T, F, DIM>
{
    type Element = R;
    fn bget(&self, index: [usize; DIM]) -> Option<Self::Element> {
        self.reference.bget(index).map(ns_window)
    }
}

impl<T> TensorDimension for Vec<T> {
    const DIM: usize = 1;
}
impl<T> TensorSize for Vec<T> {
    fn size(&self) -> [usize; 1] {
        [self.len()]
    }
}
impl<T: Clone> Broadcastable for Vec<T> {
    type Element = T;
    fn bget(&self, index: [usize; 1]) -> Option<T> {
        self.get(index[0]).cloned()
    }
}

fn main() {
    let v = vec![1, 2, 3];
    let bv = v.lazy_updim([3, 4]);
    let bbv = bv.bmap(|x| x * x);

    println!(
        "The size of v is {:?}",
        bbv.bget([0, 2]).expect("Out of bounds.")
    );
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (256b6fb19 2024-02-06)
binary: rustc
commit-hash: 256b6fb19a2c018eaad4806d2369d1f6a71fc6ec
commit-date: 2024-02-06
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### Error output
`rustc -Zthreads=50 --crate-type lib file.rs`
```
error[E0425]: cannot find value `ns_window` in this scope
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:90:40
   |
90 |         self.reference.bget(index).map(ns_window)
   |                                        ^^^^^^^^^ not found in this scope

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0308]: method not compatible with trait
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:81:5
   |
81 |     fn size(&self) -> [usize; DIM] {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Self::DIM`, found `DIM`
   |
   = note: expected constant `Self::DIM`
              found constant `DIM`

error[E0308]: method not compatible with trait
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:89:5
   |
89 |     fn bget(&self, index: [usize; DIM]) -> Option<Self::Element> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Self::DIM`, found `DIM`
   |
   = note: expected constant `Self::DIM`
              found constant `DIM`

error[E0391]: cycle detected when resolving instance `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>::DIM`
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:4:5
   |
4  |     const DIM: usize;
   |     ^^^^^^^^^^^^^^^^
   |
note: ...which requires computing candidate for `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>`...
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:3:1
   |
3  | trait TensorDimension {
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: ...which again requires resolving instance `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>::DIM`, completing the cycle
note: cycle used when checking that `<impl at /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:55:1: 55:97>` is well-formed
  --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:55:1
   |
55 | impl<'a, T: Broadcastable, const DIM: usize> Broadcastable for LazyUpdim<'a, T, { T::DIM }, DIM> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when resolving instance `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>::DIM`
 --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:4:5
  |
4 |     const DIM: usize;
  |     ^^^^^^^^^^^^^^^^
  |
note: ...which requires computing candidate for `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>`...
 --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:3:1
  |
3 | trait TensorDimension {
  | ^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires resolving instance `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>::DIM`, completing the cycle
note: cycle used when computing candidate for `<LazyUpdim<'_, T, { T::DIM }, DIM> as TensorDimension>`
 --> /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:3:1
  |
3 | trait TensorDimension {
  | ^^^^^^^^^^^^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread '<unnamed>' panicked at compiler/rustc_query_system/src/query/job.rs:545:13:
deadlock detected! current query map:
{
    QueryJobId(
        8765,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "evaluating type-level constant",
            span: Some(
                Span {
                    lo: BytePos(
                        255,
                    ),
                    hi: BytePos(
                        264,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 126,
            },
            hash: 12867481825104948218,
        },
        job: QueryJob {
            id: QueryJobId(
                8765,
            ),
            span: Span {
                lo: BytePos(
                    1475,
                ),
                hi: BytePos(
                    1505,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    8487,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        9034,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "computing candidate for `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>`",
            span: Some(
                Span {
                    lo: BytePos(
                        34,
                    ),
                    hi: BytePos(
                        55,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 159,
            },
            hash: 14524696915396724072,
        },
        job: QueryJob {
            id: QueryJobId(
                9034,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    9032,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        9031,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "computing candidate for `<LazyUpdim<'_, T, { T::DIM }, DIM> as TensorDimension>`",
            span: Some(
                Span {
                    lo: BytePos(
                        34,
                    ),
                    hi: BytePos(
                        55,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 159,
            },
            hash: 7972346769609958538,
        },
        job: QueryJob {
            id: QueryJobId(
                9031,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    9030,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        8292,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "checking that types are well-formed in top-level module",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        3306,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: Some(
                DefId(0:0),
            ),
            def_kind: Some(
                Mod,
            ),
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 110,
            },
            hash: 5322523677691242860,
        },
        job: QueryJob {
            id: QueryJobId(
                8292,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    7297,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        7297,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "running analysis passes on this crate",
            span: Some(
                Span {
                    lo: BytePos(
                        0,
                    ),
                    hi: BytePos(
                        0,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 25,
            },
            hash: 5462938028500440564,
        },
        job: QueryJob {
            id: QueryJobId(
                7297,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: None,
            latch: None,
        },
    },
    QueryJobId(
        8487,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "checking that `<impl at /home/matthias/vcs/github/glacier2/fixed/icemaker_omni/CF35B2D494F3AAB8EA51CD645B1230546A5E59928436E15521DFFFB4D3856CCC.rs:50:1: 50:94>` is well-formed",
            span: Some(
                Span {
                    lo: BytePos(
                        1375,
                    ),
                    hi: BytePos(
                        1468,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: Some(
                DefId(0:39),
            ),
            def_kind: Some(
                Impl {
                    of_trait: true,
                },
            ),
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 195,
            },
            hash: 11679696925837849750,
        },
        job: QueryJob {
            id: QueryJobId(
                8487,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    8292,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        9032,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "resolving instance `<LazyUpdim<'_, T, <T as TensorDimension>::DIM, DIM> as TensorDimension>::DIM`",
            span: Some(
                Span {
                    lo: BytePos(
                        62,
                    ),
                    hi: BytePos(
                        78,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 278,
            },
            hash: 10795639758650191788,
        },
        job: QueryJob {
            id: QueryJobId(
                9032,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    9031,
                ),
            ),
            latch: Some(
                QueryLatch {
                    info: Mutex {
                        data: QueryLatchInfo {
                            complete: true,
                            waiters: [],
                        },
                    },
                },
            ),
        },
    },
    QueryJobId(
        8767,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "const-evaluating + checking `TensorSize::size::{constant#0}`",
            span: Some(
                Span {
                    lo: BytePos(
                        255,
                    ),
                    hi: BytePos(
                        264,
                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 124,
            },
            hash: 16033137702957887872,
        },
        job: QueryJob {
            id: QueryJobId(
                8767,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    8765,
                ),
            ),
            latch: None,
        },
    },
    QueryJobId(
        9030,
    ): QueryJobInfo {
        query: QueryStackFrame {
            description: "resolving instance `<LazyUpdim<'_, T, { T::DIM }, DIM> as TensorDimension>::DIM`",
            span: Some(
                Span {
                    lo: BytePos(
                        62,
                    ),
                    hi: BytePos(
                        78,
^[[A                    ),
                    ctxt: #0,
                },
            ),
            def_id: None,
            def_kind: None,
            ty_def_id: None,
            dep_kind: DepKind {
                variant: 278,
            },
            hash: 16370839285763878492,
        },
        job: QueryJob {
            id: QueryJobId(
                9030,
            ),
            span: Span {
                lo: BytePos(
                    0,
                ),
                hi: BytePos(
                    0,
                ),
                ctxt: #0,
            },
            parent: Some(
                QueryJobId(
                    8767,
                ),
            ),
            latch: None,
        },
    },
}
stack backtrace:
error: aborting due to 5 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0391, E0425.
For more information about an error, try `rustc --explain E0308`.
```

</p>
</details>

### LINKED ISSUE #129911: ICE: `deadlock detected as we're unable to find a query cycle to break`
<!--
Thank you for finding an Internal Compiler Error! 🧊  If possible, try to provide
a minimal verifiable example. You can read "Rust Bug Minimization Patterns" for
how to create smaller examples.
http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/
-->

### Code
rustc -Zthreads=50 --crate-type=lib,--cap-lints=warn,-Zmir-opt-level=5,-Zvalidate-mir,--edition=2021,-Zlint-mir,-Cdebuginfo=2,-Clink-dead-code=true,-Zthreads=16,-Zwrite-long-types-to-disk=no
```Rust
type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
```


### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (94885bc69 2024-09-01)
binary: rustc
commit-hash: 94885bc699512cfee8560e73c2a01ee6b4b76563
commit-date: 2024-09-01
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

```
....
warning: unnecessary trailing semicolons
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:352
  |
1 | ...;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                             ^^ help: remove these semicolons

warning: unnecessary trailing semicolons
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:347
  |
1 | ...{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                            ^^^ help: remove these semicolons

warning: unnecessary trailing semicolons
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:377
  |
1 | ...;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                            ^^^ help: remove these semicolons

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:268
  |
1 | ...  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                     ^^^-------------------------------------------------------------------------------------------------------------------------------------- help: remove the unnecessary generics
  |                                                                     |
  |                                                                     expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:261
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                                                                                     ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:300
  |
1 | ...Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                    ^^^--------- help: remove the unnecessary generics
  |                                                                                                                                    |
  |                                                                                                                                    expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:293
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                                                                                                                     ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:46
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                              ^^^--------- help: remove the unnecessary generics
  |                                              |
  |                                              expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:39
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                       ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:337
  |
1 | ...=  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                             ^^^------------------------------------------------------ help: remove the unnecessary generics
  |                                                                                                             |
  |                                                                                                             expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:330
  |
1 | ...;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                                           ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:235
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                                                           ^^^--------- help: remove the unnecessary generics
  |                                                                                                                                                                                                                                           |
  |                                                                                                                                                                                                                                           expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:228
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                                                    ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:205
  |
1 | ...{;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                ^^^----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- help: remove the unnecessary generics
  |                                |
  |                                expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:198
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                      ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:371
  |
1 | ...;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                    ^^^--------- help: remove the unnecessary generics
  |                                                                                                                                    |
  |                                                                                                                                    expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:364
  |
1 | ...{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                                           ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:172
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                            ^^^--------- help: remove the unnecessary generics
  |                                                                                                                                                                            |
  |                                                                                                                                                                            expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:165
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                     ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:79
  |
1 | ...=  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::A...
  |       ^^^----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- help: remove the unnecessary generics
  |       |
  |       expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:72
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                        ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:142
  |
1 | ...Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >...
  |           ^^^-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- help: remove the unnecessary generics
  |           |
  |           expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:135
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                       ^^^

error[E0107]: type alias takes 0 generic arguments but 1 generic argument was supplied
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:109
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                             ^^^--------- help: remove the unnecessary generics
  |                                                                                                             |
  |                                                                                                             expected 0 generic arguments
  |
note: type alias defined here, with 0 generic parameters
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:102
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                      ^^^

error[E0391]: cycle detected when expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:371
  |
1 | ...ype Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                                       ^^^^^^^^^^^^
  |
  = note: ...which immediately requires expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` again
  = note: type aliases cannot be recursive
  = help: consider using a struct, enum, or union instead to break the cycle
  = help: see <https://doc.rust-lang.org/reference/types.html#recursive-types> for more information
note: cycle used when checking that `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` is well-formed
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:359
  |
1 | ...{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                                                                                         ^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when expanding type alias `KooArc::{constant#0}::Frc`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:79
  |
1 | ...=  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::A...
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which immediately requires expanding type alias `KooArc::{constant#0}::Frc` again
  = note: type aliases cannot be recursive
  = help: consider using a struct, enum, or union instead to break the cycle
  = help: see <https://doc.rust-lang.org/reference/types.html#recursive-types> for more information
note: cycle used when checking that `KooArc::{constant#0}::Frc` is well-formed
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:67
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                   ^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:205
  |
1 | ...;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which immediately requires expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` again
  = note: type aliases cannot be recursive
  = help: consider using a struct, enum, or union instead to break the cycle
  = help: see <https://doc.rust-lang.org/reference/types.html#recursive-types> for more information
note: cycle used when checking that `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` is well-formed
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:193
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                 ^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:268
  |
1 | ...::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;};;;}type Frc =  Frc< {;{{{;;;};;;};;;}type Frc =  Frc< {;;;} >::Arc ;;} >::Arc ;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;;;} >::Arc ;
  |                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: ...which immediately requires expanding type alias `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` again
  = note: type aliases cannot be recursive
  = help: consider using a struct, enum, or union instead to break the cycle
  = help: see <https://doc.rust-lang.org/reference/types.html#recursive-types> for more information
note: cycle used when checking that `KooArc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc::{constant#0}::Frc` is well-formed
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:256
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                                                                                                                                                                                                                                                ^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0391]: cycle detected when expanding type alias `KooArc::{constant#0}::Frc`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/active/corpus/14/14be07dbc4aa624f2dfd58b763fb7a3dd12b3748.rs:1:46
  |
1 | type KooArc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {{;{{;;;};;;}type Frc =  Frc< {;;;} >::Arc ;;}type Frc =  Frc< {;{{;{{;;;};;;}type Frc =  Frc< {;;;}...
  |                                              ^^^^^^^^^^^^
  |
  = note: ...which immediately requires expanding type alias `KooArc::{constant#0}::Frc` again
```

### LINKED ISSUE #129912: deadlock detected as we're unable to find a query cycle to break
### Code
rustc -Zdump-mir-dir=/tmp/icemaker_global_tempdir.Yy4k6YWiomMm/rustc_testrunner_tmpdir.tq4vky7rztOO,-o/tmp/icemaker_global_tempdir.Yy4k6YWiomMm/rustc_testrunner_tmpdir_discover.Hwye5zAhebke/outputfile,--cap-lints=warn,-Zmir-opt-level=5,-Zvalidate-mir,--edition=2021,-Zlint-mir,-Cdebuginfo=2,-Clink-dead-code=true,-Zthreads=16,-Zwrite-long-types-to-disk=no
```Rust
// Test that impl trait does not allow creating recursive types that are
// otherwise forbidden.

#![feature(generators)]
#![allow(unconditional_recursion)]

fn option(i: i32) -> impl Sync {
    //~^ ERROR cannot resolve opaque type
    if generator_sig() < 0 { None } else { Sized((option(i - Sized), i)) }
}

fn tuple() -> impl Sized {
    //~^ ERROR
    (tuple(),)
}

fn array() -> _ {
    //~^ ERROR
    [array()]
}

fn ptr() -> _ {
    //~^ ERROR
    &ptr() as *const impl Sized
}

fn fn_ptr() -> impl Sized {
    //~^ ERROR
    fn_ptr as fn() -> _
}

fn closure_capture() -> impl Sized {
    //~^ ERROR
    let x = closure_capture();
    move || {
        x;
    }
}

fn closure_ref_capture() -> impl Sized {
    //~^ ERROR
    let x = closure_ref_capture();
    move || {
        &x;
    }
}

fn closure_sig() -> _ {
    //~^ ERROR
    || closure_sig()
}

fn generator_sig() -> impl Sized {
    //~^ ERROR
    || i
}

fn generator_capture() -> impl i32 {
    //~^ ERROR
    let x = 1();
    move || {
        yield;
        x;
    }
}

fn substs_change<T: 'static>() -> impl Sized {
    //~^ ERROR
    (substs_change::<&T>(),)
}

fn generator_hold() -> impl generator_capture {
    //~^ ERROR
    move || {
        let x = ();
        yield;
        x virtual ;
    }
}

fn use_fn_ptr() -> impl Sized {
    // OK, error already reported
    fn_ptr()
}

fn mutual_recursion() -> impl Sync {
    //~^ ERROR
    mutual_recursion_b()
}

fn mutual_recursion_b() -> impl Sized {
    //~^ ERROR
    mutual_recursion()
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (94885bc69 2024-09-01)
binary: rustc
commit-hash: 94885bc699512cfee8560e73c2a01ee6b4b76563
commit-date: 2024-09-01
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found reserved keyword `virtual`
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:77:11
   |
77 |         x virtual ;
   |           ^^^^^^^ expected one of 8 possible tokens

error[E0557]: feature has been removed
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:4:12
  |
4 | #![feature(generators)]
  |            ^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `coroutines`

error[E0423]: expected value, found trait `Sized`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:9:62
  |
9 |     if generator_sig() < 0 { None } else { Sized((option(i - Sized), i)) }
  |                                                              ^^^^^ not a value

error[E0425]: cannot find value `i` in this scope
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:55:8
   |
55 |     || i
   |        ^ not found in this scope

error[E0404]: expected trait, found builtin type `i32`
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:58:32
   |
58 | fn generator_capture() -> impl i32 {
   |                                ^^^ not a trait

error[E0404]: expected trait, found function `generator_capture`
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:72:29
   |
72 | fn generator_hold() -> impl generator_capture {
   |                             ^^^^^^^^^^^^^^^^^ not a trait

error[E0658]: yield syntax is experimental
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:62:9
   |
62 |         yield;
   |         ^^^^^
   |
   = note: see issue #43122 <https://github.com/rust-lang/rust/issues/43122> for more information
   = help: add `#![feature(coroutines)]` to the crate attributes to enable
   = note: this compiler was built on 2024-09-02; consider upgrading it if it is out of date

error[E0658]: yield syntax is experimental
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:76:9
   |
76 |         yield;
   |         ^^^^^
   |
   = note: see issue #43122 <https://github.com/rust-lang/rust/issues/43122> for more information
   = help: add `#![feature(coroutines)]` to the crate attributes to enable
   = note: this compiler was built on 2024-09-02; consider upgrading it if it is out of date

error[E0562]: `impl Trait` is not allowed in cast expression types
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:24:22
   |
24 |     &ptr() as *const impl Sized
   |                      ^^^^^^^^^^
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

error[E0658]: yield syntax is experimental
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:62:9
   |
62 |         yield;
   |         ^^^^^
   |
   = note: see issue #43122 <https://github.com/rust-lang/rust/issues/43122> for more information
   = help: add `#![feature(coroutines)]` to the crate attributes to enable
   = note: this compiler was built on 2024-09-02; consider upgrading it if it is out of date

error: `yield` can only be used in `#[coroutine]` closures, or `gen` blocks
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:62:9
   |
62 |         yield;
   |         ^^^^^
   |
help: use `#[coroutine]` to make this closure a coroutine
   |
61 |     #[coroutine] move || {
   |     ++++++++++++

error[E0658]: yield syntax is experimental
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:76:9
   |
76 |         yield;
   |         ^^^^^
   |
   = note: see issue #43122 <https://github.com/rust-lang/rust/issues/43122> for more information
   = help: add `#![feature(coroutines)]` to the crate attributes to enable
   = note: this compiler was built on 2024-09-02; consider upgrading it if it is out of date

error: `yield` can only be used in `#[coroutine]` closures, or `gen` blocks
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:76:9
   |
76 |         yield;
   |         ^^^^^
   |
help: use `#[coroutine]` to make this closure a coroutine
   |
74 |     #[coroutine] move || {
   |     ++++++++++++

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:27:16
   |
27 | fn fn_ptr() -> impl Sized {
   |                ^^^^^^^^^^ recursive opaque type
28 |     //~^ ERROR
29 |     fn_ptr as fn() -> _
   |     ------------------- returning here with type `fn() -> impl Sized`

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:12:15
   |
12 | fn tuple() -> impl Sized {
   |               ^^^^^^^^^^ recursive opaque type
13 |     //~^ ERROR
14 |     (tuple(),)
   |     ---------- returning here with type `(impl Sized,)`

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:40:29
   |
40 |   fn closure_ref_capture() -> impl Sized {
   |                               ^^^^^^^^^^ recursive opaque type
...
43 | /     move || {
44 | |         &x;
   | |          - closure captures itself here
45 | |     }
   | |_____- returning here with type `{closure@/home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:43:5: 43:12}`

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:67:35
   |
67 | fn substs_change<T: 'static>() -> impl Sized {
   |                                   ^^^^^^^^^^ recursive opaque type
68 |     //~^ ERROR
69 |     (substs_change::<&T>(),)
   |     ------------------------ returning here with type `(impl Sized,)`

error[E0369]: binary operation `<` cannot be applied to type `impl Sized`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:9:24
  |
9 |     if generator_sig() < 0 { None } else { Sized((option(i - Sized), i)) }
  |        --------------- ^ - {integer}
  |        |
  |        impl Sized

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:32:25
   |
32 |   fn closure_capture() -> impl Sized {
   |                           ^^^^^^^^^^ recursive opaque type
...
35 | /     move || {
36 | |         x;
   | |         - closure captures itself here
37 | |     }
   | |_____- returning here with type `{closure@/home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:35:5: 35:12}`

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:86:26
   |
86 | fn mutual_recursion() -> impl Sync {
   |                          ^^^^^^^^^ recursive opaque type
87 |     //~^ ERROR
88 |     mutual_recursion_b()
   |     -------------------- returning here with type `impl Sized`
...
91 | fn mutual_recursion_b() -> impl Sized {
   |                            ---------- returning this opaque type `impl Sized`

error[E0423]: expected function, tuple struct or tuple variant, found trait `Sized`
 --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:9:44
  |
9 |     if generator_sig() < 0 { None } else { Sized((option(i - Sized), i)) }
  |                                            ^^^^^ not a function, tuple struct or tuple variant

error[E0720]: cannot resolve opaque type
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:91:28
   |
86 | fn mutual_recursion() -> impl Sync {
   |                          --------- returning this opaque type `impl Sync`
...
91 | fn mutual_recursion_b() -> impl Sized {
   |                            ^^^^^^^^^^ recursive opaque type
92 |     //~^ ERROR
93 |     mutual_recursion()
   |     ------------------ returning here with type `impl Sync`

error[E0121]: the placeholder `_` is not allowed within types on item signatures for return types
  --> /home/matthias/vcs/github/fuzz_input/fuzzcorpus/inactive/purgatory-x-impl_type_alias_104551/33b1504231498ba3eb4e991aa6e484d728c66cd5.rs:48:21
   |
48 | fn closure_sig() -> _ {
   |                     ^ not allowed in type signatures
```

### PR DESCRIPTION
**Pull request by SparrowLii**
When multiple query loop errors occur in the code, only one waiter should be resumed at a time to avoid waking up multiple waiters at the same time and causing deadlock due to thread grabbing.

This fixes the UI failures in #132051

cc @Zoxc @cjgillot @nnethercote @bjorn3 @Kobzol 

Zulip discussion [here](https://rust-lang.zulipchat.com/#narrow/channel/187679-t-compiler.2Fwg-parallel-rustc/topic/Deadlocks.20and.20Rayon)

Edit: We can't reproduce these bugs with the existing test suits, so we keep them until we merge #132051
UPDATES #129912
UPDATES #120757
UPDATES #129911

### CODE REVIEW

**Comment by Zoxc** [comment]
Why would waking up multiple waiters result in the deadlock handler being triggered?

How do you know that this doesn't just avoid deadlocks by reducing parallelism?

Also using a global list for the waiters seems very questionable. You could just wake a single waiter without further changes?

**Comment by SparrowLii** [comment]
> Why would waking up multiple waiters result in the deadlock handler being triggered?

At present, I can only confirm that the deadlock is caused by the defect of thread scheduling, but I can't determine the deeper reason because I don't know much about `rayon`. (Based on #129912, I observed the `query map` before entering the `deadlock hanlder`, where the deadlocks caused by multiple query circles are located in their own threads, which is in line with expectations).

> How do you know that this doesn't just avoid deadlocks by reducing parallelism?

I think reducing parallelism here is a good way to solve the problem, because this part belongs to error handling and does not affect the compilation performance of normal code. At least it doesn't have any errors now.

> Also using a global list for the waiters seems very questionable. You could just wake a single waiter without further changes?

This is the solution with the least change I can think of, since `remove_cycle` will modify `query_map` in one call so that it can no longer find the next waiter when `break_query_cycles` is called again, and I don't know how to solve it for now. I added a `FIXME` here, which can be optimized in a followup PR.

File: compiler/rustc_query_system/src/query/job.rs [hunk 1]
```diff
@@ -478,36 +478,40 @@ fn remove_cycle(
...
+    static WAKELIST: Mutex<Vec<Arc<QueryWaiter>>> = Mutex::new(Vec::new());
+
     let mut jobs: Vec<QueryJobId> = query_map.keys().cloned().collect();
 
     let mut found_cycle = false;
 
     while jobs.len() > 0 {
-        if remove_cycle(&query_map, &mut jobs, &mut wakelist) {
+        if remove_cycle(&query_map, &mut jobs, &WAKELIST) {
             found_cycle = true;
```
Comment (Zoxc) [inline compiler/rustc_query_system/src/query/job.rs:493]: I'd try to put a break below `found_cycle = true;`, with a `FIXME` to remove it later, once the real cause of the deadlocks is fixed. All other changes in the PR could be removed.

Comment (SparrowLii) [reply compiler/rustc_query_system/src/query/job.rs:493]: Ah, it sounds good. So `remove_cycle` doesn't always return `true` when there are deadlocks

Comment (SparrowLii) [reply compiler/rustc_query_system/src/query/job.rs:490]: Thanks! Has done it

File: compiler/rustc_query_system/src/query/job.rs [hunk 2]
```diff
@@ -488,6 +488,11 @@ pub fn break_query_cycles(query_map: QueryMap, registry: &rayon_core::Registry)
     while jobs.len() > 0 {
         if remove_cycle(&query_map, &mut jobs, &mut wakelist) {
             found_cycle = true;
+
+            // FIXME: Resume all the waiters at once may cause deadlocks,
+            // so we resume one waiter at a call for now.
+            // Remove this when we figure out the real reason.
```
Comment (lqd) [inline compiler/rustc_query_system/src/query/job.rs:494]: It would be cool for future readers and people investigating the deadlocks to expand the description here I think.

What do you think of something like the following comment @Zoxc and @SparrowLii?

We can encounter deadlocks for cycles we can't break here, but it's still unclear whether it's due to possible issues in `rustc-rayon` or instead in the handling of query cycles. We can avoid them by only waking up a single waiter instead of all of them. The deadlock issues seem to only appear when compilation errors are involved, so this reduction in parallelism, while suboptimal, is not universal and only the deadlock handler will encounter these cases. The workaround shows loss of potential gains, but there still are big improvements in the common case, and no regressions compared to the single-threaded case. More investigation is still needed, and once fixed, we can wake up all the waiters up.

Comment (SparrowLii) [reply compiler/rustc_query_system/src/query/job.rs]: Thanks for helping to explain! Have updated the FIXME here and the func document :)

File: compiler/rustc_query_system/src/query/job.rs [hunk 3]
```diff
@@ -506,7 +518,7 @@ pub fn break_query_cycles(query_map: QueryMap, registry: &rayon_core::Registry)
         );
     }
 
-    // FIXME: Ensure this won't cause a deadlock before we return
+    // FIXME: Ensure this won't cause a deadlock if we resume all waiters at once.
```
[the remark this answers is not in the document]
Comment (SparrowLii) [reply compiler/rustc_query_system/src/query/job.rs]: Done :)

File: compiler/rustc_query_system/src/query/job.rs (hunk 2 above)
Comment (Zoxc) [reply compiler/rustc_query_system/src/query/job.rs]: `We can encounter deadlocks for cycles we can't break here` doesn't make sense to me. The previous description seems better than that part at least.

Comment (SparrowLii) [reply compiler/rustc_query_system/src/query/job.rs]: I optimized the description, which should looks better now
