### PR TITLE
Fix E0191 suggestion for empty dyn trait args

### LINKED ISSUE #155578: Invalid Suggestion in "specify the associated type" help
### Code

```Rust
trait Meow {
    type Assoc;
}

struct Cat;

impl Meow for Cat {
    type Assoc = i32;
}

fn main() {
    let cat = Cat;
    let d: &dyn Meow<> = &cat;
}
```

### Current output

```Shell
error[E0191]: the value of the associated type `Assoc` in `Meow` must be specified
  --> src/main.rs:13:17
   |
 2 |     type Assoc;
   |     ---------- `Assoc` defined here
...
13 |     let d: &dyn Meow<> = &cat;
   |                 ^^^^^^
   |
help: specify the associated type
   |
13 |     let d: &dyn Meow<, Assoc = /* Type */> = &cat;
   |                      ++++++++++++++++++++
```

### Desired output

```Shell
help: specify the associated type
   |
13 |     let d: &dyn Meow<Assoc = /* Type */> = &cat;
   |                      ++++++++++++++++++
```

### Rationale and extra context

When using an empty `<>` to specify no associated types (this is actually valid if there are no associated types), the compiler suggests adding a leading comma inside the `<>`, but this is invalid.

### Rust Version

```Shell
rustc 1.96.0-nightly (900485642 2026-04-08)
binary: rustc
commit-hash: 900485642855f4729d926ecf24680a791f9293cf
commit-date: 2026-04-08
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.2
```

@rustbot label +D-invalid-suggestion

### PR DESCRIPTION
**Pull request by qaijuang**
Fixes rust-lang/rust#155578.

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs [hunk 1]
```diff
@@ -1115,12 +1115,13 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
...
             let code = if let Some(snippet) = snippet.strip_suffix('>') {
+                // Don't insert a leading comma for empty generic args like `dyn Trait<>`.
+                let separator = if snippet.trim_end().ends_with('<') { "" } else { ", " };
                 // The user wrote `Trait<'a>` or similar and we don't have a term we can suggest,
                 // but at least we can clue them to the correct syntax `Trait<'a, Item = /* ... */>`
                 // while accounting for the `<'a>` in the suggestion.
-                format!("{}, {}>", snippet, bindings.join(", "))
+                format!("{snippet}{separator}{}>", bindings.join(", "))
             } else if in_expr_or_pat {
                 // The user wrote `Trait`, so we don't have a term we can suggest, but at least we
```
Comment (Kivooeo) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs]:
```suggestion
            let code = if let Some(snippet) = snippet.strip_suffix("<>") {
                // Empty generics
                format!("{snippet}<{}>", bindings.join(", "))
            } else if let Some(snippet) = snippet.strip_suffix('>') {
                // Non-empty generics
                format!("{snippet}, {}>", bindings.join(", "))
            } else if in_expr_or_pat {
                // ...
            };
```

Here is prototype that I haven't tested, but, something like this should be easier to read and follow

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155637/cf1817bc6ecd2d14ca492247c804bad31948dd56..bda04580f891146a69e1bba9dcdcde1c0eeccabd)*

File: tests/ui/traits/empty-dyn-trait-args-suggestion-issue-155578.rs
Comment (fmease) [inline tests/ui/traits/empty-dyn-trait-args-suggestion-issue-155578.rs:1]: Could you please look for an existing test file that exercises this diagnostic and add the test case there? Of course, you should keep the reference to the GH issue in a comment above it.

This is super niche and doesn't warrant its own file. 

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155637/cf1817bc6ecd2d14ca492247c804bad31948dd56..bda04580f891146a69e1bba9dcdcde1c0eeccabd)*

**Comment by asquared31415** [comment]
I believe this issue also applies to non-dyn trait specifiers too, as in `arg: impl Meow<>` or in generic bounds. it's probably worth a test case for non-dyn too, just in case?

**Comment by fmease** [comment]
I'm not sure this is super warranted. This is a super niche issue that affects all *trait refs*.

**Comment by fmease** [comment]
Thanks! @bors r+
