### PR TITLE
Fix underflow in specialized ZipImpl::size_hint

### LINKED ISSUE #82282: Side effect handling in specialized zip implementation causes buffer overflow
https://github.com/rust-lang/rust/blob/0148b971c921a0831fbf3357e5936eec724e3566/library/core/src/iter/adapters/zip.rs#L200-L208

https://github.com/rust-lang/rust/blob/0148b971c921a0831fbf3357e5936eec724e3566/library/core/src/iter/adapters/zip.rs#L214-L218

`self.index` can be set to a value greater than `self.len` in this branch. This causes integer overflow in `size_hint()` and lead to a buffer overflow.

[Playground Link](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=0e6f0c70e6aaaba62610f19fd9186756) that demonstrates segfault with safe Rust code.

### PR DESCRIPTION
**Pull request by SkiFire13**
Fixes #82282

### CODE REVIEW

File: library/core/src/iter/adapters/zip.rs [hunk 1]
```diff
@@ -200,6 +200,7 @@ where
         } else if A::may_have_side_effect() && self.index < self.a.size() {
             let i = self.index;
             self.index += 1;
+            self.len += 1;
```
Comment (sdroege) [inline library/core/src/iter/adapters/zip.rs:203]: Doesn't this break the `TrustedLen` (and `TrustedRandomAccess`) impls? The "length" that is reported would not be constant any longer, and it would after this branch be bigger than the number of items being returned.

Or maybe I'm missing something :)

Comment (SkiFire13) [reply library/core/src/iter/adapters/zip.rs:203]: Quite the opposite, the increment of `self.len` bilances the previous increment of `self.index`, keeping their difference (and `size_hint`) constant. 

The bug was in fact that incrementing `self.index` changed the `size_hint` when it shouldn't.

Comment (sdroege) [reply library/core/src/iter/adapters/zip.rs:203]: Thanks! Might be worth adding a comment about that somewhere so the next person reading the code doesn't have the same question, and that it's ideally considered when changing something around that code in the future :)

Comment (SkiFire13) [reply library/core/src/iter/adapters/zip.rs:203]: I was already considering writing a follow-up PR that properly documents the safety of ZipImpl, especially around the state of `index` and `len`

Comment (sdroege) [reply library/core/src/iter/adapters/zip.rs:203]: Sounds like a good plan

**Review by kennytm — APPROVED** [review]

**Comment by SkiFire13** [comment]
@kennytm is that supposed to be the same as an `r+`? Sorry, but this is my first time seeing that in this repository

**Comment by Qwaz** [comment]
I'm not sure if this fix interacts well with `next_back()`'s length handling. Say we are using iterators with length 1 for both A and B.

1. Initialize zip
  * index = 0, len = 1
2. Call `next_back()`
  * index = 0, len = 0
  * `get_unchecked(0)` is called on both A and B
3. Call `next()`
  * Since `self.index < self.a.size()`, `get_unchecked(0)` is called again on A
  * index = 1, len = 1

Calling `get_unchecked()` on the same index twice is a violation of the second safety invariant of `TrustedRandomAccess` and can lead to duplicated elements.

**Comment by Qwaz** [comment]
Oh, was this already possible even before the fix?

**Comment by SkiFire13** [comment]
> Oh, was this already possible even before the fix?

Yes, it was and this PR wasn't aimed to fix it. I've already opened #82291 a couple of hours ago showing how it can be exploited and #82292 to fix it, unfortunately it conflicts with this PR (both add a test at the end of the same file).

**Comment by bluss** [comment]
It's worth considering if the fix that moved the increment of `index` can be reverted

**Comment by SkiFire13** [comment]
> It's worth considering if the fix that moved the increment of index can be reverted.

What does that have to do with the bug this PR should fix?

> Alternatively - would it be better to rewrite the whole zip specialization in terms of a "next_unchecked" method instead, and would that be more robust?

A discussion about that started [here](https://github.com/rust-lang/rust/issues/82291#issuecomment-782313655), then we moved on zulip ([here](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Improving.20TrustedRandomAccess.20and.20its.20Zip.20specialization/near/227088066)). Anyway I thought [you already ruled out](https://github.com/rust-lang/rust/pull/33090#issuecomment-212998513) a `next_unchecked` approach because LLVM had more trouble to optimize it (and I think it still has).

**Comment by bluss** [comment]
> What does that have to do with the bug this PR should fix?

Hm, oh I thought this issue was directly caused by that, but on new reading you're right, it's not related, sorry about that.

Anything from 2016 could of course be reevaluated 🙂

**Comment by m-ou-se** [comment]
@SkiFire13 Can you resolve the merge conflict?
