### PR TITLE
Use correct line offsets for doctests

### LINKED ISSUE #45868: rustdoc: very unhelpful span info
Do the following:

```
git clone https://github.com/rust-onig/rust-onig
cd rust-onig
git checkout 2381ea7fdc4b2dfef0905181cf26aa21b5a2ab17
git submodule update --init
cargo doc
```

Will yield the following output:

```
$ cargo doc
   Compiling onig_sys v66.1.1 (file://~/src/rust-onig/onig_sys)
 Documenting onig_sys v66.1.1 (file://~/src/rust-onig/onig_sys)
error: unknown start of token: `
 --> <stdin>:1:1
  |
1 | ```c
  | ^
  |
help: unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it's not
 --> <stdin>:1:1
  |
1 | ```c
  | ^

error: Could not document `onig_sys`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name onig_sys onig_sys/src/lib.rs -o ~/src/rust-onig/target/doc -L dependency=~/src/rust-onig/target/debug/deps --extern libc=~/src/rust-onig/target/debug/deps/liblibc-db55a80d54675fa5.rlib` (exit code: 101)
```

This is very hard to debug! Which "```" section does Rust error on? Rustdoc should provide good and clear span info on this, with line numbers relative to the file, not relative to something else.

I could only debug this through removing each single ``` section and checking whether the error persists. This way I've found out that the following section is causing this:

```rust
    ///   Iterate function call for all names.
    ///
    ///  `int onig_foreach_name(regex_t* reg,
    ///                         int (*func)(const UChar*, const UChar*, int,int*,regex_t*,void*),
    ///                         void* arg)`
    ///
    /// # Returns
    ///
    ///  * normal return: 0
    ///  * error:         func's return value.
    ///
    /// # Arguments
    ///
    ///   1. reg:     regex object.
    ///   2. func:    callback function.
    ///
    ///     ```c
    ///     func(name, name_end, <number of groups>, <group number's list>,
    ///          reg, arg);
    ///     ```
    ///
    ///     if func does not return 0, then iteration is stopped.
    ///   3. arg:     argument for func.
    pub fn onig_foreach_name(reg: OnigRegex,
```

### PR DESCRIPTION
**Pull request by Manishearth**
Not yet tested.

This doesn't handle char positions. It could if I collected a map of char offsets and lines, but this is a bit more work and requires hooking into the parser much more (unsure if it's possible).

r? @QuietMisdreavus

(fixes #45868)

### CODE REVIEW

**Comment by Manishearth** [comment]
this solution is currently incorrect, ignore it for now

**Comment by Manishearth** [comment]
Ready for review. r? @QuietMisdreavus

**Comment by Manishearth** [comment]
Need to write a test, unsure where it should go. maketest perhaps?

File: src/librustdoc/test.rs [hunk 1]
```diff
@@ -341,23 +345,27 @@ pub fn make_test(s: &str,
...
     // Next, any attributes that came from the crate root via #![doc(test(attr(...)))].
     for attr in &opts.attrs {
         prog.push_str(&format!("#![{}]\n", attr));
+        line_offset += 1;
     }
 
     // Now push any outer attributes from the example, assuming they
     // are intended to be crate attributes.
     prog.push_str(&crate_attrs);
+    line_offset += crate_attrs.lines().count();
```
Comment (QuietMisdreavus) [inline src/librustdoc/test.rs]: Is `line_offset` supposed to be the number of lines inserted by rustdoc? IIRC, `crate_attrs` is actually the `#![]` attributes from the example itself.

**Comment by QuietMisdreavus** [comment]
Nice! If i'm looking at this correctly, this will help map between the line that rustc reports an error at, and the line in the actual doctest that was responsible for it? Do we already map these lines back to the file it's in? I'm thinking about this in terms of getting the lines to work with `doc(include)`. That doesn't have to be this PR - it looks like this was an issue before that came in.

Re: where/how to test this, i'd take a look at whether/where the regular line number reporting is tested, and seeing if you can piggyback onto that by making it call `rustdoc --test` instead.

File: src/librustdoc/test.rs (hunk 1 above)
Comment (Manishearth) [reply src/librustdoc/test.rs]: Yeah, you're right. Given that the attrs can only be up top we should just not count this.

**Comment by Manishearth** [comment]
> this will help map between the line that rustc reports an error at, and the line in the actual doctest that was responsible for it? 

yeah.

> Do we already map these lines back to the file it's in?

We say "foobar.rs - itemname (line N)". But then the rustc error shows `<stdin>:line:col` which is wrong.

**Comment by Manishearth** [comment]
Added test. The existing stuff isn't easy to rejigger; it's built around assuming rustc. I just wrote a simple run-make test.

**Comment by QuietMisdreavus** [comment]
Seems good to me. Let's get this in!

@bors r+

**Review by QuietMisdreavus — APPROVED** [review]
