### PR TITLE
recursion_limit parsing handles overflows

### LINKED ISSUE #67265: Recursion limit silently ignored if it overflows a `usize`
The following code [fails to compile](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8b1e97d1ea8d2a581bd5024935dea292) since it exceeds the default recursion limit. Using `2056` as the recursion limit works as expected.

```rust
#![recursion_limit = "99999999999999999999999999999999999999999999999999999"]
//#![recursion_limit = "2056"]

macro_rules! explode {
    (recurse; $head:tt $($tail:tt)*) => { explode!(recurse; $($tail)*); };
    (recurse;) => {};
    
    (0; $($tt:tt)*) => { explode!(1; $($tt)* $($tt)* $($tt)*); };
    (1; $($tt:tt)*) => { explode!(2; $($tt)* $($tt)* $($tt)*); };
    (2; $($tt:tt)*) => { explode!(3; $($tt)* $($tt)* $($tt)*); };
    (3; $($tt:tt)*) => { explode!(recurse; $($tt)* $($tt)* $($tt)*); };
}

explode!(0; a b c);
```

This is because we don't check for integer overflow errors when parsing limits:

https://github.com/rust-lang/rust/blob/e9469a6aec2f49fa1e2ae670649f293866932253/src/librustc/middle/recursion_limit.rs#L19-L33

There's a few options here. My preference would be to silently default to `usize::MAX` when overflow occurs.

This issue has been assigned to @fisherdarling via [this comment](https://github.com/rust-lang/rust/issues/67265#issuecomment-565265070).

### PR DESCRIPTION
**Pull request by fisherdarling**
This PR adds overflow handling to `#![recursion_limit]` attribute parsing. If parsing the given value results in an `IntErrorKind::Overflow`, then the recursion_limit is set to `usize::max_value()`.

closes #67265

### CODE REVIEW

**Comment by hellow554** [comment]
Can we add a test for this? Not sure how though.

File: src/librustc/middle/recursion_limit.rs [hunk 1]
```diff
@@ -23,9 +24,16 @@ fn update_limit(krate: &ast::Crate, limit: &Once<usize>, name: Symbol, default:
...
-            if let Some(n) = s.as_str().parse().ok() {
-                limit.set(n);
-                return;
+            match s.as_str().parse() {
+                Ok(n) => {
+                    limit.set(n);
+                    return;
+                }
+                Err(e) if e.kind() == &IntErrorKind::Overflow => {
+                    limit.set(usize::max_value());
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]: I would prefer to also emit a warning here, saying that the recursion limit is too high and has been capped.

**Review by varkor — CHANGES_REQUESTED** [review]
We should add a test for this. Other than that, and adding a warning, this change looks good.

File: src/librustc/middle/recursion_limit.rs (hunk 1 above)
Comment (Centril) [reply src/librustc/middle/recursion_limit.rs]: Why not just error?

Comment (hellow554) [reply src/librustc/middle/recursion_limit.rs]: Is a recursion limit of more than `65536` realisitic? If no, then error IMHO

Comment (estebank) [reply src/librustc/middle/recursion_limit.rs]: I think we should always emit an error and for all parse failures: `#![recursion_limit = "qwer"]`, `#![recursion_limit = "999999999999999999999"]` and `#![recursion_limit = ""]` should all be emitting an error with specific wording. The overflow case should provide a structured suggestion for `std::usize::MAX` and the other cases should suggest the default `128`.

Comment (ecstatic-morse) [reply src/librustc/middle/recursion_limit.rs]: A hard error would not be strictly backwards compatible. Is this okay?

Comment (Centril) [reply src/librustc/middle/recursion_limit.rs]: Backwards-compatibility, for things we offer such guarantees, is interpreted by the language team in a "does this *actually* break people in practice?"-way. Feel free to crater this, but I have a feeling that no realistic program should be overflowing `usize::max_value()`.

Comment (fisherdarling) [reply src/librustc/middle/recursion_limit.rs]: I'll add errors for the different parse failures and add a specific suggestion for overflows. In terms of testing, could somebody point me to a good resource that describes testing for error output.

Thanks for all of the input.

**Comment by hellow554** [comment]
@fisherdarling an introduction to the various test directories and functions can be found at https://rust-lang.github.io/rustc-guide/tests/intro.html
I would suggest using the `ui` directory. But I'm not sure if you should use a new subdirectory (maybe yes, because you will likely end up with a few files (around 4-ish) and they should be grouped together).

**I** would add a folder in `test/ui` called `recursion_limit` and add a few files (e.g. `normal.rs`, `overflowing.rs`, `invalid_number.rs`, `...`) and then let the compiler run it (`./x.py test --stage=1 ui/recursion_limit` (not entirely sure about the syntax, try a few things)) and then add the `.ui` files for it (you can generate them by using `--bless` for your `x.py`

**Comment by fisherdarling** [comment]
@hellow554 This is some good advice, thank you!

**Comment by Dylan-DPC** [comment]
@fisherdarling any updates on this?

**Comment by fisherdarling** [comment]
@Dylan-DPC Currently starting a new semester, I'm planning on getting an update out this weekend!

File: src/librustc/middle/recursion_limit.rs [hunk 2]
```diff
@@ -6,26 +6,57 @@
...
+                    
+                    match e.kind() {
+                        IntErrorKind::Overflow => {
+                            err.span_label(attr.span, "the recursion_limit overflowed a `usize`");
+                        }
+                        IntErrorKind::Empty => {
+                            err.span_label(attr.span, "the recursion_limit must be a positive integer");
+                        }
+                        IntErrorKind::Underflow => {
+                            // A negative number will be caught by the invalid digit handler.
```
Comment (fisherdarling) [inline src/librustc/middle/recursion_limit.rs]: Would you like me to explicitly handle this case? Though I cannot seem to test it.

File: src/librustc/middle/recursion_limit.rs [hunk 3]
```diff
@@ -6,26 +6,57 @@
...
+                        },
+                        IntErrorKind::Zero => {
```
Comment (fisherdarling) [inline src/librustc/middle/recursion_limit.rs]: I feel like `#![recursion_limit = "0"]` would generally be a mistake. Should I make that error?

**Comment by fisherdarling** [comment]
@Dylan-DPC Ready for any comments

File: src/librustc/middle/recursion_limit.rs (hunk 3 above)
Comment (hellow554) [reply src/librustc/middle/recursion_limit.rs]: https://doc.rust-lang.org/std/num/enum.IntErrorKind.html#variant.Zero: 

> This variant will be emitted when the parsing string has a value of zero, which would be illegal for non-zero types.

so it has nothing to do with this

File: src/librustc/middle/recursion_limit.rs [hunk 4]
```diff
@@ -6,26 +6,64 @@
...
+                            return;
+                        }
+                        IntErrorKind::InvalidDigit => {
+                            err.span_label(attr.span, "invalid digit in the attribute value");
+                        }
+                        _ => (),
+                    }
+
+                    err.emit();
+                }
```
Comment (hellow554) [inline src/librustc/middle/recursion_limit.rs]: Not my code and my style, but I wouldn't use the `span_label` in every match arm, but instead use the match to set the error message ot `err.span_label` itself, e.g. `err.span_label(attr.span, match e.kind() { ... })`. But that's up to you

File: src/librustc/middle/recursion_limit.rs (hunk 2 above)
Comment (hellow554) [reply src/librustc/middle/recursion_limit.rs]: Hmm, would it hurt to explicitly handle it? If yes, you could use the [`bug!` macro](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/macro.bug.html).

File: src/librustc/middle/recursion_limit.rs [hunk 5]
```diff
@@ -6,26 +6,64 @@
...
-            if let Some(n) = s.as_str().parse().ok() {
-                limit.set(n);
-                return;
+            match s.as_str().parse() {
+                Ok(n) => {
+                    limit.set(n);
+                    return;
+                }
+                Err(e) => {
+                    let mut err = sess.struct_span_err(attr.span, "recursion_limit parsing");
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]: Could you point to the span of the value, or the entire attribute if there is no value?

Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                    let mut err = sess.struct_span_err(attr.span, "`recursion_limit` must be a non-negative integer");
```

File: src/librustc/middle/recursion_limit.rs (hunk 2 above)
Comment (varkor) [reply src/librustc/middle/recursion_limit.rs]: I would use `bug!` here, as @hellow554 suggests.

File: src/librustc/middle/recursion_limit.rs (hunk 3 above)
Comment (varkor) [reply src/librustc/middle/recursion_limit.rs]: These are for the `NonZero*` types, which this isn't going to produce, so you can `bug!` here too (and make sure we have a test for `recursion_limit = 0`, which should allow no macro expansion).

File: src/librustc/middle/recursion_limit.rs (hunk 4 above)
Comment (varkor) [reply src/librustc/middle/recursion_limit.rs]: Yes, let's return the string in each arm and then `err_span.label` after the `match`.

File: src/librustc/middle/recursion_limit.rs [hunk 6]
```diff
@@ -6,26 +6,64 @@
...
+                        IntErrorKind::Underflow => {
+                            // A negative number will be caught by the invalid digit handler.
+                        }
+                        IntErrorKind::Zero => {
+                            err.cancel();
+                            limit.set(default);
+                            return;
+                        }
+                        IntErrorKind::InvalidDigit => {
+                            err.span_label(attr.span, "invalid digit in the attribute value");
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                            err.span_label(attr.span, "not a valid integer");
```
"invalid digit" is a little confusing, because it suggests the invalid character may be a digit (which is not the case for a letter, for instance).

File: src/librustc/middle/recursion_limit.rs [hunk 7]
```diff
@@ -6,26 +6,64 @@
...
+                Ok(n) => {
+                    limit.set(n);
+                    return;
+                }
+                Err(e) => {
+                    let mut err = sess.struct_span_err(attr.span, "recursion_limit parsing");
+
+                    match e.kind() {
+                        IntErrorKind::Overflow => {
+                            err.span_label(attr.span, "the recursion_limit overflowed a `usize`");
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                            err.span_label(attr.span, "the `recursion_limit` is too large");
```
I think unless [the reference](https://doc.rust-lang.org/reference/attributes/limits.html#the-recursion_limit-attribute) says otherwise, we should avoid specifying exactly what the maximum size is, and be a little vague.

**Review by varkor — CHANGES_REQUESTED** [review]
Thanks for adding the tests, @fisherdarling! Just a few comments.

**Comment by joelpalmer** [comment]
Ping from Triage: any updates @fisherdarling?

**Comment by fisherdarling** [comment]
@joelpalmer Thanks for checking in. I'll get an update out tonight

File: src/librustc/middle/recursion_limit.rs (hunk 5 above)
Comment (fisherdarling) [reply src/librustc/middle/recursion_limit.rs]: I think I did this correctly... Look at the blessed stderr files for what it looks like.

File: src/test/ui/recursion_limit/zero.stderr [hunk 8]
```diff
@@ -0,0 +1,10 @@
+error: recursion limit reached while expanding the macro `test`
```
Comment (fisherdarling) [inline src/test/ui/recursion_limit/zero.stderr]: The PR test pipeline fails on this test. On my local machine the test passes, on the Azure machine, the error message is 
```
error: recursion limit reached while expanding `test!`
```
Missing "the macro" and inserting a "!". Any suggestions on what's different?

Comment (ecstatic-morse) [reply src/test/ui/recursion_limit/zero.stderr]: It's likely that the error message changed in the latest version of rust. You can either rebase, rebuild and rebless, or you could just copy the CI output into your branch.

File: src/librustc/middle/recursion_limit.rs [hunk 9]
```diff
@@ -6,26 +6,58 @@
...
+                    limit.set(n);
+                    return;
+                }
+                Err(e) => {
+                    let mut err = sess.struct_span_err(attr.span, "recursion_limit parsing");
+
+                    let value_span = attr
+                        .meta()
+                        .map(|meta| meta.name_value_literal().map(|lit| lit.span))
+                        .flatten()
```
Comment (hellow554) [inline src/librustc/middle/recursion_limit.rs]: `.map().flatten()` => `flat_map`

File: src/librustc/middle/recursion_limit.rs (hunk 5 above)
Comment (varkor) [reply src/librustc/middle/recursion_limit.rs]: This change doesn't seem to have been made.

File: src/librustc/middle/recursion_limit.rs [hunk 10]
```diff
@@ -6,26 +6,58 @@
...
+                        .and_then(|meta| meta.name_value_literal().cloned())
+                        .map(|lit| lit.span)
+                        .unwrap_or(attr.span);
+
+                    let error_str = match e.kind() {
+                        IntErrorKind::Overflow => "the `recursion_limit` is too large",
+                        IntErrorKind::Empty => "the `recursion_limit` must be a positive integer",
+                        IntErrorKind::InvalidDigit => "not a valid integer",
+                        IntErrorKind::Underflow => {
+                            rustc::bug!("`recursion_limit` should never underflow")
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]: Just for consistency, could you import `rustc::bug`, so you can just use it as `bug!` here?

File: src/librustc/middle/recursion_limit.rs [hunk 11]
```diff
@@ -6,26 +6,58 @@
...
+                    let mut err = sess.struct_span_err(attr.span, "recursion_limit parsing");
+
+                    let value_span = attr
+                        .meta()
+                        .and_then(|meta| meta.name_value_literal().cloned())
+                        .map(|lit| lit.span)
+                        .unwrap_or(attr.span);
+
+                    let error_str = match e.kind() {
+                        IntErrorKind::Overflow => "the `recursion_limit` is too large",
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                        IntErrorKind::Overflow => "`recursion_limit` is too large",
```

File: src/librustc/middle/recursion_limit.rs [hunk 12]
```diff
@@ -6,26 +6,58 @@
...
+                        IntErrorKind::Empty => "the `recursion_limit` must be a positive integer",
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                        IntErrorKind::Empty => "`recursion_limit` must be a positive integer",
```

**Comment by varkor** [comment]
@fisherdarling: thanks! Could you squash your commits together? We avoid merge commits in the Rust repo.

File: src/librustc/middle/recursion_limit.rs [hunk 13]
```diff
@@ -6,26 +6,60 @@
...
+
+                    let value_span = attr
+                        .meta()
+                        .and_then(|meta| meta.name_value_literal().cloned())
+                        .map(|lit| lit.span)
+                        .unwrap_or(attr.span);
+
+                    let error_str = match e.kind() {
+                        IntErrorKind::Overflow => "`recursion_limit` is too large",
+                        IntErrorKind::Empty => "`recursion_limit` must be a positive integer",
```
Comment (varkor) [inline src/librustc/middle/recursion_limit.rs]:
```suggestion
                        IntErrorKind::Empty => "`recursion_limit` must be a non-negative integer",
```
We were sending mixed messages before.

**Review by varkor — COMMENTED** [review]
Sorry for taking a while to review this again. I spotted one last thing — but after this, everything looks good! (Something seems to have happened to the committer information when you rebased, as you're listed twice, but only one is linked with your GitHub account, which you might want to look at, but it's not a big problem.)

**Comment by JohnCSimon** [comment]
Ping from triage: @fisherdarling - can you please address the comments and changes from varkor?
 thanks.

**Comment by fisherdarling** [comment]
@varkor Finished up! I hope it looks good now. Thanks for all of the help! Apologies for my delay in getting this wrapped up.

**Comment by hellow554** [comment]
the `.stderr` file must be updated. You can do that with the `--bless` flag to `x.py`

**Comment by hellow554** [comment]
After two months I think we're done.

@Varkor any last concerns?

**Comment by varkor** [comment]
@fisherdarling: thanks for bearing with all the comments! This looks good to go now!
And thanks @hellow554 for helping with the review.

@bors r=varkor,hellow554 rollup
