### PR TITLE
Check importing `crate`/`$crate`/`super` after handling `self`

### LINKED ISSUE #152997: `super` used in the middle of path is incorrectly accepted
The first import in the following example should fail ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=1a70e804a054679526c7901474e96e11)):

```rust
pub mod x {
    pub use crate::x::super::{self as crate1}; // OK but should ERROR
    pub use crate::x::self::super::{self as crate2}; //~ ERROR `self` in paths can only be used in start position

    pub fn foo() {}
}

fn main() {
    x::crate1::x::foo();
    x::crate2::x::foo();
    
    crate::x::super::x::foo(); //~ ERROR `super` in paths can only be used in start position
    crate::x::self::super::x::foo(); //~ ERROR `self` in paths can only be used in start position
}
```

Version

> Build using the Nightly version: 1.95.0-nightly
> (2026-02-21 5fb2ff8611e5a4af4dc8)

### PR DESCRIPTION
**Pull request by mu001999**
Fixes https://github.com/rust-lang/rust/issues/152997

r? petrochenkov

### CODE REVIEW

File: compiler/rustc_resolve/src/build_reduced_graph.rs [hunk 1]
```diff
@@ -664,45 +693,14 @@ impl<'a, 'ra, 'tcx> BuildReducedGraphVisitor<'a, 'ra, 'tcx> {
                             return;
                         }
                     }
-                    kw::SelfLower => {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/build_reduced_graph.rs:667]: It looks like moving the code wasn't necessary, could you keep it in its old place?
Now I don't see what the actual difference is.

Comment (mu001999) [reply compiler/rustc_resolve/src/build_reduced_graph.rs:667]: This moving is necessary because it will assign source with parent, the code itself is same in fact.
