### PR TITLE
When possible point at argument causing item obligation failure

### LINKED ISSUE #36775: Suboptimal error reporting of invalid argument to generic function
The following code produces two compilation errors.

``` rust
use std::fmt::Display;

fn main() {
    let _ = Vec::with_capacity("0"); // error #1

    displayer(()); // error #2
}

fn displayer<T: Display>(t: T) {
    println!("{}", t);
}
```
### Error 1

```
error[E0308]: mismatched types
 --> <anon>:4:32
  |
4 |     let _ = Vec::with_capacity("0"); // error #1
  |                                ^^^ expected usize, found reference
  |
  = note: expected type `usize`
  = note:    found type `&'static str`
```

The first error looks great. The compiler points at the erroneous argument.
### Error 2

```
error[E0277]: the trait bound `(): std::fmt::Display` is not satisfied
 --> <anon>:6:5
  |
6 |     displayer(()); // error #2
  |     ^^^^^^^^^ trait `(): std::fmt::Display` not satisfied
  |
  = note: `()` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
  = note: required by `displayer`
```

In the second error, however, the compiler points at the function instead of the erroneous argument. This is no big problem in this case, as the function only takes one argument, and the argument has a very simple type. But in more complex functions, it might be hard to figure out which argument is problematic.

### LINKED ISSUE #41781: Error when trait bound not satisfied for function argument should point at argument
```rust
trait T {}

fn function<U: T>(u: U) {}

fn main() {
    function(0u32);
}
```
This yields:
```
error[E0277]: the trait bound `u32: T` is not satisfied
 --> <anon>:6:5
  |
6 |     function(0u32);
  |     ^^^^^^^^ the trait `T` is not implemented for `u32`
  |
  = note: required by `function`

error: aborting due to previous error
```

When there are multiple arguments, this is much less helpful than if the span pointed at the argument in question.

### LINKED ISSUE #42855: Confusing error on mismatched argument count of function parameters
Example:

```rust
fn main() {
    bar(1, foo);
}

fn foo(a: u16) {}

fn bar<F>(a: u16, mut f: F) where F: FnMut(u16, u8) {
    f(a, 0);
}
```

The problem is the second argument in the `bar` call (`foo`) takes only one argument instead of the expected 2 arguments. However, the error looks like there is something wrong with the argument count of the `bar` call:

Error on nightly & beta:
```
error[E0593]: function takes 1 argument but 2 arguments are required
 --> <anon>:2:5
  |
2 |     bar(1, foo);
  |     ^^^ expected function that takes 2 arguments
  |
  = note: required by `bar`
```

Error on stable:

```
error[E0281]: type mismatch: the type `fn(u16) {foo}` implements the trait `std::ops::FnMut<(u16,)>`, but the trait `std::ops::FnMut<(u16, u8)>` is required (expected a tuple with 2 elements, found one with 1 elements)
 --> <anon>:2:5
  |
2 |     bar(1, foo);
  |     ^^^
  |
  = note: required by `bar`
```

Instead, the `^^^` should point to the faulty argument:

```
error[E0593]: function takes 1 argument but 2 arguments are required
 --> <anon>:2:5
  |
2 |     bar(1, foo);
  |            ^^^ expected function that takes 2 arguments
  |
  = note: required by `bar`
```

cc @oli-obk

### LINKED ISSUE #46658: Errors with incorrectly typed parameters to trait functions incorrectly point to function
When a parameter of an unexpected type is passed to a trait function, the resulting error message points to the function and not the parameter. Since the function is defined elsewhere (perhaps in another crate altogether), clearly the error is with the _parameter_ and the error message should be altered to reflect that by pointing to the parameter.

Example:

```rust
debug!("expected signature: {}", base64::encode(&hmac.result()));
```

generates the following error:

```rust
   Compiling messagebridge v0.2.0 (file:///Users/mqudsi/Projects/messagebridge)
error[E0277]: the trait bound `crypto::mac::MacResult: std::convert::AsRef<[u8]>` is not satisfied
   --> src/incoming.rs:141:42
    |
141 |         debug!("expected signature: {}", base64::encode(&hmac.result()));
    |                                          ^^^^^^^^^^^^^^ the trait `std::convert::AsRef<[u8]>` is not implemented for `crypto::mac::MacResult`
    |
    = note: required by `base64::encode`

error: aborting due to previous error

error: Could not compile `messagebridge`.

To learn more, run the command again with --verbose.

```

The text of the error message is correct (it is describing the problem with the _parameter_) but the arrows point to the impl fn and not the parameter.

### LINKED ISSUE #48099: Point at problematic argument on mismatched `Fn` argument count
(After #48047's ICE fix) When a function or closure from another crate is passed as an argument and it doesn't match the expected argument count, the error points only at the method that expected the closure:

```
error[E0593]: function is expected to take 1 argument, but it takes 2 arguments
  --> $DIR/closure-arg-count.rs:40:41
   |
40 |     let _it = vec![1, 2, 3].into_iter().map(usize::checked_add);
   |                                         ^^^ expected function that takes 1 argument
```

In the case where the function or closure is local, the span for it is highlighted:

```
error[E0593]: function is expected to take a single 2-tuple as argument, but it takes 0 arguments
  --> $DIR/closure-arg-count.rs:32:53
   |
32 |     let _it = vec![1, 2, 3].into_iter().enumerate().map(foo);
   |                                                     ^^^ expected function that takes a single 2-tuple as argument
...
44 | fn foo() {}
   | -------- takes 0 arguments
```

It would be good for consistency to point at the external's function/closure span use location, as well as printing out the signature of the method:

```
error[E0593]: function is expected to take 1 argument, but it takes 2 arguments
  --> $DIR/closure-arg-count.rs:40:41
   |
40 |     let _it = vec![1, 2, 3].into_iter().map(usize::checked_add);
   |                                         ^^^ ------------------ takes 2 arguments: `fn(self, _: u32) -> Option<u32>`
   |                                         |
   |                                         expected function that takes 1 argument
```

### LINKED ISSUE #63143: Box "doesn't have a size known at compile-time" wrong diagnostic
If I do ...

```rust
fn main() {
    let x = "hello";
    let y = Box::new(*x);
}
```
I get the following error ...

```
 --> src/main.rs:3:13
  |
3 |     let y = Box::new(*x);
  |             ^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required by `std::boxed::Box::<T>::new`
```

I think the right error should be ...

```
 --> src/main.rs:3:13
  |
3 |     let y = Box::new(*x);
  |                      ^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required by `std::boxed::Box::<T>::new`
```

Is not that `Box` is not `Sized`, the problem is that the parameter of the `Box`'s `new` function is not `Sized`. So the last note in the error is important and also kind of lost in a lot of noise.

Possibly related to #61860.

### PR DESCRIPTION
**Pull request by estebank**
Fix https://github.com/rust-lang/rust/issues/41781, fix https://github.com/rust-lang/rust/issues/42855, fix https://github.com/rust-lang/rust/issues/46658, fix https://github.com/rust-lang/rust/issues/48099, fix https://github.com/rust-lang/rust/issues/63143, fix https://github.com/rust-lang/rust/issues/36775.

### CODE REVIEW

**Comment by estebank** [comment]
Note that this regresses errors involving `?`.

**Comment by estebank** [comment]
Related, but not affected by this PR https://github.com/rust-lang/rust/issues/61860

**Comment by estebank** [comment]
CC @oli-obk @Centril

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3222,6 +3222,8 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             formal_tys.clone()
         };
 
+        let mut final_arg_types: Vec<(usize, Ty<'_>)> = vec![];
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Seems like this is going to regress happy-path compile-time perf? (I don't expect by much but still...)

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -3234,7 +3236,32 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             // an "opportunistic" vtable resolution of any trait bounds on
             // the call. This helps coercions.
             if check_closures {
-                self.select_obligations_where_possible(false);
+                // We don't use `select_obligations_where_possible` to try to figure out if the
+                // obligation is comming from a single fn call argument, and if it is, we point
+                // at the expression corresponding to that argument, instead of the call.
+                if let Err(
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Would be good to not regress readability of this already-long method further by making this bit a method.

**Comment by Centril** [comment]
The regressions to `?` are uncool given that it's a pretty common operation... Have you thought about ways to avoid this?

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3234,7 +3236,34 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    mut errors,
+                ) = self.fulfillment_cx.borrow_mut().select_where_possible(self) {
+                    if !sp.desugaring_kind().is_some() {
+                        // We *do not* do this for desugared call spans to keep good diagnostics
+                        // involving try.
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                        // involving the `?` operator.
```

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: I see no way of doing this without collecting the resolved types for the general case (there's a lazy way to do it that would only work with fully resolved types in the arguments).

**Comment by estebank** [comment]
> Have you thought about ways to avoid this?

@Centril addressed in the second commit by ignoring cases that come from desugared call spans.

File: src/test/ui/issues/issue-28098.rs [hunk 4]
```diff
@@ -16,6 +17,7 @@ pub fn other() {
 
     let _ = Iterator::next(&mut ());
     //~^ ERROR `()` is not an iterator
+    //~| ERROR `()` is not an iterator
```
Comment (estebank) [inline src/test/ui/issues/issue-28098.rs]: This file shows the case where we duplicate the errors. We should be able to elide the error pointing at `Iterator::next` with some judicious use of `Ty::Error`.

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Yeah sure, just pointing out that there is a cost to this, which may be totally acceptable. :)

**Comment by estebank** [comment]
@oli-obk https://github.com/rust-lang/rust/pull/64498/commits/d38e090adf6027da4eb7bb01f06e3f094ef57256#diff-4cee39a7c18e8b5ec52efe4563c547fbR7-R11 😀 

```
error[E0277]: the trait bound `fn() -> impl std::future::Future {foo}: std::future::Future` is not satisfied
  --> $DIR/async-fn-ctor-passed-as-arg-where-it-should-have-been-called.rs:9:9
   |
LL | fn bar(f: impl Future<Output=()>) {}
   | --------------------------------- required by `bar`
...
LL |     bar(foo);
   |         ^^^
   |         |
   |         the trait `std::future::Future` is not implemented for `fn() -> impl std::future::Future {foo}`
   |         help: use parentheses to call the function: `foo()`
```

File: src/librustc/traits/mod.rs [hunk 5]
```diff
@@ -484,7 +484,8 @@ EnumTypeFoldableImpl! {
 
 pub struct FulfillmentError<'tcx> {
     pub obligation: PredicateObligation<'tcx>,
-    pub code: FulfillmentErrorCode<'tcx>
+    pub code: FulfillmentErrorCode<'tcx>,
+    pub points_at_arg_span: bool,
```
Comment (Centril) [inline src/librustc/traits/mod.rs]: Could use a doc comment explaining what it means. Alternatively / Additionally, consider an `enum` instead to make things more obvious.

File: src/librustc/traits/error_reporting.rs [hunk 6]
```diff
@@ -991,15 +1003,27 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
                                 ident,
                                 body.params.iter()
                                     .map(|arg| match &arg.pat.node {
                                         hir::PatKind::Binding(_, _, ident, None)
                                         if ident.name != kw::SelfLower => ident.to_string(),
                                         _ => "_".to_string(),
-                                    }).collect::<Vec<_>>().join(", ")));
+                                    }).collect::<Vec<_>>().join(", "),
+                            );
+                            if points_at_arg {
```
Comment (Centril) [inline src/librustc/traits/error_reporting.rs]: Could use a comment here.

File: src/librustc_typeck/check/mod.rs [hunk 7]
```diff
@@ -3265,7 +3267,20 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
             // the call. This helps coercions.
             if check_closures {
-                self.select_obligations_where_possible(false);
+                // We don't use `select_obligations_where_possible` to try to figure out if the
+                // obligation is comming from a single fn call argument, and if it is, we point
+                // at the expression corresponding to that argument, instead of the call.
+                if let Err(
+                    mut errors,
+                ) = self.fulfillment_cx.borrow_mut().select_where_possible(self) {
+                    self.point_at_arg_instead_of_call_if_possible(
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Hmm; we could bake this into `fn select_obligations_where_possible` with:
```rust
self.select_obligations_where_possible(false, |errors| {
    self.point_at_arg_instead_of_call_if_possible(
        errors,
        &*final_arg_types,
        sp,
        &args,
    )
});
```

to make things "more automatic" and less open to mistakes.

Some cases will need to pass a `|_| {}` lambda but it also opens up for targeted tweaks in those places too.

File: src/librustc_typeck/check/mod.rs [hunk 8]
```diff
@@ -3357,6 +3373,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    let mut referenced_in = vec![];
+                    for (i, ty) in final_arg_types {
+                        let ty = self.resolve_vars_if_possible(ty);
+                        for ty in ty.walk() {
+                            if ty == predicate.skip_binder().self_ty() {
+                                referenced_in.push(*i);
+                            }
+                        }
+                    }
+                    if referenced_in.len() == 1 {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                    if let [ref_in] = &*referenced_in {
```

File: src/librustc_typeck/check/mod.rs [hunk 9]
```diff
@@ -3357,6 +3373,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        error.obligation.cause.span = args[referenced_in[0]].span;
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                        error.obligation.cause.span = args[ref_in].span;
```

File: src/librustc_typeck/check/mod.rs [hunk 10]
```diff
@@ -3357,6 +3373,36 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        final_arg_types: &[(usize, Ty<'tcx>)],
+        call_sp: Span,
+        args: &'tcx [hir::Expr],
+    ) {
+        if !call_sp.desugaring_kind().is_some() {
+            // We *do not* do this for desugared call spans to keep good diagnostics when involving
+            // the `?` operator.
+            for error in errors {
+                if let ty::Predicate::Trait(predicate) = error.obligation.predicate {
+                    let mut referenced_in = vec![];
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Try this? (Avoids the allocation)
```rust
let referenced_in = final_arg_types
    .iter()
    .flat_map(|(i, ty)| {
        let ty = self.resolve_vars_if_possible(ty);
        ty.walk()
           .filter(|&ty| ty == predicate.skip_binder().self_ty())
           .map(|_| *i)
    });

if let Some(ref_in) = referenced_in.next() {
    ...
}
```

Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: We want to make sure there's only one argument that can fit the obligation failure. Because of that the allocation will be needed, but only happens in the error path.

Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: You can use `if let (Some(ref_in), None) = (referenced_in.next(), referenced_in.next())` to check that nothing follows the first argument.

File: src/librustc_typeck/check/mod.rs [hunk 11]
```diff
@@ -2844,8 +2844,13 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
     }
 
     /// Select as many obligations as we can at present.
-    fn select_obligations_where_possible(&self, fallback_has_occurred: bool) {
-        if let Err(errors) = self.fulfillment_cx.borrow_mut().select_where_possible(self) {
+    fn select_obligations_where_possible(
+        &self,
+        fallback_has_occurred: bool,
+        f: impl Fn(&mut Vec<traits::FulfillmentError<'tcx>>),
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: The diff looks great now. Final nit: can we rename `f` to something more descriptive?

**Comment by Centril** [comment]
r? @Centril 

r=me with the elaboration you gave me privately on Discord added as a comment in some fashion. :)

**Comment by nnethercote** [comment]
Either this PR or #64584 caused a [major regression](
https://perf.rust-lang.org/compare.html?start=ea3ba36f3f4b7f0168a27d23c499efeb2304e2d5&end=72252646a8f781509e6756180182887653f657ee&stat=instructions:u) in rustc perf. It's hard to tell because the graph goes up on this PR, then down for a single run, then stabilizes again at the worse performance after #64584.

I suggest backing out both PRs, opening new PRs, and then doing perf runs on both. That should make it clear which one cause the regression.

cc @rust-lang/compiler

**Comment by Mark-Simulacrum** [comment]
See https://github.com/rust-lang/rust/pull/64584#issuecomment-533938626 - I wouldn't do anything just yet.
