### PR TITLE
Properly generalize unevaluated consts

### LINKED ISSUE #153831: [ICE]: Unevaluated `ty::Const` in MIR body
auto-reduced (treereduce-rust):
````rust
//@compile-flags: -Znext-solver=globally
#![feature(min_generic_const_args)]

type const A: () = A;

fn main() {
    A;
}

````

original:
````rust
#![feature(min_generic_const_args)]
#![feature(adt_const_params)]
type const A: () = A;

fn main() {
    A;
}

````

Version information
````
rustc 1.96.0-nightly (8db65c717 2026-03-13)
binary: rustc
commit-hash: 8db65c71725664d85d06ec96ee3e575665de1f6a
commit-date: 2026-03-13
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Znext-solver=globally`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: the feature `min_generic_const_args` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.p9RMclWVkUdv/rustc_testrunner_tmpdir_reporting.LzDrjFuCMhzz/mvce.rs:1:12
  |
1 | #![feature(min_generic_const_args)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #132980 <https://github.com/rust-lang/rust/issues/132980> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: path statement with no effect
 --> /tmp/icemaker_global_tempdir.p9RMclWVkUdv/rustc_testrunner_tmpdir_reporting.LzDrjFuCMhzz/mvce.rs:6:5
  |
6 |     A;
  |     ^^
  |
  = note: `#[warn(path_statements)]` (part of `#[warn(unused)]`) on by default

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: Unevaluated `ty::Const` in MIR body
  |
  = note: delayed at /rustc-dev/8db65c71725664d85d06ec96ee3e575665de1f6a/compiler/rustc_middle/src/mir/consts.rs:330:35
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             3: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             4: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_assign
             5: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_body
             6: <rustc_mir_transform::known_panics_lint::KnownPanicsLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
             7: rustc_mir_transform::run_analysis_to_runtime_passes
             8: rustc_mir_transform::mir_drops_elaborated_and_const_checked
             9: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::invoke_provider_fn::__rust_begin_short_backtrace
            10: rustc_query_impl::execution::try_execute_query::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::ErasedData<[u8; 8]>, rustc_middle::dep_graph::graph::DepNodeIndex>, false>
            11: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::execute_query_non_incr::__rust_end_short_backtrace
            12: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
            13: rustc_interface::passes::analysis
            14: rustc_query_impl::execution::try_execute_query::<rustc_middle::query::caches::SingleCache<rustc_middle::query::erase::ErasedData<[u8; 0]>>, false>
            15: rustc_query_impl::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
            16: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
            17: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
            18: <std::thread::lifecycle::spawn_unchecked<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            19: <std::sys::thread::unix::Thread>::new::thread_start
            20: <unknown>
            21: <unknown>
          

error: internal compiler error: Unevaluated `ty::Const` in MIR body
  |
  = note: delayed at /rustc-dev/8db65c71725664d85d06ec96ee3e575665de1f6a/compiler/rustc_middle/src/mir/consts.rs:330:35
             0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
             1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             3: <rustc_errors::DiagCtxtHandle>::delayed_bug::<&str>
             4: <rustc_mir_transform::known_panics_lint::ConstPropagator>::eval_constant
             5: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_assign
             6: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_body
             7: <rustc_mir_transform::known_panics_lint::KnownPanicsLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
             8: rustc_mir_transform::run_analysis_to_runtime_passes
             9: rustc_mir_transform::mir_drops_elaborated_and_const_checked
            10: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::invoke_provider_fn::__rust_begin_short_backtrace
            11: rustc_query_impl::execution::try_execute_query::<rustc_data_structures::vec_cache::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::ErasedData<[u8; 8]>, rustc_middle::dep_graph::graph::DepNodeIndex>, false>
            12: rustc_query_impl::query_impl::mir_drops_elaborated_and_const_checked::execute_query_non_incr::__rust_end_short_backtrace
            13: <rustc_middle::ty::context::TyCtxt>::par_hir_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
            14: rustc_interface::passes::analysis
            15: rustc_query_impl::execution::try_execute_query::<rustc_middle::query::caches::SingleCache<rustc_middle::query::erase::ErasedData<[u8; 0]>>, false>
            16: rustc_query_impl::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
            17: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
            18: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
            19: <std::thread::lifecycle::spawn_unchecked<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            20: <std::sys::thread::unix::Thread>::new::thread_start
            21: <unknown>
            22: <unknown>
          

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (8db65c717 2026-03-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z next-solver=globally -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

@rustbot label +F-min_generic_const_args +F-adt_const_params +WG-trait-system-refactor

### PR DESCRIPTION
**Pull request by khyperia**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/154053)*

- fixes https://github.com/rust-lang/rust/issues/153831
- fixes a `// FIXME(ogca)` (I am unaware of an issue for this) added in https://github.com/rust-lang/rust/pull/150823

r? @BoxyUwU

### CODE REVIEW

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 1]
```diff
@@ -61,16 +68,95 @@ impl<'tcx> InferCtxt<'tcx> {
...
+            && !gce_const_fallback
             && matches!(relation.structurally_relate_aliases(), StructurallyRelateAliases::No)
-            && let ty::Alias(_, alias) = source_ty.kind()
+            && let Some(alias) = source_term.to_alias_term()
         {
-            let normalized_alias = relation.try_eagerly_normalize_alias(*alias);
+            let normalized_alias = relation.try_eagerly_normalize_alias(alias);
 
-            if normalized_alias.is_ty_var() {
+            if term_vid(normalized_alias).is_some() {
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]:
```suggestion
            if normalized_alias.is_infer() {
```

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 2]
```diff
@@ -83,9 +169,9 @@ impl<'tcx> InferCtxt<'tcx> {
                 // However, here, though we know it *is* an alias, we initialize the generalizer
                 // with `ShallowStructurallyRelateAliases` so we treat the outermost alias as rigid,
                 // ensuring this is never a tyvar.
-                assert!(!generalized_ty.is_ty_var());
+                assert!(term_vid(generalized_term).is_none());
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]:
```suggestion
                assert!(!generalized_term.is_infer());
```

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 3]
```diff
@@ -37,6 +37,13 @@ impl From<ty::ConstVid> for TermVid {
     }
 }
 
+fn term_vid<'tcx>(term: Term<'tcx>) -> Option<TermVid> {
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]: can you move this to a method on `Term`

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 4]
```diff
@@ -61,16 +68,95 @@ impl<'tcx> InferCtxt<'tcx> {
...
+        instantiation_variance: ty::Variance,
+        source_term: Term<'tcx>,
+    ) -> RelateResult<'tcx, ()> {
+        // Hack: Fall back to old behavior if GCE is enabled. I expect GCE to be ripped out soon so
+        // this shouldn't matter soon.
+        let gce_const_fallback =
+            self.tcx.features().generic_const_exprs() && matches!(target_vid, TermVid::Const(_));
+
+        let generalized_term = if self.next_trait_solver()
+            && !gce_const_fallback
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]: GCE is incompatible with the new solver (we don't allow both to be used together) so this check probably doesn't do anything. should be able to remvoe `gce_const_fallback`

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 5]
```diff
@@ -130,40 +216,47 @@ impl<'tcx> InferCtxt<'tcx> {
...
-                        // `Projection(normalized_source, ?ty_normalized)` and
-                        // `?normalized_source <: generalized_ty`.
-                        relation.register_predicates([ty::ProjectionPredicate {
-                            projection_term: data.into(),
-                            term: generalized_ty.into(),
-                        }]);
+                match source_term.kind() {
+                    ty::TermKind::Ty(source_ty) => {
+                        match source_ty.kind() {
+                            &ty::Alias(ty::Projection, data) => {
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]: we want to mirror this behaviour for projection consts, i.e. `<T as Trait>::ASSOC_CONST` under `mGCA` 🤔 Not quite sure what a test case would look like where this matters.

In general though I think instead of matching on the kind of the term and then on what kind of alias it is, we should match try convert to an `AliasTerm` and then match on the kind of that and handle `ProjectionTy/ProjectionConst` as one arm, and similarly for  `FreeTy/FreeConst/InherentConst/InherentTy` etc

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 6]
```diff
@@ -182,114 +275,78 @@ impl<'tcx> InferCtxt<'tcx> {
...
+            }
+            (TermVid::Const(l), TermVid::Const(r)) => {
+                self.inner.borrow_mut().const_unification_table().union(l, r)
+            }
+            _ => bug!("mismatched term kinds in generalize: {l:?}, {r:?}"),
         }
+    }
 
-        Ok(())
+    fn instantiate(&self, l: TermVid, r: ty::Term<'tcx>) {
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]:
```suggestion
    fn instantiate_var_raw(&self, l: TermVid, r: ty::Term<'tcx>) {
```

and maybe a comment to indicate this is a thin wrapper around the actual var table instantiation methods. concerned that as is people might (wrongly) call this instead of `instantiate_var` or something since this *sounds* like it'd be the right thing to call but mostly isnt

File: compiler/rustc_infer/src/infer/relate/generalize.rs [hunk 7]
```diff
@@ -182,114 +275,78 @@ impl<'tcx> InferCtxt<'tcx> {
...
-                source_ct,
-            )?;
-        } else {
-            relation.relate_with_variance(
-                ty::Invariant,
-                ty::VarianceDiagInfo::default(),
-                source_ct,
-                generalized_ct,
-            )?;
+    fn equate(&self, l: TermVid, r: TermVid) {
```
Comment (BoxyUwU) [inline compiler/rustc_infer/src/infer/relate/generalize.rs]: similarly maybe `fn union_vars` instead 🤔 + a comment explaining its just a wrapper around the infer var tables

**Review by BoxyUwU — COMMENTED** [review]
very cool

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154053/e52f547ed4bc554e40ab63b264e8697b8e3c5e09..ac88926ae2008c55484abf573ce78566f41b917b)*

File: compiler/rustc_infer/src/infer/relate/generalize.rs (hunk 3 above)
Comment (khyperia) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: `TermVid` is defined locally in `generalize.rs`, which is the reason this is also locally here. Should I migrate `TermVid` to `rustc_middle`? Seems vaguely useful in general (ha) but I was trying to rein in my refactorings

File: compiler/rustc_infer/src/infer/relate/generalize.rs (hunk 4 above)
Comment (khyperia) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: > this check **probably** doesn't do anything

removing it causes this test to fail:

```
error[E0119]: conflicting implementations of trait `From<GenericStruct<{T + 1}>>` for type `GenericStruct<{T + 1}>`
  --> /d/rust/tests/ui/const-generics/issues/issue-89304.rs:8:1
   |
LL | impl<const T: usize> From<GenericStruct<T>> for GenericStruct<{T + 1}> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;

error[E0119]: conflicting implementations of trait `From<GenericStruct<_>>` for type `GenericStruct<_>`
  --> /d/rust/tests/ui/const-generics/issues/issue-89304.rs:14:1
   |
LL | impl<const T: usize> From<GenericStruct<{T + 1}>> for GenericStruct<T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;

error: aborting due to 2 previous errors
```

to be honest, I'm not going to pretend I know what's going on.

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: aha coherence

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: yeah ok I guess the "gce isnt allowed with new solver" is wrong for coherence...

Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: sure yeah seems fine to me to keep this

File: compiler/rustc_infer/src/infer/relate/generalize.rs (hunk 3 above)
Comment (BoxyUwU) [reply compiler/rustc_infer/src/infer/relate/generalize.rs]: oh, i see yeah if you could move `TermVid` to whether we define `Term`/`AliasTerm`/etc that'd be great

File: tests/ui/const-generics/mgca/free-const-recursive.rs [hunk 8]
```diff
@@ -0,0 +1,13 @@
+//! Regression test for <https://github.com/rust-lang/rust/issues/153831>
+//@ check-fail
+//@compile-flags: -Znext-solver=globally --emit=obj
+#![feature(min_generic_const_args)]
+#![expect(incomplete_features)]
+
+type const A: () = A;
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/free-const-recursive.rs:7]: can you add a `ProjectionConst` version of this test, i.e.
```rust
//@ compile-flags: -Znext-solver
#![feature(min_generic_const_args)]
#![expect(incomplete_features)]

trait Trait {
    type const A: ();
}

impl Trait for () {
    type const A: () = <() as Trait>::A;
}

fn main() {
    <() as Trait>::A;
}
```

**Review by BoxyUwU — APPROVED** [review]
looks good to me other than test to add 😌 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/154053/ac40f5e105ddc8144904679cb63c8879708a9a26..607374705d7c18999e39f89176292c560ff15cd2)*

File: tests/ui/const-generics/mgca/free-const-recursive.rs (hunk 8 above)
Comment (khyperia) [reply tests/ui/const-generics/mgca/free-const-recursive.rs:7]: done! (verified the test fails on main and succeeds with this PR)

Comment (khyperia) [reply tests/ui/const-generics/mgca/free-const-recursive.rs:7]: wait why did i call the other test "free **type** alias recursive" uuuh

Comment (khyperia) [reply tests/ui/const-generics/mgca/free-const-recursive.rs:7]: ok renamed it too

**Comment by Mark-Simulacrum** [comment]
Regressions are limited to new solver, and fairly small. Most likely no need to investigate deeper, especially as this also fixes a few bugs. Marking as triaged.
