### PR TITLE
fixed *const [type error] does not implement the Copy trait

### LINKED ISSUE #113788: Inline asm: `*const [type error]` does not implement the Copy trait
### Code

```Rust
fn main() {
	let peb: *const PEB;
	unsafe { std::arch::asm!("mov {0}, fs:[0x30]", out(reg) peb); }
}
```

### Current output

```Shell
error[E0412]: cannot find type `PEB` in this scope
 --> src/main.rs:2:18
  |
2 |     let peb: *const PEB;
  |                     ^^^ not found in this scope

error: arguments for inline assembly must be copyable
 --> src/main.rs:3:49
  |
3 |     std::arch::asm!("mov {0}, fs:[0x30]", out(reg) peb);
  |                                                    ^^^
  |
  = note: `*const [type error]` does not implement the Copy trait

For more information about this error, try `rustc --explain E0412`.
```

### Desired output

```Shell
Probably just omit the second error; no `Copy` error is given when moving an unknown type normally.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

Happens on `1.73.0-nightly (2023-07-16 0e8e857b11f60a785aea)`, as well as several earlier versions.

### PR DESCRIPTION
**Pull request by RickleAndMortimer**
Removes "error: arguments for inline assembly must be copyable" when moving an unknown type

Fixes: #113788

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/intrinsicck.rs [hunk 1]
```diff
@@ -145,8 +145,13 @@ impl<'a, 'tcx> InlineAsmCtxt<'a, 'tcx> {
         if !ty.is_copy_modulo_regions(self.tcx, self.param_env) {
             let msg = "arguments for inline assembly must be copyable";
             let mut err = self.tcx.sess.struct_span_err(expr.span, msg);
-            err.note(format!("`{ty}` does not implement the Copy trait"));
-            err.emit();
+
+            if ty.references_error() {
```
Comment (fee1-dead) [inline compiler/rustc_hir_analysis/src/check/intrinsicck.rs:149]: There's an arm above:

```rust
            ty::Error(_) => return None,
```

I think it would be better if we just did `_ if ty.references_error()` over there?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/intrinsicck.rs:149]: Yeah.

**Comment by asquared31415** [comment]
This should include tests that make sure that the issue is fixed, and makes sure that this doesn't regress.

**Comment by jackh726** [comment]
See comments above

File: tests/ui/asm/issue-113788.rs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// test that "error: arguments for inline assembly must be copyable" doesn't show up in this code
```
Comment (compiler-errors) [inline tests/ui/asm/issue-113788.rs:1]: We're missing a corresponding `tests/ui/asm/issue-113788.stderr` file

File: compiler/rustc_hir_analysis/src/check/intrinsicck.rs [hunk 3]
```diff
@@ -69,6 +69,7 @@ impl<'a, 'tcx> InlineAsmCtxt<'a, 'tcx> {
             // `!` is allowed for input but not for output (issue #87802)
             ty::Never if is_input => return None,
             ty::Error(_) => return None,
+            _ if ty.references_error() => return None,
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/intrinsicck.rs:72]: The latter arm implies the former arm

```suggestion
            _ if ty.references_error() => return None,
```

File: compiler/rustc_hir_analysis/src/check/intrinsicck.rs [hunk 4]
```diff
@@ -145,6 +146,7 @@ impl<'a, 'tcx> InlineAsmCtxt<'a, 'tcx> {
         if !ty.is_copy_modulo_regions(self.tcx, self.param_env) {
             let msg = "arguments for inline assembly must be copyable";
             let mut err = self.tcx.sess.struct_span_err(expr.span, msg);
+
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/intrinsicck.rs:149]: nit: plz remove the spurious change

```suggestion
```

**Comment by RickleAndMortimer** [comment]
> This should include tests that make sure that the issue is fixed, and that this doesn't regress.

I have the code in the original issue as a test case. I'd like to know what other test cases I could add to this PR and how to write them up.

File: tests/ui/asm/issue-113788.rs [hunk 5]
```diff
@@ -0,0 +1,9 @@
...
+// revisions: x64
+// assembly-output: emit-asm
+// [x64] compile-flags: --target x86_64-unknown-linux-gnu -Crelocation-model=pie
+// [x64] needs-llvm-components: x86
```
Comment (compiler-errors) [inline tests/ui/asm/issue-113788.rs:5]: Can you try instead:

```
// needs-asm-support
// only-x86_64
```

Also, having only one revision is kinda redundant.

**Comment by compiler-errors** [comment]
Can you squash this into one commit please? Usually for things like this where you're fixing nits and making it pass, there's no reason to maintain commit history 😸

File: src/llvm-project
Comment (fee1-dead) [inline src/llvm-project:1]: This submodule update doesn't seem to be right.

**Review by compiler-errors — APPROVED** [review]

**Comment by RickleAndMortimer** [comment]
Thank you @compiler-errors @jackh726 @asquared31415 for your feedback!
