### PR TITLE
Explain our RwLock implementation

### LINKED ISSUE #53127: Unix: RwLock is incorrect
I think the [`sys::unix::rwlock` implementation](https://github.com/rust-lang/rust/blob/b2397437530eecef72a1524a7e0a4b42034fa360/src/libstd/sys/unix/rwlock.rs) is incorrect in the sense that it has undefined behavior, for two reasons:

* ~~The access to `write_locked` is not properly synchronized: In `read`, we access `write_locked` even if `pthread_rwlock_rdlock` failed.~~ This is [fixed](https://github.com/rust-lang/rust/pull/55865).
* Worse, POSiX read-write locks have UB when the thread holding the write lock attempts to acquire it again -- and yet nothing is stopping exactly that from happening in `write`. If we really want to use POSIX rwlocks, I think we have to implement a reentrancy detector. (And then maybe we also want to use that for mutex, so that we can use the static initializer and the most efficient code path?)

### PR DESCRIPTION
**Pull request by RalfJung**
Turns out that [with the latest POSIX docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_wrlock.html), our `RwLock` implementation is actually correct. However, we cannot fully rely on that due to bugs in older glibc (fix released in 2016). Update the comments to explain that.

I also clarified our Mutex docs a bit and fixed another instance of https://github.com/rust-lang/rust/pull/55865.

r? @Amanieu 
Fixes https://github.com/rust-lang/rust/issues/53127

### CODE REVIEW

File: src/libstd/sys/unix/rwlock.rs [hunk 1]
```diff
@@ -69,18 +69,21 @@ impl RWLock {
     #[inline]
     pub unsafe fn write(&self) {
         let r = libc::pthread_rwlock_wrlock(self.inner.get());
-        // See comments above for why we check for EDEADLK and write_locked. We
-        // also need to check that num_readers is 0.
+        // See comments above for why we check for EDEADLK and write_locked. For the same reason,
+        // we also need to check that there are no readers (tracked in `num_readers`).
         if r == libc::EDEADLK
-            || *self.write_locked.get()
+            || (r == 0 && *self.write_locked.get())
```
Comment (RalfJung) [inline src/libstd/sys/unix/rwlock.rs:75]: I think I just forgot this one in https://github.com/rust-lang/rust/pull/55865.

File: src/libstd/sys/unix/mutex.rs [hunk 2]
```diff
@@ -28,14 +28,18 @@ impl Mutex {
...
         // a type of PTHREAD_MUTEX_DEFAULT, which has undefined behavior if you
-        // try to re-lock it from the same thread when you already hold a lock.
+        // try to re-lock it from the same thread when you already hold a lock
+        // (https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html).
         //
         // In practice, glibc takes advantage of this undefined behavior to
         // implement hardware lock elision, which uses hardware transactional
-        // memory to avoid acquiring the lock. While a transaction is in
+        // memory to avoid acquiring the lock.
+        // This is the case even if PTHREAD_MUTEX_DEFAULT == PTHREAD_MUTEX_NORMAL
```
Comment (Amanieu) [inline src/libstd/sys/unix/mutex.rs:37]: This might sound confusing since just a few lines below we set the mutex type to `PTHREAD_MUTEX_NORMAL`. What is actually happening is that `pthread_mutexattr_settype(PTHREAD_MUTEX_NORMAL)` disables lock elision (to conform to the standard), while `PTHREAD_MUTEX_INITIALIZER` doesn't.

Comment (Amanieu) [reply src/libstd/sys/unix/mutex.rs:37]: See [this comment](https://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/pthread_mutexattr_settype.c;h=c11a391e46fa43ac7cd4f8ba1309a3354f15ba57;hb=HEAD) in glibc.

File: src/libstd/sys/unix/rwlock.rs [hunk 3]
```diff
@@ -69,18 +69,21 @@ impl RWLock {
...
+            // Above, we make sure to only access `write_locked` when `r == 0` to avoid
+            // data races.
             if r == 0 {
+                // `pthread_rwlock_wrlock` succeeded when it should not have.
                 self.raw_unlock();
             }
             panic!("rwlock write lock would result in deadlock");
         } else {
-            debug_assert_eq!(r, 0);
+            assert_eq!(r, 0);
```
Comment (Amanieu) [inline src/libstd/sys/unix/rwlock.rs:86]: Why did you change this from a debug assert? The docs for `pthread_rwlock_wrlock` specify that it only ever returns `EDEADLK` or 0.

Comment (RalfJung) [reply src/libstd/sys/unix/rwlock.rs:86]: Consistency -- I did the same in https://github.com/rust-lang/rust/pull/55865. Seems cheap to check.

But if you want I can also make it a debug assertion again.

Comment (Amanieu) [reply src/libstd/sys/unix/rwlock.rs:86]: I would prefer making it a debug assert since this is a pretty hot path.

File: src/libstd/sys/unix/mutex.rs (hunk 2 above)
Comment (RalfJung) [reply src/libstd/sys/unix/mutex.rs]: I edited the comment, better like this?

File: src/libstd/sys/unix/rwlock.rs (hunk 3 above)
Comment (RalfJung) [reply src/libstd/sys/unix/rwlock.rs]: Okay, I did that and added an appropriate comment.
Is it generally the case that the list of error codes in the POSIX docs is exhaustive? I noticed the docs explicitly say "These functions shall not return an error code of [EINTR]" but do not say that for any of the other error codes.

Comment (Amanieu) [reply src/libstd/sys/unix/rwlock.rs]: They are supposed to be exhaustive in theory.
