### PR TITLE
Modify compile-fail/E0389 error message WIP

### LINKED ISSUE #47388: [NLL] E0389 error message uses the term `immutable item` inappropriately
The test compile-fail/E0389.rs gives the error message "cannot assign to immutable item `fancy_ref.num`". This is not particularly good because:

(a) "item" is probably not a very clear term for end-users but also
(b) even if it were, I would expect it to refer to "global things" like functions or statics, not fields of a local variable.

### PR DESCRIPTION
**Pull request by gaurikholkar-zz**
This fixes #47388 

cc @nikomatsakis @estebank 

r? @nikomatsakis 

Certain ui tests were failing locally. I'll check if the same happens here too.

### CODE REVIEW

File: src/test/compile-fail/borrowck/borrowck-overloaded-index-ref-index.rs [hunk 1]
```diff
@@ -70,5 +70,5 @@ fn main() {
     };
     s[2] = 20;
     //[ast]~^ ERROR cannot assign to immutable indexed content
-    //[mir]~^^ ERROR cannot assign to immutable item
+    //[mir]~^^ ERROR cannot assign through immutable item
```
Comment (gaurikholkar) [inline src/test/compile-fail/borrowck/borrowck-overloaded-index-ref-index.rs]: I'm not sure about the look of this test though.

**Comment by gaurikholkar** [comment]
This is how the error message looks like
```
error[E0594]: cannot assign through `&`-reference fancy_ref
  --> src/test/compile-fail/E0389.rs:18:5
   |
17 |     let fancy_ref = &(&mut fancy);
   |                     ------------- help: consider changing this to be a mutable reference: `&mut`
18 |     fancy_ref.num = 6; //~ ERROR E0389
   |     ^^^^^^^^^^^^^^^^^ cannot assign to field of `&`-reference
```
Do I need to add a ui test for this? There's an already existing compile-fail test

**Comment by estebank** [comment]
> Do I need to add a ui test for this? There's an already existing compile-fail test

Could you move the file from `compile-fail` to `ui`?

File: src/librustc_mir/borrow_check/mod.rs [hunk 2]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                 if let Err(place_err) = self.is_mutable(place, is_local_mutation_allowed) {
                     error_reported = true;
 
-                    let item_msg = match self.describe_place(place) {
-                        Some(name) => format!("immutable item `{}`", name),
-                        None => "immutable item".to_owned(),
+                    let err_info = match *place_err {
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: Given how deeply nested this is, it might make sense to move it to its own method, or at least adding a comment on top describing what the code is supposed to be doing.

File: src/librustc_mir/borrow_check/mod.rs [hunk 3]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                        Place::Projection(ref proj) => {
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: You can match on multiple levels to avoid deeply nested structures:

```rust
enum Foo {
    A { f: Bar },
    B(Bar),
}
enum Bar {
    X,
    Y,
}
let x = Foo::B(Bar::X);
match x {
    Foo::A { f: Bar::Y } => 1,
    _ => 0,
}
```

File: src/librustc_mir/borrow_check/mod.rs [hunk 4]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                                                None
+                                            }
+                                        }
+                                        _ => None,
+                                    }
+                                }
+                                _ => None,
+                            }
+                        }
+                        _ => None,
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: Given how many branches there are here, it might make sense to make `err_info` mutable with a default value of `None`, and override where applicable, but this might not be needed if the amount of branches is reduced.

File: src/librustc_mir/borrow_check/mod.rs [hunk 5]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
-                        if let Some(name) = self.describe_place(place_err) {
-                            err.note(&format!("Value not mutable causing this error: `{}`", name));
+                    if let Some((err_help_span, err_help_stmt, item_msg, sec_span)) = err_info {
+                        let mut err = self.tcx.cannot_assign(span, &item_msg, Origin::Mir, true);
+                        err.span_suggestion(err_help_span, err_help_stmt, format!(""));
+                        if place != place_err {
+                            err.span_label(span, sec_span);
                         }
+                        err.emit()
+                    }else{
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: spaces around `else`

File: src/librustc_mir/borrow_check/mod.rs [hunk 6]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                        let item_msg_ = self.get_main_error_message(place);
+                        let mut err = self.tcx.cannot_assign(span, &item_msg_, Origin::Mir, false);
+                        err.span_label(span, "cannot mutate");
+                        if place != place_err {
+                            if let Some(name) = self.describe_place(place_err) {
+                                err.note(&format!("Value not mutable causing this error: `{}`",
```
Comment (estebank) [inline src/librustc_mir/borrow_check/mod.rs]: lowercase sentences: `value not mutable`

File: src/librustc_mir/lib.rs [hunk 7]
```diff
@@ -39,6 +39,7 @@ Rust MIR: a lowered representation of Rust. Also: an experiment!
 #![feature(collection_placement)]
 #![feature(nonzero)]
 #![feature(underscore_lifetimes)]
+#![feature(crate_visibility_modifier)]
```
Comment (estebank) [inline src/librustc_mir/lib.rs]: Was this needed?

File: src/test/compile-fail/borrowck/borrowck-overloaded-index-ref-index.rs (hunk 1 above)
Comment (estebank) [reply src/test/compile-fail/borrowck/borrowck-overloaded-index-ref-index.rs]: This one seems ok-ish to me, but we might be able to improve upon it. I'll think about it.

File: src/test/compile-fail/borrowck/borrowck-issue-14498.rs [hunk 8]
```diff
@@ -27,7 +27,7 @@ fn indirect_write_to_imm_box() {
     let y: Box<_> = box &mut x;
     let p = &y;
     ***p = 2; //[ast]~ ERROR cannot assign to data in a `&` reference
-              //[mir]~^ ERROR cannot assign to immutable item `***p`
+              //[mir]~^ ERROR cannot assign through `&`-reference `p`
```
Comment (estebank) [inline src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: Not convinced about this change...

Comment (gaurikholkar) [reply src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: yes, due to the usage here `crate trait FindAssignments {`

File: src/librustc_mir/lib.rs (hunk 7 above)
Comment (gaurikholkar) [reply src/librustc_mir/lib.rs]: yes, due to the usage here `crate trait FindAssignments {`

File: src/test/compile-fail/borrowck/borrowck-issue-14498.rs (hunk 8 above)
Comment (nikomatsakis) [reply src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: certainly better than it was ("imutable item"), but not I think perfect yet -- and not necessarily better than AST variant, I don't think

File: src/librustc_mir/borrow_check/mod.rs [hunk 9]
```diff
@@ -1551,19 +1559,14 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
-
+                let item_msg = self.get_main_error_message(place);
                 let mut err = self.tcx
                     .cannot_borrow_path_as_mutable(span, &item_msg, Origin::Mir);
                 err.span_label(span, "cannot borrow as mutable");
 
                 if place != place_err {
                     if let Some(name) = self.describe_place(place_err) {
-                        err.note(&format!("Value not mutable causing this error: `{}`", name));
+                        err.note(&format!("value not mutable causing this error: `{}`", name));
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Pre-existing, but this message is not particularly grammatical. In fact, I have a hard time even understanding it -- I guess it is saying that "the value which is causing this path not to be mutable is..."?

File: src/librustc_mir/util/collect_writes.rs [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+            }
+        }
+    }
+    // TO-DO
+    // fn super_local()
+}
+
+crate trait FindAssignments {
+    fn find_assignments(&self, local: Local) -> Vec<Location>;
+    }
```
Comment (nikomatsakis) [inline src/librustc_mir/util/collect_writes.rs]: Nit: formatting

File: src/librustc_mir/util/collect_writes.rs [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+                // TO-DO
+                // self.super_local(local)
+            }
+        }
+    }
+    // TO-DO
+    // fn super_local()
+}
+
+crate trait FindAssignments {
```
Comment (nikomatsakis) [inline src/librustc_mir/util/collect_writes.rs]: I would move this to the top of the file -- this is what readers care about. Also, I would add a comment to the method:

---

Finds all statements that assign directly to `local` (i.e., `X = ...`) and returns their locations.

File: src/librustc_mir/util/collect_writes.rs [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+// except according to those terms.
+
+use rustc::mir::{Local, Location};
+use rustc::mir::Mir;
+use rustc::mir::visit::PlaceContext;
+use rustc::mir::visit::Visitor;
+
+// The Visitor walks the MIR to return the assignment statements corresponding
+// to a Local.
+pub struct FindLocalAssignmentVisitor {
```
Comment (nikomatsakis) [inline src/librustc_mir/util/collect_writes.rs]: This does not need to be public, it is an impl detail. Just make it private.

File: src/librustc_mir/borrow_check/mod.rs [hunk 13]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                            match proj.elem {
+                                ProjectionElem::Deref => {
+                                    match proj.base {
+                                        Place::Local(local) => {
+                                            let locations = self.mir.find_assignments(local);
+                                            if locations.len() > 0 {
+                                                let item_msg = if error_reported {
+                                                    if let Some(name) =
+                                                            self.describe_place(place_err) {
+                                                        let var = str::replace(&name, "*", "");
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: Hmm, I'm not crazy about the string munging =) Maybe we should just do `describe_place(&place.base)`?

File: src/librustc_mir/borrow_check/mod.rs [hunk 14]
```diff
@@ -1573,21 +1576,61 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                                                        format!("`&`-reference `{}`", var)
+                                                    } else {
+                                                        self.get_main_error_message(place)
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/mod.rs]: I would pull this into a helper function and I would change these `get_main_error_message` cases to just return `None`. The helper would be something like:

```rust
fn specialized_description(..) -> Option<String>
```

then if it is `None` you can use `get_main_error_message(place)`.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Left a few nits, to start.

File: src/test/compile-fail/borrowck/borrowck-issue-14498.rs (hunk 8 above)
Comment (nikomatsakis) [reply src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: The AST based error is this:

```
error[E0389]: cannot assign to data in a `&` reference
 --> src/main.rs:8:5
  |
8 |     ***p = 2;
  |     ^^^^^^^^ assignment into an immutable reference
```

which I think has too much jargon, but some promising elements. This also intersects your style guide @estebank. **Personally**, my preference is that the "main" message is kind of generic and formal, like it is here, telling you nothing of the program itself, but that those details are revealed in the "underlines" and in a "conversational" tone. Maybe something like this?

```
error[E0389]: cannot assign to data in a `&` reference
 --> src/main.rs:8:5
  |
8 |     ***p = 2;
  |     ^^^^^^^^ `p` is a `&` reference, so the data it refers to cannot be written
```

**Comment by pietroalbini** [comment]
@gaurikholkar ping from triage! There are a few comments from the reviewer, could you address them?

**Comment by gaurikholkar** [comment]
Reopening the PR. Sorry for the delay

File: src/test/compile-fail/borrowck/borrowck-issue-14498.rs (hunk 8 above)
Comment (gaurikholkar) [reply src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: Is this the common message for all such cases or just for the above case?

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362711478). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (604637/604637), completed with 4783 local objects.
---
[00:03:30] configure: rust.quiet-tests     := True
---
[00:15:53] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1556: line longer than 100 chars
[00:15:53] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1583: line longer than 100 chars
[00:15:53] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1611: line longer than 100 chars
---
116988 ./obj/build/bootstrap/debug/incremental/bootstrap-232achgbjnpqy/s-ezu81w52hb-ltna5o-23cdd79jjy90a
---
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:001cc8fa:start=1522946858677727392,finish=1522946858684283059,duration=6555667
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:36debfb4
$ dmesg | grep -i kill
[   10.355499] init: failsafe main process (1094) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362716049). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Receiving objects:   0% (57/12934), 92.00 KiB | 154.00 KiB/s
Receiving objects:   1% (130/12934), 308.00 KiB | 282.00 KiB/s
Receiving objects:   2% (259/12934), 308.00 KiB | 282.00 KiB/s
Receiving objects:   3% (389/12934), 308.00 KiB | 282.00 KiB/s
Receiving objects:   3% (495/12934), 612.00 KiB | 378.00 KiB/s
Receiving objects:   4% (518/12934), 908.00 KiB | 422.00 KiB/s
Receiving objects:   4% (581/12934), 1.04 MiB | 386.00 KiB/s
Receiving objects:   5% (647/12934), 1.37 MiB | 429.00 KiB/s
Receiving objects:   5% (688/12934), 1.55 MiB | 416.00 KiB/s
Receiving objects:   6% (777/12934), 1.69 MiB | 399.00 KiB/s
Receiving objects:   6% (845/12934), 1.82 MiB | 383.00 KiB/s
Receiving objects:   7% (906/12934), 2.05 MiB | 416.00 KiB/s
Receiving objects:   7% (987/12934), 2.36 MiB | 435.00 KiB/s
Receiving objects:   8% (1035/12934), 2.60 MiB | 424.00 KiB/s
Receiving objects:   9% (1165/12934), 2.86 MiB | 422.00 KiB/s
Receiving objects:   9% (1197/12934), 2.86 MiB | 422.00 KiB/s
Receiving objects:  10% (1294/12934), 3.08 MiB | 437.00 KiB/s
Receiving objects:  10% (1299/12934), 3.14 MiB | 379.00 KiB/s
Receiving objects:  10% (1323/12934), 3.23 MiB | 320.00 KiB/s
Receiving objects:  10% (1351/12934), 3.31 MiB | 293.00 KiB/s
Receiving objects:  10% (1396/12934), 3.39 MiB | 264.00 KiB/s
Receiving objects:  11% (1423/12934), 3.47 MiB | 221.00 KiB/s
Receiving objects:  11% (1503/12934), 3.68 MiB | 215.00 KiB/s
Receiving objects:  11% (1535/12934), 3.94 MiB | 170.00 KiB/s
Receiving objects:  12% (1553/12934), 3.98 MiB | 165.00 KiB/s
Receiving objects:  12% (1563/12934), 4.05 MiB | 158.00 KiB/s
Receiving objects:  12% (1612/12934), 4.15 MiB | 169.00 KiB/s
Receiving objects:  12% (1619/12934), 4.30 MiB | 172.00 KiB/s
Receiving objects:  12% (1650/12934), 4.44 MiB | 141.00 KiB/s
Receiving objects:  12% (1661/12934), 4.47 MiB | 110.00 KiB/s
Receiving objects:  12% (1677/12934), 4.64 MiB | 113.00 KiB/s
Receiving objects:  12% (1679/12934), 4.85 MiB | 126.00 KiB/s
Receiving objects:  13% (1682/12934), 4.85 MiB | 126.00 KiB/s
Receiving objects:  13% (1686/12934), 5.01 MiB | 142.00 KiB/s
Receiving objects:  14% (1811/12934), 5.25 MiB | 174.00 KiB/s
Receiving objects:  14% (1851/12934), 5.25 MiB | 174.00 KiB/s
Receiving objects:  15% (1941/12934), 5.52 MiB | 208.00 KiB/s
Receiving objects:  15% (1975/12934), 5.67 MiB | 224.00 KiB/s
Receiving objects:  15% (1990/12934), 5.68 MiB | 217.00 KiB/s
Receiving objects:  16% (2070/12934), 5.73 MiB | 213.00 KiB/s
Receiving objects:  16% (2085/12934), 5.83 MiB | 216.00 KiB/s
Receiving objects:  16% (2140/12934), 6.07 MiB | 196.00 KiB/s
Receiving objects:  16% (2145/12934), 6.07 MiB | 196.00 KiB/s
Receiving objects:  17% (2199/12934), 6.25 MiB | 136.00 KiB/s
Receiving objects:  17% (2318/12934), 6.41 MiB | 147.00 KiB/s
Receiving objects:  18% (2329/12934), 6.41 MiB | 147.00 KiB/s
Receiving objects:  19% (2458/12934), 6.41 MiB | 147.00 KiB/s
Receiving objects:  19% (2471/12934), 6.48 MiB | 140.00 KiB/s
Receiving objects:  19% (2547/12934), 6.55 MiB | 135.00 KiB/s
Receiving objects:  19% (2547/12934), 6.56 MiB | 121.00 KiB/s
Receiving objects:  20% (2587/12934), 6.56 MiB | 121.00 KiB/s
Receiving objects:  21% (2717/12934), 6.56 MiB | 121.00 KiB/s
Receiving objects:  22% (2846/12934), 6.64 MiB | 119.00 KiB/s
Receiving objects:  22% (2854/12934), 6.64 MiB | 119.00 KiB/s
Receiving objects:  23% (2975/12934), 6.70 MiB | 112.00 KiB/s
Receiving objects:  24% (3105/12934), 6.70 MiB | 112.00 KiB/s
Receiving objects:  25% (3234/12934), 6.79 MiB | 111.00 KiB/s
Receiving objects:  25% (3334/12934), 6.79 MiB | 111.00 KiB/s
Receiving objects:  26% (3363/12934), 6.79 MiB | 111.00 KiB/s
Receiving objects:  27% (3493/12934), 6.79 MiB | 111.00 KiB/s
Receiving objects:  28% (3622/12934), 6.79 MiB | 111.00 KiB/s
Receiving objects:  29% (3751/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  30% (3881/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  31% (4010/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  32% (4139/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  33% (4269/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  34% (4398/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  35% (4527/12934), 6.97 MiB | 128.00 KiB/s
Receiving objects:  36% (4657/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  37% (4786/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  37% (4874/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  38% (4915/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  39% (5045/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  40% (5174/12934), 7.27 MiB | 152.00 KiB/s
Receiving objects:  41% (5303/12934), 7.47 MiB | 197.00 KiB/s
Receiving objects:  42% (5433/12934), 7.47 MiB | 197.00 KiB/s
Receiving objects:  43% (5562/12934), 7.47 MiB | 197.00 KiB/s
Receiving objects:  44% (5691/12934), 7.47 MiB | 197.00 KiB/s
Receiving objects:  45% (5821/12934), 7.47 MiB | 197.00 KiB/s
Receiving objects:  46% (5950/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  46% (5967/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  47% (6079/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  48% (6209/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  49% (6338/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  50% (6467/12934), 7.74 MiB | 251.00 KiB/s
Receiving objects:  51% (6597/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  52% (6726/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  53% (6856/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  54% (6985/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  55% (7114/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  56% (7244/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  57% (7373/12934), 7.91 MiB | 289.00 KiB/s
Receiving objects:  57% (7424/12934), 8.18 MiB | 319.00 KiB/s
Receiving objects:  58% (7502/12934), 8.18 MiB | 319.00 KiB/s
Receiving objects:  58% (7508/12934), 8.21 MiB | 302.00 KiB/s
Receiving objects:  59% (7632/12934), 8.24 MiB | 289.00 KiB/s
Receiving objects:  59% (7655/12934), 8.24 MiB | 289.00 KiB/s
Receiving objects:  60% (7761/12934), 8.24 MiB | 289.00 KiB/s
Receiving objects:  61% (7890/12934), 8.28 MiB | 279.00 KiB/s
Receiving objects:  62% (8020/12934), 8.34 MiB | 257.00 KiB/s
Receiving objects:  62% (8032/12934), 8.36 MiB | 165.00 KiB/s
Receiving objects:  63% (8149/12934), 8.36 MiB | 165.00 KiB/s
Receiving objects:  64% (8278/12934), 8.36 MiB | 165.00 KiB/s
Receiving objects:  64% (8321/12934), 8.36 MiB | 165.00 KiB/s
Receiving objects:  65% (8408/12934), 8.36 MiB | 165.00 KiB/s
Receiving objects:  66% (8537/12934), 8.50 MiB | 155.00 KiB/s
Receiving objects:  67% (8666/12934), 8.50 MiB | 155.00 KiB/s
Receiving objects:  68% (8796/12934), 8.50 MiB | 155.00 KiB/s
Receiving objects:  69% (8925/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  69% (9017/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  70% (9054/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  71% (9184/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  72% (9313/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  73% (9442/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  74% (9572/12934), 8.64 MiB | 133.00 KiB/s
Receiving objects:  75% (9701/12934), 8.86 MiB | 139.00 KiB/s
Receiving objects:  75% (9777/12934), 8.92 MiB | 111.00 KiB/s
Receiving objects:  76% (9830/12934), 8.92 MiB | 111.00 KiB/s
Receiving objects:  77% (9960/12934), 8.92 MiB | 111.00 KiB/s
Receiving objects:  78% (10089/12934), 8.92 MiB | 111.00 KiB/s
Receiving objects:  78% (10136/12934), 9.01 MiB | 119.00 KiB/s
Receiving objects:  79% (10218/12934), 9.01 MiB | 119.00 KiB/s
Receiving objects:  79% (10223/12934), 9.05 MiB | 114.00 KiB/s
Receiving objects:  80% (10348/12934), 9.05 MiB | 114.00 KiB/s
Receiving objects:  81% (10477/12934), 9.14 MiB | 120.00 KiB/s
Receiving objects:  82% (10606/12934), 9.14 MiB | 120.00 KiB/s
Receiving objects:  83% (10736/12934), 9.14 MiB | 120.00 KiB/s
Receiving objects:  83% (10847/12934), 9.25 MiB | 125.00 KiB/s
Receiving objects:  84% (10865/12934), 9.25 MiB | 125.00 KiB/s
Receiving objects:  85% (10994/12934), 9.25 MiB | 125.00 KiB/s
Receiving objects:  86% (11124/12934), 9.25 MiB | 125.00 KiB/s
Receiving objects:  87% (11253/12934), 9.25 MiB | 125.00 KiB/s
Receiving objects:  88% (11382/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  88% (11468/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  89% (11512/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  90% (11641/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  91% (11770/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  92% (11900/12934), 9.34 MiB | 162.00 KiB/s
Receiving objects:  93% (12029/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  94% (12158/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  95% (12288/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  96% (12417/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  97% (12546/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  98% (12676/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  99% (12805/12934), 9.51 MiB | 160.00 KiB/s
Receiving objects:  99% (12826/12934), 9.51 MiB | 160.00 KiB/s
remote: Total 12934 (delta 6502), reused 2733 (delta 1265), pack-reused 0
Receiving objects: 100% (12934/12934), 9.89 MiB | 203.00 KiB/s
Receiving objects: 100% (12934/12934), 9.90 MiB | 210.00 KiB/s, done.
---
Receiving objects:   2% (21536/745349), 6.36 MiB | 849.00 KiB/s
Receiving objects:   3% (22361/745349), 6.70 MiB | 801.00 KiB/s
Receiving objects:   3% (24344/745349), 7.10 MiB | 779.00 KiB/s
Receiving objects:   3% (27558/745349), 7.90 MiB | 782.00 KiB/s
Receiving objects:   4% (29814/745349), 8.71 MiB | 777.00 KiB/s
Receiving objects:   4% (30490/745349), 8.71 MiB | 777.00 KiB/s
Receiving objects:   4% (33217/745349), 9.46 MiB | 761.00 KiB/s
Receiving objects:   4% (35299/745349), 10.05 MiB | 739.00 KiB/s
Receiving objects:   5% (37268/745349), 10.66 MiB | 704.00 KiB/s
Receiving objects:   5% (37747/745349), 10.66 MiB | 704.00 KiB/s
Receiving objects:   5% (39932/745349), 11.29 MiB | 655.00 KiB/s
Receiving objects:   5% (41871/745349), 11.79 MiB | 596.00 KiB/s
Receiving objects:   5% (44174/745349), 12.39 MiB | 581.00 KiB/s
Receiving objects:   6% (44721/745349), 12.39 MiB | 581.00 KiB/s
Receiving objects:   6% (46452/745349), 13.03 MiB | 597.00 KiB/s
Receiving objects:   6% (49316/745349), 13.84 MiB | 626.00 KiB/s
Receiving objects:   6% (51981/745349), 14.57 MiB | 673.00 KiB/s
Receiving objects:   7% (52175/745349), 14.57 MiB | 673.00 KiB/s
Receiving objects:   7% (55168/745349), 15.36 MiB | 727.00 KiB/s
Receiving objects:   7% (58140/745349), 15.71 MiB | 737.00 KiB/s
Receiving objects:   8% (59628/745349), 16.04 MiB | 746.00 KiB/s
Receiving objects:   8% (61751/745349), 16.43 MiB | 756.00 KiB/s
Receiving objects:   8% (66427/745349), 17.27 MiB | 760.00 KiB/s
Receiving objects:   9% (67082/745349), 17.79 MiB | 794.00 KiB/s
Receiving objects:   9% (72982/745349), 18.43 MiB | 855.00 KiB/s
Receiving objects:  10% (74535/745349), 19.18 MiB | 930.00 KiB/s
Receiving objects:  10% (79035/745349), 19.83 MiB | 994.00 KiB/s
Receiving objects:  11% (81989/745349), 20.77 MiB | 1.03 MiB/s
Receiving objects:  11% (82179/745349), 20.77 MiB | 1.03 MiB/s
Receiving objects:  11% (84624/745349), 21.89 MiB | 1.10 MiB/s
Receiving objects:  11% (87235/745349), 22.94 MiB | 1.12 MiB/s
Receiving objects:  12% (89442/745349), 23.37 MiB | 1.08 MiB/s
Receiving objects:  12% (90549/745349), 23.75 MiB | 1018.00 KiB/s
Receiving objects:  12% (93340/745349), 24.56 MiB | 941.00 KiB/s
Receiving objects:  12% (94805/745349), 25.23 MiB | 860.00 KiB/s
Receiving objects:  12% (96027/745349), 25.83 MiB | 757.00 KiB/s
Receiving objects:  13% (96896/745349), 26.19 MiB | 719.00 KiB/s
Receiving objects:  13% (98469/745349), 26.52 MiB | 698.00 KiB/s
Receiving objects:  13% (100854/745349), 27.30 MiB | 698.00 KiB/s
Receiving objects:  14% (104349/745349), 28.32 MiB | 765.00 KiB/s
Receiving objects:  14% (104580/745349), 28.32 MiB | 765.00 KiB/s
Receiving objects:  14% (107822/745349), 29.19 MiB | 803.00 KiB/s
Receiving objects:  14% (110173/745349), 30.02 MiB | 848.00 KiB/s
Receiving objects:  14% (111654/745349), 30.71 MiB | 838.00 KiB/s
Receiving objects:  15% (111803/745349), 30.71 MiB | 838.00 KiB/s
Receiving objects:  15% (113009/745349), 31.23 MiB | 757.00 KiB/s
Receiving objects:  15% (114162/745349), 31.44 MiB | 679.00 KiB/s
Receiving objects:  15% (115921/745349), 31.95 MiB | 599.00 KiB/s
Receiving objects:  15% (118150/745349), 32.80 MiB | 600.00 KiB/s
Receiving objects:  16% (119256/745349), 33.25 MiB | 621.00 KiB/s
Receiving objects:  16% (121081/745349), 33.66 MiB | 637.00 KiB/s
Receiving objects:  16% (124905/745349), 34.51 MiB | 713.00 KiB/s
Receiving objects:  16% (125397/745349), 35.44 MiB | 827.00 KiB/s
Receiving objects:  16% (125449/745349), 36.49 MiB | 900.00 KiB/s
Receiving objects:  16% (125543/745349), 37.46 MiB | 927.00 KiB/s
Receiving objects:  17% (126710/745349), 37.98 MiB | 955.00 KiB/s
Receiving objects:  17% (127515/745349), 38.48 MiB | 973.00 KiB/s
Receiving objects:  17% (127813/745349), 39.20 MiB | 946.00 KiB/s
Receiving objects:  17% (127999/745349), 39.76 MiB | 837.00 KiB/s
Receiving objects:  17% (128654/745349), 40.31 MiB | 744.00 KiB/s
Receiving objects:  17% (129265/745349), 40.79 MiB | 624.00 KiB/s
Receiving objects:  17% (131961/745349), 41.25 MiB | 529.00 KiB/s
Receiving objects:  17% (132426/745349), 41.58 MiB | 530.00 KiB/s
Receiving objects:  17% (133065/745349), 42.18 MiB | 537.00 KiB/s
Receiving objects:  17% (133583/745349), 42.89 MiB | 571.00 KiB/s
Receiving objects:  17% (134094/745349), 43.55 MiB | 611.00 KiB/s
Receiving objects:  18% (134163/745349), 43.91 MiB | 644.00 KiB/s
Receiving objects:  18% (135016/745349), 44.18 MiB | 650.00 KiB/s
Receiving objects:  18% (135756/745349), 44.86 MiB | 658.00 KiB/s
Receiving objects:  18% (136940/745349), 45.66 MiB | 699.00 KiB/s
Receiving objects:  18% (137702/745349), 46.49 MiB | 736.00 KiB/s
Receiving objects:  18% (138959/745349), 47.27 MiB | 753.00 KiB/s
Receiving objects:  18% (139528/745349), 47.88 MiB | 752.00 KiB/s
Receiving objects:  18% (139708/745349), 48.43 MiB | 710.00 KiB/s
Receiving objects:  18% (139951/745349), 48.71 MiB | 592.00 KiB/s
Receiving objects:  18% (140906/745349), 49.27 MiB | 521.00 KiB/s
Receiving objects:  19% (141617/745349), 49.97 MiB | 534.00 KiB/s
Receiving objects:  19% (141801/745349), 49.97 MiB | 534.00 KiB/s
Receiving objects:  19% (142460/745349), 50.62 MiB | 534.00 KiB/s
Receiving objects:  19% (142905/745349), 51.26 MiB | 590.00 KiB/s
Receiving objects:  19% (143702/745349), 51.89 MiB | 644.00 KiB/s
Receiving objects:  19% (144176/745349), 52.52 MiB | 629.00 KiB/s
Receiving objects:  19% (144603/745349), 52.81 MiB | 619.00 KiB/s
Receiving objects:  19% (144936/745349), 53.43 MiB | 613.00 KiB/s
Receiving objects:  19% (145163/745349), 54.07 MiB | 620.00 KiB/s
Receiving objects:  19% (146101/745349), 54.73 MiB | 630.00 KiB/s
Receiving objects:  19% (146514/745349), 55.43 MiB | 646.00 KiB/s
Receiving objects:  19% (147904/745349), 56.21 MiB | 687.00 KiB/s
Receiving objects:  19% (149010/745349), 57.02 MiB | 730.00 KiB/s
Receiving objects:  20% (149070/745349), 57.35 MiB | 728.00 KiB/s
Receiving objects:  20% (149477/745349), 57.71 MiB | 739.00 KiB/s
Receiving objects:  20% (150044/745349), 58.40 MiB | 741.00 KiB/s
Receiving objects:  20% (150928/745349), 59.21 MiB | 759.00 KiB/s
Receiving objects:  20% (152179/745349), 59.95 MiB | 726.00 KiB/s
Receiving objects:  20% (153239/745349), 60.67 MiB | 730.00 KiB/s
Receiving objects:  20% (154670/745349), 61.60 MiB | 784.00 KiB/s
Receiving objects:  20% (155918/745349), 63.11 MiB | 946.00 KiB/s
Receiving objects:  21% (156524/745349), 63.11 MiB | 946.00 KiB/s
Receiving objects:  21% (157215/745349), 64.39 MiB | 1.04 MiB/s
Receiving objects:  21% (158959/745349), 65.73 MiB | 1.17 MiB/s
Receiving objects:  21% (160173/745349), 66.61 MiB | 1.19 MiB/s
Receiving objects:  21% (160643/745349), 66.93 MiB | 1.15 MiB/s
Receiving objects:  21% (161316/745349), 67.71 MiB | 1014.00 KiB/s
Receiving objects:  21% (161810/745349), 68.46 MiB | 896.00 KiB/s
Receiving objects:  21% (162738/745349), 69.25 MiB | 780.00 KiB/s
Receiving objects:  21% (163609/745349), 70.15 MiB | 787.00 KiB/s
Receiving objects:  22% (163977/745349), 71.07 MiB | 839.00 KiB/s
Receiving objects:  22% (164184/745349), 71.07 MiB | 839.00 KiB/s
Receiving objects:  22% (165794/745349), 72.09 MiB | 895.00 KiB/s
Receiving objects:  22% (166792/745349), 73.16 MiB | 955.00 KiB/s
---
Receiving objects:  23% (172628/745349), 79.36 MiB | 951.00 KiB/s
Receiving objects:  23% (172905/745349), 80.20 MiB | 896.00 KiB/s
Receiving objects:  23% (173050/745349), 80.75 MiB | 805.00 KiB/s
Receiving objects:  23% (173105/745349), 81.05 MiB | 774.00 KiB/s
Receiving objects:  23% (173498/745349), 81.64 MiB | 689.00 KiB/s
Receiving objects:  23% (173999/745349), 82.25 MiB | 643.00 KiB/s
Receiving objects:  23% (175151/745349), 82.91 MiB | 604.00 KiB/s
Receiving objects:  23% (175885/745349), 83.49 MiB | 612.00 KiB/s
Receiving objects:  24% (178884/745349), 84.17 MiB | 636.00 KiB/s
Receiving objects:  24% (178999/745349), 84.17 MiB | 636.00 KiB/s
Receiving objects:  24% (180116/745349), 84.80 MiB | 641.00 KiB/s
Receiving objects:  24% (180610/745349), 85.46 MiB | 647.00 KiB/s
Receiving objects:  24% (181201/745349), 86.14 MiB | 652.00 KiB/s
Receiving objects:  24% (181733/745349), 86.81 MiB | 667.00 KiB/s
Receiving objects:  24% (184271/745349), 87.53 MiB | 672.00 KiB/s
Receiving objects:  25% (186338/745349), 87.89 MiB | 684.00 KiB/s
Receiving objects:  25% (190048/745349), 88.23 MiB | 690.00 KiB/s
Receiving objects:  25% (191548/745349), 89.05 MiB | 726.00 KiB/s
Receiving objects:  25% (192674/745349), 89.79 MiB | 727.00 KiB/s
Receiving objects:  26% (193791/745349), 90.44 MiB | 728.00 KiB/s
Receiving objects:  26% (193937/745349), 90.44 MiB | 728.00 KiB/s
Receiving objects:  26% (196462/745349), 91.12 MiB | 716.00 KiB/s
Receiving objects:  26% (197512/745349), 91.80 MiB | 701.00 KiB/s
Receiving objects:  26% (200420/745349), 92.45 MiB | 675.00 KiB/s
Receiving objects:  27% (201245/745349), 92.83 MiB | 676.00 KiB/s
Receiving objects:  27% (202067/745349), 93.18 MiB | 681.00 KiB/s
Receiving objects:  27% (205010/745349), 93.97 MiB | 705.00 KiB/s
Receiving objects:  27% (206027/745349), 94.82 MiB | 738.00 KiB/s
Receiving objects:  27% (207758/745349), 95.28 MiB | 770.00 KiB/s
Receiving objects:  28% (208698/745349), 95.79 MiB | 817.00 KiB/s
Receiving objects:  28% (210691/745349), 96.24 MiB | 839.00 KiB/s
Receiving objects:  29% (216152/745349), 97.17 MiB | 884.00 KiB/s
Receiving objects:  29% (216193/745349), 97.17 MiB | 884.00 KiB/s
Receiving objects:  29% (218976/745349), 98.26 MiB | 951.00 KiB/s
Receiving objects:  29% (220817/745349), 99.31 MiB | 999.00 KiB/s
Receiving objects:  30% (223605/745349), 100.07 MiB | 951.00 KiB/s
Receiving objects:  30% (224400/745349), 100.07 MiB | 951.00 KiB/s
Receiving objects:  30% (227914/745349), 100.73 MiB | 895.00 KiB/s
Receiving objects:  31% (231059/745349), 101.16 MiB | 888.00 KiB/s
Receiving objects:  31% (232546/745349), 101.65 MiB | 877.00 KiB/s
Receiving objects:  31% (236256/745349), 102.54 MiB | 832.00 KiB/s
Receiving objects:  31% (236277/745349), 103.43 MiB | 821.00 KiB/s
Receiving objects:  31% (236300/745349), 104.42 MiB | 897.00 KiB/s
Receiving objects:  31% (236323/745349), 105.36 MiB | 929.00 KiB/s
Receiving objects:  31% (237164/745349), 106.38 MiB | 953.00 KiB/s
Receiving objects:  32% (238512/745349), 106.90 MiB | 967.00 KiB/s
Receiving objects:  32% (240371/745349), 107.45 MiB | 993.00 KiB/s
---
Receiving objects:  38% (283233/745349), 119.40 MiB | 1017.00 KiB/s
Receiving objects:  38% (283295/745349), 119.40 MiB | 1017.00 KiB/s
Receiving objects:  39% (290687/745349), 120.44 MiB | 1011.00 KiB/s
Receiving objects:  39% (291133/745349), 120.44 MiB | 1011.00 KiB/s
Receiving objects:  39% (294797/745349), 121.15 MiB | 924.00 KiB/s
Receiving objects:  39% (295327/745349), 121.70 MiB | 830.00 KiB/s
Receiving objects:  39% (296018/745349), 122.29 MiB | 749.00 KiB/s
Receiving objects:  39% (297164/745349), 122.96 MiB | 676.00 KiB/s
Receiving objects:  39% (297192/745349), 123.64 MiB | 626.00 KiB/s
Receiving objects:  39% (297629/745349), 124.36 MiB | 651.00 KiB/s
Receiving objects:  40% (298140/745349), 124.65 MiB | 652.00 KiB/s
Receiving objects:  40% (299002/745349), 124.95 MiB | 647.00 KiB/s
Receiving objects:  40% (301489/745349), 125.69 MiB | 684.00 KiB/s
Receiving objects:  41% (305594/745349), 126.14 MiB | 710.00 KiB/s
Receiving objects:  41% (305820/745349), 126.60 MiB | 742.00 KiB/s
Receiving objects:  41% (306833/745349), 127.66 MiB | 817.00 KiB/s
Receiving objects:  41% (310524/745349), 128.41 MiB | 839.00 KiB/s
Receiving objects:  41% (311202/745349), 129.15 MiB | 857.00 KiB/s
Receiving objects:  41% (311251/745349), 130.00 MiB | 854.00 KiB/s
Receiving objects:  41% (311635/745349), 130.96 MiB | 854.00 KiB/s
Receiving objects:  42% (313047/745349), 130.96 MiB | 854.00 KiB/s
Receiving objects:  42% (315372/745349), 131.52 MiB | 854.00 KiB/s
Receiving objects:  43% (320501/745349), 132.81 MiB | 974.00 KiB/s
Receiving objects:  43% (320906/745349), 132.81 MiB | 974.00 KiB/s
---
Receiving objects:  46% (342861/745349), 141.39 MiB | 1018.00 KiB/s
Receiving objects:  46% (343920/745349), 141.75 MiB | 871.00 KiB/s
Receiving objects:  46% (345899/745349), 142.57 MiB | 760.00 KiB/s
Receiving objects:  46% (348600/745349), 143.38 MiB | 744.00 KiB/s
Receiving objects:  47% (350315/745349), 143.79 MiB | 761.00 KiB/s
Receiving objects:  47% (350929/745349), 144.29 MiB | 792.00 KiB/s
Receiving objects:  47% (353205/745349), 145.40 MiB | 886.00 KiB/s
---
Receiving objects:  48% (362199/745349), 154.17 MiB | 1015.00 KiB/s
Receiving objects:  48% (362372/745349), 155.03 MiB | 922.00 KiB/s
Receiving objects:  48% (362410/745349), 155.67 MiB | 848.00 KiB/s
Receiving objects:  48% (362465/745349), 156.04 MiB | 736.00 KiB/s
Receiving objects:  48% (362662/745349), 156.32 MiB | 563.00 KiB/s
Receiving objects:  48% (362853/745349), 156.54 MiB | 403.00 KiB/s
Receiving objects:  48% (362972/745349), 156.65 MiB | 332.00 KiB/s
Receiving objects:  48% (363171/745349), 156.90 MiB | 249.00 KiB/s
Receiving objects:  48% (363340/745349), 157.14 MiB | 221.00 KiB/s
Receiving objects:  48% (363598/745349), 157.43 MiB | 223.00 KiB/s
Receiving objects:  48% (363652/745349), 157.71 MiB | 245.00 KiB/s
Receiving objects:  48% (363687/745349), 158.11 MiB | 286.00 KiB/s
Receiving objects:  48% (363962/745349), 158.61 MiB | 341.00 KiB/s
Receiving objects:  48% (364258/745349), 159.15 MiB | 407.00 KiB/s
Receiving objects:  48% (364487/745349), 159.44 MiB | 439.00 KiB/s
Receiving objects:  48% (364498/745349), 160.13 MiB | 495.00 KiB/s
Receiving objects:  48% (364568/745349), 160.39 MiB | 503.00 KiB/s
Receiving objects:  48% (364927/745349), 161.01 MiB | 527.00 KiB/s
Receiving objects:  49% (365222/745349), 161.41 MiB | 559.00 KiB/s
Receiving objects:  49% (365541/745349), 161.83 MiB | 590.00 KiB/s
Receiving objects:  49% (366835/745349), 162.79 MiB | 678.00 KiB/s
Receiving objects:  49% (368337/745349), 164.77 MiB | 965.00 KiB/s
---
Receiving objects:  52% (389635/745349), 169.31 MiB | 1007.00 KiB/s
Receiving objects:  52% (391705/745349), 170.18 MiB | 933.00 KiB/s
Receiving objects:  52% (392975/745349), 170.64 MiB | 771.00 KiB/s
Receiving objects:  52% (393066/745349), 170.94 MiB | 641.00 KiB/s
Receiving objects:  52% (393581/745349), 171.38 MiB | 546.00 KiB/s
Receiving objects:  53% (395035/745349), 171.60 MiB | 505.00 KiB/s
Receiving objects:  53% (395223/745349), 171.85 MiB | 463.00 KiB/s
Receiving objects:  53% (395746/745349), 172.11 MiB | 426.00 KiB/s
Receiving objects:  53% (395998/745349), 172.60 MiB | 432.00 KiB/s
Receiving objects:  53% (396504/745349), 173.11 MiB | 480.00 KiB/s
Receiving objects:  53% (399015/745349), 173.61 MiB | 495.00 KiB/s
Receiving objects:  53% (399267/745349), 174.18 MiB | 517.00 KiB/s
Receiving objects:  53% (399632/745349), 174.84 MiB | 552.00 KiB/s
Receiving objects:  53% (400218/745349), 175.61 MiB | 616.00 KiB/s
Receiving objects:  54% (402489/745349), 176.64 MiB | 727.00 KiB/s
Receiving objects:  54% (403099/745349), 176.64 MiB | 727.00 KiB/s
Receiving objects:  54% (404706/745349), 177.73 MiB | 853.00 KiB/s
Receiving objects:  54% (404752/745349), 178.44 MiB | 872.00 KiB/s
Receiving objects:  54% (405058/745349), 178.93 MiB | 821.00 KiB/s
Receiving objects:  54% (405073/745349), 179.45 MiB | 740.00 KiB/s
Receiving objects:  54% (405089/745349), 179.99 MiB | 621.00 KiB/s
Receiving objects:  54% (405105/745349), 180.52 MiB | 532.00 KiB/s
Receiving objects:  54% (405119/745349), 180.95 MiB | 501.00 KiB/s
Receiving objects:  54% (405135/745349), 181.46 MiB | 510.00 KiB/s
Receiving objects:  54% (405156/745349), 182.12 MiB | 535.00 KiB/s
Receiving objects:  54% (405184/745349), 182.95 MiB | 605.00 KiB/s
Receiving objects:  54% (405216/745349), 183.89 MiB | 680.00 KiB/s
Receiving objects:  54% (405259/745349), 185.05 MiB | 848.00 KiB/s
Receiving objects:  54% (405312/745349), 185.68 MiB | 929.00 KiB/s
Receiving objects:  54% (405625/745349), 186.94 MiB | 1.03 MiB/s
Receiving objects:  54% (406366/745349), 187.82 MiB | 1.05 MiB/s
Receiving objects:  54% (406390/745349), 188.74 MiB | 1.04 MiB/s
Receiving objects:  54% (406410/745349), 189.64 MiB | 1015.00 KiB/s
Receiving objects:  54% (406431/745349), 190.44 MiB | 905.00 KiB/s
Receiving objects:  54% (406453/745349), 191.33 MiB | 863.00 KiB/s
Receiving objects:  54% (406468/745349), 191.95 MiB | 810.00 KiB/s
Receiving objects:  54% (406485/745349), 192.46 MiB | 702.00 KiB/s
Receiving objects:  54% (406503/745349), 193.00 MiB | 650.00 KiB/s
Receiving objects:  54% (406519/745349), 193.39 MiB | 545.00 KiB/s
Receiving objects:  54% (406594/745349), 193.72 MiB | 452.00 KiB/s
Receiving objects:  54% (406879/745349), 193.93 MiB | 436.00 KiB/s
Receiving objects:  54% (408401/745349), 194.48 MiB | 442.00 KiB/s
Receiving objects:  54% (408786/745349), 195.01 MiB | 439.00 KiB/s
Receiving objects:  54% (408814/745349), 195.61 MiB | 487.00 KiB/s
Receiving objects:  54% (409532/745349), 196.27 MiB | 559.00 KiB/s
Receiving objects:  54% (409765/745349), 197.06 MiB | 633.00 KiB/s
Receiving objects:  54% (409783/745349), 197.82 MiB | 674.00 KiB/s
Receiving objects:  54% (409801/745349), 198.41 MiB | 688.00 KiB/s
Receiving objects:  54% (409827/745349), 199.07 MiB | 677.00 KiB/s
Receiving objects:  54% (409857/745349), 199.71 MiB | 671.00 KiB/s
Receiving objects:  55% (409942/745349), 200.07 MiB | 661.00 KiB/s
Receiving objects:  55% (410524/745349), 200.45 MiB | 653.00 KiB/s
Receiving objects:  55% (415272/745349), 201.35 MiB | 709.00 KiB/s
Receiving objects:  55% (415522/745349), 202.39 MiB | 808.00 KiB/s
Receiving objects:  55% (416383/745349), 203.40 MiB | 886.00 KiB/s
Receiving objects:  55% (416531/745349), 204.29 MiB | 934.00 KiB/s
Receiving objects:  56% (417396/745349), 204.72 MiB | 947.00 KiB/s
Receiving objects:  56% (417923/745349), 205.27 MiB | 976.00 KiB/s
Receiving objects:  56% (421754/745349), 205.78 MiB | 983.00 KiB/s
Receiving objects:  57% (424849/745349), 206.81 MiB | 979.00 KiB/s
Receiving objects:  57% (426373/745349), 206.81 MiB | 979.00 KiB/s
Receiving objects:  57% (430293/745349), 207.75 MiB | 962.00 KiB/s
Receiving objects:  58% (432303/745349), 208.64 MiB | 961.00 KiB/s
Receiving objects:  58% (432573/745349), 208.64 MiB | 961.00 KiB/s
Receiving objects:  58% (434977/745349), 209.22 MiB | 872.00 KiB/s
Receiving objects:  58% (436746/745349), 209.89 MiB | 796.00 KiB/s
Receiving objects:  58% (437673/745349), 210.56 MiB | 720.00 KiB/s
Receiving objects:  59% (439756/745349), 211.18 MiB | 649.00 KiB/s
Receiving objects:  59% (440278/745349), 211.18 MiB | 649.00 KiB/s
Receiving objects:  59% (441711/745349), 211.89 MiB | 658.00 KiB/s
Receiving objects:  59% (445026/745349), 212.67 MiB | 683.00 KiB/s
Receiving objects:  60% (447210/745349), 213.09 MiB | 706.00 KiB/s
Receiving objects:  60% (448269/745349), 213.45 MiB | 709.00 KiB/s
Receiving objects:  60% (449427/745349), 213.98 MiB | 683.00 KiB/s
Receiving objects:  60% (451185/745349), 214.49 MiB | 650.00 KiB/s
Receiving objects:  60% (453066/745349), 215.02 MiB | 609.00 KiB/s
Receiving objects:  60% (453321/745349), 215.61 MiB | 557.00 KiB/s
Receiving objects:  60% (453644/745349), 216.27 MiB | 564.00 KiB/s
Receiving objects:  60% (453666/745349), 216.68 MiB | 592.00 KiB/s
Receiving objects:  60% (453684/745349), 217.43 MiB | 645.00 KiB/s
Receiving objects:  60% (453706/745349), 218.14 MiB | 686.00 KiB/s
Receiving objects:  60% (453722/745349), 218.82 MiB | 703.00 KiB/s
Receiving objects:  60% (453738/745349), 219.31 MiB | 668.00 KiB/s
Receiving objects:  60% (453760/745349), 219.88 MiB | 613.00 KiB/s
Receiving objects:  60% (453792/745349), 220.61 MiB | 631.00 KiB/s
Receiving objects:  61% (454663/745349), 220.94 MiB | 617.00 KiB/s
Receiving objects:  61% (456389/745349), 221.40 MiB | 629.00 KiB/s
Receiving objects:  61% (460648/745349), 222.40 MiB | 739.00 KiB/s
Receiving objects:  62% (462117/745349), 222.88 MiB | 786.00 KiB/s
Receiving objects:  62% (463087/745349), 223.45 MiB | 853.00 KiB/s
Receiving objects:  62% (469040/745349), 224.81 MiB | 1008.00 KiB/s
Receiving objects:  63% (469570/745349), 224.81 MiB | 1008.00 KiB/s
---
Receiving objects:  65% (484477/745349), 231.65 MiB | 894.00 KiB/s
Receiving objects:  65% (484675/745349), 231.65 MiB | 894.00 KiB/s
Receiving objects:  65% (485942/745349), 232.44 MiB | 739.00 KiB/s
Receiving objects:  65% (487112/745349), 233.33 MiB | 718.00 KiB/s
Receiving objects:  65% (488791/745349), 234.16 MiB | 762.00 KiB/s
Receiving objects:  66% (491931/745349), 234.68 MiB | 805.00 KiB/s
Receiving objects:  66% (494235/745349), 235.29 MiB | 878.00 KiB/s
Receiving objects:  66% (498933/745349), 236.58 MiB | 1001.00 KiB/s
Receiving objects:  67% (499384/745349), 236.58 MiB | 1001.00 KiB/s
---
Receiving objects:  68% (509683/745349), 245.77 MiB | 965.00 KiB/s
Receiving objects:  68% (509707/745349), 246.09 MiB | 866.00 KiB/s
Receiving objects:  68% (509741/745349), 246.74 MiB | 688.00 KiB/s
Receiving objects:  68% (509811/745349), 247.52 MiB | 647.00 KiB/s
Receiving objects:  68% (510683/745349), 248.33 MiB | 711.00 KiB/s
Receiving objects:  68% (511731/745349), 249.16 MiB | 755.00 KiB/s
Receiving objects:  68% (511777/745349), 250.09 MiB | 819.00 KiB/s
Receiving objects:  69% (514291/745349), 251.09 MiB | 881.00 KiB/s
Receiving objects:  69% (514348/745349), 251.09 MiB | 881.00 KiB/s
Receiving objects:  69% (515551/745349), 252.25 MiB | 955.00 KiB/s
---
Receiving objects:  72% (537481/745349), 269.15 MiB | 997.00 KiB/s
Receiving objects:  72% (538105/745349), 269.61 MiB | 987.00 KiB/s
Receiving objects:  72% (540760/745349), 270.57 MiB | 994.00 KiB/s
Receiving objects:  72% (543999/745349), 271.27 MiB | 933.00 KiB/s
Receiving objects:  73% (544105/745349), 271.27 MiB | 933.00 KiB/s
Receiving objects:  73% (545900/745349), 272.07 MiB | 862.00 KiB/s
Receiving objects:  73% (547179/745349), 272.87 MiB | 821.00 KiB/s
Receiving objects:  73% (547748/745349), 273.68 MiB | 782.00 KiB/s
Receiving objects:  73% (551319/745349), 274.44 MiB | 780.00 KiB/s
Receiving objects:  74% (551559/745349), 274.88 MiB | 798.00 KiB/s
Receiving objects:  74% (553088/745349), 275.26 MiB | 797.00 KiB/s
Receiving objects:  74% (554218/745349), 276.18 MiB | 823.00 KiB/s
Receiving objects:  74% (555137/745349), 277.08 MiB | 839.00 KiB/s
Receiving objects:  74% (557757/745349), 277.65 MiB | 797.00 KiB/s
Receiving objects:  75% (559012/745349), 278.25 MiB | 749.00 KiB/s
Receiving objects:  75% (559093/745349), 278.25 MiB | 749.00 KiB/s
Receiving objects:  75% (560012/745349), 278.86 MiB | 692.00 KiB/s
Receiving objects:  75% (561829/745349), 279.52 MiB | 634.00 KiB/s
Receiving objects:  75% (563017/745349), 280.16 MiB | 606.00 KiB/s
Receiving objects:  75% (564925/745349), 280.92 MiB | 651.00 KiB/s
Receiving objects:  76% (566466/745349), 281.34 MiB | 678.00 KiB/s
Receiving objects:  76% (566670/745349), 281.34 MiB | 678.00 KiB/s
Receiving objects:  76% (569773/745349), 282.32 MiB | 766.00 KiB/s
Receiving objects:  76% (573556/745349), 283.26 MiB | 824.00 KiB/s
Receiving objects:  77% (573919/745349), 283.75 MiB | 866.00 KiB/s
Receiving objects:  77% (576504/745349), 284.23 MiB | 897.00 KiB/s
Receiving objects:  78% (581373/745349), 285.32 MiB | 968.00 KiB/s
Receiving objects:  78% (581560/745349), 285.32 MiB | 968.00 KiB/s
Receiving objects:  78% (584228/745349), 286.33 MiB | 1000.00 KiB/s
Receiving objects:  78% (586109/745349), 287.18 MiB | 970.00 KiB/s
Receiving objects:  78% (587405/745349), 287.75 MiB | 886.00 KiB/s
Receiving objects:  79% (588826/745349), 288.40 MiB | 808.00 KiB/s
Receiving objects:  79% (589183/745349), 288.40 MiB | 808.00 KiB/s
Receiving objects:  79% (590216/745349), 289.49 MiB | 696.00 KiB/s
Receiving objects:  79% (590216/745349), 290.23 MiB | 673.00 KiB/s
Receiving objects:  79% (590216/745349), 291.05 MiB | 724.00 KiB/s
Receiving objects:  79% (592233/745349), 291.50 MiB | 757.00 KiB/s
Receiving objects:  79% (595995/745349), 292.39 MiB | 801.00 KiB/s
Receiving objects:  80% (596280/745349), 292.39 MiB | 801.00 KiB/s
Receiving objects:  80% (598257/745349), 293.34 MiB | 848.00 KiB/s
Receiving objects:  80% (600491/745349), 294.25 MiB | 885.00 KiB/s
Receiving objects:  80% (602923/745349), 294.61 MiB | 874.00 KiB/s
Receiving objects:  81% (603733/745349), 294.98 MiB | 869.00 KiB/s
Receiving objects:  81% (607514/745349), 295.39 MiB | 861.00 KiB/s
Receiving objects:  81% (610228/745349), 296.12 MiB | 819.00 KiB/s
Receiving objects:  82% (611187/745349), 296.53 MiB | 806.00 KiB/s
Receiving objects:  82% (613275/745349), 296.85 MiB | 772.00 KiB/s
Receiving objects:  82% (616957/745349), 297.56 MiB | 730.00 KiB/s
Receiving objects:  82% (618108/745349), 298.30 MiB | 732.00 KiB/s
Receiving objects:  83% (618640/745349), 298.68 MiB | 725.00 KiB/s
Receiving objects:  83% (619594/745349), 299.10 MiB | 737.00 KiB/s
Receiving objects:  83% (622849/745349), 299.88 MiB | 742.00 KiB/s
Receiving objects:  83% (624252/745349), 301.08 MiB | 777.00 KiB/s
Receiving objects:  83% (624252/745349), 301.94 MiB | 804.00 KiB/s
Receiving objects:  83% (624252/745349), 302.86 MiB | 832.00 KiB/s
Receiving objects:  83% (624703/745349), 303.35 MiB | 851.00 KiB/s
Receiving objects:  84% (626094/745349), 303.76 MiB | 854.00 KiB/s
Receiving objects:  84% (626415/745349), 304.12 MiB | 837.00 KiB/s
Receiving objects:  84% (628383/745349), 304.80 MiB | 817.00 KiB/s
Receiving objects:  84% (630250/745349), 305.57 MiB | 800.00 KiB/s
Receiving objects:  84% (631998/745349), 306.26 MiB | 746.00 KiB/s
Receiving objects:  85% (633547/745349), 306.61 MiB | 716.00 KiB/s
Receiving objects:  85% (634338/745349), 306.61 MiB | 716.00 KiB/s
Receiving objects:  85% (637382/745349), 307.31 MiB | 701.00 KiB/s
Receiving objects:  85% (640909/745349), 308.23 MiB | 755.00 KiB/s
Receiving objects:  86% (641001/745349), 308.23 MiB | 755.00 KiB/s
Receiving objects:  86% (643092/745349), 309.10 MiB | 776.00 KiB/s
Receiving objects:  86% (646481/745349), 310.08 MiB | 842.00 KiB/s
Receiving objects:  87% (648454/745349), 310.57 MiB | 876.00 KiB/s
Receiving objects:  87% (651882/745349), 310.95 MiB | 887.00 KiB/s
Receiving objects:  87% (653867/745349), 311.62 MiB | 853.00 KiB/s
Receiving objects:  88% (655908/745349), 312.39 MiB | 817.00 KiB/s
Receiving objects:  88% (655915/745349), 312.39 MiB | 817.00 KiB/s
Receiving objects:  88% (659095/745349), 313.27 MiB | 817.00 KiB/s
Receiving objects:  88% (660706/745349), 314.25 MiB | 812.00 KiB/s
Receiving objects:  88% (662303/745349), 315.08 MiB | 844.00 KiB/s
Receiving objects:  89% (663361/745349), 315.38 MiB | 830.00 KiB/s
Receiving objects:  89% (664687/745349), 315.69 MiB | 821.00 KiB/s
Receiving objects:  89% (667995/745349), 316.43 MiB | 799.00 KiB/s
Receiving objects:  89% (669995/745349), 317.18 MiB | 753.00 KiB/s
Receiving objects:  90% (670815/745349), 317.18 MiB | 753.00 KiB/s
Receiving objects:  90% (672386/745349), 317.80 MiB | 683.00 KiB/s
Receiving objects:  90% (674949/745349), 318.46 MiB | 675.00 KiB/s
Receiving objects:  90% (675426/745349), 318.81 MiB | 684.00 KiB/s
Receiving objects:  91% (678268/745349), 319.55 MiB | 686.00 KiB/s
Receiving objects:  91% (679212/745349), 319.55 MiB | 686.00 KiB/s
Receiving objects:  91% (683615/745349), 320.28 MiB | 688.00 KiB/s
Receiving objects:  92% (685722/745349), 320.64 MiB | 708.00 KiB/s
Receiving objects:  92% (687976/745349), 321.42 MiB | 734.00 KiB/s
Receiving objects:  92% (688657/745349), 321.84 MiB | 757.00 KiB/s
Receiving objects:  92% (692716/745349), 322.64 MiB | 774.00 KiB/s
Receiving objects:  93% (693175/745349), 323.06 MiB | 784.00 KiB/s
Receiving objects:  93% (695950/745349), 323.45 MiB | 789.00 KiB/s
Receiving objects:  93% (697059/745349), 324.29 MiB | 808.00 KiB/s
Receiving objects:  93% (697557/745349), 325.02 MiB | 799.00 KiB/s
Receiving objects:  93% (699992/745349), 325.63 MiB | 752.00 KiB/s
Receiving objects:  94% (700629/745349), 326.16 MiB | 688.00 KiB/s
Receiving objects:  94% (701234/745349), 326.16 MiB | 688.00 KiB/s
Receiving objects:  94% (703303/745349), 326.65 MiB | 632.00 KiB/s
Receiving objects:  94% (707445/745349), 327.23 MiB | 565.00 KiB/s
Receiving objects:  95% (708082/745349), 327.50 MiB | 550.00 KiB/s
Receiving objects:  95% (709266/745349), 327.76 MiB | 543.00 KiB/s
Receiving objects:  95% (710077/745349), 328.23 MiB | 515.00 KiB/s
Receiving objects:  95% (710300/745349), 328.73 MiB | 515.00 KiB/s
Receiving objects:  95% (712709/745349), 329.30 MiB | 527.00 KiB/s
Receiving objects:  95% (714729/745349), 329.86 MiB | 524.00 KiB/s
Receiving objects:  96% (715536/745349), 329.86 MiB | 524.00 KiB/s
Receiving objects:  96% (718289/745349), 330.39 MiB | 530.00 KiB/s
Receiving objects:  96% (719395/745349), 330.98 MiB | 558.00 KiB/s
Receiving objects:  96% (721826/745349), 331.68 MiB | 595.00 KiB/s
Receiving objects:  97% (722989/745349), 331.68 MiB | 595.00 KiB/s
Receiving objects:  97% (725413/745349), 332.42 MiB | 629.00 KiB/s
Receiving objects:  97% (726500/745349), 332.70 MiB | 635.00 KiB/s
Receiving objects:  97% (728585/745349), 333.25 MiB | 637.00 KiB/s
Receiving objects:  98% (730443/745349), 333.57 MiB | 643.00 KiB/s
Receiving objects:  98% (733147/745349), 333.94 MiB | 657.00 KiB/s
Receiving objects:  98% (734316/745349), 334.72 MiB | 675.00 KiB/s
Receiving objects:  99% (737896/745349), 335.14 MiB | 687.00 KiB/s
Receiving objects:  99% (741649/745349), 335.54 MiB | 693.00 KiB/s
remote: Total 745349 (delta 604716), reused 738386 (delta 597809), pack-reused 0
Receiving objects: 100% (745349/745349), 335.92 MiB | 716.00 KiB/s
Receiving objects: 100% (745349/745349), 336.18 MiB | 818.00 KiB/s, done.
---
Resolving deltas: 100% (604716/604716), completed with 4781 local objects.
---
[00:01:07] configure: rust.quiet-tests     := True
---
[00:09:13] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1556: line longer than 100 chars
[00:09:13] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1583: line longer than 100 chars
[00:09:13] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1611: line longer than 100 chars
---
116988 ./obj/build/bootstrap/debug/incremental/bootstrap-232achgbjnpqy/s-ezu8bvkva4-1uibcia-23cdd79jjy90a
---
10012 ./src/llvm/test/MC/AMDGPU
9648 ./src/llvm/test/MC/Disassembler/AMDGPU
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:18dce027:start=1522947461088523751,finish=1522947461096338236,duration=7814485
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0029bbc0
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362736706). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (604721/604721), completed with 4781 local objects.
---
[00:01:59] configure: rust.quiet-tests     := True
---
[00:15:13] 299 |         self.cancel_if_wrong_origin(err, o)
[00:15:13]     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
[00:15:13]     |
[00:15:13]     = note: expected type `rustc_errors::DiagnosticBuilder<'_>`
[00:15:13]                found type `rustc_errors::DiagnosticBuilder<'cx>`
[00:15:13] note: the lifetime 'cx as defined on the trait at 55:1...
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:55:1
[00:15:13]     |
[00:15:13] 55  | pub trait BorrowckErrors<'cx>: Sized + Copy {
[00:15:13]     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:15:13] note: ...does not necessarily outlive the anonymous lifetime #1 defined on the method body at 287:5
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:287:5
[00:15:13]     |
[00:15:13] 287 | /     fn cannot_assign(&self, span: Span, desc: &str, o: Origin, is_reference:bool)
[00:15:13] 288 | |                      -> DiagnosticBuilder
[00:15:13] 289 | |     {
[00:15:13] 290 | |         let msg = if is_reference {
[00:15:13] ...   |
[00:15:13] 299 | |         self.cancel_if_wrong_origin(err, o)
[00:15:13] 300 | |     }
[00:15:13]     | |_____^
[00:15:13]
[00:15:13] error[E0309]: the parameter type `Self` may not live long enough
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:305:9
[00:15:13]     |
[00:15:13] 305 |         self.cannot_assign(span, &format!("immutable static item `{}`", desc), o, false)
[00:15:13]     |         ^^^^
[00:15:13]     |
[00:15:13]     = help: consider adding an explicit lifetime bound `Self: 'cx`...
[00:15:13] note: ...so that the type `Self` is not borrowed for too long
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:305:9
[00:15:13]     |
[00:15:13] 305 |         self.cannot_assign(span, &format!("immutable static item `{}`", desc), o, false)
[00:15:13]     |         ^^^^
[00:15:13]
[00:15:13] error[E0309]: the parameter type `Self` may not live long enough
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:305:14
[00:15:13]     |
[00:15:13] 305 |         self.cannot_assign(span, &format!("immutable static item `{}`", desc), o, false)
[00:15:13]     |              ^^^^^^^^^^^^^
[00:15:13]     |
[00:15:13]     = help: consider adding an explicit lifetime bound `Self: 'cx`...
[00:15:13] note: ...so that the reference type `&Self` does not outlive the data it points at
[00:15:13]    --> librustc_mir/util/borrowck_errors.rs:305:14
[00:15:13]     |
[00:15:13] 305 |         self.cannot_assign(span, &format!("immutable static item `{}`", desc), o, false)
---
[00:15:16]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name rustc_mir librustc_mir/lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=2 -C metadata=1b4c3b4ba4ec5832 -C extra-filename=-1b4c3b4ba4ec5832 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --extern rustc_apfloat=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_apfloat-b23276248c684a7d.rlib --extern syntax_pos=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax_pos-069d1433ad059ff1.so --extern log_settings=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog_settings-6f97f4efb9094c9d.rlib --extern byteorder=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbyteorder-f04ca02424a68c4e.rlib --extern graphviz=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libgraphviz-01fc77d929e8bdd6.so --extern serialize=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-f27fded04dd31022.so --extern serialize=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-f27fded04dd31022.rlib --extern rustc_const_math=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_const_math-2cbdd37d611532dc.so --extern rustc_back=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_back-c188df8980be19c3.so --extern syntax=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax-67023beb7edf290b.so --extern rustc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc-b061046bb39a474d.so --extern rustc_errors=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_errors-d823127e323fa243.so --extern arena=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libarena-2e4ce590106ede04.so --extern log=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog-7eebd272275b441b.rlib --extern bitflags=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbitflags-e01ce88b04783514.rlib --extern rustc_data_structures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_data_structures-1e725c22de2888b8.so -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/backtrace-sys-751752dec0960570/out/.libs -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/miniz-sys-07c608814ba8d6ba/out` (exit code: 101)
[00:15:16] warning: build failed, waiting for other jobs to finish...
[00:16:04] error: build failed
[00:16:04] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" " jemalloc" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json"
[00:16:04] expected success, got: exit code: 101
[00:16:04] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1085:9
[00:16:04] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:16:04] travis_fold:end:stage0-rustc
[00:16:04] travis_time:end:stage0-rustc:start=1522949892723702712,finish=1522950514379066873,duration=621655364161
[00:16:04] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:16:04] Build completed unsuccessfully in 0:10:34
[00:16:04] Makefile:28: recipe for target 'all' failed
[00:16:04] make: *** [all] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:06721130:start=1522950515012849782,finish=1522950515018970371,duration=6120589
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:109f6e6c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

File: src/test/compile-fail/borrowck/borrowck-issue-14498.rs (hunk 8 above)
Comment (gaurikholkar) [reply src/test/compile-fail/borrowck/borrowck-issue-14498.rs]: Is this the common message for all such cases or just for the above case?

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363138817). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612604/612604), completed with 4871 local objects.
---
[00:00:46] configure: rust.quiet-tests     := True
---
[00:04:26] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1595: trailing whitespace
[00:04:26] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1611: line longer than 100 chars
[00:04:28] some tidy checks failed
[00:04:28]
[00:04:28]
[00:04:28] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:28] expected success, got: exit code: 1
[00:04:28]
[00:04:28]
[00:04:28] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:28] Build completed unsuccessfully in 0:01:54
[00:04:28] make: *** [tidy] Error 1
[00:04:28] Makefile:79: recipe for target 'tidy' failed
---
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:0137809c:start=1523025671971517003,finish=1523025671979159888,duration=7642885
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:07f0b300
$ dmesg | grep -i kill
[   11.328129] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363137246). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Receiving objects:   0% (100/12966), 340.00 KiB | 327.00 KiB/s
Receiving objects:   1% (130/12966), 340.00 KiB | 327.00 KiB/s
Receiving objects:   2% (260/12966), 340.00 KiB | 327.00 KiB/s
Receiving objects:   3% (389/12966), 340.00 KiB | 327.00 KiB/s
Receiving objects:   4% (519/12966), 764.00 KiB | 496.00 KiB/s
Receiving objects:   4% (586/12966), 764.00 KiB | 496.00 KiB/s
Receiving objects:   5% (649/12966), 1.36 MiB | 680.00 KiB/s
Receiving objects:   6% (778/12966), 1.36 MiB | 680.00 KiB/s
Receiving objects:   7% (908/12966), 1.36 MiB | 680.00 KiB/s
Receiving objects:   7% (960/12966), 2.18 MiB | 866.00 KiB/s
Receiving objects:   8% (1038/12966), 2.29 MiB | 758.00 KiB/s
Receiving objects:   9% (1167/12966), 2.29 MiB | 758.00 KiB/s
Receiving objects:  10% (1297/12966), 3.00 MiB | 850.00 KiB/s
Receiving objects:  11% (1427/12966), 3.00 MiB | 850.00 KiB/s
Receiving objects:  11% (1494/12966), 3.00 MiB | 850.00 KiB/s
Receiving objects:  12% (1556/12966), 3.92 MiB | 976.00 KiB/s
Receiving objects:  13% (1686/12966), 3.92 MiB | 976.00 KiB/s
---
Receiving objects:   1% (11859/754806), 3.56 MiB | 1013.00 KiB/s
Receiving objects:   1% (14108/754806), 4.26 MiB | 943.00 KiB/s
Receiving objects:   2% (15097/754806), 4.60 MiB | 878.00 KiB/s
Receiving objects:   2% (16437/754806), 4.94 MiB | 817.00 KiB/s
Receiving objects:   2% (18527/754806), 5.61 MiB | 745.00 KiB/s
Receiving objects:   2% (20358/754806), 6.21 MiB | 686.00 KiB/s
Receiving objects:   2% (22067/754806), 6.74 MiB | 621.00 KiB/s
Receiving objects:   3% (22645/754806), 6.95 MiB | 594.00 KiB/s
Receiving objects:   3% (23287/754806), 7.14 MiB | 564.00 KiB/s
Receiving objects:   3% (24589/754806), 7.50 MiB | 495.00 KiB/s
Receiving objects:   3% (26374/754806), 7.96 MiB | 443.00 KiB/s
Receiving objects:   3% (28398/754806), 8.48 MiB | 440.00 KiB/s
Receiving objects:   4% (30193/754806), 8.76 MiB | 446.00 KiB/s
Receiving objects:   4% (30578/754806), 9.02 MiB | 456.00 KiB/s
Receiving objects:   4% (32573/754806), 9.57 MiB | 493.00 KiB/s
Receiving objects:   4% (34354/754806), 10.04 MiB | 507.00 KiB/s
Receiving objects:   4% (35972/754806), 10.46 MiB | 503.00 KiB/s
Receiving objects:   4% (37258/754806), 10.83 MiB | 462.00 KiB/s
Receiving objects:   5% (37741/754806), 10.83 MiB | 462.00 KiB/s
Receiving objects:   5% (38848/754806), 11.25 MiB | 431.00 KiB/s
Receiving objects:   5% (40673/754806), 11.70 MiB | 424.00 KiB/s
Receiving objects:   5% (42844/754806), 11.98 MiB | 437.00 KiB/s
Receiving objects:   6% (45289/754806), 12.64 MiB | 489.00 KiB/s
Receiving objects:   6% (45646/754806), 12.64 MiB | 489.00 KiB/s
Receiving objects:   6% (47898/754806), 13.35 MiB | 561.00 KiB/s
Receiving objects:   6% (49829/754806), 13.95 MiB | 604.00 KiB/s
Receiving objects:   6% (51464/754806), 14.42 MiB | 607.00 KiB/s
Receiving objects:   7% (52837/754806), 14.84 MiB | 565.00 KiB/s
Receiving objects:   7% (53053/754806), 14.84 MiB | 565.00 KiB/s
Receiving objects:   7% (54469/754806), 15.23 MiB | 487.00 KiB/s
Receiving objects:   7% (56427/754806), 15.69 MiB | 444.00 KiB/s
Receiving objects:   7% (58621/754806), 16.20 MiB | 436.00 KiB/s
Receiving objects:   8% (60385/754806), 16.68 MiB | 447.00 KiB/s
Receiving objects:   8% (60601/754806), 16.68 MiB | 447.00 KiB/s
Receiving objects:   8% (62670/754806), 17.11 MiB | 452.00 KiB/s
Receiving objects:   8% (64997/754806), 17.54 MiB | 464.00 KiB/s
Receiving objects:   8% (67259/754806), 18.01 MiB | 455.00 KiB/s
Receiving objects:   9% (67933/754806), 18.01 MiB | 455.00 KiB/s
Receiving objects:   9% (69528/754806), 18.46 MiB | 449.00 KiB/s
Receiving objects:   9% (72068/754806), 18.96 MiB | 455.00 KiB/s
Receiving objects:   9% (74374/754806), 19.44 MiB | 468.00 KiB/s
Receiving objects:  10% (75481/754806), 19.44 MiB | 468.00 KiB/s
Receiving objects:  10% (77472/754806), 20.04 MiB | 502.00 KiB/s
Receiving objects:  10% (79594/754806), 20.57 MiB | 523.00 KiB/s
Receiving objects:  10% (81311/754806), 20.96 MiB | 503.00 KiB/s
Receiving objects:  10% (82528/754806), 21.34 MiB | 479.00 KiB/s
Receiving objects:  11% (83029/754806), 21.34 MiB | 479.00 KiB/s
Receiving objects:  11% (83892/754806), 21.79 MiB | 461.00 KiB/s
Receiving objects:  11% (85178/754806), 22.05 MiB | 450.00 KiB/s
Receiving objects:  11% (86970/754806), 22.83 MiB | 506.00 KiB/s
Receiving objects:  11% (88929/754806), 23.57 MiB | 582.00 KiB/s
Receiving objects:  12% (90577/754806), 24.18 MiB | 633.00 KiB/s
Receiving objects:  12% (91661/754806), 24.18 MiB | 633.00 KiB/s
Receiving objects:  12% (94400/754806), 24.82 MiB | 673.00 KiB/s
Receiving objects:  12% (95961/754806), 25.55 MiB | 705.00 KiB/s
Receiving objects:  12% (97695/754806), 26.29 MiB | 685.00 KiB/s
Receiving objects:  13% (98125/754806), 26.68 MiB | 696.00 KiB/s
Receiving objects:  13% (100234/754806), 27.07 MiB | 715.00 KiB/s
Receiving objects:  13% (102605/754806), 27.85 MiB | 745.00 KiB/s
Receiving objects:  14% (105673/754806), 28.67 MiB | 778.00 KiB/s
Receiving objects:  14% (105751/754806), 28.67 MiB | 778.00 KiB/s
Receiving objects:  14% (108909/754806), 29.49 MiB | 793.00 KiB/s
Receiving objects:  14% (111296/754806), 30.31 MiB | 804.00 KiB/s
Receiving objects:  15% (113221/754806), 31.23 MiB | 825.00 KiB/s
Receiving objects:  15% (113413/754806), 31.23 MiB | 825.00 KiB/s
Receiving objects:  15% (115823/754806), 32.11 MiB | 856.00 KiB/s
Receiving objects:  15% (118336/754806), 32.99 MiB | 861.00 KiB/s
Receiving objects:  15% (120720/754806), 33.89 MiB | 872.00 KiB/s
Receiving objects:  16% (120769/754806), 33.89 MiB | 872.00 KiB/s
Receiving objects:  16% (123879/754806), 34.69 MiB | 863.00 KiB/s
Receiving objects:  16% (126360/754806), 35.50 MiB | 835.00 KiB/s
Receiving objects:  16% (127989/754806), 36.23 MiB | 815.00 KiB/s
Receiving objects:  16% (128020/754806), 36.49 MiB | 773.00 KiB/s
Receiving objects:  17% (128318/754806), 36.76 MiB | 734.00 KiB/s
Receiving objects:  17% (128725/754806), 36.99 MiB | 688.00 KiB/s
Receiving objects:  17% (129106/754806), 37.49 MiB | 619.00 KiB/s
Receiving objects:  17% (129848/754806), 38.11 MiB | 582.00 KiB/s
Receiving objects:  17% (130163/754806), 38.82 MiB | 573.00 KiB/s
Receiving objects:  17% (130508/754806), 39.52 MiB | 610.00 KiB/s
Receiving objects:  17% (131403/754806), 40.25 MiB | 672.00 KiB/s
Receiving objects:  17% (131665/754806), 41.00 MiB | 712.00 KiB/s
Receiving objects:  17% (131927/754806), 41.57 MiB | 680.00 KiB/s
Receiving objects:  17% (132373/754806), 42.06 MiB | 639.00 KiB/s
Receiving objects:  17% (132746/754806), 42.57 MiB | 580.00 KiB/s
Receiving objects:  17% (133139/754806), 43.12 MiB | 553.00 KiB/s
Receiving objects:  17% (133605/754806), 43.71 MiB | 520.00 KiB/s
Receiving objects:  17% (133876/754806), 44.38 MiB | 557.00 KiB/s
Receiving objects:  17% (134267/754806), 45.13 MiB | 621.00 KiB/s
Receiving objects:  17% (134764/754806), 45.54 MiB | 653.00 KiB/s
Receiving objects:  17% (135590/754806), 46.20 MiB | 668.00 KiB/s
Receiving objects:  18% (135866/754806), 46.63 MiB | 703.00 KiB/s
Receiving objects:  18% (136123/754806), 46.98 MiB | 714.00 KiB/s
Receiving objects:  18% (136869/754806), 47.77 MiB | 744.00 KiB/s
Receiving objects:  18% (137754/754806), 48.62 MiB | 762.00 KiB/s
Receiving objects:  18% (137775/754806), 49.53 MiB | 797.00 KiB/s
Receiving objects:  18% (137795/754806), 50.21 MiB | 792.00 KiB/s
Receiving objects:  18% (138143/754806), 50.96 MiB | 787.00 KiB/s
Receiving objects:  18% (138247/754806), 51.74 MiB | 780.00 KiB/s
Receiving objects:  18% (138685/754806), 52.64 MiB | 785.00 KiB/s
Receiving objects:  18% (139540/754806), 53.54 MiB | 797.00 KiB/s
Receiving objects:  18% (141058/754806), 54.54 MiB | 871.00 KiB/s
Receiving objects:  18% (141095/754806), 55.43 MiB | 897.00 KiB/s
Receiving objects:  18% (141141/754806), 56.34 MiB | 926.00 KiB/s
Receiving objects:  18% (141196/754806), 56.75 MiB | 911.00 KiB/s
Receiving objects:  18% (141566/754806), 57.44 MiB | 869.00 KiB/s
Receiving objects:  18% (142822/754806), 58.00 MiB | 770.00 KiB/s
Receiving objects:  18% (143273/754806), 58.55 MiB | 694.00 KiB/s
Receiving objects:  18% (143410/754806), 59.08 MiB | 607.00 KiB/s
Receiving objects:  19% (143414/754806), 59.08 MiB | 607.00 KiB/s
Receiving objects:  19% (143791/754806), 59.54 MiB | 540.00 KiB/s
Receiving objects:  19% (144386/754806), 60.02 MiB | 509.00 KiB/s
Receiving objects:  19% (144628/754806), 60.63 MiB | 511.00 KiB/s
Receiving objects:  19% (144914/754806), 61.33 MiB | 554.00 KiB/s
Receiving objects:  19% (145737/754806), 61.97 MiB | 583.00 KiB/s
Receiving objects:  19% (147216/754806), 62.46 MiB | 598.00 KiB/s
Receiving objects:  19% (147309/754806), 62.94 MiB | 582.00 KiB/s
Receiving objects:  19% (147998/754806), 63.39 MiB | 537.00 KiB/s
Receiving objects:  19% (148135/754806), 63.97 MiB | 505.00 KiB/s
Receiving objects:  19% (149120/754806), 64.56 MiB | 524.00 KiB/s
Receiving objects:  19% (150699/754806), 65.14 MiB | 536.00 KiB/s
Receiving objects:  20% (150962/754806), 65.14 MiB | 536.00 KiB/s
Receiving objects:  20% (152584/754806), 65.77 MiB | 583.00 KiB/s
Receiving objects:  20% (152926/754806), 66.22 MiB | 560.00 KiB/s
Receiving objects:  20% (153461/754806), 66.59 MiB | 516.00 KiB/s
Receiving objects:  20% (153777/754806), 66.82 MiB | 503.00 KiB/s
Receiving objects:  20% (154215/754806), 67.33 MiB | 482.00 KiB/s
Receiving objects:  20% (155780/754806), 68.25 MiB | 547.00 KiB/s
Receiving objects:  20% (157270/754806), 69.54 MiB | 738.00 KiB/s
Receiving objects:  20% (157968/754806), 70.35 MiB | 833.00 KiB/s
Receiving objects:  21% (158510/754806), 70.75 MiB | 872.00 KiB/s
Receiving objects:  21% (159361/754806), 71.20 MiB | 927.00 KiB/s
Receiving objects:  21% (160369/754806), 72.11 MiB | 977.00 KiB/s
Receiving objects:  21% (161643/754806), 73.00 MiB | 895.00 KiB/s
Receiving objects:  21% (162073/754806), 73.77 MiB | 840.00 KiB/s
Receiving objects:  21% (162660/754806), 74.36 MiB | 791.00 KiB/s
Receiving objects:  21% (163439/754806), 74.96 MiB | 725.00 KiB/s
Receiving objects:  21% (163652/754806), 75.50 MiB | 650.00 KiB/s
Receiving objects:  21% (163825/754806), 75.94 MiB | 540.00 KiB/s
Receiving objects:  21% (164027/754806), 76.36 MiB | 492.00 KiB/s
Receiving objects:  21% (164065/754806), 76.62 MiB | 491.00 KiB/s
Receiving objects:  21% (164913/754806), 77.08 MiB | 460.00 KiB/s
Receiving objects:  21% (165249/754806), 77.54 MiB | 444.00 KiB/s
Receiving objects:  21% (165913/754806), 78.00 MiB | 451.00 KiB/s
Receiving objects:  22% (166058/754806), 78.26 MiB | 465.00 KiB/s
Receiving objects:  22% (167054/754806), 78.52 MiB | 473.00 KiB/s
Receiving objects:  22% (167548/754806), 79.03 MiB | 466.00 KiB/s
Receiving objects:  22% (167970/754806), 79.44 MiB | 450.00 KiB/s
Receiving objects:  22% (168239/754806), 79.80 MiB | 436.00 KiB/s
Receiving objects:  22% (169144/754806), 80.28 MiB | 435.00 KiB/s
Receiving objects:  22% (170076/754806), 80.84 MiB | 446.00 KiB/s
Receiving objects:  22% (171057/754806), 81.45 MiB | 480.00 KiB/s
Receiving objects:  22% (172066/754806), 82.18 MiB | 568.00 KiB/s
Receiving objects:  22% (173532/754806), 83.07 MiB | 677.00 KiB/s
Receiving objects:  23% (173606/754806), 83.07 MiB | 677.00 KiB/s
Receiving objects:  23% (174334/754806), 83.50 MiB | 717.00 KiB/s
Receiving objects:  23% (175601/754806), 84.46 MiB | 807.00 KiB/s
Receiving objects:  23% (177337/754806), 85.56 MiB | 914.00 KiB/s
Receiving objects:  23% (178142/754806), 86.57 MiB | 971.00 KiB/s
Receiving objects:  23% (179002/754806), 87.38 MiB | 956.00 KiB/s
Receiving objects:  23% (181025/754806), 88.33 MiB | 963.00 KiB/s
Receiving objects:  24% (181154/754806), 88.33 MiB | 963.00 KiB/s
Receiving objects:  24% (181903/754806), 89.26 MiB | 943.00 KiB/s
Receiving objects:  24% (182412/754806), 90.07 MiB | 876.00 KiB/s
Receiving objects:  24% (183187/754806), 90.60 MiB | 806.00 KiB/s
Receiving objects:  24% (184242/754806), 91.21 MiB | 754.00 KiB/s
Receiving objects:  24% (185549/754806), 91.83 MiB | 671.00 KiB/s
Receiving objects:  24% (188114/754806), 92.46 MiB | 607.00 KiB/s
Receiving objects:  25% (188702/754806), 92.46 MiB | 607.00 KiB/s
Receiving objects:  25% (191363/754806), 93.13 MiB | 627.00 KiB/s
Receiving objects:  25% (194705/754806), 93.57 MiB | 599.00 KiB/s
Receiving objects:  26% (196250/754806), 93.79 MiB | 572.00 KiB/s
Receiving objects:  26% (198026/754806), 94.00 MiB | 550.00 KiB/s
Receiving objects:  26% (200858/754806), 94.45 MiB | 511.00 KiB/s
Receiving objects:  26% (201788/754806), 95.04 MiB | 497.00 KiB/s
Receiving objects:  26% (203012/754806), 95.74 MiB | 527.00 KiB/s
Receiving objects:  27% (203798/754806), 96.06 MiB | 554.00 KiB/s
Receiving objects:  27% (204546/754806), 96.43 MiB | 593.00 KiB/s
Receiving objects:  27% (205893/754806), 97.18 MiB | 660.00 KiB/s
Receiving objects:  27% (206058/754806), 97.77 MiB | 672.00 KiB/s
Receiving objects:  27% (206743/754806), 98.04 MiB | 665.00 KiB/s
Receiving objects:  27% (209899/754806), 98.64 MiB | 643.00 KiB/s
Receiving objects:  28% (211346/754806), 99.03 MiB | 655.00 KiB/s
Receiving objects:  28% (213672/754806), 99.47 MiB | 670.00 KiB/s
Receiving objects:  28% (216003/754806), 100.32 MiB | 698.00 KiB/s
Receiving objects:  28% (217231/754806), 101.01 MiB | 720.00 KiB/s
Receiving objects:  28% (218743/754806), 101.48 MiB | 691.00 KiB/s
Receiving objects:  29% (218894/754806), 101.72 MiB | 679.00 KiB/s
Receiving objects:  29% (219375/754806), 101.96 MiB | 648.00 KiB/s
Receiving objects:  29% (220146/754806), 102.44 MiB | 555.00 KiB/s
Receiving objects:  29% (220784/754806), 102.99 MiB | 503.00 KiB/s
Receiving objects:  29% (221754/754806), 103.53 MiB | 507.00 KiB/s
Receiving objects:  29% (224846/754806), 104.12 MiB | 529.00 KiB/s
Receiving objects:  30% (226442/754806), 104.46 MiB | 551.00 KiB/s
Receiving objects:  30% (228432/754806), 104.75 MiB | 561.00 KiB/s
Receiving objects:  30% (230547/754806), 105.26 MiB | 560.00 KiB/s
Receiving objects:  30% (232704/754806), 105.69 MiB | 532.00 KiB/s
Receiving objects:  31% (233990/754806), 105.92 MiB | 520.00 KiB/s
Receiving objects:  31% (235001/754806), 106.14 MiB | 505.00 KiB/s
Receiving objects:  31% (237054/754806), 106.32 MiB | 479.00 KiB/s
Receiving objects:  31% (237679/754806), 106.72 MiB | 427.00 KiB/s
Receiving objects:  31% (239202/754806), 107.25 MiB | 434.00 KiB/s
Receiving objects:  31% (239536/754806), 107.95 MiB | 491.00 KiB/s
Receiving objects:  31% (239549/754806), 108.50 MiB | 515.00 KiB/s
Receiving objects:  31% (239562/754806), 109.07 MiB | 559.00 KiB/s
Receiving objects:  31% (239576/754806), 109.62 MiB | 592.00 KiB/s
Receiving objects:  31% (239588/754806), 110.15 MiB | 564.00 KiB/s
Receiving objects:  31% (239604/754806), 110.74 MiB | 555.00 KiB/s
Receiving objects:  31% (240181/754806), 111.25 MiB | 546.00 KiB/s
Receiving objects:  31% (240899/754806), 111.88 MiB | 556.00 KiB/s
Receiving objects:  32% (241538/754806), 112.18 MiB | 565.00 KiB/s
Receiving objects:  32% (244760/754806), 112.55 MiB | 583.00 KiB/s
Receiving objects:  32% (248460/754806), 113.23 MiB | 608.00 KiB/s
Receiving objects:  33% (249086/754806), 113.23 MiB | 608.00 KiB/s
Receiving objects:  33% (251908/754806), 113.77 MiB | 608.00 KiB/s
Receiving objects:  33% (252684/754806), 114.37 MiB | 620.00 KiB/s
Receiving objects:  33% (255523/754806), 114.64 MiB | 602.00 KiB/s
Receiving objects:  34% (256635/754806), 114.92 MiB | 593.00 KiB/s
Receiving objects:  34% (258670/754806), 115.29 MiB | 596.00 KiB/s
Receiving objects:  34% (261363/754806), 115.89 MiB | 583.00 KiB/s
Receiving objects:  34% (264066/754806), 116.34 MiB | 566.00 KiB/s
Receiving objects:  35% (264183/754806), 116.34 MiB | 566.00 KiB/s
Receiving objects:  35% (266412/754806), 116.86 MiB | 550.00 KiB/s
Receiving objects:  35% (267778/754806), 117.29 MiB | 526.00 KiB/s
Receiving objects:  35% (270291/754806), 117.72 MiB | 462.00 KiB/s
Receiving objects:  36% (271731/754806), 118.02 MiB | 472.00 KiB/s
Receiving objects:  36% (274511/754806), 118.32 MiB | 495.00 KiB/s
Receiving objects:  36% (275432/754806), 118.93 MiB | 514.00 KiB/s
Receiving objects:  36% (276567/754806), 119.57 MiB | 547.00 KiB/s
Receiving objects:  36% (277664/754806), 120.24 MiB | 602.00 KiB/s
Receiving objects:  36% (278833/754806), 120.90 MiB | 634.00 KiB/s
Receiving objects:  36% (278930/754806), 121.55 MiB | 634.00 KiB/s
Receiving objects:  37% (279279/754806), 121.82 MiB | 632.00 KiB/s
Receiving objects:  37% (279558/754806), 122.08 MiB | 619.00 KiB/s
Receiving objects:  37% (279954/754806), 122.34 MiB | 602.00 KiB/s
Receiving objects:  37% (280633/754806), 122.89 MiB | 583.00 KiB/s
Receiving objects:  37% (281339/754806), 123.32 MiB | 527.00 KiB/s
Receiving objects:  37% (284103/754806), 123.86 MiB | 508.00 KiB/s
Receiving objects:  38% (286827/754806), 124.51 MiB | 537.00 KiB/s
Receiving objects:  38% (288429/754806), 124.51 MiB | 537.00 KiB/s
Receiving objects:  39% (294375/754806), 125.17 MiB | 573.00 KiB/s
Receiving objects:  39% (294481/754806), 125.17 MiB | 573.00 KiB/s
Receiving objects:  39% (300307/754806), 125.89 MiB | 620.00 KiB/s
Receiving objects:  40% (301923/754806), 126.29 MiB | 662.00 KiB/s
Receiving objects:  40% (304139/754806), 126.64 MiB | 682.00 KiB/s
Receiving objects:  40% (304577/754806), 127.32 MiB | 699.00 KiB/s
Receiving objects:  40% (306387/754806), 128.24 MiB | 752.00 KiB/s
Receiving objects:  40% (306431/754806), 129.25 MiB | 820.00 KiB/s
Receiving objects:  41% (309471/754806), 130.66 MiB | 967.00 KiB/s
Receiving objects:  41% (310668/754806), 130.66 MiB | 967.00 KiB/s
Receiving objects:  41% (315503/754806), 132.42 MiB | 1.18 MiB/s
Receiving objects:  41% (316205/754806), 133.31 MiB | 1.20 MiB/s
Receiving objects:  42% (317019/754806), 133.31 MiB | 1.20 MiB/s
Receiving objects:  42% (320495/754806), 134.04 MiB | 1.14 MiB/s
Receiving objects:  42% (320513/754806), 134.57 MiB | 1.01 MiB/s
Receiving objects:  42% (320539/754806), 135.13 MiB | 789.00 KiB/s
Receiving objects:  42% (320583/754806), 135.71 MiB | 616.00 KiB/s
Receiving objects:  42% (320866/754806), 136.04 MiB | 602.00 KiB/s
Receiving objects:  42% (322771/754806), 136.62 MiB | 570.00 KiB/s
Receiving objects:  42% (323033/754806), 136.98 MiB | 531.00 KiB/s
Receiving objects:  43% (324567/754806), 137.32 MiB | 486.00 KiB/s
Receiving objects:  43% (324589/754806), 137.32 MiB | 486.00 KiB/s
Receiving objects:  43% (326849/754806), 137.81 MiB | 464.00 KiB/s
Receiving objects:  43% (329568/754806), 138.39 MiB | 450.00 KiB/s
Receiving objects:  43% (330305/754806), 138.98 MiB | 473.00 KiB/s
Receiving objects:  43% (330956/754806), 139.51 MiB | 532.00 KiB/s
Receiving objects:  43% (331554/754806), 140.11 MiB | 572.00 KiB/s
Receiving objects:  44% (332115/754806), 140.75 MiB | 591.00 KiB/s
Receiving objects:  44% (332228/754806), 140.75 MiB | 591.00 KiB/s
Receiving objects:  44% (332506/754806), 141.46 MiB | 618.00 KiB/s
Receiving objects:  44% (333161/754806), 142.22 MiB | 655.00 KiB/s
Receiving objects:  44% (333827/754806), 142.93 MiB | 693.00 KiB/s
Receiving objects:  44% (334706/754806), 143.66 MiB | 725.00 KiB/s
Receiving objects:  44% (336555/754806), 144.50 MiB | 758.00 KiB/s
Receiving objects:  45% (339663/754806), 144.93 MiB | 772.00 KiB/s
Receiving objects:  45% (340607/754806), 145.34 MiB | 789.00 KiB/s
Receiving objects:  45% (343870/754806), 145.96 MiB | 750.00 KiB/s
Receiving objects:  46% (347211/754806), 146.28 MiB | 741.00 KiB/s
Receiving objects:  46% (347879/754806), 146.58 MiB | 728.00 KiB/s
Receiving objects:  46% (351711/754806), 146.92 MiB | 717.00 KiB/s
Receiving objects:  46% (353340/754806), 147.58 MiB | 676.00 KiB/s
Receiving objects:  46% (354201/754806), 148.10 MiB | 583.00 KiB/s
Receiving objects:  47% (354759/754806), 148.43 MiB | 583.00 KiB/s
Receiving objects:  47% (357394/754806), 148.89 MiB | 620.00 KiB/s
Receiving objects:  47% (358879/754806), 149.71 MiB | 667.00 KiB/s
Receiving objects:  47% (361054/754806), 150.49 MiB | 702.00 KiB/s
Receiving objects:  48% (362307/754806), 150.93 MiB | 719.00 KiB/s
Receiving objects:  48% (362855/754806), 151.29 MiB | 729.00 KiB/s
Receiving objects:  48% (363771/754806), 151.90 MiB | 776.00 KiB/s
Receiving objects:  48% (364804/754806), 152.46 MiB | 704.00 KiB/s
Receiving objects:  48% (365649/754806), 153.08 MiB | 664.00 KiB/s
Receiving objects:  48% (366448/754806), 153.81 MiB | 641.00 KiB/s
Receiving objects:  48% (366955/754806), 154.40 MiB | 625.00 KiB/s
Receiving objects:  48% (367310/754806), 154.92 MiB | 611.00 KiB/s
Receiving objects:  48% (367899/754806), 155.13 MiB | 588.00 KiB/s
Receiving objects:  48% (368734/754806), 155.59 MiB | 548.00 KiB/s
Receiving objects:  48% (369025/754806), 156.16 MiB | 513.00 KiB/s
Receiving objects:  48% (369680/754806), 156.80 MiB | 523.00 KiB/s
Receiving objects:  49% (369855/754806), 157.17 MiB | 537.00 KiB/s
Receiving objects:  49% (370589/754806), 157.58 MiB | 578.00 KiB/s
Receiving objects:  49% (371218/754806), 158.34 MiB | 656.00 KiB/s
Receiving objects:  49% (371373/754806), 158.93 MiB | 666.00 KiB/s
Receiving objects:  49% (371422/754806), 159.55 MiB | 680.00 KiB/s
Receiving objects:  49% (371540/754806), 160.23 MiB | 679.00 KiB/s
Receiving objects:  49% (372039/754806), 160.97 MiB | 667.00 KiB/s
Receiving objects:  49% (372084/754806), 161.71 MiB | 675.00 KiB/s
Receiving objects:  49% (372514/754806), 162.41 MiB | 701.00 KiB/s
Receiving objects:  49% (372879/754806), 163.10 MiB | 709.00 KiB/s
Receiving objects:  49% (373341/754806), 163.85 MiB | 721.00 KiB/s
Receiving objects:  49% (373688/754806), 164.73 MiB | 752.00 KiB/s
Receiving objects:  49% (374167/754806), 165.73 MiB | 821.00 KiB/s
Receiving objects:  49% (374190/754806), 166.14 MiB | 827.00 KiB/s
Receiving objects:  49% (374577/754806), 167.16 MiB | 821.00 KiB/s
Receiving objects:  49% (374889/754806), 167.52 MiB | 814.00 KiB/s
Receiving objects:  49% (375552/754806), 168.19 MiB | 769.00 KiB/s
Receiving objects:  49% (376164/754806), 168.71 MiB | 656.00 KiB/s
Receiving objects:  49% (376895/754806), 169.28 MiB | 614.00 KiB/s
Receiving objects:  50% (377403/754806), 169.57 MiB | 606.00 KiB/s
Receiving objects:  50% (378020/754806), 170.24 MiB | 602.00 KiB/s
Receiving objects:  50% (378020/754806), 171.08 MiB | 640.00 KiB/s
Receiving objects:  50% (380216/754806), 171.51 MiB | 679.00 KiB/s
Receiving objects:  50% (383364/754806), 172.20 MiB | 710.00 KiB/s
Receiving objects:  51% (384952/754806), 172.55 MiB | 728.00 KiB/s
Receiving objects:  51% (385952/754806), 172.89 MiB | 736.00 KiB/s
Receiving objects:  51% (390665/754806), 173.38 MiB | 701.00 KiB/s
Receiving objects:  52% (392500/754806), 173.68 MiB | 676.00 KiB/s
Receiving objects:  52% (394274/754806), 174.00 MiB | 647.00 KiB/s
Receiving objects:  52% (397994/754806), 174.69 MiB | 621.00 KiB/s
Receiving objects:  52% (399234/754806), 175.31 MiB | 613.00 KiB/s
Receiving objects:  52% (399421/754806), 175.88 MiB | 611.00 KiB/s
Receiving objects:  53% (400048/754806), 175.88 MiB | 611.00 KiB/s
Receiving objects:  53% (402147/754806), 176.39 MiB | 597.00 KiB/s
Receiving objects:  53% (402679/754806), 176.80 MiB | 537.00 KiB/s
Receiving objects:  53% (403052/754806), 177.32 MiB | 510.00 KiB/s
Receiving objects:  53% (404920/754806), 177.63 MiB | 510.00 KiB/s
Receiving objects:  53% (405568/754806), 178.27 MiB | 526.00 KiB/s
Receiving objects:  53% (406033/754806), 178.89 MiB | 545.00 KiB/s
Receiving objects:  53% (407129/754806), 179.48 MiB | 582.00 KiB/s
Receiving objects:  54% (407596/754806), 179.48 MiB | 582.00 KiB/s
Receiving objects:  54% (408925/754806), 180.02 MiB | 587.00 KiB/s
Receiving objects:  54% (409001/754806), 180.61 MiB | 582.00 KiB/s
Receiving objects:  54% (409344/754806), 181.19 MiB | 569.00 KiB/s
Receiving objects:  54% (409885/754806), 181.77 MiB | 566.00 KiB/s
Receiving objects:  54% (410834/754806), 182.32 MiB | 562.00 KiB/s
Receiving objects:  54% (413247/754806), 182.93 MiB | 575.00 KiB/s
Receiving objects:  54% (414146/754806), 183.54 MiB | 582.00 KiB/s
Receiving objects:  54% (414194/754806), 184.24 MiB | 609.00 KiB/s
Receiving objects:  54% (414507/754806), 184.95 MiB | 636.00 KiB/s
Receiving objects:  54% (414530/754806), 185.31 MiB | 653.00 KiB/s
Receiving objects:  54% (414551/754806), 186.06 MiB | 685.00 KiB/s
Receiving objects:  54% (414575/754806), 186.84 MiB | 722.00 KiB/s
Receiving objects:  54% (414596/754806), 187.54 MiB | 721.00 KiB/s
Receiving objects:  54% (414617/754806), 188.14 MiB | 701.00 KiB/s
Receiving objects:  54% (414640/754806), 188.79 MiB | 677.00 KiB/s
Receiving objects:  54% (414671/754806), 189.64 MiB | 706.00 KiB/s
Receiving objects:  54% (414705/754806), 190.54 MiB | 739.00 KiB/s
Receiving objects:  54% (414750/754806), 191.58 MiB | 832.00 KiB/s
Receiving objects:  54% (415079/754806), 192.76 MiB | 954.00 KiB/s
Receiving objects:  55% (415144/754806), 192.76 MiB | 954.00 KiB/s
---
Receiving objects:  55% (419249/754806), 203.95 MiB | 995.00 KiB/s
Receiving objects:  55% (419287/754806), 204.93 MiB | 939.00 KiB/s
Receiving objects:  55% (419379/754806), 205.73 MiB | 873.00 KiB/s
Receiving objects:  56% (422692/754806), 206.14 MiB | 872.00 KiB/s
Receiving objects:  56% (424694/754806), 206.62 MiB | 886.00 KiB/s
Receiving objects:  56% (424909/754806), 207.52 MiB | 892.00 KiB/s
Receiving objects:  56% (425578/754806), 208.38 MiB | 870.00 KiB/s
Receiving objects:  56% (425860/754806), 209.34 MiB | 881.00 KiB/s
Receiving objects:  56% (426743/754806), 210.37 MiB | 926.00 KiB/s
Receiving objects:  56% (428356/754806), 211.18 MiB | 906.00 KiB/s
Receiving objects:  57% (430240/754806), 211.54 MiB | 885.00 KiB/s
Receiving objects:  57% (431576/754806), 211.91 MiB | 867.00 KiB/s
Receiving objects:  57% (433591/754806), 212.50 MiB | 806.00 KiB/s
Receiving objects:  57% (436861/754806), 213.04 MiB | 700.00 KiB/s
Receiving objects:  58% (437788/754806), 213.32 MiB | 650.00 KiB/s
Receiving objects:  58% (438918/754806), 213.63 MiB | 625.00 KiB/s
Receiving objects:  58% (441067/754806), 214.24 MiB | 591.00 KiB/s
Receiving objects:  58% (442376/754806), 214.76 MiB | 559.00 KiB/s
Receiving objects:  58% (444637/754806), 215.00 MiB | 547.00 KiB/s
Receiving objects:  59% (445336/754806), 215.26 MiB | 549.00 KiB/s
Receiving objects:  59% (446199/754806), 215.54 MiB | 553.00 KiB/s
Receiving objects:  59% (447857/754806), 216.22 MiB | 572.00 KiB/s
Receiving objects:  59% (450340/754806), 217.04 MiB | 621.00 KiB/s
Receiving objects:  59% (452697/754806), 217.73 MiB | 657.00 KiB/s
Receiving objects:  60% (452884/754806), 217.73 MiB | 657.00 KiB/s
Receiving objects:  60% (455361/754806), 218.40 MiB | 696.00 KiB/s
Receiving objects:  60% (457709/754806), 219.18 MiB | 735.00 KiB/s
Receiving objects:  60% (459362/754806), 219.75 MiB | 684.00 KiB/s
Receiving objects:  61% (460432/754806), 220.03 MiB | 653.00 KiB/s
Receiving objects:  61% (460885/754806), 220.24 MiB | 618.00 KiB/s
Receiving objects:  61% (462475/754806), 220.71 MiB | 571.00 KiB/s
Receiving objects:  61% (462718/754806), 221.29 MiB | 541.00 KiB/s
Receiving objects:  61% (463042/754806), 221.91 MiB | 540.00 KiB/s
Receiving objects:  61% (463060/754806), 222.63 MiB | 570.00 KiB/s
Receiving objects:  61% (463080/754806), 223.35 MiB | 629.00 KiB/s
Receiving objects:  61% (463101/754806), 223.76 MiB | 665.00 KiB/s
Receiving objects:  61% (463122/754806), 224.52 MiB | 708.00 KiB/s
Receiving objects:  61% (463139/754806), 225.11 MiB | 699.00 KiB/s
Receiving objects:  61% (463164/754806), 225.69 MiB | 669.00 KiB/s
Receiving objects:  61% (463194/754806), 226.34 MiB | 654.00 KiB/s
Receiving objects:  61% (466154/754806), 227.11 MiB | 662.00 KiB/s
Receiving objects:  62% (467980/754806), 227.55 MiB | 675.00 KiB/s
Receiving objects:  62% (470229/754806), 228.06 MiB | 720.00 KiB/s
Receiving objects:  62% (472269/754806), 229.04 MiB | 815.00 KiB/s
Receiving objects:  62% (473948/754806), 229.68 MiB | 811.00 KiB/s
Receiving objects:  63% (475528/754806), 230.00 MiB | 815.00 KiB/s
Receiving objects:  63% (477544/754806), 230.39 MiB | 820.00 KiB/s
Receiving objects:  63% (481229/754806), 231.01 MiB | 765.00 KiB/s
Receiving objects:  64% (483076/754806), 231.31 MiB | 720.00 KiB/s
Receiving objects:  64% (484665/754806), 231.60 MiB | 664.00 KiB/s
Receiving objects:  64% (484983/754806), 232.32 MiB | 653.00 KiB/s
Receiving objects:  64% (488144/754806), 233.16 MiB | 697.00 KiB/s
Receiving objects:  64% (490574/754806), 233.93 MiB | 713.00 KiB/s
Receiving objects:  65% (490624/754806), 233.93 MiB | 713.00 KiB/s
Receiving objects:  65% (491013/754806), 234.96 MiB | 811.00 KiB/s
---
Receiving objects:  66% (503124/754806), 240.94 MiB | 883.00 KiB/s
Receiving objects:  67% (505721/754806), 241.33 MiB | 842.00 KiB/s
Receiving objects:  67% (506739/754806), 241.69 MiB | 809.00 KiB/s
Receiving objects:  67% (508129/754806), 242.31 MiB | 688.00 KiB/s
Receiving objects:  67% (510289/754806), 242.88 MiB | 617.00 KiB/s
Receiving objects:  67% (511702/754806), 243.49 MiB | 621.00 KiB/s
Receiving objects:  67% (512044/754806), 244.08 MiB | 608.00 KiB/s
Receiving objects:  67% (513005/754806), 244.59 MiB | 565.00 KiB/s
Receiving objects:  68% (513269/754806), 244.59 MiB | 565.00 KiB/s
Receiving objects:  68% (513859/754806), 245.07 MiB | 549.00 KiB/s
Receiving objects:  68% (515514/754806), 245.62 MiB | 545.00 KiB/s
Receiving objects:  68% (515983/754806), 246.20 MiB | 533.00 KiB/s
Receiving objects:  68% (516437/754806), 246.72 MiB | 532.00 KiB/s
Receiving objects:  68% (516893/754806), 247.29 MiB | 536.00 KiB/s
Receiving objects:  68% (516971/754806), 248.01 MiB | 588.00 KiB/s
Receiving objects:  68% (517307/754806), 248.33 MiB | 597.00 KiB/s
Receiving objects:  68% (517388/754806), 249.07 MiB | 633.00 KiB/s
Receiving objects:  68% (518013/754806), 249.89 MiB | 696.00 KiB/s
Receiving objects:  68% (518580/754806), 250.72 MiB | 754.00 KiB/s
Receiving objects:  68% (519137/754806), 251.40 MiB | 746.00 KiB/s
Receiving objects:  68% (519152/754806), 251.82 MiB | 699.00 KiB/s
Receiving objects:  68% (519171/754806), 252.25 MiB | 613.00 KiB/s
Receiving objects:  68% (519201/754806), 252.80 MiB | 545.00 KiB/s
Receiving objects:  68% (519243/754806), 253.39 MiB | 498.00 KiB/s
Receiving objects:  68% (519751/754806), 253.83 MiB | 491.00 KiB/s
Receiving objects:  68% (520120/754806), 254.26 MiB | 496.00 KiB/s
Receiving objects:  69% (520817/754806), 254.53 MiB | 501.00 KiB/s
Receiving objects:  69% (520894/754806), 254.83 MiB | 510.00 KiB/s
Receiving objects:  69% (521188/754806), 255.34 MiB | 486.00 KiB/s
Receiving objects:  69% (521219/754806), 256.00 MiB | 523.00 KiB/s
Receiving objects:  69% (521275/754806), 256.70 MiB | 581.00 KiB/s
Receiving objects:  69% (524165/754806), 256.97 MiB | 591.00 KiB/s
Receiving objects:  69% (524497/754806), 257.66 MiB | 616.00 KiB/s
Receiving objects:  69% (525023/754806), 258.41 MiB | 673.00 KiB/s
Receiving objects:  69% (525177/754806), 259.25 MiB | 719.00 KiB/s
Receiving objects:  69% (525258/754806), 260.04 MiB | 736.00 KiB/s
Receiving objects:  69% (525284/754806), 260.68 MiB | 745.00 KiB/s
Receiving objects:  69% (525321/754806), 261.49 MiB | 762.00 KiB/s
Receiving objects:  69% (525815/754806), 262.28 MiB | 761.00 KiB/s
Receiving objects:  69% (526677/754806), 263.07 MiB | 755.00 KiB/s
Receiving objects:  69% (527707/754806), 263.77 MiB | 764.00 KiB/s
Receiving objects:  70% (528365/754806), 264.05 MiB | 741.00 KiB/s
Receiving objects:  70% (528551/754806), 264.29 MiB | 707.00 KiB/s
Receiving objects:  70% (529860/754806), 264.82 MiB | 660.00 KiB/s
Receiving objects:  70% (530556/754806), 265.52 MiB | 627.00 KiB/s
Receiving objects:  70% (532215/754806), 266.21 MiB | 621.00 KiB/s
Receiving objects:  70% (534764/754806), 267.02 MiB | 668.00 KiB/s
Receiving objects:  70% (535365/754806), 267.76 MiB | 726.00 KiB/s
Receiving objects:  71% (535913/754806), 268.40 MiB | 716.00 KiB/s
Receiving objects:  71% (535922/754806), 268.40 MiB | 716.00 KiB/s
Receiving objects:  71% (536547/754806), 268.99 MiB | 699.00 KiB/s
Receiving objects:  71% (537690/754806), 269.29 MiB | 680.00 KiB/s
Receiving objects:  71% (538483/754806), 269.93 MiB | 645.00 KiB/s
Receiving objects:  71% (538515/754806), 270.46 MiB | 602.00 KiB/s
Receiving objects:  71% (539750/754806), 271.16 MiB | 615.00 KiB/s
Receiving objects:  71% (541982/754806), 271.85 MiB | 640.00 KiB/s
Receiving objects:  72% (543461/754806), 272.19 MiB | 649.00 KiB/s
Receiving objects:  72% (544515/754806), 272.57 MiB | 667.00 KiB/s
Receiving objects:  72% (545239/754806), 273.27 MiB | 620.00 KiB/s
Receiving objects:  72% (545767/754806), 273.47 MiB | 579.00 KiB/s
Receiving objects:  72% (545917/754806), 273.94 MiB | 535.00 KiB/s
Receiving objects:  72% (546669/754806), 274.46 MiB | 503.00 KiB/s
Receiving objects:  72% (547472/754806), 275.07 MiB | 477.00 KiB/s
Receiving objects:  72% (547682/754806), 275.73 MiB | 545.00 KiB/s
Receiving objects:  72% (549810/754806), 276.39 MiB | 596.00 KiB/s
Receiving objects:  73% (551009/754806), 276.72 MiB | 616.00 KiB/s
Receiving objects:  73% (552256/754806), 276.96 MiB | 612.00 KiB/s
Receiving objects:  73% (553767/754806), 277.46 MiB | 596.00 KiB/s
Receiving objects:  73% (554432/754806), 277.92 MiB | 557.00 KiB/s
Receiving objects:  73% (556009/754806), 278.28 MiB | 486.00 KiB/s
Receiving objects:  73% (556615/754806), 278.65 MiB | 427.00 KiB/s
Receiving objects:  73% (556646/754806), 279.14 MiB | 430.00 KiB/s
Receiving objects:  73% (557559/754806), 279.43 MiB | 436.00 KiB/s
Receiving objects:  74% (558557/754806), 279.71 MiB | 444.00 KiB/s
Receiving objects:  74% (560433/754806), 280.06 MiB | 471.00 KiB/s
Receiving objects:  74% (562155/754806), 280.73 MiB | 543.00 KiB/s
Receiving objects:  74% (563386/754806), 281.50 MiB | 634.00 KiB/s
Receiving objects:  74% (563768/754806), 282.22 MiB | 686.00 KiB/s
Receiving objects:  74% (564252/754806), 282.65 MiB | 644.00 KiB/s
Receiving objects:  74% (565203/754806), 283.02 MiB | 577.00 KiB/s
Receiving objects:  75% (566105/754806), 283.02 MiB | 577.00 KiB/s
Receiving objects:  75% (567750/754806), 283.50 MiB | 517.00 KiB/s
Receiving objects:  75% (568551/754806), 284.00 MiB | 456.00 KiB/s
Receiving objects:  75% (569523/754806), 284.60 MiB | 478.00 KiB/s
Receiving objects:  75% (571381/754806), 285.29 MiB | 544.00 KiB/s
Receiving objects:  75% (573048/754806), 285.93 MiB | 592.00 KiB/s
Receiving objects:  76% (573653/754806), 285.93 MiB | 592.00 KiB/s
Receiving objects:  76% (574445/754806), 286.66 MiB | 644.00 KiB/s
Receiving objects:  76% (575394/754806), 287.14 MiB | 636.00 KiB/s
Receiving objects:  76% (576937/754806), 287.61 MiB | 586.00 KiB/s
Receiving objects:  76% (578126/754806), 287.82 MiB | 558.00 KiB/s
Receiving objects:  76% (579014/754806), 288.20 MiB | 500.00 KiB/s
Receiving objects:  76% (580240/754806), 288.66 MiB | 443.00 KiB/s
Receiving objects:  77% (581201/754806), 288.90 MiB | 453.00 KiB/s
Receiving objects:  77% (583028/754806), 289.18 MiB | 449.00 KiB/s
Receiving objects:  77% (585075/754806), 289.81 MiB | 488.00 KiB/s
Receiving objects:  77% (587873/754806), 290.57 MiB | 568.00 KiB/s
Receiving objects:  78% (588749/754806), 290.91 MiB | 598.00 KiB/s
Receiving objects:  78% (591594/754806), 291.34 MiB | 642.00 KiB/s
Receiving objects:  78% (593418/754806), 292.15 MiB | 715.00 KiB/s
Receiving objects:  78% (594866/754806), 292.72 MiB | 713.00 KiB/s
Receiving objects:  79% (596297/754806), 293.22 MiB | 672.00 KiB/s
Receiving objects:  79% (596507/754806), 293.22 MiB | 672.00 KiB/s
Receiving objects:  79% (597276/754806), 293.80 MiB | 638.00 KiB/s
Receiving objects:  79% (599148/754806), 294.48 MiB | 608.00 KiB/s
Receiving objects:  79% (599673/754806), 295.33 MiB | 570.00 KiB/s
Receiving objects:  79% (599673/754806), 295.79 MiB | 560.00 KiB/s
Receiving objects:  79% (599673/754806), 296.09 MiB | 564.00 KiB/s
Receiving objects:  79% (599673/754806), 296.75 MiB | 573.00 KiB/s
Receiving objects:  79% (601814/754806), 297.07 MiB | 565.00 KiB/s
Receiving objects:  80% (603845/754806), 297.43 MiB | 572.00 KiB/s
Receiving objects:  80% (605446/754806), 297.82 MiB | 594.00 KiB/s
Receiving objects:  80% (606751/754806), 298.64 MiB | 680.00 KiB/s
Receiving objects:  80% (609229/754806), 299.42 MiB | 732.00 KiB/s
Receiving objects:  81% (611393/754806), 300.21 MiB | 765.00 KiB/s
Receiving objects:  81% (611492/754806), 300.21 MiB | 765.00 KiB/s
Receiving objects:  81% (614981/754806), 300.98 MiB | 782.00 KiB/s
Receiving objects:  81% (618109/754806), 301.70 MiB | 761.00 KiB/s
Receiving objects:  82% (618941/754806), 301.70 MiB | 761.00 KiB/s
Receiving objects:  82% (620205/754806), 302.29 MiB | 720.00 KiB/s
Receiving objects:  82% (623066/754806), 302.86 MiB | 670.00 KiB/s
Receiving objects:  82% (626218/754806), 303.46 MiB | 633.00 KiB/s
Receiving objects:  83% (626489/754806), 303.46 MiB | 633.00 KiB/s
Receiving objects:  83% (627502/754806), 304.08 MiB | 594.00 KiB/s
Receiving objects:  83% (628171/754806), 304.63 MiB | 573.00 KiB/s
Receiving objects:  83% (629742/754806), 304.91 MiB | 568.00 KiB/s
Receiving objects:  83% (632142/754806), 305.48 MiB | 567.00 KiB/s
Receiving objects:  83% (632927/754806), 305.94 MiB | 540.00 KiB/s
Receiving objects:  83% (633709/754806), 306.55 MiB | 485.00 KiB/s
Receiving objects:  83% (633709/754806), 307.10 MiB | 483.00 KiB/s
Receiving objects:  83% (633709/754806), 307.82 MiB | 521.00 KiB/s
Receiving objects:  83% (633709/754806), 308.51 MiB | 569.00 KiB/s
Receiving objects:  83% (633710/754806), 308.79 MiB | 586.00 KiB/s
Receiving objects:  84% (634038/754806), 309.11 MiB | 616.00 KiB/s
Receiving objects:  84% (635269/754806), 309.46 MiB | 640.00 KiB/s
Receiving objects:  84% (636398/754806), 310.01 MiB | 643.00 KiB/s
Receiving objects:  84% (638162/754806), 310.63 MiB | 616.00 KiB/s
Receiving objects:  84% (639449/754806), 311.21 MiB | 594.00 KiB/s
Receiving objects:  84% (641133/754806), 311.81 MiB | 598.00 KiB/s
Receiving objects:  85% (641586/754806), 311.81 MiB | 598.00 KiB/s
Receiving objects:  85% (643422/754806), 312.48 MiB | 618.00 KiB/s
Receiving objects:  85% (646403/754806), 313.11 MiB | 625.00 KiB/s
Receiving objects:  85% (648540/754806), 313.74 MiB | 623.00 KiB/s
Receiving objects:  86% (649134/754806), 313.74 MiB | 623.00 KiB/s
Receiving objects:  86% (650376/754806), 314.32 MiB | 628.00 KiB/s
Receiving objects:  86% (652248/754806), 315.00 MiB | 626.00 KiB/s
Receiving objects:  86% (653122/754806), 315.50 MiB | 602.00 KiB/s
Receiving objects:  86% (655098/754806), 315.75 MiB | 586.00 KiB/s
Receiving objects:  87% (656682/754806), 316.01 MiB | 572.00 KiB/s
Receiving objects:  87% (658174/754806), 316.26 MiB | 559.00 KiB/s
Receiving objects:  87% (661293/754806), 316.68 MiB | 523.00 KiB/s
Receiving objects:  87% (663102/754806), 317.16 MiB | 477.00 KiB/s
Receiving objects:  87% (664215/754806), 317.68 MiB | 480.00 KiB/s
Receiving objects:  88% (664230/754806), 317.68 MiB | 480.00 KiB/s
Receiving objects:  88% (665799/754806), 318.28 MiB | 501.00 KiB/s
Receiving objects:  88% (668428/754806), 318.95 MiB | 544.00 KiB/s
Receiving objects:  88% (669846/754806), 319.72 MiB | 626.00 KiB/s
Receiving objects:  88% (671748/754806), 320.60 MiB | 706.00 KiB/s
Receiving objects:  89% (671778/754806), 320.60 MiB | 706.00 KiB/s
Receiving objects:  89% (676327/754806), 321.55 MiB | 797.00 KiB/s
Receiving objects:  89% (678880/754806), 322.42 MiB | 853.00 KiB/s
Receiving objects:  90% (679326/754806), 322.42 MiB | 853.00 KiB/s
Receiving objects:  90% (680315/754806), 323.04 MiB | 823.00 KiB/s
Receiving objects:  90% (683015/754806), 323.61 MiB | 773.00 KiB/s
Receiving objects:  90% (684512/754806), 324.30 MiB | 717.00 KiB/s
Receiving objects:  90% (685039/754806), 324.95 MiB | 646.00 KiB/s
Receiving objects:  91% (686874/754806), 325.16 MiB | 608.00 KiB/s
Receiving objects:  91% (687497/754806), 325.41 MiB | 590.00 KiB/s
Receiving objects:  91% (690553/754806), 325.82 MiB | 550.00 KiB/s
Receiving objects:  91% (692377/754806), 326.18 MiB | 491.00 KiB/s
Receiving objects:  92% (694422/754806), 326.36 MiB | 452.00 KiB/s
Receiving objects:  92% (694619/754806), 326.36 MiB | 452.00 KiB/s
Receiving objects:  92% (697195/754806), 326.81 MiB | 411.00 KiB/s
Receiving objects:  92% (697609/754806), 327.34 MiB | 422.00 KiB/s
Receiving objects:  92% (699272/754806), 327.91 MiB | 457.00 KiB/s
Receiving objects:  93% (701970/754806), 328.54 MiB | 514.00 KiB/s
Receiving objects:  93% (702172/754806), 328.54 MiB | 514.00 KiB/s
Receiving objects:  93% (704801/754806), 329.13 MiB | 555.00 KiB/s
Receiving objects:  93% (706354/754806), 329.71 MiB | 582.00 KiB/s
Receiving objects:  93% (706532/754806), 330.26 MiB | 574.00 KiB/s
Receiving objects:  93% (706800/754806), 330.67 MiB | 533.00 KiB/s
Receiving objects:  93% (708151/754806), 331.10 MiB | 497.00 KiB/s
Receiving objects:  94% (709518/754806), 331.30 MiB | 477.00 KiB/s
Receiving objects:  94% (709537/754806), 331.54 MiB | 466.00 KiB/s
Receiving objects:  94% (711328/754806), 332.12 MiB | 465.00 KiB/s
Receiving objects:  94% (712562/754806), 332.43 MiB | 438.00 KiB/s
Receiving objects:  94% (715658/754806), 332.83 MiB | 429.00 KiB/s
Receiving objects:  95% (717066/754806), 333.06 MiB | 435.00 KiB/s
Receiving objects:  95% (717163/754806), 333.06 MiB | 435.00 KiB/s
Receiving objects:  95% (719529/754806), 333.63 MiB | 464.00 KiB/s
Receiving objects:  95% (720411/754806), 334.41 MiB | 510.00 KiB/s
Receiving objects:  95% (722516/754806), 335.03 MiB | 577.00 KiB/s
Receiving objects:  96% (724614/754806), 335.62 MiB | 622.00 KiB/s
Receiving objects:  96% (726488/754806), 335.62 MiB | 622.00 KiB/s
Receiving objects:  96% (728850/754806), 336.39 MiB | 680.00 KiB/s
Receiving objects:  97% (732162/754806), 337.31 MiB | 729.00 KiB/s
Receiving objects:  97% (732529/754806), 337.31 MiB | 729.00 KiB/s
Receiving objects:  97% (734993/754806), 337.99 MiB | 714.00 KiB/s
Receiving objects:  97% (735978/754806), 338.61 MiB | 714.00 KiB/s
Receiving objects:  97% (739188/754806), 339.24 MiB | 711.00 KiB/s
Receiving objects:  98% (739710/754806), 339.24 MiB | 711.00 KiB/s
Receiving objects:  98% (742285/754806), 339.83 MiB | 654.00 KiB/s
Receiving objects:  98% (743710/754806), 340.61 MiB | 645.00 KiB/s
Receiving objects:  99% (747258/754806), 340.99 MiB | 660.00 KiB/s
Receiving objects:  99% (749964/754806), 341.40 MiB | 684.00 KiB/s
remote: Total 754806 (delta 612597), reused 747860 (delta 605717), pack-reused 0
Receiving objects: 100% (754806/754806), 341.86 MiB | 718.00 KiB/s
Receiving objects: 100% (754806/754806), 341.92 MiB | 650.00 KiB/s, done.
---
Resolving deltas: 100% (612597/612597), completed with 4871 local objects.
---
[00:00:45] configure: rust.quiet-tests     := True
---
[00:04:27] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1595: trailing whitespace
[00:04:27] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1611: line longer than 100 chars
[00:04:29] some tidy checks failed
[00:04:29]
[00:04:29]
[00:04:29] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:29] expected success, got: exit code: 1
[00:04:29]
[00:04:29]
[00:04:29] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:29] Build completed unsuccessfully in 0:01:46
[00:04:29] Makefile:79: recipe for target 'tidy' failed
[00:04:29] make: *** [tidy] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1161758b:start=1523025984429622464,finish=1523025984436870562,duration=7248098
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:005e7bd1
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:005e7bd1:start=1523025984443428430,finish=1523025984450086700,duration=6658270
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0c25b9c4
$ dmesg | grep -i kill
[   11.240728] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363151182). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612610/612610), completed with 4869 local objects.
---
[00:00:39] configure: rust.quiet-tests     := True
---
[00:44:32] ..........................................................................i.........................
[00:44:38] .................i..................................................................................
---
[00:45:14] ..............................................................................................i.....
[00:45:22] .......................................F.............................i..............................
[00:45:28] ....................................................................................................
[00:45:35] ....................................................................................................
[00:45:43] ....................................................................................................
`&`-reference `fancy_ref` [E0594]"
---
[00:45:44]         msg: "E0594"
---
[00:45:44] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:45:44] expected success, got: exit code: 101
[00:45:44]
[00:45:44]
[00:45:44] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:45:44] Build completed unsuccessfully in 0:02:29
[00:45:44] Makefile:58: recipe for target 'check' failed
[00:45:44] make: *** [check] Error 1
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by gaurikholkar** [comment]
@estebank @nikomatsakis repoened the issue

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363409449). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612665/612665), completed with 4869 local objects.
---
[00:00:52] configure: rust.quiet-tests     := True
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by gaurikholkar** [comment]
Not sure why tidy checks are failing. Couldn't find any trailing whitespace.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363428887). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612667/612667), completed with 4869 local objects.
---
[00:01:04] configure: rust.quiet-tests     := True
---
[00:04:35] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1578: trailing whitespace
[00:04:35] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1582: trailing whitespace
[00:04:35] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1644: trailing whitespace
[00:04:36] some tidy checks failed
[00:04:36]
[00:04:36]
[00:04:36] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:36] expected success, got: exit code: 1
[00:04:36]
[00:04:36]
[00:04:36] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:36] Build completed unsuccessfully in 0:01:54
[00:04:36] Makefile:79: recipe for target 'tidy' failed
[00:04:36] make: *** [tidy] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:159c8622:start=1523087670093303512,finish=1523087670099866766,duration=6563254
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:28befa78
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:28befa78:start=1523087670105669571,finish=1523087670112459931,duration=6790360
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:05e4a96c
$ dmesg | grep -i kill
[   10.173691] init: failsafe main process (1094) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

File: src/librustc_mir/borrow_check/mod.rs [hunk 15]
```diff
@@ -1552,21 +1579,55 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
...
+                            match *base {
+                                Place::Local(local) => {
+                                    let locations = self.mir.find_assignments(local);
+                                        if locations.len() > 0 {
+                                            let item_msg = if error_reported {
+                                                self.get_secondary_err_msg(base)
+                                            } else {
+                                                self.get_default_err_msg(place)
+                                            };
+
```
Comment (kennytm) [inline src/librustc_mir/borrow_check/mod.rs]: A line consisting of only spaces is also considered "trailing whitespaces".

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363442001). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613151/613151), completed with 4866 local objects.
---
[00:00:50] configure: rust.quiet-tests     := True
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363818315). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612769/612769), completed with 4866 local objects.
---
[00:00:42] configure: rust.quiet-tests     := True
---
[00:05:01] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1578: trailing whitespace
[00:05:01] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1582: trailing whitespace
[00:05:01] tidy error: /checkout/src/librustc_mir/borrow_check/mod.rs:1641: trailing whitespace
[00:05:02] some tidy checks failed
[00:05:02]
[00:05:02]
[00:05:02] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:05:02] expected success, got: exit code: 1
[00:05:02]
[00:05:02]
[00:05:02] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:05:02] Build completed unsuccessfully in 0:02:00
[00:05:02] Makefile:79: recipe for target 'tidy' failed
[00:05:02] make: *** [tidy] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: canno
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

File: src/librustc_mir/borrow_check/mod.rs (hunk 15 above)
Comment (gaurikholkar) [reply src/librustc_mir/borrow_check/mod.rs]: @kennytm can you help out with the fixes for the tidy errors? I've tried certain things but they don't seem to work. One of the errors is also in the previously written code.

Comment (kennytm) [reply src/librustc_mir/borrow_check/mod.rs]: @gaurikholkar The line numbers seems wrong. You could run `tidy` locally by

```
./x.py test src/tools/tidy
```

The lines with trailing whitespaces are:

```
tidy error: src/librustc_mir/borrow_check/mod.rs:1532: trailing whitespace
tidy error: src/librustc_mir/borrow_check/mod.rs:1536: trailing whitespace
tidy error: src/librustc_mir/borrow_check/mod.rs:1595: trailing whitespace
```

Comment (gaurikholkar) [reply src/librustc_mir/borrow_check/mod.rs]: Thanks you @kennytm . Yeah the line nos were wrong. My local tidy script panics -> [logs](https://gist.github.com/gaurikholkar/186eb92e2f3057ee4228e9931d7a1ca6)

Comment (kennytm) [reply src/librustc_mir/borrow_check/mod.rs]: @gaurikholkar you should just remove the entire `binaryen` folder, it is no longer used.

**Comment by nikomatsakis** [comment]
This is looking pretty good to me! Let's land it. We can always tinker more.

@bors r+

Nice job @gaurikholkar

**Review by nikomatsakis — APPROVED** [review]

File: src/test/ui/nll/issue-47388.stderr [hunk 16]
```diff
@@ -0,0 +1,11 @@
+error[E0594]: cannot assign to data in a `&` reference
+  --> $DIR/issue-47388.rs:18:5
+   |
+LL |     let fancy_ref = &(&mut fancy);
+   |                     ------------- help: consider changing this to be a mutable reference: `&mut`
```
Comment (estebank) [inline src/test/ui/nll/issue-47388.stderr]: I believe either the span or the suggestion text might be incorrect. It should either suggest `&mut (&mut fancy)` for this span, or use a span only selecting the `&`.

**Review by estebank — CHANGES_REQUESTED** [review]

**Comment by pietroalbini** [comment]
@estebank I guess now we need another PR for that...

File: src/test/ui/nll/issue-47388.stderr (hunk 16 above)
Comment (estebank) [reply src/test/ui/nll/issue-47388.stderr]: Filed #49859
