### PR TITLE
Correct generic parameter ordering in error note for E0747

### LINKED ISSUE #72815: Incorrect generic parameter ordering for E0747
https://github.com/rust-lang/rust/blob/a59264b01247836c70e24217e0d346b868387525/src/test/ui/suggestions/suggest-move-types.stderr#L121-L135
suggests type parameters should come before lifetime parameters, which is incorrect.
The message is emitted here:
https://github.com/rust-lang/rust/blob/a59264b01247836c70e24217e0d346b868387525/src/librustc_typeck/astconv.rs#L463-L477

This issue has been assigned to @camelid via [this comment](https://github.com/rust-lang/rust/issues/72815#issuecomment-636506152).

### PR DESCRIPTION
**Pull request by camelid**
Fixes #72815.

r? @varkor

### CODE REVIEW

File: src/librustc_typeck/astconv.rs [hunk 1]
```diff
@@ -483,8 +484,23 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
             arg.descr(),
             kind,
         );
+
+        let kind_ord = match kind {
+            "lifetime" => ParamKindOrd::Lifetime,
+            "type" => ParamKindOrd::Type,
+            "constant" => ParamKindOrd::Const,
+            _ => panic!(),
```
Comment (camelid) [inline src/librustc_typeck/astconv.rs:492]: Is the right way to trigger an ICE?

Comment (Aaron1011) [reply src/librustc_typeck/astconv.rs:492]: I believe that `bug!` is the preferred way to trigger an ICE.

In this case, I would recommend changing `opt_span_bug_fmt` to take the original `GenericParamDefKind`, rather than its string description. That will allow you to write an exhaustive match, removing the need for an explicit `panic!`/`bug!`

Comment (camelid) [reply src/librustc_typeck/astconv.rs:492]: Thanks for the tip! I'm new to contributing to rustc, so could you describe the change you're recommending in more detail?

Comment (Aaron1011) [reply src/librustc_typeck/astconv.rs:492]: On closer examination, it turns out that the two callers of this function actually have two different "original" types: `GenericParamDefKind` and `GenericArg`.

I believe your change is actually perfectly correct.

Comment (varkor) [inline src/librustc_typeck/astconv.rs:492]:
```suggestion
            // It's more concise to match on the string representation, though it means
            // the match is non-exhaustive.
            _ => bug!("invalid generic parameter kind"),
```

**Review by varkor — APPROVED** [review]
Thanks @camelid, this looks good! Just one tweak: we use `bug!` instead of `panic!` in the compiler, and it's helpful to give it at least a little message in case it is ever triggered. r=me after that change.

File: src/librustc_typeck/astconv.rs (hunk 1 above)
Comment (varkor) [reply src/librustc_typeck/astconv.rs:492]: I went through the same thought process @Aaron1011. It would be a little cleaner to pass `ParamKindOrd` directly, but I'm not sure it's worth making more changes.

Comment (varkor) [reply src/librustc_typeck/astconv.rs]: It would be easy to change in this pull request if desired, but I'm not sure it's worth doing: it adds quite a bit of boilerplate code, and it's only used in this one case. If we ever find ourselves doing something similar again in the future, we should revisit it.

**Comment by varkor** [comment]
@bors r+ rollup

Thanks for the pull request, @camelid!

**Comment by camelid** [comment]
Thanks for reviewing it! :)

File: src/librustc_typeck/astconv.rs [hunk 2]
```diff
@@ -483,8 +484,25 @@ impl<'o, 'tcx> dyn AstConv<'tcx> + 'o {
...
             kind,
         );
+
+        let kind_ord = match kind {
+            "lifetime" => ParamKindOrd::Lifetime,
+            "type" => ParamKindOrd::Type,
+            "constant" => ParamKindOrd::Const,
+            // It's more concise to match on the string representation, though it means
+            // the match is non-exhaustive.
+            _ => bug!("invalid generic parameter kind"),
```
Comment (ayazhafiz) [inline src/librustc_typeck/astconv.rs:494]: nit: consider including the invalid kind here?
```suggestion
            _ => bug!("invalid generic parameter kind {}", kind),
```

**Comment by camelid** [comment]
@varkor could you re-approve this? Thanks!
