### PR TITLE
Validate built-in attribute placement

### LINKED ISSUE #47725: #[link_name] is ignored on extern blocks
```rust
fn main() {
    println!("{}", unsafe { foo() });
}

#[link_name = "foobar"]
extern "C" {
    fn foo() -> u32;
}
```

This fails to link with ``undefined reference to `foo'``, but it didn't even try to find any `foobar` library.

With `#[link(name = "foobar")]`, the error is the expected `ld: cannot find -lfoobar`.

There are a few places in `libstd` using `#[link_name = "m"] extern {...}`, so I wonder if those actually have any effect either.

### LINKED ISSUE #54044: Cold Structs
```rust
#[cold]
struct DonnerParty;

fn main() {
    #[cold] 5;
}
```
Is it intentional that this work? If so, what is it supposed to do? [The reference](https://doc.rust-lang.org/reference/attributes.html#function-only-attributes) lists it as a function-only attribute, but I've always known it to work on expressions like loops as well.

### LINKED ISSUE #54584: #[target_feature(enable = "avx2")] can be applied to non-functions, but doesn't do anything
[Playground link demonstrating the problem](https://play.rust-lang.org/?gist=3be94bfbac4854bd5bfa98638d4e6bb6&version=stable&mode=release&edition=2015)

[Playground link when it works](https://play.rust-lang.org/?gist=f54e9bd36a36075b2e0fdd7387b70ecf&version=stable&mode=release&edition=2015)

The compiler should tell me that the annotation will not do anything (in the first case)

### PR DESCRIPTION
**Pull request by calebzulawski**
Closes #54584, closes #47725, closes #54044.

I've changed silently ignoring some incorrectly placed attributes to errors.  I'm not sure what the policy is since this can theoretically break code (should they be warnings instead? does it warrant a crater run?).

### CODE REVIEW

File: src/librustc_passes/check_attr.rs [hunk 1]
```diff
@@ -213,6 +223,99 @@ impl CheckAttrVisitor<'tcx> {
         }
     }
 
+    /// Checks if `#[cold]` is applied to a non-function. Returns `true` if valid.
+    fn check_cold(&self, attr: &Attribute, span: &Span, target: Target) -> bool {
+        match target {
+            Target::Fn | Target::Method(..) | Target::ForeignFn => true,
+            _ => {
```
Comment (lzutao) [inline src/librustc_passes/check_attr.rs:230]: Does `#[cold]` work for expressions or statements?

Comment (calebzulawski) [reply src/librustc_passes/check_attr.rs:230]: [The reference says no.](https://doc.rust-lang.org/reference/attributes/codegen.html#the-cold-attribute)

I think the equivalent for expressions is [`std::intrinsics::unlikely`](https://doc.rust-lang.org/std/intrinsics/fn.unlikely.html).

File: src/librustc_typeck/collect.rs [hunk 2]
```diff
@@ -2430,7 +2430,7 @@ fn codegen_fn_attrs(tcx: TyCtxt<'_>, id: DefId) -> CodegenFnAttrs {
         } else if attr.check_name(sym::thread_local) {
             codegen_fn_attrs.flags |= CodegenFnAttrFlags::THREAD_LOCAL;
         } else if attr.check_name(sym::track_caller) {
-            if tcx.is_closure(id) || tcx.fn_sig(id).abi() != abi::Abi::Rust {
+            if !tcx.is_closure(id) && tcx.fn_sig(id).abi() != abi::Abi::Rust {
```
Comment (matthewjasper) [inline src/librustc_typeck/collect.rs:2433]: Could these have comments stating that we error when using target feature on a closure in `check_attr`?

**Comment by matthewjasper** [comment]
I think changes like this in the past have sometimes needed to be warnings because existing code has attributes in incorrect places.
@bors try for a crate run

**Comment by matthewjasper** [comment]
@craterbot check

File: src/librustc_passes/check_attr.rs (hunk 1 above)
Comment (ehuss) [reply src/librustc_passes/check_attr.rs:230]: I wouldn't use the reference as a source (speaking as the author of that content).

I'm pretty sure this is wrong for closures (although that needs `#![feature(stmt_expr_attributes)]`), and maybe some of these other checks.  

The codegen attributes are particularly hard to determine where they apply because you have to follow how they are interpreted inside llvm. 

Also, I think historically, adding checks for proper attribute locations uses the `unused_attributes` lint, due to the backwards compatibility hazard.

Comment (calebzulawski) [reply src/librustc_passes/check_attr.rs:230]: Good point with closures--I think you're right.

Regarding backwards compatibility, I've seen a few different opinions while reading through the various issues.  I don't have a strong opinion but some of the arguments I've seen:
* Use `unused_attributes` for backwards compatibility
* Hard error is consistent with `repr`, `inline`, `target_feature`
* Hard error to avoid footguns like `#[link_name = "foo"] extern {}`
* Hard error to avoid ICEs such as #64768

Looking at what was done with `inline`, the lint was used to avoid breaking the bitflags crate: https://github.com/rust-lang/rust/pull/65294#issuecomment-545418714

I'm curious to see how many crates, if any, are broken by this change but I have no problem changing to a lint if that's necessary.

**Comment by pietroalbini** [comment]
@craterbot abort

**Comment by pietroalbini** [comment]
@craterbot check

**Comment by pietroalbini** [comment]
@craterbot abourt

**Comment by pietroalbini** [comment]
Woops.

@craterbot abort

**Comment by pietroalbini** [comment]
@craterbot check

**Comment by matthewjasper** [comment]
I can see `link_name`, `target_feature` and `cold` being used in incorrect places. I think those should be warnings for now.

**Comment by pietroalbini** [comment]
Just deployed a Crater change to improve the usefulness of the report, let's try it.

@craterbot reply-report

**Comment by pietroalbini** [comment]
@craterbot retry-report

**Comment by calebzulawski** [comment]
@pietroalbini much more useful!

After reviewing the report I have a few questions:

- I expected to see `#[link_name]` applied to extern modules, hence the suggestion to use `#[link(name = "...")]`, but I see it applied to types, for example in [py03](https://github.com/PyO3/pyo3/blob/master/src/ffi/methodobject.rs#L18-L28).  Does this do anything?
- There are lots of uses of `#[cold]` on expressions, does this trigger the llvm unlikely intrinsic? (and if not, maybe suggest using `std::intrinsics::unlikely` on nightly)

**Comment by matthewjasper** [comment]
`#[link_name]` does nothing on type aliases. `#[cold]` only applies to functions/closures.

File: src/librustc_typeck/collect.rs (hunk 2 above)
Comment (bjorn3) [reply src/librustc_typeck/collect.rs:2433]: Could this be `tcx.fn_sig(id).abi() != abi::Abi::Rust && tcx.fn_sig(id).abi() != abi::Abi::RustCall` instead? That would allow `#[track_caller]` on explicit `extern "rust-call" fn`.

Comment (calebzulawski) [reply src/librustc_typeck/collect.rs:2433]: Does `#[track_caller]` work with the `rust-call` ABI?  I feel like that change isn't in the scope of this PR

File: src/test/ui/feature-gate/issue-43106-gating-of-builtin-attrs.rs [hunk 3]
```diff
@@ -88,12 +93,18 @@
 #![crate_name = "0900"]
 #![crate_type = "bin"] // cannot pass "0800" here
 
-#![crate_id = "10"] //~ WARN use of deprecated attribute
+#![crate_id = "10"]
+//~^ WARN use of deprecated attribute
```
Comment (calebzulawski) [inline src/test/ui/feature-gate/issue-43106-gating-of-builtin-attrs.rs:97]: I'm not sure what I changed that resulted in these popping up (but I think these changes seem correct?)

**Review by matthewjasper — APPROVED** [review]
r=me with conflicts resolved

**Comment by lzutao** [comment]
Triage: @calebzulawski could you resolve the merge conflict?

File: src/librustc_passes/check_attr.rs [hunk 4]
```diff
@@ -201,10 +213,31 @@ impl CheckAttrVisitor<'tcx> {
...
             | Target::Method(MethodKind::Trait { body: true } | MethodKind::Inherent) => true,
+            // FIXME: #[target_feature] was previously erroneously allowed on statements and some
+            // crates used this, so only emit a warning.
+            Target::Statement => {
+                self.tcx.struct_span_lint_hir(UNUSED_ATTRIBUTES, hir_id, attr.span, |lint| {
+                    lint.build("attribute should be applied to a function")
+                        .warn(
+                            "this was previously accepted by the compiler but is \
+                               being phased out; it will become a hard error in \
+                               a future release!",
```
Comment (lzutao) [inline src/librustc_passes/check_attr.rs:234]:
```suggestion
                            "this was previously accepted by the compiler but is \
                             being phased out; it will become a hard error in \
                             a future release!",
```

Comment (lzutao) [reply src/librustc_passes/check_attr.rs:234]: this and other places

**Comment by lzutao** [comment]
Also this PR should be labelled with T-relnotes because this will effect old non-validated codes.

File: src/test/ui/check-static-recursion-foreign.rs [hunk 5]
```diff
@@ -15,7 +15,7 @@ extern crate libc;
 
 use libc::c_int;
 
-#[link_name = "check_static_recursion_foreign_helper"]
+#[link(name = "check_static_recursion_foreign_helper")]
```
Comment (lzutao) [inline src/test/ui/check-static-recursion-foreign.rs:18]: test break here: https://github.com/rust-lang-ci/rust/runs/984640615#step:23:28391

Comment (calebzulawski) [reply src/test/ui/check-static-recursion-foreign.rs:18]: Not sure what's going on here, this definitely should be `#[link]` and not `#[link_name]`.  Maybe it's specific to musl (I'm not too familiar with it)?

Comment (lzutao) [reply src/test/ui/check-static-recursion-foreign.rs:18]: not sure who to ping about musl: cc @petrochenkov @mati865

Comment (mati865) [reply src/test/ui/check-static-recursion-foreign.rs:18]: It's not musl specific, this should fail on (at least some of) other builders as well.
Sorry but I don't have time to investigate it.

Comment (calebzulawski) [reply src/test/ui/check-static-recursion-foreign.rs:18]: I'm still a little confused what to do with this.  I agree that removing the attribute entirely is likely fine, but it's unclear to me if this satisfies the intent of the original issue (#18164, I think)

File: src/test/ui/check-static-recursion-foreign.rs [hunk 6]
```diff
@@ -15,7 +15,7 @@ extern crate libc;
...
 extern "C" {
     #[allow(dead_code)]
```
[the remark this answers is not in the document]
Comment (calebzulawski) [reply src/test/ui/check-static-recursion-foreign.rs:20]: Is it ignored even in an `extern "Rust"` block?

[the remark this answers is not in the document]
Comment (ollie27) [reply src/test/ui/check-static-recursion-foreign.rs:20]: > Is it ignored even in an `extern "Rust"` block?

Yeah. `#[no_mangle]` is just a convenient version of `#[export_name]` so can be used in exactly the same places.

File: src/test/ui/check-static-recursion-foreign.rs [hunk 7]
```diff
@@ -15,7 +15,7 @@ extern crate libc;
 
 use libc::c_int;
 
-#[link_name = "check_static_recursion_foreign_helper"]
+#[link(name = "check_static_recursion_foreign_helper")]
 extern "C" {
```
[the remark this answers is not in the document]
Comment (ollie27) [reply src/test/ui/check-static-recursion-foreign.rs:19]: Changing to `extern "Rust"` won't do anything either as ABI has no effect on statics.

File: src/test/ui/check-static-recursion-foreign.rs (hunk 5 above)
Comment (ollie27) [reply src/test/ui/check-static-recursion-foreign.rs:18]: It looks like this test was checking for an ICE which would occur before linking and `#[link]` only affects linking so it should be safe to remove this line.

File: src/test/ui/check-static-recursion-foreign.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (calebzulawski) [reply src/test/ui/check-static-recursion-foreign.rs]: I've added checking for `#[no_mangle]`.

File: src/test/ui/issues/issue-2214.rs [hunk 8]
```diff
@@ -23,7 +23,7 @@ fn lgamma(n: c_double, value: &mut isize) -> c_double {
 mod m {
     use libc::{c_double, c_int};
 
-    #[link_name = "m"]
+    #[link(name = "m")]
```
Comment (lzutao) [inline src/test/ui/issues/issue-2214.rs:26]: fail to link to libm on msvc x86: https://github.com/rust-lang-ci/rust/runs/1083564279#step:23:17053

Comment (calebzulawski) [reply src/test/ui/issues/issue-2214.rs:26]: Anyone know why?  Should it be looking for a dll instead?

Comment (ehuss) [reply src/test/ui/issues/issue-2214.rs:26]: I'm pretty sure msvc does not have libm (it is part of the universal C runtime). I think this attribute can be removed.  I think on all platforms the `lgamma` function is available through one way or another (primarily via the `libc` crate I believe, which handles linking `-lm` as appropriate). Considering this test has been working with a bogus attribute, I think it should be fine to remove.

**Comment by ehuss** [comment]
@bors retry
network error
```
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/strsim/0.7.0/download`, got 502
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/strsim/0.7.0/download`, got 502
error: failed to download from `https://crates.io/api/v1/crates/strsim/0.7.0/download`

Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/strsim/0.7.0/download`, got 502
thread 'main' panicked at 'tests failed for https://github.com/XAMPPRocky/tokei', src/tools/cargotest/main.rs:72:9
```
