### PR TITLE
Fix detection of main function if there are expressions around it

### LINKED ISSUE #139651: Doc test containing code before main function fails to compile on beta
I tried this code:

```rust
//! ```
//! # std::fs::write("foo.txt", "Hello, world!").unwrap();
//! fn main() {
//!   println!("{}", std::fs::read_to_string("foo.txt").unwrap())
//! }
//! ```
```

With Rust 1.86.0, running `cargo test` compiles and runs the doctest successfully.

On the beta channel, the doctest fails to compile:

```
running 1 test
test src/lib.rs - (line 1) ... FAILED

failures:

---- src/lib.rs - (line 1) stdout ----
error: expected one of `!` or `::`, found `(`
 --> src/lib.rs:2:15
  |
2 | std::fs::write("foo.txt", "Hello, world!").unwrap();
  |               ^ expected one of `!` or `::`

error: aborting due to 1 previous error

Couldn't compile the test.

failures:
    src/lib.rs - (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

### Meta

`rustc +beta --version --verbose`:
```
rustc 1.87.0-beta.3 (a22ecb51f 2025-04-07)
binary: rustc
commit-hash: a22ecb51f85284abc5b18a32b27696b0e3e9cf85
commit-date: 2025-04-07
host: x86_64-pc-windows-msvc
release: 1.87.0-beta.3
LLVM version: 20.1.1
```

### LINKED ISSUE #140162: Regression on doc-tests with statements and a main function
### Code

I tried this code:

```rust
/// ```
/// # if cfg!(miri) { return; }
/// use playground::my_func;
///
/// fn main() {
///     println!("Hi!");
///     my_func();
/// }
/// ```
pub fn my_func() {
}
```

On stable, running this doctest succeeds. On beta, it triggers this error:
```text
running 1 test
test src/lib.rs - my_func (line 2) ... FAILED

failures:

---- src/lib.rs - my_func (line 2) stdout ----
error: expected item, found keyword `if`
 --> src/lib.rs:4:1
  |
4 | if cfg!(miri) { return; }
  | ^^ expected item
  |
  = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>

error: aborting due to 1 previous error

Couldn't compile the test.

failures:
    src/lib.rs - my_func (line 2)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

### Version it worked on

It most recently worked on: Latest stable (i.e. rustc 1.86.0)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.87.0-beta.5 (386abeb93 2025-04-19)
binary: rustc
commit-hash: 386abeb93ab8e683357f54ffe76ae53861b2d984
commit-date: 2025-04-19
host: x86_64-unknown-linux-gnu
release: 1.87.0-beta.5
LLVM version: 20.1.1
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #140162.
Fixes #139651.

Once this is merged, we can backport and I'll send a follow-up to emit a warning in case a `main` function is about to be "wrapped" (and therefore not run).

r? @fmease

try-job: x86_64-mingw-1

### CODE REVIEW

**Comment by fmease** [comment]
I'll review tonight!

File: src/librustdoc/doctest/make.rs [hunk 1]
```diff
@@ -407,15 +407,19 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
...
-                        reset_error_count(&psess);
-                        return Err(());
+                    StmtKind::Expr(ref expr) => {
+                        if matches!(expr.kind, ast::ExprKind::Err(_)) {
+                            reset_error_count(&psess);
+                            return Err(());
+                        }
+                        has_non_module_items = true;
                     }
                     StmtKind::MacCall(ref mac_call) if !info.has_main_fn => {
```
Comment (jyn514) [inline src/librustdoc/doctest/make.rs:424]: i think you need to also assume that macros can expand to expressions, not just items.

Comment (GuillaumeGomez) [reply src/librustdoc/doctest/make.rs:424]: I voluntarily ignored it for the simple fact that trying to match on a macro call is pretty much useless since we have no clue how it will be expanded. The fact that we match on `fn main` is already a pretty bad idea. If I start saying "everything that doesn't match the first condition means it's an expression", then this code would fail to compile:

```
include!("auxiliary/empty.rs");
fn main() {}
```

Because `"auxiliary/empty.rs"` would be considered an expression, meaning the whole code would be wrapped, and the compiler would be unhappy:

```
error: non-statement macro in statement position: include
  |
3 | include!("auxiliary/empty.rs");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So sadly, I think the best course of action here is to keep this ugly hack...

**Review by fmease — APPROVED** [review]
r=me with nits addressed. sorry for the broken promise and the delay

**Comment by GuillaumeGomez** [comment]
> r=me with nits addressed. sorry for the broken promise and the delay

No worries, you're supposed to be in vacation. If I had known, I wouldn't have set you as reviewer. But in any case, thanks a lot! Gonna update then r+.

File: src/librustdoc/doctest/make.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest/make.rs:424]: Sure!

Comment (GuillaumeGomez) [reply src/librustdoc/doctest/make.rs:424]: Here it is: https://github.com/rust-lang/rust/issues/140310

File: src/librustdoc/doctest/make.rs [hunk 2]
```diff
@@ -462,6 +470,11 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
                     push_to_s(&mut info.crates, source, span, &mut prev_span_hi);
                 }
             }
+            if has_non_module_items {
+                // FIXME: if `info.has_main_fn` is `true`, emit a warning here to mention that
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/doctest/make.rs:474]: Here it is: https://github.com/rust-lang/rust/issues/140310

File: src/librustdoc/doctest/make.rs [hunk 3]
```diff
@@ -437,7 +441,11 @@ fn parse_source(source: &str, crate_name: &Option<&str>) -> Result<ParseSourceIn
                             }
                         }
                     }
-                    _ => {}
+                    // We do nothing in this case. Not marking it as `non_module_items` either.
+                    StmtKind::Empty => {}
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/doctest/make.rs:445]: Wait, ignore my previous comment, it's not allowed to have a rogue semi-colon in code like that. I'll change it then.

**Comment by GuillaumeGomez** [comment]
Oh damn, that was a nasty bug. Glad we caught it. Sending the fix. :)

**Comment by GuillaumeGomez** [comment]
So explanation: it was a bad change where `MacCall` were only checked when there was no `main` function, meaning that we were entering the last arm which was considering it as an item. I added a regression test with this check.

Let's run the try job to ensure I didn't miss anything.

@bors try

**Comment by tgross35** [comment]
This seems like the most likely cause of https://github.com/rust-lang/rust/pull/140356#issuecomment-2833270138

@bors r-

**Comment by tgross35** [comment]
Huh, spurious then?

@bors r=fmease rollup=maybe

**Comment by fmease** [comment]
> maybe we should have cratered this

Not really, no. We employ crater if we *intentionally* change a behavior whereas the negative fallout you're seeing (the failed `cargotest` test and now issue #140412) is due to *unintentional* behavior changes.

As the reviewer I gladly take the blame here. The former issue I completely missed, that's totally on me. It's great that the `cargotest` smoke test caught it.

Regarding the latter (#140412), I have to note that I didn't get the chance to re-review the PR after the latest push (I only skimmed the comments). However, that's still my fault since I should've blocked the PR on a proper re-review given the delicate nature of the doctest impl.

**Comment by matthiaskrgr** [comment]
:thinking: 
what I mean is, we already knew we are likely to cause negative fallout because it slipped through the cracks once, so why not make sure there is nothing more we missed?

**Comment by fmease** [comment]
Beta backport accepted as per [#t-rustdoc > beta-nominated: #140220 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/beta-nominated.3A.20.23140220/near/514387433)
