### PR TITLE
Disable combining LLD with external llvm-config

### LINKED ISSUE #139477: FTBFS tarball rust 1.86.0: generated a symlink in a tarball: rust-lld
### Summary

The bug is not reproducible on 1.85.1.
Built from a tarball: curl -O https://static.rust-lang.org/dist/rustc-1.86.0-src.tar.gz

[00:04:41] Copy/Link "/usr/bin/lld" to "/usr/src/RPM/BUILD/rust-1.86.0/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld"
[00:22:07] thread 'main' panicked at src/bootstrap/src/utils/tarball.rs:397:21:
[00:22:07] generated a symlink in a tarball: /usr/src/RPM/BUILD/rust-1.86.0/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/rustc-1.86.0-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld

### Command used

All commands used are listed in the build log. 

### Bootstrap configuration (bootstrap.toml)

I didn't create it.

### Operating system

ALT Linux Sisyphus.

### HEAD

Built from a tarball.

### Additional context

I am building an RPM package, I am the maintainer of the rust package in ALT Linux.

### PR DESCRIPTION
**Pull request by Kobzol**
When an external `llvm-config` is used, we don't really know anything about the external LLD, as we don't build it ourselves. Therefore, we probably shouldn't allow using `rust-lld` nor copy it to the target sysroot.

Fixes: https://github.com/rust-lang/rust/issues/139477

CC @cuviper

r? @onur-ozkan

try-job: dist-x86_64-linux
try-job: dist-aarch64-linux

### CODE REVIEW

File: src/bootstrap/src/core/config/config.rs [hunk 1]
```diff
@@ -2397,6 +2397,15 @@ impl Config {
             );
         }
 
+        let has_external_llvm_config = !config.llvm_from_ci
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/config/config.rs:2400]: Nit: We could move `Builder::is_system_llvm` to `Config` since it doesn't rely on any `Builder` specific data (other than `is_builder_target` function which can also be moved).

**Review by onur-ozkan — APPROVED** [review]
r=me with/without the nit once CI is green

**Comment by Kobzol** [comment]
Hmm, it failed in post-opt tests. This might be a bit annoying, because this is not external LLVM, but a "local" LLVM, and here we do in fact want to use LLD. I think that we should just print a warning instead of panicking when LLD is configured, and just avoid putting it into the sysroot in that case. @onur-ozkan WDYT?
