### PR TITLE
ty: projections in `transparent_newtype_field`

### LINKED ISSUE #73249: ICE: could not fully normalize
ICE in packed-simd on rustc-perf, caused by ec42485ee95e3843a65b47533f6bcbcf06d9564e. I suspect https://github.com/rust-lang/rust/pull/72897 but am not sure. cc @lcnr 

Would be good to minimize so we can add a test case.

```

    Checking packed_simd v0.3.0 (/tmp/.tmpmCakLH)
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:37: could not fully normalize `<A as sealed::SimdArray>::Tuple`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (ec42485ee 2020-06-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `packed_simd`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #73249.

This PR modifies `transparent_newtype_field` so that it handles
projections with generic parameters, where `normalize_erasing_regions`
would ICE.

### CODE REVIEW

**Comment by lcnr** [comment]
I don't think this is the best approach here.
Afaict the following still causes an ICE here:
```rust
pub trait Foo {
    type Assoc: 'static;
}

impl Foo for () {
    type Assoc = u32;
}

extern "C" {
    pub fn lint_me(x: Bar<()>);
}

#[repr(transparent)]
pub struct Bar<T: Foo> {
    value: &'static <T as Foo>::Assoc,
}
```

Afaik extern functions must be fully monomorphic (ignoring lifetimes), in which case you should probably have relevant substs here.

**Comment by davidtwco** [comment]
> I don't think this is the best approach here.

I've pushed a commit that makes the case you highlighted work - well spotted. 

I added the function being modified here in #72890. It deliberately does not apply substitutions so that it can identify the field in a transparent struct which is a non-ZST. If the non-zero-sized field were a generic parameter, and if it were substituted for `()` and we didn't do this then the previous logic would consider all fields zero-sized and lint incorrectly for that reason. Using this function, we can identify which field is normally non-zero-sized, and handle that case correctly.

Given that, I think that having this function is the appropriate approach and it being unable to handle this case is just an oversight. If you have a better approach, then I'm open to making changes though.

**Comment by lcnr** [comment]
Your current approach still seems somewhat unfortunate to me, I think this warns on:
```rust
use std::marker::PhantomData;

trait Foo {
    type Assoc;
}

impl Foo for () {
    type Assoc = PhantomData<()>;
}

#[repr(transparent)]
struct Wow<T> where T: Foo<Assoc = PhantomData<T>> {
    x: <T as Foo>::Assoc,
    v: u32,
}

extern "C" {
    fn test(v: Wow<()>);
}
```

> It deliberately does not apply substitutions so that it can identify the field in a transparent struct which is a non-ZST. If the non-zero-sized field were a generic parameter, and if it were substituted for () and we didn't do this then the previous logic would find that all fields were zero-sized and lint incorrectly for that reason.

I can't quite follow your here, do you explicitly not want to lint for
```rust
#[repr(transparent)]
struct Foo<T> {
    inner: T,
}

extern "C" {
    fn foo(v: Foo<()>);
}
```

If I understand this correctly, structs with `#[repr(transparent)]` must have exactly 0 or 1 non zero sized fields. Would it work to add `FfiResult::FfiZst` and delay emitting errors on ZST fields of transparent structs similar to what is already done with `FfiPhantom`.

**Comment by davidtwco** [comment]
> Your current approach still seems somewhat unfortunate to me, I think this warns on:

It does - I've pushed a commit that fixes this and simplifies `transparent_newtype_field` further.

> I can't quite follow you here, do you explicitly not want to lint for

This case does lint and it should.

The previous behavior for transparent types was to skip any that were zero-sized. Consider the second example from your comment, with struct `Foo`, and the old logic:

- In argument position, this type's fields would all be skipped and the type would be considered "composed only of `PhantomData`" - that's not entirely correct, but the lint would trigger, so we're good.
- In return position, this type is equivalent to `()` - which shouldn't lint, because that's just a function which doesn't return anything - that was the subject of #66202. However, a lint would be produced, as the type is still considered "composed only of `PhantomData`".

With the new behavior for transparent types, where the non-ZST field is identified and only that field is checked, we would correctly determine that the `()` is FFI-unsafe; but that result can then be threaded up to the logic that says "ignore that FFI-unsafe result if this is the return type and it was a `()`". 

In the previous behaviour, the `FfiPhantom` that we had contained the whole type (not just the field's type) and so we couldn't handle that return-type case easily. 

There are certainly other ways I could have solved this - I don't think that identifying the non-ZST field is the only way, but it's quite explicit about what we're checking and I prefer that; I am open to better approaches, but I don't think using a `FfiZst` would necessarily handle that case (it could be made to, in the same way as the `FfiPhantom` approach taken previously to transparent types could have but I don't think that would be better necessarily).

---

I've pushed some other commits too:

- I noticed that the old logic had actually been duplicated for enum variants and unions, so I've unified these under some functions.
- When looking into #73251, I found some cases (some of which required this patch to not ICE) where opaque types in struct fields (via `type_alias_impl_trait`) weren't being linted before normalization (there are explicit pre-normalization checks for opaque types in the signature, but not inside of types - which seemed incorrect based on #60855).
  - I'd like to unify this logic with `check_for_opaque_type` but it requires the changes I'm working on for #73251.

File: src/librustc_lint/types.rs [hunk 1]
```diff
@@ -597,6 +597,66 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
+        use FfiResult::*;
+
+        if def.repr.transparent() {
+            // Can assume that only one field is not a ZST, so only check
+            // that field's type for FFI-safety.
+            if let Some(field) = variant.transparent_newtype_field(self.cx.tcx) {
+                self.check_field_type_for_ffi(cache, field, substs)
+            } else {
+                FfiSafe
+            }
```
Comment (lcnr) [inline src/librustc_lint/types.rs:634]: afaict this can only be hit if the type is malformed, while I don't think a delay span bug would be appropriate here,
it might be a good idea to add a comment mentioning this here

**Review by lcnr — APPROVED** [review]
LGTM, the new  `transparent_newtype_field` now also looks good :+1:

File: src/librustc_lint/types.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc_lint/types.rs:634]: Fixed, thanks!

**Comment by davidtwco** [comment]
Pushed a minor commit re-wording to re-trigger CI as the last failure was spurious.

**Comment by lcnr** [comment]
An actual ci failure this time :sweat_smile: @davidtwco, seems like you have to bless the ui tests again. The output of the following test has changed:
```
failures:
    [ui] ui/lint/lint-ctypes-73249-2.rs
    [ui] ui/lint/lint-ctypes-73249-3.rs
    [ui] ui/lint/lint-ctypes-73249-5.rs
```

**Comment by davidtwco** [comment]
Updated the PR with blessed output after a rebase.

**Review by lcnr — APPROVED** [review]

**Comment by Manishearth** [comment]
wh...what the hell? @pietroalbini this had yielded to the rollup, but it still merged

is yield implemented properly?

**Comment by Manishearth** [comment]
I think this is how those "test timed out" locks happen, because bors will continue testing the rollup and then realize it can't merge it

**Comment by pietroalbini** [comment]
> wh...what the hell? @pietroalbini this had yielded to the rollup, but it still merged
> 
> is yield implemented properly?

@Manishearth "yield" does not exist in the bors code, is just a comment saying why the PR was retried. The yield usually works because when the retry happens bors starts testing the PR with higher priority, and cancelbot kills the previous build since a new commit was pushed to `auto`.
