### PR TITLE
Prevent `__rust_begin_short_backtrace` frames from being tail-call optimised away

### LINKED ISSUE #47429: Short backtrace have regressed
```rust
% rustc +nightly -V
rustc 1.25.0-nightly (51b0b3734 2018-01-12)
% echo 'fn main() { panic!() }' > a.rs
% rustc +nightly -g a.rs
% RUST_BACKTRACE=1 ./a   
thread 'main' panicked at 'explicit panic', a.rs:1:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: a::main
             at ./a.rs:1
   7: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  11: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  12: main
  13: __libc_start_main
  14: _start
% RUST_BACKTRACE=full ./a
thread 'main' panicked at 'explicit panic', a.rs:1:13
stack backtrace:
   0:     0x557717de85fb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h5875a9b214742a4d
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x557717deb9f1 - std::sys_common::backtrace::print::h143d03afdd7f5f00
                               at libstd/sys_common/backtrace.rs:68
                               at libstd/sys_common/backtrace.rs:57
   2:     0x557717de6620 - std::panicking::default_hook::{{closure}}::h8ff827baa6fe8dc7
                               at libstd/panicking.rs:380
   3:     0x557717de6158 - std::panicking::default_hook::h23592ba8d5e03a89
                               at libstd/panicking.rs:396
   4:     0x557717de69ab - std::panicking::rust_panic_with_hook::ha49ba53377acd9fa
                               at libstd/panicking.rs:576
   5:     0x557717de4677 - std::panicking::begin_panic::hb09c91adc2d20ae1
                               at /checkout/src/libstd/panicking.rs:537
   6:     0x557717de45cd - a::main::hed51cb165992ecb8
                               at /tmp/a.rs:1
   7:     0x557717de41a1 - std::rt::lang_start::{{closure}}::h996750b753d22e78
                               at /checkout/src/libstd/rt.rs:74
   8:     0x557717de66c7 - std::panicking::try::do_call::he88b5e1c2ad945b3
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:479
   9:     0x557717df80be - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  10:     0x557717de83cf - std::rt::lang_start_internal::h4b0a952236374327
                               at libstd/panicking.rs:458
                               at libstd/panic.rs:365
                               at libstd/rt.rs:58
  11:     0x557717de4181 - std::rt::lang_start::h9e17a65d1bce7359
                               at /checkout/src/libstd/rt.rs:74
  12:     0x557717de45fd - main
  13:     0x7ff5d955bf49 - __libc_start_main
  14:     0x557717de3f39 - _start
  15:                0x0 - <unknown>
```

`1` v.s. `full` is less verbose, but I remember it also filtering out some stack frames in some previous compiler versions. (Only frame # 6 is really useful to me here.) Indeed, `src/libstd/sys_common/backtrace.rs` contains some code that looks for a `__rust_begin_short_backtrace` symbol on the stack to find out what to filter. It looks like some functionality has regressed.

Stepping through the program in gdb it looks like the `__rust_begin_short_backtrace` function is called, but despite `#[inline(never)]` there’s apparently no stack frame (anymore?) for it.

CC @Yamakaky and @alexcrichton for #41815, #38165, and #40264.

### PR DESCRIPTION
**Pull request by eggyal**
I've stumbled across some situations where there (unexpectedly) was no `__rust_begin_short_backtrace` frame on the stack during unwinding.

On closer examination, it appeared that the calls to that function had been tail-call optimised away.

This PR follows [@bjorn3's suggestion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Disabling.20tail.20call.20optimisation.3F/near/205699133), by adding calls to `black_box` that hint to rustc not to perform TCO.

Fixes #47429

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Do we have evidence this actually fixes things? I would prefer to see this land alongside a UI test or so that actually verifies that we're seeing the behavior we expect here.

Alternatively, it may be that the right fix isn't in removing TCO from the short backtrace function but reworking how we determine where to start/stop short backtraces.

**Comment by eggyal** [comment]
It has certainly fixed the lack of `__rust_begin_short_backtrace` frame that I was running up against—but that was in a custom unwind routine so perhaps not the easiest way to test.  Just thinking aloud: what would be an appropriate UI test?  Checking that the output when panicking with `RUST_BACKTRACE=1` stops before `catch_unwind`?

**Comment by eggyal** [comment]
An idea for an alternative approach could be to store the stack pointer somewhere (thread-local?), and compare against that when unwinding.

**Comment by Mark-Simulacrum** [comment]
For testing I think the best thing is probably to use a unit test in library/std/src/backtrace.rs that asserts a given number of frames and a start/stop frame when getting a short backtrace. We might need to extract the actual formatting invocation to do so, though, into a separate function not tied to panicking in particular.

I don't think we need thread locals to get good results. I [experimented](https://github.com/Mark-Simulacrum/rust/commit/d8cb0c64643336fe32f67d5dd9180ba7642cfd55) a bit locally, and was able to get things down to this:

```
thread 'main' panicked at 'Test', /home/mark/Build/rust/library/std/src/panicking.rs:457:65
stack backtrace:
   0: std::panicking::begin_panic
             at ./Build/rust/library/std/src/panicking.rs:456
   1: t::bar
             at ./t.rs:6
   2: t::main
             at ./t.rs:2
   3: core::ops::function::FnOnce::call_once
             at ./Build/rust/library/core/src/ops/function.rs:233
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And with nightly:

```
thread 'main' panicked at 'Test', t.rs:6:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at library/std/src/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at library/std/src/sys_common/backtrace.rs:59
   4: core::fmt::write
             at library/core/src/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at library/std/src/io/mod.rs:1510
   6: std::sys_common::backtrace::_print
             at library/std/src/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at library/std/src/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at library/std/src/panicking.rs:198
   9: std::panicking::default_hook
             at library/std/src/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:526
  11: std::panicking::begin_panic
             at /rustc/cfc572cae2d1fc381cce476b5c787fd7221af98c/library/std/src/panicking.rs:456
  12: t::bar
             at ./t.rs:6
  13: t::main
             at ./t.rs:2
  14: std::rt::lang_start::{{closure}}
             at /rustc/cfc572cae2d1fc381cce476b5c787fd7221af98c/library/std/src/rt.rs:67
  15: std::rt::lang_start_internal::{{closure}}
             at library/std/src/rt.rs:52
  16: std::panicking::try::do_call
             at library/std/src/panicking.rs:348
  17: std::panicking::try
             at library/std/src/panicking.rs:325
  18: std::panic::catch_unwind
             at library/std/src/panic.rs:394
  19: std::rt::lang_start_internal
             at library/std/src/rt.rs:51
  20: std::rt::lang_start
             at /rustc/cfc572cae2d1fc381cce476b5c787fd7221af98c/library/std/src/rt.rs:67
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by erikdesjardins** [comment]
This likely fixes #47429

**Comment by Mark-Simulacrum** [comment]
I think we should try to add a UI test for this. My guess is we can do that with a run-fail test, like this one https://github.com/rust-lang/rust/blob/master/src/test/ui/test-panic-abort.rs

**Comment by eggyal** [comment]
It'd be nice if `BacktraceFrameFmt` didn't output directly but cached the last frame, which `_print_fmt` only flushed once the following frame is confirmed not to be a stop frame, so that the closure that invokes main could also be excluded from short backtraces.  But perhaps that's overkill.

File: library/std/src/panicking.rs [hunk 1]
```diff
@@ -453,7 +453,9 @@ pub fn begin_panic<M: Any + Send>(msg: M) -> ! {
         intrinsics::abort()
     }
 
-    rust_panic_with_hook(&mut PanicPayload::new(msg), None, Location::caller());
+    return crate::sys_common::backtrace::__rust_end_short_backtrace(move || {
```
Comment (bjorn3) [inline library/std/src/panicking.rs:456]: Could you also do this in `begin_panic_handler`?

**Comment by eggyal** [comment]
> I think we should try to add a UI test for this. My guess is we can do that with a run-fail test, like this one https://github.com/rust-lang/rust/blob/master/src/test/ui/test-panic-abort.rs

Agreed, I'll add one now.

File: library/std/src/panicking.rs (hunk 1 above)
Comment (eggyal) [reply library/std/src/panicking.rs:456]: Good spot.  Added for next push.

**Comment by eggyal** [comment]
Okay!  Finally passing... apologies, local rebuilds taking an absolute age so took a few attempts to get here.

**Comment by Mark-Simulacrum** [comment]
This looks great. Could you squash the commits into just the one to clean up git history a bit?

I suspect that this PR might cause problems if there's cases or platforms where our mini-functions get elided regardless of the black box, but we can iron out the kinks in nightly -- I don't think we'll find them by just looking in this PR, and it's small enough that I am comfortable just landing it.

r=me with commits squashed

**Comment by eggyal** [comment]
Sure, force-pushed a squash.  Had thought bors would do that when merging.

**Comment by bjorn3** [comment]
spurious network error

**Comment by eggyal** [comment]
@Mark-Simulacrum You're right, the closure that calls `main` is present on Ubuntu, but not on my local machine (OS X).  Guessing it's TCO again.  Not sure how best to test this consistently?

**Comment by Mark-Simulacrum** [comment]
Let's add a new subdirectory and test files with `// only-linux`, `// only-macos`, `// only-windows` -- that way we can be sure this at least works on Tier 1 platforms. Ideally we'd have the same output across platforms but I'm not too worried if it's just the closure vanishing for whatever reason (which might even just be different unwinding implementation).

**Comment by eggyal** [comment]
Only problem with that is that I can only generate outputs for OS X and would otherwise have to wait on bors failures to see what the others should be.  Thought occurred to me to put a `black_box` call into the closure that invokes `main` and thereby (hopefully) ensure its frame consistently remains on all platforms?

**Comment by eggyal** [comment]
The wider problem seems to be that TCO'd frames should not be omitted from backtraces at all, as it can make tracing panics through one's own code harder: in extremis, it could lead to no backtrace at all.  Perhaps TCO should be disabled in debug builds?

**Comment by Mark-Simulacrum** [comment]
I don't think we can viably disable TCO. Plus, release + debuginfo is a common configuration, and we'd not want to hurt performance there.

I wouldn't mind a black_box where you suggest, but I suspect it won't help matters.

I'm fine with using bors to get the appropriate test outputs (we can just run it through as needed).

**Comment by eggyal** [comment]
You're right.  I tried on OS X and the closure frame isn't there even with `black_box`, so instead I'll create the tier-1 platform tests as you proposed.  A bit concerned that they'll be pretty brittle however, with small changes in environment resulting in different behaviour?

**Comment by eggyal** [comment]
Okay, I guess that should have been predictable given that it was passing before.  Different traces on Ubuntu here vs bors.  Not sure where to go with this next, but have to call it a night for now and won't be available to take another look until tomorrow evening (UK).  Grateful for any thoughts/suggestions!

**Comment by eggyal** [comment]
@Mark-Simulacrum Let's see if bors is happy with that, I guess?

https://github.com/rust-lang/rust/pull/75048/commits/d3d34732387885fe78a523093b7915da97c2612a#diff-80b26e137ed7d1f329f047555686054fR3

**Comment by eggyal** [comment]
Agh, sorry it needs rebasing!

**Comment by eggyal** [comment]
Okay, looks like a bit of progress... but no backtrace on Android—led me to https://github.com/rust-lang/rust/blob/master/src/test/ui/backtrace.rs#L2-L7, which I've duplicated here.

🤞🏻

**Comment by eggyal** [comment]
@Mark-Simulacrum could we give this another crack please?  I spotted an error before bors got a chance to retry.

**Comment by ecstatic-morse** [comment]
This PR resulted in [moderate regressions in instruction counts](https://perf.rust-lang.org/compare.html?start=c2d1b0d9800d922b0451921d2ce17e6ae665d5b4&end=f3a9de9b08659e20ce7c282ed77bc43ddd149107&stat=instructions:u). The increase is mostly concentrated in very small benchmarks with little generated code, and seems to be caused by some additional codegen query invocations.

Is there any way to mitigate this? This is more impactful for superficial benchmarks than for actual users, so I don't think it necessitates a revert if the regressions are unavoidable.

**Comment by Mark-Simulacrum** [comment]
My guess is no -- we're probably just paying the cost of having one more function to codegen. I suspect any fix (e.g., trying to locate the inlined call frame manually or so) is going to be more expensive than the current tiny regressions.

**Comment by eggyal** [comment]
We could limit the effect of this PR to debug builds only?  Enforcing short backtraces in release is unlikely to be a requirement?

**Comment by bjorn3** [comment]
Libstd is always compiled without debug assertions. The optimization level of your program doesn't matter. You are always using the same compiled libstd.
