### PR TITLE
std: Rewrite Once with poisoning

### LINKED ISSUE #31688: sync::Once and panicking closure
The documentation for sync::Once does not clarify what happens if given closure
panics. Currently I would rather expect that call_once will execute the closure
only once, whether it panics or not. But this is not what happens:

```rust
#![feature(recover)]

use std::sync::*;
use std::panic::recover;

static ONCE : Once = ONCE_INIT;

fn main() {
    for i in 1..10 {
        let _ = recover(|| { 
            ONCE.call_once(|| {
                let s = if i > 1 { "s" } else { ""};
                panic!("Once::call_once called {} time{}", i, s);
            }); 
        });
    }
}
```

Prints:
```
thread '<main>' panicked at 'Once::call_once called 1 time', <anon>:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<main>' panicked at 'Once::call_once called 2 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 3 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 4 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 5 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 6 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 7 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 8 times', <anon>:13
thread '<main>' panicked at 'Once::call_once called 9 times', <anon>:13
```

Either way documentation needs a slight improvement. And additionally code if
it is not a desired behaviour. As a side comment I will note that this
behaviour differs between languages. In C++ for example std::call_once to
proceed must not exit via exception, in Go on the other hand exiting via panic
counts as successful execution.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit rewrites the `std::sync::Once` primitive with poisoning in mind in
light of #31688. Currently a panic in the initialization closure will cause
future initialization closures to run, but the purpose of a Once is usually to
initialize some global state so it's highly likely that the global state is
corrupt if a panic happened. The same strategy of a mutex is taken where a panic
is propagated by default.

A new API, `call_once_force`, was added to subvert panics like is available on
Mutex as well (for when panicking is handled internally).

Adding this support was a significant enough change to the implementation that
it was just completely rewritten from scratch, primarily to avoid using a
`StaticMutex` which needs to have `destroy()` called on it at some point (a pain
to do).

Closes #31688

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @aturon 

cc @rust-lang/libs

**Comment by sfackler** [comment]
Oooh, is this the first use of `thread::park`?

**Comment by alexcrichton** [comment]
Nah unfortunately that trophy went to channels long ago :)

File: src/libstd/sync/once.rs [hunk 1]
```diff
@@ -68,62 +139,183 @@ impl Once {
...
+        self.call_inner(false, &mut |_| f.take().unwrap()());
+    }
+
+    /// Performs the same function as `call_once` except ignores poisoning.
+    ///
+    /// If this `Once` has been poisoned (some initialization panicked) then
+    /// this function will continue to attempt to call initialization functions
+    /// until one of them doesn't panic.
+    ///
+    /// The closure `f` is yielded a boolean indicating whether this `Once` is
```
Comment (huonw) [inline src/libstd/sync/once.rs]: Is `true` "I am poisoned", or "I am valid"?

Comment (alexcrichton) [inline src/libstd/sync/once.rs]: Probably an indicator that this should be an enum or an opaque struct! Currently it means "I'm poisoned"

File: src/libstd/sync/once.rs [hunk 2]
```diff
@@ -68,62 +139,183 @@ impl Once {
...
+    ///
+    /// This is similar to [poisoning with mutexes][poison].
+    ///
+    /// [poison]: struct.Mutex.html#poisoning
     #[stable(feature = "rust1", since = "1.0.0")]
     pub fn call_once<F>(&'static self, f: F) where F: FnOnce() {
-        // Optimize common path: load is much cheaper than fetch_add.
-        if self.cnt.load(Ordering::SeqCst) < 0 {
+        // Fast path, just see if we've completed initialization.
+        if self.state.load(Ordering::SeqCst) == COMPLETE {
```
Comment (gereeter) [inline src/libstd/sync/once.rs]: This only has to be `Acquire`, and, since this is the fast path, this should be as weak as possible to prevent additional synchronization.

File: src/libstd/sync/once.rs [hunk 3]
```diff
@@ -68,62 +139,183 @@ impl Once {
...
+    /// If this `Once` has been poisoned (some initialization panicked) then
+    /// this function will continue to attempt to call initialization functions
+    /// until one of them doesn't panic.
+    ///
+    /// The closure `f` is yielded a boolean indicating whether this `Once` is
+    /// poisoned or not.
+    #[unstable(feature = "once_poison", issue = "31688")]
+    pub fn call_once_force<F>(&'static self, f: F) where F: FnOnce(bool) {
+        // same as above, just with a different parameter to `call_inner`.
+        if self.state.load(Ordering::SeqCst) == COMPLETE {
```
Comment (gereeter) [inline src/libstd/sync/once.rs]: Similarly, this should be `Acquire`.

File: src/libstd/sync/once.rs [hunk 4]
```diff
@@ -68,62 +139,183 @@ impl Once {
...
-            let prev = self.cnt.swap(isize::MIN, Ordering::SeqCst);
-            self.lock_cnt.store(prev, Ordering::SeqCst);
+        let mut f = Some(f);
+        self.call_inner(true, &mut |p| f.take().unwrap()(p));
+    }
+
+    #[cold]
+    fn call_inner(&'static self,
+                  ignore_poisoning: bool,
+                  mut init: &mut FnMut(bool)) {
```
Comment (gereeter) [inline src/libstd/sync/once.rs]: Could you add a comment explaining that we want to function to be virtual to prevent duplication of the cold path, but that there currently isn't an allocation-free way to virtualize an `FnOnce`, which is why this uses `FnMut`?

File: src/libstd/sync/once.rs (hunk 2 above)
Comment (alexcrichton) [inline src/libstd/sync/once.rs]: Yeah I suspect a number of these orderings could be relaxed, but for now I'm leaving *everything* as `SeqCst` so it can be easily reasoned about and I haven't measured a perf difference one way or another. I suspect that this is the only ordering that matters for speed (and the one mirrored below), and I *think* it can be `Acquire` as well but I'm just playing it safe for now.

File: src/libstd/sync/once.rs (hunk 4 above)
Comment (alexcrichton) [inline src/libstd/sync/once.rs]: Sure! This was primarily done to just reduce monomorphization costs, not to specifically have a `#[cold]` branch.

**Comment by Stebalien** [comment]
There is actually a use case for panicking in the `Once` initializer: it's the *only* way to abort initialization. This could be useful for, e.g., caching result of an expensive RPC call that is expected to succeed but may fail on occasion.

**Comment by alexcrichton** [comment]
@Stebalien that's an interesting data point! When we discussed this at the libs triage meeting we didn't reach a firm conclusion about whether we were comfortable to move forward with this or not, so it's good to have this data!

File: src/libstd/sync/once.rs (hunk 2 above)
Comment (gereeter) [inline src/libstd/sync/once.rs]: First, I would expect no change in code generated or in speed on x86 - the memory model is strong enough that a sequentially consistent load is just a `mov` instruction. Second, `Acquire` is definitely correct - all the synchronization is done on a single memory location (`self.state`), while `SeqCst` only introduces new synchronization between memory actions on different memory locations with respect to `AcqRel`.

File: src/libstd/sync/once.rs [hunk 5]
```diff
@@ -13,9 +13,59 @@
...
+// primitives, however, tend to have surprising restrictions, such as the Unix
+// one doesn't allow an argument to be passed to the function.
+//
+// As a result, we end up implementing it ourselves in the standard library.
+// This also gives us the opportunity to optimize the implementation a bit which
+// should help the fast path on call sites. Consequently, let's explain how this
+// primitive works now!
+//
+// So to recap, the guarantees of a Once are that it will call the
+// initialization closure exactly once, and it will never return until the one
```
Comment (aturon) [inline src/libstd/sync/once.rs]: s/exactly/at most/

File: src/libstd/sync/once.rs (hunk 1 above)
Comment (aturon) [inline src/libstd/sync/once.rs]: Agreed.

File: src/libstd/sync/once.rs [hunk 6]
```diff
@@ -68,62 +139,194 @@ impl Once {
...
+                INCOMPLETE => {
+                    let old = self.state.compare_and_swap(state, RUNNING,
+                                                          Ordering::SeqCst);
+                    if old != state {
+                        state = old;
+                        continue
+                    }
+
+                    // Run the initialization routine, letting it know if we're
+                    // poisoned or not, and then just return immediately after
```
Comment (aturon) [inline src/libstd/sync/once.rs]: Would be helpful for this comment to mention that `Finish` does the wakeups.

File: src/libstd/sync/once.rs [hunk 7]
```diff
@@ -68,62 +139,194 @@ impl Once {
...
+                    let mut node = Waiter {
+                        thread: Some(thread::current()),
+                        signaled: AtomicBool::new(false),
+                        next: 0 as *mut Waiter,
+                    };
+                    let me = &mut node as *mut Waiter as usize;
+                    assert!(me & STATE_MASK == 0);
+
+                    while state & STATE_MASK == RUNNING {
+                        node.next = (state & !STATE_MASK) as *mut Waiter;
```
Comment (aturon) [inline src/libstd/sync/once.rs]: Yay Treiber stack! :)

**Comment by aturon** [comment]
Beautiful -- this is pretty much *exactly* what I imagined when we discussed the algorithm the other day.

Just a couple minor nits -- would be good to introduce an enum/struct before landing, rather than having to do that adjustment later. With that, r=me.

File: src/libstd/sync/once.rs [hunk 8]
```diff
@@ -35,23 +85,44 @@ use sync::StaticMutex;
 /// ```
 #[stable(feature = "rust1", since = "1.0.0")]
 pub struct Once {
-    mutex: StaticMutex,
-    cnt: AtomicIsize,
-    lock_cnt: AtomicIsize,
+    state: AtomicUsize,
```
Comment (aturon) [inline src/libstd/sync/once.rs]: This struct should have some `PhantomData` describing the kind of data `state` can point to. (Basically this should be done any time a pointer is hidden in a usize, so that auto traits etc work correctly.)

**Comment by Manishearth** [comment]
@bors r-

```
<core macros>:2:4: 2:12 error: cannot apply unary operator `!` to type `&sync::once::OnceState`
<core macros>:2 if ! $ cond {
                   ^~~~~~~~
../src/libstd/sync/once.rs:443:13: 443:30 note: in this expansion of assert! (defined in <core macros>)
<core macros>:2:4: 2:12 error: cannot apply unary operator `!` to type `&sync::once::OnceState`
<core macros>:2 if ! $ cond {
                   ^~~~~~~~
../src/libstd/sync/once.rs:466:17: 466:28 note: in this expansion of assert! (defined in <core macros>)
error: aborting due to 2 previous errors
make: *** [x86_64-unknown-linux-gnu/stage2/test/stdtest-x86_64-unknown-linux-gnu] Error 101
```

http://buildbot.rust-lang.org/builders/auto-linux-64-nopt-t/builds/8503/steps/test/logs/stdio

**Comment by huonw** [comment]
> There is actually a use case for panicking in the Once initializer: it's the only way to abort initialization. This could be useful for, e.g., caching result of an expensive RPC call that is expected to succeed but may fail on occasion.

Was this discussed further? (I've unfortunately missed quite a few libs meetings recently.)

It seems like it might be worth providing a separate function something like `try_call_once<F: FnOnce() -> Status>(...)` `enum Status { Succeeded, Retry }` that handles this case in a non-hacky way.

**Comment by aturon** [comment]
@huonw IIRC, we decided that functionality like this can be easily added in the future if desired.
