### PR TITLE
Lint on invalid values passed to x.py --warnings

### LINKED ISSUE #62402: `x.py build --warnings deny` does not fail despite warnings
I patched libstd and wanted to be sure it builds without warnings, so I did:
```
$ ./x.py build --stage 0 src/libstd --warnings deny
```
However, this build succeeded despite there being warnings:
```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
warning: /home/r/src/rust/rustc.3/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
   Compiling cc v1.0.35
   Compiling core v0.0.0 (/home/r/src/rust/rustc.3/src/libcore)
   Compiling build_helper v0.1.0 (/home/r/src/rust/rustc.3/src/build_helper)
   Compiling autocfg v0.1.4
   Compiling backtrace v0.3.29
   Compiling compiler_builtins v0.1.16
   Compiling backtrace-sys v0.1.27
   Compiling cmake v0.1.38
   Compiling std v0.0.0 (/home/r/src/rust/rustc.3/src/libstd)
   Compiling rustc_msan v0.0.0 (/home/r/src/rust/rustc.3/src/librustc_msan)
   Compiling rustc_lsan v0.0.0 (/home/r/src/rust/rustc.3/src/librustc_lsan)
   Compiling rustc_asan v0.0.0 (/home/r/src/rust/rustc.3/src/librustc_asan)
   Compiling rustc_tsan v0.0.0 (/home/r/src/rust/rustc.3/src/librustc_tsan)
   Compiling unwind v0.0.0 (/home/r/src/rust/rustc.3/src/libunwind)
   Compiling rustc-std-workspace-core v1.0.0 (/home/r/src/rust/rustc.3/src/tools/rustc-std-workspace-core)
   Compiling libc v0.2.54
   Compiling alloc v0.0.0 (/home/r/src/rust/rustc.3/src/liballoc)
   Compiling cfg-if v0.1.8
   Compiling rustc-demangle v0.1.15
   Compiling panic_abort v0.0.0 (/home/r/src/rust/rustc.3/src/libpanic_abort)
   Compiling rustc-std-workspace-alloc v1.0.0 (/home/r/src/rust/rustc.3/src/tools/rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (/home/r/src/rust/rustc.3/src/libpanic_unwind)
   Compiling hashbrown v0.4.0
warning: use of item 'core::mem::uninitialized' that will be deprecated in future version 1.38.0: use `mem::MaybeUninit` instead
  --> src/libstd/io/util.rs:48:54
   |
48 |         let mut buf: [u8; super::DEFAULT_BUF_SIZE] = mem::uninitialized();
   |                                                      ^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src/libstd/lib.rs:208:9
   |
208| #![warn(deprecated_in_future)]
   |         ^^^^^^^^^^^^^^^^^^^^

warning: use of item 'sync::once::ONCE_INIT' that will be deprecated in future version 1.38.0: the `new` function is now preferred
   --> src/libstd/sync/mod.rs:167:39
    |
167 | pub use self::once::{Once, OnceState, ONCE_INIT};
    |                                       ^^^^^^^^^

    Finished release [optimized] target(s) in 31.86s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Build completed successfully in 0:00:32
```
I have `deny-warnings = false` in my `config.toml`, but that shouldn't render `--warnings` unusable (at least, the help for `--warnings` does not say anything like that). In fact, it seems like the flag would be a NOP anyway with `deny-warnings = true`?

Also, `--warnings denyyyy` just builds fine, so it seems like there is no input sensitization going on.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This also introduces support for `--warnings allow` and fixes --warnings
being overridden by the configuration file, config.toml.

Fixes #62402

r? @RalfJung

### CODE REVIEW

File: src/bootstrap/flags.rs [hunk 1]
```diff
@@ -443,6 +443,19 @@ Arguments:
             }
         };
 
+        let warnings = match matches.opt_str("warnings").as_ref().map(|v| v.as_str()) {
```
Comment (Centril) [inline src/bootstrap/flags.rs]: Could you add this to its own function + a comment re. what is happening?

File: src/bootstrap/flags.rs [hunk 2]
```diff
@@ -468,7 +481,7 @@ Arguments:
                 .into_iter()
                 .map(|p| p.into())
                 .collect::<Vec<_>>(),
-            warnings: matches.opt_str("warnings").map(|v| v == "deny"),
+            warnings: warnings,
```
Comment (Centril) [inline src/bootstrap/flags.rs]:
```suggestion
            warnings,
```

File: src/bootstrap/flags.rs (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/flags.rs]: The code looks pretty obvious to me - what exactly would you want in the comment?

Comment (Centril) [reply src/bootstrap/flags.rs]: Well for one it would be good to know what the role of the `warnings` field is (it just says "true => deny"), why `"deny"` implies `true`, etc. But also it is hard to read code when you just have a big blob inside a function.

Also, why isn't the closure `usage` used here instead of using `std::process::exit`? (Moreover, `std::process` is in scope.)

Also, [I feel obliged to echo @oli-obk here.](https://twitter.com/oli_obk/status/1136582096737185795)

Comment (Mark-Simulacrum) [reply src/bootstrap/flags.rs]: I've added some docs to the field (previously `warnings`, now `deny_warnings`).

I disagree that this would be good to pull out into a separate function; I think that wouldn't actually help. This is a single statement, not a group, and this function is the one that deals with processing command line arguments. It's also not a repetition of code, i.e., we're not going to be able to have other code which calls this function.

We're not using `usage` because I wanted to tailor the error message specifically to warnings, e.g., by including the permitted values. It's possibly that it could be made better, but I don't personally want to spend the time figuring out how to integrate with `usage`. This works, is simple, and IMO easier to interpret for end-users and future readers of this code.

Comment (Centril) [reply src/bootstrap/flags.rs]: > I've added some docs to the field (previously `warnings`, now `deny_warnings`).

Thanks!

> I disagree that this would be good to pull out into a separate function; I think that wouldn't actually help. This is a single statement, not a group, and this function is the one that deals with processing command line arguments. It's also not a repetition of code, i.e., we're not going to be able to have other code which calls this function.

I don't think that matters so much. By having large functions you force readers to pay attention to details which may be irrelevant to what the function does at large (in this case parsing all the arguments into flags instead of just dealing with `--warnings`) and it makes skimming the code harder. We don't have to have 5 line functions everywhere, but 395 lines is not readable and this is how

Comment (Mark-Simulacrum) [reply src/bootstrap/flags.rs]: I guess I don't care that much. I can do it if it'll unblock this PR. I've never read through this whole function though when trying to edit it, so I don't really see the point, and I continue to think it's actually harmful - makes understanding it harder rather than easier in straight-line code. I would have a different opinion if this function was a mess of if statements that were all nested, but it's not.

**Comment by RalfJung** [comment]
Are you sure you want me to review bootstrap stuff? I can try, but I have basically not have had any contact with that code.^^

**Comment by Mark-Simulacrum** [comment]
This is just touching argument parsing; pretty much anyone can review it. Up to you. If you don't want to I'd assign to `@alexcrichton`

File: src/bootstrap/config.rs [hunk 3]
```diff
@@ -405,7 +405,7 @@ impl Config {
         config.incremental = flags.incremental;
         config.dry_run = flags.dry_run;
         config.keep_stage = flags.keep_stage;
-        if let Some(value) = flags.warnings {
+        if let Some(value) = flags.deny_warnings {
             config.deny_warnings = value;
         }
```
Comment (RalfJung) [inline src/bootstrap/config.rs]: So argument parsing here is some kind of two-stage process? `&[String]` -> `Flags` -> `Config`? And this is specifically for what gets passed on the cmdline?

File: src/bootstrap/config.rs [hunk 4]
```diff
@@ -571,7 +571,7 @@ impl Config {
             config.rustc_default_linker = rust.default_linker.clone();
             config.musl_root = rust.musl_root.clone().map(PathBuf::from);
             config.save_toolstates = rust.save_toolstates.clone().map(PathBuf::from);
-            set(&mut config.deny_warnings, rust.deny_warnings.or(flags.warnings));
+            set(&mut config.deny_warnings, flags.deny_warnings.or(rust.deny_warnings));
```
Comment (RalfJung) [inline src/bootstrap/config.rs]: `rust` here refers to the `config.toml`?

File: src/bootstrap/flags.rs [hunk 5]
```diff
@@ -468,7 +472,7 @@ Arguments:
                 .into_iter()
                 .map(|p| p.into())
                 .collect::<Vec<_>>(),
-            warnings: matches.opt_str("warnings").map(|v| v == "deny"),
+            deny_warnings,
```
Comment (RalfJung) [inline src/bootstrap/flags.rs]: IMO readability is slightly improved by inlining the `let`:
`deny_warnings: parse_deny_warnings(&matches)`
Not a blocker though.

**Review by RalfJung — COMMENTED** [review]
Well I suppose I can try to just make guesses about the rest of the code. ;)  Seems unlikely to have subtle interactions.

I just have a few questions and one nit, r=me otherwise.

File: src/bootstrap/config.rs (hunk 4 above)
Comment (RalfJung) [reply src/bootstrap/config.rs]: Oh also, this inversion of priority won't disturb CI somehow? I don't know exactly how CI passes its parameters but I seem to recall it's not through `config.toml`.

File: src/bootstrap/config.rs (hunk 3 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/config.rs]: Yep, that's correct -- configuration loading is a bit non-ideal.

File: src/bootstrap/config.rs (hunk 4 above)
Comment (Mark-Simulacrum) [reply src/bootstrap/config.rs]: Yes, that's true. CI doesn't pass the `--warnings` flag so it should be fine.
