### PR TITLE
Fix erroneous span for borrowck error

### LINKED ISSUE #97997: Duplicated `implementation is not general enough` error on function pointers
Given the following code ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0bd9d21018e75ff5f68b491bfd51bed4)):

```rust
trait Foo {
    const ASSOC: bool = true;
}
impl<T> Foo for fn(T) {}

fn foo(_x: i32) {}

fn impls_foo<T: Foo>(_x: T) {}

fn main() {
    // Works, but if the below code is present, it is shown as failed
    impls_foo(foo as fn(i32));

    // Fails as expected, see https://github.com/rust-lang/rust/issues/56105
    <fn(&u8) as Foo>::ASSOC;
}
```

The current (`nightly` ec55c6130 `2022-06-10`, regressed in the past week) output is:

```
   Compiling playground v0.0.1 (/playground)
error: implementation of `Foo` is not general enough
  --> src/main.rs:12:5
   |
12 |     impls_foo(foo as fn(i32));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `Foo` would have to be implemented for the type `for<'r> fn(&'r u8)`
   = note: ...but `Foo` is actually implemented for the type `fn(&'0 u8)`, for some specific lifetime `'0`

error: implementation of `Foo` is not general enough
  --> src/main.rs:15:5
   |
15 |     <fn(&u8) as Foo>::ASSOC;
   |     ^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `Foo` would have to be implemented for the type `for<'r> fn(&'r u8)`
   = note: ...but `Foo` is actually implemented for the type `fn(&'0 u8)`, for some specific lifetime `'0`

error: could not compile `playground` due to 2 previous errors
```

Ideally the output should look like:

```
   Compiling playground v0.0.1 (/playground)
error: implementation of `Foo` is not general enough
  --> src/main.rs:15:5
   |
15 |     <fn(&u8) as Foo>::ASSOC;
   |     ^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `Foo` would have to be implemented for the type `for<'r> fn(&'r u8)`
   = note: ...but `Foo` is actually implemented for the type `fn(&'0 u8)`, for some specific lifetime `'0`

error: could not compile `playground` due to previous error
```

The desired result can be achieved by swapping the order of the two statements `<fn(&u8) as Foo>::ASSOC;` and `impls_foo(foo as fn(i32));`.

### PR DESCRIPTION
**Pull request by compiler-errors**
I am not confident that this is the correct fix, but it does the job. Open to suggestions for a real fix instead.

Fixes #97997

The issue is that we pass a [dummy location](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_middle/mir/visit.rs.html#302) when type-checking the ["required consts"](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html#structfield.required_consts) that are needed by the MIR body during borrowck. This means that when we fail to evaluate the constant, we use the span of `bb0[0]`, instead of the actual span of the constant.

There are quite a few other places that use `START_BLOCK.start_location()`, `Location::START`, etc. when calling for a random/unspecified `Location` value. This is because, unlike (for example) `Span`, we don't have a dummy/miscellaneous value to use instead. I would appreciate guidance (either in this PR, or a follow-up) on what needs to be done to clean this up in general.

### CODE REVIEW

**Comment by bugadani** [comment]
Correct me if I'm wrong, but I don't think this "fixes" #97997 as that issue is about the duplicate error, not the wrong location. Looking at the new test, this PR expect the error to be duplicated, which means merging this shouldn't mark the issue fixed.

**Comment by compiler-errors** [comment]
@bugadani: The error is deduplicated by the diagnostic printing logic, except for in UI tests, and renders as one if you invoke rustc normally.

**Comment by compiler-errors** [comment]
The reason it shows up as two in the when you added that extra unrelated line original github issue was precisely because the spans for the two copies of the error (that are always printed) differ, meaning that they don't get deduplicated by the compiler.

**Comment by wesleywiser** [comment]
This seems like a question for the diagnostics working group with regards to how we want to handle this kind of situation generally in the compiler. Forwarding to @estebank as the lead of that wg. 

r? @estebank

**Comment by compiler-errors** [comment]
I was more curious about getting feedback from someone who's an expert on MIR than an expert on diagnostics. My understanding is that this isn't really a diagnosics issue per se, but an issue with Location type which is a MIR concept.

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -357,12 +357,20 @@ impl<'a, 'b, 'tcx> Visitor<'tcx> for TypeVerifier<'a, 'b, 'tcx> {
                 .add_element(live_region_vid, location);
         });
 
+        // HACK(compiler-errors): Constants that are gathered into Body.required_consts
+        // have their locations erased...
+        let locations = if location != Location::START {
+            location.to_locations()
+        } else {
+            Locations::All(constant.span)
+        };
```
Comment (estebank) [inline compiler/rustc_borrowck/src/type_check/mod.rs:366]: It seems like you've identified the right course of action (modifying Body.required_consts instead of here).

*I*'d be ok with landing this as a temporary hack, but I'd rather getting sign off from somebody immediately related to the `const` generics effort. I'd punt to @oli-obk, but he'll be somewhat unavailable.

Comment (oli-obk) [reply compiler/rustc_borrowck/src/type_check/mod.rs:366]: I wonder if we should just unconditionally use the constant's span, it seems like that span will always be better than what we can guess from the location (or we'll just end up fetching the constant's span at the location anyway). At which point it begs the question of whether we should be passing a location to `visit_constant` at all. 

A quick skim of all `visit_constant` and `visit_const` suggest that we're only really interested in the span, not the actual mir location.

anyway. Leaving the hack comment and fixing this in a follow up PR seems the quickest way forward.

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/mod.rs:366]: Yeah, I looked into that refactoring, but we also use Location (and not Locations) as a key to some different HashMaps in different MIR stages? I'll see if I can give the refactoring another go, though.
