### PR TITLE
Optimize catch_unwind to match C++ try/catch

### LINKED ISSUE #64222: Missed optimization: catch_unwind not removed when closure never unwinds
Consider this C++ code (https://gcc.godbolt.org/z/iaSj6g) 

```c++
extern "C" void foo() noexcept;

int bar() {
    try {
        foo();
        return 42;
    } catch(...) {
        return 13;
    }
}
```

which gets optimized to:

```asm
bar():                                # @bar()
        push    rax
        call    foo
        mov     eax, 42
        pop     rcx
        ret
```

Now consider the semantically identical Rust code (https://gcc.godbolt.org/z/2tXtOM):

```rust
#![feature(unwind_attributes)]

extern "C" {
    // never unwinds:
    #[unwind(abort)] fn foo(); 
}

pub unsafe fn bar() -> i32 {
    std::panic::catch_unwind(|| { foo(); 42 }).unwrap_or(13)
}
```

which generates (https://gcc.godbolt.org/z/fzSBl7 - note: to workaround `#[unwind(abort)]` currently not emitting `nounwind` I've added the attributes manually to the Rust output and piped the output through opt -O3 before piping it to llc -O3):

```asm
;; this is only a small part of what it generates
example::bar: # @example::bar
  push rbp
  push r14
  push rbx
  sub rsp, 32
  mov qword ptr [rsp + 16], 0
  mov qword ptr [rsp + 24], 0
  lea rsi, [rsp + 12]
  lea rdx, [rsp + 16]
  lea rcx, [rsp + 24]
  mov edi, offset std::panicking::try::do_call
  call qword ptr [rip + __rust_maybe_catch_panic@GOTPCREL]
  test eax, eax
  je .LBB2_1
  mov rdi, -1
  call qword ptr [rip + std::panicking::update_panic_count@GOTPCREL]
  mov r14, qword ptr [rsp + 16]
  mov rbx, qword ptr [rsp + 24]
  mov rdi, r14
  call qword ptr [rbx]
  mov rsi, qword ptr [rbx + 8]
  mov ebp, 13
  test rsi, rsi
  je .LBB2_5
  mov rdx, qword ptr [rbx + 16]
  mov rdi, r14
  call qword ptr [rip + __rust_dealloc@GOTPCREL]
  jmp .LBB2_5
.LBB2_1: # %_ZN3std5panic12catch_unwind17h19eaab96d48c9410E.exit
  mov ebp, dword ptr [rsp + 12]
.LBB2_5: # %"_ZN4core6result19Result$LT$T$C$E$GT$9unwrap_or17hd512dca21f83b98fE.exit"
  mov eax, ebp
  add rsp, 32
  pop rbx
  pop r14
  pop rbp
  ret
  mov rbp, rax
  mov rdi, r14
  mov rsi, rbx
  call alloc::alloc::box_free
  mov rdi, rbp
  call _Unwind_Resume
```

Removing the unnecessary catch unwind I get instead: 

```asm
example::bar:
  push rax
  call qword ptr [rip + foo@GOTPCREL]
  mov eax, 42
  pop rcx
  ret
```

which is the same code that clang generates and what I expect to be generated when the closure passed to `catch_unwind` never unwinds.

For `catch_unwind` to be a zero cost abstraction, it needs to generate the same machine code as C++ in this case when optimizations are turned on.

### LINKED ISSUE #64224: Why is the code size of catch_unwind so large ?
While filling #64222 I noticed that we generate more code than C++ for `catch_unwind`. That did not feel right, since C++'s `catch` can do much more than Rust's catch unwind, e.g., filtering different types of exceptions, etc. 

MWE: C++ (https://gcc.godbolt.org/z/z_dgPg):

```c++
extern "C" void foo();

int bar() {
    try {
        foo();
        return 42;
    } catch(...) {
        return 13;
    }
}
```

generates

```asm
bar(): # @bar()
  push rbx
  mov ebx, 42
  call foo
  mov eax, ebx
  pop rbx
  ret
  mov rdi, rax
  call __cxa_begin_catch
  call __cxa_end_catch
  mov ebx, 13
  mov eax, ebx
  pop rbx
  ret
```

while Rust (https://gcc.godbolt.org/z/4sbc6k):

```rust
#![feature(unwind_attributes)]

extern "C" {
    // can unwind:
    #[unwind(allow)] fn foo(); 
}

pub unsafe fn bar() -> i32 {
    std::panic::catch_unwind(|| { foo(); 42 }).unwrap_or(13)
}
```

generates

```asm
example::bar:
  push rbp
  push r14
  push rbx
  sub rsp, 32
  mov qword ptr [rsp + 16], 0
  mov qword ptr [rsp + 24], 0
  lea rdi, [rip + std::panicking::try::do_call]
  lea rsi, [rsp + 12]
  lea rdx, [rsp + 16]
  lea rcx, [rsp + 24]
  call qword ptr [rip + __rust_maybe_catch_panic@GOTPCREL]
  test eax, eax
  je .LBB2_1
  mov rdi, -1
  call qword ptr [rip + std::panicking::update_panic_count@GOTPCREL]
  mov r14, qword ptr [rsp + 16]
  mov rbx, qword ptr [rsp + 24]
  mov rdi, r14
  call qword ptr [rbx]
  mov rsi, qword ptr [rbx + 8]
  mov ebp, 13
  test rsi, rsi
  je .LBB2_5
  mov rdx, qword ptr [rbx + 16]
  mov rdi, r14
  call qword ptr [rip + __rust_dealloc@GOTPCREL]
  jmp .LBB2_5
.LBB2_1:
  mov ebp, dword ptr [rsp + 12]
.LBB2_5:
  mov eax, ebp
  add rsp, 32
  pop rbx
  pop r14
  pop rbp
  ret
  mov rbp, rax
  mov rdi, r14
  mov rsi, rbx
  call alloc::alloc::box_free
  mov rdi, rbp
  call _Unwind_Resume@PLT
  ud2
```

This appears to be a constant overhead every time `catch_unwind` is used (e.g. see https://gcc.godbolt.org/z/bAvN24). Maybe we are inlining too much ?

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This refactors the implementation of catching unwinds to allow LLVM to inline the "try" closure directly into the happy path, avoiding indirection. This means that the catch_unwind implementation is (after this PR) zero-cost unless a panic is thrown.

https://rust.godbolt.org/z/cZcUSB is an example of the current codegen in a simple case. Notably, the codegen is *exactly the same* if `-Cpanic=abort` is passed, which is clearly not great.

This PR, on the other hand, generates the following assembly:

```asm
# -Cpanic=unwind:
	push   rbx
	mov    ebx,0x2a
	call   QWORD PTR [rip+0x1c53c]        # <happy>
	mov    eax,ebx
	pop    rbx
	ret
	mov    rdi,rax
	call   QWORD PTR [rip+0x1c537]        # cleanup function call
	call   QWORD PTR [rip+0x1c539]        # <unfortunate>
	mov    ebx,0xd
	mov    eax,ebx
	pop    rbx
	ret

# -Cpanic=abort:
	push   rax
	call   QWORD PTR [rip+0x20a1]        # <happy>
	mov    eax,0x2a
	pop    rcx
	ret
```

Fixes #64224, and resolves #64222.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I suspect that the best reviewer here is r? @alexcrichton.

I am not sure whether we want to accept this. I created this patch while trying to investigate https://github.com/rust-lang/rust/issues/64224; it is a slight simplification of the generated assembly, but not really anything too major (as might be expected).

File: src/libpanic_unwind/emcc.rs [hunk 1]
```diff
@@ -48,26 +48,34 @@ static EXCEPTION_TYPE_INFO: TypeInfo = TypeInfo {
...
     __cxa_end_catch();
-    ex
+    ex.unwrap()
 }
 
 pub unsafe fn panic(data: Box<dyn Any + Send>) -> u32 {
     let sz = mem::size_of_val(&data);
-    let exception = __cxa_allocate_exception(sz);
+    let exception = __cxa_allocate_exception(sz) as *mut Exception;
     if exception == ptr::null_mut() {
```
Comment (lzutao) [inline src/libpanic_unwind/emcc.rs]:
```suggestion
     if exception.is_null() {
```

File: src/libstd/panicking.rs [hunk 2]
```diff
@@ -265,28 +287,31 @@ pub unsafe fn r#try<R, F: FnOnce() -> R>(f: F) -> Result<R, Box<dyn Any + Send>>
...
         debug_assert!(update_panic_count(0) == 0);
-        Err(mem::transmute(raw::TraitObject {
-            data: any_data as *mut _,
-            vtable: any_vtable as *mut _,
-        }))
-    };
+        obj
+    }
+
+    #[cfg(not(feature = "panic_unwind"))]
```
Comment (Amanieu) [inline src/libstd/panicking.rs]: I don't feel comfortable relying on a feature flag for this, we should instead let the compiler optimize the call out when it finds that the catch path is unreachable. If the feature flags don't match the compiler flags then this could lead to UB.

File: src/libstd/panicking.rs [hunk 3]
```diff
@@ -41,12 +65,10 @@ use realstd::io::set_panic;
...
 extern "C" {
-    fn __rust_maybe_catch_panic(
-        f: fn(*mut u8),
-        data: *mut u8,
-        data_ptr: *mut usize,
-        vtable_ptr: *mut usize,
-    ) -> u32;
+    /// The payload ptr here is actually the same as the payload ptr for the try
+    /// intrinsic (i.e., is really `*mut [u64; 2]` or `*mut *mut u8`).
+    #[unwind(allowed)]
```
[the remark this answers is not in the document]
Comment (Mark-Simulacrum) [reply src/libstd/panicking.rs]: This is not strictly true today (e.g., `emcc` uses Option::unwrap, as does the gcc implementation).

File: src/libstd/panicking.rs [hunk 4]
```diff
@@ -41,12 +65,10 @@ use realstd::io::set_panic;
...
+    fn __rust_cleanup(payload: *mut u8) -> Box<dyn Any + Send + 'static>;
```
[the remark this answers is not in the document]
Comment (Mark-Simulacrum) [reply src/libstd/panicking.rs]: I can rename the symbol to that, yes. (I think we're generally of the policy that `__rust*` symbols are our own and no one should reuse that "namespace", though).

Passing the panic in by-value means that we need to duplicate the cfg-if one more time into libpanic_abort so that we can take either `[u64; 2]` or` *mut u8` which this avoids.

File: src/libstd/panicking.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Amanieu) [reply src/libstd/panicking.rs]: The gcc implementation no longer uses unwrap (see the commit I just pushed). And in any case, any panic in this function would cause a double panic and abort, and will never unwind.

**Comment by Mark-Simulacrum** [comment]
I believe the test failure here is because we treat `-Zno-landing-pads` and `-Cpanic=abort` equivalently today, which has worked so far because `-Zno-landing-pads` was never passed to the libpanic_unwind compiler. These two options mean different things though: `-Zno-landing-pads` means that a panic will not run destructors, but will still unwind, whereas `-Cpanic=abort` will just immediately abort.

I'm not actually sure if there's much use to `-Zno-landing-pads` -- is there a situation where you want to unwind but not actually run destructors and so forth? I think the answer is no, or at least, it doesn't make much sense to me. I would suggest that we drop that flag entirely.

That would mean that the test in question would also be deleted; we do not expect that a crate with `-Cpanic=abort` can catch panics (even at thread boundaries).

**Comment by Amanieu** [comment]
Should be good to merge at this point. I moved some unrelated commits fixing some memory leaks to a separate PR (#67711).

File: src/libstd/panicking.rs [hunk 5]
```diff
@@ -29,6 +28,31 @@ use crate::io::set_panic;
 #[cfg(test)]
 use realstd::io::set_panic;
 
+// This must be kept in sync with the implementations in libpanic_unwind.
+//
+// This is *not* checked in anyway; the compiler does not allow us to use a
```
Comment (alexcrichton) [inline src/libstd/panicking.rs]: s/anyway/any way/

File: src/libstd/panicking.rs [hunk 6]
```diff
@@ -29,6 +28,31 @@ use crate::io::set_panic;
...
+// type/macro/anything from panic_unwind, since we're then linking in the
+// panic_unwind runtime even during -Cpanic=abort.
+//
+// Essentially this must be the type of `imp::Payload` in libpanic_unwind.
```
Comment (alexcrichton) [inline src/libstd/panicking.rs]: Would it be possible to extract the definition of `Payload` to a `foo.rs` file which we could include with `#[path]` here?

**Review by alexcrichton — COMMENTED** [review]
One thing I'm worried about here is that this PR changes the standard library to unconditionally use the `try` intrinsic no matter what panic mode is selected. Previously the `try` intrinsic was only codegen'd into the `panic_unwind` crate, but now it'll also be codegen'd when using `panic=abort`. 

I don't think that this is a huge huge problem but I do think that we very much want to avoid any `invoke` instructions at all in `panic=abort` mode. Some targets in LLVM die really quickly on the `invoke` instruction I think. Could you double check the raw IR output in debug mode in `panic=abort` mode to make sure no `invoke` instruction exists? 

This may require updating the codegen of the `try` intrinsic to just be `call` in panic=abort mode which I suspect would be a relatively simple change. It may also already be done, I'm not sure!

File: src/test/ui/no-landing-pads.rs [hunk 7]
```diff
@@ -1,6 +1,7 @@
 // run-pass
 // compile-flags: -Z no-landing-pads -C codegen-units=1
 // ignore-emscripten no threads support
+// ignore-test fails because catch_unwind doesn't work with no-landing-pads
```
Comment (alexcrichton) [inline src/test/ui/no-landing-pads.rs]: I think it's fine to just delete this test. This is testing the `-Z` option but it's not too important to test that nowadays. This could be re-introduced by having separate compilation, one crate with the flag and one without.

**Comment by Amanieu** [comment]
> This may require updating the codegen of the try intrinsic to just be call in panic=abort mode which I suspect would be a relatively simple change. It may also already be done, I'm not sure!

This is already the case: `try` lowers to `call` with `-Z no-landing-pads` (which `panic=abort` enables).

**Comment by alexcrichton** [comment]
Great! That's perfect

**Comment by Amanieu** [comment]
Error 0xc0000409 seems to be a stack overflow. This is going to be fun to debug...

**Comment by Amanieu** [comment]
OK so I'm starting to see what's happening here: this issue only happens with `-C prefer-dynamic`. This was fine previously since both the `try` intrinsic and the code throwing the exception were in the same DLL.

However since we are now inlining the `try` intrinsic into various crates we now need to provide a separate instance of the `TypeDescriptor` for `rust_panic` in every DLL that uses `try`.

The SEH metadata requires that the `TypeDescriptor` be within the current DLL. Matching the thrown exception type with the `catch` statement is done using a string comparison of the type name in the thrown `TypeDescriptor` with the type name in the `TypeDescriptor` handled by the `catch`.

Clang generates the following LLVM IR:
```
@"??_7type_info@@6B@" = external constant i8*
@"??_R0?AUrust_panic@@@8" = linkonce_odr global %rtti.TypeDescriptor16 { i8** @"??_7type_info@@6B@", i8* null, [17 x i8] c".?AUrust_panic@@\00" }, comdat
```

I think we should be able to manually emit the same IR manually with a note to keep it in sync with the `TypeDescriptor` in libpanic_unwind. Alternatively, can the try intrinsic codegen read the definition of the `eh_catch_typeinfo` lang item and generate the IR based on that (I'm not sure if this is possible)?

**Comment by Amanieu** [comment]
OK this should fix the issue.

I would appreciate if someone could double-check the changes in intrinsics.rs for the latest commit.

**Comment by RalfJung** [comment]
@Aaron1011 I think this will entirely break Miri's unwind implementation (`__rust_maybe_catch_panic`, which it was all based on, seems to be removed entirely)... do you have time to look at this?

**Comment by Mark-Simulacrum** [comment]
My hope would be that miri can now simply do different things for the try intrinsic (which is now the sole code path), but I've not looked into it myself :)

**Comment by RalfJung** [comment]
Miri does not implement the try intrinsic at all. Instead, it currently [hooks `__rust_maybe_catch_panic`](https://github.com/rust-lang/miri/blob/b4c54b464198bb56cf01289c50cd20af0b154d95/src/shims/foreign_items.rs#L342). (That being an FFI-imported function, it has to be specially handled by Miri anyway.)

It looks like the `try` intrinsic is more platform-specific than `__rust_maybe_catch_panic` (with this `TryPayload` type), so I expect this will make things noticeably more complicated for Miri. I am not sure though.

**Comment by Mark-Simulacrum** [comment]
Well, I think we basically just inlined the libpanic_unwind definition for the __rust_maybe_catch_panic function, and didn't make it more platform specific -- the payload pointer and the `TryPayload` type are pretty much the same concept).

I think it probably makes sense to move this discussion elsewhere, but feel free to ping me on an issue or so within miri if you'd like (I would not be opposed to trying to fix miri's panicking impl, with this PR, presuming @Aaron1011 would not be interested currently).

**Comment by RalfJung** [comment]
> we basically just inlined the libpanic_unwind definition for the __rust_maybe_catch_panic function, and didn't make it more platform specific -- the payload pointer and the TryPayload type are pretty much the same concept).

Yeah, but before Miri never saw that code. The `__rust_maybe_catch_panic` implementation in libpanic_unwind was never executed by Miri, it ran its own stuff directly in the interpreter instead.

> I would not be opposed to trying to fix miri's panicking impl, with this PR, presuming @Aaron1011 would not be interested currently

Okay, let's see what they say.

**Comment by Aaron1011** [comment]
> I think it probably makes sense to move this discussion elsewhere, but feel free to ping me on an issue or so within miri if you'd like (I would not be opposed to trying to fix miri's panicking impl, with this PR, presuming @Aaron1011 would not be interested currently).

If you'd like to fix the Miri side, that's fine by me.

**Comment by Mark-Simulacrum** [comment]
I would prefer not to. But if you have questions, or need me to do it, then I can.

**Comment by Aaron1011** [comment]
I'll work on a follow-up PR to fix it

**Comment by Amanieu** [comment]
For some reason LLVM isn't inlining the `__rust_try` function on WASM targets. But it is getting inline on all other targets...

Any ideas or should we just disable this test for WASM?

```rust
#![feature(lang_items, no_core, intrinsics)]
#![no_core]
#![crate_type = "rlib"]

#[lang = "sized"]
trait Sized {}
#[lang = "freeze"]
trait Freeze {}
#[lang = "copy"]
trait Copy {}

extern "rust-intrinsic" {
    fn r#try(f: fn(*mut u8), data: *mut u8, local_ptr: *mut u8) -> i32;
}

pub unsafe extern "C" fn __rust_maybe_catch_panic(f: fn(*mut u8), data: *mut u8) -> i32 {
    let mut payload = 0 as *mut u8;
    r#try(f, data, &mut payload as *mut _ as *mut _)
}
```

```llvm
; ModuleID = 'test.3a1fbbbh-cgu.0'
source_filename = "test.3a1fbbbh-cgu.0"
target datalayout = "e-m:e-p:32:32-i64:64-n32:64-S128"
target triple = "wasm32-unknown-emscripten"

; test::__rust_maybe_catch_panic
; Function Attrs: nounwind uwtable
define hidden i32 @_ZN4test24__rust_maybe_catch_panic17heef02838888a0db2E(void (i8*)* nocapture nonnull %f, i8* %data) unnamed_addr #0 {
start:
  %payload = alloca i8*, align 4
  %0 = bitcast i8** %payload to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* nonnull %0)
  store i8* null, i8** %payload, align 4
  %1 = call fastcc i32 @__rust_try(void (i8*)* %f, i8* %data, i8* nonnull %0) #1
  call void @llvm.lifetime.end.p0i8(i64 4, i8* nonnull %0)
  ret i32 %1
}

; Function Attrs: nounwind
define internal fastcc i32 @__rust_try(void (i8*)* nocapture nonnull, i8*, i8* nocapture) unnamed_addr #1 personality i32 (...)* @rust_eh_personality {
entry-block:
  invoke void %0(i8* %1)
          to label %then unwind label %catch

then:                                             ; preds = %entry-block
  ret i32 0

catch:                                            ; preds = %entry-block
  %3 = landingpad { i8*, i32 }
          catch i8* null
  %4 = extractvalue { i8*, i32 } %3, 0
  %5 = bitcast i8* %2 to i8**
  store i8* %4, i8** %5, align 4
  ret i32 1
}

declare i32 @rust_eh_personality(...) unnamed_addr #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #3

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #3

attributes #0 = { nounwind uwtable "target-cpu"="generic" }
attributes #1 = { nounwind }
attributes #2 = { "target-cpu"="generic" }
attributes #3 = { argmemonly nounwind }
```

**Comment by alexcrichton** [comment]
I believe there's it's the `"target-cpu"="generic"` business, the `__rust_try` intrinsic doesn't have that attribute but the `_ZN4test24__rust_maybe_catch_panic17heef02838888a0db2E` function does, meaning LLVM can't inline it.

This is likely due to the fact that `__rust_try` is a bit of a hack and not well integrated with the rest of the function-creation in rustc? There's likely just a missing call to "apply the default attributes to this newly created LLVM function" somewhere, or there's some wrapper we should be calling that we aren't.

**Comment by Amanieu** [comment]
That seems to have done the trick, thanks!

**Comment by Amanieu** [comment]
I can't reproduce these test failures locally.

**Comment by Mark-Simulacrum** [comment]
The failures are aborts (AFAICT) -- https://stackoverflow.com/questions/8177152/what-is-the-cause-of-this-application-has-requested-the-runtime-to-terminate-it.

I've rebased on latest master and enabled the mingw builder for try builds, so let's fire that up and see if we can reproduce (will help to confirm if it's just these tests or something else):

@bors try

**Comment by Mark-Simulacrum** [comment]
Interesting. The same tests fail in the new PR; that to me suggests that there's something about these specific tests that distinguishes them from other tests and causes us to hit an abort that we would not otherwise hit.

I'm not sure what that distinguishing feature is though. Maybe we're copying the exception or hitting a fatal error, and no other test does that? The tests don't seem to have much in common...

**Comment by Mark-Simulacrum** [comment]
It looks like the failing tests are due to `FatalError.raise()` being called (likely some other conditions also need to be true, since just that alone seems unlikely to have caused so few failures).

That boils down to `std::panic::resume_unwind(Box::new(FatalErrorMarker))`, but at least on Linux that seems to run just fine. I suspect that due to mingw having a custom panic resuming interface (see eh_unwind_resume lang item in libpanic_unwind/gcc.rs, and that interacting with codegen here: https://github.com/rust-lang/rust/blob/dee12bb2b7d75cce8fc8f21b5d7ea0da920df5e5/src/librustc_codegen_ssa/mir/block.rs#L173-L190) we might be generating the wrong thing.

I will try to figure out if that's accurate shortly.

**Comment by Mark-Simulacrum** [comment]
Certainly this code seems suspicious (I can't find any initialization for the pointer we're passing in, which is weird...). But it also doesn't seem like it would be affected by this PR.

I've pushed up a commit which should give us a try build for mingw for local inspection.

@bors try

**Comment by Mark-Simulacrum** [comment]
@bors try

Hm, I had built x86_64-pc-windows-gnu, but the test failures occur in i686-pc-windows-gnu, so let's try that instead.

On the x86_64-pc-windows-gnu build, I do get different behavior with this branch (vs. nightly); this branch hangs after printing the error on ui\issues\issue-62480.rs but before "aborting due to the error" is printed. On nightly everything works as expected.

We hang in 100% CPU usage pretty much.

I've not yet been able to collect a backtrace, but we appear to have 6 threads running:

```
  Id   Target Id         Frame
* 6    Thread 6420.0x20c 0x00007ffc96714143 in TlsGetValue () from C:\Windows\System32\KernelBase.dll
  5    Thread 6420.0x1980 0x00007ffc989002c2 in ntdll!RtlCaptureContext () from C:\Windows\SYSTEM32\ntdll.dll
  4    Thread 6420.0x1934 0x00007ffc988ffa54 in ntdll!ZwWaitForWorkViaWorkerFactory ()
   from C:\Windows\SYSTEM32\ntdll.dll
  3    Thread 6420.0x1930 0x00007ffc988ffa54 in ntdll!ZwWaitForWorkViaWorkerFactory ()
   from C:\Windows\SYSTEM32\ntdll.dll
  2    Thread 6420.0x1938 0x00007ffc988ffa54 in ntdll!ZwWaitForWorkViaWorkerFactory ()
   from C:\Windows\SYSTEM32\ntdll.dll
  1    Thread 6420.0x1910 0x00007ffc988fc144 in ntdll!ZwWaitForSingleObject () from C:\Windows\SYSTEM32\ntdll.dll
```

**Comment by Mark-Simulacrum** [comment]
With the i686 mingw dist build, I can reproduce the exit code 3 (and `break abort` in gdb does indeed break). Unfortunately, I did not include debugging information in the built binary (latest push does that), so getting any sort of stack trace is impossible. I can't even get symbols to resolve, possibly because `abort` is too late, not sure.

Let's kick off a build with debug-assertions and also debuginfo compiled in. @bors try

**Comment by Mark-Simulacrum** [comment]
std::bad_alloc on the rustdoc build, so we'll have to push again I guess. @bors try

**Comment by Mark-Simulacrum** [comment]
Collected a stack trace finally:


```
#0  0x63dfb32c in abort () from c:\Users\User\.rustup\toolchains\pr-i686\bin\std-9599a4456ee51be2.dll
#1  0x63df3b76 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x3372c908, context=context@entry=0x30f4a2a0)
    at C:/mingw630/src/gcc-6.3.0/libgcc/unwind.inc:71
#2  0x63df4295 in _Unwind_Resume (exc=0x3372c908) at C:/mingw630/src/gcc-6.3.0/libgcc/unwind.inc:230
#3  0x63dbda3b in rust_eh_unwind_resume () at src\libpanic_unwind/gcc.rs:336
#4  0x00f5e8cc in call_once<closure-1,()> ()
    at /rustc/4cafb6ef1e23c279188bb99e76abde35e7a3a1ee\src\libcore\ops/function.rs:232
#5  call_once<(),closure-1> () at /rustc/4cafb6ef1e23c279188bb99e76abde35e7a3a1ee\src\libstd/panic.rs:318
#6  do_call<std::panic::AssertUnwindSafe<closure-1>,()> ()
    at /rustc/4cafb6ef1e23c279188bb99e76abde35e7a3a1ee\src\libstd/panicking.rs:306
#7  try<(),std::panic::AssertUnwindSafe<closure-1>> ()
    at /rustc/4cafb6ef1e23c279188bb99e76abde35e7a3a1ee\src\libstd/panicking.rs:282
#8  std::panic::catch_unwind::h3b983688f69fc937 ()
    at /rustc/4cafb6ef1e23c279188bb99e76abde35e7a3a1ee\src\libstd/panic.rs:394
#9  0x00f278ec in {{closure}} () at src\librustc_interface/passes.rs:802
```

**Comment by Mark-Simulacrum** [comment]
https://gist.github.com/Mark-Simulacrum/14d4764787f92658130a87d0f0c597d0#file-unwind-inc-L71 is the line in gcc sources where the error occurs.

`exception` is a Rust exception, and we appear to be in rust_eh_unwind_resume at the point where the assertion fires. I *think* this is because there isn't a personality function associated with rust_eh_unwind_resume, but I'm not sure why that is yet, or whether that's actually the problem.


```
(gdb) p *exc
$6 = {exception_class = 5570770221508416340, exception_cleanup = 0x63dbd9d0 <panic_unwind::imp::panic::exception_cleanup::hd6e63ba84da803f2>, private_1 = 0,
  private_2 = 821273408}

(gdb) p fs.personality
$8 = (_Unwind_Personality_Fn) 0x0

(gdb) p fs
$7 = {regs = {reg = {{loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0,
          offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0},
        how = REG_UNSAVED}, {loc = {reg = 4294967288, offset = -8, exp = 0xfffffff8 <Address 0xfffffff8 out of bounds>}, how = REG_SAVED_OFFSET}, {loc = {reg = 0,
          offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 4294967292, offset = -4,
          exp = 0xfffffffc <Address 0xfffffffc out of bounds>}, how = REG_SAVED_OFFSET}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {
          reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0,
          exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED},
      {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED}, {loc = {reg = 0, offset = 0,
          exp = 0x0}, how = REG_UNSAVED}}, prev = 0x0, cfa_offset = 8, cfa_reg = 5, cfa_exp = 0x0, cfa_how = CFA_REG_OFFSET},
  pc = 0x63dbda33 <rust_eh_unwind_resume+3>, personality = 0x0, data_align = -4, code_align = 1, retaddr_column = 8, fde_encoding = 0 '\000',
  lsda_encoding = 255 'ÿ', saw_z = 1 '\001', signal_frame = 0 '\000', eh_ptr = 0x0}
```

**Comment by Amanieu** [comment]
Can you check if there are multiple instances of `rust_eh_unwind_resume` linked in? One issue that may happen on mingw is that there is more than one instance of libgcc linked in. We need to make sure that all our unwinding calls go to the same instance since that's where our per-dll unwinding tables are registered (see src/rtstartup).

**Comment by Mark-Simulacrum** [comment]
There are definitely multiple plausible copies in the dlls, AFAICT -- we don't seem to try to deduplicate?

```
$ echo bin/* | xargs -t -n1 nm | grep eh_unwind_resume
nm bin/rustc.exe
00407158 I __imp__rust_eh_unwind_resume
00402800 T _rust_eh_unwind_resume
nm bin/rustc_driver-fc08709b84753354.dll
71ef967c I __imp__rust_eh_unwind_resume
6b1a02b0 T __ZN103_$LT$rustc_codegen_llvm..context..CodegenCx$u20$as$u20$rustc_codegen_ssa..traits..misc..MiscMethods$GT$16eh_unwind_resume17h4bd7c5b14aa34d6dE
6d62b0c0 T __ZN5rustc6middle10lang_items13LanguageItems16eh_unwind_resume17h6f4bf1c2e5df29a9E
6da06908 T _rust_eh_unwind_resume
nm bin/rustc_macros-d007b079729ef5b9.dll
6b6fe7e0 T _rust_eh_unwind_resume
nm bin/rustdoc.exe
00a2b514 I __imp__rust_eh_unwind_resume
007edd50 T _rust_eh_unwind_resume
nm bin/std-9599a4456ee51be2.dll
63dbda30 T _rust_eh_unwind_resume
nm bin/test-dea5816d14450ea2.dll
6bdb56c0 I __imp__rust_eh_unwind_resume
6bd54a44 T _rust_eh_unwind_resume
```

`gdb` reports the folllowing when the abort triggers. That suggests there's 3 instances of that function, I think, though I'm not sure.

```
(gdb) info functions rust_eh_unwind_resume
All functions matching regular expression "rust_eh_unwind_resume":

File src\libpanic_unwind/gcc.rs:
void rust_eh_unwind_resume();

Non-debugging symbols:
0x00402800  rust_eh_unwind_resume
0x03ad6908  rust_eh_unwind_resume
0x6bd54a44  rust_eh_unwind_resume
```

If I'm following you correctly, though, this is fine, as there's 3 dlls in play here (rustc_driver, std, and test). I don't really understand the registration logic (AFAICT, we're not putting rust_eh_unwind_resume in that registration logic in anyway, but maybe there's some code I'm missing?)

**Comment by Mark-Simulacrum** [comment]
Oh, and here's a list of the libraries we have loaded. AFAICT, it only contains one gcc... unless a gcc is embedded in one of our DLLs.

```
(gdb) info sharedlibrary
From        To          Syms Read   Shared Object Library
0x778f0000  0x779b47b0  Yes (*)     C:\Windows\SysWOW64\kernel32.dll
0x77b31000  0x77d2bfd0  Yes (*)     C:\Windows\SysWOW64\KernelBase.dll
0x75611000  0x756ce764  Yes (*)     C:\Windows\SysWOW64\msvcrt.dll
0x63d81000  0x640651b0  Yes         c:\Users\User\.rustup\toolchains\pr-i686\bin\std-9599a4456ee51be2.dll
0x762c1000  0x76338ac4  Yes (*)     C:\Windows\SysWOW64\advapi32.dll
0x77581000  0x775f5360  Yes (*)     C:\Windows\SysWOW64\sechost.dll
0x769c1000  0x76a7af78  Yes (*)     C:\Windows\SysWOW64\rpcrt4.dll
0x755f1000  0x7560f10c  Yes (*)     C:\Windows\SysWOW64\sspicli.dll
0x755e1000  0x755e93b8  Yes (*)     C:\Windows\SysWOW64\cryptbase.dll
0x77d41000  0x77d9e28c  Yes (*)     C:\Windows\SysWOW64\bcryptprimitives.dll
0x76101000  0x7615de0c  Yes (*)     C:\Windows\SysWOW64\ws2_32.dll
0x75141000  0x7515ded8  Yes (*)     C:\Windows\SysWOW64\userenv.dll
0x77a11000  0x77b2e964  Yes (*)     C:\Windows\SysWOW64\ucrtbase.dll
0x75841000  0x75856b80  Yes (*)     C:\Windows\SysWOW64\profapi.dll
0x00ec1000  0x0844b6ac  Yes         c:\Users\User\.rustup\toolchains\pr-i686\bin\rustc_driver-fc08709b84753354.dll
0x77471000  0x77566d54  Yes (*)     C:\Windows\SysWOW64\ole32.dll
0x6eb41000  0x6eb617d0  Yes (*)     c:\Users\User\.rustup\toolchains\pr-i686\bin\libgcc_s_dw2-1.dll
0x6bd01000  0x6bdc0fac  Yes         c:\Users\User\.rustup\toolchains\pr-i686\bin\test-dea5816d14450ea2.dll
0x75e81000  0x760f5748  Yes (*)     C:\Windows\SysWOW64\combase.dll
0x64b41000  0x64b5254c  Yes (*)     c:\Users\User\.rustup\toolchains\pr-i686\bin\libwinpthread-1.dll
0x77381000  0x773a01f4  Yes (*)     C:\Windows\SysWOW64\gdi32.dll
0x76a81000  0x76a96a34  Yes (*)     C:\Windows\SysWOW64\win32u.dll
0x76161000  0x762b9bb4  Yes (*)     C:\Windows\SysWOW64\gdi32full.dll
0x76c41000  0x76cbb608  Yes (*)     C:\Windows\SysWOW64\msvcp_win.dll
0x776e1000  0x7787606c  Yes (*)     C:\Windows\SysWOW64\user32.dll
0x76aa1000  0x76b31f20  Yes (*)     C:\Windows\SysWOW64\oleaut32.dll
0x77601000  0x77605064  Yes (*)     C:\Windows\SysWOW64\psapi.dll
0x76e01000  0x77379040  Yes (*)     C:\Windows\SysWOW64\shell32.dll
0x764b1000  0x764eaf1c  Yes (*)     C:\Windows\SysWOW64\cfgmgr32.dll
0x76cc1000  0x76d43f0c  Yes (*)     C:\Windows\SysWOW64\SHCore.dll
0x75861000  0x75e24584  Yes (*)     C:\Windows\SysWOW64\windows.storage.dll
0x75e31000  0x75e72040  Yes (*)     C:\Windows\SysWOW64\powrprof.dll
0x77571000  0x7757c3e8  Yes (*)     C:\Windows\SysWOW64\umpdc.dll
0x77611000  0x7765362c  Yes (*)     C:\Windows\SysWOW64\shlwapi.dll
0x77da1000  0x77dae45c  Yes (*)     C:\Windows\SysWOW64\kernel.appcore.dll
0x764f1000  0x76502824  Yes (*)     C:\Windows\SysWOW64\cryptsp.dll
0x779e1000  0x77a04370  Yes (*)     C:\Windows\SysWOW64\imm32.dll
(*): Shared library is missing debugging information.
```

**Comment by mati865** [comment]
`gcc_eh` is statically linked but not literally embedded: https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/libunwind/build.rs#L36

**Comment by Amanieu** [comment]
Can you give me a link to download the toolchain produced by bors try? I'd like to have a go.

The real `_rust_eh_unwind_resume` implementation should be in the libstd dll, which contains an embedded static copy of libgcc. If you disassemble the others, they should just be simple linker-generated redirector functions which point to the implementation in libstd.

Based on the location of the assert failure, I can conclude that `fs.personality` did point to some personality function during phase 1 unwinding (since that's the only way to initialize `private_2`), but it was NULL during phase 2. This means that either `uw_frame_state_for` returned a different result between phase 1 and phase 2 (which could happen if 2 different instances of libgcc were used for each phase), or for some reason the `_Unwind_Context` was different between phase 1 and phase 2, which could be caused by a misbehaving personality function or also because 2 different instances of libgcc were used.

**Comment by Mark-Simulacrum** [comment]
`rustup-toolchain-install-master -i i686-pc-windows-gnu 4cafb6ef1e23c279188bb99e76abde35e7a3a1e` is what I've been using (https://crates.io/crates/rustup-toolchain-install-master); you can run that on a non-windows computer too to get the raw URLs needed, though they will be tar.xz files by default I believe.

I've been using the windows free VMs (as mentioned above), and the backtrace above was via msys, on the ui\issues\issue-62480.rs test.

**Comment by Mark-Simulacrum** [comment]
All 3 of the rust_eh_unwind_resume appear to be indirect jumps:

```
(gdb) info functions rust_eh_unwind_resume
All functions matching regular expression "rust_eh_unwind_resume":

File src\libpanic_unwind/gcc.rs:
void rust_eh_unwind_resume();

Non-debugging symbols:
0x00402800  rust_eh_unwind_resume
0x03b16908  rust_eh_unwind_resume
0x6bd54a44  rust_eh_unwind_resume
(gdb) disassemble 0x00402800
Dump of assembler code for function rust_eh_unwind_resume:
   0x00402800 <+0>:     jmp    *0x407158
   0x00402806 <+6>:     nop
   0x00402807 <+7>:     nop
End of assembler dump.
(gdb) disassemble 0x03b16908
Dump of assembler code for function rust_eh_unwind_resume:
   0x03b16908 <+0>:     jmp    *0x800967c
   0x03b1690e <+6>:     nop
   0x03b1690f <+7>:     nop
End of assembler dump.
(gdb) disassemble 0x6bd54a44
Dump of assembler code for function rust_eh_unwind_resume:
   0x6bd54a44 <+0>:     jmp    *0x6bdb56c0
   0x6bd54a4a <+6>:     nop
   0x6bd54a4b <+7>:     nop
End of assembler dump.
```

I didn't yet attempt to recursively follow.

**Comment by Amanieu** [comment]
The one in rustc_macros-d007b079729ef5b9.dll looks suspicious because it seems to be missing the __imp_ symbol, which might imply that it isn't an indirect jump. However it seems that the rustc_macros dll isn't actually loaded by the compiler, so that can't be the problem.

**Comment by Amanieu** [comment]
OK I understand what the problem is. Basically the problem is that `_Unwind_Resume` expects to be called directly by the relevant landing pad, but we call it via a wrapper function called `rust_eh_unwind_resume`. `_Unwind_Resume` notices this because it uses the current context to resume unwinding, which means we have an extra frame added on that shouldn't be there.

This is clearly wrong and I don't know why it was working fine previously.

However the solution may not be as simple as just calling `_Unwind_Resume` directly because there may potentially be multiple instances of libgcc in the process (for example for rustc there's one embedded in the libstd dll and as well as a separate libgcc dll). We need to make sure that the instance of `_Unwind_Resume` called is the one in the libstd dll since that's where our frame information is registered by the startup code.

However this may not be necessary: we should first try setting `custom_unwind_resume` in the target spec to false and see if that resolves the issue.

**Comment by Mark-Simulacrum** [comment]
Is there something I can trace to check if two gccs are present? As far as I can tell, that's not the case (loaded shared libraries do not contain a unwinding gcc, I believe).

(Generally I'm not sure what next steps are).

**Comment by Amanieu** [comment]
Ah actually I do have a theory as to why this was working fine previously: the only frame in which the assert triggers is the call to `rust_eh_unwind_resume` in `__rust_maybe_catch_panic`. Since both are in the same crate (libpanic_unwind), the call was inlined to call `_Unwind_Resume` directly, this avoiding the assert.

**Comment by Mark-Simulacrum** [comment]
The PR adding the custom_unwind_resume specifically did so to ensure that libstd's gcc (i.e. the one we registered with) is the one that got called, I believe (https://github.com/rust-lang/rust/pull/29177).

I've pushed up a build that disabled the custom unwinding for now though, let's see if it works: @bors try

**Comment by Amanieu** [comment]
If it turns out that we really do need `rust_eh_unwind_resume`, then we might be able to get away with implementing it as a naked function which directly jumps to `_Unwind_Resume`. I don't think there is any other way of getting a guaranteed tail call.

**Comment by Mark-Simulacrum** [comment]
I think it may be then easier to, in codegen (https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/context.rs#L409), make sure that in the custom unwind case that we're considering here we use the extern function `_Unwind_Resume` which has the same ABI I believe.

I guess that might not work though as we'd not necessarily use the right _Unwind_Resume.

**Comment by Amanieu** [comment]
That's already what the [default](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_ssa/mir/block.rs#L181) implementation does. We only need the `custom_unwind_resume` hack if we are calling a different function than `_Unwind_Resume`.

**Comment by Amanieu** [comment]
Incidentally, `custom_eh_unwind_resume` is only needed on i686 mingw, not x86_64. The latter does not rely on runtime registration for unwind so it is fine if a different libgcc unwinder is used halfway through the unwinding process.

**Comment by alexcrichton** [comment]
If this is indeed the solution it probably worked before because the function was always I lined I to the only try block in rust, since it was always in the same crate. I suspect we never tested debug mode where inlining didn't happen.

If this ends up working, can the personality be online always instead of mucking around with naked functions?

**Comment by Amanieu** [comment]
I'm hitting a roadblock with the naked function solution: during LTO, LLVM will look at the implementation of the naked function and conclude that it cannot unwind (since `asm!` can't unwind). Therefore it will conclude that since the drop landing pads never return and never unwind, the catch clause is unreachable and can be optimized away. This is clearly wrong (LLVM shouldn't be making any assumptions about the contents of naked functions) but at this point it may be too much trouble.

I'm looking into 2 alternative solutions:
- `#[inline(always)]` which I tried earlier but resulted in undefined symbols.
- Using `_Unwind_Resume` directly instead of going through a wrapper, but this may end up calling the wrong instance of `_Unwind_Resume` if we have multiple libgccs in the process in different DLLs.

**Comment by Amanieu** [comment]
@alexcrichton @Mark-Simulacrum I'm running out of ideas here, I'm not sure how to solve this issue. I've tried 3 options:
- Making `rust_eh_unwind_resume` `#[inline(always)]` doesn't seem to work: it is not getting inlined in some places (libcore?) which results in linker errors with an undefined symbol.
- Implementing `rust_eh_unwind_resume` as a naked function doesn't work because LLVM sees an inline asm statement and assumes that the asm can't unwind. ([naked branch](https://github.com/rust-lang/rust/compare/master...Amanieu:opt-catch-naked))
- Disabling the custom unwind resume and calling `_Unwind_Resume` directly doesn't seem to work since it leads to undefined reference linker errors. I haven't looked at this case in detail yet.

**Comment by Mark-Simulacrum** [comment]
Instead of the shim function, is there some way we can "re-export" the `_Unwind_Resume` specifically from std's linked gcc? Ideally we'd do so under a different name (perhaps `_rust_eh_unwind_resume`). It seems like we should definitely be able to insert some custom compiler logic to make this happen, but maybe it gets into too low-level details to be feasible.

We do seem to have *some* logic for similar functions though, so maybe adding to this list will solve the linker issue? https://github.com/Mark-Simulacrum/rust/blob/420e735f24e93a739a7305ac73b9a7a5775ee50c/src/librustc_codegen_ssa/back/symbol_export.rs#L113-L127

A random thought that I had while looking at this is to stick `#[export_name = "rust_eh_unwind_resume"]` on the `extern` block importing _Unwind_Resume, but I suspect that won't just work.

**Comment by alexcrichton** [comment]
I wouldn't touch naked functions with a 10 foot pole, so I can't really help out with debugging that. For `#[inline(always)]` I suspect that the reference to `rust_eh_unwind_resume` isn't done in a conventional manner like the rest of the compiler meaning that the auto-inlining logic of the compiler probably isn't happening which probably causes undefined symbols. I suspect that if this solution is pursued the generation of an LLVM function object from the `DefId` needs to be fixed and/or updated to happen in a more conventional way with respect to the rest of the codegen backend.

For calling `_Unwind_Resume` directly I would have to inspect the linker errors. Sorry I don't have a ton of time to pore over logs right now for this, though, so I will be of limited utility.

**Comment by Amanieu** [comment]
Here is the reason why trying to use `_Unwind_Resume` directly results in linker errors: https://gcc.gnu.org/ml/gcc/2012-03/msg00104.html

Basically we are statically link libgcc_eh.a which is only really supported for statically linked applications. However we do this for rustc which is split into several modules (libstd.dll, librustc_driver.dll, rustc.exe), and since the libgcc_eh.a symbols are not exported they are only accessible from within libstd.dll.

All of this hackery was done to avoid having Rust binaries depend on libgcc_s.dll, which is the proper way of supporting unwinding on MinGW.

Regarding `#[inline(always)]` I don't see how this could possibly work since libcore/liballoc (and others) are compiled *before* libpanic_unwind, which contains the actual definition of `rust_eh_unwind_resume`.

**Comment by Mark-Simulacrum** [comment]
@Amanieu not sure about the compiler-internal interactions, but it at least looks on the surface like `pub use _Unwind_Resume as rust_eh_unwind_resume` works -- https://rust.godbolt.org/z/pvQsf9. That's not cross crate but at least seems to have the right codegen. Notably, it does not happen even with opt-level=3 with the regular "just a function" approach (https://rust.godbolt.org/z/dGFeso).

Did you try this as well?

@bors try

**Comment by Amanieu** [comment]
I wasn't aware that it was possible to use `#[lang]` on a re-export...

**Comment by Mark-Simulacrum** [comment]
Seems it isn't that trivial. I've tried moving it onto the `Unwind_Resume` declaration in the extern "C" block, but I expect that probably won't work either.

It does seem like we should be able to associate the resumption LLVM declaration directly with the `_Unwind_Resume`, though. To be honest, I would've expected the call to get erased/inlined, anyway...

**Comment by Amanieu** [comment]
I think you should try removing the lang item entirely and have rustc import the symbol by name instead.

**Comment by Mark-Simulacrum** [comment]
Hm, that seems like it can't possibly work unless I'm missing something? i.e., we need to import the symbol specifically in libpanic_unwind, otherwise the linkage doesn't work out.

And/or, if that did work, then we could forgo the lang item and the custom logic entirely, and that would work too, which we've tried and that doesn't work?

**Comment by Amanieu** [comment]
You need to change the code in rustc that emits calls to `rust_eh_unwind_resume` to load the function pointer first.

**Comment by Mark-Simulacrum** [comment]
I think it may work out in practice (though I'm not sure) -- the code already calls `Instance::resolve` on the lang item which looks like it internally may (or may not, realistically) do the right thing.

@bors try

**Comment by Mark-Simulacrum** [comment]
@bors try

Okay, looks like we do need to load the static, trying this now which I believe does that (though completely stole the code from elsewhere, I'm not actually really sure what it's doing).

**Comment by Amanieu** [comment]
You'll need to fix all the `#[lang = "eh_unwind_resume"]` in src/test.

**Comment by Mark-Simulacrum** [comment]
Yes, I'm working on a blessing of that locally, wanted to get the dist build going though (and, in theory, even with other tests being broken we should be able to see if the aborts are still happening).

**Comment by Mark-Simulacrum** [comment]
Okay I'm not sure how to proceed from here.

I've pushed up a commit that fixes up the tests, but the codegen is still broken. I don't know how to load up the function pointer from the static and then call it.  AFAICT, there's code that does the same thing I'm doing, but I could easily be misinterpreting. Specifically, https://github.com/Mark-Simulacrum/rust/blob/opt-catch/src/librustc_codegen_llvm/context.rs#L409-L412 is leading to an assertion failure in LLVM it seems (see cutout below, also full [log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/19723/logs/55)).

I'm guessing I'm doing something wrong, but I'm struggling to find similar code in _ssa or _llvm, so not sure how to make progress. I'm not sure who on T-compiler to ask too, so I've posted a link to this comment to Zulip.

```
2020-01-30T14:28:57.5035790Z Program: D:\a\1\s\build\i686-pc-windows-gnu\stage1\bin\rustc.exe
2020-01-30T14:28:57.5036268Z File: D:/a/1/s/src/llvm-project/llvm/lib/IR/Value.cpp, Line 67
2020-01-30T14:28:57.5036426Z
2020-01-30T14:28:57.5036681Z Expression: (VTy->isFirstClassType() || VTy->isVoidTy()) && "Cannot create non-first-class values except for constants!" 
```

**Comment by bjorn3** [comment]
`cx.get_static` returns a pointer to the static. You have to dereference that pointer to get the static value.

**Comment by Mark-Simulacrum** [comment]
hm, okay, I've added some ad-hoc code that I think does that (we'll want to move it into eh_unwind_resume probably)

@bors try

**Comment by Mark-Simulacrum** [comment]
@bors try

Okay, I think the tests pass now (I think the timeouts are spurious, mostly down to debug assertions taking too long in practice). I have rebased atop master just in case, and also squashed CI commits in and rearranged commits a bit. If this try build succeeds, it should produce artifacts for mingw 32-bit for testing (if we choose to test) and also run the mingw 64-bit and 32-bit tests. That should be sufficient to ensure that we have full coverage of the known bug space.

Hopefully, everything goes well and then we can hand this off for review (given the changes to codegen, it probably makes sense to do another review pass).

**Comment by Mark-Simulacrum** [comment]
Timeouts appear non-spurious. I've updated the tests to have aborts instead of `loop {}` which will hopefully cause us to at least not timeout...

@bors try

**Comment by Mark-Simulacrum** [comment]
(Rebased). I am currently at a loss to explain the timeouts -- AFAICT, none of the code would lead to (presumably) infinite looping and a few tests locally also don't seem to do so.

My current suspicion (though without any data to support it) is that somehow calling via function pointer is leading to infinitely looping (e.g., we unwind incorrectly) specifically on CI, but I'm not really sure how that would be possible. Maybe having the load instruction from the static in that code is not allowed?

**Comment by Amanieu** [comment]
So I couldn't test this on i686 because the compiler OOMed, but I did manage to reproduce the infinite loops on x86_64. `_Unwind_Resume` is getting called correctly, but it doesn't seem to be actually stepping up a frame for some reason. It keeps unwinding to the same frame every time.

I suspect that the SEH metadata for the function isn't getting set up correctly, and LLVM gets confused due to the lack of a `resume` instruction. However this doesn't explain the failures on i686, since that doesn't use SEH at all...

**Comment by Amanieu** [comment]
OK, I see what the root problem is now: when LLVM inlines functions it needs to perform some transformations on `resume` to "flatten" them. These transformations aren't being done because of our hack to replace `resume` with a function call, which breaks functions which contain both `resume` and `catch` due to inlining.

**Comment by Amanieu** [comment]
So basically:
- We have to use LLVM's `resume` instruction, otherwise inlining breaks.
- This means that we must provide a `_Unwind_Resume` symbol.
- The `_Unwind_Resume` in libgcc_eh is not marked `dllexport`, so it will only work for the current dll (std.dll).
- The `rust_eh_unwind_resume` hack is broken in multiple ways, and has so far only worked because `__rust_try` has been invisible to inlining across dll boundaries.

At this point I think we are spending way too much effort on this, when the proper (and officially supported by MinGW) solution is to just link against libgcc_s_dw2-1.dll. How much of a breaking change would it be for Rust executables for the windows-gnu targets to once again start depending on libgcc_s_dw2-1.dll? As a bonus, this will also fix cross-language exceptions across DLL boundaries on i686-pc-windows-gnu.

**Comment by Amanieu** [comment]
cc @vadimcn for my last comment

**Comment by vadimcn** [comment]
IMO, the "proper fix" would be to remove LLVM's assumption about what symbol the resume instruction resolves to.

> At this point I think we are spending way too much effort on this, when the proper (and officially supported by MinGW) solution is to just link against libgcc_s_dw2-1.dll. How much of a breaking change would it be for Rust executables for the windows-gnu targets to once again start depending on libgcc_s_dw2-1.dll? 

You'll need to ask users.  Some people were pretty adamant about having to distribute this an dll with their programs, as I recall.

I think that in order to decide which approach should be implemented, Rust core team needs to decide how important it is for rustc toolchain to be independent from GCC.   
Back when I wrote this code, I thought the desired final outcome was to have a 100% Rust toolchain, or. at least, one that depended only on LLVM libraries and tools.  But now I've been out of this for a while, don't know which way the wind is blowing these days...

**Comment by Mark-Simulacrum** [comment]
It seems at least plausible that LLVM's _Unwind_Resume expectation might be changeable without upstream LLVM changes. I'm not all that familiar with LLVM, but it looks like if we could define our own LLVM target or get access to an existing one somewhere and call `TargetLoweringBase::setLibcallName()` on [`RTLIB::UNWIND_RESUME`](https://github.com/llvm/llvm-project/blob/af480e8c63b27ad247b8430cf124da8bcdf752f8/llvm/include/llvm/IR/RuntimeLibcalls.def#L414) then we would be able to override the symbol LLVM expects.

We could plausibly even just have a patch to our LLVM that sets a different symbol name from _Unwind_Resume in the same place I linked [above](https://github.com/llvm/llvm-project/blob/af480e8c63b27ad247b8430cf124da8bcdf752f8/llvm/include/llvm/IR/RuntimeLibcalls.def#L414).

**Comment by Amanieu** [comment]
I don't think this approach with modifying LLVM is going to work out. In particular I doubt upstream will be happy to support such a hack.

Instead, here is what I propose we do:
- Remove all the custom `eh_unwind_resume` hacks. We just use the standard `_Unwind_Resume` symbol.
- When building a statically linked `bin` or `cdylib`, statically link `libgcc_eh.a`. This should work fine since all Rust code will be able to access the private `_Unwind_Resume` symbol from libgcc.
- When building a `dylib` or with `-C prefer-dynamic`, dynamically link to `libgcc_s_dw2-1.dll`. This ensures that all Rust DLLs use a single instance of the unwinding runtime.
- Maybe add a command-line flag to force dynamically linking to libgcc, which is needed for unwinding through FFI across DLL boundaries.

This should avoid needing to package `libgcc_s_dw2-1.dll` in most cases that users will be exposed to. It will only be needed for special cases (e.g. rustc for proc macros) where the additional complexity is acceptable.

File: src/doc/unstable-book/src/language-features/lang-items.md [hunk 8]
```diff
@@ -67,7 +66,7 @@ Other features provided by lang items include:
   marked with lang items; those specific four are `eq`, `ord`,
   `deref`, and `add` respectively.
 - stack unwinding and general failure; the `eh_personality`,
-  `eh_unwind_resume`, `fail` and `fail_bounds_checks` lang items.
+  `fail` and `fail_bounds_checks` lang items.
```
Comment (bjorn3) [inline src/doc/unstable-book/src/language-features/lang-items.md]: s/fail/panic

**Comment by Amanieu** [comment]
This is finally done and ready to merge!

r? @Mark-Simulacrum

**Comment by mati865** [comment]
> Back when I wrote this code, I thought the desired final outcome was to have a 100% Rust toolchain, or. at least, one that depended only on LLVM libraries and tools.

libgcc could be replaced by compiler-rt+libunwind already but I doubt it'd change anything for this issue.

**Comment by Amanieu** [comment]
Actually the way I implemented it, you only need to dynamically link to libgcc_s-dw2-1.dll if you use dylib crates. If all the rust code is in a single DLL/EXE (which applies to `cdylib` and `bin` targets) then we link libgcc statically and don't depend on libgcc_s-dw2-1.dll.

AFAIK the only actual user of `dylib` crates is rustc to support compiler plugins, and we already ship libgcc_s-dw2-1.dll with the compiler because LLVM needs it.

I'll merge this after the next beta comes out, but cc @rust-lang/compiler and @rust-lang/libs in case anyone has objections.

TLDR: We've added a runtime dependency on libgcc_s-dw2-1.dll for compiled executables/dylibs on *-pc-windows-gnu, but only if one of our crate dependencies is a dylib (i.e. the Rust code is split across multiple DLLs). This is necessary for cross-DLL unwinding.

File: src/libpanic_unwind/seh.rs [hunk 9]
```diff
@@ -226,16 +236,16 @@ static mut TYPE_DESCRIPTOR: _TypeDescriptor = _TypeDescriptor {
 // because Box<dyn Any> isn't clonable.
 macro_rules! define_cleanup {
     ($abi:tt) => {
-        unsafe extern $abi fn exception_cleanup(e: *mut [u64; 2]) {
-            if (*e)[0] != 0 {
-                cleanup(*e);
+        unsafe extern $abi fn exception_cleanup(e: *mut Exception) {
+            if let Some(b) = e.read().data {
```
Comment (nagisa) [inline src/libpanic_unwind/seh.rs]: Nit: this is prone to diverging if anybody adds fields to `Exception`. Consider pattern matching.

File: src/librustc_codegen_llvm/intrinsic.rs [hunk 10]
```diff
@@ -1002,38 +1015,34 @@ fn codegen_msvc_try(
...
-    local_ptr: &'ll Value,
+    catch_func: &'ll Value,
     dest: &'ll Value,
 ) {
     let llfn = get_rust_try_fn(bx, &mut |mut bx| {
         // Codegens the shims described above:
         //
         //   bx:
-        //      invoke %func(%args...) normal %normal unwind %catch
+        //      invoke %func(%data) normal %normal unwind %catch
```
Comment (nagisa) [inline src/librustc_codegen_llvm/intrinsic.rs]: nit: `invoke %try_func`.

**Comment by Amanieu** [comment]
Beta has been branched, so...

@bors r=Mark-Simulacrum

File: src/libstd/panicking.rs [hunk 11]
```diff
@@ -274,27 +269,59 @@ pub unsafe fn r#try<R, F: FnOnce() -> R>(f: F) -> Result<R, Box<dyn Any + Send>>
     //
```
Comment (RalfJung) [inline src/libstd/panicking.rs]: Looks like the "2." comment above is no longer accurate? The code now does `ManuallyDrop::into_inner(data.p)` in the "panicked" case, which looks very symmetric to the "didn't panic case": in both cases we move "it out of `data` and return it", it's just a different thing we move out.

**Comment by RalfJung** [comment]
> r=Mark-Simulacrum

Now Mark is both author and reviewer of this PR. ;)

File: src/libpanic_abort/lib.rs [hunk 12]
```diff
@@ -117,16 +111,16 @@ pub mod personalities {
     //
     // Note that we don't execute landing pads, so this is never called, so it's
     // body is empty.
-    #[no_mangle]
-    #[cfg(all(target_os = "windows", target_env = "gnu"))]
+    #[rustc_std_internal_symbol]
+    #[cfg(all(bootstrap, target_os = "windows", target_env = "gnu"))]
     pub extern "C" fn rust_eh_unwind_resume() {}
```
Comment (eggyal) [inline src/libpanic_abort/lib.rs:117]: This additional requirement on `#cfg(bootstrap)]` looks as though it may be responsible for https://github.com/rust-lang/rust/issues/79609 ... not sure I understand why it was required, however ?

Comment (Amanieu) [reply src/libpanic_abort/lib.rs:117]: The compiler used to emit references to `rust_eh_unwind_resume` from codegen. But it doesn't do that any more and `rust_eh_unwind_resume` doesn't exist any more.
