### PR TITLE
Fix rust-analyzer install when not available.

### LINKED ISSUE #86999: thread 'main' panicked at 'missing rust-analyzer', src/bootstrap/install.rs:170:14
I backported the two patches from https://github.com/rust-lang/rust/pull/86568 to 1.53.0 (trying to fix #86436), but now the build fails with:
```
thread 'main' panicked at 'missing rust-analyzer', src/bootstrap/install.rs:170:14
```

According to @Mark-Simulacrum in https://github.com/rust-lang/rust/pull/86568#issuecomment-877141461:
> looks like x.py install likely needs to be similarly updated like in this PR, and that just hasn't happened yet.

### PR DESCRIPTION
**Pull request by ehuss**
This changes it so that `x.py install` won't fail if rust-analyzer isn't available. This was changed in #86568 to handle the case where installing on stable/beta, and `extended=true`, to skip rust-analyzer. But I neglected to update the install part to also ignore it.

Fixes #86999

### CODE REVIEW

**Comment by RalfJung** [comment]
The same should probably be done for Miri?

**Comment by ehuss** [comment]
Miri already checks if it isn't built ([here](https://github.com/rust-lang/rust/blob/f698cacc33f0c9148bb3bb7501087b0d37e837ec/src/bootstrap/install.rs#L182-L190)), or maybe I am misunderstanding?

**Comment by RalfJung** [comment]
I have no idea how any of that code works.^^ I just figured the nightly-only tools would all need similar changes.

In particular, even when people build with tools enabled, on beta/stable they should not get Miri. I am not sure if that is already the case or requires further changes.

**Comment by ehuss** [comment]
Ah, yea, miri was already working correctly, just rust-analyzer was out of sync.

Miri is not built for dist/install on beta/stable when tools are enabled.

**Comment by RalfJung** [comment]
Hm, but we still got bug reports until very recently from people that accidentally built Miri on stable: https://github.com/rust-lang/rust/issues/86981. So unless this changed recently, something doesn't seem to work as intended.

**Comment by ehuss** [comment]
The fix for that in #86568 is not on beta, yet.  It looks like it was tagged with beta-accepted, but was missing beta-nominated. There's a 3-stage progression (beta-nominated, beta-nominated+beta-accepted, beta-accepted). I'm not sure why Mark tagged it skipping the second stage.  I added the missing tag, hopefully it'll get picked up in the next beta rollup.

File: src/bootstrap/install.rs [hunk 1]
```diff
@@ -165,10 +165,15 @@ install!((self, builder, _config),
...
     };
     RustAnalyzer, "rust-analyzer", Self::should_build(_config), only_hosts: true, {
-        let tarball = builder
-            .ensure(dist::RustAnalyzer { compiler: self.compiler, target: self.target })
-            .expect("missing rust-analyzer");
-        install_sh(builder, "rust-analyzer", self.compiler.stage, Some(self.target), &tarball);
+        if let Some(tarball) =
+            builder.ensure(dist::RustAnalyzer { compiler: self.compiler, target: self.target })
+        {
+            install_sh(builder, "rust-analyzer", self.compiler.stage, Some(self.target), &tarball);
```
Comment (Mark-Simulacrum) [inline src/bootstrap/install.rs:171]: Hm, I think while we're at it we should do this for all of the steps in install that expect(...) the dist step. My guess is there's a similar failure caused by setting docs = false waiting to happen, for example.

Comment (ehuss) [reply src/bootstrap/install.rs:175]: Yea, good point. I surveyed the other expects and they seem safe to me. I added some comments to that effect. Though I guess that is somewhat a style issue, if you want to guard against future changes, I can add some additional skips.

File: src/bootstrap/install.rs [hunk 2]
```diff
@@ -139,11 +139,15 @@ macro_rules! install {
 
 install!((self, builder, _config),
     Docs, "src/doc", _config.docs, only_hosts: false, {
+        // `expect` should be safe, only None when config.docs is false,
+        // which is guarded in `should_run`
```
Comment (Mark-Simulacrum) [inline src/bootstrap/install.rs:143]: I think x.py install src/doc will still fail here -- the guard in the dist step is part of run(), not whether we run it by default, so it will return None even if we're not running this step by default.

**Comment by Mark-Simulacrum** [comment]
r=me with the last comment resolved (likely by similar logic to what's added for rust-analyzer)

File: src/bootstrap/install.rs (hunk 2 above)
Comment (ehuss) [reply src/bootstrap/install.rs:143]: I tested `./x.py install` locally with docs=false, and it seemed to be fine.  The guard I'm referring to is [here](https://github.com/rust-lang/rust/blob/3a24abd22fd25c836d8b4d75ff46c833f9c3934c/src/bootstrap/install.rs#L121-L124) where it expands to `run.path("src/doc").default_condition(_config.docs)`.  The `default_condition` should disable it when docs=false, correct?

Comment (ehuss) [reply src/bootstrap/install.rs]: Ah, I see.  I've added a better error message for that situation.
