### PR TITLE
Suggest to await future before ? operator

### LINKED ISSUE #61076: suggest `await` for future-related type errors
A common problem when using async-await is to forget to invoke `.await`. This often shows up as a type error, e.g. in a case like this ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef1caa955ef1aceadf33aadd348e646c)):

```rust
#![feature(async_await)]

async fn make_u32() -> u32 {
    22
}

fn take_u32(x: u32) {

}

async fn foo() {
    let x = make_u32();
    take_u32(x);
}

fn main() { }
```

currently we give a rather generic error:

```
error[E0308]: mismatched types
  --> src/main.rs:13:14
   |
13 |     take_u32(x);
   |              ^ expected u32, found opaque type
   |
   = note: expected type `u32`
              found type `impl std::future::Future`
```

it'd be nice if we could suggest adding `.await` somewhere.

### LINKED ISSUE #71811: rustc doesn't suggest missing .await before a `?`
When I compile the following code:
```
async fn fallible() -> Result<(), ()> { Ok(()) }

async fn caller() -> Result<(), ()> {
    fallible() /* mising .await */ ?;
    Ok(())
}

fn main() -> Result<(), ()> {
    futures::executor::block_on(caller())
}
```

rustc says:
```
error[E0277]: the `?` operator can only be applied to values that implement `std::ops::Try`
 --> src/main.rs:4:5
  |
4 |     fallible() /* mising .await */ ?;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `impl core::future::future::Future`
  |
  = help: the trait `std::ops::Try` is not implemented for `impl core::future::future::Future`
  = note: required by `std::ops::Try::into_result`
```

I think it should notice that the program is trying to apply `?` to a future, and suggest awaiting it.

(If there is an existing issue for this, it is not labeled `A-async-await` and `A-suggestion-diagnostics`.)

### PR DESCRIPTION
**Pull request by csmoe**
Closes https://github.com/rust-lang/rust/issues/71811
cc #61076

### CODE REVIEW

File: src/librustc_middle/hir/map/mod.rs [hunk 1]
```diff
@@ -390,11 +390,7 @@ impl<'hir> Map<'hir> {
     /// Given a `HirId`, returns the `BodyId` associated with it,
     /// if the node is a body owner, otherwise returns `None`.
     pub fn maybe_body_owned_by(&self, hir_id: HirId) -> Option<BodyId> {
-        if let Some(node) = self.find(hir_id) {
-            associated_body(node)
-        } else {
-            bug!("no entry for id `{}`", hir_id)
-        }
+        if let Some(node) = self.find(hir_id) { associated_body(node) } else { None }
```
Comment (oli-obk) [inline src/librustc_middle/hir/map/mod.rs:393]: I think this can be written as

```suggestion
        self.find(hir_id).map(associated_body)
```

but maybe you need a closure for the `map`

File: src/librustc_trait_selection/traits/error_reporting/suggestions.rs [hunk 2]
```diff
@@ -1765,6 +1776,95 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
...
+    ) {
+        debug!(
+            "suggest_await_befor_try: obligation={:?}, span={:?}, trait_ref={:?}",
+            obligation, span, trait_ref
+        );
+        let body_hir_id = obligation.cause.body_id;
+        let item_id = self.tcx.hir().get_parent_node(body_hir_id);
+
+        let mut is_future = false;
+        if let ty::Opaque(def_id, substs) = trait_ref.self_ty().kind {
```
Comment (oli-obk) [inline src/librustc_trait_selection/traits/error_reporting/suggestions.rs:1795]: it may also be a non-opaque future. Instead of searching for the future trait, you could also try to have the trait system check `trait_ref.self_ty(): Future` by using a scheme similar to clippy's `implements_trait`: https://github.com/rust-lang/rust/blob/bad3bf622bded50a97c0a54e29350eada2a3a169/src/tools/clippy/clippy_lints/src/utils/mod.rs#L323

Ideally, if there is a lot of code overlap between the clippy version and what you need, move most of this function onto `TyCtxt` and call it from both here and from clippy.

File: src/test/ui/async-await/issue-61076.rs [hunk 3]
```diff
@@ -0,0 +1,12 @@
+// edition:2018
+
+async fn foo() -> Result<(), ()> {
+    Ok(())
+}
+
+async fn bar() -> Result<(), ()> {
+    foo()?; //~ ERROR the `?` operator can only be applied to values that implement `std::ops::Try`
```
Comment (oli-obk) [inline src/test/ui/async-await/issue-61076.rs:8]: Please also add a test for manual impls of the `Future` trait
