### PR TITLE
Avoid using make_direct_deprecated() in extern "ptx-kernel"

### LINKED ISSUE #117271: nvptx "ptx-kernel" ABI (feature: abi_ptx) uses PassMode::Direct for Aggregates
It produces seemingly correct behavior. However, it needs to be switched over to a less fragile ABI handling (https://github.com/rust-lang/compiler-team/issues/672) before stabilization may happen.

@RalfJung's [comment](https://github.com/rust-lang/rust/pull/117247#issuecomment-1782361541) explains the problem and why it is considered harmless enough to allow this exception until a better solution is found.

### PR DESCRIPTION
**Pull request by bjorn3**
This method will be removed in the future as it produces a broken ABI that depends on cg_llvm implementation details. After this PR wasm32-unknown-unknown is the only remaining user of make_direct_deprecated().

Fixes https://github.com/rust-lang/rust/issues/117271
Blocks https://github.com/rust-lang/rust/issues/38788

### CODE REVIEW

File: tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs [hunk 1]
```diff
@@ -166,7 +166,7 @@ pub unsafe extern "ptx-kernel" fn f_f32_arg(_a: f32) {}
 pub unsafe extern "ptx-kernel" fn f_f64_arg(_a: f64) {}
 
 // CHECK: .visible .entry f_single_u8_arg(
-// CHECK: .param .align 1 .b8 f_single_u8_arg_param_0[1]
+// CHECK: .param .u8 f_single_u8_arg_param_0
```
Comment (bjorn3) [inline tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs:169]: I presume this has an identical ABI.

File: tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs [hunk 2]
```diff
@@ -242,22 +242,6 @@ pub unsafe extern "ptx-kernel" fn f_float_array_arg(_a: [f32; 5]) {}
 //pub unsafe extern "ptx-kernel" fn f_u128_array_arg(_a: [u128; 5]) {}
 
 // CHECK: .visible .entry f_u32_slice_arg(
-// CHECK: .param .u64 f_u32_slice_arg_param_0
-// CHECK: .param .u64 f_u32_slice_arg_param_1
+// CHECK: .param .align 8 .b8 f_u32_slice_arg_param_0[16]
```
Comment (bjorn3) [inline tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs:245]: We don't guarantee any ABI for wide pointers anyway and if this is breaks the ABI all users can be updated to pass `#[repr(C)] struct Slice<'a, T> { ptr: *const (), len: usize, _marker: PhantomData<&'a [T]> }` on the host side anyway (and preferably also the gpu side to avoid depending on the unstable ABI).

File: tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs [hunk 3]
```diff
@@ -242,22 +242,6 @@ pub unsafe extern "ptx-kernel" fn f_float_array_arg(_a: [f32; 5]) {}
...
-
-// CHECK: .visible .entry f_tuple_u32_u32_arg(
-// CHECK: .param .align 4 .b8 f_tuple_u32_u32_arg_param_0[8]
-#[no_mangle]
-pub unsafe extern "ptx-kernel" fn f_tuple_u32_u32_arg(_a: (u32, u32)) {}
-
-// CHECK: .visible .entry f_tuple_u8_u8_u32_arg(
-// CHECK: .param .align 4 .b8 f_tuple_u8_u8_u32_arg_param_0[8]
-#[no_mangle]
-pub unsafe extern "ptx-kernel" fn f_tuple_u8_u8_u32_arg(_a: (u8, u8, u32)) {}
```
Comment (bjorn3) [inline tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs:263]: Tuples don't have a stable ABI for any calling convention. And can always be replaced with structs anyway.

**Comment by bjorn3** [comment]
cc @kjetilkjeka @RDambrosio016 as target maintainers, but given that this is a tier 3 target without documentation about what the `extern "ptx-kernel"` ABI is actually supposed to be, I don't think it is worth blocking on their approval.

File: tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs (hunk 1 above)
Comment (kjetilkjeka) [reply tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs:169]: That might be correct. My worry here is that it goes against the "ptx-interoperability" docs. 

https://docs.nvidia.com/cuda/ptx-writers-guide-to-interoperability/index.html#aggregates-and-unions

Getting these kind of struct correct (per interop docs) was a big reason I couldn't get it "just right" when attempting to remove the PassMode::Direct

Comment (bjorn3) [reply tests/assembly/nvptx-kernel-abi/nvptx-kernel-args-abi-v7.rs]: The last commit reverts the ABI for this function back to what it was.

**Comment by vetleras** [comment]
I'm a colleague of Kjetil. This change does not seem to break our codebase.

**Comment by LegNeato** [comment]
> This method will be removed in the future as it produces a broken ABI that depends on cg_llvm implementation details. After this PR wasm32-unknown-unknown is the only remaining user of make_direct_deprecated().

`rust-gpu` uses this method FYI (https://github.com/Rust-GPU/rust-gpu/blob/1efb990126e15c57ade84c83f7986631b2fbbc1f/crates/rustc_codegen_spirv/src/abi.rs#L69) /cc @eddyb.

Feel free to delete this comment if this is not the right place to mention it.

**Review by wesleywiser — APPROVED** [review]
