### PR TITLE
Fix feature gating for new `try bikeshed` expressions

### LINKED ISSUE #152501: `try bikeshed $ty { … }` is not pre-expansion gated (affects beta+nightly)
The following code compiles even though it shouldn't:

```rs
fn main() {
    #[cfg(false)]
    try bikeshed () {}
}  
```

Contrary to `try { … }` it does not even issue a pre-expansion gate *warning*. For context, try blocks and some other ancient features are notoriously post-expansion gated which we can't change without breaking a large amount of crates in the ecosystem (which use the `#[cfg(feature = "nightly")]` pattern). For new syntactic forms however we *require* a pre-expansion feature gate nowadays for forward compatibility reasons. `try bikeshed $ty { … }` *is* a new syntactic form and thus should be pre-expansion gated by ~~`try_blocks`~~ `try_block_heterogeneous`.

### PR DESCRIPTION
**Pull request by scottmcm**
r? fmease
Fixes rust-lang/rust#152501

### CODE REVIEW

File: tests/ui/try-block/try-block-homogeneous-pre-expansion.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+//@ run-pass
```
Comment (lqd) [inline tests/ui/try-block/try-block-homogeneous-pre-expansion.rs]: wondering: does this need to run?

Comment (scottmcm) [reply tests/ui/try-block/try-block-homogeneous-pre-expansion.rs]: No, probably not.  You're thinking `check-pass` instead?

Comment (lqd) [reply tests/ui/try-block/try-block-homogeneous-pre-expansion.rs]: Yeah. It should be enough, right? Since this is in the frontend, it shouldn't need codegen (which is the `build-pass` variety), and check should work.

Comment (fmease) [reply tests/ui/try-block/try-block-homogeneous-pre-expansion.rs]: Indeed, `check-pass` more than suffices.

File: tests/ui/try-block/try-block-heterogeneous-pre-expansion.rs
Comment (fmease) [inline tests/ui/try-block/try-block-heterogeneous-pre-expansion.rs:1]: Usually I put test cases that ensure the feature gate happens before expansion in the dedicated `tests/ui/feature-gates/feature-gate-$FEATURE.rs` right next to the other test cases. I guess a separate test file is also fine.

**Review by fmease — APPROVED** [review]
Thanks! r=me with `build-pass` → `check-pass` @bors rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152519/5fdff787e6ef7cd4458f81e69cbb4d2a39439a98..4a3bf53b921caf7bbc6d2e36c3a38ddfd10f8f96)*

File: tests/ui/try-block/try-block-heterogeneous-pre-expansion.rs
Comment (scottmcm) [reply tests/ui/try-block/try-block-heterogeneous-pre-expansion.rs:1]: Ah, I wasn't sure that both in the same file worked.  If that's normal, then great, I'd rather not have another file.

I kept the homogeneous one in the separate file because the warning seems to only be there when the error didn't happen earlier (which is good).

**Review by fmease — APPROVED** [review]
Thanks! @bors r+

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152519/bb8b30a5fce59f5d3d17a8f010601c59f0f19d79..6afebcc4dd5f4e4b3a7d117aa7dcdd38f560d5af)*
