### PR TITLE
Tweak mismatched types error

### LINKED ISSUE #51767: expected (), found usize, while really this is the other way around
When playing around in the playground, I found an error message that was kind of strange for the situation:

```Rust
fn main() {
    [(); loop { break; } ]    
}
```

The error message is as follow:
```
  Compiling playground v0.0.1 (file:///playground)
error[E0308]: mismatched types
 --> src/main.rs:2:17
  |
2 |     [(); loop { break; } ]    
  |                 ^^^^^ expected (), found usize
  |
  = note: expected type `()`
             found type `usize`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

playground link: https://play.rust-lang.org/?gist=c6caaee68d6886fce7e3f0af324f5338&version=nightly&mode=debug
The error message would make more sense if described as `Expected usize, found ()`, or just not permit `loop {}` constructs at all at the place of the length of an array.

### LINKED ISSUE #62677: e0308 possibly confusing error message
I got the following error today:

```
error[E0308]: mismatched types
  --> src/util.rs:13:33
   |
13 |     fn from_str(input: &str) -> Result<Self, Self::Err> {
   |        --------                 ^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found ()
   |        |
   |        this function's body doesn't return
   |
   = note: expected type `std::result::Result<util::Color, &'static str>`
              found type `()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

I think the note `this function's body doesn't return` is misleading - I thought that the issue was that an inner method I was calling had an infinite loop, or returned `!` some other way, but it doesn't mean this, it actually means "this function's body doesn't return **a value**". Maybe the error message could be changed?

### LINKED ISSUE #63136: "match arms have incompatible types" hint incorrect
> this and all prior arms are found to be of type `!`

Only some of the prior arms are of type `!`, the rest is of type `FloatCC`.

```
error[E0308]: match arms have incompatible types
  --> src/llvm_intrinsics.rs:77:33
   |
60 |  /                     match scalar.assert_bits(Size::from_bytes(1)) {
61 |  |                         0 => FloatCC::Equal,
62 |  |                         1 => FloatCC::LessThan,
63 |  |                         2 => FloatCC::LessThanOrEqual,
...   |
74 |  |                         6 => {
   |  |______________________________-
75 | ||                             unimplemented!("not less than or equal");
76 | ||                         }
   | ||_________________________- this and all prior arms are found to be of type `!`
77 |  |                         kind => unreachable!("kind {:?}", kind),
   |  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `cranelift_codegen::ir::condcodes::FloatCC`, found ()
78 |  |                     }
   |  |_____________________- `match` arms have incompatible types
   |
   = note: expected type `cranelift_codegen::ir::condcodes::FloatCC`
              found type `()`
```

### PR DESCRIPTION
**Pull request by estebank**
- Change expected/found for type mismatches in `break`
- Be more accurate when talking about diverging match arms
- Tweak wording of function without a return value
- Suggest calling bare functions when their return value can be coerced to the expected type
- Give more parsing errors when encountering `foo(_, _, _)`

Fix #51767, fix #62677, fix #63136, cc #37384, cc #35241, cc #51669.

### CODE REVIEW

**Comment by estebank** [comment]
cc @Centril @varkor

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3709,7 +3709,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                             self.consider_hint_about_removing_semicolon(blk, expected_ty, err);
                         }
                         if let Some(fn_span) = fn_span {
-                            err.span_label(fn_span, "this function's body doesn't return");
+                            err.span_label(fn_span, "this function's body doesn't return a value");
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: This is a bit of half-truth I don't know if we should be spreading.
All converging functions in Rust return a value, this one just returns `()`.

File: src/librustc_typeck/check/expr.rs [hunk 2]
```diff
@@ -548,7 +548,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
                 } else {
                     assert!(e_ty.is_unit());
-                    coerce.coerce_forced_unit(self, &cause, &mut |_| (), true);
+                    let ty = coerce.expected_ty();
+                    coerce.coerce_forced_unit(self, &cause, &mut |err| {
+                        let msg = "give it a value of the expected type";
+                        let label = destination.label
+                            .map(|l| format!(" {}", l.ident))
+                            .unwrap_or_else(String::new);
+                        let sugg = format!("break{} {}", label, match ty.sty {
```
Comment (Centril) [inline src/librustc_typeck/check/expr.rs]: I'd store the `match ty.sty { ... }` result at the top of the closure.
Otherwise you are doing unnecessary work in the `=> return` case.

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -3819,6 +3819,41 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            if let Ok(_) = self.try_coerce(expr, sig.output(), expected, AllowTwoPhase::No) {
+                if let Ok(code) = self.sess().source_map().span_to_snippet(expr.span) {
+                    err.span_suggestion(expr.span, "use parentheses to call this function", format!(
+                        "{}({})",
+                        code,
+                        if sig.inputs().len() > 0 {
+                            "..."
+                        } else {
+                            ""
+                        }), if sig.inputs().len() > 0 {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Second time this occurs; I'd store the result in a `let` binding.

File: src/librustc_typeck/check/mod.rs [hunk 4]
```diff
@@ -3819,6 +3819,41 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
         pointing_at_return_type
     }
 
+    fn suggest_fn_call(
+        &self,
+        err: &mut DiagnosticBuilder<'tcx>,
+        expr: &hir::Expr,
+        expected: Ty<'tcx>,
+        found: Ty<'tcx>,
+    ) -> bool {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: The body could use some commentary in various place and a doc comment on `suggest_fn_call` showing a sample diagnostic.

File: src/librustc_typeck/check/mod.rs [hunk 5]
```diff
@@ -3819,6 +3819,41 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        if let ty::FnDef(..) | ty::FnPtr(_) = &found.sty {
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]: Return early to reduce indentation?

File: src/librustc_typeck/check/expr.rs [hunk 6]
```diff
@@ -548,7 +548,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            ty::Bool => "true",
+                            ty::Char => "'a'",
+                            ty::Int(_) | ty::Uint(_) => "42",
+                            ty::Float(_) => "3.14159",
+                            ty::Error | ty::Never => return,
```
Comment (Centril) [inline src/librustc_typeck/check/expr.rs]: Possibly?
```suggestion
                            ty::Never => "loop {}",
                            ty::Error => return,
```
`panic!()` could also be a candidate.

File: src/librustc/infer/error_reporting/mod.rs [hunk 7]
```diff
@@ -1143,27 +1146,6 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
                 }
                 (_, false, _) => {
                     if let Some(exp_found) = exp_found {
-                        let (def_id, ret_ty) = match exp_found.found.sty {
```
Comment (Centril) [inline src/librustc/infer/error_reporting/mod.rs]: Can you please explain this diff?

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: The way I read this originally was "this function's body doesn't `return` a value", which is slightly more correct ^_^

File: src/librustc_typeck/check/expr.rs (hunk 6 above)
Comment (estebank) [reply src/librustc_typeck/check/expr.rs]: I've thought about that, but that suggestion is more likely than not going to make little sense to people. I'd like to see `!` being used in the wild for a while before deciding what to suggest for it in errors.

File: src/librustc/infer/error_reporting/mod.rs (hunk 7 above)
Comment (estebank) [reply src/librustc/infer/error_reporting/mod.rs]: We used to suggest `did you mean Foo(...)?`. Now we catch this case in the new code and I have a new commit that will be even clearer. If I hadn't removed this code we would be suggesting the same thing twice.

File: src/test/ui/loops/loop-break-value.stderr [hunk 8]
```diff
@@ -90,10 +90,10 @@ error[E0308]: mismatched types
   --> $DIR/loop-break-value.rs:4:31
    |
 LL |     let val: ! = loop { break break; };
-   |                               ^^^^^ expected (), found !
+   |                               ^^^^^ expected !, found ()
    |
-   = note: expected type `()`
-              found type `!`
+   = note: expected type `!`
+              found type `()`
```
Comment (estebank) [inline src/test/ui/loops/loop-break-value.stderr]: @Centril Re: suggestion when encountering an expectation of `break !`, I feel that giving it too much consideration for a suggestion is not necessary, as I can't think of a non-degenerate construct that would cause such a case, as shown by this test.

File: src/librustc_typeck/check/expr.rs (hunk 6 above)
Comment (Centril) [reply src/librustc_typeck/check/expr.rs]: Yeah that's a good point.

File: src/librustc_typeck/check/mod.rs [hunk 9]
```diff
@@ -3819,6 +3819,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        let sig = found.fn_sig(self.tcx);
+        let sig = self
+            .replace_bound_vars_with_fresh_vars(expr.span, infer::FnCall, &sig)
+            .0;
+        let sig = self.normalize_associated_types_in(expr.span, &sig);
+        if let Ok(_) = self.try_coerce(expr, sig.output(), expected, AllowTwoPhase::No) {
+            let (mut sugg_call, applicability) = if sig.inputs().is_empty() {
+                (String::new(), Applicability::MachineApplicable)
+            } else {
+                ("...".to_owned(), Applicability::HasPlaceholders)
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                ("...".to_string(), Applicability::HasPlaceholders)
```

File: src/libsyntax/parse/parser.rs [hunk 10]
```diff
@@ -2052,9 +2052,23 @@ impl<'a> Parser<'a> {
                 while self.token != token::CloseDelim(token::Paren) {
```
Comment (Centril) [inline src/libsyntax/parse/parser.rs]: This arm should probably be rewritten using the standard list parsing infra (could try that as future work...).

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Maybe disambiguate the reading with *"this function's body doesn't `return <value>`"*?

File: src/librustc_typeck/check/mod.rs [hunk 11]
```diff
@@ -3819,6 +3819,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                match self.tcx.hir().get_if_local(def_id) {
+                    Some(Node::Item(hir::Item {
+                        node: ItemKind::Fn(.., body_id),
+                        ..
+                    })) => {
+                        let body = self.tcx.hir().body(*body_id);
+                        sugg_call = body.arguments.iter()
+                            .map(|arg| hir::print::to_string(
+                                hir::print::NO_ANN,
+                                |s| s.print_pat(&arg.pat),
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: I was originally going to match only on idents here and otherwise use `_`, but I thought it'd be ok to let it be this way:

```
error[E0308]: mismatched types
 --> file7.rs:8:20
  |
1 | fn foo(S(a, b): S) -> usize {
  | --------------------------- fn(S) -> usize {foo} defined here
...
8 |     let _: usize = foo;
  |                    ^^^
  |                    |
  |                    expected usize, found fn item
  |                    help: use parentheses to call this function: `foo(S(a, b))`
  |
  = note: expected type `usize`
             found type `fn(S) -> usize {foo}`
```

File: src/librustc_typeck/check/mod.rs [hunk 12]
```diff
@@ -3819,6 +3819,69 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            )).collect::<Vec<_>>().join(", ");
+                    }
+                    Some(Node::Ctor(hir::VariantData::Tuple(field, _))) => {
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: It would. What would be the appropriate way of checking wether a given `DefId` is a tuple struct or a tuple enum variant?

[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: If you can get a `DefKind` then you can check `CtorOf::Variant`. Not sure how you do the first... cc @davidtwco

File: src/librustc_typeck/check/mod.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Yeah it is OK but it desires a test... ;)

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: I don't want to be too prescriptive towards having to use `return` in case we suggest removing a semicolon

File: src/librustc_typeck/check/expr.rs (hunk 6 above)
Comment (estebank) [reply src/librustc_typeck/check/expr.rs]: https://github.com/rust-lang/rust/issues/63390

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: What's the situation you are concerned about re. removing a semicolon?

File: src/librustc_typeck/check/mod.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: Using the following doesn't seem to work:

```rust
                    Some(Node::Ctor(hir::VariantData::Tuple(fields, _))) => {
                        sugg_call = fields.iter().map(|_| "_").collect::<Vec<_>>().join(", ");
                        match hir.as_local_hir_id(def_id).and_then(|hir_id| hir.def_kind(hir_id)) {
                            Some(hir::def::DefKind::Enum) => msg = "instatiate this tuple variant",
                            _ => msg = "instatiate this tuple struct",
                        }
                    }
```

[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Hmm; maybe have a look at https://doc.rust-lang.org/nightly/nightly-rustc/rustc_typeck/check/struct.FnCtxt.html#method.write_resolution and see if you can `.get(...)` with the `HirId` you got?

cc @cramertj -- maybe they know :)

[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: You can also access the `TyCtxt` (which has a method `.def_kind(DefId) -> Option<DefKind>`) through `self.inh.infcx.tcx` but I don't know whether that is appropriate or not.

[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: I think I figured it out:

```rust
                        match hir.as_local_hir_id(def_id).and_then(|hir_id| hir.def_kind(hir_id)) {
                            Some(hir::def::DefKind::Ctor(hir::def::CtorOf::Variant, _)) => {
                                msg = "instatiate this tuple variant";
                            }
                            Some(hir::def::DefKind::Ctor(hir::def::CtorOf::Struct, _)) => {
                                msg = "instatiate this tuple struct";
                            }
                            _ => {}
                        }
```

[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Oh... your problem was not getting the right DefKind =P I looked at the wrong thing. Yeah, that those match arms are correct.

File: src/librustc_typeck/check/mod.rs (hunk 1 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: I'm just worried that by hinting at `return <value>;` we might confuse people when telling them that removing a semicolon would fix the problem. Then again it might be that it would help to cement the idea that both tail expressions and `return` statements are functionally the same... I wonder if adding a note would stating the existence of both `return` statements and tail expressions would be a good idea for these.

```rust
fn foo() -> usize {
    42;
}
```

```
error[E0308]: mismatched types
 --> src/lib.rs:1:13
  |
1 | fn foo() -> usize {
  |    ---      ^^^^^ expected usize, found ()
  |    |
  |    this function's body doesn't `return` a value
2 |     42;
  |       - help: consider removing this semicolon
  |
  = note: expected type `usize`
             found type `()`
```
vs
```
error[E0308]: mismatched types
 --> src/lib.rs:1:13
  |
1 | fn foo() -> usize {
  |    ---      ^^^^^ expected usize, found ()
  |    |
  |    this function's body doesn't `return <value>;`
2 |     42;
  |       - help: consider removing this semicolon
  |
  = note: expected type `usize`
             found type `()`
```

Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Hmm... Maybe be more direct and point out that the lack of a tail expression results in `()` as a type?

```rust
fn foo() -> usize {
    42;
}
```

==>

```
rror[E0308]: mismatched types
 --> src/lib.rs:1:13
  |
1 | fn foo() -> usize {
  |    ---      ^^^^^ expected usize, found ()
  |    |
  |    this function implicitly returns `()` as the body has no tail expression
2 |     42;
  |       - help: consider removing this semicolon
  |
  = note: expected type `usize`
             found type `()`

if teaching_mode {

  = help: a function can return a value in three ways:
          - with an implicit tail expression
          - with an explicit `return <value>;`
          - where function body doesn't end with a tail expression (return type is `()`)

}
```

Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: That's not that bad, although I would add a mention to `return` as well:

    this function implicitly returns `()` as the body has no tail expression nor a `return` statement

Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Sure; It's a tad long but it is complete :)

Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: changed

File: src/librustc_typeck/check/mod.rs [hunk 13]
```diff
@@ -3709,7 +3709,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                             self.consider_hint_about_removing_semicolon(blk, expected_ty, err);
                         }
                         if let Some(fn_span) = fn_span {
-                            err.span_label(fn_span, "this function's body doesn't return");
+                            err.span_label(
+                                fn_span,
+                                "this function implicitly returns `()` as its body has no tail \
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                "this function implicitly returns `()` as its body has no tail- \
```

File: src/librustc_typeck/check/mod.rs [hunk 14]
```diff
@@ -3709,7 +3709,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                 expression nor a `return` statement",
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                 nor `return`-expression",
```

**Review by Centril — COMMENTED** [review]
A bit shorter + `return` is an expr. :)

File: src/librustc_typeck/check/mod.rs (hunk 14 above)
Comment (estebank) [reply src/librustc_typeck/check/mod.rs]: Is the current

```rust
                                "this function implicitly returns `()` as its body has no tail \
                                 or `return` expression",
```

reasonable or would you like me to change it to the requested wording? I have an irrational aversion to compound-words.

Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: Seems reasonable to me as-is. The main advantage of writing *"tail- nor `return`-expression"* is that it clarifies that it refers to *tail expression nor `return` expression* without the repetition.

File: src/librustc_typeck/check/mod.rs (hunk 13 above)
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                "implicitly returns `()` as its body has no tail \
```

**Review by Centril — APPROVED** [review]
r=me when-green with or without the change below depending on whether you feel that is an improvement :)

File: src/libsyntax/parse/parser.rs (hunk 10 above)
Comment (Centril) [reply src/libsyntax/parse/parser.rs]: If you have a sec, can you file an issue for this? I might fix it myself but the reminder would be great. ^^

File: src/librustc_typeck/check/mod.rs [hunk 15]
```diff
@@ -3819,6 +3823,101 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                                hir::PatKind::Binding(_, _, ident, None)
+                                if ident.name != kw::SelfLower => ident.to_string(),
+                                _ => "_".to_string(),
+                            }).collect::<Vec<_>>().join(", ");
+                    }
+                    Some(Node::Ctor(hir::VariantData::Tuple(fields, _))) => {
+                        sugg_call = fields.iter().map(|_| "_").collect::<Vec<_>>().join(", ");
+                        match hir.as_local_hir_id(def_id).and_then(|hir_id| hir.def_kind(hir_id)) {
+                            Some(hir::def::DefKind::Ctor(hir::def::CtorOf::Variant, _)) => {
+                                msg = "instatiate this tuple variant";
```
Comment (varkor) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                msg = "instantiate this tuple variant";
```

File: src/librustc_typeck/check/mod.rs [hunk 16]
```diff
@@ -3819,6 +3823,101 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            }
+                            Some(hir::def::DefKind::Ctor(hir::def::CtorOf::Struct, _)) => {
+                                msg = "instatiate this tuple struct";
```
Comment (varkor) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                                msg = "instantiate this tuple struct";
```

File: src/libsyntax/parse/parser.rs (hunk 10 above)
Comment (estebank) [reply src/libsyntax/parse/parser.rs]: https://github.com/rust-lang/rust/issues/63396

**Comment by varkor** [comment]
Looks great!

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/63401#issuecomment-519794255, @bors r-
Rebasing + `--bless` should be enough.
