### PR TITLE
Move attribute safety checking to attribute parsing

### LINKED ISSUE #148453: "`attr` is not an unsafe attribute" diagnostic is emitted even if the attribute doesn't exist
### Code

```Rust
#[unsafe(nonexistent)]
fn foo() {}
```

### Current output

```Shell
error: `nonexistent` is not an unsafe attribute
 --> src/lib.rs:1:3
  |
1 | #[unsafe(nonexistent)]
  |   ^^^^^^ this is not an unsafe attribute
  |
  = note: extraneous unsafe is not allowed in attributes

error: cannot find attribute `nonexistent` in this scope
 --> src/lib.rs:1:10
  |
1 | #[unsafe(nonexistent)]
  |          ^^^^^^^^^^^
```

### Desired output

```Shell
error: cannot find attribute `nonexistent` in this scope
 --> src/lib.rs:1:10
  |
1 | #[unsafe(nonexistent)]
  |          ^^^^^^^^^^^
```

### Rationale and extra context

While it is true that an attribute that doesn't exist isn't unsafe, the diagnostic provides not much to no additional value, and is emitted first, pushing the real error down. If both diagnostics should be kept, the one about the attribute not existing should probably be emitted first.

### Other cases

```Rust

```

### Rust Version

rustc 1.91.0, on the [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&code=%23%5Bunsafe%28nonexistent%29%5D%0Afn+foo%28%29+%7B%7D)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JonathanBrouwer**
This PR moves attribute safety checking to be done during attribute parsing. The `cfg` and `cfg_attr` attribute no longer need special-cased safety checking, yay!

This PR is a part 1 of 2, in the second part I'd like to define attribute safety in the attribute parsers rather than getting the information from BUILTIN_ATTRIBUTE_MAP, but to keep PRs reviewable lets do that separately.

Fixes https://github.com/rust-lang/rust/issues/148453 by reordering the diagnostics. The "cannot find attribute" diagnostic now appears first, but both diagnostics still appear.

r? @jdonszelmann

### CODE REVIEW

File: tests/incremental/hashes/function_interfaces.rs [hunk 1]
```diff
@@ -279,7 +279,7 @@ pub fn no_mangle() {}
 #[rustc_clean(cfg = "cfail3")]
 #[rustc_clean(cfg = "cfail5")]
 #[rustc_clean(cfg = "cfail6")]
-#[no_mangle]
+#[unsafe(no_mangle)]
```
Comment (JonathanBrouwer) [inline tests/incremental/hashes/function_interfaces.rs:282]: The extra unsafe is necessary because without it these tests produces a lint, meaning fail2 and cfail5 are not clean. This was not previously a problem because the lint was emitted early, while it is now stored in the hir.

File: compiler/rustc_attr_parsing/src/validate_attr.rs [hunk 2]
```diff
@@ -150,98 +149,17 @@ fn is_attr_template_compatible(template: &AttributeTemplate, meta: &ast::MetaIte
...
-            );
-        }
-    }
-}
-
 // Called by `check_builtin_meta_item` and code that manually denies
 // `unsafe(...)` in `cfg`
 pub fn deny_builtin_meta_unsafety(diag: DiagCtxtHandle<'_>, unsafety: Safety, name: &Path) {
     // This only supports denying unsafety right now - making builtin attributes
     // support unsafety will requite us to thread the actual `Attribute` through
```
Comment (jdonszelmann) [inline compiler/rustc_attr_parsing/src/validate_attr.rs]: is this comment still true?

File: compiler/rustc_expand/src/config.rs [hunk 3]
```diff
@@ -421,13 +412,6 @@ impl<'a> StripUnconfigured<'a> {
         node: NodeId,
         emit_errors: ShouldEmit,
     ) -> EvalConfigResult {
-        // Unsafety check needs to be done explicitly here because this attribute will be removed before the normal check
-        deny_builtin_meta_unsafety(
```
Comment (jdonszelmann) [inline compiler/rustc_expand/src/config.rs:425]: do we still use deny_builtin_meta_unsafety anywhere since it's removed here?

File: compiler/rustc_attr_parsing/src/validate_attr.rs (hunk 2 above)
Comment (JonathanBrouwer) [reply compiler/rustc_attr_parsing/src/validate_attr.rs]: Nope, and it's hasn't been true for a long time :p
Fixed by removing the entire function

File: compiler/rustc_expand/src/config.rs (hunk 3 above)
Comment (JonathanBrouwer) [reply compiler/rustc_expand/src/config.rs:425]: Nope we don't, good catch!

**Comment by jdonszelmann** [comment]
this might be a real regression haha. take a look at this pr: https://github.com/rust-lang/rust/pull/148863. it seems that lowering spans simply isn't always worth it weirdly

**Comment by jdonszelmann** [comment]
cc: @oli-obk I guess we need to come up with a policy here: do we want to prefer correctness in incremental and lower all spans we can find regardless of the runtime cost or do we want to look for places not to lower spans for some perf wins haha
