### PR TITLE
Move EH personality functions to std

### LINKED ISSUE #41004: Endless loop on ARM while printing backtrace with -Cpanic=abort
This happens with LLVM 4.0, see https://github.com/rust-lang/rust/pull/40123#issuecomment-290949091 for some more information.

Filing the issue now to have an issue number to reference.

cc #40123

### PR DESCRIPTION
**Pull request by Amanieu**
These were previously in the panic_unwind crate with dummy stubs in the
panic_abort crate. However it turns out that this is insufficient: we
still need a proper personality function even with -C panic=abort to
handle the following cases:

1) `extern "C-unwind"` still needs to catch foreign exceptions with -C
panic=abort to turn them into aborts. This requires landing pads and a
personality function.

2) ARM EHABI uses the personality function when creating backtraces.
The dummy personality function in panic_abort was causing backtrace
generation to get stuck in a loop since the personality function is
responsible for advancing the unwind state to the next frame.

Fixes #41004

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It seems like the catching of foreign exceptions should work even if std isn't available - should this be in core perhaps? Similarly backtrace generation in theory isn't dependent on std, so if the function is needed for that it should be provided?

**Comment by Amanieu** [comment]
The `eh_personality` lang item is only required in no_std if `extern "C-unwind"` is used. Otherwise, we don't want to force no_std code to have a dependency on libunwind if it's not needed.

On ARM, a default personality function (provided by libunwind) is used for functions that don't specify a personality (which is the case for most code compiled with `-C panic=abort`). Again, this is only needed on no_std with `extern "C-unwind"` which uses `rust_eh_personality`.

**Comment by nbdd0121** [comment]
`eh_personality` lang item is also required if no_std crate uses `panic=unwind`. I have use cases where I supply a separate panic runtime and unwinding runtime (https://github.com/nbdd0121/unwinding). Currently I have to supply a copy of the personality function as well, but ideally that can be provided by some lib bundled with Rust.

**Comment by Amanieu** [comment]
I think that in the future we could move the unwinding-related functionality to its own crate that is independent of `std`. This crate would then only be pulled in by `panic_unwind` and if any codegen within a crate requires a personality function (`-Cpanic=unwind` or any use of `extern "C-unwind"`). However I feel that this should be done in a separate PR.

**Comment by bjorn3** [comment]
The personality function isn't all that big. In addition if you truly care about code size you will compile every crate including the standard library with `-Cpanic=abort` in which case there won't be any references to the personality function and thus it will be removed by `--gc-sections`.

**Comment by joshtriplett** [comment]
@bjorn3 Recompiling the standard library is much more difficult than most other steps someone might take in optimization.

**Comment by Amanieu** [comment]
On a hello world program compiled with `rustc -C panic=abort -C strip=symbols` there is a slight increase in binary size from `313656` bytes to `317752` bytes. The difference is 4096 bytes but this is probably due to rounding, so the "real" difference is less than 4KB. I think this is perfectly acceptable relative to the overall size of std.

**Comment by nbdd0121** [comment]
> I think that in the future we could move the unwinding-related functionality to its own crate that is independent of `std`. This crate would then only be pulled in by `panic_unwind` and if any codegen within a crate requires a personality function (`-Cpanic=unwind` or any use of `extern "C-unwind"`). However I feel that this should be done in a separate PR.

If we want to move it to its own crate eventually then we might just do so without first moving it into std. The codegen part could be done later and we can just let std unconditionally pull it in for now.

**Comment by joshtriplett** [comment]
@Amanieu Hello world pulls in all the format machinery, which embedded often tries to avoid. What's the delta for an empty main function?

**Comment by nbdd0121** [comment]
Embedded would use `no_std`.

**Comment by Amanieu** [comment]
> If we want to move it to its own crate eventually then we might just do so without first moving it into std. The codegen part could be done later and we can just let std unconditionally pull it in for now.

I think moving into std is a good first step since it separates the personality function from the choice of panic runtime. It should make it easier to move into a separate crate in the future. Note that it can't be placed in `core` itself since unwinding has OS dependencies (e.g. `dl_iterate_phdr`).

**Comment by nbdd0121** [comment]
I don't see why moving it into a separate crate requires it to go through std first. The personality function doesn't depend on std. The personality function also has no OS dependencies. It does depend on an unwinding runtime, but unwinding runtime can function without OS.

**Comment by Amanieu** [comment]
In this PR I'm just trying to fix two issues which require a personality function even with `-Cpanic=abort`. The minimal solution is to move the personality function into std.

Adding a new crate to support unwinding without std would require a lot more work which I have chosen to leave for a future PR.

**Comment by nbdd0121** [comment]
I don't see how adding a new crate is "a lot more work". This is all it takes:
```patch
diff --git a/Cargo.lock b/Cargo.lock
index ef9f91fdb43..1c9ce7f75e0 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1078,6 +1078,17 @@ dependencies = [
  "rustc-std-workspace-core",
 ]
 
+[[package]]
+name = "eh_personality"
+version = "0.0.0"
+dependencies = [
+ "cfg-if 0.1.10",
+ "compiler_builtins",
+ "core",
+ "libc",
+ "unwind",
+]
+
 [[package]]
 name = "either"
 version = "1.6.0"
@@ -5066,6 +5077,7 @@ dependencies = [
  "compiler_builtins",
  "core",
  "dlmalloc",
+ "eh_personality",
  "fortanix-sgx-abi",
  "hashbrown",
  "hermit-abi",
diff --git a/library/eh_personality/Cargo.toml b/library/eh_personality/Cargo.toml
new file mode 100644
index 00000000000..47cdf9ee7e9
--- /dev/null
+++ b/library/eh_personality/Cargo.toml
@@ -0,0 +1,19 @@
+[package]
+name = "eh_personality"
+version = "0.0.0"
+license = "MIT OR Apache-2.0"
+repository = "https://github.com/rust-lang/rust.git"
+description = "Personality function for unwinding Rust stack frames"
+edition = "2021"
+
+[lib]
+test = false
+bench = false
+doc = false
+
+[dependencies]
+core = { path = "../core" }
+libc = { version = "0.2", default-features = false }
+unwind = { path = "../unwind" }
+compiler_builtins = "0.1.0"
+cfg-if = "0.1.8"
diff --git a/library/eh_personality/src/lib.rs b/library/eh_personality/src/lib.rs
new file mode 100644
index 00000000000..0c9ac1ac8e4
--- /dev/null
+++ b/library/eh_personality/src/lib.rs
@@ -0,0 +1 @@
+#![no_std]
diff --git a/library/std/Cargo.toml b/library/std/Cargo.toml
index 232ccdf39d4..66c913f1911 100644
--- a/library/std/Cargo.toml
+++ b/library/std/Cargo.toml
@@ -21,6 +21,7 @@ profiler_builtins = { path = "../profiler_builtins", optional = true }
 unwind = { path = "../unwind" }
 hashbrown = { version = "0.11", default-features = false, features = ['rustc-dep-of-std'] }
 std_detect = { path = "../stdarch/crates/std_detect", default-features = false, features = ['rustc-dep-of-std'] }
+eh_personality = { path = "../eh_personality" }
 
 # Dependencies of the `backtrace` crate
 addr2line = { version = "0.16.0", optional = true, default-features = false }
diff --git a/library/std/src/lib.rs b/library/std/src/lib.rs
...skipping...
+ "core",
+ "libc",
+ "unwind",
+]
+
 [[package]]
 name = "either"
 version = "1.6.0"
@@ -5066,6 +5077,7 @@ dependencies = [
  "compiler_builtins",
  "core",
  "dlmalloc",
+ "eh_personality",
  "fortanix-sgx-abi",
  "hashbrown",
  "hermit-abi",
diff --git a/library/eh_personality/Cargo.toml b/library/eh_personality/Cargo.toml
new file mode 100644
index 00000000000..47cdf9ee7e9
--- /dev/null
+++ b/library/eh_personality/Cargo.toml
@@ -0,0 +1,19 @@
+[package]
+name = "eh_personality"
+version = "0.0.0"
+license = "MIT OR Apache-2.0"
+repository = "https://github.com/rust-lang/rust.git"
+description = "Personality function for unwinding Rust stack frames"
+edition = "2021"
+
+[lib]
+test = false
+bench = false
+doc = false
+
+[dependencies]
+core = { path = "../core" }
+libc = { version = "0.2", default-features = false }
+unwind = { path = "../unwind" }
+compiler_builtins = "0.1.0"
+cfg-if = "0.1.8"
diff --git a/library/eh_personality/src/lib.rs b/library/eh_personality/src/lib.rs
new file mode 100644
index 00000000000..0c9ac1ac8e4
--- /dev/null
+++ b/library/eh_personality/src/lib.rs
@@ -0,0 +1 @@
+#![no_std]
diff --git a/library/std/Cargo.toml b/library/std/Cargo.toml
index 232ccdf39d4..66c913f1911 100644
--- a/library/std/Cargo.toml
+++ b/library/std/Cargo.toml
@@ -21,6 +21,7 @@ profiler_builtins = { path = "../profiler_builtins", optional = true }
 unwind = { path = "../unwind" }
 hashbrown = { version = "0.11", default-features = false, features = ['rustc-dep-of-std'] }
 std_detect = { path = "../stdarch/crates/std_detect", default-features = false, features = ['rustc-dep-of-std'] }
+eh_personality = { path = "../eh_personality" }
 
 # Dependencies of the `backtrace` crate
 addr2line = { version = "0.16.0", optional = true, default-features = false }
diff --git a/library/std/src/lib.rs b/library/std/src/lib.rs
index 4ba4e2a528e..27704b7d880 100644
--- a/library/std/src/lib.rs
+++ b/library/std/src/lib.rs
@@ -368,6 +368,10 @@
 #[allow(unused_extern_crates)]
 extern crate unwind;
 
+#[doc(masked)]
+#[allow(unused_extern_crates)]
+extern crate eh_personality;
+
 // During testing, this crate is not actually the "real" std library, but rather
 // it links to the real std library, which was compiled from this same source
 // code. So any lang items std defines are conditionally excluded (or else they
```

**Comment by Amanieu** [comment]
I would prefer to leave splitting this into a separate crate to a future PR.

File: library/panic_unwind/src/emcc.rs [hunk 1]
```diff
@@ -89,7 +88,7 @@ pub unsafe fn panic(data: Box<dyn Any + Send>) -> u32 {
     let sz = mem::size_of_val(&data);
     let exception = __cxa_allocate_exception(sz) as *mut Exception;
     if exception.is_null() {
-        return uw::_URC_FATAL_PHASE1_ERROR as u32;
+        return 0;
```
Comment (Mark-Simulacrum) [inline library/panic_unwind/src/emcc.rs:91]: This change feels unrelated to the stated goal in the PR description?

File: library/std/src/personality.rs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+mod dwarf;
+
+#[cfg(not(test))]
+cfg_if::cfg_if! {
+    if #[cfg(target_os = "emscripten")] {
+        mod emcc;
+    } else if #[cfg(target_env = "msvc")] {
+        // This is required by the compiler to exist (e.g., it's a lang item),
+        // but it's never actually called by the compiler because
+        // _CxxFrameHandler3 is the personality function that is always used.
```
Comment (Mark-Simulacrum) [inline library/std/src/personality.rs:22]: It looks like this comment isn't directly replicated from the previous (which was a little less specific in terms of which cxx function is used) - some cursory online searching suggests that we may actually be using the 4th version these days, not 3rd?

**Review by Mark-Simulacrum — COMMENTED** [review]
I'm a little concerned by the coupling of changes and code movement that make reviewing those changes difficult - can you clarify whether those are intended? I noted a few cases...

File: library/std/src/personality.rs (hunk 2 above)
Comment (Amanieu) [reply library/std/src/personality.rs:22]: The old comment was incorrect, we now always use `_CxxFrameHandler3` for our personality function on MSVC targets.

`_CxxFrameHandler4` exists but it is not supported by LLVM, only by MSVC itself.

File: library/panic_unwind/src/emcc.rs (hunk 1 above)
Comment (Amanieu) [reply library/panic_unwind/src/emcc.rs:91]: Yes it's unrelated, I just noticed it while going through the code. Emscripten doesn't use the libunwind API and shouldn't be returning libunwind error codes. In the end it doesn't matter since the returned value is not used for anything, it's just printed as part of the message that indicates that initiating unwinding failed.

File: library/rtstartup/rsbegin.rs [hunk 3]
```diff
@@ -35,6 +35,16 @@ pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
...
+// Frame unwind info registration
+//
+// Each module's image contains a frame unwind info section (usually
+// ".eh_frame").  When a module is loaded/unloaded into the process, the
+// unwinder must be informed about the location of this section in memory. The
+// methods of achieving that vary by the platform.  On some (e.g., Linux), the
+// unwinder can discover unwind info sections on its own (by dynamically
+// enumerating currently loaded modules via the dl_iterate_phdr() API and
+// finding their ".eh_frame" sections); Others, like Windows, require modules
+// to actively register their unwind info sections via unwinder API.
```
[the remark this answers is not in the document]
Comment (Amanieu) [reply library/rtstartup/rsbegin.rs:47]: These wrappers were originally added so that linking to libgcc_eh could be avoided if panic=abort was used. However this has become less relevant recently since we always link to libgcc in the linker flags. This PR now makes them completely redundant since std depends on the unwinding support in libgcc no matter which panic runtime is used.

**Comment by Mark-Simulacrum** [comment]
> I'm a little concerned by the coupling of changes and code movement that make reviewing those changes difficult - can you clarify whether those are intended? I noted a few cases...

Sorry if it wasn't clear about this. My worry is that it's difficult to review this PR as-is, because it's coupling code movement and code changes. Can you split this out into separate commits at least? It might be easier to do that from scratch, but as-is it's essentially forcing me to scroll back and forth to reconstruct that separation manually, which seems like it's easy to miss something and not very reliable.

**Comment by Amanieu** [comment]
I split it up into separate commits.

**Comment by Mark-Simulacrum** [comment]
Thanks for splitting it up. I think this makes sense to me; it's mostly all factored into a module which we could move into a separate crate to further optimize this out in the long run, which should be pretty easy to do. Until it actually lets us skip linking to it I'm not sure it's worth the (slight) hassle of spinning up an additional crate though.

@bors r+ rollup=never

**Comment by klensy** [comment]
`src/tools/rust-analyzer` submodule changed in PR.

**Comment by Amanieu** [comment]
Alright, I have no idea what is going on here. Why does moving the `eh_personality` lang item from `panic_unwind` to `std. cause an LTO test to fail with linker errors?

We don't even use the `eh_personality` lang item on MSVC: it is ignored in rustc and we hard-code `_CxxFrameHandler3` as the personality function.

**Comment by danielframpton** [comment]
I took a brief look at the issue here and may circle back if I get a little more time.

The test that is failing is a thin lto test (lto-empty). With the change, there is a big difference in terms of what functions are being included in the object files we pass to the linker for libraries (e.g., for std). It seems like a set of error handling/formatting code and dependencies (including allocation, etc.).

I haven't looked carefully, but I am not sure these end up actually being called (and perhaps one part of the LTO process recognizes this which is why they are dropped), but the lto import phase seems to be important additional methods and marking them as `available_externally` (before this change they were not imported and just declared). I don't see any significant local differences in the IR before the import, but of course some methods will have moved around modules here.

An LTO expert might be able to understand where to look next?

**Comment by michaelwoerister** [comment]
I'll try to take a look at what's going on with the LTO test case -- but I can't promise that I'll get to it any time soon. So, definitely feel free to beat me to it 😉

**Comment by Amanieu** [comment]
Actually, @Mark-Simulacrum do you want to have a second look, it's been a while? Otherwise it should be fine to just merge.

**Comment by Mark-Simulacrum** [comment]
I skimmed through - seems okay. I think the biggest "risk" is accidentally reverting some changes to the original code that rebasing missed, did you check git log or similar for the original crates?

Seems easy enough to re-patch if needed though.

@bors rollup=never

**Comment by Amanieu** [comment]
(silly submodules keep getting out of sync)

@bors r=Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
@bors retry

curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to ci-mirrors.rust-lang.org:443

**Comment by bjorn3** [comment]
See https://github.com/rust-lang/rust/blob/4d45b0745ab227feb9000bc15713ade4b99241ea/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L110 which only gets applied to crates marked as `#![panic_runtime]` (panic_unwind and panic_abort). This code is necessary for correct LTO.

**Comment by bjorn3** [comment]
The symbol export level can be specified using `#[rustc_std_internal_symbol]`, but the used marker can't be I think.

**Comment by petrochenkov** [comment]
>[rust/compiler/rustc_codegen_ssa/src/back/symbol_export.rs](https://github.com/rust-lang/rust/blob/4d45b0745ab227feb9000bc15713ade4b99241ea/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L106-L115)

When I read this stuff for https://github.com/rust-lang/rust/pull/95604, it was really frustrating to see all those hacks being hardcoded into the compiler instead of supporting generally usable symbol export and used-ness attributes.

**Comment by thomcc** [comment]
`#[used]` should force a symbol to be present on the apple targets now, I think.

**Comment by bjorn3** [comment]
Isn't `#[used]` only for statics?

**Comment by thomcc** [comment]
Ah, does this have to be a function declaration and can't be made into a static?

**Comment by bjorn3** [comment]
It's a function definition, not a declaration. And the unwind runtime calls this function when unwinding through rust frames. As such it can't be made a static.

**Comment by thomcc** [comment]
I see, nevermind then.

File: compiler/rustc_codegen_ssa/src/back/symbol_export.rs [hunk 4]
```diff
@@ -103,18 +103,14 @@ fn reachable_non_generics_provider(tcx: TyCtxt<'_>, cnum: CrateNum) -> DefIdMap<
...
-                    | "rust_eh_register_frames"
-                    | "rust_eh_unregister_frames" => true,
-                    _ => false,
-                };
-                (SymbolExportLevel::Rust, used)
+            // We won't link right if this symbol is stripped during LTO.
+            let name = tcx.symbol_name(Instance::mono(tcx, def_id.to_def_id())).name;
+            let used = name == "rust_eh_personality";
+
+            let export_level = if special_runtime_crate {
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/back/symbol_export.rs:110]: This means that `rust_eh_personality` is now exported from cdylibs as it doesn't use `SymbolExportLevel::Rust`, right? That is going to give troubles when depending on two cdylibs compiled by different versions of rustc if we change the eh_personality implementation as one version of this symbol will override the other.

Comment (Amanieu) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs:110]: I think `symbol_export_level` still returns `Rust` for `rust_eh_personality` since it doesn't have any attribute such as `no_mangle` that marks it as externally visible.

Comment (bjorn3) [reply compiler/rustc_codegen_ssa/src/back/symbol_export.rs:110]: I just checked it and you are indeed right. `rust_eh_personality` is not exported.

**Comment by glandium** [comment]
This is causing problems building Firefox with *-windows-gnu targets, whereby staticlibs built with panic=abort now fail to link because of missing the symbols _GCC_specific_handler, _Unwind_GetLanguageSpecificData, _Unwind_GetIPInfo, _Unwind_GetRegionStart, _Unwind_SetGR, _Unwind_SetIP, _Unwind_GetDataRelBase, and _Unwind_GetTextRelBase. Interestingly, this doesn't happen on other targets Firefox is built for.

**Comment by Amanieu** [comment]
These symbols are provided by either `libgcc_eh.a` or `libgcc_s-dw2-1.dll`. Usually the former.

https://github.com/rust-lang/rust/blob/ff479b1f3c77e8312843e7de212253632f4c1a8a/compiler/rustc_target/src/spec/windows_gnu_base.rs#L54-L58

**Comment by glandium** [comment]
They shouldn't be needed though for panic=abort + -Clto (and weren't before).

**Comment by ChrisDenton** [comment]
This is perhaps related to the point made at the end of [this comment](https://github.com/rust-lang/rust/issues/101134#issuecomment-1235177005):

>It may just be because we build the standard library with panic=unwind so that it can be used with both panic=unwind and panic=abort.

**Comment by Amanieu** [comment]
Right, if you rebuild the standard library with `-C panic=abort` and `-Zbuild-std` then these symbols will go away.

**Comment by glandium** [comment]
Not sure about *-windows-gnu, but at least on *-linux-gnu, -Clto eliminates unused code from std. It doesn't do it for this, though...

Another problem that arises from this is that when building Firefox for aarch64-apple-darwin, linking fails with "ld64.lld: error: too many personalities (4) for compact unwind to encode"

**Comment by BatmanAoD** [comment]
@glandium @Amanieu Should these issues be moved to a new ticket? Are they related to #101134 at all?

Is this a stable-to-nightly regression?

**Comment by Amanieu** [comment]
> Not sure about *-windows-gnu, but at least on *-linux-gnu, -Clto eliminates unused code from std. It doesn't do it for this, though...

Previously we had an additional LLVM pass inserted in LTO which removed all unwinding from functions when `-C panic=abort` was used. However this was removed because it broken `extern "C-unwind"` which needs to catch unwinds (to turn them into aborts) in `-C panic=abort`.
