### PR TITLE
forbid `dyn Trait` in patterns

### LINKED ISSUE #63322: Closures in const generics cause ICE
Pretty straightforward. The idea is to plug logic into a template. This seems like something that should/could work.

```
#![feature(const_generics)]

fn test<const F: &'static dyn Fn(u32) -> u32>(i: u32) -> u32 {
    F(i)
}

const F: &'static dyn Fn(u32) -> u32 = &|x| x*x;

fn main () {
    println!("{}", test::<{F}>(5));
}
```

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7eefeb472380da1061af1be06967d30a

### LINKED ISSUE #70972: error: internal compiler error: src/librustc_mir_build/hair/pattern/_match.rs:318: cannot deref ByRef
### Code

```Rust
use std::sync::atomic::{AtomicPtr, Ordering};

const P: &dyn T = &S as &dyn T;
static mut LOGGER: AtomicPtr<&dyn T> = AtomicPtr::new(&mut P);

pub trait T {}
struct S;
impl T for S {}

pub fn f() {
    match *LOGGER.load(Ordering::SeqCst) {
        P | _ => {}
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (77621317d 2020-03-28)
binary: rustc
commit-hash: 77621317d643cc5d13da60b26ab68b057668e688
commit-date: 2020-03-28
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

Note that the error is also present on stable (1.42.0).

### Error output

```
error: internal compiler error: src/librustc_mir_build/hair/pattern/_match.rs:318: cannot deref ByRef {
    alloc: Allocation {
        bytes: [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
        relocations: Relocations(
            SortedMap {
                data: [
                    (
                        Size {
                            raw: 0,
                        },
                        (
                            (),
                            alloc2,
                        ),
                    ),
                    (
                        Size {
                            raw: 8,
                        },
                        (
                            (),
                            alloc4,
                        ),
                    ),
                ],
            },
        ),
        undef_mask: UndefMask {
            blocks: [
                65535,
            ],
            len: Size {
                raw: 16,
            },
        },
        size: Size {
            raw: 16,
        },
        align: Align {
            pow2: 3,
        },
        mutability: Not,
        extra: (),
    },
    offset: Size {
        raw: 0,
    },
}, dyn T -> dyn T

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1439
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: <rustc_mir_build::hair::pattern::_match::LiteralExpander as rustc_mir_build::hair::pattern::PatternFolder>::fold_pattern
  21: rustc_mir_build::hair::pattern::PatternFoldable::fold_with
  22: <rustc_mir_build::hair::pattern::PatKind as rustc_mir_build::hair::pattern::PatternFoldable>::super_fold_with
  23: <rustc_mir_build::hair::pattern::_match::LiteralExpander as rustc_mir_build::hair::pattern::PatternFolder>::fold_pattern
  24: rustc_mir_build::hair::pattern::check_match::MatchVisitor::lower_pattern
  25: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  26: rustc_mir_build::hair::pattern::_match::MatchCheckCtxt::create_and_enter
  27: <rustc_mir_build::hair::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  28: <rustc_mir_build::hair::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  29: rustc_mir_build::hair::pattern::check_match::check_match
  30: rustc::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc::ty::context::TyCtxt> for rustc::ty::query::queries::check_match>::compute
  31: rustc::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc::dep_graph::dep_node::DepKind>::with_deps
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  33: rustc_query_system::query::plumbing::get_query
  34: rustc_query_system::query::plumbing::ensure_query
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  36: rustc_session::utils::<impl rustc_session::session::Session>::time
  37: rustc_interface::passes::analysis
  38: rustc::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc::ty::context::TyCtxt> for rustc::ty::query::queries::analysis>::compute
  39: rustc::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc::dep_graph::dep_node::DepKind>::with_deps
  40: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  41: rustc_query_system::query::plumbing::get_query
  42: rustc::ty::context::tls::enter_global
  43: rustc_interface::interface::run_compiler_in_existing_thread_pool
  44: scoped_tls::ScopedKey<T>::set
  45: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (77621317d 2020-03-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] processing `f`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by lcnr**
Do not allow `&dyn Trait` as a generic const parameters.
This also changes dyn trait in pattern from ICE to error.

closes #63322
closes #70972

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
IMO this PR's title/description/testing should focus on pattern-matching.
Affecting `const` generics is a side-effect from that.

r? @pnkfelix

File: src/librustc_mir_build/hair/pattern/const_to_pat.rs [hunk 1]
```diff
@@ -106,6 +106,12 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
                     traits::NonStructuralMatchTy::Param => {
                         bug!("use of constant whose type is a parameter inside a pattern")
                     }
+                    traits::NonStructuralMatchTy::Dynamic => {
+                        // span_fatal avoids ICE in hair.
+                        self.tcx()
+                            .sess
+                            .span_fatal(self.span, "trait object cannot be used in patterns");
+                    }
```
Comment (eddyb) [inline src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: What you want is changes [like these](https://github.com/rust-lang/rust/pull/70872/files#diff-0f60550338d653b11927293df0fef39aL103-R121) (but `Dynamic` instead of `RawPtr`/`FnPtr`).

We should not add any new fatal errors to `rustc`.

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: This fatal error masks an ICE in `fold_const_value_deref`. https://github.com/rust-lang/rust/blob/e82734e56b2a50d38e0937d08f559d15dbe8e46b/src/librustc_mir_build/hair/pattern/_match.rs#L318

Looking into fixing that one rn

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: simple returning val in that case causes an ICE in codegen_fulfill_obligations, fixing this cleanly is currently below my minimum effort/reward ratio
https://github.com/rust-lang/rust/blob/e82734e56b2a50d38e0937d08f559d15dbe8e46b/src/librustc_trait_selection/traits/codegen/mod.rs#L61

Comment (eddyb) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: Can you push your changes? I have a hard time understand how it gets that far.

Worse case you can make `to_pat` return `PatKind::Wild` in that case, but it should be hitting the `span_fatal` lower down.

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs]: pushed my current progress for now.

File: src/librustc_mir_build/hair/pattern/const_to_pat.rs [hunk 2]
```diff
@@ -106,6 +106,13 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
                     traits::NonStructuralMatchTy::Param => {
                         bug!("use of constant whose type is a parameter inside a pattern")
                     }
+                    traits::NonStructuralMatchTy::Dynamic => {
+                        // span_fatal avoids ICE in hair.
+                        self.tcx()
+                            .sess
+                            .struct_span_err(self.span, "trait object cannot be used in patterns").emit();
+                        return inlined_const_as_pat;
```
Comment (eddyb) [inline src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: This is not what I suggested. What I was pointing to was this: https://github.com/rust-lang/rust/blob/458bae55e7130e817dfa4e9380848c200c1e8e99/src/librustc_mir_build/hair/pattern/const_to_pat.rs#L104-L122

That `msg` variable is then used instead of `make_msg()` below.

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs]: it doesn't change the returned pat though. Still causes the same ICE

`error: internal compiler error: src/librustc_trait_selection/traits/codegen/mod.rs:61: Encountered error `Unimplemented` selecting `Binder(<dyn std::cmp::PartialEq<u32> as std::cmp::PartialEq>)` during codegen`

File: src/librustc_mir_build/hair/pattern/const_to_pat.rs [hunk 3]
```diff
@@ -101,27 +101,21 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
...
+                            path, path,
+                        )
                     }
                     traits::NonStructuralMatchTy::Dynamic => {
-                        // span_fatal avoids ICE in hair.
-                        self.tcx()
-                            .sess
-                            .struct_span_err(self.span, "trait object cannot be used in patterns").emit();
-                        return inlined_const_as_pat;
+                        format!("ok")
```
Comment (eddyb) [inline src/librustc_mir_build/hair/pattern/const_to_pat.rs:114]: `"trait objects cannot be used in patterns"` would be fine as a message.

File: src/librustc_mir_build/hair/pattern/const_to_pat.rs [hunk 4]
```diff
@@ -145,13 +146,13 @@ impl<'a, 'tcx> ConstToPat<'a, 'tcx> {
 
                 if !ty_is_partial_eq {
                     // span_fatal avoids ICE from resolution of non-existent method (rare case).
-                    self.tcx().sess.span_fatal(self.span, &make_msg());
+                    self.tcx().sess.span_fatal(self.span, &msg);
```
Comment (eddyb) [inline src/librustc_mir_build/hair/pattern/const_to_pat.rs:149]: Doesn't this stop your ICE as well?

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:149]: nope. `ty_is_partial_eq` is `true` for `&dyn PartialEq<u32>`.  It is fixed for all other traits though.

This fails correctly
```rust
const F: &'static dyn Send = &7u32;

fn main() {
    let a: &dyn Send = &7u32;
    match a {
        F => panic!(),
        //~^ ERROR trait object cannot be used in patterns
        _ => {}
    }
}
```

Comment (eddyb) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:149]: > It is fixed for all other traits though.

Ah I see. I think it's fine to leave `dyn PartialEq` an ICE (and we can do an ICE test, I think we have another one already). At least that's what this comment makes me think: https://github.com/rust-lang/rust/blob/32fb4dcdd7a57683a639a0959442711d0fd123bc/src/librustc_mir_build/hair/pattern/_match.rs#L317

@oli-obk has a PR that should allow fixing this more directly: #70743

Comment (lcnr) [reply src/librustc_mir_build/hair/pattern/const_to_pat.rs:149]: I changed the test to `dyn Send` and rebased.

Don't know how to test for an ICE, we could just open an issue for `dyn PartialEq` after this is merged (which is then added to glacier).

**Comment by Dylan-DPC** [comment]
@pnkfelix this is ready for review

File: src/test/ui/const-generics/issues/issue-63322-forbid-dyn.rs [hunk 5]
```diff
@@ -0,0 +1,15 @@
+#![feature(const_generics)]
+//~^ WARN the feature `const_generics` is incomplete and may cause the compiler to crash
+
+trait A {}
+struct B;
+impl A for B {}
+
+fn test<const T: &'static dyn A>() {
+    //~^ ERROR the types of const generic parameters must derive `PartialEq` and `Eq`
```
Comment (pnkfelix) [inline src/test/ui/const-generics/issues/issue-63322-forbid-dyn.rs:9]: The PR seems fine and I'm planning to r+ it, but I wanted to ask about this part:

Do you see the error here as being the absence of `PartialEq` and `Eq`, as indicated by the diagnostic? Or is it that any use of `dyn A` will be broken here?

I personally suspect that, unless we expose a `StructuralMatch` marker trait (at which point maybe one would be able to do `trait A: StructuralMatch {}`), the user error here is in the use of `dyn A`, and therefore the diagnostic message in this case is misleading.

But I'm willing to deal with that in a followup patch.

Comment (lcnr) [reply src/test/ui/const-generics/issues/issue-63322-forbid-dyn.rs:9]: Not sure tbh, I think that we should allow something like `trait A: StructuralMatch {}` in the future.

cc @eddyb i guess

**Comment by Dylan-DPC** [comment]
failed in rollup

@bors r-

**Comment by lcnr** [comment]
fixed

**Comment by lcnr** [comment]
@pnkfelix This should be ready for merge afaict.

File: src/librustc_trait_selection/traits/structural_match.rs [hunk 6]
```diff
@@ -137,6 +138,10 @@ impl<'a, 'tcx> TypeVisitor<'tcx> for Search<'a, 'tcx> {
                 self.found = Some(NonStructuralMatchTy::Param);
                 return true; // Stop visiting.
             }
+            ty::Dynamic(..) => {
+                self.found = Some(NonStructuralMatchTy::Dynamic);
+                return true; // Stop visiting.
+            }
```
Comment (RalfJung) [inline src/librustc_trait_selection/traits/structural_match.rs:144]: So this looks like we have a fall-through clause here that by default *accepts* all types? Isn't that *incredibly dangerous*, also when new variants are added?
Any match that checks soundness things should be exhaustive, or at the least have a fallback that is safe. Here the fallback evidently was not safe.

Comment (lcnr) [reply src/librustc_trait_selection/traits/structural_match.rs:144]: https://github.com/rust-lang/rust/pull/72153
