### PR TITLE
Let `#[allow(unstable_name_collisions)]` work for things other than function

### LINKED ISSUE #81522: `#[allow(unstable_name_collisions)]` doesn't work at block scope
This code gives a warning on the latest nightly:
 
```rust
trait OptionExt<T> {
    unsafe fn unwrap_unchecked(self) -> T;
}

impl<T> OptionExt<T> for Option<T> {
    unsafe fn unwrap_unchecked(self) -> T {
        self.unwrap_or_else(|| std::hint::unreachable_unchecked())
    }
}

fn main() {
    #[allow(unstable_name_collisions)] {
        println!("{}", unsafe { Some("hello").unwrap_unchecked() });
    }
}
```

```
warning: a method with this name may be added to the standard library in the future
  --> src/main.rs:13:47
   |
13 |         println!("{}", unsafe { Some("hello").unwrap_unchecked() });
   |                                               ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unstable_name_collisions)]` on by default
   = warning: once this method is added to the standard library, the ambiguity may cause an error or change in behavior!
   = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
   = help: call with fully qualified syntax `OptionExt::unwrap_unchecked(...)` to keep using the current method
   = help: add `#![feature(option_result_unwrap_unchecked)]` to the crate attributes to enable `Option::<T>::unwrap_unchecked`
```

The warning is correct: #81383 added `Option::unwrap_unchecked` so this code is a future incompatibility hazard. The bug is that `#[allow(unstable_name_collisions)]` does not suppress the lint, although it works at function scope.

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (d1aed50ab 2021-01-26)
binary: rustc
commit-hash: d1aed50ab81df3140977c610c5a7d00f36dc519f
commit-date: 2021-01-26
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### PR DESCRIPTION
**Pull request by magurotuna**
Fixes #81522

In addition to the report in #81522, currently `#[allow(unstable_name_collisions)]` doesn't suppress the corresponding diagnostics even if this attribute is appended to an expression statement or a let statement. It seems like this is because the wrong `HirId` is passed to `struct_span_lint_hir`. 
It's fixed in this PR, and a regression test for it is also added.

### CODE REVIEW

**Comment by magurotuna** [comment]
Hmm, according to the CI, my fix doesn't work for macro invocations (so I made this PR drafted for now). But perhaps is it expected behavior? In fact, take the following as an example:

```rust
macro_rules! foo {
    ($i:ident) => {
        let $i = 42;
    };
}

fn main() {
    #[allow(unused_variables)]
    foo!(a);
}
```

`#[allow(unused_variables)]` in the above example doesn't suppress the lint diagnostic:

```
warning: unused variable: `a`
 --> src/main.rs:3:13
  |
3 |         let $i = 42;
  |             ^^ help: if this is intentional, prefix it with an underscore: `_a`
...
9 |     foo!(a);
  |     -------- in this macro invocation
  |
  = note: `#[warn(unused_variables)]` on by default
  = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 1 warning emitted
```

However, if the attribute is appended to `main` function like:

```rust
macro_rules! foo {
    ($i:ident) => {
        let $i = 42;
    };
}

#[allow(unused_variables)]
fn main() {
    foo!(a);
}
```

then it _does_ suppress the lint!
So I'm wondering if I should take macro invocations into account in this PR or not... 😕

File: compiler/rustc_typeck/src/check/method/probe.rs [hunk 1]
```diff
@@ -1511,6 +1519,7 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
                 self.orig_steps_var_values.clone(),
                 steps,
                 IsSuggestion(true),
+                scope_expr_id,
```
Comment (matthewjasper) [inline compiler/rustc_typeck/src/check/method/probe.rs:1522]: Can this be `self.scope_expr_id`?

Comment (magurotuna) [reply compiler/rustc_typeck/src/check/method/probe.rs]: That's correct! Fixed it.
