### PR TITLE
Use `getuid` to check instead of `USER` env var in rustbuild

### LINKED ISSUE #100459: Rust 1.63.0 fails to build with: error: failed to download `addr2line v0.16.0`
Trying to build Rust 1.63.0 it fails with the error below:

```
$ python3 ./x.py build --exclude src/tools/miri
Building rustbuild
    Updating crates.io index
  Downloaded cfg-if v1.0.0
  Downloaded opener v0.5.0
  Downloaded serde v1.0.125
  Downloaded sha2 v0.10.1
  Downloaded serde_derive v1.0.125
  Downloaded lazy_static v1.4.0
  Downloaded same-file v1.0.6
  Downloaded version_check v0.9.3
  Downloaded toml v0.5.7
  Downloaded xattr v0.2.2
  Downloaded pkg-config v0.3.18
  Downloaded unicode-width v0.1.8
  Downloaded tar v0.4.38
  Downloaded walkdir v2.3.2
  Downloaded regex v1.5.5
  Downloaded num_cpus v1.13.1
  Downloaded ryu v1.0.5
  Downloaded regex-syntax v0.6.25
  Downloaded cmake v0.1.44
  Downloaded typenum v1.12.0
  Downloaded itoa v0.4.6
  Downloaded proc-macro2 v1.0.37
  Downloaded xz2 v0.1.6
  Downloaded syn v1.0.91
  Downloaded log v0.4.14
  Downloaded cpufeatures v0.2.1
  Downloaded lzma-sys v0.1.16
  Downloaded libc v0.2.126
  Downloaded thread_local v1.1.4
  Downloaded crossbeam-utils v0.8.8
  Downloaded unicode-xid v0.2.2
  Downloaded cc v1.0.69
  Downloaded hex v0.4.2
  Downloaded generic-array v0.14.4
  Downloaded memchr v2.4.1
  Downloaded aho-corasick v0.7.18
  Downloaded block-buffer v0.10.2
  Downloaded fnv v1.0.7
  Downloaded getopts v0.2.21
  Downloaded regex-automata v0.1.10
  Downloaded quote v1.0.18
  Downloaded once_cell v1.12.0
  Downloaded ignore v0.4.17
  Downloaded globset v0.4.5
  Downloaded filetime v0.2.14
  Downloaded digest v0.10.2
  Downloaded crypto-common v0.1.2
  Downloaded bstr v0.2.13
  Downloaded serde_json v1.0.59
  Downloaded 49 crates (3.7 MB) in 0.48s
    Finished dev [unoptimized] target(s) in 44.74s
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
error: failed to download `addr2line v0.16.0`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
Build completed unsuccessfully in 0:00:45
```

### PR DESCRIPTION
**Pull request by Samyak2**
This makes it consistent with `x.py` as changed in #95671

Fixes #100459

### CODE REVIEW

File: src/bootstrap/lib.rs [hunk 1]
```diff
@@ -170,6 +170,8 @@ use crate::cache::{Interned, INTERNER};
 pub use crate::config::Config;
 pub use crate::flags::Subcommand;
 
+use libc;
```
Comment (Mark-Simulacrum) [inline src/bootstrap/lib.rs:173]: I think this shouldn't be necessary? Did you see compilation failures without it?

File: src/bootstrap/lib.rs [hunk 2]
```diff
@@ -397,10 +399,10 @@ impl Build {
         let out = config.out.clone();
 
         let is_sudo = match env::var_os("SUDO_USER") {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/lib.rs:401]: Can you add a comment pointing to bootstrap.py's equivalent check (and also on that check pointing to here)?

File: src/bootstrap/lib.rs (hunk 1 above)
Comment (Samyak2) [reply src/bootstrap/lib.rs:173]: Oh it does work without the `use`. I assumed it would be needed since it's not declared anywhere in the module. Is it included in the prelude just for `rustbuild`?

Comment (Mark-Simulacrum) [reply src/bootstrap/lib.rs]: libc is an external crate and since the 2018 edition, those are available without explicit use statements (well, extern crate).

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed

File: src/bootstrap/lib.rs (hunk 1 above)
Comment (Samyak2) [reply src/bootstrap/lib.rs]: Ah right, of course. It slipped my mind that `use` is used to alias paths

**Comment by Mark-Simulacrum** [comment]
Also going to approve for beta-backport as a small patch that fixes a stable/stable regression.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/100931#issuecomment-1225059031
@bors r-

**Comment by Mark-Simulacrum** [comment]
Hm, that's annoying. My guess is that this is not really relevant outside cfg(unix) because SUDO_USER won't be defined - but maybe Windows also has sudo?

Let's try to see what the python getuid() equivalent does on Windows, if anything, and go from there.

**Comment by bjorn3** [comment]
Windows has runas, which is somewhat similar to sudo, but it doesn't set SUDO_USER.

**Comment by Mark-Simulacrum** [comment]
Alright. Then I think putting a #[cfg(unix)] on the condition is reasonable.

**Comment by Samyak2** [comment]
Python's [`os.getuid()`](https://docs.python.org/3/library/os.html#os.getuid) is not available on Windows either:
```python
>>> import os
>>> os.getuid()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'getuid'
```

---

> Alright. Then I think putting a #[cfg(unix)] on the condition is reasonable.

In that case, will `is_sudo` be set to false on other platforms?

**Comment by Mark-Simulacrum** [comment]
Yes, that would make sense to me.

File: src/bootstrap/lib.rs [hunk 3]
```diff
@@ -396,13 +396,18 @@ impl Build {
         let src = config.src.clone();
         let out = config.out.clone();
 
+        #[cfg(unix)]
```
Comment (Samyak2) [inline src/bootstrap/lib.rs:399]: I wasn't sure if I had to wrap the statement below in a block. Should I?

Comment (Mark-Simulacrum) [reply src/bootstrap/lib.rs:399]: This should be fine.
