### PR TITLE
diagnostics: exclude indirect private deps from trait impl suggest

### LINKED ISSUE #88696: Suggestions for miniz_oxide included in diagnostics in crate with no dependencies
So, I was just chatting a bit with rustc and I was saying:

```rust
#![feature(never_type)]

fn a() -> Result<!, i32> {
    Err(1)
}

fn b() -> Result<u32, i32> {
    a().into()
}

fn main() {
    let _ = dbg!(b());
}
```

And then rustc said:

```
error[E0277]: the trait bound `Result<u32, i32>: From<Result<!, i32>>` is not satisfied
 --> src/main.rs:8:9
  |
8 |     a().into()
  |         ^^^^ the trait `From<Result<!, i32>>` is not implemented for `Result<u32, i32>`
  |
```

And I was like, *sure, whatever you say*.

But *then* rustc told me:

```
  = help: the following implementations were found:
            <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<&miniz_oxide::StreamResult>>
            <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<miniz_oxide::StreamResult>>
```

And I was like, *excuse me what??*

---

This crate has no dependencies. (Just an empty `cargo new ..` package.)

This happens on at least:
- rustc 1.55.0-nightly (014026d1a 2021-07-19)
- rustc 1.56.0-nightly (ccffcafd5 2021-08-11)
- rustc 1.57.0-nightly (5d2a410ff 2021-09-04)

(On `x86_64-unknown-linux-gnu` and other platforms where `backtrace` is enabled in `std`, such that `miniz_oxide` is pulled in as a dependency of `std`.)

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #88696

### CODE REVIEW

File: compiler/rustc_metadata/src/creader.rs [hunk 1]
```diff
@@ -558,10 +560,11 @@ impl<'a, 'tcx> CrateLoader<'a, 'tcx> {
                     dep_kind = CrateDepKind::MacrosOnly;
                 }
                 data.update_dep_kind(|data_dep_kind| cmp::max(data_dep_kind, dep_kind));
+                data.update_private_dep(|private_dep| private_dep && private_dep);
```
Comment (cjgillot) [inline compiler/rustc_metadata/src/creader.rs:563]: This line does nothing. Did you mean this?

```suggestion
                data.update_private_dep(|p_d| p_d && private_dep);
```

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 2]
```diff
@@ -111,7 +111,7 @@ pub(crate) struct CrateMetadata {
     source: Lrc<CrateSource>,
     /// Whether or not this crate should be consider a private dependency
     /// for purposes of the 'exported_private_dependencies' lint
-    private_dep: bool,
+    private_dep: Lock<bool>,
```
Comment (b-naber) [inline compiler/rustc_metadata/src/rmeta/decoder.rs:114]: `AtomicBool` should suffice here.

**Review by b-naber — COMMENTED** [review]
The approach seems better than the previous one, but I'm not sure I fully understand what you're doing here since I don't really know the code in `rustc_metadata`.

**Comment by b-naber** [comment]
r? rust-lang/compiler

File: library/std/tests/common/mod.rs [hunk 3]
```diff
@@ -1,5 +1,7 @@
 #![allow(unused)]
 
+#![allow(exported_private_dependencies)]
```
Comment (cjgillot) [inline library/std/tests/common/mod.rs:3]: Why is this needed?

File: compiler/rustc_metadata/src/rmeta/decoder.rs [hunk 4]
```diff
@@ -109,9 +110,10 @@ pub(crate) struct CrateMetadata {
     dep_kind: Lock<CrateDepKind>,
     /// Filesystem location of this crate.
     source: Lrc<CrateSource>,
-    /// Whether or not this crate should be consider a private dependency
-    /// for purposes of the 'exported_private_dependencies' lint
-    private_dep: bool,
+    /// Whether or not this crate should be consider a private dependency.
+    /// Used by the 'exported_private_dependencies' lint, and for determining
+    /// whether to emit suggestions that reference this crate.
+    private_dep: AtomicBool,
```
Comment (klensy) [inline compiler/rustc_metadata/src/rmeta/decoder.rs:116]: Or maybe use https://github.com/rust-lang/rust/blob/dfe31889e10e36eed53327d1ca624fbf21b475a5/compiler/rustc_data_structures/src/sync.rs#L24?

File: compiler/rustc_middle/src/ty/util.rs [hunk 5]
```diff
@@ -808,6 +808,26 @@ impl<'tcx> TyCtxt<'tcx> {
...
+        // |---------|--------|---------|--------------------|
+        // | Yes     | Yes    | Yes     | !(true && !true)   |
+        // | No      | Yes    | Yes     | !(false && !true)  |
+        // | Yes     | No     | No      | !(true && !false)  |
+        // | No      | No     | Yes     | !(false && !false) |
+        !(self.is_private_dep(key)
+            // If `extern_crate` is `None`, then the crate was injected (e.g., by the allocator).
+            // Treat that kind of crate as "indirect", since it's an implementation detail of
+            // the language.
+            && !self.extern_crate(key.as_def_id()).map_or(false, |e| e.is_direct()))
```
Comment (cjgillot) [inline compiler/rustc_middle/src/ty/util.rs:829]:
```suggestion
        // | Yes     | Yes    | Yes     | !true || true   |
        // | No      | Yes    | Yes     | !false || true  |
        // | Yes     | No     | No      | !true || false  |
        // | No      | No     | Yes     | !false || false |
        !self.is_private_dep(key)
            // If `extern_crate` is `None`, then the crate was injected (e.g., by the allocator).
            // Treat that kind of crate as "indirect", since it's an implementation detail of
            // the language.
            || self.extern_crate(key.as_def_id()).map_or(false, |e| e.is_direct()))
```

**Review by cjgillot — COMMENTED** [review]
I only have 2 nits. I'd like to get some input from the bootstrap team, as this PR introduces RUSTC_BOOTSTRAP=1 in a few places. cc @Mark-Simulacrum (or please reassign)

File: src/bootstrap/dist.rs [hunk 6]
```diff
@@ -1013,6 +1013,7 @@ impl Step for PlainSourceTarball {
                 .arg(builder.src.join("./compiler/rustc_codegen_cranelift/Cargo.toml"))
                 .arg("--sync")
                 .arg(builder.src.join("./src/bootstrap/Cargo.toml"))
+                .env("RUSTC_BOOTSTRAP", "1")
```
Comment (klensy) [inline src/bootstrap/dist.rs:1016]: Add similar comment as for other `RUSTC_BOOTSTRAP` here too?

File: compiler/rustc_data_structures/src/sync.rs [hunk 7]
```diff
@@ -143,6 +143,11 @@ cfg_if! {
                 self.0.set(val);
                 result
             }
+            pub fn fetch_and(&self, val: bool, _: Ordering) -> bool {
+                let result = self.0.get() & val;
+                self.0.set(val);
+                result
```
Comment (lukas-code) [inline compiler/rustc_data_structures/src/sync.rs:149]: This currently does `self.swap(val) & val`, not `self.fetch_and(val)`. Same for the "`fetch_or`" above.

```suggestion
                let old = self.0.get();
                self.0.set(old & val);
                old
```

**Comment by danakj** [comment]
Hey, it looks like this PR breaks building the toolchain with the Cargo binaries specified in https://github.com/rust-lang/rust/blob/master/src/stage0.json#L28-L83

The public-dependencies feature is a nightly feature, but the Cargo given there is beta.

```
linux_upload_rust log:
 Downloading https://chrome-infra-packages.appspot.com/dl/infra/3pp/static_libs/openssl/linux-amd64/+/version:2@1.1.1j.chromium.2 .......... Done.
 Downloading https://static.rust-lang.org/dist/2023-05-30/cargo-beta-x86_64-unknown-linux-gnu.tar.gz .......... Done.
 Running git submodule update --init --recursive --depth 1
 Running /b/s/w/ir/cache/builder/src/third_party/llvm-build-tools/cargo-beta-x86_64-unknown-linux-gnu/cargo/bin/cargo vendor --locked --versioned-dirs --sync ./src/tools/cargo/Cargo.toml --sync ./src/tools/rust-analyzer/Cargo.toml --sync ./compiler/rustc_codegen_cranelift/Cargo.toml --sync ./src/bootstrap/Cargo.toml
 error: failed to load manifest for workspace member `/b/s/w/ir/cache/builder/src/third_party/rust_src/src/library/std`
 
 Caused by:
   failed to parse manifest at `/b/s/w/ir/cache/builder/src/third_party/rust_src/src/library/std/Cargo.toml`
 
 Caused by:
   the cargo feature `public-dependency` requires a nightly version of Cargo, but this is the `beta` channel
   See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
   See https://doc.rust-lang.org/beta/cargo/reference/unstable.html#public-dependency for more information about using this feature.
 Failed.
 Failed cargo vendor, retrying...
 Running git submodule update --init --recursive --depth 1
 Running /b/s/w/ir/cache/builder/src/third_party/llvm-build-tools/cargo-beta-x86_64-unknown-linux-gnu/cargo/bin/cargo vendor --locked --versioned-dirs --sync ./src/tools/cargo/Cargo.toml --sync ./src/tools/rust-analyzer/Cargo.toml --sync ./compiler/rustc_codegen_cranelift/Cargo.toml --sync ./src/bootstrap/Cargo.toml
 error: failed to load manifest for workspace member `/b/s/w/ir/cache/builder/src/third_party/rust_src/src/library/std`
 
 Caused by:
   failed to parse manifest at `/b/s/w/ir/cache/builder/src/third_party/rust_src/src/library/std/Cargo.toml`
 
 Caused by:
   the cargo feature `public-dependency` requires a nightly version of Cargo, but this is the `beta` channel
   See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
   See https://doc.rust-lang.org/beta/cargo/reference/unstable.html#public-dependency for more information about using this feature.
 Failed.
```

How do we continue building the toolchain in this state?

Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1450894

**Comment by bjorn3** [comment]
I don't think `RUSTC_BOOTSTRAP` should be suggested. The cargo version used to vendor may not support `public-dependency` or it may have an incompatible implementation. By the way I opened https://github.com/rust-lang/rust/issues/112391 a couple of days ago as I didn't notice this discussion.
