### PR TITLE
[rustdoc] Display total time and compilation time of merged doctests

### LINKED ISSUE #144270: Doctest execution should report discovery and compilation time
Consider the following output from running doctests:

```rust
$ time cargo test -p all-is-cubes-base --doc
    Finished `test` profile [optimized + debuginfo] target(s) in 0.06s
   Doc-tests all_is_cubes_base

running 60 tests
test all-is-cubes-base/src/math.rs - math::notnan (line 60) ... ok
test all-is-cubes-base/src/math/aab.rs - math::aab::Aab::round_up_to_grid (line 331) ... ok
[...]
test all-is-cubes-base/src/resolution.rs - resolution::Resolution::log2 (line 70) ... ok

test result: ok. 60 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s


running 4 tests
test all-is-cubes-base/src/math.rs - math::notnan (line 76) - compile fail ... ok
test all-is-cubes-base/src/math.rs - math::notnan (line 91) - compile fail ... ok
test all-is-cubes-base/src/math.rs - math::notnan (line 69) - compile fail ... ok
test all-is-cubes-base/src/math.rs - math::notnan (line 83) - compile fail ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.55s


real	0m10.268s
user	0m6.745s
sys	0m6.373s
```

The wall-clock time taken to run this test command is 10 s. The *reported* time to run these tests is 0.06 s + 0.01 s + 1.55 s, which only adds up to 1.62 s — the time spent discovering and compiling the doctests is not counted and reported. I believe this is a “diagnostic bug” of sorts — information is being omitted which misleads the user about the performance of their project’s test suite (until they carefully watch it progress in real time).

I believe this is caused by [merged doctests](https://github.com/rust-lang/rust/pull/126245), in that if I add <code>```standalone_crate</code> to a doctest, it moves down to the second section and increases the reported time. (But, of course, that also increases the total time needed, so it does not help someone who wishes to improve performance of their test suite.)

It would be ideal if the compilation time was reported separately from the execution time (except for compile-fail tests) so the test author can direct their attention to the right part of the problem. However, it seems that would require either expanding libtest’s `OutputFormatter` trait or writing output outside of it (to stderr?).

# Version
rustdoc 1.88.0 (6b00bc388 2025-06-23)

@rustbot label +A-doctests +A-libtest +T-rustdoc +T-testing-devex

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#144270.

Does it look good to you @kpreid?

image

### CODE REVIEW

**Comment by kpreid** [comment]
> Does it look good to you @kpreid?

This seems sufficient, in that it communicates the missing information, separately.

However, there is a way in which I predict it will be frequently confusing: there is no spatial or textual association of "merged doctests compilation took…" with which tests are the merged ones. A user wanting to know which doctests this refers to has to reason about what 'merged doctests' means and then, using that fact, figure out they must be the first group since the second group has compile-fail tests.

I strongly recommend that the report of compilation time should not be separated from the tests it refers to by unrelated tests.

When I initially imagined quickly adding this feature, I imagined putting the doctest compilation time at the top, corresponding to when it actually happens, and thus also adjacent to the merged tests. Another option would be to label the group of merged tests as merged, somehow.

**Comment by GuillaumeGomez** [comment]
You can have multiple merged doctests groups, so unless we show it for each group, I'm not sure it's really useful. It tells how much time it spent compiling merged doctests and the total time for all doctests.

**Comment by kpreid** [comment]
Ah, I see, I wasn't aware that there was a possibility of multiple groups. I don't have any further ideas. Thank you for working on this.

File: src/librustdoc/doctest.rs [hunk 1]
```diff
@@ -36,6 +37,47 @@ use crate::config::{Options as RustdocOptions, OutputFormat};
 use crate::html::markdown::{ErrorCodes, Ignore, LangString, MdRelLine};
 use crate::lint::init_lints;
 
+/// Type used to display times (compilation and total) information for merged doctests.
+struct MergedDoctestTimes {
+    total_time: Instant,
+    compilation_time: Duration,
+    /// This field is used to keep track of how many merged doctests we (tried to) compile.
+    added_compilation_times: usize,
+}
```
Comment (lolbinarycat) [inline src/librustdoc/doctest.rs]:
```suggestion
struct DoctestTimes {
    compilation_start: Instant,
    /// Total time spent compiling all merged doctests
    merged_compilation_time: Duration,
    /// This field is used to keep track of how many merged doctests we (tried to) compile.
    merged_doctest_count: usize,
}
```

Since this tracks time for standalone *and* merged doctests, I think these names would be more clear.

Also, is it possible for multiple merged doctest groups to get compiled in parallel? if so, that could cause some confusion due to the total time actually being shorter.

File: src/librustdoc/doctest.rs [hunk 2]
```diff
@@ -36,6 +37,47 @@ use crate::config::{Options as RustdocOptions, OutputFormat};
...
+impl fmt::Display for MergedDoctestTimes {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(
+            f,
+            "all doctests ran in {:.2}s; merged doctests compilation took {:.2}s",
+            self.total_time.elapsed().as_secs_f64(),
+            self.compilation_time.as_secs_f64(),
+        )
+    }
+}
```
Comment (lolbinarycat) [inline src/librustdoc/doctest.rs]: Shouldn't we still print the total compilation time, even if there are no merged doctests?

File: src/librustdoc/doctest.rs [hunk 3]
```diff
@@ -501,11 +548,12 @@ fn run_test(
     rustdoc_options: &RustdocOptions,
     supports_color: bool,
     report_unused_externs: impl Fn(UnusedExterns),
-) -> Result<(), TestFailure> {
+) -> (Duration, Result<(), TestFailure>) {
```
Comment (lolbinarycat) [inline src/librustdoc/doctest.rs:556]: There should be a comment explaining that this is the time taken for *compilation*, not the total time overall.

File: src/librustdoc/doctest.rs [hunk 4]
```diff
@@ -36,6 +37,47 @@ use crate::config::{Options as RustdocOptions, OutputFormat};
...
+            println!("{self}");
+        }
+    }
+}
+
+impl fmt::Display for MergedDoctestTimes {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(
+            f,
+            "all doctests ran in {:.2}s; merged doctests compilation took {:.2}s",
```
Comment (lolbinarycat) [inline src/librustdoc/doctest.rs:77]:
```suggestion
            "all doctests compiled in {:.2}s; merged doctests compilation took {:.2}s",
```

misleading string, this only measures compilation time

File: src/librustdoc/doctest.rs [hunk 5]
```diff
@@ -1071,7 +1120,7 @@ fn doctest_run_fn(
         no_run: scraped_test.no_run(&rustdoc_options),
         merged_test_code: None,
     };
-    let res =
+    let (_, res) =
```
Comment (lolbinarycat) [inline src/librustdoc/doctest.rs:1128]: Is there a reason we're not also tracking this, so we can report `(time compiling standalone tests, time compiling merged tests)`?

I believe doctests are run with some level of parallelism, so currently we would be reporting the total absolute wall clock time for the total compilation time, but for merged doctests, we're reporting the sum of the amount of time each thread spent compiling.  This inconsistency could over-report the impact of merged doctests.

Also, if parallelism is involved, then I think perhaps a more useful metric for minimizing compilation time would be how long the *longest* test took.

**Review by lolbinarycat — CHANGES_REQUESTED** [review]

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: Not currently at least and I don't think we're planning to. That could potentially use too much resources.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: No because in this case, the numbers displayed by `libtest` are already accurate.

File: src/librustdoc/doctest.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:77]: Euh no. It measures the total time.

File: src/librustdoc/doctest.rs (hunk 3 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:556]: Indeed, gonna add some comments.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: Some extra info: for standalone tests, `libtest` reports both compilation and run time as each doctest passed to `libtest` will call the `doctest_run_fn` which handles both.

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: I added the comments, however I didn't rename the type as it is only used for merged doctests and therefore didn't update the field name either.

Comment (lolbinarycat) [reply src/librustdoc/doctest.rs]: the total time is the total time for all doctests, though??

Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: Yes but it's only run in merged doctests context.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (lolbinarycat) [reply src/librustdoc/doctest.rs]: hm, that's odd, that's what i thought initially, but the numbers in the screenshot simply don't add up for that to be the case.  not sure what's happening here.

Comment (lolbinarycat) [reply src/librustdoc/doctest.rs]: in any case, the comment explaining the rationale for ommitting all the output seems incomplete and mildly misleading.

File: src/librustdoc/doctest.rs (hunk 4 above)
Comment (lolbinarycat) [reply src/librustdoc/doctest.rs:77]: i got confused by the inconsistencies of the times in the screenshot, i think.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: Ah indeed, the total seems messed up. Gonna need to investigate what's going on.

Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: So calculation is:

```
merged compilation times + standalone run times + merged run times = total time
```

With the screenshot numbers:

```
1.24 + 0.43 + 0.05 = 1.72
```

That seems to match the numbers. Did I miss something?

File: src/librustdoc/doctest.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:1128]: We only compile and run standalone tests in parallel, merged doctests are never compiled in parallel (but still run in parallel).

We report raw numbers. Also we cannot get which tests took the longest to run as only `libtest` has this information in theory (but they don't keep track of it). Finally, I don't see how this is an issue to say how much time was spent in compiling merged doctests.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (lolbinarycat) [reply src/librustdoc/doctest.rs]: ah, i see it now, i wasn't looking at the top section because i've never seen the output for a crate with both standalone and merged doctests, and i didn't expect then to be printed in seperate groups.

i'm not sure if the output is confusing or it's just me, but maybe if the time taken for merged doctest compilation was printed right before the merged doctests were run, that would be more intuitive, saying the times for things as they happen?

i would say we should just add a comment somewhere, but that won't make it more intuitive for users..

but maybe making this 10% more intuitive isn't worth the extra implement effort, i don't know how hard it would be to print things in that order.

another possibility is when it says "running N tests" make it say "running N merged doctests" or "running N standalone doctests" so its more obvious what number refers to what.

Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: > i'm not sure if the output is confusing or it's just me, but maybe if the time taken for merged doctest compilation was printed right before the merged doctests were run, that would be more intuitive, saying the times for things as they happen?

What happens if the merged doctests compilation failed then? We still need to show this number but then it's followed by standalone doctests. Seems even more confusing imo.

Putting this information at the end sounds the less confusing option to me.

> another possibility is when it says "running N tests" make it say "running N merged doctests" or "running N standalone doctests" so its more obvious what number refers to what.

Sounds like an improvement that can be sent as a follow-up.

Comment (lolbinarycat) [reply src/librustdoc/doctest.rs]: > What happens if the merged doctests compilation failed then? We still need to show this number but then it's followed by standalone doctests. Seems even more confusing imo.

I don't know why it would be printed before the standalone tests instead of after them, but I'll trust that there's some implementation detail I don't know of.

> Sounds like an improvement that can be sent as a follow-up.

Sounds good!

Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs]: > > What happens if the merged doctests compilation failed then? We still need to show this number but then it's followed by standalone doctests. Seems even more confusing imo.
> 
> I don't know why it would be printed before the standalone tests instead of after them, but I'll trust that there's some implementation detail I don't know of.

This is nothing about technical details, just me trying to underlying that multiplying output is never desirable because of different potential cases. Your starting point was that the current output could be confusing and suggesting some alternatives. And I replied on the suggested alternative, with an example where we might display information about compile time for merged doctests that actually don't appear anywhere (because the compilation failed, reverting them to standalone doctests).

Anyway, even if not perfect, I think the current display is a nice first step.

**Review by lolbinarycat — APPROVED** [review]

**Comment by arpadav** [comment]
@GuillaumeGomez this is breaks the `--format json` unstable option, since the time displayed goes to stdout. as a result, if you run something like:

```rust
cargo +nightly test --doc -- -Z unstable-options --format json > doc-test.json
```

then

```json
...
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "ignored": 5, "measured": 0, "filtered_out": 0, "exec_time": 0.000229133 }
all doctests ran in 0.17s; merged doctests compilation took 0.17s
```

this line is at the end of each output. in addition, when using the `--workspace` flag, it appears after every library is doc-tested.

I assume this is not intended? It can easily be dealt with, but I realized my CICD started failing when parsing this output so I wanted to ask/report

**Comment by GuillaumeGomez** [comment]
No indeed. Please open an issue and ping me on it. I'll take a look in the next days.
