### PR TITLE
bootstrap: correctly handle doc paths within submodules

### LINKED ISSUE #135041: thread 'main' panicked at src/bootstrap/src/utils/helpers.rs:441:5
Build on Solaris fails with:

```
Submodule path 'src/doc/rust-by-example': checked out '093397535b48ae13ec76bc526b7e6eb8c096a85c'
thread 'main' panicked at src/bootstrap/src/utils/helpers.rs:441:5:
std::fs::read_dir(dir) failed with No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:03:34
```

MIght be related to https://github.com/rust-lang/rust/pull/134967 ?!

### PR DESCRIPTION
**Pull request by jieyouxu**
Fixes #135041 by passing the correct submodule path when requiring submodules. This PR changes `is_path_in_submodule` to `submodule_path_of`. `submodule_path_of` returns the path of the containing submodule when given a path nested inside a submodule we handle, and `None` otherwise.

I tested this manually locally by unregistering the `src/tools/cargo` submodule, then running `./x doc src/tools/cargo/src/doc`. This command fails on master with

```
thread 'main' panicked at src/bootstrap/src/utils/helpers.rs:441:5:
std::fs::read_dir(dir) failed with No such file or directory (os error 2)
```

since the require submodule fails as `src/tools/cargo/src/doc` is not a known submodule. Now we use the submodule path if such a nested-in-submodule-path is passed, and thus running this command with cargo submodule unregistered still succeeds:

```
Rustbook (x86_64-unknown-linux-gnu) - cargo
Doc path: /home/joe/repos/rust/build/x86_64-unknown-linux-gnu/doc/cargo/index.html
Build completed successfully in 0:00:11
```

r? @onur-ozkan

### CODE REVIEW

**Comment by jieyouxu** [comment]
Not *super* happy with how this macro still looks (it's still a bit convoluted), but at least the invocation-site is a bit nicer to use, I suppose.

There's also some pre-existing issues, such as:

- We do not really sanity-check the doc path and submodule path, e.g. that they share prefix. That if the doc is inside a submodule, that the `Step` author correctly passed a path where (1) it's a path of a submodule that we handle and (2) it's the *same* submodule as where the doc resides in.
- Not sure why `requires_submodule` silently fails? I think we just don't check it maybe?

File: src/bootstrap/src/core/build_steps/doc.rs [hunk 1]
```diff
@@ -34,49 +53,59 @@ macro_rules! book {
...
-        )+
-    }
+    };
 }
 
 // NOTE: When adding a book here, make sure to ALSO build the book by
 // adding a build step in `src/bootstrap/code/builder/mod.rs`!
 // NOTE: Make sure to add the corresponding submodule when adding a new book.
-// FIXME: Make checking for a submodule automatic somehow (maybe by having a list of all submodules
-// and checking against it?).
```
Comment (jieyouxu) [inline src/bootstrap/src/core/build_steps/doc.rs:69]: I think this is actually addressed by #134967.

**Comment by jieyouxu** [comment]
@onur-ozkan do you think we should fix-forward (i.e. this PR) or revert #134967 then try to reland that?

**Comment by onur-ozkan** [comment]
> @onur-ozkan do you think we should fix-forward (i.e. this PR) or revert #134967 then try to reland that?

I think we can fix it right away. I need couple minutes to review this.

File: src/bootstrap/src/core/build_steps/doc.rs [hunk 2]
```diff
@@ -20,10 +20,29 @@ use crate::core::builder::{
...
+            doc_path: $doc_path:expr
+            // Optional; only needed if `doc_path` is inside the submodule path, i.e. they are not
+            // the same.
+            $(, submodule_path: $submodule_path:expr )?
+            // Optional; only needed if the book has multi-lingual support.
+            $(, languages: $languages:expr )?
+            $( , )?
+        }
+    ) => {
+        #[derive(Debug, Clone, Hash, PartialEq, Eq)]
```
Comment (onur-ozkan) [inline src/bootstrap/src/core/build_steps/doc.rs:45]: Please correct me if I am wrong: the problem is that we are trying to update a submodule that is actually not a submodule but a subdirectory within a submodule. If that's the case, there is no need to overcomplicate this macro again (which kills the purpose of https://github.com/rust-lang/rust/pull/134967). Instead, make [is_path_in_submodule](https://github.com/onur-ozkan/rust/blob/6eb9ebf1d61131df43f18e379493e23a193c3a7c/src/bootstrap/src/utils/helpers.rs#L63-L64) to return the submodule path as `Some(path)` instead of returning `true` and return `None` instead of `false`.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/doc.rs:45]: Sounds reasonable, let me do that a bit later.

Comment (jieyouxu) [reply src/bootstrap/src/core/build_steps/doc.rs]: Changed `is_path_in_submodule` to `submodule_path_of`, which returns `Some(submodule_path)` if the destination is inside a submodule, and return `None` if it's not a submodule we handle.

**Comment by jieyouxu** [comment]
Changes since last review:

- Dropped unrelated macro changes.
- Rename `is_path_in_submodule` to `submodule_path_of`. `submodule_path_of` returns `Some(submodule_path)` if the given path is nested inside a known submodule, and `None` otherwise.
- Adjusted the helper's tests as suitable.

@rustbot ready

**Review by onur-ozkan — APPROVED** [review]
LGTM, feel free to r=me once CI goes green

File: src/bootstrap/src/core/build_steps/doc.rs (hunk 2 above)
Comment (onur-ozkan) [reply src/bootstrap/src/core/build_steps/doc.rs]: Thanks

**Comment by jieyouxu** [comment]
PR CI is 🍏 
@bors r=@onur-ozkan rollup
