### PR TITLE
ignore implied bounds with placeholders

### LINKED ISSUE #107409: ICE with generic associated types and HRTBs
Got an ICE while experimenting with GATs:

```rs
use std::marker::PhantomData as Boo;

struct Gc<'gc, T: 'gc>(Boo<fn(&'gc T) -> &'gc T>);

trait Rootable<'env> {
    type AsRoot<'r>: Rootable<'r> + 'r where 'env: 'r;
}

impl<'env, T: Rootable<'env>> Rootable<'env> for Gc<'env, T> {
    type AsRoot<'r> = Gc<'r, T::AsRoot<'r>> where 'env: 'r;
}

impl<'env> Rootable<'env> for i32 {
    type AsRoot<'r> = i32 where 'env: 'r;
}

fn reroot<'gc, T: Rootable<'gc>>(_t: T, _f: for<'a> fn(T::AsRoot<'a>)) {
}

fn test<'gc>(t: Gc<'gc, i32>) {
    reroot(t, |_| ());
}
```

This crashes with the following error:

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:828:36: cannot convert `RePlaceholder(Placeholder { universe: U1, name: BrAnon(0, None) })` to a region vid

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/compiler/rustc_errors/src/lib.rs:1609:9
stack backtrace:
   0:     0x7fc1a3ccf36a - std::backtrace_rs::backtrace::libunwind::trace::heb3166a6cb1fd02b
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fc1a3ccf36a - std::backtrace_rs::backtrace::trace_unsynchronized::h34837841e045a1d4
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc1a3ccf36a - std::sys_common::backtrace::_print_fmt::h4348a4b63f328ee4
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fc1a3ccf36a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1bad440d01eeeb29
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc1a3d3152e - core::fmt::write::hb5a073c651a6cb64
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/core/src/fmt/mod.rs:1232:17
   5:     0x7fc1a3cbf9b5 - std::io::Write::write_fmt::h97cc768331421fb2
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/io/mod.rs:1682:15
   6:     0x7fc1a3ccf135 - std::sys_common::backtrace::_print::h23bd93d6897965f3
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fc1a3ccf135 - std::sys_common::backtrace::print::h4d41ae33ce7a824f
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fc1a3cd1eff - std::panicking::default_hook::{{closure}}::h8ab48635107c713a
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/panicking.rs:267:22
   9:     0x7fc1a3cd1c3b - std::panicking::default_hook::h6305ca3c910e41d2
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/panicking.rs:286:9
  10:     0x7fc1a703e444 - rustc_driver[d1d90693eba3e117]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fc1a3cd273a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h60fe4dd8262b5528
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/alloc/src/boxed.rs:2002:9
  12:     0x7fc1a3cd273a - std::panicking::rust_panic_with_hook::ha8dfad8ee636a9a3
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/panicking.rs:692:13
  13:     0x7fc1a754dc21 - std[ef0604d174e11cd5]::panicking::begin_panic::<rustc_errors[6cf9ff966b0b62fb]::ExplicitBug>::{closure#0}
  14:     0x7fc1a754cad6 - std[ef0604d174e11cd5]::sys_common::backtrace::__rust_end_short_backtrace::<std[ef0604d174e11cd5]::panicking::begin_panic<rustc_errors[6cf9ff966b0b62fb]::ExplicitBug>::{closure#0}, !>
  15:     0x7fc1a75db2a6 - std[ef0604d174e11cd5]::panicking::begin_panic::<rustc_errors[6cf9ff966b0b62fb]::ExplicitBug>
  16:     0x7fc1a75909c6 - std[ef0604d174e11cd5]::panic::panic_any::<rustc_errors[6cf9ff966b0b62fb]::ExplicitBug>
  17:     0x7fc1a758b376 - <rustc_errors[6cf9ff966b0b62fb]::HandlerInner>::bug::<&alloc[9ea3c9e5c77b7621]::string::String>
  18:     0x7fc1a7589fd0 - <rustc_errors[6cf9ff966b0b62fb]::Handler>::bug::<&alloc[9ea3c9e5c77b7621]::string::String>
  19:     0x7fc1a759f4bb - rustc_middle[526e0ca739798ee2]::util::bug::opt_span_bug_fmt::<rustc_span[6b0f4bf036ac788e]::span_encoding::Span>::{closure#0}
  20:     0x7fc1a759f2ea - rustc_middle[526e0ca739798ee2]::ty::context::tls::with_opt::<rustc_middle[526e0ca739798ee2]::util::bug::opt_span_bug_fmt<rustc_span[6b0f4bf036ac788e]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fc1a759f2ba - rustc_middle[526e0ca739798ee2]::ty::context::tls::with_context_opt::<rustc_middle[526e0ca739798ee2]::ty::context::tls::with_opt<rustc_middle[526e0ca739798ee2]::util::bug::opt_span_bug_fmt<rustc_span[6b0f4bf036ac788e]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fc1a759f406 - rustc_middle[526e0ca739798ee2]::util::bug::opt_span_bug_fmt::<rustc_span[6b0f4bf036ac788e]::span_encoding::Span>
  23:     0x7fc1a52d57c3 - rustc_middle[526e0ca739798ee2]::util::bug::bug_fmt
  24:     0x7fc1a5f6f38e - <&mut <rustc_borrowck[2e52752a89f891f4]::type_check::free_region_relations::UniversalRegionRelationsBuilder>::create::{closure#0} as core[3a3cbeb512a16fa3]::ops::function::FnOnce<(rustc_middle[526e0ca739798ee2]::ty::Ty,)>>::call_once
  25:     0x7fc1a5f6e402 - <alloc[9ea3c9e5c77b7621]::vec::Vec<&rustc_middle[526e0ca739798ee2]::infer::canonical::QueryRegionConstraints> as alloc[9ea3c9e5c77b7621]::vec::spec_from_iter::SpecFromIter<&rustc_middle[526e0ca739798ee2]::infer::canonical::QueryRegionConstraints, core[3a3cbeb512a16fa3]::iter::adapters::flatten::FlatMap<core[3a3cbeb512a16fa3]::iter::adapters::chain::Chain<core[3a3cbeb512a16fa3]::iter::adapters::cloned::Cloned<core[3a3cbeb512a16fa3]::slice::iter::Iter<rustc_middle[526e0ca739798ee2]::ty::Ty>>, core[3a3cbeb512a16fa3]::option::IntoIter<rustc_middle[526e0ca739798ee2]::ty::Ty>>, core[3a3cbeb512a16fa3]::iter::adapters::chain::Chain<core[3a3cbeb512a16fa3]::iter::adapters::chain::Chain<core[3a3cbeb512a16fa3]::option::IntoIter<&rustc_middle[526e0ca739798ee2]::infer::canonical::QueryRegionConstraints>, core[3a3cbeb512a16fa3]::option::IntoIter<&rustc_middle[526e0ca739798ee2]::infer::canonical::QueryRegionConstraints>>, core[3a3cbeb512a16fa3]::option::IntoIter<&rustc_middle[526e0ca739798ee2]::infer::canonical::QueryRegionConstraints>>, <rustc_borrowck[2e52752a89f891f4]::type_check::free_region_relations::UniversalRegionRelationsBuilder>::create::{closure#0}>>>::from_iter
  26:     0x7fc1a5f69709 - rustc_borrowck[2e52752a89f891f4]::type_check::free_region_relations::create
  27:     0x7fc1a5f5480d - rustc_borrowck[2e52752a89f891f4]::nll::compute_regions
  28:     0x7fc1a5f23e5e - rustc_borrowck[2e52752a89f891f4]::do_mir_borrowck
  29:     0x7fc1a5f06f85 - rustc_borrowck[2e52752a89f891f4]::mir_borrowck
  30:     0x7fc1a582238d - rustc_query_system[decabb1eb79370b7]::query::plumbing::try_execute_query::<rustc_query_impl[ff3c18b748312d2f]::queries::mir_borrowck, rustc_query_impl[ff3c18b748312d2f]::plumbing::QueryCtxt>
  31:     0x7fc1a69f6c8d - <rustc_query_impl[ff3c18b748312d2f]::Queries as rustc_middle[526e0ca739798ee2]::ty::query::QueryEngine>::mir_borrowck
  32:     0x7fc1a6001124 - <rustc_borrowck[2e52752a89f891f4]::type_check::TypeChecker>::prove_closure_bounds
  33:     0x7fc1a5fdd78b - <rustc_borrowck[2e52752a89f891f4]::type_check::TypeChecker>::typeck_mir
  34:     0x7fc1a5f54b8d - rustc_borrowck[2e52752a89f891f4]::nll::compute_regions
  35:     0x7fc1a5f23e5e - rustc_borrowck[2e52752a89f891f4]::do_mir_borrowck
  36:     0x7fc1a5f06f85 - rustc_borrowck[2e52752a89f891f4]::mir_borrowck
  37:     0x7fc1a582238d - rustc_query_system[decabb1eb79370b7]::query::plumbing::try_execute_query::<rustc_query_impl[ff3c18b748312d2f]::queries::mir_borrowck, rustc_query_impl[ff3c18b748312d2f]::plumbing::QueryCtxt>
  38:     0x7fc1a568f5cd - rustc_data_structures[439cdbfa31de989]::sync::par_for_each_in::<&[rustc_span[6b0f4bf036ac788e]::def_id::LocalDefId], <rustc_middle[526e0ca739798ee2]::hir::map::Map>::par_body_owners<rustc_interface[d4b4ad1a0cb81775]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  39:     0x7fc1a568f1d3 - <rustc_session[8c42e6c16859134b]::session::Session>::time::<(), rustc_interface[d4b4ad1a0cb81775]::passes::analysis::{closure#2}>
  40:     0x7fc1a568d2b7 - rustc_interface[d4b4ad1a0cb81775]::passes::analysis
  41:     0x7fc1a67c588e - rustc_query_system[decabb1eb79370b7]::query::plumbing::try_execute_query::<rustc_query_impl[ff3c18b748312d2f]::queries::analysis, rustc_query_impl[ff3c18b748312d2f]::plumbing::QueryCtxt>
  42:     0x7fc1a69ef64a - <rustc_query_impl[ff3c18b748312d2f]::Queries as rustc_middle[526e0ca739798ee2]::ty::query::QueryEngine>::analysis
  43:     0x7fc1a66f8a60 - <rustc_interface[d4b4ad1a0cb81775]::passes::QueryContext>::enter::<rustc_driver[d1d90693eba3e117]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>
  44:     0x7fc1a624a296 - rustc_span[6b0f4bf036ac788e]::with_source_map::<core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>, rustc_interface[d4b4ad1a0cb81775]::interface::run_compiler<core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>, rustc_driver[d1d90693eba3e117]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  45:     0x7fc1a6242654 - <scoped_tls[6607de7944b4e913]::ScopedKey<rustc_span[6b0f4bf036ac788e]::SessionGlobals>>::set::<rustc_interface[d4b4ad1a0cb81775]::interface::run_compiler<core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>, rustc_driver[d1d90693eba3e117]::run_compiler::{closure#1}>::{closure#0}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>
  46:     0x7fc1a6241d52 - std[ef0604d174e11cd5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d4b4ad1a0cb81775]::util::run_in_thread_pool_with_globals<rustc_interface[d4b4ad1a0cb81775]::interface::run_compiler<core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>, rustc_driver[d1d90693eba3e117]::run_compiler::{closure#1}>::{closure#0}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>
  47:     0x7fc1a6241afa - <<std[ef0604d174e11cd5]::thread::Builder>::spawn_unchecked_<rustc_interface[d4b4ad1a0cb81775]::util::run_in_thread_pool_with_globals<rustc_interface[d4b4ad1a0cb81775]::interface::run_compiler<core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>, rustc_driver[d1d90693eba3e117]::run_compiler::{closure#1}>::{closure#0}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a3cbeb512a16fa3]::result::Result<(), rustc_errors[6cf9ff966b0b62fb]::ErrorGuaranteed>>::{closure#1} as core[3a3cbeb512a16fa3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7fc1a3cdc803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9646bd6a135081c9
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/alloc/src/boxed.rs:1988:9
  49:     0x7fc1a3cdc803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h180d98f11b902552
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/alloc/src/boxed.rs:1988:9
  50:     0x7fc1a3cdc803 - std::sys::unix::thread::Thread::new::thread_start::h83489d4028ebb6e1
                               at /rustc/ef982929c0b653436a6ea6892a2a839fba7c8b57/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7fc1a3b9f609 - start_thread
  52:     0x7fc1a3ac2133 - clone
  53:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (ef982929c 2023-01-27) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `test::{closure#0}`
#1 [mir_borrowck] borrow-checking `test`
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `playground`
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6a8a0bededa440fac1ba9fae51fe006b)

### LINKED ISSUE #112250: ICE: compiler/rustc_borrowck/src/universal_regions.rs:882:36: cannot convert `RePlaceholder(Placeholder { bound: BoundRegion { kind: BrNamed})` to a region vid
### Code

https://github.com/cryfs/cryfs/commit/ae730ecafb8af2651540e09e4dba1d76160222e4

In that commit, go to folder `src/blockstore/rust/cryfs-cli` and run ```cargo check```

### Meta

(tested in nightly, stable 1.69 and stable 1.70)

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2

```

### Error output

```
error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:882:36: cannot convert `RePlaceholder(Placeholder { universe: U1, bound: BoundRegion { var: 0, kind: BrNamed(DefId(168:840 ~ cryfs_cryfs[97fd]::filesystem::device::CryDevice::'a), 'a) } })` to a region vid
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:882:36: cannot convert `RePlaceholder(Placeholder { universe: U1, bound: BoundRegion { var: 0, kind: BrNamed(DefId(168:840 ~ cryfs_cryfs[97fd]::filesystem::device::CryDevice::'a), 'a) } })` to a region vid

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/90c541806f23a127002de5b4038be731ba1458ca/compiler/rustc_errors/src/lib.rs:1643:9
stack backtrace:
   0:     0x7f4d76578cca - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4d76578cca - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4d76578cca - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4d76578cca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4d765dd0cf - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f4d7656b805 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x7f4d76578a95 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4d76578a95 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4d7657b73e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x7f4d7657b4e5 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x7f4d79837995 - <rustc_driver_impl[fe6df70259db788d]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[da82827a87f140f9]::ops::function::FnOnce<(&core[da82827a87f140f9]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4d7657bf34 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb9b860f5a1175bda
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  12:     0x7f4d7657bf34 - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
  13:     0x7f4d79d51c31 - std[b70fedfd8b77e9]::panicking::begin_panic::<rustc_errors[c06e44e71f249a31]::ExplicitBug>::{closure#0}
  14:     0x7f4d79d515e6 - std[b70fedfd8b77e9]::sys_common::backtrace::__rust_end_short_backtrace::<std[b70fedfd8b77e9]::panicking::begin_panic<rustc_errors[c06e44e71f249a31]::ExplicitBug>::{closure#0}, !>
  15:     0x7f4d79d86b86 - std[b70fedfd8b77e9]::panicking::begin_panic::<rustc_errors[c06e44e71f249a31]::ExplicitBug>
  16:     0x7f4d79de4a76 - <rustc_errors[c06e44e71f249a31]::HandlerInner>::bug::<&alloc[c91da12302dbbf86]::string::String>
  17:     0x7f4d79de4740 - <rustc_errors[c06e44e71f249a31]::Handler>::bug::<&alloc[c91da12302dbbf86]::string::String>
  18:     0x7f4d79d9c6d4 - rustc_middle[a487dff4633a86d0]::util::bug::opt_span_bug_fmt::<rustc_span[2f805118d893a80f]::span_encoding::Span>::{closure#0}
  19:     0x7f4d79d9b18a - rustc_middle[a487dff4633a86d0]::ty::context::tls::with_opt::<rustc_middle[a487dff4633a86d0]::util::bug::opt_span_bug_fmt<rustc_span[2f805118d893a80f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f4d79d9b156 - rustc_middle[a487dff4633a86d0]::ty::context::tls::with_context_opt::<rustc_middle[a487dff4633a86d0]::ty::context::tls::with_opt<rustc_middle[a487dff4633a86d0]::util::bug::opt_span_bug_fmt<rustc_span[2f805118d893a80f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f4d79d9c626 - rustc_middle[a487dff4633a86d0]::util::bug::opt_span_bug_fmt::<rustc_span[2f805118d893a80f]::span_encoding::Span>
  22:     0x7f4d77b9c8b3 - rustc_middle[a487dff4633a86d0]::util::bug::bug_fmt
  23:     0x7f4d78724284 - rustc_borrowck[c07eeb7c7aba6c08]::type_check::free_region_relations::create
  24:     0x7f4d786fe78c - rustc_borrowck[c07eeb7c7aba6c08]::nll::compute_regions
  25:     0x7f4d786c9b46 - rustc_borrowck[c07eeb7c7aba6c08]::do_mir_borrowck
  26:     0x7f4d786c68a7 - rustc_borrowck[c07eeb7c7aba6c08]::mir_borrowck
  27:     0x7f4d786c5f6e - <rustc_borrowck[c07eeb7c7aba6c08]::provide::{closure#0} as core[da82827a87f140f9]::ops::function::FnOnce<(rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt, rustc_span[2f805118d893a80f]::def_id::LocalDefId)>>::call_once
  28:     0x7f4d782c031e - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  29:     0x7f4d782bf27b - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  30:     0x7f4d782bea53 - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::mir_borrowck
  31:     0x7f4d787ba559 - <rustc_borrowck[c07eeb7c7aba6c08]::type_check::TypeChecker>::prove_closure_bounds
  32:     0x7f4d78797c82 - <rustc_borrowck[c07eeb7c7aba6c08]::type_check::TypeChecker>::typeck_mir
  33:     0x7f4d786fec50 - rustc_borrowck[c07eeb7c7aba6c08]::nll::compute_regions
  34:     0x7f4d786c9b46 - rustc_borrowck[c07eeb7c7aba6c08]::do_mir_borrowck
  35:     0x7f4d786c68a7 - rustc_borrowck[c07eeb7c7aba6c08]::mir_borrowck
  36:     0x7f4d786c5f6e - <rustc_borrowck[c07eeb7c7aba6c08]::provide::{closure#0} as core[da82827a87f140f9]::ops::function::FnOnce<(rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt, rustc_span[2f805118d893a80f]::def_id::LocalDefId)>>::call_once
  37:     0x7f4d782c031e - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  38:     0x7f4d782bf27b - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  39:     0x7f4d782bea53 - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::mir_borrowck
  40:     0x7f4d787ba559 - <rustc_borrowck[c07eeb7c7aba6c08]::type_check::TypeChecker>::prove_closure_bounds
  41:     0x7f4d78797c82 - <rustc_borrowck[c07eeb7c7aba6c08]::type_check::TypeChecker>::typeck_mir
  42:     0x7f4d786fec50 - rustc_borrowck[c07eeb7c7aba6c08]::nll::compute_regions
  43:     0x7f4d786c9b46 - rustc_borrowck[c07eeb7c7aba6c08]::do_mir_borrowck
  44:     0x7f4d786c68a7 - rustc_borrowck[c07eeb7c7aba6c08]::mir_borrowck
  45:     0x7f4d786c5f6e - <rustc_borrowck[c07eeb7c7aba6c08]::provide::{closure#0} as core[da82827a87f140f9]::ops::function::FnOnce<(rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt, rustc_span[2f805118d893a80f]::def_id::LocalDefId)>>::call_once
  46:     0x7f4d782c031e - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  47:     0x7f4d782bf27b - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::mir_borrowck, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  48:     0x7f4d782bea53 - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::mir_borrowck
  49:     0x7f4d78ad1569 - rustc_hir_analysis[44791ba5f8e3b26d]::collect::type_of::type_of
  50:     0x7f4d7800402d - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::type_of, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  51:     0x7f4d78001bab - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::type_of, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  52:     0x7f4d780009aa - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::type_of
  53:     0x7f4d78a83648 - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  54:     0x7f4d781a3131 - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander as rustc_type_ir[5a97038ec29b7d58]::fold::TypeFolder<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::fold_ty
  55:     0x7f4d79d957c9 - rustc_middle[a487dff4633a86d0]::ty::util::fold_list::<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander, rustc_middle[a487dff4633a86d0]::ty::Ty, <&rustc_middle[a487dff4633a86d0]::ty::list::List<rustc_middle[a487dff4633a86d0]::ty::Ty> as rustc_type_ir[5a97038ec29b7d58]::fold::TypeFoldable<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::try_fold_with<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>::{closure#0}>
  56:     0x7f4d79d88292 - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander as rustc_type_ir[5a97038ec29b7d58]::fold::FallibleTypeFolder<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::try_fold_binder::<&rustc_middle[a487dff4633a86d0]::ty::list::List<rustc_middle[a487dff4633a86d0]::ty::Ty>>
  57:     0x7f4d781a3c28 - <rustc_middle[a487dff4633a86d0]::ty::Ty as rustc_type_ir[5a97038ec29b7d58]::fold::TypeSuperFoldable<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>
  58:     0x7f4d781a311a - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander as rustc_type_ir[5a97038ec29b7d58]::fold::TypeFolder<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::fold_ty
  59:     0x7f4d781a33fb - rustc_middle[a487dff4633a86d0]::ty::util::fold_list::<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander, rustc_middle[a487dff4633a86d0]::ty::subst::GenericArg, <&rustc_middle[a487dff4633a86d0]::ty::list::List<rustc_middle[a487dff4633a86d0]::ty::subst::GenericArg> as rustc_type_ir[5a97038ec29b7d58]::fold::TypeFoldable<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::try_fold_with<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>::{closure#0}>
  60:     0x7f4d781a3bfc - <rustc_middle[a487dff4633a86d0]::ty::Ty as rustc_type_ir[5a97038ec29b7d58]::fold::TypeSuperFoldable<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>
  61:     0x7f4d781a311a - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander as rustc_type_ir[5a97038ec29b7d58]::fold::TypeFolder<rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>>::fold_ty
  62:     0x7f4d78a834f3 - <rustc_middle[a487dff4633a86d0]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  63:     0x7f4d78a80fc7 - <rustc_middle[a487dff4633a86d0]::ty::context::TyCtxt>::try_expand_impl_trait_type
  64:     0x7f4d78a62727 - rustc_hir_analysis[44791ba5f8e3b26d]::check::check::check_mod_item_types
  65:     0x7f4d78e5e6eb - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::check_mod_item_types, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  66:     0x7f4d78e5df4d - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::check_mod_item_types, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  67:     0x7f4d78e5d8e9 - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::check_mod_item_types
  68:     0x7f4d78d11a4f - <rustc_session[99ba0ed9c533f203]::session::Session>::time::<(), rustc_hir_analysis[44791ba5f8e3b26d]::check_crate::{closure#6}>
  69:     0x7f4d78d0ec57 - rustc_hir_analysis[44791ba5f8e3b26d]::check_crate
  70:     0x7f4d78d090bd - rustc_interface[7aa24cde61830128]::passes::analysis
  71:     0x7f4d78f85633 - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<rustc_query_system[5e34f8384464b8a5]::query::plumbing::execute_job_incr<rustc_query_impl[3e42b93bfeb445bd]::queries::analysis, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[a487dff4633a86d0]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[5e34f8384464b8a5]::dep_graph::graph::DepNodeIndex)>
  72:     0x7f4d78f8510b - rustc_query_system[5e34f8384464b8a5]::query::plumbing::try_execute_query::<rustc_query_impl[3e42b93bfeb445bd]::queries::analysis, rustc_query_impl[3e42b93bfeb445bd]::plumbing::QueryCtxt>
  73:     0x7f4d78f84cd0 - <rustc_query_impl[3e42b93bfeb445bd]::Queries as rustc_middle[a487dff4633a86d0]::ty::query::QueryEngine>::analysis
  74:     0x7f4d78ebb726 - <std[b70fedfd8b77e9]::thread::local::LocalKey<core[da82827a87f140f9]::cell::Cell<*const ()>>>::with::<rustc_middle[a487dff4633a86d0]::ty::context::tls::enter_context<<rustc_middle[a487dff4633a86d0]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[fe6df70259db788d]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>
  75:     0x7f4d78b2202e - <rustc_interface[7aa24cde61830128]::interface::Compiler>::enter::<rustc_driver_impl[fe6df70259db788d]::run_compiler::{closure#1}::{closure#2}, core[da82827a87f140f9]::result::Result<core[da82827a87f140f9]::option::Option<rustc_interface[7aa24cde61830128]::queries::Linker>, rustc_span[2f805118d893a80f]::ErrorGuaranteed>>
  76:     0x7f4d78b1d281 - rustc_span[2f805118d893a80f]::set_source_map::<core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>, rustc_interface[7aa24cde61830128]::interface::run_compiler<core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>, rustc_driver_impl[fe6df70259db788d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  77:     0x7f4d78b1c82f - std[b70fedfd8b77e9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7aa24cde61830128]::util::run_in_thread_pool_with_globals<rustc_interface[7aa24cde61830128]::interface::run_compiler<core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>, rustc_driver_impl[fe6df70259db788d]::run_compiler::{closure#1}>::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>
  78:     0x7f4d79100661 - <<std[b70fedfd8b77e9]::thread::Builder>::spawn_unchecked_<rustc_interface[7aa24cde61830128]::util::run_in_thread_pool_with_globals<rustc_interface[7aa24cde61830128]::interface::run_compiler<core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>, rustc_driver_impl[fe6df70259db788d]::run_compiler::{closure#1}>::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[da82827a87f140f9]::result::Result<(), rustc_span[2f805118d893a80f]::ErrorGuaranteed>>::{closure#1} as core[da82827a87f140f9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  79:     0x7f4d765863b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1f2224656a778fb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  80:     0x7f4d765863b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haa29ed9703f354b7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  81:     0x7f4d765863b5 - std::sys::unix::thread::Thread::new::thread_start::h33b6dae3e3692197
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  82:     0x7f4d762bbb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  83:     0x7f4d7634da00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  84:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `cli::<impl at cryfs-cli/src/cli.rs:38:1: 38:9>::run_filesystem::{closure#0}::{closure#1}`
#1 [mir_borrowck] borrow-checking `cli::<impl at cryfs-cli/src/cli.rs:38:1: 38:9>::run_filesystem::{closure#0}`
#2 [mir_borrowck] borrow-checking `cli::<impl at cryfs-cli/src/cli.rs:38:1: 38:9>::run_filesystem`
#3 [type_of] computing type of `cli::<impl at cryfs-cli/src/cli.rs:38:1: 38:9>::run_filesystem::{opaque#0}`
#4 [check_mod_item_types] checking item types in module `cli`
#5 [analysis] running analysis passes on this crate
end of query stack
warning: `cryfs-cli` (lib) generated 4 warnings (run `cargo fix --lib -p cryfs-cli` to apply 4 suggestions)
error: could not compile `cryfs-cli` (lib); 4 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by aliemjay**
given the following code:
```rust
trait Trait {
    type Ty<'a> where Self: 'a;
}

impl<T> Trait for T {
    type Ty<'a> = () where Self: 'a;
}

struct Foo<T: Trait>(T)
where
    for<'x> T::Ty<'x>: Sized;
```

when computing the implied bounds from `Foo<X>` we incorrectly get the bound `X: !x` from the normalization of ` for<'x> <X as Trait>::Ty::<'x>: Sized`. This is a a known bug! we shouldn't use the constraints that arise from normalization as implied bounds. See #109628.

Ignore these bounds for now. This should prevent later ICEs.

Fixes #112250
Fixes #107409

### CODE REVIEW

**Comment by aliemjay** [comment]
cc @lcnr (because it involves #109628)
r? types

File: compiler/rustc_trait_selection/src/traits/outlives_bounds.rs [hunk 1]
```diff
@@ -88,6 +88,10 @@ impl<'a, 'tcx: 'a> InferCtxtExt<'a, 'tcx> for InferCtxt<'tcx> {
         };
         assert_eq!(&obligations, &[]);
 
+        // Because of #109628, we may have unexpected placeholders. Ignore them!
+        // FIXME(#109628): panic in this case once the issue is fixed.
+        bounds.drain_filter(|bound| bound.has_placeholders());
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/traits/outlives_bounds.rs:93]:
```suggestion
        bounds.retain(|bound| !bound.has_placeholders());
```

File: compiler/rustc_borrowck/src/type_check/free_region_relations.rs [hunk 2]
```diff
@@ -320,6 +320,9 @@ impl<'tcx> UniversalRegionRelationsBuilder<'_, 'tcx> {
             .fully_perform(self.infcx, DUMMY_SP)
             .unwrap_or_else(|_| bug!("failed to compute implied bounds {:?}", ty));
         debug!(?bounds, ?constraints);
+        // Because of #109628, we may have unexpected placeholders. Ignore them!
+        // FIXME(#109628): panic in this case once the issue is fixed.
+        let bounds = bounds.into_iter().filter(|bound| !bound.has_placeholders());
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/free_region_relations.rs:325]: can you move that into the `TypeOp`?

**Review by lcnr — COMMENTED** [review]
:heart:

r=me after nits

**Comment by Dylan-DPC** [comment]
@aliemjay  any updates on this? thanks

**Comment by chrysn** [comment]
I think I have a case similar to  #112250 in code at https://gitlab.com/chrysn/coap-message-demos branch embedded-nal-coap-clientserver when run as `cargo +nightly run --example std_embedded_nal_coap --features example-std_embedded_nal_coap`. Before I start minimizing this for hours I'd like to try this PR, but the code widely depends on newly stabilized features. Would you consider updating?

File: compiler/rustc_borrowck/src/type_check/free_region_relations.rs (hunk 2 above)
Comment (aliemjay) [reply compiler/rustc_borrowck/src/type_check/free_region_relations.rs:326]: Moving this into the TypeOp has no benefit as we would have to duplicate the logic in `QueryTypeOp::{perform_query,perform_locally_in_new_solver}` as well. It is also more difficult to handle canonicalized query responses - there is no easy way to detect placeholders for example.

Doing it in the query itself is difficult as we need to do  `OpportunisticRegionResolution` before checking for placeholders. Using `TypeVisitableExt::has_placeholders` to check for erroneus placeholders there does not play well with #109388 as it would yield many false positives.

**Comment by lqd** [comment]
(`deep-vector` is currently being noisy)
