### PR TITLE
Fix supertrait associated type unsoundness

### LINKED ISSUE #126079: Associated types in object-safe method signatures don't always come from supertraits
One of the requirements for a trait to be object-safe is that the associated types that show up in signatures of methods come from the supertraits of the object. We don't currently implement this correctly -- we currently ignore the substitutions of the associated type 😿.

This is unsound:

```rust
use core::marker::PhantomData;

fn transmute<T, U>(t: T) -> U {
    (&PhantomData::<T> as &dyn Foo<T, U>).transmute(t)
}

struct ActuallySuper;
struct NotActuallySuper;
trait Super<Q> {
    type Assoc;
}

trait Dyn {
    type Out;
}
impl<T, U> Dyn for dyn Foo<T, U> + '_ {
    type Out = U;
}
impl<S: Dyn<Out = U> + ?Sized, U> Super<NotActuallySuper> for S {
    type Assoc = U;
}

trait Foo<T, U>: Super<ActuallySuper, Assoc = T> where <Self as Mirror>::Assoc: Super<NotActuallySuper> {
    fn transmute(&self, t: T) -> <Self as Super<NotActuallySuper>>::Assoc;
}

trait Mirror {
    type Assoc: ?Sized;
}
impl<T: ?Sized> Mirror for T {
    type Assoc = T;
}

impl<T, U> Foo<T, U> for PhantomData<T> {
    fn transmute(&self, t: T) -> T {
        t
    }
}
impl<T> Super<ActuallySuper> for PhantomData<T> {
    type Assoc = T;
}
impl<T> Super<NotActuallySuper> for PhantomData<T> {
    type Assoc = T;
}

fn main() {
    let x = String::from("hello, world");
    let s = transmute::<&str, &'static str>(x.as_str());
    drop(x);
    println!("> {s}");
}
```

Specifically, `fn transmute(&self, t: T) -> <Self as Super<NotActuallySuper>>::Assoc;` should only be sound if the return type was `<Self as Super<ActuallySuper>>::Assoc`, *or* if we added `Super<NotActuallySuper>` as a supertrait.

We should probably deeply normalize these supertraits and actually consider the associated types' substs match modulo regions.

### PR DESCRIPTION
**Pull request by compiler-errors**
### What?

Object safety allows us to name `Self::Assoc` associated types in certain positions if they come from our trait or one of our supertraits. When this check was implemented, I think it failed to consider that supertraits can have different args, and it was only checking def-id equality.

This is problematic, since we can sneak different implementations in by implementing `Supertrait<NotActuallyTheSupertraitSubsts>` for a `dyn` type. This can be used to implement an unsound transmute function. See the committed test.

### How do we fix it?

We consider the whole trait ref when checking for supertraits. Right now, this is implemented using equality *without* normalization. We erase regions since those don't affect trait selection.

This is a limitation that could theoretically affect code that should be accepted, but doesn't matter in practice -- there are 0 crater regression. We could make this check stronger, but I would be worried about cycle issues. I assume that most people are writing `Self::Assoc` so they don't really care about the trait ref being normalized.

---

### What is up w the stacked commit

This is built on top of https://github.com/rust-lang/rust/pull/122804 though that's really not related, it's just easier to make this modification with the changes to the object safety code that I did in that PR. The only thing is that PR may make this unsoundness slightly easier to abuse, since there are more positions that allow self-associated-types -- I am happy to stall that change until this PR merges.

---

Fixes #126079 

r? lcnr

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/object_safety.rs [hunk 1]
```diff
@@ -711,120 +731,180 @@ fn receiver_is_dispatchable<'tcx>(
...
+                                    self.tcx,
+                                    ty::Binder::dummy(ty::TraitRef::identity(
+                                        self.tcx,
+                                        self.trait_def_id,
+                                    )),
+                                )
+                                .map(|trait_ref| {
+                                    self.tcx.erase_regions(
+                                        self.tcx.instantiate_bound_regions_with_erased(trait_ref),
+                                    )
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/traits/object_safety.rs:835]: This sucks lol. but I don't really care about regions here

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-126090/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
This is ready. See description. Needs fcp.

**Comment by lcnr** [comment]
This fixes an unsoundness where a where-bound `<Self as SuperTrait<DifferentArgFromSuperTrait>>::Assoc: Bound` did not cause a trait to not be object safe. See the PR description and the added test.

@rfcbot fcp merge

r=me on the changes

**Comment by nikomatsakis** [comment]
@rfcbot reviewed
