### PR TITLE
diagnostics: avoid mismatch between variance index and hir generic

### LINKED ISSUE #83556: unused param error mentions incorrect param if there's a misplaced lt param
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f6aaeef90ca703dffc311e3829186005
```rust
struct Foo<T, 'a>(&'a ());
```
causes the following error:
```
error: lifetime parameters must be declared prior to type parameters
 --> src/lib.rs:1:15
  |
1 | struct Foo<T, 'a>(&'a ());
  |           ----^^- help: reorder the parameters: lifetimes, then types, then consts: `<'a, T>`

error[E0392]: parameter `'a` is never used
 --> src/lib.rs:1:15
  |
1 | struct Foo<T, 'a>(&'a ());
  |               ^^ unused parameter
  |
  = help: consider removing `'a`, referring to it in a field, or using a marker such as `PhantomData`

```
it should be "parameter `T` is never used"

### PR DESCRIPTION
**Pull request by notriddle**
This happens because variances are constructed from ty generics, and ty generics are always constructed with lifetimes first.

https://github.com/rust-lang/rust/blob/b3aa8e7168a3d940122db3561289ffbf3f587262/compiler/rustc_hir_analysis/src/collect/generics_of.rs#L248-L269

Fixes #83556

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 1]
```diff
@@ -1755,20 +1755,41 @@ fn check_variances_for_type_defn<'tcx>(
...
+            // if they aren't in the same order, then the user has written invalid code, and already
+            // got an error about it (or I'm wrong about this)
+            tcx.sess
+                .delay_span_bug(hir_param.span, "hir generics and ty generics in different order");
+            for hp in hir_generics.params {
+                if hp.name.ident().name == ty_param.name {
+                    hir_param = hp;
+                    break;
+                }
+            }
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1785]: Should we just silence the error? The program is invalid anyway, and we check that by delaying a bug.
```suggestion
            continue;
```

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs [hunk 2]
```diff
@@ -1755,20 +1755,41 @@ fn check_variances_for_type_defn<'tcx>(
...
 
         if constrained_parameters.contains(&parameter) {
             continue;
         }
 
-        let param = &hir_generics.params[index];
+        let ty_param = &ty_generics.params[index];
+        let mut hir_param = &hir_generics.params[index];
+
+        if ty_param.name != hir_param.name.ident().name {
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1770]:
```suggestion
        if ty_param.def_id != hir_param.def_id {
```
Working with def_ids is always more robust.

File: compiler/rustc_hir_analysis/src/check/wfcheck.rs (hunk 1 above)
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/check/wfcheck.rs:1785]:
```suggestion
            if let Some(node) = tcx.find_node_by_def_id(ty_param.def_id) {
                hir_param = node.expect_generic_param();
            }
```

**Comment by cjgillot** [comment]
Thanks.
@bors r+
