### PR TITLE
Fix incorrect suggestion for trait bounds involving binary operators

### LINKED ISSUE #93927: `rustc` suggests adding a `PartialEq` bound where another trait is actually required
Given the following code (EDIT: see the [comment](https://github.com/rust-lang/rust/issues/93927#issuecomment-1036964865) below for a more concise snippet):

```rust
struct MyType<T: PartialEq>(T);

impl<T> PartialEq for MyType<T>
where
    T: PartialEq + Eq,
{
    fn eq(&self, other: &Self) -> bool {
        true
    }
}

struct MyStruct<T: PartialEq> {
    a: MyType<T>,
    b: MyType<T>,
}

impl<T> MyStruct<T>
where
    T: PartialEq,
{
    fn cond(&self) -> bool {
        self.b != self.a
    }
}

fn main() {
    let tst = MyStruct {
        a: MyType(1),
        b: MyType(2),
    };
    tst.cond();
}

```

https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=a69190abd7a2b258c588d8e994e69871

The current output is:

```
error[[E0369]](https://doc.rust-lang.org/stable/error-index.html#E0369): binary operation `!=` cannot be applied to type `MyType<T>`
  [--> src/main.rs:22:16
](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=1dacb528973e6547b8284f3039fadbb1#)   |
22 |         self.b != self.a
   |         ------ ^^ ------ MyType<T>
   |         |
   |         MyType<T>
   |
help: consider further restricting this bound
   |
19 |     T: PartialEq + std::cmp::PartialEq,
   |                  +++++++++++++++++++++

For more information about this error, try `rustc --explain E0369`.
```

Ideally the output should look like:

```
error[[E0369]](https://doc.rust-lang.org/stable/error-index.html#E0369): binary operation `!=` cannot be applied to type `MyType<T>`
  [--> src/main.rs:22:16
](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=1dacb528973e6547b8284f3039fadbb1#)   |
22 |         self.b != self.a
   |         ------ ^^ ------ MyType<T>
   |         |
   |         MyType<T>
   |
help: consider further restricting this bound
   |
19 |     T: PartialEq + std::cmp::Eq,
   |                  ++++++++++++++

For more information about this error, try `rustc --explain E0369`.
```

`!=` can't be used here because `MyType<T>` only implements `PartialEq` where `T` implements `Eq`, but instead of suggesting we add an `Eq` bound, `rustc` suggests adding an additional `PartialEq` bound, despite `T` already being `PartialEq`. 

This bug is present on both stable and nightly.

### PR DESCRIPTION
**Pull request by willcrichton**
This PR fixes #93927, #92347, #93744 by replacing the bespoke trait-suggestion logic in `op.rs` with a more common code path.

The downside is that this fix causes some suggestions to not include an `Output=` type, reducing their usefulness.

Note that this causes one case in the `missing-bounds.rs` test to fail rustfix. So I would need to move that code into a separate non-fix test if this PR is otherwise acceptable.

### CODE REVIEW

**Comment by oli-obk** [comment]
r? @oli-obk 

cc @rust-lang/wg-diagnostics

File: compiler/rustc_typeck/src/check/op.rs [hunk 1]
```diff
@@ -435,39 +434,35 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        let errors = self
+                            .lookup_op_method(lhs_ty, &[rhs_ty], Op::Binary(op, is_assign))
+                            .unwrap_err();
+                        let predicates = errors
+                            .into_iter()
+                            .filter_map(|error| error.obligation.predicate.to_opt_poly_trait_pred())
+                            .collect::<Vec<_>>();
+                        if !predicates.is_empty() {
+                            for pred in predicates {
+                                self.infcx.suggest_restricting_param_bound(
```
Comment (oli-obk) [inline compiler/rustc_typeck/src/check/op.rs:453]: I think we should teach this function about associated type bounds. You could filter all projection predicates for one that is for the current trait and type and if there is such a projection predicate, extend the suggestion with the assoc bound

File: src/test/ui/issues/issue-35668.stderr [hunk 2]
```diff
@@ -6,10 +6,10 @@ LL |     a.iter().map(|a| a*a)
    |                      |
    |                      &T
    |
-help: consider restricting type parameter `T`
+help: consider introducing a `where` bound, but there might be an alternative better way to express this requirement
```
Comment (oli-obk) [inline src/test/ui/issues/issue-35668.stderr:9]: Preexisting, but this message is too vague. We should probably check all occurrences in our ui tests and see if we can be more targetted (or at least change the wording)

File: compiler/rustc_typeck/src/check/op.rs (hunk 1 above)
Comment (willcrichton) [reply compiler/rustc_typeck/src/check/op.rs:453]: One issue I'm encountering. I don't think there's a sound way to determine what the appropriate `Output` type should be. The function `check_overloaded_binop` attempts to do this, but it can only compute `return_ty` if the initial `lookup_op_method` returns a `MethodCallee`, which it does not in the case being addressed. 

Is there some possibility here that I'm missing?

Comment (oli-obk) [reply compiler/rustc_typeck/src/check/op.rs:453]: I'm hoping that the correct associated type bound is in the `errors` list. Try dumping the entire list and checking if it contains `PredicateKind::Projection` that match the `pred` in the loop here.

Comment (willcrichton) [reply compiler/rustc_typeck/src/check/op.rs:453]: Yes I've checked, and a `Projection` predicate does not already exist. This is because the relevant predicates are generated by the function [`obligation_for_method`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/method/mod.rs#L298). That function would have to be extended to produce a `Projection` predicate, except it can only do so if it knows about the expected associated types of a method, which it cannot in this case.

Comment (estebank) [reply compiler/rustc_typeck/src/check/op.rs:453]: I think I made some related changes in https://github.com/rust-lang/rust/pull/90006/files, which won't be landing until I manage to get rid of the perf regression.

**Comment by estebank** [comment]
> The downside is that this fix causes some suggestions to not include an Output= type, reducing their usefulness.
> 
> Note that this causes one case in the missing-bounds.rs test to fail rustfix. So I would need to move that code into a separate non-fix test if this PR is otherwise acceptable.

Do we suggest the right `Output` in the new error? If we still lead the user in the right direction, only with an extra iteration, then that's fine.

File: src/test/ui/issues/issue-35668.stderr [hunk 3]
```diff
@@ -6,10 +6,10 @@ LL |     a.iter().map(|a| a*a)
...
    |
-LL | fn func<'a, T: std::ops::Mul<Output = &T>>(a: &'a [T]) -> impl Iterator<Item=&'a T> {
-   |              ++++++++++++++++++++++++++++
+LL | fn func<'a, T>(a: &'a [T]) -> impl Iterator<Item=&'a T> where &T: Mul<&T> {
+   |                                                         +++++++++++++++++
```
Comment (estebank) [inline src/test/ui/issues/issue-35668.stderr:12]: Is this suggestion change correct?

**Comment by willcrichton** [comment]
> Do we suggest the right `Output` in the new error? If we still lead the user in the right direction, only with an extra iteration, then that's fine.

No, because I don't think there is a sound way to guess what `Output` should be as mentioned here: https://github.com/rust-lang/rust/pull/94034#discussion_r808277778

File: src/test/ui/issues/issue-35668.stderr (hunk 3 above)
Comment (willcrichton) [reply src/test/ui/issues/issue-35668.stderr:12]: Yes, albeit underconstrained on `Output`. It actually fixes the previously incorrect suggestion of `T: std::ops::Mul<Output = f64>`. In that case, `Rhs = Self` means only `T * T` is valid, whereas in this case you specifically need `T * f64` here.

**Comment by willcrichton** [comment]
Ok, I have rebased / fixed and also updated the tests such that everything now passes under this PR.

File: src/test/ui/generic-associated-types/missing-bounds.stderr [hunk 4]
```diff
@@ -66,11 +66,11 @@ LL |         Self(self.0 + rhs.0)
    |
 help: consider restricting type parameter `B`
    |
-LL | impl<B: std::ops::Add<Output = B>> Add for D<B> {
-   |       +++++++++++++++++++++++++++
+LL | impl<B: std::ops::Add> Add for D<B> {
+   |       +++++++++++++++
```
Comment (estebank) [inline src/test/ui/generic-associated-types/missing-bounds.stderr:70]: Note to self: check if we can get this back.
