### PR TITLE
Fix alignment of stores to scalar pair

### LINKED ISSUE #56267: llvm lint: Undefined behavior: Memory reference address is misaligned
reduced from num_cpus:
````rust
extern crate libc;

#[inline]
pub fn get_physical() -> usize {
    get_num_physical_cpus()
}

#[cfg(target_os = "linux")]
fn get_num_physical_cpus() -> usize {
    use std::collections::HashSet;
    use std::fs::File;
    use std::io::BufRead;
    use std::io::BufReader;

    let file = File::open("/proc/cpuinfo").unwrap();
    let reader = BufReader::new(file);
    let mut set = HashSet::new();
    for _ in reader.lines().filter_map(|result| result.ok()) {
        set.insert((0, 0));
    }
    4
}
````
built with
` RUSTFLAGS="-C passes=lint" cargo build --release  -j 1` yields
````
   Compiling libc v0.2.44
Unusual: Return statement in function with noreturn attribute
  ret void
   Compiling num_cpus v1.8.0 (/tmp/num_cpus)
Undefined behavior: Memory reference address is misaligned
  %61 = load i32, i32* %60, align 8
Undefined behavior: Memory reference address is misaligned
  %132 = load i32, i32* %131, align 8
    Finished release [optimized] target(s) in 1.12s
````
cc #7463

````
rustc 1.32.0-nightly (6bfb46e4a 2018-11-26)
binary: rustc
commit-hash: 6bfb46e4ac9a2704f06de1a2ff7a4612cd70c8cb
commit-date: 2018-11-26
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0
````

### PR DESCRIPTION
**Pull request by nikic**
The alignment for the second element of a scalar pair is not the same as for the first element, make sure it is calculated correctly. This fixes #56267.

r? @eddyb

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
@nikomatsakis @Mark-Simulacrum Any chance we could still get this into the beta?

**Comment by Mark-Simulacrum** [comment]
Cc @rust-lang/compiler for beta approval. This fixes a clear beta regression but I'm not sure what the impact of that regression is.

Overall I'm fairly neutral on backporting - the patch looks relatively small.

**Comment by oli-obk** [comment]
Accepting for beta, small patch for fixing an unsoundness regression.

**Comment by eddyb** [comment]
I think there's more, similar, issues, I tried to do a search and found this:

https://github.com/rust-lang/rust/blob/b68fc18c45350e1cdcd83cecf0f12e294e55af56/src/librustc_codegen_llvm/builder.rs#L594

That's the load counterpart to this PR, so I think it should also be fixed..

File: src/test/codegen/issue-56267.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+#[allow(dead_code)]
+pub struct Foo<T> {
+    foo: u64,
+    bar: T,
+}
+
+// The store writing to bar.1 should have alignment 4. Not checking
+// other stores here, as the alignment will be platform-dependent.
+
+// CHECK: store i32 [[TMP1:%.+]], i32* [[TMP2:%.+]], align 4
```
Comment (eddyb) [inline src/test/codegen/issue-56267.rs]: This could be using `%{{.+}}`, since `TMP1` and `TMP2` aren't used. (but we should merge this PR first)

**Comment by nikomatsakis** [comment]
Removing beta-accepted so we can discuss in today's @rust-lang/compiler meeting.

**Comment by nikomatsakis** [comment]
Relevant: affects `num-cpus`, a pretty fundamental crate

**Comment by alexcrichton** [comment]
@nikic can you help out with the backport to beta? While this patch applies cleanly it generates:

```
error[E0277]: the trait bound `&builder::Builder<'_, 'll, 'tcx>: rustc_target::abi::HasDataLayout` is not satisfied
   --> librustc_codegen_llvm/mir/operand.rs:301:47
    |
301 |                 let b_offset = a_scalar.value.size(bx).align_to(b_scalar.value.align(bx).abi);
    |                                               ^^^^ the trait `rustc_target::abi::HasDataLayout` is not implemented for `&builder::Builder<'_, 'll, 'tcx>`

error[E0599]: no method named `align_to` found for type `rustc_target::abi::Size` in the current scope
   --> librustc_codegen_llvm/mir/operand.rs:301:56
    |
301 |                 let b_offset = a_scalar.value.size(bx).align_to(b_scalar.value.align(bx).abi);
    |                                                        ^^^^^^^^

error[E0277]: the trait bound `&builder::Builder<'_, 'll, 'tcx>: rustc_target::abi::HasDataLayout` is not satisfied
   --> librustc_codegen_llvm/mir/operand.rs:301:80
    |
301 |                 let b_offset = a_scalar.value.size(bx).align_to(b_scalar.value.align(bx).abi);
    |                                                                                ^^^^^ the trait `rustc_target::abi::HasDataLayout` is not implemented for `&builder::Builder<'_, 'll, 'tcx>`

error[E0615]: attempted to take value of method `abi` on type `rustc_target::abi::Align`
   --> librustc_codegen_llvm/mir/operand.rs:301:90
    |
301 |                 let b_offset = a_scalar.value.size(bx).align_to(b_scalar.value.align(bx).abi);
    |                                                                                          ^^^
    |
    = help: maybe a `()` to call it is missing?

error: aborting due to 4 previous errors

Some errors occurred: E0277, E0599, E0615.
For more information about an error, try `rustc --explain E0277`.
```

and I'm not sure how to easily fix those off the top of my head!

**Comment by nikic** [comment]
@alexcrichton The `bx` arguments probably need to be `bx.cx` on beta.

**Comment by nikic** [comment]
The whole expression should be `a.value.size(bx.cx).abi_align(b.value.align(bx.cx))`.

**Comment by alexcrichton** [comment]
Thanks! I think that solves the first and third errors, but the second/fourth still persist :(

```
error[E0599]: no method named `align_to` found for type `rustc_target::abi::Size` in the current scope
   --> librustc_codegen_llvm/mir/operand.rs:301:59
    |
301 |                 let b_offset = a_scalar.value.size(bx.cx).align_to(b_scalar.value.align(bx.cx).abi);
    |                                                           ^^^^^^^^

error[E0615]: attempted to take value of method `abi` on type `rustc_target::abi::Align`
   --> librustc_codegen_llvm/mir/operand.rs:301:96
    |
301 |                 let b_offset = a_scalar.value.size(bx.cx).align_to(b_scalar.value.align(bx.cx).abi);
    |                                                                                                ^^^
    |
    = help: maybe a `()` to call it is missing?

error: aborting due to 2 previous errors

Some errors occurred: E0599, E0615.
For more information about an error, try `rustc --explain E0599`.

```

**Comment by nikic** [comment]
@alexcrichton Could you please try the `a_scalar.value.size(bx.cx).abi_align(b_scalar.value.align(bx.cx))` variant from my last comment? That's what similar code on beta uses. If that doesn't do it I'll try locally.

**Comment by alexcrichton** [comment]
[Appears to work](https://github.com/rust-lang/rust/pull/56352)! Or at least it compiles, running some tests real quick. Thanks!
