### PR TITLE
Make Box<dyn FnOnce> respect self alignment

### LINKED ISSUE #68304: Box<dyn FnOnce> doesn't respect self alignment
The following code fails on stable:
When compiled in release mode, the `"optimized out"` assert is optimized out by LLVM even though it checks the exact same condition as the other assert, as can be verified by testing in debug mode.

Note that it's theoretically possible for the stack to be aligned correctly such that the bug is suppressed, but that's not likely. The 256's can be replaced with larger alignments if that happens.

The bug is caused by the impl of `Box<dyn FnOnce>` copying `self` to the stack with the default alignment of 16.

```rust
#![allow(dead_code)]
#[repr(align(256))]
struct A {
    v: u8
}

impl A {
    fn f(&self) -> *const A {
        assert_eq!(self as *const A as usize % 256, 0, "optimized out");
        self
    }
}

fn f2(v: u8) -> Box<dyn FnOnce() -> *const A> {
    let a = A { v };
    Box::new(move || {
        a.f()
    })
}

#[test]
fn test() {
    let addr = f2(0)();
    assert_eq!(addr as usize % 256, 0, "addr: {:?}", addr);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd447ff2503b311c957b469eb26ed8e6))

### PR DESCRIPTION
**Pull request by spastorino**
Closes #68304 

r? @eddyb @nikomatsakis

### CODE REVIEW

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 1]
```diff
@@ -21,6 +21,37 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+            let param_env = self.hir.param_env;
+
+            let arg = self.hir.mirror(arg.clone());
+            let ty = arg.ty;
+            let span = arg.span;
+
+            if !ty.is_sized(tcx.at(span), param_env)
+                && !ty.is_copy_modulo_regions(tcx, param_env, span)
+            {
+                return self.expr_as_operand(block, local_scope, arg);
```
Comment (nikomatsakis) [inline src/librustc_mir_build/build/expr/as_operand.rs:48]: So I think what this should be is invoke `as_temp` to get back a `Local` (let's call it `tmp`), and then return the operand of `Operand::Move(*tmp)`.

**Review by nikomatsakis — COMMENTED** [review]
Also, needs a test!

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 2]
```diff
@@ -21,6 +21,37 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+        if let ExprKind::Deref { ref arg } = expr.kind {
+            let tcx = self.hir.tcx();
+            let param_env = self.hir.param_env;
+
+            let arg = self.hir.mirror(arg.clone());
+            let ty = arg.ty;
+            let span = arg.span;
+
+            if !ty.is_sized(tcx.at(span), param_env)
+                && !ty.is_copy_modulo_regions(tcx, param_env, span)
```
Comment (oli-obk) [inline src/librustc_mir_build/build/expr/as_operand.rs:46]: what does `!Copy` have to do with anything here?

Comment (oli-obk) [reply src/librustc_mir_build/build/expr/as_operand.rs:46]: I'm guessing this is addressing

> The argument is moved (not copied),

I don't understand this reasoning, but note that I have not read the issue at all in the last weeks

Comment (eddyb) [reply src/librustc_mir_build/build/expr/as_operand.rs:46]: And it's redundant with `!is_sized`, because `Copy` requires `Sized` today.

Comment (eddyb) [reply src/librustc_mir_build/build/expr/as_operand.rs:46]: Maybe add `assert!(!ty.is_copy_modulo_regions(tcx, param_env, span))` with a comment about this being an unsized move.

**Comment by spastorino** [comment]
> Also, needs a test!

oh LOL, test was left untracked on my computer.

File: src/librustc_mir_build/build/expr/as_operand.rs (hunk 2 above)
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done!

**Comment by spastorino** [comment]
This is still not working :/

File: src/test/ui/fn/dyn-fn-alignment.rs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+#![allow(dead_code)]
+#[repr(align(256))]
+struct A {
+    v: u8,
+}
+
+impl A {
+    fn f(&self) -> *const A {
+        assert_eq!(self as *const A as usize % 256, 0, "optimized out");
```
Comment (RalfJung) [inline src/test/ui/fn/dyn-fn-alignment.rs:11]: The failure message here seems a bit odd?

Comment (spastorino) [reply src/test/ui/fn/dyn-fn-alignment.rs]: Yeah I've copied straight the test case from the issue but this is not needed for our tests. It's already covered in the main.

**Comment by spastorino** [comment]
@nikomatsakis @eddyb this should be now ready for review.

File: src/test/ui/unsized-locals/borrow-after-move.stderr [hunk 4]
```diff
@@ -45,12 +45,12 @@ LL |         println!("{}", &y);
 error[E0382]: borrow of moved value: `x`
   --> $DIR/borrow-after-move.rs:39:24
    |
+LL |         let x = "hello".to_owned().into_boxed_str();
+   |             - move occurs because `x` has type `std::boxed::Box<str>`, which does not implement the `Copy` trait
```
Comment (nikomatsakis) [inline src/test/ui/unsized-locals/borrow-after-move.stderr:49]: So... this is a bit suboptimal, in that the move is really occurring because `foo` was invoked on `*x` -- i.e., the type `str` -- but the new IR makes the borrow checker see it otherwise. I'm not sure how easy/hard that would be to fix. Probably not worth worrying about, I think.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 5]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
         self.as_operand(block, local_scope, expr)
     }
 
+    /// Returns an operand suitable for use until the end of the current
+    /// scope expression and suitable also to be passed as function arguments.
+    ///
+    /// The operand returned from this function will *not be valid* after
+    /// an ExprKind::Scope is passed, so please do *not* return it from
+    /// functions to avoid bad miscompiles.
+    crate fn as_call_temporary<M>(
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 6]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+        expr: M,
+    ) -> BlockAnd<Operand<'tcx>>
+    where
+        M: Mirror<'tcx, Output = Expr<'tcx>>,
+    {
+        let tcx = self.hir.tcx();
+
+        let local_scope = self.local_scope();
+        let expr = self.hir.mirror(expr);
+
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs:90]: Done but it doesn't seem to work, I'd need to investigate why, just pushed a WIP. All I can think of is that ty and scope are not get from the original expr but from the inner one.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 7]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+        if tcx.features().unsized_locals {
+            let ty = expr.ty;
+            let span = expr.span;
+            let param_env = self.hir.param_env;
+
+            if !ty.is_sized(tcx.at(span), param_env) {
+                // !sized means !copy, so this is an unsized move
+                assert!(!ty.is_copy_modulo_regions(tcx, param_env, span));
+
+                if let ExprKind::Scope { ref value, .. } = expr.kind {
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 8]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
         self.as_operand(block, local_scope, expr)
     }
 
+    /// Returns an operand suitable for use until the end of the current
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 9]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                // !sized means !copy, so this is an unsized move
+                assert!(!ty.is_copy_modulo_regions(tcx, param_env, span));
+
+                if let ExprKind::Scope { ref value, .. } = expr.kind {
+                    let value = self.hir.mirror(value.clone());
+
+                    if let ExprKind::Deref { ref arg } = value.kind {
+                        let arg = self.hir.mirror(arg.clone());
+
+                        let operand =
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done.

File: src/test/ui/unsized-locals/double-move.stderr [hunk 10]
```diff
@@ -38,25 +38,25 @@ LL |         y.foo();
...
 
-error[E0382]: use of moved value: `*x`
+error[E0382]: use of moved value: `x`
   --> $DIR/double-move.rs:45:9
    |
 LL |         let _y = *x;
    |                  -- value moved here
 LL |         x.foo();
-   |         ^ value used here after move
+   |         ^ value used here after partial move
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/test/ui/unsized-locals/double-move.stderr:47]: Done.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 11]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                            unpack!(block = self.as_temp(block, local_scope, arg, Mutability::Mut));
+                        let place = Place {
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 12]
```diff
@@ -21,6 +21,55 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+            let param_env = self.hir.param_env;
+
+            if !ty.is_sized(tcx.at(span), param_env) {
+                // !sized means !copy, so this is an unsized move
+                assert!(!ty.is_copy_modulo_regions(tcx, param_env, span));
+
+                if let ExprKind::Scope { ref value, .. } = expr.kind {
+                    let value = self.hir.mirror(value.clone());
+
+                    if let ExprKind::Deref { ref arg } = value.kind {
```
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: Done.

File: src/librustc_mir_build/build/expr/as_operand.rs [hunk 13]
```diff
@@ -75,39 +75,49 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
-        let expr = self.hir.mirror(expr);
+        if let ExprKind::Scope { region_scope, lint_level, value } = expr.kind {
+            let source_info = this.source_info(expr.span);
+            let region_scope = (region_scope, source_info);
+            return this
+                .in_scope(region_scope, lint_level, |this| this.as_call_operand(block, value));
+        }
+
+        let tcx = this.hir.tcx();
+        let local_scope = this.local_scope();
```
Comment (nikomatsakis) [inline src/librustc_mir_build/build/expr/as_operand.rs]: So the bug is about this line -- this gets the scope in which the returned value should be valid. The intent is to read the "enclosing scope at the time that `as_call_operand` was called. But because we are now recursing into scopes, what we're getting is an inner scope instead -- i.e., something specific to this particular operand.

Basically for a call, there are (at least) two scopes involved:

```
foo(    // <---------------+ scope for `foo(*x)`
  *x,   // scope for `*x`  |
) // <---------------------+
```

The `local_scope` as we initially call `as_call_operand` is the outer scope, the one for `foo(*x)`, but once we recurse, `local_scope` refers to `*x`. 

I'll push the commit I used to test this theory, which also fixes the problem. It basically just passes in `local_scope` as a parameter. Maybe it'd be better even to rename it to `call_scope` or something like that.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc_mir_build/build/expr/as_operand.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (bjorn3) [reply src/librustc_mir_build/build/expr/as_operand.rs]: The link refers to a rollup pr, not an issue.

File: src/librustc_mir_build/build/expr/as_operand.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: The approach is now working!.

File: src/librustc_mir_build/build/expr/as_operand.rs (hunk 13 above)
Comment (spastorino) [reply src/librustc_mir_build/build/expr/as_operand.rs]: @nikomatsakis right, I've followed a setup similar to what we have in `as_operand`. Check it out and please send me your patch again because I've force pushed and if I'm not wrong you also wrote some comments and some other useful stuff :).

**Comment by nikomatsakis** [comment]
@spastorino I pushed the edits to the comments that I made, as requested. I think they're a mild improvement.

**Review by nikomatsakis — APPROVED** [review]

**Comment by cramertj** [comment]
Did this also fix https://github.com/rust-lang/rust/issues/61042?
