### PR TITLE
Fix ambiguous cases of multiple & in elided self lifetimes

### LINKED ISSUE #117715: `self: &Box<Self>` produces confusing error due to failure to spot elided lifetime
### Code

```Rust
struct Concrete(u32);

impl Concrete {
    fn m(self: &std::boxed::Box<Self>) -> &u32 {
        &self.0
    }
}
```

### Current output

```Shell
error[E0106]: missing lifetime specifier
 --> src/lib.rs:4:43
  |
4 |     fn m(self: &std::boxed::Box<Self>) -> &u32 {
  |                ----------------------     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which `self` it is borrowed from
help: consider introducing a named lifetime parameter
  |
4 |     fn m<'a>(self: &'a std::boxed::Box<Self>) -> &'a u32 {
  |         ++++        ++                            ++

For more information about this error, try `rustc --explain E0106`.
error: could not compile `playground` (lib) due to previous error
```

### Desired output

```Shell
Ideally, rustc recognizes the elided lifetime in the `self` parameter and uses that.

Alternatively, "the signature does not say which `self` it is borrowed from" is reworded to more accurately describe the error.
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

```rust
fn n(self: &std::boxed::Box<Self>, _other: &u32) -> &u32 {
    &self.0
}
```

results in an error where rustc assumes we're returning the `_other` parameter, which presumably results from the same failure to spot a lifetime attached to `self`.

This issue was identified during discussion about a new Rust [RFC, here](https://github.com/rust-lang/rfcs/pull/3519#discussion_r1381792163).

I suspect this is caused by something within `find_lifetime_for_self` which isn't aware of the need to support things like `Box` as a `self` type: I haven't spotted the bug yet, I thought it was more important to get it reported properly first.

### PR DESCRIPTION
**Pull request by adetaylor**
This change proposes simpler rules to identify the lifetime on `self` parameters which may be used to elide a return type lifetime.

## The old rules

(copied from [this comment](https://github.com/rust-lang/rust/pull/117967#discussion_r1420554242))

Most of the code can be found in [late.rs](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html) and acts on AST types. The function [resolve_fn_params](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html#2006), in the success case, returns a single lifetime which can be used to elide the lifetime of return types.

Here's how:
* If the first parameter is called self then we search that parameter using "`self` search rules", below
* If no unique applicable lifetime was found, search all other parameters using "regular parameter search rules", below

(In practice the code does extra work to assemble good diagnostic information, so it's not quite laid out like the above.)

### `self` search rules

This is primarily handled in [find_lifetime_for_self](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html#2118) , and is described slightly [here](https://github.com/rust-lang/rust/issues/117715#issuecomment-1813115477) already. The code:

1. Recursively walks the type of the `self` parameter (there's some complexity about resolving various special cases, but it's essentially just walking the type as far as I can see)
2. Each time we find a reference anywhere in the type, if the **direct** referent is `Self` (either spelled `Self` or by some alias resolution which I don't fully understand), then we'll add that to a set of candidate lifetimes
3. If there's exactly one such unique lifetime candidate found, we return this lifetime.

### Regular parameter search rules

1. Find all the lifetimes in each parameter, including implicit, explicit etc.
2. If there's exactly one parameter containing lifetimes, and if that parameter contains exactly one (unique) lifetime, *and if we didn't find a `self` lifetime parameter already*, we'll return this lifetime.

## The new rules

There are no changes to the "regular parameter search rules" or to the overall flow, only to the `self` search rules which are now:

1. Recursively walks the type of the `self` parameter, searching for lifetimes of reference types whose referent **contains** `Self`.[^1]
2. Keep a record of:
   * Whether 0, 1 or n unique lifetimes are found on references encountered during the walk
4. If no lifetime was found, we don't return a lifetime. (This means other parameters' lifetimes may be used for return type lifetime elision).
5. If there's one lifetime found, we return the lifetime.
6. If multiple lifetimes were found, we abort elision entirely (other parameters' lifetimes won't be used).

[^1]: this prevents us from considering lifetimes from inside of the self-type

## Examples that were accepted before and will now be rejected

```rust
fn a(self: &Box<&Self>) -> &u32
fn b(self: &Pin<&mut Self>) -> &String
fn c(self: &mut &Self) -> Option<&Self>
fn d(self: &mut &Box<Self>, arg: &usize) -> &usize // previously used the lt from arg
```

### Examples that change the elided lifetime

```rust
fn e(self: &mut Box<Self>, arg: &usize) -> &usize
//         ^ new                ^ previous
```

## Examples that were rejected before and will now be accepted

```rust
fn f(self: &Box<Self>) -> &u32
```

---

*edit: old PR description:*

```rust
  struct Concrete(u32);

  impl Concrete {
      fn m(self: &Box<Self>) -> &u32 {
          &self.0
      }
  }
```

resulted in a confusing error.

```rust
  impl Concrete {
      fn n(self: &Box<&Self>) -> &u32 {
          &self.0
      }
  }
```

resulted in no error or warning, despite apparent ambiguity over the elided lifetime.

Fixes https://github.com/rust-lang/rust/issues/117715

### CODE REVIEW

**Comment by adetaylor** [comment]
@cjgillot hello, I didn't know rustbot would assign a reviewer for a draft PR. This isn't yet ready.

File: tests/ui/self/elision/ref-self-multi.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+impl<T, P> Deref for Wrap<T, P> {
+    type Target = T;
+    fn deref(&self) -> &T { &self.0 }
+}
+
+impl Struct {
+    fn ref_box_ref_Self(self: &Box<&Self>, f: &u32) -> &u32 {
+        f
+        //~^ ERROR missing lifetime specifier
```
Comment (RalfJung) [inline tests/ui/self/elision/ref-self-multi.rs:20]: This error should be on the line with the function signature, not at the `f`, I think?

**Comment by clubby789** [comment]
> hello, I didn't know rustbot would assign a reviewer for a draft PR. This isn't yet ready.

Btw, you can use `r<question mark> ghost` in your initial mesage to prevent a reviewer being assigned

**Comment by adetaylor** [comment]
I've now marked this as ready for review. Per discussion on https://github.com/rust-lang/rust/issues/117715, this will need a crater run.

It's possible that we want to make the tests a bit more thorough before merging, but it would be good to initially get feedback on the approach (and maybe a crater run to find out if it's doomed)

File: tests/ui/self/elision/ref-self-multi.rs [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+struct Wrap<T, P>(T, PhantomData<P>);
+
+impl<T, P> Deref for Wrap<T, P> {
+    type Target = T;
+    fn deref(&self) -> &T { &self.0 }
+}
+
+impl Struct {
+    fn ref_box_ref_Self(self: &Box<&Self>, f: &u32) -> &u32 {
```
Comment (lcnr) [inline tests/ui/self/elision/ref-self-multi.rs:20]: is that desirable? 🤔 would expect this to be ambiguous

Comment (adetaylor) [reply tests/ui/self/elision/ref-self-multi.rs:20]: Yeah - these tests are confusing. This test passes _because_ lifetime of the self type is ambiguous, so the elision rules instead assume we want to return the lifetime of the `f`, which is what we do.

We could instead say "lifetime of the self type is unclear, elision is impossible, manually specify a lifetime" - I _think_ I tried that and it broke a larger number of tests.

Comment (lcnr) [reply tests/ui/self/elision/ref-self-multi.rs:20]: alright :thinking: I think that our UI tests don't perfectly represent the way users use Rust, as `self: Something` feels like it should be overrepresented in our test suite.

My feelings here is: can we get a full and self-contained explanation of the elision rules rn, i.e. before this bug, and then the different alternatives :sweat_smile: I would have to dive into this issue myself to really have an opinion. But lifetime elision feels like something where we can work towards the "perfect" solution thanks to editions.

**Comment by lcnr** [comment]
let's do a crater run. I am still unsure about the exact behavior we want and probably have to look into this myself to figure it out 🤔 but for now

@bors try

**Comment by lcnr** [comment]
@craterbot check

**Comment by adetaylor** [comment]
I've never looked at a crater report before, but here's an attempt at analysis.

### Crates which this PR has broken

* Three real crates have actually been broken by this. In every case, they have a `self` type containing multiple references, and previously our (faulty) analysis ignored some of them, and allowed the return type lifetime to be elided. Here are the functions in question:
   ```rust
   fn b(self: &Pin<&mut Self>) -> &String
   fn a(self: &'_ mut WindowsMut<&'lt mut [T], WINDOW_SIZE>) -> Option<&'_ mut [T;  WINDOW_SIZE]>
   fn take_ext(self: &mut &Self, take: usize) -> Option<&Self>
   ```
   (Links: [1](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/reg/lending-iterator-0.1.7/log.txt), [2](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/reg/lending-iterator-0.1.7/log.txt), [2 (duplicate)](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/reg/nougat-0.2.4/log.txt), [3](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/reg/voprf-0.5.0-pre.6/log.txt).)
* There's also [this](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/gh/chen244.raindropshell/log.txt) and [this](https://crater-reports.s3.amazonaws.com/pr-117967/try%2357fd74335bb14b59b719dc3cc5bc4257e73f33ce/reg/stream-jenkins-logs-0.1.2/log.txt) which appear to be flakey unrelated errors.

### Crates which this PR has fixed

* We don't expect it to fix any pre-existing code! But it appeared to fix an [overflow in this build](https://crater-reports.s3.amazonaws.com/pr-117967/master%236f40082313d8374bdf962aba943a712d5322fae6/gh/lcdr.lu_packets/log.txt) and OOM problems in [this](https://crater-reports.s3.amazonaws.com/pr-117967/master%236f40082313d8374bdf962aba943a712d5322fae6/gh/arthurguedes375.Rust-Backpropagation/log.txt) and [this](https://crater-reports.s3.amazonaws.com/pr-117967/master%236f40082313d8374bdf962aba943a712d5322fae6/reg/rocc-0.1.33/log.txt) but I assume these are just flakey intermittent failures? (Again, this is my first time looking at crater, so perhaps it's normally 100% deterministic and something _has_ changed here)

### What now?

It would be easy to fix those crates by making lifetimes explicit, but their existence shows that this _is_ a compatibility break which has real-world consequences.

Is three crates a sufficiently tiny number that we consider this to be an acceptable compatibility break? Or, do we need to first warn on this change for a couple of releases? Or, do we need to make this change on an edition boundary?

**Comment by lcnr** [comment]
3 crates is acceptable breakage imo.

Can you try to change it to fail lifetime elision for the return type in the `Set1::Many` case while searching for the self type, pretty much change the rules to

My proposed rules would be something like this:
- each unspecified lifetime in the arguments gets elided to a unique lifetime
- if there are unspecified lifetimes in the return type, try to get the appropriate lifetime as follows:
   - collect all lifetimes in the self parameter (this already matches your current PR), depending on its count:
       - 0: collect all lifetimes found in all arguments, if there is a unique one, use it
       - 1: use the lifetime from self
       - more than 1: fail to elide the return lifetimes and error <- this diverges from your current impl

If that breaks too much code I think the following approach may also be interesting
- each unspecified lifetime in the arguments gets elided to a unique lifetime
- if there are unspecified lifetimes in the return type, try to get the appropriate lifetime as follows:
   - **search the innermost lifetime referencing self**, if none is found collect all lifetimes found in all arguments, if there is a unique one, use it impl

I would like to avoid falling back to using argument lifetimes if lifetimes for self is ambiguous, so I would like to either error if there are multiple "self lifetimes" or use the innermost one.

**Comment by adetaylor** [comment]
> I would like to avoid falling back to using argument lifetimes if lifetimes for self is ambiguous

Makes sense. I'll see what I can do.

**Comment by lcnr** [comment]
@craterbot check

File: tests/ui/self/elision/ref-self-multi.rs (hunk 1 above)
Comment (adetaylor) [reply tests/ui/self/elision/ref-self-multi.rs:24]: Fixed

**Comment by danielhenrymantilla** [comment]
Author of `lending-iterator/nougat` here.

So, we currently have:

```rs
impl<'lt> WindowsMut<&'lt mut [T]> {
    fn a(self: &mut Self) -> &mut [T] // currently works, will keep working
    fn b(self: &mut WindowsMut<&'lt mut [T]>) -> &mut [T] // currently works, will STOP working

    fn c(this: &mut Self) -> &mut [T] // currently works, will keep working
    fn d(this: &mut WindowsMut<&'lt mut [T]>) -> &mut [T] // does not work already.
```

I understand that this PR is thus making `b` behave more like `d`, even though it thus makes it as inconsistent w.r.t. `a` as `d` already is w.r.t. `c`.

Even though it is not pretty, I agree it's the least bad thing to have, so I support this PR, and will adjust my two crates accordingly (thanks @adetaylor for the thoughtful PRs!)

___

I would nonetheless like to take this opportunity to talk a bit about:

## Aside: edge cases of lifetime elision rules which are confusing

There are two slightly related aspects which can make lifetime elision rules (w.r.t. the output elided lifetime) be rather confusing, or poorly readable.

 1. The gist of it is that **output `'_` can "connect"/match an input _explicitly named_ lifetime "parameter"**.
 2. Worse, in certain cases this named lifetime "parameter" may not be generic at this layer (outer generic parameter), or may not be generic at all (`'static` hard-coded / fixed value)!

To illustrate, consider:

```rs
type Metadata = &'static str;

struct Foo<'lt>(&'lt str);

impl<'lt> Foo<'lt> {
    fn a(this: Self, metadata: &'static str) -> &str;
    fn b(this: Foo<'lt>, metadata: Metadata) -> &str;
}
```

What if I told you these two methods have different signatures

  - [Demo](https://rust.godbolt.org/z/68E1aeETr)

I personally find the capability of type aliases or `Self` aliases to affect semantics (here, those of lifetime elision rules) to be appaling.

It would thus be nice if certain efforts were made to try and go in the other directions, _e.g._, by linting whenever an output-elided lifetime (`'_`-explicitly, or implicitly) happens to match an _explicitly named_ input lifetime param, and even more so when this input lifetime "param" is `'static` or stems from an outer scope.

**Comment by lcnr** [comment]
sorry for not getting to this pr until now :sweat_smile: the comment by @danielhenrymantilla was involved enough so that I never got to feel comfortable wrt to the next steps as I lacked any kind of intuition here, moved the separate concerns into https://github.com/rust-lang/rust/issues/121152

I think that after going back to this PR every now and then I ended up at:

Eliding lifetimes in the return type using an explicit `'static` from the inputs feels very :/ to me and is something i would like to lint, part of #121152

With this PR the following now breaks
```rust
struct Foo<'a>(&'a str);

impl<'b> Foo<'b> {
    fn a<'a>(self: Self, a: &'a str) -> &str {
        a // ok
    }
    fn b<'a>(self: Foo<'b>, a: &'a str) -> &str {
        a // uses `'b` with this PR
    }
}
```
this is very similar to the example in the above comments. I continued thinking about this but think it is hard to actually "fix" this, so I would accept the inconsistently for now. idk if I consider it to be tracked as part of #121152

finally, I think we should land this PR.

We should propose an FCP explaining 1) the current rules 2) the proposed new rules 3) some minimal clear examples showing the difference. i personally would like the rules explained somewhat like this: https://github.com/rust-lang/rust/pull/117967#issuecomment-1883263023 (should also mention that the analysis uses the HIR types, not `ty` types). @adetaylor would you be up to write that, I will then start the types fcp

**Comment by adetaylor** [comment]
Sorry for the slow response - I've been [tied up with the arbitrary self types RFC](https://github.com/rust-lang/rfcs/pull/3519) - I'll get back to this in the next week or two with any luck, as I think this is a pre-requisite for actually landing the changes described in the RFC.

**Comment by adetaylor** [comment]
Hm, this appears to have _fixed_ some ICEs. That's unexpected. I will dig in.

**Comment by adetaylor** [comment]
This change proposes simpler rules to identify the lifetime on `self` parameters which may be used to elide a return type lifetime.

## The old rules

(copied from [this comment](https://github.com/rust-lang/rust/pull/117967#discussion_r1420554242))

Most of the code can be found in [late.rs](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html) and acts on AST types. The function [resolve_fn_params](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html#2006), in the success case, returns a single lifetime which can be used to elide the lifetime of return types.

Here's how:

1. If the first parameter is called self then we search that parameter using "`self` search rules", below
2. Search all other parameters using "regular parameter search rules", below

(In practice the code does extra work to assemble good diagnostic information, so it's not quite laid out like the above.)

### `self` search rules

This is primarily handled in [find_lifetime_for_self](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_resolve/late.rs.html#2118) , and is described slightly [here](https://github.com/rust-lang/rust/issues/117715#issuecomment-1813115477) already. The code:

1. Recursively walks the type of the `self` parameter (there's some complexity about resolving various special cases, but it's essentially just walking the type as far as I can see)
2. Each time we find a reference anywhere in the type, if the **direct** referent is `Self` (either spelled `Self` or by some alias resolution which I don't fully understand), then we'll add that to a set of candidate lifetimes
3. If there's exactly one such lifetime candidate found, we return this lifetime.

### Regular parameter search rules

1. Find all the lifetimes in each parameter, including implicit, explicit etc.
2. If there's exactly one parameter containing lifetimes, and if that parameter contains exactly one (unique) lifetime, *and if we didn't find a `self` lifetime parameter already*, we'll return this lifetime.

## The new rules

There are no changes to the "regular parameter search rules" or to the overall flow, only to the `self` search rules which are now:

1. Recursively walks the type of the `self` parameter in the same way as before
2. Keep a record of:
   * Whether 0, 1 or n lifetimes are found during the walk
   * Whether `Self` is found during the walk (including via aliases in the same way as before)
3. If there's one lifetime found, _and_ `Self` was found, we return the lifetime.
4. Otherwise we return no lifetimes.

## Examples that were accepted before and will now be rejected

```rust
fn a(self: &Box<&Self>) -> &u32
fn b(self: &Pin<&mut Self>) -> &String
fn c(self: &'_ mut WindowsMut<&'lt mut [T], WINDOW_SIZE>) -> Option<&'_ mut [T;  WINDOW_SIZE]>
fn d(self: &mut &Self, take: usize) -> Option<&Self>
```

## Examples that were rejected before and will now be accepted

```rust
fn e(self: &Box<Self>) -> &u32
fn f(self: &Box<Self>, _other: &u32) -> &u32 { 
    &self.0
}
```

I've no idea if I can ask RFCbot to initiate an FCP, but let's try it, otherwise @lcnr please help!

@rfcbot fcp merge

**Comment by lcnr** [comment]
> Otherwise we return no lifetimes.

I remember us considering to fail with ambiguity for >1 lifetimes instead, even if there's a unique arg lifetime :thinking: 

Another important thing to mention: this happens on the `ast` and currently does not resolve `SelfTyAlias` to the actual impl self type. Maybe it should? think the examples should therefore actually explicitly specify the self type.

From what I can tell the behavior as proposed (ignoring the num self-lts >1 case) is as follows?
```rust
struct Foo<'a>(&'a ());
impl<'a> Foo<'a> {
    fn foo(self: &Self) -> &u32 { .. } // ok
    fn bar(self: &Foo<'a>) -> &u32 { .. } // ambig
    fn baz1(self: Self) -> &u32 { .. } // zero self-lts found -> error
    fn baz2(self: Self, arg: &u32) -> &u32 { .. } // use lt from `arg`
    fn baz3(self: Foo<'a>, arg: &u32) -> &u32 { .. } // use lt from `self`
}
```

looking back at my previous comment:

> With this PR the following now breaks
> 
> ```rust
> struct Foo<'a>(&'a str);
> 
> impl<'b> Foo<'b> {
>     fn a<'a>(self: Self, a: &'a str) -> &str {
>         a // ok
>     }
>     fn b<'a>(self: Foo<'b>, a: &'a str) -> &str {
>         a // uses `'b` with this PR
>     }
> }
> ```
> 
> this is very similar to the example in the above comments. I continued thinking about this but think it is hard to actually "fix" this, so I would accept the inconsistently for now. idk if I consider it to be tracked as part of #121152

Actually, we can (mostly) fix that: we have the `Res` of the `self_ty` of the impl [source link](https://github.com/rust-lang/rust/blob/2a2c29aafa50bf6fe53d66b32070eba59f860ac3/compiler/rustc_resolve/src/late.rs#L2203-L2223), we can change it to not recurse into a type with the same `res`, changing it to

```rust
struct Foo<'a>(&'a ());
impl<'a> Foo<'a> {
    fn foo(self: &Self) -> &u32 { .. } // ok
    fn bar(self: &Foo<'a>) -> &u32 { .. } // ok (do not look into `Foo`)
    fn baz1(self: Self) -> &u32 { .. } // zero self-lts found -> error
    fn baz2(self: Self, arg: &u32) -> &u32 { .. } // use lt from `arg`
    fn baz3(self: Foo<'a>, arg: &u32) -> &u32 { .. } // use lt from `arg`
}
```
does that make sense to you and is this something you would consider doing?

**Comment by adetaylor** [comment]
> I remember us considering to fail lifetime elision with ambiguity for >1 lifetimes instead, even if there's a unique arg lifetime 🤔 did we drop that idea?

Are you talking about the case where there are multiple lifetimes but they're all the same? e.g. `fn a<'a>(self: &'a Box<&'a Self>)` or somesuch? I don't have a strong preference about what we do in that case. If you think it's best to reject them that's OK with me, though we'll need another crater run - I'll give it a try.

> we can change it to not recurse into a type with the same `res`, changing it to

I'll give that a try too. I'm not totally sold that it merits making the rules more complex, but I'll see how it shapes up.

**Comment by lcnr** [comment]
my concern is `fn foo(self: &mut &Self, arg: &u32) -> &u32 {}` which I would like to see fail with ambiguity, but afaict your rules currently use the lt from `arg`.

**Comment by adetaylor** [comment]
> my concern is `fn foo(self: &mut &Self, arg: &u32) -> &u32 {}` which I would like to see fail with ambiguity, but afaict your rules currently use the lt from `arg`.

Ah, I did fix that (if I'm understanding correctly) in [e62599f](https://github.com/rust-lang/rust/pull/117967/commits/e62599f8569509e5ebbea407d81f77fd0a9ca01b):

```rust
struct S;

impl S {
    fn foo(self: &mut &Self, arg: &u32) -> &u32 {
        arg
    }
}
```

gives:

```
error[E0106]: missing lifetime specifier
 --> test2.rs:4:44
  |
4 |     fn foo(self: &mut &Self, arg: &u32) -> &u32 {
  |                  ----------       ----     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from one of `self`'s 2 lifetimes or `arg`
help: consider introducing a named lifetime parameter
```

and a similar error appears for `d2`.

**Comment by lcnr** [comment]
then https://github.com/rust-lang/rust/pull/117967#issuecomment-2141939895 confused me :thinking: the current wording seems like we use an arg lt if there are multiple lifetimes in self

**Comment by adetaylor** [comment]
Yep - fair enough - I'll fix it

**Comment by adetaylor** [comment]
@lcnr 

> we can change it to not recurse into a type with the same `res`, changing it to

I explored the behavior here, and I realized my statement of the new rules in [the comment above](https://github.com/rust-lang/rust/pull/117967#issuecomment-2141939895) was insufficiently precise in another way.

Even after this change, lifetimes are only considered if they are attached to a reference (i.e. `&Foo` is considered but `Foo<'a>` isn't.) This is the same as the behavior before the change, but it's not obvious since this is exactly the part of the algorithm which is changing. I've adjusted the comment above to explain this.

So my hope is, this means we don't need to do anything additional (e.g. not recursing into the self type). In particular, this code already compiles fine:

```rust
struct Foo<'a>(&'a str);

impl<'b> Foo<'b> {
    fn a<'a>(self: Self, a: &'a str) -> &str {
        a // ok
    }
    fn b<'a>(self: Foo<'b>, a: &'a str) -> &str {
        a // ok
    }
}
```

and so does this:

```rust
struct Foo<'a>(&'a u32);
impl<'a> Foo<'a> {
    fn foo(self: &Self) -> &u32 { self.0 } // ok
    fn bar(self: &Foo<'a>) -> &u32 { self.0 } // ok (do not look into `Foo`)
    // fn baz1(self: Self) -> &u32 {  } // zero self-lts found -> error // errors as expected
    fn baz2(self: Self, arg: &u32) -> &u32 { arg } // use lt from `arg`
    fn baz3(self: Foo<'a>, arg: &u32) -> &u32 { arg } // use lt from `arg`
}
```

**Comment by lcnr** [comment]
does the following break?
```rust
struct Foo<T>(T);

impl<'a> Foo<&'a ()> {
    fn call_me(self: &Self) -> &() {
        self.0
    }
    
    fn call_me2(self: &Foo<&'a ()>) -> &() { self.0 }
}
```

**Comment by adetaylor** [comment]
It does break, yes:

```
error[E0106]: missing lifetime specifier
 --> test5.rs:6:40
  |
6 |     fn call_me2(self: &Foo<&'a ()>) -> &() { self.0 }
  |                       ------------     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of `self`'s 2 lifetimes it is borrowed from
help: consider using the `'a` lifetime
  |
6 |     fn call_me2(self: &Foo<&'a ()>) -> &'a () { self.0 }
  |                                         ++
```

Good spot. Is this a case where your proposal of not recursing into a type with the same `res` as `Self` would help?

**Comment by lcnr** [comment]
> Good spot. Is this a case where your proposal of not recursing into a type with the same `res` as `Self` would help?

yes, it should :thinking:

**Comment by adetaylor** [comment]
Yep, that seems to work - I will add a commit (with a test) and update the above comment tomorrow.

I'm not 100% sold that the extra mental complexity in the rules is worth it for this apparently niche scenario? - but I'm happy to trust your judgment there!

**Comment by adetaylor** [comment]
No probs, all feedback much appreciated before we broaden it out.

The [test failure above on `futures_io` is interesting](https://github.com/rust-lang/rust/pull/117967#issuecomment-2147814852). The [code is](https://docs.rs/futures-io/latest/src/futures_io/lib.rs.html#531):

```rust
impl<P> AsyncBufRead for Pin<P>
where
    P: DerefMut + Unpin,
    P::Target: AsyncBufRead,
{
    fn poll_fill_buf(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<&[u8]>> {
        self.get_mut().as_mut().poll_fill_buf(cx)
    }
}
```

so this does appear to violate the new rule you proposed. I wonder how common this is?

> I feel like it's a bit weird that `&self adds an elided useable lifetime while `Ref<'_, Self>` does not 

Yeah that is a bit weird, though it's kind of a hangover from how the rules previously worked, so I think if we change this there will be lots of breakage. I'm quite interested in fixing this because [my main interest in this whole area](https://github.com/rust-lang/rfcs/pull/3519) is to allow a `CppRef<T>` to be just as good as a `&T` from an ergonomic perspective, but for now I'm just trying to get elision sufficiently well-understood to be able to proceed with other parts of that RFC. I'll give it a try, anyway, and see what breaks.

**Comment by lcnr** [comment]
> so this does appear to violate the new rule you proposed. I wonder how common this is?

that is amazing :upside_down_face: yeah. Patterns like this definitely exist, and very much feel like we should not land this rule then. Please add the following as a test:

```rust
use std::pin::Pin;
trait Trait {
    fn method<'a>(self: Pin<&Self>, f: &'a u32) -> &'a u32 {
        f
    }
}

impl<P> Trait for Pin<P> {
    // This should not hide `&Self`, which would cause this to compile.
    fn method(self: Pin<&Self>, f: &u32) -> &u32 {
        f
    }
}
```

**Comment by adetaylor** [comment]
#### On the "no recurse into `Self` rule

I'm adding the [test you request here](https://github.com/rust-lang/rust/pull/117967#issuecomment-2149178722) but I am a little confused by your comment in the code - do you expect this to compile, or not? It doesn't:

```
   = note: expected signature `fn(Pin<&'1 Pin<P>>, &'a u32) -> &'a u32`
              found signature `fn(Pin<&'1 Pin<P>>, &'2 u32) -> &'1 u32`
   = help: the lifetime requirements from the `impl` do not correspond to the requirements in the `trait`
```

Hopefully that's what you're expecting.

It sounds like we're agreed that this rule can't be landed right now, and we do sometimes need to recurse into self. I've pushed [the branch to this tag for posterity](https://github.com/rust-lang/rust/compare/master...adetaylor:rust:fix-lifetime-elision-bug-do-not-recurse-into-self) and I've force-pushed to this PR to remove that commit.

#### On symmetry between `&T` and `Ref<T>`

> I feel like it's a bit weird that `&self` adds an elided useable lifetime while `Ref<'_, Self` does not 🤔 that would be my only remaining suggestion, apart from that I am quite happy with the rules.

I tried this. I've pushed [the experiment to this tag](https://github.com/rust-lang/rust/compare/master...adetaylor:rust:fix-lifetime-elision-bug-recurse-into-all-lifetimes) (though it would need a bit of cleanup). As expected it does yield some test failures:

```
    [ui] tests/ui/self/self_lifetime-async.rs
    [ui] tests/ui/self/self_lifetime.rs
    [ui] tests/ui/self/elision/lt-struct.rs
    [ui] tests/ui/self/elision/lt-assoc.rs
    [ui] tests/ui/self/elision/lt-assoc-async.rs
    [ui] tests/ui/self/elision/lt-struct-async.rs
```

(plus `[ui] tests/ui/self/elision/ignore-non-reference-lifetimes.rs` which I added in this PR).

A typical example failure is:

```
async fn take_Struct(self: Struct<'a>, f: &u32) -> &u32 {
                                                ---- help: add explicit lifetime `'a` to the type of `f`: `&'a u32`
       f
         ^ lifetime `'a` required
```

So, it does seem that there's tests specifically to ensure that lifetime elision does _not_ consider `<'a>`-type lifetimes.

We could certainly consider changing that? - but it would need another crater run and I'd prefer to do it separately from this PR.

#### Other comments

> > 3. If `Self` was not found, we don't return a lifetime. (This means other parameters' lifetimes may be used for return type lifetime elision).
> 
> when can that happen without getting a different error? `self: SomeTyNotMentioningSelf` always fails, shouldn't it?

Associated functions e.g.
```rust
struct Foo;
impl Foo {
    fn method_not_mentioning_self(a: u32) {}
}
```

> * If the first parameter is called self then we search that parameter using "`self` search rules", below
> * _If no unique applicable lifetime was found_, search all other parameters using "regular parameter search rules", below

Reworded. I had hoped that I could actually simplify the code along these lines as well, but the diagnostics don't work out so good.

> A hopefully final nit (and then I'll start this FCP)

Thanks! Assume I am clueless about the process :) When you're happy, I assume you will copy and paste [this comment](https://github.com/rust-lang/rust/pull/117967#issuecomment-2141939895) down to the bottom of the thread?

**Comment by lcnr** [comment]
> #### On the "no recurse into `Self` rule
> 
> I'm adding the [test you request here](https://github.com/rust-lang/rust/pull/117967#issuecomment-2149178722) but I am a little confused by your comment in the code - do you expect this to compile, or not? It doesn't:
> 
> ```
>    = note: expected signature `fn(Pin<&'1 Pin<P>>, &'a u32) -> &'a u32`
>               found signature `fn(Pin<&'1 Pin<P>>, &'2 u32) -> &'1 u32`
>    = help: the lifetime requirements from the `impl` do not correspond to the requirements in the `trait`
> ```

jup, I think it should fail with exactly this error message

> We could certainly consider changing that? - but it would need another crater run and I'd prefer to do it separately from this PR.

I think we ideally shouldn't consider named lifetimes, but yeah. Can leave that to a separate PR I guess

----

I still feel a bit uncomfortable about these changes, I feel like we haven't yet arrived at a good final solution. I think we have two desirable properties here, which conflict:

- copying a method signature from the trait definition to the impl works ~> should not look into the self type
   - this already doesn't work when inferring from arguments, e.g. `&T` int the trait can be `&&u32` in an impl
- changing `Self` to the actual type from the impl header should not impact behavior

and the separate, general properties of
- we choose the 'most sensible' lifetime available
- the rules are easy to explain and ideally without weird edge cases.

I think always consistently using lifetimes from self kinda sucks, e.g. `impl Trait for &'a u32` would break inference for `fn method(&self) -> &u32`, so I would try to somehow ignore lifetimes in `Self`. However, detecting when an arbitrary type is equal to the impl self type is impossible on the ast, so there will always be some broken cases.

There is one easy way to ignore lifetimes from the self type: only consider anonymous lifetimes :grin: I feel like doing that is generally desirable. I.e. never use named lifetimes `'a` as for the elided return lifetime. If they can specify it in an argument, they can also specify it in the return type.

I sadly don't know how much this breaks :/ but we could definitely do it over an edition

I think we can (mostly) prevent lifetimes leaking from the self type by adding the requirement "only use lifetimes from the self-type for elision of the if the self type is part of the pointee, e.g. `&Self` or `&Box<Self>`, but not `Box<Self, &Allocator>` or sth

## suggested complete rules

### in current editions

- walk through the self type and when encountering any lifetime `&'whatever Pointee`, check whether `Pointee` contains the self type, if so, add `'whatever` to the candidate set
- match on the number of candidates
   - `0`: continue by looking at the arguments
   - `1`: use this as the elided return lifetime
   - `2`: fail with a hard error
- look at arguments by considering all lifetimes `&'whatever Pointee`, if there's a unique one, use it

### in future editions

- walk through the self type and when encountering **any elided lifetime**, if so, add it to the candidate set
- match on the number of candidates
   - `0`: continue by looking at the arguments
   - `1`: use this as the elided return lifetime
   - `2`: fail with a hard error
- look at arguments by considering all lifetimes `&'whatever Pointee`, if there's a unique one, use it

--- 

does this change to the "self type walk" seem reasonable to you and is that something you wouldn't mind implementing? I think the future edition stuff is not something wehave to decide in this PR

**Comment by adetaylor** [comment]
I like the theory, but it might have to wait a few days for me to get a go at trying it!

File: tests/ui/self/elision/ref-assoc-async.rs [hunk 3]
```diff
@@ -18,22 +17,27 @@ impl Trait for Struct {
 impl Struct {
     async fn ref_AssocType(self: &<Struct as Trait>::AssocType, f: &u32) -> &u32 {
```
Comment (lcnr) [inline tests/ui/self/elision/ref-assoc-async.rs:18]: this now infers from `self` because the associated type constains the self type :sweat_smile: ah well, I guess it's fine

**Comment by lcnr** [comment]
let's do another crater run with these rules :thinking: I personally quite like them, they feel like the least bad option to me

**Comment by lcnr** [comment]
@craterbot check

**Comment by adetaylor** [comment]
Craterbot result interpretation:

* [`lu_packets`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/gh/lcdr.lu_packets/log.txt):
  ```
  [INFO] [stdout] error[E0275]: overflow evaluating the requirement `BitWriter<endio_bit::endian::BigEndian, _>: std::io::Write`
  [INFO] [stdout]   |
  [INFO] [stdout]   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`lu_packets`)
  [INFO] [stdout]   = note: required for `BitWriter<endio_bit::endian::BigEndian, _>` to implement `EWrite<LittleEndian>`
  [INFO] [stdout]   = note: required for `&'a [_]` to implement `for<'a> Serialize<LittleEndian, BitWriter<endio_bit::endian::BigEndian, _>>`
  [INFO] [stdout]   = note: 125 redundant requirements hidden
  [INFO] [stdout]   = note: required for `&Option<[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]>` to implement `Serialize<LittleEndian, BitWriter<endio_bit::endian::BigEndian, _>>`
  [INFO] [stdout]   = note: the full name for the type has been written to '/opt/rustwide/target/debug/deps/lu_packets-b9a10b97ce492327.long-type-2667777296302767703.txt'
  [INFO] [stdout]   = note: consider using `--verbose` to print the full type name to the console
  ```
  (appears unrelated to this change?)
* [`stripe-server`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/gh/aibo-bot.stripe-server/log.txt): possible some docker problem with craterbot?
* [`lindac`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/gh/linda-project.lindac/log.txt): disk full
* [`leetcode-rust`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/gh/rubenguc.leetcode-rust/log.txt): disk full
* [`rust-guessing-game`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/gh/rustiphyde.rust-guessing-game/log.txt): `ld` coredump building C++ parts, I can't see how that could be related
* [`perovskite_core`](https://crater-reports.s3.amazonaws.com/pr-117967-2/try%236e8eb3d1ba265821f8cc640134ce012d1ff211d8/reg/perovskite_core-0.0.3/log.txt): a real problem! As below.

The problem in this last crate is acutally in `vprof`:

```
[INFO] [stdout] error[E0106]: missing lifetime specifier
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/voprf-0.4.0-pre.3/src/serialization.rs:309:58
[INFO] [stdout]     |
[INFO] [stdout] 309 |     fn take_ext(self: &mut &Self, take: usize) -> Option<&Self>;
[INFO] [stdout]     |                       ----------                         ^ expected named lifetime parameter
[INFO] [stdout]     |
[INFO] [stdout]     = help: this function's return type contains a borrowed value, but the signature does not say which one of argument 1's 2 lifetimes it is borrowed from
[INFO] [stdout] help: consider introducing a named lifetime parameter
[INFO] [stdout]     |
[INFO] [stdout] 309 |     fn take_ext<'a>(self: &'a mut &'a Self, take: usize) -> Option<&'a Self>;
[INFO] [stdout]     |                ++++        ++      ++                               ++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0106]: missing lifetime specifier
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/voprf-0.4.0-pre.3/src/serialization.rs:313:58
[INFO] [stdout]     |
[INFO] [stdout] 313 |     fn take_ext(self: &mut &Self, take: usize) -> Option<&Self> {
[INFO] [stdout]     |                       ----------                         ^ expected named lifetime parameter
[INFO] [stdout]     |
[INFO] [stdout]     = help: this function's return type contains a borrowed value, but the signature does not say which one of `self`'s 2 lifetimes it is borrowed from
[INFO] [stdout] help: consider introducing a named lifetime parameter
[INFO] [stdout]     |
[INFO] [stdout] 313 |     fn take_ext<'a>(self: &'a mut &'a Self, take: usize) -> Option<&'a Self> {
[INFO] [stdout]     |                ++++        ++      ++                               ++
[INFO] [stdout] 
[INFO] [stdout] 
```

This is exactly the kind of ambiguity which we want to prevent with this PR, and (as far as I know) would have resulted in an error from any of the various permutations of this PR. I'll see about submitting a PR to `voprf` to disambiguate these, but in any case, I think that counts as a clean crater run. Do you agree @lcnr?

**Comment by lcnr** [comment]
nice!

alright, this change causes 3 crater regressions, with all affected projects accepting the fix PR, thanks @adetaylor for opening these. See https://github.com/rust-lang/rust/pull/117967#issuecomment-1888936220 for the originally affected crates.

The crater run with the final implementation did not uncover any additional issues. I've moved the FCP proposal into the PR description.

@rfcbot fcp merge

Thank you @adetaylor for your patience and good work!

**Comment by lcnr** [comment]
yikes

@rfcbot fcp cancel

@rfcbot fcp merge

**Comment by lcnr** [comment]
I am very happy with this change. I would like us to work towards not considering named lifetimes from arguments when eliding the return lifetime. See https://github.com/rust-lang/rust/pull/117967#issuecomment-2152290819 for my reasoning. This will allow us to simply the rules as we won't need to search for nested occurrences of `Self` anymore[^1]. It will also allow us to consider lifetimes from custom pointer types, such as `Ref<'_, Self>`. Right now we only consider the lifetime of the builtin reference types.


[^1]: which is broken as it happens on the `ast`: we `Self` inside of aliases and use `'a` from inside of the self-type if it recursively mentions itself `Foo<&'a Foo<()>>`

**Comment by adetaylor** [comment]
(just a note that on the specifics of the _implementation_ here, it's currently O(n^2) in the complexity of the type. But before landing it we should be able to make it O(n) with no changes to the semantics of the rules, if we so choose)

**Comment by jackh726** [comment]
I don't think this is much of, it at all, a T-types decision, but rather T-lang. To me, it doesn't pass the sniff test of "this is how the type system works", but of how syntax is translated into the underlying types.

One could argue this is also more general compiler as well as lang, since it is implementation, but with my compiler hat on, I think it's a stretch that we would want to be on FCP.

@rfcbot concern not-our-decision

**Comment by lcnr** [comment]
yeah, I think it's definitely at least at the border where both teams should be involved, and not purely t-types. I started a t-types FCP because imo it doesn't "change the spirit" of the elision rules, and also simply that I default to types FCPs for changes I am involved with. I should have at least pinged T-lang here and not doing so was my bad, will be more thoughtful going forward.

I feel fairly convinced by @jackh726, so going to cancel the types team FCP and throwing it over to lang and they can decide what to do with this.

@rfcbot fcp cancel

**Comment by nikomatsakis** [comment]
@adetaylor is this in any way related to explicit self types?

**Comment by adetaylor** [comment]
Yes, this is step one of [the plan for arbitrary self types](https://github.com/rust-lang/rust/issues/44874#issuecomment-2122179688). It's a pre-requisite because, during the RFC review process, some folks were concerned with making `self` types more complex or impactful without first resolving these inconsistencies.

I'd very much like to get this all squared away so I can continue down the plan of the actual RFC.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Discussed in the lang-team triage meeting today. Meeting consensus was that we should go forward with this (I believe). 

Example case (e) is interesting because, while it won't create UB in any existing programs, it *could* create a scenario where a library that was a sound API becomes unsound (if e.g. the body is doing a transmute and hence returns values with any lifetime). However, in that scenarion, it could as well be that an unsound API becomes sound (because the author expected the elision rules to favor `self`, as indeed I would have expected).

Looks good @aidanhs !

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Discussed in the lang-team triage meeting today. Meeting consensus was that we should go forward with this (I believe). 

Example case (e) is interesting because, while it won't create UB in any existing programs, it *could* create a scenario where a library that was a sound API becomes unsound (if e.g. the body is doing a transmute and hence returns values with any lifetime). However, in that scenario, it could as well be that an unsound API becomes sound (because the author expected the elision rules to favor `self`, as indeed I would have expected).

Nice work @adetaylor !

**Comment by tmandry** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the lang call today.  We liked the change, and we were happy about unblocking the work on arbitrary self types. This is now in FCP.

**Comment by traviscross** [comment]
@lcnr: Heads-up that FCP completed on this, so this is good to go forward as far as lang is concerned.

**Comment by lcnr** [comment]
missed that this finished FCP already. Thanks for the good work @adetaylor and thanks for sticking with it for this long!

@bors r+ rollup=never
