### PR TITLE
restore move out dataflow, add report of move out errors

### LINKED ISSUE #45363: MIR-borrowck: should distinguish "uninitalized" from "moved out of"
The AST-borrowck is often able to distinguish a path that was never assigned into (i.e. "uninitialized") from a path that had previously held a value but that value was subsequently moved elsewhere (i.e. "moved out of").

The MIR-borrowck currently uniformly reports both cases as instances of "uninitialized" state.

As an example: for the test `src/test/compile-fail/borrowck/borrowck-loan-in-overloaded-op.rs`, we have these diagnostics emitted:

```
% ./build/x86_64-unknown-l\
inux-gnu/stage1/bin/rustc -Z borrowck-mir ../src/test/compile-fail/borrowck/borrowck-loan-in-overloaded-op.rs
error[E0382]: use of moved value: `x` (Ast)
  --> ../src/test/compile-fail/borrowck/borrowck-loan-in-overloaded-op.rs:31:20
   |
31 |     let _y = {x} + x.clone(); // the `{x}` forces a move to occur
   |               -    ^ value used here after move
   |               |
   |               value moved here
   |
   = note: move occurs because `x` has type `foo`, which does not implement the `Copy` trait

error[E0381]: borrow of possibly uninitialized variable: `x` (Mir)
  --> ../src/test/compile-fail/borrowck/borrowck-loan-in-overloaded-op.rs:31:20
   |
31 |     let _y = {x} + x.clone(); // the `{x}` forces a move to occur
   |                    ^ use of possibly uninitialized `x`

error: aborting due to 2 previous errors
```

The first one is AST-borrowck, the second one MIR-borrowck.

Note in particular that AST-borrowck not only uses more precise language, but more importantly, it reports the specific span where the preceding move out occurred. This is perhaps the most important aspect of the diagnostic (especially for new-comers to Rust and move-semantics).

### PR DESCRIPTION
**Pull request by mikhail-m1**
fix https://github.com/rust-lang/rust/issues/45363 
r? @arielb1

### CODE REVIEW

File: src/librustc_mir/borrow_check.rs [hunk 1]
```diff
@@ -1083,17 +1098,47 @@ mod prefixes {
...
+        } else {
+            let msg = ""; //FIXME: add "partially " or "collaterally "
+
+            let mut err = self.tcx.cannot_act_on_moved_value(span,
+                                                             desired_action,
+                                                             msg,
+                                                             &self.describe_lvalue(lvalue),
+                                                             Origin::Mir);
+            err.span_label(span, format!("value {} here after move", desired_action));
+            for moi in mois {
```
Comment (arielb1) [inline src/librustc_mir/borrow_check.rs]: AST borrowck only shows 1 move here, as in:
```Rust
fn main() {
    let x = Box::new(1);
    if false {
        let _y = x;
    } else {
        drop(x);
    }
    x;
}
```

Comment (arielb1) [reply src/librustc_mir/borrow_check.rs]: Also, AST borrowck prefers the "value might be uninitialized" error to the "value might be moved" one - you can get it if you add a "move" representing values being uninitialized at the start of a function to the move-propagation code, but I won't hold it against you.

File: src/librustc_mir/dataflow/impls/mod.rs [hunk 2]
```diff
@@ -399,6 +436,115 @@ impl<'a, 'gcx, 'tcx> BitDenotation for DefinitelyInitializedLvals<'a, 'gcx, 'tcx
...
+            mir::StatementKind::Validate(..) |
+            mir::StatementKind::Nop => {}
+        }
+    }
+
+    fn terminator_effect(&self,
+                         sets: &mut BlockSets<MoveOutIndex>,
+                         location: Location)
+    {
+        let (mir, move_data) = (self.mir, self.move_data());
```
Comment (arielb1) [inline src/librustc_mir/dataflow/impls/mod.rs]: this code doesn't account for `DropAndReplace` - that should be handled the same way as an assignment above, so it would be buggy in the case of e.g.

```Rust
let x = Box::new(0);
let _u = x;
x = Box::new(1);
drop(x);
use(x);
```

**Comment by arielb1** [comment]
nice PR, r=me modulo nits (you only have to fix the 1-error and the DropAndReplace problems - I'm not sure defaulting to "maybe uninitialized" is actually better).

**Comment by arielb1** [comment]
Actually, could you make it so that the moving-statements pass only runs if an error occurred? This would avoid it slowing down the normal error-free path.

**Comment by arielb1** [comment]
r=me if this is green on travis
