### PR TITLE
incr-comp: hash and serialize span end line/column

### LINKED ISSUE #46744: Panic compiling `multiplex-rs`
Index out of bounds ICE while compiling [multiplex-rs](https://github.com/Vurich/libp2p-rs/tree/master/multiplex-rs). I don't know enough about why this could happen to produce a minimal reproduction. Backtrace:

```
thread 'rustc' panicked at 'index out of bounds: the len is 136 but the index is 146', /checkout/src/liballoc/vec.rs:1548:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: <rustc::ty::maps::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  11: serialize::serialize::Decoder::read_struct
  12: serialize::serialize::Decoder::read_struct
  13: serialize::serialize::Decoder::read_struct
  14: serialize::serialize::Decoder::read_seq
  15: <rustc::mir::Mir<'tcx> as serialize::serialize::Decodable>::decode::{{closure}}
  16: rustc::ty::maps::on_disk_cache::OnDiskCache::try_load_query_result
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  18: rustc::ty::maps::TyCtxtAt::optimized_mir
  19: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::optimized_mir
  20: rustc_metadata::encoder::<impl rustc_metadata::isolated_encoder::IsolatedEncoder<'a, 'b, 'tcx>>::encode_optimized_mir
  21: rustc_metadata::encoder::<impl rustc_metadata::isolated_encoder::IsolatedEncoder<'a, 'b, 'tcx>>::encode_info_for_impl_item
  22: rustc_metadata::encoder::<impl rustc_metadata::index_builder::IndexBuilder<'a, 'b, 'tcx>>::encode_addl_info_for_item
  23: rustc::hir::Crate::visit_all_item_likes
  24: rustc_metadata::encoder::encode_metadata
  25: rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  26: rustc::ty::context::TyCtxt::encode_metadata
  27: rustc_trans::base::write_metadata
  28: rustc::util::common::time
  29: rustc_trans::base::trans_crate
  30: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  31: rustc_driver::driver::phase_4_translate_to_llvm
  32: rustc_driver::driver::compile_input::{{closure}}
  33: <std::thread::local::LocalKey<T>>::with
  34: <std::thread::local::LocalKey<T>>::with
  35: rustc::ty::context::TyCtxt::create_and_enter
  36: rustc_driver::driver::compile_input
  37: rustc_driver::run_compiler
```

### LINKED ISSUE #59954: ICE when iterating over string literal with manual newline insertions
The error message by the compiler was, `thread 'rustc' panicked at 'index out of bounds: the len is 73 but the index is 74', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/slice/mod.rs:2539:10`.

The code:
```rust
pub fn search<'a>(query: &str, contents: &'a str) -> Vec<&'a str> {
    let mut results = Vec::new();
    for line in contents.lines() {
        if line.contains(query) {
            results.push(line);
        }
    }
    results
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn one_result() {
        let query = "duct";
        let contents = "Rust:\nsafe, fast, productive.\nPick three.";
        assert_eq!(vec!["safe, fast, productive."], search(query, contents));
    }
}
```
Changing the `contents` string literal to be formatted in the conventional way, i.e. without the manually inserted newline characters makes the code compile again (see below).

```rust
        let contents = "\
Rust:
safe, fast, productive.
Pick three.";
```

## Meta

The complete error message
```
$ cargo test
   Compiling minigrep v0.1.0 (/Users/snOm3ad/Desktop/rust/minigrep)
thread 'rustc' panicked at 'index out of bounds: the len is 73 but the index is 74', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/slice/mod.rs:2539:10                                    
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports                                                                                        

note: rustc 1.34.0 (91856ed52 2019-04-10) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `minigrep`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The backtrace:
```
stack backtrace:                                                                                                                                                                                          
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                                                                           
   1: std::sys_common::backtrace::_print                                                                                                                                                                  
   2: std::panicking::default_hook::{{closure}}                                                                                                                                                           
   3: std::panicking::default_hook                                                                                                                                                                        
   4: rustc::util::common::panic_hook                                                                                                                                                                     
   5: std::panicking::rust_panic_with_hook                                                                                                                                                                
   6: std::panicking::continue_panic_fmt                                                                                                                                                                  
   7: rust_begin_unwind                                                                                                                                                                                   
   8: core::panicking::panic_fmt                                                                                                                                                                          
   9: core::panicking::panic_bounds_check                                                                                                                                                                 
  10: <rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode                                      
  11: serialize::serialize::Decoder::read_struct                                                                                                                                                          
  12: serialize::serialize::Decoder::read_seq                                                                                                                                                             
  13: serialize::serialize::Decoder::read_struct                                                                                                                                                          
  14: serialize::serialize::Decoder::read_seq                                                                                                                                                             
  15: <rustc::mir::Mir<'tcx> as serialize::serialize::Decodable>::decode::{{closure}}                                                                                                                     
  16: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result                                                                                                                                 
  17: <rustc::ty::query::queries::optimized_mir<'tcx> as rustc::ty::query::config::QueryDescription<'tcx>>::try_load_from_disk                                                                            
  18: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                                                                                                            
  19: rustc_mir::monomorphize::collector::collect_items_rec                                                                                                                                               
  20: rustc_mir::monomorphize::collector::collect_items_rec                                                                                                                                               
  21: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}                                                                                                                           
  22: rustc::util::common::time                                                                                                                                                                           
  23: rustc_mir::monomorphize::collector::collect_crate_mono_items                                                                                                                                        
  24: rustc::util::common::time                                                                                                                                                                           
  25: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items                                                                                                                             
  26: rustc::ty::query::__query_compute::collect_and_partition_mono_items                                                                                                                                 
  27: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute                                              
  28: rustc::dep_graph::graph::DepGraph::with_task_impl                                                                                                                                                   
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query                                                                                                            
  30: rustc_codegen_ssa::base::codegen_crate                                                                                                                                                              
  31: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate                                                                                     
  32: rustc::util::common::time                                                                                                                                                                           
  33: rustc_driver::driver::phase_4_codegen                                                                                                                                                               
  34: rustc_driver::driver::compile_input::{{closure}}                                                                                                                                                    
  35: <std::thread::local::LocalKey<T>>::with                                                                                                                                                             
  36: rustc::ty::context::TyCtxt::create_and_enter                                                                                                                                                        
  37: rustc_driver::driver::compile_input                                                                                                                                                                 
  38: rustc_driver::run_compiler_with_pool                                                                                                                                                                
  39: <scoped_tls::ScopedKey<T>>::set                                                                                                                                                                     
  40: rustc_driver::run_compiler                                                                                                                                                                          
  41: syntax::with_globals                                                                                                                                                                                
  42: __rust_maybe_catch_panic                                                                                                                                                                            
  43: <F as alloc::boxed::FnBox<A>>::call_box                                                                                                                                                             
  44: std::sys::unix::thread::Thread::new::thread_start                                                                                                                                                   
  45: _pthread_body                                                                                                                                                                                       
  46: _pthread_start                                                                                                                                                                                      
query stack during panic:                                                                                                                                                                                 
#0 [optimized_mir] processing `tests::one_result::{{closure}}`                                                                                                                                           
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items                                                                                                                                   
end of query stack
```

### LINKED ISSUE #63161: ICE: index out of bounds: the len is 7 but the index is 7
I encountered an ICE today. Below you find the backtrace of running `cargo test`. I ran `cargo clean` afterwards and the ICE vanished, so it seams to be connected to incremental compilation.

```
thread 'rustc' panicked at 'index out of bounds: the len is 7 but the index is 7', /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2695:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  10: <rustc::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  11: serialize::serialize::Decoder::read_struct
  12: serialize::serialize::Decoder::read_seq
  13: serialize::serialize::Decoder::read_struct
  14: serialize::serialize::Decoder::read_seq
  15: <rustc::mir::Mir as serialize::serialize::Decodable>::decode::{{closure}}
  16: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  17: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  18: rustc_mir::monomorphize::collector::collect_items_rec
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  21: rustc::util::common::time
  22: rustc_mir::monomorphize::collector::collect_crate_mono_items
  23: rustc::util::common::time
  24: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  25: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_and_partition_mono_items>::compute
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  31: rustc::util::common::time
  32: rustc_interface::passes::start_codegen
  33: rustc::ty::context::tls::enter_global
  34: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  35: rustc_interface::passes::create_global_ctxt::{{closure}}
  36: rustc_interface::passes::BoxedGlobalCtxt::enter
  37: rustc_interface::queries::Query<T>::compute
  38: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  39: rustc_interface::interface::run_compiler_in_existing_thread_pool
  40: std::thread::local::LocalKey<T>::with
  41: scoped_tls::ScopedKey<T>::set
  42: syntax::with_globals
query stack during panic:
#0 [optimized_mir] processing `metadata::tests::sample_metadata_can_be_deserialized::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.36.0 (a53f9df32 2019-07-03) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
```

If required I can attach the full project including the build directories, as I zipped it after the ICE.

### LINKED ISSUE #73640: rustc bug  - index out of bounds
short summary of the bug:\
Unexpectedly the compiler return an error.\
I compile on WSL1 Debian on Win10.\
 \
I tried this code in this commit:\
`https://github.com/LucianoBestia/crates_io_database/commit/18b625fe64c4a54d871fc0f21ad6e6994dc11fab`\
\
code sample that causes the bug:\
I run this command:\
`$ clear; cargo test`\
\
I expected to see this happen:\
tests pass or fail.\
\
Instead, this happened: \
\
```
thread 'rustc' panicked at 'index out of bounds: the len is 559 but the index is 560', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2842:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0 (4fb7144ed 2020-04-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden
```
## Meta

`rustc --version --verbose`:\
\
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-unknown-linux-gnu
release: 1.43.0
LLVM version: 9.0
```

Backtrace:  
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1031
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  14: rust_begin_unwind
             at src/libstd/panicking.rs:378
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  16: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  17: <rustc::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
  18: <rustc::mir::SourceInfo as serialize::serialize::Decodable>::decode
  19: <rustc::mir::Statement as serialize::serialize::Decodable>::decode
  20: serialize::serialize::Decoder::read_seq
  21: <rustc::mir::BasicBlockData as serialize::serialize::Decodable>::decode
  22: serialize::serialize::Decoder::read_seq
  23: <rustc::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  24: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  26: rustc::ty::<impl rustc::ty::context::TyCtxt>::instance_mir
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_session::utils::<impl rustc_session::session::Session>::time
  30: rustc_mir::monomorphize::collector::collect_crate_mono_items
  31: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  32: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc_codegen_ssa::base::codegen_crate
  36: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  37: rustc_interface::passes::start_codegen
  38: rustc::ty::context::tls::enter_global
  39: rustc_interface::queries::Queries::ongoing_codegen
  40: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0 (4fb7144ed 2020-04-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `qvs20_table_mod::test::test_03_all_wrong_in_schema::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `crates_io_database`.
```

### LINKED ISSUE #73967: Panic index out of bounds running `cargo test` (unreproducable)
Follow the compiler's note I decided to unveil this issue 😄 

After first time I get the crash I ran `cargo test` 2 times and each time it was a crash but after that it went normally. I wasn't able to reproduce it.

I don't provide here the code since I consider it unreproducable.

### Meta

`RUST_BACKTRACE=1 cargo test--verbose:`

Backtrace:
```
thread 'rustc' panicked at 'index out of bounds: the len is 10 but the index is 10', src/librustc_middle/ty/query/on_disk_cache.rs:583:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIB..

note: rustc 1.44.0 (49cae5576 2020-06-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

warning: 1 warning emitted

error: could not compile `rstext`.

To learn more, run the command again with —verbose.

rust-lang/rust
github.com
 
thread 'rustc' panicked at 'index out of bounds: the len is 10 but the index is 10', src/librustc_middle/ty/query/on_disk_cache.rs:583:18
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:78
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
at src/libstd/sys_common/backtrace.rs:59
4: core::fmt::write
at src/libcore/fmt/mod.rs:1069
5: std::io::Write::write_fmt
at src/libstd/io/mod.rs:1504
6: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:62
7: std::sys_common::backtrace::print
at src/libstd/sys_common/backtrace.rs:49
8: std::panicking::default_hook::{{closure}}
at src/libstd/panicking.rs:198
9: std::panicking::default_hook
at src/libstd/panicking.rs:218
10: rustc_driver::report_ice
11: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:515
12: rust_begin_unwind
at src/libstd/panicking.rs:419
13: core::panicking::panic_fmt
at src/libcore/panicking.rs:111
14: core::panicking::panic_bounds_check
at src/libcore/panicking.rs:69
15: <rustc_middle::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span»::specialized_decode
16: <rustc_middle::mir::SourceInfo as serialize::serialize::Decodable>::decode
17: <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode
18: serialize::serialize::Decoder::read_seq
19: <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode
20: serialize::serialize::Decoder::read_seq
21: <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
22: rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
23: rustc_query_system::query::plumbing::get_query
24: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
25: rustc_mir::monomorphize::collector::collect_items_rec
26: rustc_mir::monomorphize::collector::collect_items_rec
27: rustc_mir::monomorphize::collector::collect_crate_mono_items
28: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
29: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
30: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
32: rustc_query_system::query::plumbing::get_query
33: rustc_codegen_ssa::base::codegen_crate
34: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
35: rustc_session::utils::<impl rustc_session::session::Session>::time
36: rustc_interface::passes::start_codegen
37: rustc_middle::ty::context::tls::enter_global
38: rustc_interface::queries::Queries::ongoing_codegen
39: rustc_interface::interface::run_compiler_in_existing_thread_pool
40: scoped_tls::ScopedKey<T>::set
41: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIB..

note: rustc 1.44.0 (49cae5576 2020-06-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `it_works::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
warning: 1 warning
 
emitted

error: could not compile `rstext`.

Caused by:
process didn't exit successfully: `rustc —crate-name test —edition=2018 tests/test.rs —error-format=json —json=diagnostic-rendered-ansi —emit=dep-info,link -C debuginfo=2 —test -C metadata=d3af2c6bb91399d2 -C extra-filename=-d3af2c6bb91399d2 —out-dir /home/zhiburt/proj/po-rs/target/debug/deps -C incremental=/home/zhiburt/proj/po-rs/target/debug/incremental -L dependency=/home/zhiburt/proj/po-rs/target/debug/deps —extern rstext=/home/zhiburt/proj/po-rs/target/debug/deps/librstext-96bd2310391f3aca.rlib` (exit code: 101)
```

### LINKED ISSUE #74890: Incremental build panic running `cargo test`
### Code

I don't think it's specific to any code per se, but I'm seeing this just after modifying a (now) 245 line file and hitting "run test" in vscode, maybe at about the same time I hotkey'd "save"? See below for more info.

This issue looks very similar to #73967 and maybe #73108. I suspect all three could be addressed by adopting a strategy as described in https://github.com/rust-lang/cargo/issues/6529.

### Meta

`rustc --version --verbose`:
```
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-apple-darwin
release: 1.44.1
LLVM version: 9.0
```

`rustup upgrade` did make the error "go away," I believe this is just because it invalidated the cache.

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 245 but the index is 246', src/librustc_middle/ty/query/on_disk_cache.rs:583:18
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: <rustc_middle::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
  11: <rustc_middle::mir::SourceInfo as serialize::serialize::Decodable>::decode
  12: <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode
  13: serialize::serialize::Decoder::read_seq
  14: <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode
  15: serialize::serialize::Decoder::read_seq
  16: <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  17: rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  18: rustc_query_system::query::plumbing::get_query
  19: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_mir::monomorphize::collector::collect_crate_mono_items
  23: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  24: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  25: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_query_system::query::plumbing::get_query
  28: rustc_codegen_ssa::base::codegen_crate
  29: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  30: rustc_session::utils::<impl rustc_session::session::Session>::time
  31: rustc_interface::passes::start_codegen
  32: rustc_middle::ty::context::tls::enter_global
  33: rustc_interface::queries::Queries::ongoing_codegen
  34: rustc_interface::interface::run_compiler_in_existing_thread_pool
  35: scoped_tls::ScopedKey<T>::set
  36: rustc_ast::attr::with_globals
```

</p>
</details>

### Reproducibility and Theory

So far I've reduced the state down to this project: [out-of-bounds.tar.gz](https://github.com/rust-lang/rust/files/4990994/out-of-bounds.tar.gz). `tar xvzf out-of-bounds.tar.gz; cd out-of-bounds; cargo test` has so far reproduced the error 100% of the time for me, but it's highly sensitive to the fingerprint mechanism so changes to anything in there produces a project that builds just fine.

Here's what I think is happening:

1. `cargo test` kicks off an incremental compile, and starts checking fingerprints. 
2. In order to build the dependency graph, it runs a "query" to determine 
3. As part of executing that query, it loads a cached incremental compilation unit for `tests/config.rs` that is out of sync with the current file (it refers to a point in time where the file was a few lines longer), which panics

Since this appears to be happening in the "check what work to do" phase, `rustc` never produces a new artifact that's in sync with the current state of the file, and either `cargo clean` or forcing a full rebuild is necessary to get back into sync.

The two questions I haven't gotten a good idea about are:

1. How does `rustc` determine the last incremental build is valid to run queries against? It seems that in this case, it should prefer to look through the new file than treat the last session as the file is indeed changed.
2. What did I do to get the compiler into this state in the first place? Some details that I suspect may be relevant:
    - I hit the "run test" inline helper in vscode, at about the same time as making other edits and re-saving the file
    - I have vscode configured to format on save, which does something to modify the file either just before or just after saving
    - I'm running on HFS on macOS, so my mtime timestamps are no more granular than 1 second apart

### LINKED ISSUE #75900: Index out of bounds in src/librustc_middle/ty/query/on_disk_cache.rs
```log
     Running `rustc --crate-name heph --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -Cembed-bitcode=no -C debuginfo=2 --test --cfg 'feature="default"' -C metadata=a6343bb67090b08a -C extra-filename=-a6343bb67090b08a --out-dir /Users/thomas/src/heph/target/debug/deps -C incremental=/Users/thomas/src/heph/target/debug/incremental -L dependency=/Users/thomas/src/heph/target/debug/deps --extern crossbeam_channel=/Users/thomas/src/heph/target/debug/deps/libcrossbeam_channel-9ecb709bf75fec26.rlib --extern erased_serde=/Users/thomas/src/heph/target/debug/deps/liberased_serde-244fa462d5a596a2.rlib --extern fnv=/Users/thomas/src/heph/target/debug/deps/libfnv-183fbcc1be843e1f.rlib --extern futures_core=/Users/thomas/src/heph/target/debug/deps/libfutures_core-49f8692ca16cde2d.rlib --extern futures_io=/Users/thomas/src/heph/target/debug/deps/libfutures_io-bfe7fe75d07baa83.rlib --extern futures_test=/Users/thomas/src/heph/target/debug/deps/libfutures_test-cbcebeaf29c3e8ec.rlib --extern futures_util=/Users/thomas/src/heph/target/debug/deps/libfutures_util-75d4027bb2349823.rlib --extern lazy_static=/Users/thomas/src/heph/target/debug/deps/liblazy_static-3ac5fd0e5fd029c7.rlib --extern log=/Users/thomas/src/heph/target/debug/deps/liblog-af57844bea540cbf.rlib --extern mio=/Users/thomas/src/heph/target/debug/deps/libmio-c4ff168f4dd8d66c.rlib --extern mio_pipe=/Users/thomas/src/heph/target/debug/deps/libmio_pipe-17e3a1716822c968.rlib --extern mio_signals=/Users/thomas/src/heph/target/debug/deps/libmio_signals-19fc00852f3546dd.rlib --extern num_cpus=/Users/thomas/src/heph/target/debug/deps/libnum_cpus-8173e222e24ff8b3.rlib --extern parking_lot=/Users/thomas/src/heph/target/debug/deps/libparking_lot-5be69b1765ee7c2a.rlib --extern rand=/Users/thomas/src/heph/target/debug/deps/librand-c15b19e5cece0db1.rlib --extern serde=/Users/thomas/src/heph/target/debug/deps/libserde-e81efd5064d96eed.rlib --extern serde_json=/Users/thomas/src/heph/target/debug/deps/libserde_json-8c8830ac969b650c.rlib --extern std_logger=/Users/thomas/src/heph/target/debug/deps/libstd_logger-5c8cd6509441c993.rlib`
thread 'rustc' panicked at 'index out of bounds: the len is 326 but the index is 326', src/librustc_middle/ty/query/on_disk_cache.rs:706:18
stack backtrace:
   0:        0x10d33b6d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfb2db7374ccd4d34
   1:        0x10d3a3260 - core::fmt::write::h7e381316a10f5e82
   2:        0x10d32cf7b - std::io::Write::write_fmt::h53862e22ed93af5e
   3:        0x10d33fff5 - std::panicking::default_hook::{{closure}}::h1a87f1c0565a051b
   4:        0x10d33fd37 - std::panicking::default_hook::he29ab2038604c86f
   5:        0x11174b088 - rustc_driver::report_ice::h20ae032f4c7fea6a
   6:        0x10d3406bd - std::panicking::rust_panic_with_hook::h9dab6d214201c5da
   7:        0x10d34022b - std::panicking::begin_panic_handler::{{closure}}::hf4bcec37fb7265f5
   8:        0x10d33bb18 - std::sys_common::backtrace::__rust_end_short_backtrace::h8c49942bd9c628f8
   9:        0x10d3401ea - _rust_begin_unwind
  10:        0x10d3c82cf - core::panicking::panic_fmt::hc5e2a0be1d842c94
  11:        0x10d3c8296 - core::panicking::panic_bounds_check::h40dfc66b75b71880
  12:        0x1158c674d - rustc_middle::ty::query::on_disk_cache::<impl rustc_serialize::serialize::Decodable<rustc_middle::ty::query::on_disk_cache::CacheDecoder> for rustc_span::span_encoding::Span>::decode::hd82b8a0f436ba20a
  13:        0x115a20f8c - rustc_middle::mir::_DERIVE_rustc_serialize_Decodable_D_FOR_SourceInfo::<impl rustc_serialize::serialize::Decodable<__D> for rustc_middle::mir::SourceInfo>::decode::h695d525836feb3e9
  14:        0x115a257ee - rustc_middle::mir::_DERIVE_rustc_serialize_Decodable_D_FOR_Statement::<impl rustc_serialize::serialize::Decodable<__D> for rustc_middle::mir::Statement>::decode::ha844e1be4cf6fa27
  15:        0x115adeb95 - rustc_serialize::serialize::Decoder::read_seq::h236c3e57c9d48fbd
  16:        0x115a23f54 - rustc_middle::mir::_DERIVE_rustc_serialize_Decodable_D_FOR_BasicBlockData::<impl rustc_serialize::serialize::Decodable<__D> for rustc_middle::mir::BasicBlockData>::decode::hc462cce188981f69
  17:        0x115ae28a5 - rustc_serialize::serialize::Decoder::read_seq::hb93a7c6c475425ee
  18:        0x115a1f7f6 - rustc_middle::mir::_DERIVE_rustc_serialize_Decodable_D_FOR_Body::<impl rustc_serialize::serialize::Decodable<__D> for rustc_middle::mir::Body>::decode::h7066ca664bc07799
  19:        0x115b0580a - rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result::h38b1e5e4611933a0
  20:        0x1157add6f - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::he0cb759a6ec37f41
  21:        0x115661f07 - rustc_query_system::query::plumbing::get_query_impl::h6d51c30fcf6c2fe6
  22:        0x115941f08 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir::h6938b2452d764ed0
  23:        0x1147281d0 - rustc_mir::monomorphize::collector::collect_neighbours::h490ca3a426f530e2
  24:        0x114722d10 - rustc_mir::monomorphize::collector::collect_items_rec::h9f585ad90473302c
  25:        0x114722efb - rustc_mir::monomorphize::collector::collect_items_rec::h9f585ad90473302c
  26:        0x114858d02 - rustc_session::utils::<impl rustc_session::session::Session>::time::h7554db3246046c47
  27:        0x1147217a8 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h290a58418b241f25
  28:        0x114a9d615 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h3046fc25ee2d49f1
  29:        0x111be9645 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h3b74d27acd4dd78b
  30:        0x111b05a37 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h829d453b57978aac
  31:        0x111b3b9b8 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h9716d60411728c54
  32:        0x111bbec97 - rustc_data_structures::stack::ensure_sufficient_stack::h7cf88ac4f4270b7f
  33:        0x111ac5ac3 - rustc_query_system::query::plumbing::get_query_impl::h7b9b33c7b223c5b6
  34:        0x111bed0aa - rustc_codegen_ssa::base::codegen_crate::h9dfb2043ce1aedbe
  35:        0x111be7e13 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::hca41b3ecfc779ff8
  36:        0x1119ed6b0 - rustc_interface::passes::QueryContext::enter::hb64df00a11c266b3
  37:        0x111a22620 - rustc_interface::queries::Queries::ongoing_codegen::he5b6ede59dc680b1
  38:        0x111767b89 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h5f267b10980944aa
  39:        0x1117104ee - rustc_span::with_source_map::h41746b5ad19cb6c9
  40:        0x111769561 - rustc_interface::interface::create_compiler_and_run::hae2e250f665904c6
  41:        0x11174e783 - scoped_tls::ScopedKey<T>::set::h6f614b62c5f7ab14
  42:        0x11175d1df - std::sys_common::backtrace::__rust_begin_short_backtrace::h3e44a6eb413894f0
  43:        0x1116fd45c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4585fc2219a571d0
  44:        0x10d34eddd - std::sys::unix::thread::Thread::new::thread_start::h39b071b0d2fb7aea
  45:     0x7fff6e5da109 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (5180f3da5 2020-08-23) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `test::test_size_of_actor::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `heph`.

Caused by:
  process didn't exit successfully: `rustc --crate-name heph --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -Cembed-bitcode=no -C debuginfo=2 --test --cfg 'feature="default"' -C metadata=a6343bb67090b08a -C extra-filename=-a6343bb67090b08a --out-dir /Users/thomas/src/heph/target/debug/deps -C incremental=/Users/thomas/src/heph/target/debug/incremental -L dependency=/Users/thomas/src/heph/target/debug/deps --extern crossbeam_channel=/Users/thomas/src/heph/target/debug/deps/libcrossbeam_channel-9ecb709bf75fec26.rlib --extern erased_serde=/Users/thomas/src/heph/target/debug/deps/liberased_serde-244fa462d5a596a2.rlib --extern fnv=/Users/thomas/src/heph/target/debug/deps/libfnv-183fbcc1be843e1f.rlib --extern futures_core=/Users/thomas/src/heph/target/debug/deps/libfutures_core-49f8692ca16cde2d.rlib --extern futures_io=/Users/thomas/src/heph/target/debug/deps/libfutures_io-bfe7fe75d07baa83.rlib --extern futures_test=/Users/thomas/src/heph/target/debug/deps/libfutures_test-cbcebeaf29c3e8ec.rlib --extern futures_util=/Users/thomas/src/heph/target/debug/deps/libfutures_util-75d4027bb2349823.rlib --extern lazy_static=/Users/thomas/src/heph/target/debug/deps/liblazy_static-3ac5fd0e5fd029c7.rlib --extern log=/Users/thomas/src/heph/target/debug/deps/liblog-af57844bea540cbf.rlib --extern mio=/Users/thomas/src/heph/target/debug/deps/libmio-c4ff168f4dd8d66c.rlib --extern mio_pipe=/Users/thomas/src/heph/target/debug/deps/libmio_pipe-17e3a1716822c968.rlib --extern mio_signals=/Users/thomas/src/heph/target/debug/deps/libmio_signals-19fc00852f3546dd.rlib --extern num_cpus=/Users/thomas/src/heph/target/debug/deps/libnum_cpus-8173e222e24ff8b3.rlib --extern parking_lot=/Users/thomas/src/heph/target/debug/deps/libparking_lot-5be69b1765ee7c2a.rlib --extern rand=/Users/thomas/src/heph/target/debug/deps/librand-c15b19e5cece0db1.rlib --extern serde=/Users/thomas/src/heph/target/debug/deps/libserde-e81efd5064d96eed.rlib --extern serde_json=/Users/thomas/src/heph/target/debug/deps/libserde_json-8c8830ac969b650c.rlib --extern std_logger=/Users/thomas/src/heph/target/debug/deps/libstd_logger-5c8cd6509441c993.rlib` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by tgnottingham**
Hash both the length and the end location (line/column) of a span. If we
hash only the length, for example, then two otherwise equal spans with
different end locations will have the same hash. This can cause a
problem during incremental compilation wherein a previous result for a
query that depends on the end location of a span will be incorrectly
reused when the end location of the span it depends on has changed. A
similar analysis applies if some query depends specifically on the
length of the span, but we only hash the end location. So hash both.

Fix #46744, fix #59954, fix #63161, fix #73640, fix #73967, fix #74890, fix #75900

---

See #74890 for a more in-depth analysis.

I haven't thought about what other problems this root cause could be responsible for. Please let me know if anything springs to mind. I believe the issue has existed since the inception of incremental compilation.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @Aaron1011

**Comment by tgnottingham** [comment]
It's a little unsettling at first that the hash should contain both the length and end line/column, because we can derive one from the other. It seems redundant. But that's only true when we have a source map from which to derive that info. A span in isolation is incomplete without both the length and the end location. That's my intuition, anyway.

But this raises the question of whether both should be _serialized_. Since we do have a source map when we create the in-memory spans, we don't actually need both pieces of information. Except that having both allows us to check that the information derived from the source map is consistent with what we read from disk. I'm fairly certain it's a bug if not. We probably shouldn't be reusing a span that is inconsistent with what we derive from the source map. So I've serialized both the end location and length in this PR, but I'm interested to hear what others think about the issue.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue 

Let's get some sense of how much of a performance hit it is to hash both -- if it's not, then I'm inclined to say we should :)

**Comment by tgnottingham** [comment]
@Mark-Simulacrum, I force pushed an update to the commit message. :) Does the perf run need to be requeued?

**Comment by Mark-Simulacrum** [comment]
Sort of. @rust-timer build a58d6a897ef3f0383e1fcc53cb87c6a2c8c64145

The try build completed, but bors currently loses track and doesn't print the "Try build finished" message if you force push.

**Comment by tgnottingham** [comment]
Okay, looks like there are some optimization opportunities here, which is great, because that's an area I'd like to work on. :) Looking into some small, local optimizations to start, just to see if we can get this PR performance-neutral.

**Comment by crlf0710** [comment]
@tgnottingham Ping from triage, what's the status of this?

**Comment by tgnottingham** [comment]
@crlf0710 I have a couple of performance improvements in the works. I can probably get them out within the week.

**Comment by tgnottingham** [comment]
I made some changes that should help with the performance hit of the additional line/column lookup. The last commit, which added a `span_data_to_lines_and_cols` function, was the most impactful based on my local tests. It's a modest improvement.

I'm making some changes on the hashing side, but they're significant enough that they should go into a separate PR. Hopefully that will come later this week.

**Comment by tgnottingham** [comment]
Hope to have the hash performance improvements out tomorrow or the next day.

**Comment by tgnottingham** [comment]
By the way, the hashing performance improvements are up for review in #77476.

**Comment by tgnottingham** [comment]
@nikomatsakis, yes.

**Comment by tgnottingham** [comment]
The perf impact of this individual change still looks bad, but I want to point out that the net effects of it plus the performance improvements I made in #77476 ([perf comparison](https://perf.rust-lang.org/compare.html?start=8c54cf67c1bdae93ecef9791dc07c0982bb76041&end=cd008531939631a26b5c0b5b63f06ffb0810fe7b)) are much better--neutral or an improvement on average I think. We don't see the improvement from the latter change having an additive effect here, since both the before and after commits in the perf comparison contain the change.

The fix in this PR is so simple that the change *itself* can't really be done much more efficiently (at least not obviously), and it's strictly more work. So offsetting changes like the one I linked to have to be done to address the performance impact. I think that the impact is pretty much addressed, though I'm glad to try to make offsetting improvements if people aren't happy with it so far. Note that as long as those are done in separate PRs (which I think is appropriate, as they're going to be basically unrelated to the original issue being fixed), the performance effect of this PR in isolation will look like a regression.

Either way, I intend to continue to work on performance issues, so hopefully this change will be more than offset by my efforts. :)

**Comment by Mark-Simulacrum** [comment]
Full builds are basically unaffected, and wall times do not see major impacts either. I think this is fine from a performance perspective: performance is important, but this is a correctness fix, and that can sometimes (of course) carry performance hazards with it.

That said, it looks like this carries a bunch of commits after the first one which (at first glance) look unrelated, perhaps they need to be rebased into a separate PR?

**Comment by tgnottingham** [comment]
The unrelated commits have been removed.

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+SRC=$(TMPDIR)/src
+INCR=$(TMPDIR)/incr
+
+all:
+	mkdir $(SRC)
+	mkdir $(INCR)
+	cp a.rs $(SRC)/main.rs
+	$(RUSTC) -C incremental=$(INCR) $(SRC)/main.rs
+	cp b.rs $(SRC)/main.rs
+	$(RUSTC) -C incremental=$(INCR) $(SRC)/main.rs
```
Comment (nikomatsakis) [inline src/test/run-make/incr-prev-body-beyond-eof/Makefile:16]: Hmm, we do have a specialized incremental compilation testing harness, but it relies on `#[cfg]` testing. I guess it may not be suitable for running this test. That said, I can't quite tell what would cause this test to fail -- did it used to ICE?

File: compiler/rustc_middle/src/ty/query/on_disk_cache.rs [hunk 2]
```diff
@@ -851,14 +854,25 @@ where
...
+        // We include both the end location and length, so that we can
+        // verify that the length we compute from the source map during
+        // deserialization is consistent with the serialized span.
+
         TAG_VALID_SPAN.encode(s)?;
         source_file_index.encode(s)?;
         line_lo.encode(s)?;
         col_lo.encode(s)?;
+        line_hi.encode(s)?;
+        col_hi.encode(s)?;
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/ty/query/on_disk_cache.rs:875]: If this is purely for assertion purposes, is it worth doing? Do we know if this change has any performance impact on its own?

**Review by nikomatsakis — COMMENTED** [review]
Code looks nice. Good comments! I left a few questions.

File: compiler/rustc_middle/src/ty/query/on_disk_cache.rs (hunk 2 above)
Comment (tgnottingham) [reply compiler/rustc_middle/src/ty/query/on_disk_cache.rs:875]: I can't say whether or not it's worth it, but it does have a performance impact. It accounts for most of the `tuple-stress` and `ucd` benchmark regressions. Here is the effect of removing the changes to `on_disk_cache.rs` (all of which are only necessary for the assert):

image

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile (hunk 1 above)
Comment (tgnottingham) [reply src/test/run-make/incr-prev-body-beyond-eof/Makefile:16]: Yes, just double-checked that this ICEs without the changes in this PR.

I was kind of leaning on reviewers to be able to tell me if there's a better way of doing this. :) The important thing is that the span of interest is the same in all ways except end line/col in both compilations (i.e. file name, start line/col, and length). I'm not sure that's possible to do with the other testing methods, but that's mostly on account of being new. :)

File: compiler/rustc_middle/src/ty/query/on_disk_cache.rs (hunk 2 above)
Comment (tgnottingham) [reply compiler/rustc_middle/src/ty/query/on_disk_cache.rs:875]: Given the not insignificant impact of a single assert on at least one real-world crate (ucd), I'll go ahead and remove it and the extra encoding/decoding.

Comment (nikomatsakis) [reply compiler/rustc_middle/src/ty/query/on_disk_cache.rs]: Yeah, I think that's the right call.

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile (hunk 1 above)
Comment (nikomatsakis) [reply src/test/run-make/incr-prev-body-beyond-eof/Makefile:16]: Given that the start line/column must match i'm not sure if there would be a way to use the other testing harness.

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile [hunk 3]
```diff
@@ -0,0 +1,16 @@
+-include ../../run-make-fulldeps/tools.mk
+
+# Tests that we don't ICE during incremental compilation after modifying a
+# function span such that its previous end line exceeds the number of lines
+# in the new file, but its start line/column and length remain the same.
+
+SRC=$(TMPDIR)/src
+INCR=$(TMPDIR)/incr
```
Comment (nikomatsakis) [inline src/test/run-make/incr-prev-body-beyond-eof/Makefile:8]: I'm not that familiar with the run-make harness -- @Mark-Simulacrum do you know by any chance if TMPDIR is specific to this *test*?

**Comment by tgnottingham** [comment]
CI failed on powerpc build due to linker segfaulting. :confused:

**Comment by nikomatsakis** [comment]
@tgnottingham hmm that might be something that just needs to be retried, I'm not sure... maybe somebody from @rust-lang/infra has an idea if that's a recurring problem?

**Comment by kennytm** [comment]
@bors r-

the new test failed on `arm-none-eabi-gcc` due to linker flag, looks legit

https://github.com/rust-lang-ci/rust/runs/1368962233

```
failures:

---- [run-make] run-make/incr-prev-body-beyond-eof stdout ----

error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
mkdir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/src
mkdir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/incr
cp a.rs /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/src/main.rs
LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof  -Clinker='arm-none-eabi-gcc' -C incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/incr /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/src/main.rs
Makefile:11: recipe for target 'all' failed

------------------------------------------
stderr:
------------------------------------------
error: linking with `arm-none-eabi-gcc` failed: exit code: 1
  |
  = note: "arm-none-eabi-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.24tiyo9f8xdudm29.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.2vuk8g9ve0w04u8b.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.3e2qsm1x7ht4xi2a.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.432o4h71aelwht4j.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.5aumkhj7rs1kp4mu.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.8urjmv6unxzieb8.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.j5nriyc7t40nfd8.rcgu.o" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof/main.4s37gsrti678ik8u.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/incr-prev-body-beyond-eof/incr-prev-body-beyond-eof" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-cd8d1606f661f6b0.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-448643d99e633b5d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-c7c3d631a525883a.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-d7659a11bb201e01.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-3582800a023674d1.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-56ae8ed396eb3f30.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-b13a322082c79e4f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1d4694108f8cb543.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-79eaa6e630880f50.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-0df1a4ec96f80cf7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bba9b0f0f4d77257.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-f848f9c987265235.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0d5ea4f2d39b8e27.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c22053fa5fc00a3b.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-c52e5d6301e1bd59.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2675a9a46b5cec89.rlib" "-Wl,--end-group" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-6e3d052afeb9f711.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: arm-none-eabi-gcc: error: unrecognized command line option '-m64'
          

error: aborting due to previous error

make: *** [all] Error 1
```

File: src/test/run-make/incr-prev-body-beyond-eof/a.rs [hunk 4]
```diff
@@ -0,0 +1,14 @@
+fn main() {
+    // foo must be used.
+    foo();
+}
+
+fn foo() {
+    // foo's span in a.rs and b.rs must be identical
```
Comment (Aaron1011) [inline src/test/run-make/incr-prev-body-beyond-eof/a.rs:7]: Could you mention the fact that the empty lines in this function are necessary? I'm worried that they'll get accidentally removed in the future.

Comment (tgnottingham) [reply src/test/run-make/incr-prev-body-beyond-eof/a.rs:7]: Good idea, will do.

**Comment by tgnottingham** [comment]
@jonas-schievink, we're getting multiple linker errors from a new run-make test I added. I saw that you were responsible for this line in another run-make file: `# ignore-32bit wrong/no cross compiler and sometimes we pass wrong gcc args (-m64)`, which looks related to one of the errors we're seeing (`unrecognized command line option '-m64'`).

Do you happen to know what I need to change in my run-make test to make it pass CI? I didn't think I was doing anything novel.

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile [hunk 5]
```diff
@@ -0,0 +1,16 @@
+-include ../../run-make-fulldeps/tools.mk
+
```
Comment (jonas-schievink) [inline src/test/run-make/incr-prev-body-beyond-eof/Makefile:2]: This should get you past the CI error

```suggestion
# ignore-32bit
```

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile [hunk 6]
```diff
@@ -1,5 +1,5 @@
 -include ../../run-make-fulldeps/tools.mk
-
+# ignore-32bit
```
Comment (nikomatsakis) [inline src/test/run-make/incr-prev-body-beyond-eof/Makefile:2]: Can we annotate this with a FIXME or link to an issue?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/test/run-make/incr-prev-body-beyond-eof/Makefile (hunk 6 above)
Comment (tgnottingham) [reply src/test/run-make/incr-prev-body-beyond-eof/Makefile:2]: Yes, I was thinking the same. I'm not seeing an existing issue, but I can create one. @jonas-schievink, please let me know if you know of an existing issue for this.

Comment (jonas-schievink) [reply src/test/run-make/incr-prev-body-beyond-eof/Makefile:2]: No, I didn't open one
