### PR TITLE
Init `self_decl` with a correct visibility

### LINKED ISSUE #154295: [ICE]: `reachable Public > nominal Restricted`
auto-reduced (treereduce-rust):
````rust
mod foo {

    pub use self as ops;
}

pub use foo::*;

pub fn main() {}

````

original:
````rust
//@ check-pass

mod foo {
    pub use crate::bar::*;
    pub use self as ops;
}

mod bar {
    pub use crate::foo::*;
}

pub use foo::*;
pub use baz::*;
mod baz {
    pub use super::*;
}

pub fn main() {}

````

Version information
````
rustc 1.96.0-nightly (212b0d480 2026-03-24)
binary: rustc
commit-hash: 212b0d480f337082bbe1132d2b62be20e7e61f8a
commit-date: 2026-03-24
host: x86_64-unknown-linux-gnu
release: 1.96.0-nightly
LLVM version: 22.1.0

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/middle/privacy.rs#L181-L193

Command:
`/home/matthias/.rustup/toolchains/alt-master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: internal compiler error: /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/middle/privacy.rs:187:21: DefId(0:3 ~ mvce[79fc]::foo): reachable Public > nominal Restricted(DefId(0:0 ~ mvce[79fc]))
 --> /tmp/icemaker_global_tempdir.sh6cVLdUc7z0/rustc_testrunner_tmpdir_reporting.99PWnO05RUCK/mvce.rs:1:1
  |
1 | mod foo {
  | ^^^^^^^


thread 'rustc' (2834078) panicked at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/middle/privacy.rs:187:21:
Box<dyn Any>
stack backtrace:
   0:     0x7f0ddcb3c630 - std[498aa0c2c043024a]::backtrace_rs::backtrace::libunwind::trace
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x7f0ddcb3c630 - std[498aa0c2c043024a]::backtrace_rs::backtrace::trace_unsynchronized::<std[498aa0c2c043024a]::sys::backtrace::_print_fmt::{closure#1}>
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x7f0ddcb3c630 - std[498aa0c2c043024a]::sys::backtrace::_print_fmt
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/backtrace.rs:74:9
   3:     0x7f0ddcb3c630 - <<std[498aa0c2c043024a]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[23b411eca7e13423]::fmt::Display>::fmt
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/backtrace.rs:44:26
   4:     0x7f0dd80e343e - <core[23b411eca7e13423]::fmt::rt::Argument>::fmt
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/fmt/rt.rs:152:76
   5:     0x7f0dd80e343e - core[23b411eca7e13423]::fmt::write
   6:     0x7f0ddcb5475c - std[498aa0c2c043024a]::io::default_write_fmt::<std[498aa0c2c043024a]::sys::stdio::unix::Stderr>
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/io/mod.rs:639:11
   7:     0x7f0ddcb5475c - <std[498aa0c2c043024a]::sys::stdio::unix::Stderr as std[498aa0c2c043024a]::io::Write>::write_fmt
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/io/mod.rs:1994:13
   8:     0x7f0ddcb01106 - <std[498aa0c2c043024a]::sys::backtrace::BacktraceLock>::print
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/backtrace.rs:47:9
   9:     0x7f0ddcb01106 - std[498aa0c2c043024a]::panicking::default_hook::{closure#0}
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:292:27
  10:     0x7f0ddcb2b321 - std[498aa0c2c043024a]::panicking::default_hook
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:319:9
  11:     0x7f0dd95cfc77 - <alloc[59d64f87cfa2c04d]::boxed::Box<dyn for<'a, 'b> core[23b411eca7e13423]::ops::function::Fn<(&'a std[498aa0c2c043024a]::panic::PanicHookInfo<'b>,), Output = ()> + core[23b411eca7e13423]::marker::Sync + core[23b411eca7e13423]::marker::Send> as core[23b411eca7e13423]::ops::function::Fn<(&std[498aa0c2c043024a]::panic::PanicHookInfo,)>>::call
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/alloc/src/boxed.rs:2254:9
  12:     0x7f0dd95cfc77 - rustc_driver_impl[fe3aa65ad3b0ada3]::install_ice_hook::{closure#1}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_driver_impl/src/lib.rs:1483:17
  13:     0x7f0dd95cfc77 - <alloc[59d64f87cfa2c04d]::boxed::Box<rustc_driver_impl[fe3aa65ad3b0ada3]::install_ice_hook::{closure#1}> as core[23b411eca7e13423]::ops::function::Fn<(&dyn for<'a, 'b> core[23b411eca7e13423]::ops::function::Fn<(&'a std[498aa0c2c043024a]::panic::PanicHookInfo<'b>,), Output = ()> + core[23b411eca7e13423]::marker::Sync + core[23b411eca7e13423]::marker::Send, &std[498aa0c2c043024a]::panic::PanicHookInfo)>>::call
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/alloc/src/boxed.rs:2254:9
  14:     0x7f0dd95cfc77 - std[498aa0c2c043024a]::panicking::update_hook::<alloc[59d64f87cfa2c04d]::boxed::Box<rustc_driver_impl[fe3aa65ad3b0ada3]::install_ice_hook::{closure#1}>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:235:47
  15:     0x7f0ddcb2b6ba - <alloc[59d64f87cfa2c04d]::boxed::Box<dyn for<'a, 'b> core[23b411eca7e13423]::ops::function::Fn<(&'a std[498aa0c2c043024a]::panic::PanicHookInfo<'b>,), Output = ()> + core[23b411eca7e13423]::marker::Sync + core[23b411eca7e13423]::marker::Send> as core[23b411eca7e13423]::ops::function::Fn<(&std[498aa0c2c043024a]::panic::PanicHookInfo,)>>::call
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/alloc/src/boxed.rs:2254:9
  16:     0x7f0ddcb2b6ba - std[498aa0c2c043024a]::panicking::panic_with_hook
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:833:13
  17:     0x7f0dd966aca3 - std[498aa0c2c043024a]::panicking::begin_panic::<rustc_errors[a922c803b2728478]::ExplicitBug>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:762:9
  18:     0x7f0dd96593d6 - std[498aa0c2c043024a]::sys::backtrace::__rust_end_short_backtrace::<std[498aa0c2c043024a]::panicking::begin_panic<rustc_errors[a922c803b2728478]::ExplicitBug>::{closure#0}, !>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/backtrace.rs:182:18
  19:     0x7f0dd96593c7 - std[498aa0c2c043024a]::panicking::begin_panic::<rustc_errors[a922c803b2728478]::ExplicitBug>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:761:5
  20:     0x7f0dd9698f11 - std[498aa0c2c043024a]::panic::panic_any::<rustc_errors[a922c803b2728478]::ExplicitBug>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panic.rs:260:5
  21:     0x7f0dd9698f11 - <rustc_errors[a922c803b2728478]::diagnostic::BugAbort as rustc_errors[a922c803b2728478]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_errors/src/diagnostic.rs:58:9
  22:     0x7f0ddaa92cfc - <rustc_errors[a922c803b2728478]::diagnostic::Diag<rustc_errors[a922c803b2728478]::diagnostic::BugAbort>>::emit
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_errors/src/diagnostic.rs:1283:9
  23:     0x7f0ddaa92cfc - <rustc_errors[a922c803b2728478]::DiagCtxtHandle>::span_bug::<rustc_span[3548e6eaad84bf35]::span_encoding::Span, alloc[59d64f87cfa2c04d]::string::String>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_errors/src/lib.rs:941:48
  24:     0x7f0ddab4384b - rustc_middle[bced035f372d0cd]::util::bug::opt_span_bug_fmt::<rustc_span[3548e6eaad84bf35]::span_encoding::Span>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/util/bug.rs:38:54
  25:     0x7f0ddab438d8 - rustc_middle[bced035f372d0cd]::ty::context::tls::with_opt::<rustc_middle[bced035f372d0cd]::util::bug::opt_span_bug_fmt<rustc_span[3548e6eaad84bf35]::span_encoding::Span>::{closure#0}, !>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:109:23
  26:     0x7f0ddaaf53f6 - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context_opt::<rustc_middle[bced035f372d0cd]::ty::context::tls::with_opt<rustc_middle[bced035f372d0cd]::util::bug::opt_span_bug_fmt<rustc_span[3548e6eaad84bf35]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  27:     0x7f0ddaaf398a - rustc_middle[bced035f372d0cd]::ty::context::tls::with_opt::<rustc_middle[bced035f372d0cd]::util::bug::opt_span_bug_fmt<rustc_span[3548e6eaad84bf35]::span_encoding::Span>::{closure#0}, !>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:107:5
  28:     0x7f0ddaaf398a - rustc_middle[bced035f372d0cd]::util::bug::opt_span_bug_fmt::<rustc_span[3548e6eaad84bf35]::span_encoding::Span>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/util/bug.rs:33:5
  29:     0x7f0ddaaf398a - rustc_middle[bced035f372d0cd]::util::bug::span_bug_fmt::<rustc_span[3548e6eaad84bf35]::span_encoding::Span>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/util/bug.rs:24:5
  30:     0x7f0ddab793dc - <rustc_middle[bced035f372d0cd]::middle::privacy::EffectiveVisibilities>::check_invariants
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/macros.rs:34:9
  31:     0x7f0ddb6f73f9 - rustc_privacy[7dca37ca7e82eb98]::effective_visibilities
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_privacy/src/lib.rs:1796:36
  32:     0x7f0ddbb45da7 - rustc_query_impl[fb98859da66919f9]::query_impl::effective_visibilities::invoke_provider_fn::__rust_begin_short_backtrace
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/query_impl.rs:116:46
  33:     0x7f0ddb9466cd - rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:395:59
  34:     0x7f0ddb9466cd - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  35:     0x7f0ddb9466cd - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::try_with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:462:12
  36:     0x7f0ddb9466cd - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:426:20
  37:     0x7f0ddb9466cd - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:53:9
  38:     0x7f0ddb9466cd - rustc_query_impl[fb98859da66919f9]::plumbing::start_query::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/plumbing.rs:78:9
  39:     0x7f0ddb9466cd - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context::<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:86:36
  40:     0x7f0ddb9466cd - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context_opt::<rustc_middle[bced035f372d0cd]::ty::context::tls::with_context<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:75:18
  41:     0x7f0ddb9466cd - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context::<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:86:5
  42:     0x7f0ddb9466cd - rustc_query_impl[fb98859da66919f9]::plumbing::start_query::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/plumbing.rs:65:5
  43:     0x7f0ddb9466cd - rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:395:17
  44:     0x7f0ddb9466cd - rustc_query_impl[fb98859da66919f9]::execution::try_execute_query::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>, false>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:303:17
  45:     0x7f0ddbb4615e - rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:596:32
  46:     0x7f0ddbb4615e - stacker[6504f60033954b3a]::maybe_grow::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  47:     0x7f0ddbb4615e - rustc_data_structures[9eb81cc78dd7dae1]::stack::ensure_sufficient_stack::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/stack.rs:21:5
  48:     0x7f0ddbb4615e - rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:596:5
  49:     0x7f0ddbb4615e - rustc_query_impl[fb98859da66919f9]::query_impl::effective_visibilities::execute_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/query_impl.rs:80:30
  50:     0x7f0dda498a83 - rustc_middle[bced035f372d0cd]::query::inner::query_ensure_ok_or_done::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 8usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/query/inner.rs:63:13
  51:     0x7f0dda498a83 - <rustc_middle[bced035f372d0cd]::query::plumbing::TyCtxtEnsureOk>::effective_visibilities
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/query/plumbing.rs:581:21
  52:     0x7f0dda498a83 - rustc_interface[3720df91926495db]::passes::analysis::{closure#0}::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/passes.rs:1148:33
  53:     0x7f0dd953c5af - <&mut dyn core[23b411eca7e13423]::ops::function::FnMut<(), Output = ()> + rustc_data_structures[9eb81cc78dd7dae1]::marker::DynSend as core[23b411eca7e13423]::ops::function::FnMut<()>>::call_mut
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/ops/function.rs:298:21
  54:     0x7f0dd953c5af - rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/sync/parallel.rs:99:30
  55:     0x7f0dd953c5af - <core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}> as core[23b411eca7e13423]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/panic/unwind_safe.rs:275:9
  56:     0x7f0dd953c5af - std[498aa0c2c043024a]::panicking::catch_unwind::do_call::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:581:40
  57:     0x7f0dd953c5af - std[498aa0c2c043024a]::panicking::catch_unwind::<(), core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:544:19
  58:     0x7f0dd953c5af - std[498aa0c2c043024a]::panic::catch_unwind::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panic.rs:359:14
  59:     0x7f0dd953c5af - <rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}::{closure#1}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/sync/parallel.rs:23:9
  60:     0x7f0dd953c5af - rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/sync/parallel.rs:99:23
  61:     0x7f0dd953c5af - rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::parallel_guard::<(), rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/sync/parallel.rs:39:15
  62:     0x7f0dd953c5af - rustc_data_structures[9eb81cc78dd7dae1]::sync::parallel::par_fns
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/sync/parallel.rs:75:5
  63:     0x7f0dda5067a8 - rustc_interface[3720df91926495db]::passes::analysis::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/passes.rs:1146:9
  64:     0x7f0dda5067a8 - <rustc_data_structures[9eb81cc78dd7dae1]::profiling::VerboseTimingGuard>::run::<(), rustc_interface[3720df91926495db]::passes::analysis::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/profiling.rs:845:9
  65:     0x7f0dda5067a8 - <rustc_session[31cf8ef93cf698c1]::session::Session>::time::<(), rustc_interface[3720df91926495db]::passes::analysis::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_session/src/utils.rs:17:50
  66:     0x7f0dda5067a8 - rustc_interface[3720df91926495db]::passes::analysis
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/passes.rs:1145:10
  67:     0x7f0ddbb8edc7 - rustc_query_impl[fb98859da66919f9]::query_impl::analysis::invoke_provider_fn::__rust_begin_short_backtrace
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/query_impl.rs:116:46
  68:     0x7f0ddb938774 - rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:395:59
  69:     0x7f0ddb938774 - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  70:     0x7f0ddb938774 - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::try_with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:462:12
  71:     0x7f0ddb938774 - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:426:20
  72:     0x7f0ddb938774 - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:53:9
  73:     0x7f0ddb938774 - rustc_query_impl[fb98859da66919f9]::plumbing::start_query::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/plumbing.rs:78:9
  74:     0x7f0ddb938774 - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context::<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:86:36
  75:     0x7f0ddb938774 - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context_opt::<rustc_middle[bced035f372d0cd]::ty::context::tls::with_context<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:75:18
  76:     0x7f0ddb938774 - rustc_middle[bced035f372d0cd]::ty::context::tls::with_context::<rustc_query_impl[fb98859da66919f9]::plumbing::start_query<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>::{closure#0}, rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:86:5
  77:     0x7f0ddb938774 - rustc_query_impl[fb98859da66919f9]::plumbing::start_query::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/plumbing.rs:65:5
  78:     0x7f0ddb938774 - rustc_query_impl[fb98859da66919f9]::execution::execute_job_non_incr::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:395:17
  79:     0x7f0ddb938774 - rustc_query_impl[fb98859da66919f9]::execution::try_execute_query::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>, false>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:303:17
  80:     0x7f0ddbb8f161 - rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:596:32
  81:     0x7f0ddbb8f161 - stacker[6504f60033954b3a]::maybe_grow::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rust/deps/stacker-0.1.21/src/lib.rs:57:9
  82:     0x7f0ddbb8f161 - rustc_data_structures[9eb81cc78dd7dae1]::stack::ensure_sufficient_stack::<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>, rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_data_structures/src/stack.rs:21:5
  83:     0x7f0ddbb8f161 - rustc_query_impl[fb98859da66919f9]::execution::execute_query_non_incr_inner::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/execution.rs:596:5
  84:     0x7f0ddbb8f161 - rustc_query_impl[fb98859da66919f9]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_query_impl/src/query_impl.rs:80:30
  85:     0x7f0dd95b2dbf - rustc_middle[bced035f372d0cd]::query::inner::query_ensure_ok_or_done::<rustc_middle[bced035f372d0cd]::query::caches::SingleCache<rustc_middle[bced035f372d0cd]::query::erase::ErasedData<[u8; 0usize]>>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/query/inner.rs:63:13
  86:     0x7f0dd95b2dbf - <rustc_middle[bced035f372d0cd]::query::plumbing::TyCtxtEnsureOk>::analysis
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/query/plumbing.rs:581:21
  87:     0x7f0dd95b2dbf - rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_driver_impl/src/lib.rs:325:29
  88:     0x7f0dd95b2dbf - rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt::<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/passes.rs:1019:23
  89:     0x7f0dd95b2dbf - <rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter::<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#1}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context.rs:863:37
  90:     0x7f0dd95b2dbf - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<<rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#1}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:56:9
  91:     0x7f0dd95b2dbf - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::try_with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<<rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#1}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#0}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:462:12
  92:     0x7f0dd95b2dbf - <std[498aa0c2c043024a]::thread::local::LocalKey<core[23b411eca7e13423]::cell::Cell<*const ()>>>::with::<rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context<<rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#1}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#0}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/local.rs:426:20
  93:     0x7f0dd95b2dbf - rustc_middle[bced035f372d0cd]::ty::context::tls::enter_context::<<rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>::{closure#1}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context/tls.rs:53:9
  94:     0x7f0dd95b2dbf - <rustc_middle[bced035f372d0cd]::ty::context::GlobalCtxt>::enter::<rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}, core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context.rs:863:9
  95:     0x7f0dd95b2dbf - <rustc_middle[bced035f372d0cd]::ty::context::TyCtxt>::create_global_ctxt::<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>::{closure#2}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_middle/src/ty/context.rs:1072:13
  96:     0x7f0dd95b2dbf - rustc_interface[3720df91926495db]::passes::create_and_enter_global_ctxt::<core[23b411eca7e13423]::option::Option<rustc_interface[3720df91926495db]::queries::Linker>, rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}::{closure#2}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/passes.rs:986:5
  97:     0x7f0dd95ce9f5 - rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_driver_impl/src/lib.rs:298:22
  98:     0x7f0dd95ce9f5 - rustc_interface[3720df91926495db]::interface::run_compiler::<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/interface.rs:500:80
  99:     0x7f0dd95ce9f5 - <core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}::{closure#0}> as core[23b411eca7e13423]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/panic/unwind_safe.rs:275:9
 100:     0x7f0dd95ce9f5 - std[498aa0c2c043024a]::panicking::catch_unwind::do_call::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:581:40
 101:     0x7f0dd95ce9f5 - std[498aa0c2c043024a]::panicking::catch_unwind::<(), core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:544:19
 102:     0x7f0dd95ce9f5 - std[498aa0c2c043024a]::panic::catch_unwind::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panic.rs:359:14
 103:     0x7f0dd95ce9f5 - rustc_interface[3720df91926495db]::interface::run_compiler::<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/interface.rs:500:23
 104:     0x7f0dd95be195 - rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals::<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/util.rs:203:17
 105:     0x7f0dd95be195 - rustc_interface[3720df91926495db]::util::run_in_thread_with_globals::<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/util.rs:159:24
 106:     0x7f0dd95be195 - <scoped_tls[c00c851a8a604440]::ScopedKey<rustc_span[3548e6eaad84bf35]::SessionGlobals>>::set::<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}, ()>
                               at /rust/deps/scoped-tls-1.0.1/src/lib.rs:137:9
 107:     0x7f0dd95be195 - rustc_span[3548e6eaad84bf35]::create_session_globals_then::<(), rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#0}>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_span/src/lib.rs:153:21
 108:     0x7f0dd95be195 - rustc_interface[3720df91926495db]::util::run_in_thread_with_globals::<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/compiler/rustc_interface/src/util.rs:155:17
 109:     0x7f0dd95be195 - std[498aa0c2c043024a]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/backtrace.rs:166:18
 110:     0x7f0dd95d5613 - std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked::<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/lifecycle.rs:91:13
 111:     0x7f0dd95d5613 - <core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}> as core[23b411eca7e13423]::ops::function::FnOnce<()>>::call_once
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/panic/unwind_safe.rs:275:9
 112:     0x7f0dd95d5613 - std[498aa0c2c043024a]::panicking::catch_unwind::do_call::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:581:40
 113:     0x7f0dd95d5613 - std[498aa0c2c043024a]::panicking::catch_unwind::<(), core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panicking.rs:544:19
 114:     0x7f0dd95d5613 - std[498aa0c2c043024a]::panic::catch_unwind::<core[23b411eca7e13423]::panic::unwind_safe::AssertUnwindSafe<std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/panic.rs:359:14
 115:     0x7f0dd95d5613 - std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked::<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/thread/lifecycle.rs:89:26
 116:     0x7f0dd95d5613 - <std[498aa0c2c043024a]::thread::lifecycle::spawn_unchecked<rustc_interface[3720df91926495db]::util::run_in_thread_with_globals<rustc_interface[3720df91926495db]::util::run_in_thread_pool_with_globals<rustc_interface[3720df91926495db]::interface::run_compiler<(), rustc_driver_impl[fe3aa65ad3b0ada3]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[23b411eca7e13423]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc-dev/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/core/src/ops/function.rs:250:5
 117:     0x7f0ddcb394bf - <alloc[59d64f87cfa2c04d]::boxed::Box<dyn core[23b411eca7e13423]::ops::function::FnOnce<(), Output = ()> + core[23b411eca7e13423]::marker::Send> as core[23b411eca7e13423]::ops::function::FnOnce<()>>::call_once
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/alloc/src/boxed.rs:2240:9
 118:     0x7f0ddcb394bf - <std[498aa0c2c043024a]::sys::thread::unix::Thread>::new::thread_start
                               at /rustc/212b0d480f337082bbe1132d2b62be20e7e61f8a/library/std/src/sys/thread/unix.rs:118:17
 119:     0x7f0dd68a597a - <unknown>
 120:     0x7f0dd69292bc - <unknown>
 121:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.96.0-nightly (212b0d480 2026-03-24) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [effective_visibilities] checking effective visibilities
#1 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 1 previous error


```

</p>
</details>

### PR DESCRIPTION
**Pull request by mu001999**
Fixes rust-lang/rust#154295

r? petrochenkov

### CODE REVIEW

File: tests/ui/use/pub-use-self-super-crate.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+mod foo {
+    pub mod bar {
+        pub use super as parent;
+        //~^ ERROR `super` is only public within the crate, and cannot be re-exported outside
+        pub use self::super as parent2;
+        //~^ ERROR `super` is only public within the crate, and cannot be re-exported outside
+        pub use super::{self as parent3};
+        //~^ ERROR `super` is only public within the crate, and cannot be re-exported outside
+        pub use self::{super as parent4};
+        //~^ ERROR `super` is only public within the crate, and cannot be re-exported outside
```
Comment (petrochenkov) [inline tests/ui/use/pub-use-self-super-crate.rs:13]: `self_decl` is used for `crate` too, so it would be good to test it as well.
(Also the test cases can probably be merged into a single file.)

File: compiler/rustc_resolve/src/lib.rs [hunk 2]
```diff
@@ -1749,7 +1756,13 @@ impl<'ra, 'tcx> Resolver<'ra, 'tcx> {
         span: Span,
         no_implicit_prelude: bool,
     ) -> Module<'ra> {
-        let module = self.arenas.new_module(parent, kind, expn_id, span, no_implicit_prelude);
+        let vis = match kind {
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/lib.rs]:
```suggestion
        let vis = kind.opt_def_id().map_or(Visibility::Public, |def_id| self.tcx.visibility(def_id));
```

The `opt_def_id` method can be moved from `Module` to `ModuleKind`.
