### PR TITLE
NLL: User type annotations refactor, associated constant patterns and ref bindings.

### LINKED ISSUE #54943: NLL doesn't check that user type annotations are well-formed in unreachable code
#54942 checks well-formedness in the general case, but unreachable code is deleted before NLL can check it. 

For example, [this test](https://github.com/rust-lang/rust/blob/0e07c4281c343e9e15a0a8fca79538ad1a8eb513/src/test/ui/regions/regions-outlives-projection-container-wc.rs) still compiles with NLL enabled.

### LINKED ISSUE #55401: handle user type annotations in NLL for `ref` bindings
spun off from #47184 and #54570 : 

Most of the necessary support for checking lifetime constraints introduced via complex patterns has been added. But one exceptional case which has not been properly dealt with is `ref` bindings.

If you look here the code explicitly says "ignore `pattern_user_ty` for now."

https://github.com/rust-lang/rust/blob/3e6f30ec3e6bda159063fcd126dcb14725fef92d/src/librustc_mir/build/matches/mod.rs#L518-L526

(I fixed a lot of instances of FIXME(#47184) in PR #55274, but I punted on this one.)

### LINKED ISSUE #55511: nll: respect user type annotations with constants in patterns
Breaking off from #47184 -- we need to respect user type annotations in patterns. Here are some examples:

Compiles without NLL ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=8a181a6e956584682108e19b61a4077c)):

```rust
trait Foo<'a> {
    const C: &'a u32;
}

impl<'a, T> Foo<'a> for T {
    const C: &'a u32 = &22;
}

fn foo() {
    let a = 22;
    match &a {
        <() as Foo<'static>>::C => { }
        &_ => { }
    }
}

fn main() {
}
```

Errors without NLL ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=819e4fbf897e343be51f6847e140c6ce)):

```rust
use std::cell::Cell;

trait Foo<'a> {
    const C: Option<Cell<&'a u32>>;
}

impl<'a, T> Foo<'a> for T {
    const C: Option<Cell<&'a u32>> = None;
}

fn foo() {
    let a = 22;
    let b = Some(Cell::new(&a));
    match b {
        <() as Foo<'static>>::C => { }
        _ => { }
    }
}

fn main() {
}
```

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #55511 and Fixes #55401. Contributes to #54943.

This PR performs a large refactoring on user type annotations, checks user type annotations for associated constants in patterns and that user type annotations for `ref` bindings are respected.

r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
As of submission, this PR only implements half of the proposed solution. WIP PR requested by @nikomatsakis to aid discussion in Zulip.

File: src/librustc/mir/mod.rs [hunk 1]
```diff
@@ -1784,19 +1790,8 @@ pub enum StatementKind<'tcx> {
...
-    /// The effect of this annotation is to relate the type `T_y` of the place `y`
-    /// to the user-given type `T`. The effect depends on the specified variance:
-    ///
-    /// - `Covariant` -- requires that `T_y <: T`
-    /// - `Contravariant` -- requires that `T_y :> T`
-    /// - `Invariant` -- requires that `T_y == T`
-    /// - `Bivariant` -- no effect
-    AscribeUserType(Place<'tcx>, ty::Variance, Box<UserTypeProjection<'tcx>>),
+    /// This represents the insertion of a user type ascription to be asserted.
+    AscribeUserType(UserTypeAscription),
```
Comment (nikomatsakis) [inline src/librustc/mir/mod.rs]: FWIW, I think I would make the `UserTypeAscription` only refer to the `UserTypeProjection<'tcx>` -- or, hmm, I guess that only makes sense relative to the place, huh? 

In a way, I think the thing we want in the array is probably the "kernel type", not the projection parts.

File: src/librustc/mir/visit.rs [hunk 2]
```diff
@@ -874,6 +879,22 @@ macro_rules! make_mir_visitor {
...
 
+            fn super_user_type_ascription_data(
+                &mut self,
+                _ascription: UserTypeAscription,
+                data: & $($mutability)* UserTypeAscriptionData<'tcx>,
+            ) {
+                let UserTypeAscriptionData {
+                    ref $($mutability)* user_type_projection,
+                    ref $($mutability)* span,
+                    place: _, // Don't visit place..
```
Comment (nikomatsakis) [inline src/librustc/mir/visit.rs]: I'm not sure that it matters -- it might -- but this alters the behavior of the visitor. We used to (in `super_ascribe_user_ty`) visit the place.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 3]
```diff
@@ -1289,21 +1289,32 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
                     );
                 };
             }
-            StatementKind::AscribeUserType(ref place, variance, box ref c_ty) => {
+            StatementKind::AscribeUserType(ascription) => {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: There is still some question in my mind about what user-provided type annotations mean for mutable places (do they apply to all values the place takes on? only at the point where they were given? etc). But if we *do* keep the `Locations::All` interpretation, then we might just remove the `StatementKind` for `AscribeUserType` altogether, right? Instead, we would just iterate over the `UserTypeAnnotation` array.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 4]
```diff
@@ -1289,21 +1289,32 @@ impl<'a, 'gcx, 'tcx> TypeChecker<'a, 'gcx, 'tcx> {
...
+                    Locations::All(span),
                     ConstraintCategory::TypeAnnotation,
                 ) {
                     span_mirbug!(
                         self,
                         stmt,
                         "bad type assert ({:?} <: {:?}): {:?}",
                         place_ty,
-                        c_ty,
+                        user_type_projection,
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/nll/type_check/mod.rs]: I suspect we will want to extend the `TypeVerifier` stuff:

https://github.com/rust-lang/rust/blob/6f244c9011eb01ae4d167b631ba5e3e163bafa72/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L268

well, actually, just adding to the visitor should be ok. The main thing is that we want

https://github.com/rust-lang/rust/blob/6f244c9011eb01ae4d167b631ba5e3e163bafa72/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L275

to be invoked.

**Comment by davidtwco** [comment]
Pushed a new commit that is much closer to what we're wanting - it still fails but it's closer.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 4 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Resolving this as all the code has changed.

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs (hunk 3 above)
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Resolving this as all the code has changed.

File: src/librustc/mir/visit.rs (hunk 2 above)
Comment (davidtwco) [reply src/librustc/mir/visit.rs]: Resolving this as all the code has changed.

File: src/librustc/mir/mod.rs (hunk 1 above)
Comment (davidtwco) [reply src/librustc/mir/mod.rs]: Resolving this as all the code has changed.

**Review by nikomatsakis — APPROVED** [review]
Looks great! Left one nit.

r=me once tests passed and comment is added

File: src/librustc_mir/borrow_check/nll/type_check/mod.rs [hunk 5]
```diff
@@ -722,6 +722,8 @@ struct TypeChecker<'a, 'gcx: 'tcx, 'tcx: 'a> {
     reported_errors: FxHashSet<(Ty<'tcx>, Span)>,
     borrowck_context: Option<&'a mut BorrowCheckContext<'a, 'tcx>>,
     universal_region_relations: Option<&'a UniversalRegionRelations<'tcx>>,
+    instantiated_types: FxHashMap<UserTypeAnnotationIndex, Ty<'tcx>>,
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_mir/borrow_check/nll/type_check/mod.rs]: Fixed this.

**Comment by davidtwco** [comment]
Pushed the first version of this that does what it says on the tin. Will need a fresh review as a lot has changed.

**Comment by davidtwco** [comment]
Added a fix for another issue to this PR. Still seeing an ICE on three tests for the original fix, worked out that is due to this addition:

https://github.com/rust-lang/rust/blob/bde1f0d98bd1927baf5f53bd5c0d54d1382f1c45/src/librustc_traits/type_op.rs#L151-L154

But without that addition, the test change in `src/test/ui/regions/regions-free-region-ordering-caller1.rs` doesn't happen. Still working on it.

**Comment by davidtwco** [comment]
I’ve fixed the remaining ICEs in this PR. To do this, well-formedness checking of the `UserTypeAnnotation::Ty(..)` case had to be performed only in reachable code (though this case wasn’t being done at all before AFAIK, so it’s possible it isn’t even needed).

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
I feel good about this as a solid step forward. Thanks @davidtwco for sticking with it. =)

File: src/test/ui/issue-54943-3.rs [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+// ignore-test
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply src/test/ui/issue-54943-3.rs]: I'd rather we document the current behavior, and leave "FIXME" comments explaining what we want to be if it deviates from the desired behavior.

File: src/test/ui/issue-54943-3.rs [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+
+#![feature(nll)]
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/test/ui/issue-54943-3.rs]: I've added this comment and a similar one for the other ignored test.

File: src/test/ui/issue-54943-3.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/test/ui/issue-54943-3.rs]: I've ignored both tests that we expect errors from due to unreachable code (that is, `issue-54943.rs` and `issue-54943-3.rs`).

I've add a comment to the ignored tests as per your other review comment and a FIXME that points to the #54943.

[the remark this answers is not in the document]
Comment (davidtwco) [reply src/test/ui/issue-54943-3.rs]: Changed these so they aren't ignored but test the current behaviour so they will fail when this is fixed.

**Comment by davidtwco** [comment]
Added two commits from @pnkfelix that aid in fixing #55748.

File: src/librustc_mir/hair/pattern/mod.rs [hunk 8]
```diff
@@ -179,7 +179,12 @@ impl<'tcx> PatternTypeProjection<'tcx> {
         annotations: &mut CanonicalUserTypeAnnotations<'tcx>,
         span: Span,
     ) -> UserTypeProjection<'tcx> {
-        let annotation_index = annotations.push((span, self.base));
+        let annotation = (span, self.base);
+        let annotation_index = if let Some(index) = annotations.position(|a| a == &annotation) {
```
Comment (nikomatsakis) [inline src/librustc_mir/hair/pattern/mod.rs]: I'm not convinced this is correct. Does it include some kind of link to the user's source? For example, what if we have:

```rust
let x: Vec<_> = ...;
let y: Vec<_> = ...;
```

would those two instances of `Vec<_>` wind up as the same canonical user type annotation?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
What do you think @pnkfelix @davidtwco ?

File: src/librustc_mir/hair/pattern/mod.rs (hunk 8 above)
Comment (pnkfelix) [reply src/librustc_mir/hair/pattern/mod.rs]: In further discussion on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/.2354943.20user.20type.20annot.20in.20unreachable.20code/near/152252966), @davidtwco provided a different path towards a more limited avoidance of duplication that will also resolve my issues on #55748

**Comment by pnkfelix** [comment]
(this looks good to me. I'm planning to r+ but I'll wait a few hours to see if @nikomatsakis wants to weigh in on the latest commit.)

**Comment by davidtwco** [comment]
@pnkfelix could you review the most recent commit before `r+`? - it guarantees ordering for errors produced by a debug attribute that caused the error when bors was attempting to merge this.

File: src/librustc_typeck/check/writeback.rs [hunk 9]
```diff
@@ -374,8 +376,30 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
+                    // This is a unit-testing mechanism.
+                    let node_id = self.tcx().hir().hir_to_node_id(hir_id);
+                    let span = self.tcx().hir().span(node_id);
+                    // We need to buffer the errors in order to guarantee a consistent
+                    // order when emitting them.
+                    let err = self.tcx().sess.struct_span_err(
+                        span,
+                        &format!("user substs: {:?}", user_substs)
+                    );
+                    err.buffer(&mut errors_buffer);
```
Comment (davidtwco) [inline src/librustc_typeck/check/writeback.rs]: @pnkfelix said (on a commit that since got changed in a rebase):
> Ugh this is going to be be yet another case of something where buffering upsets the use of tools like -Z treat-err-as-bug
> 
> Has we captured somewhere the pattern of buffering only if that and other related flags are off? Eg as a method on tcx? You don’t need to add such a method in this PR, but please double check if other spots that go buffering are using such a tcx method.

As far as I can gather, the only other place using diagnostic buffering like this is the borrow checker - where there are no such helpers. In this instance, buffering only takes place when the #[rustc_dump_user_substs] annotation is in use and that only happens in a handful of tests - it seems unlikely that it would interfere with usage of -Z treat-err-as-bug.

**Review by davidtwco — COMMENTED** [review]
Re-posting comments from @pnkfelix that got lost when commits changed in a rebase so they can be addressed.

File: src/librustc_typeck/check/writeback.rs (hunk 9 above)
Comment (pnkfelix) [reply src/librustc_typeck/check/writeback.rs]: Okay I must have misremembered. Chances are I tried adding such an abstraction and then later abandoned the attempt due to the code churn involved

**Comment by Xanewok** [comment]
I'm not sure I understand the fallout here.

```
   Compiling rls v1.31.6 (/home/xanewok/repos/rust/src/tools/rls)
error[E0621]: explicit lifetime required in the type of `msg`======> ] 245/246: rls(bin)
   --> src/tools/rls/src/server/mod.rs:185:21
    |
173 |       fn dispatch_message(&mut self, msg: &RawMessage) -> Result<(), jsonrpc::Error> {
    |                                           ----------- help: add explicit lifetime `'static` to the type of `msg`: `&'static server::message::RawMessage`
...
185 |                       <$n_action as LSPNotification>::METHOD => {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'static` required
...
259 | /         match_action!(
260 | |             msg.method;
261 | |             notifications:
262 | |                 notifications::Initialized,
...   |
287 | |                 requests::CodeLensRequest;
288 | |         );
    | |__________- in this macro invocation
error: aborting due to previous error
```

With [`$method` being expanded to `msg.method`](https://github.com/rust-lang/rls/blob/6f5e4bba7b1586fca6e0ea7724cadb5683b2f308/src/server/mod.rs#L260) (which itself is of type [`String`](https://github.com/rust-lang/rls/blob/6f5e4bba7b1586fca6e0ea7724cadb5683b2f308/src/server/message.rs#L296)), we match on [`$method.as_str()`](https://github.com/rust-lang/rls/blob/6f5e4bba7b1586fca6e0ea7724cadb5683b2f308/src/server/mod.rs#L183) and handle [associated constants of type `&'static str`](https://github.com/gluon-lang/languageserver-types/blob/1a6c6c18fc1350de532293fcb67cd45d12071d99/src/notification.rs#L5).

Indeed, matched value `msg.method.as_str()` will be of shorter lifetime (let's say `&'a str`) than the arms (associated constants of `&'static str` type) but I don't understand why. Shouldn't it be the other way around, that the match arms should live at least as long as the matched value? Am I missing something?

**Comment by nikomatsakis** [comment]
I filed https://github.com/rust-lang/rust/issues/57280, as this seems like a bug (and a regression).
