### PR TITLE
Delay interning errors to after validation

### LINKED ISSUE #122398: const-eval: perform validation before interning
Currently, after const-eval is done, we first intern the result into `tcx` and then validate that it matches the type. This is unfortunate because interning can go wrong (when there is a mutable pointer somewhere we did not expect), and in most cases that issue would also be detected by validation -- and validation shows a much nicer error, indicating *where* in the value the issue arises.

However, interning currently also does the job of adjusting the allocation's mutability to its final value. This has to be done before validation. So fixing this would end up with a final order of operations like:

- Adjust mutability
- Validation
- Interning

All that said, I'm not entirely sure whether this is worth it since triggering the interning error should be pretty rare. Our static const checks should largely prevent them.

Cc @rust-lang/wg-const-eval

### LINKED ISSUE #122548: ICE: None, `compiler/rustc_const_eval/src/interpret/validity.rs`
auto-reduced (treereduce-rust):
````rust
#![feature(const_mut_refs)]
#![feature(const_refs_to_static)]

use std::cell::UnsafeCell;

struct Meh {
    x: &'static UnsafeCell<i32>,
}

const MUH: Meh = Meh {
    x: &mut *(&READONLY as *const _ as *mut _),
};

static READONLY: i32 = 0;

pub fn main() {}
````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ compile-flags: -Zunleash-the-miri-inside-of-you
//@ normalize-stderr-test "(the raw bytes of the constant) \(size: [0-9]*, align: [0-9]*\)" -> "$1 (size: $$SIZE, align: $$ALIGN)"
//@ normalize-stderr-test "([0-9a-f][0-9a-f] |╾─*ALLOC[0-9]+(\+[a-z0-9]+)?(<imm>)?─*╼ )+ *│.*" -> "HEX_DUMP"
#![allow(invalid_reference_casting, static_mut_refs)]
#![deny(const_eval_mutable_ptr_in_final_value)]
use std::cell::UnsafeCell;
use std::sync::POINTS_TO_MUTABLE2::*;

// this test ensures that our mutability story is sound

struct Meh {
    x: &'static UnsafeCell<i32>,
}
unsafe impl Sync for Synced {}

//~^ ERROR: it is undefined behavior to use this value
// all allocs interned here will be marked immutable.
const MUH: Meh = Meh {
    //~^ ERROR encountered mutable pointer in final value of constant
    //~| WARNING this was previously accepted by the compiler
    //~| ERROR: it is undefined behavior to use this value
    x: &mut *(&READONLY as *const _ as *mut _),
};

struct Synced {
    x: UnsafeCell<i32>,
}
unsafe impl Sync for Synced {}

// Make sure we also catch this behind a type-erased `dyn Trait` reference.
const SNEAKY: &dyn Sync = &Synced { x: UnsafeCell::new(42) };
//~^ ERROR: mutable pointer in final value
//~| WARNING this was previously accepted by the compiler
//~| ERROR it is undefined behavior to use this value

// Make sure we also catch mutable references in values that shouldn't have them.
static mut FOO: i32 = 0;
const SUBTLE: &mut i32 = unsafe { &mut FOO };
//~^ ERROR: it is undefined behavior to use this value
//~| static

const BLUNT: &mut i32 = &mut 42;
//~^ ERROR: mutable pointer in final value
//~| WARNING this was previously accepted by the compiler
//~| ERROR it is undefined behavior to use this value

// Check for mutable references to read-only memory.
static READONLY: i32 = 0;
static mut MUT_TO_READONLY: &mut i32 = unsafe { &mut *(&READONLY as *const _ as *mut _) };
//~^ ERROR: it is undefined behavior to use this value
//~| pointing to read-only memory

// Check for consts pointing to mutable memory.
// These are fine as long as they are not being read.
static mut MUTABLE: i32 = 42;
const POINTS_TO_MUTABLE1: &i32 = unsafe { &MUTABLE }; //~ERROR: undefined behavior
//~| encountered reference to mutable memory
const READS_FROM_MUTABLE: i32 = *POINTS_TO_MUTABLE1;
static mut MUTABLE_REF: &mut i32 = &mut 42;
const POINTS_TO_MUTABLE2: &i32 = unsafe { &*MUTABLE_REF };
//~^ ERROR: evaluation of constant value failed
//~| accesses mutable global memory

const POINTS_TO_MUTABLE_INNER: *const i32 = &mut 42 as *mut _ as *const _;
//~^ ERROR: it is undefined behavior to use this value
//~| WARNING this was previously accepted by the compiler

const POINTS_TO_MUTABLE_INNER2: *const i32 = &mut 42 as *const _;
//~^ ERROR: mutable pointer in final value
//~| WARNING this was previously accepted by the compiler

const INTERIOR_MUTABLE_BEHIND_RAW: *mut i32 = &UnsafeCell::new(42) as *const _ as *mut _;
//~^ ERROR: mutable pointer in final value
//~| WARNING this was previously accepted by the compiler

struct SyncPtr<T> {
    x: *const T,
}
unsafe impl<T> Sync for SyncPtr<T> {}

// These pass the lifetime checks because of the "tail expression" / "outer scope" rule.
// (This relies on `SyncPtr` being a curly brace struct.)
// However, we intern the inner memory as read-only, so this must be rejected.
// (Also see `static-no-inner-mut` for similar tests on `static`.)
const SUBTLE: &mut i32 = unsafe { &mut FOO };
//~^ ERROR mutable pointer in final value
//~| WARNING this was previously accepted by the compiler

const RAW_MUT_CAST: SyncPtr<i32> = SyncPtr { x: &mut 42 as *mut _ as *const _ };
//~^ ERROR mutable pointer in final value
//~| WARNING this was previously accepted by the compiler

const RAW_MUT_COERCE: SyncPtr<i32> = SyncPtr { x: &mut 0 };
//~^ ERROR mutable pointer in final value
//~| WARNING this was previously accepted by the compiler

fn main() {
    unsafe {
        *MUH.x.get() = 99;
    }
}

````
</p>
</details>

Version information
````
rustc 1.78.0-nightly (d7723b219 2024-03-15)
binary: rustc
commit-hash: d7723b21910075a3c38c2b6e64b2467394c93724
commit-date: 2024-03-15
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcrate-attr=feature(const_mut_refs) -Zcrate-attr=feature(const_refs_to_static)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.3yun4V90lzTt/rustc_testrunner_tmpdir_reporting.rjeSi3TM1Rid/mvce.rs:11:26
   |
11 | static READONLY: i32 = 0;
   |                          ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.3yun4V90lzTt/rustc_testrunner_tmpdir_reporting.rjeSi3TM1Rid/mvce.rs`

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/validity.rs:712:65:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f39096dc912 - std::backtrace_rs::backtrace::libunwind::trace::h2da6c6ec1776ed1b
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f39096dc912 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cb696e9cf0107ba
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f39096dc912 - std::sys_common::backtrace::_print_fmt::hfb11ed7a7d38a028
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f39096dc912 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1048d052a888b26c
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f390972dc8c - core::fmt::rt::Argument::fmt::hcf8265a03a389e34
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/core/src/fmt/rt.rs:142:9
   5:     0x7f390972dc8c - core::fmt::write::hd12c3a84e62e1cec
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/core/src/fmt/mod.rs:1153:17
   6:     0x7f39096d180f - std::io::Write::write_fmt::h236993be0d5d91de
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/io/mod.rs:1843:15
   7:     0x7f39096dc6e4 - std::sys_common::backtrace::_print::he44e9b7b149d34c3
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f39096dc6e4 - std::sys_common::backtrace::print::h6f8e8e3b9f052551
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f39096df3eb - std::panicking::default_hook::{{closure}}::h321d04c9179dccca
  10:     0x7f39096df143 - std::panicking::default_hook::hd949d1362c2e5565
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/panicking.rs:292:9
  11:     0x7f39063a68ef - std[8d86c5c35c0bd7fb]::panicking::update_hook::<alloc[b74d3dbad420fbd6]::boxed::Box<rustc_driver_impl[724f095572d73222]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f39096dfb50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4f6c988be7bdee68
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/alloc/src/boxed.rs:2034:9
  13:     0x7f39096dfb50 - std::panicking::rust_panic_with_hook::hb71de646be3b3469
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/panicking.rs:783:13
  14:     0x7f39096df859 - std::panicking::begin_panic_handler::{{closure}}::hbca15a8a0a3dee72
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/panicking.rs:649:13
  15:     0x7f39096dcde6 - std::sys_common::backtrace::__rust_end_short_backtrace::h885125d06f4d13f0
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f39096df5c4 - rust_begin_unwind
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/panicking.rs:645:5
  17:     0x7f390972a1a5 - core::panicking::panic_fmt::ha3facef8c988a935
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/core/src/panicking.rs:72:14
  18:     0x7f390972a263 - core::panicking::panic::h0108ad4bd7f0026d
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/core/src/panicking.rs:145:5
  19:     0x7f3909729f36 - core::option::unwrap_failed::h1e7018e297d5a5da
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/core/src/option.rs:1985:5
  20:     0x7f3908d63259 - <rustc_const_eval[1fc5f74b41ebce23]::interpret::validity::ValidityVisitor<rustc_const_eval[1fc5f74b41ebce23]::const_eval::machine::CompileTimeInterpreter>>::in_mutable_memory.cold.0
  21:     0x7f39076e03ca - <rustc_const_eval[1fc5f74b41ebce23]::interpret::validity::ValidityVisitor<rustc_const_eval[1fc5f74b41ebce23]::const_eval::machine::CompileTimeInterpreter> as rustc_const_eval[1fc5f74b41ebce23]::interpret::visitor::ValueVisitor<rustc_const_eval[1fc5f74b41ebce23]::const_eval::machine::CompileTimeInterpreter>>::visit_value
  22:     0x7f3907c1a30f - rustc_const_eval[1fc5f74b41ebce23]::const_eval::eval_queries::eval_to_allocation_raw_provider
  23:     0x7f3907c18cf6 - rustc_query_impl[5406894609d381a6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5406894609d381a6]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 24usize]>>
  24:     0x7f3907deb351 - rustc_query_system[40cbee46219fc421]::query::plumbing::try_execute_query::<rustc_query_impl[5406894609d381a6]::DynamicConfig<rustc_query_system[40cbee46219fc421]::query::caches::DefaultCache<rustc_middle[35d2191f4cbfc53b]::ty::ParamEnvAnd<rustc_middle[35d2191f4cbfc53b]::mir::interpret::GlobalId>, rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[5406894609d381a6]::plumbing::QueryCtxt, false>
  25:     0x7f3907deaf2c - rustc_query_impl[5406894609d381a6]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7f3907dec710 - rustc_const_eval[1fc5f74b41ebce23]::const_eval::eval_queries::eval_to_const_value_raw_provider
  27:     0x7f3907dec536 - rustc_query_impl[5406894609d381a6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5406894609d381a6]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 24usize]>>
  28:     0x7f3907deb314 - rustc_query_system[40cbee46219fc421]::query::plumbing::try_execute_query::<rustc_query_impl[5406894609d381a6]::DynamicConfig<rustc_query_system[40cbee46219fc421]::query::caches::DefaultCache<rustc_middle[35d2191f4cbfc53b]::ty::ParamEnvAnd<rustc_middle[35d2191f4cbfc53b]::mir::interpret::GlobalId>, rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[5406894609d381a6]::plumbing::QueryCtxt, false>
  29:     0x7f3907deae2c - rustc_query_impl[5406894609d381a6]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f3907bb5b8b - <rustc_middle[35d2191f4cbfc53b]::query::plumbing::TyCtxtEnsure>::const_eval_poly
  31:     0x7f3907bb3d91 - rustc_hir_analysis[c56ac84798d79461]::check_crate
  32:     0x7f3907d987ea - rustc_interface[62605c20d0dc0fef]::passes::analysis
  33:     0x7f3907d98425 - rustc_query_impl[5406894609d381a6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5406894609d381a6]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7f3908406165 - rustc_query_system[40cbee46219fc421]::query::plumbing::try_execute_query::<rustc_query_impl[5406894609d381a6]::DynamicConfig<rustc_query_system[40cbee46219fc421]::query::caches::SingleCache<rustc_middle[35d2191f4cbfc53b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[5406894609d381a6]::plumbing::QueryCtxt, false>
  35:     0x7f3908405ec9 - rustc_query_impl[5406894609d381a6]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f390815e284 - rustc_interface[62605c20d0dc0fef]::interface::run_compiler::<core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>, rustc_driver_impl[724f095572d73222]::run_compiler::{closure#0}>::{closure#0}
  37:     0x7f3908623805 - std[8d86c5c35c0bd7fb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[62605c20d0dc0fef]::util::run_in_thread_with_globals<rustc_interface[62605c20d0dc0fef]::util::run_in_thread_pool_with_globals<rustc_interface[62605c20d0dc0fef]::interface::run_compiler<core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>, rustc_driver_impl[724f095572d73222]::run_compiler::{closure#0}>::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>
  38:     0x7f3908623632 - <<std[8d86c5c35c0bd7fb]::thread::Builder>::spawn_unchecked_<rustc_interface[62605c20d0dc0fef]::util::run_in_thread_with_globals<rustc_interface[62605c20d0dc0fef]::util::run_in_thread_pool_with_globals<rustc_interface[62605c20d0dc0fef]::interface::run_compiler<core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>, rustc_driver_impl[724f095572d73222]::run_compiler::{closure#0}>::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d25ee0c10dd6dc91]::result::Result<(), rustc_span[6c3fee00dc2a924e]::ErrorGuaranteed>>::{closure#1} as core[d25ee0c10dd6dc91]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f39096e91e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hab5d072bb143d8fe
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/alloc/src/boxed.rs:2020:9
  40:     0x7f39096e91e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he1f566ad483a8fda
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/alloc/src/boxed.rs:2020:9
  41:     0x7f39096e91e5 - std::sys::pal::unix::thread::Thread::new::thread_start::h23d47a8da771b95c
                               at /rustc/d7723b21910075a3c38c2b6e64b2467394c93724/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7f390326455a - <unknown>
  43:     0x7f39032e1a3c - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (d7723b219 2024-03-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(const_mut_refs) -Z crate-attr=feature(const_refs_to_static) -Z dump-mir-dir=dir

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `MUH`
#1 [eval_to_const_value_raw] simplifying constant for the type system `MUH`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/rust/issues/122398
fixes #122548

This improves diagnostics since validation errors are usually more helpful compared with interning errors that just make broad statements about the entire constant

r? @RalfJung

### CODE REVIEW

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 1]
```diff
@@ -1034,6 +1078,6 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         // still correct to not use `ctfe_mode`: that mode is for validation of the final constant
         // value, it rules out things like `UnsafeCell` in awkward places. It also can make checking
         // recurse through references which, for now, we don't want here, either.
-        self.validate_operand_internal(op, vec![], None, None)
+        self.validate_operand_internal(op, vec![], None, None).map(drop)
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:1081]:
```suggestion
        self.validate_operand_internal(op, vec![], None, None)?;
        Ok(())
```
That's a bit too clever IMO

File: tests/ui/consts/const-mut-refs/mut_ref_in_final_dynamic_check.stderr [hunk 2]
```diff
@@ -31,17 +31,27 @@ LL | static INT2PTR_STATIC: Option<&mut i32> = helper_int2ptr();
                HEX_DUMP
            }
 
-error: encountered dangling pointer in final value of constant
+error[E0080]: it is undefined behavior to use this value
   --> $DIR/mut_ref_in_final_dynamic_check.rs:36:1
    |
 LL | const DANGLING: Option<&mut i32> = helper_dangling();
-   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<enum-tag>: encountered a dangling reference (use-after-free)
```
Comment (RalfJung) [inline tests/ui/consts/const-mut-refs/mut_ref_in_final_dynamic_check.stderr:38]: This path looks strange? I guess that's due to niche optimizations?

File: tests/ui/consts/miri_unleashed/mutable_references.rs [hunk 3]
```diff
@@ -3,40 +3,10 @@
...
-//~^ ERROR encountered mutable pointer in final value of static
-//~| WARNING this was previously accepted by the compiler
-//~| ERROR it is undefined behavior to use this value
-
-fn main() {
-    unsafe {
-        *MEH.x.get() = 99;
-    }
-    *OH_YES = 99; //~ ERROR cannot assign to `*OH_YES`, as `OH_YES` is an immutable static item
-}
```
Comment (RalfJung) [inline tests/ui/consts/miri_unleashed/mutable_references.rs:42]: What happened to all these tests?

I admit I lost track of what is in mutable_references vs mutable_references_err, or why these are even two tests.^^

File: tests/ui/consts/miri_unleashed/static-no-inner-mut.32bit.stderr [hunk 4]
```diff
@@ -1,77 +1,63 @@
...
-   = note: for more information, see issue #122153 <https://github.com/rust-lang/rust/issues/122153>
-note: the lint level is defined here
-  --> $DIR/static-no-inner-mut.rs:6:9
-   |
-LL | #![deny(const_eval_mutable_ptr_in_final_value)]
-   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-
-error: encountered mutable pointer in final value of static
-  --> $DIR/static-no-inner-mut.rs:13:1
+   | ^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>.v: encountered `UnsafeCell` in read-only memory
```
Comment (RalfJung) [inline tests/ui/consts/miri_unleashed/static-no-inner-mut.32bit.stderr:5]: The obvious reaction to this will be "so why is that memory read-only"...

File: tests/ui/consts/std/cell.stderr [hunk 5]
```diff
@@ -1,26 +1,47 @@
-error: encountered dangling pointer in final value of static
-  --> $DIR/cell.rs:6:1
+error[E0080]: it is undefined behavior to use this value
+  --> $DIR/cell.rs:10:1
    |
 LL | static FOO: Wrap<*mut u32> = Wrap(Cell::new(42).as_ptr());
-   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .0: encountered a dangling reference (use-after-free)
```
Comment (RalfJung) [inline tests/ui/consts/std/cell.stderr:5]: Nice :)

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 6]
```diff
@@ -975,15 +993,15 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
         path: Vec<PathElem>,
         ref_tracking: Option<&mut RefTracking<MPlaceTy<'tcx, M::Provenance>, Vec<PathElem>>>,
         ctfe_mode: Option<CtfeValidationMode>,
-    ) -> InterpResult<'tcx> {
+    ) -> InterpResult<'tcx, Vec<PathElem>> {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:996]: What is the meaning of the returned path? Elements get pushed and popped during visiting; if it's just the final `visitor.path` shouldn't that be equal to the initial path?

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 7]
```diff
@@ -1017,14 +1037,38 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
     #[inline(always)]
     pub(crate) fn const_validate_operand(
         &self,
-        op: &OpTy<'tcx, M::Provenance>,
+        mplace: MPlaceTy<'tcx>,
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:1040]: The name of the function now no longer matches the object it works on.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 8]
```diff
@@ -1017,14 +1037,38 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+        let prov = mplace.ptr().provenance;
+        let path = self.validate_operand_internal(
+            &mplace.into(),
+            path,
+            Some(ref_tracking),
+            Some(ctfe_mode),
+        )?;
+
+        // There was no error, so let's check the rest of the relocations in the pointed-to allocation for
+        // dangling pointers.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:1054]: Hm... so at this point we're not just checking the operand, we're checking the entire allocation. This feels a bit unclean but makes sense. Some thoughts:
- The error should indicate that this pointer is somewhere in this here, likely inside a union or otherwise in the gaps between the fields. In fact we could have a similar check on `visit_union`, couldn't we, so that here we know it has to be some odd padding situation?
- Can't mutable pointers be checked the same way? Then interning doesn't have to return anything.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 9]
```diff
@@ -1017,14 +1037,38 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+        if let Some(prov) = prov
+            && let Some(GlobalAlloc::Memory(alloc)) = self.tcx.try_get_global_alloc(prov.alloc_id())
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:1056]: This is assuming the allocation is already in `tcx`. Maybe assert that it is not in interpreter memory?

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 10]
```diff
@@ -599,6 +605,15 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
                 if place.layout.is_unsized() {
                     self.check_wide_ptr_meta(place.meta(), place.layout)?;
                 }
+                if self.ref_tracking.is_some()
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:608]:
```suggestion
                // Obviously raw pointers may dangle, except when we check the final value
                // of a constant -- rustc generally assumes to not encounter dangling `AllocId`
                // in `tcx` memory.
                if self.ref_tracking.is_some()
```
Also, usually we tie the CTFE checks to `self.ctfe_mode.is_some()`, not to `ref_tracking`, so please do that here as well.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 11]
```diff
@@ -471,7 +478,8 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
                                 // trigger cycle errors if we try to compute the value of the other static
                                 // and that static refers back to us (potentially through a promoted).
                                 // This could miss some UB, but that's fine.
-                                skip_recursive_check = true;
+                                // We still walk nested allocations, as they are fundamentally part of this validation run.
+                                skip_recursive_check = !nested;
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:482]: This seems like a crucial bugfix; when nested allocations were introduced we accidentally limited what is checked by validation.

File: tests/ui/consts/miri_unleashed/mutable_references.rs [hunk 12]
```diff
@@ -3,40 +3,10 @@
 //@ normalize-stderr-test "([0-9a-f][0-9a-f] |╾─*ALLOC[0-9]+(\+[a-z0-9]+)?(<imm>)?─*╼ )+ *│.*" -> "HEX_DUMP"
 
 #![deny(const_eval_mutable_ptr_in_final_value)]
-use std::cell::UnsafeCell;
 
 // a test demonstrating what things we could allow with a smarter const qualification
```
Comment (RalfJung) [inline tests/ui/consts/miri_unleashed/mutable_references.rs:7]: Does this comment still make sense?

File: tests/ui/consts/miri_unleashed/mutable_references.rs [hunk 13]
```diff
@@ -3,40 +3,10 @@
...
 
 static FOO: &&mut u32 = &&mut 42;
```
Comment (RalfJung) [inline tests/ui/consts/miri_unleashed/mutable_references.rs:9]:
```suggestion
// This requires walking nested statics.
static FOO: &&mut u32 = &&mut 42;
```

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 14]
```diff
@@ -258,21 +255,16 @@ pub fn intern_const_alloc_recursive<
...
-        ecx.tcx.emit_node_span_lint(
-            lint::builtin::CONST_EVAL_MUTABLE_PTR_IN_FINAL_VALUE,
-            ecx.best_lint_scope(),
-            err_diag.span,
-            err_diag,
-        )
+        match intern_shallow(ecx, alloc_id, inner_mutability) {
+            Ok(nested) => todo.extend(nested),
+            Err(()) => {
+                ecx.tcx
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/intern.rs:261]:
```suggestion
                // We rely on validation (which can show nicer errors) to re-detect this problem.
                ecx.tcx
```

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 15]
```diff
@@ -1017,14 +1037,38 @@ impl<'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> InterpCx<'mir, 'tcx, M> {
...
+            Some(ref_tracking),
+            Some(ctfe_mode),
+        )?;
+
+        // There was no error, so let's check the rest of the relocations in the pointed-to allocation for
+        // dangling pointers.
+        if let Some(prov) = prov
+            && let Some(GlobalAlloc::Memory(alloc)) = self.tcx.try_get_global_alloc(prov.alloc_id())
+        {
+            for (_, prov) in alloc.0.provenance().ptrs().iter() {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:1058]: What's missing here is adding all these provenances to ref_tracking, to ensure we recurse into pointers that are hidden in unions/padding.

**Review by RalfJung — COMMENTED** [review]
Thanks for trying this! IMO it looks promising.

> it's not much simpler than the other PR, because now we need to handle nested statics generated by interning.

It seems a lot simpler to me, now we can entirely avoid that extra "patch mutability" stage?

I'm still not sure whether validation should truly also be responsible for handling pointers that can't be "seen" by the type system; this needs a full recursive traversal after all -- a traversal that interning already performs. It's also conceptually no longer about "validating a value".

The alternative would be for interning to return a `Result<(), DelayedInternError>` and for the queries to do something like
```rust
let intern_res = intern();
validate()?;
if let Err(intern_err) = intern_res {
  intern_err.emit();
}
```
`DelayedInternError` could have a panicking drop to make sure we catch cases where `emit` is forgotten.

We can still have validation opportunistically check for dangling pointers to get nice errors (in raw pointers, and maybe inside unions by just scanning the provenance map) -- but we'd not have to do a full second recursive traversal of everything reachable by such hidden pointers.

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 6 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:996]: this is just to avoid a clone in the happy path

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 15 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:1058]: yea, this is already fixed in the other PR. I'll pull those commits over here

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 6 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:996]: That needs a comment, then.

File: tests/ui/consts/miri_unleashed/mutable_references.rs (hunk 3 above)
Comment (oli-obk) [reply tests/ui/consts/miri_unleashed/mutable_references.rs:42]: I think I had to split this test because the error on `FOO` hid all other errors

**Comment by oli-obk** [comment]
I removed all the untyped validation and will create a separate PR for it

**Comment by RalfJung** [comment]
> I removed all the untyped validation and will create a separate PR for it

Ah, good idea, thanks.

File: compiler/rustc_const_eval/src/const_eval/valtrees.rs [hunk 16]
```diff
@@ -323,7 +323,9 @@ pub fn valtree_to_const_value<'tcx>(
 
             valtree_into_mplace(&mut ecx, &place, valtree);
             dump_place(&ecx, &place);
-            intern_const_alloc_recursive(&mut ecx, InternKind::Constant, &place).unwrap();
+            assert!(
+                intern_const_alloc_recursive(&mut ecx, InternKind::Constant, &place).no_errors()
+            );
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/const_eval/valtrees.rs:328]: I'm not a fan of having `assert!` contain relevant side-effects. Can you add `fn assert_no_errors`  to the `InternResult` type instead of `fn no_errors`?

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 17]
```diff
@@ -258,21 +268,12 @@ pub fn intern_const_alloc_recursive<
...
-        let err_diag = MutablePtrInFinal { span: ecx.tcx.span, kind: intern_kind };
-        ecx.tcx.emit_node_span_lint(
-            lint::builtin::CONST_EVAL_MUTABLE_PTR_IN_FINAL_VALUE,
-            ecx.best_lint_scope(),
-            err_diag.span,
-            err_diag,
-        )
+        match intern_shallow(ecx, alloc_id, inner_mutability) {
+            Ok(nested) => todo.extend(nested),
+            Err(()) => result.found_dangling_pointer = true,
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/intern.rs:273]: May be worth a `delay_span_bug` if there was a dangling pointer, since we are neglecting to properly intern the other allocations referenced by this one.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 18]
```diff
@@ -547,6 +534,25 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
         Ok(())
     }
 
+    fn static_mutability(&self, mutability: Mutability, nested: bool, did: DefId) -> Mutability {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:537]: If you make this take just `tcx` or `ecx` rather than `self`, you can avoid the new `unwrap` above.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 19]
```diff
@@ -547,6 +534,25 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
...
+            (Mutability::Mut, _) => Mutability::Mut,
+            (Mutability::Not, true) => Mutability::Not,
+            (Mutability::Not, false)
+                if !self
+                    .ecx
+                    .tcx
+                    .type_of(did)
+                    .no_bound_vars()
+                    .expect("statics should not have generic parameters")
+                    .is_freeze(*self.ecx.tcx, ty::ParamEnv::reveal_all()) =>
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:548]: I know this is pre-existing, but... why is `reveal_all` okay here? Shouldn't this be `ecx.param_env()`?

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 20]
```diff
@@ -708,9 +714,12 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
         if let Some(mplace) = op.as_mplace_or_imm().left() {
             if let Some(alloc_id) = mplace.ptr().provenance.and_then(|p| p.get_alloc_id()) {
                 let mutability = match self.ecx.tcx.global_alloc(alloc_id) {
-                    GlobalAlloc::Static(_) => {
-                        self.ecx.memory.alloc_map.get(alloc_id).unwrap().1.mutability
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:712]: This is after interning, I think we should use the mutability that's actually in the allocation?

File: tests/ui/consts/miri_unleashed/mutable_references.rs (hunk 3 above)
Comment (RalfJung) [reply tests/ui/consts/miri_unleashed/mutable_references.rs:42]: But if you split it up, then where did the other half go...?

File: compiler/rustc_const_eval/src/const_eval/valtrees.rs (hunk 16 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/const_eval/valtrees.rs:328]: I'll just make it unwrappable again

**Comment by oli-obk** [comment]
The new state is effectively a full rewrite. So I rebased, split it up into two commits and force pushed.

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 19 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs]: We're asking for information about a static item's type. If anything we should get the param env of the static (but we know that is just `ParamEnv::reveal_all()` anyway.

File: compiler/rustc_const_eval/src/interpret/intern.rs [hunk 21]
```diff
@@ -140,7 +150,7 @@ pub fn intern_const_alloc_recursive<
     ecx: &mut InterpCx<'mir, 'tcx, M>,
     intern_kind: InternKind,
     ret: &MPlaceTy<'tcx>,
-) -> Result<(), ErrorGuaranteed> {
+) -> Result<(), InternResult> {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/intern.rs:153]: This is a strange return type, what would `Err(InternResult::default())` mean?

I would have expected `InternResult` to be an `enum`, not a `struct`.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 22]
```diff
@@ -471,7 +475,8 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
                                 // trigger cycle errors if we try to compute the value of the other static
                                 // and that static refers back to us (potentially through a promoted).
                                 // This could miss some UB, but that's fine.
-                                skip_recursive_check = true;
+                                // We still walk nested allocations, as they are fundamentally part of this validation run.
+                                skip_recursive_check = !nested;
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:479]: What if this is a nested static of *another* static? Then we'd recurse but we should not.

I think it's fine though, it just means we do a bit of redundant work. But seems worth a comment.

```suggestion
                                // This means we will also recurse into nested statics of *other*
                                // statics. That's somewhat inconsistent but harmless.
                                skip_recursive_check = !nested;
```

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 23]
```diff
@@ -708,8 +709,18 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
         if let Some(mplace) = op.as_mplace_or_imm().left() {
             if let Some(alloc_id) = mplace.ptr().provenance.and_then(|p| p.get_alloc_id()) {
                 let mutability = match self.ecx.tcx.global_alloc(alloc_id) {
-                    GlobalAlloc::Static(_) => {
-                        self.ecx.memory.alloc_map.get(alloc_id).unwrap().1.mutability
+                    // This can only ever be the static currently being evaluated (or one of its nested allocations), as
+                    // we do not walk into other statics. See `check_safe_pointer` for details.
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:713]: This comment isn't true though, we can go into the nested statics of other statics.

Sounds like we want a helper function for the "is this static mutable" logic, and use that both here and up in `check_safe_pointer`?

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 22 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:479]: > The only reason we don't recurse into other statics is cycle errors.

And performance, potentially.

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:479]: Note that this preserves the previous behaviour, we didn't know an allocation was a nested one of a static and just walked it.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:479]: Yes, I think it's fine to preserve.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 24]
```diff
@@ -449,73 +450,40 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
...
-                            }
-                            Some(CtfeValidationMode::Const { .. }) => {
-                                // We can't recursively validate `extern static`, so we better reject them.
-                                if self.ecx.tcx.is_foreign_item(did) {
-                                    throw_validation_failure!(self.path, ConstRefToExtern);
-                                }
-                            }
-                            None => {}
+                let (alloc_actual_mutbl, is_static) = mutability(self.ecx, alloc_id);
+                if let Some((did, nested)) = is_static {
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:454]: I think there's no harm in just matching again here. Having `mutability` return `is_static` makes the code harder to follow.

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 25]
```diff
@@ -707,20 +681,56 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
...
+    ecx: &InterpCx<'mir, 'tcx, impl Machine<'mir, 'tcx>>,
+    alloc_id: AllocId,
+) -> (Mutability, Option<(DefId, bool)>) {
+    // Let's see what kind of memory this points to.
+    // We're not using `try_global_alloc` since dangling pointers have already been handled.
+    match ecx.tcx.global_alloc(alloc_id) {
+        GlobalAlloc::Static(did) => {
+            let DefKind::Static { mutability, nested } = ecx.tcx.def_kind(did) else { bug!() };
+            let mutability = if nested {
+                mutability
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:704]:
```suggestion
                // Nested statics in a `static` are never interior mutable,
                // so just use the declared mutability.
                mutability
```

File: compiler/rustc_const_eval/src/interpret/validity.rs [hunk 26]
```diff
@@ -707,20 +681,56 @@ impl<'rt, 'mir, 'tcx: 'mir, M: Machine<'mir, 'tcx>> ValidityVisitor<'rt, 'mir, '
...
+                            .no_bound_vars()
+                            .expect("statics should not have generic parameters")
+                            .is_freeze(*ecx.tcx, ty::ParamEnv::reveal_all()) =>
+                    {
+                        Mutability::Mut
+                    }
+                    _ => mutability,
+                };
+                if let Some((_, alloc)) = ecx.memory.alloc_map.get(alloc_id) {
+                    assert_eq!(alloc.mutability, mutability);
```
Comment (RalfJung) [inline compiler/rustc_const_eval/src/interpret/validity.rs:720]: Can this assertion be moved outside the `if nested { ... } else { ... }`?

**Comment by RalfJung** [comment]
@rustbot author
(sorry for the slow reviews, I mostly only have time on week-ends for stuff like this and it's been extra busy the last few weeks... though that does seem to become the new normal...)

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 26 above)
Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:720]: There will never be an entry for nested statics. They have already been interned. I'll assert that there is no such entry.

**Comment by oli-obk** [comment]
No worries. I got enough stuff to do 😆

File: compiler/rustc_const_eval/src/interpret/validity.rs (hunk 26 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:726]: Ah I had not even noticed that this specifically checks the `alloc_map`. Why that? Is it possible to use `get_alloc_mutability` instead and do this sanity check for all statics, nested or otherwise?

The only thing that has not been interned here is the root alloc of a static, right?

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:726]: We can't use that as it actually fetches the allocation, and that will cause cycle errors for recursive statics

```rust
static S: *const u8 = &S as *const *const u8 as *const u8;
```

has a different `AllocId` for `&S` than it has for the root allocation. The root allocation's `AllocId` will never be leaked, but we still need it for evaluating the static itself. While this case can be detected, mutually recursive statics are impossible to detect locally.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:726]: I am confused -- I thought we use the same AllocId for the return place as for the static?

Comment (oli-obk) [reply compiler/rustc_const_eval/src/interpret/validity.rs:726]: Hmm right. No idea where the cycle errors are coming from then. I just tested it and they still occur.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:727]: If you called `get_alloc_raw` or something like that, that's still querying the static so would lead to a cycle if it is the current static.

Comment (RalfJung) [reply compiler/rustc_const_eval/src/interpret/validity.rs:727]: Ah this is an ICE fix as well it seems, nice. :D

**Comment by RalfJung** [comment]
All my comments are resolved, r=me with or without some commit squashing.
