### PR TITLE
parser: provide better suggestions and errors on closures with braces missing

### LINKED ISSUE #107959: Bad suggestion on missing block inside of a closure
### Code

```Rust
fn main() {
    let _x = std::boxed::Box::new(|x|x+1;);
}
```

### Current output

```
error: closure bodies that contain statements must be surrounded by braces
 --> src/main.rs:2:37
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                     ^
3 | }
  | ^
  |
note: statement found outside of a block
 --> src/main.rs:2:41
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                      ---^ this `;` turns the preceding closure into a statement
  |                                      |
  |                                      this expression is a statement because of the trailing semicolon
note: the closure body may be incorrectly delimited
 --> src/main.rs:2:35
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                   ^^^^^^ this is the parsed closure...
3 | }
  | - ...but likely you meant the closure to end here
help: try adding braces
  |
2 ~     let _x = std::boxed::Box::new(|x| {x+1;);
3 ~ }}
  |

error: expected `;`, found `}`
 --> src/main.rs:2:44
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                            ^ help: add `;` here
3 | }
  | - unexpected token

error: could not compile `playground` due to 3 previous errors
```

### Desired output

```
error: closure bodies that contain statements must be surrounded by braces
 --> src/main.rs:2:37
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                     ^
3 | }
  | ^
  |
note: statement found outside of a block
 --> src/main.rs:2:41
  |
2 |     let _x = std::boxed::Box::new(|x|x+1;);
  |                                      ---^ this `;` turns the preceding closure into a statement
  |                                      |
  |                                      this expression is a statement because of the trailing semicolon
help: try adding braces
  |
2 ~     let _x = std::boxed::Box::new(|x| {x+1;});
  |

error: could not compile `playground` due to 3 previous errors
```

### PR DESCRIPTION
**Pull request by ohno418**
We currently provide wrong suggestions and unhelpful errors on closure bodies with braces missing.

For example, given the following code:

```rust
fn main() {
    let _x = Box::new(|x|x+1;);
}
```

the current output is:

```
error: expected expression, found `)`
 --> ./main.rs:2:30
  |
2 |     let _x = Box::new(|x|x+1;);
  |                              ^ expected expression

error: closure bodies that contain statements must be surrounded by braces
 --> ./main.rs:2:25
  |
2 |     let _x = Box::new(|x|x+1;);
  |                         ^
3 | }
  | ^
  |
note: statement found outside of a block
 --> ./main.rs:2:29
  |
2 |     let _x = Box::new(|x|x+1;);
  |                          ---^ this `;` turns the preceding closure into a statement
  |                          |
  |                          this expression is a statement because of the trailing semicolon
note: the closure body may be incorrectly delimited
 --> ./main.rs:2:23
  |
2 |     let _x = Box::new(|x|x+1;);
  |                       ^^^^^^ this is the parsed closure...
3 | }
  | - ...but likely you meant the closure to end here
help: try adding braces
  |
2 ~     let _x = Box::new(|x| {x+1;);
3 ~ }}
  |

error: expected `;`, found `}`
 --> ./main.rs:2:32
  |
2 |     let _x = Box::new(|x|x+1;);
  |                                ^ help: add `;` here
3 | }
  | - unexpected token

error: aborting due to 3 previous errors
```

We got 3 errors, but all but the second are unnecessary or just wrong.

This commit allows outputting correct suggestions and errors. The above code would output like this:

```
error: closure bodies that contain statements must be surrounded by braces
 --> ./main.rs:2:25
  |
2 |     let _x = Box::new(|x|x+1;);
  |                         ^    ^
  |
note: statement found outside of a block
 --> ./main.rs:2:29
  |
2 |     let _x = Box::new(|x|x+1;);
  |                          ---^ this `;` turns the preceding closure into a statement
  |                          |
  |                          this expression is a statement because of the trailing semicolon
note: the closure body may be incorrectly delimited
 --> ./main.rs:2:23
  |
2 |     let _x = Box::new(|x|x+1;);
  |                       ^^^^^^ - ...but likely you meant the closure to end here
  |                       |
  |                       this is the parsed closure...
help: try adding braces
  |
2 |     let _x = Box::new(|x| {x+1;});
  |                           +    +

error: aborting due to previous error
```

Fixes https://github.com/rust-lang/rust/issues/107959.

r? diagnostics

### CODE REVIEW

File: compiler/rustc_parse/src/parser/mod.rs [hunk 1]
```diff
@@ -982,7 +982,11 @@ impl<'a> Parser<'a> {
         let initial_semicolon = self.token.span;
 
         while self.eat(&TokenKind::Semi) {
-            let _ = self.parse_stmt(ForceCollect::Yes)?;
+            let _ =
+                self.parse_stmt_without_recovery(false, ForceCollect::Yes).unwrap_or_else(|e| {
```
Comment (ohno418) [inline compiler/rustc_parse/src/parser/mod.rs:986]: Recovery within `parse_stmt` was doing something wrong. So changed it not to do.

**Review by davidtwco — APPROVED** [review]
