### PR TITLE
Better document the implementors of Clone and Copy

### LINKED ISSUE #25893: Rustdoc: No mention of copy trait for primitive types
As a new rust user I have struggled with a little problem: http://stackoverflow.com/questions/30540419/rust-ownership-copy-clone-trait

The ownership and borrowing rules are well explained in the docs **but** the copy trait and the types that implement them are not! 

In the doc http://doc.rust-lang.org/std/marker/trait.Copy.html primitive types are not listed as copy trait implementors. They should at least be mentioned there.

It would be good to also add  a little more info here: http://doc.rust-lang.org/book/ownership.html#copy-types Maybe give some examples like in my question on stackoverflow:

> The following two snippets of code only compile because `i32` and `bool` types both implement the copy trait. Meaning that the ownership is **not** moved by default but copied instead
> 
> ``` rust
> fn main() {
>     let a = 5;
> 
>     let _y = double(a);
>     println!("{}", a);
> }
> 
> fn double(x: i32) -> i32 {
>     x * 2
> }
> ```
> 
> ``` rust
> fn main() {
>     let a = true;
> 
>     let _y = change_truth(a);
>     println!("{}", a);
> }
> 
> fn change_truth(x: bool) -> bool {
>     !x
> }
> ```

This is **very important** since it is an **exception to the most important rule** of the language

Let me know if I have to make a pull request with a "change proposal" :)

### PR DESCRIPTION
**Pull request by FraGag**
There are two parts to this change. The first part is a change to the compiler and to the standard library (specifically, libcore) to allow implementations of `Clone` and `Copy` to be written for a subset of builtin types. By adding these implementations to libcore, they now show up in the documentation. This is a [breaking-change] for users of `#![no_core]`, because they will now have to supply their own copy of the implementations of `Clone` and `Copy` that were added in libcore.

The second part is purely a documentation change to document the other implementors of `Clone` and `Copy` that cannot be described in Rust code (yet) and are thus provided by the compiler.

Fixes #25893

### CODE REVIEW

**Comment by joshtriplett** [comment]
Sorry for the delayed response.

This looks plausible to me, and I like the idea of moving this out of compiler magic and into the library itself.

I'd like to get at least one other reviewer to check this.

r? @nikomatsakis

**Comment by shepmaster** [comment]
> This is a [breaking-change] for users of #![no_core]

Should we solicit opinions of people who might be affected by this?

**Comment by rkruppe** [comment]
I believe there are practically no legitimate use cases of no_core other than compiler developers trying to minimize a problem occurring in libcore. Using it is inherently very deeply entangled with compiler internals. Many routine changes can already break no_core usage, such as changing anything about any lang item (including adding or removing them), or even just changing something about the compiler such that compiling your code requires a lang item that previously wasn't required. Basically, using no_core out of tree is not supported.

**Comment by shepmaster** [comment]
> I believe there are practically no legitimate use cases of no_core other than compiler developers trying to minimize a problem occurring in libcore.

I know that [I've needed to use it when attempting to get AVR-Rust off the ground](https://github.com/shepmaster/rust-arduino-blink-led-no-core-with-cargo/blob/master/blink/src/main.rs), I kind of assumed that other embedded folk have needed to do the same.

**Comment by joshtriplett** [comment]
Probably couldn't hurt to raise attention on this via TWiR and/or an internals thread.

**Comment by rkruppe** [comment]
@shepmaster Good point, I forgot about AVR-Rust, sorry! I have reason to suspect AVR-Rust is pretty unique in this regard, though. Most embedded stuff is happening with more mature LLVM backends which have no problem (or not nearly as big a problem, e.g., they may just be missing support for some obscure intrinsics) getting libcore to compile. For example, MPS430 seems to have working libcore .

**Comment by rkruppe** [comment]
And to be clear, "getting a new target off the ground" is a totally legitimate use of no_core (I've even used it for that myself), but I count that under "usage by compiler developers" and it should usually be very temporary (AVR apparently being an exception). Since there are few compiler developers and even fewer targets being added, I don't think it's particularly likely that this PR will land after someone copied something from libcore, yet before they scrapped that copy and started compiling libcore as-is.

**Comment by shepmaster** [comment]
To be clear, **I** don't have a problem with this change affecting AVR-Rust, it's simply the only reason I know about `no_core`.

> I have reason to suspect AVR-Rust is pretty unique in this regard, though
>
> And to be clear, "getting a new target off the ground" is a totally legitimate use of no_core

I think this is where AVR-Rust is at as well; it's just taking longer because the LLVM support is being worked on in parallel.

> I forgot about AVR-Rust, sorry

Not to worry; it's not anywhere near feature complete ;-)

**Comment by nikomatsakis** [comment]
@FraGag 

> The first part is a change to the compiler and to the standard library (specifically, libcore) to allow implementations of Clone and Copy to be written for a subset of builtin types.

Can you say a bit more about the motivation here? Is it rustdoc or something else?

File: src/librustc_typeck/diagnostics.rs [hunk 1]
```diff
@@ -1973,16 +1973,16 @@ differs from the behavior for `&T`, which is always `Copy`).
 
 E0206: r##"
 You can only implement `Copy` for a struct or enum. Both of the following
-examples will fail, because neither `i32` (primitive type) nor `&'static Bar`
-(reference to `Bar`) is a struct or enum:
+examples will fail, because neither `fn() -> i32` nor `&'static mut Bar`
```
Comment (nikomatsakis) [inline src/librustc_typeck/diagnostics.rs]: I don't think we should include `fn() -> i32` as a sample type. `&'static mut Bar` is ok I guess.

Comment (nikomatsakis) [reply src/librustc_typeck/diagnostics.rs]: What about `[u8; 256]`?

**Comment by shepmaster** [comment]
@nikomatsakis several comments on [the original issue](https://github.com/rust-lang/rust/issues/25893) stem from Stack Overflow question-askers not knowing that e.g. `i32` is `Copy`. I'd say that documenting these would be a net win, but I'm not sure if there's more.

File: src/librustc_typeck/diagnostics.rs (hunk 1 above)
Comment (nikomatsakis) [reply src/librustc_typeck/diagnostics.rs]: Also, can you add a new test for what happens when we *do* implement for `u32` (outside of libcore)? I guess we get a standard overlap failure, huh? Seems ok.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Left a few nits but I think overall this is ok. I wonder if it will affect performance.

**Comment by FraGag** [comment]
@nikomatsakis Addressed nits. I'll squashed and rebase when it's approved.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@FraGag looks good =)

**Comment by FraGag** [comment]
@nikomatsakis Squashed and rebased. The merge conflicts were just line numbers in `.stderr` files being anonymized by #48449.

File: src/libcore/marker.rs [hunk 2]
```diff
@@ -565,3 +582,43 @@ unsafe impl<T: ?Sized> Freeze for *const T {}
...
+    }
+
+    impl_copy! {
+        usize u8 u16 u32 u64 u128
+        isize i8 i16 i32 i64 i128
+        f32 f64
+        bool char
+    }
+
+    #[stable(feature = "rust1", since = "1.0.0")]
```
Comment (nikomatsakis) [inline src/libcore/marker.rs]: I guess it doesn't matter, but `!` has not been present since `1.0.0`. In fact, the type itself isn't even stable yet!

**Review by nikomatsakis — COMMENTED** [review]
Can you change the 1.0.0 -- but to what...

**Comment by nikomatsakis** [comment]
OK, I updated to 1.25.0

**Comment by FraGag** [comment]
@nikomatsakis You had changed the version on `impl Clone for !` but not on `impl Copy for !`... I amended the commit to also change the latter. r?

**Comment by nikomatsakis** [comment]
@FraGag 

Sounds good, but travis is kind of unhappy:

https://travis-ci.org/rust-lang/rust/builds/348015686#L1092

Maybe something wrong with my change after all =)

**Comment by nikomatsakis** [comment]
I don't really know what error is about

**Comment by ollie27** [comment]
The stability attributes for the impls for `!` should be `#[unstable(feature = "never_type", issue = "35121")]` like the other impls for `!`.

**Comment by FraGag** [comment]
Oops, I forgot to `git add` before amending last time. Anyway, now both impls are marked unstable (squashed in the first commit).

@nikomatsakis r?

**Comment by FraGag** [comment]
I reproduced the test failure locally. The problem is that `iter::repeat` uses `Clone`, and I didn't put `#[inline]` on the implementations of `Clone::clone` that I added, so the compiler emitted calls to the `clone` method and this inhibited the optimization. I pushed a commit to add the missing `#[inline]` attributes (they really ought to be `#[inline]`!)

Why did this only fail on one platform though? I looked at the generated LLVM IR and I noticed that on `x86_64-unknown-linux-gnu`, even when the optimization didn't kick in, the IR still contained a call to `llvm.memset` to zero-initialize the `RawVec` in the `Vec`, which made the test pass erroneously. On `i686-pc-windows-gnu` though, the `RawVec` is zero-initialized with two `store` instructions instead, so there are indeed no occurrences of `llvm.memset`. I've updated the test to check for specific argument values on the `llvm.memset` call, and verified that it fails on `x86_64-unknown-linux-gnu` when the `#[inline]` attributes are missing.

@nikomatsakis r?

**Comment by nikomatsakis** [comment]
@FraGag nice digging!

**Comment by nikomatsakis** [comment]
Also, score one for tests.

**Comment by kennytm** [comment]
Cannot document `liblibc`. This crate is `#![cfg_attr(dox, no_core)]`.

```
[01:34:22] [m[m[32m[1m   Compiling[m compiler_builtins v0.0.0 (file:///checkout/src/rustc/compiler_builtins_shim)
[01:34:22] error[E0204]: the trait `Copy` may not be implemented for this type
[01:34:22]    --> rustc/libc_shim/../../liblibc/src/macros.rs:44:14
[01:34:22]     |
[01:34:22] 44  |           impl ::dox::Copy for $i {}
[01:34:22]     |                ^^^^^^^^^^^
[01:34:22]     | 
[01:34:22]    ::: rustc/libc_shim/../../liblibc/src/unix/mod.rs:19:1
[01:34:22]     |
[01:34:22] 19  | / s! {
[01:34:22] 20  | |     pub struct group {
[01:34:22] 21  | |         pub gr_name: *mut ::c_char,
[01:34:22]     | |         -------------------------- this field does not implement `Copy`
[01:34:22] 22  | |         pub gr_passwd: *mut ::c_char,
[01:34:22] ...   |
[01:34:22] 186 | |     }
[01:34:22] 187 | | }
[01:34:22]     | |_- in this macro invocation
```

**Comment by shepmaster** [comment]
Ping from triage, @FraGag ! Will you have time to address the issues soon?

**Comment by FraGag** [comment]
@shepmaster Yes, I'm working on it.

**Comment by pietroalbini** [comment]
@FraGag weekly ping from the triage team! What's the status on this?

**Comment by FraGag** [comment]
Now that https://github.com/rust-lang/libc/pull/951 has been merged and libc 0.2.40 published, I can progress.

I just rebased and tweaked my branch to account for the changes made in https://github.com/rust-lang/rust/pull/49299, which made some changes to the documentation for `Clone` and `Copy`, to avoid redundancy with the changes I had made previously and to remove now broken links to the unstable book (thanks to the linkchecker tool for catching these!).

@nikomatsakis r?

**Comment by shepmaster** [comment]
Ping from triage, @nikomatsakis !

**Review by nikomatsakis — APPROVED** [review]
