### PR TITLE
Stop compilation early if macro expansion failed

### LINKED ISSUE #116180: Error recovery after errors during macro expansion is usually futile
### Code

```Rust
// https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=13d58799822d542a2c53296f715ac44c
macro_rules! define {
    (enum $name:ident) => {
        struct $name {}
    };
}

define! {
    struct Hello
}

fn main() {
    Hello;
}
```

### Current output

```Shell
error: no rules expected the token `struct`
 --> src/main.rs:8:5
  |
1 | macro_rules! define {
  | ------------------- when calling this macro
...
8 |     struct Hello
  |     ^^^^^^ no rules expected this token in macro call
  |
note: while trying to match `enum`
 --> src/main.rs:2:6
  |
2 |     (enum $name:ident) => {
  |      ^^^^

error[E0425]: cannot find value `Hello` in this scope
  --> src/main.rs:12:5
   |
12 |     Hello;
   |     ^^^^^ not found in this scope
```

### Desired output

```Shell
error: no rules expected the token `struct`
 --> src/main.rs:8:5
  |
1 | macro_rules! define {
  | ------------------- when calling this macro
...
8 |     struct Hello
  |     ^^^^^^ no rules expected this token in macro call
  |
note: while trying to match `enum`
 --> src/main.rs:2:6
  |
2 |     (enum $name:ident) => {
  |      ^^^^
```

### Rationale and extra context

This is a concrete example, but the problem is very general. When macro expansion goes wrong, _anything_ might have not happened as a result, for example defining types and other things. In my experience, this frequently causes cascading useless errors, mostly but not exclusively from name resolution. This makes it very hard to work with the output of `cargo check` when dealing with macro expansion errors in my experience.

We should, when there are errors during macro expansion, abort compilation after macro expansion without any further recovery. It's impossible to know which errors are actually useful and in many cases there are a lot of useless ones.

With errors during macro expansion I mean any errors that stop macros from being expanded, for example matching mismatches or macros not being found.

Note that errors _before_ macro expansion, like parser errors, tend to be fairly recoverable and we should still do recovery on them, this is specifically about the case where the error count _increases during macro expansion_.

### Other cases

_No response_

### Anything else?

cc @rust-lang/wg-diagnostics

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes rust-lang/rust#116180.

So there isn't really a type that is central for macro expansion and some errors are actually emitted (because the resolution happens after the expansion I suppose) after the expansion pass (like "not found macro"). Sometimes, errors are only emitted on the second "try" (to improve error output). So I couldn't reach a similar solution than what was done in https://github.com/rust-lang/rust/pull/133937 and suggested by @estebank in https://github.com/rust-lang/rust/issues/116180#issuecomment-3109468922. But maybe I missed something?

So in the end, I realized that there is method called every time (except one, described below) a macro error is actually emitted: `ExtCtxt::trace_macros_diag`. Considering I updated what it did, I renamed it into `macro_error_and_trace_macros_diag` to better reflect it.

There is only one call of `trace_macros_diag` which isn't reporting an error but just used for `macro_trace` feature, so I kept it as is.

r? @oli-obk

### CODE REVIEW

File: tests/ui/editions/edition-keywords-2018-2015-2.rs [hunk 1]
```diff
@@ -0,0 +1,5 @@
+//@ edition:2018
+
+fn main() {
+    let _recovery_witness: () = 0; //~ ERROR mismatched types
+}
```
Comment (estebank) [inline tests/ui/editions/edition-keywords-2018-2015-2.rs]: The point of this was to ensure that the other test would continue emitting errors after the previous errors, so it is not needed as its own file.

File: tests/ui/editions/edition-keywords-2018-2015-parsing.rs [hunk 2]
```diff
@@ -25,8 +25,6 @@ pub fn check_async() {
     if passes_tt!(r#async) == 1 {} // OK
     module::async(); //~ ERROR expected identifier, found keyword `async`
     module::r#async(); // OK
-
-    let _recovery_witness: () = 0; //~ ERROR mismatched types
```
Comment (estebank) [inline tests/ui/editions/edition-keywords-2018-2015-parsing.rs]: We can leave this in and change the comment to be `// not emitted because of the macro parsing error`.

File: tests/ui/editions/edition-keywords-2018-2015-2.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply tests/ui/editions/edition-keywords-2018-2015-2.rs]: Fine by me!

**Comment by GuillaumeGomez** [comment]
Removed split ui tests to trigger old errors but in separate files.

File: tests/ui/const-generics/min_const_generics/macro-fail.rs [hunk 3]
```diff
@@ -35,9 +32,7 @@ fn main() {
   }>;
 
   let _fail = Example::<external_macro!()>;
-  //~^ ERROR: type provided when a constant
 
   let _fail = Example::<gimme_a_const!()>;
-  //~^ ERROR unexpected end of macro invocation
-  //~| ERROR: type provided when a constant was expected
+  //~^ ERROR: unexpected end of macro invocation
```
Comment (oli-obk) [inline tests/ui/const-generics/min_const_generics/macro-fail.rs:37]: while this one correctly silences the other errors, we want to test the other `gimme_a_const` invocations. I think you can just remove this line, considering we have other tests laready emitting the `unexpected end of macro invocation` error

Comment (oli-obk) [reply tests/ui/const-generics/min_const_generics/macro-fail.rs:37]: yea, except for this one the tests look good to me, excited to try it out on large code bases

Comment (GuillaumeGomez) [reply tests/ui/const-generics/min_const_generics/macro-fail.rs:37]: Moved these parts in `tests/ui/const-generics/min_const_generics/macro-fail-const.rs`.

**Review by oli-obk — APPROVED** [review]

File: compiler/rustc_interface/src/passes.rs [hunk 4]
```diff
@@ -206,7 +206,15 @@ fn configure_and_expand(
...
         ecx.num_standard_library_imports = num_standard_library_imports;
         // Expand macros now!
-        let krate = sess.time("expand_crate", || ecx.monotonic_expander().expand_crate(krate));
+        let (krate, nb_macro_errors) = sess.time("expand_crate", || {
+            let mut expander = ecx.monotonic_expander();
+            let krate = expander.expand_crate(krate);
+            (krate, ecx.nb_macro_errors)
+        });
+
+        if nb_macro_errors > 0 {
```
Comment (oli-obk) [inline compiler/rustc_interface/src/passes.rs]:
```suggestion
            krate
        });

        if ecx.nb_macro_errors > 0 {
```

I think? there's nothing special about the `ecx` within the `time` call.

**Comment by oli-obk** [comment]
r=me with nit (should allow reverting the changes to the `time`d closure)

File: compiler/rustc_interface/src/passes.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply compiler/rustc_interface/src/passes.rs]: Felt like "more contained" but yeah, I was it was too much. ^^'

**Comment by GuillaumeGomez** [comment]
Got the handle wrong...

@bors r=oli-obk

**Comment by GuillaumeGomez** [comment]
Failed in https://github.com/rust-lang/rust/pull/144450.

**Comment by GuillaumeGomez** [comment]
Just in case.

@bors try

File: compiler/rustc_interface/src/passes.rs [hunk 5]
```diff
@@ -206,7 +206,15 @@ fn configure_and_expand(
         let mut ecx = ExtCtxt::new(sess, cfg, resolver, Some(&lint_store));
         ecx.num_standard_library_imports = num_standard_library_imports;
         // Expand macros now!
-        let krate = sess.time("expand_crate", || ecx.monotonic_expander().expand_crate(krate));
+        let krate = sess.time("expand_crate", || {
+            let mut expander = ecx.monotonic_expander();
+            let krate = expander.expand_crate(krate);
+            krate
+        });
```
Comment (oli-obk) [inline compiler/rustc_interface/src/passes.rs]: Revert the diff above

Comment (GuillaumeGomez) [reply compiler/rustc_interface/src/passes.rs]: Missed this one, thanks!

File: tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs [hunk 6]
```diff
@@ -4,18 +4,19 @@
...
-    ($ty:ty) => { compile_error!("ty"); };
-    //~^ ERROR ty
-    //~| ERROR ty
-    (impl $c:ident Trait) => {};
-    (dyn $c:ident Trait) => {};
+    (impl $c:ident Trait) => { impl $c Trait {} };
+    //~^ ERROR inherent
+    //~| WARN trait objects without an explicit `dyn` are deprecated
+    //~| WARN this is accepted in the current edition
+    (dyn $c:ident Trait) => { dyn $c Trait {} }; //~ ERROR macro expansion
```
Comment (fmease) [inline tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs:14]: Wait what?? Wait, why was this modification made? That doesn't make any sense. This destroyed the original test intention.

This is an extremely carefully crafted test case.

File: tests/ui/traits/const-traits/macro-bare-trait-objects-const-trait-bounds.rs [hunk 7]
```diff
@@ -13,7 +13,7 @@ macro_rules! check {
         compile_error!("ty");
     };
     (const $Trait:path) => {};
-    ([const] $Trait:path) => {};
+    ([const] $Trait:path) => { [const] Trait };
```
Comment (fmease) [inline tests/ui/traits/const-traits/macro-bare-trait-objects-const-trait-bounds.rs:16]: Wait what?? Wait, why was this modification made? That doesn't make any sense. This destroyed the original test intention.

Comment (GuillaumeGomez) [reply tests/ui/traits/const-traits/macro-bare-trait-objects-const-trait-bounds.rs:16]: To keep the same error output, otherwise it was truncated. Sorry if I understood wrongly what the test was checking...

File: tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs:14]: Same as previously: to keep an output as close as possible to the original because otherwise the new "early exit if the expansion macro failed" truncated the output.

Comment (fmease) [reply tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs:14]: I'm sorry but that's not how it should've been approached. These test cases are all about the macro matchers, it doesn't matter what the diagnostics look like, it's about MATCH vs. NO MATCH, so the ordering, amount of the matchers is extremely important. This changed the meaning of this test case.

For reference, tests like these were added (by me) to prevent (or demonstrate) regressions like the most recent https://github.com/rust-lang/rust/issues/146417, so it's important keep the coverage 1:1.

I'll restore the test intention in a sec.

Comment (GuillaumeGomez) [reply tests/ui/traits/const-traits/macro-const-trait-bound-theoretical-regression.rs:14]: Yeah I completely missed the point, my bad. Is there a way to add constraints on a test to prevent this situation from happening again in the future? Like move it into another testsuite maybe?
