### PR TITLE
Make sure to treat only param where clauses as inherent

### LINKED ISSUE #145185: Latest rustc tags `unused_imports` on trait imports spuriously
Copying from https://github.com/rust-lang/rust-clippy/issues/15442

### Summary

I honestly can't make heads or tails of why, but rustc is generating an `unused_imports` warning on some traits imports, but if you remove the import the build fails in several places.

### Reproducer

I honestly don't have a clue as to what the issue is here, so a minimal reproducer is hard.
https://github.com/lightningdevkit/rust-lightning/pull/4000 removes the allows that were previously in place, see the last commit.

```text
rustc stable
info: latest update on 2025-08-07, rust version 1.89.0 (29483883e 2025-08-04)
```

### PR DESCRIPTION
**Pull request by compiler-errors**
See the description in the test file. 

This PR fixes a bug introduced by rust-lang/rust#141333, where we considered non-`Param` where clauses to be "inherent" for the purpose of method probing, which leads to both changes in method ambiguity (see test) and also import usage linting (and thus fixes https://github.com/rust-lang/rust/issues/145185).

r? @lcnr

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/probe.rs [hunk 1]
```diff
@@ -1945,6 +1945,29 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
                     );
                     (xform_self_ty, xform_ret_ty) =
                         self.xform_self_ty(probe.item, trait_ref.self_ty(), trait_ref.args);
+
+                    if matches!(probe.kind, WhereClauseCandidate(_)) {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/method/probe.rs:1953]: We could fast path this for the old trait solver, since we expect things to be normalized always.

**Comment by compiler-errors** [comment]
@bors2 try @rust-timer queue

I also want to crater this since it may cause some code to fail due to new ambiguity and missing imports.

**Comment by traviscross** [comment]
Given that there was an accidental stabilization here and that we'll be accepting a breaking change to take it back, let go ahead and nominate for review.

@rustbot labels +I-lang-nominated

It hasn't been out there long, but it is particularly the kind of thing that would be easy for people to unknowingly rely on.

In fact, I'm going to go ahead kick off the FCP because I don't suspect the crater run is going to tell us very much.  The release has been out for less than a week.  Most of the people who are going to accidentally rely on this probably haven't done so yet -- they'll do it after we land this but before we release it and they adopt that release.

@rfcbot fcp merge

**Comment by traviscross** [comment]
Interestingly, the accidental stabilization didn't cause all non-param WCs to be treated as "inherent".  I'd be curious to know what defined the exact edges of this.  E.g.:

```rust
use core::ops::Deref;
mod m {
    pub trait TrA { fn f(&self); }
}

fn g1<T: Deref<Target: m::TrA> + Deref<Target = U>, U>(x: &T::Target) {
    x.f(); //~ OK
}

fn g2<T: Deref<Target: m::TrA>>(x: &T::Target) {
    x.f();//~ ERROR
}

fn g3<T: Deref<Target: m::TrA> + Deref<Target = U>, U>(x: T) {
    x.f(); //~ OK
}

fn g4<T: Deref<Target: m::TrA>>(x: T) {
    x.f(); //[v1.89]~ OK
}
```

One would kind of expect `g2` to be accepted under the same reasoning that `g4` is, but it's not.

**Comment by compiler-errors** [comment]
It's just autoderefs that start *from^ param types that are treated as inherent. In g4 we do not start with a param type and deref it.

File: tests/ui/methods/rigid-alias-bound-is-not-inherent.rs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+// We were using `DeepRejectCtxt` to ensure that `assemble_inherent_candidates_from_param`
+// did not rely on the param-env being eagerly normalized. Since aliases unify with all
+// types, this meant that a rigid param-env candidate like `<T as Deref>::Target: Trait1`
+// would be registered as a "WhereClauseCandidate", which is treated as inherent. Since
+// we evaluate these candidates for all self types in the deref chain, this candidate
+// would be satisfied for `<T as Deref>::Target`, meaning that it would be preferred over
+// an "extension" candidate like `<T as Deref>::Target: Trait2` even though it holds.
+// This is problematic, since it causes ambiguities to be broken somewhat arbitrarily.
+// And as a side-effect, it also caused our computation of "used" traits to be miscalculated
+// since inherent candidates don't count as an import usage.
```
Comment (lcnr) [inline tests/ui/methods/rigid-alias-bound-is-not-inherent.rs:16]: also test with new solver?

File: compiler/rustc_hir_typeck/src/method/probe.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1953]: hm :thinking: 

so what's going on is:
- if the *normalized* self type is a param we `assemble_inherent_candidates_from_param`
- this uses fast-reject in an attempt to filter to where-clauses which only apply for the self type
  - doesn't handle unnormalized where-clauses or alias self types

We can't normalize in assembly because it doesn't use a probe, so we instead do it here. This totally makes sense to me, r=me on this impl

Can you add a comment to `assemble_inherent_candidates_from_param` that we only filter the `bounds` as an fast-path optimization and we properly reject non-param self type where-clauses in `consider_probe`?

**Review by lcnr — COMMENTED** [review]
> This code compiles on 1.89.0. But it doesn't compile on 1.88.0, and doesn't compile with this PR. Is this intended? I don't think the test checks for this case properly.
> 
> ```rust
> pub mod module {
>     pub trait Trait {
>         fn method(&self);
>     }
> }
> 
> // No import of Trait
> use std::ops::Deref;
> 
> pub fn foo(x: impl Deref<Target: module::Trait>) {
>     x.method();
> }
> ```

I would personally like to see this test in our test suite as well. It feels clearer to me what this is testing compared to relying on preference between candidates :thinking:

File: compiler/rustc_hir_typeck/src/method/probe.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1953]: actually, move this `structurally_normalize_ty` above the `xform` and then use the normalized `ty` in `xform_self_ty`? This should avoid some work given that this change seems to actually impact perf in the new solver

**Comment by lcnr** [comment]
As a procedural comment, I believe the types team should have been involved in the FCP.

I personally would have liked to have it be fully the responsibility of the types team given that it's a subtle detail/bug of the method selection/type checking. But it does feel *user facing* enough that I think T-lang also being involved is correct.

I don't think this change is significant or contentious enough to necessarily require a new FCP, so this comment only serves as a "I don't want the T-types to lose ownership of method selection going forward".

**Comment by jackh726** [comment]
> As a procedural comment, I believe the types team should have been involved in the FCP.
> 
> I personally would have liked to have it be fully the responsibility of the types team given that it's a subtle detail/bug of the method selection/type checking. But it does feel _user facing_ enough that I think T-lang also being involved is correct.

My feeling here is this is *wholly* in the responsibility of T-types, given that this is 1) an accidental implementation bug, not intended behavior 2) very much dependent on implementation details 3) a localized change in behavior that doesn't overall effect how users write Rust.

**Comment by compiler-errors** [comment]
Frankly, if the crater run is clean I feel like this shouldn't even need an FCP, but even if an FCP does follow through, I'd like to make it (perhaps redundantly) clear that this is *not* about whether we want this behavior, but whether or not we're okay with the breakage. As TC said above,

> But, of course, if we do, we should do so intentionally.

**Comment by jackh726** [comment]
Yeah, I'm on the fence on if it needs an FCP. I think my feeling is a types FCP is probably appropriate, but doesn't need to wait the 10 day FCP (given we likely want to land this sooner rather than later).

**Comment by traviscross** [comment]
Agreed about adding types here.  Let's dual FCP it.  We'll include as part of the FCP proposal waiving the final comment period.

@rfcbot cancel

**Comment by joshtriplett** [comment]
:+1: for rolling back the *accidental* change, and :+1: for evaluating in the future whether there's any *intentional* change we want to make here.

**Comment by compiler-errors** [comment]
sg2m, also beta nominating for the same reason

**Comment by traviscross** [comment]
The failures are all spurious, but as mentioned, the signal is low here.

**Comment by lcnr** [comment]
please also add more tests
```rust
use std::ops::Deref;
trait Trait1 {
    fn call_me(&self) {}
}
impl<T> Trait1 for T {}
trait Trait2 {
    fn call_me(&self) {}
}
impl<T> Trait2 for T {}

pub fn foo<T, U>(x: T)
where
    T: Deref<Target = U>,
    U: Trait1,
{
    // This should be ambiguous. The fact that there's an inherent where-bound
    // candidate for `U` should not impact the candidates for `T`
    x.call_me();
}
```

File: compiler/rustc_hir_typeck/src/method/probe.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1953]: I don't see how moving it would change things for the better here, and it makes the structure kinda worse, so I'm not going to do this. I'm happy to review the change if you'd like to make a follow-up.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/method/probe.rs:1953]: My theory here is that the perf improvement derives from us pruning candidates with this check that would otherwise need to do unnecessary work below.

Maybe structurally normalizing eagerly here would mean we wouldn't normalize when proving things in the un-pruned (i.e. actually param) candidates, but I didn't want to tangle those changes into this PR.
