### PR TITLE
Fix incorrect type mismatch label pointing at return type

### LINKED ISSUE #46302: Incorrect type mismatch label pointing at return type
[The following code](https://play.rust-lang.org/?gist=a769cdbe3ec35523fc02633ab0eec3a2&version=stable):

```rust
fn main() { //~ NOTE expected `()` because of default return type
  let s = "abc";
  let u: &str = if true { s[..2] } else { s };
}
```

has an incorrect label:

```
error[E0308]: mismatched types
 --> src/main.rs:3:27
  |
1 | fn main() { //~ NOTE expected `()` because of default return type
  |           - expected `()` because of default return type
2 |   let s = "abc";
3 |   let u: &str = if true { s[..2] } else { s };
  |                           ^^^^^^ expected &str, found str
  |
  = note: expected type `&str`
             found type `str`
```

### PR DESCRIPTION
**Pull request by estebank**
CC #46302.

### CODE REVIEW

**Comment by arielb1** [comment]
This is still wrong in a case such as this:
```Rust
fn main() {
    let x = 0;
    match x {
        _ => {
            4
        }
    }
    println!("hi!");
}
```

I would prefer to have a tag on the expectation that it comes from a default return type.

**Comment by estebank** [comment]
Reopening as although it is imperfect I want to reduce the incidence of incorrect hints.

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -4595,21 +4595,23 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                                     format!("-> {} ",
                                             self.resolve_type_vars_with_obligations(found)));
             }
-            (&hir::FunctionRetTy::DefaultReturn(span), false, true) => {
+            (&hir::FunctionRetTy::DefaultReturn(span), false, true, true) => {
                 err.span_label(span, "possibly return type missing here?");
             }
-            (&hir::FunctionRetTy::DefaultReturn(span), _, _) => {
+            (&hir::FunctionRetTy::DefaultReturn(span), _, false, true) => {
                 // `fn main()` must return `()`, do not suggest changing return type
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/mod.rs]: Note that this is not *strictly* true anymore -- `main` *can* return other types!

**Review by nikomatsakis — APPROVED** [review]

**Comment by kennytm** [comment]
Legit, UI test not up-to-date.

```
---- [ui] ui\suggestions\issue-46302.rs stdout ----
diff of stderr:
2	  --> $DIR/issue-46302.rs:13:27
3	   |
4	LL |   let u: &str = if true { s[..2] } else { s };
-	   |                           ^^^^^^ expected &str, found str
+	   |                           ^^^^^^
+	   |                           |
+	   |                           expected &str, found str
+	   |                           help: consider borrowing here: `&s[..2]`
6	   |
7	   = note: expected type `&str`
8	              found type `str`
```

**Comment by estebank** [comment]
@kennytm very recent change, updated.

@bors r=nikomatsakis
