### PR TITLE
rustc: introduce {ast,hir}::AnonConst to consolidate so-called "embedded constants".

### LINKED ISSUE #48838: assign a Closure in Enum
Compiler say it's a bug :note: the compiler unexpectedly panicked. this is a bug.

I tried this code:
```
fn main() {
    
    let x:i32 = "0".parse().unwrap();

    let square = Functions::Square;

    println!("x square is {}", square(x));

}

enum Functions{
    Square = |x:i32|{x*x},
}
```

## Meta
```
 Compiling advanced_function v0.1.0 (file:///C:/Users/tt/IdeaProjects/advanced_function)
error: internal compiler error: src\librustc_typeck\check\mod.rs:820: can't type-check body of DefId(0/0:4 ~ advanced_function[1c36]::Functions[0])
  --> src\main.rs:13:1
   |
13 | / enum Functions{
14 | |     Square = |x:i32|{x*x},
15 | | }
   | |_^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.1 (d3ae9a9e0 2018-02-27) running on x86_64-pc-windows-msvc

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:451:9
stack backtrace:
   0: <std::sync::condvar::WaitTimeoutResult as core::fmt::Debug>::fmt
   1: <std::time::SystemTimeError as core::fmt::Display>::fmt
   2: std::panicking::Location::column
   3: std::panicking::Location::column
   4: std::panicking::rust_panic_with_hook
   5: <rustc_typeck::check::method::probe::ProbeScope as core::fmt::Debug>::fmt
   6: <rustc_typeck::constrained_type_params::Parameter as core::fmt::Debug>::fmt
   7: <rustc::hir::Arm as rustc_typeck::check::coercion::AsCoercionSite>::as_coercion_site
   8: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::nested_visit_map
   9: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  10: <rustc_typeck::check::CheckItemTypesVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeVisitor<'tcx>>::visit_item
  11: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure
  12: rustc::dep_graph::graph::DepGraph::in_ignore
  13: rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::Predicate<'tcx>>::fmt
  14: <rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx> as rustc::ty::layout::HasTyCtxt<'gcx>>::tcx
  15: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  17: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  18: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  19: <rustc_typeck::check::CheckItemTypesVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeVisitor<'tcx>>::visit_item
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure
  21: rustc::dep_graph::graph::DepGraph::in_ignore
  22: rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::Predicate<'tcx>>::fmt
  23: <rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx> as rustc::ty::layout::HasTyCtxt<'gcx>>::tcx
  24: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  26: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  27: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  28: rustc_mir::interpret::const_eval::const_eval_provider
  29: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::ensure
  30: rustc::dep_graph::graph::DepGraph::in_ignore
  31: rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::Predicate<'tcx>>::fmt
  32: <rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx> as rustc::ty::layout::HasTyCtxt<'gcx>>::tcx
  33: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::ensure
  34: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::try_get
  35: rustc::ty::maps::TyCtxtAt::const_eval
  36: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  37: <unknown>
  38: rustc_typeck::check_crate
  39: rustc_driver::profile::dump
  40: rustc_driver::profile::dump
  41: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  42: rustc_driver::driver::compile_input
  43: rustc_driver::run_compiler
  44: rustc_driver::profile::dump
  45: _rust_maybe_catch_panic
  46: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  47: <std::sync::condvar::Condvar as core::fmt::Debug>::fmt
  48: std::sys::windows::thread::Thread::new
  49: BaseThreadInitThunk

error: Could not compile `advanced_function`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```

### LINKED ISSUE #50600: error: internal compiler error: librustc_typeck/check/mod.rs:851: can't type-check body of DefId(0/0:3 ~ rust_out[317d]::Foo[0])
Input:
```
struct Foo (
        fn([u8; |x: u8| { }])
);
```

Output:
```
$ rustc -
error[E0601]: `main` function not found in crate `rust_out`

error: internal compiler error: librustc_typeck/check/mod.rs:851: can't type-check body of DefId(0/0:3 ~ rust_out[317d]::Foo[0])
 --> <anon>:1:1
  |
1 | / struct Foo (
2 | |     fn([u8; |x: u8| { }])
3 | | );
  | |__^

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
             at librustc/util/common.rs:54
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic
             at /home/vegard/rust/src/libstd/panicking.rs:397
   7: rustc_errors::Handler::span_bug
             at /home/vegard/rust/src/<panic macros>:3
   8: rustc::session::opt_span_bug_fmt::{{closure}}
             at /home/vegard/rust/src/librustc/session/mod.rs:1279
   9: rustc::ty::context::tls::with_opt::{{closure}}
             at /home/vegard/rust/src/librustc/ty/context.rs:1943
  10: rustc::ty::context::tls::with_context_opt
             at /home/vegard/rust/src/librustc/ty/context.rs:1880
  11: rustc::ty::context::tls::with_opt
             at /home/vegard/rust/src/librustc/ty/context.rs:1943
  12: rustc::session::opt_span_bug_fmt
             at /home/vegard/rust/src/librustc/session/mod.rs:1276
  13: rustc::session::span_bug_fmt
             at /home/vegard/rust/src/librustc/session/mod.rs:1267
  14: rustc_typeck::check::typeck_tables_of::{{closure}}
             at librustc_typeck/check/mod.rs:851
  15: rustc_typeck::check::typeck_tables_of
             at /home/vegard/rust/src/libcore/option.rs:376
             at librustc_typeck/check/mod.rs:850
  16: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/ty/maps/plumbing.rs:723
             at librustc/dep_graph/graph.rs:343
  17: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/dep_graph/graph.rs:209
             at librustc/ty/maps/plumbing.rs:530
             at librustc/ty/maps/plumbing.rs:200
             at librustc/ty/context.rs:1844
             at librustc/ty/context.rs:1787
             at librustc/ty/context.rs:1843
             at librustc/ty/maps/plumbing.rs:199
             at librustc/ty/context.rs:1905
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1880
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1900
             at librustc/ty/maps/plumbing.rs:189
             at librustc/ty/maps/plumbing.rs:523
  18: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/maps/plumbing.rs:372
             at librustc/ty/maps/plumbing.rs:599
             at librustc/ty/maps/plumbing.rs:606
  19: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
             at librustc/ty/maps/plumbing.rs:776
             at librustc/ty/maps/plumbing.rs:769
  20: rustc_typeck::check::typeck_tables_of
             at librustc_typeck/check/mod.rs:843
  21: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/ty/maps/plumbing.rs:723
             at librustc/dep_graph/graph.rs:343
  22: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/dep_graph/graph.rs:209
             at librustc/ty/maps/plumbing.rs:530
             at librustc/ty/maps/plumbing.rs:200
             at librustc/ty/context.rs:1844
             at librustc/ty/context.rs:1787
             at librustc/ty/context.rs:1843
             at librustc/ty/maps/plumbing.rs:199
             at librustc/ty/context.rs:1905
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1880
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1900
             at librustc/ty/maps/plumbing.rs:189
             at librustc/ty/maps/plumbing.rs:523
  23: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/maps/plumbing.rs:372
             at librustc/ty/maps/plumbing.rs:599
             at librustc/ty/maps/plumbing.rs:606
  24: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
             at librustc/ty/maps/plumbing.rs:776
             at librustc/ty/maps/plumbing.rs:769
  25: rustc_mir::interpret::const_eval::const_eval_provider
             at librustc_mir/interpret/const_eval.rs:447
  26: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/ty/maps/plumbing.rs:723
             at librustc/dep_graph/graph.rs:343
  27: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/dep_graph/graph.rs:209
             at librustc/ty/maps/plumbing.rs:530
             at librustc/ty/maps/plumbing.rs:200
             at librustc/ty/context.rs:1844
             at librustc/ty/context.rs:1787
             at librustc/ty/context.rs:1843
             at librustc/ty/maps/plumbing.rs:199
             at librustc/ty/context.rs:1905
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1880
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1900
             at librustc/ty/maps/plumbing.rs:189
             at librustc/ty/maps/plumbing.rs:523
  28: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
             at librustc/ty/maps/plumbing.rs:372
             at librustc/ty/maps/plumbing.rs:599
  29: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_const
             at librustc/ty/maps/plumbing.rs:606
             at librustc/ty/maps/plumbing.rs:776
             at librustc/ty/maps/plumbing.rs:769
             at librustc/traits/project.rs:436
  30: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
             at librustc/ty/structural_impls.rs:1176
             at librustc/ty/structural_impls.rs:857
             at librustc/traits/project.rs:346
  31: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::Slice<&'tcx rustc::ty::TyS<'tcx>>>::super_fold_with
             at librustc/ty/structural_impls.rs:890
             at librustc/ty/structural_impls.rs:776
             at /home/vegard/rust/src/libcore/ops/function.rs:271
             at /home/vegard/rust/src/libcore/option.rs:404
             at /home/vegard/rust/src/libcore/iter/mod.rs:1347
             at /home/vegard/rust/src/librustc_data_structures/array_vec.rs:197
             at /home/vegard/rust/src/librustc_data_structures/accumulate_vec.rs:113
             at /home/vegard/rust/src/libcore/iter/iterator.rs:1375
             at librustc/ty/structural_impls.rs:776
  32: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
             at librustc/ty/fold.rs:58
             at librustc/macros.rs:287
             at librustc/ty/fold.rs:58
             at librustc/ty/structural_impls.rs:735
             at librustc/ty/sty.rs:691
             at librustc/ty/sty.rs:685
             at librustc/ty/structural_impls.rs:735
             at librustc/ty/fold.rs:137
             at librustc/ty/structural_impls.rs:739
             at librustc/ty/structural_impls.rs:866
             at librustc/traits/project.rs:346
  33: rustc_typeck::check::Inherited::normalize_associated_types_in
             at /home/vegard/rust/src/librustc/ty/structural_impls.rs:890
             at /home/vegard/rust/src/librustc/traits/project.rs:324
             at /home/vegard/rust/src/librustc/traits/project.rs:283
             at /home/vegard/rust/src/librustc/traits/project.rs:267
             at /home/vegard/rust/src/librustc/infer/mod.rs:1358
             at librustc_typeck/check/mod.rs:677
  34: rustc_typeck::check::wfcheck::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::non_enum_variant
             at librustc_typeck/check/mod.rs:2075
             at librustc_typeck/check/wfcheck.rs:721
             at /home/vegard/rust/src/libcore/ops/function.rs:271
             at /home/vegard/rust/src/libcore/option.rs:404
             at /home/vegard/rust/src/libcore/iter/mod.rs:1347
             at /home/vegard/rust/src/liballoc/vec.rs:1883
             at /home/vegard/rust/src/liballoc/vec.rs:1866
             at /home/vegard/rust/src/liballoc/vec.rs:1752
             at /home/vegard/rust/src/libcore/iter/iterator.rs:1375
             at librustc_typeck/check/wfcheck.rs:718
  35: rustc_typeck::check::wfcheck::check_item_well_formed
             at librustc_typeck/check/wfcheck.rs:121
             at librustc_typeck/check/wfcheck.rs:233
             at librustc_typeck/check/wfcheck.rs:49
             at librustc_typeck/check/mod.rs:617
             at /home/vegard/rust/src/librustc/infer/mod.rs:453
             at /home/vegard/rust/src/librustc/ty/context.rs:1578
             at /home/vegard/rust/src/librustc/ty/context.rs:1844
             at /home/vegard/rust/src/librustc/ty/context.rs:1787
             at /home/vegard/rust/src/librustc/ty/context.rs:1843
             at /home/vegard/rust/src/librustc/ty/context.rs:1577
             at /home/vegard/rust/src/librustc/ty/context.rs:1905
             at /home/vegard/rust/src/librustc/ty/context.rs:1889
             at /home/vegard/rust/src/librustc/ty/context.rs:1880
             at /home/vegard/rust/src/librustc/ty/context.rs:1889
             at /home/vegard/rust/src/librustc/ty/context.rs:1900
             at /home/vegard/rust/src/librustc/ty/context.rs:1570
             at /home/vegard/rust/src/librustc/infer/mod.rs:453
             at librustc_typeck/check/mod.rs:617
             at librustc_typeck/check/wfcheck.rs:47
             at librustc_typeck/check/wfcheck.rs:232
             at librustc_typeck/check/wfcheck.rs:120
  36: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/dep_graph/graph.rs:343
  37: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/dep_graph/graph.rs:209
             at librustc/ty/maps/plumbing.rs:530
             at librustc/ty/maps/plumbing.rs:200
             at librustc/ty/context.rs:1844
             at librustc/ty/context.rs:1787
             at librustc/ty/context.rs:1843
             at librustc/ty/maps/plumbing.rs:199
             at librustc/ty/context.rs:1905
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1880
             at librustc/ty/context.rs:1889
             at librustc/ty/context.rs:1900
             at librustc/ty/maps/plumbing.rs:189
             at librustc/ty/maps/plumbing.rs:523
  38: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/maps/plumbing.rs:372
             at librustc/ty/maps/plumbing.rs:599
             at librustc/ty/maps/plumbing.rs:606
  39: rustc::ty::maps::<impl rustc::ty::maps::queries::check_item_well_formed<'tcx>>::ensure
             at librustc/ty/maps/plumbing.rs:574
             at librustc/ty/maps/plumbing.rs:740
  40: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item
             at librustc_typeck/check/wfcheck.rs:684
  41: rustc_typeck::check_crate::{{closure}}
             at /home/vegard/rust/src/librustc/hir/itemlikevisit.rs:80
             at /home/vegard/rust/src/librustc/hir/mod.rs:711
             at librustc_typeck/check/mod.rs:695
             at /home/vegard/rust/src/librustc/session/mod.rs:318
             at librustc_typeck/check/mod.rs:693
             at librustc_typeck/lib.rs:340
  42: rustc_typeck::check_crate
             at /home/vegard/rust/src/librustc/util/common.rs:166
             at /home/vegard/rust/src/librustc/util/common.rs:160
             at librustc_typeck/lib.rs:340
  43: rustc::ty::context::TyCtxt::create_and_enter
             at librustc_driver/driver.rs:1121
             at /home/vegard/rust/src/librustc/ty/context.rs:1867
             at /home/vegard/rust/src/librustc/ty/context.rs:1844
             at /home/vegard/rust/src/librustc/ty/context.rs:1787
             at /home/vegard/rust/src/librustc/ty/context.rs:1843
             at /home/vegard/rust/src/librustc/ty/context.rs:1866
             at /home/vegard/rust/src/librustc/ty/context.rs:1833
             at /home/vegard/rust/src/libstd/thread/local.rs:294
             at /home/vegard/rust/src/libstd/thread/local.rs:248
             at /home/vegard/rust/src/librustc/ty/context.rs:1825
             at /home/vegard/rust/src/libstd/thread/local.rs:294
             at /home/vegard/rust/src/libstd/thread/local.rs:248
             at /home/vegard/rust/src/librustc/ty/context.rs:1817
             at /home/vegard/rust/src/librustc/ty/context.rs:1855
             at /home/vegard/rust/src/librustc/ty/context.rs:1299
  44: rustc_driver::driver::compile_input
             at librustc_driver/driver.rs:1095
             at librustc_driver/driver.rs:231
  45: rustc_driver::run_compiler
             at librustc_driver/lib.rs:540
             at librustc_driver/lib.rs:457
             at /home/vegard/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
             at /home/vegard/rust/src/libsyntax/lib.rs:97
             at /home/vegard/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
             at /home/vegard/rust/src/libsyntax/lib.rs:96
             at librustc_driver/lib.rs:456
  46: rustc_driver::monitor::{{closure}}
             at librustc_driver/lib.rs:1684
             at librustc_driver/lib.rs:174
             at librustc_driver/lib.rs:1598
  47: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  48: rustc_driver::run
             at /home/vegard/rust/src/libstd/panicking.rs:289
             at /home/vegard/rust/src/libstd/panic.rs:374
             at librustc_driver/lib.rs:1530
             at librustc_driver/lib.rs:1597
             at librustc_driver/lib.rs:173
  49: rustc_driver::main
             at librustc_driver/lib.rs:1677
  50: std::rt::lang_start::{{closure}}
             at /home/vegard/rust/src/libstd/rt.rs:74
  51: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  52: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  53: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  54: main
  55: __libc_start_main
  56: _start
query stack during panic:
#0 [typeck_tables_of] processing `Foo`
#1 [typeck_tables_of] processing `Foo::{{closure}}`
#2 [const_eval] const-evaluating `Foo::{{closure}}`
#3 [check_item_well_formed] processing `Foo`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-dev running on x86_64-unknown-linux-gnu
```

Running on commit c166b0386888b253313e1e7e982a2a06cadaac8b.

### LINKED ISSUE #50688: Closure in repeat expression causes cyclic dependency error
The following code:
```rust
fn main() { 
    [1;  || {} ];
}
```
Will give a cyclic query dependency error between checking `main` and const-evaluating the closure,  but if you use `[1; { || {} } ]` then you get a proper type checking error.

### LINKED ISSUE #50689: Closures in enum discriminants error when they shouldn't
We'd like
```rust
enum Functions {
    Square = (|x:i32| { }, 42).1,
}
```
to work but it doesn't. #50623 makes the error less bad but still doesn't work. Issue #50688 seems related.

### PR DESCRIPTION
**Pull request by eddyb**
Previously, constants in array lengths and enum variant discriminants were "merely an expression", and had no separate ID for, e.g. type-checking or const-eval, instead reusing the expression's.

That complicated code working with bodies, because such constants were the only special case where the "owner" of the body wasn't the HIR parent, but rather the same node as the body itself.
Also, if the body happened to be a closure, we had no way to allocate a `DefId` for both the constant *and* the closure, leading to *several* bugs (mostly ICEs where type errors were expected).

This PR rectifies the situation by adding another (`{ast,hir}::AnonConst`) node around every such constant. Also, const generics are expected to rely on the new `AnonConst` nodes, as well (cc @varkor).
* fixes #48838
* fixes #50600
* fixes #50688
* fixes #50689
* obsoletes #50623

r? @nikomatsakis

### CODE REVIEW

File: src/libsyntax/ast.rs [hunk 1]
```diff
@@ -1857,7 +1866,7 @@ pub struct Variant_ {
     pub attrs: Vec<Attribute>,
     pub data: VariantData,
     /// Explicit discriminant, e.g. `Foo = 1`
-    pub disr_expr: Option<P<Expr>>,
+    pub disr_expr: Option<Const>,
```
Comment (petrochenkov) [inline src/libsyntax/ast.rs]: It's a bit strange that `const` and `static` initializers are not treated as `Const` and not visited by `fn visit_const`, for example, despite being same "constant single-expression bodies".

Comment (petrochenkov) [reply src/libsyntax/ast.rs]: Is it *necessary* to introduce `Const` in AST, btw?
New node ids can be assigned during lowering to HIR too.

(I see that some stuff in resolve becomes shorted, but I haven't looked in detail yet.)

Comment (eddyb) [reply src/libsyntax/ast.rs]: Those have items (or trait/impl associated items) they're directly attached to, so they don't need any changes, but also changing them would complicate a bunch of logic that's straight-forward today and would have to jump through an extra hoop.

There's one potential exception to this, which is that `static` could be considered to be "more disjoint" from its initializer than `const` and separating them could allow better bookkeeping of the "allocation" vs "value the allocation is initialized with" (cc @oli-obk), but even then it seems a bit stretched.

I wanted to avoid calling the type `EmbeddedConst` because it's long and potentially even more confusing, but if anyone has a better suggestion, it could use being more explicit.

Comment (oli-obk) [reply src/libsyntax/ast.rs]: the static vs its value won't get easier by changing this. Miri's bookkeeping about that is completely sane now.

Comment (eddyb) [reply src/libsyntax/ast.rs]: > Is it necessary to introduce `Const` in AST, btw?
> New node ids can be assigned during lowering to HIR too.

Sadly, yes, because the `DefId` tree is built from the AST, and nodes inside a `Const` need to be parented by it in that tree (this is where some of the ICEs for closures came from).

File: src/librustc/hir/map/def_collector.rs [hunk 2]
```diff
@@ -129,30 +113,6 @@ impl<'a> visit::Visitor<'a> for DefCollector<'a> {
 
         self.with_parent(def, |this| {
             match i.node {
-                ItemKind::Enum(ref enum_definition, _) => {
```
Comment (nikomatsakis) [inline src/librustc/hir/map/def_collector.rs]: huzzah 🎉

File: src/libsyntax/ast.rs [hunk 3]
```diff
@@ -921,6 +921,15 @@ pub enum UnsafeSource {
     UserProvided,
 }
 
+/// A constant (expression) embedded inside a type, an expression,
+/// or used to define the discriminant value of an enum variant.
```
Comment (nikomatsakis) [inline src/libsyntax/ast.rs]: Maybe we should call this an `AnonymousConst` or something like that? This would address @petrochenkov's concern about const vs static items to some extent, since they are clearly not anonymous.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me once we settle [this bikeshed](https://github.com/rust-lang/rust/pull/50851#discussion_r189376131)

File: src/libsyntax/ast.rs (hunk 1 above)
Comment (petrochenkov) [reply src/libsyntax/ast.rs]: So, what criterion should a constant `Expr` satisfy to become `Const` then? No direct parent with `DefId`?
Discriminants in enums have a direct parent with `DefId` to which they are attached - the variant itself, in this sense I don't see how they are different from `const`s or `static`s. Is preferring `Const` just a matter of convenience in this case?
Could all this be documented in a comment for `Const`?

File: src/libsyntax/ast.rs (hunk 3 above)
Comment (petrochenkov) [reply src/libsyntax/ast.rs]: Yeah, `Const` seems too generic for this thing that has a very specific technical purpose rather than represents a constant expressions in general.

File: src/libsyntax/ast.rs (hunk 1 above)
Comment (petrochenkov) [reply src/libsyntax/ast.rs]: Also, expressions in range patterns have very similar properties to array sizes, etc - `THIS ... AND_THIS`, but I guess they don't need a body because you can't smuggle arbitrary expressions into them, paths at most.

Comment (eddyb) [reply src/libsyntax/ast.rs]: The criterion is a requirement of separate const-evaluation (which requires separate type-checking).

Array type lengths and enum discriminants don't have a parent body so they need a separate `DefId` and body to even be type-checked (array type lengths could have a `DefId` attached to the `NodeId` of the `TyArray`, but enum variants already have a `DefId` with a different meaning).

The count of an `ExprRepeat` is technically guaranteed to be nested inside another body, but type-checking the `ExprRepeat` requires const-evaluating the count, which currently can't be done without the count being a separate body.

In contrast, `const` and `static`

> Also, expressions in range patterns have very similar properties to array sizes

It might be a good idea to keep those separate too, but type-checking them could require inference from the outer body (because of associated consts), so it's tricky.

I think long-term we should perhaps keep such constant expressions (including ones from paths involving const generics, in the future), in a separate body *but* type-check them like closures (sharing the inference context of their parent body), while retaining the ability to const-eval them.

File: src/libsyntax/ast.rs (hunk 3 above)
Comment (eddyb) [reply src/libsyntax/ast.rs]: I was thinking of `ty::Const` when I picked the name, TBH, but that doesn't make as much sense in the AST/HIR.

I guess `AnonConst` would work pretty well, thanks!

File: src/libsyntax/ast.rs (hunk 1 above)
Comment (oli-obk) [reply src/libsyntax/ast.rs]: Oh. will this make the difference between a variant's discriminant and it's isize value clearer?

Comment (eddyb) [reply src/libsyntax/ast.rs]: > will this make the difference between a variant's discriminant and it's isize value clearer?

Doubful.
