### PR TITLE
Fix unuseful span in type error in some format_args!() invocations

### LINKED ISSUE #140578: Unuseful span in type error in some format_args!() invocations
The span of this error is useful:

```
error[E0282]: type annotations needed
  |
# |     println!("{:?}", []);
  |                      ^^ cannot infer type
  |
```

However, in a slightly more complicated println, the same error points at the entire macro invocation:

```
error[E0282]: type annotations needed
  |
# |     println!("{:?} {a} {a:?}", [], a = 1 + 1);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
  |
```

It should have just pointed at `[]` (or perhaps `{:?}`), rather than the entire macro call.

The simple println results in this case in format_args lowering: https://github.com/rust-lang/rust/blob/cb0d6e76d0515b19d249c0147d246296b9d3d124/compiler/rustc_ast_lowering/src/format.rs#L513-L520

The more complicated println results in this case in format_args lowering: https://github.com/rust-lang/rust/blob/cb0d6e76d0515b19d249c0147d246296b9d3d124/compiler/rustc_ast_lowering/src/format.rs#L538-L547

It'd be nice if both cases would cause any type/trait errors to be reported on the argument (or placeholders), instead of on the span of the entire macro invocation.

I'm not sure if this requires changes in rustc_ast_lowering, or in the code that reports the type errors.

### PR DESCRIPTION
**Pull request by moatom**
Fixed https://github.com/rust-lang/rust/issues/140578.

r? @m-ou-se

### CODE REVIEW

**Comment by moatom** [comment]
# Current Situation

Currently, my approach is to sort the candidates so that the error associated with the span of the later argument is selected:
https://github.com/rust-lang/rust/pull/140916/files#diff-eccdf22e4bc52ce30713fd36374bb637af1f5d233bf7f60bdf84a21de12dbe9fR163-R177


At first glance, this seems to resolve the span issue:

```rust
// a1.rs
fn main() {
  println!("{:?}", []);
}

// a2.rs
fn main() {
  println!("{:?} {a} {a:?}", [], a = 1 + 1);
}
```

```bash
$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc a1.rs
error[E0282]: type annotations needed
 --> a1.rs:2:20
  |
2 |   println!("{:?}", []);
  |                    ^^ cannot infer type
  |
  = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0282`.

$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc a2.rs
error[E0282]: type annotations needed
 --> a2.rs:2:30
  |
2 |   println!("{:?} {a} {a:?}", [], a = 1 + 1);
  |                              ^^ cannot infer type
  |
  = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0282`.
```



However, this approach is ad hoc and doesn't make sense. It seems necessary to limit the sorting targets to spans originating from the same `println` macro invocation:

```bash
$ ./x.py test --stage 1
...
failures:
    ...
    [ui] tests/ui/typeck/issue-7813.rs

test result: FAILED. 17957 passed; 23 failed; 168 ignored; 0 measured; 0 filtered out; finished in 301.39s

$ git --no-pager diff --no-index \
tests/ui/typeck/issue-7813.stderr \
<(./build/x86_64-unknown-linux-gnu/stage1/bin/rustc tests/ui/typeck/issue-7813.rs 2>&1)
```

```diff
diff --git a/tests/ui/typeck/issue-7813.stderr b/dev/fd/63
index 953cbd206dc..00000000000 100644
--- a/tests/ui/typeck/issue-7813.stderr
+++ b/dev/fd/63
@@ -1,13 +1,15 @@
 error[E0282]: type annotations needed for `&[_; 0]`
-  --> $DIR/issue-7813.rs:2:9
-   |
-LL |     let v = &[];
-   |         ^   --- type must be known at this point
-   |
+ --> tests/ui/typeck/issue-7813.rs:2:9
+  |
+2 |     let v = &[]; //~ ERROR type annotations needed
+  |         ^
+3 |     let it = v.iter();
+  |              - type must be known at this point
+  |
 help: consider giving `v` an explicit type, where the placeholders `_` are specified
-   |
-LL |     let v: &[_; 0] = &[];
-   |          +++++++++
+  |
+2 |     let v: &[_; 0] = &[]; //~ ERROR type annotations needed
+  |          +++++++++

 error: aborting due to 1 previous error
```



Is there any field or identifier (e.g., in the `obligation`) that can help determine whether a span originates from the same `println` macro invocation when reporting an E0282 error? The following message suggests that there might already be data indicating the origin of the macro invocation:

>   = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

If not, where would be the appropriate place to add such information? 🤔

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 1]
```diff
@@ -163,14 +163,26 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                if e.obligation.cause.span.macro_backtrace().next().is_some_and(
+                    |trace| match trace.kind {
+                        ExpnKind::Macro(_, name) => {
+                            name.as_str().rsplit("::").next() == Some("format_args_nl")
+                        }
+                        _ => false,
+                    },
+                ) =>
+            {
+                (-1, e.obligation.cause.span.index())
```
Comment (moatom) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:176]: 1. Is `-1` appropriate?
2. Is `span.index()` really an appropriate metric to prioritize arguments?

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 2]
```diff
@@ -163,14 +163,26 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
         // Ensure `T: Sized` and `T: WF` obligations come last. This lets us display diagnostics
         // with more relevant type information and hide redundant E0282 errors.
         errors.sort_by_key(|e| match e.obligation.predicate.kind().skip_binder() {
+            ty::PredicateKind::Subtype(_)
+                if e.obligation.cause.span.macro_backtrace().next().is_some_and(
+                    |trace| match trace.kind {
+                        ExpnKind::Macro(_, name) => {
+                            name.as_str().rsplit("::").next() == Some("format_args_nl")
```
Comment (moatom) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:170]: Should does this search `format_args` rather than `format_args_nl`?

**Review by moatom — COMMENTED** [review]
@m-ou-se Could you review it at your convenience?

**Comment by chenyukang** [comment]
@m-ou-se may be busy nowadays.
r? compiler

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs (hunk 2 above)
Comment (chenyukang) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:170]: I think we should not limit it only for `format_args_nl`, otherwise other macro such as `print!` will do not got right.

**Comment by chenyukang** [comment]
I tried to understand why adding a sort strategy could resolve the issue, but haven't figured out it yet.

maybe r? @compiler-errors  know what's going on here, since the logic of suppressing was written by him.

File: compiler/rustc_span/src/span_encoding.rs [hunk 3]
```diff
@@ -281,6 +281,16 @@ impl Span {
         }
     }
 
+    #[inline]
+    pub fn len(self) -> u32 {
+        (self.len_with_tag_or_marker & !PARENT_TAG) as u32
+    }
```
[the remark this answers is not in the document]
Comment (compiler-errors) [reply compiler/rustc_span/src/span_encoding.rs:287]: yeah, remove this pls

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 4]
```diff
@@ -163,14 +163,26 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
         // Ensure `T: Sized` and `T: WF` obligations come last. This lets us display diagnostics
         // with more relevant type information and hide redundant E0282 errors.
         errors.sort_by_key(|e| match e.obligation.predicate.kind().skip_binder() {
+            ty::PredicateKind::Subtype(_)
+                if e.obligation.cause.span.macro_backtrace().next().is_some_and(
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:167]: I think this can be simplified with some other method like `span.parent` or `span.expn_kind` or something? Look on the span type for relevant functions, b/c using `backtrace.next` smells wrong 🤔

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs (hunk 1 above)
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:176]: you could use an enum with `PartialOrd` implemented on it to give these ordering precedences a name, or bump everything +1.

Comment (compiler-errors) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:176]: span.index seems strange...

Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:176]: @compiler-errors 
I now understand the relevant rustc code better!
Instead of using `-span.index`, it seems better to sort by `-e.obligation.cause.span.data().lo`, or by:
```rust
let sm = self.tcx.sess.source_map();
let bpos = e.obligation.cause.span.data().lo
let fbpos = sm.lookup_byte_offset(bpos);
let line_col_dcol = fbpos.sf.lookup_file_pos_with_col_display(fbpos.pos);
-line_col_dcol.1
```


However, this approach also seems to have a problem.

For the following span:
```rust
2 |   print!("{:?} {a} {a:?}", [], a = 1 + 1);
  |                            ^^ cannot infer type
```
the captured values during sorting are `bpos=BytePos(52)`, `line_col_dcol.0=2`, and `line_col_dcol.1=CharPos(27)`.

On the other hand, for the following span:
```rust
2 |   print!("{:?} {a} {a:?}", [], a = 1 + 1);
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
```
the captured values during sorting are `bpos=BytePos(191660)`, `line_col_dcol.0=374`, and `line_col_dcol.1=CharPos(4294769381)`.

Thus, the later span is mistakenly reported as the error in the above approach.
Is this `BytePos` value (`BytePos(191660)`) even correct in the first place?

Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: > Is this BytePos(191660) just completely wrong? Could this be a bug in the lookup_file_pos_with_col_display method?

I found out that `lookup_file_pos_with_col_display` reports the location within the macro-expanded virtual file. In contrast, `lookup_char_pos` appears to provide the correct location in the original source file. 🤔

**Comment by moatom** [comment]
@compiler-errors (CC @chenyukang)
Thank you for taking the time to review my PR, despite my limited understanding of Rust and the rough state of the code.

I've addressed all the points you mentioned! Please take a look when you have a moment.

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 5]
```diff
@@ -162,15 +172,42 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+            let span = e.obligation.cause.span;
+            let outer_expn_data = span.ctxt().outer_expn_data();
+
+            match e.obligation.predicate.kind().skip_binder() {
+                ty::PredicateKind::Subtype(_)
+                    if matches! (
+                        outer_expn_data.kind,
+                        ExpnKind::Macro(_, name) if matches!(
+                            name.as_str().rsplit("::").next(),
+                            Some("format_args" | "format_args_nl")
```
Comment (compiler-errors) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:185]: I think you may be able to use is_diagnostic_item for this, and mark `format_args_nl` as a diagnostic item.

**Review by compiler-errors — CHANGES_REQUESTED** [review]

**Comment by moatom** [comment]
@compiler-errors 
I’ve updated the PR! Could you confirm it at your convenience?

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 6]
```diff
@@ -162,15 +172,42 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                        )
+                    ) =>
+                {
+                    let sm = self.tcx.sess.source_map();
+                    let lc = sm.span_to_location_info(span);
+
+                    if sm.span_to_embeddable_string(span)
+                        == sm.span_to_embeddable_string(outer_expn_data.call_site)
```
[the remark this answers is not in the document]
Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: I updated the logic to compare the `src_hash` of the `span`'s file with that of `outer_expn_data.call_site.source_callsite`:

```rust
fn is_source_span(&self, span: Span) -> bool {
    let source_map = self.tcx.sess.source_map();

    let outer_expn_data = span.ctxt().outer_expn_data();
    let outer_callsite = outer_expn_data.call_site.source_callsite();

    let span_info = source_map.span_to_location_info(span);
    let outer_info = source_map.span_to_location_info(outer_callsite);

    match (span_info, outer_info) {
        ((Some(sf1), _, _, _, _), (Some(sf2), _, _, _, _)) => sf1.src_hash == sf2.src_hash,
        _ => false,
    }
}
```

Let me know if you have any concerns or suggestions.

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 7]
```diff
@@ -162,15 +172,33 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+        errors.sort_by_key(|e| {
+            let span = e.obligation.cause.span;
+            let outer_expn_data = span.ctxt().outer_expn_data();
+
+            match e.obligation.predicate.kind().skip_binder() {
+                ty::PredicateKind::Subtype(_)
+                    if let Some(def_id) = outer_expn_data.macro_def_id
+                        && (self.tcx.is_diagnostic_item(sym::format_args_nl_macro, def_id)
+                            || self.tcx.is_diagnostic_item(sym::format_args_macro, def_id))
+                        && self.is_source_span(span) =>
```
Comment (chenyukang) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs:184]: `is_source_span` is only used here, prefer to use `if let` to remove it:

```rust
                  if let Some(def_id) = outer_expn_data.macro_def_id
                        && let (Some(span_info), row, col, ..) =
                            self.tcx.sess.source_map().span_to_location_info(span)
                        && let (Some(outer_info), ..) =
                            self.tcx.sess.source_map().span_to_location_info(
                                outer_expn_data.call_site.source_callsite(),
                            )
                        && (self.tcx.is_diagnostic_item(sym::format_args_nl_macro, def_id)
                            || self.tcx.is_diagnostic_item(sym::format_args_macro, def_id))
                        && span_info.src_hash == outer_info.src_hash =>
                {
                    ErrorSortKey::SubtypeFormat((row, col))
                }
```

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 8]
```diff
@@ -162,15 +172,33 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+                {
+                    let source_map = self.tcx.sess.source_map();
+                    let (_, _, lo_col, _, _) = source_map.span_to_location_info(span);
+
+                    ErrorSortKey::SubtypeFormat(Reverse(lo_col))
```
[the remark this answers is not in the document]
Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: @chenyukang 
> it's better to use SubtypeFormat((row, col)) so that we keep consistent order also for unformatted code

Thanks for the critical feedback! I’ve addressed the issue.

> Why need to Reverse here?

This is because errors should be sorted in ascending order, prioritizing the rightmost occurrence.

[the remark this answers is not in the document]
Comment (chenyukang) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: | This is because errors should be sorted in ascending order, prioritizing the rightmost occurrence.

Why do we need to report rightmost occurrence first?

For code:
```rust
fn check_format_args() {
    print!("{:?} {:?} {a} {a:?}", [], [], a = 1 + 1);
}
```

Without `Reverse` the error report is:

```console
error[E0282]: type annotations needed
 --> tests/ui/errors/span-format_args-issue-140578.rs:2:35
  |
2 |     print!("{:?} {:?} {a} {a:?}", [], [], a = 1 + 1);
  |                                   ^^ cannot infer type
  |
```

With `Reverse` the error report is:
```console
error[E0282]: type annotations needed
 --> tests/ui/errors/span-format_args-issue-140578.rs:2:39
  |
2 |     print!("{:?} {:?} {a} {a:?}", [], [], a = 1 + 1);
  |                                       ^^ cannot infer type
  |
```

I think it's more natural to report the leftmost occurrence?

[the remark this answers is not in the document]
Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: > In personal preference, report on the first [] is better

Oops, sorry I missed the point. You're totally right — I'll fix it!

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 9]
```diff
@@ -162,15 +171,36 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
...
+            match e.obligation.predicate.kind().skip_binder() {
+                ty::PredicateKind::Subtype(_)
+                    if let Some(def_id) = outer_expn_data.macro_def_id
+                        && let (Some(span_file), row, col, ..) =
+                            source_map.span_to_location_info(span)
+                        && let (Some(source_file), ..) =
+                            source_map.span_to_location_info(source_span)
+                        && (self.tcx.is_diagnostic_item(sym::format_args_nl_macro, def_id)
+                            || self.tcx.is_diagnostic_item(sym::format_args_macro, def_id))
+                        && span_file.src_hash == source_file.src_hash =>
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: Once https://github.com/rust-lang/rust/pull/142594 lands you can do away with the diagnostic item approach:

```suggestion
                    if matches!(
                        span.desugaring_kind(),
                        Some(DesugaringKind::FormatLiteral { .. })
                    ) && let (Some(_), row, col, ..) =
                        source_map.span_to_location_info(span) =>
```
(I don't know if the `src_hash` part is important, maybe you need to leave that in? 🤷 )

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs [hunk 10]
```diff
@@ -136,6 +136,15 @@ pub enum DefIdOrName {
...
 }
 
+#[derive(Debug, PartialEq, Eq, PartialOrd, Ord)]
+enum ErrorSortKey {
+    SubtypeFormat(usize, usize),
+    OtherKind,
+    ClauseTraitSized,
+    Coerce,
+    ClauseWellFormed,
+}
```
Comment (mejrs) [inline compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: It's not immediately obvious what this enum is for. This really needs a doc comment, something like "for sorting the error messages so that sized and WF obligations come last". But I personally would put this inside of the function, just above `errors.sort_by_key(|e| {`. That way it is obvious that it's used for that.

File: compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs (hunk 9 above)
Comment (moatom) [reply compiler/rustc_trait_selection/src/error_reporting/traits/mod.rs]: Do we not need to restrict this to `format_args_nl_macro` and `format_args_macro`? 🤔:

```rust
if matches!(
  span.desugaring_kind(),
  Some(DesugaringKind::FormatLiteral { .. })
) && (self.tcx.is_diagnostic_item(sym::format_args_nl_macro, def_id)
      || self.tcx.is_diagnostic_item(sym::format_args_macro, def_id)) =>
```

**Comment by moatom** [comment]
@compiler-errors @chenyukang @mejrs 

I'm sorry I didn't say this explicitly earlier, but I already marked this PR as `S-waiting-on-review` on May 26.
Would someone be able to take a look?

My concern is this: https://github.com/rust-lang/rust/pull/140916#discussion_r2173091818

File: compiler/rustc_span/src/symbol.rs [hunk 11]
```diff
@@ -1056,6 +1056,7 @@ symbols! {
         format_args_capture,
         format_args_macro,
         format_args_nl,
+        format_args_nl_macro,
```
Comment (moatom) [inline compiler/rustc_span/src/symbol.rs]: no longer needed?

File: library/core/src/macros/mod.rs [hunk 12]
```diff
@@ -1027,6 +1027,7 @@ pub(crate) mod builtin {
         reason = "`format_args_nl` is only for internal \
                   language use and is subject to change"
     )]
+    #[rustc_diagnostic_item = "format_args_nl_macro"]
```
Comment (moatom) [inline library/core/src/macros/mod.rs]: no longer needed?

**Comment by compiler-errors** [comment]
I unfortunately think that the complexity of this PR is not worth the underlying issue it's fixing, but I'm not really able to review this right now

r? compiler

**Comment by nnethercote** [comment]
I looked first at the individual commits and found it very confusing. Then I looked at all the commits combined and it's actually not much code changed. Should most or all of the commits be squashed together? I don't think having them separate is useful here...

... except in one case. In PRs that improve error messages I like to see them split them into two commits:
- The first commit adds a new test, which demonstrates the old error message.
- The second commit changes the code and updates the test output, which demonstrates the improvement to the error message.

This makes it much easier for the reviewer to understand what the improvement is. Could you do this split?

Finally, there are a couple of "no longer needed?" comments above. Are they relevant? I'm not sure what to make of them.

Thanks!

@rustbot author

**Comment by moatom** [comment]
Sorry, I overlooked your intention. I’ll make the corrections later.

**Comment by moatom** [comment]
@nnethercote 
Thank you very much for your patience, and I sincerely apologize for repeatedly taking up your time. I’ve just fixed it.

@rustbot ready

**Review by nnethercote — APPROVED** [review]

**Comment by nnethercote** [comment]
@bors r+ rollup

Thanks!
