### PR TITLE
Finish stabilization of `result_ffi_guarantees`

### LINKED ISSUE #110503: Tracking Issue for result_ffi_guarantees (RFC 3391)
This is a tracking issue for the RFC "result_ffi_guarantees" (rust-lang/rfcs#3391).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement (test) the RFC
  - [ ] https://github.com/rust-lang/rust/pull/122253
  - [x] https://github.com/rust-lang/rust/pull/124747
  - [x] https://github.com/rust-lang/rust/pull/124870
  - [x] https://github.com/rust-lang/rust/pull/125672
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] ~Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])~ (not necessary, reference FCP should be all that's needed)

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None

### PR DESCRIPTION
**Pull request by workingjubilee**
The internal linting has been changed, so all that is left is making sure we stabilize what we want to stabilize.

Closes https://github.com/rust-lang/rust/issues/110503
cc @ehuss @Lokathor

### CODE REVIEW

**Comment by workingjubilee** [comment]
Also cc @rust-lang/lang for your information, as y'all already FCPed this.

File: compiler/rustc_feature/src/accepted.rs [hunk 1]
```diff
@@ -349,6 +349,9 @@ declare_features! (
     (accepted, repr_packed, "1.33.0", Some(33158)),
     /// Allows `#[repr(transparent)]` attribute on newtype structs.
     (accepted, repr_transparent, "1.28.0", Some(43036)),
+    /// Allows enums like Result<T, E> to be used across FFI, if T's niche value can
+    /// be used to describe E or vice-versa.
+    (accepted, result_ffi_guarantees, "1.80.0", Some(110503)),
```
Comment (cuviper) [inline compiler/rustc_feature/src/accepted.rs:354]: Since the previous attempt was incomplete, I think this needs a reset:
```suggestion
    (accepted, result_ffi_guarantees, "CURRENT_RUSTC_VERSION", Some(110503)),
```

**Comment by workingjubilee** [comment]
@ehuss has raised the concern that the documentation updates are unfinished.

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs [hunk 2]
```diff
@@ -1,3 +1,4 @@
+//@ build-pass
```
Comment (Noratrieb) [inline tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: can you add a test for your own custom result-like type here to ensure that it's not special cased to `Result`?
additionally, do we have tests that guarantee that, you know, this guarantee *actually* holds? would be good to have them :)

Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: The RFC does not actually extend beyond Result, actually.

Comment (Noratrieb) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: well then improper_ctypes is implemented incorrectly, because it does this for all result-like enums. the comment above the feature declaration also says result-like

**Comment by Noratrieb** [comment]
https://doc.rust-lang.org/stable/std/primitive.fn.html#abi-compatibility, our "most canonical" place to put ABI docs, isn't updated yet, it only mentions `Option<T>`

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs (hunk 2 above)
Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: I'm happy to write more tests anyways, mind.

**Comment by workingjubilee** [comment]
Oh, good catch!

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs (hunk 2 above)
Comment (Noratrieb) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: well, we'd need to make sure what we actually want to guarantee before writing tests or changing the lint^^

Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: > well then improper_ctypes is implemented incorrectly, because it allows all result-like enums. the comment above the feature declaration also says result-like

Hm.

Comment (Noratrieb) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: i have been informed and see in the code that it also allows all option-like enums so... yolo?

Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: The feature description should certainly at least be correct here.

**Comment by ehuss** [comment]
> @ehuss has raised the concern that the documentation updates are unfinished.

To repeat my answer in the issue, I think if [std's Result docs](https://doc.rust-lang.org/std/result/index.html#representation) are correct[^over], then that should be fine for now. The Reference docs are lagging and work is being done to catch up, but doesn't need to block anything here.

[^over]: Though it seems like those docs were missing a caveat that the ABI was *not* guaranteed for FFI, which I would expect this PR to then remove.

**Comment by workingjubilee** [comment]
current TODOs:
- [ ] I want to write another test for sizedness checking of some types, at least
- [ ] Correct feature description
- [ ] Update std docs for `fn(...T) -> R`: https://doc.rust-lang.org/stable/std/primitive.fn.html#abi-compatibility
- [ ] ???

**Comment by tmandry** [comment]
@rfcbot fcp merge

This completes stabilization of [RFC 3391](https://rust-lang.github.io/rfcs/3391-result_ffi_guarantees.html), which guarantees the layout of `Option<T>`, `Result<T, ()>`, and `Result<(), T>` where `T` is a nonzero type like `Nonnull`, function pointer, etc. to be the same as the underlying type.

These semantics were already [documented](https://doc.rust-lang.org/std/result/index.html#representation) prematurely without lang FCP in https://github.com/rust-lang/rust/pull/124870. The effect of this RFC appears to be to stop linting on such types in `extern "C"` fn declarations as not being FFI safe.

This FCP serves as signoff that we are fine with fully stabilizing the RFC.

@rustbot label I-lang-nominated

File: compiler/rustc_lint/src/types.rs [hunk 3]
```diff
@@ -1144,10 +1144,6 @@ pub(crate) fn repr_nullable_ptr<'tcx>(
             [var_one, var_two] => match (&var_one.fields.raw[..], &var_two.fields.raw[..]) {
                 ([], [field]) | ([field], []) => field.ty(tcx, args),
                 ([field1], [field2]) => {
-                    if !tcx.features().result_ffi_guarantees {
-                        return None;
-                    }
```
Comment (RalfJung) [inline compiler/rustc_lint/src/types.rs:1149]: Note that this makes the lint accept all "Result-like" enums, not just `Result` specifically. This goes beyond the RFC and beyond what we have documented. It matches what the lint does on `Option`, though. I don't know why the lint does this, and could not find a comment explaining this choice.

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs (hunk 2 above)
Comment (RalfJung) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: The logic about "Option-like types" is ooooold, it exists at least Since Rust 1.5 where it got moved in [this PR](https://github.com/rust-lang/rust/pull/28580/files#diff-417fa87f2027051996a0425f1e7a71c0ff0fd049dfee6711a85f82df22574724R367).

(There's also a "FIXME: This duplicates code in trans" there, which still exists, and which I have no idea if it is still true -- it is unclear to me where that duplicate code would be and what it would do.)

File: compiler/rustc_lint/src/types.rs [hunk 4]
```diff
@@ -1144,10 +1144,6 @@ pub(crate) fn repr_nullable_ptr<'tcx>(
             [var_one, var_two] => match (&var_one.fields.raw[..], &var_two.fields.raw[..]) {
```
Comment (RalfJung) [inline compiler/rustc_lint/src/types.rs:1144]: Okay so regarding the FIXME above... way back in the day we had a `fn represent_type_uncached` in `src/librustc_trans/trans/adt.rs` that also had logic for "detecting an option". If I understand the code correctly, that is actually the code that does layout computation -- seems like that lived in trans back then. Meanwhile layout computation no longer special-cases `Option`, we have way more generic enum optimizations.

So, the "FIXME: This duplicates code in codegen" above should be removed.

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs (hunk 2 above)
Comment (RalfJung) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:1]: I think the original logic for recognizing Option-like types was added when the lint was originally implemented, in https://github.com/rust-lang/rust/commit/25f953437d2bc3983b03c0d17cf56de40acec45b. It was just always carried over since then.

So... I think for `Result` we don't want this, we want to specifically recognize that type. And probably for `Option`, too, but that's a different PR.

**Comment by RalfJung** [comment]
> Update std docs for fn(...T) -> R: https://doc.rust-lang.org/stable/std/primitive.fn.html#abi-compatibility

Ah, I now have a separate PR for that before I saw you had this on your list: https://github.com/rust-lang/rust/pull/130653.

Feel free to cherry-pick that commit into your PR an close mine.

**Comment by workingjubilee** [comment]
I'm happy-enough to just let that land.

**Comment by RalfJung** [comment]
Apparently, in https://github.com/rust-lang/rust/pull/60300 t-lang FCP'd a layout guarantee for all `Option`-like enums, meaning enums with two variants where one has 1 field and the other has no field. However AFAIK that never made it into any documentation, it just remained implicit in the lint?

So one question for the lang team to answer here is whether for `Result`, we want to do something similar. I guess it would be wording like: an enum `E` is guaranteed to be layout- and ABI-compatible with type T if
- `E` has exactly two variants
- One variant has exactly one field, of type `T`
- `T` is a `rustc_nonnull_optimization_guaranteed` type
- The other variant either has no field, or exactly one field of type `U` that satisfies all of the following
  - `U` is a 1-ZST
  - `U` must have no fields
  - `U` must not have the `#[non_exhaustive]` attribute

**Comment by workingjubilee** [comment]
Thank you for finding that, Ralf!

**Comment by RalfJung** [comment]
FWIW if we make this a layout guarantee I'd probably strengthen the last bullet to just require `U` to be a 1-ZST. The `Result` docs also list the other requirements, but those are AFAIK motivated by future compat concerns, not by wanting to minimize what we guarantee about layout.

**Comment by RalfJung** [comment]
> Thank you for finding that, Ralf!

I found it [here](https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#discriminant-elision-on-option-like-enums).

**Comment by pnkfelix** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I am in favor of Ralf's guarantee, including the stronger variant. I do not believe that `non_exhaustive` should impact the behavior of the compiler but it *should* inform (hypothetical) future lints or checks, which ought to be informing users not only of things that are broken *now* but (where possible) "fragile" things that might break in minor semver bumps.

**Comment by RalfJung** [comment]
@tmandry your checkbox was set before the question came up of whether this guarantee is specifically for `Result`, or for all result-"like" enums in the sense defined [above](https://github.com/rust-lang/rust/pull/130628#issuecomment-2365492463). Could you clarify your position on that?

**Comment by tmandry** [comment]
I'm fine with including all result-like enums, and with the stronger version you proposed in https://github.com/rust-lang/rust/pull/130628#issuecomment-2366890272.

For non-exhaustive, we should consider it for lints when using the type from outside the defining crate, but that isn't what we're proposing here.

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by RalfJung** [comment]
That sounds great, yes. :)

@ehuss @chorman0773 this should probably go somewhere into the reference as well. Then the `Option` and `Result` docs just need to reference that. Any suggestions for where?

File: compiler/rustc_lint/src/types.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_lint/src/types.rs:1149]: The logic here now does not quite match what has been FCP'd, so the lint will fire on some cases where it doesn't have to fire -- specifically if the "other" variant (the one that does not contain the non-null type) has more than one field but all fields are stably 1-ZST.

This PR can land without fixing that though, it just means the lint can be improved, but that's already well-established. ;)

(I also find `is_niche_optimization_candidate` a very confusing name for "test if this is a 1-ZST and will remain a 1-ZST under semver updates". This type doesn't even have any niches... at least the function has a doc comment clearly describing what it does.)

**Comment by RalfJung** [comment]
Is that a new chapter being written as part of the spec effort, or some local change to an existing part of the reference?

**Comment by chorman0773** [comment]
It's already an existing chapter there, but I would like to rewrite parts of it. Adding `Option` and `Result` to the enum section will either be part of that or separate work along the same lines.

**Comment by workingjubilee** [comment]
Thank you everyone for sorting this out! I will update the tests appropriately to make sure.

File: compiler/rustc_lint/src/types.rs (hunk 3 above)
Comment (workingjubilee) [reply compiler/rustc_lint/src/types.rs:1149]: I lifted this comment into #72774 as part of that refactoring.

**Comment by chorman0773** [comment]
The RFC'd behaviour is PR'd to the reference in https://github.com/rust-lang/reference/pull/1654

**Comment by workingjubilee** [comment]
Update to this, I
- dropped a commit: https://github.com/rust-lang/rust/compare/9ad81f66e009f074d687f61fc31a2b4620a2445d..193352d5f8adeb34d34a421352aeff89524efe52
- tried to modify the test then rebuild, but bootstrap problems, so was forced to rebase: https://github.com/rust-lang/rust/compare/193352d5f8adeb34d34a421352aeff89524efe52..1f8124255804ca35d4938ff7998277e7b5f8f019
- expanded the existing test to cover a TwoVariantEnum type: https://github.com/rust-lang/rust/pull/130628/commits/6111f845ded19752ebee3e3e2951d47f2b1b35de

I have a draft for the actual layout test. This can land as-is and that can be a followup, or it can wait for that.

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs [hunk 5]
```diff
@@ -0,0 +1,132 @@
...
+    fn result_nonzero_usize_t(x: Result<num::NonZero<usize>, ()>);
+    fn result_nonzero_i8_t(x: Result<num::NonZero<i8>, ()>);
+    fn result_nonzero_i16_t(x: Result<num::NonZero<i16>, ()>);
+    fn result_nonzero_i32_t(x: Result<num::NonZero<i32>, ()>);
+    fn result_nonzero_i64_t(x: Result<num::NonZero<i64>, ()>);
+    fn result_nonzero_isize_t(x: Result<num::NonZero<isize>, ()>);
+    fn result_transparent_struct_t(x: Result<TransparentStruct<num::NonZero<u8>>, ()>);
+    fn result_transparent_enum_t(x: Result<TransparentEnum<num::NonZero<u8>>, ()>);
+    fn result_phantom_t(x: Result<num::NonZero<u8>, std::marker::PhantomData<()>>);
+    fn result_1zst_exhaustive_no_variant_t(x: Result<num::NonZero<u8>, Z>);
```
Comment (RalfJung) [inline tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:61]: Oh, we allow this even if the "unit" variant is an empty enum? I didn't expect that... but I guess an empty enum is a 1-ZST so makes sense. For `repr(transparent)` it may have been a mistake to treat uninhabited types as 1-ZST but this is not the right place or time to litigate that issue.

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+    fn result_nonzero_i64_e(x: Result<(), num::NonZero<i64>>);
+    fn result_nonzero_isize_e(x: Result<(), num::NonZero<isize>>);
+    fn result_transparent_struct_e(x: Result<(), TransparentStruct<num::NonZero<u8>>>);
+    fn result_transparent_enum_e(x: Result<(), TransparentEnum<num::NonZero<u8>>>);
+    fn result_phantom_e(x: Result<num::NonZero<u8>, std::marker::PhantomData<()>>);
+    fn result_1zst_exhaustive_no_variant_e(x: Result<Z, num::NonZero<u8>>);
+    fn result_1zst_exhaustive_no_field_e(x: Result<NoField, num::NonZero<u8>>);
+}
+
+enum Either<L, R> {
```
Comment (RalfJung) [inline tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:85]:
```suggestion
// This is where we test that even our own "Option-like" enums are accepted.
enum Either<L, R> {
```

**Review by RalfJung — COMMENTED** [review]
r=me with comment nit

File: tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs (hunk 5 above)
Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:61]: I think that we would _probably_ want to accept this code *whether or not* the other variant is uninhabited, because we allow `NonNull<T> where T: Sized` in FFI in general. Right?

Comment (RalfJung) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:61]: The question is whether we want to declare `Result<T, !>` to be kinda like a transparent newtype around `T`. So far, we don't.

But I agree the lint matches the FCP here. We'll have to extend the ABI compat tests (in `tests/ui/abi/compatibility.rs` and in Miri) to ensure these actually have the ABI we want, but I am fairly sure they do so that can be a follow-up PR. Miri anyway currently hard-codes our `Option`/`Result` type and needs to be adjusted for the "Option-like" definition.

Comment (workingjubilee) [reply tests/ui/rfcs/rfc-3391-result-ffi-guarantees.rs:61]: oh lol I didn't even realize abi/compatibility.rs exists. nice, that's convenient

**Comment by workingjubilee** [comment]
Since I should rewrite the layout test to use the `rustc_abi` dump attribute anyways:

@bors r=RalfJung
