### PR TITLE
Point at return type when it influences non-first `match` arm

### LINKED ISSUE #78124: Misleading compile error message when checking match arm types.
I ran into a case where the compiler is complaining that match arms have incompatible types, as seen in this code snippet below.
However, the line it is pointing to is not necessarily incorrect: the real issue is that the outer "shouldwe" Some => match-arm is not returning a u32 as expected. (In other words, this can be made to compile by adding a return <u32> after the match shouldwe2 statement). 
I eventually realized the actual issue, but this could possibly be clarified by pointing at the outer shouldwe match instead of the inner shouldwe2 match.

```rust
#![allow(unused)]

fn test(shouldwe: Option<u32>, shouldwe2: Option<u32>) -> u32 {
    match shouldwe {
        Some(val) => {
            match shouldwe2 {
                Some(val) => {
                    return val;
                }
                None => (),
            }
        }
        None => return 12,
    }
}

fn main() {
    println!("returned {}", test(None, Some(5)));
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0bb2a05f27f278d55cc68c6f17513460))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: `match` arms have incompatible types
  --> src/main.rs:10:25
   |
6  | /             match shouldwe2 {
7  | |                 Some(val) => {
8  | |                     return val;
   | |                     ----------- this is found to be of type `u32`
9  | |                 }
10 | |                 None => (),
   | |                         ^^ expected `u32`, found `()`
11 | |             }
   | |_____________- `match` arms have incompatible types

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by estebank**
When encountering code like

```rust
fn foo() -> i32 {
    match 0 {
        1 => return 0,
        2 => "",
        _ => 1,
    }
}
```

Point at the return type and not at the prior arm, as that arm has type `!` which isn't influencing the arm corresponding to arm `2`.

Fix #78124.

### CODE REVIEW

File: compiler/rustc_middle/src/traits/mod.rs [hunk 1]
```diff
@@ -402,7 +402,7 @@ pub enum ObligationCauseCode<'tcx> {
     OpaqueReturnType(Option<(Ty<'tcx>, Span)>),
 
     /// Block implicit return
-    BlockTailExpression(hir::HirId),
+    BlockTailExpression(hir::HirId, hir::HirId, hir::MatchSource),
```
Comment (compiler-errors) [inline compiler/rustc_middle/src/traits/mod.rs:405]: Can you make these fields have names?

File: compiler/rustc_hir_typeck/src/_match.rs [hunk 2]
```diff
@@ -145,7 +152,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 other_arms.remove(0);
             }
 
-            prior_arm = Some((arm_block_id, arm_ty, arm_span));
+            if !arm_ty.is_never() {
+                prior_arm = Some((arm_block_id, arm_ty, arm_span));
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/_match.rs:156]: Can you add a short comment here explaining why we skip recording an arm if it diverges here?

File: compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs [hunk 3]
```diff
@@ -1580,7 +1580,14 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             let coerce = ctxt.coerce.as_mut().unwrap();
             if let Some((tail_expr, tail_expr_ty)) = tail_expr_ty {
                 let span = self.get_expr_coercion_span(tail_expr);
-                let cause = self.cause(span, ObligationCauseCode::BlockTailExpression(blk.hir_id));
+                let cause = self.cause(
+                    span,
+                    ObligationCauseCode::BlockTailExpression(
+                        blk.hir_id,
+                        blk.hir_id,
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1587]: I am assuming from context that this second hir id is the scrutinee. It seems like it needs to be an option, otherwise it's kinda just confusing to be passing this hir id twice for this case :sweat_smile:

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1587]: Yeah, I know. It's funny because the scrutinee should really be included in the MatchSource to begin with.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs:1587]: Moved it into MatchSource

File: src/tools/clippy/tests/ui/if_same_then_else2.rs [hunk 4]
```diff
@@ -98,7 +98,7 @@ fn if_same_then_else2() -> Result<&'static str, ()> {
     };
 
     if true {
-        //~^ ERROR: this `if` has identical blocks
+        // FIXME: should emit "this `if` has identical blocks"
```
Comment (compiler-errors) [inline src/tools/clippy/tests/ui/if_same_then_else2.rs:101]: Do you know why this regressed?

**Review by compiler-errors — APPROVED** [review]
r=me if ci passes

File: src/tools/clippy/clippy_utils/src/check_proc_macro.rs [hunk 5]
```diff
@@ -149,7 +149,7 @@ fn expr_search_pat(tcx: TyCtxt<'_>, e: &Expr<'_>) -> (Pat, Pat) {
             (Pat::Str("for"), Pat::Str("}"))
         },
         ExprKind::Match(_, _, MatchSource::Normal) => (Pat::Str("match"), Pat::Str("}")),
-        ExprKind::Match(e, _, MatchSource::TryDesugar) => (expr_search_pat(tcx, e).0, Pat::Str("?")),
+        ExprKind::Match(e, _, MatchSource::TryDesugar(_)) => (expr_search_pat(tcx, e).0, Pat::Str("?")),
```
Comment (flip1995) [inline src/tools/clippy/clippy_utils/src/check_proc_macro.rs:152]: This might be the reason for the Clippy regression. Did the expression `e` that is stored in the `ExprKind::Match` change by any chance and that's why re-calling `expr_search_pat` leads to different results than before? :thinking: 

(Pretty wild guess)

Comment (estebank) [reply src/tools/clippy/clippy_utils/src/check_proc_macro.rs:152]: Fixing in https://github.com/rust-lang/rust/pull/115122
