### PR TITLE
Fix const items not being allowed to be called `r#move` or `r#static`

### LINKED ISSUE #137128: Undocumented: Identifier `r#move` cannot be used as the name of a constant
### Location

<https://doc.rust-lang.org/reference/items/constant-items.html>

### Summary

```rust
//const r#move : i32 = 17760257; // It does not compile
fn main() {
    fn r#move() {} // It does compile
}
```

```
   Compiling playground v0.0.1 (/playground)
error: expected item, found keyword `const`
 --> src/main.rs:1:1
  |
1 | const r#move : i32 = 17760257;
  | ^^^^^ expected item
  |
  = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>

error: could not compile `playground` (bin "playground") due to 1 previous error
```

This may cause problem in generated bindings for APIs in other languages.

<https://developer.android.com/reference/android/R.transition.html#move>

### PR DESCRIPTION
**Pull request by Noratrieb**
Because of an ambiguity with const closures, the parser needs to ensure that for a const item, the `const` keyword isn't followed by a `move` or `static` keyword, as that would indicate a const closure:

```rust
fn main() {
  const move // ...
}
```

This check did not take raw identifiers into account, therefore being unable to distinguish between `const move` and `const r#move`. The latter is obviously not a const closure, so it should be allowed as a const item.

This fixes the check in the parser to only treat `const ...` as a const closure if it's followed by the *proper keyword*, and not a raw identifier.

Additionally, this adds a large test that tests for all raw identifiers in all kinds of positions, including `const`, to prevent issues like this one from occurring again.

fixes #137128

### CODE REVIEW

**Comment by Noratrieb** [comment]
I don't really know if this is something that should get a lang FCP or not... This is definitely a bug and an (older) regression, so I'm inclined to say no. I don't think a lang FCP would be useful, as it's obvious that this should be allowed. But I'll @rust-lang/lang for visibility.

File: tests/ui/parser/raw/raw-idents.rs [hunk 1]
```diff
@@ -0,0 +1,157 @@
+//@ check-pass
+// To make everything a keyword:
+//@ edition:2024
```
Comment (jieyouxu) [inline tests/ui/parser/raw/raw-idents.rs:3]: Question: should we revision this test so it checks editions (2015, 2018, 2024)?

**Review by jieyouxu — COMMENTED** [review]
The parser change looks good to me, I have a nit about the test.

**Comment by jieyouxu** [comment]
> I don't really know if this is something that should get a lang FCP or not... This is definitely a bug and an (older) regression, so I'm inclined to say no. I don't think a lang FCP would be useful, as it's obvious that this should be allowed. But I'll @rust-lang/lang for visibility.

This feels like it *ought* to be accepted (it's incorrectly rejected). Since this has regressed since a long time, we should probably lang-nominate for awareness (even if T-lang decides FCP is unnecessary) if only to double-check with the reference or sth.

**Comment by Noratrieb** [comment]
I'm going to un-nominate this, because I don't think this is worth T-lang's very limited bandwidth. If anyone has objections, you can send them here, but I cannot imagine what an objection would look like :D.

File: tests/ui/parser/raw/raw-idents.rs (hunk 1 above)
Comment (Noratrieb) [reply tests/ui/parser/raw/raw-idents.rs:3]: Sure, why not :3

**Review by compiler-errors — APPROVED** [review]
Yeah, this definitely does not need lang discussion because it's just a parser bug.

**Comment by Noratrieb** [comment]
@theemathas pointed out that i wrote this test in a quite silly way, so I fixed that. And I added revisions.

File: tests/ui/parser/raw/raw-idents.rs [hunk 2]
```diff
@@ -0,0 +1,158 @@
+//@ check-pass
+//@ revisions:e2015 e2018 e2021 e2024
+//[e2015]@ edition:2015
+//[e2018]@ edition:2018
+//[e2021]@ edition:2021
+//[e2024]@ edition:2024
```
Comment (jieyouxu) [inline tests/ui/parser/raw/raw-idents.rs:6]: Sorry, I think this needs to be:

```suggestion
//@[e2015] edition:2015
//@[e2018] edition:2018
//@[e2021] edition:2021
//@[e2024] edition:2024
```

**Review by jieyouxu — CHANGES_REQUESTED** [review]

File: tests/ui/parser/raw/raw-idents.rs (hunk 2 above)
Comment (jieyouxu) [reply tests/ui/parser/raw/raw-idents.rs]: https://github.com/rust-lang/rust/issues/137146

**Review by jieyouxu — APPROVED** [review]
Thanks, also r=me once PR CI is green.

**Comment by Noratrieb** [comment]
image
looks green to me

@bors r=jieyouxu,compiler-errors

**Review by traviscross — APPROVED** [review]
