### PR TITLE
Fix incorrect outer function type parameter message

### LINKED ISSUE #51303: Non-sense help when type parameter from outer function is used
# Code

```rust
struct A;

impl A {
    fn banana(&mut self) {
        fn peach(this: &Self) {
            
        }
    }
}
```

# Error

```
error[E0401]: can't use type parameters from outer function
 --> src/main.rs:9:25
  |
7 | impl A {
  | ---- `Self` type implicitely declared here, on the `impl`
8 |     fn banana(&mut self) {
9 |         fn peach(this: &Self) {
  |            -----        ^^^^ use of type variable from outer function
  |            |
  |            help: try using a local type parameter instead: `peach<Self>`
```

---

It seems that the help message is trying to suggest to introduce a local type parameter, but is worded rather poorly, as if suggesting to *use* a `this: &peach<Self>`.

Perhaps rewording the help message to explicitly say "introduce" rather than "use" would be better, but even then `Self` is a keyword, and cannot be introduced as a local generic parameter anyway.

### PR DESCRIPTION
**Pull request by estebank**
Fix #51303.

### CODE REVIEW

**Comment by estebank** [comment]
[do not merge yet] I think it'd be nice if we actually provided a suggestion to use whatever `Self` is when possible (`impl Foo` should suggest `Foo`, while `impl Bar for Foo` should keep the current diagnostic).

cc @nagisa

File: src/librustc_resolve/lib.rs [hunk 1]
```diff
@@ -198,12 +198,25 @@ fn resolve_struct_error<'sess, 'a>(resolver: &'sess Resolver,
...
-                            |def_id| resolver.definitions.opt_span(def_id)) {
-                        err.span_label(reduce_impl_span_to_impl_keyword(cm, impl_span),
-                                    "`Self` type implicitly declared here, on the `impl`");
+                Def::SelfTy(maybe_trait_defid, maybe_impl_defid) => {
+                    if let Some(impl_span) = maybe_impl_defid.and_then(|def_id| {
+                        resolver.definitions.opt_span(def_id)
+                    }) {
+                        err.span_label(
+                            reduce_impl_span_to_impl_keyword(cm, impl_span),
+                            "`Self` type implicitly declared here, on the `impl`",
```
Comment (nagisa) [inline src/librustc_resolve/lib.rs]: `s/on the/by this/` or s/on the/by this/`.

**Comment by nagisa** [comment]
This seems good to merge with fixed wording.
