### PR TITLE
compiler: Allow `extern "interrupt" fn() -> !`

### LINKED ISSUE #143072: x86-interrupt ABI no longer compiles with never result
### Code

I tried this code:

```rust
#![feature(abi_x86_interrupt)]

extern "x86-interrupt" fn foo() -> ! {
    todo!()
}
```

I expected to see this happen: It compiles.

Instead, this happened:
```
error: invalid signature for `extern "x86-interrupt"` function
 --> <source>:3:36
  |
3 | extern "x86-interrupt" fn foo() -> ! {
  |                                    ^
  |
  = note: functions with the "custom" ABI cannot have a return type
help: remove the return type
 --> <source>:3:36
  |
3 | extern "x86-interrupt" fn foo() -> ! {
  |                                    ^
```

### Version it worked on

It most recently worked on: Rust 1.89 Nightly

### Version with regression

`rustc --version --verbose`:
```
rustc 1.90.0-nightly (0fa4ec6cd 2025-06-25)
binary: rustc
commit-hash: 0fa4ec6cde46fa17ab07acb5531cfe0dc1349ffa
commit-date: 2025-06-25
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

</p>
</details>

### PR DESCRIPTION
**Pull request by workingjubilee**
While reviewing rust-lang/rust#142633 I overlooked a few details because I was kind of excited.

- Fixes rust-lang/rust#143072

### CODE REVIEW

**Comment by folkertdev** [comment]
Now that the rules get more complex, I think the error on the return type should probably move to `rustc_hir_typeck`. The current implementation cannot reason about type aliases, so

```rust
type Unit = ();

#[cfg(any(x64, i686))]
extern "x86-interrupt" fn x86_ret_unit() -> Unit {
    unsafe { hint::unreachable_unchecked() }
}
```

gives

```
error: invalid signature for `extern "x86-interrupt"` function
  --> /home/folkertdev/rust/rust/tests/ui/abi/interrupt-returns-never-or-unit.rs:86:45
   |
LL | extern "x86-interrupt" fn x86_ret_unit() -> Unit {
   |                                             ^^^^
   |
   = note: functions with the "x86-interrupt" ABI cannot have a return type
help: remove the return type
  --> /home/folkertdev/rust/rust/tests/ui/abi/interrupt-returns-never-or-unit.rs:86:45
   |
LL | extern "x86-interrupt" fn x86_ret_unit() -> Unit {
   |                                             ^^^^

error: aborting due to 1 previous error
```

The error message is also incorrect now: the function can have a return type (so long as it's ~~black~~ `()` or `!`)

**Comment by workingjubilee** [comment]
I mean if I really want to get it right it should probably be even deeper, so we can check the actual layout.

**Comment by workingjubilee** [comment]
I don't think I want to do that level of correctness before we decide we actually want these interrupt ABIs, though, and *I*, at least, am not sold on them.

**Comment by andrewoffenden** [comment]
My me t cv to ▶️ p ppl l

Andrew Woffenden

**Comment by folkertdev** [comment]
Fair enough. Then the error message should at least be correct though right? (so, there can be a return type, just literally `()` and `!` are allowed).

> before we decide we actually want these interrupt ABIs, though, and I, at least, am not sold on them.

The x86 one gets a surprising (to me) amount of use https://github.com/search?q=extern+%22x86-interrupt%22&type=code. But in theory those could now use naked functions and compile on stable.

**Comment by workingjubilee** [comment]
@andrewoffenden what.

**Comment by workingjubilee** [comment]
> Fair enough. Then the error message should at least be correct though right? (so, there can be a return type, just literally `()` and `!` are allowed).
> 
> > before we decide we actually want these interrupt ABIs, though, and I, at least, am not sold on them.
> 
> The x86 one gets a surprising (to me) amount of use https://github.com/search?q=extern+%22x86-interrupt%22&type=code. But in theory those could now use naked functions and compile on stable.

Yes, Phil Opp espoused using them, so they gained some popularity. But they should not be used by a real OS, because an OS cannot support any debugger APIs if it uses them.

**Comment by Freax13** [comment]
I think there are valid use-cases for the "x86-interrupt" ABI even in a "real OS". Sometimes you don't need to look at the registers of the interrupted thread, and in that case, using "x86-interrupt" is completely fine and can even result in better code than a hand-written interrupt handler. For example, I use it for handling timer interrupts that happen while the kernel is executing in ring 0. That said, there are, of course, also use cases where this absolutely will not work: If you're going to write an `int 0x80` handler, you'll very likely need to hand roll your own assembly.

**Comment by phil-opp** [comment]
Apart from convenience, my main motivation for using the `x86-interrupt` calling convention was that it generates better code than you can write manually for short interrupt handlers. It backups only the registers that are used by the handler implementation. With manual inline assembly, you have to always backup all caller-saved registers.

That being said, I also agree that the `x86-interrupt` calling convention is a burden to maintain. The LLVM implementation is not really used by many people, so it's not properly tested and breaks relatively often. It's also quite a complex calling convention because of how the x86 architecture is designed (e.g. for some exceptions, an additional error code is pushed to stack). So I would fully understand if we don't want to have this complexity inside `rustc`. 

Thanks a lot for this PR by the way! I appreciate it that you try to avoid breakage, even though it's a nightly feature!

**Comment by phil-opp** [comment]
(Not directly related to this PR, but to discussion about whether we want to keep the `x86-interrupt` calling convention or not:

I think if we had support for LLVM's `PreserveAll` or `PreserveMost` calling conventions, we could use that instead of `x86-interrupt` (in combination with a naked wrapper function). This way, we could keep the complexity of the x86 interrupt stack frame out of rustc, bit still have the performance advantage of saving only the registers that will be overwritten.)

**Comment by workingjubilee** [comment]
We do support PreserveMost already as `extern "rust-cold"`, but I don't know if it works the way you need it to, @phil-opp. We can add a full-on "rust-save" though.

I agree that we really do need that as a prerequisite to any alternatives. That way any assembly can be a minimal shim sufficient to do whatever operations are needed between the machine and the OS and then jump into the main handler, instead of saving everything in the assembly.

**Comment by JayAndJef** [comment]
I was wondering why my kernel couldn't compile yet x86_64 expected a return type of `!` for interrupt handlers! good to know there's a fix coming.

File: compiler/rustc_ast_passes/src/ast_validation.rs [hunk 1]
```diff
@@ -455,7 +461,13 @@ impl<'a> AstValidator<'a> {
...
     fn reject_params_or_return(&self, abi: ExternAbi, ident: &Ident, sig: &FnSig) {
         let mut spans: Vec<_> = sig.decl.inputs.iter().map(|p| p.span).collect();
-        if let FnRetTy::Ty(ref ret_ty) = sig.decl.output {
+        if let FnRetTy::Ty(ref ret_ty) = sig.decl.output
+            && match &ret_ty.kind {
+                TyKind::Never => false,
+                TyKind::Tup(tup) if tup.is_empty() => false,
+                _ => true,
+            }
+        {
```
Comment (workingjubilee) [inline compiler/rustc_ast_passes/src/ast_validation.rs:470]: Actually, @folkertdev, I think the biggest logic with moving this to `hir_typeck` is I'm not actually sure if that's the right place for an ad-hoc validation check on the HIR. And I don't know if I should trust the previous places we put ABI checks. :face_with_spiral_eyes:

Comment (folkertdev) [reply compiler/rustc_ast_passes/src/ast_validation.rs:470]: I just know that it's where we now perform the checks for `extern "custom"` and for naked functions there. They were previously in `rustc_passes` but moving them into `hir_typeck` was both shorter and faster.

**Comment by BoxyUwU** [comment]
r? compiler

**Comment by cr1901** [comment]
Commenting to follow this PR. This should fix a [CI failure](https://github.com/cr1901/AT2XT/actions/runs/15959953951/job/45011090978#step:9:69) I started seeing a few days ago on my reference MSP430 repo.

(I've been following #132841- the issue which was closed by #142633- since it has the `O-msp430` label. Not sure what issue this should go under, so I'll put it here for now and move it if necessary.)

Re: the interrupt CC proliferation, in terms of msp430-land, TI's [ABI doc](https://www.ti.com/lit/an/slaa534a/slaa534a.pdf) states (emphasis mine):

> 3.9 Interrupt Functions
> Interrupt functions must save all the registers that are used, **even those that are normally considered callee-
> saved, except for the special purpose registers PC, SP, and SR**.
>
> Interrupts push the SR and PC registers onto the stack and branch to an interrupt handler. To return from an
> interrupt function, the function must execute the special instruction RETI, which restores the SR register and
> branches to the PC where the interrupt occurred.

In other words, it's a generic "save all the registers that are used except those that are saved by the hardware (PC, SR) and/or have known use cases to modify (PC, SR's power-mode bits, SP).  I _think_ `msp430-interrupt` and `x86-interrupt` are functionally equivalent, and so that's two interrupt CCs that could be replaced with a single generic one?

**Comment by workingjubilee** [comment]
@folkertdev Ah yeah you're right, I should have known better, sadly this is allowed due to doing AST-level validation:
```rust
#![feature(abi_x86_interrupt)]
use core::{mem, ptr};

type Alias<A> = unsafe extern "x86-interrupt" fn(A);

fn main() {
    let ptr = unsafe { mem::transmute::<_, Alias<i32>>(ptr::dangling::<u8>()) };
}
```

**Comment by zdivelbiss** [comment]
For what it's worth, I feel that if LLVM doesn't support the `x86-interrupt` ABI very stably then it isn't worth our time to do it either.

In practice, this is only used for functions that will be written a single time, will call into higher-level code, and never touched or looked at again.

Most of the actual assembly involved is very simple / straightforward, and there's a wealth of resources online that describe in detail exactly what an x86 interrupt handler should look like. Additionally, the use-case of this feature is in a pretty complex field (bare-metal x86) that already requires knowing / doing some assembly to progress through.

**Comment by Freax13** [comment]
@workingjubilee I see that you marked this PR as a draft. I'm assuming that you did so because there are still some issues left that have not yet been addressed by this PR (like the one pointed out by @folkertdev). Still, the fixes already in this PR would unblock a lot of people even if they're not perfect. Please consider landing these fixes now and improving on them later.

**Comment by workingjubilee** [comment]
Yeah, sorry, I thought it was going to be just a couple days of work and then my computer broke which... lol? I'm fine with landing this as-is if others are happy.

**Review by davidtwco — APPROVED** [review]
LGTM, seems reasonable. `hir_typeck` is probably the better place for these checks but if you want more time to think about the interrupt ABIs first then we can always move it later. It's a small addition anyway.
