### PR TITLE
Fix check of `statx` and handle EPERM

### LINKED ISSUE #65662: Compiler doesn't work when using Docker
When I run this sequence of commands:
```
docker run --rm -it ubuntu:xenial
apt update
apt install wget
wget https://sh.rustup.rs -O rustup.sh
chmod ugo+x rustup.sh 
./rustup.sh -y --default-toolchain nightly
source $HOME/.cargo/env
rustc -vV
```
I get this error:
```
rustc 1.40.0-nightly (7979016af 2019-10-20)
binary: rustc
commit-hash: 7979016aff545f7b41cc517031026020b340989d
commit-date: 2019-10-20
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
error: failed to find a `codegen-backends` folder in the sysroot candidates:
* /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
* /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

This happens due to the [`statx` syscall](https://github.com/rust-lang/rust/pull/65094) failing with EPERM. I believe Docker uses seccomp to limit which system calls may be made, and the `statx` call is too new, so it's [not whitelisted](https://github.com/moby/moby/pull/36417). Because the syscall fails with EPERM instead of ENOSYS, the fallback to regular `stat` doesn't work.

Host kernel: 4.15.0-65-generic

docker version
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by oxalica**
Should fix #65662 

https://github.com/rust-lang/rust/issues/65662#issuecomment-544593939
> I think a reasonable solution might be to do something like try to stat AT_CWD initially and if that fails with EPERM or ENOSYS we disable the syscall entirely, otherwise it's cached as always good to use. 

r? @alexcrichton

### CODE REVIEW

**Comment by lnicola** [comment]
I suppose a micro-optimization would be to only do the `AT_CWD` check if it fails for the argument, but maybe it's not worth it.

File: src/libstd/sys/unix/fs.rs [hunk 1]
```diff
@@ -120,21 +123,36 @@ cfg_has_statx! {{
...
+                    libc::AT_FDCWD,
+                    b".\0".as_ptr().cast(),
+                    0,
+                    libc::STATX_ALL,
+                    &mut buf,
+                ))
+                    .err()
+                    .and_then(|e| e.raw_os_error());
+                // `seccomp` will emit `EPERM` on denied syscall.
+                // See: https://github.com/rust-lang/rust/issues/65662
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Could this expand the comment inline to explain why `EPERM` is handled specially and why we attempt to stat a "known good" location, along with the pitfalls of this could still return a false negative?

File: src/libstd/sys/unix/fs.rs [hunk 2]
```diff
@@ -120,21 +123,36 @@ cfg_has_statx! {{
...
-                    HAS_STATX.store(false, Ordering::Relaxed);
-                    return None;
+        match STATX_STATE.load(Ordering::Relaxed) {
+            // For the first time, we try to call on current working directory
+            // to check if it is available.
+            0 => {
+                let mut buf: libc::statx = mem::zeroed();
+                let err = cvt(statx(
+                    libc::AT_FDCWD,
+                    b".\0".as_ptr().cast(),
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Could this perhaps be an empty string and pass `AT_EMPTY_PATH` in the flags?

File: src/libstd/sys/unix/fs.rs [hunk 3]
```diff
@@ -120,21 +123,36 @@ cfg_has_statx! {{
...
                 }
-                _ => return Some(Err(err)),
+                try_statx(fd, path, flags, mask)
             }
-            Ok(_) => {
+            1 => None,
+            _ => {
+                let mut buf: libc::statx = mem::zeroed();
+                if let Err(err) = cvt(statx(fd, path, flags, mask, &mut buf)) {
+                    return Some(Err(err));
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: Although not part of this PR, it might be nice to change this to return `io::Result<Option<FileAttr>>` to use `?` here instead of `if let`

File: src/libstd/sys/unix/fs.rs [hunk 4]
```diff
@@ -120,21 +123,36 @@ cfg_has_statx! {{
...
+                    .and_then(|e| e.raw_os_error());
+                // `seccomp` will emit `EPERM` on denied syscall.
+                // See: https://github.com/rust-lang/rust/issues/65662
+                if err == Some(libc::ENOSYS) || err == Some(libc::EPERM) {
+                    STATX_STATE.store(1, Ordering::Relaxed);
+                } else {
+                    STATX_STATE.store(2, Ordering::Relaxed);
                 }
-                _ => return Some(Err(err)),
+                try_statx(fd, path, flags, mask)
```
Comment (alexcrichton) [inline src/libstd/sys/unix/fs.rs]: could this perhaps use a fall-through instead of a recursive call? That way the branch that stores 1 could `return None` and this branch would fall through as well as the catch-all case below to after the `match`

**Review by alexcrichton — COMMENTED** [review]
Looks great to me, thanks again for helping to handle this @oxalica!

File: src/libstd/sys/unix/fs.rs (hunk 1 above)
Comment (oxalica) [reply src/libstd/sys/unix/fs.rs]: > ... along with the pitfalls of this could still return a false negative?

Will it? The manual said it never returns EPERM. So it should be the only case.

File: src/libstd/sys/unix/fs.rs (hunk 2 above)
Comment (oxalica) [reply src/libstd/sys/unix/fs.rs]: As the comment from @lnicola , maybe we can simply call `statx(0, null(), 0, STATX_ALL, null_mut())` and expecting an `EFAULT` according to [the manual](http://man7.org/linux/man-pages/man2/statx.2.html)?
It costs **only 1.3ns** instead of **580ns** of a successful call.

File: src/libstd/sys/unix/fs.rs (hunk 1 above)
Comment (alexcrichton) [reply src/libstd/sys/unix/fs.rs]: Perhaps! I've come to not trust man pages on errors though, they basically never describe the exhaustive set of errors, only some possible ones.

File: src/libstd/sys/unix/fs.rs (hunk 2 above)
Comment (alexcrichton) [reply src/libstd/sys/unix/fs.rs]: That also seems reasonable to me!

Comment (lnicola) [reply src/libstd/sys/unix/fs.rs]: That's not exactly what I suggested, but sounds like a good idea anyway :smile:.

File: src/libstd/sys/unix/fs.rs (hunk 3 above)
Comment (oxalica) [reply src/libstd/sys/unix/fs.rs]: To be honest, `Ok(None)` for "unavailable" seems weird to me...
`Option<Result<T>>` is for the syscall may be unavailable, or available with a result.

Changing the type does not simplify much more code. Instead, we need an extra `?` after every calls below.

**Comment by alexcrichton** [comment]
@bors: r+ 

Looks good to me!
