### PR TITLE
make UI tests that use `--test` work on panic=abort targets

### LINKED ISSUE #135819: UI tests that pass `--test` to rustc fail on panic=abort targets
Namely
- [tests/ui/macros/rfc-2011-nicer-assert-messages/feature-gate-generic_assert.rs](https://github.com/rust-lang/rust/blob/a7a6c64a657f68113301c2ffe0745b49a16442d1/tests/ui/macros/rfc-2011-nicer-assert-messages/feature-gate-generic_assert.rs#L1)
- [tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs](https://github.com/rust-lang/rust/blob/a7a6c64a657f68113301c2ffe0745b49a16442d1/tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs#L1)

By default, unit tests on panic=abort targets will abort the whole process. As these tests rely on `#[should_panic]` tests, they fail on those targets.

These tests can be made work on panic=abort targets with the additional `-Zpanic_abort_tests` flag. Both modes (with and without the `-Z` flag) can be tested using test revisions.

The other, simpler alternative is to mark the tests as `needs-unwind` to ignore them on panic=abort targets.

I'll send a PR implementing the first alternative.

### PR DESCRIPTION
**Pull request by japaric**
By passing `-Zpanic_abort_test`.

fixes #135819

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks, I'll r+ after PR CI is green.

**Comment by jieyouxu** [comment]
r? jieyouxu

File: tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs [hunk 1]
```diff
@@ -1,4 +1,10 @@
-//@ compile-flags: --test
+//@ revisions: can_unwind
+//@ [can_unwind] compile-flags: --test
+//@ [can_unwind] needs-unwind
+//
+//@ revisions: cannot_unwind
+//@ [cannot_unwind] compile-flags: --test -Zpanic_abort_tests
```
Comment (bjorn3) [inline tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs:6]: I think `-Zpanic-abort-tests` does nothing for `-Cpanic=unwind` so enabling it unconditionally should be fine.

Comment (japaric) [reply tests/ui/macros/rfc-2011-nicer-assert-messages/assert-with-custom-errors-does-not-create-unnecessary-code.rs]: indeed, that works. updated the PR

**Comment by jieyouxu** [comment]
Thanks!
@bors r+ rollup
