### PR TITLE
Forbid tail calling intrinsics

### LINKED ISSUE #144806: ICE from tail call to transmute
### Code

```Rust
#![feature(explicit_tail_calls)]
#![allow(incomplete_features)]

fn foo(_: ()) {
    unsafe {
        become std::mem::transmute::<(), ()>(());
    }
}

fn main() {
    foo(());
}
```

@rustbot labels +F-explicit_tail_calls +requires-incomplete-features

### Meta

Reproducible on the playground with version `1.90.0-nightly (2025-08-01 4b55fe199cfe9c710555)`

### Error output

```
error: internal compiler error: /rustc-dev/4b55fe199cfe9c710555a5af7f2a49491ad38254/compiler/rustc_codegen_ssa/src/mir/block.rs:992:37: intrinsic transmute must be overridden by codegen backend, but isn't
 --> src/main.rs:6:16
  |
6 |         become std::mem::transmute::<(), ()>(());
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc-dev/4b55fe199cfe9c710555a5af7f2a49491ad38254/compiler/rustc_codegen_ssa/src/mir/block.rs:992:37:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: <rustc_errors::DiagCtxtHandle>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::GenericBuilder<rustc_codegen_llvm::context::FullCx>>
   8: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   9: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: <rustc_interface::queries::Linker>::codegen_and_build_linker
  12: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  13: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2025-08-02T05_25_54-52.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by WaffleLapkin**
There is only one intrinsic that can be called on stable, as far as I can find, (`transmute`). And in general tail calling intrinsics doesn't make much sense.

Alternative to rust-lang/rust#144815 (and thus closes rust-lang/rust#144815)
Fixes https://github.com/rust-lang/rust/issues/144806

r? @scottmcm

### CODE REVIEW

File: compiler/rustc_mir_build/src/check_tail_calls.rs [hunk 1]
```diff
@@ -103,6 +103,13 @@ impl<'tcx> TailCallCkVisitor<'_, 'tcx> {
                 // skip them, producing an error about calling a closure is enough.
                 return;
             };
+
+            if let Ok(Some(instance)) =
+                ty::Instance::try_resolve(self.tcx, self.typing_env, did, args)
+                && let InstanceKind::Intrinsic(_) = instance.def
```
Comment (compiler-errors) [inline compiler/rustc_mir_build/src/check_tail_calls.rs]: importing `InstanceKind` but not `Instance` is a bit weird 🤔

**Review by compiler-errors — APPROVED** [review]
I think using `Instance::try_resolve` is a bit overkill since we can just use `tcx.instance(def_id).is_some()`, but I think resolve is ok.

**Comment by compiler-errors** [comment]
r=me unless you want a specific review

File: compiler/rustc_mir_build/src/check_tail_calls.rs [hunk 2]
```diff
@@ -103,6 +103,13 @@ impl<'tcx> TailCallCkVisitor<'_, 'tcx> {
                 // skip them, producing an error about calling a closure is enough.
                 return;
             };
+
+            if let Ok(Some(instance)) =
+                ty::Instance::try_resolve(self.tcx, self.typing_env, did, args)
+                && let ty::InstanceKind::Intrinsic(_) = instance.def
```
Comment (scottmcm) [inline compiler/rustc_mir_build/src/check_tail_calls.rs]: Do you need the *resolve* here?  Can probably just do <https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.intrinsic>.is_some()?

(Since you never get to an intrinsic through a trait impl or whatever.)

**Review by scottmcm — APPROVED** [review]
LGTM as well, with or without the change I mentioned.

I like the approach of giving a real error here -- since intrinsics are just expanded directly, there's no need to ever `become` them, as you say.

File: compiler/rustc_mir_build/src/check_tail_calls.rs (hunk 2 above)
Comment (scottmcm) [reply compiler/rustc_mir_build/src/check_tail_calls.rs]: Doh, I somehow completely missed that c-e already said this 🤦
