### PR TITLE
Clarify docs for unreachable! macro

### LINKED ISSUE #60754: Documentation for unreachable macro incorrectly describes unreachable_unchecked
The documentation for the `unreachable!` macro says:
>If the determination that the code is unreachable proves incorrect, the program immediately terminates with a `panic!`. The function `unreachable_unchecked`, which belongs to the `std::hint` module, informs the compiler to optimize the code out of the release version entirely.

This is incorrect; while building in release (and thus with optimizations) certainly makes the compiler more likely to exploit `unreachable_unchecked`, it is still UB to reach it without optimizations enabled, and LLVM is under no obligation to exploit it when compiling in release mode. 

I'm not sure what this should be changed to, which is why I'm not just submitting a PR.

### PR DESCRIPTION
**Pull request by blkerby**
Fixes #60754.

### CODE REVIEW

File: src/libcore/macros.rs [hunk 1]
```diff
@@ -445,9 +445,10 @@ macro_rules! writeln {
 /// * Iterators that dynamically terminate.
 ///
 /// If the determination that the code is unreachable proves incorrect, the
-/// program immediately terminates with a [`panic!`]. The function [`unreachable_unchecked`],
-/// which belongs to the [`std::hint`] module, informs the compiler to
-/// optimize the code out of the release version entirely.
+/// program immediately terminates with a [`panic!`].
+///
+/// The unsafe counterpart of this macro is the [`unreachable_unchecked`] function, which
+/// instead of a [`panic!`] will cause undefined behavior if the code is reached.
```
Comment (lzutao) [inline src/libcore/macros.rs]:
```diff
-/// instead of a [`panic!`] will cause undefined behavior if the code is reached.
+/// will cause undefined behavior if the code is reached.
```

Comment (blkerby) [reply src/libcore/macros.rs]: I removed the phrase now as you suggest
