### PR TITLE
Emit proper errors when on missing closure braces

### LINKED ISSUE #88065: Attempting to debug in a iterator's closure without {} gives unhelpful error
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9b9dfd706291c45a1f6a567324b6c860

Given the following code: 

```rust
fn main() {
    let num = 5;
    (1..num).reduce(|a, b| 
        println!("{}", a); // <== Here
        a * b
    ).unwrap();
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `)`, `,`, `.`, `?`, or an operator, found `;`
 --> src/main.rs:4:26
  |
4 |         println!("{}", a); // <== Here
  |                          ^
  |                          |
  |                          expected one of `)`, `,`, `.`, `?`, or an operator
  |                          help: missing `,`

error[E0425]: cannot find value `a` in this scope
 --> src/main.rs:5:9
  |
5 |         a * b
  |         ^ not found in this scope

error[E0425]: cannot find value `b` in this scope
 --> src/main.rs:5:13
  |
5 |         a * b
  |             ^ not found in this scope

error[E0061]: this function takes 1 argument but 2 arguments were supplied
    --> src/main.rs:3:14
     |
3    |       (1..num).reduce(|a, b| 
     |  ______________^^^^^^_-
     | |              |
     | |              expected 1 argument
4    | |         println!("{}", a); // <== Here
     | |_________________________-
5    |           a * b
     |           ----- supplied 2 arguments
     |
note: associated function defined here

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0061, E0425.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Ideally the output should look like:

```
3    |       (1..num).reduce(|a, b| {
     |  ____________________________^
     | | Multi-line closure requires scope brackets
```

I was trying to debug an iterator and added a `println!` call. To my surprise, it caused the compiler to fail and emit MANY warnings. None of them pointed at the real problem which is that I was missing curly brackets `{}`.

### PR DESCRIPTION
**Pull request by scrabsha**
This commit focuses on emitting clean errors for the following syntax
error:

```
Some(42).map(|a|
    dbg!(a);
    a
);
```

Previous implementation tried to recover after parsing the closure body
(the `dbg` expression) by replacing the next `;` with a `,`, which made
the next expression belong to the next function argument. As such, the
following errors were emitted (among others):
  - the semicolon token was not expected,
  - a is not in scope,
  - Option::map is supposed to take one argument, not two.

This commit allows us to gracefully handle this situation by adding
giving the parser the ability to remember when it has just parsed a
closure body inside a function call. When this happens, we can treat the
unexpected `;` specifically and try to parse as much statements as
possible in order to eat the whole block. When we can't parse statements
anymore, we generate a clean error indicating that the braces are
missing, and return an ExprKind::Err.

Closes #88065.

r? @estebank

### CODE REVIEW

File: compiler/rustc_parse/src/parser/mod.rs [hunk 1]
```diff
@@ -839,6 +868,48 @@ impl<'a> Parser<'a> {
...
+            initial_semicolon,
+            "This `;` turns the expression into a statement, which must be placed in a block",
+        );
+
+        while self.eat(&TokenKind::Semi) {
+            let _ = self.parse_stmt(ForceCollect::Yes)?;
+        }
+
+        expect_err.set_primary_message(
+            "closure body that contain statements must be surrounded by braces",
```
Comment (inquisitivecrystal) [inline compiler/rustc_parse/src/parser/mod.rs:888]: There's a grammar problem here: you either want "**a** closure body that contain**s** statements must be surrounded by braces" or ""closure bod**ies** that contain statements must be surrounded by braces". We may have a stylistic convention on which one is correct, but if so, I don't know what it is.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 2]
```diff
@@ -839,6 +868,48 @@ impl<'a> Parser<'a> {
...
+    fn recover_missing_braces_around_closure_body(
+        &mut self,
+        right_pipe_span: Span,
+        mut expect_err: DiagnosticBuilder<'_>,
+    ) -> PResult<'a, ()> {
+        let initial_semicolon = self.token.span;
+
+        expect_err.span_help(
+            initial_semicolon,
+            "This `;` turns the expression into a statement, which must be placed in a block",
```
Comment (inquisitivecrystal) [inline compiler/rustc_parse/src/parser/mod.rs:880]: Somehow reading this message in the test output below doesn't get the point across for me. I'm not entirely sure why. I think it might be that "This `;`" is clear, but then I think, "what expression? what statement?". The problem might be that those concepts seem too abstract and detached from the actual code to be understood at a glance. I'm not exactly sure how to fix it though.

File: compiler/rustc_parse/src/parser/mod.rs (hunk 1 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/mod.rs:888]: That makes sense, thanks. The [suggestion style guide](https://rustc-dev-guide.rust-lang.org/diagnostics.html?#suggestion-style-guide) doesn't help unfortunately. I have found no other wording suggestion in the documentation.

I like your second suggestion and I'll keep that one for no particular reason other than being grammatically correct. Feel free to suggest anything that may be better :)

File: compiler/rustc_parse/src/parser/mod.rs (hunk 2 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/mod.rs:880]: I understand your pain. It took me a lot of time to write this sentence and I'm still not satisfied with it.

To mitigate your "what expression? what statement?" problem, I see two solutions:
  - reword the message as "This `;` turns the **preceding** expression into a statement [...]" (see first screenshot),
  - span the help message on the whole "expression+semicolon" chunk, changing the message to "the trailing `;` turns the expression into a statement" (see second screenshot).

Both are not ideal, though.

Overall, I'm not even sure if it is a good idea to expect from the user to know the difference between an expression and a statement, given that users may not have knowledge in language grammar.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 3]
```diff
@@ -761,20 +766,44 @@ impl<'a> Parser<'a> {
...
-                                if tokens.contains(&self.token.kind) && !unclosed_delims {
-                                    self.bump();
+                            match self.last_closure_body.take() {
+                                None => {
+                                    // Attempt to keep parsing if it was a similar separator.
+                                    if let Some(ref tokens) = t.similar_tokens() {
+                                        if tokens.contains(&self.token.kind) && !unclosed_delims {
+                                            self.bump();
+                                        }
+                                    }
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/mod.rs:788]: Shouldn't this be in the `_ => {` arm?

File: compiler/rustc_parse/src/parser/mod.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/mod.rs:880]: An option we have is to abuse the `MultiSpan` API:

```rust
let mut sp: MultiSpan = vec![initial_semicolon].into();
sp.push_label(initial_semicolon, "this `;` turns the preceding expression into a statement");
sp.push_label(expr.span, "this expression is a statement because of the trailing semicolon");
sp.push_label(closure.span, "this is the parsed closure...");
sp.push_label(end_brace_span, "...but likely you meant the closure to end here");
```

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -1733,6 +1736,18 @@ impl<'a> Parser<'a> {
...
+        // Disable recovery for closure body
+        self.last_closure_body = Some(decl_hi);
+
+        if self.token.kind == TokenKind::Semi && self.token_cursor.frame.delim == DelimToken::Paren
+        {
+            // It is likely that the closure body is a block but where the
+            // braces have been removed. We will recover and eat the next
+            // statements later in the parsing process.
+
+            return Ok(self.mk_expr_err(lo.to(body.span)));
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1748]: What we might want to do is make a closure here where it's body is an error expression placeholder, although that doesn't change anything in this PR, I would like us to be able to mark that closure somehow (either by changing it's variant or just using the err expression as a marker) to detect cases where `{|x| let y = x + 1; y}` is written. But we can make that change after the fact.

Could we add a test for the "ruby closure" case? I'm intrigued at what it looks like under _this_ PR.

File: compiler/rustc_parse/src/parser/mod.rs (hunk 3 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/mod.rs]: Yes it should!

File: compiler/rustc_parse/src/parser/expr.rs (hunk 4 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/expr.rs:1748]: Oh that makes sense. I had not noticed the difference between "a closure whose body is an expr error" and "an expr error" in my early development. Thanks

File: compiler/rustc_parse/src/parser/mod.rs (hunk 2 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/mod.rs:878]: While this definitely works, I think this adds a lot of noise in the `note` section:
A screenshot of the error message with all the spanned labels suggested by estebank. The result is very cumbersome. We don't know what to read first.

I think the best solution here is to remove the `spanned_label` whose message is "this expression is a statement because of the trailing semicolon", but this needs more experiments.

File: compiler/rustc_parse/src/parser/expr.rs (hunk 4 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/expr.rs]: @estebank I added the ruby-style closure syntax ui tests you talked about. In order to make tests pass, I had to annotate them with the (arguably not helpful) current compiler output. Please ping me if this is not was you expected :)

File: compiler/rustc_parse/src/parser/mod.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/mod.rs:878]: Another alternative is to add a new note for either the statement or the closure.

It could even make sense to put the "this is the parsed closure..."/"...but likely you meant the closure to end here" in its own note, which would make the output more vertically prominent, but easier to read.

File: src/test/ui/expr/malformed_closure/ruby_style_closure.rs [hunk 5]
```diff
@@ -0,0 +1,8 @@
+fn main() {
```
Comment (estebank) [inline src/test/ui/expr/malformed_closure/ruby_style_closure.rs:1]: Let's add a comment with the ticket number and mentioning that this isn't yet handled by the compiler, but we want to at some point.

File: src/test/ui/expr/malformed_closure/ruby_style_closure.stderr [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+  --> $DIR/ruby_style_closure.rs:5:14
+   |
+LL |         Some(x * 2)
+   |              ^ not found in this scope
+
+error[E0277]: expected a `FnOnce<({integer},)>` closure, found `Option<_>`
+  --> $DIR/ruby_style_closure.rs:2:22
+   |
+LL |     let p = Some(45).and_then({
+   |                      ^^^^^^^^ expected an `FnOnce<({integer},)>` closure, found `Option<_>`
```
Comment (estebank) [inline src/test/ui/expr/malformed_closure/ruby_style_closure.stderr:11]: This should be pointing at the `Some(x * 2)`. (Not something to address in this PR)

File: compiler/rustc_parse/src/parser/mod.rs (hunk 2 above)
Comment (scrabsha) [reply compiler/rustc_parse/src/parser/mod.rs]: > It could even make sense to put the "this is the parsed closure..."/"...but likely you meant the closure to end here" in its own note, which would make the output more vertically prominent, but easier to read.

I implemented it and IMO this is what gives the best results! It makes the error message longer, but it is way easier to read, as each subdiagnostic relate a specific concept.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 7]
```diff
@@ -145,7 +146,11 @@ pub struct Parser<'a> {
 
     /// This allows us to recover when the user forget to add braces around
     /// multiple statements in the closure body.
-    pub last_closure_body: Option<Span /* The closing `|` of the closure declarator. */>,
+    pub last_closure_body: Option<(
+        Span, /* The whole body. */
+        Span, /* The closing `|` of the closure declarator. */
+        Span, /* What we parsed as closure body. */
+    )>,
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/mod.rs:152]: We should create a new struct for these :)

File: compiler/rustc_parse/src/parser/expr.rs [hunk 8]
```diff
@@ -1747,11 +1744,18 @@ impl<'a> Parser<'a> {
             body = self.mk_expr_err(body.span);
         }
 
-        Ok(self.mk_expr(
+        let body_span = body.span;
+
+        let clo = self.mk_expr(
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1749]: Can we rename this to either `closure` or `expr`? `clo` isn't used anywhere else and might lead to short lived confusion, but confusion nonetheless.

File: compiler/rustc_parse/src/parser/mod.rs [hunk 9]
```diff
@@ -145,7 +146,11 @@ pub struct Parser<'a> {
 
     /// This allows us to recover when the user forget to add braces around
     /// multiple statements in the closure body.
-    pub last_closure_body: Option<Span /* The closing `|` of the closure declarator. */>,
+    pub last_closure_body: Option<(
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/mod.rs:148]: Given that it's no longer just the body, we should rename this to `last_closure` or `current_closure`.

**Review by estebank — APPROVED** [review]
r=me after addressing the comments.

File: src/test/ui/expr/malformed_closure/missing_braces_around_block.stderr [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+LL |     ).unwrap();
+   |     ^
+   |
+note: statement found outside of a block
+  --> $DIR/missing_braces_around_block.rs:16:26
+   |
+LL |         println!("{}", a);
+   |         -----------------^ this `;` turns the preceding expression into a statement
+   |         |
+   |         this expression is a statement because of the trailing semicolon
```
Comment (estebank) [inline src/test/ui/expr/malformed_closure/missing_braces_around_block.stderr:16]: Rereading with fresh eyes, I think that this is slightly misleading: the `;` turns the previous _closure_ into a statement, as far as the parser is concerned, but I feel it might be a reasonable "white lie" to not confuse people _too_ much.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 11]
```diff
@@ -1733,11 +1738,28 @@ impl<'a> Parser<'a> {
...
         }
 
-        Ok(self.mk_expr(
+        if self.token.kind == TokenKind::Semi && self.token_cursor.frame.delim == DelimToken::Paren
+        {
+            // It is likely that the closure body is a block but where the
+            // braces have been removed. We will recover and eat the next
+            // statements later in the parsing process.
+            body = self.mk_expr_err(body.span);
+        }
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1747]: I'm somewhat uneasy with this check, but having both `Semi` and `Paren` be true should only happen on malformed code.

File: src/test/ui/expr/malformed_closure/ruby_style_closure.stderr (hunk 6 above)
Comment (estebank) [reply src/test/ui/expr/malformed_closure/ruby_style_closure.stderr]: Done in https://github.com/rust-lang/rust/pull/88719

**Comment by scrabsha** [comment]
Thanks for the approval and sorry for the noise I created. I'll do better next time :)
