### PR TITLE
Make transmuting from fn item types to pointer-sized types a hard error.

### LINKED ISSUE #19925: Set transmute from fn item to type fn lint a hard error
**Original title:** Fn item types should be zero-sized

Per [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md#function-type-polymorphism), every fn in Rust should have its own unique, zero-sized type. This fits with the overall design of closures, which also have their own unique types (but those types are not zero-sized, as they carry the environment). None of these types have any explicit syntax at present. This has been a longstanding plan, but until recently it was not fully implemented. This is changing with PR #31710, which means that some existing code will need to be adjusted to account for the new behavior. This issue attempts to summarize how things work and describe what needs to be changed.
### Zero-sized fn types

What all of this means is that, if you have a function declaration `foo`:

``` rust
// for the purposes of this discussion, all of these different kinds of `fn` declarations are equivalent:
fn foo(x: i32) { ... }
extern "C" fn foo(x: i32);
impl i32 { fn foo(x: self) { ... } }
```

the type of `foo` is **not** `fn(i32)`, as one might expect. Rather, it is a unique, zero-sized marker type that I will just write as `typeof(foo)`. However, `typeof(foo)` can be _coerced_ to a function pointer `fn(i32)`, so you rarely notice this:

``` rust
let x: fn(i32) = foo; // OK, coerces
```

The reason that this matter is that the type `fn(i32)` is not specify to any particular function: it's a function _pointer_. So calling `x()` results in a virtual call, whereas `foo()` is statically dispatched, because the type of `foo` tells us precisely what function is being called. 
### Impact on users

As noted above, coercions mean that most code will continue to work just fine before and after this issue is fully fixed. However, you can tell the difference in a few scenarios. Perhaps the most prominent is using **transmute** to convert a fn item into a fn pointer. This is often done as part of an FFI:

``` rust
extern "C" fn foo(userdata: Box<i32>) {
   ...
}

let f: extern "C" fn(*mut i32) = transmute(foo);
callback(f);
```

Here, transmute is being used to convert the types of the fn arguments. This pattern is now incorrect because, because the type of `foo` is a function **item** (`typeof(foo)`), which is zero-sized, and the target type (`fn()`) is a function pointer, which is not zero-sized. For now, this pattern still works due to some special-cased code in the compiler, but that code is expected to be removed. For future compatibility, this pattern should be rewritten. There are a few possible ways to do this:
- change the original fn declaration to match the expected signature, and do the cast in the fn body (perhaps the best);
- cast the fn item fo a fn pointer before calling transmute, as shown here:
  - `let f: extern "C" fn(*mut i32) = transmute(foo as extern "C" fn(_))`
  - `let f: extern "C" fn(*mut i32) = transmute(foo as usize) /* works too */`

The same applies to transmutes to `*mut fn()`, which were observed frequently in practice. Note though that use of this type is generally incorrect. The intention is typically to describe a function pointer, but just `fn()` alone suffices for that. `*mut fn()` is a pointer to a fn pointer. (Since these values are typically just passed to C code, however, this rarely makes a difference in practice.)
### Current status and implementation trail
- [x] PR #19891 laid the groundwork with fresh, unique types per fn item, but left the back-end work undone
- [x] PR #31710 completes the work.

### PR DESCRIPTION
**Pull request by eddyb**
Closes #19925 by removing the future compatibility lint and the associated workarounds.
This is a `[breaking-change]` if you `transmute` from a function item without casting first.
For more information on how to fix your code, see https://github.com/rust-lang/rust/issues/19925.

### CODE REVIEW

**Comment by eddyb** [comment]
r? @nikomatsakis

I'll start a crater run to see if there's any measurable impact.

**Comment by eddyb** [comment]
Crater report: https://gist.github.com/eddyb/c9a976482be44529e3cdd79ca97db0ce.

This looks pretty bad, much worse than what I remember. It seems a bunch of crates haven't fixed their code, although the warning only now got into beta, so nobody staying on stable has ever seen it.

**Comment by eddyb** [comment]
Looks like `nix` was fixed in https://github.com/nix-rust/nix, but crates.io still has a 3-month old version.
cc @carllerche

**Comment by nikomatsakis** [comment]
I've been meaning to alter the future compatibility warnings so that they
always (at least) warn, even if the user (or cap lints) sets them to allow.
That might also help.

**Comment by bluss** [comment]
@nikomatsakis That's great, because it alerts users that depend on outdated (unfixed) versions.

**Comment by kamalmarhubi** [comment]
I just got the ability to publish and published nix v0.6.0 which builds on nightly.

**Comment by eddyb** [comment]
Crater report 2: https://gist.github.com/eddyb/defd09acfd0c1d6036334d147d7fc040.

@kamalmarhubi As I feared, releasing `0.6.0` wasn't enough (e.g. [notify](https://tools.taskcluster.net/task-inspector/#nd_8WLmASmK6YWaGqqPM6A/0 still uses `0.5.0`).
Could you release `0.5.1` with `0.5.0`'s code + the transmute fix?

**Comment by eddyb** [comment]
@SSheldon [`objc-0.1.8`](https://tools.taskcluster.net/task-inspector/#RDxW3LzRTMmyAzzCmd6EHA/0) is still broken, all but the last 2 `transmute` calls (the ones in the macro) in [`src/message.rs`](https://github.com/SSheldon/rust-objc/blob/0.1.8/src/message.rs) need casts on their arguments.
You would have to release `0.1.9` to solve this, as [some crates](https://crates.io/crates/objc/reverse_dependencies) are still using `0.1.8`.

**Comment by kamalmarhubi** [comment]
@eddyb I just published a v0.5.1, which builds on nightly. Publishing things in earlier release series is harder as we don't have git tags for those releases. I can try to narrow it down, but it will probably not be today.

**Comment by eddyb** [comment]
@kamalmarhubi Thanks for the help with this!
For releases without tags, it might be easier to get the package from crates.io (I don't know how to do that without adding it as a dependency of something and then looking in `~/.cargo/registry/src/`), modify it and republish that.
It might be possible to of course bisect git to find out what sources matches (modulo metadata/files that were not included in crates.io?).

**Comment by eddyb** [comment]
@GuillaumeGomez @gkoz Reminder that [`glib-0.0.8`](https://tools.taskcluster.net/task-inspector/#AD5uSMxHTYyJL6LUxI1Vjg/0) is still broken, `0.0.9` which includes gtk-rs/glib#116 is needed (*not* `0.1.*`).

**Comment by bluss** [comment]
0.0.x versions don't upgrade automatically to anything, so nothing can be done.

**Comment by eddyb** [comment]
@bluss I just checked and [indeed that's the case](https://tools.taskcluster.net/task-inspector/#AD5uSMxHTYyJL6LUxI1Vjg/0) - why do we even allow depending on such an "unfixable" version?!

**Comment by eddyb** [comment]
@nikomatsakis I've went through all of the 50 root regressions and here's what I found:

#### Partially fixed and/or yet unpublished fixes
`nix`, `glib` and `objc` mentioned above
@tomaka tomaka/hlua#73 needs to be published as `0.1.9`.
@Ameliorate `hlua_master` has the same problem.
@tickbh `td_rlua` has [a *similar* problem](https://tools.taskcluster.net/task-inspector/#xwXESVexTmmlxsgs2Oa30g/0) in `0.1.3` (fix would have to go in `0.1.4`).

#### Yet unfixed (I might open PRs for these)
@arturoc [`gstreamer-0.4.0`](https://tools.taskcluster.net/task-inspector/#jOEvvrs3SVahp3P8lj0Atw/0) at https://github.com/arturoc/gstreamer1.0-rs.
@swizard0 [`simple-signal-1.0.5`](https://tools.taskcluster.net/task-inspector/#G7wk-3nkTQyWmYGiQfDg0A/0) with just [one problematic `transmute`](https://github.com/swizard0/rust-simple-signal/blob/da907b9f3a3faccfa894f953770bb818b249705b/src/lib.rs#L96).
@Ginurx [`zmq-rs-0.1.7`](https://tools.taskcluster.net/task-inspector/#D4nyiXTHTmeSHAnu6986gQ/0) with also just [one problematic `transmute`](https://github.com/Ginurx/zmq-rs/blob/19d4cfa842863b05640a3c91e7959a1bf8043d14/src/lib.rs#L317).

**Comment by GuillaumeGomez** [comment]
@eddyb: Fine fine!

**Comment by Ameliorate** [comment]
I've yanked `hlua_master`, so you can check that one off. It wasn't really meant to be used by anyone. I just made it because at the time hlua's github master branch didn't match what was on crates.io.

**Comment by SSheldon** [comment]
@eddyb, if the crates relying on objc 0.1 were upgraded to use 0.2, would that be satisfactory? Or must there be a fix for 0.1? The fix for 0.1 would be a lot of copy-pasting and I'm not super keen on it 😅

Looking at the crates that require 0.1:
* clipboard: I could go send a PR to update this
* metl: it actually has already updated to 0.2 but not published a new version (any plans to publish a new version @burtonageo?)
* glutin_cocoa: this is a defunct fork of cocoa
* uikit: this is mine, I'll go update it

If it's amenable to you I might just take this as an opportunity to get clipboard and uikit updated.

**Comment by eddyb** [comment]
@SSheldon That sounds great, thank you! Having seen the code, I agree that not fixing the `transmute`-laden version is better.

**Comment by eddyb** [comment]
@tomaka Is [glutin_cocoa](https://crates.io/crates/glutin_cocoa) completely unused anymore?
@alexcrichton Is yanking all the versions of such a package an acceptable policy?

**Comment by alexcrichton** [comment]
Yeah it'll work in terms of preventing new dependencies on it, but it's the same standard "lockfiles continue to work" semantics which means it's not 100% fixed if someone's using it.

If no one's using it though then shouldn't matter too much either way.

**Comment by eddyb** [comment]
@alexcrichton It has... downloads. I wonder if that's all from crater though, heh.

**Comment by swizard0** [comment]
I've fixed simple-signal crate, so it should be ok for now.

**Comment by eddyb** [comment]
@swizard0 LGTM, thanks!

**Comment by SSheldon** [comment]
`objc` status:
- [x] `uikit` was updated in SSheldon/rust-uikit@f637a0e1c92ddf87dff9d18c99fa593e089fed58 and 0.0.2 was published to crates.io
- [ ] `metl`/`metal-sys` were updated in burtonageo/metl@a82dd503e1a6b92691216f58daccbf78a4bf9628 and burtonageo/metl#2 tracks publishing these to crates.io
- [ ] `clipboard` was updated in aweinstock314/rust-clipboard#24 and aweinstock314/rust-clipboard#32 tracks publishing that to crates.io

**Comment by kamalmarhubi** [comment]
@eddyb I tracked down 0.3.9 and 0.4.2, and have released nix 0.3.10 and 0.4.3 with the fix.

**Comment by eddyb** [comment]
@brson @nikomatsakis I'm having a bit of trouble with crater, [the third report](https://gist.github.com/eddyb/d6910edf93faf3895bdc0c83a4c6a441) I generated for this PR, today, has some results from 6 days. Do I need to build new compilers to get new results from it?

**Comment by brson** [comment]
@eddyb you shouldn't need to rebuild the compilers, no, but you will see old build results if the new build results don't show up for whatever reason.

**Comment by brson** [comment]
Please let's be careful moving forward with landing this patch.

Maybe there's more we can do during the warning period to monitor progress of moving off of broken features.

**Comment by eddyb** [comment]
@brson The warning is not in stable yet, which makes the whole thing a bit tricky.
If it stays for one cycle, then the next stable will have it (the current beta) and the stable after that will have hard errors (the current nightly).
But to actually have that happen in the future, it has to become a hard error in the nightly before the beta is branched off, prior to the next release date.

**Comment by nikomatsakis** [comment]
@eddyb I think I would prefer to see the warning reach stable for at least one cycle before we make this a hard error. Personally I still sometimes think we should just make transmute "work" in this case, rather than making this an error. (In other words, change the temporary behavior into the defined behavior.)

**Comment by eddyb** [comment]
@nikomatsakis It feels so strange, because of the train model, changing this to a hard error in master even just after the warning has reached stable means that the warning would be there for 2 stable cycles.
AFAICT, "for at least one cycle" could mean 3 or more stable cycles which warn before it turns into a hard error.

**Comment by nikomatsakis** [comment]
@eddyb yes, it's unfortunate in a sense that it takes so long -- but also maybe a good thing, since it gives us plenty of time to gather early feedback. In this *particular case*, (a) the code is not a maintenance burden, which makes feel a bit more relaxed about it; (b) the impact was large, which makes me feel a bit more nervous about making it an error. That said, I guess if we make it an error on nightly, we can roll that back based on feedback from stable.

**Comment by eddyb** [comment]
@nikomatsakis Can we escalate to error by default instead of warning, and remove the workarounds next cycle?

**Comment by nikomatsakis** [comment]
@eddyb it does seem like a good idea to move a bit cautiously -- and shifting to deny by default is a good way to that. What do you think @brson? Also, I wonder if we should move this discussion to https://github.com/rust-lang/rust/issues/19925. (I'd like to be just using the FCP process itself.)

**Comment by brson** [comment]
@nikomatsakis Changing the lint to deny seems smart. If I understand, then people building their own stuff will get a more aggressive admonition, but their deps won't fail. Do we also have the ability to get the change in that displays future-incompatible lints despite `--cap-lints`? That would make sure both types of user see the problem.

**Comment by alexcrichton** [comment]
ping @eddyb, just cleaning out some old PRs, but do you know what the next step for this would be?

**Comment by nikomatsakis** [comment]
It seems like we decided to make the lint go to deny.

**Comment by eddyb** [comment]
@alexcrichton See #34923 for the smaller immediate action. I'll keep this PR in this state (but close it) so we can reuse it at a later date.

**Comment by eddyb** [comment]
Rebased and ran crater. [The report](https://gist.github.com/eddyb/c1e0c18d09af90b6ea1da71d16c9b09a) leaves 3 failing crates:
* [`carto`](https://tools.taskcluster.net/task-inspector/#0hdR-gABSKCfj5prtS_FHg/0) (because of `glib-0.0.7`)
* [`syslog-ng-common`](https://tools.taskcluster.net/task-inspector/#DzmNCXLSQHC1Iy2Ca8doCQ/0) (because of `glib-0.0.8`)
* [`glutin_cocoa-0.1.6`](https://tools.taskcluster.net/task-inspector/#yOp56jZ9QUOG0mga0dZupw/0) (because of `objc-0.1.8`)

All of these are because of dependencies that aren't updated.

Releasing `objc-0.1.9` might be possible, but `glib` is broken forever because they authors kept releasing `0.0.x` even with users (I wish Cargo never supported that versioning scheme, but it's all under the bridge).

**Comment by nikomatsakis** [comment]
@eddyb can we just open PRs for those crates updating their `Cargo.toml`?

@adolfosilva -- it seems like the `carto` crate may break because of a versioning dependency that needs to be updated. However, the repository link in crates.io appears to be wrong or stale. =( Is this package still maintained?

@ihrwein -- would it be possible to release an updated version of `syslog-ng-common` that uses a newer dependency?

@tomaka -- are you maintaining `glutin_cocoa`?

**Comment by adolfosilva** [comment]
@nikomatsakis no, it is not.

**Comment by tomaka** [comment]
> @tomaka -- are you maintaining glutin_cocoa?

No. The `glutin_cocoa` crate is the same as `cocoa`, except published by me because Servo took too much time to publish `cocoa` in my taste.

**Comment by ihrwein** [comment]
> @ihrwein -- would it be possible to release an updated version of syslog-ng-common that uses a newer dependency?

I'm no longer the maintainer, but I sent a PR for upstream. After it's merged, I can release it on crates.io and yank it.

**Comment by nikomatsakis** [comment]
@ihrwein 

> I'm no longer the maintainer, but I sent a PR for upstream. After it's merged, I can release it on crates.io and yank it.

thanks

File: src/librustc/middle/intrinsicck.rs [hunk 1]
```diff
@@ -67,20 +67,6 @@ impl<'a, 'gcx, 'tcx> ExprVisitor<'a, 'gcx, 'tcx> {
...
-                        if size_to == Pointer.size(&self.infcx.tcx.data_layout) => {
-                    // FIXME #19925 Remove this warning after a release cycle.
-                    let msg = format!("`{}` is now zero-sized and has to be cast \
-                                       to a pointer before transmuting to `{}`",
-                                      from, to);
-                    self.infcx.tcx.sess.add_lint(
-                        ::lint::builtin::TRANSMUTE_FROM_FN_ITEM_TYPES, id, span, msg);
-                    return;
-                }
-                _ => {}
```
Comment (nikomatsakis) [inline src/librustc/middle/intrinsicck.rs]: Let's keep this logic, but use it to give a helper error message and probably a unique error code. This will let us move the text from the tracking issue into a `--explain` that covers some of the key concepts here (i.e., that fn items have a unique zero-sized type). But here in the short form we should give a suggestion for how to rewrite. Something like "try `x as fn(_, _) -> _" or whatever is the most concise form we can come up with. 

I think it's important to get the diagnostics here right, this can be a fairly confusing area for people, and I think it'll come up in FFI and other things that people do early on in Rust.

Comment (eddyb) [inline src/librustc/middle/intrinsicck.rs]: TBH I still find it hard to believe that *anyone* needs to ever transmute function pointers.
We maybe need to allow `unsafe extern "C"` -variadic function types that you can coerce to from your own function types - since that is the one case where you can't use a polymorphic wrapper.

Comment (nikomatsakis) [inline src/librustc/middle/intrinsicck.rs]: The point of giving a nice error is helping people to see that they did not need `transmute` in the first place, I think.

Comment (nikomatsakis) [inline src/librustc/middle/intrinsicck.rs]: At minimum giving a custom error code and a message like "cannot transmute a fn item directly into a fn pointer", and then just kind of adapting the text for a `--explain`, would be fine (not doing the extra work to create a suggestion). That seems fairly low effort.

Comment (eddyb) [inline src/librustc/middle/intrinsicck.rs]: Oh I see what you meant, I thought you were only referring to the workaround on the argument to `transmute`, not replacing the whole call.

**Comment by ihrwein** [comment]
I yanked `syslog-ng-common`.

**Comment by nikomatsakis** [comment]
The relevant tracking issue (#19925) has now entered **final-comment period** with intention to convert the forward compat warning into a hard error.

**Comment by est31** [comment]
The FCP is complete: https://github.com/rust-lang/rust/issues/19925

**Comment by nikomatsakis** [comment]
I'd still like to see us keep the nicer error (even if it is a hard error), or at least offer some kind of hint or suggestion about what is happening here and how to fix it.

**Comment by nikomatsakis** [comment]
@wycats was just asking me about an error involving a transmute from a `Option<ZST-fn-type>` to `Option<extern "C" fn()>`. It'd be nice to catch that case in the error too!

**Comment by eddyb** [comment]
@nikomatsakis That shouldn't be too hard, given that we already have code to detect `Option`-like enums, to whitelist `Option<fn(...)>` in the FFI lint. Hopefully I'll get back to this next week.

**Comment by nikomatsakis** [comment]
@eddyb see also https://github.com/rust-lang/rust/issues/19925#issuecomment-280787992, which I think is a nifty idea, though orthogonal-ish from this PR

**Comment by eddyb** [comment]
@nikomatsakis Oh I almost forgot about the `Option` thing, I guess I'll do that now.

File: src/librustc/diagnostics.rs [hunk 2]
```diff
@@ -1725,6 +1725,68 @@ If you want to get command-line arguments, use `std::env::args`. To exit with a
...
+let x: fn(i32) = foo; // OK, coerces
+```
+
+The reason that this matter is that the type `fn(i32)` is not specific to
+any particular function: it's a function _pointer_. So calling `x()` results
+in a virtual call, whereas `foo()` is statically dispatched, because the type
+of `foo` tells us precisely what function is being called.
+
+As noted above, coercions mean that most code continues to work just fine
+before and after this behavior was implemented. However, you can tell the
```
Comment (nikomatsakis) [inline src/librustc/diagnostics.rs]: probably we don't want to say "this behavior was implemented" here...I would just say "Coercions mean that most code doesn't have to be concerned with this distinction."

Comment (eddyb) [inline src/librustc/diagnostics.rs]: Ah that's a better phrasing. I did try to remove temporal indicators, this one was trickiest.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
r=me modulo the extended error description change I suggested. 

I still think we may want to consider making `extern "C" fn` types be pointer-sized, but that's a separate change that ought to go through the RFC process IMO.

**Comment by eddyb** [comment]
@bors retry
* chocolatey network error

**Comment by alexcrichton** [comment]
@bors: retry

* chocolatey error

**Comment by eddyb** [comment]
@bors retry
* I can't see the log... because S3?
