### PR TITLE
Workaround LLVM optimizer bug by not marking &mut pointers as noalias

### LINKED ISSUE #29485: Unwinding through `fn()` references across crates causes the behavior to depend on the optimization level
In `a.rs`
```rust
#![crate_type = "lib"]

pub struct X(pub u8);

impl Drop for X {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

pub fn f(x: &mut X, g: fn()) {
    x.0 = 1;
    g();
    x.0 = 0;
}
```
In `b.rs`
```rust
extern crate a;

fn main() {
    a::f(&mut a::X(0), g);
}

fn g() {
    panic!();
}
```
```
$ rustc -O a.rs && rustc -L . b.rs && ./b
thread '<main>' panicked at 'explicit panic', b.rs:8
0
$ rustc a.rs && rustc -L . b.rs && ./b 
thread '<main>' panicked at 'explicit panic', b.rs:8
1
```
```
$ rustc -V
rustc 1.6.0-nightly (2e07996a9 2015-10-29)
```
NB: Some pre-1.0 nightlies already behaved this way.

### PR DESCRIPTION
**Pull request by dotdash**
LLVM's memory dependence analysis doesn't properly account for calls
that could unwind and thus effectively act as a branching point. This
can lead to stores that are only visible when the call unwinds being
removed, possibly leading to calls to drop() functions with b0rked
memory contents.

As there is no fix for this in LLVM yet and we want to keep
compatibility to current LLVM versions anyways, we have to workaround
this bug by omitting the noalias attribute on &mut function arguments.
Benchmarks suggest that the performance loss by this change is very
small.

Thanks to @RalfJung for pushing me towards not removing too many
noalias annotations and @alexcrichton for helping out with the test for
this bug.

Fixes #29485

### CODE REVIEW

File: src/librustc_trans/trans/attributes.rs [hunk 1]
```diff
@@ -265,7 +265,7 @@ pub fn from_fn_type<'a, 'tcx>(ccx: &CrateContext<'a, 'tcx>, fn_type: ty::Ty<'tcx
                 // on memory dependencies rather than pointer equality
                 let interior_unsafe = mt.ty.type_contents(ccx.tcx()).interior_unsafe();
 
-                if mt.mutbl == hir::MutMutable || !interior_unsafe {
+                if mt.mutbl != hir::MutMutable && !interior_unsafe {
```
Comment (alexcrichton) [inline src/librustc_trans/trans/attributes.rs]: I may not quite be understanding what's going on here, but doesn't this mean that `&usize` will have the `noalias` attribute applied?

**Comment by alexcrichton** [comment]
Looks like the travis failure is legit in that a codegen test needs to be udpated.

File: src/librustc_trans/trans/attributes.rs (hunk 1 above)
Comment (dotdash) [inline src/librustc_trans/trans/attributes.rs]: Yes, and that's intentional. The change is supposed to only affect `&mut` references (and '&' ones with unsafe interiors), because those are the ones that could have stores that would expose this bug.

Comment (dotdash) [inline src/librustc_trans/trans/attributes.rs]: Oh, also note that WRT `&usize` this is not a change, those pointers got the `noalias` attribute before as well (the `||` got changed into a `&&`). As the comment above this change says, `noalias` is about memory dependencies rather than plain pointer equality.

**Comment by dotdash** [comment]
Updated the codegen test, completely forgot about those and only ran the new test before opening the PR

File: src/librustc_trans/trans/attributes.rs (hunk 1 above)
Comment (alexcrichton) [inline src/librustc_trans/trans/attributes.rs]: Oh, right!

**Comment by Ticki** [comment]
This seems like a horrible performance loss. Can you post the benchmarks?

**Comment by dotdash** [comment]
@Ticki the results of the benchmarks we made are in #29485 -- do you have any results that show that "horrible performance loss"?

**Comment by Ticki** [comment]
Well, I haven't benchmarked this change, but in my experience, disabling noalias in GCC gave bad performance.

**Comment by dotdash** [comment]
@Ticki what exactly do you mean by "disabling noalias in GCC"? Making it ignore the `restrict` keyword? Because when comparing to C, that's basically the only change we made here.

**Comment by Ticki** [comment]
`-fno-strict-aliasing`, that is.

**Comment by dotdash** [comment]
That option disables TBAA, which rust does not use at all. The scope of
this change is smaller than that of that option.

-fno-strict-aliasing, that is.

—
Reply to this email directly or view it on GitHub
<https://github.com/rust-lang/rust/pull/31545#issuecomment-184401175>.
