### PR TITLE
Fix up iterator documentation with regards to for loop sugar

### LINKED ISSUE #23851: Document that IntoIterator allows for `for...in` sugar
http://doc.rust-lang.org/core/iter/trait.IntoIterator.html

I think we should mention somewhere in the docs for `IntoIterator` that implementing this trait allows one to write:

```rust
let my_vec = vec![1, 10, 100];
for i in my_vec { ... }
```

instead of

```rust
let my_vec = vec![1, 10, 100];
for i in my_vec.iter() { ... }
```

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #23851

### CODE REVIEW

File: src/libcore/iter.rs [hunk 1]
```diff
@@ -25,23 +25,22 @@
...
 //!
-//! // "Syntactical sugar" taking advantage of an iterator
-//! for &x in values.iter() {
+//! for x in values {
 //!     println!("{}", x);
 //! }
 //!
 //! // Rough translation of the iteration without a `for` iterator.
-//! let mut it = values.iter();
+//! let mut it = values.into_iter();
```
Comment (frewsxcv) [inline src/libcore/iter.rs]: I don't think this will work since `values` gets moved above

Comment (frewsxcv) [inline src/libcore/iter.rs]: Ah, looks like @alexcrichton fixed it in a fixup commit https://github.com/alexcrichton/rust/commit/72f59732d7974767650abfc58f8287212e5a1fba#diff-ced4ae040c5c8672d936a581401ef9ceR44
