### PR TITLE
Prevent broken pipes causing ICEs

### LINKED ISSUE #34376: ICE on "rustc --help | false"
Minimal steps to reproduce: `rustc --help | false`.

Yields an ICE. Tested in latest nightly (2016-06-15) as well as on latest stable(1.9.0).

### PR DESCRIPTION
**Pull request by varkor**
As the private `std::io::print_to` panics if there is an I/O error, which is used by `println!`, the compiler would ICE if one attempted to use a broken pipe (e.g. `rustc --help | false`). This introduces a new (private) macro `try_println!` which allows us to avoid this.

As a side note, it seems this macro might be useful publicly (and actually there seems to be [a crate specifically for this purpose](https://crates.io/crates/try_print/)), though that can probably be left for a future discussion.

One slight alternative approach would be to simply early exit without an error (i.e. exit code `0`), which [this comment](https://github.com/rust-lang/rust/issues/34376#issuecomment-377822526) suggests is the usual approach. I've opted not to take that approach initially, because I think it's more helpful to know when there is a broken pipe.

Fixes #34376.

### CODE REVIEW

File: src/libstd/io/stdio.rs [hunk 1]
```diff
@@ -701,6 +705,14 @@ pub fn _print(args: fmt::Arguments) {
     print_to(args, &LOCAL_STDOUT, stdout, "stdout");
 }
 
+#[unstable(feature = "print_internals",
+           reason = "implementation detail which may disappear or be replaced at any time",
+           issue = "0")]
+#[doc(hidden)]
+pub fn _try_print(args: fmt::Arguments) -> io::Result<()> {
+    try_print_to(args, &LOCAL_STDOUT, stdout)
+}
```
Comment (nikomatsakis) [inline src/libstd/io/stdio.rs]: seems fine, but I feel like we could easily use stable APIs to build this, no? Like, can't we just make `librustc_driver` use `write!` or something?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
I feel like I'd rather not entable libcore/libstd if we can avoid it. Thoughts?

File: src/libstd/io/stdio.rs (hunk 1 above)
Comment (varkor) [reply src/libstd/io/stdio.rs]: The primary reason I did it this way was to make sure `try_println!` had ensured identical behaviour as `println!` (apart from the panic behaviour). I'm not sure how important this is in practice, but felt that it was generally a good idea to keep things familiar, so as not to introduce some inconsistency that would lead to a different issue in the future. (Plus, if we ever want to make such functionality public, it's trivial.)

If you think this is overcomplicating things, though, I could `write` inside `librustc_driver` instead, yeah.

**Comment by varkor** [comment]
> Maybe we should just use that crate? I guess this is minimal enough code it's probably not worth adding an external dependency.

Yes, it really is very minimal. Additionally, the behaviour of the crate isn't exactly the same as `println!` (https://github.com/rust-lang/rust/pull/49606#discussion_r179292311 again relevant).

**Comment by nikomatsakis** [comment]
What's an example of how `println!` and `write!` might differ?

**Comment by varkor** [comment]
My main concern was:
https://github.com/rust-lang/rust/blob/7678d5021e5c984af52f4d1e9147f7a2d6a7ddc3/src/libstd/io/stdio.rs#L701
`write!` wouldn't have this stdout fallback, though I'm not sure if this would ever actually be an issue from the context of `librustc_driver`. I'm not really familiar with the context.

**Comment by nikomatsakis** [comment]
OK, well, I don't really care that much either way. r=me for the compiler bits, but I'd like somebody from @rust-lang/libs to at least glance over the changes to `println!`. 

r? @alexcrichton

**Comment by alexcrichton** [comment]
I'm personally a little concerned about the long-term maintainability of a solution like this, for example this doesn't change anything in `src/librustc_errors`, but doesn't that mean diagnostics will hit broken pipes? If we want to terminate on EPIPE I think we should just reenable the signal handler, right?

**Comment by varkor** [comment]
@alexcrichton: why/where was the signal handler originally disabled?

**Comment by sfackler** [comment]
@varkor https://github.com/rust-lang/rust/blob/f1ea23e2cc72cafad1dc25a06c09ec2de8e323eb/src/libstd/sys/unix/mod.rs#L71

It's disabled by default because it only really makes sense for CLI programs that only touch stdin/stdout/stderr and don't do any e.g. networking.

**Comment by varkor** [comment]
@sfackler: Thanks! I didn't realise that EPIPE triggered SIGPIPE. Are there any reasons to want to ignore SIGPIPE (i.e. is completely removing the signal handler okay)?

Also, are we happy with just exiting, or do we want to trigger an message?

**Comment by varkor** [comment]
Now an EPIPE will simply terminate rustc/rustdoc, by (re-)overriding the SIGPIPE signal handler.

**Comment by pietroalbini** [comment]
Ping from triage @alexcrichton! The author addressed your comments!

**Comment by alexcrichton** [comment]
@bors: r+

er sorry @varkor, I missed the update!
