### PR TITLE
Avoid loading needless proc-macro dependencies

### LINKED ISSUE #37958: Build error with proc_macro crates and cross-compilation
In https://github.com/servo/servo/pull/14292, cross compilation fails with the following log: https://gist.github.com/jdm/ba11e5fe48fcbc186aecb15a857b54a6

xml5ever is a crate that depends on html5ever-atoms, which itself depends on heapsize_derive if the heap_size feature is selected. heapsize_derive defines `#[derive(HeapSizeOf)]` which xml5ever makes no use of.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #37958 when no proc-macros are exported; in particular, without `pub extern crate proc_macros;`, `#![feature(macro_reexport)]`, or `#![feature(use_extern_macros)]`.

I opened https://github.com/rust-lang/cargo/issues/3334 for exported proc macros.

r? @alexcrichton

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nrc

**Comment by nox** [comment]
Could this be reviewed and prioritised? This is blocking rustup in Servo.

File: src/librustc/middle/cstore.rs [hunk 1]
```diff
@@ -67,6 +67,8 @@ pub struct CrateSource {
 
 #[derive(RustcEncodable, RustcDecodable, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Debug)]
 pub enum DepKind {
+    /// A dependency that is only used for its macros, none of which are visible from other crates.
+    UnexportedMacrosOnly,
```
Comment (nrc) [inline src/librustc/middle/cstore.rs]: Are these only used by monomorphised functions or is there some reason to include them. Would be good to comment in any case.

**Review by nrc — APPROVED** [review]
r = me with the comment expanded.

File: src/librustc/middle/cstore.rs (hunk 1 above)
Comment (jseyfried) [inline src/librustc/middle/cstore.rs]: `UnexportedMacrosOnly` are only included in the metadata as placeholders (the `CrateNum` of a dependency is computed from its position in the dependency list) -- I'll add a comment.

Does that answer your question? (not sure how monomorphised functions are relevant)

Comment (jseyfried) [inline src/librustc/middle/cstore.rs]: Oh, I see -- monopolized functions from extern crates might need to access non-visible functions. I don't think this is relevant to macros though, since expansion finishes before monopolization.
