### PR TITLE
Miri: handling of SNaN inputs in `f*::pow` operations

### LINKED ISSUE #4286: Make powf/powi(sNaN, 0) over-approximate both glibc and musl
The C standard annex F.10 says that the result of `x^0 = 1` for all x, even a NaN. For `pown` it explicitly calls out "for all x not a signalling NaN" (and doesn't say what happens on a signalling NaN); for `powf` it just says "any x, even a NaN" -- it is unclear whether that is an intentional difference or not since C generally leaves everything about the behavior of signalling NaNs unspecified. I am not sure what the IEEE spec says. This is a somewhat odd case as usually in C, operations behave the same for qNaN and sNaN, but some widely-used libc implementations return a qNaN for `sNan^0` but return 1 for `qNan^0` (the latter part being required by the standard), therefore clearly distinguishing qNaN and sNaN.

The "easiest" choice for us is to say that our functions return either 1 or a NaN non-deterministically, and if they do return a NaN the usual NaN propagation rules apply -- since one input is an sNaN, the payload if the returned NaN is completely arbitrary (in particular, it can be a qNaN or an sNaN). glibc and musl seem to disagree on the result here (see https://rust.godbolt.org/z/chsbv5v4d), so requiring more consistent behavior would involve convincing one of them that they are wrong.

@tgross35 does that sound reasonable? Should https://doc.rust-lang.org/nightly/std/primitive.f32.html#method.powf talk and friends about this case or is that not worth it?

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
fixes [miri/#4286](https://github.com/rust-lang/miri/issues/4286) and related to rust-lang/rust#138062 and [miri/#4208](https://github.com/rust-lang/miri/issues/4208#issue-2879058184).

For the following cases of the powf or powi operations, Miri returns either `1.0` or an arbitrary `NaN`:
- `powf(SNaN, 0.0)`
- `powf(1.0, SNaN)`
- `powi(SNaN, 0)`

Also added a macro in `miri/tests/pass/float.rs` which conveniently checks if both are indeed returned from such an operation.

Made these changes in the rust repo so I could test against stdlib, since these were impacted some time ago and were fixed in rust-lang/rust#138062. Tested with:
```fish
env MIRIFLAGS=-Zmiri-many-seeds ./x miri --no-fail-fast std core coretests -- f32 f64
```
This was successful. This does take a while, so I recommend using `--no-doc` and separate use of `f32` or `f64`

The pr is somewhat split up into 3 main commits, which implement the cases described above. The first commit also introduces the macro, and the last commit is just a global refactor of some things.

r? @RalfJung

### CODE REVIEW

File: src/tools/miri/src/intrinsics/mod.rs [hunk 1]
```diff
@@ -501,56 +502,97 @@ fn apply_random_float_error_to_imm<'tcx>(
...
 }
 
+/// Returns either a SNaN or a QNaN, with a randomly generated payload.
+fn random_nan<S: Semantics>(rng: &mut StdRng) -> IeeeFloat<S> {
+    if rng.random() {
+        IeeeFloat::<S>::snan(Some(rng.random()))
+    } else {
+        IeeeFloat::<S>::qnan(Some(rng.random()))
+    }
+}
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]: We already have extensive logic for random NaNs (`generate_nan`), please use that instead.

File: src/tools/miri/src/intrinsics/mod.rs [hunk 2]
```diff
@@ -501,56 +502,97 @@ fn apply_random_float_error_to_imm<'tcx>(
...
-        // FIXME(#4286): The C ecosystem is inconsistent with handling sNaN's, some return 1 others propogate
-        // the NaN. We should return either 1 or the NaN non-deterministically here.
-        // But for now, just handle them all the same.
-        // x^(±0) = 1 for any x, even a NaN
-        ("powf32" | "powf64", [_, exp]) if exp.is_zero() => Some(one),
+        // 1^y = 1 for any y, even a NaN, *but* not a SNaN
+        ("powf32" | "powf64", [base, exp]) if *base == one => {
+            let rng = ecx.machine.rng.get_mut();
+            // Handle both the musl and glibc cases non-deterministically.
+            if !exp.is_signaling() || rng.random() { one } else { random_nan(rng) }
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]: This is too compact to be readable. Also, this needs to honor the (new) `float_nondet` flag.

```rust
let return_nan = exp.is_signaling() && ecx.machine.float_nondet && rng.random();
if return_nan { ...
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 3]
```diff
@@ -501,56 +502,97 @@ fn apply_random_float_error_to_imm<'tcx>(
...
+        }
+
+        // x^(±0) = 1 for any x, even a NaN, *but* not a SNaN
+        ("powf32" | "powf64", [base, exp]) if exp.is_zero() => {
+            let rng = ecx.machine.rng.get_mut();
+            // Handle both the musl and glibc cases non-deterministically.
+            if !base.is_signaling() || rng.random() { one } else { random_nan(rng) }
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]: Same comment as above.

File: src/tools/miri/tests/pass/float.rs [hunk 4]
```diff
@@ -1067,17 +1067,39 @@ pub fn libm() {
...
+            }
+
+            let op_as_str = stringify!($pow_op);
+
+            assert!(nan_seen && one_seen, "{} should return both `NaN` or `1.0` randomly", op_as_str);
+        }};
+    }
+
+    // x^(SNaN) = (1 | NaN)
+    test_snan_nondet!(f32::powf(SNAN_F32, 0.0));
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/float.rs]: Please don't invent new logic, but use existing logic. We already have `ensure_nondet`.

**Comment by RalfJung** [comment]
Sorry for the slow review, I was traveling. And due to an upcoming deadline I'll be quite busy for another 2 weeks, unfortunately.

**Comment by RalfJung** [comment]
@bors2 try jobs=x86_64-gnu-aux

**Comment by LorrensP-2158466** [comment]
> Sorry for the slow review, I was traveling. And due to an upcoming deadline I'll be quite busy for another 2 weeks, unfortunately.

No worries! I had exams, so I couldn't respond to the review if it had been done sooner.

File: src/tools/miri/src/intrinsics/mod.rs (hunk 1 above)
Comment (LorrensP-2158466) [reply src/tools/miri/src/intrinsics/mod.rs]: oh yeah 🤦

File: src/tools/miri/src/intrinsics/mod.rs [hunk 5]
```diff
@@ -496,49 +497,84 @@ fn apply_random_float_error_to_imm<'tcx>(
...
+        ("expf32" | "expf64" | "exp2f32" | "exp2f64", [input]) if input.is_zero() => one,
 
         // (-1)^(±INF) = 1
-        ("powf32" | "powf64", [base, exp]) if *base == -one && exp.is_infinite() => Some(one),
+        ("powf32" | "powf64", [base, exp]) if *base == -one && exp.is_infinite() => one,
+
+        // 1^y = 1 for any y, even a NaN, *but* not a SNaN
+        ("powf32" | "powf64", [base, exp]) if *base == one => {
+            let rng = ecx.machine.rng.get_mut();
+            let return_nan = ecx.machine.float_nondet && rng.random() && exp.is_signaling();
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]: I had a specific logic in mind when I suggested exactly this order earlier. :)
```suggestion
            // SNaN exponents get special treatment: they might return 1, or a NaN.
            let return_nan = exp.is_signaling() && ecx.machine.float_nondet && rng.random();
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 6]
```diff
@@ -496,49 +497,84 @@ fn apply_random_float_error_to_imm<'tcx>(
...
-
-        // 1^y = 1 for any y, even a NaN.
-        ("powf32" | "powf64", [base, _]) if *base == one => Some(one),
+        ("expf32" | "expf64" | "exp2f32" | "exp2f64", [input]) if input.is_zero() => one,
 
         // (-1)^(±INF) = 1
-        ("powf32" | "powf64", [base, exp]) if *base == -one && exp.is_infinite() => Some(one),
+        ("powf32" | "powf64", [base, exp]) if *base == -one && exp.is_infinite() => one,
+
+        // 1^y = 1 for any y, even a NaN, *but* not a SNaN
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]:
```suggestion
        // 1^y = 1 for any y, even a NaN
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 7]
```diff
@@ -496,49 +497,84 @@ fn apply_random_float_error_to_imm<'tcx>(
...
+            // Handle both the musl and glibc cases non-deterministically.
+            if return_nan { ecx.generate_nan(args) } else { one }
+        }
 
-        // FIXME(#4286): The C ecosystem is inconsistent with handling sNaN's, some return 1 others propogate
-        // the NaN. We should return either 1 or the NaN non-deterministically here.
-        // But for now, just handle them all the same.
-        // x^(±0) = 1 for any x, even a NaN
-        ("powf32" | "powf64", [_, exp]) if exp.is_zero() => Some(one),
+        // x^(±0) = 1 for any x, even a NaN, *but* not a SNaN
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]:
```suggestion
        // x^(±0) = 1 for any x, even a NaN
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 8]
```diff
@@ -496,49 +497,84 @@ fn apply_random_float_error_to_imm<'tcx>(
...
+        ("powf32" | "powf64", [base, exp]) if exp.is_zero() => {
+            let rng = ecx.machine.rng.get_mut();
+            let return_nan = ecx.machine.float_nondet && rng.random() && base.is_signaling();
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]:
```suggestion
            // SNaN bases get special treatment: they might return 1, or a NaN.
            let return_nan = base.is_signaling() && ecx.machine.float_nondet && rng.random();
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 9]
```diff
@@ -496,49 +497,84 @@ fn apply_random_float_error_to_imm<'tcx>(
...
 /// Returns `Some(output)` if `powi` (called `pown` in C) results in a fixed value specified in the C standard
 /// (specifically, C23 annex F.10.4.6) when doing `base^exp`. Otherwise, returns `None`.
-fn fixed_powi_float_value<S: Semantics>(base: IeeeFloat<S>, exp: i32) -> Option<IeeeFloat<S>> {
-    match (base.category(), exp) {
-        // x^0 = 1, if x is not a Signaling NaN
-        // FIXME(#4286): The C ecosystem is inconsistent with handling sNaN's, some return 1 others propogate
-        // the NaN. We should return either 1 or the NaN non-deterministically here.
-        // But for now, just handle them all the same.
-        (_, 0) => Some(IeeeFloat::<S>::one()),
+// TODO: I'm not sure what I should document here about pown(1, SNaN) since musl and glibc do the same and the C standard is explicit here.
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]:
```suggestion
/// For SNaN treatment, we are consistent with `powf`above.
/// (We wouldn't have two, unlike powf all implementations seem to agree for powi,
/// but for now we are maximally conservative.)
```

File: src/tools/miri/src/intrinsics/mod.rs [hunk 10]
```diff
@@ -17,6 +17,7 @@ use self::atomic::EvalContextExt as _;
 use self::helpers::{ToHost, ToSoft, check_intrinsic_arg_count};
 use self::simd::EvalContextExt as _;
 use crate::math::{IeeeExt, apply_random_float_error_ulp};
+use crate::operator::EvalContextExt as _;
```
Comment (RalfJung) [inline src/tools/miri/src/intrinsics/mod.rs]: This should not be needed, the `use crate::*` takes care of it.
```suggestion
```

File: src/tools/miri/tests/pass/float.rs [hunk 11]
```diff
@@ -1500,4 +1489,18 @@ fn test_non_determinism() {
     test_operations_f32(12., 5.);
     test_operations_f64(19., 11.);
     test_operations_f128(25., 18.);
+
+
+    // x^(SNaN) = (1 | NaN)
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/float.rs]:
```suggestion
    // SNaN^0 = (1 | NaN)
```

File: src/tools/miri/tests/pass/float.rs [hunk 12]
```diff
@@ -1500,4 +1489,18 @@ fn test_non_determinism() {
...
+    ensure_nondet(|| f32::powf(SNAN_F32, 0.0));
+    ensure_nondet(|| f64::powf(SNAN_F64, 0.0));
+
+    // 1^(SNaN) = (1 | NaN)
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/float.rs]:
```suggestion
    // 1^SNaN = (1 | NaN)
```

File: src/tools/miri/tests/pass/float.rs [hunk 13]
```diff
@@ -1500,4 +1489,18 @@ fn test_non_determinism() {
...
+    ensure_nondet(|| f32::powf(1.0, SNAN_F32));
+    ensure_nondet(|| f64::powf(1.0, SNAN_F64));
+
+    // same as powf (keep it consistent):
+    // x^(SNaN) = (1 | NaN)
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/float.rs]:
```suggestion
    // x^SNaN = (1 | NaN)
```

**Comment by RalfJung** [comment]
Thanks! I added a commit with some more tests. Should be good to go now :)
@bors r+ rollup

**Comment by LorrensP-2158466** [comment]
> Thanks! I added a commit with some more tests. Should be good to go now :)

Oh wow, thanks!
