### PR TITLE
Don't ICE in `might_permit_raw_init` if reference is polymorphic

### LINKED ISSUE #107999: ICE: `need to be able to compute layouts: Unknown(T)` running miri with `-Zunpretty-mir`
### Code
You can repro with `RUSTFLAGS="-Zunpretty=mir" MIRIFLAGS="-Zmir-opt-level=3" cargo miri run`
```Rust
// This test checks that calling `mem::{uninitialized,zeroed}` with certain types results
// in a lint.

use std::mem::{self};
struct Wrap<T> { wrapped: T }

#[allow(unused)]
fn generic<T: 'static>() {
    unsafe {
        let _val: Wrap<&'static T> = mem::uninitialized(); //~ ERROR: does not permit being left uninitialized
    }
}

fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (20081880a 2023-02-13)
binary: rustc
commit-hash: 20081880ad2a98bbc8c8293f96c5b284d1584d86
commit-date: 2023-02-13
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
warning: use of deprecated function `std::mem::uninitialized`: use `mem::MaybeUninit` instead
  --> src/main.rs:10:43
   |
10 |         let _val: Wrap<&'static T> = mem::uninitialized(); //~ ERROR: does not permit being left uninitialized
   |                                           ^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: field `wrapped` is never read
 --> src/main.rs:5:18
  |
5 | struct Wrap<T> { wrapped: T }
  |        ----      ^^^^^^^
  |        |
  |        field in this struct
  |
  = note: `#[warn(dead_code)]` on by default

warning: the type `Wrap<&T>` does not permit being left uninitialized
  --> src/main.rs:10:38
   |
10 |         let _val: Wrap<&'static T> = mem::uninitialized(); //~ ERROR: does not permit being left uninitialized
   |                                      ^^^^^^^^^^^^^^^^^^^^
   |                                      |
   |                                      this code causes undefined behavior when executed
   |                                      help: use `MaybeUninit<T>` instead, and only call `assume_init` after initialization is done
   |
   = note: `Wrap<&T>` must be non-null
note: because references must be non-null (in this struct field)
  --> src/main.rs:5:18
   |
5  | struct Wrap<T> { wrapped: T }
   |                  ^^^^^^^^^^
   = note: `#[warn(invalid_value)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'need to be able to compute layouts: Unknown(T)', compiler/rustc_const_eval/src/util/might_permit_raw_init.rs:111:48
stack backtrace:
   0:     0x7febf276a9ea - std::backtrace_rs::backtrace::libunwind::trace::h599c8a609f9333f9
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7febf276a9ea - std::backtrace_rs::backtrace::trace_unsynchronized::hd98c4236d5e12dd3
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7febf276a9ea - std::sys_common::backtrace::_print_fmt::h5e56057600010abc
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7febf276a9ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6c880a29175ff5a3
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7febf27caafe - core::fmt::write::hfc0242af538b8a46
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/core/src/fmt/mod.rs:1232:17
   5:     0x7febf275b005 - std::io::Write::write_fmt::h01aa30c6b6ac7c12
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/io/mod.rs:1684:15
   6:     0x7febf276a7b5 - std::sys_common::backtrace::_print::hffab19929157fc64
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7febf276a7b5 - std::sys_common::backtrace::print::hcc10add6529763f5
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7febf276d54f - std::panicking::default_hook::{{closure}}::h7b790581a0467591
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/panicking.rs:267:22
   9:     0x7febf276d28b - std::panicking::default_hook::hea529077c0649ab7
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/panicking.rs:286:9
  10:     0x7febf5adcca4 - <rustc_driver_impl[25fd4ad55bd4d290]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[b6202784567cb4e4]::ops::function::FnOnce<(&core[b6202784567cb4e4]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7febf276dd8a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9025e888b11b840d
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/alloc/src/boxed.rs:2002:9
  12:     0x7febf276dd8a - std::panicking::rust_panic_with_hook::hbf88635db69aa1e9
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/panicking.rs:692:13
  13:     0x7febf276db09 - std::panicking::begin_panic_handler::{{closure}}::h0a5dea2fedd0d5a5
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/panicking.rs:579:13
  14:     0x7febf276ae8c - std::sys_common::backtrace::__rust_end_short_backtrace::h2507953ca43dc350
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7febf276d812 - rust_begin_unwind
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/panicking.rs:575:5
  16:     0x7febf27c74a3 - core::panicking::panic_fmt::hf2288fbc08000d27
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/core/src/panicking.rs:64:14
  17:     0x7febf27c7a33 - core::result::unwrap_failed::h949aaa38a1828029
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/core/src/result.rs:1790:5
  18:     0x7febf519ebb1 - rustc_const_eval[344787e6075ccab3]::util::might_permit_raw_init::might_permit_raw_init_lax
  19:     0x7febf519e2ee - rustc_const_eval[344787e6075ccab3]::util::might_permit_raw_init::might_permit_raw_init_lax
  20:     0x7febf519dfb9 - rustc_const_eval[344787e6075ccab3]::util::might_permit_raw_init::might_permit_raw_init
  21:     0x7febf51fa047 - <rustc_query_system[6e05d7961ccd4849]::dep_graph::graph::DepGraph<rustc_middle[26406bea1d07e151]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[26406bea1d07e151]::ty::context::TyCtxt, rustc_middle[26406bea1d07e151]::ty::ParamEnvAnd<rustc_target[88529097bdb44244]::abi::TyAndLayout<rustc_middle[26406bea1d07e151]::ty::Ty>>, bool>
  22:     0x7febf63882d9 - rustc_query_system[6e05d7961ccd4849]::query::plumbing::try_execute_query::<rustc_query_impl[38ddc62a235656bd]::queries::permits_uninit_init, rustc_query_impl[38ddc62a235656bd]::plumbing::QueryCtxt>
  23:     0x7febf63ad825 - rustc_query_system[6e05d7961ccd4849]::query::plumbing::get_query::<rustc_query_impl[38ddc62a235656bd]::queries::permits_uninit_init, rustc_query_impl[38ddc62a235656bd]::plumbing::QueryCtxt, rustc_middle[26406bea1d07e151]::dep_graph::dep_node::DepKind>
  24:     0x7febf642aa67 - <rustc_query_impl[38ddc62a235656bd]::Queries as rustc_middle[26406bea1d07e151]::ty::query::QueryEngine>::permits_uninit_init
  25:     0x7febf61b9f6e - rustc_mir_transform[d56b548caf7a8cfa]::instcombine::intrinsic_assert_panics::mem_uninitialized_valid_predicate
  26:     0x7febf4f7d8a6 - <rustc_mir_transform[d56b548caf7a8cfa]::instcombine::InstCombine as rustc_middle[26406bea1d07e151]::mir::MirPass>::run_pass
  27:     0x7febf41a1fe8 - rustc_mir_transform[d56b548caf7a8cfa]::optimized_mir
  28:     0x7febf4198ff6 - <rustc_query_system[6e05d7961ccd4849]::dep_graph::graph::DepGraph<rustc_middle[26406bea1d07e151]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[26406bea1d07e151]::ty::context::TyCtxt, rustc_span[f166845bd5138698]::def_id::DefId, &rustc_middle[26406bea1d07e151]::mir::Body>
  29:     0x7febf413771d - rustc_query_system[6e05d7961ccd4849]::query::plumbing::try_execute_query::<rustc_query_impl[38ddc62a235656bd]::queries::optimized_mir, rustc_query_impl[38ddc62a235656bd]::plumbing::QueryCtxt>
  30:     0x7febf4135484 - <rustc_middle[26406bea1d07e151]::ty::context::TyCtxt>::instance_mir
  31:     0x7febf5feda35 - rustc_middle[26406bea1d07e151]::mir::pretty::write_mir_pretty
  32:     0x7febf5ab4882 - rustc_driver_impl[25fd4ad55bd4d290]::pretty::print_after_hir_lowering
  33:     0x7febf5aa02cb - <rustc_middle[26406bea1d07e151]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}::{closure#2}::{closure#1}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>
  34:     0x7febf4d0aa30 - <rustc_interface[cf329bccbcde2f18]::interface::Compiler>::enter::<rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}::{closure#2}, core[b6202784567cb4e4]::result::Result<core[b6202784567cb4e4]::option::Option<rustc_interface[cf329bccbcde2f18]::queries::Linker>, rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>
  35:     0x7febf4d058c4 - rustc_span[f166845bd5138698]::with_source_map::<core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>, rustc_interface[cf329bccbcde2f18]::interface::run_compiler<core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>, rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  36:     0x7febf4d053d4 - <scoped_tls[9115c50d9b00df7e]::ScopedKey<rustc_span[f166845bd5138698]::SessionGlobals>>::set::<rustc_interface[cf329bccbcde2f18]::interface::run_compiler<core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>, rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}>::{closure#0}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>
  37:     0x7febf4d04ad2 - std[b5e4c008489c853a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf329bccbcde2f18]::util::run_in_thread_pool_with_globals<rustc_interface[cf329bccbcde2f18]::interface::run_compiler<core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>, rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}>::{closure#0}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>
  38:     0x7febf5371eac - <<std[b5e4c008489c853a]::thread::Builder>::spawn_unchecked_<rustc_interface[cf329bccbcde2f18]::util::run_in_thread_pool_with_globals<rustc_interface[cf329bccbcde2f18]::interface::run_compiler<core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>, rustc_driver_impl[25fd4ad55bd4d290]::run_compiler::{closure#1}>::{closure#0}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b6202784567cb4e4]::result::Result<(), rustc_errors[51cf6c1aaeeb3d69]::ErrorGuaranteed>>::{closure#1} as core[b6202784567cb4e4]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7febf2777d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h11a55f6f3d84245d
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/alloc/src/boxed.rs:1988:9
  40:     0x7febf2777d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd367d709d06ebfbd
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/alloc/src/boxed.rs:1988:9
  41:     0x7febf2777d23 - std::sys::unix::thread::Thread::new::thread_start::h340e26124c1b592b
                               at /rustc/20081880ad2a98bbc8c8293f96c5b284d1584d86/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7febf24208fd - <unknown>
  43:     0x7febf24a2d20 - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (20081880a 2023-02-13) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -Z unpretty=mir -Z mir-opt-level=3

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [permits_uninit_init] checking to see if `Wrap<&T>` permits being left uninit
#1 [optimized_mir] optimizing MIR for `generic`
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Emitting optimized MIR for a polymorphic function may require computing layout of a type that isn't (yet) known. This happens in the instcombine pass, for example. Let's fail gracefully in that condition.

cc @saethlin
fixes #107999

### CODE REVIEW

File: tests/ui/lint/invalid_value-polymorphic.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// compile-flags: --emit=mir --crate-type=lib -Zmir-opt-level=3
```
Comment (compiler-errors) [inline tests/ui/lint/invalid_value-polymorphic.rs:1]: Hm, don't need `--emit=mir` either.

Comment (saethlin) [reply tests/ui/lint/invalid_value-polymorphic.rs:1]: Yeah, if you really want you could use `-Zmir-enable-passes=+InstCombine` and trim the reproducer down all the way to just calling the intrinsic in question, `core::intrinsics::mem_uninitialized_valid::<&T>();`

File: tests/ui/lint/invalid_value-polymorphic.rs [hunk 2]
```diff
@@ -0,0 +1,8 @@
+// compile-flags: --crate-type=lib -Zmir-enable-passes=+InstCombine -Zinline-mir
```
Comment (saethlin) [inline tests/ui/lint/invalid_value-polymorphic.rs:1]:
```suggestion
// compile-flags: --crate-type=lib -Zmir-enable-passes=+InstCombine
```

File: tests/ui/lint/invalid_value-polymorphic.rs [hunk 3]
```diff
@@ -0,0 +1,8 @@
...
+// build-pass
+
+#![feature(core_intrinsics)]
+
+pub fn generic<T: 'static>() {
```
Comment (saethlin) [inline tests/ui/lint/invalid_value-polymorphic.rs:6]:
```suggestion
pub fn generic<T>() {
```

File: compiler/rustc_const_eval/src/util/might_permit_raw_init.rs [hunk 4]
```diff
@@ -108,7 +108,11 @@ fn might_permit_raw_init_lax<'tcx>(
 
     // Special magic check for references and boxes (i.e., special pointer types).
     if let Some(pointee) = this.ty.builtin_deref(false) {
-        let pointee = cx.layout_of(pointee.ty).expect("need to be able to compute layouts");
+        let Ok(pointee) = cx.layout_of(pointee.ty) else {
+            // Reference is too polymorphic, it has a layout but the pointee does not.
+            assert!(pointee.ty.needs_subst());
+            return false;
```
Comment (compiler-errors) [inline compiler/rustc_const_eval/src/util/might_permit_raw_init.rs:114]: oh, lol, this is totally wrong. this is *`might_permit_raw_init_lax`*, not `does_permit_raw_init_lax` :/ this probably should return `true`...

@saethlin, are you sure that it's valid to instcombine away an uninit validity assertion in this case? really we should be returning something ternary -- yes, no, or "too generic" (or at least, "unknown layout"), and in the case of the last option, we don't do anything in the optimization.

Comment (saethlin) [reply compiler/rustc_const_eval/src/util/might_permit_raw_init.rs:114]: Not sure what you're asking, but I'll guess.

If you are asking me what the correct thing to do instead of ICEing here is, no idea. The upstream effect here should be not applying the optimization- we don't know if `T` has alignment > 1, in which case the 0x1-filling is invalid.

If you're asking about the code I added to InstCombine, I intended to nab that directly from what codegen does when it decides to emit a panic or not for that intrinsic. Now it's a fair question as to whether what codegen does just behaves nonsensically when given a generic, if code is supposed to be monomorphized at that stage.

Comment (compiler-errors) [reply compiler/rustc_const_eval/src/util/might_permit_raw_init.rs]: What I'm saying is that it's probably not correct to return either `false` (like I did) or `true` if we can't get the layout of the pointee in this function. 

[CI failure](https://github.com/rust-lang/rust/pull/108012#issuecomment-1428863945) shows that `false` is bad because we're optimizing away perfectly fine polymorphic functions, and `true` is also probably not great, since we're dropping this assertion which may be false later once things are monomorphized. Added a mir-opt test to show that behavior in the first commit in this PR.

Second PR in this stack makes the queries you added fallible, so we can handle the `LayoutError`s gracefully and not perform the optimization in that case. It duplicates a bit of work, since we may have to call the layout query twice on some code paths, but oh well.

Comment (saethlin) [reply compiler/rustc_const_eval/src/util/might_permit_raw_init.rs]: > and `true` is also probably not great, since we're dropping this assertion

If this function is not allowed to have false positives maybe it shouldn't be called `might_`

File: compiler/rustc_middle/src/query/mod.rs [hunk 5]
```diff
@@ -2138,12 +2138,12 @@ rustc_queries! {
...
-    query permits_uninit_init(key: ty::ParamEnvAnd<'tcx, TyAndLayout<'tcx>>) -> bool {
-        desc { "checking to see if `{}` permits being left uninit", key.value.ty }
+    query might_permit_uninit_init(key: ty::ParamEnvAnd<'tcx, Ty<'tcx>>) -> Result<bool, ty::layout::LayoutError<'tcx>> {
+        desc { "checking to see if `{}` permits being left uninit", key.value }
     }
 
-    query permits_zero_init(key: ty::ParamEnvAnd<'tcx, TyAndLayout<'tcx>>) -> bool {
-        desc { "checking to see if `{}` permits being left zeroed", key.value.ty }
+    query might_permit_zero_init(key: ty::ParamEnvAnd<'tcx, Ty<'tcx>>) -> Result<bool, ty::layout::LayoutError<'tcx>> {
+        desc { "checking to see if `{}` permits being left zeroed", key.value }
```
Comment (oli-obk) [inline compiler/rustc_middle/src/query/mod.rs:2146]: add doc comments explaining that the `might` refers to "we don't know if this returns `Err`", not that the bool is a "maybe"

Comment (RalfJung) [reply compiler/rustc_middle/src/query/mod.rs:2146]: Might be better to keep the old name then? We don't say "might" for all `Result<bool>` functions, do we?

File: compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs [hunk 6]
```diff
@@ -640,7 +640,8 @@ fn codegen_regular_intrinsic_call<'tcx>(
         sym::assert_inhabited | sym::assert_zero_valid | sym::assert_mem_uninitialized_valid => {
             intrinsic_args!(fx, args => (); intrinsic);
 
-            let layout = fx.layout_of(substs.type_at(0));
+            let ty = substs.type_at(0);
+            let layout = fx.layout_of(ty);
```
Comment (RalfJung) [inline compiler/rustc_codegen_cranelift/src/intrinsics/mod.rs:644]: It's a bit of a bummer that we now always do 2 layout queries here, but it's probably not too bad.

File: compiler/rustc_const_eval/src/util/might_permit_raw_init.rs (hunk 4 above)
Comment (RalfJung) [reply compiler/rustc_const_eval/src/util/might_permit_raw_init.rs]: The function is intended to definitely answer whether we will emit a panic or not. Optimizations shouldn't change that behavior.

We don't always emit panics fully aggressively (that depends on compiler flags), so in a sense there are false negatives allowed.

File: compiler/rustc_middle/src/query/mod.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/query/mod.rs:2146]: 😄 I thought so, too, but didn't want to bring it up

**Comment by saethlin** [comment]
Just been musing about this... I'm pretty sure that all of the MIR optimization value derived here is from deleting the `is_inhabited` assertion. Initially I was concerned that the ICE here pointed at a deeper issue in the compiler.

But if the solution that preserves the optimizations of the zero init and mem_uninit init paths costs complexity elsewhere in the compiler, or especially if it makes compilation slower due to the additional queries, we should probably just delete the InstCombine for those intrinsics, and only keep the one that checks for inhabited types.

**Comment by compiler-errors** [comment]
> But if the solution that preserves the optimizations of the zero init and mem_uninit init paths costs complexity elsewhere in the compiler, or especially if it makes compilation slower due to the additional queries

I don't think that this implementation is significantly more complex, and I guess we can see if compilation is slower with

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
Spurious it seems

@bors retry
