### PR TITLE
Cache const eval queries

### LINKED ISSUE #48846: 50-110% compilation time regressions due to miri
It's not clear yet whether mir interpretation is the culprit or some changes that crept into the same PR.

Perf data: http://perf.rust-lang.org/compare.html?start=cdcca786468a71375584bb48e3093790c91084f7&end=c90f68224b069f5bb2a80e30e2737e4bb17c1466&stat=instructions:u

cc @nikomatsakis @michaelwoerister 

# Important regressions to investigate

* [ ] tuple-stress | avg: 35.0% | min: 9.8% | max: 109.4%
  - clean-incremental is a >100% hit! The rest are small.
* [ ] tuple-stress-opt | avg: 45.9% | min: 23.1% | max: 109.1%
  - same, clean-incremental is a >100% hit!
* [ ] encoding-opt | avg: 48.9% | min: 7.0% | max: 97.6%
  - clean incremental-opt
  - patched incremental: println-opt
* [ ] encoding | avg: 56.3% | min: 18.1% | max: 94.9%
  - clean is ~ 20%, as is baseline incremental
  - incremental cases are almost 100%
* [ ] coercions-opt | avg: 46.9% | min: 31.8% | max: 74.6%
  - pretty universally bad, though incremental hurts worse
* [ ] coercions | avg: 37.0% | min: 24.3% | max: 66.6%
  - pretty universally bad, though incremental hurts worse
* [ ] html5ever-opt | avg: 18.3% | min: 5.6% | max: 41.3%
  - incremental
* [ ] inflate | avg: 29.4% | min: 1.3% | max: 40.4%
  - universally bad, though incremental hurts worse
* [ ] regex-opt | avg: -0.2% | min: -18.0% | max: 4.7%
  - patched incremental: byte frequencies-opt
* [ ] script-servo-opt | avg: 4.8% | min: 0.7% | max: 12.1%
  - clean incremental-opt
* [ ] script-servo | avg: 6.0% | min: 1.7% | max: 11.6%
  - clean incremental
* [ ] inflate-opt | avg: 7.7% | min: 1.2% | max: 11.6%
  - incremental cases primarily

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #48846 (I think, still running more perf tests, but tuple-stress stops recomputing any constants)

r? @michaelwoerister

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors try

(we should run real perf tests first I guess)

**Comment by oli-obk** [comment]
ping @simulacrum can you run a perf test?

**Comment by oli-obk** [comment]
hmm... while this works and passes tests, it can cause AllocIds for statics to exist without a corresponding Allocation when running with incremental, which causes an ICE.

**Comment by Mark-Simulacrum** [comment]
Perf started for 1096950c850a1c21d1e8a5b1caf6593da10997bf.

**Comment by oli-obk** [comment]
Okay. I figured it out. incremental caches only works for queries that take a single DefId. You can get the query to get serialized, but the inverse won't work (and there's no compile-time error :cry: ).

So now I implemented it from scratch.

**Comment by oli-obk** [comment]
This should now improve incremental builds compared to pre-miri. Not just undo the regression.

File: src/librustc/ty/maps/config.rs [hunk 1]
```diff
@@ -156,6 +156,18 @@ impl<'tcx> QueryDescription<'tcx> for queries::const_eval<'tcx> {
     fn describe(tcx: TyCtxt, key: ty::ParamEnvAnd<'tcx, GlobalId<'tcx>>) -> String {
         format!("const-evaluating `{}`", tcx.item_path_str(key.value.instance.def.def_id()))
     }
+
+    #[inline]
+    fn cache_on_disk(key: Self::Key) -> bool {
+        key.value.instance.def_id().is_local()
```
Comment (michaelwoerister) [inline src/librustc/ty/maps/config.rs]: Can non-local consts be loaded from metadata? Otherwise we just might want to cache everything.

File: src/librustc/ty/maps/on_disk_cache.rs [hunk 2]
```diff
@@ -223,6 +231,45 @@ impl<'sess> OnDiskCache<'sess> {
                 encode_query_results::<trans_fn_attrs, _>(tcx, enc, qri)?;
             }
 
+            // encode successful constant evaluations
+            let constants_index = {
```
Comment (michaelwoerister) [inline src/librustc/ty/maps/on_disk_cache.rs]: It would be great if we had a comment (here or elsewhere) explaining why constants even need special handling (like you did on IRC).

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, could you do a perf-run please?

File: src/librustc/ty/maps/config.rs (hunk 1 above)
Comment (oli-obk) [reply src/librustc/ty/maps/config.rs]: not yet (at least not in general, some are), but it is planned

**Comment by oli-obk** [comment]
We could reuse the regular caching strategy, if either

* we don't cache `const_eval` queries that resulted in an error (which does not necessarily result in a reported error!, so we might end up redoing some work in the next compilation)
* we don't serialize the error enum and instead pull a dummy variant from the ether during deserialization (does this cause problems with hashing/equality expecting the same value after deserialization?)

The reason for this is that serializing/deserializing the error enum is a huge mess... We'd need to serialize things like `ty::Layout` and others, because the error variants contain such types.

**Comment by Mark-Simulacrum** [comment]
Perf should be queued.

**Comment by michaelwoerister** [comment]
Thanks, @Mark-Simulacrum!

http://perf.rust-lang.org/compare.html?start=222b0eb583a64299f43d6640617e22f19973ddab&end=a04ce41981aa3b98cd562106e77e2a7c0761883c&stat=instructions%3Au

File: src/librustc/ty/maps/config.rs (hunk 1 above)
Comment (michaelwoerister) [reply src/librustc/ty/maps/config.rs]: Let's just return true here then.

**Comment by michaelwoerister** [comment]
> We could reuse the regular caching strategy, if (...) we don't cache const_eval queries that resulted in an error

That sounds fine to me but how is it related to the problems with statics that we talked about yesterday? Is this an additional problem?

**Comment by oli-obk** [comment]
> That sounds fine to me but how is it related to the problems with statics that we talked about yesterday? Is this an additional problem?

I'd change statics to always return `ByRef` instead of `ByVal`, so they contain an `AllocId` to their allocation. Simple constants will stay `ByVal`. Since the query caching will then cache the `ByRef`, it'll also trigger a serialization for the `AllocId`.

I don't think anyone is reading the value of statics at compile time atm other than const eval itself, so having it `ByRef` is fine. This is only a convenience feature for reading the constant's value, there's no disadvantage other than that accessing a `ByRef` constant requires a bunch of function calls instead of just matching on the value.

**Comment by michaelwoerister** [comment]
OK, sounds good!

@Mark-Simulacrum, I think that perf-run is unfortunately obsolete then.

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by ishitatsuyuki** [comment]
Compare with merge base: https://perf.rust-lang.org/compare.html?start=e65547d4fad0425d1db4f33a4d8134bf2cad939e&end=02094271f28e88e64b66014726f1d996bf7acae3&stat=instructions%3Au

Compare with the day before regression: https://perf.rust-lang.org/compare.html?start=2018-03-08&end=02094271f28e88e64b66014726f1d996bf7acae3&stat=instructions%3Au

**Comment by oli-obk** [comment]
Style servo regressed in clean incremental, but not in patched incremental. Weird. I probably won't get to investigate this before monday

Everything else gained compared to before miri. Now there are mostly regular compile-time regressions, not incremental regressions.

**Comment by ishitatsuyuki** [comment]
@oli-obk servo style clean-incr regression is known to be spurious; you can check the graph and it's widely fluctuating.

**Comment by michaelwoerister** [comment]
OK, I think we should merge this version.

@eddyb, would you mind taking a look at the const evaluator changes?

**Review by eddyb — APPROVED** [review]

**Comment by kennytm** [comment]
@bors p=1

Slightly bumping performance improvement PRs.
