### PR TITLE
Use `call` instead of `invoke` for functions that cannot unwind 

### LINKED ISSUE #69911: Incorrect LLVM generated with mir-opt-level=2: cannot invoke intrinsic
```rust
struct A;

impl Drop for A {
    fn drop(&mut self) {
        println!("A");
    }
}

fn main() {
    let a = A;
    std::sync::atomic::spin_loop_hint();
    std::mem::forget(a);
}
```

```shell
$ rustc -Copt-level=0 -Zmir-opt-level=2 a.rs
Cannot invoke an intrinsic other than donothing, patchpoint, statepoint, coro_resume or coro_destroy
  invoke void @llvm.x86.sse2.pause()
          to label %15 unwind label %16
Cannot invoke an intrinsic other than donothing, patchpoint, statepoint, coro_resume or coro_destroy
  invoke void @llvm.x86.sse2.pause()
          to label %15 unwind label %16
in function _ZN1a4main17h5a7c080779719c70E
LLVM ERROR: Broken function found, compilation aborted!
```

### PR DESCRIPTION
**Pull request by wesleywiser**
The `FnAbi` now knows if the function is allowed to unwind. If a
function isn't allowed to unwind, we can use a `call` instead of an
`invoke`.

This resolves an issue when calling LLVM intrinsics which cannot unwind
LLVM will generate an error if you attempt to invoke them so we need to
ignore cleanup blocks in codegen and generate a call instead.

Fixes #69911

r? @eddyb 
cc @rust-lang/wg-ffi-unwind

### CODE REVIEW

**Comment by nikic** [comment]
There are some LLVM intrinsics that do support invokes, you can find the list at https://github.com/llvm/llvm-project/blob/30a8b77080b98ffdd1837d2ea2e74f91e40cc867/llvm/lib/IR/Verifier.cpp#L4164-L4175. Apart from maybe the wasm one, probably nothing that's relevant to Rust.

As a side-note, LLVM intrinsics should always use the "unadjusted" ABI, something that is not happening right now.

File: src/librustc/ty/layout.rs [hunk 1]
```diff
@@ -2386,93 +2467,85 @@ where
...
+        )
     }
 
     fn new_internal(
         cx: &C,
         sig: ty::PolyFnSig<'tcx>,
         extra_args: &[Ty<'tcx>],
         caller_location: Option<Ty<'tcx>>,
+        can_unwind: bool,
+        conv: Conv,
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: This should take `CodegenFnAttrFlags` instead instead of moving anything out.

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -2374,7 +2448,14 @@ where
         + HasParamEnv<'tcx>,
 {
     fn of_fn_ptr(cx: &C, sig: ty::PolyFnSig<'tcx>, extra_args: &[Ty<'tcx>]) -> Self {
-        call::FnAbi::new_internal(cx, sig, extra_args, None, |ty, _| ArgAbi::new(cx.layout_of(ty)))
+        let conv = conv(cx.tcx(), sig.abi());
+
+        let can_unwind =
+            can_unwind(cx.tcx().sess.panic_strategy(), CodegenFnAttrFlags::empty(), conv);
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: Do we ever apply `nounwind` to function pointer calls today? If not, then this should always be `true`.

File: src/librustc/ty/layout.rs [hunk 3]
```diff
@@ -2360,11 +2361,84 @@ where
...
+            // (versus stating it is UB) and *how* it would be enforced
+            // is currently under discussion; see rust-lang/rust#58794.
+            //
+            // In either case, we mark item as explicitly nounwind.
+            false
+        }
+    }
+}
+
+fn conv(tcx: TyCtxt<'_>, abi: SpecAbi) -> Conv {
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: This shouldn't be moved out of where it is, but see other comments.

**Comment by eddyb** [comment]
I think this PR is branded as fixing a bug, but it's changing a lot about how `nounwind` is computed and works, so it should be rebranded or split into two PRs.

@nikic I think those intrinsics (if ever used directly from a library, which we should've never allowed, but that's another discussion) should be marked explicitly with `#[unwind]` or w/e attribute we use for that.

File: src/librustc/ty/layout.rs (hunk 2 above)
Comment (wesleywiser) [reply src/librustc/ty/layout.rs]: No, it looks like we do not (#64090 seems to be related). I'm backing this out and restoring the current behavior.

**Comment by wesleywiser** [comment]
> @nikic I think those intrinsics (if ever used directly from a library, which we should've never allowed, but that's another discussion) should be marked explicitly with `#[unwind]`.

I agree. I wouldn't want to maintain a list of unwinding intrinsics in rustc and using `#[unwind]` on those would work.

File: src/librustc/ty/layout.rs [hunk 4]
```diff
@@ -2360,11 +2361,55 @@ where
         sig: ty::PolyFnSig<'tcx>,
         extra_args: &[Ty<'tcx>],
         caller_location: Option<Ty<'tcx>>,
+        codegen_fn_attr_flags: CodegenFnAttrFlags,
         mk_arg_type: impl Fn(Ty<'tcx>, Option<usize>) -> ArgAbi<'tcx, Ty<'tcx>>,
     ) -> Self;
     fn adjust_for_abi(&mut self, cx: &C, abi: SpecAbi);
 }
 
+fn can_unwind(
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]: If this logic now lives in `librustc`, that might help with https://github.com/rust-lang/rust/issues/65303.

**Comment by wesleywiser** [comment]
I believe this is ready for review.

File: src/librustc_codegen_ssa/mir/block.rs [hunk 5]
```diff
@@ -111,7 +111,9 @@ impl<'a, 'tcx> TerminatorCodegenHelper<'tcx> {
         destination: Option<(ReturnDest<'tcx, Bx::Value>, mir::BasicBlock)>,
         cleanup: Option<mir::BasicBlock>,
     ) {
-        if let Some(cleanup) = cleanup {
+        // If there is a cleanup block and the function we're calling can unwind, then
+        // do an invoke, otherwise do a call.
+        if let Some(cleanup) = cleanup.filter(|_| fn_abi.can_unwind) {
```
Comment (nagisa) [inline src/librustc_codegen_ssa/mir/block.rs:116]: IMO in most instances this should happen way earlier. That is, the cleanup blocks should not be reach codegen in the first place for calls of functions that cannot unwind. This can happen either during MIR construction or afterwards in some clean-up pass.

This piece of code still needs to exist, of course, because `fn_abi` information in some cases may only be available after monomorphization, but the test case that changes in this PR does not involve generics...

I’m fine with work to do this happening in some follow-up PR (possibly implemented by somebody else), but in that case at least an issue needs to exist to that effect.

**Review by nagisa — APPROVED** [review]
r=me after at least an issue is filled about not generating cleanup blocks in the first place.

**Comment by BatmanAoD** [comment]
@eddyb @amanieu will this cause us to use `call` for any `pthread`-cancelable functions? Otherwise, AFAIK it should not be a problem from the perspective of FFI-unwind.

**Comment by Amanieu** [comment]
@BatmanAoD It doesn't matter since unwinding from `extern "C"` is UB. `pthread` cancellation uses unwinding at first and then switches to longjmp if it can't find unwind info for a frame. The only valid way to use these functions is to assume they longjmp and avoid any destructors in frame that they unwind.
