### PR TITLE
windows: Return the "Not Found" error when a path is empty

### LINKED ISSUE #90940: windows: An empty path returns os error 123 instead of os error 3 with recent nightly
I tried this code:

```rust
fn main() {
    let path = std::path::Path::new("");
    if let Err(err) = path.canonicalize() {
        println!("{}", err);
        // println!("{:?}", err.kind());
    }
}
```

I expected to see this happen: `canonicalize()` returns os error 3 (`ERROR_PATH_NOT_FOUND`)

Instead, this happened: it returns os error 123 (`ERROR_INVALID_NAME`)

This is problematic as `std::io::ErrorKind` doesn't become `NotFound` but `Uncategorized`, which isn't useful for most users. Other platforms like Linux return `NotFound` so the former behavior should be correct here.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (e249ce6b2 2021-10-30)
binary: rustc
commit-hash: e249ce6b2345587d6e11052779c86adbad626dff
commit-date: 2021-10-30
host: x86_64-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0
```

The issue doesn't happen on `rustc 1.58.0-nightly (e99963c55 2021-10-29)`, I think the regression was introduced by #89174.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #90940

### CODE REVIEW

File: library/std/src/sys/windows/path/tests.rs [hunk 1]
```diff
@@ -91,7 +91,6 @@ fn verbatim() {
     // Make sure opening a drive will work.
     check("Z:", "Z:");
 
-    // An empty path or a path that contains null are not valid paths.
-    assert!(maybe_verbatim(Path::new("")).is_err());
+    // A path that contains null are not valid paths.
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/path/tests.rs:94]:
```suggestion
    // A path that contains null is not a valid path.
```

File: library/std/src/sys/windows/path.rs [hunk 2]
```diff
@@ -174,8 +174,8 @@ pub(crate) fn maybe_verbatim(path: &Path) -> io::Result<Vec<u16>> {
     const UNC_PREFIX: &[u16] = &[SEP, SEP, QUERY, SEP, U, N, C, SEP];
 
     let mut path = to_u16s(path)?;
-    if path.starts_with(VERBATIM_PREFIX) || path.starts_with(NT_PREFIX) {
-        // Early return for paths that are already verbatim.
+    if path.starts_with(VERBATIM_PREFIX) || path.starts_with(NT_PREFIX) || path == Vec::from([0]) {
```
Comment (ChrisDenton) [inline library/std/src/sys/windows/path.rs:177]:
```suggestion
    if path.starts_with(VERBATIM_PREFIX) || path.starts_with(NT_PREFIX) || path == &[0] {
```

**Comment by m-ou-se** [comment]
Thanks!

@bors r+
