### PR TITLE
Exhaustiveness checking: work around type normalization issues

### LINKED ISSUE #72476: Incorrect non-exhaustive pattern error
```rust
enum Next<I> where I: Iterator {
    Item(I::Item),
}

fn e(item: Next<&mut dyn Iterator<Item=Option<()>>>) {
    match item {
        Next::Item(None) => {}
        Next::Item(Some(())) => {}
    }
}

fn main() {}
```

Produces non-exhaustive pattern error (even though all patterns are covered):

```
error[E0004]: non-exhaustive patterns: `Item(_)` not covered
 --> main.rs:6:11
  |
1 | / enum Next<I> where I: Iterator {
2 | |     Item(I::Item),
  | |     ---- not covered
3 | | }
  | |_- `Next<&mut dyn std::iter::Iterator<Item = std::option::Option<()>>>` defined here
...
6 |       match item {
  |             ^^^^ pattern `Item(_)` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `Next<&mut dyn std::iter::Iterator<Item = std::option::Option<()>>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0004`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (9310e3bd4 2020-05-21)
binary: rustc
commit-hash: 9310e3bd4f425f84fc27878ebf2bda1f30935a63
commit-date: 2020-05-21
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

### PR DESCRIPTION
**Pull request by Nadrieril**
This should resolve https://github.com/rust-lang/rust/issues/72476 and probably https://github.com/rust-lang/rust/issues/72467.
This is a bit hacky but that's actually what the code was doing before https://github.com/rust-lang/rust/pull/71930. I'm essentially reverting https://github.com/rust-lang/rust/commit/e5a2cd526a6ad92b90dda81104abc7adf4c83495. So despite being hacky, it's been tried and tested (so much so that code relies on it now x)).
Only the third commit does anything interesting.

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
cc @matthewjasper I think

**Comment by Nadrieril** [comment]
And cc @varkor who reviewed https://github.com/rust-lang/rust/pull/71930

File: src/test/ui/pattern/usefulness/issue-72476-associated-type.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+// From https://github.com/rust-lang/rust/issues/72476
+
+trait A {
+    type Projection;
+}
+
+impl A for () {
+    type Projection = bool;
+    // using () instead of bool here does compile though
```
Comment (estebank) [inline src/test/ui/pattern/usefulness/issue-72476-associated-type.rs:11]: This comment is now out of date, right?

Comment (Nadrieril) [reply src/test/ui/pattern/usefulness/issue-72476-associated-type.rs:11]: Ah yeah, since the bug got fixed

**Review by davidtwco — APPROVED** [review]
LGTM, probably should have someone more experienced look over it though.

**Comment by mark-i-m** [comment]
@Nadrieril Would it make sense to open an issue about properly fixing this?

**Comment by Nadrieril** [comment]
I guess yeah. I'm not super motivated to do it though, it would take some work to explain properly what the issue is

**Comment by matthewjasper** [comment]
The issue is that `field.ty(..)` doesn't normalize it's output after substituting. For example, in the test the field has type `<T as  A>::Projection`, which after substituting becomes `<() as  A>::Projection`. To get the normalized type you either have to explicitly normalize, or use the result from the type of the subpattern, which typeck has already normalized.

I think that I would prefer normalization to be used here, because it's more consistent with how things have to be done in general.

**Comment by Nadrieril** [comment]
I made this PR as an emergency fixup because the related issue was high priority. I'd still like to fix this properly, but I don't think adding normalization after field.ty would be enough. There's a bunch of different places that inspect types, and I don't understand the rationale and invariants related to type normalization. It's already the second uncaught problem surfaced by this change so I'd prefer to be safe and merge this first

**Comment by Nadrieril** [comment]
Since https://github.com/rust-lang/rust/issues/72476 is P-critical, may I insist a bit to get this merged quickly?

**Comment by Nadrieril** [comment]
Thank you :pray:

**Comment by wesleywiser** [comment]
Per [discussion in the compiler team triage meeting today](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-05-28.20.2354818/near/199029420), I'm going to bump the priority on this since it fixes a `P-critical` issue.

@bors p=1

**Comment by Nadrieril** [comment]
> The issue is that `field.ty(..)` doesn't normalize it's output after substituting.

Oh, I just understood this comment x) The error popped up again (in https://github.com/rust-lang/rust/issues/89393) because I hadn't fixed it properly. I understand how to now.
