### PR TITLE
Do not emit incorrect borrow suggestion involving macros and fix overlapping multiline spans

### LINKED ISSUE #58298: Nonsensical error message for string error inside macro
Apologies if this has been posted before, I couldn't find anything but many of my searches had several hundred results and I didn't want to go through pages upon pages of them for such a minor issue (yeah, I'm part of the problem, sorry).

If you have an error where you pass a `String` instead of a `&str` inside a macro, the suggestion `rustc` emits is meaningless:

```
error[E0308]: mismatched types
    --> src/tests.rs:1108:1
     |
1108 | test_select!(select32, i32);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | |
     | expected &str, found struct `std::string::String`
     | help: consider borrowing here: `&test_select!(select32, i32);`
     | in this macro invocation
     |
     = note: expected type `&str`
                found type `std::string::String`
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Note this:

```
help: consider borrowing here: `&test_select!(select32, i32);`
```

This is an item-position macro and so this suggestion will only cause a syntax error.

### PR DESCRIPTION
**Pull request by estebank**
Fix #58298.

### CODE REVIEW

File: src/librustc_errors/emitter.rs [hunk 1]
```diff
@@ -243,6 +243,7 @@ impl EmitterWriter {
                         end_col: hi.col_display,
                         is_primary: span_label.is_primary,
                         label: span_label.label.clone(),
+                        overlaps: false,
```
Comment (davidtwco) [inline src/librustc_errors/emitter.rs]:
```suggestion
                        overlaps_exactly: false,
```

I think this might be a clearer name.

File: src/librustc_errors/emitter.rs [hunk 2]
```diff
@@ -289,17 +289,44 @@ impl EmitterWriter {
...
+                //  |       foo(
+                //  |  _____^
+                //  | |         bar,
+                //  | |     );
+                //  | |      ^
+                //  | |      |
+                //  | |______foo
+                //  |        baz
+                add_annotation_to_file(&mut output, file.clone(), ann.line_start, ann.as_start());
+                let middle = min(ann.line_start + 4, ann.line_end);
```
Comment (davidtwco) [inline src/librustc_errors/emitter.rs]: Pre-existing, but you could add a comment (or make this a constant) explaining where the 4 comes from?

**Review by davidtwco — APPROVED** [review]
Left a few nits, LGTM otherwise.

File: src/librustc_errors/emitter.rs (hunk 2 above)
Comment (estebank) [reply src/librustc_errors/emitter.rs]: I'm trying to figure out that code out and now I'm hating myself for not having written comments for it now -_-

**Review by davidtwco — APPROVED** [review]
