### PR TITLE
fix(diagnostic): wrap parens for ref impl trait param

### LINKED ISSUE #99597: Incorrect compiler hint on missing stricter trait bound
Let's consider the following snippet:
```rust
trait T1 { }

trait T2 {
    fn test(&self) { }
}

fn go(s: &impl T1) {
    s.test();
}
```
The compiler will throw the following error + hint:
```
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): no method named `test` found for reference `&impl T1` in the current scope
 --> src/lib.rs:8:7
  |
8 |     s.test();
  |       ^^^^ method not found in `&impl T1`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `test`, perhaps you need to restrict type parameter `impl T1` with it:
  |
7 | fn go(s: &impl T1 + T2) {
  |                   ++++

For more information about this error, try `rustc --explain E0599`.
```

But the hint is not correct: changing the `go` function as suggested by the compiler
```rust
fn go(s: &impl T1 + T2) {
    s.test();
}
```
Will result in a new error:
```
error: ambiguous `+` in a type
 --> src/lib.rs:7:11
  |
7 | fn go(s: &impl T1 + T2) {
  |           ^^^^^^^^^^^^ help: use parentheses to disambiguate: `(impl T1 + T2)`
```

The compiler hint should be something like this:
```
help: the following trait defines an item `test`, perhaps you need to restrict type parameter `impl T1` with it:
  |
7 | fn go(s: &(impl T1 + T2)) {
  |           +        +++++
```

The only case where just adding the restriction works out of the box is when taking an owned value as a parameter:
```rust
fn go(s: impl T1 + T2) {
    s.test();
}
```

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes https://github.com/rust-lang/rust/issues/99597

When parameters are an `impl_trait` which it needed to add trait, and it is a reference, add parentheses to the type of the parameter in the suggestion

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/method/suggest.rs [hunk 1]
```diff
@@ -2633,47 +2633,62 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                            let (sp, mut introducer) = if let Some(span) = bounds_span {
+                                (span, Introducer::Plus)
+                            } else if let Some(colon_span) = param.colon_span {
+                                (colon_span.shrink_to_hi(), Introducer::Nothing)
+                            } else {
+                                (param.span.shrink_to_hi(), Introducer::Colon)
+                            };
+                            if param.is_impl_trait() {
+                                introducer = Introducer::Plus
                             }
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/method/suggest.rs:2675]: Does this work?

```suggestion
                            } else if param.is_impl_trait() {
                                (param.span.shrink_to_hi(), Introducer::Plus)
                            } else {
                                (param.span.shrink_to_hi(), Introducer::Colon)
                            };
```

**Review by compiler-errors — APPROVED** [review]

File: compiler/rustc_hir_typeck/src/method/suggest.rs (hunk 1 above)
Comment (bvanjoi) [reply compiler/rustc_hir_typeck/src/method/suggest.rs]: Yes, `param.colon_span.is_some()` only valid when parameter is not impl trait, see: 
- https://github.com/rust-lang/rust/blob/master/compiler/rustc_ast_lowering/src/lib.rs#L2246
- https://github.com/rust-lang/rust/blob/master/compiler/rustc_ast_lowering/src/lib.rs#L2279
