### PR TITLE
Visit move out of `_0` when visiting `return`

### LINKED ISSUE #72032: Visiting a MIR `return` should visit the return place too
The `return` terminator conceptually moves out of the return place `_0`, but this is not currently reflected by the visitor infrastructure.

This can lead to incorrect dataflow solutions for `_0`. For example, `MaybeLiveLocals` reports that `_0` is dead before a `return`, which is wrong (it must always be live there). These don't currently cause any harm, since use of `_0` is fairly limited, but they are an issue for destination propagation / NRVO, which can propagate `_0` to arbitrary places in the function and needs to have correct information to do so soundly.

The simple fix of calling `visit_local` from within `super_terminator_kind` has the problem that the `MutVisitor` receives a `&mut Local`, but the local `return` reads from can not be changed. This can be caught with an assertion, but maybe there is a better solution for this?

cc @rust-lang/wg-mir-opt

### PR DESCRIPTION
**Pull request by jonas-schievink**
Closes https://github.com/rust-lang/rust/issues/72032

### CODE REVIEW

File: src/librustc_mir/transform/generator.rs [hunk 1]
```diff
@@ -91,6 +91,16 @@ impl<'tcx> MutVisitor<'tcx> for RenameLocalVisitor<'tcx> {
             *local = self.to;
         }
     }
+
+    fn visit_terminator_kind(&mut self, kind: &mut TerminatorKind<'tcx>, location: Location) {
```
Comment (oli-obk) [inline src/librustc_mir/transform/generator.rs:95]: is this change necessary? We should never set `self.from` to `_0`, right?

Comment (oli-obk) [reply src/librustc_mir/transform/generator.rs:95]: Ah nevermind, we do: https://github.com/jonas-schievink/rust/blob/e22cc993fbf9918784ec38a25e04564e7b1973ee/src/librustc_mir/transform/generator.rs#L233
