### PR TITLE
Include a header in .rlink files

### LINKED ISSUE #95297: Add version header to -Zno-link .rlink files
This allows giving a better error when attempting to use the original source file with -Zlink-only rather than crashing and allows rejecting rlink files produced by a different rustc version.

### PR DESCRIPTION
**Pull request by Kobzol**
I couldn't find the right place where to put tests. Is there some location that tests `.rlink` creation and loading?
I only found `src/test/run-make-fulldeps/separate-link/Makefile`, but I'm not sure how to check the error message in the Makefile.

Fixes: https://github.com/rust-lang/rust/issues/95297

r? @bjorn3

### CODE REVIEW

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 1]
```diff
@@ -190,3 +191,33 @@ pub fn looks_like_rust_object_file(filename: &str) -> bool {
...
+        encoder.emit_str(RUSTC_VERSION.unwrap()).unwrap();
+
+        let mut encoder = rustc_serialize::opaque::Encoder::new(encoder.into_inner());
+        rustc_serialize::Encodable::encode(codegen_results, &mut encoder).unwrap();
+        encoder.into_inner()
+    }
+
+    pub fn deserialize_rlink(data: Vec<u8>) -> Result<Self, String> {
+        if !data.starts_with(RLINK_MAGIC) {
+            return Err("The input does not look like a .rlink file".to_string());
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/lib.rs:211]: I think you should pass in `sess` to this function and use `sess.fatal()` to give an error.

File: compiler/rustc_codegen_ssa/src/lib.rs [hunk 2]
```diff
@@ -190,3 +191,33 @@ pub fn looks_like_rust_object_file(filename: &str) -> bool {
     // Check if the "inner" extension
     ext2 == Some(RUST_CGU_EXT)
 }
+
+const RLINK_MAGIC: &'static [u8; 5] = b"rlink";
```
Comment (bjorn3) [inline compiler/rustc_codegen_ssa/src/lib.rs:195]: Maybe use `rustlink`? Also I think it should contain a version number as we have changed the encoded format of strings before.

**Comment by bjorn3** [comment]
> I only found src/test/run-make-fulldeps/separate-link/Makefile, but I'm not sure how to check the error message in the Makefile.

You can use something like `$(CGREP) "the error message" < rustc_stderr.txt` after capturing the stderr output using `rustc ... 2>rustc_stderr.txt`.

**Review by bjorn3 — APPROVED** [review]
r=me once CI passes
