### PR TITLE
Suggest && and || instead of 'and' and 'or'

### LINKED ISSUE #54109: Diagnostics: There may be special error message for trying to use "and" or "or" inside if
```
error: expected `{`, found `and`
   --> src/numplay.rs:102:24
    |
102 |             if ov == 3 and nv == 4 {
    |             --         ^^^ help: try placing this code inside a block: `{ and; }`
    |             |
    |             this `if` statement has a condition, but no block

error: aborting due to previous error
```

Error message is not very helpful. It should suggest `&&` instead.

### PR DESCRIPTION
**Pull request by vi**
Resolves #54109.

Note: competing pull reqeust: #54179

r? @csmoe

### CODE REVIEW

**Comment by csmoe** [comment]
cc @estebank I prefer to this PR than mine.

File: src/libsyntax/parse/parser.rs [hunk 1]
```diff
@@ -732,6 +732,12 @@ impl<'a> Parser<'a> {
                   format!("expected {} here", expect)))
             };
             let mut err = self.fatal(&msg_exp);
+            if self.token.is_ident_named("and") {
+                err.help("Use `&&` instead of `and` for the boolean operator");
```
Comment (estebank) [inline src/libsyntax/parse/parser.rs]: Could you use the following?

```
err.span_suggestion_with_applicability(
    self.span,
    "use `&&` instead of `and` for the boolean operator",
    "&&".to_string(),
    Applicability::MaybeIncorrect,
);
```

This way the output will be presented inline and third party tools will be able to apply the suggestion in their UIs.

Same change in all four cases.

**Review by estebank — APPROVED** [review]
This is great! One small piece of feedback left. r=me after dealing with it.

Thank you @csmoe too for your change.

**Comment by vi** [comment]
Appled the recommendation. Also added `while` tests in addition to existing `if` tests just in case.

Is it not a problem that output looks a bit repetitive:

    help: use `||` instead of `or` for the boolean operator: `||`

**Comment by estebank** [comment]
There's a short span suggestion method that hides the actual suggestion and would work well for these, but it doesn't accept `Applicability`... I'm ok with it for now, but if you're in the mood to check it out to see if we could make it accept `Applicability` and modify every caller, it would be great :)

**Comment by estebank** [comment]
@bors r+ rollup
@vi If you get to update `span_suggestion_short` before this PR is merged, great, otherwise it can be a follow up task.

**Comment by vi** [comment]
As far as I understoon from the description, it is expected to change not directly related code ("modify every caller"), so another review may be needed.

**Comment by estebank** [comment]
@vi we should always be specifying `Applicability`. We don't as an accident of history: no one has bothered to go back and fully fix it everywhere.

**Comment by vi** [comment]
There is already a `span_suggestion_short_with_applicability` and it's more used than `span_suggestion_short`.

What `Applicability` should have the remaining `span_suggestion_short`s?

Applied the `span_suggestion_short_with_applicability` for now.

**Comment by estebank** [comment]
@vi that change would be great as a stand alone PR. Remember to fix indentation when needed and changing the stderr files.

**Comment by vi** [comment]
> fix indentation

`cargo fmt -- --check` shows a lot of unrelated changes and I'm not sure what is correct indentation.

**Comment by estebank** [comment]
>> fix indentation
>
> cargo fmt -- --check shows a lot of unrelated changes and I'm not sure what is correct indentation.

I believe I was referring to making sure that when a line is above 100 cols, you change it as you did in this PR:

```
	        e.span_suggestion_short_with_applicability(
                    self.span,
                    "use `&&` instead of `and` for the boolean operator",
                    "&&".to_string(),
                    Applicability::MaybeIncorrect,
                );
```

> Assuming the change touches tests?

Correct :)

**Comment by berkus** [comment]
errrr... why?

how is && or || more readable and understandable than `and` / `or`? Apart from everything else I'd rather not see &&/|| in the code at all. Even for C++ I use `and`/`or` as human-readable equivalents of the pseudographic garbage.

**Comment by vi** [comment]
@berkus I think Rust is just based on C in that aspect. C has `&&`, so Rust has `&&`. Haskell also have a convention that operators are special characters and functions are letters.

If in future some edition of Rust decides to implement both `and` and `&&` (like in Perl), or just the former like in Python, this suggestion will be modified accordingly.

**Comment by berkus** [comment]
I agree that linter is not to blame here, but where and how can I suggest the more readable `and`/`or` alternatives for inclusion/use in the language?

**Comment by estebank** [comment]
@berkus [submit an RFCS](https://github.com/rust-lang/rfcs/#before-creating-an-rfc).

**Comment by vi** [comment]
I also like Perl-style `&&` and `and` mix. But it's too Perl.
