### PR TITLE
Fix #50865: ICE on impl-trait returning functions reaching private items

### LINKED ISSUE #50865: Compiler crashed with cannot create local mono-item
Relevant logs:

```
   Compiling shadowsocks-rust v1.7.0-alpha.7 (file:///Users/zonyitoo/Projects/shadowsocks-rust)
error: internal compiler error: librustc_mir/monomorphize/collector.rs:750: Cannot create local mono-item for DefId(19/0:1252 ~ shadowsocks[e91a]::relay[0]::udprelay[0]::dns[0]::{{impl}}[2]::new[0])

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:554:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (2f2a11dfc 2018-05-16) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `shadowsocks-rust`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Reproduce steps:

1. Clone the `master` branch of https://github.com/shadowsocks/shadowsocks-rust
2. Run tests with `cargo test`
3. Compiler crashes

## Meta

```
$ rustc --version --verbose
rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)
binary: rustc
commit-hash: 2f2a11dfc436fc0f401b595f22ed043c46dbebe7
commit-date: 2018-05-16
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```

## Backtrace

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: rustc_mir::monomorphize::collector::should_monomorphize_locally
  15: rustc_mir::monomorphize::collector::visit_instance_use
  16: <rustc_mir::monomorphize::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind
  17: rustc_mir::monomorphize::collector::collect_items_rec
  18: rustc_mir::monomorphize::collector::collect_items_rec
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_mir::monomorphize::collector::collect_items_rec
  23: rustc_mir::monomorphize::collector::collect_items_rec
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_items_rec
  34: rustc_mir::monomorphize::collector::collect_items_rec
  35: rustc_mir::monomorphize::collector::collect_items_rec
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_crate_mono_items
  44: rustc::util::common::time
  45: rustc_trans::base::collect_and_partition_translation_items
  46: rustc::ty::context::tls::with_context
  47: rustc::dep_graph::graph::DepGraph::with_task_impl
  48: rustc::ty::context::tls::with_related_context
  49: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  50: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  51: rustc_trans::base::trans_crate
  52: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  53: rustc::util::common::time
  54: rustc_driver::driver::phase_4_translate_to_llvm
  55: rustc_driver::driver::compile_input::{{closure}}
  56: rustc::ty::context::tls::enter_context
  57: <std::thread::local::LocalKey<T>>::with
  58: rustc::ty::context::TyCtxt::create_and_enter
  59: rustc_driver::driver::compile_input
  60: rustc_driver::run_compiler_with_pool
  61: <scoped_tls::ScopedKey<T>>::set
  62: syntax::with_globals
  63: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  64: __rust_maybe_catch_panic
  65: rustc_driver::run
  66: rustc_driver::main
  67: std::rt::lang_start::{{closure}}
  68: std::panicking::try::do_call
  69: __rust_maybe_catch_panic
  70: std::rt::lang_start_internal
  71: main
query stack during panic:
#0 [collect_and_partition_translation_items] collect_and_partition_translation_items
end of query stack
```

And I think it also happens in stable rustc 1.26.0.

### PR DESCRIPTION
**Pull request by FelixMcFelix**
Adds a test case as suggested in #50865, and implements @petrochenkov's suggestion. Fixes #50865.

Impl-trait-returning functions are marked under a new (low) access level, which they propagate rather than `AccessLevels::Reachable`. `AccessLevels::is_reachable` returns false for such items (leaving stability analysis unaffected), these items may still be visible to the lints phase however.

### CODE REVIEW

File: src/librustc/middle/privacy.rs [hunk 1]
```diff
@@ -40,7 +42,8 @@ pub struct AccessLevels<Id = NodeId> {
 
 impl<Id: Hash + Eq> AccessLevels<Id> {
     pub fn is_reachable(&self, id: Id) -> bool {
-        self.map.contains_key(&id)
+        // self.map.contains_key(&id)
```
Comment (estebank) [inline src/librustc/middle/privacy.rs]: do not leave commented out code

File: src/test/run-pass/issue-50865-private-impl-trait/main.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
```
Comment (estebank) [inline src/test/run-pass/issue-50865-private-impl-trait/main.rs]: Update year.

File: src/test/run-pass/issue-50865-private-impl-trait/auxiliary/lib.rs [hunk 3]
```diff
@@ -0,0 +1,24 @@
+// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
```
Comment (estebank) [inline src/test/run-pass/issue-50865-private-impl-trait/auxiliary/lib.rs]: Update year.

**Review by estebank — COMMENTED** [review]
lgtm

r? @eddyb

File: src/librustc_privacy/lib.rs [hunk 4]
```diff
@@ -147,6 +150,7 @@ impl<'a, 'tcx> Visitor<'tcx> for EmbargoVisitor<'a, 'tcx> {
     }
 
     fn visit_item(&mut self, item: &'tcx hir::Item) {
+        debug!("Walked item {:?}", item);
```
Comment (varkor) [inline src/librustc_privacy/lib.rs]: Usually this would be something like: `debug!("visit_item({:?})", item);`, so it's easier to see where it comes from.

File: src/librustc_privacy/lib.rs [hunk 5]
```diff
@@ -171,6 +184,8 @@ impl<'a, 'tcx> Visitor<'tcx> for EmbargoVisitor<'a, 'tcx> {
         // Update level of the item itself
         let item_level = self.update(item.id, inherited_item_level);
 
+        debug!("Its privacy is believed to be: {:?}", item_level);
```
Comment (varkor) [inline src/librustc_privacy/lib.rs]: Perhaps just `item_level = {:?}` is sufficient?

**Comment by FelixMcFelix** [comment]
Applied suggestions, thanks for the feedback.

File: src/Cargo.lock [hunk 6]
```diff
@@ -2237,6 +2237,7 @@ dependencies = [
 name = "rustc_privacy"
 version = "0.0.0"
 dependencies = [
+ "log 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
```
Comment (petrochenkov) [inline src/Cargo.lock]: Could you avoid introducing this new dependency?

File: src/librustc_privacy/lib.rs [hunk 7]
```diff
@@ -227,6 +242,9 @@ impl<'a, 'tcx> Visitor<'tcx> for EmbargoVisitor<'a, 'tcx> {
             hir::ItemKind::ExternCrate(..) => {}
         }
 
+        let orig_level = self.prev_level;
+        self.prev_level = item_level;
```
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: Nit: `let orig_level = mem::replace(&mut self.prev_level, item_level);`

Comment (petrochenkov) [reply src/librustc_privacy/lib.rs]: Hmm, I'm not sure why these lines were moved from there to here actually.

File: src/librustc_privacy/lib.rs [hunk 8]
```diff
@@ -157,12 +161,21 @@ impl<'a, 'tcx> Visitor<'tcx> for EmbargoVisitor<'a, 'tcx> {
...
                 self.prev_level
             }
+            // Impl trait return types mark their parent function.
+            // It (and its children) are revisited if the change applies.
+            hir::ItemKind::Existential(ref ty_data) => {
+                if let Some(impl_trait_fn) = ty_data.impl_trait_fn {
+                    if let Some(node_id) = self.tcx.hir.as_local_node_id(impl_trait_fn) {
+                        self.update(node_id, Some(AccessLevel::ReachableFromImplTrait));
+                    }
+                }
```
Comment (petrochenkov) [inline src/librustc_privacy/lib.rs]: Could you move this piece of code from here to `// Update levels of nested things` below, it belongs there logically.

File: src/Cargo.lock (hunk 6 above)
Comment (FelixMcFelix) [reply src/Cargo.lock]: Any `debug!("...")` calls would then also need to be removed. Is this version of log different from that used by the rest of the rustc_* crates?

File: src/librustc_privacy/lib.rs (hunk 7 above)
Comment (FelixMcFelix) [reply src/librustc_privacy/lib.rs]: Ok. This was moved while I was figuring out how best to propagate the level from the `ReachEverythingInTheInterfaceVisitor`. Will move back and modify.

File: src/librustc_privacy/lib.rs (hunk 8 above)
Comment (FelixMcFelix) [reply src/librustc_privacy/lib.rs]: Ok.

File: src/librustc_privacy/lib.rs (hunk 7 above)
Comment (FelixMcFelix) [reply src/librustc_privacy/lib.rs]: Actually, this was moved so that `EmbargoVisitor::reach` would be able to see whether the parent node was `ReachableFromImplTrait` or at least `Reachable`, to propagate the correct level.

File: src/Cargo.lock (hunk 6 above)
Comment (petrochenkov) [reply src/Cargo.lock]: `debug!(...)` logging used for a specific debugging session is usually useless for anything else in the future, so I mean yes, it is better removed.
