### PR TITLE
Suggest replacing braces for brackets on array-esque invalid block expr

### LINKED ISSUE #87672: Better Diagnostics When Using Wrong Brackets to Create an Array
I ended up spending way too much time debugging the following error, since I was trying to port some C code to rust.
```rust
const ARR: [u8; 3] = {
    1, 2, 3
}
```
Give the error:
```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `,`
 --> src/lib.rs:2:6
  |
2 |     1, 2, 3,
  |      ^ expected one of `.`, `;`, `?`, `}`, or an operator

error: aborting due to previous error

error: could not compile `playground`
```
The error message is very vague and hard to determine the actual error here.
Seeing as though some programming languages like Java and C use `{}` for arrays, I think it'd make sense for the compiler to suggest using `[]` if the user is trying to create an array.

### PR DESCRIPTION
**Pull request by hkmatsumoto**
Newcomers may write `{1, 2, 3}` for making arrays, and the current error message is not informative enough to quickly convince them what is needed to fix the error.

This PR implements a diagnostic for this case, and its output looks like this:
```text
error: this code is interpreted as a block expression, not an array
 --> src/lib.rs:1:22
  |
1 |   const FOO: [u8; 3] = {
  |  ______________________^
2 | |     1, 2, 3
3 | | };
  | |_^
  |
  = note: to define an array, one would use square brackets instead of curly braces
help: try using [] instead of {}
  |
1 | const FOO: [u8; 3] = [
2 |     1, 2, 3
3 | ];
  |
```

Fix #87672

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 3337a035d2b47609aaf087adc04a0cbba7e3beb0

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 1]
```diff
@@ -409,6 +409,103 @@ impl<'a> Parser<'a> {
...
+        // As a workaround, we do nothing for `token::OpenDelim(token::Brace)`
+        // in the match expression below, just waiting for
+        // `token::CloseDelim(token::Brace)` to exit the loop.
+        let mut depth = [
+            1, // {}
+            0, // <>, this appears in fn calls. e.g., {foo::<A, B>(), 2, 3}
+        ];
+
+        // We keep calling `look_ahead` until we reach the end of the block expression.
+        loop {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/diagnostics.rs:444]: I have a [somewhat different approach](https://github.com/rust-lang/rust/pull/88729) that might be able to make some of this code easier to reason about.

Instead of using `look_ahead` for cases where we kind of need to parse things with non-deterministic lookahead, I do `let snapthot = self.clone()` on the `Parser` and *try to successfully parse* what the "fake" syntax would be. If that succeeds, we know that we can provide an accurate suggestion, if that doesn't, we cancel the error and rollback the parser to the previous state to emit the "normal" error we currently see and let the existing error recovery machinery take its course. With this approach, it should be possible to emit a suggestion on a case like `{0, if 1 < 2 {1} else {1}, 2, 3}`. Because cloning is somewhat expensive (but not terrible, from what I've seen), we want to avoid it on the "happy path" of well-formed code, but you can use limited `look_ahead` to see if *it could be* this case, like doing `self.look_ahead(2, |t| t.kind == &Comma)` or something.

We could even try to keep information on the `Parser` for "we are in a `const` assignment, of array type" that we check here in `maybe_suggest_brackets_instead_of_braces`, and if it is not the case, we exit early, like we do for things coming from a macro.

What do you think? (Sorry for the delay in reviewing)

File: src/test/ui/parser/bare-struct-body.stderr [hunk 2]
```diff
@@ -14,6 +14,23 @@ LL |     val: (),
...
+LL | |     };
+   | |_____^
+   |
+   = note: to define an array, one would use square brackets instead of curly braces
+help: try using [] instead of {}
+   |
+LL |     let x = [
+LL |         val: (),
+LL |     ];
+   |
```
Comment (estebank) [inline src/test/ui/parser/bare-struct-body.stderr:32]: We probably wouldn't want this error or the one above, as we are emitting two diagnostics for the same syntax error. `maybe_suggest_brackets_instead_of_braces` doesn't signal whether this worked or not, so instead what it could do is return a `PResult` and you can call `self.maybe_suggest_brackets_instead_of_braces(lo)?` instead.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (hkmatsumoto) [reply compiler/rustc_parse/src/parser/diagnostics.rs:444]: It's very smart of you to come up with the approach :)
What's nice is that by cloning the parser the codebase will be significantly simplified while the suggestion keeps working almost as-is except some cases like `{if 1 < 2 {1} else {1}, 2, 3}`, but that's compromisable as I assume it's unlikely to initialize an array with complex expressions.

File: src/test/ui/parser/bare-struct-body.stderr (hunk 2 above)
Comment (hkmatsumoto) [reply src/test/ui/parser/bare-struct-body.stderr]: By actually parsing as if they were arrays, this is no longer emitted.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Thank you, you're too kind.

Yes, I agree that this gets 80% there for 20% of the effort. If we were relying on this for the actual language and not just for error recovery, the story would be different.

File: compiler/rustc_parse/src/parser/expr.rs [hunk 3]
```diff
@@ -1752,6 +1756,36 @@ impl<'a> Parser<'a> {
...
+    fn is_array_like_block(&mut self) -> bool {
+        self.look_ahead(1, |t| matches!(t.kind, TokenKind::Ident(..) | TokenKind::Literal(_)))
+            && self.look_ahead(2, |t| t == &token::Comma)
+            && self.look_ahead(3, |t| t.can_begin_expr())
+    }
+
+    /// Emits a suggestion if it looks like the user meant an array but
+    /// accidentally used braces, causing the code to be interpreted as a block
+    /// expression.
+    fn maybe_suggest_brackets_instead_of_braces(&mut self, lo: Span, attrs: AttrVec) {
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1768]: I would change this to return a `PResult<'a, P<Expr>>`...

File: compiler/rustc_parse/src/parser/expr.rs [hunk 4]
```diff
@@ -1752,6 +1756,36 @@ impl<'a> Parser<'a> {
...
+                    arr.span,
+                    "this code is interpreted as a block expression, not an array",
+                )
+                .multipart_suggestion(
+                    "try using [] instead of {}",
+                    vec![(lo, "[".to_owned()), (hi, "]".to_owned())],
+                    Applicability::MaybeIncorrect,
+                )
+                .note("to define an array, one would use square brackets instead of curly braces")
+                .emit();
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1783]:
```suggestion
                .emit();
                *self = snapshot;
                Some(self.mk_expr_err(/*I think it takes a span here*/))
```

File: compiler/rustc_parse/src/parser/expr.rs [hunk 5]
```diff
@@ -1752,6 +1756,36 @@ impl<'a> Parser<'a> {
...
+            }
+            Err(mut e) => e.emit(),
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1785]: We don't want to emit parse errors caused by "alternative syntax".

```suggestion
            Err(mut e) => {
                e.cancel();
                None
            }
```

File: compiler/rustc_parse/src/parser/expr.rs [hunk 6]
```diff
@@ -1760,6 +1794,10 @@ impl<'a> Parser<'a> {
         blk_mode: BlockCheckMode,
         mut attrs: AttrVec,
     ) -> PResult<'a, P<Expr>> {
+        if self.is_array_like_block() {
+            self.maybe_suggest_brackets_instead_of_braces(lo, attrs.clone());
```
Comment (estebank) [inline compiler/rustc_parse/src/parser/expr.rs:1798]:
```suggestion
            if let Some(expr) = self.maybe_suggest_brackets_instead_of_braces(lo, attrs.clone()) {
                return Ok(expr);
            }
```

**Review by estebank — COMMENTED** [review]
Let's add a test as well :)

File: compiler/rustc_parse/src/parser/expr.rs (hunk 5 above)
Comment (hkmatsumoto) [reply compiler/rustc_parse/src/parser/expr.rs]: Oops, you're definitely right!
