### PR TITLE
polymorphize: `I` used if `T` used in `I: Foo<T>`

### LINKED ISSUE #75326: Symbol ambiguity with polymorphization and new mangling scheme
rustc will not currently bootstrap with `-Zsymbol-mangling-version=v0` and `-Zpolymorphization=on` due to the following issue:

Consider the following example:

```rust
// build-pass
// compile-flags: -Zpolymorphize=on -Zsymbol-mangling-version=v0

pub(crate) struct Foo<'a, I, E>(I, &'a E);

impl<'a, I, T: 'a, E> Iterator for Foo<'a, I, E>
where
    I: Iterator<Item = &'a (T, E)>,
{
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        self.find(|_| true)
    }
}

fn main() {
    let mut a = Foo([(1u32, 1u16)].iter(), &1u16);
    let mut b = Foo([(1u16, 1u32)].iter(), &1u32);
    let _ = a.next();
    let _ = b.next();
}
```

..which produces the following error:

```
error: symbol `_RNCNvXCs4fqI2P2rA04_19impl_param_manglingINtB4_3FooppENtNtNtNtCsfnEnqCNU58Z_4core4iter6traits8iterator8Iterator4next0B4_` is already defined
  --> src/test/ui/polymorphization/impl-param-mangling.rs:13:19
   |
13 |         self.find(|_| true)
   |                   ^^^^^^^^

error: aborting due to previous error
```

(*unmangled:* `<impl_param_mangling::Foo<_, _> as core::iter::traits::iterator::Iterator>::next::{closure#0}`)

Polymorphisation correctly determines that `I` and `E` are unused and that `T` is used in the closure (`T` is used by the argument). Therefore, multiple copies of this closure can be generated by polymorphization for each instantiation of `T` - however, this is not encoded in the mangling for the closure, which triggers [`assert_symbols_are_distinct`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/monomorphize/partitioning/fn.assert_symbols_are_distinct.html).

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #75326.

This PR adjusts polymorphization's handling of predicates so that after ensuring that `T` is used in `I: Foo<T>` if `I` is used, it now ensures that `I` is used if `T` is used in `I: Foo<T>`. This is necessary to mark generic parameters that only exist in impl parameters as used - thereby avoiding symbol clashes when using the new mangling scheme.

With this PR, rustc will now fully bootstrap with polymorphization and the new symbol mangling scheme enabled - not all tests pass, but I'm not sure how much of that is the interaction of the two features, I'll be looking into that soon. All tests pass with only polymorphization enabled.

r? @lcnr (this isn't sufficiently complex that I need to add to eddy's review queue)
cc @eddyb

### CODE REVIEW

File: src/test/ui/polymorphization/predicates.rs [hunk 1]
```diff
@@ -18,7 +18,28 @@ where
...
 }
 
+// In addition, check that `I` is considered used in `next::{{closure}}`, because `T` is used and
+// `T` is really just `I::Item`.
+
+pub(crate) struct Foo<'a, I, E>(I, &'a E);
+
+impl<'a, I, T: 'a, E> Iterator for Foo<'a, I, E>
+where
+    I: Iterator<Item = &'a (T, E)>,
```
Comment (lcnr) [inline src/test/ui/polymorphization/predicates.rs:28]: Can you add a test using `std::iter::Repeat<I>: Iter...` or something like that to check that we actually use `mark_ty` for `self_ty` here?

Comment (davidtwco) [reply src/test/ui/polymorphization/predicates.rs:28]: I might be misunderstanding what you mean - but doesn't the existing `foo` function in this test handle that?

Comment (lcnr) [reply src/test/ui/polymorphization/predicates.rs:28]: Foo also has `ty::Param` as `self_ty`, doesn't it?

I want to test a type which contains a `ty::Param` as `self_ty` which is currently not tested afaict

Comment (davidtwco) [reply src/test/ui/polymorphization/predicates.rs:36]: Fixed!

File: src/librustc_mir/monomorphize/polymorphize.rs [hunk 2]
```diff
@@ -120,45 +119,82 @@ fn mark_used_by_predicates<'tcx>(
...
+        let mut vis = MarkUsedGenericParams { tcx, def_id, unused_parameters };
         ty.visit_with(&mut vis);
     };
 
+    let def_id = tcx.closure_base_def_id(def_id);
     let predicates = tcx.explicit_predicates_of(def_id);
-    debug!("mark_parameters_used_in_predicates: predicates_of={:?}", predicates);
+    debug!("mark_used_by_predicates: predicates_of={:?}", predicates);
+
     for (predicate, _) in predicates.predicates {
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_mir/monomorphize/polymorphize.rs]: Fixed!

File: src/librustc_mir/monomorphize/polymorphize.rs [hunk 3]
```diff
@@ -120,45 +119,82 @@ fn mark_used_by_predicates<'tcx>(
...
+
+                // Consider `I` used if `T` is used in predicates of the form
+                // `<I as Iterator>::Item = &'a (T, E)` (see rust-lang/rust#75326)
+                debug!("mark_used_by_predicates: checking projection ty");
+                if is_ty_used(unused_parameters, proj.ty) {
+                    debug!("mark_used_by_predicates: used!");
+                    mark_ty(unused_parameters, self_ty);
                 }
             }
             _ => (),
```
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/librustc_mir/monomorphize/polymorphize.rs]: Fixed!

**Comment by lcnr** [comment]
While I think that this restriction is somewhat unfortunate this does look correct to me now.

@bors r+ rollup

File: src/librustc_mir/monomorphize/polymorphize.rs [hunk 4]
```diff
@@ -318,3 +373,36 @@ impl<'a, 'tcx> TypeVisitor<'tcx> for UsedGenericParametersVisitor<'a, 'tcx> {
         }
     }
 }
+
+/// Visitor used to check if a generic parameter is used.
+struct IsUsedGenericParams<'a> {
```
Comment (eddyb) [inline src/librustc_mir/monomorphize/polymorphize.rs:378]: Maybe this should be called `HasUsedGenericParams`?

File: src/librustc_mir/monomorphize/polymorphize.rs [hunk 5]
```diff
@@ -120,45 +119,101 @@ fn mark_used_by_predicates<'tcx>(
...
+                        // No need to check for projection type being used if `self_ty` was used.
+                        continue;
+                    }
+
+                    // Consider `I` used if `T` is used in predicates of the form
+                    // `<I as Iterator>::Item = &'a (T, E)` (see rust-lang/rust#75326)
+                    debug!("mark_used_by_predicates: checking projection ty");
+                    if is_ty_used(unused_parameters, proj.ty) {
+                        debug!("mark_used_by_predicates: used!");
+                        mark_ty(unused_parameters, self_ty);
```
Comment (eddyb) [inline src/librustc_mir/monomorphize/polymorphize.rs:199]: I think this is overly simplistic, I suspect you can replace `I: Iterator<...>` with `(): WeirdIterator<I, ...>`.
Any treatment of the `Self` parameter as special is suspicious by default, IMO.

File: src/librustc_mir/monomorphize/polymorphize.rs [hunk 6]
```diff
@@ -120,45 +119,101 @@ fn mark_used_by_predicates<'tcx>(
...
+                    debug!("mark_used_by_predicates: checking substs");
                     for ty in trait_ref.substs.types() {
-                        debug!("unused_generic_params: (trait) ty={:?}", ty);
-                        mark_ty(unused_parameters, ty);
+                        if is_ty_used(unused_parameters, ty) {
+                            debug!("mark_used_by_predicates: used!");
+                            mark_ty(unused_parameters, trait_ref.self_ty());
+                        }
                     }
                 }
```
Comment (eddyb) [inline src/librustc_mir/monomorphize/polymorphize.rs:175]: This sounds like an overly complicated way to handle "if any parameters are used, all are".
Notable strangeness:
* `substs.types()` will include `self_ty` so some of this code already seems redundant with itself
* `.types()` makes me wonder: what about const generics?

**Comment by davidtwco** [comment]
I'll address @eddyb's comments in a follow-up.

**Comment by davidtwco** [comment]
Filed #75595 to address @eddyb's comments.
