### PR TITLE
Deduplicate unreachable blocks, for real this time

### LINKED ISSUE #110551: Codegen regression involving `assume`/`unreachable_unchecked`
### Code

I tried this code:

```rust
pub fn f(a: Option<u32>) -> u32 {
    match a {
        None => {}
        Some(_) => unsafe { std::hint::unreachable_unchecked() }
    }

    a.unwrap()
}
```

I expected to see this happen: no branch instructions emitted, `unreachable_unchecked` makes an assumption that `a` is `None`, so `unwrap` should be inlined and optimized as a panic.

Instead, this happened: there is a discriminant check still emitted.

### Version it worked on

It most recently worked on: nightly-2023-03-26

### Version with regression

```
; rustc +nightly-2023-03-27 --version --verbose
rustc 1.70.0-nightly (db0cbc48d 2023-03-26)
binary: rustc
commit-hash: db0cbc48d4aaa300713a95d9b317a365a474490c
commit-date: 2023-03-26
host: aarch64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

## ASM diff

See godbolt: https://godbolt.org/z/5WKTY99Te

## Bisection results

Regression occurred in #106428 (cc @saethlin).

searched nightlies: from nightly-2023-03-01 to nightly-2023-04-01
regressed nightly: nightly-2023-03-27
searched commit range: https://github.com/rust-lang/rust/compare/0c61c7a978fe9f7b77a1d667c77d2202dadd1c10...db0cbc48d4aaa300713a95d9b317a365a474490c
regressed commit: https://github.com/rust-lang/rust/commit/2420bd34ba68a625840022de2a56aec228500359

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: aarch64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2023-03-01 --end=2023-04-01 --regress=success --script=./t.sh
```
</details>

<details>
<summary>t.sh</summary>

```bash
#!/bin/sh

set -ex

rustc t.rs --crate-type=lib --emit=asm -O && cat ./t.s | grep -E "cbz\s+w0, .LBB0_2"
```

(if you want to test on `x86_64` replace `"cbz\s+w0, .LBB0_2"` with `"testl\s+%edi, %edi"`)

</details>

<details>
<summary>t.rs</summary>

```rust
pub fn f(a: Option<i32>) -> i32 {
    unsafe { if !a.is_none() { std::hint::unreachable_unchecked() } }

    return a.unwrap();
}
```

</details>

## History

@heckad originally noticed the problem and opened #110456, then @WaffleLapkin suggested that this is a compiler issue, then @bugadani [noticed](https://github.com/rust-lang/rust/pull/110456#issuecomment-1512025633) that this is a regression, then @WaffleLapkin bisected and opened this issue.

### PR DESCRIPTION
**Pull request by saethlin**
In https://github.com/rust-lang/rust/pull/106428 (in particular https://github.com/rust-lang/rust/pull/106428/commits/41eda69516dd3ee217ae07c0efa369d31f630405) we noticed that inlining `unreachable_unchecked` can produce duplicate unreachable blocks. So we improved two MIR optimizations: `SimplifyCfg` was given a simplify to deduplicate unreachable blocks, then `InstCombine` was given a combiner to deduplicate switch targets that point at the same block. The problem is that change doesn't actually work.

Our current pass order is
```
SimplifyCfg (does nothing relevant to this situation)
Inline (produces multiple unreachable blocks)
InstCombine (doesn't do anything here, oops)
SimplifyCfg (produces the duplicate SwitchTargets that InstCombine is looking for)
```

So in here, I have factored out the specific function from `InstCombine` and placed it inside the simplify that produces the case it is looking for. This should ensure that it runs in the scenario it was designed for.

Fixes https://github.com/rust-lang/rust/issues/110551
r? @cjgillot

### CODE REVIEW

File: tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// compile-flags: -Zmir-opt-level=2 -Zinline-mir
+// ignore-debug: standard library debug assertions add a panic that breaks this optimization
```
Comment (cjgillot) [inline tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs:2]: Blessing the `ignore-debug` tests requires to recompile everything, which is tedious.
Can you use the intrinsic directly and cook your own `unreachable_unchecked`?

File: compiler/rustc_mir_transform/src/simplify.rs [hunk 2]
```diff
@@ -290,14 +302,22 @@ pub fn remove_duplicate_unreachable_blocks<'tcx>(tcx: TyCtxt<'tcx>, body: &mut B
...
                 // entirely excluded cleanup blocks in building the set of duplicates.
                 if self.duplicates.contains(target) {
+                    if *target != self.duplicates[0] {
+                        optimization_was_applied = true;
+                    }
                     *target = self.duplicates[0];
                 }
             }
 
+            if optimization_was_applied {
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/simplify.rs:317]: Is this heavy enough to warrant the short circuit?
Could this cause us to miss cases where combining would be useful, but the branches are already deduplicated?
`match { A => {}, B | C => unreachable }`

File: compiler/rustc_mir_transform/src/instcombine.rs [hunk 3]
```diff
@@ -1,10 +1,11 @@
 //! Performs various peephole optimizations.
 
+use crate::simplify::combine_duplicate_switch_targets;
 use crate::MirPass;
 use rustc_hir::Mutability;
 use rustc_middle::mir::{
     BinOp, Body, CastKind, Constant, ConstantKind, LocalDecls, Operand, Place, ProjectionElem,
-    Rvalue, SourceInfo, Statement, StatementKind, SwitchTargets, Terminator, TerminatorKind, UnOp,
+    Rvalue, SourceInfo, Statement, StatementKind, Terminator, TerminatorKind, UnOp,
 };
```
Comment (cjgillot) [inline compiler/rustc_mir_transform/src/instcombine.rs:9]: For MIR opts, a glob import is probably best here.

File: tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+#![crate_type = "lib"]
```
Comment (cjgillot) [inline tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs:3]: Unrelated: should we make mir-opt tests "lib" by default, to avoid to list all the cases in a `fn main` everywhere?

File: compiler/rustc_mir_transform/src/simplify.rs (hunk 2 above)
Comment (cjgillot) [reply compiler/rustc_mir_transform/src/simplify.rs:317]: Or do you rely on the call in instcombine?

File: tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs (hunk 1 above)
Comment (saethlin) [reply tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs:2]: I'm really wary of doing things like that. Modifying the mir-opt test for the convenience of testing is what caused this regression in the first place, and this test is already somewhat removed from the code that was reported to not optimize.

File: tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs (hunk 4 above)
Comment (saethlin) [reply tests/mir-opt/instcombine_duplicate_switch_targets_e2e.rs:3]: If we can. The codegen tests could do with the same treatment; I pulled this style of testing from them. There's a `#![crate_type = "lib"]` in nearly every single codegen test file.

File: compiler/rustc_mir_transform/src/simplify.rs (hunk 2 above)
Comment (saethlin) [reply compiler/rustc_mir_transform/src/simplify.rs]: When I wrote this I think I didn't realize how rare the combining should be. And I'm quite sure I do not want to be relying on InstCombine.

**Comment by saethlin** [comment]
It seems prudent to
@bors try @rust-timer queue
