### PR TITLE
Fix rendering of reexported macros 2.0 and fix visibility of reexported items

### LINKED ISSUE #86276: rustdoc: Re-exported macros 2.0 are rendered as `macro_rules!`
I noticed this while working on a fix for #86208. I think the issue is just that `clean/inline.rs` does not check if the macro is a `macro_rules!`, whereas `clean/mod.rs` does.

### [core](https://doc.rust-lang.org/stable/core/ptr/macro.addr_of.html) (original)

image

### [std](https://doc.rust-lang.org/stable/std/ptr/macro.addr_of.html) (re-export)

image

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
So, this PR grew a bit out of focus, it does the following things:

* Fixes #86276.
* Fixes visibility display for reexported items: it now takes the visibility of the "use" statement rather than the visibility of the reexported item itself).
* Fixes the display of reexported items if "--document-private-items" option is used. Before, they were simply skipped.
* Fixes inconsistency on typedef items: they didn't display their visibility contrary to other items.

I added tests to check everything listed above.

cc @camelid @ollie27 (in case one of you want to review?)

r? @jyn514

### CODE REVIEW

File: src/librustdoc/clean/inline.rs [hunk 1]
```diff
@@ -546,22 +546,47 @@ fn build_static(cx: &mut DocContext<'_>, did: DefId, mutable: bool) -> clean::St
...
-                matchers
-                    .iter()
-                    .map(|span| { format!("    {} => {{ ... }};\n", span.to_src(cx)) })
-                    .collect::<String>()
-            );
+            let tts: Vec<_> = def.body.inner_tokens().into_trees().collect();
+            let matchers: Vec<Span> = tts.chunks(4).map(|arm| arm[0].span()).collect();
+
+            let name = name.clean(cx);
+            let source = if def.macro_rules {
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/inline.rs:559]: This code is mostly the same as the one in [clean/mod.rs](https://github.com/rust-lang/rust/blob/701496384fd2d46557b3f013b50860c69c9848cc/src/librustdoc/clean/mod.rs#L2177-L2208). Do we want to unify both or not? I'd tend to say yes but considering of the small differences (manipulating ast vs hir), not sure if the result would look better. So I thought about using a macro instead. What do you think?

**Comment by jyn514** [comment]
Both this and https://github.com/rust-lang/rust/pull/86282 basically rewrite the macro rendering, I would rather not review both at once. I plan to review the other first since it's a more serious bug.

**Comment by GuillaumeGomez** [comment]
> Both this and #86282 basically rewrite the macro rendering, I would rather not review both at once. I plan to review the other first since it's a more serious bug.

It's fine, let's wait until #86282 is merged! I'll mark the PR as blocked for the time being and give a try to improve the code by removing the duplication.

**Comment by GuillaumeGomez** [comment]
I unified it into a function in the end. :)

**Comment by GuillaumeGomez** [comment]
Rebased on #86282.

File: src/librustdoc/clean/utils.rs [hunk 2]
```diff
@@ -577,3 +579,37 @@ pub(super) fn render_macro_arms<'a>(
 pub(super) fn render_macro_matcher(matcher: &TokenTree) -> String {
     rustc_ast_pretty::pprust::tt_to_string(matcher)
 }
+
+pub(super) fn display_macro_source(
+    cx: &mut DocContext<'_>,
+    name: Symbol,
+    def: &ast::MacroDef,
+    def_id: DefId,
+    vis: impl Clean<Visibility>,
```
Comment (jyn514) [inline src/librustdoc/clean/utils.rs:588]: You could avoid making this generic by passing in `Visibility` instead. The only drawback is it cleans the visibility early, instead of on-demand, but shrinking the generated code size seems worth it to me.

File: src/librustdoc/clean/mod.rs [hunk 3]
```diff
@@ -1696,6 +1697,23 @@ impl Clean<Visibility> for hir::Visibility<'_> {
...
+    fn clean(&self, cx: &mut DocContext<'_>) -> Visibility {
+        match self.kind {
+            ast::VisibilityKind::Public => Visibility::Public,
+            ast::VisibilityKind::Inherited => Visibility::Inherited,
+            ast::VisibilityKind::Crate(_) => {
+                let krate = DefId::local(CRATE_DEF_INDEX);
+                Visibility::Restricted(krate)
+            }
+            ast::VisibilityKind::Restricted { id, .. } => {
+                let did = cx.enter_resolver(|r| r.local_def_id(id)).to_def_id();
```
Comment (jyn514) [inline src/librustdoc/clean/mod.rs:1710]: It's unfortunate that this has to call into the resolver :/ I'm hoping to get rid of it at some point: https://github.com/rust-lang/rust/issues/83761. But we already call `load_macro_untracked` above, so hopefully fixing that will allow removing this impl at the same time.

**Review by jyn514 — APPROVED** [review]
LGTM with the nit about `display_macro_source` fixed

**Comment by jyn514** [comment]
Oh I forgot - can you add a test for `pub(crate)` and `pub(self)` macros? Right now `impl Clean for ast::Visibility` isn't tested at all.

File: src/librustdoc/clean/utils.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/utils.rs:588]: I'd rather not, the conversion from the `ast::Visibility` needs to call `enter_resolver`, so if we can avoid it as much as possible, I think it's better. I can add a FIXME though if you want?

Comment (jyn514) [reply src/librustdoc/clean/utils.rs:588]: Nah, that logic makes sense to me.

**Comment by GuillaumeGomez** [comment]
Adding the requested tests then.

File: src/test/rustdoc/auxiliary/macro-2-reexport.rs [hunk 4]
```diff
@@ -0,0 +1,6 @@
+#![crate_name = "macro_2_reexport"]
```
Comment (camelid) [inline src/test/rustdoc/auxiliary/macro-2-reexport.rs:1]: nit: Isn't this `crate_name` redundant? Is it just so that renaming the test doesn't cause it to fail?

Comment (GuillaumeGomez) [reply src/test/rustdoc/auxiliary/macro-2-reexport.rs:1]: It's completely redundant but I find it easier this way to have the crate name written even if useless.

**Comment by GuillaumeGomez** [comment]
I updated the PR and the first comment as well to explain what I did here. I don't know why I expected less things to be broken around reexports... Anyway, that should clean things up quite a lot.

File: src/test/rustdoc/reexports-priv.rs [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+
+#![crate_name = "foo"]
+
+extern crate reexports;
+
+// @has 'foo/macro.addr_of.html' '//*[@class="docblock type-decl"]' 'pub macro addr_of($place : expr) {'
+pub use reexports::addr_of;
+// @has 'foo/macro.addr_of_crate.html' '//*[@class="docblock type-decl"]' 'pub(crate) macro addr_of_crate($place : expr) {'
+pub(crate) use reexports::addr_of_crate;
+// @has 'foo/macro.addr_of_self.html' '//*[@class="docblock type-decl"]' 'pub(crate) macro addr_of_self($place : expr) {'
```
Comment (Stupremee) [inline src/test/rustdoc/reexports-priv.rs:12]: Maybe add a test with multiple matchers for completeness?

**Review by Stupremee — APPROVED** [review]

File: src/test/rustdoc/reexports-priv.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/reexports-priv.rs:12]: What do you mean?

File: src/librustdoc/clean/mod.rs [hunk 6]
```diff
@@ -2052,7 +2053,7 @@ fn clean_use_statement(
     // forcefully don't inline if this is not public or if the
     // #[doc(no_inline)] attribute is present.
     // Don't inline doc(hidden) imports so they can be stripped at a later stage.
-    let mut denied = !import.vis.node.is_pub()
+    let mut denied = (!import.vis.node.is_pub() && !cx.render_options.document_private)
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:2056]: This is a very good question. I'll check to be sure and if not, I'll check that it's a restricted "pub".

**Comment by GuillaumeGomez** [comment]
@Stupremee Fixed the issue you spotted and added a test to prevent a regression.

File: src/test/rustdoc/reexports-priv.rs (hunk 5 above)
Comment (Stupremee) [reply src/test/rustdoc/reexports-priv.rs:12]: Ah sorry. Meant to link [here](https://github.com/rust-lang/rust/pull/86841/files#diff-9ae3607a55a104c791e37441a1f68b776f76cbb9ec02b73fc22b1f75693fb3ecR3), but I mean't to add a macro that contains multiple matchers or is this covered somewhere else?

Comment (GuillaumeGomez) [reply src/test/rustdoc/reexports-priv.rs:12]: Oh I see! Yes it's tested in other places. I didn't change this part, only the macros "header".
