### PR TITLE
Emit DW_AT_main_subprogram

### LINKED ISSUE #32620: emit DW_AT_main_subprogram
When making an executable, rustc should emit `DW_AT_main_subprogram` on the CU and the subprogram DIE for the main function that is going to be executed by `main`.

This marker would allow gdb's `start` command to find the correct spot in user code to set an initial breakpoint.  (This doesn't work yet, see https://sourceware.org/bugzilla/show_bug.cgi?id=16264 - but could be made to work.)

### PR DESCRIPTION
**Pull request by tromey**
This changes rustc to emit DW_AT_main_subprogram on the "main" program.
This lets gdb suitably stop at the user's main in response to
"start" (rather than the library's main, which is what happens
currently).

Fixes #32620
r? michaelwoerister

### CODE REVIEW

**Comment by alexcrichton** [comment]
It looks like llvm 3.7 may break the tests added here (on travis), but I think that can be fixed with `// min-llvm-version 3.7`

**Comment by tromey** [comment]
> I think that can be fixed with // min-llvm-version 3.7

Thanks - I will update the patch soon.  I think for this I'll introduce a new test, so that the existing test keeps running on travis.

File: src/librustc_llvm/ffi.rs [hunk 1]
```diff
@@ -451,6 +451,7 @@ pub mod debuginfo {
         FlagIndirectVariable = 1 << 13,
         FlagLValueReference = 1 << 14,
         FlagRValueReference = 1 << 15,
+        FlagMainSubprogram = 1 << 21,
```
Comment (michaelwoerister) [inline src/librustc_llvm/ffi.rs]: I looks like older LLVM versions will just silently ignore this. At least 3.7 on Travis. Which is good.

**Review by michaelwoerister — COMMENTED** [review]
Looks good to me. Thanks @tromey! A test case for the common case would be good (can be very similar to the #[start] test case).

File: src/librustc_trans/debuginfo/mod.rs [hunk 2]
```diff
@@ -286,7 +296,7 @@ pub fn create_function_debug_context<'a, 'tcx>(cx: &CrateContext<'a, 'tcx>,
             is_local_to_unit,
             true,
             scope_line as c_uint,
-            FlagPrototyped as c_uint,
+            flags,
```
Comment (tromey) [inline src/librustc_trans/debuginfo/mod.rs]: `flags` is initialized to include it:

```
+    let mut flags = FlagPrototyped as c_uint;
```

I'm happy to write this some other way if you think it would be clearer.

Comment (michaelwoerister) [inline src/librustc_trans/debuginfo/mod.rs]: Oh, that's right, I just missed it. Sorry.

**Comment by tromey** [comment]
> It looks like llvm 3.7 may break the tests added here (on travis), but I think that can be fixed with // min-llvm-version 3.7

I'm wondering today if that should be "min-llvm-version 3.8"?  Since IIUC 3.7 is what is in travis, and will fail.  Even 3.8 is technically wrong in a sense, because if there's a real 3.8 release, it won't contain the needed patch.

File: src/librustc_trans/debuginfo/mod.rs [hunk 3]
```diff
@@ -274,6 +274,16 @@ pub fn create_function_debug_context<'a, 'tcx>(cx: &CrateContext<'a, 'tcx>,
     let function_name = CString::new(name).unwrap();
     let linkage_name = CString::new(linkage_name).unwrap();
 
+    let mut flags = FlagPrototyped as c_uint;
+    match *cx.sess().entry_fn.borrow() {
+        Some((id, _)) => {
+            if instance == Instance::mono(cx.shared(), cx.tcx().map.local_def_id(id)) {
```
Comment (tromey) [inline src/librustc_trans/debuginfo/mod.rs]: I needed something a bit wordier:

```
            if let Some(local_id_unwrapped) = local_id {
                if id == local_id_unwrapped {
                    flags |= FlagMainSubprogram as c_uint;
                }
            }
```

**Comment by michaelwoerister** [comment]
> I'm wondering today if that should be "min-llvm-version 3.8"? 

I guess that no LLVM release in existence today contains the patch, so this test can only pass with our own version of LLVM. Do we have a `rust-llvm-only` directive for tests?

File: src/librustc_trans/debuginfo/mod.rs (hunk 3 above)
Comment (michaelwoerister) [inline src/librustc_trans/debuginfo/mod.rs]: Oh, that makes sense. Though you could probably make it shorter be wrapping `id` in an `Option` and then comparing `Option` against `Option`. Or do something like this:
```rust
let entry_fn_id = *cx.sess().entry_fn.borrow();
if entry_fn_id.is_some() && local_id == entry_fn_id {
    flags |= ...;
}
```

Comment (arielb1) [inline src/librustc_trans/debuginfo/mod.rs]: The standard style is is `if entry_fn_id == Some(local_id)`.

**Comment by tromey** [comment]
Just FYI - I've rebased this and fixed it up, and it works in manual testing.  However the test cases fail now.  I don't know the test suite setup very well; my suspicion is that the tests aren't built in isolation, leading rustc not to emit `DW_AT_main_subprogram` for the test `main` functions.  I'll try to ping someone on irc tomorrow to see what can be done; or else if you are reading this and happen to know, please comment.  Thanks :)

**Comment by tromey** [comment]
> However the test cases fail now.

Of course this turned out to be operator error; somehow I had a stale rustc in my tree that I was running manually.

**Comment by michaelwoerister** [comment]
Let me know when it's ready for review.

**Comment by tromey** [comment]
@michaelwoerister - hopefully it's ready now.

**Comment by tromey** [comment]
Well, I guess not.  In the new scheme for DIFlags I suppose some kind of version or other configury is needed.  Maybe I should have listened to that warning in RustWrapper.cpp.

**Comment by alexcrichton** [comment]
ping @tromey, it looks like this may need a rebase now?

**Comment by tromey** [comment]
> it looks like this may need a rebase now?

Yeah.  Sorry about my silence on this.  I still intend to work on it.  I think there are two issues with the patch currently.

One is that the refactor in this area means that the old approach of passing in the constant, regardless of the underlying LLVM version, will no longer work, because the enumerator in question just doesn't exist in earlier versions of LLVM.  The Rust fork of LLVM does have this, and so does 4.0, but I don't know of a way to distinguish the Rust LLVM from the ordinary upstream LLVM.  So, maybe adding a way to distinguish this case would be good.

Alternatively a simpler solution would be to only enable this feature for LLVM 4.0.  I think this is less nice because in the future I hope to add more Rust-specific features to LLVM's debuginfo generation, and backport these to the Rust LLVM fork; and if this all comes to pass then it will be handy to have the necessary infrastructure already in place.

The second problem with this patch is related: the tests also have no way to check whether they're being run against the Rust fork of LLVM.

**Comment by cuviper** [comment]
> I don't know of a way to distinguish the Rust LLVM from the ordinary upstream LLVM. So, maybe adding a way to distinguish this case would be good.

There is a `-DLLVM_RUSTLLVM` for this sort of thing.  It's used in `PassWrapper.cpp` to stub a couple functions that only exist in the Rust fork of LLVM.

**Comment by tromey** [comment]
> There is a -DLLVM_RUSTLLVM for this sort of thing

Thanks!  That really simplifies things.

**Comment by alexcrichton** [comment]
re-r? @michaelwoerister

**Comment by michaelwoerister** [comment]
@bors r+

Thanks @tromey!
