### PR TITLE
[breaking change] Validate crate name in `--extern` [MCP 650]

### LINKED ISSUE #113035: Crate name found in `--extern` gets suggested verbatim on unresolved import
Given the code in file `user.rs` as shown below:

```rs
use a_great_crate::item;
```

rustc outputs the following when invoked via `rustc user.rs --crate-type=lib --edition=2021 --extern=a-great-crate=liba_great_crate.rlib`:

```
error[E0432]: unresolved import `a_great_crate`
 --> user.rs:1:5
  |
1 | use a_great_crate::item;
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `a_great_crate`
  |
help: there is a crate or module with a similar name
  |
1 | use a-great-crate::item;
  |     ~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
```

While ideally, in this specific case it should either suggest nothing of if feasible suggest changing the `--extern` flag to `--extern=a_great_crate=liba_great_crate.rlib` (the latter is probably <kbd>P-low</kbd>). I did actually get confused by the suggestion when I originally faced it.

In fact, rustc suggests whatever garbage you put in the flag (e.g. on `rustc … '--extern=a&-gre?t#crate=xxx'`). In these cases it shouldn't consider the name at all (I realize though that this might be a case of *garbage in, garbage out*).

@rustbot label T-compiler A-diagnostics A-suggestion-diagnostics D-invalid-suggestion

### PR DESCRIPTION
**Pull request by fmease**
Reject non-ASCII-identifier crate names passed to the CLI option `--extern` (`rustc`, `rustdoc`).
Implements [MCP 650](https://github.com/rust-lang/compiler-team/issues/650) (except that we only allow ASCII identifiers not arbitrary Rust identifiers).
Fixes #113035.

[As mentioned on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Disallow.20non-identifier-valid.20--extern.20cr.E2.80.A6.20compiler-team.23650/near/376826988), doing a crater run probably doesn't make sense since it wouldn't yield anything. Most users don't interact with `rustc` directly but only ever through Cargo which always passes a valid crate name to `--extern` when it invokes `rustc` and `rustdoc`. In any case, the user wouldn't be able to use such a crate name in the source code anyway.

Note that I'm not using [`rustc_session::output::validate_crate_name`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/output/fn.validate_crate_name.html) (used for `--crate-name` and `#![crate_name]`) since the latter doesn't reject non-ASCII crate names and ones that start with a digit.

As an aside, I've also thought about getting rid of `validate_crate_name` entirely in a separate PR (with another MCP) in favor of `is_ascii_ident` to reject more weird `--crate-name`s, `#![crate_name]`s and file names but I think that would lead to a lot of actual breakage, namely because of file names starting with a digit. In `tests/ui` 9 tests would be impacted for example.

CC @estebank
r? @est31

### CODE REVIEW

File: compiler/rustc_session/src/config.rs [hunk 1]
```diff
@@ -2451,6 +2451,19 @@ pub fn parse_externs(
             Some((opts, name)) => (Some(opts), name.to_string()),
         };
 
+        if !rustc_lexer::is_ident(&name) {
+            let mut error = handler.early_struct_error(format!(
+                "crate name `{name}` passed to `--extern` is not a valid identifier"
```
Comment (fmease) [inline compiler/rustc_session/src/config.rs:2456]: I briefly considered `Debug`-printing `name` instead (via `{:?}` or via `.escape_debug()`) to escape line breaks but it looked weird.

File: compiler/rustc_session/src/session.rs [hunk 2]
```diff
@@ -1710,6 +1710,15 @@ impl EarlyErrorHandler {
         self.handler.struct_fatal(msg).emit()
     }
 
+    #[allow(rustc::untranslatable_diagnostic)]
+    #[allow(rustc::diagnostic_outside_of_impl)]
+    pub(crate) fn early_struct_error(
```
Comment (fmease) [inline compiler/rustc_session/src/session.rs:1715]: It's unfortunate that I had to introduce this method. I can get rid of it again at the cost of not showing the `.help("replace dashes with underscores …")`.

**Comment by ehuss** [comment]
One thing that might want to be considered is that generally rustc requires crate names to be ASCII. That is, you cannot reference an extern crate with unicode characters. Should this also be checking `name.as_str().is_ascii()`?

**Comment by fmease** [comment]
> One thing that might want to be considered is that generally rustc requires crate names to be ASCII. That is, you cannot reference an extern crate with unicode characters. Should this also be checking name.as_str().is_ascii()?

Hmm, good point! That is very interesting since `rustc` actually allows you to compile crates with non-ASCII idents & link it via `--extern` and it only fails once you actually try to *reference* the crate name in the code (*cannot load a crate with a non-ascii name*).

I'm gonna check if it's ASCII then :+1: and I'm gonna do the same in the follow-up PR that makes `--crate-name` and `#![crate_name]` stricter.

File: tests/run-make/incr-foreign-head-span/Makefile [hunk 3]
```diff
@@ -15,7 +15,7 @@ INCR=$(TMPDIR)/incr
 all:
 	cp first_crate.rs second_crate.rs $(TMPDIR)
 	$(RUSTC) $(TMPDIR)/first_crate.rs  -C incremental=$(INCR) --target $(TARGET) --crate-type lib
-	$(RUSTC) $(TMPDIR)/second_crate.rs -C incremental=$(INCR) --target $(TARGET)  --extern first-crate=$(TMPDIR) --crate-type lib
+	$(RUSTC) $(TMPDIR)/second_crate.rs -C incremental=$(INCR) --target $(TARGET)  --extern first_crate=$(TMPDIR)/libfirst_crate.rlib --crate-type lib
```
Comment (fmease) [inline tests/run-make/incr-foreign-head-span/Makefile:18]: I'm still baffled that this test used to work at all, can somebody enlighten me? If I manually reproduce the steps taken by this Makefile, I correctly get the error *can't find crate for `first_crate`* with a nightly rustc (since the name is *first-crate* on master). Is there any preprocessing going on here?

Apart from the incorrect crate name, `--extern` can't point to a directory, which I've also fixed. What is going on?

File: tests/ui/rfcs/rfc-2457-non-ascii-idents/crate_name_nonascii_forbidden-2.rs
Comment (fmease) [inline tests/ui/rfcs/rfc-2457-non-ascii-idents/crate_name_nonascii_forbidden-2.rs:1]: This test has become obsolete since it would've triggered on the `--extern` first instead of on the use item. It's superseded by `extern-flag/invalid-crate-name-non-ascii.rs`.

File: compiler/rustc_session/src/session.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_session/src/session.rs:1715]: It's fine.

**Review by estebank — APPROVED** [review]

File: tests/run-make/incr-foreign-head-span/Makefile (hunk 3 above)
Comment (est31) [reply tests/run-make/incr-foreign-head-span/Makefile:18]: This is weird indeed. I've checked the logs of recently successful runs and `tests/run-make/incr-foreign-head-span` *does* succeed on master. Very weird.

File: compiler/rustc_session/src/config.rs [hunk 4]
```diff
@@ -2451,6 +2451,19 @@ pub fn parse_externs(
...
+                "crate name `{name}` passed to `--extern` is not a valid ASCII identifier"
+            ));
+            let adjusted_name = name.replace("-", "_");
+            if crate::utils::is_ascii_ident(&adjusted_name) {
+                error.help(format!(
+                    "consider replacing the dashes with underscores: `{adjusted_name}`"
+                ));
+            }
+            error.emit();
+        }
```
[the remark this answers is not in the document]
Comment (fmease) [reply compiler/rustc_session/src/config.rs:2465]: The lints `uncommon_codepoints`, `mixed_script_confusables` and `confusable_idents` are amazing for sure! I'd lean towards not doing that here since it'd mean moving the code from `rustc_lint` here and adapting it to an environment that doesn't have a `Session` yet, yuck! Not sure how easy that'd be, maybe it's not that bad. `early_errors` can't even be translated right now.

[the remark this answers is not in the document]
Comment (est31) [reply compiler/rustc_session/src/config.rs:2465]: @fmease fair points :+1: . It can also be later work, too.

[the remark this answers is not in the document]
Comment (estebank) [reply compiler/rustc_session/src/config.rs:2465]: My stance is always "don't block on improving a solution short of perfect as long as it improves over the status quo", and this PR comfortably glides over that bar.
