### PR TITLE
syntax: Fix encoding and decoding spans

### LINKED ISSUE #31025: nightly `rustc -Z ast-json` generates malformed json
In #30565, @michaelwoerister changed the encoding of `syntax::codemap::Span` from serializing the value as a single `u64` into serializing two sequential `u32` values. Unfortunately this violates the serialization protocol, and causes a span like `mk_sp(0, 10)` to be serialized as `010`. Here's the current implementation:

```rust
impl Encodable for Span {
    fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error> {
        try!(s.emit_u32(self.lo.0));
        s.emit_u32(self.hi.0)
    }
}

impl Decodable for Span {
    fn decode<D: Decoder>(d: &mut D) -> Result<Span, D::Error> {
        let lo = BytePos(try! { d.read_u32() });
        let hi = BytePos(try! { d.read_u32() });
        Ok(mk_sp(lo, hi))
    }
}
```

Semantically speaking these spans should be serialized as a tuple, which would properly delimit the two values, but since that'd add a bunch of tagging overhead to the output, it'd probably be more efficient to just restore the old encoding:

```rust
impl Encodable for Span {
    fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error> {
        // Encode spans as a single u64 in order to cut down on tagging overhead
        // added by the RBML metadata encoding. The should be solved differently
        // altogether some time (FIXME #21482)
        s.emit_u64( (self.lo.0 as u64) | ((self.hi.0 as u64) << 32) )
    }
}

impl Decodable for Span {
    fn decode<D: Decoder>(d: &mut D) -> Result<Span, D::Error> {
        let lo_hi: u64 = try! { d.read_u64() };
        let lo = BytePos(lo_hi as u32);
        let hi = BytePos((lo_hi >> 32) as u32);
        Ok(mk_sp(lo, hi))
    }
}
```

### PR DESCRIPTION
**Pull request by erickt**
The protocol for `serialize::{En,De}code` doesn't allow for two integers to be serialized next to each other.

Closes #31025.

cc @michaelwoerister

### CODE REVIEW

**Comment by sfackler** [comment]
Large numbers are always somewhat sketchy to work with in JSON since they'll so often round trip through a double. Should we maybe encode with the packed number in a string?

**Comment by erickt** [comment]
@sfackler: True, although `libserialize`, `rustc-serialize`, and `serde` all are able to properly parse out `u64` numbers, we can't assume other json parsers can read them. From what I understand, we only have to worry about dropping values if we ever get to `2^53 + 1`. All other integers below that are representible in an f64. So I'm not sure how often this will come up in practice :)

**Comment by sfackler** [comment]
I've seen it hit in systems that use randomly generated 64 bit identifiers, for example.

In this case, I think it'd require a high span index greater than 2^21, which is roughly 2 million. It seems not wildly unreasonable to have 2 megabytes of source code for a crate, but I'm not sure.

**Comment by michaelwoerister** [comment]
How bad would it be for JSON to encode spans as structs? Because for the binary encoding that is used for crate metadata, there's no more overhead for these. The main reason for encoding it as two separate values was to allow for the variable-length integer format to kick in properly.

**Comment by erickt** [comment]
@michaelwoerister: Yeah, serializing them into structs would work.

We can save this for another time, but we could also optimize the rbml tuple encoding (and tuple structs) to match that of structs by leaving out the tag and the length encoding. We'd lose some safety, but it might shave some more bytes off our metadata.

**Comment by michaelwoerister** [comment]
@erickt No need to touch RBML, I think. The bulk of spans stored in metadata is within *opaque* sections where we don't have any of this overhead anymore since #30565. So I'd say, just do the clean solution and encode spans as structs.

**Comment by erickt** [comment]
@sfackler / @michaelwoerister: I've updated the patch to serialize Spans as a struct. Tests passed locally, and the size of the libraries seems to be identical to before this patch.

File: src/libsyntax/codemap.rs [hunk 1]
```diff
@@ -164,16 +164,31 @@ impl Eq for Span {}
...
 impl Encodable for Span {
     fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error> {
-        try!(s.emit_u32(self.lo.0));
-        s.emit_u32(self.hi.0)
+        s.emit_struct("Span", 2, |s| {
+            try!(s.emit_struct_field("lo", 0, |s| {
+                self.lo.encode(s)
+            }));
+
+            s.emit_struct_field("hi", 0, |s| {
```
Comment (michaelwoerister) [inline src/libsyntax/codemap.rs]: The field index should be 1 here.

File: src/libsyntax/codemap.rs [hunk 2]
```diff
@@ -164,16 +164,31 @@ impl Eq for Span {}
...
     fn decode<D: Decoder>(d: &mut D) -> Result<Span, D::Error> {
-        let lo = BytePos(try! { d.read_u32() });
-        let hi = BytePos(try! { d.read_u32() });
-        Ok(mk_sp(lo, hi))
+        d.read_struct("Span", 2, |d| {
+            let lo = try!(d.read_struct_field("lo", 0, |d| {
+                BytePos::decode(d)
+            }));
+
+            let hi = try!(d.read_struct_field("hi", 0, |d| {
```
Comment (michaelwoerister) [inline src/libsyntax/codemap.rs]: Same as above

**Comment by michaelwoerister** [comment]
r=me if you fix those two errors.

**Comment by erickt** [comment]
Thanks @michaelwoerister!
