### PR TITLE
fix: Error on illegal `[const]`s inside blocks within legal positions

### LINKED ISSUE #132067: `~const` is allowed on structs (and other bad positions) within `const fn`.
We now silently accept `~const Trait` in illegal positions when they're nested in legal positions, because AST validation is not smart enough. I think it would be nice if we made validation more robust; perhaps moving it to ast lowering is the best thing to do.

_Originally posted by @compiler-errors in https://github.com/rust-lang/rust/pull/131985#discussion_r1812880692_

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes rust-lang/rust#132067

I initially considered moving `[const]` validations to `rustc_ast_lowering`, but that approach would require adding constness information to `AssocCtxt`, which introduces significant changes - especially within `rustc_expand` - just to support a single use case here:

https://github.com/rust-lang/rust/blob/3fb1b53a9dbfcdf37a4b67d35cde373316829930/compiler/rustc_ast_passes/src/ast_validation.rs#L1596-L1610

Instead, I believe it's sufficient to simply "reset" `[const]` allowness whenever we enter a new block.

### CODE REVIEW

File: tests/ui/traits/const-traits/conditionally-const-in-struct-args.rs [hunk 1]
```diff
@@ -1,7 +1,3 @@
-//@ compile-flags: -Znext-solver
```
Comment (ShoyuVanilla) [inline tests/ui/traits/const-traits/conditionally-const-in-struct-args.rs:1]: I guess this flags were introduced to prevent triggering other ICEs but we don't need this anymore?

File: tests/ui/unpretty/exhaustive.rs [hunk 2]
```diff
@@ -807,7 +807,6 @@ mod types {
         let _: impl Send + 'static;     //[hir]~ ERROR `impl Trait` is not allowed
         let _: impl 'static + Send;     //[hir]~ ERROR `impl Trait` is not allowed
         let _: impl ?Sized;             //[hir]~ ERROR `impl Trait` is not allowed
-        let _: impl [const] Clone;       //[hir]~ ERROR `impl Trait` is not allowed
```
Comment (ShoyuVanilla) [inline tests/ui/unpretty/exhaustive.rs]: This one used to pass ast passes - and failing tests with this PR - but I think it shouldn't

Comment (compiler-errors) [reply tests/ui/unpretty/exhaustive.rs]: Hm, yeah this should definitely still be allowed. `impl [const] Clone` is valid in a const fn with the `impl_trait_in_bindings`, and it should for example work in this case:

```
const fn foo<T: [const] Foo>(x: &T) {
    let y: &impl [const] Foo = x;
}
```

`impl_trait_in_bindings` is probably just broken with `[const]`-ness. If you could fix the AST validation, then that would be great. Otherwise, I'd at least like to understand why it is broken so it can have a proper FIXME in the codebase and so we can file an issue to fix it as a follow-up.

Comment (ShoyuVanilla) [reply tests/ui/unpretty/exhaustive.rs]: Oh, I wasn't aware of `impl_trait_in_bindings` 😅 I'll try fixing this AST validation with proper interaction with that feature. Thanks!

**Comment by ShoyuVanilla** [comment]
So, I’ve prohibited the following:

- Any usage of `[const] Trait` bounds on ADTs, regardless of position—including inside `const fn` bodies.
- Any local usages of `[const] Trait` bounds (I doubt there would be any case other than `impl [const] Trait` within `impl_trait_in_binding`) inside anonymous constants, such as in const generic arguments. They are still allowed in legal places like `const fn` bodies.
