### PR TITLE
Gracefully handle ternary operator

### LINKED ISSUE #112578: Non-existant ternary operator is not gracefully handled
### Code

```Rust
fn main() {
    let x = 5 > 2 ? 3 : 1;
}
```

### Current output

```Shell
Compiling rust-playground v0.1.0 (/Users/Jens.Hausdorf/dev/rust-playground)
error: expected one of `.`, `;`, `?`, `else`, or an operator, found `3`
 --> src/main.rs:2:21
  |
2 |     let x = 5 > 2 ? 3 : 1;
  |                     ^ expected one of `.`, `;`, `?`, `else`, or an operator

error: could not compile `rust-playground` (bin "rust-playground") due to previous error
```

### Desired output

```Shell
Compiling rust-playground v0.1.0 (/Users/Jens.Hausdorf/dev/rust-playground)
error: should have used inline if-expression instead
 --> src/main.rs:2:21
  |
2 |     let x = 5 > 2 ? 3 : 1;
  |                     ^ expected one of `.`, `;`, `?`, `else`, or an operator
help: consider changing this to use if-expression
  |
2 |     let x = if 5 > 2 { 3 } else { 1 };
  |  
error: could not compile `rust-playground` (bin "rust-playground") due to previous error
```

### Rationale and extra context

New rustaceans might expect that Rust has the ternary operator.

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Centri3**
Fixes #112578

~~May not be the best way to do this as it doesn't check for a single `:`, so it could perhaps appear even when the actual issue is just a missing semicolon. May not be the biggest deal, though?~~

Nevermind, got it working properly now ^^

### CODE REVIEW

File: tests/ui/parser/ternary_operator.rs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+}
+
+fn d() {
+    let x = 5 > 2 ? { let x = vec![]: Vec<u16>; x } : { false }; //~ ERROR Rust has no ternary operator
+    //~^ HELP use an `if-else` expression instead
+    //~^^ ERROR expected one of `.`, `;`, `?`, `else`, or an operator, found `:`
+    //~^^^ ERROR the `?` operator can only be applied to values that implement `Try`
+    //~^^^^ HELP the trait `Try` is not implemented for `{integer}`
+    //~^^^^^ ERROR the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`) [E0277]
+    //~^^^^^^ HELP the trait `FromResidual<_>` is not implemented for `()`
```
Comment (compiler-errors) [inline tests/ui/parser/ternary_operator.rs:33]:
```suggestion
    //~| ERROR expected one of `.`, `;`, `?`, `else`, or an operator, found `:`
    //~| ERROR the `?` operator can only be applied to values that implement `Try`
    //~| HELP the trait `Try` is not implemented for `{integer}`
    //~| ERROR the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`) [E0277]
    //~^^^^^^ HELP the trait `FromResidual<_>` is not implemented for `()`
```

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 2]
```diff
@@ -339,14 +339,20 @@ impl<'a> Parser<'a> {
...
 
-        let err = ExpectedIdentifier {
-            span: bad_token.span,
-            token: bad_token,
-            suggest_raw,
-            suggest_remove_comma,
-            help_cannot_start_number,
+        let mut err = if let Some(lo) = self.maybe_ternary_lo && self.token == token::Colon {
+            self.bump();
+            self.parse_expr()?;
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:344]: Can you [snapshot](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/parser/struct.Parser.html#method.create_snapshot_for_diagnostic) the parser before the bump and recover `Err` from `parse_expr` by canceling the error, restoring the snapshot, and falling into the branch below?

I'd like for this ternary error to not result in some even more cursed knockdown errors.

File: tests/ui/parser/ternary_operator.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/parser/ternary_operator.rs:33]: (also elsewhere)

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 2 above)
Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs:344]: Would this be necessary in `maybe_recover_from_ternary_operator` as well?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs:344]: Yeah... hm... ideally those two places wouldn't be doing almost the same exact logic as well...

Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs:344]: Yeah it's unfortunate, but `expected_ident_found` seems to be necessary as otherwise it'll sometimes complain about finding `:` instead of an identifier. I'm not entirely sure why the other check in `expected_one_of_not_found` doesn't cover it :/

Parsing the second expression should be extracted though

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 3]
```diff
@@ -1330,6 +1337,37 @@ impl<'a> Parser<'a> {
...
+                    return Err(err);
+                }
+            }
+
+            self.bump();
+            if self.parse_expr().map_err(|err| err.cancel()).is_ok() {
+                self.sess.emit_err(TernaryOperator { span: self.token.span.with_lo(lo) });
+            } else {
+                self.restore_snapshot(snapshot);
+            }
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1363]: can you use a match here rather than if_else + map_err + is_ok? :smile_cat:

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 4]
```diff
@@ -1330,6 +1337,37 @@ impl<'a> Parser<'a> {
...
+        } else {
+            self.restore_snapshot(snapshot);
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1365]: This isn't actually restoring anything, is it?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 5]
```diff
@@ -1330,6 +1337,37 @@ impl<'a> Parser<'a> {
         }
     }
 
+    /// Rust has no ternary operator (`cond ? then : else`). Parse it and try
+    /// to recover from it if `then` and `else` are valid expressions.
+    pub(super) fn maybe_recover_from_ternary_operator(&mut self) -> PResult<'a, ()> {
+        let snapshot = self.create_snapshot_for_diagnostic();
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1343]: Move this into the `if` statement right before the parse?

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 6]
```diff
@@ -1330,6 +1337,37 @@ impl<'a> Parser<'a> {
...
+        let Some(lo) = self.maybe_ternary_lo else {
+            return Ok(());
+        };
+
+        if self.prev_token == token::Question {
+            if let Err(err) = self.parse_expr() {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1349]: Can you explain why we're recovering the failure case here? Does `parse_expr` try to eat the `:` here? I would've expected it to leave the colon behind, i.e. for the code to look more like:

```
match self.parse_expr() {
  Ok(_) if self.token == token::Colon => { /* keep going */ },
  Ok(_) => { self.restore_snapshot(snapshot); return Ok(()); }
  Err(e) => { e.cancel(); self.restore_snapshot(snapshot); return Ok(()); }
}

self.bump(); // eat `:`
```

File: tests/ui/parser/ternary_operator.rs [hunk 7]
```diff
@@ -0,0 +1,38 @@
+#![no_main]
+
+fn a() {
+    let x = 5 > 2 ? true : false; //~ ERROR Rust has no ternary operator
```
Comment (compiler-errors) [inline tests/ui/parser/ternary_operator.rs:4]: nit: `//~^` is easier to read when chained all the way down

```suggestion
    let x = 5 > 2 ? true : false;
    //~^ ERROR Rust has no ternary operator
```

File: tests/ui/parser/ternary_operator.rs [hunk 8]
```diff
@@ -0,0 +1,38 @@
+#![no_main]
```
Comment (compiler-errors) [inline tests/ui/parser/ternary_operator.rs:1]: nit: there's no reason to use `no_main` here :sweat_smile: either add a dummy main, or use `// compile-flags: --crate-type=lib` or something. adding a dummy main is the easiest, tho.

File: tests/ui/parser/ternary_operator.stderr [hunk 9]
```diff
@@ -0,0 +1,113 @@
...
+   |
+   = help: use an `if-else` expression instead
+
+error[E0277]: the `?` operator can only be applied to values that implement `Try`
+  --> $DIR/ternary_operator.rs:4:17
+   |
+LL |     let x = 5 > 2 ? true : false;
+   |                 ^^^ the `?` operator cannot be applied to type `{integer}`
+   |
+   = help: the trait `Try` is not implemented for `{integer}`
```
Comment (compiler-errors) [inline tests/ui/parser/ternary_operator.stderr:45]: Hmm... it's somewhat disappointing that this is still being parsed as a try expr... :thinking:

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 6 above)
Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1349]: Kind of, it thinks it's type ascription unfortunately on cases like `f32::MAX` and errors on it. Not sure if there's a better way to do it.

File: tests/ui/parser/ternary_operator.stderr (hunk 9 above)
Comment (compiler-errors) [reply tests/ui/parser/ternary_operator.stderr:45]: Something like:

```
if has_question {
    // `expr?`
    e = self.mk_expr(lo.to(self.prev_token.span), ExprKind::Try(e));
    if self.may_recover() && self.token == tok::Colon {
        // try recover here, setting up `e` to be an if statement so that typeck is happy...
    }
    continue;
}
```

Comment (Centri3) [reply tests/ui/parser/ternary_operator.stderr:45]: Yeah ideally it wouldn't, that part of it still feels very terse. I don't see where `?` is parsed though, can you give some pointers? I was thinking it could perhaps then modify the previous expression to remove the try.

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 6 above)
Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1349]: See my comment below about possibly implementing this logic in `parse_expr_dot_or_call_with_` with eager lookahead and `Parser::may_recover` instead.

File: tests/ui/parser/ternary_operator.rs (hunk 8 above)
Comment (Centri3) [reply tests/ui/parser/ternary_operator.rs:1]: Yeah that's just generally how it's done in clippy ^^ I'm fine with anything else

File: tests/ui/parser/ternary_operator.stderr (hunk 9 above)
Comment (compiler-errors) [reply tests/ui/parser/ternary_operator.stderr:45]: https://github.com/rust-lang/rust/blob/1821920cc8e7dc44b0035da890170bf3eadc2ae9/compiler/rustc_parse/src/parser/expr.rs#L962-L975

Comment (compiler-errors) [reply tests/ui/parser/ternary_operator.stderr:45]: But to be very clear, I'd be happy to approve this without having to rewrite this another time, if you address all the other comments above.

Comment (Centri3) [reply tests/ui/parser/ternary_operator.stderr:45]: I'd gladly do it in hopes of a better diagnostic :)

File: compiler/rustc_parse/src/parser/diagnostics.rs (hunk 6 above)
Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs:1349]: I've implemented it there now, it still needs to do this though. It basically does the inverse of what it did before: It checks if it successfully parses an expression, then a `:`, then another expression after a `?`. Shouldn't cause any noticeable issues but checking this on *every* `?` is terrible, imo, so is there a better way to do that?

Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Ok it caused noticeable issues :sweat_smile:, looks like it also checks after a match on an `expr?` which means an unexpected `if` may appear. All good, except for the fact that it emits this error without returning `Err`... So we can't cancel it.

This will likely need a different approach.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Ugh, yeah, there are cases where this may be ambiguous, e.g. `expr ? - expr`

Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: That would fail to find the `: expr`, though. So I *think* it won't complain about the ternary unless there's an invalid expression, then a `:`, then an actual expression, which is never valid syntax afaik. Unless I'm misunderstanding?

Regardless though, is there a way to 'silence' diagnostics temporarily, like with snapshots?

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: No you're correct, but we should probably only be doing this somewhat expensive parsing if we know we're (almost surely) on an error path, which is pretty difficult to form a heuristic for..

Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: It's probably easier to move it back to `expected_one_of_not_found` then, but store a mutable reference to the `?`. That way we can modify it if we're allowed to recover. That way we for sure only do it on an error path

Comment (Centri3) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Ignore i.e. keep them or somehow suppress them? I'm fine with either.

Comment (compiler-errors) [reply compiler/rustc_parse/src/parser/diagnostics.rs]: Keep them

File: compiler/rustc_parse/src/parser/diagnostics.rs [hunk 10]
```diff
@@ -1330,6 +1337,41 @@ impl<'a> Parser<'a> {
         }
     }
 
+    /// Rust has no ternary operator (`cond ? then : else`). Parse it and try
+    /// to recover from it if `then` and `else` are valid expressions.
+    pub(super) fn maybe_recover_from_ternary_operator(&mut self) -> PResult<'a, ()> {
```
Comment (compiler-errors) [inline compiler/rustc_parse/src/parser/diagnostics.rs:1342]: nit: i don't see any `?`, can this just return nothing?

**Comment by compiler-errors** [comment]
gotta do a perf run cause parser is larger

@bors try @rust-timer queue

**Comment by Centri3** [comment]
I actually just removed the `maybe_ternary_lo` field, so it should be the same size again. But yeah a perf run is wise

**Review by compiler-errors — APPROVED** [review]
