### PR TITLE
Fix incorrect trait privacy error

### LINKED ISSUE #21670: "error: source trait is private" (fixed by adding `use` of *struct*)
My attempt to call `Any::get_type_id()` and use its return value of as an instance of `fmt::Debug` does not work without import of `std::any::TypeId` *struct*: http://doc.rust-lang.org/std/any/struct.TypeId.html

Example code:

```rust
use std::thread;
// use std::any::TypeId; // uncomment this line to make the compile work

fn main() {
    let b1 = Box::new(3u64);
    println!("hello world, b1: {:?}", b1);
    let child = thread::Thread::scoped(|| {
        let b2 = Box::new(4u64);
        println!("other thread b2: {:?}", b2);
    });
    match child.join() {
        Ok(()) => {}
        Err(ref panic_arg) => {
            if let Some(s) = panic_arg.downcast_ref::<&str>() {
                println!("whoops child died with str: {}", s);
            } else if let Some(s) = panic_arg.downcast_ref::<String>() {
                println!("whoops child died with String: {}", s);
            } else {
                let id = panic_arg.get_type_id();
                println!("whoops child died with unknown panic arg, id: {:?}", id);
            }
        }
    }
}
```

Transcript of attempt to compile:
```
<anon>:19:26: 19:49 error: source trait is private
<anon>:19                 let id = panic_arg.get_type_id();
                                   ^~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

### PR DESCRIPTION
**Pull request by jseyfried**
This PR fixes #21670 by using the crate metadata instead of `ExternalExports` to determine if an external item is public.

r? @nikomatsakis

### CODE REVIEW

**Comment by arielb1** [comment]
There's some seriously ugly code triplication in `fn def_privacy`.

File: src/librustc_privacy/lib.rs [hunk 1]
```diff
@@ -498,7 +497,7 @@ impl<'a, 'tcx> PrivacyVisitor<'a, 'tcx> {
         let node_id = if let Some(node_id) = self.tcx.map.as_local_node_id(did) {
             node_id
         } else {
-            if self.external_exports.contains(&did) {
+            if self.tcx.sess.cstore.visibility(did) == hir::Public {
                 debug!("privacy - {:?} was externally exported", did);
                 return Allowable;
             }
```
Comment (arielb1) [inline src/librustc_privacy/lib.rs]: Terrible triplication below this line. Could you clean it up?

**Comment by jseyfried** [comment]
@arielb1 Agreed. Once this PR and #31938 land, I'm going to refactor away `PrivacyVisitor` entirely, so I'd prefer not to clean it up now.

**Comment by nikomatsakis** [comment]
@jseyfried Wonderful. I much prefer this fix to the old one :)
