### PR TITLE
Make `x test distcheck` self-contained

### LINKED ISSUE #145183: distcheck uses submodules of the repo, not the tarball
### Summary

Discovered while working on #145121 - https://github.com/rust-lang/rust/pull/145121#issuecomment-3169618351

`Distcheck` invokes `make check` which runs `.../build/tmp/distcheck/src/bootstrap/bootstrap.py test --stage 2`

when the inner bootstrap runs, it calls `compute_src_directory` where `flags_src` is `None`

https://github.com/rust-lang/rust/blob/ffb9d94dcf4ade0d534842be3672d5e9f47e1333/src/bootstrap/src/core/config/config.rs#L473-L475

And `compute_src_directory` ends up executing `git rev-parse --show-cdup` with cwd in `.../build/tmp/distcheck` so it ends up setting `src` to the outer git checkout, not the current extracted tarball.  From there, all the `git_info` for the submodules ends up finding them in the outer git checkout.

As a result, the LLVM build, for example, uses the source code from the surrounding git repository, not the source code from the extracted tarball (which has a subset of the LLVM projects):

Here is an example from CI, in [this build](https://github.com/rust-lang/rust/actions/runs/16840316716/job/47709809269)  the raw log has this:

```
2025-08-08T21:21:12.0222503Z running: cd "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/llvm/build" && CMAKE_PREFIX_PATH="" DESTDIR="" LC_ALL="C" "cmake" "/checkout/src/llvm-project/llvm" "-G" "Ninja" "-DLLVM_ENABLE_ASSERTIONS=ON" "-DLLVM_UNREACHABLE_OPTIMIZE=OFF" "-DLLVM_ENABLE_PLUGINS=OFF" "-DLLVM_TARGETS_TO_BUILD=AArch64;AMDGPU;ARM;BPF;Hexagon;LoongArch;MSP430;Mips;NVPTX;PowerPC;RISCV;Sparc;SystemZ;WebAssembly;X86" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR;M68k;CSKY;Xtensa" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_INCLUDE_BENCHMARKS=OFF" "-DLLVM_INCLUDE_TESTS=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_ENABLE_BINDINGS=OFF" "-DLLVM_ENABLE_Z3_SOLVER=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=4" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DLLVM_ENABLE_WARNINGS=OFF" "-DLLVM_INSTALL_UTILS=ON" "-DLLVM_ENABLE_ZLIB=ON" "-DLLVM_ENABLE_LIBXML2=OFF" "-DLLVM_VERSION_SUFFIX=-rust-1.91.0-nightly" "-DCMAKE_INSTALL_MESSAGE=LAZY" "-DCMAKE_C_COMPILER_LAUNCHER=sccache" "-DCMAKE_CXX_COMPILER_LAUNCHER=sccache" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_ASM_COMPILER=cc" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_SHARED_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++" "-DCMAKE_MODULE_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++" "-DCMAKE_EXE_LINKER_FLAGS= -Wl,-Bsymbolic -static-libstdc++" "-DLLVM_ENABLE_ZSTD=OFF" "-DCMAKE_INSTALL_PREFIX=/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_BUILD_TYPE=Release"
```

we're in the `build/tmp/distcheck` build but the sources we're compiling are `/checkout/src/llvm-project/llvm` not `build/tmp/distcheck/src/llvm-project`

### Command used

```sh
./x test distcheck
```

### Expected behaviour

Distcheck checks the submodule sources from the tarball

### Actual behaviour

Distcheck checks the submodule sources of the enclosing git repo.

### Bootstrap configuration (bootstrap.toml)
```toml
profile = 'dist'

[llvm]
download-ci-llvm = false
targets = "AArch64;X86"

[gcc]

[build]

# Arguments passed to the `./configure` script, used during distcheck. You
# probably won't fill this in but rather it's filled in by the `./configure`
# script. Useful for debugging.
configure-args = []

[install]

[rust]
download-rustc = false

[dist]
compression-formats = ["gz"]

[target.x86_64-unknown-linux-gnu]
```

### Operating system

All

### HEAD

2886b36df4a

### Additional context

Fixing this issue will uncover a problem with the Tidy check [`gcc_submodule`](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/gcc_submodule.rs) - the check ensures that the gcc submodule is up to date with respect to the codegen_gcc backend.  However the tarball explicitly excludes `src/gcc` and as a result the tidy check will fail in the tarball.

One way to fix the check is to look for the `src/gcc/notice.txt` file that is generated in the tarball and skip the rest of the tidy check.

https://github.com/rust-lang/rust/blob/ca77504943887037504c7fc0b9bf06dab3910373/src/bootstrap/src/core/build_steps/dist.rs#L1119-L1124

### PR DESCRIPTION
**Pull request by Kobzol**
Before, the checked components were extracted under the checked out source root, which caused us to test some weird combination of tarball + checkout sources/aritfacts/configuration.

Now `x test distcheck` works with an external temporary directory instead, which should make it self-contained. I also moved some config from the Dockerfile to the test itself, and fixed an issue in tidy that caused `x test tidy` to fail on tarball sources.

I also removed `.args(&builder.config.configure_args)`, because it was passing all kinds of crap from the CI config to the distcheck step, which was making it less reproducible.

Fixes: https://github.com/rust-lang/rust/issues/145183

r? @jieyouxu

try-job: x86_64-gnu-distcheck

### CODE REVIEW

**Comment by Kobzol** [comment]
Ok, should be ready for a review.

File: src/bootstrap/src/lib.rs [hunk 1]
```diff
@@ -1950,6 +1950,20 @@ impl Build {
         t!(fs::remove_dir_all(dir))
     }
 
+    /// Make sure that `dir` will be an empty existing directory after this function ends.
+    /// If it existed before, it will be first deleted.
+    fn clear_dir(&self, dir: &Path) {
```
Comment (jieyouxu) [inline src/bootstrap/src/lib.rs:1955]: Question: can this use `build_helper::remove_and_create_dir_all`?

File: src/ci/docker/host-x86_64/x86_64-gnu-distcheck/Dockerfile [hunk 2]
```diff
@@ -33,9 +33,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 COPY scripts/sccache.sh /scripts/
 RUN sh /scripts/sccache.sh
 
-# We are disabling CI LLVM since distcheck is an offline build.
-ENV NO_DOWNLOAD_CI_LLVM 1
+# Make distcheck builds faster
+ENV DISTCHECK_CONFIGURE_ARGS "--enable-sccache"
```
Comment (jieyouxu) [inline src/ci/docker/host-x86_64/x86_64-gnu-distcheck/Dockerfile:37]: Question: hm, can this caching accidentally cause what should've failed in distcheck to pass?

**Review by jieyouxu — COMMENTED** [review]
Two questions

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145845/ee361e8fca1c30e13e7a31cc82b64c045339d3a8..2ea8621779f0ed509ab28e11e3113b9ccb330262)*

File: src/bootstrap/src/lib.rs (hunk 1 above)
Comment (Kobzol) [reply src/bootstrap/src/lib.rs:1955]: I would rather introduce the I/O helpers into bootstrap directly, so that they can integrate with (I/O) tracing spans.

File: src/ci/docker/host-x86_64/x86_64-gnu-distcheck/Dockerfile (hunk 2 above)
Comment (Kobzol) [reply src/ci/docker/host-x86_64/x86_64-gnu-distcheck/Dockerfile:37]: I certainly hope not, because we use it everywhere in our CI, even on dist builders, so if it caused something like that, we have bigger problems.

File: src/bootstrap/src/lib.rs (hunk 1 above)
Comment (jieyouxu) [reply src/bootstrap/src/lib.rs:1955]: Okay, that makes sense

**Review by jieyouxu — APPROVED** [review]
Thanks

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145845/ee361e8fca1c30e13e7a31cc82b64c045339d3a8..2ea8621779f0ed509ab28e11e3113b9ccb330262)*
