### PR TITLE
Map RPIT duplicated lifetimes back to fn captured lifetimes

### LINKED ISSUE #114285: ICE: `Region parameter out of range when substituting in region`
While compiling the [`diagnostics`](https://github.com/latex-lsp/texlab/tree/master/crates/diagnostics) subcrate of [`texlab`](https://github.com/latex-lsp/texlab) with recent nightlies.

### Code

```Rust
pub struct Key;
#[derive(Clone)]
pub struct Value;

use std::collections::HashMap;

pub struct DiagnosticBuilder<'db> {
    inner: HashMap<&'db Key, Vec<&'db Value>>,
}

impl<'db> DiagnosticBuilder<'db> {
    pub fn iter(&self) -> impl Iterator<Item = (&'db Key, impl Iterator<Item = &Value>)> {
        self.inner
            .iter()
            .map(|(key, values)| (*key, values.iter().map(|v| *v)))
    }
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0e5e65e841a2f0b98c671f668240ed2b)

### Meta

With stable (`1.71.0`) and beta (`1.72.0-beta.3`) it compiles fine.

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (32303b219 2023-07-29)
binary: rustc
commit-hash: 32303b219d4dffa447aa606bc11c7a648f44a862
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:808:13: Region parameter out of range when substituting in region '_ (index=2, args = [ReEarlyBound(DefId(0:207 ~ diagnostics[32bc]::{impl#0}::'db), 0, 'db), ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrNamed(DefId(0:402 ~ diagnostics[32bc]::{impl#0}::iter::'_), '_) })])
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/compiler/rustc_errors/src/lib.rs:1645:9
stack backtrace:
   0:     0x7f3b46362fc1 - std::backtrace_rs::backtrace::libunwind::trace::he692921cd71061da
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3b46362fc1 - std::backtrace_rs::backtrace::trace_unsynchronized::h268323222e8c1ab8
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3b46362fc1 - std::sys_common::backtrace::_print_fmt::haee60c61afbc4ed3
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f3b46362fc1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd36c36e4b57d240a
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3b463c949c - core::fmt::rt::Argument::fmt::h0bae45bdae59332b
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/fmt/rt.rs:138:9
   5:     0x7f3b463c949c - core::fmt::write::h1eff66863ae03e81
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f3b463557ae - std::io::Write::write_fmt::ha8cad047da0cc87b
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/io/mod.rs:1714:15
   7:     0x7f3b46362dd5 - std::sys_common::backtrace::_print::h55c2e79c6c43fc91
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f3b46362dd5 - std::sys_common::backtrace::print::ha1cd10f2ad29b00d
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f3b46365e2a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h1c11dff971492549
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:278:22
  10:     0x7f3b46365996 - std::panicking::panic_hook_with_disk_dump::hffdc434b289dce74
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:305:9
  11:     0x7f3b49617f39 - rustc_driver_impl[2f0949cc27d93100]::install_ice_hook::{closure#0}
  12:     0x7f3b463666d0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h85e1510843a93c91
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2021:9
  13:     0x7f3b463666d0 - std::panicking::rust_panic_with_hook::hf537c3fb4549c7ab
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:733:13
  14:     0x7f3b49be3271 - std[ec332d703e613242]::panicking::begin_panic::<rustc_errors[e840185ed010efcf]::ExplicitBug>::{closure#0}
  15:     0x7f3b49be1cd6 - std[ec332d703e613242]::sys_common::backtrace::__rust_end_short_backtrace::<std[ec332d703e613242]::panicking::begin_panic<rustc_errors[e840185ed010efcf]::ExplicitBug>::{closure#0}, !>
  16:     0x7f3b49ba3ab6 - std[ec332d703e613242]::panicking::begin_panic::<rustc_errors[e840185ed010efcf]::ExplicitBug>
  17:     0x7f3b49bda934 - <rustc_errors[e840185ed010efcf]::HandlerInner>::bug::<alloc[3f9bbb105762381e]::string::String>
  18:     0x7f3b49bda7c6 - <rustc_errors[e840185ed010efcf]::Handler>::bug::<alloc[3f9bbb105762381e]::string::String>
  19:     0x7f3b49bc084c - rustc_middle[e8d608d57e197328]::util::bug::opt_span_bug_fmt::<rustc_span[3261ff60f64e7044]::span_encoding::Span>::{closure#0}
  20:     0x7f3b49bbf64a - rustc_middle[e8d608d57e197328]::ty::context::tls::with_opt::<rustc_middle[e8d608d57e197328]::util::bug::opt_span_bug_fmt<rustc_span[3261ff60f64e7044]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f3b49bbf618 - rustc_middle[e8d608d57e197328]::ty::context::tls::with_context_opt::<rustc_middle[e8d608d57e197328]::ty::context::tls::with_opt<rustc_middle[e8d608d57e197328]::util::bug::opt_span_bug_fmt<rustc_span[3261ff60f64e7044]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f3b47fa4c60 - rustc_middle[e8d608d57e197328]::util::bug::bug_fmt
  23:     0x7f3b49bd3cf1 - <rustc_middle[e8d608d57e197328]::ty::generic_args::ArgFolder as rustc_type_ir[982dbabe9c9a37e2]::fold::TypeFolder<rustc_middle[e8d608d57e197328]::ty::context::TyCtxt>>::fold_region::region_param_out_of_range
  24:     0x7f3b476945e0 - <rustc_middle[e8d608d57e197328]::ty::generic_args::GenericArg as rustc_type_ir[982dbabe9c9a37e2]::fold::TypeFoldable<rustc_middle[e8d608d57e197328]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[e8d608d57e197328]::ty::generic_args::ArgFolder>
  25:     0x7f3b4768e76f - <rustc_middle[e8d608d57e197328]::ty::Ty as rustc_type_ir[982dbabe9c9a37e2]::fold::TypeSuperFoldable<rustc_middle[e8d608d57e197328]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[e8d608d57e197328]::ty::generic_args::ArgFolder>
  26:     0x7f3b476944fa - <rustc_middle[e8d608d57e197328]::ty::generic_args::GenericArg as rustc_type_ir[982dbabe9c9a37e2]::fold::TypeFoldable<rustc_middle[e8d608d57e197328]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[e8d608d57e197328]::ty::generic_args::ArgFolder>
  27:     0x7f3b4768e76f - <rustc_middle[e8d608d57e197328]::ty::Ty as rustc_type_ir[982dbabe9c9a37e2]::fold::TypeSuperFoldable<rustc_middle[e8d608d57e197328]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[e8d608d57e197328]::ty::generic_args::ArgFolder>
  28:     0x7f3b486ce2e3 - rustc_hir_analysis[ac900bc9cb535ca9]::check::check::check_mod_item_types
  29:     0x7f3b4825d85c - rustc_query_impl[7a7d4cbbbc398ddf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e8d608d57e197328]::query::erase::Erased<[u8; 0usize]>>
  30:     0x7f3b4825d83e - <rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core[7c3dc332a8e1c229]::ops::function::FnOnce<(rustc_middle[e8d608d57e197328]::ty::context::TyCtxt, rustc_span[3261ff60f64e7044]::def_id::LocalDefId)>>::call_once
  31:     0x7f3b4825a9b0 - rustc_query_system[86f95befa84333f8]::query::plumbing::try_execute_query::<rustc_query_impl[7a7d4cbbbc398ddf]::DynamicConfig<rustc_query_system[86f95befa84333f8]::query::caches::VecCache<rustc_span[3261ff60f64e7044]::def_id::LocalDefId, rustc_middle[e8d608d57e197328]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7a7d4cbbbc398ddf]::plumbing::QueryCtxt, true>
  32:     0x7f3b48f7c1b2 - rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::check_mod_item_types::get_query_incr::__rust_end_short_backtrace
  33:     0x7f3b489f7f67 - <rustc_middle[e8d608d57e197328]::hir::map::Map>::for_each_module::<rustc_hir_analysis[ac900bc9cb535ca9]::check_crate::{closure#6}::{closure#0}>
  34:     0x7f3b489f665f - rustc_hir_analysis[ac900bc9cb535ca9]::check_crate
  35:     0x7f3b489f1c6a - rustc_interface[3259f0f1c0f54e17]::passes::analysis
  36:     0x7f3b48b16a4a - rustc_query_impl[7a7d4cbbbc398ddf]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e8d608d57e197328]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7f3b48b16a39 - <rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::analysis::dynamic_query::{closure#2} as core[7c3dc332a8e1c229]::ops::function::FnOnce<(rustc_middle[e8d608d57e197328]::ty::context::TyCtxt, ())>>::call_once
  38:     0x7f3b48dfadf6 - rustc_query_system[86f95befa84333f8]::query::plumbing::try_execute_query::<rustc_query_impl[7a7d4cbbbc398ddf]::DynamicConfig<rustc_query_system[86f95befa84333f8]::query::caches::SingleCache<rustc_middle[e8d608d57e197328]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7a7d4cbbbc398ddf]::plumbing::QueryCtxt, true>
  39:     0x7f3b48dfa96e - rustc_query_impl[7a7d4cbbbc398ddf]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  40:     0x7f3b4888e4d5 - <rustc_middle[e8d608d57e197328]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[2f0949cc27d93100]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>
  41:     0x7f3b4888db02 - <rustc_interface[3259f0f1c0f54e17]::interface::Compiler>::enter::<rustc_driver_impl[2f0949cc27d93100]::run_compiler::{closure#1}::{closure#2}, core[7c3dc332a8e1c229]::result::Result<core[7c3dc332a8e1c229]::option::Option<rustc_interface[3259f0f1c0f54e17]::queries::Linker>, rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>
  42:     0x7f3b48886bb8 - std[ec332d703e613242]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3259f0f1c0f54e17]::util::run_in_thread_pool_with_globals<rustc_interface[3259f0f1c0f54e17]::interface::run_compiler<core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>, rustc_driver_impl[2f0949cc27d93100]::run_compiler::{closure#1}>::{closure#0}, core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>
  43:     0x7f3b4888633e - <<std[ec332d703e613242]::thread::Builder>::spawn_unchecked_<rustc_interface[3259f0f1c0f54e17]::util::run_in_thread_pool_with_globals<rustc_interface[3259f0f1c0f54e17]::interface::run_compiler<core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>, rustc_driver_impl[2f0949cc27d93100]::run_compiler::{closure#1}>::{closure#0}, core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c3dc332a8e1c229]::result::Result<(), rustc_span[3261ff60f64e7044]::ErrorGuaranteed>>::{closure#1} as core[7c3dc332a8e1c229]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f3b46370dc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc5b9f463e020ec3e
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2007:9
  45:     0x7f3b46370dc5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h140e20c91de13bb4
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2007:9
  46:     0x7f3b46370dc5 - std::sys::unix::thread::Thread::new::thread_start::hfad7ee6626cdd5ae
                               at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7f3b4608f18a - start_thread
                               at ./nptl/pthread_create.c:444:8
  48:     0x7f3b4611dbd0 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  49:                0x0 - <unknown>


rustc version: 1.73.0-nightly (32303b219 2023-07-29)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_mod_item_types] checking item types in top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

### LINKED ISSUE #114579: Crate cloud-storage does not compile on nightly-2023-07-27
<!--
Thank you for filing a regression report! 🐛 A regression is something that changed between versions of Rust but was not supposed to.

Please provide a short summary of the regression, along with any information you feel is relevant to replicate it.
-->
Got compilation error when bumping rust for external crate `cloud-storage` for version indicated below. (https://github.com/ThouCheese/cloud-storage-rs)

### Code

I tried this code:

```rust
⋊> ~/g/d/cloud-storage-rs on master ◦ rustup default nightly-2023-07-26-x86_64-unknown-linux-gnu                                                                                                                                                                          13:51:22
info: using existing install for 'nightly-2023-07-26-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2023-07-26-x86_64-unknown-linux-gnu'

  nightly-2023-07-26-x86_64-unknown-linux-gnu unchanged - rustc 1.73.0-nightly (864bdf784 2023-07-25)

⋊> ~/g/d/cloud-storage-rs on master ◦ rustc --version                                                                                                                                                                                                                     13:51:23
rustc 1.73.0-nightly (864bdf784 2023-07-25)
⋊> ~/g/d/cloud-storage-rs on master ◦ cargo clippy                                                                                                                                                                                                                        13:51:28
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
⋊> ~/g/d/cloud-storage-rs on master ◦ rustup default nightly-2023-07-27-x86_64-unknown-linux-gnu                                                                                                                                                                          13:51:34
info: using existing install for 'nightly-2023-07-27-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2023-07-27-x86_64-unknown-linux-gnu'

  nightly-2023-07-27-x86_64-unknown-linux-gnu unchanged - rustc 1.73.0-nightly (0d95f9132 2023-07-26)

⋊> ~/g/d/cloud-storage-rs on master ◦ cargo clippy                                                                                                                                                                                                                        13:54:54
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
    Checking once_cell v1.18.0
   Compiling vcpkg v0.2.15
   Compiling pkg-config v0.3.27
    Checking cfg-if v1.0.0
    Checking pin-project-lite v0.2.11
   Compiling futures-core v0.3.28
    Checking bytes v1.4.0
    Checking itoa v1.0.9
   Compiling serde v1.0.183
   Compiling tokio v1.29.1
   Compiling num-traits v0.2.16
   Compiling serde_derive v1.0.183
   Compiling futures-task v0.3.28
   Compiling indexmap v1.9.3
   Compiling quote v1.0.32
    Checking mio v0.8.8
    Checking socket2 v0.4.9
   Compiling cc v1.0.82
   Compiling syn v2.0.28
   Compiling slab v0.4.8
    Checking tracing-core v0.1.31
   Compiling futures-util v0.3.28
   Compiling openssl v0.10.56
    Checking foreign-types-shared v0.1.1
    Checking fnv v1.0.7
    Checking http v0.2.9
    Checking foreign-types v0.3.2
   Compiling num-integer v0.1.45
    Checking tracing v0.1.37
    Checking futures-sink v0.3.28
   Compiling futures-channel v0.3.28
    Checking hashbrown v0.12.3
   Compiling native-tls v0.2.11
    Checking bitflags v1.3.2
    Checking tinyvec_macros v0.1.1
   Compiling httparse v1.8.0
    Checking pin-utils v0.1.0
    Checking tinyvec v1.6.0
   Compiling num-bigint v0.2.6
    Checking percent-encoding v2.3.0
   Compiling serde_json v1.0.104
    Checking openssl-probe v0.1.5
    Checking try-lock v0.2.4
    Checking ryu v1.0.15
    Checking log v0.4.19
    Checking regex-syntax v0.7.4
    Checking unicode-normalization v0.1.22
    Checking want v0.3.1
   Compiling openssl-sys v0.9.91
   Compiling ring v0.16.20
    Checking form_urlencoded v1.2.0
    Checking http-body v0.4.5
    Checking time v0.1.45
    Checking unicode-bidi v0.3.13
    Checking iana-time-zone v0.1.57
    Checking tower-service v0.3.2
    Checking httpdate v1.0.2
    Checking regex-automata v0.3.6
    Checking chrono v0.4.26
    Checking idna v0.4.0
    Checking base64 v0.13.1
    Checking untrusted v0.7.1
   Compiling async-trait v0.1.72
    Checking spin v0.5.2
    Checking url v2.4.0
    Checking serde_urlencoded v0.7.1
    Checking encoding_rs v0.8.32
    Checking base64 v0.21.2
    Checking base64 v0.12.3
    Checking mime v0.3.17
    Checking ipnet v2.8.0
    Checking lazy_static v1.4.0
    Checking simple_asn1 v0.4.1
    Checking dotenv v0.15.0
    Checking regex v1.9.3
    Checking hex v0.4.3
    Checking pem v0.8.3
    Checking jsonwebtoken v7.2.0
   Compiling tokio-macros v2.1.0
   Compiling openssl-macros v0.1.1
    Checking tokio-util v0.7.8
    Checking tokio-native-tls v0.3.1
    Checking h2 v0.3.20
    Checking hyper v0.14.27
    Checking hyper-tls v0.5.0
    Checking reqwest v0.11.18
    Checking cloud-storage v0.11.1 (/home/mikael/gitrepos/dev/cloud-storage-rs)
error: concrete type differs from previous defining opaque type use
   --> src/client/object.rs:325:24
    |
325 |     ) -> crate::Result<impl Stream<Item = crate::Result<u8>> + Unpin> {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                        |
    |                        expected `resources::object::SizedByteStream<futures_util::stream::TryFlatten<futures_util::stream::Map<impl futures_util::Stream<Item = std::result::Result<bytes::Bytes, reqwest::Error>>, [closure@src/client/object.rs:344:18: 344:25]>>>`, got `resources::object::SizedByteStream<futures_util::stream::TryFlatten<futures_util::stream::Map<impl futures_util::Stream<Item = std::result::Result<bytes::Bytes, reqwest::Error>>, [closure@src/client/object.rs:344:18: 344:25]>>>`
    |                        this expression supplies two conflicting concrete types for the same opaque type

error: could not compile `cloud-storage` (lib) due to previous error
```

I expected to see this happen: Should compile on nightly 2023-07-27 toolchain.

Instead, this happened: Did not compile on nightly 2023-07-27 toolchain.

### Version it worked on

<!--
Provide the most recent version this worked on, for example:

It most recently worked on: Rust 1.47
-->

It most recently worked on: Compiles on nightly 2023-07-26 toolchain.

### Version with regression

<!--
Provide the version you are using that has the regression.
-->

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (0d95f9132 2023-07-26)
binary: rustc
commit-hash: 0d95f9132909ae7c5f2456748d0ffd1c3ba4a8e8
commit-date: 2023-07-26
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

<!--
Did the compiler crash? If so, please provide a backtrace.
-->

### Backtrace
<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

<!--
If you know when this regression occurred, please add a line like below, replacing `{channel}` with one of stable, beta, or nightly.

@rustbot modify labels: +regression-from-stable-to-{channel} -regression-untriaged
-->

### LINKED ISSUE #114597: New compilation error on nightly with RPIT.
I tried this code:

https://cs.opensource.google/fuchsia/fuchsia/+/main:src/connectivity/network/netcfg/src/lib.rs;l=1762;drc=4a7d2eb6793e61c0021f8dd7dab35804590d36b6 
The function beginning with the signature:
```
async fn create_device_stream(
        &self,
    ) -> Result<
        impl futures::Stream<Item = Result<devices::NetworkDeviceInstance, anyhow::Error>>,
        anyhow::Error,
    > { ... }
```

I expected to see this happen: Compiles successfully, as it did on previous releases.

Instead, this happened:
```
error: concrete type differs from previous defining opaque type use
    --> ../../src/connectivity/network/netcfg/src/lib.rs:1765:9
     |
1765 |         impl futures::Stream<Item = Result<devices::NetworkDeviceInstance, anyhow::Error>>,
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |         |
     |         expected `TryFlattenUnordered<futures::stream::Fuse<TryFilterMap<futures::stream::ErrInto<Watcher, anyhow::Error>, [async block@../../src/connectivity/network/netcfg/src/lib.rs:1782:17: 1843:18], [closure@../../src/connectivity/network/netcfg/src/lib.rs:1780:29: 1780:82]>>>`, got `TryFlattenUnordered<futures::stream::Fuse<TryFilterMap<futures::stream::ErrInto<Watcher, anyhow::Error>, [async block@../../src/connectivity/network/netcfg/src/lib.rs:1782:17: 1843:18], [closure@../../src/connectivity/network/netcfg/src/lib.rs:1780:29: 1780:82]>>>`
     |         this expression supplies two conflicting concrete types for the same opaque type
error: aborting due to previous error
```

Recompiling with `-Zverbose` outputs:
```
error: concrete type differs from previous defining opaque type use
    --> ../../src/connectivity/network/netcfg/src/lib.rs:1765:9
     |
1765 |         impl futures::Stream<Item = Result<devices::NetworkDeviceInstance, anyhow::Error>>,
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |         |
     |         expected `TryFlattenUnordered<futures::stream::Fuse<TryFilterMap<futures::stream::ErrInto<Watcher, anyhow::Error>, [static NetCfg<ReEarlyBound(DefId(0:3068 ~ netcfg[7715]::{impl#13}::create_device_stream::{opaque#0}::'a), 2, 'a)>::create_device_stream::{closure#0}::{closure#2}::{closure#0} upvar_tys=(fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy) for<Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None))> {ResumeTy, fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(None) }) InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon(None) }) PathBuf, Opaque(DefId(0:2630 ~ netcfg[7715]::devices::{impl#4}::get_instance_stream::{opaque#0}), [ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(0), BoundRegion { var: 3, kind: BrAnon(None) })]), ()}], [NetCfg<ReEarlyBound(DefId(0:3068 ~ netcfg[7715]::{impl#13}::create_device_stream::{opaque#0}::'a), 2, 'a)>::create_device_stream::{closure#0}::{closure#2} closure_kind_ty=i16 closure_sig_as_fn_ptr_ty=extern "rust-call" fn((WatchMessage,)) -> [static NetCfg<ReEarlyBound(DefId(0:3068 ~ netcfg[7715]::{impl#13}::create_device_stream::{opaque#0}::'a), 2, 'a)>::create_device_stream::{closure#0}::{closure#2}::{closure#0} upvar_tys=(fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy) for<Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None))> {ResumeTy, fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(None) }) InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon(None) }) PathBuf, Opaque(DefId(0:2630 ~ netcfg[7715]::devices::{impl#4}::get_instance_stream::{opaque#0}), [ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(0), BoundRegion { var: 3, kind: BrAnon(None) })]), ()}] upvar_tys=(InstallerProxy)]>>>`, got `TryFlattenUnordered<futures::stream::Fuse<TryFilterMap<futures::stream::ErrInto<Watcher, anyhow::Error>, [static NetCfg<ReEarlyBound(DefId(0:626 ~ netcfg[7715]::{impl#13}::'a), 0, 'a)>::create_device_stream::{closure#0}::{closure#2}::{closure#0} upvar_tys=(fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy) for<Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None))> {ResumeTy, fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(None) }) InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon(None) }) PathBuf, Opaque(DefId(0:2630 ~ netcfg[7715]::devices::{impl#4}::get_instance_stream::{opaque#0}), [ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(0), BoundRegion { var: 3, kind: BrAnon(None) })]), ()}], [NetCfg<ReEarlyBound(DefId(0:626 ~ netcfg[7715]::{impl#13}::'a), 0, 'a)>::create_device_stream::{closure#0}::{closure#2} closure_kind_ty=i16 closure_sig_as_fn_ptr_ty=extern "rust-call" fn((WatchMessage,)) -> [static NetCfg<ReEarlyBound(DefId(0:626 ~ netcfg[7715]::{impl#13}::'a), 0, 'a)>::create_device_stream::{closure#0}::{closure#2}::{closure#0} upvar_tys=(fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy) for<Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None)), Region(BrAnon(None))> {ResumeTy, fuchsia_fs::directory::WatchEvent, PathBuf, InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrAnon(None) }) InstallerProxy, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrAnon(None) }) PathBuf, Opaque(DefId(0:2630 ~ netcfg[7715]::devices::{impl#4}::get_instance_stream::{opaque#0}), [ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(0), BoundRegion { var: 3, kind: BrAnon(None) })]), ()}] upvar_tys=(InstallerProxy)]>>>`
     |         this expression supplies two conflicting concrete types for the same opaque type

error: aborting due to previous error
```

Which when diffed, shows a change only from instances of
`NetCfg<ReEarlyBound(DefId(0:3068 ~ netcfg[7715]::{impl#13}::create_device_stream::{opaque#0}::'a), 2, 'a)>` to
`NetCfg<ReEarlyBound(DefId(0:626 ~ netcfg[7715]::{impl#13}::'a), 0, 'a)>`.

### Meta

Error output is from rustc commit 139b49b99523c43219b39079aa8fb2e084c52a1c
Likely related to #113661, CC @oli-obk @lcnr

### LINKED ISSUE #114601: RPITITs don't inherit outlives bounds after >1 layer of nesting
I tried this code:

```rust
#![feature(return_position_impl_trait_in_trait)]

trait Foo {
    fn early<'a, T: 'a>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;

    fn late<'a, T>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;
}
```

I expected to see it compile.

Instead, this happened: 

```
error[E0309]: the parameter type `T` may not live long enough
 --> src/lib.rs:4:64
  |
4 |     fn early<'a, T: 'a>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;
  |                                                                ^^^^^^^^^^^ ...so that the reference type `&'a T` does not outlive the data it points at
  |
help: consider adding an explicit lifetime bound...
  |
4 |     fn early<'a, T: 'a + 'a>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;
  |                        ++++

error[E0309]: the parameter type `T` may not live long enough
 --> src/lib.rs:6:59
  |
6 |     fn late<'a, T>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;
  |                                                           ^^^^^^^^^^^ ...so that the reference type `&'a T` does not outlive the data it points at
  |
help: consider adding an explicit lifetime bound...
  |
6 |     fn late<'a, T: 'a>(x: &'a T) -> impl Iterator<Item = impl Into<&'a T>>;
  |                  ++++
```

---

#112682 didn't install bidirectional outlives bounds 100% correctly when the lifetimes are being inherited past one layer of `impl Trait`.

### PR DESCRIPTION
**Pull request by compiler-errors**
Use the [`lifetime_mapping`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/struct.OpaqueTy.html#structfield.lifetime_mapping) to map an RPIT's captured lifetimes back to the early- or late-bound lifetimes from its parent function. We may be going thru several layers of mapping, since opaques can be nested, so we introduce `TyCtxt::map_rpit_lifetime_to_fn_lifetime` to loop through several opaques worth of mapping, and handle turning it into a `ty::Region` as well.

We can then use this instead of the identity substs for RPITs in `check_opaque_meets_bounds` to address #114285.

We can then also use `map_rpit_lifetime_to_fn_lifetime` to properly install bidirectional-outlives predicates for both RPITs and RPITITs. This addresses #114601.

I based this on #114574, but I don't actually know how much of that PR we still need, so some code may be redundant now... :shrug: 

---

Fixes #114597
Fixes #114579
Fixes #114285

Also fixes #114601, since it turns out we had other bugs with RPITITs and their duplicated lifetime params :sweat_smile:.

Supersedes #114574

r? @oli-obk

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/collect/predicates_of.rs [hunk 1]
```diff
@@ -340,7 +340,7 @@ fn gather_explicit_predicates_of(tcx: TyCtxt<'_>, def_id: LocalDefId) -> ty::Gen
         };
         debug!(?lifetimes);
 
-        compute_bidirectional_outlives_predicates(tcx, &generics.params, &mut predicates);
+        compute_bidirectional_outlives_predicates(tcx, &generics.params, &mut vec![]);
```
Comment (oli-obk) [inline compiler/rustc_hir_analysis/src/collect/predicates_of.rs]: uh, please add a comment as to why it's ok that we're dropping these bounds on the floor. Because afaict, modulo some checks, this function call is now a no-op.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs]: lol, no, I left that in due to testing.

it's fine because i don't actually think we actually USE these predicates anywhere (i'm pretty sure we never call predicates_of on an opaque??), but i'm just an idiot and forgot to put this back.

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/predicates_of.rs]: there 🤦 fixed
