### PR TITLE
fix universes in the NLL type tests

### LINKED ISSUE #98095: NLL: unsound verification of higher ranked outlives bounds
This code now passes under under NLL after #95565:  ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e4d68f7aec3814820e945ad4d0253a7c))
```rust
fn assert_static<T>() where for<'a> T: 'a, {}

// `test` passes without requiring `T: 'static`
fn test<T>() { assert_static::<T>(); }
```

`assert_static` should be able to infer that `T: 'static` because, in the language of Chalk, I believe the bound `for<'a> T: 'a` should be lowered to `forall<'a> { Outlives(T: 'a) :- WellFormed(T). }` and because the well-formedness of T is assumed to be true, we can instantiate `'a` to any lifetime including `'static`.

@rustbot label T-compiler T-types regression-from-stable-to-nightly C-bug

### PR DESCRIPTION
**Pull request by nikomatsakis**
In the NLL code, we were not accommodating universes in the
`type_test` logic.

Fixes #98095.

r? @compiler-errors 

This breaks some tests, however, so the purpose of this branch is more explanatory and perhaps to do a crater run.

### CODE REVIEW

**Comment by compiler-errors** [comment]
marking this as experimental since it probably shouldn't be merged, since it breaks existing UI tests

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 1]
```diff
@@ -1278,6 +1278,18 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+                "eval_outlives: sub universe `{sub_region_scc:?}` is not nameable \
+                by super `{sup_region_scc:?}`, promoting to static",
+            );
+
+            return self.eval_outlives(sup_region, self.universal_regions.fr_static);
+        }
+
         // Both the `sub_region` and `sup_region` consist of the union
         // of some number of universal regions (along with the union
         // of various points in the CFG; ignore those points for
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:1295]: I'm curious if the logic below (`let universal_outlives = ...`) is necessary due to the added logic above. I don't know enough about borrowck to make a judgement.

**Comment by klensy** [comment]
This touches Cargo.lock, so errors will remain.

File: src/test/ui/regions/forall-wf-ref-reflexive.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
+// Test that we consider `for<'a> &'a T: 'a` to be sufficient to prove
+// that `for<'a> &'a T: 'a`.
+//
+// FIXME. Except we don't!
```
Comment (jackh726) [inline src/test/ui/regions/forall-wf-ref-reflexive.rs:4]: known-bug?

File: compiler/rustc_infer/src/infer/outlives/verify.rs [hunk 3]
```diff
@@ -82,27 +83,39 @@ impl<'cx, 'tcx> VerifyBoundCx<'cx, 'tcx> {
         debug!("param_bound(param_ty={:?})", param_ty);
 
         // Start with anything like `T: 'a` we can scrape from the
-        // environment
-        let param_bounds = self
-            .declared_generic_bounds_from_env(GenericKind::Param(param_ty))
-            .into_iter()
-            .map(|outlives| outlives.1);
+        // environment. If the environment contains something like
+        // `for<'a> T: 'a`, then we know that `T` outlives everything.
```
Comment (jackh726) [inline compiler/rustc_infer/src/infer/outlives/verify.rs:87]: So this is the type of thing that worries me for forward-compatibility. If we eventually mean that `'a` to only mean lifetimes where T is WF, then `'a` doesn't outlive *everything*, necessarily.

(I'm just reading comments for now, not code)

Comment (aliemjay) [reply compiler/rustc_infer/src/infer/outlives/verify.rs:87]: This code applies to `ParamTy`s only and they're assumed to be WF unconditionally, so i see no problem here.

Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/outlives/verify.rs:87]: I don't think that's a problem. This only occurs when there is a where-clause in the environment that says `for<'a> T: 'a`. That will always mean *everything*. The situation you're talking about is different -- e.g., `for<'a> <T as Foo<'a>>::Item: 'b`.

File: src/test/ui/regions/forall-wf-ref-reflexive.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/regions/forall-wf-ref-reflexive.rs:4]: I believe so, certainly a pre-existing one. This feels like an implied bounds situation to me. We ought to be able to know that `for<'a> &'a T: 'a` is really `for<'a> if (WF(&'a T)) { &'a T: 'a }`, and -- in that case -- we would be succesful here.

File: compiler/rustc_borrowck/src/region_infer/mod.rs (hunk 1 above)
Comment (nikomatsakis) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:1359]: I believe it is still relevant. I think that the code below is meant to deal with "top-level" generics declared on the function, where we do have finer-grained outlives data.

**Comment by compiler-errors** [comment]
@rust-timer queue

**Comment by compiler-errors** [comment]
we would like to get this checked ASAP, preferably before next week so we can determine whether this can go into beta. Therefore bumping the priority.

@craterbot check p=5

File: compiler/rustc_infer/src/infer/outlives/verify.rs [hunk 4]
```diff
@@ -82,27 +83,39 @@ impl<'cx, 'tcx> VerifyBoundCx<'cx, 'tcx> {
...
+        let mut param_bounds = vec![];
+        for declared_bound in declared_bounds_from_env {
+            let bound_region = declared_bound.map_bound(|outlives| outlives.1);
+            if let Some(region) = bound_region.no_bound_vars() {
+                // This is `T: 'a` for some free region `'a`.
+                param_bounds.push(VerifyBound::OutlivedBy(region));
+            } else {
+                // This is `for<'a> T: 'a`. This means that `T` outlives everything! All done here.
+                return VerifyBound::AllBounds(vec![]);
+            }
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/outlives/verify.rs:98]: I wonder if it's better to dicharge `for<'a> T: 'a` as `T: 'static` earlier when elaborating implied bounds.

Currently `for<'a> (T,): 'a` doesn't imply itself, which is surprising since we now allow more complex projection bounds to imply themselve `for<'a> <&'a () as Tr<'a>>::Assoc: 'a`.

File: compiler/rustc_infer/src/infer/outlives/verify.rs [hunk 5]
```diff
@@ -238,7 +255,7 @@ impl<'cx, 'tcx> VerifyBoundCx<'cx, 'tcx> {
         // like `T` and `T::Item`. It may not work as well for things
         // like `<T as Foo<'a>>::Item`.
         let c_b = self.param_env.caller_bounds();
-        let param_bounds = self.collect_outlives_from_predicate_list(&compare_ty, c_b.into_iter());
+        let param_bounds = self.collect_outlives_from_predicate_list(erased_ty, c_b.into_iter());
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/outlives/verify.rs:258]: nit: update the comment above;  we no longer compare using equality.

File: compiler/rustc_infer/src/infer/region_constraints/mod.rs [hunk 6]
```diff
@@ -224,7 +224,9 @@ pub enum VerifyBound<'tcx> {
     ///
     /// meaning, if the subject G is equal to `<T as Trait<'a>>::Item`
     /// (after inference), and `'a: min`, then `G: min`.
-    IfEq(Ty<'tcx>, Box<VerifyBound<'tcx>>),
+    IfEq(Ty<'tcx>, Region<'tcx>),
+
+    IfEqBound(ty::Binder<'tcx, VerifyIfEq<'tcx>>),
```
Comment (aliemjay) [inline compiler/rustc_infer/src/infer/region_constraints/mod.rs:229]: nit: rename IfEqBound to IfEq and refer to the docs of `VerifyIfEq`.

**Review by aliemjay — APPROVED** [review]
Looks good :+1:
Thanks!

File: src/test/ui/regions/forall-wf-ref-reflexive.rs (hunk 2 above)
Comment (compiler-errors) [reply src/test/ui/regions/forall-wf-ref-reflexive.rs:4]: I think @jackh726 means using the `// known-bug` attribute

File: compiler/rustc_infer/src/infer/outlives/verify.rs (hunk 4 above)
Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/outlives/verify.rs:98]: My expectation is that we would make `for<'a> T: 'a` an implied bound of `for<'a> (T,): 'a`, just as we currently make `T: 'a` an elaboration of `(T,): 'a`.  I guess we skip that for higher-ranked things?

Relevant code:

https://github.com/rust-lang/rust/blob/6499c5e7fc173a3f55b7a3bd1e6a50e9edef782d/compiler/rustc_infer/src/traits/util.rs#L210-L216

**Comment by aliemjay** [comment]
I'm investigating the crater report now.

**Comment by aliemjay** [comment]
I see only 3 regression. The others looks spurious and many can be confirmed as such when comparing to previous crater runs.

`collectivity`:
```rust
#![feature(generic_associated_types)]

pub trait Get<K> {
  /// The type of the value returned by `get`.
  type Value<'a>
  where
    Self: 'a;
}

fn multiply_at<T>(data: &T)
where
    T: for<'a> Get<usize, Value<'a> = &'a usize>,
{
  None::<T::Value<'_>>.map(|_| {});
}

fn main() {}
```

`snocat`:
```rust
pub fn negotiate<'stream, S>(link: S)
where
    S: 'stream,
    for<'a> &'a S: 'a,
{
    fn lives_as_long<'a, T: 'a>(_: T) {}
    lives_as_long::<'stream, _>(|| {
        let _l = link;
    })
}

fn main() {}
```

`vimwiki_core`:
```rust
pub trait ElementLike {}

pub struct Located<T> where T: ElementLike {
    inner: T,
}

pub struct BlockElement<'a>(&'a str);

impl ElementLike for BlockElement<'_> {}


pub struct Page<'a> {
    /// Comprised of the elements within a page
    pub elements: Vec<Located<BlockElement<'a>>>,
}

impl<'a, __IdxT> ::core::ops::Index<__IdxT> for Page<'a> where
    Vec<Located<BlockElement<'a>>>: ::core::ops::Index<__IdxT>
{
    type Output =
        <Vec<Located<BlockElement<'a>>> as
        ::core::ops::Index<__IdxT>>::Output;

    #[inline]
    fn index(&self, idx: __IdxT) -> &Self::Output {
        <Vec<Located<BlockElement<'a>>> as
                ::core::ops::Index<__IdxT>>::index(&self.elements, idx)
    }
}

fn main() {}
```

I'll try to investigate them later.

File: compiler/rustc_infer/src/infer/outlives/test_type_match.rs [hunk 7]
```diff
@@ -0,0 +1,203 @@
...
+            Ok(pattern)
+        } else {
+            self.no_match()
+        }
+    }
+
+    #[instrument(skip(self), level = "debug")]
+    fn tys(&mut self, pattern: Ty<'tcx>, value: Ty<'tcx>) -> RelateResult<'tcx, Ty<'tcx>> {
+        if pattern == value {
+            return Ok(pattern);
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/outlives/test_type_match.rs:170]:
```suggestion
            Ok(pattern)
```

File: compiler/rustc_infer/src/infer/outlives/test_type_match.rs [hunk 8]
```diff
@@ -0,0 +1,203 @@
...
+        match m.map.get(&br) {
+            Some(&r) => Some(r),
+            None => {
+                // If there is no mapping, then this region is unconstrained.
+                // In that case, we escalate to `'static`.
+                Some(tcx.lifetimes.re_static)
+            }
+        }
+    } else {
+        // The region does not contain any inference variables.
```
Comment (oli-obk) [inline compiler/rustc_infer/src/infer/outlives/test_type_match.rs:60]: I don't understand this comment. This whole scheme is about bound lifetimes, why do inference variables play into it? Is this basically the path for `for<'a> T: 'b` where `'b` is a regular generic param? Could be helpful to exhaustively match on the `RegionKind`s here and explain how each variant can end up here.

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 9]
```diff
@@ -1185,33 +1211,71 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
         if generic_ty_normalized == test_ty_normalized {
-            self.eval_verify_bound(tcx, body, generic_ty, lower_bound, verify_bound)
+            let verify_bound_vid = self.to_region_vid(verify_bound);
+            self.eval_outlives(verify_bound_vid, lower_bound)
         } else {
             false
         }
     }
 
+    fn eval_if_eq_bound(
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/region_infer/mod.rs:1255]: Is the separation of bound/not bound solely a performance thing? Could we merge them and make the decision on whether the binder binds nothing?

Comment (nikomatsakis) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:1255]: @oli-obk I'm removing the "bound" variant, I thought I pushed that but I guess not.

Comment (nikomatsakis) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:1255]: er, removing the *not* bound variant. it's dead code in this PR anyway.

File: compiler/rustc_infer/src/infer/outlives/test_type_match.rs (hunk 8 above)
Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/outlives/test_type_match.rs:60]: The bound variables are inference variables -- a `for<'a> T: 'a` bound, when applied to solve a particular constraint `T: 'b`, means that `'a` is an inference variable that we can infer to be `'b`.

**Review by aliemjay — CHANGES_REQUESTED** [review]
The regression of `vimwiki_core` is fixed by the patch below.

The other regressions are strongly rlated to the bug of `for<'a> &'a T: 'a` doesn't imply itself and how we borrow check closures in NLL.  They can be reduced to:
```rust
pub fn negotiate<S>(link: S)
where
    for<'a> &'a S: 'a,
{
    || { 
        let _x = link;
    };
}
```
```rust
#![feature(generic_associated_types)]

pub trait Get {
  type Value<'a> where Self: 'a;
}

fn multiply_at<T>(x: T)
where
    for<'a> T: Get<Value<'a> = ()>,
{
    || {
        let _x = x;
    };
}
```

File: compiler/rustc_borrowck/src/region_infer/mod.rs [hunk 10]
```diff
@@ -1300,10 +1379,18 @@ impl<'tcx> RegionInferenceContext<'tcx> {
...
+            debug!(
+                "eval_outlives: returning true because super is universal and hence contains all points"
+            );
             return true;
         }
 
-        self.scc_values.contains_points(sup_region_scc, sub_region_scc)
+        let result = self.scc_values.contains_points(sup_region_scc, sub_region_scc);
+        debug!(
+            "eval_outlives: returning {} because of comparison between points in sup/sub",
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply compiler/rustc_borrowck/src/region_infer/mod.rs:1390]:
```suggestion
            "returning {} because of comparison between points in sup/sub",
```

File: src/test/ui/regions/forall-wf-ref-reflexive.rs (hunk 2 above)
Comment (nikomatsakis) [reply src/test/ui/regions/forall-wf-ref-reflexive.rs:4]: Ah, cool. Citing which bug?

File: compiler/rustc_infer/src/infer/outlives/test_type_match.rs (hunk 8 above)
Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/outlives/test_type_match.rs:60]: I pushed an improved comment that hopefully clarifies things.

File: compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs [hunk 11]
```diff
@@ -818,9 +822,24 @@ impl<'cx, 'tcx> LexicalResolver<'cx, 'tcx> {
...
                 (var_values.normalize(self.region_rels.tcx, *k) == generic_ty)
-                    && self.bound_is_met(b, var_values, generic_ty, min)
+                    && self.bound_is_met(&VerifyBound::OutlivedBy(*r), var_values, generic_ty, min)
+            }
+
+            VerifyBound::IfEqBound(verify_if_eq_b) => {
+                match test_type_match::extract_verify_if_eq_bound(
+                    self.tcx(),
+                    self.param_env,
+                    verify_if_eq_b,
```
[the remark this answers is not in the document]
Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs]: thanks, I added a regression test and pushed this fix

File: compiler/rustc_infer/src/infer/outlives/verify.rs (hunk 5 above)
Comment (nikomatsakis) [reply compiler/rustc_infer/src/infer/outlives/verify.rs:258]: done

**Comment by jackh726** [comment]
@bors r+ p=5 rollup=never

We want this in before beta cut, since this fixes a stable-to-nightly unsound regression, caused by NLL stabilization.

There are two known regressions here, but one requires GATs (unstable) and the other has an obvious fix (remove the `'a` bound). Given this, it makes sense to land this. We might be able to fix and backport a fix for those; but if not, it's not the end of the world.

I think the code here and adjacent would be a good candidate for a types team deep dive; this feels a bit ad-hoc to me, even if correct (but I have little personal context to the overall design of this logic).

**Comment by oli-obk** [comment]
In diesel-check-full, the main regression is

```
205,739,874  ???:<rustc_middle::ty::context::CtxtInterners>::intern_ty
190,507,805  ???:<alloc::vec::Vec<rustc_middle::ty::sty::Binder<rustc_middle::ty::OutlivesPredicate<rustc_middle::ty::Ty, rustc_middle::ty::sty::Region>>> as alloc::vec::spec_from_iter::SpecFromIter<rustc_middle::ty::sty::Binder<rustc_middle::ty::OutlivesPredicate<rustc_middle::ty::Ty, rustc_middle::ty::sty::Region>>, core::iter::adapters::inspect::Inspect<core::iter::adapters::chain::Chain<core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Predicate>>, <rustc_infer::infer::outlives::verify::VerifyBoundCx>::collect_outlives_from_predicate_list<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Predicate>>>::{closure
```

the second one is entirely due to the logic in `can_match_erased_ty`. There may be some possible gains if we skip the binder first and then erase, but it generally won't help much. Ideally we'd just relate the types while ignoring lifetimes.

**Comment by rylev** [comment]
@oli-obk should we capture this in an issue? I think it's pretty likely that this regression will go unaddressed if we leave it in the comment here.
