### PR TITLE
Fix parsing of erroneously placed semicolons

### LINKED ISSUE #124935: Wrong diagnostic: `main` function not found in crate
Tested on nightly and stable.
```rs
;
fn main() { }
```
```
error: expected item, found `;`
 --> src/main.rs:1:1
  |
1 | ;
  | ^ help: remove this semicolon

error[E0601]: `main` function not found in crate `tests`
 --> src/main.rs:1:2
  |
1 | ;
  |  ^ consider adding a `main` function to `src/main.rs`

For more information about this error, try `rustc --explain E0601`.
error: could not compile `tests` (bin "tests") due to 2 previous errors
```
The second diagnostic is strange.

### PR DESCRIPTION
**Pull request by oriongonza**
This closes https://github.com/rust-lang/rust/issues/124935, is a continuation of https://github.com/rust-lang/rust/pull/125245 after rebasing https://github.com/rust-lang/rust/pull/125117.

Thanks @gurry for your code and sorry for making it confusing :P

r? fmease

### CODE REVIEW

File: compiler/rustc_parse/src/parser/item.rs [hunk 1]
```diff
@@ -59,10 +59,18 @@ impl<'a> Parser<'a> {
...
+        // There shouldn't be any semicolons before or afer items.
+        // `parse_item` consumes the appropriate semicolons so any leftover is an error.
+        let mut last = None;
+        while let Some(item) = {
+            self.maybe_consume_incorrect_semicolon(last);
+            self.parse_item(ForceCollect::No)?
+        } {
             items.push(item);
+            last = items.last().map(|x| &**x);
         }
```
Comment (gurry) [inline compiler/rustc_parse/src/parser/item.rs:72]: Will this work when you have multiple consecutive incorrect semicolons e.g.:
```rust
;
;
fn main() { }
```

I think you should call `maybe-consume_incorrect_semicolon` in a loop and consume as many of them as possible before calling `parse_item`

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -59,10 +59,18 @@ impl<'a> Parser<'a> {
...
-        while let Some(item) = self.parse_item(ForceCollect::No)? {
-            self.maybe_consume_incorrect_semicolon(Some(&item));
+
+        // There shouldn't be any semicolons before or afer items.
+        // `parse_item` consumes the appropriate semicolons so any leftover is an error.
+        let mut last = None;
+        while let Some(item) = {
+            self.maybe_consume_incorrect_semicolon(last);
+            self.parse_item(ForceCollect::No)?
+        } {
```
Comment (gurry) [inline compiler/rustc_parse/src/parser/item.rs:69]: Using a block in a `while` loop's predicate is not a style I have seen used in the compiler code. Maybe move those statements into the loop body and use a `loop` instead instead of a `while`?

File: compiler/rustc_parse/src/parser/item.rs [hunk 3]
```diff
@@ -59,10 +59,18 @@ impl<'a> Parser<'a> {
...
             items.push(item);
+            last = items.last().map(|x| &**x);
         }
+        self.maybe_consume_incorrect_semicolon(last);
```
Comment (gurry) [inline compiler/rustc_parse/src/parser/item.rs:73]: This may not be needed

**Comment by gurry** [comment]
> Thanks @gurry for your code and sorry for making it confusing :P

Don't worry and welome to rustc :)

File: compiler/rustc_parse/src/parser/item.rs (hunk 1 above)
Comment (dev-ardi) [reply compiler/rustc_parse/src/parser/item.rs:72]: Good catch

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (dev-ardi) [reply compiler/rustc_parse/src/parser/item.rs:73]: It's needed to parse trailing semis:
```rs
fn main(){}
;
```

File: compiler/rustc_parse/src/parser/item.rs (hunk 2 above)
Comment (dev-ardi) [reply compiler/rustc_parse/src/parser/item.rs]: Okay, I agree that it can be a bit harder to follow. Done :)

File: compiler/rustc_parse/src/parser/item.rs (hunk 3 above)
Comment (gurry) [reply compiler/rustc_parse/src/parser/item.rs:75]: The preceding loop should take care of trailing semicolons as well. For this code:
```rust
fn main(){}
;
```
it should parse the item `main` in the first iteration and then iterate again and consume the semicolon.

File: compiler/rustc_parse/src/parser/item.rs [hunk 4]
```diff
@@ -59,10 +59,20 @@ impl<'a> Parser<'a> {
...
+        // There shouldn't be any semicolons before or afer items.
+        // `parse_item` consumes the appropriate semicolons so any leftover is an error.
+        let mut last = None;
+        loop {
+            while self.maybe_consume_incorrect_semicolon(last) {} // Eat all bad semicolons
+            let Some(item) = self.parse_item(ForceCollect::No)? else {
+                break;
+            };
             items.push(item);
+            last = items.last().map(|x| &**x);
```
Comment (gurry) [inline compiler/rustc_parse/src/parser/item.rs:72]: A ref on top of a deref seems redundant. Maybe replace `&**x` with just `*x`

**Review by gurry — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/item.rs [hunk 5]
```diff
@@ -59,10 +59,20 @@ impl<'a> Parser<'a> {
 
         let post_attr_lo = self.token.span;
         let mut items = ThinVec::new();
-        while let Some(item) = self.parse_item(ForceCollect::No)? {
-            self.maybe_consume_incorrect_semicolon(Some(&item));
+
+        // There shouldn't be any semicolons before or afer items.
```
Comment (gurry) [inline compiler/rustc_parse/src/parser/item.rs:63]:
```suggestion
        // There shouldn't be any stray semicolons before or afer items.
```

**Review by gurry — CHANGES_REQUESTED** [review]

File: compiler/rustc_parse/src/parser/item.rs (hunk 5 above)
Comment (fmease) [reply compiler/rustc_parse/src/parser/item.rs:63]: and *afer* → *after* :)

**Review by fmease — COMMENTED** [review]
plz squash

**Review by fmease — APPROVED** [review]

**Review by fmease — APPROVED** [review]
Thanks!
