### PR TITLE
const-eval: allow constants to refer to mutable/external memory, but reject such constants as patterns

### LINKED ISSUE #140653: Const-eval "undefined behavior" error in apparently entirely safe code
I tried this code:

```rust
static __CALLSITE: tracing::callsite::DefaultCallsite = {
    const META: tracing::Metadata<'static> = {
        tracing::Metadata::new(
            "my span",
            "tracing_test::a",
            tracing::Level::ERROR,
            Some("src/a.rs"),
            Some(35u32),
            Some("tracing_test::a"),
            tracing::field::FieldSet::new(
                &["message"],
                tracing::callsite::Identifier(&__CALLSITE),
            ),
            tracing::metadata::Kind::SPAN,
        )
    };
    tracing::callsite::DefaultCallsite::new(&META)
};
```

I expected to see this happen: Either it fails to compile due to a type error or it compiles successfully.

Instead, this happened: "it is undefined behavior to use this value"

Here's a self-contained reproducer:
```rust
use std::sync::atomic::*;

static FOO: AtomicU32 = AtomicU32::new(0);
const C: &'static AtomicU32 = &FOO;
```
yields
```
error[E0080]: it is undefined behavior to use this value
 --> src/lib.rs:4:1
  |
4 | const C: &'static AtomicU32 = &FOO;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value: encountered reference to mutable memory in `const`
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 8, align: 8) {
              ╾───────alloc1────────╼                         │ ╾──────╼
          }
```

I lost context on "constants referencing statics" so I am not sure right now whether this is just a poorly worded error message, or whether there's some static check that should have caught this earlier but for some reason did not.

Cc @rust-lang/wg-const-eval 

### Meta

Latest nightly

### PR DESCRIPTION
**Pull request by RalfJung**
Reference PR:

- https://github.com/rust-lang/reference/pull/1859

This fixes https://github.com/rust-lang/rust/issues/140653 by accepting code such as this:
```rust
static FOO: AtomicU32 = AtomicU32::new(0);
const C: &'static AtomicU32 = &FOO;
```
This can be written entirely in safe code, so there can't really be anything wrong with it.

We also accept the much more questionable following code, since it looks very similar to the interpreter:
```rust
static mut FOO2: u32 = 0;
const C2: &'static u32 = unsafe { &mut FOO2 };
```
Using this without causing UB is at least very hard (the details are unclear since it is related to how the aliasing model deals with the staging of const-eval vs runtime code).

If a constant like `C2` is used as a pattern, we emit an error:
```
error: constant BAD_PATTERN cannot be used as pattern
  --> $DIR/const_refs_to_static_fail.rs:30:9
   |
LL |         BAD_PATTERN => {},
   |         ^^^^^^^^^^^
   |
   = note: constants that reference mutable or external memory cannot be used as pattern
```
(If you somehow manage to build a pattern with constant `C`, you'd get the same error, but that should be impossible: we don't have a type that can be used in patterns and that has interior mutability.)

The same treatment is afforded for shared references to `extern static`, for the same reason: the const evaluation is entirely fine with it, we just can't build a pattern for it -- and when using interior mutability, this can be totally sound.

We do still not accept anything where there is an `&mut` in the final value of the const, as that should always require unsafe code and it's hard to imagine a sound use-case that would require this.

### CODE REVIEW

**Comment by RalfJung** [comment]
@rust-lang/lang nominating for FCP following prior discussion in https://github.com/rust-lang/rust/issues/140653.

File: src/tools/clippy/clippy_lints/src/non_copy_const.rs [hunk 1]
```diff
@@ -261,51 +261,22 @@ impl<'tcx> NonCopyConst<'tcx> {
...
-            cx.typing_env(),
-            ty::UnevaluatedConst::new(def_id, args),
-            DUMMY_SP,
-        );
+        let const_ = ty::UnevaluatedConst::new(def_id, args);
+        let result = cx.tcx.const_eval_resolve_for_typeck(cx.typing_env(), const_, DUMMY_SP);
         Self::is_value_unfrozen_raw(cx, result, ty)
     }
-
-    pub fn const_eval_resolve(
```
Comment (RalfJung) [inline src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: @rust-lang/clippy I could not figure out why clippy has its own version of this function, and there's no comment giving any hint. The easiest way to fix the build failure was to remove the function so I did that.

File: tests/ui/consts/miri_unleashed/mutable_references.rs [hunk 2]
```diff
@@ -73,10 +73,10 @@ static mut MUT_TO_READONLY: &mut i32 = unsafe { &mut *(&READONLY as *const _ as
 // # Check for consts pointing to mutable memory
 
 static mut MUTABLE: i32 = 42;
-const POINTS_TO_MUTABLE: &i32 = unsafe { &MUTABLE }; //~ ERROR undefined behavior
-//~| NOTE encountered reference to mutable memory
+const POINTS_TO_MUTABLE: &i32 = unsafe { &MUTABLE }; // OK, as long as it is not used as a pattern.
+
 static mut MUTABLE_REF: &mut i32 = &mut 42;
-const POINTS_TO_MUTABLE2: &i32 = unsafe { &*MUTABLE_REF };
+const POINTS_TO_MUTABLE2: &i32 = unsafe { &*MUTABLE_REF }; // FIXME why does this stil error?
```
Comment (RalfJung) [inline tests/ui/consts/miri_unleashed/mutable_references.rs:79]: I still need to look into this.

File: src/tools/clippy/clippy_lints/src/non_copy_const.rs (hunk 1 above)
Comment (flip1995) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: @Jarcho might know.

Comment (RalfJung) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: Hm, this does seem to change some of the tests. I have no clue why that is, apparently some detail of the old code was load-bearing. The total lack of comments in the code makes this rather painful to debug...

Comment (RalfJung) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: The entire logic of this lint seems off to me. Why is this using valtrees in the first place? That seems to be a misuse of the valtree APIs. I think what you really want here is to use a value visitor to walk the value of the const and search for `UnsafeCell`, similar to [this](https://github.com/rust-lang/miri/blob/e4ec1271b493b23f928417740f5bd6d47ff0ec9b/src/helpers.rs#L481). That will then also work with non-valtree-compatible constants.

Please consult with the stakeholders of an API before using it in creative ways in clippy. Long-term that saves a lot of maintenance work. :)

Comment (RalfJung) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: I think somehow previously clippy managed to convince the valtree evaluation machinery to evaluate generic consts without throwing `TooGeneric`. I have no idea why that worked, but it was never supposed to work -- constants must be monomorphic to be evaluated.  Furthermore, whenever it did encounter `TooGeneric`, clippy interprets that as an unfrozen value (when really it means "we have no clue at all") -- with a long comment for why that's the better choice. However, now that more `TooGeneric` errors appear (and as far as I can tell, those errors are correct), this is no longer the better choice, so I changed it. That means the lint fires *much* less than before (it never fires on generic consts any more, which affects the majority of testcases), but I don't think it makes sense to even attempt to lint on generic consts -- rustc is not designed for that, and trying to misuse its APIs is not long a long-term viable strategy.

@oli-obk maybe you have a better idea here.

Comment (RalfJung) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: > I want to talk to the bootstrap team during the all-hands what we can do in Clippy to finally improve this situation.

Great! Let me know if I can help
FWIW based on [your comment](https://github.com/rust-lang/rust/issues/78717#issuecomment-2633552248) I think a solution should be fairly simple, but I've been waiting for https://github.com/rust-lang/rust/pull/119899 before looking into it myself as it seems pointless to touch any of the staging part now if it's all going to change anyway... and I didn't want to create more conflicts for that PR.

> I think I remember now that the function in question here was added as patch work to "fix" something in the lint.

That is useful background, thanks! A comment in the code explaining that and linking to the issue this fixes would have been helpful.^^

**Comment by traviscross** [comment]
As discussed in https://github.com/rust-lang/rust/issues/140653#issuecomment-2860131843, this sounds right to me, and I proposed that we do it.

@rfcbot fcp merge

File: src/tools/clippy/clippy_lints/src/non_copy_const.rs (hunk 1 above)
Comment (flip1995) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: Samuel removed the test I was referring to in this comment in [rust-lang/rust-clippy#14788](https://github.com/rust-lang/rust-clippy/pull/14788). So we should be a tiny bit closer.

Comment (flip1995) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: Jason is working on a PR rust-lang/rust-clippy#13207 that refactors this lint and removes the `ValTree` API misuse. 

> I managed to get one of those cases to fire the lint again by more closely following the original code. No idea why that particular change made a difference for that case, or why all the other cases are still not firing.

So if this PR introduces some false negatives, I would say that isn't too bad.

Comment (RalfJung) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: Yeah, as-is the PR adds a bunch of false negatives. Though seems like I'll just have to wait until https://github.com/rust-lang/rust-clippy/pull/13207 syncs to this repo, drop my changes, and rebase.

Comment (flip1995) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: This PR missed the sync by 1 day. So the next one will be in just short of 2 weeks.. I can do an out-of-cycle sync if you want it sooner.

Comment (flip1995) [reply src/tools/clippy/clippy_lints/src/non_copy_const.rs:288]: Next sync is in exactly 10 days. So that (if nothing goes wrong) goes in first.

**Comment by tmandry** [comment]
@rfcbot concern whole team signoff

The proposal is to allow shared references to mutable memory in consts, but not to allow those consts to be used in patterns. This is a notable expansion and it is (to my knowledge) the first time we are not allowing a const to be used in a pattern, which constrains future decisions. I don't have a problem with it, and I think we probably should do it, but I would like the full team to know about it because it didn't have an RFC.

---

On a meta note, I keep having the feeling that this cluster of features is being "designed just in time". That is not to criticize anyone. Every decision we make seems reasonable and has good rationale, but it makes me nervous because I can't tell where we will ultimately end up as we go down this road. The path we are committing to here is something I'd ideally love to have considered in an RFC.

On the other hand, maybe this is working as intended? There are a lot of details to work out, and I don't know of anyone with a crystal ball who can foresee every implication. And if we did consider every implication it might overwhelm the lang team into indecision :).

I think we are far enough down this path that there's nothing to be done here, but it's something to think about.

**Comment by RalfJung** [comment]
> The proposal is to allow shared references to mutable memory in consts, but not to allow those consts to be used in patterns.

To be fully precise, this is about such shared references in the final value of a const. We already allowed such shared references to appear as temporaries within the computation of a const before.

> On the other hand, maybe this is working as intended? There are a lot of details to work out, and I don't know of anyone with a crystal ball who can foresee every implication. And if we did consider every implication it might overwhelm the lang team into indecision :).

That's pretty much how I see it. There are a whole bunch of things one could imagine doing, but it's rather unclear what the trade-offs are, and which ones are worth it. So instead of planning a grand architecture on the whiteboard and then putting it into reality all at once, we're discovering one step at a time what it is that users actually want or need.

**Comment by nikomatsakis** [comment]
@rfcbot fcp reviewed

This feels like it should work to me-- i'll leave a more extended comment with some thoughts.

**Comment by tmandry** [comment]
@rfcbot resolve whole team signoff

**Comment by nikomatsakis** [comment]
A few questions and/or comments for @RalfJung and @BoxyUwU — it continues to be true that every time I have to review a const issue, despite having talked over these things with you time and time again, I feel confused, somewhat like @tmandry said in their comment, about the "north star" we are working towards. I don't have a strong intuition for why one thing should work and not another.

What I have *somewhat* internalized is the idea of "valtree-able" values being a subset of all constants and the idea that const *generics* are only instantiable with a valtree-able value. I *think* that patterns are similarly limited, no? i.e., a valtree-able value can clearly be converted to a pattern. But I suppose that we can accommodate a wider set of constants in patterns by compiling them to use `==`, but I think we try to avoid doing that except for cases that would also be valtree-able? I remember a lot of doc reads on this topic but I'm not sure where we ultimately *landed*.

**Comment by RalfJung** [comment]
I don't have a north star for this so I cannot help with that part unfortunately. ;) My strategy has been, given a use case we do not support, to carve out the smallest reasonable extension that would allow the use case.

Regarding valtrees: currently, only valtree-able constants can be used in patterns. That simplifies things a lot in terms of implementation and reasoning so I would prefer to keep this property as long as we possibly can. Note that only a subset of valtree-able constants are accepted as const generics (e.g. all floats are excluded from const generics, but some floats are allowed in patterns).

**Comment by RalfJung** [comment]
@oli-obk FCP should finish fairly soon here, so this is ready for review. :)

@traviscross I guess this will also need a reference PR? Not sure when I'll get around to that.
I couldn't even find where the limitation "the final value of a const cannot refer to mutable memory" is documented, if at all. I did however find [this](https://doc.rust-lang.org/nightly/reference/const_eval.html#r-const-eval.const-expr.borrows), which has a small mistake (orthogonal to this PR): borrows in consts are also allowed to refer to `static` items and promoteds. (EDIT: put up a PR for that: https://github.com/rust-lang/reference/pull/1858)

**Comment by traviscross** [comment]
cc @ehuss

**Review by oli-obk — APPROVED** [review]
My preference would have been 3 commits

* error reporting pulled out of query
* stylistic refactoring of match with large arm
* actual changes

but since I already reviewed everything, let's land it as is

**Comment by RalfJung** [comment]
Thanks! I agree smaller commits are nicer in retrospect, but I discovered these things half-way through implementation so it'd have been a lot of work to disentangle them...

**Comment by ehuss** [comment]
> the final value of a const cannot refer to mutable memory

Maybe you are referring to [this](https://doc.rust-lang.org/nightly/reference/items/constant-items.html?highlight=constant#r-items.const.final-value-immutable)? That was added as part of [const_refs_to_statics](https://github.com/rust-lang/rust/issues/128183) (https://github.com/rust-lang/reference/pull/1610)

**Comment by RalfJung** [comment]
Ah, yes, that's it.  That should be just removed, and then instead we need something [here](https://doc.rust-lang.org/nightly/reference/patterns.html#grammar-PathPattern) about consts referencing mutable/extern statics.

**Comment by oli-obk** [comment]
> so it'd have been a lot of work to disentangle them...

Ah damn right I forgot to sell you jj at the all hands.

**Comment by RalfJung** [comment]
Reference PR: https://github.com/rust-lang/reference/pull/1859

**Comment by RalfJung** [comment]
@bors r-
I guess the reference PR has to land first?

File: tests/ui/consts/issue-17718-const-bad-values.rs [hunk 3]
```diff
@@ -7,8 +7,4 @@
 const C1: &'static mut [usize] = &mut [];
 //~^ ERROR: mutable references are not allowed
 
-static mut S: i32 = 3;
-const C2: &'static mut i32 = unsafe { &mut S };
-//~^ ERROR: reference to mutable memory
-
```
Comment (ehuss) [inline tests/ui/consts/issue-17718-const-bad-values.rs]: Why was this removed? It doesn't seem like its behavior was changed by this PR (it still generates the same E0080 error). Is it covered in some other test?

Comment (RalfJung) [reply tests/ui/consts/issue-17718-const-bad-values.rs]: Uh, I don't remember...
The error message does change, so it is unclear whether this even still tests the right thing. :shrug: But I can add the test back with the new error, sure.

**Comment by RalfJung** [comment]
@oli-obk based on @ehuss's questions in https://github.com/rust-lang/reference/pull/1859, I made the "borrow of non-transient" error more uniform (use a shared error for raw and ref borrows, and use the same wording for mutable and interior mutable borrows), and made them explicitly talk about lifetime extension, since we have to wait for that reference PR anyway. If you prefer, I can also split this into a separate PR.

File: tests/ui/consts/const-mut-refs/issue-76510.stderr [hunk 4]
```diff
@@ -1,4 +1,4 @@
-error[E0764]: mutable references are not allowed in the final value of constants
+error[E0764]: mutable borrows of lifetime-extended temporaries are not allowed in constants
```
Comment (RalfJung) [inline tests/ui/consts/const-mut-refs/issue-76510.stderr]: This is still somewhat abbreviated... lifetime extension "within" constants is fine, it's just lifetime extension at the top-level scope where we restrict borrows. I couldn't think of a good way to concisely state this.

Comment (oli-obk) [reply tests/ui/consts/const-mut-refs/issue-76510.stderr]: we don't need to be concise if we add some more info at the label or in a note. That's probably worth it for this case that will otherwise send most ppl to having to ask for help in a forum

Comment (RalfJung) [reply tests/ui/consts/const-mut-refs/issue-76510.stderr]: Do you have a concrete proposal for wording? I am a bit at a loss here, the primary message is quite long already. "mutable borrows of top-level lifetime-extended temporaries"? Even I don't quite understand what that means. "mutable borrows of lifetime-extended temporaries in the top-level scope"?

Comment (RalfJung) [reply tests/ui/consts/const-mut-refs/issue-76510.stderr]: https://doc.rust-lang.org/nightly/reference/destructors.html#r-destructors.scope.lifetime-extension.static also just says "static and const items" without saying anything about "top-level scope".

Comment (RalfJung) [reply tests/ui/consts/const-mut-refs/issue-76510.stderr]: > "mutable borrows of lifetime-extended temporaries in the top-level scope"?

I've gone for something like this now.

**Comment by RalfJung** [comment]
@rustbot ready

(Still also waiting for reference PR, but we can finalize the error message tweaks here in the mean time.)

**Review by oli-obk — APPROVED** [review]
yea this is much better than the "final value" diagnostic messages

r=me after blessing

**Comment by RalfJung** [comment]
This should probably still wait for https://github.com/rust-lang/reference/pull/1865 ?
@bors r-

**Review by traviscross — APPROVED** [review]

**Comment by traviscross** [comment]
Thanks for holding this for the documentation updates to the Reference.  That's now ready, so we can...

@bors r=oli-obk

**Comment by traviscross** [comment]
...but it has conflicts...

@bors r-

**Comment by RalfJung** [comment]
Yeah, I was waiting for the reference PR to finish so I don't have to rebase N times.
