### PR TITLE
Remove extra call to upvar_tys

### LINKED ISSUE #78720: ICE: compiler/rustc_middle/src/ty/sty.rs:399:33: upvar_tys called before capture types are inferred
### Code

```Rust
fn server() -> impl {
    ().map2(|| "")
}
trait FilterBase2 {
    fn map2<F>(self, F) -> Map2<F> {}
}
struct Map2<segment2> {
    _func: F,
}
impl<F> FilterBase2 for F {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (338f939a8 2020-11-02)
binary: rustc
commit-hash: 338f939a8d77061896cd0a1ca87a2c6d1f4ec359
commit-date: 2020-11-02
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

### Error output

```
error: at least one trait must be specified
 --> reduced-mutant.rs:1:16
  |
1 | fn server() -> impl {
  |                ^^^^

error[E0412]: cannot find type `F` in this scope
  --> reduced-mutant.rs:8:12
   |
8  |       _func: F,
   |              ^
   |
help: a trait with a similar name exists
   |
8  |     _func: Fn,
   |            ^^
help: you might be missing a type parameter
   |
7  | struct Map2<segment2, F> {
   |                     ^^^

warning: type parameter `segment2` should have an upper camel case name
 --> reduced-mutant.rs:7:13
  |
7 | struct Map2<segment2> {
  |             ^^^^^^^^ help: convert the identifier to upper camel case (notice the capitalization): `Segment2`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

error[E0601]: `main` function not found in crate `reduced_mutant`
  --> reduced-mutant.rs:1:1
   |
1  | / fn server() -> impl {
2  | |     ().map2(|| "")
3  | | }
4  | | trait FilterBase2 {
...  |
9  | | }
10 | | impl<F> FilterBase2 for F {}
   | |____________________________^ consider adding a `main` function to `reduced-mutant.rs`

error: internal compiler error: /rustc/338f939a8d77061896cd0a1ca87a2c6d1f4ec359/compiler/rustc_middle/src/ty/sty.rs:399:33: upvar_tys called before capture types are inferred

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (338f939a8 2020-11-02) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `server`
#1 [mir_built] building MIR for `server`
end of query stack
error: aborting due to 4 previous errors; 1 warning emitted

Some errors have detailed explanations: E0412, E0601.
For more information about an error, try `rustc --explain E0412`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_middle::ty::sty::ClosureSubsts::upvar_tys
   9: <rustc_trait_selection::opaque_types::ConstrainOpaqueTypeRegionVisitor<OP> as rustc_middle::ty::fold::TypeVisitor>::visit_ty
  10: <core::iter::adapters::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
  11: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_visit_with
  12: <rustc_trait_selection::opaque_types::ConstrainOpaqueTypeRegionVisitor<OP> as rustc_middle::ty::fold::TypeVisitor>::visit_ty
  13: <rustc_infer::infer::InferCtxt as rustc_trait_selection::opaque_types::InferCtxtExt>::constrain_opaque_types
  14: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  15: rustc_hir::intravisit::walk_expr
  16: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  17: rustc_hir::intravisit::walk_expr
  18: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  19: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  20: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  21: rustc_typeck::check::regionck::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::regionck_fn
  22: rustc_infer::infer::InferCtxtBuilder::enter
  23: rustc_typeck::check::typeck
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
  28: rustc_mir_build::thir::cx::Cx::new
  29: rustc_infer::infer::InferCtxtBuilder::enter
  30: rustc_mir_build::build::mir_built
  31: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_built>::compute
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  33: rustc_data_structures::stack::ensure_sufficient_stack
  34: rustc_query_system::query::plumbing::get_query_impl
  35: rustc_mir::transform::check_unsafety::unsafety_check_result
  36: core::ops::function::FnOnce::call_once
  37: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::unsafety_check_result>::compute
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_data_structures::stack::ensure_sufficient_stack
  40: rustc_query_system::query::plumbing::get_query_impl
  41: rustc_query_system::query::plumbing::ensure_query_impl
  42: rustc_mir::transform::mir_const
  43: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_const>::compute
  44: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  45: rustc_data_structures::stack::ensure_sufficient_stack
  46: rustc_query_system::query::plumbing::get_query_impl
  47: rustc_mir::transform::mir_promoted
  48: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_promoted>::compute
  49: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  50: rustc_data_structures::stack::ensure_sufficient_stack
  51: rustc_query_system::query::plumbing::get_query_impl
  52: rustc_mir::borrow_check::mir_borrowck
  53: core::ops::function::FnOnce::call_once
  54: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  55: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  56: rustc_data_structures::stack::ensure_sufficient_stack
  57: rustc_query_system::query::plumbing::get_query_impl
  58: rustc_typeck::collect::type_of::type_of
  59: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_of>::compute
  60: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  61: rustc_data_structures::stack::ensure_sufficient_stack
  62: rustc_query_system::query::plumbing::get_query_impl
  63: rustc_typeck::check::check::check_item_type
  64: rustc_middle::hir::map::Map::visit_item_likes_in_module
  65: rustc_typeck::check::check::check_mod_item_types
  66: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_item_types>::compute
  67: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  68: rustc_data_structures::stack::ensure_sufficient_stack
  69: rustc_query_system::query::plumbing::get_query_impl
  70: rustc_query_system::query::plumbing::ensure_query_impl
  71: rustc_session::utils::<impl rustc_session::session::Session>::time
  72: rustc_typeck::check_crate
  73: rustc_interface::passes::analysis
  74: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  75: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  76: rustc_data_structures::stack::ensure_sufficient_stack
  77: rustc_query_system::query::plumbing::get_query_impl
  78: rustc_interface::passes::QueryContext::enter
```

</p>
</details>

**NOTE: The bug is found by our work-in-progress compiler testing tool Kira, and the test program is reduced/minimized by [Perses](https://github.com/chengniansun/perses)**

### PR DESCRIPTION
**Pull request by arora-aman**
We already visit the tuple of upvar_tys, we don't need to visit each individual type.

Fixes #78720

r? @ghost

### CODE REVIEW

**Comment by arora-aman** [comment]
Running tests

**Comment by arora-aman** [comment]
I'm curious if we will ever call [Iterator for NeedDrop](https://github.com/rust-lang/rust/pull/78392/files#diff-ef8f5bb3073cc775d87fcf1dc0c8155961f5d83c84066ce8d47e519451cc541c) and [ty/layout](https://github.com/rust-lang/rust/pull/78392/files#diff-b0320c2b8868f325d83c027fc5d71732636e9763551e35895488f30fe057c6e9) in case the types haven't been inferred yet?


I'm assuming [this](https://github.com/rust-lang/rust/pull/78392/files#diff-364437e256ad04fca55aa5caad19f91c17f801ae42af0983b06fb464d4789b77) is fine, we won't be working with basic blocks if we have uninferred types.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@arora-aman the `elaborate-drops` code is fine, but for needs-drop I would change it to just enqueue the tupled upvars type. In general I would prefer to write code that operates on `tupled_upvar_ty` than code which invokes `upvar_tys`. 

In fact, I think we could rewrite the layout code the same way -- the layout of the closure is just the same as `self.layout_of(tupled_upvar_ty)` (if you look at the code for `ty::Tuple`, you'll see that this is basically what we're already doing anyway).

File: compiler/rustc_middle/src/ty/layout.rs [hunk 1]
```diff
@@ -2097,42 +2103,44 @@ where
...
             ty::Adt(def, substs) => {
                 match this.variants {
-                    Variants::Single { index } => def.variants[index].fields[i].ty(tcx, substs),
+                    Variants::Single { index } => Ok(def.variants[index].fields[i].ty(tcx, substs)),
 
                     // Discriminant field for enums (where applicable).
                     Variants::Multiple { ref tag, .. } => {
                         assert_eq!(i, 0);
-                        return tag_layout(tag);
+                        return Err(tag_layout(tag));
```
Comment (arora-aman) [inline compiler/rustc_middle/src/ty/layout.rs:2143]: I don't think this is necessarily an err ...

File: compiler/rustc_middle/src/ty/layout.rs [hunk 2]
```diff
@@ -2028,7 +2028,12 @@ where
         TyAndLayout { ty: this.ty, layout }
     }
 
-    fn field(this: TyAndLayout<'tcx>, cx: &C, i: usize) -> C::TyAndLayout {
+    fn ty_and_layout_kind(
+        this: TyAndLayout<'tcx>,
+        cx: &C,
+        i: usize,
+        ty: C::Ty,
+    ) -> Result<C::Ty, C::TyAndLayout> {
```
Comment (arora-aman) [inline compiler/rustc_middle/src/ty/layout.rs:2036]: I'd probably add an enum which is 
```rust
// Name can probably we better.
enum TyMaybeWithLayout {
    Ty(C::Ty),
    TyAndLayout(C::TyAndLayout)
}
```

File: compiler/rustc_middle/src/ty/layout.rs [hunk 3]
```diff
@@ -2028,7 +2028,12 @@ where
         TyAndLayout { ty: this.ty, layout }
     }
 
-    fn field(this: TyAndLayout<'tcx>, cx: &C, i: usize) -> C::TyAndLayout {
+    fn ty_and_layout_kind(
```
Comment (arora-aman) [inline compiler/rustc_middle/src/ty/layout.rs:2031]: This can just be a helper method defined inside the field method

File: compiler/rustc_middle/src/ty/layout.rs (hunk 1 above)
Comment (roxelo) [reply compiler/rustc_middle/src/ty/layout.rs:2143]: I am using the Err not because it is an error, but to know whether to return or to pass as parameter the output of `ty_and_layout_kind` into `layout_of`

File: compiler/rustc_middle/src/ty/layout.rs (hunk 2 above)
Comment (roxelo) [reply compiler/rustc_middle/src/ty/layout.rs:2036]: Oh I see, I guess that way I don't need to use result and use "Err" as a workaround

File: compiler/rustc_middle/src/ty/layout.rs (hunk 1 above)
Comment (roxelo) [reply compiler/rustc_middle/src/ty/layout.rs:2143]: Nvm, I see what you mean now: https://github.com/rust-lang/rust/pull/78725#discussion_r522574962

File: compiler/rustc_middle/src/ty/layout.rs (hunk 3 above)
Comment (roxelo) [reply compiler/rustc_middle/src/ty/layout.rs:2031]: Good point!

File: compiler/rustc_middle/src/ty/layout.rs [hunk 4]
```diff
@@ -2144,6 +2152,13 @@ where
             | ty::Param(_)
             | ty::Infer(_)
             | ty::Error(_) => bug!("TyAndLayout::field_type: unexpected type `{}`", this.ty),
+        }
+    }
+
+    fn field(this: TyAndLayout<'tcx>, cx: &C, i: usize) -> C::TyAndLayout {
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/ty/layout.rs:2158]: what is the motivation to extract this helper function?

File: compiler/rustc_target/src/abi/mod.rs [hunk 5]
```diff
@@ -1070,6 +1070,12 @@ pub trait TyAndLayoutMethods<'a, C: LayoutOf<Ty = Self>>: Sized {
         cx: &C,
         variant_index: VariantIdx,
     ) -> TyAndLayout<'a, Self>;
+    fn ty_and_layout_kind(
```
Comment (nikomatsakis) [inline compiler/rustc_target/src/abi/mod.rs:1073]: in particular, I don't think this is called from anywhere else, right?

File: compiler/rustc_middle/src/ty/layout.rs (hunk 4 above)
Comment (arora-aman) [reply compiler/rustc_middle/src/ty/layout.rs:2158]: we can't recurse on a match block as far as I know

Comment (arora-aman) [reply compiler/rustc_middle/src/ty/layout.rs:2158]: Essentially the call is 
```
cx.layout_of(match {

})
```

One way would be to construct a new `TyAndLayout` with the tuple instead of Closure as `this.ty` but I'm not sure if anything else needs to change around it

File: compiler/rustc_middle/src/ty/layout.rs [hunk 6]
```diff
@@ -2097,42 +2103,44 @@ where
...
             // Arrays and slices.
-            ty::Array(element, _) | ty::Slice(element) => element,
-            ty::Str => tcx.types.u8,
+            ty::Array(element, _) | ty::Slice(element) => Ok(element),
+            ty::Str => Ok(tcx.types.u8),
 
             // Tuples, generators and closures.
-            ty::Closure(_, ref substs) => substs.as_closure().upvar_tys().nth(i).unwrap(),
+            ty::Closure(_, ref substs) => {
+                Self::ty_and_layout_kind(this, cx, i, substs.as_closure().tupled_upvars_ty())
```
Comment (nikomatsakis) [inline compiler/rustc_middle/src/ty/layout.rs:2111]: I see, so the motivation is so that we can redirect here? And in particular so that we can get the field of a type that is not `self.ty`? You could also just have this arm of the match use a `return`...

```rust
cx.layout_of(match foo {
    ...
    Closure => return ...,
    ...
})
```

though arguably it's harder to follow. I'm ok with a helper, just wanted to understand its motivation better.

Comment (roxelo) [reply compiler/rustc_middle/src/ty/layout.rs]: Yes, that was the idea. I have moved the helper function so it now inside of the `field` method.

File: compiler/rustc_target/src/abi/mod.rs (hunk 5 above)
Comment (roxelo) [reply compiler/rustc_target/src/abi/mod.rs]: Yes, I have moved the helper function to now be inside the `field` method

**Comment by roxelo** [comment]
Other locations where `upvar_tys()` is called:

- rustc_trait_selection/src/traits/select/mod.rs
```
1609:                    Where(obligation.predicate.rebind(substs.as_closure().upvar_tys().collect()))
```
Not an issue since we `shallow_resolve` first and check if the type is `ty::Infer` before calling `upvar_tys()`

- rustc_mir_build/src/thir/cx/expr.rs
```
394:                .zip(substs.upvar_tys())
```
Should be fine since call takes place in `mir`

- rustc_middle/src/ty/print/pretty.rs
```
667:                        self = self.comma_sep(substs.as_generator().upvar_tys())?;
708:                        self = self.comma_sep(substs.as_closure().upvar_tys())?;
```
Not an issue since we call `is_valid` on the `generator` and `closure` first.

- rustc_mir/src/borrow_check/type_check/mod.rs
```
752:                    return match substs.as_closure().upvar_tys().nth(field.index()) {
755:                            field_count: substs.as_closure().upvar_tys().count(),
1948:                match substs.as_closure().upvar_tys().nth(field_index) {
1951:                        field_count: substs.as_closure().upvar_tys().count(),
```
Should be fine since call takes place in `mir`

- rustc_mir/src/borrow_check/diagnostics/var_name.rs
```
38:            self.universal_regions().defining_ty.upvar_tys().position(|upvar_ty| {
47:        let upvar_ty = self.universal_regions().defining_ty.upvar_tys().nth(upvar_index);
```
Should be fine since call takes place in `mir`

- rustc_mir_build/src/build/mod.rs
```
827:            let upvar_tys = upvar_substs.upvar_tys();
828:            let upvars_with_tys = upvars.iter().zip(upvar_tys);
```
Should be fine since call takes place in `mir`

- rustc_middle/src/ty/layout.rs
```
612:                let tys = substs.as_closure().upvar_tys();
```
**This is bad, no check for ty::Infer**

- rustc_mir/src/transform/generator.rs
```
1256:                    substs.upvar_tys().collect(),
```
Should be fine since call takes place in `mir`

- rustc_mir/src/util/elaborate_drops.rs
```
853:                let tys: Vec<_> = substs.as_closure().upvar_tys().collect();
863:                let tys: Vec<_> = substs.as_generator().upvar_tys().collect();
```
Should be fine since call takes place in `mir`

- rustc_codegen_llvm/src/debuginfo/metadata.rs
```
664:            let upvar_tys: Vec<_> = substs.as_closure().upvar_tys().collect();
669:                &upvar_tys,
677:            let upvar_tys: Vec<_> = substs
682:            prepare_enum_metadata(cx, t, def_id, unique_type_id, usage_site_span, upvar_tys)
```
Should be fine since call takes place in `codegen`

- rustc_traits/src/dropck_outlives.rs
```
220:                    &format!("upvar_tys for closure not found. Expected capture information for closure {}", ty,),
226:                for ty in substs.as_closure().upvar_tys() {
262:                    &format!("upvar_tys for generator not found. Expected capture information for generator {}", ty,),
270:                    .upvar_tys()
```
Not an issue since we call `is_valid` on the `generator` and `closure` first.

- rustc_ty/src/needs_drop.rs
```
99:                            for upvar_ty in substs.as_closure().upvar_tys() {
109:                            for upvar_ty in substs.upvar_tys() {
```
Not an issue since we call `is_valid` on the `generator` and `closure` first.

- rustc_mir/src/shim.rs
```
316:            builder.tuple_like_shim(dest, src, substs.as_closure().upvar_tys())
```
Should be fine since call takes place in `mir`

**Comment by arora-aman** [comment]
> * rustc_middle/src/ty/layout.rs
> 
> ```
> 612:                let tys = substs.as_closure().upvar_tys();
> ```
> 
> **This is bad, no check for ty::Infer**

https://github.com/rust-lang/rust/blob/7cf57288753b0fa35c3c0e7cad90c4737a4cd754/compiler/rustc_middle/src/ty/layout.rs#L612-L617

It already throws a bug if the type there is Infer
https://github.com/rust-lang/rust/blob/7cf57288753b0fa35c3c0e7cad90c4737a4cd754/compiler/rustc_middle/src/ty/layout.rs#L1244-L1246

and redirecting to tuple might not be what we want since it will use `MaybeSized`
https://github.com/rust-lang/rust/blob/7cf57288753b0fa35c3c0e7cad90c4737a4cd754/compiler/rustc_middle/src/ty/layout.rs#L620-L630

**Comment by nikomatsakis** [comment]
Let me know when this is ready for review (latest commits seem good)

**Comment by arora-aman** [comment]
@nikomatsakis  Right sorry forgot to ping you here.


@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

File: compiler/rustc_ty/src/needs_drop.rs [hunk 7]
```diff
@@ -94,15 +94,21 @@ where
                     _ if component.is_copy_modulo_regions(tcx.at(DUMMY_SP), self.param_env) => (),
 
                     ty::Closure(_, substs) => {
-                        for upvar_ty in substs.as_closure().upvar_tys() {
-                            queue_type(self, upvar_ty);
+                        // Ensure that the upvar tys has been inferred
+                        if substs.as_closure().is_valid() {
```
Comment (nikomatsakis) [inline compiler/rustc_ty/src/needs_drop.rs:98]: I think this could be `queue_type(substs.as_closure().tupled_upvars_ty())`, no?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: compiler/rustc_ty/src/needs_drop.rs (hunk 7 above)
Comment (nikomatsakis) [reply compiler/rustc_ty/src/needs_drop.rs:98]: (same with generators)

Comment (roxelo) [reply compiler/rustc_ty/src/needs_drop.rs]: done

**Comment by roxelo** [comment]
@nikomatsakis Ready for review

@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

**Comment by roxelo** [comment]
@nikomatsakis Merge conflict has been resolved

@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

**Review by nikomatsakis — APPROVED** [review]

**Comment by rylev** [comment]
@arora-aman @nikomatsakis this change caused a moderate regression in the [const eval stress test](https://perf.rust-lang.org/compare.html?start=29c4358c189fbb3bd3fd7ac3d7a95fac7b97814c&end=c4926d01ada661d4fbffb0e5b1708ae5463d47b3&stat=instructions:u). Perhaps an investigation is warranted into why that is.
