### PR TITLE
Stabilize `cfg_boolean_literals`

### LINKED ISSUE #131204: Tracking issue for RFC 3695: Allow boolean literals as cfg predicates
This is a tracking issue for the RFC "Allow boolean literals as cfg predicates" ([rust-lang/rfcs/#3695](https://github.com/rust-lang/rfcs/pull/3695)).
The feature gate for the issue is `#![feature(cfg_boolean_literals)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Accept an RFC.
  - https://github.com/rust-lang/rfcs/pull/3695
- [x] Implement in nightly.
  - https://github.com/rust-lang/rust/pull/131034
- [ ] Add documentation to the [reference][].
  - https://github.com/rust-lang/reference/pull/1762
- [ ] Stabilize.
  - https://github.com/rust-lang/rust/pull/138632

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[stabilization-instructions]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rust/pull/131034
- https://github.com/rust-lang/cargo/pull/14649

### PR DESCRIPTION
**Pull request by clubby789**
Closes #131204
@rustbot labels +T-lang +I-lang-nominated
This will end up conflicting with the test in #138293 so whichever doesn't land first will need updating

--

# Stabilization Report

### What is the RFC for this feature and what changes have occurred to the user-facing design since the RFC was finalized?

[RFC 3695](https://github.com/rust-lang/rfcs/pull/3695), none.

### What behavior are we committing to that has been controversial? Summarize the major arguments pro/con.

None

### Are there extensions to this feature that remain unstable? How do we know that we are not accidentally committing to those?

None

## Has a call-for-testing period been conducted? If so, what feedback was received?

Yes; only positive feedback was received.

### Summarize the major parts of the implementation and provide links into the code (or to PRs)

Implemented in [#131034](https://github.com/rust-lang/rust/pull/131034).

### Summarize existing test coverage of this feature

- [Basic usage, including `#[cfg()]`, `cfg!()` and `#[cfg_attr()]`](https://github.com/rust-lang/rust/blob/6d71251cf9e40326461f90f8ff9a7024706aea87/tests/ui/cfg/true-false.rs)
- [`--cfg=true/false` on the command line being accessible via `r#true/r#false`](https://github.com/rust-lang/rust/blob/6d71251cf9e40326461f90f8ff9a7024706aea87/tests/ui/cfg/raw-true-false.rs)
- [Interaction with the unstable `#[doc(cfg(..))]` feature](https://github.com/rust-lang/rust/tree/6d71251/tests/rustdoc-ui/cfg-boolean-literal.rs)
- [Denying `--check-cfg=cfg(true/false)`](https://github.com/rust-lang/rust/tree/6d71251/tests/ui/check-cfg/invalid-arguments.rs)
- Ensuring `--cfg false` on the command line doesn't change the meaning of `cfg(false)`: `tests/ui/cfg/cmdline-false.rs`
- Ensuring both `cfg(true)` and `cfg(false)` on the same item result in it being disabled: `tests/ui/cfg/both-true-false.rs`

### What outstanding bugs in the issue tracker involve this feature? Are they stabilization-blocking?

The above mentioned issue; it should not block as it interacts with another unstable feature.

### What FIXMEs are still in the code for that feature and why is it ok to leave them there?

None

### Summarize contributors to the feature by name for recognition and assuredness that people involved in the feature agree with stabilization 
- @clubby789 (RFC)
- @Urgau (Implementation in rustc)

### Which tools need to be adjusted to support this feature. Has this work been done?

`rustdoc`'s  unstable`#[doc(cfg(..)]` has been updated to respect it. `cargo` has been updated with a forward compatibility lint to enable supporting it in cargo once stabilized.

### What updates are needed to the reference/specification? (link to PRs when they exist)

A few lines to be added to the reference for configuration predicates, specified in the RFC.

### CODE REVIEW

File: tests/ui/cfg/true-false.rs [hunk 1]
```diff
@@ -1,7 +1,6 @@
 //@ run-pass
 
 #![feature(link_cfg)]
-#![feature(cfg_boolean_literals)]
 
 #[cfg(true)]
```
Comment (jieyouxu) [inline tests/ui/cfg/true-false.rs:5]: Question: this is somewhat pedantic, but is there a negative test for e.g.

- That *only* exactly `true`/`false` are accepted, *not* `r#true`/`r#false`.
- That *only* `true`/`false` is permitted, i.e. not `cfg(true = "")` or `cfg(true(false))`.
- Can this be used as an *inner* attribute on the crate root?

File: compiler/rustc_feature/src/accepted.rs [hunk 2]
```diff
@@ -93,6 +93,8 @@ declare_features! (
     (accepted, c_unwind, "1.81.0", Some(74990)),
     /// Allows `#[cfg_attr(predicate, multiple, attributes, here)]`.
     (accepted, cfg_attr_multi, "1.33.0", Some(54881)),
+    /// Allows the use of `#[cfg(<true/false>)]`.
+    (accepted, cfg_boolean_literals, "CURRENT_RUSTC_VERSION", Some(131204)),
```
Comment (jieyouxu) [inline compiler/rustc_feature/src/accepted.rs:97]: Question: how does this interact with the cli interface, i.e. what if I'm a sneaky user and wrote

```rs
// FILENAME: foo.rs
// CLI:      rustc --cfg=true foo.rs

#[cfg(true)]
fn main() {}
```

Is this permitted? If so, what's the behavior? It would be good to add a test case for this.

For instance, on nightly, `rustc --cfg=true` on

```rs
#![feature(cfg_boolean_literals)]
#[cfg(true)]
fn main() {}
```

Successfully compiles. (It produces a warning that `main` is unused, but that's because `dead_code` vs cfg-gated code.)

File: tests/ui/cfg/true-false.rs (hunk 1 above)
Comment (jieyouxu) [reply tests/ui/cfg/true-false.rs:5]: For instance, it may be good to add a test for its behavior when used as an inner attribute on the crate-level e.g.

```rust
#![feature(cfg_boolean_literals)]
#![cfg(false)]

fn main() {}
```

does not compile because the whole file is `cfg(false)`'d out, whereas

```rs
#![feature(cfg_boolean_literals)]
#![cfg(true)]

fn main() {}
```

compiles.

(And maybe even `#![cfg_attr(true, cfg(true))]` etc. at crate-root.)

File: tests/ui/cfg/true-false.rs [hunk 3]
```diff
@@ -1,7 +1,6 @@
 //@ run-pass
 
 #![feature(link_cfg)]
-#![feature(cfg_boolean_literals)]
```
Comment (jieyouxu) [inline tests/ui/cfg/true-false.rs:4]: Note: not a blocker for this stabilization, but we should reject revision names `true` and `false` in compiletest as well, because they will try to set `--cfg=true` and `--cfg=false`.

File: tests/ui/cfg/true-false.rs (hunk 1 above)
Comment (jieyouxu) [inline tests/ui/cfg/true-false.rs:5]: Question: I thought of another case where a test may be useful: what's the behavior of

```rs
#[cfg(true)]
#[cfg(false)]
fn main() {}
```

vs

```rs
#[cfg(false)]
#[cfg(true)]
fn main() {}
```

File: compiler/rustc_attr_parsing/src/attributes/cfg.rs
Comment (jieyouxu) [inline compiler/rustc_attr_parsing/src/attributes/cfg.rs:1]: Nit (meta): It would be good if you could describe in a bit more detail what the test coverage for this looks like (e.g. negative/positive tests, specific edge cases, interactions with other things, basic functionality smoke tests, etc. etc.)

File: compiler/rustc_feature/src/accepted.rs (hunk 2 above)
Comment (Urgau) [reply compiler/rustc_feature/src/accepted.rs:97]: > Is this permitted? If so, what's the behavior? It would be good to add a test case for this.

I believe we have a test for it, and what it does is that `true` (in the CLI arg) is treated as an identifier and to access it you need to use the raw syntax, that is `r#true`.

File: tests/ui/cfg/true-false.rs (hunk 1 above)
Comment (jieyouxu) [reply tests/ui/cfg/true-false.rs:5]: Ah right. Is there a test case for accepting the raw literals? I'm not seeing it in the test diffs, although I might be completely missing it.

File: compiler/rustc_feature/src/accepted.rs (hunk 2 above)
Comment (jieyouxu) [reply compiler/rustc_feature/src/accepted.rs:97]: I'm having a bit of trouble finding this specific test, so it might be good linking it in the stabilization report itself :D

File: tests/ui/cfg/true-false.rs (hunk 1 above)
Comment (Urgau) [reply tests/ui/cfg/true-false.rs:5]: I believe it's this one. https://github.com/rust-lang/rust/blob/493c38ba371929579fe136df26eccd9516347c7a/tests/ui/cfg/raw-true-false.rs

Comment (jieyouxu) [reply tests/ui/cfg/true-false.rs:5]: Oh right, so only the `true`/`false` were gated. Makes sense.

Comment (jieyouxu) [reply tests/ui/cfg/true-false.rs:5]: I think this is sufficiently addressed so resolving.

**Comment by traviscross** [comment]
@clubby789: If you could, please link in the stabilization report to each test that we would want to review the behavior of this feature and the edges of it, and describe what each is intended to demonstrate if that's not already included as a comment in the test itself.

File: tests/ui/cfg/true-false.rs (hunk 1 above)
Comment (Urgau) [reply tests/ui/cfg/true-false.rs:5]: It's the same, `main` would not be defined. As the `#[cfg]` attribute only expands when the condition evaluates to true.

**Comment by clubby789** [comment]
Added a couple of new tests with the edge cases described, and descriptions of the test coverage to the report

File: tests/ui/cfg/true-false.rs (hunk 3 above)
Comment (clubby789) [reply tests/ui/cfg/true-false.rs:4]: https://github.com/rust-lang/rust/issues/138663

**Comment by tmandry** [comment]
@rfcbot fcp merge

**Comment by traviscross** [comment]
In testing, I notice that this works, as expected:

```rust
//@ check-pass
//@ compile-flags: --cfg r#false --check-cfg=cfg(r#false)
fn main() {
    #[cfg(not(r#false))]
    compile_error!("");
}
```

And this works:

```rust
//@ check-pass
//@ compile-flags: --cfg false --check-cfg=cfg(r#false)
fn main() {
    #[cfg(not(r#false))]
    compile_error!("");
}
```

But that this doesn't work:

```rust
//@ check-pass
//@ compile-flags: --cfg false --check-cfg=cfg(false)
fn main() {
    #[cfg(not(r#false))]
    compile_error!("");
}
```

What's the reason that it's OK for `--check-cfg` to require `r#false` but not for `--cfg`?

**Comment by traviscross** [comment]
@rfcbot concern question-on-check-cfg
@rfcbot reviewed

**Comment by joshtriplett** [comment]
We should definitely ensure that `--cfg` and `--check-cfg` accept the same things, consistently.

We may wish to add a warning when you apply *either* of those to a keyword, since in code that would need to be matched with `r#`, and it would be *clearer* if the command-line likewise used the `r#` syntax.

(None of these should ever affect the behavior of `cfg(false)` or `cfg(true)`, only `cfg(r#false)` and `cfg(r#true)`.)

**Comment by traviscross** [comment]
We discussed this today in the lang triage meeting.  We believe this test should pass, exactly as it does for `cfg(r#while)`:

```rust
//@ check-pass
//@ revisions: r0x0 r0x1 r1x0 r1x1
//@[r0x0] compile-flags: --cfg false --check-cfg=cfg(false)
//@[r0x1] compile-flags: --cfg false --check-cfg=cfg(r#false)
//@[r1x0] compile-flags: --cfg r#false --check-cfg=cfg(false)
//@[r1x1] compile-flags: --cfg r#false --check-cfg=cfg(r#false)
#![deny(unexpected_cfgs)]
fn main() {
    #[cfg(not(r#false))]
    compile_error!("");
}
```

Please add a test to this effect.

**Comment by Urgau** [comment]
> What's the reason that it's OK for `--check-cfg` to require `r#false` when it's not for `--cfg`?

In `--cfg false`, `r#false` is the path of the [`MetaItem`](https://doc.rust-lang.org/stable/reference/attributes.html#meta-item-attribute-syntax).

While in `--check-cfg cfg(false)`, `false` is the boolean literal false.

And since a path can be a identifier `--cfg false` becomes `r#false`, while `false` is a literal, which can't be an identifier.

**Comment by traviscross** [comment]
@Urgau: Do you think that `false`, as a literal, should be treated differently than non-literal keywords like `while` in this regard?  I could maybe see a case for that.

**Comment by Urgau** [comment]
I think we could justify the boolean literals being treated differently and accept them in `--check-cfg` on the basis of consistency with `--cfg`.

`while` and other keywords are also an interesting case, we do accept them without raw-ness in `--cfg while` and `--check-cfg cfg(while)` but we only accept them with raw in the attribute `#[cfg(r#while)]`.

We could try to be more consistent in `--cfg` and `--check-cfg` by only accepting the same form that will be accepted in the attribute, so only accept `r#false` and `r#while` in `--cfg` and `--check-cfg`, that would make them consistent with the `#[cfg]` attribute.

**Comment by traviscross** [comment]
Yes.  Since we already accept `while` in both `--cfg` and `--check-cfg`, it still sounds right then to do the same for `true` and `false`.  If we ever decide to tighten that up for other keywords over an edition, we'd handle then for this as well.

**Comment by clubby789** [comment]
> Please add a test to this effect.

Made a [PR](https://github.com/rust-lang/rust/pull/138767) to allow this

**Review by davidtwco — APPROVED** [review]
Stabilisation impl LGTM, r=me after t-lang FCP concludes

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by clubby789** [comment]
Switched a bunch of `cfg(FALSE)` to `cfg(false)` in the tests to get some more coverage on the feature

**Comment by traviscross** [comment]
Since we settled the question of what this should do, I'm going to let the FCP run, and I'll take assignment and `r=` this after looking it over after the other PR is merged (after the MCP completes) that will align the behavior.

@rfcbot resolve question-on-check-cfg
r? traviscross

**Review by Urgau — APPROVED** [review]
