### PR TITLE
Stabilize -Zno-jump-tables into -Cjump-tables=bool

### LINKED ISSUE #116592: Tracking Issue for `no-jump-tables`
This is a tracking issue for the `-Zno-jump-tables` compiler flag

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC https://github.com/rust-lang/rust/pull/105812
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
  - [x] Unstable docs: https://github.com/rust-lang/rust/pull/116593
- [x] Formatting for new syntax has been added to the [Style Guide] ([nightly-style-procedure]) (N/A)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[nightly-style-procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md 
[Style Guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

- [ ] Should this be `-Zjump-tables=false`? C compilers accept both `-fjump-tables` and `-fno-jump-tables`. [#rust-for-linux > Stabilizing &#96;-Zno-jump-tables&#96;? @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/Stabilizing.20.60-Zno-jump-tables.60.3F/near/536345902)

### Implementation history

- Implementation: https://github.com/rust-lang/rust/pull/105812

### PR DESCRIPTION
**Pull request by pmur**
I propose stabilizing the -Zno-jump-tables option into -Cjump-tables=<bool>.

# `-Zno-jump-tables` stabilization report
## What is the RFC for this feature and what changes have occurred to the user-facing design since the RFC was finalized?
No RFC was created for this option. This was a narrowly scoped option introduced in rust-lang/rust#105812 to support code generation requirements of the x86-64 linux kernel, and eventually other targets as Rust For Linux grows.

The tracking is rust-lang/rust#116592.

##  What behavior are we committing to that has been controversial? Summarize the major arguments pro/con.

The behavior of this flag is well defined, and mimics the existing `-fno-jump-tables` option currently available with LLVM and GCC with some caveats:

* Unlike clang or gcc, this option may be ignored by the code generation backend. Rust can support multiple code-generation backends. For stabilization, only the LLVM backend honors this option.
* The usage of this option will not guarantee a library or binary is free of jump tables. To ensure a jump-table free binary, all crates in the build graph must be compiled with this option. This includes implicitly linked crates such as std or core.
* This option only enforces the crate being compiled is free of jump tables.
* No verification is done to ensure other crates are compiled with this option. Enforcing code generation options are applied across the crate graph is out of scope for this option.

What should the flag name be?
* As introduced, this option was named `-Zno-jump-tables`. However, other major toolchains allow both positive and negative variants of this option to toggle this feature. Renaming the option to `-Cjump-tables=<bool>` makes this option consistent, and if for some reason, expandable to other arguments in the future. Notably, many LLVM targets have a configurable and different thresholds for when to lower into a jump table.

## Are there extensions to this feature that remain unstable? How do we know that we are not accidentally committing to those.
No. This option is used exclusively to gate a very specific class of optimization.

## Summarize the major parts of the implementation and provide links into the code (or to PRs)
* The original PR rust-lang/rust#105812 by @ojeda 
* The stabilized CLI option is parsed as a bool:
https://github.com/pmur/rust/blob/68bfda9025ccb2778e2606e12e8021b9918f40d3/compiler/rustc_session/src/options.rs#L2025-L2026
* This options adds an attribute to each llvm function via: 
https://github.com/pmur/rust/blob/68bfda9025ccb2778e2606e12e8021b9918f40d3/compiler/rustc_codegen_llvm/src/attributes.rs#L210-L215
* Finally, the rustc book is updated with the new option:
https://github.com/pmur/rust/blob/68bfda9025ccb2778e2606e12e8021b9918f40d3/src/doc/rustc/src/codegen-options/index.md?plain=1#L212-L223

## Has a call-for-testing period been conducted? If so, what feedback was received?
No. The option has originally created is being used by Rust For Linux to build the x86-64 kernel without issue.

## What outstanding bugs in the issue tracker involve this feature? Are they stabilization-blocking?
There are no outstanding issues.

## Summarize contributors to the feature by name for recognition and assuredness that people involved in the feature agree with stabilization

* @ojeda implemented this feature in rust-lang/rust#105815 as  `-Zno-jump-tables`.
* @tgross35 created and maintained the tracking issue rust-lang/rust#116592, and provided feedback about the naming of the cli option.

## What FIXMEs are still in the code for that feature and why is it ok to leave them there?
There are none.

## What static checks are done that are needed to prevent undefined behavior?
This option cannot cause undefined behavior. It is a boolean option with well defined behavior in both cases.

## In what way does this feature interact with the reference/specification, and are those edits prepared?
This adds a new cli option to `rustc`. The documentation is updated, and the unstable documentation cleaned up in this PR.

## Does this feature introduce new expressions and can they produce temporaries? What are the lifetimes of those temporaries?
No.

## What other unstable features may be exposed by this feature?
None.

## What is tooling support like for this feature, w.r.t rustdoc, clippy, rust-analzyer, rustfmt, etc.?
No support is required from other rust tooling.

## Open Items

- [x] Are there objections renaming `-Zno-jump-tables` to `-Cjump-tables=<bool>`? The consensus is no.
- [x] Is it desirable to keep `-Zno-jump-tables` for a period of time? The consensus is no.

---

Closes rust-lang/rust#116592

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (jieyouxu) [inline compiler/rustc_codegen_llvm/src/attributes.rs:1]: Question [GUARANTEE 1/3]: is this intended to be a hint, or a guarantee?

Comment (jieyouxu) [inline compiler/rustc_codegen_llvm/src/attributes.rs:1]: Question:

> This option enables the -fno-jump-tables flag for LLVM, which makes the codegen backend avoid generating jump tables when lowering switches.
> 
> This option adds the LLVM no-jump-tables=true attribute to every function.
> 
>  The option can be used to help provide protection against jump-oriented-programming (JOP) attacks, such as with the linux kernel's [IBT](https://www.phoronix.com/news/Linux-IBT-By-Default-Tip).

How does this interact with pre-compiled std? I.e. can you mix downstream user crates compiled with `-Cjump-tables=no` versus a pre-compiled std compiled and distributed with `-Cjump-tables=yes`?

File: src/doc/rustc/src/codegen-options/index.md [hunk 1]
```diff
@@ -209,6 +209,19 @@ Note that while the `-C instrument-coverage` option is stable, the profile data
...
+## jump-tables
+
+This option is used to allow or prevent the codegen backend from creating
+jump tables when lowering switches.
+
+* `y`, `yes`, `on`, `true` or no value: allow jump tables (the default).
+* `n`, `no`, `off` or `false`: disable jump tables.
+
+Disabling jump tables can be used to help provide protection against
+jump-oriented-programming (JOP) attacks, such as with the linux kernel's [IBT].
```
Comment (jieyouxu) [inline src/doc/rustc/src/codegen-options/index.md]: Discussion [GUARANTEE 3/3]: If the flag is intended to be a hint, then this sentence can be a bit misleading, because we may not always guarantee it. We may want to slightly caveat this wording to not convey a "false promise" so to speak.

Or, if a user do want such protection, then do they need to enforce it over the whole crate graph?

File: src/doc/rustc/src/codegen-options/index.md [hunk 2]
```diff
@@ -209,6 +209,19 @@ Note that while the `-C instrument-coverage` option is stable, the profile data
 format produced by the resulting instrumentation may change, and may not work
 with coverage tools other than those built and shipped with the compiler.
 
+## jump-tables
+
+This option is used to allow or prevent the codegen backend from creating
+jump tables when lowering switches.
```
Comment (jieyouxu) [inline src/doc/rustc/src/codegen-options/index.md]: Discussion: Hm, what happens if a different cg backend is selected?

cc @GuillaumeGomez @antoyo

Comment (jieyouxu) [inline src/doc/rustc/src/codegen-options/index.md]: Question [GUARANTEE 2/3]: This wording reads like a _guarantee_ -- but _is it_? _Can_ we make that guarantee?

File: tests/assembly-llvm/x86_64-no-jump-tables.rs
Comment (jieyouxu) [inline tests/assembly-llvm/x86_64-no-jump-tables.rs:1]: Question: I'm assuming that if you inspect the assembly of an actual hello world binary that uses std in some way, then you might see jump stables still? 🤔

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (jieyouxu) [inline compiler/rustc_codegen_llvm/src/attributes.rs:1]: > Are there objections renaming -Zno-jump-tables to -Zjump-tables=<bool>?

Not having double-negatives is very nice 👍 

> Is it desirable to keep `-Zno-jump-tables` for a period of time?

No, I rather not have to keep around an unstable flag as an alias to a stable flag, that's very weird.

**Comment by ojeda** [comment]
Thanks for this!

> and eventually other targets as Rust For Linux grows

Yeah, it may get used for other things. Apart from what I mentioned in the original PR, I see LoongArch also uses it since a year ago (so I assume it should be passed for Rust too there, Cc @chenhuacai in case there is a reason not to).

> Are there objections renaming `-Zno-jump-tables` to `-Zjump-tables=<bool>`?

I assume you mean `-C` for the latter, i.e. we are going directly from `-Zno-jump-tables` to `-Cjump-tables` rather than one more step -- that is what the PR seems to do, right? Otherwise, we will need to support 3 names on the kernel side, which isn't great.

As for the name change, it seems fine -- the usual argument for using the current name is to keep it close to GCC's and Clang's flags, which always helps, but here it is obvious, i.e. we are not changing other parts of the name or grouping different flags into a new one or things like that.

> Is it desirable to keep `-Zno-jump-tables` for a period of time?

I think it is fine either way for us.

If the old flag isn't there, we may get a kernel build error here in this PR, in which case I can give you a commit to fix it.

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (antoyo) [reply src/doc/rustc/src/codegen-options/index.md]: It is not implemented yet in cg_gcc, but I guess it could be by sending `-fno-jump-tables` with `context.add_driver_option("-fno-jump-tables")` or `context.add_command_line_option("-fno-jump-tables")`.

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (pmur) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: This is guarantee for the crate being compiled. No attempts are made to verify the entire link unit is compiled with this flag.

I think that is OK. It may be desirable for some crates to control this option. A jump table isn't always a more performant optimization (such was my experience when experimenting with them on Go/PPC64).

Comment (pmur) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: It should link without issue. Disabling this codegen optimization should have no effect on ABI.

File: src/doc/rustc/src/codegen-options/index.md (hunk 1 above)
Comment (pmur) [reply src/doc/rustc/src/codegen-options/index.md]: The flag should be guarantee anything compiled with jump tables turned off does not contain jump tables. It would be up to the user to enforce this dependency beyond the individual crate.

I think it might be better to remove this statement entirely. Maybe it would be better rewriten as:
```
Disabling jump tables can be used to help provide protection against
jump-oriented-programming (JOP) attacks. However, this option makes
no guarantee any precompiled or external dependencies are compiled 
with or without jump tables.
```

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (pmur) [reply src/doc/rustc/src/codegen-options/index.md]: Should this be implemented for the other backends before stabilizing?

Comment (pmur) [reply src/doc/rustc/src/codegen-options/index.md]: It should, though that is entirely dependent on the codegen backend to honor it.

More accurately, this should be reworded as `the LLVM codegen backend`. However, it seems relatively trivial to pass this through to the gcc backend too.

File: tests/assembly-llvm/x86_64-no-jump-tables.rs
Comment (pmur) [reply tests/assembly-llvm/x86_64-no-jump-tables.rs:1]: Yes, if they exist and are included when linking. That is expected, though unintuitive to someone unfamiliar with the rust build system.

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (ojeda) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: > Not having double-negatives is very nice 👍

The current flag (i.e. the GCC/Clang naming) has no double negatives, i.e. it does not take a parameter. If it did, then yeah, it wouldn't be great.

**Comment by pmur** [comment]
> I assume you mean `-C` for the latter, i.e. we are going directly from `-Zno-jump-tables` to `-Cjump-tables` rather than one more step -- that is what the PR seems to do, right? Otherwise, we will need to support 3 names on the kernel side, which isn't great.

Yes. I've updated the report. The PR intentionally contains a commit to rename `-Zno-jump-tables` to `-Zjump-tables=`, but I think that detail is ultimately irrelevant. I don't think anyone wants to support 3 names.

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (tgross35) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: It's not a single-option flag for the C compilers: `-fjump-tables` is a legal option (and the default), `-fno-jump-tables` is just its inverted value. As-is, if we wanted to pass the positive option to rustc it would mean something like `-Cno-jump-tables=false` which has the double negative.

Unfortunately we do have a few flags that didn't remove the C-style `no-` prefix, e.g. `-Cno-redzone=false`, but I don't think we should follow that precedent. (Honestly we should probably consider deprecating that one in favor of a new `-Credzone=...`.)

Comment (ojeda) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: @tgross35 Not sure if you are replying to @jieyouxu or me. If you are replying to me, then I am confused, because that is what I was saying.

Comment (tgross35) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: It was in response to your comment about the CC flag: I'm saying that there is no double negative in that case specifically because `-fno-jump-tables` is already inverted (from `-fjump-tables`), not necessarily because it doesn't take any options.

I think we're in agreement, I'm just making a point that we aren't actually consistent with the C compilers currently because our base flag is "no-jump-tables" while theirs is "jump-tables" (and we don't treat `no-` as a prefix to flip boolean flags).

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (tgross35) [reply src/doc/rustc/src/codegen-options/index.md]: I don't think we need to block on it, though it may be worth a note. For GCC it should be a simple check here https://github.com/rust-lang/rust/blob/fe55364329579d361b1ab565728bc033a7dba07e/compiler/rustc_codegen_gcc/src/base.rs#L96, I think it should be fine to add a commit doing that to this PR if you're up for it.

(assuming Antoni is okay with doing it here rather than the submodule repo to avoid dancing also dancing around the name change).

Cc @bjorn3 for cranelift

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (tgross35) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: Maybe it's worth mentioning in the docs that:

* This can be enabled for a single crate if you are interested in controlling this for performance reasons
* If you are going after IBT concerns, it probably needs to be enabled for all crates in the graph
* Pre-built std may not meet your requirements

(Great questions btw Jieyou)

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (bjorn3) [reply src/doc/rustc/src/codegen-options/index.md]: Cranelift doesn't have support emission of jump tables for the `br_table` instruction. Avoiding emitting `br_table` itself may be feasible, but would require a cranelift-frontend change. FWIW cg_clif silently ignores many of these flags already.

Comment (antoyo) [reply src/doc/rustc/src/codegen-options/index.md]: > (assuming Antoni is okay with doing it here rather than the submodule repo to avoid dancing also dancing around the name change).

I'm OK with this.

Comment (pmur) [reply src/doc/rustc/src/codegen-options/index.md]: Adding support to the gcc backend seems straightforward. What is the difference between using `add_driver_option` vs `add_command_line_option`? The former did inhibit jump tables when I tested it.

Comment (tgross35) [reply src/doc/rustc/src/codegen-options/index.md]: It looks like maybe precedence? https://gcc.gnu.org/onlinedocs/jit/topics/contexts.html#c.gcc_jit_context_add_command_line_option

Comment (antoyo) [reply src/doc/rustc/src/codegen-options/index.md]: Some options won't work if not using the correct function. If it works, all is good.

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (jieyouxu) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: Yeah, this is why I asked, because depending on what you are aiming for, perf-only versus _security_ concerns might want different levels of guarantees (or don't need guarantees).

Comment (jieyouxu) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: (Yeah for better or worse, the rustc flags sometimes accept too many different forms of "on"/"off" that make it confusing...)

Comment (ojeda) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: > It was in response to your comment about the CC flag

My comment (and @jieyouxu's, given the quote) was referring to the current Rust flag, not the C one. In any case, I think you are talking from an implementation point of view, but I think the user interface is what matters: `-fx` existing or not does not change anything regarding double negatives on e.g. `-fno-x` and whether compilers auto-implement negatives or not (and what is the "base option" etc.) is orthogonal.

So what I was trying to say with my original comment is that there is no double negative with the current Rust interface, because the OP comment sounded ambiguous to me, i.e. there is no double negative being removed w.r.t. the current state. It is only because we want the flexibility of a parameter that the issue is introduced if we kept the name.

Comment (pmur) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: For clarification, is this a concern with the implementation or documentation? If the latter, I wonder what the most appropriate wording is. If the flag is not consistently used for all crates, this option is most likely a hint. I am unsure how this attribute survives through inlining and LTO of crates which don't enable this option.

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (jieyouxu) [reply src/doc/rustc/src/codegen-options/index.md]: I would probably add "the LLVM codegen backend" for now.

EDIT: never mind this was updated.

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (jieyouxu) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: I think there's no disagreement here, so resolving.

File: compiler/rustc_codegen_gcc/src/base.rs [hunk 3]
```diff
@@ -126,6 +126,11 @@ pub fn compile_codegen_unit(
         for arg in &tcx.sess.opts.cg.llvm_args {
             context.add_command_line_option(arg);
         }
+
+        if !tcx.sess.opts.cg.jump_tables {
+            context.add_command_line_option("-fno-jump-tables");
+        }
```
Comment (jieyouxu) [inline compiler/rustc_codegen_gcc/src/base.rs]: Remark (meta): in general for any stabilization PRs, I really would recommend that any functionality or design changes are implemented and landed _before_ the stabilization PR, and not in the stabilization PR itself (as these changes are prone to receive less scrutiny when mixed with stabilization concerns). For example, this goes straight from unimplemented -> be under a stable compiler flag.

(This is not really specific to this PR, but I've found stabilization PRs that batch non-stabilization-specific concerns super easy to miss things.)

File: src/doc/rustc/src/codegen-options/index.md (hunk 1 above)
Comment (jieyouxu) [reply src/doc/rustc/src/codegen-options/index.md]: Yes, that wording I think conveys the "caveat" that I was concerned about.

File: src/doc/rustc/src/codegen-options/index.md [hunk 4]
```diff
@@ -209,6 +209,26 @@ Note that while the `-C instrument-coverage` option is stable, the profile data
...
+* `n`, `no`, `off` or `false`: disable jump tables.
+
+To prevent jump tables being created from Rust code, a target must ensure
+all crates are compiled with jump tables disabled.
+
+Note, in many cases the rust toolchain is distributed with precompiled
+crates which could possibly include jump tables. Furthermore, this option
+does not guarantee a target will be free of jump tables. They could arise
+from external dependencies, inline asm, or other complicated interactions
+when using crates which are compiled with jump table support.
```
Comment (jieyouxu) [inline src/doc/rustc/src/codegen-options/index.md]: Suggestion: I recommend _explicitly_ calling out that this notably includes the precompiled standard library (cf. the hello-world-using-std binary example https://github.com/rust-lang/rust/pull/145974#discussion_r2308965556). Basically

> Note, in many cases the rust toolchain is distributed with precompiled
crates (such as the precompiled standard library) which could possibly include jump tables.

File: src/doc/rustc/src/codegen-options/index.md [hunk 5]
```diff
@@ -209,6 +209,26 @@ Note that while the `-C instrument-coverage` option is stable, the profile data
 format produced by the resulting instrumentation may change, and may not work
 with coverage tools other than those built and shipped with the compiler.
 
+## jump-tables
+
+This option is used to allow or prevent the LLVM or GCC codegen backend from
+creating jump tables when lowering switches from Rust code.
```
Comment (jieyouxu) [inline src/doc/rustc/src/codegen-options/index.md]: Discussion: hm, I'm not sure if we should mention the GCC codegen backend's support of this from stable-facing rustc docs, especially given that we don't have cg_gcc tests for this right? I might even recommend dropping the GCC part from this stabilization PR (and perhaps land that separately).

**Review by jieyouxu — CHANGES_REQUESTED** [review]
A few minor things, I'll start an FCP after these discussions.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/145974/fe55364329579d361b1ab565728bc033a7dba07e..696892fc0a85c0a15d01e03ebd941939b44d15dc)*

File: src/doc/rustc/src/codegen-options/index.md (hunk 2 above)
Comment (jieyouxu) [reply src/doc/rustc/src/codegen-options/index.md]: > Should this be implemented for the other backends before stabilizing?

Given that only the LLVM codegen backend is "stably" supported, it is not a stabilization blocker.

**Comment by arielb1** [comment]
Should this involve mitigation enforcement (rust-lang/rfcs#3855) as well?

Why should this differ from stack protector in that respect?

File: compiler/rustc_codegen_gcc/src/base.rs (hunk 3 above)
Comment (pmur) [reply compiler/rustc_codegen_gcc/src/base.rs]: Ok. I agree the patch detracts from the stabilization discussion and have dropped it.

File: src/doc/rustc/src/codegen-options/index.md (hunk 5 above)
Comment (pmur) [reply src/doc/rustc/src/codegen-options/index.md]: I've dropped it. If the gcc codegen backend is still unstable, I don't think it should be mentioned here. There wasn't an explicit test, and I haven't yet figured what an architecture independent test would look like.

**Comment by jieyouxu** [comment]
I'll wait a bit for the mitigation enforcement discussions, seems like it's not super clear if this should be blocked on that effort (as a more "cohesive" package, so to speak).

File: compiler/rustc_codegen_llvm/src/attributes.rs
Comment (jieyouxu) [reply compiler/rustc_codegen_llvm/src/attributes.rs:1]: Both, but I find the present wording to be sufficiently clear for this distinction.

File: compiler/rustc_session/src/options.rs [hunk 6]
```diff
@@ -2093,6 +2093,8 @@ options! {
         "instrument the generated code to support LLVM source-based code coverage reports \
         (note, the compiler build config must include `profiler = true`); \
         implies `-C symbol-mangling-version=v0`"),
+    jump_tables: bool = (true, parse_bool, [TRACKED],
+        "Allow jump table and lookup table generation from switch case lowering (default: yes)"),
```
Comment (petrochenkov) [inline compiler/rustc_session/src/options.rs]:
```suggestion
        "allow jump table and lookup table generation from switch case lowering (default: yes)"),
```

File: src/doc/rustc/src/codegen-options/index.md [hunk 7]
```diff
@@ -209,6 +209,27 @@ Note that while the `-C instrument-coverage` option is stable, the profile data
...
+This option is used to allow or prevent the LLVM codegen backend from creating
+jump tables when lowering switches from Rust code.
+
+* `y`, `yes`, `on`, `true` or no value: allow jump tables (the default).
+* `n`, `no`, `off` or `false`: disable jump tables.
+
+To prevent jump tables being created from Rust code, a target must ensure
+all crates are compiled with jump tables disabled.
+
+Note, in many cases the rust toolchain is distributed with precompiled
```
Comment (wesleywiser) [inline src/doc/rustc/src/codegen-options/index.md]: nit

```suggestion
Note, in many cases the Rust toolchain is distributed with precompiled
```

**Review by wesleywiser — APPROVED** [review]

**Review by wesleywiser — APPROVED** [review]

**Comment by ojeda** [comment]
Please add https://github.com/ojeda/rust/commit/8781c65fd2083b47b9d38fe6b2cf6f6d720bde6c to this branch and try again. I tested it locally. Thanks!

**Comment by tgross35** [comment]
@pmur I think you'll have to pick up Miguel's patch ([comment](https://github.com/rust-lang/rust/pull/145974#issuecomment-3475939357)) on your branch for this to go through, since that updates the rust-for-linux job to work with both flags
