### PR TITLE
Call into fastfail on abort in libpanic_abort on Windows x86(_64)

### LINKED ISSUE #73215: Use __fastfail in libpanic_abort on Windows
libpanic_abort currently uses Rust's [abort intrinsic for aborts](https://github.com/rust-lang/rust/blob/13290e83a6e20f3b408d177a9d64d8cf98fe4615/library/panic_abort/src/lib.rs#L60) (which uses an illegal opcode to abort the process). This directly contrasts with libstd which uses [inline assembly](https://github.com/rust-lang/rust/blob/13290e83a6e20f3b408d177a9d64d8cf98fe4615/library/std/src/sys/windows/mod.rs#L315) to call into Windows [__failfail intrinsic](https://docs.microsoft.com/en-us/cpp/intrinsics/fastfail). This is preferred because __fastfail allows for debuggers to attach after the process has aborted for debugging. 

Perhaps we should use the same abort implementation used in libstd for libpanic_abort. 

### Drawbacks
Before Windows 8 __fastfail wasn't available and so calling into it on this platforms leads to an access violation. Access violations are not catchable by normal exception handlers but are catchable by [SEH}(https://docs.microsoft.com/en-us/windows/win32/debug/structured-exception-handling)

### PR DESCRIPTION
**Pull request by rylev**
This partially resolves #73215 though this is only for x86 targets. This code is directly lifted from [libstd](https://github.com/rust-lang/rust/blob/13290e83a6e20f3b408d177a9d64d8cf98fe4615/library/std/src/sys/windows/mod.rs#L315). `__fastfail` is the preferred way to abort a process on Windows as it will hook into debugger toolchains.  

Other platforms expose a `_rust_abort` symbol which wraps `std::sys::abort_internal`. This would also work on Windows, but is a slightly largely change as we'd need to make sure that the symbol is properly exposed to the linker. I'm inlining the call to the `__fastfail`, but the indirection through `rust_abort` might be a cleaner approach. 

 A different instruction must be used on ARM architectures. I'd like to verify this works first before tackling ARM.

### CODE REVIEW

**Comment by mati865** [comment]
Is there a reason to duplicate the code instead of calling already existing function?

**Comment by rylev** [comment]
The function is not available as it's defined in standard and panic_abort is `!#[no_std]`. The trick pulled by some targets is to expose a `__rust_panic` symbol which is linked to when linking panic_abort and the standard library. We can also use that trick here I believe. I'm just not familiar enough with the mechanics of how std gets built to ensure that it works properly.

File: library/std/src/sys/windows/mod.rs [hunk 1]
```diff
@@ -281,7 +281,11 @@ macro_rules! impl_is_zero {
 impl_is_zero! { i8 i16 i32 i64 isize u8 u16 u32 u64 usize }
 
 pub fn cvt<I: IsZero>(i: I) -> crate::io::Result<I> {
-    if i.is_zero() { Err(crate::io::Error::last_os_error()) } else { Ok(i) }
+    if i.is_zero() {
```
Comment (rylev) [inline library/std/src/sys/windows/mod.rs:284]: This change came from rustfmt.

**Comment by alexcrichton** [comment]
The already existing function only exists in libstd I believe which panic_abort can't depend on. I'm not sure what's up with `__rust_abort` but that looks like it's for niche use cases, and the amount of duplication here is just one line, so I think duplication is fine here.

**Comment by shepmaster** [comment]
@alexcrichton would you feel comfortable taking this review? I definitely don't understand it enough.

**Comment by alexcrichton** [comment]
Sure!

@bors: r+
