### PR TITLE
std: improve handling of timed condition variable waits on macOS

### LINKED ISSUE #37440: Unexpected behavior using std::thread::park_timeout on OSX
I have encountered what I think is unexpected behavior from `std::thread::park_timeout` on OSX: when called with "large" values the `park_timeout` call will return immediately, instead of waiting for an `unpark` call. What constitutes "large" is variable, and appears to correspond to the current value in the system monotonic clock source.

The following code reproduces the issue:

``` rust
use std::thread;
use std::time::Duration;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::u64;

// "Small" value that will properly sleep until `unpark` is called.
const TEST_VALUE: u64 = 10_000u64;

// "Large" value that will return almost immediately.
// const TEST_VALUE: u64 = u64::MAX;

fn main() {
    let stop = Arc::new(AtomicBool::new(false));
    let stop2 = stop.clone();

    let handle = thread::spawn(move || {
        loop {
            if stop2.load(Ordering::Relaxed) { break }
            println!("Parking for 0x{:08x} millis", TEST_VALUE);
            thread::park_timeout(Duration::from_millis(TEST_VALUE));
        }
    });

    thread::sleep(Duration::new(1, 0));
    stop.store(true, Ordering::Relaxed);
    handle.thread().unpark();
    handle.join().unwrap();
}
```

If you run the code above with the "small" value uncommented the internal loop only runs once, waiting for the 1-second sleep to expire before `unpark` is called. But if you run with the "large" value uncommented, the internal loop runs a very large number of times as each call to `thread::park_timeout` returns almost immediately.

As noted above, the actual value of "large" decreases over time, I believe based on `u64::MAX - (current_monotonic_time)`. I unfortunately couldn't come up with a way to prove this is the case.

I've seen this behavior on OSX Yosemite and Sierra.

Edit: this happens on 1.11, 1.12, beta, and nightly.

### PR DESCRIPTION
**Pull request by joboet**
Fixes rust-lang/rust#37440 (for good).

This fixes two issues with `Condvar::wait_timeout` on macOS:

Apple's implementation of `pthread_cond_timedwait` internally converts the absolute timeout to a relative one, measured in nanoseconds, but fails to consider overflow when doing so. This results in `wait_timeout` returning much earlier than anticipated when passed a duration that is slightly longer than `u64::MAX` nanoseconds (around 584 years). The existing clamping introduced by rust-lang/rust#42604 to address rust-lang/rust#37440 unfortunately used a maximum duration of 1000 years and thus still runs into the bug when run on older macOS versions (or with `PTHREAD_MUTEX_USE_ULOCK` set to a value other than "1"). See https://github.com/rust-lang/rust/issues/37440#issuecomment-3285958326 for context.

Reducing the maximum duration alone however would not be enough to make the implementation completely correct. As macOS does not support `pthread_condattr_setclock`, the deadline passed to `pthread_cond_timedwait` is measured against the wall-time clock. `std` currently calculates the deadline by retrieving the current time and adding the duration to that, only for macOS to convert the deadline back to a relative duration by [retrieving the current time itself](https://github.com/apple-oss-distributions/libpthread/blob/1ebf56b3a702df53213c2996e5e128a535d2577e/src/pthread_cond.c#L802-L819) (this conversion is performed before the aforementioned problematic one). Thus, if the wall-time clock is adjusted between the `std` lookup and the system lookup, the relative duration could have changed, possibly even to a value larger than $2^{64}\ \textrm{ns}$. Luckily however, macOS supports the non-standard, tongue-twisting `pthread_cond_timedwait_relative_np` function which avoids the wall-clock-time roundtrip by taking a relative timeout. Even apart from that, this function is perfectly suited for `std`'s purposes: it is public (albeit badly-documented) API, [available since macOS 10.4](https://github.com/apple-oss-distributions/libpthread/blob/1ebf56b3a702df53213c2996e5e128a535d2577e/include/pthread/pthread.h#L555-L559) (that's way below our minimum of 10.12) and completely resilient against wall-time changes as all timeouts are [measured against the monotonic clock](https://github.com/apple-oss-distributions/xnu/blob/e3723e1f17661b24996789d8afc084c0c3303b26/bsd/kern/sys_ulock.c#L741) inside the kernel.

Thus, this PR switches `Condvar::wait_timeout` to `pthread_cond_timedwait_relative_np`, making sure to clamp the duration to a maximum of $2^{64} - 1 \ \textrm{ns}$. I've added a miri shim as well, so the only thing missing is a definition of `pthread_cond_timedwait_relative_np` inside `libc`.

### CODE REVIEW

File: src/tools/miri/src/shims/unix/sync.rs [hunk 1]
```diff
@@ -853,14 +854,23 @@ pub trait EvalContextExt<'tcx>: crate::MiriInterpCxExt<'tcx> {
...
             }
         };
-        if data.clock == TimeoutClock::RealTime {
-            this.check_no_isolation("`pthread_cond_timedwait` with `CLOCK_REALTIME`")?;
-        }
+
+        let (clock, anchor) = if relative {
+            // `pthread_cond_timedwait_relative_np` always measures time against the
+            // monotonic clock, regardless of the condvar clock.
+            (TimeoutClock::Monotonic, TimeoutAnchor::Relative)
```
Comment (RalfJung) [inline src/tools/miri/src/shims/unix/sync.rs:861]: So the argument named `relative` really is very specific for this macos operation, and also swaps out the clock.  Please give it a name that more accurately reflects what it does (e.g. `macos_relative_np`), and document it in the doc comment for this function.

File: src/tools/miri/tests/pass-dep/libc/pthread_cond_timedwait_relative_np_apple.rs [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+
+        assert_eq!(libc::pthread_mutex_lock(&mut mutex as *mut _), 0);
+
+        let current_time = Instant::now();
+        assert_eq!(
+            libc::pthread_cond_timedwait_relative_np(&mut cond, &mut mutex, &timeout),
+            libc::ETIMEDOUT
+        );
+        let elapsed_time = current_time.elapsed().as_millis();
+        assert!(50 <= elapsed_time && elapsed_time <= 150);
```
Comment (RalfJung) [inline src/tools/miri/tests/pass-dep/libc/pthread_cond_timedwait_relative_np_apple.rs]:
```suggestion
        // This is actually deterministic (since isolation remains enabled), but can change slightly with Rust updates.
        assert!(90 <= elapsed_time && elapsed_time <= 110);
```

File: src/tools/miri/src/shims/unix/macos/foreign_items.rs [hunk 3]
```diff
@@ -307,6 +307,12 @@ pub trait EvalContextExt<'tcx>: crate::MiriInterpCxExt<'tcx> {
                 this.os_unfair_lock_assert_not_owner(lock_op)?;
             }
 
+            "pthread_cond_timedwait_relative_np" => {
+                let [cond, mutex, reltime] =
+                    this.check_shim_sig_lenient(abi, CanonAbi::C, link_name, args)?;
+                this.pthread_cond_timedwait(cond, mutex, reltime, dest, true)?;
```
Comment (RalfJung) [inline src/tools/miri/src/shims/unix/macos/foreign_items.rs]:
```suggestion
                this.pthread_cond_timedwait(cond, mutex, reltime, dest, /* macos_relative_np */ true)?;
```

File: src/tools/miri/src/shims/unix/foreign_items.rs [hunk 4]
```diff
@@ -815,7 +815,7 @@ pub trait EvalContextExt<'tcx>: crate::MiriInterpCxExt<'tcx> {
             "pthread_cond_timedwait" => {
                 let [cond, mutex, abstime] =
                     this.check_shim_sig_lenient(abi, CanonAbi::C, link_name, args)?;
-                this.pthread_cond_timedwait(cond, mutex, abstime, dest)?;
+                this.pthread_cond_timedwait(cond, mutex, abstime, dest, false)?;
```
Comment (RalfJung) [inline src/tools/miri/src/shims/unix/foreign_items.rs]:
```suggestion
                this.pthread_cond_timedwait(cond, mutex, abstime, dest, /* macos_relative_np */ false)?;
```

File: library/std/src/sys/pal/unix/sync/condvar.rs [hunk 5]
```diff
@@ -84,6 +81,68 @@ impl Condvar {
...
+        // This can be observed even on newer platforms (by setting the environment
+        // variable PTHREAD_MUTEX_USE_ULOCK to a value other than "1") by calling e.g.
+        // ```
+        // condvar.wait_timeout(..., Duration::from_secs(u64::MAX.div_ceil(1_000_000_000));
+        // ```
+        // (see #37440, especially
+        // https://github.com/rust-lang/rust/issues/37440#issuecomment-3285958326).
+        //
+        // To work around this issue, always clamp the timeout to u64::MAX nanoseconds,
+        // even if the "ulock" variant is used (which does guard against timeouts).
```
Comment (RalfJung) [inline library/std/src/sys/pal/unix/sync/condvar.rs]:
```suggestion
        // even if the "ulock" variant is used (which does guard against overflow).
```

File: src/tools/miri/src/shims/unix/sync.rs (hunk 1 above)
Comment (joboet) [reply src/tools/miri/src/shims/unix/sync.rs:861]: Done, thank you!

File: library/std/src/sys/pal/unix/sync/condvar.rs [hunk 6]
```diff
@@ -84,6 +81,68 @@ impl Condvar {
...
+                lock: *mut libc::pthread_mutex_t,
+                timeout: *const libc::timespec,
+            ) -> libc::c_int;
+        }
+
+        let r = unsafe { pthread_cond_timedwait_relative_np(self.raw(), mutex, &timeout) };
+        assert!(r == libc::ETIMEDOUT || r == 0);
+        // Report clamping as a spurious wakeup. Who knows, maybe some
+        // interstellar space probe will rely on this ;-).
+        r == 0 || clamped
```
Comment (RalfJung) [inline library/std/src/sys/pal/unix/sync/condvar.rs:131]: This is actually an interesting API question... is `wait_timeout` allowed to return "timeout" for a spurious wakeup?

The other codepath, which clamps the timeout on cygwin, still assumes that to be allowed, but this codepath here goes out of its way to avoid that.

Comment (joboet) [reply library/std/src/sys/pal/unix/sync/condvar.rs:131]: The documentation of `wait_timeout` says that (emphasis mine)
> The returned [WaitTimeoutResult](https://doc.rust-lang.org/nightly/std/sync/struct.WaitTimeoutResult.html) value indicates if the timeout is *known* to have elapsed.

So I'd say that spurious wakeups may not return a `WaitTimeoutResult` that indicates timeout. But then again, who knows what the system might do internally – the newer futex-like macOS implementation of `pthread_cond_timedwait` for instance properly clamps the nanoseconds, but will not perform this check. I guess it isn't too much of an issue, given that even the clamped timeout will only actually occur after 584 (macOS) and 1000 (Cygwin) years.

File: library/std/tests/sync/condvar.rs [hunk 7]
```diff
@@ -267,3 +267,35 @@ nonpoison_and_poison_unwrap_test!(
...
+                maybe_unwrap(sent.set(true));
+                cond.notify_all();
+            });
+
+            let guard = maybe_unwrap(sent.lock());
+            // If there is internal overflow, this call will return almost
+            // immediately, before the other thread has reached the `notify_all`
+            let (guard, res) = maybe_unwrap(cond.wait_timeout(guard, Duration::from_secs(u64::MAX.div_ceil(1_000_000_000))));
+            assert!(!res.timed_out());
+            assert!(*guard);
```
Comment (matthiaskrgr) [inline library/std/tests/sync/condvar.rs:298]: this seems to fail in CI from time to time: https://github.com/rust-lang/rust/issues/147885
