### PR TITLE
resolve: Implement prelude search for macro paths, implement tool attributes

### LINKED ISSUE #51277: tool_attributes feature stops working when rust_2018_preview feature is enabled
If both features `tool_attributes` and `rust_2018_preview` are enabled, scoped attributes lead to the error message 
```
error[E0658]: paths of length greater than one in macro invocations are currently unstable (see issue #38356)
 --> src/main.rs:4:3
  |
4 | #[rustfmt::skip]
  |   ^^^^^^^^^^^^^
  |
  = help: add #![feature(proc_macro_path_invoc)] to the crate attributes to enable
```

I think this can be fixed by doing this https://github.com/rust-lang/rust/pull/47773#pullrequestreview-92758596 right. I would like to try and fix this, but I need some pointers where to start.

This needs to be fixed, so clippy can use the new scoped attributes instead of the old `cfg_attr`s (https://github.com/rust-lang-nursery/rust-clippy/pull/2823). 

### I tried this code:
```rust
#![feature(tool_attributes)]
#![feature(rust_2018_preview)]

#[rustfmt::skip]
fn main() {
    //code not to format
}
```
[Playground](https://play.rust-lang.org/?gist=5e58bba0f9cde9deb1a0a60c7b604d6a&version=nightly&mode=debug)
This should compile without errors, but gives the error above

## Meta
```
rustc 1.28.0-nightly (5d0631a64 2018-05-30)
binary: rustc
commit-hash: 5d0631a6438cf30cac236b7176371663e35c8d07
commit-date: 2018-05-30
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

### LINKED ISSUE #52512: Macro path resolution ignores preludes
All kinds of them - [extern prelude](https://github.com/rust-lang/rust/pull/49789), standard library prelude, language prelude, except for the macro prelude of course (which contains of builtin macros and macros from `#[macro_use] extern crate`). 

```rust
#![feature(extern_prelude, use_extern_macros)]
#![allow(unused)]

mod m {
    fn f() {
        std::mem::drop(0); // OK, extern prelude
        Result::Ok::<u8, u8>(0); // OK, standard library prelude
        u8::clone(&0); // OK, language prelude
        
        std::panic!(); // ERROR failed to resolve. Use of undeclared type or module `std`
        Result::Ok!(); //  ERROR failed to resolve. Use of undeclared type or module `Result`
        u8::clone!(); // ERROR failed to resolve. Use of undeclared type or module `u8`
    }
}

fn main() {}
```

### LINKED ISSUE #52576: Calling macros with full paths doesn't work with implicit crates
```rust
// edition = "2018"
// [dependencies] lazy_static = "1.0.1"

#![feature(rustc_2018_preview)]
#![feature(use_extern_macros)]
lazy_static::lazy_static! {static ref FOO: u8 = 1;}
```

This fails to compile (even with `extern crate lazy_static`). It does compile if I add a `use lazy_static`.

AIUI this is a bug, you should be able to import directly from crates in macros as well.

cc @dtolnay  @alexcrichton

### PR DESCRIPTION
**Pull request by petrochenkov**
When identifier is macro path is resolved in scopes (i.e. the first path segment - `foo` in `foo::mac!()` or `foo!()`), scopes are searched in the same order as for non-macro paths - items in modules, extern prelude, tool prelude (see later), standard library prelude, language prelude, but with some extra shadowing restrictions (names from globs and macro expansions cannot shadow names from outer scopes). See the comment in `fn resolve_lexical_macro_path_segment` for more details.

"Tool prelude" currently contains two "tool modules" `rustfmt` and `clippy`, and is searched immediately after extern prelude.
This makes the [possible long-term solution](https://github.com/rust-lang/rfcs/blob/master/text/2103-tool-attributes.md#long-term-solution) for tool attributes exactly equivalent to the existing extern prelude scheme, except that `--extern=my_crate` making crate names available in scope is replaced with something like `--tool=my_tool` making tool names available in scope.

The `tool_attributes` feature is still unstable and `#![feature(tool_attributes)]` now implicitly enables `#![feature(use_extern_macros)]`. `use_extern_macros` is a prerequisite for `tool_attributes`, so their stabilization will happen in the same order.
If `use_extern_macros` is not enabled, then tool attributes are treated as custom attributes (this is temporary, anyway).

Fixes https://github.com/rust-lang/rust/issues/52576
Fixes https://github.com/rust-lang/rust/issues/52512
Fixes https://github.com/rust-lang/rust/issues/51277
cc https://github.com/rust-lang/rust/issues/52269

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? @alexcrichton 
cc @nrc @djrenren

File: src/librustc_resolve/macros.rs [hunk 1]
```diff
@@ -542,67 +561,222 @@ impl<'a> Resolver<'a> {
...
+                WhereToResolve::ToolPrelude => {
+                    if is_known_tool(ident.name) {
+                        let binding = (Def::ToolMod, ty::Visibility::Public,
+                                       ident.span, Mark::root()).to_name_binding(self.arenas);
+                        Ok(MacroBinding::Global(binding))
+                    } else {
+                        Err(Determinacy::Determined)
+                    }
+                }
+                WhereToResolve::StdLibPrelude => {
```
Comment (petrochenkov) [inline src/librustc_resolve/macros.rs]: FIXME: account for `no_implicit_prelude`.

**Comment by pietroalbini** [comment]
This is also blocking edition crater runs.

**Comment by pietroalbini** [comment]
@bors r- 

This is breaking clippy, and we're in beta week. https://github.com/rust-lang/rust/pull/52944#issuecomment-409624428

**Comment by alexcrichton** [comment]
I've sent a PR for the clippy breakage in https://github.com/rust-lang-nursery/rust-clippy/pull/2993

**Comment by oli-obk** [comment]
I created a long lived branch for your PR: https://github.com/rust-lang-nursery/rust-clippy/tree/acrichto_lockstep

you can point the clippy submodule at that commit in this PR and then merge it

**Comment by Manishearth** [comment]
We should not create long lived branches -- we should create short lived ones that we `git merge` into master to keep the commits around.

**Comment by alexcrichton** [comment]
@bors: retry

Looks like with https://github.com/rust-lang/rust/pull/52949 we're in the mode of "we can break tools again"

**Comment by Manishearth** [comment]
This breaks Servo in a weird way. I'm unable to reproduce this out of tree

https://travis-ci.org/servo/servo-with-rust-nightly/jobs/411851355

```
error[E0659]: `warn` is ambiguous
   --> ports/servo/glutin_app/window.rs:733:21
    |
733 |                     warn!("Failed to swap window buffers ({}).", err);
    |                     ^^^^
    |
note: `warn` could refer to the name imported here
   --> ports/servo/non_android_main.rs:12:1
    |
12  | #[macro_use] extern crate log;
    | ^^^^^^^^^^^^
note: `warn` could also refer to the name defined here
   --> ports/servo/glutin_app/window.rs:733:21
    |
733 |                     warn!("Failed to swap window buffers ({}).", err);
    |                     ^^^^
    = note: macro-expanded macro imports do not shadow
```

any idea what's going on? seems like a regression

**Comment by Manishearth** [comment]
cc @pietroalbini might want to be careful about that regression before cutting a beta ^^

**Comment by petrochenkov** [comment]
I'll look what happens.

**Comment by petrochenkov** [comment]
@Manishearth 
This is an expected breakage.
The general rule sounds like "names from globs and macro expansions cannot shadow names from outer scopes when macro paths are resolved".
Without this rule macro expansion would almost always get stuck in scopes with unexpanded macros or globs without being able to proceed.

In this case macro expanded name (macro_rules macro `warn` from `#[macro_use] extern crate log;` inside `include!()` expansion) shadows a name from outer scope (built-in attribute `warn` from the language prelude), and this happens during resolution of the macro path `warn` in `warn!("Failed to swap window buffers ({}).", err);`.

Minimized reproduction:
```rust
macro_rules! my_include {() => {
    #[macro_use] extern crate log;
}}

my_include!();

fn main() {
    warn!("");
}
```

In this case, since breakage affects stable channel, built-in attributes can be somehow special-cased to avoid the error, or perhaps some more general solution can be found, but I'd prefer to see crater results before proceeding with a fix.

**Comment by petrochenkov** [comment]
Since https://github.com/rust-lang/rust/issues/53072 doesn't include this PR, we need a separate crater run for it.

**Comment by Mark-Simulacrum** [comment]
Queued a crater run for this PR (check only) here: https://github.com/rust-lang/rust/issues/53089

**Comment by nnethercote** [comment]
Good news! This PR improved compile speed on a few benchmarks, the best by 3.7%:
https://perf.rust-lang.org/compare.html?start=40cb4478a3f550bf12d81cdcf08cc9ef3985ed41&end=40e4b6ee3dd70a05007915bd1c15c150a7b7899f&stat=instructions:u
