### PR TITLE
pointee_info_at: fix logic for recursing into enums

### LINKED ISSUE #131834: Drop the dereferenceable attribute when a reference is passed in an enum
Considering [the following code](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=d3fe55772eb8ed60ebd5ad31f7e57b02), it should print 0 with a release build, but I get a segmentation violation.

```rust
#![feature(rustc_attrs)]
#![allow(internal_features)]
#![allow(dead_code)]

#[rustc_layout_scalar_valid_range_start(1)]
#[rustc_layout_scalar_valid_range_end(0xfffffffffffffff0)]
pub struct RestrictedAddress(&'static i8);

enum E {
    A(RestrictedAddress),
    B,
    C,
}

#[no_mangle]
#[inline(never)]
fn foo(a: E) -> i8 {
    match a {
        E::A(v) => *v.0,
        _ => 0,
    }
}

fn main() {
    println!("{}", foo(std::hint::black_box(E::B)));
}
```

This is because we are adding the `dereferenceable` attribute, which allows LLVM to hoist the load instruction. In this case, we need to drop the `dereferenceable` attribute.

@rustbot label +requires-nightly +I-miscompile +A-codegen

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/131834

The logic in `pointee_info_at` was likely written at a time when the null pointer optimization was the *only* enum layout optimization -- and as `Variant::Multiple` kept getting expanded, nobody noticed that the logic is now unsound.

The job of this function is to figure out whether there is a dereferenceable-or-null and aligned pointer at a given offset inside a type. So when we recurse into a multi-variant enum, we better make sure that all the other enum variants must be null! This is the part that was forgotten, and this PR adds it.

The reason this didn't explode in many ways so far is that our references only have 1 niche value (null), so it's not possible on stable to have a multi-variant enum with a dereferenceable pointer and other enum variants that are not null. But with `rustc_layout_scalar_valid_range` attributes one can force such a layout, and if @the8472's work on alignment niches ever lands, that will make this possible on stable.

### CODE REVIEW

File: compiler/rustc_middle/src/ty/layout.rs [hunk 1]
```diff
@@ -1011,25 +1011,41 @@ where
...
+                        assert_eq!(tagged_variant, *niche_variants.start());
+                        if *niche_start == 0 {
+                            // The other variant is encoded as "null", so we can recurse searching for
+                            // a pointer here. This relies on the fact that the codegen backend
+                            // only adds "dereferenceable" if there's also a "nonnull" proof,
+                            // and that null is aligned for all alignments so it's okay to forward
+                            // the pointer's alignment.
+                            Some(this.for_variant(cx, *untagged_variant))
+                        } else {
+                            None
```
Comment (DianQK) [inline compiler/rustc_middle/src/ty/layout.rs:1045]: IIUC, this align will always be 1. I adjusted align at #131739, and I think it's sound.

Comment (DianQK) [reply compiler/rustc_middle/src/ty/layout.rs:1045]: How about adding a `dereferenceable` field to `PointeeInfo`? Or something similar?

File: compiler/rustc_middle/src/ty/layout.rs [hunk 2]
```diff
@@ -1011,25 +1011,41 @@ where
...
                     Variants::Multiple {
-                        tag_encoding: TagEncoding::Niche { untagged_variant, .. },
+                        tag_encoding:
+                            TagEncoding::Niche { untagged_variant, niche_variants, niche_start },
                         tag_field,
+                        variants,
                         ..
-                    } if this.fields.offset(tag_field) == offset => {
-                        Some(this.for_variant(cx, untagged_variant))
+                    } if variants.len() == 2 && this.fields.offset(*tag_field) == offset => {
```
Comment (DianQK) [inline compiler/rustc_middle/src/ty/layout.rs:1030]: Should ignore uninhabited variants?

File: compiler/rustc_middle/src/ty/layout.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1045]: No, `align` here can be larger than 1. This is checked by the existing test:
```
// CHECK: @option_borrow(ptr noalias noundef readonly align 4 dereferenceable_or_null(4) %_x)
#[no_mangle]
pub fn option_borrow(_x: Option<&i32>) {}

// CHECK: @option_borrow_mut(ptr noalias noundef align 4 dereferenceable_or_null(4) %_x)
#[no_mangle]
pub fn option_borrow_mut(_x: Option<&mut i32>) {}
```
Notice the `align 4`.

I don't see why adding a "dereferenceable" field would help. The entire `PointeeInfo` struct *is* the "derefernceable-or-null" flag; a non-dereferenceable type must return `None`. The "or-null" part is easy to deal with later since we can use the scalar range to check whether null is allowed or not; it would be redundant to also compute that here.

Comment (DianQK) [reply compiler/rustc_middle/src/ty/layout.rs:1045]: Perhaps my comment was a bit misplaced. See https://github.com/rust-lang/rust/pull/131739/files#diff-a93329b2efc9dabaf147bfdb806fb52501ed7889eb08e26e1a2714bb43862531R22-R39. In this case, we need to drop `dereferenceable`, but we can keep `align 8`.

File: compiler/rustc_middle/src/ty/layout.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1030]: That's not needed.  A 2-variant enum where one variant is uninhabited will use `Variants::Single`.

Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1030]: This will theoretically miss some optimizations on a 3-variant enum where 1 variant is uninhabited and the other variant is null. But the goal of this PR is a soundness fix, so I am totally fine with missing some possible optimizations.

File: compiler/rustc_middle/src/ty/layout.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/layout.rs:1045]: I don't think that's worth the effort. We shouldn't implement complicated logic like that unless it actually has real-world benefit.

**Comment by DianQK** [comment]
Feel free to r=me or not. This will unlock @the8472's work even without #131739.
The align related discussion can be continued entirely in #131739.

**Review by dianqk — APPROVED** [review]

**Comment by RalfJung** [comment]
Thanks!
@bors r=DianQK
