### PR TITLE
doctests: fix merging on stable

### LINKED ISSUE #137898: Doctest merging doesn't work at all on stable
I downloaded the current stable branch, and set up this sample crate to detect if the test is running in merged mode.

~~~rust
//! ```rust
//! let location = std::panic::Location::caller();
//! assert_eq!(location.line(), 11);
//! ```
~~~

If I run `RUSTC_BOOTSTRAP=1 cargo +stable test` it passes. If I drop the bootstrap env, it fails.

https://github.com/rust-lang/rust/blob/f4a216d28ee635afce685b4206e713579f66e130/src/librustdoc/doctest/runner.rs#L74-L77

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: aarch64-apple-darwin
release: 1.85.0
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #137898

The generated multi-test harness relies on nightly-only APIs, so the only way to run it on stable is to enable them.

To prevent the executing test case from getting at any of the stuff that the harness uses, they're built as two separate crates. The test bundle isn't built with RUSTC_BOOTSTRAP, while the runner harness is.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Good catch! r=me once CI pass. Also is there a way to test it?

File: src/librustdoc/doctest.rs [hunk 1]
```diff
@@ -550,7 +550,12 @@ fn run_test(
     }
 
     compiler.arg("--edition").arg(doctest.edition.to_string());
-    if !doctest.is_multiple_tests {
+    if doctest.is_multiple_tests {
+        // The merged test harness uses the `test` crate, so we need to actually allow it.
+        // This will not expose nightly features on stable, because crate attrs disable
+        // merging, and `#![feature]` is required to be a crate attr.
```
Comment (fmease) [inline src/librustdoc/doctest.rs:556]: I'm afraid that isn't true in practice because `partition_source` is pretty naive and buggy at the moment and only detect crate attributes that are literally start with the string `#![`! Literally adding a space between one of these tokens succeeds in circumventing `partition_source`'s checks.

I presume code like the following would start compiling on stable once this PR hits stable (edition 2024):

```rs
//! ```
//! #! [feature(rustc_attrs)]
//! #! [rustc_coherence_is_core]
//! impl i32 { fn identity(self) -> Self { self } }
//! fn main() { assert_eq!(1 + 1, 2i32.identity()); }
//! ```
```

We should address that bug really really soon, ideally blocking this PR??

The crate attribute checks should not be textual but syntactic (to account for things like `#/**/!/**/[…]`, too.

**Review by fmease — CHANGES_REQUESTED** [review]

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (fmease) [reply src/librustdoc/doctest.rs:556]: I guess I can be convinced that this needn't block this PR because this obviously a corner case nobody would think about immediately.

Comment (notriddle) [reply src/librustdoc/doctest.rs:556]: If you trick rustdoc into letting you use a feature attribute in a merged doctest, it still won't work, because merged doctests are inside modules, and feature flags aren't allowed in modules.

```text
warning: crate-level attribute should be in the root module
 --> src/lib.rs:7:5
  |
7 |     #! [feature(rustc_attrs)]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_attributes)]` on by default
```

Comment (fmease) [reply src/librustdoc/doctest.rs:556]: Yes, I'm aware of that.

Comment (fmease) [reply src/librustdoc/doctest.rs:556]: The reason it still works for `rustc_attrs` and `test` specifically because the `feature` is also present in the crate root (and the non-crate-root attribute is just a warning):

```rs
#![allow(unused_extern_crates)]
#![allow(internal_features)]
#![feature(test)]
#![feature(rustc_attrs)]
```

Comment (fmease) [reply src/librustdoc/doctest.rs:556]: See the generated crate:

<details>

```rs
#![allow(unused_extern_crates)]
#![allow(internal_features)]
#![feature(test)]
#![feature(rustc_attrs)]

#![allow(unused)]
extern crate test;
mod __doctest_0 {

#! [feature(rustc_attrs)]
#! [rustc_coherence_is_core]
impl i32 { fn identity(self) -> Self { self } }
fn main() { assert_eq!(1 + 1, 2i32.identity()); }
pub const TEST: test::TestDescAndFn = test::TestDescAndFn::new_doctest(
"again.rs - (line 1)", false, "again.rs", 1, false, false,
test::StaticTestFn(
    || {
if let Some(bin_path) = crate::__doctest_mod::doctest_path() {
    test::assert_test_result(crate::__doctest_mod::doctest_runner(bin_path, 0))
} else {
    test::assert_test_result(self::main())
}
},
));
}


mod __doctest_mod {
    use std::sync::OnceLock;
    use std::path::PathBuf;

    pub static BINARY_PATH: OnceLock<PathBuf> = OnceLock::new();
    pub const RUN_OPTION: &str = "RUSTDOC_DOCTEST_RUN_NB_TEST";

    #[allow(unused)]
    pub fn doctest_path() -> Option<&'static PathBuf> {
        self::BINARY_PATH.get()
    }

    #[allow(unused)]
    pub fn doctest_runner(bin: &std::path::Path, test_nb: usize) -> Result<(), String> {
        let out = std::process::Command::new(bin)
            .env(self::RUN_OPTION, test_nb.to_string())
            .args(std::env::args().skip(1).collect::<Vec<_>>())
            .output()
            .expect("failed to run command");
        if !out.status.success() {
            Err(String::from_utf8_lossy(&out.stderr).to_string())
        } else {
            Ok(())
        }
    }
}

#[rustc_main]
fn main() -> std::process::ExitCode {
const TESTS: [test::TestDescAndFn; 1] = [__doctest_0::TEST];
let test_marker = std::ffi::OsStr::new(__doctest_mod::RUN_OPTION);
let test_args = &["rustdoctest".to_string(),];
const ENV_BIN: &'static str = "RUSTDOC_DOCTEST_BIN_PATH";

if let Ok(binary) = std::env::var(ENV_BIN) {
    let _ = crate::__doctest_mod::BINARY_PATH.set(binary.into());
    unsafe { std::env::remove_var(ENV_BIN); }
    return std::process::Termination::report(test::test_main(test_args, Vec::from(TESTS), None));
} else if let Ok(nb_test) = std::env::var(__doctest_mod::RUN_OPTION) {
    if let Ok(nb_test) = nb_test.parse::<usize>() {
        if let Some(test) = TESTS.get(nb_test) {
            if let test::StaticTestFn(f) = test.testfn {
                return std::process::Termination::report(f());
            }
        }
    }
    panic!("Unexpected value for `{}`", __doctest_mod::RUN_OPTION);
}

eprintln!("WARNING: No rustdoc doctest environment variable provided so doctests will be run in the same process");
std::process::Termination::report(test::test_main(test_args, Vec::from(TESTS), None))
}
```

</details>

Comment (notriddle) [reply src/librustdoc/doctest.rs:556]: @fmease Yes, that's a problem.

I've pushed a second commit that should solve this problem by building the test bundle and the test harness as a stable library crate that exports all the main functions, plus a harness with unstable features that runs them). This should make it impossible for a user to accidentally use a nightly-only feature.

I've also added a test case to ensure this.

File: src/librustdoc/doctest.rs [hunk 2]
```diff
@@ -543,85 +549,100 @@ fn run_test(
         .unwrap_or_else(|| rustc_interface::util::rustc_path().expect("found rustc"));
     let mut compiler = wrapped_rustc_command(&rustdoc_options.test_builder_wrappers, rustc_binary);
 
-    compiler.arg(format!("@{}", doctest.global_opts.args_file.display()));
+    let mut compiler_args = vec![];
```
Comment (GuillaumeGomez) [inline src/librustdoc/doctest.rs:552]: Is there a reason to store these arguments in a temporary variable instead of putting them directly in `compiler`?

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (fmease) [reply src/librustdoc/doctest.rs]: > The reason it still works for rustc_attrs and test specifically

Hmmm, I've now done local testing of the original version of this PR and it's possible that I am partially mistaken, it's all so confusing. The example from https://github.com/rust-lang/rust/pull/137899#discussion_r1976734417 might not compile after all on stable even with `RUSTC_BOOTSTRAP=1`? I don't really know. I've tried `RUSTC_BOOTSTRAP=-1 rustdoc +FIRST_COMMIT_ONLY file.rs --edition 2024 --test` (`-1` makes rustc/rustdoc think it's stable) and that still leads to

```
error[E0554]: `#![feature]` may not be used on the nightly release channel
 --> file.rs:2:1
  |
2 | #! [feature(rustc_attrs)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

However, I don't know if `RUSTC_BOOTSTRAP=-1` is a proper replacement for "bootstrap profile == dist" (it that how it works?). I'm flabbergasted as to why that doesn't compile.

---

Still, the following "exploit" does compile (and I'm more than confused what's the difference to the previous code) under `RUSTC_BOOTSTRAP=-1 rustdoc +FIRST_COMMIT_ONLY file.rs --edition 2024 --test`:

```rs
//! ```
//! #! [feature(rustc_attrs)]
//! #[rustc_coinductive] trait Trait {}
//! ```
```

---

In any case, it seems like my original comment still holds in that the first commit is exploitable.

Another less severe example: Assuming `--doctest-compilation-args` is stable (which it isn't yet), this would be another exploit: `RUSTC_BOOTSTRAP=-1 rustdoc +FIRST_COMMIT_ONLY file.rs --edition 2024 --test --doctest-compilation-args -Zfmt-debug=none` (where the `RUSTC_BOOTSTRAP=-1` is just a placeholder for "stable distribution"):

```rs
//! ```
//! #[derive(Debug)] struct Pair;
//! assert!(format!("{Pair:?}").is_empty());
//! ```
```

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (notriddle) [reply src/librustdoc/doctest.rs:552]: Yes, because I'm invoking two compilers.

On https://github.com/rust-lang/rust/pull/137899/files#diff-f30ab1f8c0cc2b3a6b7e5f5d2f731800f01774155f534e2a8851187cad09e9fbR613 I build the doctests themselves.

On https://github.com/rust-lang/rust/pull/137899/files#diff-f30ab1f8c0cc2b3a6b7e5f5d2f731800f01774155f534e2a8851187cad09e9fbR665 I build the doctest runner, which is built with unstable features.

File: src/librustdoc/doctest.rs (hunk 1 above)
Comment (notriddle) [reply src/librustdoc/doctest.rs]: @fmease 

It looks like `#![rustc_coherence_is_core]` is silently ignored when not at the crate root. Which means, if I run run with `--persist-doctests`, the [resulting code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=f1290e6b6f3db9f53d4ea3654f513b28) gets the "cannot define inherent impl outside of core" error.

Comment (jieyouxu) [reply src/librustdoc/doctest.rs]: I don't know the specifics about *this* rustdoc issue, but:

> However, I don't know if `RUSTC_BOOTSTRAP=-1` is a proper replacement for "bootstrap profile == dist" (it that how actual stable distributions of rustc/rustdoc come to life?).

It is not for the same purpose. The dist profile of bootstrap sets additional things. `RUSTC_BOOTSTRAP=-1` is an internal-testing-only flag (I added it mostly to test rustc nightly-gated diagnostics differences) to trick rustc into thinking it is a stable-channel compiler and is not a substitute for dist config.

File: src/librustdoc/doctest.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply src/librustdoc/doctest.rs:552]: Then please add a comment explaining this.

Comment (notriddle) [reply src/librustdoc/doctest.rs:552]: `conmpiler_args` is the common arguments for both compilers. Regular `compiler` builds the tests, while `compiler_runner` builds the test harness.

The difference is the source path, output path, crate-type, and RUSTC_BOOTSTRAP environment variable.

**Review by fmease — APPROVED** [review]
I've gone through all files and tested things locally. This is definitely the approach we should take. Very good idea, thanks!

The code constructing the compiler invocations is messier than I'd hoped (out of necessity!). There's definitely room for cleanups and refactoring which can be done in follow-up PRs. I must say — only having gone through the changes once — I'm not 100% confident yet I didn't miss potential issues with the way flags are passed since it's all very delicate (cf. the string-based extraction of transitive deps from `--extern` (don't we need to ~~"import"~~ adjust transitives `-L`s too?)).

I might want to go over it again but generally +1 from me. (The last 4 commits should be squashed into one.)

---

[We likely want to nominate this for stable backport too and force a point release](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/A.20point.20release.20for.20the.20doctest.20merging.20bug.3F). Backports should generally be small and low risk (since it obviously prevents real users from testing the changes "outside of production") which this PR isn't I'd say. So we might want to think about alternative strategies (like only shipping the first commit for a release???).

File: src/librustdoc/doctest.rs [hunk 3]
```diff
@@ -630,8 +653,63 @@ fn run_test(
...
+        // compile-fail tests never get merged, so this should always pass
         let status = child.wait().expect("Failed to wait");
+
+        // the actual test runner is a separate component, built with nightly-only features;
+        // build it now
+        let runner_input_file = doctest.path_for_merged_doctest_runner();
+
+        let mut runner_compiler =
+            wrapped_rustc_command(&rustdoc_options.test_builder_wrappers, rustc_binary);
+        runner_compiler.env("RUSTC_BOOTSTRAP", "1");
```
Comment (fmease) [inline src/librustdoc/doctest.rs:666]: This now missing the comment that was present in the first commit

Comment (notriddle) [reply src/librustdoc/doctest.rs:666]: Good catch.

**Comment by notriddle** [comment]
> don't we need to "import" transitives -Ls too?)

`compiler_args` should already have the -Ls for transitive deps, otherwise building doctests wouldn't have worked in the first place.

We need to generate -Ls for direct deps because the direct deps of the test bundle become transitive deps of the runner.

File: src/librustdoc/doctest.rs [hunk 4]
```diff
@@ -630,8 +653,65 @@ fn run_test(
...
+                // Direct dependencies of the tests themselves are
+                // indirect dependencies of the test runner.
+                // They need to be in the library search path.
+                let dir = Path::new(path)
+                    .parent()
+                    .filter(|x| x.components().count() > 0)
+                    .unwrap_or(Path::new("."));
+                runner_compiler.arg("-L").arg(dir);
+            }
+        }
```
Comment (fmease) [inline src/librustdoc/doctest.rs:686]: Is this really necessary? Did you have a concrete case where this was necessary?
Locally I've experimented with the consequences of removing it, couldn't find any problems and all tests pass without it, too. It's possible that I missed something.

Everything seems to work out just fine without this extra logic because any `--extern`s and `-L`s (most likely `-Ldependency=`s from Cargo) passed to rustdoc for the "overarching host crate" (the crate containing the doctest) get stuffed into the args file `rustdoc-cfgs` which we use for compiling both the bundle and the runner.

---

And if the (non-Cargo) user passes too few `-L` flags to the host crate, then the latter wouldn't even compile and we wouldn't even reach this function `run_test`. Example:

`directory/foreign.rs` (`rustc directory/foreign.rs --crate-type=lib --out-dir directory/`):

```rs
pub const VALUE: bool = true;
```

`file.rs`:

```rs
//! ```
//! assert!(foreign::VALUE);
//! ```
```

* `rustdoc file.rs --edition 2024 --test --extern foreign=directory/libforeign.rlib` passes just fine without this loop over `extern_strs` because the argsfile (shared by the bundle & the runner compiler) contains `--extern foreign=directory/libforeign.rlib`. This loop would've just added `-Ldirectory` which is unnecessary.
* (`rustdoc file.rs --edition 2024 --test --extern foreign -Ldependency` also passes because the argsfile contains `-Ldirectory` and `--extern=foreign` but ofc that isn't relevant to this loop as it skips such externs)
* if want to only add `foreign` to the doctest, not the host crate: `rustdoc file.rs --edition 2024 --test -Zunstable-options --doctest-compilation-args '--extern foreign=directory/libforeign.rlib'`: This also passes just fine because of the argsfile and it obviously doesn't trigger this loop at all

Comment (fmease) [reply src/librustdoc/doctest.rs:686]: Similarly for more complex crate graphs (`a.rs` <- `b.rs` <- `c.rs`(with doctest)):

1. `rustc directory/a.rs --crate-type=lib --out-dir directory`
2. `rustc directory/b.rs --crate-type=lib --edition 2018 --extern a -Ldirectory` (or similar)
3. finally
  1. `rustdoc c.rs --edition 2024 --test --extern b=directory/libb.rlib -Ldependency=directory` also passes without this loop which would've added `-Ldirectory`
  2. (similarly, `rustdoc c.rs --edition 2024 --test -Zunstable-options --doctest-compilation-args '--extern foreign=separate/libforeign.rlib -Ldependency=separate'`)

**Comment by fmease** [comment]
> We need to generate -Ls for direct deps because the direct deps of the test bundle become transitive deps of the runner.

I don't think this is necessary as written up in https://github.com/rust-lang/rust/pull/137899#discussion_r1986463750. However, I won't block this PR on my concern (which could also be unjustified). I'm also a bit wary of generating extra `-L…` instead of `-Ldependency=…` (the latter is "safer"/stricter as it only permits transitive deps which is what we want I guess) but I don't actually know if this can lead to any compilation failures down the line (due to ambiguities?).

**Comment by fmease** [comment]
I've rebased and fixed a small typo (`#[feature]` to `#![feature]` in a comment).

**Comment by fmease** [comment]
@bors r=fmease,GuillaumeGomez rollup=always p=6
p=6: Fixes a P-critical issue.

**Comment by fmease** [comment]
Beta and stable backport accepted as per Zulip polls:

1. [#t-rustdoc > beta-nominated: #137899 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/beta-nominated.3A.20.23137899/near/503324233)
2. [#t-rustdoc > stable-nominated: #137899 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/stable-nominated.3A.20.23137899/near/503326446)

In both cases, out of 8 (7 active) members, 4 members voted for, 0 against.
