### PR TITLE
Show types of all args when missing args

### LINKED ISSUE #33649: Insufficient arguments error E0061 & E0050 would be more helpful if it printed what arguments are needed
When I call a function with insufficient arguments, rustc just says the number of arguments is wrong. 

> <anon>:4:5: 4:26 error: this function takes 1 parameter but 0 parameters were supplied [E0061]
> <anon>:4     std::fs::File::open();
>              ^~~~~~~~~~~~~~~~~~~~~

This would be much more helpful if it said which arguments, and what they are, e.g.:

> error: The `path` argument was not supplied to the `open` function

or at least show the funcition definition in a note:

> <anon>:4:5: 4:26 error: this function takes 1 parameter but 0 parameters were supplied [E0061]
> <anon>:4     std::fs::File::open();
> note: `fn open<P: AsRef<Path>>(path: P) -> Result<File>`

Similar problem applies to E0050 ("error: method `foo` has 1 parameter but the declaration in trait `bar` has 2").

----

rustc 1.10.0-nightly (2b79e05a0 2016-05-13)

### PR DESCRIPTION
**Pull request by estebank**
When there're missing arguments in a function call, present a list of
all the expected types:

``` rust
fn main() {
    t("");
}

fn t(a: &str, x: String) {}
```

``` bash
% rustc file.rs
file.rs:3:5: 2:8 error: this function takes 2 parameters but 0
parameters were supplied [E0061]
file.rs:3     t();
              ^~~
file.rs:3:5: 2:8 help: run `rustc --explain E0061` to see a detailed explanation
file.rs:3:5: 2:8 note: the following parameter types were expected: &str, std::string::String
error: aborting due to previous error
```

Fixes #33649

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -2418,6 +2418,14 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
                             args.len(),
                             if args.len() == 1 {" was"} else {"s were"});
+                        let input_types = fn_inputs.iter().map(|i| format!("{:?}", i))
+                            .collect::<Vec<String>>();
+                        if input_types.len() > 0 {
+                            tcx.sess.span_note_without_error(sp,
+                                &format!("the following parameter type{} expected: {}",
+                                    if expected_arg_count == 1 {" was"} else {"s were"},
+                                    input_types.join(", ")));
+                        }
```
Comment (oli-obk) [inline src/librustc_typeck/check/mod.rs]: This should probably be in its own function to reduce code repetition (this would allow `E0057`, `E0060` and `E0061` to be merged into a single error number).

Also it should be using the error builders, so you can attach the note to the main error.

Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Done!

**Comment by oli-obk** [comment]
Sorry ^^ I'm not a reviewer

**Comment by estebank** [comment]
@oli-obk not a problem :)

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -2407,30 +2407,46 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+            let input_types = fn_inputs.iter().map(|i| format!("{:?}", i)).collect::<Vec<String>>();
+            if input_types.len() > 0 {
+                err.note(&format!("the following parameter type{} expected: {}",
+                        if expected_count == 1 {" was"} else {"s were"},
+                        input_types.join(", ")));
+            }
+            err.emit();
+        }
+
+
```
Comment (jseyfried) [inline src/librustc_typeck/check/mod.rs]: nit: just one newline here would be more idiomatic

File: src/librustc_typeck/check/mod.rs [hunk 3]
```diff
@@ -2407,30 +2407,46 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                } else {
+                    expected_arg_tys = match expected_arg_tys.get(0) {
+                        Some(&ty) => match ty.sty {
+                            ty::TyTuple(ref tys) => &tys,
+                            _ => &[]
+                        },
+                        None => &[]
+                    };
+                    arg_types.to_vec()
+                },
```
Comment (jseyfried) [inline src/librustc_typeck/check/mod.rs]: nit: the following would more idiomatic
```rust
                ty::TyTuple(arg_types) if arg_types.len() != args.len() => {
                    ...
                },
                ty::TyTuple(arg_types) => {
                    ...
                },
```

File: src/test/compile-fail/issue-18819.rs [hunk 4]
```diff
@@ -24,4 +24,5 @@ fn print_x(_: &Foo<Item=bool>, extra: &str) {
 
 fn main() {
     print_x(X);  //~error this function takes 2 parameters but 1 parameter was supplied
+    //~^ NOTE the following parameter types were expected
```
Comment (jseyfried) [inline src/test/compile-fail/issue-18819.rs]: Could you add the expected types to one of these tests?

Comment (estebank) [inline src/test/compile-fail/issue-18819.rs]: Done

File: src/librustc_typeck/check/mod.rs (hunk 3 above)
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Done, I completely forgot about this being possible.

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (estebank) [inline src/librustc_typeck/check/mod.rs]: Done.

**Comment by jseyfried** [comment]
Thanks! @bors r+
