### PR TITLE
fix(rustdoc): always use a channel when linking to doc.rust-lang.org

### LINKED ISSUE #131971: rustdoc should link to its current version of the rustdoc book
currently, rustdoc just links to https://doc.rust-lang.org/rustdoc/

this could lead to confusion for old crates on docs.rs when someone tries to use a new feature and it doesn't work.

perhaps, rustdoc 1.80.1 should link to https://doc.rust-lang.org/1.80.1/rustdoc/ and other versions should link to their matching documentation...

### PR DESCRIPTION
**Pull request by poliorcetics**
Closes #131971

I manually checked the resulting links

One issue is that this will create `nightly/...` links in places that formerly linked to stable, is that ok ? (the `slice` and `array` links in the search help notably)

### CODE REVIEW

**Review by camelid — APPROVED** [review]
Makes sense to me. r=me with CI fixed (just tidy line-length errors)

**Comment by GuillaumeGomez** [comment]
I'm not sure it's the right fix: currently it's only targeting the same channel whereas the issue is about the same version as rustdoc when the doc is generated.

**Comment by camelid** [comment]
> I'm not sure it's the right fix: currently it's only targeting the same channel whereas the issue is about the same version as rustdoc when the doc is generated.

Sure, this is more of an existing limitation of `DOC_RUST_LANG_ORG_CHANNEL` though, right? We could just change it to use the `1.x.x` version instead of `stable` to resolve your concern right?

**Comment by GuillaumeGomez** [comment]
Not sure... I suppose it could work, but on nightly, the item we're targeting might not be there when the current version is release 12 weeks later. Tricky problem.

**Comment by camelid** [comment]
> Not sure... I suppose it could work, but on nightly, the item we're targeting might not be there when the current version is release 12 weeks later. Tricky problem.

I'm a little confused what the issue is. I'm pretty sure this PR is a strict improvement over the status quo, since we will match the version in more cases than before. In any case, these are only for a few custom links to things that don't change that much, like the `slice` primitive. It's not going to be going away.

**Comment by GuillaumeGomez** [comment]
Yeah, maybe you're right. But in any case, it doesn't solve the issue which wants the version and not the channel. I'm fine merging as is but it's not the fix asked in the issue.

**Comment by camelid** [comment]
@GuillaumeGomez why did the original PR introduce `DOC_RUST_LANG_ORG_CHANNEL` in the first place? Should we just get rid of it and always use the Rustdoc version (or `beta`/`nightly` if it's an unstable version) instead?

**Comment by GuillaumeGomez** [comment]
I think using a version unless it's `beta`/`nightly` would be the correct fix.

**Comment by poliorcetics** [comment]
Isn't that already being done: https://github.com/rust-lang/rust/blob/336209eef13882bd1e211b24779584cb7ef911eb/src/bootstrap/src/core/builder/mod.rs#L1185-L1195 ?

```rust
    pub fn doc_rust_lang_org_channel(&self) -> String {
        let channel = match &*self.config.channel {
            "stable" => &self.version,
            "beta" => "beta",
            "nightly" | "dev" => "nightly",
            // custom build of rustdoc maybe? link to the latest stable docs just in case
            _ => "stable",
        };

        format!("https://doc.rust-lang.org/{channel}")
    }
```

**Comment by camelid** [comment]
@poliorcetics you're right, and I just confirmed by looking at the rendering for existing uses of the constant. Guillaume and I must've gotten confused (the name of the constant maybe could be improved 😅).

Can you fix the tidy errors so I can approve?

**Comment by GuillaumeGomez** [comment]
And maybe the name of the constant too please? :3

**Comment by camelid** [comment]
Yeah, let's do `DOC_RUST_LANG_ORG_VERSION`.

File: src/librustdoc/clean/utils.rs [hunk 1]
```diff
@@ -589,9 +589,9 @@ pub(crate) fn attrs_have_doc_flag<'a>(
 /// so that the channel is consistent.
 ///
 /// Set by `bootstrap::Builder::doc_rust_lang_org_channel` in order to keep tests passing on beta/stable.
-pub(crate) const DOC_RUST_LANG_ORG_CHANNEL: &str = env!("DOC_RUST_LANG_ORG_CHANNEL");
+pub(crate) const DOC_RUST_LANG_ORG_VERSION: &str = env!("DOC_RUST_LANG_ORG_VERSION");
 pub(crate) static DOC_CHANNEL: Lazy<&'static str> =
```
Comment (camelid) [inline src/librustdoc/clean/utils.rs:593]: Can you rename this to `RUSTDOC_VERSION` too? For consistency with the above, but not `DOC_VERSION` because it could be confused with the current crate's version.

File: src/librustdoc/html/static/js/main.js [hunk 2]
```diff
@@ -1358,10 +1358,10 @@ function preLoadCss(cssUrl) {
 
     function buildHelpMenu() {
         const book_info = document.createElement("span");
-        const channel = getVar("channel");
+        const channel = `https://doc.rust-lang.org/${getVar("channel")}`;
```
Comment (camelid) [inline src/librustdoc/html/static/js/main.js:1361]: This should be called `drloChannel` or something like that instead.

File: src/librustdoc/html/static/js/search.js [hunk 3]
```diff
@@ -4408,17 +4408,18 @@ ${item.displayPath}<span class="${type}">${name}</span>\
             }
         });
     } else if (query.error === null) {
+        const channel = `https://doc.rust-lang.org/${getVar("channel")}`;
```
Comment (camelid) [inline src/librustdoc/html/static/js/search.js:4411]: ditto

File: src/librustdoc/html/static/js/main.js [hunk 4]
```diff
@@ -1392,10 +1392,10 @@ href="https://doc.rust-lang.org/${channel}/rustdoc/read-documentation/search.htm
              <code>-&gt; vec</code> or <code>String, enum:Cow -&gt; bool</code>)",
             "You can look for items with an exact name by putting double quotes around \
              your request: <code>\"string\"</code>",
-             "Look for functions that accept or return \
-              <a href=\"https://doc.rust-lang.org/std/primitive.slice.html\">slices</a> and \
-              <a href=\"https://doc.rust-lang.org/std/primitive.array.html\">arrays</a> by writing \
-              square brackets (e.g., <code>-&gt; [u8]</code> or <code>[] -&gt; Option</code>)",
+             `Look for functions that accept or return \
+              <a href=\"${drloChannel}/std/primitive.slice.html\">slices</a> and \
```
Comment (camelid) [inline src/librustdoc/html/static/js/main.js:1396]: The CI error is talking about cases like there. Before it used `"` for the string, so the literal `"` in the HTML had to be escaped. Now you're using ``` ` ``` for the string, so the literal `"` does not need escaping -- and the linter doesn't like that it still is escaped.

There are several other cases elsewhere in this file and the other too.

File: src/librustdoc/html/static/js/search.js [hunk 5]
```diff
@@ -4408,17 +4408,18 @@ ${item.displayPath}<span class="${type}">${name}</span>\
             }
         });
     } else if (query.error === null) {
+        const dlroChannel = `https://doc.rust-lang.org/${getVar("channel")}`;
```
Comment (camelid) [inline src/librustdoc/html/static/js/search.js:4411]: To fix the CI error here, you need to add getVar to the globals list at the top of the file. It should be available to this file. cc @GuillaumeGomez  -- correct me if I'm wrong

**Comment by camelid** [comment]
@poliorcetics just a gentle ping. This is so close to being ready. Pretty sure you just need to fix the redundant escape sequences issue and then I can r+.

**Review by camelid — APPROVED** [review]
Thanks!
