### PR TITLE
Fix auto trait impl rustdoc ice

### LINKED ISSUE #48463: rustdoc ICE
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.25.0-nightly (b1f8e6fb0 2018-02-22) running on x86_64-unknown-linux-gnu
error: Could not document `glib`.
```

I'll check where we use an `unwrap`.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #48463.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -3428,7 +3428,9 @@ fn build_deref_target_impls(cx: &DocContext,
         let primitive = match *target {
             ResolvedPath { did, .. } if did.is_local() => continue,
             ResolvedPath { did, .. } => {
-                ret.extend(inline::build_impls(cx, did, true));
+                // We set the last parameter to false to avoid looking for auto-impls for traits
+                // and therefore avoid an ICE.
```
Comment (QuietMisdreavus) [inline src/librustdoc/clean/mod.rs]: This is only part of the story. The real reason we should pass `false` here is because auto-traits don't propagate through `Deref` anyway, so we shouldn't be synthesizing impls for them.

File: src/test/rustdoc/auto-impl-for-trait.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
+// Copyright 2018 The Rust Project Developers. See the COPYRIGHT
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
```
Comment (QuietMisdreavus) [inline src/test/rustdoc/auto-impl-for-trait.rs]: Can you add a comment to this test explaining why it's here, or at least referencing the issue?

**Review by QuietMisdreavus — COMMENTED** [review]
Couple of nits about comments `>_>`

**Comment by GuillaumeGomez** [comment]
Updated.
