### PR TITLE
Fix ?Sized where bound not being displayed at the correct place

### LINKED ISSUE #46726: Rustdoc renders `where Q: ?Sized` incorrectly
Code:

```rust
pub fn seek_by<Q, F>(&mut self, mut f: F) -> bool
where
    K: Borrow<Q>,
    Q: ?Sized,
    F: FnMut(&Q) -> cmp::Ordering,
{
    // ...
}
```

Rustdoc:

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #46726.

r? @QuietMisdreavus

### CODE REVIEW

File: src/librustdoc/clean/mod.rs [hunk 1]
```diff
@@ -1190,16 +1190,37 @@ impl<'tcx> Clean<Type> for ty::ProjectionTy<'tcx> {
...
+        // predicates. The point in here is to move the bounds definitions from type params
+        // to where predicates when such cases occur.
+        for where_pred in &mut g.where_predicates {
+            match *where_pred {
+                WherePredicate::BoundPredicate { ty: Generic(ref name), ref mut bounds } => {
+                    if bounds.is_empty() {
+                        for type_params in &mut g.type_params {
+                            if &type_params.name == name {
+                                *bounds = type_params.bounds.clone();
+                                type_params.bounds.clear();
```
Comment (kennytm) [inline src/librustdoc/clean/mod.rs]: You could simply move the ownership away, either with

```rust
*bounds = mem::replace(&mut type_params.bounds, HirVec::new())
```

or, since `bounds.is_empty()`,

```
mem::swap(&mut bounds, &mut type_params.bounds);
```

Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs]: Oh nice!

**Comment by GuillaumeGomez** [comment]
Updated.
