### PR TITLE
Structurally normalize in range pattern checking in HIR typeck

### LINKED ISSUE #200: enumoid regression: not structurally normalizing type in hir typeck pattern checking
https://crater-reports.s3.amazonaws.com/pr-133502-11/try%2328f13ad7c79d80decb5a3d54595a8b4105f397a3/reg/enumoid-0.4.0/log.txt

minimal:

```rust
trait Foo {
    type Bar;
}

impl Foo for () {
    type Bar = i32;
}

fn main() {
    const X: <() as Foo>::Bar = 0;

    match 0 {
        X..=X => {}
        _ => {}
    }
}
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/200

r? lcnr

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/pat.rs [hunk 1]
```diff
@@ -866,6 +866,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 // be peeled to `str` while ty here is still `&str`, if we don't
                 // err early here, a rather confusing unification error will be
                 // emitted instead).
+                let ty = self.structurally_resolve_type(expr.span, ty);
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/pat.rs:869]: do we need to do the same in `fn calc_adjust_mode` given that this also structurally matches on `check_pat_expr_unadjusted`?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/pat.rs:869]: possibly
