### PR TITLE
Don't produce debug information for compiler-introduced-vars when desugaring assignments.

### LINKED ISSUE #138198: LLVM "conflicting locations for variable" assertions
> The "conflicting locations for variable" bug might still be around in rust-1.84 and rust-1.85.  A bunch of us on Gentoo are consistently hitting this same SIGABORT when compiling firefox with newer rust installs.  It's always seemingly when running the exact same build step too, so it appears to be 100% reproducible.
> 
> I managed to get a stacktrace here, not sure if this might explain what we're seeing more:
> 
> https://bugs.gentoo.org/949280#c13
> 
> Rust is a bit outside of my realm of expertise, but if you'd like us to try running anything else on the workdir right after it fails, we'll try and offer any evidence that we can. 

 _Originally posted by @yuri-sevatz in [#131944](https://github.com/rust-lang/rust/issues/131944#issuecomment-2704946264)_

### PR DESCRIPTION
**Pull request by khuey**
An assignment such as

(a, b) = (b, c);

desugars to the HIR

{ let (lhs, lhs) = (b, c); a = lhs; b = lhs; };

The repeated `lhs` leads to multiple Locals assigned to the same DILocalVariable. Rather than attempting to fix that, get rid of the debug info for these bindings that don't even exist in the program to begin with.

Fixes #138198

r? @jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
This heuristic makes sense to me, thanks

File: compiler/rustc_mir_build/src/builder/matches/mod.rs [hunk 1]
```diff
@@ -2815,18 +2817,42 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
     }
+
+    /// Some bindings are introduced when producing HIR from the AST and don't
+    /// actually exist in the source. Skip producing debug info for those when
+    /// we can recognize them.
+    fn should_emit_debug_info_for_binding(&self, name: Symbol, var_id: LocalVarId) -> bool {
+        // For now we only recognize the output of desugaring assigns.
+        if name != sym::lhs {
+            return true;
+        }
```
Comment (jieyouxu) [inline compiler/rustc_mir_build/src/builder/matches/mod.rs:2844]: I do wonder if we are synthesizing other constructs that are not present in the surface syntax, but I can't immediately think of other cases. If they crop up, well this is a good place to centralize the handling.

Comment (khuey) [reply compiler/rustc_mir_build/src/builder/matches/mod.rs:2844]: I also couldn't think of a case where we unambiguously want to remove the debug info today, but I expect they will crop up eventually.
