### PR TITLE
Detect likely `.` -> `..` typo in method calls

### LINKED ISSUE #65015: Point at duplicated dot in method access
[The following incorrect code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=afabf424606627e723a6faed1bcde8e9)

```rust
struct Type {
    option: Option<Vec<u8>>
}

impl Type {
    fn method(&self) -> Option<Vec<u8>> {
        self.option..as_ref().map(|x| x)
    }
}

fn main() {
    let _ = Type { option: None }.method();
}
```

```
error[E0425]: cannot find function `as_ref` in this scope
 --> src/main.rs:7:22
  |
7 |         self.option..as_ref().map(|x| x)
  |                      ^^^^^^ not found in this scope

error[E0308]: mismatched types
 --> src/main.rs:7:9
  |
6 |     fn method(&self) -> Option<Vec<u8>> {
  |                         --------------- expected `std::option::Option<std::vec::Vec<u8>>` because of return type
7 |         self.option..as_ref().map(|x| x)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found struct `std::ops::Range`
  |
  = note: expected type `std::option::Option<_>`
             found type `std::ops::Range<std::option::Option<_>>`
```

has a typo where two dots where written where one for method access was meant. It is not made clear enough in the output due to complaining about finding `Range` but not pointing at the two dots that caused the range to be there.

### PR DESCRIPTION
**Pull request by estebank**
Fix #65015.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 1]
```diff
@@ -1432,4 +1432,46 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        }
+        if let ty::Adt(adt, _) = expected_ty.kind()
+            && self.tcx.lang_items().range_struct() == Some(adt.did())
+        {
+            return;
+        }
+        err.span_suggestion_verbose(
+            start.expr.span.between(end.expr.span),
+            "you might have meant to write a method call instead of a range",
+            ".".to_string(),
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:1473]: nit: this `to_string` is no longer needed

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 2]
```diff
@@ -1604,6 +1604,7 @@ impl<'tcx, 'exprs, E: AsCoercionSite> CoerceMany<'tcx, 'exprs, E> {
                         None,
                         Some(coercion_error),
                     );
+                    fcx.check_for_range_as_method_call(&mut err, expr, found, expected);
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/coercion.rs:1607]: hm, any reason why this isn't living inside `emit_coerce_suggestions` with the rest of the suggestions?

File: compiler/rustc_hir_typeck/src/demand.rs [hunk 3]
```diff
@@ -1432,4 +1432,46 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            [start, end],
+            _,
+        ) = expr.kind else { return; };
+        let mut expr = end.expr;
+        while let hir::ExprKind::MethodCall(_, rcvr, ..) = expr.kind {
+            // Getting to the root receiver and asserting it is a fn call let's us ignore cases in
+            // `src/test/ui/methods/issues/issue-90315.stderr`.
+            expr = rcvr;
+        }
+        let hir::ExprKind::Call(..) = expr.kind else { return; };
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/demand.rs:1460]: Ideally we'd check that the lhs of the `..` [has a method](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/fn_ctxt/struct.FnCtxt.html#method.probe_for_name) with the name of this call ident. 

You should at least be checking that this call has only one path segment though, since `a..b::c()` is going to be an eroneous suggestion, right?

File: compiler/rustc_resolve/src/late.rs [hunk 4]
```diff
@@ -3341,8 +3341,20 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
 
                 let def_id = this.parent_scope.module.nearest_parent_mod();
                 let instead = res.is_some();
-                let suggestion =
-                    if res.is_none() { this.report_missing_type_error(path) } else { None };
+                let suggestion = if let Some((start, end)) = this.diagnostic_metadata.in_range
+                    && path[0].ident.span.lo() == end.span.lo()
```
Comment (compiler-errors) [inline compiler/rustc_resolve/src/late.rs:3345]: I didn't look too much into this, but does this check that this is a method?

We should also probably double check this is a path with one segment, right?

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/coercion.rs:1607]: Because it otherwise also triggers for the case of `Struct { field ..Default::default() }` when the problem is a missing comma.

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_resolve/src/late.rs:3345]: It doesn't, but during resolve we don't have enough data to do that (although now that I'm tracking `start` I *might* be able to cobble something together).

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 2 above)
Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1607]: hm -- I'd rather suppress that specifically (checking that the expr isn't a field assignment), because I'm suspicious of other places where we're failing to make this suggestion because they don't go through `CoerceMany`

Comment (estebank) [reply compiler/rustc_hir_typeck/src/coercion.rs:1607]: So have an explicit check of the `hir().parent(expr.hir_id)` to see if the current range happens to be the last field in a struct literal? It can be done.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/coercion.rs:1607]: either last field, or a field at all, depending on how particular you want to implement it -- i don't have a strong opinion either way, if you're able to do it.

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_resolve/src/late.rs:3345]: I'm comfortable with the weasel wording on this one suggestion: it is a guess, and we'd have to perform more extensive surgery on resolve to track more state, and it is already quite a beast.

Comment (compiler-errors) [reply compiler/rustc_resolve/src/late.rs:3345]: My only concern is that this triggers when we have any resolution error on the RHS of a range, e.g.

```rust
fn foo() {
  a..b;
}
```

Results in:
```
error[E0425]: cannot find value `a` in this scope
 --> /home/ubuntu/test.rs:2:5
  |
2 |     a..b;
  |     ^ not found in this scope

error[E0425]: cannot find value `b` in this scope
 --> /home/ubuntu/test.rs:2:8
  |
2 |     a..b;
  |        ^ not found in this scope
  |
help: you might have meant to write a method call instead of a range
  |
2 -     a..b;
2 +     a.b;
```

I'd much prefer if the wording was made to not mention methods in specific, but focus on the `.` itself -- something like "you might've meant to write the `.` operator instead of a range"?

**Comment by compiler-errors** [comment]
r=me -- preferably with the resolve diagnostic's wording made more generic, but I guess I won't hold you to it

File: compiler/rustc_resolve/src/late.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_resolve/src/late.rs:3345]: What do you think of "you might have meant to write `.` instead of `..`"

Comment (compiler-errors) [reply compiler/rustc_resolve/src/late.rs:3345]: Yeah, that works fine. 

Just would prefer it to not mention "methods" unless we can verify it's actually a method, but since this code is in resolve, I totally understand how that's hard, haha.
