### PR TITLE
CTFE/Miri engine Pointer type overhaul

### LINKED ISSUE #841: Make force_ptr a total operation, and ptr-to-int-casts not require extra machine state
Currently, `force_bits` is a total operation in the sense that it will never go wrong in Miri (it can fail in CTFE though), but `force_ptr` can fail. That is very annoying, it means that we have to call `force_ptr` at *just the right spot* or we'll either causes errors in well-behaved code by converting too early, or re-do the conversion all the time because we do it too late. (See https://github.com/rust-lang/rust/pull/62441 for some very careful `force_ptr` placement.)

I think it might be a good idea to make `force_ptr` never fail. The way this could be done is by designating a particular `AllocId` as representing the "integer allocation" and having base address 0, so that a pointer with offset `o` is equal to the integer `o`. This would mean that every pointer-sized value has two equivalent representations (returned by `force_bits` and `force_ptr`, respectively) -- which is maybe suboptimal, but IMO it is better than the current situation where only *some* pointer-sized values have two representations.

Potentially, that would also let us use `Pointer` instead of `Scalar` in `MemPlace`, simplifying (I think) lots of code. However, that would mean even CTFE has two different representations for the same value. But given that the engine will have to handle that anyway, I am not sure if it is a problem.

@oli-obk will recognize this as basically bringing back the "ZST allocation" or whatever it used to be called. It was a mess back then, but I think removing it only helped because it meant we had a canonical representation for every value -- a property we already lost with intptrcast.

What do you think?

**Current proposal:** https://github.com/rust-lang/miri/issues/841#issuecomment-516584650

### PR DESCRIPTION
**Pull request by RalfJung**
This fixes the long-standing problem that we are using `Scalar` as a type to represent pointers that might be integer values (since they point to a ZST). The main problem is that with int-to-ptr casts, there are multiple ways to represent the same pointer as a `Scalar` and it is unclear if "normalization" (i.e., the cast) already happened or not. This leads to ugly methods like `force_mplace_ptr` and `force_op_ptr`.
Another problem this solves is that in Miri, it would make a lot more sense to have the `Pointer::offset` field represent the full absolute address (instead of being relative to the `AllocId`). This means we can do ptr-to-int casts without access to any machine state, and it means that the overflow checks on pointer arithmetic are (finally!) accurate.

To solve this, the `Pointer` type is made entirely parametric over the provenance, so that we can use `Pointer<AllocId>` inside `Scalar` but use `Pointer<Option<AllocId>>` when accessing memory (where `None` represents the case that we could not figure out an `AllocId`; in that case the `offset` is an absolute address). Moreover, the `Provenance` trait determines if a pointer with a given provenance can be cast to an integer by simply dropping the provenance.

I hope this can be read commit-by-commit, but the first commit does the bulk of the work. It introduces some FIXMEs that are resolved later.
Fixes https://github.com/rust-lang/miri/issues/841
Miri PR: https://github.com/rust-lang/miri/pull/1851
r? @oli-obk

### CODE REVIEW

File: compiler/rustc_middle/src/ty/print/pretty.rs [hunk 1]
```diff
@@ -1068,8 +1069,8 @@ pub trait PrettyPrinter<'tcx>:
             ty::Char if char::try_from(int).is_ok() => {
                 p!(write("{:?}", char::try_from(int).unwrap()))
             }
-            // Raw pointers
-            ty::RawPtr(_) | ty::FnPtr(_) => {
+            // Pointer types
+            ty::Ref(..) | ty::RawPtr(_) | ty::FnPtr(_) => {
```
Comment (oli-obk) [inline compiler/rustc_middle/src/ty/print/pretty.rs:1073]: can we really end up here for references? Integer references should only exists for ZSTs, and we shouldn't be printing the address in that case.

File: compiler/rustc_mir/src/const_eval/eval_queries.rs [hunk 2]
```diff
@@ -162,14 +162,15 @@ pub(super) fn op_to_const<'tcx>(
...
                 ScalarMaybeUninit::Scalar(s) => ConstValue::Scalar(s),
-                ScalarMaybeUninit::Uninit => to_const_value(&op.assert_mem_place(ecx)),
+                ScalarMaybeUninit::Uninit => to_const_value(&op.assert_mem_place()),
             },
             Immediate::ScalarPair(a, b) => {
-                let (data, start) = match a.check_init().unwrap() {
-                    Scalar::Ptr(ptr) => {
-                        (ecx.tcx.global_alloc(ptr.alloc_id).unwrap_memory(), ptr.offset.bytes())
+                // We know `offset` is relative to the allocation, so we can use `into_parts`.
+                let (data, start) = match ecx.scalar_to_ptr(a.check_init().unwrap()).into_parts() {
```
Comment (oli-obk) [inline compiler/rustc_mir/src/const_eval/eval_queries.rs:169]: could into_parts assert this flag internally? Or does miri also have a need for it?

File: compiler/rustc_middle/src/ty/print/pretty.rs (hunk 1 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/ty/print/pretty.rs:1073]: I am honestly not sure, but in my experience in printing code it's good to have reasonable code paths even for currently impossible cases -- makes debugging a lot easier.

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 3]
```diff
@@ -83,55 +83,74 @@ pub trait PointerArithmetic: HasDataLayout {
...
+    /// "Erasing" a tag converts it to the default tag type if possible. Used only for formatting purposes!
+    fn erase_for_fmt(self) -> AllocId;
+}
+
+impl Provenance for AllocId {
+    // With the `AllocId` as provenance, the `offset` is interpreted *relative to the allocation*,
+    // so ptr-to-int casts are not possible (since we do not know the global physical offset).
+    const OFFSET_IS_ADDR: bool = false;
+
+    fn fmt(ptr: &Pointer<Self>, f: &mut fmt::Formatter<'_>) -> fmt::Result {
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs:109]: Why is there a custom formatting function? Couldn't this be an impl on `Pointer<AllocId>` directly, allowing all aggregates containing `Pointer` to derive their `Debug` impls?

File: compiler/rustc_middle/src/mir/interpret/mod.rs [hunk 4]
```diff
@@ -177,7 +177,7 @@ pub enum LitToConstError {
 }
 
 #[derive(Copy, Clone, Eq, Hash, Ord, PartialEq, PartialOrd)]
-pub struct AllocId(pub u64);
+pub struct AllocId(pub NonZeroU64);
```
Comment (oli-obk) [inline compiler/rustc_middle/src/mir/interpret/mod.rs:180]: maybe change the debug impl to print `id - 1` to reduce the test noise in the PR

**Comment by oli-obk** [comment]
The design lgtm in general, I'm mainly unhappy about the roundabout formatting stuff that requires one to essentially write the derived impl by hand.

File: compiler/rustc_middle/src/mir/interpret/mod.rs (hunk 4 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/mod.rs:180]: That seems awfully confusing for debugging...

**Comment by RalfJung** [comment]
I pushed some more commits, mostly because changes were needed to get Miri to work again.

One change is rather unfortunate: I had to give the `init_allocation_extra` machine hook access to `&Memory` (and not just `&MemoryExtra`, and this necessitated a less optimal implementation of `Memory::get_mut`. With a better borrow checker we could recover the original cost for the happy case (where the allocation is in the local memory), but there'd still be extra cost for when we have to reach for the global memory. I also hat to make `MonoHashMap::get` in Miri less efficient to avoid `RefCell` panics.
The reason Miri needs `&Memory` is that it needs to query the size and alignment of allocations. So one possible alternative would be to make `dead_alloc_map` actually contain *all* allocations, not just the dead ones; and to give the `init_allocation_extra` machine hook access to that map as well. This would be a rather gross hack since Rust does not have good support for representing "a struct with some of its fields borrowed away".

An extremely coarse benchmark (`time ./miri test pass`) showed no regressions in Miri performance; let's make sure there is no rustc regression either:
@bors try
@rust-timer queue

File: compiler/rustc_middle/src/mir/interpret/pointer.rs [hunk 5]
```diff
@@ -143,37 +162,78 @@ impl From<AllocId> for Pointer {
...
+        (self.provenance, self.offset)
+    }
+
+    #[inline(always)]
+    pub fn erase_for_fmt(self) -> Pointer
+    where
+        Tag: Provenance,
+    {
+        // FIXME: This is wrong! `self.offset` might be an absolute address.
+        Pointer { offset: self.offset, provenance: self.provenance.erase_for_fmt() }
```
Comment (RalfJung) [inline compiler/rustc_middle/src/mir/interpret/pointer.rs:217]: I still need to figure out a solution to this problem: we can't just change the `Tag` type since that affects how `offset` must be interpreted! (As absolute address vs as relative to some `AllocId`.)

I'll look into where this is currently actually needed, maybe there is a better way. The backup plan is to return a `Pointer<Option<Tag>>` and use the `None` provenance to reflect absolute addresses, but that would be an unfortunate loss of information in Miri traces.

File: compiler/rustc_mir/src/const_eval/eval_queries.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:169]: Yeah Miri needs to access the `offset` to compare between `Pointer<AllocId>` (address is relative) and `Pointer<Tag>` (address is absolute).

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:109]: I don't see how. The `Tag` type affects how the `Pointer` itself is rendered:
- `Pointer<AllocId>`: `alloc123+0x13`
- `Pointer<Tag>`: `0x12defg60[alloc123]<Stacked Borrows info>`

Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:109]: >  I'm mainly unhappy about the roundabout formatting stuff that requires one to essentially write the derived impl by hand.

Yeah I am unhappy about that as well.^^ Open to suggestions for how to do this better.

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:217]: I think I can avoid pretty much all of those uses (though I am not quite sure yet how to best factor that) -- except for the one in `impl Display for ImmTy`. I am actually somewhat doubtful about that implementation... do we really want it to display the *pointee* of references etc? For Miri and even during a CTFE execution this will not work at all since it looks up the data only in the global `tcx`! So I think my preferred solution here would be to not call `pretty_print_const_scalar` at all, which would elegantly remove the problem...

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 3 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:109]: can miri implement Display for Pointer<Tag> since Tag is a miri-internal type?

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 5 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:217]: oof, yea that's annoying. I don't remember why we dispatch to the pretty printer, so yea, just printing without tcx or ecx information seems best

File: compiler/rustc_mir/src/const_eval/eval_queries.rs (hunk 2 above)
Comment (RalfJung) [reply compiler/rustc_mir/src/const_eval/eval_queries.rs:169]: FWIW, I actually did think of a way to make this more type-safe: the `Provenance` trait could have an associated type `Offset`, and a function `wrap_offset(Size) -> Offset`. Then `into_parts` would return `Offset`, so code generic in `Tag` would actually not know the type `Offset` and this could not use it wrong.

Then we might go even further and make the `Pointer::offset` field be of type `Offset`... though at that point we cannot define generic pointer arithmetic methods any more so we'd need some more methods in the `Provenance` trait.

But I am not sure if that's worth it. I had one bug caused by mis-interpreting a relative offset as absolute, and this would not have caught it (since the bug was about pointers stored inside an `Allocation`, where the offset is part of the byte array anyway).

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:217]: Ah I think it is to get nice printing of scalars for some of the UB messages. I will keep using the const-pretty-print code for `ScalarInt` but not use it for `Pointer`.

**Comment by RalfJung** [comment]
Ah, we even got slight speed-ups, probably because `MemPlace` is a bit smaller now. :)

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:109]: Doesn't that only work for "fundamental" types?

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 5 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs]: Resolved by latest commit.

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 3 above)
Comment (RalfJung) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:110]: Oh also that would not help -- the generic code in `rustc_mir::interpret` needs to know for sure that it can debug-print pointers. So we need something generic.

Is it possible to add `Pointer<Self::PointerTag>: Debug` as a requirement to the `Machine` trait?^^

File: compiler/rustc_middle/src/mir/interpret/allocation.rs [hunk 6]
```diff
@@ -321,7 +330,11 @@ impl<Tag: Copy, Extra> Allocation<Tag, Extra> {
         cx: &impl HasDataLayout,
         range: AllocRange,
     ) -> AllocResult<ScalarMaybeUninit<Tag>> {
-        // `get_bytes_unchecked` tests relocation edges.
+        // `get_bytes_with_uninit_and_ptr` tests relocation edges.
+        // We deliberately error when loading data that partailly has provenance, or partially
```
Comment (bjorn3) [inline compiler/rustc_middle/src/mir/interpret/allocation.rs:334]:
```suggestion
        // We deliberately error when loading data that partially has provenance, or partially
```

File: compiler/rustc_middle/src/mir/interpret/pointer.rs (hunk 3 above)
Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:110]: > Is it possible to add `Pointer<Self::PointerTag>: Debug` as a requirement to the `Machine` trait?^^

Not in a useful way (you'd have to repeat the bound at every usage site of `Machine`).

*but* you could keep your `fmt` function and only implement `Debug` manually on `Pointer<Tag: Provenance>` and then you should be able to derive `Debug` everywhere else, as long as you add the `Tag: Provenance` bound to all the types instead of only on the impls. It's not nice, but nicer than doing manual trivial impls everywhere I think?

Comment (oli-obk) [reply compiler/rustc_middle/src/mir/interpret/pointer.rs:110]: thinking about this again, it's not too bad, so we can merge and figure out improvements later

**Comment by oli-obk** [comment]
r=me if you want, unless you are already working on the things we discussed and want to get them into this PR

**Comment by RalfJung** [comment]
Yeah I am already experimenting now.^^

**Comment by RalfJung** [comment]
This leads to an unnecessary `Tag: Debug` bound (because we can't control the `where` clause if the generated `Debug`, which is the entire problem of course), but I still think it's a win overall.

I did not yet do this for `Scalar` and `ScalarMaybeUninit` though, just to the higher-level types.

**Comment by RalfJung** [comment]
Ah, with that last commit this PR actually has a net negative line count. :)
