### PR TITLE
Disallow non-explicit elided lifetimes in async fn

### LINKED ISSUE #60203: Async fns that take structs with elided lifetime parameters are broken.
[This code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7e4da079a8f770befd3b1583d27c2262) fails to compile with a very strange error:

```rust
#![feature(test, futures_api, async_await, await_macro)]
struct HasLifetime<'a>(&'a bool);
async fn bug(lifetime: HasLifetime) { 
    if *lifetime.0 { }
}
```

Error given:

```
error: cannot infer an appropriate lifetime
 --> src/lib.rs:3:37
  |
3 |   async fn bug(lifetime: HasLifetime) { 
  |                                       ^
  |                                       |
  |  _____________________________________this return type evaluates to the `'static` lifetime...
  | |
4 | |     if *lifetime.0 { }
5 | | }
  | |_^ ...but this borrow...
  |
note: ...can't outlive the anonymous lifetime #1 defined on the function body at 3:1
 --> src/lib.rs:3:1
  |
3 | / async fn bug(lifetime: HasLifetime) { 
4 | |     if *lifetime.0 { }
5 | | }
  | |_^
help: you can add a constraint to the return type to make it last less than `'static` and match the anonymous lifetime #1 defined on the function body at 3:1
  |
3 | async fn bug(lifetime: HasLifetime)  + '_{ 
  |                                      ^^^^
```

It seems the compiler fails to generate a lifetime constraint on the `impl Future<...>` the function compiles down to because there is no apparent lifetime on `HasLifetime`. Replacing it with `HasLifetime<'_>` fixes the problem.

### PR DESCRIPTION
**Pull request by cramertj**
Fix https://github.com/rust-lang/rust/issues/60203

r? @nikomatsakis

### CODE REVIEW

File: src/librustc/hir/lowering.rs [hunk 1]
```diff
@@ -5298,13 +5298,23 @@ impl<'a> LoweringContext<'a> {
 
     fn elided_path_lifetime(&mut self, span: Span) -> hir::Lifetime {
         match self.anonymous_lifetime_mode {
-            // N.B., We intentionally ignore the create-parameter mode here
-            // and instead "pass through" to resolve-lifetimes, which will then
-            // report an error. This is because we don't want to support
-            // impl elision for deprecated forms like
+            // In create-parameter mode we error here because we don't want to support
+            // deprecated impl elision in new features like impl elision and `async fn`,
+            // both of which work using the `CreateParameter` mode:
```
Comment (Centril) [inline src/librustc/hir/lowering.rs]: I understand why this is happening but I find it rather strange that `async fn`s and `fn`s don't act similarly. That said, I agree with the consensus in the meeting that we can change our minds later if need be.

File: src/test/ui/async-fn-path-elision.rs [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// edition:2018
```
Comment (Centril) [inline src/test/ui/async-fn-path-elision.rs]: This test should be moved to a dedicated folder for async/await; having it here makes reviewing the stabilization report harder to review and also clutters the already polluted `ui/` folder.

File: src/librustc/hir/lowering.rs [hunk 3]
```diff
@@ -5298,13 +5298,23 @@ impl<'a> LoweringContext<'a> {
...
-            AnonymousLifetimeMode::CreateParameter |
+            //     async fn foo(_: std::cell::Ref<u32>) { ... }
+            AnonymousLifetimeMode::CreateParameter => {
+                struct_span_err!(
+                    self.sess,
+                    span,
+                    E0726,
+                    "implicit elided lifetime not allowed here"
+                ).help("consider using an explicit elided lifetime: `'_`").emit();
+                self.sess.abort_if_errors();
```
Comment (Centril) [inline src/librustc/hir/lowering.rs]: This seems pretty bad tho to fatally abort compilation; ideally we should let it continue... if that cannot be feasibly fixed now, let's please add a `FIXME` here with an associated `A-diagnostics` issue.

Comment (cramertj) [reply src/librustc/hir/lowering.rs]: Why is this bad? There's no reason this is needed-- we could certainly continue compilation, but elsewhere in lowering we abort on errors, so I did the same here.

File: src/test/ui/async-fn-path-elision.rs (hunk 2 above)
Comment (cramertj) [reply src/test/ui/async-fn-path-elision.rs]: There is no such folder today. The existing async fn tests live in `ui/async-fn-*.rs`. I'd prefer not to change all of that in this PR.

Comment (Centril) [reply src/test/ui/async-fn-path-elision.rs]: OK; can you make a C-cleanup issue for that?

File: src/librustc/hir/lowering.rs (hunk 3 above)
Comment (Centril) [reply src/librustc/hir/lowering.rs]: My understanding is that we generally want compilation to continue to let the user see other errors beyond the lowering stage; same with parsing, i.e. that's why we do recovery... but @estebank  is the expert here.

Comment (estebank) [reply src/librustc/hir/lowering.rs]: We're removing as many of the `abort_if_errors` as possible in order to avoid [the "waves of errors" experience](https://mobile.twitter.com/isislovecruft/status/876542921323028480). The more gating steps in the compiler the more likely you are to have real errors hidden from the users. A more reasonable thing to do is either marking entire blocks with placeholders (`tcx.types.error` is a good example) and let the compiler continue and ignore those placeholders. It pollutes later stages with some logic to ignore them but it dramatically improves the experience. In this case in particular you're already recovering with `self.new_named_lifetime(id, span, hir::LifetimeName::Error)`, so `abort_if_errors` shouldn't be needed. Did you see any knock-down effects? It'd be much better to fix those places than having this here, but of course that could be left for a later clean up PR, which is why leaving a `FIXME` is enough in this case.

File: src/test/ui/async-fn-path-elision.rs (hunk 2 above)
Comment (cramertj) [reply src/test/ui/async-fn-path-elision.rs]: https://github.com/rust-lang/rust/issues/60418

File: src/librustc/hir/lowering.rs (hunk 3 above)
Comment (cramertj) [reply src/librustc/hir/lowering.rs]: Huh, I guess I'm one of the only remaining ones who *wants* the "waves of errors" experience. I've had many fewer problems with "waves of errors" than I have with getting hundreds of errors due to a failed import or a missing WF bound. I'll go ahead and remove this, though, since it seems like there's a plan and policy in place. Thanks for bringing this up, @Centril , and for clarifying the plan, @estebank ! :)

Comment (estebank) [reply src/librustc/hir/lowering.rs]: @cramertj we certainly want to silence useless knock-down errors, but to do so we first need to see/experience them :)

I think long term it'll be a much better experience.

Comment (cramertj) [reply src/librustc/hir/lowering.rs]: Makes sense! I'll do my best to follow bugs when I see these so we can track them down in the future.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Generally positive, but the error wording is a bit confusing. If we don't want to do the proper fix, then perhaps something like "help: use `'_` to represent the elided lifetime explicitly"?

File: src/test/ui/async-fn-path-elision.stderr [hunk 4]
```diff
@@ -0,0 +1,10 @@
+error[E0726]: implicit elided lifetime not allowed here
+  --> $DIR/async-fn-path-elision.rs:8:20
+   |
+LL | async fn error(lt: HasLifetime) {
+   |                    ^^^^^^^^^^^
+   |
+   = help: consider using an explicit elided lifetime: `'_`
```
[the remark this answers is not in the document]
Comment (cramertj) [reply src/test/ui/async-fn-path-elision.stderr]: I've put up a change to reuse the logic from the `rust_2018_idioms` elided lifetime parameters in types lint-- this gives a nice improvement for the impl headers case as well-- thanks for the recommendation! As a drive-by, I did notice that the error prints somewhat surprisingly:

```rust
#![deny(rust_2018_idioms)]

struct Foo<'a>(&'a u8);

fn foo(_: Foo) {}
```

gives 
```
error: hidden lifetime parameters in types are deprecated
 --> src/main.rs:5:11
  |
5 | fn foo(_: Foo) {}
  |           ^^^- help: indicate the anonymous lifetime: `<'_>`
```

Strangely, adding a type parameter makes it spell out the whole type:

```rust
#![deny(rust_2018_idioms)]

struct Foo<'a, T>(&'a T);

fn foo<T>(_: Foo<T>) {}
```
```
error: hidden lifetime parameters in types are deprecated
 --> src/main.rs:5:14
  |
5 | fn foo<T>(_: Foo<T>) {}
  |              ^^^^^^ help: indicate the anonymous lifetime: `Foo<'_, T>`
```

Not sure if that's intended, but I found `: <'_>` a bit odd.

**Review by nikomatsakis — APPROVED** [review]
Nice!
