### PR TITLE
Make `compare_impl_item` into a query

### LINKED ISSUE #119701: ICE: effects, gce: difference in caller_arg caller_abi layout
auto-reduced (treereduce-rust):
````rust
#![feature(const_trait_impl, generic_const_exprs)]

fn main() {
    let _ = process::<()>([()]);
}

fn process<T: const Trait>() -> [(); T::make(2)] {
    input
}

#[const_trait]
trait Trait {
    fn make(input: u8) -> usize;
}

impl const Trait for () {
    fn make(input: usize) -> usize {
        input / 2
    }
}


````

original:
````rust
// check-pass

#![feature(const_trait_impl, effects, generic_const_exprs)]
#![allow(incomplete_features)]

fn main() {
    let _ = process::<()>([()]);
    let _ = Struct::<(), 4> { field: [1, 0] };
}

fn process<T: const Trait>(input: [(); T::make(2)]) -> [(); T::make(2)] {
    input
}

struct Struct<T: const Trait, const P: usize>
where
    [u32; T::make(P)]:,
{
    field: [u32; T::make(P)],
}

#[const_trait]
trait Trait {
    fn make(input: u8) -> usize;
}

impl const Trait for () {
    fn make(input: usize) -> usize {
        input / 2
    }
}

````

Version information
````
rustc 1.77.0-nightly (87e143089 2024-01-07)
binary: rustc
commit-hash: 87e1430893d55001034bd76c5dbe832d80bc50c3
commit-date: 2024-01-07
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0425]: cannot find value `input` in this scope
 --> /tmp/icemaker_global_tempdir.jkf89PvuHS4R/rustc_testrunner_tmpdir_reporting.GWTS1Qe3YIbK/mvce.rs:8:5
  |
8 |     input
  |     ^^^^^ not found in this scope

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.jkf89PvuHS4R/rustc_testrunner_tmpdir_reporting.GWTS1Qe3YIbK/mvce.rs:1:39
  |
1 | #![feature(const_trait_impl, effects, generic_const_exprs)]
  |                                       ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0053]: method `make` has an incompatible type for trait
  --> /tmp/icemaker_global_tempdir.jkf89PvuHS4R/rustc_testrunner_tmpdir_reporting.GWTS1Qe3YIbK/mvce.rs:17:20
   |
17 |     fn make(input: usize) -> usize {
   |                    ^^^^^
   |                    |
   |                    expected `u8`, found `usize`
   |                    help: change the parameter type to match the trait: `u8`
   |
note: type in trait
  --> /tmp/icemaker_global_tempdir.jkf89PvuHS4R/rustc_testrunner_tmpdir_reporting.GWTS1Qe3YIbK/mvce.rs:13:20
   |
13 |     fn make(input: u8) -> usize;
   |                    ^^
   = note: expected signature `fn(u8) -> _`
              found signature `fn(usize) -> _`

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/terminator.rs:454:9:
assertion `left == right` failed
  left: Layout { size: Size(1 bytes), align: AbiAndPrefAlign { abi: Align(1 bytes), pref: Align(1 bytes) }, abi: Scalar(Initialized { value: Int(I8, false), valid_range: 0..=255 }), fields: Primitive, largest_niche: None, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(1 bytes) }
 right: Layout { size: Size(8 bytes), align: AbiAndPrefAlign { abi: Align(8 bytes), pref: Align(8 bytes) }, abi: Scalar(Initialized { value: Int(I64, false), valid_range: 0..=18446744073709551615 }), fields: Primitive, largest_niche: None, variants: Single { index: 0 }, max_repr_align: None, unadjusted_abi_align: Align(8 bytes) }
stack backtrace:
   0:     0x7f288f98c7e6 - std::backtrace_rs::backtrace::libunwind::trace::he8bb9a2968030ce5
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f288f98c7e6 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e6335639c9b85e4
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f288f98c7e6 - std::sys_common::backtrace::_print_fmt::hd66fef07c209e556
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f288f98c7e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hecd93f344b959b6a
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f288f9deed0 - core::fmt::rt::Argument::fmt::h2ce15aff494aed3e
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f288f9deed0 - core::fmt::write::hfa1934f2b28427b2
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f288f9801df - std::io::Write::write_fmt::h3d316f3d08b299da
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/io/mod.rs:1810:15
   7:     0x7f288f98c5c4 - std::sys_common::backtrace::_print::h0e9229b4060901ad
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f288f98c5c4 - std::sys_common::backtrace::print::he46da77420c9de24
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f288f98f357 - std::panicking::default_hook::{{closure}}::h54b1b53158ffe881
  10:     0x7f288f98f0b9 - std::panicking::default_hook::h2bf110e162a78c7d
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/panicking.rs:292:9
  11:     0x7f2892753d9c - std[6006d4e995217078]::panicking::update_hook::<alloc[e75bd506fea0da47]::boxed::Box<rustc_driver_impl[d2c301b665c661c0]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f288f98faa6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h751b1f22210c3ae5
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f288f98faa6 - std::panicking::rust_panic_with_hook::h08d4c37f8f6f3bb0
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/panicking.rs:783:13
  14:     0x7f288f98f7f2 - std::panicking::begin_panic_handler::{{closure}}::hd6d6630725f99a44
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/panicking.rs:657:13
  15:     0x7f288f98cce6 - std::sys_common::backtrace::__rust_end_short_backtrace::h3c42b90070a2a7fe
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f288f98f550 - rust_begin_unwind
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/panicking.rs:645:5
  17:     0x7f288f9db5d5 - core::panicking::panic_fmt::ha8ce81f4758d271e
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/core/src/panicking.rs:72:14
  18:     0x7f288f9dbb6b - core::panicking::assert_failed_inner::h33251d3505946c37
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/core/src/panicking.rs:342:17
  19:     0x7f28926ccfe3 - core[3198d8acc012de37]::panicking::assert_failed::<rustc_target[c2cb60685ff2eae8]::abi::Layout, rustc_target[c2cb60685ff2eae8]::abi::Layout>
  20:     0x7f2891be0c84 - <rustc_const_eval[51909c9ef48db599]::interpret::eval_context::InterpCx<rustc_const_eval[51909c9ef48db599]::const_eval::machine::CompileTimeInterpreter>>::pass_argument::<core[3198d8acc012de37]::iter::adapters::filter::Filter<core[3198d8acc012de37]::iter::adapters::zip::Zip<core[3198d8acc012de37]::slice::iter::Iter<rustc_const_eval[51909c9ef48db599]::interpret::terminator::FnArg>, core[3198d8acc012de37]::slice::iter::Iter<rustc_target[c2cb60685ff2eae8]::abi::call::ArgAbi<rustc_middle[7e63d8cceb784d0e]::ty::Ty>>>, <rustc_const_eval[51909c9ef48db599]::interpret::eval_context::InterpCx<rustc_const_eval[51909c9ef48db599]::const_eval::machine::CompileTimeInterpreter>>::eval_fn_call::{closure#2}>>
  21:     0x7f2891bcd830 - <rustc_const_eval[51909c9ef48db599]::interpret::eval_context::InterpCx<rustc_const_eval[51909c9ef48db599]::const_eval::machine::CompileTimeInterpreter>>::eval_fn_call
  22:     0x7f28947c8545 - rustc_const_eval[51909c9ef48db599]::const_eval::eval_queries::eval_body_using_ecx
  23:     0x7f28947b93fe - rustc_const_eval[51909c9ef48db599]::const_eval::eval_queries::eval_in_interpreter
  24:     0x7f28947b8fee - rustc_const_eval[51909c9ef48db599]::const_eval::eval_queries::eval_to_allocation_raw_provider
  25:     0x7f28947b8e76 - rustc_query_impl[123ba24cfbee05a3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[123ba24cfbee05a3]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>
  26:     0x7f28947b7d4b - rustc_query_system[c043c6b7422f834c]::query::plumbing::try_execute_query::<rustc_query_impl[123ba24cfbee05a3]::DynamicConfig<rustc_query_system[c043c6b7422f834c]::query::caches::DefaultCache<rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[123ba24cfbee05a3]::plumbing::QueryCtxt, false>
  27:     0x7f28947b7730 - rustc_query_impl[123ba24cfbee05a3]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f2894489e89 - rustc_middle[7e63d8cceb784d0e]::query::plumbing::query_get_at::<rustc_query_system[c043c6b7422f834c]::query::caches::DefaultCache<rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>>
  29:     0x7f289448a3e7 - rustc_const_eval[51909c9ef48db599]::const_eval::eval_to_valtree
  30:     0x7f289448a362 - <rustc_const_eval[51909c9ef48db599]::provide::{closure#0} as core[3198d8acc012de37]::ops::function::FnOnce<(rustc_middle[7e63d8cceb784d0e]::ty::context::TyCtxt, rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>)>>::call_once
  31:     0x7f289448a336 - rustc_query_impl[123ba24cfbee05a3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[123ba24cfbee05a3]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>
  32:     0x7f289448a2ef - <rustc_query_impl[123ba24cfbee05a3]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[3198d8acc012de37]::ops::function::FnOnce<(rustc_middle[7e63d8cceb784d0e]::ty::context::TyCtxt, rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>)>>::call_once
  33:     0x7f28947b7d67 - rustc_query_system[c043c6b7422f834c]::query::plumbing::try_execute_query::<rustc_query_impl[123ba24cfbee05a3]::DynamicConfig<rustc_query_system[c043c6b7422f834c]::query::caches::DefaultCache<rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[123ba24cfbee05a3]::plumbing::QueryCtxt, false>
  34:     0x7f28947b7630 - rustc_query_impl[123ba24cfbee05a3]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f28947b6ea8 - rustc_middle[7e63d8cceb784d0e]::query::plumbing::query_get_at::<rustc_query_system[c043c6b7422f834c]::query::caches::DefaultCache<rustc_middle[7e63d8cceb784d0e]::ty::ParamEnvAnd<rustc_middle[7e63d8cceb784d0e]::mir::interpret::GlobalId>, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 24usize]>>>
  36:     0x7f28941c13a0 - <rustc_middle[7e63d8cceb784d0e]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  37:     0x7f2892a45e92 - <rustc_infer[c8d919f150ceb777]::infer::InferCtxt>::const_eval_resolve
  38:     0x7f289473955a - rustc_trait_selection[cf05ae63d4650815]::traits::const_evaluatable::is_const_evaluatable
  39:     0x7f2890a76e34 - <rustc_trait_selection[cf05ae63d4650815]::traits::fulfill::FulfillProcessor as rustc_data_structures[2b23c279f5a9a63c]::obligation_forest::ObligationProcessor>::process_obligation
  40:     0x7f2893a1507b - <rustc_data_structures[2b23c279f5a9a63c]::obligation_forest::ObligationForest<rustc_trait_selection[cf05ae63d4650815]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[cf05ae63d4650815]::traits::fulfill::FulfillProcessor>
  41:     0x7f2894533ff9 - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_argument_types
  42:     0x7f28943de028 - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_call
  43:     0x7f28944bb6f0 - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  44:     0x7f2893fa4ae0 - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_decl
  45:     0x7f2893fa26e2 - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_block_with_expected
  46:     0x7f28944bbaff - <rustc_hir_typeck[b859d96d8979696c]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  47:     0x7f289405077d - rustc_hir_typeck[b859d96d8979696c]::check::check_fn
  48:     0x7f2893cd6556 - rustc_hir_typeck[b859d96d8979696c]::typeck
  49:     0x7f2893cd5909 - rustc_query_impl[123ba24cfbee05a3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[123ba24cfbee05a3]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 8usize]>>
  50:     0x7f2893bf04f9 - rustc_query_system[c043c6b7422f834c]::query::plumbing::try_execute_query::<rustc_query_impl[123ba24cfbee05a3]::DynamicConfig<rustc_query_system[c043c6b7422f834c]::query::caches::VecCache<rustc_span[4446da8eb7a0bfab]::def_id::LocalDefId, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[123ba24cfbee05a3]::plumbing::QueryCtxt, false>
  51:     0x7f2893bf0190 - rustc_query_impl[123ba24cfbee05a3]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7f2893befa14 - <rustc_middle[7e63d8cceb784d0e]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[e479025b5d5dcfb6]::check_crate::{closure#6}>::{closure#0}
  53:     0x7f2893bee333 - rustc_hir_analysis[e479025b5d5dcfb6]::check_crate
  54:     0x7f2894649919 - rustc_interface[a2edae3cd6dbf972]::passes::analysis
  55:     0x7f289464955f - rustc_query_impl[123ba24cfbee05a3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[123ba24cfbee05a3]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 1usize]>>
  56:     0x7f289499ace4 - rustc_query_system[c043c6b7422f834c]::query::plumbing::try_execute_query::<rustc_query_impl[123ba24cfbee05a3]::DynamicConfig<rustc_query_system[c043c6b7422f834c]::query::caches::SingleCache<rustc_middle[7e63d8cceb784d0e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[123ba24cfbee05a3]::plumbing::QueryCtxt, false>
  57:     0x7f289499aad5 - rustc_query_impl[123ba24cfbee05a3]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  58:     0x7f2894a2f2b5 - rustc_interface[a2edae3cd6dbf972]::interface::run_compiler::<core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>, rustc_driver_impl[d2c301b665c661c0]::run_compiler::{closure#0}>::{closure#0}
  59:     0x7f28949bf886 - std[6006d4e995217078]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a2edae3cd6dbf972]::util::run_in_thread_with_globals<rustc_interface[a2edae3cd6dbf972]::util::run_in_thread_pool_with_globals<rustc_interface[a2edae3cd6dbf972]::interface::run_compiler<core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>, rustc_driver_impl[d2c301b665c661c0]::run_compiler::{closure#0}>::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>
  60:     0x7f28949bf6b3 - <<std[6006d4e995217078]::thread::Builder>::spawn_unchecked_<rustc_interface[a2edae3cd6dbf972]::util::run_in_thread_with_globals<rustc_interface[a2edae3cd6dbf972]::util::run_in_thread_pool_with_globals<rustc_interface[a2edae3cd6dbf972]::interface::run_compiler<core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>, rustc_driver_impl[d2c301b665c661c0]::run_compiler::{closure#0}>::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3198d8acc012de37]::result::Result<(), rustc_span[4446da8eb7a0bfab]::ErrorGuaranteed>>::{closure#1} as core[3198d8acc012de37]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  61:     0x7f288f9999d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5ce354fdf0c7f9b3
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/alloc/src/boxed.rs:2016:9
  62:     0x7f288f9999d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb85fbf7e27da60df
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/alloc/src/boxed.rs:2016:9
  63:     0x7f288f9999d5 - std::sys::unix::thread::Thread::new::thread_start::h62fdb86990446cb0
                               at /rustc/87e1430893d55001034bd76c5dbe832d80bc50c3/library/std/src/sys/unix/thread.rs:108:17
  64:     0x7f288f7859eb - <unknown>
  65:     0x7f288f8097cc - <unknown>
  66:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (87e143089 2024-01-07) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `process::{constant#0}`
#1 [eval_to_valtree] evaluating type-level constant
#2 [typeck] type-checking `main`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0053, E0425.
For more information about an error, try `rustc --explain E0053`.

```

</p>
</details>

### LINKED ISSUE #121127: ICE: tcx: `index out of bounds: the len is 1 but the index is 1`
auto-reduced (treereduce-rust):
````rust
#![feature(specialization)]

pub trait Foo {
    fn abc() -> u32;
}

pub trait Marker {}

impl<T> Foo for T {
    default fn abc(f: fn(&T), t: &T) -> u32 {
        16
    }
}

impl<T: Marker> Foo for T {
    fn def() -> u32 {
        Self::abc()
    }
}


````

original:
````rust
// run-pass
#![feature(specialization)]
//~^ WARN the feature `specialization` is incomplete

pub trait Foo {
    fn abc() -> u32;
    fn def() -> u32;
}

pub trait Marker {}

impl Marker for () {}

impl<T> Foo for T {
    default fn abc(f: fn(&T), t: &T) -> u32 { 16 }
    default fn def() -> u32 { 42 }
}

impl<T: Marker> Foo for T {
    fn def() -> u32 {
        Self::abc()
    }
}

fn main() {
   assert_eq!(<()>::def(), 16);
   assert_eq!(<i32>::def(), 42);
}

````

Version information
````
rustc 1.78.0-nightly (ee9c7c940 2024-02-14)
binary: rustc
commit-hash: ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46
commit-date: 2024-02-14
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zpolymorphize=on -Zinline-mir=yes`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0407]: method `def` is not a member of trait `Foo`
  --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:16:5
   |
16 | /     fn def() -> u32 {
17 | |         Self::abc()
18 | |     }
   | |_____^ not a member of trait `Foo`

warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:19:2
   |
19 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs`

error[E0050]: method `abc` has 2 parameters but the declaration in trait `Foo::abc` has 0
  --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:10:23
   |
4  |     fn abc() -> u32;
   |     ---------------- trait requires 0 parameters
...
10 |     default fn abc(f: fn(&T), t: &T) -> u32 {
   |                       ^^^^^^^^^^^^^ expected 0 parameters, found 2

warning: unused variable: `f`
  --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:10:20
   |
10 |     default fn abc(f: fn(&T), t: &T) -> u32 {
   |                    ^ help: if this is intentional, prefix it with an underscore: `_f`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `t`
  --> /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:10:31
   |
10 |     default fn abc(f: fn(&T), t: &T) -> u32 {
   |                               ^ help: if this is intentional, prefix it with an underscore: `_t`

thread 'rustc' panicked at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/compiler/rustc_middle/src/mir/tcx.rs:133:61:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0:     0x7f1870d8ce46 - std::backtrace_rs::backtrace::libunwind::trace::h5168cb64cb843b87
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f1870d8ce46 - std::backtrace_rs::backtrace::trace_unsynchronized::hbbff473666b784c6
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1870d8ce46 - std::sys_common::backtrace::_print_fmt::h6c61b632e6cc7949
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f1870d8ce46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h974a6b559c2b8d41
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1870ddd46c - core::fmt::rt::Argument::fmt::hf6a5273aff56768c
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/core/src/fmt/rt.rs:142:9
   5:     0x7f1870ddd46c - core::fmt::write::h1caffe3a78971207
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f1870d807ef - std::io::Write::write_fmt::h2caf2bb3485e27a5
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/io/mod.rs:1854:15
   7:     0x7f1870d8cbf4 - std::sys_common::backtrace::_print::h0414d95b24b9ea44
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1870d8cbf4 - std::sys_common::backtrace::print::hfdf60e3b3d06625d
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1870d8f93b - std::panicking::default_hook::{{closure}}::h3c1109072cde0ade
  10:     0x7f1870d8f689 - std::panicking::default_hook::hfe3c076d4f24ecbe
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/panicking.rs:292:9
  11:     0x7f1873bf563c - std[2308076c1424b998]::panicking::update_hook::<alloc[33ce0ef41c101337]::boxed::Box<rustc_driver_impl[d317596fd5f90102]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f1870d900a0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8a55f98e23703736
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/alloc/src/boxed.rs:2030:9
  13:     0x7f1870d900a0 - std::panicking::rust_panic_with_hook::hc147efcd5d482f2c
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/panicking.rs:785:13
  14:     0x7f1870d8fde2 - std::panicking::begin_panic_handler::{{closure}}::h6174f0cd2a065d90
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/panicking.rs:659:13
  15:     0x7f1870d8d326 - std::sys_common::backtrace::__rust_end_short_backtrace::h770b1c8f4d2029d4
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f1870d8fb14 - rust_begin_unwind
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/panicking.rs:647:5
  17:     0x7f1870dd9975 - core::panicking::panic_fmt::h66e8ea0facb42563
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/core/src/panicking.rs:72:14
  18:     0x7f1870dd9bc2 - core::panicking::panic_bounds_check::h178a976047dd7a3b
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/core/src/panicking.rs:208:5
  19:     0x7f18730fc93a - <rustc_mir_transform[c0673d0b3c528a53]::remove_zsts::RemoveZsts as rustc_middle[efc8e2d5742a68dd]::mir::MirPass>::run_pass
  20:     0x7f1874e1420f - rustc_mir_transform[c0673d0b3c528a53]::pass_manager::run_passes_inner
  21:     0x7f1875157fbd - rustc_mir_transform[c0673d0b3c528a53]::optimized_mir
  22:     0x7f1874e92975 - rustc_query_impl[ecef4a4fa1cc3689]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecef4a4fa1cc3689]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 8usize]>>
  23:     0x7f1874e93020 - rustc_query_system[8b26caae5283da17]::query::plumbing::try_execute_query::<rustc_query_impl[ecef4a4fa1cc3689]::DynamicConfig<rustc_query_system[8b26caae5283da17]::query::caches::DefIdCache<rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ecef4a4fa1cc3689]::plumbing::QueryCtxt, false>
  24:     0x7f1874e9279e - rustc_query_impl[ecef4a4fa1cc3689]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7f18757f01d8 - rustc_middle[efc8e2d5742a68dd]::query::plumbing::query_get_at::<rustc_query_system[8b26caae5283da17]::query::caches::DefIdCache<rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 8usize]>>>
  26:     0x7f1875800c32 - rustc_query_impl[ecef4a4fa1cc3689]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecef4a4fa1cc3689]::query_impl::unused_generic_params::dynamic_query::{closure#2}::{closure#0}, rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 4usize]>>
  27:     0x7f187580041b - rustc_query_system[8b26caae5283da17]::query::plumbing::try_execute_query::<rustc_query_impl[ecef4a4fa1cc3689]::DynamicConfig<rustc_query_system[8b26caae5283da17]::query::caches::DefaultCache<rustc_middle[efc8e2d5742a68dd]::ty::instance::InstanceDef, rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[ecef4a4fa1cc3689]::plumbing::QueryCtxt, false>
  28:     0x7f187580012c - rustc_query_impl[ecef4a4fa1cc3689]::query_impl::unused_generic_params::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f18757fbc2c - rustc_interface[e88069c12facd435]::passes::analysis
  30:     0x7f18757fb229 - rustc_query_impl[ecef4a4fa1cc3689]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ecef4a4fa1cc3689]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 1usize]>>
  31:     0x7f1875c3afe5 - rustc_query_system[8b26caae5283da17]::query::plumbing::try_execute_query::<rustc_query_impl[ecef4a4fa1cc3689]::DynamicConfig<rustc_query_system[8b26caae5283da17]::query::caches::SingleCache<rustc_middle[efc8e2d5742a68dd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ecef4a4fa1cc3689]::plumbing::QueryCtxt, false>
  32:     0x7f1875c3ad49 - rustc_query_impl[ecef4a4fa1cc3689]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f1875c44695 - rustc_interface[e88069c12facd435]::interface::run_compiler::<core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>, rustc_driver_impl[d317596fd5f90102]::run_compiler::{closure#0}>::{closure#0}
  34:     0x7f1875dc5ad8 - std[2308076c1424b998]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e88069c12facd435]::util::run_in_thread_with_globals<rustc_interface[e88069c12facd435]::util::run_in_thread_pool_with_globals<rustc_interface[e88069c12facd435]::interface::run_compiler<core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>, rustc_driver_impl[d317596fd5f90102]::run_compiler::{closure#0}>::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>
  35:     0x7f1875dc5904 - <<std[2308076c1424b998]::thread::Builder>::spawn_unchecked_<rustc_interface[e88069c12facd435]::util::run_in_thread_with_globals<rustc_interface[e88069c12facd435]::util::run_in_thread_pool_with_globals<rustc_interface[e88069c12facd435]::interface::run_compiler<core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>, rustc_driver_impl[d317596fd5f90102]::run_compiler::{closure#0}>::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[db7e23408f407db6]::result::Result<(), rustc_span[e043cedf16fd8748]::ErrorGuaranteed>>::{closure#1} as core[db7e23408f407db6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x7f1870d991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbe12538a3d7e111d
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/alloc/src/boxed.rs:2016:9
  37:     0x7f1870d991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h306728bac30291a0
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/alloc/src/boxed.rs:2016:9
  38:     0x7f1870d991e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hec142a176366d167
                               at /rustc/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/std/src/sys/pal/unix/thread.rs:108:17
  39:     0x7f1870b809eb - <unknown>
  40:     0x7f1870c047cc - <unknown>
  41:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (ee9c7c940 2024-02-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z polymorphize=on -Z inline-mir=yes -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<impl at /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:15:1: 15:26>::def`
#1 [unused_generic_params] determining which generic parameters are unused by `<impl at /tmp/icemaker_global_tempdir.M7q9vo4k970Y/rustc_testrunner_tmpdir_reporting.QyBQD8LaDYVe/mvce.rs:15:1: 15:26>::def`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 3 warnings emitted

Some errors have detailed explanations: E0050, E0407, E0601.
For more information about an error, try `rustc --explain E0050`.

```

</p>
</details>

### LINKED ISSUE #121411: ICE: effects: `mismatch between caller ABI and caller arguments`
TBH this felt very familiar but I couldn't find any other tickets with this ice msg. was the message changed perhaps? :thinking: 

snippet:
````rust
#![feature(const_trait_impl, effects)]

#[const_trait]
trait Foo {
    fn into_iter(&self) {}
}

impl const Foo for () {
    fn into_iter(a: u32, b: u32) {}
}

const _: () = Foo::into_iter(&());


````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.a7aOa14Rjgwm/rustc_testrunner_tmpdir_reporting.nGXmGatUmLHL/mvce.rs:12:35
   |
12 | const _: () = Foo::into_iter(&());
   |                                   ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.a7aOa14Rjgwm/rustc_testrunner_tmpdir_reporting.nGXmGatUmLHL/mvce.rs`

error[E0186]: method `into_iter` has a `&self` declaration in the trait, but not in the impl
 --> /tmp/icemaker_global_tempdir.a7aOa14Rjgwm/rustc_testrunner_tmpdir_reporting.nGXmGatUmLHL/mvce.rs:9:5
  |
5 |     fn into_iter(&self) {}
  |     ------------------- `&self` used in trait
...
9 |     fn into_iter(a: u32, b: u32) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&self` in impl

warning: unused variable: `a`
 --> /tmp/icemaker_global_tempdir.a7aOa14Rjgwm/rustc_testrunner_tmpdir_reporting.nGXmGatUmLHL/mvce.rs:9:18
  |
9 |     fn into_iter(a: u32, b: u32) {}
  |                  ^ help: if this is intentional, prefix it with an underscore: `_a`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `b`
 --> /tmp/icemaker_global_tempdir.a7aOa14Rjgwm/rustc_testrunner_tmpdir_reporting.nGXmGatUmLHL/mvce.rs:9:26
  |
9 |     fn into_iter(a: u32, b: u32) {}
  |                          ^ help: if this is intentional, prefix it with an underscore: `_b`

thread 'rustc' panicked at compiler/rustc_const_eval/src/interpret/terminator.rs:655:21:
assertion `left == right` failed: mismatch between caller ABI and caller arguments
  left: 1
 right: 2
stack backtrace:
   0:     0x7f3101f8caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f3101f8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3101f8caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f3101f8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3101fdda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f3101fdda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f3101f814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7f3101f8c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f3101f8c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f3101f8f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7f3101f8f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7f3104e7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f3101f8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f3101f8fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7f3101f8fa92 - std::panicking::begin_panic_handler::{{closure}}::h4bfbc62f377d59e6
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:660:13
  15:     0x7f3101f8cfd6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc8487cf1bc04a693
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f3101f8f7c4 - rust_begin_unwind
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:648:5
  17:     0x7f3101fd9f95 - core::panicking::panic_fmt::h88277cce839da186
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/panicking.rs:72:14
  18:     0x7f3101fda5bf - core::panicking::assert_failed_inner::h5fb0563819aeab95
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/panicking.rs:337:23
  19:     0x7f3104df22ce - core[85b4fd477ce5bb21]::panicking::assert_failed::<usize, usize>
  20:     0x7f3103e7dd4a - <rustc_const_eval[b7e9a6566b8f5ff6]::interpret::eval_context::InterpCx<rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::machine::CompileTimeInterpreter>>::eval_fn_call
  21:     0x7f31070863e0 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_body_using_ecx::{closure#0}
  22:     0x7f3107076f23 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_in_interpreter
  23:     0x7f31065fa938 - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_allocation_raw_provider
  24:     0x7f31065fa706 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  25:     0x7f3106c0ba51 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  26:     0x7f3106c0b62c - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7f31065fb60d - rustc_const_eval[b7e9a6566b8f5ff6]::const_eval::eval_queries::eval_to_const_value_raw_provider
  28:     0x7f31065fb40c - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>
  29:     0x7f3106c0ba14 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::mir::interpret::GlobalId>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  30:     0x7f3106c0b530 - rustc_query_impl[9d4c51777e2bb749]::query_impl::eval_to_const_value_raw::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f3106bafe6b - <rustc_middle[446dd094ad85939e]::query::plumbing::TyCtxtEnsure>::const_eval_poly
  32:     0x7f3106badbd3 - rustc_hir_analysis[71d4294717f7f2b7]::check_crate
  33:     0x7f3106ca2dd3 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  34:     0x7f3106ca2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7f3106f3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  36:     0x7f3106f3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7f3106f4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  38:     0x7f31071be705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  39:     0x7f31071be532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7f3101f99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  41:     0x7f3101f99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  42:     0x7f3101f99725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  43:     0x7f3101d819eb - <unknown>
  44:     0x7f3101e057cc - <unknown>
  45:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `_`
#1 [eval_to_const_value_raw] simplifying constant for the type system `_`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0186, E0601.
For more information about an error, try `rustc --explain E0186`.

```

</p>
</details>

### LINKED ISSUE #129075: ICE: tcx: index out of bounds
auto-reduced (treereduce-rust):
````rust
struct Foo<T>([T; 2]);

impl<T: Default + Copy> Default for Foo<T> {
    fn default(&mut self) -> Self {
        Foo([Default::default(); 2])
    }
}

fn field_array() {
    let a: i32;
    let b;
    Foo([a, b]) = Default::default();
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
#![allow(unused_variables)]

use std::array::TryFromSliceError;
use std::convert::TryInto;

struct Zeroes;
impl Into<[usize; 2]> for Zeroes {
    fn into(self) -> [usize; 2] {
        [0; 2]
    }
}
impl Into<[usize; 3]> for Zeroes {
    fn into(self) -> [usize; 3] {
        [0; 3]
    }
}
impl Into<[Option<Box<u8>>; 48]> for Zeroes {
    fn into(self) -> [usize; 4] {
        [0; 4]
    }
}

fn zeroes_into() {
    let [a, b, c] = Zeroes.into();
    let [d, e, f]: [_; 3] = Zeroes.into();
}

fn array_try_from(x: &[usize]) -> Result<usize, TryFromSliceError> {
    let [a, b] = d.succ().isoweekdate().1()?;
    Ok(a + b)
}

fn destructuring_assignment() {
    let a: i32;
    let b;
    [a, b] = Default::default();
}

fn test_nested_array() {
    let a: [_; 3];
    let b;
    //~^ ERROR type annotations needed
    [a, b] = Default::default();
}

fn test_nested_array_type_hint() {
    let a: [_; 3];
    let b;
    [a, b] = Default::default();
    let _: i32 = b[1];
}

fn test_working_nested_array() {
    let a: i32;
    [[a, _, _], _, _] = Default::default();
}

struct Foo<T>([T; 2]);

impl<T: Default + Copy> Default for Foo<T> {
    fn default(&mut self, (_,): (T,)) -> Self {
        Foo([Default::default(); 2])
    }
}

fn field_array() {
    let a: i32;
    let b;
    Foo([a, b]) = Default::default();
}

fn main() {}

````
</p>
</details>

Version information
````
rustc 1.82.0-nightly (e5b3e68ab 2024-08-13)
binary: rustc
commit-hash: e5b3e68abf170556b9d56c6f9028318e53c9f06b
commit-date: 2024-08-13
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zvalidate-mir -Zinline-mir=yes`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:13:2
   |
13 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs`

error[E0185]: method `default` has a `&mut self` declaration in the impl, but not in the trait
 --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:4:5
  |
4 |     fn default(&mut self) -> Self {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&mut self` used in impl
  |
  = note: `default` from trait: `fn() -> Self`

warning: variable `a` is assigned to, but never used
  --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:10:9
   |
10 |     let a: i32;
   |         ^
   |
   = note: consider using `_a` instead
   = note: `#[warn(unused_variables)]` on by default

warning: variable `b` is assigned to, but never used
  --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:11:9
   |
11 |     let b;
   |         ^
   |
   = note: consider using `_b` instead

warning: value assigned to `a` is never read
  --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:12:10
   |
12 |     Foo([a, b]) = Default::default();
   |          ^
   |
   = help: maybe it is overwritten before being read?
   = note: `#[warn(unused_assignments)]` on by default

warning: value assigned to `b` is never read
  --> /tmp/icemaker_global_tempdir.ufzSPaPZx9Up/rustc_testrunner_tmpdir_reporting.doFpl6Nkk2VR/mvce.rs:12:13
   |
12 |     Foo([a, b]) = Default::default();
   |             ^
   |
   = help: maybe it is overwritten before being read?

thread 'rustc' panicked at /rustc/e5b3e68abf170556b9d56c6f9028318e53c9f06b/compiler/rustc_middle/src/mir/tcx.rs:131:61:
index out of bounds: the len is 11 but the index is 11
stack backtrace:
   0:     0x71a82a9be6ad - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd8cddadc2f1356ba
   1:     0x71a82b2049ef - core::fmt::write::hf4a4be5c7aa55e78
   2:     0x71a82c1c5511 - std::io::Write::write_fmt::h937572d76c9c7a9b
   3:     0x71a82a9c0d8b - std::panicking::default_hook::{{closure}}::h663ce340916a5919
   4:     0x71a82a9c09fe - std::panicking::default_hook::h5cb270171c609139
   5:     0x71a829b4b6c9 - std[c898dee7a900a719]::panicking::update_hook::<alloc[f79bb38400b26b08]::boxed::Box<rustc_driver_impl[7bc6674bbf855457]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x71a82a9c16a7 - std::panicking::rust_panic_with_hook::h527dcb0b253a1e21
   7:     0x71a82a9c1367 - std::panicking::begin_panic_handler::{{closure}}::hbc0a646a011dd19f
   8:     0x71a82a9beb69 - std::sys::backtrace::__rust_end_short_backtrace::h44802a1bb26a785a
   9:     0x71a82a9c1034 - rust_begin_unwind
  10:     0x71a827f50563 - core::panicking::panic_fmt::hb546fe36be3a0f24
  11:     0x71a828efc287 - core::panicking::panic_bounds_check::h90b5d213a1bed1e4
  12:     0x71a82bb52baa - <rustc_mir_transform[9616e0e93931520b]::inline::Inliner>::try_inlining
  13:     0x71a82bb4fc89 - <rustc_mir_transform[9616e0e93931520b]::inline::Inliner>::process_blocks
  14:     0x71a82bb4fd09 - <rustc_mir_transform[9616e0e93931520b]::inline::Inliner>::process_blocks
  15:     0x71a82bb4f126 - <rustc_mir_transform[9616e0e93931520b]::inline::Inline as rustc_middle[2e745f839ecdcb12]::mir::MirPass>::run_pass
  16:     0x71a82b201cd1 - rustc_mir_transform[9616e0e93931520b]::pass_manager::run_passes_inner
  17:     0x71a82b7a1df2 - rustc_mir_transform[9616e0e93931520b]::optimized_mir
  18:     0x71a82c143ddb - rustc_query_impl[52474172086763ba]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[52474172086763ba]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e745f839ecdcb12]::query::erase::Erased<[u8; 8usize]>>
  19:     0x71a82b228434 - rustc_query_system[1f2263bc77e8d28d]::query::plumbing::try_execute_query::<rustc_query_impl[52474172086763ba]::DynamicConfig<rustc_query_system[1f2263bc77e8d28d]::query::caches::DefIdCache<rustc_middle[2e745f839ecdcb12]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[52474172086763ba]::plumbing::QueryCtxt, false>
  20:     0x71a82b2279df - rustc_query_impl[52474172086763ba]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  21:     0x71a827f13204 - <rustc_middle[2e745f839ecdcb12]::ty::context::TyCtxt>::instance_mir
  22:     0x71a82b9af306 - rustc_interface[922598e417aca69f]::passes::run_required_analyses
  23:     0x71a82bd3611e - rustc_interface[922598e417aca69f]::passes::analysis
  24:     0x71a82bd360f1 - rustc_query_impl[52474172086763ba]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[52474172086763ba]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[2e745f839ecdcb12]::query::erase::Erased<[u8; 1usize]>>
  25:     0x71a82c18efae - rustc_query_system[1f2263bc77e8d28d]::query::plumbing::try_execute_query::<rustc_query_impl[52474172086763ba]::DynamicConfig<rustc_query_system[1f2263bc77e8d28d]::query::caches::SingleCache<rustc_middle[2e745f839ecdcb12]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[52474172086763ba]::plumbing::QueryCtxt, false>
  26:     0x71a82c18ed0f - rustc_query_impl[52474172086763ba]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  27:     0x71a82bfced29 - rustc_interface[922598e417aca69f]::interface::run_compiler::<core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>, rustc_driver_impl[7bc6674bbf855457]::run_compiler::{closure#0}>::{closure#1}
  28:     0x71a82bfb6690 - std[c898dee7a900a719]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[922598e417aca69f]::util::run_in_thread_with_globals<rustc_interface[922598e417aca69f]::util::run_in_thread_pool_with_globals<rustc_interface[922598e417aca69f]::interface::run_compiler<core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>, rustc_driver_impl[7bc6674bbf855457]::run_compiler::{closure#0}>::{closure#1}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>::{closure#0}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>
  29:     0x71a82bfb6cfa - <<std[c898dee7a900a719]::thread::Builder>::spawn_unchecked_<rustc_interface[922598e417aca69f]::util::run_in_thread_with_globals<rustc_interface[922598e417aca69f]::util::run_in_thread_pool_with_globals<rustc_interface[922598e417aca69f]::interface::run_compiler<core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>, rustc_driver_impl[7bc6674bbf855457]::run_compiler::{closure#0}>::{closure#1}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>::{closure#0}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57139b9ad86af3c3]::result::Result<(), rustc_span[6e02c34e35948369]::ErrorGuaranteed>>::{closure#1} as core[57139b9ad86af3c3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x71a82bfb706b - std::sys::pal::unix::thread::Thread::new::thread_start::h2b4f313cc68cf720
  31:     0x71a82d72139d - <unknown>
  32:     0x71a82d7a649c - <unknown>
  33:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (e5b3e68ab 2024-08-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir -Z inline-mir=yes -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `field_array`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors; 4 warnings emitted

Some errors have detailed explanations: E0185, E0601.
For more information about an error, try `rustc --explain E0185`.

```

</p>
</details>

### LINKED ISSUE #129127: ICE: unhandled type `unhandled type: &'{erased} mut Closure`
auto-reduced (treereduce-rust):
````rust
pub struct Statement;

pub struct Rows<'stmt>(&'stmt Statement);

impl<'stmt> Iterator for Rows<'stmt> {
    type Item = String;

    fn next() -> Option<Self::Item> {
        let stmt = Statement;
        let rows = Rows(&stmt);
        rows.map(|row| row).next()

        // x
        //
    }
}

fn get_names() -> Option<String> {
    let stmt = Statement;
    let rows = Rows(&stmt);
    rows.map(|row| row).next()

    // x
    //
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
// This is a reduction of a concrete test illustrating a case that was
// annoying to Rust developer stephaneyfx (see issue #46413).
// With resolving issue #54556, pnkfelix hopes that the new diagnostic
// With resolving issue #54556, pnkfelix hopes that the new diagnostic
// output produced by NLL helps to *explain* the semantic significance
// of temp drop order, and thus why storing the result in `x` and then
// returning `x` works.

pub struct Statement;

pub struct Rows<'stmt>(&'stmt Statement);

impl<'stmt> Drop for Option<String> {
    fn drop(&mut self) {}
}

impl<'stmt> Iterator for Rows<'stmt> {
    type Item = String;

    fn next() -> Option<Self::Item> {
    let stmt = Statement;
    let rows = Rows(&stmt); //~ ERROR does not live long enough
    rows.map(|row| row).next()
    // let x = rows.map(|row| row).next();
    // x
    //
    // Removing the map works too as does removing the Drop impl.
}
}

fn drop(&mut self) {}

fn get_names() -> Option<String> {
    let stmt = Statement;
    let rows = Rows(&stmt); //~ ERROR does not live long enough
    rows.map(|row| row).next()
    // let x = rows.map(|row| row).next();
    // x
    //
    // Removing the map works too as does removing the Drop impl.
}

````
</p>
</details>

Version information
````
rustc 1.82.0-nightly (3139ff09e 2024-08-15)
binary: rustc
commit-hash: 3139ff09e9d07f7700f8d15ed25a231e29c43627
commit-date: 2024-08-15
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir -Zcross-crate-inline-threshold=always`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.NrtTvI7Be5z2/rustc_testrunner_tmpdir_reporting.g9SosB3OsY2q/mvce.rs:25:2
   |
25 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.NrtTvI7Be5z2/rustc_testrunner_tmpdir_reporting.g9SosB3OsY2q/mvce.rs`

error[E0186]: method `next` has a `&mut self` declaration in the trait, but not in the impl
 --> /tmp/icemaker_global_tempdir.NrtTvI7Be5z2/rustc_testrunner_tmpdir_reporting.g9SosB3OsY2q/mvce.rs:8:5
  |
8 |     fn next() -> Option<Self::Item> {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut self` in impl
  |
  = note: `next` from trait: `fn(&mut Self) -> Option<<Self as Iterator>::Item>`

error: internal compiler error: compiler/rustc_mir_transform/src/validate.rs:1491:30: unhandled type: &'{erased} mut Closure(DefId(0:13 ~ mvce[127c]::{impl#0}::next::{closure#0}), ['{erased}, i16, Binder { value: extern "RustCall" fn((std::string::String,)) -> std::string::String, bound_vars: [] }, ()])

thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:1491:30:
Box<dyn Any>
stack backtrace:
   0:     0x72956f1cb7fd - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbd75d7a8055bf739
   1:     0x72956fa04059 - core::fmt::write::h5f25313cecccceeb
   2:     0x7295709aa9d1 - std::io::Write::write_fmt::h17a84ab5b179ddb5
   3:     0x72956f1cdedb - std::panicking::default_hook::{{closure}}::h49f53d56c8f7e527
   4:     0x72956f1cdb4e - std::panicking::default_hook::h00ed981b528c65ea
   5:     0x72956e354309 - std[e33d86a7a723a6e1]::panicking::update_hook::<alloc[f0b0d1fafd7580bd]::boxed::Box<rustc_driver_impl[58349887e35c8b09]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x72956f1ce7f7 - std::panicking::rust_panic_with_hook::h3d0aa5d214fe032a
   7:     0x72956e38e671 - std[e33d86a7a723a6e1]::panicking::begin_panic::<rustc_errors[e83ab56271777d9d]::ExplicitBug>::{closure#0}
   8:     0x72956e3816b6 - std[e33d86a7a723a6e1]::sys::backtrace::__rust_end_short_backtrace::<std[e33d86a7a723a6e1]::panicking::begin_panic<rustc_errors[e83ab56271777d9d]::ExplicitBug>::{closure#0}, !>
   9:     0x72956e381436 - std[e33d86a7a723a6e1]::panicking::begin_panic::<rustc_errors[e83ab56271777d9d]::ExplicitBug>
  10:     0x72956e397651 - <rustc_errors[e83ab56271777d9d]::diagnostic::BugAbort as rustc_errors[e83ab56271777d9d]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x72956e95abe4 - rustc_middle[110fa1e98ae6b18b]::util::bug::opt_span_bug_fmt::<rustc_span[179c096983d138e1]::span_encoding::Span>::{closure#0}
  12:     0x72956e9407fa - rustc_middle[110fa1e98ae6b18b]::ty::context::tls::with_opt::<rustc_middle[110fa1e98ae6b18b]::util::bug::opt_span_bug_fmt<rustc_span[179c096983d138e1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x72956e94068b - rustc_middle[110fa1e98ae6b18b]::ty::context::tls::with_context_opt::<rustc_middle[110fa1e98ae6b18b]::ty::context::tls::with_opt<rustc_middle[110fa1e98ae6b18b]::util::bug::opt_span_bug_fmt<rustc_span[179c096983d138e1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x72956c438250 - rustc_middle[110fa1e98ae6b18b]::util::bug::bug_fmt
  15:     0x72956cf744bc - rustc_mir_transform[741e50beaeca447e]::validate::validate_types
  16:     0x72956cf5642e - <rustc_mir_transform[741e50beaeca447e]::validate::Validator as rustc_middle[110fa1e98ae6b18b]::mir::MirPass>::run_pass
  17:     0x72956dc7e930 - rustc_mir_transform[741e50beaeca447e]::pass_manager::validate_body
  18:     0x72956fa02693 - rustc_mir_transform[741e50beaeca447e]::pass_manager::run_passes_inner
  19:     0x7295703d47f7 - rustc_mir_transform[741e50beaeca447e]::optimized_mir
  20:     0x7295703c1c5d - rustc_query_impl[2d64fd05a0316b8c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d64fd05a0316b8c]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[110fa1e98ae6b18b]::query::erase::Erased<[u8; 8usize]>>
  21:     0x72956fa281a7 - rustc_query_system[63eaae8e4727c3d2]::query::plumbing::try_execute_query::<rustc_query_impl[2d64fd05a0316b8c]::DynamicConfig<rustc_query_system[63eaae8e4727c3d2]::query::caches::DefIdCache<rustc_middle[110fa1e98ae6b18b]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[2d64fd05a0316b8c]::plumbing::QueryCtxt, false>
  22:     0x72956fa2775f - rustc_query_impl[2d64fd05a0316b8c]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  23:     0x72956c537429 - <rustc_middle[110fa1e98ae6b18b]::ty::context::TyCtxt>::instance_mir
  24:     0x729570486506 - rustc_interface[5dc7c791b1753136]::passes::run_required_analyses
  25:     0x72957054369e - rustc_interface[5dc7c791b1753136]::passes::analysis
  26:     0x729570543671 - rustc_query_impl[2d64fd05a0316b8c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[2d64fd05a0316b8c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[110fa1e98ae6b18b]::query::erase::Erased<[u8; 1usize]>>
  27:     0x72957096a62e - rustc_query_system[63eaae8e4727c3d2]::query::plumbing::try_execute_query::<rustc_query_impl[2d64fd05a0316b8c]::DynamicConfig<rustc_query_system[63eaae8e4727c3d2]::query::caches::SingleCache<rustc_middle[110fa1e98ae6b18b]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[2d64fd05a0316b8c]::plumbing::QueryCtxt, false>
  28:     0x72957096a38f - rustc_query_impl[2d64fd05a0316b8c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7295707dd0e9 - rustc_interface[5dc7c791b1753136]::interface::run_compiler::<core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>, rustc_driver_impl[58349887e35c8b09]::run_compiler::{closure#0}>::{closure#1}
  30:     0x7295707c6610 - std[e33d86a7a723a6e1]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[5dc7c791b1753136]::util::run_in_thread_with_globals<rustc_interface[5dc7c791b1753136]::util::run_in_thread_pool_with_globals<rustc_interface[5dc7c791b1753136]::interface::run_compiler<core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>, rustc_driver_impl[58349887e35c8b09]::run_compiler::{closure#0}>::{closure#1}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>::{closure#0}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>
  31:     0x7295707c6c7a - <<std[e33d86a7a723a6e1]::thread::Builder>::spawn_unchecked_<rustc_interface[5dc7c791b1753136]::util::run_in_thread_with_globals<rustc_interface[5dc7c791b1753136]::util::run_in_thread_pool_with_globals<rustc_interface[5dc7c791b1753136]::interface::run_compiler<core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>, rustc_driver_impl[58349887e35c8b09]::run_compiler::{closure#0}>::{closure#1}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>::{closure#0}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3fe3910426b5ab0e]::result::Result<(), rustc_span[179c096983d138e1]::ErrorGuaranteed>>::{closure#1} as core[3fe3910426b5ab0e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7295707c6feb - std::sys::pal::unix::thread::Thread::new::thread_start::h2aa5d6e6e369f96b
  33:     0x729571f6639d - <unknown>
  34:     0x729571feb49c - <unknown>
  35:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (3139ff09e 2024-08-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z cross-crate-inline-threshold=always -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `get_names`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0186, E0601.
For more information about an error, try `rustc --explain E0186`.

```

</p>
</details>

### LINKED ISSUE #129214: ICE: `Encountered error SignatureMismatch`
auto-reduced (treereduce-rust):
````rust
//@ run-pass

trait to_str {}

trait map<T> {
    fn map<U, F>(&self, f: F) -> Vec<U>
    where
        F: FnMut(&Box<usize>) -> U;
}
impl<T> map<T> for Vec<T> {
    fn map<U, F>(&self, mut f: F) -> Vec<U>
    where
        F: FnMut(&T) -> U,
    {
        let mut r = Vec::new();
        for i in self {
            r.push(f(i));
        }
        r
    }
}

fn foo<U, T: map<U>>(x: T) -> Vec<String> {
    x.map(|_e| "hi".to_string())
}

pub fn main() {
    assert_eq!(foo(vec![1]), ["hi".to_string()]);
}


````

<details><summary><strong>original code</strong></summary>
<p>

original:
````rust
//@ run-pass
#![repr(align=8)]



trait to_str {
    fn to_string_(&self) -> String;
}
impl to_str for isize {
    fn to_string_(&self) -> String { self.to_string() }
}
impl to_str for String {
    fn to_string_(&self) -> String { self.clone() }
}
impl to_str for () {
    fn to_string_(&self) -> String { "()".to_string() }
}

trait map<T> {
    fn map<U, F>(&self, f: F) -> Vec<U> where F: FnMut(&Box<usize>) -> U;
}
impl<T> map<T> for Vec<T> {
    fn map<U, F>(&self, mut f: F) -> Vec<U> where F: FnMut(&T) -> U {
        let mut r = Vec::new();
        for i in self {
            r.push(f(i));
        }
        r
    }
}

fn foo<U, T: map<U>>(x: T) -> Vec<String> {
    x.map(|_e| "hi".to_string() )
}
fn bar<U:to_str,T:map<U>>(x: T) -> Vec<String> {
    x.map(|_e| _e.to_string_() )
}

pub fn main() {
    assert_eq!(foo(vec![1]), ["hi".to_string()]);
    assert_eq!(bar::<isize, Vec<isize> >(vec![4, 5]), ["4".to_string(), "5".to_string()]);
    assert_eq!(bar::<String, Vec<String> >(vec!["x".to_string(), "y".to_string()]),
               ["x".to_string(), "y".to_string()]);
    assert_eq!(bar::<(), Vec<()>>(vec![()]), ["()".to_string()]);
}

````
</p>
</details>

Version information
````
rustc 1.82.0-nightly (0f26ee4fd 2024-08-17)
binary: rustc
commit-hash: 0f26ee4fd95a1c046582dfb18892f520788e2c2c
commit-date: 2024-08-17
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zvalidate-mir -Copt-level=3 --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: trait `to_str` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:3:7
  |
3 | trait to_str {}
  |       ^^^^^^ help: convert the identifier to upper camel case: `ToStr`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: trait `map` should have an upper camel case name
 --> /tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:5:7
  |
5 | trait map<T> {
  |       ^^^ help: convert the identifier to upper camel case: `Map`

error[E0276]: impl has stricter requirements than trait
  --> /tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:13:12
   |
6  | /     fn map<U, F>(&self, f: F) -> Vec<U>
7  | |     where
8  | |         F: FnMut(&Box<usize>) -> U;
   | |___________________________________- definition of `map` from trait
...
13 |           F: FnMut(&T) -> U,
   |              ^^^^^^^^^^^^^^ impl has extra requirement `for<'a> F: FnMut(&'a T)`

error[E0276]: impl has stricter requirements than trait
  --> /tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:13:25
   |
6  | /     fn map<U, F>(&self, f: F) -> Vec<U>
7  | |     where
8  | |         F: FnMut(&Box<usize>) -> U;
   | |___________________________________- definition of `map` from trait
...
13 |           F: FnMut(&T) -> U,
   |                           ^ impl has extra requirement `for<'a> F: FnOnce(&'a T)`

error: internal compiler error: compiler/rustc_traits/src/codegen.rs:44:13: Encountered error `SignatureMismatch(SignatureMismatchData { found_trait_ref: <{closure@/tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:24:11: 24:15} as std::ops::FnMut<(&std::boxed::Box<usize>,)>>, expected_trait_ref: <{closure@/tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:24:11: 24:15} as std::ops::FnMut<(&i32,)>>, terr: Sorts(ExpectedFound { expected: i32, found: std::boxed::Box<usize, std::alloc::Global> }) })` selecting `<{closure@/tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:24:11: 24:15} as std::ops::FnMut<(&i32,)>>` during codegen

thread 'rustc' panicked at compiler/rustc_traits/src/codegen.rs:44:13:
Box<dyn Any>
stack backtrace:
   0:     0x7d4a373c429d - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hce35dec2bed7e8e1
   1:     0x7d4a37c05297 - core::fmt::write::haaf8a728f3019c12
   2:     0x7d4a38ebbd91 - std::io::Write::write_fmt::hb0dc5188703aea0d
   3:     0x7d4a373c697b - std::panicking::default_hook::{{closure}}::h35c501ae74c82675
   4:     0x7d4a373c65ee - std::panicking::default_hook::hc1ddd62643c4c855
   5:     0x7d4a36558729 - std[54b021f941472252]::panicking::update_hook::<alloc[8840b3d3a55bb7af]::boxed::Box<rustc_driver_impl[ec4d44b725e7aa11]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x7d4a373c7297 - std::panicking::rust_panic_with_hook::h7960ad04eaeb646d
   7:     0x7d4a36593111 - std[54b021f941472252]::panicking::begin_panic::<rustc_errors[2e519a482e3c741a]::ExplicitBug>::{closure#0}
   8:     0x7d4a36586156 - std[54b021f941472252]::sys::backtrace::__rust_end_short_backtrace::<std[54b021f941472252]::panicking::begin_panic<rustc_errors[2e519a482e3c741a]::ExplicitBug>::{closure#0}, !>
   9:     0x7d4a36581536 - std[54b021f941472252]::panicking::begin_panic::<rustc_errors[2e519a482e3c741a]::ExplicitBug>
  10:     0x7d4a3659c0f1 - <rustc_errors[2e519a482e3c741a]::diagnostic::BugAbort as rustc_errors[2e519a482e3c741a]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7d4a36b5f6c4 - rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt::<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}
  12:     0x7d4a36b452da - rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_opt::<rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7d4a36b4516b - rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_context_opt::<rustc_middle[10ec7aec7d9fdda3]::ty::context::tls::with_opt<rustc_middle[10ec7aec7d9fdda3]::util::bug::opt_span_bug_fmt<rustc_span[a5a4c6b08f7cf6f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7d4a34650ac0 - rustc_middle[10ec7aec7d9fdda3]::util::bug::bug_fmt
  15:     0x7d4a34628187 - rustc_traits[87fc0fd8b38a9555]::codegen::codegen_select_candidate
  16:     0x7d4a381ef9f7 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::codegen_select_candidate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 16usize]>>
  17:     0x7d4a381efd23 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::DefaultCache<(rustc_middle[10ec7aec7d9fdda3]::ty::ParamEnv, rustc_type_ir[40aaada2a0110c33]::predicate::TraitRef<rustc_middle[10ec7aec7d9fdda3]::ty::context::TyCtxt>), rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  18:     0x7d4a381ef99d - rustc_query_impl[69287ea093d06d1d]::query_impl::codegen_select_candidate::get_query_non_incr::__rust_end_short_backtrace
  19:     0x7d4a3514619c - rustc_ty_utils[6c9943a590e2da67]::instance::resolve_instance_raw
  20:     0x7d4a383965e9 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::resolve_instance_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 32usize]>>
  21:     0x7d4a38396929 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::DefaultCache<rustc_middle[10ec7aec7d9fdda3]::ty::ParamEnvAnd<(rustc_span[a5a4c6b08f7cf6f]::def_id::DefId, &rustc_middle[10ec7aec7d9fdda3]::ty::list::RawList<(), rustc_middle[10ec7aec7d9fdda3]::ty::generic_args::GenericArg>)>, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 32usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  22:     0x7d4a38396564 - rustc_query_impl[69287ea093d06d1d]::query_impl::resolve_instance_raw::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7d4a37c3b2d3 - <rustc_middle[10ec7aec7d9fdda3]::ty::instance::Instance>::try_resolve
  24:     0x7d4a38ba52e9 - rustc_mir_transform[c8fa74b5a51f9a1a]::inline::cycle::mir_callgraph_reachable::process
  25:     0x7d4a38ba5a30 - rustc_mir_transform[c8fa74b5a51f9a1a]::inline::cycle::mir_callgraph_reachable::process
  26:     0x7d4a38ba4b14 - rustc_mir_transform[c8fa74b5a51f9a1a]::inline::cycle::mir_callgraph_reachable
  27:     0x7d4a38ba49a9 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::mir_callgraph_reachable::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7d4a38ba496b - <rustc_query_impl[69287ea093d06d1d]::query_impl::mir_callgraph_reachable::dynamic_query::{closure#2} as core[5070cb7ec77c977]::ops::function::FnOnce<(rustc_middle[10ec7aec7d9fdda3]::ty::context::TyCtxt, (rustc_middle[10ec7aec7d9fdda3]::ty::instance::Instance, rustc_span[a5a4c6b08f7cf6f]::def_id::LocalDefId))>>::call_once
  29:     0x7d4a3838c719 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::DefaultCache<(rustc_middle[10ec7aec7d9fdda3]::ty::instance::Instance, rustc_span[a5a4c6b08f7cf6f]::def_id::LocalDefId), rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  30:     0x7d4a3838c44c - rustc_query_impl[69287ea093d06d1d]::query_impl::mir_callgraph_reachable::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7d4a385faf85 - <rustc_mir_transform[c8fa74b5a51f9a1a]::inline::Inliner>::try_inlining
  32:     0x7d4a385f8820 - <rustc_mir_transform[c8fa74b5a51f9a1a]::inline::Inliner>::process_blocks
  33:     0x7d4a385f7ce6 - <rustc_mir_transform[c8fa74b5a51f9a1a]::inline::Inline as rustc_middle[10ec7aec7d9fdda3]::mir::MirPass>::run_pass
  34:     0x7d4a37c02151 - rustc_mir_transform[c8fa74b5a51f9a1a]::pass_manager::run_passes_inner
  35:     0x7d4a38605a37 - rustc_mir_transform[c8fa74b5a51f9a1a]::optimized_mir
  36:     0x7d4a3862925d - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7d4a37c25ea7 - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::DefIdCache<rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  38:     0x7d4a37c2545f - rustc_query_impl[69287ea093d06d1d]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7d4a347845c4 - <rustc_middle[10ec7aec7d9fdda3]::ty::context::TyCtxt>::instance_mir
  40:     0x7d4a38386406 - rustc_interface[f40e7651e6b02ea1]::passes::run_required_analyses
  41:     0x7d4a3875c49e - rustc_interface[f40e7651e6b02ea1]::passes::analysis
  42:     0x7d4a3875c471 - rustc_query_impl[69287ea093d06d1d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[69287ea093d06d1d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>
  43:     0x7d4a38b867ee - rustc_query_system[1449707d44461b06]::query::plumbing::try_execute_query::<rustc_query_impl[69287ea093d06d1d]::DynamicConfig<rustc_query_system[1449707d44461b06]::query::caches::SingleCache<rustc_middle[10ec7aec7d9fdda3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[69287ea093d06d1d]::plumbing::QueryCtxt, false>
  44:     0x7d4a38b8654f - rustc_query_impl[69287ea093d06d1d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7d4a389d38ea - rustc_interface[f40e7651e6b02ea1]::interface::run_compiler::<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}
  46:     0x7d4a389b3210 - std[54b021f941472252]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_with_globals<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_pool_with_globals<rustc_interface[f40e7651e6b02ea1]::interface::run_compiler<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>
  47:     0x7d4a389b387a - <<std[54b021f941472252]::thread::Builder>::spawn_unchecked_<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_with_globals<rustc_interface[f40e7651e6b02ea1]::util::run_in_thread_pool_with_globals<rustc_interface[f40e7651e6b02ea1]::interface::run_compiler<core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>, rustc_driver_impl[ec4d44b725e7aa11]::run_compiler::{closure#0}>::{closure#1}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5070cb7ec77c977]::result::Result<(), rustc_span[a5a4c6b08f7cf6f]::ErrorGuaranteed>>::{closure#1} as core[5070cb7ec77c977]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7d4a389b3beb - std::sys::pal::unix::thread::Thread::new::thread_start::he8fde62ed04f9a93
  49:     0x7d4a3a11039d - <unknown>
  50:     0x7d4a3a19549c - <unknown>
  51:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.82.0-nightly (0f26ee4fd 2024-08-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir -C opt-level=3 --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
#0 [codegen_select_candidate] computing candidate for `<{closure@/tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:24:11: 24:15} as core::ops::function::FnMut<(&i32,)>>`
#1 [resolve_instance_raw] resolving instance `<{closure@/tmp/icemaker_global_tempdir.CTvLxe24vLkE/rustc_testrunner_tmpdir_reporting.sonlNjO1Rab2/mvce.rs:24:11: 24:15} as core::ops::function::FnMut<(&i32,)>>::call_mut`
end of query stack
error: aborting due to 3 previous errors; 2 warnings emitted

For more information about this error, try `rustc --explain E0276`.

```

</p>
</details>

### LINKED ISSUE #131294: ICE: `deref projection of non-dereferenceable ty PlaceTy`
auto-reduced (treereduce-rust):
````rust
pub struct Statement;

pub struct Rows<'stmt>(&'stmt Statement);

impl<'stmt> Iterator for Rows<'stmt> {
    type Item = String;

    fn next() -> Option<Self::Item> {
        format!("Hello {}", "world").into()
    }
}

fn get_names() -> Option<String> {
    let stmt = Statement;
    let rows = Rows(&stmt);
    rows.map(|row| row).next()
}

````

original:
````rust
pub struct Statement;

pub struct Rows<'stmt>(&'stmt Statement);

impl<'stmt> Iterator for Rows<'stmt> {
    type Item = String;

    fn next() -> Option<Self::Item> {
        let stmt = Statement;
        let rows = Rows(&stmt);
        format!("Hello {}", "world").into()

        // x
        //
    }
}

fn get_names() -> Option<String> {
    let stmt = Statement;
    let rows = Rows(&stmt);
    rows.map(|row| row).next()

    // x
    //
}

````

Version information
````
rustc 1.83.0-nightly (5a4ee43c3 2024-10-05)
binary: rustc
commit-hash: 5a4ee43c387110736440cecc375cb5aedc441dbc
commit-date: 2024-10-05
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zmir-opt-level=5 -Zvalidate-mir -Zcross-crate-inline-threshold=always`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.6F6DD8mcNIb4/rustc_testrunner_tmpdir_reporting.T2OQxr9MgywH/mvce.rs:23:2
   |
23 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.6F6DD8mcNIb4/rustc_testrunner_tmpdir_reporting.T2OQxr9MgywH/mvce.rs`

error[E0186]: method `next` has a `&mut self` declaration in the trait, but not in the impl
 --> /tmp/icemaker_global_tempdir.6F6DD8mcNIb4/rustc_testrunner_tmpdir_reporting.T2OQxr9MgywH/mvce.rs:8:5
  |
8 |     fn next() -> Option<Self::Item> {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut self` in impl
  |
  = note: `next` from trait: `fn(&mut Self) -> Option<<Self as Iterator>::Item>`

error: internal compiler error: compiler/rustc_middle/src/mir/tcx.rs:84:21: deref projection of non-dereferenceable ty PlaceTy { ty: [core::fmt::rt::Argument<'{erased}>; 0_usize], variant_index: None }

thread 'rustc' panicked at compiler/rustc_middle/src/mir/tcx.rs:84:21:
Box<dyn Any>
stack backtrace:
   0:     0x74eb187249fa - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h585b06d402bc00d5
   1:     0x74eb18e03426 - core::fmt::write::h62d1c51a5a367817
   2:     0x74eb1a01a651 - std::io::Write::write_fmt::hd7881933ac2a1e16
   3:     0x74eb18724852 - std::sys::backtrace::BacktraceLock::print::ha0ac5d8e3803f857
   4:     0x74eb18726d26 - std::panicking::default_hook::{{closure}}::h7a48a96dd6d0b686
   5:     0x74eb18726b70 - std::panicking::default_hook::h4ad77b5924a748da
   6:     0x74eb177db8ff - std[f6927571c1bb7893]::panicking::update_hook::<alloc[1b6d6df6cca9b2d3]::boxed::Box<rustc_driver_impl[83de0f0d7a3bbaf8]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x74eb18727438 - std::panicking::rust_panic_with_hook::h15ea114d0f0705b7
   8:     0x74eb17815451 - std[f6927571c1bb7893]::panicking::begin_panic::<rustc_errors[33bfe5951055d2f3]::ExplicitBug>::{closure#0}
   9:     0x74eb178084f6 - std[f6927571c1bb7893]::sys::backtrace::__rust_end_short_backtrace::<std[f6927571c1bb7893]::panicking::begin_panic<rustc_errors[33bfe5951055d2f3]::ExplicitBug>::{closure#0}, !>
  10:     0x74eb178084b3 - std[f6927571c1bb7893]::panicking::begin_panic::<rustc_errors[33bfe5951055d2f3]::ExplicitBug>
  11:     0x74eb1781ece1 - <rustc_errors[33bfe5951055d2f3]::diagnostic::BugAbort as rustc_errors[33bfe5951055d2f3]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x74eb17e49ca4 - rustc_middle[4aa8808438232afe]::util::bug::opt_span_bug_fmt::<rustc_span[b73f4c38f6b79966]::span_encoding::Span>::{closure#0}
  13:     0x74eb17e2fb1a - rustc_middle[4aa8808438232afe]::ty::context::tls::with_opt::<rustc_middle[4aa8808438232afe]::util::bug::opt_span_bug_fmt<rustc_span[b73f4c38f6b79966]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x74eb17e2f9ab - rustc_middle[4aa8808438232afe]::ty::context::tls::with_context_opt::<rustc_middle[4aa8808438232afe]::ty::context::tls::with_opt<rustc_middle[4aa8808438232afe]::util::bug::opt_span_bug_fmt<rustc_span[b73f4c38f6b79966]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x74eb153daa80 - rustc_middle[4aa8808438232afe]::util::bug::bug_fmt
  16:     0x74eb1a1cac71 - <rustc_middle[4aa8808438232afe]::mir::tcx::PlaceTy>::projection_ty.cold
  17:     0x74eb1637d221 - rustc_mir_transform[e62bc607d4a6429b]::validate::validate_types
  18:     0x74eb163bb165 - <rustc_mir_transform[e62bc607d4a6429b]::validate::Validator as rustc_mir_transform[e62bc607d4a6429b]::pass_manager::MirPass>::run_pass
  19:     0x74eb171067c0 - rustc_mir_transform[e62bc607d4a6429b]::pass_manager::validate_body
  20:     0x74eb18e0bb06 - rustc_mir_transform[e62bc607d4a6429b]::pass_manager::run_passes_inner
  21:     0x74eb190ae9a2 - rustc_mir_transform[e62bc607d4a6429b]::optimized_mir
  22:     0x74eb190ad25b - rustc_query_impl[7b31fe52c1943d23]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7b31fe52c1943d23]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4aa8808438232afe]::query::erase::Erased<[u8; 8usize]>>
  23:     0x74eb18e2f378 - rustc_query_system[af74fb06ba218297]::query::plumbing::try_execute_query::<rustc_query_impl[7b31fe52c1943d23]::DynamicConfig<rustc_query_system[af74fb06ba218297]::query::caches::DefIdCache<rustc_middle[4aa8808438232afe]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7b31fe52c1943d23]::plumbing::QueryCtxt, false>
  24:     0x74eb18e2e933 - rustc_query_impl[7b31fe52c1943d23]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  25:     0x74eb16135e79 - <rustc_middle[4aa8808438232afe]::ty::context::TyCtxt>::instance_mir
  26:     0x74eb1921e74a - rustc_interface[a7beddea6b2aa80d]::passes::run_required_analyses
  27:     0x74eb19bf6f9e - rustc_interface[a7beddea6b2aa80d]::passes::analysis
  28:     0x74eb19bf6f71 - rustc_query_impl[7b31fe52c1943d23]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7b31fe52c1943d23]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4aa8808438232afe]::query::erase::Erased<[u8; 1usize]>>
  29:     0x74eb19cd31ee - rustc_query_system[af74fb06ba218297]::query::plumbing::try_execute_query::<rustc_query_impl[7b31fe52c1943d23]::DynamicConfig<rustc_query_system[af74fb06ba218297]::query::caches::SingleCache<rustc_middle[4aa8808438232afe]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7b31fe52c1943d23]::plumbing::QueryCtxt, false>
  30:     0x74eb19cd2ecf - rustc_query_impl[7b31fe52c1943d23]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  31:     0x74eb19b2151e - rustc_interface[a7beddea6b2aa80d]::interface::run_compiler::<core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>, rustc_driver_impl[83de0f0d7a3bbaf8]::run_compiler::{closure#0}>::{closure#1}
  32:     0x74eb19bd9150 - std[f6927571c1bb7893]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a7beddea6b2aa80d]::util::run_in_thread_with_globals<rustc_interface[a7beddea6b2aa80d]::util::run_in_thread_pool_with_globals<rustc_interface[a7beddea6b2aa80d]::interface::run_compiler<core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>, rustc_driver_impl[83de0f0d7a3bbaf8]::run_compiler::{closure#0}>::{closure#1}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>::{closure#0}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>
  33:     0x74eb19bd9817 - <<std[f6927571c1bb7893]::thread::Builder>::spawn_unchecked_<rustc_interface[a7beddea6b2aa80d]::util::run_in_thread_with_globals<rustc_interface[a7beddea6b2aa80d]::util::run_in_thread_pool_with_globals<rustc_interface[a7beddea6b2aa80d]::interface::run_compiler<core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>, rustc_driver_impl[83de0f0d7a3bbaf8]::run_compiler::{closure#0}>::{closure#1}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>::{closure#0}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1b34d82e9cff2ed]::result::Result<(), rustc_span[b73f4c38f6b79966]::ErrorGuaranteed>>::{closure#1} as core[e1b34d82e9cff2ed]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x74eb19bda701 - std::sys::pal::unix::thread::Thread::new::thread_start::h4498a525a6fc6a9e
  35:     0x74eb1b27639d - <unknown>
  36:     0x74eb1b2fb49c - <unknown>
  37:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.83.0-nightly (5a4ee43c3 2024-10-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=5 -Z validate-mir -Z cross-crate-inline-threshold=always -Z dump-mir-dir=dir

query stack during panic:
#0 [optimized_mir] optimizing MIR for `get_names`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0186, E0601.
For more information about an error, try `rustc --explain E0186`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Turns `compare_impl_item` into a query (generalizing the existing query for `compare_impl_const`), and uses that in `Instance::resolve` to fail resolution when an implementation is incompatible with the trait it comes from.

Fixes #119701
Fixes #121127
Fixes #121411
Fixes #129075
Fixes #129127
Fixes #129214
Fixes #131294

### CODE REVIEW

**Comment by compiler-errors** [comment]
Even though this has a modest perf hit on incr builds, I still think this should land, since it eliminates a large number of CTFE and inliner ICEs that come from `Instance::resolve`ing signatures that are invalid.

**Comment by compiler-errors** [comment]
r? lcnr maybe? or re-roll, or maybe vibe-check on whether you think this isn't worth the perf hit.

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs [hunk 1]
```diff
@@ -35,6 +35,26 @@ use crate::errors::{LifetimesOrBoundsMismatchOnTrait, MethodShouldReturnFuture};
 
 mod refine;
 
+/// Call the query `tcx.compare_impl_item()` directly instead.
+pub(super) fn compare_impl_item(
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:39]: move this into a submodule so that we don't need to rename them to `_inner`

File: compiler/rustc_ty_utils/src/instance.rs [hunk 2]
```diff
@@ -215,15 +215,11 @@ fn resolve_associated_item<'tcx>(
 
             let args = tcx.erase_regions(args);
 
-            // Check if we just resolved an associated `const` declaration from
-            // a `trait` to an associated `const` definition in an `impl`, where
-            // the definition in the `impl` has the wrong type (for which an
-            // error has already been/will be emitted elsewhere).
-            if leaf_def.item.kind == ty::AssocKind::Const
-                && trait_item_id != leaf_def.item.def_id
+            // Meow
```
Comment (lcnr) [inline compiler/rustc_ty_utils/src/instance.rs:218]: meow

**Review by lcnr — COMMENTED** [review]
r=me after meow

perf hit feels totally acceptable to me

File: compiler/rustc_hir_analysis/src/check/compare_impl_item.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:39]: i kinda just renamed them inner for style reasons, but i could just also revert their names

Comment (lcnr) [reply compiler/rustc_hir_analysis/src/check/compare_impl_item.rs:39]: hmm, then yeah, I would like to revert their naming then :thinking:

**Comment by compiler-errors** [comment]
Addressed the nits, so I'm just gonna re-approve it

@bors r=lcnr

**Comment by compiler-errors** [comment]
lmao, ok I think I know how to turn this into a cycle 🤔

**Comment by lcnr** [comment]
gamer!

**Comment by rylev** [comment]
Perf regressions were excused [here](https://github.com/rust-lang/rust/pull/133365#issuecomment-2495766076)

@rustbot label: +perf-regression-triaged
