### PR TITLE
rustbuild: allow disabling deny(warnings) for bootstrap

### LINKED ISSUE #63911: 1.38 beta fails to bootstrap itself
When using 1.38 beta to bootstrap itself, I get:

```
error: unnecessary `unsafe` block
   --> src/bootstrap/builder.rs:148:19
    |                    
148 |             name: unsafe { ::std::intrinsics::type_name::<S>() },
    |                   ^^^^^^ unnecessary `unsafe` block
    |                  
```

### PR DESCRIPTION
**Pull request by Keruspe**
When deny-warnings is not specified or set to true, the behaviour is the same as before.
When deny-warnings is set to false, warnings are now allowed

Fixes #63911

### CODE REVIEW

File: src/bootstrap/lib.rs [hunk 1]
```diff
@@ -104,7 +104,7 @@
 //! also check out the `src/bootstrap/README.md` file for more information.
 
 // NO-RUSTC-WRAPPER
-#![deny(warnings, rust_2018_idioms, unused_lifetimes)]
+#![deny(rust_2018_idioms, unused_lifetimes)]
```
Comment (petrochenkov) [inline src/bootstrap/lib.rs]: There are several crates with `NO-RUSTC-WRAPPER`.
Supposedly all of them should use this logic + `deny-warnings` should affect the rust_2018_idioms/unused_lifetimes stuff too.

I'm not sure how much code is affected by `RUSTFLAGS` set in `bootstrap.py`.
Perhaps the `#![deny(warnings, rust_2018_idioms, unused_lifetimes)]` can be moved to there?
Or perhaps `bootstrap.py` can define some feature and `NO-RUSTC-WRAPPER` can then use `#![cfg_attr(featuer_name, deny(warnings, rust_2018_idioms, unused_lifetimes))]`?

Comment (petrochenkov) [reply src/bootstrap/lib.rs]: (Warning levels for code going through the wrapper are set in https://github.com/rust-lang/rust/blob/master/src/bootstrap/bin/rustc.rs#L125-L136.)

Comment (Keruspe) [reply src/bootstrap/lib.rs]: Well, bootstrap is special as it's the only crate built from bootstrap.py and not from rustbuild.
The environment modified in this PR is only used for this crate and not for the other ones

File: src/bootstrap/bootstrap.py [hunk 2]
```diff
@@ -631,6 +631,10 @@ def build_bootstrap(self):
         target_linker = self.get_toml("linker", build_section)
         if target_linker is not None:
             env["RUSTFLAGS"] += "-C linker=" + target_linker + " "
+        if self.get_toml("deny-warnings", "rust") == "false":
+            env["RUSTFLAGS"] += "-Awarnings "
```
[the remark this answers is not in the document]
Comment (Keruspe) [reply src/bootstrap/bootstrap.py]: Done

File: src/bootstrap/lib.rs (hunk 1 above)
Comment (Keruspe) [reply src/bootstrap/lib.rs]: Done

**Review by Mark-Simulacrum — COMMENTED** [review]
Modulo this comment and squashed commits r=me

File: src/bootstrap/lib.rs [hunk 3]
```diff
@@ -104,8 +104,6 @@
 //! also check out the `src/bootstrap/README.md` file for more information.
 
 // NO-RUSTC-WRAPPER
-#![deny(warnings, rust_2018_idioms, unused_lifetimes)]
```
[the remark this answers is not in the document]
Comment (Keruspe) [reply src/bootstrap/lib.rs]: This part of bootstrap.py is only used for building the bootstrap crate, not for the other ones (the env map is local to this function, it's not a global env).
Removing this specific NO-RUSTC-WRAPPER line makes sense though as this code is built before the rustc wrapper anyways

[the remark this answers is not in the document]
Comment (Keruspe) [reply src/bootstrap/lib.rs]: Oh, nvm, I hadn't actually grepped for NO-RUSTC-WRAPPER yet.

**Comment by Keruspe** [comment]
squashed

**Comment by Keruspe** [comment]
@Mark-Simulacrum Do you think that it could be backported to 1.38 or should we do that downstream?

**Comment by Mark-Simulacrum** [comment]
We generally don't backport bootstrap changes so I would do so downstream.
