### PR TITLE
More expressions correctly are marked to end with curly braces

### LINKED ISSUE #118859: Let-else not checking for curly brace of inline const before `else`
```rust
#![feature(inline_const)]

fn main() {
    let false = const {
        true
    } else {
        return;
    };
}
```

I believe the intention in let-else is that this code should be considered syntactically invalid, but it compiles successfully today.

If you replace `const` with `unsafe`, it correctly fails to parse.

```console
error: right curly brace `}` before `else` in a `let...else` statement not allowed
 --> src/main.rs:6:5
  |
6 |     } else {
  |     ^
  |
help: wrap the expression in parentheses
  |
4 ~     let false = (unsafe {
5 |         true
6 ~     }) else {
  |
```

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Fixes #118859, and replaces the mentioned match statement with an exhaustive list, so that this code doesn't get overlooked in the future

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
This needs tests for every one of these expressions. Please add them to some relevant subdirectory in `tests/ui`, maybe just `tests/ui/parser`, though you could add a subdirectory to `tests/ui/parser`... up to you.

Also, this causes some code to go from passing to failing, right? If so, we need to nominate this for T-lang discussion.

**Comment by dtolnay** [comment]
> Also, this causes some code to go from passing to failing, right? If so, we need to nominate this for T-lang discussion.

Not any stable code. The only behavior changes in the PR are to `const {}`, `do yeet`, and `become`, all of which are properly feature gated in the parser even inside of #\[cfg(any())\] code.

```rust
#[cfg(any())]
fn repro() {
    let _ = const {} else {};
    let _ = do yeet {} else {};
    let _ = become {} else {};
}
```

```console
error[E0658]: inline-const is experimental
 --> src/lib.rs:3:13
  |
3 |     let _ = const {} else {};
  |             ^^^^^
  |
  = note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information
  = help: add `#![feature(inline_const)]` to the crate attributes to enable

error[E0658]: `do yeet` expression is experimental
 --> src/lib.rs:4:13
  |
4 |     let _ = do yeet {} else {};
  |             ^^^^^^^^^^
  |
  = note: see issue #96373 <https://github.com/rust-lang/rust/issues/96373> for more information
  = help: add `#![feature(yeet_expr)]` to the crate attributes to enable

error[E0658]: `become` expression is experimental
 --> src/lib.rs:5:13
  |
5 |     let _ = become {} else {};
  |             ^^^^^^^^^
  |
  = note: see issue #112788 <https://github.com/rust-lang/rust/issues/112788> for more information
  = help: add `#![feature(explicit_tail_calls)]` to the crate attributes to enable
```

File: compiler/rustc_ast/src/util/classify.rs [hunk 1]
```diff
@@ -40,15 +40,49 @@ pub fn expr_trailing_brace(mut expr: &ast::Expr) -> Option<&ast::Expr> {
...
                 expr = &closure.body;
             }
             Gen(..) | Block(..) | ForLoop(..) | If(..) | Loop(..) | Match(..) | Struct(..)
-            | TryBlock(..) | While(..) => break Some(expr),
-            _ => break None,
+            | TryBlock(..) | While(..) | ConstBlock(_) => break Some(expr),
+            Break(_, _)
+            | Range(_, _, _)
+            | Ret(_)
+            | Yield(_)
```
Comment (compiler-errors) [inline compiler/rustc_ast/src/util/classify.rs:56]: Can you make this more precise? The only pattern that must be matched here is `Yield(None)`. Same with a few of the other below patterns.

**Comment by dtolnay** [comment]
> The only behavior changes in the PR are to `const {}`, `do yeet`, and `become`, all of which are properly feature gated in the parser even inside of #[cfg(any())] code.

But I would like @rust-lang/lang to comment on other cases ending in brace, not touched in this PR, which are stable.

```rust
// ExprKind::FormatArgs
let _ = format_args! {
    "..."
} else {
    return;
};
```

```rust
// ExprKind::MacCall
let Ok(_) = writeln! {
    io::sink(),
    "...",
} else {
    return;
};
```

```rust
// ExprKind::IncludedBytes
let b"..." = include_bytes! {
    concat!(env!("OUT_DIR"), "/the_bytes")
} else {
    return;
};
```

```rust
// ExprKind::InlineAsm
let 0isize = asm! {
    ...
} else {
    return;
};
```

and finally, unstable `offset_of`.

**Comment by WaffleLapkin** [comment]
Nominating for T-lang discussion as per the comment above

**Comment by nnethercote** [comment]
Michael is already effectively serving as reviewer, and clearly knows more about this particular piece of code than I do. Therefore:

r? @compiler-errors

**Comment by GearsDatapacks** [comment]
I have added tests for these cases, and made the match expression more explicit.

**Comment by WaffleLapkin** [comment]
(removed the https://github.com/rust-lang/rust/labels/has-merge-commits because it looks like the merge commits in question were removed)

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the T-lang meeting today.  There was a feeling that the current behavior may not in fact be ambiguous and that it may be fine to leave it as-is.  However, we were a bit unsure about the ask.

@dtolnay: If there's a specific rule that you would propose here, please describe that and why it would be better and then renominate this issue for further discussion.

**Comment by WaffleLapkin** [comment]
We've talked about this today in @rust-lang/lang triage meeting. We were not sure what you are asking/proposing, @dtolnay, maybe you can clarify?

Specifically it was unclear why we would want to prohibit macro examples in your comment (https://github.com/rust-lang/rust/pull/118880#issuecomment-1852543049). Since macros use `!` there is no potential for ambiguity.

We even talked about maybe instead allowing _more_ expressions ending in `}` before `else {`, as there shouldn't actually be ambiguity and it's not fully clear why this restriction is necessary at all.

Reading the test (my personal opinions):
- `{}`, `S{}`, `const{}`, `unsafe{}` — don't see any ambiguity, we could just allow that
- `for`, `while`, `a = ` — they all have `()` type, so are useless with let-else, fine to disallow to prevent confusion
- `if+else`, `loop`, `match` — those can be useful with with let-else but also might be confusing 🤷🏻

**Comment by dtolnay** [comment]
A design aspect of the [let-else RFC](https://rust-lang.github.io/rfcs/3137-let-else.html) that was important enough to feature in the 6-sentence summary is that the `EXPRESSION` in the syntax `let PATTERN: TYPE = EXPRESSION else DIVERGING_BLOCK;` must not end in `}`.

This restriction ended up in the RFC based on multiple rounds of feedback.

- The feature originally envisioned by the author did not have this restriction. It only had the essential restriction that `EXPRESSION` must not be `if … {…}` (+`else if`) because in that case the new syntax would collide with stable syntax that already had a different meaning.

- Based on a suggestion in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60let.20pattern.20.3D.20expr.20else.20.7B.20.2E.2E.2E.20.7D.60.20statements) by bstrie shortly before the publication of the RFC, the syntax was made more restrictive to say `EXPRESSION` must not be what the Reference calls [*ExpressionWithBlock*](https://doc.rust-lang.org/1.74.1/reference/expressions.html). The change was made in https://github.com/rust-lang/rfcs/pull/3137/commits/3438586767d104cc48087329c2402a1416507bc7 and means the expression must not be any of `{…}`, `unsafe {…}`, `loop {…}`, `while … {…}`, `for … in … {…}`, `if … {…}` (+`else if` +`else`), or `match … {…}`.

- The wording to disallow the above expressions was made more precise in response to [Niko's non-blocking concern](https://github.com/rust-lang/rfcs/pull/3137#issuecomment-867518963). The wording improvement was made in https://github.com/rust-lang/rfcs/pull/3137/commits/89c5b6e13e2b023ac22bd0fc924a8a9921e569e9 without changing the intent of the restriction.

- In response to [steffahn's insightful comment](https://github.com/rust-lang/rfcs/pull/3137#issuecomment-875010250) and a related older [unresolved review by nagisa](https://github.com/rust-lang/rfcs/pull/3137#discussion_r645967967) and [followup](https://github.com/rust-lang/rfcs/pull/3137#issuecomment-879793422), followed by several +1 comments in GitHub and Zulip, and [digama0's review](https://github.com/rust-lang/rfcs/pull/3137#pullrequestreview-705746580), the syntax was made more restrictive again to disallow `EXPRESSION` from being anything having the last token `}`. This change was https://github.com/rust-lang/rfcs/pull/3137/commits/c0c2fccc15c7812f182d8e042270086514b11278. It disallows `async {…}`, `try {…}`, `const {…}`, `Struct {…}`, `|…| {…}`, `&{…}`, `break {…}`, `return {…}` and many others. This restriction was not implemented by the compiler.

- With further iteration from Zulip, the wording was clarified in https://github.com/rust-lang/rfcs/pull/3137/commits/b6b87d6a9f32de75f0a25c731404166881eda750 to emphasize that any expression ending in `}` **before macro expansion** is not allowed. `mac! {…}` is one such example. This restriction was not implemented by the compiler and the cases in https://github.com/rust-lang/rust/pull/118880#issuecomment-1852543049 all violate it.

The compiler's implementation of let-else did not implement the restriction described by the accepted RFC, so some programs that the RFC says are invalid syntax are accepted by stable Rust compilers since 1.65.0.

To understand why disallowing only *ExpressionWithBlock* is not sufficient, see the code samples containing `-if` in steffahn's comment.

Separately from the ambiguities explained in that comment, steffahn also was I think the first to note a human value in having `} else {` **always** mean an `else` corresponding to an `if`, as opposed to an `else` corresponding to a `let`. This is voiced in steffahn's comment linked above, as well as subsequent discussion on Zulip arriving at agreement about the final strengthenings (_"on the grounds that it makes it easy to distinguish let from let-else by looking for an `else` not preceded by `}`"_).

https://github.com/rust-lang/rfcs/pull/3137#issuecomment-879838580 has a summary of the consensus from Zulip and the state of the RFC after the second strengthening of the restriction.

https://github.com/rust-lang/rfcs/pull/3137#issuecomment-880086112 expresses the author's fondness in favor of the second strengthened restriction, _"to be clear to human readers"_, which I also agree with, and is further reinforced by a lang team consensus expressed by Josh in Zulip: ***"Based on the lang team consensus, the thing we wanted to avoid was `let PAT = some_construct_with { braces } else { diverge };`"***

At the time, only one single exception to the must-not-end-in-`}` form of the restriction was still being considered, and that was very explicitly the specific case of `{…}`, i.e. `let … = {…} else {…};` with nothing between the `=` and first `{`. _"So, nothing that ends in `}` and doesn't start with `{` unless it's wrapped in parentheses or braces."_ Ultimately there was not consensus about this exception, there was strong opposition in Zulip and it was never written into the RFC or implemented in the compiler.

The issue of `}` before `else` did not get listed as an unresolved question in the final draft of the RFC which got merged. This is because the topic was sufficiently resolved by the discussion described above and the lang team consensus via Zulip, and all parties were in agreement about this iteration of the restriction. So there was no further discussion of it in the [tracking issue](https://github.com/rust-lang/rust/issues/87335) nor during [stabilization](https://github.com/rust-lang/rust/pull/93628) aside from [one brief comment](https://github.com/rust-lang/rust/issues/87335#issuecomment-1015055078) reinforcing that the restriction is intentional and future possibilities are left open.

Mentioning some of the contributors whose comments I have paraphrased, in case their view has changed since then or has not been adequately captured here: @Fishrock123 @digama0 @steffahn @camsteffen @bstrie

> @dtolnay: If there's a specific rule that you would propose here for the handling of this kind of thing, please describe that and why it would be better and then renominate this issue for further discussion.

The rule I like is that `EXPRESSION` must not end in `}`, which was the RFC final draft.

To the extent that the compiler is going to accept some `EXPRESSION` which end in `}` (which is not my preference), I think those cases should be approved by the lang team since so far no exceptions to must-not-end-in-`}` have been through team approval.

**Comment by compiler-errors** [comment]
Thanks for the detailed history, @dtolnay.

@GearsDatapacks: As for this PR, the fact that these remaining expressions can't be fixed without breaking existing code should be recorded in a FIXME, so it isn't forgotten. Since the PR only changes unstable syntax, I can r+ it after that.

Also, please squash all these commits into one.

@rustbot author

File: compiler/rustc_ast/src/util/classify.rs [hunk 2]
```diff
@@ -40,15 +40,49 @@ pub fn expr_trailing_brace(mut expr: &ast::Expr) -> Option<&ast::Expr> {
...
+            | MacCall(_)
+            | IncludedBytes(_)
+            | FormatArgs(_)
+            | Err => break None,
+            // More complex cases
+            // InlineAsm
+            // OffsetOf
+            // MacCall
+            // IncludedBytes
+            // FormatArgs
```
Comment (compiler-errors) [inline compiler/rustc_ast/src/util/classify.rs:85]: Remove this and move all of the stable exprs above that can end in `}` into a separate arm with a `FIXME`.

**Comment by GearsDatapacks** [comment]
I added the FIXME, and squashed the commits into one.

**Review by compiler-errors — APPROVED** [review]

**Comment by camsteffen** [comment]
Is the FIXME actually fixable? If it's an edition thing, how to we record todos for the next edition?

**Comment by compiler-errors** [comment]
> Is the FIXME actually fixable?

Not clear...

> If it's an edition thing, how to we record todos for the next edition?

I also have no idea. I think we may want to open a new tracking issue after T-lang weighs in on the existing inconsistencies, and we can add the relevant 2024 tags to that issue.

**Comment by dtolnay** [comment]
> Is the FIXME actually fixable?

Yes.

Currently on crates.io, here is the prevalence of each kind of expression in the EXPRESSION part of a let-else (using syn::Expr's naming):

- 12623&emsp;Expr::MethodCall
- 4641&emsp;Expr::Path
- 3272&emsp;Expr::Call (function call)
- 1752&emsp;Expr::Reference
- 1368&emsp;Expr::Field
- 1067&emsp;Expr::Try (question mark)
- 476&emsp;Expr::Await
- 192&emsp;Expr::Index
- 185&emsp;Expr::Tuple
- 180&emsp;Expr::Unary
- 80&emsp;Expr::Macro
- 65&emsp;Expr::Paren
- 5&emsp;Expr::Binary
- 3&emsp;Expr::Array
- 1&emsp;Expr::Block
- 1&emsp;Expr::ForLoop
- 1&emsp;Expr::If
- 1&emsp;Expr::Loop
- 1&emsp;Expr::Match
- 1&emsp;Expr::While
- 0&emsp;all others (Assign, Async, Break, Cast, Closure, Const, Continue, Let, Lit, Range, Repeat, Return, Struct, TryBlock, Unsafe, Yield)

Of the 80 macro calls, **all 80 use parenthesis delimiter**. 0 use square bracket delimiter or brace delimiter.

**Comment by digama0** [comment]
I'm curious about the `Expr::Block`, `Expr::ForLoop` and `Expr::While` examples because `Expr::Block` is supposed to be specifically disallowed and the other two should be a type error (you can't refutably match something with type `()`).

**Comment by dtolnay** [comment]
It's parser test cases from rust-analyzer in ra_ap_parser 0.0.189.
https://github.com/rust-lang/rust-analyzer/tree/master/crates/parser/test_data/parser/err

test_data/parser/err/0049_let_else_right_curly_brace_for.rs
test_data/parser/err/0050_let_else_right_curly_brace_loop.rs
test_data/parser/err/0051_let_else_right_curly_brace_match.rs
test_data/parser/err/0052_let_else_right_curly_brace_while.rs
test_data/parser/err/0053_let_else_right_curly_brace_if.rs
test_data/parser/inline/err/0017_let_else_right_curly_brace.rs

**Comment by dtolnay** [comment]
I am moving the lang-nominated label over to #119057 for followup.

@rustbot label -I-lang-nominated
