### PR TITLE
rustc: generalize monomorphic_const_eval to polymorphic constants.

### LINKED ISSUE #23898: enum variants aren't considered to be const during const-evaluation
Spawned off of #5873

``` rust
use self::Category::*;

enum Category {
    A,
    B,
    C,
    NumCategories,
}
const NUM_CATEGORIES: usize = NumCategories as usize;

fn main() {
    let the_categories: [Category; NUM_CATEGORIES] = [A, B, C];
    println!("{:?}", the_categories);
}
```

[playpen](http://is.gd/wHhpXH)

```
<anon>:9:31: 9:44 error: array length constant evaluation error: non-constant path in constant expr [E0250]
<anon>:9 const NUM_CATEGORIES: usize = NumCategories as usize;
                                       ^~~~~~~~~~~~~
<anon>:12:25: 12:51 note: for array length here
<anon>:12     let the_categories: [Category; NUM_CATEGORIES] = [A, B, C];
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

### LINKED ISSUE #41394: ICE thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 18446744073709551615'
Building Servo with rustc 1.18.0-nightly (467aaab50 2017-04-19):

```rust
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 18446744073709551615', /checkout/src/libcollections/vec.rs:1484
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:56
  10: rustc::ty::AdtDef::discriminant_for_variant
  11: rustc_trans::mir::rvalue::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_rvalue
  12: rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_block
  13: rustc_trans::mir::trans_mir
  14: rustc_trans::trans_item::TransItem::define
  15: rustc_trans::base::trans_crate
  16: rustc_driver::driver::phase_4_translate_to_llvm
  17: rustc_driver::driver::compile_input::{{closure}}
  18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  19: rustc::ty::context::TyCtxt::create_and_enter
  20: rustc_driver::driver::phase_3_run_analysis_passes
  21: rustc_driver::driver::compile_input
  22: rustc_driver::run_compiler
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  25: <F as alloc::boxed::FnBox<A>>::call_box
  26: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  27: start_thread
  28: __clone

error: Could not compile `script`.
```

For what it’s worth, 18446744073709551615 is 0xFFFF_FFFF_FFFF_FFFF.

### PR DESCRIPTION
**Pull request by eddyb**
With the addition of `Substs` to the query key, we can now evaluate *and cache* polymorphic constants.

Fixes #23898 by replacing the crippled explicit-discriminant-only local-crate-only `lookup_variant_by_id` with `ConstVal::Variant` which can describe variants irrespective of their discriminant.

Fixes #41394 by fixing #23898 (for the original testcase) and by not looping past the first discriminant.

### CODE REVIEW

**Comment by eddyb** [comment]
ping @rust-lang/compiler This fixes a regression in nightly, we should fix it before next beta.

File: src/librustc_const_eval/eval.rs [hunk 1]
```diff
@@ -569,12 +524,21 @@ fn resolve_trait_associated_const<'a, 'tcx: 'a>(
...
             traits::VtableImpl(ref impl_data) => {
-                let name = tcx.associated_item(trait_item_id).name;
+                let name = trait_item.name;
                 let ac = tcx.associated_items(impl_data.impl_def_id)
                     .find(|item| item.kind == ty::AssociatedKind::Const && item.name == name);
                 match ac {
-                    Some(ic) => lookup_const_by_id(tcx, ic.def_id, Substs::empty()),
-                    None => default_value,
+                    Some(ic) => {
+                        let substs = tcx.lift(&impl_data.substs).unwrap();
```
Comment (arielb1) [inline src/librustc_const_eval/eval.rs]: doesn't this need to do the `drain_fulfillment_cx_or_panic` thing?

File: src/librustc_const_eval/eval.rs [hunk 2]
```diff
@@ -289,9 +267,22 @@ fn eval_const_expr_partial<'a, 'tcx>(cx: &ConstContext<'a, 'tcx>,
...
       hir::ExprCast(ref base, _) => {
-        match cast_const(tcx, cx.eval(base)?, ety) {
-            Ok(val) => val,
-            Err(kind) => return Err(ConstEvalErr { span: e.span, kind: kind }),
+        let base_val = cx.eval(base)?;
+        let base_ty = cx.tables.expr_ty(base);
+
+        // Avoid applying substitutions if they're empty, that'd ICE.
+        let base_ty = if cx.substs.is_empty() {
+            base_ty
```
Comment (arielb1) [inline src/librustc_const_eval/eval.rs]: this sounds dubious.

Comment (eddyb) [inline src/librustc_const_eval/eval.rs]: Empty substitutions are used to signify "polymorphic evaluation". Providing identity substitutions in the right locations is harder.

File: src/librustc_const_eval/eval.rs (hunk 1 above)
Comment (eddyb) [inline src/librustc_const_eval/eval.rs]: We can't panic here, but I guess, yeah, it should be using something similar to trans.

Comment (arielb1) [inline src/librustc_const_eval/eval.rs]: There used to be a `drain_fulfillment_cx` without the panic part function. Can you reintroduce it? We need to not drop nested obligations on the floor, because of associated types in impls:

```Rust
trait Foo {
    const BAR: usize;
}

impl<U, V> Foo for (U, V) where U: Iterator<Item=V>, V: Foo {
    const BAR: usize = V::BAR;
}

impl Foo for u32 { const BAR: usize = 4; }
```

**Comment by arielb1** [comment]
r+ modulo the fulfillment_cx problem.

**Comment by TimNN** [comment]
```
[00:10:06] error: expected one of `,`, `.`, `?`, `}`, or an operator, found `None`
[00:10:06]    --> /checkout/src/librustc_const_eval/eval.rs:518:21
[00:10:06]     |
[00:10:06] 518 |                     None => {
[00:10:06]     |                     ^^^^
[00:10:06] 
[00:10:06] error: aborting due to previous error
[00:10:06] 
[00:10:06] error: Could not compile `rustc_const_eval`.
[00:10:06] Build failed, waiting for other jobs to finish...
[00:11:53] error: build failed
```

**Comment by TimNN** [comment]
@bors retry

* #40546
