### PR TITLE
Make the `c` feature for `compiler-builtins` an explicit opt-in

### LINKED ISSUE #101172: bootstrap cannot check library/std for windows from macOS (and possibly others)
I often write patches for `std::sys::windows` while not using windows. It would be nice if `./x.py check --target x86_64-pc-windows-msvc library/std` worked, but instead it does not -- I get an error like https://gist.github.com/thomcc/7c889b3a1306922f7eda28f45f1d304e (this is from a build where `aarch64-apple-darwin` is the host).

As a result, to check changes to std::sys::windows while not on windows, I'm forced to a full stage1 build, and then in some other workspace run `cargo +stage1 check -Zbuild-std --target x86_64-pc-windows-msvc` (where `+stage1` is a linked toolchain).  This works, but is tedious/time-consuming.

CC @jyn514 who suggested I file this issue, and suggested that it "looks like we're handling the linker arguments wrong when cross compiling".

### PR DESCRIPTION
**Pull request by jyn514**
Its build script doesn't support cross-compilation. I tried fixing it, but the cc crate itself doesn't appear to support cross-compiling to windows either unless you use the -gnu toolchain:
```
  error occurred: Failed to find tool. Is `lib.exe` installed?
```

Fixes https://github.com/rust-lang/rust/issues/101172.

### CODE REVIEW

File: src/bootstrap/compile.rs [hunk 1]
```diff
@@ -312,15 +312,18 @@ pub fn std_cargo(builder: &Builder<'_>, target: TargetSelection, stage: u32, car
...
-    let compiler_builtins_c_feature = if compiler_builtins_root.exists() {
-        // Note that `libprofiler_builtins/build.rs` also computes this so if
-        // you're changing something here please also change that.
-        cargo.env("RUST_COMPILER_RT_ROOT", &compiler_builtins_root);
-        " compiler-builtins-c"
-    } else {
-        ""
-    };
+    let compiler_builtins_c_feature =
+        if compiler_builtins_root.exists() && target == builder.build.build {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/compile.rs:319]: This condition is probably overly strict. I'd guess that for e.g. 64-bit -> 32-bit linux the build script probably works fine?

In general, my worry is that this makes it easy for us to have cross-compiled platforms have a fairly different performance (and potentially behavior) profile silently without being able to easily diagnose that...

Comment (Mark-Simulacrum) [reply src/bootstrap/compile.rs:319]: I think to fix the issue in question we can likely have a flag (perhaps off by default, and turned in CI, both in DEPLOY and non-DEPLOY configurations) that gates this rather than detecting based on cross-compilation. We can also give a better error message suggesting to use the flag.

Comment (jyn514) [reply src/bootstrap/compile.rs]: Seems reasonable, done. I'm not sure what you meant by a better error message, though - if we were able to predict when this goes wrong, we would be able to fix the bug upstream / avoid using the optimized feature in the first place.

Comment (Mark-Simulacrum) [reply src/bootstrap/compile.rs]: I mean that if we are in the condition where we're probably going to fail, we can probably warn about that, or ideally after failure print something like "help: if you want to avoid cross-compiling compiler-builtins C code, enable X flag in config.toml".

File: src/bootstrap/config.rs [hunk 2]
```diff
@@ -1423,6 +1427,18 @@ impl Config {
     pub fn submodules(&self, rust_info: &GitInfo) -> bool {
         self.submodules.unwrap_or(rust_info.is_git())
     }
+
+    /// Return whether we're using an externally provided LLVM.
+    ///
+    /// In particular, this may not be the latest version, nor contain our rust-specific patches.
+    pub fn using_external_llvm(&self, target: TargetSelection) -> bool {
```
Comment (Mark-Simulacrum) [inline src/bootstrap/config.rs:1434]: Can we unify with `fn is_rust_llvm` in Build?

File: src/ci/run.sh [hunk 3]
```diff
@@ -69,6 +69,11 @@ RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --set rust.codegen-units-std=1"
 # space required for CI artifacts.
 RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --dist-compression-formats=xz"
 
+# Enable the `c` feature for compiler_builtins, but only when the `compiler-rt` source is available.
+if [ "$EXTERNAL_LLVM" = "" ]; then
```
Comment (Mark-Simulacrum) [inline src/ci/run.sh:73]: Will we run into a problem on the dist-various-2 builder, IIRC, that has custom LLVM for a subset of the targets?

File: src/bootstrap/config.rs (hunk 2 above)
Comment (jyn514) [reply src/bootstrap/config.rs]: Didn't know that existed, thanks :)

File: src/ci/run.sh (hunk 3 above)
Comment (jyn514) [reply src/ci/run.sh:73]: I'm not sure. I've added it to PR CI temporarily to test.

**Comment by Mark-Simulacrum** [comment]
I'm a little worried that e.g. distros won't turn this on even if they can and end up with slower builds as a result. Not sure it's worth being too concerned about though. I think we can re-assess if we run into trouble as a result of this; if needed we can flip the default.

I'll flag as relnotes so we can mention it in internal changes/compat notes, I think.

@bors r+

**Comment by jyn514** [comment]
```
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc: error while loading shared libraries: libLLVM-15-rust-1.66.0-nightly.so: cannot open shared object file: No such file or directory
```
???

will dig into this later

File: src/bootstrap/dist.rs [hunk 4]
```diff
@@ -1838,23 +1838,21 @@ fn add_env(builder: &Builder<'_>, cmd: &mut Command, target: TargetSelection) {
...
-            // copying them here is going to cause problems as we may end up
-            // with the wrong files and isn't what distributions want.
-            //
-            // This behavior may be revisited in the future though.
-            //
-            // If the LLVM is coming from ourselves (just from CI) though, we
-            // still want to install it, as it otherwise won't be available.
-            return false;
-        }
+    if builder.is_rust_llvm(target) {
```
Comment (bjorn3) [inline src/bootstrap/dist.rs:1841]: This flipped the condition. Previously only external LLVM's would not be installed. Now only rust LLVM's would not be installed, despite the fact that it needs to be installed.

File: src/bootstrap/dist.rs [hunk 5]
```diff
@@ -1838,23 +1838,21 @@ fn add_env(builder: &Builder<'_>, cmd: &mut Command, target: TargetSelection) {
...
-            // copying them here is going to cause problems as we may end up
-            // with the wrong files and isn't what distributions want.
-            //
-            // This behavior may be revisited in the future though.
-            //
-            // If the LLVM is coming from ourselves (just from CI) though, we
-            // still want to install it, as it otherwise won't be available.
-            return false;
-        }
+    if !builder.is_rust_llvm(target) {
```
Comment (tmandry) [inline src/bootstrap/dist.rs:1841]: Please revert this. The point of `is_rust_llvm` is to know whether it contains Rust patches. In #101072 I added a config option so you can use a vanilla upstream LLVM without affecting other parts of how bootstrap works, this breaks that by re-coupling the idea of "is patched" to "is in tree".

File: src/bootstrap/compile.rs [hunk 6]
```diff
@@ -312,8 +310,15 @@ pub fn std_cargo(builder: &Builder<'_>, target: TargetSelection, stage: u32, car
     // If `compiler-rt` is available ensure that the `c` feature of the
     // `compiler-builtins` crate is enabled and it's configured to learn where
     // `compiler-rt` is located.
-    let compiler_builtins_root = builder.src.join("src/llvm-project/compiler-rt");
-    let compiler_builtins_c_feature = if compiler_builtins_root.exists() {
+    let compiler_builtins_c_feature = if builder.config.optimized_compiler_builtins {
+        if !builder.is_rust_llvm(target) {
```
Comment (tmandry) [inline src/bootstrap/compile.rs:314]: Likewise, this should be checking if a source checkout of LLVM is being used. It shouldn't be affected by the `llvm-has-rust-patches` target option.

Comment (jyn514) [reply src/bootstrap/compile.rs:314]: I think `is_rust_llvm` is exactly what we want here, actually. We want to know that if we use the sources in `src/llvm-project`, the instrumentation there will match the instrumentation in libLLVM.so, which is true exactly when that has the same patches as the submodule. Whether it was originally built from source or not shouldn't matter.

Comment (tmandry) [reply src/bootstrap/compile.rs:314]: Yeah you want to know if the versions match, which isn't the same as whether you're building from source.. it also isn't the same as whether it includes Rust patches, though. I commented on the other PR

**Comment by pietroalbini** [comment]
I want to note that disabling the `c` feature appears to have more side effects than just less optimizations.

At least on the `aarch64-unknown-linux-gnu` target, disabling that flag results in `rustc` being unable to compile anything when using GCC < 9.4 as the linker, due to its lack of support for `-m outline-atomics` ([introduced in GCC 9.4](https://gcc.gnu.org/gcc-9/changes.html#GCC9.4)). Linking anything results in [a bunch of linking errors](https://gist.github.com/pietroalbini/33e1a25fecaddc8ad936eb2ba26ecf05), that are suppressed by either using a newer GCC as the linker or enabling the new config flag.

(I discovered this when pulling the latest changes into Ferrocene)

File: src/bootstrap/compile.rs [hunk 7]
```diff
@@ -312,8 +310,15 @@ pub fn std_cargo(builder: &Builder<'_>, target: TargetSelection, stage: u32, car
...
+            panic!(
+                "need a managed LLVM submodule for optimized intrinsics support; unset `llvm-config` or `optimized-compiler-builtins`"
+            );
```
Comment (pietroalbini) [inline src/bootstrap/compile.rs:317]: If this check is present, there has to be a way to provide the path to the `compiler-rt` source code of the custom LLVM, otherwise it will be impossible to use custom LLVMs on some platforms (see https://github.com/rust-lang/rust/pull/101833#issuecomment-1270191721).

What I would do is have a check like:

```rust
if optimized_compiler_builtins && (!is_rust_llvm() || compiler_rt_src_path)
```

Comment (tmandry) [reply src/bootstrap/compile.rs:317]: Do you mean

```rust
if optimized_compiler_builtins && !(is_rust_llvm() || compiler_rt_src_path)
```

?

Comment (pietroalbini) [reply src/bootstrap/compile.rs:317]: Yep, sorry!
