### PR TITLE
Special treatment empty tuple when suggest adding a string literal in format macro.

### LINKED ISSUE #130170: does not detect {} not being in quotes when looking for a string literal, instead offers an incorrect solution
### Code

```Rust
use serde_json;

let idsmap: HashMap<String, u8> = serde_json::from_reader(fs::File::open("id_keys.json").expect("error 3"))
    .expect("error 4");
println!({},idsmap.get("1stSpellCost"));
```

### Current output

```Shell
error: format argument must be a string literal
  --> src/main.rs:55:14
   |
55 |     println!({},idsmap.get("1stSpellCost"));
   |              ^^
   |
help: you might be missing a string literal to format with
   |
55 |     println!("{} {}", {},idsmap.get("1stSpellCost"));
   |              ++++++++
```

### Desired output

```Shell
error: format argument must be a string literal
  --> src/main.rs:55:14
   |
55 |     println!({},idsmap.get("1stSpellCost"));
   |              ^^
   |
help: you might be missing brackets
   |
55 |     println!("{}",idsmap.get("1stSpellCost"));
   |              +  +
```

### Rationale and extra context

Cargo does not seem to be detecting the {} outside brackets and provides an incredibly strange fix instead.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7
```

### Anything else?

the file is from here: 
https://github.com/Wynntils/Static-Storage/blob/main/Reference/id_keys.json  
You will need serde_json crate.

### PR DESCRIPTION
**Pull request by surechen**
For example:
```rust
let s = "123";
println!({}, "sss", s);
```
Suggest:
`println!("{:?} {} {}", {}, "sss", s);`

fixes #130170

### CODE REVIEW

File: compiler/rustc_builtin_macros/src/format.rs [hunk 1]
```diff
@@ -195,12 +195,26 @@ fn make_format_args(
                                     Applicability::MaybeIncorrect,
                                 );
                             } else {
-                                let sugg_fmt = match args.explicit_args().len() {
-                                    0 => "{}".to_string(),
-                                    count => {
-                                        format!("{}{{}}", "{} ".repeat(count))
+                                let is_empty_tuple = |kind: &ExprKind| -> bool {
```
Comment (jieyouxu) [inline compiler/rustc_builtin_macros/src/format.rs:198]: Question: wait, this name seems misleading. The body of this closure matches on:

1. The actual empty tuple `()`, and
2. An empty block `{}` which is not a tuple?

File: compiler/rustc_builtin_macros/src/format.rs [hunk 2]
```diff
@@ -195,12 +195,26 @@ fn make_format_args(
...
+                                    match kind {
+                                        ExprKind::Block(b, _) if b.stmts.is_empty() => true,
```
Comment (jieyouxu) [inline compiler/rustc_builtin_macros/src/format.rs:200]: Question: will this fire on `'label: {}`? Maybe we want `ExprKind::Block(b, None)` here?

File: tests/ui/macros/format-issue-130170.rs [hunk 3]
```diff
@@ -0,0 +1,11 @@
+//@ run-rustfix
+
+fn main() {
+    let s = "123";
+    println!({}, "sss", s);
```
Comment (jieyouxu) [inline tests/ui/macros/format-issue-130170.rs:5]: Suggestion: if this is intended to provide the suggestion for both `println!({}, "sss", s)` and `println!((), "sss", s)` cases, please add a test case for both.

File: tests/ui/macros/format-issue-130170.rs
Comment (jieyouxu) [inline tests/ui/macros/format-issue-130170.rs:1]: Suggestion: rename test as something like `format-empty-block-unit-tuple-suggestion-130170`

File: compiler/rustc_builtin_macros/src/format.rs (hunk 1 above)
Comment (surechen) [reply compiler/rustc_builtin_macros/src/format.rs]: Done. Thank you.

File: compiler/rustc_builtin_macros/src/format.rs (hunk 2 above)
Comment (surechen) [reply compiler/rustc_builtin_macros/src/format.rs]: > Question: will this fire on `'label: {}`? Maybe we want `ExprKind::Block(b, None)` here?

Done. Thank you.

File: tests/ui/macros/format-issue-130170.rs (hunk 3 above)
Comment (surechen) [reply tests/ui/macros/format-issue-130170.rs]: > Suggestion: if this is intended to provide the suggestion for both `println!({}, "sss", s)` and `println!((), "sss", s)` cases, please add a test case for both.

Done. Thank you.

File: tests/ui/macros/format-issue-130170.rs
Comment (surechen) [reply tests/ui/macros/format-issue-130170.rs:1]: > Suggestion: rename test as something like `format-empty-block-unit-tuple-suggestion-130170`

Done. Thank you.

File: compiler/rustc_builtin_macros/src/format.rs [hunk 4]
```diff
@@ -195,12 +195,26 @@ fn make_format_args(
...
+                                        ExprKind::Block(b, None) if b.stmts.is_empty() => true,
+                                        ExprKind::Tup(v) if v.is_empty() => true,
+                                        _ => false,
                                     }
                                 };
+
+                                let mut sugg_fmt = "".to_string();
+                                for kind in [&efmt.kind]
+                                    .into_iter()
+                                    .chain(args.explicit_args().into_iter().map(|a| &a.expr.kind))
```
Comment (jieyouxu) [inline compiler/rustc_builtin_macros/src/format.rs:209]: Suggestion: maybe

```rs
std::iter::once(efmt.kind)
    .chain(args.explicit_args().into_iter().map(|a| &a.expr.kind))
```

**Review by jieyouxu — APPROVED** [review]
Thanks, some last minor nits then r=me.

**Review by jieyouxu — APPROVED** [review]
Thanks, r=me after PR CI is green.

**Comment by surechen** [comment]
> Thanks, r=me after PR CI is green.

Done. Thank you.
