### PR TITLE
Clarify suggetion for field used as method

### LINKED ISSUE #38321: "did you mean" for misusing a field as a method is misleading
The error is currently:
```
error: no method named `src_addr` found for type `&wire::ipv4::Repr` in the current scope
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
    |
note: did you mean to write `self.src_addr`?
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
```
which is of course absurd.

To reproduce:
```rust
struct Foo {
    src_addr: usize
}

fn main() {
    let foo = Foo { src_addr: 10 };
    foo.src_addr()
}
```

### PR DESCRIPTION
**Pull request by estebank**
Instead of

```rust
error: no method named `src_addr` found for type `&wire::ipv4::Repr` in the current scope
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
    |
note: did you mean to write `self.src_addr`?
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
```

present

```rust
error: no method named `src_addr` found for type `&wire::ipv4::Repr` in the current scope
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^ field, not a method
    |
    = help: did you mean to write `self.src_addr` instead of `self.src_addr(...)`?
```

Fix #38321.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I wonder if we should suggest `(self.src_addr)(...)`, at least in the event that the field is callable? It's non-obvious.

**Comment by nikomatsakis** [comment]
But I guess that feels like a separate issue. =)

File: src/librustc_typeck/check/method/suggest.rs [hunk 1]
```diff
@@ -197,17 +197,23 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
                                     let field_ty = field.ty(tcx, substs);
 
                                     if self.is_fn_ty(&field_ty, span) {
-                                        err.span_note(span,
-                                                      &format!("use `({0}.{1})(...)` if you \
-                                                                meant to call the function \
-                                                                stored in the `{1}` field",
-                                                               expr_string,
-                                                               item_name));
+                                        err.help(&format!("use `({0}.{1})(...)` if you \
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/method/suggest.rs]: oh, we do that already =)

File: src/librustc_typeck/check/method/suggest.rs [hunk 2]
```diff
@@ -197,17 +197,23 @@ impl<'a, 'gcx, 'tcx> FnCtxt<'a, 'gcx, 'tcx> {
...
+                                                           meant to call the function \
+                                                           stored in the `{1}` field",
+                                                          expr_string,
+                                                          item_name));
+                                        err.span_label(span,
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/method/suggest.rs]: Personally, I think I would give the same `span_label` either way (i.e., just "is a field, not a method") but change the help text. I think this syntax is a bit long and specific for a label.

File: src/test/compile-fail/issue-18343.rs [hunk 3]
```diff
@@ -14,6 +14,8 @@ struct Obj<F> where F: FnMut() -> u32 {
 
 fn main() {
     let o = Obj { closure: || 42 };
-    o.closure(); //~ ERROR no method named `closure` found
-    //~^ NOTE use `(o.closure)(...)` if you meant to call the function stored in the `closure` field
+    o.closure();
+    //~^ ERROR no method named `closure` found
+    //~| HELP use `(o.closure)(...)` if you meant to call the function stored in the `closure` field
+    //~| NOTE `closure` is a field storing a function, not a method
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-18343.rs]: can you change this to a `ui` test? I'd personally also rename it to something like `suggestion-for-field-with-fn-type-issue-18343.rs`, since `issue-18343.rs` seems like a name suitable only for "fix random ICE regression test" to me.

File: src/test/compile-fail/issue-2392.rs [hunk 4]
```diff
@@ -48,45 +48,58 @@ fn main() {
 
     let o_closure = Obj { closure: || 42, not_closure: 42 };
     o_closure.closure(); //~ ERROR no method named `closure` found
-    //~^ NOTE use `(o_closure.closure)(...)` if you meant to call the function stored
+    //~^ HELP use `(o_closure.closure)(...)` if you meant to call the function stored
+    //~| NOTE `closure` is a field storing a function, not a method
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-2392.rs]: I think this should be a UI test too

File: src/test/compile-fail/issue-32128.rs [hunk 5]
```diff
@@ -19,7 +19,9 @@ fn main() {
         })
     };
 
-    demo.example(1);    //~ ERROR no method named `example`
-                        //~^ NOTE use `(demo.example)(...)`
+    demo.example(1);
+    //~^ ERROR no method named `example`
+    //~| HELP use `(demo.example)(...)`
+    //~| NOTE `example` is a field storing a function, not a method
```
Comment (nikomatsakis) [inline src/test/compile-fail/issue-32128.rs]: really all of these feel like ui tests to me :) 

maybe make a directory like `src/test/ui/suggestions/confuse-field-and-method/` and just move the (not renamed) `issue-123.rs` files into that directory?

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
r=me once you make those ui tests

**Comment by estebank** [comment]
@nikomatsakis all done!

File: src/librustc_typeck/check/method/suggest.rs (hunk 2 above)
Comment (estebank) [inline src/librustc_typeck/check/method/suggest.rs]: I just realized I misread this comment. I'm keeping different labels, but much shortened (`field, not a method` vs `field storing a function, not a method`). Is that ok?

Comment (nikomatsakis) [inline src/librustc_typeck/check/method/suggest.rs]: personally, I find "field storing a function" confusing. It makes it sound (to me) like this is an error **specifically because the field stores a function** (where indeed it would be an error for any field).

Comment (estebank) [inline src/librustc_typeck/check/method/suggest.rs]: Changed so that both cases have the same label as originally requested.
