### PR TITLE
Suggest call fn ctor passed as arg to fn with type param bounds

### LINKED ISSUE #63100: "Try invoking the function" hint
Hi,

Let's consider following code:
```rust
fn foo() -> usize {
    0
}

fn bar(i: usize) {
    
}

fn main() {
    bar(foo);
}
```
Right now it fails with the `expected usize, found fn item` message - I think it would be helpful if compiler bragged about missing parentheses when function's return type matches expected type:
```rust
fn main() {
    bar(foo);
//      ^^^ expected usize, found fn item
//          hint: try invoking the function: foo()
}
```
It may even help a little bit when dealing with `async` functions - recently I've written:
```rust
async fn foo() {
    
}

fn bar(f: impl Future<Output=()>) {
    
}

fn main() {
    bar(foo);
}
```
... and it took me a few minutes to notice that what I actually wanted was `bar(foo())`.

### PR DESCRIPTION
**Pull request by estebank**
_Reviewer note: the relevant changes are in the second commit, the first is simple and mechanical, but verbose._

When forgetting to call a fn in an argument position to an fn that has a generic bound:

```rust
async fn foo() {}

fn bar(f: impl Future<Output=()>) {}

fn main() {
    bar(foo); // <- should be `bar(foo());`
} 
```

suggest calling it:

```
error[E0277]: the trait bound `fn() -> impl std::future::Future {foo}: std::future::Future` is not satisfied
  --> $DIR/async-fn-ctor-passed-as-arg-where-it-should-have-been-called.rs:9:5
   |
LL | fn bar(f: impl Future<Output=()>) {}
   | --------------------------------- required by `bar`
...
LL |     bar(foo);
   |     ^^^ the trait `std::future::Future` is not implemented for `fn() -> impl std::future::Future {foo}`
   |
   = help: it looks like you forgot to use parentheses to call the function: `foo()`
```

Fix #63100. Follow up to #63833 and #63337.

### CODE REVIEW

**Comment by estebank** [comment]
Future work: keep accurate obligation spans for type bounds associated to specific fn arguments to point at the argument instead of the ident of the fn call.

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -953,6 +958,58 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+    fn suggest_fn_call(
+        &self,
+        obligation: &PredicateObligation<'tcx>,
+        err: &mut DiagnosticBuilder<'tcx>,
+        trait_ref: &ty::Binder<ty::TraitRef<'tcx>>,
+    ) {
+        let self_ty = trait_ref.self_ty();
+        match self_ty.sty {
+            ty::FnDef(def_id, _) => {
+                // We tried to apply the bound to an `fn`. Check wether calling it
```
Comment (Patryk27) [inline src/librustc/traits/error_reporting.rs]: Typo: `whether`

File: src/librustc/traits/error_reporting.rs [hunk 2]
```diff
@@ -953,6 +958,58 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                // would evaluate to a type that *would* satisfy the trait binding.
+                // If it would, suggest calling it: `bar(foo)` -> `bar(foo)`. This
+                // case is *very* to hit if `foo` is `async`.
```
Comment (killercup) [inline src/librustc/traits/error_reporting.rs]:
```suggestion
                // case is *very* likely to hit if `foo` is `async`.
```

**Comment by estebank** [comment]
ping

File: src/test/ui/suggestions/fn-ctor-passed-as-arg-where-it-should-have-been-called.stderr [hunk 3]
```diff
@@ -0,0 +1,14 @@
+error[E0277]: the trait bound `fn() -> impl T {foo}: T` is not satisfied
+  --> $DIR/fn-ctor-passed-as-arg-where-it-should-have-been-called.rs:17:5
+   |
+LL | fn bar(f: impl T<O=()>) {}
+   | ----------------------- required by `bar`
+...
+LL |     bar(foo);
+   |     ^^^ the trait `T` is not implemented for `fn() -> impl T {foo}`
+   |
+   = help: it looks like you forgot to use parentheses to call the function: `foo()`
```
Comment (oli-obk) [inline src/test/ui/suggestions/fn-ctor-passed-as-arg-where-it-should-have-been-called.stderr]: In case anyone is wondering why this is not a suggestion on `foo`'s span: the error itself is already wrongly highlighting the `bar` function instead of its `foo` argument. That's a longstanding issue, but we have some ideas on how to continue with it.

**Comment by estebank** [comment]
@bors retry

😅
```
2019-08-30T17:52:18.6413568Z   local time: Fri Aug 30 17:52:18 UTC 2019
2019-08-30T17:52:18.7239154Z   network time: Fri, 30 Aug 2019 17:52:18 GMT
```

**Comment by lzutao** [comment]
Need a rebase and update to #63127
```rust
2019-08-30T17:52:11.4840646Z error[E0609]: no field `arguments` on type `&hir::Body`
2019-08-30T17:52:11.4843201Z --> src/librustc/traits/error_reporting.rs:998:38
2019-08-30T17:52:11.4843767Z |
2019-08-30T17:52:11.4844668Z 998 | body.arguments.iter()
2019-08-30T17:52:11.4845227Z | ^^^^^^^^^
2019-08-30T17:52:11.4845472Z
2019-08-30T17:52:18.4590264Z error: aborting due to previous error
```

File: src/librustc/traits/error_reporting.rs [hunk 4]
```diff
@@ -953,6 +958,58 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                    Ok(EvaluationResult::EvaluatedToOkModuloRegions) |
+                    Ok(EvaluationResult::EvaluatedToAmbig) => {
+                        if let Some(hir::Node::Item(hir::Item {
+                            ident,
+                            node: hir::ItemKind::Fn(.., body_id),
+                            ..
+                        })) = self.tcx.hir().get_if_local(def_id) {
+                            let body = self.tcx.hir().body(*body_id);
+                            err.help(&format!(
+                                "it looks like you forgot to use parentheses to \
```
Comment (zackmdavis) [inline src/librustc/traits/error_reporting.rs]:
```suggestion
                                "use parentheses to \
```

Omit needless words.
