### PR TITLE
Deeply normalize item bounds in new solver

### LINKED ISSUE #142: nested RPITIT in default methods result in type mismatch
```rust
use std::ops::Deref;

trait Foo {
    fn bar() -> impl Deref<Target = impl Sized> {
        &()
    }
}

fn main() {}
```
```
error[E0271]: type mismatch resolving `<impl Deref<Target = impl Sized> as Deref>::Target == impl Sized`
 --> <source>:4:17
  |
4 |     fn bar() -> impl Deref<Target = impl Sized> {
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ
  |
note: required by a bound in `Foo::{synthetic#0}`
 --> <source>:4:28
  |
4 |     fn bar() -> impl Deref<Target = impl Sized> {
  |                            ^^^^^^^^^^^^^^^^^^^ required by this bound in `Foo::{synthetic#0}`
```

affected tests

  - tests/ui/impl-trait/in-trait/nested-rpitit-bounds.rs
  - tests/ui/impl-trait/in-trait/default-body-with-rpit.rs

### LINKED ISSUE #151: GATs can weaken where clauses in impl
```rust
trait Foo {
    type T<'a>: Sized where Self: 'a;
}

impl Foo for &() {
    type T<'a> = ();
}
```

This fails in the old solver, passes in the new solver. This fails in the old solver because in `check_type_bounds` we normalize the item bound like `<&() as Foo>::T<'a>: Sized` into `(): Sized`, but when normalizing we also require proving the GAT where clauses hold. 

In the new solver we simply structurally replace instances of GATs with their definition type using the `ReplaceTy` folder, which is a kind of "normalization" but which doesn't require that the GAT where clauses hold.

For now, we could just register the GAT bounds in `check_type_bounds` to paper over this problem, though I think we could think harder about how and where GAT where clauses are required to hold in normalization...

### PR DESCRIPTION
**Pull request by compiler-errors**
Built on #136863. 

Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/142.
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/151.

cc https://github.com/rust-lang/trait-system-refactor-initiative/issues/116

First commit reworks candidate preference for projection bounds to prefer param-env projection clauses even if the corresponding trait ref doesn't come from the param-env.

Second commit adjusts the associated type item bounds check to deeply normalize in the new solver. This causes some test fallout which I will point out.

r? lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/gat-wf.rs [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// Make sure that, like the old trait solver, we end up requiring that the WC of
```
Comment (compiler-errors) [inline tests/ui/traits/next-solver/gat-wf.rs:1]: This is also the cause for the failures in `tests/ui/traits/const-traits/predicate-entailment-passes.rs`. Where clauses must be equal, which kinda makes the GATs in that test useless.

File: tests/ui/traits/const-traits/predicate-entailment-passes.rs [hunk 2]
```diff
@@ -6,32 +6,21 @@
 #[const_trait] trait Bar {}
```
Comment (compiler-errors) [inline tests/ui/traits/const-traits/predicate-entailment-passes.rs:6]: See below for why I ripped out the GATs from this test.

**Comment by lcnr** [comment]
with https://github.com/rust-lang/rust/pull/136863 merged, please rebase and then r=me (though I'd like to look at the PR myself at this point again and manually approve)

File: tests/ui/traits/next-solver/gat-wf.rs (hunk 1 above)
Comment (compiler-errors) [reply tests/ui/traits/next-solver/gat-wf.rs:1]: Kinda prefer an explicit test. 91833 is a mess. I'll add flag, tho, whoops.

**Comment by lcnr** [comment]
gamer

@bors r+ rollup
