### PR TITLE
Unconditionally disable LLVM's FastISel on AArch64

### LINKED ISSUE #21627: Incorrect sign extension from `i32` to `i64` on AArch64
When compiling the following code (which is a minimized version of `impl_to_primitive_int_to_int!` from libcore/num/mod.rs) on AArch64 with rustc from 2015-01-24, the output is unfortunately `NO :(`

```
use std::num::Int;

fn main() {
	let n = 960 as i64;
	let min_value: i32 = Int::min_value();
	if min_value as i64 <= n {
		println!("OK :)");
	} else {
		println!("NO :(")
	}
}
```

The disassembled code of `main` starts as:
```
00000000000071ec <_ZN4main20h2d56baed33734ff2faaE>:
    71ec:       a9be6ffc        stp     x28, x27, [sp,#-32]!
    71f0:       a9017bfd        stp     x29, x30, [sp,#16]
    71f4:       910043fd        add     x29, sp, #0x10
    71f8:       d10443ff        sub     sp, sp, #0x110
    71fc:       b27a0fe8        orr     x8, xzr, #0x3c0
    7200:       f81e83a8        str     x8, [x29,#-24]
    7204:       94000048        bl      7324 <_ZN3num7i32.Int9min_value20hb9150aaae7f1b75agpbE>
    7208:       b81e43a0        str     w0, [x29,#-28]
    720c:       b89e43a8        ldrsw   x8, [x29,#-28]
    7210:       2a0803e0        mov     w0, w8
    7214:       2a0003e8        mov     w8, w0
    7218:       f85e83a9        ldr     x9, [x29,#-24]
    721c:       eb09011f        cmp     x8, x9
```

The problem is with the two moves at `0x7210` and `0x7214`, which erroneously clear the top 32 bits of `x8`, which thus becomes `0x80000000` instead of the expected `0xffffffff80000000`.

The error was first found in the rustup_20150109 branch of Servo (https://github.com/servo/servo/pull/4716), but the latest Rust also exhibits the problem (as shown above).

### PR DESCRIPTION
**Pull request by akosthekiss**
Before ca07e256f62f772d14c42f41af46f2aeacc54983, LLVM's AArch64FastISel
had a sign (and zero?) extension bug. Until rustc gets its LLVM past
that commit, the way of workaround is to pass an option to LLVM that
forces the disabling of FastISel (which would normally kick in for -O0).

Fixes #21627

### CODE REVIEW

File: src/librustc_trans/back/write.rs [hunk 1]
```diff
@@ -1012,6 +1012,9 @@ unsafe fn configure_llvm(sess: &Session) {
         if sess.time_llvm_passes() { add("-time-passes"); }
         if sess.print_llvm_passes() { add("-debug-pass=Structure"); }
 
+        // FIXME #21627 disable faulty FastISel on AArch64 (even for -O0)
```
Comment (huonw) [inline src/librustc_trans/back/write.rs]: I think this number should refer to an open bug (i.e. you can preemptively open one "reenable FastISel on AArch64" before this lands) so that it gets picked up in future triage/general bug handling.

**Comment by huonw** [comment]
An alternative would be to just update the LLVM Rust uses, @alexcrichton would know the right process for this.

**Comment by alexcrichton** [comment]
We currently have a [fork of LLVM](https://github.com/rust-lang/llvm) which basically only serves the purpose of allowing us to pin to specific revisions as well as pile on some [custom optimizations](https://github.com/rust-lang/llvm/commits/rust-llvm-2014-12-30) (just the top 6 patches).

Updating LLVM is basically just doing something like the following:

```
git clone git://github.com/rust-lang/llvm
cd llvm
git remote add llvm git://github.com/llvm-mirror/llvm
git fetch llvm
git checkout -b rust-llvm-$date rust-llvm-$old_date
git rebase llvm/master
# fix conflicts and make a PR to rust-lang/llvm
```

I'll merge it to a new branch of `rust-lang/llvm` and then we can update the in-tree copy. This is also fine to do now, either way works!

**Comment by richo** [comment]
I had a similar tree kicking around anyway. I just redid the rebase quickly
(The last patch is now upstream).

I just made a fork and pushed it to richo/llvm
@ 070a227e1848ec2cd23cc8d0ad6e72460f2e7438 (rust-llvm-2014-01-26)

**Comment by akiss77** [comment]
I'd vote/ask for accepting this PR (no surprise, since it's mine :) until the LLVM update happens. (Except if that happens soon. I have no experience with that, don't know how much work it takes.) It'll be easy to remove these two lines after that.

**Comment by richo** [comment]
Relevant PR for llvm: https://github.com/rust-lang/llvm/pull/26

**Comment by alexcrichton** [comment]
I've now merged rust-lang/llvm#26, @akiss77 would you be ok trying out updating LLVM in this patch instead?

If it's too complicated due to random build failures or such we can also hold off for now and merge this instead.

**Comment by richo** [comment]
Looks like something went pearshaped in my rebase. I am poking a little
now, but I can definitely amend tonight.

Sorry!

**Comment by richo** [comment]
I've updated my branch. I'm running make check now, I'll report back later

**Comment by akiss77** [comment]
I'll be OK trying out the new LLVM, but let's see what @richo has to report back first. (I have quite a long build cycle, so I rather wouldn't start it up if there are some known issues around.)

**Comment by richo** [comment]
I fixed the original issues, but I'm currently fighting with some internal conversions that have been broken in the update.

**Comment by richo** [comment]
If you feel like writing some C++ I can push the trees for you to have a look at though!

**Comment by akiss77** [comment]
I don't dare to undertake this right now since I'll be off travelling in some hours for the coming 3-4 days. (Eventhough I do love C++.)

**Comment by richo** [comment]
As an update, I poked a little tonight and then Alex poked quite a bit more. This will probably make it out in the not too distant future, but this workaround is rpobably a good idea if it's breaking things on aarch64.

**Comment by alexcrichton** [comment]
Yeah it looks like the LLVM update will take awhile, so we can go ahead and put this in the queue in the meantime.

**Comment by akiss77** [comment]
what happened to @bors ?
