### PR TITLE
Do not forget to pass DWARF fragment information to LLVM.

### LINKED ISSUE #115113: ScalarReplacementOfAggregates causes rustc to emit invalid LLVM debuginfo (and sometimes rustc segfaults)
https://rust.godbolt.org/z/9YvvvcMKj

```rust
pub struct Endian;

#[allow(dead_code)]
pub struct EndianSlice<'input> {
    slice: &'input [u8],
    endian: Endian,
}

pub fn test(s: &[u8]) {
    let slice = EndianSlice { slice: s, endian: Endian };
}
```

Compiled with
```
--emit=llvm-ir -C debuginfo=2 -Zmir-opt-level=0 -Zmir-enable-passes=+ScalarReplacementOfAggregates
```

Becomes this:
```llvm
define void @example::test(ptr align 1 %s.0, i64 %s.1) unnamed_addr #0 !dbg !7 {
start:
  %slice.dbg.spill1 = alloca { ptr, i64 }, align 8
  %slice.dbg.spill = alloca %Endian, align 1
  %s.dbg.spill = alloca { ptr, i64 }, align 8
  %0 = getelementptr inbounds { ptr, i64 }, ptr %s.dbg.spill, i32 0, i32 0
  store ptr %s.0, ptr %0, align 8
  %1 = getelementptr inbounds { ptr, i64 }, ptr %s.dbg.spill, i32 0, i32 1
  store i64 %s.1, ptr %1, align 8
  call void @llvm.dbg.declare(metadata ptr %s.dbg.spill, metadata !22, metadata !DIExpression()), !dbg !30
  call void @llvm.dbg.declare(metadata ptr %slice.dbg.spill, metadata !23, metadata !DIExpression()), !dbg !31
  %2 = getelementptr inbounds { ptr, i64 }, ptr %slice.dbg.spill1, i32 0, i32 0, !dbg !32
  store ptr %s.0, ptr %2, align 8, !dbg !32
  %3 = getelementptr inbounds { ptr, i64 }, ptr %slice.dbg.spill1, i32 0, i32 1, !dbg !32
  store i64 %s.1, ptr %3, align 8, !dbg !32
  call void @llvm.dbg.declare(metadata ptr %slice.dbg.spill1, metadata !23, metadata !DIExpression()), !dbg !31
  ret void, !dbg !33
}
<snip>
!22 = !DILocalVariable(name: "s", arg: 1, scope: !7, file: !8, line: 9, type: !12)
!23 = !DILocalVariable(name: "slice", scope: !24, file: !8, line: 10, type: !25, align: 8)
```

ScalarReplacementOfAggregates is on by default in the stable toolchain that is currently being released, and it was turned on in  https://github.com/rust-lang/rust/pull/112002. There is an LLVM assertion which can catch some manifestations of this problem, but in the wild it seems rather hard to actually hit the assertion.

To the best of my knowledge https://bugzilla.redhat.com/show_bug.cgi?id=2226564 is the closest we have to someone hitting this in the wild. I hit it on my own by using `-Cdebuginfo=2 -Zinline-mir-threshold=1000 -Zinline-mir-hint-threshold=1000` with `-Zbuild-std`.

If this becomes a problem when 1.72 goes out, an emergency fix would be just reverting the change to `is_enabled` in the linked PR.

### LINKED ISSUE #115142: Crash (SEGFAULT) when building Firefox for ARMv7 or x86 Android with 1.72
Building Firefox for the thumbv7neon-linux-androideabi and i686-linux-android fails with a rust compiler crash:
```
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x3116d63)[0x7fd329284d63]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bf90)[0x7fd325e27f90]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm12DIExpression15getFragmentInfoENS0_16expr_op_iteratorES1_+0x21)[0x7fd3231624e1]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x65f448b)[0x7fd3231f448b]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x661387c)[0x7fd32321387c]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit24constructVariableDIEImplERKNS_11DbgVariableEb+0xf19)[0x7fd322c9f459]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x4a9)[0x7fd322a73469]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit27constructSubprogramScopeDIEEPKNS_12DISubprogramEPNS_12LexicalScopeE+0xe9)[0x7fd322c9fde9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm10DwarfDebug15endFunctionImplEPKNS_15MachineFunctionE+0x210)[0x7fd322c9c650]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DebugHandlerBase11endFunctionEPKNS_15MachineFunctionE+0x5e)[0x7fd322d4031e]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm10AsmPrinter16emitFunctionBodyEv+0x1a5b)[0x7fd322b8511b]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x7c7f637)[0x7fd32487f637]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x7c7f637)[0x7fd32487f637]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0xc02)[0x7fd32293a018]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x26d)[0x7fd3229a7b39]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273ce36)[0x7fd3288aae36]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273c838)[0x7fd3288aa838]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273a9d8)[0x7fd3288a89d8]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2602f27)[0x7fd328770f27]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2602467)[0x7fd328770467]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2600794)[0x7fd32876e794]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x25f9ce6)[0x7fd328767ce6]
/builds/worker/fetches/rustc/lib/libstd-fe004512c8383174.so(rust_metadata_std_49ba9e76e27f693e+0x1032d5)[0x7fd3260e52d5]
/lib/x86_64-linux-gnu/libc.so.6(+0x88fd4)[0x7fd325e74fd4]
/lib/x86_64-linux-gnu/libc.so.6(__clone+0x40)[0x7fd325ef4820]
```

I wish I could give something more detailed, but I haven't had the time to try to yet. I however identified the regression to come from 642c92e63008ffb49f6ad8344e07bfa7d5b0d9bb (Enable ScalarReplacementOfAggregates in optimized builds) and building with `-Zmir-enable-passes=-ScalarReplacementOfAggregates` avoids the crash.

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/115113 for the rustc part

### CODE REVIEW

File: tests/codegen/sroa-fragment-debuginfo.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+}
+
+#[no_mangle]
+pub fn test(s: &[u8]) {
+// CHECK: void @test(
+// CHECK: %slice.dbg.spill1 = alloca { ptr, i64 },
+// CHECK: %slice.dbg.spill = alloca %Endian,
+// CHECK: %s.dbg.spill = alloca { ptr, i64 },
+// CHECK: call void @llvm.dbg.declare(metadata ptr %s.dbg.spill, metadata ![[S:.*]], metadata !DIExpression()),
+// CHECK: call void @llvm.dbg.declare(metadata ptr %slice.dbg.spill, metadata ![[SLICE:.*]], metadata !DIExpression(DW_OP_LLVM_fragment, 0, 0)),
```
Comment (nikic) [inline tests/codegen/sroa-fragment-debuginfo.rs:21]: Shouldn't this be something like 128, 0 rather than 0, 0?

It would probably be clearer to use a non-zero sized type here.

File: tests/codegen/sroa-fragment-debuginfo.rs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+pub struct ExtraSlice<'input> {
+    slice: &'input [u8],
+    extra: u32,
+}
+
+#[no_mangle]
+pub fn extra(s: &[u8]) {
+// CHECK: void @extra(
+// CHECK: %slice.dbg.spill1 = alloca i32,
+// CHECK: %slice.dbg.spill = alloca { ptr, i64 },
```
Comment (nikic) [inline tests/codegen/sroa-fragment-debuginfo.rs:15]: Test should require 64-bit target, otherwise the sizes / offset aren't correct.

**Comment by cuviper** [comment]
For #115113 in 1.73, we should either backport this or disable SROA again.

@rustbot label +beta-nominated

**Comment by apiraino** [comment]
I feel this patch can also be evaluated for a stable backport (if there will be plans for a 1.72.1 release).

@rustbot label stable-backport

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-08-31/near/388331987).

Stable backport declined (#115140 already disabled the MIR opt that caused fragment debuginfo to be generated from rustc, [comment on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-08-31/near/388337264)).

@rustbot label +beta-accepted -stable-nominated
