### PR TITLE
naked functions: emit `.private_extern` on macos

### LINKED ISSUE #148307: Unable to link code containing naked functions on ARM64 macOS with ThinLTO enabled
_I have originally reported this issue in `wasmtime` repository and was redirected here: https://github.com/bytecodealliance/wasmtime/issues/11957. I have tried to minimize the reproduction, but I failed to do so in reasonable time. The complexity of `wasmtime` crates is critical here. I would appreciate any hints that would help me minimize this._

Compiling Wasmtime 38.0.3 produces a linker error on ARM64 macOS when building with ThinLTO enabled. The error indicates that `wasmtime_fiber_switch` symbol is undefined during linking.

```
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "<426 object files omitted>" "/var/folders/8c/r_zrp9mj12xd414t08zrks940000gn/T/rustc2wYYXA/{libwasmtime-e843f7bbc21927d3,libzstd_sys-7eabaf414ee67d02,libwasmtime_internal_jit_debug-9043bb9a4e496da8}.rlib" "<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-*.rlib" "-liconv" "-lSystem" "-lc" "-lm" "-arch" "arm64" "-mmacosx-version-min=11.0.0" "-L" "/Users/mk/Developer/software-mansion/scarb/linker-repro/wasmtime-only-test/target/release/build/wasmtime-15671f59b24bbe0f/out" "-L" "/Users/mk/Developer/software-mansion/scarb/linker-repro/wasmtime-only-test/target/release/build/zstd-sys-1ea01473940232bc/out" "-L" "/Users/mk/Developer/software-mansion/scarb/linker-repro/wasmtime-only-test/target/release/build/wasmtime-internal-jit-debug-2aaf81cce8508d62/out" "-o" "/Users/mk/Developer/software-mansion/scarb/linker-repro/wasmtime-only-test/target/release/deps/wasmtime_only_test-69cba5150eff8962" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: ld: warning: object file (/private/var/folders/8c/r_zrp9mj12xd414t08zrks940000gn/T/rustc2wYYXA/libwasmtime-e843f7bbc21927d3.rlib[2](242b1992def1ef0b-helpers.o)) was built for newer 'macOS' version (26.0) than being linked (11.0)
          ld: warning: object file (/private/var/folders/8c/r_zrp9mj12xd414t08zrks940000gn/T/rustc2wYYXA/libwasmtime_internal_jit_debug-9043bb9a4e496da8.rlib[2](db3b6bfb95261072-gdbjit.o)) was built for newer 'macOS' version (26.0) than being linked (11.0)
          Undefined symbols for architecture arm64:
            "wasmtime_internal_fiber::stackswitch::aarch64::wasmtime_fiber_switch::h0b241ee887e10750", referenced from:
                wasmtime_internal_fiber::unix::Suspend::switch::hfd4514b4efef3e13 in wasmtime_only_test-69cba5150eff8962.wasmtime-e843f7bbc21927d3.wasmtime.7e3b8021754df0c4-cgu.05.rcgu.o.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
```

What's important is that this issue only pops up with ThinLTO enabled. It didn't fail with either LTO disabled, set to FatLTO, or Wasmtime 37.

### Steps to Reproduce

- **Architecture**: ARM64 (Apple Silicon)
- **OS**: macOS 26.0
- **Rust**: 1.90.0
- **Wasmtime**: 38.0.3
- **Build Profile**: `release` with `lto = "thin"`

**Cargo.toml:**
```toml
[package]
name = "linker-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "38"

[profile.release]
lto = "thin"

```

**src/main.rs:**
```rust
fn main() {
    let engine = wasmtime::Engine::default();
    println!("Engine created: {:?}", engine);
}
```

**Build command:**
```bash
cargo build --release
```

This will fail with the linker error shown above.

I think the wasmtime commit that triggers this regression is: https://github.com/bytecodealliance/wasmtime/commit/3e9eca8b23ace6b2631c557e0e84bb8371c18ed2

### Meta

I have tested this reproduction on all stable+beta+nightly at the time of submitting this issue:

`rustc --version --verbose`:
```
rustc 1.90.0 (1159e78c4 2025-09-14)
binary: rustc
commit-hash: 1159e78c4747b02ef996e55082b704c09b970588
commit-date: 2025-09-14
host: aarch64-apple-darwin
release: 1.90.0
LLVM version: 20.1.8
```

```
rustc 1.92.0-beta.1 (3b4dd9bf1 2025-10-28)
binary: rustc
commit-hash: 3b4dd9bf1410f8da6329baa36ce5e37673cbbd1f
commit-date: 2025-10-28
host: aarch64-apple-darwin
release: 1.92.0-beta.1
LLVM version: 21.1.3
```

```
rustc 1.93.0-nightly (292be5c7c 2025-10-29)
binary: rustc
commit-hash: 292be5c7c05138d753bbd4b30db7a3f1a5c914f7
commit-date: 2025-10-29
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.3
```

### PR DESCRIPTION
**Pull request by folkertdev**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/148339)*

fixes https://github.com/rust-lang/rust/issues/148307

Emit `.private_extern` on macos when the naked function uses `Linkage::Internal`. Failing to do so can cause issues with LTO.

The documentation on this directive is kind of sparse, but I believe this is at least not incorrect, and does fix the issue. 

r? @Amanieu 
cc @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
Is this really only an issue on macOS? I would have assumes this is an issue on all platforms.

**Comment by folkertdev** [comment]
> aka use external linkage + hidden visibility on ELF and equivalent with other object file formats.

Hmm, we do emit the following:

https://github.com/rust-lang/rust/blob/6a884ad1b502fe48307d363858510702429fc735/compiler/rustc_middle/src/mir/mono.rs#L151-L159

but apparently that is not enough.

Is `compiler/rustc_monomorphize/src/partitioning.rs ` the right place to fix this?

**Comment by bjorn3** [comment]
That gets overridden at https://github.com/rust-lang/rust/blob/6a884ad1b502fe48307d363858510702429fc735/compiler/rustc_monomorphize/src/partitioning.rs#L583-L586

File: compiler/rustc_codegen_ssa/src/mir/naked_asm.rs [hunk 1]
```diff
@@ -181,7 +181,8 @@ fn prefix_and_suffix<'tcx>(
                 }
             }
             Linkage::Internal => {
-                // write nothing
+                // LTO can fail when internal linkage is used.
+                emit_fatal("naked functions may not have internal linkage")
```
Comment (folkertdev) [inline compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:185]: is this too strict? We could allow it, but I think this is only reachable now with an explicit linkage attribute (which is unstable).

Comment (Amanieu) [reply compiler/rustc_codegen_ssa/src/mir/naked_asm.rs:185]: I think this is fine for now. We can always revise it later if it becomes a problem.

**Comment by folkertdev** [comment]
Hmm, this PR makes changes for macos only, so I'd guess this is a spurious failure?

File: compiler/rustc_monomorphize/src/partitioning.rs [hunk 2]
```diff
@@ -580,6 +580,16 @@ fn internalize_symbols<'tcx>(
...
 
+            // When LTO inlines the caller of a naked function, it will attempt but fail to make the
+            // naked function symbol visible. To ensure that LTO works correctly, do not default
+            // naked functions to internal linkage and default visibility.
+            if let MonoItem::Fn(instance) = item {
+                let flags = cx.tcx.codegen_instance_attrs(instance.def).flags;
+                if flags.contains(CodegenFnAttrFlags::NAKED) {
+                    continue;
+                }
+            }
```
Comment (folkertdev) [inline compiler/rustc_monomorphize/src/partitioning.rs:591]: @bjorn3 why would we handle naked functions differently from some other external symbol defined in global assembly?

```rust
extern "C" {
    fn foo();
}

global_asm!(
    "foo:", "ret"
);
```

is it just that nobody ran into this issue with global assembly so far? In any case this fix is causing issues elsewhere, see https://github.com/rust-lang/rust/issues/151946

Comment (bjorn3) [reply compiler/rustc_monomorphize/src/partitioning.rs:591]:
```rust
global_asm!(
    "foo:", "ret"
);
```

this defines a local symbol, which means that only if `foo` gets called within the exact same object file will it work. There is never a guarantee that the `global_asm!()` gets added to the same codegen unit, so without `.globl foo` or (if you don't use dylibs) `.hidden foo` your example is effectively invalid.
