### PR TITLE
Always generate GEP i8 / ptradd for struct offsets

### LINKED ISSUE #121719: Common branch folding for enum types fails when there are more than three enum variants.
I tried this code:
https://godbolt.org/z/Yh7Px49jh
```rust
#[repr(C)]
pub struct A {
    x: f64,
    y: u64,
}
#[repr(C)]
pub struct B {
    x: f64,
    y: u32,
}
#[repr(C)]
pub struct C {
    x: f64,
    y: u16,
}
#[repr(C)]
pub struct D {
    x: f64,
    y: u8,
}

pub enum E {
    A(A),
    B(B),
    C(C),
    D(D),
}

impl E {
    #[inline(never)]
    pub fn x(&self) -> &f64 {
        match self {
            E::A(A { x, .. }) | E::B(B { x, .. }) | E::C(C { x, .. }) | E::D(D { x, .. }) => x,
        }
    }
}
```

I expected to see this happen: 

The `E::x` function gets optimized into a single add instruction since all the field has the same offset

Instead, this happened: 

When the enum has four or more variants, the asm generated is
```
example::E::x:
        mov     rax, rdi
        mov     rcx, qword ptr [rdi]
        lea     rdx, [rip + .LJTI0_0]
        movsxd  rcx, dword ptr [rdx + 4*rcx]
        add     rcx, rdx
        jmp     rcx
.LBB0_1:
        add     rax, 8
        ret
.LJTI0_0:
        .long   .LBB0_1-.LJTI0_0
        .long   .LBB0_1-.LJTI0_0
        .long   .LBB0_1-.LJTI0_0
        .long   .LBB0_1-.LJTI0_0
```

When the enum has three variants, the folding took effects but still generates strange stuff
```
example::E::x:
        mov     rax, rdi
        mov     rcx, qword ptr [rdi]
        test    rcx, rcx
        je      .LBB0_2
        cmp     ecx, 1
.LBB0_2:
        add     rax, 8
        ret
```

When it has two variants, it finally produces idiomatic code
```
example::E::x:
        lea     rax, [rdi + 8]
        ret
```

Interestingly, rustc **will** generate idiomatic code when:
1. Enum variants not exceeding three
2. Enum variants share the same layout. As in the demo the field `y` is used to disrupt the layout.
3. (Edit) Rustc version <=1.64.

### Meta

godbold rustc 1.76.0 with `-C opt-level=3 -C target-cpu=x86-64-v3`

Edit: Tried more godbolt settings. This is a regression introduced sometime between rust 1.64 and rust 1.65.

### PR DESCRIPTION
**Pull request by erikdesjardins**
This implements #98615, and goes a bit further to remove `struct_gep` entirely.

Upstream LLVM is in the beginning stages of [migrating to `ptradd`](https://discourse.llvm.org/t/rfc-replacing-getelementptr-with-ptradd/68699). LLVM 19 will [canonicalize](https://github.com/llvm/llvm-project/pull/68882) all constant-offset GEPs to i8, which has roughly the same effect as this change.

Fixes #121719.

Split out from #121577.

r? @nikic

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/va_arg.rs [hunk 1]
```diff
@@ -89,11 +89,31 @@ fn emit_aapcs_va_arg<'ll, 'tcx>(
...
+    // There is no padding between fields since `void*` is size=8 align=8, `int` is size=4 align=4.
+    // See https://github.com/ARM-software/abi-aa/blob/master/aapcs64/aapcs64.rst
+    // Table 1, Byte size and byte alignment of fundamental data types
+    // Table 3, Mapping of C & C++ built-in data types
+    let ptr_offset = 8;
+    let i32_offset = 4;
+    let gr_top = bx.inbounds_ptradd(va_list_addr, bx.cx.const_usize(ptr_offset));
+    let vr_top = bx.inbounds_ptradd(va_list_addr, bx.cx.const_usize(2 * ptr_offset));
+    let gr_offs = bx.inbounds_ptradd(va_list_addr, bx.cx.const_usize(3 * ptr_offset));
+    let vr_offs = bx.inbounds_ptradd(va_list_addr, bx.cx.const_usize(3 * ptr_offset + i32_offset));
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_llvm/src/va_arg.rs:115]: Normally I'd feel bad about this kind of manual layout computation, but this file is already packed full of hardcoded offsets and assumptions.

At some point we should re-evaluate whether we can use the LLVM `va_arg` directly.

To that point, I'm confused about the comment

> The LLVM va_arg instruction is lacking in some instances, so we should only use it as a fallback.

...does Clang also implement this logic manually?

File: compiler/rustc_codegen_ssa/src/mir/place.rs [hunk 2]
```diff
@@ -102,34 +102,10 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
...
-                }
-                _ => {
-                    let ty = bx.backend_type(self.layout);
-                    bx.struct_gep(ty, self.llval, bx.cx().backend_field_index(self.layout, ix))
-                }
+            let llval = if offset.bytes() == 0 {
+                self.llval
+            } else {
+                bx.inbounds_ptradd(self.llval, bx.const_usize(offset.bytes()))
             };
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_ssa/src/mir/place.rs:109]: The old code used non-inbounds GEP for ZSTs. But [it's okay for inbounds to point one-past-the end](https://llvm.org/docs/LangRef.html#getelementptr-instruction):

> The base pointer has an in bounds address of an allocated object, which means that it points into an allocated object, or to its end.

...which handles the ZST being "outside" of e.g. `struct Foo(u64, ())` (where it is at an offset of 8 bytes), so I think using inbounds for ZST fields is okay. Unless ZSTs can be arbitrarily far outside the bounds of a layout? (@oli-obk?)

File: compiler/rustc_codegen_ssa/src/mir/place.rs [hunk 3]
```diff
@@ -188,7 +164,7 @@ impl<'a, 'tcx, V: CodegenObject> PlaceRef<'tcx, V> {
         debug!("struct_field_ptr: DST field offset: {:?}", offset);
 
         // Adjust pointer.
-        let ptr = bx.gep(bx.cx().type_i8(), self.llval, &[offset]);
+        let ptr = bx.ptradd(self.llval, offset);
```
Comment (erikdesjardins) [inline compiler/rustc_codegen_ssa/src/mir/place.rs:167]: This can probably be `inbounds` as well, I don't know why DSTs would be different. (I certainly hope we don't allow DST fields to go out of bounds...) Maybe I'll open another PR for this.

File: compiler/rustc_codegen_ssa/src/mir/place.rs (hunk 2 above)
Comment (oli-obk) [reply compiler/rustc_codegen_ssa/src/mir/place.rs:109]: Miri doesn't catch it yet: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=682be508e94b238472eccdb9e1fdef3b

And it seems to be an open question on whether it is ok or not: https://github.com/rust-lang/unsafe-code-guidelines/issues/93

Tho looks like it's leaning towards it being ok I think?

Comment (erikdesjardins) [reply compiler/rustc_codegen_ssa/src/mir/place.rs:109]: Only the initial field offset in that example (`x.1`) will go through this code, so I think it would be fine...but I'll change it back to non-inbounds for ZSTs anyways, so that the only functional change in this PR is the GEP i8/ptradd change, and since ZST field offsets should never be performance critical, so it doesn't really matter.

File: compiler/rustc_codegen_llvm/src/va_arg.rs (hunk 1 above)
Comment (nikic) [reply compiler/rustc_codegen_llvm/src/va_arg.rs:115]: Yes. LLVM types are not rich enough to encode all the necessary ABI requirements to make something like the va_arg instruction work correctly. It would probably be best to remove it entirely.

**Comment by nikic** [comment]
We did not encounter any significant issues when we started canonicalizing these upstream, so I think it's fairly safe to do this step now. We could wait until the LLVM 19 release, but it doesn't really seem necessary.

@bors r+ rollup=never

**Comment by RalfJung** [comment]
This PR is at the top of the queue but not being processed...

**Comment by erikdesjardins** [comment]
I can't reproduce that failure locally. In a windows VM with build/host/target set to `i686-pc-windows-gnu`, all rustdoc tests pass, including `tests\rustdoc\issue-94183-blanket-impl-reexported-trait.rs`.

<details>
<summary>
Output
</summary>

```
C:\dev\rust>python x.py test --stage 2 tests\rustdoc\issue-94183-blanket-impl-reexported-trait.rs
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.17s
Building stage0 library artifacts (i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.51s
Building compiler artifacts (stage0 -> stage1, i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 1.08s
Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
Building stage1 library artifacts (i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.72s
Building compiler artifacts (stage1 -> stage2, i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 1.74s
Creating a sysroot for stage2 compiler (use `rustup toolchain link 'name' build/host/stage2`)
Uplifting library (stage1 -> stage2)
Building stage0 tool compiletest (i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.97s
Building tool rustdoc (stage1 -> stage2, i686-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.99s
Testing stage2 compiletest suite=rustdoc mode=rustdoc (i686-pc-windows-gnu)
warning: `tidy` is not installed; diffs will not be generated

running 1 tests
.

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 678 filtered out; finished in 1.62s

Build completed successfully in 0:00:18
```
</details>

So let's retry?

(Fingers crossed this change doesn't trigger a BOLT miscompile or something...)

**Comment by mati865** [comment]
> (Fingers crossed this change doesn't trigger a BOLT miscompile or something...)

Windows GNU doesn't use PGO or BOLT so that must be something else. Did you use the same mingw-w64 toolchain as Rust CI?

**Comment by erikdesjardins** [comment]
Yes. The same `i686-12.2.0-release-posix-dwarf-rt_v10-rev0.7z` that's referenced here: https://github.com/rust-lang/rust/blob/279c9ba260389ac92c4827a721d3163c4e519f66/src/ci/scripts/install-mingw.sh#L12

(At least, assuming that the package mirrored in rustc's S3 is the same as [this release](https://github.com/niXman/mingw-builds-binaries/releases/tag/12.2.0-rt_v10-rev0), which I downloaded.

**Comment by mati865** [comment]
Yeah, that's the same toolchain. If it fails again I'll try to look into it in the following days.

**Comment by nnethercote** [comment]
Are the binary size increases expected?

**Comment by erikdesjardins** [comment]
It's not _unexpected_ per se, since an intended consequence of this is more GEPs being merged, which can push things under inlining/vectorization thresholds.

It looks like almost all of the size regressions are nearly the exact same magnitude:

image

<details>
<summary>js diff</summary>

```js
[...document.querySelectorAll('tr.toggle')].forEach(e => {
    const [before, after] = [...e.querySelectorAll('td.numeric')];

    const td = document.createElement('td');
    const diff = after.querySelector('abbr').title - before.querySelector('abbr').title;

    td.textContent = diff > 0 ? '+' + diff : diff;
    
    e.append(td);
});
```
</details>

which suggests that something in the std "runtime" is getting slightly bigger.

I'll diff one of those and see if I can figure out what it is

**Comment by erikdesjardins** [comment]
The regression is all in backtrace-related code:

```
_ZN3std12backtrace_rs9symbolize5gimli7Context3new                                                              +288 bytes (17760 -> 18048) +047 insts (3525 -> 3572), +0 funcs ( 1 ->  1)
_ZN9addr2line16ResUnit$LT$R$GT$25find_function_or_location28_$u7b$$u7b$closure$u7d$$u7d$                       +256 bytes (11792 -> 12048) +023 insts (2507 -> 2530), +0 funcs ( 1 ->  1)
_ZN3std12backtrace_rs9symbolize5gimli7resolve                                                                  +240 bytes (14800 -> 15040) +025 insts (2709 -> 2734), +0 funcs ( 1 ->  1)
_ZN4core6option19Option$LT$$RF$T$GT$6cloned                                                                    +176 bytes (    0 ->   176) +056 insts (   0 ->   56), +1 funcs ( 0 ->  1)
_ZN5gimli4read8rnglists20RngListIter$LT$R$GT$4next                                                             +160 bytes ( 3248 ->  3408) +043 insts ( 813 ->  856), +0 funcs ( 1 ->  1)
_ZN9addr2line11render_file                                                                                     +112 bytes (  848 ->   960) +034 insts ( 201 ->  235), +0 funcs ( 1 ->  1)
_ZN93_$LT$gimli..read..line..LineProgramHeader$LT$R$C$Offset$GT$$u20$as$u20$core..clone..Clone$GT$5clone       +096 bytes ( 1120 ->  1216) +033 insts ( 244 ->  277), +0 funcs ( 1 ->  1)
_ZN5gimli4read5dwarf13Unit$LT$R$GT$3new                                                                        +064 bytes (10224 -> 10288) +016 insts (2063 -> 2079), +0 funcs ( 1 ->  1)
_ZN5gimli4read4unit18Attribute$LT$R$GT$5value                                                                  +032 bytes ( 1328 ->  1360) +006 insts ( 382 ->  388), +0 funcs ( 1 ->  1)
_ZN9addr2line30LoopingLookup$LT$T$C$L$C$F$GT$10new_lookup                                                      +032 bytes ( 1536 ->  1568) -011 insts ( 352 ->  341), +0 funcs ( 1 ->  1)
_ZN9addr2line5Lines5parse                                                                                      +016 bytes ( 9920 ->  9936) +012 insts (2144 -> 2156), +0 funcs ( 1 ->  1)
_ZN5gimli4read5dwarf14Dwarf$LT$R$GT$11attr_string                                                              +016 bytes (  592 ->   608) +004 insts ( 165 ->  169), +0 funcs ( 1 ->  1)
_ZN5alloc7raw_vec11finish_grow                                                                                 +016 bytes (  576 ->   592) +003 insts ( 188 ->  191), +0 funcs ( 4 ->  4)
_ZN3std2io5Write18write_all_vectored                                                                           +016 bytes ( 1328 ->  1344) +003 insts ( 347 ->  350), +0 funcs ( 2 ->  2)
_ZN9addr2line16ResUnit$LT$R$GT$18dwarf_and_unit_dwo                                                            +016 bytes ( 1376 ->  1392) +002 insts ( 289 ->  291), +0 funcs ( 1 ->  1)
_ZN11miniz_oxide7inflate4core10decompress                                                                      +016 bytes ( 7888 ->  7904) +001 insts (1913 -> 1914), +0 funcs ( 1 ->  1)
_ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$7reserve21do_reserve_and_handle                                          -016 bytes (  944 ->   928) +008 insts ( 232 ->  240), +0 funcs ( 5 ->  5)
_ZN5gimli4read6abbrev13Abbreviations6insert                                                                    -016 bytes ( 4864 ->  4848) +006 insts ( 918 ->  924), +0 funcs ( 1 ->  1)
_ZN9addr2line8function17Function$LT$R$GT$14parse_children                                                      -016 bytes ( 5376 ->  5360) +003 insts (1088 -> 1091), +0 funcs ( 1 ->  1)
_ZN3std4path7PathBuf14_set_extension                                                                           -016 bytes (  624 ->   608) +000 insts ( 167 ->  167), +0 funcs ( 1 ->  1)
_ZN5alloc3ffi5c_str7CString19_from_vec_unchecked                                                               -016 bytes (  352 ->   336) +000 insts (  97 ->   97), +0 funcs ( 1 ->  1)
_ZN91_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$3fmt           -016 bytes (  592 ->   576) -002 insts ( 123 ->  121), +0 funcs ( 1 ->  1)
_ZN69_$LT$std..sys..pal..unix..stdio..Stderr$u20$as$u20$std..io..Write$GT$14write_vectored                     -016 bytes (   96 ->    80) -004 insts (  29 ->   25), +0 funcs ( 1 ->  1)
_ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$16reserve_for_push                                                       -032 bytes ( 3296 ->  3264) +027 insts ( 834 ->  861), +0 funcs (17 -> 17)
```
(`Option::cloned` doesn't get inlined...in `_ZN9addr2line11render_file`.)

(Generated with [this ad-hoc script](https://gist.github.com/erikdesjardins/8212e23cf07ba235628717c6159fe838). There's probably some existing way to do this though, isn't there...)

It's kind of interesting that the regression is spread across a bunch of different functions but all in backtrace-related code. Although probably it's just because one function was optimized differently and the butterfly effect cascaded to everything else in its call graph.

Looking at `gimli7Context3new`, it's very hard to see anything meaningful in the asm diff, even with all constants and registers normalized, hundreds of instructions are moved around. It doesn't look obviously worse, just...perturbed. Same with `find_function_or_location`.

So I don't really see anything actionable here.

It does make me wonder if we should be compiling backtrace-related crates with `opt-level=s` though--there's a ton of enormous functions and just scanning through (not necessarily in the changed functions) I see some unrolled loops. Size is probably more of a priority than runtime performance for backtrace code.

**Comment by Kobzol** [comment]
> (Generated with [this ad-hoc script](https://gist.github.com/erikdesjardins/8212e23cf07ba235628717c6159fe838). There's probably some existing way to do this though, isn't there...)

```bash
$  cargo run --bin collector binary_stats --symbols <rustc>
```
But it will show slightly different stuff than your script.

**Comment by workingjubilee** [comment]
> It does make me wonder if we should be compiling backtrace-related crates with opt-level=s though--there's a ton of enormous functions and just scanning through (not necessarily in the changed functions) I see some unrolled loops. Size is probably more of a priority than runtime performance for backtrace code.

Runtime performance isn't _zero_ concern for backtrace code, oddly enough (mainly for the "forced capture" case), but backtrace-rs contains algorithmic optimizations which already make the appropriate trades, so yes, if you can get a significantly smaller code size by optimizing in that direction, that would be good.

We can also look at working with the addr2line and gimli maintainers to reduce the code size a bit, if we can identify the heaviest-hitters in those crates.
