### PR TITLE
Make RPITITs inherit the `assumed_wf_types` of their parent method

### LINKED ISSUE #113796: AFIT no longer seems to play nice with lifetime GATs
Tracking issue: https://github.com/rust-lang/rust/issues/91611

A few months ago I authored a [complete example for a possible `AsyncIterator::lend` method](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=92cb8f410bf782c3c9e59c47c947a0bc). This used to compile fine on `rustc 1.71.0-nightly (f5559e338 2023-04-24)`, but it no longer does on the latest nightly. Here is a minimized repro:

```rust
#![allow(incomplete_features)]
#![feature(async_fn_in_trait)]

trait AsyncLendingIterator {
    type Item<'a>
    where
        Self: 'a;

    async fn next(&mut self) -> Option<Self::Item<'_>>;
}

struct Lend<I>(I);
impl<I> AsyncLendingIterator for Lend<I> {
    type Item<'a> = &'a I
    where
        Self: 'a;

    async fn next(&mut self) -> Option<Self::Item<'_>> {
        todo!()
    }
}
```

This gives the following error:

```text
Compiling playground v0.0.1 (/playground)
error[[E0311]](https://doc.rust-lang.org/nightly/error_codes/E0311.html): the parameter type `T` may not live long enough
  --> src/main.rs:29:5
   |
29 |     async fn next(&mut self) -> Option<Self::Item<'_>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the parameter type `T` must be valid for the anonymous lifetime as defined here...
  --> src/main.rs:9:19
   |
9  |     async fn next(&mut self) -> Option<Self::Item<'_>>;
   |                   ^
note: ...so that the type `LendingIter<T>` will meet its required lifetime bounds
  --> src/main.rs:29:5
   |
29 |     async fn next(&mut self) -> Option<Self::Item<'_>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0311`.
error: could not compile `playground` (bin "playground") due to previous error
```

I have a feeling async traits no longer play nice with lifetime GATs?

### Meta
Tested on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=65ebfd25e9d6acf289466066a007eb64) using the current nightly:
```
nightly-2023-07-16 0e8e857b11f60a785aea
```

---

cc/ @rust-lang/wg-async, @compiler-errors

### PR DESCRIPTION
**Pull request by compiler-errors**
... and then move the RPITIT well-formedness check to just use the regular logic of wfchecking an associated type.

---

We need to inherit the `assumed_wf_types` of the RPITIT's parent function in order for the given code to be considered well-formed:

```rust
trait Foo {
  fn bar<'a, T>(_: &'a T) -> impl Iterator<Output = &'a T>;
}
```

Since for `&'a T` to be WF, we need `T: 'a`.

In order for this to work for late-bound lifetimes, we need to do some additional mapping of any late-bound lifetimes captured by these assumed wf types. This is because within the body of the function (and thus in the `assumed_wf_types`), they're represented as `ReFree` variants of the original late-bound lifetimes declared in the function's generics, but in the RPITIT's GAT, they're represented as "reified" `ReEarlyBound` vars (duplicated during opaque type lowering). Luckily, the mapping between these two is already [stored in the opaque](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/struct.OpaqueTy.html#structfield.lifetime_mapping).

Fixes #113796

### CODE REVIEW

File: compiler/rustc_ty_utils/src/implied_bounds.rs [hunk 1]
```diff
@@ -42,6 +44,41 @@ fn assumed_wf_types<'tcx>(tcx: TyCtxt<'tcx>, def_id: LocalDefId) -> &'tcx [(Ty<'
...
+                                name,
+                            },
+                        ),
+                    );
+                }
+            }
+            let a = tcx.fold_regions(tcx.assumed_wf_types(fn_def_id.expect_local()).to_vec(), |re, _| {
+                if let Some(re) = mapping.get(&re) { *re } else { re }
+            });
+            tcx.arena.alloc_from_iter(a)
```
Comment (spastorino) [inline compiler/rustc_ty_utils/src/implied_bounds.rs]: Can we add docs that explain what going on here?

File: compiler/rustc_ty_utils/src/implied_bounds.rs [hunk 2]
```diff
@@ -42,6 +51,74 @@ fn assumed_wf_types<'tcx>(tcx: TyCtxt<'tcx>, def_id: LocalDefId) -> &'tcx [(Ty<'
...
+                                    def_id: new_early_bound_def_id.to_def_id(),
+                                    index,
+                                    name,
+                                },
+                            ),
+                        );
+                    }
+                }
+                // FIXME: This could use a real folder, I guess.
+                let a = tcx.fold_regions(
```
Comment (spastorino) [inline compiler/rustc_ty_utils/src/implied_bounds.rs:97]: can you give this a more meaningful name?

File: compiler/rustc_ty_utils/src/implied_bounds.rs [hunk 3]
```diff
@@ -42,6 +51,74 @@ fn assumed_wf_types<'tcx>(tcx: TyCtxt<'tcx>, def_id: LocalDefId) -> &'tcx [(Ty<'
...
+                    tcx.assumed_wf_types(fn_def_id.expect_local()).to_vec(),
+                    |re, _| {
+                        if let Some(re) = mapping.get(&re) { *re } else { re }
```
Comment (spastorino) [inline compiler/rustc_ty_utils/src/implied_bounds.rs:100]: This is fine by me to be honest so do whatever you prefer with this comment but I guess if you find a way to name the `re` inside `Some` differently it may be a little bit clearer?

**Review by spastorino — COMMENTED** [review]
This is great Michael, thanks for doing this.

r=me after checking my nits and doing what you prefer with them.

**Comment by compiler-errors** [comment]
had to bless a test

@bors r=spastorino
