### PR TITLE
Fix wording around sort guarantees

### LINKED ISSUE #38524: Reconsidering the recent changes in sort guarantees
The PR in question is #38192.

@steveklabnik had some [objections](https://www.reddit.com/r/rust/comments/5jkvo0/four_years_with_rust/dbh394k/) to new guarantees of the sort algorithm.

**Old** guarantees: "This sort is stable and O(n log n) worst-case but allocates approximately 2 * n where n is the length of self."
**New** guarantees: "This sort is stable and O(n log n) worst-case, but allocates temporary storage half the size of self."

The new version is ATM in nightly only, so we still have time to adjust it. I agree that saying "**approximately** half the size" would be slightly better.

However... should we perhaps leave the guarantees as they were (`2 * n`), in order not to make alternative implementations non-compliant? What exactly should the documentation say?

Here's my stance on the issue:

First, sort algorithms should never ever allocate `2 * n` additional memory. That's just way too much and I'm strongly against `2 * n`. Even the old merge sort can be easily tweaked to allocate just `n` without compromising performance.

Second, stable sorts can often get away with allocating just `n / 2`. In fact, I successfully tweaked the old merge sort to allocate just `n / 2` before I jumped on the TimSort ship.

Any stable sort that requires `n` memory can be made to work with just `n / 2`. Here's how. Split the input array in half. Sort each half using the allocated auxilliary buffer (which is of same length as the half itself). Move one of the halves into the buffer. Merge them into the original orray. Done.

Guarantees in some other programming languages:
1. Python ([source](https://svn.python.org/projects/python/trunk/Objects/listsort.txt)) - TimSort allocates `n / 2`.
2. Java ([source](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7-b147/java/util/TimSort.java)) - TimSort allocates `n / 2`.
3. C++ ([docs](http://en.cppreference.com/w/cpp/algorithm/stable_sort)) - `std::stable_sort` allocates `n`.

I believe it's safe to say that the standard sort allocates approximately `n / 2`, but would be okay with guaranteeing `n`, too.

Libs team, what do you think? @bluss?

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #38524 

/cc @rust-lang/libs @stjepang

### CODE REVIEW

File: src/libcollections/slice.rs [hunk 1]
```diff
@@ -1041,8 +1041,11 @@ impl<T> [T] {
 
     /// This is equivalent to `self.sort_by(|a, b| a.cmp(b))`.
     ///
-    /// This sort is stable and `O(n log n)` worst-case, but allocates
-    /// temporary storage half the size of `self`.
+    /// This sort is stable and `O(n log n)` worst-case. 
+    ///
+    /// # Current Implementation
+    /// 
+    /// The current implementation allocates temporary storage half the size of `self`.
```
Comment (stjepang) [inline src/libcollections/slice.rs]: Now that we have a section about the current implementation, this would be a great chance to expand a little bit. For inspiration, see [Java's docs](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#sort(java.util.List)) starting from "Implemenation note".

I would like to see several things pointed out:

1. That this sort is an adaptation of Tim Peter's timsort with this [link](http://svn.python.org/projects/python/trunk/Objects/listsort.txt).
2. That this is an iterative sort.
3. That this is an adaptive sort. Again, Java has a nice explanation: "It is well-suited to merging two or more sorted arrays: simply concatenate the arrays and sort the resulting array."

File: src/libcollections/slice.rs [hunk 2]
```diff
@@ -1041,8 +1041,11 @@ impl<T> [T] {
 
     /// This is equivalent to `self.sort_by(|a, b| a.cmp(b))`.
     ///
-    /// This sort is stable and `O(n log n)` worst-case, but allocates
-    /// temporary storage half the size of `self`.
+    /// This sort is stable and `O(n log n)` worst-case.
```
Comment (stjepang) [inline src/libcollections/slice.rs]: Let's explain what "stable" means, since it can be a confusing term for people unfamiliar with it.
Java's docs have a nice concise explanation: "This sort is guaranteed to be stable: equal elements will not be reordered as a result of the sort."

**Review by ghost — CHANGES_REQUESTED** [review]
You changed the documentation of `sort()`, but forgot about `sort_by` and `sort_by_key` :)

The current changes will resolve the discussed normativity issue, which is good. However, I'd like to push for higher quality documentation while we're at it.

I left a few suggestions on how to do that. We don't need long boring walls of text. Just a few points on the key characteristics of this particular implementation.

**Comment by stjepang** [comment]
One more thing I noticed...

`sort_by` has this explanation: Sorts the slice, in place, using `compare` to compare elements.
I'd like to see "in place" gone because it sounds like `sort_by` does not allocate, which is incorrect.

`sort_by_key` has this explanation: Sorts the slice, in place, using `f` to extract a key by which to order the sort by.
We again have "in place" but this time it at least makes sense - it's trying to say that `sort_by_key` does not do decorate-sort-undecorate.
However, I'm not too happy with "in place" here either and would prefer different wording.

**Comment by steveklabnik** [comment]
@brson @alexcrichton are we going to backport this? If so, I can wrap it up right now, but if not, I'd rather not drop everything to do so. know you wanted to get beta done by today

**Comment by alexcrichton** [comment]
I'd be ambivalent about a backport. I wouldn't advocate for it but I also wouldn't say no.

**Review by ghost — APPROVED** [review]

**Comment by alexcrichton** [comment]
@steveklabnik looks like there's a whitespace error here, but other than that r=me
