### PR TITLE
arithmetic-overflow checks during const-eval

### LINKED ISSUE #22531: constant evaluation should not mask overflow for cases that are otherwise checked
While working on rebasing #20795 I discovered that the new `run-fail` tests it adds were failing to panic, because the arithmetic in question was being handled by the constant evaluation, and the overflow was thus happening at compile time rather than run time.

An example of such an expression:

```rust
fn main() {
    let x = 200u8 + 200u8 + 200u8;
}
```

(Thank goodness it didn't cause my `rustc` to panic!  That would have been a bit frustrating.)

Anyway, we should fix that, as part of #22020.

That is, the program above should fail to compile, and it should not cause an ICE; it should signal a proper error message saying that the arithmetic expression overflowed (because 200+200+200 == 600 > 255 == u8::MAX).

### LINKED ISSUE #23030: Should C-style enums silently overflow?
Spawned off of a note from PR #22532 on commit 1246d4067fdc034d064dfb78f88c2c3c079c3f4f

The following program:
```rust
#[repr(usize)]
enum Foo {
    A = 0xffffffffffffffff_usize,
    B,
    C
}

fn main() {
    println!("Hello World: {:x}", Foo::A as usize);
    println!("Hello World: {:x}", Foo::B as usize);
    println!("Hello World: {:x}", Foo::C as usize);
}
```

compiles and prints:
```
Hello World: ffffffffffffffff
Hello World: 0
Hello World: 1
```

My personal preference would be for a compiler error due to the implicit overflow, with a note saying that the programmer should explicitly assign some value to `Foo::B`. (And thus they can opt into the current behavior by assigning it `B = 0,`; then `Foo::C` would continue to be assigned 1 as today.)

### LINKED ISSUE #23221: Can't implement Copy for C style enums with negative discriminants that overflow into unspecified positive discriminants
```rust
fn main() { }

#[repr(C)]
#[derive(Copy)]
enum X {
    A = -1,
    B,
}
```
```
test5.rs:7:5: 7:6 error: Discriminant overflowed!
test5.rs:7     B,
               ^
```

### LINKED ISSUE #23235: Overflow checking failed on #[repr(i64)] enums
Code:

```rust
#[repr(i64)]
enum X {
    A = 0x_7FFF_FFFF_FFFF_FFFF,
    B,
}

fn main() {
    println!("{}", X::A as i64);
    println!("{}", X::B as i64);
}
```

Output:
```
9223372036854775807
-9223372036854775808
```

This is the opposite of https://github.com/rust-lang/rust/issues/23221

### PR DESCRIPTION
**Pull request by pnkfelix**
const_eval : add overflow-checking for {`+`, `-`, `*`, `/`, `<<`, `>>`}.

One tricky detail here: There is some duplication of labor between `rustc::middle::const_eval` and `rustc_trans::trans::consts`. It might be good to explore ways to try to factor out the common structure to the two passes (by abstracting over the particular value-representation used in the compile-time interpreter).

---

Update: Rebased atop #23841

Fix #22531

Fix #23030

Fix #23221

Fix #23235

### CODE REVIEW

**Comment by pnkfelix** [comment]
cc @eddyb 

(actually, I'd be happy to take a review from eddyb)

Also, eddyb: You may be concerned about collisions here with your own const-fn work. Feel free to recommend some ordering on how the two PR's land, or suggest some other strategy to avoid unnecessary rebasing effort.

**Comment by eddyb** [comment]
`const fn` is pretty simple, really, there won't be much churn I would have to deal with (I don't think).

As for the checks in trans: I did something else for div/rem: `check_const` invokes `const_eval` for those binops on integers and errors if evaluation fails.
Sadly, that doesn't work well in the presence of `const fn` and associated constants.

@nikomatsakis I wonder if recording "obligations" on constant evaluation would make sense - like `where` clauses, but implicit and working on values (either arguments of `const fn`s or associated constants on type parameters).

File: src/librustc/middle/const_eval.rs [hunk 1]
```diff
@@ -297,57 +307,294 @@ impl ConstEvalErr {
...
+            if !oflo { Ok($const_ty(ret)) } else { signal!(e, $signal_exn) }
+        }
+    }
 }
-fn checked_sub_uint(e: &Expr, a: u64, b: u64) -> Result<const_val, ConstEvalErr> {
-    let (ret, oflo) = a.overflowing_sub(b);
-    if !oflo { Ok(const_uint(ret)) } else { signal!(e, SubuWithOverflow(a, b)) }
+
+pub_fn_checked_op!{ const_int_checked_add(a: i64, b: i64,.. IntTy) {
+           int_arith_body overflowing_add const_int AddiWithOverflow(a, b)
```
Comment (eddyb) [inline src/librustc/middle/const_eval.rs]: Are the indentation levels here intentional?

Comment (pnkfelix) [inline src/librustc/middle/const_eval.rs]: yeah it was so that the operator name (e.g. "add") would line up in both the method name and in the operator invocation.

Maybe I would have been better off using some well-placed calls to `stringify!`...

**Comment by nikomatsakis** [comment]
r+ modulo the FIXME

**Comment by eddyb** [comment]
@nikomatsakis Should we open a discussion about the interactions between `trans::consts` and `const_eval` somewhere else?

I personally prefer checking somewhere higher than `trans`, but in the end, what I am not particularly fond of is extracting values from LLVM for checking.

It works for this PR, and it's not enough to stop it from merging (we *need* those checks in beta), but I hope we can find a cleaner solution.

**Comment by pnkfelix** [comment]
@eddyb @nikomatsakis 
> Should we open a discussion about the interactions between trans::consts and const_eval somewhere else?

I just made this post on internals: http://internals.rust-lang.org/t/removing-const-eval-duplication-of-labor-between-librustc-and-librustc-trans/1786

so we can continue that conversation in a focused fashion there.

**Comment by pnkfelix** [comment]
@bors r-

I want to check this in a cross-compiling environment, and perhaps land it in tandem with #23841  and perhaps a fix for #23890

**Comment by pnkfelix** [comment]
(I have now rebased this atop #23841, but I am pretty sure that it is going to conflict with other PR's in the queue, namely #23549, so I am still holding off on putting back the r+ until I see if that lands or not.)

**Comment by pnkfelix** [comment]
annoying: the error messages on some of my tests are different for 64-bit compile versus a cross-compiling 64-bit host/32-bit target.  :(

**Comment by pnkfelix** [comment]
r=nikomatsakis ; @alexcrichton says he will merge into next rollup.

**Comment by andersk** [comment]
I think this caused #23968: `!0u32/2` gives “error: attempted to divide with overflow in a constant expression [E0020]”.
