### PR TITLE
remove InPlaceIterable marker from Peekable due to unsoundness

### LINKED ISSUE #85322: The implementation of `InPlaceIterable` for `Peekable` is unsound
This code leads to an out of bounds write, makes the assert fail and triggers miri:

```rust
fn main() {
    let v = vec![0; 5];
    let mut i = v.into_iter().peekable();
    i.peek();
    let v = i.clone().collect::<Vec<_>>();
    assert!(v.len() <= v.capacity());
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5ae04e3e0e8609192bea44fd6782f55)

The problem is that after cloning a `Peekable` the inner iterator can no longer be considered advanced, but the `Peekable` may still yield the peeked element without advancing it, thus breaking the contract of `InPlaceIterable`.

### PR DESCRIPTION
**Pull request by the8472**
The unsoundness is not in Peekable per se, it rather is due to the
interaction between Peekable being able to hold an extra item
and vec::IntoIter's clone implementation shortening the allocation.

An alternative solution would be to change IntoIter's clone implementation
to keep enough spare capacity available.

fixes #85322

### CODE REVIEW

**Comment by SkiFire13** [comment]
I think you could also add a regression test, just to make sure this bug is catched if someone will try to implement `InPlaceIterable`  for `Peekable` again in the future.

**Comment by the8472** [comment]
Right, will do. I might even try to salvage the optimization later so it's good to have a test.

**Comment by the8472** [comment]
Perf looks neutral.

@rustbot label T-libs-impl

File: library/alloc/tests/vec.rs [hunk 1]
```diff
@@ -1095,6 +1094,18 @@ fn test_from_iter_specialization_panic_during_drop_leaks() {
...
+// the contract.
+#[test]
+fn test_collect_after_iterator_clone() {
+    let v = vec![0; 5];
+    let mut i = v.into_iter().peekable();
+    i.peek();
+    let v = i.clone().collect::<Vec<_>>();
+    assert!(v.len() <= v.capacity());
+}
+
```
Comment (SkiFire13) [inline library/alloc/tests/vec.rs:1108]: I was wondering if this test could be improved. Right now this detects the problem only because `IntoIter::clone` allocates a vec with the exact capacity needed but if it allocated extra capacity **at the end** of the vec this test would actually pass even though the `Peekable` implementation is still wrong. A more robust test should also check that it doesn't overwrite each element before reading it. For example:

```suggestion
#[test]
fn test_collect_after_iterator_clone() {
    let v = vec![0; 5];
    let mut i = v.into_iter().map(|i| i + 1).peekable();
    i.peek();
    let v = i.clone().collect::<Vec<_>>();
    assert_eq!(v, [1, 1, 1, 1, 1]);
    assert!(v.len() <= v.capacity());
}
```

With the current implementation the first assert fails due to `v` being equal to `[1, 2, 3, 4, 5]`. Another option would be changing the `0` to something like `String::from("abc")` and hope that the test catches the quintuple free.

**Comment by pietroalbini** [comment]
Nominating to beta backport [as requested on Zulip](https://zulip-archive.rust-lang.org/241545trelease/09318betabackports.html#239570461).

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/21853weekly2021052054818.html#239601929)

@rustbot label +beta-accepted
