### PR TITLE
Reduce the diagnostic spam when multiple fields are missing in pattern

### LINKED ISSUE #47457: Collect multiple missing fields on struct pattern into a single diagnostic
When confusing a Fn-like struct with a regular struct in an `if let` pattern, the output leaves a lot to be desired:
```rust
struct S(usize, usize, usize, usize);

fn main() {
    if let S { a, b, c, d } = S(1, 2, 3, 4) {
        println!("hi");
    }
}
```
<details><summary>
<a href="https://play.rust-lang.org/?gist=7480b80ff35037ef78d4727e80e7abca&version=nightly">Current output</a></summary>

```
error[E0026]: struct `S` does not have a field named `a`
 --> src/main.rs:4:16
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |                ^ struct `S` does not have field `a`
 
error[E0026]: struct `S` does not have a field named `b`
 --> src/main.rs:4:19
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |                   ^ struct `S` does not have field `b`

error[E0026]: struct `S` does not have a field named `c`
 --> src/main.rs:4:22
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |                      ^ struct `S` does not have field `c`

error[E0026]: struct `S` does not have a field named `d`
 --> src/main.rs:4:25
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |                         ^ struct `S` does not have field `d`

error[E0027]: pattern does not mention field `0`
 --> src/main.rs:4:12
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^^^ missing field `0`
  |
  = note: trying to match a tuple variant with a struct variant pattern

error[E0027]: pattern does not mention field `1`
 --> src/main.rs:4:12
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^^^ missing field `1`
  |
  = note: trying to match a tuple variant with a struct variant pattern

error[E0027]: pattern does not mention field `2`
 --> src/main.rs:4:12
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^^^ missing field `2`
  |
  = note: trying to match a tuple variant with a struct variant pattern

error[E0027]: pattern does not mention field `3`
 --> src/main.rs:4:12
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^^^ missing field `3`
  |
  = note: trying to match a tuple variant with a struct variant pattern

error: aborting due to 8 previous errors
```
</details>

We should probably collect all these errors into a single diagnostic error:

```
error[E0026]: struct `S` does not have a field named `a`, `b`, `c` or `d`
 --> src/main.rs:4:16
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |                ^  ^  ^  ^ struct `S` does not have these fields
  = note: trying to match a tuple variant with a struct variant pattern

error[E0027]: pattern does not mention fields `0`, `1`, `2`, or `3`
 --> src/main.rs:4:12
  |
4 |     if let S { a, b, c, d } = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^^^ missing fields `0`, `1`, `2`, and `3`
  |
  = note: trying to match a tuple variant with a struct variant pattern
  = help: you probably meant to use tuple struct syntax:
  |
4 |     if let S (a, b, c, d) = S(1, 2, 3, 4) {
  |            ^^^^^^^^^^^^^^
```

Even better if there was only one diagnostic.

### PR DESCRIPTION
**Pull request by estebank**
Fix #47457.

### CODE REVIEW

File: src/test/ui/missing-fields-in-struct-pattern.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+// file at the top-level directory of this distribution and at
+// http://rust-lang.org/COPYRIGHT.
+//
+// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
+// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
+// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
+// option. This file may not be copied, modified, or distributed
+// except according to those terms.
+
+struct S(usize, usize, usize, usize);
```
Comment (oli-obk) [inline src/test/ui/missing-fields-in-struct-pattern.rs]: did you forget to generate or `git add` a .stderr file?

File: src/librustc_typeck/check/_match.rs [hunk 2]
```diff
@@ -963,6 +937,46 @@ https://doc.rust-lang.org/reference/types.html#trait-objects");
...
+            let mut err = struct_span_err!(tcx.sess,
+                                           spans,
+                                           E0026,
+                                           "{} `{}` does not have {}",
+                                           kind_name,
+                                           tcx.item_path_str(variant.did),
+                                           field_names);
+            for (span, name) in &inexistent_fields {
+                err.span_label(*span,
+                               format!("{} `{}` does not have field `{}`",
```
Comment (oli-obk) [inline src/librustc_typeck/check/_match.rs]: I think the labels could just be `unknown field` instead of repeating all information

**Review by oli-obk — CHANGES_REQUESTED** [review]
r? @oli-obk iirc eddyb doesn't like diagnostics PRs

File: src/librustc_typeck/check/_match.rs (hunk 2 above)
Comment (oli-obk) [reply src/librustc_typeck/check/_match.rs]: or, since these are usually very compact, do something similar to use imports:

```
warning: unused imports: `u32`, `usize`
 --> src/main.rs:1:11
  |
1 | use std::{usize, u32};
  |           ^^^^^  ^^^
```

Comment (estebank) [reply src/librustc_typeck/check/_match.rs]: [Changed](https://github.com/rust-lang/rust/pull/49160/files#diff-fd9ccd843c9940dcc501010d9b603807).

File: src/test/ui/missing-fields-in-struct-pattern.rs (hunk 1 above)
Comment (estebank) [reply src/test/ui/missing-fields-in-struct-pattern.rs]: Added.

**Comment by oli-obk** [comment]
@bors r+

Looks sooo much better than the old spammy messages!

**Review by oli-obk — APPROVED** [review]
