### PR TITLE
Fix ICE in `improper_ctypes_definitions` lint with all-ZST transparent types

### LINKED ISSUE #87496: ICE: compiler/rustc_lint/src/types.rs:859:17: malformed transparent type
### Code

```Rust
#[repr(transparent)]
struct TransparentCustomZst(());
extern "C" {
    fn good17(p: TransparentCustomZst);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (9c25eb7aa 2021-07-25)
binary: rustc
commit-hash: 9c25eb7aa3a71fb951564b0ddf131be59c2c951d
commit-date: 2021-07-25
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
warning: struct is never constructed: `TransparentCustomZst`
 --> mutant.rs:2:8
  |
2 | struct TransparentCustomZst(());
  |        ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function is never used: `good17`
 --> mutant.rs:4:5
  |
4 |     fn good17(p: TransparentCustomZst);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: compiler/rustc_lint/src/types.rs:859:17: malformed transparent type

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1034:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (9c25eb7aa 2021-07-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 2 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: struct is never constructed: `TransparentCustomZst`
 --> mutant.rs:2:8
  |
2 | struct TransparentCustomZst(());
  |        ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function is never used: `good17`
 --> mutant.rs:4:5
  |
4 |     fn good17(p: TransparentCustomZst);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: compiler/rustc_lint/src/types.rs:859:17: malformed transparent type

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1034:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_lint::types::ImproperCTypesVisitor::check_variant_for_ffi
   8: rustc_lint::types::ImproperCTypesVisitor::check_type_for_ffi
   9: rustc_lint::types::ImproperCTypesVisitor::check_type_for_ffi_and_report_errors
  10: rustc_lint::types::ImproperCTypesVisitor::check_foreign_fn
  11: <rustc_lint::types::ImproperCTypesDeclarations as rustc_lint::passes::LateLintPass>::check_foreign_item
  12: rustc_hir::intravisit::Visitor::visit_nested_foreign_item
  13: rustc_hir::intravisit::walk_item
  14: rustc_hir::intravisit::Visitor::visit_nested_item
  15: rustc_lint::late::late_lint_mod
  16: rustc_query_system::query::plumbing::get_query_impl
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::lint_mod
  18: rustc_data_structures::sync::join
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
  21: rustc_interface::passes::analysis
  22: rustc_query_system::query::plumbing::get_query_impl
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  24: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  25: rustc_span::with_source_map
  26: rustc_interface::interface::create_compiler_and_run
  27: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (9c25eb7aa 2021-07-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
#0 [lint_mod] linting top-level module
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 2 warnings emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by FabianWolff**
Fixes #87496. There is also another function in the same file that looks fishy, but I haven't been able to produce an ICE there, and in any case, it's not related to #87496:
https://github.com/rust-lang/rust/blob/fd853c00e255559255885aadff9e93a1760c8728/compiler/rustc_lint/src/types.rs#L720-L734

r? @JohnTitor

### CODE REVIEW

File: src/test/ui/repr/repr-transparent-issue-87496.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// Regression test for the ICE described in #87496.
+
+// check-pass
+
+#[repr(transparent)]
+struct TransparentCustomZst(());
+extern "C" {
+    fn good17(p: TransparentCustomZst);
+}
```
Comment (hellow554) [inline src/test/ui/repr/repr-transparent-issue-87496.rs:9]: you could make the struct and extern fn pub to avoid warnings :)

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
LGTM, thanks for the follow-up! But I'm not part of t-compiler, so r? @nikomatsakis for the final review

File: compiler/rustc_lint/src/types.rs [hunk 2]
```diff
@@ -851,12 +851,13 @@ impl<'a, 'tcx> ImproperCTypesVisitor<'a, 'tcx> {
...
         if def.repr.transparent() {
-            // Can assume that only one field is not a ZST, so only check
+            // Can assume that at most one field is not a ZST, so only check
             // that field's type for FFI-safety.
             if let Some(field) = transparent_newtype_field(self.cx.tcx, variant) {
                 self.check_field_type_for_ffi(cache, field, substs)
             } else {
-                bug!("malformed transparent type");
+                // All fields are ZSTs
+                FfiSafe
```
Comment (camelid) [inline compiler/rustc_lint/src/types.rs:860]: I'm not sure if this is the correct behavior; in the implementation I had started, I initially went with `FfiSafe` but then switched to `FfiUnsafe`. The reason is that according to the issue where the new behavior was discussed (https://github.com/rust-lang/rust/issues/77841#issuecomment-716575747) \[emphasis mine\],

> That's a good point. So here is a proposed set of rules:
> 
>   * A `repr(transparent)` type `T` must meet the following rules:
>       
>     * It may have any number of 1-ZST fields
>     * In addition, it may have at most one other field of type U
> 
> 
> If that other field is present, then T behaves like type U for ABI purposes. **Otherwise, T consists only of 1-ZST types, and it behaves like `()`, which is the "canonical" 1-ZST.**

and `()` is currently FFI-**unsafe**:

```
warning: `extern` block uses type `()`, which is not FFI-safe
 --> src/lib.rs:2:18
  |
2 |     fn good17(p: ());
  |                  ^^ not FFI-safe
  |
  = note: `#[warn(improper_ctypes)]` on by default
  = help: consider using a struct instead
  = note: tuples have unspecified layout
```

There's also this later comment in that thread (https://github.com/rust-lang/rust/issues/77841#issuecomment-716698421):

> Hmm, the lint considers `()` an improper_ctype. But then an empty struct is UB(!?) in C, so I guess there isn't a canonical ABI for this.

File: src/test/ui/repr/repr-transparent-issue-87496.rs [hunk 3]
```diff
@@ -0,0 +1,11 @@
+// Regression test for the ICE described in #87496.
+
+// check-pass
```
Comment (camelid) [inline src/test/ui/repr/repr-transparent-issue-87496.rs:3]: Hmm, for some reason there doesn't seem to be a `.stderr` file being generated? Yet CI is passing...

File: compiler/rustc_lint/src/types.rs (hunk 2 above)
Comment (nikomatsakis) [reply compiler/rustc_lint/src/types.rs:860]: I think this is correct -- no fields ought to behave like `()`

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Per @camelid's point, the behavior for "all ZST fields" seems incorrect.

**Comment by JohnCSimon** [comment]
Triage: 
@FabianWolff can you mark the change request from nikomatsakis as completed if you've completed it? Thanks.

**Comment by FabianWolff** [comment]
> Triage:
> @FabianWolff can you mark the change request from nikomatsakis as completed if you've completed it? Thanks.

@JohnCSimon What exactly do you mean by this? I thought that's what the `@rustbot ready` is for (though it doesn't really seem to have had an effect above...). In any case, I've clicked on "Re-request review" for now.

**Comment by nikomatsakis** [comment]
Ugh! Sorry @FabianWolff, reading now!

**Review by nikomatsakis — APPROVED** [review]
