### PR TITLE
Miri: unleash all feature gates

### LINKED ISSUE #71630: Miri does not get entirely unleashed
I tried this code on nightly with `-Zunleash-the-miri-inside-of-you`:

```rust
#![allow(const_err)]
#![feature(const_raw_ptr_deref)]

use std::cell::UnsafeCell;


struct Meh {
    x: UnsafeCell<i32>,
}

unsafe impl Sync for Meh {}

static MEH: Meh = Meh {
    x: UnsafeCell::new(42),
};

const WRITE: () = unsafe {
    *MEH.x.get() = 12;
};


fn main() {
}
```

I expected that that should try to mutate a global, and show an error along those lines. But instead, const-checking gets in the way, even though "unleash Miri" should disable that:
```
warning: skipping const checks
  --> unleash.rs:18:6
   |
18 |     *MEH.x.get() = 12;
   |      ^^^

error[E0019]: constant contains unimplemented expression type
  --> unleash.rs:18:5
   |
18 |     *MEH.x.get() = 12;
   |     ^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0019`.
```

### PR DESCRIPTION
**Pull request by RalfJung**
IMO it is silly to unleash features that do not even have a feature gate yet, but not unleash features that do. The only thing this achieves is making unleashed mode annoying to use as we have to figure out the feature flags to enable (and not always do the error messages say what that flag is).

Given that the point of `-Z unleash-the-miri-inside-of-you` is to debug the Miri internals, I see no good reason for this extra hurdle. I cannot imagine a situation where we'd use that flag, realize the program also requires some feature gate, and then be like "oh I guess if this feature is unstable I will do something else". Instead, we'll always just add that flag to the code as well, so requiring the flag achieves nothing.

r? @oli-obk @ecstatic-morse 
Fixes https://github.com/rust-lang/rust/issues/71630

### CODE REVIEW

File: src/test/ui/consts/miri_unleashed/box.rs [hunk 1]
```diff
@@ -11,4 +11,7 @@ static TEST_BAD: &mut i32 = {
     //~^ WARN skipping const check
     //~| ERROR could not evaluate static initializer
     //~| NOTE heap allocations
+    //~| WARN skipping const checks
+    //~| WARN skipping const checks
+    //~| WARN skipping const checks
```
Comment (RalfJung) [inline src/test/ui/consts/miri_unleashed/box.rs:16]: Okay this is getting a bit ridiculous, I wonder if we can deduplicate better? Maybe use `tcx.sess.warn` without a span?

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/box.rs:16]: I think if you remove all `WARN` and `NOTE` from a test, it'll not require any, only errors are strictly required to be annotated

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/box.rs:16]: But yea, deduplicating warnings like we do lints makes sense. I don't think we should warn without spans, that'll be fairly useless, then we can just not do it at all

Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/box.rs:16]: I want the `NOTE` though to make sure the error message makes sense.

> deduplicating warnings like we do lints makes sense

How'd that work here?

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/box.rs:16]: We have https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.HandlerInner.html#structfield.emitted_diagnostics and the reason it doesn't work is because we don't do it for tests. So... you need to add `compile-flags: -Z deduplicate-diagnostics=yes` to the tests where you want to dedup errors/warnings.

**Comment by ecstatic-morse** [comment]
The goal of the current behavior is to prevent unnecessary use of `-Zunleash` in the test suite when feature gates would suffice. Requiring test writers to use feature gates when possible makes it easy to see what tests no longer need `-Zunleash` when a new feature is implemented on nightly.

Without a diagnostics bug--we were not suggesting that nightly users enable `#![feature(const_mut_refs)]` when we saw a deref of a mutable reference--the solution to the problem you encountered would have been clear. We should fix this instead.

**Comment by RalfJung** [comment]
> the solution to the problem you encountered would have been clear.

Yes, it would have been clearer.

But I still think we should not ask for feature gates with unleash-miri. Even if the compiler tells me which feature gate is missing, that's just needless hoops for me to jump through. All it achieves is annoy me as I am crafting the testcase.

> The goal of the current behavior is to prevent unnecessary use of -Zunleash in the test suite when feature gates would suffice.

I'm not a fan of that kind of nudging -- not when it has harmful effects elsewhere. The way to prevent people from unnecessarily adding the flag is to tell them during review.

>  Requiring that test writers use feature gates makes it easy to see what tests no longer need -Zunleash when a new feature is implemented on nightly.

Most (all?) unleash tests that we have should remain unleash even when we get const-checking for those features -- the point of these tests is to check the underlying engine, not to check const-qualification. So I don't buy this motivation at well, we typically do not want to remove that flag ever.

**Comment by ecstatic-morse** [comment]
This seems like a difference in values rather than a dispute over the facts. I'd rather have as many tests exercise the const-checker as possible. You would rather not have to think about it while writing `-Zunleash` tests.

The stakes here are pretty low, so I'm fine with any outcome, but I would appreciate it if you avoided `-Zunleash` going forward when it is possible to write the same test with just feature gates. Obviously this is distinct from the case in #71630.

**Comment by RalfJung** [comment]
> This seems like a difference in values rather than a dispute over the facts. I'd rather have as many tests exercise the const-checker as possible. You would rather not have to think about it while writing -Zunleash tests.

For those tests, why would you use the flag at all?
As far as I am concerned, the entire purpose to use this flag -- the only reason it even exists -- is to disable the const-checker and test the dynamic checks of the underlying motivation.

So when your goal is exercising the const-checker, shouldn't you just not use this flag?

**Comment by ecstatic-morse** [comment]
It's possible for the same test to exercise rare code paths in both the static checks and the dynamic ones. After this PR is merged, it will be possible for you to turn off the const-checker in tests you write even if const-checking could handle just fine. I ask that you don't.

**Comment by RalfJung** [comment]
@ecstatic-morse  I don't think I entirely understand which tests you do not want me to modify how -- so I will just make sure to Cc you on every change I make to miri-unleash tests. That way you can make sure I do not accidentally regress test coverage for the static checks.

I think maybe you are saying I should not add the miri-unleash flag to existing tests ("turn off the const-checker"). I will make sure to never do that, and instead duplicate the test, like what we ended up doing in https://github.com/rust-lang/rust/pull/71604. Does that work for you?

File: src/test/ui/consts/miri_unleashed/box.rs (hunk 1 above)
Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/box.rs:16]: The spans are different though, so this will not help much.

Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/box.rs:15]: Okay, one of the 4 messages for this const got removed... that's not helpful.

Maybe I can somehow use the span of the const, not the oepration inside the const, which should help deduplicate more?

Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/box.rs]: All right, the combination of using the item's span and `-Zdeduplicate-diagnostics` helps.

**Comment by ecstatic-morse** [comment]
r? @oli-obk 

If it were up to me, we wouldn't merge this. Someone else should approve.

**Comment by RalfJung** [comment]
@ecstatic-morse: @oli-obk would like us to form consensus here, and I tend to agree. So let me make another attempt at trying to understand your concern.

If I understand you correctly, you are worried that this change will reduce test coverage for the static const-eval checks. I agree that would be bad. However, I am confused about this concern: in my mind, the *entire point* of the miri-unleash flag is to *not* run the static const-eval checks. A test that sets this flag is, by definition, not meant to test anything related to the static checks. Thus I fail to understand how any change in the behavior of this flag can have bad effects on test coverage for the static checks. Maybe you have been using this flag differently?

Currently, indeed the flag dos not disable the static checks *entirely*, but it disables them mostly, to the extend that I don't think any test meant to cover the static checks can meaningfully use this flag. In particular, the checks for *all stable features* are disabled, which actually means stabilizing a feature *decreases* test coverage (they no longer get tested in "miri-unleashed" tests). I don't think that is a good situation even just from the perspective of testing the static checks. Tests for them should simply never use this flag, period.

Maybe you could give a concrete example for how one of our existing tests becomes less useful with this change, or how this change might lead to someone accidentally not testing the thing they wanted to test -- or really any example. So far, whlle I understand your concern in the abstract, I fail to understand how it relates to this PR.

**Comment by RalfJung** [comment]
> The stakes here are pretty low, so I'm fine with any outcome, but I would appreciate it if you avoided -Zunleash going forward when it is possible to write the same test with just feature gates.

This is particularly confusing to me, as the unleash tests I write are usually tests that will *never* get accepted by Miri, even when the features all become stable. The point is to write const-unsound code and make sure it gets rejected by the dynamic checks. None of the tests in "miri-unleashed" is meant to exercise the static const-checker; that should all happen in dedicated tests (and I think it does so far, and I don't think this PR is likely to change that).

Do we have a single "pass" test with "miri-unleash"? I don't think, they are all about exercising error paths in the CTFE engine that are otherwise unreachable because the static checks prevent even getting to those failures.

**Comment by RalfJung** [comment]
Or to put my confusion in one sentence: I don't understand how it make sense that miri-unleash disables the static checks that prevent non-`const fn` to be called (or any other operation that we will never permit), but does *not* disable the check that prevents `if` from being used. It allows the crazy dangerous things but disallows the "perfectly fine but not yet stable" things, which seems just nonsensical to me.

**Comment by ecstatic-morse** [comment]
> Side note: we can make sure that when a test specifies unleash, it needs to actually unleash anything in order to pass.

This is the thing I want to enforce. The goal is to prevent you or (more importantly) others from using `-Zunleash` as a replacement for `#![feature(many,different,things)]` either in-tree or downstream. I've never said that this is currently going on in-tree. If there's another way to guarantee this that you find less onerous, such as the one Oli mentioned, I'm happy to approve it.

> I'm not a fan of that kind of nudging -- not when it has harmful effects elsewhere. The way to prevent people from unnecessarily adding the flag is to tell them during review. The flag name is already scary enough to nudge people away from it.

I'm a fan of nudging. I'm sorry that you ran into a bad diagnostic, but I don't think the current behavior is "harmful". If you had encountered a scenario that couldn't be resolved just by adding a feature gate, it would be much easier to understand your desire to remove this. The automated check is currently accomplishing the goal I stated above, and I believe that things that can be automated should be: There's no need to rely on the review process.

**Comment by RalfJung** [comment]
> This is the thing I want to enforce. The goal is to prevent you or (more importantly) others from using -Zunleash as a replacement for #![feature(many,different,things)] either in-tree or downstream.

So, what about making `-Zunleash` call `delay_span_bug` when it unleashes anything, to make sure that this is only ever used to test error paths? That seems easier than what @oli-obk suggests, and should also avoid your concern?

**Comment by ecstatic-morse** [comment]
Sure. That would work. Out of curiosity, what span would you pass to `delay_span_bug`. Presumably `DUMMY_SP` would do the right thing?

**Comment by RalfJung** [comment]
Dang, that does not work... for example `assoc_const.rs` is a build-fail test that indeed *does* fail, but `delay_span_bug` is not patient enough and complains that it's not failing early enough. :/

@oli-obk is there any way around that?

**Comment by RalfJung** [comment]
Actually `read_from_static` is a run-pass Miri-unleash test (the only one, I think)... but I am not sure what it is meant to test, actually...

**Comment by oli-obk** [comment]
Hmm... curious that `delay_span_bug` doesn't work, it basically is the same thing as what I suggested (assuming there are no pass test). `delay_span_bug` should not bail out before codegen, that seems like a bug. I can look into this if you want.

**Comment by RalfJung** [comment]
Well maybe we are seeing the final error only during codegen?

> assuming there are no pass test

There is [a single pass test](https://github.com/rust-lang/rust/blob/bd0bacc694d7d8175804bb6f690cb846bfa4a9ee/src/test/ui/consts/miri_unleashed/read_from_static.rs). It was added inhttps://github.com/rust-lang/rust/pull/66606. Do you think we can remove it?

**Comment by oli-obk** [comment]
Ehm..... that run pass test is in fact what @ecstatic-morse warned us about. It also passes *without* unleash!

**Comment by oli-obk** [comment]
I'll make a PR fixing delay span bug and using it for detecting such tests

**Comment by RalfJung** [comment]
> that run pass test is in fact what @ecstatic-morse warned us about. It also passes without unleash!

Ah, good that we caught that then. :) It should not have used unleash to begin with.

File: src/librustc_mir/transform/check_consts/validation.rs [hunk 2]
```diff
@@ -248,12 +248,13 @@ impl Validator<'mir, 'tcx> {
...
-        // can be turned on with `-Zunleash-the-miri-inside-of-you`.
-        let is_unleashable = O::IS_SUPPORTED_IN_MIRI && O::feature_gate().is_none();
+        // If an operation is supported in miri it can be turned on with
+        // `-Zunleash-the-miri-inside-of-you`.
+        let is_unleashable = O::IS_SUPPORTED_IN_MIRI;
 
         if is_unleashable && self.tcx.sess.opts.debugging_opts.unleash_the_miri_inside_of_you {
-            self.tcx.sess.span_warn(span, "skipping const checks");
+            self.tcx.sess.delay_span_bug(self.span, "skipping const checks is for testing error paths only");
+            self.tcx.sess.span_warn(self.tcx.def_span(self.def_id), "skipping const checks");
```
Comment (RalfJung) [inline src/librustc_mir/transform/check_consts/validation.rs:257]: I feel like we don't need both `delay_span_bug` and `warn`; would you be okay removing the warning then?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: I'm not sure we need the `delay_span_bug` at all here. In case the test doesn't need const checks, this won't actually trigger the delay span bug, which is why `read_from_static` doesn't trigger it.

I'll let you know of my findings (working on a PR about the delay span bug thing right now)

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: We have more run-pass tests. E.g. https://github.com/rust-lang/rust/blob/8417d68de5e063426ab6bb7f383df6117d1beeed/src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.rs needs unleash in order to check something at runtime.

So we can't use delay span bug to achieve "checking that the only skips are skipping feature gates". This does in fact need a separate system.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > I'm not sure we need the delay_span_bug at all here.

This is the only place where the flag makes any behavioral difference. So if this `delay_span_bug` doesn't fire, then sure the flag is unnecessary, but it also does not disable any feature checks or so, it just does nothing.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > We have more run-pass tests

That looks more like we should just add a feature gate for `const fn` pointers, and then use that?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: > That looks more like we should just add a feature gate for const fn pointers, and then use that?

That requires nontrivial parser changes, but yes, we should.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: > This is the only place where the flag makes any behavioral difference. So if this delay_span_bug doesn't fire, then sure the flag is unnecessary, but it also does not disable any feature checks or so, it just does nothing.

Well, there are multiple `"skipping const check"` in the source, and the only thing it checks now is whether unleash tests that actually unleash something cause an error, which I don't believe is what @ecstatic-morse had in mind.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > That requires nontrivial parser changes, but yes, we should.

Well, that code clearly already works without any parser changes. So adding a feature gate just requires implementing `feaure_gate` for `FnCallIndirect`, doesn't it?

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > Well, there are multiple "skipping const check" in the source, and the only thing it checks now is whether unleash tests that actually unleash something cause an error, which I don't believe is what @ecstatic-morse had in mind.

They [said themselves](https://github.com/rust-lang/rust/pull/71631#issuecomment-622013979) that it "would work".

Your proposal of somehow detecting whether the test could work without feature gates, doesn't really match the main use-case for this flag which is to *disable all static checks* (no matter whether they are stable or unstable or whatever) so that we can test the dynamic ones. I just don't want to have to care what the static checks are saying for this code. The flag means "static checks, shut up". Your proposal means I still have to care about the static checks.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: > Well, that code clearly already works without any parser changes. So adding a feature gate just requires implementing feaure_gate for FnCallIndirect, doesn't it?

There's no way we'll ever stabilize it in a way that will work that way. Feature gates are something that is only unstable because it's baking on nightly and maybe has a few bugs or because it's a compiler internal thing needed for implementing libstd. But at least it has a tracking issue. Unleash was to me always for things that didn't have a way forward to stabilization at the time when I added the unleash path.

Otherwise we could add feature gates for everything, even `UnsafeCell` behind references in constants. I'm ok with changing the "rules" (which are vague, I admit), but we need a line somewhere that differentiates "this is unsound" from "this is unstable".

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: > They said themselves that it "would work".

From the context (copied below), I think there was some confusion about what effect that `delay_span_bug` would have.

>> we can make sure that when a test specifies unleash, it needs to actually unleash anything in order to pass.
>
> This is the thing I want to enforce. The goal is to prevent you or (more importantly) others from using `-Zunleash` as a replacement for `#![feature(many,different,things)]` either in-tree or downstream.

Comment (ecstatic-morse) [reply src/librustc_mir/transform/check_consts/validation.rs]: More concretely, I don't want people using `-Zunleash` to get around adding a [long list of feature gates](https://github.com/ecstatic-morse/const-phf/blob/1a8768ea97d297b47873b8e753779e521df21356/src/lib.rs#L1-L12) to make their test or ecosystem code work. I actually wasn't thinking about the case where tests accidentally add `-Zunleash` even when it does literally nothing. That's not really tied to my original concern, since they used all the correct feature gates. It does seem like we should warn in this case, though.

Always making `-Zunleash` cause an error prevents people from using it to avoid feature gates, since their code just won't work. FWIW, I think the status quo achieves this in a more straightforward way, but that seems to be a no-go for some reason. However, `delay_span_bug` means that we can't have `run-pass` unleash tests. I think Ralf thought there was no use case for them, but that seems to be incorrect?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs]: > More concretely, I don't want people using -Zunleash to get around adding a long list of feature gates to make their test or ecosystem code work.

I consider that a non-issue outside of rustc's test suite, as specifying `-Z` command line flags is not something to easily do outside of manually invoking nighlty `rustc`. Even if you use `RUSTFLAGS`, that will just be a mess, give you loads of `skipping const checks` warnings and the flag's documentation states that it is unsound!

> Always making -Zunleash cause an error prevents people from using it to avoid feature gates, since their code just won't work.

I don't think people are using it in practice (https://github.com/search?p=7&q=%22unleash+the+miri+inside+of+you%22&type=Code) even if https://github.com/rust-embedded/blog/blob/bfc76e942f890142c2be9edbe0d15f0c829eff39/content/2019-02-20-newsletter-15.md#L73 and https://github.com/rust-embedded/wg/blob/056080eaf325d6f81413a172f2bd635fafa39ec4/minutes/2019-02-05.irc.log#L142 seem to suggest that potentially people may use it to get around limitations without realizing it is unsound, but that's been a year ago without any usage of said flag on github.

> FWIW, I think the status quo achieves this in a more straightforward way, but that seems to be a no-go for some reason.

I believe (correct me @RalfJung if I'm misinterpreting), that the issue is that while it's certainly possible to add feature flags, it's a pointless boilerplate excercise, because for the test the stability of any features is irrelevant, it is supposed to be testing the miri-engine. Technically we could just wrap the entire const check infrastructure in a single `if unleash` check instead of doing it per gate (but that would stop giving us warnings and stuff).

Maybe a middle ground would be to replace the "skipping const checks" warning with a "skipping feature gate check for `some_feature_name`" in case it's a feature gate check? Then it would still be obvious what's going on and CI would still break for that test if something about the feature gate changes, but that breakage could be blessed away.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > without realizing it is unsound

It hopefully isn't unsound. ;)

> that the issue is that while it's certainly possible to add feature flags, it's a pointless boilerplate excercise, because for the test the stability of any features is irrelevant, it is supposed to be testing the miri-engine

That summarizes my point, yes.

I have an idea for yet another middle ground proposal that hopefully keeps all existing tests (except for the silly one) working and makes everyone happy... let's see if that works.

**Comment by RalfJung** [comment]
Okay I pushed my latest proposal: this is effectively a `delay_span_bug` (but through the `Session` like @oli-obk did to delay it properly) for whenever the miri-unleash flag is sued to get around a feature flag.

This lets me write tests that fail in CTFE without worrying about static checks (they fail anyway, so the `delay_span_bug` does not matter), but makes sure that run-pass tests properly set the feature flag.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 2 above)
Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: > Maybe a middle ground would be to replace the "skipping const checks" warning with a "skipping feature gate check for some_feature_name" in case it's a feature gate check? Then it would still be obvious what's going on and CI would still break for that test if something about the feature gate changes, but that breakage could be blessed away.

That would be fine for me, too. It might be preferable as it does not require the hacky `impl Drop for Session`.

File: src/test/ui/consts/miri_unleashed/const_refers_to_static.rs [hunk 3]
```diff
@@ -1,8 +1,8 @@
 // build-fail
-// compile-flags: -Zunleash-the-miri-inside-of-you
+// compile-flags: -Zunleash-the-miri-inside-of-you -Zdeduplicate-diagnostics
 #![allow(const_err)]
-
-#![feature(const_raw_ptr_deref)]
+#![feature(const_raw_ptr_deref)] // FIXME: cannot remove because then rustc thinks there is no error
```
Comment (RalfJung) [inline src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: This is so weird. The test passes (so rustc fails), but if I remove the flag I am hitting the new panic *and the errors are not even printed*. Do we drop the session before codegen, or so?!?

File: src/librustc_mir/transform/check_consts/validation.rs [hunk 4]
```diff
@@ -248,12 +248,15 @@ impl Validator<'mir, 'tcx> {
...
-        // If an operation is supported in miri (and is not already controlled by a feature gate) it
-        // can be turned on with `-Zunleash-the-miri-inside-of-you`.
-        let is_unleashable = O::IS_SUPPORTED_IN_MIRI && O::feature_gate().is_none();
+        // If an operation is supported in miri it can be turned on with
+        // `-Zunleash-the-miri-inside-of-you`.
+        let is_unleashable = O::IS_SUPPORTED_IN_MIRI;
 
         if is_unleashable && self.tcx.sess.opts.debugging_opts.unleash_the_miri_inside_of_you {
-            self.tcx.sess.span_warn(span, "skipping const checks");
+            self.tcx.sess.span_warn(self.tcx.def_span(self.def_id), "skipping const checks");
```
Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/validation.rs:256]: side note: what do you think about emitting the feature name that is being skipped if there is one?

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:256]: Sure... or maybe not even emit the warning in that case? Either there will be other errors or a panic at the end listing the missing gates.

Comment (oli-obk) [inline src/librustc_mir/transform/check_consts/validation.rs:256]: Why did you move to reporting on the current item instead of at the span where the const check is being skipped?

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:256]: To make deduplication work. Otherwise we still get one warning per unique span, which can be half a dozen in a 2-line const...

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:256]: I think emitting them is good, as it shows where things are being skipped. I mean, I added them on purpose so we'd be able so see exactly where a test is skipping checks, in order to notice when the checks change in any way

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:256]: Otherwise I'm worried this will kill deduplication, so we'll have 5 annotations per const again.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > in order to notice when the checks change in any way

The point of the flag is to not worry about the static checks, and focus on testing the underlying engine. Why would I care if the checks change? I explicitly *do not want* to care about that, that's why I use the flag.^^

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Well... each of these is a true skipped static check. Unless you think there's no value to them? I personally found it convenient and helpful. I mean I was actually thinking now that it could make sense to emit "skipping `op specific message` const check" so we really know what's being skipped.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: ok, so same discussion as above, let's continue there.

File: src/test/ui/consts/miri_unleashed/const_refers_to_static.rs (hunk 3 above)
Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: hmm... maybe that panic causes a double panic when dropping the fields of `Session` during unwinding?

Maybe we should report this error not via a panic in a `Session` destructor, but wherever "n previous errors" is reported, because there should be no further things happening after that.

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: I think my choice of using `Session::drop` may have been very much not thought through

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: So, while https://github.com/rust-lang/rust/blob/86c0fca44bc0b49085b177d0244bc300f6cd4655/src/librustc_interface/interface.rs#L196 is the right point in time, I don't like putting it right there

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: I don't see any other way though. So...

1. make the code from `Session::drop` a `Session::check_unleash_gates` (or choose a better name)
2. Create `Session::finish_diagnostics` which invokes the `compiler.sess.diagnostic().print_error_count(registry);` and invoke `finish_diagnostics` in https://github.com/rust-lang/rust/blob/86c0fca44bc0b49085b177d0244bc300f6cd4655/src/librustc_interface/interface.rs#L196 instead of doing the `print_error_count` directly there (I think you can get the `Registry` needed from the `Session`).
3. call `Session::check_unleash_gates` before the `print_error_count` in `finish_diagnostics`
4. Change the `panic!` to `self.err` invocation.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: For the way I am using the flag, these warnings provide negative value (i.e., they get in the way): I don't care what I am skipping, I just want to skip *all the checks* (it's called "unleash" for a reason :D ) -- and then I still have to acknowledge every skipped thing when writing UI tests, and adding all these `//~ WARN` is quite cumbersome.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: so.... how about we just emit one message at the end saying `skipped N static checks`?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Oh or even better: we collect all of the messages with their spans in a list, and report a single warning at the end and give that warning lots of labels to point the messages there. This way you only have a single warning to skip and I get all my messages in the `.stderr` file

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Where would we collect that list?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Maybe in the session variable you created? You don't need a list of feature gates anymore in that case, as you can just make it a boolean if any feature gate was skipped.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: How that? Don't I need a list of feature gates *and spans* so I can report them all?

File: src/test/ui/consts/miri_unleashed/const_refers_to_static.rs (hunk 3 above)
Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static.rs:4]: Yes that seems to work. :) Commit incoming.

File: src/librustc_mir/transform/check_consts/validation.rs (hunk 4 above)
Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: I was thinking of just stuffing the full message in there, so we can also start reporting a more detailed message for gateless checks.

Basically the error for not having feature gates in a build-pass unleash test would not contain the gate list anymore, but there'd be a separate warning in every unleash test (irrelevant of whether it uses feature gates or not or whether it compiles), and that warning would point to all skip sites.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > and that warning would point to all skip sites.

That still requires a list of spans though, not just a `bool`? (And at that point we might as well track the gates as well.)

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: @oli-obk I also do not understand whether you want these warnings to appear only in case the program otherwise builds, or always? If always, then sure we could just emit them here but writing miri-unleash UI tests would still be quite tedious. If only for "pass" tests, then... well see above, then the state needs to be stored somewhere so we can wait with emitting the warning until we know that rustc will actually succeed otherwise.

Maybe the flag should just have two values: one that emits the warning (eagerly, no extra state needed), and one that emits *no* warnings but also definitely will not let the build pass (like `delay_span_bug`, but actually delaying long enough).

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: I was trying to avoid making the flag configurable. I indeed want the warning to always occur, and don't see why writing unleash tests would be tedious from that. All you get is a big warning at the end, which I consider ok, similar to how every MIR dump contains a warning about the instability of the dump.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: But then wouldn't we have to add `//~ WARN` everywhere for every single span of the warning, to make ui tests happy?

I don't really mind the warnings to show up when I run the tests (it's noise that can hide useful information, but whatever). The annoying part is getting the ui test suite to be happy.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Also I still don't understand how "one warning at the end" could possibly be implemented with just a `bool` in the global state. I think you'll have to show some code to demonstrate that.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > But then wouldn't we have to add //~ WARN everywhere for every single span of the warning, to make ui tests happy?

No, just a single one, probably at the top of the file, as it has no span (or maybe we use the first label's span). Labels don't have any representation in `//~` syntax, they just show up in stderr.

> Also I still don't understand how "one warning with all the information emitted at the end" could possibly be implemented with just a bool in the global state. I think you'll have to show some code to demonstrate that.

I don't mean just a bool, I mean to have both a bool and a list, but you don't need the `HashSet` for dedup, you just have a single list (potentially sort it at the end), that you always use to emit the warning. The bool is just there to emit an error in case the test would have successfully compiled but never have unleashed a non-feature-gated thing.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > No, just a single one, probably at the top of the file, as it has no span (or maybe we use the first label's span). Labels don't have any representation in //~ syntax, they just show up in stderr.

I guess I don't know what "labels" vs "spans" are...

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > The bool is just there to emit an error in case the test would have successfully compiled but never have unleashed a non-feature-gated thing.

I thought we agreed in your PR that this is not the right kind of error, and instead we should error when unleashing any feature gate (like my PR does now)?

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > I thought we agreed in your PR that this is not the right kind of error, and instead we should error when unleashing any feature gate (like my PR does now)?

Sorry, we've went back and forth too many times. You're right.

Comment (oli-obk) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: > I guess I don't know what "labels" vs "spans" are...

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.DiagnosticBuilder.html#method.span_label allows you to add an arbitrary annotation to an arbitrary span. This is what gives us the `^^^^^ something here` annotations.

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: Hm... I did that, but it doesn't print the labels.
```rust
            for &(span, feature_gate) in unleashed_features.iter() {
                if let Some(feature_gate) = feature_gate {
                    diag.span_label(span, format!("skipping check for `{}` feature", feature_gate));
                } else {
                    diag.span_label(span, "skipping check that does not even have a feature gate");
                }
            }
            diag.emit();
```
becomes just
```
warning: skipping const checks
```

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs:257]: I tried passing a proper span to `struct_warn`, no luck.

Our diagnostics APIs are quite hard to use correctly, it seems. :/

Comment (RalfJung) [reply src/librustc_mir/transform/check_consts/validation.rs]: I went for `span_help` now, that seems to work. It's quite the hack though...

File: src/test/ui/consts/miri_unleashed/box.rs [hunk 5]
```diff
@@ -1,5 +1,5 @@
-// compile-flags: -Zunleash-the-miri-inside-of-you
-#![feature(const_mut_refs, box_syntax)]
+// compile-flags: -Zunleash-the-miri-inside-of-you -Zdeduplicate-diagnostics
```
Comment (oli-obk) [inline src/test/ui/consts/miri_unleashed/box.rs:1]: the deduplication isn't necessary anymore, right?

File: src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs [hunk 6]
```diff
@@ -2,7 +2,7 @@
 // aux-build:static_cross_crate.rs
 #![allow(const_err)]
 
-#![feature(exclusive_range_pattern, half_open_range_patterns, const_if_match, const_panic)]
+#![feature(exclusive_range_pattern, half_open_range_patterns, const_if_match)]
```
Comment (oli-obk) [inline src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs:5]: `const_if_match` can also be removed here

Comment (oli-obk) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs:5]: ah no, that's a HIR check

Comment (RalfJung) [reply src/test/ui/consts/miri_unleashed/const_refers_to_static_cross_crate.rs:5]: Yeah...

File: src/test/ui/consts/const-points-to-static.rs [hunk 7]
```diff
@@ -3,8 +3,9 @@
 #![allow(dead_code)]
 
 const TEST: &u8 = &MY_STATIC;
-//~^ skipping const checks
-//~| it is undefined behavior to use this value
+//~^ ERROR it is undefined behavior to use this value
+//~| NOTE  encountered a reference pointing to a static variable
```
Comment (RalfJung) [inline src/test/ui/consts/const-points-to-static.rs:7]: Another curious thing about diagnostic UI tests: looks like `NOTE` annotations match what the rustc API calls "labels". Do they also match what the rustc API calls "note"?
