### PR TITLE
More reductions in error handling diversity

### LINKED ISSUE #67933: #[deny(warnings) isn't working on E0170
This code compiles without errors:

```rust
#![allow(unused_variables)]
#![allow(non_snake_case)]
#![allow(unreachable_patterns)]
#![allow(dead_code)]
#![deny(warnings)]

enum Foo {
    Bar,
    Baz,
}

fn fn1(e: Foo) {
    match e {
        Bar => {},
        Baz => {},
    }
}

fn main() {}
```

With the following output:

```
Compiling playground v0.0.1 (/playground)
warning[E0170]: pattern binding `Bar` is named the same as one of the variants of the type `Foo`
  --> src/main.rs:14:9
   |
14 |         Bar => {},
   |         ^^^ help: to match on the variant, qualify the path: `Foo::Bar`

warning[E0170]: pattern binding `Baz` is named the same as one of the variants of the type `Foo`
  --> src/main.rs:16:9
   |
16 |         Baz => {},
   |         ^^^ help: to match on the variant, qualify the path: `Foo::Baz`

    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/playground`
```

However, the `#[deny(warnings)]` should make it fail.

### PR DESCRIPTION
**Pull request by Centril**
In this follow up to https://github.com/rust-lang/rust/pull/67744, we:

- Remove all fatal / error / warning macros in `syntax` except for `struct_span_err`, which is moved to `rustc_errors`.

- Lintify some hard-coded warnings which used warning macros.

- Defatalize some errors.

In general, the goal here is to make it painful to use fatal or unstructured errors and so we hopefully won't see many of these creep in.

Fixes https://github.com/rust-lang/rust/issues/67933.

### CODE REVIEW

File: src/librustc_typeck/structured_errors.rs [hunk 1]
```diff
@@ -50,8 +50,7 @@ impl<'tcx> StructuredDiagnostic<'tcx> for VariadicError<'tcx> {
     }
 
     fn code(&self) -> DiagnosticId {
-        syntax::diagnostic_used!(E0617);
-        DiagnosticId::Error("E0617".to_owned())
+        syntax::stringify_error_code!(E0617)
```
Comment (Mark-Simulacrum) [inline src/librustc_typeck/structured_errors.rs]: If we're touching most of these locations, would it be worth also moving to (loosely speaking) `rustc_errors::error_code!(...)`? Maybe out of scope for this PR. I'm also not a fan of the `stringify_` naming, as that's an implementation detail IMO.

File: src/librustc_typeck/check/mod.rs [hunk 2]
```diff
@@ -155,6 +155,17 @@ use self::method::{MethodCallee, SelfSource};
 pub use self::Expectation::*;
 use self::TupleArgumentsFlag::*;
 
+#[macro_export]
```
Comment (Mark-Simulacrum) [inline src/librustc_typeck/check/mod.rs]: I think we can drop the `macro_export` here if we place this above the `mod` declarations (might already be the case), would be nice to avoid letting other crates use it perhaps? Not sure.

**Review by Mark-Simulacrum — COMMENTED** [review]
Some of my comments I think get obsoleted by future commits, but along with them, two higher-level comments:

* no real point to moving span_err and friends to struct_span_err(...).emit()
* it is not clear that removing the macros, rather than (e.g.) moving to rustc_errors is helpful

I'm also not super happy with moving things to lints in this PR; feels like maybe there's some discussion to be had, and it's not clear that it brings us benefits from the PR goals perspective. Maybe we could split those commits out? I don't know if we need (e.g.) sign off or so. Seems like probably no, and indeed moving to lints is good.

Would also be good to do some rebase magic and cleanup commits (a few are misspelled or essential duplicates of each other, e.g., I would roll in all the "unused" macro removal into the ~last commit which removes the syntax::diagnostics::macros module.

File: src/librustc_metadata/locator.rs [hunk 3]
```diff
@@ -1039,15 +1038,14 @@ pub fn find_plugin_registrar(
     };
 
     if target_only {
-        // Need to abort before syntax expansion.
```
[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_metadata/locator.rs]: We removed the syntax plugin support. :)

File: src/librustc_typeck/structured_errors.rs (hunk 1 above)
Comment (Centril) [reply src/librustc_typeck/structured_errors.rs]: Renamed. :)

File: src/test/ui/lint/lint-uppercase-variables.stderr [hunk 4]
```diff
@@ -49,4 +51,3 @@ LL |         Foo => {}
 
 error: aborting due to 4 previous errors
 
-For more information about this error, try `rustc --explain E0170`.
```
[the remark this answers is not in the document]
Comment (Centril) [reply src/test/ui/lint/lint-uppercase-variables.stderr]: Readded the error codes. :)

File: src/librustc_typeck/check/mod.rs (hunk 2 above)
Comment (Centril) [reply src/librustc_typeck/check/mod.rs]: It didn't work :(

**Comment by Centril** [comment]
(For the benefit of everyone reading, here's a summary of notes I left on Discord...)

> * no real point to moving span_err and friends to struct_span_err(...).emit()

The point is to encourage adding `.span_suggestion(...)`, `.span_label(...)` and whatnot by not immediately emitting the error ("the right thing should be more convenient"). Eventually we can maybe rename to `error!(...).emit();` once diversity is further reduced.

> it is not clear that removing the macros, rather than (e.g.) moving to rustc_errors is helpful

I think we should make it harder to emit unstructured / fatal errors as well as hard-coded warnings, and those macros are in the way of that. Also, the diagnostics builder API is good enough that `help!(...)` et. al feels unnecessary.

> I'm also not super happy with moving things to lints in this PR; feels like maybe there's some discussion to be had, and it's not clear that it brings us benefits from the PR goals perspective. Maybe we could split those commits out? I don't know if we need (e.g.) sign off or so. Seems like probably no, and indeed moving to lints is good.

So lintifying these enabled nixing some of the macros. Beyond that, hard-coded warnings are not something we want outside of things like the NLL transition (which are super rare and don't deserve sugar).

> Would also be good to do some rebase magic and cleanup commits (a few are misspelled or essential duplicates of each other, e.g., I would roll in all the "unused" macro removal into the ~last commit which removes the syntax::diagnostics::macros module.

Squashed all into one commit. :)

**Comment by Mark-Simulacrum** [comment]
Changes look fine to me overall; probably makes sense to wait for @petrochenkov here though.

File: src/librustc/hir/check_attr.rs [hunk 5]
```diff
@@ -428,21 +431,29 @@ impl CheckAttrVisitor<'tcx> {
...
+            )
+            .emit();
         }
         // Warn on repr(u8, u16), repr(C, simd), and c-like-enum-repr(C, u8)
         if (int_reprs > 1)
             || (is_simd && is_c)
             || (int_reprs == 1 && is_c && item.map_or(false, |item| is_c_like_enum(item)))
         {
-            let hint_spans: Vec<_> = hint_spans.collect();
-            span_warn!(self.tcx.sess, hint_spans, E0566, "conflicting representation hints");
```
Comment (petrochenkov) [inline src/librustc/hir/check_attr.rs]: I suspect this was made a warning rather than an error for backward compatibility.
So it's rather a deprecation lint than a linty lint (or perhaps it can be made an error right away).

File: src/librustc/lint/builtin.rs [hunk 6]
```diff
@@ -95,6 +95,18 @@ declare_lint! {
     "detects overlapping patterns"
 }
 
+declare_lint! {
+    pub BINDING_VARIANT_NAME,
```
Comment (petrochenkov) [inline src/librustc/lint/builtin.rs]: This does look like a linty lint, but it doesn't match the [lint naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#lints).

File: src/librustc/hir/check_attr.rs (hunk 5 above)
Comment (Centril) [reply src/librustc/hir/check_attr.rs]: The warning was introduced in https://github.com/rust-lang/rust/pull/34623. I got the sense that it was deliberate as "not going to become an error" but I could be wrong.

**Comment by petrochenkov** [comment]
>Eventually we can maybe rename to `error!(...).emit();`

+1, if the errors are spanned and structural by default, then it doesn't make sense to write `struct_span`.

File: src/librustc_errors/diagnostic_builder.rs [hunk 7]
```diff
@@ -385,3 +385,22 @@ impl<'a> Drop for DiagnosticBuilder<'a> {
...
+            &format!($($message)*),
+            $crate::error_code!($code),
+        )
+    })
+}
+
+#[macro_export]
+macro_rules! error_code {
+    ($code:ident) => {{
+        let _ = $code;
```
[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc_errors/diagnostic_builder.rs]: It's one of my goals to remove this (mainly for incremental benefits and possibly internationalization as a stretch goal), but I wanted to leave it for a follow-up since there might be objections. As I understand it, we want to both catch unused error codes (I believe tidy does this) and used unregistered error codes (tidy doesn't catch this).

File: src/librustc/lint/builtin.rs (hunk 6 above)
Comment (Centril) [reply src/librustc/lint/builtin.rs]: Hmm... I went back and forth on some names but wasn't aware of the conventions. Would "allow `binding_with_variant_name`" work"? (it's a bit long though...)

**Comment by petrochenkov** [comment]
We also probably need a variation of `struct_span_err` without an error code though, errors with codes are not an overwhelming majority right now, unlike e.g. spanned errors.
(But that kind of depends on the decision about error codes in general.)

**Comment by Centril** [comment]
The variant without a code is just `self.struct_span_err(...)` (not a macro) though? (It works well enough the parser... At least I've never wanted for more.)

File: src/librustc/lint/builtin.rs (hunk 6 above)
Comment (petrochenkov) [reply src/librustc/lint/builtin.rs]: `binding` -> `bindings`

>it's a bit long though...

I doubt people will have to write it often.

Comment (Centril) [reply src/librustc/lint/builtin.rs]: Ah, cool. `bindings_with_variant_name` it is then. :)

**Comment by petrochenkov** [comment]
@Centril 
You have to write `&format!(...)` with `self.struct_span_err`, which is kind of annoying.

File: src/librustc/hir/check_attr.rs (hunk 5 above)
Comment (petrochenkov) [reply src/librustc/hir/check_attr.rs]: https://github.com/rust-lang/rust/pull/34623 started as an error (https://github.com/rust-lang/rust/pull/34623#issuecomment-230188553) and things like `repr(u8, u16)` can never work as stated, so it never makes sense to `allow` this lint long term, so it looks like a deprecation lint to me.

File: src/librustc_errors/diagnostic_builder.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (petrochenkov) [reply src/librustc_errors/diagnostic_builder.rs]: Ah, if tidy still makes the check, then let's leave it.

File: src/librustc/hir/check_attr.rs (hunk 5 above)
Comment (Centril) [reply src/librustc/hir/check_attr.rs]: Ah, that makes sense. I'll go make it an error and we can find out whether 4 years later, anyone still depends on it in the beta crater runs...?

Comment (Centril) [reply src/librustc/hir/check_attr.rs]: Fixed.

File: src/librustc/lint/builtin.rs (hunk 6 above)
Comment (Centril) [reply src/librustc/lint/builtin.rs]: Fixed.

**Comment by Centril** [comment]
Review comments should be addressed now (except for the new variation on the macro, which I think could be done some other time).

**Comment by Centril** [comment]
Yay; CI is finally happy 🎉

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/67846#issuecomment-570738528, @bors r-

(Needs rebase due to test changes.)

**Comment by petrochenkov** [comment]
That's some weird rustbuild failure.
cc @Mark-Simulacrum

**Comment by Centril** [comment]
Let's find out if this is spurious, @bors retry rollup=never

**Comment by Centril** [comment]
Verified the problem locally & fixed it.

**Comment by Centril** [comment]
And rebased; @bors r=petrochenkov
