### PR TITLE
Be a bit more careful around exotic cycles in in the inliner

### LINKED ISSUE #143700: cycle detected when optimizing MIR
Only under `--release`, after https://github.com/rust-lang/rust/pull/142625 https://github.com/EFanZh/ast-demangle no longer builds with a cycle error during inline evaluation. Default `--debug` builds do not hit this.

### Code

https://github.com/EFanZh/ast-demangle (as of commit b4b0d5d, which is current HEAD)

I expected to see this happen: pass

Instead, this happened: cycle error

```
error[E0391]: cycle detected when optimizing MIR for `rust_v0::<impl at src/rust_v0/mod.rs:60:32: 60:41>::eq`
   --> src/rust_v0/mod.rs:60:32
    |
60  | #[derive(Clone, Eq, Hash, Ord, PartialEq, PartialOrd)]
    |                                ^^^^^^^^^
    |
note: ...which requires optimizing MIR for `rust_v0::<impl at src/rust_v0/mod.rs:210:39: 210:48>::eq`...
   --> src/rust_v0/mod.rs:210:39
    |
210 | #[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    |                                       ^^^^^^^^^
    = note: ...which again requires optimizing MIR for `rust_v0::<impl at src/rust_v0/mod.rs:60:32: 60:41>::eq`, completing the cycle
note: cycle used when optimizing MIR for `rust_v0::<impl at src/rust_v0/mod.rs:15:39: 15:48>::eq`
   --> src/rust_v0/mod.rs:15:39
    |
15  | #[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    |                                       ^^^^^^^^^
    = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

### Version it worked on

Before https://github.com/rust-lang/rust/pull/142625

### Version with regression

https://github.com/rust-lang/rust/pull/142625

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_errors/src/lib.rs:1838:17:
aborting due to `-Z treat-err-as-bug=1`
stack backtrace:
   0:     0x71ada4175aa3 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h4b84b18f52d871f7
   1:     0x71ada4802c7f - core::fmt::write::hddeac91703b6499d
   2:     0x71ada416b5d3 - std::io::Write::write_fmt::h28f31377e98688f6
   3:     0x71ada4175902 - std::sys::backtrace::BacktraceLock::print::h52d0fd2be6990145
   4:     0x71ada417939a - std::panicking::default_hook::{{closure}}::h77b4c5e7cec39435
   5:     0x71ada4178f1f - std::panicking::default_hook::h61df2e12d1f260cf
   6:     0x71ada3223d33 - std[c539802e89e8d81a]::panicking::update_hook::<alloc[247485d20f619618]::boxed::Box<rustc_driver_impl[3a492dd9a06cbf2d]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x71ada4179beb - std::panicking::rust_panic_with_hook::h2deddd251118f4d3
   8:     0x71ada41798b6 - std::panicking::begin_panic_handler::{{closure}}::h5fe965e188abe62f
   9:     0x71ada4175f69 - std::sys::backtrace::__rust_end_short_backtrace::h0f72bacaad7bd6db
  10:     0x71ada41795cd - __rustc[38c938b2c9dd7d5c]::rust_begin_unwind
  11:     0x71ada08ba720 - core::panicking::panic_fmt::h80892ba21db80006
  12:     0x71ada3274037 - <rustc_errors[793135f862eb652b]::DiagCtxtInner>::panic_if_treat_err_as_bug
  13:     0x71ada5d31e88 - <rustc_errors[793135f862eb652b]::DiagCtxtInner>::emit_diagnostic::{closure#3}
  14:     0x71ada5d2f98d - rustc_interface[b327675518afe1b5]::callbacks::track_diagnostic::<core[cdc97c9c0b6fd462]::option::Option<rustc_span[dd9d35b931de6930]::ErrorGuaranteed>>::{closure#0}
  15:     0x71ada5d2f32b - rustc_interface[b327675518afe1b5]::callbacks::track_diagnostic::<core[cdc97c9c0b6fd462]::option::Option<rustc_span[dd9d35b931de6930]::ErrorGuaranteed>>
  16:     0x71ada5d2e93d - <rustc_errors[793135f862eb652b]::DiagCtxtInner>::emit_diagnostic
  17:     0x71ada5d2e7ff - <rustc_errors[793135f862eb652b]::DiagCtxtHandle>::emit_diagnostic
  18:     0x71ada0fdc5d0 - <rustc_span[dd9d35b931de6930]::ErrorGuaranteed as rustc_errors[793135f862eb652b]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  19:     0x71ada3b9bf8c - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::mk_cycle::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefaultCache<rustc_type_ir[4c29bc3dc42f1408]::predicate::TraitRef<rustc_middle[5796165e46beff11]::ty::context::TyCtxt>, rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt>
  20:     0x71ada3b82859 - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::cycle_error::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefIdCache<rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt>
  21:     0x71ada483849a - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::try_execute_query::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefIdCache<rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt, false>
  22:     0x71ada483711b - rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  23:     0x71ada1a5e420 - <rustc_middle[5796165e46beff11]::ty::context::TyCtxt>::instance_mir
  24:     0x71ada542e9f5 - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  25:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  26:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  27:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  28:     0x71ada547e3fd - <rustc_mir_transform[b3fbc0bf8a9d046a]::inline::Inline as rustc_mir_transform[b3fbc0bf8a9d046a]::pass_manager::MirPass>::run_pass
  29:     0x71ada4810158 - rustc_mir_transform[b3fbc0bf8a9d046a]::run_optimization_passes
  30:     0x71ada51f90a0 - rustc_mir_transform[b3fbc0bf8a9d046a]::optimized_mir
  31:     0x71ada51f8875 - rustc_query_impl[3a213cbfc7e81906]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>
  32:     0x71ada4837c25 - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::try_execute_query::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefIdCache<rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt, false>
  33:     0x71ada483711b - rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  34:     0x71ada1a5e420 - <rustc_middle[5796165e46beff11]::ty::context::TyCtxt>::instance_mir
  35:     0x71ada542e9f5 - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  36:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  37:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  38:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  39:     0x71ada547e3fd - <rustc_mir_transform[b3fbc0bf8a9d046a]::inline::Inline as rustc_mir_transform[b3fbc0bf8a9d046a]::pass_manager::MirPass>::run_pass
  40:     0x71ada4810158 - rustc_mir_transform[b3fbc0bf8a9d046a]::run_optimization_passes
  41:     0x71ada51f90a0 - rustc_mir_transform[b3fbc0bf8a9d046a]::optimized_mir
  42:     0x71ada51f8875 - rustc_query_impl[3a213cbfc7e81906]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>
  43:     0x71ada4837c25 - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::try_execute_query::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefIdCache<rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt, false>
  44:     0x71ada483711b - rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  45:     0x71ada1a5e420 - <rustc_middle[5796165e46beff11]::ty::context::TyCtxt>::instance_mir
  46:     0x71ada542e9f5 - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  47:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  48:     0x71ada542d83f - rustc_mir_transform[b3fbc0bf8a9d046a]::inline::process_blocks::<rustc_mir_transform[b3fbc0bf8a9d046a]::inline::NormalInliner>
  49:     0x71ada547e3fd - <rustc_mir_transform[b3fbc0bf8a9d046a]::inline::Inline as rustc_mir_transform[b3fbc0bf8a9d046a]::pass_manager::MirPass>::run_pass
  50:     0x71ada4810158 - rustc_mir_transform[b3fbc0bf8a9d046a]::run_optimization_passes
  51:     0x71ada51f90a0 - rustc_mir_transform[b3fbc0bf8a9d046a]::optimized_mir
  52:     0x71ada51f8875 - rustc_query_impl[3a213cbfc7e81906]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>
  53:     0x71ada4837c25 - rustc_query_system[8d89d55943c1ebd2]::query::plumbing::try_execute_query::<rustc_query_impl[3a213cbfc7e81906]::DynamicConfig<rustc_query_system[8d89d55943c1ebd2]::query::caches::DefIdCache<rustc_middle[5796165e46beff11]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[3a213cbfc7e81906]::plumbing::QueryCtxt, false>
  54:     0x71ada483711b - rustc_query_impl[3a213cbfc7e81906]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  55:     0x71ada534af1d - <rustc_metadata[e2b15c2c3f6f00d0]::rmeta::encoder::EncodeContext>::encode_crate_root
  56:     0x71ada5c7d5f0 - <rustc_metadata[e2b15c2c3f6f00d0]::rmeta::encoder::encode_metadata::{closure#3} as core[cdc97c9c0b6fd462]::ops::function::FnOnce<(rustc_middle[5796165e46beff11]::ty::context::TyCtxt, &std[c539802e89e8d81a]::path::Path)>>::call_once
  57:     0x71ada5c7a830 - rustc_metadata[e2b15c2c3f6f00d0]::rmeta::encoder::encode_metadata
  58:     0x71ada575ff98 - rustc_metadata[e2b15c2c3f6f00d0]::fs::encode_and_write_metadata
  59:     0x71ada5b0b68a - <rustc_interface[b327675518afe1b5]::queries::Linker>::codegen_and_build_linker
  60:     0x71ada5b091c7 - rustc_interface[b327675518afe1b5]::passes::create_and_enter_global_ctxt::<core[cdc97c9c0b6fd462]::option::Option<rustc_interface[b327675518afe1b5]::queries::Linker>, rustc_driver_impl[3a492dd9a06cbf2d]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  61:     0x71ada5aed6e4 - rustc_interface[b327675518afe1b5]::interface::run_compiler::<(), rustc_driver_impl[3a492dd9a06cbf2d]::run_compiler::{closure#0}>::{closure#1}
  62:     0x71ada59d29f8 - std[c539802e89e8d81a]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[b327675518afe1b5]::util::run_in_thread_with_globals<rustc_interface[b327675518afe1b5]::util::run_in_thread_pool_with_globals<rustc_interface[b327675518afe1b5]::interface::run_compiler<(), rustc_driver_impl[3a492dd9a06cbf2d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  63:     0x71ada59d26d6 - <<std[c539802e89e8d81a]::thread::Builder>::spawn_unchecked_<rustc_interface[b327675518afe1b5]::util::run_in_thread_with_globals<rustc_interface[b327675518afe1b5]::util::run_in_thread_pool_with_globals<rustc_interface[b327675518afe1b5]::interface::run_compiler<(), rustc_driver_impl[3a492dd9a06cbf2d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[cdc97c9c0b6fd462]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  64:     0x71ada59d0cfd - std::sys::pal::unix::thread::Thread::new::thread_start::h7f3d8f76868ca167
  65:     0x71ad9f29caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  66:     0x71ad9f329c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  67:                0x0 - <unknown>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
Copied from the comment here: https://github.com/rust-lang/rust/issues/143700#issuecomment-3053810353

---

```rust
#![feature(fn_traits)]

#[inline]
pub fn a() {
    FnOnce::call_once(a, ());
    FnOnce::call_once(b, ());
}

#[inline]
pub fn b() {
    FnOnce::call_once(b, ());
    FnOnce::call_once(a, ());
}
```

This should demonstrate the issue. For ease of discussion, I'm gonna call the two fn-def types `{a}` and `{b}`.

When collecting the cyclic local callees in `mir_callgraph_cyclic` for `a`, we first check the first call terminator in `a`. We end up calling process on `<{a} as FnOnce>::call_once`, which ends up visiting `a`'s instance again. This is cyclical. However, we don't end up marking `FnOnce::call_once` as a cyclical def id because it's a foreign item. That's fine.

When visiting the second call terminator in `a`, which is `<{b} as FnOnce>::call_once`, we end up recursing into `b`. We check the first terminator, which is `<{b} as FnOnce>::call_once`, but although that is its own mini cycle, it doesn't consider itself a cycle for the purpose of this query because it doesn't involve the *root*. However, when we visit the *second* terminator in `b`, which is `<{a} as FnOnce>::call_once`, we end up **erroneously** *not* considering that call to be cyclical since we've already inserted it into our set of seen instances, and as a consequence we don't recurse into it. This means that we never collect `b` as recursive.

Do this in the flipped case too, and we end up having two functions which mututally do not consider each other to be recursive participants. This leads to a query cycle.

---

I ended up also renaming some variables so I could more clearly understand their responsibilities in this code. Let me know if the renames are not welcome.

Fixes https://github.com/rust-lang/rust/issues/143700
r? @cjgillot

### CODE REVIEW

File: compiler/rustc_mir_transform/src/inline/cycle.rs [hunk 1]
```diff
@@ -64,15 +64,15 @@ fn process<'tcx>(
...
     target: LocalDefId,
-    seen: &mut FxHashSet<ty::Instance<'tcx>>,
+    seen: &mut FxHashMap<ty::Instance<'tcx>, bool>,
     involved: &mut FxHashSet<LocalDefId>,
     recursion_limiter: &mut FxHashMap<DefId, usize>,
     recursion_limit: Limit,
 ) -> bool {
     trace!(%caller);
-    let mut cycle_found = false;
+    let mut reaches_root = false;
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/inline/cycle.rs:73]: This is more like "may reach root" given that we bail out with a possibly false-positive when hitting the recursion limit, but that was a mouthful.

File: compiler/rustc_mir_transform/src/inline/cycle.rs [hunk 2]
```diff
@@ -64,15 +64,15 @@ fn process<'tcx>(
...
 
-    for &(callee, args) in tcx.mir_inliner_callees(caller.def) {
+    for &(callee_def_id, args) in tcx.mir_inliner_callees(caller.def) {
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/inline/cycle.rs:75]: with the name `callee`, `DefId` ends up shadowing `Instance` ends up shadowing `DefId` again 😆

File: compiler/rustc_mir_transform/src/inline/cycle.rs [hunk 3]
```diff
@@ -101,10 +104,17 @@ fn process<'tcx>(
...
 
-        if seen.insert(callee) {
+        let callee_reaches_root = if let Some(&c) = seen.get(&callee) {
+            // Even if we have seen this callee before, and thus don't need
+            // to recurse into it, we still need to propagate whether it reaches
+            // the root so that we can mark all the involved callers, in case we
+            // end up reaching that same recursive callee through some *other* cycle.
+            c
+        } else {
+            seen.insert(callee, false);
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/inline/cycle.rs:114]: I think it's safe to consider this to be `false` initially.

File: compiler/rustc_mir_transform/src/inline/cycle.rs [hunk 4]
```diff
@@ -81,14 +81,17 @@ fn process<'tcx>(
...
+            trace!(?callee_def_id, "cannot resolve, skipping");
             continue;
         };
 
         // Found a path.
         if callee.def_id() == target.to_def_id() {
-            cycle_found = true;
+            reaches_root = true;
+            seen.insert(callee, true);
+            continue;
```
Comment (compiler-errors) [inline compiler/rustc_mir_transform/src/inline/cycle.rs:94]: I don't think it's necessary to recurse on callees here, so I just `continue`d.

File: tests/mir-opt/inline_double_cycle.b.Inline.panic-unwind.diff [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
++     scope 1 (inlined <fn() {b} as FnOnce<()>>::call_once - shim(fn() {b})) {
++     }
++     scope 2 (inlined <fn() {a} as FnOnce<()>>::call_once - shim(fn() {a})) {
++     }
+  
+      bb0: {
+          StorageLive(_1);
+          StorageLive(_2);
+          _2 = ();
+-         _1 = <fn() {b} as FnOnce<()>>::call_once(b, move _2) -> [return: bb1, unwind continue];
```
Comment (compiler-errors) [inline tests/mir-opt/inline_double_cycle.b.Inline.panic-unwind.diff:21]: It's nice to see we didn't break inlining at least for the `FnOnce` call. It's kind of a shame we can't inline `a` into `b` or vice versa, but it's obviously not clear which one to inline into the other without adding arbitrary ordering which is bad.

**Review by estebank — APPROVED** [review]

**Comment by cjgillot** [comment]
Thanks a lot for fixing this!
@bors r+

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/143866#issuecomment-3066715616

**Comment by matthiaskrgr** [comment]
@bors r- rollup=iffy

https://github.com/rust-lang/rust/pull/144110#issuecomment-3089375388

**Comment by compiler-errors** [comment]
Apologies. I just forgot to stage some files, so this doesn't need to stay iffy. There are now staged files for both abort and unwind cases.

@bors r=cjgillot rollup=maybe
