### PR TITLE
Document std limitations before/after main

### LINKED ISSUE #110708: Consider documenting that (parts of?) stdlib must not be used before/after main
All existing standard library documentation implicitly assumes that the APIs are being used between the start of a Rust `main` and end of `main`.

For example [`std::thread::current`](https://doc.rust-lang.org/1.69.0/std/thread/fn.current.html) does not document any indication that the function would panic. **It does not need to document that**, because the function _cannot_ panic, as long as the call occurs within the duration of `main`.

However it's possible to observe a panic like this:

```rust
extern "C" fn get_thread() {
    let _ = std::panic::catch_unwind(std::thread::current);
}

fn main() {
    unsafe { libc::atexit(get_thread) };
}
```

```console
thread '<unnamed>' panicked at 'use of std::thread::current() is not possible after the thread's local data has been destroyed', library/std/src/thread/mod.rs:733:5
stack backtrace:
   5: core::option::Option<T>::expect
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/option.rs:741:21
   6: std::thread::current
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:733:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  11: std::panic::catch_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  12: playground::get_thread
             at ./[src/main.rs:2](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021#):13
  14: exit
  15: __libc_start_main
  16: _start
```

(Related PR and discussion: https://github.com/rust-lang/rust/pull/107216)

In general using the standard library from an `atexit` callback, or before `main` through a static constructor, is UB: according to https://github.com/rust-lang/rust/pull/107216#issuecomment-1400038633 _"we can't really guarantee anything specific happens [...]; at least not in a cross-platform way."_

Is this worth calling out centrally as a caveat to all other documentation of the standard library? At the top level of the whole `std` crate (it would perhaps be more prominent than it deserves), at the module level, or in the Reference? Certainly for `std::thread`, `std::io`, `std::fs`, the expectation users need to have is that nothing in there will work outside of `main`.

Are there APIs it makes sense to carve out as being permissible outside of `main`? Stuff like `Cell`, `ManuallyDrop`, `MaybeUninit`, `NonNull`, etc. We'd maybe need to do research into how constructors and atexit are being used in the wild. For example the `inventory` crate relies on `AtomicPtr`, `UnsafeCell`, and `Option` to be usable before `main`: https://github.com/dtolnay/inventory/blob/508cb5918640d05414b0c49843d1c26088df6713/src/lib.rs#L191. It seems obvious that those things should work but there isn't documentation which guarantees it. I assume that makes the `inventory` crate technically unsound as written.

### PR DESCRIPTION
**Pull request by the8472**
Solves #110708

### CODE REVIEW

File: library/std/src/lib.rs [hunk 1]
```diff
@@ -152,6 +152,31 @@
...
+//! On the other hand `core` and `alloc` are most likely to work in such environments with
+//! the caveat that any hookable behavior such as panics, oom handling or allocators will also
+//! depend on the compatibility of the hooks.
+//!
+//! Some features may also behave differently outside main, e.g. stdio could become unbuffered,
+//! some panics might turn into aborts, backtraces might not get symbolicated or similar.
+//!
+//! Non-exhaustive list of known limitations:
+//!
+//! - after-main use of thread-locals, which also affects additional features:
```
Comment (Amanieu) [inline library/std/src/lib.rs:173]: It's not just after main that these can cause issues, they may panic during TLS destruction when any thread is exiting.

Comment (the8472) [reply library/std/src/lib.rs:173]: Sure, but this section (and the filed issue it is trying to address) is about before/after main, not about non-main-thread lifecycles.

We could generalize it to "outside std-managed lifecycle scopes" or some similar mouthful?

Comment (Amanieu) [reply library/std/src/lib.rs:173]: I just think this one sentence could be generalized to apply to TLS destruction in general, not just when exiting the main thread.

**Review by dtolnay — APPROVED** [review]
I agree with Amanieu's comment that there is room to be more informative about non-main-thread limitations too, but let's land this since it does address #110708 already, and take further details in followup PRs.

Thanks!
