### PR TITLE
Sort "implementations on foreign types" section in the sidebar

### LINKED ISSUE #71926: The list of impl on the left of rust docs are in the wrong order
This can easily be seen here: https://docs.rs/diesel/1.4.4/diesel/deserialize/trait.FromSqlRow.html

The impl for the biggest tuple is at the top of the list but at the bottom of the page.

CC @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #71926.

We were sorting by the ID instead of sorting by the name. They're not in the same order as the implementations but I think it makes more sense this way considering this is what we do for the methods as well.

r? @kinnison 

cc @rust-lang/rustdoc

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
This appears to do as intended.  Is there a need to add a test to ensure things remain sorted?  is there anything else whose sort ordering needs tweaking?  If the answer to those two points is "no" then I'm okay for this to be merged r=kinnison

File: src/librustdoc/html/render.rs [hunk 1]
```diff
@@ -4345,19 +4345,21 @@ fn sidebar_trait(buf: &mut Buffer, it: &clean::Item, t: &clean::Trait) {
             .iter()
             .filter(|i| i.inner_impl().for_.def_id().map_or(false, |d| !c.paths.contains_key(&d)))
             .filter_map(|i| match extract_for_impl_name(&i.impl_item) {
-                Some((ref name, ref id)) => {
-                    Some(format!("<a href=\"#{}\">{}</a>", id, Escape(name)))
-                }
+                Some((name, id)) => Some((id, name)),
```
Comment (ollie27) [inline src/librustdoc/html/render.rs:4348]: Do we really need to swap the order in this tuple? In fact if we leave it as `(name, id)` then we can continue to just use `res.sort();` below.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs:4348]: I didn't pay attention, good catch!

**Comment by GuillaumeGomez** [comment]
@kinnison For the tests, it's in progress but in another [PR](https://github.com/rust-lang/rust/pull/70533) (and it might take a while...).

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/html/render.rs [hunk 2]
```diff
@@ -4345,19 +4345,21 @@ fn sidebar_trait(buf: &mut Buffer, it: &clean::Item, t: &clean::Trait) {
             .iter()
             .filter(|i| i.inner_impl().for_.def_id().map_or(false, |d| !c.paths.contains_key(&d)))
             .filter_map(|i| match extract_for_impl_name(&i.impl_item) {
-                Some((ref name, ref id)) => {
-                    Some(format!("<a href=\"#{}\">{}</a>", id, Escape(name)))
-                }
+                Some((name, id)) => Some((name, id)),
```
Comment (kinnison) [inline src/librustdoc/html/render.rs:4348]: Is this actually doing anything any more?

Comment (GuillaumeGomez) [reply src/librustdoc/html/render.rs:4348]: No you're right, I can completely remove the `match`. Thanks!

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by kinnison — APPROVED** [review]
Assuming green CI, I'm r+ on this @ollie27 ?
