### PR TITLE
Properly handle `async` block and `async fn` in `if` exprs without `else`

### LINKED ISSUE #115405: ^^^^^^^ expected `()`, found `Result<ServiceResponse<B>, _>` ???   not related not informative ..
### Code

```Rust
//main.rs
use actix_web::{get,web,http,Result,App,HttpServer,HttpRequest, Responder, HttpResponse};
use serde::{Deserialize,Serialize};
use actix_cors::Cors;

mod heartbeat;

static PORT :u16 = 9091;

#[get("/")]
async fn index()->impl Responder {
    
    HttpResponse::Ok().body("template")
}

 

#[derive(Serialize)]
pub struct Response {
    pub message: String,
}

async fn not_found() ->Result<HttpResponse> {
    let response = Response {
        message: "Resource not found".to_string(),
    };
    Ok(HttpResponse::NotFound().json(response))
}


#[actix_web::main]
async fn main()-> std::io::Result<()> {
    std::env::set_var("RUST_LOG", "debug");
    env_logger::init();
    HttpServer::new(|| App::new()
    .wrap(
        Cors::default()
            .allowed_origin("http://*") // Allow all http origins
            .allowed_origin("https://*") // Allow all https origins
            .allowed_methods(vec!["GET","POST","PUT","DELETE","OPTIONS"])
            .allowed_headers(vec![http::header::AUTHORIZATION,http::header::CONTENT_TYPE,
                http::header::ACCEPT,http::header::LINK])
            .allowed_header("X-CSRF-TOKEN")
            .supports_credentials()
            .max_age(300)
    )
    .wrap(heartbeat::Heartbeat)
    .service(index)
    .service(web::resource("/ping"))
    .default_service(web::route().to(not_found)))
    .bind(("127.0.0.1",PORT))?
    .run()
    .await        
}


//heartbeat.rs

use std::future::{ready, Ready};

use actix_http::header::{HeaderValue, HeaderName};
use actix_web::{
    dev::{self, Service, ServiceRequest, ServiceResponse, Transform},
    Error,http::Method
};
use futures_util::future::LocalBoxFuture;
//use crate::constants;

pub struct Heartbeat;

impl<S, B> Transform<S, ServiceRequest> for Heartbeat
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Response = ServiceResponse<B>;
    type Error = Error;
    type InitError = ();
    type Transform = HeartMiddleware<S>;
    type Future = Ready<Result<Self::Transform, Self::InitError>>;

    fn new_transform(&self, service: S) -> Self::Future {
        ready(Ok(HeartMiddleware { service }))
    }
}

pub struct HeartMiddleware<S> {
    service: S,
}


impl<S, B> Service<ServiceRequest> for HeartMiddleware<S>
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Response = ServiceResponse<B>;
    type Error = Error;
    type Future = LocalBoxFuture<'static, Result<Self::Response, Self::Error>>;

    dev::forward_ready!(service);

    fn call(&self, req: ServiceRequest) -> Self::Future {
        

        let fut = self.service.call(req);
        
        

        Box::pin(async move {
            
            let mut res = fut.await?;
            let headers = res.headers_mut();
            headers.insert(
                 HeaderName::from_static("Content-Type"), HeaderValue::from_static("text/plain")
             );
            
            if (Method::POST == req.method() || 
                 Method::GET  == req.method()  ||
                 Method::HEAD == req.method()) && req.path() == "/ping" {
                 Ok(res)
            }
             
            Err(actix_web::error::ErrorImATeapot("Tea"))
        })
    }
}
```

### Current output

```Shell
cargo build
   Compiling broker-service v0.1.0 (C:\dev\my\rust\workspace\broker-service)
warning: unused import: `HttpRequest`
 --> src\main.rs:1:52
  |
1 | use actix_web::{get,web,http,Result,App,HttpServer,HttpRequest, Responder, HttpResponse};
  |                                                    ^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Deserialize`
 --> src\main.rs:2:13
  |
2 | use serde::{Deserialize,Serialize};
  |             ^^^^^^^^^^^

error[E0308]: mismatched types
  --> src\heartbeat.rs:65:18  
   |
62 | /             if (Method::POST == req.method() ||
63 | |                  Method::GET  == req.method()  ||
64 | |                  Method::HEAD == req.method()) && req.path() == "/ping" {
65 | |                  Ok(res)
   | |                  ^^^^^^^ expected `()`, found `Result<ServiceResponse<B>, _>`
66 | |             }
   | |_____________- expected this to be `()`
   |
   = note: expected unit type `()`
                   found enum `Result<ServiceResponse<B>, _>`
note: return type inferred to be `()` here
  --> src\heartbeat.rs:56:27
   |
56 |             let mut res = fut.await?;
   |                           ^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
warning: `broker-service` (bin "broker-service") generated 2 warnings
error: could not compile `broker-service` (bin "broker-service") due to previous error; 2 warnings emitted
```

### Desired output

```Shell
the real Cause for the error 
what is :
^^^^^^^ expected `()`, found `Result<ServiceResponse<B>, _>` ???
```

### Rationale and extra context

using letest actix-web

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by estebank**
When encountering a tail expression in the then arm of an `if` expression without an `else` arm, account for `async fn` and `async` blocks to suggest `return`ing the value and pointing at the return type of the `async fn`.

We now also account for AFIT when looking for the return type to point at.

Fix #115405.

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -1037,33 +1040,82 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                        }
+                    }
+                    if let hir::ExprKind::Block(hir::Block { expr: Some(expr), .. }, _) = expr.kind
+                    {
+                        if let Some(ty) = self.typeck_results.borrow().node_type_opt(expr.hir_id) {
+                            rets.push(ty);
+                        }
+                    }
                 }
+                rets.into_iter().all(|ty| self.can_coerce(found, ty))
```
Comment (estebank) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1102]: @compiler-errors poor-man's time-traveling type inference 😬

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 2]
```diff
@@ -1037,33 +1040,82 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                let ty = self.normalize(expr.span, ty);
+                self.can_coerce(found, ty)
+            }
+            hir::FnRetTy::DefaultReturn(_) if in_closure => {
+                let mut rets = vec![];
+                if let Some(ret_coercion) = self.ret_coercion.as_ref() {
+                    let ret_ty = ret_coercion.borrow().expected_ty();
+                    rets.push(ret_ty);
+                }
+                let mut visitor = CollectRetsVisitor { ret_exprs: vec![] };
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: Why do you need to do this? If the `ret_coercion` has a type, then it will have already been coerced with all of these `ret_exprs` collected below.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: Like, the whole point of `ret_coercion` is to be the type that all of the `return` expressions in the body are coerced into

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: `ret_coercion` is (always?) an inference type.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: It's not always an inference type. It may *appear* to be an inference type if you print it without calling `resolve_vars_if_possible` on it (which you don't need to do here), but it gets equated with another type as soon as the first `return` statement is type checked, and `can_coerce` will handle it properly below.

Applying this diff makes no changes to the UI:
```diff
diff --git a/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs b/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs
index afe5d0d4880..0a03429b37f 100644
--- a/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs
+++ b/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs
@@ -1,6 +1,5 @@
 use super::FnCtxt;
 
-use crate::coercion::CollectRetsVisitor;
 use crate::errors;
 use crate::fluent_generated as fluent;
 use crate::fn_ctxt::rustc_span::BytePos;
@@ -17,7 +16,6 @@
 use rustc_hir as hir;
 use rustc_hir::def::Res;
 use rustc_hir::def::{CtorKind, CtorOf, DefKind};
-use rustc_hir::intravisit::{Map, Visitor};
 use rustc_hir::lang_items::LangItem;
 use rustc_hir::{
     CoroutineDesugaring, CoroutineKind, CoroutineSource, Expr, ExprKind, GenericBound, HirId, Node,
@@ -1082,23 +1080,6 @@ pub(in super::super) fn suggest_missing_break_or_return_expr(
                     let ret_ty = ret_coercion.borrow().expected_ty();
                     rets.push(ret_ty);
                 }
-                let mut visitor = CollectRetsVisitor { ret_exprs: vec![] };
-                if let Some(item) = self.tcx.hir().find(id)
-                    && let Node::Expr(expr) = item
-                {
-                    visitor.visit_expr(expr);
-                    for expr in visitor.ret_exprs {
-                        if let Some(ty) = self.typeck_results.borrow().node_type_opt(expr.hir_id) {
-                            rets.push(ty);
-                        }
-                    }
-                    if let hir::ExprKind::Block(hir::Block { expr: Some(expr), .. }, _) = expr.kind
-                    {
-                        if let Some(ty) = self.typeck_results.borrow().node_type_opt(expr.hir_id) {
-                            rets.push(ty);
-                        }
-                    }
-                }
                 rets.into_iter().all(|ty| self.can_coerce(found, ty))
             }
             _ => false,
```

Unless I am mistaken, pls remove the `CollectRetsVisitor` usage (and the changes to it).

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: For the record, that diff is to just demonstrate that it works without the usage of `CollectRetsVisitor `. The code should be simplified into a single `can_coerce` call.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: Actually, I think none of your tests aren't actually exercising this behavior of a previous return statement having constrained the `ret_coercion`?

Anyways, you should also be using `.merged_ty()` from the `ret_coercion` instead of `.expected_ty()`, but you still shouldn't need to look at any of the `node_ty`s of the return expressions. You should write a test that exercises that the lint will *not* be made if the type is incompatible with other returns.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: I wanted to avoid an incorrect suggestion in the face of

```rust
pub fn baz() -> Pin<Box<dyn Future<Output = Result<S, ()>> + 'static>> {
    Box::pin(async move {
        if true {
            Some(S) //~ ERROR mismatched types
        }
        Err(())
    })
}
```

Now, looking into it, not only the logic is now wrong (after doing some changes cleaning up for publication), but the type for the returning expressions isn't actually available. For some reason, I *had* gotten a value for them, but now with the code as is now. Given that, yes, the entire visitor thing is useless and can be removed. I was hoping to avoid nonsensical suggestions like the one above, but oh well.

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:1085]: Keeping around a single can_coerce call for the `ret_coercion.expected_ty()` should avoid such a nonsensical suggestion, at least according to local testing.

File: compiler/rustc_hir_typeck/src/coercion.rs [hunk 3]
```diff
@@ -92,14 +92,16 @@ impl<'a, 'tcx> Deref for Coerce<'a, 'tcx> {
 
 type CoerceResult<'tcx> = InferResult<'tcx, (Vec<Adjustment<'tcx>>, Ty<'tcx>)>;
 
-struct CollectRetsVisitor<'tcx> {
-    ret_exprs: Vec<&'tcx hir::Expr<'tcx>>,
+pub struct CollectRetsVisitor<'tcx> {
```
Comment (compiler-errors) [inline compiler/rustc_hir_typeck/src/coercion.rs:95]: this isn't needed

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: I think I know why I had something that seemed to be working earlier. I tried using `check_expr` at some point, which "worked", but trying it again now it does cause multiple issues that make it more of a pain in the neck than we want to deal with.

File: compiler/rustc_hir_typeck/src/coercion.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/coercion.rs]: Done.

Comment (estebank) [reply compiler/rustc_hir_typeck/src/coercion.rs]: Oh, shit, had in flight changes... let me clean up the mess first.

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs [hunk 4]
```diff
@@ -955,14 +955,35 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                    kind: hir::ItemKind::Fn(ref sig, ..),
-                    owner_id,
-                    ..
-                })) = self.tcx.hir().find_parent(hir_id) =>
-            {
+            Node::Expr(&hir::Expr {
+                hir_id,
+                kind:
+                    hir::ExprKind::Closure(hir::Closure {
+                        kind: hir::ClosureKind::Coroutine(..), ..
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:962]: this is now only handling coroutines, not other closrues anymore. If this is actually intended, the documentation on `get_node_fn_decl` needs to be adjusted.

**Review by oli-obk — CHANGES_REQUESTED** [review]

File: compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs (hunk 4 above)
Comment (estebank) [reply compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs:962]: As discussed yesterday, the docstring *used* to be wrong, now the behavior matches the description.

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
@bor@ r+

**Comment by oli-obk** [comment]
> @bor@ r+

uhm... mobile keyboard failure

r=me after rebase

@rustbot author
