### PR TITLE
Port `#[crate_name]` to the new attribute parsing infrastructure

### LINKED ISSUE #137687: ICE: ` expr in place where literal is expected (builtin attr parsing)`
auto-reduced (treereduce-rust):
````rust
//@compile-flags: --crate-type=lib
#[crate_name = concat!("Cloneb")]

macro_rules! inline {
    () => {};
}

````

original:
````rust
#[crate_name = concat!("Cloneb")]
macro_rules! mac {
    ($ident:ident) => { let $ident = 42; }
}

#[macro_export]
macro_rules! inline {
    () => ()
}

````

Version information
````
rustc 1.87.0-nightly (ac91805f3 2025-02-26)
binary: rustc
commit-hash: ac91805f3179fc2225c60e8ccf5a1daa09d43f3d
commit-date: 2025-02-26
host: x86_64-unknown-linux-gnu
release: 1.87.0-nightly
LLVM version: 20.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused macro definition: `inline`
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:3:14
  |
3 | macro_rules! inline {
  |              ^^^^^^
  |
  = note: `#[warn(unused_macros)]` on by default

warning: crate-level attribute should be an inner attribute: add an exclamation mark: `#![foo]`
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:1:1
  |
1 | #[crate_name = concat!("Cloneb")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_attributes)]` on by default

warning: 2 warnings emitted

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: expr in place where literal is expected (builtin attr parsing)
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:1:14
  |
1 | #[crate_name = concat!("Cloneb")]
  |              ^
  |
note: delayed at compiler/rustc_attr_parsing/src/parser.rs:359:24
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
         4: <rustc_attr_parsing::parser::MetaItemParser>::from_attr
         5: <rustc_resolve::def_collector::DefCollector as rustc_ast::visit::Visitor>::visit_item
         6: <rustc_resolve::def_collector::DefCollector as rustc_ast::visit::Visitor>::visit_crate
         7: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
         8: <rustc_expand::expand::MacroExpander>::collect_invocations
         9: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
        10: <rustc_expand::expand::MacroExpander>::expand_crate
        11: rustc_interface::passes::resolver_for_lowering_raw
        12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        13: <rustc_query_impl::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        15: rustc_query_impl::query_impl::resolver_for_lowering_raw::get_query_non_incr::__rust_end_short_backtrace
        16: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        17: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        18: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        19: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        20: std::sys::pal::unix::thread::Thread::new::thread_start
        21: <unknown>
        22: <unknown>
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:1:14
  |
1 | #[crate_name = concat!("Cloneb")]
  |              ^

error: internal compiler error: expr in place where literal is expected (builtin attr parsing)
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:1:1
  |
1 | #[crate_name = concat!("Cloneb")]
  | ^^^^^^^^^^^^^^
  |
note: delayed at /rustc/ac91805f3179fc2225c60e8ccf5a1daa09d43f3d/compiler/rustc_attr_parsing/src/context.rs:336:43
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_errors::DiagCtxtHandle>::span_delayed_bug::<rustc_span::span_encoding::Span, &str>
         4: <rustc_resolve::def_collector::DefCollector as rustc_ast::visit::Visitor>::visit_item
         5: <rustc_resolve::def_collector::DefCollector as rustc_ast::visit::Visitor>::visit_crate
         6: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
         7: <rustc_expand::expand::MacroExpander>::collect_invocations
         8: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
         9: <rustc_expand::expand::MacroExpander>::expand_crate
        10: rustc_interface::passes::resolver_for_lowering_raw
        11: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
        12: <rustc_query_impl::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 16]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        14: rustc_query_impl::query_impl::resolver_for_lowering_raw::get_query_non_incr::__rust_end_short_backtrace
        15: rustc_interface::passes::create_and_enter_global_ctxt::<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
        16: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
        17: std::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
        18: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        19: std::sys::pal::unix::thread::Thread::new::thread_start
        20: <unknown>
        21: <unknown>
 --> /tmp/icemaker_global_tempdir.o4pBxOKZHwPg/rustc_testrunner_tmpdir_reporting.DGIJGRHWWShI/mvce.rs:1:1
  |
1 | #[crate_name = concat!("Cloneb")]
  | ^^^^^^^^^^^^^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.87.0-nightly (ac91805f3 2025-02-26) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z dump-mir-dir=dir

query stack during panic:
end of query stack

```

</p>
</details>

### PR DESCRIPTION
**Pull request by jdonszelmann**
r? @fmease 

Closes rust-lang/rust#137687

### CODE REVIEW

**Comment by jdonszelmann** [comment]
ugh, I made a mistake, gimme one sec

File: compiler/rustc_driver_impl/src/lib.rs [hunk 1]
```diff
@@ -667,11 +669,13 @@ fn print_crate_info(
                     return Compilation::Continue;
                 };
                 let t_outputs = rustc_interface::util::build_output_filenames(attrs, sess);
-                let crate_name = passes::get_crate_name(sess, attrs);
```
[the remark this answers is not in the document]
Comment (jdonszelmann) [reply compiler/rustc_driver_impl/src/lib.rs:670]: because I'm dumb and removed it completely first and then blindly reinserted it. let me fix

File: compiler/rustc_driver_impl/src/lib.rs [hunk 2]
```diff
@@ -667,7 +668,8 @@ fn print_crate_info(
...
+                let crate_name = get_crate_name(sess, attrs);
```
Comment (bjorn3) [inline compiler/rustc_driver_impl/src/lib.rs:671]: I believe all changes to this file can be reverted now. It only changes a `passes::get_crate_name` to `get_crate_name` + import of `passes::get_crate_name`.

Comment (jdonszelmann) [reply compiler/rustc_driver_impl/src/lib.rs]: mhm, you're right

**Review by fmease — APPROVED** [review]

File: compiler/rustc_attr_data_structures/src/attributes.rs [hunk 3]
```diff
@@ -175,6 +175,11 @@ pub enum AttributeKind {
         span: Span,
     },
     ConstStabilityIndirect,
+    CrateName {
+        name: Symbol,
+        name_span: Span,
```
[the remark this answers is not in the document]
Comment (jdonszelmann) [reply compiler/rustc_attr_data_structures/src/attributes.rs]: hmm, I'm not sure that makes it that much better but if you really want it I'm fine with it. Other attrs sometimes have more than 1 span related and then it's nice to distinguish them by name but here it's possible

File: compiler/rustc_attr_parsing/src/attributes/crate_name.rs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+use super::SingleAttributeParser;
+use crate::context::AcceptContext;
+use crate::parser::ArgParser;
+use crate::session_diagnostics::{ExpectedNameValue, IncorrectMetaItem, UnusedMultiple};
+
+pub(crate) struct CratenameParser;
+
+impl SingleAttributeParser for CratenameParser {
+    const PATH: &'static [Symbol] = &[sym::crate_name];
```
[the remark this answers is not in the document]
Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/attributes/crate_name.rs]: fair enough, d'ya mind if I remove that for all attr parsers in another PR? they'll all have this

**Comment by jdonszelmann** [comment]
@fmease and I decided to delay this PR for a bit until more diagnostic infra for attrs lands (hopefully next week) to make the duplicate error a warning to be consistent with current master.

**Comment by wesleywiser** [comment]
Hi @jdonszelmann and @fmease, #137687 has reached beta so it would be great if we could resolve that via a beta-backport of this PR. Do you think it's possible to resolve the review feedback and merge this PR in the next week or so?

I can probably pitch in to help if necessary 🙂

**Comment by wesleywiser** [comment]
Just to clarify, will this PR then depend on the attribute diagnostics work? (Is that #138164?)

Generally, for backports, we try to keep the backport as small as possible so if this PR can be made to work independently of that PR (possibly even with a degraded diagnostics experience), that would be highly preferred.

**Comment by jdonszelmann** [comment]
No. We decided to delay this because it's relatively low prio and any nice and permanent solution for this depends on that. I'll make a temp fix that at least doesn't ice separately then, that sounds better for now. I don't mind doing it, I know the problem now and then I also know how to fix it permanently later. You'll hear from me

**Comment by theemathas** [comment]
Note that #137687 actually has two separate problems:
1. A problem (lower priority) involving the `#[crate_name]` attribute.
2. A problem (higher priority, found in a crater run) involving user-defined macro_rules and derive macros.

This PR only appears to address the first problem. The second problem would probably need to have a separate fix.

**Comment by jdonszelmann** [comment]
ok this is weird, I've copied just the tests over to master to fix it in a temporary way

**Comment by jieyouxu** [comment]
(I know I've said this in the other PR too, but just in case)

Just a heads up: I split #137687 into two issues:

- #137687 is used to track Matthias's fuzzed regression (the `#[crate_name = concat!("Cloneb")]` one).
- #140612 is used to track the crater regressions (known to affect user macros)

**Comment by jdonszelmann** [comment]
@fmease finally got around to this one. The 2nd commit introduces lints for early-parsed attributes which was something that was unsupported earlier simply because no attribute needed it until now. The warning/error is unfortunately emitted twice now which is hard to fix in this PR. We simply call a very long chain of functions twice, and expect the first time to emit errors and the 2nd not. It's hard to distinguish these cases, and in some cases when we try to get metadata from rustc we only actually trigger the chain once so it's hard to even define in which call to emit errors. I left a todo for it.

File: compiler/rustc_hir/src/attrs/encode_cross_crate.rs [hunk 5]
```diff
@@ -7,12 +7,16 @@ pub enum EncodeCrossCrate {
...
+    ///
+    /// If this is "Yes", then another crate can do `tcx.get_all_attrs(did)` for a did in this crate, and get the attribute.
+    /// When this is No, the attribute is filtered out while encoding and other crate won't be able to observe it.
+    /// This can be unexpectedly good for performance, so unless necessary for cross-crate compilation, prefer No.
     pub fn encode_cross_crate(&self) -> EncodeCrossCrate {
         use AttributeKind::*;
         use EncodeCrossCrate::*;
 
         match self {
-            // tidy-alphabetical-start
```
Comment (fmease) [inline compiler/rustc_hir/src/attrs/encode_cross_crate.rs]: Why remove tidy-alphabetical-* and the "Needed for rustdoc" comments?

File: compiler/rustc_interface/src/passes.rs [hunk 6]
```diff
@@ -1125,6 +1127,28 @@ fn run_required_analyses(tcx: TyCtxt<'_>) {
     }
 }
 
+pub(crate) fn parse_crate_name(
```
Comment (fmease) [inline compiler/rustc_interface/src/passes.rs]: Could you maybe move it below the `fn get_crate_name`? It feels a bit misplaced between `fn run_required_analyses` and `fn analysis`.

File: compiler/rustc_interface/src/util.rs [hunk 7]
```diff
@@ -519,11 +521,10 @@ pub fn build_output_filenames(attrs: &[ast::Attribute], sess: &Session) -> Outpu
...
 
-    let crate_name = sess
-        .opts
-        .crate_name
-        .clone()
-        .or_else(|| rustc_attr_parsing::find_crate_name(attrs).map(|n| n.to_string()));
+    let crate_name =
+        sess.opts.crate_name.clone().or_else(|| {
+            parse_crate_name(sess, attrs, ShouldEmit::Nothing).map(|i| i.0.to_string())
+        });
```
Comment (fmease) [inline compiler/rustc_interface/src/util.rs:527]: (I've already mentioned this is the past but I plan on getting rid of this (re)parsing here eventually once I've figured out some nuances; see https://github.com/fmease/rust/pull/22/commits/e688f5e3d1ce7430b466730cd5859493899b1f25)

File: compiler/rustc_lint/src/early/diagnostics.rs [hunk 8]
```diff
@@ -468,5 +470,15 @@ pub fn decorate_builtin_lint(
         BuiltinLintDiag::UnexpectedBuiltinCfg { cfg, cfg_name, controlled_by } => {
             lints::UnexpectedBuiltinCfg { cfg, cfg_name, controlled_by }.decorate_lint(diag)
         }
+        BuiltinLintDiag::AttributeLint(attr) => {
+            emit_attribute_lint_kind(&attr, DiagEmitter(diag));
```
Comment (fmease) [inline compiler/rustc_lint/src/early/diagnostics.rs]: The word `emit` here is misleading I feel like, this function is effectively not emitting, it's only decorating. Welp, to be fair, fns like `emit_node_span_lint` also don't emit necessarily (depending on fn `lint_level`'s decision).

Er, but I see that it's like that because `emit_attribute_lint_kind` / `SimpleLintEmitter` is there to abstract over / generalize `emit_node_span_lint` and `decorate_lint`. Not sure what else to call all of these "`LitEmitter`"-related items tho atm :shrug:

File: tests/ui/attributes/malformed-attrs.stderr [hunk 9]
```diff
@@ -369,6 +363,12 @@ LL - #[used()]
 LL + #[used]
    |
 
+error[E0539]: malformed `crate_name` attribute input
+  --> $DIR/malformed-attrs.rs:71:1
+   |
+LL | #[crate_name]
+   | ^^^^^^^^^^^^^ help: must be of the form: `#[crate_name = "name"]`
```
Comment (fmease) [inline tests/ui/attributes/malformed-attrs.stderr:477]: (will be `` must be of the form: `#![crate_name = "name"]` `` (extra `!`) after #145238 (future conflict))

File: tests/ui/invalid-compile-flags/print-crate-name-request-malformed-crate-name.stdout [hunk 10]
```diff
@@ -0,0 +1 @@
+print_crate_name_request_malformed_crate_name
```
Comment (fmease) [inline tests/ui/invalid-compile-flags/print-crate-name-request-malformed-crate-name.stdout]: Ah, interesting ^^. This'll lead to some interesting output in the terminal where stdout & stderr are typically merged.

Ideally we shouldn't emit this (wrong) crate name … but it's probably unavoidable rn since the new attr parsing APIs don't return a `Result<_, _>`?

File: compiler/rustc_attr_parsing/src/context.rs [hunk 11]
```diff
@@ -689,22 +695,48 @@ impl<'sess> AttributeParser<'sess, Early> {
...
         };
         let mut parsed = p.parse_attribute_list(
             attrs,
             target_span,
             target_node_id,
             OmitDoc::Skip,
             std::convert::identity,
-            |_lint| {
-                panic!("can't emit lints here for now (nothing uses this atm)");
+            |AttributeLint { id, span, kind }| {
```
Comment (fmease) [inline compiler/rustc_attr_parsing/src/context.rs]: (Since I lack a bigger picture of the new attr parsing APIs) Is it desirable that `parse_limited{,_should_emit}` default to lint buffering by default? Shouldn't the caller decide that (via a callback)?


For example, what happens if someone calls one of these functions in a later compiler stage when all buffered lints "have been emitted already"? Can that even happen or are buffered lints only emitted when the session is destroyed (I don't know much about this logic of `buffer_lint`)?

**Review by fmease — APPROVED** [review]
I have some nits and questions but generally :+1:, thanks!

File: compiler/rustc_middle/src/ty/context.rs [hunk 12]
```diff
@@ -1417,15 +1418,24 @@ pub struct TyCtxt<'tcx> {
     gcx: &'tcx GlobalCtxt<'tcx>,
 }
 
+pub struct Simple<'tcx>(TyCtxt<'tcx>, &'static Lint, HirId, MultiSpan);
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/context.rs]: "`Simple`" and "`SimpleLintEmitter`" are quite nondescript and confusing to be totally honest. Could you rename this maybe? Not entirely sure what to call of these "things". Maybe `Simple` → `LintEmission`?? hmm >.<

(cc the naming problem of the `emit_*` & `decorate_*` abstraction I mentioned in an earlier review comment)

File: compiler/rustc_hir/src/attrs/encode_cross_crate.rs (hunk 5 above)
Comment (jdonszelmann) [reply compiler/rustc_hir/src/attrs/encode_cross_crate.rs]: seems accidental, my bad

File: tests/ui/attributes/malformed-attrs.stderr (hunk 9 above)
Comment (jdonszelmann) [reply tests/ui/attributes/malformed-attrs.stderr:477]: I think it's after this one https://github.com/rust-lang/rust/pull/145243 but ye

File: compiler/rustc_middle/src/ty/context.rs (hunk 12 above)
Comment (jdonszelmann) [reply compiler/rustc_middle/src/ty/context.rs]: renamed some things, should be much better now

File: tests/ui/invalid-compile-flags/print-crate-name-request-malformed-crate-name.stdout (hunk 10 above)
Comment (jdonszelmann) [reply tests/ui/invalid-compile-flags/print-crate-name-request-malformed-crate-name.stdout]: hmm, yea if the attr can't be parsed it's as if the crate name wasn't set at all. Hard to change since that's usually the behavior we want, i.e. give an error, ignore it, and continue

File: compiler/rustc_attr_parsing/src/context.rs (hunk 11 above)
Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/context.rs]: that can't really happen

Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/context.rs]: in later compiler stages you don't have ast::Attribute's anymore to parse since they're all parsed during lowering. This is just for the few cases where we want to parse earlier. The only way this could go wrong in is *during* rustc_ast_lowering where you do still have ast attributes but have already emitted all lints. However, this is also the place where we do all existing attr parsing already in the right way. It's hard to mess that up there.

File: compiler/rustc_lint_defs/Cargo.toml [hunk 13]
```diff
@@ -9,7 +9,7 @@ rustc_abi = { path = "../rustc_abi" }
 rustc_ast = { path = "../rustc_ast" }
 rustc_data_structures = { path = "../rustc_data_structures" }
 rustc_error_messages = { path = "../rustc_error_messages" }
-rustc_hir_id = { path = "../rustc_hir_id" }
```
Comment (fmease) [inline compiler/rustc_lint_defs/Cargo.toml]: Partially undoes https://github.com/rust-lang/rust/pull/145390 but I guess that's unavoidable (we'd need to move `DefPathHash` and `AttributeLintKind` to `rustc_hir_id` to be able to revert that which wouldn't make sense). https://github.com/rust-lang/rust/pull/145390 was simply "overfitting" you could say.

File: compiler/rustc_attr_parsing/src/attributes/crate_level.rs [hunk 14]
```diff
@@ -0,0 +1,34 @@
...
+    fn convert(cx: &mut AcceptContext<'_, '_, S>, args: &ArgParser<'_>) -> Option<AttributeKind> {
+        let ArgParser::NameValue(n) = args else {
+            cx.expected_name_value(cx.attr_span, None);
+            return None;
+        };
+
+        let Some(name) = n.value_as_str() else {
+            cx.expected_string_literal(n.value_span, Some(n.value_as_lit()));
+            return None;
+        };
```
Comment (fmease) [inline compiler/rustc_attr_parsing/src/attributes/crate_level.rs:24]: Does this regress `#[crate_name = concat!("x")] fn f() {}`? I guess it won't because `concat!` is already expanded by then?

File: compiler/rustc_errors/src/lib.rs
Comment (fmease) [inline compiler/rustc_errors/src/lib.rs:1]: As discussed, `AttributeLintDecoratorOrEmitter`, `decorate_or_emit`, etc. would be more accurate.

Or going vague, `AttributeLintHandler`, `fn handle`, `DeferredAttributeLintHandler`, `type Handler: …;`.

But if you feel it's too churny to go rename them again, it's okay to leave it.

File: compiler/rustc_interface/src/passes.rs [hunk 15]
```diff
@@ -1244,8 +1246,7 @@ pub fn get_crate_name(sess: &Session, krate_attrs: &[ast::Attribute]) -> Symbol
     // in all code paths that require the crate name very early on, namely before
     // macro expansion.
 
-    let attr_crate_name =
-        validate_and_find_value_str_builtin_attr(sym::crate_name, sess, krate_attrs);
```
Comment (fmease) [inline compiler/rustc_interface/src/passes.rs:1248]: (once we port `#[recursion_limit]`, we can get rid of `validate_and_find_value_str_builtin_attr`)

File: compiler/rustc_lint/src/early/diagnostics.rs [hunk 16]
```diff
@@ -478,5 +480,15 @@ pub fn decorate_builtin_lint(
         BuiltinLintDiag::UnexpectedBuiltinCfg { cfg, cfg_name, controlled_by } => {
             lints::UnexpectedBuiltinCfg { cfg, cfg_name, controlled_by }.decorate_lint(diag)
         }
+        BuiltinLintDiag::AttributeLint(attr) => {
+            decorate_attribute_lint_kind(&attr, DiagEmitter(diag));
+        }
+    }
+}
+
+struct DiagEmitter<'a, 'b>(&'a mut Diag<'b, ()>);
```
Comment (fmease) [inline compiler/rustc_lint/src/early/diagnostics.rs]:
```suggestion
struct DiagDecorator<'a, 'b>(&'a mut Diag<'b, ()>);
```

File: compiler/rustc_middle/src/ty/context.rs [hunk 17]
```diff
@@ -1417,15 +1418,24 @@ pub struct TyCtxt<'tcx> {
     gcx: &'tcx GlobalCtxt<'tcx>,
 }
 
-impl<'tcx> LintEmitter for TyCtxt<'tcx> {
-    fn emit_node_span_lint(
+pub struct Decorator<'tcx>(TyCtxt<'tcx>, &'static Lint, HirId, MultiSpan);
```
Comment (fmease) [inline compiler/rustc_middle/src/ty/context.rs]:
```suggestion
pub struct Emitter<'tcx>(TyCtxt<'tcx>, &'static Lint, HirId, MultiSpan);
```

File: compiler/rustc_passes/src/check_attr.rs [hunk 18]
```diff
@@ -367,22 +368,49 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
             let builtin = attr.ident().and_then(|ident| BUILTIN_ATTRIBUTE_MAP.get(&ident.name));
 
             if hir_id != CRATE_HIR_ID {
-                if let Some(BuiltinAttribute { type_: AttributeType::CrateLevel, .. }) =
-                    attr.ident().and_then(|ident| BUILTIN_ATTRIBUTE_MAP.get(&ident.name))
-                {
-                    match style {
-                        Some(ast::AttrStyle::Outer) => self.tcx.emit_node_span_lint(
+                match attr {
+                    // FIXME(jdonszelmann) after https://github.com/rust-lang/rust/pull/145085 merges, move to attribute parsing
```
Comment (fmease) [inline compiler/rustc_passes/src/check_attr.rs]: (#145085 has been merged)

File: tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.stderr [hunk 19]
```diff
@@ -233,10 +233,10 @@ LL | #[windows_subsystem = "windows"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
 warning: crate-level attribute should be an inner attribute: add an exclamation mark: `#![foo]`
-  --> $DIR/issue-43106-gating-of-builtin-attrs.rs:782:1
+  --> $DIR/issue-43106-gating-of-builtin-attrs.rs:782:16
    |
 LL | #[crate_name = "0900"]
-   | ^^^^^^^^^^^^^^^^^^^^^^
+   |                ^^^^^^
```
Comment (fmease) [inline tests/ui/feature-gates/issue-43106-gating-of-builtin-attrs.stderr]: Wait, the highlight should span the entire attribute; the problem isn't with the string literal (contrary to diagnostics like `crate name must not be empty` or `` `--crate-name` and `#[crate_name]` are required to match ``)

File: compiler/rustc_interface/src/passes.rs [hunk 20]
```diff
@@ -1244,8 +1246,7 @@ pub fn get_crate_name(sess: &Session, krate_attrs: &[ast::Attribute]) -> Symbol
...
+    let attr_crate_name = parse_crate_name(sess, krate_attrs, ShouldEmit::ErrorsAndLints);
```
Comment (fmease) [inline compiler/rustc_interface/src/passes.rs]: Could you please make this raise a FatalError on parse error to address https://github.com/rust-lang/rust/pull/137729/files#r2267446182 or add a `FIXME(fmease): Exit fatally on parse error.` so I can do so as a follow-up?

**Review by fmease — APPROVED** [review]
Some small comments. r=me with nits addressed in one way or another

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/137729/57e620e56b718abaf47f18e1e20a3cc3480b258b..e8dac5dfede0c83a9e83456a4f0e8fd4b13e435c)*

File: tests/ui/lint/unused/unused-attr-duplicate.rs
Comment (fmease) [inline tests/ui/lint/unused/unused-attr-duplicate.rs:1]: (random file)

Did this PR actually add a regression test for #137687? Did I miss it

File: compiler/rustc_lint_defs/Cargo.toml (hunk 13 above)
Comment (jdonszelmann) [reply compiler/rustc_lint_defs/Cargo.toml]: sigh, I actually considered making a similar change in the past but found it too destructive of a thing to do and found other solutions. Was very surprised when I saw someone else ended up doing this anyway :upside_down_face:

Comment (jdonszelmann) [reply compiler/rustc_lint_defs/Cargo.toml]: I'll move that some day in another PR

Comment (joshtriplett) [reply compiler/rustc_lint_defs/Cargo.toml]: `DefPathHash` is from `rustc_span` and can be imported from there (and `rustc_lint_defs` was already doing so). Please do leave that, so that it's easier to re-disentangle later.

But yeah, `AttributeLintKind` can't really move.

`BuiltinLintDiag` is *really* proving to be a pain in terms of bottlenecking the build, with dependencies *from* many invocations and *to* many types. I suspect the right fix for that might involve a `dyn Trait`.

File: compiler/rustc_lint_defs/src/lib.rs [hunk 21]
```diff
@@ -9,9 +9,10 @@ use rustc_data_structures::stable_hasher::{
     HashStable, StableCompare, StableHasher, ToStableHashKey,
 };
 use rustc_error_messages::{DiagArgValue, DiagMessage, IntoDiagArg, MultiSpan};
-use rustc_hir_id::{HashStableContext, HirId, ItemLocalId};
+use rustc_hir::def_id::DefPathHash;
+use rustc_hir::lints::AttributeLintKind;
+use rustc_hir::{HashStableContext, HirId, ItemLocalId};
 use rustc_macros::{Decodable, Encodable, HashStable_Generic};
-use rustc_span::def_id::DefPathHash;
```
Comment (joshtriplett) [inline compiler/rustc_lint_defs/src/lib.rs]: Please leave `DefPathHash` imported from `rustc_span`, and `HashStableContext, HirId, ItemLocalId` imported from `rustc_hir_id`, so that only `AttributeLintKind` is imported from `rustc_hir`.

File: compiler/rustc_lint_defs/Cargo.toml (hunk 13 above)
Comment (joshtriplett) [reply compiler/rustc_lint_defs/Cargo.toml]: I wrote a PR to add the necessary infrastructure to use a `dyn Trait` and avoid requiring a `BuiltinLintDiag` variant in order to buffer a lint: https://github.com/rust-lang/rust/pull/145747

File: tests/ui/lint/unused/unused-attr-duplicate.stderr [hunk 22]
```diff
@@ -1,306 +1,320 @@
...
    |
 LL | #![deny(unused_attributes)]
    |         ^^^^^^^^^^^^^^^^^
 
 error: unused attribute
-  --> $DIR/unused-attr-duplicate.rs:14:1
+  --> $DIR/unused-attr-duplicate.rs:37:1
    |
-LL | #![crate_name = "unused_attr_duplicate2"]
-   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove this attribute
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/unused-attr-duplicate.stderr:22]: this error is moved up a bit

File: tests/ui/lint/unused/unused-attr-duplicate.stderr [hunk 23]
```diff
@@ -1,306 +1,320 @@
...
+   |
+LL | #![crate_name = "unused_attr_duplicate2"]
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove this attribute
+   |
+note: attribute also specified here
+  --> $DIR/unused-attr-duplicate.rs:13:1
+   |
+LL | #![crate_name = "unused_attr_duplicate"]
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/unused-attr-duplicate.stderr:304]: this error is emitted twice, known problem (see comment in code file)

File: tests/ui/lint/unused/unused_attributes-must_use.fixed [hunk 24]
```diff
@@ -66,6 +66,8 @@ extern "Rust" {
 }
 
  //~ ERROR unused attribute
+//~^ ERROR `#[must_use]` attribute cannot be used on macro calls
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/unused_attributes-must_use.fixed:69]: this is a funny one. This PR doesn't just add crate_name, it also makes lints during early parsing possible. Another recent change that landed was attribute validation using the new parser infrastructure. So, the timeline:

1. we completely ignored the fact that must_use isn't compatible with macros
2. new validation, we started noticing this and producing this lint but ignored it when parsing early. Attributes on macros are always parsed early, not late, so you never saw this lint
3. now with this PR we emit early lints and find this lint

note, this is a warning, not an error. Only in this file it's an error because of the lint annotations at the top of this file. This is not a breaking change, this is an expected change that was just silently ignored before this PR

File: tests/ui/lint/unused/unused_attributes-must_use.stderr [hunk 25]
```diff
@@ -1,20 +1,29 @@
...
-   | ^^^^^^^^^^
+   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+   = help: `#[must_use]` can be applied to functions, data types, unions, and traits
 note: the lint level is defined here
   --> $DIR/unused_attributes-must_use.rs:4:9
    |
 LL | #![deny(unused_attributes, unused_must_use)]
    |         ^^^^^^^^^^^^^^^^^
 
+error: unused attribute `must_use`
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/unused_attributes-must_use.stderr:15]: same

File: compiler/rustc_errors/src/lib.rs
Comment (jdonszelmann) [reply compiler/rustc_errors/src/lib.rs:1]: nope, joshes canges made it unnecessary hehe

File: compiler/rustc_lint_defs/Cargo.toml (hunk 13 above)
Comment (jdonszelmann) [reply compiler/rustc_lint_defs/Cargo.toml]: fixed this, lint_defs is unmodified now

File: compiler/rustc_interface/src/passes.rs (hunk 20 above)
Comment (jdonszelmann) [reply compiler/rustc_interface/src/passes.rs]: I'll just leave the comment. It turns out that with how fatal errors work this is extraordinarily hard to do. It'd mean that every single attribute parser needs to become generic over its emission guarantee.

File: compiler/rustc_attr_parsing/src/attributes/crate_level.rs (hunk 14 above)
Comment (jdonszelmann) [reply compiler/rustc_attr_parsing/src/attributes/crate_level.rs:24]: this gives a warning that it's not used as a crate-level attribute

File: tests/ui/lint/unused/unused-attr-duplicate.rs
Comment (jdonszelmann) [reply tests/ui/lint/unused/unused-attr-duplicate.rs:1]: regression tests added, plus an ICE on stable fixed.

File: compiler/rustc_attr_parsing/src/parser.rs [hunk 26]
```diff
@@ -361,12 +362,8 @@ fn expr_to_lit(
         //   the error because an earlier error will have already
         //   been reported.
         let msg = "attribute value must be a literal";
-        let mut err = psess.dcx().struct_span_err(span, msg);
```
Comment (jdonszelmann) [inline compiler/rustc_attr_parsing/src/parser.rs:364]: there's a subtle bug in this version, fixed in my last commit. When an expression in an attribute is a macro, and the macro expands to a literal, and we parse an attribute with ShouldEmit::Nothing, we would delay that as a bug expecting a second parse to emit the error. However, when  the macro then expands to a literal, we don't hit the same codepath and we never emit an error about this. The delayed bug turns into an ICE.

A very similar problem was happening in February already (https://github.com/rust-lang/rust/issues/137687) which was recognized and even a backport was made for it. However, in later versions it *still* made it to stable. 

The last commit of this PR adds tests for these cases and fixes this by, when we expect a literal, but have ShouldEmit::Nothing, we *don't* delay a bug, instead we do nothing. This is correct because if the macro indeed turns into a literal, the second parse might very well be correct. We shouldn't have delayed a bug at all.

Specifically for crate_name, we parse with ShouldEmit::EarlyFatal so when it cares about this being a literal, it will error about it as it should.

File: tests/ui/resolve/path-attr-in-const-block.stderr [hunk 27]
```diff
@@ -4,5 +4,11 @@ error: cannot find macro `foo` in this scope
 LL |         #![path = foo!()]
    |                   ^^^
 
-error: aborting due to 1 previous error
+error: attribute value must be a literal
+  --> $DIR/path-attr-in-const-block.rs:6:19
+   |
+LL |         #![path = foo!()]
```
Comment (jdonszelmann) [inline tests/ui/resolve/path-attr-in-const-block.stderr:10]: extra error, but this is correct/expected. bonus!

File: tests/ui/lint/unused/concat-in-crate-deprecated-issue-137687.rs [hunk 28]
```diff
@@ -0,0 +1,6 @@
+//@ check-pass
+#[deprecated = concat !()]
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/concat-in-crate-deprecated-issue-137687.rs:2]: regression test for a new case of https://github.com/rust-lang/rust/issues/137687

Comment (jdonszelmann) [reply tests/ui/lint/unused/concat-in-crate-deprecated-issue-137687.rs:2]: ICE on stable currently: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=aea39cc8b7e80959b032d48976fe98fa

File: tests/ui/lint/unused/concat-in-crate-name-issue-137687.rs [hunk 29]
```diff
@@ -0,0 +1,9 @@
+#![deny(unused)]
+
+#[crate_name = concat !()]
```
Comment (jdonszelmann) [inline tests/ui/lint/unused/concat-in-crate-name-issue-137687.rs:3]: regression test for https://github.com/rust-lang/rust/issues/137687 (ICEs on stable currently: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=fc3557244535c7ed2a625b5741cc6e5f)

**Comment by jhpratt** [comment]
merge conflicts

@bors r-

**Comment by jdonszelmann** [comment]
yay, finally!
