### PR TITLE
Highlight and simplify mismatched types

### LINKED ISSUE #21025: Type mismatch error should have spans if it's too long
```
error: mismatched types: expected `session_types::Session<session_types::Cap<(), session_types::Rec<session_types::Offer<_, session_types::Rcv<collections::string::String, session_types::Choose<session_types::Snd<_, _>, session_types::Snd<_, session_types::Offer<_, session_types::Rcv<collections::string::String, session_types::Choose<session_types::Snd<(), _>, session_types::Snd<_, session_types::Rec<session_types::Offer<_, session_types::Offer<_, session_types::Snd<collections::string::String, session_types::Eps>>>>>>>>>>>>>>, (), _>`, found `session_types::Session<session_types::Cap<(), session_types::Rec<session_types::Offer<session_types::Snd<collections::string::String, session_types::Eps>, session_types::Rcv<collections::string::String, session_types::Choose<session_types::Snd<collections::string::String, session_types::Var<session_types::Z>>, session_types::Snd<collections::string::String, session_types::Offer<session_types::Snd<collections::string::String, session_types::Eps>, session_types::Rcv<collections::string::String, session_types::Choose<session_types::Snd<collections::string::String, session_types::Var<session_types::Z>>, session_types::Snd<collections::string::String, session_types::Rec<session_types::Offer<session_types::Snd<isize, session_types::Snd<isize, session_types::Var<session_types::Z>>>, session_types::Offer<session_types::Rcv<isize, session_types::Choose<session_types::Snd<collections::string::String, session_types::Snd<collections::string::String, session_types::Var<session_types::Z>>>, session_types::Snd<collections::string::String, session_types::Var<session_types::Z>>>>, session_types::Snd<collections::string::String, session_types::Eps>>>>>>>>>>>>>>, (), ()>` (expected (), found struct collections::string::String) 
```

It would be useful if there was a note as to where the `()` and `String` from `(expected (), found struct collections::string::String)` were for large types.

An additional note that's shown when the error report is above x (300?) characters which highlights the mismatched types (using something like our `^~~~~~` for code spans) would be useful.

### LINKED ISSUE #40186: Improve output of E0271
This error is encountered often with futures and tokio, where a returned future has an associated type that doesn't match the expected return type.

An example of current behavior:

```
error[E0271]: type mismatch resolving `<futures::AndThen<futures::stream::Fold<futures::stream::MapErr<hyper::Body, [closure@src/consumer/pinger.rs:100:41: 107:18 uri:_, request_type:_, correlation_id:_, tx:_, event:_]>, [closure@src/consumer/pinger.rs:107:35: 110:18], futures::FutureResult<std::vec::Vec<u8>, futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>>, std::vec::Vec<u8>>, futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>, [closure@src/consumer/pinger.rs:110:29: 127:18 timer:_, status_code:_, response_status:_, uri:_, tx:_, event:_, headers:_, request_type:_, correlation_id:_]> as futures::IntoFuture>::Error == futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>`
   |
16 |     Box::new(
   |     ^ expected futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>, found struct `io::Error`
   |
   = note: expected type `futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>`
   = note:    found type `io::Error`
   = note: required for the cast to the object type `Future<Error=futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>> + 'static`
```

And a playpen of a the current behavior (though the error is much smaller): https://is.gd/iigJ2p

A message like this pushes the actionable information down several lines. It may help to instead, output something like this:

```
error[E0271]: type mismatch resolving `<futures::AndThen<...>::Error`
   |
16 |     Box::new(
   |     ^ expected futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>, found struct `io::Error`
   |
   = note: expected type `futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>`
   = note:    found type `io::Error`
   = note: required for the cast to the object type `Future<Error=futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>> + 'static`
   = note: full type is `<futures::AndThen<futures::stream::Fold<futures::stream::MapErr<hyper::Body, [closure@src/consumer/pinger.rs:100:41: 107:18 uri:_, request_type:_, correlation_id:_, tx:_, event:_]>, [closure@src/consumer/pinger.rs:107:35: 110:18], futures::FutureResult<std::vec::Vec<u8>, futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>>, std::vec::Vec<u8>>, futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>, [closure@src/consumer/pinger.rs:110:29: 127:18 timer:_, status_code:_, response_status:_, uri:_, tx:_, event:_, headers:_, request_type:_, correlation_id:_]> as futures::IntoFuture>::Error == futures::sink::Send<futures::sync::mpsc::Sender<(events::http_request_event::HttpRequestEvent, std::result::Result<consumer::pinger::HttpResult, consumer::pinger::HttpResult>)>>`
```

Additionally, it might be even clearer to omit some of the type parameters (leaving enough to differentiate) in the 'expected' and 'found' notes, leaving the full type for the bottom note. 

```
error[E0271]: type mismatch resolving `<futures::AndThen<...>::Error`
   |
16 |     Box::new(
   |     ^ expected futures::sink::Send<...>, found struct `io::Error`
   |
   = note: expected type `futures::sink::Send<...>`
   = note:    found type `io::Error`
```

cc @eddyb

### PR DESCRIPTION
**Pull request by estebank**
Shorten mismatched types errors by replacing subtypes that are not
different with `_`, and highlighting only the subtypes that are
different.

Given a file

```rust
struct X<T1, T2> {
    x: T1,
    y: T2,
}

fn foo() -> X<X<String, String>, String> {
    X { x: X {x: "".to_string(), y: 2}, y: "".to_string()}
}

fn bar() -> Option<String> {
    "".to_string()
}
```

provide the following output

```rust
error[E0308]: mismatched types
  --> file.rs:6:5
   |
 6 |     X { x: X {x: "".to_string(), y: 2}, y: "".to_string()}
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found {integer}
   |
   = note: expected type `X<X<_, std::string::String>, _>`
                                 ^^^^^^^^^^^^^^^^^^^   // < highlighted
              found type `X<X<_, {integer}>, _>`
                                 ^^^^^^^^^             // < highlighted

error[E0308]: mismatched types
  --> file.rs:6:5
   |
10 |     "".to_string()
   |     ^^^^^^^^^^^^^^ expected struct `std::option::Option`, found `std::string::String`
   |
   = note: expected type `Option<std::string::String>`
                          ^^^^^^^                   ^  // < highlighted
              found type `std::string::String`
```

Fix #21025. Re: #40186. Follow up to #39906.

I'm looking to change how this output is accomplished so that it doesn't create list of strings to pass around, but rather add an elided `Ty` placeholder, and use the same string formatting for normal types. I'll be doing that soonish.

r? @nikomatsakis

### CODE REVIEW

**Comment by estebank** [comment]
Visual output:

**Comment by arielb1** [comment]
@estebank 
Shouldn't the "found type `std::string::String`" be highlighted as well?

**Comment by estebank** [comment]
It only highlights differing parts, while dimming the parts that are the same. In that case, only the `std::option::Option<...>` part is relevant to the error. May be we can incorporate the elision logic without any highlighting change for the "composition" case?

**Comment by arielb1** [comment]
@estebank 

I mean, I expected:
```

note: expected type `std::option::Option<std::string::String>`
                     ^^^^^^^^^^^^^^^^^^^^                   ^
      found type    `std::string::String`
                     ^^^^^^^^^^^^^^^^^^^
```

File: src/librustc/infer/error_reporting/mod.rs [hunk 1]
```diff
@@ -365,6 +365,257 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+    /// For the following code:
+    ///
+    /// ```norun
+    /// let x: Foo<Bar<Qux> = foo::<Bar<Qux>>();
+    /// ```
+    ///
+    /// The type error output will behave in the following way:
+    ///
+    /// ```text
+    /// Foo<Bar<Qux>
```
Comment (arielb1) [inline src/librustc/infer/error_reporting/mod.rs]: syntax error: mismatched parentheses

File: src/librustc/infer/error_reporting/mod.rs [hunk 2]
```diff
@@ -365,6 +365,257 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
         }
     }
 
+    /// Given that `other_ty` is the same as a type argument for `name` in `sub`, populate `value`
+    /// highlighting `name` and every type argument that isn't at `pos` (which is `other_ty`), and
+    /// populate `other_value` with `other_ty`.
+    ///
+    /// ```text
+    /// Foo<Bar<Qux>
```
Comment (arielb1) [inline src/librustc/infer/error_reporting/mod.rs]: syntax error: mismatched parentheses

File: src/librustc_errors/diagnostic.rs [hunk 3]
```diff
@@ -35,6 +35,46 @@ pub struct SubDiagnostic {
     pub render_span: Option<RenderSpan>,
 }
 
+#[derive(PartialEq, Eq)]
```
Comment (arielb1) [inline src/librustc_errors/diagnostic.rs]: Call this `StyledString` or something?

File: src/librustc/infer/error_reporting/mod.rs [hunk 4]
```diff
@@ -365,6 +365,257 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                    //         |   |
+                    //         |   elided as they were the same
+                    //         not elided, they were different
+                    let lifetimes = sub1.regions().zip(sub2.regions());
+                    for (i, lifetimes) in lifetimes.enumerate() {
+                        let l1 = lifetime_display(lifetimes.0);
+                        let l2 = lifetime_display(lifetimes.1);
+                        if l1 == l2 {
+                            values.0.push_normal("'_");
+                            values.1.push_normal("'_");
```
Comment (nikomatsakis) [inline src/librustc/infer/error_reporting/mod.rs]: Unlike `_`, this is not legal syntax for a user to type, but I guess that's ok. Not sure what else to use, in any case.

File: src/test/ui/mismatched_types/abridged.stderr [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+   = help: here are some functions which might fulfill your needs:
+           - .unwrap()
+
+error[E0308]: mismatched types
+  --> $DIR/abridged.rs:30:5
+   |
+30 |     Foo { bar: 1 }
+   |     ^^^^^^^^^^^^^^ expected enum `std::option::Option`, found struct `Foo`
+   |
+   = note: expected type `std::option::Option<Foo>`
```
Comment (nikomatsakis) [inline src/test/ui/mismatched_types/abridged.stderr]: too bad we lose the highlighting here, but I don't really know how to fix that

**Review by nikomatsakis — APPROVED** [review]
r=me modulo test failures; @arielb1's thoughts on underlining seem potentially fine, but I could go either way (and even if we did want to do it, I'd be fine w/ leaving it for a later PR).

**Comment by nikomatsakis** [comment]
I see @arielb1 also posted some other suggestions that seem potentially good; e.g. using `StyledString` or what have you. I don't have a strong opinion. This didn't seem like a lot of code and it read fairly easily (thanks @estebank for the comments, the code seemed pretty easy to understand this time) but DRYer is always better.

File: src/librustc/infer/error_reporting/mod.rs [hunk 6]
```diff
@@ -365,6 +365,257 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+
+    /// Compare two given types, eliding parts that are the same between them and highlighting
+    /// relevant differences, and return two representation of those types for highlighted printing.
+    fn cmp(&self, t1: ty::Ty<'tcx>, t2: ty::Ty<'tcx>) -> (TypeString, TypeString) {
+        match (&t1.sty, &t2.sty) {
+            (&ty::TyAdt(def1, sub1), &ty::TyAdt(def2, sub2)) => {
+                let mut values: (TypeString, TypeString) = (TypeString::new(), TypeString::new());
+                let path1 = self.tcx.item_path_str(def1.did.clone());
+                let path2 = self.tcx.item_path_str(def2.did.clone());
+                if path1 == path2 {
```
Comment (arielb1) [inline src/librustc/infer/error_reporting/mod.rs]: compare the dids?

File: src/librustc/infer/error_reporting/mod.rs (hunk 1 above)
Comment (estebank) [inline src/librustc/infer/error_reporting/mod.rs]: Fixed.

File: src/librustc/infer/error_reporting/mod.rs (hunk 2 above)
Comment (estebank) [inline src/librustc/infer/error_reporting/mod.rs]: Fixed.

File: src/librustc/infer/error_reporting/mod.rs (hunk 4 above)
Comment (estebank) [inline src/librustc/infer/error_reporting/mod.rs]: I agree with your reasoning. I followed this path given that the compiler already has diagnostics that show `'_` in some cases.

File: src/test/ui/mismatched_types/abridged.stderr (hunk 5 above)
Comment (estebank) [inline src/test/ui/mismatched_types/abridged.stderr]: Yeah... I've been thinking that we could expand ui errors to have a mode where ANSI escape codes are kept (`.stderr_full`? A comment flag in the `.rs` test file?).

File: src/librustc/infer/error_reporting/mod.rs (hunk 6 above)
Comment (estebank) [inline src/librustc/infer/error_reporting/mod.rs]: Done.

Comment (nikomatsakis) [inline src/librustc/infer/error_reporting/mod.rs]: yes, that seems better (@estebank -- just change to `if def1.did == def2.did {`)

File: src/librustc_errors/diagnostic.rs (hunk 3 above)
Comment (estebank) [inline src/librustc_errors/diagnostic.rs]: Done.

**Comment by estebank** [comment]
@nikomatsakis I believe I addressed all the points (except [the highlighting case brought up](https://github.com/rust-lang/rust/pull/41205#issuecomment-293247998) by @arielb1), as well as fixed a small presentational bug that was left from when I was first preparing this code.
