### PR TITLE
Fix json tuple struct enum variant 

### LINKED ISSUE #87887: `cargo rustdoc -- --output-format json` now says a tuple variant is a struct variant
Note the current type of `Variant` in rustdoc-json-types:

https://github.com/rust-lang/rust/blob/eaf6f463599df1f18da94a6965e216ea15795417/src/rustdoc-json-types/lib.rs#L271-L275

### Code

I tried this code:

```rust
pub enum MyEnum {
    Variant(MyStruct),
}

pub struct MyStruct {
}
```

And ran this:

```
cargo rustdoc -- --output-format json -Z unstable-options 
```

I expected to see this happen (or something along these lines saying it's a tuple variant):

```json
    "0:3": {
      "id": "0:3",
      "crate_id": 0,
      "name": "MyEnum",
      "span": { "filename": "src\\lib.rs", "begin": [1, 0], "end": [3, 1] },
      "visibility": "public",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "enum",
      "inner": {
        "generics": { "params": [], "where_predicates": [] },
        "variants_stripped": false,
        "variants": ["0:4"],
        "impls": [
          "F0:0",
          "F0:1",
          "F0:2",
          "F0:4",
          "F0:5",
          "F0:6",
          "F0:7",
          "F0:8",
          "F0:9",
          "F0:10",
          "F0:11",
          "F0:12"
        ]
      }
    },
    "0:4": {
      "id": "0:4",
      "crate_id": 0,
      "name": "Variant",
      "span": { "filename": "src\\lib.rs", "begin": [2, 4], "end": [2, 21] },
      "visibility": "default",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "variant",
      "inner": {
        "variant_kind": "tuple",
        "variant_inner": [
          {
            "kind": "resolved_path",
            "inner": {
              "name": "MyStruct",
              "id": "0:7",
              "args": { "angle_bracketed": { "args": [], "bindings": [] } },
              "param_names": []
            }
          }
        ]
      }
    }
```

Instead, this happened:

```json
    "0:3": {
      "id": "0:3",
      "crate_id": 0,
      "name": "MyEnum",
      "span": { "filename": "src\\lib.rs", "begin": [1, 0], "end": [3, 1] },
      "visibility": "public",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "enum",
      "inner": {
        "generics": { "params": [], "where_predicates": [] },
        "variants_stripped": false,
        "variants": ["0:4"],
        "impls": [
          "a:2:2881-0:3",
          "a:2:2893-0:3",
          "a:2:2922-0:3",
          "a:1:5759-0:3",
          "a:1:5760-0:3",
          "b:2:2814-0:3",
          "b:2:2810-0:3",
          "b:2:2825-0:3",
          "b:2:2820-0:3",
          "b:2:2486-0:3",
          "b:2:2489-0:3",
          "b:2:3546-0:3"
        ]
      }
    },
    "0:4": {
      "id": "0:4",
      "crate_id": 0,
      "name": "Variant",
      "span": { "filename": "src\\lib.rs", "begin": [2, 4], "end": [2, 21] },
      "visibility": "default",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "variant",
      "inner": { "variant_kind": "struct", "variant_inner": ["0:6"] }
    },
```

### Another Example

Here's a more complicated example:

```rust
pub enum MyEnum {
    Variant(MyStruct<String>, MyStruct<String>),
}

pub struct MyStruct<T> {
    pub value: T,
}
```

Outputs:

```json
    "0:3": {
      "id": "0:3",
      "crate_id": 0,
      "name": "MyEnum",
      "span": { "filename": "src\\lib.rs", "begin": [1, 0], "end": [3, 1] },
      "visibility": "public",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "enum",
      "inner": {
        "generics": { "params": [], "where_predicates": [] },
        "variants_stripped": false,
        "variants": ["0:4"],
        "impls": [
          "a:2:2881-0:3",
          "a:2:2893-0:3",
          "a:2:2922-0:3",
          "a:1:5759-0:3",
          "a:1:5760-0:3",
          "b:2:2814-0:3",
          "b:2:2810-0:3",
          "b:2:2825-0:3",
          "b:2:2820-0:3",
          "b:2:2486-0:3",
          "b:2:2489-0:3",
          "b:2:3546-0:3"
        ]
      }
    },
    "0:4": {
      "id": "0:4",
      "crate_id": 0,
      "name": "Variant",
      "span": { "filename": "src\\lib.rs", "begin": [2, 4], "end": [2, 47] },
      "visibility": "default",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "variant",
      "inner": { "variant_kind": "struct", "variant_inner": ["0:6", "0:7"] }
    },
    "0:6": {
      "id": "0:6",
      "crate_id": 0,
      "name": "0",
      "span": { "filename": "src\\lib.rs", "begin": [2, 12], "end": [2, 28] },
      "visibility": "default",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "struct_field",
      "inner": {
        "kind": "resolved_path",
        "inner": {
          "name": "MyStruct",
          "id": "0:8",
          "args": {
            "angle_bracketed": {
              "args": [
                {
                  "type": {
                    "kind": "resolved_path",
                    "inner": {
                      "name": "String",
                      "id": "5:7431",
                      "args": {
                        "angle_bracketed": { "args": [], "bindings": [] }
                      },
                      "param_names": []
                    }
                  }
                }
              ],
              "bindings": []
            }
          },
          "param_names": []
        }
      }
    },
    "0:7": {
      "id": "0:7",
      "crate_id": 0,
      "name": "1",
      "span": { "filename": "src\\lib.rs", "begin": [2, 30], "end": [2, 46] },
      "visibility": "default",
      "docs": null,
      "links": {},
      "attrs": [],
      "deprecation": null,
      "kind": "struct_field",
      "inner": {
        "kind": "resolved_path",
        "inner": {
          "name": "MyStruct",
          "id": "0:8",
          "args": {
            "angle_bracketed": {
              "args": [
                {
                  "type": {
                    "kind": "resolved_path",
                    "inner": {
                      "name": "String",
                      "id": "5:7431",
                      "args": {
                        "angle_bracketed": { "args": [], "bindings": [] }
                      },
                      "param_names": []
                    }
                  }
                }
              ],
              "bindings": []
            }
          },
          "param_names": []
        }
      }
    }
```

### Version it worked on

It most recently worked on: nightly-2021-06-27 -- I did not do any tests for the specific version it started failing in

### Version with regression

`rustc +nightly --version --verbose`:
```
rustc 1.56.0-nightly (ad981d58e 2021-08-08)
binary: rustc
commit-hash: ad981d58e1ca16bcf4072577934630deb11c5e14
commit-date: 2021-08-08
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #87887.

cc @dsherret @camelid

r? @notriddle

### CODE REVIEW

**Review by notriddle — APPROVED** [review]

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -1937,7 +1937,7 @@ crate struct Enum {
 #[derive(Clone, Debug)]
 crate enum Variant {
     CLike,
-    Tuple(Vec<Type>),
+    Tuple(VariantStruct),
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:1940]: I guess it works as well. :)

File: src/librustdoc/clean/mod.rs [hunk 2]
```diff
@@ -1707,9 +1707,22 @@ impl Clean<Item> for ty::VariantDef {
     fn clean(&self, cx: &mut DocContext<'_>) -> Item {
         let kind = match self.ctor_kind {
             CtorKind::Const => Variant::CLike,
-            CtorKind::Fn => Variant::Tuple(
-                self.fields.iter().map(|f| cx.tcx.type_of(f.did).clean(cx)).collect(),
-            ),
+            CtorKind::Fn => Variant::Tuple(VariantStruct {
+                struct_type: CtorKind::Fictive,
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:1711]: Indeed, good catch!

File: src/librustdoc/html/render/print_item.rs [hunk 3]
```diff
@@ -937,6 +937,20 @@ fn item_union(w: &mut Buffer, cx: &Context<'_>, it: &clean::Item, s: &clean::Uni
     document_type_layout(w, cx, def_id);
 }
 
+fn print_tuple_struct_fields(w: &mut Buffer, cx: &Context<'_>, s: &clean::VariantStruct) {
+    for (i, ty) in s
+        .fields
+        .iter()
+        .filter_map(|f| if let clean::StructFieldItem(ref ty) = *f.kind { Some(ty) } else { None })
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/print_item.rs:944]: It's used to get the wrapped `ty` inside. I'll rework the code and add an `unreachable!`.

File: src/librustdoc/clean/mod.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/librustdoc/clean/mod.rs:1711]: Well, since I'll remove the `VariantStruct` wrapper, I guess it won't be very important. :)

File: src/librustdoc/clean/types.rs [hunk 4]
```diff
@@ -715,6 +715,7 @@ impl ItemKind {
             StructItem(s) => s.fields.iter(),
             UnionItem(u) => u.fields.iter(),
             VariantItem(Variant::Struct(v)) => v.fields.iter(),
+            VariantItem(Variant::Tuple(v)) => v.iter(),
```
Comment (GuillaumeGomez) [inline src/librustdoc/clean/types.rs:718]: @camelid: I had to use a `Vec<Item>` because of this function.

**Comment by GuillaumeGomez** [comment]
Updated! I replaced the `VariantStruct` with a `Vec<Item>` (because it's needed in a function).

File: src/librustdoc/passes/stripper.rs [hunk 5]
```diff
@@ -94,7 +94,7 @@ impl<'a> DocFolder for Stripper<'a> {
             // implementations of traits are always public.
             clean::ImplItem(ref imp) if imp.trait_.is_some() => true,
             // Struct variant fields have inherited visibility
```
Comment (camelid) [inline src/librustdoc/passes/stripper.rs:96]: nit:

```suggestion
            // Variant fields have inherited visibility
```

File: src/librustdoc/html/render/print_item.rs [hunk 6]
```diff
@@ -1041,7 +1044,13 @@ fn item_enum(w: &mut Buffer, cx: &Context<'_>, it: &clean::Item, e: &clean::Enum
             document_non_exhaustive(w, variant);
 
             use crate::clean::Variant;
-            if let clean::VariantItem(Variant::Struct(ref s)) = *variant.kind {
+            if let Some((extra, fields)) = match *variant.kind {
+                clean::VariantItem(Variant::Struct(ref s)) => {
+                    Some((if s.struct_type == CtorKind::Fn { "Tuple " } else { "" }, &s.fields))
```
Comment (camelid) [inline src/librustdoc/html/render/print_item.rs:1049]: This `if` condition will always be false, right? Can you remove the `if`?

File: src/librustdoc/clean/types.rs (hunk 4 above)
Comment (camelid) [reply src/librustdoc/clean/types.rs:718]: Ok, that seems good enough for now 👍

File: src/librustdoc/html/render/print_item.rs (hunk 6 above)
Comment (GuillaumeGomez) [reply src/librustdoc/html/render/print_item.rs:1049]: I guess, I'll add an `unreachable`, just in case.

Comment (GuillaumeGomez) [reply src/librustdoc/html/render/print_item.rs]: It's better to simply move it actually.

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/fold.rs [hunk 7]
```diff
@@ -56,6 +56,10 @@ crate trait DocFolder: Sized {
                             || j.fields.iter().any(|f| f.is_stripped());
```
Comment (camelid) [inline src/librustdoc/fold.rs:56]: \[Self note (for future):\] We can probably remove this part because variant fields always have inherited visibility.

File: src/librustdoc/passes/stripper.rs [hunk 8]
```diff
@@ -93,8 +93,8 @@ impl<'a> DocFolder for Stripper<'a> {
 
             // implementations of traits are always public.
             clean::ImplItem(ref imp) if imp.trait_.is_some() => true,
-            // Struct variant fields have inherited visibility
-            clean::VariantItem(clean::Variant::Struct(..)) => true,
+            // Variant fields have inherited visibility
+            clean::VariantItem(clean::Variant::Struct(..) | clean::Variant::Tuple(..)) => true,
```
Comment (camelid) [inline src/librustdoc/passes/stripper.rs:97]: This seems like an unrelated—but still good—fix, right?

Comment (GuillaumeGomez) [reply src/librustdoc/passes/stripper.rs:97]: Ah indeed, didn't even pay attention. But yes, bug fix! :)

Comment (camelid) [reply src/librustdoc/passes/stripper.rs:97]: Or actually it shouldn't have any effect on behavior, but it *is* a performance fix :)
