### PR TITLE
use `require_lang_item` over `unwrap`.

### LINKED ISSUE #72099: Internal compiler error due to failed typecheck (on no_core)
Bad types can lead to an internal compiler error, rather than an error message when compiling. Only affects `no_core` on nightly.

## Code
```
#![feature(no_core, lang_items)]
#![no_core]

#[lang = "sized"]
trait Sized {}

fn foo() -> bool {
    ()
}
```

## Expected
```
error[E0308]: mismatched types
```

## Reality
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_typeck/check/demand.rs:637:35
```

## Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (9912925c2 2020-05-10)
binary: rustc
commit-hash: 9912925c254589f58338cb2993163e618475ff75
commit-date: 2020-05-10
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

Backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_typeck/check/demand.rs:637:35
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::panicking::panic
             at src/libcore/panicking.rs:52
  15: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt>::check_ref
  16: rustc_typeck::check::FnCtxt::suggest_deref_ref_or_into
  17: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt>::emit_coerce_suggestions
  18: rustc_typeck::check::coercion::CoerceMany<E>::coerce_inner
  19: rustc_typeck::check::FnCtxt::check_block_with_expected
  20: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  21: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  22: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  23: rustc_typeck::check::check_fn
  24: rustc_middle::ty::context::GlobalCtxt::enter_local
  25: rustc_typeck::check::typeck_tables_of
  26: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_tables_of>::compute
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_query_system::query::plumbing::get_query_impl
  29: rustc_query_system::query::plumbing::ensure_query_impl
  30: rustc_typeck::check::typeck_item_bodies
  31: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  33: rustc_query_system::query::plumbing::get_query_impl
  34: rustc_typeck::check_crate
  35: rustc_interface::passes::analysis
  36: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_data_structures::stack::ensure_sufficient_stack
  39: rustc_query_system::query::plumbing::get_query_impl
  40: rustc_middle::ty::context::tls::enter_global
  41: rustc_interface::interface::run_compiler_in_existing_thread_pool
  42: scoped_tls::ScopedKey<T>::set
  43: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (9912925c2 2020-05-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=1 -C llvm-args=--x86-asm-syntax=intel --crate-type rlib

query stack during panic:
#0 [typeck_tables_of] type-checking `foo`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

### PR DESCRIPTION
**Pull request by lcnr**
Does not yet replace all uses of `lang_items\(\)\.*\.unwrap\(\)`, as there are more
than I expected :sweat_smile: 

Fixes #72099 

r? @RalfJung

*edit: The goal of this this PR is to change ICE from missing lang items to a fatal error.*

### CODE REVIEW

File: src/librustc_mir/borrow_check/type_check/mod.rs [hunk 1]
```diff
@@ -1468,7 +1469,7 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
                 self.check_rvalue(body, rv, location);
                 if !self.tcx().features().unsized_locals {
                     let trait_ref = ty::TraitRef {
-                        def_id: tcx.lang_items().sized_trait().unwrap(),
+                        def_id: tcx.require_lang_item(SizedTraitLangItem, None),
```
Comment (RalfJung) [inline src/librustc_mir/borrow_check/type_check/mod.rs:1472]: Since we have a `stmt`, I think we can pass a meaningful span here instead of `None`.

Comment (RalfJung) [reply src/librustc_mir/borrow_check/type_check/mod.rs:1472]: In fact we can probably do better and use `self.last_span`, also most other places in this file.
(Found by inspecting what the `span_mirbug!` macro does.)

File: src/librustc_mir/transform/generator.rs [hunk 2]
```diff
@@ -1207,7 +1208,7 @@ impl<'tcx> MirPass<'tcx> for StateTransform {
         };
 
         // Compute GeneratorState<yield_ty, return_ty>
-        let state_did = tcx.lang_items().gen_state().unwrap();
+        let state_did = tcx.require_lang_item(GeneratorStateLangItem, None);
```
Comment (RalfJung) [inline src/librustc_mir/transform/generator.rs:1211]: We could use `body.span` here.

File: src/librustc_mir/transform/generator.rs [hunk 3]
```diff
@@ -381,7 +382,7 @@ fn make_generator_state_argument_indirect<'tcx>(tcx: TyCtxt<'tcx>, body: &mut Bo
 fn make_generator_state_argument_pinned<'tcx>(tcx: TyCtxt<'tcx>, body: &mut Body<'tcx>) {
     let ref_gen_ty = body.local_decls.raw[1].ty;
 
-    let pin_did = tcx.lang_items().pin_type().unwrap();
+    let pin_did = tcx.require_lang_item(PinTypeLangItem, None);
```
Comment (RalfJung) [inline src/librustc_mir/transform/generator.rs:385]: We could use `body.span` here.

**Comment by RalfJung** [comment]
Could you also cover the one that the issue was reported about?

https://github.com/rust-lang/rust/blob/3fe4dd2dda2826643c4ce4ee7307707a90e08d25/src/librustc_typeck/check/demand.rs#L637

**Comment by lcnr** [comment]
done

**Review by RalfJung — APPROVED** [review]
This LGTM. However, this is code that I am not familiar with, so I'd prefer if someone else also took a look. Cc @oli-obk @matthewjasper

**Comment by oli-obk** [comment]
Oh, that's a very good idea. I wonder if we can make `lang_items` private at some point and just have sensible wrappers like `require_lang_item`.

But we can address this in future work. For now:

@bors r+

**Comment by jonas-schievink** [comment]
This looks like a good `E-easy` contribution, so maybe open an issue for the follow-up work here?

**Comment by lcnr** [comment]
@jonas-schievink Opened https://github.com/rust-lang/rust/issues/72195 for this, not
sure what other labels apply there.
