### PR TITLE
Report unconstrained region in hidden types lazily

### LINKED ISSUE #264: opaque type uses with defining args, but failing member constraints error
```rust
struct Inv<'a>(*mut &'a ());
fn foo(f: impl FnOnce() -> Inv<'static>) -> Inv<'static> {
    f()
}

fn rpit() -> impl Sized {
    foo(|| rpit())
}
```
inside of the closure there's an `opaque = Inv<'unconstrained>` use. `'unconstrained` is equal to the external region `'1` so we member constraints don't lift it to `'static`.

That's fine, as there's a fully defining use in the parent body. However, MIR borrowck currently always expects defining uses to be fully defining if the opaque type args are.

We should not error in this case, but instead do it similarly to HIR typeck: https://github.com/rust-lang/rust/blob/370143facfb348ad3b29749c0393402d76b280c3/compiler/rustc_hir_typeck/src/opaque_types.rs#L200.

We want to use the same enum in MIR borrowck
```rust
#[derive(Copy, Clone, Debug)]
enum UsageKind<'tcx> {
    None,
    NonDefiningUse(OpaqueTypeKey<'tcx>, ProvisionalHiddenType<'tcx>),
    UnconstrainedHiddenType(ProvisionalHiddenType<'tcx>),
    HasDefiningUse(DefinitionSiteHiddenType<'tcx>),
}
```
and update the opaque type in the storage. We have to make sure to eagerly map the nll vars to named regions or `'erased` as the opaque type storage is shared by the different bodies (parent body + closures).

MIR borrowck should then have a pass at its end checking that all opaques are set to `HasDefiningUse` and only emit errors for `UnconstrainedHiddenType` there instead of doing so eagerly.

We also need to add tests for this, likely using TAIT as it's annoyingly easy to get additional uses of RPITs just because they're mentioned in the signature

### PR DESCRIPTION
**Pull request by adwinwhite**
Fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/264

I didn't copy the mechanism of HIR typeck as I found that we just need to be lax in the unconstrained region case.
It already ignores non-defining uses and invalid params.

About tests, I'm having trouble coming up with more complex ones. 🙁

This fixes `ukanren` and `codecrafters-redis-rust` but not rust-lang/rust#151322 and rust-lang/rust#151323.
I believe they are a [different problem](https://github.com/rust-lang/rust/issues/151322#issuecomment-3864656974).

r? @lcnr

### CODE REVIEW

File: tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+#[define_opaque(MultiUse1)]
+fn unconstrained_in_closure() -> MultiUse1 {
+    guide_closure_sig(|| unconstrained_in_closure());
+    mk_static()
+}
+
+type MultiUse2 = impl Sized;
+#[define_opaque(MultiUse2)]
+fn capture_different_universals_not_on_bounds<'a, 'b, 'c>(a: &'a i32, b: &'b i32, c: &'c i32)  {
```
Comment (adwinwhite) [inline tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs]: Just make sure that we report error for each invalid capture. 
In my other attempt, only one unconstrained error per opaque definition is reported.

Comment (lcnr) [reply tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs]: hmm, I personally don't actually think this is too important and we do only report one error in HIR typeck 🤔

Comment (lcnr) [reply tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs]: please move the check-pass regression test into a separate file

File: compiler/rustc_borrowck/src/root_cx.rs [hunk 2]
```diff
@@ -84,23 +87,38 @@ impl<'tcx> BorrowCheckRootCtxt<'tcx> {
...
+            &mut self.hidden_types,
+            &mut self.unconstrained_hidden_types,
+        );
+        for error in unexpected_region_errors {
+            let (def_id, error) = error.to_error();
+            let Some(result) = self.collect_region_constraints_results.get_mut(&def_id) else {
+                unreachable!("the body should depend on opaques type if it has opaque use");
+            };
+            result.deferred_opaque_type_errors.push(error);
+        }
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/root_cx.rs]: is there a reason you're return a list of errors instead of eagerly adding them t `deferred_opaque_type_errors` in `detect_unconstrained_hidden_types` (i guess then called `handle_unconstrained_hidden_types`)

File: compiler/rustc_borrowck/src/root_cx.rs [hunk 3]
```diff
@@ -27,6 +28,7 @@ pub(super) struct BorrowCheckRootCtxt<'tcx> {
     pub tcx: TyCtxt<'tcx>,
     root_def_id: LocalDefId,
     hidden_types: FxIndexMap<LocalDefId, ty::DefinitionSiteHiddenType<'tcx>>,
+    unconstrained_hidden_types: Vec<UnexpectedHiddenRegion<'tcx>>,
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/root_cx.rs]: comment please

File: compiler/rustc_borrowck/src/root_cx.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_borrowck/src/root_cx.rs]: also, why the `def_id` check here? 🤔 it's not immediately clear to me whether this assert is important. We could avoid some code if we don't check htis as the `def_id` is otherwise unused

**Review by lcnr — COMMENTED** [review]
I am slightly unhappy about having both a `hidden_types` and `unconstrained_hidden_types` field but think it's a fairly clean solution.

The alternative would be to change `hidden_types` to an enum with a variant for `unconstrained_hidden_types` (either a single one or a list), but I don't think that's necessarily better 🤔 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152218/035b01b794602d5861daa43ac792f372f8981ed7..a509e967f8e78e552fe80bf963c653e0e0f6c901)*

File: compiler/rustc_borrowck/src/root_cx.rs (hunk 2 above)
Comment (adwinwhite) [reply compiler/rustc_borrowck/src/root_cx.rs]: Ah, you're right. Eagerly adding the errors in `detect_unconstrained_hidden_types` is cleaner.


The `def_id` is needed because we need to insert error to the body where it originates from. The region var only makes sense in its own infcx. Yeah, I should have comments for this.

File: tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs [hunk 4]
```diff
@@ -0,0 +1,24 @@
+//@ check-pass
+//@ compile-flags: -Znext-solver
+
+// Some defining uses of opaque types can't constrain captured regions to universals.
+// Previouly, we eagerly report error in this case.
+// Now we report error only if there's no fully defining use from all bodies of the typeck root.
```
Comment (lcnr) [inline tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs:8]: link the issue this is a regression test for

File: tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+
+// Regression test for trait-system-refactor-initiative#264.
+//
+// Some defining uses of opaque types can't constrain captured regions to universals.
+// Previouly, we eagerly report error in this case.
+// Now we report error only if there's no fully defining use from all bodies of the typeck root.
+
+#![feature(type_alias_impl_trait)]
+
+struct Invar<'a>(*mut &'a ());
```
Comment (lcnr) [inline tests/ui/traits/next-solver/opaques/eventually-constrained-region.rs]:
```suggestion
struct Inv<'a>(*mut &'a ());
```
sorry, this is the convention we generally use and `Invar` is confusing to me. Please also change this test to use RPIT instead of tait

File: compiler/rustc_borrowck/src/region_infer/opaque_types/mod.rs [hunk 6]
```diff
@@ -570,6 +614,40 @@ pub(crate) fn apply_definition_site_hidden_types<'tcx>(
     errors
 }
 
+/// We handle `UnexpectedHiddenRegion` error lazily in the next solver.
+/// Hope that it can be resolved by another fully defining use, which may not exist.
+/// We detect eventually unconstrained region via this function after collecting defining uses from all
+/// bodies.
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/region_infer/opaque_types/mod.rs]:
```suggestion
/// We handle `UnexpectedHiddenRegion` error lazily in the next solver as
/// there may be a fully defining use in another body.
///
/// In case such a defining use does not exist, we register an error here.
```

**Review by lcnr — COMMENTED** [review]
nits, then r=me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/152218/7b25457166468840db16998f507296675f0e07a0..10301d5b42c3065b6f9cd5e5335fe06e2104c550)*
